### ISSUE TITLE
storage: goroutine leak in  TestSplitSnapshotRace_SplitWins

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10870] opened 2016-11-20 19:32 UTC
Found in https://teamcity.cockroachdb.com/viewLog.html?buildId=53438&buildTypeId=Cockroach_UnitTests

```
 <autogenerated>:10: Leaked goroutine: 
goroutine 25757 [chan receive]: github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds.func1(0xc420128f80, 0xc420619800, 0xc4200303e0, 0xc4200303e8) 
/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1370 +0x94 
created by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).beginCmds /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1376 +0x14c4
````

**Comment by tamird** [comment] 2016-11-20 19:37
Dupe of #10781.

**Closed by tamird** 2016-11-20 19:37 UTC
Labels: test-failure
