### ISSUE TITLE
kvserver: include latch owners in trace events

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#103721] opened 2023-05-22 15:44 UTC
It would be useful to know the txn ID of the latch holder when looking at latch waits in traces. Consider the below sequence, are the latch holders the same txn at different timestamps, or different writers waiting in line?

```
     1.030ms      0.027ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.900399117,0
     1.391ms      0.362ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.900765453,0
     3.892ms      2.501ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.904238139,0
     8.024ms      4.131ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.904563190,0
    10.630ms      2.606ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.905321443,0
    15.412ms      4.783ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.907133801,0
    17.967ms      2.555ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.908193464,0
    23.046ms      5.079ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.915571525,0
    25.900ms      2.854ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.917035078,0
    27.857ms      1.958ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.920719030,0
    30.613ms      2.756ms                event:kv/kvserver/spanlatch/manager.go:532 [n3,s3,r5463/5:/Table/148{4-5}] waiting to acquire write latch /Table/1484/1/0/0@1684463162.332100381,0, held by write latch /Table/1484/1/0/0@1684463161.922391976,0
```

Jira issue: CRDB-28157

**Comment by nvanbenschoten** [comment] 2023-11-16 19:25
Duplicate of https://github.com/cockroachdb/cockroach/issues/114601.

**Closed by nvanbenschoten** 2023-11-16 19:25 UTC
Labels: C-enhancement, A-kv-observability, T-kv
