### ISSUE TITLE
doctor: tool that fixes missing ParentID issue

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#57455] opened 2020-12-03 14:46 UTC
The missing ParentID issue is fairly well-understood: it means that the table is orphaned from a failed `DROP DATABASE CASCADE` statement and should be deleted. See #51782.

The proposed tool would delete the orphaned table(s) by creating a new database, reparenting the orphaned tables, and dropping the new database `CASCADE`.

**Comment by DGollings** [comment] 2020-12-14 13:46
So currently have this issue in production, one (ironically unimportant) orphan table that I just can't get rid off. 

At least not by dropping anything resembling that table anywhere. but as far as I can tell if I can't use any of the functions in #56937 unless I upgrade my prod cluster to a dev version (v2.21) nor does it look like a trivial fix (spent some time reading [repair_test.go](https://github.com/cockroachdb/cockroach/blob/v21.1.0-alpha.1/pkg/sql/tests/repair_test.go))

And to top it all off, I can't make backups, so can't just nuke and start again either.

So, luckily the issue is fairly well-understood, but the solution is also fairly undocumented :)

so, creating a database and dropping a new database is clear to me, but how do I reparent an orphaned table? Scouring the docs didn't really help too much (I assume its not `alter table convert to schema with parent`)

**Comment by ajwerner** [comment] 2020-12-14 15:01
For what it's worth, we've backported the repair functions to 20.2.3 which should be out this week. That should enable you to use the technique in that test (which is admittedly non-trivial). However, given that this is seemingly pressing, there are mechanisms to perform this repair without those functions. The fix is rather low-level and in that way scary, hence the desire to not officially document any sort of repair. I can help you to resolve the situation in the meantime.

Would you be able to create a new database for the purpose of the reparenting, then run the following queries and share them with me. They won't have any user data but will contain the structure of the unimportant table. Hope that that's okay. If you don't want to share the schemas publicly, you can share with me at ajwerner@cockroachlabs.com. 

```
CREATE DATABASE to_drop; -- create the database
SELECT * FROM system.namespace WHERE "parentID" = 0 AND name = "to_drop"; -- or whatever you called the database
SELECT id, encode(descriptor, 'hex') FROM system.descriptor WHERE "parentID" = <parentID from error message>; 
```

The parentID from the last query should come from an error message that looks like: 

`ERROR: table "..." has unknown ParentID <parentID of interest>`

**Comment by DGollings** [comment] 2020-12-14 15:51
luckily the table in question is just a Dutch zipcode dump, completely public. So might as well keep it that way:

`CREATE DATABASE to_drop`
`SELECT * FROM system.namespace WHERE "parentID" = 0 AND name = 'to_drop'`
>  parentID | parentSchemaID |  name   | id   
+----------+----------------+---------+-----+
         0 |              0 | to_drop | 409


Broken table:
`230 |             29 | nl_postcodes                      | 269`
error message complains about 230, but couldn't use that to select, I think the actual id is also fine?
`SELECT id, encode(descriptor, 'hex') FROM system.descriptor WHERE id = '269';`
>   269 | 0a91090a0c6e6c5f706f7374636f646573188d0220e60128023a0a08dfdfb5ceebedca8716422a0a02696410011a0b080e10001800300050861720002a1167656e5f72616e646f6d5f7575696428293000421e0a0a7374726161746e61616d10021a0a0807100018003000501920013000421e0a0a687569736e756d6d657210031a0a0807100018003000501920003000421e0a0a687569736c657474657210041a0a080710001800300050192001300042280a14687569736e756d6d6572746f65766f6567696e6710051a0a0807100018003000501920013000421c0a08706f7374636f646510061a0a0807100018003000501920003000421e0a0a776f6f6e706c6161747310071a0a0807100018003000501920003000421c0a0867656d65656e746510081a0a0807100018003000501920003000421d0a0970726f76696e63696510091a0a0807100018003000501920003000421d0a096f626a6563745f6964100a1a0a0807100018003000501920003000421f0a0b6f626a6563745f74797065100b1a0a0807100018003000501920003000421e0a0a6e6576656e6164726573100c1a0a080710001800300050192000300042160a0178100d1a0b080210401800300050bd052000300042160a0179100e1a0b080210401800300050bd0520003000421e0a096c6f6e676974756465100f1a0b080210401800300050bd0520003000421d0a086c6174697475646510101a0b080210401800300050bd0520003000481152330a077072696d6172791001180122026964300140004a10080010001a00200028003000380040005a007a0208008001008801005a680a246e6c5f706f7374636f6465735f706f7374636f64655f687569736e756d6d65725f696478100218002208706f7374636f6465220a687569736e756d6d6572300630033801400040004a10080010001a00200028003000380040005a007a0208008001008801005a9e010a3a6e6c5f706f7374636f6465735f67656d65656e74655f776f6f6e706c616174735f7374726161746e61616d5f687569736e756d6d65725f69647810031800220867656d65656e7465220a776f6f6e706c61617473220a7374726161746e61616d220a687569736e756d6d65723008300730023003380140004000400040004a10080010001a00200028003000380040005a007a02080080010088010060046a150a090a0561646d696e10020a080a04726f6f741002800101880103980100b201d5010a077072696d61727910001a0269641a0a7374726161746e61616d1a0a687569736e756d6d65721a0a687569736c65747465721a14687569736e756d6d6572746f65766f6567696e671a08706f7374636f64651a0a776f6f6e706c616174731a0867656d65656e74651a0970726f76696e6369651a096f626a6563745f69641a0b6f626a6563745f747970651a0a6e6576656e61647265731a01781a01791a096c6f6e6769747564651a086c61746974756465200120022003200420052006200720082009200a200b200c200d200e200f20102800b80101c20100e80100f2010408001200f801008002009202009a020a08dfdfb5ceebedca8716b20209696d706f7274696e67

**Comment by ajwerner** [comment] 2020-12-14 16:19
Okay, you'll need to run the following as root. It should fix the problem. Let me know if you run into any trouble.

```sql
INSERT INTO system.users VALUES ('node', NULL, true);
GRANT node TO root;
UPDATE system.descriptor SET descriptor = decode('0add0a0a0c6e6c5f706f7374636f646573188d0220990328033a0042320a02696410011a0d080e100018003000508617600020002a1167656e5f72616e646f6d5f757569642829300068007000780042260a0a7374726161746e61616d10021a0c0807100018003000501960002001300068007000780042260a0a687569736e756d6d657210031a0c0807100018003000501960002000300068007000780042260a0a687569736c657474657210041a0c0807100018003000501960002001300068007000780042300a14687569736e756d6d6572746f65766f6567696e6710051a0c0807100018003000501960002001300068007000780042240a08706f7374636f646510061a0c0807100018003000501960002000300068007000780042260a0a776f6f6e706c6161747310071a0c0807100018003000501960002000300068007000780042240a0867656d65656e746510081a0c0807100018003000501960002000300068007000780042250a0970726f76696e63696510091a0c0807100018003000501960002000300068007000780042250a096f626a6563745f6964100a1a0c0807100018003000501960002000300068007000780042270a0b6f626a6563745f74797065100b1a0c0807100018003000501960002000300068007000780042260a0a6e6576656e6164726573100c1a0c08071000180030005019600020003000680070007800421e0a0178100d1a0d080210401800300050bd05600020003000680070007800421e0a0179100e1a0d080210401800300050bd0560002000300068007000780042260a096c6f6e676974756465100f1a0d080210401800300050bd0560002000300068007000780042250a086c6174697475646510101a0d080210401800300050bd056000200030006800700078004811524b0a077072696d6172791001180122026964300140004a10080010001a00200028003000380040005a007a020800800100880100900100980100a20106080012001800a80100b20100ba01005a80010a246e6c5f706f7374636f6465735f706f7374636f64655f687569736e756d6d65725f696478100218002208706f7374636f6465220a687569736e756d6d6572300630033801400040004a10080010001a00200028003000380040005a007a020800800100880100900100980100a20106080012001800a80100b20100ba01005ab6010a3a6e6c5f706f7374636f6465735f67656d65656e74655f776f6f6e706c616174735f7374726161746e61616d5f687569736e756d6d65725f69647810031800220867656d65656e7465220a776f6f6e706c61617473220a7374726161746e61616d220a687569736e756d6d65723008300730023003380140004000400040004a10080010001a00200028003000380040005a007a020800800100880100900100980100a20106080012001800a80100b20100ba010060046a190a090a0561646d696e10020a080a04726f6f74100212001800800101880103980100b201d5010a077072696d61727910001a0269641a0a7374726161746e61616d1a0a687569736e756d6d65721a0a687569736c65747465721a14687569736e756d6d6572746f65766f6567696e671a08706f7374636f64651a0a776f6f6e706c616174731a0867656d65656e74651a0970726f76696e6369651a096f626a6563745f69641a0b6f626a6563745f747970651a0a6e6576656e61647265731a01781a01791a096c6f6e6769747564651a086c61746974756465200120022003200420052006200720082009200a200b200c200d200e200f20102800b80101c20100e80100f2010408001200f801008002009202009a020a08dfdfb5ceebedca8716b20209696d706f7274696e67b80200c00200c80200', 'hex') WHERE id = 269;
UPDATE system.namespace SET "parentID" = 409 WHERE id = 269;
REVOKE node FROM root;
DELETE FROM system.users WHERE username = 'node';
DROP DATABASE to_drop CASCADE;
```

**Comment by DGollings** [comment] 2020-12-14 16:23
worked, thanks :)

for anyone reading this, I don't think what I sent you (in 'encode') is the same as what's in 'decode', so no copy&paste fix for others, correct?

**Comment by ajwerner** [comment] 2020-12-14 16:28
Glad it worked!

> for anyone reading this, I don't think what I sent you (in 'encode') is the same as what's in 'decode', so no copy&paste fix for others, correct?

Correct, this command was custom-tailored to the information you sent. If others hit this before we have a real tool that's production ready, we can provide a fix. However, this issue stands in for us to create a more self-service approach. I'm not super keen on teaching the dark arts of manual descriptor repair as there's a lot that can go wrong and I worry that would open us up to bug reports that will be totally bewildering. Very soon we'll have repair functions in a released version (20.2.3) which will do a bit of sanity checking, leave a paper trail, and allow the logic to live in SQL rather than outside of the database.

**Comment by DGollings** [comment] 2020-12-14 16:34
edited in order to add a warning to my request, and thanks again. Still my favourite DB

**Comment by postamar** [comment] 2021-07-29 17:04
I believe we can close this now that we have `crdb_internal.unsafe_upsert_descriptor`.

**Closed by postamar** 2021-07-29 17:04 UTC
Labels: C-enhancement, T-sql-schema
