### ISSUE TITLE
`Transaction with wrong status error for` INSERT ... SELECT Query

### ISSUE THREAD

**Issue by debraj-manna** [cockroachdb/cockroach#19916] opened 2017-11-08 17:46 UTC
This is discussed in [forum](https://forum.cockroachlabs.com/t/handling-triggers-in-cockroach-db/1100/)

**Cockroach Schema**

```
CREATE TABLE config_versions (
    customerid integer NOT NULL,
    objecttype integer NOT NULL,
    objectid bigint NOT NULL,
    propertyname text NOT NULL,
    timeinstant bigint NOT NULL,
    updatetimestamp timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY (customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp),
    INDEX config_versions_by_version (updatetimestamp)
);

CREATE TABLE config_str (
    customerid integer NOT NULL,
    objecttype integer NOT NULL,
    objectid bigint NOT NULL,
    propertyname text NOT NULL,
    timeinstant bigint NOT NULL,
    updatetimestamp timestamp with time zone DEFAULT now(),
    value text,
    PRIMARY KEY (customerid, objecttype, objectid, propertyname, timeinstant)
);
```

**Cockroach SQL Output**
```
root@:26257/vnera> truncate table config_versions;
TRUNCATE

Time: 21.742703ms

root@:26257/vnera> truncate table config_str;
TRUNCATE

Time: 19.756285ms

root@:26257/van> INSERT INTO config_versions (customerId, objecttype, objectid, propertyname, timeinstant, UpdateTimestamp) SELECT * FROM [ INSERT INTO config_str (customerId, objecttype, objectid, propertyname, timeinstant, value) VALUES (1, 1, '5787634245046922574'::int8, 'prop_2', '10'::int8, '1') RETURNING customerId, objecttype, objectid, propertyname, timeinstant,now() ];
pq: internal/client/txn.go:887: attempting to use transaction with wrong status or finalized: COMMITTED true

root@:26257/van> SELECT count(*) FROM config_str;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
(1 row)

Time: 704.186µs

root@:26257/van> SELECT count(*) FROM config_versions;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
(1 row)

Time: 1.08122ms
```
Also I think this is confusing the above query failed but it entered data in `config_str`

**Cockroach Version** 

```
dmanna-m01:main dmanna$ cockroach version
Build Tag:    v1.1.1
Build Time:   2017/10/19 15:29:38
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  f3bc578c89627d02f2ca30f02b835388278a1c83
Build Type:   release
```

**Comment by knz** [comment] 2017-11-08 19:47
This is a duplicate of #18806.

**Closed by knz** 2017-11-08 19:47 UTC
