### ISSUE TITLE
circleci: failed tests: TestReleaseAcquireByNameDeadlock

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8889] opened 2016-08-29 16:16 UTC
The following test appears to have failed:

[#21908](https://circleci.com/gh/cockroachdb/cockroach/21908):

```
I160829 16:12:28.419806 kv/dist_sender.go:1018  application error: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160829 16:12:28.420038 util/log/trace.go:64  reply error GC [/Local/Range/"\xba"/RangeDescriptor,/Local/Range/"\xba"/"rdsc\x00"): end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160829 16:12:28.420186 internal/client/db.go:493  failed batch: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
W160829 16:12:28.420286 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
==================
WARNING: DATA RACE
Read at 0x00c4202464f0 by goroutine 79:
  github.com/cockroachdb/cockroach/sql.(*tableState).release.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:705 +0x8d
  github.com/cockroachdb/cockroach/sql.(*tableState).release()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:728 +0x1b1
  github.com/cockroachdb/cockroach/sql.(*tableState).purgeOldLeases()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:798 +0x407
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:1180 +0x9c5
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
--
  github.com/cockroachdb/cockroach/sql.TestReleaseAcquireByNameDeadlock()
      /go/src/github.com/cockroachdb/cockroach/sql/lease_internal_test.go:384 +0x6e6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Goroutine 79 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x73
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:1197 +0x12d
  github.com/cockroachdb/cockroach/server.NewServer()
      /go/src/github.com/cockroachdb/cockroach/server/server.go:196 +0x18a6
  github.com/cockroachdb/cockroach/server.(*TestServer).Start()
      /go/src/github.com/cockroachdb/cockroach/server/testserver.go:229 +0x352
  github.com/cockroachdb/cockroach/testutils/serverutils.StartServerRaw()
      /go/src/github.com/cockroachdb/cockroach/testutils/serverutils/test_server_shim.go:140 +0x159
--
  github.com/cockroachdb/cockroach/sql.TestReleaseAcquireByNameDeadlock()
      /go/src/github.com/cockroachdb/cockroach/sql/lease_internal_test.go:355 +0x317
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Goroutine 119 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:646 +0x52f
  testing.RunTests.func1()
      /usr/local/go/src/testing/testing.go:793 +0xb9
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:799 +0x4ba
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:743 +0x12f
--
I160829 16:15:58.550921 rpc/context.go:165  closing 127.0.0.1:51097
I160829 16:15:58.551765 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestReacquireLeaseOnRestart (0.58s)
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/sql	217.934s
I160829 16:12:23.134940 rand.go:76  Random seed: 1071492652428440437
=== RUN   TestClusterFlow
I160829 16:12:23.154137 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
W160829 16:12:23.177710 gossip/gossip.go:1070  not connected to cluster; use --join to specify a connected node
W160829 16:12:23.183948 server/status/runtime.go:109  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I160829 16:12:23.197020 server/node.go:407  store store=0:0 not bootstrapped
I160829 16:12:23.210435 storage/replica.go:2106  store=1:1 range=1 [/Min-/Max): applying command with forced error: storage/replica.go:2031: no-op on empty Raft entry
E160829 16:12:23.211245 storage/replica.go:2141  store=1:1 range=1 [/Min-/Max): error executing raft command: storage/replica.go:2031: no-op on empty Raft entry
I160829 16:12:23.212118 storage/replica_trigger.go:308  store=1:1 range=1 [/Min-/Max): new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 409024h12m32.207508155s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=2016-08-29 16:12:23.211833704 +0000 UTC]
I160829 16:12:23.215280 server/node.go:339  **** cluster {3b9865ce-777a-4625-8639-d990a9465a89} has been created

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2016-10-04 17:43
Unable to reproduce this on GCE, so...closing.

**Closed by tamird** 2016-10-04 17:43 UTC
Labels: Robot, test-failure
