### ISSUE TITLE
sql: cannot project json_object_keys() on a json column

### ISSUE THREAD

**Issue by seanlaff** [cockroachdb/cockroach#26110] opened 2018-05-25 22:00 UTC
`json_object_keys` works against a json string, but not against a json column (as it does in postgres).

```
CREATE TABLE jsontest (myjson JSONB);
INSERT INTO jsontest (myjson) VALUES ('{"first_name": "Lola", "last_name": "Dog", "location": "NYC", "online" : true, "friends" : 547}');
SELECT jsonb_object_keys(myjson) FROM jsontest;
```
Yields the error 
`pq: column name "myjson" not found`

While the same steps in postgres yield
```
 jsonb_object_keys
-------------------
 online
 friends
 location
 last_name
 first_name
(5 rows)
```

Coackroach information:
```
I180524 17:40:10.133530 1 util/log/clog.go:1134  [config] file created at: 2018/05/24 17:40:10
I180524 17:40:10.133530 1 util/log/clog.go:1134  [config] running on machine: roach1
I180524 17:40:10.133530 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.2 (x86_64-unknown-linux-gnu, built 2018/05/21 14:55:20, go1.10)
I180524 17:40:10.133530 1 util/log/clog.go:1134  [config] arguments: [/cockroach/cockroach start --insecure]
I180524 17:40:10.734765 23 cli/start.go:595  [config] clusterID: 19338980-b351-4a2d-9ced-3531916c62fc
```

**Comment by knz** [comment] 2018-05-26 15:30
This query fails because it is a lateral join in disguise. The true form of this query is

``sql
SELECT j.* FROM jsontest, LATERAL jsonb_object_keys(jsontest.myjson) AS j`
```

Lateral joins are not yet supported in CockroachDB, see #24560 and #3288.

**Comment by knz** [comment] 2018-05-26 15:32
This is really a duplicate of  #21159.

Thanks for noticing though! We'll track the issue there.

**Closed by knz** 2018-05-26 15:32 UTC
Labels: A-sql-json, A-sql-planning, C-enhancement
