### ISSUE TITLE
stability: High-latency cluster failing with errors like "context deadline exceeded"

### ISSUE THREAD

**Issue by smaliz** [cockroachdb/cockroach#6046] opened 2016-04-13 19:11 UTC
### What version of CockroachDB are you using (`cockroach version`)?

```
docker exec -it dg_roach_test ./cockroach version --deps
Build Tag:   beta-20160331-150-g7f91743
Build Time:  2016/04/06 20:05:37
Platform:    linux amd64
Go Version:  go1.6
C Compiler:  gcc 4.9.2
Build Deps:
  github.com/VividCortex/ewma                c34099b489e4ac33ca8d8c5f9d29d6eeaf69f2ed
  github.com/biogo/store                     3b4c041f52c224ee4a44f5c8b150d003a40643a0
  github.com/chzyer/readline                 30b462e50b8f8a1172c3b2f780894c0db2ae2dcb
  github.com/cockroachdb/c-protobuf          4feb192131ea08dfbd7253a00868ad69cbb61b81
  github.com/cockroachdb/c-rocksdb           b80d2efe8e544bbcc4b50dec8e89f9305f5da745
  github.com/cockroachdb/c-snappy            5c6d0932e0adaffce4bfca7bdf2ac37f79952ccf
  github.com/cockroachdb/cmux                112f0506e7743d64a6eb8fedbcff13d9979bbf92
  github.com/cockroachdb/cockroach           7f917439b21046dc8e3df0d69ddc2c9fc7c33043
  github.com/cockroachdb/pq                  94a0880a5cc09284fe5677c86e44d5ba342912dc
  github.com/codahale/hdrhistogram           360314142131c2043d1346f197f86435b287c6da
  github.com/coreos/etcd                     83ada7232a13491f7ef94cb398d9af8b3b2cb5fb
  github.com/cpuguy83/go-md2man              2724a9c9051aa62e9cca11304e7dd518e9e41599
  github.com/dustin/go-humanize              8929fe90cee4b2cb9deb468b51fb34eba64d1bf0
  github.com/elastic/gosigar                 a19182d1f557de49dc3cef0eefa688ae6a3316d9
  github.com/elazarl/go-bindata-assetfs      57eb5e1fc594ad4b0b1dbea7b286d299e0cb43c2
  github.com/gengo/grpc-gateway              965b62d83c33af1be34fd5d70ccf814c4029a319
  github.com/gogo/protobuf                   128ef922449da3dbb6c5d942856877a1a7235fef
  github.com/golang/protobuf                 8d92cf5fc15a4382f8964b08e1f42a75c0591aa3
  github.com/google/btree                    cc6329d4279e3f025a53a83c397d2339b5705c45
  github.com/julienschmidt/httprouter        77366a47451a56bb3ba682481eed85b64fea14e8
  github.com/kr/pretty                       add1dbc86daf0f983cd4a48ceb39deb95c729b67
  github.com/kr/text                         bb797dc4fb8320488f47bf11de07a733d7233e1f
  github.com/lib/pq                          3cd0097429be7d611bb644ef85b42bfb102ceea4
  github.com/mattn/go-isatty                 56b76bdf51f7708750eac80fa38b952bb9f32639
  github.com/mattn/go-runewidth              d6bea18f789704b5f83375793155289da36a3c7f
  github.com/olekukonko/tablewriter          cca8bbc0798408af109aaaa239cbd2634846b340
  github.com/opentracing/basictracer-go      e8d818a9990870fbd77b7e03697110ee074b71f2
  github.com/opentracing/opentracing-go      01498abd158dfdbe8e251856bc7d14cb0f046fa3
  github.com/rcrowley/go-metrics             eeba7bd0dd01ace6e690fa833b3f22aaec29af43
  github.com/russross/blackfriday            b43df972fb5fdf3af8d2e90f38a69d374fe26dd0
  github.com/satori/go.uuid                  f9ab0dce87d815821e221626b772e3475a0d2749
  github.com/shurcooL/sanitized_anchor_name  10ef21a441db47d8b13ebcc5fd2310f636973c77
  github.com/spf13/cobra                     c678ff029ee250b65714e518f4f5c5cb934955de
  github.com/spf13/pflag                     7f60f83a2c81bc3c3c0d5297f61ddfa68da9d3b7
  golang.org/x/crypto                        c7e3b0ebdd409a0d024e3d71801427ab0e05fb2e
  golang.org/x/net                           1dd0d85fc0634d2dbe7f7d06d176c2ff548e6332
  golang.org/x/text                          1b466db55e0ba5d56ef5315c728216b42f796491
  google.golang.org/grpc                     9e3a674ceba65708273cf1cd8e71a1bdce68107b
  gopkg.in/inf.v0                            3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4
  gopkg.in/yaml.v1                           9f9df34309c04878acc86042b16630b0f696e1de
```
## What operating system and processor architecture are you using?

```
cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

uname -r
3.10.0-327.3.1.el7.x86_64
```
### What flags/environment variables did you pass to `cockroach start`?

Nothing fancy, i just built a new docker image using the cockroachdb/cockroach image and added a /cockroach/cockroach-data volume. I then have my first instance running with the following command

``` Shell
docker run -m 20g --cpu-shares=512  --net=host\
        -v /srv/cockroach/pam/cockroach-data:/cockroach/cockroach-data \
        --name=dg_roach_test \
        -d docker-registry/dwadba/cockroachdb:beta start --insecure --store=cockroach-data --host=`hostname` --port=13000 --http-port=13080 --attrs=gld
```

The others are started with the same command with the addition of the `--join` flag

So, we started a six node cluster with three nodes in LA and the other three nodes in India.
The LA nodes were started with the `--attrs` value of **gld** and the India hosts with **blr**

Not sure that it matters, but the replication policy for our database was set to this

``` Shell
docker exec -it dg_roach_test ./cockroach --host=`hostname` --port 13000 zone set xyzdb --insecure 'replicas:
- attrs: [gld]
- attrs: [gld]
- attrs: [gld]
- attrs: [blr]
- attrs: [blr]
- attrs: [blr]'
```

FYI **The latency b/w the two sites is 220 ms**. 
### Please describe the issue you observed:

When we started the cluster, all six nodes were working and behaving as expected for a couple of days atleast. A few days later i noticed the web-console reporting the nodes as down.
When i look at the logs, they are repeatedly complaining about the following

**From cockroach.ERROR**

```
Log line format: [IWEF]yymmdd hh:mm:ss.uuuuuu file:line msg
E160407 01:35:05.502610 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 06:05:32.699999 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 06:14:28.335213 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 09:42:07.669840 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 11:51:09.740818 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 14:08:54.460864 rpc/context.go:157  rpc error: code = 4 desc = "context deadline exceeded"
E160407 22:13:05.989338 storage/replica_command.go:1677  replica: range=1 [/Min-/System/"tsd\x12cr.node.sql.latency-1h-p50\x00\x01\x89\xf8\x060=2"), checksum mismatch: e = 1c8c72faa55ccc6288d6f39be24a04c538f22c2d3ffae7a5b584bcb5b816df297ba742b782d433505ee821163276c982f78d6716ae5aa5c339f7d4937869bfb9, v = 84069688bf830025ab767bf67850167bdc5f62f43b63d7ed0d878e69aae7a0d87b9f6352da65449a5cb4d5608b6392f220e8975b0acb625e4b9317a774aa3f86
E160407 23:43:05.624640 storage/replica_command.go:1677  replica: range=33 [/System/"tsd\x12cr.node.sql.latency-1h-p50\x00\x01\x89\xf8\x060=2"-/System/"tsd\x12cr.node.sql.query.count\x00\x01\x89\xf8\x06026"), checksum mismatch: e = 66737755444c75bfb894e3b39fe4086db620e9da3927409d7e4de294d2d06bc3326e809ebae305fedd0b982b5ee885bf6fa8009617d2a51e04d89e91d866a9a3, v = 8ac5e87fcb4a3233d6877726358e58020d4c3b51bbef2436912b2a49fff1ff2997a987d37927cbf2b5e818ff8cf0bb8f85710568a4ff3447aa07801edf8c3651
E160408 01:13:05.645346 storage/replica_command.go:1677  replica: range=27 [/System/"tsd\x12cr.node.sql.query.count\x00\x01\x89\xf8\x06026"-/System/"tsd\x12cr.node.txn.abandons-1m\x00\x01\x89\xf8\x060-3"), checksum mismatch: e = 5771c098d40fe634152bc56c0c9f68c591d70a43364752de49ae69711275295876215469092ecc86f5cb0e4853066d9ae166faed543fab10a93536205a0974c4, v = f95584eb26a4197ae7b3cb5c5511e1a7d4adc3e7bc28d14dd6898f37cfc8cf5ab97e30284a26d64d46a562dc9ced70311e16c1760d99beee119ea79910947653
E160408 02:43:05.680505 storage/replica_command.go:1677  replica: range=26 [/System/"tsd\x12cr.node.txn.abandons-1m\x00\x01\x89\xf8\x060-3"-/System/"tsd\x12cr.node.txn.durations-1m-p75\x00\x01\x89\xf8\x060-3"), checksum mismatch: e = 5b6eb21b174e312f0206084e810cc3773d075571862ad713543103d8832aa6225b52a90d80b2d10055cc9f2d37ec0a2032ed8feaed90f88e3259fd22b34abec5, v = 4fddb71f927b60214e965a8f1860ee71dc660931896b2f51f4b0659646b65772b75a4e3f7340880e8c5954f9124e4021e9067243e847c32f63cbfa39d83777ba
E160408 04:12:06.106619 storage/replica_command.go:1677  replica: range=29 [/System/"tsd\x12cr.node.txn.durations-1m-p75\x00\x01\x89\xf8\x060-3"-/System/"tsd\x12cr.node.txn.durations-1m-p75\x00\x01\x89\xf8\x060-4"), checksum mismatch: e = 93efb4611bea576741a0f03e709bed4ee45095e0ed4cb80a904bdd13c9ac480d43987b70930e4cc4ae8c330ad5582d45ba1f549212f67988000276e0a363d6bc, v = 0bf5d906b2f1e0b0240b886a26e4ae6463f00043df929f528874b6f0fd5a061d1193b03548c35c90eccc0d28891d7694618ba23d9786c7fdebefd1b85ca8bc37
E160408 05:43:05.877805 storage/replica_command.go:1677  replica: range=25 [/System/"tsd\x12cr.node.txn.durations-1m-p75\x00\x01\x89\xf8\x060-4"-/System/"tsd\x12cr.store.rocksdb.block.cache.pinned-usage\x00\x01\x89\xf8\x06024"), checksum mismatch: e = b18457701cd9942ef074b1cb6603229f4658593d3cfd76512891494f65795d0420f268d4f887a4e25f23bcabdbf07cad140bc1e93ac39912bc093356d989bbd9, v = 7ba504a2a3eca8a3a009a2efd63eb6634b2e1a51a349b604d7ebbf2f2a312588a55949ac4e1d3349ff7705427b0908a2d121f3e7707dfb057f7122d92640d8ef
E160408 07:12:06.106618 storage/replica_command.go:1677  replica: range=28 [/System/"tsd\x12cr.store.rocksdb.bloom.filter.prefix.useful\x00\x01\x89\xf8\x060-2"-/System/"tsd\x12cr.store.rocksdb.bloom.filter.prefix.useful\x00\x01\x89\xf8\x060-3"), checksum mismatch: e = 9bdac28dd09c896e6c5c8a894ade62051846f2fb3895ab53227dfc3e6c813e04b132f3201d7a5117f4185bd000027239687e5510101af5d894260acc4e18ae47, v = 4238231364dde13814e07bad0c96d9ab5d2511365f106cf6b12b970c02564988fc3eb5c765279c3ab17a66e5892a257dcf1522ae3b379ec84c14a1bd410a3ac2
```

**From cockroach.WARNING**

```
W160413 00:36:59.349848 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:00.350154 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:01.350310 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:02.350533 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:02.976055 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (129733) for range 44
W160413 00:37:03.350739 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:04.350992 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:05.351201 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:05.695067 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:06.351439 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:07.351651 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:08.351851 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:09.352044 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:10.352268 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:11.352536 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:12.352819 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:13.353072 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:14.353349 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:15.353637 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:16.353895 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:16.910485 ts/db.go:98  error writing time series data: failed to send RPC: too many errors encountered (3 of 3 total): rpc error: code = 4 desc = "context deadline exceeded"
W160413 00:37:17.354168 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:18.354353 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:19.354542 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:20.354790 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:21.355059 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:22.355266 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:23.250107 server/node.go:598  error recording status summaries: failed to send RPC: too many errors encountered (3 of 3 total): rpc error: code = 4 desc = "context deadline exceeded"
W160413 00:37:23.355552 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:24.355760 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:25.356016 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:26.356329 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:27.356635 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 00:37:27.980788 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (129733) for range 44
W160413 00:37:28.356933 gossip/gossip.go:893  first range unavailable or cluster not initialized
W1
```

**From cockroach.INFO**

```
W160413 13:06:36.731891 gossip/gossip.go:893  first range unavailable or cluster not initialized
I160413 13:06:37.609966 server/status/runtime.go:160  runtime stats: 4.3 GiB RSS, 118 goroutines, 12 MiB active, 190.50cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
W160413 13:06:37.732079 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:38.732310 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:39.732507 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:40.732709 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:41.062250 server/node.go:598  error recording status summaries: failed to send RPC: too many errors encountered (3 of 3 total): rpc error: code = 4 desc = "context deadline exceeded"
W160413 13:06:41.732970 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:42.733176 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:43.733452 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:44.207352 ts/db.go:98  error writing time series data: failed to send RPC: too many errors encountered (3 of 3 total): rpc error: code = 4 desc = "context deadline exceeded"
W160413 13:06:44.733709 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:45.733890 gossip/gossip.go:893  first range unavailable or cluster not initialized
W160413 13:06:46.734103 gossip/gossip.go:893  first range unavailable or cluster not initialized
I160413 13:06:47.610068 server/status/runtime.go:160  runtime stats: 4.3 GiB RSS, 118 goroutines, 12 MiB active, 190.50cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
W160413 13:06:47.698470 storage/raft_log_queue.go:116  storage/raft_log_queue.go:101: raft log's oldest index (0) is less than the first index (129733) for range 44
W160413 13:06:47.734363 gossip/gossip.go:893  first range unavailable or cluster not initialized
```

**Comment by tschottdorf** [comment] 2016-04-14 13:00
Hi @smaliz, thanks for your report.

The "checksum mismatch" errors are easy to explain: We are running a background process that compares the checksums of the copies of the data stored, but we have repeatedly run into issues that cause checksum mismatches. Usually these are caused by computations which the replicas don't carry out as synchronously as they should. @vivekmenezes, are the keys logged above already known to currently cause us trouble?

Especially if you've intermittently updated nodes, and in particular if there was load on the cluster at the time, it's possible that your replicas diverged due to version mismatch. We're working towards a better migration process, but it's not in place yet. Luckily, while these are errors, they'll not interfere with your test cluster otherwise for the time being.

The more interesting issue is

```
W160413 13:06:37.732079 gossip/gossip.go:893  first range unavailable or cluster not initialized
```

which indicates that your cluster has lost internal connectivity, i.e. a signal which ought to be broadcast across all of the cluster (via Gossip) isn't received by that node. Unfortunately, this could have a variety of reasons, including the exotic configuration you're running (I'm calling it exotic because we're still busy working out kinks in close-proximity clusters, so the use case you're currently running, while supported, might have some unknown issues on top of some known ones we've encountered during testing).

Would you mind posting the output of

`./cockroach debug range ls`? I'm interested in where the first range is located. You might have to run this from a particular node since it may fail for some (or even all, which would also constitute a useful data point).

Another interesting data point would be grabbing all of the nodes `/debug/` endpoint recursively (i.e. wget everything in `node:8080/debug/*`).

**Comment by vivekmenezes** [comment] 2016-04-14 16:44
Thanks for the report and we are definitely excited to see you try out this type of configuration. Thank you!

https://github.com/cockroachdb/cockroach/pull/5905 contains the fix for the consistency checksum mismatch that you are seeing, and unfortunately was not present on that release. It will be available on the 20160414 release. Unfortunately the fix will only fix consistency issues in new data and all existing data (only cockroach internal data not your data) will continue to be inconsistent. There is no harm in running the system as is. Thanks

**Comment by smaliz** [comment] 2016-04-20 16:59
Hi Tobias and Vivek, apologies for the delayed response. 

So, our cluster is not really doing any work, i get the checksum mismatch with an idle cluster and no databases. I will grab the latest release to see if the checksum issues go away.

I tried to you get the output you asked for but `./cockroach debug range ls` fails on all the nodes with the following error

```
Error: scan failed: failed to send RPC: too many errors encountered (3 of 3 total): rpc error: code = 4 desc = "context deadline exceeded"
```

And hitting the `/debug/*` endpoint gives me options to obtain debug on requests, variables, block etc. 
Let me know which one you are interested in seeing. 

thx guys. FYI, i will be rebuilding my cluster with the latest bits.

**Comment by tamird** [comment] 2016-07-02 02:11
@smaliz have you been able to reproduce these problems with newer betas?

**Comment by jonasschneider** [comment] 2016-07-11 06:28
I am able to reproduce this with a cluster topology of two nodes in the same DC and one satellite node far out (~200ms RTT). Is there a workaround to increase the set deadline or to extend it?

Is this also an issue caused by long-running transactions, or does this only stem from the network latency issues?

**Comment by bdarnell** [comment] 2016-07-11 17:23
@jonasschneider It's most likely related to the network latency; we haven't yet done much testing with > 200ms RTT. We know there are some issues but we don't know yet which variables need to be tweaked for this kind of environment.

Also, asymmetric configurations like this are not ideal. The remote node is likely to be chronically behind, so as soon as you lose one of the two nodes in the main DC everything will freeze until the remote node can catch up, and then things will be slow until you can re-replicate to a new node in the main DC. And even while everything is up, if the remote node manages to win an election it will slow everybody else down. It's better to have three peer datacenters, roughly equidistant from each other.

**Comment by spencerkimball** [comment] 2017-03-30 20:33
Work has been done to address this and we've run with high latency links now. I'm closing this issue due to age. Let's reopen a new issue as additional problems are encountered in deployments with high latency links.

**Closed by spencerkimball** 2017-03-30 20:33 UTC
Labels: community-questions, stability
