### ISSUE TITLE
Wrong result of SQL query

### ISSUE THREAD

**Issue by mputau** [cockroachdb/cockroach#82249] opened 2022-06-01 10:56 UTC
**Describe the problem**
I have met wrong query result.

**To Reproduce**

My setup:

```
CREATE TABLE public.table1 (id BIGINT DEFAULT unique_rowid() NOT NULL, description varchar(256),  status int4 NOT NULL, CONSTRAINT TABLE1_PKEY PRIMARY KEY (id));

CREATE TABLE public.table2 (id BIGINT DEFAULT unique_rowid() NOT NULL, table1_id BIGINT NOT null,  status int4 NOT NULL, CONSTRAINT TABLE2_PKEY PRIMARY KEY (id), CONSTRAINT fk_table2_table1 FOREIGN KEY (table1_id) REFERENCES public.table1(id));

CREATE INDEX table2_table1_id_idx ON public.table2 (table1_id);

insert into public.table1 values (1, 'DESCRIPTION1', 1);
insert into public.table1 values (2, 'DESCRIPTION2', 1);

insert into public.table2 values (1, 1, 1);
insert into public.table2 values  (2, 2, 0);
```
When I execute query:
```
select t1.id as table1_id, t2.id as table2_id, t2.status as t2_status from table1 t1
left join table2 t2 on t1.id = t2.table1_id and t2.status = 1 
```
I get result (correct)
![image](https://user-images.githubusercontent.com/81216944/171390712-7c42c616-89f1-4a25-bfb3-2ae8fdb0ea48.png)

But when I execute following query (added `where` clause)
```
select t1.id as table1_id, t2.id as table2_id, t2.status as t2_status from table1 t1
left join table2 t2 on t1.id = t2. table1_id and t2.status = 1 
where t1.description like '%DESC%'
```
The result is wrong:
![image](https://user-images.githubusercontent.com/81216944/171388747-3a734577-dfa9-4fdb-9742-57c556b0622e.png)

 It seems to me that table2_id on the second row should be empty.

**Expected behavior**
Results of both queries should be equal

**Additional data / screenshots**
Execution plan of wrong query:
![image](https://user-images.githubusercontent.com/81216944/171388193-dc7a1eed-e078-4470-a622-f44bf5498125.png)

**Environment:**
 - CockroachDB version - CockroachDB CCL v22.1.0 (x86_64-pc-linux-gnu, built 2022/05/23 16:27:47, go1.17.6)
 - Server OS: Linux(Ubuntu)
 - Client app :  `cockroach sql`
 
 **Additional context**
 

Jira issue: CRDB-16256

**Comment by rytaft** [comment] 2022-06-01 12:15
Hi @mputau, thanks very much for the report, and sorry you are running into this issue. It seems that you have run into the same issue as https://github.com/cockroachdb/cockroach/issues/81968. This bug is already fixed and will be included in 22.1.1, which will be released next week. 

In the mean time, you can work around this issue by either removing index `table2_table1_id_idx`, or ensuring that it includes all columns from `table2`.

**Comment by rytaft** [comment] 2022-06-01 14:57
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/81968. Thanks again for the report, and please don't hesitate to reach out if you have other questions.

**Closed by rytaft** 2022-06-01 14:57 UTC
Labels: C-bug, O-community, X-blathers-triaged

**Comment by rytaft** [comment] 2022-06-22 14:18
@mputau Thank you so much for finding and filing this issue, we really appreciate it. We're always looking to improve our testing coverage, so we'd love to understand your use cases and workload. If you are willing to share, would you mind reaching out to support@cockroachlabs.com (please mention this GitHub issue in the email)? Thank you!
