### ISSUE TITLE
sql: DROP DATABASE CASCADE with 1000s of tables fails

### ISSUE THREAD

**Issue by rkruze** [cockroachdb/cockroach#38984] opened 2019-07-19 04:37 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Django performs a large number of DML statements when settings up the database to run its test suite. This runs successfully the first time but if you let Django drop the database and recreated it you get the following: 

`split failed while applying backpressure to [txn: 97a88a2b], Put [/Table/15/1/470022975105761281/0,/Min), Put [/Table/15/1/470022975105761281/1/1,/Min) on range r1654:/Table/15/{1/470022975105761281-2/"failed"/2019-07-18T23:49:23.546435Z/469969677668941827} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=1]: could not find valid split key`

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Run the Django test suite once using the CRDB backend - https://github.com/cockroachlabs/cockroach-django
3. After the tables and indexes have been created, rerun the tests and say yes to dropping the database. 
4. This will fail with an error like: `split failed while applying backpressure to [txn: 97a88a2b], Put [/Table/15/1/470022975105761281/0,/Min), Put [/Table/15/1/470022975105761281/1/1,/Min) on range r1654:/Table/15/{1/470022975105761281-2/"failed"/2019-07-18T23:49:23.546435Z/469969677668941827} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=1]: could not find valid split key`

**Expected behavior**
That the DDL statements would execute with no errors. 

**Additional data / screenshots**
Table 15 is the Jobs table. When I do a `select count(*)` on the jobs table I get a count of 4302 rows. 

**Environment:**
 - CockroachDB version 19.1.2
 - Server OS: Mac
 - Client app Django Unit Tests

**Comment by bdarnell** [comment] 2019-07-19 13:23
Sounds like #38617, which is fixed on master and slated to be fixed in 19.1.4. If this happens repeatably (and it is indeed fixed on master or the current release-19.1 branch), it would be evidence in favor of releasing 19.1.4 ahead of schedule.

**Comment by bdarnell** [comment] 2019-07-19 13:58
I've tried to reproduce this but the django test suite fails very early when it tries to create a partial index. How exactly are you running the tests? Are you able to get past this point?

**Comment by rkruze** [comment] 2019-07-19 15:17
I left out that I'm running on the following branch https://github.com/cockroachlabs/cockroach-django/tree/django_tests 

So first I install the cockroach django backend. Then I add a file called test_cockroach.py to the django/tests folder, with the following content:

```
DATABASES = {
    'default': {
        'NAME': 'django_test',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '26257',
        'ENGINE': 'cockroach.django',
    },
    'other': {
        'NAME': 'django_test_other',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '26257',
        'ENGINE': 'cockroach.django',
    }
}

SECRET_KEY = "django_tests_secret_key"

# Use a fast hasher to speed up tests.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',
]
```

Then I run the tests with the following: 
`./runtests.py -v 3 --settings test_cockrocah` 

You will run an error of `CREATE INDEX "django_site_domain_a2e37b91_like" ON "django_site" ("domain" varchar_pattern_ops)` but at this point rereun the tests and when asked if you wish to drop the database, say 'yes'.

**Comment by bdarnell** [comment] 2019-07-19 17:05
OK, I'm seeing the same thing now. Took me about 5 runs to see the backpressure error (and then once it's happened it's repeatable on the same db instance). `cockroach debug range-data` produces 196MB of (asciified) output for that range). Nearly all of that is on a single key (in my case, `/Table/15/1/470164125564043265/0`). This is a job for a DROP DATABASE command with an 85KB payload (because it contains the names of all tables being dropped). There are 1555 versions of this row. Each version appears to be slightly larger than the last. 

This doesn't look like the runaway job status loop of #38617. Instead, it looks like some accidentally-quadratic behavior in DROP DATABASE. Maybe it's updating the job payload for every table?

**Comment by timgraham** [comment] 2021-02-10 03:04
I haven't been able to reproduce this with CockroachDB 21.1 alpha 2, so it's probably been fixed.

However, the drop database query takes on the order of 5-10 minutes. Perhaps this merits a separate issue? Here's a sample excerpt from the slow query log:
```
1612910977927254381,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","Age":8822.244}
I210209 22:49:58.191913 8743648 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:46934›,hostnossl,user=root] 2 ={"Timestamp":1612910983568345588,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","Age":20264.715,"NumRetries":1}
...
I210209 22:56:51.802531 8743648 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:46934›,hostnossl,user=root] 34 ={"Timestamp":1612911398085667563,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","Age":433875.3,"NumRetries":33}
I210209 22:56:58.950153 8743648 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:46934›,hostnossl,user=root] 35 ={"Timestamp":1612911418744531836,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","SQLSTATE":"40001","ErrorText":"‹TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE - intent pushed): \"sql txn\" meta={id=a84d40ed key=/Table/SystemConfigSpan/Start pri=0.04359349 epo=34 ts=1612911418.744531836,1 min=1612910977.927254381,0 seq=0} lock=true stat=PENDING rts=1612911408.296850320,2 wto=false max=1612910977.927254381,0›","Age":441022.97,"NumRetries":34}
I210209 22:57:09.631147 8743648 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:46934›,hostnossl,user=root] 36 ={"Timestamp":1612911420137033373,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","Age":451703.97,"NumRetries":35}
...
I210209 22:58:58.212670 8743648 10@util/log/event_log.go:32 ⋮ [n1,client=‹127.0.0.1:46934›,hostnossl,user=root] 44 ={"Timestamp":1612911521277283983,"EventType":"slow_query","Statement":"‹DROP DATABASE test_djangotests2›","User":"‹root›","ExecMode":"exec","Age":560285.5,"NumRetries":43}
```

**Comment by ajwerner** [comment] 2021-02-10 03:09
Glad to hear it! The proximate causes of the initial issue are certainly gone. Additionally the cascade logic was largely reworked in 20.2. Other things have changed as well. I'm going to close this.

**Closed by ajwerner** 2021-02-10 03:09 UTC
Labels: A-schema-changes, C-bug
