### ISSUE TITLE
Failed tests (11362): TestLogic 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3847] opened 2016-01-14 10:55 UTC
The following test appears to have failed:

[#11362](https://circleci.com/gh/cockroachdb/cockroach/11362):

```
127.0.0.1:0  10:53:42.229398  44.665µs  sending batch  kv/txn_coord_sender.go:308

I0114 10:53:42.230347 827 client/db.go:485  failed batch: kv/txn_coord_sender.go:376: transaction is already committed or aborted
E0114 10:53:42.230509 827 client/txn.go:303  failure aborting transaction: kv/txn_coord_sender.go:376: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:376: transaction is already committed or aborted
I0114 10:53:42.233053 827 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestLogic (66.39s)
	logic_test.go:455: testdata/snapshot_issue2861:50: expected success, but found
		pq: kv/txn_coord_sender.go:376: transaction is already committed or aborted
=== RUN   TestPGWire
W0114 10:53:42.238906 827 server/server.go:102  running in insecure mode, this is strongly discouraged. See --insecure and --certs.
I0114 10:53:42.242978 827 rpc/clock_offset.go:153  monitoring cluster offset
I0114 10:53:42.247162 827 raft/raft.go:446  [group 1] 1 became follower at term 5
I0114 10:53:42.247428 827 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0114 10:53:42.247566 827 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0114 10:53:42.247693 827 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0114 10:53:42.247818 827 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
--
--- PASS: TestColumnTypeSQLString (0.00s)
	<autogenerated>:28: prior leak detected, leaktest disabled
=== RUN   TestInitialKeys
--- PASS: TestInitialKeys (0.00s)
	<autogenerated>:28: prior leak detected, leaktest disabled
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	97.981s
=== RUN   TestNoLinkForbidden
--- PASS: TestNoLinkForbidden (0.90s)
=== RUN   TestDates
I0114 10:52:32.248784 839 rpc/clock_offset.go:153  monitoring cluster offset
I0114 10:52:32.262084 839 raft/raft.go:446  [group 1] 1 became follower at term 5
I0114 10:52:32.262505 839 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0114 10:52:32.262714 839 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I0114 10:52:32.262919 839 raft/raft.go:459  [group 1] 1 became candidate at term 6
I0114 10:52:32.263137 839 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I0114 10:52:32.263352 839 raft/raft.go:487  [group 1] 1 became leader at term 6

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-01-14 14:32
I was unable to reproduce using `make stressrace PKG=./sql TESTS=TestLogic`. Going to keep trying. CircleCI is being real slow. I can't get to the logs for the failed test.

**Comment by petermattis** [comment] 2016-01-25 21:45
Still unable to reproduce, but I was able to get the logs from CircleCI. The specific failure was on `testdata/snapshot_issue2861`. @tschottdorf this was your test. Any ideas what is going on?

**Comment by petermattis** [comment] 2016-01-26 21:40
Ran `make stressrace PKG=./sql TESTS=TestLogic TESTFLAGS="-d testdata/snapshot_issue2861" STRESSFLAGS="-p 96"` for 373345 runs without failure. Not sure how to reproduce this one.

**Comment by petermattis** [comment] 2016-01-26 23:10
483273 runs of `make stressrace PKG=./sql TESTS=TestLogic STRESSFLAGS="-p 96"` without failure. I'm going to close this for now. I don't think it is worth investigating further at this time.

**Closed by petermattis** 2016-01-26 23:10 UTC
Labels: test-failure, TestLogic
