### ISSUE TITLE
sql: odd treatment of characters in column name

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#19413] opened 2017-10-20 16:55 UTC
Is this expected behavior? Currently running on the PM cluster.

![image](https://user-images.githubusercontent.com/5768024/31832691-eedd762e-b595-11e7-9bda-2b701f0d6713.png)

But wrapping the column name in quotes works fine.

**Comment by a-robinson** [comment] 2017-10-20 16:59
Yeah, this is intended behavior for the sake of working the same as postgres, but it does have some controversy around it. Closing as a dupe of https://github.com/cockroachdb/cockroach/issues/19359 (which you apparently put a label on a couple days ago?)

**Closed by a-robinson** 2017-10-20 16:59 UTC

**Comment by dianasaur323** [comment] 2017-10-20 19:45
lol, thanks @a-robinson. I had a sneaking suspicion I had seen a similar issue recently. Information overload... =.=
