### ISSUE TITLE
ui: pkg/ui/workspaces/db-console/jest.sh is flaky

### ISSUE THREAD

**Issue by pavelkalinnikov** [cockroachdb/cockroach#97179] opened 2023-02-15 15:24 UTC
**Describe the problem**

`pkg/ui/workspaces/db-console/jest.sh` test is flaky on `master`. Started flaking on ~ Jan 20, 2023.

Last failure: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UiTest/8717392

Jira issue: CRDB-24561

**Comment by pavelkalinnikov** [comment] 2023-02-16 18:25
@cockroachdb/dev-inf This test keeps timing out for what appears to be an infrastructure reason.

**Comment by rharding6373** [comment] 2023-02-28 00:22
Bumping this issue, since this is currently flaking with a 27% rate in the UI Test build and 55% on the Merged ARM64 Tests build. A recent test failure: https://teamcity.cockroachdb.com/viewLog.html?buildId=8864360&buildTypeId=Cockroach_PostMerge_MergedArm64Tests

**Comment by jlinder** [comment] 2023-02-28 03:53
@pavelkalinnikov What made this look like an infrastructure problem to you? I'm not seeing anything indicating an infrastructure problem and these failures look like a test is timing out.

----

The first occurrence I found is [this UI Test run on ARM](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UiTest/8394732?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true) from Jan 20. The [next occurrence](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_TestsAwsLinuxArm64_UiTest/8464135?showRootCauses=false&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) happens six days later on Jan 26. It's been gradually happening more frequently on ARM. 

On Intel, I only see two failures that match this pattern since Dec 28. Both were today on PR branches ([one](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_UiTest/8866363), [two](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Ci_Tests_UiTest/8864233)).

There's no line indicating which test(s) failed. I expect it's because they timed out and were killed before they could output their log messages.

@sjbarag could you help pinpoint the problem test or identify another frontend person who can?

**Comment by pavelkalinnikov** [comment] 2023-02-28 14:37
Sorry, classifying this as the infra problem might be incorrect. I got this impression from [this](https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1676474536589029) chat.

**Comment by sjbarag** [comment] 2023-02-28 19:44
> What made this look like an infrastructure problem to you? I'm not seeing anything indicating an infrastructure problem and these failures look like a test is timing out.

@jlinder I'd mentioned this as an infra bug because these tests don't time out on x86_64 (and JS is architecture-unaware). If this were a bug in the JS app, I'd expect tests run on x86_64 to time out roughly as often — that's unfortunately not what we see!

> There's no line indicating which test(s) failed. I expect it's because they timed out and were killed before they could output their log messages.

Yep, that sounds about right. But there's basically no reason for these tests to hang indefinitely only sometimes and only on ARM64. I'll look around in a bit, but I'd like to rule out teamcity agent limitations first :) What are the specs of our ARM teamcity workers?

**Comment by healthy-pod** [comment] 2023-03-14 03:33
> Alternatively, I'd be fine with not testing db-console on ARM64. Assuming we have sufficient test coverage for the backing endpoints, db-console has zero understanding of its loading browser's architecture (by design; JS runs in a sandboxed VM, after all)

@renatolabs / @srosenberg  do you have any concerns from a test-eng perspective about this?

> But I'd still love to get some info on our ARM teamcity workers. I just don't have permission to see that from what I understand. @jlinder let me know if you get some time to chat!

We use `c6g.4xlarge` on AWS for our ARM agents. Let me know if you have other questions!

**Comment by renatolabs** [comment] 2023-03-14 13:55
>  do you have any concerns from a test-eng perspective about this?

I think it's fine not to run these tests on ARM64.

Given what @sjbarag said about JS running in a sandboxed VM in the client's browser, I'd like to take a step back and understand: what kinds of bugs could we realistically catch by running the test suite on ARM64? Would it be architectural differences that leak through the VM in a way that impacts clients running on ARM64?

**Comment by srosenberg** [comment] 2023-03-14 14:25
> I'd like to take a step back and understand: what kinds of bugs could we realistically catch by running the test suite on ARM64

Integration bugs. The test suite has some end-to-end tests if I recall correctly. It could be the infra., but we can't rule out our own code based on speculation. I think we should find the root cause for the time out.

**Comment by smg260** [comment] 2023-03-15 13:42
A visualisation of recent runs [2023-03-09 to 2023-03-15]. At this point, calling it flaky is being a bit too kind.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/25202158/225326256-8a615a96-01c2-4199-900a-d2ff8c4c0f0a.png">

Also interesting to note the increasing frequency over time

**Comment by sjbarag** [comment] 2023-03-15 15:35
Understood. I've got a cloud release to run today, but working on this will
be the first thing after that.

**Comment by sjbarag** [comment] 2023-03-15 18:22
Not entirely sure what's going on here, but I managed to take down an entire `c6g.4xlarge` by running `bazel test //pkg/ui/workspaces/db-console:jest`. After a while it just… stops responding to network traffic and stops emitting events. I've seen this on my GCP dev machine a few times, but generally thought it was something with my dev setup.

Typically, manually running jest with `-w4` (or something small like that) works: https://jestjs.io/docs/cli#--maxworkersnumstring

I'm going to give that a try. It's possible that https://github.com/facebook/jest/pull/12497 is the root-cause of that. Upgrading jest would  theoretically work, but I'm not sure what else would break as a result.

**Comment by sjbarag** [comment] 2023-03-15 18:57
Setting `-w4` kept the VM from going down, but it did repro the test hang 🤔  We'll see what `--runInBand` does.

It does look like transpilation takes a long time, so I'll have to look into something like https://github.com/evanw/jest-esbuild-demo if a jest upgrade doesn't solve things.

**Comment by sjbarag** [comment] 2023-03-15 20:04
`--runInBand` is — unsurprisingly — extremely slow. It's not a valid path forward either way.

Upgrading to Jest 28 seems to still leak memory like crazy. My GCP dev machine dies even with `-w 4` once `htop` reports 30.7/31.3GB RAM used. Switching to Jest 28 + `@swc/jest` (https://swc.rs/docs/usage/jest) for transpilation instead of `ts-jest` + `babel-jest` is significantly faster on amd64, but some tests fail — probably due to the defaults from `@swc/jest`.

If I can get `@swc/jest` working in Jest 27, that's probably the simplest fix for now to unblock our upcoming release.

**Comment by sjbarag** [comment] 2023-03-16 23:13
Yikes, it's beginning to look like we're hitting https://github.com/facebook/jest/issues/11956.

Partial results so far, but there's a massive difference in used memory outside of Bazel when passing `--no-compilation-cache` to `node`:

![image](https://user-images.githubusercontent.com/665775/225771938-c60fb782-8b36-4a51-957b-eba74a10c127.png)


Working on getting this into our BUILD.bazel now to see if it keeps memory usage under control

**Comment by sjbarag** [comment] 2023-03-17 00:09
```diff
diff --git a/pkg/ui/workspaces/db-console/BUILD.bazel b/pkg/ui/workspaces/db-console/BUILD.bazel
index 9e3ea5a159f..83ec279fcf1 100644
--- a/pkg/ui/workspaces/db-console/BUILD.bazel
+++ b/pkg/ui/workspaces/db-console/BUILD.bazel
@@ -363,6 +363,7 @@ jest_test(
     data = JEST_DEPS,
     templated_args = [
         "--node_options=--max-old-space-size=8192",
+        "--node_options=--no-compilation-cache",
         "-w 25%",
         "--ci",
         "--config",
```

This _seems_ to take care of it, but there is a warning at the end for about open handles. I've got a `node --no-compilation-cache --max-old-space-size=16384 node_modules/.bin/jest --runInBand --detectOpenHandles` running in the background to see if that reports anything juicy.

**Closed** 2023-03-17 23:25 UTC
Labels: C-bug, A-webui, T-dev-inf
