### ISSUE TITLE
stability: corruption in gamma

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#12817] opened 2017-01-10 16:03 UTC
```
E170110 04:54:39.852163 145 storage/replica.go:4400  [n4,s4,r273/2:/Table/51/1/42{26594…-44871…},@c421255800] stalling replica due to: could not commit batch: Corruption: block checksum mismatch
panic: Corruption: block checksum mismatch [recovered]
	panic: Corruption: block checksum mismatch

```

On gamma, I can reliably generate this error after running a cluster for a while from 
https://cockroachgammabackup.file.core.windows.net/gamma-12489-x

**Comment by BramGruneir** [comment] 2017-01-10 16:03
The good news, is that after that node died, the rest of the cluster recovered quickly.

**Comment by bdarnell** [comment] 2017-03-10 02:17
Duplicate of #12875.

**Closed by bdarnell** 2017-03-10 02:17 UTC
