### ISSUE TITLE
Test failure in CI build 1248

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#605] opened 2015-04-09 02:52 UTC
The following test appears to have failed:

[#1248](https://circleci.com/gh/cockroachdb/cockroach/1248):

```
I0409 02:49:53.578819     270 multiraft.go:651] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0409 02:49:53.579926     270 multiraft.go:654] New Entry[0]: 6/35 EntryNormal 13d338a64404813261fece1535d95dc3: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428547793563451698 random:7061307856256589251 > key:"b
I0409 02:49:53.580973     270 multiraft.go:657] Committed Entry[0]: 6/35 EntryNormal 13d338a64404813261fece1535d95dc3: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428547793563451698 random:7061307856256589251 > key:"b
I0409 02:49:53.588499     270 raft.go:390] raft: 101 became follower at term 5
I0409 02:49:53.588724     270 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb0c5b6]

goroutine 1677 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2080a0b70, 0xc2085501e0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:638 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2080a0b70)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:480 +0x1af5
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:152 +0x60

--
goroutine 1678 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc20839e160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1122 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:478 +0xc92
FAIL	github.com/cockroachdb/cockroach/storage	3.405s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)
I0409 02:49:53.578819     270 multiraft.go:651] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0409 02:49:53.579926     270 multiraft.go:654] New Entry[0]: 6/35 EntryNormal 13d338a64404813261fece1535d95dc3: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428547793563451698 random:7061307856256589251 > key:"b
I0409 02:49:53.580973     270 multiraft.go:657] Committed Entry[0]: 6/35 EntryNormal 13d338a64404813261fece1535d95dc3: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428547793563451698 random:7061307856256589251 > key:"b
I0409 02:49:53.588499     270 raft.go:390] raft: 101 became follower at term 5
I0409 02:49:53.588724     270 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb0c5b6]

goroutine 1677 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2080a0b70, 0xc2085501e0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:638 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2080a0b70)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:480 +0x1af5
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:152 +0x60

--
goroutine 1678 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc20839e160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1122 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:478 +0xc92
FAIL	github.com/cockroachdb/cockroach/storage	3.405s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-04-09 02:53
Duplicate of #597

**Closed by bdarnell** 2015-04-09 02:53 UTC
Labels: test-failure
