### ISSUE TITLE
panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#41311] opened 2019-10-04 01:55 UTC
9-node roachprod cluster running the latest beta (v19.2.0-beta.20190930), with MovR running on separate VMs in each region. Node 2 panicked. 

To access node:

```
roachprod run jesse-movr-multi-region-georeplicas:2
```

Excerpt from the logs:

```
I191003 20:58:23.080333 3792216 storage/replica_command.go:1583  [n2,replicate,s2,r8/1406:/Table/1{2-3}] change replicas (add [(n1,s1):1428VOTER_INCOMING] remove [(n8,s8):1427VOTER_OUTGOING]): existing descriptor r8:/Table/1{2-3} [(n4,s4):1411, (n8,s8):1427, (n2,s2):1406, (n9,s9):1415, (n7,s7):1425, (n1,s1):1428LEARNER, next=1429, gen=4272]
I191003 20:58:23.886654 3792216 storage/replica_raft.go:291  [n2,s2,r8/1406:/Table/1{2-3}] proposing ENTER_JOINT ADD_REPLICA[(n1,s1):1428VOTER_INCOMING], REMOVE_REPLICA[(n8,s8):1427VOTER_OUTGOING]: after=[(n4,s4):1411 (n8,s8):1427VOTER_OUTGOING (n2,s2):1406 (n9,s9):1415 (n7,s7):1425 (n1,s1):1428VOTER_INCOMING] next=1429
I191003 20:58:23.954508 3792216 storage/replica_command.go:1583  [n2,replicate,s2,r8/1406:/Table/1{2-3}] change replicas (add [] remove []): existing descriptor r8:/Table/1{2-3} [(n4,s4):1411, (n8,s8):1427VOTER_OUTGOING, (n2,s2):1406, (n9,s9):1415, (n7,s7):1425, (n1,s1):1428VOTER_INCOMING, next=1429, gen=4273]
I191003 20:58:24.060949 3792216 storage/replica_raft.go:291  [n2,s2,r8/1406:/Table/1{2-3}] proposing LEAVE_JOINT: after=[(n4,s4):1411 (n1,s1):1428 (n2,s2):1406 (n9,s9):1415 (n7,s7):1425] next=1429
I191003 20:58:25.775388 158 storage/store_remove_replica.go:129  [n2,s2,r78/158:/Table/1{3/1/2019…-4}] removing replica r78/158
I191003 20:58:26.116570 120 storage/store_remove_replica.go:129  [n2,s2,r24/1411:/Table/{28-53}] removing replica r24/1411
I191003 20:58:28.262205 166 storage/store_remove_replica.go:129  [n2,s2,r16/1092:/Table/2{0-1}] removing replica r16/1092
E191003 20:58:31.357899 181 util/log/crash_reporting.go:207  [n2] a panic has occurred!
panic: runtime error: makeslice: cap out of range [recovered]
        panic: runtime error: makeslice: cap out of range

goroutine 181 [running]:
panic(0x3b50560, 0x489a3d0)
        /usr/local/go/src/runtime/panic.go:565 +0x2c5 fp=0xc00ce67400 sp=0xc00ce67370 pc=0x78d165
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0006878c0, 0x4957500, 0xc000677b60)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x121 fp=0xc00ce67460 sp=0xc00ce67400 pc=0x12d02f1
runtime.call32(0x0, 0x4185028, 0xc0000f5ca0, 0x1800000018)
        /usr/local/go/src/runtime/asm_amd64.s:519 +0x3b fp=0xc00ce67490 sp=0xc00ce67460 pc=0x7bb1db
panic(0x3b50560, 0x489a3d0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5 fp=0xc00ce67520 sp=0xc00ce67490 pc=0x78d055
runtime.panicmakeslicecap(...)
        /usr/local/go/src/runtime/slice.go:31
runtime.makeslice(0x3a0e7a0, 0x0, 0xffffffffffffffff, 0x76278f1)
        /usr/local/go/src/runtime/slice.go:46 +0xf2 fp=0xc00ce67550 sp=0xc00ce67520 pc=0x7a3db2
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Capacity(0xc0008d8300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2103 +0x1b8 fp=0xc00ce67940 sp=0xc00ce67550 pc=0x1c3f458
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Descriptor(0xc0008d8300, 0x4957500, 0xc000677b60, 0x4957500, 0xc00f81b5f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2176 +0x4f fp=0xc00ce67ac0 sp=0xc00ce67940 pc=0x1c3faef
github.com/cockroachdb/cockroach/pkg/storage.(*Store).updateCapacityGauges(0xc0008d8300, 0x4957500, 0xc000677b60)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store_raft.go:737 +0x34 fp=0xc00ce67af8 sp=0xc00ce67ac0 pc=0x1c4f784
github.com/cockroachdb/cockroach/pkg/storage.(*Store).ComputeMetrics(0xc0008d8300, 0x4957500, 0xc000677b60, 0x7aa, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2328 +0x8c fp=0xc00ce67cb0 sp=0xc00ce67af8 pc=0x1c4065c
github.com/cockroachdb/cockroach/pkg/server.(*Node).computePeriodicMetrics.func1(0xc0008d8300, 0x76e499, 0xc009404d90)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:735 +0x5a fp=0xc00ce67d38 sp=0xc00ce67cb0 pc=0x2f8aa7a
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).VisitStores.func1(0x2, 0xc0008d8300, 0xc009404d90)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:126 +0x38 fp=0xc00ce67d68 sp=0xc00ce67d38 pc=0x1c82258
github.com/cockroachdb/cockroach/pkg/util/syncutil.(*IntMap).Range(0xc0003757f8, 0xc00ce67e20)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/int_map.go:352 +0xe7 fp=0xc00ce67e00 sp=0xc00ce67d68 pc=0x938957
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).VisitStores(0xc0003757c0, 0xc009404e68, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:125 +0x75 fp=0xc00ce67e48 sp=0xc00ce67e00 pc=0x1c610c5
github.com/cockroachdb/cockroach/pkg/server.(*Node).computePeriodicMetrics(0xc000696000, 0x4957500, 0xc000677b60, 0x7aa, 0x1, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:734 +0x77 fp=0xc00ce67e98 sp=0xc00ce67e48 pc=0x2f61c07
github.com/cockroachdb/cockroach/pkg/server.(*Node).startComputePeriodicMetrics.func1(0x4957500, 0xc000677b60)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:721 +0x15d fp=0xc00ce67f78 sp=0xc00ce67e98 pc=0x2f8a93d
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00029d0d0, 0xc0006878c0, 0xc00036c760)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0xfb fp=0xc00ce67fc8 sp=0xc00ce67f78 pc=0x12d248b
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00ce67fd0 sp=0xc00ce67fc8 pc=0x7bcef1
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:189 +0xa8

goroutine 1 [select, 327 minutes]:
runtime.gopark(0x4188508, 0x0, 0x1809, 0x1)
        /usr/local/go/src/runtime/proc.go:301 +0xef fp=0xc000bdf520 sp=0xc000bdf500 pc=0x78f27f
runtime.selectgo(0xc000bdfa90, 0xc000bdf788, 0x4, 0x73f5920, 0x3f1dda0)
        /usr/local/go/src/runtime/select.go:313 +0xcb8 fp=0xc000bdf648 sp=0xc000bdf520 pc=0x79edb8
github.com/cockroachdb/cockroach/pkg/cli.runStart(0x6f79a80, 0xc0008b1050, 0x0, 0x9, 0xc000d1a900, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:838 +0xb5b fp=0xc000bdfb40 sp=0xc000bdf648 pc=0x301794b
github.com/cockroachdb/cockroach/pkg/cli.runStartJoin(0x6f79a80, 0xc0008b1050, 0x0, 0x9, 0x3af5b60, 0xc0004567e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/start.go:428 +0x4e fp=0xc000bdfb88 sp=0xc000bdfb40 pc=0x3016dbe
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x6f79a80, 0xc0008b1050, 0x0, 0x9, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:65 +0x6e fp=0xc000bdfd30 sp=0xc000bdfb88 pc=0x302c80e
github.com/cockroachdb/cockroach/pkg/cli.maybeShoutError.func1(0x6f79a80, 0xc0008b1050, 0x0, 0x9, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:218 +0x4d fp=0xc000bdfd70 sp=0xc000bdfd30 pc=0x302d8ad
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).execute(0x6f79a80, 0xc0008b0fc0, 0x9, 0x9, 0x6f79a80, 0xc0008b0fc0)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:762 +0x465 fp=0xc000bdfe58 sp=0xc000bdfd70 pc=0x2d7a0a5
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x6f73920, 0x4184ee8, 0x4957480, 0xc000078060)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:852 +0x2ec fp=0xc000bdff28 sp=0xc000bdfe58 pc=0x2d7ab3c
github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:800
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:224
github.com/cockroachdb/cockroach/pkg/cli.Main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:66 +0x24e fp=0xc000bdff88 sp=0xc000bdff28 pc=0x2fd949e
main.main()
        /go/src/github.com/cockroachdb/cockroach/pkg/cmd/cockroach/main.go:26 +0x20 fp=0xc000bdff98 sp=0xc000bdff88 pc=0x3044e20
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000bdffe0 sp=0xc000bdff98 pc=0x78ee8c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000bdffe8 sp=0xc000bdffe0 pc=0x7bcef1

goroutine 2 [force gc (idle), 327 minutes]:
runtime.gopark(0x41884c8, 0x739a350, 0x1410, 0x1)
        /usr/local/go/src/runtime/proc.go:301 +0xef fp=0xc00008efb0 sp=0xc00008ef90 pc=0x78f27f
runtime.goparkunlock(...)
        /usr/local/go/src/runtime/proc.go:307
runtime.forcegchelper()
        /usr/local/go/src/runtime/proc.go:250 +0xb7 fp=0xc00008efe0 sp=0xc00008efb0 pc=0x78f127
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc00008efe8 sp=0xc00008efe0 pc=0x7bcef1
created by runtime.init.5
        /usr/local/go/src/runtime/proc.go:239 +0x35
...
```

Full logs attached: 
[node2.zip](https://github.com/cockroachdb/cockroach/files/3688659/node2.zip)

**Comment by jseldess** [comment] 2019-10-04 02:03
Lifetime extended for 100h in case people want to poke around.

**Comment by andy-kimball** [comment] 2019-10-04 02:12
@ajkr, could I get you to look at this one? Looks like the `ReplicaCount` metric value is somehow a really huge number?? Jesse's extended the cluster in case you need to access it.

**Comment by nvanbenschoten** [comment] 2019-10-04 02:29
This is a duplicate of #41271, which I have a patch out (https://github.com/cockroachdb/cockroach/pull/41278) to fix.

@jseldess you can go ahead and kill that cluster.

**Closed by nvanbenschoten** 2019-10-04 02:29 UTC

**Comment by jseldess** [comment] 2019-10-04 12:46
Thanks, @nvanbenschoten. I kept the cluster running overnight, and another node crashed, seemingly for the same reason. At least the logs show the same panic message. Is this panic supposed to occur so frequently?

**Comment by nvanbenschoten** [comment] 2019-10-04 20:59
It's new as of last week, so it's not clear how frequently we expect to hit it.
