### ISSUE TITLE
Enhancement Request: Allow Read-only mode in case of quorum loss

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#26688] opened 2018-06-13 14:45 UTC
From the [forum](https://forum.cockroachlabs.com/t/request-for-read-only-cluster-instead-of-unresponsive-when-losing-quorum/1723):

> I am worried about a scenario where we are running 100% on AWS and relying on AWS NTP and something goes wonky with their NTP service, and the cluster starts evicting nodes to where we lose quorum. Are there any gates that can be set for the number of nodes which can be evicted? Furthermore, I would rather the cluster go read-only than become inaccessible / unresponsive when losing quorum.

fat0, ik_zelf, please provide more details on your use case below:

**FEATURE REQUEST**

1. Please describe the feature you are requesting, as well as your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

**Comment by tschottdorf** [comment] 2018-06-19 14:49
Duplicate of https://github.com/cockroachdb/cockroach/issues/6150

Note also that follower reads could at some point allow something like this, but more in the "you can read some reasonably recent version of data hopefully -- not in the "all queries will become read only" type of way).

We're very unlikely to provide this feature ever, because once you lose a majority you can't trust the consistency of the data in the minority, which means the SQL layer will have to deal with any type of inconsistent view of the underlying KV store.

**Closed by tschottdorf** 2018-06-19 14:49 UTC
Labels: C-enhancement
