### ISSUE TITLE
kvserver/rangefeed: checkpoint events can cause OOMs

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#114190] opened 2023-11-09 21:19 UTC
**Describe the problem**

OOMs were observed during a large scale test, specifically when testing changefeed / rangefeed performance.

Heap profiles point the finger at checkpoint events. Retained size and number of objects is far beyond what would be expected if memory budgets were being respected:

`inuse_space`:

![Screenshot 2023-11-09 at 12 50 49 PM](https://github.com/cockroachdb/cockroach/assets/804457/3b1e6b77-5826-4ace-89d9-e695a1179a89)

`inuse_objects`:

<img width="639" alt="Screenshot 2023-11-09 at 1 08 15 PM" src="https://github.com/cockroachdb/cockroach/assets/804457/eb04bdd0-50ca-4f2e-af7c-a055ba70cc38">

**Environment:**
 - CockroachDB version `V23.2.0-ALPHA.6-DEV`
 - Server OS: Linux.

**Additional context**

More context [here](https://cockroachlabs.slack.com/archives/C05VAJ5H3QS/p1699556601555169) (internal).

Debugging artifacts can be found [here](https://drive.google.com/drive/folders/1yYDIGUeCw_LmSFQCE_-QuCeM-7heOQ1o) (internal).

Jira issue: CRDB-33387

**Comment by nicktrav** [comment] 2023-11-09 21:20
cc @cockroachdb/cdc

**Comment by erikgrinaker** [comment] 2023-11-10 11:45
This seems legit. The changefeed processors struggled to keep up for whatever reason, and we don't subject checkpoints to memory budgets. The checkpoint events were likely sitting around in the registration channel buffers, which have a 4096-event size per replica (so 614M events with 150k replicas, which can eat up to 40 GB memory if they're all filled up -- which is very unlikely, but gives an upper bound).

https://github.com/cockroachdb/cockroach/blob/ab00ae96196b3b2ca8b77d1ec3bce35050316f1d/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L772-L773

https://github.com/cockroachdb/cockroach/blob/96409753f5c10669506b0b168d8800ec47ce4a30/pkg/kv/kvserver/rangefeed/processor.go#L953-L967

**Comment by miretskiy** [comment] 2023-11-10 15:16
I don't know if this is a release blocker -- it's not a regression.  @erikgrinaker ?

**Comment by erikgrinaker** [comment] 2023-11-10 15:18
Yeah, not a blocker. It has always been like this, and it isn't clear that a fix would be safe this late in the cycle.

**Comment by wenyihu6** [comment] 2024-03-18 17:47
Each rangefeed processor has an event buffering channel eventC. These events could point to large underlying data structure, and keeping them buffered in the channel prevents the underlying data from being garbage collected. To mitigate OOMs, we previously introduced memory budget to limit event buffering to the eventC channel. 
https://github.com/cockroachdb/cockroach/blob/690c67f1cdb3ac5797924c7c918716b3355e6dd8/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L64

This is how the memory accounting model works currently:

Before sending an event to the eventC channel, it calculatesDataSize based on the event to predict how much memory an event would take. It tries to allocate memory from the budget feed. The event then holds onto the same memory alloc and passed to registrations as part of a shared event when publishing the events. As the registry publishes the event to registrations, it will create a new rangefeed event (e.x.https://github.com/cockroachdb/cockroach/blob/aa58da93a7fa83bbf905c2b096b9f1954d35d402/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L748-L757) based on event c and a shared event holding the memory alloc. It then increases the reference count of the memory alloc. As registration publishes the event to its stream, it decreases the reference count of the memory alloc https://github.com/cockroachdb/cockroach/blob/6fcbdfcd9ac29420751b9e9f96350092028d23dc/pkg/kv/kvserver/rangefeed/registry.go#L343. The memory is then returned back to the budget feed when reference count becomes zero https://github.com/cockroachdb/cockroach/blob/3df5f2c9b1bf280e7918c197725250871b4b3776/pkg/kv/kvserver/rangefeed/budget.go#L263-L264.

However, the current memory accounting did not have a good way to predict the memory footprint of events. It uses calculateDateSize which 1. Does not account for memory of the new RangeFeedEvents that could be spawned (such as checkpoint events https://github.com/cockroachdb/cockroach/blob/6681efbbd7d49f09167febc9ef8db01b191a77ab/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L806) 2. inaccurately uses protobuf-encoded wire size for data (https://github.com/cockroachdb/cockroach/blob/6681efbbd7d49f09167febc9ef8db01b191a77ab/pkg/kv/kvserver/rangefeed/processor.go#L303) 3. does not account for memory of the base structs.

The challenging part of this issue is we are not sure if new rangefeed events can be spawned before buffering event e to the eventC channel. 
- Solution 1: Ideally, we would want to allocate memory only when we know for sure that we are publishing a checkpoint event so that we are not over- or under-accounting. This is hard since once the processor sends the event to the eventC channel, it is committed to sending it unless we try to disconnect the scheduler. It cannot backoff and decide not to send it if it cannot acquire a memory budget. 
- Solution 2: We can use the processor's resolved timestamp to predict if a checkpoint event will happen. But calling p.rts.ConsumeLogicalOp for memory accounting can change internal field unresolvedIntentQueue. To resolve this, we could make a deep copy of rts, but this is on a hot path and could introduce significant overhead. 
- Solution 3: We over-accounts at the beginning to account for everything that could have happened. If the memory turns out to be not needed, we de-allocates the memory right away to prevent registrations from holding onto unnecessary memory for too long.  (Open pr: https://github.com/cockroachdb/cockroach/pull/120550 ,https://github.com/cockroachdb/cockroach/pull/120348)
- Solution 4: We roughly estimate the memory and sacrifice some precision for simplicity. We are allowing small overhead of shared event structs and checkpoint events caused by logical ops to slip away from memory accounting. (Open pr: https://github.com/cockroachdb/cockroach/pull/120347)

Currently, we are picking solution 4 for its simplicity and will revisit this topic if anything comes up. 

**More details for solution 4**
Instead of accounting memory for both the current event and future rangefeed events, it will always pick the maximum memory between the two. It also allows additional shared event overhead (should be very small) and checkpoint events (caused by logical ops) (should be rare) to slip away. 
- For logical ops, we always take current event memory. Current event memory is always larger if we assume no checkpoint events will be published for any logical ops. (same underlying data)
- For checkpoint events (ct and initRTS), we always take checkpoint rangefeed event. Future events are larger. (curr: 80, future: 152) (span points to the same underlying data)
- For sst events, we always take future rangefeed event (future base structs is larger than current base structs by 2) (same underlying data).
- For sync events, we always take current events. (current memory usage is larger as no future events will be created.

**Closed** 2024-03-22 20:50 UTC
Labels: C-bug, A-cdc, T-cdc, O-testcluster, A-kv-rangefeed, branch-release-23.2, O-23.2-scale-testing
