### ISSUE TITLE
Sentry: signal_unix.go:881: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#132292] opened 2024-10-10 08:55 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5977601345/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5977601345/?referrer=webhooks_plugin)

Panic Message:

```
signal_unix.go:881: runtime error: invalid memory address or nil pointer dereference
(1) attached stack trace
  -- stack trace:
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:881
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).readProbeImpl
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:434
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).readProbe
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:363
  | github.com/cockroachdb/cockroach/pkg/kv/kvprober.(*Prober).Start.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvprober/kvprober.go:341
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:503
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (2) runtime error: invalid memory address or nil pointer dereference
Error types: (1) *withstack.withStack (2) runtime.errorString
-- report composition:
runtime.errorString
signal_unix.go:881: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/util/stop/stopper.go#L502-L504](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/util/stop/stopper.go#L502-L504)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L340-L342](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L340-L342)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L362-L364](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L362-L364)
[https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L433-L435](https://github.com/cockroachdb/cockroach/blob/a55b0171112fc9471764f6fe08d10f6fe323ff50/pkg/kv/kvprober/kvprober.go#L433-L435)
[GOROOT/src/runtime/signal_unix.go#L880-L882](GOROOT/src/runtime/signal_unix.go#L880-L882)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 503
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).Start.func1.1 at line 341
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).readProbe at line 363
pkg/kv/kvprober/kvprober.go in pkg/kv/kvprober.(*Prober).readProbeImpl at line 434
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 881
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.0-alpha.1 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.3.0-alpha.1 |
| Cockroach SHA | a55b0171112fc9471764f6fe08d10f6fe323ff50 |
| # of CPUs | 2 |
| # of Goroutines | 739 |

Jira issue: CRDB-42928

**Comment by stevendanna** [comment] 2024-10-10 12:28
Looks like a duplicate of #131672

**Closed by stevendanna** 2024-10-10 12:28 UTC
Labels: C-bug, O-sentry
