### ISSUE TITLE
server/ui: Command queue debug page fails with internal error if run against wrong node

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#24968] opened 2018-04-21 20:40 UTC
The command queue debug page only works if you load it on a node that contains a replica for the range.

For example, on Adriatic, I was looking at the range debug page for r15 on node 1. I clicked on the "Visualize" link for the "CmdQ State", but was immediately greeted with an internal server error:

<img width="1252" alt="screen shot 2018-04-21 at 4 26 17 pm" src="https://user-images.githubusercontent.com/7085343/39088579-90f228de-4582-11e8-85b5-9fd6ede58ccf.png">

This is because I was browsing node 1's admin UI, but the range doesn't have a replica on node 1. The page loads properly if I open it from a node that contains a replica, even if that node's replica isn't the current leaseholder.

The page should be made to load properly regardless of which node it's opened on.

**Comment by couchand** [comment] 2018-04-24 15:38
Dupe of #21239

**Closed by couchand** 2018-04-24 15:38 UTC
