### ISSUE TITLE
Test failure in CI build 1005

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#507] opened 2015-03-30 14:09 UTC
The following test appears to have failed:

[#1005](https://circleci.com/gh/cockroachdb/cockroach/1005):

```
I0330 14:05:31.951899      69 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:119 XXX_unrecognized:[]}
I0330 14:05:31.951966      69 multiraft.go:641] New Entry[0]: 6/119 EntryNormal 00000000000000001a0bb37b0107586e: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:799 > cmd_id:<wall_time:0 random:0 > key:"nLogmNnTLx" user:"root" rep
I0330 14:05:31.952027      69 multiraft.go:644] Committed Entry[0]: 6/119 EntryNormal 00000000000000001a0bb37b0107586e: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:799 > cmd_id:<wall_time:0 random:0 > key:"nLogmNnTLx" user:"root" rep
I0330 14:05:31.952592      69 queue.go:207] processing range range=1 (""-"HtiUfUFpOF") from split queue...
I0330 14:05:31.952996      69 range.go:1865] initiating a split of range 1 "\"\""-"\"HtiUfUFpOF\"" at key "\"FnxZTCgeqD\""
panic: test timed out after 30s

goroutine 697 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0xfe3028, 0x1460380, 0x2b, 0x2b, 0xc208029a01)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:117 +0xaa6
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop(0xc20800bda0, 0xc2081037c0, 0xc20828b180)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:208 +0x55a
created by github.com/cockroachdb/cockroach/storage.(*baseQueue).Start
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:132 +0x5d
FAIL	github.com/cockroachdb/cockroach/kv	30.053s
=== RUN TestHeartbeatSingleGroup
I0330 14:05:31.622847      77 multiraft.go:407] node 1 starting
I0330 14:05:31.622981      77 multiraft.go:407] node 2 starting
I0330 14:05:31.623181      77 raft.go:390] raft: 1 became follower at term 5
I0330 14:05:31.623311      77 raft.go:207] raft: newRaft 1 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0330 14:05:31.624156      77 raft.go:390] raft: 2 became follower at term 5
I0330 14:05:31.624221      77 raft.go:207] raft: newRaft 2 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0330 14:05:31.624341      77 raft.go:464] raft: 1 is starting a new election at term 5
I0330 14:05:31.624366      77 raft.go:403] raft: 1 became candidate at term 6
I0330 14:05:31.624379      77 raft.go:447] raft: 1 received vote from 1 at term 6
I0330 14:07:29.431221     256 multiraft.go:644] Committed Entry[0]: 6/13 EntryNormal 13d04bd2855bc0fb45a6e3cafccae224: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1427724449429045499 random:5018949295715050020 > user:"" repli
I0330 14:07:29.432264     256 kv.go:125] failed Increment: mvcc.go:450: attempted access to empty key
I0330 14:07:29.432360     256 retry.go:85]  failed an iteration: mvcc.go:450: attempted access to empty key
I0330 14:07:29.432426     256 retry.go:100]  failed; retrying in 50ms
==================
WARNING: DATA RACE
Write by goroutine 54:
  github.com/cockroachdb/cockroach/storage.TestAllocateErrorAndRecovery()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc_test.go:162 +0x874
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 74:
  github.com/cockroachdb/cockroach/storage.func·009()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:114 +0x24e
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/storage.(*IDAllocator).allocateBlock()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:118 +0x158
  github.com/cockroachdb/cockroach/storage.func·008()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:92 +0x7a

Goroutine 54 (running) created at:
I0330 14:07:29.431221     256 multiraft.go:644] Committed Entry[0]: 6/13 EntryNormal 13d04bd2855bc0fb45a6e3cafccae224: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1427724449429045499 random:5018949295715050020 > user:"" repli
I0330 14:07:29.432264     256 kv.go:125] failed Increment: mvcc.go:450: attempted access to empty key
I0330 14:07:29.432360     256 retry.go:85]  failed an iteration: mvcc.go:450: attempted access to empty key
I0330 14:07:29.432426     256 retry.go:100]  failed; retrying in 50ms
==================
WARNING: DATA RACE
Write by goroutine 54:
  github.com/cockroachdb/cockroach/storage.TestAllocateErrorAndRecovery()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc_test.go:162 +0x874
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 74:
  github.com/cockroachdb/cockroach/storage.func·009()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:114 +0x24e
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/storage.(*IDAllocator).allocateBlock()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:118 +0x158
  github.com/cockroachdb/cockroach/storage.func·008()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:92 +0x7a

Goroutine 54 (running) created at:
I0330 14:05:31.951899      69 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:119 XXX_unrecognized:[]}
I0330 14:05:31.951966      69 multiraft.go:641] New Entry[0]: 6/119 EntryNormal 00000000000000001a0bb37b0107586e: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:799 > cmd_id:<wall_time:0 random:0 > key:"nLogmNnTLx" user:"root" rep
I0330 14:05:31.952027      69 multiraft.go:644] Committed Entry[0]: 6/119 EntryNormal 00000000000000001a0bb37b0107586e: raft_id:2 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:799 > cmd_id:<wall_time:0 random:0 > key:"nLogmNnTLx" user:"root" rep
I0330 14:05:31.952592      69 queue.go:207] processing range range=1 (""-"HtiUfUFpOF") from split queue...
I0330 14:05:31.952996      69 range.go:1865] initiating a split of range 1 "\"\""-"\"HtiUfUFpOF\"" at key "\"FnxZTCgeqD\""
panic: test timed out after 30s

goroutine 697 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0xfe3028, 0x1460380, 0x2b, 0x2b, 0xc208029a01)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/storage/split_queue.go:117 +0xaa6
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop(0xc20800bda0, 0xc2081037c0, 0xc20828b180)
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:208 +0x55a
created by github.com/cockroachdb/cockroach/storage.(*baseQueue).Start
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:132 +0x5d
FAIL	github.com/cockroachdb/cockroach/kv	30.053s
=== RUN TestHeartbeatSingleGroup
I0330 14:05:31.622847      77 multiraft.go:407] node 1 starting
I0330 14:05:31.622981      77 multiraft.go:407] node 2 starting
I0330 14:05:31.623181      77 raft.go:390] raft: 1 became follower at term 5
I0330 14:05:31.623311      77 raft.go:207] raft: newRaft 1 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0330 14:05:31.624156      77 raft.go:390] raft: 2 became follower at term 5
I0330 14:05:31.624221      77 raft.go:207] raft: newRaft 2 [peers: [1,2], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0330 14:05:31.624341      77 raft.go:464] raft: 1 is starting a new election at term 5
I0330 14:05:31.624366      77 raft.go:403] raft: 1 became candidate at term 6
I0330 14:05:31.624379      77 raft.go:447] raft: 1 received vote from 1 at term 6

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2015-03-30 14:54
Duplicate of #501

**Closed** 2015-03-30 15:24 UTC
Labels: test-failure
