### ISSUE TITLE
Panic when visiting databases page post schema change - v20.1.0-beta.4

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#47009] opened 2020-04-03 20:55 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
Downloaded `CockroachDB CCL v20.1.0-beta.4 (x86_64-apple-darwin14, built 2020/03/24 01:31:53, go1.13.5)`

`cockroach start --insecure --host localhost --background`

`cockroach sql --insecure --host localhost -e "create database movr;"`

`docker run -it --rm cockroachdb/movr:movr-20.1-beta.20.4.1 --url "postgres://root@docker.for.mac.localhost:26257/movr?sslmode=disable" load --num-users 100 --num-rides 100 --num-vehicles 10`

`docker run -it --rm cockroachdb/movr:movr-20.1-beta.20.4.1 --url "postgres://root@docker.for.mac.localhost:26257/movr?sslmode=disable" --num-threads 10 run --city "new york" --city "boston"`

In a new terminal
`docker run -it --rm cockroachdb/movr:movr-20.1-beta.20.4.1 --url "postgres://root@docker.for.mac.localhost:26257/movr?sslmode=disable" configure-multi-region`

That runs the following commands
```
===primary key alters===
ALTER TABLE users ALTER PRIMARY KEY USING COLUMNS (city, id);
ALTER TABLE rides ALTER PRIMARY KEY USING COLUMNS (city, id);
ALTER TABLE vehicle_location_histories ALTER PRIMARY KEY USING COLUMNS (city, ride_id, timestamp);
ALTER TABLE vehicles ALTER PRIMARY KEY USING COLUMNS (city, id);
ALTER TABLE user_promo_codes ALTER PRIMARY KEY USING COLUMNS (city, user_id, code);
===foreign key alters===
DROP INDEX users_city_idx;
ALTER TABLE vehicles DROP CONSTRAINT fk_owner_id_ref_users;
CREATE INDEX ON vehicles (city, owner_id);
DROP INDEX vehicles_auto_index_fk_owner_id_ref_users;
DROP INDEX vehicles_city_idx;
ALTER TABLE vehicles ADD CONSTRAINT fk_owner_id_ref_users_mr FOREIGN KEY (city, owner_id) REFERENCES users (city,id);
ALTER TABLE rides DROP CONSTRAINT fk_rider_id_ref_users;
CREATE INDEX ON rides (city, rider_id);
ALTER TABLE rides ADD CONSTRAINT fk_rider_id_ref_users_mr FOREIGN KEY (city, rider_id) REFERENCES users (city,id);
ALTER TABLE rides DROP CONSTRAINT fk_vehicle_id_ref_vehicles;
CREATE INDEX ON rides (city, vehicle_id);
ALTER TABLE rides ADD CONSTRAINT fk_vehicle_id_ref_vehicles_mr FOREIGN KEY (city, vehicle_id) REFERENCES vehicles (city,id);
DROP INDEX rides_auto_index_fk_rider_id_ref_users;
DROP INDEX rides_auto_index_fk_vehicle_id_ref_vehicles;
ALTER TABLE user_promo_codes DROP CONSTRAINT fk_user_id_ref_users;
ALTER TABLE user_promo_codes ADD CONSTRAINT fk_user_id_ref_users_mr FOREIGN KEY (city, user_id) REFERENCES users (city,id);
```

Navigated to: `http://localhost:8080/#/database/movr/table/rides`

![image](https://user-images.githubusercontent.com/894257/78403883-3a96e580-75cb-11ea-886f-169f992fe147.png)

In the logs I see 

```
Nathaniels-MacBook-Pro-2:~ nate$ more /Users/nate/cockroach-data/logs/cockroach.log
I200403 20:40:57.500047 1 util/log/sync_buffer.go:70  [config] file created at: 2020/04/03 20:40:57
I200403 20:40:57.500047 1 util/log/sync_buffer.go:70  [config] running on machine: Nathaniels-MacBook-Pro-2
I200403 20:40:57.500047 1 util/log/sync_buffer.go:70  [config] binary: CockroachDB CCL v20.1.0-beta.4 (x86_64-apple-darwin14, built 2020/03/24 01:31:53, go1.13.5)
I200403 20:40:57.500047 1 util/log/sync_buffer.go:70  [config] arguments: [cockroach start --insecure --host localhost]
I200403 20:40:57.500047 1 util/log/sync_buffer.go:70  line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓
I200403 20:40:57.500046 1 cli/start.go:1187  logging to directory /Users/nate/cockroach-data/logs
W200403 20:40:57.500701 1 cli/start.go:1233  RUNNING IN INSECURE MODE!

- Your cluster is open for any client that can access localhost.
- Any user, even root, can log in without providing a password.
- Any user, connecting as root, can read or write any data in your cluster.
- There is no network encryption nor authentication, and thus no confidentiality.

Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v20.1/secure-a-cluster.html
W200403 20:40:57.500772 1 cli/start.go:1108  Using the default setting for --cache (128 MiB).
  A significantly larger value is usually needed for good performance.
  If you have a dedicated server a reasonable setting is --cache=.25 (2.0 GiB).
I200403 20:40:57.500803 1 cli/start.go:1247  CockroachDB CCL v20.1.0-beta.4 (x86_64-apple-darwin14, built 2020/03/24 01:31:53, go1.13.5)
W200403 20:40:57.604915 1 cli/start.go:537  running 'cockroach start' without --join is deprecated.
Consider using 'cockroach start-single-node' or 'cockroach init' instead.
I200403 20:40:57.615722 1 server/config.go:398  system total memory: 8.0 GiB
I200403 20:40:57.615788 1 server/config.go:400  server configuration:
max offset             500000000
cache size             128 MiB
SQL memory pool size   2.0 GiB
scan interval          10m0s
scan min idle time     10ms
scan max idle time     1s
event log enabled      true
...skipping...
panic: unknown PG name for oid 0

goroutine 54862 [running]:
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).PGName(0xc007563608, 0x82eb580, 0xa87c360)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/types/types.go:1077 +0x148
github.com/cockroachdb/cockroach/pkg/sql.glob..func64.1.1(0xc0075635f0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:417 +0x33f
github.com/cockroachdb/cockroach/pkg/sql.forEachColumnInTable(0xc007563000, 0xc007ba30d0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1705 +0x86
github.com/cockroachdb/cockroach/pkg/sql.glob..func64.1(0xc003e47240, 0x79b1306, 0x6, 0xc007563000, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:380 +0x10d
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDesc.func1(0xc003e47240, 0x79b1306, 0x6, 0xc007563000, 0xc003b189b0, 0x1, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1517 +0x4d
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookupInternal(0x826fe40, 0xc005381700, 0xc00707c3b8, 0xc003e47080, 0x0, 0x0, 0xc007ba3288, 0xc003c019a0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1677 +0x432
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDescWithTableLookup(...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1582
github.com/cockroachdb/cockroach/pkg/sql.forEachTableDesc(0x826fe40, 0xc005381700, 0xc00707c3b8, 0xc003e47080, 0x0, 0xc007ba32e8, 0x50, 0x76c7980)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:1511 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.glob..func64(0x826fe40, 0xc005381700, 0xc00707c3b8, 0xc003e47080, 0xc003c019a0, 0xc003c01950, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:377 +0x81
github.com/cockroachdb/cockroach/pkg/sql.virtualDefEntry.getPlanInfo.func1(0x826fe40, 0xc005381700, 0xc00707c3b8, 0xc0042d8fa0, 0x6, 0xc00004e000, 0x74ce520, 0x7575700, 0xd36f708)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:274 +0x354
github.com/cockroachdb/cockroach/pkg/sql.(*execFactory).ConstructVirtualScan.func1(0x826fe40, 0xc005381700, 0xc00707c3b8, 0x400c85a, 0x74ce520, 0x7575700, 0xc005381701)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_exec_factory.go:144 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec(0xc005380e00, 0x826fe40, 0xc005381700, 0xc005523180, 0xc00707c3b8, 0x0, 0x5)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/delayed.go:48 +0x57
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x79c5364, 0xd, 0x8271a40, 0xc005380e00, 0x0, 0x0)
:panic: unknown PG name for oid 0
```

Debug zip doesn't work as I get:
```
requesting database details for movr... writing: debug/schema/movr@details.json
6 tables found
requesting table details for movr.promo_codes... writing: debug/schema/movr/promo_codes.json
requesting table details for movr.rides... writing: debug/schema/movr/rides.json
requesting table details for movr.user_promo_codes... writing: debug/schema/movr/user_promo_codes.json
requesting table details for movr.users... writing: debug/schema/movr/users.json
requesting table details for movr.vehicle_location_histories... writing: debug/schema/movr/vehicle_location_histories.json
requesting table details for movr.vehicles... writing: debug/schema/movr/vehicles.json
requesting database details for postgres... writing: debug/schema/postgres@details.json
0 tables found
requesting database details for system... writing: debug/schema/system@details.json
26 tables found
requesting table details for system.comments... writing: debug/schema/system/comments.json
  ^- resulted in rpc error: code = Unavailable desc = transport is closing
requesting table details for system.descriptor... writing: debug/schema/system/descriptor.json
  ^- resulted in rpc error: code = Canceled desc = grpc: the client connection is closing
requesting table details for system.eventlog... writing: debug/schema/system/eventlog.json
  ^- resulted in rpc error: code = Canceled desc = grpc: the client connection is closing
requesting table details for system.jobs... writing: debug/schema/system/jobs.json
  ^- resulted in rpc error: code = Canceled desc = grpc: the client connection is closing
requesting table details for system.lease... writing: debug/schema/system/lease.json
  ^- resulted in rpc error: code = Canceled desc = grpc: the client connection is closing
requesting table details for system.locations... writing: debug/schema/system/locations.json
  ^- resulted in rpc error: code = Canceled desc = grpc: the client connection is closing
```

[cockroach.log](https://github.com/cockroachdb/cockroach/files/4429873/cockroach.log)

**Comment by nstewart** [comment] 2020-04-03 21:32
Unfortunately, I cannot reproduce this -- just tried. I was also clicking around the statements pages at the time. I'll leave open for now in case the panic rings any bells

**Comment by awoods187** [comment] 2020-04-03 21:40
It's strange because I didn't see this either running the commands the first time or when I tried reproducing this after you filed the issue.

**Comment by jordanlewis** [comment] 2020-04-03 22:17
@rohany, it seems like we accidentally leave some columns in a bad state. Perhaps the column is zeroed out? In any case, seems like it doesn't have a type, which causes this panic when somebody queries its columns via a virtual table.

**Comment by rohany** [comment] 2020-04-03 22:37
Huh, this is strange -- we don't touch any of the column descriptors in the primary key change, so there must be something subtle going on. I'll see if I can repro this.

**Comment by rohany** [comment] 2020-04-03 23:26
@nstewart was this a oneoff thing? I haven't succeeded at reproducing it either

**Comment by nstewart** [comment] 2020-04-04 03:17
After the first crash, it would crash nearly every time I visited the page. After I wiped the database I couldn’t reproduce it again

Nate Stewart
Chief Product Officer, Cockroach Labs
Check out our blog: www.cockroachlabs.com/blog/ ( http://www.cockroachlabs.com/blog/ )

**Comment by jordanlewis** [comment] 2020-10-06 20:47
Closing due to age / no repro

**Closed by jordanlewis** 2020-10-06 20:47 UTC
