### ISSUE TITLE
sql: Joining Interleaved table with parent table over UUID typed column fails.

### ISSUE THREAD

**Issue by derkan** [cockroachdb/cockroach#25838] opened 2018-05-23 11:13 UTC
Is this a question, feature request, or bug report?
> BUG

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. 

```
80523 10:34:14.588013 1 util/log/clog.go:1134  [config] file created at: 2018/05/23 10:34:14
I180523 10:34:14.588013 1 util/log/clog.go:1134  [config] running on machine: derkan
I180523 10:34:14.588013 1 util/log/clog.go:1134  [config] binary: CockroachDB CCL v2.0.2 (x86_64-unknown-linux-gnu, built 2018/05/21 14:55:20, go1.10)
I180523 10:34:14.588013 1 util/log/clog.go:1134  [config] arguments: [/usr/local/bin/cockroach start --insecure --host=localhost --store=./db/data,attrs=ssd,size=2GiB --log-dir=./db/log --http-port=8088]
I180523 10:34:19.348514 15 cli/start.go:595  [config] clusterID: fdae8641-2305-40e0-b2e5-f8501d4477d5
```
2. Please describe the issue you observed:

This code returns no rows although rows are existing(please look at result of last sql statement):
```sql
CREATE TABLE accounts (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	"name" STRING(128) NOT NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX accounts_name_key ("name" ASC)
);

CREATE TABLE users (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	"name" STRING(128) NOT NULL,
	account_id UUID NOT NULL,
	username STRING(128) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX users_name_key ("name" ASC),
	UNIQUE INDEX users_username_key (username ASC),
	CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id),
	INDEX users_auto_index_users_account_id_fkey (account_id ASC)
);

CREATE TABLE documents (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL,
	"name" STRING(256) NOT NULL,
	CONSTRAINT documents_pkey PRIMARY KEY (id ASC),
	CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id),
	UNIQUE INDEX documents_user_id_name_key (user_id ASC, "name" ASC)
) INTERLEAVE IN PARENT users (id);

INSERT INTO accounts(name) VALUES('Test Account');
INSERT INTO users(name,username,account_id) SELECT 'Test User','test',id FROM accounts;
INSERT INTO documents(name,user_id) SELECT 'Document',id FROM users;

SELECT * FROM documents;
+--------------------------------------+--------------------------------------+----------+
|                  id                  |               user_id                |   name   |
+--------------------------------------+--------------------------------------+----------+
| 0c1de31d-2af7-4051-9ecc-e941ec0a33f4 | f0a20d89-19cc-432d-9c8e-a69dd796f7cd | Document |
+--------------------------------------+--------------------------------------+----------+
(1 row)

select id,name from users where id='f0a20d89-19cc-432d-9c8e-a69dd796f7cd';
+--------------------------------------+-----------+
|                  id                  |   name    |
+--------------------------------------+-----------+
| f0a20d89-19cc-432d-9c8e-a69dd796f7cd | Test User |
+--------------------------------------+-----------+
(1 row)

SELECT documents.name,users.account_id FROM documents JOIN users  ON documents.user_id = users.id;
+----------+--------------------------------------+
|   name   |              account_id              |
+----------+--------------------------------------+
| Document | 726a2e47-b225-40b4-a67b-e8859e6ae771 |
+----------+--------------------------------------+
(1 row)

select * from documents where id='0c1de31d-2af7-4051-9ecc-e941ec0a33f4';
+--------------------------------------+--------------------------------------+----------+
|                  id                  |               user_id                |   name   |
+--------------------------------------+--------------------------------------+----------+
| 0c1de31d-2af7-4051-9ecc-e941ec0a33f4 | f0a20d89-19cc-432d-9c8e-a69dd796f7cd | Document |
+--------------------------------------+--------------------------------------+----------+
(1 row)


SELECT documents.name,users.account_id FROM documents JOIN users ON documents.user_id = users.id 
WHERE documents.id = '0c1de31d-2af7-4051-9ecc-e941ec0a33f4';
+------+------------+
| name | account_id |
+------+------------+
+------+------------+
(0 rows)
```

But if I change primary key columns' types to `SERIAL`, it works:

```sql
CREATE TABLE accounts_b (
	id SERIAL NOT NULL,
	"name" STRING(128) NOT NULL,
	CONSTRAINT accounts_b_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX accounts_b_name_key ("name" ASC)
);

CREATE TABLE users_b (
	id SERIAL NOT NULL,
	"name" STRING(128) NOT NULL,
	account_id INT NOT NULL,
	username STRING(128) NOT NULL,
	CONSTRAINT users_b_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX users_b_name_key ("name" ASC),
	UNIQUE INDEX users_b_username_key (username ASC),
	CONSTRAINT users_b_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts_b (id),
	INDEX users_b_auto_index_users_b_account_id_fkey (account_id ASC)
);

CREATE TABLE documents_b (
	id SERIAL NOT NULL,
	user_id INT NOT NULL,
	"name" STRING(256) NOT NULL,
	CONSTRAINT documents_b_pkey PRIMARY KEY (id ASC),
	CONSTRAINT documents_b_user_id_fkey FOREIGN KEY (user_id) REFERENCES users_b (id),
	UNIQUE INDEX documents_b_user_id_name_key (user_id ASC, "name" ASC)
) INTERLEAVE IN PARENT users_b (id);

INSERT INTO accounts_b(name) VALUES('Test Account');
INSERT INTO users_b(name,username,account_id) SELECT 'Test User','test',id FROM accounts_b;
INSERT INTO documents_b(name,user_id) SELECT 'Document',id FROM users_b;

SELECT * FROM documents_b;
+--------------------+--------------------+----------+
|         id         |      user_id       |   name   |
+--------------------+--------------------+----------+
| 350626680253906945 | 350626680226086913 | Document |
+--------------------+--------------------+----------+
(1 row)


select id,name from users_b where id=350626680226086913;
+--------------------+-----------+
|         id         |   name    |
+--------------------+-----------+
| 350626680226086913 | Test User |
+--------------------+-----------+
(1 row)

SELECT documents_b.name,users_b.account_id FROM documents_b JOIN users_b  ON documents_b.user_id = users_b.id;
+----------+--------------------+
|   name   |     account_id     |
+----------+--------------------+
| Document | 350626680201871361 |
+----------+--------------------+
(1 row)



SELECT documents_b.name,users_b.account_id FROM documents_b JOIN users_b ON documents_b.user_id = users_b.id 
WHERE documents_b.id = 350626680253906945;
+----------+--------------------+
|   name   |     account_id     |
+----------+--------------------+
| Document | 350626680201871361 |
+----------+--------------------+
(1 row)
```

**Comment by knz** [comment] 2018-05-23 11:38
cc @jordanlewis @arjunravinarayan

**Comment by jordanlewis** [comment] 2018-05-23 22:40
Thank you for the extraordinarily pleasant reproduction instructions!

However, I cannot reproduce this issue. Perhaps it has been solved since version 2.0.2?

```
CREATE TABLE accounts (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	"name" STRING(128) NOT NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX accounts_name_key ("name" ASC)
);

CREATE TABLE users (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	"name" STRING(128) NOT NULL,
	account_id UUID NOT NULL,
	username STRING(128) NOT NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id ASC),
	UNIQUE INDEX users_name_key ("name" ASC),
	UNIQUE INDEX users_username_key (username ASC),
	CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id),
	INDEX users_auto_index_users_account_id_fkey (account_id ASC)
);

CREATE TABLE documents (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	user_id UUID NOT NULL,
	"name" STRING(256) NOT NULL,
	CONSTRAINT documents_pkey PRIMARY KEY (id ASC),
	CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id),
	UNIQUE INDEX documents_user_id_name_key (user_id ASC, "name" ASC)
) INTERLEAVE IN PARENT users (id);

INSERT INTO accounts(name) VALUES('Test Account');
INSERT INTO users(name,username,account_id) SELECT 'Test User','test',id FROM accounts;
INSERT INTO documents(name,user_id) SELECT 'Document',id FROM users;

SELECT * FROM documents;
+--------------------------------------+--------------------------------------+----------+
|                  id                  |               user_id                |   name   |
+--------------------------------------+--------------------------------------+----------+
| ec7ddacb-39e3-4e5d-9a1e-963093965e36 | 11045aa1-f1c9-4324-a650-1b7f50a0de24 | Document |
+--------------------------------------+--------------------------------------+----------+
(1 row)

Time: 1.507924ms

root@127.0.0.1:54079/demo> SELECT documents.name,users.account_id FROM documents JOIN users ON documents.user_id = users.id
WHERE documents.id = 'ec7ddacb-39e3-4e5d-9a1e-963093965e36';
+----------+--------------------------------------+
|   name   |              account_id              |
+----------+--------------------------------------+
| Document | 6dbc1a75-eee5-4966-b466-fc5a25eab0e6 |
+----------+--------------------------------------+
(1 row)

Time: 4.958171ms
```

**Comment by jordanlewis** [comment] 2018-05-23 22:50
I can reproduce your problem on the `release-2.0` branch, indicating the fix has been made to master but not backported to `release-2.0`. Now, it's just a matter of tracking down what the fix was, and backporting it.

Thank you for reporting this issue!

**Comment by jordanlewis** [comment] 2018-05-24 20:56
Hmm, actually, I *can't* reproduce this on `release-2.0`, suggesting the first time that I tried, I didn't do the test correctly. I've created a logic test that runs your test scenario, and cannot reproduce on `master`, `release-2.0`, or `v2.0.2`.

Here's the test script. Does this match what you were doing? The format of this script is simple - statements get executed, `let` statements save their result to a `var`, and `query` statements compare their output to the value below the `----` and fail the test if the output differs.

```
statement ok
CREATE TABLE accounts (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        "name" STRING(128) NOT NULL,
        CONSTRAINT accounts_pkey PRIMARY KEY (id ASC),
        UNIQUE INDEX accounts_name_key ("name" ASC)
)

statement ok
CREATE TABLE users (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        "name" STRING(128) NOT NULL,
        account_id UUID NOT NULL,
        username STRING(128) NOT NULL,
        CONSTRAINT users_pkey PRIMARY KEY (id ASC),
        UNIQUE INDEX users_name_key ("name" ASC),
        UNIQUE INDEX users_username_key (username ASC),
        CONSTRAINT users_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts (id),
        INDEX users_auto_index_users_account_id_fkey (account_id ASC)
)

statement ok
CREATE TABLE documents (
        id UUID NOT NULL DEFAULT gen_random_uuid(),
        user_id UUID NOT NULL,
        "name" STRING(256) NOT NULL,
        CONSTRAINT documents_pkey PRIMARY KEY (id ASC),
        CONSTRAINT documents_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id),
        UNIQUE INDEX documents_user_id_name_key (user_id ASC, "name" ASC)
) INTERLEAVE IN PARENT users (id);

statement ok
INSERT INTO accounts(name) VALUES('Test Account')

statement ok
INSERT INTO users(name,username,account_id) SELECT 'Test User','test',id FROM accounts

let $docid
INSERT INTO documents(name,user_id) SELECT 'Document',id FROM users RETURNING id


query I
SELECT COUNT(*) FROM documents JOIN users ON documents.user_id = users.id
WHERE documents.id = '$docid'
----
1
```

**Comment by jordanlewis** [comment] 2018-06-13 22:32
Hi @derkan, finally was able to reproduce this problem. The issue is actually in `INSERT` - looks like there's a bug that causes any insert data source that draws from a randomized builtin (like `gen_random_uuid`) to sometimes invoke that builtin twice, which gives bad results. Will have a fix soon - thanks for your patience.

**Comment by jordanlewis** [comment] 2018-06-13 22:39
I spoke too soon, the root cause isn't quite right. But there's definitely something going wrong with `gen_random_uuid` - the problem goes away if the insert into the parent interleave uses a static UUID.

**Comment by jordanlewis** [comment] 2018-06-15 19:14
Hi @derkan, sorry for the delay. There's 2 problems here - the good news is that one of them you can fix. It's a misunderstanding about how interleaved tables work.

Your schema is probably not doing what you think it is. You've created a users table with a primary key `id`. Then, you've created a documents table with a different primary key, `id`, and an indexed column `user_id` that points to the `id` of the users table.

However, you then went ahead and interleaved the `documents` table into the `users` table on the *user* id. That's nonsensical - you're asking the database to store all documents with id `1` next to users with id `1`. I assume you wanted to store all documents next to the users with their `user_id` - but that's not possible unless you prefix the primary key of the documents table by `user_id`, giving a composite primary key `(user_id, id)`. If you do that, then you can interleave documents into users where `documents.user_id=users.id` by saying `INTERLEAVE IN PARENT users(user_id)`.

Does that make sense?



You've still discovered a real bug. It doesn't have to do with UUIDs, as it turns out, but just to do with interleaved table joins. We're going to fix that bug, but you should fix your schema, too.

**Closed** 2018-06-18 13:51 UTC
Labels: A-sql-execution, C-investigation, O-community
