### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestBaseQueuePurgatory

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6525] opened 2016-05-05 11:42 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/9dc275b7bc4447f18538c2398083fb6bb88a4e27

Stress build found a failed test:

```
=== RUN   TestBaseQueuePurgatory
W160505 06:55:01.712329 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160505 06:55:01.715130 storage/queue.go:496  [test] purgatory is now empty
--- FAIL: TestBaseQueuePurgatory (0.00s)
	queue_test.go:530: expected purgatory size of 10; got 9
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
1 runs so far, 0 failures, over 25s
14 runs so far, 0 failures, over 30s
15 runs so far, 0 failures, over 35s
15 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
23 runs so far, 0 failures, over 55s
29 runs so far, 0 failures, over 1m0s
29 runs so far, 0 failures, over 1m5s
30 runs so far, 0 failures, over 1m10s
30 runs so far, 0 failures, over 1m15s
36 runs so far, 0 failures, over 1m20s
43 runs so far, 0 failures, over 1m25s
44 runs so far, 0 failures, over 1m30s
45 runs so far, 0 failures, over 1m35s
45 runs so far, 0 failures, over 1m40s
50 runs so far, 0 failures, over 1m45s
58 runs so far, 0 failures, over 1m50s
60 runs so far, 0 failures, over 1m55s
61 runs so far, 0 failures, over 2m0s
62 runs so far, 0 failures, over 2m5s
66 runs so far, 0 failures, over 2m10s
73 runs so far, 0 failures, over 2m15s
74 runs so far, 0 failures, over 2m20s
76 runs so far, 0 failures, over 2m25s
77 runs so far, 0 failures, over 2m30s
80 runs so far, 0 failures, over 2m35s
87 runs so far, 0 failures, over 2m40s
90 runs so far, 0 failures, over 2m45s
91 runs so far, 0 failures, over 2m50s
92 runs so far, 0 failures, over 2m55s
96 runs so far, 0 failures, over 3m0s
102 runs so far, 0 failures, over 3m5s
106 runs so far, 0 failures, over 3m10s
107 runs so far, 0 failures, over 3m15s
109 runs so far, 0 failures, over 3m20s
115 runs so far, 0 failures, over 3m25s
118 runs so far, 0 failures, over 3m30s
123 runs so far, 0 failures, over 3m35s
123 runs so far, 0 failures, over 3m40s
126 runs so far, 0 failures, over 3m45s
131 runs so far, 0 failures, over 3m50s
134 runs so far, 0 failures, over 3m55s
139 runs so far, 0 failures, over 4m0s
139 runs so far, 0 failures, over 4m5s
142 runs so far, 0 failures, over 4m10s
147 runs so far, 0 failures, over 4m15s
152 runs so far, 0 failures, over 4m20s
155 runs so far, 0 failures, over 4m25s
155 runs so far, 0 failures, over 4m30s
158 runs so far, 0 failures, over 4m35s
163 runs so far, 0 failures, over 4m40s
168 runs so far, 0 failures, over 4m45s
171 runs so far, 0 failures, over 4m50s
171 runs so far, 0 failures, over 4m55s
174 runs so far, 0 failures, over 5m0s
178 runs so far, 0 failures, over 5m5s
183 runs so far, 0 failures, over 5m10s
185 runs so far, 0 failures, over 5m15s
186 runs so far, 0 failures, over 5m20s
188 runs so far, 0 failures, over 5m25s
192 runs so far, 0 failures, over 5m30s
197 runs so far, 0 failures, over 5m35s
199 runs so far, 0 failures, over 5m40s
199 runs so far, 0 failures, over 5m45s
202 runs so far, 0 failures, over 5m50s
207 runs so far, 0 failures, over 5m55s
212 runs so far, 0 failures, over 6m0s
214 runs so far, 0 failures, over 6m5s
215 runs so far, 0 failures, over 6m10s
218 runs so far, 0 failures, over 6m15s
223 runs so far, 0 failures, over 6m20s
228 runs so far, 0 failures, over 6m25s
230 runs so far, 0 failures, over 6m30s
232 runs so far, 0 failures, over 6m35s
235 runs so far, 0 failures, over 6m40s
239 runs so far, 0 failures, over 6m45s
244 runs so far, 0 failures, over 6m50s
245 runs so far, 0 failures, over 6m55s
246 runs so far, 0 failures, over 7m0s
249 runs so far, 0 failures, over 7m5s
254 runs so far, 0 failures, over 7m10s
258 runs so far, 0 failures, over 7m15s
259 runs so far, 0 failures, over 7m20s
261 runs so far, 0 failures, over 7m25s
264 runs so far, 0 failures, over 7m30s
267 runs so far, 0 failures, over 7m35s
272 runs so far, 0 failures, over 7m40s
272 runs so far, 0 failures, over 7m45s
276 runs so far, 0 failures, over 7m50s
279 runs so far, 0 failures, over 7m55s
283 runs so far, 0 failures, over 8m0s
286 runs so far, 0 failures, over 8m5s
288 runs so far, 0 failures, over 8m10s
290 runs so far, 0 failures, over 8m15s
293 runs so far, 0 failures, over 8m20s
298 runs so far, 0 failures, over 8m25s
300 runs so far, 0 failures, over 8m30s
303 runs so far, 0 failures, over 8m35s
306 runs so far, 0 failures, over 8m40s
308 runs so far, 0 failures, over 8m45s
312 runs so far, 0 failures, over 8m50s
314 runs so far, 0 failures, over 8m55s
318 runs so far, 0 failures, over 9m0s
321 runs so far, 0 failures, over 9m5s
325 runs so far, 0 failures, over 9m10s
327 runs so far, 0 failures, over 9m15s
330 runs so far, 0 failures, over 9m20s
333 runs so far, 0 failures, over 9m25s
336 runs so far, 0 failures, over 9m30s
338 runs so far, 0 failures, over 9m35s
344 runs so far, 0 failures, over 9m40s
344 runs so far, 0 failures, over 9m45s
348 runs so far, 0 failures, over 9m50s
350 runs so far, 0 failures, over 9m55s
353 runs so far, 0 failures, over 10m0s
357 runs so far, 0 failures, over 10m5s
357 runs so far, 0 failures, over 10m10s
362 runs so far, 0 failures, over 10m15s
364 runs so far, 0 failures, over 10m20s
367 runs so far, 0 failures, over 10m25s
370 runs so far, 0 failures, over 10m30s
372 runs so far, 0 failures, over 10m35s
377 runs so far, 0 failures, over 10m40s
377 runs so far, 0 failures, over 10m45s
380 runs so far, 0 failures, over 10m50s
385 runs so far, 0 failures, over 10m55s
386 runs so far, 0 failures, over 11m0s
392 runs so far, 0 failures, over 11m5s
393 runs so far, 0 failures, over 11m10s
395 runs so far, 0 failures, over 11m15s
400 runs so far, 0 failures, over 11m20s
401 runs so far, 0 failures, over 11m25s
407 runs so far, 0 failures, over 11m30s
408 runs so far, 0 failures, over 11m35s
410 runs so far, 0 failures, over 11m40s
416 runs so far, 0 failures, over 11m45s
416 runs so far, 0 failures, over 11m50s
421 runs so far, 0 failures, over 11m55s
422 runs so far, 0 failures, over 12m0s
426 runs so far, 0 failures, over 12m5s
430 runs so far, 0 failures, over 12m10s
430 runs so far, 0 failures, over 12m15s
435 runs so far, 0 failures, over 12m20s
436 runs so far, 0 failures, over 12m25s
440 runs so far, 0 failures, over 12m30s
444 runs so far, 0 failures, over 12m35s
444 runs so far, 0 failures, over 12m40s
449 runs so far, 0 failures, over 12m45s
453 runs so far, 0 failures, over 12m50s
458 runs so far, 0 failures, over 12m55s
459 runs so far, 0 failures, over 13m0s
460 runs so far, 0 failures, over 13m5s
464 runs so far, 0 failures, over 13m10s
468 runs so far, 0 failures, over 13m15s
473 runs so far, 0 failures, over 13m20s
473 runs so far, 0 failures, over 13m25s
476 runs so far, 0 failures, over 13m30s
478 runs so far, 0 failures, over 13m35s
481 runs so far, 0 failures, over 13m40s
486 runs so far, 0 failures, over 13m45s
487 runs so far, 0 failures, over 13m50s
490 runs so far, 0 failures, over 13m55s
493 runs so far, 0 failures, over 14m0s
495 runs so far, 0 failures, over 14m5s
499 runs so far, 0 failures, over 14m10s
500 runs so far, 0 failures, over 14m15s
505 runs so far, 0 failures, over 14m20s
507 runs so far, 0 failures, over 14m25s
509 runs so far, 0 failures, over 14m30s
512 runs so far, 0 failures, over 14m35s
514 runs so far, 0 failures, over 14m40s
520 runs so far, 0 failures, over 14m45s
521 runs so far, 0 failures, over 14m50s
524 runs completed, 1 failures, over 14m55s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-05 22:33
Duplicate of #6342

**Closed by bdarnell** 2016-05-05 22:33 UTC
Labels: Robot, test-failure
