### ISSUE TITLE
Panic when PGDUMP import finishes

### ISSUE THREAD

**Issue by victor-oancea-leftclick-io** [cockroachdb/cockroach#68348] opened 2021-08-02 22:12 UTC
build: CCL v21.1.6  (go1.15.11)

When the PGDUMP import finishes, server crashes with a panic:

```
runtime error: invalid memory address or nil pointer dereference
* (1) attached stack trace
*   -- stack trace:
*   | runtime.gopanic
*   | 	/usr/local/go/src/runtime/panic.go:969
*   | runtime.panicmem
*   | 	/usr/local/go/src/runtime/panic.go:212
*   | runtime.sigpanic
*   | 	/usr/local/go/src/runtime/signal_unix.go:742
*   | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).ReadTimestamp
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:297
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getLeasedDescriptorByID
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:322
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByIDMaybeSetTxnDeadline.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1064
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByIDMaybeSetTxnDeadline
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1071
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByID
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:1002
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDatabaseByID
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:931
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableDatabaseByID
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:921
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getUserDefinedSchemaByName.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:723
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getUserDefinedSchemaByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:772
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getSchemaByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:890
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:835
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:514
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getTypeByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:672
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableTypeByName
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/collection.go:656
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors.(*LogicalSchemaAccessor).GetObjectDesc
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/accessors/logical_schema_accessors.go:170
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupObject
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:197
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ResolveExisting
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/name_resolution.go:349
*   | github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:156
*   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).ResolveType
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:323
*   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.ResolveType
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/type_name.go:172
*   | github.com/cockroachdb/cockroach/pkg/sql.NewTableDesc
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/create_table.go:1761
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.MakeSimpleTableDescriptor
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_table_creation.go:163
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.createPostgresTables
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_pgdump.go:353
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.readPostgresCreateTable
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/read_import_pgdump.go:480
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.parseAndCreateBundleTableDescs
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1764
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).parseBundleSchemaIfNeeded
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1811
*   | github.com/cockroachdb/cockroach/pkg/ccl/importccl.(*importResumer).Resume
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/ccl/importccl/import_stmt.go:1877
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1203
*   | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
*   | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1204
```

**Comment by adityamaru** [comment] 2021-08-09 15:29
Hey @victor-oancea-leftclick-io sorry for the delayed response! We have seen some cases of PGDUMP crashing because of the presence of User-Defined Types as columns in the tables being imported. Do you have any `CREATE TYPE` and corresponding usage of those user-defined types in your dump file?

**Comment by adityamaru** [comment] 2021-08-24 15:03
We added some guardrails around unsupported UDTs in IMPORT that should make it into the next 21.1 dot release - https://github.com/cockroachdb/cockroach/pull/69249. Closing this for now, but feel free to reopen if this is not the root cause!

**Closed by adityamaru** 2021-08-24 15:03 UTC
Labels: C-bug, O-community, A-bulkio, X-blathers-triaged, T-bulkio
