### ISSUE TITLE
sql: unexpected "rangefeeds require kv.rangefeed.enabled" on system tables

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#76331] opened 2022-02-09 20:39 UTC
I am running into a problem which seems to be caused by system table rangefeeds in the tenant not working. I distilled the change I was working on to just a delay during tenant initialization.

Apply this diff:
```
diff --git a/pkg/server/node.go b/pkg/server/node.go
index 3ad254081e..4dd5fd236a 100644
--- a/pkg/server/node.go
+++ b/pkg/server/node.go
@@ -1390,6 +1390,7 @@ func (n *Node) TenantSettings(
 ) error {
 	ctx := n.storeCfg.AmbientCtx.AnnotateCtx(stream.Context())
 	ctxDone := ctx.Done()
+	time.Sleep(10 * time.Second)
 
 	// TODO(radu): implement this. For now we just respond with an initial event
 	// so the tenant can initialize.
```

Then run:
```
make test PKG=./pkg/ccl/logictestccl 'TESTS=TestTenantLogic/3node-tenant#01/tenant$$' TESTFLAGS='-v -show-logs' TESTTIMEOUT=30s
```

Sometimes the test passes, but usually it gets stuck and you see this in logs:
```
W220209 20:33:47.697524 5665 kv/kvclient/rangefeed/rangefeed.go:301  [nsql1,rangefeed=sql_instances] 190  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:157: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency
W220209 20:33:47.699613 2113 kv/kvclient/rangefeed/rangefeed.go:301  [nsql1,rangefeed=table-stats-cache] 191  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:157: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latenc> y
W220209 20:33:47.701328 5772 kv/kvclient/rangefeed/rangefeed.go:301  [nsql1,rangefeed=settings-watcher] 192  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:157: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency
W220209 20:33:47.703405 5775 kv/kvclient/rangefeed/rangefeed.go:301  [nsql1,rangefeed=system-config-cache] 193  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:157: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-late> ncy
W220209 20:33:47.712925 6384 kv/kvclient/rangefeed/rangefeed.go:301  [nsql?,rangefeed=table-stats-cache] 194  rangefeed failed 0 times, restarting: kv/kvserver/replica_rangefeed.go:157: rangefeeds require the kv.rangefeed.enabled setting. See https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latenc> y
```

This is on 4df7f50b9bd54fe943f048eb762f8e602ae8bf34.

@ajwerner suspects #74555.

**Comment by RaduBerinde** [comment] 2022-02-11 03:51
@yuzefovich ran into this as well (he hit `ERROR: setting updated but timed out waiting to read new value` when setting a cluster setting). I reproduced with his data directory and saw the same logs as above.

**Comment by ajwerner** [comment] 2022-02-11 04:43
https://github.com/cockroachdb/cockroach/pull/76420 is something and attacks the heart of the problem. There's still some rough edges to iron out here.

**Comment by onlysavior** [comment] 2022-02-11 04:44
您好，来信已收到，回尽快给您回复，祝身体健康

**Comment by RaduBerinde** [comment] 2022-02-11 04:54
> @yuzefovich ran into this as well (he hit `ERROR: setting updated but timed out waiting to read new value` when setting a cluster setting). I reproduced with his data directory and saw the same logs as above.

Some more info here - Yahor ran into a problem and he gave me the cockroach-data dir. I started a regular node with that dir and saw these messages:
```
W220211 03:49:13.566659 530 kv/kvclient/rangefeed/rangefeed.go:301 ⋮ [n1,rangefeed=‹sql_instances›] 205  rangefeed failed 9 times, restarting: ‹kv/kvserver/replica_rangefeed.go›:157: rangefeeds require the kv.rangefeed.enabled setting. See ‹https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency›
W220211 03:49:13.635930 891 kv/kvclient/rangefeed/rangefeed.go:301 ⋮ [n1,rangefeed=‹settings-watcher›] 206  rangefeed failed 9 times, restarting: ‹kv/kvserver/replica_rangefeed.go›:157: rangefeeds require the kv.rangefeed.enabled setting. See ‹https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency›
I220211 03:49:13.715993 497 sql/sqlstats/persistedsqlstats/flush.go:32 ⋮ [n1] 207  flushing 2 stmt/txn fingerprints (10240 bytes) after 1.0089529s
W220211 03:49:13.861032 177 kv/kvclient/rangefeed/rangefeed.go:301 ⋮ [n1,rangefeed=‹table-stats-cache›] 208  rangefeed failed 10 times, restarting: ‹kv/kvserver/replica_rangefeed.go›:157: rangefeeds require the kv.rangefeed.enabled setting. See ‹https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency›
W220211 03:49:14.084262 299 kv/kvclient/rangefeed/rangefeed.go:301 ⋮ [n1,rangefeed=‹system-config-cache›] 209  rangefeed failed 9 times, restarting: ‹kv/kvserver/replica_rangefeed.go›:157: rangefeeds require the kv.rangefeed.enabled setting. See ‹https://www.cockroachlabs.com/docs/v22.1/change-data-capture.html#enable-rangefeeds-to-reduce-latency›
```

And I was able to reproduce `ERROR: setting updated but timed out waiting to read new value` when changing a cluster setting.

**Comment by ajwerner** [comment] 2022-02-11 04:57
> @yuzefovich ran into this as well (he hit `ERROR: setting updated but timed out waiting to read new value` when setting a cluster setting). I reproduced with his data directory and saw the same logs as above.

Any chance I can get this data directory? On some level it's going to have to do with the span configs being incorrect. A scan of `SELECT crdb_internal.pretty_key(start_key, 0), crdb_internal.pretty_key(end_key, 0), crdb_internal.pb_to_json('cockroach.roachpb.SpanConfig', config) from system.span_configurations` will hold good clues.

**Comment by yuzefovich** [comment] 2022-02-11 04:59
Sent you a link on slack (out of paranoia of that directory containing some confidential information).

**Comment by ajwerner** [comment] 2022-02-11 05:19
Classic lack of version upgrade testing ☹️. There's a funny problem here. We watch for changes in span configs using a rangefeed. We used to decide if rangefeeds were enabled by looking at the keys of the replica but we stripped that in https://github.com/cockroachdb/cockroach/pull/74555/files#diff-b080aecf7d979c0b5a4c43973db709d0d866f137cb4e961ebfc0d979ad22c003. The problem is, in the mixed version state, we won't support the rangefeeds we need. That's bad and means we need to put the old logic back. The good news about the old logic is it's all still valid. 

I'm not getting some ambient feels of concern about upgrade considerations for the tenants themselves, but I think if we just wholesale put the old logic back, we'll be fine.

**Comment by ajwerner** [comment] 2022-02-11 05:20
I *think* @RaduBerinde you'll be fine with https://github.com/cockroachdb/cockroach/pull/76420 for new tenants in new cluster and that new clusters bootstrapped off of master will be fine. We'll definitely need to do some mixed version testing. Sort of appalling that there's no mixed version test which sets a cluster setting.

**Comment by arulajmani** [comment] 2022-02-11 17:43
Maybe I'm missing something, but I'm not entirely sure how we end up in this mixed version case. Looking here: 

https://github.com/cockroachdb/cockroach/blob/4b8258c4b4a8f89fe8a4ea87fc8ee7cd5c916b6d/pkg/config/system.go#L311-L319

Doesn't this mean we should be supporting the rangefeeds we need? It also looks like we have [this logic](https://github.com/cockroachdb/cockroach/blob/d35cf750ba6e11176a14cfb32e78049b77e84209/pkg/kv/kvserver/replica.go#L1013) to support rangefeeds if a config is not explicitly set on a replica. 

----

After typing all of that, I came across this logic where we seem to be swallowing an error and applying the default span config on the replica -- maybe this is what's causing the issue?
https://github.com/cockroachdb/cockroach/blob/14001c526d2f8f9eefb242aab06323566776b0c2/pkg/kv/kvserver/store.go#L2316-L2328

If we don't want to bring back the old key stripping logic, maybe we can set `RangefeedEnabled` to be true on the `DefaultSpanConfig` that we have on the `kvserver.StoreConfig`? Essentially, moving this logic a layer above: https://github.com/cockroachdb/cockroach/blob/6e1cbfe18bbadea1903a809eb5aafd4da7410f43/pkg/server/server.go#L540-L559

**Closed** 2022-02-12 01:49 UTC
Labels: C-bug, branch-master, release-blocker

**Comment by yuzefovich** [comment] 2022-02-12 01:53
@ajwerner should this issue be closed by #76420?

**Comment by irfansharif** [comment] 2022-02-12 02:07
Yes, I think so. There's a migration bug theorized above, but I don't think it holds -- sending a PR with a test to prove it. As for how https://github.com/cockroachdb/cockroach/pull/74555 could affect the non-system tenant, I'm not sure yet. Do you have a repro I could use to see what you were seeing?

**Comment by irfansharif** [comment] 2022-02-13 00:30
I took a look at the zipped store being referenced above, confirming that I saw the same as described -- rangefeeds were wedged on server startup. I also noticed that if the server process was _restarted_, things worked just fine. Eventually I just disabled the reconciliation job and poked at the store's contents of `system.span_configurations`, and noticed that even for system tables, it didn't have `config.RangefeedEnabled` set. I'm guessing that the store was created off of a binary that did not have https://github.com/cockroachdb/cockroach/pull/74555. Because the span config proto did not know about this field, on KV store start up when scanning from that table, we applied `config.RangefeedEnabled == false` for system database ranges, blocking all rangefeeds. The reason restarting the server seemed to resolve the problem is because the first time the server range, the reconciliation job will have successfully run, overwriting `system.span_configuration` protos with the right field set. The reason it was not picked up by process the first time time is because the per-store component that listens in on updates to the table also made use of rangefeeds, so was similarly wedged. This was not a problem post-restart.

Anyway, I don't think there's anything to do here, not a bug AFAICT. #76466 confirms that mixed-version state with rangefeeds work just fine; ee were careful about embedding the right defaults in #74555.
