### ISSUE TITLE
sqlbase: TableDescriptor.Validate is incomplete

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50854] opened 2020-07-01 01:22 UTC
The new test in #50853 turned up several descriptor fields that should be validated in `TableDescriptor.Validate`. This issue tracks adding validation checks for them.

## TableDescriptor
- [ ] `UnexposedParentSchemaID`: @rohany  
- [ ] `NextMutationID`: @lucy-zhang 
- [x] `Checks`: @solongordon 
- [ ] `ViewQuery`: @solongordon 
- [ ] `DependsOn`: @solongordon 
- [ ] `DependedOnBy`: @solongordon 
- [ ] `SequenceOpts`: @arulajmani 
- [ ] `GCMutations`: @pbardea 
- [ ] `ReplacementOf`: @dt 

## IndexDescriptor
- [ ] `StoreColumnNames`: @solongordon   
- [ ] `ExtraColumnIDs`: @solongordon 
- [ ] `StoreColumnIDs`: @solongordon 
- [ ] `CompositeColumnIds`: @solongordon 
- [x] `Predicate`: @mgartner 

## ColumnDescriptor
- [ ] `Type`: @rohany 
- [ ] `DefaultExpr`: @solongordon 
- [ ] `UsesSequenceIDs`: @arulajmani 
- [ ] `OwnsSequenceIds`: @arulajmani  
- [x] `ComputeExpr`: @solongordon 
- [ ] `LogicalColumnID`: @RichardJCai

## FKConstraint
- [ ] `OriginColumnIDs`: @lucy-zhang 
- [ ] `ReferencedColumnIDs`: @lucy-zhang 

## Meta
- [x] The validate function should take in an interface that can cache descriptor lookups, rather than a raw `*kv.Txn`.

Jira issue: CRDB-4081

**Comment by jordanlewis** [comment] 2020-07-06 15:54
Added 2 missing cases: checks for `OriginColumnIDs` and `ReferencedColumnIDs` in `ForeignKeyConstraint`.

**Comment by jordanlewis** [comment] 2020-07-06 15:55
Also cases for the fields in `ColumnDescriptor`. cc @rohany, @RichardJCai , @solongordon.

**Comment by solongordon** [comment] 2020-07-20 15:19
I've mentioned this to a few people but don't feel like I have a satisfying answer: what do we do about the fact that there are almost certainly descriptors in the wild which will fail these new validations after the cluster is upgraded (for example, due to the recent sequence ownership bugs)? A user might upgrade and then find that they can no longer alter one of their tables. Even worse, they might be unable to restore from backup, since `Validate` is run on each table after restoring.

Couple ideas:
- We could try to add logic to repair broken descriptors, but this seems hard or impossible to do in the general case, and it will only cover issues we already know about.
- We could add "soft" validations which would error out during tests but not in production. Maybe they could even error out for certain operations like CREATE TABLE but not for ALTERs?

Interested to hear more thoughts on this.

**Comment by jordanlewis** [comment] 2020-07-20 17:36
This is definitely troublesome.

Here's an idea from brainstorming with @lucy-zhang. We change all `ALTER` commands that edit table descriptors to:

1. Run `Validate` on the descriptors that are about to be changed, and note down the result. If the result is a fail, use `ReportOrPanic` to panic in tests and report to sentry in production. Also log.
2. Perform the descriptor changes.
3. Run `Validate` again. If it fails:
    - If `Validate` passed before, prevent the change from going through and return an error to the user, prompting them to contact us.
    - If `Validate` failed before, return no error to the user, but log and report again.

This sequence should guard us against old, busted descriptors, even as our `Validate` method becomes more stringent.

**Comment by solongordon** [comment] 2020-07-20 19:25
Nice, that sounds promising. I suppose for usages which aren't changing the descriptor like RESTORE and `catalogkv.unwrapDescriptor` we would just do step 1 (`Validate` and then `ReportOrPanic` and log)? A little troubling that we would be reducing the level of protection we already have there, but maybe there isn't a good way around that.

**Comment by pbardea** [comment] 2020-07-20 23:01
Some thoughts with respect to the backup/restore use case. One thing I wanted to note is that `RESTORE` does sometimes change the table descriptor (some flavors of restore more than others). Consider the case where we restore a table without one of its dependencies (which is possible with a flag), we will remove some dependencies in the table descriptor (e.g. a FK dependency). This is a bit tricky since `Validation` would fail, since the table is missing its dependencies, until restore updates the table descriptor. Then a validation violation at this point could be caused by the original table descriptor being malformed, or a bug in `RESTORE`. It's unfortunate that we won't be able to tell the difference.

However, for some restores (e.g. cluster restores), I think it should be feasible to follow the approach listed above (`Validate` before restoring, and if it was successful assert `Validate` after changing the descriptor).

I also considered a scheme where we validate during `BACKUP` where we have access to all dependent tables and save that result in the backup file. Then, during `RESTORE` we could only `Validate` the descriptor if it was valid at the time of backup. The problem with this approach is that it doesn't handle what happens when we make `Validate` more restrictive.

As a side-note, it would be nice if we could only `BACKUP` tables that were in a valid state to avoid any surprises during `RESTORE`. But it doesn't look like we can get to a world where we can assume that all descriptors can be `Validate`d or automatically fixed anytime soon.

**Comment by arulajmani** [comment] 2020-07-21 14:41
@pbardea doesn't it make sense to validate after the table descriptor has been updated by `RESTORE`? I agree that if validation fails it could be because the original table descriptor was malformed or there was a bug in `RESTORE`, but regardless we should fail because restoring a malformed table descriptor will have consequences downstream?

**Comment by postamar** [comment] 2022-03-08 22:23
I think we can close this, we're pretty thorough these days, enough so that it's easier to have issues which track what's _not_ being validated and really should be.

**Closed by postamar** 2022-03-08 22:23 UTC
Labels: C-cleanup, T-sql-experience, T-bulkio, T-sql-schema, T-sql-queries
