### ISSUE TITLE
kvserver: flake in TestPromoteNonVoterInAddVoter

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#100880] opened 2023-04-06 21:58 UTC
Found here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9479503?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestPromoteNonVoterInAddVoter
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/d486233d291fa43f53db749aea077e75/logTestPromoteNonVoterInAddVoter3114583795
    test_log_scope.go:79: use -show-logs to present logs inline
    replicate_queue_test.go:2349:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/kv/kvserver_test/pkg/kv/kvserver/replicate_queue_test.go:2349
          Error:        Expected to promote non-voter, instead added voter
          Test:         TestPromoteNonVoterInAddVoter
          Messages:     Added voter store ID: 6
                        Add voter events: [{r63:/{Table/104-Max} [(n1,s1):1, (n2,s2):7, (n3,s3):4, (n4,s4):8NON_VOTER, (n6,s6):9, next=10, gen=28] <nil> <nil> (n6,s6):9 <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:62"}} {r63:/{Table/104-Max} [(n1,s1):1, (n2,s2):7, (n3,s3):4, (n4,s4):8, (n6,s6):9, next=10, gen=29] <nil> <nil> (n4,s4):8 <nil> range under-replicated {"Target":"s4, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:62"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):7, (n3,s3):4, (n6,s6):11LEARNER, next=12, gen=40] <nil> <nil> (n6,s6):11LEARNER <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):7, (n3,s3):4, (n6,s6):11, next=12, gen=41] <nil> <nil> (n6,s6):11 <nil> range under-replicated {"Target":"s6, necessary:true, diversity:1.00, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):7, (n3,s3):4, (n6,s6):11, (n4,s4):12LEARNER, next=13, gen=42] <nil> <nil> (n4,s4):12LEARNER <nil> range under-replicated {"Target":"s4, necessary:true, diversity:0.88, converges:0, balance:0, rangeCount:61"}} {r63:/{Table/104-Max} [(n5,s5):10, (n2,s2):7, (n3,s3):4, (n6,s6):11, (n4,s4):12, next=13, gen=43] <nil> <nil> (n4,s4):12 <nil> range under-replicated {"Target":"s4, necessary:true, diversity:0.88, converges:0, balance:0, rangeCount:61"}}]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/d486233d291fa43f53db749aea077e75/logTestPromoteNonVoterInAddVoter3114583795
--- FAIL: TestPromoteNonVoterInAddVoter (30.78s)
```

cc @erikgrinaker for triage

Jira issue: CRDB-26666

**Comment by erikgrinaker** [comment] 2023-04-14 12:18
This seems like an allocator issue, reassigning to KV distribution. Same with #101519 on `master`.

CC @cockroachdb/kv-distribution

**Comment by kvoli** [comment] 2023-05-10 13:49
Dupe of #100880 - closing to focus discussion there.

**Closed by kvoli** 2023-05-10 13:49 UTC
Labels: C-bug, C-test-failure, A-kv-distribution, T-kv
