### ISSUE TITLE
tsdump: failed with empty key span on  time-restricted invocation

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#81085] opened 2022-05-06 06:58 UTC
**Describe the problem**

```
$ roachprod ssh tobias-lsm:1 -- ./cockroach debug tsdump --insecure --format=raw --from '2022-05-05 12:00:00' --to '2022-05-05 18:00:00' > tsdump.gob.yaml
ERROR: rpc error: code = Unknown desc = end key /System/tsd/cr.node.abortspanbytes//10s/2022-05-05T00:00:00Z must be greater than start /System/tsd/cr.node.abortspanbytes//10s/2022-05-05T00:00:00Z
Failed running "debug tsdump"
Error: COMMAND_PROBLEM: exit status 1
(1) COMMAND_PROBLEM
Wraps: (2) Node 1. Command with error:
  | ```
  | ./cockroach debug tsdump --insecure --format=raw --from 2022-05-05 12:00:00 --to 2022-05-05 18:00:00
  | ```
Wraps: (3) exit status 1
Error types: (1) errors.Cmd (2) *hintdetail.withDetail (3) *exec.ExitError
```

`from` < `to`, so this ought to work.

`--from '2022-05-05 12:00:00' --to '2022-05-05 23:59:59'` fails in the same way.

`--from '2022-05-05 12:00:00' --to '2022-05-06 00:00:00'` works.

This has to have to do with some truncation of date boundaries in the server-side `tsdump` implementation. We are somehow ending up with an empty span; maybe the date range at this point has been rolled up into 24h slots and so selecting an interval that doesn't cross a midnight will fail. We should make sure to "round away" from the endpoints to avoid this issue.

**To Reproduce**

**Expected behavior**

I would expect to see a successful tsdump that includes (but may exceed) the time bounds provided.

**Additional data / screenshots**

Right now it's 2022-05-06 8am UTC, in case that's relevant to determine if the timeseries in question has already been rolled up. (I would be mildly surprised by this as it seems fairly aggressive).

Jira issue: CRDB-15361

**Comment by aadityasondhi** [comment] 2022-07-22 19:05
I am inclined to close this issue after attempts at reproducing this error have failed and investigating the code suggests that we do “round away” for both our start and end keys to avoid an error like this from occurring. Please take a look at my reasoning below and let me know if I have missed something.

Code that does the rounding away:

We add a `delta` to the end key equivalent to the `SlabDuration` which is defined in a map based on resolution in `slabDurationByResolution`. For the default 10s resolution this equates to 1h, and for the rolled up 30m resolution, it is 24h. Reference: https://github.com/cockroachdb/cockroach/blob/master/pkg/ts/server.go#L419

Next when creating the db keys, we truncate these values to the nearest slab duration boundary. By design, this results in the start key getting rounded down and the end key rounded up (due to the delta added earlier). Reference: https://github.com/cockroachdb/cockroach/blob/master/pkg/ts/keys.go#L64

Additionally, I used a `roachprod` cluster to try and reproduce this on a cluster with CRDB `v22.1.3` and that investigation suggests the same behavior as described above. Reference notes: https://docs.google.com/document/d/12Bn7F2M33qjaq_J_mOdyE73CEC-Wi-Q4y7LEHRZz4-M/

**Comment by aadityasondhi** [comment] 2022-07-27 14:41
Closing this issue based on above. Feel free to reopen if there is a reoccurrence.

**Closed by aadityasondhi** 2022-07-27 14:41 UTC
Labels: C-bug, T-observability-inf
