### ISSUE TITLE
circleci: failed tests (14450): TestStoreMetrics 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5215] opened 2016-03-13 23:02 UTC
The following test appears to have failed:

[#14450](https://circleci.com/gh/cockroachdb/cockroach/14450):

```
I160313 23:01:30.387991 storage/raft_transport.go:221  remote node 2 at 127.0.0.1:58197 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160313 23:01:30.388144 storage/raft_transport.go:221  remote node 1 at 127.0.0.1:48491 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160313 23:01:30.388235 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160313 23:01:30.388400 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160313 23:01:30.388503 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestStoreMetrics (0.32s)
	client_metrics_test.go:47: storage/client_metrics_test.go:84: sysbytes for store: actual 434 != expected 360
	client_metrics_test.go:47: storage/client_metrics_test.go:85: syscount for store: actual 6 != expected 5
	client_metrics_test.go:91: storage/client_metrics_test.go:159: verifyStats failed, aborting test.
=== RUN   TestRaftLogQueue
W160313 23:01:30.389755 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160313 23:01:30.394157 raft/raft.go:459  [group 1] 1 became follower at term 5
W160313 23:01:30.394205 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160313 23:01:30.394235 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160313 23:01:30.394265 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160313 23:01:30.394310 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160313 23:01:54.528212 storage/raft_transport.go:186  establishing Raft transport stream to node 2 at 127.0.0.1:58302
--- PASS: TestInOrderDelivery (0.58s)
=== RUN   Example_rebalancing
W160313 23:01:55.107598 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
--- PASS: Example_rebalancing (0.13s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	28.465s
=== RUN   TestBatchBasics
I160313 23:01:45.645756 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I160313 23:01:45.649841 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I160313 23:01:45.652259 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 18:06
Duplicate of #5208.

**Closed by petermattis** 2016-03-14 18:06 UTC
Labels: test-failure
