### ISSUE TITLE
Test failure in CI build 1236

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#598] opened 2015-04-08 19:57 UTC
The following test appears to have failed:

[#1236](https://circleci.com/gh/cockroachdb/cockroach/1236):

```
I0408 19:55:25.529591     269 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0408 19:55:25.530690     269 multiraft.go:641] New Entry[0]: 6/35 EntryNormal 13d3220838b6777f65157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428522925513144191 random:7283855682742174347 > key:"b
I0408 19:55:25.531786     269 multiraft.go:644] Committed Entry[0]: 6/35 EntryNormal 13d3220838b6777f65157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428522925513144191 random:7283855682742174347 > key:"b
I0408 19:55:25.538615     269 raft.go:390] raft: 101 became follower at term 5
I0408 19:55:25.538902     269 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb00a76]

goroutine 1674 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2084e4ab0, 0xc2086569f0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:625 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2084e4ab0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:477 +0x1ad7
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:149 +0x60

--
goroutine 1675 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc208396160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1121 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:477 +0xc07
FAIL	github.com/cockroachdb/cockroach/storage	3.357s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)
I0408 19:55:25.529591     269 multiraft.go:638] HardState updated: {Term:6 Vote:257 Commit:35 XXX_unrecognized:[]}
I0408 19:55:25.530690     269 multiraft.go:641] New Entry[0]: 6/35 EntryNormal 13d3220838b6777f65157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428522925513144191 random:7283855682742174347 > key:"b
I0408 19:55:25.531786     269 multiraft.go:644] Committed Entry[0]: 6/35 EntryNormal 13d3220838b6777f65157426e50ec28b: raft_id:1 cmd:<end_transaction:<header:<timestamp:<wall_time:0 logical:31 > cmd_id:<wall_time:1428522925513144191 random:7283855682742174347 > key:"b
I0408 19:55:25.538615     269 raft.go:390] raft: 101 became follower at term 5
I0408 19:55:25.538902     269 raft.go:207] raft: newRaft 101 [peers: [101], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x10 pc=0xb00a76]

goroutine 1674 [running]:
github.com/cockroachdb/cockroach/multiraft.(*state).propose(0xc2084e4ab0, 0xc2086569f0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:625 +0xc6
github.com/cockroachdb/cockroach/multiraft.(*state).start(0xc2084e4ab0)
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:477 +0x1ad7
created by github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).Start
	/go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:149 +0x60

--
goroutine 1675 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft(0xc208396160)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1121 +0xee6
created by github.com/cockroachdb/cockroach/storage.(*Store).Start
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:477 +0xc07
FAIL	github.com/cockroachdb/cockroach/storage	3.357s
=== RUN TestBatchBasics
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
--- PASS: TestBatchMerge (0.00s)
=== RUN TestBatchProto
--- PASS: TestBatchProto (0.00s)
=== RUN TestBatchScan
--- PASS: TestBatchScan (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-04-08 19:59
Duplicate of #597

**Closed by bdarnell** 2015-04-08 19:59 UTC
Labels: test-failure
