### ISSUE TITLE
Failed tests (12525): TestNodeStatus 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4247] opened 2016-02-09 03:37 UTC
The following test appears to have failed:

[#12525](https://circleci.com/gh/cockroachdb/cockroach/12525):

```
I0209 03:34:37.437726 119 util/tracing/tracer.go:40  [Trace sending batch]
 * 03:34:37.437294meta descriptor lookup
 * 03:34:37.437303sending RPC
 * 03:34:37.437323sending to 127.0.0.1:50567
I0209 03:34:37.439843 119 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestNodeStatus (0.20s)
	cli_test.go:822: value for live_bytes (10373) greater than max (10000)
	cli_test.go:822: value for live_bytes (10373) greater than max (10000)
=== RUN   TestGenMan
Generated CockroachDB man pages in /tmp/TestGenMan093911139/
--- PASS: TestGenMan (0.04s)
	leaktest.go:110: prior leak detected, leaktest disabled
=== RUN   TestGenAutocomplete
Generated bash completion file /tmp/TestGenAutoComplete657343590/cockroach.bash
--- PASS: TestGenAutocomplete (0.03s)
	leaktest.go:110: prior leak detected, leaktest disabled
--
W0209 03:34:40.643533 119 storage/replica.go:1707  failed to push during intent resolution: conflicting intents on [/Meta2/Table/13 /Meta2/Max]: resolved? false
[node --host=127.0.0.1 --port=55292 --certs=/tmp/cli-test455791920 ls]
[node --host=127.0.0.1 --port=55292 --certs=/tmp/cli-test455791920 status 10000]
Error: Error: node 10000 doesn't exist
--- PASS: Example_node (0.15s)
FAIL
FAIL	github.com/cockroachdb/cockroach/cli	3.732s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.00s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.00s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.00s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-09 03:46
Dupe of #4239

**Closed by bdarnell** 2016-02-09 03:46 UTC
Labels: test-failure, TestNodeStatus
