### ISSUE TITLE
Revert failure due to "command is too large"

### ISSUE THREAD

**Issue by dankinder** [cockroachdb/cockroach#59662] opened 2021-02-01 19:05 UTC
**Describe the problem**

I am running a series of IMPORT INTO commands in sequence, each importing 80 data files at a time from S3.

After the cluster reached about 450GB of data, an import failed with this error: "job 629451099347484673: cannot be reverted, manual cleanup may be required: rolling back partially completed IMPORT: command is too large: 67607882 bytes (max: 67108864)"

Now the table is completely offline and I'm not finding any documentation about how to manually clean it up.

Luckily this is an offline cluster we're migrating too so we aren't in dire straits. But it's unusable right now.

**To Reproduce**

This is tricky because I've run thousands of these imports so far and never seen this error. The error message indicates it has to do with a command going over-size, so I'm guessing the specs of my cluster don't really matter, but I could provide them if needed.

I don't want to post the specific import sql here but can say that the full import statements are roughly 24kb each including all 80 files being imported as S3 paths with credentials.

I can send logs privately if you want those.

**Expected behavior**
Not a failure, or a table that's not offline, or a reference to documentation about how to clean up

**Environment:**
 - CockroachDB version 20.2.3
 - Server OS: Centos 6
 - Client app: Go (pgx)

**Comment by adityamaru** [comment] 2021-02-01 19:52
Hi @dankinder, thanks for reaching out!
 
First for some context (some of which you might already know):

IMPORT INTO takes the target table offline before ingesting data and only marks it as public once the import job has successfully completed. If the import job fails for any reason, we need to rollback the ingested data to the timestamp at which the import job was started. This allows us to get back to the consistent state we were in at the beginning of the import.

The error message mentioned above indicates that the job failed to revert on import failure because it hit an internal limit we have on the size of a command that can be written to the raft log (64 MiB). At this point, we do not bring the table online as it might be in an inconsistent state with data prior to the import, as well as some data ingested during the import.

The first priority will be to fix the offline table state, and then we can investigate why the IMPORT failed in the first place.
It would be helpful if you could upload a debug zip (https://www.cockroachlabs.com/docs/v20.2/cockroach-debug-zip.html). This would allow us to get information about the schema of the table being imported into, and potentially the cause of the failed import. The easiest way to upload this securely would be to create a ticket at https://support.cockroachlabs.com/hc/en-us, and upload the debug zip via SendSafely.

Let me know if this works for you 🙂

**Comment by adityamaru** [comment] 2021-02-01 19:55
As a follow-up question, you indicated that this was an offline cluster. Was the table being imported into, empty at the time the import was run? Unfortunately, we might have to do some descriptor surgery to get out of this state, and this is a lot easier if the table was empty or you are comfortable dropping the data prior to the IMPORT.

If not, we will come up with alternative next steps.

**Comment by dankinder** [comment] 2021-02-01 22:05
I'm okay blowing the table away and restarting from empty, if you can give me instructions on how to do that.

The debug zip is 3GB so will take a bit to submit to a ticket. Will have that done soon.

**Comment by adityamaru** [comment] 2021-02-01 23:24
That's good to know, let me have a look at the debug zip and recommend some next steps.

**Comment by lucy-zhang** [comment] 2021-02-02 15:16
I'm removing this from our board but let us know if you need anything.

**Comment by dankinder** [comment] 2021-02-02 15:36
Actually it occurred to me that this is the first table in the DB that I'm populating, so I could just drop the whole DB. Will a DROP DATABASE command successfully drop a locked table and all its data?

**Comment by dankinder** [comment] 2021-02-02 15:59
Turns out it stops me from doing that: `ERROR: cannot drop a database with OFFLINE tables, ensure <my table> is dropped or made public before dropping database <db>` But I don't see any mechanism for forcing it to drop the offline table.

**Comment by tim-o** [comment] 2021-02-02 17:06
Attachments available here: https://cockroachdb.zendesk.com/agent/tickets/7471

**Comment by adityamaru** [comment] 2021-02-02 17:27
I'm crafting a query to get the descriptor to a public state, so that we can drop it. I'll update this issue shortly!

**Comment by adityamaru** [comment] 2021-02-02 18:26
@dankinder first addressing the immediate problem of the offline table:

Can you run the following query, to flip the table state from `OFFLINE` to `PUBLIC`, and then `DROP` the table.

```
SELECT
	crdb_internal.unsafe_upsert_descriptor(
		53,
		crdb_internal.json_to_pb(
			'cockroach.sql.sqlbase.Descriptor',
			json_set(
				crdb_internal.pb_to_json(
					'cockroach.sql.sqlbase.Descriptor',
					descriptor,
				),
				ARRAY['table', 'state'],
				'"PUBLIC"'::JSONB
			)
		)
	)
FROM
	system.descriptor
WHERE
	id = 53;
```

Now addressing the failed import:

From the debug.zip I am seeing multiple IMPORT jobs on the above table, that failed with `checking for key collisions: ingested key collides with an existing one:`. This occurs when the IMPORT INTO CSV files have rows that will "shadow" already existing rows in the table being imported into. From the "Known Limitations" section of our docs for IMPORT INTO:
`Imported rows must not conflict with existing rows in the table or any unique secondary indexes.`egs: if the primary key of a row in the target table collides with the primary key of a row being imported, then we will fail the import into.

Think of IMPORT as adding rows, and not updating existing rows. So I just wanted to check if this explains the import failures?

Lastly, addressing the failed import revert due to command size:

I forgot that the debug.zip does not include the schema of the table. If you could attach the schema of the above table (you could redact the colNames, I'm more interested in the types and constraints) to see if a single key can get very large. I suspect I know the reason for this revert to fail, but want to double-check.

**Comment by dankinder** [comment] 2021-02-03 03:27
Hi @adityamaru, thanks for your help, the query worked! (Though, you've got an extra comma after "descriptor"... if only it were Go right?)

I'm aware of the key collision failures and actually filed an issue last year about that: https://github.com/cockroachdb/cockroach/issues/53363 -- with the data source I'm getting everything from I simply can't prevent a small proportion of duplicates without going through a whole separate massive sort | uniq process . It's few enough duplicates that I have a tool now that will stream that data into S3 files, run the import in batches, and then if the import fails, insert it all via direct SQL. It's a little sad to have to write but it works.

Here's the table I'm inserting into, no non-primary indexes. Some of the string fields can have up to a few kb of data but shouldn't get larger than that.
```
CREATE TABLE mytable (                                                                                                   
    a STRING,                                                                                                            
    b STRING,                                                                                                            
    c STRING,                                                                                                            
    d STRING,                                                                                                            
    e STRING,                                                                                                            
    f TIMESTAMP WITH TIME ZONE,                                                                                          
    g INT,                                                                                                               
    h STRING,                                                                                                            
    i BOOL,                                                                                                              
    j STRING,                                                                                                            
    k BOOL,                                                                                                              
    l STRING,                                                                                                            
    m INT,                                                                                                               
    n INT,                                                                                                               
    o INT,                                                                                                               
    p STRING,                                                                                                            
    q BOOL,                                                                                                              
    r STRING,                                                                                                            
    s BOOL,                                                                                                              
    t STRING,                                                                                                            
    u BOOL,                                                                                                              
    v INT,                                                                                                               
    PRIMARY KEY (a, b, c, d, e, f)                                                                                       
);                                      
```

For now I'm rerunning with fewer files per import command in hopes that that helps.

**Comment by adityamaru** [comment] 2021-02-04 14:17
The `command is too large` error is occurring because the keys being reverted in a single batch end up being larger than the internal raft log command size. We are discussing a possible improvement that can paginate these reverts and thereby not hit this command size when rolling back an import. I'll update this ticket with the PR if and when it is merged, but rerunning with fewer (or split up) files should allow you to get past this for the time being. 

I'm closing the issue but feel free to reopen it if anything comes up!

**Closed by adityamaru** 2021-02-04 14:17 UTC
Labels: C-bug, O-community, X-blathers-triaged
