### ISSUE TITLE
sentry: conn_executor.go:639: panic while executing 1 statements: UPDATE _ SET _ = $1 WHERE _ = $2: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32974] opened 2018-12-10 14:07 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/801785260/?referrer=webhooks_plugin

conn_executor.go:639: panic while executing 1 statements: UPDATE _ SET _ = $1 WHERE _ = $2: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go in func1 at line 40
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go in Format at line 721
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go in formatNodeOrHideConstants at line 47
github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go in FormatNode at line 276
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go in MakeExpression at line 84
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go in AddRendering at line 484
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in selectRenders at line 1160
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2283
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in func1 at line 2437
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visitInternal at line 124
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visit at line 101
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visitInternal at line 455
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visitConcrete at line 114
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visitInternal at line 468
github.com/cockroachdb/cockroach/pkg/sql/walk.go in visit at line 101
github.com/cockroachdb/cockroach/pkg/sql/walk.go in walkPlan at line 65
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in wrapPlan at line 2412
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2366
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 740
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1169
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 309
```

**Comment by jordanlewis** [comment] 2018-12-13 16:50
This is the explicit panic here:

```
                        d, err := p.Eval(evalCtx)
                        if err != nil {
                                panic(fmt.Sprintf("failed to serialize placeholder: %s", err))
                        }
```

Unfortunately, we have no clue what the error is. Argh.

**Comment by jordanlewis** [comment] 2019-02-07 16:48
Duplicate of #34349.

**Closed by jordanlewis** 2019-02-07 16:48 UTC
Labels: C-bug, O-sentry, V-2.1.1
