### ISSUE TITLE
latency cliff in `BenchmarkSQL/TenantCockroach` when stressed over a few minutes

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#93560] opened 2022-12-14 00:09 UTC
Something is very off when running `BenchmarkSQL/TenantCockroach` for a few minutes. This runs queries against a shared-process tenant on a single-node cluster. The same thing does not seem to happen when testing directly against the cluster.

```
dev bench pkg/bench -f 'SQL/TenantCockroach$/InsertDistinct/count=1000' --count=1000000 -v --stream-output --ignore-cache --timeout=100h
```

After ~12min, the latency becomes *100x* worse.

```
BenchmarkSQL/TenantCockroach/InsertDistinct/count=1000-24                    279           6198306 ns/op
[35 / 36] Testing //pkg/bench:bench_test; 660s linux-sandbox
BenchmarkSQL/TenantCockroach/InsertDistinct/count=1000-24                    289         372467526 ns/op
[35 / 36] Testing //pkg/bench:bench_test; 861s linux-sandbox
BenchmarkSQL/TenantCockroach/InsertDistinct/count=1000-24                    100         732684018 ns/op
```

One suspicion was about the tenant rate limiter: `kv.tenant_rate_limiter.burst_limit_seconds` and `kv.tenant_rate_limiter.rate_limit`. However, this doesn't seem to be it. Increasing `kv.tenant_rate_limiter.burst_limit_seconds` does eliminate a latency increase that comes a few seconds into the benchmark, but not this huge cliff at the 12min mark.

Jira issue: CRDB-22401

Epic CRDB-23559

**Comment by ecwall** [comment] 2023-03-29 18:08
`count=1000` was causing errors on my MacBook
```
bench_test.go:1013: read tcp 127.0.0.1:57656->127.0.0.1:56392: read: connection reset by peer
```

I am running this in gce to try to reproduce:
```
roachprod create $CLUSTER -n 1 --os-volume-size 100 --gce-machine-type n1-highcpu-16
roachprod setup-ssh $CLUSTER
roachprod ssh $CLUSTER:1

curl -O -L https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64
sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
chmod a+x /usr/local/bin/bazel
sudo apt-get install g++ unzip zip libncurses5-dev libresolv-wrapper --assume-yes
git clone https://github.com/cockroachdb/cockroach.git crdb_source
cd crdb_source
./dev doctor
bazel clean --expunge
./dev bench pkg/bench -f 'SQL/TenantCockroach$/InsertDistinct/count=1000' --count=1000000 -v --stream-output --ignore-cache --timeout=100h
```

**Comment by ecwall** [comment] 2023-03-29 18:17
@knz I am not sure that this patch is needed to resolve this because I am not seeing a performance decrease after ~12min.

I've been running for around 15min and almost every run is ~1,000,000 ns/op with the exception of 2 runs that were ~25,000,000 ns/op like this:
```
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16         	    1035	   1186358 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16         	     100	  25738691 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16         	    1071	   1059878 ns/op
```

**Comment by knz** [comment] 2023-03-29 18:18
great! This means that we have overcome the original issue. Thanks for checking :)

**Comment by knz** [comment] 2023-03-29 18:18
please include some bench results from the beginning of the run, then after 10mn, as a comment on this issue, then we can close it.

**Comment by andreimatei** [comment] 2023-03-29 20:07
I can reproduce the failure on OSX. If I create the connections one at a time and pass them to the benchmark goroutines, it works fine. But the concurrent creation of connections seems to not work, with both `lib/pq` and `pgx`. I've got no idea what's going on or why it only happens on Macs; seems bad to me.

**Comment by ecwall** [comment] 2023-03-29 20:27
Here are results showing that this issue is resolved:
```
ubuntu@wall-test-0001:~/crdb_source$ ./dev bench pkg/bench -f 'SQL/TenantCockroach$/InsertDistinct/count=1000' --count=1000000 -v --stream-output --ignore-cache --timeout=100h
$ bazel test --test_timeout=360005 --test_arg -test.timeout=100h0m0s pkg/bench:all --nocache_test_results --test_arg -test.run=- --test_arg '-test.bench=SQL/TenantCockroach$/InsertDistinct/count=1000' --test_sharding_strategy=disabled --test_arg -test.v --test_arg -test.count=1000000 --crdb_test_off --test_output streamed
INFO: Invocation ID: 3e79a2f3-7ac0-41ef-80b3-7d2569f59202
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
INFO: Analyzed 3 targets (0 packages loaded, 219 targets configured).
INFO: Found 2 targets and 1 test target...
I230329 18:00:26.033056 1 (gostd) rand.go:199  [-] 1  random seed: 5079059572121543793
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) CPU @ 2.30GHz
BenchmarkSQL
    test_log_scope.go:161: test logs captured to: /tmp/cockroach/_tmp/99262b2ae388e806cec3034f997f74ca/logBenchmarkSQL681009506
    test_log_scope.go:79: use -show-logs to present logs inline
BenchmarkSQL/SharedProcessTenantCockroach
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16               981     1083675 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1011     1094648 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1106     1091718 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1140     1088298 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1156     1039348 ns/op
...
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1093     1017381 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1106     1049000 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1134     1008205 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1160      984843 ns/op
BenchmarkSQL/SharedProcessTenantCockroach/InsertDistinct/count=1000-16              1098     1123756 ns/op
[8 / 9] Testing //pkg/bench:bench_test; 1049s linux-sandbox
```

**Closed by ecwall** 2023-03-29 20:27 UTC
Labels: C-bug, branch-master, A-multitenancy, GA-blocker, T-multitenant
