### ISSUE TITLE
Test failure in CI build 3958

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1473] opened 2015-06-23 23:31 UTC
The following test appears to have failed:

[#3958](https://circleci.com/gh/cockroachdb/cockroach/3958):

```
=== RUN TestUnretryableError
I0623 23:28:42.990639     337 client.go:121] client 127.0.0.1:45453 connected
--- PASS: TestUnretryableError (0.31s)
=== RUN TestClientNotReady
E0623 23:28:43.311958     337 client.go:118] client 127.0.0.1:47183 failed to connect: client.go:303: client is closed
--- FAIL: TestClientNotReady (0.42s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
E0623 23:28:53.557970     337 client.go:118] client 127.0.0.1:36556 failed to connect: client.go:301: client timeout
W0623 23:28:53.569180     337 client.go:300] client 127.0.0.1:48723 unhealthy after 10ms
E0623 23:28:53.569334     337 client.go:118] client 127.0.0.1:48723 failed to connect: client.go:301: client timeout
W0623 23:28:53.569724     337 client.go:300] client 127.0.0.1:57091 unhealthy after 10ms
E0623 23:28:53.569902     337 client.go:118] client 127.0.0.1:57091 failed to connect: client.go:301: client timeout
--- FAIL: TestComplexScenarios (10.26s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
			github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:104 +0x28d
=== RUN TestUpdatedAddr
W0623 23:28:53.682196     337 server.go:212] asked for port 1234, got 1235
W0623 23:28:53.682369     337 server.go:212] asked for port 1234, got 1235
W0623 23:28:53.682463     337 server.go:212] asked for port 1234, got 1235
--- FAIL: TestUpdatedAddr (0.10s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
			/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x36
		github.com/cockroachdb/cockroach/rpc.TestMain(0xc20800a910)
			/go/src/github.com/cockroachdb/cockroach/rpc/main_test.go:56 +0x36
		main.main()
			github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:104 +0x28d
FAIL
FAIL	github.com/cockroachdb/cockroach/rpc	15.292s
=== RUN TestAll
I0623 23:28:54.710411     393 rpc_test.go:49] Arith.Add(1, 2): 3
I0623 23:28:54.715727     393 rpc_test.go:49] Arith.Add(1, 2): 3
--- PASS: TestAll (0.01s)
PASS
ok  	github.com/cockroachdb/cockroach/rpc/codec	0.035s
?   	github.com/cockroachdb/cockroach/rpc/codec/message	[no test files]
?   	github.com/cockroachdb/cockroach/rpc/codec/wire	[no test files]
=== RUN TestGetCertificateUser
--- PASS: TestGetCertificateUser (0.00s)
=== RUN TestUnretryableError
I0623 23:28:42.990639     337 client.go:121] client 127.0.0.1:45453 connected
--- PASS: TestUnretryableError (0.31s)
=== RUN TestClientNotReady
E0623 23:28:43.311958     337 client.go:118] client 127.0.0.1:47183 failed to connect: client.go:303: client is closed
--- FAIL: TestClientNotReady (0.42s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
E0623 23:28:53.557970     337 client.go:118] client 127.0.0.1:36556 failed to connect: client.go:301: client timeout
W0623 23:28:53.569180     337 client.go:300] client 127.0.0.1:48723 unhealthy after 10ms
E0623 23:28:53.569334     337 client.go:118] client 127.0.0.1:48723 failed to connect: client.go:301: client timeout
W0623 23:28:53.569724     337 client.go:300] client 127.0.0.1:57091 unhealthy after 10ms
E0623 23:28:53.569902     337 client.go:118] client 127.0.0.1:57091 failed to connect: client.go:301: client timeout
--- FAIL: TestComplexScenarios (10.26s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
			github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:104 +0x28d
=== RUN TestUpdatedAddr
W0623 23:28:53.682196     337 server.go:212] asked for port 1234, got 1235
W0623 23:28:53.682369     337 server.go:212] asked for port 1234, got 1235
W0623 23:28:53.682463     337 server.go:212] asked for port 1234, got 1235
--- FAIL: TestUpdatedAddr (0.10s)
	<autogenerated>:31: Test appears to have leaked an rpc client:
		net.(*pollDesc).Wait(0xc2080118e0, 0x72, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:84 +0x63
		net.(*pollDesc).WaitRead(0xc2080118e0, 0x0, 0x0)
			/usr/src/go/src/net/fd_poll_runtime.go:89 +0x51
		net.(*netFD).Read(0xc208011880, 0xc208065400, 0x400, 0x400, 0x0, 0x7f49198dcd80, 0xc208390018)
			/usr/src/go/src/net/fd_unix.go:242 +0x4b3
		net.(*conn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0x4403fb, 0x0, 0x0)
			/usr/src/go/src/net/net.go:121 +0x125
		net.(*TCPConn).Read(0xc208050160, 0xc208065400, 0x400, 0x400, 0xc2083123f0, 0x0, 0x0)
--
			/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:34 +0x36
		github.com/cockroachdb/cockroach/rpc.TestMain(0xc20800a910)
			/go/src/github.com/cockroachdb/cockroach/rpc/main_test.go:56 +0x36
		main.main()
			github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:104 +0x28d
FAIL
FAIL	github.com/cockroachdb/cockroach/rpc	15.292s
=== RUN TestAll
I0623 23:28:54.710411     393 rpc_test.go:49] Arith.Add(1, 2): 3
I0623 23:28:54.715727     393 rpc_test.go:49] Arith.Add(1, 2): 3
--- PASS: TestAll (0.01s)
PASS
ok  	github.com/cockroachdb/cockroach/rpc/codec	0.035s
?   	github.com/cockroachdb/cockroach/rpc/codec/message	[no test files]
?   	github.com/cockroachdb/cockroach/rpc/codec/wire	[no test files]
=== RUN TestGetCertificateUser
--- PASS: TestGetCertificateUser (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-06-24 01:45
dupe of #1444

**Closed by tamird** 2015-06-24 01:45 UTC
Labels: test-failure
