### ISSUE TITLE
circleci: failed tests (14438): TestNodeRestart 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5212] opened 2016-03-13 18:46 UTC
The following test appears to have failed:

[#14438](https://circleci.com/gh/cockroachdb/cockroach/14438):

```
E160313 18:44:16.939410 acceptance/cluster/localcluster.go:476  node=0 status=restart
W160313 18:44:20.240890 acceptance/chaos_test.go:251  round 2: cluster recovered
I160313 18:44:20.341298 acceptance/cluster/localcluster.go:629  stopping
I160313 18:44:20.341504 acceptance/cluster/localcluster.go:527  event stream done, resetting...: net/http: request canceled
I160313 18:44:20.341524 acceptance/cluster/localcluster.go:550  events monitor exits
--- FAIL: TestNodeRestart (12.02s)
	chaos_test.go:269: pq: storage/store.go:1486: Rejecting command with timestamp in the future: 1457894656282574686 (345.218982ms ahead)
	chaos_test.go:153: pq: storage/store.go:1486: Rejecting command with timestamp in the future: 1457894656282574686 (344.332176ms ahead)
=== RUN   TestGossipPeerings
I160313 18:44:22.195442 acceptance/cluster/localcluster.go:273  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
Node 2 - Store 0
Total Nodes Count:3, Total Store Count:3
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:64: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-17 13:49
Duplicate of #3087.

**Closed by petermattis** 2016-03-17 13:49 UTC
Labels: test-failure
