### ISSUE TITLE
changefeedccl: initial protected timestamp does not match cursor

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#113492] opened 2023-10-31 13:40 UTC
<img width="1289" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18633281/3481ca0b-efe7-4fe4-90aa-998a5957a446">

Jira issue: CRDB-33019

**Comment by miretskiy** [comment] 2023-10-31 14:10
Can you say more? When changefeed is created, a new record is also created.  What is the mismatch you're talking about?

**Comment by miretskiy** [comment] 2023-11-17 22:01
I think it actually works as intended.  I think this tiny table checkpoints almost immediately, and updates highwatermark accordingly.

**Comment by wenyihu6** [comment] 2023-11-20 14:52
Discussed in meetings and closing as no apparent issues. I will re-sync with Jay after he is back and re-open if needed.

**Closed by wenyihu6** 2023-11-20 14:52 UTC
Labels: C-bug, A-cdc, T-cdc
