### ISSUE TITLE
storage: flake in TestRangeLimitTxnMaxTimestamp 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#43737] opened 2020-01-06 14:31 UTC
I got the following failure in a totally unrelated PR: https://teamcity.cockroachdb.com/viewLog.html?buildId=1675685&buildTypeId=Cockroach_UnitTests

```
--- FAIL: TestRangeLimitTxnMaxTimestamp (0.27s)
    client_replica_test.go:945: cannot replace lease repl=(n1,s1):1 seq=1 start=0,0 epo=1 pro=0.000000100,110 with repl=(n2,s2):2 seq=0 start=0.000000100,190 exp=<nil> pro=0.000000100,191: couldn't request lease for (n2,s2):2: node not in the liveness table
```

**Comment by knz** [comment] 2020-01-06 14:32
cc @petermattis for triage

**Comment by petermattis** [comment] 2020-01-06 15:02
@knz Unless I'm missing something, this looks like a node liveness issue. Any reason you're thinking this is Storage level issue?

**Comment by knz** [comment] 2020-01-06 15:09
I did not look at the error past the name of the package where the test is present.

**Comment by petermattis** [comment] 2020-01-06 15:11
Confusingly, the `storage` package is owned by the KV team.

**Comment by knz** [comment] 2020-01-06 15:25
I was mindful of that. My usual way to process this type of failure is to look at who worked on that test last and ask for their recommendation. In this case, the code was written by Spencer in 2014-2015 and never touched since. So you're next in line to decide what to happen with it. :)

**Comment by petermattis** [comment] 2020-01-06 15:28
cc @ajwerner and @nvanbenschoten for KV triage.

**Comment by nvanbenschoten** [comment] 2020-01-06 15:48
I was able to reproduce after 6117 iterations. That's fast enough that it makes me wonder whether this was a recent regression.

**Comment by nvanbenschoten** [comment] 2020-01-06 18:37
I'm able to reproduce at-will using roachprod-stress. I'm not going to have time to dig further over the next few days though. The L2 support rotation is already picking up.

**Comment by nvanbenschoten** [comment] 2020-04-22 23:54
```
546537 runs so far, 0 failures, over 1h44m25s
```
That's quite a different story on `master` under `roachprod-stressrace`. We haven't seen this test fail since this was filed, so I'm going to close this. We can dig in again if we ever see it flake again.

**Closed by nvanbenschoten** 2020-04-22 23:54 UTC
Labels: A-storage, C-test-failure, branch-master
