### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6147] opened 2016-04-19 11:26 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/250d0afc7fa8dc7fb8a0a1800e10035c3e2e54a1

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x461141 m=0

goroutine 0 [idle]:
runtime.futex(0x1169268, 0x0, 0x0, 0x0, 0x0, 0x1168810, 0x0, 0x0, 0x40fbf4, 0x1169268, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x1169268, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x1169268)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820018000, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820148d80)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7ffe0a845780)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcfd158, 0x1148ca0, 0xb, 0xb, 0xb5bb01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820043f08, 0xb5bb60)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1168720)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 54 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc82061c80c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc82061c808)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc82061c800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc82030e000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc82030e000, 0x1148d18)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 86 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201bc000, 0xc820160b40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 16 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f41a5895ce8, 0x72, 0xc8203fa000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203de060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203de060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203de000, 0xc8203fa000, 0x400, 0x400, 0x0, 0x7f41a588e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820162020, 0xc8203fa000, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82012a960, 0x7f41a580f2c0, 0xc820162020, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8203f6000, 0xcfd917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8203f6000, 0xc820898000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8201be120)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8201be120, 0xc82034c038, 0x9, 0x9, 0xc81fff15e9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f41a5792d80, 0xc8201be120, 0xc82034c038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f41a5792d80, 0xc8201be120, 0xc82034c038, 0x9, 0x9, 0xc82012fb08, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82034c038, 0x9, 0x9, 0x7f41a5792d80, 0xc8201be120, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82034c000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc82012fa10, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82024d770)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 85 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201bc000, 0xc8203261a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 87 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f41a5895da8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200a93a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200a93a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200a9340, 0x0, 0x7f41a5895f50, 0xc8203e00c0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820138218, 0xc820041ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820138218, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82011fa00, 0x7f41a5894ec0, 0xc820138218, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201bc000, 0xc820160b60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 88 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201bc000, 0xc820160c60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 89 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201662a0)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201662a0)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 90 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201d5e04)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201d5e00)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201d5e00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc82061c800, 0xcfd9d8)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc82061c800, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc82061c800, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8200a93b0, 0xc8203d8320, 0xc8201d3310, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:191 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201bc000, 0xc82012f830)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 55 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f41a5895e68, 0x72, 0xc820037800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203e8060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203e8060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203e8000, 0xc820037800, 0x400, 0x400, 0x0, 0x7f41a588e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820034000, 0xc820037800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820012720, 0x7f41a580f2c0, 0xc820034000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8203f4000, 0xcfd917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8203f4000, 0xc820870000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8202262a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8202262a0, 0xc8200e0278, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f41a5792d80, 0xc8202262a0, 0xc8200e0278, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f41a5792d80, 0xc8202262a0, 0xc8200e0278, 0x9, 0x9, 0x2a24ce3fc6866c01, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8200e0278, 0x9, 0x9, 0x7f41a5792d80, 0xc8202262a0, 0xa5000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8200e0240, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201d81b0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8203f8120, 0xc8201d8240)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82011fa00, 0x7f41a5792dd0, 0xc8203f8120)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82011fa00, 0x7f41a5792ca8, 0xc8203f4000, 0x7f41a5792d08, 0xc8208b8370)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82011fa00, 0x7f41a580f260, 0xc820034000)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 15 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82024d770)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 39 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8203f8120)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

rax    0xca
rbx    0x0
rcx    0x461143
rdx    0x0
rdi    0x1169268
rsi    0x0
rbp    0x1
rsp    0x7ffe0a8455e0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x2c
r13    0xcfa3e0
r14    0x0
r15    0x8
rip    0x461141
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
89 runs so far, 0 failures, over 5s
196 runs so far, 0 failures, over 10s
295 runs so far, 0 failures, over 15s
400 runs so far, 0 failures, over 20s
499 runs so far, 0 failures, over 25s
603 runs so far, 0 failures, over 30s
702 runs so far, 0 failures, over 35s
804 runs so far, 0 failures, over 40s
905 runs so far, 0 failures, over 45s
1010 runs so far, 0 failures, over 50s
1112 runs so far, 0 failures, over 55s
1215 runs so far, 0 failures, over 1m0s
1320 runs so far, 0 failures, over 1m5s
1421 runs so far, 0 failures, over 1m10s
1522 runs so far, 0 failures, over 1m15s
1626 runs so far, 0 failures, over 1m20s
1729 runs so far, 0 failures, over 1m25s
1829 runs so far, 0 failures, over 1m30s
1928 runs so far, 0 failures, over 1m35s
2028 runs so far, 0 failures, over 1m40s
2127 runs so far, 0 failures, over 1m45s
2226 runs so far, 0 failures, over 1m50s
2331 runs so far, 0 failures, over 1m55s
2435 runs so far, 0 failures, over 2m0s
2535 runs so far, 0 failures, over 2m5s
2635 runs so far, 0 failures, over 2m10s
2730 runs so far, 0 failures, over 2m15s
2835 runs so far, 0 failures, over 2m20s
2930 runs so far, 0 failures, over 2m25s
3031 runs so far, 0 failures, over 2m30s
3127 runs so far, 0 failures, over 2m35s
3222 runs so far, 0 failures, over 2m40s
3323 runs so far, 0 failures, over 2m45s
3416 runs so far, 0 failures, over 2m50s
3511 runs so far, 0 failures, over 2m55s
3613 runs so far, 0 failures, over 3m0s
3714 runs so far, 0 failures, over 3m5s
3812 runs so far, 0 failures, over 3m10s
3908 runs so far, 0 failures, over 3m15s
4007 runs so far, 0 failures, over 3m20s
4104 runs so far, 0 failures, over 3m25s
4199 runs so far, 0 failures, over 3m30s
4297 runs so far, 0 failures, over 3m35s
4397 runs so far, 0 failures, over 3m40s
4497 runs so far, 0 failures, over 3m45s
4593 runs so far, 0 failures, over 3m50s
4691 runs so far, 0 failures, over 3m55s
4786 runs so far, 0 failures, over 4m0s
4885 runs so far, 0 failures, over 4m5s
4983 runs so far, 0 failures, over 4m10s
5082 runs so far, 0 failures, over 4m15s
5180 runs so far, 0 failures, over 4m20s
5276 runs so far, 0 failures, over 4m25s
5374 runs so far, 0 failures, over 4m30s
5471 runs so far, 0 failures, over 4m35s
5568 runs so far, 0 failures, over 4m40s
5670 runs so far, 0 failures, over 4m45s
5767 runs so far, 0 failures, over 4m50s
5865 runs so far, 0 failures, over 4m55s
5966 runs so far, 0 failures, over 5m0s
6064 runs so far, 0 failures, over 5m5s
6161 runs so far, 0 failures, over 5m10s
6261 runs so far, 0 failures, over 5m15s
6358 runs so far, 0 failures, over 5m20s
6456 runs so far, 0 failures, over 5m25s
6559 runs so far, 0 failures, over 5m30s
6653 runs so far, 0 failures, over 5m35s
6751 runs so far, 0 failures, over 5m40s
6845 runs so far, 0 failures, over 5m45s
6946 runs so far, 0 failures, over 5m50s
7040 runs so far, 0 failures, over 5m55s
7138 runs so far, 0 failures, over 6m0s
7233 runs so far, 0 failures, over 6m5s
7328 runs so far, 0 failures, over 6m10s
7424 runs so far, 0 failures, over 6m15s
7519 runs so far, 0 failures, over 6m20s
7616 runs so far, 0 failures, over 6m25s
7707 runs so far, 0 failures, over 6m30s
7801 runs so far, 0 failures, over 6m35s
7899 runs so far, 0 failures, over 6m40s
7992 runs so far, 0 failures, over 6m45s
8086 runs so far, 0 failures, over 6m50s
8178 runs so far, 0 failures, over 6m55s
8266 runs so far, 0 failures, over 7m0s
8358 runs so far, 0 failures, over 7m5s
8453 runs so far, 0 failures, over 7m10s
8548 runs so far, 0 failures, over 7m15s
8637 runs so far, 0 failures, over 7m20s
8729 runs so far, 0 failures, over 7m25s
8825 runs so far, 0 failures, over 7m30s
8919 runs so far, 0 failures, over 7m35s
9011 runs so far, 0 failures, over 7m40s
9108 runs so far, 0 failures, over 7m45s
9204 runs so far, 0 failures, over 7m50s
9295 runs so far, 0 failures, over 7m55s
9384 runs so far, 0 failures, over 8m0s
9480 runs so far, 0 failures, over 8m5s
9574 runs so far, 0 failures, over 8m10s
9665 runs so far, 0 failures, over 8m15s
9755 runs so far, 0 failures, over 8m20s
9846 runs so far, 0 failures, over 8m25s
9932 runs so far, 0 failures, over 8m30s
10024 runs so far, 0 failures, over 8m35s
10116 runs so far, 0 failures, over 8m40s
10205 runs so far, 0 failures, over 8m45s
10295 runs so far, 0 failures, over 8m50s
10387 runs so far, 0 failures, over 8m55s
10478 runs so far, 0 failures, over 9m0s
10567 runs so far, 0 failures, over 9m5s
10654 runs so far, 0 failures, over 9m10s
10749 runs so far, 0 failures, over 9m15s
10840 runs so far, 0 failures, over 9m20s
10930 runs so far, 0 failures, over 9m25s
11024 runs so far, 0 failures, over 9m30s
11114 runs so far, 0 failures, over 9m35s
11204 runs so far, 0 failures, over 9m40s
11300 runs so far, 0 failures, over 9m45s
11393 runs so far, 0 failures, over 9m50s
11490 runs so far, 0 failures, over 9m55s
11586 runs so far, 0 failures, over 10m0s
11679 runs so far, 0 failures, over 10m5s
11780 runs so far, 0 failures, over 10m10s
11875 runs so far, 0 failures, over 10m15s
11964 runs completed, 1 failures, over 10m19s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
