### ISSUE TITLE
core: zone config not set

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#38074] opened 2019-06-06 19:39 UTC
Related to https://github.com/cockroachdb/cockroach/issues/38065

```
alter table <TableName> CONFIGURE ZONE USING lease_preferences = '[[+region=gcp-asia-southeast1]]';
CONFIGURE ZONE 1
Time: 1.011314805s

```
Running SHOW ZONE CONFIGURATIONS; afterwards returns no result for <TableName>, even hours after the fact.

**Comment by ajwerner** [comment] 2019-06-06 19:48
Perhaps related, the Data Distribution page times out.

**Comment by DuskEagle** [comment] 2019-06-06 19:57
In the cluster we noticed this in, certain tables did have zone configurations set. However, when we tried to set a zone configuration on a table that already had an index zone configuration, the command succeeded but the result did not show up when running `SHOW ZONE CONFIGURATIONS`. It's unclear if the index zone configuration is an important piece of the puzzle or a red herring.

**Comment by DuskEagle** [comment] 2019-06-06 22:48
When we removed the index zone configuration before adding a table zone configuration, we were able to successfully add the table zone configuration afterward. The existence of the index config zone config definitely seems to have been the cause.

**Comment by nvanbenschoten** [comment] 2019-07-18 14:03
I decided to take a look at this because it popped up as one on 6 Core S-1 issues yesterday. I think I tracked the issue down to our determination of whether a zone configuration is a "subzone placeholder", which is here:
https://github.com/cockroachdb/cockroach/blob/68d9da92fce00ceec147611f630b147bd518a0da/pkg/config/zone.go#L593-L598

Notice that we only consider the zone's num_replicas when determining whether a zone is a placeholder or not. This indicates that if you modify a zone but don't give it a num_replicas value then the modification will be ignored by `SHOW ZONE CONFIGURATION`, which is powered by [`crdb_internal.zones`](https://github.com/cockroachdb/cockroach/blob/68d9da92fce00ceec147611f630b147bd518a0da/pkg/sql/crdb_internal.go#L1905).

Here's a small reproduction:
```sql
root@:26257/defaultdb> create table t (i int);
CREATE TABLE

root@:26257/defaultdb> create table t2 (i int, index(i));
CREATE TABLE

root@:26257/defaultdb> alter table t CONFIGURE ZONE USING constraints = COPY FROM PARENT, lease_preferences = '[[+rack=0]]';
CONFIGURE ZONE 1

root@:26257/defaultdb> alter index t2_i_idx CONFIGURE ZONE USING constraints = COPY FROM PARENT, lease_preferences = '[[+rack=0]]';
CONFIGURE ZONE 1

root@:26257/defaultdb> SELECT zone_id, zone_name FROM crdb_internal.zones WHERE cli_specifier IS NOT NULL;
  zone_id |       zone_name
+---------+-----------------------+
        0 | .default
        1 | system
       15 | system.jobs
       16 | .meta
       17 | .system
       22 | .liveness
       52 | defaultdb.t
       53 | defaultdb.t2@t2_i_idx

root@:26257/defaultdb> alter table t2 CONFIGURE ZONE USING constraints = COPY FROM PARENT, lease_preferences = '[[+rack=1]]';
CONFIGURE ZONE 1

root@:26257/defaultdb> SELECT zone_id, zone_name FROM crdb_internal.zones WHERE cli_specifier IS NOT NULL;
  zone_id |       zone_name
+---------+-----------------------+
        0 | .default
        1 | system
       15 | system.jobs
       16 | .meta
       17 | .system
       22 | .liveness
       52 | defaultdb.t
       53 | defaultdb.t2@t2_i_idx

root@:26257/defaultdb> alter table t2 CONFIGURE ZONE USING num_replicas=3, constraints = COPY FROM PARENT, lease_preferences = '[[+rack=1]]';
CONFIGURE ZONE 1

root@:26257/defaultdb> SELECT zone_id, zone_name FROM crdb_internal.zones WHERE cli_specifier IS NOT NULL;
  zone_id |       zone_name
+---------+-----------------------+
        0 | .default
        1 | system
       15 | system.jobs
       16 | .meta
       17 | .system
       22 | .liveness
       52 | defaultdb.t
       53 | defaultdb.t2
       53 | defaultdb.t2@t2_i_idx
```
Notice that the `defaultdb.t2` zone only appears in `crdb_internal.zones` after it has been assigned a `num_replicas`.

What I'm not sure about is what the right fix for this is. It might be either:
1. make sure that any updates to zone `defaultdb.t2` move it from a subzone placeholder to a real zone by assigning to `num_replicas`
2. make the determination of whether a zone is a "subzone placeholder" based on more than just `num_replicas`

@danhhz do you have any knowledge here? I see that you reviewed #19717, which introduced the concept of subzone placeholder. If not, do you know who would know about them?

**Comment by andreimatei** [comment] 2019-10-02 14:30
cc @rohany

**Comment by rohany** [comment] 2019-10-02 15:15
yeah this is definitely an issue with the *num_replicas == 0 being the subzone placeholder sentinel. I would want to do suggestion 2 (introduce a flag or something about whether a zone is a placeholder or not), but that doesn't seem backwards compatible. Doing suggestion 1 seems like it will be a fine option for now. When we update a zone, we can set the num_replicas field to nil if num_replicas isn't requested to be set to avoid this behavior.

**Comment by andreimatei** [comment] 2019-10-02 15:46
I don't know anything about anything, but I think it's time we do away with the concept of "placeholder" zones completely now that we have cascading zone configs. Hopefully if that concept goes away, this issue goes away.

**Comment by rohany** [comment] 2019-10-02 15:47
I agree as well, but I don't know enough to estimate the consequences of that. I think we should do suggestion 1 for 19.2, and then look to remove subzone placeholders after the release

**Comment by awoods187** [comment] 2019-10-02 22:30
Glad we are tackling this. I think fixing this in the short-term is a good idea and we can take our time on the longer-term solution.

**Closed** 2019-10-03 15:15 UTC
Labels: A-kv-distribution, C-bug, S-1-blocking-adoption
