### ISSUE TITLE
Test failure in CI build 7907

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2644] opened 2015-09-23 20:25 UTC
The following test appears to have failed:

[#7907](https://circleci.com/gh/cockroachdb/cockroach/7907):

```
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:278 +0x31d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820155aa0, 0xc82015f7a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x62
FAIL	github.com/cockroachdb/cockroach/storage	1.421s
=== RUN   TestBatchBasics
I0923 20:25:09.773445 973 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0923 20:25:09.774341 973 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0923 20:25:09.776738 973 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-23 20:33
dupe of #2566.

**Closed by tamird** 2015-09-23 20:33 UTC
Labels: test-failure
