### ISSUE TITLE
Simulated network latencies in cockroach multi-region demo are too subtle

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#77001] opened 2022-02-24 19:20 UTC
**Issue:**
Cockroach demo in a multi-region mode need more dramatic latency differences, at least by an order of magnitude to illustrate MR benefits. Currently, in a MR demo, EU is <5 ms away from US.

**Repro:**
- `cockroach demo --no-example-database --insecure --nodes 9 --global`
- confirm the cluster is regionalized with `SHOW REGIONS FROM CLUSTER;` and other simple metadata queries
- point a browser to the db console and observe the latencies on the network map page

**Environment:**
 - CockroachDB version v21.2.4
 - Server OS: Windows10
 - Client app: n/a

**Additional context**
This issue has a significant/material impact on customer demos that can be accommodated by a local/portable/laptop setup, which eliminates demo risks factors and allows customers to take ownership/repro the demo in-house.

Jira issue: CRDB-13365

**Comment by ajstorm** [comment] 2022-02-28 22:36
@rafiss pointed out to me today that this is likely a duplicate of https://github.com/cockroachdb/cockroach/issues/63098.  @a-entin can you please retry without `--insecure` and let me know if it works?

**Comment by stbof** [comment] 2022-02-28 22:53
@ajstorm At one point this [demo doc](https://www.cockroachlabs.com/docs/dev/demo-low-latency-multi-region-deployment.html#step-1-simulate-a-multi-region-cluster) was able to demonstrate latency differences and it used the `--insecure` flag.

**Comment by ajstorm** [comment] 2022-02-28 23:38
Do you know when the last time the multiregion demo worked?

**Comment by stbof** [comment] 2022-02-28 23:58
I joined in Sept 2021, so I don't know. Perhaps @rmloveland might know.

**Comment by a-entin** [comment] 2022-03-01 14:59
Checked. The regression occurred in one of the minors of 21.1
20.2.19 (latest minor) - works
21.1.0 (first minor) - works
21.1.15 (latest minor) - does not work
21.2.?? - does not work

i can binary search to identify the 21.1.X version, lmk if need me to

**Comment by a-entin** [comment] 2022-03-01 15:12
21.1.10 doesn't
21.1.5 doesn't

So between 21.1.1 and 21.1.4

**Closed** 2022-03-17 06:26 UTC
Labels: C-bug

**Comment by ajstorm** [comment] 2022-03-17 15:38
Just to note, this is now fixed in master.  I'm going to let it bake over the weekend and then backport it next week.
