### ISSUE TITLE
raft: `panic: group 3 after(13) is out of range [committed(14)]`

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2360] opened 2015-09-04 13:55 UTC
The following test appears to have failed:

[#6917](https://circleci.com/gh/cockroachdb/cockroach/6917):

```
I0904 13:55:03.425600 950 raft/raft.go:468  group 3 100000001 received vote from 100000001 at term 7
I0904 13:55:03.425762 950 raft/raft.go:447  group 3 100000001 became leader at term 7
I0904 13:55:03.427252 950 stopper.go:229  draining; tasks left:
1      storage/replica.go:1143
E0904 13:55:03.427636 950 raft/log.go:99  group 3 after(13) is out of range [committed(14)]
panic: group 3 after(13) is out of range [committed(14)]

goroutine 2645 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc8202b0730, 0x13ef620, 0x29, 0xc820011b20, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1ce
github.com/coreos/etcd/raft.(*raftLog).append(0xc82000aa80, 0xc82011adc0, 0x1, 0x1, 0x48)
	/go/src/github.com/coreos/etcd/raft/log.go:99 +0x26d
github.com/coreos/etcd/raft.(*raft).appendEntry(0xc8202aef70, 0xc82011adc0, 0x1, 0x1)
	/go/src/github.com/coreos/etcd/raft/raft.go:373 +0x1a9
github.com/coreos/etcd/raft.stepLeader(0xc8202aef70, 0x2, 0x0, 0x100000001, 0x0, 0x0, 0x0, 0xc82011adc0, 0x1, 0x1, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:539 +0x529
--
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:268 +0x87
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202b4120, 0xc820150530)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	3.303s
=== RUN   TestBatchBasics
I0904 13:54:59.670303 945 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0904 13:54:59.674079 945 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0904 13:54:59.679652 945 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-09-04 14:16
Likely to be a dupe of #1878.

**Closed** 2015-09-10 22:29 UTC
Labels: test-failure
