### ISSUE TITLE
opt: referenced WITH not found when building WithScan

### ISSUE THREAD

**Issue by aayushshah15** [cockroachdb/cockroach#43420] opened 2019-12-20 20:08 UTC
A sqlsmith run caught this, @savoie indicated that it seems like a legit bug.

```
  - assertion failure
  - error with attached stack trace:
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildWithScan
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1525
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:260
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildSelect
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:529
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:194
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildLimitOffset
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:1161
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:206
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildProject
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:571
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).buildRelational
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational.go:197
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).build
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:131
    github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder.(*Builder).Build
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go:100
    github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:267
    github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171
    github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170
    github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:740
    github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:373
    github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:374
    github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:976
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:821
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:713
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:416
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1283
    github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1212
    github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:451
    github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
    	/Users/aayushshah/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584
    runtime.goexit
    	/Users/aayushshah/.gvm/gos/go1.12/src/runtime/asm_amd64.s:1337
  - error with embedded safe details: couldn't find With expression with ID %d
    -- arg 1: <opt.WithID>
  - couldn't find With expression with ID 3
CRASHER:
caused by: server panic: pq: internal error: couldn't find With expression with ID 3
```

The query that caused this is as follows:

```
STATEMENT:
WITH
	with_45383 (col_245194) AS (SELECT * FROM (VALUES (1981629909:::OID)) AS tab_111612 (col_245194)),
	with_45384 (col_245195)
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						(ARRAY[1785944020:::OID,3189245027:::OID,3364231263:::OID]),
						(ARRAY[1543083689:::OID,2061845090:::OID]),
						(ARRAY[2256201809:::OID,1275517629:::OID]),
						(
							ARRAY[3678913498:::OID,1896316741:::OID,2596850662:::OID,765594920:::OID,4080437401:::OID,3025668190:::OID,1678582154:::OID,1146434578:::OID,475267780:::OID]
						),
						(ARRAY[3144217290:::OID,342562322:::OID,3052667344:::OID]),
						(
							CASE
							WHEN false
							THEN ARRAY[2956227234:::OID,1277896688:::OID,1562043077:::OID,1306577109:::OID,730894763:::OID,1552569912:::OID,3119907789:::OID]
							ELSE ARRAY[2419253458:::OID,3231740512:::OID,696246744:::OID,1972342443:::OID]
							END
						)
				)
					AS tab_111613 (col_245195)
		)
SELECT
	'[[[{}], true], [{}], {}, {"]UXmrkNviKi+": true, "c": []}, [[], [[]]], [[]]]':::JSONB AS col_245196,
	tab_111614._float4 AS col_245197,
	tab_111614._timestamptz AS col_245198,
	(-1470719863.949913105):::DECIMAL AS col_245199,
	NULL AS col_245200,
	tab_111614._interval AS col_245201,
	tab_111614._timestamp AS col_245202,
	(
		WITH
			with_45385 (col_245203)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								('1990-05-06':::DATE),
								('infinity':::DATE),
								('5874897-12-31':::DATE),
								('1988-08-31':::DATE),
								(current_timestamp():::DATE::DATE),
								('1994-12-28':::DATE)
						)
							AS tab_111615 (col_245203)
					EXCEPT ALL SELECT * FROM (VALUES (NULL), (NULL)) AS tab_111616 (col_245204)
				),
			with_45386 (col_245205)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								((-775243253):::INT8),
								((-161394624):::INT8),
								(1016547993:::INT8),
								(1898144085:::INT8),
								(1108629432:::INT8),
								(1302828545:::INT8)
						)
							AS tab_111617 (col_245205)
				),
			with_45387 (col_245206)
				AS (
					SELECT
						*
					FROM
						(
							VALUES
								(ARRAY['1977-12-16':::DATE,'1972-11-10':::DATE,'1994-07-29':::DATE]),
								(
									('1993-11-12':::DATE::DATE || (ARRAY['1970-01-01':::DATE]::DATE[] || NULL::DATE[])::DATE[]::DATE[])::DATE[]
								),
								(ARRAY['1975-02-28':::DATE]),
								(ARRAY['1995-10-19':::DATE]),
								(ARRAY['1983-04-09':::DATE,'1983-01-13':::DATE,'1981-11-29':::DATE])
						)
							AS tab_111618 (col_245206)
				)
		SELECT
			tab_111614._int4 AS col_245208
		FROM
			with_45385 AS cte_ref_13240
		WHERE
			EXISTS(SELECT '\xa313afbc8c':::BYTES AS col_245207 LIMIT 79:::INT8)
		LIMIT
			1:::INT8
	)
		AS col_245209,
	tab_111614._bool AS col_245210,
	'e':::STRING AS col_245211,
	(-0.5713967084884644):::FLOAT8 AS col_245212,
	tab_111614._bytes AS col_245213,
	tab_111614._date AS col_245214,
	tab_111614._inet AS col_245215,
	tab_111614._uuid AS col_245216
FROM
	defaultdb.public.seed@[0] AS tab_111614
LIMIT
	56:::INT8;
```
Here are the full logs: 
[crashlog.txt](https://github.com/cockroachdb/cockroach/files/3990050/crashlog.txt)

**Comment by aayushshah15** [comment] 2019-12-20 20:09
cc @justinj.

**Comment by jordanlewis** [comment] 2019-12-20 20:36
I think this is a duplicate of #42373.

**Closed by jordanlewis** 2019-12-20 20:36 UTC
