### ISSUE TITLE
stability: system key stats inconsistency

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12278] opened 2016-12-12 13:49 UTC
sha: a855534

node 6 (`104.196.20.102`) died with inconsistencies:
```
E161212 12:40:03.585655 1093495575 storage/replica_command.go:1877  [n6,s11,r15190/2:/Table/51/1/8{099837â<80>¦-100398â<80>¦},@c4229ea000] replica {9 17 1} is inconsistent: expected checksum 528010d7e1e00ddb6ec8d02fd46d468c29f22cf764e271e29a6fd599e589370ea6d3b1cbc5aa0536645c89634568be2fe080df77161a99fc62ae9a05e85e5933, got 72908c051b4dfd87a708a039a496b2b54b926608bd2a4e1c4f4f1656a595cbb09ccf29a8b3bdf091acd37e1177d2c0f65f2cee164cb23c13960e1fe4eaf31204
--- leaseholder
+++ follower
-0.000000000,0 /Local/RangeID/15190/r/RangeStats
-  ts:<zero>
-  value:^R^D^H^@^P^@^X^@ ^@(^@2|^MÌu<83>^C     <87>Ö×^N<92><82><8f>^T^QíÏ¦^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!a³^C^B^@^@^@^@)H<9e>^C^@^@^@^@^@17Õõ^@^@^@^@^@9H<9e>^C^@^@^@^@^@A*Þ^M^A^@^@^@^@IH<9e>^C^@^@^@^@^@Q*     ^@^@^@^@^@^@Y^_^@^@^@^@^@^@^@aº<88>^@^@^@^@^@^@i4^@^@^@^@^@^@^@p^@
-  raw_key:/Local/RangeID/15190/r/RangeStats raw_value:120408001000180020002800327c0dcc7583030987d6d70e92828f1411edcfa600000000001900000000000000002161b303020000000029489e0300000000003137d5f5000000000039489e030000000000412ade0d010000000049489e030000000000512a09000000000000591f0000000000000061ba880000000000006934000000000000007000
+0.000000000,0 /Local/RangeID/15190/r/RangeStats
+  ts:<zero>
+  value:^R^D^H^@^P^@^X^@ ^@(^@2|É<94>^Xî^C     <87>Ö×^N<92><82><8f>^T^QíÏ¦^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!a³^C^B^@^@^@^@)H<9e>^C^@^@^@^@^@17Õõ^@^@^@^@^@9H<9e>^C^@^@^@^@^@A*Þ^M^A^@^@^@^@IH<9e>^C^@^@^@^@^@Q*     ^@^@^@^@^@^@Y^_^@^@^@^@^@^@^@a<9a><88>^@^@^@^@^@^@i3^@^@^@^@^@^@^@p^@
+  raw_key:/Local/RangeID/15190/r/RangeStats raw_value:120408001000180020002800327cc99418ee030987d6d70e92828f1411edcfa600000000001900000000000000002161b303020000000029489e0300000000003137d5f5000000000039489e030000000000412ade0d010000000049489e030000000000512a09000000000000591f00000000000000619a880000000000006933000000000000007000
F161212 12:40:03.585755 1093487834 storage/replica_command.go:1893  [n6,s11,r15190/2:/Table/51/1/8{099837â<80>¦-100398â<80>¦},@c4229ea000] consistency check failed with 2 inconsistent replicas
goroutine 1093487834 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x412d4c01, 0x22e9ec75, 0x2a4b6c0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:849 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2a4ccc0, 0xc400000004, 0x224abda, 0x1a, 0x765, 0xc42758cf80, 0x76)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:714 +0x7b1
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f3d7061cf80, 0xc431d73aa0, 0x4, 0x2, 0x19fd116, 0x36, 0xc42e385c20, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f3d7061cf80, 0xc431d73aa0, 0x1, 0xc400000004, 0x19fd116, 0x36, 0xc42e385c20, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f3d7061cf80, 0xc431d73aa0, 0x19fd116, 0x36, 0xc42e385c20, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc4229ea000, 0x7f3d7061cf80, 0xc431d73aa0, 0xc4345d72c0, 0x36, 0x40, 0xc4345d7340, 0x36, 0x40, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1893 +0x65c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addAdminCmd(0xc4229ea000, 0x7f3d7061cf80, 0xc431d73aa0, 0x148f8297da823575, 0x0, 0xb00000006, 0x2, 0x3b56, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1660 +0x39c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4229ea000, 0x7f3d7061cf80, 0xc431d73aa0, 0x148f8297da823575, 0x0, 0xb00000006, 0x2, 0x3b56, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1230 +0x682
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420075500, 0x7f3d7061cf80, 0xc431d73aa0, 0x148f8297da823575, 0x0, 0xb00000006, 0x2, 0x3b56, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2471 +0x6c5
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc420071aa0, 0x7f3d7061cf80, 0xc431d73aa0, 0x0, 0x0, 0xb00000006, 0x2, 0x3b56, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:824 +0x2a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc4200ea000, 0xc4295b1cd8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x100
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc42024e580, 0x7f3d7061cf40, 0xc42825e2c0, 0xc42371f2e8, 0xc42825e2c0, 0x62ef23, 0xc4216326f0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:835 +0x1ed
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc42024e580, 0x7f3d7061cf40, 0xc42825e2c0, 0xc42371f2e8, 0x2595e20, 0xc4248c70a0, 0x11)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:857 +0xa0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0x2574660, 0xc42024e580, 0xc4327141e0, 0xc42371f2c0, 0xc432714120)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:189 +0x64
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:192 +0x23c
```

Leaving node down and silencing alert

**Comment by mberhault** [comment] 2016-12-12 15:46
ditto on `104.196.175.87`:

```
E161212 15:40:48.531158 1098080218 storage/replica_command.go:1877  [n4,s8,r17511/1:/Table/51/1/24{85817â<80>¦-91350â<80>¦},@c442a3f200] replica {9 17 2} is inconsistent: expected checksum e09a0e4593fb66bd5173a72790f49b03a23efded573f62e523788f9a44bf29a83cd7ab46dde2f9154dd0623143eee8e3c2dfcbe743e36708b3c6008df98f20c3, got 5931cbce7b992970015949e60d83149e0aaa80bf59b32a0ec141d2ac64e63d701f136408c1bfb923ea39464a91624bc4c9a493e8da100509c9719afd81632231
--- leaseholder
+++ follower
-0.000000000,0 /Local/RangeID/17511/r/RangeStats
-  ts:<zero>
-  value:^R^D^H^@^P^@^X^@ ^@(^@2|0<9c>­Q^C      "<85>ýZs<8c><8f>^T^Qÿ¤¹^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!^@<8f>^@^B^@^@^@^@)^S<99>^C^@^@^@^@^@1<85>tô^@^@^@^@^@9^S<99>^C^@^@^@^@^@A{^Z^L^A^@^@^@^@I^S<99>^C^@^@^@^@^@Q^L
^@^@^@^@^@^@Y"^@^@^@^@^@^@^@a<84>®^@^@^@^@^@^@i@^@^@^@^@^@^@^@p^@
-  raw_key:/Local/RangeID/17511/r/RangeStats raw_value:120408001000180020002800327c309cad5103092285fd5a738c8f1411ffa4b9000000000019000000000000000021008f000200000000291399030000000000318574f40000000000391399030000000000417b1a0c0100000000491399030000000000510c0a0000000000005922000000000000006184ae0000000000006940000000000000007000
+0.000000000,0 /Local/RangeID/17511/r/RangeStats
+  ts:<zero>
+  value:^R^D^H^@^P^@^X^@ ^@(^@2|ùÚ°{^C "<85>ýZs<8c><8f>^T^Qÿ¤¹^@^@^@^@^@^Y^@^@^@^@^@^@^@^@!^@<8f>^@^B^@^@^@^@)^S<99>^C^@^@^@^@^@1<85>tô^@^@^@^@^@9^S<99>^C^@^@^@^@^@A{^Z^L^A^@^@^@^@I^S<99>^C^@^@^@^@^@Q^L
^@^@^@^@^@^@Y"^@^@^@^@^@^@^@a¤®^@^@^@^@^@^@iA^@^@^@^@^@^@^@p^@
+  raw_key:/Local/RangeID/17511/r/RangeStats raw_value:120408001000180020002800327cf9dab07b03092285fd5a738c8f1411ffa4b9000000000019000000000000000021008f000200000000291399030000000000318574f40000000000391399030000000000417b1a0c0100000000491399030000000000510c0a00000000000059220000000000000061a4ae0000000000006941000000000000007000
```

**Comment by mberhault** [comment] 2016-12-12 15:46
taking entire cluster down and silencing

**Comment by petermattis** [comment] 2016-12-12 16:17
In both cases, the difference in the stats is in `Sys{Bytes,Count}`:

```
[SysBytes: 35002 != 34970 SysCount: 52 != 51]
[SysBytes: 44676 != 44708 SysCount: 64 != 65]
```

**Comment by petermattis** [comment] 2016-12-12 16:21
`delta` was undergoing splits when these errors occurred and was stable for 3 days before the splits. Could we have recently introduced an error in our stats accounting during splits?

@spencerkimball Did you change code in this area recently?

**Comment by petermattis** [comment] 2016-12-12 17:20
@tamird suggested this might be related to the Raft tombstone key. I'm about to check that hypothesis.

**Comment by petermattis** [comment] 2016-12-12 17:47
Neither occurrence seems to involve a Raft tombstone key. Using `cockroach debug range-data` on the consistency check failure for `r17511` shows that the stats differ on disk (as expected):

`104.196.175.87`:
`/Local/RangeID/17511/r/RangeStats: contains_estimates:false last_update_nanos:1481557229503874338 intent_age:12166399 gc_bytes_age:0 live_bytes:33591040 live_count:235795 key_bytes:16020613 key_count:235795 val_bytes:17570427 val_count:235795 intent_bytes:2572 intent_count:34 sys_bytes:44676 sys_count:64`

`104.196.23.238`:
`/Local/RangeID/17511/r/RangeStats: contains_estimates:false last_update_nanos:1481557602776547566 intent_age:12179081 gc_bytes_age:0 live_bytes:33598193 live_count:235844 key_bytes:16023945 key_count:235844 val_bytes:17574248 val_count:235844 intent_bytes:2572 intent_count:34 sys_bytes:44708 sys_count:65`

Both ranges have the exact same number of replicated range local keys: 64. You might notice that more than just `Sys{Bytes,Count}` differ in the stats. That is because `104.196.175.87` crashed and stopped processing operations while `104.196.23.238` plowed on ahead.

**Comment by petermattis** [comment] 2016-12-12 18:11
Looking at the `r15190` consistency failure, I can see that one replica has 51 system keys while the other has 52. The difference is:

```
+/Local/Range/"\xbb\x89\xfdpi\x8d\x05\xce-\xab\xa5\x1234f00c3a-8e6b-4d8f-96d0-59b1af40cb31\x00\x01\xf8!\xc5o\x88"/Transaction/addrKey:/id:"ec1de2b9-b15e-4424-8790-4ea4ff2a31b7":
```

I think this might be due to the replica containing that key being significantly ahead of the crashed replica. 

Note that the crashed replica in this instance (`104.196.20.102`) has the following range stats:

`/Local/RangeID/15190/r/RangeStats: contains_estimates:false last_update_nanos:1481546401721403674 intent_age:10933290 gc_bytes_age:0 live_bytes:33797160 live_count:237129 key_bytes:16110971 key_count:237129 val_bytes:17686189 val_count:237129 intent_bytes:2346 intent_count:31 sys_bytes:35002 sys_count:52`

So the replica thinks it has 52 system keys, but a manual count reveals only 51.

**Comment by petermattis** [comment] 2016-12-12 18:51
I also tried running a local 4-node cluster via `roachdemo` configured with small (1 MB) ranges and a 1m consistency check interval to stress splits and consistency checks. Nothing. And I tried running `zerosum -n 4 -m 3 -c none`. That has now been running fine for 10m and the cluster has 850+ ranges. 

I'm out of ideas. @bdarnell anything to add? @tamird were you able to put any suspicion on the {raft,lease} applied index optimization?

**Comment by petermattis** [comment] 2016-12-12 19:04
Heh, as soon as I wrote the last message I had another idea. Perhaps the problem is related to the Raft tombstone key being present on the left-hand side of the split. Sure enough, I see that `r17511` was created fairly recently:

```
I161212 15:14:26.130865 71 storage/replica_command.go:2380  [n4,split,s8,r502/8:/Table/51/1/24{80285…-91350…},@c43e07c900] initiating a split of this range at key /Table/51/1/248581762302092281/"1101ddb2-ee03-465a-a6c5-e0b23c03707d"/503874 [r17511]
```

On `104.196.175.87` (`delta-04`):

```
/Local/RangeID/502/r/RaftTombstone: next_replica_id:8
```

But on `104.196.23.238` (`delta-09`) there is no tombstone key. Recall from earlier that the stats on `delta-04` say there are 64 system keys while on `delta-09` the stats say 65 system keys. The way we compute stats during a split is to compute the stats for the left-hand side from the replica state and compute the right-hand side stats using arithmetic. What this suggests it that we should find an inconsistency for `r502` as well. 

On `104.196.175.87` (`delta-04`): `/Local/RangeID/502/r/RangeStats: contains_estimates:false last_update_nanos:1481557223823727111 intent_age:18653288 gc_bytes_age:0 live_bytes:33596160 live_count:235781 key_bytes:16019584 key_count:235781 val_bytes:17576576 val_count:235781 intent_bytes:4620 intent_count:54 sys_bytes:68375 sys_count:94`

And `104.196.23.238` (`delta-09`): `/Local/RangeID/502/r/RangeStats: contains_estimates:false last_update_nanos:1481557615393354944 intent_age:18674456 gc_bytes_age:0 live_bytes:33604679 live_count:235840 key_bytes:16023596 key_count:235840 val_bytes:17581083 val_count:235840 intent_bytes:4620 intent_count:54 sys_bytes:68343 sys_count:93`

Both the `SysBytes` and `SysCount` deltas line up here: the delta in the stats for `r502` match the deltas in `r17511`. The only bit that is slightly off is that `sudo ./cockroach debug keys --from human:/Local/RangeID/502/r/RaftTombstone --sizes /mnt/data2` reports the size of the tombstone key+value as 31 bytes, not 32.

**Comment by petermattis** [comment] 2016-12-12 19:14
I'm not sure how to fix this. The tombstone key has been baked into the stats for the right-hand side range. Fixing would require recomputing the stats for system keys. I suppose we could write a migration to do this. The underlying issue with tombstone keys has been fixed. Is that migration worth the effort?

Cc @cockroachdb/stability

**Comment by petermattis** [comment] 2016-12-12 19:34
For completeness, `r15190` was created via a split from `r7204` which was the range in #12130 that caused a consistency check failure on `delta` last week due to the Raft tombstone key.

**Comment by bdarnell** [comment] 2016-12-13 04:24
The tombstone key bug didn't make it into any beta releases, did it? As long as this only affects clusters that were running from master during a small window, I don't think there's a need to add a migration to recompute stats.

**Comment by petermattis** [comment] 2016-12-13 13:32
The tombstone bug was introduced in dc6c5f66d05d9bc64721c916b847665233b2ab37 which is in beta-20161201 and was fixed in 1fe2feb4af4f8eec71ba53a8646f7dc4717a426d which is in beta-20161208.

**Comment by bdarnell** [comment] 2016-12-13 13:49
OK, so it did make it out in the wild. But we haven't gotten any reports of problems from anywhere but our own test clusters, so that's good. I think we can probably wait and see if anyone runs into this before investing in a migration.

**Comment by petermattis** [comment] 2016-12-13 15:11
I agree we should hold off on writing the migration. The tombstone problem was not easy to trip over.

**Comment by petermattis** [comment] 2017-01-23 20:42
With no reports from the wild, it seems unlikely that we're going to write a migration to recompute the MVCC stats at this point.

**Closed by petermattis** 2017-01-23 20:42 UTC
