### ISSUE TITLE
Optimizer to rewrite queries to scan for min(),max() values

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#61648] opened 2021-03-08 19:45 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
When trying to find the `min(id),max(id)` for a PK value a FULL scan is run. When you re-write the query to force two individual queries to be run, it performs as expected.  Would like to see the optimizer do this re-write.

```
root@localhost:26257/defaultdb> select min(id),max(id) from int_pk;
  min |   max
------+----------
    1 | 5000000
(1 row)

Time: 1.526s total (execution 1.525s / network 0.000s)

root@localhost:26257/defaultdb> explain select min(id),max(id) from int_pk;
       tree      |        field        |  description
-----------------+---------------------+-----------------
                 | distribution        | full
                 | vectorized          | true
  group (scalar) |                     |
   └── scan      |                     |
                 | estimated row count | 5000000
                 | table               | int_pk@primary
                 | spans               | FULL SCAN
(7 rows)

Time: 1ms total (execution 1ms / network 0ms)


root@localhost:26257/defaultdb> select (select min(id) from int_pk), (select max(id) from int_pk);
  min |   max
------+----------
    1 | 5000000
(1 row)

Time: 2ms total (execution 2ms / network 0ms)

root@localhost:26257/defaultdb> explain select (select min(id) from int_pk), (select max(id) from int_pk);
            tree           |        field        |         description
---------------------------+---------------------+-------------------------------
                           | distribution        | local
                           | vectorized          | false
  root                     |                     |
   ├── values              |                     |
   │                       | size                | 2 columns, 1 row
   ├── subquery            |                     |
   │    │                  | id                  | @S1
   │    │                  | original sql        | (SELECT min(id) FROM int_pk)
   │    │                  | exec mode           | one row
   │    └── group (scalar) |                     |
   │         └── scan      |                     |
   │                       | estimated row count | 1
   │                       | table               | int_pk@primary
   │                       | spans               | LIMITED SCAN
   │                       | limit               | 1
   └── subquery            |                     |
        │                  | id                  | @S2
        │                  | original sql        | (SELECT max(id) FROM int_pk)
        │                  | exec mode           | one row
        └── group (scalar) |                     |
             └── revscan   |                     |
                           | estimated row count | 1
                           | table               | int_pk@primary
                           | spans               | LIMITED SCAN
                           | limit               | 1
(25 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

**Comment by rytaft** [comment] 2021-03-15 23:32
I think this could be supported with a new exploration rule that detects when a `ScalarGroupBy` has multiple aggregates that are all `min` or `max` aggregates with a single variable argument. The `ScalarGroupBy` would be replaced by a `Select` with multiple subqueries (similar to the rewrite shown above), with one subquery for each aggregate. This would allow `ReplaceScalarMinMaxWithLimit` to fire for each subquery.

**Comment by rytaft** [comment] 2021-03-16 20:25
Looks like this is actually a duplicate of https://github.com/cockroachdb/cockroach/issues/35038.

**Closed by rytaft** 2021-03-16 20:25 UTC
Labels: A-sql-optimizer, C-enhancement, good first issue
