### ISSUE TITLE
cli: `cockroach quit` reports transient RPC error during server shutdown, confuses acceptance tests

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#25870] opened 2018-05-23 19:33 UTC
During a merge to master build for #25863 (which doesn't seem to have related changes), `TestDockerCLI/test_audit_log.tcl` flaked: https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=675599&_focus=1873

There seems to be an error encountered during shutdown of the test.  The end of the output is:

```
.180523 18:29:23.153390098 EXPECT TEST: INTERRUPT TO FOREGROUND PROCESS

Error: interrupted
Failed running "sql"

.180523 18:29:23.561740353 EXPECT TEST: BEGIN STOP SERVER
graceful shutdown failed: rpc error: code = Internal desc = grpc: compressed flag set with identity or empty encoding; proceeding with hard shutdown
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

hard shutdown failed: Failed to connect to the node: error sending drain request: rpc error: code = Canceled desc = grpc: the client connection is closing
Failed running "quit"
child process exited abnormally
    while executing
"system "$argv quit""
    (procedure "stop_server" line 4)
    invoked from within
"stop_server $argv"
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_audit_log.tcl" line 87)
non-zero exit code: 1
    	cli_test.go:92: non-zero exit code: 1
```

**Comment by knz** [comment] 2018-05-25 17:27
Also I am not planning to look at this - I know next to nothing about gRPC and very little about `cockroach quit` and the server shutdown process.

/cc @tschottdorf for triage

**Comment by petermattis** [comment] 2018-05-25 17:29
This is a bug in `cockroacah quit`. I think this bug is a duplicate of #26047 (or vice versa). @benesch and/or @a-robinson are looking into it.

**Comment by tschottdorf** [comment] 2018-05-29 10:03
This is also failing the decommission roachtest: https://github.com/cockroachdb/cockroach/issues/26144

IMO we should whitelist this transient error until the matter is resolved, at least for the purpose of `./cockroach quit`.

**Comment by knz** [comment] 2018-05-29 11:18
addressing this client-side in #26158

**Closed** 2018-05-29 18:53 UTC
Labels: A-cli, C-test-failure, S-3-productivity
