### ISSUE TITLE
sql: add connection limit syntax

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#54400] opened 2020-09-15 14:18 UTC
In this [issue](https://github.com/cockroachdb/cockroach/issues/54116), we plan to support `CONNECTION LIMIT = -1` as a no-op. This issue tracks a general purpose implementation of `CONNECTION LIMIT = foo` on a per database limit.

**Comment by rafiss** [comment] 2021-12-09 23:45
duplicate of https://github.com/cockroachdb/cockroach/issues/54241

**Closed by rafiss** 2021-12-09 23:45 UTC
Labels: C-enhancement
