### ISSUE TITLE
circleci: failed tests (13913): TestGossipPeerings TestSingleKey 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4909] opened 2016-03-06 17:27 UTC
The following test appears to have failed:

[#13913](https://circleci.com/gh/cockroachdb/cockroach/13913):

```
I160306 17:25:11.117936 acceptance/replication_test.go:50  waiting for first range to have 3 replicas
I160306 17:25:12.119161 acceptance/replication_test.go:66  found 3 replicas
I160306 17:25:13.140068 acceptance/gossip_peerings_test.go:124  restarting node 0
I160306 17:25:15.833024 acceptance/gossip_peerings_test.go:135  restarting node 1
I160306 17:25:18.469390 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestGossipPeerings (12.79s)
	localcluster.go:568: expected event &{0 die}, got <nil> (after [])
=== RUN   TestGossipRestart
--- SKIP: TestGossipRestart (0.00s)
	gossip_peerings_test.go:147: TODO(pmattis): #4445
=== RUN   TestDockerJava
I160306 17:25:21.101050 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
....I160306 17:25:21.345443 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160306 17:25:21.794690 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.3
I160306 17:25:21.794736 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
--
I160306 17:26:52.831936 acceptance/replication_test.go:66  found 1 replicas
I160306 17:26:53.833819 acceptance/replication_test.go:66  found 1 replicas
I160306 17:26:54.835677 acceptance/replication_test.go:66  found 1 replicas
I160306 17:26:55.837438 acceptance/replication_test.go:66  found 1 replicas
I160306 17:26:55.938002 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestSingleKey (20.19s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 1
=== RUN   TestStatusServer
--- SKIP: TestStatusServer (0.00s)
	status_server_test.go:94: TODO(pmattis): #4512
=== RUN   TestBuildBabyCluster
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:66: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 20:38
Duplicate of #4894.

**Closed by petermattis** 2016-03-06 20:38 UTC
Labels: test-failure
