### ISSUE TITLE
opt: unexpected behavior in an edge case with RANGE mode of window framing

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#53442] opened 2020-08-25 22:31 UTC
Found by sqlsmith in #48268.

The following results in a panic
```
CREATE TABLE table1 (col1 INT8 PRIMARY KEY);

CREATE TABLE table2 (col2 INT2 PRIMARY KEY);

SELECT
  max(col2::INT8) OVER (
    PARTITION BY col2 ORDER BY col2 RANGE 1 PRECEDING
  )
FROM
  table2 NATURAL JOIN table1
WHERE
  false;
```
This is a pathological case with RANGE mode of framing in which ORDER BY clause (which must contain exactly one column) contains the same column as the one mentioned in PARTITION BY clause, and such case was supposed to be fixed by #44666. Interestingly, if I remove the cast within `max`, then the plan is different and the panic doesn't occur.

The panic occurs because at the execution time that single ORDER BY column has `-1` as its index which is populated incorrectly in https://github.com/cockroachdb/cockroach/blob/96e89e091a278b9938d35060b9c1b3583125af49/pkg/sql/opt/exec/execbuilder/relational.go#L2190-L2193
This occurs, I think, because the optimizer thinks that `col2` column is not needed in the output, so `w.RangeOffsetColumn == 1` gets mapped to `-1`.

cc @RaduBerinde

**Comment by mgartner** [comment] 2020-08-31 19:23
The issue is that the `ReduceWindowPartitionCols` normalization rule is pruning the range offset column, because `WHERE false` implies a cardinality of zero making the functional dependency "from" set empty: `()-->(1-4,6)`.

It seems to me that the special case of `RANGE` frames requires `ReduceWindowPartitionCols` and `SimplifyWindowOrdering` to not fire. Is this the best way to fix this panic and the original issue fixed by #44666: to peak into the WindowsItem->WindowsItemPrivate->WindowFrame->Mode (if it exists), and do not fire these rules if it is `tree.RANGE`? I think that would eliminate the need for the `RangeOffsetColumn` workaround from #44666. A potential downside is that other optimizations may not fire as a result.

**Comment by mgartner** [comment] 2020-08-31 20:38
I'm more confident that this is the correct fix given that there is also a panic with the same query as above, but `ORDER BY col1`. If execution requires `col1`, it can't be pruned.

```
CREATE TABLE table1 (col1 INT8 PRIMARY KEY);

CREATE TABLE table2 (col2 INT2 PRIMARY KEY);

SELECT
  max(col2::INT8) OVER (
    PARTITION BY col2 ORDER BY col1 RANGE 1 PRECEDING
  )
FROM
  table2 NATURAL JOIN table1
WHERE
  false;
```

**Comment by yuzefovich** [comment] 2020-08-31 20:44
The correctness comes first, so I'm in favor of disabling these two rules (can we only disable `SimplifyWindowOrdering`?) in the case of `RANGE` mode of framing.

**Closed** 2020-09-02 19:03 UTC
Labels: C-bug
