### ISSUE TITLE
build: GID '20' already exists

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#28488] opened 2018-08-11 15:35 UTC
Something broke recently for `build/builder.sh`:

```
~ build/builder.sh
groupadd: GID '20' already exists
autouseradd: /usr/sbin/groupadd failed
```

**Comment by benesch** [comment] 2018-08-13 18:39
Yeah, sorry about this. Fix coming in a second. Also, duplicate of #28299; consolidating on that issue.

**Closed by benesch** 2018-08-13 18:39 UTC
Labels: A-build-system, C-bug
