### ISSUE TITLE
cli: don't allow balancer to be specified via command line flags

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4732] opened 2016-02-29 22:30 UTC
Choosing between usage and range-count for rebalancing decisions is not something we should expect operators to specify on the command line. Let's choose the appropriate default for now and then move towards an automated approach.

@jseldess don't document the `--balance_mode` flag.

**Comment by mrtracy** [comment] 2016-02-29 22:42
If we're going to remove this flag, that is going to have consequences for testing cockroach with multiple nodes on a single machine (which is the reason this flag was added in the first place).  There are a few ways to do this:

1. Declare that "rangecount" is the new default. I'm fine with this.
2. Allow stores to be specified with a maximum size that is independent of the disk size. You would also need to update the way that a store's Capacity is computed to account for this. In this case, "usage" can remain the default and the single-node scenario still works.
3. Declare that running multiple nodes on a single machine is not a valid testing scenario for the purposes of rebalancing - I don't like this scenario, but it's possible.

Additionally, I don't know if we'll ever have an "automated approach" for this use case; this flag was intended for developers to use alternative balancing strategies, and while it initially is only used to solve the "multi-node, same hard drive" conundrum, it could eventually allow developers to test out different balancing algorithms.  Instead, I think it should moved to gossiped cluster configuration; the main problem with this flag is that it's a cluster-wide setting, not a per-node setting, and thus makes no sense as a command line argument.

**Comment by bdarnell** [comment] 2016-02-29 22:44
@BramGruneir is working on the second option, to be able to cap the size of each store.

**Comment by spencerkimball** [comment] 2016-03-01 13:23
@mrtracy again, I'm trying to avoid having @jseldess explain what these flags mean. And once we release a flag in the wild, we're going to have a much more difficult time removing it.

**Comment by mrtracy** [comment] 2016-03-01 16:01
@spencerkimball I'm fine with removing the flag, we just need to pick an alternative solution for the problem it was solving.  It looks like we're going to go with solution #2.

**Comment by BramGruneir** [comment] 2016-03-01 16:32
Just a head's up that the maximum size work will be done by end of week.

**Comment by spencerkimball** [comment] 2016-03-06 18:26
@BramGruneir should this be closed?

**Comment by BramGruneir** [comment] 2016-03-06 18:39
As soon as I get the size changed merged.
The code should be ready to go this evening.

**Comment by jseldess** [comment] 2016-03-07 22:53
`--store=size` documented here: https://www.cockroachlabs.com/docs/start-a-node.html#store

**Closed** 2016-03-09 15:05 UTC
Labels: docs-done
