### ISSUE TITLE
sql: sequelize requires ORDER BY in aggregations

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25148] opened 2018-04-28 16:22 UTC
Sequelizes uses the following query, note the ORDER BY inside the aggregation.

```sql
query TT
SELECT t.typname enum_name, array_agg(e.enumlabel ORDER BY enumsortorder) enum_value
    FROM pg_type t
    JOIN pg_enum e ON t.oid = e.enumtypid
    JOIN pg_catalog.pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
    GROUP BY 1
```

cc @RaduBerinde @andy-kimball @justinj

**Comment by RaduBerinde** [comment] 2018-04-28 22:28
Note that one (perhaps temporary) option is partial support: only allow a single `ORDER BY` clause per query (or if there are multiple, they must match). This would be pretty easy to implement and would cover this particular case.

**Comment by knz** [comment] 2018-04-29 11:25
Good call. Thanks for the suggestion.

**Comment by jordanlewis** [comment] 2019-04-30 15:34
This is a duplicate of #23620

**Closed by jordanlewis** 2019-04-30 15:34 UTC
Labels: A-sql-pgcompat, A-sql-planning, C-enhancement
