### ISSUE TITLE
stress: failed test in cockroach/util/retry/retry.test: TestRetryExceedsMaxBackoff

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5223] opened 2016-03-14 09:43 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f587240217828432af6a84192503586355af19ab

Stress build found a failed test:

```
=== RUN   TestRetryExceedsMaxBackoff
--- FAIL: TestRetryExceedsMaxBackoff (1.00s)
	retry_test.go:44: expected retry loop to run for 20ms, actually ran for 1.000448268s
```

Run Details:

```
6514 runs so far, 0 failures, over 5s
12904 runs so far, 0 failures, over 10s
19003 runs so far, 0 failures, over 15s
24950 runs so far, 0 failures, over 20s
30637 runs so far, 0 failures, over 25s
36076 runs so far, 0 failures, over 30s
41403 runs so far, 0 failures, over 35s
46526 runs so far, 0 failures, over 40s
46774 runs completed, 1 failures, over 41s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 18:06
Duplicate of #5209.

**Closed by petermattis** 2016-03-14 18:06 UTC
Labels: Robot, test-failure
