### ISSUE TITLE
sql: dotNET server explorer fails silently with npgsql

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#18026] opened 2017-08-30 15:03 UTC
The server explorer for npgsql's support for .net's server explorer fails with the following query.

```
I170830 10:52:42.628529 341 sql/executor.go:1311  [client=[::1]:53463,user=maxroach2,n1] parsing: SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'BASE TABLE') tmp
I170830 10:52:42.628529 341 sql/executor.go:1311  [client=[::1]:53463,user=maxroach2,n1] preparing: SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'BASE TABLE') tmp
I170830 10:52:42.629030 341 sql/executor.go:644  [client=[::1]:53463,user=maxroach2,n1] execPrepared: SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'BASE TABLE') tmp
I170830 10:52:42.629030 341 sql/executor.go:1072  [client=[::1]:53463,user=maxroach2,n1] executing 1/1: SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'BASE TABLE') AS tmp
I170830 10:52:42.629030 341 sql/executor.go:1311  [client=[::1]:53463,user=maxroach2,n1] SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'BASE TABLE') AS tmp
I170830 10:52:42.629529 341 sql/executor.go:1777  [client=[::1]:53463,user=maxroach2,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause
```

```
SELECT * 
FROM (
  SELECT table_catalog, table_schema, table_name, table_type 
  FROM information_schema.tables 
  WHERE table_type = 'BASE TABLE'
) AS tmp
```

But when I execute both the inner and outer query in the SQL console, they both work.
```
root@:26257/bank> SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table
_type = 'BASE TABLE') AS tmp;
+---------------+--------------+--------------+------------+
| table_catalog | table_schema |  table_name  | table_type |
+---------------+--------------+--------------+------------+
| def           | bank         | accounts     | BASE TABLE |
| def           | system       | descriptor   | BASE TABLE |
| def           | system       | eventlog     | BASE TABLE |
| def           | system       | jobs         | BASE TABLE |
| def           | system       | lease        | BASE TABLE |
| def           | system       | namespace    | BASE TABLE |
| def           | system       | rangelog     | BASE TABLE |
| def           | system       | settings     | BASE TABLE |
| def           | system       | ui           | BASE TABLE |
| def           | system       | users        | BASE TABLE |
| def           | system       | web_sessions | BASE TABLE |
| def           | system       | zones        | BASE TABLE |
+---------------+--------------+--------------+------------+
(12 rows)

Time: 16.88ms
```

The user maxroach2 has grant all permission on the bank database, so I'm not sure why this isn't working.

**Comment by jordanlewis** [comment] 2017-08-30 15:04
@BramGruneir can you try the queries again as the `maxroach2` user from the console?

**Comment by BramGruneir** [comment] 2017-08-30 15:07
weird:
```
maxroach2@:26257/bank> SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = '
ASE TABLE';
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
+---------------+--------------+------------+------------+
(0 rows)

Time: 3.9146ms

maxroach2@:26257/bank> SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = '
ASE TABLE';
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
+---------------+--------------+------------+------------+
(0 rows)

Time: 4.237ms
```

And in the logs I'm still seeing:
`query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause`

Think this might be a permissions issue?

**Comment by jordanlewis** [comment] 2017-08-30 15:09
The `query not supported` message is not an error - it's an info log explaining that the query will be executed with the classic sql execution engine.

Did you paste the log wrong or did you really search for `'ASE TABLE'`? :) That would be a problem.

**Comment by BramGruneir** [comment] 2017-08-30 15:12
Hmm... not sure, reran:

```
maxroach2@:26257/> set database = bank;
SET

Time: 837.4µs

maxroach2@:26257/bank> SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE table_type = 'B
ASE TABLE';
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
+---------------+--------------+------------+------------+
(0 rows)

Time: 3.8741ms

maxroach2@:26257/bank> SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE
table_type = 'BASE TABLE') AS tmp;
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
+---------------+--------------+------------+------------+
(0 rows)

Time: 4.8715ms
```

**Comment by jordanlewis** [comment] 2017-08-30 15:30
I can't reproduce this problem. 

```
root@:26257/> create database jordan;
CREATE DATABASE

Time: 8.367312ms

root@:26257/> grant all on database jordan to jordan;
GRANT

Time: 3.317348ms
```

```
jordan@:26257/jordan> create table foo(a int);
CREATE TABLE

Time: 14.804987ms

jordan@:26257/jordan> SELECT * FROM (SELECT table_catalog, table_schema, table_name, table_type FROM information_schema.tables WHERE
                   -> table_type = 'BASE TABLE') AS tmp;;
+---------------+--------------+------------+------------+
| table_catalog | table_schema | table_name | table_type |
+---------------+--------------+------------+------------+
| def           | jordan       | foo        | BASE TABLE |
+---------------+--------------+------------+------------+
(1 row)

Time: 1.783741ms
```

**Comment by TedBear42** [comment] 2017-12-02 02:13
I'm getting this bug when trying to use the postgresql JDBC driver to connect to cockroachDB with presto.

"query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause"

The query I'm trying to run in presto is 
"show tables from postgresql.db1;"

If I look into the cockroach logs I see that this is getting executed.
I171202 02:07:07.628332 513 sql/executor.go:1505  [client=10.63.128.116:60038,user=root,n1] SELECT NULL AS table_cat, n.nspname AS table_schem, c.relname AS table_name, CASE (n.nspname ~ '^pg_') OR (n.nspname = 'information_schema') WHEN true THEN CASE WHEN (n.nspname = 'pg_catalog') OR (n.nspname = 'information_schema') THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TABLE' WHEN 'v' THEN 'SYSTEM VIEW' WHEN 'i' THEN 'SYSTEM INDEX' ELSE NULL END WHEN n.nspname = 'pg_toast' THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TOAST TABLE' WHEN 'i' THEN 'SYSTEM TOAST INDEX' ELSE NULL END ELSE CASE c.relkind WHEN 'r' THEN 'TEMPORARY TABLE' WHEN 'p' THEN 'TEMPORARY TABLE' WHEN 'i' THEN 'TEMPORARY INDEX' WHEN 'S' THEN 'TEMPORARY SEQUENCE' WHEN 'v' THEN 'TEMPORARY VIEW' ELSE NULL END END WHEN false THEN CASE c.relkind WHEN 'r' THEN 'TABLE' WHEN 'p' THEN 'TABLE' WHEN 'i' THEN 'INDEX' WHEN 'S' THEN 'SEQUENCE' WHEN 'v' THEN 'VIEW' WHEN 'c' THEN 'TYPE' WHEN 'f' THEN 'FOREIGN TABLE' WHEN 'm' THEN 'MATERIALIZED VIEW' ELSE NULL END ELSE NULL END AS table_type, d.description AS remarks FROM pg_catalog.pg_namespace AS n, pg_catalog.pg_class AS c LEFT JOIN pg_catalog.pg_description AS d ON ((c.oid = d.objoid) AND (d.objsubid = 0)) LEFT JOIN pg_catalog.pg_class AS dc ON ((d.classoid = dc.oid) AND (dc.relname = 'pg_class')) LEFT JOIN pg_catalog.pg_namespace AS dn ON ((dn.oid = dc.relnamespace) AND (dn.nspname = 'pg_catalog')) WHERE ((c.relnamespace = n.oid) AND (n.nspname LIKE 'db1')) AND ((((false OR (((c.relkind IN ('r', 'p')) AND (n.nspname !~ '^pg_')) AND (n.nspname != 'information_schema'))) OR (((c.relkind = 'v') AND (n.nspname != 'pg_catalog')) AND (n.nspname != 'information_schema'))) OR (c.relkind = 'm')) OR (c.relkind = 'f')) ORDER BY table_type, table_schem, table_name
I171202 02:07:07.633591 513 sql/executor.go:2084  [client=10.63.128.116:60038,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause
I171202 02:07:07.635671 513 sql/executor.go:1505  [client=10.63.128.116:60038,user=root,n1] SELECT (0 results) done

Now if I look at that database and table, I have grant to public, root for all.

If I run that same query in the cockroachDB I get this.
+-----------+-------------+------------+------------+---------+
| table_cat | table_schem | table_name | table_type | remarks |
+-----------+-------------+------------+------------+---------+
| NULL      | db1         | a          | TABLE      | NULL    |
| NULL      | db1         | foo        | TABLE      | NULL    |
+-----------+-------------+------------+------------+---------+

**Comment by jordanlewis** [comment] 2018-04-26 20:44
Hi @TedBear42, sorry for the very late response. If you still have access to this, can you see what user you connected to Cockroach with in your JDBC connection?

**Comment by jordanlewis** [comment] 2018-04-26 20:44
@BramGruneir it would be cool if you re-tried the server explorer sometime soon. Lots of things have changed.

**Comment by BramGruneir** [comment] 2018-04-30 15:11
Indeed.  I'll give it a try this week.

**Comment by jordanlewis** [comment] 2019-09-03 15:57
@BramGruneir how did you test this? I want to redo it.

**Comment by jordanlewis** [comment] 2019-09-19 02:46
Closing - @BramGruneir if you get a chance please try to repro this but I think the underlying issue here probably got fixed.

**Closed by jordanlewis** 2019-09-19 02:46 UTC
Labels: A-sql-pgcompat, C-investigation
