### ISSUE TITLE
sql/opt: push filter through shard column union

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#75288] opened 2022-01-21 19:19 UTC
**Is your feature request related to a problem? Please describe.**
This issue pertains to missing optimizations which can help when searching hash-sharded tables/indexes. Consider

```sql
CREATE TABLE t (i INT PRIMARY KEY USING HASH WITH BUCKET_COUNT = 8);
INSERT INTO t SELECT * FROM generate_series(1, 1000000);
ANALYZE t;
```

The following query gets a rather nice plan:

```sql
SELECT * FROM t ORDER BY i LIMIT 10;
```

However, if we add any filter that the optimizer doesn't know how to deal with in spans, you get a full scan. Consider:

```sql
> EXPLAIN  SELECT * FROM t WHERE i%2 != 0  ORDER BY i LIMIT 10;
                                             info
----------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • limit
  │ estimated row count: 10
  │ count: 10
  │
  └── • filter
      │ estimated row count: 333,333
      │ filter: (i % 2) != 0
      │
      └── • sort
          │ estimated row count: 80
          │ order: +i
          │
          └── • scan
                estimated row count: 80 (<0.01% of the table; stats collected 3 minutes ago)
                table: t@t_pkey
                spans: [/0 - /7]
```
**Describe the solution you'd like**

Ideally we'd get the same plan as:
```sql
SELECT
    *
FROM
    (
        SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 0
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 1
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 2
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 3
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 4
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 5
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 6
        UNION ALL SELECT * FROM t WHERE i % 2 != 0 AND crdb_internal_i_shard_8 = 7
    )
ORDER BY
    i
LIMIT
    10;
```

**Additional context**

One note is that the estimated stats on the filter seem funky. Maybe there's some obvious reason not to do this. Seems like if we can parallelize these scans, we pretty much always should. 

Jira issue: CRDB-12543

**Comment by msirek** [comment] 2022-01-24 17:59
Perhaps there is a better way to stitch the results of the separate shard scans together to maintain the PK sort order than by using UNION ALL, like using some metadata in the Scan itself to instruct the execution engine.  One could imagine future customers having giant clusters and hundreds of hash buckets, which would lead to some EXPLAIN plans which are very hard to read, especially if the query were joining multiple tables.

**Comment by ajwerner** [comment] 2022-01-24 18:06
No disagreement. I care more about the optimization than the explain diagram, but I agree, they do get rather unwieldy. It seems like this optimization could be relevant in other contexts, especially if we have other rules which might rewrite disjunctions or `IN` into `UNION ALL`.

**Comment by msirek** [comment] 2022-02-07 17:09
@ajwerner I thought I read somewhere that you are going to start using a STORED crdb_internal_i_shard_8 column instead of VIRTUAL for your use case.  I just want to make sure this is the case because if we try the new optimization in this issue, it might not get picked up by the optimizer if the column is virtual because stats collection is currently not allowed on virtual columns and the UNION ALL query plan may not look as good.

**Comment by ajwerner** [comment] 2022-02-07 17:12
> @ajwerner I thought I read somewhere that you are going to start using a STORED crdb_internal_i_shard_8 column instead of VIRTUAL for your use case. I just want to make sure this is the case because if we try the new optimization in this issue, it might not get picked up by the optimizer if the column is virtual because stats collection is currently not allowed on virtual columns and the UNION ALL query plan may not look as good.

The plan is to proceed with virtual. I wonder if there's a solution to the stats problem. Perhaps we should synthesize stats for the shard column; it's rather special in terms of its properties.

**Comment by msirek** [comment] 2022-02-07 17:18
> 
> The plan is to proceed with virtual. I wonder if there's a solution to the stats problem. Perhaps we should synthesize stats for the shard column; it's rather special in terms of its properties.

Yeah, I thought maybe there's a way to build stats from the implicit CHECK constraint, but I don't know if that's something that's easy to do in the code.  The problem is that we only see 8 values coming from the check constraint and use that to reduce the selectivity.  Maybe we could internally identify check constraints and not apply selectivity from them (somehow), since we know rows that aren't qualified for the check constraint can't be in the table anyway.

**Comment by rytaft** [comment] 2022-02-08 19:34
It sounds like moving to a virtual shard column will increase the priority of https://github.com/cockroachdb/cockroach/issues/69120. I think fixing that issue will fix this (related to @msirek's point above).

**Comment by msirek** [comment] 2022-02-08 20:20
For the optgen portion my initial idea was to create a new rule similar to SplitLimitedScanIntoUnionScans, but to handle Selects, copying the filters and remapping columns.  Incomplete code is here (with some debugging code that can be ignored):

https://github.com/msirek/cockroach/blob/29f4d3c0c05455ab579b25432aa4c09c96caca77/pkg/sql/opt/xform/rules/limit.opt#L99-L123
https://github.com/msirek/cockroach/blob/29f4d3c0c05455ab579b25432aa4c09c96caca77/pkg/sql/opt/xform/limit_funcs.go#L177-L197

branch:
https://github.com/msirek/cockroach/tree/splitSelectIntoUnionSelects

**Comment by msirek** [comment] 2022-02-17 15:46
Looking back into this...

**Comment by msirek** [comment] 2022-02-22 02:28
Switching to balanced binary tree of UNION ALLs vs. a left-deep tree helps performance for cases with higher number of hash buckets:
`32 buckets`
```
SET experimental_enable_hash_sharded_indexes=true;
CREATE TABLE t (i INT PRIMARY KEY USING HASH WITH BUCKET_COUNT = 32, j int);
INSERT INTO t SELECT g,g FROM generate_series(1, 1000000) g(g);
ANALYZE t;
-- left deep:
SELECT * FROM t ORDER BY i LIMIT 1 OFFSET 999999;
     i    |    j
----------+----------
  1000000 | 1000000
(1 row)

Time: 1.266s

-- balanced:
SELECT * FROM t ORDER BY i LIMIT 1 OFFSET 999999;
     i    |    j
----------+----------
  1000000 | 1000000
(1 row)

Time: 775ms
```
`256 buckets`
```
SET experimental_enable_hash_sharded_indexes=true;
CREATE TABLE t (i INT PRIMARY KEY USING HASH WITH BUCKET_COUNT = 256, j int);
INSERT INTO t SELECT g,g FROM generate_series(1, 1000000) g(g);
ANALYZE t;
-- left deep:
SELECT * FROM t ORDER BY i LIMIT 1 OFFSET 999999;
     i    |    j
----------+----------
  1000000 | 1000000
(1 row)

Time: 6.353s

-- balanced:
SELECT * FROM t ORDER BY i LIMIT 1 OFFSET 999999;
     i    |    j
----------+----------
  1000000 | 1000000
(1 row)

Time: 969ms 
```

**Closed** 2022-03-04 20:06 UTC
Labels: C-enhancement, A-sql-optimizer, T-sql-queries
