### ISSUE TITLE
geomfn tests fail on ppc64le

### ISSUE THREAD

**Issue by amitsadaphule** [cockroachdb/cockroach#72228] opened 2021-10-29 12:50 UTC
**Describe the problem**

I built the cockroachdb **v20.2.17** on ppc64le and when I executed the test suite, I found that there were test failures for `pkg/geo/geomfn` package.

When I analysed the log [geomfn_fail.log](https://github.com/cockroachdb/cockroach/files/7441992/geomfn_fail.log). Logs of failing tests pasted below (Please refer attached full package test log for more details):

```
--- FAIL: TestShortestLineString/MULTILINESTRING_to_MULTILINESTRING (0.00s)
	distance_test.go:682: 
			Error Trace:	distance_test.go:682
			Error:      	Not equal: 
							expected: geo.Geometry{spatialObject:geopb.SpatialObject{Type:2, EWKB:geopb.EWKB{0x1, 0x2, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80}, SRID:0, ShapeType:2, BoundingBox:(*geopb.BoundingBox)(0xc0002d5160)}}
							actual  : geo.Geometry{spatialObject:geopb.SpatialObject{Type:2, EWKB:geopb.EWKB{0x1, 0x2, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40}, SRID:0, ShapeType:2, BoundingBox:(*geopb.BoundingBox)(0xc0002d5200)}}
							
							Diff:
							--- Expected
							+++ Actual
							@@ -5,4 +5,4 @@
								00000000  01 02 00 00 00 02 00 00  00 00 00 00 00 00 00 00  |................|
							-   00000010  80 00 00 00 00 00 00 00  80 00 00 00 00 00 00 00  |................|
							-   00000020  80 00 00 00 00 00 00 00  80                       |.........|
							+   00000010  40 00 00 00 00 00 00 00  40 00 00 00 00 00 00 00  |@.......@.......|
							+   00000020  40 00 00 00 00 00 00 00  40                       |@.......@|
							   },
							@@ -11,6 +11,6 @@
							   BoundingBox: (*geopb.BoundingBox)({
							-   LoX: (float64) -0,
							-   HiX: (float64) -0,
							-   LoY: (float64) -0,
							-   HiY: (float64) -0
							+   LoX: (float64) 2,
							+   HiX: (float64) 2,
							+   LoY: (float64) 2,
							+   HiY: (float64) 2
							   })
			Test:       	TestShortestLineString/MULTILINESTRING_to_MULTILINESTRING

--- FAIL: TestSegmentize/GEOMETRYCOLLECTION_(POINT_(40.0_10.0),_LINESTRING_(10.0_10.0,_20.0_20.0,_10.0_40.0),_POLYGON_((40.0_40.0,_20.0_45.0,_45.0_30.0,_40.0_40.0))),_maximum_segment_length:_10.000000 (0.00s)
	segmentize_test.go:128: 
			Error Trace:	segmentize_test.go:128
			Error:      	Not equal: 
							expected: geo.Geometry{spatialObject:geopb.SpatialObject{Type:2, EWKB:geopb.EWKB{0x1, 0x7, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x1, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x30, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x3a, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x2a, 0x40, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x40, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x40, 0x40, 0x56, 0x55, 0x55, 0x55, 0x55, 0xd5, 0x44, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x3a, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x45, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x46, 0x40, 0x56, 0x55, 0x55, 0x55, 0x55, 0x55, 0x3c, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x56, 0x55, 0x55, 0x55, 0x55, 0x55, 0x42, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x41, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x46, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x45, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x41, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40}, SRID:0, ShapeType:8, BoundingBox:(*geopb.BoundingBox)(0xc0005bc6a0)}}
							actual  : geo.Geometry{spatialObject:geopb.SpatialObject{Type:2, EWKB:geopb.EWKB{0x1, 0x7, 0x0, 0x0, 0x0, 0x3, 0x0, 0x0, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x1, 0x2, 0x0, 0x0, 0x0, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x30, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x3a, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x2a, 0x40, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x40, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x1, 0x3, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x40, 0x40, 0x56, 0x55, 0x55, 0x55, 0x55, 0xd5, 0x44, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x3a, 0x40, 0xab, 0xaa, 0xaa, 0xaa, 0xaa, 0xaa, 0x45, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x34, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x46, 0x40, 0x56, 0x55, 0x55, 0x55, 0x55, 0x55, 0x3c, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x55, 0x55, 0x55, 0x55, 0x55, 0x55, 0x42, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x41, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x46, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x3e, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x40, 0x45, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x80, 0x41, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x44, 0x40}, SRID:0, ShapeType:8, BoundingBox:(*geopb.BoundingBox)(0xc0005bc620)}}
							
							Diff:
							--- Expected
							+++ Actual
							@@ -18,3 +18,3 @@
								000000d0  00 80 46 40 56 55 55 55  55 55 3c 40 00 00 00 00  |..F@VUUUUU<@....|
							-   000000e0  00 00 44 40 56 55 55 55  55 55 42 40 00 00 00 00  |..D@VUUUUUB@....|
							+   000000e0  00 00 44 40 55 55 55 55  55 55 42 40 00 00 00 00  |..D@UUUUUUB@....|
								000000f0  00 80 41 40 00 00 00 00  00 80 46 40 00 00 00 00  |..A@......F@....|
			Test:       	TestSegmentize/GEOMETRYCOLLECTION_(POINT_(40.0_10.0),_LINESTRING_(10.0_10.0,_20.0_20.0,_10.0_40.0),_POLYGON_((40.0_40.0,_20.0_45.0,_45.0_30.0,_40.0_40.0))),_maximum_segment_length:_10.000000
```

**To Reproduce**

```
#!/bin/bash

CWD=`pwd`

# Install all dependencies
dnf -y --disableplugin=subscription-manager install \
        http://mirror.centos.org/centos/8/BaseOS/ppc64le/os/Packages/centos-gpg-keys-8-2.el8.noarch.rpm \
        http://mirror.centos.org/centos/8/BaseOS/ppc64le/os/Packages/centos-linux-repos-8-2.el8.noarch.rpm \
        https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm

yum install -y git cmake make gcc-c++ autoconf ncurses-devel.ppc64le wget.ppc64le openssl-devel.ppc64le diffutils procps-ng

cd $HOME

set -eu

# Install nodejs
NODE_VERSION=v12.18.2
DISTRO=linux-ppc64le
wget https://nodejs.org/dist/$NODE_VERSION/node-$NODE_VERSION-$DISTRO.tar.gz
tar -xzf node-$NODE_VERSION-$DISTRO.tar.gz
export PATH=$HOME/node-$NODE_VERSION-$DISTRO/bin:$PATH

npm install yarn --global

cd $HOME

# Setup go environment and install go
GOPATH=$HOME/go
COCKROACH_HOME=$GOPATH/src/github.com/cockroachdb
mkdir -p $COCKROACH_HOME
export GOPATH
curl -O https://dl.google.com/go/go1.13.5.linux-ppc64le.tar.gz
tar -C /usr/local -xzf go1.13.5.linux-ppc64le.tar.gz
rm -rf go1.13.5.linux-ppc64le.tar.gz
export PATH=$PATH:/usr/local/go/bin

# Clone cockroach and build
COCKROACH_VERSION=v20.2.17
cd $COCKROACH_HOME
git clone https://github.com/cockroachdb/cockroach.git
cd cockroach
git checkout $COCKROACH_VERSION
make buildoss

export GOMAXPROCS=4
make test PKG=./pkg/geo/geomfn TESTFLAGS='-v -count=1'
```

**Environment:**

CockroachDB [v20.2.17]
Architecture and OS: [ppc64le/RHEL/UBI 8.4]
Go: [1.13.5]
Node: [12.18.2]

Any pointers to resolve the failures would be of great help.

Epic CRDB-10447

Jira issue: CRDB-11050

**Comment by jtsiros** [comment] 2022-02-17 23:41
cc: @cockroachdb/dev-inf for triage

**Comment by prashantkhoje** [comment] 2022-06-14 11:21
The TestSegmentize/GEOMETRYCOLLECTION_ failure is fixed by:
https://github.com/cockroachdb/cockroach/pull/81894

**Comment by otan** [comment] 2022-08-15 11:00
marking as a duplicate of #72226

**Closed by otan** 2022-08-15 11:00 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-dev-inf
