### ISSUE TITLE
Can't access ui on docker container - SPDY error

### ISSUE THREAD

**Issue by eviekassela** [cockroachdb/cockroach#5164] opened 2016-03-11 15:28 UTC
I have created a single-node database with a docker container and exposed its port with this command:
`docker run -it -d -p 127.0.0.1:26257:26257 --name cockroach1 -h cockroach1 cockroachdb/cockroach shell`
After setting up the certificates for localhost and cockroach1, I start it with:
 root@cockroach1:/cockroach# ./cockroach start           
build:     alpha.v1-835-ge9f364b @ 2016/03/10 00:18:00 (go1.6)
admin:     https://cockroach1:26257
...

Everything seems ok according to the logs but when I try to access the ui in the browser in https://{{docker_ip}}:26257 or https://localhost:26257 I get first the warning about the self-signed certificate, I accept it and then I get an SPDY protocol error. What could be the problem?
If I run ./cockroach start --insecure and try to access the site http://localhost:26257 it works fine.

Thank you

**Comment by tamird** [comment] 2016-03-11 15:30
This is a dupe of #5020 or #5047. The issue should be fixed in a later revision.

**Closed by tamird** 2016-03-11 15:30 UTC
