### ISSUE TITLE
sql: implement pg_catalog.pg_opclass

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#27765] opened 2018-07-19 21:39 UTC
See https://www.postgresql.org/docs/10/static/catalog-pg-opclass.html for details.

This is needed for #27763.

To do this, we will require fleshing out some more pg_catalog tables:

* pg_catalog.pg_am needs to be populated
* pg_catalog.pg_authid needs to be implemented and populated
* pg_catalog.pg_opfamily needs to be implemented and populated

**Comment by jordanlewis** [comment] 2020-11-09 00:52
Duplicate of #48729.

**Closed by jordanlewis** 2020-11-09 00:52 UTC
Labels: A-sql-pgcatalog, A-sql-pgcompat, C-enhancement, good first issue
