### ISSUE TITLE
circleci: failed tests (13516): TestSSLEnforcement 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4721] opened 2016-02-29 18:51 UTC
The following test appears to have failed:

[#13516](https://circleci.com/gh/cockroachdb/cockroach/13516):

```
E160229 18:48:11.438006 server.go:2159  http: TLS handshake error from 127.0.0.1:38401: tls: first record does not look like a TLS handshake
E160229 18:48:11.528232 server.go:2159  http: TLS handshake error from 127.0.0.1:38403: tls: first record does not look like a TLS handshake
E160229 18:48:11.560087 server.go:2159  http: TLS handshake error from 127.0.0.1:38404: tls: first record does not look like a TLS handshake
E160229 18:48:11.603723 server.go:2159  http: TLS handshake error from 127.0.0.1:38406: tls: first record does not look like a TLS handshake
I160229 18:48:11.641698 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestSSLEnforcement (0.99s)
	authentication_test.go:148: [28]: expected success=true, got err=Post https://127.0.0.1:41673/sql/Execute: stream error: stream ID 13; STREAM_CLOSED
=== RUN   TestParseInitNodeAttributes
I160229 18:48:11.672581 server/context.go:141  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
I160229 18:48:11.673268 server/context.go:229  1 storage engine initialized
I160229 18:48:11.673365 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestParseInitNodeAttributes (0.00s)
=== RUN   TestParseJoinUsingAddrs
I160229 18:48:11.676516 server/context.go:141  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
I160229 18:48:11.677029 server/context.go:229  1 storage engine initialized
I160229 18:48:11.677171 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--
W160229 18:48:35.743342 ts/db.go:96  error writing time series data: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:620: node 1 stopped
I160229 18:48:35.745164 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (5.87s)
=== RUN   TestNewStoreSpec
--- PASS: TestNewStoreSpec (0.01s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	27.888s
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.10s)
=== RUN   TestRuntimeStatRecorder
I160229 18:48:23.505588 server/status/runtime.go:137  runtime stats: 5 goroutines, 4.96MiB active, 50000000.00cgo/sec, 1085140.00/497350.00 %(u/s)time, 361871.07 %gc (4x)
--- PASS: TestRuntimeStatRecorder (0.01s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	1.192s
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.02s)
=== RUN   TestSplitAndExpr

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-29 18:53
Duplicate of #4718

**Closed by bdarnell** 2016-02-29 18:53 UTC
Labels: test-failure
