### ISSUE TITLE
circleci: failed tests (14807): TestDockerJava 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5384] opened 2016-03-18 19:10 UTC
The following test appears to have failed:

[#14807](https://circleci.com/gh/cockroachdb/cockroach/14807):

```
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:386)
	at main.main(main.java:58)
I160318 19:09:09.106211 acceptance/cluster/localcluster.go:634  stopping
I160318 19:09:09.106420 acceptance/cluster/localcluster.go:532  event stream done, resetting...: net/http: request canceled
I160318 19:09:09.106438 acceptance/cluster/localcluster.go:555  events monitor exits
--- FAIL: TestDockerJava (19.95s)
	util_test.go:259: expected success: non-zero exit code: 1
=== RUN   TestDockerPHP
I160318 19:09:11.021582 acceptance/cluster/localcluster.go:274  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160318 19:09:11.021752 acceptance/cluster/docker.go:73  ImagePull cockroachdb/builder:20160305-182433 starting
..................
I160318 19:09:12.359763 acceptance/cluster/docker.go:89  ImagePull cockroachdb/builder:20160305-182433 complete
I160318 19:09:12.828115 acceptance/cluster/localcluster.go:566  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.058547019
I160318 19:09:12.930595 acceptance/cluster/localcluster.go:517  events monitor starts
I160318 19:09:13.198465 acceptance/cluster/localcluster.go:465  *** started roach0 ***
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:63: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-18 19:20
Duplicate of #5382.

**Closed by petermattis** 2016-03-18 19:20 UTC
Labels: Robot, test-failure
