### ISSUE TITLE
cli : add border to sql query results. 

### ISSUE THREAD

**Issue by rajputshubham** [cockroachdb/cockroach#31869] opened 2018-10-25 09:05 UTC
when a user runs a query, He expects conventional bordered query result. Though current system doesn't have any formatting.
![issue](https://user-images.githubusercontent.com/44107877/47488972-1f1a9d80-d863-11e8-8fcc-af90397d787b.png)

**Comment by knz** [comment] 2018-10-25 10:37
This is a duplicate of issue #30851. It is planned to make the formatting configurable.

Note:

- The absence of borders makes it possible to copy-paste the data into a spreadsheet program.

- Also it is the default formatting in the `psql` client, which has been reported by other users as a model to follow.

**Closed by knz** 2018-10-25 10:37 UTC
Labels: X-duplicate
