### ISSUE TITLE
pgwire: bad handling of error in multi-statement query

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#72769] opened 2021-11-15 18:46 UTC
With the patch below applied to master (c968f1f2bb376ec085b157d364df4efa4c31dc1c), you get the following:

```
make testshort PKG=./pkg/sql TESTS=TestPrimaryKeyChangeKVOps  TESTFLAGS="-v"
...
schema_changer_test.go:2894: pq: unexpected message 'C' in simple query execution
```

This kind of libpq error means that we're probably not playing nice at the pgwire level. I think we've seen the same in https://github.com/cockroachdb/cockroach/issues/54389 and couldn't repro.

The patch is the following. It is incorrect because it messes up something at the tracing level, but still I think it the error the test gets is unexpected.

```diff
diff --git a/pkg/sql/execinfra/processorsbase.go b/pkg/sql/execinfra/processorsbase.go
index 4acec2fcbe..c913b8af81 100644
--- a/pkg/sql/execinfra/processorsbase.go
+++ b/pkg/sql/execinfra/processorsbase.go
@@ -833,7 +833,8 @@ func (pb *ProcessorBase) AppendTrailingMeta(meta execinfrapb.ProducerMetadata) {
 // ProcessorSpan creates a child span for a processor (if we are doing any
 // tracing). The returned span needs to be finished using tracing.FinishSpan.
 func ProcessorSpan(ctx context.Context, name string) (context.Context, *tracing.Span) {
-       return tracing.ChildSpanRemote(ctx, name)
+       // !!! return tracing.ChildSpanRemote(ctx, name)
+       return tracing.ChildSpan(ctx, name)
 }
```

The test in question runs a multi-statement "simple query":
```
sqlDB.Query(`
	SET TRACING=on, kv, results;
	DELETE FROM t.test WHERE y = 2;
	SET TRACING=off;
	SELECT message FROM [SHOW KV TRACE FOR SESSION] WHERE
		message LIKE 'Del /Table/53/2%' ORDER BY message;`
 ```
 https://github.com/cockroachdb/cockroach/blob/782ae3e67552192ea5a8b7aee0a91f002264bdac/pkg/sql/schema_changer_test.go#L2887-L2895

The patch causes [`StopTracing()`](https://github.com/cockroachdb/cockroach/blob/c98800d0eabce7305c847c42512d80fea2b5c2c5/pkg/sql/exec_util.go#L2065) to return an error (a span is ingested twice), which in turn translates, I think, into the `set tracing=off` statement returning an error. The problem surely has to do with the fact that there's another query after the erroring one.

I've tried to repro more generally with multi-statement queries, but failed. I think the `set tracing=on/off` statements are somehow special (I think they might be handled specifically in the `connExecutor`).

Perhaps the ancient https://github.com/cockroachdb/cockroach/issues/4306 which did something about a similar issue might have clues.

Jira issue: CRDB-11275

**Comment by cucaroach** [comment] 2021-11-24 11:04
So what happens is the patch causes [this](https://github.com/cockroachdb/cockroach/blob/c0090fd04a4e5c619f4291b6371e8bb50600def4/pkg/sql/exec_util.go#L2386) error to occur but since its a "observer" statement (error occurs during 'SET TRACING = off;') we don't return the error we just stash it on the commandResult and it gets returned later [here](https://github.com/cockroachdb/cockroach/blob/4ef90c25dc9914e3e7254b18ae06e02fc9c0bc53/pkg/sql/pgwire/command_result.go#L121).    Anyways it seems like simpleQuery just isn't expecting to see more results after the 'E' error but in that case why does it keep going instead of returning?   My hot take is that if we encounter an error in the non-last statement of a multi-statement query we should stop processing the query and be 'done' (ie make sure the error is returned in an expected way) but I'm proselytizing about things I have zero experience with.   

The real error can be seen with this patch but that's probably not what we're after:

```
diff --git a/pkg/sql/schema_changer_test.go b/pkg/sql/schema_changer_test.go
index c7425d36f7..9bb56746ed 100644
--- a/pkg/sql/schema_changer_test.go
+++ b/pkg/sql/schema_changer_test.go
@@ -2885,11 +2885,14 @@ CREATE TABLE t.test (
  }
 
  // Test that we only insert the necessary k/v's.
- rows, err := sqlDB.Query(`
- SET TRACING=on,kv,results;
+ _, err := sqlDB.Exec(`SET TRACING=on,kv,results;
  INSERT INTO t.test VALUES (1, 2, 3, NULL, NULL, 6);
- SET TRACING=off;
- SELECT message FROM [SHOW KV TRACE FOR SESSION] WHERE
+ SET TRACING=off;`)
+ if err != nil {
+   t.Fatal(err)
+ }
+
+ rows, err := sqlDB.Query(`SELECT message FROM [SHOW KV TRACE FOR SESSION] WHERE
    message LIKE 'InitPut /Table/53/2%' ORDER BY message;`)
  if err != nil {
    t.Fatal(err)
```

Hot potato to SQL experience!

**Comment by rafiss** [comment] 2022-02-22 18:06
it's possible https://github.com/cockroachdb/cockroach/pull/76834 will help with this. gonna test it out

**Comment by rafiss** [comment] 2022-02-22 18:23
@andreimatei the interfaces have changed so the diff from the original issue report doesn't apply now. do you have a tip for a different way i can try to repro this?

**Comment by rafiss** [comment] 2022-03-16 19:33
I'll close this, but please reopen if you can provide another way to reproduce it.

**Closed by rafiss** 2022-03-16 19:33 UTC
Labels: C-bug, A-sql-pgwire, T-sql-experience, T-sql-queries
