### ISSUE TITLE
sentry: conn_executor.go:670: panic while executing 1 statements: SELECT _, _, ARRAY (SELECT _) FROM _: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#31999] opened 2018-10-30 09:34 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/747009458/

```
*log.safeError: conn_executor.go:670: panic while executing 1 statements: SELECT _, _, ARRAY (SELECT _) FROM _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 418, in func1
  File "runtime/asm_amd64.s", line 573, in call32
  File "runtime/panic.go", line 502, in gopanic
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/memo/typing.go", line 100, in FindAggregateOverload
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go", line 542, in buildGroupBy
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go", line 112, in buildRelational
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go", line 372, in buildProject
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/relational_builder.go", line 109, in buildRelational
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go", line 59, in build
  File "github.com/cockroachdb/cockroach/pkg/sql/opt/exec/execbuilder/builder.go", line 48, in Build
  File "github.com/cockroachdb/cockroach/pkg/sql/plan.go", line 479, in makeOptimizerPlan
  File "github.com/cockroachdb/cockroach/pkg/sql/planner.go", line 548, in optionallyUseOptimizer
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 766, in dispatchToExecutionEngine
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 403, in execStmtInOpenState
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 95, in execStmt
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 1143, in run
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 420, in ServeConn
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go", line 309, in func4
```

**Comment by knz** [comment] 2018-10-30 11:02
@rytaft can you have a look?

**Comment by rytaft** [comment] 2018-10-30 13:57
It looks like this query is trying to build an aggregate with child types for which there is no function overload:
https://github.com/cockroachdb/cockroach/blob/3e9a4e9bc5849729c17d686ae83f647024338fc0/pkg/sql/opt/memo/typing.go#L100

Could this be a case of us building an `array_agg` with a an unsupported type? cc @justinj

**Comment by justinj** [comment] 2018-10-30 14:07
Yeah, possibly, I'll take a look, thanks for letting me know!

**Comment by rytaft** [comment] 2018-10-30 14:16
I found a way to reproduce:
```
create table t (x string COLLATE en PRIMARY KEY);
select array(select x from t) from t;
```

**Comment by knz** [comment] 2018-12-19 13:52
@justinj I think this has been fixed right? I can't seem to repro any more.

**Comment by justinj** [comment] 2018-12-19 16:21
Yes, this should have been fixed by my change, thanks for the heads up!

**Closed by justinj** 2018-12-19 16:21 UTC
Labels: A-sql-planning, C-bug, O-sentry, S-2-temp-unavailability
