### ISSUE TITLE
Support for pgvector (or equivalent) in CockroachDB

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#121504] opened 2024-04-01 22:05 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-37291

**Comment by jordanlewis** [comment] 2024-05-17 01:06
Duplicate of #121432, which has more detail.

**Comment by yuzefovich** [comment] 2024-07-08 17:10
dup of #121432

**Closed by yuzefovich** 2024-07-08 17:10 UTC
Labels: C-enhancement, T-sql-queries
