### ISSUE TITLE
circleci: failed tests (13907): TestReplicateRogueRemovedNode 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4904] opened 2016-03-06 06:53 UTC
The following test appears to have failed:

[#13907](https://circleci.com/gh/cockroachdb/cockroach/13907):

```
E160306 06:52:26.432400 storage/client_test.go:737  engine 2: missing key "a"
I160306 06:52:27.085289 kv/txn_coord_sender.go:294  txn coordinator: 1.57 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 14.998s/25.978s/1m0.129s avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (4 samples)
I160306 06:52:27.434278 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I160306 06:52:27.434415 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I160306 06:52:27.434518 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (15.42s)
	testing.go:170: storage/client_raft_test.go:1317: condition failed to evaluate within 15s: storage/client_test.go:755: expected [16 0 5], got [16 0 0]
=== RUN   TestReplicateReAddAfterDown
I160306 06:52:27.505882 raft/raft.go:459  [group 1] 1 became follower at term 5
I160306 06:52:27.505948 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160306 06:52:27.506015 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160306 06:52:27.506046 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160306 06:52:27.506070 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
I160306 06:52:27.506102 raft/raft.go:500  [group 1] 1 became leader at term 6
I160306 06:52:27.506421 storage/replica.go:1684  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
I160306 06:52:27.507069 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1.000s
--
I160306 06:52:51.737080 stopper.go:273  draining; tasks left:
2      gossip/infostore.go:285
I160306 06:52:51.737116 stopper.go:273  draining; tasks left:
1      gossip/infostore.go:285
--- PASS: Example_rebalancing (0.15s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	55.487s
=== RUN   TestBatchBasics
I160306 06:52:21.040547 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I160306 06:52:21.045160 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I160306 06:52:21.047528 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-03-08 15:42
Duplicate of #4692

**Closed by bdarnell** 2016-03-08 15:42 UTC
Labels: test-failure
