### ISSUE TITLE
sql: panic in makeIndexConstraints

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18316] opened 2017-09-07 14:43 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/345117355/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 499, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/index_selection.go", line 567, in makeIndexConstraints
  File "github.com/cockroachdb/cockroach/pkg/sql/index_selection.go", line 472, in makeOrConstraints
  File "github.com/cockroachdb/cockroach/pkg/sql/index_selection.go", line 369, in analyzeExprs
...
(28 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

**Comment by cuongdo** [comment] 2017-09-07 14:44
@knz please triage. this has been happening pretty often.

**Comment by bdarnell** [comment] 2017-09-07 15:45
We have a customer log with this crash (version 1.0.5):

```
	panic: update transaction_event set send_id=null where (send_id is not null) and send_timestamp<$1: runtime error: index out of range

goroutine 407690 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42051a000, 0x7f876d74e718, 0xc42022c450)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x1901f60, 0xc4213be4b0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc421559200, 0x7f876d74e718, 0xc42167fdd0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x1901f60, 0xc4213be4b0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4204341bc, 0x5b)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:499 +0x131
panic(0x192e4a0, 0x274bee0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeIndexConstraints(0xc420ebe480, 0xc422d0b860, 0x2, 0x2, 0x1, 0x1, 0x11b808f, 0xc420706cc8, 0x278f460)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:567 +0x1889
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeOrConstraints(0xc420ebe480, 0xc422d0b840, 0x1, 0x1, 0xc42276d1b0, 0x11b8260)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:472 +0xc2
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).analyzeExprs(0xc420ebe480, 0xc422d0b840, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:369 +0x67
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc420706c80, 0x7f876d74e718, 0xc421b4d9e0, 0xc422770000, 0x0, 0x0, 0x7, 0xff00000007, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:168 +0x1261
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0x7f876d74e718, 0xc421b4d9e0, 0xc420706c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc422770000, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:298 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f876d74e718, 0xc421b4d9e0, 0xc420706c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x2794540, 0xc422770000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:240 +0x6d7
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0x7f876d74e718, 0xc421b4d9e0, 0xc420706c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420c86120, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:311 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f876d74e718, 0xc421b4d9e0, 0xc420706c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x27944c0, 0xc420c86120, 0x278f520, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:243 +0x3107
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f876d74e718, 0xc421b4d9e0, 0xc420706c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x2794840, 0xc42309ad80, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:63 +0xd54
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc420706c80, 0x7f876d74e718, 0xc421b4d9e0, 0x2794840, 0xc42309ad80, 0x2794840, 0xc42309ad80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:36 +0x93
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc420706c80, 0x7f876d74e718, 0xc421b4d9e0, 0x2794840, 0xc42309ad80, 0x2c383e8, 0x0, 0x0, 0x2794840, 0xc42309ad80, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:48 +0x10b
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc420706c80, 0x7f876d74e718, 0xc421b4d9e0, 0x278b860, 0xc421bc1540, 0x59b13d5c, 0x2b5e33e1, 0xc421c6a1a0, 0x9aada9)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:223 +0x155
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc42064ae00, 0x278b860, 0xc421bc1540, 0xc420706c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```

The `transaction_event` table definition is

```
CREATE TABLE transaction_event (
	id INT NOT NULL DEFAULT unique_rowid(),
	message BYTES NOT NULL,
	received INT NOT NULL,
	username STRING(255) NOT NULL,
	classname STRING(255) NOT NULL,
	send_id STRING(255) NULL,
	send_timestamp TIMESTAMP NULL,
	CONSTRAINT pk_transaction_event PRIMARY KEY (id ASC),
	FAMILY "primary" (id, message, received, username, classname, send_id, send_timestamp)
)
```

**Comment by vivekmenezes** [comment] 2017-09-07 16:54
```
exprLoop:
                for _, e := range andExprs {
                        if c, ok := e.(*parser.ComparisonExpr); ok {
                                var tupleMap []int

                                if ok, colIdx := getColVarIdx(c.Left); ok && v.desc.Columns[colIdx].ID != colID {
                                        // This expression refers to a column other than the one we're
                                        // looking for.
                                        continue
				}

```

the panic is happening on the line
```
 if ok, colIdx := getColVarIdx(c.Left); ok && v.desc.Columns[colIdx].ID != colID {
```

and it's likely caused by the value of colidx being incorrect.

**Comment by petermattis** [comment] 2017-09-07 18:13
Given the frequency of occurrence, I thought this would be reproducible using that table and query. It is not. 

PS All of the occurrences on sentry seem to be for the same user.

**Comment by bdarnell** [comment] 2017-09-07 18:37
And that user's logs are showing a lot of "time out trying to submit crash report" messages, so the true error rate is higher than what we're seeing in sentry (the logs I have are from the same cluster as the one in sentry).

**Comment by petermattis** [comment] 2017-09-07 18:48
Seems like a crash on that line is impossible, but clearly it is happening. For the table and query listed above, we're doing `getColVarIdx("send_id")` which should be returning `true, 5` (at least it is when I test it locally). This works correctly on both master and 1.0.5. 

Cc @RaduBerinde who is most familiar with the `IndexedVar` code. Any ideas how we could be returning an invalid column index?

**Comment by knz** [comment] 2017-09-07 19:09
This is a query with a placeholder. I recall we don't handle indexed vars very healthily when the same query is executed multiple times. @jordanlewis has fixed another bug in that area in the last quarter. Looking at this myself, the next thing I'm going to try is a prepare/execute/execute and see what happens.

**Comment by knz** [comment] 2017-09-07 19:09
I'd really want this user to use a custom build so we can check the structure of the IndexedVar at that point. How much willingness is there to try a custom build?

**Comment by jordanlewis** [comment] 2017-09-07 19:25
@bdarnell is that the full stack trace? It would be useful to see a little more if it's available to confirm that this is happening during execution of a pre-prepared statement and not anything else.

**Comment by bdarnell** [comment] 2017-09-07 19:29
@jordanlewis here's the full stack:

```
	panic: update transaction_event set send_id=null where (send_id is not null) and send_timestamp<$1: runtime error: index out of range

goroutine 2426 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420090a00, 0x7f17c0fdc1a8, 0xc420466cc0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x1901f60, 0xc42029a980)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420652000, 0x7f17c0fdc1a8, 0xc421584330)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x1901f60, 0xc42029a980)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements.func1(0xc4203ea0dc, 0x5b)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:499 +0x131
panic(0x192e4a0, 0x274bee0)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeIndexConstraints(0xc4215fe3c0, 0xc420280280, 0x2, 0x2, 0x1, 0x1, 0x11b808f, 0xc421594cc8, 0x278f460)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:567 +0x1889
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeOrConstraints(0xc4215fe3c0, 0xc420280260, 0x1, 0x1, 0xc4215f91b0, 0x11b8260)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:472 +0xc2
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).analyzeExprs(0xc4215fe3c0, 0xc420280260, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:369 +0x67
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc421594c80, 0x7f17c0fdc1a8, 0xc421585ec0, 0xc4215fc000, 0x0, 0x0, 0x7, 0xff00000007, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:168 +0x1261
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0x7f17c0fdc1a8, 0xc421585ec0, 0xc421594c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc4215fc000, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:298 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f17c0fdc1a8, 0xc421585ec0, 0xc421594c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x2794540, 0xc4215fc000, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:240 +0x6d7
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0x7f17c0fdc1a8, 0xc421585ec0, 0xc421594c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc4215c3c20, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:311 +0xd7
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f17c0fdc1a8, 0xc421585ec0, 0xc421594c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x27944c0, 0xc4215c3c20, 0x278f520, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:243 +0x3107
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x7f17c0fdc1a8, 0xc421585ec0, 0xc421594c80, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x2794840, 0xc420340900, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:63 +0xd54
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc421594c80, 0x7f17c0fdc1a8, 0xc421585ec0, 0x2794840, 0xc420340900, 0x2794840, 0xc420340900, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:36 +0x93
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc421594c80, 0x7f17c0fdc1a8, 0xc421585ec0, 0x2794840, 0xc420340900, 0x2c383e8, 0x0, 0x0, 0x2794840, 0xc420340900, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:48 +0x10b
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc421594c80, 0x7f17c0fdc1a8, 0xc421585ec0, 0x278b860, 0xc4215c1640, 0x59b13d78, 0x12ad34d9, 0xc42158c1a0, 0x9aada9)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:223 +0x155
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4204f7340, 0x278b860, 0xc4215c1640, 0xc421594c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1580 +0x118
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4204f7340, 0xc420b63200, 0x278b860, 0xc4215c1640, 0xc42029a300, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1340 +0x463
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc4204f7340, 0xc420b63200, 0xc42029a510, 0x1, 0x1, 0xc42029a300, 0x0, 0x0, 0x0, 0xc42158cb80, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:955 +0x818
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4204f7340, 0xc420b63200, 0xc42029a510, 0x1, 0x1, 0xc42029a300, 0x1, 0xc42029a528, 0x1c00, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:863 +0xd1
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func1(0x7f17c0fdc1a8, 0xc421585ec0, 0xc420287e40, 0xc42029a528, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:695 +0x1df
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420287e40, 0x7f17c0fdc1a8, 0xc421585ec0, 0xc420010000, 0xc4215cf030, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:641 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4204f7340, 0xc420b63200, 0xc4203ea0dc, 0x5b, 0xc42029a300, 0x0, 0x0, 0x0, 0x0, 0x1995100)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:717 +0x66d
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4204f7340, 0xc420b63200, 0xc4203ea0dc, 0x5b, 0xc42029a300, 0x0, 0x0, 0x0, 0xc4203ea100)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:505 +0x11b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420652000, 0xc4203ea0dc, 0x5b, 0xc42029a300, 0x2c383e8, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:836 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc420652000, 0xc420652028, 0xc42157cb40, 0xc420652045)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:823 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420652000, 0x7f17c0fdc1a8, 0xc421584330, 0xc4202bfaf0, 0x5400, 0xc420220f50, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:455 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc420220e00, 0x7f17c0fdc3c8, 0xc42156ce80, 0x2793300, 0xc4201f5f40, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x2793300, 0xc4201f5f40)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:615 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc420090a00, 0x7f17c0fdc1a8, 0xc420466cc0, 0xc4203a4028, 0x2793300, 0xc4201f5f40, 0xc420af5890)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
```

**Comment by richardwu** [comment] 2017-11-21 07:33
So my intuition and previous experience with https://github.com/cockroachdb/cockroach/pull/19752 (which was later in https://github.com/cockroachdb/cockroach/pull/19701 and regression tested here https://github.com/cockroachdb/cockroach/pull/20063) led me to believe that this could be happening because of some edge case with schema mutations.

I was able to reproduce this locally on commit be60cc5a4 (I didn't realize the binary on this computer was that outdated, but I assume this still is the case on master).

## Intuition

Note that `send_id` is the 2nd last column. What if we had a really big table, dropped 2+ columns such that two columns lose their read capabilities, then tried to execute a query with `send_id`?

I believe `IndexedVar` is initialized based on `planColumns(n.plan)` whose underlying plan node would be a `scanNode`. If we map `planColumns` back to the `scanNode`, we see that it references `resultColumns` [which has a 1-1 mapping to `cols` that may contain columns in schema changes!](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/scan.go#L51-L54). Maybe I'm missing a few links, but I believe this is case.

Now that the index for `send_id` is initialized to `5`, proceeding to drop 2 columns will revoke the read capabilities of 2 columns in our table descriptor, which shrinks `desc.Columns` down to a length 5 with max index `4` et voila, we've got ourselves an out of bounds error.

## Reproduction

The key is to let `DROP COLUMNS` run long enough to interactive execute the query with read capabilities revoked. 

```sql
# Create a table where we can drop 2 columns (not in the primary key of course)
# The types of our columns do not matter but preferably we have relative large
# rows so our DROP COLUMNS take a while
CREATE TABLE bar (
  id INT PRIMARY KEY,
  data1 STRING DEFAULT 'cockroachdbisthebest',
  data2 STRING DEFAULT 'wholetthecockroachesout',
  send_id INT,           
  send_timestamp INT
);

# We insert a ton of rows O(100k) to allow us time to run our query.
# I ran 5 of the following queries (changing the first generate_series params 
# to avoid conflict primary keys).
INSERT INTO bar (id, send_id, send_timestamp) SELECT a, b, c FROM
  generate_series(1,100000) AS a(a), 
  generate_serires(1,1) AS b(b),
  generate_serires(1,1) AS c(c);
```

Now open up 4 SQL consoles (technically we only need 3 - 2 for dropping and 1 for the query - but for some reason it only worked once I dropped 3 columns) and have the following two queries buffered in your input
```
ALTER TABLE bar DROP COLUMN data1;

ALTER TABLE bar DROP COLUMN data2;

# This isn't necessary under the intuition but for some reason it only
# worked once I started dropping this column shortly after data1 
# was dropped.
ALTER TABLE bar DROP COLUMN send_timestamp;

# Noop query
UPDATE bar SET send_id = NULL WHERE (send_id IS NOT NULL) AND (send_timestamp < 0);
```
I initially ran the first two drop queries then rapidly executed the `UPDATE` query many times. I'm guessing there was some delay with descriptors/read capability revocation, but shortly before the `DROP COLUMN data1` completed with no success reproducing the panic, I ran `DROP COLUMN send_timestamp` for the heck of it and the query successful produced the panic thereafter.

## Trace

Again this was ran with a binary with commit be60cc5a4ccfb6a597a47f5eb9d0a88a0e1b1289 so the line numbers will need to be matched up with that commit.

```
*
* ERROR: [client=[::1]:53592,user=root,n1] a SQL panic has occurred!
*
*
* ERROR: [n1] a panic has occurred!
*
panic while executing "UPDATE bar SET send_id = NULL WHERE (send_id IS NOT NULL) AND (send_timestamp < 0);": runtime error: index out of range

goroutine 2350 [running]:
runtime/debug.Stack(0x6332c40, 0xc4206561e0, 0xc4200b2000)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x6332c40, 0xc4206561e0, 0xc4200b2000, 0x557a060, 0xc420c91ce0, 0x1)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:147 +0x2fe
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc42070a5a0, 0x6332c40, 0xc4206561e0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0xf3
panic(0x557a060, 0xc420c91ce0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420426900, 0x6332c40, 0xc4211760f0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:423 +0xa1
panic(0x557a060, 0xc420c91ce0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*Session).maybeRecover(0xc420638000, 0x573ed60, 0x9, 0xc42178d5f7, 0x53)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/session.go:1346 +0x262
panic(0x554be40, 0x67f8fb0)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeIndexConstraints(0xc421553300, 0xc420c91c80, 0x2, 0x2, 0x1, 0x1, 0x4d80202, 0xc420638260, 0x6339f20)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:565 +0x1d6f
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).makeOrConstraints(0xc421553300, 0xc420c91c60, 0x1, 0x1, 0xc4220ed3e0, 0x4d803bf)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:470 +0xdf
github.com/cockroachdb/cockroach/pkg/sql.(*indexInfo).analyzeExprs(0xc421553300, 0xc420c91c60, 0x1, 0x1)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:367 +0x67
github.com/cockroachdb/cockroach/pkg/sql.(*planner).selectIndex(0xc420638208, 0x6332b80, 0xc421552d40, 0xc420dec580, 0x0, 0x5683e00, 0x0, 0x6339bc0, 0xc422659fb0, 0x6333d00)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/index_selection.go:166 +0x115d
github.com/cockroachdb/cockroach/pkg/sql.expandScanNode(0x6332b80, 0xc421552d40, 0xc420638208, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc420dec580, 0x1, 0x6339bc0, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:297 +0x10a
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x6332b80, 0xc421552d40, 0xc420638208, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x63335c0, 0xc420dec580, 0x0, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:214 +0x166b
github.com/cockroachdb/cockroach/pkg/sql.expandRenderNode(0x6332b80, 0xc421552d40, 0xc420638208, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0xc421cab320, 0xc420dc1e50, 0xc422659dd0, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:310 +0xda
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x6332b80, 0xc421552d40, 0xc420638208, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x6333580, 0xc421cab320, 0x6333580, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:217 +0x13c7
github.com/cockroachdb/cockroach/pkg/sql.doExpandPlan(0x6332b80, 0xc421552d40, 0xc420638208, 0x7fffffffffffffff, 0x0, 0x0, 0x0, 0x6333900, 0xc4221bc000, 0x0, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:60 +0x899
github.com/cockroachdb/cockroach/pkg/sql.(*planner).expandPlan(0xc420638208, 0x6332b80, 0xc421552d40, 0x6333900, 0xc4221bc000, 0x6333900, 0xc4221bc000, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/expand_plan.go:33 +0x93
github.com/cockroachdb/cockroach/pkg/sql.(*planner).optimizePlan(0xc420638208, 0x6332b80, 0xc421552d40, 0x6333900, 0xc4221bc000, 0x6866d80, 0x0, 0x0, 0x6333900, 0xc4221bc000, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/optimize.go:46 +0x10b
github.com/cockroachdb/cockroach/pkg/sql.(*planner).makePlan(0xc420638208, 0x6332b80, 0xc421552d40, 0x6335dc0, 0xc421552ac0, 0x0, 0x0, 0x0, 0x14f9079bed88c654, 0x1, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:202 +0x166
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc4200a0fc0, 0x6335dc0, 0xc421552ac0, 0x0, 0x0, 0x0, 0x14f9079bed88c654, 0x1, 0xc421237740, 0xc420638208, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1886 +0x11a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc4200a0fc0, 0xc420638000, 0x6335dc0, 0xc421552ac0, 0x0, 0x0, 0x0, 0x14f9079bed88c654, 0x1, 0xc421237740, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1601 +0x656
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execSingleStatement(0xc4200a0fc0, 0xc420638000, 0x6335dc0, 0xc421552ac0, 0x0, 0x0, 0x0, 0x14f9079bed88c654, 0x1, 0xc421237740, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1172 +0x6a5
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc4200a0fc0, 0xc420638000, 0xc421552b80, 0x1, 0x1, 0x0, 0x1, 0x1, 0x0, 0x6337be0, ...)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1046 +0x3e5
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed.func1(0x6332b80, 0xc421552d40, 0xc4225b6000, 0xc420f58fd8, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:838 +0x276
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4225b6000, 0x6332b80, 0xc421552d40, 0x101, 0xc4204e8460, 0xed1a5c59c, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:722 +0x1a6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execParsed(0xc4200a0fc0, 0xc420638000, 0xc421552b80, 0x1, 0x1, 0x0, 0x0, 0xc420568c00, 0x54)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:861 +0x2de
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc4200a0fc0, 0xc420638000, 0xc42178d5f7, 0x53, 0x0, 0x0, 0x53, 0xc42178d5f7)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:748 +0x502
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc4200a0fc0, 0xc420638000, 0xc42178d5f7, 0x53, 0x0, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:629 +0x1bd
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc420426900, 0xc420426928, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:612 +0x1d0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420426900, 0x6332c40, 0xc4211760f0, 0xc420bce5c0, 0x5400, 0xc42093e368, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:503 +0x8ae
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42093e200, 0x6332b80, 0xc420331200, 0x633e840, 0xc420798960, 0x0, 0x0)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x929
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x633e840, 0xc420798960)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:746 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc42070a5a0, 0x6332c40, 0xc4206561e0, 0xc42000e060, 0x633e840, 0xc420798960, 0xc420e98a20)
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:140 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/rwu1997/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:137 +0x263
```

Here're the data directories/logs of the 3 nodes (Cockroach Labs access only) https://drive.google.com/a/cockroachlabs.com/file/d/1HeZMBY4LPEnAwL0ip_jCph1YNhGePv9i/view?usp=sharing.

**Comment by knz** [comment] 2017-11-21 07:54
Thanks Cuong for reproducing the issue!

As discussed in #19752 I too am very uncomfortable as to having UPDATE pass publicAndNonPublicColumns as scanVisibility to the scanNode and therefore work on mutated columns. IT doesn't feel right to me.

**Comment by vivekmenezes** [comment] 2017-11-21 16:02
assigning to myself to see what I can do about this. Thanks!

**Closed** 2018-01-11 17:19 UTC
Labels: high priority
