### ISSUE TITLE
sql: query using UDF does not use correct secondary index

### ISSUE THREAD

**Issue by ecwall** [cockroachdb/cockroach#104218] opened 2023-06-01 17:43 UTC
Cockroach is incorrectly doing a full table scan on the `test_table@test_table_pkey` PK index instead of doing a lookup in the `test_table@test_table_flat_name_idx` secondary index when a query contains a UDF.

Repro steps:
```
DROP TABLE IF EXISTS test_table;

CREATE TABLE test_table (
    item_id     TEXT      PRIMARY KEY,
    flat_name   TEXT      NOT NULL
);

CREATE INDEX ON test_table (flat_name);

CREATE OR REPLACE FUNCTION
    flatten_name(input TEXT)
RETURNS TEXT IMMUTABLE LANGUAGE SQL AS $$
    SELECT LOWER(input)
$$;

INSERT INTO test_table (item_id, flat_name)
SELECT gen_random_uuid(), lower(substr(md5(random()::text), 0, 4)) FROM generate_series(1, 10000);

EXPLAIN ANALYZE
SELECT item_id
FROM test_table
   WHERE flat_name = flatten_name('3BD2');
```

Postgres result:
![image](https://github.com/cockroachdb/cockroach/assets/8524448/9758adb6-aeb6-4055-a9a8-8b6678987808)

CRDB result:
![image](https://github.com/cockroachdb/cockroach/assets/8524448/504a8bc5-1703-467d-a78b-465a54c65431)

CRDB result if `flatten_name` is replaced with the `lower` builtin:
![image](https://github.com/cockroachdb/cockroach/assets/8524448/8ed35ca9-ed10-43a5-b989-656e8c5c5ed3)

Jira issue: CRDB-28415

**Comment by rharding6373** [comment] 2023-06-09 20:37
I tried to reproduce this at head and got the following plan, which does have the filter pushed into the index scan:

```
EXPLAIN ANALYZE                                                                                                                      
  SELECT item_id                                                                                                                       
  FROM test_table                                                                                                                      
  WHERE flat_name = flatten_name('3BD2');     
...
  • scan
    nodes: n1
    regions: us-east1
    actual row count: 0
    KV time: 136µs
    KV contention time: 0µs
    KV rows decoded: 0
    KV bytes read: 0 B
    KV gRPC calls: 1
    estimated max memory allocated: 20 KiB
    sql cpu time: 12µs
    missing stats
    table: test_table@test_table_flat_name_idx
    spans: [/'3bd2' - /'3bd2']
```

@ecwall do you know what sha you were at approximately? If so I can try to find the PR that resolved this, but otherwise I will simply close this issue since it appears we do the right thing now.

**Comment by ecwall** [comment] 2023-06-26 19:44
@rharding6373 it was originally reported here https://cockroachdb.slack.com/archives/CP4D9LD5F/p1685384542893279, but I am not sure what version it was.

It looks like it was again reported here https://cockroachdb.slack.com/archives/CP4D9LD5F/p1687808167294689

**Comment by ecwall** [comment] 2023-06-26 20:01
I tested in 23.1.4:
```
demo@127.0.0.1:26257/movr> EXPLAIN ANALYZE                                                                                                                                                                    
                        -> SELECT item_id                                                                                                                                                                     
                        -> FROM test_table                                                                                                                                                                    
                        ->    WHERE flat_name = flatten_name('3BD2');                                                                                                                                         
                        info
-----------------------------------------------------
  planning time: 1ms
  execution time: 7ms
  distribution: full
  vectorized: true
  rows read from KV: 10,000 (693 KiB, 1 gRPC calls)
  cumulative time spent in KV: 6ms
  maximum memory usage: 1.1 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 2ms
  regions: us-east1

  • root
  │
  ├── • filter
  │   │ nodes: n1
  │   │ regions: us-east1
  │   │ actual row count: 0
  │   │ sql cpu time: 184µs
  │   │ filter: flat_name = @S1
  │   │
  │   └── • scan
  │         nodes: n1
  │         regions: us-east1
  │         actual row count: 10,000
  │         KV time: 6ms
  │         KV contention time: 0µs
  │         KV rows read: 10,000
  │         KV bytes read: 693 KiB
  │         KV gRPC calls: 1
  │         estimated max memory allocated: 840 KiB
  │         sql cpu time: 2ms
  │         missing stats
  │         table: test_table@test_table_pkey
  │         spans: FULL SCAN
  │
  └── • subquery
      │ id: @S1
      │ original sql: <unknown>
      │ exec mode: one row
      │
      └── • values
            nodes: n1
            regions: us-east1
            actual row count: 1
            sql cpu time: 10µs
            size: 1 column, 1 row
(46 rows)
```

and 22.2.10:
```
demo@127.0.0.1:26257/movr> EXPLAIN ANALYZE                                                                                                                                                                                               SELECT item_id                                                                                                                                                                                                                           FROM test_table                                                                                                                                                                                                                             WHERE flat_name = flatten_name('3BD2');
                        info
-----------------------------------------------------
  planning time: 3ms
  execution time: 2.4s
  distribution: local
  vectorized: true
  rows read from KV: 10,000 (693 KiB, 1 gRPC calls)
  cumulative time spent in KV: 9ms
  maximum memory usage: 870 KiB
  network usage: 0 B (0 messages)
  regions: us-east1

  • filter
  │ nodes: n1
  │ regions: us-east1
  │ actual row count: 0
  │ filter: flat_name = flatten_name('3BD2')
  │
  └── • scan
        nodes: n1
        regions: us-east1
        actual row count: 10,000
        KV time: 9ms
        KV contention time: 0µs
        KV rows read: 10,000
        KV bytes read: 693 KiB
        KV gRPC calls: 1
        estimated max memory allocated: 840 KiB
        missing stats
        table: test_table@test_table_pkey
        spans: FULL SCAN
(29 rows)
```

**Comment by rharding6373** [comment] 2023-06-26 23:21
Still can't repro the original example at head. I bisected the fix to https://github.com/cockroachdb/cockroach/pull/100881, which hoists uncorrelated subqueries and allows us to do further optimizations (like pushing the filter into the scan). This was backported and should be in both 23.1 and 22.2 releases (as of [23.1.2](https://github.com/cockroachdb/cockroach/compare/v23.1.1...v23.1.2) and [22.2.9](https://github.com/cockroachdb/cockroach/compare/v22.2.8...v22.2.9), respectively).

This change was protected with a flag, though, so in 23.1.2+ you should set the following session var and then the filter is pushed down as expected:
```
SET optimizer_hoist_uncorrelated_equality_subqueries=true;
demo@127.0.0.1:26257/movr> EXPLAIN ANALYZE                                                                                       
                        -> SELECT item_id                                                                                        
                        -> FROM test_table                                                                                       
                        ->    WHERE flat_name = flatten_name('3BD2');                                                            
                                      info
--------------------------------------------------------------------------------
  planning time: 2ms
  execution time: 360µs
  distribution: local
  vectorized: true
  cumulative time spent in KV: 192µs
  maximum memory usage: 20 KiB
  network usage: 0 B (0 messages)
  sql cpu time: 11µs
  regions: us-east1

  • scan
    nodes: n1
    regions: us-east1
    actual row count: 0
    KV time: 192µs
    KV contention time: 0µs
    KV rows read: 0
    KV bytes read: 0 B
    KV gRPC calls: 1
    estimated max memory allocated: 20 KiB
    sql cpu time: 11µs
    estimated row count: 3 (0.03% of the table; stats collected 5 seconds ago)
    table: test_table@test_table_flat_name_idx
    spans: [/'3bd2' - /'3bd2']
```

This won't help in 22.2, though. A big change implemented in 23.1 that isn't in 22.2 is inlining UDFs as subqueries: https://github.com/cockroachdb/cockroach/pull/92955, and the above change won't help. This might be too big a change in behavior to backport safely, and could be seen as performance improvements to UDFs. @mgartner Do you have an opinion on whether we can backport inlining UDFs to 22.2?

**Comment by rharding6373** [comment] 2023-06-26 23:23
I tried the second example at head but the full scan is still present, so it will require more investigation. Repro steps from the thread are:

```
CREATE TABLE if NOT EXISTS jobs (
    id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    pipeline_id int NOT NULL,
    project_id int NOT NULL,
    job_id bigint NOT NULL,
    name varchar NOT NULL,
    created_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    ref varchar NOT NULL,
    runner varchar,
    stage varchar NOT NULL,
    status varchar NOT NULL,
    failure_reason varchar,
    web_url varchar NOT NULL,
    downstream_pipeline_id int,
    UNIQUE(pipeline_id, project_id, job_id)
);

CREATE INDEX IF NOT EXISTS jobs_created_at_idx ON jobs (created_at);
CREATE INDEX IF NOT EXISTS jobs_started_at_idx ON jobs (started_at);

CREATE OR REPLACE FUNCTION TO_TIMESTAMP(dt VARCHAR, fmt VARCHAR) RETURNS TIMESTAMP AS $BODY$ SELECT strptime(dt, '%Y-%m-%d %H:%M:%S') $BODY$ LANGUAGE SQL IMMUTABLE;

EXPLAIN SELECT count(*)
FROM public.jobs
WHERE created_at >= TO_TIMESTAMP('2023-06-26 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US');
```

**Comment by rharding6373** [comment] 2023-06-26 23:37
Oh the example in https://github.com/cockroachdb/cockroach/issues/104218#issuecomment-1608456290 isn't affected because it's not an equality subquery. If the query is modified to 

```
EXPLAIN SELECT count(*)
FROM public.jobs
WHERE created_at = TO_TIMESTAMP('2023-06-26 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US');
```

then the filter is pushed down. We should consider hoisting subqueries in other kinds of expressions besides equality.

**Comment by levsha** [comment] 2023-07-18 21:44
Looks like PostgreSQL executes immutable UDF even before query plan and then just uses the value in the query plan. And this behavior is in line with it's documentations https://www.postgresql.org/docs/current/sql-createfunction.html that says
```
If this option is given, any call of the function with all-constant arguments can be immediately replaced with the function value.
```
Can't CockroachDB do the same? It is what it does with native functions isn't it? I believe that behavior with immutable UDFs should be the same as with native fuctions.

**Comment by mgartner** [comment] 2023-07-18 22:05
@levsha Yes you are correct, and CockroachDB already behaves as you describe.

I believe the problem from the most immediate example above is that we're missing a normalization rule to convert an uncorrelated, single-column ValuesExpr subquery into just a value:

```
SELECT count(*)
FROM public.jobs
WHERE created_at >= foo('2023-06-26 00:00:00.000000', 'YYYY-MM-DD HH24:MI:SS.US');

scalar-group-by
 ├── columns: count:22!null
 ├── cardinality: [1 - 1]
 ├── stable
 ├── key: ()
 ├── fd: ()-->(22)
 ├── select
 │    ├── columns: created_at:6!null
 │    ├── stable
 │    ├── scan jobs@jobs_created_at_idx
 │    │    └── columns: created_at:6!null
 │    └── filters
 │         └── ge [outer=(6), stable, subquery, constraints=(/6: (/NULL - ])]
 │              ├── created_at:6
 │              └── subquery
 │                   └── values
 │                        ├── columns: column21:21!null
 │                        ├── cardinality: [1 - 1]
 │                        ├── key: ()
 │                        ├── fd: ()-->(21)
 │                        └── ('2023-06-26 00:00:00',)
 └── aggregations
      └── count-rows [as=count_rows:22]
```

I'll work on this rule now.

**Closed** 2023-07-21 16:56 UTC
Labels: C-enhancement, T-sql-queries, A-sql-udf
