### ISSUE TITLE
changefeedccl: TestChangeFeedsTimestamps barfs on txn restart

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#29276] opened 2018-08-29 17:08 UTC
```
changefeed_test.go:188: error scanning '&{<nil> 0xc421372000}': pq: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=0a06ad43 key=/Table/53/1/1/0 rw=true pri=0.00725207 iso=SERIALIZABLE stat=PENDING epo=0 ts=1535560400.695807677,1 orig=1535560400.695068560,0 max=1535560400.695068560,0 wto=false rop=false seq=3
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=869750&buildTypeId=Cockroach_UnitTests

**Comment by danhhz** [comment] 2018-08-29 17:32
Duplicate of https://github.com/cockroachdb/cockroach/issues/29241, which has a fix out for review if you want to review it https://github.com/cockroachdb/cockroach/pull/29269

**Closed by danhhz** 2018-08-29 17:32 UTC
Labels: A-cdc, C-test-failure
