### ISSUE TITLE
Sentry: panic.go:884: runtime error: slice bounds out of range [:-8]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113288] opened 2023-10-30 14:37 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4586582149/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4586582149/?referrer=webhooks_plugin)

Panic Message:

```
panic.go:884: runtime error: slice bounds out of range [:-8]
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.goPanicSliceAcap
  | 	GOROOT/src/runtime/panic.go:139
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go:416
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSplice
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go:390
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).addInternal
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go:175
  | github.com/cockroachdb/pebble/internal/arenaskl.(*Inserter).Add
  | 	github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go:98
  | github.com/cockroachdb/pebble.(*memTable).apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/mem_table.go:217
  | github.com/cockroachdb/pebble.(*DB).commitApply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:831
  | github.com/cockroachdb/pebble.(*commitPipeline).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go:317
  | github.com/cockroachdb/pebble.(*DB).applyInternal
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:808
  | github.com/cockroachdb/pebble.(*DB).Apply
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go:746
  | github.com/cockroachdb/pebble.(*Batch).Commit
  | 	github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go:1109
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit
  | 	github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:549
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).ApplyToStateMachine
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go:562
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:290
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:251
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:1005
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:718
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:646
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:395
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:302
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (2) runtime error: slice bounds out of range [:-8]
Error types: (1) *withstack.withStack (2) runtime.boundsError
-- report composition:
runtime.boundsError
panic.go:884: *withstack.withStack (top exception)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L301-L303)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go#L394-L396)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go#L645-L647)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L717-L719](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L717-L719)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1004-L1006](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go#L1004-L1006)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L289-L291](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/apply/task.go#L289-L291)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go#L561-L563](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go#L561-L563)
[https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_batch.go#L548-L550](https://github.com/cockroachdb/cockroach/blob/810d4f27a7f02b9cc2750cab654ed1c62ac3e75a/pkg/storage/pebble_batch.go#L548-L550)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1108-L1110](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go#L1108-L1110)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L745-L747](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L745-L747)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L807-L809](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L807-L809)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L316-L318](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go#L316-L318)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L830-L832](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go#L830-L832)
[github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/mem_table.go#L216-L218](github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/mem_table.go#L216-L218)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L97-L99](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L97-L99)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L174-L176](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L174-L176)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L389-L391](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L389-L391)
[github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L415-L417](github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go#L415-L417)
[GOROOT/src/runtime/panic.go#L138-L140](GOROOT/src/runtime/panic.go#L138-L140)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftScheduler).Start.func2 at line 302
pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go in pkg/kv/kvserver.(*raftSchedulerShard).worker at line 395
pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go in pkg/kv/kvserver.(*Store).processReady at line 646
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReady at line 718
pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go in pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked at line 1005
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries at line 251
pkg/kv/kvserver/apply/task.go in pkg/kv/kvserver/apply.(*Task).applyOneBatch at line 290
pkg/kv/kvserver/pkg/kv/kvserver/replica_app_batch.go in pkg/kv/kvserver.(*replicaAppBatch).ApplyToStateMachine at line 562
pkg/storage/pebble_batch.go in pkg/storage.(*pebbleBatch).Commit at line 549
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/batch.go in github.com/cockroachdb/pebble.(*Batch).Commit at line 1109
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).Apply at line 746
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).applyInternal at line 808
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/commit.go in github.com/cockroachdb/pebble.(*commitPipeline).Commit at line 317
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/db.go in github.com/cockroachdb/pebble.(*DB).commitApply at line 831
github.com/cockroachdb/pebble/external/com_github_cockroachdb_pebble/mem_table.go in github.com/cockroachdb/pebble.(*memTable).apply at line 217
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Inserter).Add at line 98
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).addInternal at line 175
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSplice at line 390
github.com/cockroachdb/pebble/internal/arenaskl/external/com_github_cockroachdb_pebble/internal/arenaskl/skl.go in github.com/cockroachdb/pebble/internal/arenaskl.(*Skiplist).findSpliceForLevel at line 416
GOROOT/src/runtime/panic.go in runtime.goPanicSliceAcap at line 139
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.2 |
| Go Version | go1.19.4 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.2 |
| Cockroach SHA | 810d4f27a7f02b9cc2750cab654ed1c62ac3e75a |
| # of CPUs | 24 |
| # of Goroutines | 490 |

Jira issue: CRDB-32851

**Comment by erikgrinaker** [comment] 2023-10-30 15:36
Dupe of #113289.

**Closed by erikgrinaker** 2023-10-30 15:36 UTC
Labels: C-bug, O-sentry
