### ISSUE TITLE
odd log

### ISSUE THREAD

**Issue by damiencarol** [cockroachdb/cockroach#5667] opened 2016-03-29 14:58 UTC
2016-03-29 16:50:59	ERROR	[replicate] 3 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 16:40:59	ERROR	[replicate] 3 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 16:24:49	ERROR	[replicate] 5 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 16:14:49	ERROR	[replicate] 5 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 16:04:49	ERROR	[replicate] 5 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 15:54:49	ERROR	[replicate] 5 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 15:44:49	ERROR	[replicate] 4 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 15:34:49	ERROR	[replicate] 4 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 15:24:49	ERROR	[replicate] 3 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511
2016-03-29 15:14:49	ERROR	[replicate] 2 replicas failing with "0 of 2 stores with an attribute matching []"	storage/queue.go:511

**Comment by tamird** [comment] 2016-03-29 15:03
@damiencarol can you give a bit more detail on your setup? How many nodes are you running? how were they started? what kind of load are you applying?

**Comment by damiencarol** [comment] 2016-03-29 15:22
2 nodes.
Launching on 1 machine 
with:
    ./cockroach start --insecure &
and
./cockroach start --insecure --store=cockroach-data2 --port=26258 --http-port=8081 --join=localhost:26257 &

**Comment by damiencarol** [comment] 2016-03-29 15:46
No particular load. Only exemple queries from GitHub.

**Comment by tamird** [comment] 2016-03-29 15:50
This "error" is expected. The system is telling you that there are two nodes that want to up-replicate a range, but that neither of the two nodes is suitable as an up-replication target; this is because both nodes are already replicas of that range.

The root cause of this error condition is that the default configuration is set to replicate each range to three nodes, and you're only running two. Adding a third node will silence the error, but it is also "safe" to ignore if you're intentionally running two nodes. Note that running 2 nodes is not recommended because a loss of either node will result in the cluster being down (since quorum is not possible).

I'm going to close this for now, but let us know if you have further questions.

**Closed by tamird** 2016-03-29 15:50 UTC

**Comment by damiencarol** [comment] 2016-03-29 16:25
@tamird ok, thanks for your time.
It is not clear that a minimum of 3 nodes is required.

**Comment by tamird** [comment] 2016-03-29 16:27
Again, it's not required - only recommended. Note that these "errors" do
not prevent the cluster from running.

**Comment by damiencarol** [comment] 2016-03-29 16:37
yep

**Comment by tschottdorf** [comment] 2016-03-29 18:36
The error message could be more descriptive, though. We've repeatedly
improved it, but I would argue not enough.
