### ISSUE TITLE
tests: fix emails for daily tests

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7742] opened 2016-07-11 15:10 UTC
As far as I know, the daily tests aren't emailing out any more. At least, I don't see emails going to the `daily` Google Group. Let's get that working again.

**Comment by tamird** [comment] 2016-07-11 15:33
Dupe of https://github.com/cockroachdb/cockroach-prod/issues/98

**Closed** 2016-07-13 22:10 UTC
