### ISSUE TITLE
ui: mouse-over sometimes shows different numbers from graphs

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18075] opened 2017-08-31 15:11 UTC
![image](https://user-images.githubusercontent.com/5768024/29930654-fa95184e-8e3c-11e7-82a2-ff82a690baf9.png)

This is on our PM cluster composed of 4 nodes. I'm running a rolling restart to upgrade the cluster. I shut down 165.227.80.203 and the replicas should have gone down to zero. Mousing over, they indeed did, but the graph doesn't who it. I think this might have to do with https://github.com/cockroachdb/cockroach/issues/17552.

**Comment by couchand** [comment] 2017-12-11 18:26
This appears to be a duplicate of #12856.

**Closed by couchand** 2017-12-11 18:26 UTC
