### ISSUE TITLE
stress: failed test in cockroach/server/status/status.test: TestMetricsRecorder

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5222] opened 2016-03-14 09:43 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f587240217828432af6a84192503586355af19ab

Stress build found a failed test:

```
=== RUN   TestMetricsRecorder
--- FAIL: TestMetricsRecorder (1.03s)
	recorder_test.go:287: recorder did not yield expected time series collection; diff:
		 [[6].Datapoints[0].Value: 10 != 0 [7].Datapoints[0].Value: 10 != 0 [8].Datapoints[0].Value: 10 != 0 [9].Datapoints[0].Value: 10 != 0 [10].Datapoints[0].Value: 10 != 0 [11].Datapoints[0].Value: 10 != 0 [12].Datapoints[0].Value: 10 != 0 [13].Datapoints[0].Value: 10 != 0 [48].Datapoints[0].Value: 10 != 0 [49].Datapoints[0].Value: 10 != 0 [50].Datapoints[0].Value: 10 != 0 [51].Datapoints[0].Value: 10 != 0 [52].Datapoints[0].Value: 10 != 0 [53].Datapoints[0].Value: 10 != 0 [54].Datapoints[0].Value: 10 != 0 [55].Datapoints[0].Value: 10 != 0 [96].Datapoints[0].Value: 10 != 0 [97].Datapoints[0].Value: 10 != 0 [98].Datapoints[0].Value: 10 != 0 [99].Datapoints[0].Value: 10 != 0 [100].Datapoints[0].Value: 10 != 0 [101].Datapoints[0].Value: 10 != 0 [102].Datapoints[0].Value: 10 != 0 [103].Datapoints[0].Value: 10 != 0 [104].Datapoints[0].Value: 10 != 0 [105].Datapoints[0].Value: 10 != 0 [106].Datapoints[0].Value: 10 != 0 [107].Datapoints[0].Value: 10 != 0 [108].Datapoints[0].Value: 10 != 0 [109].Datapoints[0].Value: 10 != 0 [110].Datapoints[0].Value: 10 != 0 [111].Datapoints[0].Value: 10 != 0]
```

Run Details:

```
581 runs so far, 0 failures, over 5s
1157 runs so far, 0 failures, over 10s
1730 runs so far, 0 failures, over 15s
2314 runs so far, 0 failures, over 20s
2900 runs so far, 0 failures, over 25s
3474 runs so far, 0 failures, over 30s
4047 runs so far, 0 failures, over 35s
4627 runs so far, 0 failures, over 40s
5206 runs so far, 0 failures, over 45s
5781 runs so far, 0 failures, over 50s
6355 runs so far, 0 failures, over 55s
6936 runs so far, 0 failures, over 1m0s
7509 runs so far, 0 failures, over 1m5s
8090 runs so far, 0 failures, over 1m10s
8667 runs so far, 0 failures, over 1m15s
9250 runs so far, 0 failures, over 1m20s
9826 runs so far, 0 failures, over 1m25s
10395 runs so far, 0 failures, over 1m30s
10966 runs so far, 0 failures, over 1m35s
11548 runs so far, 0 failures, over 1m40s
12121 runs so far, 0 failures, over 1m45s
12695 runs so far, 0 failures, over 1m50s
13267 runs so far, 0 failures, over 1m55s
13839 runs so far, 0 failures, over 2m0s
14416 runs so far, 0 failures, over 2m5s
14996 runs so far, 0 failures, over 2m10s
15567 runs so far, 0 failures, over 2m15s
16146 runs so far, 0 failures, over 2m20s
16713 runs so far, 0 failures, over 2m25s
17288 runs so far, 0 failures, over 2m30s
17855 runs so far, 0 failures, over 2m35s
18430 runs so far, 0 failures, over 2m40s
19006 runs so far, 0 failures, over 2m45s
19574 runs so far, 0 failures, over 2m50s
20151 runs so far, 0 failures, over 2m55s
20718 runs so far, 0 failures, over 3m0s
20813 runs completed, 1 failures, over 3m2s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 18:05
Duplicate of #4855.

**Closed by petermattis** 2016-03-14 18:05 UTC
Labels: Robot, test-failure
