### ISSUE TITLE
sql: panic during TRUNCATE

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15765] opened 2017-05-08 14:41 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/267426066/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
    panic(r)
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 499, in func1
    panic(fmt.Errorf("%s: %v", stmts, r))
  File "github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go", line 656, in deleteAllRowsFast
    panic(fmt.Sprintf("%d results returned", l))
  File "github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go", line 631, in deleteAllRows
    return td.deleteAllRowsFast(ctx, resume, limit)
  File "github.com/cockroachdb/cockroach/pkg/sql/truncate.go", line 118, in truncateTable
    newResume, err := td.deleteAllRows(ctx, resume, chunkSize)
...
(21 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

cc @dt @vivekmenezes @danhhz

**Comment by cuongdo** [comment] 2017-07-14 19:54
@vivekmenezes please assign

**Comment by vivekmenezes** [comment] 2017-07-17 18:27
leaving this assigned to me because I've been mucking around here. Not yet sure what the problem is.

**Comment by vivekmenezes** [comment] 2017-08-10 19:12
This panic can occur if TRUNCATE is called in the middle of a column backfill during an ADD/DROP COLUMN schema change. We can fix this easily but there is also another issue here that we implement TRUNCATE BY a DROP followed by an ADD TABLE. The ADD TABLE should not be a blind copy of the table descriptor. All the outstanding mutations must be resolved.

**Comment by vivekmenezes** [comment] 2017-08-29 15:01
I'm looking at fixing this issue this week

**Comment by vivekmenezes** [comment] 2017-09-19 01:25
I was struggling to figure out why this panic was happening until I saw
```
newResume, err := td.deleteAllRows(ctx, resume, chunkSize)
```
in the panic report. newResume has never been a variable in this file

```git whatchanged -p  pkg/sql/truncate.go  | grep newResume```

**Closed by vivekmenezes** 2017-09-19 01:25 UTC
Labels: 1.0.1, bug

**Comment by jordanlewis** [comment] 2017-09-19 13:59
Hah, very true.
