### ISSUE TITLE
kvserver: rolling restart leads to de facto unavailable due to lagging split triggers

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#80537] opened 2022-04-26 10:35 UTC
**Describe the problem**

@aliher1911 has PR #80286 which reliably results in long periods of unavailability, on 21.2.8. This does not (or not readily) reproduce on master.
We don't understand what fixed it.

**To Reproduce**

Run the roachtest in the linked PR on 21.2.8. Look at the UI and watch the SQL latencies spike to >10s and the throughput drop to zero.
The test performs rolling restarts of a node at a time.

**Expected behavior**

No outage since rolling restarts don't lose quorum.

We didn't get to fully investigate this because we got preempted with higher priority work. However, we did see that there is de facto unavailability in the cluster because ranges that are 3x-replicated are losing one follower (as a result of getting drained gracefully). This leaves two voters, but one voter is uninitialized since it is waiting to be initialized through a split trigger (this is the only path in which a voter is uninitialized, since uupreplication always goes through an initialized learner). The split trigger comes from the left hand side of the split, i.e. the pre-split range. Looking at that range, we find it in the same state, etc.

We need to understand what delays the split triggers. The workload is write heavy (which is what triggers the splits in the first place), so it could "simply" be result of interactions with the quota pool and the rolling restarts that result in lots of data needing to be applied on each of the links of the split chain. It could be that the rolling restart can result in dormant ranges that will not apply the sorely needed split trigger until woken up by the replicate queue.

Anecdotally we see that the outage persists many minutes, and resolves over time at a steady pace ("slow ranges" dropping down).

We should understand this repro and see how much of the findings still apply on `master`.

**Additional data / screenshots**

**Environment:**

**Additional context**

Jira issue: CRDB-15356

**Comment by aliher1911** [comment] 2022-04-26 10:43
Couple of notes on tests:
- test was running with 350 QPS and behaviour was seen on either 5 or 6 node cluster
- QPS 350 origin: 5 node cluster runs at 420QPS when no limit is set so this gives it some headroom
- when running at 50 QPS rolling restart runs without hiccups, but it could be down to no splits happening for a long time until ranges become sufficiently full.

**Comment by aliher1911** [comment] 2022-04-26 10:44
Support issue that triggered the investigation: https://github.com/cockroachlabs/support/issues/1476

**Comment by erikgrinaker** [comment] 2023-10-25 09:01
Since this has apparently been fixed in all supported versions ("does not reproduce on master" as of April 2022), and we haven't gotten around to investigating this yet, I'm closing this out.

**Closed by erikgrinaker** 2023-10-25 09:01 UTC
Labels: C-investigation, O-support, T-kv-replication
