### ISSUE TITLE
Sentry: func_desc.go:331: function × (1611): depended-on-by relation × (746) does not have a column with ID 19
(1)
Wraps: (2)
Wraps: (3) keys: [sql.schema.validation_errors.read.backward_references....

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#117932] opened 2024-01-18 18:24 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4889399590/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4889399590/?referrer=webhooks_plugin)

Panic Message:

```
func_desc.go:331: function × (1611): depended-on-by relation × (746) does not have a column with ID 19
(1)
Wraps: (2)
Wraps: (3) keys: [sql.schema.validation_errors.read.backward_references.function]
Wraps: (4) keys: [sql.schema.validation_errors.read.backward_references.function]
Wraps: (5) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:264
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:186
  | [...repeated from below...]
Wraps: (6) function × (1611)
Wraps: (7) assertion failure
Wraps: (8) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/funcdesc.(*immutable).validateInboundTableRef
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/funcdesc/func_desc.go:331
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/funcdesc.(*immutable).ValidateBackReferences
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/funcdesc/func_desc.go:282
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:114
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:109
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).finalizeDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:666
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:220
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByIDGetter.Desc
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:48
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByIDGetter.Function
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func247.2.1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2599
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/schemadesc.(*immutable).ForEachFunctionSignature
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/schemadesc/schema_desc.go:541
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func247.2.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2598
  | github.com/cockroachdb/cockroach/pkg/sql.forEachSchema.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2306
  | github.com/cockroachdb/cockroach/pkg/sql.forEachSchema
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2314
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func247.2
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2597
  | github.com/cockroachdb/cockroach/pkg/sql.forEachDatabaseDesc
  | 	github.com/cockroachdb/cockroach/pkg/sql/information_schema.go:2367
  | github.com/cockroachdb/cockroach/pkg/sql.glob..func247
  | 	github.com/cockroachdb/cockroach/pkg/sql/pg_catalog.go:2595
  | github.com/cockroachdb/cockroach/pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_schema.go:678
  | github.com/cockroachdb/cockroach/pkg/sql.setupGenerator.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/virtual_table.go:127
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (9) depended-on-by relation × (746) does not have a column with ID 19
Error types: (1) *colexecerror.notInternalError (2) *colexecerror.notInternalError (3) *telemetrykeys.withTelemetry (4) *telemetrykeys.withTelemetry (5) *withstack.withStack (6) *errutil.withPrefix (7) *assert.withAssertionFailure (8) *withstack.withStack (9) *errutil.leafError
-- report composition:
*errutil.leafError: depended-on-by relation × (746) does not have a column with ID 19
func_desc.go:331: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: function × (1611)
validate.go:264: *withstack.withStack (1)
*telemetrykeys.withTelemetry: sql.schema.validation_errors.read.backward_references.function
*telemetrykeys.withTelemetry: sql.schema.validation_errors.read.backward_references.function
*colexecerror.notInternalError
*colexecerror.notInternalError
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_schema.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_schema.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2594-L2596](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2594-L2596)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2366-L2368](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2366-L2368)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2596-L2598](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2596-L2598)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2313-L2315](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2313-L2315)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2305-L2307](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2305-L2307)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2597-L2599](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2597-L2599)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/schemadesc/schema_desc.go#L540-L542](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/schemadesc/schema_desc.go#L540-L542)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2598-L2600](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2598-L2600)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L47-L49](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L47-L49)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L665-L667](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L665-L667)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L263-L265](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L263-L265)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/util/stop/stopper.go#L469-L471)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_table.go#L126-L128](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_table.go#L126-L128)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_schema.go#L677-L679](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/virtual_schema.go#L677-L679)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2594-L2596](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2594-L2596)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2366-L2368](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2366-L2368)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2596-L2598](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2596-L2598)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2313-L2315](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2313-L2315)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2305-L2307](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/information_schema.go#L2305-L2307)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2597-L2599](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2597-L2599)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/schemadesc/schema_desc.go#L540-L542](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/schemadesc/schema_desc.go#L540-L542)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2598-L2600](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/pg_catalog.go#L2598-L2600)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L47-L49](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/getters.go#L47-L49)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L219-L221](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L219-L221)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L665-L667](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/descriptor.go#L665-L667)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L108-L110](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L108-L110)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L113-L115](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/internal/validate/validate.go#L113-L115)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L281-L283](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L281-L283)
[https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L330-L332](https://github.com/cockroachdb/cockroach/blob/8d065df26e25a762a1abbbf2b1e475456b341a00/pkg/sql/catalog/funcdesc/func_desc.go#L330-L332)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 678
pkg/sql/pg_catalog.go in pkg/sql.glob..func247 at line 2595
pkg/sql/information_schema.go in pkg/sql.forEachDatabaseDesc at line 2367
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2 at line 2597
pkg/sql/information_schema.go in pkg/sql.forEachSchema at line 2314
pkg/sql/information_schema.go in pkg/sql.forEachSchema.func1 at line 2306
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2.1 at line 2598
pkg/sql/catalog/schemadesc/schema_desc.go in pkg/sql/catalog/schemadesc.(*immutable).ForEachFunctionSignature at line 541
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2.1.1 at line 2599
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Function at line 142
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Desc at line 48
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 666
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 109
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 114
pkg/sql/catalog/funcdesc/func_desc.go in pkg/sql/catalog/funcdesc.(*immutable).ValidateBackReferences at line 282
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 186
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 264
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 470
pkg/sql/virtual_table.go in pkg/sql.setupGenerator.func3 at line 127
pkg/sql/virtual_schema.go in pkg/sql.(*virtualDefEntry).getPlanInfo.func1.1 at line 678
pkg/sql/pg_catalog.go in pkg/sql.glob..func247 at line 2595
pkg/sql/information_schema.go in pkg/sql.forEachDatabaseDesc at line 2367
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2 at line 2597
pkg/sql/information_schema.go in pkg/sql.forEachSchema at line 2314
pkg/sql/information_schema.go in pkg/sql.forEachSchema.func1 at line 2306
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2.1 at line 2598
pkg/sql/catalog/schemadesc/schema_desc.go in pkg/sql/catalog/schemadesc.(*immutable).ForEachFunctionSignature at line 541
pkg/sql/pg_catalog.go in pkg/sql.glob..func247.2.1.1 at line 2599
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Function at line 142
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByIDGetter.Desc at line 48
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 220
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).finalizeDescriptors at line 666
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 109
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func3 at line 114
pkg/sql/catalog/funcdesc/func_desc.go in pkg/sql/catalog/funcdesc.(*immutable).ValidateBackReferences at line 282
pkg/sql/catalog/funcdesc/func_desc.go in pkg/sql/catalog/funcdesc.(*immutable).validateInboundTableRef at line 331
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.13 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.13 |
| Cockroach SHA | 8d065df26e25a762a1abbbf2b1e475456b341a00 |
| # of CPUs | 32 |
| # of Goroutines | 335 |

Jira issue: CRDB-35421

**Comment by michae2** [comment] 2024-01-18 19:24
Dupe of (and same cluster as) https://github.com/cockroachdb/cockroach/issues/117930

**Closed by michae2** 2024-01-18 19:24 UTC
Labels: C-bug, O-sentry
