### ISSUE TITLE
sql: make InternalExecutor have the same descs.Collection as the parent

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#69495] opened 2021-08-27 20:27 UTC
**Is your feature request related to a problem? Please describe.**
The internal executor uses a different descriptor `Collection` than the parent `conn_executor`. We've seen this cause performance problems since some builtins are implemented using the internal executor. If the builtin is called once per each output row in a query, then the table descriptors need to be re-fetched for each invocation of the internal executor. 

@ajwerner suggests that _not_ using the same Collection might be a correctness problem. https://github.com/cockroachdb/cockroach/issues/58356#issuecomment-898751692

**Describe the solution you'd like**
It would be nice if the internal executor could use the same Collection as the conn_executor it's used from.

**Describe alternatives you've considered**
Implement builtins without using the internal executor.

**Additional context**
This caused severe performance problems in https://github.com/cockroachdb/cockroach/issues/57924 and https://github.com/cockroachdb/cockroach/issues/65551. We still have a backlog item for addressing other similar issues (https://github.com/cockroachdb/cockroach/issues/66173)

This was discussed in Slack: https://cockroachlabs.slack.com/archives/C0168LW5THS/p1611947857055600

Jira issue: CRDB-9622

Epic CRDB-14492

**Comment by ajwerner** [comment] 2021-09-14 17:37
At its core, I think the problem here is that the internal executor abstraction is sitting at the wrong layer. It's this free-floating thing that is sort of associated with a session and sort of not. We should bind the internal executor much more closely to the session and connection. It should not take a transaction but rather should be initialized with one. 

We'll still need to be careful with concurrency and transaction usage, but that's not new. This feels like a relatively important thing to do sooner rather than later.

**Comment by RichardJCai** [comment] 2021-10-11 19:35
> > This is only with regards to the InternalExecutor used for builtins (aka on EvalContext) right?
> > I think my PR here might fix it. #71246
> 
> How does this fix it? The internal executor hanging off of the `ExecConfig` is no better.

Nvm just realized we still init a new conn_executor at https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/internal.go#L182 which is where the Collections is created.

We could make it so InternalExecutor overrides could take Collections as a short term solution. Although I don't think having to always override to use the IE is a good idea which is what's going on in #71246 to use the IE for any builtins.

**Comment by ajwerner** [comment] 2021-10-11 20:32
>Although I don't think having to always override to use the IE is a good idea which is what's going on in #71246 to use the IE for any builtins.

I agree. I think we should increase the coupling between the internal executor and the conn executor in the common case. See https://github.com/cockroachdb/cockroach/pull/71246#issuecomment-940420184.

**Comment by rafiss** [comment] 2021-11-04 22:11
I think this is affecting activerecord too https://github.com/cockroachdb/activerecord-cockroachdb-adapter/issues/234

**Comment by otan** [comment] 2021-11-24 03:24
I gave this a go (this was intended to be a quick and dirty to see if passing the same descCollection through is enough): https://github.com/cockroachdb/cockroach/pull/73100

But end up with this when running [this query](https://gist.github.com/otan/498fc5fef15f6147be5ae1f429ca146f) - any ideas?:

```
panic: interface conversion: catalog.NameEntry is *lease.descriptorVersionState, not *descs.uncommittedDescriptor

goroutine 3447 [running]:
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).getByName(0xc00132e8c0, 0x0, 0x0, {0xc0039c2076, 0x8})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:219 +0x17b
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getByName(0xc00132e888, {0x9bbcb70, 0xc002334000}, 0xc0047be9a0, {0x0, 0x0}, {0x0, 0x0}, {0xc0039c2076, 0x9}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:182 +0x219
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDatabaseByName(0x8, {0x9bbcb70, 0xc002334000}, 0x9bbcb70, {0xc0039c2076, 0x9}, {0x0, 0x0, 0x0, 0x0, ...})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:63 +0x85
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableDatabaseByName(...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:45
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByNameIgnoringRequiredAndType(0xc00132e888, {0x9bbcb70, 0xc002334000}, 0x0, {0xc0039c2076, 0x9}, {0x86be9da, 0xd}, {0x86be9e8, 0x13}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:157 +0x149
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByName(0x8, {0x9bbcb70, 0xc002334000}, 0x171464d8, {0xc0039c2076, 0x10}, {0x86be9da, 0x10}, {0x86be9e8, 0x13}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:64 +0x1b2
github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetObjectDesc(0x0, {0x9bbcb70, 0xc002334000}, 0x40e9e9e, {0xc0039c2076, 0xc0010dc99b}, {0x86be9da, 0x0}, {0x86be9e8, 0x13}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:39 +0x9f
github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupObject(0x0, {0x9bbcb70, 0xc002334000}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 0x0, ...}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:190 +0x439
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExisting({0x9bbcb70, 0xc002334000}, 0xc004062040, {0x1718a2c0, 0xc00132ec28}, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:404 +0x143
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject({0x9bbcb70, 0xc002334000}, {0x9c40c00, 0xc00132ec28}, 0xc004062040, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:193 +0x173
github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingTableObject({0x9bbcb70, 0xc002334000}, {0x9c40c00, 0xc00132ec28}, 0xc00132f438, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:121 +0x15d
github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveDataSource(0xc00132f420, {0x9bbcb70, 0xc002334000}, {0x0, 0x0}, 0xc0015af258)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:207 +0x20f
github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies(0xc004653c20, {0x9bbcb70, 0xc002334000}, {0x9d26100, 0xc00132f420})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:293 +0xf7
github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale(0xc004653c20, {0x9bbcb70, 0xc002334000}, 0xc00132ee98, {0x9d26100, 0xc00132f420})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:322 +0x493
github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer(0xc00132ec28, {0x9bbcb70, 0xc002334000})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:100 +0x8af
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared(0xc00132ed90, {0x9bbcb70, 0xc002334000}, 0xc0015d01f8, {0xc0015d01f8, 0x3, 0xc0015af608}, 0xc00132ec28)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:287 +0x22c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func1({0x9bbcb70, 0xc002334000}, 0x23)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:220 +0x40a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare(0xc00132e600, {0x9bbcb70, 0xc002334000}, {{{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, 0x2}, {0xc00185eb40, ...}, ...}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:226 +0x2cd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt(0xc00132e600, {0x9bbcb70, 0xc002334000}, {0x0, 0x0}, {{{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, ...}, ...}, ...)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:111 +0x110
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare(0xc00132e600, {0x9bbcb70, 0xc002334000}, {{0x0, 0x0}, {{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, ...}, ...})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:53 +0x23b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00132e600, {0x9bbcac8, 0xc003f61f40})
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1840 +0x11a6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00132e600, {0x9bd8b38, 0xc003f5ef50}, 0xc002642fd0, {0x467fbd8, 0xc0004a0000, 0x0}, 0xc001950000)
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1672 +0x285
github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:213 +0x8d
created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:212 +0x5d4
```

**Comment by rafiss** [comment] 2021-11-24 03:44
Curious if @RichardJCai has an idea? He did something similar in https://github.com/cockroachdb/cockroach/pull/71246

**Comment by RichardJCai** [comment] 2021-11-24 19:13
> I gave this a go (this was intended to be a quick and dirty to see if passing the same descCollection through is enough): #73100
> 
> But end up with this when running [this query](https://gist.github.com/otan/498fc5fef15f6147be5ae1f429ca146f) - any ideas?:
> 
> ```
> panic: interface conversion: catalog.NameEntry is *lease.descriptorVersionState, not *descs.uncommittedDescriptor
> 
> goroutine 3447 [running]:
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*uncommittedDescriptors).getByName(0xc00132e8c0, 0x0, 0x0, {0xc0039c2076, 0x8})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/uncommitted_descriptors.go:219 +0x17b
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getByName(0xc00132e888, {0x9bbcb70, 0xc002334000}, 0xc0047be9a0, {0x0, 0x0}, {0x0, 0x0}, {0xc0039c2076, 0x9}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:182 +0x219
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDatabaseByName(0x8, {0x9bbcb70, 0xc002334000}, 0x9bbcb70, {0xc0039c2076, 0x9}, {0x0, 0x0, 0x0, 0x0, ...})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:63 +0x85
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableDatabaseByName(...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/database.go:45
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByNameIgnoringRequiredAndType(0xc00132e888, {0x9bbcb70, 0xc002334000}, 0x0, {0xc0039c2076, 0x9}, {0x86be9da, 0xd}, {0x86be9e8, 0x13}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:157 +0x149
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getObjectByName(0x8, {0x9bbcb70, 0xc002334000}, 0x171464d8, {0xc0039c2076, 0x10}, {0x86be9da, 0x10}, {0x86be9e8, 0x13}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:64 +0x1b2
> github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetObjectDesc(0x0, {0x9bbcb70, 0xc002334000}, 0x40e9e9e, {0xc0039c2076, 0xc0010dc99b}, {0x86be9da, 0x0}, {0x86be9e8, 0x13}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/object.go:39 +0x9f
> github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupObject(0x0, {0x9bbcb70, 0xc002334000}, {{0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 0x0, ...}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/resolver.go:190 +0x439
> github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExisting({0x9bbcb70, 0xc002334000}, 0xc004062040, {0x1718a2c0, 0xc00132ec28}, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:404 +0x143
> github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingObject({0x9bbcb70, 0xc002334000}, {0x9c40c00, 0xc00132ec28}, 0xc004062040, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:193 +0x173
> github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver.ResolveExistingTableObject({0x9bbcb70, 0xc002334000}, {0x9c40c00, 0xc00132ec28}, 0xc00132f438, {{0x1, 0x0, 0x0, 0x0, 0x0, ...}, ...})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/resolver/resolver.go:121 +0x15d
> github.com/cockroachdb/cockroach/pkg/sql.(*optCatalog).ResolveDataSource(0xc00132f420, {0x9bbcb70, 0xc002334000}, {0x0, 0x0}, 0xc0015af258)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt_catalog.go:207 +0x20f
> github.com/cockroachdb/cockroach/pkg/sql/opt.(*Metadata).CheckDependencies(0xc004653c20, {0x9bbcb70, 0xc002334000}, {0x9d26100, 0xc00132f420})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/metadata.go:293 +0xf7
> github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).IsStale(0xc004653c20, {0x9bbcb70, 0xc002334000}, 0xc00132ee98, {0x9d26100, 0xc00132f420})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:322 +0x493
> github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepareUsingOptimizer(0xc00132ec28, {0x9bbcb70, 0xc002334000})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:100 +0x8af
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).populatePrepared(0xc00132ed90, {0x9bbcb70, 0xc002334000}, 0xc0015d01f8, {0xc0015d01f8, 0x3, 0xc0015af608}, 0xc00132ec28)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:287 +0x22c
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare.func1({0x9bbcb70, 0xc002334000}, 0x23)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:220 +0x40a
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).prepare(0xc00132e600, {0x9bbcb70, 0xc002334000}, {{{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, 0x2}, {0xc00185eb40, ...}, ...}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:226 +0x2cd
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt(0xc00132e600, {0x9bbcb70, 0xc002334000}, {0x0, 0x0}, {{{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, ...}, ...}, ...)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:111 +0x110
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare(0xc00132e600, {0x9bbcb70, 0xc002334000}, {{0x0, 0x0}, {{0x9bebb78, 0xc00141f680}, {0x86be98c, 0x104}, 0x3, ...}, ...})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:53 +0x23b
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00132e600, {0x9bbcac8, 0xc003f61f40})
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1840 +0x11a6
> github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00132e600, {0x9bd8b38, 0xc003f5ef50}, 0xc002642fd0, {0x467fbd8, 0xc0004a0000, 0x0}, 0xc001950000)
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1672 +0x285
> github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx.func1()
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:213 +0x8d
> created by github.com/cockroachdb/cockroach/pkg/sql.(*InternalExecutor).initConnEx
> 	/Users/otan/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:212 +0x5d4
> ```

I think I actually had a working method to pass the descCollections through in an earlier version of #71246, I don't recall running into any of those errors. Once #71246 is merged I can add back that code (trying to limit the scope of that refactor).

**Comment by ajwerner** [comment] 2021-12-08 20:35
> Once #71246 is merged I can add back that code (trying to limit the scope of that refactor).

@RichardJCai has the time come?

**Comment by RichardJCai** [comment] 2021-12-08 21:16
> > Once #71246 is merged I can add back that code (trying to limit the scope of that refactor).
> 
> @RichardJCai has the time come?

Pretty busy as of recent, I have another refactor in the works that I think I can easily tag this desc.Collections work (injecting desc.Collections) as part of. https://github.com/cockroachdb/cockroach/pull/73293

Will probably be a flex friday thing though.

**Closed** 2022-08-12 06:02 UTC
Labels: C-enhancement, C-performance, A-schema-descriptors, T-sql-experience, A-tools-prisma, A-tools-activerecord, A-tools-django, A-tools-hasura
