### ISSUE TITLE
cdc: files sent to cloudstorage sink split at 2.8mb with parquet format 

### ISSUE THREAD

**Issue by biradarganesh25** [cockroachdb/cockroach#93547] opened 2022-12-13 20:29 UTC
**Describe the problem**

If changefeeds are created with parquet format and cloudstorage sink is used, files that get sent to the sink are split at 2.8mb instead of the specified file size, which is 16mb. 

**To Reproduce**

1. Setup roachprod cluster with default config.
2. Load tpcc data
3. Start changefeed with parquet format and use gcloud storage as sink (which is what I used to verify). The default file size is 16mb, which is what should be the file size that appear in the cloudstorage sink.
4. See that the files in the sink are all 2.8mb.

Jira issue: CRDB-22391

Epic CRDB-15071

**Comment by amruss** [comment] 2022-12-21 18:28
Suggestion: upping the max memory default to 1GB again

**Comment by miretskiy** [comment] 2023-01-09 14:43
Closing as working as intended.

**Closed by miretskiy** 2023-01-09 14:43 UTC
Labels: C-bug, A-cdc
