### ISSUE TITLE
sql: optimize query plan generation with results of sub-queries

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7042] opened 2016-06-03 23:14 UTC
(requested by @RaduBerinde in #6994)

Prior to #6735 sub-queries were ran and substituted by their result in the `Expr` syntax tree prior/during initialization of `selectNode`. In particular the result of the sub-query was known prior to index selection, and the resulting value could be used to optimize range lookups.

Since #6735 the execution of sub-queries is always delayed until `planNode.Start()`; meanwhile index selection still occurs in `selectNode.expandPlan()`. 

Since having a sub-query as the right-hand side of a comparison is a rather common SQL use case, it is important that this case be optimized appropriately. We can foresee two main ways to achieve this:
- flatten the sub-query as a JOIN in the outer select;
- create a new planNode phase `expandSubQueries()` and delay index selection in selectNode until this phase; then add an option to `EXPLAIN(PLAN)` that calls `expandSubQueries()` if requested by the user.

Non-solutions that should not be considered:
- run the sub-queries during `selectNode.expandPlan()` - there should always be a way for `EXPLAIN(PLAN)` to observe the planNode tree without sending KV commands;
- run the sub-queries during `selectNode.Start()` - this would require `EXPLAIN(PLAN)` to run `Start()` and run into #6613 again.

Jira issue: CRDB-6180

gz#11529

**Comment by andy-kimball** [comment] 2018-08-25 02:18
Proposing we close this as "obsolete", since the cost-based optimizer does things differently.

**Comment by jordanlewis** [comment] 2020-04-02 19:46
```
root@127.0.0.1:62369/defaultdb> explain select * from b where a = (select a from b limit 1);
       tree      |    field     |        description
-----------------+--------------+----------------------------
                 | distributed  | true
                 | vectorized   | false
  root           |              |
   ├── scan      |              |
   │             | table        | b@primary
   │             | spans        | ALL
   │             | filter       | a = @S1
   └── subquery  |              |
        │        | id           | @S1
        │        | original sql | (SELECT a FROM b LIMIT 1)
        │        | exec mode    | one row
        └── scan |              |
                 | table        | b@primary
                 | spans        | ALL
                 | limit        | 1
(15 rows)
```

I don't think this is really done. In spirit, we can't use the results of subqueries to generate spans, which I do think is unfortunate.

**Comment by RaduBerinde** [comment] 2021-06-05 23:45
Part of the solution here would be to hoist subqueries into joins in more cases, as suggested in #35110.

**Comment by mgartner** [comment] 2023-04-03 20:41
This is a duplicate of #23264. Closing.

**Closed by mgartner** 2023-04-03 20:41 UTC
Labels: C-performance, A-sql-optimizer, T-sql-queries
