### ISSUE TITLE
Under-replicated ranges when scaling from 3 to 5 nodes

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#32699] opened 2018-11-28 23:18 UTC
In 2.1, when scaling from 3 to 5 nodes, the Admin UI calls out a number of under-replicated ranges as data is rebalanced. According to the problem range report, these under-replicated ranges are all system ranges, many of which required 5 replicas. It seems that at 3 nodes, the system ignores that requirement, but as soon as you have more than 3 nodes, the system remembers the requirement and recognizes its under-replicated state. Not a big deal, but it could alarm users that, all of a sudden, after adding nodes, ranges are under-replicated; you might expect this when removing nodes without first decommissioning, but not really when adding nodes.

Thoughts:

- Perhaps we could silence the under-replication during that initial up-replication of system ranges. We wouldn't want to silence under-replication of system ranges forever, though.
- We might want to up-replicate any under-replicated ranges BEFORE doing other rebalancing work. 

I also want to mention that, though rebalancing happens evenly in 2.1, it's significantly slower than in earlier releases, based on testing of local clusters.

Steps to reproduce:

1. Start a 3 node cluster locally. 

2. Lower the max range size to make rebalancing more dramatic:

    ```
    cockroach sql --execute="ALTER RANGE default CONFIGURE ZONE USING range_min_bytes=1, range_max_bytes=262144;" --insecure --host=localhost:26257
    ```

3. Load the tpcc schema and initial dataset:

    ```
    cockroach workload init tpcc \
    'postgresql://root@localhost:26257?sslmode=disable'
    ```

3. Run the workload for a bit (optional):

    ```
    cockroach workload run tpcc \
    --duration=30s \
    'postgresql://root@localhost:26257?sslmode=disable'
    ```

4. Add 2 more nodes.

5. In the Admin UI, watch replicas rebalance. And note the **Under-replicated ranges* count, which will slowly decrease over time.

cc: @nvanbenschoten, @tbg

**Comment by nvanbenschoten** [comment] 2018-11-29 16:18
cc. @a-robinson. Both of Jesse's ideas here sound like they're worth considering. 

> Perhaps we could silence the under-replication during that initial up-replication of system ranges. We wouldn't want to silence under-replication of system ranges forever, though.

I don't know how the current "silencing" works. Does this sound easy to do?

> We might want to up-replicate any under-replicated ranges BEFORE doing other rebalancing work.

I would expect the `replicateQueue` to prioritize under-replicated ranges over general rebalancing.

**Comment by a-robinson** [comment] 2018-11-29 16:52
> I don't know how the current "silencing" works. Does this sound easy to do?

It'd be an awkward edge case that would be easy to confuse with longer-standing situations caused by real problems. I'd really rather not do anything special here.

> I would expect the `replicateQueue` to prioritize under-replicated ranges over general rebalancing.

It does. The only thing prioritized more highly than adding a replica to an under-replicated range is adding a replica to a range with a dead replica. If that isn't the case here, then something is quite broken.

However, we do prioritize splitting ahead of rebalancing (https://github.com/cockroachdb/cockroach/issues/25047). The incredibly low `range_max_bytes` might be affecting things here. Either way, it's great we have a simple reproduction to dig into.

**Comment by jseldess** [comment] 2018-11-29 16:58
I'm happy to try this again without the low `range_max_bytes` in a bit.

**Comment by jseldess** [comment] 2018-11-29 21:31
I just restested without lowering the `range_max_bytes`. Both up-replicating system ranges and rebalancing the data happened very fast, so as @a-robinson suggested, the splits must've been getting in the way before.

**Comment by tbg** [comment] 2018-12-04 15:02
I'm surprised you even got a functioning cluster with that setting. See https://github.com/cockroachdb/cockroach/issues/29336

**Comment by lunevalex** [comment] 2021-07-22 18:01
Closing this, does not like there is anything left to do.

**Closed by lunevalex** 2021-07-22 18:01 UTC
Labels: A-kv-replication, C-enhancement, T-kv
