### ISSUE TITLE
sql: TestQueryCache deadlocks under stress

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#105174] opened 2023-06-20 10:35 UTC
**Describe the problem**

`dev test //pkg/sql -f TestQueryCache --stress` deadlocks.

This may be related to  #104660.

**To Reproduce**

The test should not deadlock.

Jira issue: CRDB-28910
Epic: CRDB-28893

**Comment by THardy98** [comment] 2023-06-23 20:42
I'm having a lot of trouble trying to determine the cause of this.

It seems difficult to reproduce, running `./dev test pkg/sql -f TestQueryCache --stress -- --define gotags=bazel,gss,deadlock` locally and on gceworker doesn't reproduce reliably (I sometimes add `--stress-args='-p=4'` to not blow up my/gceworker machine, not sure if that has a huge impact on reproducability).

It often produces:
0 runs so far, 0 failures, over <'x' amount of time>
but very rarely:
POTENTIAL DEADLOCK: ...

even when running for over 30mins.

I've tried running the above on commits prior to the introduction of any audit logging logic (I'm not certain if the CCL commit tagged in the issue is the cause of the deadlock, I wanted to bisect without much success) and seem to get the same result (sometimes runs will complete, sometimes not).

**Comment by knz** [comment] 2023-06-28 12:25
@THardy98 this may not be something related to your change/work.

Is the QueryCache something that the cluster obs team maintains? If not maybe this is a problem for the SQL queries team to pick up.

**Comment by THardy98** [comment] 2023-06-28 14:54
Not something cluster-obs maintains.

Looking at the `git blame` it does look like SQL queries.

**Comment by cucaroach** [comment] 2023-06-28 17:46
Trying to repro now that the race issue was fixed.

**Comment by msirek** [comment] 2023-07-07 19:42
I couldn't repro this. Will run the test over an extended period on a gceworker with a commit from a couple weeks ago.

**Comment by msirek** [comment] 2023-07-08 01:11
No deadlock after 5 1/2 hours

./dev test pkg/sql -f TestQueryCache --stress  -- --define gotags=bazel,gss,deadlock

```
...
454165 runs so far, 0 failures, over 5h29m10s
454280 runs so far, 0 failures, over 5h29m15s
454397 runs so far, 0 failures, over 5h29m20s
454512 runs so far, 0 failures, over 5h29m25s
454630 runs so far, 0 failures, over 5h29m30s
454747 runs so far, 0 failures, over 5h29m35s
454860 runs so far, 0 failures, over 5h29m40s
[2,757 / 2,758] Testing //pkg/sql:sql_test; 19780s linux-sandbox, remote-cache

msirek@gceworker-msirek:~/go/src/github.com/cockroachdb/cockroach$ git log -1
commit ade0dfab8882043a4178966f5fb9b7b94b3e86c3 (HEAD)
Author: Ricky Stewart <ricky@cockroachlabs.com>
Date:   Thu Jun 22 11:53:22 2023 -0500

    bazel: fix builds under `--force_build_cdeps`
    
    This codepath isn't exercised in CI, so we didn't notice it was broken
    with the Bazel 6.2.1 upgrade.
    
    Epic: none
    Release note: None

```

**Comment by cucaroach** [comment] 2023-07-10 16:18
This must have been related to https://github.com/cockroachdb/cockroach/pull/105227.   Closing.

**Closed** 2023-08-31 16:16 UTC
Labels: C-bug, C-test-failure, skipped-test, T-sql-queries
