### ISSUE TITLE
circleci: failed tests (14414): TestClusterRecovery 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5200] opened 2016-03-12 21:29 UTC
The following test appears to have failed:

[#14414](https://circleci.com/gh/cockroachdb/cockroach/14414):

```
I160312 21:27:48.057949 acceptance/chaos_test.go:179  client 0 shutting down
I160312 21:27:48.071588 acceptance/chaos_test.go:362  272 4.1/sec
I160312 21:27:48.171934 acceptance/cluster/localcluster.go:629  stopping
I160312 21:27:48.172131 acceptance/cluster/localcluster.go:527  event stream done, resetting...: net/http: request canceled
I160312 21:27:48.172148 acceptance/cluster/localcluster.go:550  events monitor exits
--- FAIL: TestClusterRecovery (72.97s)
	chaos_test.go:269: pq: storage/stores.go:87: store 3 not found
=== RUN   TestNodeRestart
I160312 21:27:49.908955 acceptance/cluster/localcluster.go:273  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
Node 2 - Store 0
Total Nodes Count:3, Total Store Count:3
I160312 21:27:49.909124 acceptance/cluster/docker.go:73  ImagePull cockroachdb/builder:20160305-182433 starting
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:64: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-17 13:45
Duplicate of #5024.

**Closed by petermattis** 2016-03-17 13:45 UTC
Labels: test-failure
