### ISSUE TITLE
bazel: `build //pkg/cmd/cockroach` fails if `ccache` is installed

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#71176] opened 2021-10-05 20:50 UTC
If `ccache` is installed, I get the following error:

```
ERROR: /spill/kena/cache/bazel/_bazel_kena/fd4e84c51f365d6a93ea158225b979df/external/com_google_protobuf/BUILD:154:11: Compiling src/google/protobuf/util/delim
ited_message_util.cc failed: (Exit 1): gcc failed: error executing command /usr/lib/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-param
eter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 39 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/lib/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall
-Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 39 argume
nt(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ccache: error: Failed to create directory /home/kena/.ccache/tmp: Read-only file system
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.811s, Critical Path: 0.58s
INFO: 22 processes: 22 internal.
FAILED: Build did NOT complete successfully
```

it looks like bazel fails to set the ccache output directory to a path inside the sandbox.

If I then unstall `ccache`, and run the build command again, I get a different error:

```
ERROR: /spill/kena/cache/bazel/_bazel_kena/fd4e84c51f365d6a93ea158225b979df/external/com_google_protobuf/BUILD:410:10: Compiling src/google/protobuf/compiler/main.cc failed: (Exit 1): gcc failed: error executing command /usr/lib/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 37 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/lib/ccache/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall
-Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 37 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
src/main/tools/linux-sandbox-pid1.cc:390: "execvp(/usr/lib/ccache/gcc, 0x2302020)": No such file or directory
Target //pkg/cmd/cockroach:cockroach failed to build
Use --verbose_failures to see the command lines of failed build steps.
```

This tells me that the full path to the host gcc was embedded inside the bazel cache somehow.

If I then remove the bazel cache (`/spill/kena/cache/bazel/_bazel_kena`) entirely (with ccache still uninstalled), then the build succeeds.

**Comment by rickystewart** [comment] 2021-10-05 23:01
Known issue/"WONTFIX" thing. `ccache` and Bazel, by design, don't play together nicely. `ccache`'s entire purpose is to write to its cache outside the sandbox, and Bazel will fail the build when it notices `ccache` doing that.

Have you tried building w/ `dev build`?  `dev build` strips the `ccache` symlinks out of the `PATH` before calling `bazel` for exactly this reason.

**Comment by knz** [comment] 2021-10-05 23:03
okay but I thought that bazel was sandboxing the C compiler, isn't that a thing any more?

**Comment by knz** [comment] 2021-10-05 23:06
the above error was obtained on a plain linux ubuntu.
how do I opt into using the sandboxed compiler?

**Comment by rickystewart** [comment] 2021-10-05 23:08
Build w/ `--config=crosslinux` (NB: do this INSTEAD OF `--config=dev`, if you happened to have that in your `~/.bazelrc`)

**Closed** 2021-10-05 23:23 UTC
Labels: C-bug
