### ISSUE TITLE
Cluster cannot upgrade version 

### ISSUE THREAD

**Issue by christian-lefty** [cockroachdb/cockroach#74623] opened 2022-01-10 13:37 UTC
Hello,

I have upgraded a cluster from version v19.2.12 to 20.1.17 then 20.2.18 without any issues.
However when I performed 20.2.19 to 21.1.12, the version doesn't get upgraded.

See my cluster all nodes are on 21.1.12:

![Screenshot from 2022-01-10 14-34-46](https://user-images.githubusercontent.com/13681456/148774800-adce30dd-ce61-471a-94c6-e380358f34b9.png)

However the CLI shows the cluster setting version is stuck:

show cluster setting version;
  version
-----------
  20.2
(1 row)

Time: 38ms total (execution 3ms / network 35ms)

I have found the following error statement in the logs:

`
I220110 13:30:04.475653 4202711 migration/migrationmanager/manager.go:125 ⋮ [n11,intExec=‹set-version›,migration-mgr] 1740  stepping through 20.2-2
I220110 13:30:04.477076 1930 server/auto_upgrade.go:75 ⋮ [n11] 1741  error when finalizing cluster version upgrade: ‹set-version›: n1 required, but unavailable
`

This is problematic because n1 is a node that was decomissioned a very long time ago

![Screenshot from 2022-01-10 14-36-46](https://user-images.githubusercontent.com/13681456/148775088-3f10946a-7269-4408-82f1-93c0c2848509.png)

**Comment by msbutler** [comment] 2022-01-10 15:22
@christian-lefty wanted to let you know that i'm finding the right team to look into this for you.

**Comment by christian-lefty** [comment] 2022-01-10 16:35
@msbutler  amazing, thanks

**Comment by ivankresic4p** [comment] 2022-01-11 17:59
@christian-lefty I had the same issue, you can read about it here https://forum.cockroachlabs.com/t/cannot-upgrade-to-v21-2-cluster-version-error/4971. You have to decommission those nodes again, that will remove them from the admin panel and enable you to finish the upgrade. If needed, set the appropriate version to cluster.preserve_downgrade_option, if just deleting the nodes doesn't help.

**Comment by msbutler** [comment] 2022-01-12 17:22
@christian-lefty let me know if [this ](https://github.com/cockroachdb/cockroach/issues/74623#issuecomment-1010220097)solves your issue. Also, are you a cockroach cloud user?

**Comment by christian-lefty** [comment] 2022-01-13 10:50
Hello! Yes the answer above fixed the issue, thanks @ivankresic4p 

No not a cloud user.

**Comment by msbutler** [comment] 2022-01-13 16:24
Closing this issue, as it is a duplicate of https://github.com/cockroachdb/cockroach/issues/70084

**Closed by msbutler** 2022-01-13 16:24 UTC
Labels: O-community, X-blathers-untriaged

**Comment by recursionbane** [comment] 2023-03-03 16:53
I have this exact error, and the suggestion above to run the decommission command from a different node does not resolve it.
It merely hangs for >24 hours, though it prints a dot every ten minutes or so.

```
docker exec -it cockroachdb ./cockroach node decommission 1 --insecure
warning: node 1 is already decommissioning or decommissioned

  id | is_live | replicas | is_decommissioning |   membership    | is_draining
-----+---------+----------+--------------------+-----------------+--------------
   1 |  false  |        2 |        true        | decommissioning |    true
(1 row)
.......................
```

The node is long-dead, though the server name is now reused for a different node.

Is there a force-decom or a force-delete I can perform on the node?

**Comment by msbutler** [comment] 2023-03-03 17:17
@recursionbane could you open up a new issue with the specs (e.g. version) of your cluster, and a detailed timeline of the steps you took to upgrade your cluster? That way it will be properly triaged.
