### ISSUE TITLE
kvserver: programming error: timestamp change by implicitly committed transaction

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#105332] opened 2023-06-22 10:24 UTC
**Describe the problem**

On https://github.com/cockroachdb/cockroach/pull/97779

[kvnemesis.zip](https://github.com/cockroachdb/cockroach/files/11833255/kvnemesis.zip)
[kvnemesis-logs.zip](https://github.com/cockroachdb/cockroach/files/11833256/kvnemesis-logs.zip)

```
b.ReverseScan(tk(10336907422874864688), tk(15724485944471569813)) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
```

<details>
<summary>Details</summary>

```
./dev test --stress --filter TestKVNemesisSingleNode ./pkg/kv/kvnemesis/
//pkg/kv/kvnemesis:kvnemesis_test                                        FAILED in 949.1s

--- FAIL: TestKVNemesisSingleNode (11.24s)
    kvnemesis_test.go:278: seed: 6689026260782761782
    kvnemesis.go:168: error applying x.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
          txn.SetIsoLevel(isolation.ReadCommitted)
          {
            b := &kv.Batch{}
            b.GetForUpdate(tk(2943894847620899253)) // (<nil>, <nil>)
            b.Put(tk(6642475870640949667), sv(28)) // <nil>
            txn.Run(ctx, b) // @1687427277.196278000,0 <nil>
          }
          {
            b := &kv.Batch{}
            b.Scan(tk(1939140750992769417), tk(5501181370973784319)) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
            b.ReverseScan(tk(10336907422874864688), tk(15724485944471569813)) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
            txn.Run(ctx, b) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
          }
          txn.ReverseScanForUpdate(ctx, tk(16189193108374242322), tk(17086342579961093455), 0) // omitted
          return errors.New("rollback")
        }) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0: failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
    kvnemesis.go:168: error applying x.Scan(ctx, tk(1939140750992769417), tk(5501181370973784319), 0) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0: failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
    kvnemesis.go:168: error applying x.ReverseScan(ctx, tk(10336907422874864688), tk(15724485944471569813), 0) // failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0: failed indeterminate commit recovery: programming error: timestamp change by implicitly committed transaction: 1687427277.194248000,1->1687427277.155932000,0
```

</details>

cc @arulajmani @nvanbenschoten 

Jira issue: CRDB-28985

**Comment by nvanbenschoten** [comment] 2023-07-31 23:13
Duplicate of https://github.com/cockroachdb/cockroach/issues/107860.

**Closed by nvanbenschoten** 2023-07-31 23:13 UTC
Labels: C-bug, T-kv
