### ISSUE TITLE
cdc: TestChangefeedKafkaMessageTooLarge is flakey

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#93518] opened 2022-12-13 16:14 UTC
```
--- FAIL: TestChangefeedKafkaMessageTooLarge (46.27s)
    test_log_scope.go:161: test logs captured to: /Users/rc/src/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/f5cb02fa45891c8256821a187ced6fe9/logTestChangefeedKafkaMessageTooLarge484067361
    test_log_scope.go:79: use -show-logs to present logs inline
    --- FAIL: TestChangefeedKafkaMessageTooLarge/kafka (46.25s)
        helpers_test.go:751: making server as secondary tenant
        helpers_test.go:837: making kafka feed factory
        --- FAIL: TestChangefeedKafkaMessageTooLarge/kafka/succeed_against_a_large_backfill (45.22s)
            changefeed_test.go:7478: still waiting for job status; current reverting
    changefeed_test.go:7550: -- test log scope end --
```

Build: <https://teamcity.cockroachdb.com/viewLog.html?buildId=7943709&buildTypeId=Cockroach_PostMerge_MergedArm64Tests>

Can be easily reproduced by stressing the test (~1m, 200 runs).

Jira issue: CRDB-22376

**Comment by samiskin** [comment] 2022-12-21 18:10
Closing as duplicate of https://github.com/cockroachdb/cockroach/issues/93847

**Closed by samiskin** 2022-12-21 18:10 UTC
Labels: C-bug, A-cdc, T-cdc
