### ISSUE TITLE
failed test: bank/zerosum-splits because of "change replicas failed"

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#32604] opened 2018-11-26 18:34 UTC
https://teamcity.cockroachdb.com/viewLog.html?buildId=1022401&problemId=2150
```
test.go:645,bank.go:375,bank.go:521,acceptance.go:65: pq: change replicas of r25 failed: unexpected value: timestamp:<wall_time:1542833398422176901 >
```
[Unit_Tests_roachtest_14471.log.zip](https://github.com/cockroachdb/cockroach/files/2616863/Unit_Tests_roachtest_14471.log.zip)
The failed TC run was for a comments-only PR.

There's also #32497 open for a different failure of the same test, and @petermattis seems to claim there that no failure of the test is reproducible.

@benesch I'm... assigning it to... you.

**Comment by benesch** [comment] 2018-11-26 21:07
Root cause is #31287. See #32608 for deflaking in the meantime.

**Comment by tbg** [comment] 2018-12-04 15:36
#32608 has landed so I think this should close. Please reopen if not.

**Closed by tbg** 2018-12-04 15:36 UTC
Labels: A-core-distribution, C-test-failure
