### ISSUE TITLE
distsqlrun: panic in diskRowIterator

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#24588] opened 2018-04-08 00:27 UTC
From https://teamcity.cockroachdb.com/viewLog.html?buildId=593740&buildTypeId=Cockroach_SqlLogicTests&tab=buildLog&_focus=33263

```
unexpected fault address 0x7f1fbec00000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f1fbec00000 pc=0x12d0904]

goroutine 29245680 [running]:
runtime.throw(0x20378d1, 0x5)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0xc428b479f8 sp=0xc428b479d8 pc=0x8091f1
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:395 +0x211 fp=0xc428b47a48 sp=0xc428b479f8 pc=0x81ed01
github.com/cockroachdb/cockroach/pkg/storage/engine.gobytes(0x7f1fbec00000, 0x0, 0xe, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/slice.go:30 +0x34 fp=0xc428b47a90 sp=0xc428b47a48 pc=0x12d0904
github.com/cockroachdb/cockroach/pkg/storage/engine.cSliceToGoBytes(0x7f1fbec00000, 0x0, 0xd, 0xe, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:2229 +0x3a fp=0xc428b47ac8 sp=0xc428b47a90 pc=0x12e07ca
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Value(0xc436ce21c0, 0xe, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1965 +0x2f fp=0xc428b47b00 sp=0xc428b47ac8 pc=0x12de43f
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDBMapIterator).Value(0xc42c349500, 0xc4330a43f4, 0x9, 0xa)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/disk_map.go:295 +0x36 fp=0xc428b47b30 sp=0xc428b47b00 pc=0x12bfd06
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.diskRowIterator.Row(0xc42a1aea00, 0x234ade0, 0xc42c349500, 0x16f2b5d, 0xc42c349500, 0xc42ae0c801, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/disk_row_container.go:224 +0xb0 fp=0xc428b47bb8 sp=0xc428b47b30 pc=0x1683d40
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*diskRowIterator).Row(0xc427be8e40, 0x2049401, 0x0, 0x0, 0x10, 0x0)
	<autogenerated>:1 +0x52 fp=0xc428b47c08 sp=0xc428b47bb8 pc=0x16f2c72
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Next(0xc4384dcea0, 0xc42ea99b00, 0x2, 0x2, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:177 +0x4ea fp=0xc428b47f50 sp=0xc428b47c08 pc=0x16ddc8a
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x2335380, 0xc42e0d3ec0, 0x2336100, 0xc4384dcea0, 0x231c780, 0xc435b3c1e0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:135 +0x35 fp=0xc428b47f90 sp=0xc428b47f50 pc=0x166a145
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Run(0xc4384dcea0, 0xc433cafdf8)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:282 +0x6e fp=0xc428b47fd0 sp=0xc428b47f90 pc=0x16de96e
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc428b47fd8 sp=0xc428b47fd0 pc=0x838c81
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:470 +0x3a5
```

**Comment by petermattis** [comment] 2018-05-06 16:40
Duplicate of #25289.

**Closed by petermattis** 2018-05-06 16:40 UTC
Labels: C-bug, S-2-temp-unavailability
