### ISSUE TITLE
sql: support for pgsql4

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#40390] opened 2019-08-30 23:02 UTC
pgsql4
Version:4.11
A user tried to administrate with pgsql4 but saw this behavior:
![image](https://user-images.githubusercontent.com/22278911/64055128-b114c600-cb58-11e9-8626-a45727245901.png)

> No database shows up too. I can't administrate with pgsql4.

Jira issue: CRDB-5541

**Comment by jordanlewis** [comment] 2022-11-07 20:33
Duplicate of #25213

**Closed by jordanlewis** 2022-11-07 20:33 UTC
Labels: C-enhancement, A-sql-pgcompat, T-sql-experience
