### ISSUE TITLE
Test failure in CI build 9171

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3085] opened 2015-11-10 17:02 UTC
The following test appears to have failed:

[#9171](https://circleci.com/gh/cockroachdb/cockroach/9171):

```
W1110 17:02:17.619867 944 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
W1110 17:02:17.718427 944 multiraft/multiraft.go:1221  node 5 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 17:02:17.718574 944 multiraft/multiraft.go:1221  node 5 failed to send message to 6: multiraft/transport.go:132: transport is closed
W1110 17:02:17.719706 944 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
W1110 17:02:17.719836 944 multiraft/multiraft.go:1221  node 6 failed to send message to 4: multiraft/transport.go:132: transport is closed
--- FAIL: TestSplitSnapshotRace_SnapshotWins (37.11s)
	<autogenerated>:32: storage/client_split_test.go:778: condition failed to evaluate within 3s: storage/client_test.go:559: expected [0 11 11 11 0 0], got [0 11 11 1 0 0]
	client_test.go:270: timed out during shutdown
=== RUN   Example_rebalancing
W1110 17:02:17.853762 944 multiraft/multiraft.go:1221  node 5 failed to send message to 6: multiraft/transport.go:132: transport is closed
W1110 17:02:17.853906 944 multiraft/multiraft.go:1221  node 5 failed to send message to 4: multiraft/transport.go:132: transport is closed
I1110 17:02:17.854007 944 raft/raft.go:488  [group 11] 4 is starting a new election at term 92
I1110 17:02:17.854113 944 raft/raft.go:422  [group 11] 4 became candidate at term 93
I1110 17:02:17.854182 944 raft/raft.go:471  [group 11] 4 received vote from 4 at term 93
I1110 17:02:17.854385 944 raft/raft.go:464  [group 11] 4 [logterm: 8, index: 35] sent vote request to 1 at term 93
I1110 17:02:17.854630 944 raft/raft.go:464  [group 11] 4 [logterm: 8, index: 35] sent vote request to 5 at term 93
--
W1110 17:02:18.457626 944 multiraft/multiraft.go:1221  node 5 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 17:02:18.457787 944 multiraft/multiraft.go:1221  node 5 failed to send message to 6: multiraft/transport.go:132: transport is closed
W1110 17:02:18.461899 944 multiraft/multiraft.go:1221  node 6 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 17:02:18.462033 944 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
--- PASS: Example_rebalancing (0.67s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	67.085s
=== RUN   TestBatchBasics
I1110 17:01:11.288421 940 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1110 17:01:11.292816 940 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1110 17:01:11.298722 940 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-11-10 18:00
Dupe of (the new version of) #3038.

**Closed by tamird** 2015-11-10 18:00 UTC
Labels: test-failure
