### ISSUE TITLE
sql: adding column hangs and leaves server in bad state

### ISSUE THREAD

**Issue by benmargolin** [cockroachdb/cockroach#13380] opened 2017-02-02 19:09 UTC
Is this a question, feature request, or bug report?

INFO header: 

```I170201 14:25:57.148339 1 util/log/clog.go:1012  [config] file created at: 2017/02/01 14:25:57
I170201 14:25:57.148339 1 util/log/clog.go:1012  [config] running on machine: sonicfe
I170201 14:25:57.148339 1 util/log/clog.go:1012  [config] binary: CockroachDB CCL beta-20170126 (linux amd64, built 2017/01/26 16:00:11, go1.7.4)
I170201 14:25:57.148339 1 util/log/clog.go:1012  [config] arguments: [cockroach start --store=/home/sonic/cockroach-data/ --http-port 8280 --vmodule=executor=2]
```
2. Please describe the issue you observed:

Hang on attempt to alter table and add a non-null timestamp column.

- What did you do?

Wanted to add a ts col to a table. Here's the table def:

```+-------+----------------------------------------------------------------------------------------+
| Table |                                      CreateTable                                       |
+-------+----------------------------------------------------------------------------------------+
| users | CREATE TABLE users (␤                                                                  |
|       |     username STRING(40) NOT NULL,␤                                                     |
|       |     firebase_uid STRING(128) NULL,␤                                                    |
|       |     testonly BOOL NOT NULL DEFAULT false,␤                                             |
|       |     display_name STRING NOT NULL DEFAULT '',␤                                          |
|       |     photo_uri STRING NOT NULL DEFAULT '',␤                                             |
|       |     audio_uri STRING NOT NULL DEFAULT '',␤                                             |
|       |     created_ts TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                        |
|       |     created TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                           |
|       |     testts TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                            |
|       |     CONSTRAINT "primary" PRIMARY KEY (username),␤                                      |
|       |     FAMILY "primary" (username, firebase_uid, testonly, created_ts, created, testts),␤ |
|       |     FAMILY fam_1_display_name (display_name),␤                                         |
|       |     FAMILY fam_2_photo_uri (photo_uri),␤                                               |
|       |     FAMILY fam_3_audio_uri (audio_uri)␤                                                |
|       | )                                                                                      |
+-------+----------------------------------------------------------------------------------------+
```

There's 73 rows in the table. Here's the commands I ran from a batch file:

`cockroach --database=sonic sql < 0021_usertimestamps.sql`

and the contents of that file are:

```
SET DATABASE = sonic;

-- Adds tracking of when users are created. Preexisting user dates won't be quite right, but,
-- that's OK.

ALTER TABLE users ADD COLUMN created_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP();
```

- What did you expect to see?

I expected the column to be added and the values to be set to the current time.

- What did you see instead?

The SQL console hung after "SET". Waited a couple of minutes. Nothing. Stopped the script. Tried to shut down the server with quit from commandline, wouldn't. Eventually did get it to quit, and restarted the server. Did show create table and the column wasn't present. Tried to add it again and got "duplicate column" error. Tried to drop the column and got `pq: column "created_ts" in the middle of being added, try again later`. I then manually tried to add another column (differen name, otherwise same command) and the same hang happened. 
Even after a server upgrade to the latest beta, same thing.

I'm currently worried it's in a bad state :( Oh also I ran this same command on my dev server previously, and it worked fine -- but that has different data and is also the 20161103 release (need to upgrade that!)

**Comment by knz** [comment] 2017-02-02 19:16
cc @dt @vivekmenezes @bdarnell

**Comment by benmargolin** [comment] 2017-02-02 19:25
Hey! Some possible new info. I just tried to migrate the data to a tmp table and this is the show create table output:
```+-------+----------------------------------------------------------------------------------------+
| Table |                                      CreateTable                                       |
+-------+----------------------------------------------------------------------------------------+
| users | CREATE TABLE users (␤                                                                  |
|       |     username STRING(40) NOT NULL,␤                                                     |
|       |     firebase_uid STRING(128) NULL,␤                                                    |
|       |     testonly BOOL NOT NULL DEFAULT false,␤                                             |
|       |     display_name STRING NOT NULL DEFAULT '',␤                                          |
|       |     photo_uri STRING NOT NULL DEFAULT '',␤                                             |
|       |     audio_uri STRING NOT NULL DEFAULT '',␤                                             |
|       |     created_ts TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                        |
|       |     created TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                           |
|       |     testts TIMESTAMP NOT NULL DEFAULT current_timestamp(),␤                            |
|       |     CONSTRAINT "primary" PRIMARY KEY (username),␤                                      |
|       |     FAMILY "primary" (username, firebase_uid, testonly, created_ts, created, testts),␤ |
|       |     FAMILY fam_1_display_name (display_name),␤                                         |
|       |     FAMILY fam_2_photo_uri (photo_uri),␤                                               |
|       |     FAMILY fam_3_audio_uri (audio_uri)␤                                                |
|       | )                                                                                      |
+-------+----------------------------------------------------------------------------------------+
(1 row)
```

Which actually shows the columns! This is on the latest beta (20170126). I was able to drop the extra "test" columns (created, testts) as well! So it sort of... works now. Also the column values all look OK.

Is it possible because I'm running in a single-node system, the alter just took a reeeeally long time? [Crazy theory follows:] Maybe it was timing out trying to propagate the change to other non-existent nodes, and it wasn't until it totally gave up, that the "transaction" finished to add the column? I say this because I know in the past there were some issues about it being confused to some extent, about running in a single-node config.

**Comment by petermattis** [comment] 2017-02-02 21:40
@benmargolin Can you share `0021_usertimestamps.sql`? I'm sure we'll get to the bottom of this quickly if we can reproduce locally.

**Comment by bdarnell** [comment] 2017-02-02 21:41
@petermattis It's there in the original post: `ALTER TABLE users ADD COLUMN created_ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP();`

**Comment by petermattis** [comment] 2017-02-02 21:43
Ah, I misread that. I was actually looking for the 73 rows of data. I suppose we could generate some synthetic data.

**Comment by benmargolin** [comment] 2017-02-03 00:01
It's "production" user data so unfortunately I can't share it.

**Comment by vivekmenezes** [comment] 2017-02-03 02:43
So created_ts was already in the original schema and also part of the primary key, so perhaps you were trying something different. Thanks

**Comment by vivekmenezes** [comment] 2017-02-03 02:49
I'd appreciate it if you can reproduce this with the database flag `--vmodule=executor=2,backfill=2,schema_changer=2`

and share the logs. Thanks!

**Comment by benmargolin** [comment] 2017-02-03 04:15
@vivekmenezes it wasn't in the original schema, no. it got magically added to the PK when the table was altered to include the column. I'll see if I can repro tomorrow with those flags.

**Comment by bdarnell** [comment] 2017-02-03 04:28
It's not in the primary key, that's the primary column family.

**Comment by benmargolin** [comment] 2017-02-13 22:10
Hi guys, I've got more info, as I was hit by this again in production. This time I didn't try to stop it, just let it go. It finally _did_ finish adding a timestamp column to a 28-row table, but only after an astounding **8  minutes**.

I'm attaching the relevant bits of the INFO log, hope it helps.
[slow_alter_infolog.txt](https://github.com/cockroachdb/cockroach/files/772547/slow_alter_infolog.txt)

**Comment by petermattis** [comment] 2017-02-13 22:30
@benmargolin Is this the same table schema that you were using before? If not, could you provide the original `create table` statement and the `alter table` statement you used?

@vivekmenezes Have you been able to reproduce this locally?

**Comment by benmargolin** [comment] 2017-02-14 00:03
Actually it happened on at least 2 different tables. And I think they were both different tables than the first time (so 3 in total). Here's the schema for one of them, before the alter:
```
+--------+-----------------------------------------------------+
| Table  |                     CreateTable                     |
+--------+-----------------------------------------------------+
| groups | CREATE TABLE groups (␤                              |
|        |     group_name STRING NOT NULL,␤                    |
|        |     display_name STRING NOT NULL DEFAULT '',␤       |
|        |     photo_uri STRING NOT NULL DEFAULT '',␤          |
|        |     created_by STRING NOT NULL DEFAULT '',␤         |
|        |     CONSTRAINT "primary" PRIMARY KEY (group_name),␤ |
|        |     FAMILY "primary" (group_name, display_name),␤   |
|        |     FAMILY fam_1_photo_uri (photo_uri),␤            |
|        |     FAMILY fam_2_created_by (created_by)␤           |
|        | )                                                   |
+--------+-----------------------------------------------------+
```

here's the alter:
`ALTER TABLE groups ADD COLUMN last_msg_ts TIMESTAMP NULL;`

I **believe** it did the exact same thing (took multiple minutes) to do this alter:
`ALTER TABLE contact_graph ADD unread_count INT NOT NULL DEFAULT 0;`
on a freshly-created, empty table like this:
```
CREATE TABLE contact_graph (
  from_user STRING NOT NULL,
  to_user STRING NOT NULL,
  sent_invite_ts TIMESTAMP NULL,
  was_invited_ts TIMESTAMP NULL,
  accepted_ts TIMESTAMP NULL,
  blocked_ts TIMESTAMP NULL,
  last_contact_ts TIMESTAMP NULL);
```
although it's possible that one went OK -- there were a number of updates that happened in a script. Hopefully the traces in the attached log give enough of an idea what is happening.

I've now upgraded to the latest snapshot (2/9 I think) and have added the extra flags, if it happens again I'll add those logs too. I'm scared to really try it much, as I said this is a production DB.

**Comment by vivekmenezes** [comment] 2017-02-14 13:13
Any long delay is usually because of the table lease mechanism not working properly with leases not being released.

There are a number of sections in the logs that looks suspicious

the heartbeats for the lease release commands are failing

```
W170213 13:52:45.908648 51974119 kv/txn_coord_sender.go:773  heartbeat to "sql/lease.go:249 LeaseStore.Release" id=3fd18375 key=/Table/11/1/60/3/2017-02-03T20:58:03.391769Z/1 rw=true pri=0.01576012 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.752603936,0 orig=1487022755.752603936,0 max=1487022756.252603936,0 wto=false rop=true failed: heartbeat for transaction "sql/lease.go:249 LeaseStore.Release" id=3fd18375 key=/Table/11/1/60/3/2017-02-03T20:58:03.391769Z/1 rw=true pri=0.01576012 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.752603936,0 orig=1487022755.752603936,0 max=1487022755.752603936,0 wto=false rop=true failed; record not present
W170213 13:52:45.910390 51974397 kv/txn_coord_sender.go:773  heartbeat to "sql/lease.go:249 LeaseStore.Release" id=defad222 key=/Table/11/1/60/3/2017-02-03T02:45:48.219291Z/1 rw=true pri=0.05419352 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.692368447,0 orig=1487022755.692368447,0 max=1487022756.192368447,0 wto=false rop=true failed: heartbeat for transaction "sql/lease.go:249 LeaseStore.Release" id=defad222 key=/Table/11/1/60/3/2017-02-03T02:45:48.219291Z/1 rw=true pri=0.05419352 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.692368447,0 orig=1487022755.692368447,0 max=1487022755.692368447,0 wto=false rop=true failed; record not present
W170213 13:52:45.916587 51975184 kv/txn_coord_sender.go:773  heartbeat to "sql/lease.go:249 LeaseStore.Release" id=6a724b04 key=/Table/11/1/60/3/2017-02-04T14:38:11.322717Z/1 rw=true pri=0.01718509 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022756.049259653,0 orig=1487022756.049259653,0 max=1487022756.549259653,0 wto=false rop=true failed: heartbeat for transaction "sql/lease.go:249 LeaseStore.Release" id=6a724b04 key=/Table/11/1/60/3/2017-02-04T14:38:11.322717Z/1 rw=true pri=0.01718509 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022756.049259653,0 orig=1487022756.049259653,0 max=1487022756.049259653,0 wto=false rop=true failed; record not present
W170213 13:52:45.916815 51974662 kv/txn_coord_sender.go:773  heartbeat to "sql/lease.go:249 LeaseStore.Release" id=4f313ff5 key=/Table/11/1/55/3/2017-02-03T00:34:59.205557Z/1 rw=true pri=0.03741197 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.248326381,0 orig=1487022755.248326381,0 max=1487022755.748326381,0 wto=false rop=true failed: heartbeat for transaction "sql/lease.go:249 LeaseStore.Release" id=4f313ff5 key=/Table/11/1/55/3/2017-02-03T00:34:59.205557Z/1 rw=true pri=0.03741197 iso=SERIALIZABLE stat=PENDING epo=0 ts=1487022755.248326381,0 orig=1487022755.248326381,0 max=1487022755.248326381,0 wto=false rop=true failed; record not present
```

raft mutex being held for > 4 seconds

```
W170213 13:52:59.976111 37 storage/replica.go:564  [n1,s1,r21/1:/{System/"upda…-Table/11},@c42087a600] raftMu: mutex held by github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady for 4.319725843s (>500ms):
```

a lease was not released properly

```
E170213 13:53:24.854898 52047593 internal/client/txn.go:337  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
W170213 13:53:24.854923 52047593 sql/lease.go:765  error releasing lease "63(\"read_tracking\") ver=1:1486081266238820000": does not exist
```

```
E170213 13:53:25.885496 52064664 internal/client/txn.go:337  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
W170213 13:53:25.885525 52064664 sql/lease.go:765  error releasing lease "65(\"health_checks\") ver=1:1486914976439712000": does not exist
```

```
E170213 13:53:26.103629 52048253 internal/client/txn.go:337  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
W170213 13:53:26.103646 52048253 sql/lease.go:765  error releasing lease "63(\"read_tracking\") ver=1:1486858510273348000": does not exist
```

We even override an existing schema change lease

```
I170213 13:58:52.367818 83 sql/schema_changer.go:121  Overriding existing expired lease node_id:1 expiration_time:1487023069501015590 
```

Lots of stuff here that I need to process. Will take a look today. Thank you!

**Comment by vivekmenezes** [comment] 2017-02-14 16:04
The logs point to a table lease that hasn't expired. There are plenty of these log messages:

```
I170213 13:53:23.214600 51947959 sql/lease.go:290  publish (count leases): descID=61 name=groups version=3 count=1
```

So at least we understand what is slowing down the schema change.

**Comment by vivekmenezes** [comment] 2017-02-14 21:53
And we also see a particular release lease that fails
```
E170213 13:53:22.101464 52026868 internal/client/txn.go:337  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: does not exist
W170213 13:53:22.101504 52026868 sql/lease.go:765  error releasing lease "61(\"groups\") ver=3:1486142038522163000": does not exist
```

So it's looking like we have an issue with raft getting busy enough that some transactions fail. When a lease release fails, it will hold up a schema change for at least 5 minutes. I'm going to continue investigating. I wonder if this is all related to these messages:

```
W170213 13:52:59.976111 37 storage/replica.go:564  [n1,s1,r21/1:/{System/"upda…-Table/11},@c42087a600] raftMu: mutex held by github.com/cockroachdb/cockroach
/pkg/storage.(*Replica).handleRaftReady for 4.319725843s (>500ms):
```

**Comment by vivekmenezes** [comment] 2017-02-15 18:27
I've pushed a change that retries the table lease release transaction so that it has a better chance of succeeding. When it succeeds the schema change blocked on it can make progress.

Fundamentally it's worrisome that the lease release transaction is seeing the above error. It points to the transaction not finding its record which happens when it's unable to heartbeat properly. It looks like your cluster is seeing some weird load that is overloading it resulting in transactions failing. It will be great if you can share what workload you are applying to this cluster. Thanks.

**Comment by benmargolin** [comment] 2017-02-15 19:30
Well my cluster is 1 node, which I maintain is probably part of the issue
-- I suspect there's some code somewhere that really really doesn't like
single-node configs as it's not the expected situation.

Aside from that, this gets very light load overall. Currently if it hit 10
qps I'd be surprised. Most of the queries are quite simple, although some
are more complex (joins). How do I characterize the workload in a way that
would help you understand? Is there some kind of logging that would help?

**Comment by vivekmenezes** [comment] 2017-02-17 15:53
@benmargolin this issue should be fixed with the commit I merged today (available on next weeks beta). I'm not closing this issue because we are concerned about some transactions not completing in the logs. I've just made the schema change code more robust against those failures, but I worry we're papering over the underlying issue.

**Comment by benmargolin** [comment] 2017-02-17 16:36
Got it, thanks for the investigation and attempted fix. Will try to upgrade when new beta is out.

**Comment by vivekmenezes** [comment] 2017-03-07 16:23
@benmargolin is the schema change that you've been running speeded up? Thanks

**Comment by benmargolin** [comment] 2017-03-10 14:43
I actually gave up and switched to Postgres :( sorry. I had too many unexplained performance issues that scared me. My needs are pretty simple, I don't actually need a lot of horiz scaling (yet) and psql is even overkill, but as we're launching the product now, I didn't want to have to deal with any more unknowns that necessary, and Cockroach just didn't convince me it was ready for what I was going to throw at it, yet. I still hope to use it in the future, however, and will keep tracking development. You folks seem to overall be making huge progress and it's impressive; I hope it'll suit my needs eventually.

**Comment by dianasaur323** [comment] 2017-03-10 15:44
@benmargolin I'm sorry to hear that, but glad that you tried us out. The good thing is that our compatibility with the PostgreSQL wire protocol means that trying us again in the future hopefully won't be too hard. If you have time, I'd love to dig in a little further on your use case, needs, and concerns so that we can address and prioritize them going forward. If you're up for it, let me know the best way to connect with you!

**Comment by donpdonp** [comment] 2017-06-06 17:33
```sql
alter table schedules drop status;
alter table schedules add status int not null default 0;
```
I'm seeing a similar behavior. version is below.
build:      CCL v1.0 @ 2017/05/10 13:19:57 (go1.8.1)

```
2017/06/06 10:28:57 FAIL 20170606_alter_schedules_status.sql (pq: column "status" being dropped, try again later), quitting migration.
```

Not sure what to do here, I tried restarting cockroach but the problem remains. This is a one-node install with basically zero query load on the box.

**Comment by vivekmenezes** [comment] 2017-06-06 20:44
@donpdonp what you're reporting is an issue with recycling a name for a schema element (column in your case). It is similar to https://github.com/cockroachdb/cockroach/issues/12123 where cockroach fails to drop and create a table using the same name.

I hope the system itself didn't hang? It should report the error and quit.

**Comment by donpdonp** [comment] 2017-06-06 20:48
it did report the error and kept going, though i was not sure what state the schema was in. So the problem is reusing a schema column name in the same transaction? (I belive my schema manager tool runs migrations in a transaction). I could do the migration steps by hand at the sql console w/o a transaction.

**Comment by vivekmenezes** [comment] 2017-06-06 20:56
yeah doing the migration step by step will work. Each command waits until it is complete (it executes the schema change as a transaction, and then, waits until it has been completely executed.) Time should not matter there as long as you take it out of a transaction and run the second command after the first has completed.

**Comment by vivekmenezes** [comment] 2017-08-07 20:19
Closing this issue as outdated.

**Closed by vivekmenezes** 2017-08-07 20:19 UTC
Labels: bug, community-questions, investigation, stability
