### ISSUE TITLE
sql: dropping a sequence with a sequence owners corrupts the table that owns the sequence

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#50649] opened 2020-06-25 16:47 UTC
Repro:

```
root@:26257/defaultdb> create table a (a int primary key);
CREATE TABLE

Time: 49.454ms

root@:26257/defaultdb> create sequence foo owned by a.a;
CREATE SEQUENCE

Time: 162.234ms

root@:26257/defaultdb> drop sequence foo;
DROP SEQUENCE

Time: 251.705ms

root@:26257/defaultdb> drop table a;
ERROR: table is being dropped
```

It looks like there is no code to remove the sequence owner ID from the column descriptor that owns the sequence when the sequence is dropped.

**Comment by rohany** [comment] 2020-06-25 17:51
Huh, @RichardJCai found this a bit ago -- https://github.com/cockroachdb/cockroach/issues/48249

**Comment by RichardJCai** [comment] 2020-06-25 18:00
> Huh, @RichardJCai found this a bit ago -- #48249

I realize that it actually prevents dropping the table that owns the sequence after.

**Comment by lucy-zhang** [comment] 2020-06-26 20:04
I'm reopening the issue to discuss how we want to get users' table descriptors out of this state, if they're already in it. This problem (dropped/nonexistent sequence descriptors) is a special case of https://github.com/cockroachdb/cockroach/issues/50651, but it seems worth bringing up separately.

Is there anything targeted we can do to avoid this failure if we hit a dropped/nonexistent sequence while dropping a column or table? Based on a very cursory look at the code, I was wondering if we can just check for `ErrDescriptorNotFound` and not return an error in one of these places (not sure which one is the problem):

https://github.com/cockroachdb/cockroach/blob/fe7865840db53037b5ed9003aa228ba96b47e6fd/pkg/sql/drop_sequence.go#L161

https://github.com/cockroachdb/cockroach/blob/fe7865840db53037b5ed9003aa228ba96b47e6fd/pkg/sql/sequence.go#L475

**Comment by ajwerner** [comment] 2020-07-02 22:56
We've got a related and big problem which is sort of the opposite. Dropping a database which has tables which utilizes sequences corrupts, well, everything. I'll be creating another issue to track that but it's bad.

**Comment by arulajmani** [comment] 2020-07-03 02:04
I looked into the issue of dropping databases which have tables that utilize sequences and it seems like the table that uses the sequence isn't getting dropped. I don't think that problem is related to this issue though, as there is no "ownership" in that case. 

The root cause of that issue seems to be `filterCascadedTables`, which seems to be designed for table-view / view-view dependency relationships so that we don't try to unnecessarily drop views that would be dropped in other table/view's drop cascade. This doesn't seem to play well with sequences, which don't drop the tables that depend on them during cascade (aside we currently don't support cascade for sequences). 

I think we can fix this by ensuring `filterCascadedTables` skips sequences when accumulating dependencies, so that it returns both the table descriptor for the sequence that uses it and the sequence itself so that they both can be cleaned up. Feel free to assign me the issue, I'm happy to take it on!

**Comment by ajwerner** [comment] 2020-07-06 14:16
@arulajmani thanks for taking a look last week. I've written the issue up as https://github.com/cockroachdb/cockroach/issues/50997 and tentatively assigned it to you. Let me know if you run into any trouble or would like me to look.

**Comment by arulajmani** [comment] 2020-07-08 19:59
I've opened #51170 for discussion about how to get users' table descriptors out of invalid states if they're already in it. Fixes for a few issues could get users' into invalid states and I've tagged all of them in the issue above. 

Closing this.

**Closed by arulajmani** 2020-07-08 19:59 UTC
Labels: C-bug, S-1
