### ISSUE TITLE
sql: commit fails when inserting large amount of data

### ISSUE THREAD

**Issue by priitp** [cockroachdb/cockroach#14264] opened 2017-03-20 08:27 UTC
Not sure if it's already reported, but when inserting large amount of data in transaction commit fails with
 
`pq: restart transaction: retry txn "sql txn" id=67fdee7f key=/Table/0/0 rw=true pri=100.00000000 iso=SERIALIZABLE stat=PENDING epo=1 ts=1489997501.207915389,1 orig=1489997501.207915389,1 max=1489997501.707915389,0 wto=false rop=false
Error: pq: restart transaction: retry txn "sql txn" id=67fdee7f key=/Table/0/0 rw=true pri=100.00000000 iso=SERIALIZABLE stat=PENDING epo=1 ts=1489997501.207915389,1 orig=1489997501.207915389,1 max=1489997501.707915389,0 wto=false rop=false`

As for the test case, this script ([test_data.sql.zip](https://github.com/cockroachdb/cockroach/files/854198/test_data.sql.zip))

* Starts transaction.
* Creates database and table.
* Inserts around 600k rows and commits.

Another issue is that memory usage significantly grows around the failing commit, see for example node roach2 in attached logs: 
[roachx_logs.zip](https://github.com/cockroachdb/cockroach/files/854209/roachx_logs.zip)

**Comment by knz** [comment] 2017-03-20 12:25
hi @priitp! Thanks for your report.

Both aspects are fully expected:
- CockroachDB implements optimistic concurrency control: transactions try to perform the change to the database, but if another transaction touches the same data concurrently one of them will be "pushed" and will need to be restarted by the client. For more details see: https://www.cockroachlabs.com/docs/transactions.html#transaction-retries
- When a transaction writes to the database, it writes "intents" onto the database instead of modifying the data directly, so that the transaction can be more easily cancelled in case of a ROLLBACK or a push. However the node where the SQL query is received needs to "remember" which intents have been written throughout the transaction, so as to be able to remove them when the transaction is actually successfully committed. The memory growth you observe is likely related to these intents.

In order to alleviate these two issues we strongly recommend to split up your insert work in smaller batches, for example 100 rows at a time. To accelerate the insert further, you can also parallelize it across multiple client connections, for example 10 connections per node.

Does this answer your concern?

**Comment by priitp** [comment] 2017-03-20 14:05
Hi,

I'm not sure where the contention should come in this particular case, since database and table are created inside the transaction and by definition shouldn't exist for the rest of the world until this transaction commits. All the statements are sent via "cockroach sql" command as a single patch, so it should be able to to do automatic retry.

**Comment by knz** [comment] 2017-03-20 20:22
@priitp we can discuss where the retry error comes from, but for this I'll need input from some colleagues.
Meanwhile there are two things I need to communicate to clarify:
- although schema changes are atomic, for various reasons (which we can discuss separately) the newly created table will become visible from the perspective of other transactions even while your insert transaction is ongoing. It won't be available for selects, drop, alter table etc (conceptually, its creation is not complete yet until the txn has committed) however its name will be visible and it may be touched by internal processes in charge of statistics, the admin UI, etc.
- Also, do consider that creating the table and populating it in the same transaction is a very expensive way to do things in CockroachDB. The cost you are paying is to accumulate the list of all insert intents in memory until the transaction is committed. If you have enough RAM that it will fit, you're fine, but otherwise you risk running into swap or crashing the node, which in both case will result in an extremely long txn commit or rollback.

@andreimatei  can you take a look at the error message please. @danhhz thinks that the table key "/Table/0/0" is suspicious and should never be there.

**Comment by knz** [comment] 2017-03-20 21:19
(@priitp: note that I am able to reproduce your issue, we're also investigating on our side)

**Comment by knz** [comment] 2017-03-21 00:11
@priitp we are making progress on the investigation. Our preliminary findings suggest your transaction is simply "too big". The precise mechanism why the error occurs is still being investigated, but for the time being if you want to work around the issue I recommend you add the rows in smaller transactions.

Some further news from the investigation. The following scenario reproduces the issue reliably:
1. `create database test; create table test.blah(x int primary key);`
2. `begin`
3. issue X+epsilon inserts to the table (e.g. X = 512, epsilon = 8)
4. wait Y+epsilon seconds (e.g. Y = 10, epsilon = 5)
5. issue `alter table test.blah split at (...);`
6. wait Y+ epsilon seconds
7. issue X+epsilon more inserts to the table
8. `commit`

This will *always* fail with the aforementioned error.

The investigation shows the error occurs as long as X = `defaultEvictionSizeThreshold` and Y = `MinTSCacheWindow`. If the scenario above is ran with a smaller X, or a smaller Y, then the error does not reliably occur.

For example I am using the following script:

```shell
(echo "create database if not exists test; set database=test;"
 echo "create table blah(x int primary key);"
 echo "begin;";
 for ((i=0; i < 520; i++)); do 
    echo "insert into blah(x) values($i);"
 done
 sleep 15
 echo "alter table blah split at (500);"
 sleep 15
 for ((i=1000; i < 1520; i++)); do 
     echo "insert into blah(x) values($i);"
 done
 echo "commit; select count(*) from blah;") | ./cockroach sql
```

cc @andreimatei

**Comment by andreimatei** [comment] 2017-03-21 00:33
@priitp do be more concrete, it would appear that your transaction is an unfortunate combination of taking too long from start to finish (more than 10s) and also touching too many keys from a single range (more than 512). This is a known limitation of the system. But the specifics of what goes on in your case are still not perfectly clear to me.

@petermattis we've debugged this until we blamed the `timestampCache` pretty convincingly. The cache overflows and needs to evict something, and so further writes to the range in question fail the cache test.
But the interesting thing is that, in the script that Raphael posted above, the error doesn't reproduce if we don't perform a split. And by my reading of the code, a split, if anything should make the error *less likely* because we're splitting the caches (although it probably doesn't matter much, as we don't remove spans from the left cache that migrated to the right cache).
The answer maybe has something to do with when requests in these caches are "expanded" (actually inserted in the interval tree as opposed to just stored in a b-tree), but I couldn't quite figure out the smoking gun. I suspect you might just know.
Once this question is answered, I'd ask if there's anything to be improved such that the presence or absence of a split doesn't matter. And also, given that splits do seem to make this more likely, and that the bug was reported for a (presumably) data import operation, maybe there's ways to make splits reduce the size of the left-side cache after some entries are moved over to the right side.

cc @nvanbenschoten

**Comment by bdarnell** [comment] 2017-03-21 15:25
I think the reason the split matters is that we don't copy the linked list used for tracking LRU order into the RHS cache. Everything gets reinserted in key order and so the evictions may happen differently. The eviction policy in timestamp cache is a bit subtle (and I don't know if this is intentional or an accident): Whenever the cache is above 512 entries, we iterate over the LRU list and evict entries that are more than 10 seconds old until we reach one that should not be evicted. In the event that LRU order does not correspond to the age of the entry, the cache can grow to more than 512 entries. I suspect that's what's happening here; you might want to log the size of the cache when it's copied to confirm.

**Comment by petermattis** [comment] 2017-03-27 14:54
I think the eviction policy in the timestamp cache is accidental. https://github.com/cockroachdb/cockroach/issues/9423 proposes moving from a per-Replica timestamp cache to a per-Store timestamp cache. In addition to the memory benefits mentioned in that issue, it seems like a per-Store timestamp cache would avoid the problem encountered here.

**Comment by petermattis** [comment] 2017-03-30 12:50
Ok, I can reproduce this failure on master and switching to a per-Store timestamp cache fixes the problem. I have minor concerns about this approach, though. See #9423. 

Another option to fixing is to ensure that we maintain the same LRU order when copying a `TimestampCache` during a split. This would be straightforward.

**Closed** 2017-03-31 14:03 UTC
Labels: community-questions
