### ISSUE TITLE
circleci: failed tests: TestPGWireConnectionCloseReleasesLeases

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7758] opened 2016-07-11 22:47 UTC
The following test appears to have failed:

[#20127](https://circleci.com/gh/cockroachdb/cockroach/20127):

```
W160711 22:43:37.754035 kv/dist_sender.go:729  failed to invoke AdminSplit [/Table/51/0,/Min): key range /Table/51/0-/Min outside of bounds of range /Table/14-/Table/50
W160711 22:43:37.754458 kv/dist_sender.go:776  key range /Table/51/0-/Min outside of bounds of range /Table/14-/Table/50
I160711 22:43:37.757742 storage/replica_command.go:2184  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160711 22:43:37.768610 storage/log.go:84  Range Event: "split", range: 6, info: {"UpdatedDesc":{"range_id":6,"start_key":"ug==","end_key":"uw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":7,"start_key":"uw==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
==================
WARNING: DATA RACE
Write by goroutine 111:
  github.com/cockroachdb/cockroach/sql.(*tableState).release.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:688 +0x165
  github.com/cockroachdb/cockroach/sql.(*tableState).release()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:700 +0x3e9
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).Release()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:1094 +0x254
  github.com/cockroachdb/cockroach/sql.(*planner).releaseLeases()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:362 +0x170
  github.com/cockroachdb/cockroach/sql.(*Session).Finish()
--
  github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1()
      /go/src/github.com/cockroachdb/cockroach/server/server.go:370 +0x75
  github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith.func1()
      /go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:131 +0x93

Previous read by goroutine 120:
  github.com/cockroachdb/cockroach/sql.TestPGWireConnectionCloseReleasesLeases.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/pgwire_internal_test.go:81 +0xcf
  github.com/cockroachdb/cockroach/util.RetryForDuration()
      /go/src/github.com/cockroachdb/cockroach/util/testing.go:125 +0x192
  github.com/cockroachdb/cockroach/util.SucceedsSoonDepth()
      /go/src/github.com/cockroachdb/cockroach/util/testing.go:112 +0x44
  github.com/cockroachdb/cockroach/util.SucceedsSoon()
      /go/src/github.com/cockroachdb/cockroach/util/testing.go:106 +0x4b
  github.com/cockroachdb/cockroach/sql.TestPGWireConnectionCloseReleasesLeases()
      /go/src/github.com/cockroachdb/cockroach/sql/pgwire_internal_test.go:86 +0xf03
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 111 (running) created at:
  github.com/cockroachdb/cockroach/util/netutil.(*Server).ServeWith()
      /go/src/github.com/cockroachdb/cockroach/util/netutil/net.go:133 +0x397
  github.com/cockroachdb/cockroach/server.(*Server).Start.func8()
      /go/src/github.com/cockroachdb/cockroach/server/server.go:373 +0xd4
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:142 +0x5f

Goroutine 120 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  github.com/cockroachdb/cockroach/sql_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/sql/main_test.go:197 +0xf8
  main.main()
      github.com/cockroachdb/cockroach/sql/_test/_testmain.go:602 +0x20a
==================
I160711 22:43:37.781001 stopper.go:355  draining; tasks left:
--
I160711 22:46:23.684286 internal/client/db.go:474  failed batch: read at time 1468278683.681292945,7 encountered previous write with future timestamp 1468278683.681292945,7 within uncertainty interval
I160711 22:46:23.712579 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
--- PASS: TestReacquireLeaseOnRestart (0.73s)
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/sql	176.662s
I160711 22:43:20.661980 rand.go:76  Random seed: -7558385881327905234
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.03s)
=== RUN   TestFlowRegistry
--- PASS: TestFlowRegistry (0.30s)
=== RUN   TestOrderedSync
--- PASS: TestOrderedSync (0.00s)
=== RUN   TestJoinReader
I160711 22:43:21.006756 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
W160711 22:43:21.045561 gossip/gossip.go:934  not connected to cluster; use --join to specify a connected node

```
Please assign, take a look and update the issue accordingly.

**Comment by andreimatei** [comment] 2016-07-11 23:05
dupe of #7750

**Closed by andreimatei** 2016-07-11 23:05 UTC
Labels: Robot, test-failure
