### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6174] opened 2016-04-20 11:42 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/535a93151832c1042a2f66738be73b98c1a082da

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x461141 m=0

goroutine 0 [idle]:
runtime.futex(0x1169328, 0x0, 0x0, 0x0, 0x0, 0x11688d0, 0x0, 0x0, 0x40fbf4, 0x1169328, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x1169328, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x1169328)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820014000, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc82006e600)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7fff1f6508a0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcfd4b8, 0x1148d60, 0xb, 0xb, 0xb5bd01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820043f08, 0xb5bda0)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x11687e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 65 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201df1cc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201df1c8)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc8201df1c0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc820448000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc820448000, 0x1148dd8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 84 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8204263f0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 115 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8202b64b0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 98 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d4000, 0xc820664000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 99 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d4000, 0xc820136320)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 100 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f681e49bc48, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200633a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200633a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820063340, 0x0, 0x7f681e49bd30, 0xc82043e080)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82013e1b8, 0xc820045ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82013e1b8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc820109a00, 0x7f681e49aca0, 0xc82013e1b8, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d4000, 0xc820136340)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 101 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d4000, 0xc820136440)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 102 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc82015a460)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc82015a460)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 103 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201ed4d4)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201ed4d0)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201ed4d0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc8201df1c0, 0xcfdd38)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc8201df1c0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc8201df1c0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8200633b0, 0xc820432280, 0xc8206530b0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:191 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d4000, 0xc8201e8a50)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 114 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f681e49bb88, 0x72, 0xc82062c800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820688060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820688060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820688000, 0xc82062c800, 0x400, 0x400, 0x0, 0x7f681e558050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820138010, 0xc82062c800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201e8f60, 0x7f681e55fea0, 0xc820138010, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820694000, 0xcfdd17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820694000, 0xc820406000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820010cc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820010cc0, 0xc8200e4338, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f681e529438, 0xc820010cc0, 0xc8200e4338, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f681e529438, 0xc820010cc0, 0xc8200e4338, 0x9, 0x9, 0x526def4b271cb601, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8200e4338, 0x9, 0x9, 0x7f681e529438, 0xc820010cc0, 0x1e000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8200e4300, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201e9860, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8204263f0, 0xc8201e9920)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc820109a00, 0x7f681e529488, 0xc8204263f0)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820109a00, 0x7f681e529360, 0xc820694000, 0x7f681e5293c0, 0xc8200e0a50)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc820109a00, 0x7f681e55fe40, 0xc820138010)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 116 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f681e49bac8, 0x72, 0xc820174c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820686060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820686060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820686000, 0xc820174c00, 0x400, 0x400, 0x0, 0x7f681e558050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820162128, 0xc820174c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201d63c0, 0x7f681e55fea0, 0xc820162128, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82068a000, 0xcfdd17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82068a000, 0xc82021a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820290120)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820290120, 0xc820292f38, 0x9, 0x9, 0xc81fff0b18, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f681e529438, 0xc820290120, 0xc820292f38, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f681e529438, 0xc820290120, 0xc820292f38, 0x9, 0x9, 0xc820013478, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820292f38, 0x9, 0x9, 0x7f681e529438, 0xc820290120, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820292f00, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820013380, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8202b64b0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

rax    0xca
rbx    0x0
rcx    0x461143
rdx    0x0
rdi    0x1169328
rsi    0x0
rbp    0x1
rsp    0x7fff1f650700
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x6
r13    0xcfa3c1
r14    0x3
r15    0x8
rip    0x461141
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
95 runs so far, 0 failures, over 5s
204 runs so far, 0 failures, over 10s
306 runs so far, 0 failures, over 15s
416 runs so far, 0 failures, over 20s
524 runs so far, 0 failures, over 25s
631 runs so far, 0 failures, over 30s
737 runs so far, 0 failures, over 35s
839 runs so far, 0 failures, over 40s
947 runs so far, 0 failures, over 45s
1055 runs so far, 0 failures, over 50s
1166 runs so far, 0 failures, over 55s
1271 runs so far, 0 failures, over 1m0s
1378 runs so far, 0 failures, over 1m5s
1483 runs so far, 0 failures, over 1m10s
1589 runs so far, 0 failures, over 1m15s
1696 runs so far, 0 failures, over 1m20s
1805 runs so far, 0 failures, over 1m25s
1911 runs so far, 0 failures, over 1m30s
2017 runs so far, 0 failures, over 1m35s
2128 runs so far, 0 failures, over 1m40s
2237 runs so far, 0 failures, over 1m45s
2346 runs so far, 0 failures, over 1m50s
2450 runs so far, 0 failures, over 1m55s
2558 runs so far, 0 failures, over 2m0s
2663 runs so far, 0 failures, over 2m5s
2767 runs so far, 0 failures, over 2m10s
2869 runs so far, 0 failures, over 2m15s
2971 runs so far, 0 failures, over 2m20s
3078 runs so far, 0 failures, over 2m25s
3184 runs so far, 0 failures, over 2m30s
3285 runs so far, 0 failures, over 2m35s
3393 runs so far, 0 failures, over 2m40s
3494 runs so far, 0 failures, over 2m45s
3601 runs so far, 0 failures, over 2m50s
3706 runs so far, 0 failures, over 2m55s
3809 runs so far, 0 failures, over 3m0s
3913 runs so far, 0 failures, over 3m5s
4022 runs so far, 0 failures, over 3m10s
4127 runs so far, 0 failures, over 3m15s
4232 runs so far, 0 failures, over 3m20s
4337 runs so far, 0 failures, over 3m25s
4441 runs so far, 0 failures, over 3m30s
4545 runs so far, 0 failures, over 3m35s
4650 runs so far, 0 failures, over 3m40s
4756 runs so far, 0 failures, over 3m45s
4860 runs so far, 0 failures, over 3m50s
4962 runs so far, 0 failures, over 3m55s
5064 runs so far, 0 failures, over 4m0s
5164 runs so far, 0 failures, over 4m5s
5267 runs so far, 0 failures, over 4m10s
5366 runs so far, 0 failures, over 4m15s
5472 runs so far, 0 failures, over 4m20s
5577 runs so far, 0 failures, over 4m25s
5676 runs so far, 0 failures, over 4m30s
5777 runs so far, 0 failures, over 4m35s
5880 runs so far, 0 failures, over 4m40s
5976 runs so far, 0 failures, over 4m45s
6083 runs so far, 0 failures, over 4m50s
6178 runs so far, 0 failures, over 4m55s
6282 runs so far, 0 failures, over 5m0s
6381 runs so far, 0 failures, over 5m5s
6480 runs so far, 0 failures, over 5m10s
6581 runs so far, 0 failures, over 5m15s
6681 runs so far, 0 failures, over 5m20s
6778 runs so far, 0 failures, over 5m25s
6877 runs so far, 0 failures, over 5m30s
6977 runs so far, 0 failures, over 5m35s
7076 runs so far, 0 failures, over 5m40s
7177 runs so far, 0 failures, over 5m45s
7278 runs so far, 0 failures, over 5m50s
7380 runs so far, 0 failures, over 5m55s
7477 runs so far, 0 failures, over 6m0s
7570 runs so far, 0 failures, over 6m5s
7670 runs so far, 0 failures, over 6m10s
7767 runs so far, 0 failures, over 6m15s
7868 runs so far, 0 failures, over 6m20s
7967 runs so far, 0 failures, over 6m25s
8068 runs so far, 0 failures, over 6m30s
8169 runs so far, 0 failures, over 6m35s
8270 runs so far, 0 failures, over 6m40s
8368 runs so far, 0 failures, over 6m45s
8470 runs so far, 0 failures, over 6m50s
8569 runs so far, 0 failures, over 6m55s
8662 runs so far, 0 failures, over 7m0s
8763 runs so far, 0 failures, over 7m5s
8863 runs so far, 0 failures, over 7m10s
8964 runs so far, 0 failures, over 7m15s
9061 runs so far, 0 failures, over 7m20s
9162 runs so far, 0 failures, over 7m25s
9261 runs so far, 0 failures, over 7m30s
9357 runs so far, 0 failures, over 7m35s
9454 runs so far, 0 failures, over 7m40s
9555 runs so far, 0 failures, over 7m45s
9654 runs so far, 0 failures, over 7m50s
9753 runs so far, 0 failures, over 7m55s
9853 runs so far, 0 failures, over 8m0s
9948 runs so far, 0 failures, over 8m5s
10045 runs so far, 0 failures, over 8m10s
10145 runs so far, 0 failures, over 8m15s
10240 runs so far, 0 failures, over 8m20s
10336 runs so far, 0 failures, over 8m25s
10439 runs so far, 0 failures, over 8m30s
10535 runs so far, 0 failures, over 8m35s
10631 runs so far, 0 failures, over 8m40s
10728 runs so far, 0 failures, over 8m45s
10827 runs so far, 0 failures, over 8m50s
10926 runs so far, 0 failures, over 8m55s
11023 runs so far, 0 failures, over 9m0s
11121 runs so far, 0 failures, over 9m5s
11217 runs so far, 0 failures, over 9m10s
11313 runs so far, 0 failures, over 9m15s
11410 runs so far, 0 failures, over 9m20s
11506 runs so far, 0 failures, over 9m25s
11603 runs so far, 0 failures, over 9m30s
11699 runs so far, 0 failures, over 9m35s
11796 runs so far, 0 failures, over 9m40s
11889 runs so far, 0 failures, over 9m45s
11985 runs so far, 0 failures, over 9m50s
12081 runs so far, 0 failures, over 9m55s
12178 runs so far, 0 failures, over 10m0s
12267 runs so far, 0 failures, over 10m5s
12362 runs so far, 0 failures, over 10m10s
12454 runs so far, 0 failures, over 10m15s
12543 runs so far, 0 failures, over 10m20s
12637 runs so far, 0 failures, over 10m25s
12726 runs so far, 0 failures, over 10m30s
12818 runs so far, 0 failures, over 10m35s
12910 runs so far, 0 failures, over 10m40s
13002 runs so far, 0 failures, over 10m45s
13091 runs so far, 0 failures, over 10m50s
13179 runs so far, 0 failures, over 10m55s
13275 runs so far, 0 failures, over 11m0s
13366 runs so far, 0 failures, over 11m5s
13458 runs so far, 0 failures, over 11m10s
13548 runs so far, 0 failures, over 11m15s
13636 runs so far, 0 failures, over 11m20s
13726 runs so far, 0 failures, over 11m25s
13817 runs so far, 0 failures, over 11m30s
13909 runs so far, 0 failures, over 11m35s
13999 runs so far, 0 failures, over 11m40s
14090 runs so far, 0 failures, over 11m45s
14178 runs so far, 0 failures, over 11m50s
14273 runs so far, 0 failures, over 11m55s
14368 runs so far, 0 failures, over 12m0s
14462 runs so far, 0 failures, over 12m5s
14553 runs so far, 0 failures, over 12m10s
14561 runs completed, 1 failures, over 12m10s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
