### ISSUE TITLE
Support jsonb_path_query()

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#121512] opened 2024-04-01 23:01 UTC
Customer needs to construct complex JSONB Queries to search into arbitrarily nested JSON through their application code and SQL Alchemy.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-37295

**Comment by rytaft** [comment] 2024-04-03 15:03
Is this the same as #22513?

**Comment by dikshant** [comment] 2024-04-10 19:47
Yep definitely the same.

**Comment by mgartner** [comment] 2024-12-30 17:01
Closing as a duplicate of #22513.

**Closed by mgartner** 2024-12-30 17:01 UTC
Labels: C-enhancement, T-sql-queries
