### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestForbiddenDeps

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6523] opened 2016-05-05 11:42 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/9dc275b7bc4447f18538c2398083fb6bb88a4e27

Stress build found a failed test:

```
=== RUN   TestForbiddenDeps
--- FAIL: TestForbiddenDeps (0.01s)
	build.go:69: cannot find package "github.com/cockroachdb/cockroach/kv" in any of:
			/usr/local/go/src/github.com/cockroachdb/cockroach/kv (from $GOROOT)
			($GOPATH not set)
FAIL


ERROR: exit status 1
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
1 runs completed, 1 failures, over 18s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-05 22:29
Duplicate of #6489

**Closed by bdarnell** 2016-05-05 22:29 UTC
Labels: Robot, test-failure
