### ISSUE TITLE
backupccl: restore fails when issuing an AdminSplit

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#96746] opened 2023-02-07 21:19 UTC
When running a large restore we occasionally see the call to `AdminSplit` - https://github.com/cockroachdb/cockroach/blob/2f811420a1492ca547659003f193233341b7fd87/pkg/ccl/backupccl/split_and_scatter_processor.go#L99 failing with:

```
ERROR: importing 228177 ranges: splitting key /Table/134/1/200039096531068: unable to find store 83 in range r17080:/Table/134/1/2000390{55231406-60112830} [(n87,s87):6, (n46,s46):7, (n85,s85):8, next=9, gen=460, sticky=1675807501.216768519,0]
```

This error comes from the code that processes an `AdminTransferLease` - https://github.com/cockroachdb/cockroach/blob/3359d4631e5572d7431ec05d0bb5b806854fcb4c/pkg/kv/kvserver/replica_range_lease.go#L881 when the target replica is not a replica of the range. The stack points to https://github.com/cockroachdb/cockroach/blob/7de12736ece9240707a66dc4d50ea1224005203d/pkg/kv/kvserver/replica_send.go#L952 being where we invoke the transfer from, but it is still unclear where the `AdminSplit` logic sends an `AdminTransferLease`. It is worth noting that there were changes made to how we split and scatter chunks in https://github.com/cockroachdb/cockroach/pull/94805 but it is not yet clear why we are seeing more of this error than before.

Jira issue: CRDB-24307

**Comment by rhu713** [comment] 2023-02-08 20:33
Adding additional debug logging reveals that the error is from the [first error in `adminSplitWithDescriptor` ](https://github.com/cockroachdb/cockroach/blob/5a8167df51a5b4800a71f6fc4601485011d6527a/pkg/kv/kvserver/replica_command.go#L313)

**Comment by nvanbenschoten** [comment] 2023-02-08 20:47
The fact that a split is failing with an error from a lease transfer indicates that this is likely fallout from https://github.com/cockroachdb/cockroach/pull/74077. To perform a range split, ranges first need to leave joint consensus configurations. This can require a lease transfer to the VOTER_INCOMING that was just added to the range.

`unable to find store 83 in range r17080` is an interesting error to get in these cases. It likely indicates a form of race. Either store 83 was already removed from the range by this point or the leaseholder fielding the TransferLease request has not seen store 83 get added to the range. I'm not sure that the first case is possible, but the second seems to be.

If we can reproduce this, it should be possible to determine which case we are in and diagnose the issue. cc. @shralex 

@adityamaru are we seeing this in a test? Are there reproduction steps.

**Comment by adityamaru** [comment] 2023-02-08 20:54
>  are we seeing this in a test? Are there reproduction steps.

We saw this error for the first time in a TPCE 100Million restore on a 96 node cluster 😅 It is quite reproducible at that scale but we haven't seen it in any of our smaller restore roachtests yet.

**Comment by adityamaru** [comment] 2023-02-08 20:59
If it helps @rhu713 or I can run the restore with a patched binary and get you the logs though.

**Comment by shermanCRL** [comment] 2023-02-13 15:27
Hiya @nvanbenschoten just an FYI (and sorry if repetitive) that this is blocking our ability to deliver “slim manifests” to a customer, it would be great to get this resolved ASAP. Sounds like it’s in KV’s court. Please ping / ask questions to @rhu713 or @adityamaru.

**Comment by nvanbenschoten** [comment] 2023-02-21 19:20
Hi @shermanCRL, apologies for the delay. I was OOO last week. I'll raise this issue in the KV weekly today and find a path to getting it resolved.

In the meantime, @adityamaru how would you prefer we work with you to test a potential fix? I suspect that the resolution will look something like https://github.com/nvanbenschoten/cockroach/commit/e48d7ba71f53d147abebbef79c31e78b1d9d5207. Do you have an environment to test the restore with a patched binary up and running?

**Comment by dt** [comment] 2023-02-21 19:30
Aditya is OOO this week; @rhu713 has repro steps though

**Comment by rhu713** [comment] 2023-02-22 01:29
I think you should be able reproduce often on master with the 96 node setup that I was using to test restore:
```
roachprod create $CLUSTER  -n 96 --gce-machine-type n2-standard-16  --local-ssd=false  --gce-pd-volume-size=4096
```
and
```
 RESTORE FROM latest IN 'gs://rui-backup-test/tpce/23.1-filesList/10M/3?AUTH=implicit';
```

Though the reproduction seems pretty consistent, it does take tens of minutes to maybe hours for the error to occur and stop the restore.

**Comment by nvanbenschoten** [comment] 2023-03-07 14:59
I think the fix for this is https://github.com/cockroachdb/cockroach/pull/98116, but I'm not able to reproduce the issue to confirm because of https://cockroachlabs.slack.com/archives/C2C5FKPPB/p1678148317150499. I'll hold off on this issue until that's resolved.

**Closed** 2023-04-07 20:27 UTC
Labels: C-bug, A-disaster-recovery, A-kv, GA-blocker, T-kv, branch-release-23.1
