### ISSUE TITLE
Unexpected results might be related to `BIT` and `INDEX`

### ISSUE THREAD

**Issue by DerZc** [cockroachdb/cockroach#102412] opened 2023-04-27 11:07 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

Consider the following program:
```
CREATE DATABASE database1;
USE database1;
SET CLUSTER SETTING diagnostics.reporting.enabled    = false;
SET CLUSTER SETTING diagnostics.reporting.send_crash_reports = false;
SET CLUSTER SETTING sql.metrics.statement_details.plan_collection.enabled = 'off';
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = 'off';
SET CLUSTER SETTING timeseries.storage.enabled = 'off';
set experimental_enable_hash_sharded_indexes='on';

CREATE TABLE t0 (c0 VARBIT(55)[] AS (ARRAY[B'1111111111111111111111111111111111110010101010100100111000111001', B'1']) STORED);

CREATE UNIQUE INDEX ON t0(rowid DESC, c0 DESC);

INSERT INTO t0 (rowid) VALUES (1488128305);
 
SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN ((VALUES (1488128305)))));

SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN (SELECT t0.rowid FROM t0 )));
```

There is only one value in `t0.c0`, so this two `SELECT` queries should be equivalent and have the same results. As `((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))` always return `TRUE`, so the results of these two queries should be `1488128305`.

But I get the following results:
```
> SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN ((VALUES (1488128305)))));
  rowid
---------
(0 rows)

Time: 1ms

> SELECT t0.rowid FROM t0 WHERE (((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))AND((t0.rowid) IN (SELECT t0.rowid FROM t0 )));
    rowid
--------------
  1488128305
(1 row)

Time: 1ms
```
The first query returns an empty result, which is unexpected.

I tried three methods that can avoid this bug. The first is to remove the `INDEX`, then this bug can not reproduce. The second is to modify the value `1111111111111111111111111111111111110010101010100100111000111001` to a smaller one, or modify the type of `t0.c0` to `INT`. The third is remove `((NOT ((t0.c0) NOT BETWEEN (t0.c0) AND t0.c0)))`.

**To Reproduce**

I build CockroachDB from the latest commit version https://github.com/cockroachdb/cockroach/commit/5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039, and run it in a single machine. I run this program in CLI.

**Expected behavior**
The first query has correct result.

**Environment:**
 - CockroachDB version https://github.com/cockroachdb/cockroach/commit/5b44c4fd6d97dc3a75e786fed24f47ad8bcf9039
 - Server OS: [Ubuntu 22.04]
 - Client app [CLI, JDBC]

Jira issue: CRDB-27431

**Comment by mgartner** [comment] 2023-04-27 13:45
Thanks for the bug report!

This looks like a regression. It does not reproduce on v22.2.6 nor v22.1.13. I'm marking as a GA-blocker for now until we can investigate and figure out the impact of this.

**Comment by mgartner** [comment] 2023-04-27 14:06
Here's a reduced reproduction:

```sql
CREATE TABLE t (
  k INT PRIMARY KEY,
  b VARBIT(1)[] AS (ARRAY[B'11', B'1']) STORED,
  UNIQUE INDEX (k, b)
);

INSERT INTO t (k) VALUES (1);
 
-- Returns 0 rows.
SELECT k FROM t WHERE (b BETWEEN b AND b) AND k = 1;

-- Returns 1 row.
SELECT k FROM t WHERE (b BETWEEN b AND b) AND k IN (SELECT k FROM t);
```

**Closed** 2023-05-05 16:27 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries, v23.1.2
