### ISSUE TITLE
release: 20.2.0-alpha.2

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#51035] opened 2020-07-06 22:56 UTC
Candidate SHA: `d3119926d33d808c6384cf3e99a7f7435f395489` (d3119926d33d808c6384cf3e99a7f7435f395489)
Tag: [`provisional_202007220233_v20.2.0-alpha.2`](https://github.com/cockroachdb/cockroach/releases/tag/provisional_202007220233_v20.2.0-alpha.2)

Deployment status: Qualifying
Qualification Suite: (passed ✅) [Tests passed: 1, ignored: 291](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_ReleaseQualification&tab=buildTypeStatusDiv&branch_Cockroach=provisional_202007220233_v20.2.0-alpha.2)
Nightly Suite: (completed ✅) [Tests failed: 24 (5 new), passed: 249, ignored: 19](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_NightlySuite&tab=buildTypeStatusDiv&branch_Cockroach_Nightlies=provisional_202007220233_v20.2.0-alpha.2)
 
Admin UI for Qualification Clusters:

|Time|20.2.0-alpha.1|20.2.0-alpha.2|
|-|-|-|
|7/21, 11:45p|[alpha.1](http://celia-release-2-v2020-alpha1-59b79642-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster?start=1595368901&end=1595390501)|[alpha.2](http://celia-release-2-v2020-alpha2-d3119926-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster?start=1595368912&end=1595390512)|

[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: Mon 7/27 ~Thur 7/16, Thur 7/9, Mon 7/6~ (usually a week before the release)
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA) 
  - [x] fill in `Candidate SHA` above
  - [x] email thread on releases@
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA) 
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [ ] Ack security@ on the generated Stackdriver Alert to confirm these writes were part of a planned release (Just reply on the email received alert email acking that this was part of the release process)
 
[Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)
- [x] [Check binaries]
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Verify-node-crash-reports-appear-in-sentry.io)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in all WIP elements above (Nightly Suite, Admin UI, etc.)
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RoachtestFailureSignoff)
 
- [x] [Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date. Do not proceed below until the release date.
 
Release date: `WIP fill in date: usually Monday WIP`
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [x] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.Tagtherelease)
- [x] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
- [ ] If applicable, [update the map that roachtests use to map a version to a previous version, to reference the newly tagged version](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L1145)
 
- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
 
- For production or stable releases
  - [ ] Announce version to the [registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
 
- [ ] Update docs
- [ ] External communications for release
 
Cleanup:
- [ ] Clean up provisional tag from repository
- [x] Destroy roachprod clusters

**Comment by celiala** [comment] 2020-07-07 22:02
[Nightly Suite](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_NightlySuite)

![image](https://user-images.githubusercontent.com/3051672/86848438-045e7b80-c07c-11ea-9d1e-bed9096f9a2b.png)

**Comment by celiala** [comment] 2020-07-07 22:04
[Release Qualification build](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_ReleaseQualification)

![image](https://user-images.githubusercontent.com/3051672/86848593-4982ad80-c07c-11ea-882f-65e2db76c772.png)

![image](https://user-images.githubusercontent.com/3051672/86848587-438ccc80-c07c-11ea-99b0-6820cceb6397.png)

**Comment by celiala** [comment] 2020-07-08 14:56
A release blocker for the alpha has come up in https://github.com/cockroachdb/cockroach/issues/50687.

We're going to need to cherry pick the fix: https://github.com/cockroachdb/cockroach/pull/51143

**Comment by celiala** [comment] 2020-07-15 04:50
# Test Failures

## Roachtest Nightly - GCE
(Tests failed: 27 (8 new), passed: 245, ignored: 18)

Failures: 
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly/2080704

### [appdev]

- [ ] django | [appdev]
- [ ] pgjdbc | [appdev]
- [ ] psycopg | [appdev]

### [bulkio]
- [ ] backup2TB/n10cpu4 | [bulkio]
- [ ] dump-backwards-compatibility | [bulkio]
- [ ] import/tpcc/warehouses=1000/nodes=32 | [bulkio]

### [kv]

- [ ] kv50/rangelookups/relocate/nodes=8 | [kv]
- [ ] scaledata/jobcoordinator/nodes=6 | [kv]
- [ ] tpcc/interleaved/nodes=3/cpu=16/w=500 | [kv]
- [ ] tpcc/mixed-headroom/n5cpu16 | [kv]
- [ ] drop/tpcc/w=100,nodes=9 | [kv]
- [ ] follower-reads/nodes=3 | [kv]
- [ ] kv/contention/nodes=4 | [kv]
- [ ] kv/splits/nodes=3/quiesce=true | [kv]
- [ ] scaledata/filesystem_simulator/nodes=3 | [kv]
- [ ] scaledata/filesystem_simulator/nodes=6 | [kv]
- [ ] tpccbench/nodes=6/cpu=16/multi-az | [kv]
- [ ] tpccbench/nodes=9/cpu=4/chaos/partition | [kv]
- [ ] tpccbench/nodes=9/cpu=4/multi-region | [kv]

### [sql-exec]

- [ ] scrub/index-only/tpcc/w=100 | [sql-exec]
- [ ] sqlsmith/setup=empty/setting=no-mutations | [sql-exec]
- [ ] sqlsmith/setup=seed/setting=no-ddl | [sql-exec]
- [ ] scrub/all-checks/tpcc/w=100 | [sql-exec]
- [ ] sqlsmith/setup=seed/setting=no-mutations | [sql-exec]

### [sql-schema]

- [ ] schemachange/index/tpcc/w=100 | [sql-schema]
- [ ] schemachange/during/tpcc | [sql-schema]
- [ ] schemachange/index/tpcc/w=1000 | [sql-schema]

**Comment by ajwerner** [comment] 2020-07-15 14:44
All of the schemachange test failures seem to be due to a timeout in the data import.
`schemachange/index/tpcc/w=100 (1) - 	test_runner.go:804: test timed out (45m0s)` - while running `roachprod run teamcity-2080704-1594412253-72-n5cpu4:5 -- ./workload fixtures load tpcc --warehouses=100  {pgurl:1}`  and the same goes for `schemachange/during/tpcc` and `schemachange/index/tpcc/w=1000`

**Comment by irfansharif** [comment] 2020-07-15 14:47
Checked off the KV failures. We're actively working on 
- #50865 (splits bug, being investigated by @aayushshah15)
- #51028 (txnwait queue getting clogged up, being investigated by @nvanbenschoten), and 
- #50262 (follower reads bug, being investigated by @andreimatei)

There are a bunch of other "KV roachtests" that are failing due to wedged imports. I've reallocated them to bulk IO for investigation (I've assigned a bunch to @dt).

**Comment by rafiss** [comment] 2020-07-15 15:30
Signed off on AppDev. Django and psycopg failures were because of parsing logic in the test that has since been fixed. PGJDBC has some flaky tests that we are figuring out how to ignore or stabilize.

**Comment by lucy-zhang** [comment] 2020-07-15 17:00
Checking off the two `schemachange/index/tpcc` failures for reasons stated above. I'm taking another look at `schemachange/during/tpcc`.

**Comment by rohany** [comment] 2020-07-15 17:42
Signing off on the RSG tests -- opened two issues to track the failures (https://github.com/cockroachdb/cockroach/issues/51472, https://github.com/cockroachdb/cockroach/issues/51473) but they shouldn't block the release.

**Comment by rohany** [comment] 2020-07-15 18:00
Signing off on the SQLSmith failures. Opened some issues to track the individual failures but they shouldn't block the release.

**Comment by rohany** [comment] 2020-07-15 18:01
The scrub failures have timed out due to the same reasons as the schemachange tests.

**Comment by celiala** [comment] 2020-07-23 01:27
### Roachtest Nightly - GCE
(Tests failed: 24 (5 new), passed: 249, ignored: 19)
https://teamcity.cockroachdb.com/viewLog.html?buildId=2107811&buildTypeId=Cockroach_Nightlies_WorkloadNightly

#### [appdev]
- [ ] django | [appdev]
- [ ] hibernate | [appdev]
- [ ] pgjdbc | [appdev]

#### [bulkio]
- [ ] dump-backwards-compatibility | [bulkio]
- [ ] jobs/mixed-versions | [bulkio]

#### [kv]
- [ ] acceptance/cli/node-status | [kv]
- [ ] acceptance/multitenant | [kv]
- [ ] autoupgrade | [kv]
- [ ] decommission-recommission | [kv]
- [ ] decommission/mixed-versions | [kv]
- [ ] decommission/nodes=4/duration=1h0m0s | [kv]
- [ ] follower-reads/nodes=3 | [kv]
- [ ] gossip/chaos/nodes=9 | [kv]
- [ ] scaledata/filesystem-simulator/nodes=6 | [kv]
- [ ] scaledata/job-coordinator/nodes=3 | [kv]
- [ ] scaledata/job-coordinator/nodes=6 | [kv]
- [ ] transfer-leases/drain | [kv]
- [ ] transfer-leases/quit | [kv]
- [ ] transfer-leases/signal | [kv]

#### [partitioning]
- [ ] roachmart/partition=true | [partitioning]

#### [storage]
- [ ] clearrange/checks=false | [storage]
- [ ] clearrange/checks=true | [storage]

### Random Syntax Tests
https://teamcity.cockroachdb.com/viewLog.html?buildId=2107812&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

#### [sql-exec]

- [ ] TestRandomSyntaxGeneration
- [ ] TestRandomSyntaxFunctions

#### Other tests

| Test | Message |
| -|-|
|[SQLite Logic Tests](https://teamcity.cockroachdb.com/viewLog.html?buildId=2107795&buildTypeId=Cockroach_SqlLogicTests)|Process exited with code 2 (Step: Command Line)  
|[Compose Tests](https://teamcity.cockroachdb.com/viewLog.html?buildId=2107813&buildTypeId=Cockroach_Nightlies_ComposeTests&tab=buildResultsDiv&branch_Cockroach_Nightlies=provisional_202007220233_v20.2.0-alpha.2)|Process exited with code 1 (Step: Command Line)|
|[SQLite Logic Test High VModule Nightly](https://teamcity.cockroachdb.com/viewLog.html?buildId=2107810&buildTypeId=Cockroach_Nightlies_SqlLogicTestHighVModuleNightly&tab=buildResultsDiv&branch_Cockroach_Nightlies=provisional_202007220233_v20.2.0-alpha.2)|Process exited with code 1 (Step: make testlogic TESTFLAGS='--vmodule=*=10 -show-sql -test.v' (Command Line))|

**Comment by knz** [comment] 2020-07-23 11:46
The " gossip/chaos/nodes=9 | [kv]" failure is #51721.

I believe it denotes a real bug but it's not new. I would tend to think it shouldn't block the release. @nvanbenschoten @andreimatei what do you think?

**Comment by knz** [comment] 2020-07-23 11:48
The Random syntax generation tests are finding two real bugs. However I don't think they are real blockers. Signing off on them.

**Comment by rafiss** [comment] 2020-07-23 14:37
Signed off on appdev tests. They aren't new problems.

**Comment by nvanbenschoten** [comment] 2020-07-23 14:48
`acceptance/multitenant` is missing the --tenant-addr flag, which is due to the mismatch between the roachtest SHA and the CRDB SHA. That's not a blocker so signing off.

`follower-reads/nodes=3` looks like a real issue. We see `fewer than 2 follower reads occurred: saw [0 2 1] before and [0 3 1] after`. @andreimatei and @aayushshah15 have been working in this area recently. They'll likely be interested in this issue.

**Comment by nvanbenschoten** [comment] 2020-07-23 15:02
> The " gossip/chaos/nodes=9 | [kv]" failure is #51721.
>
> I believe it denotes a real bug but it's not new. I would tend to think it shouldn't block the release. @nvanbenschoten @andreimatei what do you think?

We see that nodes are getting different IDs from their roachprod IDs (see https://github.com/cockroachdb/cockroach/issues/51721#issuecomment-663054708). It's unclear whether this is a regression inside cockroach or outside cockroach. We'll need to figure that out before we make a determination on whether this is a blocker or not.

**Comment by irfansharif** [comment] 2020-07-23 15:06
It's not, that's me again. https://github.com/cockroachdb/cockroach/issues/51497#issuecomment-662242352, fixed by https://github.com/cockroachdb/cockroach/pull/51790.

**Comment by irfansharif** [comment] 2020-07-24 16:05
Signing off the clearrange checks, looks to be infra-flakes: https://github.com/cockroachdb/cockroach/issues/51716, https://github.com/cockroachdb/cockroach/issues/51711.

**Comment by irfansharif** [comment] 2020-07-24 21:19
Signed off the rest of the KV tests. The follower reads roachtest has been flaky for some time now, and still under investigation (so we shouldn't hold the release up). The autoupgrade test is another victim of `roachprod --sequential` being broken: https://github.com/cockroachdb/cockroach/issues/51776#issuecomment-663737950.

**Comment by solongordon** [comment] 2020-07-27 15:16
Signed off on `roachmart/partition=true`. Looks like a timing issue on the test side and the test has passed in subsequent builds on master.

**Closed** 2020-08-14 21:18 UTC
