### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestBaseQueuePurgatory

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6557] opened 2016-05-06 11:37 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f6ed931f3edc5da0508c4bf15c1413b544196a14

Stress build found a failed test:

```
=== RUN   TestBaseQueuePurgatory
W160506 06:51:03.102988 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160506 06:51:03.104834 storage/queue.go:496  [test] purgatory is now empty
--- FAIL: TestBaseQueuePurgatory (0.01s)
	queue_test.go:530: expected purgatory size of 10; got 9
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
22 runs so far, 0 failures, over 55s
31 runs so far, 0 failures, over 1m0s
31 runs so far, 0 failures, over 1m5s
31 runs so far, 0 failures, over 1m10s
31 runs so far, 0 failures, over 1m15s
34 runs so far, 0 failures, over 1m20s
46 runs so far, 0 failures, over 1m25s
46 runs so far, 0 failures, over 1m30s
46 runs so far, 0 failures, over 1m35s
46 runs so far, 0 failures, over 1m40s
49 runs so far, 0 failures, over 1m45s
61 runs so far, 0 failures, over 1m50s
61 runs so far, 0 failures, over 1m55s
62 runs so far, 0 failures, over 2m0s
62 runs so far, 0 failures, over 2m5s
65 runs so far, 0 failures, over 2m10s
74 runs so far, 0 failures, over 2m15s
75 runs so far, 0 failures, over 2m20s
75 runs so far, 0 failures, over 2m25s
75 runs so far, 0 failures, over 2m30s
79 runs so far, 0 failures, over 2m35s
88 runs so far, 0 failures, over 2m40s
88 runs so far, 0 failures, over 2m45s
89 runs so far, 0 failures, over 2m50s
89 runs so far, 0 failures, over 2m55s
93 runs so far, 0 failures, over 3m0s
100 runs so far, 0 failures, over 3m5s
100 runs so far, 0 failures, over 3m10s
103 runs so far, 0 failures, over 3m15s
103 runs so far, 0 failures, over 3m20s
107 runs so far, 0 failures, over 3m25s
114 runs so far, 0 failures, over 3m30s
114 runs so far, 0 failures, over 3m35s
117 runs so far, 0 failures, over 3m40s
118 runs so far, 0 failures, over 3m45s
121 runs so far, 0 failures, over 3m50s
127 runs so far, 0 failures, over 3m55s
127 runs so far, 0 failures, over 4m0s
131 runs so far, 0 failures, over 4m5s
133 runs so far, 0 failures, over 4m10s
135 runs so far, 0 failures, over 4m15s
138 runs completed, 1 failures, over 4m18s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:52
Duplicate of #6342

**Closed by bdarnell** 2016-05-21 15:52 UTC
Labels: Robot, test-failure
