### ISSUE TITLE
sql: DELETE does not complete for 8000 rows, but does for 2000-5000

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31793] opened 2018-10-24 16:36 UTC
**Describe the problem**

DELETE on a table completes in seconds for 2000-5000 rows, but hangs (or perhaps completes in minutes) for 8000.

@bdarnell suggests perhaps `max_refresh_span_bytes` is involved, but no investigation has shown this yet.

**To Reproduce**

TBD

**Expected behavior**

DELETE latency proportional to number of rows deleted.

**Environment:**

2.1 on Linux

**Additional context**

Reported by customer K

**Comment by knz** [comment] 2018-10-24 16:37
@awoods187 could you approach the user and ask them to provide repro details suitable for publication on github so we have something to work with.

**Comment by awoods187** [comment] 2018-10-24 16:57
@andy-kimball can you comment here? Would like to see if we can fill in on our own before reaching out

**Comment by andy-kimball** [comment] 2018-10-25 04:02
I believe @nvanbenschoten located the root cause for this and will be making a change to the default value for `kv.closed_timestamp.target_duration`. Nathan, if that's correct, can your team take over this issue and close it down once fix is in?

**Comment by nvanbenschoten** [comment] 2018-10-25 14:02
Yeah, closing now that https://github.com/cockroachdb/cockroach/pull/31841 is merged.

**Closed by nvanbenschoten** 2018-10-25 14:02 UTC
Labels: A-sql-mutations, C-investigation
