### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6115] opened 2016-04-18 10:55 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/0958303ee7be3dd3fe7281c7008f520c53c8ebbd

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x4612c9 m=0

goroutine 0 [idle]:
runtime.epollwait(0x7fff00000004, 0x7fff370baed8, 0xffffffff00000080, 0x1, 0x1ffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:440 +0x19
runtime.netpoll(0x1160b01, 0x0)
	/usr/local/go/src/runtime/netpoll_epoll.go:67 +0x94
runtime.findrunnable(0xc820016a00, 0x0)
	/usr/local/go/src/runtime/proc.go:1955 +0x62c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.goexit0(0xc820146600)
	/usr/local/go/src/runtime/proc.go:2207 +0x1f9
runtime.mcall(0x7fff370bb5f0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcf75a8, 0x1141060, 0xb, 0xb, 0xb57301)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820043f08, 0xb57320)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 14 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201ef08c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201ef088)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc8201ef080, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc820392000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc820392000, 0x11410d8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 34 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1160a60)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:994 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:595 +0x8a

goroutine 29 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820489d10)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 30 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f88b80e2618, 0x72, 0xc82006a800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82025d870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82025d870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82025d810, 0xc82006a800, 0x400, 0x400, 0x0, 0x7f88b80a1028, 0xc82007c080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820154068, 0xc82006a800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201f8f60, 0x7f88b80e2a50, 0xc820154068, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820242000, 0xcf7e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820242000, 0xc82048a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc82007afc0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82007afc0, 0xc82044a938, 0x9, 0x9, 0xc82007b618, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f88b8030918, 0xc82007afc0, 0xc82044a938, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f88b8030918, 0xc82007afc0, 0xc82044a938, 0x9, 0x9, 0xc82016e5a8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82044a938, 0x9, 0x9, 0x7f88b8030918, 0xc82007afc0, 0x20000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82044a900, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201fefc0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc820489d10)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 51 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201e6000, 0xc82000a4c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 52 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201e6000, 0xc8201f15a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 53 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f88b80e26d8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201353a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201353a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820135340, 0x0, 0x7f88b802c480, 0xc820230180)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201721e0, 0xc820046ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8201721e0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc8200aba00, 0x7f88b80e1730, 0xc8201721e0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201e6000, 0xc8201f15c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 54 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201e6000, 0xc8201f16c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 55 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201922a0)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201922a0)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 56 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201ff7d4)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201ff7d0)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201ff7d0, 0x1160680)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc8201ef080, 0xcf7e28)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc8201ef080, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc8201ef080, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8201353b0, 0xc820260280, 0xc820642260, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:175 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:157 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201e6000, 0xc8201f8e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f88b80e2558, 0x72, 0xc820145400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820240060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820240060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820240000, 0xc820145400, 0x400, 0x400, 0x0, 0x7f88b80a1028, 0xc82007c080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820088018, 0xc820145400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820194540, 0x7f88b80e2a50, 0xc820088018, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820462000, 0xcf7e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820462000, 0xc820496000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820010360)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820010360, 0xc82042c038, 0x9, 0x9, 0x19, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f88b8030918, 0xc820010360, 0xc82042c038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f88b8030918, 0xc820010360, 0xc82042c038, 0x9, 0x9, 0xc8203b3a48, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82042c038, 0x9, 0x9, 0x7f88b8030918, 0xc820010360, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82042c000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201fa330, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820236000, 0xc8201fa3f0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc8200aba00, 0x7f88b8030968, 0xc820236000)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc8200aba00, 0x7f88b8030840, 0xc820462000, 0x7f88b80308a0, 0xc8202562c0)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc8200aba00, 0x7f88b80e29f0, 0xc820088018)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 16 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820236000)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x4612c9
rdx    0x80
rdi    0x4
rsi    0x7fff370baed8
rbp    0x11614a0
rsp    0x7fff370bae98
r8     0x11614a0
r9     0xc820020000
r10    0xffffffff
r11    0x246
r12    0xc820236000
r13    0xa
r14    0xbc91a0
r15    0x8
rip    0x4612c9
rflags 0x246
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
103 runs so far, 0 failures, over 5s
215 runs so far, 0 failures, over 10s
327 runs so far, 0 failures, over 15s
439 runs so far, 0 failures, over 20s
550 runs so far, 0 failures, over 25s
664 runs so far, 0 failures, over 30s
771 runs so far, 0 failures, over 35s
882 runs so far, 0 failures, over 40s
990 runs so far, 0 failures, over 45s
1100 runs so far, 0 failures, over 50s
1209 runs so far, 0 failures, over 55s
1322 runs so far, 0 failures, over 1m0s
1430 runs so far, 0 failures, over 1m5s
1536 runs so far, 0 failures, over 1m10s
1649 runs so far, 0 failures, over 1m15s
1760 runs so far, 0 failures, over 1m20s
1867 runs so far, 0 failures, over 1m25s
1975 runs so far, 0 failures, over 1m30s
2084 runs so far, 0 failures, over 1m35s
2186 runs so far, 0 failures, over 1m40s
2291 runs so far, 0 failures, over 1m45s
2398 runs so far, 0 failures, over 1m50s
2506 runs so far, 0 failures, over 1m55s
2613 runs so far, 0 failures, over 2m0s
2717 runs so far, 0 failures, over 2m5s
2822 runs so far, 0 failures, over 2m10s
2929 runs so far, 0 failures, over 2m15s
3031 runs so far, 0 failures, over 2m20s
3143 runs so far, 0 failures, over 2m25s
3245 runs so far, 0 failures, over 2m30s
3353 runs so far, 0 failures, over 2m35s
3460 runs so far, 0 failures, over 2m40s
3565 runs so far, 0 failures, over 2m45s
3670 runs so far, 0 failures, over 2m50s
3772 runs so far, 0 failures, over 2m55s
3876 runs so far, 0 failures, over 3m0s
3981 runs so far, 0 failures, over 3m5s
4080 runs so far, 0 failures, over 3m10s
4182 runs so far, 0 failures, over 3m15s
4284 runs so far, 0 failures, over 3m20s
4385 runs so far, 0 failures, over 3m25s
4485 runs so far, 0 failures, over 3m30s
4588 runs so far, 0 failures, over 3m35s
4687 runs so far, 0 failures, over 3m40s
4785 runs so far, 0 failures, over 3m45s
4880 runs so far, 0 failures, over 3m50s
4982 runs so far, 0 failures, over 3m55s
5076 runs so far, 0 failures, over 4m0s
5177 runs so far, 0 failures, over 4m5s
5277 runs so far, 0 failures, over 4m10s
5372 runs so far, 0 failures, over 4m15s
5469 runs so far, 0 failures, over 4m20s
5566 runs so far, 0 failures, over 4m25s
5664 runs so far, 0 failures, over 4m30s
5765 runs so far, 0 failures, over 4m35s
5862 runs so far, 0 failures, over 4m40s
5961 runs so far, 0 failures, over 4m45s
6062 runs so far, 0 failures, over 4m50s
6165 runs so far, 0 failures, over 4m55s
6265 runs so far, 0 failures, over 5m0s
6361 runs so far, 0 failures, over 5m5s
6458 runs so far, 0 failures, over 5m10s
6557 runs so far, 0 failures, over 5m15s
6655 runs so far, 0 failures, over 5m20s
6756 runs so far, 0 failures, over 5m25s
6849 runs so far, 0 failures, over 5m30s
6948 runs so far, 0 failures, over 5m35s
7048 runs so far, 0 failures, over 5m40s
7146 runs so far, 0 failures, over 5m45s
7245 runs so far, 0 failures, over 5m50s
7338 runs so far, 0 failures, over 5m55s
7439 runs so far, 0 failures, over 6m0s
7536 runs so far, 0 failures, over 6m5s
7632 runs so far, 0 failures, over 6m10s
7732 runs so far, 0 failures, over 6m15s
7830 runs so far, 0 failures, over 6m20s
7928 runs so far, 0 failures, over 6m25s
8027 runs so far, 0 failures, over 6m30s
8129 runs so far, 0 failures, over 6m35s
8227 runs so far, 0 failures, over 6m40s
8326 runs so far, 0 failures, over 6m45s
8429 runs so far, 0 failures, over 6m50s
8524 runs so far, 0 failures, over 6m55s
8622 runs so far, 0 failures, over 7m0s
8719 runs so far, 0 failures, over 7m5s
8813 runs so far, 0 failures, over 7m10s
8915 runs so far, 0 failures, over 7m15s
9011 runs so far, 0 failures, over 7m20s
9111 runs so far, 0 failures, over 7m25s
9207 runs so far, 0 failures, over 7m30s
9310 runs so far, 0 failures, over 7m35s
9412 runs so far, 0 failures, over 7m40s
9513 runs so far, 0 failures, over 7m45s
9611 runs so far, 0 failures, over 7m50s
9710 runs so far, 0 failures, over 7m55s
9808 runs so far, 0 failures, over 8m0s
9905 runs so far, 0 failures, over 8m5s
10004 runs so far, 0 failures, over 8m10s
10100 runs so far, 0 failures, over 8m15s
10198 runs so far, 0 failures, over 8m20s
10300 runs so far, 0 failures, over 8m25s
10397 runs so far, 0 failures, over 8m30s
10493 runs so far, 0 failures, over 8m35s
10592 runs so far, 0 failures, over 8m40s
10692 runs so far, 0 failures, over 8m45s
10784 runs so far, 0 failures, over 8m50s
10880 runs so far, 0 failures, over 8m55s
10974 runs so far, 0 failures, over 9m0s
11073 runs so far, 0 failures, over 9m5s
11164 runs so far, 0 failures, over 9m10s
11259 runs so far, 0 failures, over 9m15s
11352 runs so far, 0 failures, over 9m20s
11452 runs so far, 0 failures, over 9m25s
11550 runs so far, 0 failures, over 9m30s
11646 runs so far, 0 failures, over 9m35s
11739 runs so far, 0 failures, over 9m40s
11838 runs so far, 0 failures, over 9m45s
11936 runs so far, 0 failures, over 9m50s
12031 runs so far, 0 failures, over 9m55s
12126 runs so far, 0 failures, over 10m0s
12224 runs so far, 0 failures, over 10m5s
12317 runs so far, 0 failures, over 10m10s
12413 runs so far, 0 failures, over 10m15s
12510 runs so far, 0 failures, over 10m20s
12605 runs so far, 0 failures, over 10m25s
12695 runs so far, 0 failures, over 10m30s
12761 runs completed, 1 failures, over 10m33s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
