### ISSUE TITLE
ui: jobs page renders É character on div overflow in Safari

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#44837] opened 2020-02-06 21:45 UTC
**Describe the problem**

The jobs page rendered an odd character when the job description overflowed the container.

**To Reproduce**

Run some jobs with long names (say, a `RESTORE TABLE FROM ...`) and look at them on the main jobs page using Safari

**Expected behavior**
The `...` should be rendered when the div runs over but instead we get an É

**Additional data / screenshots**
 
<img width="237" alt="Screen Shot 2020-02-06 at 4 44 53 PM" src="https://user-images.githubusercontent.com/986307/73981338-07ecab80-4900-11ea-9f31-7c5ddf825e4f.png">

**Comment by koorosh** [comment] 2020-03-18 13:45
Could not reproduce on the latest build

Probably fixed with Jobs table redesign

Validated on b5f030223f

<img width="762" alt="Screenshot 2020-03-18 at 15 43 44" src="https://user-images.githubusercontent.com/3106437/76966948-678e9b80-692f-11ea-8bd4-cecef0a54bb2.png">

**Closed by koorosh** 2020-03-18 13:45 UTC
Labels: A-webui
