### ISSUE TITLE
Syntax error for multi-valued comparison and COLLATE

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#45142] opened 2020-02-17 14:12 UTC
Consider the following statements:

```sql
CREATE TABLE t0(c0 STRING COLLATE en);
SELECT * FROM t0 WHERE t0.c0 < SOME ('' COLLATE en, CASE WHEN true THEN NULL END); -- ERROR: at or near ")": syntax error
```
Unexpectedly, the SELECT results in the following error:

```
ERROR: at or near ")": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
SET ROW (@1 < ANY ('' COLLATE en, NULL::STRING COLLATE ))
                                                       ^
HINT: try \h SET SESSION
```
Replacing `CASE WHEN true THEN NULL END` by `NULL` avoids this error. I found this error based on commit `bb14400cdd1397f47c3781b4830199f169cef497`.

**Comment by knz** [comment] 2020-02-17 16:02
cc @asubiotto @yuzefovich for triage. Looks like the traditional distsql expression serialization bug.

**Comment by yuzefovich** [comment] 2020-02-17 16:55
It might be a duplicate of #44137

**Comment by yuzefovich** [comment] 2020-02-18 01:16
On a quick glance it seems to be different from #44137 (at least the same fix doesn't work here).

**Comment by rafiss** [comment] 2021-06-08 16:17
@yuzefovich this seems more like an issue with DistSQL serialization -- do you / SQL Queries have more knowledge about how that works? I don't think the SQL Experience team has worked on it much.

**Comment by yuzefovich** [comment] 2021-06-10 20:56
Never mind, it hasn't been fixed yet.

**Closed** 2021-06-16 01:14 UTC
Labels: A-sql-execution, C-bug, O-community
