### ISSUE TITLE
EXPERIMENTAL CHANGEFEED with error: ‹*tree.CreateChangefeed not implemented in the new schema changer

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#95053] opened 2023-01-11 11:51 UTC
**Describe the problem**
Encounter this while investigating https://github.com/cockroachdb/cockroach/issues/95044,

```
...
... # EXPERIMENTAL CHANGEFEED DATA
attempting to cancel query...
(error encountered after some results were delivered)
```

```
I230111 11:40:47.225138 2430 sql/schemachanger/scbuild/build.go:39 ⋮ [n1,client=127.0.0.1:49476,user=root] 993  building declarative schema change targets for EXPERIMENTAL CHANGEFEED
W230111 11:40:47.225252 2430 runtime/panic.go:884 ⋮ [n1,client=127.0.0.1:49476,user=root] 994  failed building declarative schema change targets for EXPERIMENTAL CHANGEFEED with error: ‹*tree.CreateChangefeed not implemented in the new schema changer›
I230111 11:40:47.225550 33443 1@ccl/changefeedccl/changefeed_stmt.go:854 ⋮ [n1,client=127.0.0.1:49476,user=root] 995  changefeed planning to connect to destination 
```

What did you do? Describe in your own words.
(create a quick error just for tracking - will comeback for more detail if needed) `cockroachdb` `v22.2.2`

Jira issue: CRDB-23296

**Comment by miretskiy** [comment] 2023-01-11 14:04
I've seen this error in many places, not just with create changefeed -- which clearly doesn't implement schema change.
Not sure if there is anything specific changefeed needs to do .. or it just might be working as intended.

**Comment by amruss** [comment] 2023-01-11 19:43
Punting to SQL Schema @ajwerner

**Comment by ajwerner** [comment] 2023-01-12 15:53
What error was actually delivered? I don't think that that warning bubbles up.

**Comment by ajwerner** [comment] 2023-01-12 15:57
Indeed I find we do log that error but it has nothing to do with a changefeed not working.

**Comment by ajwerner** [comment] 2023-01-12 19:30
I'm going to close this issue -- the log message has now been downgraded to INFO. When you determine what error was hit, file a new issue describing it.

**Closed by ajwerner** 2023-01-12 19:30 UTC
Labels: C-bug, O-community, A-cdc, X-blathers-triaged, T-cdc, T-sql-schema
