### ISSUE TITLE
release: v19.2.10

### ISSUE THREAD

**Issue by celiala** [cockroachdb/cockroach#52841] opened 2020-08-14 21:22 UTC
#### Release Candidate Overview:

Candidate SHA: `5a1eb98cf9e0139f58b138f2743a3e0f55408b2f` (5a1eb98cf9e0139f58b138f2743a3e0f55408b2f, https://github.com/cockroachdb/cockroach/releases/tag/provisional_202008191705_v19.2.10)
Deployment status: Qualifying
Qualification Suite: [#166 - started 8/19, 4:30p](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_ReleaseQualification&branch_Cockroach=provisional_202008191705_v19.2.10&tab=buildTypeStatusDiv)
Nightly Suite: [#2313 - started 8/19, 4:30p](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_Nightlies_NightlySuite&branch_Cockroach_Nightlies=provisional_202008191705_v19.2.10&tab=buildTypeStatusDiv)
 - [#1967 (19 Aug 20 21:26) - Roachtest Nightly - GCE](https://teamcity.cockroachdb.com/viewLog.html?buildId=2198863&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly)
   - 👍 Completed: Tests failed: 9 (4 new), passed: 210, ignored: 74

 
#### Admin UI for Qualification Clusters:

Created | v19.2.9 | v19.2.10 | +2 day | 8/19 | +1 day | +4 day
--|--|-- | -- | -- | -- | --
8/15, 2:30p| [v19.2.9](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/overview/list) | [v19.2.10](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/) | 8/17, 12:30p | new SHA | 8/20, 3pm | 8/24, 10:30a
Overview (+QPS, Latency) | [Overview](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster) | [Overview](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster) | ✅ | - | ✅ | ✅ 
SQL | [SQL](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/sql/cluster) | [SQL](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/sql/cluster) | ✅ | - | ✅ | ✅ 
Replication | [Replication](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/replication/cluster) | [Replication](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/replication/cluster) | ✅ | - | ✅ | ✅ 
 
### [Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `WIP fill in date to roll out: usually Monday, a week before the release WIP`
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA)
  - [x] fill in `Candidate SHA` above
  - [x] email thread on releases@
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] Ack security@ and release-engineering-team@ on the generated AWS S3 bucket write Alert to confirm these writes were part of a planned release (Just reply on the email received alert email acking that this was part of the release process)
 
### [Release Qualification](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification)

- [x] [Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkbinaries) - https://github.com/cockroachdb/bincheck/pull/217
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in all WIP elements above (Nightly Suite, Admin UI, etc.)
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Roachtest-Failure-Signoff)
 
- [x] [Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date. Do not proceed below until the release date.
 
Release date: `Tentatively Monday, 24 Aug, 2020`
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [ ] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.Tagtherelease)
- [ ] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
- [ ] If applicable, [update the map that roachtests use to map a version to a previous version, to reference the newly tagged version](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L1145)
 
- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
 
- For production or stable releases
  - [ ] Announce version to the [registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
 
- [ ] Update docs
- [ ] External communications for release
 
Cleanup:
- [ ] Clean up provisional tag from repository
- [ ] Destroy roachprod clusters

#
_(deprecated 8/19 -- previous candidate details below)_

### Release Blocker Details:
- Issue: sql: panic caused by DEALLOCATE ALL / DISCARD ALL inside of a prepared statement #52915
  - Backport PR: https://github.com/cockroachdb/cockroach/pull/52992 (master PR https://github.com/cockroachdb/cockroach/pull/52940)
  - See [#sql-execution channel](https://cockroachlabs.slack.com/archives/CJGSARZJR/p1597688243024200) for latest discussions

### Release Details:

Candidate SHA: `13350e2bebf99997730262bce26b843ed3ecb1be` (13350e2bebf99997730262bce26b843ed3ecb1be, [provisional_202008151325_v19.2.10](https://github.com/cockroachdb/cockroach/releases/tag/provisional_202008151325_v19.2.10))
Deployment status: ⛔ Release Blocked ⛔
Qualification Suite: [#165, ✅ passed](https://teamcity.cockroachdb.com/viewType.html?buildTypeId=Cockroach_ReleaseQualification&branch_Cockroach=provisional_202008151325_v19.2.10&tab=buildTypeStatusDiv)
Nightly Suite:
- [#2306 (16 Aug 20 15:31) - Nightly Suite](https://teamcity.cockroachdb.com/viewLog.html?buildId=2185657&buildTypeId=Cockroach_Nightlies_NightlySuite)
  - [#1960 (16 Aug 20 16:23) - Roachtest Nightly - GCE](https://teamcity.cockroachdb.com/viewLog.html?buildId=2185654&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly)
    - Tests failed: 12 (9 new), passed: 208, ignored: 72 (👍 completed with failures)

 
Admin UI for Qualification Clusters:

Created | v19.2.9 | v19.2.10 | 2 day check
--|--|-- | --
8/15, 2:30p| [v19.2.9](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/overview/list) | [v19.2.10](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/) | 8/17, 12:30p
Overview (+QPS, Latency) | [Overview](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster) | [Overview](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/overview/cluster) | ✅ 
SQL | [SQL](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/sql/cluster) | [SQL](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/sql/cluster) | ✅ 
Replication | [Replication](http://celia-release-3-v1929-5930d185-0001.roachprod.crdb.io:26258/#/metrics/replication/cluster) | [Replication](http://celia-release-3-v19210-13350e2b-0001.roachprod.crdb.io:26258/#/metrics/replication/cluster) | ✅

**Comment by celiala** [comment] 2020-08-17 16:57
Nightly Tests - Sign-Off checklist

TODO

**Comment by rafiss** [comment] 2020-08-17 18:12
Signed off on the Django test -- it's a temporary flake.

The PGJDBC test failure is quite concerning. The PGJDBC test suite is causing a panic in CockroachDB. It is caused by issuing a `DEALLOCATE ALL` or `DISCARD ALL` statement from within a prepared statement. The details are in https://github.com/cockroachdb/cockroach/issues/52915. I think this qualifies as a release blocker until we understand things further.

**Comment by nvanbenschoten** [comment] 2020-08-17 19:17
Signing off on all CDC tests. They're all testing failures that will be fixed by https://github.com/cockroachdb/cockroach/pull/52928.

**Comment by nvanbenschoten** [comment] 2020-08-17 19:19
Signing off on `follower-reads/nodes=3`. This was a test breakage due to the removal of the "experimental" prefix on the `experimental_follower_read_timestamp()` builtin. This will be fixed by https://github.com/cockroachdb/cockroach/pull/52925.

**Comment by nvanbenschoten** [comment] 2020-08-17 19:20
Signing off on `kv/contention/nodes=4`. This has known failure modes that we're ok with in v19.2. I've bumped the min version for the test in https://github.com/cockroachdb/cockroach/pull/52921.

**Comment by nvanbenschoten** [comment] 2020-08-17 19:21
Signing off on `tpcc-nowait/nodes=3/w=1`. The error is concerning, but not overly so as nothing bad will happen if someone hits it and it seems exceedingly rare. I've improved logging here to help us debug in the future in https://github.com/cockroachdb/cockroach/pull/52923.

**Comment by rafiss** [comment] 2020-08-20 17:19
Signed off on appdev tests. django has a new flaky test that I will ignore in the tests for now. hibernate failed due to a new flake that hasn't happened before, but is not concerning. psycopg is failing because of a setup issue that I'll address today.

**Comment by irfansharif** [comment] 2020-08-20 19:32
Signed off on the KV tests.

**Comment by adityamaru** [comment] 2020-08-20 20:24
Signed off on BulkIO tests. TPCC tests failed to run due to a workload/version mismatch due to recent changes made to workload.

**Comment by andreimatei** [comment] 2020-09-21 14:26
closing as 19.2.10 was released

**Closed by andreimatei** 2020-09-21 14:26 UTC
