### ISSUE TITLE
storage: v2.0.1: panic in cmdQ.remove

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#28889] opened 2018-08-21 08:59 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/655619267/

```
*log.safeError: stopper.go:175: *errors.errorString
  File "github.com/cockroachdb/cockroach/pkg/storage/command_queue.go", line 749, in remove
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2302, in removeCmdsFromCommandQueue
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 2015, in done
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 111, in finishRaftApplication
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4851, in processRaftCommand
...
(8 additional frame(s) were not displayed)

stopper.go:175: *errors.errorString
```

**Comment by andreimatei** [comment] 2018-08-21 20:45
The node was on v2.0.1

**Comment by nvanbenschoten** [comment] 2018-08-22 03:33
This is a pretty interesting panic. It was either caused by a command with an empty range of keys or a command with an inverted range of keys. Neither should be possible.

https://github.com/cockroachdb/cockroach/blob/749187a93a93a2bb2b73b8b3ef90e56d7e181313/pkg/util/interval/interval.go#L45-L54

**Comment by nvanbenschoten** [comment] 2018-08-22 21:52
This is baffling. I'm not seeing how we can hit this panic. First off, let's look at where the error could come from. There are two `interval.Tree` implementations, `btree` and `llrbTree`.
* `btree.Delete` returns an error iff:
** the `Interface` is nil
** `Interface.Range()` has inverted start and end keys
** `Interface.Range()` has equal start and end keys
* `llrbTree.Delete` returns an error iff:
** `Interface.Range()` has inverted start and end keys
** `Interface.Range()` has equal start and end keys

In all likelyhood the server was using `llrbTree`, but since we don't have access to its environment, we can't tell for sure.

* we know from the stack-trace that `cmd != nil`. For all intents and purposes, this means that the `interval.Tree` implementations can be ignored here and that the error must have been caused by one of the two later cases.
* we know from the stack-trace that `!cmd.expanded`
* this means that the command must have been inserted into the interval tree in `command_queue.go:707`, but it didn't hit the error there!
* `cmd.key` is only mutated once, when it's set.
* `cmd.key` is set to `coveringSpan.AsRange()`, which is computed on `command_queue.go:629`. It's possible that one of the provided spans was empty or inverted here, but that doesn't add up, because again we didn't hit this error when we inserted into the tree.

The only way this seems logically consistent is if the `*cmd` passed to `CommandQueue.remove` was never added to the tree in the first place.

**Comment by nvanbenschoten** [comment] 2018-08-22 21:57
Another thing we know if that the command was not in the `readsBuffer` or it would not have hit this branch in `CommandQueue.remove`.

**Comment by nvanbenschoten** [comment] 2018-08-22 22:11
I just confirmed that the `*cmd` passed to `CommandQueue.remove` comes from only one place, `CommandQueue.add`. Furthermore, `CommandQueue.add` is the only place where we construct `cmd` objects, and since we know the `cmd` is not nil, it **must** have come from `CommandQueue.add`, which means it must have been inserted into the tree already (which should have triggered this panic earlier).

**Comment by nvanbenschoten** [comment] 2018-08-22 22:14
... unless it was put and kept in the `readsBuffer`, but we already proved that that wasn't possible because then we wouldn't have hit the branch in `CommandQueue.remove`.

**Comment by nvanbenschoten** [comment] 2018-08-22 22:31
I don't really have a good idea of what to do about this past adding a `log.Safe` to this panic so we can know for sure what the error it is if we see it again. We've only ever seen this once so time will tell if we see it again any time soon.

**Comment by tschottdorf** [comment] 2018-08-23 09:03
Could've just been a bit flip 🤷‍♂️ Logging and time will tell.

**Comment by nvanbenschoten** [comment] 2018-10-31 16:25
Still only a single event and https://github.com/cockroachdb/cockroach/pull/28983 was merged. Closing.

**Closed by nvanbenschoten** 2018-10-31 16:25 UTC
Labels: C-bug, S-2-temp-unavailability
