### ISSUE TITLE
sql: error result is ambiguous in tpcc after online primary key change

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#44504] opened 2020-01-29 20:24 UTC
I'm testing out online primary key changes as described in https://github.com/cockroachdb/cockroach/issues/44501
I ran this change:
```SQL
set experimental_enable_primary_key_changes =true;
ALTER TABLE customer ALTER COLUMN c_city set not null;
ALTER TABLE customer ALTER PRIMARY KEY USING COLUMNS (c_city, c_w_id ASC, c_d_id ASC, c_id ASC);
```
After completing an online primary key change, the workload failed with:
```
Error: error in payment: ERROR: result is ambiguous (intent missing and record aborted) (SQLSTATE 40003)
Error:  exit status 1
```

**Comment by rohany** [comment] 2020-01-29 20:45
I've never seen this error before. I hope it is easier to repro on a smaller TPCC cluster.

**Comment by rohany** [comment] 2020-01-29 23:34
cc @nvanbenschoten do you know what this error means / what badness it could point to?

**Comment by nvanbenschoten** [comment] 2020-01-30 18:51
The error means that a transaction commit was ambiguous (did it commit successfully?) and that the state it needs to determine whether it succeeded was GCed before it could check. It's rare and should only be seen when both a) a cluster is badly overloaded and b) there's contention. From #44501, it sounds like this was the case as the latency spike points toward an overloaded cluster.

**Comment by rohany** [comment] 2020-01-30 19:02
Does running tpcc while performing multiple index creations enough to overload the cluster? I don't have a good feel for these things.

**Comment by awoods187** [comment] 2020-01-30 20:35
This was only tpc-c 2K on a 3 node cluster--it should have been more than fine.

**Comment by irfansharif** [comment] 2020-02-11 20:37
Unrelated to your experiments, I was running other multi-region TPCC benchmarks on v19.2.2 this week and I ran into  "result is ambiguous" errors all the time. I assume because it was multi-region and remote warehouse txns generate a larger contention footprint, this was expected behavior. I was running 9 nodes across three regions (us-west1-b, us-central1-b, us-east1-b), with `workload` per region running TPCC-1k, and that alone enough to generate these errors over a 20-30m run.

**Comment by jordanlewis** [comment] 2020-03-04 05:03
I was going to assign this away, but seems like "result is ambiguous" isn't a bug - it just means the cluster is overloaded, right?

Rohan, please try to reproduce this while you're doing the tpcc alter primary key roachtest. You should definitely use a large dataset like in this example. If you can't repro even with the same cluster size, you can close. If you can repro, take a CPU profile when the error is returned to try to figure out how and if the PK change is to blame.

**Comment by rohany** [comment] 2020-03-09 15:15
Closing in favor of https://github.com/cockroachdb/cockroach/issues/45888.

**Closed by rohany** 2020-03-09 15:15 UTC
Labels: C-investigation

**Comment by dt** [comment] 2020-03-13 23:38
I am also seeing `Error: error in payment: ERROR: result is ambiguous (intent missing and record aborted) (SQLSTATE 40003)` when running tpcc 3k on a brand-new 5 node cluster and no schema changes.

**Comment by nvanbenschoten** [comment] 2020-03-16 18:57
@dt What latencies were you seeing before you hit the error?
