### ISSUE TITLE
server: storeCachedSettingsKVs does not remove unset settings values

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#70567] opened 2021-09-22 13:31 UTC
**Is your feature request related to a problem? Please describe.**

In `settingsworker.go` we store on disk in the system tenant a cache of settings. This allows us to have some access to all settings before the KV layer becomes available (e.g. during node restarts). 

When the settings watcher finds a rangefeed update, we write it https://github.com/cockroachdb/cockroach/blob/9c8aa87293a026a874dec816869e0cfa1e833154/pkg/server/settingsworker.go#L60

The issue is, when we write it, we don't clear out the values which are now unset. See https://github.com/cockroachdb/cockroach/blob/9c8aa87293a026a874dec816869e0cfa1e833154/pkg/server/settings_cache.go#L24-L38

**Describe the solution you'd like**
We should clear the keys which do exist and are not in the set we want to write.

**Additional context**

This can be very annoying as we might retain values which are no longer valid. See https://github.com/cockroachdb/cockroach/issues/68335. 

Jira issue: CRDB-10124
Epic: CRDB-6671

**Comment by knz** [comment] 2023-04-23 08:51
cc @stevendanna  - also see the PR contributed by a community member https://github.com/cockroachdb/cockroach/pull/101472

**Comment by ajstorm** [comment] 2023-04-26 16:54
@stevendanna to assign this to an epic and investigate.

**Comment by knz** [comment] 2023-09-28 17:52
i updated the text to remove mentions of "gossip" and adding mention of the setting watcher.

The problem is that rangefeed deletions in the setting watcher are not translated to kv Del operations in the cache.

**Closed** 2023-09-29 19:01 UTC
Labels: C-bug, branch-master, release-blocker, A-configurability, T-multitenant, branch-release-23.2
