### ISSUE TITLE
sql: the "attribute number" in result RowDescription is not properly populated

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#49640] opened 2020-05-28 13:02 UTC
The change in #48417 works only for "simple query" executions, and does not work for bind/prepare executions.

Found while running the `row_description` pgtest using postgresql:

```
            testdata/pgtest/row_description:164: RowDescription
            expected:
            {"Type":"RowDescription","Fields":[{"Name":"b","TableOID":0,"TableAttributeNumber":0,"DataTypeOID":1042,"DataTypeSize":-1,"TypeModifier":12,"Format":0}]}

            found:
            {"Type":"RowDescription","Fields":[{"Name":"b","TableOID":0,"TableAttributeNumber":2,"DataTypeOID":1042,"DataTypeSize":-1,"TypeModifier":12,"Format":0}]}

```

**Comment by rafiss** [comment] 2020-05-28 18:37
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/49215

**Closed** 2020-05-28 19:15 UTC
Labels: A-sql-pgcompat, A-sql-pgwire, C-bug
