### ISSUE TITLE
Test failure in CI build 9606

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3225] opened 2015-11-25 13:26 UTC
The following test appears to have failed:

[#9606](https://circleci.com/gh/cockroachdb/cockroach/9606):

```
W1125 13:26:14.198885 915 storage/store.go:1354  conflicting intents on [/Local/Range/RangeDescriptor/"\xff\f\x03\xe8YxwuEyHEJPgFqJnBjubtvhOLWFMdlHHyMZzugInzXqHDYNXIPTtJBttpCHLqFwYhHjVyCFuJrGnOQxJunBvGMaUOxZzruJGwNWLP"]: resolved? true
W1125 13:26:14.207471 915 storage/store.go:1354  conflicting intents on [/Local/Range/RangeDescriptor/"\xff\f\x03\xe8"]: resolved? true
I1125 13:26:14.212536 915 client/db.go:483  failed batch: node unavailable; try another peer
E1125 13:26:14.212938 915 storage/queue.go:374  failure processing replica range=2 [/Table/1000-/Max) from split queue: storage/replica_command.go:1319: split at key /Table/1000/"YxwuEyHEJPgFqJnBjubtvhOLWFMdlHHyMZzugInzXqHDYNXIPTtJBttpCHLqFwYhHjVyCFuJrGnOQxJunBvGMaUOxZzruJGwNWLP" failed: node unavailable; try another peer
I1125 13:26:14.214016 915 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestStoreZoneUpdateAndRangeSplit (33.43s)
	client_split_test.go:492: expected range to split within 1s
=== RUN   TestStoreRangeSplitWithMaxBytesUpdate
I1125 13:26:14.215660 915 gossip/gossip.go:172  gossiping node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
I1125 13:26:14.219391 915 multiraft/multiraft.go:557  node 1 starting
I1125 13:26:14.220102 915 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1125 13:26:14.220848 915 raft/raft.go:409  [group 1] 1 became follower at term 5
I1125 13:26:14.221033 915 raft/raft.go:218  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1125 13:26:14.221236 915 multiraft/multiraft.go:959  node 1 campaigning because initial confstate is [1]
I1125 13:26:14.221502 915 raft/raft.go:489  [group 1] 1 is starting a new election at term 5
I1125 13:26:14.221600 915 raft/raft.go:422  [group 1] 1 became candidate at term 6
--
I1125 13:26:18.637835 915 storage/replica.go:1369  gossiping system config from store 1, range 2
I1125 13:26:18.655296 915 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestStoreSplitReadRace (0.09s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.82s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	64.843s
=== RUN   TestBatchBasics
I1125 13:25:25.810937 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1125 13:25:25.814282 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1125 13:25:25.819908 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-11-25 13:30
Probable duplicate of #3219, although the failures are not identical.

**Closed by bdarnell** 2015-11-25 13:30 UTC
Labels: test-failure
