### ISSUE TITLE
Test failure in CI build 8548

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2882] opened 2015-10-21 20:20 UTC
The following test appears to have failed:

[#8548](https://circleci.com/gh/cockroachdb/cockroach/8548):

```
E1021 20:20:08.067704 978 storage/client_test.go:497  error reading "a" from engine 1: value type is not INT: UNKNOWN
E1021 20:20:09.068071 978 storage/client_test.go:497  error reading "a" from engine 1: value type is not INT: UNKNOWN
I1021 20:20:10.069009 978 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1021 20:20:10.069122 978 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1021 20:20:10.069184 978 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (3.35s)
	testing.go:157: storage/client_raft_test.go:1361: condition failed to evaluate within 3s: storage/client_test.go:511: expected [16 0 0], got [16 0 5]
=== RUN   TestReplicateReAddAfterDown
I1021 20:20:10.070449 978 multiraft/multiraft.go:524  node 1 starting
I1021 20:20:10.070546 978 storage/replica.go:1244  gossiping cluster id  from store 1, range 1
I1021 20:20:10.070707 978 raft/raft.go:409  [group 1] 1 became follower at term 5
I1021 20:20:10.070757 978 raft/raft.go:218  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1021 20:20:10.070841 978 multiraft/multiraft.go:918  node 1 campaigning because initial confstate is [1]
I1021 20:20:10.070970 978 raft/raft.go:488  [group 1] 1 is starting a new election at term 5
I1021 20:20:10.070992 978 raft/raft.go:422  [group 1] 1 became candidate at term 6
I1021 20:20:10.071007 978 raft/raft.go:471  [group 1] 1 received vote from 1 at term 6
--

I1021 20:20:12.013030 978 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestStoreRangeSystemSplits (0.18s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.16s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	14.230s
=== RUN   TestBatchBasics
I1021 20:19:49.389152 955 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1021 20:19:49.390069 955 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1021 20:19:49.392787 955 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-10-21 20:23
Duplicate of #2880

**Closed by bdarnell** 2015-10-21 20:23 UTC
Labels: test-failure
