### ISSUE TITLE
Sentry: memo.go:488: cannot overwrite × /  (10548.38) with × /  (×)
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/o...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129788] opened 2024-08-28 11:15 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5766445417/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5766445417/?referrer=webhooks_plugin)

Panic Message:

```
memo.go:488: cannot overwrite × /  (10548.38) with × /  (×)
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).SetBestProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:488
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:819
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:275
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:620
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).DeclareCursor.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/sql_cursor.go:86
  | github.com/cockroachdb/cockroach/pkg/sql.(*delayedNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/delayed.go:50
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:520
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:299
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:523
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:175
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:183
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:94
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:245
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:135
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:278
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
Wraps: (4) cannot overwrite × /  (10548.38) with × /  (×)
Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: cannot overwrite × /  (10548.38) with × /  (×)
memo.go:488: *withstack.withStack (top exception)
*assert.withAssertionFailure
*colexecerror.notInternalError
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/vectorized_flow.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/vectorized_flow.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L277-L279](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L277-L279)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L243-L245)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L244-L246](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/flow_coordinator.go#L244-L246)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/stats.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/stats.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexecerror/error.go#L134-L136](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexecerror/error.go#L134-L136)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/stats.go#L93-L95](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colflow/stats.go#L93-L95)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexec/columnarizer.go#L182-L184](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/colexec/columnarizer.go#L182-L184)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_node_to_row_source.go#L174-L176](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_node_to_row_source.go#L174-L176)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan.go#L522-L524](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan.go#L522-L524)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L42-L44](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L42-L44)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L78-L80](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L78-L80)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L111-L113](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/walk.go#L111-L113)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan.go#L519-L521](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan.go#L519-L521)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/delayed.go#L49-L51](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/delayed.go#L49-L51)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/sql_cursor.go#L85-L87](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/sql_cursor.go#L85-L87)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L619-L621](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L619-L621)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L274-L276](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L274-L276)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L818-L820](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L818-L820)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/memo/memo.go#L487-L489](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/memo/memo.go#L487-L489)
</details>

```
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 278
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 244
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run.(*BatchFlowCoordinator).init.func2 at line 245
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 103
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 135
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 94
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 183
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 175
pkg/sql/plan.go in pkg/sql.startExec at line 523
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 299
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 520
pkg/sql/delayed.go in pkg/sql.(*delayedNode).startExec at line 50
pkg/sql/sql_cursor.go in pkg/sql.(*planner).DeclareCursor.func1 at line 86
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 620
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 275
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 819
pkg/sql/opt/memo/memo.go in pkg/sql/opt/memo.(*Memo).SetBestProps at line 488
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.3 |
| Cockroach SHA | 9e10212477fde97f55ea4fff01797288c836575c |
| # of CPUs | 8 |
| # of Goroutines | 1206 |

Jira issue: CRDB-41711

**Comment by rytaft** [comment] 2024-09-10 14:27
Duplicate of #116022

**Closed by rytaft** 2024-09-10 14:27 UTC
Labels: C-bug, X-duplicate, O-sentry, branch-release-24.1
