### ISSUE TITLE
testing: goroutine leak in TestCopyTransaction

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12884] opened 2017-01-12 18:19 UTC
Found in https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=116224#_focus=8824

8 leaked goroutines.

cc @mjibson

**Comment by knz** [comment] 2017-01-12 18:20
(failing with prop-eval kv enabled)

**Comment by mjibson** [comment] 2017-01-12 18:42
Note: this may get fixed by https://github.com/cockroachdb/cockroach/pull/12723 because it improves the COPY protocol to send a command complete message.

**Comment by tamird** [comment] 2017-01-12 18:44
How come goroutines are leaking, even in the failure case?

**Comment by tamird** [comment] 2017-02-06 17:47
Welp, I couldn't reproduce this, so closing.

**Closed by tamird** 2017-02-06 17:47 UTC
Labels: test-failure
