### ISSUE TITLE
Sentry: datum.go:5355: comparison of two different versions of enum %!s(func() string=0x15226e0) oid ×: versions 35 and 34
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136795] opened 2024-12-05 11:18 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6112769262/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6112769262/?referrer=webhooks_plugin)

Panic Message:

```
datum.go:5355: comparison of two different versions of enum %!s(func() string=0x15226e0) oid ×: versions 35 and 34
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DEnum).Compare
  | 	pkg/sql/sem/tree/datum.go:5355
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.searchPrefixes.func1
  | 	pkg/sql/opt/constraint/locality.go:80
  | sort.Search
  | 	GOROOT/src/sort/search.go:65
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.searchPrefixes
  | 	pkg/sql/opt/constraint/locality.go:99
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.FindMatch
  | 	pkg/sql/opt/constraint/locality.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Constraint).ConsolidateSpans
  | 	pkg/sql/opt/constraint/constraint.go:532
  | github.com/cockroachdb/cockroach/pkg/sql/opt/idxconstraint.(*Instance).Init
  | 	pkg/sql/opt/idxconstraint/index_constraints.go:1152
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).initIdxConstraintForIndex
  | 	pkg/sql/opt/xform/general_funcs.go:197
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).tryConstrainIndex
  | 	pkg/sql/opt/xform/select_funcs.go:1194
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).MakeCombinedFiltersConstraint
  | 	pkg/sql/opt/xform/select_funcs.go:295
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans.func1
  | 	pkg/sql/opt/xform/select_funcs.go:447
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter
  | 	pkg/sql/opt/xform/scan_index_iter.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEach
  | 	pkg/sql/opt/xform/scan_index_iter.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans
  | 	pkg/sql/opt/xform/select_funcs.go:439
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreSelect
  | 	bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:363
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroupMember
  | 	bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:26
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroup
  | 	pkg/sql/opt/xform/explorer.go:180
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	pkg/sql/opt/xform/optimizer.go:559
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeEnforcer
  | 	pkg/sql/opt/xform/optimizer.go:745
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).enforceProps
  | 	pkg/sql/opt/xform/optimizer.go:697
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
  | 	pkg/sql/opt/xform/optimizer.go:589
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	pkg/sql/opt/xform/optimizer.go:546
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	pkg/sql/opt/xform/optimizer.go:266
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	pkg/sql/plan_opt.go:845
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	pkg/sql/plan_opt.go:260
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	pkg/sql/conn_executor_exec.go:2305
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	pkg/sql/conn_executor_exec.go:1854
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	pkg/sql/conn_executor_exec.go:1187
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	pkg/sql/conn_executor_exec.go:3451
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	pkg/sql/conn_executor_exec.go:140
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	pkg/sql/conn_executor.go:2341
Wraps: (3) comparison of two different versions of enum %!s(func() string=0x15226e0) oid ×: versions 35 and 34
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: comparison of two different versions of enum %!s(func() string=0x15226e0) oid ×: versions 35 and 34
datum.go:5355: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[pkg/sql/conn_executor.go#L2340-L2342](pkg/sql/conn_executor.go#L2340-L2342)
[pkg/sql/conn_executor_exec.go#L139-L141](pkg/sql/conn_executor_exec.go#L139-L141)
[pkg/sql/conn_executor_exec.go#L3450-L3452](pkg/sql/conn_executor_exec.go#L3450-L3452)
[pkg/sql/conn_executor_exec.go#L140-L142](pkg/sql/conn_executor_exec.go#L140-L142)
[pkg/sql/conn_executor_exec.go#L1186-L1188](pkg/sql/conn_executor_exec.go#L1186-L1188)
[pkg/sql/conn_executor_exec.go#L1853-L1855](pkg/sql/conn_executor_exec.go#L1853-L1855)
[pkg/sql/conn_executor_exec.go#L2304-L2306](pkg/sql/conn_executor_exec.go#L2304-L2306)
[pkg/sql/plan_opt.go#L259-L261](pkg/sql/plan_opt.go#L259-L261)
[pkg/sql/plan_opt.go#L844-L846](pkg/sql/plan_opt.go#L844-L846)
[pkg/sql/opt/xform/optimizer.go#L265-L267](pkg/sql/opt/xform/optimizer.go#L265-L267)
[pkg/sql/opt/xform/optimizer.go#L545-L547](pkg/sql/opt/xform/optimizer.go#L545-L547)
[pkg/sql/opt/xform/optimizer.go#L588-L590](pkg/sql/opt/xform/optimizer.go#L588-L590)
[pkg/sql/opt/xform/optimizer.go#L696-L698](pkg/sql/opt/xform/optimizer.go#L696-L698)
[pkg/sql/opt/xform/optimizer.go#L744-L746](pkg/sql/opt/xform/optimizer.go#L744-L746)
[pkg/sql/opt/xform/optimizer.go#L558-L560](pkg/sql/opt/xform/optimizer.go#L558-L560)
[pkg/sql/opt/xform/explorer.go#L179-L181](pkg/sql/opt/xform/explorer.go#L179-L181)
[bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L25-L27](bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L25-L27)
[bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L362-L364](bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L362-L364)
[pkg/sql/opt/xform/select_funcs.go#L438-L440](pkg/sql/opt/xform/select_funcs.go#L438-L440)
[pkg/sql/opt/xform/scan_index_iter.go#L201-L203](pkg/sql/opt/xform/scan_index_iter.go#L201-L203)
[pkg/sql/opt/xform/scan_index_iter.go#L298-L300](pkg/sql/opt/xform/scan_index_iter.go#L298-L300)
[pkg/sql/opt/xform/select_funcs.go#L446-L448](pkg/sql/opt/xform/select_funcs.go#L446-L448)
[pkg/sql/opt/xform/select_funcs.go#L294-L296](pkg/sql/opt/xform/select_funcs.go#L294-L296)
[pkg/sql/opt/xform/select_funcs.go#L1193-L1195](pkg/sql/opt/xform/select_funcs.go#L1193-L1195)
[pkg/sql/opt/xform/general_funcs.go#L196-L198](pkg/sql/opt/xform/general_funcs.go#L196-L198)
[pkg/sql/opt/idxconstraint/index_constraints.go#L1151-L1153](pkg/sql/opt/idxconstraint/index_constraints.go#L1151-L1153)
[pkg/sql/opt/constraint/constraint.go#L531-L533](pkg/sql/opt/constraint/constraint.go#L531-L533)
[pkg/sql/opt/constraint/locality.go#L115-L117](pkg/sql/opt/constraint/locality.go#L115-L117)
[pkg/sql/opt/constraint/locality.go#L98-L100](pkg/sql/opt/constraint/locality.go#L98-L100)
[GOROOT/src/sort/search.go#L64-L66](GOROOT/src/sort/search.go#L64-L66)
[pkg/sql/opt/constraint/locality.go#L79-L81](pkg/sql/opt/constraint/locality.go#L79-L81)
[pkg/sql/sem/tree/datum.go#L5354-L5356](pkg/sql/sem/tree/datum.go#L5354-L5356)
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2341
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 140
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3451
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1187
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1854
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2305
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 260
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 845
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 266
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 546
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember at line 589
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).enforceProps at line 697
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeEnforcer at line 745
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 559
pkg/sql/opt/xform/explorer.go in pkg/sql/opt/xform.(*explorer).exploreGroup at line 180
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreGroupMember at line 26
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreSelect at line 363
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans at line 439
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEach at line 202
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter at line 299
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).GenerateConstrainedScans.func1 at line 447
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).MakeCombinedFiltersConstraint at line 295
pkg/sql/opt/xform/select_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).tryConstrainIndex at line 1194
pkg/sql/opt/xform/general_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).initIdxConstraintForIndex at line 197
pkg/sql/opt/idxconstraint/index_constraints.go in pkg/sql/opt/idxconstraint.(*Instance).Init at line 1152
pkg/sql/opt/constraint/constraint.go in pkg/sql/opt/constraint.(*Constraint).ConsolidateSpans at line 532
pkg/sql/opt/constraint/locality.go in pkg/sql/opt/constraint.FindMatch at line 116
pkg/sql/opt/constraint/locality.go in pkg/sql/opt/constraint.searchPrefixes at line 99
GOROOT/src/sort/search.go in sort.Search at line 65
pkg/sql/opt/constraint/locality.go in pkg/sql/opt/constraint.searchPrefixes.func1 at line 80
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.(*DEnum).Compare at line 5355
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.3.0 |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.3.0 |
| Cockroach SHA | ef2ebe96f3a26fd6d6716e2ec4a0c8c6fe0fb567 |
| # of CPUs | 2 |
| # of Goroutines | 817 |

Jira issue: CRDB-45253

**Comment by Dedej-Bergin** [comment] 2024-12-10 18:09
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/132105

**Closed by Dedej-Bergin** 2024-12-10 18:09 UTC
Labels: C-bug, O-sentry, X-blathers-triaged, T-sql-foundations, branch-release-24.3
