### ISSUE TITLE
Test failure in CI build 9365

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3129] opened 2015-11-13 19:00 UTC
The following test appears to have failed:

[#9365](https://circleci.com/gh/cockroachdb/cockroach/9365):

```
I1113 18:59:29.815051 1000 gossip/gossip.go:172  gossiping node descriptor node_id:3 address:<network_field:"localhost" address_field:"3" > attrs:<> 
I1113 18:59:29.816341 1000 storage/queue.go:193  no system config available. skipping...
I1113 18:59:30.894033 1000 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1113 18:59:30.894153 1000 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1113 18:59:30.894209 1000 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestRaftLogQueue (1.09s)
	testing.go:157: storage/client_raft_log_queue_test.go:93: condition failed to evaluate within 1s: storage/client_raft_log_queue_test.go:90: raft log has not been truncated yet, currentIndex:11 originalIndex:11
=== RUN   TestStoreRecoverFromEngine
I1113 18:59:30.894670 1000 gossip/gossip.go:172  gossiping node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
I1113 18:59:30.895444 1000 multiraft/multiraft.go:562  node 1 starting
I1113 18:59:30.895543 1000 raft/raft.go:409  [group 1] 1 became follower at term 5
I1113 18:59:30.895584 1000 raft/raft.go:218  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1113 18:59:30.895662 1000 multiraft/multiraft.go:964  node 1 campaigning because initial confstate is [1]
I1113 18:59:30.895786 1000 storage/replica.go:1259  gossiping cluster id  from store 1, range 1
I1113 18:59:30.895895 1000 raft/raft.go:488  [group 1] 1 is starting a new election at term 5
I1113 18:59:30.895916 1000 raft/raft.go:422  [group 1] 1 became candidate at term 6
--
W1113 18:59:47.016172 1000 rpc/server.go:435  rpc: write response failed: write tcp 127.0.0.1:38547->127.0.0.1:49915: use of closed network connection
--- SKIP: TestSplitSnapshotRace_SnapshotWins (0.01s)
	client_split_test.go:740: TODO(bdarnell): https://github.com/cockroachdb/cockroach/issues/3121
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.14s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	19.411s
=== RUN   TestBatchBasics
I1113 18:59:21.895579 977 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1113 18:59:21.896524 977 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1113 18:59:21.910385 977 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-11-13 19:51
Dupe of #3124.

**Closed by tamird** 2015-11-13 19:51 UTC
Labels: test-failure
