### ISSUE TITLE
sql: panic: flow: unexpected 204800 leftover bytes

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#40621] opened 2019-09-10 05:24 UTC
On the TPCH SF1 dataset:

```
set vectorize=experimental_on;

SELECT
	c_name,
	c_custkey,
	o_orderkey,
	o_orderdate,
	o_totalprice,
	sum(l_quantity)
FROM
	customer,
	orders,
	lineitem
WHERE
	o_orderkey IN (
		SELECT
			l_orderkey
		FROM
			lineitem
		GROUP BY
			l_orderkey HAVING
				sum(l_quantity) > -9223372036854775807
	)
	AND c_custkey = o_custkey
	AND o_orderkey = l_orderkey
GROUP BY
	c_name,
	c_custkey,
	o_orderkey,
	o_orderdate,
	o_totalprice
ORDER BY
	o_totalprice DESC,
	o_orderdate
LIMIT 100;
```

```
* ERROR: [n1,client=[::1]:56946,user=root] a SQL panic has occurred while executing "SELECT c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, sum(l_quantity) FROM customer, orders, lineitem WHERE ((o_orderkey IN (SELECT l_orderkey FROM lineitem GROUP BY l_orderkey HAVING sum(l_quantity) > $1::INT8)) AND (c_custkey = o_custkey)) AND (o_orderkey = l_orderkey) GROUP BY c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice ORDER BY o_totalprice DESC, o_orderdate LIMIT 100": flow: unexpected 204800 leftover bytes

runtime/debug.Stack(0x4f50c00, 0xc00fce68c0, 0x3)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x4f50c00, 0xc00fce68c0, 0xc000858000, 0x43b7400, 0xc00a1dc9c0, 0x1)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:217 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc008264000, 0x4f50c00, 0xc00fce68c0, 0x3f4f640, 0xc0072e98e0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:723 +0x2a0
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc008264000, 0x4f50c00, 0xc00fce68c0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0x61
panic(0x3f4f640, 0xc0072e98e0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4f50cc0, 0xc007718f00, 0xc000858000, 0xc000028630, 0x26, 0x0, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:554 +0x226
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc007c48820, 0x4f50cc0, 0xc007718f00, 0x30d9301)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x291
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop(...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2780
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Cleanup(0xc007433c20, 0x4f50cc0, 0xc007718f00)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:630 +0x87
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func5()
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:354 +0xc0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc008264000, 0x4f50cc0, 0xc00094b170, 0xc008264358, 0x3, 0x7f74cc9722a8, 0xc000720f68, 0xc00ad3a901, 0x0, 0x0, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:823 +0x4c1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc008264000, 0x4f50cc0, 0xc00094b170, 0xc008264358, 0x7f74cc9722a8, 0xc000720f68, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:708 +0x6de
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc008264000, 0x4f50cc0, 0xc00094b170, 0x4f75880, 0xc00f93ae00, 0xc0082987f7, 0x1af, 0x1, 0x4, 0xc00b1df080, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xc2f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc008264000, 0x4f50cc0, 0xc00094b170, 0x4f75880, 0xc00f93ae00, 0xc0082987f7, 0x1af, 0x1, 0x4, 0xc00b1df080, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:98 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc008264000, 0x4f50c00, 0xc000e19f80, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1300 +0xed6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc008264000, 0x4f50c00, 0xc00fce68c0, 0xc000b78340, 0x5400, 0x15000, 0xc000b783d8, 0xc00f718230, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1167 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000826000, 0x4f50c00, 0xc00fce68c0, 0xc008264000, 0x5400, 0x15000, 0xc000b783d8, 0xc00f718230, 0x0, 0x0)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:444 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc01b818079, 0xc0004b4120, 0x4f50c00, 0xc00fce68c0, 0xc00f718230, 0xc000826000, 0xc000720900, 0x4f73e00, 0xc0004b4100, 0xc01cb71b00, ...)
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b
```

This is tpch query 18 with a randomized argument for the HAVING clause. I'm not able to repro this, so it's possible it's due to multiple executions happening at once (which is what my test was doing). Also possibly due to the connection getting its context canceled, and maybe somewhere something isn't cleaning up correctly. Marking this as `C-investigation` until we can repro it.

**Comment by asubiotto** [comment] 2019-09-10 10:04
Able to reproduce this by canceling the query while it's executing. Will investigate. This is amazing, thanks!

**Comment by asubiotto** [comment] 2019-09-10 10:30
Unfortunately it's not deterministic. Is this on one node only? The next step is to probably write a test to stress this.

**Comment by mjibson** [comment] 2019-09-10 16:03
Yes, this happened initially on a single node.

**Comment by asubiotto** [comment] 2019-09-19 11:12
Added a test to stress this and I have a reliable reproduction. Digging.

**Comment by asubiotto** [comment] 2019-09-23 14:22
I have a fix out for the memory error (turns out the `Columnarizer` was not closing its inputs properly) but am now encountering another bug with the same query.
The error is:
`unexpected error from the vectorized runtime: interface conversion: coldata.column is []float64, not *coldata.Bytes`
encountered in the hash aggregator downstream of a hash joiner. This hash joiner has as output types:
`[{{IntFamily 64 0 [] 0xa63e320 0 <nil> [] [] 20 <nil>}} {{FloatFamily 64 0 [] 0xa63e320 0 <nil> [] [] 701 <nil>}} {{DateFamily 0 0 [] 0xa63e320 0 <nil> [] [] 1082 <nil>}} {{FloatFamily 64 0 [] 0xa63e320 0 <nil> [] [] 701 <nil>}} {{IntFamily 64 0 [] 0xa63e320 0 <nil> [] [] 20 <nil>}} {{StringFamily 25 0 [] 0xa63e320 0 <nil> [] [] 1043 <nil>}}]`
but the downstream aggregator has:
`[Int64 Bytes Int64 Float64 Int64 Float64]`
I believe there's some projection going on inside the hash joiner that is not taken into account downstream. @yuzefovich since you worked on the joiner types recently, does this look like anything to you before I start digging further?

**Comment by yuzefovich** [comment] 2019-09-23 16:42
I'm glad we found this - indeed, this problem is caused by my recent changes. What happens is that I "fixed" the joiners in a sense that they now handle projections themselves (this was always desired but didn't work properly); however, at the moment they do not fully "handle" the projection. In this particular case, we have `post.OutputColumns = {6, 7, 0, 2, 3, 5}` with `6` and `7` corresponding to the right side and others to the left side. But the joiner always outputs left out columns first, so after the joiner we will get an equivalent of `{0, 2, 3, 5, 6, 7}`. I'll open up a PR to fix this.

**Closed** 2019-09-27 14:55 UTC
Labels: C-bug, O-sqlsmith
