### ISSUE TITLE
SHOW RANGES does not show expected results in multi-region cluster with super regions

### ISSUE THREAD

**Issue by codingconcepts** [cockroachdb/cockroach#106128] opened 2023-07-04 19:27 UTC
**Problem**

Creating a multi-region cluster with super regions does not _appear_ to replicate data correctly.

**To Reproduce**

Create the cluster:
```
cockroach demo \
  --insecure \
  --no-example-database \
  --nodes 12 \
  --demo-locality=region=us-east1,az=a:region=us-east1,az=b:region=us-east2,az=a:region=us-east2,az=b:region=us-west2,az=a:region=us-west2,az=b:region=eu-west2,az=a:region=eu-west2,az=b:region=eu-west3,az=a:region=eu-west3,az=b:region=eu-north1,az=a:region=eu-north1,az=b
```

Create the database and populate a table:
``` sql
CREATE DATABASE "meetup";
USE "meetup";

ALTER DATABASE "meetup" SET PRIMARY REGION "us-east1";
ALTER DATABASE "meetup" ADD REGION "us-east2";
ALTER DATABASE "meetup" ADD REGION "us-west2";
ALTER DATABASE "meetup" ADD REGION "eu-west2";
ALTER DATABASE "meetup" ADD REGION "eu-west3";
ALTER DATABASE "meetup" ADD REGION "eu-north1";

ALTER DATABASE "meetup" SURVIVE REGION FAILURE;

SET enable_super_regions = 'on';
ALTER DATABASE "meetup" ADD SUPER REGION us VALUES "us-east1", "us-east2", "us-west2";
ALTER DATABASE "meetup" ADD SUPER REGION eu VALUES "eu-west2", "eu-west3", "eu-north1";

CREATE TABLE "product" (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" STRING NOT NULL,
  "market" STRING NOT NULL,
  "crdb_region" CRDB_INTERNAL_REGION AS (
    CASE
        WHEN "market" IN ('ie', 'uk') THEN 'eu-west2'
        WHEN "market" IN ('de', 'fr') THEN 'eu-west3'
        WHEN "market" IN ('no', 'se') THEN 'eu-north1'
        WHEN "market" IN ('us') THEN 'us-east1'
        ELSE 'eu-west2'
    END
  ) STORED,
  "amount" DECIMAL NOT NULL,
  "currency" STRING NOT NULL,

  INDEX ("market")
) LOCALITY REGIONAL BY ROW;

INSERT INTO product ("id", "name", "market", "amount", "currency") VALUES
  ('b7eaba08-2d20-4109-9a39-aeba20c486a4', 'Americano', 'uk', 3.80, 'gbp'),
  ('279d936b-2f68-445d-9301-cd062d283859', 'Latte', 'uk', 4.15, 'gbp'),
  ('2586aa2c-84e0-4f28-b299-732c2314aa91', 'Cappuccino', 'uk', 4.15, 'gbp'),

  ('fd16dd63-d9ea-418f-8353-a891287a7be0', 'Americano', 'ie', 4.40, 'gbp'),
  ('7ad66c52-6a6a-4f9f-a590-4b5ede1c82f1', 'Latte', 'ie', 4.80, 'gbp'),
  ('1a8b5e94-220e-411a-8f26-fe43dd6485f1', 'Cappuccino', 'ie', 4.80, 'gbp'),

  ('2f22da46-d983-4878-8ad2-a6e6ff7e8f39', 'Americano', 'de', 4.40, 'eur'),
  ('a5ece2cb-6b76-46fd-a11b-a53dcf2f0669', 'Latte', 'de', 4.80, 'eur'),
  ('de17b8db-a6dc-48a3-a33b-1272365c7226', 'Cappuccino', 'de', 4.80, 'eur'),

  ('a63a07fd-1f7a-41b7-bcaa-67c0118cd3f2', 'Américain', 'fr', 4.40, 'eur'),
  ('279c0aea-21a0-48dd-8197-0bbf0f7defd0', 'Latté', 'fr', 4.80, 'eur'),
  ('29bc6a72-35b8-456a-8e92-de5899bb8c0a', 'Cappuccino', 'fr', 4.80, 'eur'),

  ('6acf78f8-e6ed-4a02-a899-9978f958f513', 'Américain', 'no', 51.41, 'eur'),
  ('9b52c9ef-76ef-42d2-8302-0a74a0dad1c7', 'Latté', 'no', 56.15, 'eur'),
  ('a7b54333-dc25-4c01-bfb0-d93205af30a9', 'Cappuccino', 'no', 56.15, 'eur'),

  ('fe0b83b5-4573-439b-87ab-1193f12e01fb', 'Américain', 'se', 52.27, 'sek'),
  ('6214d841-9a52-4f06-8085-16cf076704e6', 'Latté', 'se', 57.09, 'sek'),
  ('f04f5fa9-88ba-4a52-b0e7-f77bb516f15a', 'Cappuccino', 'se', 57.09, 'sek'),

  ('b6f2327f-80c3-44ce-9c3c-d0c04736c90f', 'Americano', 'us', 4.80, 'usd'),
  ('0cc06e87-713c-4edd-af0b-627be0fb6843', 'Latte', 'us', 5.24, 'usd'),
  ('c880c792-32df-43d7-9b4d-d5745c842f4b', 'Cappuccino', 'us', 5.24, 'usd');
```

Show replicas by region and az:
``` sql
SELECT DISTINCT
  split_part(split_part(unnest(replica_localities), ',', 1), '=', 2) region,
  split_part(split_part(unnest(replica_localities), ',', 2), '=', 2) az,
  unnest(replicas) replica
FROM [SHOW RANGES FROM TABLE product]
ORDER BY replica;
```

```
   region   | az | replica
------------+----+----------
  us-east1  | a  |       1
  us-east1  | b  |       2
  us-east2  | a  |       3
  us-east2  | b  |       4
  us-west2  | a  |       5
  us-west2  | b  |       6
  eu-west2  | a  |       7
  eu-west2  | b  |       8
  eu-west3  | a  |       9
  eu-west3  | b  |      10
  eu-north1 | a  |      11
  eu-north1 | b  |      12
```

Show replicas and ranges by region (all):
``` sql
WITH
  replicas AS (
    SELECT DISTINCT
      split_part(unnest(replica_localities), ',', 1) replica_localities,
      replicas
    FROM [SHOW RANGES FROM TABLE product]
  ),
  ranges AS (
    SELECT
      replicas,
      range_id
    FROM [SHOW RANGES FROM TABLE product]
  )
SELECT
  split_part(re.replica_localities, '=', 2) region,
  re.replicas,
  array_agg(ra.range_id) range_ids
FROM replicas re
JOIN ranges ra ON re.replicas = ra.replicas
GROUP BY re.replica_localities, re.replicas
ORDER BY range_ids;
```

```
   region   |     replicas      |   range_ids
------------+-------------------+----------------
  us-east1  | {2,3,5,7,9,11,12} | {64}
  us-east2  | {2,3,5,7,9,11,12} | {64}
  us-west2  | {2,3,5,7,9,11,12} | {64}
  eu-west2  | {2,3,5,7,9,11,12} | {64}
  eu-west3  | {2,3,5,7,9,11,12} | {64}
  eu-north1 | {2,3,5,7,9,11,12} | {64}
  eu-west2  | {7,8,9,11,12}     | {65,79,77,67}
  eu-west3  | {7,8,9,11,12}     | {65,79,77,67}
  eu-north1 | {7,8,9,11,12}     | {65,79,77,67}
  us-east1  | {1,2,3,5,7,9,12}  | {66}
  us-east2  | {1,2,3,5,7,9,12}  | {66}
  us-west2  | {1,2,3,5,7,9,12}  | {66}
  eu-west2  | {1,2,3,5,7,9,12}  | {66}
  eu-west3  | {1,2,3,5,7,9,12}  | {66}
  eu-north1 | {1,2,3,5,7,9,12}  | {66}
  us-east1  | {2,4,5,7,8,9,11}  | {68}
  us-east2  | {2,4,5,7,8,9,11}  | {68}
  us-west2  | {2,4,5,7,8,9,11}  | {68}
  eu-west2  | {2,4,5,7,8,9,11}  | {68}
  eu-west3  | {2,4,5,7,8,9,11}  | {68}
  eu-north1 | {2,4,5,7,8,9,11}  | {68}
  eu-west2  | {7,9,10,11,12}    | {69,81}
  eu-west3  | {7,9,10,11,12}    | {69,81}
  eu-north1 | {7,9,10,11,12}    | {69,81}
  us-east1  | {2,3,4,5,8,9,11}  | {70}
  us-east2  | {2,3,4,5,8,9,11}  | {70}
  us-west2  | {2,3,4,5,8,9,11}  | {70}
  eu-west2  | {2,3,4,5,8,9,11}  | {70}
  eu-west3  | {2,3,4,5,8,9,11}  | {70}
  eu-north1 | {2,3,4,5,8,9,11}  | {70}
  us-east1  | {1,2,3,4,5}       | {71,85,83,73}
  us-east2  | {1,2,3,4,5}       | {71,85,83,73}
  us-west2  | {1,2,3,4,5}       | {71,85,83,73}
  us-east1  | {1,2,3,5,8,10,11} | {72}
  us-east2  | {1,2,3,5,8,10,11} | {72}
  us-west2  | {1,2,3,5,8,10,11} | {72}
  eu-west2  | {1,2,3,5,8,10,11} | {72}
  eu-west3  | {1,2,3,5,8,10,11} | {72}
  eu-north1 | {1,2,3,5,8,10,11} | {72}
  us-east1  | {1,2,3,5,7,10,12} | {74}
  us-east2  | {1,2,3,5,7,10,12} | {74}
  us-west2  | {1,2,3,5,7,10,12} | {74}
  eu-west2  | {1,2,3,5,7,10,12} | {74}
  eu-west3  | {1,2,3,5,7,10,12} | {74}
  eu-north1 | {1,2,3,5,7,10,12} | {74}
  us-east1  | {1,2,3,5,6}       | {75,87}
  us-east2  | {1,2,3,5,6}       | {75,87}
  us-west2  | {1,2,3,5,6}       | {75,87}
  us-east1  | {2,3,5,7,9,10,11} | {76}
  us-east2  | {2,3,5,7,9,10,11} | {76}
  us-west2  | {2,3,5,7,9,10,11} | {76}
  eu-west2  | {2,3,5,7,9,10,11} | {76}
  eu-west3  | {2,3,5,7,9,10,11} | {76}
  eu-north1 | {2,3,5,7,9,10,11} | {76}
  us-east1  | {2,3,5,6,7,9,11}  | {78,84}
  us-east2  | {2,3,5,6,7,9,11}  | {78,84}
  us-west2  | {2,3,5,6,7,9,11}  | {78,84}
  eu-west2  | {2,3,5,6,7,9,11}  | {78,84}
  eu-west3  | {2,3,5,6,7,9,11}  | {78,84}
  eu-north1 | {2,3,5,6,7,9,11}  | {78,84}
  us-east1  | {1,2,3,6,8,10,11} | {80}
  us-east2  | {1,2,3,6,8,10,11} | {80}
  us-west2  | {1,2,3,6,8,10,11} | {80}
  eu-west2  | {1,2,3,6,8,10,11} | {80}
  eu-west3  | {1,2,3,6,8,10,11} | {80}
  eu-north1 | {1,2,3,6,8,10,11} | {80}
  us-east1  | {2,3,4,5,7,9,11}  | {82}
  us-east2  | {2,3,4,5,7,9,11}  | {82}
  us-west2  | {2,3,4,5,7,9,11}  | {82}
  eu-west2  | {2,3,4,5,7,9,11}  | {82}
  eu-west3  | {2,3,4,5,7,9,11}  | {82}
  eu-north1 | {2,3,4,5,7,9,11}  | {82}
  us-east1  | {1,2,3,5,8,10,12} | {86}
  us-east2  | {1,2,3,5,8,10,12} | {86}
  us-west2  | {1,2,3,5,8,10,12} | {86}
  eu-west2  | {1,2,3,5,8,10,12} | {86}
  eu-west3  | {1,2,3,5,8,10,12} | {86}
  eu-north1 | {1,2,3,5,8,10,12} | {86}
  us-east1  | {2,3,5,6,7,10,12} | {88}
  us-east2  | {2,3,5,6,7,10,12} | {88}
  us-west2  | {2,3,5,6,7,10,12} | {88}
  eu-west2  | {2,3,5,6,7,10,12} | {88}
  eu-west3  | {2,3,5,6,7,10,12} | {88}
  eu-north1 | {2,3,5,6,7,10,12} | {88}
```

Show replicas and ranges by region (one row): 
``` sql
WITH
  replicas AS (
    SELECT DISTINCT
      split_part(unnest(replica_localities), ',', 1) replica_localities,
      replicas
    FROM [SHOW RANGE FROM TABLE product FOR ROW ('us-east1', 'b6f2327f-80c3-44ce-9c3c-d0c04736c90f')]
  ),
  ranges AS (
    SELECT
      replicas,
      range_id
    FROM [SHOW RANGE FROM TABLE product FOR ROW ('us-east1', 'b6f2327f-80c3-44ce-9c3c-d0c04736c90f')]
  )
SELECT
  split_part(re.replica_localities, '=', 2) region,
  re.replicas,
  array_agg(ra.range_id) range_ids
FROM replicas re
JOIN ranges ra ON re.replicas = ra.replicas
GROUP BY re.replica_localities, re.replicas
ORDER BY range_ids;
```

``` sql
   region  |  replicas   | range_ids
-----------+-------------+------------
  us-east1 | {1,2,3,4,5} | {71}
  us-east2 | {1,2,3,4,5} | {71}
  us-west2 | {1,2,3,4,5} | {71}
```

Show replicas and ranges by region (another row): 
``` sql
WITH
  replicas AS (
    SELECT DISTINCT
      split_part(unnest(replica_localities), ',', 1) replica_localities,
      replicas
    FROM [SHOW RANGE FROM TABLE product FOR ROW ('eu-west3', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')]
  ),
  ranges AS (
    SELECT
      replicas,
      range_id
    FROM [SHOW RANGE FROM TABLE product FOR ROW ('eu-west3', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')]
  )
SELECT
  split_part(re.replica_localities, '=', 2) region,
  re.replicas,
  array_agg(ra.range_id) range_ids
FROM replicas re
JOIN ranges ra ON re.replicas = ra.replicas
GROUP BY re.replica_localities, re.replicas
ORDER BY range_ids;
```

```
   region   |    replicas    | range_ids
------------+----------------+------------
  eu-west2  | {7,9,10,11,12} | {69}
  eu-west3  | {7,9,10,11,12} | {69}
  eu-north1 | {7,9,10,11,12} | {69}
```

**Expected behavior**
I would expect the query to show replicas and ranges by region (all) to show no overlap of replicas between regions.

**Environment:**
```
Build Tag:        v23.1.4
Build Time:       2023/06/16 21:03:22
Distribution:     CCL
Platform:         darwin arm64 (aarch64-apple-darwin21.2)
Go Version:       go1.19.4
C Compiler:       Clang 10.0.0 
Build Commit ID:  cf85e8ad48bb7a8afd821863d4f345baafa4a1b6
Build Type:       release
Enabled Assertions: false
```

Jira issue: CRDB-29416

**Comment by ajstorm** [comment] 2023-07-04 20:10
Not sure where this should reside long-term, but sending it to Cluster Observability for first triage.

**Comment by pschulz1** [comment] 2023-07-05 07:06
The following repro of a super region + regional by row setup shows that a single row seems/looks like to exist in both super regions at the time. We seem to lack tooling to verify what is actually happening and where data is actually placed. 

```
cockroach demo --nodes=9

\demo add region=us-central1,zone=a;
\demo add region=us-central1,zone=b;
\demo add region=us-central1,zone=c;
\demo add region=europe-central1,zone=a;
\demo add region=europe-central1,zone=b;
\demo add region=europe-central1,zone=c;
\demo add region=europe-north1,zone=a;
\demo add region=europe-north1,zone=b;
\demo add region=europe-north1,zone=c;

SHOW REGIONS;

      region      |  zones  | database_names | primary_region_of | secondary_region_of
------------------+---------+----------------+-------------------+----------------------
  europe-central1 | {a,b,c} | {}             | {}                | {}
  europe-north1   | {a,b,c} | {}             | {}                | {}
  europe-west1    | {b,c,d} | {}             | {}                | {}
  us-central1     | {a,b,c} | {}             | {}                | {}
  us-east1        | {b,c,d} | {}             | {}                | {}
  us-west1        | {a,b,c} | {}             | {}                | {}
(6 rows)

ALTER DATABASE MOVR SET PRIMARY REGION "europe-west1";
ALTER DATABASE MOVR ADD region "europe-central1";
ALTER DATABASE MOVR ADD region "europe-north1";
ALTER DATABASE MOVR ADD region "us-east1";
ALTER DATABASE MOVR ADD region "us-central1";
ALTER DATABASE MOVR ADD region "us-west1";

SET enable_super_regions = 'on';

ALTER DATABASE movr ADD SUPER REGION "us" VALUES "us-east1", "us-west1", "us-central1";

ALTER DATABASE movr ADD SUPER REGION "eu" VALUES "europe-west1", "europe-central1", "europe-north1";

ALTER DATABASE movr SURVIVE REGION FAILURE;

ALTER TABLE users SET LOCALITY REGIONAL BY ROW;


INSERT INTO users (id, city, name, address, credit_card) VALUES (gen_random_uuid(), 'trippstadt', 'andrea schulz', '67705 Heidenkopfstr 128', '7875559802');
INSERT INTO users (id, city, name, address, credit_card, crdb_region) VALUES (gen_random_uuid(), 'trippstadt', 'patrick schulz', '67705 Heidenkopfstr 128', '7875559802', 'us-central1');

SELECT * FROM users WHERE city IN ('trippstadt');

                   id                  |    city    |      name      |         address         | credit_card
---------------------------------------+------------+----------------+-------------------------+--------------
  508c2fc8-a55d-4073-9aa6-1e4fc99254cc | trippstadt | patrick schulz | 67705 Heidenkopfstr 128 |  7875559802
  2df6c8ec-9029-4a88-bba2-0cf64aa744bb | trippstadt | andrea schulz  | 67705 Heidenkopfstr 128 |  7875559802


SHOW RANGE FROM TABLE users FOR ROW ('europe-west1', 'trippstadt', '508c2fc8-a55d-4073-9aa6-1e4fc99254cc');

  start_key |      end_key       | range_id | lease_holder |  lease_holder_locality   |    replicas    |                                                                  replica_localities                                                                   | voting_replicas | non_voting_replicas
------------+--------------------+----------+--------------+--------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------------
  …/"\x80"  | …/"\x80"/PrefixEnd |      111 |            7 | region=europe-west1,az=b | {7,9,13,14,18} | {"region=europe-west1,az=b","region=europe-west1,az=d","region=europe-central1,zone=a","region=europe-central1,zone=b","region=europe-north1,zone=c"} | {14,9,7,13,18}  | {}
(1 row)

SHOW RANGE FROM TABLE users FOR ROW ('europe-west1', 'trippstadt', '2df6c8ec-9029-4a88-bba2-0cf64aa744bb');
  start_key |      end_key       | range_id | lease_holder |  lease_holder_locality   |    replicas    |                                                                  replica_localities                                                                   | voting_replicas | non_voting_replicas
------------+--------------------+----------+--------------+--------------------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------------
  …/"\x80"  | …/"\x80"/PrefixEnd |      111 |            7 | region=europe-west1,az=b | {7,9,13,14,18} | {"region=europe-west1,az=b","region=europe-west1,az=d","region=europe-central1,zone=a","region=europe-central1,zone=b","region=europe-north1,zone=c"} | {14,9,7,13,18}  | {}
(1 row)

SELECT crdb_region, * FROM users WHERE city IN ('trippstadt')
                        -> ;
  crdb_region |                  id                  |    city    |      name      |         address         | credit_card
--------------+--------------------------------------+------------+----------------+-------------------------+--------------
  us-central1 | 508c2fc8-a55d-4073-9aa6-1e4fc99254cc | trippstadt | patrick schulz | 67705 Heidenkopfstr 128 |  7875559802
  us-east1    | 2df6c8ec-9029-4a88-bba2-0cf64aa744bb | trippstadt | andrea schulz  | 67705 Heidenkopfstr 128 |  7875559802
(2 rows)

SELECT * FROM gateway_region()
                        -> ;
  gateway_region
------------------
  us-east1
(1 row)

SHOW RANGE FROM TABLE users FOR ROW (‘us-central1’, ‘trippstadt’, ‘508c2fc8-a55d-4073-9aa6-1e4fc99254cc’);

  start_key |      end_key       | range_id | lease_holder |   lease_holder_locality   |   replicas    |                                                       replica_localities                                                       | voting_replicas | non_voting_replicas
------------+--------------------+----------+--------------+---------------------------+---------------+--------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------------
  …/“\xa0”  | …/“\xa0"/PrefixEnd |      113 |           10 | region=us-central1,zone=a | {2,3,5,10,11} | {“region=us-east1,az=c”,“region=us-east1,az=d”,“region=us-west1,az=b”,“region=us-central1,zone=a”,“region=us-central1,zone=b”} | {11,3,2,5,10}   | {}
(1 row)

SHOW RANGE FROM TABLE users FOR ROW (‘us-east1’, ‘trippstadt’, ‘2df6c8ec-9029-4a88-bba2-0cf64aa744bb’);

  start_key |      end_key       | range_id | lease_holder | lease_holder_locality |   replicas    |                                                       replica_localities                                                       | voting_replicas | non_voting_replicas
------------+--------------------+----------+--------------+-----------------------+---------------+--------------------------------------------------------------------------------------------------------------------------------+-----------------+----------------------
  …/“\xc0”  | …/“\xc0"/PrefixEnd |      195 |            2 | region=us-east1,az=c  | {1,2,4,10,11} | {“region=us-east1,az=b”,“region=us-east1,az=c”,“region=us-west1,az=a”,“region=us-central1,zone=a”,“region=us-central1,zone=b”} | {4,2,10,1,11}   | {}
(1 row)
```

**Comment by knz** [comment] 2023-07-13 12:02
Some considerations for the future investigation: 

- `SHOW RANGES` and `SHOW RANGE FOR ROW` are fundamentally different observability features, so if there's problems with both they should be investigated separately.
- we'll need to be careful to ensure that the raw data (in the `crdb_internal` vtables) is correct before further investigating what `SHOW RANGES` does with it.

**Comment by dikshant** [comment] 2023-07-28 21:39
I ran these queries from our docs [here](https://www.cockroachlabs.com/docs/stable/data-domiciling#step-5-verify-updated-replica-placement) to check for violations after replicating @codingconcepts original repro. 

I ran:
```sql
SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
```

Looks like we do have violating ranges here even though in @codingconcepts schema we do not use a Global Table.

```
  zone_id | subzone_id |       type       |       config       | report_id |        violation_start        | violating_ranges
----------+------------+------------------+--------------------+-----------+-------------------------------+-------------------
      104 |          0 | voter_constraint | +region=us-east1:2 |         1 | 2023-07-28 21:25:49.771258+00 |                4
(1 row)
```

Selecting more columns:

```sql
WITH
    partition_violations
        AS (
            SELECT
                *
            FROM
                system.replication_constraint_stats
            WHERE
                violating_ranges > 0
        ),
    report
        AS (
            SELECT
                crdb_internal.zones.zone_id,
                crdb_internal.zones.subzone_id,
                target,
                database_name,
                table_name,
                index_name,
                partition_violations.type,
                partition_violations.config,
                partition_violations.violation_start,
                partition_violations.violating_ranges
            FROM
                crdb_internal.zones, partition_violations
            WHERE
                crdb_internal.zones.zone_id
                = partition_violations.zone_id
        )
SELECT * FROM report;
```

I got the following result:

```
  zone_id | subzone_id |     target      | database_name | table_name | index_name |       type       |       config       |        violation_start        | violating_ranges
----------+------------+-----------------+---------------+------------+------------+------------------+--------------------+-------------------------------+-------------------
      104 |          0 | DATABASE meetup | meetup        | NULL       | NULL       | voter_constraint | +region=us-east1:2 | 2023-07-28 21:25:49.771258+00 |                4
(1 row)
```

My understanding is that is does point to an error in data placement itself instead of just `SHOW RANGES` being incorrect which is a deeper issue. @knz Does this method of checking data placement and the results seem correct to you?

cc: @rafiss @rimadeodhar @kevin-v-ngo

**Comment by j82w** [comment] 2023-07-31 15:01
We're in the process of reproducing the issue and investigating. We should hopefully have an update by tomorrow.

**Comment by j82w** [comment] 2023-08-01 20:06
> Show replicas and ranges by region (another row):
> 
> WITH
>   replicas AS (
>     SELECT DISTINCT
>       split_part(unnest(replica_localities), ',', 1) replica_localities,
>       replicas
>     FROM [SHOW RANGE FROM TABLE product FOR ROW ('eu-west3', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')]
>   ),
>   ranges AS (
>     SELECT
>       replicas,
>       range_id
>     FROM [SHOW RANGE FROM TABLE product FOR ROW ('eu-west3', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')]
>   )
> SELECT
>   split_part(re.replica_localities, '=', 2) region,
>   re.replicas,
>   array_agg(ra.range_id) range_ids
> FROM replicas re
> JOIN ranges ra ON re.replicas = ra.replicas
> GROUP BY re.replica_localities, re.replicas
> ORDER BY range_ids;
>    region   |    replicas    | range_ids
> ------------+----------------+------------
>   eu-west2  | {7,9,10,11,12} | {69}
>   eu-west3  | {7,9,10,11,12} | {69}
>   eu-north1 | {7,9,10,11,12} | {69}
>
>Expected behavior
>I would expect the query to show replicas and ranges by region (all) to show no overlap of replicas between regions.

This query is not properly mapping replica to region. The replicas column index position maps to the replica_localities array position.  Please try the following query.
```sql
SELECT DISTINCT
      split_part(unnest(replica_localities), ',', 1) replica_localities,
      unnest(replicas) replica,
      range_id
    FROM [SHOW RANGE FROM TABLE product FOR ROW ('eu-west3', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')];
```
| replica\_localities | replica | range\_id |
| :--- | :--- | :--- |
| region=eu-west2 | 8 | 71 |
| region=eu-west3 | 9 | 71 |
| region=eu-west3 | 10 | 71 |
| region=eu-north1 | 11 | 71 |
| region=eu-north1 | 12 | 71 |


@dikshant the replication is done asynchronously for new clusters when adding regions. It can take several minutes for the replication to complete and the ranges be moved to the correct region. Do you still see the violating_ranges after waiting for like 5 minutes?

**Comment by dikshant** [comment] 2023-08-02 18:19
I waited 10+ mins but on cockroach demo I am still seeing that the violating range is still present.

**Comment by arulajmani** [comment] 2023-08-02 19:51
@j82w it's hard to say, given you weren't able to reproduce the issue after following the same steps. 

@dikshant is this readily reproducible? If so, maybe file a new issue with reproduction steps and route to KV. It might also be helpful to grab a debug zip once you repro.

**Comment by dikshant** [comment] 2023-08-02 19:54
@arulajmani perhaps the issue I am seeing is only with demo which is where I have been testing it. I am making a proper MR cluster now and will add a repro and debug zip.

**Comment by dikshant** [comment] 2023-08-03 00:25
@arulajmani here is a debug zip, see below for repro steps.
https://drive.google.com/file/d/1Ilkl1vWS8CpyuNDku93dC9XLs0U9aI4k/view?usp=sharing

I tried this on a 23.1.7 on a 18 node multi region cluster in roachprod.

So this is interesting. Mapping replicas to replica_localities using @j82w 's fixed query shows the correct mappings:
```
root@localhost:26257/meetup> SELECT DISTINCT
                          ->       split_part(unnest(replica_localities), ',', 2) replica_localities,
                          ->       unnest(replicas) replica,
                          ->       range_id
                          ->     FROM [SHOW RANGE FROM TABLE product FOR ROW ('europe-west1', '2f22da46-d983-4878-8ad2-a6e6ff7e8f39')];
    replica_localities   | replica | range_id
-------------------------+---------+-----------
  region=europe-west1    |       7 |       69
  region=europe-west1    |       9 |       69
  region=europe-central2 |      11 |       69
  region=europe-central2 |      12 |       69
  region=europe-north1   |      15 |       69
(5 rows)
```

However, the violating range is still present and this is after waiting 10+ minutes:
```
root@localhost:26257/meetup> SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
  zone_id | subzone_id |       type       |       config       | report_id |        violation_start        | violating_ranges
----------+------------+------------------+--------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=us-east4:2 |         1 | 2023-08-02 23:44:58.271424+00 |                3
(1 row)

Time: 105ms total (execution 105ms / network 0ms)
```

# Reproduction steps:

1) Create a MR cluster. I used:
   ```
   roachprod create dikshant-test -n 18 --gce-zones 'us-east4-a','us-east4-a','us-east4-a','us- 
   central1-a','us-central1-a','us-central1-a','europe-west1-b','europe-west1-b','europe-west1- 
   b','europe-central2-b','europe-central2-b','europe-central2-b',"europe-north1-b","europe- 
   north1-b","europe-north1-b","us-west1-a","us-west1-a","us-west1-a" && roachprod stage. 
   dikshant-test release v23.1.7 && roachprod start dikshant-test:1-18
   ```

2) Apply the following DDL and DML:
   https://gist.github.com/dikshant/d4d170d70e493119b7cb6306aedb7551


3) Check for violating ranges after waiting for ~10 minutes:
   ```
   SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
   ```

It seems the violating range always has the primary region on the config. I don't know if this is expected behavior.

For example I ran an ALTER to change the primary region:
```
ALTER DATABASE "meetup" SET PRIMARY REGION "us-west1";
SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
```
And got:

```
  zone_id | subzone_id |       type       |       config       | report_id |        violation_start        | violating_ranges
----------+------------+------------------+--------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=us-west1:2 |         1 | 2023-08-03 00:11:17.833192+00 |                2
(1 row)
```

Whereas running:
```
SET alter_primary_region_super_region_override = 'on';
ALTER DATABASE "meetup" SET PRIMARY REGION "europe-west1";
```
Gives us:
```
SELECT * FROM system.replication_constraint_stats WHERE violating_ranges > 0;
  zone_id | subzone_id |       type       |         config         | report_id |        violation_start        | violating_ranges
----------+------------+------------------+------------------------+-----------+-------------------------------+-------------------
      116 |          0 | voter_constraint | +region=europe-west1:2 |         1 | 2023-08-03 00:16:19.488701+00 |                8
```

**Comment by arulajmani** [comment] 2023-08-03 16:48
@dikshant I'm going to close this out now that Irfan has created https://github.com/cockroachdb/cockroach/issues/108127 from your comment. 

@j82w addressed the initial issue.

**Closed by arulajmani** 2023-08-03 16:48 UTC
Labels: C-bug, T-kv
