### ISSUE TITLE
demo: error printed in sql shell when using cockroach demo and partitioning

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#39624] opened 2019-08-13 13:46 UTC
I ran cockroach demo using:
```SQL
./cockroach demo movr --nodes 3 --demo-locality=region=us-east1,region=us-central1,region=us-west1
```
Then I partitioned part of the database:
```SQL
root@127.0.0.1:64182/movr> show partitions from database movr;
E190813 13:44:15.872885 30010 sql/distsqlrun/server.go:609  [n1] context canceled: readerCtx in Inbox stream handler (local reader canceled)
E190813 13:44:15.873525 30553 sql/exec/colrpc/outbox.go:274  [n3,streamID=0] Outbox Recv connection error: rpc error: code = Unknown desc = context canceled: readerCtx in Inbox stream handler (local reader canceled)
E190813 13:44:15.876533 30522 sql/distsqlrun/server.go:609  [n1] context canceled: readerCtx in Inbox stream handler (local reader canceled)
E190813 13:44:15.876684 30012 sql/exec/colrpc/outbox.go:274  [n3,streamID=0] Outbox Recv connection error: rpc error: code = Unknown desc = context canceled: readerCtx in Inbox stream handler (local reader canceled)
  database_name | table_name | partition_name | parent_partition | column_names |                   index_name                   | partition_value |   zone_constraints
+---------------+------------+----------------+------------------+--------------+------------------------------------------------+-----------------+-----------------------+
  movr          | users      | chicago        | NULL             | city         | users@primary                                  | ('chicago')     | [+region=us-central1]
  movr          | users      | new_york       | NULL             | city         | users@primary                                  | ('new york')    | [+region=us-east1]
  movr          | users      | seattle        | NULL             | city         | users@primary                                  | ('seattle')     | [+region=us-west1]
  movr          | vehicles   | chicago        | NULL             | city         | vehicles@primary                               | ('chicago')     | [+region=us-central1]
  movr          | vehicles   | chicago        | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('chicago')     | [+region=us-central1]
  movr          | vehicles   | new_york       | NULL             | city         | vehicles@primary                               | ('new york')    | [+region=us-east1]
  movr          | vehicles   | new_york       | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('new york')    | [+region=us-east1]
  movr          | vehicles   | seattle        | NULL             | city         | vehicles@primary                               | ('seattle')     | [+region=us-west1]
  movr          | vehicles   | seattle        | NULL             | city         | vehicles@vehicles_auto_index_fk_city_ref_users | ('seattle')     | [+region=us-west1]
(9 rows)

Time: 18.176ms
```

**Comment by jordanlewis** [comment] 2019-08-19 13:41
Two issues here - one is that `demo` should probably not print any logs, even if they're errors. Second is that it's weird that we're treating these context cancellations as errors for logging purposes... @asubiotto is that expected?

**Comment by asubiotto** [comment] 2019-08-19 14:08
The distsql server logs any error it gets back from handling a `FlowStream` (be it in row or vectorized execution) as an error, so this isn't specific to context cancellations. Maybe that should be changed to a warning? Same thing could be said of the outbox.

**Comment by jordanlewis** [comment] 2019-08-23 14:27
Closing this as a duplicate of #39939 which focuses just on the demo issue.

**Closed by jordanlewis** 2019-08-23 14:27 UTC
Labels: A-partitioning, C-bug, S-3-ux-surprise

**Comment by knz** [comment] 2019-08-26 16:39
:+1: on downgrading context cancellation to warnings. We don't want error lines in log files either.
