### ISSUE TITLE
opt: bad index selected in single table query

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#38017] opened 2019-06-04 20:04 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#3390](https://cockroachdb.zendesk.com/agent/tickets/3390)
**Group:** Support
**Requester:** lee.burgess@unibet.com
**Organization:** Kindred Group
**Assignee:** Ricardo Rocha
**Issue escalated by:** Ricardo Rocha

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto">
<p dir="auto">tx_pte.txt contains the DDL and Statistics for the TX Table.</p>

<p dir="auto">If I actually execute the query and force/hint it to use the index “tx@tx_idx_3” it runs in 200 ms.</p>

<p dir="auto">Explain Plan </p>

<p dir="auto">&gt; tree       | field  |                        description
<br>&gt; +-----------------+--------+-----------------------------------------------------------+
<br>&gt; render          |        |
<br>&gt; └── index-join |        |
<br>&gt; │         | table  | tx@tx_pk
<br>&gt; └── scan  |        |
<br>&gt;            | table  | tx@tx_idx_3
<br>&gt;            | spans  | /"DEPOSIT_COMPLETED"/!NULL-/"DEPOSIT_COMPLETED"/PrefixEnd
<br>&gt;            | filter | updated &lt; (current_timestamp() - '30 days')
<br>&gt; (7 rows)
<br>&gt;  
<br>&gt; Time: 2.608133ms</p>

<p dir="auto">Real-time Execution:</p>

<p dir="auto">select * FROM tx@tx@tx_idx_3 AS tx0_
<br>WHERE tx0_.current_state
<br>    IN ('DEPOSIT_BLOCKED_BY_LIMIT',
<br>        'DEPOSIT_TRANSFER_RETRY',
<br>        'DEPOSIT_TRANSACTION_CREATED',
<br>        'DEPOSIT_INITIATED')
<br>    AND tx0_.updated &lt; current_timestamp() - interval '30 days'
<br>ORDER BY tx0_.updated ASC;</p>

<p dir="auto">Time: 271.145094ms
<br>  
<br>Without hinting it.</p>

<p dir="auto">Explain Plan </p>

<p dir="auto">&gt; tree       | field  |                        description
<br>&gt; +-----------------+--------+-----------------------------------------------------------+
<br>&gt; render         |        |
<br>&gt; └── sort      |        |
<br>&gt; │        | order  | +updated
<br>&gt; └── scan |        |
<br>&gt;           | table  | tx@tx_pk
<br>&gt;           | spans  | ALL
<br>&gt;           | filter | (current_state IN ('DEPOSIT_BLOCKED_BY_LIMIT',
<br>&gt; 'DEPOSIT_INITIATED', 'DEPOSIT_TRANSACTION_CREATED',
<br>&gt; 'DEPOSIT_TRANSFER_RETRY')) AND (updated &lt; (current_timestamp() - '30 days'))
<br>&gt; (7 rows)</p>

<p dir="auto">Real-time Execution:</p>

<p dir="auto">select * FROM tx AS tx0_
<br>WHERE tx0_.current_state
<br>    IN ('DEPOSIT_BLOCKED_BY_LIMIT',
<br>        'DEPOSIT_TRANSFER_RETRY',
<br>        'DEPOSIT_TRANSACTION_CREATED',
<br>        'DEPOSIT_INITIATED')
<br>    AND tx0_.updated &lt; current_timestamp() - interval '30 days'
<br>ORDER BY tx0_.updated ASC;</p>

<p dir="auto">Time: 4m39.544897691s</p>

<p dir="auto">We have implemented the work around where we force tbl@index and execution is around the 200-300 ms,  but why does the optimizer not choose the index as it is clearly faster.</p>
</div></blockquote>

**Comment by justinj** [comment] 2019-06-04 20:14
cc @rytaft, this is the issue I was telling you about that I think is fundamentally a histogram issue, though I don't know for sure. @ricardocrdb was asking if we had a GitHub issue for them, I don't think we do, right?

**Comment by rytaft** [comment] 2019-06-05 14:37
This first plan doesn't really make sense given the query -- the plan references "DEPOSIT_COMPLETED", while that value doesn't appear anywhere in the query. Are you sure this is the right plan?

If the index is on `current_state`, I would think we should be able to find the right plan and use that index. Since it looks like the customer is using 19.1.1, it would be great it they could rerun both queries (with and without hinting) using `EXPLAIN (opt, env) <query>`. Thanks!

**Comment by rytaft** [comment] 2019-06-05 14:39
Regarding histograms, I don't believe we have an issue, although I'm happy to create one if it would be helpful.

**Comment by RaduBerinde** [comment] 2019-06-20 18:37
I think that the problem here may be that the stats (in the ticket) show only 4 distinct values for `current_state`. So a filter like `IN ('DEPOSIT_BLOCKED_BY_LIMIT', 'DEPOSIT_TRANSFER_RETRY', 'DEPOSIT_TRANSACTION_CREATED', 'DEPOSIT_INITIATED')` has very high selectivity. In reality, some of these four values don't show up anywhere. This would indeed be fixed by histograms because we would be able to detect that there is little overlap between the values.

**Comment by rytaft** [comment] 2019-06-24 13:53
Ah good point -- didn't notice the attached file in the ticket. I agree that histograms are the long-term solution here, although I think there may be something we can do in the mean time. In particular, the fact that there are 4 distinct values before the filter and 4 after currently makes the stats code think that the filter is not selective at all (i.e., selectivity=1). I can try to tweak the code a bit to force filters such as this one to have selectivity < 1.

**Comment by RaduBerinde** [comment] 2019-06-24 14:20
Note that in this case the good plan has an index join, so I'm guessing the selectivity value would need to be quite small.

**Comment by rytaft** [comment] 2019-06-24 14:32
Good point - we won't be able to determine whether the index join is worth it without histograms. I just confirmed that we already do the right thing if the index is covering, so I don't think it's worth it to make the change I described above.

**Comment by rytaft** [comment] 2021-06-07 15:13
Closing this since histograms have been available for several releases now, and based on previous comments we thought they would fix this issue. If this user is still seeing a bad plan on a newer release feel free to open another issue.

**Closed by rytaft** 2021-06-07 15:13 UTC
Labels: A-sql-optimizer, C-investigation, no-issue-activity
