### ISSUE TITLE
circleci: failed tests: TestEagerReplication 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7456] opened 2016-06-24 01:54 UTC
The following test appears to have failed:

[#19578](https://circleci.com/gh/cockroachdb/cockroach/19578):

```
E160624 01:53:11.221197 storage/replica.go:1797  [node=1,store=1,range=5] error executing raft command: storage/replica.go:1707: no-op on empty Raft entry
I160624 01:53:11.221599 storage/replica_command.go:1575  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000123ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I160624 01:53:11.223095 client/db.go:474  failed batch: node unavailable; try another peer
W160624 01:53:11.223257 storage/intent_resolver.go:319  [node=1,store=1,range=4] failed to resolve intents: node unavailable; try another peer
I160624 01:53:11.224114 storage/engine/rocksdb.go:185  closing in-memory rocksdb instance
--- FAIL: TestEagerReplication (0.28s)
	replicate_test.go:45: expected 5 replicas in purgatory, but found 4
=== RUN   Example_rebalancing
W160624 01:53:11.224983 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
--- PASS: Example_rebalancing (0.90s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	62.794s
=== RUN   TestBatchBasics
I160624 01:53:26.082833 storage/engine/rocksdb.go:142  opening in memory rocksdb instance
I160624 01:53:26.084769 storage/engine/rocksdb.go:185  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160624 01:53:26.111896 storage/engine/rocksdb.go:142  opening in memory rocksdb instance
I160624 01:53:26.113855 storage/engine/rocksdb.go:185  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.04s)
=== RUN   TestBatchGet
I160624 01:53:26.133565 storage/engine/rocksdb.go:142  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-06-24 01:56
Duplicate of #7444.

**Closed by petermattis** 2016-06-24 01:56 UTC
Labels: Robot, test-failure
