### ISSUE TITLE
Allow operators to rate limit new connections

### ISSUE THREAD

**Issue by joshimhoff** [cockroachdb/cockroach#54759] opened 2020-09-24 17:54 UTC
**Is your feature request related to a problem? Please describe.**
If you open up too many connections per unit time, bc/ e.g. you aren't using connection pooling, CRDB will spend all its CPU time in password hashing algorithms. This is bad user experience. If CRDB provided a means to rate limit new connections, being rate limited would signal "you are using CRDB incorrectly, plz use a connection pool". It would signal this more clearly IMHO than "oh huh I have no CPU left to serve queries". In fact, we could even include something like the first block of text in the error message returned when the rate limiting kicks in. As is, users have a bad experience and they don't in practice easily figure out why & fix it.

This is one aspect of a much broader story: CRDB should degrade gracefully under different kinds of load.

**Describe the solution you'd like**
I am imaging some way to indicate a desired rate of new connections, possibly over different time periods. Maybe a cluster setting?

**Additional context**
This happens often on CC clusters. It leads to SRE oncall being paged. So much CPU is used that even basic single row reads to our test DB fail.

**Comment by ajwerner** [comment] 2020-09-24 17:57
I feel like there are easier and harder versions of this. The easiest version is to rate limit per node with no concern for users. Fancier would be a global rate-limit coordinated through some distributed token bucket with some policies per role.

**Comment by lunevalex** [comment] 2021-12-02 23:06
@joshimhoff it seems like its a dupe of #47602.

**Closed** 2021-12-02 23:09 UTC
Labels: C-enhancement, A-sql-execution, O-sre, T-sql-queries
