### ISSUE TITLE
storage: we're dialing nodes under the `raftMu`

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#40529] opened 2019-09-05 23:42 UTC
This issue seems to have two parts. One seems very bad, the other one is test-only. But maybe they're really one and the same; I don't really know. I'll let someone else judge the matter.

1) It would appear that we attempt to dial a connection while holding the `raftMu`.
This is no bueno at all (is it?), cause dialing can take arbitrarily long (I don't even see a timeout around this dialer).
https://github.com/cockroachdb/cockroach/blob/b3190af2fd41741affa9de4d183abaff52fac5f2/pkg/storage/raft_transport.go#L594
FWIW here's a stack trace of it in action:
```
    rpc            context.go:344             (*Connection).Connect(#1256, #12, #261, 0x4, #1256, #1235)
    nodedialer     nodedialer.go:147          (*Dialer).dial(*Dialer(#135), Context(#12), NodeID(0x4), Addr(#1232), *wrappedBreaker(#1258), ConnectionClass(0x0), ...)
    nodedialer     nodedialer.go:90           (*Dialer).Dial(*Dialer(#135), Context(#12), NodeID(0x4), ConnectionClass(0x4))
    storage        raft_transport.go:594      (*RaftTransport).startProcessNewQueue(*RaftTransport(#578), Context(#12), NodeID(0x4), ConnectionClass(0x1f0))
    storage        raft_transport.go:562      (*RaftTransport).SendAsync(*RaftTransport(#578), *RaftMessageRequest(#1225), ConnectionClass(0x0))
    storage        replica_raft.go:1182       (*Replica).sendRaftMessageRequest(*Replica(#1087), Context(#12), *RaftMessageRequest(#1225), 0x4)
    storage        replica_raft.go:1147       (*Replica).sendRaftMessage(*Replica(#1087), Context(#12), Message(0x3), 0x3, 0x7, 0x7, 0x23, #1257, ...)
    storage        replica_raft.go:1089       (*Replica).sendRaftMessages(*Replica(#1087), Context(#12), []Message(#1230 len=2 cap=2))
    storage        replica_raft.go:639        (*Replica).handleRaftReadyRaftMuLocked(*Replica(#1087), Context(#12), IncomingSnapshot(0x0), 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    storage        replica_raft.go:432        (*Replica).handleRaftReady(*Replica(#1087), Context(#12), IncomingSnapshot(0x0), 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    storage        store.go:3684              (*Store).processReady(*Store(#660), Context(#12), RangeID(0x7))
    storage        scheduler.go:227           (*raftScheduler).worker(*raftScheduler(#581), Context(#12))
    storage        scheduler.go:161           (*raftScheduler).Start.func2(*raftScheduler(#12), Context(#714))
```

2) In tests using the `TestCluster` it would appear that 1) can actually cause a hung cluster when a node in the cluster is `Stop()ed`. Like, I actually see that `Dial` be blocked for a minute and I see other proposals trying to get the mutex.
Why does this happen so easily in tests, where I guess we haven't seen this in the wild? A difference is that in tests, when you stop a server, no process gets killed, and so the listening port is maybe in a different state that it'd be if the process did get killed (and in the latter case, `Dial()` presumably fails. Except I've traced through the `Server` listener code with @ajwerner and it would appear that we do close the listener when the stopper is stopped (so I guess we'd expect `Dial()` to also fail... and yet it doesn't).
The closing of the listener happens here:
https://github.com/cockroachdb/cockroach/blob/57ca9600603e788ec3f96f384fafe2821eb6a92f/pkg/server/server.go#L1708

Another interesting bit is that, in the case that I've caught, the `TestCluster` was shutting down when I saw a `Replica.evalAndPropose()` block for one minute.

**Comment by tbg** [comment] 2019-09-06 07:19
Duplicate of https://github.com/cockroachdb/cockroach/issues/40529

**Comment by tbg** [comment] 2019-09-06 07:20
Err, I mean https://github.com/cockroachdb/cockroach/issues/40362

**Closed by tbg** 2019-09-06 07:19 UTC
Labels: A-core-replication, C-bug
