### ISSUE TITLE
cdc: Support starting changefeeds with cursor in restored clusters

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#43371] opened 2019-12-19 21:38 UTC
**Is your feature request related to a problem? Please describe.**
As a part of the registration cluster migration to CockroachCloud, we had to stop changefeeds on the old cluster and start a new changefeed process in the new cluster. I'd expect to be able to restart the changefeed in the new cluster where the old changefeed left off, but that isn't possible today. Changefeeds require MVCC histories for keys so that they can stream udpates that fall after the `high_water_timestamp` that is passed to the `with cursor =` option when the changefeed is created. Unfortunately, although we can backup with revision histories, we are not able to restore clusters with the histories intact. 

This means that when restoring a cluster, you cannot start a changefeed using the `with cursor =` option. This leads to all sorts of unpleasantness: 

- I have to restart the changefeed from the beginning of time which means that all of the data that had previously been streamed to my cloud sink will be streamed there again, incurring the relevant S3 data transfer costs
- Due to #43103, we can require multiple days for a catch up scan to re-process and re-send existing data in tables to a cloud storage sink depending on the size of the tables. This effectively means that I will not have my CDC job running while it is catching up - new events are not streamed until the job catches up.
- This requires a bunch of config changes on the Snowflake side. Snowflake auto-ingestion has to be disabled while the data is resent, and the existing tables need to be truncated and then the new data needs to be re-ingested and auto-ingestion reconfigured

Jira issue: CRDB-5284

**Comment by miretskiy** [comment] 2021-08-10 13:09
Personally, I think restoring running jobs is fraught with dangers.  on error pause will not help here since revision histories are messed up anyway.  I kinda thing it's working as intended.  @amruss what do you think?

**Comment by mwang1026** [comment] 2021-08-10 14:04
Well there's a deeper core problem here of "we don't restore revision history so you can't restart a changefeed even if you wanted to" but yes, if you all deem it unnecessary work then we can close this and not worry about the "restoring revision history" issue.

When we do file based streaming in the future, that actually could be an interesting "replay from streamed backup files on s3" as a way to accomplish the same outcome which is probably superior to this.

**Comment by piyush-singh** [comment] 2021-08-10 15:20
Perhaps I should not have specified my desired solution and instead focused on the problem. I don't know that restarting with a cursor is exactly what I need; it could be that restarting without a backfill as Michael pointed out above is enough. I think the core user problem is that if I have to restore a backup of a CRDB cluster, I might have to wait days for CDC to get into a healthy (caught up) state. Even if my RPO is okay, my RTO is suddenly multiple days if I had any critical service or system that depended on CDC downstream from cockroach.

**Closed** 2023-01-09 17:35 UTC
Labels: A-cdc, T-cdc
