### ISSUE TITLE
sql: support USING btree in combination with a function

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#64861] opened 2021-05-07 00:16 UTC
**Is your feature request related to a problem? Please describe.**
In PG the following is supported
`CREATE UNIQUE INDEX ON customers USING btree (lower((email)::text));`

**Describe the solution you'd like**
Ability to create a btree unique index with another function surrounding the column should work.

**Describe alternatives you've considered**
I created a computed column with lower() and creating a unique index with btree works but requires an additional column.

**Additional context**

```sql
drop table if exists customers;

create table customers (
    id uuid not null default gen_random_uuid() primary key,
    first_name string,
    last_name string,
    email text 
);

insert into customers (first_name, last_name, email)
    values ('Artem', 'Ervits', 'Artem@cockroachlabs.com');

CREATE UNIQUE INDEX ON customers USING btree (lower((email)::text));


root@127.0.0.1:52031/defaultdb> CREATE UNIQUE INDEX ON customers USING btree (lower((email)::text));
invalid syntax: statement ignored: at or near ")": syntax error: unimplemented: this syntax
SQLSTATE: 0A000
DETAIL: source SQL:
CREATE UNIQUE INDEX ON customers USING btree (lower((email)::text))
                                                                  ^
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/9682/v20.2
```

the following works

```sql
drop table if exists customers;

create table customers (
    id uuid not null default gen_random_uuid() primary key,
    first_name string,
    last_name string,
    email_old text,
    email text as (lower(email_old)::text) stored
);

CREATE UNIQUE INDEX ON customers USING btree (email);

insert into customers (first_name, last_name, email_old)
    values ('Artem', 'Ervits', 'Artem@artem.com'),
    ('A', 'B', 'abc@ABC.COM');
```

**Comment by otan** [comment] 2021-05-07 00:26
duplicate of https://github.com/cockroachdb/cockroach/issues/9682.

**Closed by otan** 2021-05-07 00:26 UTC
Labels: C-enhancement
