### ISSUE TITLE
sql: Drop database statement does not work with tables having foreign keys

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#10830] opened 2016-11-19 13:11 UTC
Steps to reproduce:

```
create database test;
set database=test;

CREATE TABLE customers (id INT PRIMARY KEY, email STRING UNIQUE);

CREATE TABLE products (sku STRING PRIMARY KEY, price DECIMAL(9,2));

CREATE TABLE orders (
  id INT PRIMARY KEY,
  product STRING NOT NULL REFERENCES products,
  quantity INT,
  customer INT NOT NULL CONSTRAINT valid_customer REFERENCES customers (id),
  CONSTRAINT id_customer_unique UNIQUE (id, customer),
  INDEX (product),
  INDEX (customer)
);

drop database test;
```

- Expected result: The database `test` should be dropped, the command emitting: `DROP DATABASE`
- What is happening: The command emits: `pq: table "customers" is being dropped` and the database `test` still exist.

**Comment by tlvenn** [comment] 2016-11-19 13:14
I am running cockroachdb build: beta-20161110-255-gfc005be @ 2016/11/18 13:49:57 (go1.7.3)
I have built it from master yesterday.

**Comment by tlvenn** [comment] 2016-11-22 04:41
@knz any idea what is causing this ? Could it has to do with the order in which tables are dropped ?

**Comment by knz** [comment] 2016-11-22 08:00
cc @vivekmenezes @dt @andreimatei

**Comment by knz** [comment] 2016-11-22 08:02
This might be a duplicate of #8497. @dt what do you think?

**Closed** 2016-12-05 22:49 UTC
Labels: bug, ux-surprise
