### ISSUE TITLE
sql: the infrastructure in #44947 is probably defective in geo-dist clusters

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#45578] opened 2020-03-02 13:59 UTC
The PR #44947 is "not hooked up"  but introduces a cluster-wide system table for "diagnostics requests".

I have a hard time believing this was designed with geo-distributed clusters in mind. The way I read the PR description (which is rather short) is that every node would periodically poll from `system.statement_diagnostics_request` and write every matching query to `system.statement_diagnostics` when there are matching requests.

How is this not going to incur periodic cross-region polls requests and intense cross-region writes when an app happens to be geo-distributed and also match a request?

**Comment by RaduBerinde** [comment] 2020-03-02 14:37
I don't see it as a problem, it's a small query on `statement_diagnostics_request` every 10 seconds. We only get a result and then write to `statement_diagnostics` once per *manually*-requested statement diagnostics.

But I'm not sure why we poll at all since we added a gossip notification mechanism.

**Comment by andreimatei** [comment] 2020-03-02 15:10
The polling is async, if that alleviates your concerns...

The thing with gossip is that I don't think gossiping across SQL gateways (as opposed to between lower levels of the system) will be with us for much longer. @ajwerner is already trying to get rid of the various gossip users to make room for ephemeral gateways. I'd get rid of the polling in favor of a change feed, but that's not quite there yet. So for now I've added the gossip trigger just as an optimization, but I don't want to depend on it.

**Comment by andreimatei** [comment] 2020-03-02 21:06
Can I close?

**Comment by ajwerner** [comment] 2020-03-03 19:26
@knz this is an attempt to capture my views of the discussion we had offline earlier.

## Concerns with this subsystem as I understand them

There are two elements to this new subsystem which draw my ire. The remaining 3 points I heard and want to explore. 

1) The gossip for low-latency notification of requests on all gateways

This is primarily problematic to me because of a desire to decouple the SQL layer from the gossip network. Gossip is valuable to broadcast information to nodes which should be available either 1) prior to cluster bootstrap or 2) in the face of range unavailability. Things like network address mappings are the perfect example of something that should live in gossip.

Cluster settings are another interesting case but given you can't write to them without the KV being available I'm less sure.

2) The polling for eventual discovery

The polling is lame because, as you noted, it is likely to incur regular cross-region communication from each gateway to the leaseholder of this table. In most cases, the gossip should be sufficient to notify gateways of the need to update. In general this is just extra traffic. That being said, it should be quite low throughput in the common case.

I'm especially okay with the polling because it is a simple concept on top of stable interfaces which can easily be replaced later.

3) Network traffic due to periodic polling over WAN links

I suspect that this is extremely low bandwidth. If we have 100 nodes and 10 active requests which we'll say are at most 1kb we're talking about 100Kbyte/s total, not all of which will be over a WAN link. Gzip compression will also help with these responses. 1kb is probably wildly conservative. Most of the time there will be no active requests.

4) Cost of writing to the durable KV - especially in the context of lower durability requirements

We're talking about a couple hundred bytes in response to explicit user action. We write more than this to the range log. I suspect that that too bothers you but I'm not sure I understand the exact root cause of that ire. High latency reads and writes in exchange for high availability is a reasonable choice in the tradeoff space that makes sense for both of these use cases.

Writes to the distributed KV will be unavailable if a quorum is down. System tables should be replicated. Temporary unavailability should be tolerated. I don't think that partitioning the writes to this sort of table is an overwhelmingly pressing problem. We could do it but that would lead to other tradeoffs such as reduced total system availability in the face of region failure - that seems like a bad tradeoff to make.

5) Availability of this subsystem

I am unsure that I understand this concern. Replicated system ranges are highly available. Perhaps this was in relation on to a vision of the subsystem where the data were partitioned. In the face of leaseholder failure they will need to wait out the epoch expiration but that's a well understood failure mode that doesn't keep me up at night when thinking about SQL and certainly doesn't concern me for this feature. 

## My visions for a proper implementation - Rangefeeds

Rangefeeds represent a pretty ideal data distribution architecture for this use case. They can be created on follower replicas. When writes gets replicated to the followers they will be propagated to the gateways in that region. We could replace both the polling and gossip with rangefeeds.

Had we coordinated earlier I would have liked to use rangefeeds for this feature. Rangefeeds are currently gated behind a cluster setting. This setting defaults to off because rangefeeds require the addition of logical operations to raft commands which incurs some overhead (I believe Nathan measured it to be 4-5% in TPC-C). My intention early in the next cycle is to make the control of this option finer-grained and specifically to enable rangefeeds on system ranges unconditionally as the overhead is acceptable there. There's more we can do to optimize that overhead but that's a separate discussion.

In general, every subsystem which needs to respond to state changes and can reasonably be unavailable if the database is unavailable (read: some ranges are unavailable) should be using rangefeeds. 

I'll add that my feeling we shouldn't be going out of our way to optimize availability in the face of total region failure. I don't think this is super controversial but maybe it is. HA, multi-region deployments should spread their data over multiple AZs. That should provide robustness to most events. If the goal is to attain high availability and low-latency reads while supporting a threat model that includes full region failure then we should prioritize the work to implement consistent read replicas in our KV (I think these things will prove to be darn valuable). 

## Philosophical point

We absolutely should be worried about building features which will behave poorly in global contexts. Furthermore we should understand the requirements when building features. 

That being said, we must not assume that because our KV provides stronger guarantees than we require that it is the wrong choice to build a feature. A core tenant of our database is that serializable transactions aren't too expensive for your every day use cases. Looking to utilize anything other than the KV (or better yet SQL) in the course of feature implementation has both a cost and implementation burden. Solutions which are more optimized for their problem but require new investment are likely to detract resources which could be used to improve our core offering. 
Lack of functionality that prevents proper implementation of a feature should be understood. If it affects our ability to build functionality inside of cockroach, it likely affects our users ability to build on top of cockroach. The bar to justify building stateful features outside of the SQL execution path on top of anything other than the KV (or SQL) should be very high.

I will grant that there is a whole family of features for which the above philosophy is not valid: features related to observing and debugging internal database functionality which provide critical value when the cluster is not available.

**Comment by knz** [comment] 2020-03-03 22:33
> I will grant that there is a whole family of features for which the above philosophy is not valid: features related to observing and debugging internal database functionality which provide critical value when the cluster is not available.

Circling back to why I opened this issue in the first place: tracing of SQL queries falls under this description.

The rest of your explanations I can stand behind.

**Comment by ajwerner** [comment] 2020-03-03 23:22
> Circling back to why I opened this issue in the first place: tracing of SQL queries falls under this description.

While I imagine there are some cases where that's true, I suspect that the majority of cases where tracing is going to provide value is when queries complete but are in some way surprising, such as being slow.

Fortunately I think we're quite close to providing a story related to tracing that utilizes external trace collectors and interacts nicely with this feature. Today we offer support for tracing with zipkin and lightstep. Unfortunately our current implementation involving these tracers is less than ideal. The most glaring problem I've experiences from the Zipkin tracer (and is also the case with the ligthstep tracer) is that we only support tracing 100% of queries. 

I think that I'd be more willing to use these features if we offered

1) Controllable sampling rate
2) Sampling decisions tied into this specific feature
3) Sampling decision controlled with a connection setting

I suspect that in cases where I wanted to use tracing to debug production issues, I would set up tracing to talk to a collector but set sampling to 0 so as to not incur any overhead in the usual case. I would then anticipate using 3) above. 2) would be straightforward in the case that we did any of these things and would complement the functionality we've already implemented nicely. In short, if we had more sophisticated control of sampling policies in our tracers which hooked into the decisions of this system then we might have a story to tell even in the face of cluster unavailability.

There is something of a fundamental problem with trying to rely on tracing to debug hung clusters. Cockroach makes the somewhat uncommon decision of having requests hang indefinitely at low levels of the system in the face of unavailability. In these cases we're unlikely to see any spans published to a trace collector.

I actually would like to see work on this outside of the context of this specific feature and additionally outside of the context of debugging unavailable clusters. 100% sampling is effectively unusable for high throughput systems but it's all we offer.

Also of interest with regards to external tracing systems would be providing a mechanism for clients to hand us trace IDs and whether we should trace a given query (https://github.com/cockroachdb/cockroach/issues/19403).

**Comment by andreimatei** [comment] 2020-03-03 23:24
> Circling back to why I opened this issue in the first place: tracing of SQL queries falls under this description.

So is this about geo-distribution or is it about unavailability? And is it about the polling or is about the insertion of the request to trace?

My view is that, if your system ranges are unavailable, what you want to do is something else rather than trace a user query. We already have specific "alerting" for unavailable ranges, and tracing doesn't really help you debug anything about them. You're gonna look at the range report, see what nodes the replicas are on, and then see why some of those nodes are dead.
As things stand, if you've come to the tracing page in the UI because "the cluster is down" and you don't really know what to do so you're pushing random buttons, the fact that you'll fail to create a tracing request when the respective range is unavailable is actually a better indication to the user about "what's wrong with the cluster" than if we managed to trace a query that touches an unavailable range. Such a query generally just hangs in some RPC - trying to acquire a range lease or waiting for the replication of a command. And when it hangs, you don't get a trace back. Even if the query as a whole does not hang (say, if you set a timeout for it), the RPC to the interesting range still doesn't respond and your trace is still missing what would probably be the more interesting part of the trace.

So I don't think that getting this query tracing thing to work when that respective system range is not available is too important. When I was writing the thing, I had considered building it such that the node that's trying to create the request can do everything locally as a contingency (remember the request, trace the query, store the trace?), but it seemed very complicated to serve an UI from this in-memory state - and again I didn't see a very clear benefit.

**Comment by knz** [comment] 2020-03-03 23:31
In my ideal world, there are two networks: a monitoring/tracing network (more-or-less what we call UI + monitoring + logging + time series + liveness  today), and a storage network (more or less SQL + KV).

The monitoring network would have near-zero persisted state and would only use persisted state for cachine. In particular it would "just work" if its storage would disappear under it and restarted with a blank state.

In that world, "tracing a query" is the user pressing a button in the monitoring network. That then instructs the storage layer to start a trace, via a RPC. The storage network then export the output of the trace to a collector in the monitoring network. There's not storage operation involved in the entire tracing.
 

(There's a totally orthogonal discussion about whether an unavailable range should cause a KV op to hang indefinitely. We know the current behavior is problematic. The jury is still out on this one but I suspect the way forward is to have the client decide based on a deadline / completion trade-off, which is done at the level of the client app.)

**Comment by ajwerner** [comment] 2020-03-03 23:40
That's a good, if large, vision. I'm supportive in theory though am unsure of the priority of such an investment right now. In the shorter term I'm hopeful that we can usefully leverage existing tools to monitor our system out of band. Time series, tracing, network logging / log evacuation are spaces with a lot of mature solutions. Furthermore I anticipate that customers already have preferences for how they'd like to utilize this sort of information. My feeling is that we should invest in understanding their current behaviors and preferences before embarking to build such tools inside of cockroach. 

> (There's a totally orthogonal discussion about whether an unavailable range should cause a KV op to hang indefinitely. We know the current behavior is problematic. The jury is still out on this one but I suspect the way forward is to have the client decide based on a deadline / completion trade-off, which is done at the level of the client app.)

Did intend to open that can of worms. I generally agree about client timeouts. I was merely remarking on the negative interaction of this behavior with tracing in the context of debugging hung requests.

**Comment by andreimatei** [comment] 2020-03-03 23:43
> In that world, "tracing a query" is the user pressing a button in the monitoring network. That then instructs the storage layer to start a trace, via a RPC. The storage network then export the output of the trace to a collector in the monitoring network. There's not storage operation involved in the entire tracing.

Just to make sure there's no confusion about the feature we're discussing: this feature doesn't "start a trace"; it registers the desire to trace a query that will come asynchronously in the future, to any node. You can "start a trace" directly using `set tracing=on; my_query;` or with the upcoming `explain (bundle) my_query`. The former does not depend on any storage.

**Comment by knz** [comment] 2020-03-04 00:06
>  it registers the desire to trace a query that will come asynchronously in the future, to any node

Agreed but that still doesn't need persistence, a simple bookeeping on every node of requests registered via the RPC would be sufficient.

**Comment by knz** [comment] 2020-03-04 00:06
@andy-kimball I think I am satisfied by the information provided regarding the original concern, but as you can see in this thread we now have collected further insight that may orient further development in the future. How do you suggest we capture this insight so it doesn't get lost?

**Comment by andreimatei** [comment] 2020-05-21 19:08
Closing this; I don't think keeping it open more serves anything.

**Closed by andreimatei** 2020-05-21 19:08 UTC
Labels: A-tracing, C-bug
