### ISSUE TITLE
sql: Hibernate tries to load SERIAL types into an int

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#22607] opened 2018-02-12 19:54 UTC
Hibernate tries to load SERIAL types into an int, which fails if they are too large - testDirectIdPropertyAccess

We can likely use sequences to combat this but will need to investigate and test. 

Referenced in [16491](https://github.com/cockroachdb/cockroach/issues/16491)

**Comment by vilterp** [comment] 2018-02-12 19:59
Another solution is to make Hiberate use a java `long`, which is 64 bits, so it shouldn't fail to load a SERIAL value. Need to try & test that as well.

**Comment by knz** [comment] 2018-06-22 11:38
I think this may be a duplicate of #24062.

**Closed** 2018-08-16 21:44 UTC
Labels: A-sql-pgcompat, A-sql-semantics, C-enhancement
