### ISSUE TITLE
stability: OOM on beta

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8056] opened 2016-07-27 13:20 UTC
`beta` nodes are getting into OOM situations again.
We're on the same machine types as before: 4vCPUs, 15GB ram.

Nothing particularly out of the ordinary though.
This happened on two nodes overnight:

`cockroach@104.196.157.72`

OOM killer info:

```
[309129.613310] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
<snip>
[309129.797303] [ 3199]     0  3199   228385     1498      43        0             0 block_writer
[309129.863136] [32388]     0 32388   159898     1592      40        0             0 photos
[309129.871357] [29494]     0 29494  7765868  3722173   14931        0             0 cockroach
[309129.887937] Out of memory: Kill process 29494 (cockroach) score 939 or sacrifice child
[309129.896054] Killed process 29494 (cockroach) total-vm:31063472kB, anon-rss:14888692kB, file-rss:0kB
```

Last few minutes of mem stats:

```
I160727 02:08:16.602654 server/status/runtime.go:189  runtime stats: 12 GiB RSS, 2849 goroutines, 2.2 GiB/2.3 GiB/4.9 GiB GO alloc/idle/total, 6.3 GiB/7.8 GiB CGO alloc/total, 365.49cgo/sec, 0.07/0.01 %(u/s)time, 0.00 %gc (0x)
I160727 02:08:26.602190 server/status/runtime.go:189  runtime stats: 12 GiB RSS, 2869 goroutines, 1.8 GiB/2.7 GiB/4.9 GiB GO alloc/idle/total, 6.0 GiB/7.4 GiB CGO alloc/total, 93134.17cgo/sec, 1.31/0.36 %(u/s)time, 0.00 %gc (2x)
I160727 02:08:36.668620 server/status/runtime.go:189  runtime stats: 12 GiB RSS, 2885 goroutines, 2.8 GiB/2.0 GiB/5.2 GiB GO alloc/idle/total, 6.0 GiB/7.4 GiB CGO alloc/total, 82462.83cgo/sec, 2.01/0.57 %(u/s)time, 0.01 %gc (2x)
I160727 02:08:46.601997 server/status/runtime.go:189  runtime stats: 13 GiB RSS, 2885 goroutines, 4.2 GiB/1.4 GiB/6.0 GiB GO alloc/idle/total, 6.7 GiB/8.1 GiB CGO alloc/total, 139470.91cgo/sec, 1.92/0.62 %(u/s)time, 0.00 %gc (1x)
I160727 02:08:56.602265 server/status/runtime.go:189  runtime stats: 13 GiB RSS, 2873 goroutines, 4.2 GiB/1.4 GiB/6.0 GiB GO alloc/idle/total, 6.7 GiB/8.1 GiB CGO alloc/total, 364.89cgo/sec, 0.59/0.18 %(u/s)time, 0.00 %gc (0x)
I160727 02:09:06.615660 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2876 goroutines, 2.7 GiB/3.0 GiB/6.0 GiB GO alloc/idle/total, 6.7 GiB/8.2 GiB CGO alloc/total, 367.32cgo/sec, 0.88/0.21 %(u/s)time, 0.00 %gc (1x)
I160727 02:09:16.604380 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2871 goroutines, 4.0 GiB/1.7 GiB/6.1 GiB GO alloc/idle/total, 6.7 GiB/8.1 GiB CGO alloc/total, 368.25cgo/sec, 0.95/0.24 %(u/s)time, 0.00 %gc (0x)
I160727 02:09:26.602858 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2858 goroutines, 2.7 GiB/3.0 GiB/6.1 GiB GO alloc/idle/total, 6.6 GiB/8.0 GiB CGO alloc/total, 369.35cgo/sec, 0.93/0.23 %(u/s)time, 0.00 %gc (1x)
I160727 02:09:36.631386 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2849 goroutines, 3.8 GiB/1.9 GiB/6.1 GiB GO alloc/idle/total, 6.6 GiB/8.0 GiB CGO alloc/total, 363.36cgo/sec, 0.64/0.13 %(u/s)time, 0.00 %gc (0x)
I160727 02:09:46.602138 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2306 goroutines, 4.1 GiB/1.6 GiB/6.1 GiB GO alloc/idle/total, 6.6 GiB/8.0 GiB CGO alloc/total, 363.62cgo/sec, 0.10/0.02 %(u/s)time, 0.00 %gc (0x)
I160727 02:09:56.621500 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2311 goroutines, 4.2 GiB/1.6 GiB/6.1 GiB GO alloc/idle/total, 6.5 GiB/7.8 GiB CGO alloc/total, 370.55cgo/sec, 0.34/0.10 %(u/s)time, 0.00 %gc (0x)
I160727 02:10:06.602473 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2329 goroutines, 4.2 GiB/1.6 GiB/6.1 GiB GO alloc/idle/total, 6.5 GiB/7.8 GiB CGO alloc/total, 366.14cgo/sec, 0.21/0.06 %(u/s)time, 0.00 %gc (0x)
I160727 02:10:16.603268 server/status/runtime.go:189  runtime stats: 14 GiB RSS, 2325 goroutines, 4.2 GiB/1.6 GiB/6.1 GiB GO alloc/idle/total, 6.5 GiB/7.8 GiB CGO alloc/total, 364.67cgo/sec, 0.02/0.00 %(u/s)time, 0.00 %gc (0x)
I160727 02:10:26.624179 server/status/runtime.go:189  runtime stats: 13 GiB RSS, 2650 goroutines, 4.2 GiB/1.5 GiB/6.1 GiB GO alloc/idle/total, 6.0 GiB/7.5 GiB CGO alloc/total, 11778.71cgo/sec, 0.08/0.03 %(u/s)time, 0.00 %gc (0x)
```

While it does look like a temporary increase in both Go and CGo memory, it's enough to get us over the edge.
Heap diffs show an increase in grpc.recvMsg (between two of the more interesting heap profiles, not the final one):

```
go tool pprof --base memprof.2016-07-27T02_08_26.786  ../cockroach memprof.2016-07-27T02_08_46.772 
Entering interactive mode (type "help" for commands)
(pprof) top
860.49MB of 709.28MB total (  100%)
Dropped 1383 nodes (cum <= 3.55MB)
      flat  flat%   sum%        cum   cum%
  860.49MB   100%   100%   860.49MB   100%  google.golang.org/grpc.(*parser).recvMsg
         0     0%   100%   858.91MB   100%  github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1
         0     0%   100%   858.91MB   100%  github.com/cockroachdb/cockroach/storage.(*RaftTransport).RaftMessage.func1.1.1
         0     0%   100%   859.91MB   100%  github.com/cockroachdb/cockroach/storage.(*multiRaftRaftMessageServer).Recv
         0     0%   100%   857.91MB   100%  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1
         0     0%   100%   859.91MB   100%  google.golang.org/grpc.(*serverStream).RecvMsg
         0     0%   100%   859.91MB   100%  google.golang.org/grpc.recv
         0     0%   100%   709.28MB   100%  runtime.goexit
```

Final heap pdfs for:
go: [node2.go.heap.pdf](https://github.com/cockroachdb/cockroach/files/386107/node2.go.heap.pdf)
cgo: [node2.cgo.heap.pdf](https://github.com/cockroachdb/cockroach/files/386109/node2.cgo.heap.pdf)

Copy of all logs (including last 50 memprof and jeprof files) can be found on:

```
cockroach@104.196.157.72:~/logs.8056
cockroach@104.196.153.89:~/logs.8056
```

**Comment by mberhault** [comment] 2016-07-27 14:21
@bdarnell: is there any memory-related work going on?

**Comment by bdarnell** [comment] 2016-07-27 16:25
The only current work related to snapshot memory usage is @tamird's work to introduce snapshot acknowledgements. Unclear whether that would fix the issue here or not.

The most interesting thing I see in the logs is that we are getting multiple non-preemptive snapshots being applied in parallel:
```
cockroach@104.196.153.89: I160727 15:52:01.393000 storage/replica_raftstorage.go:587  store=5:5 ([]=/mnt/data) range=1584 [/Table/51/1/4296226427003495721/"8931c524-d235-4865-93c6-c9ec27b78b3d"/1425533-/Table/51/1/4298426712627684273/"29ddce67-4ff7-41e8-b2d7-8e749d3d76da"/627218): with replicaID 23, applying Raft snapshot for range 1584 at index 110293 (encoded size=64122279, 112564 KV pairs, 2 log entries)
cockroach@104.196.153.89: I160727 15:52:01.447843 storage/replica_raftstorage.go:587  store=5:5 ([]=/mnt/data) range=4019 [/Table/51/1/5349958056598016447/"c4bc6ab8-bc1f-433a-9c5a-0f76301bda5c"/433080-/Table/51/1/5352182114829582530/"5d03b71f-7582-432c-88a6-1c695a3f4fa4"/4857044): with replicaID 18, applying Raft snapshot for range 4019 at index 85858 (encoded size=63319044, 113202 KV pairs, 59 log entries)
cockroach@104.196.153.89: I160727 15:52:01.469215 storage/replica_raftstorage.go:587  store=5:5 ([]=/mnt/data) range=3900 [/Table/51/1/6882515983394598571/"0419fe63-e906-4ed4-9651-0371c77b77a1"/55429-/Table/51/1/6884720455317757018/"15eecf25-c738-4df9-84ac-9425f09eea4f"/2795432): with replicaID 21, applying Raft snapshot for range 3900 at index 84406 (encoded size=63353153, 112785 KV pairs, 11 log entries)
cockroach@104.196.153.89: I160727 15:52:01.712239 storage/replica_raftstorage.go:587  store=5:5 ([]=/mnt/data) range=4856 [/Table/54/1/"#\x82\xaa&=LD!\xab\xfdD?\x14\xc1x\xbb"-/Table/54/1/"G-\xec\t\xad\x8fO\xed\xb4\xed:\xc42\xc4q\x0e"): with replicaID 3, applying Raft snapshot for range 4856 at index 494474 (encoded size=40469403, 606447 KV pairs, 33 log entries)
cockroach@104.196.153.89: I160727 15:52:04.241951 storage/replica_raftstorage.go:590  store=5:5 ([]=/mnt/data) range=1584 [/Table/51/1/4296226427003495721/"8931c524-d235-4865-93c6-c9ec27b78b3d"/1425533-/Table/51/1/4298426712627684273/"29ddce67-4ff7-41e8-b2d7-8e749d3d76da"/627218): with replicaID 23, applied Raft snapshot for range 1584 in 2.84783114s
cockroach@104.196.153.89: I160727 15:52:04.703370 storage/replica_raftstorage.go:590  store=5:5 ([]=/mnt/data) range=4019 [/Table/51/1/5349958056598016447/"c4bc6ab8-bc1f-433a-9c5a-0f76301bda5c"/433080-/Table/51/1/5352182114829582530/"5d03b71f-7582-432c-88a6-1c695a3f4fa4"/4857044): with replicaID 18, applied Raft snapshot for range 4019 in 3.25545259s
cockroach@104.196.153.89: I160727 15:52:38.501651 storage/replica_raftstorage.go:590  store=5:5 ([]=/mnt/data) range=3900 [/Table/51/1/6882515983394598571/"0419fe63-e906-4ed4-9651-0371c77b77a1"/55429-/Table/51/1/6884720455317757018/"15eecf25-c738-4df9-84ac-9425f09eea4f"/2795432): with replicaID 21, applied Raft snapshot for range 3900 in 37.031497676s
cockroach@104.196.153.89: I160727 15:52:39.818209 storage/replica_raftstorage.go:590  store=5:5 ([]=/mnt/data) range=4856 [/Table/54/1/"#\x82\xaa&=LD!\xab\xfdD?\x14\xc1x\xbb"-/Table/54/1/"G-\xec\t\xad\x8fO\xed\xb4\xed:\xc42\xc4q\x0e"): with replicaID 3, applied Raft snapshot for range 4856 in 38.105876663s
```

The combination of aggressive raft log truncation and concurrent handleRaftReady execution can amplify problems: a node that falls behind can lose its ability to catch up without a snapshot, and this may happen to multiple ranges at once (in fact this is likely). 

Lots of messages like this just before the server died:
```
W160727 02:10:26.593616 storage/replica.go:1682  failed to look up recipient replica 11 in range 3263: replica 11 not found in range 3263
W160727 02:10:26.593626 storage/replica.go:1682  failed to look up recipient replica 11 in range 3263: replica 11 not found in range 3263
W160727 02:10:26.593646 storage/replica.go:1682  failed to look up recipient replica 11 in range 3263: replica 11 not found in range 3263
W160727 02:10:26.593780 storage/replica.go:1682  failed to look up recipient replica 18 in range 3181: replica 18 not found in range 3181
W160727 02:10:26.593789 storage/replica.go:1682  failed to look up recipient replica 18 in range 3181: replica 18 not found in range 3181
W160727 02:10:26.593846 storage/replica.go:1682  failed to look up recipient replica 12 in range 3177: replica 12 not found in range 3177
W160727 02:10:26.593867 storage/replica.go:1682  failed to look up recipient replica 12 in range 3177: replica 12 not found in range 3177
W160727 02:10:26.593947 storage/replica.go:1682  failed to look up recipient replica 17 in range 2887: replica 17 not found in range 2887
W160727 02:10:26.594211 storage/replica.go:1682  failed to look up recipient replica 23 in range 1575: replica 23 not found in range 1575
W160727 02:10:26.594233 storage/replica.go:1682  failed to look up recipient replica 23 in range 1575: replica 23 not found in range 1575
```

This could be a sign of problems with the replica descriptor cache. If the message rate is too high, replica descriptors might not stay in the cache long enough for acknowledgements to be sent. (although this shouldn't matter for established ranges, only for new ones)

**Comment by petermattis** [comment] 2016-07-27 18:59
The aggressive raft log truncation is only done while all of the replicas current. If a replica falls behind, won't we allow the raft log to grow to be the range max-bytes?

**Comment by bdarnell** [comment] 2016-07-27 19:00
Yeah, it has to fall significantly behind in order for raft log truncation to be an issue.

**Comment by bdarnell** [comment] 2016-07-27 22:37
For the record, this doesn't appear to be a regression in this week's beta so it shouldn't block the release. My working theory is that this is a longstanding issue that has been exposed by the increasing replica count. 

If a replica is added to a range and becomes leader soon afterward, and another replica is lagging at this time, the lagging replica will get messages from a leader that it knows nothing about. In this case the only way the lagging node can reply is to use the From address of the incoming message (because it doesn't yet have a copy of the range descriptor that includes the new leader). The trouble is that by the time everything has gone through raft we've lost any connection to the incoming message that triggered the reply. 

We solved this by introducing the replica descriptor cache: we store the replica descriptor of *every* incoming message in an LRU cache so that hopefully be available when we send the reply. This worked so far but now the number of replicas (and the number of messages - coalescing heartbeats would make things better here) has increased to the point that a replica descriptor can be purged from the cache while it's still needed.

We could address this by increasing the cache size, or (following a TODO in the code) only caching those replica descriptors that are not present in the range descriptor. But the best solution is probably #7694, to move the replica descriptor cache into Replica itself (it's on Store for historical reasons). A tiny replica descriptor cache per replica would address the problem more precisely without any need to tune a shared cache. A single entry may be sufficient, since this only matters for messages sent by the leader.

**Comment by bdarnell** [comment] 2016-07-27 22:44
To be clear, there are two issues here. I think the replica descriptor cache is the root cause, but there's also the proximate issue that we don't have effective throttling of raft-generated snapshots.

**Comment by petermattis** [comment] 2016-07-28 00:28
@bdarnell Do you want someone to pick up #7694 while you investigate how to throttle raft-generated snapshots?

**Comment by bdarnell** [comment] 2016-07-28 03:13
Yeah, if we have someone free (I think everyone on core is occupied, but this should make a decent starter project if someone on another team wants to learn more about this area). I'll start writing up an RFC for streaming snapshots.

**Comment by cuongdo** [comment] 2016-07-28 16:59
Also getting OOMs on allocator tests.

**Comment by petermattis** [comment] 2016-07-28 21:23
Possibly/probably related: when using my `zerosum` stress tool which is taking a node down for between 15-45s and then reviving it, upon reviving I see a ton of these messages in the logs:

```
I160728 17:13:43.431648 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 29 in 339.26µs. encoded size=4917, 11 KV pairs, 19 log entries
I160728 17:13:43.461271 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 34 in 233.306µs. encoded size=7349, 14 KV pairs, 24 log entries
I160728 17:13:43.491636 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 41 in 259.037µs. encoded size=9917, 16 KV pairs, 31 log entries
I160728 17:13:43.521102 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 47 in 302.753µs. encoded size=12147, 18 KV pairs, 37 log entries
I160728 17:13:43.550346 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 53 in 301.084µs. encoded size=14375, 20 KV pairs, 43 log entries
I160728 17:13:43.594168 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 59 in 338.24µs. encoded size=16603, 22 KV pairs, 49 log entries
I160728 17:13:43.624808 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 65 in 363.163µs. encoded size=18834, 24 KV pairs, 55 log entries
I160728 17:13:43.651223 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 71 in 430.663µs. encoded size=21064, 26 KV pairs, 61 log entries
I160728 17:13:43.680386 storage/replica_raftstorage.go:467  generated snapshot for range 5 at index 77 in 408.382µs. encoded size=23294, 28 KV pairs, 67 log entries
...
```

During a 5s period we generated 128 snapshots for range 5. During that same time period on the flapping node I see:

```
I160728 17:13:47.634260 storage/replica_raftstorage.go:588  store=1:1 ([]=cockroach-data/1) range=5 [/Table/14-/Table/50): with replicaID 88, applying Raft snapshot for range 5 at index 549 (encoded size=15239, 184 KV pairs, 4 log entries)
I160728 17:13:47.636161 storage/replica_raftstorage.go:591  store=1:1 ([]=cockroach-data/1) range=5 [/Table/14-/Table/50): with replicaID 88, applied Raft snapshot for range 5 in 1.876566ms
I160728 17:13:48.153968 storage/replica_raftstorage.go:588  store=1:1 ([]=cockroach-data/1) range=5 [/Table/14-/Table/50): with replicaID 105, applying Raft snapshot for range 5 at index 653 (encoded size=17472, 218 KV pairs, 4 log entries)
I160728 17:13:48.156725 storage/replica_raftstorage.go:591  store=1:1 ([]=cockroach-data/1) range=5 [/Table/14-/Table/50): with replicaID 105, applied Raft snapshot for range 5 in 2.722618ms
```

So we generated 128 snapshots for range 5 but only applied them twice. In total, I count 482 snapshots generated but only 30 applied. After those 30, 9 were Raft snapshots and 21 were preemptive. That's a bit inefficient. Any ideas what is going on here? This is very easy to reproduce.

**Comment by petermattis** [comment] 2016-07-28 21:25
This looks like the culprit: after each snapshot generation I see the following in the log:

```
W160728 17:13:43.625365 storage/replica.go:337  range 5: outgoing raft transport stream to {1 1 0} closed by the remote: rpc error: code = 2 desc = replicaID cannot move backwards from 9 to 0
```

**Comment by petermattis** [comment] 2016-07-28 21:29
Along with the snapshot generation I can see a node looping trying to add and remove node ID 1 to the range. Node 1 is the flapper.

```
I160728 17:13:47.873338 storage/replica.go:1419  store=3:3 ([]=cockroach-data/2) range=5 [/Table/14-/
Table/50): proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:95} for range 5: [{NodeID:4 StoreID
:4 ReplicaID:4} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3}]
I160728 17:13:47.886738 storage/replica.go:1419  store=3:3 ([]=cockroach-data/2) range=5 [/Table/14-/
Table/50): proposing ADD_REPLICA {NodeID:1 StoreID:1 ReplicaID:96} for range 5: [{NodeID:4 StoreID:4
ReplicaID:4} {NodeID:3 StoreID:3 ReplicaID:2} {NodeID:2 StoreID:2 ReplicaID:3} {NodeID:1 StoreID:1 Re
plicaID:96}]
```

**Comment by petermattis** [comment] 2017-02-22 16:46
Closing as this is a very old OOM issue.

**Closed by petermattis** 2017-02-22 16:46 UTC
