### ISSUE TITLE
sql: show tables is expensive and can take very long on geo-distributed clusters

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#44510] opened 2020-01-29 22:07 UTC
**Describe the problem**

On a geo-distributed cluster, running show jobs can take very long depending on the distribution of the nodes, and where a lease is. 

It also appears that currently when we run show tables we only get 1 table descriptor at a time instead of batching them all together: 

`sending batch 1 Get` shows up ~220 times and each time this takes about 80ms to complete

In this particular case, the request was also coming from a DC that on the opposite end of the world, and the latency between nodes is ~170ms. 

**To Reproduce**

I've attempted to reproduce but wasn't able to get as drastic a result as the user. 

Set up geo-distributed roachprod cluster with nodes in US, EMEA, and Singapore
Set lease preference to Singapore
Created 200 empty tables
Run show tables.

I did notice an increase from ~1ms to over 150ms

**Expected behavior**
We should find a way to optimize show tables .

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 19.2.2

**Additional context**
What was the impact?

Was causing microservices to stall out or become very slow for the user.

**Comment by RoachietheSupportRoach** [comment] 2020-01-29 23:20
Zendesk ticket #[4559](https://cockroachdb.zendesk.com/agent/tickets/4559) has been linked to this issue.

**Comment by awoods187** [comment] 2020-03-25 14:39
@jordanlewis I think this needs triage

**Comment by jordanlewis** [comment] 2020-03-25 16:33
I can't reproduce the "many GET" issue. Maybe this is gone in 20.1? @roncrdb when you were trying this were you also seeing many GET commands?

**Comment by roncrdb** [comment] 2020-03-25 20:20
Hey @jordanlewis ,

I wasn't able to reproduce however @florence-crl  currently has a case where a geo-distributed cluster is taking 20+ seconds to return `SHOW DATABASES` not sure if this falls into the same issue as `SHOW TABLES` I did have them run a trace on it, and it has the same `batch 1 Get` show up ~63 times and you see the the the get is going to n11 and back to n16 each time. 

They are running version 19.2.3

They are also reporting that this slowness occurred after upgrading to 19.2.3 from 19.2.0.

**Comment by awoods187** [comment] 2021-09-20 12:34
I think this can be safely closed in favor of more specific future issues @jordanlewis

**Closed by awoods187** 2021-09-20 12:34 UTC
Labels: A-sql-execution, no-issue-activity
