### ISSUE TITLE
cli: workload verb should use .cockroach-certs similar to start and sql verbs

### ISSUE THREAD

**Issue by sheaffej** [cockroachdb/cockroach#49773] opened 2020-06-01 21:49 UTC
To make it easy to smoke test a newly configured secure cluster, it would be helpful if `cockroach workload` would default to using the cert path `.cockroach-certs` similar to how `cockroach start` and `cockroach sql` do.

Currently, the `workload` verb requires the sslXXX= parameters to be set in the URL string, which can get very long since it requires fully-qualified path names.
https://www.cockroachlabs.com/docs/v20.1/cockroach-workload.html#synopsis

If we set up the cluster certs so they are in `$HOME/.cockroach-certs` then the start and sql verbs do not need to supply the sslmode, sslrootcert, sslcert, and sslkey paths. And then quickly smoke testing the cluster would be:

```
cockroach workload init tpcc
cockroach workload run tpcc --duration=1h
```
Instead of:
```
cockroach workload init tpcc 'postgresql://root@j4-crl:26257?sslmode=verify-ca&sslrootcert=/Users/jsheaffer/.cockroach-certs/ca.crt&sslcert=/Users/jsheaffer/.cockroach-certs/client.root.crt&sslkey=/Users/jsheaffer/.cockroach-certs/client.root.key'

cockroach workload run tpcc --duration=1h 'postgresql://root@j4-crl:26257?sslmode=verify-ca&sslrootcert=/Users/jsheaffer/.cockroach-certs/ca.crt&sslcert=/Users/jsheaffer/.cockroach-certs/client.root.crt&sslkey=/Users/jsheaffer/.cockroach-certs/client.root.key'
```

**Comment by knz** [comment] 2020-06-02 12:41
duplicate of #29285

**Closed by knz** 2020-06-02 12:41 UTC
Labels: A-cli, C-enhancement
