### ISSUE TITLE
*: substantial qps dips when "gracefully" quitting a server

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#22573] opened 2018-02-11 05:35 UTC
Running the v1.1.5 release build locally with ycsb running against it, running `cockroach quit` on a node that the ycsb client is not connected to causes a substantial dip in QPS.

For example, this was from running `cockroach quit --insecure --port=26261` to quit the 5th node in a 5 node cluster (where three concurrent ycsb clients were hitting nodes 1, 2, and 3, respectively):

<img width="930" alt="screen shot 2018-02-11 at 12 00 08 am" src="https://user-images.githubusercontent.com/7085343/36070146-a7aed5fa-0ec2-11e8-8e1a-8b53586c4242.png">

The ycsb client's output was:
```
elapsed______ops/sec__reads/empty/errors___writes/errors____scans/errors
  3m53s        264.9         254 / 0 / 0          11 / 0           0 / 0
  3m54s         75.0          70 / 0 / 0           5 / 0           0 / 0
  3m55s         40.0          36 / 0 / 0           4 / 0           0 / 0
  3m56s          5.0           4 / 0 / 0           1 / 0           0 / 0
  3m57s          0.0           0 / 0 / 0           0 / 0           0 / 0
  3m58s          0.0           0 / 0 / 0           0 / 0           0 / 0
  3m59s          0.0           0 / 0 / 0           0 / 0           0 / 0
   4m0s          3.0           3 / 0 / 0           0 / 0           0 / 0
   4m1s        138.8         130 / 0 / 0           9 / 0           0 / 0
   4m2s        255.1         242 / 0 / 0          13 / 0           0 / 0
   4m3s        264.5         255 / 0 / 0           9 / 0           0 / 0
```

And then, after bumping the replication factor up to 5 (using `echo 'num_replicas: 5' | cockroach zone set .default --insecure -f -`) and killing nodes 4 and 5 in quick succession (`cockroach quit --insecure --port=26260` and `cockroach quit --insecure --port=26261`), it resulted in:

<img width="926" alt="screen shot 2018-02-11 at 12 08 37 am" src="https://user-images.githubusercontent.com/7085343/36070153-cd28acca-0ec2-11e8-8201-c894b51f8845.png">

And the ycsb client's output looked similarly bad:

```
elapsed______ops/sec__reads/empty/errors___writes/errors____scans/errors
 12m35s        270.6         254 / 0 / 0          16 / 0           0 / 0
 12m36s        263.4         255 / 0 / 0           9 / 0           0 / 0
 12m37s        186.4         178 / 0 / 0           8 / 0           0 / 0
 12m38s         85.9          78 / 0 / 0           8 / 1           0 / 0
 12m39s         14.0          13 / 0 / 0           1 / 0           0 / 0
 12m40s          0.0           0 / 0 / 0           0 / 0           0 / 0
 12m41s          0.0           0 / 0 / 0           0 / 0           0 / 0
 12m42s          4.0           3 / 0 / 0           1 / 0           0 / 0
 12m43s          0.0           0 / 0 / 0           0 / 0           0 / 0
 12m44s         14.0          13 / 0 / 0           1 / 0           0 / 0
 12m45s          0.0           0 / 0 / 0           0 / 0           0 / 0
 12m46s          0.0           0 / 0 / 0           0 / 0           0 / 0
 12m47s        114.0         106 / 0 / 0           8 / 0           0 / 0
 12m48s        260.9         243 / 0 / 0          18 / 0           0 / 0
 12m49s        252.0         230 / 0 / 0          22 / 0           0 / 0
```

My understanding of `cockroach quit` is that it's supposed to do a graceful shutdown, which is supposed to gracefully transfer all leases off the node that's being shut down before actually shutting the node down, in order to avoid any major disruptions in user traffic. The above disruptions are clearly too large to be the result of just lease transfers, so I suspect there's something wrong with the draining process. Potentially related to #22424.

**Comment by bdarnell** [comment] 2018-02-13 01:28
Please test with commits before and after #21682 was merged. I think that might help here. Before that change, a connection that was created immediately after a server restarted could be routed to the GRPC server instead of the pgwire server, where it would hang for a time before failing.

**Comment by a-robinson** [comment] 2018-02-13 01:34
To clarify, none of the above graphs / terminal outputs include what happens when the node comes back up. They show the behavior when you just kill a node and leave it/them down.

The restarting in these cases was relatively uneventful.

**Comment by bdarnell** [comment] 2018-02-13 01:36
Ah, ok. Not the same issue, then.

**Comment by nvanbenschoten** [comment] 2018-02-13 03:33
@asubiotto and I spent some time looking at this today. One thing that wasn't clear to us was how draining interacts with graceful Raft leadership transfers. As discussed above, we attempt to transfer away all leases before shutting down a server. Per the usual Replica state machine processing, this should trigger a call to `maybeTransferRaftLeadership` in `leasePostApply`. However, we don't make sure that the leadership transfer ever results in a Raft ready process loop by calling `enqueueRaftUpdateCheck`. In fact, we don't actually make any effort at all to wait for this Raft leadership transfer to succeed. Unless I'm missing something, this would mean that a graceful shutdown might still create upwards of 3 seconds of unavailability. Perhaps that is what we're seeing here.

**Comment by asubiotto** [comment] 2018-02-13 14:30
There definitely is a call to `maybeTransferRaftLeadership`. In the 0 QPS scenarios, this check https://github.com/cockroachdb/cockroach/blob/2f73ab2357925bd6d77dc5d5027e47db09cc07ec/pkg/storage/replica_proposal.go#L423
fails. The `Match` on the replica we transferred the lease to is less than `r.mu.lastIndex`. Therefore leadership is never transferred and we get zero qps until a new election is triggered. I verified that there are no drops in QPS if the leadership transfer succeeds. How should I go about fixing this scenario for draining?

**Comment by nvanbenschoten** [comment] 2018-02-13 14:43
One approach would be to force the call to `TransferLeader` regardless of the `Match` state during these lease transfers, since we know that the target replica was at least up-to-date when we [began transferring it the lease](https://github.com/cockroachdb/cockroach/blob/2f73ab2357925bd6d77dc5d5027e47db09cc07ec/pkg/storage/replicate_queue.go#L532).

We could also loosen this `pr.Match == r.mu.lastIndex` check, reducing it to require that the target replica is only "up-to-date enough", instead of fully caught up. It's a little crazy that we'll skip this call to `TransferLeader` whenever the target replica happens to be the second follower (n=3) to respond to a lease transfer request.

**Comment by asubiotto** [comment] 2018-02-13 15:37
It seems that the only call to `maybeTransferRaftLeadership` comes from `leasePostApply` and a helper function `RaftTransferLeader` for testing so it seems that we could follow your first approach without any negative side effects, since I don't think we ever transfer leases to behind replicas (including non-draining scenarios, is this correct?).

The second seems safer, but what exactly would an "up-to-date enough" check look like?

**Comment by nvanbenschoten** [comment] 2018-02-13 15:51
> It seems that the only call to maybeTransferRaftLeadership comes from leasePostApply and a helper function RaftTransferLeader for testing so it seems that we could follow your first approach without any negative side effects, since I don't think we ever transfer leases to behind replicas (including non-draining scenarios, is this correct?).

To start, why don't we verify that doing so would fix this issue.

> The second seems safer, but what exactly would an "up-to-date enough" check look like?

We would need to add some heuristic to determine whether the replica is up-to-date enough to allow a leadership transfer. This could be some combination of `pr.Match` being some threshold away from `r.mu.lastIndex` and `now() - lastUpdateTimes[follower]` being below some threshold.

**Comment by bdarnell** [comment] 2018-02-13 17:57
> The second seems safer, but what exactly would an "up-to-date enough" check look like?

A node must be up-to-date with (at least) all committed entries in order to win an election, and it probably must be completely up to date (with the outgoing leader's uncommitted entries). However, we could consider whether the node will be up to date after applying all in-flight MsgApps instead of its current state. This would mean checking `pr.Next - 1` instead of `pr.Match`, I think.

We could also consider changing this from "outgoing leader transfers leadership" to "incoming leaseholder campaigns" (the former was required when we were using CheckQuorum; now that we've switched to PreVote either would theoretically work). We'd need to test and make sure this is not more disruptive, but it wouldn't require any complications in draining.

**Comment by nvanbenschoten** [comment] 2018-02-13 18:24
> We could also consider changing this from "outgoing leader transfers leadership" to "incoming leaseholder campaigns"

This would avoid the race where a Replica calls `raftGroup.TransferLeader` but doesn't process its next Ready struct and send out the corresponding messages before it shuts down.

**Comment by asubiotto** [comment] 2018-02-15 15:43
Changing "outgoing leader transfers leadership" to "incoming leaseholder campaigns" ran into the problem that the transferee, being a follower, [forwards the `MsgTransferLeader` to the leader.](
https://github.com/cockroachdb/vendored/blob/45bbba4974dc2a816aeed44c95cc301d1b492a41/github.com/coreos/etcd/raft/raft.go#L1187) This makes the things worse, as the leader is more likely to have shut down.
@nvanbenschoten pointed out that [this test that transfers leadership to a slow node](https://github.com/coreos/etcd/blob/d54f281b26ecabdcfe2af0310f607d15f6c655d6/raft/raft_test.go#L3123) implies that we don't need to do our own checks for a `MsgTransferLeader`.
@bdarnell what do you think of simply removing the `pr.Match == lastIndex` check? This provides us with the benefit that this change can be cherrypicked into earlier version to improve our rolling upgrade story.

**Comment by bdarnell** [comment] 2018-02-15 15:46
Removing that check SGTM. It's redundant with checks that raft does internally, and raft does them better (instead of a one-time check, it records the desire to transfer and does so as soon as the target catches up)

**Comment by nvanbenschoten** [comment] 2018-02-15 18:14
> what do you think of simply removing the pr.Match == lastIndex check

Yeah, I agree with that approach as well. The only remaining question then is how long we want to wait for the Raft leadership to transfer before giving up. Should we just tie this to the draining context like we do for the draining lease transfer?

**Comment by asubiotto** [comment] 2018-02-15 18:24
@bdarnell suggested a 5s timeout. How do I check for a successful raft leadership transfer?

**Comment by nvanbenschoten** [comment] 2018-02-15 18:36
I think you would just want to wait until `repl.RaftStatus().SoftState.RaftState != raft.StateLeader`. I'm not sure what a good way to monitor this would be though.

**Comment by asubiotto** [comment] 2018-02-16 00:15
I was seeing zero QPS on startup of a node that had been down for a relatively long time and I'm not knowledgeable enough in this area to figure out exactly what's going on but since I only changed the check it seems that it introduced some instability in some other `leasePostApply` cases.
I made a more contained check: transfer leadership if the replica is draining. This seems to do the trick. I haven't been able to reproduce zero QPS when a node that isn't getting traffic goes down.
@a-robinson it would be great if you could try to reproduce your issue once #22767 is in.

**Comment by bdarnell** [comment] 2018-02-17 11:37
That `lastIndex` check was doing something useful when we're catching up on the raft log - it ensures that we only transfer leadership when applying the "current" lease instead of one in the past. So maybe what we need is to replace the log index check with one that verifies that the new lease is valid at the current time.

**Closed** 2018-03-02 16:31 UTC
Labels: bug
