### ISSUE TITLE
roachprod: pebble benchmark regression ~May 16th

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#104273] opened 2023-06-02 17:47 UTC
In cockroachdb/pebble#2578 we observed an unexpected increase in throughput in a write-heavy benchmark. After investigating further, we realized that the throughput increase was a result of decreased compaction performance, likely because of a change of the performance characteristics of the disk.

Note: These pebble nightly benchmarks are run through the `pebble/ycsb` roachtest.

Jira issue: CRDB-28441

**Comment by jbowens** [comment] 2023-06-02 17:50
This might be noticeable on the [kv0/enc=false/nodes=1/cpu=32
](https://roachperf.crdb.dev/?filter=&view=kv0%2Fenc%3Dfalse%2Fnodes%3D1%2Fcpu%3D32&tab=aws) roachperf graph as well:

<img width="825" alt="Screenshot 2023-06-02 at 1 49 18 PM" src="https://github.com/cockroachdb/cockroach/assets/867352/e314018e-2704-4448-bfed-7600d24bacdb">

**Comment by jbowens** [comment] 2023-06-05 20:03
On the storage-side, I think we should retry running ycsb/F using a Pebble binary built from an old SHA, once with a recent roachprod/roachtest and once with an old (eg, May 1st) roachprod/roachtest.

https://cockroachlabs.slack.com/archives/C023S0V4YEB/p1685740813124779?thread_ts=1685715794.392999&cid=C023S0V4YEB

**Comment by jbowens** [comment] 2023-06-21 16:19
The roachtest should produce artifacts that include files with names somethign like `ycsb_F.log`. The roachtest is a weird one in that it doesn't use the `cockroach` binary, but will use a pebble binary named by the `PEBBLE_BIN` env var I think.

**Comment by RaduBerinde** [comment] 2023-06-21 16:34
Hm, I ran it without a pebble binary.. I did find the workload log in the artifacts.

There are some `pebble/ycsb` tests which I think use that binary but those don't have an `F`. I don't see a `ycsv/F/values=1024` (the one in #2578) though. This is with a roachtest from May 1st.

```
radu (ce40ce73c96)+* ~/roach # roachtest list | ag ycsb
pebble/ycsb/A/race/duration=30 [storage]
pebble/ycsb/size=1024 [storage]
pebble/ycsb/size=1024/duration=10 [storage]
pebble/ycsb/size=64 [storage]
pebble/ycsb/size=64/duration=10 [storage]
splits/load/ycsb/a/nodes=4/obj=cpu [kv]
splits/load/ycsb/b/nodes=4/obj=cpu [kv]
splits/load/ycsb/d/nodes=4/obj=cpu [kv]
splits/load/ycsb/e/nodes=4/obj=cpu [kv]
ycsb/A/nodes=3 [test-eng]
ycsb/A/nodes=3/cpu=32 [test-eng]
ycsb/A/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
ycsb/B/nodes=3 [test-eng]
ycsb/B/nodes=3/cpu=32 [test-eng]
ycsb/B/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
ycsb/C/nodes=3 [test-eng]
ycsb/C/nodes=3/cpu=32 [test-eng]
ycsb/C/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
ycsb/D/nodes=3 [test-eng]
ycsb/D/nodes=3/cpu=32 [test-eng]
ycsb/D/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
ycsb/E/nodes=3 [test-eng]
ycsb/E/nodes=3/cpu=32 [test-eng]
ycsb/E/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
ycsb/F/nodes=3 [test-eng]
ycsb/F/nodes=3/cpu=32 [test-eng]
ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global [test-eng]
zfs/ycsb/A/nodes=3/cpu=32 [storage]
```

**Comment by RaduBerinde** [comment] 2023-06-22 00:41
So I ran the `ycsb/F` benchmarks in two configurations, three runs each. The ops/s numbers for all the runs are below.  It looks like an improvement on `ycsb/F/nodes=3` and a regression on `ycsb/F/nodes=3/cpu=32`

### both roachtest/roachprod and cockroach at ce40ce73c96 (May 1st)

ycsb/F/nodes=3:  7287.1  7136.7  7217.8
ycsb/F/nodes=3/cpu=32:  18606.3  19117.5  19079.0
artifacts/ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global:  18516.7  17509.9  18327.7

### cockroach still at ce40ce73c96 (May 1st); roachtest/roachprod at 795dd78a4c0 (Jun 17)

ycsb/F/nodes=3:  8253.2  8223.3  8226.0
ycsb/F/nodes=3/cpu=32:  17970.1  17676.9  17924.3
ycsb/F/nodes=3/cpu=32/mvcc-range-keys=global:  17634.0  18309.8  18446.3

**Comment by RaduBerinde** [comment] 2023-06-22 16:55
@jbowens I think the experiment above confirms that indeed there was a material difference in `roachtest`. Is there anything else we need to look at here or can we close?

**Comment by bananabrick** [comment] 2023-06-27 00:41
`pebble/ycsb`, runs all I think. I'm going to try running `pebble/ycsb` with `A-E` commented out using two different roachtest binaries.

**Comment by bananabrick** [comment] 2023-07-01 04:42
Posting some results for `pebble/ycsb/size=64/duration=10`, with every workload except `F` commented out in `pebble_ycsb.go` file in the Cockroach repo.

I'm using a Pebble commit from June 1: https://github.com/cockroachdb/pebble/commit/f98d3df2f00258c18b842f4610f39a0c6c967a8b. The pebble binary was built and set for the roachtest using `GOOS=linux GOARCH=amd64 go build ./cmd/pebble && export PEBBLE_BIN=<path to binary>`.

First, I checked out the following Cockroach commit: 1ee30a1fe7e56814a37c22457078c3a6bd0ede27 from April 29.

Then, I ran `dev build`, `dev build roachprod` and `dev build roachtest`. Then I ran `roachtest run pebble/ycsb/size=1024`.

After that I repeated the steps above for a Cockroach commit around June 29.

Here's the difference:

```
arjunnair@crlMBP-C02FR0UTMD6TMjA4 pebblelogs % benchstat old_perf new_perf
                 │   old_perf   │           new_perf            │
                 │   ops/sec    │   ops/sec     vs base         │
ycsb/F/values=64   151.6k ± 11%   145.6k ± 14%  ~ (p=1.000 n=6)

                 │   old_perf   │           new_perf            │
                 │     read     │     read      vs base         │
ycsb/F/values=64   1.051T ± 12%   1.027T ± 13%  ~ (p=0.790 n=6)

                 │   old_perf   │           new_perf            │
                 │    write     │    write      vs base         │
ycsb/F/values=64   1.221T ± 11%   1.191T ± 13%  ~ (p=1.000 n=6)

                 │  old_perf  │           new_perf            │
                 │   r-amp    │   r-amp     vs base           │
ycsb/F/values=64   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=6) ¹
¹ all samples are equal

                 │  old_perf  │             new_perf             │
                 │   w-amp    │   w-amp     vs base              │
ycsb/F/values=64   12.03 ± 1%   12.25 ± 0%  +1.83% (p=0.004 n=6)
```

I can't seem to get a statistically significant difference between either run. I ran this twice to make sure. Maybe I messed something up.

**Comment by bananabrick** [comment] 2023-07-01 19:04
Yea, aws has a massive difference. I ran the following command `./bin/roachtest run ^pebble/ycsb/size=64/duration=10$ --cloud aws --artifacts=pebble_logs/aws_oldd --parallelism 3 --cpu-quota=384`.

```
Benchmarkycsb/F/values=64 177135128  295224.8 ops/sec  151359577700 read  188394877457 write  0.00 r-amp  8.62 w-amp
```

```
Benchmarkycsb/F/values=64 401570651  669283.5 ops/sec  235324587820 read  321723454343 write  0.00 r-amp  6.47 w-amp
```

Closing this out.

**Closed by bananabrick** 2023-07-01 19:04 UTC
Labels: C-bug, T-storage, A-roachperf-investigation, T-testeng
