### ISSUE TITLE
DbVisualizer error when selecting a primary key.

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24647] opened 2018-04-10 21:17 UTC
In DbVisualizer, I tried to select a primary key. An error was present in dbvisualizer and in the logtostderr
`An error occurred while performing the operation:
ERROR: syntax error at or near "."
Detail: source SQL:
SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, ct.relname AS TABLE_NAME, a.attname AS COLUMN_NAME, (i.keys).n AS KEY_SEQ, ci.relname AS PK_NAME FROM pg_catalog.pg_class ct JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid) JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid) JOIN (SELECT i.indexrelid, i.indrelid, i.indisprimary, information_schema._pg_expandarray(i.indkey) AS keys FROM pg_catalog.pg_index i) i ON (a.attnum = (i.keys).x AND a.attrelid = i.indrelid) JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) WHERE true AND n.nspname = 'information_schema' AND ct.relname = 'columns' AND i.indisprimary ORDER BY table_name, pk_name, key_seq
^`

And in logtostderr
`I180410 21:15:27.942999 215 server/status/runtime.go:219  [n1] runtime stats: 160 MiB RSS, 161 goroutines, 121 MiB/25 MiB/163 MiB GO alloc/idle/total, 42 MiB/69 MiB CGO alloc/total, 53.91cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I180410 21:15:28.239753 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] [NoTxn pos:838] executing SendError: syntax error at or near "."
I180410 21:15:28.239804 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] execution error: syntax error at or near "."`

**Comment by jordanlewis** [comment] 2018-04-10 21:38
Duplicate of #16971

**Closed** 2018-04-11 14:37 UTC
Labels: pg-compat
