### ISSUE TITLE
storage: failure in TestClosedTimestampCanServeThroughoutLeaseTransfer in unrelated CI run

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#42367] opened 2019-11-11 14:28 UTC
Found in:

https://teamcity.cockroachdb.com/viewLog.html?buildId=1585662&buildTypeId=Cockroach_UnitTests

```
I191111 12:54:18.661179 581224 storage/replica_command.go:413  [n1,split,s1,r24/1:/{Table/28-Max}] initiating a split of this range at key /Table/53 [r25] (zone config)
I191111 12:54:19.157686 579021 gossip/gossip.go:1531  [n3] node has connected to cluster via gossip
I191111 12:54:19.158012 579021 storage/stores.go:259  [n3] wrote 2 node addresses to persistent storage
I191111 12:54:19.437611 581492 storage/replica_consistency.go:256  [n1,consistencyChecker,s1,r4/1:/System{/tsd-tse}] triggering stats recomputation to resolve delta of {ContainsEstimates:4068 LastUpdateNanos:1573476858204984753 IntentAge:0 GCBytesAge:0 LiveBytes:-98526 LiveCount:-1953 KeyBytes:-94521 KeyCount:-1953 ValBytes:-4005 ValCount:-1953 IntentBytes:0 IntentCount:0 SysBytes:0 SysCount:0}
I191111 12:54:19.751105 577903 util/stop/stopper.go:539  quiescing
I191111 12:54:19.751205 581654 util/stop/stopper.go:539  quiescing
I191111 12:54:19.751222 581588 util/stop/stopper.go:539  quiescing
I191111 12:54:19.751413 581653 util/stop/stopper.go:539  quiescing
W191111 12:54:19.751699 581334 storage/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.751832 581453 storage/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.752000 579199 storage/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 1: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.752084 579021 gossip/gossip.go:1517  [n3] no incoming or outgoing connections
W191111 12:54:19.752230 579198 storage/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 1: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.753311 579208 storage/raft_transport.go:637  [n1] while processing outgoing Raft queue to node 3: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.753754 579246 storage/raft_transport.go:637  [n1] while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.753755 579452 storage/raft_transport.go:637  [n1] while processing outgoing Raft queue to node 3: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.753856 579453 storage/raft_transport.go:637  [n1] while processing outgoing Raft queue to node 2: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.754010 581351 storage/raft_transport.go:637  [n2] while processing outgoing Raft queue to node 3: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.754112 581391 storage/raft_transport.go:637  [n2] while processing outgoing Raft queue to node 3: rpc error: code = Unavailable desc = transport is closing:
W191111 12:54:19.754193 578745 gossip/gossip.go:1517  [n2] no incoming or outgoing connections
W191111 12:54:19.754287 579305 storage/raft_transport.go:637  [n2] while processing outgoing Raft queue to node 1: rpc error: code = Canceled desc = grpc: the client connection is closing:
W191111 12:54:19.754476 579333 storage/raft_transport.go:637  [n2] while processing outgoing Raft queue to node 1: rpc error: code = Canceled desc = grpc: the client connection is closing:
    closed_timestamp_test.go:171: on [n2,s2,r25/3:/{Table/53-Max}]: [NotLeaseHolderError] r25: replica (n2,s2):3 not lease holder; current lease is repl=(n1,s1):1 seq=0 start=1573476859.291839802,0 epo=1 pro=1573476859.291845725,0
```

**Comment by ajwerner** [comment] 2019-11-11 15:55
Duplicate of #37468.

**Closed by ajwerner** 2019-11-11 15:55 UTC
Labels: A-storage
