### ISSUE TITLE
roachperf displaying erratic tpc-c data

### ISSUE THREAD

**Issue by johnrk** [cockroachdb/cockroach#39634] opened 2019-08-13 18:55 UTC
**The Problem**
Erratic data shown for tpc-c performance data in May and July-August.

**To Reproduce**
go to this graph: https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16&tab=gce

**Expected behavior**
Less erratic data in the number of warehouses measured. For example, we shouldn't have the dips in number of warehouses around July 21-28 and August 4th.

**Screenshot:**
![image](https://user-images.githubusercontent.com/1663752/62968987-40d91700-bdda-11e9-9bab-dbdfe5070b40.png)

**Environment:**
 - Client app: Chrome

**Additional context**
I'm pulling this data for the Core product council.

**Comment by johnrk** [comment] 2019-08-13 18:55
Hey @ajwerner , could you also take a look at this?

**Comment by ajwerner** [comment] 2019-08-13 19:01
I think there's two issues here. It seems like for this one, for whatever reason, we just have a single run from this instance of tpccbench. I'll look into that.

There are some other instances of erratic perf data caused by failed tests. We generally need a better mechanism to audit and remove this old data. It's possible today but it's painful. This is tracked by https://github.com/cockroachdb/roachperf/issues/36

We need to decide whether it makes sense to track these issues in this repo or in the [roachperf](https://github.com/cockroachdb/roachperf/issues repo). I don't care but I'd strongly prefer that we pick one.

**Comment by ajwerner** [comment] 2019-08-14 20:02
I cleaned some of the data up and removed the cache. It should look somewhat better soon.

**Comment by ajwerner** [comment] 2019-08-20 23:29
I removed some of the detritus. I'm going to close this.

**Closed by ajwerner** 2019-08-20 23:29 UTC
Labels: A-core, C-bug
