### ISSUE TITLE
sql: table with foreign key appears to be invisible within transaction it's created in

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#17949] opened 2017-08-28 13:03 UTC
When we try to insert into `b`, below, the table can't be found if it has a foreign key constraint, but works fine if there is no constraint.
```
root@:26257/d> CREATE TABLE a (x INT PRIMARY KEY);
CREATE TABLE

root@:26257/d> INSERT INTO a VALUES (1);
INSERT 1

root@:26257/d> BEGIN;
            -> CREATE TABLE b (y INT REFERENCES a(x));
            -> INSERT INTO b VALUES (1);
            ->
pq: relation "b" does not exist
root@:26257 ERROR> rollback;
ROLLBACK

root@:26257/d> BEGIN;
            -> CREATE TABLE b (y INT);
            -> INSERT INTO b VALUES (1);
            ->
INSERT 1

root@:26257/d  OPEN> COMMIT;
COMMIT
```

Jira issue: CRDB-6022

**Comment by dt** [comment] 2017-08-28 15:27
Tables with references to other tables cannot become public (usable) until all nodes have updated their cached versions of all referenced tables --typically about 2s after the transaction creating the new table and adding those references commits. We used to disallow any statements in a txn following a DDL because of this theoretical limitation, but IIRC we changed this at some point, so I'm no longer clear on what the expected semantics are... @vivekmenezes or @jordanlewis are now the experts on the expected behavior here.

**Comment by jordanlewis** [comment] 2023-01-04 15:30
This now has a nicer error message and will get fixed later with the new schema changer, so closing.

**Closed by jordanlewis** 2023-01-04 15:30 UTC
Labels: C-bug, S-3-ux-surprise, A-schema-changes, A-schema-transactional, T-sql-schema
