### ISSUE TITLE
DB Console shows Full Scan? No for statement plan with FULL SCAN

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#105449] opened 2023-06-23 18:09 UTC
**Describe the problem**
DB Console shows Full Scan? No on Statement Fingerprint details page for statement plan with FULL SCAN.

I was not able to reproduce this from a clean cluster. This issue can be seen in the attached zipped cluster.

**To Reproduce**

Download https://binaries.cockroachdb.com/cockroach-v23.1.4.darwin-11.0-arm64.tgz and unzip in a test directory
Download cockroach-data.zip from [internal slack thread](https://cockroachlabs.slack.com/archives/G01Q9D01NTU/p1687543915877939?thread_ts=1687533892.752839&cid=G01Q9D01NTU) into the test directory
Run: `./cockroach start-single-node --insecure --listen-addr=localhost:36257 --sql-addr=localhost:26257 --http-addr=localhost:8080 --background`

In DB Console (http://localhost:8080/#/overview/list)
1. Navigate to Insights page > Schema Insights tab
2. In the row with the Create Index insight, click on the Statement link to open the Statement Fingerprints details page (adjust time interval to include `Jun 23, 2023 at 14:53 UTC`)
3. On the Overview tab, notice the properties:
`Full Scan? No`
`Fingerprint ID 97ffc170783445fd`
`Last execution time Jun 23, 2023 at 14:53 UTC`
4. Go to the Explain Plans tab
5. In the Plans table, notice there are 2 rows. Scroll to the right of the Plans table and notice that for both rows the Full Scan column has the value No.
6. Click on the Plan Gist link for either row, notice in the plan has `spans: FULL SCAN`

In SQL CLI
- Run the query:
`select * from crdb_internal.statement_statistics where fingerprint_id='\x97ffc170783445fd'`
- Returns 3 rows all with `"fullScan": true`

**Expected behavior**
In the DB Console, `Full Scan? Yes`

**Additional data / screenshots**
<img width="1042" alt="Screenshot 2023-06-23 at 11 17 46 AM" src="https://github.com/cockroachdb/cockroach/assets/58752716/43ee2b5d-b2df-459d-b58f-aab1609fd15d">

**Environment:**
 - CockroachDB version [e.g. 23.1.4]
 - Server OS: Mac ARM
 - Client app DB console

Jira issue: CRDB-29052

**Comment by koorosh** [comment] 2023-07-16 20:42
This issue was already fixed by following PR https://github.com/cockroachdb/cockroach/pull/106434
It can be reproduced if select short period of time - then `full scan` shows incorrect value. 
Otherwise if selected period ie for 2 month then it shows correct result because it queries data from 
persisted table instead of `crdb_internal.statement_activity` view.

**Closed** 2023-07-25 19:04 UTC
Labels: C-bug, T-cluster-observability, A-cluster-observability
