### ISSUE TITLE
storage: zone configs lack expressivity

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19985] opened 2017-11-10 23:39 UTC
The zone configuration format makes certain configurations difficult and/or brittle. This is an umbrella issue to collect them.

1. two datacenters A and B, want two replicas in A and a third in B. I think this can be achieved by giving the nodes in A `--locality dc=a,hash=<random thing>` and the nodes in `B` `--locality=b`. It also seems that it would break if `B` got anything added to their locality.
2. 4 datacenters A B C D, want exactly one replica in A B C, none in D. This could use a negative constraint on `D`. Again this seems brittle since adding a new DC would wipe things out. Or similarly to the previous example, can give A-C longer distinct locality prefixes and trust that D's doesn't ever grow to the same length.

**Comment by tschottdorf** [comment] 2017-11-10 23:39
This is in stark contrast to the earlier zone config system we had in place, which would let you specify

```
replicas:
  - dc1
  - dc1
  - dc2
```

**Comment by tschottdorf** [comment] 2017-11-10 23:43
@danhhz assigning you to add anything else you can think of.

See also https://forum.cockroachlabs.com/t/specifying-number-of-replicas-per-data-center/1080/5.

**Comment by a-robinson** [comment] 2017-11-11 02:12
Related:
storage: rebalancing - updates to positive constraints https://github.com/cockroachdb/cockroach/issues/14163
storage: Diversity scores not working as intended in allocator https://github.com/cockroachdb/cockroach/issues/17479

**Comment by tschottdorf** [comment] 2017-11-11 04:20
Thanks @a-robinson, should've known there's already something on this. I'll leave this open because well, I did search for the other issues and managed to miss them, and this way the chance of finding one of them in the future is higher.

**Comment by danhhz** [comment] 2017-12-18 20:38
I don't have anything to add at the moment, but we'll add info here as our partitioning test partners actually try it out

**Comment by petermattis** [comment] 2018-01-05 02:59
My thinking from an offline chat with Alex today: we should extend the constraint language with conjunctions and disjunctions. Specifically, we could add `Constraint.{AND,OR}` and `Constraint.children`, the latter would only be present for `{AND,OR}` constraints. This addresses @tschottdorf's second example: `required:(A OR B OR C)`. Extending `constraintCheck` to process conjunctions and disjunctions of constraints appears to be relatively straightforward.

To address the second example, we need to add constraint logic that applies to the set of replicas in a range. I propose we add a `Constraint.num_replicas` field that is only allowed for top-level `REQUIRED` constraints. `constraintCheck` would be modified so that such a `REQUIRED` constraint would be interpreted as a `POSITIVE` constraint. A new `rangeConstraintCheck` function would take all of the replicas for a range (including the proposed addition) and verify "range-level" constraints. This function would loop over the top-level constraints and for each `REQUIRED` constraint with a non-zero `num_replicas`, it would verify that number of replicas match the constrain. If the range contains less than the desired number of replicas, we would assume the missing replicas will match the constraint. This would address @tschottdorf's first example: `required:A,num_replicas=2 required:B,num_replicas=1`.

I would appreciate the above being torn apart. Implementation-wise, this seems feasible. It would allow expressing constraints with no solution, but you can already do that with the existing constraints.

**Comment by petermattis** [comment] 2018-01-09 13:38
@a-robinson Any additional thoughts about this?

@bdarnell PTAL at the proposal above.

**Comment by bdarnell** [comment] 2018-01-09 15:31
The proposal SGTM

**Comment by a-robinson** [comment] 2018-01-09 19:51
**Backwards compatibility**

The proposed solution breaks backwards compatibility with existing configs, because we can’t switch from a list of strings to a list of protos. We can write a migration to move from the old format to the new, but we’ll also cause pain for existing users.

**User Experience**

Currently we recommend people use YAML files for their zone configs:
```yaml
range_min_bytes: <size-in-bytes>
range_max_bytes: <size-in-bytes>
gc:
  ttlseconds: <time-in-seconds>
num_replicas: <number-of-replicas>
constraints: [comma-separated constraint list]
```

The kind of nesting being proposed gets a little unwieldy in YAML.
Depending on the proto definition we use, it could look like this, for example:

```yaml
range_min_bytes: 1048576
range_max_bytes: 67108864
gc:
  ttlseconds: 90000
num_replicas: 3
constraints:
  - condition: AND
    numReplicas: 2
    children:
      requirements: [“a”]
    children:
      Requirements: [“b”]
  - condition: AND
    numReplicas: 1
    children:
      requirements: [“c”]
```

And in writing that out, a number of questions around the structure of the protocol buffer jump out:
* Are multiple levels of nesting allowed? E.g. `(A AND (B OR C))`
* Can you omit the `children` and `condition fields` and just specify `requirements` directly in the top-level `constraints` object?
* Do you use separate protos for the top-level constraints object and the children? If not, we’ll have to do a bunch of input validation.

**Scope creep**

OR conditions are solving a different problem than what we’ve been concerned about for 2.0. There may be situations where they’re useful, but none of the cases I remember discussing would have benefited from them. They’re simple enough to implement, but do add extra complexity to the text format.

> This addresses @tschottdorf's second example: required:(A OR B OR C). Extending constraintCheck to process conjunctions and disjunctions of constraints appears to be relatively straightforward.

I think you misread his situation. It looks to me like he’s saying he wants 1 replica in A, 1 replica in B, and 1 replica in C. Not 1 replica in `(A OR B OR C)`, or even 3 replicas in `(A OR B OR C)`. Although that latter interpretation is an interesting question -- which one should users prefer? If an entire datacenter goes down, the latter will mean a ton of rebalancing work that might fill up the disks in your other datacenters, but it would give you a 50% chance of surviving a second datacenter failure.

**Deciding when to rebalance**

Having separate sets of constraints for each replica (1 replica in A, 1 in B, etc.) will make deciding when to rebalance a little trickier. We’ll have to consider a possible rebalance candidate valid even if we already have the correct number of replicas in its locality (because if we didn’t we fundamentally wouldn’t be able to rebalance within a locality). I think this’ll force our hand into implementing https://github.com/cockroachdb/cockroach/issues/20751 to avoid making bad comparisons across localities if some localities have more data in them than others (since otherwise we’ll almost never rebalance between nodes within those localities). I think that’s true no matter what solution we go with, though. I mainly include this point to indicate that the work may be a little more than expected.

-------------------

I think my main concern here is around the complexity. I do think this is workable, but we went from a proposal that was backwards compatible (with no migrations needed), that didn’t add any nesting to the yaml configurations, and for which it’s easier to understand the scope of possible configurations to something much broader. Perhaps that’s a good thing, but I’d have an easier time convincing myself of that if we had some realistic situations that it solved that the simpler version didn’t solve (or that it solved better than the simpler version).

**Comment by a-robinson** [comment] 2018-01-09 19:57
Notes from a meeting about this last week, for context:

* Current Proposal:
    * Add back something like the old `replicas` repeated field
    * Can specify between 0 and `numReplicas` different sets of attributes - any additional replicas that aren't specified can be placed anywhere in the cluster
    * For now, don't allow it to be specified if positive/negative constraints are also specified (drastically simplifies implementation and testing)
    * Coding of the above scope should only take a day or two - as long as testing doesn't go horribly wrong, it should take less than a week of work altogether. Most of the work would be around making sure it plays nicely with diversity scoring and rebalancing.
    * How does this apply when thinking about zone configs and tables?
        * When used during rebalancing, we don’t consider hierarchy
        * We would have to change current structure for support
    * This creates two separate constraints systems and in the short term, the user can only use one or the other for any given zone
        * In the long term we will need to merge these two solutions together and that seems possible
        * A lot of potential gotchas from merging together, so there is also a risk that they cannot be merged together and will always be incompatible
    * What happens with required constraint? For example, all data is in the EU and one replica is configured for the US?
        * This could be a problem today under the current code
        * We likely need for something in the Admin UI to warn users
    * Can you specify the same constraints twice? Having a list would match each to a replica
        * Maybe, but that could be ambiguous
    * It may be worth spending some time in the allocator code to evaluate other options
        * For example, it is hard to deal with different interleaving of requirements from user under the current proposed solution
    * We require all of the constraints on a replica to match
    * Do we have the knowledge for where other replicas are located?
        * Yes, we have this knowledge from diversity
    * How do we integrate constraint part (which is independent) and the full range information?
* What is the customer demand for this in 2.0?
    * We have anecdotal feedback that its very hard to use current zone configs
    * We have heard the desire for replica level control from partitioning configs, but probably need to dig into the specifics
* What is the other future work needed for zone configs?
    * Need SQL interface
    * Decide if TTLs make sense to be implemented via zone configs
    * The above discussion on replica-level constraints

**Comment by danhhz** [comment] 2018-01-09 20:21
I also can't think of any current use cases where we'd need the OR (and agree with @a-robinson's reading of @tschottdorf's case (1)). If that's true, is implementing only the "Constraint.num_replicas field that is only allowed for top-level REQUIRED constraints" part of @petermattis's proposal sufficient?

**Comment by a-robinson** [comment] 2018-01-09 20:48
It'd either break backwards compatibility or make for a weird text format, but I do think it'd be sufficient for the situations we've considered.

A related question that's on been my mind today is how prohibited constraints play into this. It doesn't seem like you'd ever want a negative constraint to apply to just a single replica, only to the entire range.

**Comment by a-robinson** [comment] 2018-01-09 21:09
Also cc @BramGruneir, since he's done a lot of thought about this in the past.

**Comment by petermattis** [comment] 2018-01-09 21:20
> The proposed solution breaks backwards compatibility with existing configs, because we can’t switch from a list of strings to a list of protos.

I'm not seeing where the backward compatibility breakage is coming from. Can you elaborate? Do you have a branch with code you're experimenting with?

> Are multiple levels of nesting allowed? E.g. (A AND (B OR C))

I don't see why we would prohibit it.

> Can you omit the children and condition fields and just specify requirements directly in the top-level constraints object?

Yes. We'd want that for backward compatibility.

> Do you use separate protos for the top-level constraints object and the children? If not, we’ll have to do a bunch of input validation.

I was thinking we'd use the same proto and do validation.

**Comment by petermattis** [comment] 2018-01-09 21:21
> A related question that's on been my mind today is how prohibited constraints play into this. It doesn't seem like you'd ever want a negative constraint to apply to just a single replica, only to the entire range.

I was imagining that `Constraint.num_replicas` can only be non-zero for required constraints.

**Comment by a-robinson** [comment] 2018-01-10 15:11
> I'm not seeing where the backward compatibility breakage is coming from. Can you elaborate? Do you have a branch with code you're experimenting with?

No branch I'm working from. I think I was wrong about the text format not being backwards compatible -- we can customize the yaml parser to convert a string array into a more structured proto. It still doesn't feel very idiomatic to encode so much inside the strings - we have to include positive constraints, negative contraints, and the optional number of replicas. And that's assuming we aren't supporting both AND and OR -- more parsing will be needed if we want to.

So I guess we'd structure it as something like `["+constraint1,+constraint2,+constraint3;numReplicas=2", "+constraint4,+constraint5;numReplicas=1,"-constraint6"`, with the last entry omitting a number of replicas in order to apply to the whole range. We'll have to pick out some sort of separator character (the `;` in this example) that isn't allowed in node attributes or locality key-value pairs and start enforcing that it isn't allowed in them.



> I was imagining that `Constraint.num_replicas` can only be non-zero for required constraints.

That's been my thought as well.

**Comment by awoods187** [comment] 2018-01-25 14:12
Adding in notes from last meeting:

- Does the new solution support backward compatibility?
Yes, although it will add complexity because of marshaling 
- ACIDLIB (Andy K’s project) uses AND/OR and has thought through similar syntax
We will add this info to the tracking issue  
- Is OR necessary?
It does not add implementation complexity. It gives users more way to go wrong. 
OR creates the need for nesting 
Everything is AND implicitly 
Lowers the scope of the change to keep it as AND only 
We can likely solve current use cases without using OR 
- CRDB will need changes to rebalancing to make sure it still works--regardless of which format we choose. It is unclear how difficult or complex this will be
- What happens in the event a replica is missing? Not just up replication but node failure?
We should respect customer setup (but educate them on best practices via docs)
We may need a solution that identifies problems and notifies the user via the Admin UI
- We need a prototype to evaluate the proposed solution 
This can help determine the need for OR as well as the complexity involved in rebalancing 
We need to evaluate external syntax 
Alex will prototype this solution and will post to the issue with an update  
- We will track this in the CORE meeting moving forward

**Comment by awoods187** [comment] 2018-01-25 18:35
dropping in here for discussion later: how would we track feature usage of And/Or?

**Comment by a-robinson** [comment] 2018-02-20 21:08
Just a quick update on the current state of this as of #22819 so people can more easily chime in:

The old format will continue to be supported as is: `[+a=1, +b=2, +c=3, +ssd]`. All such constraints apply to all replicas in the range. In the example above, all replicas will need to be in a locality with `a=1`, `b=2`, `c=3`, and with a node or store attribute of `ssd`.

A new per-replica, or "expressive", format allows you to assign numbers of replicas to specific sets of constraints: ["(+a=1,+b=2):2", "(+a=1,+b=2):2", "(+a=2,+ssd):1"]`. Sets of constraints that apply to the same replica(s) are grouped in parentheses and suffixed with a colon and the number of replicas they apply to.

What do people think about the new format? Would something else be clearer? We should perhaps use something other than a `:` to separate the constraints from the number of replicas, because it's a special character in YAML that necessitates putting quotes around everything.

**Comment by benesch** [comment] 2018-02-20 21:18
Why not take more advantage of YAML?

```yml
- +a=1,+b=2: 2
- +a=2,+b=3: 2
- +a=2,+ssd: 1
```

Or, more compactly:

```
{"+a=1,+b=2": 2, "+a=2,+b=3": 2, "+a=2,+ssd": 1}
```

Re your original proposal: In the compact syntax the commas will require quoting no matter what, so probably not worth trying to find a separator besides `:`.

**Comment by a-robinson** [comment] 2018-02-21 15:39
Thanks, @benesch. That's a very interesting idea. I stuck with lists because that made on-disk compatibility easiest, but we could certainly use a map on the front-end for converting to/from yaml.

That looks pretty appealing to me, and it should be easily doable with a little reworking of #22819. It also gets rid of the issue with v1.1 clients silently doing the wrong thing being discussed in https://github.com/cockroachdb/cockroach/pull/22819#issuecomment-367193332. Any other final thoughts, @BramGruneir / @petermattis / @bdarnell?

**Comment by petermattis** [comment] 2018-02-21 15:58
I have no objections to @benesch's proposal.

**Closed** 2018-02-21 22:31 UTC
Labels: partitioning
