### ISSUE TITLE
sql: COUNT(*) returns incorrect count when subquery contains DISTINCT

### ISSUE THREAD

**Issue by eldos-dl** [cockroachdb/cockroach#16304] opened 2017-06-03 12:50 UTC
**BUG REPORT**
```
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release
```
Code:
```
CREATE TABLE A (            
    id INT NOT NULL DEFAULT unique_rowid(),  
    name STRING(100) NOT NULL,               
    age INT NOT NULL,         
    CONSTRAINT "primary" PRIMARY KEY (id)
);
INSERT INTO A (name, age) VALUES ('A', 22);
INSERT INTO A (name, age) VALUES ('B', 23);

SELECT * FROM (SELECT name, age FROM a);
-- Returns the table as expected.
-- +------+-----+
-- | name | age |
-- +------+-----+
-- | A    |  22 |
-- | B    |  23 |
-- +------+-----+
SELECT COUNT(*) FROM (SELECT name, age FROM a); -- Returns 2 as expected.
SELECT * FROM (SELECT DISTINCT name, age FROM A);
-- Returns the table as expected.
-- +------+-----+
-- | name | age |
-- +------+-----+
-- | A    |  22 |
-- | B    |  23 |
-- +------+-----+

SELECT COUNT(*) FROM (SELECT DISTINCT name, age FROM A); -- Returns 1 (incorrect)
```
`COUNT(*)` is returning one even though there are two rows.

**Comment by jordanlewis** [comment] 2017-06-03 14:51
Thanks for the bug report!

As a workaround until we fix this issue, you could use `SELECT COUNT(name) FROM...` assuming `name` is not null.

The issue is caused by a bug in `DISTINCT`. Since no columns from the inner query are directly used in the outer query, we assume that it's not necessary to demarshal them from the actual row value. That's an incorrect assumption, since `DISTINCT` always needs to see the actual column value to do its work properly.

I think can be fixed by adding an extra check to `setNeededColumns`.

**Comment by knz** [comment] 2017-06-03 16:15
The root ause issue is caused by a bug in Radu's recent improvement to aggregation. The problem is that groupNode now introduces an intermediate renderNode before distinctNode, and mistakenly has this renderNode render StarDatumInstance for `count(*)` instead of the columns of the source. This *in turns* (correctly) causes the columns from the original source to become omitted (since they are not used any more)

**Comment by knz** [comment] 2017-06-03 16:15
cc @RaduBerinde

**Comment by RaduBerinde** [comment] 2017-06-03 17:54
I would say that the renderNode correctly renders StarDatumInstance, and what's incorrect is that distinctNode causes the original columns to become omitted. The distinct node itself needs all the columns to figure out which rows to eliminate, so the fact that the values aren't necessary after the distinctNode shouldn't mean that they are not necessary before it.

This problem is not particularly tied to aggregation or `COUNT(*)`. For example:
```sql
root@:26257/test> SELECT DISTINCT "name", age FROM a;
+------+-----+
| name | age |
+------+-----+
| A    |  22 |
| B    |  23 |
| A    |  30 |
+------+-----+
(3 rows)
root@:26257/test> SELECT name FROM (SELECT DISTINCT "name", age FROM a);
+------+
| name |
+------+
| A    |       <----------- This should be identical to the column above
| B    |
+------+
(2 rows)
root@:26257/test> EXPLAIN (VERBOSE) SELECT name FROM (SELECT DISTINCT "name", age FROM a);
+-------+----------+----------+-------------+-------------------------------------+----------+
| Level |   Type   |  Field   | Description |               Columns               | Ordering |
+-------+----------+----------+-------------+-------------------------------------+----------+
|     0 | render   |          |             | ("name")                            |          |
|     0 |          | render 0 | name        |                                     |          |
|     1 | distinct |          |             | ("name", age)                       | =age     |
|     1 |          | key      | age         |                                     |          |
|     2 | render   |          |             | ("name", age)                       | =age     |
|     2 |          | render 0 | test.a.name |                                     |          |
|     2 |          | render 1 | NULL        |                                     |          |
|     3 | scan     |          |             | (id[omitted], "name", age[omitted]) |          |
|     3 |          | table    | a@primary   |                                     |          |
|     3 |          | spans    | ALL         |                                     |          |
+-------+----------+----------+-------------+-------------------------------------+----------+
(10 rows)
```


I also noticed an unrelated issue:
```
root@:26257/test> EXPLAIN (VERBOSE) SELECT count(*) FROM (SELECT DISTINCT "name", age FROM a);
+-------+----------+-------------+-------------+----------------------------------------------+--------------+
| Level |   Type   |    Field    | Description |                   Columns                    |   Ordering   |
+-------+----------+-------------+-------------+----------------------------------------------+--------------+
|     0 | group    |             |             | ("count(*)")                                 |              |
|     0 |          | aggregate 0 | count(*)    |                                              |              |
|     1 | render   |             |             | ("*")                                        | ="*"         |
|     1 |          | render 0    | *           |                                              |              |
|     2 | distinct |             |             | ("name", age)                                | ="name",=age |
|     2 |          | key         | name, age   |                                              |              |
|     3 | render   |             |             | ("name", age)                                | ="name",=age |
|     3 |          | render 0    | NULL        |                                              |              |
|     3 |          | render 1    | NULL        |                                              |              |
|     4 | scan     |             |             | (id[omitted], "name"[omitted], age[omitted]) |              |
|     4 |          | table       | a@primary   |                                              |              |
|     4 |          | spans       | ALL         |                                              |              |
+-------+----------+-------------+-------------+----------------------------------------------+--------------+
```
The "="name",=age " is incorrect. It's probably coming from the renderNode constant detection. I think we want to exclude omitted columns from that detection. I don't know if this problem can actually cause any issues in practice (if an ordering is required on a column, it won't be omitted).

**Closed** 2017-06-05 14:03 UTC
Labels: 1.0.2, bug, high priority
