### ISSUE TITLE
sql: investigate the output of Hibernates' org.hibernate.test.batch.BatchTest 

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26812] opened 2018-06-18 21:20 UTC
There is a default jdbcBatchSize that seems to be set for Postgres but not for cockroach.  More investigation is needed.

See the tests:
- org.hibernate.test.batch.BatchTest
  - testBatchInsertUpdate
  - testBatchInsertUpdateSizeEqJdbcBatchSize 	

By defaulting to 0, there just might be a missing setting or something simple.  Seems like this isn't supplied by postgres directly.

**Comment by knz** [comment] 2018-06-30 01:58
@BramGruneir This issue is improperly qualified. It does neither state what is the deviation (difference between expected behavior and actual behavior) nor what action items should be carried out.

Unless you provide either (preferably both), we can't do anything with this.

**Comment by BramGruneir** [comment] 2018-07-02 14:22
I disagree.  This is labeled as investigation.  An investigation is actionable.  

In this case, as specified, the default seems to be set to 0

My guess is that this is an issue with hibernate and not cockroach. But a more thorough investigation is required.

**Comment by knz** [comment] 2018-07-02 15:57
Define:

- What is a "batch" in JDBC/Hibernate. How does it correspond to SQL.
- How is the batch size determined. How this determination is made in SQL or in the wire protocol.

**Comment by knz** [comment] 2018-07-02 16:00
The issue title was wrong. 

We do not really know what the issue is so the title must reflect the investigation not the working theory as to the source of the problem.

**Comment by jordanlewis** [comment] 2019-05-15 21:00
Fixed as of 2.1 🎉

**Closed by jordanlewis** 2019-05-15 21:00 UTC
Labels: A-sql-hibernate, C-investigation
