### ISSUE TITLE
build: Reconsider go version restrictions

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#17973] opened 2017-08-28 20:06 UTC
CockroachDB 1.0's Makefile only allows it to be built with Go 1.8, even though Go 1.9 has been released and CockroachDB 1.1 is not yet available (and assuming both projects stick to their respective release schedules, a similar situation will play out for each CockroachDB release). This is inconvenient for users who may have to downgrade their version of Go to build CockroachDB from source (or make a parallel installation, or use a builder image, etc). 

It makes sense for the Makefile to enforce a minimum Go version; I'm not sure if it makes sense to enforce a maximum. We often have linter failures when upgrading Go versions, and sometimes we have other test failures, but I don't think we've had much trouble with the main binary breaking when a new version of Go is used (have I forgotten anything?). Given this, we may want to change our version enforcement to specify a minimum instead of a range.

**Comment by benesch** [comment] 2018-02-07 19:27
Duplicate of #19431, so also fixed by #21426.

**Closed by benesch** 2018-02-07 19:27 UTC
