### ISSUE TITLE
circleci: failed tests (14717): TestLogic 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5344] opened 2016-03-17 15:20 UTC
The following test appears to have failed:

[#14717](https://circleci.com/gh/cockroachdb/cockroach/14717):

```
testdata/poison_after_push: 6
testdata/poison_after_push:28 testuser: SELECT * FROM t
testdata/poison_after_push:33 testuser: COMMIT
testdata/poison_after_push:40 testuser: SELECT * FROM t
I160317 15:18:58.843231 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestLogic (27.79s)
	logic_test.go:531: testdata/poison_after_push:40: expected retry txn, but found <nil>
=== RUN   TestQueryCounts
W160317 15:18:58.865571 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
I160317 15:18:58.865636 rpc/clock_offset.go:162  monitoring cluster offset every 30s
W160317 15:18:58.873867 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
I160317 15:18:58.874589 server/node.go:350  store store=0:0 ([]=) not bootstrapped
I160317 15:18:58.879320 raft/raft.go:459  [group 1] 1 became follower at term 5
I160317 15:18:58.879471 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160317 15:18:58.879547 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160317 15:18:58.879622 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160317 15:20:00.028396 storage/replica_command.go:68  test injecting error: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
W160317 15:20:00.029357 kv/dist_sender.go:652  failed to invoke BeginTransaction [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/2/1,/Min): read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160317 15:20:00.029643 client/db.go:418  failed batch: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160317 15:20:00.032237 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestTxnRestart (1.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	119.785s
=== RUN   TestEval
--- PASS: TestEval (0.02s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-17 15:25
Duplicate of #4787.

**Closed by petermattis** 2016-03-17 15:25 UTC
Labels: Robot, test-failure
