### ISSUE TITLE
circleci: failed tests (14519): TestLogic 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5250] opened 2016-03-14 22:28 UTC
The following test appears to have failed:

[#14519](https://circleci.com/gh/cockroachdb/cockroach/14519):

```
I160314 22:27:20.945849 storage/replica_command.go:495  auto-gc'ed d3e51ef2 (1 intents)
testdata/poison_after_push: 7
testdata/poison_after_push:33 testuser: COMMIT
testdata/poison_after_push:40 testuser: SELECT * FROM t
I160314 22:27:22.824977 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestLogic (17.24s)
	logic_test.go:531: testdata/poison_after_push:40: expected retry txn, but found <nil>
=== RUN   TestQueryCounts
W160314 22:27:22.834909 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160314 22:27:22.835282 rpc/clock_offset.go:162  monitoring cluster offset every 30s
W160314 22:27:22.836545 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160314 22:27:22.836815 server/node.go:350  store store=0:0 ([]=) not bootstrapped
I160314 22:27:22.853143 raft/raft.go:459  [group 1] 1 became follower at term 5
I160314 22:27:22.853258 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160314 22:27:22.853293 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160314 22:27:22.853325 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160314 22:27:34.594875 storage/replica_command.go:68  test injecting error: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
W160314 22:27:34.595073 kv/dist_sender.go:652  failed to invoke BeginTransaction [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/2/1,/Min): read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160314 22:27:34.595131 client/db.go:418  failed batch: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160314 22:27:34.595534 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestTxnRestart (0.16s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	41.051s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 23:43
Duplicate of #4787.

**Closed by petermattis** 2016-03-14 23:43 UTC
Labels: Robot, test-failure
