### ISSUE TITLE
rangefeed: dropping events (in catch up scan?)

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#44878] opened 2020-02-07 21:17 UTC
Found with kvnemesis.

Repro: Stress #44769 with roachprod-stress. This can take a while (1h+ sometimes)

```
make roachprod-stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisMultiNode TESTTIMEOUT=60s TESTFLAGS='-v -show-logs' CLUSTER=dan-stress
```

A bunch of previous repros with increasing amounts of debug logging are documented in https://github.com/cockroachdb/cockroach/pull/44769

The issue is that a write of a committed txn appears in kv but doesn't come out of RangeFeed before the resolved timestamp is bumped. In the following repro, follow the "cdfa3544" key. This key is written 3 times, none of which come out of RangeFeed. Other repros have been on keys that have only been written once, so it's likely not interesting that this one was overwritten.

First, the range splits and rangefeeds disconnect and reconnect on the two halves. Each half gets a resolved timestamp of 0.0 and then a real resolved timestamp:

```
I200207 19:37:57.980265 5594 storage/replica_command.go:396  [n2,s2,r30/2:/{Table/50/"50…-Max}] initiating a split of this range at key /Table/50/"5b41bf37" [r33] (manual)
...
I200207 19:37:57.991045 5104 storage/rangefeed/registry.go:539  remove /Table/5{0-1} 1581104277.875275044,0 retry rangefeed (REASON_RANGE_SPLIT)
...
I200207 19:37:57.993231 5796 storage/rangefeed/registry.go:453  register /Table/50{-/"50060c6d"} 1581104277.947404728,0
I200207 19:37:57.993275 5796 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50-/Table/50/"50060c6d" event=/Table/50-/Table/50/"50060c6d" ts=0,0
...
I200207 19:37:57.993406 5796 storage/rangefeed/registry.go:483  PublishToOverlapping event=/Min-/Max ts=1581104277.947404728,0
I200207 19:37:57.993463 5796 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50-/Table/50/"50060c6d" event=/Table/50-/Table/50/"50060c6d" ts=1581104277.947404728,0
...
I200207 19:37:57.997228 5761 storage/rangefeed/registry.go:453  register /Table/5{0/"50060c6d"-1} 1581104277.947404728,0
I200207 19:37:57.997267 5761 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50/"50060c6d"-/Table/51 event=/Table/50/"50060c6d"-/Table/51 ts=0,0
...
I200207 19:37:57.997454 5761 storage/rangefeed/registry.go:483  PublishToOverlapping event=/Min-/Max ts=1581104277.947404728,0
I200207 19:37:57.997515 5761 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50/"50060c6d"-/Table/51 event=/Table/50/"50060c6d"-/Table/51 ts=1581104277.947404728,0
```

The key is written at time 1581104277.953233825,0. The WriteIntent and CommitIntent is processed by 2/3 replicas, presumably the ones the rangefeed is not connected to.

```
I200207 19:37:58.014006 1072 storage/replica_rangefeed.go:506  [n2,s2,r33/2:/{Table/50/"5b…-Max}] WIP MVCCWriteIntentOp /Table/50/"cdfa3544" 1581104277.953233825,0 1581104277.953233825,0 1978ce52-d8db-480a-885b-529eab65460d
...
I200207 19:37:58.014461 1363 storage/replica_rangefeed.go:506  [n3,s3,r33/3:/{Table/50/"5b…-Max}] WIP MVCCWriteIntentOp /Table/50/"cdfa3544" 1581104277.953233825,0 1581104277.953233825,0 1978ce52-d8db-480a-885b-529eab65460d
...
I200207 19:37:58.018226 1032 storage/replica_rangefeed.go:506  [n2,s2,r33/2:/{Table/50/"5b…-Max}] WIP MVCCCommitIntentOp /Table/50/"cdfa3544":1581104277.953233825,0 -> /<empty> 1978ce52-d8db-480a-885b-529eab65460d
...
I200207 19:37:58.018934 1392 storage/replica_rangefeed.go:506  [n3,s3,r33/3:/{Table/50/"5b…-Max}] WIP MVCCCommitIntentOp /Table/50/"cdfa3544":1581104277.953233825,0 -> /<empty> 1978ce52-d8db-480a-885b-529eab65460d
```

The key is written to a few more times. Each time 2/3 replicas process a CommitIntent and WriteIntent, but nothing is emitted from the relevant rangefeed `{Table/50/"5b…-Max}` for a very long time. Eventually this range splits at "5b41bf37", so our key is still on the rhs, now range `/Table/5{0/"5b41bf37"-1}`. This is redialed at the same 1581104277.947404728,0 timestamp it was last time (so still correctly before our write). Some writes come out of the rangefeed (past the timestamp our key was first written at, unclear if this is interesting).

```
I200207 19:37:59.087320 7382 kv/dist_sender_rangefeed.go:151  [n1] RangeFeed dial /Table/5{0/"5b41bf37"-1} 1581104277.947404728,0
I200207 19:37:59.088383 7384 storage/rangefeed/registry.go:453  register /Table/5{0/"5b41bf37"-1} 1581104277.947404728,0
I200207 19:37:59.088425 7384 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50/"5b41bf37"-/Table/51 event=/Table/50/"5b41bf37"-/Table/51 ts=0,0
I200207 19:37:59.088505 7382 kv/dist_sender_rangefeed.go:277  [n1] RangeFeedCheckpoint req=/Table/50/"5b41bf37"-/Table/51 event=/Table/50/"5b41bf37"-/Table/51 ts=0,0
I200207 19:37:59.088532 5099 kv/kvnemesis/watcher.go:162  rangefeed Put /Table/50/"ad44127e" 1581104277.967639047,0 -> /BYTES/v-4 (prev /<empty>)
I200207 19:37:59.088554 5099 kv/kvnemesis/watcher.go:162  rangefeed Put /Table/50/"ff815392" 1581104277.962125945,0 -> /BYTES/v-3 (prev /<empty>)
```

Very shortly afterward (2 lines in the logs) a resolved timestamp is emitted by this range that is past our write, but the write hasn't come out. Incorrect!

```
I200207 19:37:59.088671 7384 storage/rangefeed/registry.go:199  maybeStripEvent req=/Table/50/"5b41bf37"-/Table/51 event=/Table/50/"5b41bf37"-/Table/51 ts=1581104278.161414786,0
I200207 19:37:59.088699 7382 kv/dist_sender_rangefeed.go:277  [n1] RangeFeedCheckpoint req=/Table/50/"5b41bf37"-/Table/51 event=/Table/50/"5b41bf37"-/Table/51 ts=1581104278.161414786,0
```

**Comment by danhhz** [comment] 2020-02-07 21:39
https://gist.github.com/danhhz/915bcc77637b25b4dbc062c6d0bd8711

**Comment by nvanbenschoten** [comment] 2020-02-19 06:39
It appears that we're dealing with a closed timestamp bug. I've reproduced this a few times, each with incrementally more logging, and there are a few things that appear consistent across all reproductions:
- the "lost" write happens immediately after a Range split
- the rangefeed gets connected to a replica that is slower (~30 ms) than the other two replicas to perform the split
- the rangefeed's catch-up scan does not observe the value even though its timestamp is above the rangefeed's starting timestamp
- the rangefeed is then notified that the range's closed timestamp was forwarded **past** the write's timestamp without the write ever being published. This ends up in a checkpoint message that blows up the test

Here's where things get interesting:
- the closed timestamp delivered to the rangefeed came from the replica's [`initialMaxClosed`](https://github.com/cockroachdb/cockroach/blob/0f0b1944a785ee8ee54446d2bf12348c0017c208/pkg/storage/replica_follower_read.go#L108)
- this `initialMaxClosed` is set [when the replicas is created](https://github.com/cockroachdb/cockroach/blob/0f0b1944a785ee8ee54446d2bf12348c0017c208/pkg/storage/store_split.go#L201) using the closed timestamp from the LHS replica
- the two leading replicas are given a different `initialMaxClosed` than the lagging replica during the split. These values are all pulled from their LHS range's closed timestamp `Provider`. The leading replicas' `initialMaxClosed` is below the lost write's timestamp. The lagging replica's `initialMaxClosed` is above the lost write's timestamp. This alone is **not** a problem on its own, however...
- one of the leading post-split replicas was able to serve as the leaseholder and perform the write at a timestamp above its `initialMaxClosed` but below the lagging replica's `initialMaxClosed`. This **is a violation of the closed timestamp monotonicity invariant** and causes the rangefeed issue we see here.

So the question is - how did a split allow us to break the closed timestamps most important property? Were the leading replicas incorrect about the closed timestamp or was the lagging replica?

**Comment by nvanbenschoten** [comment] 2020-02-19 07:30
Yes, this definitely looks like a bug in how `initialMaxClosed` interacts with the closed timestamp `Provider`. The following logs demonstrate the problem. In this setup, the lost value had a timestamp of `1582094872.333690540,0` and was written to `r31` with a lease index of 2.

The logs show the three r29 LHS replicas (r29/1 is lagging) as they split off replicas for r31.

```
I200219 06:47:52.351717 1389 storage/replica_follower_read.go:112  [n3,s3,r29/2:/{Table/50/"64…-Max}] maxClosed provider=0,0 lease=1582094870.614722590,0 init=1582094872.252432141,0
I200219 06:47:52.351741 1389 storage/store_split.go:216            [n3,s3,r29/2:/{Table/50/"64…-Max}] splitting off range 31 with LAI=8 and maxClosed=1582094872.252432141,0
I200219 06:47:52.355521 1101 storage/replica_follower_read.go:112  [n2,s2,r29/3:/{Table/50/"64…-Max}] maxClosed provider=0,0 lease=1582094870.614722590,0 init=1582094872.252432141,0
I200219 06:47:52.355548 1101 storage/store_split.go:216            [n2,s2,r29/3:/{Table/50/"64…-Max}] splitting off range 31 with LAI=8 and maxClosed=1582094872.252432141,0
I200219 06:47:53.316883 176 storage/closedts/provider/provider.go:346  found max closed nodeID=2 rangeID=29 epoch=1 lai=8 entry=CT: 1582094873.313460070,0 @ Epoch 1
    Full: false
    MLAI: r3: 49, r4: 31, r5: 10, r7: 13, r10: 10, r11: 19, r12: 10, r25: 10, r28: 45, r29: 8, r31: 2, r32: 0
I200219 06:47:53.316913 176  storage/replica_follower_read.go:112  [n1,s1,r29/1:/{Table/50/"64…-Max}] maxClosed provider=1582094873.313460070,0 lease=1582094870.614722590,0 init=1582094872.252432141,0
I200219 06:47:53.316937 176  storage/store_split.go:216            [n1,s1,r29/1:/{Table/50/"64…-Max}] splitting off range 31 with LAI=8 and maxClosed=1582094873.313460070,0
```

Things to notice:
- neither of the first two r29 replicas has a closed timestamp from their provider, so they set the `initialMaxClosed` on their r31 children to their own `initialMaxClosed`: `1582094872.252432141,0`.
- the third r29 replica has a closed timestamp from its provider, so it sets this as the `initialMaxClosed` on its r31 child: `1582094873.313460070,0`.
- the split occurs at r29's lease index 8.
- when r29/1 set its child's `initialMaxClosed`, it had received a closed timestamp entry with an MLAI map containing `[..., r29: 8, r31: 2, ... ]`.
- the `initialMaxClosed` timestamp is set in a `splitPostApply` call on the parent range, so it considers the split entry to already be applied for the purposes of its call to `maxClosed`.

So what we see here is that because r29/1 was lagging so far behind, it had received a closed timestamp entry that included information about both r29 and r31. It then used its current lease applied index (which included the split entry itself!) to retrieve the timestamp of this entry and set it as the `initialMaxClosed` of r31/1. That's where it got itself in trouble because we know from the closed timestamp entry that r31 didn't close out that timestamp until after it applied LAI 2.

So what's the bug here? Well, you could argue that r29/1 should have noticed that r31 already had a closed timestamp entry and should have done something differently because of it. That's not really the issue though. The problem is that assigning the `initialMaxClosed` to the new RHS from the provider while considering the split Raft entry's lease index to be applied is semantically incorrect. To make this dramatically clear, consider the LHS of a split quiescing immediately after a split and continuing to forward its closed timestamp at the same LAI. If a slow follower heard about these updates for hours and then finally applied the split entry, it would be obviously incorrect for it to set an `initialMaxClosed` of this current time on the RHS range, which may have a large Raft log to catch up on.

I believe that the semantically correct fix here would be to determine this `initialMaxClosed` without considering the current log entry to be applied. In other words, a closed timestamp formed on the split entries lease index should not make it into the RHS, so `initialMaxClosed` must come from the closed timestamp formed on the previous lease index. This is easy enough to do – we can just move the `initialMaxClosed` call to `acquireSplitLock`, where the `*Replica` object is actually created.

**Comment by nvanbenschoten** [comment] 2020-02-19 07:56
Separately, I also think there's something going wrong with closed timestamps and range merges. I'm not sure exactly what I'm seeing in this test, but from a high-level, I don't understand how they are expected to interact.

I wonder if we need to block closed timestamp notifications for ranges that have been frozen by a subsume request. Or we at least need to block rangefeed checkpoint publications some other way while a range is in this state. Maybe @tbg can take over for me on that train of thought as I'm signing off for the night.

**Comment by tbg** [comment] 2020-02-19 12:58
Great analysis, @nvanbenschoten. That is a subtle bug. It's interesting that we were clearly thinking about this sort of thing but not quite catching on:

https://github.com/cockroachdb/cockroach/blob/b2850e12dfb1d436fcf9af522cad142af7501bbc/pkg/storage/store_split.go#L208-L211

To make sure I have paged this back in correctly, using `SplitLAI-1` is safe because the split trigger itself declares a read of the entire RHS (at the commit timestamp)?
Concretely, let's say the raft log has a `Put` at `ts=10`, `LAI=99`, and then the `Split` at `ts=20`, `LAI=100`. On each of the replicas, `MaxClosed(ctpb.LAI(99))` may return a different timestamp, but they're all `< 20` so it doesn't matter: the RHS will never accept any writes at `ts <= 20`.

> This is easy enough to do – we can just move the initialMaxClosed call to acquireSplitLock, where the *Replica object is actually created. This is called while the Raft application batch (which will contain only the split entry) is being staged, so the replica's LAI will not have been updated yet.

SGTM. Another is to pass the LAI explicitly into `maxClosed`, but I prefer your suggestion.

> Separately, I also think there's something going wrong with closed timestamps and range merges.

I think you're on to something here. When we freeze the RHS, we get a [FreezeTimestamp](https://github.com/cockroachdb/cockroach/blob/64e3f46d4ff6f4f17a882dc36134466a9a820d7e/pkg/storage/batcheval/cmd_subsume.go#L133) back which is an upper bound on all writes and read timestamps ever served by that range. However, the range will happily continue to announce new closed timestamps. When the LHS applies the merge trigger, it [don't seem to care](https://github.com/cockroachdb/cockroach/blob/b2850e12dfb1d436fcf9af522cad142af7501bbc/pkg/storage/store_merge.go#L27-L32) about the RHS' maxClosed at all. In effect, the LHS may ultimately accept writes to the span once belonging to the RHS that were previously closed out (by the now-defunct RHS leaseholder). We need to strengthen `FreezeTimestamp` so that it also bounds the closed timestamp emitted by the RHS (under the active lease), which means "pausing" closed timestamps as you suggested. I don't see an obvious way to implement this, so we're going to have to think about it (registering a long-open command with the tracker is bad as it holds up the store-wide CT, emitting faux LAIs is also tricky, etc). Maybe we do need to introduce an explicit "paused" state that is similar to quiescence but without tracking the store-wide CT. I'm skeptical about trying to hack around this in RangeFeed itself as that seems to amount to adding hard-to-understand complexity for the sole purpose of masking missing functionality in the CT subsystem.

**Comment by andreimatei** [comment] 2020-06-04 20:15
Putting a keyword here just to see if the cat licks it up - on the merge trigger, could we simply populate the tscache of the merged range with a span covering the rhs and a timestamp corresponding to the RHS's closed timestamp?

**Comment by nvanbenschoten** [comment] 2020-06-04 21:28
We do already populate the timestamp cache of the merged range with a span covering the rhs and the _subsumption time_ [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/store_merge.go#L88)

But where would we get the RHS's _closed timestamp_? How would we know that the RHS hasn't continued to broadcast larger closed timestamps since we grabbed it? I believe that replica subsumption is the last point at which we synchronous coordinate with the RHS leaseholder.

That's why it seems like we'll need to pause closed timestamp notifications on ranges that are being subsumed. But maybe that's missing a cleaner solution.

**Comment by nvanbenschoten** [comment] 2020-06-04 21:30
Is your suggestion assuming that the leaseholders of the RHS and LHS range will be collocated? I don't think we have that guarantee, do we?

**Comment by andreimatei** [comment] 2020-06-04 22:09
I was assuming collocated leaseholders, but I don't really know how merges work

**Comment by aayushshah15** [comment] 2020-06-08 17:52
> When we freeze the RHS, we get a FreezeTimestamp back which is an upper bound on all writes and read timestamps ever served by that range. However, the range will happily continue to announce new closed timestamps.

This is actually mentioned in the [follower reads RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20180603_follower_reads.md#splitsmerges), but it doesn't seem to account for the closed timestamp updates the RHS leaseholder continues to broadcast after the subsume call. On top of this, `SubsumeResponse` doesn't currently contain the RHS store's closed ts as of subsumption time either. 

I have a question: instead of trying to pause the entire store's closed timestamp updates, could we add a mechanism to omit the subsumed range's entry in the MLAI map for future closed ts updates? The solution would then be as follows: 
1. In `Subsume`, somehow ensure that future closed ts updates from the RHS's store won't contain the RHS range's ID in their MLAI map. Record the latest closed timestamp as of this time. This sounds doable since `Subsume` is only called on the RHS range's leaseholder. Additionally, sounds like we already try to do something similar for quiescent ranges?
2. `SubsumeResponse` will contain the closed ts we just recorded. 
3. In the merge trigger, the subsuming range will bump its timestamp cache low water mark with the recorded closed timestamp, the [way it currently does for the freeze timestamp](https://github.com/cockroachdb/cockroach/blob/a43a1d282bb2209d1c216053d88e11c1e505e343/pkg/kv/kvserver/store_merge.go#L88).

I'm currently trying to figure out details for how / if step 1 can be done.

**Comment by ajwerner** [comment] 2020-06-08 22:58
Discussed with @aayushshah15 offline for a while. I think so long as we prevent closed timestamps from increasing on followers while the merge is in its critical phase, we should be okay. One way to do that is to ensure that those followers have not applied the MLAI being propagated through the closed timestamp subsystem. A way to achieve that is to propagate an index of a proposal which hasn't yet been proposed. The subsumption and its properties make this less crazy than it sounds. I theorize (without having run it), that the below patch will fix this bug. Having a deterministic or at least rapid reproduction of the bug will be nice.

```go
diff --git a/pkg/kv/kvserver/replica.go b/pkg/kv/kvserver/replica.go
index d8178af059..982ee6bc47 100644
--- a/pkg/kv/kvserver/replica.go
+++ b/pkg/kv/kvserver/replica.go
@@ -1272,6 +1272,24 @@ func (r *Replica) maybeWatchForMerge(ctx context.Context) error {
        // range in case it managed to quiesce between when the Subsume request
        // arrived and now, which is rare but entirely legal.
        r.unquiesceLocked()
+
+       // This range represents the leaseholder of a RHS in the critical phase of a
+       // merge. It would be problematic if a closed timestamp above the subsumption
+       // were to be propagated as it might lead to a resolved timestamp on a
+       // rangefeed for the RHS which is above a future write on the LHS (see issue
+       // #44878). In order to prevent the present timestamp from being closed, we
+       // publish a LAI for a proposal which has not yet been issued. That proposal
+       // will ultimately need to either be the one which aborts the merge or commits
+       // the merge. The point being, until another command commits, no followers
+       // will be able to act on a published closed timestamp.
+       //
+       // It is the case that a present follower can forcibly take the lease but we
+       // call this method on new leaseholders when they take the lease. No new
+       // actionable closed timestamp should be published for this range until the
+       // next command proposed under the lease commits.
+       _, untrack := r.store.cfg.ClosedTimestamp.Tracker.Track(ctx)
+       untrack(ctx, ctpb.Epoch(r.mu.state.Lease.Epoch), r.RangeID,
+               ctpb.LAI(r.mu.state.LeaseAppliedIndex+1))
        r.mu.Unlock()
        taskCtx := r.AnnotateCtx(context.Background())
```

**Comment by nvanbenschoten** [comment] 2020-06-11 17:25
@aayushshah15's proposal in https://github.com/cockroachdb/cockroach/issues/44878#issuecomment-640779111 sounds complete, but I think it's overcomplicated. We know that the closed timestamp at the time of subsumption will be less than the freeze time because the freeze time comes from the leaseholder's clock, so we should be able to skip steps 2 and 3.

That leaves us with what @ajwerner proposed, preventing closed timestamps from increasing while the merge is in its critical phase by artificially pushing the required LAI for any future closed timestamp entry to an LAI after the merge completes and boxing out closed timestamp entries with the current LAI. Semantically, that seems correct. In practice, I think we'll need to be careful that we're explicit about the assumptions we're relying on and that the implementation of these components actually obeys those assumptions. Here are a few assumptions that we'll need to confirm:
1. the LAI that follows a Subsume request **must** be the applied only _after_ the merge completes. The RHS range will be destroyed if the merge completes successfully, so the LAI that follows a Subsume request **must** be applied only _after_ the merge aborts, if applicable. This is an extension/specialization of the subsumption promises discussed in [the range merges tech note](https://github.com/cockroachdb/cockroach/blob/master/docs/tech-notes/range-merges.md#transfer-of-power). In practice, this guarantee seems to hold because lease requests do not bump the lease applied index and they are the only Raft proposals allowed (I think... are there requests that don't acquire any latches that could sneak through? `ComputeChecksumRequest`?) on the RHS, but we'll want to be clear about that now being a critical component of the correctness here.
2. tracking an LAI in the ClosedTimestamp tracker ensures that we never broadcast an update for any LAI less than that going forward.
3. we never broadcast a closed timestamp entry between the time that we evaluate the Subsume request and the time that we run `maybeWatchForMerge` for the first time. I don't think the proposed patch guarantees this, so we may need to lift the `Tracker.Track` up above `SubsumeRequest` evaluation. Or into `SubsumeRequest` evaluation.

**Comment by ajwerner** [comment] 2020-06-11 23:30
> 3. we never broadcast a closed timestamp entry between the time that we evaluate the Subsume request and the time that we run maybeWatchForMerge for the first time. I don't think the proposed patch guarantees this, so we may need to lift the Tracker.Track up above SubsumeRequest evaluation. Or into SubsumeRequest evaluation.

This seems real. It should be easy enough to add the call to `Track` above evaluation in `executeReadOnlyBatchWithServersideRefreshes` and then stick then stick the untrack closure into the `LocalResult` for use in or around the call to `maybeWachForMerge`. I suspect it'd be fine to pass the closure into the call. 

In practice it would mean that somehow the world stalled for an amount of time on the order of the closed timestamp duration but it's better to be careful here.

**Comment by ajwerner** [comment] 2020-06-12 00:11
I think we can revise point 3 to say:

3. we never broadcast a closed entry **after the freeze time** between the time that we evaluate the Subsume request and the time that we run `maybeWatchForMerge` for the first time. 

Hence the `In practice` comment. On the whole though it seems worth threading it appropriately.

**Comment by aayushshah15** [comment] 2020-06-12 17:47
Few more questions:
1. I learned today that the subsumed leaseholder of the RHS blocks all requests (and not just writes as I had naively assumed). It seems to even be [blocking all historical reads](https://github.com/cockroachdb/cockroach/blob/603b31c5b0c277b82381bc716322004aab1a4e16/pkg/kv/kvserver/replica_read.go#L40). Does anyone know why we do this? In fact, with the solution currently in the discussion, it seems like we have this asymmetry where we would allow historical follower reads (i.e. reads before the freeze timestamp) on the RHS range's followers but the same reads would block if routed to the leaseholder.
2. @andreimatei and I were discussing the possibility of co-locating the LHS and RHS leaseholders during a merge. It seems like this might make certain things a bit easier. For example: if the LHS and RHS shared a timestamp cache it would be possible to allow the RHS to continue serving reads even while a merge is in progress. This approach could also make it easier to reason about the interactions with rangefeeds. I'm personally not sure what the tradeoffs are though. Any thoughts?

**Comment by ajwerner** [comment] 2020-06-12 18:33
2. Seems not worth the effort to enforce. Leases can always move, even in the critical phase of a merge. Given that, trying to make it an invariant needed for correctness seems foolhardy.

**Comment by andreimatei** [comment] 2020-06-12 18:39
> Leases can always move, even in the critical phase of a merge

Can they? My understanding is that the lease post-apply hook already deals with new leases for frozen ranges by blocking reads from them. I think that's sufficient for what we want here. With no new reads, the timestamp cache on the rhs on the leaseholder at the time the lhs and rhs were collocated should stay valid, right?

I'm thinking that it'd be great for reads to the rhs to not be blocked for the duration of the merge transaction.

**Comment by ajwerner** [comment] 2020-06-12 18:46
Now you're talking about something different, you're talking about moving the timestamp cache. That feels like a different goal altogether. I'm on-board with the idea, just think it doesn't fall into this issue.

All this being said, I think it'd be reasonable to solve 1. by looking if the read-only query would be serviceable with a follower read when you might block it due to the merge and only then serve it. That would break the asymmetry and not need us to think about the timestamp cache for now.

**Comment by nvanbenschoten** [comment] 2020-06-12 19:48
> I'm thinking that it'd be great for reads to the rhs to not be blocked for the duration of the merge transaction.

Some of this is discussed in https://github.com/cockroachdb/cockroach/pull/39765 and in https://github.com/cockroachdb/cockroach/issues/32583#issuecomment-515852516. The thing to be very careful with here is uncertainty windows. Even if a read's timestamp is below the freeze time, it would be incorrect to serve the read if it has an uncertainty window that exceeds the freeze time.

**Comment by andreimatei** [comment] 2020-06-12 19:57
The way I see it, it's all about the timestamp cache. The problem is that, if a follower "activates" one of these closed timestamps and serves reads, those reads would not be correctly reflected by the merged range's timestamps cache (right?). And your solution is to make sure that followers don't activate the closed timestamps by publishing them with a MLAI that will never come (in case the merge commits).

But isn't that backwards? We're trying to prevent followers from serving follower reads, and at the same time we're also preventing writes to the range. These seem contradictory - if there's no writes, one would think that the followers can serve reads just fine. And, in fact, I'd also like the leaseholder to serve non-stale reads after the subsume. That's be cool, right? To make the merging as non-disruptive as possible - particularly considering that merging is a global operation, whereas follower reads want local latencies.
So, let's see if we could make merges not block reads on the rhs.

Strawman:
1) only start merging when lhs and rhs leases are collocated on a store (and thus the tscache is shared)
2) once the RHS has been subsumed, the current leaseholder continues both serving reads and publishing closed timestamps (with the regular LAI, no +1 tricks)
3) if the lease for the RHS changes hands while the range is subsumed (which, IIUC, is already detected through an intent on the... range-local copy of the RHS descriptor?) then this new leaseholder cannot serve reads and also cannot publish closed timestamps. We can use the MLAI=LAI+1 idea.
4) if the merge commits and the rhs lease has not moved (and is still valid), then the timestamp cache for the rhs does not need to be set to anything - the shared  tscache has recorded all the regular reads and the closed timestamps that were published by the shared node are also naturally accounted for.

**Comment by ajwerner** [comment] 2020-06-12 20:23
I buy what you're saying about the RHS. What mechanism do we have in place to prevent the lease on the LHS from moving?

**Comment by andreimatei** [comment] 2020-06-12 22:35
Well I'm thinking we wouldn't prevent it from moving in any particular way. If it moves, then we fallback to preventing reads by doing the LAI+1.
But if a merge commit hook notices that the RHS lease hasn't moved and is still valid, it rejoices and leaves the tscache be.

**Comment by ajwerner** [comment] 2020-06-12 22:36
I think you missed what I’m saying. I hear you about the LAI+1 trick for lease movement on the RHS but what happens if the lease moves on the LHS?

**Comment by andreimatei** [comment] 2020-06-12 22:53
Hmm, I did miss what you were saying. Indeed, if the LHS lease moves, then the closed timestamps that have been published in the meantime for the RHS become problematic again, as do regular reads that have been served by the RHS leaseholder. Maybe this is the turd in the punch bowl; I'll sleep on it.

**Closed** 2020-08-04 06:15 UTC
Labels: C-bug
