### ISSUE TITLE
sentry: conn_executor.go:643: panic while executing 1 statements: SELECT _.*, _._ FROM _ AS _ LEFT JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE ((_._ = _) AND (_._ = _)) AND (_._ = _._) GROUP BY _.*, _._ ORDER BY _._ ASC: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33190] opened 2018-12-17 11:50 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/811617516/?referrer=webhooks_plugin

conn_executor.go:643: panic while executing 1 statements: SELECT _.*, _._ FROM _ AS _ LEFT JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE ((_._ = _) AND (_._ = _)) AND (_._ = _._) GROUP BY _.*, _._ ORDER BY _._ ASC: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 313, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1173, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 752, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2299, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2329, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForDistinct', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2658, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2279, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2273, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForLookupJoin', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 1844, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2273, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForLookupJoin', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 1918, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'convertOrdering', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 935, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'panicindex', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 28, u'filename': u'runtime/panic.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:643: panic while executing 1 statements: SELECT _.*, _._ FROM _ AS _ LEFT JOIN _ AS _ ON _._ = _._ LEFT JOIN _ AS _ ON _._ = _._ WHERE ((_._ = _) AND (_._ = _)) AND (_._ = _._) GROUP BY _.*, _._ ORDER BY _._ ASC: caused by <redacted>

**Comment by jordanlewis** [comment] 2018-12-17 20:19
```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in convertOrdering at line 935
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForLookupJoin at line 1918
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2273
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForLookupJoin at line 1844
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2273
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2279
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForDistinct at line 2658
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2329
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2299
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 752
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1173
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 313
```

**Comment by jordanlewis** [comment] 2018-12-18 14:45
Dupe of #33179

**Closed by jordanlewis** 2018-12-18 14:45 UTC
Labels: C-bug, O-sentry
