### ISSUE TITLE
Rust & postgres_types & Enums / Json not working as expected

### ISSUE THREAD

**Issue by davecline** [cockroachdb/cockroach#57411] opened 2020-12-02 22:28 UTC
We're trying to get a simple postgres/cockroach example that contains Rust Enums and serde_json::Value types into and out of a table.

Thus far we've not succeeded.

We've tried to use straight VARCHAR as the column type for the Rust Enum, but we get errors when we try to insert:
> Error: error serializing parameter 2: cannot convert between the Rust type `project::models::MyEnum` and the Postgres type `varchar`

We've tried to use Postgres.Enum types but get odd:
> Error: error deserializing column 1: cannot convert between the Rust type `i8` and the Postgres type `bpchar`

We've tried SQLx, Tokio_postgres, and the associated "ToSql" & "FromSql"

Could someone on the CockroachDb team code up a more comprehensive test case that includes Enums?

The whole serde_json::Value thing we might be able to handle using SQLx, but it's still not ideal using two separate crates to deal with the common column types we expect.

If someone reads this and needs more info/sample program... I'll check back here in a few days.

**Comment by rafiss** [comment] 2020-12-03 00:04
Thanks for the report! A simple code example that reproduces would be very helpful. If you are able to, it would be even more helpful if you could use Wireshark to capture the traffic sent back and forth between the Rust app and CockroachDB, and attach the capture here.

**Comment by davecline** [comment] 2020-12-03 23:03
Going to try and add information to this post for your elucidation...

##############
Cargo.toml:
```
[package]
name = "pg-sqlx"
version = "0.1.0"
authors = ["Scott Hawker <shawker@dsco.io>"]
edition = "2018"

[dependencies]
postgres-openssl = "0.4.0"
uuid = { version = "0.8.1", features = ["v4", "serde"] }
tokio = { version = "0.2", features = ["macros"] }
chrono = { version = "0.4.2", features = ["serde"] }
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
sqlx = { version = "0.4.0", features = [ "runtime-tokio-rustls", "postgres", "uuid", "chrono", "json" ] }
dotenv = "0.15.0"
strum = { version = "0.20", features = ["derive"] }
strum_macros = "0.20"
```

//////////////////////////
main.rs
```
extern crate strum;
#[macro_use] extern crate strum_macros;
use dotenv;
use serde_json::{json, Value};
use std::env;
use sqlx::{PgPool};
use sqlx::types::{Uuid};
use sqlx::types::chrono::{DateTime, Utc};
use std::error::Error;

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {

    // Setup and acquire a connection to the database (will use the "pool" concept as is how we'll use it in production
    // Your connection string will have to have had the CA file stored locally and specified (see the .env file).
    dotenv::dotenv().ok();
    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL not defined in .env file");
    let pool = PgPool::connect(&database_url).await?;

    // Define the object with Enum and serde_json::Value type
    let mut sample = Stuff{
        my_name: "Fallow".to_owned(),
        my_mood: Mood::Ok,
        an_optional_string: Some("is in stock".to_owned()),
        a_position: 4321,
        is_active: true,
        the_id: None,
        create_date: None,
        some_json: Some(json!({ "title":"Rannie", "age":47, "active":false }))
    };

    let sql = 
        "INSERT INTO defaultdb.stuff (my_name, an_optional_string, a_position, is_active, my_mood, some_json ) 
         VALUES ($1, $2, $3, $4, $5, $6) 
         RETURNING the_id"; 

    // Insert the object into the Postgres table
    println!("{:?}", &sql);
    let result: (Uuid,) = sqlx::query_as(sql)
        .bind(&sample.my_name)
        .bind(&sample.an_optional_string)
        .bind(&sample.a_position)
        .bind(&sample.is_active)
        .bind(&sample.my_mood)
        .bind(&sample.some_json)
        .fetch_one(&pool)
        .await?;

    // Update the local object with the UUID that was returned from the insert
    sample.the_id = Some(result.0);
    println!("\nthe_id: {}", sample.the_id.unwrap());

    // Update the object and then update the database table
    sample.my_mood = Mood::Happy;
    sample.some_json = Some(json!({"arbitraryJson":"json values here","tag":"circular","count":123}));
    let sql = 
        "UPDATE defaultdb.stuff SET some_json = $2 WHERE the_id = $1"; 
    sqlx::query(sql)
        .bind(&sample.the_id)
        .bind(&sample.some_json)
        .execute(&pool)
        .await?;

    // Fetch the database instance into a local object instance and print it out
    let sql = 
        "SELECT my_name, an_optional_string, a_position, is_active, the_id, create_date, my_mood, some_json
         FROM defaultdb.stuff WHERE the_id = $1";
    let instance: Stuff = sqlx::query_as(&sql)
        .bind(&sample.the_id)
        .fetch_one(&pool)
        .await?;

    dbg!{instance};

    Ok(())
}
#[derive(sqlx::Type, Debug, Display, EnumString)]
#[sqlx(rename = "VARCHAR", rename_all = "lowercase")]
enum Mood {
    Sad,
    Ok,
    Happy,
}

#[derive(Debug, sqlx::FromRow)]
struct Stuff {
    my_name: String,
    my_mood: Mood,
    an_optional_string: Option<String>,
    a_position: i64,
    is_active: bool,
    the_id: Option<Uuid>, // populated on insert
    create_date: Option<DateTime<Utc>>, //populated on insert
    some_json: Option<Value>, // Arbitrary nested json
}
```

##############
.env file
```
DATABASE_URL=postgresql://defaultdbUser:PW_HERE@INSTANCE_NAME.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&sslrootcert=/Volumes/secure/cockroach-ca.crt
```
* We assume you have creds and a CA cert to use.

------------------
DDL:
```
CREATE TABLE defaultdb.public.stuff (
	the_id UUID NOT NULL DEFAULT gen_random_uuid(),
	my_mood VARCHAR NOT NULL,
	my_name VARCHAR NOT NULL,
	an_optional_string VARCHAR NULL,
	a_position INT8 NOT NULL DEFAULT 0:::INT8,
	some_json JSONB NULL,
	is_active BOOL NOT NULL DEFAULT true,
	create_date TIMESTAMPTZ(6) NOT NULL DEFAULT now():::TIMESTAMPTZ,
	CONSTRAINT s2_pk PRIMARY KEY (the_id ASC),
	FAMILY "primary" (the_id, my_mood, my_name, an_optional_string, a_position, some_json, is_active, create_date)
);
```

### Of note is the Enum where we have to
``` #[sqlx(rename = "VARCHAR", rename_all = "lowercase")] ```

 the declaration otherwise we get the dreaded:
```
Error: ColumnDecode { index: "1", source: "mismatched types; Rust type `i8` (as SQL type `\"CHAR\"`) is not compatible with SQL type `CHAR`" }
```
From what we can tell, normal postgres does not induce this issue.

**Comment by davecline** [comment] 2020-12-03 23:05
Also note: We're not using the postgres provided "ENUM" type. We tried that, and and set the table's mood column to that type, but then all sorts of additional errors cropped up.

**Comment by davecline** [comment] 2020-12-18 17:20
https://github.com/launchbadge/sqlx/blob/master/tests/postgres/derives.rs

That should be the test script to confirm that Cockroachdb fully works with Rust::sqlx.

**Comment by rafiss** [comment] 2020-12-18 17:23
@davecline I ran the code you provided in the comment (https://github.com/cockroachdb/cockroach/issues/57411#issuecomment-738426389) (and removed the sqlx rename directive) but I got a different error:

```
"INSERT INTO defaultdb.stuff (my_name, an_optional_string, a_position, is_active, my_mood, some_json ) \n         VALUES ($1, $2, $3, $4, $5, $6) \n         RETURNING the_id"
Error: RowNotFound
```

It looks like that error could be related to this issue: https://github.com/launchbadge/sqlx/issues/237

Also, it looks like when I run that code against Postgres, I get the same RowNotFound error.

 Which versions are you using? Here is my information:
* CockroachDB v20.2.2
* cargo 1.48.0

I will try the https://github.com/launchbadge/sqlx/blob/master/tests/postgres/derives.rs script now

**Comment by rafiss** [comment] 2020-12-18 18:31
I ran the `tests/postgres/derives.rs` test against CockroachDB v20.2.2 and I see the following:

```
running 13 tests
test test_from_row_tuple ... FAILED
test test_from_row_with_rename ... FAILED
test test_enum_type ... FAILED
test test_unprepared_type_transparent ... FAILED
test test_from_row ... FAILED
test test_from_row_with_keyword ... FAILED
test test_prepared_type_transparent ... FAILED
test test_default ... FAILED
test test_unprepared_type_strong_enum ... ok
test test_record_type ... FAILED
test test_prepared_type_weak_enum ... ok
test test_prepared_type_strong_enum ... ok
test test_unprepared_type_weak_enum ... ok
```

So it looks like the enum tests work, but there are a lot of other problems. I made issue https://github.com/cockroachdb/cockroach/issues/58074 to track the broader issue of supporting sqlx.

But to your initial bug report, I am not seeing the error you are seeing with enums. Maybe it's because of the CockroachDB version you are using?

**Comment by rafiss** [comment] 2020-12-18 19:20
Also, I found the bug with using database ENUM types. (the `cannot convert between the Rust type i8 and the Postgres type bpchar` bug.) The problem is with this query:

```
SELECT typname, typcategory, typrelid, typelem FROM pg_catalog.pg_type WHERE oid = $1
```

sqlx runs this query to get metadata about the enum type. The problem is that in PostgreSQL, `typcategory` is a `"char"` type, but in CockroachDB it is a `text` type. We actually do have another issue that covers this problem here: https://github.com/cockroachdb/cockroach/issues/57301

**Comment by rafiss** [comment] 2020-12-18 22:28
The enum issue will be resolved by PRs https://github.com/cockroachdb/cockroach/pull/58084 and https://github.com/cockroachdb/cockroach/pull/58084

We will use #58074 to track any further issues with sqlx, so I will close this issue for now. Thanks for the bug report!

**Closed by rafiss** 2020-12-18 22:28 UTC
Labels: A-sql-pgwire, O-community
