### ISSUE TITLE
sql: Crash caused by panic: Non-nullable column with no value!

### ISSUE THREAD

**Issue by dendon** [cockroachdb/cockroach#26938] opened 2018-06-23 18:43 UTC
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

```grep -F '[config]' cockroach-data/logs/cockroach.log
I180623 18:33:10.174584 1 util/log/clog.go:1131  [config] file created at: 2018/06/23 18:33:10
I180623 18:33:10.174584 1 util/log/clog.go:1131  [config] running on machine: db-1
I180623 18:33:10.174584 1 util/log/clog.go:1131  [config] binary: CockroachDB CCL v2.1.0-alpha.20180604 (x86_64-unknown-linux-gnu, built 2018/06/04 14:39:32, go1.10)
I180623 18:33:10.174584 1 util/log/clog.go:1131  [config] arguments: [cockroach-server/cockroach --cache=20% --max-sql-memory=20% --max-disk-temp-storage=20% --logtostderr=INFO --certs-dir=certs start]
I180623 18:33:13.684931 100 cli/start.go:606  [config] clusterID: ef4bdebc-6f30-49d9-be9f-5c6430ed5ed5
```

2. Please describe the issue you observed:

- What did you do?
Dropped the column (tag_date_day) that caused the crash afterwards.
Even after 3 restarts, the db randomly keeps crashing.

```
E180623 18:28:57.818212 1073 util/log/crash_reporting.go:477  [n1,client=127.0.1:38768,user=root] Reported as error 471aeccb8a1349b8849935e218e500ae
panic: Non-nullable column "video:tag_date_day" with no value! Index scanned was "primary" with the index key columns (id) and the values (341574605735198721) [recovered]
        panic: panic while executing 1 statements: SELECT * FROM _._._ WHERE _ = $1 LIMIT _; caused by Non-nullable column "video:tag_date_day" with no value! Index scanned was "primary" with the index key columns (id) and the values (341574605735198721)

goroutine 1073 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc42829e000, 0x29f1580, 0xc428288700, 0x22b5a80, 0xc427c587c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:653 +0x367
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc42829e000, 0x29f1580, 0xc428288700)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:399 +0x61
panic(0x22b5a80, 0xc427c587c0)
        /usr/local/go/src/runtime/panic.go:505 +0x229
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc4202a33a0, 0x29f1640, 0xc4269bbe90)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1208 +0x9d1
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc4202a33a0, 0x29f1640, 0xc4269bbe90, 0x1, 0x41, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:960 +0x183
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc4202a33a0, 0x29f1640, 0xc4269bbe90, 0xc42829e498, 0xc42829e428, 0x0, 0x0, 0xc42dfae690, 0x7fffffffffffffff, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:974 +0x5a
github.com/cockroachdb/cockroach/pkg/sql.(*scanNode).Next(0xc4202a3200, 0x29f1640, 0xc4269bbe90, 0xc42829e498, 0xc42829e428, 0xc42dfae690, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/scan.go:210 +0x75
github.com/cockroachdb/cockroach/pkg/sql.(*limitNode).Next(0xc42dfae690, 0x29f1640, 0xc4269bbe90, 0xc42829e498, 0xc42829e428, 0xc42dfae690, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/limit.go:92 +0x77
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).forEachRow(0xc42829e000, 0x29f1640, 0xc4269bbe90, 0xc42829e498, 0xc42829e428, 0x29e6400, 0xc42dfae690, 0xc429884c40, 0x10, 0x7e1a03bc56d32c82)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:764 +0x60
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithLocalEngine(0xc42829e000, 0x29f1640, 0xc4269bbe90, 0xc42829e428, 0x3, 0x7fca29b1de08, 0xc42bb1dd00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:709 +0x1f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42829e000, 0x29f1640, 0xc4269bbe90, 0x29f3d40, 0xc428055500, 0xc428104a80, 0x3f, 0x43, 0xc428fbc150, 0x2d, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:657 +0x7de
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42829e000, 0x29f1640, 0xc4269bbe90, 0x29f3d40, 0xc428055500, 0xc428104a80, 0x3f, 0x43, 0xc428fbc150, 0x2d, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:398 +0xb33
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42829e000, 0x29f1640, 0xc4269bbe90, 0x29f3d40, 0xc428055500, 0xc428104a80, 0x3f, 0x43, 0xc428fbc150, 0x2d, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:92 +0x358
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42829e000, 0x29f1580, 0xc428288700, 0xc426d23200, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1108 +0x1280
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42029fc00, 0x29f1580, 0xc428288700, 0xc42905b01b, 0x4, 0xc42905b00d, 0x4, 0x0, 0x0, 0x29d7c40, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:401 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func3(0xc42029fc00, 0x29f1580, 0xc428288700, 0xc42829a000, 0x5400, 0x15000, 0xc42094a600, 0xc426d23200, 0xc426d231f0, 0xc42d403fd0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:266 +0x122
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:265 +0xf27
```

**Comment by dendon** [comment] 2018-06-23 19:57
After noticing that a SELECT * caused it, I replaced all SELECT queries to supply the columns they require to not use wildcards anymore.

Which didn't 'hot-fixed' it, yet the message changed a bit

```
panic: Non-nullable column "video:tag_date_day" with no value! Index scanned was "primary" with the index key columns (id) and the values (341567886164721665)

goroutine 21828 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc420158690, 0x29f1580, 0xc42fd7a3c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:1208 +0x9d1
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc420158690, 0x29f1580, 0xc42fd7a3c0, 0xc42fd7a7c0, 0x40, 0x38, 0x2497b40, 0x1, 0x0, 0x38)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:960 +0x183
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc420158690, 0x29f1580, 0xc42fd7a3c0, 0xc426e70170, 0x1, 0x1, 0x1, 0x1, 0xc8, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:974 +0x5a
github.com/cockroachdb/cockroach/pkg/sql/backfill.(*ColumnBackfiller).RunColumnBackfillChunk(0xc420158690, 0x29f1580, 0xc42fd7a3c0, 0xc4256761a0, 0xc4289d7090, 0x5, 0x3400000039, 0x167, 0x153ad7ee6c3dbb81, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/backfill/backfill.go:215 +0xf04
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk.func1(0x29f1580, 0xc42fd7a3c0, 0xc4256761a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:84 +0x173
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x29f1580, 0xc42fd7a3c0, 0xc4256761a0, 0xc427410ea0, 0x153ae2181a8b478c, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:516 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc4256761a0, 0x29f1580, 0xc42fd7a3c0, 0xc425670101, 0xc426e70120, 0xc42cd218e8, 0xc42cd218d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:748 +0x10c
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc4209afd10, 0x29f1580, 0xc42fd7a3c0, 0xc4288a1a40, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:515 +0x133
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk(0xc420158300, 0x29f1640, 0xc42a75e390, 0xc4304bcfc0, 0x1, 0x1, 0xc42fcd99d8, 0xc, 0x61bc9, 0xc429fe3c90, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:73 +0x141
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).mainLoop(0xc420158300, 0x29f1640, 0xc42a75e390, 0x0, 0x29f1640)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:128 +0x5de
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).Run(0xc420158300, 0x29f1640, 0xc42a75e390, 0xc42c3fa538)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:80 +0x197
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:492 +0x3f4
```

**Comment by solongordon** [comment] 2018-06-27 15:22
Thank you for the bug report. If there's no sensitive info, would you mind sharing the output of `SHOW CREATE TABLE <table name>` for the relevant table, as well as the full query which is causing the error?

**Comment by dendon** [comment] 2018-06-27 23:36
Thanks for you reply @solongordon.

Actually, I can't run any query on the db anymore as it crashes seconds (< 5s) after starting it.
If you want, I can try to create a `CREATE TABLE` that matches the scheme the best possible at the moment when this occurred.

The query was: `SELECT * FROM web.video WHERE id = $1 LIMIT 1`

**Comment by RaduBerinde** [comment] 2018-06-28 12:21
CC @vivekmenezes  Looks like the column had been dropped.

**Comment by solongordon** [comment] 2018-06-28 14:06
Thanks for the query. Yes, if you could provide your best guess at what the table schema was before you dropped the column, that might be helpful in reproducing the bug.

**Comment by dendon** [comment] 2018-06-28 14:51
@RaduBerinde 
> What did you do?
Dropped the column (tag_date_day) that caused the crash afterwards.
Even after 3 restarts, the db randomly keeps crashing.

Correct, I issued to drop the column and once the job started, after some time, the panic appeared for the first time.

@solongordon 
To reproduce it, you might need a certain db size and workload as all changes were made without any problem on the dev system, but once applied to the production, started to occur.

I hope it's ok that I obscured the column names, I kept the primary and affected column untouched.

```
CREATE TABLE web.video
(
  id SERIAL PRIMARY KEY
);

ALTER TABLE web.video ADD COLUMN col_2 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_2;
ALTER TABLE web.video ADD COLUMN col_3 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_3;
ALTER TABLE web.video ADD COLUMN col_4 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_4;
ALTER TABLE web.video ADD COLUMN col_5 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_5;
ALTER TABLE web.video ADD COLUMN col_6 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_6;
ALTER TABLE web.video ADD COLUMN col_7 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_7;
ALTER TABLE web.video ADD COLUMN col_8 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_8;
ALTER TABLE web.video ADD COLUMN col_9 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_9;
ALTER TABLE web.video ADD COLUMN col_10 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_10;
ALTER TABLE web.video ADD COLUMN col_11 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_11;
ALTER TABLE web.video ADD COLUMN col_12 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_12;
ALTER TABLE web.video ADD COLUMN col_13 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_13;
ALTER TABLE web.video ADD COLUMN col_14 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_14;
ALTER TABLE web.video ADD COLUMN col_15 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_15;
ALTER TABLE web.video ADD COLUMN col_16 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_16;
ALTER TABLE web.video ADD COLUMN col_17 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_17;
ALTER TABLE web.video ADD COLUMN col_18 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_18;
ALTER TABLE web.video ADD COLUMN col_19 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_19;
ALTER TABLE web.video ADD COLUMN col_20 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_20;
ALTER TABLE web.video ADD COLUMN col_21 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_21;
ALTER TABLE web.video ADD COLUMN col_22 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_22;
ALTER TABLE web.video ADD COLUMN col_23 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_23;
ALTER TABLE web.video ADD COLUMN col_24 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_24;
ALTER TABLE web.video ADD COLUMN col_25 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_25;
ALTER TABLE web.video ADD COLUMN col_26 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_26;
ALTER TABLE web.video ADD COLUMN col_27 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_27;
ALTER TABLE web.video ADD COLUMN tag_date_day STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_tag_date_day;
ALTER TABLE web.video ADD COLUMN col_29 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_29;
ALTER TABLE web.video ADD COLUMN col_30 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_30;
ALTER TABLE web.video ADD COLUMN col_31 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_31;
ALTER TABLE web.video ADD COLUMN col_32 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_32;
ALTER TABLE web.video ADD COLUMN col_33 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_33;
ALTER TABLE web.video ADD COLUMN col_34 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_34;
ALTER TABLE web.video ADD COLUMN col_35 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_35;
ALTER TABLE web.video ADD COLUMN col_36 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_36;
ALTER TABLE web.video ADD COLUMN col_37 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_37;
ALTER TABLE web.video ADD COLUMN col_38 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_38;
ALTER TABLE web.video ADD COLUMN col_39 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_39;
ALTER TABLE web.video ADD COLUMN col_40 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_40;
ALTER TABLE web.video ADD COLUMN col_41 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_41;
ALTER TABLE web.video ADD COLUMN col_42 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_42;
ALTER TABLE web.video ADD COLUMN col_43 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_43;
ALTER TABLE web.video ADD COLUMN col_44 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_44;
ALTER TABLE web.video ADD COLUMN col_45 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_45;
ALTER TABLE web.video ADD COLUMN col_46 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_46;
ALTER TABLE web.video ADD COLUMN col_47 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_47;
ALTER TABLE web.video ADD COLUMN col_48 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_48;
ALTER TABLE web.video ADD COLUMN col_49 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_49;
ALTER TABLE web.video ADD COLUMN col_50 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_50;
ALTER TABLE web.video ADD COLUMN col_51 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_51;
ALTER TABLE web.video ADD COLUMN col_52 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_52;
ALTER TABLE web.video ADD COLUMN col_53 INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_col_53;
ALTER TABLE web.video ADD COLUMN col_54 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_54;
ALTER TABLE web.video ADD COLUMN col_55 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_55;
ALTER TABLE web.video ADD COLUMN col_56 STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_col_56;

ALTER TABLE web.video ADD CONSTRAINT col_2_unique UNIQUE (col_2);
ALTER TABLE web.video ADD CONSTRAINT col_6_unique UNIQUE (col_6);
ALTER TABLE web.video ADD CONSTRAINT col_3_col_4_unique UNIQUE (col_3, col_4);

CREATE INDEX col_2_storing_id ON web.video (col_2) STORING (id);
CREATE INDEX col_6_storing_id ON web.video (col_6) STORING (id);
CREATE INDEX col_7_storing_id ON web.video (col_7) STORING (id);
CREATE INDEX col_8_col_3_col_5_desc_storing_id ON web.video (col_8, col_3, col_5 DESC) STORING (id);
CREATE INDEX col_33_col_3_col_5_desc_storing_id ON web.video (col_33, col_3, col_5 DESC) STORING (id);
CREATE INDEX col_36_storing_id ON web.video (col_36) STORING (id);
CREATE INDEX col_3_col_4_storing_id ON web.video (col_3, col_4) STORING (id);
CREATE INDEX col_43_storing_id ON web.video (col_43) STORING (id);
CREATE INDEX col_50_storing_id ON web.video (col_50) STORING (id);
CREATE INDEX col_33_col_34_col_5_desc_storing_id ON web.video (col_33, col_34, col_5 DESC) STORING (id);
CREATE INDEX col_8_col_24_storing_col_10_col_39 ON web.video (col_8, col_24) STORING (col_10, col_39);
CREATE INDEX col_8_col_24_col_25_storing_col_10_col_39 ON web.video (col_8, col_24, col_25) STORING (col_10, col_39);
CREATE INDEX col_8_col_24_col_25_col_26_storing_col_10_col_39 ON web.video (col_8, col_24, col_25, col_26) STORING (col_10, col_39);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_storing_col_10_col_39 ON web.video (col_8, col_24, col_25, col_26, col_27) STORING (col_10, col_39);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_tag_date_day_storing_col_10_col_39 ON web.video (col_8, col_24, col_25, col_26, col_27, tag_date_day) STORING (col_10, col_39);
CREATE INDEX col_8_col_24_col_4_asc_storing_id ON web.video (col_8, col_24, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_4_asc_storing_id ON web.video (col_8, col_24, col_25, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_4_asc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_col_4_asc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_27, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_tag_date_day_col_4_asc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_27, tag_date_day, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_25_col_4_asc_storing_id ON web.video (col_8, col_25, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_4_asc_storing_id ON web.video (col_8, col_25, col_26, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_27_col_4_asc_storing_id ON web.video (col_8, col_25, col_26, col_27, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_27_tag_date_day_col_4_asc_storing_id ON web.video (col_8, col_25, col_26, col_27, tag_date_day, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_26_col_4_asc_storing_id ON web.video (col_8, col_26, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_26_col_27_col_4_asc_storing_id ON web.video (col_8, col_26, col_27, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_26_col_27_tag_date_day_col_4_asc_storing_id ON web.video (col_8, col_26, col_27, tag_date_day, col_4 ASC) STORING (id);
CREATE INDEX col_8_col_24_col_4_desc_storing_id ON web.video (col_8, col_24, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_4_desc_storing_id ON web.video (col_8, col_24, col_25, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_4_desc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_col_4_desc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_27, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_24_col_25_col_26_col_27_tag_date_day_col_4_desc_storing_id ON web.video (col_8, col_24, col_25, col_26, col_27, tag_date_day, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_25_col_4_desc_storing_id ON web.video (col_8, col_25, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_4_desc_storing_id ON web.video (col_8, col_25, col_26, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_27_col_4_desc_storing_id ON web.video (col_8, col_25, col_26, col_27, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_25_col_26_col_27_tag_date_day_col_4_desc_storing_id ON web.video (col_8, col_25, col_26, col_27, tag_date_day, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_26_col_4_desc_storing_id ON web.video (col_8, col_26, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_26_col_27_col_4_desc_storing_id ON web.video (col_8, col_26, col_27, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_26_col_27_tag_date_day_col_4_desc_storing_id ON web.video (col_8, col_26, col_27, tag_date_day, col_4 DESC) STORING (id);
CREATE INDEX col_8_col_29_storing_col_30_col_31 ON web.video (col_8, col_29) STORING (col_30, col_31);
```

**Comment by solongordon** [comment] 2018-07-02 18:24
Great, thanks for the details. Unfortunately no luck reproducing on my end so far. I think someone with more DROP COLUMN familiarity will need to take a look. Attaching my repro script here.
[repro_drop_column_bug.txt](https://github.com/cockroachdb/cockroach/files/2156375/repro_drop_column_bug.txt)

**Comment by jordanlewis** [comment] 2018-09-05 20:33
ping @vivekmenezes, might want to take another look after our latest learnings on the other similar issue.

**Comment by vivekmenezes** [comment] 2018-09-14 15:42
Thanks for reporting this problem. I'm closing this because it's the same as #29374. We think we have a solution for it. Thanks!

**Closed by vivekmenezes** 2018-09-14 15:42 UTC
Labels: A-schema-descriptors, A-sql-execution, C-bug, S-2-temp-unavailability
