### ISSUE TITLE
sql: panic: invalid datum type given: int, expected unknown

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#37565] opened 2019-05-17 07:14 UTC
```
CREATE TABLE tab_orig (
    i8 INT8,
    f8 FLOAT8,
    d  DATE,
    t  TIMESTAMP,
    tz TIMESTAMPTZ,
    n  INTERVAL,
    o  BOOL,
    e  DECIMAL,
    s  STRING,
    b  BYTES,
    u  UUID,
    ip INET,
    j  JSONB
);

INSERT
  INTO tab_orig
SELECT g::INT8,
       g::FLOAT8,
       '2001-01-01'::DATE + g,
       '2001-01-01'::TIMESTAMP + g * '1 day'::INTERVAL,
       '2001-01-01'::TIMESTAMPTZ + g * '1 day'::INTERVAL,
       g * '1 day'::INTERVAL,
       g % 2 = 1,
       g::DECIMAL,
       g::STRING,
       g::STRING::BYTES,
       substring('00000000-0000-0000-0000-' || g::STRING || '00000000000', 1, 36)::UUID,
       '0.0.0.0'::INET + g,
       g::STRING::JSONB
  FROM generate_series(1, 5) AS g;

SELECT tab_110.i8::INT8 + tab_111.ip::INET AS col_255,
       (
          SELECT tab_111.i8 AS col_257
            FROM tab_orig AS tab_114
                 INNER JOIN tab_orig AS tab_115 ON EXISTS(
                                                                SELECT tab_111.i8 AS col_256
                                                                  FROM tab_orig AS tab_116,
                                                                       tab_orig AS tab_117,
                                                                       tab_orig AS tab_118,
                                                                       tab_orig AS tab_119
                                                                 WHERE NOT tab_117.o
                                                                 LIMIT 17::INT8
                                                               ),
                 tab_orig AS tab_120
        ORDER BY tab_114.s DESC
           LIMIT 1::INT8
       ) AS col_258,
       tab_113.f8 AS col_259,
       tab_111.s AS col_260,
       B'0001011111000010110101000110001010' AS col_261,
       B'10' AS col_262,
       tab_112.i8 AS col_263,
       tab_110.s AS col_264
  FROM tab_orig AS tab_110,
       tab_orig AS tab_111
       CROSS JOIN tab_orig AS tab_112
       FULL JOIN tab_orig AS tab_113 ON false;
```

```
panic: invalid datum type given: int, expected unknown [recovered]
        panic: panic while executing 1 statements: SELECT _._::INT8 + _._::INET AS _, (SELECT _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON EXISTS (SELECT _._ AS _ FROM _ AS _, _ AS _, _ AS _, _ AS _ WHERE NOT _._ LIMIT _::INT8), _ AS _ ORDER BY _._ DESC LIMIT _::INT8) AS _, _._ AS _, _._ AS _, _ AS _, _ AS _, _._ AS _, _._ AS _ FROM _ AS _, _ AS _ CROSS JOIN _ AS _ FULL JOIN _ AS _ ON _; caused by invalid datum type given: int, expected unknown

goroutine 383 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001694380, 0x3a3cf40, 0xc001012e80, 0x2dc5540, 0xc0009565e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:719 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001694380, 0x3a3cf40, 0xc001012e80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:431 +0x61
panic(0x2dc5540, 0xc0009565e0)
        /usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xd, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:170 +0x25d
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc000fea000, 0xc0016946d0, 0x3a3e080, 0xc0012dca00, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:186 +0x54e
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x3a3d000, 0xc0013d1590, 0x3a48a80, 0xc000fea000, 0x3a2e340, 0xc00129aa80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc000fea000, 0x3a3d000, 0xc0013d1590)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc000bc05a0, 0x3a3d000, 0xc0013d1590, 0x342c1f0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:626 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000440c80, 0xc00142d380, 0xc0018d0a20, 0xc00137e898, 0xc0011fe580, 0xc001694790, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000440c80, 0x3a3d000, 0xc001278b70, 0xc001694790, 0xc00142d380, 0xc0018d0a20, 0x3a3ec40, 0xc0010167e0, 0xc0011fe580)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:839 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001694380, 0x3a3d000, 0xc001278b70, 0xc0016946d0, 0x3, 0x7fbe51a5ef38, 0xc0017268f0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1112 +0x283
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001694380, 0x3a3d000, 0xc001278b70, 0xc0016946d0, 0x7fbe51a5ef38, 0xc0017268f0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:948 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001694380, 0x3a3d000, 0xc001278b70, 0x3a42c00, 0xc0006cbc00, 0xc0018d456d, 0x53e, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:456 +0xdd0
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001694380, 0x3a3d000, 0xc001278b70, 0x3a42c00, 0xc0006cbc00, 0xc0018d456d, 0x53e, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:102 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001694380, 0x3a3cf40, 0xc001012e80, 0xc000222578, 0x5400, 0x15000, 0xc000222610, 0xc000328140, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1182 +0x21c8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc00058edc0, 0x3a3cf40, 0xc001012e80, 0xc001694380, 0x5400, 0x15000, 0xc000222610, 0xc000328140, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:433 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc00058edc0, 0x3a3cf40, 0xc001012e80, 0xc0010b0000, 0xc0003950e4, 0xc000328140, 0xc001694380, 0x5400, 0x15000, 0xc000222610, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:337 +0xe6
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:320 +0x1080

```

**Comment by jordanlewis** [comment] 2019-05-17 15:18
Thanks @mjibson - this is a duplicate of #37454. I verified that they're both being caused by the same bug (apply join with null output column type) by looking at the `EXPLAIN(verbose,types)` output and noting that an output column had `unknown` type.

**Closed by jordanlewis** 2019-05-17 15:18 UTC
Labels: C-bug, O-sqlsmith

**Comment by mjibson** [comment] 2019-05-17 18:08
My mistake. I forgot I had filed that other bug. This one felt new.
