### ISSUE TITLE
sql:  support `show_trgm` and `%` operator with collated strings

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#86615] opened 2022-08-22 21:13 UTC
`show_trgms` does not support collated strings:

```
defaultdb> SELECT show_trgm('foo' collate "de_DE");
ERROR: unknown signature: show_trgm(collatedstring{de_DE})
SQLSTATE: 42883
```

The `%` operator does not support collated strings:

```
defaultdb> SELECT 'food' collate "de_DE" % 'foo' collate "de_DE";
ERROR: unsupported binary operator: <collatedstring{de_DE}> % <collatedstring{de_DE}>
SQLSTATE: 22023
```

Jira issue: CRDB-18840

**Comment by lnhsingh** [comment] 2023-05-03 18:20
Dupe of #41285, which is already documented in 22.2 Known Limitations.

**Closed** 2023-05-05 19:07 UTC
Labels: C-enhancement, docs-done, docs-known-limitation, C-qa, T-sql-queries
