### ISSUE TITLE
Add Support For hstore Extension

### ISSUE THREAD

**Issue by logston** [cockroachdb/cockroach#51994] opened 2020-07-28 13:43 UTC
**Is your feature request related to a problem? Please describe.**
It would be great to have support for the hstore extension.

**Describe the solution you'd like**
Ability to enable the same behavior that is available in PostgreSQL under the extension of the same name. 

**Describe alternatives you've considered**
None at the moment. I'm simply showing interest in having this feature available. 

**Additional context**

```sql
postgres=# CREATE EXTENSION IF NOT EXISTS hstore;
ERROR:  at or near "EOF": syntax error: unimplemented: this syntax
DETAIL:  source SQL:
CREATE EXTENSION IF NOT EXISTS hstore
                                        ^
HINT:  You have attempted to use a feature that is not yet implemented.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

**Comment by otan** [comment] 2020-07-28 15:02
Hello! This is a duplicate of https://github.com/cockroachdb/cockroach/issues/41284.

Would be great if you could react to the issue as an indicator of popularity.

In the meantime, I will close this one in favour of the original issue.

**Closed by otan** 2020-07-28 15:02 UTC
Labels: C-enhancement, O-community, X-blathers-oncall
