### ISSUE TITLE
Unexpected result when using a record in WHERE filter

### ISSUE THREAD

**Issue by suyZhong** [cockroachdb/cockroach#130649] opened 2024-09-13 10:45 UTC
**Describe the problem**

Consider the test case below. It is unexpected that the third query returns a row `1 NULL`, since the second query shows that the expression should be evaluated to `false`. 

**To Reproduce**

What did you do? Describe in your own words.

Start the CockroachDB instance by using Docker.

```
docker run --name cockroachdb-test -p 10011:26257 -p 10012:8080 cockroachdb/cockroach:latest start-single-node --insecure
```

Execute the below statements through psql:
```sql
DROP DATABASE IF EXISTS test;
CREATE DATABASE test;
USE test;

CREATE  TABLE  t0(c0 INT, c1 INT);
INSERT INTO t0(c0) VALUES (1);

SELECT * FROM t0; -- 1 NULL
SELECT ((t0.c0, t0.c1) IS NOT NULL) FROM t0; -- f
SELECT * FROM t0 WHERE ((t0.c0, t0.c1) IS NOT NULL);
-- Expected: empty
-- Actual: 1 NULL
```

**Expected behavior**
The third query should return an empty result

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 24.2.1
 - Server OS: Docker image
 - Client app: psql and JDBC

**Additional context**
What was the impact?

Jira issue: CRDB-42161

**Comment by mgartner** [comment] 2024-09-17 18:52
This might be a duplicate of #127814.

**Comment by mgartner** [comment] 2024-09-17 23:30
More evidence that it is a duplicate: we get a correct result with the row-by-row engine:

```sql
CREATE  TABLE  t0(c0 INT, c1 INT);

INSERT INTO t0(c0) VALUES (1);

-- This should return no rows.
SELECT * FROM t0 WHERE ((t0.c0, t0.c1) IS NOT NULL);
--   c0 |  c1
-- -----+-------
--    1 | NULL
-- (1 row)

SET vectorize=off;

SELECT * FROM t0 WHERE ((t0.c0, t0.c1) IS NOT NULL);
--   c0 | c1
-- -----+-----
-- (0 rows)
```

**Closed** 2024-09-18 15:39 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries
