### ISSUE TITLE
sql: can mutate `system.zones`

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17251] opened 2017-07-26 23:39 UTC
```
root@:26257/> SELECT * FROM crdb_internal.zones;
pq: relation "crdb_internal.zones" does not exist
root@:26257/> SELECT * FROM system.zones;
+----+----------------------------------------------------------------+
| id |                             config                             |
+----+----------------------------------------------------------------+
|  0 | "\x10\x80\x80@\x18\x80\x80\x80 \"\x04\b\x80\xa3\x05(\x032\x00" |
+----+----------------------------------------------------------------+
(1 row)
root@:26257/> update system.zones set config='OUCH' where id=0;
UPDATE 1
root@:26257/> SELECT * FROM system.zones;
+----+--------+
| id | config |
+----+--------+
|  0 | OUCH   |
+----+--------+
(1 row)
root@:26257/> ^D
[tschottdorf@macts-2 cockroach (decommission-cli)]$ ./cockroach zone ls
Error: connections with user root must use a client certificate
Failed running "zone"
[tschottdorf@macts-2 cockroach (decommission-cli)]$ ./cockroach zone ls --insecure
# Server version: CockroachDB CCL db7becbeb-dirty (darwin amd64, built 2017/07/26 23:07:30, go1.9beta2) (same version as client)
# Cluster ID: fb3ceedf-9e1c-4cc5-829c-b21ecd86ac44
Error: proto: illegal wireType 7
Failed running "zone"
```

I looked into this hoping that I would be able to update the zone configs using sql. @vivekmenezes for triage.

**Comment by a-robinson** [comment] 2017-07-27 03:27
[The comment on `SystemAllowedPrivileges`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/system.go#L139) explains the situation quite well.

**Comment by benesch** [comment] 2017-07-31 04:54
Though it doesn't explain why we've chosen read/write privileges for so many of these tables 😞 . The fact that you can do a

```
UPDATE system.jobs SET payload = 'garbage'
```

is pretty horrifying.

**Comment by benesch** [comment] 2017-12-12 15:28
For posterity: #19277 is tracking the broader problem of "this is allowed for all system tables."

**Comment by mberhault** [comment] 2017-12-12 15:44
This is a duplicate of the broader #19277

**Closed by mberhault** 2017-12-12 15:44 UTC
Labels: bug
