### ISSUE TITLE
sql: flakey TestLogic/local-vec-off/enums

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#79366] opened 2022-04-04 19:26 UTC
**Describe the problem**

Seeing what looks like an unrelated flake on #77337. Running `dev test pkg/sql/logictest -f=TestLogic/local-vec-off/enums -v --show-logs` on that branch passes just fine locally.

```
------- Stdout: -------
=== RUN   TestLogic/local-vec-off/enums
=== PAUSE TestLogic/local-vec-off/enums
=== CONT  TestLogic/local-vec-off/enums
[17:46:01] --- progress: /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/explain_analyze: 24 statements
[17:46:01] --- progress: /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/geospatial: 30 statements
[17:46:02] --- progress: /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/family: 31 statements
[17:46:02] --- progress: /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/exclude_data_from_backup: 13 statements
[17:46:02] --- total progress: 26766 statements
=== CONT  TestLogic/local-vec-off/enums
    logic.go:2930: 
         
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/enums:428: SELECT
          typname, oid, typelem, typarray
        FROM
          pg_type
        WHERE
          typname IN ('collision', '_collision', '__collision', '___collision')
        expected:
            _collision    100139  0       100140
            __collision   100140  100139  0
            collision     100141  0       100142
            ___collision  100142  100141  0
            
        but found (query options: "rowsort" -> ignore the following ordering of rows) :
            _collision    100140  0       100141
            __collision   100141  100140  0
            collision     100142  0       100143
            ___collision  100143  100142  0
[17:46:30] --- done: /go/src/github.com/cockroachdb/cockroach/pkg/sql/logictest/testdata/logic_test/enums with config local-vec-off: 82 tests, 1 failures
```

TC build [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=4785035&buildTypeId=Cockroach_UnitTests). +cc @ajwerner looks like we were here last as of https://github.com/cockroachdb/cockroach/commit/bef34a58b2eeff34b695b57a11a8ba5914c50eea.

Jira issue: CRDB-14757

**Comment by ajwerner** [comment] 2022-04-05 13:27
Duplicate of https://github.com/cockroachdb/cockroach/issues/37751

**Closed by ajwerner** 2022-04-05 13:27 UTC
Labels: C-bug, C-test-failure, T-sql-schema
