### ISSUE TITLE
roachperf: gradual kv95 decline of 10%

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#101299] opened 2023-04-12 12:18 UTC
Our performance on kv95 has declined about 10% since the start of 2023, we should find out why.

https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3%2Fcpu%3D32&tab=gce

<img width="788" alt="Screenshot 2023-04-12 at 14 17 16" src="https://user-images.githubusercontent.com/644420/231454450-aa76549f-234a-4fcc-83ef-68c6d430c34b.png">

Jira issue: CRDB-26897

**Comment by srosenberg** [comment] 2023-04-13 02:20
Just posting current findings, investigation is still ongoing.

Average throughput,

```
{
  "hashResults": {
    "04f7dd3a4d1": "114365",
    "8866ecadd99": "111790",
    "5968c056d4c": "115424",
    "a3d53668ff5": "117643",
    "6f5d89ecc44": "118018",
    "f273aaeaff9": "113424",
    "e62ac1fd32a": "114875",
    "780ade34b11": "117478",
    "ba5ac5bfe9a": "116822",
    "23eea5ecd88": "117762"
  },
  "goodThreshold": "113424",
  "badThreshold": "111790"
}
```

Bisection steps,

```git bisect start
# status: waiting for both good and bad commits
# good: [04f7dd3a4d1d2bf7072783e77e46b1ab360c07eb] cli/demo: display just one HTTP URL when using the server controller
git bisect good 04f7dd3a4d1d2bf7072783e77e46b1ab360c07eb
# status: waiting for bad commit, 1 good commit known
# bad: [8866ecadd99e5f6dc8db9fed5d09bc57cd90b03c] Merge #94950 #95232 #95241
git bisect bad 8866ecadd99e5f6dc8db9fed5d09bc57cd90b03c
# good: [5968c056d4c880846dcb6c16b9e73333e4f829dd] Merge pull request #93871 from nvanbenschoten/nvanbenschoten/lengthPrefixSnappy
git bisect good 5968c056d4c880846dcb6c16b9e73333e4f829dd
# good: [a3d53668ff52c2306f37fcad8e9212ff665ca115] Merge pull request #93068 from Xiang-Gu/implement-add-constraint-foreign-key
git bisect good a3d53668ff52c2306f37fcad8e9212ff665ca115
# good: [6f5d89ecc44033168da27e9306a973c8b0eefeb0] Merge #95020 #95029 #95172
git bisect good 6f5d89ecc44033168da27e9306a973c8b0eefeb0
# good: [f273aaeaff9e3ffd301790bc3e3e36d1b7ca18d6] Merge #93760 #95211
git bisect good f273aaeaff9e3ffd301790bc3e3e36d1b7ca18d6
# good: [e62ac1fd32ae3b4b3ff232013fcb36345e79d671] Merge #93284 #94671 #95162 #95217 #95224
git bisect good e62ac1fd32ae3b4b3ff232013fcb36345e79d671
# good: [780ade34b111fcb50bc3ae78acaf6991c591633c] sql: add statement.sql to EXPLAIN ANALYZE (DEBUG, REDACT)
git bisect good 780ade34b111fcb50bc3ae78acaf6991c591633c
# good: [ba5ac5bfe9a43fc3ffa38756618454859946f505] sem/tree: fix the formatting of backup options
git bisect good ba5ac5bfe9a43fc3ffa38756618454859946f505
# good: [23eea5ecd88783c0d0419af322dd4f9113d9ce25] randident: add some escape sequences
git bisect good 23eea5ecd88783c0d0419af322dd4f9113d9ce25
# first bad commit: [8866ecadd99e5f6dc8db9fed5d09bc57cd90b03c] Merge #94950 #95232 #952
```

First _detected_ regression seems to be in https://github.com/cockroachdb/cockroach/commit/8866ecadd99e5f6dc8db9fed5d09bc57cd90b03c

**Comment by erikgrinaker** [comment] 2023-04-13 08:55
I'm not sure bisection will be effective at diagnosing a gradual decline like this, since each change's contribution may be smaller than the error margin. May want to e.g. compare CPU profiles and traces from December and now.

**Comment by srosenberg** [comment] 2023-04-13 13:04
> I'm not sure bisection will be effective at diagnosing a gradual decline like this,

Indeed, I don't have high hopes for this exercise.

> May also want to e.g. compare CPU profiles and traces from December and now.

Yep, I'll get those after running another instance of the bisect script.

**Comment by renatolabs** [comment] 2023-04-13 15:02
> Oddly this implicates https://github.com/cockroachdb/cockroach/commit/43a25a09f92408accdeb3cfed1eb35e02d375877 which doesn't appear to have anything to do with with perf. regression.

This, coupled with the results of the first bisection (leading to a bors merge commit) indicates that the entire analysis doesn't really make sense and there's no single commit that leads to performance degradation in the range bisected (as we suspected). If there were, we should have converged to a non-merge commit.

Just agreeing with the sentiment that we should look at other sources (such as CPU profiles) instead.

**Comment by sean-** [comment] 2023-04-18 05:39
It is believed it's the expansion of the scope of this mutex in the hot path to prevent racy reads of `w.mu.current.HighestTrackableValue()` when `Record()`'ing histogram data: https://github.com/cockroachdb/cockroach/commit/bdf3f6262e380b867aa8884016eae53d28d074a4#diff-95727896b4622f2e4c21587338f0a2f83589f3c722de76435e7b5077012e303dR76

**Comment by erikgrinaker** [comment] 2023-04-20 14:59
That only explains the recent cliff though. There's been a steady decline since December.

**Comment by srosenberg** [comment] 2023-04-24 16:21
@cockroachdb/sql-sessions

**Comment by srosenberg** [comment] 2023-04-24 16:42
For [95449](https://github.com/cockroachdb/cockroach/pull/95449), CPU profile suggests >= ~2.5% slowdown in `getRegionsForNode`.

After the change,

<img width="1734" alt="3ed2853d39c_recordStatementSummary_plus_getRegionsForNode" src="https://user-images.githubusercontent.com/1616764/234061670-f3a46f88-e845-46f5-b5a9-942fc1fee535.png">

Before the change,

<img width="1730" alt="a3d53668ff5_recordStatementSummary" src="https://user-images.githubusercontent.com/1616764/234061697-ef9923a2-d116-449b-a38e-f5cd25709861.png">

**Comment by srosenberg** [comment] 2023-04-24 16:47
For [96396](https://github.com/cockroachdb/cockroach/pull/96396), CPU profile suggests >= ~1% slowdown in `GetPercentileValues`.

**Comment by srosenberg** [comment] 2023-04-24 17:09
The storage regression is much smaller, accounting for ~0.5% in the CPU profile. However, it could in fact be larger in reality (owing to sampling-based profiling), and it's worth looking into; @cockroachdb/storage

**Comment by erikgrinaker** [comment] 2023-04-24 17:11
Thanks Stan! Can we get #95188 backported to `release-22.2` and `release-23.1` for comparison please?

**Comment by jbowens** [comment] 2023-04-24 17:14
@cockroachdb/storage — @RaduBerinde mind taking a look to see if there's something we can do here: https://github.com/cockroachdb/cockroach/issues/101299#issuecomment-1520537264

**Comment by RaduBerinde** [comment] 2023-04-24 17:24
I will see if there's a way to remove that.. But there is also a separate `runtime.newobject` which is new.. Also, it's surprising to me that a `sync.Pool.Get` is taking longer than a `runtime.newobject`..

**Comment by srosenberg** [comment] 2023-04-24 17:34
> @srosenberg could I get the profiles you were looking at in [#101299 (comment)](https://github.com/cockroachdb/cockroach/issues/101299#issuecomment-1520537264) ?

[a3d53668ff5_cpu_pprof.zip](https://github.com/cockroachdb/cockroach/files/11313077/a3d53668ff5_cpu_pprof.zip)
[3ed2853d39c_cpu_pprof.zip](https://github.com/cockroachdb/cockroach/files/11313078/3ed2853d39c_cpu_pprof.zip)

**Comment by srosenberg** [comment] 2023-04-24 17:35
> Can we get https://github.com/cockroachdb/cockroach/issues/95188 backported to release-22.2 and release-23.1 for comparison please?

It's already in 23.1; 22.2 backport: https://github.com/cockroachdb/cockroach/pull/102161

**Comment by RaduBerinde** [comment] 2023-04-24 17:47
@jbowens the before/after commit range also includes enabling value blocks, and I believe that's where the newobject call is coming from (plus an extra call to `NewReadHandle`). I can try to improve `NewReadHandle` but not the allocation:
https://github.com/cockroachdb/pebble/blob/master/sstable/reader.go#L420

**Comment by knz** [comment] 2023-04-24 18:46
> For https://github.com/cockroachdb/cockroach/pull/95449, CPU profile suggests >= ~2.5% slowdown in getRegionsForNode.

Split into separate issue: #102170

**Comment by sumeerbhola** [comment] 2023-04-25 13:55
> Ack — fyi @sumeerbhola, not sure this alone is significant enough to warrant jumping through hoops to remove the allocation.

@jbowens 
Yes, I think we should wait until the other regressions are dealt with. The idea in the code comment is the only one I have for reducing that allocation. kv95 by default is tiny kv pairs and single kv reads, so I think it is much more sensitive than typical customer workloads.

**Comment by maryliag** [comment] 2023-04-26 19:10
@srosenberg fixes for #102208 and #102170 are now merged to master, 23.1 and 23.1.0 branches.

**Comment by RaduBerinde** [comment] 2023-04-26 19:16
A change to remove the two sync.Pool operations for ReadHandle is merged to 23.1 and 23.1.0.

**Comment by RaduBerinde** [comment] 2023-04-26 19:25
> Is it also in master? I am doing a run off of master now. I'll do the next one from 23.1.0 (and 23.1).

Not yet, the Pebble dep will get bumped by #102295

**Comment by srosenberg** [comment] 2023-04-27 02:45
`UsePreallocatedReadHandle` (https://github.com/cockroachdb/pebble/pull/2481) is now negligible. The two paths in the flamegraph account for ~0.016% and ~0.012% CPU. Very nice!

<img width="1738" alt="UsePreallocatedReadHandle_flame" src="https://user-images.githubusercontent.com/1616764/234746619-ca5ede8a-49b9-4968-ba19-d32e4c5c5d84.png">

**Comment by srosenberg** [comment] 2023-04-27 02:49
`recordStatementSummary` now accounts for ~1.86% CPU (cf., ~1.66% CPU as of [a3d53668ff5](https://github.com/cockroachdb/cockroach/commit/a3d53668ff52c2306f37fcad8e9212ff665ca115)). Very nice!

<img width="1735" alt="recordStatementSummary_flame" src="https://user-images.githubusercontent.com/1616764/234747208-62c051a3-af07-4635-9fb3-e1ea97edb3cb.png">

**Comment by srosenberg** [comment] 2023-04-27 02:58
In master, we have yet another regression, i.e., unrelated to any of the above.

<img width="1817" alt="kv95_a947128ca4c_master_regression" src="https://user-images.githubusercontent.com/1616764/234747684-3279b045-3dfd-4999-9ee4-7e6cc1113546.png">

Split into a new issue: https://github.com/cockroachdb/cockroach/issues/102398

**Comment by srosenberg** [comment] 2023-04-27 03:17
`23.1.0` runs average ~106k,

<img width="1814" alt="kv95_23_1_0" src="https://user-images.githubusercontent.com/1616764/234750454-e43ed7be-619a-4dd4-8067-6a0ba416032a.png">

The dips do appear to be a new artifact. I am not yet able to correlate those with system metrics, but it doesn't appear to be worrisome. I am doing another pair of runs for `23.1` which also show similar dips.

**Comment by srosenberg** [comment] 2023-04-27 03:31
Zooming in on one of the dips, it appears to be caused by the workload generator. The runtime metrics indicate object allocation rate drops during the window of ~5 minutes (it's fairly stable otherwise). We're also seeing a drop in file descriptors, as well as a reduction in packet rate. (The former is puzzling; the file descriptors don't correlate with TCP connections; this workload doesn't read from the filesystem afaik?!)

<img width="1825" alt="kv95_dip_zoom" src="https://user-images.githubusercontent.com/1616764/234752614-cd1c9527-a057-4c6e-bc4f-9d423ac1b029.png">

<img width="1809" alt="runtime_dip_zoom" src="https://user-images.githubusercontent.com/1616764/234752625-71445d61-1807-4744-8a34-5836bd05dc1c.png">

<img width="1830" alt="network_dip_zoom" src="https://user-images.githubusercontent.com/1616764/234752649-616387b5-63a8-493b-95d6-5ccb42a42aa8.png">

**Comment by srosenberg** [comment] 2023-04-27 05:30
`23.1` runs average ~106k,

<img width="1831" alt="kv95_23_1" src="https://user-images.githubusercontent.com/1616764/234767945-0e3f4016-a94a-44a3-8989-b105a303c006.png">

**Comment by srosenberg** [comment] 2023-04-27 05:34
On average, both `23.1.0` and `23.1` are now well within 5% of the baseline ([a3d53668ff5](https://github.com/cockroachdb/cockroach/commit/a3d53668ff52c2306f37fcad8e9212ff665ca115). I am removing release blocker labels and closing this out.

**Closed by srosenberg** 2023-04-27 05:34 UTC
Labels: C-performance, branch-master, GA-blocker, T-testeng, branch-release-23.1, blocks-23.1.0-rc.1
