### ISSUE TITLE
local test cluster unresponsive after ~2000 inserts on 8table/~10indices database

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16168] opened 2017-05-26 16:16 UTC
reported by @TomArbuckle on Gitter. Looks like something unexpected is going on; perhaps we can repro this easily (which is typically easier than trying to remote-debug someone's local cluster).

----

I’m investigating some odd behaviour and was hoping the logs might help me. I’m not sure what to expect in terms of performance from CockroachDB.
Should storing 2 to 4 thousand small blobs of data cause a well specced development machine serious problems? (5 x CockroachDB instances running locally?) The schema involves 8 tables with 10~12 indices (not all of which are in use).

1). Snappy compressed JSON blobs of text. Pre-compression. all but a few are human readable, so bytes up to kB.
2). 1000 blobs are stored first but don’t cause a problem. Once I add more, things start going wrong quickly.
3). Current schema looks as follows. (attachment)

Detailed description:

I’m storing smallish JSON blobs (from another application via a jdbc connection) in CockroachDB. I’m running five instances of CockroachDB on the same machine (macOS). CockroachDB is a compiled version of the most recent version in the github repository. I front CockroachDB with haproxy — and am using prometheus and grafana for logging (in case that matters).
My local application sends regular SQL queries to CockroachDB concerning the DB contents and their update status, every 10 seconds.
Scenario 1. Adding small blobs to an empty DB.
1000 blobs -> OK
2000 blobs -> 2 cores maxed out
3000 blobs -> machine is struggling
more blobs -> unresponsive, and with higher numbers (~8000 IIRC) eventually OOM.
Scenario 2. Adding blobs to an empty DB.
1000 blobs -> OK.
Add 1000 very small (a few bytes in size) blobs -> 2 cores maxing out.
Observe CockroachDB graphs -> number of SQL queries is increasing steadily.
Kill my own app, restart HAProxy. Do not reconnect anything to CockroachDB. Number of SQL Queries stays constant (84 for example). Machine remains busy.
Leave machine for 35 minutes. Number of SQL Queries suddenly drops to zero.

[sql.txt](https://github.com/cockroachdb/cockroach/files/1032433/sql.txt)

**Comment by tschottdorf** [comment] 2017-05-26 16:17
@tomarbuckle could you verify that you're seeing the same problems on a single-node cluster (and if not there, on a three node cluster)? That would help rule out the possibility that your machine is simply overwhelmed by running five nodes at once (there are some more settings that would need to be tweaked to properly handle this use case; for example RocksDB normally allocates a fixed fraction of memory to its block cache).

**Comment by TomArbuckle** [comment] 2017-05-26 16:23
@tschottdorf Will do. Just as info.
cockroach version
Build Tag:    d962689c6
Build Time:   2017/05/26 12:57:00
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.1
C Compiler:   4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
Build SHA-1:  d962689c6ff0d65da0cae21612b92d6ff65cf83b
Build Type:   development

**Comment by TomArbuckle** [comment] 2017-05-26 16:28
![screen shot 2017-05-26 at 13 06 49](https://cloud.githubusercontent.com/assets/25199520/26503334/3a883cb6-4238-11e7-902c-4ef55379b1bd.png)
12.05 Is when the local application was killed.
![screen shot 2017-05-26 at 13 39 56](https://cloud.githubusercontent.com/assets/25199520/26503343/445f7218-4238-11e7-9e5a-54348988ab14.png)
Was surprised by the blip at 12.39, followed by the cessation of the SQL queries.

**Comment by TomArbuckle** [comment] 2017-05-26 16:30
Noted that I rebuilt CockroachDB after this issue so the previous version report is incorrect.

**Comment by TomArbuckle** [comment] 2017-05-26 16:42
[to_github.tar.gz](https://github.com/cockroachdb/cockroach/files/1032494/to_github.tar.gz)

Log files for each node, 1 - 5.

**Comment by tschottdorf** [comment] 2017-05-26 17:02
I recovered the statements run from the command line. Extracted JOIN just because that's a possible candidate. I think I also saw some large-ish deletions in there, though.
[join.txt](https://github.com/cockroachdb/cockroach/files/1032529/join.txt)
[out.txt](https://github.com/cockroachdb/cockroach/files/1032530/out.txt)

@RaduBerinde, anything jumps out?

**Comment by knz** [comment] 2017-05-26 18:41
@TomArbuckle I notice you didn't mention `--cache-size`. Did you use this argument? By default CockroachDB uses 25% of system RAM for caching per node. After 4 nodes, it's expected your system will struggle.

**Comment by tschottdorf** [comment] 2017-05-26 18:53
@knz yup, that might well be it, that's why I asked @TomArbuckle to run this on a single node cluster too.

**Comment by bdarnell** [comment] 2017-05-26 23:20
The logs also show that you're using the flag `--max-sql-memory=3G`, which could allow `JOIN` processing across all nodes to use up to 15GB. You appear to be running this on a macbook pro which could have at most 16GB of RAM. Either of these could in theory push the machine into swap, although the memory usage logged by `runtime.go` (mostly) doesn't support this hypothesis. Go memory usage is stable, CGo usage is growing as expected but is only a few hundred megs on most nodes. However, node 3 is an outlier with 1.4GB in CGo, and its last memory stats are

    I170526 17:33:24.917174 62 server/status/runtime.go:225  [n3] runtime stats: 1.0 GiB RSS, 205 goroutines, 61 MiB/54 MiB/179 MiB GO alloc/idle/total, 1.2 GiB/1.4 GiB CGO alloc/total, 108.20cgo/sec, 0.02/0.01 %(u/s)time, 0.00 %gc (1x)


RSS is lower than CGO alloc, which I think means that the machine is swapping. I would suggest running with `--cache=100MB --max-sql-memory=100MB` and see if that makes things healthier.

**Comment by TomArbuckle** [comment] 2017-05-29 16:30
What I discovered so far...

My memory settings weren't helping -- just making the problem worse. (Thanks @bdarnell for this tip.)

Starting from an empty DB for each test, I tried runs in which I started with 1000 records, then added 1000 more with 1, 3 and 5 nodes with various memory settings (thanks to @tschottdorf), but we can skip them because I've been able to reduce the problem area since then.

I tried a run with one node fronted by HAProxy. I started with 1000 records and tried to add 6,500 small byte-sized records. I was *unable* to reach a total of 7,500 records, adding small records slowly in a separate thread. I don't think this was due to lack of memory. cockroach was CPU bound, maxing out the machine. ~8G of memory was free at the start of the tests. I had to kill it because the machine was thrashing, with number of SQL connections increasing steadily.
[cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26258 --http-port=8081 --background --vmodule=executor=2]

I tried a run with one node to which I connected directly (no HAProxy running). I *was* able to reach a total of 7,500 records. The CPU load was still heavy but the job completed.
[cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26257 --http-port=8081 --background --vmodule=executor=2]

What I noticed was that there were some connections left over after the addition of the data. As these went away, the load on the machine decreased by one unit each time. i.e. Load 3.0 = 3 connections, load 2.0 = 2 connections, load 1.0 = 1 connection.

Here's a screen shot. The sudden drop in SQL Queries (lowest graph) corresponds to the completion of the data addition process. The yellow peak in the middle graph is (I believe) my SQL query to check this.

![screen shot 2017-05-29 at 16 58 13](https://cloud.githubusercontent.com/assets/25199520/26556489/ada00c86-4492-11e7-8b0e-570ed75ac589.png)

and here are corresponding lsof -i -P results

Toms-MBP:db tom$ lsof -i -P | fgrep cock ; date
cockroach 84876  tom    9u  IPv4 0x54152e86ea9973c1      0t0  TCP localhost:26257 (LISTEN)
cockroach 84876  tom   11u  IPv4 0x54152e86e85d53c1      0t0  TCP localhost:8081 (LISTEN)
cockroach 84876  tom   15u  IPv4 0x54152e86d7e041d1      0t0  TCP localhost:63669->localhost:26257 (ESTABLISHED)
cockroach 84876  tom   16u  IPv4 0x54152e86ce5a8ac9      0t0  TCP localhost:26257->localhost:63669 (ESTABLISHED)
cockroach 84876  tom   18u  IPv4 0x54152e86ce57d3c1      0t0  TCP toms-mbp:63670->ec2-52-2-126-154.compute-1.amazonaws.com:443 (CLOSED)
cockroach 84876  tom   19u  IPv4 0x54152e86ce81d3c1      0t0  TCP localhost:8081->localhost:63674 (ESTABLISHED)
cockroach 84876  tom   26u  IPv4 0x54152e86cda211d1      0t0  TCP localhost:26257->localhost:49332 (CLOSE_WAIT)
cockroach 84876  tom   27u  IPv4 0x54152e86cca173c1      0t0  TCP localhost:26257->localhost:49356 (CLOSE_WAIT)
cockroach 84876  tom   33u  IPv4 0x54152e86e8b947a1      0t0  TCP localhost:26257->localhost:49393 (CLOSE_WAIT)
Mon 29 May 2017 16:56:12 IST
Toms-MBP:db tom$ lsof -i -P | fgrep cock ; date
cockroach 84876  tom    9u  IPv4 0x54152e86ea9973c1      0t0  TCP localhost:26257 (LISTEN)
cockroach 84876  tom   11u  IPv4 0x54152e86e85d53c1      0t0  TCP localhost:8081 (LISTEN)
cockroach 84876  tom   15u  IPv4 0x54152e86d7e041d1      0t0  TCP localhost:63669->localhost:26257 (ESTABLISHED)
cockroach 84876  tom   16u  IPv4 0x54152e86ce5a8ac9      0t0  TCP localhost:26257->localhost:63669 (ESTABLISHED)
cockroach 84876  tom   18u  IPv4 0x54152e86ce57d3c1      0t0  TCP toms-mbp:63670->ec2-52-2-126-154.compute-1.amazonaws.com:443 (CLOSED)
cockroach 84876  tom   19u  IPv4 0x54152e86ce81d3c1      0t0  TCP localhost:8081->localhost:63674 (ESTABLISHED)
cockroach 84876  tom   26u  IPv4 0x54152e86cda211d1      0t0  TCP localhost:26257->localhost:49332 (CLOSE_WAIT)
cockroach 84876  tom   27u  IPv4 0x54152e86cca173c1      0t0  TCP localhost:26257->localhost:49356 (CLOSE_WAIT)
Mon 29 May 2017 16:56:30 IST
Toms-MBP:db tom$ 
Toms-MBP:db tom$ lsof -i -P | fgrep cock ; date
cockroach 84876  tom    9u  IPv4 0x54152e86ea9973c1      0t0  TCP localhost:26257 (LISTEN)
cockroach 84876  tom   11u  IPv4 0x54152e86e85d53c1      0t0  TCP localhost:8081 (LISTEN)
cockroach 84876  tom   15u  IPv4 0x54152e86d7e041d1      0t0  TCP localhost:63669->localhost:26257 (ESTABLISHED)
cockroach 84876  tom   16u  IPv4 0x54152e86ce5a8ac9      0t0  TCP localhost:26257->localhost:63669 (ESTABLISHED)
cockroach 84876  tom   18u  IPv4 0x54152e86ce57d3c1      0t0  TCP toms-mbp:63670->ec2-52-2-126-154.compute-1.amazonaws.com:443 (CLOSED)
cockroach 84876  tom   19u  IPv4 0x54152e86ce81d3c1      0t0  TCP localhost:8081->localhost:63674 (ESTABLISHED)
cockroach 84876  tom   20u  IPv4 0x54152e86e8b935b1      0t0  TCP localhost:8081->localhost:49503 (ESTABLISHED)
cockroach 84876  tom   27u  IPv4 0x54152e86cca173c1      0t0  TCP localhost:26257->localhost:49356 (CLOSE_WAIT)
Mon 29 May 2017 16:57:39 IST

Continued in next post ...

**Comment by tschottdorf** [comment] 2017-05-30 01:25
Thanks for the digging @TomArbuckle! I wouldn't be surprised if you were able to eliminate HAProxy as well. Perhaps do a test run where do you only inserts (i.e. no select). If that works, I think you're probably right and that query you're running is problematic and triggers some internal badness.

Approximate schema (recovered from log files - @TomArbuckle, if you have that cleaned up, would appreciate it). @RaduBerinde, any ideas?

```sql
CREATE DATABASE cip
CREATE DATABASE done
CREATE INDEX IF NOT EXISTS k_recordregion2_id ON recordregion2 (id)
CREATE INDEX done
CREATE INDEX k_record_id ON record (id)
CREATE INDEX k_recordlocation_id ON recordlocation3 (id)
CREATE INDEX k_recordnumber3_id ON recordnumber3 (id)
CREATE INDEX k_recordstring4_id ON recordstring4 (id)
CREATE INDEX k_recordupdate_typeid_updatedate ON recordupdate (typeid, updatedate)
CREATE INDEX k_recordupdate_updatedate ON recordupdate (updatedate)
CREATE INDEX k_recorduuid3_id ON recorduuid3 (id)
CREATE TABLE done
CREATE TABLE record (id BYTES NOT NULL, typeid BYTES NOT NULL, data BYTES NOT NULL, CONSTRAINT primary1 PRIMARY KEY (typeid ASC, id ASC), FAMILY primary1 (id, typeid, data))
CREATE TABLE recordlocation3 (id BYTES NOT NULL, typeid BYTES NOT NULL, symbolid INT NOT NULL, value DECIMAL NOT NULL, CONSTRAINT primary2 PRIMARY KEY (symbolid ASC, value ASC, typeid ASC, id ASC), FAMILY primary2 (id, typeid, symbolid, value))
CREATE TABLE recordnumber3 (id BYTES NOT NULL, typeid BYTES NOT NULL, symbolid INT NOT NULL, value DECIMAL NOT NULL, CONSTRAINT primary3 PRIMARY KEY (symbolid ASC, value ASC, typeid ASC, id ASC), FAMILY primary3 (id, typeid, symbolid, value))
CREATE TABLE recordregion2 (id BYTES NOT NULL, typeid BYTES NOT NULL, symbolid INT NOT NULL, value DECIMAL NOT NULL, CONSTRAINT primary4 PRIMARY KEY (symbolid ASC, value ASC, typeid ASC, id ASC), FAMILY primary4 (id, typeid, symbolid, value))
CREATE TABLE recordstring4 (id BYTES NOT NULL, typeid BYTES NOT NULL, symbolid INT NOT NULL, value BYTES NOT NULL, CONSTRAINT primary5 PRIMARY KEY (symbolid ASC, value ASC, typeid ASC, id ASC), FAMILY primary5 (id, typeid, symbolid, value))
CREATE TABLE recordupdate (id BYTES NOT NULL, typeid BYTES NOT NULL, updatedate DECIMAL NOT NULL, CONSTRAINT primary6 PRIMARY KEY (id ASC), FAMILY primary6 (id, typeid, updatedate))
CREATE TABLE recorduuid3 (id BYTES NOT NULL, typeid BYTES NOT NULL, symbolid INT NOT NULL, value BYTES NOT NULL, CONSTRAINT primary7 PRIMARY KEY (symbolid ASC, value ASC, typeid ASC, id ASC), FAMILY primary7 (id, typeid, symbolid, value))
CREATE TABLE symbol (symbolid SERIAL NOT NULL, value BYTES NOT NULL, CONSTRAINT primary8 PRIMARY KEY (symbolid ASC), FAMILY primary8 (symbolid, value))
CREATE UNIQUE INDEX k_symbol_value ON symbol (value)
```

**Comment by RaduBerinde** [comment] 2017-05-30 03:17
The joins in join.txt involve window functions and they are 7-way joins, 4 of which are left outer joins. They wouldn't run under distsql, and I believe we don't propagate filters as well as we could for outer joins, @knz knows best.

In any case, to be sure what's going on we need to look at long-running queries; enabling tracing would help.

**Comment by TomArbuckle** [comment] 2017-05-30 09:24
Info.

- Schema is attachment in problem report (sql.txt). I do "CREATE DATABASE CIP;" manually in a cockroach sql node (which I try to remember to close) before the application starts so it's not included.
- @tschottdorf Yes, HAProxy can be eliminated to reduce the problem. (My suspicion is that my application uses 10 threads for calculations (including connections), the jdbc driver can have more "maxActive=32", for example, and that HAProxy allows more simultaneous connections.) So using HAProxy is not necessary to see the problem, just one CockroachDB node.
- @RaduBerinde OK. Will be looking at long running queries today (and have noted the need for tracing).

**Comment by RaduBerinde** [comment] 2017-05-30 12:11
@TomArbuckle to enable tracing, set `COCKROACH_ENABLE_TRACING=1` env var on each host. Recent traces can be seen at `127.0.0.1:8080/debug` (`requests` link).
If accessing `/debug` from another machine, a cluster setting needs to be changed through SQL: `SET CLUSTER SETTING server.remote_debugging.mode = 'any';`

**Comment by TomArbuckle** [comment] 2017-05-30 12:17
@RaduBerinde Got it. Thanks for this. Continuing ...

**Comment by knz** [comment] 2017-05-30 14:59
Yes these queries can hardly be optimized automatically for now. We're probably going to look at outer joins some time this year but the combined stack of 7 joins together with window functions will only become fast and lean (especially in memory usage) much later, next year at the earliest. I think it may be worthwhile to brainstorm a little about how to rewrite them. We're not technically offering SQL consultancy but if you were to provide an overview of what these expensive status queries are doing, we could have a look.

**Comment by TomArbuckle** [comment] 2017-05-30 16:43
@knz Thanks for going through the data so far -- and for offering to take a look.

My understanding is that this application gathers statistics on itself regularly, as well as doing housekeeping jobs. Multiple users can be entering data independently and having a summary of that data can be useful. For example, 'When was any instance of a particular type of data last updated?' or 'How many instances of a particular type have been referenced in the past [timeperiod]?' Hence, every 10 seconds or so, some thread is gathering statistics on the data present in the DB.

To continue the example, (here's a query that timed out in my tests today),

SELECT MAX(r.updatedate)
FROM recordupdate r
LEFT OUTER JOIN recordnumber3 i0 ON i0.id = r.id AND i0.typeid = r.typeid AND i0.symbolid IN (-1)
WHERE 1 = 1
AND r.typeid IN (to_uuid('0000015c-59d5-da9e-affc-ffddd0e90006')))

translates as

"When was the last thing of type 0000015c-59d5-da9e-affc-ffddd0e90006 updated (without caring what its subtype is = io.symbolid)?" [id, typeid are UUIDs and r.updatedate is millis since the epoch. symbolid is a SERIAL.]

**Comment by knz** [comment] 2017-05-30 16:52
Can you explain here what the join on `i0` (`recordnumber3`) is achieving? It does not seem like you need this to proceed. What would be wrong with

```sql
SELECT MAX(r.updatedate)
FROM recordupdate r
WHERE r.typeid = to_uuid('0000015c-59d5-da9e-affc-ffddd0e90006')
```

**Comment by TomArbuckle** [comment] 2017-05-30 17:12
Yes. I agree.

The system is generating these automated queries -- and, in this case, the SQL is more complex than necessary. However, for other queries not shown, I believe this level of complexity is necessary. It's just that the code template used to generate the queries doesn't change. 

Another way to say the same thing, if I were doing the queries manually, I would use what you suggest. I don't get that option, though.

**Comment by TomArbuckle** [comment] 2017-05-31 12:56
@knz I was thinking about your question concerning these queries.

When I was working to get this application running with cockroachdb, I
turned off some optional functionality. This allowed me to omit some
tables, views (with complicated definitions) and indexes not present in
the current reported schema.

Therefore, without looking in detail into the application code, I
believe what we're seeing here are vestigial remnants -- templated
stub hooks -- that would be querying these missing tables, views and
indexes.

That doesn't help with the issue at hand -- but I'd say that it's a
better explanation of the form of these JOIN expressions.

**Comment by TomArbuckle** [comment] 2017-05-31 13:02
The procedure for the tests.

- Start CockroachDB (empty data directory).
- Create a DB: cockroach sql --insecure -e "CREATE DATABASE CIP;"
- Verify creation: cockroach sql --insecure -e "SHOW DATABASES;"

- Start the application to add around 1000 records, possibly checking to see how many were present using SELECT calls.

- Add 9000 small records more in a single thread and observe the system. The records contain Snappy compressed
String("AAA VVVEEERRRYYY LLLOOONNNGGG NAME " + i), UUIDs and metadata
for i=0 .. 8999.  [During this time, the status update thread runs every 10
seconds or so, adding these LEFT OUTER JOIN queries. Adding records
runs for several minutes.]

- When/if addition of the records completes, kill the application and
observe CockroachDB.

- Investigate any CockroachDB busy threads left over after closing the application.
- Quit cockroach, when it becomes quiescent.
- From time to time, generate profiling stack traces.

Tests are carried out on a 16GB, 8 core Mac running macOS
10.12.5. Approximately 8GB of memory is free before starting to run
the tests.

**Comment by TomArbuckle** [comment] 2017-05-31 13:12
Test without HAProxy.

$ cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26257 --http-port=8081 --background --vmodule=executor=2

Tracing is on. [export COCKROACH_ENABLE_TRACING=1 ]

![screen shot 2017-05-31 at 11 40 03](https://cloud.githubusercontent.com/assets/25199520/26633060/110b2ddc-460a-11e7-8916-035d94ad5942.png)

Screenshot of start, adding 1000 records, wait, then a few minutes of adding the remaining 9000 records.

**Comment by TomArbuckle** [comment] 2017-05-31 13:12
![screen shot 2017-05-31 at 12 06 18](https://cloud.githubusercontent.com/assets/25199520/26633237/a3c2ef2a-460a-11e7-95d1-5743bc7ee049.png)

Screenshot shows end of adding data (11.01), killing of application (11.04) and thread continuing afterwards. lsof shows connections in CLOSE WAIT state.

**Comment by TomArbuckle** [comment] 2017-05-31 13:17
Max load ws around 500% (5 cores).
Max memory requirement was around 1.61Gb. (No memory pressure on this machine.)
Total time to add 9000 records around 25 minutes.
No reports of timeouts (with direct connection, no HAProxy).

Continued ...

**Comment by TomArbuckle** [comment] 2017-05-31 13:20
Test with HAProxy

HAProxy is started to front a one node cluster and connections go through HAProxy to CockroachDB.

cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26258 --http-port=8081 --background --vmodule=executor=2

Tracing is on.

![screen shot 2017-05-31 at 12 36 20](https://cloud.githubusercontent.com/assets/25199520/26633517/952c1f58-460b-11e7-8cce-98282c5f48a2.png)

At this point, load is around 400% and memory requirement is about 350MB.

**Comment by TomArbuckle** [comment] 2017-05-31 13:25
![screen shot 2017-05-31 at 12 53 27](https://cloud.githubusercontent.com/assets/25199520/26633765/5cfb0d6e-460c-11e7-9a5f-36d05540d654.png)

Here the application has had to be killed. Load is approaching 11.00 and all 8 cores are maxed out. Memory requirement remains around 1.6GB. lsof shows CLOSE WAIT or CLOSE connections piling up.

It eventually takes six minutes for CockroachDB to become quiescent.

Total test time (without adding all records) around 30 minutes.

**Comment by TomArbuckle** [comment] 2017-05-31 13:43
I believe there are two overlapping issues here.

1. as already identified, how things like LEFT OUTER JOIN are to be handled;
2. what happens with mid-calculation connections being closed, likely easier to solve.

Anyway, over to you guys ...

**Comment by knz** [comment] 2017-06-01 10:59
I filed point 2 as #16262

**Comment by cuongdo** [comment] 2017-08-22 20:08
@knz could you please triage?

**Comment by knz** [comment] 2017-08-23 11:28
@TomArbuckle we have equipped CockroachDB 1.1 with the ability to inspect running queries from another session. Could you download the latest v1.1-alpha binary, reproduce the problem, then issue `SHOW CLUSTER QUERIES` from another shell when the problem occurs? I'd like to see in which state the queries are at that moment.

Then if you do see the queries there, if you issue the statement `CANCEL QUERY ...`, does the query disappear? If so, does the cluster recover if you issue `CANCEL QUERY ...` on many of the queries?

**Comment by TomArbuckle** [comment] 2017-08-25 14:08
Repeating the two experiments using the procedure listed above, namely a single CockroachDB node with 1) a direct connection and 2) a connection via HAProxy...

CockroachDB exhibits the previously reported behaviour.

- Without HAProxy, adding 9000 records (to an initial 1000) completes in around 40 minutes.
- With HAProxy, after adding around 3,500 records (to an initial 1000), cockroachDB is unable to make further progress as the number of connections grows and LEFT JOIN status update queries swamp the DB.
- In both cases, LEFT JOIN status queries continue after the driving application is terminated.

Changes
- macOS updated (10.12.6)
- HAproxy updated (1.7.9)

CockroachDB (not quite the 1.1-alpha but a recent build of the GitHub repo):

$ cockroach version
Build Tag:    13ab4fb2c
Build Time:   2017/08/23 13:07:14
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
Build SHA-1:  13ab4fb2c0a4413be9cff6370d5958e7199ed15f
Build Type:   development

The same machine (a recent MacBook Pro, 16Gb RAM) was used as in the previous tests.

There was always at least 1Gb of memory free (= no memory pressure).

**Comment by TomArbuckle** [comment] 2017-08-25 14:12
Experiment 1 (No HAProxy = direct connection).

![screen shot 2017-08-25 at 11 31 46](https://user-images.githubusercontent.com/25199520/29717532-6628daae-89a7-11e7-9f2e-7cb52de2d9be.png)

Data (includes SHOW CLUSTER QUERIES; text)
[Fri25_NoProxy.tar.gz](https://github.com/cockroachdb/cockroach/files/1252056/Fri25_NoProxy.tar.gz)

**Comment by TomArbuckle** [comment] 2017-08-25 14:16
Experiment 2 (HAProxy but still only one node)

![screen shot 2017-08-25 at 12 55 45](https://user-images.githubusercontent.com/25199520/29717677-ea5ad1f6-89a7-11e7-9f93-3bb734c435b0.png)

Data (includes SHOW CLUSTER QUERIES; text)
[Fri25_HAProxy.tar.gz](https://github.com/cockroachdb/cockroach/files/1252066/Fri25_HAProxy.tar.gz)

**Comment by TomArbuckle** [comment] 2017-08-25 14:23
Experiment 1 (IIRC, Max memory was around 830MB)
cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26258 --http-port=8081 --background --vmodule=executor=2

Experiment 2 via HAProxy. (IIRC, Max memory was around 2.3GB)
cockroach start --insecure --host=localhost --store=node1 --max-sql-memory=1G --cache=1G --port=26257 --http-port=8081 --background --vmodule=executor=2

For both, COCKROACH_ENABLE_TRACING=1

**Comment by TomArbuckle** [comment] 2017-08-25 14:25
Continuing with CANCEL QUERY tests, which I guess are also part of #16262.

**Comment by TomArbuckle** [comment] 2017-08-28 15:43
Cancel Query Tests -- One Node, No Proxy

Continuing with the above tests, if the client application is connected,
at least some queries can be cancelled. (The client reports their context as being
cancelled). Cancellation takes some time. Even after issuing a
cancellation request, a query can move from preparing to
executing. A cancelled query can run for tens of seconds before
disappearing. It's difficult to know (from cockroach CLI) whether a query
has been cancelled or has just run to completion. Missing
queries (the requested id is not matched) **are** reported when the query
cancellation is issued.

If the driving application is quit while queries are in progress, they
appear to run to completion regardless of how many cancel requests are
issued. In other words, once a driving application has gone away, it
doesn't seem to be possible to cancel any running queries it leaves
behind.

**Comment by TomArbuckle** [comment] 2017-08-28 15:50
Cancel Query Tests -- One Node via HAProxy

Fill the DB with around 10,000 records (without a proxy) then stop and reconnect via a proxy. Leave the client application running for a while. The number of CockroachDB connections increases (stopped at ~65 measured using lsof). The number of HAProxy connections remains relatively stable in mid-teens.

Orphaned LEFT JOIN queries build up (issued by the client as status update checks).

Was going to see if they could be cancelled but hit the following error.

* ERROR: [client=127.0.0.1:50083,user=root,n1] a SQL panic has occurred!
* ERROR: [n1] a panic has occurred!
* ERROR: [n1] Reported as error ee72b8681eca43129eeebdb8ceefcc7f

Stopping there for just now.

**Comment by TomArbuckle** [comment] 2017-08-29 11:30
Cancel Query Tests -- One Node via HAProxy

Continue test via HAProxy using same DB. Leave the setup (client + DB) running for a while.

Number of CockroachDB connections increases (~85 at present) while number of HAProxy connections remains mid-teens (as measured using lsof).

Try to cancel all running queries using cockroach sql shell.

Very few are cancelled. (Notch in top plot at around 11.05.) Most continue. Cluster (one node) remains unusable.

![screen shot 2017-08-29 at 12 14 13](https://user-images.githubusercontent.com/25199520/29818314-aeaeb6b8-8cb3-11e7-961a-97b476a5ad4c.png)

End of testing.

**Comment by knz** [comment] 2017-08-30 14:39
The SELECT query is meant to narrow down the join to a single row by performing a UUID equality lookup (`r.typeid IN (to_uuid('0000015c-59d5-da9e-affc-ffddd0e90006')))`). However the way this query was written was not optimized by CockroachDB  -- in turn causing each query to result in a full table scan. As the table grows with more records, each SELECT would be longer and longer, causing the latency to increase and the QPS to decrease.

@TomArbuckle I added an optimization for this left join in #18017 yesteday. can you check with this patch applied (i.e. compile from source from a recent checkout) what is the result of EXPLAIN with that query on your schema?

**Comment by TomArbuckle** [comment] 2017-08-30 15:57
Very nice. Some preliminary EXPLAIN results.

cockroach version
Build Tag:    20bd2bc2d
Build Time:   2017/08/30 14:55:11
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)
Build SHA-1:  20bd2bc2d1854d328b8ceac74fe22609b159feb3
Build Type:   development

Quick test: one node connected via HAProxy as above

EXPLAIN SELECT max(r.updatedate) FROM recordupdate AS r WHERE (1 = 1) AND ((r.id IS NOT NULL) AND (r.id IN (to_uuid('ffffffff-ffff-ffff-ffff-ffffffffffff'))));
+-------+---------+-------+----------------------------------------+
| Level |  Type   | Field |              Description               |
+-------+---------+-------+----------------------------------------+
|     0 | group   |       |                                        |
|     1 | render  |       |                                        |
|     2 | revscan |       |                                        |
|     2 |         | table | recordupdate@k_recordupdate_updatedate |
|     2 |         | spans | /#-                                    |
+-------+---------+-------+----------------------------------------+
(5 rows)

Time: 7.009296ms

Here's another query:

EXPLAIN SELECT max(r.updatedate) FROM recordupdate AS r LEFT JOIN recordnumber3 AS i0 ON ((i0.id = r.id) AND (i0.typeid = r.typeid)) AND (i0.symbolid IN (-1)) WHERE (1 = 1) AND (r.typeid IN (to_uuid('0000015e-27fc-da6a-a15e-bffc3da20006')));
+-------+--------+----------+-----------------------------------------------------------------------------------------------------------------+
| Level |  Type  |  Field   |                                                   Description                                                   |
+-------+--------+----------+-----------------------------------------------------------------------------------------------------------------+
|     0 | group  |          |                                                                                                                 |
|     1 | render |          |                                                                                                                 |
|     2 | join   |          |                                                                                                                 |
|     2 |        | type     | left outer                                                                                                      |
|     2 |        | equality | (id, typeid) = (id, typeid)                                                                                     |
|     3 | scan   |          |                                                                                                                 |
|     3 |        | table    | recordupdate@k_recordupdate_typeid_updatedate                                                                   |
|     3 |        | spans    | /"\x00\x00\x01^'\xfc\xdaj\xa1^\xbf\xfc=\xa2\x00\x06"/#-/"\x00\x00\x01^'\xfc\xdaj\xa1^\xbf\xfc=\xa2\x00\x06\x00" |
|     3 | scan   |          |                                                                                                                 |
|     3 |        | table    | recordnumber3@primary3                                                                                          |
|     3 |        | spans    | /-1-/0                                                                                                          |
+-------+--------+----------+-----------------------------------------------------------------------------------------------------------------+
(11 rows)

Time: 2.008831ms

**Comment by knz** [comment] 2017-08-30 15:59
So this clearly shows that these queries will perform orders of magnitude faster than previously. I'd be curious if the problem you were observing earlier still occurs now.

**Comment by bdarnell** [comment] 2017-08-30 16:44
Also, what is your haproxy configuration? There may be some things we can adjust there that will keep it from leaking connections the next time you find a query that ends up being very slow.

**Comment by TomArbuckle** [comment] 2017-08-31 08:21
@bdarnell haproxy.cfg

```
global
  maxconn 4096
  daemon

defaults
    mode                tcp
    timeout connect     10s
    timeout client      1m
    timeout server      1m

listen psql
    bind :26257
    mode tcp
    balance leastconn
    server cockroach1 localhost:26258 check
    server cockroach2 localhost:26259 check
    server cockroach3 localhost:26260 check
    server cockroach4 localhost:26261 check
    server cockroach5 localhost:26262 check
```

Note that only node cockroach1 is being used for these tests.

**Comment by TomArbuckle** [comment] 2017-08-31 14:28
@knz Retested version 20bd2bc via HAProxy connection.

Client + CockroachDB left running for a few hours in the background.

Mid-way, increased number of records from 10k to 30k and then beyond.

![screen shot 2017-08-31 at 15 12 35](https://user-images.githubusercontent.com/25199520/29928038-e1f7e0fa-8e5f-11e7-9b61-45cb4ba39427.png)

Looks good.

**Comment by knz** [comment] 2017-08-31 14:51
Do you reckon we satisfactorily addressed the primary issue you reported initially?

**Comment by TomArbuckle** [comment] 2017-08-31 15:21
Yes.

(Currently at ~90k inserts and still going (with a single node via HAProxy).)

**Comment by knz** [comment] 2017-08-31 15:26
Ok then we'll let you test this a bit further so you can confirm there is nothing unwieldy popping up a bit further. Then in a few days if we don't hear back from you I'll close this issue. I hope this is acceptable to you. 

In any case, **thank you** for pushing us to look into this. This problem definitely needed some love.

**Comment by bdarnell** [comment] 2017-08-31 22:30
I found a couple of haproxy options that might make a difference here: `option abortonclose` and `option server-fin 1s` (from [this thread](http://thread.gmane.org/gmane.comp.web.haproxy/21393)). These options are supposed to make haproxy more aggressive about forwarding connection-close events from the client to the backend, which might address the problem where it's accumulating lots of connections with haproxy but not with direct connections (I'm not completely clear on this, though).

**Comment by knz** [comment] 2017-09-15 11:22
Thank you again!

**Closed by knz** 2017-09-15 11:22 UTC
Labels: community-questions
