### ISSUE TITLE
ui: localities debug page scrolls to top periodically

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#23411] opened 2018-03-05 20:42 UTC
The `/#/reports/localities` debug page periodically scrolls to top. I'm guessing that the page is refreshing, but the content changes very infrequently so this is somewhat annoying. And even if the contents have changed, scrolling to the top of the page on refresh is irritating.

**Comment by a-robinson** [comment] 2018-03-05 20:45
Also see https://github.com/cockroachdb/cockroach/issues/21700, which is probably caused by the same mechanism

**Comment by couchand** [comment] 2018-03-05 20:53
We can apply a patch here, but it's worth noting that a similar problem affects many pages on the admin UI, and it would be really nice to fix it more generally (but probably out of scope for 2.0).  But we can throw in a patch for this instance of it.

**Comment by vilterp** [comment] 2018-03-05 20:54
Same fix as https://github.com/cockroachdb/cockroach/pull/22527, I think. Need to still render the UI while we're refreshing its data.

I agree that we need to refactor this into a shared pattern of some kind.

**Comment by dianasaur323** [comment] 2018-03-05 21:29
If this is a refactor you all are about and want to consider prioritizing, perhaps we should create an issue and also add it to airtable? cc @piyush-singh

**Comment by vilterp** [comment] 2018-03-05 21:37
Yeah maybe. @mrtracy also discusses some possible network issues in #18741. Unclear thus far what the right abstraction here is, but we'll def be thinking about it.

**Comment by mrtracy** [comment] 2018-03-05 21:53
However, in this case it appears to be using the wrong criteria to determine when to display a "loading" message instead of content.  In general, pages should only display "loading" message instead of content if there is no data.  However, both of these pages (localities and the raft page) display the loading message whenever new data is being fetched, instead of just displaying the old data.  This causes the entire page content to quickly "flash", resetting the scroll position in the process.  I have a fix in progress.

**Comment by dianasaur323** [comment] 2018-03-05 21:56
yay, baller!

**Closed** 2018-03-05 23:57 UTC
Labels: ux-surprise
