### ISSUE TITLE
Constrained scan of date index with timestamp range predicate

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#93228] opened 2022-12-07 23:29 UTC
**Is your feature request related to a problem? Please describe.**
Given a table t: 
```
create table t (a date primary key);
```
A range query with timestamp predicate does not use the index:
```
explain select * from t where a < now();
                        info
----------------------------------------------------
  distribution: local
  vectorized: true

  • filter
  │ filter: a < '2022-12-08 00:14:09.611943+01:00'
  │
  └── • scan
        missing stats
        table: t@t_pkey
        spans: FULL SCAN
```
**Describe the solution you'd like**
The optimizer should derive a new predicate here, something like `a < now()::date + interval '1' day`, to avoid a full scan of all rows. Depending on the implementation, the original predicate might still have to be evaluated (for example, to handle when the timestamp being compared has no hours, minutes, seconds, or microseconds). Builtin functions like now() or constants could be supported, but UDFs which could return the maximum possible timestamp might error out if adding 1 day to their return value, so maybe wouldn't be supported.

**Describe alternatives you've considered**
None

**Additional context**
Opened for support issue: https://github.com/cockroachlabs/support/issues/1942

Jira issue: CRDB-22225

**Comment by mgartner** [comment] 2024-04-23 22:12
Closing as a duplicate of #21143.

**Closed by mgartner** 2024-04-23 22:12 UTC
Labels: C-enhancement, T-sql-queries, E-quick-win
