### ISSUE TITLE
cdc: TestChangefeedHandlesDrainingNodes flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#95611] opened 2023-01-20 19:03 UTC
See CI flake here: [TestChangefeedHandlesDrainingNodes](https://teamcity.cockroachdb.com/viewLog.html?buildId=8390616&buildTypeId=Cockroach_BazelEssentialCi#testNameId8657985868505175386)

Jira issue: CRDB-23616

Epic CRDB-11732

**Comment by jayshrivastava** [comment] 2023-02-22 18:56
Dupe of https://github.com/cockroachdb/cockroach/issues/97233

**Closed by jayshrivastava** 2023-02-22 18:56 UTC
Labels: C-test-failure, A-cdc, T-cdc
