### ISSUE TITLE
sql: TestLogic_mixed_version_role_members_user_ids flaked on 23.1

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#106204] opened 2023-07-05 18:57 UTC
See flake here https://teamcity.cockroachdb.com/viewLog.html?buildId=10790736&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-29446

**Comment by rafiss** [comment] 2023-07-06 17:50
Dupe of https://github.com/cockroachdb/cockroach/issues/105946

**Closed by rafiss** 2023-07-06 17:50 UTC
Labels: C-test-failure, T-sql-foundations
