### ISSUE TITLE
sql: Return pgerror syntax error code when appropriate

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#9290] opened 2016-09-12 13:59 UTC
We haven't been returning the postgres error code ("42601") for any errors up to this point. We've started using it in #9278, but should go through the other errors being returned by our other planNode constructors and returning it where appropriate.

**Comment by andreimatei** [comment] 2016-09-12 15:45
dupe of #5329

**Closed by andreimatei** 2016-09-12 15:45 UTC
Labels: cleanup, enhancement
