### ISSUE TITLE
Cannot start docker local cluster with v20.2.2 on MacOS Big Sur

### ISSUE THREAD

**Issue by z0mb1ek** [cockroachdb/cockroach#57192] opened 2020-11-27 12:13 UTC
Hi, trying to start cluster on MacOS Big Sur with version 20.2.2 and when I make 
`docker exec -it roach1 ./cockroach init --insecure`

2 and 3 nodes go down with fatal error:
```
I201127 12:04:19.684508 84 cli/start.go:680 ⋮ node startup completed:
CockroachDB node starting at 2020-11-27 12:04:19.6842962 +0000 UTC (took 18.5s)
build:               CCL v20.2.2 @ 2020/11/25 14:45:44 (go1.13.14)
webui:               ‹http://roach2:8080›
sql:                 ‹postgresql://root@roach2:26257?sslmode=disable›
RPC client flags:    ‹/cockroach/cockroach <client cmd> --host=roach2:26257 --insecure›
logs:                ‹/cockroach/cockroach-data/logs›
temp dir:            ‹/cockroach/cockroach-data/cockroach-temp218036500›
external I/O path:   ‹/cockroach/cockroach-data/extern›
store[0]:            ‹path=/cockroach/cockroach-data›
storage engine:      pebble
status:              initialized new node, joined pre-existing cluster
clusterID:           ‹cf9120e1-c7fe-4b02-9298-1d9aff99ac8d›
nodeID:              3
I201127 12:04:19.685120 550 jobs/job_scheduler.go:346 ⋮ [n3] waiting 3m0s before scheduled jobs daemon start
I201127 12:04:19.724125 567 sql/sqlliveness/slstorage/slstorage.go:342 ⋮ [n3] inserted sqlliveness session ‹3f672fd5b9ad43da875bb1adbfd73594›
I201127 12:04:19.724198 567 sql/sqlliveness/slinstance/slinstance.go:143 ⋮ [n3] created new SQL liveness session ‹3f672fd5b9ad43da875bb1adbfd73594›
I201127 12:04:19.745147 565 sql/event_log.go:146 ⋮ [n3] Event: ‹"node_join"›, target: 3, info: ‹{Descriptor:{NodeID:3 Address:roach2:26257 Attrs: Locality: ServerVersion:20.2 BuildTag:v20.2.2 StartedAt:1606478659464495500 LocalityAddress:[] ClusterName: SQLAddress:roach2:26257} ClusterID:cf9120e1-c7fe-4b02-9298-1d9aff99ac8d StartedAt:1606478659464495500 LastUp:1606478659464495500}›
I201127 12:04:19.760676 551 server/server_update.go:55 ⋮ [n3] no need to upgrade, cluster already at the newest version
I201127 12:04:19.904502 589 kv/kvserver/replica_raftstorage.go:798 ⋮ [n3,s3,r27/3:{-}] applying LEARNER snapshot [id=‹1e4ad4bb› index=21]
E201127 12:04:19.996087 644 util/log/crash_reporting.go:321 ⋮ [n3] Queued as error ‹4bb68211fd5049b0a5f9009d91da9558›
I201127 12:04:20.006813 589 kv/kvserver/replica_raftstorage.go:819 ⋮ [n3,s3,r27/3:‹/{NamespaceTab…-Table/32}›] applied LEARNER snapshot [‹total=102ms›‹›‹ingestion=4@92ms›id=‹1e4ad4bb› index=21]
I201127 12:04:20.276592 606 kv/kvserver/replica_raftstorage.go:798 ⋮ [n3,s3,r35/3:{-}] applying LEARNER snapshot [id=‹41c95150› index=32]
I201127 12:04:20.370090 606 kv/kvserver/replica_raftstorage.go:819 ⋮ [n3,s3,r35/3:‹/{Table/39-Max}›] applied LEARNER snapshot [‹total=93ms›‹›‹ingestion=4@80ms›id=‹41c95150› index=32]
I201127 12:04:20.599710 680 kv/kvserver/replica_raftstorage.go:798 ⋮ [n3,s3,r8/3:{-}] applying LEARNER snapshot [id=‹00aa8a9c› index=42]
W201127 12:04:20.642766 654 vendor/google.golang.org/grpc/internal/channelz/logging.go:73 ⋮ ‹grpc: addrConn.createTransport failed to connect to {roach3:26257  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...›
W201127 12:04:20.643078 529 kv/kvserver/raft_transport.go:637 ⋮ [n3] while processing outgoing Raft queue to node 2: ‹rpc error: code = Canceled desc = grpc: the client connection is closing›:
W201127 12:04:20.644193 647 kv/kvserver/raft_transport.go:637 ⋮ [n3] while processing outgoing Raft queue to node 2: ‹rpc error: code = Unavailable desc = transport is closing›:
F201127 12:04:20.691140 644 vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:145 ⋮ [n3] ‹000004.sst›:
open ‹/cockroach/cockroach-data/000004.sst›: no such file or directory
directory contains 20 files, 9 unknown, 5 tables, 2 logs
goroutine 644 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x964b900, 0x78ea26, 0xc001bb4bf8, 0x78ea26)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/get_stacks.go:25 +0xb8
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0x964ab00, 0x4, 0x164b5bd495bda05c, 0x284, 0x88e818e, 0x3f, 0x91, 0xc000311900, 0x95, 0xc00117cc88, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:241 +0xa02
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x62e01e0, 0xc000586ea0, 0x4, 0x3, 0x52e81b7, 0x42, 0xc001233440, 0x6, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:52 +0x1ac
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x62e01e0, 0xc000586ea0, 0x2, 0xc000000004, 0x52e81b7, 0x42, 0xc001233440, 0x6, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:44 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:183
github.com/cockroachdb/cockroach/pkg/storage.pebbleLogger.Fatalf(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:369
github.com/cockroachdb/pebble/internal/base.MustExist(0x64591a0, 0xc0011223c0, 0xc001e936b0, 0x24, 0x7f2a96ff7bc0, 0xc001122420, 0x623ed40, 0xc001f04150)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:145 +0x392
github.com/cockroachdb/pebble.(*tableCache).withReader(0xc000513598, 0xc001a0f380, 0xc001ac3438, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_cache.go:85 +0x1b3
github.com/cockroachdb/pebble.(*DB).loadTableStats(0xc000513500, 0xc001e008c0, 0x6, 0xc001a0f380, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_stats.go:253 +0xeb
github.com/cockroachdb/pebble.(*DB).loadNewFileStats(0xc000513500, 0xc001e35020, 0xc001d40f00, 0x4, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_stats.go:184 +0x1ec
github.com/cockroachdb/pebble.(*DB).collectTableStats(0xc000513500)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_stats.go:103 +0x162
created by github.com/cockroachdb/pebble.(*DB).maybeCollectTableStats
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/table_stats.go:45 +0x5e

For more context, check log files in: /cockroach/cockroach-data/logs


****************************************************************************
```

**Comment by skunkworker** [comment] 2020-12-04 18:12
I just ran into this issue as well, following the guide https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html#step-2-start-the-cluster on Mac OS Catalina 10.15.7.

the `roach1` node is the only one online, `roach2` would come online but as soon as `node3` was online it would error out and show this same error on both `roach1` and `roach2`.

To reproduce.

1. create the bridge.
2. start roach1.
3. start roach2.
4. start roach3.
5. initialize the cluster.
6. visiting the localhost:8080 page shows `NODE_STATUS_LIVE` for only `roach1`.
7. `roach1` and `roach2` would go offline and both show the same error but missing different `.sst` files.

I tried a few combinations where I would initialize the cluster before adding roach1 and roach2 but this still caused the same error to occur.

More logs before

````
I201204 18:09:52.360879 160 server/status/runtime.go:522 ⋮ [n2] runtime stats: 124 MiB RSS, 172 goroutines, 30 MiB/30 MiB/39 MiB GO alloc/idle/total, 1.6 MiB/2.8 MiB CGO alloc/total, 0.1 CGO/sec, 1.2/2.4 %(u/s)time, 0.0 %gc (0x), 35 KiB/48 KiB (r/w)net
I201204 18:10:02.325202 160 server/status/runtime.go:522 ⋮ [n2] runtime stats: 127 MiB RSS, 172 goroutines, 22 MiB/36 MiB/44 MiB GO alloc/idle/total, 1.6 MiB/2.8 MiB CGO alloc/total, 0.1 CGO/sec, 1.2/2.5 %(u/s)time, 0.0 %gc (1x), 35 KiB/50 KiB (r/w)net
I201204 18:10:12.325007 160 server/status/runtime.go:522 ⋮ [n2] runtime stats: 127 MiB RSS, 173 goroutines, 28 MiB/31 MiB/44 MiB GO alloc/idle/total, 1.6 MiB/2.8 MiB CGO alloc/total, 0.1 CGO/sec, 1.2/2.2 %(u/s)time, 0.0 %gc (0x), 45 KiB/56 KiB (r/w)net
I201204 18:10:19.960656 34 kv/kvserver/stores.go:255 ⋮ [n2] wrote 2 node addresses to persistent storage
I201204 18:10:20.383569 431 kv/kvserver/replica_raftstorage.go:798 ⋮ [n2,s2,r11/2:{-}] applying LEARNER snapshot [id=‹f197ce25› index=19]
E201204 18:10:20.540378 438 util/log/crash_reporting.go:321 ⋮ [n2] Queued as error ‹c64f5618f1ca46a6a2f2fa71316689ee›
I201204 18:10:20.556226 431 kv/kvserver/replica_raftstorage.go:819 ⋮ [n2,s2,r11/2:‹/Table/1{5-6}›] applied LEARNER snapshot [‹total=170ms›‹›‹ingestion=4@114ms›id=‹f197ce25› index=19]
F201204 18:10:21.089731 438 vendor/github.com/cockroachdb/pebble/internal/base/filenames.go:145 ⋮ [n2] ‹000007.sst›:
open ‹/cockroach/cockroach-data/000007.sst›: no such file or directory
directory contains 20 files, 9 unknown, 5 tables, 2 logs
```

**Comment by skunkworker** [comment] 2020-12-04 21:19
When running the cluster natively in MacOS this error does not occur, just on `Docker Desktop for Mac 2.5.0.1`

**Comment by erikgrinaker** [comment] 2020-12-13 14:15
This only happens when using a volume mounted from the host, removing the following flag appears to fix the issue:

```
-v "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data"
```

**Comment by knz** [comment] 2020-12-13 14:21
NB: if the user removes the flag, then the data is not in the host filesystem any more, so deleting the container will also remove the data files. This makes it harder to administrate a cluster safely.

**Comment by robert-s-lee** [comment] 2020-12-13 19:17
per https://github.com/cockroachdb/cockroach/issues/57873, folks following the docs page on Mac will need the modified instructions to remove `-v` option.  cc @jseldess

**Comment by knz** [comment] 2020-12-14 07:07
I disagree: we should not modify the doc.

This is a docker bug cause by apple and I am expecting a fix or workaround will be made available upstream. We need to chase that first.

**Comment by robert-s-lee** [comment] 2020-12-14 14:45
this issue happens on OS X 10.15.7 (19H15) as well with CRDB 20.2.1 and 20.2.2.  Prior CRDB versions are ok (as far back as 19.1)

**Comment by erikgrinaker** [comment] 2020-12-14 15:47
I suspect the errors were introduced with this commit, which quite possibly just uncovered a bug that's been there earlier as well: https://github.com/cockroachdb/pebble/commit/0a9a34bbaea6bad5fe767fe7558b16e09b8570f4. It was vendored into the 20.2 branch with https://github.com/cockroachdb/vendored/commit/d7a2da2e4a6224030aa516c144e6c95a48b2e1d2.

**Comment by jbowens** [comment] 2020-12-14 16:22
We've been seeing 'no such file or directory' errors reported via Sentry since 20.2 alpha. The cockroachdb/pebble@0a9a34b commit was in response to those reports. It shouldn't have caused new panics, just moved the panic closer to the filesystem operation that lead to the panic and provide better visibility into the code path yielding the error.

> this issue happens on OS X 10.15.7 (19H15) as well with CRDB 20.2.1 and 20.2.2. Prior CRDB versions are ok (as far back as 19.1)

I'm surprised it doesn't reproduce on 20.2.0, given then we've seen the Sentry reports as far back as 20.2.0 alphas. We should also check if it reproduces on 20.1.x with `--storage-engine=pebble`. We have only seen reports with Pebble as the storage engine, which was made the default with 20.2.

It's a little disconcerting that it seems easier to reproduce in releases containing cockroachdb/pebble@0a9a34b, as that might indicate there are fatal storage engine errors that are swallowed higher up the call stack.

cc @petermattis

**Comment by erikgrinaker** [comment] 2020-12-14 18:05
@jbowens I'm seeing what appears to be the same error on 20.2.0 as well, but they're not fatal, and the cluster starts up normally:

```
I201214 17:55:42.479835 891 vendor/github.com/cockroachdb/pebble/ingest.go:268 ⋮ [n3] [JOB 21] ingesting: sstable created 000022
I201214 17:55:42.482393 891 vendor/github.com/cockroachdb/pebble/ingest.go:268 ⋮ [n3] [JOB 21] ingesting: sstable created 000025
I201214 17:55:42.484453 891 vendor/github.com/cockroachdb/pebble/ingest.go:268 ⋮ [n3] [JOB 21] ingesting: sstable created 000023
I201214 17:55:42.486674 891 vendor/github.com/cockroachdb/pebble/ingest.go:268 ⋮ [n3] [JOB 21] ingesting: sstable created 000024
I201214 17:55:42.489125 891 vendor/github.com/cockroachdb/pebble/db.go:1364 ⋮ [n3] [JOB 22] WAL created 000026 (recycled 000008)
I201214 17:55:42.489384 930 vendor/github.com/cockroachdb/pebble/compaction.go:953 ⋮ [n3] [JOB 23] flushing 1 memtable to L0
I201214 17:55:42.490659 930 vendor/github.com/cockroachdb/pebble/compaction.go:1559 ⋮ [n3] [JOB 23] flushing: sstable created 000027
I201214 17:55:42.491937 930 vendor/github.com/cockroachdb/pebble/compaction.go:1008 ⋮ [n3] [JOB 23] flushed 1 memtable to L0 [000027] (2.2 K), in 0.0s, output rate 1.1 M/s
I201214 17:55:42.492030 932 vendor/github.com/cockroachdb/pebble/compaction.go:1369 ⋮ [n3] [JOB 24] compacting L0 [000027] (2.2 K) + L6 [000020 000019] (3.2 K)
I201214 17:55:42.495626 828 vendor/github.com/cockroachdb/pebble/table_stats.go:186 ⋮ [n3] background error: open ‹/cockroach/cockroach-data/000022.sst›: no such file or directory
I201214 17:55:42.496371 828 vendor/github.com/cockroachdb/pebble/table_stats.go:186 ⋮ [n3] background error: open ‹/cockroach/cockroach-data/000025.sst›: no such file or directory
I201214 17:55:42.496488 932 vendor/github.com/cockroachdb/pebble/compaction.go:1559 ⋮ [n3] [JOB 24] compacting: sstable created 000028
I201214 17:55:42.496995 828 vendor/github.com/cockroachdb/pebble/table_stats.go:186 ⋮ [n3] background error: open ‹/cockroach/cockroach-data/000023.sst›: no such file or directory
I201214 17:55:42.497558 828 vendor/github.com/cockroachdb/pebble/table_stats.go:186 ⋮ [n3] background error: open ‹/cockroach/cockroach-data/000024.sst›: no such file or directory
I201214 17:55:42.497547 891 vendor/github.com/cockroachdb/pebble/ingest.go:635 ⋮ [n3] [JOB 21] ingested L0:000022 (1.2 K), L0:000025 (1.2 K), L0:000023 (1.4 K), L6:000024 (1.2 K)
I201214 17:55:42.497641 932 vendor/github.com/cockroachdb/pebble/compaction.go:1408 ⋮ [n3] [JOB 24] compacted L0 [000027] (2.2 K) + L6 [000020 000019] (3.2 K) -> L6 [000028] (3.3 K), in 0.0s, output rate 654 K/s
I201214 17:55:42.498327 932 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 24] sstable deleted 000019
I201214 17:55:42.498926 932 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 24] sstable deleted 000020
I201214 17:55:42.499510 932 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 24] sstable deleted 000027
I201214 17:55:42.499584 912 vendor/github.com/cockroachdb/pebble/compaction.go:1369 ⋮ [n3] [JOB 26] compacting L0 [000022 000025 000023] (3.8 K) + L6 [000028] (3.3 K)
I201214 17:55:42.503396 912 vendor/github.com/cockroachdb/pebble/compaction.go:1559 ⋮ [n3] [JOB 26] compacting: sstable created 000029
I201214 17:55:42.504968 912 vendor/github.com/cockroachdb/pebble/compaction.go:1408 ⋮ [n3] [JOB 26] compacted L0 [000022 000025 000023] (3.8 K) + L6 [000028] (3.3 K) -> L6 [000029] (3.5 K), in 0.0s, output rate 730 K/s
I201214 17:55:42.505755 912 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 26] sstable deleted 000022
I201214 17:55:42.506478 912 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 26] sstable deleted 000023
I201214 17:55:42.507114 912 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 26] sstable deleted 000025
I201214 17:55:42.507834 912 vendor/github.com/cockroachdb/pebble/compaction.go:2312 ⋮ [n3] [JOB 26] sstable deleted 000028
```

However, one of the nodes eventually panics with the same error during iteration, which I believe is what you were referring to:

```
I201214 17:55:51.437226 1383 kv/kvserver/replica_raftstorage.go:798 ⋮ [n2,s2,r33/3:{-}] applying LEARNER snapshot [id=‹8d089163› index=21]
E201214 17:55:51.474021 679 util/log/crash_reporting.go:138 ⋮ [n2,s2] a panic has occurred!
open ‹/cockroach/cockroach-data/000131.sst›: no such file or directory
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	/usr/local/go/src/runtime/panic.go:679
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).destroy
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:460
  | github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Close
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:73
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*replicaAppBatch).Close
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_application_state_machine.go:977
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).applyOneBatch
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:282
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply.(*Task).ApplyCommittedEntries
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/apply/task.go:247
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReadyRaftMuLocked
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:765
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).handleRaftReady
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:425
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_raft.go:483
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:226
  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/scheduler.go:166
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1
  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222
  | runtime.goexit
  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
Wraps: (2) open ‹/cockroach/cockroach-data/000131.sst›
Wraps: (3) no such file or directory
Error types: (1) *withstack.withStack (2) *os.PathError (3) syscall.Errno
```

None of these errors happen when the host-mounted volume is disabled, by removing the `-v`. My guess would be that there are some idiosyncrasies (or just plain bugs) in the Docker/macOS filesystem bridge that Pebble doesn't take into account.

**Comment by jbowens** [comment] 2020-12-14 20:14
@erikgrinaker Thanks, yeah that makes sense. I wonder if we're seeing this: https://github.com/docker/for-mac/issues/5124#issuecomment-744486435 I'm going to try running using the patched Docker for Mac version in that issue.

**Comment by jbowens** [comment] 2020-12-14 20:21
I'm not positive about this, but I _think_ RocksDB will keep all the sstables its written in its table cache until they need to be evicted. Pebble doesn't put a table into its table cache until the first _read_, so just-written tables are _not_ in the table cache. That could explain why we've only seen this issue with Pebble. You wouldn't see it on RocksDB until its cache was full and it hit its first cache miss.

**Comment by jbowens** [comment] 2020-12-15 16:00
@knz Should we update the docs to make use of a docker _volume_?: https://github.com/docker/for-mac/issues/5124#issuecomment-745211978

**Comment by knz** [comment] 2020-12-15 16:08
yes that would be clever

**Comment by erikgrinaker** [comment] 2020-12-15 18:44
Makes sense @jbowens, thanks for looking into this! As you noted on the issue, this also works fine by disabling gRPC-FUSE in Docker (Preferences → Experimental Features → Use gRPC FUSE for file sharing). This is fairly new and was enabled by default in Docker for Mac 2.4.0.0 (September 30th). Maybe that could be listed as a workaround too.

**Comment by jseldess** [comment] 2020-12-15 20:03
Thanks for the suggestion and docs issue, @erikgrinaker!

**Comment by rafiss** [comment] 2021-02-18 03:58
Closing since the docs were updated. Thanks for investigating and documenting, all!

**Closed by rafiss** 2021-02-18 03:58 UTC
Labels: B-os-macos, O-community, X-blathers-triaged
