### ISSUE TITLE
circleci: failed tests: TestTxnPutOutOfOrder

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6775] opened 2016-05-18 17:35 UTC
The following test appears to have failed:

[#18040](https://circleci.com/gh/cockroachdb/cockroach/18040):

```
I160518 17:35:26.740337 kv/dist_sender.go:974  application error: range 0: replica <nil> not leader; leader is <nil>
I160518 17:35:26.740471 kv/dist_sender.go:974  application error: range 0: replica <nil> not leader; leader is <nil>
I160518 17:35:26.740604 kv/dist_sender.go:974  application error: range 0: replica <nil> not leader; leader is <nil>
I160518 17:35:26.740729 kv/dist_sender.go:974  application error: range 0: replica <nil> not leader; leader is <nil>
I160518 17:35:26.740859 kv/dist_sender.go:974  application error: range 0: replica <nil> not leader; leader is <nil>
panic: test timed out after 1m10s

goroutine 14692 [running]:
panic(0x156f960, 0xc821c80050)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1d17878, 0x24a2540, 0x10f, 0x10f, 0xc820215b01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820045ef8, 0xc820265c98)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820045ef8)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:54 +0x1de
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:604 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x277a0a0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 14674 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:992 +0x3cf
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820bbc4a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14635 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9ef20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14640 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9f040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14669 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc820e94960)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:203 +0xd21
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:188 +0x20
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820d46800)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14638 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9efc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14637 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9ef80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14678 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820bbc6a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14675 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1011 +0x3cf
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820bbc4c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14690 [select]:
github.com/cockroachdb/cockroach/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:123 +0x86a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc8215ff040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14670 [select]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:225 +0x23f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820eaede0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14665 [semacquire]:
sync.runtime_Syncsemacquire(0xc821728f90)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc821728f80)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Quiesce(0xc821800310)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:354 +0x1eb
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc821800310)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:300 +0x1a7
github.com/cockroachdb/cockroach/storage_test.TestTxnPutOutOfOrder(0xc8219150e0)
	/go/src/github.com/cockroachdb/cockroach/storage/client_replica_test.go:322 +0xdaa
testing.tRunner(0xc8219150e0, 0x24a3cb0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 14679 [select]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc821801260, 0xecece9eac, 0xaee4eb8, 0x27794c0, 0xc821728f40, 0xc821800310, 0xc821926300, 0xc820021e98)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:161 +0x568
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc821926300, 0xc821224240)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:203 +0x78
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc821224690, 0xc821729e00)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:231 +0x246
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:205 +0x21e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820bbc6c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14639 [select]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9efe0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14666 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc82185dda0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:164 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:165 +0x8f4

goroutine 14636 [runnable]:
fmt.(*pp).argNumber(0xc821dd2ea0, 0x2, 0x1960640, 0xa, 0x8, 0x3, 0x1, 0x5, 0x0)
	/usr/local/go/src/fmt/print.go:1088
fmt.(*pp).doPrintf(0xc821dd2ea0, 0x1960640, 0xa, 0xc820914048, 0x3, 0x3)
	/usr/local/go/src/fmt/print.go:1144 +0xc87
fmt.Sprintf(0x1960640, 0xa, 0xc820914048, 0x3, 0x3, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:203 +0x6f
github.com/cockroachdb/cockroach/roachpb.BatchRequest.String(0xc8, 0xdf388, 0x100000001, 0x1, 0x2, 0x0, 0x0, 0x0, 0xc8219d8ba0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/roachpb/batch.go:525 +0x64a
github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).String(0xc820c99340, 0x0, 0x0)
	<autogenerated>:414 +0xb3
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820e9ef60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14673 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func4()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:921 +0x13d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820bbc480)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14671 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2059 +0xbf1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc821800310, 0xc820d47dc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
FAIL	github.com/cockroachdb/cockroach/storage	70.049s
=== RUN   TestBatchBasics
I160518 17:34:06.434263 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160518 17:34:06.436714 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.02s)
=== RUN   TestBatchRepr
I160518 17:34:06.441427 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160518 17:34:06.443054 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.02s)
=== RUN   TestBatchGet
I160518 17:34:06.460742 storage/engine/rocksdb.go:137  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-18 18:11
Duplicate of #6736

**Closed by bdarnell** 2016-05-18 18:11 UTC
Labels: Robot, test-failure
