### ISSUE TITLE
`pkg/sql/logictest/tests/fakedist`: `TestLogic_record` fails under `race`

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#119780] opened 2024-02-29 20:05 UTC
[EngFlow link](https://tanzanite.cluster.engflow.com/invocations/default/a3eb9939-b546-4f38-a839-ddad7c6985a6?testReportRun=3&testReportAttempt=0#targets-Ly9wa2cvc3FsL2xvZ2ljdGVzdC90ZXN0cy9mYWtlZGlzdDpmYWtlZGlzdF90ZXN0)

Follow up from #118691. Seems to be a different problem.

```
==================
WARNING: DATA RACE
Write at 0x00c00535a5f0 by goroutine 427784:
  github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.ensureTypeMetadataIsHydrated()
      github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/hydrate.go:123 +0x145
  github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.ensureTypeIsHydratedRecursive()
      github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/hydrate.go:106 +0x3cd
  github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.ensureTypeIsHydratedRecursive()
      github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/hydrate.go:83 +0x464
  github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc.HydratedTFromDesc()
      github.com/cockroachdb/cockroach/pkg/sql/catalog/typedesc/hydrate.go:55 +0xa6
  github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveType()
      github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:364 +0x4d2
  github.com/cockroachdb/cockroach/pkg/sql.(*planner).ResolveType()
      <autogenerated>:1 +0x53
...
```

Jira issue: CRDB-36310

**Comment by DrewKimball** [comment] 2024-03-04 18:23
Dupe of #119866, I'll push up a fix soon.

**Closed by DrewKimball** 2024-03-04 18:23 UTC
Labels: C-bug, T-sql-queries
