### ISSUE TITLE
perf: denim running loadgen/YCSB shows latency degradation

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#13627] opened 2017-02-16 18:36 UTC
Azure cluster denim has been running YCSB for a week now, and query latency has slowly degraded to the point where median execution latency is ~200ms, and 99%ile latency is in multiple seconds(!) for multiple nodes. One of the nodes (node 3), however, is still performing well with ~15ms execution latency. Performance has steadily degraded every day. Note that there are other bugs as well on denim, such as #13611, and the fact that QPS does not scale up linearly with more nodes even though it should based on the query load pattern.

<img width="888" alt="screenshot 2017-02-16 13 32 23" src="https://cloud.githubusercontent.com/assets/1565833/23035296/9d3ce4ea-f44c-11e6-9100-1feb7ee54152.png">

@petermattis could you please triage this for me? Thank you!

**Comment by petermattis** [comment] 2017-02-17 19:35
I'm still investigating `denim`, but so far the investigation has produced:
* https://github.com/cockroachdb/loadgen/pull/19 which removed unnecessary KV reads when qualifying table names. https://github.com/cockroachdb/cockroach/pull/13635 fixed the issue in CockroachDB
* https://github.com/cockroachdb/loadgen/pull/21 which was causing connection thrashing. While the overhead of TLS is reasonable for data transfer, opening TLS connections is somewhat expensive.

Right now, latencies on `denim` appear reasonable, though the cluster appears to be CPU limited by the node running `ycsb`. This node is also running `cockroach` and `haproxy`. @arjunravinarayan is going to move `ycsb` and `haproxy` to a separate node and also rebuild the cluster to use 8 cores/machine.

**Comment by petermattis** [comment] 2017-02-17 19:41
![screen shot 2017-02-17 at 2 40 43 pm](https://cloud.githubusercontent.com/assets/6201335/23080538/1ec973b6-f51f-11e6-97bc-fa8e4a32aa60.png)

**Comment by a-robinson** [comment] 2017-03-06 19:42
I'm seeing some similar degradation when doing high latency testing, and it's hard to tell how much is due to the high latency lease placement vs the natural behavior of cockroach, so getting to the bottom of this would be great :)

**Comment by petermattis** [comment] 2017-03-06 20:39
Just reproduced the problem on `denim` using 2db0d6d83f03ae3699a48b29fb7dd96d43b72ecd. The problem did not magically go away.

**Comment by petermattis** [comment] 2017-03-06 21:19
`kv` doesn't show the same performance degradation as `ycsb`, but it does show high latency on a single node. `/debug/requests` shows that `r22` is involved in all of the slow requests. And `/debug/range?id=22` shows that range as consistently having O(100-200) pending commands while other ranges on the system have O(0-1) pending commands. Something is hammering that one range which happens to be the first range in the `test.kv` table. Load generator bug?

**Comment by petermattis** [comment] 2017-03-06 22:25
The `kv` problem with hammering a single range was a load generator bug. See https://github.com/cockroachdb/loadgen/pull/29. Fixing this "improved" `kv` performance so that it is now similar to `ycsb` performance when configured with the same read/write ratio.

**Comment by petermattis** [comment] 2017-03-07 02:25
Performance on `denim` looks stable under `kv` workload. Currently running at 35k ops/sec for almost an hour. 99th-%tile latencies on all of the nodes are reasonably steady at ~25-30ms. The difference between `ycsb` and `kv` is the skewed distribution for reads. But `ycsb` performance starts out good and then hits a cliff. What changes? Still looking.

**Comment by petermattis** [comment] 2017-03-07 16:40
The node experiencing high latencies has a lot of requests hitting `r10`:

```
2017/03/07 16:38:20.566775	0.208849	node.Batch
16:38:20.566778	 .     3	... txnID:2eb086ee-4943-4bfe-95a1-81b9164e1402
16:38:20.566780	 .     2	... node.Batch
16:38:20.566784	 .     4	... [n2] 1 Scan
16:38:20.566790	 .     6	... [n2,s2] executing 1 requests
16:38:20.566795	 .     5	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] read-only path
16:38:20.566799	 .     5	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] command queue
16:38:20.732090	 .165290	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] waiting for read lock
16:38:20.732151	 .    61	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] read completed
```

```
2017/03/07 16:38:20.443505	0.319658	node.Batch
16:38:20.443509	 .     3	... txnID:3ff3cd20-7b6b-49f2-84ef-9c8d7ca499f8
16:38:20.443511	 .     2	... node.Batch
16:38:20.443515	 .     4	... [n2] 1 Scan
16:38:20.443522	 .     7	... [n2,s2] executing 1 requests
16:38:20.443527	 .     5	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] read-only path
16:38:20.443533	 .     6	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] command queue
16:38:20.763098	 .319565	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] waiting for read lock
16:38:20.763149	 .    51	... [n2,s2,r10/2:/Table/51/1/280{308970-754021},@c420a7ee00] read completed
```

Why so many requests to `r10`? And why are we spending so much time `waiting for read lock`?

**Comment by petermattis** [comment] 2017-03-07 17:27
Killing the node holding the lease for `r10` allowed the lease to migrate to another node and it pulled along the high latencies with it.

**Comment by petermattis** [comment] 2017-03-07 19:39
Interesting, the range that is having the trouble always always spans the keys `[/Table/51/1/280308970, /Table/51/1/280754021]`. We pre-split the ycsb table deterministically at `280308970` and `280754021`. Due to the way ycsb keys are hashed, this range of keys happens to get twice as many read requests as the next most active range (I instrumented our `ycsb` client to run simulations that demonstrate this). So the observation that this range is receiving the majority of read requests is correct, though it isn't clear why performance falls off a cliff at some point.

**Comment by petermattis** [comment] 2017-03-07 20:11
<img width="865" alt="screen shot 2017-03-07 at 3 07 47 pm" src="https://cloud.githubusercontent.com/assets/6201335/23675614/dd5e98de-0347-11e7-9426-ba694d110c1a.png">

We seem to be spending a lot of time in the `CommandQueue`. Another node with normal latencies doesn't show the `CommandQueue` at all on a profile.

**Comment by petermattis** [comment] 2017-03-07 20:19
Prometheus metrics show: `replicas_commandqueue_maxtreesize{store="1"} 209`. Is something getting wedged up in the command queue, or is this just the load itself that is causing that number of entries in the command queue? Other nodes report that metric as zero or near zero.

**Comment by petermattis** [comment] 2017-03-07 20:28
Ok, an ad-hoc graph for the `maxtreesize` metric shows that it jumped from 0-1 to ~200 at exactly the same time that performance fell off a cliff. Now to figure out why.

**Comment by petermattis** [comment] 2017-03-07 20:57
The global command queue for the problematic range shows:

```
I170307 20:50:23.783802 120 storage/store.go:3891  [n3,s3,r25/4:/Table/51/1/280{308970-754021},@c4208d4700] command queue (global): 213
  2350015 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350098 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350381 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350456 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350611 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350630 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350737 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350741 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350763 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350792 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350823 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350919 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2350968 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2351042 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2351057 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
  2351071 readonly [/Table/51/1/280308970,/Table/51/1/280308971)
...
```

So we have 1 hot key `280308970` that is somehow filling up the command queue. Curiously, for a period of time the command queue is ok. And then something happens (what, I don't know) and it backs up. Note that other log messages indicate that these commands are not permanently wedged. They enter the command queue, get processed and then exit.

**Comment by petermattis** [comment] 2017-03-07 20:59
It's possible the command queue size is a symptom and not the problem. Perhaps reads for this particular key have gotten slow causing each operation to spend longer in the command queue.

**Comment by petermattis** [comment] 2017-03-08 03:02
`CommandQueue` uses a single interval tree to hold spans for both read operations and write operations. `CommandQueue.getWait` retrieves any overlapping spans and, if `readOnly` is true, filters out the read operation spans. Consider what is happening above for the single hot row that is being accessed. `CommandQueue` has O(200) spans for read commands in its tree for the same row. `getWait` needs to retrieve all of these spans and then filters all of them away. 

I think this inefficiency can be fixed by keeping separate trees for read and write operations. Then `CommandQueue.getOverlaps` for read operations would only have to consult the write spans tree which, for the YCSB workload, is usually empty.

I prototyped this and it doubles performance when in the "slow regime" from 9k-10k ops/sec to 18k-20k ops/sec. But this is still below the 30k-35k ops/sec we're seeing in the "fast regime". So still something to figure out here.

**Comment by arjunravinarayan** [comment] 2017-03-08 03:10
On Tue, Mar 7, 2017 at 7:02 PM Peter Mattis <notifications@github.com>
wrote:

> CommandQueue uses a single interval tree to hold spans for both read
> operations and write operations. CommandQueue.getWait retrieves any
> overlapping spans and, if readOnly is true, filters out the read
> operation spans. Consider what is happening above for the single hot row
> that is being accessed. CommandQueue has O(200) spans for read commands
> in its tree for the same row. getWait needs to retrieve all of these
> spans and then filters all of them away.
>
> I think this inefficiency can be fixed by keeping separate trees for read
> and write operations. Then CommandQueue.getOverlaps for read operations
> would only have to consult the write spans tree which, for the YCSB
> workload, is usually empty.
>
> I prototyped this and it doubles performance when in the "slow regime"
> from 9k-10k ops/sec to 18k-20k ops/sec.
>
I assume performance is unchanged in the fast regime, as the command queue
is empty, correct?

But this is still below the 30k-35k ops/sec we're seeing in the "fast

**Comment by petermattis** [comment] 2017-03-08 03:15
> I assume performance is unchanged in the fast regime, as the command queue is empty, correct?

Correct.

**Comment by petermattis** [comment] 2017-03-08 15:57
<img width="476" alt="screen shot 2017-03-08 at 10 53 31 am" src="https://cloud.githubusercontent.com/assets/6201335/23711327/8abcabb0-03ed-11e7-92b0-c204db2b60b7.png">

The above graph shows range-level operations per node. In the good regime, the load is fairly evenly distributed. But then something happens and one node starts receiving 100x the operations as other nodes. Still not clear what happened as there were no lease rebalances immediately preceding this. So my hypothesis that a few hot ranges landed on a single node seems to be wrong.

**Comment by petermattis** [comment] 2017-03-08 21:21
I added a bit of logging to `ycsb`. When the "bad regime" is entered, the log shows:

```
~ cockroach@cockroach-denim-0007:~$ tail -1000000 ycsb.keys | uniq -c
1000000 1 -> 280308970
```

That's showing that the 1m most recently read keys were for the same key: `1` is the raw zipf key and `280308970` is the hashed key. So there is some problem in the key generation. Maybe an overflow or something like that.

Cc @arjunravinarayan

**Comment by petermattis** [comment] 2017-03-08 21:27
Oh boy, `ZipfGenerator.r` is not protected by a mutex.

**Comment by petermattis** [comment] 2017-03-08 22:36
Pretty sure https://github.com/cockroachdb/loadgen/pull/31 will fix the issue here. We'll know in an hour.

**Comment by petermattis** [comment] 2017-03-08 23:56
<img width="933" alt="screen shot 2017-03-08 at 6 55 19 pm" src="https://cloud.githubusercontent.com/assets/6201335/23729599/dc5adbfc-0430-11e7-9ee1-63ab96d60c45.png">

1.5 hours of steady performance. I'm going to declare success.

**Comment by a-robinson** [comment] 2017-03-08 23:57
Nice find!

**Closed** 2017-03-08 23:59 UTC
Labels: performance
