### ISSUE TITLE
Incorrect path to include file in generated eventlog.md

### ISSUE THREAD

**Issue by stbof** [cockroachdb/cockroach#84024] opened 2022-07-07 18:57 UTC
https://www.cockroachlabs.com/docs/v21.2/eventlog#sql-access-audit-events

https://www.cockroachlabs.com/docs/v22.1/eventlog#sql-access-audit-events

This content is remotely included from https://github.com/cockroachdb/cockroach/blob/release-21.2/docs/generated/eventlog.md  and https://github.com/cockroachdb/cockroach/blob/release-22.1/docs/generated/eventlog.md

<img width="1154" alt="Screen Shot 2022-07-07 at 11 56 32 AM" src="https://user-images.githubusercontent.com/20482960/177851034-1d20c68f-5c98-435d-a979-bbe78e25b168.png">

Jira issue: CRDB-17416

**Comment by knz** [comment] 2022-07-08 14:30
Hi Stefanie, thanks for reporting. I believe this is not a crdb issue, instead it's a doc infra issue.
@taroface do you remember how we did this integration?

**Comment by ianjevans** [comment] 2022-07-08 17:46
@knz It's a limitation in our doc tools, but since we consume these files directly to build the docs it will involve changes in this repo so the generated files work correctly.

**Comment by knz** [comment] 2022-07-08 18:36
Thanks. What changes are required?
(The issue is assigned to me but I don't know what needs to be done)

**Comment by knz** [comment] 2022-07-08 21:01
How is that the best option? We're expecting that this callout will change phrasing from version to version. Isn't it better to fix the processing of that include in the doc generation code instead?

**Comment by stbof** [comment] 2022-07-08 21:12
I'm not claiming it's the best option. We have a long list of doc tools Jiras. I don't know how they will be prioritized, but I don't think this is the highest priority right now.  In the meantime the fix should be to replace the unresolved reference with the text.

**Comment by stbof** [comment] 2022-07-08 21:19
My bad. The problem is that the path to the included file changed in 21.2 to `common/experimental-warning.md`.  So that's all you need to do to fix it.

**Comment by stbof** [comment] 2022-07-08 21:20
![Uploading Screen Shot 2022-07-08 at 2.20.12 PM.png…]()

**Comment by stbof** [comment] 2022-07-08 21:23
My bad. The problem is that the path to the included file changed in 21.2 to `common/experimental-warning.md`.  See the next comment.  There's no longer a version specific file. So that's all you need to do to fix it.
<img width="612" alt="Screen Shot 2022-07-08 at 2 20 12 PM" src="https://user-images.githubusercontent.com/20482960/178072270-cf1d1f74-6c54-4f2c-9bab-345afc148e5b.png">

**Comment by knz** [comment] 2022-07-08 21:41
Cool, 
so I went to investigate this.

It appears that `eventlog.md` does not, in fact, contain this include to experimental-warning.md.

It was already removed by @taroface on the `master` branch as part of PR #78255 on March 22.

Now we have a couple of problems on our hands:

- The PR #78255 from March 22 was not backported to the release-22.1 branch. That's why the copy included in the v22.1 doc tree is broken. I'll do this backport.
- as your screenshot above shows, you still need to (manually) fix the broken include in `logging-use-cases.md`, `show-range-for-row.md`, etc.
- the doc source file `v21.1/eventlog.md` incorrectly points to the `master` branch of crdb in the include. This should be release-21.1 instead. That's also a change in the docs repo.

**Comment by stbof** [comment] 2022-07-08 21:52
The includes aren't broken in logging-use-cases.md, show-range-for-row.md, etc. because in 21.1 the include file still existed in v21.1/misc/experimental-warning.md

I'll fix v21.1/eventlog.md.

**Comment by knz** [comment] 2022-07-08 23:38
Fixed in #84111, #84112 and #84114

**Comment by knz** [comment] 2023-01-10 09:15
we've fixed those.

**Closed by knz** 2023-01-10 09:15 UTC
Labels: C-bug, A-docs, A-logging
