### ISSUE TITLE
sql: poison_after_push failure

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#4787] opened 2016-03-02 21:09 UTC
See https://circle-artifacts.com/gh/petermattis/cockroach/404/artifacts/0/tmp/circle-artifacts.lxM4EST/test.log

The error is `logic_test.go:529: testdata/poison_after_push:40: expected retry txn, but found pq: txn aborted "sql/executor.go:597 sql implicit: false" id=e215adcb key=/Table/51/1/2/0 rw=true pri=0.00070515 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456952200.882866398,0 orig=1456952200.882866398,0 max=1456952200.932866398,0`. I'm pretty sure this is unrelated to the changes in the associated PR.

**Comment by vivekmenezes** [comment] 2016-03-08 21:38
https://circleci.com/gh/cockroachdb/cockroach/14082?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by RaduBerinde** [comment] 2016-03-14 19:27
The error is passing through here:
```go
		if !inTxn {
			// Detect implicit transactions.
			if _, isBegin := stmts[0].(*parser.BeginTransaction); !isBegin {
				execOpt.AutoCommit = true
				stmtsToExec = stmtsToExec[0:1]
			}
			txnState.txn = e.newTxn(planMaker.session)
			execOpt.AutoRetry = true
			txnState.txnTimestamp = time.Now()
			txnState.txn.SetDebugName(fmt.Sprintf("sql implicit: %t", execOpt.AutoCommit), 0)
		}
```

I believe we should be `inTxn` here.. I know @andreimatei made some restructuring of related code since so it might no longer be an issue. I'll try to repro locally.

The error in Vivek's link is different (`expected retry txn, but found <nil>`), I think that one is the same with #4249 and was fixed.

**Comment by RaduBerinde** [comment] 2016-03-14 20:56
Could not repro locally. The issue might be fixed already.
```
$ make stress PKG=./sql TESTS=TestLogic TESTFLAGS='-d testdata/poison_after_push'
..
483270 runs so far, 0 failures, over 1h15m50s
```

**Comment by RaduBerinde** [comment] 2016-03-14 23:43
`1544179 runs so far, 0 failures, over 4h2m10s`

**Comment by petermattis** [comment] 2016-03-14 23:45
This just happened again on CircleCI (see #5250). Try running `make stress` without specifying a particular logic test file. Try running `make stress` without specifying a specific test. Or ask Tobias if there is additional logging that can be added so that we can track this down the next time it happens on CircleCI.

**Comment by RaduBerinde** [comment] 2016-03-15 14:04
Thanks. Looks like it's a case with `expected retry txn, but found <nil>` (which we thought was fixed in #4249). Will try to investigate

**Comment by RaduBerinde** [comment] 2016-03-15 20:14
@tschottdorf in order for the test to succeed, the LOW priority transaction has to lose to the HIGH priority transaction, right? That isn't necessarily the case because there is randomness in the priority - in fact it's the case only 99% of the time.

The priority inversion explains what we see above - we expect a "retry txn" error but we get no error. But then I'm not sure why I can't reproduce the failure locally.

**Comment by RaduBerinde** [comment] 2016-03-15 20:33
Ah, we don't initialize the random seed for sql tests so repeating just that file results in the same priorities. So it depends on the amount of random calls that happened before in whatever sequence of tests ran on CircleCI

**Comment by tschottdorf** [comment] 2016-03-15 20:34
> (which we thought was fixed in #4249). Will try to investigate

Nope, that was a kv test which didn't properly set its priorities, so that fix didn't affect this one

> in order for the test to succeed, the LOW priority transaction has to lose to the HIGH priority transaction, right? That isn't necessarily the case because there is randomness in the priority - in fact it's the case only 99% of the time.

Is it really 99% or maybe something much higher?

> The priority inversion explains what we see above - we expect a "retry txn" error but we get no error. But then I'm not sure why I can't reproduce the failure locally.

Not really - we complete the `HIGH` read successfully, so it can't not have pushed it unless it didn't have to. If the Push did happen (which is my working hypothesis), then maybe the sequence cache didn't get poisoned. This poisoning happens synchronously with EndTransaction, at least when executed on the same range, though, so that's weird again.
We're creating a new table, so there may be range splits going on in the background. Not sure that has anything to do with it, but worth keeping in mind.

**Comment by tschottdorf** [comment] 2016-03-15 20:35
try running with `TESTFLAGS=-count 100` to tickle the randomness more.

**Comment by RaduBerinde** [comment] 2016-03-15 20:48
Yes it's 99% (lose vs win ratio is 1 to 10/0.1).
I tried setting the randomness seed and using -count and I still can't reproduce.
But if I change the test to reverse the HIGH and LOW priorities I get the `expected retry txn, but found <nil>` error right away. So it does depend on the priorities.. (if it didn't why did you bother using HIGH and LOW?)

**Comment by RaduBerinde** [comment] 2016-03-15 20:50
We generate a few more priorities during that test so maybe it's not as simple as two priorities getting inverted, but rather a specific order for more than two priorities. That would make it more rare.

**Comment by RaduBerinde** [comment] 2016-03-15 21:01
I ran more iterations and reproduced with the randomness fix. These were the priorities generated during the test:
```
MEH priority: 1.000000 value: 1720297
MEH priority: 1.000000 value: 654365
MEH priority: 1.000000 value: 559137
MEH priority: 0.100000 value: 121155
MEH priority: 1.000000 value: 26059
MEH priority: 10.000000 value: 98165
MEH priority: 1.000000 value: 28083
MEH priority: 1.000000 value: 160866
MEH priority: 1.000000 value: 132655
MEH priority: 1.000000 value: 98837
MEH priority: 1.000000 value: 13175
MEH priority: 1.000000 value: 123250
MEH priority: 1.000000 value: 225647
MEH priority: 1.000000 value: 523697
```
We see the priority inversion.

**Comment by RaduBerinde** [comment] 2016-03-15 21:15
My thinking for fixing this is to extend the SQL syntax to allow specifying the exact priority number. E.g. `PRIORITY INTERNAL(100)` would translate to `-100` priority value which goes around the random generation.

My worry is that this will open this "feature" to be used by anyone, and even worse it will make it into the syntax-based documentation. Andrei tells me he was thinking of adding another internal thing (a transaction tag/name) so maybe we want to be able to hide certain parts of the grammar from the documentation anyway.

**Comment by petermattis** [comment] 2016-03-15 21:18
Could we add something to the logic test framework? That seems a bit hackier than extending the SQL syntax, but it does avoid extending the syntax.

**Comment by RaduBerinde** [comment] 2016-03-15 21:24
Yeah, we could add a flag that controls `setUserPriority` and if the flag is set, we convert HIGH and LOW to hardcoded values. This might be a bit obtuse to whoever reads the test and assumes that SQL will always work as the test expects it to work though. If we go this route, I'll make sure to comment this properly in the test.

**Comment by petermattis** [comment] 2016-03-15 21:27
I was thinking you'd add a logic test directive: `txn-priority HIGH = <val>`. The logic test runner would see that directive and set some global that controls the mapping of `HIGH` to an actual priority value.

**Comment by tschottdorf** [comment] 2016-03-15 22:19
> (if it didn't why did you bother using HIGH and LOW?)

sorry, yes, HIGH and LOW are definitely required. Did the failing test get the error on the "HIGH" transaction? If so, that makes sense - but I thought the test got the error when the LOW guy should find out it was aborted but didn't. That doesn't make sense with the priority inversion - the HIGH (with his lower prio) should not be able to succeed (at least not without somehow pushing the intent, which should trigger the correct error when the LOW guy comes back).

**Comment by tschottdorf** [comment] 2016-03-15 22:36
I like the idea of internally translating HIGH and LOW in the test runner. As far as I'm concerned, don't need a switch in the test file - but there should be a way to disable it in the parallel runner.

But I want to make sure we understand the mechanism by which the above test is failing - if my assumptions are right, I don't understand it just yet.

**Comment by RaduBerinde** [comment] 2016-03-15 22:48
I see. You are right that the HIGH transaction does commit successfuly. But given that reversing HIGH and LOW in the test makes it hit right away, it's definitely not a race condition related to ranges splitting and whatnot.

**Comment by RaduBerinde** [comment] 2016-03-15 22:49
I will work on adding the `txn-priority` thing, I like that. In the meantime we should investigate with HIGH and LOW reversed and see what is happening.

**Comment by tschottdorf** [comment] 2016-03-16 02:28
Sounds good, though my first priority would be debugging the issue at hand
(your message indicates that that's your second). Should be easy enough
with the inversed prios.

**Comment by RaduBerinde** [comment] 2016-03-16 03:08
No, I agree, "in the meantime" as in "before" :)  I looked into it a bit more with inverted priorities. Here is what I found so far:
 - if (after the SELECT that succeeds) the second txn tries to commit, that (fortunately) fails: `client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:390: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:390: transaction is already committed or aborted`
 - the SELECT of the second txn (low priority after inverting) takes a long time to complete (seconds), which suggests it's being retried internally. It is the first statement in a txn so the server should be allowed to retry it (I will check with Andrei if this is expected)
 - the SELECT of the first txn that runs after the second txn and which we would expect to fail), returns just row 1 - it does NOT return the row we added in the same txn. If I add a SELECT that runs before the second txn it returns both rows.

Looking at the priorities generated, it doesn't look that the retried txn gets through because it finally gets a high enough priority. It looks more like some kind of timeout kills the first txn and that allows the second txn to go through - it always goes through after about the same amount of time / # of retries. If this is what is happening, the bug here is that the next statement in the timed out transaction does not fail.

Here are two examples. In this one we never get anything bigger than 1920029:
```
testdata/poison_after_push:20 root: INSERT INTO t VALUES (2)
Generated priority value 1920029 for priority 10.000000
Generated priority value 285794 for priority 1.000000
testdata/poison_after_push:26 testuser: BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE, PRIORITY LOW
testdata/poison_after_push:30 testuser: SELECT * FROM t
Generated priority value 14022 for priority 0.100000
Restart: upgrading priority. Before: 14022
Generated priority value 670238 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 67397 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 269086 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 78665 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 274903 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 195611 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 189355 for priority 1.000000
Restart: upgraded priority. After:   1920028
Restart: upgrading priority. Before: 14022
Generated priority value 443028 for priority 1.000000
Restart: upgraded priority. After:   1920028
```

Here we actually get a few values that are higher than 686604 but it doesn't seem to make a difference:
```
testdata/poison_after_push:17 root: BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE, PRIORITY HIGH
testdata/poison_after_push:20 root: INSERT INTO t VALUES (2)
Generated priority value 686604 for priority 10.000000
Generated priority value 464749 for priority 1.000000
testdata/poison_after_push:26 testuser: BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE, PRIORITY LOW
testdata/poison_after_push:30 testuser: SELECT * FROM t
Generated priority value 90239 for priority 0.100000
Restart: upgrading priority. Before: 90239
Generated priority value 816409 for priority 1.000000
Restart: upgraded priority. After:   816409
Restart: upgrading priority. Before: 90239
Generated priority value 225197 for priority 1.000000
Restart: upgraded priority. After:   686603
Restart: upgrading priority. Before: 90239
Generated priority value 929325 for priority 1.000000
Restart: upgraded priority. After:   929325
Restart: upgrading priority. Before: 90239
Generated priority value 25177 for priority 1.000000
Restart: upgraded priority. After:   686603
Restart: upgrading priority. Before: 90239
Generated priority value 186997 for priority 1.000000
Restart: upgraded priority. After:   686603
Restart: upgrading priority. Before: 90239
Generated priority value 18498 for priority 1.000000
Restart: upgraded priority. After:   686603
Restart: upgrading priority. Before: 90239
Generated priority value 203361 for priority 1.000000
Restart: upgraded priority. After:   686603
Restart: upgrading priority. Before: 90239
Generated priority value 105665 for priority 1.000000
Restart: upgraded priority. After:   686603
```

**Comment by tschottdorf** [comment] 2016-03-16 03:28
Ah - that's likely retrying in `(*Store).Send` then and never succeeds
until it can push the other transaction based on that one's inactivity. Can
you take a look at the timestamps in the failing CI run and see whether
they indicate a 10-20s test duration? That would support that hypothesis.

That the txn which has been aborted based on inactivity can go back to that
range and read "incorrect" data (it lost its own write) is bad - preventing
that is part of why I introduced sequence cache poisoning in the first
place. When the push which aborts the txn comes bad, we should send a
ResolveIntent which clears up the intent - try logging it (in
`ResolveIntent` will do) and make sure that it's calling
`clearSequenceCache` with poison=true and that that calls actually puts
something into the cache (and if all of that happens, why it's not read
correctly in `checkSequenceCache`).

**Comment by RaduBerinde** [comment] 2016-03-16 13:57
Yeah I see the test taking 17sec in CircleCI (normally takes a second or so) so he same is happening.

More stuff I found:

- ROLLBACK gets the same error as the COMMIT `client/txn.go:346  failure aborting transaction: kv/txn_coord_sender.go:390: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:390: transaction is already committed or aborted`

- if I replace the SELECT with an INSERT, I get `client/txn.go:347  failure aborting transaction: kv/txn_coord_sender.go:390: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:342: transaction must not write on multiple coordinators`

**Comment by RaduBerinde** [comment] 2016-03-16 15:24
poison is false in clearSequenceCache

```
testdata/poison_after_push:30 testuser: SELECT * FROM t
Executing txn <nil>
Generated priority value 6841 for priority 0.100000
Restart: upgrading priority. Before: 6841
Generated priority value 1144132 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 41083 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 98008 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 821078 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 138571 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 274256 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 331864 for priority 1.000000
Restart: upgraded priority. After:   4885614
Restart: upgrading priority. Before: 6841
Generated priority value 241503 for priority 1.000000
Restart: upgraded priority. After:   4885614
I160316 11:23:16.775594 server/status/runtime.go:140  runtime stats: 56 goroutines, 5.43MiB active, 277.00cgo/sec, 0.02/0.01 %(u/s)time, 0.00 %gc (4x)
clearSequenceCache for txn 97ffaa78-d2a9-4ef6-83ea-f7218c516f41. poison: false
testdata/poison_after_push: 7
testdata/poison_after_push:35 testuser: COMMIT
Executing txn 12ec986f-fa6b-4b06-98ce-4c0c579729da
Executing txn <nil>
Executing txn 97ffaa78-d2a9-4ef6-83ea-f7218c516f41
testdata/poison_after_push:42 root: SELECT * FROM t
Executing txn 97ffaa78-d2a9-4ef6-83ea-f7218c516f41
testdata/poison_after_push:47 root: COMMIT
Executing txn 97ffaa78-d2a9-4ef6-83ea-f7218c516f41
E160316 11:23:19.327567 client/txn.go:347  failure aborting transaction: kv/txn_coord_sender.go:390: transaction is already committed or aborted; abort caused by: kv/txn_coord_sender.go:390: transaction is already committed or aborted
```

**Comment by tschottdorf** [comment] 2016-03-16 15:27
Ok, let's find out where that poison originates. The caller of clearSequenceCache should be ResolveIntents and the site at which it originated should be an invocation of `resolveIntents()` during conflict resolution (which happens in `processWriteIntentError`). That should set `true`, so maybe there's another path that gets there first though it shouldn't.

**Comment by tschottdorf** [comment] 2016-03-16 15:33
```
# This is the range which conflicts with the previous range (whose history is below):

Range descriptor with start key /Table/53/2/"k\xcaPe\xce\xe6I\xbc\x8af\xd9\xf8V[L\xdb"/Tue Mar 15 17:24:18 UTC 2016 at time 2016-03-15 22:38:05.667140187 -0400 EDT
range_id:92 start_key:"\275\212!k\312Pe\316\346I\274\212f\331\370V[L\333\000\001\"\371V\350EB\371\031\007\322~" end_key:"\377\377" replicas:<node_id:3 store_id:3 replica_id:1 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:2 store_id:2 replica_id:3 > next_replica_id:4

history of range #27 (reverse chronological):

# store 3 goes away
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 19:57:32.915390465 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:5 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:2 store_id:2 replica_id:6 > next_replica_id:7

# store 2 comes back
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 19:57:18.342057769 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:5 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:2 store_id:2 replica_id:6 > next_replica_id:7

# store 2 goes away (because why not)
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 19:56:08.884514045 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:5 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:6

# replicas 1, 2, 3, 4 (readded #4)
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 19:55:53.569246911 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:2 store_id:2 replica_id:4 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:5 > next_replica_id:6

# replicas 1, 2, 3 next_id 5 (rebalanced #4 away)
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 16:23:39.010442116 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:2 store_id:2 replica_id:4 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:5

# replicas 1, 2, 3, 4 next_id 5
Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 16:23:38.95187694 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:2 store_id:2 replica_id:4 > next_replica_id:5

Range descriptor with start key /Table/53/2/""/Tue Mar 15 18:23:13 UTC 2016 at time 2016-03-15 15:58:14.159086249 -0400 EDT
range_id:27 start_key:"\275\212!\000\001\"\371V\350S\021\371\033\213\340\353" end_key:"\377\377" replicas:<node_id:4 store_id:4 replica_id:1 > replicas:<node_id:1 store_id:1 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4

```

**Comment by RaduBerinde** [comment] 2016-03-16 15:39
In `resolveIntents` poison is true but there are no intents.
`clearSequenceCache` is called from the last line of EndTransaction

```
resolveIntents: 0 intents, poison=true
Restart: upgrading priority. Before: 26231
Generated priority value 855298 for priority 1.000000
Restart: upgraded priority. After:   3043697
resolveIntents: 0 intents, poison=true
I160316 11:37:33.198637 server/status/runtime.go:140  runtime stats: 56 goroutines, 4.95MiB active, 292.19cgo/sec, 0.02/0.01 %(u/s)time, 0.00 %gc (4x)
clearSequenceCache for txn 55374adc-7911-4b5e-a382-d2cc60e5c63b. poison: false
goroutine 67 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x18
github.com/cockroachdb/cockroach/storage.(*Replica).clearSequenceCache(0xc820110540, 0x7fe74c333948, 0xc8203c9aa0, 0xc8204a9008, 0x0, 0xc82039be30, 0x0, 0xc82039be40, 0x4, 0x8, ...)
	/go2/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1084 +0x168
github.com/cockroachdb/cockroach/storage.(*Replica).EndTransaction(0xc820110540, 0x7fe74c333948, 0xc8203c9aa0, 0xc8204a9008, 0x143c5d022d0cea74, 0x0, 0x100000001, 0x1, 0x1, 0x0, ...)
```

**Comment by RaduBerinde** [comment] 2016-03-16 15:46
Could it have something to do with this TODO in `maybePushTransactions`?
`// TODO(bdarnell): return resolveIntents even on error.`

Those calls do return errors, e.g. `pushErr: txn "sql/executor.go:603 sql implicit: false" id=ddc9fe09 key=/Min rw=false pri=0.67167869 iso=SERIALIZABLE stat=PENDING epo=1 ts=1458143128.783396579,0 orig=1458143128.783396579,0 max=1458143128.783396579,0 failed to push "sql/executor.go:603 sql implicit: false" id=b89447f7 key=/Table/51/1/2/0 rw=false pri=0.67167874 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458143128.761908594,0 orig=1458143128.761908594,0 max=1458143128.761908594,0`

**Comment by RaduBerinde** [comment] 2016-03-16 15:59
I think I may be looking at the wrong thing - these things happen when the transaction tries to read but cannot. The first txn doesn't get pushed, it times out - maybe that time out code doesn't do the right thing when aborting the txn.

**Comment by tschottdorf** [comment] 2016-03-16 16:10
Ok, discussed and grokked offline. @RaduBerinde is working on the fix.

**Comment by RaduBerinde** [comment] 2016-03-16 18:22
Thank you very much Toby for all the hand-holding! I will have a PR out shortly.

**Closed** 2016-03-17 20:36 UTC
Labels: bug, test-failure
