### ISSUE TITLE
kv: TestClockUpdateOnResponse goroutine leak

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7524] opened 2016-06-29 16:18 UTC
Perhaps this was the `TestOwnNodeCertain` leak I was seeing.

```
~/Development/go/src/github.com/cockroachdb/cockroach master make stress PKG=./kv TESTS=TestClockUpdateOnResponse
...
--- FAIL: TestClockUpdateOnResponse (5.05s)
	leaktest.go:86: Leaked goroutine: goroutine 46 [IO wait]:
		net.runtime_pollWait(0x9181858, 0x77, 0x4055bc0)
			/Users/pmattis/Development/go-1.6/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc8200f2140, 0x77, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitWrite(0xc8200f2140, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:82 +0x36
		net.(*netFD).connect(0xc8200f20e0, 0x0, 0x0, 0x91809f0, 0xc8201c9b80, 0xecf05eb7f, 0x166906ca, 0x6124480, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/fd_unix.go:127 +0x28e
		net.(*netFD).dial(0xc8200f20e0, 0x91809a8, 0x0, 0x91809a8, 0xc8201f22a0, 0xecf05eb7f, 0xc8166906ca, 0x6124480, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/sock_posix.go:137 +0x364
		net.socket(0x54bec40, 0x3, 0x2, 0x1, 0x0, 0xc8201f2200, 0x91809a8, 0x0, 0x91809a8, 0xc8201f22a0, ...)
			/Users/pmattis/Development/go-1.6/src/net/sock_posix.go:89 +0x429
		net.internetSocket(0x54bec40, 0x3, 0x91809a8, 0x0, 0x91809a8, 0xc8201f22a0, 0xecf05eb7f, 0x166906ca, 0x6124480, 0x1, ...)
			/Users/pmattis/Development/go-1.6/src/net/ipsock_posix.go:161 +0x153
		net.dialTCP(0x54bec40, 0x3, 0x0, 0xc8201f22a0, 0xecf05eb7f, 0xc8166906ca, 0x6124480, 0x0, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/tcpsock_posix.go:171 +0x12b
		net.dialSingle(0xc8201dc090, 0x9180940, 0xc8201f22a0, 0xecf05eb7f, 0x166906ca, 0x6124480, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:371 +0x40c
		net.dialSerial.func1(0xecf05eb7f, 0x166906ca, 0x6124480, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:343 +0x75
		net.dial(0x54bec40, 0x3, 0x9180940, 0xc8201f22a0, 0xc8201c9b60, 0xecf05eb7f, 0x166906ca, 0x6124480, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/fd_unix.go:40 +0x60
		net.dialSerial(0xc8201dc090, 0xc8200e81a0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:345 +0x7d0
		net.(*Dialer).Dial(0xc8201499b0, 0x54bec40, 0x3, 0xc82000ea00, 0xf, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:239 +0x512
		net.DialTimeout(0x54bec40, 0x3, 0xc82000ea00, 0xf, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:200 +0xa3
		google.golang.org/grpc/transport.newHTTP2Client.func1(0xc82000ea00, 0xf, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:110 +0x69
		google.golang.org/grpc/transport.newHTTP2Client(0xc82000ea00, 0xf, 0xc820149e60, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:116 +0x111
		google.golang.org/grpc/transport.NewClientTransport(0xc82000ea00, 0xf, 0xc820149e60, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/transport.go:347 +0x4d
		google.golang.org/grpc.(*Conn).resetTransport(0xc8201d4000, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:464 +0x448
		google.golang.org/grpc.NewConn.func1(0xc8201d4000)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:350 +0x2a
		created by google.golang.org/grpc.NewConn
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
FAIL


ERROR: exit status 1

142 runs completed, 1 failures, over 6s
FAIL
```

**Comment by tamird** [comment] 2016-07-05 15:46
20 minutes, 40k iters and no repro. I'm at a loss.

**Comment by petermattis** [comment] 2016-07-05 16:55
I've been running `block_writer` locally in between builds when these failures have occurred. I wonder if there is some OS level resource that `block_writer` runs are exhausting.

**Comment by bdarnell** [comment] 2016-07-05 17:03
I haven't confirmed this recently, but I've experienced severe performance degradation in either `connect()` or `accept()` locally on OSX, apparently based on the number of sockets that have been opened or closed in the last few minutes (this was in the context of an HTTP server benchmark that started out at 4k QPS and degraded to under 1k QPS after a few seconds when the client didn't reuse connections). It looks like something in the network stack is keeping track of connections in an inefficient way and performance suffers until the older connections to age out of the cache. It's possible that this is what is making the connection slow enough to make a goroutine late and count as a leak.

**Comment by tamird** [comment] 2016-07-05 19:09
https://github.com/grpc/grpc-go/pull/751

**Comment by tamird** [comment] 2016-07-13 15:24
Now that #7723 is merged, I'm going to close this. There's upstream PR in grpc.

**Closed by tamird** 2016-07-13 15:24 UTC
Labels: test-failure
