### ISSUE TITLE
sql: Schema Change Manager may infinitely retry schema changes

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#44299] opened 2020-01-23 13:47 UTC
There are at least two occasions in schema change manager code in 19.2 where errors to start or resume a job are ignored or not handled in some cases which may lead to a schema change being retried indefinitely potentially without an exponential backoff.

From https://github.com/cockroachdb/cockroach/blob/release-19.2/pkg/sql/schema_changer.go#L1007
```
	if err := sc.job.Started(ctx); err != nil {
		if log.V(2) {
			log.Infof(ctx, "Failed to mark job %d as started: %+v", *sc.job.ID(), err)
		}
		// Go through the recording motions. See comment above.
		sqltelemetry.RecordError(ctx, err, &sc.settings.SV)
	}
```

and

From https://github.com/cockroachdb/cockroach/blob/release-19.2/pkg/sql/schema_changer.go#L1981
```
			for tableID, sc := range schemaChangers {
				if timeutil.Since(sc.execAfter) > 0 {
					evalCtx := createSchemaChangeEvalCtx(ctx, s.execCfg.Clock.Now(), &SessionTracing{}, s.ieFactory)

					execCtx, cleanup := tracing.EnsureContext(ctx, s.ambientCtx.Tracer, "schema change [async]")
					err := sc.exec(execCtx, false /* inSession */, &evalCtx)
					cleanup()

					// Advance the execAfter time so that this schema
					// changer doesn't get called again for a while.
					sc.execAfter = timeutil.Now().Add(delay)
					schemaChangers[tableID] = sc

					if err != nil {
						if shouldLogSchemaChangeError(err) {
							log.Warningf(ctx, "Error executing schema change: %s", err)
						}
						if err == sqlbase.ErrDescriptorNotFound {
							// Someone deleted this table. Don't try to run the schema
							// changer again. Note that there's no gossip update for the
							// deletion which would remove this schemaChanger.
							delete(schemaChangers, tableID)
						}
					} else {
						// We successfully executed the schema change. Delete it.
						delete(schemaChangers, tableID)
					}
```
On some occasions these retires would happen every few ms which suggests that the exponential backoff logic may have a bug.
More seriously the retires on certain schema changes cause the schema changer to repeatedly acquire a lease on a table which can bloat the lease range to gigabytes and can make the cluster unresponsive. For more see https://github.com/cockroachdb/cockroach/issues/44019. And https://github.com/cockroachdb/cockroach/issues/39255 may be related.

**Expected behavior**
Multiple failures of schema changes should be detected or at least we should have sane exponential backoff to prevent accumulation of work artifacts in the system tables.

**Environment:**
 - CockroachDB version 19.2.x

**Additional context**
This bug may cause cluster to become unresponsive - unable to serve queries and to connect to the admin UI.

**Comment by lucy-zhang** [comment] 2020-01-23 22:10
Summarizing a conversation with @pbardea:

In #44019 our hypothesis was that the original job-related error originated from https://github.com/cockroachdb/cockroach/blob/2878820bc2f9ccc5f005c6ef9128ed58282b176f/pkg/sql/schema_changer.go#L646 which occurs in a callback passed to `Publish()`, which runs that callback in a transaction in a retry loop (supposedly exponential). So there are 3 layers of possible "retries":

1. the transaction used in `Publish()` can retry itself (which can't be what's happening here, since we abort the transaction due to a non-retriable error)
2. the retry loop in `Publish()` is configured incorrectly and is retrying in a tight loop without backing off (which shouldn't happen, since we just use the default retry options; in fact, we shouldn't be retrying at all unless we get `errLeaseVersionChanged`, which is not the case here):
https://github.com/cockroachdb/cockroach/blob/2878820bc2f9ccc5f005c6ef9128ed58282b176f/pkg/sql/lease.go#L378
3. the `SchemaChangeManager` is retrying, since it stores a list of `SchemaChanger`s in memory and keeps retrying them until they succeed: https://github.com/cockroachdb/cockroach/blob/878820bc2f9ccc5f005c6ef9128ed58282b176f/pkg/sql/schema_changer.go#L2239-L2248
I don't see how this would cause us to retry multiple times a second.

@spaskob is that consistent with what you've seen? It's not clear to me so far which level of retry loop we're stuck in in #44019, but maybe someone else knows.

**Comment by pbardea** [comment] 2020-01-24 20:43
After reproducing this (as described in #44019), @lucy-zhang and I determined the following was happening:

1. GC timer triggers `maybeGCMutations`
2. A lease is acquired on the table that has the drop index mutation (which successfully writes to the table descriptor)
3. The zone config for this table is updated to remove any constraint for the subzone of the index that is to be dropped.
4. `Publish` is called which does 2 things in the same transaction (which in this case is always aborted):
a. Re-writes the descriptor, removing `gc_mutations` from the descriptor.
b. Tries to lookup the job, fails and aborts the entire transaction.
5. The lease on the table is revoked (the table descriptor is written again).
Since the schema change was not completed and the `gc_mutations` were not removed from this descriptor this process repeats.

Although it is surprising to me that the GC timer is being triggered as often as it is. Will investigate that further.

**Comment by lucy-zhang** [comment] 2020-02-04 19:10
Our current understanding of the problem is that in a single iteration of the loop Paul described above, the transaction that updates the zone config is causing the system config range to be gossiped, which triggers the async schema changer on other nodes. That's probably what's causing the tight loop when the problem occurs on a multi-node cluster.

We are indeed scheduling the GC timer to go off immediately (with an `execAfter` in the past), based on the `DropTime` from the GC mutation. That update happens here: https://github.com/cockroachdb/cockroach/blob/v19.2.0/pkg/sql/schema_changer.go#L2133-L2163

Schema changes will no longer be scheduled by the `SchemaChangeManager` in 20.1, so the question is what to do about 19.2 and earlier versions. It doesn't make sense to always add a delay on running the schema change; in the normal case, if we find a `DropTime` in the past, we should try to schedule GC as soon as possible. What we actually care about is ensuring that schema changes don't get retried too soon after the most recent attempt, which would be a more complicated fix since we don't currently store the time of the most recent attempt or anything.

**Comment by lucy-zhang** [comment] 2020-02-06 18:12
I think we should consider this closed by #44607. Both incidents with retries we've seen are fixed by that PR, and the issue isn't exactly about the schema change manager retrying; it's more about triggering schema changes due to gossiped zone config updates too often, which is a situation that's specific to the bug being fixed by #44607. If anyone disagrees, we can reopen the issue.

#44720 was an attempt to patch just the schema change manager, but after offline discussions we're deprioritizing that approach since #44607 covers all known issues.

**Closed by lucy-zhang** 2020-02-06 18:12 UTC
Labels: A-bulkio, A-schema-changes, C-bug
