### ISSUE TITLE
sql: no error returned when the second statement on a line fails

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16787] opened 2017-06-29 14:07 UTC
I noticed that when a statement that fails is on the same line with a statement that doesn't fail, we don't see the error. See below.

```$ ./cockroach sql --host 13.82.91.246 --insecure -u test
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
test@13.82.91.246:26257/> SHOW USERS;
pq: user test does not have SELECT privilege on table users
test@13.82.91.246:26257/> SHOW DATABASES; SHOW USERS;
+--------------------+
|      Database      |
+--------------------+
| crdb_internal      |
| information_schema |
| pg_catalog         |
+--------------------+
(3 rows)
test@13.82.91.246:26257/> SELECT * FROM lol; SELECT * FROM lol;
pq: table "lol" does not exist
test@13.82.91.246:26257/> SHOW DATABASES; SELECT * FROM lol;
+--------------------+
|      Database      |
+--------------------+
| crdb_internal      |
| information_schema |
| pg_catalog         |
+--------------------+
(3 rows)
```

**Comment by jordanlewis** [comment] 2017-06-29 14:51
Dupe of/related to #16519

**Comment by knz** [comment] 2017-07-04 16:20
dup #16519 indeed.

**Closed by knz** 2017-07-04 16:20 UTC
