### ISSUE TITLE
sql: joinPredicate filter evalution does not take outer joins into consideration

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#12311] opened 2016-12-13 10:02 UTC
An outer join should return all rows from both tables, even those that do not match the join predicate. We currently exhibit this behavior for unmatched join indices, but we do not respect it for filters on outer joins. This leads to the following behavior, which I think is new because it is suddenly blocking Hibernate:

```
create table a (i int);
create table b (i int, b bool);
insert into a values (1), (2), (3);
insert into b values (1, false), (2, false), (3, true);

root@:26257> SELECT a.i, b.b FROM a LEFT JOIN b ON (a.i = b.i AND b.b = true);
+---+------+
| i |  b   |
+---+------+
| 3 | true |
+---+------+
(1 row)
```

The final query should instead return something like:
```
+---+------+
| i |  b   |
+---+------+
| 1 | NULL |
| 2 | NULL |
| 3 | true |
+---+------+
```

I believe the code that is causing this issue is https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/join.go#L511.

**Comment by knz** [comment] 2016-12-13 12:50
@irfansharif if you could have a look and see if the change is easy, that'd be chill.

**Comment by knz** [comment] 2016-12-13 14:53
@irfansharif never mind me, the problem is obvious :) fix underway!

**Comment by nvanbenschoten** [comment] 2016-12-14 21:16
Thanks for the bug fix @jordanlewis, this will unblock Hibernate!

I still don't think our handling of outer joins is quite correct, specifically for `FULL OUTER JOINs`. The following comparison between Cockroach and Postgres using the schema set up above demonstrates the issue.

Cockroach:
```
root@:26257> SELECT a.i, b.b FROM a FULL OUTER JOIN b ON ((a.i = b.i) AND (a.i > 0));
+---+-------+
| i |   b   |
+---+-------+
| 1 | false |
| 2 | false |
| 3 | true  |
+---+-------+
(3 rows)
root@:26257> SELECT a.i, b.b FROM a FULL OUTER JOIN b ON ((a.i = b.i) AND (a.i > 1));
+---+-------+
| i |   b   |
+---+-------+
| 1 | NULL  |
| 2 | false |
| 3 | true  |
+---+-------+
(3 rows)
```

Postgres:
```
nathan=# SELECT a.i, b.b FROM a FULL OUTER JOIN b ON ((a.i = b.i) AND (a.i > 0));
 i | b
---+---
 1 | f
 2 | f
 3 | t
(3 rows)

nathan=# SELECT a.i, b.b FROM a FULL OUTER JOIN b ON ((a.i = b.i) AND (a.i > 1));
 i | b
---+---
 1 |
 2 | f
 3 | t
   | f
(4 rows)
```

For `FULL OUTER JOINS`, I think we need similar logic to what you just added in but for when no rows on the left match the predicate for a given row on the right.

**Comment by jordanlewis** [comment] 2016-12-14 21:18
Very true - good catch and I'll send another patch.

**Comment by jordanlewis** [comment] 2016-12-14 22:34
It's not quite enough to just conditionally call `b.MarkSeen()` because there can be several distinct rows per hash bucket. In this example, if `1`, `2`, and `3` all mysteriously hashed to the same bucket, we would mark the bucket as seen as soon as we found a match, preventing us from getting to any of the non-matched right rows by the end of the join.

If you're wondering how I thought of this example, it's because there seems to be a deeper bug in hash joins that we're encountering here that causes none of the column indices to be marked as equality indices. Therefore, each of the rows hashes to the same empty string value, causing them all to be placed in the same bucket.

I filed #12358 to investigate this other issue.

**Closed** 2016-12-15 18:56 UTC
Labels: bug, orm-support
