### ISSUE TITLE
backupccl: RESTORE slowing at end

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#23509] opened 2018-03-06 21:44 UTC
During a TPCC restore, we noticed that the speed of the restore of a table slows way down near the end. Looking at a goroutine dump, a single node (out of a 24 node cluster) had hundreds of goroutines in beginLimitedRequest, which throttles import requests to one at a time.

Next question was: why did that node (node 9) have so many requests after a scatter had run. Doing a range dump for the new table, we made a histogram with the number of leader leases per node of the new table:

![ss](https://user-images.githubusercontent.com/41181/37060067-2ab01584-215d-11e8-9d79-e0a302800f9a.png)

This indeed does show node 9 having a much higher number of leader leases compared to other nodes.

Our guess is that scatter is indeed scattering, but since various restores have already happened, it is possible that scatter has no choice but to put the new ranges onto some underfull nodes, which makes the restore eventually take a long time on that node. We don't think there's any specific thing to do regarding this scatter problem at the current time.

However, we do think it's worth removing or upping the limit in beginLimitedRequest since we have some other limits during addsstable that may make the beginLimitedRequest throttling unnecessary.

Epic CRDB-6406

**Comment by mjibson** [comment] 2018-03-06 21:50
https://github.com/cockroachdb/cockroach/blob/fe8163133d5d243ae246a939e90a1dbc6f2337d1/pkg/ccl/storageccl/import.go#L40 should be changed to numcpu probably during the test.

**Comment by petermattis** [comment] 2018-03-06 22:46
I think the problem here is that scattering a small number of ranges (hundreds) in a cluster containing tens of thousands of ranges will often be a no-op. See https://github.com/cockroachdb/cockroach/issues/23358#issuecomment-370530322 for a suggestion about plumbing a new flag down to `SCATTER` so that we can force replicas to be spread out across a cluster. This would be helpful for manually ensuring a table is spread across a cluster and very helpful for `RESTORE`.

**Comment by awoods187** [comment] 2018-10-24 12:43
I observe this on all of my TPC-C restores of 10k. The last 0.2tb take ~40m when the first 2tb take 120m.

**Comment by tschottdorf** [comment] 2018-10-29 15:51
Saw this in the CPU usage graph in roachtest/restore2TB. Not sure if this is what was talked about before or if it's some replication hiccup, but here we go.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/5076964/47662242-daf90700-db9a-11e8-924f-0271f1f87754.png">

**Comment by awoods187** [comment] 2018-11-14 02:34
I can see similar things on master. For example:
![image](https://user-images.githubusercontent.com/22278911/48456107-cd8f6f80-e78b-11e8-8160-6994c56534f9.png)

The job has been at 99% for at least the last 2 hours:
![image](https://user-images.githubusercontent.com/22278911/48456121-dbdd8b80-e78b-11e8-80eb-82337b9688f4.png)

**Comment by tbg** [comment] 2018-11-14 05:08
That looks like a worse problem. Is that cluster still up?

**Comment by tbg** [comment] 2018-11-14 13:05
@awoods187 just sent me a cluster of his that had the same symptom. Not sure it's the root cause of the behavior he's seeing but the cluster had all the signs of https://github.com/cockroachdb/cockroach/pull/31875#issuecomment-438644609 which is hopefully fixed once that PR lands.

**Comment by mwang1026** [comment] 2020-11-18 18:30
cc @pbardea thoughts on how relevant this still is with the work you did in 20.2?

**Comment by pbardea** [comment] 2021-05-26 16:21
There are a few things going on here:
- AdminScatter was augmented with a flag that forces the leases of the target range to be scatter (this was added a while ago and I don't know if it was introduced after this bug was reported)
- The 20.2 refactor should enable all of the nodes to process the ranges that they're scattered as soon as they're available (ie they're not bottlenecked on other nodes)
- Further improvements based on recent restore performance investigation suggested that we could do a better job sizing the chunks that we hand out to worker nodes based on cluster size. https://github.com/cockroachdb/cockroach/pull/64067 improves that.

A lot of this issue is also covered in https://github.com/cockroachdb/cockroach/issues/63925. One thing that hasn't been benchmarked is the performance of restoring a table into a cluster that already holds a significant amount of data. My hypothesis is that the RandomizeLeases flag on the AdminScatter request should help ensure that the entries are probably distributed, but I can run a benchmark to confirm. If we see pretty even AddSSTable traffic across the nodes in that benchmark I think we can close out this issue.

**Comment by shermanCRL** [comment] 2021-06-22 19:11
We think we’ve made substantial improvements here, will close for now. There is probably more to be done, but not urgently, and can re-open if need be.

**Closed by shermanCRL** 2021-06-22 19:11 UTC
Labels: A-bulkio, C-performance, T-bulkio
