### ISSUE TITLE
Long restore of geo-distributed tpc-c 5k with storage queue errors 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#31172] opened 2018-10-10 01:13 UTC
**Describe the problem**

I ran a 9 node tpc-c multi-region deployment using tpc-c bench and roachprod. The restore of tpc-c 5k took 12+ hrs (still in progress).

**To Reproduce**

1. Ran `bin/roachtest bench '^tpccbench/nodes=9/cpu=16/multi-region$$' --wipe=false --user=andy`

**Expected behavior**
Faster restore of tpc-c 

**Additional data / screenshots**
```
E181010 00:18:26.064789 1654046 storage/queue.go:788  [raftsnapshot,n1,s1,r17845/1:/Table/57/1/2125/37396{-/0}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 26a3d630 at applied index 18 with error: [n3,s3],r17845: cannot apply snapshot: snapshot intersects existing range [n3,s3,r3484/2:/Table/5{7/1/994/…-8}]
E181010 00:18:26.132189 1654073 storage/queue.go:788  [raftsnapshot,n1,s1,r17941/1:/Table/57/1/1829/67093{-/0}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 7e83cfbb at applied index 18 with error: [n3,s3],r17941: cannot apply snapshot: snapshot intersects existing range [n3,s3,r3484/2:/Table/5{7/1/994/…-8}]
E181010 00:18:26.199505 1653933 storage/queue.go:788  [raftsnapshot,n1,s1,r18000/1:/Table/57/1/2127/45317{-/0}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 042d4d5b at applied index 18 with error: [n3,s3],r18000: cannot apply snapshot: snapshot intersects existing range [n3,s3,r3484/2:/Table/5{7/1/994/…-8}]
E181010 00:18:26.266851 1654094 storage/queue.go:788  [raftsnapshot,n1,s1,r17773/1:/Table/57/1/187{7/248…-8/288…}] snapshot failed: (n3,s3):2: remote couldn't accept Raft snapshot 27a33942 at applied index 42 with error: [n3,s3],r17773: cannot apply snapshot: snapshot intersects existing range [n3,s3,r3484/2:/Table/5{7/1/994/…-8}]
```

![image](https://user-images.githubusercontent.com/22278911/46707432-e8f4e100-cc07-11e8-9fe2-0d71a906dc05.png)

**Environment:**
 - CockroachDB version 2.1 beta on 9/17

**Comment by benesch** [comment] 2018-10-10 03:37
This is reminiscent of a stress failure in TestStoreRangeMergeWatcher (that I don’t actually suspect is related to merges). I can’t pull the issue up right now; on mobile.

**Comment by tschottdorf** [comment] 2018-10-10 11:38
@petermattis or @nvanbenschoten do you have bandwidth to take a look today? I suspect this repros quickly, but we might as well look at it while it's there.

**Comment by petermattis** [comment] 2018-10-10 16:15
I don't have time to look at it today. I should have time to look at it on Friday.

**Comment by awoods187** [comment] 2018-10-10 16:15
I tried to re-run this on the 2.1 beta from 10/08 and it didn't finish restoring before it was killed by roachprod after 13 hours. I can't get the logs because it was already destroyed but i have this:

![image](https://user-images.githubusercontent.com/22278911/46750552-36179800-cc86-11e8-89f3-59038e5ceb1f.png)

**Comment by petermattis** [comment] 2018-10-10 16:17
How long do geo-distributed restores usually take? Is this a regression, or expected?

**Comment by bdarnell** [comment] 2018-10-10 16:19
A more complete screenshot:

![image](https://user-images.githubusercontent.com/160562/46745285-c354ef80-cc7a-11e8-8a54-a36585c38ce0.png)

So we have two healthy replicas and one that needs a raft snapshot (the data it needs includes a split, which is causing other ranges to get their snapshots blocked, but doesn't appear to be the root cause). The raft log is large enough to prevent sending the snapshot, but not ridiculous (18MB). 

The two healthy replicas should be able to commit a raft log truncation to resolve this problem, but they're not. The leader's proposal quota is full. It looks like there's a kind of deadlock in `updateProposalQuotaRaftMuLocked`, in which this node is live enough to keep proposal quota tied up and allowing the log to be truncated.

**Comment by awoods187** [comment] 2018-10-10 19:03
Do you want me to keep this cluster alive? its set to expire this evening

**Comment by bdarnell** [comment] 2018-10-10 19:10
I'm OK with letting this cluster go. But try again to see if it's repeatable.

**Comment by awoods187** [comment] 2018-10-10 19:29
Alright I'm killing it now. I'll run it tomorrow morning

**Comment by awoods187** [comment] 2018-10-11 13:12
I'm re-running this same setup now and hit another bug: https://github.com/cockroachdb/cockroach/issues/31260

But more importantly, I also ran into a bunch of errors:

2018-10-11 12:41:12 | ERROR | [n1] failed attempt to acquire migration lease: lease /System/"system-version/lease" is not available until at least 1539261732.606390643,0
-- | -- | --



TIME | SEVERITY | MESSAGE | FILE:LINE
-- | -- | -- | --
2018-10-11 12:41:12 | WARNING | RUNNING IN INSECURE MODE!  - Your cluster is open for any client that can access <all your IP addresses>. - Any user, even root, can log in without providing a password. - Any user, connecting as root, can read or write any data in your cluster. - There is no network encryption nor authentication, and thus no confidentiality.  Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.1/secure-a-cluster.html | cli/start.go:1055
2018-10-11 12:41:12 | INFO | line format: [IWEF]yymmdd hh:mm:ss.uuuuuu goid file:line msg utf8=✓ | util/log/clog.go:1151
2018-10-11 12:41:12 | INFO | [config] arguments: [./cockroach start --insecure --store=path=/mnt/data1/cockroach --log-dir=/home/andrewwoods/logs --cache=25% --max-sql-memory=25% --port=26257 --http-port=26258 --locality=cloud=gce,region=us-east1,zone=us-east1-b] | util/log/clog.go:1151
2018-10-11 12:41:12 | INFO | [config] binary: CockroachDB CCL v2.1.0-beta.20181008 (x86_64-unknown-linux-gnu, built 2018/10/08 16:22:44, go1.10.3) | util/log/clog.go:1151
2018-10-11 12:41:12 | INFO | [config] running on machine: andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001 | util/log/clog.go:1151
2018-10-11 12:41:12 | INFO | [config] file created at: 2018/10/11 12:41:12 | util/log/clog.go:1151
2018-10-11 12:41:12 | INFO | available memory from cgroups (8.0 EiB) exceeds system memory 14 GiB, using system memory | server/status/recorder.go:609
2018-10-11 12:41:12 | INFO | CockroachDB CCL v2.1.0-beta.20181008 (x86_64-unknown-linux-gnu, built 2018/10/08 16:22:44, go1.10.3) | cli/start.go:1069
2018-10-11 12:41:12 | INFO | available memory from cgroups (8.0 EiB) exceeds system memory 14 GiB, using system memory | server/status/recorder.go:609
2018-10-11 12:41:12 | INFO | system total memory: 14 GiB | server/config.go:385
2018-10-11 12:41:12 | INFO | server configuration: max offset             500000000 cache size             3.5 GiB SQL memory pool size   3.5 GiB scan interval          10m0s scan min idle time     10ms scan max idle time     1s event log enabled      true | server/config.go:387
2018-10-11 12:41:12 | INFO | using local environment variables: COCKROACH_ENABLE_RPC_COMPRESSION=false, COCKROACH_BACKGROUND_RESTART=1 | cli/start.go:913
2018-10-11 12:41:12 | INFO | process identity: uid 1016 euid 1016 gid 1017 egid 1017 | cli/start.go:920
2018-10-11 12:41:12 | INFO | starting cockroach node | cli/start.go:545
2018-10-11 12:41:12 | INFO | opening rocksdb instance at "/mnt/data1/cockroach/cockroach-temp762012115" | storage/engine/rocksdb.go:574
2018-10-11 12:41:12 | INFO | [n?] monitoring forward clock jumps based on server.clock.forward_jump_check_enabled | server/server.go:848
2018-10-11 12:41:12 | INFO | opening rocksdb instance at "/mnt/data1/cockroach" | storage/engine/rocksdb.go:574
2018-10-11 12:41:12 | INFO | [n?] 1 storage engine initialized | server/config.go:493
2018-10-11 12:41:12 | INFO | [n?] RocksDB cache size: 3.5 GiB | server/config.go:496
2018-10-11 12:41:12 | INFO | [n?] store 0: RocksDB, max size 0 B, max open file limit 60536 | server/config.go:496
2018-10-11 12:41:12 | WARNING | neither --listen-addr nor --advertise-addr was specified. The server will advertise "andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001" to other nodes, is this routable?  Consider using: - for local-only servers:  --listen-addr=localhost - for multi-node clusters: --advertise-addr=<host/IP addr> | cli/start.go:887
2018-10-11 12:41:12 | INFO | [n?] **** cluster aeb26468-90d2-4d2f-9f85-99af9177cf65 has been created | server/node.go:370
2018-10-11 12:41:12 | INFO | [n?] **** add additional nodes by specifying --join=andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001:26257 | server/server.go:1412
2018-10-11 12:41:12 | INFO | [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001:26257" > attrs:<> locality:<tiers:<key:"cloud" value:"gce" > tiers:<key:"region" value:"us-east1" > tiers:<key:"zone" value:"us-east1-b" > > ServerVersion:<major_val:2 minor_val:0 patch:0 unstable:12 > build_tag:"v2.1.0-beta.20181008" started_at:1539261672562775275 | gossip/gossip.go:395
2018-10-11 12:41:12 | INFO | [n1,s1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available | storage/store.go:1559
2018-10-11 12:41:12 | INFO | [n1] initialized store [n1,s1]: disk (capacity=369 GiB, available=350 GiB, used=18 KiB, logicalBytes=7.0 KiB), ranges=1, leases=0, queries=0.00, writes=0.00, bytesPerReplica={p10=7183.00 p25=7183.00 p50=7183.00 p75=7183.00 p90=7183.00 pMax=7183.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00 pMax=0.00} | server/node.go:473
2018-10-11 12:41:12 | INFO | [n1] read 0 node addresses from persistent storage | storage/stores.go:242
2018-10-11 12:41:12 | INFO | [n1] connecting to gossip network to verify cluster ID... | server/node.go:696
2018-10-11 12:41:12 | INFO | [n1] node connected via gossip and verified as part of cluster "aeb26468-90d2-4d2f-9f85-99af9177cf65" | server/node.go:721
2018-10-11 12:41:12 | INFO | [n1] node=1: started with [<no-attributes>=/mnt/data1/cockroach] engine(s) and attributes [] | server/node.go:545
2018-10-11 12:41:12 | INFO | [n1] available memory from cgroups (8.0 EiB) exceeds system memory 14 GiB, using system memory | server/status/recorder.go:609
2018-10-11 12:41:12 | INFO | [n1] starting http server at [::]:26258 (use: andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001:26258) | server/server.go:1549
2018-10-11 12:41:12 | INFO | [n1] starting grpc/postgres server at [::]:26257 | server/server.go:1551
2018-10-11 12:41:12 | INFO | [n1] advertising CockroachDB node at andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0001:26257 | server/server.go:1552
2018-10-11 12:41:12 | WARNING | [n1] unable to get node liveness: node not in the liveness table | jobs/registry.go:315
2018-10-11 12:41:12 | INFO | [n1] received initial cluster-verification connection from {tcp andy-1539261548-tpccbench-nodes-9-cpu-16-multi-region-0003:26257} | gossip/server.go:226
2018-10-11 12:41:12 | INFO | [n1,split,s1,r1/1:/M{in-ax}] initiating a split of this range at key /System/"" [r2] | storage/replica_command.go:298
2018-10-11 12:41:12 | INFO | [n1,split,s1,r2/1:/{System/-Max}] initiating a split of this range at key /System/NodeLiveness [r3] | storage/replica_command.go:298
2018-10-11 12:41:12 | INFO | [n1] wrote 1 node addresses to persistent storage | storage/stores.go:261
2018-10-11 12:41:12 | INFO | [n1,split,s1,r3/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/NodeLivenessMax [r4] | storage/replica_command.go:298
2018-10-11 12:41:12 | INFO | [n1,split,s1,r4/1:/{System/NodeL…-Max}] initiating a split of this range at key /System/tsd [r5] | storage/replica_command.go:298
2018-10-11 12:41:12 | INFO | [n1,split,s1,r5/1:/{System/tsd-Max}] initiating a split of this range at key /System/"tse" [r6] | storage/replica_command.go:298
2018-10-11 12:41:12 | ERROR | [n1] failed attempt to acquire migration lease: lease /System/"system-version/lease" is not available until at least 1539261732.606390643,0


2018-10-11 12:41:24 | ERROR | [n1,raftsnapshot,s1,r436/1:/Table/55/1/9/8/2871{-/0}] snapshot failed: (n8,s8):2: remote couldn't accept Raft snapshot de5eca15 at applied index 16 with error: [n8,s8],r436: cannot apply snapshot: snapshot intersects existing range [n8,s8,r330/2:/Table/55/1/{7/9/11…-69/3/2…}]
-- | -- | --

**Comment by a-robinson** [comment] 2018-10-11 18:35
The first error is fixed by https://github.com/cockroachdb/cockroach/pull/31270#event-1898974564

The second is being worked on in https://github.com/cockroachdb/cockroach/issues/30064

**Comment by asubiotto** [comment] 2018-10-17 14:00
I've also been running into the same issue with a similar setup.

**Comment by tschottdorf** [comment] 2018-10-17 18:46
@asubiotto which of the issues? The stuck restore?

**Comment by tschottdorf** [comment] 2018-10-17 18:48
Probably not worth trying to repro this until https://github.com/cockroachdb/cockroach/issues/31330#issuecomment-430066026 is fixed. Also when reproing should turn merges off because of known bug at the time of writing (hopefully fixed in a few days tops): https://github.com/cockroachdb/cockroach/issues/31409#issuecomment-430581851

**Comment by asubiotto** [comment] 2018-10-17 22:58
Yes, stuck (or very slow) restore with a lot of these `snapshot intersects range` message.

**Comment by tschottdorf** [comment] 2018-10-23 20:57
@asubiotto do you still see this? As far as I can tell, we've fixed everything mentioned in this thread and I haven't been seeing this particular problem in my testing of #31409 (where before the fixes I would).

**Comment by asubiotto** [comment] 2018-10-23 21:52
Haven't tried again but planning to soon. Will update this issue when I do.

**Comment by asubiotto** [comment] 2018-11-14 22:31
Just restored tpcc 5k on a multi-region cluster with no issues so closing this one as my understanding is that all that has been mentioned has been fixed. Feel free to reopen if this is not the case.

**Closed by asubiotto** 2018-11-14 22:31 UTC
Labels: C-investigation, S-1-stability
