### ISSUE TITLE
sql/stats: provide a mechanism to disable automatic stats for a table

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#70970] opened 2021-10-01 00:13 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes injecting stats can solve a problem in a pinch. Automatic stats might clobber those injected stats. Turning off all automatic stats collection is too big of a hammer. 

**Describe the solution you'd like**
Provide some mechanism to disable automatic stats for a single table.

Epic CRDB-9059

**Comment by rytaft** [comment] 2021-10-06 17:53
This looks like a duplicate of #40989.

**Closed by rytaft** 2021-10-06 17:53 UTC
Labels: C-enhancement, T-sql-queries
