### ISSUE TITLE
Syntax error in UDF when referencing implicit row type

### ISSUE THREAD

**Issue by umanwizard** [cockroachdb/cockroach#101207] opened 2023-04-11 04:23 UTC
**To Reproduce**

```
create table t (a int);
create function f(x t) returns int as 'select $1.a + 42' language sql;
```

Output:

```
ERROR:  at or near ".": syntax error
DETAIL:  source SQL:
select $1.a + 42
         ^
```

**Expected behavior**
The function should successfully be created, and we should be able to write queries like `select f(t) from t;`.

This works in Postgres.

**Environment:**
Cockroach cloud serverless

Jira issue: CRDB-26858

**Comment by rharding6373** [comment] 2023-04-12 19:01
Thank you for the report!

This is a duplicate of https://github.com/cockroachdb/cockroach/issues/99725.

**Closed by rharding6373** 2023-04-12 19:01 UTC
Labels: C-bug, O-community, T-sql-queries
