### ISSUE TITLE
circleci: failed tests: TestRebalanceInterval

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6250] opened 2016-04-22 19:32 UTC
The following test appears to have failed:

[#16711](https://circleci.com/gh/cockroachdb/cockroach/16711):

```
=== RUN   TestRebalanceInterval
W160422 19:30:11.052591 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160422 19:30:11.054528 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
==================
WARNING: DATA RACE
Read by goroutine 25:
  github.com/cockroachdb/cockroach/util/timeutil.Now()
      /go/src/github.com/cockroachdb/cockroach/util/timeutil/time.go:51 +0x40
  github.com/cockroachdb/cockroach/util/hlc.UnixNano()
      /go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:100 +0x25
  github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock()
      /go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x54
  github.com/cockroachdb/cockroach/util/hlc.(*Clock).Now()
      /go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:183 +0x98
  github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
      /go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:205 +0x50d
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Previous write by goroutine 40:
  github.com/cockroachdb/cockroach/util/timeutil.SetTimeOffset()
      /go/src/github.com/cockroachdb/cockroach/util/timeutil/time.go:32 +0x3f
  github.com/cockroachdb/cockroach/storage.TestRebalanceInterval()
      /go/src/github.com/cockroachdb/cockroach/storage/allocator_test.go:1221 +0xe0f
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 25 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/storage.(*StorePool).start()
      /go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:227 +0xcd
  github.com/cockroachdb/cockroach/storage.NewStorePool()
      /go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:163 +0x246
  github.com/cockroachdb/cockroach/storage.createTestAllocator()
      /go/src/github.com/cockroachdb/cockroach/storage/allocator_test.go:172 +0x1a0
  github.com/cockroachdb/cockroach/storage.TestRebalanceInterval()
      /go/src/github.com/cockroachdb/cockroach/storage/allocator_test.go:1174 +0xae
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 40 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  github.com/cockroachdb/cockroach/storage_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:54 +0x22f
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:576 +0x20a
==================
--- PASS: TestRebalanceInterval (0.02s)
--
I160422 19:30:54.942708 stopper.go:352  draining; tasks left:
19     gossip/infostore.go:286
--- PASS: Example_rebalancing (1.08s)
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/storage	45.478s
=== RUN   TestBatchBasics
I160422 19:31:05.258946 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160422 19:31:05.261425 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I160422 19:31:05.281531 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160422 19:31:05.282894 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.02s)
=== RUN   TestBatchMerge
I160422 19:31:05.289609 storage/engine/rocksdb.go:137  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-22 19:33
Duplicate of #6200

**Closed by bdarnell** 2016-04-22 19:33 UTC
Labels: Robot, test-failure
