### ISSUE TITLE
CockroachDb 19.1 + Sequalize ORM V5.x Connection issue

### ISSUE THREAD

**Issue by mkharibalaji** [cockroachdb/cockroach#42364] opened 2019-11-11 12:48 UTC
Environment :  Windows 2016 Server
1 ) Install Cockroach DB 19.1
2) create a nodejs application with Sequalize ORM
3) Setup the sample database bank with a user maxroach and no ssl or insecure config in the local machine without clustering

var sequelize = new Sequelize('bank', 'maxroach', '', {
	 host: 'localhost',
    dialect: 'postgres',
    port: 26257,
    logging: console.log
});

sequelize
  .authenticate()
  .then(() => {
    console.log('Connection has been established successfully.');
  })
  .catch(err => {
    console.error('Unable to connect to the database:', err);
  });

**Expected behavior**
A Connection should have been established

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/5992474/68588482-8660bb00-0481-11ea-8674-86e0812fbe3b.png)

**Comment by rafiss** [comment] 2019-11-11 20:01
@mkharibalaji Thanks for the report. With the code sample you provided, sequelize should be logging the SQL query it is generating. Can you find the query (or queries), and share them here?

When I run your code sample, it works, though so far I have only tried on MacOS.

```
$ node sequelize-repro.js
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize-cockroachdb/node_modules/sequelize/lib/sequelize.js:245:13
Executing (default): SELECT 1+1 AS result
Connection has been established successfully.
```

**Comment by rafiss** [comment] 2020-04-21 20:22
I'm going to close this since we haven't been able to reproduce it. @mkharibalaji, please open it again if you'd like us to investigate more!

**Closed by rafiss** 2020-04-21 20:22 UTC
Labels: A-sql-pgcompat, C-investigation, O-community
