### ISSUE TITLE
build: unit tests CI job failed with nil pointer

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#111062] opened 2023-09-21 17:13 UTC
Seen here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/11873883?expandBuildProblemsSection=true&hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true

```
  ERROR: /go/src/github.com/cockroachdb/cockroach/pkg/sql/opt/norm/BUILD.bazel:67:8: GoCompilePkg pkg/sql/opt/norm/rowflow.recompile890.a failed: (Exit 1): builder failed: error executing command (from target //pkg/sql/opt/norm:norm_test) bazel-out/k8-opt-exec-2B5CBBC6/bin/external/go_sdk/builder_reset/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags bazel,gss,bazel,gss -src pkg/sql/rowflow/input_sync.go -src ... (remaining 67 arguments skipped)
  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
  compilepkg: panic: runtime error: invalid memory address or nil pointer dereference
  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e87fc]
  goroutine 136 [running]:
  go/types.methodSet.add(0xc121a0?, {0x0, 0x2, 0x0?}, {0x0, 0x0, 0x0?}, 0x0?, 0xbb?)
    GOROOT/src/go/types/methodset.go:214 +0xdc
  go/types.NewMethodSet({0xc121a0?, 0xc000bd3810?})
    GOROOT/src/go/types/methodset.go:150 +0x869
  golang.org/x/tools/go/types/typeutil.(*MethodSetCache).lookupNamed(0xc001954020, 0xc000bd3810)
    golang.org/x/tools/go/types/typeutil/external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:66 +0x99
  golang.org/x/tools/go/types/typeutil.(*MethodSetCache).MethodSet(0xc001954020, {0xc121a0?, 0xc000bd3810?})
    golang.org/x/tools/go/types/typeutil/external/org_golang_x_tools/go/types/typeutil/methodsetcache.go:37 +0xe5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121a0?, 0xc000bd3810?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:194 +0xf5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc000bdbb18?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121c8?, 0xc000bf4210?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:211 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc000c74738?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121c8?, 0xc000bf4520?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:211 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc000c74db0?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121a0?, 0xc0001e0000?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:211 +0x1d0
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc000c74e10?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121a0?, 0xc000427f10?}, 0x0, 0xfb2d48?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:212 +0x1f7
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12240?, 0xc000cfbef0?}, 0x1, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:258 +0x6b6
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121a0?, 0xc0001ae380?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:251 +0x589
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121c8?, 0xc000d77540?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:223 +0x5d1
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc00185c870?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121c8?, 0xc0025fb870?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:212 +0x1f7
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc12268?, 0xc002665a10?}, 0x0, 0xfb2d40?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:263 +0x7f5
  golang.org/x/tools/go/ssa.(*Program).needMethods(0xc001954000, {0xc121f0?, 0xc00296fa40?}, 0x0, 0x503a3e?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:239 +0x314
  golang.org/x/tools/go/ssa.(*Program).needMethodsOf(0xc001954000, {0xc121f0?, 0xc00296fa40?}, 0x2a00000000000180?)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/methods.go:175 +0x7f
  golang.org/x/tools/go/ssa.(*Package).build(0xc003025c00)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/builder.go:2479 +0x13f
  sync.(*Once).doSlow(0xc001954000?, 0xc0003c1860?)
    GOROOT/src/sync/once.go:74 +0xc2
  sync.(*Once).Do(...)
    GOROOT/src/sync/once.go:65
  golang.org/x/tools/go/ssa.(*Package).Build(...)
    golang.org/x/tools/go/ssa/external/org_golang_x_tools/go/ssa/builder.go:2455
  golang.org/x/tools/go/analysis/passes/buildssa.run(0xc002ae45b0)
    golang.org/x/tools/go/analysis/passes/buildssa/external/org_golang_x_tools/go/analysis/passes/buildssa/buildssa.go:73 +0x1a8
  main.(*action).execOnce(0xc00023e000)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:353 +0x843
  sync.(*Once).doSlow(0x0?, 0x0?)
    GOROOT/src/sync/once.go:74 +0xc2
  sync.(*Once).Do(...)
    GOROOT/src/sync/once.go:65
  main.(*action).exec(0x0?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:280 +0x3d
  main.execAll.func1(0x0?)
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:274 +0x54
  created by main.execAll
    main/external/io_bazel_rules_go/go/tools/builders/nogo_main.go:272 +0x47
  [12,142 / 15,102] 431 / 696 tests, 1 failed; checking cached actions
  INFO: Elapsed time: 384.932s, Critical Path: 327.74s
  INFO: 11304 processes: 1895 internal, 108 local, 9301 processwrapper-sandbox.
  FAILED: Build did NOT complete successfully
  FAILED: Build did NOT complete successfully
  ERROR: exit status 1
```

**Comment by rickystewart** [comment] 2023-09-21 17:15
Dupe of #99988

**Closed by rickystewart** 2023-09-21 17:15 UTC
Labels: C-bug, C-test-failure, T-dev-inf
