### ISSUE TITLE
sql: sql tests time out due to delays in TestParallel and/or TestLogic

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#5376] opened 2016-03-18 15:03 UTC
```
panic: test timed out after 1m10s
...
goroutine 18395 [chan receive]:
github.com/cockroachdb/cockroach/sql_test.(*parallelTest).run(0xc82063e060, 0xc82030a120, 0x1a)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:144 +0x9aa
github.com/cockroachdb/cockroach/sql_test.TestParallel(0xc8202a8000)
	/go/src/github.com/cockroachdb/cockroach/sql/parallel_test.go:174 +0x436
testing.tRunner(0xc8202a8000, 0x2316cd8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892
...
```

**Comment by vivekmenezes** [comment] 2016-03-18 15:07
https://circleci.com/gh/cockroachdb/cockroach/14720?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by vivekmenezes** [comment] 2016-03-18 15:07
https://circleci.com/gh/cockroachdb/cockroach/14717

**Comment by RaduBerinde** [comment] 2016-03-18 18:34
I noticed this too the other day and I reduced the number of txns in the
test, as part of a PR I merged today. I'll keep my eye on it and close if
it's ok. Something seemingly did change recently though because it used to
be fast, I will do a bisect to try to pinpoint it.

**Comment by RaduBerinde** [comment] 2016-03-18 19:54
I did a git bisect and it found this commit:
https://github.com/cockroachdb/cockroach/commit/aedb0e9792f51323ebb69bf65c3fa271cbd2e546 (Added high-content benchmarks and fixed starvation bugs)

@spencerkimball @tschottdorf This is a test where three clients all do `INSERT INTO T VALUES ((SELECT MAX(k+1) FROM T))` 50 times in a row.

At the commit right before this change, I the test was taking 0.5s:

```
root@radu-pc-linux (58b2418) ~/roach # make test PKG=./sql TESTS=TestParallel TESTTIMEOUT=10s
..
ok  	github.com/cockroachdb/cockroach/sql	0.464s
ok  	github.com/cockroachdb/cockroach/sql	0.539s
```

At this commit it consistently takes 24s:
```
root@radu-pc-linux (aedb0e9) ~/roach # make test PKG=./sql TESTS=TestParallel
ok  	github.com/cockroachdb/cockroach/sql	24.032s
ok  	github.com/cockroachdb/cockroach/sql	23.948s
```

This is a huge regression, I think we should look at the change again.

On master I changed the test to do 10 txns instead of 50 and it still takes 12s (which is slow but should be enough to avoid the timeout failure).

**Comment by RaduBerinde** [comment] 2016-03-18 20:25
It looks like everything is fast except a transaction or two which stall for 10+ seconds.

Here is a log with verbosity 1, this txn stalls for 11 secs: https://gist.github.com/RaduBerinde/21292d7569fd1d9021cb#file-gistfile1-txt-L216

**Comment by andreimatei** [comment] 2016-03-18 20:29
It's probably just an exponential backoff getting unlucky. As we know
already, we need to do something about these exponential backoffs.

**Comment by tschottdorf** [comment] 2016-03-18 20:32
No, I don't think that's an exponential backoff going unlucky. A 10s stall usually means that something bangs against a running transaction until that transaction's record times out (the log seems to corroborate that).

**Comment by RaduBerinde** [comment] 2016-03-19 23:21
Same delays observed in TestLogic, see #5394

**Closed** 2016-03-24 17:37 UTC
Labels: bug
