### ISSUE TITLE
backupccl: write SQL migration to mark system tables not backed up as `exclude_data_from_backup`

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#80866] opened 2022-05-02 13:41 UTC
We should write a sql migration that alters system tables which we never want to be able to backup with the `exclude_data_from_backup` bit set on their descriptors. This ensures that a cluster or system database backup does not hold up GC on these tables by virtue of the protected timestamp records they will write during the backup, though it also makes it impossible to backup the contents such tables, even explicitly/directly, so this is not something we likely want to do wholesale either. 

Epic CRDB-35306

Jira issue: CRDB-15476

**Comment by irfansharif** [comment] 2022-08-23 00:10
Is this something we're looking to do for 22.2?

**Comment by dt** [comment] 2024-02-28 21:15
This came up recently in https://github.com/cockroachlabs/support/issues/2826.

Lease is probably a priority given its high rate of churn, but the foundations team might know of other system tables they'd want to mark as unbackupable and thus not subject to backup's PTS.

**Comment by rafiss** [comment] 2024-02-29 17:07
> but the foundations team might know of other system tables they'd want to mark as unbackupable and thus not subject to backup's PTS

do we already have that list, thanks to the `shouldIncludeInClusterBackup` flag?

https://github.com/cockroachdb/cockroach/blob/73f847f59bf90e880dd1afc8b801c2a16293f3a1/pkg/ccl/backupccl/system_schema.go#L625-L631

**Comment by msbutler** [comment] 2024-03-01 16:27
@rafiss yes exactly. Though once this bug is fixed, perhaps backupccl should rely on the schema of each system table.

**Comment by msbutler** [comment] 2024-03-01 16:45
I think we'd have to deal with a circular dependency, but that's fine. More general question: Do we need to backport this?

**Comment by dt** [comment] 2024-03-01 16:49
> do we already have that list, thanks to the shouldIncludeInClusterBackup flag?

Actually these aren't quite the same thing. Specifically, `shouldIncludeInClusterBackup` is whether or not we actively back it up in a cluster backup. Anything that is backed up must _not_ use `exclude_data_from_backup` obviously, but the inverse isn't implied: just because a table isn't included in cluster backups doesn't necessarily mean we should make it impossible to back it up, even manually, which setting it as `exclude_data_from_backup` would do.

**Comment by rafiss** [comment] 2024-03-01 16:53
> just because a table isn't included in cluster backups doesn't necessarily mean we should make it impossible to back it up, even manually, which setting it as exclude_data_from_backup would do.

Isn't it true that system tables are meant for internal-use only, and not part of our stable APIs? Why would we want to support a use case of manually backing up reserved tables that we don't document?

**Comment by dt** [comment] 2024-03-01 17:06
> why would we want to support a use case of manually backing up reserved tables

I expanded the comment to mention this, but *we* have used such backups in the past, either requesting them from a customer as part of debugging something to be able to reproduce it, or when we're about to do surgery on a table, etc.

But there's also a more serious correctness issue as well: spans that set this flag get elided _including during tenant backups_. If this flag is applied to system.descriptor or system.jobs -- neither of which are included in cluster backups -- restored tenants would have empty descriptor or jobs tables after being restored, despite the data in those spans still being there.

This flag can only be safely set on truly *ephemeral* data. Put another way, it must be safe to erase the content of any table that uses this flag while all are stopped and then restart the nodes. That's true of `leases`, but not many of the other system tables that aren't included in cluster backups.

**Comment by Arivijay** [comment] 2024-03-06 18:56
@dt 
Thanks for highlighting the criticality around excluding system.leases from backups. Could you advise on the process and timeline for assessing the feasibility and safety of this exclusion? I would like to give the customer a rough ETA.

**Comment by rafiss** [comment] 2024-03-07 22:13
Closing this since https://github.com/cockroachdb/cockroach/pull/119947 has been merged. As mentioned above, this is a more targeted change that only sets exclude_data_from_backup for the tables that have been explicitly configured to have a smaller gc.ttl.

SQL Foundations won't be able to own a full audit of all the system tables at this time. IMO, the team who created each specific system table is best equipped to determine if that table should be excluded from backups / protected timestamps.

**Comment by rafiss** [comment] 2024-03-08 15:48
reopening since https://github.com/cockroachdb/cockroach/pull/119947 is being reverted for now. (see https://github.com/cockroachdb/cockroach/issues/120122)

**Comment by rafiss** [comment] 2024-03-08 17:50
https://github.com/cockroachdb/cockroach/pull/120144 will reapply the change, but should not be merged until https://github.com/cockroachdb/cockroach/issues/120122 is resolved.

**Comment by rafiss** [comment] 2024-03-22 18:16
I am reverting the change again (https://github.com/cockroachdb/cockroach/pull/120901). Using exclude_data_from_backup seems to have made `ALTER RANGE ... RELOCATE` flaky under multitenancy. (see https://github.com/cockroachdb/cockroach/issues/120847 and https://github.com/cockroachdb/cockroach/issues/120772).

**Comment by rafiss** [comment] 2024-03-22 18:17
This feels too risky to include in v24.1 at this point.

**Comment by rafiss** [comment] 2024-03-25 17:00
Actually, i think those tests just need to have the split queues disabled, since they need exact control over where replicas go. So, I'm not reverting this (see latest patch in https://github.com/cockroachdb/cockroach/pull/120901)

**Closed by rafiss** 2024-03-25 17:00 UTC
Labels: C-enhancement, O-support, T-sql-foundations, P-3
