### ISSUE TITLE
kv: general test flakiness due to Pebble close error

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#51544] opened 2020-07-17 09:08 UTC
**Describe the problem**

`make stress PKG=./pkg/kv/kvclient/kvcoord` is failing reliably with the following stack trace:

```
panic: pebble: closed [recovered]
        panic: pebble: closed [recovered]
        panic: pebble: closed

goroutine 9311 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc001803b00, 0x1702240, 0xc000431680)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:183 +0x11f
panic(0x9b3820, 0xc0002931a0)
        /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Send.func1(0xc000b1af58, 0xc000b1afe0, 0xc000b1afd8, 0xc000476e00)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_send.go:103 +0x1e6
panic(0x9b3820, 0xc0002931a0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/cockroachdb/pebble.(*DB).newIterInternal(0xc000441500, 0x177b5a0, 0xc000bf8280, 0x0, 0x0, 0x0, 0xc00095c370, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:668 +0xd94
github.com/cockroachdb/pebble.(*Batch).NewIter(0xc00043b180, 0xc00095c370, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/batch.go:675 +0x1df
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleIterator).init(0xc00095c368, 0x16e6680, 0xc00043b180, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_iterator.go:125 +0x46b
github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).NewIterator(0xc00095c340, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble_batch.go:207 +0x14f
github.com/cockroachdb/cockroach/pkg/storage.MVCCGet(0x1702300, 0xc001d389c0, 0x82ece9408, 0xc001204780, 0xc0004461c0, 0x26, 0x40, 0x0, 0x0, 0xc000000000, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:754 +0x9b
github.com/cockroachdb/cockroach/pkg/storage.MVCCGetProto(0x1702300, 0xc001d389c0, 0x82ece9408, 0xc001204780, 0xc0004461c0, 0x26, 0x40, 0x0, 0x0, 0x173e060, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/storage/mvcc.go:630 +0xd7
github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval.EndTxn(0x1702300, 0xc001d389c0, 0x82ed61598, 0xc001204780, 0x179c260, 0xc00038b000, 0x7b, 0x3, 0x100000001, 0x1, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/batcheval/cmd_end_transaction.go:200 +0x309
github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateCommand(0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0x0, 0x82ed61598, 0xc001204780, 0x179c260, 0xc00038b000, 0xc000734000, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_evaluate.go:471 +0x235
github.com/cockroachdb/cockroach/pkg/kv/kvserver.evaluateBatch(0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0x82ed61598, 0xc001204780, 0x179c260, 0xc00038b000, 0xc000734000, 0xc000bf8080, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_evaluate.go:241 +0x3c2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWrapper(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0x179c260, 0xc00038b000, 0xc000734000, 0xc000bf8080, 0xc0012043c0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:557 +0x144
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatchWithServersideRefreshes(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0x179c260, 0xc00038b000, 0xc000734000, 0xc000bf8080, 0xc0012043c0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:526 +0x135
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateWriteBatch(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0xc000bf8080, 0xc0012043c0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:349 +0x212
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evaluateProposal(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0xc000bf8080, 0xc0012043c0, 0x0, 0xc000aa5600, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:735 +0x127
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).requestToProposal(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc00058a190, 0x8, 0xc000bf8080, 0xc0012043c0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_proposal.go:855 +0x8e
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc000bf8080, 0xc000744000, 0xc000b1a330, 0x0, 0x0, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_raft.go:73 +0xee
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc000bf8080, 0x0, 0x0, 0xc0004b2da0, 0x100000001, 0x1, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_write.go:133 +0x769
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries(0xc00038b000, 0x1702300, 0xc001d389c0, 0xc000bf8080, 0xdfed58, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:275 +0x3e7
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithRangeID(0xc00038b000, 0x1702300, 0xc001d38990, 0x2, 0xc000bf8080, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:95 +0x6b2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send(0xc00038b000, 0x1702300, 0xc001d38990, 0x7b, 0x3, 0x100000001, 0x1, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_send.go:37 +0x91
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Send(0xc000476e00, 0x1702300, 0xc001d38810, 0x7b, 0x3, 0x100000001, 0x1, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/store_send.go:194 +0x5a2
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).Send(0xc000caf300, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x100000001, 0x1, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores.go:177 +0xed
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*senderTransport).SendNext(0xc000b04000, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x100000001, 0x1, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:299 +0x21e
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*localTestClusterTransport).SendNext(0xc000f200a0, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/local_test_cluster_util.go:44 +0x8f
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas(0xc000578840, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1795 +0x6b1
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch(0xc000578840, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1459 +0x305
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).divideAndSendBatchToRanges(0xc000578840, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1099 +0x18ef
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).Send(0xc000578840, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:739 +0x8e4
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnLockGatekeeper).SendLocked(0xc00014cd38, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_lock_gatekeeper.go:86 +0x11c
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnMetricRecorder).SendLocked(0xc00014cd00, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_metric_recorder.go:46 +0x8d
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnCommitter).SendLocked(0xc00014ccd0, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_committer.go:190 +0x53b
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc00014cc38, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:247 +0x9b
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSpanRefresher).SendLocked(0xc00014cc38, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_span_refresher.go:182 +0x180
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnPipeliner).SendLocked(0xc00014cb78, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go:252 +0x159
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnSeqNumAllocator).SendLocked(0xc00014cb58, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_seq_num_allocator.go:105 +0x20c
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*txnHeartbeater).SendLocked(0xc00014cab8, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_interceptor_heartbeater.go:172 +0x1a9
github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*TxnCoordSender).Send(0xc00014c900, 0x1702300, 0xc001d38810, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/txn_coord_sender.go:499 +0x3cc
github.com/cockroachdb/cockroach/pkg/kv.(*DB).sendUsingSender(0xc000caf400, 0x17022c0, 0xc001204360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:742 +0x122
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).Send(0xc0016e6360, 0x17022c0, 0xc001204360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:911 +0x11e
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).rollback.func1.1(0x17022c0, 0xc001204360, 0xb2d05e00, 0x17022c0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:733 +0x98
github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout(0x17022c0, 0xc001204360, 0xc8b302, 0x12, 0xb2d05e00, 0xc000bcee68, 0x0, 0x0)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135 +0x9e
github.com/cockroachdb/cockroach/pkg/kv.(*Txn).rollback.func1(0x1702240, 0xc000431680)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:732 +0x14b
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1(0xc001803b00, 0x1702240, 0xc000431680, 0xc000d34020, 0x16, 0x0, 0x0, 0xc001d78140)
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:323 +0xee
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask
        /data/home/kena/src/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:318 +0x131
```

**To Reproduce**

```
make stress PKG=./pkg/kv/kvclient/kvcoord
```

Jira issue: CRDB-4032

**Comment by knz** [comment] 2020-07-17 09:12
cc @tbg @petermattis for triage.

**Comment by knz** [comment] 2020-07-17 09:13
I am going to bisect this and see when it came from.

**Comment by knz** [comment] 2020-07-17 09:20
This commit seems OK: 12b58af06d9104bc585bc0773bbe29d68ff2d826

Will bisect between now and then.

**Comment by knz** [comment] 2020-07-17 10:30
I have tried very hard to use `git bisect` to get to the root cause and every time `git bisect` comes to the conclusion I have contradictory outputs.

It may be that our Makefile / Go dependency tracking is not right so that when I switch branches, I am not re-building the vendor dir properly.

**Comment by knz** [comment] 2020-07-17 10:30
I will not investigate this further myself.

**Comment by knz** [comment] 2020-07-17 10:47
For reference this one is very probably OK, after running from a clean repo:

[91ae9bc70d00868e46c83139c0e5621e4e4971f3] Merge #51232 #51299

**Comment by knz** [comment] 2020-07-17 10:53
(I'm re-running my bisect session with 'make clean' in-between each step, just to be sure)

**Comment by knz** [comment] 2020-07-17 11:17
Here's my latest bisect log:

```
# bad: [af0031e3004327b8d09e23e99eb9659abf7d82de] Merge #51375 #51520
# good: [753fe8f51291aff12e4dad5a6fc850988c25dd82] Merge #51235
git bisect start 'master' '753fe8f51291aff12e4dad5a6fc850988c25dd82'
# good: [d0c79625eda85d3aa38afad5b0254d419a9bc4cd] Merge #51023 #51154 #51256 #51303
git bisect good d0c79625eda85d3aa38afad5b0254d419a9bc4cd
# good: [91ae9bc70d00868e46c83139c0e5621e4e4971f3] Merge #51232 #51299
git bisect good 91ae9bc70d00868e46c83139c0e5621e4e4971f3
# good: [2f05eb02306768de6d8c35310851c5d4684d55a5] geoviz: add improvements
git bisect good 2f05eb02306768de6d8c35310851c5d4684d55a5
# good: [2d21db0fca674cd448c1d9d2bf14c53244de56f3] builtins: add underscore variant for each index builtin
git bisect good 2d21db0fca674cd448c1d9d2bf14c53244de56f3
# good: [2d21db0fca674cd448c1d9d2bf14c53244de56f3] builtins: add underscore variant for each index builtin
git bisect good 2d21db0fca674cd448c1d9d2bf14c53244de56f3
# good: [2d21db0fca674cd448c1d9d2bf14c53244de56f3] builtins: add underscore variant for each index builtin
git bisect good 2d21db0fca674cd448c1d9d2bf14c53244de56f3
# good: [f00c3ff59db097746011ffb1586fd4ce67f5596d] Merge #51225 #51311
git bisect good f00c3ff59db097746011ffb1586fd4ce67f5596d
# bad: [9062cb0fb03e7af73745601e5ad44f3b8b87d519] Merge #50771
git bisect bad 9062cb0fb03e7af73745601e5ad44f3b8b87d519
# bad: [51398fb4a822bb9257ddba87682380ec0745f6ae] Merge #51327
git bisect bad 51398fb4a822bb9257ddba87682380ec0745f6ae
# bad: [0f36c8df07b6d7f948989a68926141b1e9866368] Merge #51351
git bisect bad 0f36c8df07b6d7f948989a68926141b1e9866368
# bad: [a215af7dd3a7387a4454082c27c1528ff54b1698] Merge #51319
git bisect bad a215af7dd3a7387a4454082c27c1528ff54b1698
# good: [d86e265eb443e9eeac8a743ad558b5bfa58e3720] kv: consolidate RangeInfos in RPC responses
git bisect good d86e265eb443e9eeac8a743ad558b5bfa58e3720
# good: [3a299690b26b528a1fdbf28865e1bc81ae697264] Merge #51310
git bisect good 3a299690b26b528a1fdbf28865e1bc81ae697264
# good: [dfdd8bb563dd7f6899c96a963a3906257784c135] geoviz: expose --geo_libs flag
git bisect good dfdd8bb563dd7f6899c96a963a3906257784c135
# bad: [a9e9c9cdf75f07c51dfca3773305d4af379c5fb7] Merge #51168
git bisect bad a9e9c9cdf75f07c51dfca3773305d4af379c5fb7
# first bad commit: [a9e9c9cdf75f07c51dfca3773305d4af379c5fb7] Merge #51168
```

This points to #51168 as the culprit, but I don't understand how it causes the problem.

Maybe someone else needs to re-run the bisect to confirm.

**Comment by knz** [comment] 2020-07-17 11:18
The problem with this bisect result is the following:

- the merge commit a9e9c9cdf75f07c51dfca3773305d4af379c5fb7 triggers the bug
- however the only commit inside that branch, d86e265eb443e9eeac8a743ad558b5bfa58e3720, does not.

(This is why I wrote it's incosnsitent)

**Comment by tbg** [comment] 2020-07-17 12:40
Raphael I have a PR out about this. It doesn't fix all of the causes but
provides a tool for doing so.

**Comment by tbg** [comment] 2020-07-17 14:59
Looking at this with Andrei. Like you suggested it's probably https://github.com/cockroachdb/cockroach/pull/51310/files exposing an existing problem.

**Comment by andreimatei** [comment] 2020-07-24 16:24
Hopefully this was fixed enough by #51413

**Comment by ajwerner** [comment] 2020-08-08 00:50
I hit this on a freshly rebased branch here: https://teamcity.cockroachdb.com/viewLog.html?buildId=2161675&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test

**Comment by ajwerner** [comment] 2020-08-08 01:08
One thing I'll note is that we seem to lack synchronization that all of our outstanding grpc requests have concluded when the stopper stops. This seems like a problem. 

It seems like we should add something to the server shutdown code that prevents new requests and wait for outstanding requests on certain grpc services. In particular `Batch` and `RangeFeed` from `Internal` and others like `PerReplicaClient`

**Comment by andreimatei** [comment] 2020-08-08 04:31
I'll get new energy on https://github.com/cockroachdb/cockroach/pull/51566

**Comment by ajwerner** [comment] 2020-08-14 16:00
https://teamcity.cockroachdb.com/viewLog.html?buildId=2182751&buildTypeId=Cockroach_UnitTests_Test&tab=artifacts#%2Fraw.0.json.txt.tgz here's another

**Comment by ajwerner** [comment] 2020-10-02 14:17
The vast majority of these seem to have to do with range merges happening after shutdown.

**Comment by jbowens** [comment] 2022-08-15 21:28
Closing out as unactionable. I think most instances have been fixed throughout the cockroach repo.

**Closed by jbowens** 2022-08-15 21:28 UTC
Labels: C-test-failure, S-3-productivity, T-storage
