### ISSUE TITLE
TestGetFirstRangeDescriptor is Flaky

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#1588] opened 2015-06-30 20:13 UTC
From https://circleci.com/gh/cockroachdb/cockroach/4344

```
I0630 19:46:27.572287     308 gossip.go:500] client disconnected: client.go:186: stopping outgoing client 3 @ /tmp/unix-socket908118202; already have incoming
W0630 19:46:27.572483     308 gossip.go:518] missing sentinel gossip 3; assuming partition and reconnecting
W0630 19:46:27.573747     308 gossip.go:518] missing sentinel gossip 3; assuming partition and reconnecting
I0630 19:46:27.576918     308 client.go:121] client /tmp/unix-socket065643080 connected
I0630 19:46:27.577189     308 client.go:121] client /tmp/unix-socket065643080 connected
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xaafa36]

goroutine 231 [running]:
github.com/cockroachdb/cockroach/proto.FromNetAddr(0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/proto/gossip.go:29 +0x36
github.com/cockroachdb/cockroach/gossip.(*client).gossip(0xc20810b860, 0xc20810c750, 0xc2080ae6c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:124 +0x5e9
github.com/cockroachdb/cockroach/gossip.funcÂ·001()
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:85 +0x320
github.com/cockroachdb/cockroach/util.funcÂ·001()
--
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:74 +0x5f1
github.com/cockroachdb/cockroach/util.funcÂ·001()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:75 +0x80
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:76 +0x133
FAIL	github.com/cockroachdb/cockroach/kv	0.937s
=== RUN TestHeartbeatSingleGroup
--- PASS: TestHeartbeatSingleGroup (0.34s)
=== RUN TestHeartbeatMultipleGroupsJointLeader
--- PASS: TestHeartbeatMultipleGroupsJointLeader (0.03s)
=== RUN TestHeartbeatResponseFanout
I0630 19:46:29.606867     318 heartbeat_test.go:377] SubmitCommand succeed after Heartbeat Response fanout
E0630 19:46:29.612524     318 transport.go:202] sending rpc failed: read tcp 127.0.0.1:45308: use of closed network connection
E0630 19:46:29.612877     318 transport.go:202] sending rpc failed: read tcp 127.0.0.1:45308: use of closed network connection
E0630 19:46:29.613204     318 transport.go:202] sending rpc failed: read tcp 127.0.0.1:39913: use of closed network connection
E0630 19:46:29.613486     318 transport.go:202] sending rpc failed: read tcp 127.0.0.1:39913: use of closed network connection
```

This doesn't appear to have failed on master yet, but i'm guessing its only a matter of time.

**Comment by tschottdorf** [comment] 2015-06-30 20:32
duplicate of #1563

**Closed by tschottdorf** 2015-06-30 20:32 UTC
Labels: test-failure
