### ISSUE TITLE
kv: closed timestamp regression on drt-large

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#122016] opened 2024-04-09 14:55 UTC
Nodes 6 and 9 of the `drt-large` cluster went down last night with closed timestamp regressions

```
F240409 07:59:27.429493 109583 kv/kvserver/replica_closedts.go:263 ⋮ [T1,Vsystem,n6] 770841  side-transport update saw closed timestamp regression on r16472: (lai=2548, ts=1712649563.889408923,0) -> (lai=2547, ts=1712649564.426571698,0)
```

and

```
F240409 02:44:44.184257 8190663 kv/kvserver/replica_closedts.go:263 ⋮ [n23] 341041  side-transport update saw closed timestamp regression on r29677: (lai=287, ts=1712630678.676057292,0) -> (lai=286, ts=1712630680.929988206,0)
```

Logs are on the respective nodes.

Jira issue: CRDB-37665

**Comment by kvoli** [comment] 2024-04-09 15:08
This can probably be closed as a duplicate of #121480. The LAI regression looks the same.

**Comment by nvanbenschoten** [comment] 2024-04-09 16:21
> This can probably be closed as a duplicate of https://github.com/cockroachdb/cockroach/issues/121480. The LAI regression looks the same.

While we have this second reproduction, it would be useful to determine which aspects mirror the failure in #121480 and which aspects do not. For instance, in https://github.com/cockroachdb/cockroach/issues/121480#issuecomment-2032726685, you said we saw two lease transfers in rapid succession. Do we see that here as well?

**Comment by kvoli** [comment] 2024-04-09 18:21
For `r16472` there wasn't a lease transfer, but the lease was re-applied multiple times with a multi-second replication lag prior to the closed TS regression:

```python
W240409 07:59:25.338283 4245 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 57297  applied lease after ~3.67s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=670 start=1712649561.670877828,0 exp=1712649567.670824057,0 pro=1712649561.670824057,0 prev=repl=(n31,s467):34 seq=669 start=1712649560.697935728,0 epo=4 pro=1712649560.697935728,0]
F240409 07:59:27.429493 109583 kv/kvserver/replica_closedts.go:263 ⋮ [T1,Vsystem,n6] 770841  side-transport update saw closed timestamp regression on r16472: (lai=2548, ts=1712649563.889408923,0) -> (lai=2547, ts=1712649564.426571698,0)
```

<details><summary>r16472</summary>
<p>

```python
I240409 07:58:25.626026 4251 kv/kvserver/store_raft.go:699 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 769650  raft ready handling: 1.12s [append=0.00s, apply=0.00s, sync=1.12s, other=0.00s], wrote [append-batch=107 B, append-ent=0 B (1), ] pebble stats: [commit-wait 1.115753609s sem 248ns]; node might be overloaded
W240409 07:59:19.195437 4249 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 770678  applied lease after ~1.92s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=666 start=1712649557.278405228,0 exp=1712649563.278359720,0 pro=1712649557.278359720,0 prev=repl=(n31,s467):34 seq=665 start=1712649557.197546833,0 epo=4 pro=1712649557.197546833,0]
W240409 07:59:25.338283 4245 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 770799  applied lease after ~3.67s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=670 start=1712649561.670877828,0 exp=1712649567.670824057,0 pro=1712649561.670824057,0 prev=repl=(n31,s467):34 seq=669 start=1712649560.697935728,0 epo=4 pro=1712649560.697935728,0]
I240409 07:25:31.025069 4263 kv/kvserver/replica_raft.go:1621 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 742345  slow non-blocking raft commit: commit-wait 775.616352ms sem 851ns
W240409 07:59:19.195437 4249 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 57275  applied lease after ~1.92s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=666 start=1712649557.278405228,0 exp=1712649563.278359720,0 pro=1712649557.278359720,0 prev=repl=(n31,s467):34 seq=665 start=1712649557.197546833,0 epo=4 pro=1712649557.197546833,0]
W240409 07:59:25.338283 4245 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 57297  applied lease after ~3.67s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=670 start=1712649561.670877828,0 exp=1712649567.670824057,0 pro=1712649561.670824057,0 prev=repl=(n31,s467):34 seq=669 start=1712649560.697935728,0 epo=4 pro=1712649560.697935728,0]
W240409 07:59:19.195437 4249 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 57275  applied lease after ~1.92s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=666 start=1712649557.278405228,0 exp=1712649563.278359720,0 pro=1712649557.278359720,0 prev=repl=(n31,s467):34 seq=665 start=1712649557.197546833,0 epo=4 pro=1712649557.197546833,0]
W240409 07:59:25.338283 4245 2@kv/kvserver/replica_proposal.go:624 ⋮ [T1,Vsystem,n6,s29,r16472/11:‹/Table/136/1/"@"/1010{02…-41…}›,raft] 57297  applied lease after ~3.67s replication lag, client traffic may have been delayed [lease=repl=(n6,s29):11 seq=670 start=1712649561.670877828,0 exp=1712649567.670824057,0 pro=1712649561.670824057,0 prev=repl=(n31,s467):34 seq=669 start=1712649560.697935728,0 epo=4 pro=1712649560.697935728,0]
F240409 07:59:27.429493 109583 kv/kvserver/replica_closedts.go:263 ⋮ [T1,Vsystem,n6] 770841  side-transport update saw closed timestamp regression on r16472: (lai=2548, ts=1712649563.889408923,0) -> (lai=2547, ts=1712649564.426571698,0)
```

</p>
</details> 

For `r29677` there were two lease transfers just prior (`s348` -> `s236` and `s348` -> `s201`). Both come from the same source (`s348`), implying that the lease transferred back quickly, or didn't transfer in the first instance. The close TS is reported on `n23`, **which transferred the lease away.**

```python
I240409 02:44:38.111254 28527827 13@kv/kvserver/lease_queue.go:143 ⋮ [T1,Vsystem,n23,lease,s348,r29677/15:‹/Table/137/1/"`"/80{15/…-69/…}›] 1134921  transferring lease to s236 usage=[batches/s=0.0 request_cpu/s=0µs raft_cpu/s=0µs write(keys)/s=0.0 write(bytes)/s=0 B read(keys)/s=0.0 read(bytes)/s=0 B]
I240409 02:44:39.336570 28528568 13@kv/kvserver/lease_queue.go:143 ⋮ [T1,Vsystem,n23,lease,s348,r29677/15:‹/Table/137/1/"`"/80{15/…-69/…}›] 1134941  transferring lease to s201 usage=[batches/s=0.0 request_cpu/s=0µs raft_cpu/s=0µs write(keys)/s=0.0 write(bytes)/s=0 B read(keys)/s=0.0 read(bytes)/s=0 B]
F240409 02:44:44.184257 8190663 kv/kvserver/replica_closedts.go:263 ⋮ [n23] 341041  side-transport update saw closed timestamp regression on r29677: (lai=287, ts=1712630678.676057292,0) -> (lai=286, ts=1712630680.929988206,0)
```


<details><summary>Details</summary>
<p>


```python
I240409 02:44:38.111254 28527827 13@kv/kvserver/lease_queue.go:143 ⋮ [T1,Vsystem,n23,lease,s348,r29677/15:‹/Table/137/1/"`"/80{15/…-69/…}›] 1134921  transferring lease to s236 usage=[batches/s=0.0 request_cpu/s=0µs raft_cpu/s=0µs write(keys)/s=0.0 write(bytes)/s=0 B read(keys)/s=0.0 read(bytes)/s=0 B]
I240409 02:44:39.336570 28528568 13@kv/kvserver/lease_queue.go:143 ⋮ [T1,Vsystem,n23,lease,s348,r29677/15:‹/Table/137/1/"`"/80{15/…-69/…}›] 1134941  transferring lease to s201 usage=[batches/s=0.0 request_cpu/s=0µs raft_cpu/s=0µs write(keys)/s=0.0 write(bytes)/s=0 B read(keys)/s=0.0 read(bytes)/s=0 B]
I240409 02:44:41.262910 4229 kv/kvserver/replica_raft.go:1621 ⋮ [T1,Vsystem,n5,s53,r29677/26:‹/Table/137/1/"`"/80{15/…-69/…}›,raft] 636036  slow non-blocking raft commit: commit-wait 1.871889405s sem 641ns
F240409 02:44:44.184257 8190663 kv/kvserver/replica_closedts.go:263 ⋮ [n23] 341041  side-transport update saw closed timestamp regression on r29677: (lai=287, ts=1712630678.676057292,0) -> (lai=286, ts=1712630680.929988206,0)
I240409 02:44:44.827898 8073 kv/kvserver/replica_raft.go:1621 ⋮ [T1,Vsystem,n15,s236,r29677/16:‹/Table/137/1/"`"/80{15/…-69/…}›,raft] 643431  slow non-blocking raft commit: commit-wait 6.039455446s sem 676ns
```

</p>
</details>

**Comment by kvoli** [comment] 2024-04-09 19:10
Logs are available [here](https://drive.google.com/file/d/1xaH5c63AoXINWaHoGqu8Yfk8O_QDBVZJ/view?usp=sharing) (internal).

**Closed** 2024-05-03 04:15 UTC
Labels: C-bug, A-kv-replication, O-testcluster, P-0, v23.1.27, v23.2.13, v24.1.1
