### ISSUE TITLE
log: seeming race or corruption in log tags

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#56873] opened 2020-11-18 23:13 UTC
**Describe the problem**

I was looking at some logs from a 20.2.0 cluster recently and found that the log tags present in log lines seemed impossible given the logging context. The logs were collected via debug zip without redaction. The debug zip command was also run from a 20.2.0 binary.

```
I201116 21:53:45.142698 4061 jobs/registry.go:874 ⋮ [n16,raftsnapshot,s16,r1433/32:‹/System/tsd/cr.node.txn.resta…›] cleaning up 1000 expired job records
```

The line in question should never have log tags from the raft snapshot queue execution. 

**To Reproduce**

No clue.

**Comment by ajwerner** [comment] 2020-11-18 23:13
@knz tagging you to triage as I sense you've been in this area most recently. This sort of thing is rampant over these logs.

**Comment by knz** [comment] 2020-11-19 11:12
that is most definitely odd and frightening - thanks for reporting

**Comment by knz** [comment] 2020-11-19 11:43
I investigated this and I discovered a possible path to what you saw.

That's something I'd like to get an extra pair of eyes from @tbg too.

Look at this function from package `logtags`:

```go
// AddTags returns a context that has the tags in the given context plus another
// set of tags. Tags are deduplicated (see Buffer.AddTags).
λ AddTags(⋄ context.Context, tags *Buffer) context.Context {
  b ≔ FromContext(⋄)
  newB ≔ b.Merge(tags)
  if newB ≡ b {
    return ⋄
  }
  return WithTags(⋄, newB)
}
```

On its face, this function *looks and feels* like it takes the tags it's given as argument and **copies** them "into" the new returned context.

It looks this way because the declared API of `Merge` is to "Return a fresh buffer".

However, `Merge` has a shortcut:

```go
λ (b *Buffer) Merge(other *Buffer) *Buffer {
  if b ≡ nil || len(b.tags) ≡ 0 {
    return other
  }
  ...
```

So if the incoming `ctx` doesn't have logging tags yet, the context returned by `AddTags()` attaches the provided `logtags.Buffer` **by reference** into the context.

So if the `Buffer` is subsequently modified in-place, it's possible to see context tags "appear" out of scope inside an unrelated function.

I think this is the root cause and I think either we need to get rid of this shortcut in `Merge` or force-copy the incoming `*Buffer` in `AddTags`.

----

Further than that, I was looking for where this "unwanted" reference could leak in a way that explains what you saw.


There are just 4 calls to `AddTags`. Two of them are "safe":
```go
pkg/sql/schema_changer.go:      ctx = logtags.AddTags(ctx, sc.execLogTags())
pkg/sql/type_change.go: ctx = logtags.AddTags(ctx, t.logTags())
```

In both cases, the helper function allocates a fresh `logtag.Buffer` on the heap and it is never reused elsewhere.

However, look at these two:
```
pkg/util/log/ambient_context.go:                ctx = logtags.AddTags(ctx, ac.tags)
pkg/util/log/ambient_context.go:                        ctx = logtags.AddTags(ctx, ac.tags)
```

This takes the current `ac.tags` and puts it in the annotated context.

You'd say -- well what about that? It certainly looks like `ac.tags` is only ever replaced by a fresh pointer reference, for example here:

```go
λ (ac *AmbientContext) AddLogTag(name string, value interface{}) {
  ac.tags = ac.tags.Add(name, value)  // allocates a new logtags.Buffer
  ...
```

**However** that's not all of the story, consider this:

```go
// LogTags returns the tags in the ambient context.
λ (ac *AmbientContext) LogTags() *logtags.Buffer {
  return ac.tags
}
```

this function is used like this:

```go
λ (n *Node) setupSpanForIncomingRPC(...) {
  ...
  newSpan = n.storeCfg.AmbientCtx.Tracer.StartSpan(
     opName, tracing.WithLogTags(n.storeCfg.AmbientCtx.LogTags()),
  )
  ctx = tracing.ContextWithSpan(ctx, newSpan)
  ...
```

So now every time an RPC arrives into a node, the current ambiant context for the store embeds its `logtags.Buffer` *by reference* into the current trace via a `SpanOption`.

And ... *span options get reused across multiple contexts*

So now you'd get the same `logtags.Buffer` embedded in traces in different goroutines.

This could *still* maybe be OK? if tracing never mutated logtags.Buffer in-place?

Unfortunately I don't know enough about tracing to be sure.

**Comment by tbg** [comment] 2020-11-19 12:39
Trace spans holds on to log tags only for printing. They will never add anything to the log tags buffer.

I agree that the root cause is likely to be this `Merge` function but am finding zero proof. I looked up Andrew's original log line and its context originates here:

https://github.com/cockroachdb/cockroach/blob/19951d2ad7a8eb3c20c38c6e55e1414549d1850f/pkg/jobs/registry.go#L689

So it's `context.Background()`, then goes through `RunAsyncTask`. `RunAsyncTask` goes through `ForkCtxSpan` but this will be a noop since `context.Background()` contains no span.

Then we go through `stopper.WithCancelOnQuiesce(ctx)` but that doesn't do anything with log tags neither.

And that's it! It seems "impossible" that there would even be any log tags at that point. This was on master, but I am just looking at 20.2 and the story hasn't changed.

There isn't even any ambient context involved. This is puzzling.

**Comment by tbg** [comment] 2020-11-19 13:09
I put a fatal on that log line hoping to hit it during tests, but not sure what to run. `./pkg/jobs...` doesn't hit it (there's one test that calls it, but it is skipped and has badly rotted - it fatals elsewhere before), and `./pkg/sql` doesn't either. Trying the logic tests now.

**Comment by knz** [comment] 2020-11-19 13:10
oh I think I got it :facepalm: 

```go
λ (s *statusServer) LogFile(...) {
  ...
  var entry logpb.Entry
  decoder ≔ log.NewEntryDecoder(reader, inputEditMode)
  for {
    if ⊙ ≔ decoder.Decode(&entry); ⊙ ≠ ∅ {
       ..
```

`Decode` does not re-initialize all the fields. If there is no tag on the current line, it will pick up the tags from the previous line...

**Comment by knz** [comment] 2020-11-19 13:10
i'm sending a pr

**Comment by tbg** [comment] 2020-11-19 13:11
Nice find!

**Closed** 2020-11-19 14:05 UTC
Labels: A-logging, C-bug
