### ISSUE TITLE
Test failure in CI build 4663

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1692] opened 2015-07-15 22:43 UTC
The following test appears to have failed:

[#4663](https://circleci.com/gh/cockroachdb/cockroach/4663):

```
Name                 Origin       Ts               Dur       Desc                            File
c999666220422072.30  127.0.0.1:0  22:34:26.220440  92.077µs  node                            server/node.go:489
c999666220422072.30  127.0.0.1:0  22:34:26.220459  71.732µs  ·executing InternalRangeLookup  storage/store.go:1237
c999666220422072.30  127.0.0.1:0  22:34:26.220463  66.626µs  ··read path                     storage/range.go:520

panic: test timed out after 30s

goroutine 64956 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [semacquire]:
sync.(*Cond).Wait(0xc208577680)
	/usr/src/go/src/sync/cond.go:62 +0x9e
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:207 +0x344
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:79 +0x5d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0xfc
FAIL	github.com/cockroachdb/cockroach/client	30.021s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
I0715 22:34:00.710817      88 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:34:00.730237      88 gossip/gossip.go:166 gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:34:00.730303      88 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:34:00.754375      88 gossip/gossip.go:166 gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:34:00.755854      88 base/context.go:103 setting up TLS from certificates directory: test_certs
I0715 22:34:00.795039      88 gossip/server.go:113 gossip: received infostore with 3 info(s): info "local-key": local value, info "node:1": node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "node:2": node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
Name             Origin       Ts               Dur        Desc                            File
c70832891834.13  127.0.0.1:0  22:41:10.832940  319.705µs  node                            server/node.go:489
c70832891834.13  127.0.0.1:0  22:41:10.832977  270.937µs  ·executing InternalRangeLookup  storage/store.go:1237
c70832891834.13  127.0.0.1:0  22:41:10.832990  256.928µs  ··read path                     storage/range.go:520

panic: test timed out after 5m0s

goroutine 206929 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [semacquire, 4 minutes]:
sync.(*Cond).Wait(0xc208176380)
	/usr/src/go/src/sync/cond.go:62 +0xb6
--
	/go/src/github.com/cockroachdb/cockroach/server/server.go:234 +0x269
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:79 +0x8c
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x14c
FAIL	github.com/cockroachdb/cockroach/client	300.090s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
I0715 22:36:27.308539     284 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:36:27.366494     284 gossip/gossip.go:166 gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:36:27.367013     284 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:36:27.423008     284 gossip/gossip.go:166 gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:36:27.426840     284 base/context.go:103 setting up TLS from certificates directory: test_certs
I0715 22:36:27.702537     284 gossip/server.go:113 gossip: received infostore with 3 info(s): info "node:1": node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "node:2": node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "local-key": local value

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-07-15 22:44
Another dupe of #1684

**Closed by bdarnell** 2015-07-15 22:44 UTC
Labels: test-failure
