### ISSUE TITLE
ui: statement diagnostics page downloads to same file name

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#46425] opened 2020-03-23 18:12 UTC
When debugging an issue, I'm often interested in diagnostics for a set of queries.

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/10536690/77348432-d2fdb200-6d0f-11ea-8931-a11a5dd1e4e2.png">

I'm able to activate collection for the set of them through the statements page, but when downloading them they will all download to the same filename by default (statement-diagnostics.json). That aside, I don't believe the JSON generated actually specifies the statement it pertains to.

**Comment by irfansharif** [comment] 2020-03-23 18:12
Assigning David for triage.

**Comment by dhartunian** [comment] 2020-03-23 20:27
@piyush-singh for prioritization

@koorosh can you comment on the difficulty of dynamically setting the JSON filename based on the fingerprint or at least some ID?

**Comment by koorosh** [comment] 2020-03-24 15:37
> @piyush-singh for prioritization
> 
> @koorosh can you comment on the difficulty of dynamically setting the JSON filename based on the fingerprint or at least some ID?

It is a minor change, not difficult. Require local change with no regression.

**Comment by piyush-singh** [comment] 2020-03-24 17:27
Ideally we would include the fingerprint in some way when naming the file, otherwise these will be incredibly hard to disambiguate, especially since we don't have the query in the bundle itself. I'd consider this very important to land for 20.1. Presumably we will need to have some way to truncate the fingerprint when naming the file, otherwise these could be incredibly long. I believe we are doing some kind of truncation for the hover tooltip, maybe reusing that for the naming of the file? We should eventually figure out a way to embed the query itself in the diagnostic bundle.

Are there other tools that have solved a similar problem?

**Comment by dhartunian** [comment] 2020-03-24 18:13
additional options to perhaps consider:

* explore a server-side change that adds the fingerprint to the file?
* insert the fingerprint into the JSON on the client-side after we download

otherwise, making the fingerprint "filename friendly" (replacing spaces etc.) and truncating should do the trick.

**Comment by dhartunian** [comment] 2020-04-16 14:45
Given that the download is now a statement bundle, it contains the statement within. Closing this for now.

**Closed by dhartunian** 2020-04-16 14:45 UTC
