### ISSUE TITLE
sql: pause/unpause/cancel schema changes

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#16018] opened 2017-05-18 13:46 UTC
We need a way to pause/unpause a schema change when it is hogging resources on a cluster.

It is possible that someone can use the API we provide to build an external scheduler that pauses/unpauses the schema change based on resource demands. Although we should really make pausing/unpausing internal and automatic.

We also need a mechanism to cancel a schema change. Some schema changes take days to execute (schema change of a 500M row table) and if someone inadvertently runs a schema change
thinking it will take minutes, they might like to cancel the schema change.

We have a jobs table that is shared between backup/restore schema change and other future job types. The SQL commands and the admin UI interface should be shared across these job types and can be operations on the common jobs table. Only the underlying implementation need be different. @benesch so he is aware.

**Comment by a6802739** [comment] 2017-06-01 10:18
@vivekmenezes  could I have a try for this?

**Comment by jordanlewis** [comment] 2017-06-01 11:58
Thanks but we already have an ongoing plan and effort for this issue in house.

**Comment by a6802739** [comment] 2017-06-01 13:17
@jordanlewis  Thank you all the way.

**Comment by vivekmenezes** [comment] 2017-06-01 15:52
The work on this issue can start once the SQL for pause/unpause/cancel has been developed for backup/restore jobs. We should use the same SQL commands and change the implementation for schema change jobs.

**Comment by petermattis** [comment] 2017-08-17 02:00
@jordanlewis this isn't happening for 1.1, right?

**Comment by dianasaur323** [comment] 2017-08-17 13:45
Just chatted with @jordanlewis and punting into 1.2. Adding into Airtable.

**Comment by bdarnell** [comment] 2017-08-17 19:02
Didn't this happen in #17434? I need to remove it from the release notes if it's not what I thought.

**Comment by benesch** [comment] 2017-08-17 19:33
That added pause/resume/cancel only for backup/restore, I'm afraid.

**Comment by dianasaur323** [comment] 2017-09-17 16:48
Related to https://github.com/cockroachdb/cockroach/issues/7554

**Comment by dianasaur323** [comment] 2017-09-22 13:03
**Rationale**
We currently use the syntax pause/resume/cancel jobs, but only support backup/restore. We need to add this functionality to schema changes.

**PM Acceptance Testing**
- [ ] Run a schema change
- [ ] Pause it
- [ ] Resume it
- [ ] Cancel it
- [ ] Observe what this looks like in the admin UI
- [ ] Check show query behavior
- [ ] Check show jobs behavior
- [ ] Make sure this matches pause, resume, cancel backup/restore user experience

**Comment by vivekmenezes** [comment] 2017-09-25 02:38
This can be something @lego can take on if he's interested.

**Comment by vivekmenezes** [comment] 2017-09-27 16:55
They do have a way to "purge" if you take a look at schema_changer.go . It gets called automatically when the schema change hits an unrecoverable error. We can drive it through the cancel command for this issue.

**Comment by lego** [comment] 2017-10-20 20:45
Once we add job control to schema changes, there will be some funky usability edge cases introduced. This happens specifically because of schema changes will run in the foreground. For example,
- Run `CREATE INDEX ...`
- In another terminal `CANCEL JOB ...`

What does the first terminal show? `OK` or `schema change job 1234556 was canceled. rolled back schema change "CREATE INDEX ..."`?

What happens to any schema changes that were after our canceled one. Do they continue to run, or do they all get canceled? If they continue to run, then how does that get mixed in with the possible rollback message?

(I'm not familiar with the order of execution, but can you run statements after schema changes in a transaction? It appears schema changes occur at the end of the transaction)

**Comment by vivekmenezes** [comment] 2017-10-23 19:59
In the current UI if a schema change gets rolled back due to a problem we return the problem error code to the user as long as that session is still on. I think you can return ```cancelled by admin``` 

Only the one cancelled ahouls be cancelled. That being said you can have a dependency between two schema changes (an index created after a column is added, cancelling the column schema change should also revert the index).

you can run statements after schema changes, but they cannot reference the schema change. It doesn't make sense to use an index that hasn't already being created for instance.

**Comment by lego** [comment] 2017-12-12 20:32
I made a (unsuccessful) stab at trying to do this, but here are the
challenges that came up. This summarizes discussion from WIP PRs
to help give others context (#19913 and #19463). Sorry that this is
lengthy. It's a pretty comprehensive proposal of how to complete this.

1. Currently, the schema changes acquire a schema changer lease, which
   ensures a change is only being executed by one node. This can be
   functionally replaced by a combination of the Job leases and Job
   dependencies.

   Also, the `ScemaChangeManager` is only there to pick up and run
   schema changes that aren't executed by the session. This is replaced
   by the `Registry`.

   Sidenote: A recent change to make `execAfter` meaningfully long for
   `DROP TABLE` adds an extra challenge to this (#20601). Naively, I
   think this is as simple as creating a lease that expires at
   `execAfter`. If the node that owns the lease fails liveliness, then
   the next node that picks up the schema change recognizes this and
   also acquires a long lease, but doesn't run it yet. This overall,
   feels like a large hack on top of job management.

2. Schema changes need job dependencies for ordered execution.

   It's easy for the executor to run them in order synchronously, but if
   the jobs are orphaned by the session and they run asynchronously
   dependencies will ensure they run in order, one at a time.

   When schema changes are created, if there are any existing schema
   changes then the job for the last change is set as the dependency for
   the new schema changes.

   Once a schema change job, it will query all jobs that depend on it
   and move those to `running` within the same txn that we set the job
   to `success` (or `failure`) on completion. This does not need to be
   built for jobs in general, but that makes it simpler. This can be
   done without much complexity with the new `JobResumer` interface, in
   particular the `OnFailureOrCancel` and `OnSuccess` hooks.

3. Another requirement which is challenging keeping the deferred
   execution of schema changes. A schema change (and job) is created in
   a txn, but the execution is deferred until just after the txn is
   closed. We need to prevent other nodes from running the schema
   change. Schema changes happen in two steps:
 
    1. When a user executes a schema change in a txn, e.g.
       `ALTER TABLE ...`, this immediately creates the schema changer
       and the job record in the txn. Execution of the schema change is
       deferred and does not happen yet.
  
    2. Once the txn ends, the executor attempts to run the schema changes
       synchronously, in order. If the user closes the session anytime
       after the txn ends, even before schema changes begin running, another
       node will pick up the schema change and run them asynchronously.

   To achieve this, `Registry.CreateJob` can be added to the JobRegistry
   interface to create a job in a txn, register it with the local job
   registry, obtain (and refresh) the job lease, but not run it yet
   (i.e. `Registry.StartJob` without running it).
  
   The idea behind acquiring the job lease is to prevent other nodes
   from executing the schema change yet, before the session can get to
   it. The lease will also need to be refreshed during the txn. The
   simplest way that just "works" would be to have a goroutine that is a
   part of the session which just keeps refreshing all the pending
   schema change leases using the active txn.

   (Actually, this may be less of a problem than I expect because if the
   jobs are made in a txn, they aren't visible to other nodes yet.
   Regardless, we need to make sure when the txn ends the lease will not
   expire immediately.)

   An alternative would be to create a `pending` status for jobs, and
   only start them after the txn. A problem with this is reliably moving
   the jobs from `pending` to `running` if a session is closed, or a
   node fails.


This skips over rollbacks, caused by failure or cancellation. They
shouldn't be to difficult to create the rollback within the
`OnCancelOrFailure` Resumer hook. Of course, I wouldn't be surprised if
there were other challenges that come up here.

**Comment by dianasaur323** [comment] 2017-12-12 23:30
quick fyi @mjibson this became more complicated than expected, as you anticipated, so let's spend some time on this next release.

**Comment by mjibson** [comment] 2017-12-13 06:31
Yup. Already spoke to Joey and Vivek about this and am writing an RFC about it.

**Comment by arjunravinarayan** [comment] 2018-03-01 20:17
@mjibson what was the outcome of that RFC writing process?

**Comment by benesch** [comment] 2018-03-01 20:19
Either way this can definitely be punted to 2.1.

**Comment by mjibson** [comment] 2018-03-01 21:40
I guess the result was I didn't do anything because other stuff came along. But someone will eventually be assigned to actually do this. Not sure who.

**Comment by dianasaur323** [comment] 2018-03-02 20:55
Yep, this is scheduled for 2.1, and at that point, we'll get a clearer sense for who is doing what. I think it fits naturally into the time we are planning on investing in schema changes anyway.

**Comment by vivekmenezes** [comment] 2018-04-12 14:06
this is now a very high priority issue and we should consider cherry picking into 2.0 . If a schema change gets stuck there is no way to recover from the problem.

**Comment by dianasaur323** [comment] 2018-04-12 16:07
agreed - in some ways this is turning out to be more of a bug than a feature at this point...

**Comment by mjibson** [comment] 2018-04-12 17:44
What happened to change this to be high priority?

**Comment by vivekmenezes** [comment] 2018-04-12 18:32
see the conversation on gitter

**Comment by erichocean** [comment] 2018-05-10 21:14
I think a better UI for the `cockroach sql` client when executing a schema change is to immediately return the job id and give control back to the prompt. If you want to see when the job completes, you can query the job.

Right now, I'll execute a `create index` and then I have to force-quit and restart so I can move on to other queries, such as creating other indexes.

**Comment by benesch** [comment] 2018-05-11 16:55
But we could introduce a syntax variant like `ALTER TABLE ASYNC...`. Or
perhaps a session variable that's enabled by default in CLI sessions.

**Comment by mjibson** [comment] 2018-06-01 05:15
We don't have plans to implement pause/resume anytime soon. Removing from milestones.

**Comment by jordanlewis** [comment] 2020-03-24 18:31
This has been subsumed by jobs and other efforts in the last couple of years.

**Closed by jordanlewis** 2020-03-24 18:31 UTC
Labels: A-bulkio, A-schema-changes, C-enhancement
