### ISSUE TITLE
sql: unsupported interval syntax

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#12429] opened 2016-12-15 21:34 UTC
The following statement works in postgres:
`select interval '4' minute;`

But on Cockroach, returns:
`invalid syntax: statement ignored: unimplemented at or near ";"`
`select interval '4' minute;`

Unclear if we *should* support this (as opposed to the more normal '4 minute' syntax).

**Comment by jordanlewis** [comment] 2016-12-15 21:56
This is actually a duplicate of #12110, although the title of that ticket wasn't the clearest. I'll update the title and close this one.

**Closed by jordanlewis** 2016-12-15 21:56 UTC
Labels: sql-semantics
