### ISSUE TITLE
Test failure in CI build 7223

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2447] opened 2015-09-10 15:08 UTC
The following test appears to have failed:

[#7223](https://circleci.com/gh/cockroachdb/cockroach/7223):

```
E0910 15:08:36.276104 813 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 15:08:36.576087 813 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 15:08:36.876097 813 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 15:08:37.176109 813 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 15:08:37.476111 813 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
panic: test timed out after 1m10s

goroutine 2973 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x13b4a00, 0x1952160, 0x1f, 0x1f, 0x7d4b01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:252 +0x31d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820162300, 0xc8201d8380)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x62
FAIL	github.com/cockroachdb/cockroach/server	70.040s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.00s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.00s)
=== RUN   TestRuntimeStatRecorder
I0910 15:07:32.914807 823 server/status/runtime.go:118  runtime stats: 10 goroutines, 5.11MiB active, 50000000.00cgo/sec, 96310.00/48150.00 %(u/s)time, 1356.82 %gc (1x)
--- PASS: TestRuntimeStatRecorder (0.00s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.00s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by BramGruneir** [comment] 2015-09-10 15:18
dupe of #2440

**Closed by BramGruneir** 2015-09-10 15:18 UTC
Labels: test-failure
