### ISSUE TITLE
can not see added column  in on single transication?

### ISSUE THREAD

**Issue by leafji** [cockroachdb/cockroach#52529] opened 2020-08-08 03:26 UTC
**Describe the problem**
i reproduce as below:
1. first create table t1;
create table t1(a int);
2. do follow sql with in single transication:
begin;
alter table t1 add column b int;
show create table t1;
insert into t1(b) values (3);
3. as of result, i can not see new added column in this transication, and abort.
root@192.168.2.2:26359/defaultdb> begin;
alter table t1 add column b int;
show create table t1;
insert into t1(b) values (3);

Now adding input for a multi-line SQL transaction client-side (smart_prompt enabled).
Press Enter two times to send the SQL text collected so far to the server, or Ctrl+C to cancel.
You can also use \show to display the statements entered so far.
                               ->
  table_name |        create_statement
-------------+----------------------------------
  t1         | CREATE TABLE t1 (
             |     a INT8 NULL,
             |     FAMILY "primary" (a, rowid)
             | )
(1 row)
(error encountered after some results were delivered)
ERROR: column "b" does not exist
SQLSTATE: 42703

**Environment:**
 - CockroachDB version [CockroachDB CCL v20.1.3 (x86_64-unknown-linux-gnu, built 2020/06/23 08:44:08, go1.13.9)]
 - Server OS: Linux
 - Client app :cockroach sql

I expect my new add column can be see with in this transication,  i know this is a limit of online-schema change,  
I want to know why canot do this job with in a single transication, could you explain this for me more detail.
Thank you very much.

**Comment by ajwerner** [comment] 2020-08-08 05:04
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/43057. This is a well known and understood issue. Unfortunately it’s rather complex to make this work with online schema changes. We’ve been developing a plan and are hoping to start working on it for the spring 2021 release. 

Feel free to comment on that issue if you have more to add.

**Closed by ajwerner** 2020-08-08 05:04 UTC
Labels: C-bug, O-community, X-blathers-triaged
