### ISSUE TITLE
crash looping -- sideloaded file not found

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#113135] opened 2023-10-26 12:40 UTC
**Describe the problem**

In a customer environment, a restore caused the disks to fill up which resulted in many of the nodes crashing due to full disks / disk stalls (Note: This should probably be a separate issue, as this shouldn't cause a crash). During one of the crashes, we "lost" a side-loaded file. It wasn't clear if the file was written and then deleted or never written at all, but either way, there was an "unprocessed" Raft entry pointing to the file, and the file was gone. This caused the system to repeatedly crash loop until the node was taken offline and replaced by a different file.

The panic error is:
`loading sideloaded data: sideloaded file not found.`

**To Reproduce**

I have not attempted to reproduce it yet, but it would be worth trying a db restore and repeatedly killing one of the nodes during the restore using `kill -9`. We should also test with a full reboot of the OS as it may catch other issues as well. 

**Expected behavior**
The side loaded files and the Raft log should be consistent.

**Environment:**
 - CockroachDB version : v23.1.11

Jira issue: CRDB-32766

**Comment by pavelkalinnikov** [comment] 2023-10-30 19:41
> It wasn't clear if the file was written and then deleted or never written at all

Good point regarding deletion. I explored this, and it seems like one of the possible scenarios is:

0. Raft log has a few sideloaded entries.
1. Raft gets a log write which overrides a tail of entries. https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L174
2. An **async** log write is sent to Pebble. https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L252-L259
3. In the meantime, execution proceeds and removes a bunch of overridden raft entries. https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L291-L304
4. Crash, before the async log write 2 completes.
5. Restart sees the old state from step 0, but does not see some entries because they were removed in step 3.

**Comment by pavelkalinnikov** [comment] 2023-10-30 19:41
@erikgrinaker WDYT, does this sound plausible?

**Comment by pavelkalinnikov** [comment] 2023-10-30 19:44
Specifically, this statement got broken after introduction of async log writes:
https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L295-L296

**Comment by pavelkalinnikov** [comment] 2023-10-30 19:50
Ah no, `nonBlockingSync` can't be true when `overwriting`:
https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L248

False alarm.

**Comment by pavelkalinnikov** [comment] 2023-10-30 19:57
There still something weird here. Would appreciate a second pair of eyes on the following:

Even though we don't use async log write when there are log entries to be overwritten
https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L239-L252

we still may commit without sync:

https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L276

**Comment by pavelkalinnikov** [comment] 2023-10-30 20:28
If any of these lines incorrectly assign false, we may have a bug.
https://github.com/cockroachdb/cockroach/blob/e8367041383e1123b2f71cfd4b54439ab4ac56b8/pkg/kv/kvserver/logstore/logstore.go#L236-L237

It's hard to tell exactly whether `len(m.Responses) > 0` is a safe check to rely on. It's assigned in etcd/raft as follows: https://github.com/etcd-io/raft/blob/f3fa38bee62ec85ed7c9ee36c1073348c845bf4f/rawnode.go#L248-L260.

Previously, we [relied](https://github.com/cockroachdb/cockroach/pull/94165/files#diff-df7ae37de4bee37fd1fd16b201c787b7db9bf888c4b18cd59d2e3e15b52417edL185) on the `MustSync` field which was well defined: https://github.com/etcd-io/raft/blob/f3fa38bee62ec85ed7c9ee36c1073348c845bf4f/rawnode.go#L163.

**Comment by pavelkalinnikov** [comment] 2023-10-30 20:47
Another suspect for a sneaky deletion is https://github.com/cockroachdb/cockroach/blob/6a447621356ba0366cc0db15cb3dcf26327d1152/pkg/kv/kvserver/replica_application_result.go#L488-L495
although it promises that it's safe.

**Comment by pavelkalinnikov** [comment] 2023-10-30 21:03
So, here is a new scenario to try:

1. Batch with the log truncation is committed (but not synced).
2. Sideloaded files are removed.
3. Kill (before the new state from step 1 is synced).
4. Restart should see missing sideloaded files.

**Comment by pavelkalinnikov** [comment] 2023-10-30 22:47
This issue is possibly related to #38566.

**Comment by pavelkalinnikov** [comment] 2023-11-09 21:43
Managed to reproduce this panic in #114191

**Comment by pavelkalinnikov** [comment] 2023-11-14 15:32
The panic in #114191 is due to a different issue: #114411. The latter should be fixed first.

**Comment by pavelkalinnikov** [comment] 2023-11-22 15:42
**Now** #114191 reproduces the right failure.

If I change the sync behaviour here https://github.com/cockroachdb/cockroach/blob/e5570cb99a5221dd80bb7cae6f92714d2d082755/pkg/kv/kvserver/replica_app_batch.go#L561-L564

to `sync := true`, the test stops panicking. This proves the conjecture that the root cause is the lack of state machine sync before removing the sideloaded files.

The fix will be setting `sync` to true if the truncation command touches any sideloaded files.

**Comment by pavelkalinnikov** [comment] 2023-11-25 13:39
#114191 now also has the fix. Hopefully will be able to polish and merge the whole thing this coming week.

**Comment by erikgrinaker** [comment] 2023-12-13 09:57
Downgrading to non-blocker, pre-existing issue.

**Closed** 2024-01-03 20:05 UTC
Labels: C-bug, O-support, branch-master, T-kv-replication, branch-release-22.2, branch-release-23.1, branch-release-23.2
