### ISSUE TITLE
opt: not all user-defined types used in a query stored in metadata

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#67434] opened 2021-07-09 18:31 UTC
There are still a few edge cases where we are not capturing all the user-defined types in a query in the metadata. This is problematic since we rely on those user-defined types to decide whether or not a cached memo is stale.

For example, one of the validation queries used for `ALTER TYPE ... DROP VALUE` does not have all user-defined types accounted for. This seems to be a problem when a user-defined type is used as an array column in a table. See this test case for an example: https://github.com/cockroachdb/cockroach/blob/4dbb74c9e3abe2d87646a6891a60d31cdef5f328/pkg/sql/logictest/testdata/logic_test/alter_type#L536 

Jira issue: CRDB-8541

**Comment by mgartner** [comment] 2023-05-25 16:38
@rytaft spend a few minutes trying to figure out if there is a bug here, if not please close this.

**Comment by cucaroach** [comment] 2023-08-21 20:09
Is this a dupe of https://github.com//cockroachdb/cockroach/issues/96674?

**Comment by mgartner** [comment] 2023-08-30 22:34
I'm confused about the example in the description above—it appears to be behaving as expected. I'm going to go ahead and close this.

**Closed by mgartner** 2023-08-30 22:34 UTC
Labels: C-bug, A-sql-optimizer, T-sql-queries
