### ISSUE TITLE
investigate poorly performing workload

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#16595] opened 2017-06-19 14:06 UTC
via user @HeikoOnnebrink:

Basically I have 2 tables

```
CREATE TABLE IF NOT EXISTS Requests (
RequestKey serial PRIMARY KEY,
RequestType string NOT NULL,
RequestLock bool NOT NULL default false,
RequestTime timestamp,
RequestState string,
LastStep string,
LastError string,
ResourceType string NOT NULL,
DCname string,
ID bytes NOT NULL,
Body bytes)

CREATE TABLE IF NOT EXISTS PostgresqlDBs (
ID bytes PRIMARY KEY,
DCname string,
AccountingGroup string,
Version string,
Name string,
Description string,
Username string,
Password string,
ServerName string,
IP string,
Port integer,
ReplicationMasterID string,
DataProtection boolean,
HostFlavour string,
StorageType string,
StorageGB integer,
DesiredState string,
CurrentState string,
StartTime timestamp,
ServerID string,
IPinternal string,
DBVolumeName string,
DockerVolumeName string,
ContainerID bytes,
MetricContainerID bytes,
PostgresqlPWD string)
```

The have workers that execute below SQL to retrieve (next) requests to process from the request table (globally sorted via SERIAL requestkey) and sequentially per ID
```
SELECT min(requestkey) AS requestkey FROM Requests WHERE dcname = $1 OR dcname is null 
GROUP BY id HAVING count (case when requestlock = true then 1 end) = 0 ORDER BY 1 LIMIT 1
```
In case a record is returned worker tries to lock the request by issuing this SQL :
```
UPDATE Requests set RequestLock = TRUE where requestkey = $1 and requestlock = false
```
If worker was able to "lock" the record it reads the full content of the request
```
SELECT * from Requests where requestkey = $1;
```
Then the worker processes the request, inserts a new record into Postgresqldbs and deletes the request via
```
DELETE FROM Requests WHERE RequestKey = $1
```
Up from here the worker goes back to the beginning of the process loop to work on the next request.
the whole thing is written in GO using database/SQLX and standard PostgreSQL GO client..
To produce some load its enough to create some hundred records into requests table..

as promised I created a custom build from latest master branch, upgraded the 9 node cluster and re-ran the tests.
Good news .. I am no more able to reproduce the “result is ambiguous” error ..  .. on the other hand overall cluster response seems to have gone down.. but this I need first to confirm after more testing..

Question:
You mentioned improvements to the retry code that seem to fix my issue. In which official release will they be included / delivered ?

to add dashboard metrics to my first impression... with release-1.0 branch based build I have p50 latency in the range of some few ms ... with the latest master branch build it goes up to 500-600 ms ..
.. with peaks in the range of seconds ...

**Comment by andreimatei** [comment] 2017-06-19 20:24
Thanks @HeikoOnnebrink!

> You mentioned improvements to the retry code that seem to fix my issue. In which official release will they be included / delivered ?

The fix will likely be backported to 1.0.3, which will be released in the next few weeks.

As to the regression you've found... I think it's likely that, with the version upgrade, a lot of queries that resulted in retryable errors before now block for longer. This is due to how our transaction conflict resolution code evolved. So, when you look at a latency percentile, are you looking at what crdb reports in its UI, or are you measuring something in your application?

Another thing that I've noticed you may not be aware of, related or not to the regression, is that your `SELECTs` scan the whole table. Your query is pretty complicated; it looks like you're trying to select the oldest task that's part of a group for which no other task is currently being processed.
You can see that the whole table is being scanned by those queries by doing either an `EXPLAIN(METADATA) SELECT ...` or `EXPLAIN(DISTSQL) SELECT ...` and opening URL. The worst thing about these full table scan is that they also need to go through all the rows that have been deleted "recently" and haven't yet been garbage collected - such rows leave "tombstones". Unfortunately there doesn't appear to be a good way to observe if this is the problem (I've filed #16608 for better tracing). In any case, perhaps the "regression" is due to you running your program for longer than you did before with the old version and thus generating many of these tombstones. Could that be the case? Can you try running a 1.0 server on the current database state and seeing if the performance is better (to affirm the regression)?

If the tombstones are indeed the problem, the default time they live for is 24h (so you can do time-travel queries on past data up to 24h). You can change that with something like the following, and see if it helps.
```
./cockroach zone set .default -f - --insecure <<EOF
gc:
  ttlseconds: 600
EOF
```

**Comment by HeikoOnnebrink** [comment] 2017-06-20 04:36
The degrade of performance I have measured by some application throughput indicator (requests per minute). Then I looked at the UI at the P50 latency counter and compared different test runs with different CRDB versions. 
What looks strange at me is the fact that CRDB itself without any user load shows high values for the custom build that I created from latest master branch ... right now when I came back to the office it shows peaks up to 5100.3 ms without any user processes running.. ? 

Now for the SQLs above:
The idea of the request table is to have a kind of ingest queue for incoming requests. The number of rows at some point in time should be low as I have a bunch of workers that fight to process them (and I can scale them up as needed to catch up with any higher ingest rate... ) 
As I have some long time Oracle background my assumption was that for low number of records a full scan even could be a good approach as it avoids reading additional index records (blocks) to lookup the data,  As I learned now this kind of sorted queue I have implemented on top of CRDB seems to be a kind of anti-pattern when I see that for time travel queries 24h of historic data is left in place and queried during the full table scans (even it is not visible .. ) That explains that my test results of each run are not comparable as each run delete data, but because of time travel query the data is left behind for the next run .. 

So my options seem to be : 

work on the query, maybe drop in some index and get rid of the full scan. But even with index in place I assume still deleted data is scanned ...

change the ttl of data

Question here :
Any way to change the TTL on a per table level and not globally ?

**Comment by HeikoOnnebrink** [comment] 2017-06-20 06:08
one more question to EXPLAIN.. when playing around with different indexes / index orders is there any way to get timed statistics or costs of the explained SQL ?

**Comment by HeikoOnnebrink** [comment] 2017-06-20 08:40
I rebuild the cluster from scratch (before I just did the upgrade - downgrade of the binaries.. ) now P50 is arround 80ms while on stress.. looks better .. I keep on testing ..

**Comment by andreimatei** [comment] 2017-06-21 15:27
Sorry for the late reply.

> So my options seem to be :
> work on the query, maybe drop in some index and get rid of the full scan. But even with index in place I assume still deleted data is scanned ...

Yes... I have thought about your query a bit, and I couldn't figure out a way to rewrite it such that it wouldn't require a full table scan with our current planner. That is, respecting the semantics of the given query - returning a request from an id for which there currently isn't another request being processed, and return the min of all such requests... Hopefully, you can relax this requirement some.
You are right that an index also carries deleted data that might need to be scanned, but, generally speaking, if you manage to get an index by, say, timestamp, and you scan it backwards (descending) with a small limit, then, assuming timestamps are increasing, you'll never scan over much garbage (because the garbage has lower timestamps).

> change the ttl of data
Yup.

> Question here :
> Any way to change the TTL on a per table level and not globally ?

Yes; you can make your table be part of a particular "zone", and the TTL is configured by zones. https://www.cockroachlabs.com/docs/configure-replication-zones.html

Your use case is not uncommon (albeit your query is more complicated than most), so we'll keep an eye going forward for planning optimizations that make it less likely for such queries to have to perform full scans.

**Comment by HeikoOnnebrink** [comment] 2017-06-21 18:08
one way to get load down would be to move away from "polling" the request table in a loop and instead use some wakeup approach. In my previous implementation of my service I persisted against ETCD and was happy with the ETCD WATCH option. In PostgreSQL there is some proprietary NOTIFY command that does a similar job.. I saw it also somewhere in your backlog .. whats the status about NOTIFY on Roach .. ?

**Comment by andreimatei** [comment] 2017-06-21 18:27
There are no specific plans at this time for any type of triggers or notifications. They will not be part of the next release, at least. It's a commonly requested featured, so we'll surely do something in the area at some point.

I believe you should be able to get polling to work well enough if you simplify your query: make it generally return an available task without regard for task groups. Or you can probably also get it to work with groups if you maintain a separate table for the groups with a task count, and a separate table for the tasks, and you join the two. But you'll likely need to relax your inter-group ordering requirement.

**Comment by HeikoOnnebrink** [comment] 2017-06-21 19:21
ok.. will wait for NOTIFY to get implemented.. in between adding an index on dcname,requestlock,id storing requestkey gave a boost of throughput. Also testing has confirmed that latency goes up over time when I insert/delete records in/from requests table.. Your assumption seems to apply that the delete date that was not removed by GC creates extra load. from what I see this impacts over time the latency as displayed in e.g. UI counter P50 ...

**Comment by andreimatei** [comment] 2017-06-23 18:53
I'm closing this because there's nothing actionable here. I've opened the issue above for documenting this behavior.
I'll open another discussion about perhaps changing the default TTL from 24h. We've been discussing other optimizations that we could make if we decide against changing the TTL, too.

**Closed by andreimatei** 2017-06-23 18:53 UTC
