### ISSUE TITLE
Test failure in CI build 7910

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2646] opened 2015-09-23 21:31 UTC
The following test appears to have failed:

[#7910](https://circleci.com/gh/cockroachdb/cockroach/7910):

```
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:220 +0x29a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820500600, 0xc820505fc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x62
FAIL	github.com/cockroachdb/cockroach/storage	5.013s
=== RUN   TestBatchBasics
I0923 21:30:51.078438 990 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0923 21:30:51.079183 990 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0923 21:30:51.081032 990 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-23 21:51
another dupe of #2566

**Closed by tamird** 2015-09-23 21:51 UTC
Labels: test-failure
