### ISSUE TITLE
make query stats in node_statement_statistics persistent 

### ISSUE THREAD

**Issue by mikeczabator-doordasher** [cockroachdb/cockroach#58151] opened 2020-12-21 22:15 UTC
**Is your feature request related to a problem? Please describe.**
The default behavior is to roll off queries from the node_statement_statistics table after a designated amount of time. I would like them to persist by being written out to a log file rather than deleting them.

**Comment by asubiotto** [comment] 2021-03-02 18:09
Closing as a duplicate of #56219

**Closed by asubiotto** 2021-03-02 18:09 UTC
Labels: C-enhancement, O-community
