### ISSUE TITLE
GORM .Save and makeInternalPlanner called with a transaction without timestamps error

### ISSUE THREAD

**Issue by timchunght** [cockroachdb/cockroach#14828] opened 2017-04-11 23:10 UTC
I am using GORM as recommended by cockroach, however, the DB crashes on UPDATE. 

```
func (self *Role) Update() error {

	self.UpdatedAt = time.Now()
	dbResult := db.Table("roles").Save(self)
	if dbResult.Error != nil {
		return dbResult.Error
	}

	return nil
}
```
The output SQL is 
```
UPDATE "roles" SET "name" = 'Admin', "description" = 'all system', "visible" = 'false', "updated_at" = '2017-04-11 19:04:49', "created_at" = '2017-04-11 17:52:24'  WHERE "roles"."id" = '235479839856099329'
```

This always crashes the DB with `makeInternalPlanner called with a transaction without timestamps`

The stranger thing is, if I execute this query in `cockroach sql`, it complains about int <-> string comparison. But if I have executed an fixed version of the UPDATE query (by removing the quotes around id), all subsequent request via GORM functions WITHOUT any issues (it is just the same query with quotes)! 

PS: everything works in Postgres.

Here is the trace from the log
```
goroutine 658 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4202da8c0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:199 +0x94
panic(0x53ba080, 0xc420b05090)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420845200, 0x7b63390, 0xc4208eb260)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:348 +0x74
panic(0x53ba080, 0xc420b05090)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql.makeInternalPlanner(0x55ee33d, 0xd, 0xc420479cc0, 0x55e2152, 0x4, 0xc4200903d0, 0x63e5160)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:114 +0x70c
github.com/cockroachdb/cockroach/pkg/sql.LeaseStore.Acquire(0x5f6f1a0, 0xc420484dc0, 0xc42026f000, 0x3ff0000000000000, 0xc42026f000, 0xc420090000, 0x0, 0x0, 0x0, 0xc4200903d0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:157 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*tableState).acquireNodeLease(0xc42028ce10, 0x7b63390, 0xc420da7fb0, 0xc420479cc0, 0x0, 0xc420210480, 0x0, 0xc400000000, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:723 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql.(*tableState).acquireFromStoreLocked(0xc42028ce10, 0x7b63390, 0xc420da7fb0, 0xc420479cc0, 0xc400000000, 0xc420210480, 0xc420f45af0, 0xc420fbd450)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:617 +0xa8
github.com/cockroachdb/cockroach/pkg/sql.(*tableState).acquire(0xc42028ce10, 0x7b63390, 0xc420da7fb0, 0xc420479cc0, 0x0, 0xc420210480, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:575 +0x12e
github.com/cockroachdb/cockroach/pkg/sql.(*LeaseManager).Acquire(0xc420210480, 0x7b63390, 0xc420da7fb0, 0xc420479cc0, 0x6b, 0xc420b814c8, 0x54483c0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/lease.go:1144 +0x86
github.com/cockroachdb/cockroach/pkg/sql.(*planner).getTableLeaseByID(0xc4209e0800, 0x7b63390, 0xc420da7fb0, 0x6b, 0x2, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/table.go:379 +0x101
github.com/cockroachdb/cockroach/pkg/sql.(*planner).fillFKTableMap(0xc4209e0800, 0x7b63390, 0xc420da7fb0, 0xc420960bd0, 0x14b2fadef0e4f829, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/planner.go:253 +0xb8
github.com/cockroachdb/cockroach/pkg/sql.(*planner).Update(0xc4209e0800, 0x7b63390, 0xc420da7fb0, 0xc420b72640, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:175 +0x515
github.com/cockroachdb/cockroach/pkg/sql.(*planner).prepare(0xc4209e0800, 0x7b63390, 0xc420da7fb0, 0x5f87ca0, 0xc420b72640, 0x0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:416 +0x559
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).Prepare(0xc4200fa680, 0xc420cdf08e, 0x81, 0xc420fe5200, 0xc4209602d0, 0x0, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:466 +0x637
github.com/cockroachdb/cockroach/pkg/sql.PreparedStatements.New(0xc420fe5200, 0xc4208eb320, 0xc4200fa680, 0xc420cdf08d, 0x0, 0xc420cdf08e, 0x81, 0xc4209602d0, 0x85, 0x0, ...)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/prepare.go:76 +0x63
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleParse(0xc420845200, 0xc420845228, 0xc420863260, 0x50)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:546 +0x432
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420845200, 0x7b63390, 0xc4208eb260, 0xc420899930, 0x5400, 0xc42001a4d0, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:434 +0x8f0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc42001a380, 0x7b63470, 0xc42012b800, 0x5f90580, 0xc420b84460, 0x0, 0x0)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x927
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5f90580, 0xc420b84460)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/server/server.go:587 +0x153
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4202da8c0, 0xc4203c0020, 0x5f90580, 0xc420b84460, 0xc4201b3920)
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
	/ext-go/1/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
```

**Comment by andreimatei** [comment] 2017-04-11 23:26
Thanks for the report! This is a dupe of #14473 and has been fixed a few days ago.
You can wait for this week's beta release on Thursday, or you can build from source for a working binary.

**Closed by andreimatei** 2017-04-11 23:26 UTC

**Comment by timchunght** [comment] 2017-04-12 00:35
@andreimatei Out of curiosity. Does the UPDATE command involve preparing a transaction? It appears from the log that it is a simple UPDATE. Thanks.
