### ISSUE TITLE
sql: conn_executor.go:521: panic while executing 1 statements: SELECT DISTINCT _._, _._, _._ FROM _ AS...

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#25279] opened 2018-05-03 14:25 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/542212399/

```
*log.safeError: conn_executor.go:521: panic while executing 1 statements: SELECT DISTINCT _._, _._, _._ FROM _ AS _ CROSS JOIN _ AS _ WHERE _._ = _._ LIMIT _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go", line 393, in AddRendering
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 948, in selectRenders
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1898, in createPlanForNode
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1894, in createPlanForNode
...
(11 additional frame(s) were not displayed)

conn_executor.go:521: panic while executing 1 statements: SELECT DISTINCT _._, _._, _._ FROM _ AS _ CROSS JOIN _ AS _ WHERE _._ = _._ LIMIT _: caused by <redacted>
```

**Comment by RaduBerinde** [comment] 2018-05-03 15:18
The panic is due to a render expression that is projecting a column that is omitted below. I tried to reproduce with similar queries but wasn't successful. Hopefully someone who runs into it files an issue with more information.

**Comment by jordanlewis** [comment] 2018-08-21 15:08
Closing as we can't reproduce this.

**Closed by jordanlewis** 2018-08-21 15:08 UTC
Labels: A-sql-execution, C-bug, S-2-temp-unavailability
