### ISSUE TITLE
kvserver: regression in BenchmarkBumpSideTransportClosed from release 23.1

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#115058] opened 2023-11-24 16:50 UTC
**Describe the problem**

I bisected a regression in BenchmarkBumpSideTransportClosed to https://github.com/cockroachdb/cockroach/pull/103736:

```
benchdiff --new=${first_bad} --old=${last_good} --post-checkout='bash post-checkout.sh' --run=${test_name} --count=10 ${pkg_name} --cpuprofile
test binaries already exist for '2a2acee'; skipping build
test binaries already exist for 'f641415'; skipping build

  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/kv/kvserver \

name                        old time/op    new time/op    delta
BumpSideTransportClosed-24     245ns ± 0%     296ns ± 9%  +21.13%  (p=0.000 n=10+9)

name                        old alloc/op   new alloc/op   delta
BumpSideTransportClosed-24     0.00B          1.40B ±43%    +Inf%  (p=0.000 n=10+10)

name                        old allocs/op  new allocs/op  delta
BumpSideTransportClosed-24      0.00           0.00          ~     (all equal)

```

Nothing obvious is jumping out to me when looking at the patch or comparing CPU profiles (attached below). I'll toss this over to someone more familiar with AC (cc @aadityasondhi).

[profiles.zip](https://github.com/cockroachdb/cockroach/files/13461120/profiles.zip)

----

Note that you'll need to run the benchmark using go1.19. 

Jira issue: CRDB-33861

**Comment by aadityasondhi** [comment] 2023-12-12 18:35
Note to self: we should also check allocs

**Comment by aadityasondhi** [comment] 2023-12-12 19:45
alloc object:
<img width="1627" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/1cb16315-07fb-4608-bb1e-60c76500ce5a">

alloc space:
<img width="1618" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/63c68c0e-4bf2-43b7-a0d2-9f064fdd3a56">

Nothing really jumps out here, going to close this issue.

**Comment by nvanbenschoten** [comment] 2023-12-16 02:01
I'm finding that this commit (f641415bfa7116347ffb0614764972db245de10b) is also to blame for the regression we have been trying to hunt down in `ReturnOnRangeBoundary` (the last regression in https://github.com/cockroachdb/cockroach/issues/114310).
```
benchdiff --new=f641415b --post-checkout='bash post-checkout.sh' --run='ReturnOnRangeBoundary' --count=10 ./pkg/kv/kvclient/kvcoord
test binaries already exist for 'a438519'; skipping build
test binaries already exist for 'f641415'; skipping build

  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/kv/kvclient/kvcoord -

name                      old time/op    new time/op    delta
ReturnOnRangeBoundary-30     385µs ± 4%     458µs ±12%  +18.78%  (p=0.000 n=10+10)

name                      old alloc/op   new alloc/op   delta
ReturnOnRangeBoundary-30    93.6kB ± 0%    95.6kB ± 1%   +2.09%  (p=0.000 n=9+8)

name                      old allocs/op  new allocs/op  delta
ReturnOnRangeBoundary-30       763 ± 0%       779 ± 2%   +2.03%  (p=0.000 n=9+10)
```

It doesn't sound like we reached a full understanding of why the commit had this effect on `BenchmarkBumpSideTransportClosed`. That's concerning, given the significant impact we now know it had on multiple microbenchmarks.

I'll re-open this for now without re-applying the `GA-blocker` label. Still, before we release v23.2 it would be good to isolate the cause of the regression in that commit and decide what, if anything, we want to do about it.

**Comment by aadityasondhi** [comment] 2023-12-18 18:22
Ack. I will take a closer look at those changes (https://github.com/cockroachdb/cockroach/commit/f641415bfa7116347ffb0614764972db245de10b). Not too familiar with the work done there so might have been hasty at closing this. Thanks for re-surfacing this!

**Comment by aadityasondhi** [comment] 2024-01-11 22:35
Doing a diff between the old and new mem profiles has this:

<img width="590" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/44066a3a-3f76-4464-9bb5-57e595b6a9be">

**Comment by aadityasondhi** [comment] 2024-01-11 22:38
Based on the number of metric related entries in here. I wonder if https://github.com/cockroachdb/cockroach/pull/116581. Will try to see if those changes helped here.

**Comment by aadityasondhi** [comment] 2024-01-17 16:10
cpu profile diff seems to suggest mutex contention as a possible cause for extra cpu (time/op)

<img width="1728" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/00b0ccbf-bbab-4c23-8e22-3a16bf466930">

**Comment by aadityasondhi** [comment] 2024-01-17 19:05
adding some more data on allocs, seems to be flaky (between 1 and 0 B/op) in nature across runs of this benchmark:
```
BenchmarkBumpSideTransportClosed-10      5617202               203.0 ns/op             1 B/op          0 allocs/op
--- BENCH: BenchmarkBumpSideTransportClosed-10
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed1923299320
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed3010244981
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed3090654710
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed1306614561
        ... [output truncated]
BenchmarkBumpSideTransportClosed-10      6060468               192.2 ns/op             0 B/op          0 allocs/op
--- BENCH: BenchmarkBumpSideTransportClosed-10
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed3269332300
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed2917343095
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed748915223
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTransportClosed2392838720
        ... [output truncated]
BenchmarkBumpSideTransportClosed-10      6080515               192.9 ns/op             1 B/op          0 allocs/op
--- BENCH: BenchmarkBumpSideTransportClosed-10
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed3192514857
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed2641194731
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed1359826602
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed3425156504
        ... [output truncated]
BenchmarkBumpSideTransportClosed-10      5608111               185.9 ns/op             0 B/op          0 allocs/op
--- BENCH: BenchmarkBumpSideTransportClosed-10
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed2500898758
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed2210966116
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed428704004
    test_log_scope.go:79: use -show-logs to present logs inline
    replica_closedts_test.go:734: -- test log scope end --
    test_log_scope.go:161: test logs captured to: /Users/aadityasondhi/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/577bfc8ed46850d1aaafa923fa37ce78/logBenchmarkBumpSideTr
ansportClosed3482177157
```

**Comment by aadityasondhi** [comment] 2024-01-17 19:37
mutex profile with the change:

<img width="1728" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/ee3d28b5-13a5-4103-84cf-517d3025ab46">

mutex profile diff with previous:
<img width="1727" alt="image" src="https://github.com/cockroachdb/cockroach/assets/20070511/eda9141b-e7b2-4dcb-81ff-70fbc37f20af">

Seems to be more time spent waiting on mutexes but im not sure why from looking at the change or trying to find the call sites for these mutexes.

**Comment by aadityasondhi** [comment] 2024-01-17 19:44
Just for posterity reverting to 250ms by changing it [here](https://github.com/cockroachdb/cockroach/pull/103736/files#diff-6859ddf1742cf570545a4ce46c31f279f5f9b658adadfb75a71e674f2454e6d6R297) did nothing to help with the benchmark:
```
benchstat branch.txt 250ms.txt
name                        old time/op    new time/op    delta
BumpSideTransportClosed-10     196ns ± 9%     204ns ±13%   ~     (p=0.400 n=9+10)

name                        old alloc/op   new alloc/op   delta
BumpSideTransportClosed-10    0.60B ±100%    0.60B ±100%   ~     (p=1.000 n=10+10)

name                        old allocs/op  new allocs/op  delta
BumpSideTransportClosed-10      0.00           0.00        ~     (all equal)
```

**Comment by aadityasondhi** [comment] 2024-01-19 19:45
Ran it again with `-benchtime` setting. 
```
./dev bench pkg/kv/kvserver -f='BenchmarkBumpSideTransportClosed' --bench-mem --stream-output --test-args='-test.cpuprofile=cpu-branch.out -test.memprofile=mem-branch.out -test.mutexprofile=mutex-branch.out -test.benchtime=10000x' --ignore-cache | tee branch.txt
```

```
name                        old time/op    new time/op    delta
BumpSideTransportClosed-10    2.57µs ± 0%    7.54µs ± 0%   ~     (p=1.000 n=1+1)

name                        old alloc/op   new alloc/op   delta
BumpSideTransportClosed-10      144B ± 0%      255B ± 0%   ~     (p=1.000 n=1+1)

name                        old allocs/op  new allocs/op  delta
BumpSideTransportClosed-10      0.00           0.00        ~     (all equal)
```

[2024-01-19-tests.zip](https://github.com/cockroachdb/cockroach/files/13993763/2024-01-19-tests.zip)

**Comment by aadityasondhi** [comment] 2024-01-29 20:13
https://github.com/cockroachdb/cockroach/issues/115058#issuecomment-1901008986

CPU and heap profiles from this comment don't show anything that could point to the AC change. I am not sure what else I could look at, I have exhausted all options I knew of. Maybe we can close this issue, unless others have thoughts on where to take this next.

**Comment by aadityasondhi** [comment] 2024-01-30 21:30
Closing this based on the above comment. To view the profiles from that comment, download the zip and use:
```
 go tool pprof -diff_base=cpu-prev.out -http=localhost:12345 cpu-branch.out
``` 
cc @sumeerbhola

**Closed by aadityasondhi** 2024-01-30 21:30 UTC
Labels: C-bug, A-benchmarking, T-admission-control
