### ISSUE TITLE
sql: allow ARRAYs in forward indexes

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#17154] opened 2017-07-20 21:16 UTC
Arrays support inverted indexes, but not forward indexes. If you want to index arrays, starting in CockroachDB 20.1 consider using an inverted index on your column.

This issue tracks adding forward indexes to array types.

Jira issue: CRDB-6049

**Comment by bra-fsn** [comment] 2017-08-18 12:12
You should definitely implement it. :+1:

**Comment by bra-fsn** [comment] 2018-03-13 09:26
Any chance that this will be implemented?

**Comment by justinj** [comment] 2018-03-13 14:38
It's not currently planned for a release, it's on my to-do list to look into when I get some free time - can't promise anything at the moment though.

Out of curiosity, do you have any details on what you would use this for?

**Comment by bra-fsn** [comment] 2018-03-13 16:29
Sure. Currently I have two use cases:
1. tagging messages with labels (like important, later etc) and searching for messages which have a label or labels. Labels here are mostly strings or enums (a limited set which can grow in time).
2. tagging objects with location IDs. There can be a limited (but variable in the range of 1 to tens) number of locations for each object. Some have only one, some more. The location IDs here are numbers (integers). I want to search for objects which live on a given location ID. There can be millions-billions of them, so I want to page on the result set (of course maintaining consistency, so between the start and the end of the search, the result set should be consistent, fixed)

**Comment by ckome** [comment] 2018-05-06 18:36
You should definitely implement it. :)

**Comment by mzimmerman** [comment] 2019-02-10 02:06
My use case for this is storing all email addresses associated with each email I load into the DB.  I want to be able to search for all messages associated with one email address.

**Comment by jordanlewis** [comment] 2020-04-01 13:32
Arrays are now indexable via inverted indexes, which supports containment operations on the arrays. We still don't support ordinary forward indexes on arrays.

**Comment by knz** [comment] 2020-04-28 14:40
@rohany @RaduBerinde I think the recent key encoding for arrays will solve this issue?

(sorry I put this comment on an unrelated issue about JSON - this is the one about arrays)

**Comment by rohany** [comment] 2020-04-28 14:42
Yup, I've marked that PR as closing this (#48045)

**Comment by ajwerner** [comment] 2021-07-29 21:31
If and when we allow this we need to be careful of enum values in partitioning and how it interacts with dropping enum values.

**Comment by saurik** [comment] 2022-01-05 05:37
> Out of curiosity, do you have any details on what you would use this for?

@justinj FWIW, my use case is for storing tree-like data using a path encoding in the primary key (which is the correct way of doing it for the kinds of queries I am going to do). I can (and will) get by using a string-like type--and I haven't yet checked what operates you support for arrays and so if you wouldn't support an indexed "prefix of array matches [0,3,1]" (which I presume you would have to support for strings) it wouldn't really matter anyway--but it feels more "natural" to do this with arrays.

**Comment by ajwerner** [comment] 2022-08-23 22:08
This is the cause of https://github.com/prisma/prisma/issues/12282

**Comment by jordanlewis** [comment] 2022-11-11 19:01
> If and when we allow this we need to be careful of enum values in partitioning and how it interacts with dropping enum values.

Can you elaborate @ajwerner ?

**Comment by ajwerner** [comment] 2022-11-11 19:07
When we drop enum values we go and see if they are used anywhere. There's code to do this for arrays inside rows. There's also code which searches for enum values in partitioning descriptors. There will need to be code added to search for the values inside of enums used as partitioning values, assuming we support that. 

Consider a contrived transformation of [this test](https://github.com/cockroachdb/cockroach/blob/6700a17f3cf0f0614b132f2199e11cb5c7f05f0f/pkg/ccl/logictestccl/testdata/logic_test/partitioning_enum#L7-L19).

```
CREATE TYPE places AS ENUM ('us', 'eu', 'ap');
CREATE TABLE partitioned_table (
    place places[], id INT8,
    PRIMARY KEY (place, id)
)
    PARTITION BY LIST (place)
        (
            PARTITION us VALUES IN (ARRAY['us']),
            PARTITION eu VALUES IN (ARRAY['eu'])
        );
ALTER TYPE places DROP VALUE 'us';
```

The above should fail because `us` is used in a partitioning array. I don't think the logic [here](https://github.com/cockroachdb/cockroach/blob/47e60ac8a1139e990c84d60ab51b1c51227ea618/pkg/sql/type_change.go#L976-L983) would find it.

**Comment by jordanlewis** [comment] 2022-11-11 19:09
Indeed...


```
F221111 19:09:22.802901 2775 sql/opt_catalog.go:1456  [-] 314  error while decoding partition tuple: tabledesc.immutable: {ID: 106, Version: 1, ModificationTime: "1668193750.882603364,0", ParentID: 100, ParentSchemaID: 101, State: PUBLIC, NextColumnID: 3, Columns: [{ID: 1, TypeID: 100105, Null: false}, {ID: 2, TypeID: 20, Null: false}], NextFamilyID: 1, Families: [{ID: 0, Columns: [1, 2]}], PrimaryIndex: 1, NextIndexID: 2, Indexes: [{ID: 1, Unique: true, KeyColumns: [{ID: 1, Dir: ASC}, {ID: 2, Dir: ASC}]}]} []                                                                                           F221111 19:09:22.802901 2775 sql/opt_catalog.go:1456  [-] 314 !goroutine 2775 [running]:                                         
```

**Closed** 2022-11-19 00:15 UTC
Labels: C-enhancement, O-community, A-sql-encoding, X-anchored-telemetry
