### ISSUE TITLE
sql: add character index to PQ syntax errors

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20198] opened 2017-11-21 16:12 UTC
While the interactive SQL shell is able to provide a `DETAIL`  snippet with a caret symbol pointing to the symbol where syntax parsing failed, drivers (and our logic tests) will not propagate this information.

It'd be nice if we could highlight the index of the character in the string that caused the syntax parsing error, especially in complex queries.

For example the query
```
CREATE TABLE foo (id INT PRIMARY KEY, (a) INT))
```
Returns the error
```
pq: syntax error at or near "("
```
in `lib/pq`, which one can imagine can be ambiguous when there are numerous open parentheses.

Instead, we could return something like
```
pq: syntax error at or near "(" (character idx 38-39) 
```

cc: @vivekmenezes @awoods187

**Comment by knz** [comment] 2018-05-09 23:32
Duplicate of #25332

**Closed by knz** 2018-05-09 23:32 UTC
Labels: C-enhancement
