### ISSUE TITLE
server/ui: node status can still be written after files are forcibly deleted from underneath running CockroachDB instance

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#13615] opened 2017-02-16 07:33 UTC
Reported from the forum: https://forum.cockroachlabs.com/t/problems-when-i-testing-the-cluster/458

"""
I was testing a cluster, have 4 nodes,

node1 localhost:26251 /data/store1
node2 localhost:26252 /data/store2
node3 localhost:26253 /data/store3
node4 localhost:26254 /data/store4

when the cluster is running, i remove all the files of the node 4 , then restart all nodes.
i found these problems:

Admin UI can't work normally.

node number from 4 to 5.

and "View nodes list" cat not open.

Fortunately, "cockroach sql" can work on every node, and data is not lost.
"""

![screenshot](https://cdn-standard4.discourse.org/uploads/cockroachlabs/original/1X/30d53a6fdd9d66f620e587966f00d6e221d4e142.png)

**Comment by petermattis** [comment] 2017-02-16 13:19
The increase in the number of nodes from 4 to 5 is expected. By erasing the data directory for one of the nodes and then restarting it you effectively created a new node. We need to add a command to allow the removal of a node by node ID.

The `NaN`s for capacity used and unavailable ranges is unexpected and definitely a bug.

**Comment by andreimatei** [comment] 2017-02-16 15:42
@petermattis if we had a way to remove a node by ID, how would one know which node ids are in this situation (likely never to come back because we're now running a different node on that machine)? Should the UI help identify them?

**Comment by petermattis** [comment] 2017-02-16 22:01
> if we had a way to remove a node by ID, how would one know which node ids are in this situation (likely never to come back because we're now running a different node on that machine)? Should the UI help identify them?

Hopefully this would be indicated in the UI somehow. We'd certainly see that one of the nodes is not live, but there is probably something better that could be done. For example, identify that one of the nodes is not live and that a live node is using the same IP address and port as the dead node.

**Comment by mrtracy** [comment] 2017-03-21 19:55
The issue with duplicate node addresses is being tracked more succinctly in #12587.

This issue is fairly pathological: it does not reproduce it simply by deleting node 4's data - it reproduces if node 4's data is forcibly deleted _while node 4 is still running_.  Apparently, node 4 does not crash immediately, and actually proceeds to write node statuses normally which contain undefined values for some metrics.  That's what is causing the NaN and the node list crash - the node status still exists for that node, but it does not contain a metric we always expect it to contain.

There are a number of issues at play here:

1. Why is the node still running when all of its backing files have been forcibly deleted out from under it?  The node does seem to crash if you try to access the Admin UI, but i'm surprised it's able to call `Capacity()` on the engine in a way that does not cause a fatal exception.
2. This broke our assumption that all node status objects have defined metrics, and unfortunately in javascript `number + undefined === NaN`. This is a typical default value problem on this structure, sometimes these are messy to fix. Our options are to create a `GetStatusMetricOrZero(status, "metric-name")` function and use that every place we want to access a metric, or to use `status.metrics.get("metric-name") || 0` everywhere. Neither of these is lint or compiler enforceable, AFAIK.
We could also potentially fix this server-side, by writing "zero" for metrics instead of undefined values - we really do need to investigate why the server was writing incomplete statuses and not either crashing or writing zero numeric values.

**Comment by dianasaur323** [comment] 2017-04-19 22:38
@vivekmenezes do you know which milestone you want to move this one to? I'm trying to get rid of issues with no milestone. I think perhaps 1.1?

**Comment by tschottdorf** [comment] 2018-08-21 11:49
Closing as there hasn't been any activity for well over a year and I don't foresee any in the future.

**Closed by tschottdorf** 2018-08-21 11:49 UTC
Labels: C-bug, O-community, S-3-ux-surprise
