### ISSUE TITLE
sqlccl: import csv fails if csv file is empty

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19864] opened 2017-11-07 15:19 UTC
Reported in

https://forum.cockroachlabs.com/t/import-fails-when-csv-file-is-empty/1073

```
import TABLE group_discovery (
groupid bigint NOT NULL,
parent_group_prototypeid bigint NOT NULL,
name varchar(64) NOT NULL,
lastcheck integer NOT NULL,
ts_delete integer NOT NULL,
PRIMARY KEY (groupid)
)
csv data (‘nodelocal:///Users/ronr/Documents/werk/zabbix/data/group_discovery.csv’)
with temp=‘nodelocal:///tmp/tmp.txt’, nullif = ‘\N’;

pq: could not get first key
Error: pq: could not get first key
Failed running “sql”
```

cc @mjibson

**Comment by danhhz** [comment] 2017-11-07 15:29
Duplicate of https://github.com/cockroachdb/cockroach/issues/19834

**Closed by danhhz** 2017-11-07 15:29 UTC
