### ISSUE TITLE
circleci: failed tests (14960): TestCommitWaitState

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5443] opened 2016-03-21 20:03 UTC
The following test appears to have failed:

[#14960](https://circleci.com/gh/cockroachdb/cockroach/14960):

```
I160321 20:02:47.346619 client/db.go:422  failed batch: storage/replica_command.go:1664: split at key /Table/51 failed: node unavailable; try another peer
E160321 20:02:47.346708 storage/queue.go:444  [split] range=6 [/Table/50-/Max): error: storage/split_queue.go:100: unable to split range=6 [/Table/50-/Max) at key "/Table/51/0": storage/replica_command.go:1664: split at key /Table/51 failed: node unavailable; try another peer
I160321 20:02:47.346824 stopper.go:352  draining; tasks left:
1      storage/queue.go:381
I160321 20:02:48.344505 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:33203: getsockopt: connection refused"; Reconnecting to "127.0.0.1:33203"
panic: test timed out after 1m10s

goroutine 25940 [running]:
panic(0x1483480, 0xc8207ae1c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1bb3d88, 0x232dce0, 0x48, 0x48, 0xdb88401ab0627701)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820033f08, 0x11)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/sql_test.TestMain(0xc820033f08)
	/go/src/github.com/cockroachdb/cockroach/sql/main_test.go:234 +0x26
main.main()
	github.com/cockroachdb/cockroach/sql/_test/_testmain.go:382 +0x114

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2601d40)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 24256 [IO wait]:
net.runtime_pollWait(0x7f41dc6e9500, 0x72, 0xc820895000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820e62140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820e62140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820e620e0, 0xc820895000, 0x1000, 0x1000, 0x0, 0x7f41dc711050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8202cc008, 0xc820895000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc/transport.(*http2Client).reader(0xc820cf6870)
	/go/src/google.golang.org/grpc/transport/http2_client.go:754 +0xef
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 24136 [semacquire]:
sync.runtime_Semacquire(0xc820052094)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*WaitGroup).Wait(0xc820052088)
	/usr/local/go/src/sync/waitgroup.go:127 +0xb4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc820052070)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:302 +0x1dd
github.com/cockroachdb/cockroach/server.(*Server).Stop(0xc82041c270)
	/go/src/github.com/cockroachdb/cockroach/server/server.go:359 +0x28
github.com/cockroachdb/cockroach/server.(*TestServer).Stop(0xc820370030)
	/go/src/github.com/cockroachdb/cockroach/server/testserver.go:318 +0x5d
--
testing.tRunner(0xc820048000, 0x232e340)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 24169 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8205042a0)
	/go/src/google.golang.org/grpc/clientconn.go:511 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8205042a0)
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 24735 [select]:
google.golang.org/grpc.(*Conn).Wait(0xc820504000, 0x7f41dc6ebd00, 0xc8205c8000, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:552 +0x360
google.golang.org/grpc.(*unicastPicker).Pick(0xc820a914e0, 0x7f41dc6ebd00, 0xc8205c8000, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/picker.go:84 +0x51
google.golang.org/grpc.Invoke(0x7f41dc6ebd00, 0xc8205c8000, 0x1934c40, 0x1d, 0x17ad760, 0xc820c5d7c0, 0x179fee0, 0xc820f22800, 0xc8208660a0, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:154 +0x6d0
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc8202cc4a0, 0x7f41dc6ebd00, 0xc8205c8000, 0xc820c5d7c0, 0x0, 0x0, 0x0, 0xc82107be08, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc820e6c6c0, 0xc8208660a0, 0xc820d649d0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:187 +0x2b5
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820052070, 0xc820614060)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 24170 [chan receive]:
github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1.1(0x7f41dc6e8408, 0xc820bb3880, 0xc820a0c460, 0xc820a095b0, 0xf)
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:177 +0x51
created by github.com/cockroachdb/cockroach/server.RegisterAdminHandlerFromEndpoint.func1
	/go/src/github.com/cockroachdb/cockroach/server/admin.pb.gw.go:181 +0x205

goroutine 24254 [select]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820799200)
	/go/src/google.golang.org/grpc/transport/http2_server.go:610 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 24734 [sleep]:
time.Sleep(0x6119b9a2)
	/usr/local/go/src/runtime/time.go:59 +0xf9
google.golang.org/grpc.(*Conn).resetTransport(0xc820504000, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/clientconn.go:461 +0x79f
google.golang.org/grpc.NewConn.func1(0xc820504000)
	/go/src/google.golang.org/grpc/clientconn.go:317 +0x2a
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:323 +0x509

goroutine 24255 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820cf6870)
	/go/src/google.golang.org/grpc/transport/http2_client.go:831 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 24152 [IO wait]:
net.runtime_pollWait(0x7f41dc6e86c0, 0x72, 0xc82035c000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820e621b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820e621b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820e62150, 0xc82035c000, 0x1000, 0x1000, 0x0, 0x7f41dc711050, 0xc820010048)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8202cc000, 0xc82035c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
google.golang.org/grpc.(*Server).handleRawConn(0xc820ebd180, 0x7f41dc71fe20, 0xc8203de0b0)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 24143 [chan receive]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc820c814a0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:135 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:136 +0x7c9
FAIL	github.com/cockroachdb/cockroach/sql	70.071s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-03-22 12:58
Dupe of #5424

**Closed by bdarnell** 2016-03-22 12:58 UTC
Labels: Robot, test-failure
