### ISSUE TITLE
Data race in pebble

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#55169] opened 2020-10-02 13:07 UTC
**Describe the problem**

There is a race between reading and writing the field `written` in struct
```
type block struct {
	// buf[:written] has already been filled with fragments. Updated atomically.
	written int32
	// buf[:flushed] has already been flushed to w.
	flushed int32
	buf     [blockSize]byte
}
```
from file `pebble/internal/record/log_writer.go`

**To Reproduce**

I am unable to reproduce locally. There is a stack trace on TC: https://teamcity.cockroachdb.com/downloadBuildLog.html?buildId=2340048&plain=true
See also https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=2340048&_focus=6145&consoleStyle=true which is the same data but in structured format.

The failure occurs when testing this PR https://github.com/cockroachdb/cockroach/pull/54017.

**Comment by spaskob** [comment] 2020-10-02 13:10
The stack trace from the above link is hard to read - I have transformed it here:
```
=== RUN   TestInvalidObjects
WARNING: DATA RACE
Read at 0x00c001210000 by goroutine 36:

  github.com/cockroachdb/pebble/internal/record.(*LogWriter).emitEOFTrailer()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:625 +0x5b

  github.com/cockroachdb/pebble/internal/record.(*LogWriter).Close()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:540 +0x3e

  github.com/cockroachdb/pebble.(*DB).Close()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:876 +0x38e

  github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close()

      /go/src/github.com/cockroachdb/cockroach/pkg/storage/pebble.go:610 +0xe5

  github.com/cockroachdb/cockroach/pkg/server.(*Engines).Close()

      /go/src/github.com/cockroachdb/cockroach/pkg/server/config.go:452 +0x8d

  github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop()

      /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:518 +0x540

  github.com/cockroachdb/cockroach/pkg/sql_test.TestInvalidObjects()

      /go/src/github.com/cockroachdb/cockroach/pkg/sql/crdb_internal_test.go:493 +0xf87

  testing.tRunner()

      /usr/local/go/src/testing/testing.go:909 +0x199


Previous write at 0x00c001210000 by goroutine 474:

  sync/atomic.StoreInt32()

      /usr/local/go/src/runtime/race_amd64.s:229 +0xb

  github.com/cockroachdb/pebble/internal/record.(*LogWriter).emitFragment()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:659 +0x56b

  github.com/cockroachdb/pebble/internal/record.(*LogWriter).SyncRecord()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/internal/record/log_writer.go:593 +0x9e

  github.com/cockroachdb/pebble.(*DB).commitWrite()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:650 +0x2bb

  github.com/cockroachdb/pebble.(*DB).commitWrite-fm()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:601 +0x63

  github.com/cockroachdb/pebble.(*commitPipeline).prepare()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:377 +0x347

  github.com/cockroachdb/pebble.(*commitPipeline).Commit()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/commit.go:253 +0xd0

  github.com/cockroachdb/pebble.(*DB).Apply()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/db.go:556 +0x200

  github.com/cockroachdb/cockroach/pkg/storage.(*pebbleBatch).Commit()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/pebble/batch.go:727 +0xcc

  github.com/cockroachdb/cockroach/pkg/storage.WriteSyncNoop()

      /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine.go:652 +0xeb

  github.com/cockroachdb/cockroach/pkg/kv/kvserver.Server.WaitForApplication.func1()

      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores_server.go:114 +0x269

  github.com/cockroachdb/cockroach/pkg/kv/kvserver.Server.execStoreCommand()

      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores_server.go:42 +0x93

  github.com/cockroachdb/cockroach/pkg/kv/kvserver.Server.WaitForApplication()

      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/stores_server.go:88 +0xa9

  github.com/cockroachdb/cockroach/pkg/kv/kvserver._PerReplica_WaitForApplication_Handler.func1()

      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:281 +0xa1

  github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/server.go:44 +0xbd8

  google.golang.org/grpc.getChainUnaryHandler.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x146

  github.com/cockroachdb/cockroach/pkg/rpc.NewServer.func1()

      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:199 +0x135

  google.golang.org/grpc.getChainUnaryHandler.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:921 +0x146

  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor()

      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:60 +0xbe

  github.com/cockroachdb/cockroach/pkg/rpc.kvAuth.unaryInterceptor-fm()

      /go/src/github.com/cockroachdb/cockroach/pkg/rpc/auth.go:47 +0x80

  google.golang.org/grpc.chainUnaryServerInterceptors.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:907 +0x110

  github.com/cockroachdb/cockroach/pkg/kv/kvserver._PerReplica_WaitForApplication_Handler()

      /go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/storage_services.pb.go:283 +0x1d8

  google.golang.org/grpc.(*Server).processUnaryRPC()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1082 +0x954

  google.golang.org/grpc.(*Server).handleStream()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:1405 +0x12bd

  google.golang.org/grpc.(*Server).serveStreams.func1.1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:746 +0xc8


Goroutine 36 (running) created at:

  testing.(*T).Run()

      /usr/local/go/src/testing/testing.go:960 +0x651

  testing.runTests.func1()

      /usr/local/go/src/testing/testing.go:1202 +0xa6

  testing.tRunner()

      /usr/local/go/src/testing/testing.go:909 +0x199

  testing.runTests()

      /usr/local/go/src/testing/testing.go:1200 +0x521

  testing.(*M).Run()

      /usr/local/go/src/testing/testing.go:1117 +0x2ff

  github.com/cockroachdb/cockroach/pkg/sql_test.TestMain()

      /go/src/github.com/cockroachdb/cockroach/pkg/sql/main_test.go:32 +0x15b

  main.main()

      _testmain.go:682 +0x223


Goroutine 474 (finished) created at:

  google.golang.org/grpc.(*Server).serveStreams.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:744 +0xb8

  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/http2_server.go:442 +0x16a6

  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/internal/transport/http2_server.go:483 +0x459

  google.golang.org/grpc.(*Server).serveStreams()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:742 +0x19a

  google.golang.org/grpc.(*Server).handleRawConn.func1()

      /go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/server.go:703 +0x4c
```

**Comment by petermattis** [comment] 2020-10-02 13:57
The suspicion from the Storage team is that there is a misuse of Pebble's contract and the race is closing the DB with using the DB. @spaskob also had a failure with the `pebble: closed` error which could be caused by the same underlying problem.

@tbg Do we still have some sort of teardown problem? @spaskob says his test isn't doing anything fancy:

```
	defer leaktest.AfterTest(t)()
	defer log.Scope(t).Close(t)
	s, sqlDB, _ := serverutils.StartServer(t, base.TestServerArgs{})
	defer s.Stopper().Stop(context.Background())
```

**Comment by spaskob** [comment] 2020-10-02 14:08
This is the test that cause the race: https://github.com/cockroachdb/cockroach/pull/54017/commits/d6106e5150f7f8be507b0b35131032b650330110#diff-8f7a31e2deeced9435b09a82aada5f4d

**Comment by spaskob** [comment] 2020-10-02 15:07
Courtesy of @ajwerner https://github.com/cockroachdb/cockroach/issues/51544

**Comment by ajwerner** [comment] 2020-10-02 15:27
Closing as dupe of #51544. The race is theoretically pretty widely possible but in practice because clients tend to shut down reasonably, the primary source of the race seems to be due to range merges that happen asynchronously due to operations at the end of tests which drop tables.

**Closed by ajwerner** 2020-10-02 15:27 UTC
Labels: A-storage, C-bug
