### ISSUE TITLE
sql: unexpected output change for `SHOW GRANTS`

### ISSUE THREAD

**Issue by Amruta-Ranade** [cockroachdb/cockroach#47147] opened 2020-04-07 20:22 UTC
We noticed a change in SQL output on running `SHOW GRANTS` for admin users on CC.

Before (CC clusters running 19.2.4):
![Screen Shot 2020-04-07 at 3 22 08 PM](https://user-images.githubusercontent.com/11484018/78715599-a048e180-78eb-11ea-9814-01013887819a.png)

After: (CC clusters running 19.2.5/ also checked on a local 20.1 cluster):
<img width="1078" alt="Screen Shot 2020-04-07 at 3 27 37 PM" src="https://user-images.githubusercontent.com/11484018/78715623-ab037680-78eb-11ea-9026-e7d3584ee798.png">

Don't know if this is a bug/regression/expected behavior. Wanted to put on your radar though.

**Comment by RichardJCai** [comment] 2020-04-07 22:17
I tried to reproduce this on a 19.2.4 cluster and this is the output I got
```➜  cockroach-v19.2.4.darwin-10.9-amd64 ./cockroach demo
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 1 node.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional vehicle sharing company).
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# Web UI: http://127.0.0.1:62745
#
# Server version: CockroachDB CCL v19.2.4 (x86_64-apple-darwin14, built 2020/02/06 21:49:44, go1.12.12) (same version as client)
# Cluster ID: 16466d6f-aac2-4122-bfaa-7ad3a73d8814
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:62747/movr> create user db_admin;
CREATE USER 1

Time: 3.206ms

root@127.0.0.1:62747/movr> grant admin to db_admin;
GRANT

Time: 29.897ms

root@127.0.0.1:62747/movr> show grants for db_admin;
  database_name | schema_name | table_name | grantee | privilege_type
+---------------+-------------+------------+---------+----------------+
(0 rows)

Time: 4.113ms

root@127.0.0.1:62747/movr>```

It's not showing me any grants for 19.2.4 on db_admin after I create db_admin and run `GRANT admin TO db_admin` 

I'm confused why db_admin has this output on CC in 19.2.4 since db_admin is created through `CREATE USER 'db_admin' WITH PASSWORD 'foobar';` then running `GRANT admin TO db_admin;`

Furthermore this behaviour is consistent with 19.2.2 and 20.1.

**Comment by RichardJCai** [comment] 2020-04-07 22:37
I believe the grants shouldn't appear so it's strange that it even appeared on the 19.2.4 cluster unless someone specifically granted those privileges to db_admin.

Spoke with @DuskEagle and he could not reproduce the output on another 19.2.4 cluster - grants were not appearing for db_admin.

Closing for now.

**Closed by RichardJCai** 2020-04-07 22:37 UTC
Labels: C-investigation
