### ISSUE TITLE
sql: UPDATE while schema change can result in error

### ISSUE THREAD

**Issue by dendon** [cockroachdb/cockroach#33260] opened 2018-12-19 08:42 UTC
**Describe the problem**

doing UPDATEs can result in errors while a CREATE INDEX is running.

error message & query:
```
ERROR:  value type is not BYTES: UNKNOWN
UPDATE "cache" SET "value" = $1, "updated" = $2, "expires" = $3 WHERE "id" = $4
```
schema:
```
CREATE TABLE cache
(
  id SERIAL PRIMARY KEY
);

ALTER TABLE cache ADD COLUMN method STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_method;
ALTER TABLE cache ADD COLUMN name STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_name;
ALTER TABLE cache ADD COLUMN value STRING NOT NULL DEFAULT '' CREATE IF NOT EXISTS FAMILY family_value;
ALTER TABLE cache ADD COLUMN locked INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_locked;
ALTER TABLE cache ADD COLUMN created INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_created;
ALTER TABLE cache ADD COLUMN updated INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_updated;
ALTER TABLE cache ADD COLUMN expires INT NOT NULL DEFAULT 0 CREATE IF NOT EXISTS FAMILY family_expires;

CREATE INDEX method_name ON cache (method, name);
```

schema change:
```
CREATE INDEX method_name_storing_value ON cache (method, name) STORING (value);
```

**Environment:**
CockroachDB CCL v2.1.2 (x86_64-unknown-linux-gnu, built 2018/12/10 20:15:47, go1.10.3)

**Comment by knz** [comment] 2018-12-19 14:36
@dendon thank you for your report. Can you help us investigate further? How did you run the test?

I would like to know if the error occurs when UPDATE is issued cocnurrently with the first or the second CREATE INDEX.

Also are you able to reproduce this error consistently? If so we would be interested in enclosing the UPDATE statement as follows:

```
EXPLAIN(VERBOSE) UPDATE ...; -- save the plan every time the UPDATE is executed
SET tracing = on; 
UPDATE ...; -- as you did previously
SET tracing = off;
-- then only if the UPDATE fails:
SHOW TRACE FOR SESSION;
```

Then as soon as you see the UPDATE fail with the error please report both the logical plan and the session trace.

**Comment by knz** [comment] 2018-12-19 14:37
cc @vivekmenezes we'll need to investigate this too

**Comment by dendon** [comment] 2018-12-19 14:55
Hey @knz, I actually did not run any test, it just happened on the production system, which also means I rather don't want to run any actual test on the system.

I ran the second CREATE INDEX, the one included in the schema is already in there for some time.

But since I run everything twice (one time on the dev system and one time on the production), it's either related to the size and or the workload, as it didn't happened on the dev system.

**Comment by vivekmenezes** [comment] 2018-12-19 15:14
This is appears to be a problem with a value not containing the right tag type. Not something easy to debug but I'll give it a shot.

**Comment by vivekmenezes** [comment] 2019-02-07 16:08
@dt assigning to you since you have been able to reproduce.

**Comment by dt** [comment] 2019-02-07 17:21
Reproduction details are in #34683 -- I'll probably aim to make that workload to a roachtest.

**Comment by dt** [comment] 2019-02-22 00:29
@jordanlewis and I dug into this for a couple hours today. My workload does updates on a k/v-ish table, only updating the values -- no inserts. When I added an index *that stores* the value, the updates immediate got this error. Indeed, this reproduces with `kv` when you do `CREATE INDEX ON kv(k) STORING (v)`.

Digging deeper, we figured out that this error is coming out of row fetcher when it is trying to decode the kv for the purpose of the uniqueness error helper... but that only added to the mystery: why are we generating uniqueness errors for updates to existing keys that don't change the keys, just the values?

We tracked it down to our CPuts -- we cput from the old value to the new value, but if the backfill hasn't yet created that index entry, then there's no old value. This normally ends up working, since most indexes don't have values either way, but for STORING indexes, they do, so an unbackfilled row will always fail.

**Comment by knz** [comment] 2019-02-22 03:36
Wow, amazing investigation.

This has probably been broken forever. I am so glad you figured it out!!!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dt** [comment] 2019-02-22 13:31
Yeah, I'm pretty sure this has been broken forever, but it is hard to hit without STORING (or whatever composite is).

Absent STORING, for non-unique indexes, entries never have values, so I think the CPut always runs with nil as its expected value.

With stored columns, it runs with its old value.

I'm still scratching my head trying to figure out if this is even possible to fix with our current KV API primitives: We want a put op that refuses to overwrite a row unless it has exactly the value we think it has -- so that we're sure we're not clobbering an entry for a different row in a unique index -- but is allowed to write if there's no value. AFAIK, that isn't a primitive we have right now.

- CPut only allows specifying exactly one expected value. 
- InitPut has the "or if empty" semantics, but doesn't let you change from old to new -- just from `nothing` to `new` or `new` to `new`. It is thus only useful in the backfiller.

Initially I was thinking we could just try `CPut`ting with expected first and then on error with nothing, but we do whole batches of of updates at once, so that would get pretty messy pretty quickly.

I'm currently thinking we need new semantics from KV to fix this. Specifically, we need to further parameterize `CPut` with an "allow empty` flag. Alternatively, @jordanlewis suggested generalizing that and instead making the expected value to `CPut` variadic, so you could supply multiple expected values, of which the actual value must be one, and then supply empty and old for index updates during backfills. 

I think I'm leaning slightly towards the smaller change of just adding the "allow empty" flag just since I think empty is slightly special and adding just bool flag it is slightly smaller change in semantics to think about, but I could go either way.

cc usual suspects @bdarnell @knz @jordanlewis

**Comment by knz** [comment] 2019-02-22 13:36
All these ideas look fine to me. Be mindful with variadic arguments that it may increase the complexity of the data structure and bump a constant in the time/space complexity of kv batch execution.

**Comment by bdarnell** [comment] 2019-02-22 16:30
Yeah, it sounds like we need an "allow empty" flag for CPut. If we do that, can we fold InitPut back into CPut? The original reason it was a separate method was to avoid a boolean argument on CPut (#6072). However, they've diverged since then (and re-converged in some cases like timestamp cache handling).

InitPut has another option failOnTombstone. Tombstones are a special kind of "empty". Does CPut with this new option also need to fail on tombstones for the same reason as InitPut?

**Comment by dt** [comment] 2019-02-22 17:22
yeah, I think we would be able to fold InitPut usage into such a CPut, though I'm hesitant to do that until after 19.1 is cut.

**Comment by dt** [comment] 2019-02-22 23:20
Discussion continuing on #35157.

**Closed** 2019-02-26 21:49 UTC
Labels: A-schema-changes, A-sql-mutations, C-bug, S-3-erroneous-edge-case
