### ISSUE TITLE
Test failure in CI build 1006

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#508] opened 2015-03-30 14:20 UTC
The following test appears to have failed:

[#1006](https://circleci.com/gh/cockroachdb/cockroach/1006):

```
I0330 14:18:47.173111     261 multiraft.go:644] Committed Entry[0]: 6/13 EntryNormal 13d04c7051f3f38745a6e3cafccae224: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1427725127171437447 random:5018949295715050020 > user:"" repli
I0330 14:18:47.174097     261 kv.go:125] failed Increment: mvcc.go:450: attempted access to empty key
I0330 14:18:47.174157     261 retry.go:85]  failed an iteration: mvcc.go:450: attempted access to empty key
I0330 14:18:47.174201     261 retry.go:100]  failed; retrying in 50ms
==================
WARNING: DATA RACE
Write by goroutine 54:
  github.com/cockroachdb/cockroach/storage.TestAllocateErrorAndRecovery()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc_test.go:162 +0x874
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 74:
  github.com/cockroachdb/cockroach/storage.func·009()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:114 +0x24e
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/storage.(*IDAllocator).allocateBlock()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:118 +0x158
  github.com/cockroachdb/cockroach/storage.func·008()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:92 +0x7a

Goroutine 54 (running) created at:
I0330 14:18:47.173111     261 multiraft.go:644] Committed Entry[0]: 6/13 EntryNormal 13d04c7051f3f38745a6e3cafccae224: raft_id:1 cmd:<increment:<header:<timestamp:<wall_time:0 logical:7 > cmd_id:<wall_time:1427725127171437447 random:5018949295715050020 > user:"" repli
I0330 14:18:47.174097     261 kv.go:125] failed Increment: mvcc.go:450: attempted access to empty key
I0330 14:18:47.174157     261 retry.go:85]  failed an iteration: mvcc.go:450: attempted access to empty key
I0330 14:18:47.174201     261 retry.go:100]  failed; retrying in 50ms
==================
WARNING: DATA RACE
Write by goroutine 54:
  github.com/cockroachdb/cockroach/storage.TestAllocateErrorAndRecovery()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc_test.go:162 +0x874
  testing.tRunner()
      /usr/src/go/src/testing/testing.go:447 +0x133

Previous read by goroutine 74:
  github.com/cockroachdb/cockroach/storage.func·009()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:114 +0x24e
  github.com/cockroachdb/cockroach/util.RetryWithBackoff()
      /go/src/github.com/cockroachdb/cockroach/util/retry.go:80 +0x6d
  github.com/cockroachdb/cockroach/storage.(*IDAllocator).allocateBlock()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:118 +0x158
  github.com/cockroachdb/cockroach/storage.func·008()
      /go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:92 +0x7a

Goroutine 54 (running) created at:

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2015-03-30 14:26
The data race looks real, but the test failure seems to be some sort of linux container issue. 

Duplicate of #507.

**Comment by petermattis** [comment] 2015-03-30 14:54
Duplicate of #501

**Closed** 2015-03-30 15:24 UTC
Labels: test-failure
