### ISSUE TITLE
*log.safeError: stopper.go:179: infostore.go:198

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#22467] opened 2018-02-07 18:31 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/452439620/

```
*log.safeError: stopper.go:179: infostore.go:198
  File "github.com/cockroachdb/cockroach/pkg/gossip/infostore.go", line 198, in addInfo
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 842, in addInfoLocked
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 836, in AddInfo
  File "github.com/cockroachdb/cockroach/pkg/gossip/gossip.go", line 856, in AddInfoProto
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 5607, in MaybeGossipNodeLiveness
...
(12 additional frame(s) were not displayed)

stopper.go:179: infostore.go:198
```

**Comment by arjunravinarayan** [comment] 2018-02-07 18:32
https://sentry.io/cockroach-labs/cockroachdb/issues/452439991/

Assigning to @nvanbenschoten for triaging, as this sentry report has pretty little to go on. The alpha build is a little old - is this an issue that has been resolved in subsequent alphas?

**Comment by a-robinson** [comment] 2018-02-07 18:35
Dupe of https://github.com/cockroachdb/cockroach/issues/20986. It's unfortunate this wasn't on a more recent build, since we've since added extra diagnostic info to this `log.Fatal`.

**Closed by a-robinson** 2018-02-07 18:35 UTC

**Comment by arjunravinarayan** [comment] 2018-02-07 20:12
Thank you for the rapid triage @a-robinson!
