### ISSUE TITLE
Insertion error:  RETRY_COMMIT_DEADLINE_EXCEEDED

### ISSUE THREAD

**Issue by agaganin** [cockroachdb/cockroach#51586] opened 2020-07-19 11:56 UTC
hi dear!

When doing multiple batch-inserts into a table after a few minutes, I get this error:
org.postgresql.util.PSQLException: ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_COMMIT_DEADLINE_EXCEEDED - txn timestamp pushed too much; deadline exceeded by 1m53.542091563s (1595158747.005378403,2 > 1595158633.463286840,0)): meta={id=b8f4317e key=/Table/58/1/573728451218866177/0 pri=0.00777231 epo=0 ts=1595158747.005378403,2 min=1595158428.310706348,0 seq=5001} lock=true stat=PENDING rts=1595158747.005378403,2 wto=false max=1595158428.330175001,0

**Comment by jordanlewis** [comment] 2020-11-10 04:29
This is expected behavior. Please read our documentation on retry errors.

Closing due to age and lack of actionability.

**Closed by jordanlewis** 2020-11-10 04:29 UTC
Labels: A-kv-transactions, C-investigation, O-community, X-blathers-oncall
