### ISSUE TITLE
sql: suboptimal query plan improved by manual index selection

### ISSUE THREAD

**Issue by vilterp** [cockroachdb/cockroach#24297] opened 2018-03-28 19:24 UTC
This user got a slow query, and was able to speed it up by forcing an index selection with the `table@index` syntax: https://forum.cockroachlabs.com/t/how-to-improve-cockroachdb-query-performance/1461

This may be a known issue, but they (and I) would be interested in some explanation of why the manually-chosen index was faster.

### Setup:
- 8M rows
- 10 nodes
- CockroachDB V2.0 20180326

### Schema: (copy pasted / cleaned up from the forum)
```sql
CREATE TABLE t_sync_data (
    remote_id UUID NOT NULL,
    conflict_remote_id UUID NULL,
    user_id UUID NOT NULL,
    last_sync_id INT NOT NULL,
    data_type STRING NOT NULL,
    sync_data STRING NULL,
    deleted BOOL NOT NULL,
    create_device_id STRING NOT NULL,
    original_data_id STRING NOT NULL,
    create_time INT NOT NULL,
    last_update_time INT NOT NULL,
    CONSTRAINT “primary” PRIMARY KEY (remote_id ASC),
    INDEX t_sync_data_user_id_data_type_idx (user_id ASC, data_type ASC),
    INDEX t_sync_data_last_sync_id_idx (last_sync_id ASC),
    FAMILY f_meta (remote_id, conflict_remote_id, user_id, last_sync_id, data_type, deleted, create_device_id, original_data_id, create_time, last_update_time),
    FAMILY f_data (sync_data)
)

CREATE INDEX ON t_sync_data (last_sync_id, user_id, data_type);
CREATE INDEX ON t_sync_data (user_id, data_type);
CREATE INDEX ON t_sync_data (last_sync_id);
```

### Original (slow) query and plan:

~6sec

```
SELECT *
FROM t_sync_data
WHERE last_sync_id>0
  AND user_id='11cd19e4-837d-4bff-4a76-aefa0ddbec64'
  AND data_type='a01'
ORDER BY last_sync_id ASC
LIMIT 50;
±------------------------±-------±---------------------------------------------------------------+
| Tree                   | Field | Description                                                   |
±------------------------±-------±---------------------------------------------------------------+
| limit                  |       |                                                               |
| └── render             |       |                                                               |
| └── index-join         |       |                                                               |
| ├── scan               |       |                                                               |
| │                      | table | t_sync_data@t_sync_data_last_sync_id_user_id_data_type_idx    |
| │                      | spans | /1/"!\xcd\x19\xe4\x83}K\xffJv\xae\xfa\r\xdb\xecd"/“highlight”-|
| └── scan               |       |                                                               |
|                        | table | t_sync_data@primary                                           |
±------------------------±------±----------------------------------------------------------------+
(8 rows)
```

### Faster query:

~50ms

```
SELECT *
FROM t_sync_data@t_sync_data_user_id_data_type_idx
WHERE last_sync_id>0
  AND user_id='11cd19e4-837d-4bff-4a76-aefa0ddbec64'
  AND data_type='a01'
ORDER BY last_sync_id ASC
LIMIT 50;
```

**Comment by andy-kimball** [comment] 2018-08-25 01:07
The cost-based optimizer uses the `t_sync_data_user_id_data_type_idx` index, since it deems the cost of a more selective index + explicit sort less than a less selective index without a sort. Closing this one down. Added regression case to `opt/xform/testdata/external/customer`.

**Closed by andy-kimball** 2018-08-25 01:07 UTC
Labels: A-sql-planning, C-question

**Comment by vilterp** [comment] 2018-08-27 21:09
Excellent; thanks!
