### ISSUE TITLE
Postgresql JDBC driver hangs with certain sequence of queries

### ISSUE THREAD

**Issue by ruzkant** [cockroachdb/cockroach#24578] opened 2018-04-07 09:06 UTC
Log header:
I180407 08:17:30.775591 203 util/log/clog.go:1001  [config] file created at: 2018/04/07 08:17:30
I180407 08:17:30.775591 203 util/log/clog.go:1001  [config] running on machine: zachv-T460s
I180407 08:17:30.775591 203 util/log/clog.go:1001  [config] binary: CockroachDB CCL v2.0.0 (x86_64-unknown-linux-gnu, built 2018/04/03 20:56:09, go1.10)
I180407 08:17:30.775591 203 util/log/clog.go:1001  [config] arguments: [cockroach start --insecure --host=localhost --http-port 26280 --verbosity=1]

Postgresql driver: 42.2.2

I have a github repo that duplicates the issue:
https://github.com/ruzkant/cockroachdb-issue

- What did you do?
I found it when running a project (flowable) that creates the database tables after checking the database metadata from the jdbc driver to see if tables already exist. This is done in a transaction.

After lots of experimentation I narrowed it down not to the metadata queries in the driver specifically. So the project above recreates the issue by running the following sequence of queries:
1. show tables (or any other select query)
2. create table
3. insert into new table

- What did you expect to see?
The database table created and a record inserted.

While I know cockroach does not support DML's following by DDL's, in this case it is a simple query before the DDL, which works when run using cockroach commandline client.

Even if not really supported , then at least it shouldn't hang the driver, but generate an exception,  

- What did you see instead?
The postgres driver just hangs after the insert statement. Specifically it hangs after writing protocol data to cockroach socket and when trying to receive response data. It does not get any data back, hanging immediately on first read.

There is a variation where a delay between the select and the create table causes an exception on the insert.

I suspect this is some wire protocol issue, especially considering the timing issue when adding delays, but I don't know much about it.

**Comment by petermattis** [comment] 2018-04-07 12:47
@ruzkant Thanks for the report. We'll take a look.

**Comment by jordanlewis** [comment] 2018-04-08 14:31
I think there's a bug in the table lease acquiring code that's causing this. Specifically, the following sequence of statements occurs:

```
BEGIN TRANSACTION;
SHOW TABLES;
CREATE TABLE t...
INSERT INTO TABLE t...
```

All of these statements are prepared via pgwire. The `INSERT` fails during preparation. If you run with `--vmodule=table=2`, you can see that it hangs when trying to acquire the table lease for `t`, in `TableCollection.getTableVersion`.

I believe the actual hang inside of that method is `tc.leaseMgr.AcquireByName`. I stopped tracing at that point. I think this is definitely a real issue though, and it reminds me of a problem that the Flyway folks were seeing in their integration work for 2.0.

**Comment by jordanlewis** [comment] 2018-04-08 20:27
cc @vivekmenezes

**Comment by vivekmenezes** [comment] 2018-04-09 13:40
likely related to https://github.com/cockroachdb/cockroach/issues/23718

**Comment by vivekmenezes** [comment] 2018-04-09 13:57
@jordanlewis I'm unable to reproduce this using https://github.com/cockroachdb/cockroach/pull/23816

Any thoughts?

**Comment by jordanlewis** [comment] 2018-04-09 14:00
It's only the pgwire `PREPARE` pathway that causes this issue.

You may be able to reproduce with `SQL PREPARE` as well.

Try 

```
PREPARE x AS insert into m3 (id, acol) VALUES (1, 'text with ; sign')
```

**Comment by vivekmenezes** [comment] 2018-04-09 14:06
yes that does it

**Comment by vivekmenezes** [comment] 2018-04-17 17:17
closed by https://github.com/cockroachdb/cockroach/pull/23816

**Comment by vivekmenezes** [comment] 2018-04-17 17:18
cherry picking into 2.0

**Closed** 2018-04-17 17:17 UTC
