### ISSUE TITLE
sql: not able to update column in cockroach-sequelize db

### ISSUE THREAD

**Issue by karnprem90** [cockroachdb/cockroach#17173] opened 2017-07-23 09:31 UTC
.save() function is not working in cockroach-sequelize db. I am getting this error.
error: unsupported comparison operator: <int> = <string>

**Comment by benesch** [comment] 2018-04-24 13:16
Hmm, sounds like there's something particular about your schema that's causing the error. Could you post your model definition?

**Comment by knz** [comment] 2018-07-23 12:24
cc @tim-o for further qualification / next steps

**Comment by tim-o** [comment] 2018-07-23 14:09
@karnprem90  - if you need further assistance here, let us know - in the meantime I'll close the issue since we couldn't reproduce. Apologies again for the significant delay in response originally.

**Closed by tim-o** 2018-07-23 14:09 UTC
Labels: A-sql-pgcompat, C-investigation, O-community
