### ISSUE TITLE
sql: lib/pq confused by unicode characters in text[], while psql is OK with them

### ISSUE THREAD

**Issue by dmkret** [cockroachdb/cockroach#31872] opened 2018-10-25 14:09 UTC
russian character \u0422 'Т' (capital te) not saved well if it's inside of a string array.

**To Reproduce**
```golang
import "github.com/lib/pq"
...
rows, err := db.Query("SELECT ARRAY ['У, 'Л', 'Т']")
for rows.Next() {
    var value pq.StringArray
    rows.Scan(&value)
    fmt.Println(value)
}

output for cockroachdb> {"У", "Л" ,"\u0422"}
output for postgresql> {"У", "Л", "Т"}
```

**Environment:**
 - CockroachDB version: 2.0.6
 - Client app: `cockroach sql`, `golang: pq`

**Comment by knz** [comment] 2018-10-25 14:19
Thanks Anton for your problem report. 
The problem is strictly in the Go driver `lib/pq` not in CockroachDB.

If you use the `psql` command from PostgreSQL and connect it to a CockroachDB server, you will see the right output:

```
kena@kenabook ~/cockroach % psql -U root -h localhost -p 26257
psql (10.5 (Ubuntu 10.5-0ubuntu0.18.04), server 9.5.0)
Type "help" for help.

root=# SELECT ARRAY ['У', 'Л', 'Т'];
     array
---------------
 {"У","Л","Т"}
(1 row)
```

Note also that we are aware of numerous problems with `lib/pq`. At this time we recommend using `pgx` instead, although the particular Unicode situation you are facing may not be handled by `pgx` either (you'd need to check)

**Comment by dmkret** [comment] 2018-10-25 15:48
@knz, thanks for reply!

I have the same issue with psql. Probably it is store processing problem.

**Reproduce**

Create table with data
```bash
root@81142ab6c98d:/cockroach# ./cockroach sql --insecure           
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL v2.0.6 (x86_64-unknown-linux-gnu, built 2018/10/01 13:59:40, go1.10) (same version as client)
# Cluster ID: b60deba7-37ed-43f6-986f-b3e20e62ef54
#
# Enter \? for a brief introduction.
#
warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
root@:26257/> create database test;
CREATE DATABASE

Time: 10.19165ms

root@:26257/> set database = test;
SET

Time: 295.408µs

root@:26257/test> create table test (test text[] NOT NULL);
CREATE TABLE

Time: 13.422543ms

root@:26257/test> insert into test values ('Т');
pq: value type string doesn't match type ARRAY of column "test"
root@:26257/test> insert into test values (ARRAY ['Т']);
INSERT 1

Time: 2.62925ms

root@:26257/test> select * from test;
+------------+
|    test    |
+------------+
| {"\u0422"} |
+------------+
(1 row)

Time: 3.549855ms
```

Select data using psql

```bash
root@81142ab6c98d:/cockroach# psql -h 127.0.0.1 -d test -p 26257
psql (9.4.19, server 9.5.0)
WARNING: psql major version 9.4, server major version 9.5.
         Some psql features might not work.
Type "help" for help.

test=> select * from test;
    test    
------------
 {"\u0422"}
(1 row)
```

Also I have the same issue with `golang: pgx` driver.

**Comment by knz** [comment] 2018-10-25 16:11
1) That's something different, your previous example was using an `array[]` expression only and not storing anything in the table.

Nevertheless, you can verify that the issue is only in the client/server protocol and not in the CockroachDB store: `select length(test[1]) from test` should still return 1.

2) The particular client/server protocol problem revealed in your test is a known limitation of CockroachDB 2.0 and has been fixed in the upcoming 2.1 release.

**Comment by dmkret** [comment] 2018-11-01 09:53
Since CockroachDB version: 2.1.0 it's ok with `lib/pq`.

**Comment by knz** [comment] 2018-11-01 10:02
Thank you for confirming.

@mjibson btw this is an example of what we were discussing next week, encoding behavior is different but is valid.

**Closed** 2021-06-05 12:17 UTC
Labels: A-sql-pgwire, C-investigation, O-community
