### ISSUE TITLE
Test failure in CI build 7530

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2539] opened 2015-09-17 14:08 UTC
The following test appears to have failed:

[#7530](https://circleci.com/gh/cockroachdb/cockroach/7530):

```
E0917 14:07:54.669881 929 storage/replica.go:954  error executing raft command: write too old: timestamp 0.100000001,3 <= 0.100000001,3
I0917 14:07:54.674016 929 kv/replica_slice.go:53  node 1 is not gossiped: gossip/gossip.go:194: unable to lookup descriptor for node 1: gossip/gossip.go:270: key "node:1" does not exist or has expired
I0917 14:07:54.674109 929 kv/dist_sender.go:299  unable to determine this node's attributes for replica selection; node is most likely bootstrapping
W0917 14:07:54.682638 929 kv/dist_sender.go:569  failed to invoke *proto.EndTransactionRequest ["",""): retry txn "storage/replica_command.go:1535 (*Replica).ChangeReplicas" id=2462528c key="" rw=false pri=97.02622359 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.100000001,4 orig=0.000000000,2 max=0.000000000,2
==================
WARNING: DATA RACE
Read by goroutine 80:
  fmt.(*fmt).fmt_sbx()
      /tmp/workdir/go/src/fmt/format.go:345 +0x43d
  fmt.(*fmt).fmt_bx()
      /tmp/workdir/go/src/fmt/format.go:365 +0xe1
  fmt.(*pp).fmtBytes()
      /tmp/workdir/go/src/fmt/print.go:575 +0x1e2
  fmt.(*pp).printArg()
      /tmp/workdir/go/src/fmt/print.go:800 +0x735
  fmt.(*pp).doPrintf()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  runtime.slicecopy()
      /tmp/workdir/go/src/runtime/slice.go:110 +0x0
  github.com/gogo/protobuf/proto.mergeAny()
      /go/src/github.com/gogo/protobuf/proto/clone.go:176 +0x12f9
  github.com/gogo/protobuf/proto.mergeStruct()
      /go/src/github.com/gogo/protobuf/proto/clone.go:84 +0x3a8
  github.com/gogo/protobuf/proto.Clone()
      /go/src/github.com/gogo/protobuf/proto/clone.go:52 +0x23c
  github.com/cockroachdb/cockroach/proto.(*Transaction).Update()
      /go/src/github.com/cockroachdb/cockroach/proto/data.go:477 +0xc2
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.String()
      /tmp/workdir/go/src/reflect/value.go:1632 +0x84
  encoding/json.stringEncoder()
      /tmp/workdir/go/src/encoding/json/encode.go:546 +0x2de
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Len()
      /tmp/workdir/go/src/reflect/value.go:1003 +0x178
  encoding/json.isEmptyValue()
      /tmp/workdir/go/src/encoding/json/encode.go:281 +0x1bc
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:572 +0x1bf
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.IsNil()
      /tmp/workdir/go/src/reflect/value.go:969 +0xb3
  encoding/json.encodeByteSlice()
      /tmp/workdir/go/src/encoding/json/encode.go:631 +0x5a
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Int()
      /tmp/workdir/go/src/reflect/value.go:880 +0x14f
  encoding/json.intEncoder()
      /tmp/workdir/go/src/encoding/json/encode.go:487 +0x83
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.IsNil()
      /tmp/workdir/go/src/reflect/value.go:963 +0x82
  encoding/json.isEmptyValue()
      /tmp/workdir/go/src/encoding/json/encode.go:291 +0x1f3
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:572 +0x1bf
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Int()
      /tmp/workdir/go/src/reflect/value.go:882 +0x17e
  encoding/json.intEncoder()
      /tmp/workdir/go/src/encoding/json/encode.go:487 +0x83
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Int()
      /tmp/workdir/go/src/reflect/value.go:880 +0x14f
  encoding/json.intEncoder()
      /tmp/workdir/go/src/encoding/json/encode.go:487 +0x83
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Len()
      /tmp/workdir/go/src/reflect/value.go:1003 +0x178
  encoding/json.isEmptyValue()
      /tmp/workdir/go/src/encoding/json/encode.go:281 +0x1bc
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:572 +0x1bf
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
      /go/src/github.com/cockroachdb/cockroach/storage/main_test.go:35 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/storage/_test/_testmain.go:444 +0x209
==================
==================
WARNING: DATA RACE
Read by goroutine 80:
  reflect.Value.Bool()
      /tmp/workdir/go/src/reflect/value.go:246 +0x45
  encoding/json.boolEncoder()
      /tmp/workdir/go/src/encoding/json/encode.go:476 +0x6b
  encoding/json.(*structEncoder).encode()
      /tmp/workdir/go/src/encoding/json/encode.go:582 +0x361
  encoding/json.(*structEncoder).(encoding/json.encode)-fm()
      /tmp/workdir/go/src/encoding/json/encode.go:596 +0x5e
  encoding/json.(*structEncoder).encode()
--
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /go/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:572 +0x2225
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous write by goroutine 94:
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).updateState()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:704 +0x186b
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).SendBatch()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:439 +0x1701
  github.com/cockroachdb/cockroach/client.SendCallConverted()
      /go/src/github.com/cockroachdb/cockroach/client/provisional.go:48 +0x3d8
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:295 +0xae
  github.com/cockroachdb/cockroach/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/client/txn.go:50 +0x14f
--
--- PASS: TestStoreRangeSystemSplits (1.15s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.68s)
PASS
Found 10 data race(s)
FAIL	github.com/cockroachdb/cockroach/storage	28.284s
=== RUN   TestBatchBasics
I0917 14:07:44.439204 955 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0917 14:07:44.442727 955 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I0917 14:07:44.448619 955 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-17 14:16
dupe of #2537.

**Closed by tamird** 2015-09-17 14:16 UTC
Labels: test-failure
