### ISSUE TITLE
pgbench: failing to generate data server-side

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#94238] opened 2022-12-23 14:50 UTC
**Is your feature request related to a problem? Please describe.**
[Pgbench](https://www.postgresql.org/docs/current/pgbench.html) is a common utility to stress test databases. It has ability to generate test data and up until recently it could only generate data client-side. In the recent releases, it introduced an option to generate data server-side, which it claims to be a faster solution.

> g or G (Generate data, client-side or server-side)
Generate data and load it into the standard tables, replacing any data already present.

> With G (server-side data generation), only small queries are sent from the pgbench client and then data is actually generated in the server. No significant bandwidth is required for this variant, but the server will do more work. Using G causes logging not to print any progress message while generating data.

Today, the option to generate data server-side does not work with CockroachDB.

**Describe the solution you'd like**

I would like to have an option of running data generation server-side in case the dataset is larger than my local client can handle.

**Describe alternatives you've considered**
Using client-side option with smaller scale.

**Additional context**

To repro:

Using pgbench 14 or higher, this output is from version 15.1 installed via homebrew

```bash
pgbench \
 --initialize \
 --init-steps=dtGpf \
 --host=${PGHOST} \
 --username=${PGUSER} \
 --port=${PGPORT} \
 --no-vacuum \
 --scale=${SCALE} \
 --foreign-keys \
${PGDATABASE}
```

```bash
dropping old tables...
creating tables...
NOTICE:  storage parameter "fillfactor" is ignored
NOTICE:  storage parameter "fillfactor" is ignored
NOTICE:  storage parameter "fillfactor" is ignored
generating data (server-side)...
pgbench: error: query failed: ERROR:  unsupported binary operator: <decimal> + <int> (desired <int>)
pgbench: detail: Query was: insert into pgbench_tellers(tid,bid,tbalance) select tid, (tid - 1) / 10 + 1, 0 from generate_series(1, 1000) as tid
```

I believe the error comes from [here](https://github.com/postgres/postgres/blob/master/src/bin/pgbench/pgbench.c#L4995)

In CockroachDB:

```sql
example=> insert into pgbench_tellers(tid,bid,tbalance) select tid, (tid - 1) / 10 + 1, 0 from generate_series(1, 1000) as tid returning tid;
ERROR:  unsupported binary operator: <decimal> + <int> (desired <int>)
```

but it should be:

```sql
example=> insert into pgbench_tellers(tid,bid,tbalance) select tid, ((tid - 1) / 10)::int + 1, 0 from generate_series(1, 1000) as tid;
INSERT 0 1000
```

Jira issue: CRDB-22764

**Comment by dbist** [comment] 2022-12-23 15:10
the following test case passes in Cockroach

```go
diff --git a/pkg/sql/sem/tree/type_check_test.go b/pkg/sql/sem/tree/type_check_test.go
index 78b765328e..1dc4b3efb3 100644
--- a/pkg/sql/sem/tree/type_check_test.go
+++ b/pkg/sql/sem/tree/type_check_test.go
@@ -254,6 +254,7 @@ func TestTypeCheckError(t *testing.T) {
        }{
                {`'1' + '2'`, `ambiguous binary operator:`},
                {`'a' + 0`, `unsupported binary operator:`},
+               {`1.0 + 0`, `unsupported binary operator:`},
                {`1.1 # 3.1`, `unsupported binary operator:`},
                {`~0.1`, `unsupported unary operator:`},
                {`'a' > 2`, `unsupported comparison operator:`},
```

```bash
artem@crlMBP-HQ0J2W33NQMjUx cockroach % ./dev test pkg/sql/rowenc --filter type_check_test.go
$ bazel test pkg/sql/rowenc:all --test_env=GOTRACEBACK=all --test_filter=type_check_test.go --test_sharding_strategy=disabled --test_output errors
INFO: Invocation ID: 15930dc5-0d25-47a1-b1a4-e98404743f9f
INFO: Analyzed 3 targets (0 packages loaded, 0 targets configured).
INFO: Found 2 targets and 1 test target...
INFO: Elapsed time: 0.524s, Critical Path: 0.30s
INFO: 1 process: 1 internal.
//pkg/sql/rowenc:rowenc_test                                    (cached) PASSED in 1.2s

Executed 0 out of 1 test: 1 test passes.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
INFO: Build Event Protocol files produced successfully.
INFO: Build completed successfully, 1 total action
```

**Comment by dbist** [comment] 2022-12-23 15:23
in postgres

```sql
postgres=# insert into pgbench_tellers(tid,bid,tbalance) select tid, (tid - 1) / 10 + 1, 0 from generate_series(1, 1000) as tid returning tid;

  999
 1000
(1000 rows)

INSERT 0 1000
```

```sql
postgres=# insert into pgbench_tellers(tid,bid,tbalance) select tid, ((tid - 1) / 10)::int + 1, 0 from generate_series(1, 1000) as tid returning tid;

 998
  999
 1000
(1000 rows)

INSERT 0 1000
```

**Comment by mgartner** [comment] 2022-12-27 19:34
What do you mean when you say "it should be" using the cast? 

The root cause is that CRDB's integer division operator returns a DECIMAL, not an INT. See #41448.

**Comment by mgartner** [comment] 2022-12-27 19:35
I'm going to close this as a duplicate of #41448.

**Closed by mgartner** 2022-12-27 19:35 UTC
Labels: C-enhancement, T-sql-queries
