### ISSUE TITLE
sql: incorrect span generation for key lookups of system tables

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#58614] opened 2021-01-07 16:22 UTC
**edit by @jordanlewis: see https://github.com/cockroachdb/cockroach/issues/58614#issuecomment-756541303 for the root cause problem description and repro**

**Describe the problem**

I have a query where I add a predicate to a select and the result set seems to be inverted. My intuition is that adding a predicate via `AND` can only restrict the result set.

**To Reproduce**

```sql
CREATE DATABASE foo;
CREATE TABLE foo.bar();
DROP DATABASE foo CASCADE;
  WITH descs AS (
                SELECT id,
                       crdb_internal.pb_to_json(
                        'cockroach.sql.sqlbase.Descriptor',
                        descriptor
                       ) AS descriptor
                  FROM system.descriptor
             )
SELECT id
  FROM descs
 WHERE (descriptor->'table') IS NOT NULL
   AND (
        NOT EXISTS(
                SELECT d.id
                  FROM system.descriptor AS d
                 WHERE d.id = (descs.descriptor->'table'->>'parentId')::INT8
            )
       );
 ```
 
 The below should result in:
 
 ```
   id
------
  60
(1 row)
```

If I augment the above select with `AND (descriptor->'table'->>'state') = 'PUBLIC'` then I get:

```
demo@127.0.0.1:33623/movr>   WITH descs AS (
                SELECT id,
                       crdb_internal.pb_to_json(
                        'cockroach.sql.sqlbase.Descriptor',
                        descriptor
                       ) AS descriptor
                  FROM system.descriptor
             )
SELECT id
  FROM descs
 WHERE (descriptor->'table') IS NOT NULL
   AND (
        NOT EXISTS(
                SELECT d.id
                  FROM system.descriptor AS d
                 WHERE d.id = (descs.descriptor->'table'->>'parentId')::INT8
            )
       )
   AND (descriptor->'table'->>'state') = 'PUBLIC';
  id
------
   2
   3
   4
   5
   6
   8
  11
  12
  13
  14
  15
  19
  20
  21
  23
  24
  25
  26
  27
  28
  30
  31
  32
  33
  34
  35
  36
  37
  39
  53
  54
  55
  56
  57
  58
(35 rows)

Time: 30ms total (execution 30ms / network 0ms)
```

**Expected behavior**
I expect the final select to return 0 rows.

**Environment:**

This reproduces at v20.2.3 and the nightly 27af9b003943ee1a8b1d27b8db527a54ec6557de.

**Comment by jordanlewis** [comment] 2021-01-07 16:29
The only difference in the plan is that the join chosen is a lookup join in the second case, vs a hash join in the first case:

```
root@127.0.0.1:55400/movr> explain wITH descs AS (
                SELECT id,
                       crdb_internal.pb_to_json(
                        'cockroach.sql.sqlbase.Descriptor',
                        descriptor
                       ) AS descriptor
                  FROM system.descriptor
             )
SELECT id
  FROM descs
 WHERE (descriptor->'table') IS NOT NULL
   AND (
        NOT EXISTS(
                SELECT d.id
                  FROM system.descriptor AS d
                 WHERE d.id = (descs.descriptor->'table'->>'parentId')::INT8
            )
       );
            tree           |       field        |            description
---------------------------+--------------------+------------------------------------
                           | distribution       | full
                           | vectorized         | false
  hash join (anti)         |                    |
   │                       | equality           | (column12) = (id)
   │                       | right cols are key |
   ├── render              |                    |
   │    └── filter         |                    |
   │         │             | filter             | (descriptor->'table') IS NOT NULL
   │         └── render    |                    |
   │              └── scan |                    |
   │                       | missing stats      |
   │                       | table              | descriptor@primary
   │                       | spans              | FULL SCAN
   └── scan                |                    |
                           | missing stats      |
                           | table              | descriptor@primary
                           | spans              | FULL SCAN
(17 rows)

Time: 1ms total (execution 1ms / network 0ms)

root@127.0.0.1:55400/movr> explain WITH descs AS (
                SELECT id,
                       crdb_internal.pb_to_json(
                        'cockroach.sql.sqlbase.Descriptor',
                        descriptor
                       ) AS descriptor
                  FROM system.descriptor
             )
SELECT id
  FROM descs
 WHERE (descriptor->'table') IS NOT NULL
   AND (
        NOT EXISTS(
                SELECT d.id
                  FROM system.descriptor AS d
                 WHERE d.id = (descs.descriptor->'table'->>'parentId')::INT8
            )
       )
   AND (descriptor->'table'->>'state') = 'PUBLIC';
            tree           |         field         |                                      description
---------------------------+-----------------------+-----------------------------------------------------------------------------------------
                           | distribution          | full
                           | vectorized            | false
  lookup join (anti)       |                       |
   │                       | table                 | descriptor@primary
   │                       | equality              | (column12) = (id)
   │                       | equality cols are key |
   └── render              |                       |
        └── filter         |                       |
             │             | filter                | ((descriptor->'table') IS NOT NULL) AND (((descriptor->'table')->>'state') = 'PUBLIC')
             └── render    |                       |
                  └── scan |                       |
                           | missing stats         |
                           | table                 | descriptor@primary
                           | spans                 | FULL SCAN
(14 rows)
```

**Comment by ajwerner** [comment] 2021-01-07 16:33
Here's an even more stark version of the repro:

```sql
CREATE DATABASE foo;
CREATE TABLE foo.bar();
DROP DATABASE foo CASCADE;
CREATE VIEW v AS  (
                      WITH descs AS (
                                    SELECT id,
                                           crdb_internal.pb_to_json(
                                            'cockroach.sql.sqlbase.Descriptor',
                                            descriptor
                                           ) AS descriptor
                                      FROM system.descriptor
                                 )
                    SELECT id, descriptor
                      FROM descs
                     WHERE (descriptor->'table') IS NOT NULL
                       AND NOT EXISTS(
                                SELECT d.id
                                  FROM system.descriptor AS d
                                 WHERE d.id
                                       = (
                                            descs.descriptor->'table'->>'parentId'
                                        )::INT8
                               )
                  );
```

Then compare the outputs of:

```sql
SELECT id FROM v;
```
vs
```sql
SELECT id FROM v WHERE (descriptor->'table'->>'state') = 'PUBLIC';
```

**Comment by ajwerner** [comment] 2021-01-07 16:34
Okay, I guess then this is an execution bug in the lookup anti join.

**Comment by ajwerner** [comment] 2021-01-07 16:40
The answer is still wrong with `SET vectorize = off`.

**Comment by ajwerner** [comment] 2021-01-07 16:45
Okay, I can confirm that if the query is rewritten for force the `INNER HASH JOIN` instead of the lookup join, everything works as expected.

```sql
CREATE VIEW v AS  (
                      WITH descs AS (
                                    SELECT id,
                                           crdb_internal.pb_to_json(
                                            'cockroach.sql.sqlbase.Descriptor',
                                            descriptor
                                           ) AS descriptor
                                      FROM system.descriptor
                                 )
                    SELECT id, descriptor
                      FROM descs
                     WHERE (descriptor->'table') IS NOT NULL
                       AND NOT EXISTS(
                                SELECT d.id
                                  FROM system.descriptor AS d
                                       INNER HASH JOIN descs ON (
                                                                            d.id
                                                                            = (
                                                                                    descs.descriptor->'table'->>'parentId'
                                                                                )::INT8
                                                                        )
                               )
                  );
                  ```

**Comment by ajwerner** [comment] 2021-01-07 17:17
Actually this later view seems wrong also somehow for reasons I do not understand.

**Comment by jordanlewis** [comment] 2021-01-07 17:21
Here's an EXPLAIN ANALYZE of the anti lookup join that appears to be doing the wrong thing: https://cockroachdb.github.io/distsqlplan/decode.html#eJysVNtO80YQvu9TjOYmjrSE2CmnlZDCIRRD6qDEQKU2Qo49BYOza3bXEhHKY_UF-mSVD4kTGiLQ_1_4Yr795puz31G_Jsjx3vUvISIdajgZgTXq9XtnPsQRg1BFk4dYGFIiSFrp5MHIh2cthdUIZfiiZBA-tfRrkn-TQFPrnHSo4tRI1WCFYmk0c93ahIvh4HfQM21o2lplLSOXjDKl-8vesAeWZdXMnb-ydrtDDRNMEmo0wR2BN_DBu-33m3DinYOVm70_3JFf1xO1Frr_i1ykVwUqaMdQhtOtT4NWZgWmgSJh3KjR5Nz1_MNms0pkS9rrCtoEJq_lGBo3t6d996zRRIZCRuQFU9LI_0QbxwxTJUPSWqocei8IbvSGvM0wFmlmcnjMMJSKkL-jiU1CyNHPYw4piEjttpFhRCaIk0K2TrCbqngaqBkyHKWB0Bx2kOGQRESKQ9f-oYXgnI_8oev9xrpOXlpCfxswWZqQ5tBxFog2QZKAiafEwdmfamSo4senmuocLaEN3Ou7hb23sEMpDAkTS1E9tf_9Z0EtNEFREFU5XN_BZGaWmH0A1_EpMpwEJnwiDTIzaWY47CPDynsBOUc4njMszWoM2gSPhNyes6-P6iJODClSu_b6nEqcg2V1nfVVWrZ20ylso29awRWxehdrcGUhvq68PI-aUN4Jg25eJb1RmK1MqOM45Yw-tn3vW213vtP2KxmL6kCc9cb7s5Q49HsXPpx4vgtXA9crGBvupi_lS5bCs4wFSMHL8gZ5nt1ctUhgfZVLaOsqHx4sN_ary9ze0NVfj-yf0dXOd7o6JJ1KoWmto58pt-djhhQ9Uvlv0zJTId0oGRZhSnNQ-BVARNqUr3ZpuKJ8yhNcdba3OjvbnZ2tzp0PzuP5L_8FAAD__2ZXXHo=

Note that it has 29 input tuples, reads 0 things from KV, but still outputs 29 tuples... seems very wrong.

**Comment by jordanlewis** [comment] 2021-01-07 17:23
Er, wait, I have it backward. Isn't that exactly what it *should* be doing? No matches = all output.

**Comment by jordanlewis** [comment] 2021-01-07 17:25
I think this *is* an optimizer issue, actually. I think the issue is that an anti lookup join is weird - it inverts a match. So you can't re-order filters across it, right? If you put the filter before it, it will add *more* things. If you put the filter after, it will subtract things.

**Comment by jordanlewis** [comment] 2021-01-08 04:37
There is a bug in span generation for certain special system tables, like `system.namespace` and `system.descriptor`. The reason for this bug is that these special system tables have descriptors that don't match their encoding, because they are written to with direct kv operations and do not use SQL.

We've learned this lesson before (see the PR text of #55699); this is yet another manifestation.

Specifically, the problem is that the descriptors for `system.descriptor` and `system.namespace` include a column family specification that separates the key columns from the value column. But, the code that writes to namespace and descriptor tables only writes a single key, to the hardcoded column family of the value of the table. This is in fact an invalid encoded row in our column family encoding scheme: rows must contain a sentinel key for their key columns, even if they're all alone in their own family.

Because of this, the code that generates "tight" spans for queries that only need elements from the key columns of one of these special table descriptors is invoked. It produces a span that expects to match the sentinel key for the row. But, the sentinel key will never exist, because the code that writes to these tables never creates one.

The simplest repro of this phenomenon is below:

```
demo@127.0.0.1:26257/defaultdb> select id from system.descriptor where id=5;
  id
------
(0 rows)

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> select id, length(descriptor) from system.descriptor where id=5;
  id | length
-----+---------
   5 |    308
(1 row)
```

As you can see, the first query returns 0 rows but should return 1. Using `EXPLAIN(DISTSQL)` on these queries shows the "true" spans generated (which include the expectation that the result will be stored in the {0-1} column family for the first query, where no key will live.

The fix for this is probably to disable the column family tight span generation code for system tables, because it will not work properly (and is unnecessary, since these system tables always just have a single key despite having multiple families).

**Closed** 2021-01-20 19:15 UTC
Labels: S-0-visible-logical-error
