### ISSUE TITLE
Error creating a partial index that's dependent on the existence of a JSON field

### ISSUE THREAD

**Issue by codingconcepts** [cockroachdb/cockroach#108432] opened 2023-08-09 12:30 UTC
**Describe the problem**

When I attempt to create a partial inverted index on a JSON column *with data*, I receive an error, rather than either a successful index creation or an unimplemented warning. If I create the same inverted index on a JSON column that does *not* have data, I don't receive an error.

**To Reproduce**

``` sh
cockroach demo --insecure --no-example-database
```

``` sql
CREATE TABLE person (
  "id" UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  "contact" JSON NOT NULL
);

INSERT INTO person ("id", "contact") VALUES
  ('a54bf5ea-6c40-4581-9a16-227ffe36c6b3', '{"country": "UK"}'),
  ('baa3df1e-26ab-4fa0-8fda-930e0115532b', '{"country": "UK"}'),
  ('c1feb38c-5e2d-4608-b21e-c2cb33916d5d', '{"country": "US"}'),
  ('d186fbc6-4a2e-4faf-8e07-46b96774bf26', '{"country": "US"}');

UPDATE person
SET "contact" = jsonb_set("contact", '{state}', '"CA"', true)
WHERE "contact" @> '{"country": "US"}';

CREATE INVERTED INDEX ON person("contact")
WHERE "contact" ? 'state';
```

```
*
* ERROR: Queued as error 8fce4a2e8ff84f858cf0481f5ad15ed1
*
ERROR: internal error: executing declarative schema change PostCommitPhase stage 7 of 7 with 1 ValidationType op (rollback=false) for CREATE INDEX: validation of index person_contact_idx failed: expected 0 rows, found 4
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/backfill.go:1745: func2()
github.com/cockroachdb/cockroach/pkg/util/ctxgroup/ctxgroup.go:168: func1()
golang.org/x/sync/errgroup/external/org_golang_x_sync/errgroup/errgroup.go:75: func1()
src/runtime/asm_arm64.s:1172: goexit()

HINT: You have encountered an unexpected error.
```

**Environment:**
Build Tag:        v23.1.5
Build Time:       2023/07/01 02:00:30
Distribution:     CCL
Platform:         darwin arm64 (aarch64-apple-darwin21.2)
Go Version:       go1.19.10
C Compiler:       Clang 10.0.0 
Build Commit ID:  72556c6b5dc0d4ed1a0202bc4176586956d54739
Build Type:       release
Enabled Assertions: false

**Additional context**
No client impact, just working locally.

Jira issue: CRDB-30469

**Comment by rafiss** [comment] 2024-03-05 16:46
This does not reproduce in v23.1.16 nor v23.2.1. The bug was present in v23.1.9 though. Closing since this was fixed.

**Closed by rafiss** 2024-03-05 16:46 UTC
Labels: C-bug, T-sql-foundations
