### ISSUE TITLE
TestLeaderAfterSplit panic in RocksDB

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#9968] opened 2016-10-13 20:55 UTC
https://teamcity.cockroachdb.com/viewLog.html?buildId=31562&buildTypeId=Cockroach_UnitTests

```
SIGABRT: abort
PC=0x7fdd95a4f067 m=5
signal arrived during cgo execution

goroutine 25742 [syscall, locked to thread]:
runtime.cgocall(0x17e4ae0, 0xc422099df0, 0x0)
    /usr/local/go/src/runtime/cgocall.go:131 +0xb9 fp=0xc422099dc0 sp=0xc422099d88
github.com/cockroachdb/cockroach/pkg/storage/engine._Cfunc_DBClose(0x7fdd8d6d8b60)
    ??:0 +0x63 fp=0xc422099df0 sp=0xc422099dc0
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).Close(0xc4203f4480)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:402 +0x1bf fp=0xc422099e78 sp=0xc422099df0
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc42173a090)
    /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:376 +0x435 fp=0xc422099f30 sp=0xc422099e78
github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Stop.func1(0xc421990000, 0xc421db87e0)
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:342 +0x2cb fp=0xc422099fa0 sp=0xc422099f30
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc422099fa8 sp=0xc422099fa0
created by github.com/cockroachdb/cockroach/pkg/storage_test.(*multiTestContext).Stop
    /go/src/github.com/cockroachdb/cockroach/pkg/storage/client_test.go:345 +0x95
```

**Comment by petermattis** [comment] 2016-10-13 21:27
This is happening during shutdown, which is less worrisome than if it happened during execution. We're probably double-closing the DB somehow. I've been unable to reproduce after 5m of local stress.

Cc @andreimatei who is changing how engine shutdown works.

**Comment by andreimatei** [comment] 2016-10-13 21:53
Hmmm I think I'm just changing the form of how they get closed, not the function. Having said that, if someone's gonna run more tests, it's probably worth running with #9845 too see if it happens to help.

Other than that... any clue of what SIGABRT would mean in this context? It's not a segmentation fault, is it? Maybe it's a weird timeout?

**Comment by tamird** [comment] 2016-10-13 22:27
It's an assertion on the c++ side. @RaduBerinde didn't post the most interesting part of the test output:
```
I161013 20:46:40.653466 25742 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
I161013 20:46:40.653602 25742 storage/engine/rocksdb.go:396  closing in-memory rocksdb instance
storage.test: /go/src/github.com/cockroachdb/c-rocksdb/internal_db_column_family.cc:444: rocksdb::ColumnFamilyData::~ColumnFamilyData(): Assertion `is_last_reference' failed.
```

**Comment by petermattis** [comment] 2016-10-14 01:17
We saw this RocksDB assertion before in https://github.com/cockroachdb/cockroach/issues/352. In that case it was a failure to close an iterator before closing the DB.

**Comment by petermattis** [comment] 2016-10-17 17:15
So far I've been unable to reproduce this using: 

```
make stressrace PKG=./storage TESTS=TestLeaderAfterSplit STRESSFLAGS="-stderr -maxfails 1 -p 32"
````

Update: as soon as I started writing this comment a failure occurred.

**Comment by petermattis** [comment] 2016-10-17 18:06
Looks like two separate problems. Both of the same effect, we create a RocksDB iterator that isn't closed by the time the engine is closed. The first reason this can occur is that `raftScheduler` does not wait for the worker goroutines to finish when `stopper.ShouldStop()` returns. That's easy to fix.

The second reason this can occur is that the `snapshot()` creates an iterator and stores it in `Replica.mu.outSnap` but we never close that iterator if the store is stopped before the snapshot is sent. I need to explore this further, but we might need something at the store level which iterates over the replicas and calls `Replica.CloseOutSnap` when the store is stopped.

**Closed** 2016-10-17 20:04 UTC
Labels: test-failure
