### ISSUE TITLE
sql: dropping a very small table is very slow

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#38111] opened 2019-06-08 02:30 UTC
Running on master at 33f9a3c2c5a0d2b756a8827daa74285b1aece401, a single node on my laptop.

I created a small table, inserted several rows into it, and attempted to drop it. I expected it to be an instant operation, but it was taking longer than a few seconds, so I ctrl-c'ed the cli. Now, I can neither drop the table or create a new one with the same name. Here is the log:
```
root@:26257/defaultdb> CREATE TABLE nondroppable (a INT PRIMARY KEY);
CREATE TABLE

Time: 4.641ms

root@:26257/defaultdb> INSERT INTO nondroppable VALUES (1), (2), (3);
INSERT 3

Time: 6.225ms

root@:26257/defaultdb> DROP TABLE nondroppable;
^C
(ctrl-c'ed here after a few seconds)


root@:26257/defaultdb> DROP TABLE nondroppable;
pq: relation "nondroppable" does not exist
root@:26257/defaultdb> CREATE TABLE nondroppable (a INT PRIMARY KEY);
pq: relation "nondroppable" already exists
```
Note that dropping an empty table works fine:
```
root@:26257/defaultdb> CREATE TABLE nondroppable (a INT PRIMARY KEY);
CREATE TABLE

Time: 5.463ms

root@:26257/defaultdb> DROP TABLE nondroppable;
DROP TABLE

Time: 30.659ms
```

The jobs page shows the "dropping" job in "Draining names" stage.
<img width="1298" alt="Screen Shot 2019-06-07 at 10 22 10 PM" src="https://user-images.githubusercontent.com/5135385/59140991-56156d80-8973-11e9-8845-6aca72e1d5e8.png">

The issue persists after the node restart.

Assigning @dt for triage (since I guess it is a schema change operation?).

**Comment by yuzefovich** [comment] 2019-06-08 02:40
Update: the job completed in `Duration: 00:08:36`, and now I can create a table with the same name again, but it is an awfully slow completion (I restarted the node within that time period).

I reran the commands again without ctrl-c'ing:
```
root@:26257/defaultdb> CREATE TABLE nondroppable (a INT PRIMARY KEY);
CREATE TABLE

Time: 5.995ms

root@:26257/defaultdb> INSERT INTO nondroppable VALUES (1), (2), (3);
INSERT 3

Time: 3.722ms

root@:26257/defaultdb> DROP TABLE nondroppable;
DROP TABLE

Time: 4m56.079853s
```

**Comment by adityamaru27** [comment] 2019-06-27 21:54
I did some debugging on this today and observed the following:

• Initially, I could reproduce the error consistently when run locally, but not on roachprod. I tracked down the bottleneck to `waitToUpdateLeases` called by the SchemaChanger while attempting to drain the table names in `sc.drainNames`. The SchemaChanger would wait for a single unexpired lease to elapse before updating the table desc, thus taking 4+mins to execute `DROP`.

• From there, I tried to narrow down to where this regression was introduced, but somewhere along the line I cleared `cockroach-data` before running the above set of queries, and ever since I cannot reproduce this behavior.

**Comment by yuzefovich** [comment] 2019-09-03 16:27
I've run into this problem again. Here are some logs (maybe they'll be useful):
```
I190903 16:25:14.893377 6828 sql/event_log.go:130  [n1,client=[::1]:49994,user=root] Event: "drop_table", target: 647, info: {TableName:defaultdb.public.temo Statement:DROP TABLE temo User:root CascadeDroppedViews:[]}
I190903 16:25:14.896593 6828 sql/lease.go:329  [n1,client=[::1]:49994,user=root,scExec] waiting for 1 leases to expire: desc=[{temo 647 2}]
W190903 16:25:14.897149 30803 sql/lease.go:281  unexpected results while deleting lease &{id:647 version:2 expiration:{Time:{wall:265823000 ext:63703124921 loc:<nil>}}}: expected 1 result, found 0
I190903 16:25:17.172302 70 server/status/runtime.go:498  [n1] runtime stats: 311 MiB RSS, 205 goroutines, 138 MiB/103 MiB/270 MiB GO alloc/idle/total, 98 MiB/146 MiB CGO alloc/total, 629.5 CGO/sec, 9.4/2.0 %(u/s)time, 0.0 %gc (0x), 153 KiB/26 KiB (r/w)net
W190903 16:25:18.422621 36454 sql/lease.go:281  unexpected results while deleting lease &{id:201 version:1 expiration:{Time:{wall:807989000 ext:63703124910 loc:<nil>}}}: expected 1 result, found 0
```

**Comment by lucy-zhang** [comment] 2020-04-30 21:26
The problem is that the table is stuck in the draining names state after the initial transaction to drop the table. I'm closing this because the async schema change to move the table out of the draining names state works differently now, and we actually have more of a guarantee now that the job registry will  run the job to do it. If this specific problem re-emerges then we can reopen it.

**Closed by lucy-zhang** 2020-04-30 21:26 UTC
Labels: C-enhancement
