### ISSUE TITLE
sql: cannot parse numbers with leading zeros or whitespace

### ISSUE THREAD

**Issue by Lukens4242** [cockroachdb/cockroach#70446] opened 2021-09-20 21:31 UTC
Edit: This is a broader issue that is common to all number parsing in Cockroach SQL and is not specific to IMPORT.
```
demo@127.0.0.1:26257/movr> select '0008'::int;
ERROR: could not parse "0008" as type int: strconv.ParseInt: parsing "0008": invalid syntax
SQLSTATE: 22P02
demo@127.0.0.1:26257/movr> select ' 0008'::int;
ERROR: could not parse " 0008" as type int: strconv.ParseInt: parsing " 0008": invalid syntax
SQLSTATE: 22P02
```

In pg, these both work:
*Query*

    select '0008'::int, ' 0008'::int;

| int4 | int4 |
| ---- | ---- |
| 8    | 8    |

---

[View on DB Fiddle](https://www.db-fiddle.com/f/4jyoMCicNSZpjMt4jFYoz5/2448)

Orignial IMPORT issue:

**Describe the problem**

A customer is trying to import a set of data in csv files.  They are coming from an older system that outputs fixed width comma separated values.  The first element of the data is an integer which can either have leading spaces or leading zeroes.  When importing this type of file, the following errors are generated:
```
root@localhost:26257/defaultdb> import into dml1 (id, string1, string2) csv data('gs://lukens-tests/dml1.csv') with nullif = '';
ERROR: gs://lukens-tests/dml1.csv: error parsing row 1: parse "id" as INT8: could not parse "     1" as type int: strconv.ParseInt: parsing "     1": invalid syntax (row: "     1,STRING1                     ,STRING1")
root@localhost:26257/defaultdb> import into dml1 (id, string1, string2) csv data('gs://lukens-tests/dml1.csv') with nullif = '';
ERROR: gs://lukens-tests/dml1.csv: error parsing row 8: parse "id" as INT8: could not parse "0008" as type int: strconv.ParseInt: parsing "0008": invalid syntax (row: "0008,STRING8                     ,STRING8")
```

**To Reproduce**

What did you do? Describe in your own words.

I created a simple table and attempted to import a csv file with column 1 being an integer with either leading zeroes or leading spaces.  The error above is produced when trying to do this.

If possible, provide steps to reproduce the behavior:

```
create table dml1 ( id int not null, string1 string not null, string2 string not null, ts1 timestamp not null defult current_timestamp(), ts2 timestamp not null default current_timestamp());
root@localhost:26257/defaultdb> import into dml1 (id, string1, string2) csv data('gs://lukens-tests/dml1.csv') with nullif = '';
ERROR: gs://lukens-tests/dml1.csv: error parsing row 1: parse "id" as INT8: could not parse "     1" as type int: strconv.ParseInt: parsing "     1": invalid syntax (row: "     1,STRING1                     ,STRING1")
root@localhost:26257/defaultdb> import into dml1 (id, string1, string2) csv data('gs://lukens-tests/dml1.csv') with nullif = '';
ERROR: gs://lukens-tests/dml1.csv: error parsing row 8: parse "id" as INT8: could not parse "0008" as type int: strconv.ParseInt: parsing "0008": invalid syntax (row: "0008,STRING8                     ,STRING8")
```

Here are the two files:
```
    1,STRING1                     ,STRING1
    2,STRING2                     ,STRING2
    3,STRING3                     ,STRING3
    4,STRING4                     ,STRING4
    5,STRING5                     ,STRING5
    6,STRING6                     ,STRING6
    7,STRING7                     ,STRING7
    8,STRING8                     ,STRING8
    9,STRING9                     ,STRING9
```
```
0001,STRING1                     ,STRING1
0002,STRING2                     ,STRING2
0003,STRING3                     ,STRING3
0004,STRING4                     ,STRING4
0005,STRING5                     ,STRING5
0006,STRING6                     ,STRING6
0007,STRING7                     ,STRING7
0008,STRING8                     ,STRING8
0009,STRING9                     ,STRING9
```

**Expected behavior**
With the first element having leading zeroes, I would expect that "0008" would be properly parsed as an integer.
With the first element having leading spaces, I would also expect that "    8" would be properly parsed as an integer.
When importing a csv file where each element is fixed width, the whitespace should be trimmed around all values.

**Environment:**
 - CockroachDB version 20.2 and 21.1

**Comment by shermanCRL** [comment] 2021-09-20 23:15
Thanks! We’ve labelled as SQL Experience -- this will put it in their triage queue. (For the future, best not to assign individuals, rather should assign a team label.)

**Comment by rafiss** [comment] 2021-09-21 03:34
This looks like a duplicate of https://github.com/cockroachdb/cockroach/issues/68986 -- I'll close this issue since that other issue already has a pointer to the code that will need fixing.

**Closed by rafiss** 2021-09-21 03:34 UTC
Labels: C-bug, O-support, A-sql-builtins, T-sql-experience
