### ISSUE TITLE
log: introduce redactability inside SQL statement representation included in logging events

### ISSUE THREAD

**Issue by thtruo** [cockroachdb/cockroach#65468] opened 2021-05-19 17:09 UTC
Mentioned by @knz 

**Is your feature request related to a problem? Please describe.**
Until we can distinguish between operational and application data, any object name (e.g. columns, tables) included in SQL statements will be conservatively considered application data. 

That means the entire statement, including SQL keywords, is considered "sensitive" or "unsafe" information.

**Describe the solution you'd like**
We need some form of partial redaction, similar to what is used in stmtstats.

**Additional context**
This is part of the logging telemetry infrastructure effort.

**Comment by thtruo** [comment] 2021-05-19 17:10
cc @kevin-v-ngo @jordanlewis for awareness

**Comment by knz** [comment] 2021-05-20 11:34
This issue is a duplicate of #65401.

**Closed by knz** 2021-05-20 11:34 UTC
Labels: A-logging, A-sql-observability, C-enhancement
