### ISSUE TITLE
allow SELECT FROM without fields

### ISSUE THREAD

**Issue by soupi** [cockroachdb/cockroach#116659] opened 2023-12-18 13:10 UTC
**Describe the problem**

I'd like to run queries that return no fields. An example of that is the following:

```sql
create table t(x int);

insert into t values (1),(2),(3);

select count(*) from (select from t);
```

On postgres, the above return:

```
 count 
-------
     3
(1 row)
```

On cockroach, the above return:

```
ERROR:  at or near "from": syntax error
DETAIL:  source SQL:
select count(*) from (select from t)
                             ^
HINT:  try \h SELECT
```

**Additional context**
What was the impact?

This feature is used in [Hasura's postgres connector](https://github.com/hasura/ndc-postgres) to support graphql queries such as:

```graphql
query {
  artists(where: ..., limit: 10) {
    __typename
  }
}
```

where we expect empty rows that inform how many results are expected to be returned.

Jira issue: CRDB-34708

**Comment by yuzefovich** [comment] 2023-12-20 00:21
@soupi thanks for the report! I have a WIP to address this, but currently it results in removing some of the contextual error help, so we might not be able to merge this as is. Please feel free to follow #116835 if interested.

**Comment by michae2** [comment] 2023-12-20 01:08
I think this is a dupe of https://github.com/cockroachdb/cockroach/issues/83255 (but maybe we can dupe that to this issue).

**Comment by yuzefovich** [comment] 2023-12-20 01:09
Indeed, let's close this as a dup of #83255. @soupi please follow the progress there.

**Closed by yuzefovich** 2023-12-20 01:09 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries, A-tools-hasura
