### ISSUE TITLE
ui: Overload Dashboard Admission graphs are missing node numbers

### ISSUE THREAD

**Issue by florence-crl** [cockroachdb/cockroach#73317] opened 2021-11-30 20:24 UTC
**Describe the problem**

In the DB Console, Metrics->Overload Dashboard, node numbers are missing from the following graphs:

* KV Admission Slots
* KV Admission IO Tokens Exhausted Duration Per Second
* Admission Work Rate
* Admission Delay Rate
* Admission Delay: 75th percentile

**To Reproduce**

* Create a 21.2.1 3-node cluster
* In the DB Console, go to Metrics->Overload Dashboard
* Hover over the KV Admission Slots graph
* In the pop-up legend, notice that there are no node numbers after "Total Slots" or "Used Slots"
* Compare to the LSM L0 Health graph which has node numbers after "L0 Sublevels" and "L0 Files"

**Expected behavior**

In the pop-up legends, there should be node numbers.

**Additional data / screenshots**

<img width="1195" alt="Screen Shot 2021-11-30 at 3 10 52 PM" src="https://user-images.githubusercontent.com/58752716/144122200-a2f3f783-3b0f-4968-93a9-556506c1ffdc.png">

<img width="1161" alt="Screen Shot 2021-11-30 at 3 14 42 PM" src="https://user-images.githubusercontent.com/58752716/144122219-b0386a0a-1eef-48fe-bc7c-37f6b8b30000.png">

**Environment:**
 - CockroachDB version 21.2.1
 - Server OS: Mac
 - Client app DB Console

**Comment by zachlite** [comment] 2022-01-05 19:52
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/70764
Fixed in https://github.com/cockroachdb/cockroach/pull/71415

**Closed** 2022-01-05 19:52 UTC
Labels: C-bug, T-kv-observability
