### ISSUE TITLE
Unexpected behaviors on a generated BOOL column

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#97437] opened 2023-02-22 03:17 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
I start CockroachDB v22.2.0 with the command `./cockroach start-single-node --certs-dir=certs --host=localhost --http-host=localhost`.

I type the following statements, which build a table t0 with a generated `BOOL` column c0 and a TIMESTAMP column c1. The INSERT statement only fills a value to c1, and c0 is generated column, which is expected always to be NOT NULL. However, when I fetch its value, null is returned.
```
CREATE TABLE t0 (c0 BOOL AS (NOT NULL) STORED, c1 TIMESTAMP);
INSERT INTO t0 (c1) VALUES(TIMESTAMP '1969-12-28T05:49:09');

SELECT c0 IS NOT NULL FROM t0; -- false, unexpected
SELECT t0.c1 FROM t0 WHERE TRUE ORDER BY ((1 IS NOT NULL)) NOT BETWEEN ((((86238108)-(-9223372036854775808)) < 1)) AND (t0.c0); -- no error
EXPLAIN SELECT t0.c1 FROM t0 WHERE TRUE ORDER BY ((1 IS NOT NULL)) NOT BETWEEN ((((86238108)-(-9223372036854775808)) < 1)) AND (t0.c0);
         info
-----------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: t0@t0_pkey
    spans: FULL SCAN
```

If I remove the generated property for column c0. The query `SELECT t0.c1 FROM t0 WHERE TRUE ORDER BY ((1 IS NOT NULL)) NOT BETWEEN ((((86238108)-(-9223372036854775808)) < 1)) AND (t0.c0); ` returns an error.
```
CREATE TABLE t0 (c0 BOOL, c1 TIMESTAMP);
INSERT INTO t0 (c1) VALUES(TIMESTAMP '1969-12-28T05:49:09');

SELECT c0 IS NOT NULL FROM t0; -- false, expcted
SELECT t0.c1 FROM t0 WHERE TRUE ORDER BY ((1 IS NOT NULL)) NOT BETWEEN ((((86238108)-(-9223372036854775808)) < 1)) AND (t0.c0); -- [22003] ERROR: integer out of range
EXPLAIN SELECT t0.c1 FROM t0 WHERE TRUE ORDER BY ((1 IS NOT NULL)) NOT BETWEEN ((((86238108)-(-9223372036854775808)) < 1)) AND (t0.c0);
             info
-------------------------------
  distribution: local
  vectorized: true

  • sort
  │ order: +column6
  │
  └── • render
      │
      └── • scan
            missing stats
            table: t0@t0_pkey
            spans: FULL SCAN
```

**Expected behavior**
The generated BOOL column c0 should always be NOT NULL.

**Environment:**
 - CockroachDB version v22.2.0
 - Server OS: Ubuntu 22.04 LTS
 - Client app cockroach sql

Jira issue: CRDB-24695

**Comment by DrewKimball** [comment] 2023-02-28 21:10
It isn't intuitive, but `NOT NULL` is actually `NULL`. So, the first version of the table has a computed stored column that is guaranteed to be `NULL`. This allows the `ORDER BY` to be optimized away, since `BETWEEN` with a `NULL` value simplifies to the constant `NULL`. 

In the second version, the `c0` column happens to be `NULL`, but there is no guarantee, and so the `ORDER BY` cannot be simplified. Thus, we observe the overflow.

Closing this one as expected behavior.

**Closed by DrewKimball** 2023-02-28 21:10 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries
