### ISSUE TITLE
circleci: failed tests: TestGossipNoForwardSelf 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5926] opened 2016-04-07 18:15 UTC
The following test appears to have failed:

[#16040](https://circleci.com/gh/cockroachdb/cockroach/16040):

```
I160407 18:09:50.004210 gossip/server.go:261  @2: distantHops: 2 from 5
I160407 18:09:50.005491 gossip/client.go:84  closing client to node 1 (127.0.0.1:44739): gossip/client.go:168: received forward from node 1 to 4 (127.0.0.1:45024)
I160407 18:09:50.005980 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
==================
WARNING: DATA RACE
Write by goroutine 143:
  github.com/cockroachdb/cockroach/gossip.(*client).handleResponse()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:151 +0x847
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2.1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:229 +0x94
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:233 +0x62
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Previous read by goroutine 82:
  reflect.Value.Int()
      /usr/local/go/src/reflect/value.go:887 +0x14f
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:865 +0x44e
  fmt.(*pp).printValue()
      /usr/local/go/src/fmt/print.go:848 +0x551
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:932 +0x4aa5
  fmt.(*pp).printValue()
      /usr/local/go/src/fmt/print.go:848 +0x551
--
  github.com/cockroachdb/cockroach/gossip.TestGossipNoForwardSelf()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip_test.go:197 +0x1585
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 143 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:234 +0x573
  github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:78 +0x323
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Goroutine 82 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:120 +0x210
==================
==================
WARNING: DATA RACE
Write by goroutine 143:
  github.com/cockroachdb/cockroach/gossip.(*client).handleResponse()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:153 +0x900
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2.1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:229 +0x94
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:233 +0x62
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Previous read by goroutine 82:
  reflect.Value.pointer()
      /usr/local/go/src/reflect/value.go:91 +0x97
  reflect.Value.MapKeys()
      /usr/local/go/src/reflect/value.go:1070 +0xec
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:893 +0x2eb1
  fmt.(*pp).printValue()
      /usr/local/go/src/fmt/print.go:848 +0x551
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:932 +0x4aa5
--
  github.com/cockroachdb/cockroach/gossip.TestGossipNoForwardSelf()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip_test.go:197 +0x1585
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Goroutine 143 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:234 +0x573
  github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:78 +0x323
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Goroutine 82 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:120 +0x210
==================
I160407 18:09:50.008043 gossip/client.go:146  node 5 received [node:4] from node 1 (1 fresh)
I160407 18:09:50.008126 gossip/server.go:261  @5: distantHops: 2 from 2
I160407 18:09:50.009295 gossip/client.go:146  node 4 received [node:2 node:5 node:1] from node 1 (1 fresh)
I160407 18:09:50.009408 gossip/server.go:261  @4: distantHops: 2 from 2
I160407 18:09:50.009693 gossip/client.go:146  node 4 received [node:1 node:2 node:5] from node 1 (0 fresh)
I160407 18:09:50.009789 gossip/server.go:261  @4: distantHops: 2 from 2
--- FAIL: TestGossipNoForwardSelf (0.09s)
	gossip_test.go:197: expected &{1 0xc820126098 <nil> map[1:1460052589965876342 2:1460052589969675619 5:1460052589982517365] 0xc82014e060} to be disconnected, got &{1 0xc820126098 0xc820195d40 map[] 0xc820432ea0}
=== RUN   TestGossipCullNetwork
W160407 18:09:50.034398 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
W160407 18:09:50.037469 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:09:50.041210 gossip/gossip.go:913  starting client to 127.0.0.1:53619
W160407 18:09:50.041830 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:09:50.043762 gossip/gossip.go:913  starting client to 127.0.0.1:34182
W160407 18:09:50.044360 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:09:50.046304 gossip/gossip.go:913  starting client to 127.0.0.1:59922
I160407 18:09:50.051781 gossip/server.go:114  node 4 returned 1 info(s) to node 1
--
I160407 18:09:51.307257 gossip/server.go:206  node 1 received [127.0.0.1:33932 127.0.0.1:49539 node:4] from node 3 (3 fresh)
I160407 18:09:51.307342 gossip/server.go:261  @1: distantHops: 2 from 4
I160407 18:09:51.307630 gossip/server.go:206  node 1 received [127.0.0.1:49539 node:4 127.0.0.1:33932] from node 3 (0 fresh)
I160407 18:09:51.309813 gossip/server.go:261  @1: distantHops: 2 from 4
--- PASS: TestGossipStorage (0.12s)
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	1.867s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.086s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-07 21:29
Duplicate of #5923

**Closed by bdarnell** 2016-04-07 21:29 UTC
Labels: Robot, test-failure
