### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestShowCreateTable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6276] opened 2016-04-25 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/fbb1243f55df4aa02f59c57d4133ec85460748e7

Stress build found a failed test:

```
=== RUN   TestShowCreateTable
W160425 06:29:35.366341 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160425 06:29:35.368687 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160425 06:29:35.370867 server/node.go:359  store store=0:0 ([]=) not bootstrapped
W160425 06:29:35.370885 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160425 06:29:35.372562 storage/replica_command.go:1439  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.37220781s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.372474727 +0000 UTC]
I160425 06:29:35.373155 server/node.go:309  **** cluster {e564d8d4-635a-4e77-97ea-aeb48b77c6cc} has been created
I160425 06:29:35.373175 server/node.go:310  **** add additional nodes by specifying --join=127.0.0.1:32943
W160425 06:29:35.373190 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160425 06:29:35.373773 server/node.go:372  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8106086400 RangeCount:0}
I160425 06:29:35.373791 server/node.go:284  node ID 1 initialized
I160425 06:29:35.373836 storage/stores.go:287  read 0 node addresses from persistent storage
I160425 06:29:35.373883 server/node.go:493  connecting to gossip network to verify cluster ID...
I160425 06:29:35.374026 server/node.go:514  node connected via gossip and verified as part of cluster {"e564d8d4-635a-4e77-97ea-aeb48b77c6cc"}
I160425 06:29:35.374056 server/node.go:337  [node=1] Started node with [[]=] engine(s) and attributes []
I160425 06:29:35.374079 server/server.go:366  starting https server at 127.0.0.1:35777
I160425 06:29:35.374090 server/server.go:367  starting grpc/postgres server at 127.0.0.1:32943
I160425 06:29:35.374240 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160425 06:29:35.375613 storage/replica_command.go:1901  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160425 06:29:35.376065 server/updates.go:147  No previous updates check time.
I160425 06:29:35.384293 storage/replica_command.go:1439  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.473402794s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.384240998 +0000 UTC]
I160425 06:29:35.384413 storage/replica_command.go:1901  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160425 06:29:35.397175 storage/replica_command.go:1439  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.473402794s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.397145272 +0000 UTC]
I160425 06:29:35.397273 storage/replica_command.go:1901  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160425 06:29:35.408897 storage/replica_command.go:1439  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.473402794s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.408849613 +0000 UTC]
I160425 06:29:35.409021 storage/replica_command.go:1901  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160425 06:29:35.476313 storage/replica_command.go:1439  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.526138324s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.47627301 +0000 UTC]
I160425 06:29:35.476408 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160425 06:29:35.476611 storage/replica_command.go:1901  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160425 06:29:35.487764 storage/replica_command.go:1439  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.537563315s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.487726403 +0000 UTC]
I160425 06:29:35.495147 storage/split_queue.go:100  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0 /Table/52/0]
I160425 06:29:35.495329 storage/replica_command.go:1901  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160425 06:29:35.509315 storage/replica_command.go:1439  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.558903653s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.509258255 +0000 UTC]
I160425 06:29:35.509916 storage/replica_command.go:1901  initiating a split of range=7 [/Table/51-/Max) at key /Table/52
I160425 06:29:35.523197 storage/replica_command.go:1439  range 8: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405990h29m36.572540404s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-25 06:29:35.52314885 +0000 UTC]
I160425 06:29:35.532635 storage/split_queue.go:100  splitting range=8 [/Table/52-/Max) at keys [/Table/53/0 /Table/54/0]
I160425 06:29:35.532844 storage/replica_command.go:1901  initiating a split of range=8 [/Table/52-/Max) at key /Table/53
I160425 06:29:35.534806 stopper.go:352  draining; tasks left:
2      server/node.go:742
1      storage/queue.go:383
1      kv/txn_coord_sender.go:895
I160425 06:29:35.534845 stopper.go:352  draining; tasks left:
2      server/node.go:742
1      storage/queue.go:383
E160425 06:29:35.535032 client/txn.go:391  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: writing transaction timed out or ran on multiple coordinators
E160425 06:29:35.535251 storage/queue.go:446  [split] range=8 [/Table/52-/Max): error: storage/split_queue.go:103: unable to split range=8 [/Table/52-/Max) at key "/Table/53/0": storage/replica_command.go:1954: split at key /Table/53 failed: writing transaction timed out or ran on multiple coordinators
I160425 06:29:35.535289 stopper.go:352  draining; tasks left:
1      storage/queue.go:383
--- FAIL: TestShowCreateTable (0.17s)
	show_test.go:125: pq: sql/lease.go:108: table ID 53 not found
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
3 runs so far, 0 failures, over 35s
10 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
18 runs so far, 0 failures, over 1m10s
19 runs so far, 0 failures, over 1m15s
24 runs so far, 0 failures, over 1m20s
29 runs so far, 0 failures, over 1m25s
30 runs so far, 0 failures, over 1m30s
30 runs so far, 0 failures, over 1m35s
32 runs so far, 0 failures, over 1m40s
32 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
35 runs so far, 0 failures, over 1m55s
38 runs so far, 0 failures, over 2m0s
41 runs so far, 0 failures, over 2m5s
43 runs so far, 0 failures, over 2m10s
43 runs so far, 0 failures, over 2m15s
43 runs so far, 0 failures, over 2m20s
43 runs so far, 0 failures, over 2m25s
45 runs so far, 0 failures, over 2m30s
48 runs so far, 0 failures, over 2m35s
50 runs so far, 0 failures, over 2m40s
53 runs so far, 0 failures, over 2m45s
53 runs so far, 0 failures, over 2m50s
53 runs so far, 0 failures, over 2m55s
55 runs so far, 0 failures, over 3m0s
57 runs so far, 0 failures, over 3m5s
59 runs so far, 0 failures, over 3m10s
60 runs completed, 1 failures, over 3m11s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-25 19:37
Duplicate of #6226

**Closed by bdarnell** 2016-04-25 19:37 UTC
Labels: Robot, test-failure
