### ISSUE TITLE
LEFT JOIN with multiple conditions: RangeIterator seek to invalid key /Min

### ISSUE THREAD

**Issue by dimpavloff** [cockroachdb/cockroach#83618] opened 2022-06-29 21:32 UTC
**Describe the problem**

As part of trying out 22.1, we've stumbled on the following error with one of our queries:
`ERROR: RangeIterator seek to invalid key /Min`

The same query works fine on CRDB 21.2.10

**To Reproduce**

The actual query we have is a bit more complicated as it has an extra LEFT JOIN an other WHERE clauses but hopefully the below simplifies the steps it w.l.o.g:

```
CREATE TABLE a (
  id TEXT PRIMARY KEY
);

CREATE TABLE b (
  id TEXT PRIMARY KEY,
  a_id TEXT ,
  status INT,
  INDEX b_a_id (a_id ASC),
  INDEX b_status_idx (status ASC)
);

SELECT a.id FROM a
LEFT JOIN b AS b2 ON (a.id = b2.a_id AND b2.status = 2) 
WHERE (a.id IN ('3f90e30a-c87a-4017-b9a0-8f964b91c4af',
'3adaf3da-0368-461a-8437-ee448724b78d', 'd0c13b06-5368-4522-8126-105b0a9513cd', 'a52d579d-dfcb-45ab-9991-9f0a2e2b936d'))
ORDER BY id DESC
LIMIT 2;

```

If `AND b2.status = 2` is removed, then the query works. 
If the LIMIT value is changed to 1 or >3, then the query works again. If I run `EXPLAIN` on the query with `LIMIT 2` and then `LIMIT 6`, one difference which stands out is the use of `revscan` in the case when the query fails.

**Expected behavior**
The query does not error.

**Environment:**
 - CockroachDB version: 22.1.2
 - Server OS: Linux
 - Client app: `cockroach sql`

Jira issue: CRDB-17175

**Comment by alistair-roacher** [comment] 2022-07-01 11:56
Managed to recreate this issue using v21.2.0 but appears to be fixed in v21.2.12.
Cannot recreate with v21.1.2 or v21.1.11 so looks like it was probably introduced in v21.2.0.

**Comment by rytaft** [comment] 2022-07-11 22:47
Thank you for the report, @dimpavloff! Confirmed that I can reproduce on 22.1 and not on the latest version of 21.2. It also reproduces on master. Looking into this now.

**Comment by rytaft** [comment] 2022-07-12 02:52
I bisected to this commit:
```
commit 5b7a6102a134c657ebb7836d6f134842ea78d8dd
Author: Jordan Lewis <jordanthelewis@gmail.com>
Date:   Fri Mar 5 19:30:35 2021 -0400

    sql: issue GetRequests from SQL when possible
    
    Previously, SQL unconditionally emitted ScanRequests for every read that
    it produced, even if we were completely sure that the scan could contain
    only a single key that was fully known at request time.
    
    This was less efficient than necessary, because ScanRequests cause the
    KV layer to do more work than GetRequests.
    
    Here are the reasons why GetRequests are more efficient:
    
    - MVCCGet, unlike MVCCScan, is able to use a prefix iterator, which
      allows it to make use of RocksDB/Pebble bloom filters. There may also
      be other wins at the storage layer, like avoiding prefetching
    - various data structures have optimizations and fast-paths for
      single-key operations (e.g. timestamp cache, latch manager, refresh
      span tracking)
    - various code paths are simpler in the point operation case
    - a point operation implies only needing a single key allocation instead
      of a start and end key allocation
    - a point operation implies only needing to return up to a single
      result, which means that we can avoid some indirection in various
      places
    - A scan over a span that has at most 1 key, but does not know it, needs
      to iterate over all the versions (or eventually do a second expensive
      seek), looking for the non-existent next key in the span. A Get can do
      a single seek, read the key, and be done.
    
    Release note (performance improvement): SQL will now emit GetRequests
    when possible to KV instead of always emitting ScanRequests. This
    manifests as a modest performance improvement for some workloads.
```

**Closed** 2022-08-03 22:03 UTC
Labels: C-bug, O-community, T-sql-queries

**Comment by dimpavloff** [comment] 2022-08-04 09:37
Thanks for the fix!

**Comment by yuzefovich** [comment] 2022-08-04 15:49
@dimpavloff thanks for the report and a repro!
