### ISSUE TITLE
intsets: v22.2.12: panic in Sparse.IsEmpty

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109944] opened 2023-09-02 00:03 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4447195697/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4447195697/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: invalid memory address or nil pointer dereference
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:240
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | runtime.panicmem
  | 	GOROOT/src/runtime/panic.go:260
  | runtime.sigpanic
  | 	GOROOT/src/runtime/signal_unix.go:835
  | golang.org/x/tools/container/intsets.(*Sparse).IsEmpty
  | 	golang.org/x/tools/container/intsets/external/org_golang_x_tools/container/intsets/sparse.go:300
  | github.com/cockroachdb/cockroach/pkg/util.(*FastIntSet).fitsInSmall
  | 	github.com/cockroachdb/cockroach/pkg/util/pkg/util/fast_int_set.go:88
  | github.com/cockroachdb/cockroach/pkg/util.FastIntSet.SubsetOf
  | 	github.com/cockroachdb/cockroach/pkg/util/pkg/util/fast_int_set.go:344
  | github.com/cockroachdb/cockroach/pkg/sql/opt.ColSet.SubsetOf
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*FuncDepSet).ComputeClosure
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/func_dep.go:665
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*OrderingChoice).Simplify
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/ordering_choice.go:738
  | github.com/cockroachdb/cockroach/pkg/sql/opt/ordering.distinctOnBuildChildReqOrdering
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/group_by.go:86
  | github.com/cockroachdb/cockroach/pkg/sql/opt/ordering.BuildChildRequired
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/ordering/ordering.go:64
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.BuildChildPhysicalProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/physical_props.go:88
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:761
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:765
Wraps: (3) runtime error: invalid memory address or nil pointer dereference
  | -- cause hidden behind barrier
  | runtime error: invalid memory address or nil pointer dereference
  | (1) runtime error: invalid memory address or nil pointer dereference
  | Error types: (1) runtime.errorString
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: invalid memory address or nil pointer dereference
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L764-L766)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L760-L762](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L760-L762)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/physical_props.go#L87-L89](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/physical_props.go#L87-L89)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/ordering/ordering.go#L63-L65](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/ordering/ordering.go#L63-L65)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/ordering/group_by.go#L85-L87](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/ordering/group_by.go#L85-L87)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/props/ordering_choice.go#L737-L739](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/props/ordering_choice.go#L737-L739)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/props/func_dep.go#L664-L666](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/props/func_dep.go#L664-L666)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/colset.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/colset.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/pkg/util/fast_int_set.go#L343-L345](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/pkg/util/fast_int_set.go#L343-L345)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/pkg/util/fast_int_set.go#L87-L89](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/pkg/util/fast_int_set.go#L87-L89)
[golang.org/x/tools/container/intsets/external/org_golang_x_tools/container/intsets/sparse.go#L299-L301](golang.org/x/tools/container/intsets/external/org_golang_x_tools/container/intsets/sparse.go#L299-L301)
[GOROOT/src/runtime/signal_unix.go#L834-L836](GOROOT/src/runtime/signal_unix.go#L834-L836)
[GOROOT/src/runtime/panic.go#L259-L261](GOROOT/src/runtime/panic.go#L259-L261)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/sql/opt/xform/optimizer.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/feededb3d12a703bada7699b65ad1e191f97a91b/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 765
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 761
pkg/sql/opt/xform/physical_props.go in pkg/sql/opt/xform.BuildChildPhysicalProps at line 88
pkg/sql/opt/ordering/ordering.go in pkg/sql/opt/ordering.BuildChildRequired at line 64
pkg/sql/opt/ordering/group_by.go in pkg/sql/opt/ordering.distinctOnBuildChildReqOrdering at line 86
pkg/sql/opt/props/ordering_choice.go in pkg/sql/opt/props.(*OrderingChoice).Simplify at line 738
pkg/sql/opt/props/func_dep.go in pkg/sql/opt/props.(*FuncDepSet).ComputeClosure at line 665
pkg/sql/opt/colset.go in pkg/sql/opt.ColSet.SubsetOf at line 113
pkg/util/pkg/util/fast_int_set.go in pkg/util.FastIntSet.SubsetOf at line 344
pkg/util/pkg/util/fast_int_set.go in pkg/util.(*FastIntSet).fitsInSmall at line 88
golang.org/x/tools/container/intsets/external/org_golang_x_tools/container/intsets/sparse.go in golang.org/x/tools/container/intsets.(*Sparse).IsEmpty at line 300
GOROOT/src/runtime/signal_unix.go in runtime.sigpanic at line 835
GOROOT/src/runtime/panic.go in runtime.panicmem at line 260
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize.func1 at line 240
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v22.2.12 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.12 |
| Cockroach SHA | feededb3d12a703bada7699b65ad1e191f97a91b |
| # of CPUs | 20 |
| # of Goroutines | 3274 |

Jira issue: CRDB-31171

**Comment by rharding6373** [comment] 2023-11-03 02:26
This can only happen if the Sparse fast int set's root is nil, but it's not clear what events lead to this since the root should never be null.

**Comment by rharding6373** [comment] 2023-11-05 14:59
Closing as not reproducible.

**Closed by rharding6373** 2023-11-05 14:59 UTC
Labels: C-bug, O-sentry, T-sql-queries
