### ISSUE TITLE
sql: TemporaryObjectCleaner needs work for multi-tenancy

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#47894] opened 2020-04-22 09:36 UTC
TemporaryObjectCleaner uses the status server and isMeta1Leaseholder, both of which won't be available on a [SQL tenant server](https://docs.google.com/document/d/1EI8T-3N77g0OOlALwzRC0ddji1_4rH2xZvG9GbAa6D0/edit?ts=5e7a83b4#):

https://github.com/cockroachdb/cockroach/blob/0b0750433e6369bcc8f46e6b9a6b82fd1a1c6f25/pkg/sql/temporary_schema.go#L390-L400

I think we want to continue cleaning schemas as a periodic operation running on the SQL tenant itself (as opposed to running it on behalf of all tenants in the KV layer). This means some work needs to be done here to avoid these dependencies.

This issue is likely easy to address if we figure out how to get `SHOW SESSIONS` etc to work in this setting.

I don't think this blocks phase 2 (if some temporary schemas don't get cleaned up, that's fine I guess) but note that in phase 2 we know that there's at most one SQL tenant at any given time, so it should be easy to always clean in that case.

**Comment by rafiss** [comment] 2022-01-20 06:23
It looks like this is a dupe of https://github.com/cockroachdb/cockroach/issues/67401 and was resolved by https://github.com/cockroachdb/cockroach/pull/69486. closing. cc @fqazi @ajwerner

**Closed by rafiss** 2022-01-20 06:23 UTC
Labels: A-multitenancy, T-sql-queries
