### ISSUE TITLE
Almost everything leaks a Store

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#498] opened 2015-03-28 07:40 UTC
See `test.log` from https://circleci.com/gh/cockroachdb/cockroach/990

**Comment by joezxy** [comment] 2015-03-28 09:30
I am also testing the latest code in my machine, found there are leak problems in storage folder caused by TestAllocateErrorAndRecovery. Actually this file was committed before leak testing was added, so i did not found this problem at that time. Very sorry for that...i will fix this problem.

And by the same time, maybe you can remove this testcase or revert the PR. I will resubmit it after resolve this leak issue. Sorry for that again...

**Comment by joezxy** [comment] 2015-03-28 12:49
The reason of this problem: IDAllocator.Allocate() will start background "allocateBlock()" goroutine to prefetch IDs in the middle. If TestXXX returns before these goroutines finish, then leak problem will come.

Add time.Sleep(50 * time.Millisecond) at the last of TestAllocateErrorAndRecovery will resolve this problem

@tschottdorf , could you please try this on your machine? and add it into your PR #497 if ok. I think it will be faster for recorvering the code comparing with raising another PR by me.

Very sorry for disturbing you all by my mistake.

**Closed** 2015-03-28 17:49 UTC

**Comment by bdarnell** [comment] 2015-03-28 17:51
By the way, there was only one leak here; it just looked like everything leaked because of poor error reporting (once something is leaked, it will probably stay leaked and be reported on every following test).
