### ISSUE TITLE
kv: range split causes span config to change

### ISSUE THREAD

**Issue by jayshrivastava** [cockroachdb/cockroach#109507] opened 2023-08-25 15:40 UTC
In https://github.com/cockroachdb/cockroach/issues/109306, we observed that when a range was split, the new range had a different span config than the original.

The particular span config setting which was flipped was `rangefeed_enabled`. In our test, this was true by default, but was false when we started a rangefeed on the newly created range. We expect that this setting (perhaps all span configs) would be consistent with the original range upon splitting.

Jira issue: CRDB-30959

**Comment by arulajmani** [comment] 2023-08-25 15:42
(Copying over from Slack)

The RHS of the split starts off as an uninitialized replica, which is given the default span configuration of the cluster. Once the split is processed, we update it with the correct span configuration once the split has applied. See around: https://github.com/cockroachdb/cockroach/blob/c215aba0c61518342af3f865f74f07cf43f6ac2e/pkg/kv/kvserver/replica_raftstorage.go#L383-L413
Looks like [r.mu](http://r.mu/) , which protects r.mu.conf, is only acquired inside of r.SetSpanConfig(). So there does seem to be a race here, if the `r.mu.conf` is read before the span config is set. I'm not sure if this is intentional or an oversight.

**Comment by aliher1911** [comment] 2023-09-28 18:10
I don't completely follow where the race is. Looking at the split:

https://github.com/cockroachdb/cockroach/blob/a851fe95f9715fd95fe25907e770514a7157d802/pkg/kv/kvserver/store_split.go#L332-L341

we update config before calling `markReplicaInitializedLockedReplLocked` so I expect store not to send rangefeed requests to the replica until it was marked as initialized there.

Do we have any repro or at least conditions when such race occurs?

**Comment by jayshrivastava** [comment] 2023-09-29 03:44
I believe stressing the test in https://github.com/cockroachdb/cockroach/issues/109306 on the commit SHA will eventually repro the problem. I know for sure that `r.isRangefeedEnabledRLocked()` must have returned false for the test to fail. I also saw in the log messages that a range split occurred before setting the "rangefeed must be enabled error". There's some more details in that issue.

**Comment by aliher1911** [comment] 2023-09-29 13:09
I don't think this has anything to do with replica temporary losing its span config on split. Can't make it to fail in stress but the error in the log shows at least something:
```
I230823 06:01:04.432105 1088810 ccl/changefeedccl/cdctest/row.go:73 ⋮ [-] 614  Read row ‹/Table/106/1/"only_some_deleted_values"/100/0›
I230823 06:01:04.432223 1088810 ccl/changefeedccl/cdctest/row.go:73 ⋮ [-] 615  Read row ‹/Table/106/1/"only_some_deleted_values"/100/1/1›
I230823 06:01:04.911048 1142796 kv/kvserver/replica_command.go:438 ⋮ [T1,n1,split,s1,r63/1:‹/{Table/62-Max}›] 616  initiating a split of this range at key /Table/106 [r64] (‹span config›)‹›
W230823 06:01:04.954302 1094472 kv/kvclient/rangefeed/rangefeed.go:331 ⋮ [rangefeed=‹feed-foo›] 617  rangefeed failed 0 times, restarting: rangefeeds require the kv.rangefeed.enabled setting. See ‹https://www.cockroachlabs.com/docs/v23.1/change-data-capture.html#enable-rangefeeds-to-reduce->
```
It looks like we are consuming data from /Table/106 for some time. Then we get a split which is triggered by split queue realizing that it needs to split ranges on span configs. Which looks like previously our table was still part of the larger range `/{Table/62-Max}` that included previous tables and stretching to the end of keyspace. That range had rangefeeds enable so everything worked.
Once we split, we applied new span config which doesn't have range feeds enabled and test fails.

I checked out SHA in question and added a 30 sec sleep after everything is deleted from the table.
Test is now failing 100% times because we are guaranteed to make this split prior to executing test.
Which means span is incorrectly configured in the first place but test used to pass because split queue was not picking up new configs fast enough. I don't think it is a problem by itself as this queue is asynchronous by design.

**Comment by aliher1911** [comment] 2023-09-29 13:11
So the fix you made to explicitly enable range feeds is addressing the real issue. I'm closing this off as there's nothing to do here.

**Closed by aliher1911** 2023-09-29 13:11 UTC
Labels: C-bug, A-kv-replication, branch-master, GA-blocker, T-kv-replication
