### ISSUE TITLE
jobs: Unexpected Network Activity Due to Jobs in Jobs Table

### ISSUE THREAD

**Issue by gnanakeethan** [cockroachdb/cockroach#57370] opened 2020-12-02 14:29 UTC
**Describe the problem**

I have a fairly minimal database with 100MB of disk data. It has around 100,000 rows in total of all tables. I enabled scheduled backups on the system. 

**To Reproduce**

What did you do? Describe in your own words.

1. I setup a secure cluster. m5.large x 3 in AWS 
2. Cluster Initialised Successfully
3. Restore From latest backup (100,000 rows of rows in total of all tables)
4. Enable Backups to AWS S3, via instance role. (AUTH=implicit)

**Expected behavior**
Regular backups in intervals I configured. It happened. But it also increased network activity over time, which grown little suspicious. I disabled the backups and the network activity stabilised at the level it was brought up. 

**Additional data / screenshots**

![Screenshot 2020-12-02 at 19 57 37](https://user-images.githubusercontent.com/2353181/100885422-a32abf00-34d8-11eb-9fb5-052cd5b426bb.jpg)
Each spike in the graph is a backup activity occurring every hour.

![Screenshot 2020-12-02 at 19 58 51](https://user-images.githubusercontent.com/2353181/100885585-d5d4b780-34d8-11eb-9c6f-5de203ea6561.jpg)
Network Activity is transmitted across the nodes in a similar fashion. 

**Environment:**
 - CockroachDB version 20.2.2
 - Server OS: Amazon Linux 2

**Additional context**
What was the impact?
Overall network consumption grows over time without hitting a limit.

**Comment by mwang1026** [comment] 2020-12-02 15:31
Thanks @gnanakeethan for filing. I wanted to confirm that you're not doing any other operations on the cluster (read, write, schema change) and the only thing you did was (1) RESTORE and then (2) setup the backup schedule. If that's not the case, it'd be helpful to know what kind of workload you have running on the cluster / what kind of operations you're doing on the cluster.

Thanks!

**Comment by gnanakeethan** [comment] 2020-12-03 07:26
Yes. I can confirm this. I do not have any schema changes since my last backup and restore operation. Attached the screenshots previously. If I increase the frequency of the backups, the network bandwidth consumed following each scheduled backup operation goes up as it goes. 

I am unsure why it is such. 

I am attaching an updated screenshot with latest day with our regular load. You can see the difference. 

![Screenshot 2020-12-03 at 12 55 45](https://user-images.githubusercontent.com/2353181/100977405-f3e8f900-3566-11eb-8fd3-0e8bb65c6b2c.jpg)


Thanks

**Comment by gnanakeethan** [comment] 2020-12-03 07:31
@mwang1026 You can clearly see that there is a difference after the spike at 00:00, which is a scheduled backup operation.

**Comment by dt** [comment] 2020-12-04 20:59
@gnanakeethan Thanks for the report! We were able to reproduce this internally. 

Some notes for our internal digging: it looks like if we move the leaseholder for the internal jobs table, we see the node sending and nodes receiving change as well, so it follows that we're seeing jobs traffic here. What's interesting is that the traffic doesn't coincide to when the schedule actually runs -- even if we disable schedule execution loop completely (`jobs.scheduler.enabled = false`) we still see the elevated activity remain constant (though it stops growing). So what it looks like is we have activity as a function of size of -- not changes to -- the jobs table. The current theory is this is probably related to the new job claiming code in 20.2, so BulkIO is handing this one over to Schema (who may have already merged some fixes for that for the next patch release?)

**Comment by gnanakeethan** [comment] 2020-12-05 06:33
@dt  Thank you very much. 

I suppose this can be affecting most of the installations then. 

Hope to have a fix soon. 

Thanks.

**Comment by ajwerner** [comment] 2020-12-09 01:28
This should be fixed by https://github.com/cockroachdb/cockroach/pull/57591 which should be out in 20.2.3 in a week or so.

**Comment by ajwerner** [comment] 2020-12-09 01:28
Let me confirm that now.

**Comment by ajwerner** [comment] 2020-12-09 14:13
Yep, confirmed.

**Closed by ajwerner** 2020-12-09 14:13 UTC
Labels: C-bug, O-community, X-blathers-triaged

**Comment by gnanakeethan** [comment] 2020-12-09 14:17
Thank you @ajwerner
