### ISSUE TITLE
sql: spurious "unique constraint violation" error on non-unique index

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#19087] opened 2017-10-06 14:42 UTC
Table schema:

```sql
CREATE TABLE transaction_event (
    id INT NOT NULL DEFAULT unique_rowid(),
    message BYTES NOT NULL,
    received INT NOT NULL,
    username STRING(255) NOT NULL,
    classname STRING(255) NOT NULL,
    send_id STRING(255) NULL,
    send_timestamp TIMESTAMP NULL,
    CONSTRAINT pk_transaction_event PRIMARY KEY (id ASC),
    INDEX transaction_event_send_timestamp_idx (send_timestamp ASC),
    FAMILY "primary" (id, message, received, username, classname, send_id, send_timestamp)
);
```

The user encounters the following error:
```
ERROR: duplicate key value (send_timestamp)=(285826096097689601) violates unique constraint "transaction_event_send_timestamp_idx"
```

when issuing this statement:
```
update transaction_event set send_id=?, send_timestamp=? where (send_id is null) and (id in (? , ? , ? , ? , ? , ? , ? , ?))
```
with parameters (e.g.)
```
(b79195a0-5bd7-4bc5-ab74-526ea0e5a10d,2017-10-06 15:46:22.785,285826096097689601,285826096657727489,285826096989339650,285826097310597121,285826097641521155,285826097964285954,285826098301337602,285826098678267906)
```

Since the index is not unique the error should not be generated. However the function `ConvertBatchError` which generates the error is a bit convoluted and it may be that the message really means something different.

@danhhz @jordanlewis any opinion? Is there any chance this spurious message could appear as a result of #18533?

**Comment by petermattis** [comment] 2017-10-06 14:49
Is it possible that `update` is overwriting an existing key in the `transaction_event_send_timestamp_idx` index when nothing has changed for the row?

Also, that error message looks erroneous as it seems to be comparing `send_timestamp` with `id`.

**Comment by knz** [comment] 2017-10-06 15:05
Hi Jordan I am assigning to you for initial look, but really because I think you're the best person to triage this.

**Comment by jordanlewis** [comment] 2017-10-06 15:11
I'm not going to get to this for a little while, since I'm out this weekend until Tuesday night. If this is high priority I would recommend assigning someone else for now - I'll be happy to look myself next week in either case.

**Comment by knz** [comment] 2017-10-06 15:14
Good call, thanks. @vivekmenezes do you want to triage?

**Comment by dianasaur323** [comment] 2017-10-09 18:59
Ping! Let's make sure we follow up on this?

**Comment by vivekmenezes** [comment] 2017-10-11 13:17
Jordan's back today so hoping he can take a look at this.

**Comment by jordanlewis** [comment] 2017-10-11 14:00
@knz is the example you gave internally consistent? In other words, did the error message you provided arise from that exact set of parameters? Just wondering since you wrote (e.g.) next to the parameters.

**Comment by jordanlewis** [comment] 2017-10-11 14:09
Also, has anyone tried or succeeded to reproduce this?

**Comment by knz** [comment] 2017-10-11 14:10
Yes it is easily reproducible

**Comment by jordanlewis** [comment] 2017-10-11 23:13
Having a tough time reproducing it myself. I did a couple of tests to try to reproduce it - loaded a ton of random data into the table with and without nulls and tried to run that update with a combination of null and not null rows in the `IN` clause.

Also tried the following simple test without success, for posterity:

```
root@:26257/test> INSERT INTO transaction_event(message, received, username, classname) VALUES ('hi', 2, 'foo', 'bar'), ('hi', 2, 'foo', 'bar');
INSERT 2

Time: 5.821826ms

root@:26257/test> select * from transaction_event;
+--------------------+---------+----------+----------+-----------+---------+----------------+
|         id         | message | received | username | classname | send_id | send_timestamp |
+--------------------+---------+----------+----------+-----------+---------+----------------+
| 287352459338317825 | hi      |        2 | foo      | bar       | NULL    | NULL           |
| 287352459338350593 | hi      |        2 | foo      | bar       | NULL    | NULL           |
+--------------------+---------+----------+----------+-----------+---------+----------------+
(2 rows)

root@:26257/test> update transaction_event set send_id='foo', send_timestamp='2009-01-31 13:35:46+00:00' where send_id is null and (id in (287352459338317825, 287352459338350593));
UPDATE 2

Time: 3.067229ms
```

**Comment by jordanlewis** [comment] 2018-02-22 04:50
@BramGruneir weren't you working on something similar to this? Any chance it's the same issue?

**Comment by BramGruneir** [comment] 2018-02-22 16:13
Sadly no.  My issue was that I just hadn't converted the errors using ConvertBatchError yet so they were not human readable.

**Comment by jordanlewis** [comment] 2018-03-05 18:44
Closing this as unreproducible. We can re-open if necessary.

**Closed by jordanlewis** 2018-03-05 18:44 UTC
Labels: bug
