### ISSUE TITLE
storage: optimize read path for the no-range-keys case

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#82559] opened 2022-06-07 22:46 UTC
It was observed in #82045 that there is a ~20% slowdown in the existing, typical read path when using an iterator stack that supports range keys, even in the case when there are no range keys to iterate over.

We'll want to claw back some / all of this slowdown.

`HasPointAndRange()` has also been seen to be a significant contributor, and should be optimized. Related to #83801.

Once this is done, we should optimize and benchmark the following performance-critical paths again, comparing them with 22.1:

- [x] `MVCCScan`
- [x] `MVCCGet`
- [x] `ComputeStats`
- [x] `MVCCExportToSST`
- [x] `CatchUpIterator.CatchUpScan`

Jira issue: CRDB-16511

Epic CRDB-2624

**Comment by erikgrinaker** [comment] 2022-08-07 19:06
I ran some benchmarks comparing `release-22.1` against `master`. The results aren't too bad -- I think we should aim to get the regressions below 5% before we ship, which seems like it should be within reach.

```
name                                                           old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24                5.04µs ± 1%    5.28µs ± 2%   +4.79%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=1/versions=10/valueSize=64-24               6.87µs ± 1%    7.17µs ± 1%   +4.31%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24              34.6µs ± 1%    37.9µs ± 1%   +9.64%  (p=0.000 n=8+10)
MVCCScan_Pebble/rows=100/versions=10/valueSize=64-24              113µs ± 1%     119µs ± 1%   +6.02%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24            2.45ms ± 2%    2.72ms ± 1%  +10.77%  (p=0.000 n=10+7)
MVCCScan_Pebble/rows=10000/versions=10/valueSize=64-24           9.12ms ± 1%   10.18ms ± 1%  +11.70%  (p=0.000 n=10+9)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-24         5.51µs ± 1%    5.82µs ± 2%   +5.62%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=1/versions=10/valueSize=64-24        9.21µs ± 1%    9.77µs ± 0%   +6.03%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=64-24       46.3µs ± 1%    50.9µs ± 1%   +9.90%  (p=0.000 n=10+9)
MVCCReverseScan_Pebble/rows=100/versions=10/valueSize=64-24       316µs ± 1%     334µs ± 1%   +5.86%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=64-24     3.62ms ± 1%    3.94ms ± 1%   +8.62%  (p=0.000 n=10+9)
MVCCReverseScan_Pebble/rows=10000/versions=10/valueSize=64-24    29.4ms ± 9%    31.7ms ± 2%   +7.58%  (p=0.002 n=10+10)
MVCCGet_Pebble/versions=1/valueSize=8-24                         4.81µs ± 1%    5.05µs ± 1%   +5.09%  (p=0.000 n=10+9)
MVCCGet_Pebble/versions=10/valueSize=8-24                        5.81µs ± 1%    6.14µs ± 1%   +5.60%  (p=0.000 n=9+10)
MVCCGet_Pebble/versions=100/valueSize=8-24                       13.9µs ± 3%    14.5µs ± 2%   +4.15%  (p=0.000 n=10+10)
MVCCComputeStats_Pebble/valueSize=32-24                           143ms ± 1%     173ms ± 1%  +20.89%  (p=0.000 n=9+10)
```

**Comment by erikgrinaker** [comment] 2022-08-15 11:59
Updated benchmarks show some improvement, but still a ~10% regression for scans:

```
name                                                          old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24               5.09µs ± 2%    5.33µs ± 1%   +4.78%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24             34.7µs ± 0%    38.2µs ± 2%  +10.09%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24           2.47ms ± 2%    2.74ms ± 1%  +10.91%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-24        5.53µs ± 1%    5.81µs ± 1%   +5.10%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=64-24      46.4µs ± 1%    50.4µs ± 2%   +8.65%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=64-24    3.68ms ± 2%    3.91ms ± 1%   +6.31%  (p=0.000 n=9+10)
MVCCGet_Pebble/versions=1/valueSize=8-24                        4.83µs ± 1%    5.02µs ± 1%   +3.93%  (p=0.000 n=9+8)
MVCCGet_Pebble/versions=10/valueSize=8-24                       5.88µs ± 2%    6.10µs ± 1%   +3.76%  (p=0.000 n=10+10)
MVCCGet_Pebble/versions=100/valueSize=8-24                      14.0µs ± 4%    14.1µs ± 3%     ~     (p=0.853 n=10+10)
MVCCComputeStats_Pebble/valueSize=8-24                           199ms ± 2%     219ms ± 1%   +9.77%  (p=0.000 n=10+10)
MVCCComputeStats_Pebble/valueSize=32-24                          139ms ± 1%     152ms ± 0%   +9.30%  (p=0.000 n=10+8)
MVCCComputeStats_Pebble/valueSize=256-24                        46.2ms ± 7%    48.5ms ± 9%     ~     (p=0.165 n=10+10)
```

**Comment by erikgrinaker** [comment] 2022-08-19 15:01
Some more benchmarks with #86440, getting down into the single digits:

```
name                                                   old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24        5.12µs ± 1%    5.49µs ± 2%  +7.15%  (p=0.000 n=9+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24      36.3µs ± 2%    38.3µs ± 1%  +5.49%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24    2.52ms ± 1%    2.71ms ± 0%  +7.78%  (p=0.000 n=10+7)
MVCCGet_Pebble/versions=1/valueSize=8-24                 4.83µs ± 1%    5.10µs ± 2%  +5.61%  (p=0.000 n=10+10)
MVCCGet_Pebble/versions=10/valueSize=8-24                5.91µs ± 1%    6.17µs ± 2%  +4.50%  (p=0.000 n=10+9)
MVCCGet_Pebble/versions=100/valueSize=8-24               14.6µs ± 3%    14.9µs ± 4%  +2.07%  (p=0.043 n=10+10)
MVCCComputeStats_Pebble/valueSize=32-24                   141ms ± 2%     154ms ± 2%  +9.21%  (p=0.000 n=10+10)
```

There is some variance compared to previous results (also for 22.1 case), but this may well be due to VM/cloud differences, so I'm note sure if they can really be compared precisely across runs.

**Comment by jbowens** [comment] 2022-08-19 22:44
Found some old, small fruit in Pebble in cockroachdb/pebble#1917 and cockroachdb/pebble#1918. 🍎 🍌 🍏 🍋 🍇

**Comment by erikgrinaker** [comment] 2022-08-21 13:16
Good news! I ran some `MVCCExportToSST` benchmarks on top of #86259 comparing them with 22.1, and we have a decent performance boost. I believe I made some simple, opportunistic optimizations here when I first added range key support (avoiding key comparisons and allocations and such).

TBI disabled (`StartTS=0`):

```
name                                                                       old time/op  new time/op  delta
MVCCExportToSST/numKeys=64/numRevisions=1/exportAllRevisions=false-24      60.4µs ± 1%  55.8µs ± 2%   -7.54%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=64/numRevisions=1/exportAllRevisions=true-24       58.3µs ± 1%  52.6µs ± 1%   -9.76%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=1/exportAllRevisions=false-24     484µs ± 2%   410µs ± 1%  -15.28%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=1/exportAllRevisions=true-24      433µs ± 3%   355µs ± 2%  -18.08%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=1/exportAllRevisions=false-24    3.25ms ± 0%  2.99ms ± 1%   -8.19%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=1/exportAllRevisions=true-24     2.82ms ± 0%  2.53ms ± 1%  -10.16%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=1/exportAllRevisions=false-24   24.5ms ± 0%  23.5ms ± 1%   -4.33%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=1/exportAllRevisions=true-24    21.2ms ± 0%  19.9ms ± 0%   -6.21%  (p=0.008 n=5+5)
```

TBI enabled (`StartTS>0`):

```
name                                                                       old time/op  new time/op  delta
MVCCExportToSST/numKeys=64/numRevisions=1/exportAllRevisions=false-24      78.0µs ± 3%  69.9µs ± 1%  -10.36%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=64/numRevisions=1/exportAllRevisions=true-24       72.6µs ± 1%  66.6µs ± 1%   -8.25%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=1/exportAllRevisions=false-24     698µs ± 1%   614µs ± 1%  -12.09%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=1/exportAllRevisions=true-24      644µs ± 1%   556µs ± 1%  -13.61%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=1/exportAllRevisions=false-24    4.94ms ± 1%  4.57ms ± 1%   -7.49%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=1/exportAllRevisions=true-24     4.52ms ± 0%  4.14ms ± 0%   -8.41%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=1/exportAllRevisions=false-24   37.8ms ± 0%  36.1ms ± 1%   -4.56%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=1/exportAllRevisions=true-24    34.5ms ± 1%  32.8ms ± 0%   -5.01%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=64/numRevisions=10/exportAllRevisions=false-24      170µs ± 5%   166µs ± 4%     ~     (p=0.222 n=5+5)
MVCCExportToSST/numKeys=64/numRevisions=10/exportAllRevisions=true-24       293µs ± 1%   270µs ± 2%   -7.83%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=10/exportAllRevisions=false-24   2.16ms ± 0%  2.19ms ± 1%   +1.09%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=1024/numRevisions=10/exportAllRevisions=true-24    3.95ms ± 0%  3.79ms ± 1%   -3.97%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=10/exportAllRevisions=false-24   17.5ms ± 0%  17.8ms ± 2%     ~     (p=0.056 n=5+5)
MVCCExportToSST/numKeys=8192/numRevisions=10/exportAllRevisions=true-24    31.2ms ± 0%  30.7ms ± 0%   -1.46%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=10/exportAllRevisions=false-24   147ms ± 0%   152ms ± 4%   +3.27%  (p=0.008 n=5+5)
MVCCExportToSST/numKeys=65536/numRevisions=10/exportAllRevisions=true-24    255ms ± 0%   253ms ± 0%   -0.73%  (p=0.008 n=5+5)
```

**Comment by erikgrinaker** [comment] 2022-08-21 13:16
And #86515 will mostly eliminate the `ComputeStats` performance regression.

**Comment by erikgrinaker** [comment] 2022-08-21 14:47
`CatchUpScan` is looking at about ~5% with #86512, which is in line with other benchmarks, and I guess is OK for now. Note that these benchmarks are with TBI enabled, since they all use a non-zero start time.

```
name                                                 old time/op  new time/op  delta
CatchUpScan/mixed-case/withDiff=true/perc=0.00-24     483ms ± 1%   529ms ± 2%  +9.49%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=true/perc=50.00-24    993ms ± 0%  1026ms ± 0%  +3.30%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=true/perc=75.00-24    876ms ± 1%   903ms ± 1%  +3.10%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=true/perc=95.00-24    178ms ± 1%   195ms ± 1%  +9.43%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=true/perc=99.00-24    154ms ± 1%   163ms ± 0%  +5.82%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=false/perc=0.00-24    743ms ± 1%   786ms ± 1%  +5.75%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=false/perc=50.00-24   634ms ± 0%   666ms ± 0%  +5.05%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=false/perc=75.00-24   578ms ± 1%   597ms ± 1%  +3.28%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=false/perc=95.00-24   166ms ± 1%   176ms ± 1%  +6.08%  (p=0.008 n=5+5)
CatchUpScan/mixed-case/withDiff=false/perc=99.00-24   152ms ± 0%   159ms ± 0%  +4.64%  (p=0.016 n=5+4)
```

**Comment by erikgrinaker** [comment] 2022-08-29 13:32
Ran some more scan benchmarks, and despite recent optimizations we're unfortunately still at about 8%:

```
name                                                          old time/op    new time/op    delta
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24               4.99µs ± 1%    5.37µs ± 1%  +7.68%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24             34.6µs ± 2%    37.4µs ± 2%  +7.81%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24           2.44ms ± 1%    2.64ms ± 1%  +8.24%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-24        5.55µs ± 1%    5.75µs ± 1%  +3.50%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=64-24      46.4µs ± 2%    49.5µs ± 1%  +6.52%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=64-24    3.61ms ± 0%    3.82ms ± 1%  +5.72%  (p=0.000 n=9+10)
```

**Comment by erikgrinaker** [comment] 2022-09-07 10:41
Given where we are in the release cycle, I think we've done what we can here. Closing this one out.

**Closed by erikgrinaker** 2022-09-07 10:41 UTC
Labels: C-performance, A-storage, T-storage
