### ISSUE TITLE
sql: Distribution awareness in the CBO/route local

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#41207] opened 2019-09-30 17:46 UTC
Currently, the CBO plans queries and distributes them based upon available resources among other decisions. This can be problematic because some queries could be executed entirely locally. Queries can need to travel across localities and pay a significant latency penalty when, if locality were factored into the decision making, they could be executed locally.

**Comment by rytaft** [comment] 2021-06-08 15:04
Duplicate of https://github.com/cockroachdb/cockroach/issues/47226. (Also partially fixed by locality optimized search)

**Closed by rytaft** 2021-06-08 15:04 UTC
Labels: C-enhancement, no-issue-activity
