### ISSUE TITLE
sql: partial result returned for aggregate statement before error is hit

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#51242] opened 2020-07-09 19:55 UTC
I have a table with no pre-define primary key 

`
CREATE TABLE z_leo_flowdomain2019 (
flowid INT4 NULL,
domainid INT8 NULL,
FAMILY "primary" (flowid, domainid, rowid)
)`

If I run select count on it will give inconsistent result and "batch timestamp" Error.

> root@:26257/playground> select count(0) from z_Leo_flowdomain2019;
    count
  708082566
(1 row)
(error encountered after some results were delivered)
ERROR: batch timestamp 1594235705.430809503,0 must be after replica GC threshold 1594235705.435869570,0

> root@:26257/playground> select count(0) from z_Leo_flowdomain2019;
    count
  863661188
(1 row)
(error encountered after some results were delivered)
ERROR: batch timestamp 1594323322.393613979,0 must be after replica GC threshold 1594323322.405023080,0

I am running 10 nodes CockroachDb 20.1.3

Jira issue: CRDB-4066

**Comment by nvanbenschoten** [comment] 2020-07-10 14:10
Hi @leomkkwan, thanks for the report. How long are these queries taking to run? The fact that you're returning about 1B rows implies that it might be a while. How long is your GC TLL on this table? Do you mind running `SHOW ZONE CONFIGURATION FOR TABLE z_Leo_flowdomain2019;`?

The error that you're seeing indicates that data you are trying to read has been GCed by the time you got to it. This likely indicates that your [GC TLL](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html#replication-zone-variables) is much lower than the 25-hour default.

Past that point, I think the question is why you're seeing a partial result for an aggregation before the `error encountered after some results were delivered` message and the error. @jordanlewis do you know why that might be? We shouldn't be spilling to the client due to memory pressure.

**Comment by leomkkwan** [comment] 2020-07-10 15:55
The TTL was set to 60 seconds, and the error will pop around 60 seconds. Once I change the ttl back to default 90000 seconds, I am able to run this query

> root@:26257/playground> select count(0) from z_Leo_flowdomain2019;
    count
  1004031639
(1 row)
Time: 2m44.702786483s

Thanks.

**Comment by nvanbenschoten** [comment] 2020-07-10 16:05
Got it. We typically don't recommend running with TTLs below 10 minutes. That's especially true if you intend to run queries that take multiple minutes.

So to summarize, we're not seeing inconsistent results from the select statement, we're seeing a partial result from the select statement before a GC error is hit and the partial result is revoked ("error encountered after some results were delivered"). Does that make sense?

The remaining question in my mind is why we're ever even returning a partial result in this situation. @yuzefovich can I assign you to take a look at that?

@leomkkwan is there anything else here that we can help with?

**Comment by yuzefovich** [comment] 2020-08-03 20:27
Hey @leomkkwan, I wonder if you still have the setup that reproduces the situation in which we return the result of partial aggregation followed by an error. If you do, could you please run `EXPLAIN` on the query? I'm interested whether the vectorized engine is used for that query because that could explain why partial aggregation result is returned - due to the fact that we might buffering an error and propagating it with a delay (due to some details of the implementation).

**Comment by asubiotto** [comment] 2020-09-18 08:29
Hi @leomkkwan,

I'm going to close this issue since there's been no activity. Please feel free to reopen with additional information.

**Comment by leomkkwan** [comment] 2020-09-18 14:21
Please re-open this ticket and this can be easily to be replicate

Make gc.ttlseconds to short enough value like 10 seconds, then run the query. The below test is running on v20.1.5

root@:26257/filu> select count(0) from t_baseid;
    count
-------------
  266533986
(1 row)

Time: 15.711376233s

root@:26257/filu> ALTER DATABASE filu CONFIGURE ZONE using      gc.ttlseconds = 10;
CONFIGURE ZONE 1

Time: 116.910251ms

root@:26257/filu> select count(0) from t_baseid;
   count
------------
  84845254
(1 row)
(error encountered after some results were delivered)
ERROR: batch timestamp 1600438666.455903709,0 must be after replica GC threshold 1600438666.458649192,0


root@:26257/filu> explain select count(0) from t_baseid;
       tree      |    field    |      description
-----------------+-------------+-------------------------
                 | distributed | true
                 | vectorized  | true
  group          |             |
   │             | aggregate 0 | count(column6)
   │             | scalar      |
   └── render    |             |
        └── scan |             |
                 | table       | t_baseid@idx_emailsha1
                 | spans       | FULL SCAN
(9 rows)

Time: 30.433645ms

**Comment by yuzefovich** [comment] 2023-11-26 22:08
Closing as unactionable

**Closed by yuzefovich** 2023-11-26 22:08 UTC
Labels: C-investigation, O-community, A-sql-execution, T-sql-queries, no-issue-activity
