### ISSUE TITLE
sql: improve error message on unique violation

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#20543] opened 2017-12-06 23:55 UTC
I had a composite primary key -> trying to insert a non-unique value into a row marked as unique threw this error:

pq: unexpected value: raw_bytes:"\215\204\375l\003\367\234@" timestamp:<wall_time:1512595115330023326 >

We should have a better error for this scenario?

**Comment by jordanlewis** [comment] 2017-12-18 16:04
Duplicate of #20780.

**Closed by jordanlewis** 2017-12-18 16:04 UTC
Labels: fixitday, ux-surprise
