### ISSUE TITLE
colexec: window logictest fails with unexpected interface conversion when batchSize=1 

### ISSUE THREAD

**Issue by Azhng** [cockroachdb/cockroach#46646] opened 2020-03-26 20:26 UTC
```
    --- FAIL: TestLogic/local (0.45s)
        --- FAIL: TestLogic/local/window (0.45s)
            logic.go:1171: overriding vectorize mode to , setting batch size to 1
            logic.go:2098:

                testdata/logic_test/window:2031: SELECT product_name, price, nth_value(product_name, 2) OVER w AS second FROM products WHERE price = 200 OR price = 700 WINDOW w as (PARTITION BY price ORDER BY product_name RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING) ORDER BY price, product_name
                expected success, but found
                (XX000) internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []bool
                error.go:92: in func1()
                DETAIL: stack trace:
                github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:92: func1()
                runtime/panic.go:522: gopanic()
                runtime/iface.go:248: panicdottypeE()
                github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:188: Bool()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/proj_const_right_ops.eg.go:1770: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:125: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:36: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/const.eg.go:120: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/case.go:136: func1()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:204: PerformOperation()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/case.go:131: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:125: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/bool_vec_to_sel.go:36: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/simple_project.go:120: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/const.eg.go:322: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/simple_project.go:120: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:41: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:149: next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:140: nextAdapter()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95: CatchVectorizedRuntimeError()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:177: Next()
                github.com/cockroachdb/cockroach/pkg/sql/rowexec/windower.go:278: accumulateRows()
                github.com/cockroachdb/cockroach/pkg/sql/rowexec/windower.go:230: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:111: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:41: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:135: spool()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/sort.go:265: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:215: func1()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95: CatchVectorizedRuntimeError()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/disk_spiller.go:213: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/invariants_checker.go:41: Next()
                github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:149: next()

                NOTE: internal errors may have more details in logs. Use -show-logs.
            logic.go:1852:
                 pq: internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []bool
```
parent issue: #46185

**Comment by yuzefovich** [comment] 2020-03-26 20:37
Which sha are you running on? I wonder whether it is the same issue that #46543 fixed.

**Comment by Azhng** [comment] 2020-03-26 20:40
master sha is: `03b0c5910b5594641f9d958a137a9126c0cb8045` 

This is a different issue I think

**Comment by yuzefovich** [comment] 2020-03-26 20:45
I'll take a look if you don't mind.

**Comment by Azhng** [comment] 2020-03-26 20:46
reassigned

**Comment by yuzefovich** [comment] 2020-03-26 22:52
This is a concerning issue, and the root cause is IMO, again, `simpleProjectOp` with its `projectingBatch` lens that does not actually copy the data into a separate output batch from the input batch.

Here is the plan
```
└ *rowexec.windower
  └ *colexec.Materializer
    └ *colexec.simpleProjectOp
      └ *colexec.constInt64Op
        └ *colexec.simpleProjectOp
          └ *colexec.boolVecToSelOp
            └ *colexec.selBoolOp
              └ *colexec.caseOp
                ├ *colexec.bufferOp
                │ └ *colexec.CancelChecker
                │   └ *colexec.colBatchScan
                ├ *colexec.constBoolOp
                │ └ *colexec.boolVecToSelOp
                │   └ *colexec.selBoolOp
                │     └ *colexec.projEQDecimalDecimalConstOp
                │       └ *colexec.bufferOp
                ├ *colexec.constBoolOp
                │ └ *colexec.boolVecToSelOp
                │   └ *colexec.selBoolOp
                │     └ *colexec.projEQDecimalDecimalConstOp
                │       └ *colexec.bufferOp
                └ *colexec.constBoolOp
                  └ *colexec.bufferOp
```
and description of what is happening in this issue:
1. `colBatchScan` returns a batch with 11 columns
2. `caseOp` appends 12th column for its output type of `Bool` type (by the way, we have `caseOp` because the query contains `WHERE price = 200 OR price = 700` which is converted into `CASE WHEN price = 200 THEN true WHEN price = 700 THEN true ELSE false` with `selBoopOp` on top of the output); the batch has 12 columns now
3. on the first batch in `caseOp` we get a tuple in which `price = 200`
3.1. first WHEN arm appends 13th column of `Bool` type (to project equality of 3rd column "price" with a constant "200); the batch has 13 columns now
3.2 second WHEN arm gets a zero-length batch as an input because all tuples have been matched; still 13 columns in the batch now
3.3. ELSE arm also gets a zero-length batch for the same reason, still 13 columns
4. bottom `simpleProjectOp` returns only the first 11 columns from the batch (initially), so it has a "projectingBatch "lens as `[0, 1, ..., 10]`
5. `constInt64Op` appends a new `Int64` column; the batch now has 14 columns and the lens of the bottom projection is `[0, 1, ..., 10, 13]`
6. upper `simpleProjectOp` has lens as `[2, 3, 11]` which translates into `[2, 3, 13]` on the "internal" non-projecting batch

Ok, we have gone through one iteration. On one of the consequent iterations, when the first WHEN arm does not match all of the tuples, the second WHEN arm will actually get to run. It expects a `Bool` column at index 13 in the "internal" batch. However, there is already present column of `Int64` type, so our `Allocator.MaybeAddColumn` method does nothing, the column of incorrect type remains at the index, and we panic because of type mismatch.

I see three ways to solve this particular issue:
1. remove the short-circuiting logic that we have put in place, and run all operators that append columns even on zero-length batches. We have had problems with this approach previously, so I don't really like this solution.
2. change `Allocator.MaybeAddColumn` method to replace the column and allocate a new one if there is already a column of the wrong type. This will - hopefully - resolve all problems in this area; however, the cost is that we might end up in a situation when we're constantly replacing the vectors by allocating new ones in the same position. I believe in the example above, on every batch from `colBatchScan` we will have to allocate a new column twice when the second WHEN arms gets non-zero length batch, so the performance will suffer. I don't have a good feeling about how likely such scenario will actually be occurring, but having `CASE`, `AND`, `OR` operations in the query seems like prerequisites. Yet the actual input data will matter a lot as well (for example, if the very first batch has such data that all WHEN arms and ELSE arm of `caseOp` end up not short-circuiting, then we're good). Personally, I'm leaning towards this solution for this release.
3. actually solve the root of the problem by making `simpleProjectOp` support its own internal batch and removing `projectingBatch` length entirely. I think this is the right solution long-term, but the performance implications are unclear, and I feel like it's too late to do this in the current release.

cc @jordanlewis @asubiotto thoughts?

**Comment by jordanlewis** [comment] 2020-03-26 23:36
I think the root of the problem here isn't really `simpleProjectOp` - it's in fact the "lazy" way in which we populate columns in batches.

The thing that I had originally intended (but never built, obviously) was a column allocator that laid out all of the columns required by each operator in some kind of map as the operators are being created. The whole thing where operators create columns on demand is just so unfortunate. I doubt we can fix this for the release though.

What about the idea of disabling `case`?

I don't like the idea of making `simpleProjectOp` expensive the way you're talking about. It should really remain a lens. I do think that we can solve our general problems by allocating columns in batches up front. This is also just a cleaner architecture overall - you never want an operator to have to do *anything* dynamic. Its operating mode should all be pre-ordained by planning and operator setup.

**Comment by yuzefovich** [comment] 2020-03-27 00:51
Hm, I agree with you that having a centralized allocator (that not only performs memory accounting but also full batch management) would be great, but it is definitely out of scope for this release. I think we should work on this idea as a part of the "dynamic batch size" initiative for 20.2.

We still need to fix the issue for this release though. I think simply disabling `case` might be insufficient (we would need to disable `and` and `or` operators and possibly others): I can't think of an example OTOH outside of these three operators, but it seems possible to me to have a plan with a chain of operators like `proj op 1 <- simpleProjectOp <- proj op 2 <- ... ` in which initially `proj op 2` receives zero-length batch and short-circuits but `proj op 1` actually appends the column which messes up the expected indices. Maybe it is not possible, I'm not sure.

**Comment by jordanlewis** [comment] 2020-03-27 01:12
What about the idea of somehow forcing every operator to allocate its columns up front? I know it's tricky with some of them... but maybe it's possible? What if we had `Init`... return a batch!?! as an example. And then operators would be responsible for widening their batches in Init. I actually like that... does it make any sense?

**Comment by yuzefovich** [comment] 2020-03-27 01:22
This could work, but I'm worried the change will be the source of even more bugs.

I do see the beauty of `Init` method in that it must be called on every operator. We could change it to
```
Init() coldata.Batch
```
which would return the output batch of an `Operator`. However, we would need to enforce that every operator uses that particular batch for its output, but we probably already have that. I guess it is worth exploring further.

**Comment by asubiotto** [comment] 2020-03-27 09:53
This is very unfortunate. I think if we were to change `Init`, we have the problem discussed in slack that we would probably also need to change the `Next` interface to not return a batch, otherwise the semantics become confusing (as long as I'm not missing something). I think there might be another possibility:
1. Have `OneInputNode` and `TwoInputNode` implement `Next` and all operators must embed `OneInputNode` (I think they already do). The `Next` method in `OneInputNode` would enforce a constant schema. In the case operator, it will append all columns to the input batch if they don't exist yet. Same with the const operator, it will append an int column before returning the batch to the operator. This will hopefully start to get rid of our dynamic schema problem.
2. Restrict `MaybeAddColumn` to only be used within the `OneInputNode`.

**Comment by yuzefovich** [comment] 2020-03-27 14:31
Yes, the semantics will be confusing if we change only `Init` method, that is why on slack I'm calling it a "best effort" attempt to return the batch that will be the output, and on its own such change would not be sufficient to resolve problems like this issue demonstrates.

Hm, in regards to `OneInputNode`- at least currently - not all operators embed `OneInputNode` or `TwoInputNode` in itself. That probably could be fixed, but I don't see how embedding is gonna help us, could you spell it out how it would "enforce the constant schema"? I think this idea is essentially the same as Jordan's idea on slack of "threading in all of the extra projection types back into the most recent batch owner and let the allocator manage that".

**Comment by asubiotto** [comment] 2020-03-27 14:45
I guess I was using `OneInputNode` because I assumed it or it's equivalent is embedded by all operators. I'm 100% certain what Jordan's idea is but it seems like if we have a case operator, we would need some way to pass expected types all the way up to whoever is first allocating the batch?

What I'm proposing is that when we create a new operator that currently calls `MaybeAddColumn`. It will take a look at its input schema and at that stage determine that it needs n more columns. For example, the case operator knows its input types + that it needs three boolean columns. The case operator will then pass this information to `OneInputNode`. We'll change `OneInputNode` to wrap its `input` field with a wrapper struct that intercepts the `Next` method and has the information of this expected, constant schema.

Now, whenever the case operator calls `Next`, it can be 100% sure that there is no need to call `MaybeAddColumn`. The wrapper struct will call `Next` on the case's true input, then add any columns that need to be added. Since we'll remove `MaybeAddColumn` from all operators, there won't be any issues with short-circuiting logic because those columns will already have been added by the wrapper. Note this typing issue also won't be a problem (because it's essentially due to missing columns).This will allow us to also remove the custom logic we have in the projection operator and always assume that an input batch is of a given schema and a projection mapping can be left unchanged.

**Closed** 2020-04-03 15:36 UTC
