### ISSUE TITLE
cli/sql: support COPY FROM STDIN in the sql shell

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16392] opened 2017-06-07 20:57 UTC
```
root@:26257/test> create table z(a int);
CREATE TABLE
root@:26257/test> copy z(a) from stdin;
pq: unknown response for simple query: 'G'
root@:26257 ?>
```

Jira issue: CRDB-6066

Epic CRDB-14477

**Comment by jordanlewis** [comment] 2017-06-07 21:06
cc @knz @mjibson as people of interest in the `cockroach sql` and `COPY FROM` arenas respectively.

**Comment by mjibson** [comment] 2017-06-07 21:09
I'm unlikely to have time to work on this or the other COPY bug for a while.

**Comment by knz** [comment] 2017-06-07 23:02
We don't support this. This is not a bug :)

We recommend for now that people who want to use COPY use pg's CLI client, which works with CockroachDB.

**Comment by cuongdo** [comment] 2017-08-30 19:54
"Claiming" this task, as it will be Pete Vilter's starter project.

**Comment by mjibson** [comment] 2017-08-30 19:58
I've started some prerequisite work for this feature. Talk to me when work begins on this.

**Comment by sibblegp** [comment] 2017-09-06 17:35
If your shell doesn't support copy, I would highly suggest you update your documentation:

> cockroach sql --database=[database name] < statements.sql

> The .sql files generated by pg_dump provide better performance because they use the COPY statement instead of bulk INSERT statements.

https://www.cockroachlabs.com/docs/stable/import-data.html#import-from-generic-sql-dump

**Comment by mjibson** [comment] 2017-09-06 17:38
I'm confused. That page you linked has a large section about how to produce and import COPY dumps. What are we missing?

**Comment by sploiselle** [comment] 2018-10-24 15:52
@mjibson Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by knz** [comment] 2018-10-24 16:45
"""
title: importing data using the PostgreSQL COPY protocol

Currently the built-in SQL shell provided with CockroachDB (`cockroach sql` / `cockroach demo`) does not support importing data using the COPY statement. Users can use the `psql` client command provided with PostgreSQL to load this data into CockroachDB instead. For details see https://www.cockroachlabs.com/docs/stable/import-data.html#import-from-generic-sql-dump
"""

**Comment by lanzao** [comment] 2018-10-29 08:46
I wonder why cockroachDB shell does not support COPY FROM STDIN? Will follow-up support？

**Comment by knz** [comment] 2018-10-29 12:10
> why

because it's 1) complicated and 2) slow. All the data goes through a single connection. CockroachDB provides an IMPORT PGDUMP statement which is much faster and can operate in parallel.

> will follow-up support

maybe (probably) although it's not planned yet.

**Comment by otan** [comment] 2022-04-07 00:53
This is incredibly tricky with what we have today. I basically see two ways of making this work, both are gnarly.

The problem here our CLI currently using `lib/pq` (but `jackc/pgx` is an issue too), and the library APIs do not play well with a COPY command being passed into `Query`.

Let's start by looking at PG:
* In PG, queries are passed in: https://github.com/postgres/postgres/blob/0d5c387573be5c40bf18b7b8983f406637dff42f/src/bin/psql/common.c#L1487
* Queries can have multiple results (if they have multiple statements). If we detect during a statement that we have a COPY, we go into the special COPY case: https://github.com/postgres/postgres/blob/0d5c387573be5c40bf18b7b8983f406637dff42f/src/bin/psql/common.c#L936-L941
* And basically results are copied one a time.

The key here is `libpq` (what PG uses) allows inspection of each low level pgwire response individually, but we don't get that level of fine grainness in `lib/pq` or `jackc/pgx`:
* In `lib/pq`, we run into `pq: unknown response for simple query: 'G'`. This is because the result type, `G`, is not supported. Instead, [`lib/pq` recommends using the `CopyIn` API](https://pkg.go.dev/github.com/lib/pq#hdr-Bulk_imports)
* In `jackc/pgx`, `COPY ... FROM STDIN` hangs if passing into `Exec`, or errors with `CopyFrom not supported in extended protocol mode` [`CopyFrom` is the correct API to handle it.](https://pkg.go.dev/github.com/jackc/pgx/v4#hdr-Copy_Protocol).

As far as I can tell, we have two options here:
* Change `clisqlshell` to actually parse statements, then use the appropriate `CopyIn` command (assuming lib/pq). Unfortunately, the `CopyIn`/`CopyFrom` interfaces are not rich enough to take into account the extra options provided by `COPY`, such as `DELIMITER` or `ESCAPE`. We could look at extending the libraries to do so. Importing `parser` also introduces a whole heap of dependencies on `clisqlshell`, which was intended to be lightweight (tl;dr here is parser imports tree which imports the whole world, and that's it's own discussion...)
* Change `lib/pq` to handle `'G'` to return a special status in `database/sql/driver.Rows`' `Tag` interface, which symbolises one should start copying in https://github.com/lib/pq/blob/8446d16b8935fdf2b5c0fe333538ac395e3e1e4b/conn.go#L745. Then read some input from STDIN and assume it's for Copy. Unknown how this affects files loaded by `-f` or piped in by stdin.

I guess we're inclined to do the latter, but it adds another blocker to moving to `jackc/pgx`. The former is even messier.

At this point I'd welcome a second opininon.

**Comment by knz** [comment] 2022-04-07 11:27
Can we do it the other way, the way that `psql` does it: require that the CLI user type `\copy` and then handle that by using the Copy API in the driver?

**Comment by otan** [comment] 2022-04-07 12:27
`psql` does not require using `\copy` (but it is an option):

```
 ⚙ otan  ~/go/src/github.com/cockroachdb/cockroach   scanner ●  psql
psql (14.2)
Type "help" for help.

otan=# copy t from stdin;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 1    2
>> ERROR:  duplicate key value violates unique constraint "t_pkey"
DETAIL:  Key (a)=(1) already exists.
CONTEXT:  COPY t, line 1
```

**Comment by bdarnell** [comment] 2022-04-07 14:31
Is there not a third option to modify pgx to handle the `G` message type? Or are there other interface differences that make that impossible? 

`pgx` also has a sibling library `pgconn` that exposes lower-level details. I haven't looked into the differences between pgconn and pgx to see how feasible it would be to use pgconn in the sql shell, but a sql shell (as opposed to an application) seems like the kind of place that would potentially benefit from the lower level interface in other ways too.

**Comment by rafiss** [comment] 2022-04-07 16:28
whenever we do move away from lib/pq, I also think using `pgconn` and `pgproto3`. would be a reasonable idea. we use it to implement [sqlproxy](https://github.com/cockroachdb/cockroach/tree/master/pkg/ccl/sqlproxyccl) as well as many internal tests.

**Comment by otan** [comment] 2022-04-07 20:41
> pgx also has a sibling library pgconn that exposes lower-level details. 

ah yeah `pgconn` makes more sense to use, TIL.

> Is there not a third option to modify pgx to handle the G message type? 

`G` is pretty special, needs a bit of specialness. It basically changes how the next bit of content should be processed. might not be too bad, might be. i'll give it a go maybe.

> recognize when receiving an error from the driver "type G not supported" when the user types the COPY statement, and printing to the user "maybe use \copy instead?"

i think that's a good stop gap if we don't manage to do anything else.

**Comment by otan** [comment] 2022-04-08 01:54
it's unfortunately very hard to salvage `lib/pq`:
* making it understand `G` and then subsequent commands as copy in is very confusing in terms of it's state
* making the `\copy` command call `CopyIn` has a few gotchas:
  * need to break the abstractions to be able to propagate a raw `CopyData` through without using `Exec`: https://github.com/lib/pq/compare/master...otan-cockroach:copy_in_stuff?expand=1
  * `COPY` must be inside a txn in the `lib/pq` driver. We can make the cli spin up a new `txn` to counteract this, but it's gnarly if we're already inside a txn.
  * generally messy.

the txn deal may be a killer, but in any case here's a sample PR showing it working: https://github.com/cockroachdb/cockroach/pull/79629/

```
root@127.0.0.1:26257/defaultdb> create table t (a int, b int);
ERROR: relation "defaultdb.public.t" already exists
SQLSTATE: 42P07
root@127.0.0.1:26257/defaultdb> \copy t from stdin csv;
>> 1,2
>> 3,4
>> \.
COPY 2
root@127.0.0.1:26257/defaultdb> select * from t;
  a | b
----+----
  1 | 2
  3 | 4
(2 rows)


Time: 3ms total (execution 2ms / network 0ms)
```

missing a lot of CLI changes (hitting tabs should actually make tabs, EOF handling), but the base is there. 

i would say we should switch to `pgconn`, but IIUC kerberos is not implemented on it and that's a blocker.

**Comment by otan** [comment] 2022-04-08 06:40
i'm actually at a state where https://github.com/cockroachdb/cockroach/pull/79629 needs unit tests and is mergable; heck i'd even say backportable to v22.1 if we consider it high enough priority.

**Closed** 2022-04-13 22:17 UTC
Labels: C-enhancement, docs-done, docs-known-limitation, T-sql-experience

**Comment by mari-crl** [comment] 2022-05-13 20:57
:information_source: Hello! I am a human and not at all a robot! Look at my very human username! :robot: :notes:
:thinking: Although I tried very hard to figure out what to do with this issue, more powerful human brains will need to help me. (specifically: Both Github and Jira issues were modified after exalate problems) :confounded:
:arrows_counterclockwise: **Please visit this issue's mirror at [CRDB-6066](https://cockroachlabs.atlassian.net/browse/CRDB-6066) and try to sync the two sides up manually.** :star2:
:white_check_mark: When you're finished, comment saying as much asn a member of Developer Infrastructure will be along to finish linking. :link:
:no_entry_sign: Note that until this is done, **this issue is not and will not be synced to Jira with Exalate**. :no_entry_sign:
:sweat_smile: Feeling lost? Don't worry about it! A member of @cockroachdb/exalate-22-cleanup-team will be along shortly to help! :+1:
:construction_worker: Developer Infrastructure members: when ready, open Exalate from the right-hand menu of the mirror issue in Jira, then choose Connect and enter this issue's URN: `cockroachdb/cockroach-16392`. Either way, delete this comment when you're done. :key:
:pray: Thank you for your compliance, my fellow humans! :robot: :wave:
