### ISSUE TITLE
colexec: inconsistent handling of context cancellation

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51647] opened 2020-07-21 16:32 UTC
Some tests occasionally fail due to an unexpected "query canceled" message in the vectorized engine. We suspect that the cause is context management - cancelling a context within a flow might be cancelling the outer query by accident.

See #51215, which might be related.

**Comment by yuzefovich** [comment] 2020-07-22 05:22
I spent a bunch of time looking into this issue today, and here is what I see so far. The plan (slightly modified version of what we get for the first test case in `TestUncertaintyErrorIsReturned`) for the context. I also was working on top of #51518 which changes the hash router to propagate the error to all outputs.

![Screen Shot 2020-07-21 at 9 51 27 PM](https://user-images.githubusercontent.com/5135385/88135605-5636f380-cb9c-11ea-950b-00c91170b526.png)

The test injects RWUI error on node 1, so both `TableReader/0` and `TableReader/2` return that error when scanned by `cFetcher`. The error is marked as `StorageError`, so it is propagated throughout the vectorized engine unchanged. The hash routers on both table readers catch it, and both routers send it out on both of its inputs.

The errors are then caught by one input goroutine for each of 4 parallel unordered synchronizers that are inputs to the hash joiners. Next, each goroutine sends it on `errCh` to its unordered synchronizer which, once received the error, cancels its input goroutines and repanics with the error.

Now, we're at hash joiner level, and all of the above was happening while each of the hash joiners requested the first batch from the right input, but it ended up in a panic, so the errors by-pass the hash joiners and are caught by the output of `HashJoiner/5` on node 2 and by right input to unordered synchronizer sitting on `No-op/6` on node 1.

Then we seem to have a race between two goroutines that are inputs to that unordered synchronizer on `No-op/6`. If the "local" right goroutine wins, then we have the following:
1. right input goroutine catches the error, then sends it to the unordered synchronizer and exits itself
2. the unordered synchronizer receives the RWUI error from `errCh`, cancels both of its inputs, and propagates the error further
3. a) left input goroutine, which is an `Inbox`, observes two things - `readerCtx` cancellation (which prompts `Inbox.RunWithStream` method to finish with "context cancelled" error) and "context cancelled" error is `Recv`'ed from the stream by `Next` goroutine. I don't really understand why the latter happens.
  b) RWUI error is caught by the root materializer which then transitions into draining state with that error and, once draining is complete (which actually seems to not properly drain all `MetadataSource` because `Outbox` on `HashJoiner/5` encounters an EOF error when attempting to send the metadata - the cause is the same stream "context cancelled" error as in 3. a)), cancels the flow.

What's unclear to me is why does the stream between `HashJoiner/5` and unordered sync on `No-op/6` encounters "context cancelled" error when both `Send`ing and `Recv`ing before the materializer cancels the flow (at least that's what it looks like from the logs). It's also somewhat mysterious to me whether the context that materializer cancels is related to `stream.Context()` that is part of gRPC implementation.

**Comment by yuzefovich** [comment] 2020-07-22 17:25
I think I understand what's going on now. Based on [this](https://github.com/cockroachdb/cockroach/blob/708df8bca077276b9161d68486beae26e77e4377/pkg/sql/colflow/colrpc/inbox.go#L220-L222) comment:
```
	// Now wait for one of the events described in the method comment. If a
	// cancellation is encountered, nothing special must be done to cancel the
	// reader goroutine as returning from the handler will close the stream.
```
canceling `readerCtx` in step 3. a) above causes the stream to become unusable (basically, `readerCtx` cancellation causes "context canceled" error on `Recv` from the stream) since we're exiting from `RunWithStream` method upon `readerCtx` cancellation. Now I think that #51772 might fix things.

The remaining question for me is what should we be doing with errors other than "query canceled" and "context canceled" when the parallel unordered synchronizer performs internal cancellation? Maybe the correct thing to do is actually ignore all errors (the synchronizer would get into "canceled" state)? Should we be accumulating other errors to be returned as metadata?

Another thing that is still unclear to me is why we would ever return a different error from RWUI error with which the materializer moves into draining.

**Comment by yuzefovich** [comment] 2020-07-22 18:19
I see why the query could get a different error in the result. The materializer receives RWUI error and moves into draining state with it, that RWUI error is then set on `commandResult` and from now on materializer calls `DrainHelper()`. That method calls `DrainMeta` on the unordered synchronizer which at that point has a "stream" context canceled error in `errCh`, so that error is returned as metadata to `DistSQLReceiver`. If the priority of that error is higher than of RWUI error, then the latter is overwritten by the former.

If we add the following diff:
```
diff --git a/pkg/sql/colflow/colrpc/inbox.go b/pkg/sql/colflow/colrpc/inbox.go
index 0cd45f7e99..2295baed37 100644
--- a/pkg/sql/colflow/colrpc/inbox.go
+++ b/pkg/sql/colflow/colrpc/inbox.go
@@ -14,6 +14,7 @@ import (
        "context"
        "fmt"
        "io"
+       "strings"
 
        "github.com/apache/arrow/go/arrow/array"
        "github.com/cockroachdb/cockroach/pkg/col/coldata"
@@ -24,6 +25,7 @@ import (
        "github.com/cockroachdb/cockroach/pkg/sql/execinfrapb"
        "github.com/cockroachdb/cockroach/pkg/sql/types"
        "github.com/cockroachdb/cockroach/pkg/util/log"
+       "github.com/cockroachdb/errors"
        "github.com/cockroachdb/logtags"
 )
 
@@ -272,6 +274,15 @@ func (i *Inbox) Next(ctx context.Context) coldata.Batch {
                        // goroutine. Regardless of the cause we want to propagate such
                        // error in all cases so that the caller could decide on how to
                        // handle it.
+                       log.VEventf(ctx, 1, "Inbox Recv error: %v", err)
+                       if strings.Contains(err.Error(), context.Canceled.Error()) {
+                               // TODO(yuzefovich): we substitute the stream's context
+                               // cancellation error with a fake error. For some reason, the
+                               // whole query will get this error as the result although RWUI
+                               // error of TestUncertaintyErrorIsReturned is propagated to the
+                               // unordered synchronizer first.
+                               err = errors.AssertionFailedf("blah")
+                       }
                        i.errCh <- err
                        colexecerror.ExpectedError(err)
```
then the assertion failure will always overwrite RWUI error, so we'll always get an unexpected error in `TestUncertaintyErrorIsReturned`.

So the questions remain:
1. what we should be doing with errors from inputs in unordered synchronizer after an internal cancellation was performed? I feel like we might want to swallow all errors at that point, not only "query canceled" or "context canceled"
2. how do we ensure that we can drain the metadata from remote nodes if the reader context of inboxes is getting canceled which deems the streams unusable (point in 3. b) above)? It seems like we need to rethink the way we shutdown the inboxes and streams.

**Comment by yuzefovich** [comment] 2020-07-22 19:52
During my investigation I found a bug with cancellation of the outboxes that has been present since forever, and I included the fix as the first commit in #51772.

**Comment by jordanlewis** [comment] 2020-07-28 16:26
@asubiotto, we need your input on this issue when you get back. Especially point 2 - is it okay if we miss some metadata that's produced after a limit is satisfied?

**Comment by asubiotto** [comment] 2020-08-03 12:45
> is it okay if we miss some metadata that's produced after a limit is satisfied?

Yes, this is the same principle as swallowing RWUI errors if we've already returned the necessary results.

> what we should be doing with errors from inputs in unordered synchronizer after an internal cancellation was performed? I feel like we might want to swallow all errors at that point, not only "query canceled" or "context canceled.

I think that's fine. We already do this in some cases (check the case where `errCh` is full when another input wants to write the error).

> how do we ensure that we can drain the metadata from remote nodes if the reader context of inboxes is getting canceled which deems the streams unusable (point in 3. b) above)? It seems like we need to rethink the way we shutdown the inboxes and streams.

Good point. When encountering an error, we usually want to drain the inputs (based on a reading of calling `MoveToDraining` with an error). I think the context cancellation in the unordered synchronizer is a remnant of when no draining occurred. The proper behavior for this case seems to me like it should be `input goroutine A encounters error -> main goroutine returns that error`, then the upstream component that receives this error should then call `DrainMeta` on the main goroutine, which would cause a coordinated shutdown of the input goroutines.

**Comment by yuzefovich** [comment] 2020-08-03 14:47
After looking into #52057 a little bit more, I started wondering whether we actually need to be swallowing "context canceled" (both flow's context and stream's context) errors regardless whether the cancellation is internal from the perspective of the unordered synchronizer. Consider a chain with two parallel unordered synchronizers: `sync1 -> sync2` (`sync1` is the input). Suppose `sync2` performs an internal cancellation which cancels the context on which `sync1` is listening on. From `sync1`'s perspective, it wasn't an internal cancellation, so it propagates `ctx.Err()` further via a panic, which is caught by `sync2`. So the question is shouldn't we swallow such error in `sync2`? I think the same question is relevant when we have `some operator -> sync2` and that "some operator" cancels the context.

Another question is that in such scenario our `CatchVectorizedRuntimeError` might annotate the error, and I'm not sure whether current `errors.Is` check will be able to see "through" the annotations that it was a "context canceled" error (I think the check should work though, just putting this thought out).

**Comment by asubiotto** [comment] 2020-08-03 15:09
What I'm suggesting is that we get rid of any internal context cancellation during a graceful shutdown because the synchronizer should be drained, which will have the same effect of cleaning up the input goroutines. This will allow us to get rid of any swallowing behavior. During a hard shutdown (an actual context cancellation), a context cancellation by the materializer will clean everything up and we probably don't care about swallowing anything.

**Comment by yuzefovich** [comment] 2020-08-03 16:37
Your suggestion sounds good to me.

**Closed** 2020-08-17 14:47 UTC
Labels: C-bug
