### ISSUE TITLE
Make host flag into advertise_url and listen_url

### ISSUE THREAD

**Issue by aaronjheng** [cockroachdb/cockroach#6845] opened 2016-05-22 10:52 UTC
I could not setup a basic cluster with 3 nodes in my local docker. I found out that the "--host" flag would set the advertiser url and listen url. 
When I set "--host" to my computer's ip, I got an error like below.
> Error: cockroach server exited with error: listen tcp 192.168.0.100:26257: bind: cannot assign requested address
Failed running "start"

So, I think it's better there are `advertise_url` and `listen_url` to configure the advertise url and listen bind url. just like etcd do.

**Comment by tamird** [comment] 2016-05-22 14:17
Dupe of #1008

**Closed by tamird** 2016-05-22 14:17 UTC
