### ISSUE TITLE
sql: SCRUB DATABASE system produces errors

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36556] opened 2019-04-05 04:50 UTC
```
EXPERIMENTAL SCRUB DATABASE SYSTEM
```

```
scrub_index.go:102: could not create query plan | string
github.com/cockroachdb/cockroach/pkg/sql/scrub_index.go:102: in Start()
github.com/cockroachdb/cockroach/pkg/sql/scrub.go:128: in Next()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:178: in Next()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174: in Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:814: in Run()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:627: in Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252: in Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:840: in PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1121: in execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957: in dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459: in execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101: in execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1221: in execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1157: in run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:437: in ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:581: in func1()
E190405 04:49:23.116054 281 sql/sqltelemetry/report.go:39  encountered internal error:
sql/sqlbase/errors.go:118 in NewUndefinedColumnError(): (XX000) internal error: could not create query plan: column "expiresat" does not exist
```

Jira issue: CRDB-4493

**Comment by jordanlewis** [comment] 2019-04-05 14:19
@lucy-zhang could you PTAL?

**Comment by lucy-zhang** [comment] 2019-04-05 14:57
We shouldn't allow running SCRUB on the `system` database. Even aside from this panic, caused by not being able to query most of the columns in `system.web_sessions`, there are a lot of spurious errors about index decoding failures.

**Comment by postamar** [comment] 2022-03-08 20:09
Closing, nowadays we get
```
demo@127.0.0.1:26257/defaultdb> EXPERIMENTAL SCRUB DATABASE SYSTEM;
ERROR: scrub-index: index "jobs_run_stats_idx" is a partial index that does not contain all the rows needed to execute this query
SQLSTATE: 42809
demo@127.0.0.1:26257/defaultdb> 
```

**Closed by postamar** 2022-03-08 20:09 UTC
Labels: C-bug, A-sql-scrub, T-sql-schema
