### ISSUE TITLE
sql: allow StrVals to resolve to arrays

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22384] opened 2018-02-05 18:35 UTC
It would be nice if we could resolve StrVals to arrays, so that expressions like the following would work without an explicit cast:
```
SELECT '{"a":"b"}'#>'{a}'
```
but from a brief investigation this seems to cause a handful of problems that I would need to look into, so I'm deeming this low-pri for the time being.

**Comment by jordanlewis** [comment] 2019-05-07 14:33
Duplicate of #23299.

(that one came later, but has more details and is linked to stuff)

**Closed by jordanlewis** 2019-05-07 14:33 UTC
Labels: A-sql-semantics, C-enhancement
