### ISSUE TITLE
sql: mixed type where condition doesn't constrain index

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#20046] opened 2017-11-14 17:57 UTC
Uncovered from #19932, consider the following two queries:

```
root@:26257/debraj> explain SELECT customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp FROM config_versions WHERE updatetimestamp >= 1510472101::TIMESTAMP ORDER BY updatetimestamp DESC LIMIT 2147483647;
+-------+-------+-------+--------------------------------------------+
| Level | Type  | Field |                Description                 |
+-------+-------+-------+--------------------------------------------+
|     0 | limit |       |                                            |
|     1 | scan  |       |                                            |
|     1 |       | table | config_versions@config_versions_by_version |
|     1 |       | spans | ALL                                        |
+-------+-------+-------+--------------------------------------------+
(4 rows)

root@:26257/debraj> explain  SELECT customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp FROM config_versions WHERE updatetimestamp >= '2017-11-12 07:35:01+00:00' ORDER BY updatetimestamp DESC LIMIT 2147483647;
+-------+-------+-------+--------------------------------------------+
| Level | Type  | Field |                Description                 |
+-------+-------+-------+--------------------------------------------+
|     0 | limit |       |                                            |
|     1 | scan  |       |                                            |
|     1 |       | table | config_versions@config_versions_by_version |
|     1 |       | spans | -/1922-02-19T16:24:58.000000999Z           |
|     1 |       | limit |                                 2147483647 |
+-------+-------+-------+--------------------------------------------+
(5 rows)
```

The explicit timestamp cast from the given integer constant prevents the planner from using the information. This also happens if we take the first form of the query and add an explicit cast:

```
root@:26257/debraj> explain  SELECT customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp FROM config_versions WHERE updatetimestamp >= '2017-11-12 07:35:01+00:00'::timestamp ORDER BY updatetimestamp DESC LIMIT 2147483647;
+-------+-------+-------+--------------------------------------------+
| Level | Type  | Field |                Description                 |
+-------+-------+-------+--------------------------------------------+
|     0 | limit |       |                                            |
|     1 | scan  |       |                                            |
|     1 |       | table | config_versions@config_versions_by_version |
|     1 |       | spans | ALL                                        |
+-------+-------+-------+--------------------------------------------+
(4 rows)
```
In both cases we should be able to evaluate the given constant, using whatever special cased codepath we use to wrap the given bare string and use it to construct our more precise KV scans.

Assigning @jordanlewis for evaluation and triage. The title could probably also use some cleanup but I'm struggling to formulate a better one.

**Comment by jordanlewis** [comment] 2017-11-14 18:00
Nice find

**Comment by jordanlewis** [comment] 2017-11-14 18:20
Do you have the `SHOW CREATE TABLE` for that table?

**Comment by arjunravinarayan** [comment] 2017-11-14 18:24
It's in the linked issue. Here's my cleaned up create statement:
```
CREATE TABLE config_versions (                                                                                                          customerid INTEGER NOT NULL,                                                                                                                                objecttype INTEGER NOT NULL,                                                                                                                                objectid INT NOT NULL,                                                                                                                                      propertyname STRING NOT NULL,                                                                                                                               timeinstant INT NOT NULL,                                                                                                                                   updatetimestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),                                                                                            CONSTRAINT "primary" PRIMARY KEY (customerid ASC, objecttype ASC, objectid ASC, propertyname ASC, timeinstant ASC, updatetimestamp DESC),                   INDEX config_versions_by_version (updatetimestamp DESC),                                                                                                    FAMILY "primary" (customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp));
```

**Comment by jordanlewis** [comment] 2017-11-14 18:28
Thanks.

If you change the cast to `::TIMESTAMPTZ` (the table's column type is in fact timestamp with time zone and not timestamp) the span creation appears to work successfully.

Nonetheless this is still clearly a bug.

**Comment by jordanlewis** [comment] 2017-11-14 18:56
The bug is that index selection doesn't consider a `TIMESTAMP` to be comparable to a `TIMESTAMPTZ`, and therefore discards the constraint comparing the `TIMESTAMPTZ` column to the `TIMESTAMP` value as unusable for the purposes of constraining the index.

This is apparently by design, at least somewhat:

https://github.com/cockroachdb/cockroach/blob/5769b3bb9a91380fdc504e080fee9e1e76bca291/pkg/sql/index_selection.go#L735-L749

Does @nvanbenschoten remember any more details about why mixed type comparisons can't be used for index selection? See #4313.

**Comment by nvanbenschoten** [comment] 2017-11-16 20:06
Mixed type comparisons can't be used for index selection because the encoded values may not compare the same way as the `Datum` values. We take great care to enforce the relationship that `datum.Compare(a, b)` provides the same semantics as `bytes.Compare(encode(a), encode(b))` when `a` and `b` are the same types (which is the reason why index selection constraints work at all).  However, when `a` and `b` are different types, we have no way to be sure this relationship holds.

That all said, for `Datums` types that share the same encoding and mutually exhibit this relationship (as is the case for `TIMESTAMP` and `TIMESTAMPTZ`), we shouldn't need this restriction and should be able to perform better index selection.

**Comment by jordanlewis** [comment] 2017-12-11 02:04
@RaduBerinde I'm not actively working on this, so if you have a plan for how to fix it feel free to reassign!

**Comment by nvanbenschoten** [comment] 2017-12-11 13:43
To address this, I think we'll want to introduce something like the notion of "encoding equivalency classes". Any types within the same class will need to:
1. share the same ordered and unordered encodings.
2. implement Datum comparison routines (`datum.Compare(a, b)` and `datum.Compare(b, a)`).
3. ensure that these two functions agree in all cases (see `TestDatumOrdering` and `TestEncDatumCompare`).

Once we have this formalized, we can loosen the constraint on mixed type comparisons to only mixed encoding equivalency class comparisons.

**Comment by RaduBerinde** [comment] 2017-12-11 15:32
As a simpler solution for this particular case, couldn't we add a normalization rule to convert the constant to the variable type (if one is TIMESTAMP and the other TIMESTAMPTZ)?

**Comment by nvanbenschoten** [comment] 2017-12-11 15:58
The problem is the cast though, right? We already do the right type conversion for untyped constants. Do you want the normalization rule to just ignore improper casts like these?

**Comment by RaduBerinde** [comment] 2017-12-11 16:14
Hm. Good point.. If we know that `a > 'x'::timestamp` is always equivalent to `a > 'x'::timestamptz`, it should be ok to remove/change the cast no?

**Comment by RaduBerinde** [comment] 2017-12-11 19:30
Cool, makes sense.

**Comment by RaduBerinde** [comment] 2018-09-25 14:50
@justinj I think your PR covers this case, can you verify?

**Comment by justinj** [comment] 2018-09-25 17:53
The PR as written won't, because it doesn't use INT -> TIMESTAMP conversions, are those safe to just include in the whitelist? Are there any gotchas with that? I'm a little iffy on how such conversions work but it seems like it should be safe

**Comment by RaduBerinde** [comment] 2018-09-28 17:39
I thought the problem here was a `TIMESTAMP` vs `TIMESTAMPTZ` comparison?

**Comment by RaduBerinde** [comment] 2018-10-02 21:47
Indeed the example still doesn't work. I believe the problem is that we don't constant-fold the cast; if we did that, maybe `UnifyComparisonTypes` would kick in.

In any case, moving this to 2.2.

```
root@127.227.206.252:41463/defaultdb> explain (opt) SELECT customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp FROM config_versions WHERE updatetimestamp >= 1510472101::TIMESTAMP ORDER BY updatetimestamp DESC LIMIT 2147483647;
                                                                                         text                                                                                         
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  limit                                                                                                                                                                               
   ├── columns: customerid:1(int!null) objecttype:2(int!null) objectid:3(int!null) propertyname:4(string!null) timeinstant:5(int!null) updatetimestamp:6(timestamptz!null)            
   ├── select                                                                                                                                                                         
   │    ├── columns: customerid:1(int!null) objecttype:2(int!null) objectid:3(int!null)    │    ├── scan config_versions@config_versions_by_version                                                                                                                           
   │    └── filters [type=bool, outer=(6), constraints=(/6: (/NULL - ])]                                                                                                              
   │         └── ge [type=bool, outer=(6), constraints=(/6: (/NULL - ])]                                                                                                              
   │              ├── variable: updatetimestamp [type=timestamptz, outer=(6)]                                                                                                         
   │              └── cast: TIMESTAMP [type=timestamp]                                                                                                                                
   │                   └── const: 1510472101 [type=int]                                                                                                                               
   └── const: 2147483647 [type=int]                                                                                                                                                   
```

**Comment by justinj** [comment] 2019-05-22 14:30
Seems fixed now:
```
root@127.0.0.1:55293/defaultdb> create table config_versions (updatetimestamp timestamp, customerid int, objecttype int, objectid int, propertyname int, timeinstant int, primary key (updatetimestamp desc));
CREATE TABLE

Time: 3.455ms

root@127.0.0.1:55293/defaultdb> explain SELECT customerid, objecttype, objectid, propertyname, timeinstant, updatetimestamp FROM config_versions WHERE updatetimestamp >= 1510472101::TIMESTAMP ORDER BY updatetimestamp DESC LIMIT 2147483647;
    tree    | field |       description
+-----------+-------+--------------------------+
  render    |       |
   └── scan |       |
            | table | config_versions@primary
            | spans | -/2017-11-12T07:35:01Z/#
            | limit | 2147483647
(5 rows)
```

**Closed by justinj** 2019-05-22 14:30 UTC
Labels: A-sql-planning, C-enhancement
