### ISSUE TITLE
TestReplicateRogueRemovedNode: expected [16 0 5], got [16 5 5]

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3434] opened 2015-12-14 16:08 UTC
The following test appears to have failed:

[#10156](https://circleci.com/gh/cockroachdb/cockroach/10156):

```
W1214 16:08:07.438649 961 multiraft/multiraft.go:1298  node 1 failed to send message to 3: multiraft/transport.go:158: unknown peer 3
W1214 16:08:07.449893 961 multiraft/multiraft.go:1298  node 2 failed to send message to 3: multiraft/transport.go:158: unknown peer 3
I1214 16:08:07.512531 961 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1214 16:08:07.512874 961 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1214 16:08:07.513157 961 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (1.48s)
	<autogenerated>:32: storage/client_raft_test.go:1322: condition failed to evaluate within 1s: storage/client_test.go:576: expected [16 0 5], got [16 5 5]
=== RUN   TestReplicateReAddAfterDown
E1214 16:08:07.516786 961 gossip/gossip.go:181  different node IDs were set for the same gossip instance (2147483647, 1)
I1214 16:08:07.519072 961 multiraft/multiraft.go:579  node 1 starting
I1214 16:08:07.519719 961 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1214 16:08:07.521266 961 raft/raft.go:441  [group 1] 1 became follower at term 5
I1214 16:08:07.521790 961 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1214 16:08:07.522371 961 multiraft/multiraft.go:999  node 1 campaigning because initial confstate is [1]
I1214 16:08:07.522473 961 raft/raft.go:521  [group 1] 1 is starting a new election at term 5
I1214 16:08:07.522564 961 raft/raft.go:454  [group 1] 1 became candidate at term 6
--
I1214 16:08:17.564785 961 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1214 16:08:17.564992 961 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.43s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.74s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	32.884s
=== RUN   TestBatchBasics
I1214 16:08:10.161669 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1214 16:08:10.165092 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1214 16:08:10.170266 1019 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-01-04 22:59
Duplicate of #3538

**Closed by bdarnell** 2016-01-04 22:59 UTC
Labels: test-failure
