### ISSUE TITLE
circleci: failed tests (14224): TestRangeSplitsWithWritePressure TestKVDBCoverage TestKVDBInternalMethods 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5046] opened 2016-03-10 03:47 UTC
The following test appears to have failed:

[#14224](https://circleci.com/gh/cockroachdb/cockroach/14224):

```
W160310 03:45:22.263097 storage/replica.go:1809  [node=1,store=1,range=3] failed to resolve intents: kv/batch.go:53: local key range must not span ranges
I160310 03:45:26.925073 kv/txn_coord_sender.go:282  txn coordinator: 25.27 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.2/1 avg/σ/max restarts (33 samples)
I160310 03:45:31.925493 kv/txn_coord_sender.go:282  txn coordinator: 18.11 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.2/1 avg/σ/max restarts (33 samples)
I160310 03:45:36.925946 kv/txn_coord_sender.go:282  txn coordinator: 12.97 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.2/1 avg/σ/max restarts (33 samples)
I160310 03:45:41.929096 kv/txn_coord_sender.go:282  txn coordinator: 9.29 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.2/1 avg/σ/max restarts (33 samples)
--- FAIL: TestRangeSplitsWithWritePressure (20.69s)
	testing.go:170: kv/split_test.go:221: condition failed to evaluate within 15s: kv/split_test.go:218: failed to verify no dangling intents: conflicting intents on [/Meta2/"YvOAlRdXcV" /Meta2/"gBGjZfYbbH"]: resolved? false
	leaktest.go:80: Leaked goroutine: goroutine 964 [chan receive]:
		github.com/cockroachdb/cockroach/rpc.NewContext.func1()
			/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x57
		github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066a1e0)
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
		created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
			/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62
	leaktest.go:80: Leaked goroutine: goroutine 965 [chan receive]:
		github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8206604e0)
--
I160310 03:46:03.819518 storage/raft_log_queue.go:135  truncating the raft log of range 1 to 33
I160310 03:46:03.831320 server/status/runtime.go:137  runtime stats: 68 goroutines, 8.88MiB active, 151.66cgo/sec, 0.52/0.49 %(u/s)time, 0.00 %gc (11x)
I160310 03:46:03.850430 server/node.go:611  node 1 status: {"desc":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:45725"},"attrs":{}},"store_ids":[1],"range_count":1,"started_at":1457581553817394406,"updated_at":1457581563844610339,"stats":{"last_update_nanos":1457581563831551614,"intent_age":0,"gc_bytes_age":0,"live_bytes":10098,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":9482,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:03.851028 server/node.go:626  store 1 status: {"desc":{"store_id":1,"attrs":{},"node":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:45725"},"attrs":{}},"capacity":{"capacity":257668677632,"available":194229284864,"range_count":1}},"node_id":1,"range_count":1,"started_at":1457581553817394406,"updated_at":1457581563844610339,"stats":{"last_update_nanos":1457581563831551614,"intent_age":0,"gc_bytes_age":0,"live_bytes":10098,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":9482,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:03.960214 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestKVDBCoverage (10.19s)
	testserver.go:59: Could not start server: server/testserver.go:274: had 1 ranges at startup, expected 5
=== RUN   TestKVDBInternalMethods
W160310 03:46:03.986656 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
I160310 03:46:03.988289 rpc/clock_offset.go:148  monitoring cluster offset
W160310 03:46:03.990032 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
I160310 03:46:04.017493 server/node.go:348  store store=0:0 ([]=) not bootstrapped
I160310 03:46:04.022211 raft/raft.go:459  [group 1] 1 became follower at term 5
I160310 03:46:04.022275 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160310 03:46:04.022341 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160310 03:46:04.022371 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160310 03:46:14.028137 storage/raft_log_queue.go:135  truncating the raft log of range 1 to 31
I160310 03:46:14.039172 server/status/runtime.go:137  runtime stats: 69 goroutines, 8.18MiB active, 95.67cgo/sec, 0.51/0.47 %(u/s)time, 0.00 %gc (11x)
I160310 03:46:14.068016 server/node.go:611  node 1 status: {"desc":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:42448"},"attrs":{}},"store_ids":[1],"range_count":1,"started_at":1457581564028431801,"updated_at":1457581574067333470,"stats":{"last_update_nanos":1457581574050347239,"intent_age":0,"gc_bytes_age":0,"live_bytes":16566,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":15950,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:14.068613 server/node.go:626  store 1 status: {"desc":{"store_id":1,"attrs":{},"node":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:42448"},"attrs":{}},"capacity":{"capacity":257668677632,"available":195119190016,"range_count":1}},"node_id":1,"range_count":1,"started_at":1457581564028431801,"updated_at":1457581574067333470,"stats":{"last_update_nanos":1457581574050347239,"intent_age":0,"gc_bytes_age":0,"live_bytes":16566,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":15950,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:14.167882 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
--- FAIL: TestKVDBInternalMethods (10.21s)
	testserver.go:59: Could not start server: server/testserver.go:274: had 1 ranges at startup, expected 5
=== RUN   TestKVDBTransaction
W160310 03:46:14.197719 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
I160310 03:46:14.198270 rpc/clock_offset.go:148  monitoring cluster offset
W160310 03:46:14.200037 gossip/gossip.go:912  not connected to cluster; use --join to specify a connected node
I160310 03:46:14.205293 server/node.go:348  store store=0:0 ([]=) not bootstrapped
I160310 03:46:14.208714 raft/raft.go:459  [group 1] 1 became follower at term 5
I160310 03:46:14.209569 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160310 03:46:14.209598 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160310 03:46:14.209645 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160310 03:46:24.286545 server/node.go:611  node 1 status: {"desc":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:42725"},"attrs":{}},"store_ids":[1],"range_count":1,"started_at":1457581574247862931,"updated_at":1457581584285908496,"stats":{"last_update_nanos":1457581584280451441,"intent_age":0,"gc_bytes_age":0,"live_bytes":16076,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":15460,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:24.287031 server/node.go:626  store 1 status: {"desc":{"store_id":1,"attrs":{},"node":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:42725"},"attrs":{}},"capacity":{"capacity":257668677632,"available":195119190016,"range_count":1}},"node_id":1,"range_count":1,"started_at":1457581574247862931,"updated_at":1457581584285908496,"stats":{"last_update_nanos":1457581584280451441,"intent_age":0,"gc_bytes_age":0,"live_bytes":16076,"live_count":27,"key_bytes":616,"key_count":27,"val_bytes":15460,"val_count":27,"intent_bytes":0,"intent_count":0,"sys_bytes":338,"sys_count":6},"leader_range_count":1,"replicated_range_count":1,"available_range_count":1}
I160310 03:46:24.290491 server/status/runtime.go:137  runtime stats: 68 goroutines, 9.03MiB active, 126.46cgo/sec, 0.53/0.46 %(u/s)time, 0.00 %gc (12x)
I160310 03:46:24.387480 storage/engine/rocksdb.go:141  closing in-memory rocksdb instance
I160310 03:46:26.940587 kv/txn_coord_sender.go:282  txn coordinator: 0.46 txn/sec, 100.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0 avg/σ/max restarts (0 samples)
panic: test timed out after 1m10s

goroutine 6423 [running]:
panic(0x13b7ee0, 0xc820a7e090)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1a74ac0, 0x219ca60, 0x57, 0x57, 0xc820237400)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820034f08, 0x5cfa83)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/kv/_test/_testmain.go:232 +0x117

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x24ed8a0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1010 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 6289 [sleep]:
time.Sleep(0x2faf080)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cockroachdb/cockroach/util/leaktest.AfterTest.func1()
	/go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:76 +0x309
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:323 +0xfb
testing.(*common).FailNow(0xc8209ad830)
	/usr/local/go/src/testing/testing.go:346 +0x36
testing.(*common).Fatalf(0xc8209ad830, 0x1820340, 0x1a, 0xc820a6c7a0, 0x1, 0x1)
	/usr/local/go/src/testing/testing.go:389 +0x83
--
testing.tRunner(0xc8209ad830, 0x219d138)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 966 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1878 +0xa32
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc8207ac7e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 989 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b7e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 980 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc820514960)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:241 +0xbf3
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:226 +0x20
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc8207ac030)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 967 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func3()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:718 +0x11a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc820292600)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 986 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b740)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 965 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc8206604e0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:127 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:128 +0x5c2

goroutine 977 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:129 +0x910
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc8206cf440)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 964 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:99 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066a1e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 969 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:808 +0x353
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc820292640)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 987 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc820514fc0, 0xece72e4d1, 0x37769e19, 0x24ed000, 0xc8200171a0, 0xc8202380e0, 0xc8205a81c0, 0xc82001f698)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:176 +0x531
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc8205a81c0, 0xc8206a0180)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:214 +0x78
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc8206a0420, 0xc82051adc0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:230 +0x246
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:216 +0x1e1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b760)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 993 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b860)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 994 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc820514b40, 0xece72e4d1, 0x3777233b, 0x24ed000, 0xc8200171a0, 0xc8202380e0, 0xc8205a81c0, 0xc820268698)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:176 +0x531
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc8205a81c0, 0xc8206a0180)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:214 +0x78
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc8206a0270, 0xc82051ae40)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:230 +0x246
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:216 +0x1e1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b880)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 992 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b840)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 991 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b820)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 990 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b800)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 988 [select, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:352 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc82066b7c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62

goroutine 968 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:789 +0x353
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8202380e0, 0xc820292620)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x62
FAIL	github.com/cockroachdb/cockroach/kv	70.038s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)
=== RUN   TestKeyPrefixEnd
--- PASS: TestKeyPrefixEnd (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2016-03-10 12:23
possibly a dupe of #5043

**Closed by tamird** 2016-03-10 12:23 UTC
Labels: test-failure
