### ISSUE TITLE
sql: An error with a transaction retry

### ISSUE THREAD

**Issue by maweike** [cockroachdb/cockroach#52467] opened 2020-08-06 11:38 UTC
**Describe the problem**
An ALTER TABLE ADD COLUMN operation performed in a transaction maybe fail

reproduce like this:

create table a(a int);
begin;
select * from a;
alter table a add column "id" int;
commit;

Commit may fail with an error
restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" meta={id=b3c004d7 key=/Table/SystemConfigSpan/Start pri=0.01034620 epo=0 ts=1596707332.404527033,1 min=1596707332.403829047,0 seq=5} rw=true stat=PENDING rts=1596707332.403829047,0 wto=false max=1596707332.403829047,0

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster : use default cluster settings
2. Send SQL ... / CLI command ：use the SQL described above
3. See error

**Environment:**
 - Server OS:  Linux/Ubuntu16.04
 - Client app cockroach sql

**Comment by ajwerner** [comment] 2020-08-08 05:09
These errors are a common occurrence. See https://www.cockroachlabs.com/docs/v20.1/transactions.html#client-side-intervention for dealing with them and https://www.cockroachlabs.com/docs/v20.1/transaction-retry-error-reference.html for more details on where they might be coming from. 

I’m closing this issue as it does not indicate that a bug exists. If you disagree, consider filing an issue with more details explaining how the system is not working as intended. If you’re just getting started, the community slack would be a better forum to learn than filing issues.

**Closed by ajwerner** 2020-08-08 05:09 UTC
Labels: C-bug, O-community, X-blathers-triaged
