### ISSUE TITLE
Allow variable sub-expressions in DEFAULT value and CHECK constraints 

### ISSUE THREAD

**Issue by alex-berger** [cockroachdb/cockroach#129392] opened 2024-08-21 08:46 UTC
**Is your feature request related to a problem? Please describe.**

We have a multi-tenant data model like the one outline below, in which each tenant has a primary data location into which all data for that tenant should be stored using CockroachDB's [regional by row](https://www.cockroachlabs.com/docs/v24.2/table-localities.html#regional-by-row-tables) feature. Now, we have the following requirements:
- To enforce that tenant's data is never stored in the wrong region, we must put some [CHECK](https://www.cockroachlabs.com/docs/stable/check) constraints in place, which based on the tenant's unique ID will ensure that the right region is used to store data. 
- To decouple the business logic (e.g. INSERTS) from that row-level data homing logic, we also want to be able to populate the `crdb_region` column using a [DEFAULT](https://www.cockroachlabs.com/docs/stable/default-value) value constraint.

Unfortunately, this is currently not possible as CockroachDB does not allow using variable sub-expressions in DEFAULT value and CHECK constraints (see below example).

```SQL
-- Our tenant table, containing the data homing configuration for each tenant. 
create table nx.tenant (
  -- the unique tenant_id
  id uuid not null, 
  -- the CRDB region to store data for this tenant.
  crdb_region public.crdb_internal_region not null, 
  constraint tenant_pk primary key (id)
) locality regional by row as crdb_region;

-- UDF given a tenant_id returning the tenant's data region. Used for CHECK and DEFAULT constraints.
CREATE FUNCTION xx_my_region(tenant_id uuid) RETURNS public.crdb_internal_region STABLE LANGUAGE SQL AS 
   'SELECT crdb_region from nx.tenant where id = tenant_id';

-- Example table, which contains tenant specific data that must be stored in the tenant's data region.
create table nx.tenant_data (
  id uuid not null,
  -- the tenant_id
  tenant_id uuid not null,
  -- Below default constraint will result in 
  -- "SQL Error [42601]: ERROR: variable sub-expressions are not allowed ..."
  -- caused by the use of "tenant_id" as parameter (variable sub-expression) in the call to UDF.
  crdb_region public.crdb_internal_region not null 
     -- not using FK here for reasons (but that's for another feature request).
     check (crdb_region = alex_berger_tenancy.xx_my_region(tenant_id)) 
     default alex_berger_tenancy.xx_my_region(tenant_id),
  constraint data_pk primary key (id)
) locality regional by row as crdb_region;
```

***Why is this important to us***

Our customers (the tenants in our data model) rely on us to make sure we always store their data in their region only. This is a strict and non-negotiable compliance requirement. And we must not violate this data homing requirement under any circumstances. Therefore, we must enforce correct data homing on the database schema level (as outlined above) to avoid misplaced tenant data (e.g. due to bugs in software or human errors).

**Describe the solution you'd like**

Allow usage of variable sub-expressions in [DEFAULT](https://www.cockroachlabs.com/docs/stable/default-value) and [CHECK](https://www.cockroachlabs.com/docs/stable/check) constraints such that examples like the one outlined above will work.

**Describe alternatives you've considered**
None, as we are not aware on how to achieve this otherwise.

**Additional context**

- [#44412](https://github.com/cockroachdb/cockroach/issues/44412) already raised this in context of [Check Constraints](https://www.cockroachlabs.com/docs/stable/check), but was closed due to no activity.
- I guess, these are some of the offending code lines 
   - https://github.com/cockroachdb/cockroach/blob/f1a5aa8a633636138fededdf46a8dcc20f899a48/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_alter_column_set_default.go#L136
   - https://github.com/cockroachdb/cockroach/blob/f1a5aa8a633636138fededdf46a8dcc20f899a48/pkg/sql/alter_table.go#L1363

Jira issue: CRDB-41517

**Comment by alex-berger** [comment] 2024-08-21 12:29
Related to https://github.com/cockroachdb/cockroach/issues/87699

**Comment by mgartner** [comment] 2024-08-23 17:41
> To enforce that tenant's data is never stored in the wrong region, we must put some [CHECK](https://www.cockroachlabs.com/docs/stable/check) constraints in place, which based on the tenant's unique ID will ensure that the right region is used to store data.
> ...
> Unfortunately, this is currently not possible as CockroachDB does not allow using variable sub-expressions in DEFAULT value and CHECK constraints (see below example).

These types of `CHECK` constraints are allowed[^check]. However, foreign keys are a better tool for this use case because they are specifically designed to uphold a constraint involving data across multiple tables. See the example[^fk].

> Our customers (the tenants in our data model) rely on us to make sure we always store their data in their region only. This is a strict and non-negotiable compliance requirement. And we must not violate this data homing requirement under any circumstances.

`CHECK` constraints are not able to do this with any real integrity. Non-immutable `CHECK` constraints can be violated because, by design, they are only upheld upon writes (i.e., `INSERT`, `UPDATE` and `UPSERT`) to the table with the `CHECK` constraint. They provide no real guarantees when data in other tables is mutated. We support them for compatibility with Postgres, but in an ideal world I would prefer we disallowed them entirely because they are quite dangerous. See the example showing a non-immutable `CHECK` constraint that can be violated[^corrupt].

> To decouple the business logic (e.g. INSERTS) from that row-level data homing logic, we also want to be able to populate the crdb_region column using a [DEFAULT](https://www.cockroachlabs.com/docs/stable/default-value) value constraint.

[Triggers](https://www.postgresql.org/docs/current/triggers.html) will work well for this, once they are supported. We're currently working on them and we hope to land them in an upcoming major release soon.

[^check]: Example of a `CHECK` contraint calling a UDF with an argument.

    ```sql
    CREATE TABLE s (k INT PRIMARY KEY, i INT);
    INSERT INTO s VALUES (1, 10), (2, 20);
    
    CREATE FUNCTION f(x INT) RETURNS INT LANGUAGE SQL AS $$
      SELECT i FROM s WHERE k = x
    $$;
    
    CREATE TABLE t (
      k INT PRIMARY KEY,
      a INT CHECK (a = f(k))
    );
    
    INSERT INTO t VALUES (1, 10);
    
    INSERT INTO t VALUES (2, 20);
    
    SELECT * FROM t;
    --  k | a
    ------+-----
    --  1 | 10
    --  2 | 20
    --(2 rows)
    
    UPDATE t SET a = 30 WHERE k = 1;
    -- ERROR: failed to satisfy CHECK constraint (a = public.f(k))
    -- SQLSTATE: 23514
    -- CONSTRAINT: check_a_k
    ```

[^fk]: Example of using foreign key constraint to maintain data locality guarantees.

    ```sql
    CREATE TABLE tenant (
      id INT PRIMARY KEY, -- using an INT for simplicity
      crdb_region STRING NOT NULL, -- using a STRING for simplicity
      UNIQUE (crdb_region, id)
    );
    
    CREATE TABLE tenant_data (
      id INT PRIMARY KEY,
      tenant_id INT NOT NULL,
      crdb_region STRING NOT NULL,
      FOREIGN KEY (crdb_region, tenant_id) REFERENCES tenant(crdb_region, id)
        ON UPDATE CASCADE
    );
    
    INSERT INTO tenant VALUES (1, 'east');
    -- INSERT 0 1
    
    INSERT INTO tenant_data VALUES (10, 1, 'east');
    -- INSERT 0 1
    
    INSERT INTO tenant_data VALUES (11, 1, 'west');
    -- ERROR: insert on table "tenant_data" violates foreign key constraint "tenant_data_crdb_region_tenant_id_fkey"
    -- SQLSTATE: 23503
    -- DETAIL: Key (crdb_region, tenant_id)=('west', 1) is not present in table "tenant".
    -- CONSTRAINT: tenant_data_crdb_region_tenant_id_fkey
    
    UPDATE tenant SET crdb_region = 'west' WHERE id = 1;
    -- UPDATE 1
    
    SELECT * FROM tenant_data;
    --   id | tenant_id | crdb_region
    -- -----+-----------+--------------
    --   10 |         1 | west
    -- (1 row)
    ```

[^corrupt]: Example of a `CHECK` constraint failing to uphold guarantees across data in multiple tables.

    ```sql
    CREATE TABLE eleven (i INT);
    INSERT INTO eleven VALUES (11);
    
    CREATE FUNCTION elvn() RETURNS INT LANGUAGE SQL AS $$
      SELECT i FROM eleven;
    $$;
    
    -- Create a table with a CHECK constraint invoking a stable function, i.e., it
    -- is not immutable.
    CREATE TABLE t (
      k INT PRIMARY KEY,
      a INT CHECK (a = elvn())
    );
    
    INSERT INTO t VALUES (1, 11);
    -- INSERT 0 1
    
    -- We have one run conforming to the CHECK constraint.
    SELECT * FROM t;
    --  k | a
    -- ---+----
    --  1 | 11
    -- (1 row)
    
    -- Change the value in eleven.
    UPDATE eleven SET i = 12;
    -- UPDATE 1
    
    -- Inserting 11 now fails due to the CHECK constraint.
    INSERT INTO t VALUES (2, 11);
    -- ERROR: failed to satisfy CHECK constraint (a = public.elvn())
    -- SQLSTATE: 23514
    -- CONSTRAINT: check_a
    
    -- We can insert 12.
    INSERT INTO t VALUES (2, 12);
    -- INSERT 0 1
    
    -- Now we have two rows, one that conforms to the CHECK constraint and one that
    -- does not.
    SELECT * FROM t;
    --  k | a
    -- ---+----
    --  1 | 11
    --  2 | 12
    -- (2 rows)
    ```

**Comment by alex-berger** [comment] 2024-08-26 07:17
@mgartner Which exact CockroachDB version did you use?

**Comment by alex-berger** [comment] 2024-08-27 08:27
OK, I think I figured out where my confusion is coming from :-) as of CockroachDB version `v24.2`

- CHECK constraints support variable sub-expressions 
- DEFAULT value constraints, still **do not** support variable sub-expressions

So we can narrow down the scope of this feature request to 

> Support variable sub-expressions in DEFAULT value constrains.

**Comment by alex-berger** [comment] 2024-08-28 14:25
Related to https://github.com/cockroachdb/cockroach/issues/66619

**Comment by mgartner** [comment] 2024-08-28 14:26
> OK, I think I figured out where my confusion is coming from :-) as of CockroachDB version v24.2
> 
>     * CHECK constraints support variable sub-expressions
>     * DEFAULT value constraints, still do not support variable sub-expressions

That's correct. I'll go ahead and close this as a duplicate of #66619.

**Closed by mgartner** 2024-08-28 14:26 UTC
Labels: C-enhancement, O-community, A-multiregion, T-sql-queries
