### ISSUE TITLE
roachtest: acceptance/version-upgrade replica divergence

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#53017] opened 2020-08-19 09:05 UTC
Got this one in TC

https://teamcity.cockroachdb.com/viewLog.html?buildId=2193857&buildTypeId=Cockroach_UnitTests

```
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) 5 safe details enclosed
		Wraps: (3) r273 (/Table/39) is inconsistent: RANGE_INCONSISTENT 
		  | (n4,s4):2: checksum ed7dab4b5c025c23de1aa6b05b6ed71de040f8305e2cfc84ad9075efbc915dc7cc15506bc9643f915ef63342f0adacc72bf7972a60150b3c278e77a7c0c24be2
		  | - stats: contains_estimates:0 last_update_nanos:1597771902160888573 intent_age:0 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 intent_bytes:0 intent_count:0 sys_bytes:855 sys_count:11 abort_span_bytes:3 
		  | - stats.Sub(recomputation): last_update_nanos:1597771902160888573 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 sys_bytes:855 sys_count:11 abort_span_bytes:3 
		  | (n1,s1):1: checksum ed7dab4b5c025c23de1aa6b05b6ed71de040f8305e2cfc84ad9075efbc915dc7cc15506bc9643f915ef63342f0adacc72bf7972a60150b3c278e77a7c0c24be2
		  | - stats: contains_estimates:0 last_update_nanos:1597771902160888573 intent_age:0 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 intent_bytes:0 intent_count:0 sys_bytes:855 sys_count:11 abort_span_bytes:3 
		  | - stats.Sub(recomputation): last_update_nanos:1597771902160888573 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 sys_bytes:855 sys_count:11 abort_span_bytes:3 
		  | (n3,s3):3: checksum eeae37c2fd09b4d36ab136d6287ac83602355685d37478b4868aa74c9141e02dc91caab524eb7a3a31d1fa98c531d04849ac866bdc30b03a2847d1a3b047630c [minority]
		  | - stats: contains_estimates:0 last_update_nanos:1597771902160888573 intent_age:0 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 intent_bytes:0 intent_count:0 sys_bytes:855 sys_count:11 abort_span_bytes:0 
		  | - stats.Sub(recomputation): last_update_nanos:1597771902160888573 gc_bytes_age:111375 live_bytes:448 live_count:8 key_bytes:1624 key_count:8 val_bytes:2520 val_count:120 sys_bytes:855 sys_count:11 
		Error types: (1) *withstack.withStack (2) *safedetails.withSafeDetails (3) *errors.errorString

test artifacts and logs in: artifacts/acceptance/version-upgrade/run_1
	cluster.go:1699,test_runner.go:837: r273 (/Table/39) is inconsistent: RANGE_INCONSISTENT 
		(1) attached stack trace
		  | main.(*cluster).CheckReplicaDivergenceOnDB
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1650
		  | main.(*cluster).FailOnReplicaDivergence.func2
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1696
		  | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:135
		  | main.(*cluster).FailOnReplicaDivergence
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/cluster.go:1693
		  | main.(*testRunner).runTest
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:837
		  | main.(*testRunner).runWorker
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:464
		  | main.(*testRunner).Run.func2
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/cmd/roachtest/test_runner.go:275
		  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1
		  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:222
		  | runtime.goexit
		  | 	/usr/local/go/src/runtime/asm_amd64.s:1357
		Wraps: (2) 5 safe details enclosed
```

https://teamcity.cockroachdb.com/viewLog.html?buildId=2193857&buildTypeId=Cockroach_UnitTests

**Comment by irfansharif** [comment] 2020-08-19 12:45
Duplicate of #52907.

**Closed by irfansharif** 2020-08-19 12:45 UTC
Labels: C-test-failure
