### ISSUE TITLE
Suspicious Estimated Rows of `HAVING` Clause

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#88982] opened 2022-09-29 02:43 UTC
**Describe the problem**

Greater number of estimated rows returned by a specific `SELECT` statement with `HAVING` clause than the same `SELECT` statement without the `HAVING` clause. 

**To Reproduce**

```
create table t0 (c1 INT);
create table t1 (c1 INT);
insert into t0 values(1),(2);
insert into t1 values(3),(4),(5);
ANALYZE t0;
ANALYZE t1;
EXPLAIN (VERBOSE) SELECT t0.c1 FROM t1 LEFT OUTER JOIN t0 ON NULL GROUP BY t0.c1; -- estimated rows: 1
EXPLAIN (VERBOSE) SELECT t0.c1 FROM t1 LEFT OUTER JOIN t0 ON NULL GROUP BY t0.c1 HAVING ((t0.c1) IS NULL); -- estimated rows: 3
```

**Expected behavior**
The number of estimated rows of the second `SELECT` statement should be less than that of the first one as the second `SELECT` has an additional `HAVING` constraint than the first `SELECT` statement.

**Additional data / screenshots**

The query plan of the first `SELECT` statement.
```
                                                 info
----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • distinct
  │ columns: (c1)
  │ estimated row count: 1
  │ distinct on: c1
  │
  └── • cross join (left outer)
      │ columns: (c1)
      │ estimated row count: 3
      │
      ├── • scan
      │     columns: ()
      │     estimated row count: 3 (100% of the table; stats collected 11 minutes ago)
      │     table: t1@t1_pkey
      │     spans: FULL SCAN
      │
      └── • norows
            columns: (c1)
(20 rows)
```

The query plan of the second `SELECT` statement.
```
                                                               info
--------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • limit
  │ columns: (c1)
  │ count: 1
  │
  └── • filter
      │ columns: (c1)
      │ estimated row count: 3
      │ filter: c1 IS NULL
      │
      └── • cross join (left outer)
          │ columns: (c1)
          │ estimated row count: 3
          │
          ├── • scan
          │     columns: ()
          │     estimated row count: 3 (100% of the table; stats collected 11 minutes ago)
          │     table: t1@t1_pkey
          │     spans: FULL SCAN
          │
          └── • norows
                columns: (c1)
(24 rows)
```

We have no idea what the `limit` (It has a number of count 1) means in the second query plan, but the estimated rows seems unexpected in the `filter`.

As a reference, if we remove the `LEFT JOIN` in the both `SELECT` statements, the number estimated rows is expected.
```
EXPLAIN (VERBOSE) SELECT t0.c1 FROM t0 GROUP BY t0.c1; -- estimated rows: 2
EXPLAIN (VERBOSE) SELECT t0.c1 FROM t0 GROUP BY t0.c1 HAVING ((t0.c1) IS NULL); -- estimated rows: 0
```

**Environment:**
 - CockroachDB version [f188d21d1853ca8b81d9c4f0ab46d7c0fa34ee44]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

**Comment by DrewKimball** [comment] 2022-09-30 01:30
I think this is expected behavior - the `HAVING` clause shouldn't filter any rows in this case. Because the join condition is `ON NULL`, there will be no matches and so the `LEFT JOIN` will output each left row null-extended to fill out the right columns. Because of that,  `t0.c1 IS NULL` will always be true. I'm going to close this issue for now, but feel free to comment with any further questions you have.

**Closed by DrewKimball** 2022-09-30 01:30 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries

**Comment by DrewKimball** [comment] 2022-09-30 02:40
The query with `HAVING` also expects 1 row (not 3), it's just obscured by the `limit` node. It's only the intermediate operators that expect 3 rows, which is the same as the first query.

**Comment by bajinsheng** [comment] 2022-09-30 05:24
Thanks for your explanation!

But what is the meaning of the `limit` node in the query plan? I haven't found any document about it.

In your explanation, I understand the final estimated row is the `count` in the `limit` node, not the `estimated rows` in the `filter` node. May I ask what is the difference between `count` and `estimated rows`? Are both the same meaning?

**Comment by DrewKimball** [comment] 2022-09-30 08:22
The `limit` is just what it sounds like; it passes through input rows until it reaches a preset limit (1 in this case). Since a limit can be expected to output the smaller of its limit value and its input's expected row count, an `estimated row count` field would be redundant.

As for why there's a `limit` instead of `distinct` for the `HAVING` query, the `IS NULL` filter lets the optimizer see that the grouping column is constant, and so we only need to output a single row from the input in order to satisfy the `distinct`. Therefore, it gets transformed into a `limit`.
