### ISSUE TITLE
sql: allow inserts into computed columns if default value.

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#114860] opened 2023-11-21 21:41 UTC
Repro:
```
CREATE TABLE gtest1 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED);
INSERT INTO gtest1 VALUES (1);
INSERT INTO gtest1 VALUES (2, DEFAULT); -- succeeds in postgres
SELECT * FROM gtest1;
 a | b                                                                 
---+---                                                                
 1 | 2                                                                 
 2 | 4  -- missing in CRDB because the last insert fails
```

Found in pg_regress generated

Jira issue: CRDB-33722

**Comment by mgartner** [comment] 2023-12-05 19:44
Duplicate of #22434.

**Closed by mgartner** 2023-12-05 19:44 UTC
Labels: C-bug, O-qa, T-sql-queries, O-pg-regress
