### ISSUE TITLE
server: had X ranges at startup, expected 22

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#29144] opened 2018-08-27 20:34 UTC
https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=864518&_focus=46771

```
[20:21:58][Run Go tests] TestDropDatabaseDeleteData
...
[20:21:58][TestDropDatabaseDeleteData] test_server_shim.go:176: had 9 ranges at startup, expected 22
```

**Comment by vivekmenezes** [comment] 2018-08-27 20:52
I've begun to this more often on some test failures as well.

**Comment by petermattis** [comment] 2018-08-27 21:00
@couchand Have you rebased with master? I thought I fixed this error in https://github.com/cockroachdb/cockroach/pull/28877. Ditto for @vivekmenezes. If you can reproduce on a build that you are sure includes #28877 I'd love to take a look.

**Comment by vivekmenezes** [comment] 2018-08-27 21:02
@petermattis I'm pretty sure I saw this on a branch that was rebased today.

**Comment by petermattis** [comment] 2018-08-27 21:39
@vivekmenezes It would be super helpful if you can point me towards other CI failures.

**Comment by petermattis** [comment] 2018-08-28 00:41
Looks like the build @couchand referenced definitely included #28877. The error in that failure looks slightly different from what I saw before:

```
I180827 20:19:05.080080 61196 storage/replica_proposal.go:210  [n1,s1,r18/1:/{Table/21-Max}] new range lease repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0 following repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0
I180827 20:19:05.080699 61580 storage/replica_command.go:298  [split,n1,s1,r19/1:/{Table/22-Max}] initiating a split of this range at key /Table/23 [r20]
I180827 20:19:05.085893 61203 storage/replica_proposal.go:210  [n1,s1,r19/1:/{Table/22-Max}] new range lease repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0 following repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0
I180827 20:19:05.086456 61620 storage/replica_command.go:298  [split,n1,s1,r20/1:/{Table/23-Max}] initiating a split of this range at key /Table/50 [r21]
I180827 20:19:05.090441 61067 storage/replica_proposal.go:210  [n1,s1,r20/1:/{Table/23-Max}] new range lease repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0 following repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0
I180827 20:19:05.090920 61516 storage/replica_command.go:298  [split,n1,s1,r21/1:/{Table/50-Max}] initiating a split of this range at key /Table/51 [r22]
I180827 20:19:05.095782 61156 storage/replica_proposal.go:210  [n1,s1,r21/1:/{Table/50-Max}] new range lease repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0 following repl=(n1,s1):1 seq=3 start=1535401134.946701909,0 epo=1 pro=1535401144.952676685,0
[TestDropDatabaseDeleteData] test_server_shim.go:176: had 9 ranges at startup, expected 22
```

I'm pretty sure an error is logged if one of those splits fails. So it looks like there are 22 ranges, but the test cluster code is only seeing 9? That sounds weird.

**Comment by andreimatei** [comment] 2018-08-28 00:48
The messages say that the splits are "initiated". Do they happen just one at a time?

**Comment by petermattis** [comment] 2018-08-28 00:58
> The messages say that the splits are "initiated". Do they happen just one at a time?

Yes (by the `split` queue which we know is happening due to the `split` tag). Hmmm, actually I'm wrong. The split queue now has a concurrency of 4. Regardless, at worst we'd expect the 18 ranges. But there were only 9.

**Comment by petermattis** [comment] 2018-08-28 01:13
Linked to #29027 and #29068 which are other failures that seem to include #28877. Not sure what is going on. I've spent the last 30m unsuccessfully trying to reproduce. #29027 shows a similar failure to the above where we seem to have initiated splits for all of the ranges, but the test reports that only 11 of 22 ranges exist. #29068 is a more expected failure where I only see log messages for splits up to range 12 and only 12 ranges are reported at failure time.

**Comment by couchand** [comment] 2018-09-04 18:35
Just got another one on a pure UI PR, in this case just CSS even.  https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=882167&_focus=16962

**Comment by petermattis** [comment] 2018-09-06 01:43
Just noticed something interesting: the current crop of failures all involve single-node clusters, usually started via `serverutils.StartServer()`. The failure fixed by #28877 involved multi-node cluster. Almost certainly a different problem.

**Comment by petermattis** [comment] 2018-09-06 01:51
Most of the recent failures show a similar pattern. The test starts up and splits, splits, splits within a few seconds there is a 7-8s gap in the logs. For example:

```
I180904 05:45:41.417086 4182 gossip/gossip.go:941  [n1] gossip connectivity
  n1 [sentinel];
 
I180904 05:45:49.620606 4294 storage/replica_proposal.go:211  [n1,s1,r10/1:/Table/1{3-4}] new range lease repl=(n1,s1):1 seq=3 start=1536039939.564064621,0 epo=1 pro=1536039949.618037271,0 following repl=(n1,s1):1 seq=2 start=1536039939.564064621,0 exp=1536039948.577861780,0 pro=1536039939.577892057,0
```

And

```
I180831 05:22:34.462649 2609 gossip/gossip.go:941  [n1] gossip connectivity
  n1 [sentinel];
 
I180831 05:22:41.474264 2768 storage/replica_proposal.go:211  [n1,s1,r4/1:/System/{NodeLive…-tsd}] new range lease repl=(n1,s1):1 seq=3 start=1535692952.466982014,0 epo=1 pro=1535692961.473976227,0 following repl=(n1,s1):1 seq=2 start=1535692952.466982014,0 exp=1535692961.467219509,0 pro=1535692952.467236389,0
```

What happened to our splits? Or did something else occur with the test? 

I'm unable to reproduce this problem so far, even with a targeted test and severe stress.

**Comment by petermattis** [comment] 2018-09-06 02:12
I tried melting my machine by running one of these failing tests with `STRESSFLAGS="-p 64"` and I was able to see a failure. I then bumped initial split timeout from 10s to 1m and the failure went away. I wonder if we're running a little to close to the edge.

I've pondered in the past running stress with half the concurrency of the default.

**Comment by petermattis** [comment] 2018-09-06 15:41
Just checked. Swap is not enabled on the TC machines.

**Comment by andreimatei** [comment] 2018-09-18 17:42
You can try adding a flag making the split queue do all its work (or, say,
the first x splits) in a recorded span and print that trace on test
failure. I can show you things if you want.

**Comment by andreimatei** [comment] 2018-12-13 19:39
I'm deleting the test that was introduced when this bug was fixed. The test was relying on a server's initial splits to produce some chaos. The initial splits are going away. 
Reopening the issue until a better test is written. If no better idea comes along, the initial splits can still be performed in tests in the storage package when using a `multiTestContext` with a  particular option (instead of using a `TestStore`).
```
// Verify that replicas don't temporrily disappear from the replicas map during
// the splits. See #29144.
func TestStoreSplitDisappearingReplicas(t *testing.T) {
	defer leaktest.AfterTest(t)()
	stopper := stop.NewStopper()
	defer stopper.Stop(context.TODO())
	store, _ := createTestStore(t, stopper)
	go storage.WatchForDisappearingReplicas(t, store)
	if err := server.WaitForInitialSplits(store.DB()); err != nil {
		t.Fatal(err)
	}
}
```

**Comment by petermattis** [comment] 2018-12-14 18:04
@andreimatei Re-opening this issue doesn't quite seem right. The original problem was fixed and you're not re-introducing it. I think it is more appropriate to track this in a new issue.

FWIW, all this test is doing is making sure that replicas do not spuriously disappear during splits. It was previously taking advantage of the initial splits for this purpose, but it should be perfectly fine to perform manual splits (you'll want to disable the merge-queue, though). That is, rather than `WaitForInitialSplits`, just create 100 manual splits.

**Comment by andreimatei** [comment] 2018-12-19 00:02
OK, recreated the test.

**Closed by andreimatei** 2018-12-19 00:02 UTC
Labels: A-core-kv, C-test-failure
