### ISSUE TITLE
opt: query taking over 400s after upgrade 

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#43958] opened 2020-01-14 15:28 UTC
**Describe the problem**
The Tracker Network recently upgrade their production cluster from 19.1 to 19.2.1 and noticed that a query went from taking ~18s to return to over ~350s to return. 

Upon further investigation it was suggested that they force a different join algorithm other than lookup which was being used.

When forcing to use a merge or a hash join, the time to return data drastically dropped from ~350s to ~10s. 

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

Attached is the original query, as well as the explain(opt, env), table statistics, and the explain analyze can all be found [here](https://drive.google.com/drive/folders/1Xoo0yFNBtI3ZQ5N26ebYvmBOSb-M74p_?usp=sharing)

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**
As mentioned before this query was taking under 20s and increased drastically after upgrading.  The query in question is critical to their application and so it should not be taking over 400s to return results. As mentioned, we did find a workaround, but it would be good to know the root cause of this issue. If we need more information please let me know and we can get more info. 

**Environment:**
 - CockroachDB version 19.2.1

**Comment by RoachietheSupportRoach** [comment] 2020-01-14 15:29
Zendesk ticket #[4391](https://cockroachdb.zendesk.com/agent/tickets/4391) has been linked to this issue.

**Comment by RaduBerinde** [comment] 2020-01-17 19:01
The query uses window functions so it would have used the heuristic planner in 19.1.  I am working on reproducing, but regardless for now they will have to keep the join hint.

**Comment by bladefist** [comment] 2020-01-17 19:15
@RaduBerinde was that regression documented anywhere?

**Comment by RaduBerinde** [comment] 2020-01-17 19:27
I reproduced and the estimated statistics are pretty good, they're not the issue. The problem is that we no longer parallelize certain lookup joins in 19.2 and the coster was not aware of that. That was fixed in https://github.com/cockroachdb/cockroach/pull/43059, which I believe will be in the next 19.2.x release. I recommend trying again with that release when it becomes available. The new plan is not a hash join, but a different (single) lookup join that can be parallelized:
```
sort
 └── project
      ├── window partition=() ordering=-6 opt(38)
      │    ├── project
      │    │    └── limit
      │    │         ├── sort
      │    │         │    └── inner-join (lookup apex_account)
      │    │         │         ├── lookup columns are key
      │    │         │         ├── select
      │    │         │         │    ├── scan tbl
      │    │         │         │    └── filters
      │    │         │         │         ├── legend = 8
      │    │         │         │         └── kills IS NOT NULL
      │    │         │         └── filters
      │    │         │              ├── platform_id = 1
      │    │         │              └── is_banned = false
      │    │         └── const: 100
      │    └── windows
      │         └── rank
      └── projections
           └── rank + 100
```

**Comment by RaduBerinde** [comment] 2020-01-17 19:38
@bladefist it was documented in the release notes that queries with window functions now use the optimizer. But not as a regression - in general it's a positive change, though of course there are some cases (like this one) where the optimizer chooses a bad plan and the heuristic planner happened to be doing a good job.

Another issue that is relevant is that in 19.1, lookup joins could cause OOM so we stopped parallelizing them in 19.2.0 (I'm not sure if this was documented with the release). This can make some queries much slower. In 19.2.2 we made a fix to parallelize them when the lookup columns are a key in the target table (common case), and the PR mentioned above (which will be in 19.2.3) fixes the optimizer to cost the slower lookup joins accordingly (together these are all needed to fix this case).

**Comment by RaduBerinde** [comment] 2020-01-17 19:43
Btw 19.2.3 is scheduled for release on 2020-01-27.

**Comment by bladefist** [comment] 2020-01-17 19:49
Ok thanks.  So in 19.2.3 these queries will automatically do what kind of join? I assume not a lookup join since that is slow for my queries.

**Comment by RaduBerinde** [comment] 2020-01-17 20:08
In 19.2.3 this query will do a different lookup join (plan pasted [above](https://github.com/cockroachdb/cockroach/issues/43958#issuecomment-575762424)). I am hoping it's even faster than the hash join plan (which has an index-join), but can't know for sure. Note that the bad plan you are seeing has both the index-join and TWO lookup joins.

I believe you can try that plan using `apex_stats AS tbl INNER LOOKUP JOIN apex_account@primary` but only in 19.2.2 (it will still be slow in 19.2.1 because it doesn't have #42681).

**Comment by bladefist** [comment] 2020-01-17 20:18
Instead of wait to see, we can find out now? I'm in #tracker-network on your slack and you guys already have some of our databases, happy to share more, there is no PII.

**Comment by RaduBerinde** [comment] 2020-01-17 23:04
Just leaving a note to keep track of current status - I tried the `release-19.2` branch with the real data. I get the plan [above](https://github.com/cockroachdb/cockroach/issues/43958#issuecomment-575762424) which is a different lookup join but it performs in the same ballpark as a hinted merge join (maybe 25% slower). Just by looking at the plans and how many rows go into each operator, it's not clear that one plan will always be better than the other (it likely depends on configuration details).

**Comment by RaduBerinde** [comment] 2020-01-20 20:33
I tried the `release-19.2` branch again and now I get the old plan. They are likely close in estimated cost and minor differences in stats matter. I will keep looking at this.

**Comment by RaduBerinde** [comment] 2020-01-20 21:20
There are two things I see in the plans that contribute:
 - the optimizer thinks `is_banned = false` has selectivity 50% because we don't have a histogram on that column. If I create a statistic on this column, the plan changes to [the plan in this comment](https://github.com/cockroachdb/cockroach/issues/43958#issuecomment-575762424) which is much faster (even faster than the merge join). Maybe we should always get histograms for bool columns since they would be very cheap, what do you think @rytaft?
 - the full table scan cost for `apex_stats` is very high, compared to the costs added by the joins. The cost formula is roughly `cpuCostFactor * (numTableCols + numScannedCols) + seqIOCostFactor`, and because the table has 35 columns the former term is comparable to the second which should normally dominate. Not sure if there is much we can do about this in a point release.

**Comment by awoods187** [comment] 2020-01-21 14:57
I like the idea of adding histograms here if they dont incur a large cost. We'd probably need a benchmark to prove that to ourselves.

**Comment by rytaft** [comment] 2020-01-21 18:11
SGTM regarding histograms (already approved your PR)

**Comment by awoods187** [comment] 2020-03-25 14:40
@RaduBerinde can we close this issue now?

**Comment by RaduBerinde** [comment] 2020-03-25 15:06
Yeah, I filed #46560 to keep track of improving the scan cost.

**Closed by RaduBerinde** 2020-03-25 15:06 UTC
Labels: C-investigation
