### ISSUE TITLE
Compaction Queue Stuck

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#26634] opened 2018-06-12 14:26 UTC
I am running a 5 nodes cluster with 2.0.2, and this relate to this ticket #21824 .

Previously I though the Compaction Queue issue was fixed by the above ticket, but the queue suddenly bump and stuck. This is a production cluster with very little traffic and work load.

![compaction queue](https://user-images.githubusercontent.com/18466032/41296388-e08fe7e8-6e2a-11e8-9734-403fe7c05850.PNG)

![screencapture-192-168-28-11-8080-2018-06-12-10_24_17](https://user-images.githubusercontent.com/18466032/41296408-e768189c-6e2a-11e8-85c9-c8bf5fd9f44b.png)

**Comment by nvanbenschoten** [comment] 2018-06-12 15:34
@tschottdorf for triage. Was this already fixed?

**Comment by tschottdorf** [comment] 2018-06-12 20:40
Thanks @leomkkwan. Turns out this was fixed but not backported to the 2.0 release.

@bdarnell do you think this is worth backporting? The diff [is here](https://github.com/cockroachdb/cockroach/compare/release-2.0...tschottdorf:backport2.0-26039?body=Backport+2%2F2+commits+from+%2326039.%0A%0A%2Fcc+%40cockroachdb%2Frelease%0A%0A---%0A%0AThe+compactor+had+an+optimization+that+would+stop+the+compactor+loop+when%0Ano+work+was+to+be+done.%0A%0AUnfortunately%2C+the+condition+to+probe+this+was+incorrect.+Essentially%2C%0Awhenever+%2Aany%2A+work+had+been+done%2C+the+loop+stopped+and+would+not+reawaken%0Auntil+the+next+incoming+suggestion.+In+the+absence+of+such+a+suggestion%2C%0Athe+skipped+existing+suggestions+would+never+be+revisited%2C+and+thus+never%0Adiscarded.+This+created+confusion+as+it+kept+the+%22queued+bytes%22+metric+up.%0A%0ARefactor+the+code+so+that+instead+of+stopping%2C+the+loop+waits+for+the+max%0Aage+before+running+again+%28except+if+there+are+further+suggestions%29.%0A%0AIt%27s+hard+to+use+timers+correctly%2C+so+this+commit+should+be+scrutinized.+In%0Aparticular%2C+whether+it%27s+correct+to+call+%60t.Reset%60+in+a+select+that+does%0Anot+read+from+the+timer%27s+channel.%0A%0AThe+test+change+makes+%60make+test+PKG%3D.%2Fpkg%2Fstorage%2Fcompactor%60+fail+every%0Atime+on+my+machine+before+the+fix.%0A%0AI+would+suggest+not+backporting+this%2C+at+least+not+until+there+is+a%0Afollow-up+bugfix+that+needs+backporting+and+doesn%27t+apply+cleanly+on+top+of%0Athis+diff.%0A%0AFixes+%2321824.%0A%0ARelease+note+%28bug+fix%29%3A+Expired+compaction+suggestions+are+now+dropped+not%0Atoo+soon+after+they+expire.+Previously%2C+this+could+be+delayed+indefinitely.%0A&expand=1&title=backport-2.0%3A+compactor%3A+never+stop+the+loop).

**Comment by bdarnell** [comment] 2018-06-12 20:44
Yes, I think we should backport it.

**Comment by tschottdorf** [comment] 2018-06-12 21:18
Ok, it's merging now, which I think means it will be released in the upcoming v2.0.3 release.

@leomkkwan I'll close this when that has been confirmed. Please reopen when you've upgraded to v2.0.3 if this issue reappears. Thanks again for the report!

**Closed** 2018-06-14 09:39 UTC
