### ISSUE TITLE
stability: data corruption without crash

### ISSUE THREAD

**Issue by ravikumarsureshbabu** [cockroachdb/cockroach#13168] opened 2017-01-26 17:48 UTC
Hi @bdarnell 

I am trying to benchmark the optimal concurrency for cockroach DB.

The set up is same as mentioned in issue #13005 . I have modified concurrency's server.go to do each iteration 5 times. 
[server.go.zip](https://github.com/cockroachdb/cockroach/files/733093/server.go.zip)

My benchmark is a bank application. It does transfers between two randomly picked accounts. At the end of every second, it checks total or net balance in the balance in intact. While running this benchmark, abruptly I get net balance incorrect error.

I have used to binary https://benmisc.blob.core.windows.net/misc/cockroach.20170124
To run benchmark
- ./concurrency -start=30 -end=200 -step=5
    If it exits with the incorrect balance error. To verify it 
    - go to /benchmark/base
    - ./base 

 Not very consistently reproducible. It has happened to me twice. The benchmark takes a lot of time to complete. 

Thanks,
Ravi

**Comment by ravikumarsureshbabu** [comment] 2017-01-26 20:27
I got this error for the third time in a row. Seems like reproducible.

**Comment by bdarnell** [comment] 2017-01-27 03:50
It would be easier for us to examine and comment on your code if you'd post it to github instead of a zip file. I think the bug is here, in base/main.go:

```
		from := getAccount()
		to := getAccount()
		//from, to := rand.Intn(*numAccounts)+1, rand.Intn(*numAccounts)+1
		//log.Printf("from %v to %v", from, to)
		if from == to {
			continue
		}
		if useSystemAccount {
			// Use the first account number we generated as a coin flip to
			// determine whether we're transferring money into or out of
			// the system account.
			if from > *numAccounts/2 {
				from = systemAccountID
			} else {
				to = systemAccountID
			}
		}
```

`getAccount()` returns a random account ID in the range `[0..numAccounts]` (`systemAccountID` is 0). You check to see whether both account IDs are the same, but after you've done that check you may change one of them to zero. This makes it possible for both account IDs to be zero when you enter the transaction.

Inside the transaction, several things go wrong if both transaction IDs are the same: `toBalance` is uninitialized because the `switch` statement always matches the `fromBalance` case first, and you `UPDATE` the same row twice, clobbering the first update. 

There are ways to rewrite the transaction to work even when both account IDs are the same, but the simplest answer would be to move the check for `from == to` until after you have made any changes to these variables.

**Comment by ravikumarsureshbabu** [comment] 2017-01-27 04:21
Thanks for responding. I thought of putting the code itself, then file seemed too big to copy paste. I will do this from next time.

UseSystemAccount will be true on "high" contention case. But I was running it in "low" contention. So both of the accounts will not be same when I got this error.

**Comment by bdarnell** [comment] 2017-01-27 22:48
I wasn't talking about pasting your code into an issue; I was suggesting you upload it as a repo or a gist. And since the `concurrency` and `contention` wrapper binaries appear to just be wrappers around the `base` binary, can you provide instructions in terms of the `base` binary to simplify reproduction?

There is no `-end` flag in the `concurrency` package that you've provided. Did you mean `-max`? How long does it take to reproduce the error? I haven't seen it yet. 

You're missing an error check for `rows.Err()` after performing the `SELECT`, but I'm not sure if there is any error that could happen here and still allow the following UPDATEs to succeed.

Can you provide any more detail about what happens when the corruption occurs? Logs, packet captures, etc? (consider using `tcpdump` with the `-C` and `-W` options while running the test)

**Comment by ravikumarsureshbabu** [comment] 2017-01-28 00:10
Yeah, its max flag. sorry.

It takes lot of time. I started at concurrency 30. I saw the error at 60. 
What concurrency binary does is triggering the base at each concurrency. Since the error is not consistent, I cant point to specific case to run the base. :) 

I have the logs captured without any vmodule flags.
[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/736524/logs.tar.gz)

Even you want it with some specific flag, I can rerun the experiment with the flag.

**Comment by bdarnell** [comment] 2017-01-28 03:41
I've run this from 30-200 five times now without hitting an error. I think if you're still seeing "Bad entry in block" errors (#13005) indicating on-disk corruption that somehow made it past the checksum check, it's plausible that those same errors are sometimes resulting in transactional problems. It's probably better to figure that out first, and come back to this problem if it recurs in an environment that is not also seeing this other corruption.

**Comment by bdarnell** [comment] 2017-02-06 15:22
Now that #13005 has been isolated to a particular machine, do you still see this problem if that machine is removed from the cluster?

**Comment by ravikumarsureshbabu** [comment] 2017-02-07 06:51
Since I removed the machine from the cluster, I am not seeing either of the crashes. I am still running my benchmark. I will let you know if I get any :)

**Comment by dianasaur323** [comment] 2017-04-10 18:54
I'm going to close this out since it seems like @ravikumarsureshbabu is no longer seeing these crashes. Please feel free to re-open the issue if you are.

**Closed by dianasaur323** 2017-04-10 18:54 UTC
Labels: community-answered
