### ISSUE TITLE
Create composite index with non jsonb (like varchar) and jsonb

### ISSUE THREAD

**Issue by akshath** [cockroachdb/cockroach#26548] opened 2018-06-08 15:12 UTC
Hi Team, 

I am trying to create a composite index with non-jsonb (like varchar) and jsonb and I am getting error. 

I tried the following variations. Is this supported? I am using latest version of cockroach 2.0.2. Thank you.

`CREATE INDEX ON table_a (a, b DESC, c->>'d');`
`CREATE INDEX ON table_a (a, b DESC, (c->>'d'));`

**Comment by jordanlewis** [comment] 2018-06-08 15:27
Hi @akshath,

We don't support indexes with computed expressions at the moment. To make this work, you'll need to make a computed column on `c->>'d'` and put the index on that.

**Comment by akshath** [comment] 2018-06-08 18:02
Thanks, Jordan for the quick reply. Hope to see this supported in a future release.

**Comment by knz** [comment] 2018-07-21 14:41
This is a duplicate of #9682. We'll support this eventually.

**Closed by knz** 2018-07-21 14:41 UTC
