### ISSUE TITLE
ui: Styling on Jobs page empty state has transparency issues

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#47581] opened 2020-04-16 20:37 UTC
![image](https://user-images.githubusercontent.com/21692034/79504187-76d13980-8000-11ea-8647-27d3361fecc4.png)

On master as of yesterday. Looks like when we click the filter drop downs on the Jobs pages, we can see the empty state through the drop down.

**Comment by dhartunian** [comment] 2020-04-16 21:57
Just a note that this is to do w/ use of z-index on the "empty jobs" component. we should eliminate the z-index usage here which I believe was set for the background image.

**Comment by dhartunian** [comment] 2020-06-15 22:37
# Testing Requirements

* Screenshot in PR is enough here. This is too minor to add to specific tests.

**Comment by koorosh** [comment] 2020-06-16 13:59
It probably has been fixed with recent changes. 
Cannot reproduce (both in Chrome and Firefox)

<img width="929" alt="Screenshot 2020-06-16 at 16 46 39" src="https://user-images.githubusercontent.com/3106437/84784100-9a116880-aff2-11ea-8603-34fb5b210f6d.png">

**Closed** 2020-06-16 14:04 UTC
Labels: A-webui-layout-and-style, C-bug
