### ISSUE TITLE
Sentry: expr.go:148: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
(1) attached stack trace
  -- stack trace:
  |...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#136510] opened 2024-12-02 19:41 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6105893008/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6105893008/?referrer=webhooks_plugin)

Panic Message:

```
expr.go:148: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
(1) attached stack trace
  -- stack trace:
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:770
  | [...repeated from below...]
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.typeAnnotation.assertTyped
  | 	pkg/sql/sem/tree/expr.go:148
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Subquery).TypeCheck
  | 	pkg/sql/sem/tree/type_check.go:1764
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheck
  | 	pkg/sql/sem/tree/type_check.go:345
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.TypeCheckAndRequire
  | 	pkg/sql/sem/tree/type_check.go:355
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).analyzeExpr
  | 	pkg/sql/analyze_expr.go:34
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).planTenantSpec
  | 	pkg/sql/tenant_spec.go:63
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).LookupTenantInfo
  | 	pkg/sql/tenant_spec.go:148
  | github.com/cockroachdb/cockroach/pkg/crosscluster/physical.alterReplicationJobHook.func1
  | 	pkg/crosscluster/physical/alter_replication_job.go:220
  | github.com/cockroachdb/cockroach/pkg/sql.(*hookFnNode).startExec.func1
  | 	pkg/sql/planhook.go:194
  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
  | 	pkg/util/stop/stopper.go:498
  | runtime.goexit
  | 	src/runtime/asm_arm64.s:1222
Wraps: (4) ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
Error types: (1) *withstack.withStack (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
-- report composition:
*errutil.leafError: ReturnType called on TypedExpr with empty typeAnnotation. Was the underlying Expr type-checked before asserting a type of TypedExpr?
expr.go:148: *withstack.withStack (top exception)
*assert.withAssertionFailure
panic.go:770: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[pkg/util/stop/stopper.go#L497-L499](pkg/util/stop/stopper.go#L497-L499)
[pkg/sql/planhook.go#L193-L195](pkg/sql/planhook.go#L193-L195)
[pkg/crosscluster/physical/alter_replication_job.go#L219-L221](pkg/crosscluster/physical/alter_replication_job.go#L219-L221)
[pkg/sql/tenant_spec.go#L147-L149](pkg/sql/tenant_spec.go#L147-L149)
[pkg/sql/tenant_spec.go#L62-L64](pkg/sql/tenant_spec.go#L62-L64)
[pkg/sql/analyze_expr.go#L33-L35](pkg/sql/analyze_expr.go#L33-L35)
[pkg/sql/sem/tree/type_check.go#L354-L356](pkg/sql/sem/tree/type_check.go#L354-L356)
[pkg/sql/sem/tree/type_check.go#L344-L346](pkg/sql/sem/tree/type_check.go#L344-L346)
[pkg/sql/sem/tree/type_check.go#L1763-L1765](pkg/sql/sem/tree/type_check.go#L1763-L1765)
[pkg/sql/sem/tree/expr.go#L147-L149](pkg/sql/sem/tree/expr.go#L147-L149)
[GOROOT/src/runtime/panic.go#L769-L771](GOROOT/src/runtime/panic.go#L769-L771)
[src/runtime/asm_arm64.s#L1221-L1223](src/runtime/asm_arm64.s#L1221-L1223)
[pkg/util/stop/stopper.go#L497-L499](pkg/util/stop/stopper.go#L497-L499)
[pkg/sql/planhook.go#L193-L195](pkg/sql/planhook.go#L193-L195)
[pkg/crosscluster/physical/alter_replication_job.go#L219-L221](pkg/crosscluster/physical/alter_replication_job.go#L219-L221)
[pkg/sql/tenant_spec.go#L147-L149](pkg/sql/tenant_spec.go#L147-L149)
[pkg/sql/tenant_spec.go#L62-L64](pkg/sql/tenant_spec.go#L62-L64)
[pkg/sql/analyze_expr.go#L33-L35](pkg/sql/analyze_expr.go#L33-L35)
[pkg/sql/sem/tree/type_check.go#L354-L356](pkg/sql/sem/tree/type_check.go#L354-L356)
[pkg/sql/sem/tree/type_check.go#L344-L346](pkg/sql/sem/tree/type_check.go#L344-L346)
[pkg/sql/sem/tree/type_check.go#L1763-L1765](pkg/sql/sem/tree/type_check.go#L1763-L1765)
[pkg/sql/sem/tree/expr.go#L147-L149](pkg/sql/sem/tree/expr.go#L147-L149)
</details>

```
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 194
pkg/crosscluster/physical/alter_replication_job.go in pkg/crosscluster/physical.alterReplicationJobHook.func1 at line 220
pkg/sql/tenant_spec.go in pkg/sql.(*planner).LookupTenantInfo at line 148
pkg/sql/tenant_spec.go in pkg/sql.(*planner).planTenantSpec at line 63
pkg/sql/analyze_expr.go in pkg/sql.(*planner).analyzeExpr at line 34
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheckAndRequire at line 355
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheck at line 345
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*Subquery).TypeCheck at line 1764
pkg/sql/sem/tree/expr.go in pkg/sql/sem/tree.typeAnnotation.assertTyped at line 148
GOROOT/src/runtime/panic.go in runtime.gopanic at line 770
src/runtime/asm_arm64.s in runtime.goexit at line 1222
pkg/util/stop/stopper.go in pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2 at line 498
pkg/sql/planhook.go in pkg/sql.(*hookFnNode).startExec.func1 at line 194
pkg/crosscluster/physical/alter_replication_job.go in pkg/crosscluster/physical.alterReplicationJobHook.func1 at line 220
pkg/sql/tenant_spec.go in pkg/sql.(*planner).LookupTenantInfo at line 148
pkg/sql/tenant_spec.go in pkg/sql.(*planner).planTenantSpec at line 63
pkg/sql/analyze_expr.go in pkg/sql.(*planner).analyzeExpr at line 34
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheckAndRequire at line 355
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.TypeCheck at line 345
pkg/sql/sem/tree/type_check.go in pkg/sql/sem/tree.(*Subquery).TypeCheck at line 1764
pkg/sql/sem/tree/expr.go in pkg/sql/sem/tree.typeAnnotation.assertTyped at line 148
```

### Tags

| Tag | Value |
| --- | --- |
| Command | demo |
| Environment | development |
| Go Version | go1.22.8 X:nocoverageredesign |
| Platform | darwin arm64 |
| Distribution | CCL |
| Cockroach Release | v25.1.0-alpha.00000000-dev-749b563a7b5957b2db487c6e8e2fdeed8630103d |
| Cockroach SHA | 749b563a7b5957b2db487c6e8e2fdeed8630103d |
| # of CPUs | 10 |
| # of Goroutines | 468 |

**Comment by fqazi** [comment] 2024-12-03 18:13
Duplicate of https://github.com/cockroachdb/cockroach/issues/136339

**Closed by fqazi** 2024-12-03 18:13 UTC
Labels: C-bug, O-sentry, X-blathers-triaged, T-sql-foundations
