### ISSUE TITLE
Failed tests (10480): TestProgressWithDownNode 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3562] opened 2015-12-30 20:34 UTC
The following test appears to have failed:

[#10480](https://circleci.com/gh/cockroachdb/cockroach/10480):

```
W1230 20:33:14.429367 971 multiraft/multiraft.go:1138  failed to look up replica ID for range 1 (disabling replica ID check): storage/store.go:1705: store 3 not found as replica of range 1
I1230 20:33:14.433757 971 raft/raft.go:772  [group 1] 3 [commit: 14] ignored snapshot [index: 14, term: 6]
I1230 20:33:15.612449 971 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1230 20:33:15.612926 971 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1230 20:33:15.613138 971 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestProgressWithDownNode (1.39s)
	<autogenerated>:32: storage/client_raft_test.go:812: condition failed to evaluate within 1s: storage/client_raft_test.go:809: expected [5 5 5], got [5 5 0]
=== RUN   TestReplicateAddAndRemove
E1230 20:33:15.618162 971 gossip/gossip.go:180  different node IDs were set for the same gossip instance (2147483647, 1)
I1230 20:33:15.619195 971 multiraft/multiraft.go:578  node 1 starting
I1230 20:33:15.619879 971 storage/replica.go:1307  gossiping cluster id  from store 1, range 1
I1230 20:33:15.621524 971 raft/raft.go:446  [group 1] 1 became follower at term 5
I1230 20:33:15.621764 971 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1230 20:33:15.621927 971 multiraft/multiraft.go:998  node 1 campaigning because initial confstate is [1]
I1230 20:33:15.622010 971 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I1230 20:33:15.622087 971 raft/raft.go:459  [group 1] 1 became candidate at term 6
--
I1230 20:33:34.646922 971 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1230 20:33:34.647076 971 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.41s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.70s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	28.805s
=== RUN   TestBatchBasics
I1230 20:33:28.194761 1032 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1230 20:33:28.198146 1032 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1230 20:33:28.203266 1032 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-01-04 23:31
I can't reproduce this, and the code behind the first line of the logs has been changed substantially so I'm going to close this unless it turns up again.

**Closed by bdarnell** 2016-01-04 23:31 UTC
Labels: test-failure, TestProgressWithDownNode
