### ISSUE TITLE
sql: redact statement bundle

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#68570] opened 2021-08-07 03:07 UTC
Statement bundles contain several bits of unredacted user data, ranked in order from most to least sensitive

1. Histograms contain real data samples
2. Placeholders can contain real data samples
3. The statement can contain data
4. The schema could be sensitive

The histograms are very sensitive. Arbitrary user data is contained in them. We should redact these values, along with the placeholders.

Ideally, the redaction would be done using some method of obfuscation that preserves the meaning and usability of the histogram while removing the real data values.

Jira issue: CRDB-9095

**Comment by mgartner** [comment] 2021-08-14 00:57
I was under the impression that this is by design and something that users need to be aware of before they share statement bundles, just like a debug zip.

Perhaps the action item here is to make this clear in the [`EXPLAIN ANALYZE` docs](https://www.cockroachlabs.com/docs/stable/explain-analyze.html), like we do in the [`cockroach debug zip` docs](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html).

**Comment by rytaft** [comment] 2021-08-17 18:47
cc @ianjevans for the docs-todo @mgartner identified above

cc @vy-ton for prioritization of the top-level issue

**Comment by michae2** [comment] 2023-03-21 16:24
Marking this as fixed, as of v23.1. Further improvements will be tracked by https://github.com/cockroachdb/cockroach/issues/98817 and other issues.

**Closed by michae2** 2023-03-21 16:24 UTC
Labels: C-bug, T-sql-queries, N-followup
