### ISSUE TITLE
restore: OOM with TPC-H scale factor 10 data

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14776] opened 2017-04-11 01:12 UTC
build: 725ea82
config: 6-node cluster on 6 Azure [Standard_D3 VMs](https://azure.microsoft.com/en-us/blog/new-d-series-virtual-machine-sizes/) (proposer-evaluated KV enabled, as required by RESTORE)

What I did (I gave the full URL to @danhhz):

```
RESTORE tpch.* FROM 'azure://[redacted]/scalefactor-10';
```

It looks like the store got to ~24 GB, which is around where it should be. However, the OOM killer killed the `cockroach` instance on the node from which I initiated the RESTORE:

```
[1041637.873658] Out of memory: Kill process 42101 (cockroach) score 961 or sacrifice child
[1041637.879925] Killed process 42101 (cockroach) total-vm:24957948kB, anon-rss:13761140kB, file-rss:0kB
```

Here are the last runtime stats before the kill:
```
I170410 22:35:07.800302 107 server/status/runtime.go:227  [n1] runtime stats: 12 GiB RSS, 1320 goroutines, 7.7 GiB/1.5 GiB/9.6 GiB GO alloc/idle/total, 2.4 GiB/2.7 GiB CGO alloc/total, 42113.69cgo/sec, 2.53/0.23 %(u/s)time, 0.00 %gc (0x)
```

This seems like a *lot* of memory allocated by Go. All the other nodes have ~3-4 GiB RSS, which seems fine.

**Comment by petermattis** [comment] 2017-04-11 01:14
That is a lot of memory allocated by Go. Any chance you were running with `COCKROACH_MEMPROF_INTERVAL`?

**Comment by cuongdo** [comment] 2017-04-11 01:15
No, unfortunately not. Should I try again with that setting?

**Comment by cuongdo** [comment] 2017-04-11 01:15
Logs from the single crashing node:

[cockroach.stderr.gz](https://github.com/cockroachdb/cockroach/files/911834/cockroach.stderr.gz)

**Comment by petermattis** [comment] 2017-04-11 01:18
Yeah, if this is reproducible, heap profiles would be very useful in determining what is going on. That env var takes a duration like `10s`, `30s` or `1m`.

**Comment by danhhz** [comment] 2017-04-12 21:20
Seems like there a memory leak in encodeRaftCommand. @petermattis and I are looking into it

**Comment by danhhz** [comment] 2017-04-12 21:39
I've tried a number of heap profiles and nothing has jumped out.

@petermattis suspected the raftEntryCache, so I tried putting some logging on the number of entries and size it thought it held. It stayed between 15-30 entries and around 15MB

This reproduces locally in a few minutes (or on a worker if you don't want to melt your machine) with ```COCKROACH_PROPOSER_EVALUATED_KV=true COCKROACH_ENTERPRISE_ENABLED=true roachdemo -n 3```

followed by ```
CREATE DATABASE datablocks;
RESTORE datablocks.* FROM '[redacted]';
```

The memory growth appears is in "Go Total" on the admin ui. As of when I'm writing this, master doesn't rebalance leaseholders after making new ranges. This means the one node that gets all the Import requests (and then sends out the WriteBatches) is seeing all the memory growth.

**Comment by petermattis** [comment] 2017-04-12 21:50
@danhhz Can you get @a-robinson the full reproduction instructions?

**Comment by bdarnell** [comment] 2017-04-13 02:33
The raft entry cache can grow bigger than it "should" because one cache entry may be holding on to memory allocated from a larger slice (#13231).

However, I don't think memory allocated in encodeRaftCommand can make its way into the raft entry cache - I'm pretty sure it goes through a serialization/deserialization cycle between the two locations.

**Comment by petermattis** [comment] 2017-04-13 12:34
The memory from `encodeRaftCommand` is passed in to `raft.RawNode.Propose`. I thought it then came out in `raft.Ready.Entries` which would get added to the `raftEntryCache`.

The profile showed that there were 3GB allocated via `encodeRaftCommand` via ~3000 allocations. So this wasn't 1 entry being held on to. The 1MB entry size corresponds to the sizes of the `WriteBatch` operations performed by restore.

**Comment by petermattis** [comment] 2017-04-13 12:49
Another possibility for the leak is that we're not performing raft ready processing and raft entries are stuck in the `raft.unstable` log. I don't have a theory for how that is happening.

**Comment by a-robinson** [comment] 2017-04-14 03:18
I played with this a bunch earlier today, but didn't make any significant progress. I was having trouble repro-ing it consistently on my standard azworker -- the disk performance degradation was pretty bad and things got really cluttered up due to all the requests in the system waiting on them (the admin UI rarely worked as a result). I think it'd be worth using #14820 to see if that helps isolate the memory behavior from the terrible performance behavior.

The only particularly useful conclusion I can contribute is that entries are not getting stuck in raft's unstable log. I ran with this diff and the unstable log was always empty when new entries were getting appended to it:

```
diff --git a/github.com/coreos/etcd/raft/log_unstable.go b/github.com/coreos/etcd/raft/log_unstable.go
index 8ae301c..2ec21ed 100644
--- a/github.com/coreos/etcd/raft/log_unstable.go
+++ b/github.com/coreos/etcd/raft/log_unstable.go
@@ -101,6 +101,11 @@ func (u *unstable) restore(s pb.Snapshot) {
 }

 func (u *unstable) truncateAndAppend(ents []pb.Entry) {
+       var totalLen int64
+       for i := range u.entries {
+               totalLen += int64(len(u.entries[i].Data))
+       }
+       u.logger.Infof("in unstable.truncateAndAppend: %d entries, %d total length", len(u.entries), totalLen)
        after := ents[0].Index
        switch {
        case after == u.offset+uint64(len(u.entries)):
```

**Comment by petermattis** [comment] 2017-04-14 13:49
Ok, one theory shot down.

How do I download the backup data to my laptop so that I can reproduce locally?

**Comment by danhhz** [comment] 2017-04-14 14:47
@petermattis you want to download so you can repro offline? I assume azure has some tooling you can install to download the relevant folder, but I haven't had to use it yet (maybe @mjibson has). Another possibility is to do the RESTORE once onto a local (1 node?) cluster and then immediately use BACKUP to save it to your hard drive

**Comment by mjibson** [comment] 2017-04-14 19:02
I haven't done that on azure, not immediately sure how.

**Comment by danhhz** [comment] 2017-04-14 19:07
@petermattis did you ever get your repro set up for this?

**Comment by petermattis** [comment] 2017-04-14 19:38
> did you ever get your repro set up for this?

Yes.

**Comment by petermattis** [comment] 2017-04-14 19:57
@danhhz I think this fixes the leak, though I've only run short tests because I don't want to consume too much azure egress bandwidth:

```diff
~/Development/go/src/github.com/cockroachdb/cockroach/vendor (29ed000...) git diff
diff --git a/github.com/coreos/etcd/raft/log_unstable.go b/github.com/coreos/etcd/raft/log_unstable.go
index 8ae301c..d83b02c 100644
--- a/github.com/coreos/etcd/raft/log_unstable.go
+++ b/github.com/coreos/etcd/raft/log_unstable.go
@@ -83,7 +83,13 @@ func (u *unstable) stableTo(i, t uint64) {
        // only update the unstable entries if term is matched with
        // an unstable entry.
        if gt == t && i >= u.offset {
-               u.entries = u.entries[i+1-u.offset:]
+               // Clear the entries we are truncated so that the GC can reclaim any
+               // resources they were pointing to.
+               n := i + 1 - u.offset
+               for j := uint64(0); j < n; j++ {
+                       u.entries[j] = pb.Entry{}
+               }
+               u.entries = u.entries[n:]
                u.offset = i + 1
        }
 }
```

@danhhz Can you test this change? You'll have to apply the diff to the `etcd/raft` within the `vendor` directory.

Cc @bdarnell

**Comment by petermattis** [comment] 2017-04-14 20:07
Ugh, that patch breaks one of the `etcd/raft` tests which checks that entries are not modified after being added to `unstable`. I'm not sure yet of raft is depending on those semantics or not. @danhhz It is probably still safe to test that this fixes the leak.

**Comment by petermattis** [comment] 2017-04-14 20:23
https://github.com/coreos/etcd/issues/7746

**Comment by danhhz** [comment] 2017-04-17 15:16
@petermattis I tried this on lapis and on all nodes got
```
E170417 15:10:21.170403 65 vendor/github.com/coreos/etcd/raft/log.go:191  [n1,s1,r1/1:/{Min-System/},@c420bfa000] tocommit(5227) is out of range [lastIndex(5226)]. Was the raft log corrupted, truncated, or lost?
```

**Comment by petermattis** [comment] 2017-04-17 15:18
How long did that take to occur?

**Comment by danhhz** [comment] 2017-04-17 15:18
Immediately

**Comment by petermattis** [comment] 2017-04-17 15:19
And this is from a clean cluster? I ran with that patch several times for minutes without problems.

**Comment by danhhz** [comment] 2017-04-17 15:26
Ah, I did not wipe it. I'll try that

**Comment by petermattis** [comment] 2017-04-17 15:28
That error shouldn't occur, though.

**Comment by danhhz** [comment] 2017-04-17 15:30
Just repro'd with a wiped cluster

**Comment by petermattis** [comment] 2017-04-17 15:41
I'm on a plane right now and won't be able to look at this until later. Might want to get @bdarnell to take a look.

**Comment by danhhz** [comment] 2017-04-17 17:55
This even repros for me on the sqlccl tests. I've checked very carefully that I applied your patch correctly and it looks okay. Not really sure where to look from here

**Comment by a-robinson** [comment] 2017-04-17 19:22
This also trivially repros for me. I'll check into it on the assumption that @bdarnell hasn't gotten around to it yet.

**Comment by petermattis** [comment] 2017-04-17 19:42
Does it repro without my patch to `etcd/raft`? That seemed so innocuous. But it would be great to know that it is, in fact, unsafe to mutate the entries in `unstable` after they are committed.

**Comment by danhhz** [comment] 2017-04-17 19:44
Yes, applying that patch immediately causes lapis and at least one of the sqlccl tests to panic. Is there any chance you were testing it locally with a 1 node cluster? The panic stacktrace is in `stepFollower`

**Comment by a-robinson** [comment] 2017-04-17 19:46
It does not panic without the patch. It panics with the patch.

**Comment by petermattis** [comment] 2017-04-17 19:47
> Is there any chance you were testing it locally with a 1 node cluster?

There is a 100% chance I was doing that.

**Comment by a-robinson** [comment] 2017-04-17 20:24
If I had to make a guess at exactly what's going on here, it's that clearing out the entries' index fields is messing with the logic in `(*Replica).append` for determining what the last index persisted to storage was.

Even if that's not the exact issue, it looks like we need to avoid modifying entries that can be passed back to the application. It's pretty clearly unsafe.

**Comment by a-robinson** [comment] 2017-04-17 20:35
@danhhz, want to try out this diff?

```diff
diff --git a/github.com/coreos/etcd/raft/log_unstable.go b/github.com/coreos/etcd/raft/log_unstable.go
index 8ae301c3..474a7431 100644
--- a/github.com/coreos/etcd/raft/log_unstable.go
+++ b/github.com/coreos/etcd/raft/log_unstable.go
@@ -83,7 +83,10 @@ func (u *unstable) stableTo(i, t uint64) {
        // only update the unstable entries if term is matched with
        // an unstable entry.
        if gt == t && i >= u.offset {
-               u.entries = u.entries[i+1-u.offset:]
+               n := i + 1 - u.offset
+               newEntries := make([]pb.Entry, uint64(len(u.entries))-n)
+               copy(newEntries, u.entries[n:])
+               u.entries = newEntries
                u.offset = i + 1
        }
 }
```

**Comment by danhhz** [comment] 2017-04-17 21:21
@a-robinson (after some unrelated setbacks) testing your patch now. very early, seems okay, but it needs to run for a while before I can say for sure

**Comment by danhhz** [comment] 2017-04-17 21:38
Yeah this looks pretty good with alex's patch ![image](https://cloud.githubusercontent.com/assets/52528/25105866/9be82074-2394-11e7-9e8d-65d75212f96a.png)

**Comment by bdarnell** [comment] 2017-04-17 21:50
> If I had to make a guess at exactly what's going on here, it's that clearing out the entries' index fields is messing with the logic in (*Replica).append for determining what the last index persisted to storage was.

But `Replica.append` is called before `RawNode.Advance`, which is what calls `unstable.stableTo`. I'm not seeing anything that holds pointers to this array across that call to `Advance` (the `raftEntryCache` copies the `Entry` structs), so it seems like it should have been fine with @petermattis's patch. It's definitely safer to allocate a new buffer each time, though. Even though I can't tell why it's failing in our code, I could see other applications reusing the slice after `Advance`.

**Comment by bdarnell** [comment] 2017-04-17 22:00
Aha! Entry slices from `unstable` can also be written into `raftpb.Message.Entries`, and these are sent asynchronously. So it's possible that we send out garbage messages in some cases with @petermattis's patch. Let's get @a-robinson's patch submitted upstream.

**Comment by petermattis** [comment] 2017-04-17 22:03
Oy, vey! Always copying doesn't seem good for performance. I wonder if we can set `u.entries = nil` when `len(u.entries) == 0`.

**Comment by a-robinson** [comment] 2017-04-17 22:03
Will do. I was just running some of our benchmarks before sending it out.

**Comment by bdarnell** [comment] 2017-04-17 22:08
A busy range may never get to `len(u.entries) == 0`. I think we might need to be able to discard old entries even while the list is not empty (i.e. a check of len() vs cap() like I suggested in https://github.com/coreos/etcd/issues/7746#issuecomment-294366884)

**Comment by petermattis** [comment] 2017-04-18 00:49
@bdarnell Your proposal on coreos/etcd#7746 is fine by me. Upstream has been silently. Is there someone we should ping directly? Or will sending a PR spur some action?

**Comment by bdarnell** [comment] 2017-04-18 01:44
Send a PR and assign it to xiang90

**Comment by a-robinson** [comment] 2017-04-18 03:29
https://github.com/coreos/etcd/pull/7758

Although I went with `cap(u.entries) > 4*len(u.entries)` to try and reduce the number of allocations on busy raft groups. When things settle down, the array will always be cleared out when the number of entries drops to 0.

**Comment by a-robinson** [comment] 2017-04-18 04:16
The change in the PR handled the restore workload fine. What benchmark(s) would you recommend trying?

**Comment by xiang90** [comment] 2017-04-18 11:42
>  Upstream has been silently. Is there someone we should ping directly? Or will sending a PR spur some action?

sorry. i was in China for the last few days. so i did not really check github frequently enough. i already reviewed the pr from @a-robinson. :)

**Closed** 2017-04-18 17:38 UTC
