### ISSUE TITLE
colexec: performance hit with vec ON on TPCH Q20

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#45614] opened 2020-03-03 02:15 UTC
In the nightly run of `tpchvec` [roachtest](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/1777546:id/tpchvec/run_1/test.log) we see this:
```
... --vectorize=experimental_on 
...
I200302 09:14:36.383656 27 workload/tpch/tpch.go:465  [q20] returned 186 rows after 17.61 seconds
I200302 09:14:53.658895 27 workload/tpch/tpch.go:465  [q20] returned 186 rows after 17.27 seconds
I200302 09:15:11.355536 27 workload/tpch/tpch.go:465  [q20] returned 186 rows after 17.70 seconds

... --vectorize=off 
...
I200302 09:15:26.071300 12 workload/tpch/tpch.go:465  [q20] returned 186 rows after 13.09 seconds
I200302 09:15:38.858741 12 workload/tpch/tpch.go:465  [q20] returned 186 rows after 12.79 seconds
I200302 09:15:51.816203 12 workload/tpch/tpch.go:465  [q20] returned 186 rows after 12.96 seconds
...
... [q20] vec OFF was faster by 35.88%: 17.61s ON vs 12.96s OFF --- WARNING
```
This is a noticeable performance regression. Note that `workmem` was set to `64MiB` (which is the default, but it just so happened to be set so randomly).

One possible explanation is that vectorized engine spilled to disk whereas row-by-row engine didn't. Further investigation is needed.

**Comment by asubiotto** [comment] 2020-03-03 13:50
> One possible explanation is that vectorized engine spilled to disk whereas row-by-row engine didn't.

It's possible, but does this query need to spill to disk? It seems to me like there's only a final stage sort with 168 rows. If there were more rows, however, note that with a `64MiB` limit, the sorter effectively only has `32MiB` of work memory. #45593 will try to tune this to increase the work memory available.

Anyway. There's some investigation to be done. Also it's an interesting query because we're doing a filter based on a `DATE` and `INTERVAL`, which is what I was mentioning in the meeting yesterday. Might be interesting to see how #45626 affects this query, if at all.

**Comment by yuzefovich** [comment] 2020-03-04 17:03
In last night's run, `workmem` was set to `16MiB`, and the runtimes are comparable:
```
... --vectorize=experimental_on
...
I200304 09:18:45.067149 44 workload/tpch/tpch.go:465  [q20] returned 186 rows after 13.94 seconds
I200304 09:18:59.240655 44 workload/tpch/tpch.go:465  [q20] returned 186 rows after 14.17 seconds
I200304 09:19:13.020615 44 workload/tpch/tpch.go:465  [q20] returned 186 rows after 13.78 seconds

... --vectorize=off
...
I200304 09:19:28.115179 37 workload/tpch/tpch.go:465  [q20] returned 186 rows after 13.35 seconds
I200304 09:19:41.814452 37 workload/tpch/tpch.go:465  [q20] returned 186 rows after 13.70 seconds
I200304 09:19:55.979695 37 workload/tpch/tpch.go:465  [q20] returned 186 rows after 14.17 seconds
```
so spilling to disk only with vec ON might not be the issue.

**Comment by yuzefovich** [comment] 2020-03-18 02:22
In another [run](https://teamcity.cockroachdb.com/repository/download/Cockroach_Nightlies_WorkloadNightly/1811809:id/tpchvec/perf/run_1/test.log) with `64MB` work memory:
```
16:23:25 tpchvec.go:618: [q20] vec OFF was faster by 20.58%: 14.18s ON vs 11.76s OFF --- WARNING
vec ON times: [13.89 14.18 14.5]	 vec OFF times: [11.56 11.76 12.01]
```

**Comment by jordanlewis** [comment] 2020-03-20 05:46
I think this issue is a big deal. Locally, I get a 10 second difference on q20 - 13 seconds with off vs 23 seconds with auto. If we can't figure out what's going on here, I don't see why we can really ship with all of the new stuff by default.

I looked at pprof, which showed a ton of time in the colexec hash aggregator. I haven't reviewed that code carefully, but I'm nervous about it. I see that we're heavily using Go maps. That is a recipe for performance disaster.

I temporarily disabled the planning of colexec hash aggregators, and observed a major improvement in query latency - shaving off 12 seconds from the previous time, and beating rowexec again.

I think we'll probably want to consider disabling automatic planning of colexec hash aggregation for the release - a fix for this doesn't seem trivial.

**Comment by asubiotto** [comment] 2020-03-23 16:47
Agreed that this issue is a blocker for turning vectorized hash aggregations on by default. Let's take a look and figure out what the source of the performance regression is and make a decision based on that.

**Comment by yuzefovich** [comment] 2020-03-23 23:41
I found the source (at least, the main one) of inefficiency, so I'll pick this issue up.

**Closed** 2020-03-24 17:51 UTC
Labels: C-performance, S-3-productivity
