### ISSUE TITLE
rangefeed: Pushtxn in rangefeed returned abort, but txn may have been committed

### ISSUE THREAD

**Issue by pand5a** [cockroachdb/cockroach#104309] opened 2023-06-05 01:53 UTC
I don't know if it's appropriate to send it here, but I'm really troubled.

The RangeFeed relies on the return result of PushTxns (task. go: pushOldTxns) ABORTED to remove the tracked txn in UnresolvedIntentQueue, which depends on the correctness of PushTxn.

https://github.com/cockroachdb/cockroach/blob/9c2f65094e2aa121d8e9b15c90e4d657848f1667/pkg/kv/kvserver/rangefeed/task.go#L324-L336

 But in cmd_push_txn.go The “case txnID” case of [PushTxn ->SynthesizeTxnFromMeta ->CanCreateTxnRecord(replica_tscache.go)]  may return a transaction that has already been COMMITTED but has status=Abort, which may cause rts in the RangeFeed to advance incorrectly. Do I understand correctly?
https://github.com/cockroachdb/cockroach/blob/9c2f65094e2aa121d8e9b15c90e4d657848f1667/pkg/kv/kvserver/replica_tscache.go#L529-L543

Jira issue: CRDB-28452

Epic CRDB-27235

**Comment by aliher1911** [comment] 2023-06-09 11:56
I'm looking into this. Seems like the question would be can we have pending intent in the past when we see a transaction tombstone for committed transaction that we interpreted as abort.

**Comment by pand5a** [comment] 2023-06-12 01:46
Is it possible that this is the case:


It is possible that the rangefeed is built on a non majority replica, while the pushtxn in the rangefeed is sent at a fixed frequency, that is:

1. Leashold and Majority submitted it at ts1.

2. The rangefeed is built on a minority replica, and a pushtxn is issued on ts2 and a txnabort is returned. However, as the replica is asynchronous, so the commit is received on ts3 on this replica

**Comment by aliher1911** [comment] 2023-06-12 09:03
It looks like we just need a range feed running on a follower and that follower should be lagging behind on raft application. In that case it could try to push already committed transactions because it tries to compare txn timestamps from the intents it observes with wall clock (`now() - threshold`). Then it will drop the transaction from the list and advance its resolved timestamp.

We have a protection in rangefeed
https://github.com/cockroachdb/cockroach/blob/9c2f65094e2aa121d8e9b15c90e4d657848f1667/pkg/kv/kvserver/rangefeed/resolved_timestamp.go#L265-L273
which would cause node to panic if timestamp regression is detected to prevent any potential data inconsistency/loss on the client side.
And I can't find any evidence of panics generated by regressions like that which means it happens sufficiently infrequently.

To address it we may need to distinguish between abort types when resolving intents and in this particular case keep transaction and wait for intents to get resolved.

**Comment by aliher1911** [comment] 2023-06-15 20:13
I see what you mean. Didn't realize we skip intents when checking timestamp assertion. Even if we did, intents could arrive after checkpoint is out and even if we panic, client will not reread that data because of published checkpoint timestamp.

As for pts_cache, I don't think we need any extra info there. The problem seem to be that we know this special cause where transaction tombstone is present which should be a enough rare case, but we don't have a mechanism to surface this error to range feed processor easily without changing protocol. pts_cache can reside on any other node where transaction record was created.

Did you see this error actually happening?

**Comment by pand5a** [comment] 2023-07-19 07:01
Sorry for being too busy lately and slow to reply. 
by code review, I want to use one slow node and two fast nodes, which may trigger this issue. Because from a code perspective, this issue should exist. I will try it out some time.

**Comment by nicktrav** [comment] 2023-10-23 14:24
This is a correctness bug that's been here for some time. Therefore, we don't think this should be holding up the 23.2 release.

**Closed** 2024-01-23 23:52 UTC
Labels: C-bug, O-community, branch-master, branch-release-22.2, branch-release-23.1, A-kv-rangefeed, branch-release-23.2, C-technical-advisory, v23.1.15, v23.2.3, v23.2.1
