### ISSUE TITLE
circleci: failed tests: TestDockerNodeJS 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5898] opened 2016-04-06 19:13 UTC
The following test appears to have failed:

[#15968](https://circleci.com/gh/cockroachdb/cockroach/15968):

```
I160406 19:12:26.709349 acceptance/replication_test.go:66  found 2 replicas
I160406 19:12:26.809898 acceptance/cluster/localcluster.go:649  stopping
I160406 19:12:26.810109 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160406 19:12:26.810128 acceptance/cluster/localcluster.go:570  events monitor exits
I160406 19:12:26.811392 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container 532963a67c4d1c2f5aea16e37d1b7232e0aad10a4fadb75b9df8507d1c4b7c30: Container 532963a67c4d1c2f5aea16e37d1b7232e0aad10a4fadb75b9df8507d1c4b7c30 is not running
--- FAIL: TestDockerNodeJS (25.51s)
	testing.go:113: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestDockerPHP
I160406 19:12:28.963269 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160406 19:12:28.964864 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160406 19:12:29.537133 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.335769758
I160406 19:12:29.613776 acceptance/cluster/localcluster.go:532  events monitor starts
I160406 19:12:29.927091 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32866
  trace:     https://127.0.0.1:32866/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-06 19:16
Duplicate of #5879.

**Closed by petermattis** 2016-04-06 19:16 UTC
Labels: Robot, test-failure
