### ISSUE TITLE
Failed on the write benchmark.

### ISSUE THREAD

**Issue by absolute8511** [cockroachdb/cockroach#1043] opened 2015-05-16 03:56 UTC
I set up a cluster with 3 nodes and did some write benchmark. The benchmark will write keys from 0 to 1M with the value size 100bytes using different threads.
However, when the benchmark running, two of the nodes crashed.  First the node 1 crashed and then node 3, node 2 left but no write can be done.
PS: I am using the code from the master branch.

The node 1 log:
```
level="INFO" time="2015-05-15T21:12:03+08:00" file="server.go" line="111" msg="gossip: received 2 info(s) from 10.200.180.17:8080"
level="WARNING" time="2015-05-15T21:12:04+08:00" file="dist_sender.go" line="555" msg="failed to invoke EndTransaction: failed to send RPC: too many errors encountered (1 of 1 total): rpc to Node.EndTransaction timed out after 15s"
level="INFO" time="2015-05-15T21:12:04+08:00" file="retry.go" line="101" msg="routing EndTransaction rpc failed; retrying in 1s"
level="WARNING" time="2015-05-15T21:12:04+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: failed to send RPC: too many errors encountered (1 of 1 total): rpc to Node.Put timed out after 15s"
level="INFO" time="2015-05-15T21:12:04+08:00" file="retry.go" line="101" msg="routing Put rpc failed; retrying in 1s"
level="WARNING" time="2015-05-15T21:12:04+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: failed to send RPC: too many errors encountered (1 of 1 total): rpc to Node.Put timed out after 15s"
level="INFO" time="2015-05-15T21:12:04+08:00" file="retry.go" line="101" msg="routing Put rpc failed; retrying in 1s"
level="WARNING" time="2015-05-15T21:12:04+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: failed to send RPC: too many errors encountered (1 of 1 total): rpc to Node.Put timed out after 15s"
...
...
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing Put rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: key range \"716083\"-\"\" outside of bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing Put rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing Put rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing Put rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside of bounds of range \"\"-\"406729\""
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke Put: key range \"716083\"-\"\" outside of bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
...
...
on inconsistent read: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="WARNING" time="2015-05-15T21:12:29+08:00" file="store.go" line="1100" msg="async resolve on inconsistent read: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="WARNING" time="2015-05-15T21:12:29+08:00" file="store.go" line="1100" msg="async resolve on inconsistent read: replica node_id:\"\\001\" store_id:\"\\001\" attrs:<>  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
panic: MultiRaft.Events backlog reached limit

goroutine 34 [running]:
github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).sendEvent(0xc208032000, 0xcf5a60, 0xc20bd60b80)
        /data/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:182 +0xaf
...
...
goroutine 45566184 [select]:
github.com/cockroachdb/cockroach/rpc.sendOne(0xc20853e0a0, 0x37e11d600, 0xc2090023c0, 0x14, 0xf2b1e0, 0xc211be3900, 0xf17b80, 0xc209090e70, 0xc2088b4c60)
        /data/src/github.com/cockroachdb/cockroach/rpc/send.go:230 +0x9af
created by github.com/cockroachdb/cockroach/rpc.Send
        /data/src/github.com/cockroachdb/cockroach/rpc/send.go:168 +0x1578

goroutine 45566079 [select]:
github.com/cockroachdb/cockroach/rpc.sendOne(0xc2082941e0, 0x37e11d600, 0xc2086796c0, 0x14, 0xf2b1e0, 0xc208d2d900, 0xf17b80, 0xc208cc5960, 0xc208842960)
        /data/src/github.com/cockroachdb/cockroach/rpc/send.go:230 +0x9af
created by github.com/cockroachdb/cockroach/rpc.Send
        /data/src/github.com/cockroachdb/cockroach/rpc/send.go:168 +0x1578
```

log on node 2:
```
level="INFO" time="2015-05-15T21:12:03+08:00" file="client.go" line="165" msg=
"gossip: received 1 info(s) from 10.200.180.17:8080"
level="WARNING" time="2015-05-15T21:12:05+08:00" file="dist_sender.go" line="5
55" msg="failed to invoke InternalMerge: failed to send RPC: too many errors e
ncountered (1 of 1 total): rpc to Node.InternalMerge timed out after 15s"
level="INFO" time="2015-05-15T21:12:05+08:00" file="retry.go" line="101" msg="
routing InternalMerge rpc failed; retrying in 1s"
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg=
"error executing raft command Put: key range \"616070\"-\"\" outside of bounds
 of range \"\"-\"406729\""
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg=
"error executing raft command Put: key range \"516080\"-\"\" outside of bounds
 of range \"\"-\"406729\""
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: key range \"716083\"-\"\" outside of bounds of range \"\"-\"406729\""
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: key range \"816089\"-\"\" outside of bounds of range \"\"-\"406729\""
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: key range \"916094\"-\"\" outside of bounds of range \"\"-\"406729\""
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: key range \"416085\"-\"\" outside of bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="range_command.go" line="759" msg="range 1: new leader lease 1431695511.315682888,1-1431695521.965042591,0 @2:2"
level="INFO" time="2015-05-15T21:12:19+08:00" file="range.go" line="909" msg="gossiping first range from store 2, range 1"
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command InternalLeaderLease: cannot replace lease 1431695521.965042591,0-1431695540.559439898,0 @2:2 with 1431695511.316099405,0-1431695512.316099405,0 @1:1"
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="ERROR" time="2015-05-15T21:12:19+08:00" file="range.go" line="761" msg="error executing raft command Put: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" > "
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside of bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="tls.go" line="52" msg="connecting via tcp to bc-r6app6:8080 without TLS"
level="INFO" time="2015-05-15T21:12:19+08:00" file="client.go" line="148" msg="client bc-r6app6:8080 connected"
level="INFO" time="2015-05-15T21:12:19+08:00" file="client.go" line="222" msg="client bc-r6app6:8080 starting heartbeat"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside of bounds of range \"\"-\"406729\""
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside of bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"

...
...

level="INFO" time="2015-05-15T21:12:25+08:00" file="range_command.go" line="759" msg="range 2: new leader lease 1431695541.926260471,1-1431695543.600269318,0 @2:2"
level="INFO" time="2015-05-15T21:12:25+08:00" file="range_command.go" line="759" msg="range 1: new leader lease 1431695542.710263729,1-1431695544.676086426,0 @2:2"
level="WARNING" time="2015-05-15T21:12:25+08:00" file="store.go" line="1100" msg="async resolve on inconsistent read: conflicting write intents [{Key:\"\\x00\\x00meta2\\xff\\xff\" Txn:\"split range 1 at \\\"406729\\\"\" {id=62d7e0e4-8d97-45ef-bcf2-f886665e3a07 pri=1683323327, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1431695509.225826979,0 orig=1431695509.225826979,0 max=1431695509.475826979,0} XXX_unrecognized:[]}]: resolved? true"
level="WARNING" time="2015-05-15T21:12:25+08:00" file="store.go" line="1100" msg="async resolve on inconsistent read: conflicting write intents [{Key:\"\\x00\\x00meta1\\xff\\xff\" Txn:\"split range 1 at \\\"406729\\\"\" {id=62d7e0e4-8d97-45ef-bcf2-f886665e3a07 pri=1683323327, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1431695509.225826979,0 orig=1431695509.225826979,0 max=1431695509.475826979,0} XXX_unrecognized:[]}]: resolved? true"
level="WARNING" time="2015-05-15T21:12:25+08:00" file="store.go" line="1100" msg="async resolve on inconsistent read: conflicting write intents [{Key:\"\\x00\\x00meta2\\xff\\xff\" Txn:\"split range 1 at \\\"406729\\\"\" {id=62d7e0e4-8d97-45ef-bcf2-f886665e3a07 pri=1683323327, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1431695509.225826979,0 orig=1431695509.225826979,0 max=1431695509.475826979,0} XXX_unrecognized:[]}]: resolved? true"

```

log on node 3:
```
level="INFO" time="2015-05-15T21:12:03+08:00" file="client.go" line="165" msg=
"gossip: received 1 info(s) from 10.200.180.17:8080"
level="WARNING" time="2015-05-15T21:12:06+08:00" file="dist_sender.go" line="5
55" msg="failed to invoke InternalMerge: failed to send RPC: too many errors e
ncountered (1 of 1 total): rpc to Node.InternalMerge timed out after 15s"
level="INFO" time="2015-05-15T21:12:06+08:00" file="retry.go" line="101" msg="
routing InternalMerge rpc failed; retrying in 1s"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="5
55" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside o
f bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="r
outing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="tls.go" line="52" msg="
connecting via tcp to bc-r6app7:8080 without TLS"
level="INFO" time="2015-05-15T21:12:19+08:00" file="client.go" line="148" msg=
"client bc-r6app7:8080 connected"
level="INFO" time="2015-05-15T21:12:19+08:00" file="client.go" line="222" msg=
"client bc-r6app7:8080 starting heartbeat"
level="WARNING" time="2015-05-15T21:12:19+08:00" file="dist_sender.go" line="5
55" msg="failed to invoke InternalPushTxn: key range \"406729\"-\"\" outside o
f bounds of range \"\"-\"406729\""
level="INFO" time="2015-05-15T21:12:19+08:00" file="retry.go" line="94" msg="r
outing InternalPushTxn rpc failed; retrying immediately"

...
...
level="INFO" time="2015-05-15T21:12:27+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:27+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" > "
level="INFO" time="2015-05-15T21:12:27+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-15T21:12:27+08:00" file="dist_sender.go" line="555" msg="failed to invoke InternalPushTxn: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" > "
level="INFO" time="2015-05-15T21:12:27+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
panic: MultiRaft.Events backlog reached limit

goroutine 61 [running]:
github.com/cockroachdb/cockroach/multiraft.(*MultiRaft).sendEvent(0xc20822c160, 0xcf5a60, 0xc209540e80)
        /data/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:182 +0xaf
```

**Comment by vivekmenezes** [comment] 2015-05-18 14:58
Vincent,

We are right now working hard on getting cockroach to be a lot more stable
in a three node environment. Over the next two weeks or so we should make
some good progress towards that. Thank you so much for trying it out and we
appreciate you helping out. You will hear from us when we've completed a
lot more of our testing.

Thanks

**Comment by absolute8511** [comment] 2015-05-22 10:23
After some review, I found it was caused by the range split while writing. I set up 3 new nodes and just send the range split command will fail the cluster.

**Comment by spencerkimball** [comment] 2015-05-23 09:32
Looks like the proximate cause of your crash is the multiraft event backlog limit was reached. @bdarnell , any ideas?

**Comment by bdarnell** [comment] 2015-05-23 16:59
It's hard to say without more information. We don't have good backpressure throughout the system yet so it's not surprising that an aggressive benchmark could fill up the buffer. Or it could be some other problem, like the infinitely-retrying InternalPushTxn op that was just fixed. If the problem is triggered by a split then we should audit all of our internal retry mechanisms and make sure that they will pick up the new range ID (I know we have unit tests for this but as we've seen many times this week the DistSender behaves significantly differently from the LocalSender).

**Comment by absolute8511** [comment] 2015-05-24 13:55
I did the test with single write thread and it always failed while the write records reach about 500,000. So I think it may be range split issue. Maybe it has nothing about the aggressive benchmark. If any need, I hope I can do any help for you guys.

**Comment by absolute8511** [comment] 2015-05-26 03:31
some different logs from crash
```
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\002\" store_id:\"\\002\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
level="WARNING" time="2015-05-25T21:11:58+08:00" file="dist_sender.go" line="556" msg="failed to invoke InternalPushTxn: replica node_id:\"\\003\" store_id:\"\\003\" attrs:<attrs:\[r"hdd\" >  not leader; leader is node_id:\"\\001\" store_id:\"\\001\" attrs:<> "
level="INFO" time="2015-05-25T21:11:58+08:00" file="retry.go" line="94" msg="routing InternalPushTxn rpc failed; retrying immediately"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xab3c75]

goroutine 4969665 [running]:
github.com/cockroachdb/cockroach/storage.(*Store).resolveWriteIntentError(0xc2081a4000, 0xc20819fc00, 0xc20808ee10, 0x7f0ea72d9f98, 0xc2081f1180, 0x100000002, 0x0, 0x0)
        /data/src/github.com/cockroachdb/cockroach/storage/store.go:1231 +0x1305
github.com/cockroachdb/cockroach/storage.func·034()
        /data/src/github.com/cockroachdb/cockroach/storage/store.go:1107 +0x6d
created by github.com/cockroachdb/cockroach/storage.func·035
        /data/src/github.com/cockroachdb/cockroach/storage/store.go:1111 +0x3d0

```

**Comment by tschottdorf** [comment] 2015-05-26 03:45
@absolute8511 what `git rev-parse HEAD` is this running on?

**Comment by absolute8511** [comment] 2015-05-26 07:16
I am using the master branch, and maybe changed some logs to debug the issue. The actually code is below:
```
func (s *Store) resolveWriteIntentError(wiErr *proto.WriteIntentError, rng *Range, args proto.Request,
...
...
	wiErr.Resolved = true // success!

	// We pushed the transaction(s) successfully, so resolve the intent(s).
	for i, intent := range wiErr.Intents {
		pushReply := bReply.Responses[i].GetValue().(*proto.InternalPushTxnResponse)
		resolveArgs := &proto.InternalResolveIntentRequest{
			RequestHeader: proto.RequestHeader{
				// Use the pushee's timestamp, which might be lower than the
				// pusher's request timestamp. No need to push the intent higher
				// than the pushee's txn!
				Timestamp: pushReply.PusheeTxn.Timestamp,
				Key:       intent.Key,
				User:      UserRoot,
				Txn:       pushReply.PusheeTxn,
			},
		}
		resolveReply := &proto.InternalResolveIntentResponse{}
		// Add resolve command with wait=false to add to Raft but not wait for completion.
		waitForResolve := wait && i == len(wiErr.Intents)-1
		if resolveErr := rng.AddCmd(client.Call{Args: resolveArgs, Reply: resolveReply}, waitForResolve); resolveErr != nil {
			return resolveErr
		}
	}

	return wiErr
}

```

I found the `pushReply.PusheeTxn` is nil which cause the crash.

**Comment by absolute8511** [comment] 2015-05-26 07:32
The fix on etcd is another  crash  position I have found before.  https://github.com/coreos/etcd/commit/d58fac453dad14528f304e4d80c041c86f716c02

**Comment by tschottdorf** [comment] 2015-05-26 20:04
I'm going to need the exact commit (for any report to help with anything) - `master` changes every hour or so. We just fixed a bug that would cause this a couple of days ago in #1045.
Thanks,
Tobias

**Comment by tschottdorf** [comment] 2015-05-26 20:05
The first crash you posted is expected since the recovery scenario hasn't been benchmarked yet. We've just today increased the backlog size considerably though, so you'll likely not see this error again.

**Comment by absolute8511** [comment] 2015-05-27 12:26
After update the master today, the single write thread test no more crash. But the read will crash. After some review, I found it is caused by the concurrent access in the leader_cache.go
```
I0527 20:13:10.385489   31401 server.go:1775] http: panic serving 127.0.0.1:55723: runtime error: invalid memory address or nil pointer dereference
goroutine 16999039 [running]:
net/http.func·011()
        /usr/local/go/src/net/http/server.go:1130 +0xbb
container/list.(*List).MoveToFront(0xc20806df50, 0xc20f34abd0)
        /usr/local/go/src/container/list/list.go:169 +0x1e0
github.com/cockroachdb/cockroach/util/cache.(*baseCache).access(0xc20806df80, 0xc20f34aba0)
        /data/src/github.com/cockroachdb/cockroach/util/cache/cache.go:181 +0x43
github.com/cockroachdb/cockroach/util/cache.(*baseCache).Get(0xc20806df80, 0xd50440, 0xc20f1d8d80, 0x0, 0x0, 0x0)
        /data/src/github.com/cockroachdb/cockroach/util/cache/cache.go:156 +0x94
github.com/cockroachdb/cockroach/kv.(*leaderCache).Lookup(0xc20801f1a0, 0x2, 0x3)
        /data/src/github.com/cockroachdb/cockroach/kv/leader_cache.go:52 +0x80
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc20805f100, 0xc20818add0, 0x7f86a414bea0, 0xc20a4e7cc0, 0x7f86a414bef8, 0xc20e6e3960, 0x0, 0x0)
```

It is not enough to only use the read lock on the LRU cache since the read may modify the LRU list concurrently.

**Comment by vivekmenezes** [comment] 2015-05-27 13:26
Thanks for pointing this out Vincent. I do see the baseCache being modified
when you call Get() on it. Let me take a look at this.

**Comment by tamird** [comment] 2015-05-27 14:53
@vivekmenezes is this good to close?

**Comment by tschottdorf** [comment] 2015-05-27 15:10
Thanks @absolute8511, really appreciate your reports. Check out #1149 for our version of such a test - it's already uncovered a sleuth of related problems. If the specific issues above have been addressed, please close this issue (and  open another one if you run into something else).

**Closed** 2015-05-29 02:23 UTC
