### ISSUE TITLE
storage: LSM inversion during a decommission resulting in high latency

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#133182] opened 2024-10-22 18:54 UTC
**Describe the problem**

During a decommission, one of the nodes had an LSM inversion which resulted in a AC induced stall resulting in KV exec latency > 10s.

**To Reproduce**

This occured with the following run:

`COCKROACH_RANDOM_SEED=6457058786027231088 roachtest run perturbation/metamorphic/decommission`

The test configuration is:
```
2024/10/22 17:18:55 admission_control_latency.go:741: test variations are: 
seed: 6457058786027231088, 
fillDuration: 10m0s, 
maxBlockBytes: 1, 
perturbationDuration: 30m0s, 
validationDuration: 5m0s,
ratioOfMax: 0.500000, 
splits: 10000, 
numNodes: 12, 
numWorkloadNodes: 1, 
vcpu: 8, 
disks: 1, 
memory: high, 
leaseType: expiration, 
cloud: gce, 
perturbation: decommission{drain: false}
```

**Expected behavior**
The system should not hit LSM inversion due to a decommission. 

**Additional data / screenshots**
A few logs related to this failure from n11 (which encountered the issue):
The decommission starts at 15:06:19

[cockroach.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T15_11_13Z.015363.log](https://github.com/user-attachments/files/17480886/cockroach.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T15_11_13Z.015363.log)
[cockroach.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log](https://github.com/user-attachments/files/17480887/cockroach.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log)
[cockroach-pebble.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T15_06_39Z.015363.log](https://github.com/user-attachments/files/17480889/cockroach-pebble.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T15_06_39Z.015363.log)
[cockroach-pebble.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log](https://github.com/user-attachments/files/17480890/cockroach-pebble.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log)
[cockroach-kv-distribution.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log](https://github.com/user-attachments/files/17480894/cockroach-kv-distribution.baptistcockroachlabscom-1729608378-01-n13cpu8hm-0011.ubuntu.2024-10-22T14_48_24Z.015363.log)

**Additional context**
Decommission is a common operation and we don't expect a system running at 50% to hit IO overload due to a decommission.

Note that the test passes if `SET CLUSTER SETTING admission.kv.bulk_only.enabled = true` is set. 

See https://cockroachlabs.slack.com/archives/C06UFBJ743F/p1729616623255589 for more context.

Jira issue: CRDB-43498

**Comment by itsbilal** [comment] 2024-10-24 15:32
We actually snuck in a regression in this space a recent while back, when we were doing disaggregated storage and implementing the first iteration of IngestAndExcise. Our heuristic for applying a snapshot as a regular batch instead of as an ingest is now not used because `doExcise` is always true:

https://github.com/cockroachdb/cockroach/blob/bc31b91b23790433d77c46d332a6aba9f913c9d5/pkg/kv/kvserver/replica_raftstorage.go#L589

The fix for this should be pretty straightforward. I can work on that.

**Closed** 2024-10-24 18:55 UTC
Labels: C-bug, A-storage, A-admission-control, T-storage, branch-release-24.1, branch-release-24.2, branch-release-24.3, O-perturbation, v24.1.8, v24.2.6
