### ISSUE TITLE
Panic in scan request when running tpc-c on a 7 node 36 cpu cluster

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35186] opened 2019-02-25 18:15 UTC
**Describe the problem**

I hit an error when running tpc-c on a 7 node 36 cpu cluster resulting from a panic. 
```
Error: error in payment: EOF
Error:  exit status 1
```
```
* ERROR: [n5,client=172.31.33.239:54762,user=root] a SQL panic has occurred while executing "SELECT i_price, i_name, i_data FROM item WHERE i_id IN (8477, 8560, 12218, 14593, 16577, 22561, 28993, 72129, 76221, 81211, 81327, 82302) ORDER BY i_id": runtime error: index out of range
*
*
* ERROR: [n5,client=172.31.33.239:54762,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT _, _, _ FROM _ WHERE _ IN (_, _, __more10__) ORDER BY _; caused by runtime error: index out of range

goroutine 200965 [running]:
runtime/debug.Stack(0x39145c0, 0xc01f85d540, 0xc000000003)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x39145c0, 0xc01f85d540, 0xc0002b7300, 0x2fb78c0, 0xc0447495f0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:212 +0xa6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc051a6d000, 0x39145c0, 0xc01f85d540, 0x2d763e0, 0x552f010)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:714 +0x2dd
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc051a6d000, 0x39145c0, 0xc01f85d540)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:427 +0x61
panic(0x2d763e0, 0x552f010)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges.func1(0xc104a81f20, 0xc104a82210, 0xc104a82150, 0xc104a82208, 0xc104a81e87, 0xc104a81f08, 0xc104a81e8c)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:825 +0x50e
panic(0x2d763e0, 0x552f010)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/roachpb.(*ScanRequest).MarshalTo(0xc077b1f600, 0xc1268d5508, 0x13, 0x13, 0x15, 0x2, 0x11)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:10156 +0x17d
github.com/cockroachdb/cockroach/pkg/roachpb.(*RequestUnion_Scan).MarshalTo(0xc060fdcd10, 0xc1268d5506, 0x15, 0x15, 0xf2c4ce, 0xc060fdcd10, 0x17)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:13248 +0xdf
github.com/cockroachdb/cockroach/pkg/roachpb.(*RequestUnion).MarshalTo(0xc104a80840, 0xc1268d5506, 0x15, 0x15, 0x17, 0xb6, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:13149 +0x73
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).MarshalTo(0xc00ad40a80, 0xc1268d5450, 0xcb, 0xcb, 0xcb, 0xcb, 0x3124fa0)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:14561 +0x246
github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).Marshal(0xc00ad40a80, 0x3124fa0, 0xc00ad40a80, 0x7f140cf293a0, 0xc00ad40a80, 0xc037d0e401)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:14536 +0x7f
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto.codec.Marshal(0x3124fa0, 0xc00ad40a80, 0xc1133b6920, 0x3, 0xc00007a570, 0xc00007a500, 0x7f140d07e3b0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/encoding/proto/proto.go:70 +0x19c
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.encode(0x7f140cf29040, 0x59bc888, 0x3124fa0, 0xc00ad40a80, 0xc0447493e0, 0x39403e0, 0x39153c0, 0x6, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/rpc_util.go:487 +0x5e
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*csAttempt).sendMsg(0xc03b9b3860, 0x3124fa0, 0xc00ad40a80, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:482 +0xca
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*clientStream).SendMsg(0xc00ad40b80, 0x3124fa0, 0xc00ad40a80, 0xc000a08000, 0x319cd0a)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/stream.go:403 +0x43
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.invoke(0x3914680, 0xc164a1d500, 0x319cd0a, 0x21, 0x3124fa0, 0xc00ad40a80, 0x3079360, 0xc17d1fa7e0, 0xc000a08000, 0xc0009d86c0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:75 +0xfe
github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingClientInterceptor.func1(0x3914680, 0xc164a1d500, 0x319cd0a, 0x21, 0x3124fa0, 0xc00ad40a80, 0x3079360, 0xc17d1fa7e0, 0xc000a08000, 0x32c2d38, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go:47 +0xb49
github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc.(*ClientConn).Invoke(0xc000a08000, 0x3914680, 0xc164a1d500, 0x319cd0a, 0x21, 0x3124fa0, 0xc00ad40a80, 0x3079360, 0xc17d1fa7e0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/vendor/google.golang.org/grpc/call.go:35 +0x109
github.com/cockroachdb/cockroach/pkg/roachpb.(*internalClient).Batch(0xc17c2fa698, 0x3914680, 0xc164a1d500, 0xc00ad40a80, 0x0, 0x0, 0x0, 0xc164a1d500, 0x1, 0x3914680)
	/go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.pb.go:9305 +0xd2
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).sendBatch(0xc044749380, 0x3914680, 0xc164a1d500, 0x1, 0x38e8380, 0xc17c2fa698, 0x0, 0x0, 0x100000001, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:199 +0x126
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext(0xc044749380, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x100000001, 0x1, 0x795f, 0x0, 0xc0e3436600, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:168 +0x130
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendToReplicas(0xc000880900, 0x3914680, 0xc164a1d500, 0xc000880950, 0x795f, 0xc1868f39a0, 0x3, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1363 +0x2d3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendRPC(0xc000880900, 0x3914680, 0xc164a1d500, 0x795f, 0xc1868f39a0, 0x3, 0x3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:416 +0x244
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendSingleRange(0xc000880900, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0e3436600, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:496 +0x221
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).sendPartialBatch(0xc000880900, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0e3436600, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:1139 +0x322
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).divideAndSendBatchToRanges(0xc000880900, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0e3436600, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:962 +0x8b3
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).Send(0xc000880900, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:710 +0x48b
github.com/cockroachdb/cockroach/pkg/kv.(*txnLockGatekeeper).SendLocked(0xc07bd5ed08, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:233 +0xe8
github.com/cockroachdb/cockroach/pkg/kv.(*txnMetricRecorder).SendLocked(0xc07bd5ecd0, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_metric_recorder.go:51 +0xa2
github.com/cockroachdb/cockroach/pkg/kv.(*txnCommitter).SendLocked(0xc07bd5ecc0, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_committer.go:44 +0x219
github.com/cockroachdb/cockroach/pkg/kv.(*txnSpanRefresher).sendLockedWithRefreshAttempts(0xc07bd5ec40, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_span_refresher.go:160 +0x83
github.com/cockroachdb/cockroach/pkg/kv.(*txnSpanRefresher).SendLocked(0xc07bd5ec40, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_span_refresher.go:101 +0xf9
github.com/cockroachdb/cockroach/pkg/kv.(*txnPipeliner).SendLocked(0xc07bd5ebc0, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_pipeliner.go:171 +0xf9
github.com/cockroachdb/cockroach/pkg/kv.(*txnIntentCollector).SendLocked(0xc07bd5eb80, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_intent_collector.go:101 +0x43d
github.com/cockroachdb/cockroach/pkg/kv.(*txnSeqNumAllocator).SendLocked(0xc07bd5eb68, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_seq_num_allocator.go:92 +0x23b
github.com/cockroachdb/cockroach/pkg/kv.(*txnHeartbeater).SendLocked(0xc07bd5eab8, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc1093e0300, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_interceptor_heartbeater.go:221 +0x27b
github.com/cockroachdb/cockroach/pkg/kv.(*TxnCoordSender).Send(0xc07bd5e900, 0x3914680, 0xc164a1d500, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn_coord_sender.go:698 +0x591
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).sendUsingSender(0xc000672580, 0x3914680, 0xc164a1d4d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:622 +0x119
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Send(0xc16bbbebd0, 0x3914680, 0xc164a1d4d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:790 +0x13c
github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).fetch(0xc088489520, 0x3914680, 0xc164a1d4d0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:242 +0x626
github.com/cockroachdb/cockroach/pkg/sql/row.(*txnKVFetcher).nextBatch(0xc088489520, 0x3914680, 0xc164a1d4d0, 0x1, 0x203059, 0x0, 0x0, 0xc000bb3da0, 0xc14de0f340, 0xc0392955e0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_batch_fetcher.go:326 +0x1dd
github.com/cockroachdb/cockroach/pkg/sql/row.(*kvFetcher).nextKV(0xc04b72c4d8, 0x3914680, 0xc164a1d4d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/kv_fetcher.go:71 +0x2ef
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).NextKey(0xc04b72c4a0, 0x3914680, 0xc164a1d4d0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:489 +0x82
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScanFrom(0xc04b72c4a0, 0x3914680, 0xc164a1d4d0, 0x38eefc0, 0xc088489520, 0x0, 0xe14e01)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:479 +0x97
github.com/cockroachdb/cockroach/pkg/sql/row.(*Fetcher).StartScan(0xc04b72c4a0, 0x3914680, 0xc164a1d4d0, 0xc16bbbebd0, 0xc0c546e000, 0xc, 0xc, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/fetcher.go:470 +0x1e7
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Start(0xc04b72c000, 0x3914680, 0xc164a1d410, 0x59bebe0, 0x2c6fc60)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:253 +0x271
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc04b72c000, 0x3914680, 0xc164a1d410)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:800 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc14de0f340, 0x3914680, 0xc164a1d410, 0x32be3e0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:623 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000612640, 0xc0ef216660, 0xc16bbbebd0, 0xc104a84998, 0xc135cb6580, 0xc051a6d520, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:252 +0x8ad
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000612640, 0x3914680, 0xc164a1ced0, 0xc051a6d520, 0xc0ef216660, 0xc16bbbebd0, 0x3916240, 0xc0fc420360, 0xc135cb6580)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:841 +0x227
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc051a6d000, 0x3914680, 0xc164a1ced0, 0xc051a6d460, 0x3, 0x7f13e6566430, 0xc0cf9cf4a0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1049 +0x278
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc051a6d000, 0x3914680, 0xc164a1ced0, 0xc051a6d460, 0x7f13e6566430, 0xc0cf9cf4a0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:898 +0x644
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc051a6d000, 0x3914680, 0xc164a1ced0, 0x391a180, 0xc112803f40, 0xc0d9a70b71, 0xa6, 0x0, 0xc0e7d69b80, 0x3, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:436 +0xd8c
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc051a6d000, 0x3914680, 0xc164a1ced0, 0x391a180, 0xc112803f40, 0xc0d9a70b71, 0xa6, 0x0, 0xc0e7d69b80, 0x3, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc051a6d000, 0x39145c0, 0xc01f85d540, 0xc0005c70b8, 0x5400, 0x15000, 0xc0005c7150, 0xc00ba4c560, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1241 +0x1439
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000bf1520, 0x39145c0, 0xc01f85d540, 0xc051a6d000, 0x5400, 0x15000, 0xc0005c7150, 0xc00ba4c560, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:429 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000bf1520, 0xc066ec4d00, 0xc04c4427d4, 0xc00ba4c560, 0x39145c0, 0xc01f85d540, 0xc051a6d000, 0x5400, 0x15000, 0xc0005c7150, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:331 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:314 +0x1040
```
**To Reproduce**
Normal steps for tpc-c (no partitioning)

**Environment:**
v2.2.0-alpha.20190211-325-geaad50f

**Comment by awoods187** [comment] 2019-02-25 18:16
[cockroach.log](https://github.com/cockroachdb/cockroach/files/2901885/cockroach.log)

**Comment by jordanlewis** [comment] 2019-02-25 18:19
@tbg looks like another reproduction of that protobuf corruption we saw a while ago.

**Comment by jordanlewis** [comment] 2019-02-25 18:20
Not sure if this really should be assigned to you.

**Comment by jordanlewis** [comment] 2019-02-25 18:32
<img width="696" alt="image" src="https://user-images.githubusercontent.com/43821/53359653-832c9b80-3901-11e9-9e8e-ad8ef4d78a0b.png">
<img width="606" alt="image" src="https://user-images.githubusercontent.com/43821/53359654-84f65f00-3901-11e9-990f-77723a35dc1d.png">

Hmm... @tbg I guess I'm being barred from assigning this to you. I thought you were looking at this last, was I mistaken?

**Comment by awoods187** [comment] 2019-02-25 19:03
Oh my bad! I misread and thought I had assigned it to the wrong person! My bad 😞

**Comment by tbg** [comment] 2019-02-26 12:06
The panic is familiar and occurs here:

https://github.com/cockroachdb/cockroach/blob/1bf315d52b18ca1ee890af7d36f225166eb00fc0/pkg/roachpb/api.pb.go#L14557-L14564

like always.

**Comment by tbg** [comment] 2019-02-26 13:04
https://github.com/cockroachdb/cockroach/issues/34241

**Closed** 2019-02-26 13:04 UTC
