### ISSUE TITLE
kv: investigate kv95 regression around Feb 18

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#62148] opened 2021-03-17 11:19 UTC
See https://groups.google.com/a/cockroachlabs.com/d/msgid/eng/CABz5gWE%3DsO75sEtqB3MjA6ZcDqzKk%3DQhoXLVsMXkUHbtmHVuzg%40mail.gmail.com?utm_medium=email&utm_source=footer (internal) and

https://roachperf.crdb.dev/?filter=&view=kv95%2Fenc%3Dfalse%2Fnodes%3D3&tab=aws (internal).

**Comment by erikgrinaker** [comment] 2021-03-22 15:55
The regression on Feb 18 was due to #59992, and was fixed by #61777. This was verified by cherry-picking the fix onto the initial PR merge, and showing that it recovered performance with `sampling=0`. Separate work is underway to improve performance with sampling enabled.

This means there were other performance regressions in the period after Feb 18 that counteracted #61777. Will open a separate issue for this.

**Closed by erikgrinaker** 2021-03-22 15:55 UTC
Labels: C-investigation, C-performance, GA-blocker
