### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestLogic

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5372] opened 2016-03-18 10:17 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/842946ff77b3de333f0df91c160b4d238867ecb0

Stress build found a failed test:

```
=== RUN   TestLogic
--- FAIL: TestLogic (0.00s)
	logic_test.go:769: No testfiles found (globs: [testdata/[^.]*])
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
1 runs completed, 1 failures, over 20s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-18 13:01
Duplicate of #5339.

**Closed by petermattis** 2016-03-18 13:01 UTC
Labels: Robot, test-failure
