### ISSUE TITLE
sql: `samplerProcessor` using 40% of CPU on cluster with 200k ranges

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#34792] opened 2019-02-11 20:01 UTC
I was performing some testing around determining the number of ranges that we can reliably create on a cluster. In one test, I created a 3-node cluster with 4 vCPU machines and performed 200k splits on a table. I then let it sit there.

I came back a little later to find that all three machines were using about 70% of their available CPU even with no load on the cluster. About 40% of this utilization was consistently allocated to `samplerProcessor.Run`.

![screen shot 2019-02-11 at 2 46 12 pm](https://user-images.githubusercontent.com/5438456/52589214-4e521c00-2e0c-11e9-8fbb-1d56fc645db1.png)

It appears that most of the work is due to byte slice comparisons in `DistSender`. Presumably this is due to a full table scan by the `tableReader`, which requires a `ScanRequest` to be divided 200k times. How is this supposed to work? Is the scan limited (probably not)? How often do we expect to kick these sampling runs off?

cc. @RaduBerinde @rytaft

**Comment by RaduBerinde** [comment] 2019-02-11 20:22
We shouldn't be recalculating stats in an idle cluster. We should kick off these runs once a node modifies more than 5% of the size of a table (well, it's probabilistic so on average). The scan is not limited.

Do you know how long it sat idle?

**Comment by nvanbenschoten** [comment] 2019-02-11 20:29
Only about 10 minutes at that point, but I just checked (~30 minutes later) and the issue persists.

**Comment by andy-kimball** [comment] 2019-02-12 22:38
We should scan the full table once at startup if there are no stats on that table yet. Thereafter, we should only rescan if 5% rows are update/deleted/inserted. You can use `SHOW JOBS` to see if/when `CREATE STATISTICS` jobs ran (should be once per table if no mutations are happening).

I assume this table was newly created. Did you insert rows, and if so, how many? Also, if you executed a table scan query against this table, do you see similar time and CPU being expended?

**Comment by nvanbenschoten** [comment] 2019-02-13 07:54
I went back to try to repro this and failed to observe the same thing, so I think my original report was wrong about the cluster being idle. I suspect that as soon as my 200k splits were done, my workload generator started writing data to the table. 

> Thereafter, we should only rescan if 5% rows are update/deleted/inserted.

How does this work for small tables? If I have a 20 row table, will we really kick off a `CREATE STATISTICS` job every time I update any row?

What about during bulk loading? I'd expect that for the first few minutes we'd be rescanning repeatedly without any other limiting mechanism.

> I assume this table was newly created. Did you insert rows, and if so, how many?

Yes, I was just running `workload run kv --init --splits=200000` on a 3-node cluster with 4-core machines. Once the splits completed, it began inserting rows as fast as possible with 8 threads.

> Also, if you executed a table scan query against this table, do you see similar time and CPU being expended?

I'm not sure, but I would expect so. Scanning across 200k ranges is going to be expensive no matter what we do. Do we take the expense of each stats computation into account in order to throttle the fraction of time that we're performing them or is it possible for the stats computations to fall behind foreground traffic to the point where we're always running them?

**Comment by rytaft** [comment] 2019-02-13 15:04
> How does this work for small tables? If I have a 20 row table, will we really kick off a `CREATE STATISTICS` job every time I update any row?

We don't actually try to refresh after every update. We aggregate the counts of updated rows in a background thread and trigger a refresh every minute-or-so. Only one automatic `CREATE STATISTICS` job can run at a time, so it could be more than a minute if stats for another large table are being refreshed.  It could also be less than a minute if the updates for this table are spread across multiple nodes, and another node triggers a refresh.

> What about during bulk loading? I'd expect that for the first few minutes we'd be rescanning repeatedly without any other limiting mechanism.

If you're using IMPORT or RESTORE, we would only refresh once at the end. INSERT could cause many refreshes if it's a large table, but we would refresh at most once per minute per node, and only one job can run at a time. 

> Do we take the expense of each stats computation into account in order to throttle the fraction of time that we're performing them or is it possible for the stats computations to fall behind foreground traffic to the point where we're always running them?

I'm going to add some throttling to automatic stats jobs in this next milestone so you shouldn't see the CPU utilization be quite so high. We should never "fall behind" since we have the mechanism described above of limiting refreshes to at most once per minute per node, with at most one job running at a time.

Thanks for these questions and for filing the issue! I'll play around with running the workload + splits and see if I uncover anything. Is there anything else I should know about how to reproduce this? I haven't tested much with a large number of splits so it's definitely possible that something weird is going on.

**Comment by nvanbenschoten** [comment] 2019-02-13 21:59
Thanks for the explanation! 

> I'm going to add some throttling to automatic stats jobs in this next milestone so you shouldn't see the CPU utilization be quite so high. We should never "fall behind" since we have the mechanism described above of limiting refreshes to at most once per minute per node, with at most one job running at a time.

So if I'm understanding this correctly, we'll never run more than one stats job at a time. However, if a single run of the job starts taking close to 60s, we could get in a position where one is always running. That should be fine for cases where the size of the table (and by extension, the cost it takes to change 5% of the table) is correlated to the cost of running one of these jobs. I guess the issue here is that the case where we have a large number of splits but relatively few rows in the table breaks this correlation. It's inexpensive to change 5% of the table but expensive to scan over it.

> Is there anything else I should know about how to reproduce this?

I don't think so, but feel free to ping me if you have any questions.

**Comment by rytaft** [comment] 2019-02-13 22:30
> we could get in a position where one is always running

Yea, that's pretty much true. But I have to imagine that this case of 200k splits would be pretty rare unless a table also had a ton of data, right? If there were a lot of data, the refreshes would be much rarer. At any rate, I'm hopeful that throttling will alleviate this issue regardless of the ratio of splits to data size.

I'll dig into this tomorrow and see what I can find. Thanks for the info!

**Comment by RaduBerinde** [comment] 2019-02-14 00:44
Would be interesting to know how much a full table scan takes in this case.

**Comment by rytaft** [comment] 2019-03-26 20:34
Finally had a chance to spend some time on this. I ran the experiment as described above, and let the workload run for 1.5 hours before killing it. When auto stats was running, the CPU utilization varied from 0-40% for the `samplerProcessor`. I mostly saw 10-30% whenever I checked `pprof`, presumably because throttling was usually partially enabled. Each `CREATE STATISTICS` run took about 25-30 minutes to complete. Closing this issue since it seems like the latest adaptive throttling changes that @RaduBerinde made are working as designed, and any performance hit due to stats is relatively minor and short-lived.

**Closed by rytaft** 2019-03-26 20:34 UTC
Labels: A-sql-planning, C-investigation
