### ISSUE TITLE
sql: `COUNT` has slow (linear) performance

### ISSUE THREAD

**Issue by alamaison** [cockroachdb/cockroach#7825] opened 2016-07-14 10:05 UTC
We run queries like `SELECT count(id) from jobs;` to be able to display the total number of entries when paginating (i.e. 'Showing 100 of 8945').  These queries appear to do a linear table scan, when I would have expected it to use the index and return in constant time:

```
explain select count(id) from jobs;
+-------+-------+--------------+
| Level | Type  | Description  |
+-------+-------+--------------+
|     0 | group | count(id)    |
|     1 | scan  | jobs@primary |
+-------+-------+--------------+
```

for a table with this schema

```
CREATE TABLE jobs(
    id TEXT UNIQUE NOT NULL PRIMARY KEY,
   ... other fields ...
);
CREATE INDEX jobs_index on jobs(id);
```

We get the same result (and slow performance) with `SELECT count(*) from jobs;` and `SELECT count(1) from jobs;`.  I would have expected all these queries to consult the index and execute in contstant time the way `SELECT MAX(id) from jobs;` does.

Is this behaviour intended? And is there a workaround or a better way?

```
I160712 17:29:36.471788 util/log/clog.go:998  [config] file created at: 2016/07/12 17:29:36
I160712 17:29:36.471788 util/log/clog.go:998  [config] running on machine: 15-09-29-08-58-36-0-i-11ae46a9-dev-cockroach
I160712 17:29:36.471788 util/log/clog.go:998  [config] binary: CockroachDB beta-20160629 (linux amd64, built 2016/06/29 19:26:55, go1.6.2)
I160712 17:29:36.471788 util/log/clog.go:998  [config] arguments: [/cockroach/cockroach start --insecure --store=/mnt/cockroach --host 10.56.87.23]
```

```
I160712 17:29:38.678525 util/log/clog.go:998  [config] file created at: 2016/07/12 17:29:38
I160712 17:29:38.678525 util/log/clog.go:998  [config] running on machine: 15-10-23-11-32-51-0-i-9a09ab22-dev-cockroach
I160712 17:29:38.678525 util/log/clog.go:998  [config] binary: CockroachDB beta-20160629 (linux amd64, built 2016/06/29 19:26:55, go1.6.2)
I160712 17:29:38.678525 util/log/clog.go:998  [config] arguments: [/cockroach/cockroach start --insecure --store=/mnt/cockroach --join 10.56.87.23:26257 --host 10.56.87.20]
```

```
I160712 17:29:40.877116 util/log/clog.go:998  [config] file created at: 2016/07/12 17:29:40
I160712 17:29:40.877116 util/log/clog.go:998  [config] running on machine: 15-10-23-11-32-39-0-i-9709ab2f-dev-cockroach
I160712 17:29:40.877116 util/log/clog.go:998  [config] binary: CockroachDB beta-20160629 (linux amd64, built 2016/06/29 19:26:55, go1.6.2)
I160712 17:29:40.877116 util/log/clog.go:998  [config] arguments: [/cockroach/cockroach start --insecure --store=/mnt/cockroach --join 10.56.87.23:26257 --host 10.56.87.50]
```

**Comment by alamaison** [comment] 2016-07-14 10:21
cc @csdigi

**Comment by tschottdorf** [comment] 2016-07-14 10:31
> We get the same result (and slow performance) with SELECT count(*) from jobs; and SELECT count(1) from jobs;. I would have expected all these queries to consult the index and execute in contstant time the way SELECT MAX(id) from jobs; does.

I'm not sure how it would use the index. The index only allows you to do a sorted scan. That helps you fox `MAX(id)` where you simply search the largest one from the top (i.e. you start at infinity and grab the first result you find in descending order), but counting is a different issue altogether - an index entry has no idea how many other values there are below it - that's a global property.

> Is this behaviour intended? And is there a workaround or a better way?

It certainly doesn't seem like unexpected behaviour to me. As for workarounds, I think pagination using an index would work best if from the starting point, you return N results and then the next page starts from the index entry which belongs to the last result returned from the current page.

Example: when paginating through a list of names, after you've received the first 25, you don't get to ask for entries 26 to 50, you ask for 25 more entries: `WHERE name > 'miller' LIMIT 25` if your previous page ended at 'miller'. That way, it can use the index (on `name`).
Maybe there's a different solution using "counts" only, but I suspect not. @RaduBerinde?

**Comment by csdigi** [comment] 2016-07-14 11:20
In the pagination example above, the ```COUNT``` is merely for the user to know how many items they are paging through. I would not have expected the index itself to be able to improve this situation (and in fact the ```MAX(id)``` would only work if we had strictly sequential IDs which is very unperformant in a distributed DB.

I would have maybe expected that something under the covers might be tracking the number of keys in each index / range which could be used to efficiently answer this question. I believe linear scan performance on ```COUNT``` is expected behaviour from a key/value store (such as BigTable, or Datastore) but not from a SQL database (where the "norm" is to have fast / constant time access to table metadata such as item count).

**Comment by tschottdorf** [comment] 2016-07-14 11:27
Keeping a consistent count of objects is likely difficult since the table may span across many nodes, and so most writes would have to update a non-local counter, resulting in unpleasant additional commit latencies.
What's likely more tractable is obtaining rough approximate counts on key ranges (at least as long as the number of shard metadata doesn't exceed what can be stored in memory). Knowing all the ranges the desired parts of the index cover, and knowing their approximate size plus some average size of the rows within, we could compute from that alone an approximation (reality would have to tell about the quality of this approximation).

In either case, with distributed SQL (currently in the works) `COUNT(*)` would be completely parallelized (but it's still not great to do a round trip to all shards for every client's paging request, though the result could presumably be cached).

**Comment by csdigi** [comment] 2016-07-14 12:49
An approximate count is all that is required for us (much in the same way as the interface for gmail uses it). While a distributed count is helpful the performance penalty will always be pretty high on it (and I would imagine the actual uses of having a strongly consistent count are not that many). If we ever wanted to refine the accuracy of our counts I (our tables are also append only) we could always keep one manually (and use some of the Datastore tricks like counter sharding to reduce write contention).

**Comment by RaduBerinde** [comment] 2016-07-14 13:46
The only way an index would help is that we know there is a 1-1 correspondence between rows and keys (whereas a primary table has a variable number of keys per row). So if we somehow were able to count the keys in a range more efficiently, we could use that to count the rows accurately; but we don't have that capability at this point.

Judging from a quick google search, the mileage varies a lot on how fast `SELECT COUNT(*) FROM table` works with other SQL databases. Though many of them have row count statistics available in table metadata; we do not (maintaining that is tricky in a distributed database without hindering performance).

**Comment by RaduBerinde** [comment] 2016-07-14 15:11
What I suggest as a possible workaround is to cache the value and only repeat the query every now and then.

You could use the database to store the cached key, here's an example:

```sql
CREATE TABLE cached_stuff (key STRING PRIMARY KEY, value INT, time TIMESTAMP);
UPSERT into cached_stuff VALUES ('t_count', (SELECT COUNT(*) FROM t), NOW());
```

When you need the value you can do
```sql
SELECT value, NOW() - time as age FROM cached_stuff WHERE key = 't_count';
```
to get back the value and the "age":
```
value	age
1    	1.085ms
```

If the age is more than a threshold (e.g. 10 seconds), then you can update the value by rerunning the `UPSERT` statement and read it again.

**Comment by alamaison** [comment] 2016-07-14 15:25
> I'm not sure how it would use the index. The index only allows you to do a sorted scan.

Naively, I was assuming an index had an associated length, `COUNT` of a primary key field was just a matter of returning the length of the primary key index.

Thanks for the suggested workaround.  It looks like some sort of caching is the way to go.

FWIW This isn't unique to CockroachDB: https://wiki.postgresql.org/wiki/Count_estimate

**Comment by tschottdorf** [comment] 2016-07-14 15:29
> Naively, I was assuming an index had an associated length, COUNT of a primary key field was just a matter of returning the length of the primary key index.

That's only an option for tables which are written in the order of ascending index and never get deleted from (and if that doesn't already reduce the possible use case to very little, it also has no chance of scaling out because each write needs to query the authoritatively "newest" row). :)

**Comment by tschottdorf** [comment] 2017-11-17 23:50
Work on generating approximate stats has begun as per https://github.com/cockroachdb/cockroach/pull/18399 and the PRs that ping it.

**Comment by arjunravinarayan** [comment] 2018-02-13 18:42
I would advocate for closing this issue. `COUNT` is and will have linear performance characteristics until we have consistent incrementally updated materialized views that can store the `COUNT`. As previous commenters have said, indexes don't really help cache counts unless you go all the way to more complex denormalizations like materialized views. 

Meanwhile, we've made considerable progress speeding up our scan performance in the upcoming release, although it still is linear in time with the size of the database (but perhaps less annoying now that its faster). Perhaps the last bit of work that we could do to deliver something that is constant time is to expose a view into our table statistics, with the appropriate caution and documentation that these statistics are approximate and inconsistent, but that's also larger scope than this issue.

**Comment by BrianSullivan1956** [comment] 2018-02-15 00:21
While Count is a linear operation, would it not be better that it scan the index rather than the table. 
This is particularly true when the index is narrow and the table is wide. 
While still be linear, it may end up reading a lot less ranges.

I'm guessing the current form of the optimizer is only looking at the expected number of rows?
Rather than Rows * Bytes processed?

**Comment by RaduBerinde** [comment] 2018-02-15 00:22
The current index selection code is rudimentary, but it does prefer scanning smaller indexes.

**Comment by arjunravinarayan** [comment] 2018-03-05 03:13
Closing this issue as there's nothing actionable we have to do on this now. The only answer that will truly give us a less than linear complexity at answering COUNT queries in a transactional fashion is materialized views. That is on our radar, but will not be implemented in 2018.

**Closed by arjunravinarayan** 2018-03-05 03:13 UTC
Labels: community-questions, performance

**Comment by solebox** [comment] 2020-02-23 13:36
> Keeping a consistent count of objects is likely difficult since the table may span across many nodes, and so most writes would have to update a non-local counter, resulting in unpleasant additional commit latencies.
> What's likely more tractable is obtaining rough approximate counts on (indexed) key ranges (at least as long as the number of shard metadata doesn't exceed what can be stored in memory). Knowing all the ranges the desired parts of the index covers, and knowing their approximate size plus some average size of the rows within, we could compute from that alone an approximation (reality would have to tell about the quality of this approximation).
> 
> In either case, with distributed SQL (currently in the works), `COUNT(*)` would be completely parallelized (but it's still not great to do a round trip to all shards for every client's paging request, though the result could presumably be cached).

how about just incrementing local counters and then give a sum from all the nodes that have the table? just ask for it and default to zero , and you solve it,  no latancy at all but a really good estimate
