### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6231] opened 2016-04-22 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/7330af43411417dc60927b5a4cee0ee715b2cadc

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x4612c9 m=0

goroutine 0 [idle]:
runtime.epollwait(0x4, 0x7ffcc248cb10, 0xffffffff00000080, 0xda8c07, 0xffffffff, 0x198040, 0x33, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:440 +0x19
runtime.netpoll(0x1168901, 0x0)
	/usr/local/go/src/runtime/netpoll_epoll.go:67 +0x94
runtime.findrunnable(0xc820015500, 0x0)
	/usr/local/go/src/runtime/proc.go:1955 +0x62c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820001c80)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7ffcc248d220)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcfd578, 0x1148e20, 0xb, 0xb, 0xb5be01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820042f08, 0xb5be20)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 34 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x11688a0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 71 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc820149ecc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820149ec8)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc820149ec0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc820412000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc820412000, 0x1148e98)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 24 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f0758050c08, 0x72, 0xc82041f800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820220060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820220060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820220000, 0xc82041f800, 0x400, 0x400, 0x0, 0x7f075808c050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820144058, 0xc82041f800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820afe000, 0x7f0758050f38, 0xc820144058, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820232000, 0xcfdd17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820232000, 0xc820676000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8202400c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8202400c0, 0xc820230038, 0x9, 0x9, 0xc81fff3e7a, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f0758094d90, 0xc8202400c0, 0xc820230038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f0758094d90, 0xc8202400c0, 0xc820230038, 0x9, 0x9, 0xc8201f02a8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820230038, 0x9, 0x9, 0x7f0758094d90, 0xc8202400c0, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820230000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201f0180, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc820440000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 8 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d6000, 0xc820682040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 9 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d6000, 0xc82012c4a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 10 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f0758050cc8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200633a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200633a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820063340, 0x0, 0x7f0758090a40, 0xc82025b140)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82012a0b8, 0xc820045ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82012a0b8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82009da00, 0x7f075804fd20, 0xc82012a0b8, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d6000, 0xc82012c4c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 11 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d6000, 0xc82012c640)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 12 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820168540)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820168540)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 13 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201f05d4)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201f05d0)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201f05d0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc820149ec0, 0xcfddf8)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc820149ec0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc820149ec0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8200633b0, 0xc820258280, 0xc82013e040, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:191 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201d6000, 0xc8201ea000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 14 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f0758050b48, 0x72, 0xc820896800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820255870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820255870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820255810, 0xc820896800, 0x400, 0x400, 0x0, 0x7f075808c050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82012a0c8, 0xc820896800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201ea120, 0x7f0758050f38, 0xc82012a0c8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201d0c00, 0xcfdd17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8201d0c00, 0xc820ac4000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8201e82a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8201e82a0, 0xc82046a038, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f0758094d90, 0xc8201e82a0, 0xc82046a038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f0758094d90, 0xc8201e82a0, 0xc82046a038, 0x9, 0x9, 0xc2faf4d1f30f4901, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82046a038, 0x9, 0x9, 0x7f0758094d90, 0xc8201e82a0, 0x58000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82046a000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820182d50, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820412090, 0xc820182de0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82009da00, 0x7f0758094de0, 0xc820412090)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82009da00, 0x7f0758094cb8, 0xc8201d0c00, 0x7f0758094d18, 0xc820ac02c0)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82009da00, 0x7f0758050ed8, 0xc82012a0c8)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 23 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820440000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 58 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820412090)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x4612c9
rdx    0x80
rdi    0x4
rsi    0x7ffcc248cb10
rbp    0x11692e0
rsp    0x7ffcc248cad0
r8     0x11692e0
r9     0xc820428009
r10    0xffffffff
r11    0x246
r12    0x853ce64
r13    0xa
r14    0x7
r15    0x8
rip    0x4612c9
rflags 0x246
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
103 runs so far, 0 failures, over 5s
215 runs so far, 0 failures, over 10s
325 runs so far, 0 failures, over 15s
435 runs so far, 0 failures, over 20s
543 runs so far, 0 failures, over 25s
660 runs so far, 0 failures, over 30s
770 runs so far, 0 failures, over 35s
880 runs so far, 0 failures, over 40s
993 runs so far, 0 failures, over 45s
1103 runs so far, 0 failures, over 50s
1209 runs so far, 0 failures, over 55s
1321 runs so far, 0 failures, over 1m0s
1432 runs so far, 0 failures, over 1m5s
1540 runs so far, 0 failures, over 1m10s
1655 runs so far, 0 failures, over 1m15s
1769 runs so far, 0 failures, over 1m20s
1880 runs so far, 0 failures, over 1m25s
1988 runs so far, 0 failures, over 1m30s
2098 runs so far, 0 failures, over 1m35s
2208 runs so far, 0 failures, over 1m40s
2314 runs so far, 0 failures, over 1m45s
2426 runs so far, 0 failures, over 1m50s
2532 runs so far, 0 failures, over 1m55s
2641 runs so far, 0 failures, over 2m0s
2753 runs so far, 0 failures, over 2m5s
2861 runs so far, 0 failures, over 2m10s
2970 runs so far, 0 failures, over 2m15s
3082 runs so far, 0 failures, over 2m20s
3192 runs so far, 0 failures, over 2m25s
3302 runs so far, 0 failures, over 2m30s
3411 runs so far, 0 failures, over 2m35s
3523 runs so far, 0 failures, over 2m40s
3633 runs so far, 0 failures, over 2m45s
3739 runs so far, 0 failures, over 2m50s
3849 runs so far, 0 failures, over 2m55s
3954 runs so far, 0 failures, over 3m0s
4060 runs so far, 0 failures, over 3m5s
4171 runs so far, 0 failures, over 3m10s
4278 runs so far, 0 failures, over 3m15s
4385 runs so far, 0 failures, over 3m20s
4496 runs so far, 0 failures, over 3m25s
4602 runs so far, 0 failures, over 3m30s
4712 runs so far, 0 failures, over 3m35s
4816 runs so far, 0 failures, over 3m40s
4927 runs so far, 0 failures, over 3m45s
5036 runs so far, 0 failures, over 3m50s
5140 runs so far, 0 failures, over 3m55s
5247 runs so far, 0 failures, over 4m0s
5352 runs so far, 0 failures, over 4m5s
5456 runs so far, 0 failures, over 4m10s
5562 runs so far, 0 failures, over 4m15s
5670 runs so far, 0 failures, over 4m20s
5779 runs so far, 0 failures, over 4m25s
5887 runs so far, 0 failures, over 4m30s
5991 runs so far, 0 failures, over 4m35s
6098 runs so far, 0 failures, over 4m40s
6199 runs so far, 0 failures, over 4m45s
6306 runs so far, 0 failures, over 4m50s
6413 runs so far, 0 failures, over 4m55s
6521 runs so far, 0 failures, over 5m0s
6625 runs so far, 0 failures, over 5m5s
6729 runs so far, 0 failures, over 5m10s
6831 runs so far, 0 failures, over 5m15s
6937 runs so far, 0 failures, over 5m20s
7043 runs so far, 0 failures, over 5m25s
7148 runs so far, 0 failures, over 5m30s
7252 runs so far, 0 failures, over 5m35s
7356 runs so far, 0 failures, over 5m40s
7460 runs so far, 0 failures, over 5m45s
7569 runs so far, 0 failures, over 5m50s
7668 runs so far, 0 failures, over 5m55s
7773 runs so far, 0 failures, over 6m0s
7881 runs so far, 0 failures, over 6m5s
7982 runs so far, 0 failures, over 6m10s
8083 runs so far, 0 failures, over 6m15s
8182 runs so far, 0 failures, over 6m20s
8282 runs so far, 0 failures, over 6m25s
8384 runs so far, 0 failures, over 6m30s
8482 runs so far, 0 failures, over 6m35s
8584 runs so far, 0 failures, over 6m40s
8683 runs so far, 0 failures, over 6m45s
8786 runs so far, 0 failures, over 6m50s
8886 runs so far, 0 failures, over 6m55s
8990 runs so far, 0 failures, over 7m0s
9094 runs so far, 0 failures, over 7m5s
9194 runs so far, 0 failures, over 7m10s
9297 runs so far, 0 failures, over 7m15s
9396 runs so far, 0 failures, over 7m20s
9499 runs so far, 0 failures, over 7m25s
9601 runs so far, 0 failures, over 7m30s
9705 runs so far, 0 failures, over 7m35s
9806 runs so far, 0 failures, over 7m40s
9905 runs so far, 0 failures, over 7m45s
10005 runs so far, 0 failures, over 7m50s
10105 runs so far, 0 failures, over 7m55s
10207 runs so far, 0 failures, over 8m0s
10310 runs so far, 0 failures, over 8m5s
10411 runs so far, 0 failures, over 8m10s
10510 runs so far, 0 failures, over 8m15s
10608 runs so far, 0 failures, over 8m20s
10708 runs so far, 0 failures, over 8m25s
10810 runs so far, 0 failures, over 8m30s
10910 runs so far, 0 failures, over 8m35s
11007 runs so far, 0 failures, over 8m40s
11107 runs so far, 0 failures, over 8m45s
11205 runs so far, 0 failures, over 8m50s
11302 runs so far, 0 failures, over 8m55s
11404 runs so far, 0 failures, over 9m0s
11500 runs so far, 0 failures, over 9m5s
11601 runs so far, 0 failures, over 9m10s
11695 runs so far, 0 failures, over 9m15s
11797 runs so far, 0 failures, over 9m20s
11896 runs so far, 0 failures, over 9m25s
11997 runs so far, 0 failures, over 9m30s
12098 runs so far, 0 failures, over 9m35s
12199 runs so far, 0 failures, over 9m40s
12298 runs so far, 0 failures, over 9m45s
12396 runs so far, 0 failures, over 9m50s
12495 runs so far, 0 failures, over 9m55s
12597 runs so far, 0 failures, over 10m0s
12696 runs so far, 0 failures, over 10m5s
12792 runs so far, 0 failures, over 10m10s
12890 runs so far, 0 failures, over 10m15s
12991 runs so far, 0 failures, over 10m20s
13086 runs so far, 0 failures, over 10m25s
13185 runs so far, 0 failures, over 10m30s
13289 runs so far, 0 failures, over 10m35s
13386 runs so far, 0 failures, over 10m40s
13481 runs so far, 0 failures, over 10m45s
13575 runs so far, 0 failures, over 10m50s
13674 runs so far, 0 failures, over 10m55s
13765 runs so far, 0 failures, over 11m0s
13863 runs so far, 0 failures, over 11m5s
13956 runs so far, 0 failures, over 11m10s
14054 runs so far, 0 failures, over 11m15s
14156 runs so far, 0 failures, over 11m20s
14168 runs completed, 1 failures, over 11m21s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
