### ISSUE TITLE
kvserver: probe replication lag before lease transfer

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#99779] opened 2023-03-28 09:21 UTC
Before executing a lease transfer, we should make sure the would-be leaseholder is reasonably caught up, to avoid unavailability while we're waiting for it to apply the lease.

Jira issue: CRDB-26073

Epic CRDB-25206

**Comment by tbg** [comment] 2023-03-30 11:18
Duplicate of https://github.com/cockroachdb/cockroach/issues/96304, keeping that one because it has more details. Moving the Epic over.

**Closed by tbg** 2023-03-30 11:18 UTC
Labels: C-enhancement, A-kv, T-kv-replication
