### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6260] opened 2016-04-23 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/18d9f805a6ec17edc9f027e5f4853291db2c47c0

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x461141 m=0

goroutine 0 [idle]:
runtime.futex(0x1170268, 0x0, 0x0, 0x0, 0x0, 0x116f810, 0x0, 0x0, 0x40fbf4, 0x1170268, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x1170268, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x1170268)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc82001ea00, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc82008d980)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7fff3e4fd7e0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xd03638, 0x114fca0, 0xb, 0xb, 0xb60701)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820045f08, 0xb60740)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 69 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8203ec120)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 39 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8000, 0xc8201694c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x116f720)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 68 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc82015294c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820152948)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc820152940, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc8200be000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc8200be000, 0x114fd18)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 14 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f04a16e42a8, 0x72, 0xc820037800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203f3870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203f3870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203f3810, 0xc820037800, 0x400, 0x400, 0x0, 0x7f04a16a0028, 0xc82007c080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201581c8, 0xc820037800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82019e630, 0x7f04a16e4998, 0xc8201581c8, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8208eec00, 0xd03e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8208eec00, 0xc820338000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820199f80)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820199f80, 0xc8208b64b8, 0x9, 0x9, 0x405763, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f04a16e8d30, 0xc820199f80, 0xc8208b64b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f04a16e8d30, 0xc820199f80, 0xc8208b64b8, 0x9, 0x9, 0xc8201e3a78, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8208b64b8, 0x9, 0x9, 0x7f04a16e8d30, 0xc820199f80, 0x20000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8208b6480, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201e3950, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8203844b0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 12 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f04a16e4428, 0x72, 0xc82006c400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82040a060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82040a060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82040a000, 0xc82006c400, 0x400, 0x400, 0x0, 0x7f04a16a0028, 0xc82007c080)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820088018, 0xc82006c400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc82039e000, 0x7f04a16e4998, 0xc820088018, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820862000, 0xd03e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820862000, 0xc82089a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820010840)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820010840, 0xc8208ae0f8, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f04a16e8d30, 0xc820010840, 0xc8208ae0f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f04a16e8d30, 0xc820010840, 0xc8208ae0f8, 0x9, 0x9, 0xc29fee3b8083d501, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8208ae0f8, 0x9, 0x9, 0x7f04a16e8d30, 0xc820010840, 0xa1000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8208ae0c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820013c50, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8203ec120, 0xc820013ce0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc8200afa00, 0x7f04a16e8d80, 0xc8203ec120)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc8200afa00, 0x7f04a16e8c58, 0xc820862000, 0x7f04a16e8cb8, 0xc820868370)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc8200afa00, 0x7f04a16222e8, 0xc820088018)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 41 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8000, 0xc8201695e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 40 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f04a16e4368, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8208d93a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8208d93a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8208d9340, 0x0, 0x7f04a16222c0, 0xc8204020a0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc8201581b0, 0xc820046ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8201581b0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc8200afa00, 0x7f04a16e3480, 0xc8201581b0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8000, 0xc8201694e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 38 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8000, 0xc8208e42e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 42 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc82019a2a0)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc82019a2a0)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 43 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201e3d14)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201e3d10)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201e3d10, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc820152940, 0xd03eb8)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc820152940, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc820152940, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8208d93b0, 0xc8203f81e0, 0xc8201578f0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:191 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201c8000, 0xc8201df920)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 13 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8203844b0)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

rax    0xca
rbx    0x0
rcx    0x461143
rdx    0x0
rdi    0x1170268
rsi    0x0
rbp    0x1
rsp    0x7fff3e4fd640
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x81
r13    0xc8200b6c18
r14    0x15
r15    0x8
rip    0x461141
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
98 runs so far, 0 failures, over 5s
212 runs so far, 0 failures, over 10s
316 runs so far, 0 failures, over 15s
429 runs so far, 0 failures, over 20s
536 runs so far, 0 failures, over 25s
642 runs so far, 0 failures, over 30s
752 runs so far, 0 failures, over 35s
861 runs so far, 0 failures, over 40s
972 runs so far, 0 failures, over 45s
1082 runs so far, 0 failures, over 50s
1189 runs so far, 0 failures, over 55s
1297 runs so far, 0 failures, over 1m0s
1407 runs so far, 0 failures, over 1m5s
1517 runs so far, 0 failures, over 1m10s
1622 runs so far, 0 failures, over 1m15s
1731 runs so far, 0 failures, over 1m20s
1837 runs so far, 0 failures, over 1m25s
1948 runs so far, 0 failures, over 1m30s
2057 runs so far, 0 failures, over 1m35s
2163 runs so far, 0 failures, over 1m40s
2273 runs so far, 0 failures, over 1m45s
2381 runs so far, 0 failures, over 1m50s
2493 runs so far, 0 failures, over 1m55s
2604 runs so far, 0 failures, over 2m0s
2713 runs so far, 0 failures, over 2m5s
2822 runs so far, 0 failures, over 2m10s
2929 runs so far, 0 failures, over 2m15s
3037 runs so far, 0 failures, over 2m20s
3139 runs so far, 0 failures, over 2m25s
3246 runs so far, 0 failures, over 2m30s
3354 runs so far, 0 failures, over 2m35s
3463 runs so far, 0 failures, over 2m40s
3576 runs so far, 0 failures, over 2m45s
3681 runs so far, 0 failures, over 2m50s
3786 runs so far, 0 failures, over 2m55s
3892 runs so far, 0 failures, over 3m0s
4000 runs so far, 0 failures, over 3m5s
4110 runs so far, 0 failures, over 3m10s
4219 runs so far, 0 failures, over 3m15s
4326 runs so far, 0 failures, over 3m20s
4441 runs so far, 0 failures, over 3m25s
4549 runs so far, 0 failures, over 3m30s
4653 runs so far, 0 failures, over 3m35s
4756 runs so far, 0 failures, over 3m40s
4862 runs so far, 0 failures, over 3m45s
4967 runs so far, 0 failures, over 3m50s
5076 runs so far, 0 failures, over 3m55s
5178 runs so far, 0 failures, over 4m0s
5284 runs so far, 0 failures, over 4m5s
5385 runs so far, 0 failures, over 4m10s
5492 runs so far, 0 failures, over 4m15s
5599 runs so far, 0 failures, over 4m20s
5703 runs so far, 0 failures, over 4m25s
5807 runs so far, 0 failures, over 4m30s
5914 runs so far, 0 failures, over 4m35s
6016 runs so far, 0 failures, over 4m40s
6118 runs so far, 0 failures, over 4m45s
6224 runs so far, 0 failures, over 4m50s
6332 runs so far, 0 failures, over 4m55s
6437 runs so far, 0 failures, over 5m0s
6535 runs so far, 0 failures, over 5m5s
6641 runs so far, 0 failures, over 5m10s
6741 runs so far, 0 failures, over 5m15s
6840 runs so far, 0 failures, over 5m20s
6948 runs so far, 0 failures, over 5m25s
7050 runs so far, 0 failures, over 5m30s
7154 runs so far, 0 failures, over 5m35s
7255 runs so far, 0 failures, over 5m40s
7359 runs so far, 0 failures, over 5m45s
7457 runs so far, 0 failures, over 5m50s
7556 runs so far, 0 failures, over 5m55s
7658 runs so far, 0 failures, over 6m0s
7759 runs so far, 0 failures, over 6m5s
7862 runs so far, 0 failures, over 6m10s
7964 runs so far, 0 failures, over 6m15s
8067 runs so far, 0 failures, over 6m20s
8163 runs so far, 0 failures, over 6m25s
8259 runs so far, 0 failures, over 6m30s
8364 runs so far, 0 failures, over 6m35s
8461 runs so far, 0 failures, over 6m40s
8560 runs so far, 0 failures, over 6m45s
8656 runs so far, 0 failures, over 6m50s
8760 runs so far, 0 failures, over 6m55s
8859 runs so far, 0 failures, over 7m0s
8961 runs so far, 0 failures, over 7m5s
9059 runs so far, 0 failures, over 7m10s
9161 runs so far, 0 failures, over 7m15s
9260 runs so far, 0 failures, over 7m20s
9357 runs so far, 0 failures, over 7m25s
9459 runs so far, 0 failures, over 7m30s
9556 runs so far, 0 failures, over 7m35s
9654 runs so far, 0 failures, over 7m40s
9754 runs so far, 0 failures, over 7m45s
9855 runs so far, 0 failures, over 7m50s
9955 runs so far, 0 failures, over 7m55s
10058 runs so far, 0 failures, over 8m0s
10160 runs so far, 0 failures, over 8m5s
10259 runs so far, 0 failures, over 8m10s
10355 runs so far, 0 failures, over 8m15s
10457 runs so far, 0 failures, over 8m20s
10554 runs so far, 0 failures, over 8m25s
10658 runs so far, 0 failures, over 8m30s
10757 runs so far, 0 failures, over 8m35s
10858 runs so far, 0 failures, over 8m40s
10960 runs so far, 0 failures, over 8m45s
11063 runs so far, 0 failures, over 8m50s
11159 runs so far, 0 failures, over 8m55s
11260 runs so far, 0 failures, over 9m0s
11358 runs so far, 0 failures, over 9m5s
11462 runs so far, 0 failures, over 9m10s
11561 runs so far, 0 failures, over 9m15s
11662 runs so far, 0 failures, over 9m20s
11767 runs so far, 0 failures, over 9m25s
11867 runs so far, 0 failures, over 9m30s
11963 runs so far, 0 failures, over 9m35s
12064 runs so far, 0 failures, over 9m40s
12161 runs so far, 0 failures, over 9m45s
12260 runs so far, 0 failures, over 9m50s
12357 runs so far, 0 failures, over 9m55s
12458 runs so far, 0 failures, over 10m0s
12492 runs completed, 1 failures, over 10m2s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
