### ISSUE TITLE
QA: TSQuery incorrect results with the FOLLOWED BY (<->) operator

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#98864] opened 2023-03-17 16:17 UTC
From [TSVector and TSQuery QA](https://gist.github.com/msirek/2c4aef2a3c2038f6b9f3a6fa443ad6da),
The following returns `true` on Postgres, but `false` on CRDB:
```sql
SELECT 'fat cats ate fat rats' @@ 'fat <-> rats'::tsquery;
  ?column?
------------
     f
```

If the `<->` operator is unimplemented, an error message indicating such should be reported.

Jira issue: CRDB-25556

**Comment by mgartner** [comment] 2023-04-04 18:57
@jordanlewis any ideas what might be wrong here?

**Comment by jordanlewis** [comment] 2023-04-04 20:08
I don't observe this inconsistency...

```
jordan=# SELECT 'fat cats ate fat rats' @@ 'fat <-> rats'::tsquery;
 ?column?
----------
 f
(1 row)
```

The reason that this returns false is that casting a string directly to tsvector doesn't automatically add position lists to each of the terms. If you're expecting a tsvector to include position lists, you should either add them manually or use the `to_tsvector` builtin. (This is the same in CRDB as in Postgres)

```
jordan=# SELECT 'fat:1 cats:2 ate:3 fat:4 rats:5'::tsvector @@ 'fat <-> rats'::tsquery;
 ?column?
----------
 t
(1 row)

jordan=#

demo@127.0.0.1:26257/defaultdb> SELECT 'fat:1 cats:2 ate:3 fat:4 rats:5'::tsvector @@ 'fat <-> rats'::tsquery;
  ?column?
------------
     t
(1 row)

Time: 1ms total (execution 1ms / network 0ms)
```

I think this can be closed, @msirek did I miss something here?

**Comment by mgartner** [comment] 2023-04-12 13:05
I can't reproduce the inconsistency either. Closing.

**Closed by mgartner** 2023-04-12 13:05 UTC
Labels: C-bug, C-qa, GA-blocker, T-sql-queries, branch-release-23.1

**Comment by msirek** [comment] 2023-04-13 16:02
> I think this can be closed, @msirek did I miss something here?

I agree. Perhaps something changed since I tested this.
