### ISSUE TITLE
storage: requested entry at index is unavailable errors

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#15437] opened 2017-04-27 23:57 UTC
I'm seeing these entries periodically in the log with a very simple setup. To reproduce, run:

`$ rm -rf cockroach-data/ ; ./cockroach start --insecure --store=cockroach-data/1 --logtostderr`
`$ go run loadgen/kv/main.go --batch=10`

```
I170427 19:53:22.689866 24 server/status/runtime.go:225  [n1] runtime stats: 514 MiB RSS, 165 goroutines, 77 MiB/50 MiB/156 MiB GO alloc/idle/total, 264 MiB/344 MiB CGO alloc/total, 74954.75cgo/sec, 2.34/0.18 %(u/s)time, 0.00 %gc (25x)
E170427 19:53:25.952894 105 storage/queue.go:634  [raftlog,n1,s1,r12/1:/Table/51{-/1/10040…}] requested entry at index is unavailable
E170427 19:53:32.580697 105 storage/queue.go:634  [raftlog,n1,s1,r13/1:/{Table/51/1/1…-Max}] requested entry at index is unavailable
```

**Comment by bdarnell** [comment] 2017-04-28 02:23
Hmm. This is plausibly propEvalKV-related. It doesn't appear too harmful in this instance but I'll take a look to see what's going on.

**Comment by petermattis** [comment] 2017-04-28 13:25
Reproduces for me. I'll poke around while Ben is dealing with the RequestLease/CommandQueue issue.

**Comment by petermattis** [comment] 2017-04-28 13:38
The error is occurring during evaluation of a `TruncateLogRequest`. Specifically, this code:

```
	// args.Index is the first index to keep.
	term, err := cArgs.EvalCtx.Term(args.Index - 1)
	if err != nil {
		return EvalResult{}, err
	}
```

Seems very odd. I need to turn on some more logging to see what entries are being truncated.

**Comment by petermattis** [comment] 2017-04-28 14:13
```
I170428 09:49:47.593360 24 storage/raft_log_queue.go:234  [raftlog,n1,s1,r12/1:/{Table/51-Max}] truncating raft log 146305-146413: size=91523
I170428 09:49:47.657059 24 storage/raft_log_queue.go:234  [raftlog,n1,s1,r12/1:/{Table/51-Max}] truncating raft log 146413-146515: size=83892
I170428 09:49:47.657433 147296 storage/replica_raftstorage.go:173  [n1,s1,r12/1:/{Table/51-Max}] entries: unavailable
I170428 09:49:47.657472 147296 storage/replica_command.go:1854  [n1,s1,r12/1:/{Table/51-Max}] error getting term for index 146514 first-index=146413: requested entry at index is unavailable
```

So we're truncate the entries `146413` and `146414` and trying to find the term for `146414` is failing. Need more logging to find out what is going on with the missing Raft log entry. Lots of `+ 1` and `- 1` in this code. I'm suspicious we have an off-by-one somewhere.

**Comment by petermattis** [comment] 2017-04-28 14:23
Might be an off-by-one in `raftLogQueue`:

```
I170428 10:19:58.850549 147 storage/replica_raftstorage.go:470  [n1,s1,r12/1:/Table/51{-/1/15430…}] append 187693-187696
I170428 10:19:58.854777 231 storage/raft_log_queue.go:234  [raftlog,n1,s1,r12/1:/Table/51{-/1/15430…}] truncating raft log 187593-187698: size=89968
```

Seems like we're trying to truncate an entry that hasn't been written.

**Comment by petermattis** [comment] 2017-04-28 14:53
Not an off-by-one:

`I170428 10:47:57.109330 224 storage/raft_log_queue.go:125  [raftlog,n1,s1,r12/1:/Table/51{-/1/-4690…}] truncatable-index=211045 last-index=211037 quorum-index=211045 {"id":"1","term":6,"vote":"1","commit":211045,"lead":"1","raftState":"StateLeader","progress":{"1":{"match":211045,"next":211046,"state":"ProgressStateProbe"}}}`

The above is showing that we computed `211045` as the truncatable index even though the last Raft log entry we wrote was at index `211037`. We computed that larger index because `getQuorumIndex` returned `211045` due to the Raft status indicating that we've committed to that index. 

Huh? How is the commit index possibly past the index of the last Raft log entry we wrote? Paging @bdarnell.

**Comment by petermattis** [comment] 2017-04-28 15:05
`RaftStatus.Progress.Match` for the leader is updated when a message is proposed. For a single replica Raft group, `RaftStatus.Commit` is also updated at propose time. This seems weird, but I'm not sure if it is problematic. 

We can avoid the error message by ensuring we never try to truncate an entry that is after `LastIndex`.

**Comment by bdarnell** [comment] 2017-04-28 15:20
`RaftStatus` is quirky - it sometimes reflects the status that *will be true* after the next `Ready` is processed. It's the only way to get information about the leader's views of the followers, but for information about the local node it's sometimes inconsistent. We probably ought to be getting the `Commit` index from the last `HardState` instead of `RaftStatus`, and using `LastIndex` instead of `Progress.Match` for the local node.

**Closed** 2017-04-28 16:44 UTC
