### ISSUE TITLE
server/debug: TestAdminDebugRedirect timed out

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#108246] opened 2023-08-05 15:51 UTC
See https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11200270?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true&expandBuildTestsSection=true

cc @knz 

Jira issue: CRDB-30381

**Comment by ericharmeling** [comment] 2023-08-22 17:43
I have been unable to reproduce this failure on gceworker with a number of different test configurations.

This timeout might have something to do with the (brief) machine type switch for TC unit tests. A lot of tests were timing out after the switch from `t2d-standard-48` to `c2-standard-60`. We have since switched back to using `t2d-standard-48`, so I don't expect this timeout to occur again.

Some background: https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1691424868840639?thread_ts=1691421937.376619&cid=CJ0H8Q97C

**Comment by ericharmeling** [comment] 2023-08-22 18:05
Going to close this for now, with the explanation given above. If this test flakes again, we can do a more in-depth investigation.

**Closed by ericharmeling** 2023-08-22 18:05 UTC
Labels: C-test-failure, T-observability-inf, A-observability-inf
