### ISSUE TITLE
colexecwindow: emit rows early if the out col exceeds the mem limit

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#90645] opened 2022-10-25 19:18 UTC
roachtest.unoptimized-query-oracle/disable-rules=all/seed-multi-region [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7094346?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestNightlyGceBazel/7094346?buildTab=artifacts#/unoptimized-query-oracle/disable-rules=all/seed-multi-region) on master @ [11e299bb1bec2f5666658393f14c12ebe11cc4a4](https://github.com/cockroachdb/cockroach/commits/11e299bb1bec2f5666658393f14c12ebe11cc4a4):

```
test artifacts and logs in: /artifacts/unoptimized-query-oracle/disable-rules=all/seed-multi-region/run_1
(query_comparison_util.go:242).runOneRoundQueryComparison: failed to set random seed. 1702 statements run: dial tcp 35.237.205.248:26257: connect: connection refused
```
<p>Parameters: <code>ROACHTEST_cloud=gce</code>
, <code>ROACHTEST_cpu=4</code>
, <code>ROACHTEST_encrypted=false</code>
, <code>ROACHTEST_ssd=0</code>
</p>
<details><summary>Help</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

See: [How To Investigate \(internal\)](https://cockroachlabs.atlassian.net/l/c/SSSBr8c7)

</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*unoptimized-query-oracle/disable-rules=all/seed-multi-region.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/90504#issuecomment-1288906989_
      

Jira issue: CRDB-20869

**Comment by rytaft** [comment] 2022-10-25 19:20
This comment shows the memory profile: https://github.com/cockroachdb/cockroach/issues/90504#issuecomment-1289214321

**Comment by michae2** [comment] 2023-10-26 16:25
@DrewKimball given that the last failure was a year ago, do you think we can close this issue as stale? Or is what you described above still a problem?

**Comment by DrewKimball** [comment] 2023-10-26 16:44
>@DrewKimball given that the last failure was a year ago, do you think we can close this issue as stale? Or is what you described above still a problem?

It's still a problem, but it's not unique to window functions - other places, like cross-join, have the same problem. We could probably close this in favor of a more general tracking issue for cases like this in the vectorized engine.

**Comment by michae2** [comment] 2023-10-26 16:49
@DrewKimball would it make sense to consolidate these into #109309?

**Comment by DrewKimball** [comment] 2023-10-26 17:05
Maybe we could merge both into https://github.com/cockroachdb/cockroach/issues/87587 - they're all about handling the case where we go from small rows to large rows, or vice versa.

**Comment by DrewKimball** [comment] 2023-10-26 17:20
Closing as dupe of https://github.com/cockroachdb/cockroach/issues/109309

**Closed by DrewKimball** 2023-10-26 17:20 UTC
Labels: C-test-failure, O-roachtest, A-sql-vec, O-rsg, branch-master, T-sql-queries
