### ISSUE TITLE
sql/catalog: v22.2.9: referenced descriptor ID 105: descriptor not found

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105257] opened 2023-06-21 05:14 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4264555061/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4264555061/?referrer=webhooks_plugin)

Panic Message:

```
errors.go:83: referenced descriptor ID 105: descriptor not found
(1)
Wraps: (2) assertion failure
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.wrapError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:111
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:224
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/stored_catalog.go:308
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:191
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:88
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:336
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getSchemaByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:73
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:61
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:132
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:402
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).matchUDF
  | 	github.com/cockroachdb/cockroach/pkg/sql/drop_function.go:109
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).mustGetMutableFunctionForAlter
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_function.go:383
  | github.com/cockroachdb/cockroach/pkg/sql.(*alterFunctionSetOwnerNode).startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/alter_function.go:199
  | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:297
  | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:79
  | github.com/cockroachdb/cockroach/pkg/sql.walkPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:43
  | github.com/cockroachdb/cockroach/pkg/sql.startExec
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:521
  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:166
  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:187
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*batchInfoCollector).Init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:101
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:247
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).init
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:246
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:320
Wraps: (4) referenced descriptor ID 105
Wraps: (5) secondary error attachment
  | failed to find descriptor [105]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:172
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:142
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:109
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:224
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/stored_catalog.go:308
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:191
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:88
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:336
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).getSchemaByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:73
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/schema.go:61
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:132
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:402
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).matchUDF
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/drop_function.go:109
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planner).mustGetMutableFunctionForAlter
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/alter_function.go:383
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*alterFunctionSetOwnerNode).startExec
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/alter_function.go:199
  |   | github.com/cockroachdb/cockroach/pkg/sql.startExec.func2
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/plan.go:518
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/walk.go:112
  |   | github.com/cockroachdb/cockroa...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#757L756-L758](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/distsql_running.go#757L756-L758)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/vectorized_flow.go#320L319-L321](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/vectorized_flow.go#320L319-L321)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#291L290-L292](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#291L290-L292)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#246L245-L247](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#246L245-L247)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#92L91-L93](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#92L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#247L246-L248](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/flow_coordinator.go#247L246-L248)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/stats.go#101L100-L102](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/stats.go#101L100-L102)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#92L91-L93](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexecerror/error.go#92L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/stats.go#92L91-L93](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colflow/stats.go#92L91-L93)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/columnarizer.go#187L186-L188](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/colexec/columnarizer.go#187L186-L188)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_node_to_row_source.go#166L165-L167](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan_node_to_row_source.go#166L165-L167)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan.go#521L520-L522](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan.go#521L520-L522)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#43L42-L44](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#43L42-L44)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#79L78-L80](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#79L78-L80)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#297L296-L298](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#297L296-L298)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#112L111-L113](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/walk.go#112L111-L113)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan.go#518L517-L519](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/plan.go#518L517-L519)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/alter_function.go#199L198-L200](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/alter_function.go#199L198-L200)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/alter_function.go#383L382-L384](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/alter_function.go#383L382-L384)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/drop_function.go#109L108-L110](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/drop_function.go#109L108-L110)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#402L401-L403](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#402L401-L403)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#132L131-L133](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/schema_resolver.go#132L131-L133)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#61L60-L62](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#61L60-L62)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#73L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/schema.go#73L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#336L335-L337](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#336L335-L337)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#88L87-L89](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#88L87-L89)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#191L190-L192](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/descs/descriptor.go#191L190-L192)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/stored_catalog.go#308L307-L309](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/stored_catalog.go#308L307-L309)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_reader.go#224L223-L225](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_reader.go#224L223-L225)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#73L72-L74](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#73L72-L74)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#111L110-L112](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#111L110-L112)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#128L127-L129](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/internal/catkv/catalog_query.go#128L127-L129)
[GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595](GOROOT/src/runtime/asm_amd64.s#1594L1593-L1595)
[GOROOT/src/runtime/proc.go#233L232-L234](GOROOT/src/runtime/proc.go#233L232-L234)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6325L6324-L6326](GOROOT/src/runtime/proc.go#6325L6324-L6326)
[GOROOT/src/runtime/proc.go#6348L6347-L6349](GOROOT/src/runtime/proc.go#6348L6347-L6349)
[https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/errors.go#83L82-L84](https://github.com/cockroachdb/cockroach/blob/1b11ca676513ae073ea696c7cc3123d2684bc4bd/pkg/sql/catalog/errors.go#83L82-L84)
</details>

```
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 757
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 320
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).Run at line 291
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init at line 246
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*BatchFlowCoordinator).init.func1 at line 247
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).Init at line 101
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/stats.go in pkg/sql/colflow.(*batchInfoCollector).init at line 92
pkg/sql/colexec/columnarizer.go in pkg/sql/colexec.(*Columnarizer).Init at line 187
pkg/sql/plan_node_to_row_source.go in pkg/sql.(*planNodeToRowSource).Start at line 166
pkg/sql/plan.go in pkg/sql.startExec at line 521
pkg/sql/walk.go in pkg/sql.walkPlan at line 43
pkg/sql/walk.go in pkg/sql.(*planVisitor).visit at line 79
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal at line 297
pkg/sql/walk.go in pkg/sql.(*planVisitor).visitInternal.func1 at line 112
pkg/sql/plan.go in pkg/sql.startExec.func2 at line 518
pkg/sql/alter_function.go in pkg/sql.(*alterFunctionSetOwnerNode).startExec at line 199
pkg/sql/alter_function.go in pkg/sql.(*planner).mustGetMutableFunctionForAlter at line 383
pkg/sql/drop_function.go in pkg/sql.(*planner).matchUDF at line 109
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).ResolveFunction at line 402
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).LookupSchema at line 132
pkg/sql/catalog/descs/schema.go in pkg/sql/catalog/descs.(*Collection).GetImmutableSchemaByName at line 61
pkg/sql/catalog/descs/schema.go in pkg/sql/catalog/descs.(*Collection).getSchemaByName at line 73
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getDescriptorByName at line 336
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.(*Collection).getDescriptorByID at line 88
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 191
pkg/sql/catalog/internal/catkv/stored_catalog.go in pkg/sql/catalog/internal/catkv.(*StoredCatalog).EnsureFromStorageByIDs at line 308
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetDescriptorEntries at line 224
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 73
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 111
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.wrapError at line 128
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6325
GOROOT/src/runtime/proc.go in runtime.doInit at line 6348
pkg/sql/catalog/errors.go in pkg/sql/catalog.init at line 83
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v22.2.9 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.9 |
| Cockroach SHA | 1b11ca676513ae073ea696c7cc3123d2684bc4bd |
| # of CPUs | 16 |
| # of Goroutines | 274 |

Jira issue: CRDB-28944

**Comment by rafiss** [comment] 2023-06-27 18:05
Could it happen if a schema was dropped concurrently with altering the function?

For now, since we don't have enough information to reproduce it, we'll backlog this.

**Comment by rafiss** [comment] 2024-02-05 16:51
closing due to staleness

**Closed by rafiss** 2024-02-05 16:51 UTC
Labels: O-sentry, X-blathers-triaged, T-sql-foundations

**Comment by BuonOmo** [comment] 2024-09-05 07:01
I'm having a similar error when interacting with my db:

```
ERROR: referenced descriptor ID 28208: looking up ID 28208: descriptor not found
```

And I can't even drop it (same error).
