### ISSUE TITLE
sql: user seeing error --pq: empty slice--

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#19495] opened 2017-10-24 16:09 UTC
We've seen two reports from users seeing this error:

```pq: empty slice```

**Comment by lego** [comment] 2017-10-26 15:44
From gitter,

> When I commit a transaction, I'm getting the error "pq: empty slice." Any idea as to what generates this error?

https://gitter.im/cockroachdb/cockroach?at=59e93cd2d6c36fca3172e6c0

And another case,
> `SELECT mob FROM test_db.loan_consumer_application where maincontact = '...';`
> This is doing an index join between the `maincontact` index and the primary index.

https://gitter.im/cockroachdb/cockroach?at=59ef09205c40c1ba79dc7bb7
https://files.gitter.im/cockroachdb/cockroach/8Qf7/image.png

The error itself is thrown by `"util/encoding".PeekLength`.

This function is on a number of code paths involving interleaved tables, but also some others. In particular:
- Upserting rows (`upsertRowPKs`). If there are row conflicts found when using a secondary index and the table is interleaved. (Not sure what dictates secondary index usage here.)
- `ConvertBatchError`, which appears to be called when constraint failures are encountered. This is called on `tableUpdater.finalize`, `tableInserter.finalize`, and `tableUpserter.flush`.
- `EncDatumFromBuffer`.
  - Decoding composite encoding values from disk rows (i.e. hash joins pushed to disk due to the large data size)
  - Decoding key encoded datums from disk rows. This happens if a hash joiner requires a certain ordering.
  - `"pkg/server".refreshSettings`…?
- `StreamDecoder.GetRow`
  - distSQL processor input streams
  - valuesProcessor's output stream
    - `emptyPlan`
    - `createPlanForValues`

The tricky part is determining if this was an edge case or not. Most of the code paths are straightforward to hit, but if the bug doesn't reproduce it could have indirectly been something else, like
- Failed to send the or initialize the correct data
- Bad interleaved tables
- Failed to initialize the correct data columns (so we expect more data, e.g. bad families, bad distSQL processor input schema)

**Comment by lego** [comment] 2017-10-26 15:47
@kylemcgourty what query statements were in the transaction? Were any of them schema changes (`alter table`) or upserting (`INSERT INTO ... ON CONFLICT`, `UPSERT INTO `? Also, did you have any interleaved tables?

**Comment by jordanlewis** [comment] 2018-04-26 20:55
We have no details on this, so closing as unactionable.

**Closed by jordanlewis** 2018-04-26 20:55 UTC
Labels: X-invalid
