### ISSUE TITLE
Show backup should show the "locality" of the backup

### ISSUE THREAD

**Issue by livlobo** [cockroachdb/cockroach#74857] opened 2022-01-14 15:57 UTC
**Is your feature request related to a problem? Please describe.**
When a user tries to restore a backup, it will be helpful for them to know if that backup was a multi-region backup and what the locality of the backup is, so that they can configure the destination cluster, db, table with the right locality, if needed. This is also required for implementing a more intuitive flow for self-service restores in CockroachDB Cloud.

**Describe the solution you'd like**
Add a "locality type" column to the SHOW BACKUP output - that will indicate:
For clusters / DB backups
- Single region
- Multi-region

For table backups
- Regional by row
- Regional by table
- Global

Add a 'supported regions' column to SHOW BACKUP output - that will indicate the list of supported regions for that object type.

**Describe alternatives you've considered**
- Ask the user if they are trying to restore a MR DB/Table (not a great UX, prone to user error)
- Try to restore anyway, and interpret the error output (e.g. restoring descriptor 99 is not supported in a non multi-region db, etc.). This is also error prone because the error messages can't always be relied on to interpret whether that backup has multi-region objects within it. Also, it quite cumbersome to try to parse and analyze these.

Jira issue: CRDB-12296

**Comment by msbutler** [comment] 2022-08-05 13:17
duplicate of https://github.com/cockroachdb/cockroach/issues/79681#issuecomment-1173246410

**Closed by msbutler** 2022-08-05 13:17 UTC
Labels: C-enhancement, A-bulkio, E-starter, T-bulkio, E-quick-win
