### ISSUE TITLE
orms: Flyway error when creating tables on multi-region cluster 

### ISSUE THREAD

**Issue by damienhollis** [cockroachdb/cockroach#32515] opened 2018-11-20 21:29 UTC
**Describe the problem**

We currently use flyway to maintain our database schema and to date this has (generally) been working well.   Today we are testing using a cockroach cluster that spans several regions, including US, Australia, and Asia.  When flyway tries to create the schema, we get this error:

```
Unable to commit transaction
----------------------------
SQL State  : 40001
Error Code : 0
Message    : ERROR: restart transaction: HandledRetryableTxnError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=b084959f key=/Table/SystemConfigSpan/Start rw=true pri=0.04137014 iso=SERIALIZABLE stat=PENDING epo=0 ts=1542748620.756122558,1 orig=1542748616.503022366,0 max=1542748616.507674965,0 wto=false rop=false seq=781

```

If we run exactly the same script in a console it works fine.  And it works fine on a 3 node local cluster.  Also, absolutely nothing else is happening in the cluster.

Note: it is just the first flyway script that fails, which creates most of the tables, indexes and foreign keys.  Subsequent scripts (which are smaller), seem to work.

**To Reproduce**

1. create a new cluster that spans multiple regions.
2. create database
3. have flyway try to create tables within database

**Expected behavior**

Tables, indexes, etc to be created.

**Additional data / screenshots**

Currently this happens within a spring boot application, so it is a little hard to share.  I can try to create a simple example using JDBC that should exhibit the same behaviour.  Let me know if you need me to do that?

**Environment:**
 - CockroachDB version 2.1.1
 - Server OS: Linux
 - Client app JDBC

**Additional context**

If this does not work, we will need to look at different ways to maintain our schema, which would have significant impact on our project.

**Comment by drewdeally** [comment] 2018-11-20 22:00
It could be you have FK creation in the table DDL or as an alter table in the same transaction set.

**Comment by drewdeally** [comment] 2018-11-20 22:03
Please refer https://www.cockroachlabs.com/docs/v2.1/online-schema-changes.html#run-schema-changes-inside-a-transaction-with-create-table

**Comment by damienhollis** [comment] 2018-11-21 01:06
@drewdeally so I guess the difference is that flyway is trying to run the changes within a transaction? I wonder why this worked on a non-regionally distributed cluster?  I'll look at making changes as per the docs.

One question, the example uses:

SAVEPOINT cockroach_restart;
...
RELEASE SAVEPOINT cockroach_restart;

Is the SAVEPOINT important in this example?

**Comment by drewdeally** [comment] 2018-11-21 01:50
@damienhollis I sent it over for you to review.  If you can reproduce the issue as you suggested and share it here,  We can get a better insight.

**Comment by drewdeally** [comment] 2018-11-21 16:56
thanks

**Comment by tim-o** [comment] 2018-11-26 21:14
@damienhollis - `RETRY_SERIALIZABLE` errors can occur when we detect that an open transaction would conflict with the attempted schema change. As in [this example](https://www.cockroachlabs.com/docs/stable/demo-serializable.html#scenario-on-cockroachdb) . As Drew noted, the exception is for create table statements.

The `SAVEPOINT` and `RELEASE SAVEPOINT` statements are important since the former will automatically retry a transaction for you (see [here](https://www.cockroachlabs.com/docs/stable/savepoint.html) ).

It'd be helpful to see the actual script if you can share it - let me know if you need a private folder and I can set one up.

**Comment by damienhollis** [comment] 2018-11-26 21:19
@tim-o - thanks for the info.  If you provide a private folder, I'll share the script with you.

**Comment by tim-o** [comment] 2018-11-26 22:18
Actually, no need for further action on your part - I was out of the loop on a known issue, we're working with Flyway on this already.

**Comment by damienhollis** [comment] 2019-01-07 03:44
Do you have an update on this issue?  Currently flyway is not really useable with cockroach 2.1.  Is the issue related to cockroach or flyway - i.e. are you waiting on this issue: https://github.com/flyway/flyway/issues/2216

**Comment by vivekmenezes** [comment] 2019-01-07 16:09
https://github.com/cockroachdb/cockroach/issues/17698 is an open related issue for reference

**Comment by tim-o** [comment] 2019-01-07 16:14
Hey @damienhollis - flyway is targeting support for CRDB 2.1 in their 6.0 release, which I believe is due for release later this month.

**Comment by awoods187** [comment] 2019-03-12 17:06
This should work now with the most recent flyway https://flywaydb.org/blog/flyway-6.0.0-beta. Let me know how it works for you!

**Comment by jordanlewis** [comment] 2019-05-07 16:37
Closing - feel free to re-open if latest flyway still encounters the issue.

**Closed by jordanlewis** 2019-05-07 16:37 UTC
Labels: A-schema-changes, C-investigation, O-community
