### ISSUE TITLE
storage: inconsistent committed entries in Raft log

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#36353] opened 2019-03-29 21:58 UTC
I've got a scary one. 
Check out the tail of this `cockroach debug raft-log` on the leader, `n1`:
```
0.000000000,0 /Local/RangeID/7828/u/RaftLog/logIndex:18 (0x0169f71e94757266746c000000000000001200): Term:8 Index:18  by lease #4
proposer_replica:<node_id:1 store_id:1 replica_id:3 > proposer_lease_sequence:4 max_lease_index:4 replicated_eval_result:<timestamp:<wall_time:1553825991176579823 > delta:<last_update_nanos:1553825991176579823 live_bytes:34914540 live_count:104618 key_bytes:2126461 key_count:104618 val_bytes:32788079 val_count:104618 > add_sstable:<crc32:4108212582 > > write_batch:<data:"\000\000\000\000\000\000\000\000\000\000\000\000" > 
write batch:
```
Now look at it on any of the followers (say, `n2`):
```
0.000000000,0 /Local/RangeID/7828/u/RaftLog/logIndex:18: Term:6 Index:18  by lease #0
proposer_replica:<node_id:0 store_id:0 replica_id:0 > replicated_eval_result:<timestamp:<> delta:<> > 
```

**Same index, different term, very different data.**
The leader has what I have reason to believe is an AddSStable (so, there's sideloaded data in there), where the followers have a zero value, which seems to have come back from the data because there's a zero value at term 6 at index 12 (consistent with the leader). 
First question: are these zero values supposed to occur?

The range debug page claims that index 18 is a committed entry (18 is the "Last Index" and the "Commit" and "Applied" across all the replicas).
The log size reported by that page differs between the replicas - 33.7MB on the leader, 929B on the followers.

The way I started looking into this cluster and this range is because a `workload fixtures import` got blocked with one particular `AddSSTable` command being reproposed over and over again, and each time being refused by Raft because:
```
I190329 16:55:57.578308 1024 storage/replica_raft.go:420  [n1,s1,r7828/3:/Table/59/1/{1/4612-7/50294}] proposing command 3ece3298cc9d63af: 1 AddSstable
I190329 16:55:57.601162 1024 vendor/go.etcd.io/etcd/raft/raft.go:655  [n1,s1,r7828/3:/Table/59/1/{1/4612-7/50294}] 3 appending new entries to log would exceed uncommitted entry size limit; dropping proposal
```
There should be no uncommitted entries and so the command in question should be allowed to go through, but somehow the stats maintained by the Raft lib seem to have gotten corrupted. How that's related to the inconsistent log exactly, I'm not sure, but it has to be related somehow.
@ajwerner had a theory that perhaps the cache we have around raft log entries might be to blame, cause we don't cache entries with sideloaded data. So far a smoking gun was not found.

Given the leader's belief that some AddSSTable was applied for that range, it's seems interesting that a reproposal an AddSSTable is ongoing on that range. Cause my understanding about imports is that we only expect one AddSSTable per range - so if it succeeded, what's up with the reproposals?

[r7828 Range _ Debug _ Cockroach Console.pdf](https://github.com/cockroachdb/cockroach/files/3024650/r7828.Range._.Debug._.Cockroach.Console.pdf)
[n2-raft-log-7828.txt]
(https://github.com/cockroachdb/cockroach/files/3024648/n2-raft-log-7828.txt)
[n1-raft-log-7828.txt](https://github.com/cockroachdb/cockroach/files/3024649/n1-raft-log-7828.txt)
Debug zip:
https://drive.google.com/open?id=1bsJfYduXnZqJ7_u6dMBZDhSNyus_4qgw

The cluster is andrei-repro-1553814655-02-n7cpu72. The range in question is 7828.
I've extended the cluster, stopped the consistency queue so that it doesn't kill anything. The roachtest and workload invocation will timeout in a few hours, but hopefully they won't stop that command from being endlessly reproposed. And the cluster should be left alive. I've also copied all the data dirs away and gotten a debug.zip.
More looking to come.

cc @bdarnell @tbg @petermattis @nvanbenschoten @ajwerner

**Comment by ajwerner** [comment] 2019-03-29 22:44
From the logs at the beginning of the reproposals:
```
ip-172-31-42-166> W190329 02:20:51.287263 109391 storage/replica_write.go:224  [n1,s1,r7828/3:/Table/59/1/{1/4612-7/50294}] have been waiting 60.00s for proposing command AddSSTable [/Table/59/1/6/45676/0,/Table/59/1/7/50294).
This range is likely unavailable.
Please submit this message at

  https://github.com/cockroachdb/cockroach/issues/new/choose

along with

        https://yourhost:8080/#/reports/range/7828

and the following Raft status: {"id":"3","term":8,"vote":"3","commit":18,"lead":"3","raftState":"StateLeader","applied":18,"progress":{"1":{"match":18,"next":19,"state":"ProgressStateReplicate"},"2":{"match":18,"next":19,"state":"ProgressStateReplicate"},"3":{"match":18,"next":19,"state":"ProgressStateReplicate"}},"leadtransferee":"0"}  
```

**Comment by ajwerner** [comment] 2019-03-29 22:46
![Screenshot_2019-03-29 Custom Chart Debug Cockroach Console](https://user-images.githubusercontent.com/1839234/55266358-f011b900-5252-11e9-86d3-565947964ed4.png)

**Comment by ajwerner** [comment] 2019-03-29 23:55
My initial comments about the caching interactions with sideloading I no longer find compelling. The data we store in the cache are raftpb.Entries so there's no relationship to zero value storagepb.RaftCommand.

Going back to the above logging happened after 60s from 02:20:51.287263, which happens to be after just after a split was initiated but before `checked consistency for split` was reported, which makes sense as the command was likely being blocked from being by the split. 

Anyway, let's look at these splits that come in at roughly the same time on the parent range:
``` 
ip-172-31-42-166> I190329 02:19:39.259895 109574 storage/replica_command.go:246  [n1,s1,r64/5:/Table/{59-60}] initiating a split of this range at key /Table/59/1/12/59505 [r7789] (manual)                       
ip-172-31-42-166> I190329 02:19:39.266950 109544 storage/replica_command.go:246  [n1,s1,r64/5:/Table/{59-60}] initiating a split of this range at key /Table/59/1/27/48382 [r7790] (manual)                       
ip-172-31-42-166> I190329 02:19:39.284289 109574 storage/replica_command.go:368  [n1,s1,r64/5:/Table/59{-/1/12/59…}] checked consistency for split of r64-r7789                                                   
ip-172-31-42-166> I190329 02:19:39.362541 109475 storage/replica_command.go:246  [n1,s1,r64/5:/Table/59{-/1/12/59…}] initiating a split of this range at key /Table/59/1/7/50294 [r7823] (manual)                 
ip-172-31-42-166> I190329 02:19:39.452207 109486 storage/replica_command.go:246  [n1,s1,r64/5:/Table/59{-/1/12/59…}] initiating a split of this range at key /Table/59/1/1/4612 [r7824] (manual)                  
ip-172-31-42-166> I190329 02:19:39.452330 109373 storage/replica_command.go:246  [n1,s1,r64/5:/Table/59{-/1/12/59…}] initiating a split of this range at key /Table/59/1/5/99089 [r7825] (manual)                 
ip-172-31-42-166> I190329 02:19:43.255871 109486 storage/replica_command.go:246  [n1,s1,r64/5:/Table/59{-/1/7/502…}] initiating a split of this range at key /Table/59/1/1/4612 [r7828] (manual)                  
ip-172-31-42-166> I190329 02:19:43.258867 109373 storage/replica_command.go:246  [n1,s1,r64/5:/Table/59{-/1/7/502…}] initiating a split of this range at key /Table/59/1/5/99089 [r7829] (manual)                 
ip-172-31-42-166> I190329 02:19:50.345088 109475 storage/replica_command.go:368  [n1,s1,r64/5:/Table/59{-/1/1/4612}] checked consistency for split of r64-r7823                                                   
ip-172-31-42-166> I190329 02:19:51.584092 109486 storage/replica_command.go:368  [n1,s1,r64/5:/Table/59{-/1/1/4612}] checked consistency for split of r64-r7828     
```

My point is that the proposal happens essentially as soon as the split occurs, maybe there's something going on with sideloaded raft proposals and splits?

**Comment by tbg** [comment] 2019-03-30 08:32
I haven't checked this but sideloaded log entries can actually differ. One follower may have the sideloaded data inlined while another one has the sideloaded data sideloaded. This is because if a snapshot contains a sideloaded entry, we have to inline the payload

**Comment by tbg** [comment] 2019-03-30 12:28
Those two proposals don't look like they differ in the way I described.

**Comment by bdarnell** [comment] 2019-03-30 15:13
The leader's log entry has `Term:8 Index:18`, while the follower n2 has `Term:6 Index:18`. This isn't good. Raft log entries are properly identified by the combination of index and term, not the index alone, although the term is only included in certain parts of the protocol. The leader tracks the highest (index, term) pair for each follower and shouldn't tell the follower to commit index 18 unless its version of index 18 is from the right term.

For example, maybe n2 was the leader of term 6, and proposed an entry at index 18, but was deposed before that entry committed. Two more elections ensue, advancing the term to 8 and n1 becomes leader of that term. When n1 sends its first round of MsgApps for n8, it should detect that n2 has an entry 18 of the wrong term and instruct it to discard that portion of its logs instead of committing it.

The most likely scenario here is that we are synthesizing raft messages (perhaps for coalesced heartbeats) and only considering the commit index in places where we also need to look at the term. It's also possible (but less likely) that this bug is in etcd/raft. 

An empty entry at entry 18 and term 6 is curious. Because of some bootstrapping trickery we use, the first election for a new range occurs at term 6, and the log index starts at 10. A completely empty entry comes from inside raft, in one of two cases. A newly elected leader appends an empty entry, which for term 6 should always end up at index 11 (and because this comes from raft instead of us, I don't think there's any way it could end up getting proposed more than once to make it into index 18). If a config change is pending and a second change is proposed, the second entry is transformed into an empty one (but we can see that there were no successful config changes on this range). 

Looking at the full raft logs, they're printed differently (was one using a different version of `cockroach debug raft-log`?), but they agree up to index 17. 

```
i11, t6: Empty entry from raft due to new leader
i12, t6: A no-op entry from cockroach? Not sure what this is
i13, t7: Empty entry from raft due to new leader
i14, t7: A ComputeChecksum operation
i15, t7: The initial Put of a transaction on a range descriptor
i16, t7: A second Put in the same transaction, to a different range descriptor key
    (looks like this txn is a split)
i17, t8: Empty entry from raft due to new leader
```

At `i18`, they diverge as shown above: n1 has `i18, t8: AddSSTable`, while n2 has `i18, t6: empty`. So n2 apparently added an entry for t6 to its log after it already had an entry for t8. That's never supposed to happen (although the enforcement of this is kind of spotty, with a couple of checks at boundary conditions instead of entry-by-entry assertions).

**Comment by nvanbenschoten** [comment] 2019-03-30 20:11
> i12, t6: A no-op entry from cockroach? Not sure what this is

Was this the result of a replica attempting to unquiesce the Range?

https://github.com/cockroachdb/cockroach/blob/7cf6043545751dce8970d04482a679d343760e1a/pkg/storage/replica_raft_quiesce.go#L99-L100

It's unclear from what's been written here so far - does `n3` agree with `n1` or `n2`?

**Comment by nvanbenschoten** [comment] 2019-03-30 20:47
For others who want to take a look, here's the node mapping for the three replicas of Range 7828:
```
andrei-repro-1553814655-02-n7cpu72:1 -> n1 / r3
andrei-repro-1553814655-02-n7cpu72:4 -> n2 / r1
andrei-repro-1553814655-02-n7cpu72:7 -> n7 / r2
```

**Comment by nvanbenschoten** [comment] 2019-03-30 20:49
> does n3 agree with n1 or n2?

Yes it does. `n2` and `n7` both have the committed term regression.

**Comment by nvanbenschoten** [comment] 2019-03-30 21:59
It does seem possible to me that this is related to the Raft entry cache. Here's what I've pieced together so far towards a theory for how both followers could end up in this state:
1. if a Raft leader sent a `MsgApp` with an incorrect entry then a follower would never notice. It would blindly overwrite its own Raft log without inspecting the individual entry. As long as the `LogTerm` on the overall `MsgApp` was correct, the follower would trust the leader. Since both followers ended up in the same state, it seems more likely that the leader sent the wrong entry to both of them then that they both ended up doing the same wrong thing (e.g. a race condition in both of their entry caches is highly unlikely).
2. the initial `MsgApp` sent by a leader from its "unstable" log failed to reach a follower then subsequent `MsgApp`s would come from the leader's Raft entry cache, if the cache lookup doesn't miss.
3. there doesn't seem to be a way for a term regression to be introduced into a leader's log after the fact. It seems more likely that the leader had `i12, t6` through `i18, t6` in its log before it began proposing entries in term 8 and that it expected to truncate all old term 6 entries.
4. our [`raftentry.Cache`](https://github.com/cockroachdb/cockroach/blob/a6b3c540b696002b2ed07036a657612995d6d1ab/pkg/storage/raftentry/ring_buffer.go#L38) is _not_ term aware. Critically, this means that it does not perform the same truncation of Raft entries from previous terms that extend out past new entries from later terms. The corresponding logic for this behavior in our persistent Raft log is [here](https://github.com/cockroachdb/cockroach/blob/a6b3c540b696002b2ed07036a657612995d6d1ab/pkg/storage/replica_raftstorage.go#L621).
5. this means that if the leader somehow decided not to add an entry for index 18 at term 8 to its Raft entry cache and then queried this cache through index 18 when generating a `MsgAPp`, it could end up grabbing index 18 from term 6 instead and it would happily send this to both of its followers in a `MsgApp`.

So the one missing piece that would make this all possible is if we ever decide not to add a new entry to a leader's Raft entry cache. This doesn't seem like a crazy thing for us to do, especially for large entries with sideloaded data.

**Comment by nvanbenschoten** [comment] 2019-03-30 22:04
Ding ding ding!

https://github.com/cockroachdb/cockroach/blob/a6b3c540b696002b2ed07036a657612995d6d1ab/pkg/storage/raftentry/cache.go#L134-L138

**Comment by nvanbenschoten** [comment] 2019-03-30 22:11
This isn't exactly it, but I think the fix is along these lines:
```
diff --git a/pkg/storage/raftentry/ring_buffer.go b/pkg/storage/raftentry/ring_buffer.go
index ec6e5ab06f..4b5e3437bd 100644
--- a/pkg/storage/raftentry/ring_buffer.go
+++ b/pkg/storage/raftentry/ring_buffer.go
@@ -61,6 +61,14 @@ func (b *ringBuf) add(ents []raftpb.Entry) (addedBytes, addedEntries int32) {
 		}
 		it = it.push(b, e)
 	}
+	if it != last(b) && it.entry(b).Term != ents[0].Term {
+		for ok := true; ok; {
+			addedBytes -= int32(it.entry(b).Size())
+			addedEntries--
+			it.clear(b)
+			it, ok = it.next(b)
+		}
+	}
 	return
 }
```

**Comment by ajwerner** [comment] 2019-03-30 22:13
Alternatively or additionally should add calls which get rejected due to size where you noted above clear the cached entries which would be overwritten?

**Comment by nvanbenschoten** [comment] 2019-03-30 22:24
I think additionally. The case that the patch above wouldn't solve is if the first entry with a new term was rejected due to size.

**Comment by tbg** [comment] 2019-04-01 14:08
> with one particular AddSSTable command being reproposed over and over again, and each time being refused by Raft because:

Do we understand this as well? I'm guessing that the entry that gets dropped over and over again is just fallout from sending an incorrect entry out to followers, though it's hard to think through what exactly would happen at the Raft level.

@bdarnell 

> The leader tracks the highest (index, term) pair for each follower and shouldn't tell the follower to commit index 18 unless its version of index 18 is from the right term.

Where does it track the highest term? I thought the tracking is completely represented by

https://github.com/cockroachdb/vendored/blob/3f5e5955a4eeffd4c82010e2c249893d94976ffc/go.etcd.io/etcd/raft/progress.go#L37-L83

Here's my attempt at what happens internally when the wrong entry is picked from the cache.

First, the leader grabs the wrong entry and sends an MsgApp. Notably, it uses the real log term (8), not the stale one from the wrong entry (6).

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/raft.go#L520-L521

The follower receives this MsgApp here

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/raft.go#L1308-L1321

`maybeAppend` seems to have appended the entry, for we see it in the logs. Internally, it checks the `logTerm` against the `term` for the index before that of the entry, which is the

> i17, t8: Empty entry from raft due to new leader

So that checks out. The response MsgAppResp from the follower will make no reference to the term of the entry. So why didn't replication just continue? I was hoping to see some Raft state corruption that would make committing this entry fail (or that would block further appends to the followers), but now I'm not convinced that's the case. Maybe the term 6 entry also confused the leader's uncommitted log size tracking. From looking at the code, it's clear that when the command was first proposed, the leader saw it and accounted for the true size of the proposal. It's less clear that it would also have subtracted the corresponding amount after it got committed:

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/rawnode.go#L200-L202

This eventually gets populated here

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/log.go#L306-L342

and if it hit `Entries()` it would hit the cache and grab the empty entry as well (ironically, leading to applying the empty thing on the leader despite what's in the log, and trading a replica inconsistency for just straight-up missing data on all replicas). I *think* this would hit the storage because the entry wouldn't be unstable any more; we'd call `stableTo` 

https://github.com/cockroachdb/vendored/blob/a7e87efade33ddd79f2d32d77b8ecc78a3fae167/go.etcd.io/etcd/raft/rawnode.go#L59-L62

after advancing the `Ready` that processes the `MsgAppResp` from at least one of the followers, and would only compute `CommittedEntries` in the next Raft cycle.

There's enough going on here that I might've gotten this wrong, though. @andreimatei I don't think you ever told us why you started looking into this Raft log in the first place -- was it just that you got the unavailable range and wanted to dig in? Or was there some inconsistency reported?

**Comment by tbg** [comment] 2019-04-01 14:10
Oh - and fantastic work tracking this down. It's a shame it had to happen over a weekend, but this is a great catch and happens to be a wonderful team effort also.

**Comment by nvanbenschoten** [comment] 2019-04-01 14:25
> There's enough going on here that I might've gotten this wrong, though.

No, I think you're spot on. The leader applied the stale entry from its cache for the same reason that it replicated it to followers, so the account [here](https://github.com/etcd-io/etcd/blob/be39aa5bb2ab93756598339d934c3775eda82507/raft/rawnode.go#L201) broke and we "leaked" uncommitted size allowance.

I think this leak is what caused @andreimatei to start digging. It resulted in an import stalling.

**Comment by nvanbenschoten** [comment] 2019-04-01 14:41
The next question we're going to have to ask is what other Replica inconsistencies this can explain. #35424? @tbg and @andreimatei you're most familiar with these other cases. Do the pieces here fit together to explain that?

I think this could have also materialized as only the leader or only one of the followers applying the stale entry, depending on `raftentry.Cache` evictions. We could also see this with Raft entries that individually are below the size of `Cache.maxBytes` but together exceeded this size limit when added to the cache. Because the sets of entries added to the cache can differ between replicas, there seem to be a lot of different ways we could permute this into inconsistent entry application.

**Comment by tbg** [comment] 2019-04-01 16:58
We didn't have the log entries that caused the divergence in #35424. When we can look at the log, we can 100% identify this issue with an analysis similar to @andreimatei's above.

In the absence of the logs, is there any way we can tell? I suspect there isn't. Unless there's something I'm missing, I think we should go ahead and classify all replica divergences in "before this was fixed" and "after this was fixed". "Before this was fixed" is assumed to have been caused by this bug (at least as far as we know). (Notably this does not include the one time series based divergence that we have seen, for the symptom there is different - a part of a command was lost, not the whole command).

I agree with your observation that any kind of individual command not applying on any subset of peers could in principle be caused by the bug at hand.

**Comment by nvanbenschoten** [comment] 2019-04-01 17:08
> In the absence of the logs, is there any way we can tell? I suspect there isn't.

I don't think so either.

https://github.com/cockroachdb/cockroach/issues/35424 was during an import, which dramatically increases the chance that it was due to this bug. So I think we should close that as well when the fix goes in. Sound good to you?

**Comment by ajwerner** [comment] 2019-04-01 17:14
Another piece of supporting evidence on #35424 beyond just that it was during import is the delta in stats is large:
```
key_bytes:13613486 val_bytes:19940949 sys_bytes:932
```
```
key_bytes:-2411770 val_bytes:-3532515 sys_bytes:548
```
is `39499104` bytes > `pkg/storage/store.go:   defaultRaftEntryCacheSize = 1 << 24 // 16M`

**Comment by tbg** [comment] 2019-04-01 17:15
Yes, sounds good to me. I should've said this explicitly: we should close all of the investigations preceding this bug that could be explained by it.

**Closed** 2019-04-01 17:21 UTC
Labels: S-1

**Comment by nvanbenschoten** [comment] 2019-04-01 17:25
Great point @ajwerner. That delta certainly lends more weight behind the theory that the follower skipped the application of the `AddSSTableRequest` entry due to this bug.

**Comment by bdarnell** [comment] 2019-04-01 17:42
> Where does it track the highest term? I thought the tracking is completely represented by progress.go

Oh, I had it inside-out. The leader only tracks the index, but it only increases this index based on a (non-reject) MsgAppResp, which implies that the follower validated the term of the MsgApp. So the chain is 1. follower matches term, sends MsgAppResp, 2. leader updates pr.Match, 3. leader limits m.Commit to what is in pr.Match. (This is why it's important to clamp Commit at pr.Match, because log entries with higher indexes than have been matched may be from the wrong term)
