### ISSUE TITLE
Investigate i3 machine type series performance 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34841] opened 2019-02-12 21:16 UTC
Investigate why I3s perform worse than m5 or c5 machine types

**Comment by bdarnell** [comment] 2019-02-12 21:26
How much worse? They're pre-nitro, so that accounts for a lot of difference. Is the gap between i3 and m5d bigger than the gap between m4 and m5? (actually, they say that `i3.metal` instances have nitro, but not the other i3s. Not sure how that works, since nitro is all or nothing on the other instance families). 

This is kind of confusing on the AWS site - they have a section for "storage optimized" instances and i3 are the only ssd-based option in that section, even though the m5d and c5d instances are probably the true successor to the i3 (better performance, but not as much storage space) but they're lumped in to general purpose.

**Comment by awoods187** [comment] 2019-02-12 21:31
This is mostly a placeholder issue in case we need to make the i3 series work for a customer.

From the cloud report:
![image](https://user-images.githubusercontent.com/22278911/52669266-a019a580-2ee3-11e9-94bd-49f2a1909517.png)

**Comment by nvanbenschoten** [comment] 2019-12-18 04:32
I just did some more testing with the i3 series and it performed dramatically worse than I was expecting. I was trying to run sysbench's `oltp_insert` workload and was observing extremely high latency. I dropped down to a single node cluster and ran kv0 locally against it. On 64 vCPU machines (`i3.16xlarge`, no RAID striping so only using 1 of the NVMe SSDs), I hit a concurrency wall at a concurrency of 32 worker threads. Anywhere above that and latency jumps from 1-3ms up to ~90ms. Throughput similarly crashes above this concurrency limit, dropping from ~20,000 qps down to just 3,000.

I wasn't able to diagnose what the problem was. Storage looked healthy and the machine was only running at about 20% of its available CPU capacity. The issue reproduced regardless of whether the workload process was running on the same host or a different host. There's definitely something strange going on here that deserves a closer look if we ever see customer interest in this instance type.

**Comment by nvanbenschoten** [comment] 2019-12-18 04:33
For now though, I'm going to close this. We can re-open if necessary.

**Closed by nvanbenschoten** 2019-12-18 04:33 UTC
Labels: C-investigation

**Comment by nvanbenschoten** [comment] 2019-12-18 04:58
Here's a comparison using `kv0` between the an `m5d.8xlarge` and an `i3.8xlarge`, both running single-node clusters. Take note of both the overall performance and also the cliff that the i3 hits above 64 threads here.
```
$ roachprod create nathan-i3 --nodes=1 --clouds=aws --aws-machine-type-ssd=i3.8xlarge
$ roachprod stage  nathan-i3 cockroach
$ roachprod start  nathan-i3
$ roachprod run    nathan-i3 -- ./cockroach workload init kv
$ roachprod run    nathan-i3 -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=16
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
     10.0s        0         103788        10378.4      1.5      1.5      2.4      3.1     10.0  write
$ roachprod run    nathan-i3 -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=32
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         185705        18569.7      1.7      1.6      2.8      4.2      8.4  write
$ roachprod run    nathan-i3 -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=64
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         244528        24451.7      2.6      2.5      3.8      6.8     18.9  write
$ roachprod run    nathan-i3 -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=128
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   10.0s        0         157161        15714.5      8.1      5.0     35.7     46.1     71.3

$ roachprod create nathan-m5d --nodes=1 --clouds=aws --aws-machine-type-ssd=m5d.8xlarge
$ roachprod stage  nathan-m5d cockroach
$ roachprod start  nathan-m5d
$ roachprod run    nathan-m5d -- ./cockroach workload init kv
$ roachprod run    nathan-m5d -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=16
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         198708        19870.4      0.8      0.8      1.2      2.2      4.5  write
$ roachprod run    nathan-m5d -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=32
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         282275        28226.7      1.1      1.0      1.9      2.8      8.9  write
$ roachprod run    nathan-m5d -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=64
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         360031        36001.6      1.8      1.7      2.5      4.7      8.4  write
$ roachprod run    nathan-m5d -- ./cockroach workload run kv --read-percent=0 --duration=10s --concurrency=128
  ...
  _elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
   10.0s        0         344380        34435.9      3.7      3.7      5.2      7.3     14.7  write
```
