### ISSUE TITLE
cli: cursor on back arrow causes reprint of the last command if it's multiline

### ISSUE THREAD

**Issue by xphoniex** [cockroachdb/cockroach#15460] opened 2017-04-28 12:08 UTC
inside `cockroach sql`, if the last command in history is multiline and I use back arrow to make a change the console would keep reprinting the command and cursor position is not visible (though it's at the right position).

`root@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'mroot@:26257/> SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'murino', (SELECT (INSERT INTO posts VALUES (2, 'a', 'b', 0)) LIKE 'INSERT 1'), 0);`

![cli](https://cloud.githubusercontent.com/assets/14107758/25528067/0f3cb4a0-2c31-11e7-8f21-4d0204b4811e.png)

**Comment by petermattis** [comment] 2017-04-28 12:50
@xphoniex Thanks for the report. I was unable to reproduce this just now. If I navigate to an item in history, I'm able to edit the line without issue. What terminal emulator are you running and on what OS? Please include the output of `uname -a` and `echo $TERM`.

**Comment by xphoniex** [comment] 2017-04-28 13:01
I'm on ubuntu 16.04 tls, gnome terminal.

```
$ uname -a
Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM
xterm-256color
```

**Comment by petermattis** [comment] 2017-04-28 13:50
@xphoniex Thanks. Is it possible your terminal got into a bad state? Do you mind trying to reproduce on a newly created terminal?

**Comment by xphoniex** [comment] 2017-04-28 15:52
@petermattis oh I just realized what the problem was, it was because I didn't have /go/bin in my $PATH. I was running cockroach from current directory (`make` outputs the binary in current dir)

**Comment by xphoniex** [comment] 2017-04-28 16:08
It broke again when I inserted a longer subquery into my 2-line command. It broke when the command became 3 line :/ are you testing on linux/ubuntu too @petermattis ?

**Comment by petermattis** [comment] 2017-04-28 17:10
I'm running on Mac OS X because that is what I have easily available. It is more likely that the terminal matters vs the OS. Since you're building from source I'm guessing you're running against current master, but just to be sure, what is the output of `cockroach version`?

Can you describe the exact steps to reproduce the problem? Here is what I tried:

```
~/Development/go/src/github.com/cockroachdb/cockroach/pkg master ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257/> SELECT
           -> count(*)
           -> FROM
           -> system.namespace;
+----------+
| count(*) |
+----------+
|       11 |
+----------+
(1 row)
```

I then used up-arrow to select the previous history entry and used the left and right arrows to change `count(*)` to `*`:

```
root@:26257/> SELECT * FROM system.namespace;
+----------+------------+----+
| parentID |    name    | id |
+----------+------------+----+
|        0 | system     |  1 |
|        1 | descriptor |  3 |
|        1 | eventlog   | 12 |
|        1 | jobs       | 15 |
|        1 | lease      | 11 |
|        1 | namespace  |  2 |
|        1 | rangelog   | 13 |
|        1 | settings   |  6 |
|        1 | ui         | 14 |
|        1 | users      |  4 |
|        1 | zones      |  5 |
+----------+------------+----+
(11 rows)
```

**Comment by benesch** [comment] 2017-04-28 19:47
@petermattis I can confirm that I've seen this as well on my macOS development box. Here's what happens if I hold up-arrow to page through the last ~100 things I've typed:

https://gist.githubusercontent.com/benesch/d64a2a9e75df906b2f4cb4121d3370ce/raw/15cf60cb6e1aa1052353378ac1bffb496d479ef1/broken%2520output

It's appears that every command that I've ever typed was merged into one giant string and set as the earliest history entry. Smells like a bug in our readline library.

**Comment by benesch** [comment] 2017-04-28 19:49
chzyer/readline#85 may also be relevant, though @knz's steps to reproduce don't actually reproduce the issue for me.

**Comment by xphoniex** [comment] 2017-04-29 06:10
@petermattis by multiline, I mean when the line wraps (is more than 80 chars)

```
$ ./cockroach version
Build Tag:    2559afe-dirty
Build Time:   2017/04/14 16:35:13
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8
C Compiler:   gcc 5.4.0 20160609
Build SHA-1:  2559afe3f01812ae9f48f3cc4ab7ccf25a147ab0
Build Type:   development
```

I just synced my fork but the problem is still there. Here's the exact steps:

`$ ./cockroach start --insecure --store=node1`

```
$ ./cockroach sql --insecure
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
root@:26257/> 
```

now copy and paste `SELECT IF((SELECT recep FROM posts WHERE sender = 'khoze') LIKE 'murino', (INSERT INTO posts (id, recep, sender, seen) VALUES (2, 'a', 'b', 0)), null);` into the terminal and press enter (don't mind the error)

click up-arrow and then click left-arrow at least seven times.

**Comment by petermattis** [comment] 2017-04-29 12:29
@xphoniex Do you have local changes? I can't find the SHA 2559afe3f01812ae9f48f3cc4ab7ccf25a147ab0 in the github repo.

I performed your exact reproduction steps (including resizing my terminal to 80 columns wide) and was unable to reproduce any badness on Mac OS X + iTerm2.

@benesch I also tried the reproduction steps in chzyer/readline#85. Nothing but success.

**Comment by tschottdorf** [comment] 2017-04-29 12:41
Maybe an `asciinema` recording can help? I was hoping they'd allow replaying the actual key strokes in the recording in a local terminal which they don't, but it might still be helpful to track this down.

**Comment by tschottdorf** [comment] 2017-04-29 12:43
Ok, https://github.com/scoopex/scriptreplay_ng might do it. Anyhoo, there's probably an easier way to repro this. Just throwing it out there.

**Comment by knz** [comment] 2017-04-29 12:43
I can reproduce this fairly reliably. It is most definitely a "feature" of which terminal you use. In particular:

- iTerm - no problem
- tmux inside `st` - no problem
- `st` without tmux - reproduces
- tmux inside `xterm` - no problem
- `xterm` without tmux - reproduces

This is indeed a duplicate of https://github.com/chzyer/readline/issues/85. The root cause of the problem is rather esoteric (= rather simple in a historically complicated context): vt100-compatible terminals have really special/weird handling for the last line of output, that has to do with how the semantics of the vt100 control codes were designed around limitations in the controller circuit of the original vt100 terminals. The `readline` library we use does not handle this properly, causing problems on any "real" vt100-compatible terminal emulator. But the iTerm and tmux implementers (in the latter cast, libvt's implementers really) have learned from the observation that a bunch of programs are clueless about this and decided to diverge to "fix" their behavior by providing non-standard escape semantics.

To fix this bug the author of the readline library could either "learn to do the right thing", or use the terminfo library which contains pre-encoded sequences to do the right thing automatically.

**Comment by knz** [comment] 2017-04-29 12:45
On our wide we could also do what ben and I discussed a while ago, and that is to switch to `libedit` as our readline provider. (I'd actually argue the same for most of our dependencies - instead of using 80%-complete Go reimplementations of complex, mature libraries; but that's a tangent)

**Comment by petermattis** [comment] 2017-04-29 12:47
Oh, that's fun. Thanks for the details @knz. Let's document this as a known limitation and get it fixed in 1.1.

**Comment by petermattis** [comment] 2017-04-29 12:56
@xphoniex Btw, I think you can write your query (which doesn't work the way you've written it) as:

```
INSERT INTO posts (id, recep, sender, seen) 
  SELECT 2, 'a', b', 0 FROM posts WHERE sender = 'khoze' AND recep LIKE 'murino' LIMIT 1
```

The idea is that the `SELECT` returns a row containing `(2, 'a', 'b', 0)` only if at least 1 row in `posts` matches the query. The `INSERT` will then either insert those values or nothing.

**Comment by xphoniex** [comment] 2017-05-02 05:43
just to be clear, are we planning on fixing `chzyer/readline` or switching to `libedit`?

**Comment by knz** [comment] 2017-05-02 09:39
Either would be fine. We need to thoroughly test `libedit` before making a concrete plan to use it instead though.

**Comment by xphoniex** [comment] 2017-05-06 07:23
This can be fixed using chzyer/readline#103 although it still has issues when statement includes misc. characters (won't be a problem IRL)

I agree with knz, it'd be better to use mature libraries than abandoned ones.

**Comment by jseldess** [comment] 2017-05-10 03:00
Known limitation documented with https://github.com/cockroachdb/docs/pull/1381

**Comment by mberhault** [comment] 2017-08-23 09:26
@knz: switching to a native `libreadline` implementation seems too disruptive for 1.1. As for fixing the go one, it seems like the project has been mostly dormant for a while.
Should we still try this for 1.1?

**Comment by knz** [comment] 2017-08-23 10:53
Nope, bumping.

**Comment by hexasoftware** [comment] 2017-10-02 08:21
I addressed this issue on a fork I created since, the original author wasn't active 
https://github.com/gohxs/readline/issues/1
Basically certain terminals moves the cursor back (as in line up when needed) when we backspace chzyer solution was to transform left arrows in backspaces, (4x left arrow = \b\b\b\b) tmux indeed works but without tmux on linux it just prints last line. I solved by proper position the cursor but there is a lot more inconsistencies such as windows ansi. and also without termcap this is basically taking a chance for the terminals to support the hardcoded features/behaviour

**Comment by knz** [comment] 2017-10-02 14:09
The right solution to this will be #18531.

**Comment by hexasoftware** [comment] 2017-10-02 15:57
no windows version then.

**Comment by knz** [comment] 2017-10-02 16:24
I would welcome help extending go-libedit to use http://mingweditline.sourceforge.net/ on windows. If you have experience with windows dev, feel free to have a look.

**Comment by knz** [comment] 2017-10-02 16:25
Also remember windows is considered "dev only". We could also invite users to develop using the new linux subsystem for windows, where the regular terminal code would work.

**Comment by hexasoftware** [comment] 2017-10-02 17:00
I noticed that as I was coding a windows ansi wrapper/terminal utils, windows have terminal codes on the regular console as of version win10 1511 which needs to be enabled via SetConsoleMode

**Closed** 2017-10-05 22:46 UTC
Labels: community-questions, docs-done, known-limitation
