### ISSUE TITLE
Test failure in CI build 6975

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2378] opened 2015-09-05 20:39 UTC
The following test appears to have failed:

[#6975](https://circleci.com/gh/cockroachdb/cockroach/6975):

```
W0905 20:37:12.024695 948 storage/store.go:610  error gossiping configs: storage/replica.go:976: node is stopping
W0905 20:38:12.024023 948 storage/store.go:629  error gossiping system config: storage/replica.go:976: node is stopping
W0905 20:38:12.024184 948 storage/store.go:610  error gossiping configs: storage/replica.go:976: node is stopping
I0905 20:38:12.024327 948 storage/replica.go:996  gossiping cluster id  from store 1, range 1
W0905 20:38:12.024558 948 storage/store.go:591  error gossiping first range data: storage/replica.go:976: node is stopping
panic: test timed out after 5m0s

goroutine 2706 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14d09f0, 0x1a49580, 0xbc, 0xbc, 0x125ba01)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:252 +0x3db
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82005c360, 0xc8201e4c40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.060s
=== RUN   TestBatchBasics
I0905 20:34:09.790873 953 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0905 20:34:09.794227 953 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0905 20:34:09.799507 953 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2015-09-05 20:42
Can we disable `TestStoreRangeMergeNonConsecutive` until it is not flaky?

**Comment by tamird** [comment] 2015-09-06 13:30
It's been disabled. Closing as dupe of #2363.

**Closed by tamird** 2015-09-06 13:30 UTC
Labels: test-failure
