### ISSUE TITLE
ALTER table failed and job stuck in reverting. Field now dropped and not able to recreate it anymore

### ISSUE THREAD

**Issue by lucacri** [cockroachdb/cockroach#67465] opened 2021-07-10 14:15 UTC
**Describe the problem**

I was performing an ALTER TABLE on a big table (7M records), and it failed. 

My goal was to move a field to a new `family`, hence I was issuing the following:

```sql
ALTER TABLE sales ADD COLUMN updated_at_f timestamptz AS (updated_at::timestamptz) STORED FAMILY ftimes;
ALTER TABLE sales ALTER COLUMN updated_at_f DROP STORED, RENAME COLUMN updated_at TO updated_at_bk, RENAME COLUMN updated_at_f TO updated_at;
ALTER TABLE sales DROP COLUMN IF EXISTS updated_at_bk;
```

Unfortunately part of the ALTER did perform, and the table does not have any field (`updated_at`, `updated_at_bk` nor `updated_at_f`);

If I try to re-add the field manually:
```sql
alter table sales ADD COLUMN updated_at TIMESTAMPTZ NULL FAMILY ftimes;
```

I receive the error: 
> [42701] ERROR: duplicate: column "updated_at" in the middle of being added, not yet public

The job was still marked as "Running", so after a few hours I manually stopped it (`CANCEL JOB XXX`), but now it's stuck in `REVERTING` for the past 12 hours.

**To Reproduce**

I'm assuming you can test by trying to add fields and see if they fail.

**Expected behavior**
I expect the field to be created correctly, or at least to revert back to a state where the field is still present. At the moment, the field `updated_at` does not exist, and it is creating havoc in my production code

**Additional data / screenshots**
I can send you all the logs you need!

**Environment:**
 - CockroachDB version 21.1.5
 - Server OS: GKE
 - Client app: all of them 

**Additional context**
What was the impact?
At the moment, the field `updated_at` does not exist, and it is creating havoc in my production code. And I have no idea on when (or if) this whole process will revert itself. Clients are starting to notice

**Comment by rafiss** [comment] 2021-07-10 18:11
@lucacri Sorry to hear that happened. I don't quite know how to get out of this situation, but I'll share this with our schema change team to see if they have ideas.

**Comment by lucacri** [comment] 2021-07-10 18:17
I “solved” it by creating a new table, and copying the  data over it, and renamed it

I kept the old table (renamed to “sales_old”) in case you want me to do some troubleshooting/ bug discovery

**Comment by ajwerner** [comment] 2021-07-13 14:28
We're doing things here mostly by retrying forever on reverting with exponential backoff rather than just failing.

**Comment by ajwerner** [comment] 2021-07-13 14:29
I'm marking this as a duplicate of https://github.com/cockroachdb/cockroach/issues/66685.

**Closed by ajwerner** 2021-07-13 14:29 UTC
Labels: C-bug, O-community, T-sql-schema, X-blathers-triaged
