### ISSUE TITLE
sql: consider support for inet datatype

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16498] opened 2017-06-13 17:20 UTC
This might be a popular Postgres datatype - shouldn't be too hard to support it if we choose to.

https://www.postgresql.org/docs/9.3/static/datatype-net-types.html

**Comment by bdarnell** [comment] 2017-06-13 17:24
Duplicate of #6981

**Closed by bdarnell** 2017-06-13 17:24 UTC
Labels: sql-semantics
