### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestPropagateTxnOnPushError

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4972] opened 2016-03-08 11:04 UTC
The following test appears to have failed:

```
=== RUN   TestPropagateTxnOnPushError
W160308 05:07:56.001712 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160308 05:07:56.002512 server/node.go:353  store store=0:0 ([]=) not bootstrapped
I160308 05:07:56.003434 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457413677.003s
W160308 05:07:56.003769 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160308 05:07:56.003816 server/node.go:299  **** cluster b4d0a6bb-602b-4be8-96a9-4945d9aac287 has been created
I160308 05:07:56.003833 server/node.go:300  **** add additional nodes by specifying --join=127.0.0.1:38037
W160308 05:07:56.003843 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160308 05:07:56.004174 server/node.go:366  initialized store store=1:1 ([]=): {Capacity:8312655872 Available:6108106752 RangeCount:0}
I160308 05:07:56.004192 server/node.go:275  node ID 1 initialized
I160308 05:07:56.004222 storage/stores.go:289  read 0 node addresses from persistent storage
I160308 05:07:56.004260 server/node.go:486  connecting to gossip network to verify cluster ID...
I160308 05:07:56.004572 server/node.go:507  node connected via gossip and verified as part of cluster "b4d0a6bb-602b-4be8-96a9-4945d9aac287"
I160308 05:07:56.004599 server/node.go:331  [node=1] Started node with [[]=] engine(s) and attributes []
I160308 05:07:56.004618 server/server.go:315  starting https/postgres server at 127.0.0.1:38037
I160308 05:07:56.005734 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0]
I160308 05:07:56.006791 server/status/runtime.go:137  runtime stats: 37 goroutines, 6.90MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (258x)
I160308 05:07:56.014026 storage/replica_command.go:1332  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160308 05:07:56.022338 storage/replica_command.go:1255  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457413677.054s
I160308 05:07:56.022438 storage/replica_command.go:1332  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160308 05:07:56.026491 storage/replica_command.go:1255  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457413677.054s
I160308 05:07:56.026717 storage/replica_command.go:1332  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160308 05:07:56.031897 storage/replica_command.go:1255  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457413677.054s
I160308 05:07:56.077697 storage/replica_command.go:1332  initiating a split of range=1 [/Min-/Table/11) at key "b"
I160308 05:07:56.082377 storage/replica_command.go:1255  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457413677.082s
I160308 05:07:56.086836 stopper.go:273  draining; tasks left:
1      storage/replica.go:1831
1      server/node.go:689
1      kv/txn_coord_sender.go:825
I160308 05:07:56.088541 stopper.go:273  draining; tasks left:
1      storage/replica.go:1831
1      server/node.go:689
--- FAIL: TestPropagateTxnOnPushError (5.13s)
	dist_sender_server_test.go:612: expected TransactionRetryError, but got: <nil>
	dist_sender_server_test.go:621: unexpected epoch; the txn must be attempted 2 times, but got 1 attempts
	leaktest.go:80: Leaked goroutine: goroutine 8944 [chan receive]:
		github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError.func1.1(0xc8209cc000, 0xc82068c88c)
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:563 +0x13a
		github.com/cockroachdb/cockroach/client.(*DB).Txn.func1(0xc8209cc000, 0xc82068c88c, 0x4)
			/go/src/github.com/cockroachdb/cockroach/client/db.go:468 +0x25
		github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8209cc000, 0x1bf0101, 0xc820416e58, 0x1)
			/go/src/github.com/cockroachdb/cockroach/client/txn.go:462 +0x394
		github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc8206dd220, 0xc820416f68, 0x0)
			/go/src/github.com/cockroachdb/cockroach/client/db.go:469 +0x1a1
		github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError.func1(0xc8206dd220, 0xc820506d20, 0xc820506d80, 0xc8207658c0, 0xc820506de0)
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:556 +0x62
		created by github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:569 +0x247
FAIL


ERROR: exit status 1
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-08 15:22
Duplicate of #4906.

**Closed by petermattis** 2016-03-08 15:22 UTC
Labels: Robot, test-failure
