### ISSUE TITLE
Test failure in CI build 9838

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3316] opened 2015-12-03 19:49 UTC
The following test appears to have failed:

[#9838](https://circleci.com/gh/cockroachdb/cockroach/9838):

```
E1203 19:48:55.717968 990 client/txn.go:308  failure aborting transaction: kv/txn_coord_sender.go:377: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
W1203 19:48:55.718239 990 kv/dist_sender.go:568  failed to invoke AdminSplit [/Table/1001,/Min): storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
I1203 19:48:55.718455 990 client/db.go:483  failed batch: storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
E1203 19:48:55.718629 990 storage/queue.go:374  failure processing replica range=1 [/Min-/Table/1000) from split queue: storage/split_queue.go:101: unable to split range=1 [/Min-/Table/1000) at key "/Table/1001": storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
I1203 19:48:55.719338 990 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestStoreRangeSystemSplits (138.97s)
	<autogenerated>:32: storage/client_split_test.go:603: condition failed to evaluate within 5s: storage/client_split_test.go:597: expected split keys:
		[/System/Meta2/"\xff\f\x03\xe8" /System/Meta2/"\xff\f\x03\xe9" /System/Meta2/"\xff\f\x03\xea" /System/Meta2/"\xff\f\x03\xeb" /System/Meta2/"\xff\f\x03\xec" /System/Meta2/"\xff\f\x03\xed" /System/Meta2/"\xff\f\x03\xee" /System/Meta2/"\xff\f\x03\xef" /System/Meta2/"\xff\f\x03\xf0" /System/Meta2/"\xff\f\x03\xf1" /System/Meta2/"\xff\f\x03\xf2" /System/Meta2/"\xff\f\x03\xf3" /System/Meta2/"\xff\f\x03\xf4" /System/Meta2/"\xff\xff"]
		but found:
		[/System/Meta2/"\xff\f\x03\xe8" /System/Meta2/"\xff\xff"]
=== RUN   TestSplitSnapshotRace_SplitWins
I1203 19:48:55.722697 990 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1203 19:48:55.722934 990 multiraft/multiraft.go:579  node 1 starting
I1203 19:48:55.723489 990 raft/raft.go:441  [group 1] 1 became follower at term 5
I1203 19:48:55.723664 990 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1203 19:48:55.723782 990 multiraft/multiraft.go:999  node 1 campaigning because initial confstate is [1]
--
I1203 19:48:59.324384 990 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1203 19:48:59.324555 990 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.37s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.40s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	172.397s
=== RUN   TestBatchBasics
I1203 19:46:11.522839 1002 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1203 19:46:11.527317 1002 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1203 19:46:11.535592 1002 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-12-03 21:11
Dupe of #3227

**Closed by bdarnell** 2015-12-03 21:11 UTC
Labels: test-failure
