### ISSUE TITLE
circleci: failed tests: TestSplitAt

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#9078] opened 2016-09-02 19:53 UTC
The following test appears to have failed:
[#22207](https://circleci.com/gh/cockroachdb/cockroach/22207) 

```
I160902 15:22:29.012818 18944 kv/dist_sender.go:1036  [n1] application error: retry txn "server/node.go:739 (*Node).recordJoinEvent.func1" id=3f0e350f key=/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/0 rw=false pri=0.03983504 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.056818818,1 orig=1472829749.009331184,0 max=1472829749.009331184,0 wto=false rop=false
I160902 15:22:29.012946 18944 kv/dist_sender.go:771  [n1] reply error BeginTransaction [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/0,/Min), ConditionalPut [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/0,/Min), ConditionalPut [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/2/1,/Min), ConditionalPut [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/3/1,/Min), ConditionalPut [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/4/1,/Min), ConditionalPut [/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/5/1,/Min): retry txn "server/node.go:739 (*Node).recordJoinEvent.func1" id=3f0e350f key=/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/0 rw=false pri=0.03983504 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.056818818,1 orig=1472829749.009331184,0 max=1472829749.009331184,0 wto=false rop=false
I160902 15:22:29.013024 18944 internal/client/db.go:498  failed batch: retry txn "server/node.go:739 (*Node).recordJoinEvent.func1" id=3f0e350f key=/Table/12/1/2016-09-02T15:22:29.009164Z/"\x14p\x8a\xdat\x809w\x00"/0 rw=false pri=0.03983504 iso=SERIALIZABLE stat=PENDING epo=1 ts=1472829749.056818818,1 orig=1472829749.056818818,1 max=1472829749.059331184,0 wto=false rop=false
I160902 15:22:29.013065 18944 sql/event_log.go:109  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:45971} Attrs:} ClusterID:{UUID:50729267-b19c-440f-bcd8-0c5cfa8a936c} StartedAt:1472829749009015858}
I160902 15:22:29.014529 18948 storage/replica.go:2237  [n1,s1,r1{/Min-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.014775 18948 storage/replica.go:2272  [n1,s1,r1{/Min-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.036161 18979 rpc/clock_offset.go:147  1 of 1 nodes are within the maximum offset of 50ms
I160902 15:22:29.064110 18953 storage/replica_command.go:2190  [n1,s1,r1{/Min-/Max}] initiating a split of this range at key /Table/11
I160902 15:22:29.065242 18953 storage/log.go:85  Range Event: "split", range: 1, info: {"UpdatedDesc":{"range_id":1,"end_key":"kw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":2,"start_key":"kw==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.071376 18947 storage/queue.go:293  [replicate] store=1:1 2{/Table/11-/Max}: split needed; not adding
I160902 15:22:29.071833 18948 storage/replica.go:2237  [n1,s1,r2{/Table/11-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.072102 18948 storage/replica.go:2272  [n1,s1,r2{/Table/11-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.072587 18953 kv/dist_sender.go:1036  application error: key range /Table/12/0-/Min outside of bounds of range /Min-/Table/11
I160902 15:22:29.072640 18953 kv/dist_sender.go:771  reply error AdminSplit [/Table/12/0,/Min): key range /Table/12/0-/Min outside of bounds of range /Min-/Table/11
W160902 15:22:29.072864 18953 kv/dist_sender.go:816  key range /Table/12/0-/Min outside of bounds of range /Min-/Table/11
I160902 15:22:29.073528 18953 storage/replica_command.go:2190  [n1,s1,r2{/Table/11-/Max}] initiating a split of this range at key /Table/12
I160902 15:22:29.075352 18953 storage/log.go:85  Range Event: "split", range: 2, info: {"UpdatedDesc":{"range_id":2,"start_key":"kw==","end_key":"lA==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":3,"start_key":"lA==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.093161 18948 storage/replica_command.go:1357  [n1,s1,r2{/Table/11-/Max}] <nil> pushed 26239b62: priority
I160902 15:22:29.094251 18953 kv/dist_sender.go:1036  application error: retry txn "storage/replica_command.go:2236 (*Replica).AdminSplit" id=26239b62 key=/Local/Range/"\x93"/RangeDescriptor rw=true pri=0.01334934 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.091081807,1 orig=1472829749.073624815,0 max=1472829749.073624815,0 wto=false rop=false
I160902 15:22:29.094298 18953 kv/dist_sender.go:771  reply error EndTransaction [/Local/Range/"\x93"/RangeDescriptor,/Min): retry txn "storage/replica_command.go:2236 (*Replica).AdminSplit" id=26239b62 key=/Local/Range/"\x93"/RangeDescriptor rw=true pri=0.01334934 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.091081807,1 orig=1472829749.073624815,0 max=1472829749.073624815,0 wto=false rop=false
I160902 15:22:29.094379 18953 internal/client/db.go:498  failed batch: retry txn "storage/replica_command.go:2236 (*Replica).AdminSplit" id=26239b62 key=/Local/Range/"\x93"/RangeDescriptor rw=true pri=0.01334934 iso=SERIALIZABLE stat=PENDING epo=1 ts=1472829749.091081807,1 orig=1472829749.091081807,1 max=1472829749.123624815,0 wto=false rop=false
I160902 15:22:29.095915 18953 storage/log.go:85  Range Event: "split", range: 2, info: {"UpdatedDesc":{"range_id":2,"start_key":"kw==","end_key":"lA==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":3,"start_key":"lA==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.100748 18913 storage/queue.go:293  [replicate] store=1:1 3{/Table/12-/Max}: split needed; not adding
I160902 15:22:29.101244 18946 storage/replica.go:2237  [n1,s1,r3{/Table/12-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.101524 18946 storage/replica.go:2272  [n1,s1,r3{/Table/12-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.102779 18953 kv/dist_sender.go:1036  application error: key range /Table/13/0-/Min outside of bounds of range /Table/11-/Table/12
I160902 15:22:29.102838 18953 kv/dist_sender.go:771  reply error AdminSplit [/Table/13/0,/Min): key range /Table/13/0-/Min outside of bounds of range /Table/11-/Table/12
W160902 15:22:29.102941 18953 kv/dist_sender.go:816  key range /Table/13/0-/Min outside of bounds of range /Table/11-/Table/12
I160902 15:22:29.103175 18953 storage/replica_command.go:2190  [n1,s1,r3{/Table/12-/Max}] initiating a split of this range at key /Table/13
I160902 15:22:29.104115 18986 kv/dist_sender.go:1036  application error: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
I160902 15:22:29.104170 18986 kv/dist_sender.go:771  reply error GC [/Local/Range/"\x93"/RangeDescriptor,/Local/Range/"\x93"/"rdsc\x00"): end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
I160902 15:22:29.104209 18986 internal/client/db.go:498  failed batch: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
W160902 15:22:29.104231 18986 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x93"/"rdsc\x00" must be greater than start /Local/Range/"\x93"/RangeDescriptor
I160902 15:22:29.105170 18953 storage/log.go:85  Range Event: "split", range: 3, info: {"UpdatedDesc":{"range_id":3,"start_key":"lA==","end_key":"lQ==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":4,"start_key":"lQ==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.107839 18948 storage/queue.go:293  [replicate] store=1:1 4{/Table/13-/Max}: split needed; not adding
I160902 15:22:29.108133 18913 storage/replica.go:2237  [n1,s1,r4{/Table/13-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.108296 18913 storage/replica.go:2272  [n1,s1,r4{/Table/13-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.109085 18953 kv/dist_sender.go:1036  application error: key range /Table/14/0-/Min outside of bounds of range /Table/12-/Table/13
I160902 15:22:29.109132 18953 kv/dist_sender.go:771  reply error AdminSplit [/Table/14/0,/Min): key range /Table/14/0-/Min outside of bounds of range /Table/12-/Table/13
W160902 15:22:29.109201 18953 kv/dist_sender.go:816  key range /Table/14/0-/Min outside of bounds of range /Table/12-/Table/13
I160902 15:22:29.109346 18953 storage/replica_command.go:2190  [n1,s1,r4{/Table/13-/Max}] initiating a split of this range at key /Table/14
I160902 15:22:29.109852 18988 kv/dist_sender.go:1036  application error: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
I160902 15:22:29.109899 18988 kv/dist_sender.go:771  reply error GC [/Local/Range/"\x94"/RangeDescriptor,/Local/Range/"\x94"/"rdsc\x00"): end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
I160902 15:22:29.109934 18988 internal/client/db.go:498  failed batch: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
W160902 15:22:29.109955 18988 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x94"/"rdsc\x00" must be greater than start /Local/Range/"\x94"/RangeDescriptor
I160902 15:22:29.110767 18953 storage/log.go:85  Range Event: "split", range: 4, info: {"UpdatedDesc":{"range_id":4,"start_key":"lQ==","end_key":"lg==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":5,"start_key":"lg==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.113787 18947 storage/replica.go:2237  [n1,s1,r5{/Table/14-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.114033 18947 storage/replica.go:2272  [n1,s1,r5{/Table/14-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
W160902 15:22:29.114794 18890 storage/store.go:2089  [n1,s1] conflicting intents on [/Meta2/Table/12 /Meta2/Max]: resolved? false
I160902 15:22:29.114861 18990 kv/dist_sender.go:1036  application error: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
I160902 15:22:29.114923 18990 kv/dist_sender.go:771  reply error GC [/Local/Range/"\x95"/RangeDescriptor,/Local/Range/"\x95"/"rdsc\x00"): end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
I160902 15:22:29.114968 18990 internal/client/db.go:498  failed batch: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
W160902 15:22:29.115001 18990 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x95"/"rdsc\x00" must be greater than start /Local/Range/"\x95"/RangeDescriptor
W160902 15:22:29.148851 18974 sql/pgwire/v3.go:176  unrecognized configuration parameter "extra_float_digits"
W160902 15:22:29.148892 18974 sql/pgwire/v3.go:176  unrecognized configuration parameter "datestyle"
W160902 15:22:29.148919 18974 sql/pgwire/v3.go:176  unrecognized configuration parameter "client_encoding"
I160902 15:22:29.153719 18974 sql/event_log.go:109  [n1] Event: "create_database", target: 50, info: {DatabaseName:d Statement:CREATE DATABASE d User:root}
I160902 15:22:29.168108 18974 sql/event_log.go:109  [n1] Event: "create_table", target: 51, info: {TableName:d.t Statement:CREATE TABLE d.t (i INT, s STRING, PRIMARY KEY (i, s), INDEX s_idx (s)) User:root}
I160902 15:22:29.173916 18953 storage/split_queue.go:99  splitting store=1:1 5{/Table/14-/Max} at keys [/Table/50/0]
I160902 15:22:29.174456 18953 kv/dist_sender.go:1036  application error: key range /Table/50/0-/Min outside of bounds of range /Table/13-/Table/14
I160902 15:22:29.174531 18953 kv/dist_sender.go:771  reply error AdminSplit [/Table/50/0,/Min): key range /Table/50/0-/Min outside of bounds of range /Table/13-/Table/14
W160902 15:22:29.174697 18953 kv/dist_sender.go:816  key range /Table/50/0-/Min outside of bounds of range /Table/13-/Table/14
I160902 15:22:29.175068 18953 storage/replica_command.go:2190  [n1,s1,r5{/Table/14-/Max}] initiating a split of this range at key /Table/50
I160902 15:22:29.181158 18953 storage/log.go:85  Range Event: "split", range: 5, info: {"UpdatedDesc":{"range_id":5,"start_key":"lg==","end_key":"ug==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":6,"start_key":"ug==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.206198 18948 storage/queue.go:293  [replicate] store=1:1 6{/Table/50-/Max}: split needed; not adding
I160902 15:22:29.206803 18947 storage/replica.go:2237  [n1,s1,r6{/Table/50-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.207095 18947 storage/replica.go:2272  [n1,s1,r6{/Table/50-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.211322 18997 kv/dist_sender.go:1036  application error: end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
I160902 15:22:29.211372 18997 kv/dist_sender.go:771  reply error GC [/Local/Range/"\x96"/RangeDescriptor,/Local/Range/"\x96"/"rdsc\x00"): end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
I160902 15:22:29.211404 18997 internal/client/db.go:498  failed batch: end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
W160902 15:22:29.211421 18997 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\x96"/"rdsc\x00" must be greater than start /Local/Range/"\x96"/RangeDescriptor
I160902 15:22:29.211569 18974 sql/event_log.go:109  [n1] Event: "create_table", target: 52, info: {TableName:d.i Statement:CREATE TABLE d.i (k INT PRIMARY KEY) User:root}
I160902 15:22:29.219056 18953 storage/split_queue.go:99  splitting store=1:1 6{/Table/50-/Max} at keys [/Table/51/0 /Table/52/0]
I160902 15:22:29.221439 18974 kv/dist_sender.go:1036  application error: key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/14-/Table/50
I160902 15:22:29.221491 18974 kv/dist_sender.go:771  reply error AdminSplit [/Table/51/1/2/"b"/0,/Min): key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/14-/Table/50
W160902 15:22:29.221636 18974 kv/dist_sender.go:816  key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/14-/Table/50
I160902 15:22:29.221865 18974 storage/replica_command.go:2190  [n1,s1,r6{/Table/50-/Max}] initiating a split of this range at key /Table/51/1/2/"b"
I160902 15:22:29.223778 18974 storage/log.go:85  Range Event: "split", range: 6, info: {"UpdatedDesc":{"range_id":6,"start_key":"ug==","end_key":"u4mKEmIAAQ==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":7,"start_key":"u4mKEmIAAQ==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.228298 18948 storage/queue.go:293  [replicate] store=1:1 6{/Table/50-/Table/51/1/2/"b"}: split needed; not adding
I160902 15:22:29.228362 18948 storage/queue.go:293  [replicate] store=1:1 7{/Table/51/1/2/"b"-/Max}: split needed; not adding
I160902 15:22:29.229602 18913 storage/replica.go:2237  [n1,s1,r7{/Table/51/1/2/"b"-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.229870 18913 storage/replica.go:2272  [n1,s1,r7{/Table/51/1/2/"b"-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.232106 19011 kv/dist_sender.go:1036  application error: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.232760 19011 kv/dist_sender.go:771  reply error GC [/Local/Range/"\xba"/RangeDescriptor,/Local/Range/"\xba"/"rdsc\x00"): end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.232813 19011 internal/client/db.go:498  failed batch: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
W160902 15:22:29.232842 19011 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.232887 18953 kv/dist_sender.go:1036  application error: key range /Table/51/0-/Min outside of bounds of range /Table/14-/Table/50
I160902 15:22:29.233536 18953 kv/dist_sender.go:771  reply error AdminSplit [/Table/51/0,/Min): key range /Table/51/0-/Min outside of bounds of range /Table/14-/Table/50
W160902 15:22:29.233640 18953 kv/dist_sender.go:816  key range /Table/51/0-/Min outside of bounds of range /Table/14-/Table/50
I160902 15:22:29.233880 18953 storage/replica_command.go:2190  [n1,s1,r6{/Table/50-/Table/51/1/2/"b"}] initiating a split of this range at key /Table/51
I160902 15:22:29.235906 18953 storage/log.go:85  Range Event: "split", range: 6, info: {"UpdatedDesc":{"range_id":6,"start_key":"ug==","end_key":"uw==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":8,"start_key":"uw==","end_key":"u4mKEmIAAQ==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.236326 18974 kv/dist_sender.go:1036  application error: key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/50-/Table/51/1/2/"b"
I160902 15:22:29.237345 18974 kv/dist_sender.go:771  reply error AdminSplit [/Table/51/1/2/"b"/0,/Min): key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/50-/Table/51/1/2/"b"
I160902 15:22:29.240088 19001 storage/intent_resolver.go:194  skipping PushTxn for 2da53821-7137-4a1a-9e5c-16962c06df88; attempt already in flight
I160902 15:22:29.240790 18948 storage/replica_command.go:1363  [n1,s1,r6{/Table/50-/Table/51/1/2/"b"}] failed to push "storage/replica_command.go:2236 (*Replica).AdminSplit" id=2da53821 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.02531968 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.234191539,0 orig=1472829749.234191539,0 max=1472829749.234191539,0 wto=false rop=false
I160902 15:22:29.241581 19001 kv/dist_sender.go:1036  application error: failed to push "storage/replica_command.go:2236 (*Replica).AdminSplit" id=2da53821 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.02531968 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.234191539,0 orig=1472829749.234191539,0 max=1472829749.234191539,0 wto=false rop=false
I160902 15:22:29.241653 19001 kv/dist_sender.go:771  reply error PushTxn [/Local/Range/"\xba"/RangeDescriptor,/Min): failed to push "storage/replica_command.go:2236 (*Replica).AdminSplit" id=2da53821 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.02531968 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.234191539,0 orig=1472829749.234191539,0 max=1472829749.234191539,0 wto=false rop=false
I160902 15:22:29.241707 19001 internal/client/db.go:498  failed batch: failed to push "storage/replica_command.go:2236 (*Replica).AdminSplit" id=2da53821 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.02531968 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.234191539,0 orig=1472829749.234191539,0 max=1472829749.234191539,0 wto=false rop=false
W160902 15:22:29.241755 19001 storage/intent_resolver.go:303  store=1:1 1{/Min-/Table/11}: failed to push during intent resolution: failed to push "storage/replica_command.go:2236 (*Replica).AdminSplit" id=2da53821 key=/Local/Range/"\xba"/RangeDescriptor rw=true pri=0.02531968 iso=SERIALIZABLE stat=PENDING epo=0 ts=1472829749.234191539,0 orig=1472829749.234191539,0 max=1472829749.234191539,0 wto=false rop=false
W160902 15:22:29.243656 18974 kv/dist_sender.go:816  key range /Table/51/1/2/"b"/0-/Min outside of bounds of range /Table/50-/Table/51/1/2/"b"
I160902 15:22:29.243992 18974 kv/dist_sender.go:1036  application error: storage/replica_command.go:2176: range is already split at key /Table/51/1/2/"b"
I160902 15:22:29.244056 18974 kv/dist_sender.go:771  reply error AdminSplit [/Table/51/1/2/"b"/0,/Min): storage/replica_command.go:2176: range is already split at key /Table/51/1/2/"b"
I160902 15:22:29.244104 18974 internal/client/db.go:498  failed batch: storage/replica_command.go:2176: range is already split at key /Table/51/1/2/"b"
I160902 15:22:29.247343 18946 storage/replica.go:2237  [n1,s1,r8{/Table/51-/Table/51/1/2/"b"}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.247707 18946 storage/replica.go:2272  [n1,s1,r8{/Table/51-/Table/51/1/2/"b"}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.249142 18953 storage/replica_command.go:2190  [n1,s1,r7{/Table/51/1/2/"b"-/Max}] initiating a split of this range at key /Table/52
I160902 15:22:29.251023 19002 kv/dist_sender.go:1036  application error: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.251163 19002 kv/dist_sender.go:771  reply error GC [/Local/Range/"\xba"/RangeDescriptor,/Local/Range/"\xba"/"rdsc\x00"): end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.251210 19002 internal/client/db.go:498  failed batch: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
W160902 15:22:29.251239 19002 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\xba"/"rdsc\x00" must be greater than start /Local/Range/"\xba"/RangeDescriptor
I160902 15:22:29.252827 18953 storage/log.go:85  Range Event: "split", range: 7, info: {"UpdatedDesc":{"range_id":7,"start_key":"u4mKEmIAAQ==","end_key":"vA==","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2},"NewDesc":{"range_id":9,"start_key":"vA==","end_key":"//8=","replicas":[{"node_id":1,"store_id":1,"replica_id":1}],"next_replica_id":2}}
I160902 15:22:29.255480 18974 storage/replica_command.go:2190  [n1,s1,r7{/Table/51/1/2/"b"-/Max}] initiating a split of this range at key /Table/51/1/5/"e"
I160902 15:22:29.258603 18946 storage/replica.go:2237  [n1,s1,r9{/Table/52-/Max}] applying command with forced error: storage/replica.go:2162: no-op on empty Raft entry
E160902 15:22:29.258874 18946 storage/replica.go:2272  [n1,s1,r9{/Table/52-/Max}] error executing raft command: storage/replica.go:2162: no-op on empty Raft entry
I160902 15:22:29.262704 19004 kv/dist_sender.go:1036  application error: end key /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/"rdsc\x00" must be greater than start /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor
I160902 15:22:29.262782 19004 kv/dist_sender.go:771  reply error GC [/Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor,/Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/"rdsc\x00"): end key /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/"rdsc\x00" must be greater than start /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor
I160902 15:22:29.262814 19004 internal/client/db.go:498  failed batch: end key /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/"rdsc\x00" must be greater than start /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor
W160902 15:22:29.262830 19004 storage/intent_resolver.go:344  could not GC completed transaction: end key /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/"rdsc\x00" must be greater than start /Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor
W160902 15:22:29.263106 18974 storage/store.go:2089  [n1,s1] conflicting intents on [/Meta2/Max]: resolved? false
I160902 15:22:29.264358 18974 kv/dist_sender.go:1036  application error: unexpected value: raw_bytes:" 9\215q\003\010\007\022\007\273\211\212\022b\000\001\032\001\274\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:1472829749249252173 logical:0 > 
I160902 15:22:29.264428 18974 kv/dist_sender.go:771  reply error BeginTransaction [/Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor,/Min), ConditionalPut [/Local/Range/"\xbb\x89\x8a\x12b\x00\x01"/RangeDescriptor,/Min), ConditionalPut [/Local/Range/"\xbb\x89\x8d\x12e\x00\x01"/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta2/Table/51/1/5/"e",/Min): unexpected value: raw_bytes:" 9\215q\003\010\007\022\007\273\211\212\022b\000\001\032\001\274\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:1472829749249252173 logical:0 > 
I160902 15:22:29.264500 18974 internal/client/db.go:498  failed batch: unexpected value: raw_bytes:" 9\215q\003\010\007\022\007\273\211\212\022b\000\001\032\001\274\"\006\010\001\020\001\030\001(\002" timestamp:<wall_time:1472829749249252173 logical:0 > 
I160902 15:22:29.264677 18974 kv/dist_sender.go:1036  application error: storage/replica_command.go:2237: split at key /Table/51/1/5/"e" failed: conflict updating range descriptors
I160902 15:22:29.264747 18974 kv/dist_sender.go:771  reply error AdminSplit [/Table/51/1/5/"e"/0,/Min): storage/replica_command.go:2237: split at key /Table/51/1/5/"e" failed: conflict updating range descriptors
I160902 15:22:29.264784 18974 internal/client/db.go:498  failed batch: storage/replica_command.go:2237: split at key /Table/51/1/5/"e" failed: conflict updating range descriptors
I160902 15:22:29.264973 18890 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160902 15:22:29.265133 18984 http2_server.go:276  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:45971->127.0.0.1:58067: use of closed network connection
I160902 15:22:29.265200 18892 rpc/context.go:169  closing 127.0.0.1:45971
I160902 15:22:29.265300 18979 rpc/context.go:169  closing 127.0.0.1:45971
I160902 15:22:29.265452 18890 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
	split_at_test.go:132: ALTER TABLE d.t SPLIT AT (5, 'e'): unexpected error: pq: storage/replica_command.go:2237: split at key /Table/51/1/5/"e" failed: conflict updating range descriptors
```

see also #9076 which was for the same build, retrying again after succeeded for build [#22224](https://circleci.com/gh/cockroachdb/cockroach/22224)

**Comment by andreimatei** [comment] 2016-09-06 18:07
dupe of #9120

**Closed by andreimatei** 2016-09-06 18:07 UTC
