### ISSUE TITLE
storage: TestStoreRangeMergeAbandonedFollowersAutomaticallyGarbageCollected flaky

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#32062] opened 2018-10-31 19:33 UTC
It failed on https://github.com/cockroachdb/cockroach/pull/31957. The culprit was a timeout, with endless spam:

```
E181031 19:27:12.087176 69259 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot b2ee3b54 at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.136100 69298 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 69451a88 at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.289314 69318 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 3ec1b048 at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.385763 69265 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 647bd927 at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.486789 69249 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 188c170f at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.585974 69234 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 751dc921 at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.635955 69364 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot f8ca11fe at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.786097 69366 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 5498509a at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
E181031 19:27:12.886162 69353 storage/queue.go:803  [raftsnapshot,s1,r2/1:{b-/Max}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 55fe78af at applied index 13 with error: [n3,s3],r2: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r1/3:/M{in-ax}]
panic: test timed out after 8m0s

goroutine 69379 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:1240 +0xfc
created by time.goFunc
	/usr/local/go/src/time/sleep.go:172 +0x44
```

**Comment by benesch** [comment] 2018-10-31 19:56
Is there no justice in this world? I literally ran that under stress race 129 THOUSAND times without it failing. Agh!

**Comment by benesch** [comment] 2018-10-31 20:35
Gosh, I really can't reproduce this. Even on a 20 node cluster using TC-sized VMs, I've successfully run the entire storage package's tests on 6ff9e55236ea58f855115693495742c74efa8f9d 600+ times with no failures. I suppose we'll just have to wait and see if this repros.

**Comment by benesch** [comment] 2018-11-12 16:53
Nothing in the last two weeks. Closing for now since it's proven impossible to reproduce.

**Comment by tbg** [comment] 2018-11-13 13:19
There's no justice in this world.
https://github.com/cockroachdb/cockroach/issues/32062

**Comment by andreimatei** [comment] 2018-11-15 21:17
There's no justice in this world: https://teamcity.cockroachdb.com/viewLog.html?buildId=1013042&buildTypeId=Cockroach_UnitTests

**Comment by aizumoff** [comment] 2018-11-16 16:31
Hi! 
I'm on cockroach v2.1.0 deployed in Insecure mode from your Yaml into k8s (1.10). 3x AWS EC2 t2.XLarge nodes + 3x PVC (100GBs each). Just in case its helpful. 
 
I've encountered this issues while doing many Imports 10thx GBs. And now I see this errors on all 3 nodes and 3 nodes eating 30% CPU:

[n2,raftsnapshot,s2,r7368/2:/Table/88/1/"\x81{=\x9…-^\xf…}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot 2841ccda at applied index 18 with error: [n3,s3],r7368: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r3274/3:/{Table/70/1/"…-Max}] | storage/queue.go:793
-- | --
 

[n2,raftsnapshot,s2,r7221/2:/Table/88/1/"{1\x9fi…-2\xe1>…}] snapshot failed: (n3,s3):3: remote couldn't accept Raft snapshot d22b2dbf at applied index 24 with error: [n3,s3],r7221: cannot apply snapshot: snapshot intersects existing range; initiated GC: [n3,s3,r3274/3:/{Table/70/1/"…-Max}] | storage/queue.go:793
-- | --

**Comment by tbg** [comment] 2018-11-16 21:59
Hi @aizumoff, thanks for your report. You're more likely to be running into #31409, which is a larger debug effort underway right now. Please subscribe to that issue. The expectation is that the symptoms will be much milder in v2.1.2.

**Closed** 2018-12-18 18:31 UTC
Labels: C-test-failure
