### ISSUE TITLE
sql: `testing_optimizer_disable_rule_probability` causes "top-level relational expression cannot have outer columns"

### ISSUE THREAD

**Issue by SteveLeungYL** [cockroachdb/cockroach#94960] opened 2023-01-09 22:48 UTC
**Describe the problem**

The latest version of the CockroachDB (01032c22407) shows `Internal Error` when executing the following query:

```sql
SET testing_optimizer_disable_rule_probability = 1.0;
CREATE TABLE v0 (c1 INT PRIMARY KEY, c2 INT);
SELECT SUM(c1) OVER ( ORDER BY c2 ) FROM v0 GROUP BY c1;
```

**To Reproduce**

Here is the detail steps to reproduce the bug.

1. In operating system Ubuntu 20.04, download the CockroachDB source code from the github source.
2. Use the latest version of the CockroachDB code (tested version: 01032c22407)
3. Directly `make install` in the root repository folder. 
4. Run `./cockroach demo`, and then paste the PoC query to the cockroach cli environment.
5. Observe the `Internal Error` and log the stack information. 

**Expected behavior**
The SELECT statement should be executed successfully. 

**Additional data / screenshots**

Here is the outputted stack trace:

```
ERROR: internal error: top-level relational expression cannot have outer columns: (2)
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:279: Optimize()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:584: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:237: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1526: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1133: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:738: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2522: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:129: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1959: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1964: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1882: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:834: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:727: func1()
runtime/asm_arm64.s:1165: goexit()

HINT: You have encountered an unexpected error.
```

**Environment:**
 - CockroachDB version: v23.1.0-alpha
 - Server OS: Ubuntu 20.04 LTS
 - Client app: CockroachDB demo command. (`./cockroach demo`)
 - Detailed CockroachDB version output:

```
cockroach version details:
Build Tag:        v23.1.0-alpha.1-688-g01032c2240
Build Time:       2023/01/09 22:41:46
Distribution:     CCL
Platform:         linux arm64 (aarch64-linux-gnu)
Go Version:       go1.19
C Compiler:       gcc 9.4.0
Build Commit ID:  01032c22407e98b48b96e7a57a3a33f8a1db0b5a
Build Type:       development
```

**Additional context**

This Internal Error problem may not happen in the real-world application, since it requires the specific setup: `SET testing_optimizer_disable_rule_probability = 1.0;`, which is a developer setting used to control the query optimization. However, an `Internal Error` is still unexpected from the resulted behavior. Therefore, this problem is reported here. 

Jira issue: CRDB-23245

**Comment by yuzefovich** [comment] 2024-01-27 01:22
This error was observed on a serverless cluster, putting back into triage.

**Comment by mgartner** [comment] 2024-09-17 21:25
Closing as a duplicate of #130400.

**Closed by mgartner** 2024-09-17 21:25 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries, P-2
