### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestRaceWithBackfill

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#7154] opened 2016-06-10 12:38 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/19503c4f6d3de020f62877d47dea404511be3461

Stress build found a failed test:

```
=== RUN   TestRaceWithBackfill
I160610 07:07:10.596085 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160610 07:07:10.599609 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
W160610 07:07:10.604388 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160610 07:07:10.604578 server/node.go:401  store store=0:0 ([]=) not bootstrapped
I160610 07:07:10.606551 storage/replica_command.go:1531  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.106104593s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.606459556 +0000 UTC]
I160610 07:07:10.607014 server/node.go:327  **** cluster {5fddf2b3-e94f-4752-a86a-4f8ec97b549a} has been created
I160610 07:07:10.607037 server/node.go:328  **** add additional nodes by specifying --join=127.0.0.1:42452
W160610 07:07:10.607051 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160610 07:07:10.607580 server/node.go:414  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:7931219968 RangeCount:0}
I160610 07:07:10.607607 server/node.go:302  node ID 1 initialized
I160610 07:07:10.607660 storage/stores.go:287  read 0 node addresses from persistent storage
I160610 07:07:10.607713 server/node.go:535  connecting to gossip network to verify cluster ID...
I160610 07:07:10.608323 server/node.go:556  node connected via gossip and verified as part of cluster {"5fddf2b3-e94f-4752-a86a-4f8ec97b549a"}
I160610 07:07:10.608356 server/node.go:355  [node=1] Started node with [[]=] engine(s) and attributes []
I160610 07:07:10.608381 server/server.go:417  starting https server at 127.0.0.1:40460
I160610 07:07:10.608395 server/server.go:418  starting grpc/postgres server at 127.0.0.1:42452
I160610 07:07:10.608684 storage/split_queue.go:96  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160610 07:07:10.630487 server/updates.go:156  No previous updates check time.
I160610 07:07:10.630551 storage/replica_command.go:2079  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160610 07:07:10.653586 storage/replica_command.go:1531  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.207254617s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.653540194 +0000 UTC]
I160610 07:07:10.653722 storage/replica_command.go:2079  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160610 07:07:10.658372 storage/replica_command.go:1531  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.208045052s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.658335592 +0000 UTC]
I160610 07:07:10.658499 storage/replica_command.go:2079  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160610 07:07:10.679609 storage/replica_command.go:1531  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.229291009s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.679564292 +0000 UTC]
I160610 07:07:10.679768 storage/replica_command.go:2079  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160610 07:07:10.722081 storage/replica_command.go:1531  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.271685619s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.722039189 +0000 UTC]
I160610 07:07:10.722213 storage/split_queue.go:96  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0 /Table/51/0]
I160610 07:07:10.722628 storage/replica_command.go:2079  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160610 07:07:10.731949 storage/replica_command.go:1531  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.281609527s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:10.731903587 +0000 UTC]
I160610 07:07:10.733181 storage/replica_command.go:2079  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160610 07:07:11.440415 storage/replica_command.go:1531  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407095h7m15.990123633s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-10 07:07:11.440361538 +0000 UTC]
I160610 07:07:11.604613 gossip/gossip.go:923  starting client to 127.0.0.1:42452
I160610 07:07:11.605272 gossip/client.go:86  closing client to node 1 (127.0.0.1:42452): gossip/client.go:180: stopping outgoing client to node 1 (127.0.0.1:42452); loopback connection
I160610 07:07:11.689360 sql/lease.go:250  publish (count leases): descID=51 name=test version=5 count=1
I160610 07:07:12.202432 sql/lease.go:250  publish (count leases): descID=51 name=test version=6 count=1
I160610 07:07:12.342989 sql/lease.go:250  publish (count leases): descID=51 name=test version=7 count=1
I160610 07:07:12.401604 sql/lease.go:250  publish (count leases): descID=51 name=test version=8 count=1
I160610 07:07:13.219785 sql/lease.go:250  publish (count leases): descID=51 name=test version=9 count=1
I160610 07:07:13.350274 sql/lease.go:250  publish (count leases): descID=51 name=test version=10 count=1
I160610 07:07:13.410852 sql/lease.go:250  publish (count leases): descID=51 name=test version=11 count=1
E160610 07:07:14.281756 storage/replica.go:2308  [node=1,store=1,range=1] could not load SystemConfig span: must retry later due to intent on SystemConfigSpan
I160610 07:07:15.255103 sql/lease.go:250  publish (count leases): descID=51 name=test version=12 count=1
I160610 07:07:15.406707 sql/lease.go:250  publish (count leases): descID=51 name=test version=13 count=1
I160610 07:07:15.458314 sql/lease.go:250  publish (count leases): descID=51 name=test version=14 count=1
I160610 07:07:15.653281 stopper.go:352  draining; tasks left:
1      server/node.go:803
W160610 07:07:15.653627 sql/schema_changer.go:273  node unavailable; try another peer
W160610 07:07:15.653725 sql/schema_changer.go:196  node unavailable; try another peer
--- FAIL: TestRaceWithBackfill (5.08s)
	schema_changer_test.go:428: schema change ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') took 570.321905ms
	schema_changer_test.go:428: schema change ALTER TABLE t.test DROP pi took 931.950069ms
	schema_changer_test.go:428: schema change CREATE UNIQUE INDEX foo ON t.test (v) took 1.932218429s
	schema_changer_test.go:450: pq: BeginTransaction can't overwrite "sql/executor.go:422 sql txn implicit" id=e634fa3f key=/Table/51/3/2884/0 rw=true pri=0.00407365 iso=SERIALIZABLE stat=PENDING epo=0 ts=1465542435.489024899,1 orig=1465542435.488998714,0 max=1465542435.488998714,0 wto=true rop=false
	schema_changer_test.go:428: schema change DROP INDEX t.test@vidx took 258.345671ms
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
0 runs so far, 0 failures, over 40s
0 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
16 runs so far, 0 failures, over 1m20s
16 runs so far, 0 failures, over 1m25s
16 runs so far, 0 failures, over 1m30s
29 runs so far, 0 failures, over 1m35s
32 runs so far, 0 failures, over 1m40s
32 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
32 runs so far, 0 failures, over 1m55s
32 runs so far, 0 failures, over 2m0s
32 runs so far, 0 failures, over 2m5s
32 runs so far, 0 failures, over 2m10s
32 runs so far, 0 failures, over 2m15s
39 runs so far, 0 failures, over 2m20s
46 runs so far, 0 failures, over 2m25s
48 runs so far, 0 failures, over 2m30s
48 runs so far, 0 failures, over 2m35s
48 runs so far, 0 failures, over 2m40s
48 runs so far, 0 failures, over 2m45s
48 runs so far, 0 failures, over 2m50s
48 runs so far, 0 failures, over 2m55s
48 runs so far, 0 failures, over 3m0s
50 runs so far, 0 failures, over 3m5s
62 runs so far, 0 failures, over 3m10s
63 runs so far, 0 failures, over 3m15s
64 runs so far, 0 failures, over 3m20s
64 runs so far, 0 failures, over 3m25s
64 runs so far, 0 failures, over 3m30s
64 runs so far, 0 failures, over 3m35s
64 runs so far, 0 failures, over 3m40s
64 runs so far, 0 failures, over 3m45s
65 runs so far, 0 failures, over 3m50s
73 runs so far, 0 failures, over 3m55s
79 runs so far, 0 failures, over 4m0s
80 runs so far, 0 failures, over 4m5s
80 runs so far, 0 failures, over 4m10s
80 runs so far, 0 failures, over 4m15s
80 runs so far, 0 failures, over 4m20s
80 runs so far, 0 failures, over 4m25s
80 runs so far, 0 failures, over 4m30s
81 runs so far, 0 failures, over 4m35s
88 runs so far, 0 failures, over 4m40s
92 runs so far, 0 failures, over 4m45s
96 runs so far, 0 failures, over 4m50s
96 runs so far, 0 failures, over 4m55s
96 runs so far, 0 failures, over 5m0s
96 runs so far, 0 failures, over 5m5s
96 runs so far, 0 failures, over 5m10s
96 runs so far, 0 failures, over 5m15s
97 runs so far, 0 failures, over 5m20s
101 runs so far, 0 failures, over 5m25s
107 runs so far, 0 failures, over 5m30s
110 runs so far, 0 failures, over 5m35s
112 runs so far, 0 failures, over 5m40s
112 runs so far, 0 failures, over 5m45s
112 runs so far, 0 failures, over 5m50s
112 runs so far, 0 failures, over 5m55s
112 runs so far, 0 failures, over 6m0s
112 runs so far, 0 failures, over 6m5s
116 runs so far, 0 failures, over 6m10s
119 runs so far, 0 failures, over 6m15s
125 runs so far, 0 failures, over 6m20s
128 runs so far, 0 failures, over 6m25s
128 runs so far, 0 failures, over 6m30s
128 runs so far, 0 failures, over 6m35s
128 runs so far, 0 failures, over 6m40s
128 runs so far, 0 failures, over 6m45s
128 runs so far, 0 failures, over 6m50s
130 runs so far, 0 failures, over 6m55s
134 runs so far, 0 failures, over 7m0s
140 runs so far, 0 failures, over 7m5s
143 runs so far, 0 failures, over 7m10s
144 runs so far, 0 failures, over 7m15s
144 runs so far, 0 failures, over 7m20s
144 runs so far, 0 failures, over 7m25s
144 runs so far, 0 failures, over 7m30s
144 runs so far, 0 failures, over 7m35s
145 runs so far, 0 failures, over 7m40s
148 runs so far, 0 failures, over 7m45s
155 runs so far, 0 failures, over 7m50s
159 runs so far, 0 failures, over 7m55s
160 runs so far, 0 failures, over 8m0s
160 runs so far, 0 failures, over 8m5s
160 runs so far, 0 failures, over 8m10s
160 runs so far, 0 failures, over 8m15s
160 runs so far, 0 failures, over 8m20s
161 runs so far, 0 failures, over 8m25s
164 runs so far, 0 failures, over 8m30s
166 runs so far, 0 failures, over 8m35s
175 runs so far, 0 failures, over 8m40s
175 runs so far, 0 failures, over 8m45s
176 runs so far, 0 failures, over 8m50s
176 runs so far, 0 failures, over 8m55s
176 runs so far, 0 failures, over 9m0s
176 runs so far, 0 failures, over 9m5s
177 runs so far, 0 failures, over 9m10s
179 runs so far, 0 failures, over 9m15s
181 runs so far, 0 failures, over 9m20s
189 runs so far, 0 failures, over 9m25s
190 runs so far, 0 failures, over 9m30s
192 runs so far, 0 failures, over 9m35s
192 runs so far, 0 failures, over 9m40s
192 runs so far, 0 failures, over 9m45s
192 runs so far, 0 failures, over 9m50s
193 runs so far, 0 failures, over 9m55s
194 runs so far, 0 failures, over 10m0s
197 runs so far, 0 failures, over 10m5s
201 runs so far, 0 failures, over 10m10s
206 runs so far, 0 failures, over 10m15s
208 runs so far, 0 failures, over 10m20s
208 runs so far, 0 failures, over 10m25s
208 runs so far, 0 failures, over 10m30s
208 runs so far, 0 failures, over 10m35s
208 runs so far, 0 failures, over 10m40s
210 runs so far, 0 failures, over 10m45s
211 runs so far, 0 failures, over 10m50s
216 runs so far, 0 failures, over 10m55s
217 runs completed, 1 failures, over 10m55s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by vivekmenezes** [comment] 2016-06-10 18:04
From storgae/replica_command.go

```
if ok {
		// Check whether someone has come in ahead and already aborted the
		// txn.
		if txn.Status == roachpb.ABORTED {
			return reply, roachpb.NewTransactionAbortedError()
		} else if txn.Status == roachpb.PENDING && h.Txn.Epoch > txn.Epoch {
			// On a transaction retry there will be an extant txn record but
			// this run should have an upgraded epoch. The extant txn record
			// may have been pushed or otherwise updated, so update this
			// command's txn and rewrite the record.
			reply.Txn.Update(&txn)
		} else {
			return reply, roachpb.NewTransactionStatusError(fmt.Sprintf("BeginTransaction can't overwrite %s", txn))
		}
	}
```

It appears that this test had a transaction that was retried with the same epoch

**Comment by tamird** [comment] 2016-07-01 16:20
Just ran into this again: https://circleci.com/gh/tamird/cockroach/175

**Comment by vivekmenezes** [comment] 2016-07-12 14:16
duplicate of #7628

**Closed by vivekmenezes** 2016-07-12 14:16 UTC
Labels: Robot, test-failure
