### ISSUE TITLE
Include index recommendations in statement bundle

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#100372] opened 2023-04-01 00:27 UTC
**Is your feature request related to a problem? Please describe.**
When analyzing explain plans in a statement bundle, it would be handy to have the index recommendations present in a file, so the statement bundle setup (which sometimes errors out due to missing DDL or bad creation order of tables with foreign keys) doesn't have to be done to get hints on which indexes would be helpful.

**Describe the solution you'd like**
Add the output of regular EXPLAIN to the statement bundle, which includes index recommendations.

**Describe alternatives you've considered**
None

Jira issue: CRDB-26392

**Comment by msirek** [comment] 2023-04-01 01:24
EXPLAIN(VERBOSE) may also be useful to include because it shows limit hints.

**Comment by michae2** [comment] 2023-04-25 00:28
Oh, looks like this is a dupe of https://github.com/cockroachdb/cockroach/issues/98097

**Closed** 2023-04-25 00:29 UTC
Labels: C-enhancement, A-sql-explain, T-sql-queries
