### ISSUE TITLE
crash in raft.sendAppend: error from range_raftstorage.go:245

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1187] opened 2015-05-28 20:52 UTC
```
E0528 20:47:12.818151       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0528 20:47:12.849569       1 client.go:150] client roach1.local:8080 connected
I0528 20:47:12.849768       1 client.go:224] client roach1.local:8080 starting heartbeat
E0528 20:47:13.210226       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:13.622575       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:14.024363       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0528 20:47:14.428034       1 queue.go:262] failure processing range range=1 (""-"\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
I0528 20:47:14.563834       1 server.go:111] gossip: received 7 info(s) from 172.17.0.191:8080
I0528 20:47:14.901081       1 client.go:150] client roach2.local:8080 connected
I0528 20:47:14.901209       1 client.go:224] client roach2.local:8080 starting heartbeat
panic: range_raftstorage.go:245: failed to get desc: conflicting write intents [{Key:"\x00\x00\x00k\x00\x01rdsc" Txn:"change replicas of 1" {id=d751d638-91ea-41f4-88a2-e946d05ebe02 pri=1579927167, iso=SERIALIZABLE, stat=PENDING, epo=0, ts=1432846034.852988720,0 orig=1432846034.852988720,0 max=1432846035.102988482,0} XXX_unrecognized:[]}]: resolved? false

goroutine 19 [running]:
github.com/coreos/etcd/raft.(*raft).sendAppend(0xc208182000, 0x300000003)
	/go/src/github.com/coreos/etcd/raft/raft.go:250 +0x159
github.com/coreos/etcd/raft.stepLeader(0xc208182000, 0x4, 0x100000001, 0x300000003, 0x7, 0x0, 0xa3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:523 +0x6f3
github.com/coreos/etcd/raft.(*raft).Step(0xc208182000, 0x4, 0x100000001, 0x300000003, 0x7, 0x0, 0xa3, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/coreos/etcd/raft/raft.go:487 +0x259
github.com/coreos/etcd/raft.(*multiNode).run(0xc208112840)
	/go/src/github.com/coreos/etcd/raft/multinode.go:236 +0xd0b
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:56 +0xb6
```
full log: https://gist.github.com/tamird/b4cdde131fe7aa464e92

discovered when running PutTest with 5 nodes.

**Comment by tschottdorf** [comment] 2015-06-09 19:13
duplicate of #1191

**Comment by bdarnell** [comment] 2015-06-09 19:14
I'm not sure this is a duplicate: the panic message is different.

**Comment by tschottdorf** [comment] 2015-06-09 19:17
oops, yeah, let's leave it open.

**Comment by bdarnell** [comment] 2015-06-11 20:33
This is caused by #876. Snapshot() calls MVCCGet in inconsistent mode to avoid WriteIntentErrors (which is safe for the range descriptor because of other magic), but now we may return WriteIntentErrors even in inconsistent mode in order to resolve them. Snapshot() needs to detect and ignore WriteIntentErrors.

**Comment by tschottdorf** [comment] 2015-06-11 20:40
that seems easy to fix. Can you update the comment for `MVCCGet` while you're at it? Also, `MVCCGetProto` should have the same semantics (returning `true` but also passing the `WriteIntentError`), though that pattern is kind of troubling.

**Closed** 2015-06-13 17:32 UTC
Labels: PTAL
