### ISSUE TITLE
pgwire+sql: support the `datestyle` session parameter

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17779] opened 2017-08-21 14:31 UTC
Reported on https://forum.cockroachlabs.com/t/odbc-and-cockroachdb/779/3

The pg ODBC driver attempts to set several session parameters including `datestyle`, which is not yet supported by CockroachDB.

We should look at the default value in pg and accept at least this default value (as a no-op) instead of returning an error. Then check if that is sufficient to enable ODBC compatibility.

**Comment by dianasaur323** [comment] 2017-08-21 14:34
cc @nstewart for prioritization

**Comment by bdarnell** [comment] 2017-08-21 17:13
Duplicate of #16452 

I think this was fixed for 1.1 with #16557, although issue #16452 has not yet been closed. Can someone verify that this works with a 1.1 alpha?

**Closed by bdarnell** 2017-08-21 17:13 UTC
Labels: easy, enhancement, helpwanted, orm-support
