### ISSUE TITLE
server: unnecessary log.Fatal when shutting down during startup

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#26817] opened 2018-06-19 04:24 UTC
As best as I can tell, attempting to start up with a canceled context results in an unnecessary `log.Fatal`:

```
I180616 05:58:21.923196 106 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  Failed to dial 10.1.7.187:26257: context canceled; please retry.
E180616 05:58:21.923204 293 storage/queue.go:656  [replicaGC,n1,s1,r101/19:/System/tsd/cr.store.queue.gc…] failed to send RPC: sending to all 2 replicas failed; last er
ror: {<nil> rpc error: code = FailedPrecondition desc = grpc: the client connection is closing}
I180616 05:58:21.923299 25034 util/stop/stopper.go:474  quiescing; tasks left:
8      kv.DistSender: sending partial batch
1      ts.poller: poll
1      node.Node: writing summary
I180616 05:58:21.923436 25034 util/stop/stopper.go:474  quiescing; tasks left:
7      kv.DistSender: sending partial batch
1      ts.poller: poll
1      node.Node: writing summary
W180616 05:58:21.923485 312 server/node.go:732  [n1,summaries] error recording initial status summaries: failed to send RPC: sending to all 1 replicas failed; last erro
r: {<nil> rpc error: code = Unavailable desc = transport is closing}
I180616 05:58:21.923516 25034 util/stop/stopper.go:474  quiescing; tasks left:
7      kv.DistSender: sending partial batch
1      ts.poller: poll
W180616 05:58:21.923520 62 gossip/gossip.go:1241  [n1] no incoming or outgoing connections
I180616 05:58:21.923536 354 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp 10.1.7.188:26257: operation was canceled"; Reconnecting to {RVMHM182S007321:26257 <nil>}
I180616 05:58:21.923558 354 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
I180616 05:58:21.923542 25034 util/stop/stopper.go:474  quiescing; tasks left:
6      kv.DistSender: sending partial batch
1      ts.poller: poll
I180616 05:58:21.923618 25034 util/stop/stopper.go:474  quiescing; tasks left:
5      kv.DistSender: sending partial batch
1      ts.poller: poll
I180616 05:58:21.923700 25034 util/stop/stopper.go:474  quiescing; tasks left:
4      kv.DistSender: sending partial batch
1      ts.poller: poll
I180616 05:58:21.923750 25034 util/stop/stopper.go:474  quiescing; tasks left:
3      kv.DistSender: sending partial batch
1      ts.poller: poll
E180616 05:58:21.923870 32 sql/jobs/registry.go:143  error while adopting jobs: failed to send RPC: sending to all 1 replicas failed; last error: {<nil> rpc error: code = Unavailable desc = transport is closing}
F180616 05:58:21.923919 25 server/server.go:1088  [n1] failed to get list of completed migrations: failed to send RPC: sending to all 1 replicas failed; last error: {<nil> rpc error: code = Unavailable desc = transport is closing}
```

Because the startup was interrupted and our context is canceled, we don't need to panic quite so hard when we can't send an RPC to get the completed migrations.

/cc @garvitjuniwal

**Comment by tschottdorf** [comment] 2018-09-27 15:17
Dupe of https://github.com/cockroachdb/cockroach/issues/19579, which has been fixed in newer versions.

**Closed by tschottdorf** 2018-09-27 15:17 UTC
Labels: A-core-kv, C-bug
