### ISSUE TITLE
teamcity: failed tests on develop: testrace/TestRaftHeartbeats

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#8917] opened 2016-08-29 22:13 UTC
[#15798](https://teamcity.cockroachdb.com/viewLog.html?buildId=15798&buildTypeId=Cockroach_UnitTests)

```
Race detected!
I160829 21:21:48.008190 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160829 21:21:48.010240 gossip/gossip.go:232  initial resolvers: []
W160829 21:21:48.010365 gossip/gossip.go:1076  not connected to cluster; use --join to specify a connected node
I160829 21:21:48.010646 gossip/gossip.go:266  NodeID set to 1
I160829 21:21:48.016248 rpc/context.go:199  dialing 127.0.0.1:37601
I160829 21:21:48.025978 gossip/gossip.go:266  NodeID set to 1
I160829 21:21:48.044541 storage/store.go:966  store=1:1: failed initial metrics computation: store=1:1: system config not yet available
I160829 21:21:48.044930 gossip/gossip.go:280  NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:37601" > attrs:<> 
I160829 21:21:48.046437 storage/replica.go:2817  [s1,r1{/Min-/Max}] gossiping cluster id {"00000000-0000-0000-0000-000000000000"} from store 1, range 1
I160829 21:21:48.057443 storage/replica.go:2209  [s1,r1{/Min-/Max}] applying command with forced error: storage/replica.go:2134: no-op on empty Raft entry
E160829 21:21:48.059376 storage/replica.go:2244  [s1,r1{/Min-/Max}] error executing raft command: storage/replica.go:2134: no-op on empty Raft entry
I160829 21:21:48.060585 storage/replica_trigger.go:308  [s1,r1{/Min-/Max}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160829 21:21:48.060725 storage/replica.go:2839  [s1,r1{/Min-/Max}] gossiping sentinel from store 1, range 1
I160829 21:21:48.061220 storage/replica.go:2846  [s1,r1{/Min-/Max}] gossiping first range from store 1, range 1: [{1 1 1}]
I160829 21:21:48.061846 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1}]
I160829 21:21:48.064194 storage/replica.go:2839  [s1,r1{/Min-/Max}] gossiping sentinel from store 1, range 1
I160829 21:21:48.064599 storage/replica.go:2846  [s1,r1{/Min-/Max}] gossiping first range from store 1, range 1: [{1 1 1}]
I160829 21:21:48.065107 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160829 21:21:48.067081 gossip/gossip.go:232  initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:37601})]
W160829 21:21:48.067223 gossip/gossip.go:1076  not connected to cluster; use --join to specify a connected node
I160829 21:21:48.067345 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1}]
I160829 21:21:48.067645 gossip/gossip.go:266  NodeID set to 2
I160829 21:21:48.071800 rpc/context.go:199  dialing 127.0.0.1:32786
I160829 21:21:48.077375 gossip/gossip.go:266  NodeID set to 2
I160829 21:21:48.079932 gossip/server.go:162  node 1: returning 5 info(s) to node 2: [system-db node:1 cluster-id sentinel first-range]
I160829 21:21:48.080486 gossip/server.go:289  node 1: received [] from node 2 (0 fresh)
I160829 21:21:48.081647 gossip/client.go:113  node 2: started gossip client to 127.0.0.1:37601
I160829 21:21:48.083853 gossip/client.go:208  node 2: received [cluster-id first-range node:1 sentinel system-db] from node 1 (5 fresh)
I160829 21:21:48.084219 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1}]
I160829 21:21:48.088340 gossip/gossip.go:280  NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:32786" > attrs:<> 
I160829 21:21:48.089706 gossip/client.go:177  node 2: sending [node:2]
I160829 21:21:48.090755 gossip/server.go:289  node 1: received [node:2] from node 2 (1 fresh)
I160829 21:21:48.091834 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160829 21:21:48.094055 gossip/gossip.go:232  initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:37601})]
W160829 21:21:48.094234 gossip/gossip.go:1076  not connected to cluster; use --join to specify a connected node
I160829 21:21:48.094493 gossip/gossip.go:266  NodeID set to 3
I160829 21:21:48.098462 rpc/context.go:199  dialing 127.0.0.1:39988
I160829 21:21:48.106361 gossip/server.go:162  node 1: returning 6 info(s) to node 3: [first-range system-db node:2 node:1 cluster-id sentinel]
I160829 21:21:48.107440 gossip/server.go:289  node 1: received [] from node 3 (0 fresh)
I160829 21:21:48.108067 gossip/client.go:113  node 3: started gossip client to 127.0.0.1:37601
I160829 21:21:48.109420 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1}]
I160829 21:21:48.110817 gossip/client.go:208  node 3: received [node:1 node:2 sentinel system-db cluster-id first-range] from node 1 (6 fresh)
I160829 21:21:48.112178 gossip/gossip.go:266  NodeID set to 3
I160829 21:21:48.115371 gossip/gossip.go:280  NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:39988" > attrs:<> 
I160829 21:21:48.118003 gossip/client.go:177  node 3: sending [node:3]
I160829 21:21:48.118966 gossip/server.go:289  node 1: received [node:3] from node 3 (1 fresh)
I160829 21:21:48.119588 gossip/server.go:162  node 1: returning 1 info(s) to node 2: [node:3]
I160829 21:21:48.121029 gossip/client.go:208  node 2: received [node:3] from node 1 (1 fresh)
I160829 21:21:48.123630 storage/replica_raftstorage.go:511  generated snapshot 6827d938-c857-4477-9849-99c297754f88 for range 1 at index 12 in 275.82µs. 2 log entries
I160829 21:21:48.127844 storage/replica_raftstorage.go:642  store=2:2 1{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 12 (id={6827d938-c857-4477-9849-99c297754f88}, encoded size=16, 1 rocksdb batches, 2 log entries)
I160829 21:21:48.129125 storage/replica_raftstorage.go:645  store=2:2 1{/Min-/Max}: with replicaID [?], applied preemptive snapshot in 0.001s
I160829 21:21:48.130153 storage/store.go:2592  streamed snapshot: kv pairs: 26, log entries: 2
I160829 21:21:48.131981 storage/replica_command.go:3055  change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I160829 21:21:48.134873 storage/replica.go:2303  [s1,r1{/Min-/Max}] applied part of replica change txn: BeginTransaction [/Local/Range/""/RangeDescriptor,/Min), ConditionalPut [/Local/Range/""/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), pErr=<nil>
I160829 21:21:48.137461 storage/replica.go:1572  [s1,r1{/Min-/Max}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160829 21:21:48.138759 storage/replica.go:2303  [s1,r1{/Min-/Max}] applied part of replica change txn: EndTransaction [/Local/Range/""/RangeDescriptor,/Min), pErr=<nil>
I160829 21:21:48.139349 storage/replica.go:2839  gossiping sentinel from store 1, range 1
I160829 21:21:48.139929 gossip/server.go:162  node 1: returning 2 info(s) to node 2: [node:3 sentinel]
I160829 21:21:48.140449 gossip/server.go:162  node 1: returning 1 info(s) to node 3: [sentinel]
I160829 21:21:48.141323 storage/replica.go:2846  gossiping first range from store 1, range 1: [{1 1 1} {2 2 2}]
I160829 21:21:48.141840 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160829 21:21:48.143046 gossip/client.go:208  node 3: received [sentinel] from node 1 (1 fresh)
I160829 21:21:48.143214 gossip/client.go:208  node 2: received [node:3 sentinel] from node 1 (1 fresh)
I160829 21:21:48.143588 gossip/server.go:162  node 1: returning 2 info(s) to node 3: [sentinel first-range]
I160829 21:21:48.143780 gossip/server.go:162  node 1: returning 3 info(s) to node 2: [first-range node:3 sentinel]
I160829 21:21:48.145231 gossip/client.go:208  node 3: received [sentinel first-range] from node 1 (1 fresh)
I160829 21:21:48.146091 gossip/client.go:208  node 2: received [first-range node:3 sentinel] from node 1 (1 fresh)
I160829 21:21:48.146331 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160829 21:21:48.146477 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I160829 21:21:48.150519 storage/replica_raftstorage.go:511  generated snapshot 0dff4183-aed5-4704-848e-cc5912ae1223 for range 1 at index 14 in 213.438µs. 4 log entries
I160829 21:21:48.153064 storage/raft_transport.go:405  raft transport stream to node 1 established
I160829 21:21:48.153293 storage/store.go:2592  streamed snapshot: kv pairs: 29, log entries: 4
I160829 21:21:48.154616 storage/replica_raftstorage.go:642  store=3:3 1{/Min-/Min}: with replicaID [?], applying preemptive snapshot at index 14 (id={0dff4183-aed5-4704-848e-cc5912ae1223}, encoded size=16, 1 rocksdb batches, 4 log entries)
I160829 21:21:48.156207 storage/replica_raftstorage.go:645  store=3:3 1{/Min-/Max}: with replicaID [?], applied preemptive snapshot in 0.001s
I160829 21:21:48.158621 storage/replica.go:2303  [s2,r1{/Min-/Max}] applied part of replica change txn: BeginTransaction [/Local/Range/""/RangeDescriptor,/Min), ConditionalPut [/Local/Range/""/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), pErr=<nil>
I160829 21:21:48.158884 storage/replica_command.go:3055  change replicas of 1: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I160829 21:21:48.159456 storage/replica.go:2303  [s2,r1{/Min-/Max}] applied part of replica change txn: EndTransaction [/Local/Range/""/RangeDescriptor,/Min), pErr=<nil>
I160829 21:21:48.160731 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
I160829 21:21:48.165898 storage/replica.go:2303  [s1,r1{/Min-/Max}] applied part of replica change txn: BeginTransaction [/Local/Range/""/RangeDescriptor,/Min), ConditionalPut [/Local/Range/""/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), pErr=<nil>
I160829 21:21:48.169325 storage/replica.go:1572  [s1,r1{/Min-/Max}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160829 21:21:48.171202 storage/replica.go:2303  [s2,r1{/Min-/Max}] applied part of replica change txn: BeginTransaction [/Local/Range/""/RangeDescriptor,/Min), ConditionalPut [/Local/Range/""/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), pErr=<nil>
I160829 21:21:48.173693 storage/replica.go:2303  [s1,r1{/Min-/Max}] applied part of replica change txn: EndTransaction [/Local/Range/""/RangeDescriptor,/Min), pErr=<nil>
I160829 21:21:48.175830 storage/replica.go:2303  [s2,r1{/Min-/Max}] applied part of replica change txn: EndTransaction [/Local/Range/""/RangeDescriptor,/Min), pErr=<nil>
I160829 21:21:48.176117 storage/replica.go:2839  gossiping sentinel from store 1, range 1
I160829 21:21:48.176542 storage/replica.go:2846  gossiping first range from store 1, range 1: [{1 1 1} {2 2 2} {3 3 3}]
I160829 21:21:48.177131 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
I160829 21:21:48.177678 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160829 21:21:48.177987 gossip/server.go:162  node 1: returning 3 info(s) to node 2: [node:3 sentinel first-range]
I160829 21:21:48.178542 gossip/server.go:162  node 1: returning 2 info(s) to node 3: [sentinel first-range]
I160829 21:21:48.179337 gossip/client.go:208  node 2: received [first-range node:3 sentinel] from node 1 (2 fresh)
I160829 21:21:48.179592 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160829 21:21:48.179915 gossip/client.go:208  node 3: received [sentinel first-range] from node 1 (2 fresh)
I160829 21:21:48.180118 kv/dist_sender.go:223  gossipped first range descriptor: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I160829 21:21:48.251824 storage/raft_transport.go:405  raft transport stream to node 1 established
I160829 21:21:48.256211 storage/replica.go:2303  [s3,r1{/Min-/Max}] applied part of replica change txn: BeginTransaction [/Local/Range/""/RangeDescriptor,/Min), ConditionalPut [/Local/Range/""/RangeDescriptor,/Min), Put [/Meta2/Max,/Min), Put [/Meta1/Max,/Min), pErr=<nil>
I160829 21:21:48.256972 storage/replica.go:2303  [s3,r1{/Min-/Max}] applied part of replica change txn: EndTransaction [/Local/Range/""/RangeDescriptor,/Min), pErr=<nil>
I160829 21:21:48.258190 storage/replica_trigger.go:458  unable to gossip first range; hasLease=false, err=<nil>
I160829 21:21:48.676598 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.677402 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.678437 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.679553 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.679951 rpc/context.go:165  closing 127.0.0.1:32786
I160829 21:21:48.680430 rpc/context.go:165  closing 127.0.0.1:37601
I160829 21:21:48.681723 rpc/context.go:165  closing 127.0.0.1:39988
I160829 21:21:48.682211 rpc/context.go:165  closing 127.0.0.1:39988
I160829 21:21:48.682530 gossip/server.go:162  node 1: returning 2 info(s) to node 3: [sentinel first-range]
==================
WARNING: DATA RACE
Write at 0x00c42035ae28 by goroutine 295:
  golang.org/x/net/trace.freeEventLog()
      /go/src/golang.org/x/net/trace/events.go:417 +0xe6
  golang.org/x/net/trace.(*eventLog).unref()
      /go/src/golang.org/x/net/trace/events.go:355 +0x6e
  golang.org/x/net/trace.(*eventLog).Finish()
      /go/src/golang.org/x/net/trace/events.go:153 +0x7b
  github.com/cockroachdb/cockroach/gossip.New.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:227 +0x46
  github.com/cockroachdb/cockroach/util/stop.CloserFn.Close()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:86 +0x34
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:365 +0x434
  github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop.func1()
      /go/src/github.com/cockroachdb/cockroach/storage/client_test.go:338 +0x26f

Previous write at 0x00c42035ae28 by goroutine 349:
  golang.org/x/net/trace.(*eventLog).printf()
      /go/src/golang.org/x/net/trace/events.go:323 +0x282
  golang.org/x/net/trace.(*eventLog).Printf()
      /go/src/golang.org/x/net/trace/events.go:311 +0x6f
  github.com/cockroachdb/cockroach/util/log.Event()
      /go/src/github.com/cockroachdb/cockroach/util/log/trace.go:64 +0x1a5
  github.com/cockroachdb/cockroach/util/log.addStructured()
      /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:64 +0x1b7
  github.com/cockroachdb/cockroach/util/log.logDepth()
      /go/src/github.com/cockroachdb/cockroach/util/log/log.go:70 +0x99
  github.com/cockroachdb/cockroach/util/log.Infof()
      /go/src/github.com/cockroachdb/cockroach/util/log/log.go:78 +0x8f
  github.com/cockroachdb/cockroach/gossip.(*server).Gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/server.go:162 +0xc56
  github.com/cockroachdb/cockroach/gossip._Gossip_Gossip_Handler()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.pb.go:211 +0xd9
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /go/src/google.golang.org/grpc/server.go:686 +0xc7c
  google.golang.org/grpc.(*Server).handleStream()
      /go/src/google.golang.org/grpc/server.go:770 +0x170d
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /go/src/google.golang.org/grpc/server.go:419 +0xb8

Goroutine 295 (running) created at:
  github.com/cockroachdb/cockroach/storage_test.(*multiTestContext).Stop()
      /go/src/github.com/cockroachdb/cockroach/storage/client_test.go:344 +0x94
  github.com/cockroachdb/cockroach/storage_test.TestRaftHeartbeats()
      /go/src/github.com/cockroachdb/cockroach/storage/client_raft_test.go:1330 +0x362
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:610 +0xc9

Goroutine 349 (finished) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /go/src/google.golang.org/grpc/server.go:420 +0xba
  google.golang.org/grpc/transport.(*http2Server).operateHeaders()
      /go/src/google.golang.org/grpc/transport/http2_server.go:221 +0x126d
  google.golang.org/grpc/transport.(*http2Server).HandleStreams()
      /go/src/google.golang.org/grpc/transport/http2_server.go:282 +0x7f3
  google.golang.org/grpc.(*Server).serveStreams()
      /go/src/google.golang.org/grpc/server.go:421 +0x1d5
  google.golang.org/grpc.(*Server).serveNewHTTP2Transport()
      /go/src/google.golang.org/grpc/server.go:408 +0x4f0
  google.golang.org/grpc.(*Server).handleRawConn()
      /go/src/google.golang.org/grpc/server.go:385 +0x54c
==================
I160829 21:21:48.683609 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.683703 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
I160829 21:21:48.991718 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.991830 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
I160829 21:21:48.992130 util/stop/stopper.go:342  stop has been called, stopping or quiescing all running tasks
I160829 21:21:48.992237 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
```

**Comment by tamird** [comment] 2016-08-29 22:46
Dupe of #8905.

**Closed by tamird** 2016-08-29 22:46 UTC
Labels: test-failure
