### ISSUE TITLE
gss: TestGSSFileDescriptorCount is skipped

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51791] opened 2020-07-22 20:28 UTC
```
	// When the docker-compose.yml added a ulimit for the cockroach
	// container the open file count would just stop there, it wouldn't
	// cause cockroach to panic or error like I had hoped since it would
	// allow a test to assert that multiple gss connections didn't leak
	// file descriptors. Another possibility would be to have something
	// track the open file count in the cockroach container, but that seems
	// brittle and probably not worth the effort. However this test is
	// useful when doing manual tracking of file descriptor count.
```

Jira issue: CRDB-4015

**Comment by spaskob** [comment] 2021-02-12 22:53
@jordanlewis please add to an appropriate project board.

**Comment by knz** [comment] 2021-08-30 12:29
@catj-cockroach and @jlinder  I'd like your advice on this one. In summary:

- we had a test that verifies that crdb does not leak file descriptors, by checking that the total number of fds does not grow unbounded under load.
- this test got broken when we changed our container config to limit the max number of fds in the container, whereby the process gets a "too many fds" error too early.

We have an interest in the test because the customers using this feature typically do not restrict their fds / run on bare metal. What to do?

**Comment by catj-cockroach** [comment] 2021-08-30 19:15
> this test got broken when we changed our container config to limit the max number of fds in the container, whereby the process gets a "too many fds" error too early.

@knz I'd agree that this test is worth keeping! This strikes me as being a case where we would want to run the tests outside of a container (spin up a VM and test there). Are the thresholds for when we throw the "too many fds" error configurable?

**Comment by knz** [comment] 2021-08-31 12:48
> Are the thresholds for when we throw the "too many fds" error configurable?

I don't know.
(For context, we more or less lost all of our internal expertise on the GSS code. Whatever needs to happen now, needs to be reverse-engineered from the code first.)

**Comment by rafiss** [comment] 2023-08-22 18:39
This issue just landed on the SQL Foundations board. Do we still feel that this is a test worth keeping? My understanding from the above is that the only way to make it work is to rewrite the test so it does not run in a Docker container, but I don't know if we have the tools for that.

**Comment by knz** [comment] 2023-08-22 20:41
The alternative as described in the comment at the very top of the issue is to use process inspection to count the number of active file descriptors. we can maybe use our gosigar dependency for that, in which case the test would not any more require a descriptor limit to be set.

**Closed** 2023-08-23 23:54 UTC
Labels: C-cleanup, skipped-test, T-sql-foundations, A-authentication
