### ISSUE TITLE
sql: support DO statement for running running anonymous code blocks

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#107345] opened 2023-07-21 14:00 UTC
**Describe the problem**

Running the following SQL 

```
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'test') THEN
        CREATE SCHEMA test;
    END IF;
END $EF$;
```

will return error `ERROR: at or near "do": syntax error`

See the [Postgres documentation](https://www.postgresql.org/docs/current/sql-do.html) for more details on the `DO` statement.

**Additional context**

What was the impact?

This issue is affecting a number of tests in efcore.pg library

Jira issue: CRDB-30000

**Comment by rafiss** [comment] 2023-07-25 18:39
Tagging the SQL Queries team, as this may be related to ongoing work with plpgsql. (And there may already be a different issue to track this)

**Comment by Enalmada** [comment] 2023-09-27 18:18
Could we get an update here?   [Drizzle ORM](https://github.com/drizzle-team/drizzle-orm) migrations output DO for duplicate_object checking and I don't believe that is going to change anytime soon.  Supporting this would go a long way toward being able to get Drizzle users to seriously consider CockroachDB as a viable option.

```
DO $$ BEGIN
 CREATE TYPE "status" AS ENUM('ACTIVE', 'COMPLETED');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
```

**Comment by mgartner** [comment] 2023-10-09 20:37
Thanks for the feedback @Enalmada. In v23.2 we're supporting PLpgSQL functions and procedures for the first time, which brings us a step closer towards supporting anonymous code blocks. We'll keep this issue updated with more information when we have it.

**Comment by DrewKimball** [comment] 2024-12-19 18:58
This is a duplicate of #115268 - you can follow any updates there.

**Closed by DrewKimball** 2024-12-19 18:58 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries, A-tools-efcore, A-sql-plpgsql
