### ISSUE TITLE
kvserver: RANGE_CONSISTENT_STATS_INCORRECT via kvnemesis

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#93184] opened 2022-12-07 07:55 UTC
via kvnemesis on #89477:

```
range 54 (/Table/53) RANGE_CONSISTENT_STATS_INCORRECT: stats: {ContainsEstimates:0 LastUpdateNanos:1670373332207974387 IntentAge:0 GCBytesAge:0 LiveBytes:0 LiveCount:0 KeyBytes:0 KeyCount:0 ValBytes:0 ValCount:0 IntentBytes:0 IntentCount:0 SeparatedIntentCount:0 RangeKeyCount:0 RangeKeyBytes:0 RangeValCount:0 RangeValBytes:0 SysBytes:3475 SysCount:13 AbortSpanBytes:0}

13702 runs completed, 1 failures, over 3h7m25s

```

[failure.tgz](https://github.com/cockroachdb/cockroach/files/10173857/failure.tgz)

Jira issue: CRDB-22209

**Comment by nvanbenschoten** [comment] 2023-03-13 20:38
@tbg @erikgrinaker do you know whether this is a duplicate of https://github.com/cockroachdb/cockroach/issues/98473?

**Comment by erikgrinaker** [comment] 2023-03-13 20:46
It's a dupe of #93896 and #94876.

**Closed by erikgrinaker** 2023-03-13 20:46 UTC
Labels: C-bug, T-kv
