### ISSUE TITLE
context canceled for basic aggregate/join queries

### ISSUE THREAD

**Issue by dankinder** [cockroachdb/cockroach#54034] opened 2020-09-08 16:40 UTC
**Describe the problem**

As I'm evaluating CRDB, I'm seeing the following error for several pretty basic aggregation and join queries. I'll give 2 examples below, one is a pretty standard join between a small and large table, another is simply `count(distinct(key))`.
```
ERROR: communication error: rpc error: code = Canceled desc = context canceled
SQLSTATE: 58C01
```
It's an unhelpful message, I don't see anything interesting in the logs, the nodes don't take a whole lot of mem or cpu, don't crash, and since these queries cover quite a few ranges the traces are horribly long. It'd be nice to know if there is any configuration that can mitigate this.

**To Reproduce**

(Note: I can't provide the real data or schema for these)

_Query 1: basic join with a large table_
This database is 5 nodes on SSD, little over 300GB of data. CRDB v20.1.3.

Schema:
```
CREATE TABLE table1 (
    id integer NOT NULL,
    name text NOT NULL
   --  ... some other stuff ...
);

CREATE TABLE table2 (
   id integer NOT NULL,
   table1_id integer
   -- ... some other stuff ...
);
```

Load table1 with 2MB of data, and table2 with 300GB.
```
> select count(*) from table2 inner join table1 on table2.table1_id = table1.id group by table1.name;
ERROR: communication error: rpc error: code = Canceled desc = context canceled
SQLSTATE: 58C01
```

_Query 2: basic aggregation_
This database is 3 nodes on SSD, about 3TB of data (1TB/node, at R=3). CRDB v20.1.4.

Schema:
```
CREATE TABLE t (
    key INT8 NOT NULL,
    value INT8 NOT NULL,
    PRIMARY KEY (key, value)
);
```

Load this table with 60 billion rows, then:
```
 select count(distinct(key)) from t;
ERROR: communication error: rpc error: code = Canceled desc = context canceled
SQLSTATE: 58C01
```

**Expected behavior**
Successful query completion.

**Environment:**
 - Server OS: Centos 7
 - Client app: `cockroach sql`

**Comment by jordanlewis** [comment] 2020-09-08 18:44
@dankinder, thanks for the report. Agreed these aren't helpful error messages. We often seen context canceled errors if the cluster is somehow underresourced. What kind of nodes are you running the database on? Especially interested in memory and number of vCPUS.

**Comment by dankinder** [comment] 2020-09-08 19:12
The cluster for query 1 (5-node) is just 5 different disks (jbod) in the same server with 48vCPU and 64GB RAM. (I'm aware that's not a recommended setup, but this is just a trial. And the cockroach nodes don't seem to come even close to maximally using those resources.)

The cluster for query 2 is 3 independent hosts, each with 40vCPU and 64GB RAM. We're using 2 disks per host as well, but doing that via 2 `--store` flags in one CRDB node.

**Comment by jordanlewis** [comment] 2020-09-08 19:18
Thanks. That should obviously be more than enough for the queries in question. We'll look into this.

**Comment by asubiotto** [comment] 2020-09-09 10:44
Hi @dankinder, I'm going to try to reproduce the query 1 failure with a synthetic dataset on my end. In the meantime, could you share the logs from around the time of failure from all 5 nodes?

**Comment by dankinder** [comment] 2020-09-09 22:58
[cockroach-5.log](https://github.com/cockroachdb/cockroach/files/5198280/cockroach-5.log)
[cockroach-4.log](https://github.com/cockroachdb/cockroach/files/5198281/cockroach-4.log)
[cockroach-3.log](https://github.com/cockroachdb/cockroach/files/5198282/cockroach-3.log)
[cockroach-2.log](https://github.com/cockroachdb/cockroach/files/5198283/cockroach-2.log)
[cockroach-1.log](https://github.com/cockroachdb/cockroach/files/5198284/cockroach-1.log)

Also, the only flags I'm passing to cockroach other than certs-dir/join/listen-addr/http-addr are `--max-sql-memory=.15` and `--store=path=/srv/disk1/cockroach-data-node1,attrs=ssd`

**Comment by dankinder** [comment] 2020-09-09 23:10
I should also mention, for query 1, table1 (24 columns) has about 16k rows, table2 (42 columns) has 400M.

**Comment by asubiotto** [comment] 2020-09-10 11:55
In the logs (specifically in `cockroach-4.log`) is the cause of the error:
```
W200909 22:26:35.340009 5135158 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26262 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.342407 5135104 kv/kvserver/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 1: rpc error: code = Unavailable desc = transport is closing:
W200909 22:26:35.356316 5135171 kv/kvserver/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 5: rpc error: code = Unavailable desc = transport is closing:
W200909 22:26:35.366013 5135173 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26258 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.391273 5135097 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26260 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.394860 5135112 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26259 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.405962 5135109 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26258 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.411821 5135161 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26262 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.453957 43815288 vendor/google.golang.org/grpc/clientconn.go:1206  grpc: addrConn.createTransport failed to connect to {seu-ssdchunk67.s2prod:26258 0  <nil>}. Err :connection error: desc = "transport: Error while dialing cannot reuse client connection". Reconnecting...
W200909 22:26:35.458357 40642320 kv/kvserver/raft_transport.go:637  [n3] while processing outgoing Raft queue to node 5: rpc error: code = Unavailable desc = transport is closing:
W200909 22:26:35.497399 139 gossip/gossip.go:1516  [n3] first range unavailable; resolvers exhausted
E200909 22:26:35.577456 5135074 rpc/context.go:1002  [n3] removing connection to seu-ssdchunk67.s2prod:26258 due to error: cannot reuse client connection
W200909 22:26:35.737906 312 kv/kvserver/store_raft.go:508  [n3,s3,r2/4:/System/NodeLiveness{-Max}] handle raft ready: 10.7s [applied=0, batches=0, state_assertions=0]
```

The connection is closed and most likely is what results in the grpc error you observe `ERROR: communication error: rpc error: code = Canceled desc = context canceled`. The other interesting part of the logs is this line:
```
W200909 22:26:35.737906 312 kv/kvserver/store_raft.go:508  [n3,s3,r2/4:/System/NodeLiveness{-Max}] handle raft ready: 10.7s [applied=0, batches=0, state_assertions=0]
```
This log message usually indicates that the cluster is overloaded. When I've previously in these situations is that due to the overload a GRPC heartbeat does not occur in time and the connection is closed. This is curious given the specs you shared though. Can you double-check maximum CPU and memory usage during these queries?

**Comment by dankinder** [comment] 2020-09-10 14:34
So this is very interesting, I got a different error running it this time while tracking performance. The error is
```
ERROR: root: memory budget exceeded: 10240 bytes requested, 10115348480 currently allocated, 10115351961 bytes in budget
SQLSTATE: 53200
```
Maybe in previous runs it was running out of memory and starting to page, such that the heartbeat failed before we hit this "memory budget exceeded" error?

I hadn't noticed before that memory does spike right at the end of the query. You can also see a strange pattern here where after some initial work, one process just chugs along for a while.
![Screen Shot 2020-09-10 at 10 21 23 AM](https://user-images.githubusercontent.com/5198575/92744456-848cb000-
f34f-11ea-8567-2d5a0e60e90a.png)

Zooming in on the last 15 minutes
![Screen Shot 2020-09-10 at 10 28 13 AM](https://user-images.githubusercontent.com/5198575/92746199-09c49480-f351-11ea-888d-68cc2d756496.png)

I guess the big question is what consumed so much memory there at the end. I did pass `--max-sql-memory=.15`, so it doesn't make much sense.

**Comment by dankinder** [comment] 2020-09-10 14:55
Also here's the explain for this query:
```
              tree              |     field      |     description
--------------------------------+----------------+-----------------------
                                | distributed    | true
                                | vectorized     | false
  render                        |                |
   └── group                    |                |
        │                       | aggregate 0    | name
        │                       | aggregate 1    | count_rows()
        │                       | group by       | name
        └── render              |                |
             └── merge-join     |                |
                  │             | type           | inner
                  │             | equality       | (table1_id) = (id)
                  │             | mergeJoinOrder | +"(table1_id=id)"
                  ├── scan      |                |
                  │             | table          | table2@table1_id_idx
                  │             | spans          | FULL SCAN
                  └── sort      |                |
                       │        | order          | +id
                       └── scan |                |
                                | table          | table1@primary
                                | spans          | FULL SCAN
(20 rows)
```

**Comment by dankinder** [comment] 2020-09-10 15:42
Yeah this is the only query going on, there is no other notable activity on the host at all.

There shouldn't be any IO starvation, each process is writing logs and everything to the store disk, not a central log directory. Disk util doesn't seem to exceed a few %
![Screen Shot 2020-09-10 at 11 35 49 AM](https://user-images.githubusercontent.com/5198575/92755474-da665580-f359-11ea-8f49-7f27b643e97e.png)

Your theory that the issue is with lacking disk spilling for aggregations sounds reasonable. There aren't that many groups (only 10 distinct values of the `name` column in this case), but it's a lot of data being sorted into those groups for counting. I'll try upping max-sql-memory and see what happens.

I'll set GOMAXPROCS as well in case it makes any difference.

Thanks for the help!

**Comment by asubiotto** [comment] 2020-09-10 16:13
> Your theory that the issue is with lacking disk spilling for aggregations sounds reasonable. There aren't that many groups (only 10 distinct values of the name column in this case), but it's a lot of data being sorted into those groups for counting. I'll try upping max-sql-memory and see what happens.

If there are only 10 distinct values of the name column, then the theory goes out the window because memory usage in hash aggregations is only proportional to the number of groups (in this case 10). There is a slight possibility that the merge joiner runs into the same issue with the ID column since it needs to materialize a cross product for rows with the same ID, but the best thing to do would be to collect a profile while the memory usage is high to figure out what actually allocated the memory. You can get the profile from: `http://<your_admin_ui_url>/debug/pprof/heap?debug=1 `, another alternative is to get a debug zip: https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html which also includes a lot more information while the query is running.

**Comment by yuzefovich** [comment] 2020-09-10 17:49
@dankinder thanks for providing all the information!

I agree with @asubiotto that the memory budget is likely to be reached during the merge join operation because we buffer up all rows with the same ID in memory (a side comment is that, theoretically we only have to buffer rows from the right side, but it is not implemented). I would be interested if you could try `SET vectorize=on;` and then run the query again - this should make the query run via the vectorized execution engine, and in the vectorized merge joiner we do have the disk-spilling support for exactly this case of many rows having the same values in the equality columns.

**Comment by dankinder** [comment] 2020-09-10 19:25
Wow, `SET vectorize=on;` not only worked, the query finished in 3m33s! Previous runs were going for ~1h15m before timing out. Too bad it isn't using the vectorized engine automatically.

Sadly query 2 still fails with context cancelled.

**Comment by yuzefovich** [comment] 2020-09-10 19:31
Glad to hear that now at least one query works well :) To provide some more color, we think that the vectorized engine is mature enough in 20.1 release, so it is reasonable to have it as `on` (i.e. `SET CLUSTER SETTING sql.defaults.vectorize=on;`), but we decided to take a more cautious approach in 20.1 release, so we kept a more defensive setting `auto` as the default. In 20.2 `vectorize=on` will be the default option.

I'll let Alfonso follow-up regarding the query 2 since he has better context on the issue.

**Comment by asubiotto** [comment] 2020-09-11 07:50
That's great to hear! Could you fetch a [debug zip](https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html) from the second cluster after the query completes with a cancellation error? Could you also share CPU/Mem/Disk utilization during the query?

**Comment by dankinder** [comment] 2020-09-11 12:51
Sure, I'm out today but will circle back next week.

**Comment by asubiotto** [comment] 2020-09-21 09:50
Hi @dankinder are you still having issues?

**Comment by dankinder** [comment] 2020-09-28 16:47
Yes, sorry I have been full up with other work.

As a brief note, query 2 does go for much longer using the vectorized engine than not before the context gets cancelled. Like, 12+ hours rather than ~1 hour.

@asubiotto debug zips can contain sensitive data right? Is there a way I can send you that without posting those here?

**Comment by asubiotto** [comment] 2020-09-29 07:54
They do. You can send them to me directly at alfonso@cockroachlabs.com

**Comment by dankinder** [comment] 2020-10-23 19:00
Hi @asubiotto I haven't forgotten about this but have been busy. I just emailed you debug zips.

Btw I was able to make the query work (sort of) by doing this instead: `select count(*) from (select key from t group by key);` -- equivalent to the failing query `select count(distinct(key)) from t;`

**Comment by andreimatei** [comment] 2021-07-12 23:18
I think it's time to be honest and close this, in the hope that more recent versions do better or there's a new repro.

**Closed by andreimatei** 2021-07-12 23:18 UTC
Labels: C-bug, O-community, T-sql-queries, X-blathers-triaged
