### ISSUE TITLE
rangefeed: regression in `Rangefeed` benchmark

### ISSUE THREAD

**Issue by arulajmani** [cockroachdb/cockroach#123076] opened 2024-04-25 19:10 UTC
**Describe the problem**

We bisected a regression in `Rangefeed` benchmark down to https://github.com/cockroachdb/cockroach/commit/13c9b9d1903eda3fc303ed6b54bda25d5a012313: 

```
building benchmark binaries for 'bf24702' 1/1 -
test binaries already exist for '13c9b9d'; skipping build
  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/kv/kvserver/rangefeed |

name                                                         old time/op    new time/op    delta
Rangefeed/procType=scheduler/opType=closedts/numRegs=10-24     7.69µs ± 2%    8.04µs ± 2%   +4.55%  (p=0.000 n=10+8)
Rangefeed/procType=scheduler/opType=closedts/numRegs=100-24     125µs ±14%     140µs ±10%  +11.87%  (p=0.002 n=10+10)
Rangefeed/procType=scheduler/opType=closedts/numRegs=1-24      1.06µs ± 2%    1.19µs ± 8%  +12.47%  (p=0.000 n=8+10)

name                                                         old alloc/op   new alloc/op   delta
Rangefeed/procType=scheduler/opType=closedts/numRegs=1-24        270B ± 1%      317B ± 1%  +17.54%  (p=0.000 n=10+10)
Rangefeed/procType=scheduler/opType=closedts/numRegs=100-24      367B ± 5%      455B ± 4%  +24.04%  (p=0.000 n=10+9)
Rangefeed/procType=scheduler/opType=closedts/numRegs=10-24       321B ± 1%      434B ± 1%  +35.13%  (p=0.000 n=10+10)

name                                                         old allocs/op  new allocs/op  delta
Rangefeed/procType=scheduler/opType=closedts/numRegs=100-24      6.00 ± 0%      7.00 ± 0%  +16.67%  (p=0.000 n=10+8)
Rangefeed/procType=scheduler/opType=closedts/numRegs=1-24        5.00 ± 0%      6.00 ± 0%  +20.00%  (p=0.000 n=10+10)
Rangefeed/procType=scheduler/opType=closedts/numRegs=10-24       5.00 ± 0%      7.00 ± 0%  +40.00%  (p=0.000 n=10+10)
```

I haven't compared CPU/memory profiles. @wenyihu6, could I ask you to investigate this given you authored the change? 

Jira issue: CRDB-38189

**Comment by wenyihu6** [comment] 2024-04-25 19:12
Ack, taking a look.

**Comment by wenyihu6** [comment] 2024-04-25 20:59
From an initial look, the biggest difference came from `enqueueEventInternal` which is expected since we are now more strict with memory accounting and allocating a larger size with `calculateDateEventSize`. I will keep looking into it to confirm my theory here.

| Before| After |
| -| - |
| <img width="200" alt="Screenshot 2024-04-25 at 4 53 15 PM" src="https://github.com/cockroachdb/cockroach/assets/56973754/4e96fb6b-b02c-48b9-bcca-f0319b449c92"> |<img width="200" alt="Screenshot 2024-04-25 at 4 53 12 PM" src="https://github.com/cockroachdb/cockroach/assets/56973754/91ef73fd-012b-4414-9450-656c58c18b58">

**Comment by wenyihu6** [comment] 2024-04-29 17:29
I took another look at this - there are three things to highlight here: 
I noticed that there were regressions in cpu and allocations due to the presence of my changes, even when they weren’t being called (budget=false). After some trial and error, I was able to significantly improve the regression in this benchmark (PR link here). I doubt this will have a real world impact though. 

<details>
<summary>Improvement</summary>

```
❯ benchdiff --new=a6e678fd7cb --old=13c9b9   --post-checkout='bash post-checkout.sh' --run=BenchmarkRangefeed --count=10  ./pkg/kv/kvserver/rangefeed
test binaries already exist for '13c9b9d'; skipping build
test binaries already exist for 'a6e678f'; skipping build
  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/kv/kvserver/rangefeed /
name                                                                      old time/op    new time/op    delta
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12      118µs ±14%      83µs ±62%  -29.72%  (p=0.002 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12        131µs ±12%     100µs ±43%  -23.78%  (p=0.001 n=8+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12        119µs ±13%     102µs ±24%  -13.96%  (p=0.015 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12           561ns ±10%     524ns ± 3%   -6.55%  (p=0.001 n=10+8)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12       457ns ±10%     428ns ± 6%   -6.47%  (p=0.007 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12          513ns ± 3%     503ns ± 5%     ~     (p=0.113 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12        6.15µs ±39%    5.41µs ±31%     ~     (p=0.165 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12        1.40µs ± 3%    1.40µs ± 7%     ~     (p=1.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12       6.07µs ±18%    6.15µs ±24%     ~     (p=0.971 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12       106µs ±29%     119µs ±10%     ~     (p=0.077 n=9+9)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12     5.00µs ±41%    4.77µs ±39%     ~     (p=0.670 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12     119µs ±17%     117µs ±25%     ~     (p=0.604 n=10+9)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12         5.59µs ±22%    5.83µs ±30%     ~     (p=0.481 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12         102µs ±60%      89µs ±62%     ~     (p=0.631 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12         1.63µs ± 4%    1.68µs ± 6%     ~     (p=0.108 n=9+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12        6.36µs ±18%    6.07µs ± 6%     ~     (p=0.395 n=10+8)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12        477ns ± 7%     460ns ± 5%     ~     (p=0.065 n=10+9)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12      5.08µs ±15%    5.24µs ±22%     ~     (p=0.684 n=10+10)
RangefeedBudget/budget=false-12                                              533ns ± 7%     530ns ± 9%     ~     (p=0.631 n=10+10)
RangefeedBudget/budget=true-12                                               546ns ± 8%     535ns ± 5%     ~     (p=0.182 n=9+10)
name                                                                      old alloc/op   new alloc/op   delta
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12         340B ± 2%      262B ± 2%  -22.79%  (p=0.000 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12        359B ± 2%      285B ± 2%  -20.61%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12       414B ± 2%      332B ± 2%  -19.81%  (p=0.000 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12        957B ± 3%      782B ± 4%  -18.29%  (p=0.000 n=9+9)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12      439B ± 5%      359B ±17%  -18.28%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12         932B ± 4%      764B ± 6%  -18.01%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12        452B ± 2%      374B ± 2%  -17.27%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12          927B ± 4%      774B ± 4%  -16.56%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12            473B ± 3%      395B ± 1%  -16.34%  (p=0.000 n=10+8)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12          955B ± 1%      806B ± 5%  -15.65%  (p=0.000 n=8+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12           944B ± 4%      797B ± 5%  -15.61%  (p=0.000 n=10+10)
RangefeedBudget/budget=true-12                                                469B ± 1%      397B ± 1%  -15.39%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12           488B ± 1%      413B ± 1%  -15.37%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12       1.01kB ± 5%    0.85kB ± 8%  -15.31%  (p=0.000 n=10+10)
RangefeedBudget/budget=false-12                                               490B ± 1%      416B ± 2%  -15.18%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12          539B ± 1%      459B ± 3%  -14.86%  (p=0.000 n=8+9)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12           584B ± 2%      502B ± 1%  -14.11%  (p=0.000 n=9+9)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12       480B ± 8%      418B ±13%  -12.94%  (p=0.001 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12         555B ± 1%      486B ± 4%  -12.47%  (p=0.000 n=8+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12          601B ± 5%      534B ± 4%  -11.15%  (p=0.000 n=8+9)
name                                                                      old allocs/op  new allocs/op  delta
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12       6.60 ± 9%      5.00 ± 0%  -24.24%  (p=0.000 n=10+8)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12         12.0 ± 0%      10.0 ± 0%  -16.67%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12        12.0 ± 0%      10.0 ± 0%  -16.67%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12        6.00 ± 0%      5.00 ± 0%  -16.67%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12           12.0 ± 0%      10.0 ± 0%  -16.67%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12         6.00 ± 0%      5.00 ± 0%  -16.67%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12         13.0 ± 0%      11.0 ± 0%  -15.38%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12          11.0 ± 0%       9.4 ± 6%  -14.55%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12      7.00 ± 0%      6.00 ± 0%  -14.29%  (p=0.000 n=9+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12        7.00 ± 0%      6.00 ± 0%  -14.29%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12          12.0 ± 0%      10.3 ± 7%  -14.17%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12           8.00 ± 0%      7.00 ± 0%  -12.50%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12            8.00 ± 0%      7.00 ± 0%  -12.50%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12       8.00 ± 0%      7.00 ± 0%  -12.50%  (p=0.000 n=7+10)
RangefeedBudget/budget=false-12                                               8.00 ± 0%      7.00 ± 0%  -12.50%  (p=0.000 n=10+10)
RangefeedBudget/budget=true-12                                                8.00 ± 0%      7.00 ± 0%  -12.50%  (p=0.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12         9.00 ± 0%      8.00 ± 0%  -11.11%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12           9.00 ± 0%      8.00 ± 0%  -11.11%  (p=0.000 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12          10.0 ± 0%       9.0 ± 0%  -10.00%  (p=0.000 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12          8.00 ± 0%      7.30 ±10%   -8.75%  (p=0.001 n=8+10)
```
</details>

Despite the improvement, some regressions still persist in this patch. 
<details>

```
❯ benchdiff --new=a6e678fd7cb --old=f50e8fc   --post-checkout='bash post-checkout.sh' --run=BenchmarkRangefeed --count=10  ./pkg/kv/kvserver/rangefeed
checking out 'f50e8fc'
building benchmark binaries for 'a6e678f' 1/1 /
  pkg=1/1 iter=10/10 cockroachdb/cockroach/pkg/kv/kvserver/rangefeed /
name                                                                      old time/op    new time/op    delta
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12          514ns ± 8%     497ns ± 5%      ~     (p=0.063 n=9+9)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12        5.47µs ±29%    5.33µs ±24%      ~     (p=0.912 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12        1.39µs ± 4%    1.38µs ± 5%      ~     (p=0.359 n=8+9)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12       5.26µs ±11%    5.56µs ±17%      ~     (p=0.243 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12       439ns ±11%     432ns ± 5%      ~     (p=0.780 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12     4.49µs ±16%    4.58µs ±23%      ~     (p=0.684 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12         5.53µs ±19%    5.31µs ±14%      ~     (p=0.529 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12        5.84µs ± 8%    5.95µs ± 3%      ~     (p=0.423 n=9+8)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12      4.36µs ±29%    4.82µs ±21%      ~     (p=0.218 n=10+10)
RangefeedBudget/budget=false-12                                              510ns ± 3%     519ns ±12%      ~     (p=0.579 n=10+10)
RangefeedBudget/budget=true-12                                               525ns ± 5%     534ns ± 8%      ~     (p=0.497 n=10+9)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12         1.62µs ± 3%    1.68µs ± 7%    +3.94%  (p=0.016 n=9+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12           519ns ± 3%     540ns ± 6%    +4.01%  (p=0.029 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12        424ns ± 7%     455ns ± 4%    +7.29%  (p=0.001 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12      55.4µs ±83%   107.5µs ±34%   +94.00%  (p=0.002 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12   50.0µs ±154%   103.9µs ±49%  +108.09%  (p=0.002 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12        36.7µs ±22%    85.3µs ±66%  +132.56%  (p=0.027 n=8+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12    55.1µs ±108%   130.5µs ±17%  +137.06%  (p=0.000 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12       41.5µs ±79%   106.0µs ±42%  +155.34%  (p=0.000 n=9+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12       35.7µs ± 4%   103.2µs ±64%  +189.21%  (p=0.000 n=8+10)
name                                                                      old alloc/op   new alloc/op   delta
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12      389B ±11%      339B ±16%   -12.84%  (p=0.009 n=10+8)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12         281B ± 0%      259B ± 2%    -7.83%  (p=0.000 n=8+9)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12         899B ± 7%      844B ± 7%    -6.11%  (p=0.002 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12        823B ± 3%      786B ± 5%    -4.55%  (p=0.003 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12          560B ± 7%      535B ± 5%    -4.41%  (p=0.017 n=10+9)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12           415B ± 1%      413B ± 1%      ~     (p=0.374 n=10+7)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12          460B ± 1%      459B ± 2%      ~     (p=0.732 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12         498B ± 4%      487B ± 6%      ~     (p=0.114 n=7+10)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12          770B ± 6%      788B ± 1%      ~     (p=0.139 n=10+8)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12         776B ± 5%      769B ± 4%      ~     (p=0.541 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12        285B ± 2%      286B ± 2%      ~     (p=0.563 n=9+10)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12       330B ± 1%      330B ± 1%      ~     (p=0.641 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12           503B ± 2%      503B ± 1%      ~     (p=0.919 n=10+9)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12           792B ± 7%      796B ± 6%      ~     (p=0.351 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12          818B ± 4%      806B ± 6%      ~     (p=0.425 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12       394B ±14%      421B ±19%      ~     (p=0.106 n=10+8)
RangefeedBudget/budget=false-12                                               412B ± 1%      414B ± 1%      ~     (p=0.805 n=10+10)
RangefeedBudget/budget=true-12                                                392B ± 0%      396B ± 0%    +1.16%  (p=0.000 n=8+7)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12            393B ± 1%      398B ± 2%    +1.20%  (p=0.002 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12        329B ± 1%      372B ± 3%   +12.92%  (p=0.000 n=8+8)
name                                                                      old allocs/op  new allocs/op  delta
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=1-12          9.40 ± 6%      9.00 ± 0%    -4.26%  (p=0.046 n=10+8)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=1-12           7.00 ± 0%      7.00 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=10-12          7.30 ±10%      7.30 ±10%      ~     (p=1.000 n=10+10)
Rangefeed/budget=false/procType=scheduler/opType=write/numRegs=100-12         8.00 ± 0%      8.00 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=10-12         10.0 ± 0%      10.0 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=commit/numRegs=100-12        10.0 ± 0%      10.0 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=1-12        5.00 ± 0%      5.00 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=10-12       5.00 ± 0%      5.00 ± 0%      ~     (all equal)
Rangefeed/budget=false/procType=scheduler/opType=closedts/numRegs=100-12      6.00 ± 0%      6.00 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=1-12            7.00 ± 0%      7.00 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=10-12           8.00 ± 0%      8.00 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=write/numRegs=100-12          9.00 ± 0%      9.00 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=1-12           10.0 ± 0%      10.0 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=10-12          10.6 ± 6%      10.4 ± 6%      ~     (p=0.656 n=10+10)
Rangefeed/budget=true/procType=scheduler/opType=commit/numRegs=100-12         11.0 ± 0%      11.0 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=1-12         5.00 ± 0%      5.00 ± 0%      ~     (all equal)
RangefeedBudget/budget=false-12                                               7.00 ± 0%      7.00 ± 0%      ~     (all equal)
RangefeedBudget/budget=true-12                                                7.00 ± 0%      7.00 ± 0%      ~     (all equal)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=100-12       6.00 ± 0%      7.00 ± 0%   +16.67%  (p=0.000 n=10+8)
Rangefeed/budget=true/procType=scheduler/opType=closedts/numRegs=10-12        5.00 ± 0%      6.00 ± 0%   +20.00%  (p=0.000 n=8+8)
❯ 
```
</details>

Some parts of the regressions are expected and understandable[^1]. We are now accounting memory for checkpoint events which involve additional overhead such as getting an allocation token from the pool for every checkpoint event. This is why we saw a significant increase in allocations for closedts only. 

<details>

```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.(*FeedBudget).TryGet in github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed/budget.go
   65.42ms   668.56ms (flat, cum)  0.79% of Total
         .          .    159:func (f *FeedBudget) TryGet(ctx context.Context, amount int64) (*SharedBudgetAllocation, error) {
    9.67ms    47.06ms    160:   if !RangefeedBudgetsEnabled.Get(f.settings) {
         .          .    161:           return nil, nil
         .          .    162:   }
         .    35.42ms    163:   f.mu.Lock()
   28.37ms    28.37ms    164:   defer f.mu.Unlock()
    9.67ms     9.67ms    165:   if f.mu.closed {
         .          .    166:           return nil, budgetClosedError
         .          .    167:   }
         .          .    168:   var err error
    9.67ms    19.35ms    169:   if f.mu.memBudget.Used()+amount > f.limit {
         .          .    170:           return nil, errors.Wrap(mon.NewMemoryBudgetExceededError(amount,
         .          .    171:                   f.mu.memBudget.Used(),
         .          .    172:                   f.limit), "rangefeed budget")
         .          .    173:   }
         .   292.03ms    174:   if err = f.mu.memBudget.Grow(ctx, amount); err != nil {
         .          .    175:           return nil, err
         .          .    176:   }
    8.04ms   236.67ms    177:   return getPooledBudgetAllocation(SharedBudgetAllocation{size: amount, refCount: 1, feed: f}), nil
         .          .    178:}
```

</details>

However, there are still other parts of the regression that I don’t quite understand. But I believe they don’t have any real world implications, and here is why:
1. With my changes, time spent on computing memory size was actually better. 
```
    -0.15s  0.18%  1.46%     -0.31s  0.36%  github.com/cockroachdb/cockroach/pkg/kv/kvserver/rangefeed.calculateDateEventSize
```

2. The regression is there despite my changes not being called at all during `budget = false`. If we compare the regression of `budget = true` V.S. `budget = false` from my patch here, they are roughly the same. After looking at the cpu and mem profiles, the regressions were because we are doing a lot more `logical ops` (more write intent op, commit intent op, updateTxn, publish value) and much less checkpoint events when my changes are there. These events are hardcoded from the benchmark. The number of events constructed should be only related to b.N here. So I don’t think there are any real world impacts. My current suspicion is that this might be due to b.N / other benchmark configurations being different with my changes. We can see from below that checkpoint events are a lot less now and more logical ops events were constructed. 

<img width="916" alt="Screenshot 2024-04-29 at 1 20 59 PM" src="https://github.com/cockroachdb/cockroach/assets/56973754/934b76be-1e84-442e-a709-0a7448dc7c40">

<details>
```
   17.06ms  -483.87ms (flat, cum)  0.57% of Total
    9.67ms     9.67ms    636:func (p *ScheduledProcessor) consumeEvent(ctx context.Context, e *event) {
         .          .    637:   switch {
    7.71ms     7.71ms    638:   case e.ops != nil:
     -10ms   902.47ms    639:           p.consumeLogicalOps(ctx, e.ops, e.alloc)
         .          .    640:   case !e.ct.IsEmpty():
         .     -1.41s    641:           p.forwardClosedTS(ctx, e.ct.Timestamp, e.alloc)
         .          .    642:   case bool(e.initRTS):
         .          .    643:           p.initResolvedTS(ctx, e.alloc)
         .          .    644:   case e.sst != nil:
         .          .    645:           p.consumeSSTable(ctx, e.sst.data, e.sst.span, e.sst.ts, e.alloc)
         .          .    646:   case e.sync != nil:
         .          .    647:           if e.sync.testRegCatchupSpan != nil {
         .          .    648:                   if err := p.reg.waitForCaughtUp(ctx, *e.sync.testRegCatchupSpan); err != nil {
         .          .    649:                           log.Errorf(
         .          .    650:                                   ctx,
         .          .    651:                                   "error waiting for registries to catch up during test, results might be impacted: %s",
         .          .    652:                                   err,
         .          .    653:                           )
         .          .    654:                   }
         .          .    655:           }
         .          .    656:           close(e.sync.c)
         .          .    657:   default:
         .          .    658:           log.Fatalf(ctx, "missing event variant: %+v", e)
         .          .    659:   }
    9.67ms     9.67ms    660:}
```

</details>

2. From the spreadsheet, there were regressions for legacy processors as well. I would be surprised if there is a regression from my PR since my work was only added for scheduled processors. I did a bisect on legacy benchmarks, and it led me to this [commit](https://github.com/cockroachdb/cockroach/commit/5aa0b8f619eddaeb6824d93f1822d0f1cf61a586). This was the first commit that we imported the etcd/raft package to crdb. It’s unclear if this commit actually introduced the regression or if the benchdiff is being weird with commit history we imported from other repo.

4. Regression coming from [^1] is expected and relatively small in this benchmark, but it might turn out to be significant in real world scenarios. Checkpoint events happen at a much larger frequency compared to other logical ops. We are now acquiring/releasing budget and getting/returning SharedBudgetAllocation to the pool much more frequently now. Raft updates and checkpoint events may happen around a similar time, and this could lead to more mutex contentions. When the cluster is overloaded and we are running out of memory, we could be waiting up to (defaultEventChanTimeout) 50ms here to acquire a budget. It’s configurable, but we are not sure about the real world implications here. 

Overall, I don't think the regression here has a real world impact, but I will keep looking into the remaining pieces of puzzle here.

**Comment by wenyihu6** [comment] 2024-04-29 21:13
> Regression coming from 1 is expected and relatively small in this benchmark, but it might turn out to be significant in real world scenarios. Checkpoint events happen at a much larger frequency compared to other logical ops. We are now acquiring/releasing budget and getting/returning SharedBudgetAllocation to the pool much more frequently now. Raft updates and checkpoint events may happen around a similar time, and this could lead to more mutex contentions. When the cluster is overloaded and we are running out of memory, we could be waiting up to (defaultEventChanTimeout) 50ms here to acquire a budget. Timeout is configurable, but we are not sure about the real world implications here.

@nicktrav is there someone on KV who could chime in and provide insights into the real-world impacts of the concerns above? Is there a good way to measure these impacts other than scale testing?

**Comment by wenyihu6** [comment] 2024-05-06 15:30
Sorry for the late reply here. I was tied up with on-call duties and couldn’t find a chance to revisit this issue again. Thanks for providing your insights and details calculations! I really appreciate it. 

Your analysis makes sense to me. I just wanted to double check three things here: 

- Other mvcc logical operations (including MVCCDeleteRangeOp, MVCCUpdateIntentOp, MVCCCommitIntentOp, MVCCAbortIntentOp, MVCCAbortTxnOp, and key value pairs MVCCWriteValueOp, MVCCCommitIntentOp) from raft logs including write values, AddSSTTable events including SST contents are also fighting for the mutex and the memory here. initResolvedTSScan is also there, but I’m assuming this would be a negligible one-time initialization. Do you perhaps know how often they happen? 
- I see that by default, the bound amount can reserve up to 0.5(https://github.com/cockroachdb/cockroach/blob/8695c8eeb34efeee9cee32e2a0f273de179dfa42/pkg/kv/kvserver/rangefeed/budget.go#L34) *  256 MiB (https://github.com/cockroachdb/cockroach/blob/91f53eae420edbb40cddfd2559bcb4406f7a4c93/pkg/server/config.go#L68 ) = 128 MiB. Each rangefeed can reserve up to 0.05 (https://github.com/cockroachdb/cockroach/blob/8695c8eeb34efeee9cee32e2a0f273de179dfa42/pkg/kv/kvserver/rangefeed/budget.go#L46)*128 MiB = 6.4 MiB. Given that this value is even larger than the 10KB you pointed out, I’m assuming this won’t be a problem. I see that you used the DefaultPoolAllocationSize which is the limit for each allocation in the pool which also makes sense to me. Is the actual upper limit the minimum between these two values?
- I recall Erik mentioning that these limits serve as maximums rather than guaranteed reserved budgets. Rangefeeds can allocate up to these limits, but it doesn’t ensure they will always have these amounts of memory. 

> The best way would probably be to just create one of these rangefeed-dense cluster configurations where per-range checkpoints have historically been a problem (do we have a roachtest?) and look at a mutex profile. If the mutexes in the memory accounting object hierarchy don't show up prominently on the mutex profile, things are likely ok.

Thanks! I will look into this.

**Comment by wenyihu6** [comment] 2024-06-06 16:16
Closing as we probably don't have time to look into this in the near future. Some of the regressions were expected, and the other part of regression that I couldn't explain doesn't seem to be a concern in practise.

**Closed by wenyihu6** 2024-06-06 16:16 UTC
Labels: C-performance, A-cdc, T-cdc, P-1
