### ISSUE TITLE
sql: update error on Group By of JSON

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36770] opened 2019-04-11 18:23 UTC
The error message when running a Group By on JSON is hard to understand:
```sql
SELECT
    cluster, cfg
FROM
    registration.zonecfgs
WHERE
    cfg->'constraints' != 'null'
    AND json_array_length(cfg->'constraints') = 9
GROUP BY
    cluster, cfg;
```
```
pq: internal error: uncaught error: unable to encode table key: *tree.DJSON
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.EncodeTableKey
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/column_type_encoding.go:167
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*EncDatum).Encode
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:269
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Distinct).encode
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/distinct.go:185
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Distinct).Next
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/distinct.go:219
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:174
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).startInternal.func1
	/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:567
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/distsqlpb/data.go:151: in NewError()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/stream_encoder.go:109: in AddMetadata()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:125: in addRow()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:293: in mainLoop()
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/outbox.go:413: in run()

HINT: You have encountered an unexpected error inside CockroachDB.

Please check https://github.com/cockroachdb/cockroach/issues to check
whether this problem is already tracked. If you cannot find it there,
please report the error with details at:

    https://github.com/cockroachdb/cockroach/issues/new/choose

If you would rather not post publicly, please contact us directly at:

    support@cockroachlabs.com

The Cockroach Labs team appreciates your feedback.
```

**Comment by jordanlewis** [comment] 2019-05-07 16:45
This is a duplicate of #35706.

**Closed by jordanlewis** 2019-05-07 16:45 UTC
Labels: A-sql-json, C-enhancement, S-3-ux-surprise
