### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestBaseQueuePurgatory

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6793] opened 2016-05-19 12:16 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/bfb28e1ab481c9cf2c475b85f55081e42ba851f5

Stress build found a failed test:

```
=== RUN   TestBaseQueuePurgatory
W160519 07:29:42.331092 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 07:29:42.333707 storage/queue.go:496  [test] purgatory is now empty
--- FAIL: TestBaseQueuePurgatory (15.08s)
	queue_test.go:530: expected purgatory size of 10; got 9
	testing.go:113: storage/queue_test.go:547: condition failed to evaluate within 15s: storage/queue_test.go:544: expected 30 processed replicas; got 29
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
18 runs so far, 0 failures, over 1m15s
31 runs so far, 0 failures, over 1m20s
31 runs so far, 0 failures, over 1m25s
31 runs so far, 0 failures, over 1m30s
31 runs so far, 0 failures, over 1m35s
31 runs so far, 0 failures, over 1m40s
31 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
43 runs so far, 0 failures, over 1m55s
43 runs so far, 0 failures, over 2m0s
43 runs so far, 0 failures, over 2m5s
43 runs so far, 0 failures, over 2m10s
43 runs so far, 0 failures, over 2m15s
44 runs so far, 0 failures, over 2m20s
45 runs so far, 0 failures, over 2m25s
52 runs so far, 0 failures, over 2m30s
56 runs so far, 0 failures, over 2m35s
56 runs so far, 0 failures, over 2m40s
56 runs so far, 0 failures, over 2m45s
56 runs so far, 0 failures, over 2m50s
59 runs so far, 0 failures, over 2m55s
59 runs so far, 0 failures, over 3m0s
64 runs so far, 0 failures, over 3m5s
71 runs so far, 0 failures, over 3m10s
71 runs so far, 0 failures, over 3m15s
71 runs so far, 0 failures, over 3m20s
71 runs so far, 0 failures, over 3m25s
73 runs so far, 0 failures, over 3m30s
74 runs so far, 0 failures, over 3m35s
77 runs so far, 0 failures, over 3m40s
85 runs so far, 0 failures, over 3m45s
85 runs so far, 0 failures, over 3m50s
85 runs so far, 0 failures, over 3m55s
85 runs so far, 0 failures, over 4m0s
87 runs so far, 0 failures, over 4m5s
89 runs so far, 0 failures, over 4m10s
91 runs so far, 0 failures, over 4m15s
99 runs so far, 0 failures, over 4m20s
99 runs so far, 0 failures, over 4m25s
100 runs so far, 0 failures, over 4m30s
100 runs so far, 0 failures, over 4m35s
102 runs so far, 0 failures, over 4m40s
104 runs so far, 0 failures, over 4m45s
106 runs so far, 0 failures, over 4m50s
109 runs so far, 0 failures, over 4m55s
114 runs so far, 0 failures, over 5m0s
115 runs so far, 0 failures, over 5m5s
115 runs so far, 0 failures, over 5m10s
117 runs so far, 0 failures, over 5m15s
118 runs so far, 0 failures, over 5m20s
121 runs so far, 0 failures, over 5m25s
123 runs so far, 0 failures, over 5m30s
129 runs so far, 0 failures, over 5m35s
129 runs so far, 0 failures, over 5m40s
129 runs so far, 0 failures, over 5m45s
131 runs so far, 0 failures, over 5m50s
132 runs so far, 0 failures, over 5m55s
134 runs so far, 0 failures, over 6m0s
136 runs so far, 0 failures, over 6m5s
142 runs so far, 0 failures, over 6m10s
142 runs so far, 0 failures, over 6m15s
142 runs so far, 0 failures, over 6m20s
144 runs so far, 0 failures, over 6m25s
145 runs so far, 0 failures, over 6m30s
147 runs so far, 0 failures, over 6m35s
150 runs so far, 0 failures, over 6m40s
156 runs so far, 0 failures, over 6m45s
156 runs so far, 0 failures, over 6m50s
157 runs so far, 0 failures, over 6m55s
158 runs so far, 0 failures, over 7m0s
158 runs so far, 0 failures, over 7m5s
161 runs so far, 0 failures, over 7m10s
164 runs so far, 0 failures, over 7m15s
169 runs so far, 0 failures, over 7m20s
170 runs so far, 0 failures, over 7m25s
171 runs so far, 0 failures, over 7m30s
172 runs so far, 0 failures, over 7m35s
172 runs so far, 0 failures, over 7m40s
175 runs so far, 0 failures, over 7m45s
177 runs so far, 0 failures, over 7m50s
181 runs so far, 0 failures, over 7m55s
185 runs so far, 0 failures, over 8m0s
185 runs so far, 0 failures, over 8m5s
186 runs so far, 0 failures, over 8m10s
186 runs so far, 0 failures, over 8m15s
189 runs so far, 0 failures, over 8m20s
191 runs so far, 0 failures, over 8m25s
194 runs so far, 0 failures, over 8m30s
199 runs so far, 0 failures, over 8m35s
199 runs so far, 0 failures, over 8m40s
200 runs so far, 0 failures, over 8m45s
200 runs so far, 0 failures, over 8m50s
203 runs so far, 0 failures, over 8m55s
205 runs so far, 0 failures, over 9m0s
208 runs so far, 0 failures, over 9m5s
211 runs so far, 0 failures, over 9m10s
211 runs so far, 0 failures, over 9m15s
212 runs so far, 0 failures, over 9m20s
213 runs completed, 1 failures, over 9m20s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:52
Duplicate of #6342

**Closed by bdarnell** 2016-05-21 15:52 UTC
Labels: Robot, test-failure
