### ISSUE TITLE
SchemaValidationException

### ISSUE THREAD

**Issue by tejahere** [cockroachdb/cockroach#51419] opened 2020-07-14 17:44 UTC
Working on a POC. 

Installed Pulsar 2.6.0
Installed Debizium connector nar file. 
Installed postgres 
Java version is 1.8_252

When updated a table in postgres, I was able to see the log of the changes in the pulsar client log for the topic. 

When done schema changes, example adding a new column or something, I am not seeing the changes but the pulsar is erroring out with SchemaValidationException. 

Received error from server. prg.apache.pulsar.broker.service.schema.exceptions.IncompatibleSchemaException: org.apache.avro.SchemaValidationException: Unable to read schema:

Please let me know the changes required from my end to configure the yml file. 

Also, please let me know if it is the limitation of Pulsar with postgres and debezium or we have a solution to allow the schema changes to be pushed to the topic. 

Help us out in providing a scolution to the above exception

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

**Additional data / screenshots**
If the problem is SQL-related, include a copy of the SQL query and the schema
of the supporting tables.

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]
 - Server OS: [e.g. Linux/Distrib]
 - Client app [e.g. `cockroach sql`, JDBC, ...]

**Additional context**
What was the impact?

**Comment by otan** [comment] 2020-07-15 05:19
duplicate of #51421

**Closed** 2020-07-15 05:20 UTC
Labels: O-community, X-blathers-oncall
