### ISSUE TITLE
kvserver: TestRaftSSTableSideloadingTruncation/loosely-coupled=true seems flaky

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#77046] opened 2022-02-25 17:44 UTC
```
TestRaftSSTableSideloadingTruncation/loosely-coupled=true
    raft_log_queue_test.go:923: condition failed to evaluate within 45s: expected firstIndex == 14, got 11
        goroutine 29970 [running]:
        runtime/debug.Stack()
        	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsWithin({0x5711eb8, 0xc000e24b60}, 0x0, 0x0)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:60 +0x5f
        github.com/cockroachdb/cockroach/pkg/testutils.SucceedsSoon({0x5711eb8, 0xc000e24b60}, 0x1)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/soon.go:41 +0x4a
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.waitForTruncationForTesting(0x0, 0x0, 0x0, 0x0)
        	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/raft_log_queue_test.go:923 +0x65
        github.com/cockroachdb/cockroach/pkg/kv/kvserver.TestRaftSSTableSideloadingTruncation.func1(0xc000e24b60, 0xb7)
        	/go/src/github.com/cockroachdb/cockroach/pkg/kv/kvserver/replica_sideload_test.go:860 +0x633
        github.com/cockroachdb/cockroach/pkg/testutils.RunTrueAndFalse.func1(0xffdf20)
        	/go/src/github.com/cockroachdb/cockroach/pkg/testutils/subtest.go:23 +0x24
        testing.tRunner(0xc000e24b60, 0xc00369cc48)
        	/usr/local/go/src/testing/testing.go:1259 +0x102
        created by testing.(*T).Run
        	/usr/local/go/src/testing/testing.go:1306 +0x35a
```

Example build: https://teamcity.cockroachdb.com/viewLog.html?buildId=4459715&buildTypeId=Cockroach_UnitTests

**Comment by sumeerbhola** [comment] 2022-02-26 00:43
Reproduced using stress, and added some additional instrumentation
```
truncating to index < 14
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, 13
tryEnactTruncations enactIndex: -1, raftAppliedIndex: 0
    raft_log_queue_test.go:923: condition failed to evaluate within 45s: expected firstIndex == 14, got 11
```
There is a race which is only a problem for the test: the FlushEnd callback is after the version edit, but before the new read state is installed.
https://github.com/cockroachdb/pebble/blob/7e5c8ee1daa4cea7bb03e237e6d1a65b9f0cd3a3/compaction.go#L1455-L1466
Moving the FlushEnd after the read state installation fixes the problem (ran for 10min, while before it was failing after 1min).

**Comment by sumeerbhola** [comment] 2022-03-01 14:44
This should be fixed by https://github.com/cockroachdb/cockroach/pull/77131.
No failure after > 4000 runs, so I am closing the issue.

**Comment by sumeerbhola** [comment] 2022-03-01 16:42
I had a test failure after 6000 runs. I am trying to reproduce with instrumentation, but no success so far.
I am still inclined to believe that the failure is a problem with the test and not the actual code -- the test is dependent on a single flush callback for liveness because there won't be any more writes, and if the "durable" observation made in that callback is somehow stale, then the test will fail.

**Comment by sumeerbhola** [comment] 2022-03-01 19:05
Found it. There is a silly race in how the raftLogTruncator queues the durability callbacks.

Failed run with additional instrumentation:
(rai is the RaftAppliedIndex. Ignore lui)
```
=== RUN   TestRaftSSTableSideloadingTruncation/loosely-coupled=true
addPendingTruncation: 13
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 24, lui: 0
addPendingTruncation: 14
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 25, lui: 0
addPendingTruncation: 15
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 26, lui: 0
addPendingTruncation: 16
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 27, lui: 0
addPendingTruncation: 17
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 28, lui: 0
addPendingTruncation: 18
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 29, lui: 0
addPendingTruncation: 19
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 30, lui: 0
addPendingTruncation: 20
durabilityAdvancedCallback run true, queued false
durabilityAdvanced
tryEnactTruncations 1
tryEnactTruncations 1, enactIndex: 0, rai: 31, lui: 0
addPendingTruncation: 21
durabilityAdvancedCallback run false, queued true
```

**Comment by tbg** [comment] 2022-10-27 14:37
This test is skipped again, as a result of https://github.com/cockroachdb/pebble/issues/2064. It can happen that pebble is holding the ingested files open, so the truncation will not delete the sideloaded files, and the test will notice that and fail.

I haven't been seeing this on master, but I see it in https://github.com/cockroachdb/cockroach/pull/89632#issuecomment-1293415352.

**Comment by jbowens** [comment] 2022-11-04 22:32
was this unskipped? it doesn't appear to be skipped on master

**Comment by tbg** [comment] 2022-11-07 08:30
Hmm, my bad - I had skipped it in https://github.com/cockroachdb/cockroach/pull/89632#issuecomment-1293415352 (I thought) but apparently not. Either way, the root cause was https://github.com/cockroachdb/pebble/issues/2064 which is since fixed so assuming that pebble PR got picked up we're good here!

**Comment by jbowens** [comment] 2022-11-07 14:42
Thanks, yeah, pebble was bumped to include it, so I'll close this out.

**Closed by jbowens** 2022-11-07 14:42 UTC
Labels: C-test-failure, skipped-test, T-storage
