### ISSUE TITLE
storage: engine/switch/nodes=3 roachtest observes re-appearing key

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#47406] opened 2020-04-12 19:20 UTC
I've been exploring an assertion failure in the `engine/switch/nodes=3` roachtest that looks like: 
```
F200410 17:06:18.069264 9013 kv/kvserver/concurrency/concurrency_manager.go:261  [n2,s2,r41/3:/Table/61{-/1/0/6/-…}] caller violated contract: discovered lock by different transaction than existing lock
```
Verbose logging in [this branch](https://github.com/nvanbenschoten/cockroach/commits/nvanbenschoten/debugCallerViolated) revealed that the assertion is being hit when a transaction is performing an UPDATE on a key while using implicit SFU semantics. The transaction reads a key using a locking `Scan` request, which acquires an unreplicated lock on the key. At this point, we know that the scan did not see an intent, or it would not have been successful. The transaction then issues a `Put` to the same key. This time, it does see an intent on the key from an old transaction. It passes this intent back to the lockTable, which proceeds to hit the fatal error because the existing unreplicated lock does not agree with the replicated lock being discovered.

This shouldn't be possible. The locking scan would not have been able to succeed if it has seen the intent. So the intent must have been written after the locking scan, but this a) should not be possible because the request would have waited on the unreplicated lock, b) doesn't explain why the intent always has a much earlier timestamp than the unreplicated lock, and c) isn't what we see from the logs. What we actually see is that the intent was written before the locking scan but not observed by the locking scan. It's unclear whether it was resolved before the scan or not.

In all cases, the locking `Scan` and subsequent `Put` take place in quick succession on a node running `pebble`, usually about a second after than node has started up.

In 200 iterations of this test, I've seen this 4 times. During those 200 runs, I also saw a TPC-C consistency check fail once, which may or may not be related:
```
run_043201.093_n4_workload_check_tpcc: 04:32:01 cluster.go:335: > /home/nathan/go/src/github.com/cockroachdb/cockroach/bin/roachprod run nathan-1586578312-06-n4cpu4:4 -- ./workload check tpcc --warehouses=1 --expensive-checks=true {pgurl:1}
I200411 04:32:01.754906 1 workload/tpcc/tpcc.go:372  check 3.3.2.1 took 11.173689ms
I200411 04:32:01.904827 1 workload/tpcc/tpcc.go:372  check 3.3.2.2 took 149.89151ms
I200411 04:32:01.927484 1 workload/tpcc/tpcc.go:372  check 3.3.2.3 took 22.630589ms
Error: check failed: 3.3.2.3: 1 rows returned, expected zero
```

After digging into potential KV-level issues that could have caused this, I'm more and more convinced that something is going wrong in the storage layer. I tested this theory by applying the following patch to the test - disabling pebble while retaining the test's periodic restart behavior.
```
diff --git a/pkg/cmd/roachtest/engine_switch.go b/pkg/cmd/roachtest/engine_switch.go
index a5579c9..4b3dfce 100644
--- a/pkg/cmd/roachtest/engine_switch.go
+++ b/pkg/cmd/roachtest/engine_switch.go
@@ -27,7 +27,7 @@ func registerEngineSwitch(r *testRegistry) {
                loadNode := c.Node(c.spec.NodeCount)
                c.Put(ctx, workload, "./workload", loadNode)
                c.Put(ctx, cockroach, "./cockroach", roachNodes)
-               pebbleArgs := startArgs("--args=--storage-engine=pebble")
+               pebbleArgs := startArgs("--args=--storage-engine=rocksdb")
                rocksdbArgs := startArgs("--args=--storage-engine=rocksdb")
                c.Start(ctx, t, roachNodes, rocksdbArgs)
                stageDuration := 1 * time.Minute
```

I ran this for 400 iterations without seeing a single failure. Given that I saw 4 (+1 potentially related failure) in 200 iterations with pebble, it seems pretty likely that that's where the issue lies.

I don't have any strong theories about what's going on at the storage layer because I haven't dug into it. Maybe a compaction is dropping a deletion tombstone that should be covering up the intent key? Maybe the intent key should have been there all along but pebble didn't finish recovering from its WAL before the first scan was evaluated? I'm happy to help out digging more into this however I can, but I'll need assistance from someone with Pebble expertise to go any further.

**Comment by petermattis** [comment] 2020-04-12 19:23
I've also been stressing this test and just encountered the failed TPCC check:

```
```

**Comment by petermattis** [comment] 2020-04-12 19:34
> Verbose logging in this branch ...

The `nvanbenschoten/debugCallerViolated` is slightly out of date. Can you rebase it on current master? I did so in my own investigations and haven't been able to see your assertion failure fire today (135 passes, 1 tpcc check failure).

> I ran this for 400 iterations without seeing a single failure. Given that I saw 4 (+1 potentially related failure) in 200 iterations with pebble, it seems pretty likely that that's where the issue lies.

Interesting. The other data point that would be interesting is if either failure mode occurs when running only Pebble. I'll try this.

> I don't have any strong theories about what's going on at the storage layer because I haven't dug into it. Maybe a compaction is dropping a deletion tombstone that should be covering up the intent key? 

Do we know the key in question? If yes, we can turn on "archival" file deletion in Pebble to allow further post-mortem debugging.

> Maybe the intent key should have been there all along but pebble didn't finish recovering from its WAL before the first scan was evaluated?

This is impossible in both RocksDB and Pebble. The WAL is fully replayed when the database is open. What is possible is that RocksDB or Pebble disagree on where the end of the WAL is, though that sounds like a long-shot possibility to me.

**Comment by petermattis** [comment] 2020-04-12 21:29
Something else to note about this test is that it runs a 3-node cluster. That means that there is no rebalancing taking place. In the absence of rebalancing and the absence of table truncations/drops, there should be no range tombstones. So whatever is happening is taking place is likely happening with only "point" operations.

> Interesting. The other data point that would be interesting is if either failure mode occurs when running only Pebble. I'll try this.

I'm trying this right now. So far, 100 successful runs and 0 failures.

**Comment by petermattis** [comment] 2020-04-12 22:58
> I'm trying this right now. So far, 100 successful runs and 0 failures.

Gah! 200 passes and 0 failures when only using `--storage-engine=pebble`. This isn't definitive, but does point a finger at a RocksDB / Pebble incompatibility.

**Comment by petermattis** [comment] 2020-04-13 00:11
Reverted `engine/switch` back so that it switches between RocksDB and Pebble and I encountered another TPCC check failure:

```
Error: check failed: 3.3.2.4: order.sum(o_ol_cnt): 66777 != order_line.count(*): 66765
```

**Comment by nvanbenschoten** [comment] 2020-04-13 01:29
> The nvanbenschoten/debugCallerViolated is slightly out of date. Can you rebase it on current master?

Done and pushed in case you want to use it.

> Do we know the key in question? If yes, we can turn on "archival" file deletion in Pebble to allow further post-mortem debugging.

Yes, https://github.com/nvanbenschoten/cockroach/commit/b9d79ccf8c7d57c72d4cae85e986a155c48b44a4#diff-3bd61c970cda5e3d946f4c29a1dd2129R1278 added the key in question to the fatal error, so we can determine where the problem came from after the fact. Of course, this is an MVCCMetadata key, so the LSM key has a timestamp suffix of 0. 

> This is impossible in both RocksDB and Pebble. The WAL is fully replayed when the database is open.

Got it, that's how I expected it to work but wasn't positive. Out of curiosity, how long does this WAL recovery usually take? I see that in RocksDB, `max_total_wal_size` backpressures writes to ensure that the WAL never grows too large. Is there an equivalent concept in Pebble? Is that simply a function of `MemTableSize*MemTableStopWritesThreshold`? Do you know how long it would take to recover from this maximum WAL size?

> In the absence of rebalancing and the absence of table truncations/drops, there should be no range tombstones. 

We are periodically killing nodes though, so I think it is still possible to see snapshots during the test, which include a range deletion tombstone to wipe out the existing data in the recipient replica's engine.

**Comment by petermattis** [comment] 2020-04-13 12:27
> Out of curiosity, how long does this WAL recovery usually take?

A second or two. 

> Is there an equivalent concept in Pebble? Is that simply a function of MemTableSize*MemTableStopWritesThreshold? 

The `max_total_wal_size` option is mainly useful when multiple column families are being used. For CRDB, the WAL size is capped by the number of memtables and is approximately `MemTableSize*MemTableStopWritesThreshold` (that isn't exactly accurate because memtable size != WAL size).

> Do you know how long it would take to recover from this maximum WAL size?

I haven't actually measured it, but I'd be surprised if it ever takes longer than a few seconds. Longer than 10 seconds would be shocking. 

> We are periodically killing nodes though, so I think it is still possible to see snapshots during the test, which include a range deletion tombstone to wipe out the existing data in the recipient replica's engine.

Good point, though we are restarting the nodes immediately. I looked through the sstables and WALs on one of the nodes from a failed run. There was 1 range deletion present in an sstable:

```
/Users/pmattis/debug/run_107/1.cockroach/000240.sst
              /Local/RangeID/73""/0,0-/Local/RangeID/74""/0,0#10628211,RANGEDEL
```

And a handful of additional range deletions in archived WALs:

```
/Users/pmattis/debug/run_107/1.cockroach/archive/000092.log
    RANGEDEL(/Local/RangeID/53""/0,0,/Local/RangeID/54""/0,0)
/Users/pmattis/debug/run_107/1.cockroach/archive/000111.log
    RANGEDEL(/Local/RangeID/63""/0,0,/Local/RangeID/64""/0,0)
/Users/pmattis/debug/run_107/1.cockroach/archive/000150.log
    RANGEDEL(/Local/RangeID/54""/0,0,/Local/RangeID/55""/0,0)
/Users/pmattis/debug/run_107/1.cockroach/archive/000230.log
    RANGEDEL(/Local/RangeID/73""/0,0,/Local/RangeID/74""/0,0)
```

Do you know offhand why we would have only seen range deletions that look like this?

**Comment by nvanbenschoten** [comment] 2020-04-13 15:01
> Do you know offhand why we would have only seen range deletions that look like this?

Those do not look like the range deletion tombstones written during snapshot application because those span the entire range-id local keyspace instead of just the replicated range-id local keyspace. The only place I see that form of range deletion tombstone coming from is replica destruction. This currently comes in three forms:
1. removing a replica due to rebalancing
2. removing a preemptive snapshot
3. removing the RHS of a split if it got ahead of the LHS

None of these sound concerning on their own. The third case is the only one I would expect you to be able to hit in this test.

**Comment by itsbilal** [comment] 2020-04-14 19:46
I've been diving into the store directories that came out of Peter's reproduction of this issue. It seems like there's a missing row in the `new_order` table that corresponds to the MVCC key `/Table/58/1/0/2/6172` (for district 2, warehouse 0, order 6172).

```
root@localhost:26257/tpcc> SELECT * FROM new_order WHERE no_d_id = 2 LIMIT 100 OFFSET 500;
  no_o_id | no_d_id | no_w_id
----------+---------+----------
     6168 |       2 |       0
     6169 |       2 |       0
     6170 |       2 |       0
     6171 |       2 |       0
     6173 |       2 |       0
     6174 |       2 |       0
     6175 |       2 |       0
     6176 |       2 |       0
     6177 |       2 |       0
     6178 |       2 |       0
     6179 |       2 |       0
     6180 |       2 |       0
...

root@localhost:26257/tpcc> SELECT * FROM new_order WHERE no_o_id=6172;
  no_o_id | no_d_id | no_w_id
----------+---------+----------
     6172 |       1 |       0
     6172 |       3 |       0
     6172 |       4 |       0
     6172 |       5 |       0
     6172 |       6 |       0
     6172 |       7 |       0
     6172 |       8 |       0
     6172 |       9 |       0
     6172 |      10 |       0
(9 rows)
```

There was no delivery made for that district/order/warehouse according to `order_line`. `new_order` entries are added alongside the corresponding `order` in the same txn, and the `new_order` row is deleted when a delivery is made (in the same txn as the one used to update `order_line`). Since `order_line` was not updated with a delivery time, and we see existent entries in `new_order` for districts 1 and 3 with the same order ID, the key corresponding to our missing row did go missing in the storage layer somewhere in between.

On closer inspection: the new_order keys for all entries for order 6172 are in L6 on nodes n1 and n2, but on L5 for node n3, where we see a point deletion at that key:

```
/Table/58/1/0/1/6172/0/0,0#9417604,DEL []
/Table/58/1/0/1/6172/0/1586713610.876312833,0#9417385,SET [d70012600a]
/Table/58/1/0/2/6172/0/0,0#10448211,DEL []
/Table/58/1/0/2/6172/0/1586713623.656139496,0#10448210,DEL []
/Table/58/1/0/3/6172/0/0,0#9329753,DEL []
/Table/58/1/0/3/6172/0/1586713602.871578295,0#9329640,SET [9ac8b36b0a]
/Table/58/1/0/4/6172/0/0,0#9594209,DEL []
/Table/58/1/0/4/6172/0/1586713631.027322785,0#9593769,SET [87cd83d30a]
/Table/58/1/0/5/6172/0/0,0#9600929,DEL []
/Table/58/1/0/5/6172/0/1586713631.778965678,0#9600661,SET [4c9150760a]
/Table/58/1/0/6/6172/0/0,0#9410326,DEL []
/Table/58/1/0/6/6172/0/1586713610.061625795,2#9410233,SET [ca0522d80a]
/Table/58/1/0/7/6172/0/0,0#9391220,DEL []
/Table/58/1/0/7/6172/0/1586713608.305525671,0#9390835,SET [0159f17d0a]
/Table/58/1/0/8/6172/0/0,0#9734901,DEL []
/Table/58/1/0/8/6172/0/1586713642.944163544,0#9734594,SET [f3d941330a]
/Table/58/1/0/9/6172/0/0,0#9486860,DEL []
/Table/58/1/0/9/6172/0/1586713616.471865804,0#9486625,SET [388592960a]
/Table/58/1/0/10/6172/0/0,0#9394105,DEL []
/Table/58/1/0/10/6172/0/1586713608.497681825,0#9393788,SET [be11e0380a]
```

The only other interesting thing I could uncover with that sequence number was that the very next operation was in the `AbortSpan` range:

```
/Local/RangeID/38/r/AbortSpan/"865dea2c-c4b5-439a-8385-1bfee53a94e6"/0,0#10448212,SET [120408001000180020002800321bb073064e030a04be89888a120a08e895b0d2a4f4c8821618e0b403]
```

Still digging while I try to repro the same issue in clusters with archiving enabled on pebble.

**Comment by petermattis** [comment] 2020-04-14 20:58
@itsbilal Nice sleuthing so far. The point deletion at `/Table/58/1/0/2/6172/0/1586713623.656139496,0#10448210,DEL` being present on only `n3` is likely due to compactions happening at different times. As soon as that key gets compacted to L6 we'll elide it from the compacted sstable.

It sounds like we aborted at least one transaction involving order 6172. That isn't unexpected. Why was a subsequent transaction for the order not performed? Or if it was, what happened to it?

**Comment by itsbilal** [comment] 2020-04-14 21:12
@petermattis Yeah, we got lucky that we didn't compact away that point tombstone in `n3` by the time the test ended. The others were likely compacted away.

The abort itself isn't the concern; if the delivery transaction got aborted, we should still see the `new_order` entry, and if the order transaction got aborted, the `order` entry and the entirety of order 6172 shouldn't have existed in the first place. Instead we're seeing a txn abort that happened to take away a previously committed value. I'm looking through the abort / intent resolution code to see why this could happen.

**Comment by petermattis** [comment] 2020-04-15 13:08
> Instead we're seeing a txn abort that happened to take away a previously committed value.

I'm not following the conclusion here. We're seeing a txn abort, but the value is is deleting is likely the value that was previously written in the txn being aborted.

**Closed** 2020-04-17 18:11 UTC
Labels: A-storage, C-bug, C-test-failure, O-roachtest
