### ISSUE TITLE
Failed tests (11942): TestGossipRestart 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4002] opened 2016-01-28 03:13 UTC
The following test appears to have failed:

[#11942](https://circleci.com/gh/cockroachdb/cockroach/11942):

```
E0128 03:12:10.342294 27354 acceptance/cluster/localcluster.go:417  node=1 status=restart
E0128 03:12:10.476045 27354 acceptance/cluster/localcluster.go:417  node=2 status=start
I0128 03:12:12.034317 27354 acceptance/gossip_peerings_test.go:181  waiting for gossip to be connected
E0128 03:12:12.035271 27354 acceptance/cluster/localcluster.go:417  node=2 status=restart
I0128 03:12:32.196638 27354 acceptance/cluster/localcluster.go:544  stopping
--- FAIL: TestGossipRestart (43.87s)
	testing.go:177: acceptance/gossip_peerings_test.go:69: condition failed to evaluate within 20s: invalid character 'p' after top-level value
=== RUN   TestJava
--- SKIP: TestJava (0.00s)
	java_test.go:28: https://github.com/cockroachdb/cockroach/issues/3826
=== RUN   TestPHP
--- SKIP: TestPHP (0.00s)
	php_test.go:28: https://github.com/cockroachdb/cockroach/issues/3826
=== RUN   TestPut
I0128 03:12:36.962959 27354 acceptance/cluster/localcluster.go:219  started docker-spy: 172.17.0.31
I0128 03:12:36.962984 27354 acceptance/cluster/localcluster.go:226  initializing cluster
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:32: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	main_test.go:60: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-12 15:48
Duplicate of #3934.

**Closed by petermattis** 2016-02-12 15:48 UTC
Labels: test-failure, TestGossipRestart
