### ISSUE TITLE
acceptance: errors in iptables in TestPartitionBank not picked up properly by go-test-teamcity

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#12674] opened 2017-01-04 14:30 UTC
Found in:

https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&buildTypeId=Cockroach_UnitTests_Acceptance&buildId=107925#_

The issue is that `iptables` fails but go-test-teamcity doesn't properly transform the failure into a TC marker:
```
[14:25:38][Step 2/2] TestPartitionBank (11s)
[14:25:50][TestPartitionBank] 	partition.go:105: errors restoring the network: [error executing [iptables -X partition_nemesis]:
[14:25:50][TestPartitionBank] 		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[14:25:50][TestPartitionBank] 		
[14:25:50][TestPartitionBank] 		]
[14:25:50][TestPartitionBank] ##teamcity[testFailed timestamp='2017-01-04T14:25:50.199' name='TestPartitionBank' details='	partition.go:105: errors restoring the network: |[error executing |[iptables -X partition_nemesis|]:|n		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
[14:25:50][TestPartitionBank] |n		|n		|]']
```

This TC build also has emitted the detailed acceptance log to a file: https://teamcity.cockroachdb.com/repository/download/Cockroach_UnitTests_Acceptance/107925:id/acceptance/acceptance.log

The input passed to go-test-teamcity is thus:

```
=== RUN   TestPartitionBank
--- FAIL: TestPartitionBank (11.29s)
	partition.go:105: errors restoring the network: [error executing [iptables -X partition_nemesis]:
		rpc error: code = 2 desc = oci runtime error: exec failed: exit status 1
		
		]
```

I believe this is a distinct issue from #12654 because the branch this TC build is working around the possible underlying causes of #12654.

cc @jordanlewis

**Comment by jordanlewis** [comment] 2017-01-04 14:50
Thanks, I'll take a look at this today. In the meantime, I'm going to change the build scripts to tee the raw output of the tests to a file in the artifacts to prevent similar headaches in the future.

**Comment by knz** [comment] 2017-01-04 14:51
I'm already pushing a fix to tee the output in #12662.

**Comment by knz** [comment] 2017-01-04 15:13
note: the test is currently skipped ( dc42004ef47ab865832b6002c61ce97e763e981b ) so you will need to re-enable to investigate this.

**Comment by jordanlewis** [comment] 2017-01-04 16:47
This was caused by stray carriage return characters, which `go-test-teamcity` was just passing through unchanged. They need to be deleted or turned into escaped newlines. I pushed a fix: https://github.com/2tvenom/go-test-teamcity/pull/9

**Comment by jordanlewis** [comment] 2017-01-04 16:53
I've verified this fix locally so I'm going to close this issue.

**Closed by jordanlewis** 2017-01-04 16:53 UTC

**Comment by knz** [comment] 2017-01-04 17:07
Thanks!
