### ISSUE TITLE
distsql: panic in partitionSpans

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16178] opened 2017-05-26 21:24 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/281085632/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 499, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 433, in partitionSpans
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 580, in createTableReaders
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1436, in createPlanForNode
...
(22 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

**Comment by knz** [comment] 2017-05-26 21:36
cc @andreimatei

**Comment by andreimatei** [comment] 2017-05-26 21:43
dupe of #16127

**Closed by andreimatei** 2017-05-26 21:43 UTC
