### ISSUE TITLE
sql: `pg_function_is_visible` fails for UDFs

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#94953] opened 2023-01-09 20:15 UTC
Found while working on #88061.

**Describe the problem**

`pg_function_is_visible()` fails for the OID of UDFs.

**To Reproduce**

```sql
> CREATE FUNCTION myfunc(val INT) RETURNS INT CALLED ON NULL INPUT LANGUAGE SQL AS $$ SELECT val $$;
> select pg_function_is_visible(oid) from pg_proc where proname='myfunc';
ERROR: function 100105 does not exist: function undefined
SQLSTATE: 42883
```

**Expected behavior**

All the OID values in `pg_proc` are valid inputs to `pg_function_is_visible`.

cc @rafiss @mgartner  @chengxiong-ruan  for triage.

Jira issue: CRDB-23241

**Comment by rafiss** [comment] 2023-01-09 20:35
i think this one will be fixed by https://github.com/cockroachdb/cockroach/pull/94771

**Comment by mgartner** [comment] 2023-01-09 20:38
This looks like a regression introduced in https://github.com/cockroachdb/cockroach/commit/acf5006af145e338178d833f361f20a9ced78a5e. It works on v22.2.1:

```
defaultdb> select version();
                                        version
----------------------------------------------------------------------------------------
  CockroachDB CCL v22.2.1 (x86_64-apple-darwin19, built 2022/12/22 15:14:07, go1.19.1)
(1 row)


defaultdb> CREATE FUNCTION myfunc(val INT) RETURNS INT CALLED ON NULL INPUT LANGUAGE SQL AS $$ SELECT val $$;
CREATE FUNCTION

defaultdb> select pg_function_is_visible(oid) from pg_proc where proname='myfunc';
  pg_function_is_visible
--------------------------
            t
(1 row)
```

**Comment by rafiss** [comment] 2023-01-09 20:41
I think the regression is in cee3ee9419f475092fd66f1cffe29017fd692d3e, not acf5006af145e338178d833f361f20a9ced78a5e.

**Comment by mgartner** [comment] 2023-01-09 20:42
Ahh, good catch!

**Comment by jordanlewis** [comment] 2023-01-09 20:54
Yeah I happened to notice this as well, it's fixed here: https://github.com/cockroachdb/cockroach/pull/94771/commits/72217690fcc020e36e04f4b0dabfaee4b6b57934

Will get this merged soon;

**Comment by rafiss** [comment] 2023-01-09 21:00
also note that v22.2 has a _different_ problem with `pg_function_is_visible` for UDFs. It's too permissive, since it doesn't actually inspect the search_path. See https://github.com/cockroachdb/cockroach/issues/89546

Backporting the fixes that we've made on `master` isn't feasible since it would require other changes, but I can make a smaller change just for v22.2.

**Closed** 2023-01-15 16:41 UTC
Labels: C-bug, A-sql-pgcompat, A-sql-vtables, T-sql-sessions, A-schema-catalog, A-sql-udf
