### ISSUE TITLE
storage: node hangs for 1 minute when first replica is deleted

### ISSUE THREAD

**Issue by WillHaack** [cockroachdb/cockroach#7297] opened 2016-06-16 21:44 UTC
While setting up sql benchmark tests for a multinode cluster I waited for one of the two joining nodes to have a replica before executing sql commands. During the tests, the first node wound up dropping its first range and adding it to one of the joining nodes. This caused the node to stall for 1 minute, pausing all sql commands issued to the cluster, while throwing the error:

    W160616 16:46:15.660980 kv/dist_sender.go:655  failed to send RPC: sending to all 1 replicas failed; last error: range 1 was not found

The node should probably be able to resolve this in a quicker manner if it's able to resolve it at all.

**Comment by tschottdorf** [comment] 2016-06-16 21:47
Please post the branch that reproduces as well. The precise issue is that the test there sets up a three node cluster, but with a 1x replication default. That usually leads to that cluster promptly rebalancing the first range off node 1. DistSender then spins for about a minute trying to hit the meta range, presumably rescued only by a refreshed info from Gossip. We should find out why Gossip isn't immediately updated as the replication happens.

**Comment by bdarnell** [comment] 2016-06-16 22:17
> We should find out why Gossip isn't immediately updated as the replication happens.

I don't think there's anything that tries to do this. The first range is gossiped on a timer and there's not currently a way to kick it off sooner.

**Comment by WillHaack** [comment] 2016-06-17 17:18
https://github.com/cockroachdb/cockroach/tree/mark-replication-bug

    make test PKG=./sql TESTS=TestMultinodeCockroach

**Comment by petermattis** [comment] 2016-06-29 15:08
Yep, we only gossip the first range once per minute. See `Store.startGossip` and `Store.maybeGossipFirstRange`. We should be more aggressive about gossiping the first range when its descriptor changes.

@paperstreet Assigning to you per the discussion yesterday about distributing the stability work more widely.

**Comment by paperstreet** [comment] 2016-07-05 14:21
Did some initial digging last week, but forgot to update the issue:

- lowering both sentinelGossipInterval and DefaultGossipStoresInterval to be 1 second helps some (12.1s instead of 60.3s) but lowering only one of the two doesn't help
- adding an unconditional call to `r.maybeGossipFirstRange()` to `(r *Replica).changeReplicasTrigger` doesn't seem to help
- I skimmed a stacktrace from while it's hanging, but nothing popped out to my untrained eye: https://gist.github.com/paperstreet/ed3121871eccdbe61a0b4f4b1ff20762

I'll keep looking

**Comment by paperstreet** [comment] 2016-07-05 15:35
I think I've tracked this down to `(*replicateQueue).shouldQueue` switching from returning false to true. Now I've just got to figure out why...seems like this thread is pulling fairly easily

**Comment by paperstreet** [comment] 2016-07-05 16:12
Aha! If I have the `r.maybeGossipFirstRange()` fix and lower the `DefaultGossipStoresInterval`, it goes down to 12 seconds. So it looks like I need to stick a call to `(*Node).gossipStores` somewhere as well

**Comment by tschottdorf** [comment] 2016-07-05 16:26
Just curious, what if you lower the lease duration? Rebalancing the first range first replica (which is pretty much always the lease holder) comes with mandatory downtime (until we use a lease transfer).

What do you think the DefaultGossipStoresInterval has to do with it? Is that the frequency at which the first range gossip is triggered?

**Comment by paperstreet** [comment] 2016-07-05 20:00
The DefaultGossipStoresInterval thing is (I think) an issue with how the test is setting everything up. I guess the important thing here is that the `r.maybeGossipFirstRange()` fix actually does address the first range gossip issue pointed out above.

So, what's left for this issue? Add that line and test it somehow? How would I write that test? Do we have all the necessary hooks?

**Comment by tschottdorf** [comment] 2016-07-05 20:11
It should be possible to set up a three-node cluster, wait for initial
replication of the first range, and then to disable the replication queue
and to downreplicate so that the first range leader disappears.
Subsequently we should be able to verify that the first range gossip
updates accordingly in a short amount of time (and once we have lease
transfers, we can check more).

On Tue, Jul 5, 2016 at 4:00 PM Daniel Harrison <notifications@github.com>
wrote:

> The DefaultGossipStoresInterval thing is (I think) an issue with how the
> test is setting everything up. I guess the important thing here is that the
> r.maybeGossipFirstRange() fix actually does address the first range
> gossip issue pointed out above.
>
> So, what's left for this issue? Add that line and test it somehow? How
> would I write that test? Do we have all the necessary hooks?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7297#issuecomment-230585859>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135N9k0BnvnvhoSsimx53KYpkjR_8Sks5qSrfSgaJpZM4I313M>
> .
>
-- 

-- Tobias

**Comment by andreimatei** [comment] 2016-07-07 21:30
Reminder to everybody involved that, once this is fixed, we should get rid of forcing full replication in `multinode_test.go` (soon to be `TestCluster`).

**Comment by petermattis** [comment] 2016-07-11 19:43
@paperstreet Ping. We should get the fix in soon even if we're waiting for additional infrastructure to test it properly.

**Comment by paperstreet** [comment] 2016-07-11 19:53
@petermattis Unfortunately, the fix breaks `TestUnreplicateFirstRange`. I've spent a number of hours looking into why with @tschottdorf but I haven't nailed down what's happening yet.

**Comment by petermattis** [comment] 2016-07-11 20:09
Ok. Let me take a look.

**Comment by paperstreet** [comment] 2016-07-11 20:12
The last thing I found was that it seems like after range 1 is unreplicated from node 2, then node 2 keeps trying to elect itself as leader, but is waiting for a 2 node majority. It never gets that majority because it's ignoring node 1 (I think). Without the first range gossip change, it only waits for a 1 node majority, which is correct.

**Comment by bdarnell** [comment] 2016-07-11 20:16
Downreplicating a range from 2 replicas to 1 is a weird case and I'm not sure if we can/should support it. I think we should change TestUnreplicateFirstRange to use all three stores (i.e. upreplicate to all three, then remove from node 1 leaving it on 2 and 3. The point of the test is just to make sure that caches get invalidated correctly and we can find the range once it has moved from store ) so that it doesn't reduce the replica count to 1.

**Comment by petermattis** [comment] 2016-07-11 20:24
Changing that test to down-replicate from 3-2 and then up-replicate from 2-3 still hangs sometimes. The hang only occurs if we call `Replica.maybeGossipFirstRange` from `Replica.changeReplicasTrigger`.

**Comment by petermattis** [comment] 2016-07-11 20:24
And here is the error that is logged over and over:

```
W160711 16:24:17.373090 storage/replica.go:331  range 1: outgoing raft transport stream to {2 2 2} closed by the remote: rpc error: code = 2 desc = range 1: discarding message from {NodeID:1 StoreID:1 ReplicaID:1}, older than NextReplicaID 4
```

**Comment by petermattis** [comment] 2016-07-12 00:35
I thought I had this figured out, but I don't. Putting the `Replica.maybeGossipFirstRange` in a `batch.Defer()` helps, but I still see a hang every few runs (easy to trigger with `go test -count 100 -v -run TestUnreplicateFirstRange`. I've been running with `-vmodule=raft=5,replica=3,intent_resolver=3,queue=3` to get more verbose logging. 

Note, when the hang happens now, it appears that everything freezes. There are no periodic messages or anything. I've also tried a different version of `TestUnreplicateFirstRange` which down-replicates from 3 -> 2 replicas. Here we sometimes get into a loop whereby we can't elect a new leader for the group. Note that in both cases, the problem appears in the final step of the test where we're adding a new replica. I'm not sure if that is significant.

**Comment by bdarnell** [comment] 2016-07-12 02:53
The hang is a deadlock: `changeReplicasTrigger` runs on the `processRaft` goroutine. `maybeGossipFirstRange` must acquire the range lease if it's not already held (it's not, if node 2 or 3 needs to take it away from the deposed node 1), which calls back into raft. 

The trick is to run `maybeGossipFirstRange` asynchronously (inside a `batch.Defer` so it doesn't start until the `changeReplicasTrigger` has been processed:

```
batch.Defer(func() {
    r.store.Stopper().RunAsyncTask(func() {
       r.maybeGossipFirstRange()
    })
})
```

**Closed** 2016-07-13 16:04 UTC
