### ISSUE TITLE
WHERE clause on ARRAY incorrectly applied when GIN index exists

### ISSUE THREAD

**Issue by quentez** [cockroachdb/cockroach#117979] opened 2024-01-19 16:10 UTC
**Describe the problem**

I'm running a query with multiple conditions on arrays using `<@` and `&&` operators in its `WHERE` clause combined with both `AND` and `OR` operators.

- When there are no indices on the table, the results are correct.

- After adding a GIN index on the array column, other rows start being included in the results. The incorrect results are consistent with the query conditions _if_ the `OR` condition was applied at the top-level and not nested in parentheses.

Removing the index restores the correct behavior.

**To Reproduce**

1. Spin up a CockroachCloud Serverless cluster running v23.1.14.
2. Create a table with the following schema:

```sql
CREATE TABLE test_bug
(
    id bigint not null
      constraint test_bug_pk primary key,
    links text[]
);
```

3. Fill it with the following test data:

```sql
INSERT INTO public.test_bug (id, links) VALUES (1, '{str1}');
INSERT INTO public.test_bug (id, links) VALUES (2, '{str2}');
INSERT INTO public.test_bug (id, links) VALUES (3, '{str2,str3}');
INSERT INTO public.test_bug (id, links) VALUES (4, '{str1,str2,str3}');
```

4. Run the query:

```sql
SELECT * 
FROM test_bug as t
WHERE 
    ARRAY['str1'] <@ t.links 
    AND (
        ARRAY ['str1'] && t.links
        OR (ARRAY ['str2'] && t.links AND ARRAY ['str3'] && t.links)
    );
```

This returns rows 1 and 4.

5. Create the GIN index:

```sql
CREATE INDEX "idx_links" ON test_bug USING gin (links);
```

6. Run the query again (I force the index but it also happens when it gets picked automatically):

```sql
SELECT * 
FROM test_bug@{FORCE_INDEX="idx_links"} as t
WHERE 
    ARRAY['str1'] <@ t.links 
    AND (
        ARRAY ['str1'] && t.links
        OR (ARRAY ['str2'] && t.links AND ARRAY ['str3'] && t.links)
    );
```

This now returns rows 1, 4, _**and 3**_.
(Row 3 does not match the mandatory `ARRAY['str1'] <@ t.links` condition).

7. Remove the index and try again, the results should be back to normal.

**Expected behavior**
The query results should always be the same regardless of the index being used.

**Environment:**
 - CockroachDB version Serverless v23.1.14
 - Server OS: Linux
 - Client app: Any SQL client

Jira issue: CRDB-35441

**Comment by yuzefovich** [comment] 2024-01-23 19:59
Thanks for the very detailed report @quentez! I can confirm that this is a bug, and it's present in 23.2.0, 23.1.12, and 22.2.16 versions. Chances are it has been present since #49446 which was merged around 20.2 time frame.

**Closed** 2024-01-26 18:41 UTC
Labels: C-bug, O-community, S-3-erroneous-edge-case, X-blathers-triaged, T-sql-queries, v23.1.15, v23.2.1
