### ISSUE TITLE
cli: combination of transactions and statements confuses someone with quantum results

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#4309] opened 2016-02-10 23:02 UTC
Smallest example I can repro with
```
create database x; create table x.y(a int);
insert into x.y(a) values (1);

begin; select * from x.y; end; select a from x.y;  begin;  select a from x.y; end;
+---+
| a |
+---+
| 1 |
+---+
begin; select * from x.y; end; select a from x.y;  begin;  select a from x.y; end;
query error: pq: unexpected DataRow in simple query execution
begin; select * from x.y; end; select a from x.y;  begin;  select a from x.y; end;
+---+
| a |
+---+
| 1 |
+---+
begin; select * from x.y; end; select a from x.y;  begin;  select a from x.y; end;
query error: pq: unexpected DataRow in simple query execution
```

waaaaa

**Comment by andreimatei** [comment] 2016-02-10 23:18
This doesn't reproduce with `psql`. Looks like a CLI issue.

**Comment by tamird** [comment] 2016-02-10 23:32
Possibly related to https://github.com/cockroachdb/pq/commit/de04a24934fb5fa9e4981a8246a8feb312eeb270

**Comment by dt** [comment] 2016-03-04 21:51
This one also looks like it no longer repros on master.
I get the same result every time:
```
root@:26257> begin; select * from x.y; end; select a from x.y;  begin;  select a from x.y; end;
+---+
| a |
+---+
| 1 |
+---+
+---+
| a |
+---+
| 1 |
+---+
+---+
| a |
+---+
| 1 |
+---+
```

**Comment by petermattis** [comment] 2016-04-09 19:10
Pretty sure this was a bug in `cockroachdb/pq` when receiving multiple results. Closing because this is no longer reproducible.

**Closed by petermattis** 2016-04-09 19:10 UTC
Labels: bug
