### ISSUE TITLE
sql: fix handling of write-only columns during update

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#42459] opened 2019-11-13 21:08 UTC
Quoting @knz's notes from a discussion we had:

----

For context, we're considering the segment of time while a new column is being added, say ALTER TABLE t ADD COLUMN y INT DEFAULT 123:

- the table descriptor lists the column "y" but it's "non-public"

- there's a backfill operation running in the background to get 123 into it

During that segment of time, some rows have a value (the backfill is done with them), and some others don't (the backfill hasn't reached them yet).

Now how does this work "currently":

- SELECT queries and all ways in which a SQL client can select a query, can't use the column because it's non-public. They don't even get fetched/decoded from KV when possible. So far so good.

- an UPDATE will not allow the SQL client to target the new column (SET y = 456) because it's non-public. So far so good.

But now we have an edge case: if the new column shares a column family with one of the existing public column, say column "x".

If the SQL code runs UPDATE SET x = 123, as it must be able to do, it must read the current value of all the other columns and write them back. *Including the newly, currently backfilled, column.*

Now consider the case where UPDATE reaches a row that has not been backfilled yet.

The way it *should* work is "if the read part of UPDATE does not find a value for the column, then evaluate DEFAULT just-in-time to produce a value".

Like this (UPDATE SET x = 456):

- read (x,y) -> (111, NULL)

- ignore the non-public columns, override with DEFAULT: (x,y) := (456, DEFAULT)

- write back (x,y) = (456, 123)

Then after this happens, if the backfiller encounters either a write intent or a newer write, it considers (assumes) that the SQL mutation guaranteed the validity of the column's value and ignores the row.

The way it seems to actually work (according to Radu): the read part fetches the current value from the non-public column, then *reuses it as-is*.

Like this:

- read (x, y) -> (111, NULL)

- fill in the assigned columns: (x, y) := (456, NULL)

- write back (x,y) = (456, NULL)

This produces a value that's unexpected in the row (NULL instead of 123), in a way that the backfiller will not fix: the write is at a newer timestamp than the backfill, so the backfill will assume it's "already done".

The result is rows that may violate the table's constraints (what if y was NOT NULL? or a CHECK constraint?).

----

Repro (the updates on the right were run while ALTER TABLE was running):

![image](https://user-images.githubusercontent.com/16544120/68804362-91594e00-062f-11ea-9695-cc63e95eac7b.png)

**Comment by RaduBerinde** [comment] 2019-11-13 21:16
The proposed solution is to always project the DEFAULT values for these columns. If the DEFAULT expression is impure (e.g. `gen_random_uuid`), we may end up generating new values when we update a row. However we haven't found a scenario where those previous overwritten values could have "leaked out". This is because public columns or indexes can't depend on write-only columns, and you can only access public columns via SQL.

It's still up for discussion where this logic belongs. It would be fairly easily to do in the optimizer (and probably what we'll do at least short term) but @andy-kimball makes a good argument for a layer low in the SQL stack (right above KV) that "injects" values for write-only columns (and perhaps even cooperates directly with the backfill process) and allows the rest of the SQL code to not worry about schema changes (eliminating a whole class of issues). I think that deserves some consideration as a longer-term solution.

**Comment by jordanlewis** [comment] 2019-11-14 15:07
Is this also problematic for computed columns?

**Comment by RaduBerinde** [comment] 2019-11-14 15:17
I don't think so, we seem to recompute those on update.

**Comment by RaduBerinde** [comment] 2019-11-14 15:30
In fact we seem to recompute them in too many cases, filed https://github.com/cockroachdb/cockroach/issues/42482

**Comment by andy-kimball** [comment] 2020-03-14 16:14
The problem is that the optimizer currently reads the values of write-only columns (which goes against rules of write-only columns). However, I don't know how to fix this without introducing a different problem. If we can't read the existing value of a column, then we have to use the default or computed value. But what about columns that are `NOT NULL` with no default or computed value? Also, this idea runs into the following issue:

This runs in transaction A:
```
root@:26257/defaultdb> CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL DEFAULT (10)); INSERT INTO t VALUES (1, 5); SELECT * FROM t;
  x | y
----+----
  1 | 5

root@:26257/defaultdb> BEGIN TRANSACTION; ALTER TABLE t DROP COLUMN y;
ALTER TABLE

root@:26257/defaultdb  OPEN> UPDATE t SET x=2 RETURNING *;
  x
-----
  2
```
Then in transaction B, which will block on the intent created by A:
```
root@:26257/defaultdb> SELECT * FROM t;
```
Now transaction A commits and transaction B will now complete:
```
root@:26257/defaultdb> SELECT * FROM t;
  x | y
----+-----
  2 | 10
```
Notice that although I did not update `y`, it nevertheless got set to `10`, the default value. But what else can we do? We're not allowed to read the existing value of `5`, right?

**Comment by petermattis** [comment] 2020-03-14 16:37
> Notice that although I did not update y, it nevertheless got set to 10, the default value. But what else can we do? We're not allowed to read the existing value of 5, right?

Well, you did update `y` by dropping the column. It happens that a transaction can see an intermediary state, which isn't good. I wonder how much of a problem this is in practice. If you're doing `SELECT *` while concurrently dropping a column from a table your application is going to break anyways. Before dropping the column `y` you need to ensure that none of the queries that can be running concurrently are accessing `y`. The general advice for application developers is to always explicitly name the columns. In this case, `SELECT x FROM t`.

**Comment by RaduBerinde** [comment] 2020-03-14 16:41
I would argue that the original problem is worse because it's not "transient" - if you add a column and do some updates (that seemingly don't affect that column) you can end up with NULL values on a not-null column, and then stay in that state long after the schema change completed.

I am not familiar with schema changes enough but it seems to me that when you're dropping a column, we would first need to wait until all nodes got on board with the new descriptor before doing anything to the table.

**Comment by andy-kimball** [comment] 2020-03-14 16:41
Transactions do not see intermediate state in this case. They're just seeing different versions of the schema, which is how F1 works. That's by-design.

**Comment by andy-kimball** [comment] 2020-03-14 16:47
I don't know that there's a perfect way out of this. So I suspect we'll need to pick the "least surprising behavior". While I agree that using default values is less surprising (i.e. the behavior I show), we still no way to deal with `NOT NULL` columns with no default value. This means it's impossible to drop `NOT NULL` columns. This is what happens when we try:
```
root@:26257/defaultdb> CREATE TABLE t (x INT PRIMARY KEY, y INT NOT NULL); INSERT INTO t VALUES (1, 1); SELECT * FROM t;
  x | y
----+----
  1 | 1

root@:26257/defaultdb> BEGIN TRANSACTION; ALTER TABLE t DROP COLUMN y;
ALTER TABLE

root@:26257/defaultdb  OPEN> UPDATE t SET x=2 RETURNING *;
ERROR: driver: bad connection
warning: connection lost!
```

**Comment by ajwerner** [comment] 2020-03-14 16:49
> This means it's impossible to drop NOT NULL columns. What are we supposed to set those columns to? 
> But what about columns that are NOT NULL with no default or computed value? Also, this idea runs into the following issue:

These shouldn't generally be allowed. Pedantically these should be allowed only if the table has no rows. Today we seem to allow adding, try to do the backfill with `NULL` and fail on the constraint check. If we forced the user transaction trying to add such a column to scan the table and prove it was empty, we should be out of this pickle. 

```
root@127.37.32.100:42321/movr> CREATE TABLE foo (i INT PRIMARY KEY);
CREATE TABLE

Time: 4.227853ms

root@127.37.32.100:42321/movr> ALTER TABLE foo ADD COLUMN j INT NOT NULL;
ALTER TABLE

Time: 69.693582ms

root@127.37.32.100:42321/movr> INSERT INTO foo VALUES (1, 2);
INSERT 1

Time: 2.983224ms

root@127.37.32.100:42321/movr> ALTER TABLE foo ADD COLUMN k INT NOT NULL;
ERROR: null value in column "k" violates not-null constraint
SQLSTATE: 23502
```


> I am not familiar with schema changes enough but it seems to me that when you're dropping a column, we would first need to wait until all nodes got on board with the new descriptor before doing anything to the table.

I agree. Forcing schema changes in transactions to coordinate with concurrent queries seems importnat.

---

Side note. I'm not all too bothered by changing the rules of write only. It seems potentially okay for the query execution reading from non-public columns. It seems like a tough corner to paint ourselves in if we can't. We just need to make sure that those columns don't make their way to the user. 

All that being said, maybe there are other ways out. This seems like a place where a column-masked write operation would be nice. @andreimatei has long dreamed of such a thing. If we could selectively write to just the x column here

**Comment by andy-kimball** [comment] 2020-03-14 16:53
@ajwerner, I think the other interesting case is _dropping_ a `NOT NULL` column (i.e. not just about _adding_). My 2nd example shows why dropping is problematic if we try to fill `write-only` columns with default values.

**Comment by andy-kimball** [comment] 2020-03-14 16:55
Also, as another piece of information, SQL Server does not allow `NOT NULL` columns to be added to a non-empty table unless they have a `DEFAULT` value, for all the reasons that are laid out here.

**Comment by knz** [comment] 2020-03-14 16:59
> >     But what about columns that are NOT NULL with no default or computed value?

> These shouldn't generally be allowed. Pedantically these should be allowed only if the table has no rows.

I was reviewing the thread and this is the correct answer. 

Note that this check is already implemented in crdb, **albeit the code to check this is implemented in the wrong place**:

```
root@127.0.0.1:62613/defaultdb> alter table t add column x int not null;
ERROR: null value in column "x" violates not-null constraint
SQLSTATE: 23502
```

The check is currently implemented in contraint validation *during the backfill*. That's too late - as the participants in this thread have identified above, this implementation creates a segment of time between the apparition of a column desc "NOT NULL with no default" and the actual backfill error, where all badness can occur.

The proper handling of this is IMHO to prevent the  addition of the column at the moment the ALTER statement  is issued, with an optional "is the table empty" check if we want to preserve that behavior.

**Comment by ajwerner** [comment] 2020-03-14 17:00
> Also, as another piece of information, SQL Server does not allow NOT NULL columns to be added to a non-empty table unless they have a DEFAULT value, for all the reasons that are laid out here.

> The check is currently implemented in contraint validation during the backfill. That's too late 

I assumed this and didn't read the code. My bad. Turns out we are smart and have already implemented this policy: https://github.com/cockroachdb/cockroach/blob/a30aedd73d8f0b40a2e7a195d204b3e421e10734/pkg/sql/alter_table.go#L191-L201

> @ajwerner, I think the other interesting case is dropping a NOT NULL column (i.e. not just about adding). My 2nd example shows why dropping is problematic if we try to fill write-only columns with default values.

I'm not sure I totally understand the fundamental problem. When you drop a column, it should become `DELETE_ONLY`. The bug here if we write to that column after the change is in the transaction's seems view of the table descriptor.

**Comment by andy-kimball** [comment] 2020-03-14 17:01
Deleting a column will first transition it to `WRITE_ONLY`, and only then to `DELETE_ONLY`. There's a window where some transactions will be reading the dropped column while others are only writing to it (and not reading).

**Comment by andy-kimball** [comment] 2020-03-14 17:03
An easy way to experiment with this stuff is to drop a column in a transaction:
```
BEGIN TRANSACTION; ALTER TABLE t DROP COLUMN y;
```
That column will be in the `write-only` state for the rest of the transaction, allowing you to experiment with it. We use this trick in a number of SQL logic tests.

**Comment by andy-kimball** [comment] 2020-03-14 17:09
To sum up, if we read columns that are in the `write-only` state, then we run into crashes when adding columns. But if we use default values for columns in the `write-only` state, then we run into crashes when dropping columns.

**Comment by andy-kimball** [comment] 2020-03-14 17:12
Do we have an easy way to create a `DEFAULT` value for all data types? Like 0 for `INT`, empty string for `TEXT`, etc? We could use that for columns in the `write-only` state. Any existing SQL code that does such a thing?

**Comment by jordanlewis** [comment] 2020-03-14 17:18
I don't think there's existing code for that, but it would be very easy to make.

I think the way out here is to teach DROP to be smarter... Andy, can you elaborate here:

>  The code I wrote just crashes in this case, because it tries to set the NOT NULL column to NULL

What was the crash exactly?

**Comment by ajwerner** [comment] 2020-03-14 17:20
>To sum up, if we read columns that are in the write-only state, then we run into crashes when adding columns. But if we use default values for columns in the write-only state, then we run into crashes when dropping columns.

One less than satisfying solution is to disable dropping of `NOT NULL` columns without a `DEFAULT` value. If you want to drop the column you need to add a `DEFAULT`, a cheap schema change.

I do see the general pickle here now. It's awkward because a transaction can see a row under a schema with a column that doesn't exist when the row is written.

**Comment by andy-kimball** [comment] 2020-03-14 17:20
Here's the crash:
```
* ERROR: [n1,client=[::1]:51758,hostnossl,user=root] a panic has occurred!
*
panic while executing 1 statements: UPDATE _ SET _ = _ RETURNING *

goroutine 969 [running]:
runtime/debug.Stack(0x84ae8c0, 0xc0006d5a40, 0x3)
	/usr/local/Cellar/go@1.12/1.12.17/libexec/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x84ae8c0, 0xc0006d5a40, 0xc00053f500, 0x78a8bc0, 0xc005afe000, 0x1)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:218 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000d32000, 0x84ae8c0, 0xc0006d5a40, 0x7590ee0, 0xae6de20)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:829 +0x34f
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000d32000, 0x84ae8c0, 0xc0006d5a40)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476 +0x61
panic(0x7590ee0, 0xae6de20)
	/usr/local/Cellar/go@1.12/1.12.17/libexec/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MarshalColumnValue(0xc0045adef8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/column_type_encoding.go:778 +0xcf
github.com/cockroachdb/cockroach/pkg/sql/row.(*Inserter).InsertRow(0xc005b64208, 0x84ae8c0, 0xc006256280, 0x84aee00, 0xc0074c0b00, 0xc0068a7420, 0x2, 0x2, 0x0, 0x0, ...)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/inserter.go:147 +0xe0
github.com/cockroachdb/cockroach/pkg/sql/row.(*Updater).UpdateRow(0xc005b64048, 0x84ae8c0, 0xc006256280, 0xc0074c0b00, 0xc0068a75a0, 0x1, 0x2, 0xc0003e5450, 0x1, 0x1, ...)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/row/updater.go:404 +0x2cea
github.com/cockroachdb/cockroach/pkg/sql.(*tableUpdater).rowForUpdate(...)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_update.go:53
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).processSourceRow(0xc005b64000, 0x84ae8c0, 0xc006256280, 0xc007677b00, 0xc000d323b8, 0xc0068a75a0, 0x2, 0x2, 0x0, 0x7c24830)
	/Users/andyk/go/src/github.com/cockroachdb/cockroach/pkg/sql/update.go:309 +0x7e6
github.com/cockroachdb/cockroach/pkg/sql.(*updateNode).BatchedNext(0xc005b64000, 0x84ae8c0, 0xc006256280, 0xc007677b00, 0xc000d323b8, 0x0, 0x0, 0xc00571ba10)
```
How do you think DROP could be smarter?

**Comment by andy-kimball** [comment] 2020-03-14 17:21
> One less than satisfying solution is to disable dropping of NOT NULL columns without a DEFAULT value. If you want to drop the column you need to add a DEFAULT, a cheap schema change.

That is along lines I'm suggesting, except that I'm proposing to create a default DEFAULT value. : )

**Comment by jordanlewis** [comment] 2020-03-14 17:21
We can teach `DROP` to behave slightly differently. First, it changes the column to be nullable. Then, it drops the column.

**Comment by andy-kimball** [comment] 2020-03-14 17:22
> We can teach DROP to behave slightly differently. First, it changes the column to be nullable. Then, it drops the column.
Yes, that's another interesting option.

**Comment by ajwerner** [comment] 2020-03-14 17:25
> We can teach DROP to behave slightly differently. First, it changes the column to be nullable. Then, it drops the column.

Does this require coordinating with concurrent transactions. Namely making sure that those concurrent transactions can handle a null value before the schema change commits?

**Comment by andy-kimball** [comment] 2020-03-14 17:28
I think if an application is dropping a column, it should not have concurrent transactions trying to access that column. So when that happens, it's an edge case. I think it's OK for us to define how that edge case works, as long as our definition is simple and predictable (like saying that we first make column NULL and then drop it). It's just not OK to crash.

**Comment by ajwerner** [comment] 2020-03-14 17:34
> it should not have concurrent transactions trying to access that column

I'm not enthusiastic about this perspective. Cockroach offers a lot of reflection via pg_catalog etc. It's pretty reasonable for transaction shape to be based on schema read from a catalog at runtime.

>  I think it's OK for us to define how that edge case works, as long as our definition is simple and predictable (like saying that we first make column NULL and then drop it). It's just not OK to crash.

100% agree. I think forcing a `DEFAULT` value, whether explicit or explicit is a good way out of this in the short term. 

As far as dropping the `NOT NULL` constraint goes, there may be something there, I'm just working to understand how the implementation might work. To avoid the crash we need to be sure that by the time the NULL value is committed, no readers believe that column is `NOT NULL`.

**Comment by andy-kimball** [comment] 2020-03-14 17:39
> I'm not enthusiastic about this perspective.

My point is not that we shouldn't expect it to happen; just that it should be quite rare without clear user expectations of how it should behave, and therefore we have more freedom to define our semantics when it does happen.

**Comment by andy-kimball** [comment] 2020-03-14 18:04
Another piece of data: my testing indicates that the original issue that Radu/Raphael describe has caused a crash (due to NULL values in non-NULL columns) as far back as 2.1. So this issue is independent of adding CBO-based mutations in 19.1.

**Comment by awoods187** [comment] 2020-03-17 02:14
What is the expectation for when we want to address this?

**Comment by ajwerner** [comment] 2020-03-17 02:29
> What is the expectation for when we want to address this?

I'm in favour of disabling dropping of `NOT NULL` columns in explicit transactions ASAP (this release, right now!?) as the first step. Sure it's a new limitation but the alternative is crashing and that's horrible.

Andy Kimball is advocating that dropping that column should just implicitly add a default in the process to some zero value for each data type. That way if you, in that same transaction, add a new row (and thus don't have a value for that column), we don't write `NULL`, but instead write this new non-`NULL` value. I'm not at all opposed to that proposal. It will only be detected in the rarest of cases and even then it's explainable. 

We'd need to enumerate a default zero value for each type. The only challenging one that pops out to me are the timestamps. Maybe we use unix epoch time? January 1st, 1970. People in computing circles tend to recognize that as zero.

**Comment by andy-kimball** [comment] 2020-03-17 15:37
This is on the list of Release Blockers, and I'm working on fixing it. My plan is to use a zero value for each type for NOT NULL cases. This is what I'm proposing to use as zero values:
```
		{t: types.Bool, expected: "false"},
		{t: types.Int, expected: "0:::INT8"},
		{t: types.Int2, expected: "0:::INT8"},
		{t: types.Int4, expected: "0:::INT8"},
		{t: types.Float, expected: "0.0:::FLOAT8"},
		{t: types.Float4, expected: "0.0:::FLOAT8"},
		{t: types.Decimal, expected: "0:::DECIMAL"},
		{t: types.MakeDecimal(10, 5), expected: "0:::DECIMAL"},
		{t: types.Date, expected: "'2000-01-01':::DATE"},
		{t: types.Timestamp, expected: "'0001-01-01 00:00:00+00:00':::TIMESTAMP"},
		{t: types.Interval, expected: "'00:00:00':::INTERVAL"},
		{t: types.String, expected: "'':::STRING"},
		{t: types.MakeChar(3), expected: "'':::STRING"},
		{t: types.Bytes, expected: "'\\x':::BYTES"},
		{t: types.TimestampTZ, expected: "'0001-01-01 00:00:00+00:00':::TIMESTAMPTZ"},
		{t: types.MakeCollatedString(types.MakeVarChar(10), "de"), expected: "'' COLLATE de"},
		{t: types.MakeCollatedString(types.VarChar, "en_US"), expected: "'' COLLATE en_US"},
		{t: types.Oid, expected: "26:::OID"},
		{t: types.RegClass, expected: "crdb_internal.create_regclass(2205,'regclass'):::REGCLASS"},
		{t: types.Unknown, expected: "NULL"},
		{t: types.Uuid, expected: "'00000000-0000-0000-0000-000000000000':::UUID"},
		{t: types.MakeArray(types.Int), expected: "ARRAY[]:::INT8[]"},
		{t: types.MakeArray(types.MakeArray(types.String)), expected: "ARRAY[]:::STRING[][]"},
		{t: types.OidVector, expected: "ARRAY[]:::OID[]"},
		{t: types.INet, expected: "'0.0.0.0/0':::INET"},
		{t: types.Time, expected: "'00:00:00':::TIME"},
		{t: types.Jsonb, expected: "'null':::JSONB"},
		{t: types.TimeTZ, expected: "'00:00:00+00:00:00':::TIMETZ"},
		{t: types.MakeTuple([]types.T{}), expected: "()"},
		{t: types.MakeTuple([]types.T{*types.Int, *types.MakeChar(1)}), expected: "(0:::INT8, '':::STRING)"},
		{t: types.MakeTuple([]types.T{*types.OidVector, *types.MakeTuple([]types.T{*types.Float})}), expected: "(ARRAY[]:::OID[], (0.0:::FLOAT8,))"},
		{t: types.VarBit, expected: "B''"},
		{t: types.MakeBit(5), expected: "B''"},
```

**Closed** 2020-03-20 05:50 UTC
