### ISSUE TITLE
geo/geogfn: unknown signature: st_distance(geography, geometry)

### ISSUE THREAD

**Issue by timgraham** [cockroachdb/cockroach#53720] opened 2020-08-31 23:29 UTC
**Describe the problem**

PostGIS doesn't [document](https://postgis.net/docs/ST_Distance.html) that ST_Distance (implemented in https://github.com/cockroachdb/cockroach/issues/48395) has that signature but I guess it works.

**To Reproduce**

```sql
SELECT "geogapp_city"."name" FROM "geogapp_city"
WHERE ST_Distance("geogapp_city"."point", ST_GeomFromEWKB('...'::bytea)) <= 804672.0
```

**Environment:**
 - CockroachDB version 20.2 alpha 3

**Comment by otan** [comment] 2020-08-31 23:47
>  unknown signature: st_distance(geography, geometry)

this is because we don't have implicit casts from geometry->geography :(
this would be a duplicate of #38965

**Closed** 2020-08-31 23:48 UTC
Labels: C-bug, O-community, X-blathers-triaged
