### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestStoreRangeSplitStats

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6748] opened 2016-05-17 12:19 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/2cc5a467f6c280e97e49a22b884b649fd7790273

Stress build found a failed test:

```
=== RUN   TestStoreRangeSplitStats
I160517 07:24:34.574483 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160517 07:24:34.575211 gossip/gossip.go:893  not connected to cluster; use --join to specify a connected node
I160517 07:24:34.577161 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1.000000123s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I160517 07:24:34.578130 storage/replica_command.go:2011  initiating a split of range=1 [/Min-/Max) at key /Table/50
I160517 07:24:34.580548 storage/replica_command.go:1470  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1.000000123s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I160517 07:24:34.605112 storage/replica_command.go:2011  initiating a split of range=2 [/Table/50-/Max) at key /Table/50/0/"Z"
W160517 07:24:34.605402 storage/stores.go:200  range not contained in one range: [/Meta2/Table/50/0/"Z",/Table/50/0/"Z\x00"), but have [/Min,/Table/50)
I160517 07:24:34.608896 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:338
1      storage/intent_resolver.go:299
I160517 07:24:34.617668 stopper.go:352  draining; tasks left:
1      storage/intent_resolver.go:299
W160517 07:25:34.577609 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:25:34.577663 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:26:34.577591 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:26:34.577636 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:27:34.577608 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:27:34.577663 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:28:34.577613 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:28:34.577664 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:29:34.577718 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:29:34.577810 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:30:34.577627 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:30:34.577646 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:31:34.577610 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:31:34.577756 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
W160517 07:32:34.577595 storage/store.go:995  [node=1,store=1] error gossiping first range data: storage/replica.go:2126: node is stopping
W160517 07:32:34.577779 storage/store.go:1014  [node=1,store=1] error gossiping system config: storage/replica.go:2126: node is stopping
SIGABRT: abort
PC=0x62de21 m=0

goroutine 0 [idle]:
runtime.futex(0x2801188, 0x0, 0x0, 0x0, 0x0, 0x2800010, 0x0, 0x0, 0x5dc6f4, 0x2801188, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x2801188, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x2801188)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc82001aa00, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc82006ea80)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7ffe96854c10)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 8 minutes]:
testing.RunTests(0x1d7d610, 0x25283a0, 0x10f, 0x10f, 0xc82012bd01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8200efef8, 0xc820307c98)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc8200efef8)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:54 +0x1de
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:604 +0x114

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 35 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x27fff20)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 15663 [semacquire, 8 minutes]:
sync.runtime_Syncsemacquire(0xc82113e5d0)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82113e5c0)
	/usr/local/go/src/sync/cond.go:63 +0x9b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Quiesce(0xc82144e4d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:354 +0x1eb
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc82144e4d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:300 +0x1a7
github.com/cockroachdb/cockroach/storage_test.TestStoreRangeSplitStats(0xc8212c0750)
	/go/src/github.com/cockroachdb/cockroach/storage/client_split_test.go:494 +0x1e08
testing.tRunner(0xc8212c0750, 0x2529bd0)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 15735 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func4()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:921 +0x13d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc82112b340)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15723 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4c80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15722 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc82144fc70, 0xececcbe32, 0x2262c243, 0x27ff340, 0xc82113e600, 0xc82144e4d0, 0xc820898f00, 0xc820545e98)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:161 +0x568
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc820898f00, 0xc821b86930)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:203 +0x78
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc821b86cc0, 0xc8215aca00)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:231 +0x246
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:205 +0x21e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4c40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15724 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4ca0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15733 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2059 +0xbf1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8203639f0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15728 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4d20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15737 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1011 +0x3cf
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc82112b380)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15679 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:123 +0x86a
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc821b68050)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15732 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:225 +0x23f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc82112a460)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15736 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:992 +0x3cf
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc82112b360)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15727 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4d00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15746 [runnable]:
time.absDate(0x7ffffffe7214923f, 0x2698f01, 0x27ff340, 0x7ffffffe7214923f, 0x11, 0x89)
	/usr/local/go/src/time/time.go:678
time.Time.date(0xececcc03f, 0xc802698f8b, 0x27ff340, 0x8d4901, 0x7e0, 0x5, 0x11, 0x89)
	/usr/local/go/src/time/time.go:674 +0x4a
time.Time.Day(0xececcc03f, 0x2698f8b, 0x27ff340, 0x11)
	/usr/local/go/src/time/time.go:309 +0x38
golang.org/x/net/trace.(*trace).delta(0xc8202763c0, 0xececcc03f, 0x2698f8b, 0x27ff340, 0x1d779dc, 0x1d779dd)
	/go/src/golang.org/x/net/trace/trace.go:729 +0x15e
golang.org/x/net/trace.(*trace).addEvent(0xc8202763c0, 0x17c7da0, 0xc821b192c0, 0x15e0000)
	/go/src/golang.org/x/net/trace/trace.go:755 +0x308
golang.org/x/net/trace.(*trace).LazyPrintf(0xc8202763c0, 0x19bd558, 0x2, 0xc8219ca010, 0x1, 0x1)
	/go/src/golang.org/x/net/trace/trace.go:790 +0xa2
github.com/opentracing/basictracer-go.glob.func2.1(0x1862220, 0xc8218baa80)
	/go/src/github.com/opentracing/basictracer-go/event_nettrace.go:19 +0x343
github.com/opentracing/basictracer-go.(*spanImpl).onLog(0xc8214a6360, 0x0, 0x0, 0x0, 0xc820abd7a0, 0x1e, 0x0, 0x0)
	/go/src/github.com/opentracing/basictracer-go/event.go:40 +0xc4
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc8214a6360, 0x0, 0x0, 0x0, 0xc820abd7a0, 0x1e, 0x0, 0x0)
	/go/src/github.com/opentracing/basictracer-go/span.go:109 +0x114
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc8214a6360, 0xc820abd7a0, 0x1e)
	/go/src/github.com/opentracing/basictracer-go/span.go:94 +0x7d
github.com/cockroachdb/cockroach/util/log.Trace(0x7f4c1bb69938, 0xc821b19140, 0xc820abd7a0, 0x1e)
	/go/src/github.com/cockroachdb/cockroach/util/log/trace.go:29 +0x63
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc820e1af00, 0x7f4c1bb69938, 0xc821b19140, 0xdf, 0x209fce6, 0x100000001, 0x1, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1824 +0x10e6
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc82113e740, 0x7f4c1bb69938, 0xc821b190e0, 0x0, 0x0, 0x100000001, 0x1, 0x3, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/stores.go:178 +0x501
github.com/cockroachdb/cockroach/kv.(*senderTransport).SendNext(0xc8202dc1b0, 0xc8219320c0)
	/go/src/github.com/cockroachdb/cockroach/kv/transport.go:290 +0x3cc
github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas(0xc8212c0990, 0x7f4c1bb69938, 0xc82166e030, 0x1, 0x2540be400, 0xb2d05e00, 0xc821b864b0, 0x2, 0xc8210680e0, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1007 +0x8eb
github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC(0xc8212c0990, 0x7f4c1bb69938, 0xc82166e030, 0x2, 0xc8210680e0, 0x1, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:337 +0x230
github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange(0xc8212c0990, 0x7f4c1bb69938, 0xc82166e030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:452 +0x206
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2(0xc8215ddf40, 0xc8215ddbf0, 0xc8215de6d0, 0xc8212c0990, 0xc8215de6c0, 0x4, 0xd)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:711 +0x448
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc8212c0990, 0x7f4c1bb69938, 0xc82166e030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:712 +0x9e1
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc8212c0990, 0x7f4c1bb69938, 0xc82166e030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:556 +0x6d5
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc821140f00, 0x7f4c1bb69938, 0xc82166e030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:367 +0xa5d
github.com/cockroachdb/cockroach/client.(*DB).send(0xc820dc22d0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:471 +0x3ee
github.com/cockroachdb/cockroach/client.(*DB).(github.com/cockroachdb/cockroach/client.send)-fm(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:418 +0x37
github.com/cockroachdb/cockroach/client.sendAndFill(0xc8215df508, 0xc8212fe000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:400 +0x200
github.com/cockroachdb/cockroach/client.(*DB).Run(0xc820dc22d0, 0xc8212fe000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:418 +0x85
github.com/cockroachdb/cockroach/storage.(*intentResolver).maybePushTransactions(0xc82112a540, 0x7f4c1baef610, 0xc82166e000, 0xc82096f440, 0x2, 0x2, 0xdf, 0xd, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/storage/intent_resolver.go:223 +0x783
github.com/cockroachdb/cockroach/storage.(*intentResolver).processIntentsAsync.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/intent_resolver.go:275 +0x174
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunLimitedAsyncTask.func1(0xc82144e4d0, 0x222d823, 0x1a, 0x12b, 0xc8211410e0, 0xc8217a8d40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:218 +0x8d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunLimitedAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:219 +0x1e2

goroutine 15721 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4c20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15726 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4ce0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15731 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc821140f00)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:203 +0xd21
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:188 +0x20
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8203629c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15725 [select, 8 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x303
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82144e4d0, 0xc8210a4cc0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 15664 [chan receive, 8 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc821140300)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:164 +0x3a
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:165 +0x8f4

rax    0xca
rbx    0x0
rcx    0x62de23
rdx    0x0
rdi    0x2801188
rsi    0x0
rbp    0x1
rsp    0x7ffe96854a70
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x14d
r13    0x1d779de
r14    0x1
r15    0x2c
rip    0x62de21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
19 runs so far, 0 failures, over 1m15s
32 runs so far, 0 failures, over 1m20s
32 runs so far, 0 failures, over 1m25s
32 runs so far, 0 failures, over 1m30s
32 runs so far, 0 failures, over 1m35s
32 runs so far, 0 failures, over 1m40s
32 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
47 runs so far, 0 failures, over 1m55s
47 runs so far, 0 failures, over 2m0s
47 runs so far, 0 failures, over 2m5s
47 runs so far, 0 failures, over 2m10s
47 runs so far, 0 failures, over 2m15s
47 runs so far, 0 failures, over 2m20s
48 runs so far, 0 failures, over 2m25s
53 runs so far, 0 failures, over 2m30s
62 runs so far, 0 failures, over 2m35s
62 runs so far, 0 failures, over 2m40s
62 runs so far, 0 failures, over 2m45s
62 runs so far, 0 failures, over 2m50s
62 runs so far, 0 failures, over 2m55s
62 runs so far, 0 failures, over 3m0s
66 runs so far, 0 failures, over 3m5s
76 runs so far, 0 failures, over 3m10s
77 runs so far, 0 failures, over 3m15s
77 runs so far, 0 failures, over 3m20s
77 runs so far, 0 failures, over 3m25s
77 runs so far, 0 failures, over 3m30s
77 runs so far, 0 failures, over 3m35s
79 runs so far, 0 failures, over 3m40s
88 runs so far, 0 failures, over 3m45s
91 runs so far, 0 failures, over 3m50s
91 runs so far, 0 failures, over 3m55s
91 runs so far, 0 failures, over 4m0s
91 runs so far, 0 failures, over 4m5s
91 runs so far, 0 failures, over 4m10s
93 runs so far, 0 failures, over 4m15s
99 runs so far, 0 failures, over 4m20s
105 runs so far, 0 failures, over 4m25s
105 runs so far, 0 failures, over 4m30s
105 runs so far, 0 failures, over 4m35s
105 runs so far, 0 failures, over 4m40s
106 runs so far, 0 failures, over 4m45s
108 runs so far, 0 failures, over 4m50s
114 runs so far, 0 failures, over 4m55s
120 runs so far, 0 failures, over 5m0s
120 runs so far, 0 failures, over 5m5s
120 runs so far, 0 failures, over 5m10s
120 runs so far, 0 failures, over 5m15s
121 runs so far, 0 failures, over 5m20s
123 runs so far, 0 failures, over 5m25s
128 runs so far, 0 failures, over 5m30s
132 runs so far, 0 failures, over 5m35s
134 runs so far, 0 failures, over 5m40s
134 runs so far, 0 failures, over 5m45s
134 runs so far, 0 failures, over 5m50s
136 runs so far, 0 failures, over 5m55s
137 runs so far, 0 failures, over 6m0s
141 runs so far, 0 failures, over 6m5s
145 runs so far, 0 failures, over 6m10s
148 runs so far, 0 failures, over 6m15s
148 runs so far, 0 failures, over 6m20s
148 runs so far, 0 failures, over 6m25s
150 runs so far, 0 failures, over 6m30s
152 runs so far, 0 failures, over 6m35s
156 runs so far, 0 failures, over 6m40s
160 runs so far, 0 failures, over 6m45s
163 runs so far, 0 failures, over 6m50s
163 runs so far, 0 failures, over 6m55s
163 runs so far, 0 failures, over 7m0s
165 runs so far, 0 failures, over 7m5s
166 runs so far, 0 failures, over 7m10s
171 runs so far, 0 failures, over 7m15s
174 runs so far, 0 failures, over 7m20s
178 runs so far, 0 failures, over 7m25s
178 runs so far, 0 failures, over 7m30s
178 runs so far, 0 failures, over 7m35s
180 runs so far, 0 failures, over 7m40s
181 runs so far, 0 failures, over 7m45s
185 runs so far, 0 failures, over 7m50s
188 runs so far, 0 failures, over 7m55s
192 runs so far, 0 failures, over 8m0s
192 runs so far, 0 failures, over 8m5s
193 runs so far, 0 failures, over 8m10s
194 runs so far, 0 failures, over 8m15s
195 runs so far, 0 failures, over 8m20s
199 runs so far, 0 failures, over 8m25s
201 runs so far, 0 failures, over 8m30s
206 runs so far, 0 failures, over 8m35s
207 runs so far, 0 failures, over 8m40s
207 runs so far, 0 failures, over 8m45s
208 runs so far, 0 failures, over 8m50s
211 runs so far, 0 failures, over 8m55s
214 runs so far, 0 failures, over 9m0s
216 runs so far, 0 failures, over 9m5s
221 runs so far, 0 failures, over 9m10s
221 runs so far, 0 failures, over 9m15s
222 runs so far, 0 failures, over 9m20s
223 runs so far, 0 failures, over 9m25s
226 runs so far, 0 failures, over 9m30s
228 runs so far, 0 failures, over 9m35s
230 runs so far, 0 failures, over 9m40s
235 runs so far, 0 failures, over 9m45s
235 runs so far, 0 failures, over 9m50s
236 runs so far, 0 failures, over 9m55s
237 runs so far, 0 failures, over 10m0s
240 runs so far, 0 failures, over 10m5s
242 runs so far, 0 failures, over 10m10s
244 runs so far, 0 failures, over 10m15s
249 runs so far, 0 failures, over 10m20s
249 runs so far, 0 failures, over 10m25s
250 runs so far, 0 failures, over 10m30s
252 runs so far, 0 failures, over 10m35s
254 runs so far, 0 failures, over 10m40s
257 runs so far, 0 failures, over 10m45s
259 runs so far, 0 failures, over 10m50s
264 runs so far, 0 failures, over 10m55s
264 runs so far, 0 failures, over 11m0s
265 runs so far, 0 failures, over 11m5s
267 runs so far, 0 failures, over 11m10s
269 runs so far, 0 failures, over 11m15s
271 runs completed, 1 failures, over 11m16s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2016-05-24 16:38
Looks like something might've been caught in an infinite loop in `DistSender`. Since the node is draining, maybe we're using a retry loop that doesn't have the stopper wired in somewhere.

**Comment by tschottdorf** [comment] 2016-07-12 11:50
Closing as not reproducable after `make stress PKG=./storage TESTS=TestStoreRangeSplitStats STRESSFLAGS='-maxfails 1 -stderr -maxruns 15000 -p 16'` (and the same without `-p`).

**Closed by tschottdorf** 2016-07-12 11:50 UTC
Labels: Robot, test-failure
