### ISSUE TITLE
release: v20.1.4

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#51919] opened 2020-07-27 15:33 UTC
Candidate SHA: [`12049d3fe3650660e1b6abf1e522d9bb016acb88`](https://github.com/cockroachdb/cockroach/commit/12049d3fe3650660e1b6abf1e522d9bb016acb88)
Deployment status: restarted 20.1.4 cluster with new SHA

Qualification Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=2129919

Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=2129939
 
Admin UI for Qualification Clusters:
- Old Version: http://radu-release-v2013-7fd454f8-0001.roachprod.crdb.io:26258/
- New Version: http://radu-release-v2014-97b6fc07-0001.roachprod.crdb.io:26258/
(note: this cluster was started with 97b6fc07 and later bumped to 12049d3f)
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: 2020-07-27
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA)
  - [x] fill in `Candidate SHA` above
  - [x] email thread on releases@
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] Ack security@ and release-engineering-team@ on the generated AWS S3 bucket write Alert to confirm these writes were part of a planned release (Just reply on the email received alert email acking that this was part of the release process)
 
Release Qualification
- [x] [Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in all WIP elements above (Nightly Suite, Admin UI, etc.)
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Roachtest-Failure-Signoff)
 
- [x] [Keep an eye on clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters) until release date. Do not proceed below until the release date.
 
Release date: 2020-08-03
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/328859690/Release+Qualification#Monitoring-the-Qualification-Clusters)
- [x] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-11.Tagtherelease)
- [x] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
- [x] If applicable, [update the map that roachtests use to map a version to a previous version, to reference the newly tagged version](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/test_runner.go#L1145)
 
- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
 
- For production or stable releases
  - [x] Announce version to the [registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
 
- [x] Update docs
- [x] External communications for release
 
Cleanup:
- [x] Clean up provisional tag from repository
- [x] Destroy roachprod clusters

**Comment by RaduBerinde** [comment] 2020-07-28 14:39
## Nightly test failures ##

### Random Syntax Tests ###
https://teamcity.cockroachdb.com/viewLog.html?buildId=2121237&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests

- [ ] TestRandomSyntaxSchemaChangeColumn
- [ ] TestRandomSyntaxGeneration

**Comment by RaduBerinde** [comment] 2020-07-28 14:41
Signing off for TestRandomSyntaxSchemaChangeColumn (similar failure like [last release](https://github.com/cockroachdb/cockroach/issues/50528)) and TestRandomSyntaxGeneration (it's a minor issue - I backported a fix for it in #51948, but no need to pick a new SHA).

**Comment by RaduBerinde** [comment] 2020-07-29 15:48
Restarting the process with new SHA `97b6fc07480fc845a60f73224d28cf2e6dcda25d` (to include #52003).

For the docs team, if you started preparing notes based on the old SHA, these are the release notes of the changes that are on top of that:
```
    Release note (bug fix): Previously, RESTORE would sometimes block at the
    end of the job when sending its results back if the connection that
    started the job disconnected. This is now fixed.

    Release note (bug fix): CockroachDB previously could crash on some
    queries with merge joins, and this has now been fixed.

    Release note (bug fix): Previously, a BACKUP job would block once it
    finished backing up the data.

    Release note (bug fix): CockroachDB could previously encounter benign
    internal "context canceled" errors when queries were executed by the
    vectorized engine.

    Release note (bug fix): Increase robustness of restore against
    descriptors which may be in an unexpected state.
```
Full git commit logs here: https://gist.github.com/RaduBerinde/8fad858dbbe41dad9a9b28e8b5571b05

**Comment by RaduBerinde** [comment] 2020-07-29 22:32
Restarting the process with new SHA `12049d3fe3650660e1b6abf1e522d9bb016acb88` (to include #52072).

There is only one change on top of the previous SHA, and it has no release note.

**Comment by yuzefovich** [comment] 2020-07-30 15:44
Signing off on `tpchvec/perf` (vectorize ON is more than 20% slower than vectorize OFF on Q15), this seems like a noise and shouldn't block the release, but I'll look into that more closerly.

**Comment by adityamaru** [comment] 2020-07-30 16:08
Signing off on `import/tpch/nodes=8`. There was a dead node because of clock sync error:
`remote wall time is too far ahead (996.848547ms) to be trustworthy
 [n5] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (4 of 9 are within the offset)`

Signing off on `jobs/mixed-versions`. Will be fixed by #51951.

**Comment by pbardea** [comment] 2020-07-30 16:14
Re: `jobs/mixed-versions`, this is a different failure than then one that will be fixed by #51951. However, this test has been quite flaky and it looks like we've been seeing this error since at least June 6: https://github.com/cockroachdb/cockroach/issues/48194#issuecomment-640004533. It's certainly not a regression, but worth looking into separately.

**Comment by rafiss** [comment] 2020-07-30 16:35
Signed off on AppDev tests. There are a few existing flaky tests that we are excluding now.

**Comment by andreimatei** [comment] 2020-07-30 18:58
Signed off on all KVs.

**Closed** 2020-08-04 15:22 UTC
