### ISSUE TITLE
sql: SCRUB problem with column families

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#41002] opened 2019-09-23 21:56 UTC
See the following which creates two identical tables but with differing column families. SCRUB fails on the second one with the below error.

```
CREATE TABLE t (
    id INT8 PRIMARY KEY, name STRING, data INT8 DEFAULT 2,
    CONSTRAINT abc CHECK (name > 'he'),
    INDEX name_idx (name)
);

INSERT INTO t VALUES (1, 'hello'), (2, 'help'), (0, 'heeee');

EXPERIMENTAL SCRUB TABLE t;

DROP TABLE t;

CREATE TABLE t (
    id INT8 PRIMARY KEY, name STRING, data INT8 DEFAULT 2,
    CONSTRAINT abc CHECK (name > 'he'),
    INDEX name_idx (name),
    FAMILY (name),
    FAMILY (data)
);

INSERT INTO t VALUES (1, 'hello'), (2, 'help'), (0, 'heeee');

EXPERIMENTAL SCRUB TABLE t;
```

```
  job_uuid |         error_type         | database  | table | primary_key |            timestamp             | repaired |                                                                                                            details                                                                                                             
+----------+----------------------------+-----------+-------+-------------+----------------------------------+----------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
  NULL     | index_value_decoding_error | defaultdb | t     | (0)         | 2019-09-23 21:52:29.016735+00:00 |  false   | {"error_message": "value failed to round-trip encode. Column=data colIDDiff=3 Key=/Table/53/1/1/0 expected \\"\\", got: []byte{0x33, 0x4}", "index_name": "primary", "row_data": {"data": "2", "id": "0", "name": "'heeee'"}}  
  NULL     | index_value_decoding_error | defaultdb | t     | (1)         | 2019-09-23 21:52:29.016735+00:00 |  false   | {"error_message": "value failed to round-trip encode. Column=data colIDDiff=3 Key=/Table/53/1/2/0 expected \\"\\", got: []byte{0x33, 0x4}", "index_name": "primary", "row_data": {"data": "2", "id": "1", "name": "'hello'"}}  
  NULL     | index_value_decoding_error | defaultdb | t     | (2)         | 2019-09-23 21:52:29.016735+00:00 |  false   | {"error_message": "value failed to round-trip encode. Column=data colIDDiff=3 Key=/Min expected \\"\\", got: []byte{0x33, 0x4}", "index_name": "primary", "row_data": {"data": "2", "id": "2", "name": "'help'"}} 
```

Jira issue: CRDB-5493

**Comment by postamar** [comment] 2022-03-08 20:14
Closing because I can't reproduce this.

**Closed by postamar** 2022-03-08 20:14 UTC
Labels: C-bug, A-sql-scrub, T-sql-schema
