### ISSUE TITLE
circleci: failed tests (14347): TestGossipCullNetwork 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5130] opened 2016-03-11 05:01 UTC
The following test appears to have failed:

[#14347](https://circleci.com/gh/cockroachdb/cockroach/14347):

```
I160311 04:57:19.988451 gossip/server.go:258  @1: distantHops: 1 from 3
I160311 04:57:19.988653 gossip/client.go:146  node 1 received [node:4] from node 4 (0 fresh)
I160311 04:57:19.988727 gossip/server.go:258  @1: distantHops: 1 from 4
E160311 04:57:19.991605 rpc/context.go:155  rpc error: code = 13 desc = "transport is closing"
E160311 04:57:19.991859 rpc/context.go:155  rpc error: code = 13 desc = "transport is closing"
--- FAIL: TestGossipCullNetwork (5.11s)
	<autogenerated>:31: Leaked goroutine: goroutine 739 [select]:
		google.golang.org/grpc/transport.(*serverHandlerTransport).runStream(0xc82028c0c0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:345 +0x154
		google.golang.org/grpc/transport.(*serverHandlerTransport).HandleStreams(0xc82028c0c0, 0xc82023acc0)
			/go/src/google.golang.org/grpc/transport/handler_server.go:335 +0x112b
		google.golang.org/grpc.(*Server).serveStreams(0xc820134200, 0x7fd0b3232720, 0xc82028c0c0)
			/go/src/google.golang.org/grpc/server.go:325 +0x1dd
		google.golang.org/grpc.(*Server).ServeHTTP(0xc820134200, 0x7fd0b3232698, 0xc820026438, 0xc820124b60)
			/go/src/google.golang.org/grpc/server.go:368 +0x1c0
		net/http.(Handler).ServeHTTP-fm(0x7fd0b3232698, 0xc820026438, 0xc820124b60)
--
I160311 04:57:27.493865 gossip/server.go:203  node 1 received [127.0.0.1:58331] from node 2 (0 fresh)
I160311 04:57:27.494011 gossip/server.go:258  @1: distantHops: 1 from 2
I160311 04:57:27.495241 gossip/server.go:203  node 1 received [127.0.0.1:58331] from node 2 (1 fresh)
I160311 04:57:27.495342 gossip/server.go:258  @1: distantHops: 1 from 3
--- PASS: TestGossipStorage (0.09s)
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	8.154s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.056s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 12:43
Seems to be fixed by #5169 which changed tests to use `grpc.Server.Server` instead of `grpc.Server.ServeHTTP`. I can't reproduce any failure with this test using `make stress` on master.

**Closed by petermattis** 2016-03-14 12:43 UTC
Labels: test-failure
