### ISSUE TITLE
Unable to copy a table if it contains a boolean column

### ISSUE THREAD

**Issue by dhannum** [cockroachdb/cockroach#17087] opened 2017-07-18 18:55 UTC
Hi,

Create table as select throws an error if the source table contains at least one boolean column. If the source table has no boolean columns, everything works great.

Here is a test case:

```SQL
create table test_bool
(
        foo boolean NOT NULL
);
insert into test_bool values (true);
create table test_bool2 as select * from test_bool;
```

When I run this from my favorite SQL tool, here's the error that comes back

Code: 0, SQL State: XX000]  ERROR: value type bool cannot be used for table columns

I've also tried it with explicitly making the table column bool and the same issue happens.

**Comment by dhannum** [comment] 2017-07-18 19:52
This also happens when you "create view as select..." Same issue

**Comment by jordanlewis** [comment] 2017-07-18 19:53
Hi @dhannum, thanks for the report. I can't reproduce this on master:

```
root@:26257/test> create table fnord (foo boolean not null);
CREATE TABLE
root@:26257/test> insert into fnord values(true);
INSERT 1
root@:26257/test> create table fnord2 as select * from fnord;
SELECT 1
root@:26257/test> select * from fnord2;
+------+
| foo  |
+------+
| true |
+------+
(1 row)
```

I think this issue is a duplicate of #15827, which again is fixed on master but not in the 1.0 release branch.

**Comment by dhannum** [comment] 2017-07-19 13:52
I see on the duplicate issue that it's assigned to 1.1? Is there a target release date? Working around this is rather inconvenient. Thanks!

**Comment by jordanlewis** [comment] 2017-07-19 14:02
We're planning to release a 1.0.4 version soon as well, which will contain the fix.

If you're feeling adventurous, you can also use an alpha release, which won't exhibit this issue.

**Comment by jordanlewis** [comment] 2017-07-28 21:46
[1.0.4](https://www.cockroachlabs.com/docs/releases/v1.0.4.html) contains the fix. Thanks @dhannum!

**Closed by jordanlewis** 2017-07-28 21:46 UTC
