### ISSUE TITLE
roachperf: regression on 2022-08-17

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#86847] opened 2022-08-25 09:46 UTC
Seeing a pretty clear regression on `kv95/enc=false/nodes=3/cpu=32/size=64kb`. This does not line up with the regression over in #86541, which happened a week earlier.

<img width="790" alt="Screenshot 2022-08-25 at 11 42 43" src="https://user-images.githubusercontent.com/644420/186632216-a42a0ac3-7913-4801-b5dd-81269d5fddc8.png">

Jira issue: CRDB-18963

**Comment by renatolabs** [comment] 2022-08-25 14:48
Seems like we only see a drop on GCE. First drop happening on 2022-08-16. Bisecting... 🔍

**Comment by renatolabs** [comment] 2022-08-25 21:32
This is either non-deterministic, or it's already fixed on master. Notes so far:

* on `master` at the time I started the test (54bc65f212), I get "normal" qps (7037.65 mean, 58.51 stdev over 5 runs)
* on a Aug 18 commit (1be194d939), I do observe the regression (5667.12 mean, 123.64 stdev over 3 runs -- 2 runs failed because of #86299).

I'll pick this up again tomorrow depending on what we see on roachperf.

**Comment by srosenberg** [comment] 2023-03-09 04:10
I don't believe we ever identified the root cause. :( It's trending up, so that might be good news. Closing this out since the regression in question has lost its relevance.

<img width="771" alt="kv95" src="https://user-images.githubusercontent.com/1616764/223914600-1843d984-93f7-4980-b529-080add411975.png">

**Closed by srosenberg** 2023-03-09 04:10 UTC
Labels: C-performance, A-roachperf-investigation, T-testeng
