### ISSUE TITLE
storage: "checksum for AddSSTable ... does not match" crash after restarting from sudden termination 

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#24025] opened 2018-03-19 17:19 UTC
I started killing nodes with `kill -9` while they were restoring to test some job adoption code.

After a few cycles of this, one of my nodes started crashing by itself immediately after starting with the following log message:

```
180319 17:16:20.511232 139 storage/replica_proposal.go:332  [n4,s4,r2118/3:/Table/51/1/209{4/6/7…-6/5/2…}] checksum for AddSSTable at index term 6, index 17 does not match; at proposal time d8dd431d (3638379293), now 96311136 (2519798070)
goroutine 139 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc4204c0400, 0xc4204c0420, 0x3185600, 0x1b)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:935 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3a331c0, 0xc400000004, 0x3185663, 0x1b, 0x14c, 0xc42f042300, 0xb6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:811 +0x753
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2641780, 0xc424c03890, 0x4, 0x2, 0x23d6ffa, 0x68, 0xc431a80c20, 0x6, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:154 +0x2e5
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2641780, 0xc424c03890, 0x1, 0xc400000004, 0x23d6ffa, 0x68, 0xc431a80c20, 0x6, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:55 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2641780, 0xc424c03890, 0x23d6ffa, 0x68, 0xc431a80c20, 0x6, 0x6)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:149 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.addSSTablePreApply(0x2641780, 0xc424c03890, 0xc420246000, 0x2669680, 0xc420888d00, 0x2650f80, 0xc424c03b90, 0x6, 0x11, 0xc4451f8000, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go:332 +0x10fb
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc424c1a000, 0x2641780, 0xc424c03890, 0xc42536ce08, 0x8, 0x6, 0x11, 0x300000003, 0x1, 0x7, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4702 +0xf0f
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc424c1a000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3658 +0x12c8
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x2641780, 0xc42526fcb0, 0xc424c1a000, 0x2641780)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3814 +0x109
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc42068e000, 0x2641780, 0xc42526fcb0, 0xc431a74310, 0xc427037ed0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3155 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc42068e000, 0x2641780, 0xc424c16300, 0x846)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3802 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42002e510, 0x2641780, 0xc424c16300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2641780, 0xc424c16300)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc425339450, 0xc4201baf30, 0xc425339440)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
```

**Comment by dt** [comment] 2018-03-19 18:05
https://sentry.io/cockroach-labs/cockroachdb/issues/498294024/

**Comment by tschottdorf** [comment] 2018-04-16 23:43
Assuming this isn't just a disk corruption problem, this looks like we're writing down an SSTable for a log entry `(term,index)` (`(6,17)` in this crash) but then don't actually commit that entry. Instead, another log entry is proposed (at that position). The reason I suspect that is because at the level of the sideloaded storage we use a [PutIfNotExists](https://github.com/cockroachdb/cockroach/blob/96295ac25279f02474e67895a8f5b6e60c09dee0/pkg/storage/replica_sideload_disk.go#L71) operation and that invites that sort of bug. On the other hand, I'm not sure how a `(term,index)` pair would ever be reused for another entry.

@nvanbenschoten you're currently in that area of code, do you have any additional insights?

**Comment by nvanbenschoten** [comment] 2018-04-17 00:30
> On the other hand, I'm not sure how a `(term,index)` pair would ever be reused for another entry.

That's a good point. A Raft leader should ever re-use the same index within the same term, although perhaps we're dealing with a case where the old term was not persisted by the time the node crashed and it was able to come back up and campaign again for the same term. This would certainly not be a possibility if an entry had been committed at that term as that would imply that the term had been persisted in the `HardState`, but maybe the crash happened immediately after the sideloaded storage was populated.

Regardless, I completely agree that `PutIfNotExists` should be changed to `Put` and that it should overwrite any existing files. What was the reason for the other behavior? Did we just want to avoid duplicate work in cases where the same file was being written twice?

**Comment by tschottdorf** [comment] 2018-04-17 01:00
We put the file down before we commit the batch that persists the log, which must somehow be opening up this race. I think this could happen as follows:

1. node 1 has lease and raft leader for range X
1. AddSSTable gets proposed, SSTable is sideloaded, but process is killed before even appending it to the log locally.
1. node restarts quickly enough to retain raft leadership, but it loses its lease (or rather, isn't allowed to use it when restarting, so it goes elsewhere).
1. another AddSSTable is proposed on the new leaseholder, but since the Raft leader hasn't changed, that's where it's forwarded. It is now sideloaded at the same (index,term) tuple, but does not overwrite the file.
1. boom

> Regardless, I completely agree that PutIfNotExists should be changed to Put and that it should overwrite any existing files. What was the reason for the other behavior? Did we just want to avoid duplicate work in cases where the same file was being written twice?

I tried to page that back in earlier and did not manage to find a reason for the current behavior. I think it was just a bad idea on my end.

**Comment by nvanbenschoten** [comment] 2018-04-17 15:52
That requires some careful timing, but it all seems plausible to me. @dt is this reproducible?

**Comment by bdarnell** [comment] 2018-04-17 16:49
>  A Raft leader should ever re-use the same index within the same term, although perhaps we're dealing with a case where the old term was not persisted by the time the node crashed and it was able to come back up and campaign again for the same term

This shouldn't happen. Nodes always persist the term when casting votes, and increment their term when starting a campaign, so it's not possible to ever have two leaders of the same term (even if the log entries the first leader proposed were never committed), or for a previous leader to resume its old term after a restart.

**Comment by nvanbenschoten** [comment] 2018-04-17 19:42
> This shouldn't happen. Nodes always persist the term when casting votes, and increment their term when starting a campaign, so it's not possible to ever have two leaders of the same term

Are you saying that the series of events hypothesized in https://github.com/cockroachdb/cockroach/issues/24025#issuecomment-381796110 can't happen, or just that what I said above can't happen? 

I think the key to the latter hypothesis is that the SSTable was sideloaded before the term was persisted. The assumtion that relies on is that etcd/raft can propose new entries (at a new term) in the same `raft.Ready` that it is voting for that term. Do you know off the top of your head if this actually happens in practice? I can't image that it does.

**Comment by nvanbenschoten** [comment] 2018-04-17 19:44
Just edited the previous message. I had gotten that wrong.

**Comment by bdarnell** [comment] 2018-04-17 19:49
In a multi-node cluster, a new leader always persists its new term when it transitions to StateCandidate, and it cannot propose any new log entries until it has transitioned to StateLeader (which is always a separate operation). So I don't see any way this could happen today unless it happens while the range is in a single-node state.

(Note that in abstract raft, it is permissible for the node to send out its MsgVotes, get responses, and start acting as leader without ever recording its own self-vote. That could lead to the scenario you describe. But that's not currently possible in etcd/raft).

**Comment by tschottdorf** [comment] 2018-04-17 20:26
Ok, much simpler theory: we write the SSTable in chunks. If we crash during that operation, we'll still get the log index, but we will never complete the SSTable and the checksum fails.

This seems a lot more plausible, and the fix is the same -- always write the file.

**Comment by dt** [comment] 2018-04-17 20:33
w.r.t reproduction -- i'm not sure if it still does. I was running a `RESTORE` of tpcc probably (I think I was doing `/bin/workload fixtures load tpcc --warehouses=1000` or similar) and then running `kill -9` on one of my nodes four nodes while trying to catch a different bug that had to do with the progress tracking. That's about all I recall though, sorry!

**Comment by nvanbenschoten** [comment] 2018-04-17 20:33
I was just thinking about how difficult this will be to correctly time in a reproduction and came to the exact same conclusion! I'm going to try to test this out now. Thanks for the hypotheses 😃

**Comment by bdarnell** [comment] 2018-04-17 20:38
> This seems a lot more plausible, and the fix is the same -- always write the file.

Yeah, that seems likely. We could also do the write-to-temporary-and-rename dance to avoid ever writing the bad file, but then we'd have to make sure we cleaned up too.

**Comment by nvanbenschoten** [comment] 2018-04-17 22:06
@dt I was just able to reproduce this fairly easily after setting `kv.bulk_sst.sync_size` to `16kb`. Checking now if the proposed fix works.

**Closed** 2018-04-18 02:59 UTC
