### ISSUE TITLE
sql: Grant/Revoke all on db is slow

### ISSUE THREAD

**Issue by e-mbrown** [cockroachdb/cockroach#96227] opened 2023-01-30 20:22 UTC
In a multiregion cluster `GRANT ALL ON * TO USER` and `REVOKE ALL ON * FROM USER` gets progressively slower as more tables and users are created.

**To Reproduce**
Using a v22.2.2 roachprod cluster with 9 nodes and 3 regions :

#ofUsers: 5
#ofTables: 20
```
root@localhost:26257/defaultdb> GRANT ALL ON * TO user1;  
Time: 15.173s total (execution 15.172s / network 0.000s)

root@localhost:26257/defaultdb>  REVOKE ALL ON * FROM t11;
Time: 14.562s total (execution 14.562s / network 0.000s)

```

#ofUsers: 10
#ofTables: 40
```
root@localhost:26257/defaultdb> GRANT ALL ON * TO user1;
Time: 26.982s total (execution 26.982s / network 0.000s)

root@localhost:26257/defaultdb> REVOKE ALL ON * FROM user1;
Time: 33.745s total (execution 33.745s / network 0.000s)
```

#ofUsers: 20
#ofTables: 100
```
root@localhost:26257/defaultdb> GRANT ALL ON * TO user1;
Time: 35.276s total (execution 35.275s / network 0.000s)

root@localhost:26257/defaultdb> REVOKE ALL ON * FROM user1;
Time: 51.862s total (execution 51.861s / network 0.000s)

```

Jira issue: CRDB-24016

gz#15749

gz#19375

Epic CRDB-24134

**Comment by rafiss** [comment] 2023-01-31 21:45
This is essentially expected. With more tables, the GRANT and REVOKE statements have more work to do. And in a multiregion cluster, this takes longer. The use case of using `*` seems like it could be for testing. These settings can be used for tests to improve performance: https://www.cockroachlabs.com/docs/stable/local-testing.html#use-a-local-single-node-cluster-with-in-memory-storage

**Comment by oliverisaac** [comment] 2023-01-31 21:49
If the process could be parallelized across databases that would help a lot. An individual grant might take a while, but two grants against two databases would only take as long as the longer grant instead of compounding the time.

**Comment by theodore-hyman** [comment] 2023-02-09 20:47
@rafiss This was opened in relation to a customer performance concern around this functionality in testing in multi region. If the testing has to be done in a multi-region context, is there any other approach we can advise here? Or are you saying, there is no easy fix for this, its expected behavior (unless the process is parallelized across databases as @oliverisaac mentions). 

Maybe as a low-hanging fruit would be to tell them to do the testing on a multi-region cluster with less tables/databases? 

Just seeing if there is any more insight you can provide and confirming my understanding, thank you.

**Comment by rafiss** [comment] 2023-03-30 20:04
I don't think there's an easy fix. One issue with the "parallelizing" idea is that this would probably mean making GRANT non-transactional. (that is, each task that is parallelized would use a different transaction.) This also might not work as well as desired, since these transactions woul be contending with each other since they operate on the same data, so some of them would be stuck waiting for others to complete.

**Comment by daniel-crlabs** [comment] 2023-11-16 19:49
@annrpom as the on call ( and @rafiss since you have been involved in this ticket in the past), this issue has come up again with a customer running on `23.1.11`. Are there any plans to improve this behavior or any work around suggested? They are running 15 nodes multi-region cluster across europe, asia and north america. 

Customer stated the following:

>On 11/13 we granted select on 3 tables to a user. Each grant took 30-45 seconds. We recently upgraded from `22.2` to `23.1.11`. When running those grants in `22.2`, each processes in about 3 seconds.

>Today we tried to grant select on Db.* to a user, which has started to hang indefinitely, and eventually completed after `30 seconds`.

**Comment by annrpom** [comment] 2023-11-16 21:07
Hey @daniel-crlabs, one suggestion we can make is for the customer to perform those grants in a single transaction

**Comment by daniel-crlabs** [comment] 2023-11-16 21:45
Thank you, I'll have them try this.

**Comment by rafiss** [comment] 2024-01-16 19:07
Closing in favor of https://github.com/cockroachdb/cockroach/issues/117643, which covers the same issue and has some ideas on how we can improve this.

**Closed by rafiss** 2024-01-16 19:07 UTC
Labels: C-bug, T-sql-foundations
