### ISSUE TITLE
sql: KV encoding internal error (assertion failed) during index creation concurrent with upsert

### ISSUE THREAD

**Issue by QuYongjie** [cockroachdb/cockroach#34286] opened 2019-01-28 10:31 UTC
When I created the index, I had a problem inserting data at the same time.
But when the index is created, the data insertion is no problem.
version：2.1.4

error：

```
psycopg2.InternalError: value type is not BYTES: UNKNOWN
```

Executing index:  
```
create INDEX zyb_report_check_record_wide_idx11 on zyb_report.check_record_wide_v2(sale_corp_code ASC, c_check_time ASC, check_time ASC) STORING (corp_name, sale_corp_name, goods_name, close_price, quantity, c_check_num)
```

Executing sql: 
```
INSERT INTO zyb_report.check_record_wide_v2 (id, corp_code, corp_name, goods_name, close_price, quantity, status, pay_method, is_vm, sale_code, sale_corp_code, sale_corp_name, check_time, pay_status, create_by, create_time, order_detail_id, c_check_time, c_check_num, c_corp_code, c_sale_corp_code, order_detail_modify_time, corp_modify_time, mold_goods_code_modify_time, check_record_modify_time)
VALUES
  (121587986, 'sdzfxszsyfx', '苏州苏园旅游发展有限公司（自助机）-分销', '全价成人票【淡季】', 60.000000, 4, 'valid', 'vm', 'F', '11', 'sdzgyhqs', '苏州市虎丘山风景名胜区管理处', TIMESTAMP '2019-01-27 09:16:13', 'payed', 'szsyfx', TIMESTAMP '2019-01-27 09:14:49', 165088011, TIMESTAMP '2019-01-27 09:16:11', 3, 'sdzfxszsyfx', 'sdzgyhqs', TIMESTAMP '2019-01-27 09:16:32', TIMESTAMP '2019-01-09 11:37:47', TIMESTAMP '2017-12-12 10:57:13', TIMESTAMP '2019-01-27 09:16:02'),
  (121587987, 'sdzfxxytcfx', '襄阳唐城旅游发展有限公司-分销', '大唐盛宴（午餐）', 0.010000, 1, 'valid', 'vm', 'F', '060', 'sdzgytclygy', '襄阳唐城旅游发展有限公司-供应', TIMESTAMP '2019-01-27 09:16:01', 'payed', 'xytcfx', TIMESTAMP '2019-01-27 09:15:01', 165088053, TIMESTAMP '2019-01-27 09:16:01', 1, 'sdzfxxytcfx', 'sdzgytclygy', TIMESTAMP '2019-01-27 09:16:02', TIMESTAMP '2019-01-27 14:34:12', TIMESTAMP '2018-09-03 13:27:16', TIMESTAMP '2019-01-27 09:16:02'),
  (121587990, 'njtnfx', '南京途牛国际旅行社有限公司', '18三小时畅滑套票（周末）', 175.000000, 5, 'valid', 'vm', 'F', '04', 'sdzgyhzdms', '杭州大明山风景旅游有限公司', TIMESTAMP '2019-01-27 09:15:34', 'payed', 'njtnfx', TIMESTAMP '2019-01-25 14:02:46', 164759403, TIMESTAMP '2019-01-27 09:15:34', 5, 'njtnfx', 'sdzgyhzdms', TIMESTAMP '2019-01-27 09:16:03', TIMESTAMP '2018-12-17 15:23:47', TIMESTAMP '2017-03-02 09:19:10', TIMESTAMP '2019-01-27 09:16:03'),
  (121588168, 'sdzfxbjkxfx', '北京酷讯科技有限公司（美团）', '美团【旺季】槟榔谷门票+观光车票', 100.000000, 3, 'valid', 'vm', 'F', '25', 'sdzgyblg', '海南槟榔谷黎苗文化旅游区', TIMESTAMP '2019-01-27 09:16:56', 'payed', 'bjkxfx', TIMESTAMP '2019-01-27 07:50:14', 165076663, TIMESTAMP '2019-01-27 09:16:56', 3, 'sdzfxbjkxfx', 'sdzgyblg', TIMESTAMP '2019-01-27 09:16:57', TIMESTAMP '2019-01-23 17:15:00', TIMESTAMP '2017-06-02 10:06:58', TIMESTAMP '2019-01-27 09:16:57')
ON CONFLICT (id)
  DO UPDATE SET id              = excluded.id, corp_code = excluded.corp_code, corp_name = excluded.corp_name,
    goods_name                  = excluded.goods_name, close_price = excluded.close_price, quantity = excluded.quantity,
    status                      = excluded.status, pay_method = excluded.pay_method, is_vm = excluded.is_vm,
    sale_code                   = excluded.sale_code, sale_corp_code = excluded.sale_corp_code,
    sale_corp_name              = excluded.sale_corp_name, check_time = excluded.check_time,
    pay_status                  = excluded.pay_status, create_by = excluded.create_by,
    create_time                 = excluded.create_time, order_detail_id = excluded.order_detail_id,
    c_check_time                = excluded.c_check_time, c_check_num = excluded.c_check_num,
    c_corp_code                 = excluded.c_corp_code, c_sale_corp_code = excluded.c_sale_corp_code,
    order_detail_modify_time    = excluded.order_detail_modify_time, corp_modify_time = excluded.corp_modify_time,
    mold_goods_code_modify_time = excluded.mold_goods_code_modify_time,
    check_record_modify_time    = excluded.check_record_modify_time
    WHERE excluded.order_detail_modify_time > zyb_report.check_record_wide_v2.order_detail_modify_time OR
          excluded.corp_modify_time > zyb_report.check_record_wide_v2.corp_modify_time OR
          excluded.mold_goods_code_modify_time > zyb_report.check_record_wide_v2.mold_goods_code_modify_time OR
          excluded.check_record_modify_time > zyb_report.check_record_wide_v2.check_record_modify_time
RETURNING (id, corp_code, corp_name, goods_name, close_price, quantity, status, pay_method, is_vm, sale_code, sale_corp_code, sale_corp_name, check_time, pay_status, create_by, create_time, order_detail_id, c_check_time, c_check_num, c_corp_code, c_sale_corp_code, order_detail_modify_time, corp_modify_time, mold_goods_code_modify_time, check_record_modify_time)
```

Schema for the table:
```
CREATE TABLE check_record_wide_v2 (
	id INT NOT NULL,
	corp_code STRING NULL,
	corp_name STRING NULL,
	goods_name STRING NULL,
	close_price FLOAT8 NULL,
	quantity INT NULL,
	status STRING NULL,
	pay_method STRING NULL,
	is_vm STRING NULL,
	sale_code STRING NULL,
	sale_corp_code STRING NULL,
	sale_corp_name STRING NULL,
	check_time TIMESTAMP NULL,
	pay_status STRING NULL,
	create_by STRING NULL,
	create_time TIMESTAMP NULL,
	order_detail_id INT NULL,
	c_check_time TIMESTAMP NULL,
	c_check_num INT NULL,
	c_corp_code STRING NULL,
	c_sale_corp_code STRING NULL,
	order_detail_modify_time TIMESTAMP NULL,
	corp_modify_time TIMESTAMP NULL,
	mold_goods_code_modify_time TIMESTAMP NULL,
	check_record_modify_time TIMESTAMP NULL,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	INDEX zyb_report_check_record_wide_idx1 (sale_corp_code ASC, create_time ASC) STORING (corp_name, sale_corp_name, goods_name, close_price, quantity, c_check_num),
	INDEX zyb_report_check_record_wide_idx2 (corp_code ASC, create_time ASC) STORING (sale_corp_name, corp_name, goods_name, close_price, quantity, c_check_num),
	INDEX zyb_report_check_record_wide_idx3 (c_check_time ASC),
	INDEX zyb_report_check_record_wide_idx4 (corp_code ASC, c_check_time ASC, create_time ASC) STORING (sale_corp_name, corp_name, goods_name, close_price, quantity, c_check_num),
	INDEX zyb_report_check_record_wide_idx5 (corp_code ASC, check_time ASC, create_time ASC) STORING (sale_corp_name, corp_name, goods_name, close_price, quantity, c_check_num),
	INDEX zyb_report_check_record_wide_idx7 (sale_corp_code ASC, check_time ASC, create_time ASC) STORING (corp_name, sale_corp_name, goods_name, close_price, quantity, c_check_num),
	INDEX zyb_report_check_record_wide_idx6 (sale_corp_code ASC, c_check_time ASC, create_time ASC) STORING (corp_name, sale_corp_name, goods_name, close_price, quantity, c_check_num),
	FAMILY "primary" (id, corp_code, corp_name, goods_name, close_price, quantity, status, pay_method, is_vm, sale_code, sale_corp_code, sale_corp_name, check_time, pay_status, create_by, create_time, order_detail_id, c_check_time, c_check_num, c_corp_code, c_sale_corp_code, order_detail_modify_time, corp_modify_time, mold_goods_code_modify_time, check_record_modify_time)
)
```

**Comment by knz** [comment] 2019-02-04 10:16
@vivekmenezes @lucy-zhang have you encountered anything similar recently or in the past? I think I recall a similar issue but I can't find it.

**Comment by vivekmenezes** [comment] 2019-02-04 14:45
https://github.com/cockroachdb/cockroach/issues/33260 is the related issue. Is this one reproducible?

**Comment by knz** [comment] 2019-02-04 14:54
@QuYongjie once again thank you for submitting this issue. Are you able to reproduce the error on demand? Do you have a test program we can use to further investigate? Thank you

**Comment by QuYongjie** [comment] 2019-02-16 01:45
> [＃33260](https://github.com/cockroachdb/cockroach/issues/33260)是相关问题。这个可重复吗？

This is repeatable. But my table has 100 million pieces of data. It should be triggered when the amount of data is large.

**Comment by dt** [comment] 2019-02-22 18:55
This is certainly the same as #33260 -- during the index creation, we don't handle changes to the values in the `STORING` columns. Closing as a duplicate of #33260 where we're discussing the details and how to fix it.

**Closed by dt** 2019-02-22 18:55 UTC
Labels: A-schema-changes, C-investigation, O-community, S-3-erroneous-edge-case
