### ISSUE TITLE
networking: better visibility of DNS/advertised-host issues.

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#12107] opened 2016-12-06 20:14 UTC
Last night a handful of `delta` nodes OOM'ed:

<img width="858" alt="screen shot 2016-12-06 at 2 04 34 pm" src="https://cloud.githubusercontent.com/assets/6201335/20939487/07bdda5e-bbbd-11e6-9907-e0a73923ac51.png">

The periodic memory profiles showed a huge spike in memory from the Raft log entry slices:

```
         .          .     93:	// stopping once we have enough.
   10.77GB    10.77GB     94:	ents := make([]raftpb.Entry, 0, hi-lo)
         .          .     95:	size := uint64(0)
```

`delta` was restarted yesterday (12/5) at 21:43 and the memory spike occurred on 12/6 at 03:45. 

The ranges graph showed a significant number of under-replicated ranges:

<img width="934" alt="screen shot 2016-12-06 at 1 59 01 pm" src="https://cloud.githubusercontent.com/assets/6201335/20940541/288cb882-bbc1-11e6-8e80-c12091a43c7f.png">

The replica leaseholders graph shows one node has no leases, which is curious:

<img width="932" alt="screen shot 2016-12-06 at 2 00 36 pm" src="https://cloud.githubusercontent.com/assets/6201335/20940608/5ce07bf0-bbc1-11e6-832c-a173cd497473.png">

Despite the under-replicated ranges, the replicate queue wasn't doing anything significant:

<img width="932" alt="screen shot 2016-12-06 at 2 00 59 pm" src="https://cloud.githubusercontent.com/assets/6201335/20940632/7a8b2934-bbc1-11e6-92a1-2c601997b4b9.png">

Looking at the logs from the node with 0 leases showed communication issues:

```
I161205 21:48:07.700832 182 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup cockroach-delta-01 on [::1]:53: read udp [::1]:49702->[::1]:53: read: connection refused"; Reconnecting to {"cockroach-delta-01:26257" <nil>}
```

Port 53 is the DNS port. So the client was trying to connect to `cockroach-delta-01` and failing to resolve that hostname to an IP address. The node with the communication difficulties, `cockroach-delta-04`, experienced an root-disk-full situation. We have previously seen that a full root disk could lead to an empty `/etc/resolv.conf`. I hypothesize that the empty (or non-existent) `/etc/resolv.conf` led to Go using talking to localhost for DNS.

Interestingly, `delta-04` was able to talk via gossip to other nodes because gossip is configured (via the `--join` flag) to use IP addresses. This explain why the replicate queue was not fixing the under-replicated nodes: the replicate queue recognizes dead / unavailable nodes by a gossip-based signal. But gossip was ok for `delta-04` so the replicate queue thought nothing had to be done. The under-replicated range metric is powered by node liveness and the Raft progress of the replicas.

At 03:45, `delta-04` reported the last of the communication problems:

```
I161206 03:45:05.268431 751 vendor/google.golang.org/grpc/clientconn.go:667  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup cockroach-delta-07 on [::1]:53: read udp [::1]:49088->[::1]:53: read: connection refused"; Reconnecting to {"cockroach-delta-07:26257" <nil>}
```

Shortly after that the OOM occurs. Logs show a number of snapshots generated at that time. The Raft data shows that the associated ranges had never had their Raft logs truncated. That is, the truncated state index is 10 which is the initial index position. The un-truncated Raft logs had 1000s of entries. While `storage.entries` limits the number of entries it will return based on the `maxBytes` parameter, the code was allocating a slice for the full range of Raft log entries. (See #12100 which fixes the `storage.entries` behavior).

In person we discussed avoiding using DNS for intra-node communication, but that would likely run into problems due to our use of certs. The other action item is #12101 which is to make replicate queue use the same signal (node liveness) as the under-replicated range metric.

**Comment by tamird** [comment] 2016-12-06 22:18
@petermattis disable `block_writer` to allow delta to recover, and the event is largely over. Here's the relevant time slice, starting from the deploy which included #12100: https://monitoring.gce.cockroachdb.com/dashboard/db/cockroach-replicas?from=1481055277214&to=1481062260000&var-cluster=delta&var-node=All&var-rate_interval=1m.

<img width="953" alt="screen shot 2016-12-06 at 17 13 24" src="https://cloud.githubusercontent.com/assets/1535036/20946179/c76d0496-bbd7-11e6-98e8-0240b2120d31.png">

<img width="953" alt="screen shot 2016-12-06 at 17 13 50" src="https://cloud.githubusercontent.com/assets/1535036/20946184/cb6b7082-bbd7-11e6-8f2d-493c044a1015.png">

Note the oscillation in the unavailable replicas graph - the end of that oscillation signals the shutting down of `block_writer`. I don't know what to make of that oscillation.

Runtime metrics were uninteresting during this time.

**Comment by bdarnell** [comment] 2016-12-07 13:20
> In person we discussed avoiding using DNS for intra-node communication, but that would likely run into problems due to our use of certs.

Gossip uses certs in the same way; how does it get away with using IP addresses? I think we should be able to resolve any issues that may arise from using IP addresses instead of hostnames. 

It would be good in most cases to advertise an IP instead of a hostname, but the problem is that when a node has multiple IPs its not always easy to decide which one to advertise, while the machine will always have a distinguished default hostname.

**Comment by mberhault** [comment] 2016-12-07 13:23
We put all the addresses/names we know of in the certs.
For example, delta's first node has the following:
```
            X509v3 Subject Alternative Name:
                DNS:cockroach-delta-01, DNS:cockroach-delta-01.c.cockroach-shared.internal, DNS:localhost, DNS:delta.gce.cockroachdb.com, IP Address:127.0.0.1, IP Address:104.196.191.196
```

**Comment by petermattis** [comment] 2016-12-07 15:30
Oh yeah, good point about the IP addresses being in the certs. Can we resolve the hostname and advertise the IP address? At least on GCE this seems like it would give the external IP address via `/etc/hosts`.

**Comment by tamird** [comment] 2016-12-07 15:40
Don't you think /etc/hosts will have the same full-disk problem as
/etc/resolv.conf?

**Comment by a-robinson** [comment] 2016-12-07 15:44
Are you aware of any automated processes that write to /etc/hosts? I don't have the largest sample size in the world, but I haven't ever seen it have disk-related problems.

**Comment by tamird** [comment] 2016-12-07 15:45
No, just speculating.

**Comment by petermattis** [comment] 2016-12-07 15:46
If we can't resolve the hostname of the local node, we shouldn't let the process start.

**Comment by bdarnell** [comment] 2016-12-08 08:16
Some systems (notably [debian](http://serverfault.com/questions/363095/why-does-my-hostname-appear-with-the-address-127-0-1-1-rather-than-127-0-0-1-in)) add the default hostname to `/etc/hosts` with a loopback IP, so resolving our own hostname and advertising the result would not work in this case. This would be easy to special-case (if our hostname resolves to anything in `127.0.0.0/8`, advertise the hostname instead), although I'm slightly worried about accumulating hacks and heuristics here.

**Comment by dianasaur323** [comment] 2017-04-06 16:11
assigning @mberhault. Feel free to re-assign.

**Comment by mberhault** [comment] 2017-04-18 15:23
I'm not sure what there is to do here.

Which host to advertise depends on the networking setup (VPC vs open network) and DNS setup (eg: local VM hostnames are resolvable within the VPC in GCE/AWS/Azure, but not on Digital Ocean).

**Comment by bdarnell** [comment] 2017-04-18 15:35
I don't think there's anything to do here for 1.0. Later, we might want to add some heuristics to better diagnose issues like this (e.g. resolving our own hostname to see if DNS is wired up correctly).

**Comment by mberhault** [comment] 2017-04-18 15:52
Ok, renaming for now.

**Closed** 2017-06-19 20:14 UTC
