### ISSUE TITLE
NULL loaded on NOT NULL using load csv

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#18076] opened 2017-08-31 15:41 UTC
separated this issue from incorrect size reporting that was closed https://github.com/cockroachdb/cockroach/issues/17355#issuecomment-326130454

Will test again when a new alpha is available
[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/1267650/logs.tar.gz)
 as alpha 0817 regressed and cannot load the files

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent

$ cockroach version
Build Tag:    v1.1-alpha.20170810
Build Time:   2017/08/10 15:13:13
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  c3fca980b5a31384599aba0091cd6a0200e12797
Build Type:   release

2. Please describe the issue you observed:

- What did you do?

  ALTER TABLE lineitem ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');

- What did you expect to see?

- What did you see instead?

 ALTER TABLE lineitem ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: dial tcp [::1]:26257: getsockopt: connection refused
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp [::1]:26257: getsockopt: connection refused

**Comment by robert-s-lee** [comment] 2017-08-31 16:18
The same behavior on 
Build Tag:    391d19f
Build Time:   2017/08/31 16:02:30

root@:26257/tpch>  ALTER TABLE nation ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
ALTER TABLE

Time: 102.738022ms

root@:26257/tpch>  ALTER TABLE lineitem ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: dial tcp [::1]:26257: getsockopt: connection refused
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp [::1]:26257: getsockopt: connection refused
[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/1267777/logs.tar.gz)

rsleembpro:dbgen.osx rslee$ cockroach version
Build Tag:    391d19f
Build Time:   2017/08/31 16:02:30
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  391d19f65fc1583fba632c203c82985442322545
Build Type:   release

**Comment by robert-s-lee** [comment] 2017-08-31 16:22
This also causes metadata to be out of sync. column named interest is not there, but alter table sees conflict.

select * from lineitem limit 1;
+------------+-----------+-----------+--------------+------------+-----------------+------------+-------+--------------+--------------+---------------------------+---------------------------+---------------------------+-------------------+------------+-------------------------+
| l_orderkey | l_partkey | l_suppkey | l_linenumber | l_quantity | l_extendedprice | l_discount | l_tax | l_returnflag | l_linestatus |        l_shipdate         |       l_commitdate        |       l_receiptdate       |  l_shipinstruct   | l_shipmode |        l_comment        |
+------------+-----------+-----------+--------------+------------+-----------------+------------+-------+--------------+--------------+---------------------------+---------------------------+---------------------------+-------------------+------------+-------------------------+
|          1 |    155190 |      7706 |            1 |      17.00 |        21168.23 |       0.04 |  0.02 | N            | O            | 1996-03-13 00:00:00+00:00 | 1996-02-12 00:00:00+00:00 | 1996-03-22 00:00:00+00:00 | DELIVER IN PERSON | TRUCK      | egular courts above the |
+------------+-----------+-----------+--------------+------------+-----------------+------------+-------+--------------+--------------+---------------------------+---------------------------+---------------------------+-------------------+------------+-------------------------+
(1 row)

Time: 15.822089ms

root@:26257/tpch>
root@:26257/tpch>
root@:26257/tpch> ALTER TABLE lineitem ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
pq: duplicate column name: "interest"

show create table lineitem;
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|  Table   |                                                                                                                                                                 CreateTable                                                                                                                                                                  |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| lineitem | CREATE TABLE lineitem (␤                                                                                                                                                                                                                                                                                                                     |
|          |     l_orderkey INTEGER NOT NULL,␤                                                                                                                                                                                                                                                                                                            |
|          |     l_partkey INTEGER NOT NULL,␤                                                                                                                                                                                                                                                                                                             |
|          |     l_suppkey INTEGER NOT NULL,␤                                                                                                                                                                                                                                                                                                             |
|          |     l_linenumber INTEGER NOT NULL,␤                                                                                                                                                                                                                                                                                                          |
|          |     l_quantity DECIMAL(15,2) NOT NULL,␤                                                                                                                                                                                                                                                                                                      |
|          |     l_extendedprice DECIMAL(15,2) NOT NULL,␤                                                                                                                                                                                                                                                                                                 |
|          |     l_discount DECIMAL(15,2) NOT NULL,␤                                                                                                                                                                                                                                                                                                      |
|          |     l_tax DECIMAL(15,2) NOT NULL,␤                                                                                                                                                                                                                                                                                                           |
|          |     l_returnflag STRING(1) NOT NULL,␤                                                                                                                                                                                                                                                                                                        |
|          |     l_linestatus STRING(1) NOT NULL,␤                                                                                                                                                                                                                                                                                                        |
|          |     l_shipdate DATE NOT NULL,␤                                                                                                                                                                                                                                                                                                               |
|          |     l_commitdate DATE NOT NULL,␤                                                                                                                                                                                                                                                                                                             |
|          |     l_receiptdate DATE NOT NULL,␤                                                                                                                                                                                                                                                                                                            |
|          |     l_shipinstruct STRING(25) NOT NULL,␤                                                                                                                                                                                                                                                                                                     |
|          |     l_shipmode STRING(10) NOT NULL,␤                                                                                                                                                                                                                                                                                                         |
|          |     l_comment STRING(44) NOT NULL,␤                                                                                                                                                                                                                                                                                                          |
|          |     CONSTRAINT "primary" PRIMARY KEY (l_orderkey ASC, l_linenumber ASC),␤                                                                                                                                                                                                                                                                    |
|          |     INDEX l_ok (l_orderkey ASC),␤                                                                                                                                                                                                                                                                                                            |
|          |     INDEX l_pk (l_partkey ASC),␤                                                                                                                                                                                                                                                                                                             |
|          |     INDEX l_sk (l_suppkey ASC),␤                                                                                                                                                                                                                                                                                                             |
|          |     INDEX l_sd (l_shipdate ASC),␤                                                                                                                                                                                                                                                                                                            |
|          |     INDEX l_cd (l_commitdate ASC),␤                                                                                                                                                                                                                                                                                                          |
|          |     INDEX l_rd (l_receiptdate ASC),␤                                                                                                                                                                                                                                                                                                         |
|          |     INDEX l_pk_sk (l_partkey ASC, l_suppkey ASC),␤                                                                                                                                                                                                                                                                                           |
|          |     INDEX l_sk_pk (l_suppkey ASC, l_partkey ASC),␤                                                                                                                                                                                                                                                                                           |
|          |     FAMILY fam_0_l_returnflag_l_orderkey_l_partkey_l_suppkey_l_linenumber_l_tax_l_linestatus_l_shipdate_l_commitdate_l_receiptdate_l_shipinstruct_l_shipmode_l_comment (l_returnflag, l_orderkey, l_partkey, l_suppkey, l_linenumber, l_tax, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment),␤ |
|          |     FAMILY fam_1_l_quantity_l_extendedprice_l_discount (l_quantity, l_extendedprice, l_discount)␤                                                                                                                                                                                                                                            |
|          | )                                                                                                                                                                                                                                                                                                                                            |
+----------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by vivekmenezes** [comment] 2017-08-31 16:23
Can you include the original schema for tables nation and lineitem? Were both tables added through the csv import?

**Comment by vivekmenezes** [comment] 2017-08-31 16:32
This crash is happening because during the column backfill process for column interest the backfill finds a NULL value for one of the existing NON-NULL columns. I think SELECT * FROM lineitem should also crash the system.

**Comment by vivekmenezes** [comment] 2017-08-31 16:47
```
W170831 11:32:53.636484 280 storage/node_liveness.go:379  [n1,hb] slow heartbeat took 1.8s
panic: Non-nullable column with no value!

goroutine 14541 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc4203f2f10)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:588 +0x259
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc4203f2f10, 0x8841a08, 0xc42a7be800, 0xc420c06b00, 0x40133c8, 0x700, 0x56396a0, 0x1, 0xc420e02e00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:559 +0x13d
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRowDecoded(0xc4203f2f10, 0x8841a08, 0xc42a7be800, 0xc4657ac600, 0x1, 0x1, 0x1, 0x1, 0xc8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:569 +0x4c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk.func1(0x8841a08, 0xc42a7be800, 0xc46abf0b00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:209 +0x8b0
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn.func1(0x8841a08, 0xc42a7be800, 0xc46abf0b00, 0xc4211daf48, 0x54fb480, 0xc4211daf80)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:517 +0x43
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc46abf0b00, 0x8841a08, 0xc42a7be800, 0xc42a010101, 0xc4211daf90, 0xc421584400, 0x6b910d0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:749 +0xb6
github.com/cockroachdb/cockroach/pkg/internal/client.(*DB).Txn(0xc42041c840, 0x8841a08, 0xc42a7be800, 0xc452479180, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/internal/client/db.go:518 +0x142
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*columnBackfiller).runChunk(0xc4203f2c00, 0x88204f8, 0xc44e9c3f50, 0xc4214f3000, 0x1, 0x1, 0xc45bf00c90, 0x9, 0x10, 0xc4211711d0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/columnbackfiller.go:246 +0x164
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).mainLoop(0xc4203f2c00, 0x88204f8, 0xc44e9c3f50, 0x569446c, 0x8)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:137 +0x5b9
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*backfiller).Run(0xc4203f2c00, 0x88204f8, 0xc44e9c3f50, 0xc42d504430)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/backfiller.go:89 +0x224
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:366 +0x332

```

**Comment by vivekmenezes** [comment] 2017-08-31 16:58
BTW I'm seeing all columns being set to NOT NULL which is the default value, which makes me suspect that the table descriptor isn't being initialized properly. Where in the code on the CSV side are the descriptors initialized?

**Comment by mjibson** [comment] 2017-08-31 17:28
CSV descriptors are made at https://github.com/cockroachdb/cockroach/blob/221490e339256a8ce627d341d234f22ed430406e/pkg/ccl/sqlccl/csv.go#L215

**Comment by vivekmenezes** [comment] 2017-08-31 17:33
robert can you explain the method you are using to specify the schema for the CSV import

**Comment by vivekmenezes** [comment] 2017-08-31 18:18
robert I'd like to reproduce this issue. Is this simply a matter of loading the data via CSV and then running the ALTER TABLE command?

**Comment by vivekmenezes** [comment] 2017-08-31 18:24
BTW we checked to see if this is a CSV issue and it's unlikely to be the case because CSV calls sql.GenerateInsertRow() when inserting a row and that function checks the NON-NULL constraint on all columns.

**Comment by robert-s-lee** [comment] 2017-08-31 20:12
#17355 (comment) has the script to load the csv, then run the two alter commands.

attached is the dbgen for OSX to generate the data

unzip dbgen.osx.2.zip
cd dbgen.osx
./dbgen -b dists.dss
unzip Archive.2.zip into the dbgen.osx directory
./02-tpch-create-sst.sh
modify script to add license key
./03-tpch-load-sst.sh
cockroach sql --insecure <<EOF
use tpch;
ALTER TABLE nation ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
ALTER TABLE lineitem ADD COLUMN interest DECIMAL NOT NULL DEFAULT (DECIMAL '1.3');
EOF

[Archive 2.zip](https://github.com/cockroachdb/cockroach/files/1268347/Archive.2.zip)

[dbgen.osx 2.zip](https://github.com/cockroachdb/cockroach/files/1268338/dbgen.osx.2.zip)

**Comment by vivekmenezes** [comment] 2017-09-01 01:44
I'm seeing lines like 

```
32      85811   8320    5       44      79059.64        0.05    0.06    N       O       1995-08-28      1995-08-20      1995-09-14      DELIVER IN PERSON       AIR     symptotes nag according to the ironic depo
32      11615   4117    6       6       9159.66 0.04    0.03    N       O       1995-07-21      1995-09-23      1995-07-25      COLLECT COD     RAIL     gifts cajole carefully.
```

in datafile lineitem.tbl . See the second line is missing an entry for column l_tax which is a NON NULL column

I'm also seeing the load command being used with --nullif=\N which indicates that it will insert NULL values where needed.

So I'm pretty sure this bug is in load csv.

**Comment by vivekmenezes** [comment] 2017-09-01 01:46
And I think you should be able to see the panic with ```SELECT * FROM lineitem```

**Comment by mjibson** [comment] 2017-09-01 02:08
I'll look into it.

**Comment by mjibson** [comment] 2017-09-01 05:56
I wasn't able to generate this panic. I ran both those ALTER statements successfully. When I attempt to import null data I get:

> Error: pq: generate insert row: nodelocal:///tmp/csv: row 2: null value in column "s" violates not-null constraint

When I use `load csv` I get:

> Error: generate insert row: nodelocal:///home/mjibson/src/github.com/cockroachdb/cockroach/csv: row 2: null value in column "s" violates not-null constraint

So I haven't been able to repro this. If you use a binary from today, can you reproduce the panic?

Below was my test script.

```
./cockroach sql --insecure -e 'drop database if exists d cascade; create database d'
./cockroach sql --insecure -e 'drop database if exists csv cascade; create database csv'

cat <<EOF >/tmp/csv
1,a
2,N
EOF

cat <<EOF >table
create table t (i integer not null, s string not null)
EOF

./cockroach sql --insecure -d d -e "import table t (i integer not null, s string not null) csv data ('nodelocal:///tmp/csv') with temp = 'nodelocal:///tmp', nullif = 'N' ;"

echo TRY LOCAL

./cockroach load csv --table table --data csv --dest ~/load --nullif 'N'

./cockroach sql --insecure -d csv -e "restore csv.* from 'nodelocal:///home/mjibson/load';"
``

**Comment by robert-s-lee** [comment] 2017-09-01 12:54
https://drive.google.com/open?id=0B4ylwRfb_1ifWVQ0MFpCZWpYZk0 has the original TBL created by dbgen

https://drive.google.com/open?id=0B4ylwRfb_1ifRVZFRU5FaHpGMlU has the output from the load csv process

**Comment by robert-s-lee** [comment] 2017-09-01 13:09
@vivekmenezes is right.  It is not alter table that is causing the panic

Couple of question:

- [ ] how is NULL getting through the constraint check during the load?
- [ ] Should the database panic when encountering such state or do something else?

> select sum(l_extendedprice) from lineitem;
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: dial tcp [::1]:26257: getsockopt: connection refused
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp [::1]:26257: getsockopt: connection refused

> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001218 |
+----------+
(1 row)

**Comment by mjibson** [comment] 2017-09-01 17:49
I still can't recreate this panic. I downloaded the tpch.sf1.sst.zip, unziped it into /home/mjibson/load-done and ran:

```
root@:26257/> RESTORE csv.* FROM 'nodelocal:///home/mjibson/load-done/lineitem.sst';
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
|       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
| 275963656800174081 | succeeded |                  1 | 6001225 |      48009720 |              0 | 829069818 |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
(1 row)

Time: 2m5.991637235s

root@:26257/> use csv;
SET

Time: 1.083017ms

root@:26257/csv> select sum(l_extendedprice) from lineitem;
+----------------------+
| sum(l_extendedprice) |
+----------------------+
|      229577310901.20 |
+----------------------+
(1 row)

Time: 25.737042488s

root@:26257/csv> SELECT count() FROM lineitem;
pq: unknown signature: count()
root@:26257/csv> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001215 |
+----------+
(1 row)

Time: 19.581330789s
```

**Comment by vivekmenezes** [comment] 2017-09-01 18:04
@robert-s-lee I suspect you might not be regenerating the data (the regeneration is failing) and so you are loading up with old bad data. Wanna blow up your data files and retry. Thanks!

**Comment by robert-s-lee** [comment] 2017-09-01 18:24
I used the SST file this morning.  Was all of the SST directories loaded in order that was in the script with 3 CRDB nodes?

**Comment by robert-s-lee** [comment] 2017-09-05 17:15
Repro on Linux (Ubuntu) 

$ cockroach version
Build Tag:    7280eda
Build Time:   2017/09/05 15:22:14
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  7280edad905b0fd89c87f3ba0e71314c8af81a7d
Build Type:   release-gnu

[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/1278271/logs.tar.gz)

**Comment by mjibson** [comment] 2017-09-06 08:26
I was able to reproduce this. I made a 3 node cluster on my local machine and ran the restore, which first produced the error

```
pq: result is ambiguous (job lease expired)
```

But when run again worked:

```
root@:25001/csv> RESTORE csv.* FROM 'nodelocal:///home/mjibson/load-sst/lineitem.sst';
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
|       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
| 277251030137274369 | succeeded |                  1 | 6001225 |      48009720 |              0 | 829069818 |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
(1 row)

Time: 1m14.252081767s

root@:25001/csv> select sum(l_extendedprice) from lineitem;
driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the transaction status: dial tcp [::1]:25001: getsockopt: connection refused
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp [::1]:25001: getsockopt: connection refused
```

Node 1 printed:

```
panic: Non-nullable column "lineitem:l_extendedprice" with no value!

goroutine 12028 [running]:
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).finalizeRow(0xc424b467c8)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:588 +0x318
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*RowFetcher).NextRow(0xc424b467c8, 0x2995fa0, 0xc4211ee780, 0xc424674e00, 0x10, 0x10, 0x0, 0x0, 0x0)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/rowfetcher.go:559 +0x13f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*tableReader).Run(0xc424b46000, 0x2995fa0, 0xc4211ee780, 0xc42530bd98)
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/tablereader.go:206 +0x3ad
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
        /home/mjibson/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:394 +0x3d7
```

I restarted node 1 and reran the query and it succeeded:

```
root@:25001 ?> 
connection lost; opening new connection: all session settings will be lost
root@:25001/csv> 
root@:25001/csv> SELECT sum(l_extendedprice) FROM lineitem;
+----------------------+
| sum(l_extendedprice) |
+----------------------+
|      229577310901.20 |
+----------------------+
(1 row)

Time: 12.905347788s
```

When trying with the dataset from azure at backup-test/benchmarks/tpch/scalefactor-1, the following error happens (and upon retry, continues to happen; also remember that this error occurred once above, too):

```
root@:25001/> restore tpch.lineitem from 'nodelocal:///home/mjibson/az-tpch';
pq: result is ambiguous (job lease expired)
```

And the logs had

```
W170906 04:19:51.736931 167 sql/jobs/registry.go:329  job 277268164244996097: canceling due to liveness failure
W170906 04:19:51.737552 13597 storage/replica.go:2669  [n1,s1,r168/1:/Table/53/5/9{155/22…-613/22…}] context cancellation after 6.9s of attempting command AddSSTable [/Table/53/5/9155/221449809128980481/0,/Table/53/5/9613/221412575599132673/0/NULL)
W170906 04:19:51.737957 13596 ccl/storageccl/import.go:195  [n1,s1,r168/1:/Table/53/5/9{155/22…-613/22…}] addsstable [/Table/53/5/9155/221449809128980481/0,/Table/53/5/9613/221412575599132673/0/NULL) attempt 0 failed: result is ambiguous (context canceled)
E170906 04:19:51.738775 12901 sql/jobs/registry.go:315  job 277268164244996097: ignoring FinishedWith error: result is ambiguous (job lease expired)
```

Have not yet done testing with a real cluster, but wanted to document the current findings with a cluster on a single machine.

**Comment by mjibson** [comment] 2017-09-06 08:29
Maybe someone from core like @petermattis can shed some light on this.

**Comment by mjibson** [comment] 2017-09-06 18:25
More weirdness. When running a 3 node cluster on a laptop, doing a restore, then immediately running a count(*):

```
root@:26257/tpch> restore csv.* from 'nodelocal:///home/mjibson/load-sst/lineitem.sst' with into_db = 'tpch';
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
|       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
| 277384839621509121 | succeeded |                  1 | 6001225 |      48009720 |              0 | 829069818 |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
(1 row)

Time: 1m54.405295146s

root@:26257/tpch>  SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001219 |
+----------+
(1 row)

Time: 21.482950878s

root@:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001218 |
+----------+
(1 row)

Time: 16.584715032s

root@:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001221 |
+----------+
(1 row)

Time: 15.719184338s

root@:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001221 |
+----------+
(1 row)


Time: 13.744231253s

root@:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001221 |
+----------+
(1 row)

Time: 13.869512803s

root@:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001221 |
+----------+
(1 row)

Time: 14.47719723s

root@:26257/tpch> --- stopped node 1
root@:26257/tpch> 
error retrieving the transaction status: driver: bad connection
connection lost; opening new connection: all session settings will be lost
error retrieving the database name: dial tcp 127.0.0.1:26257: getsockopt: connection refused
root@:26257 ?> ^D
~/src/github.com/cockroachdb/cockroach (release-1.1)$ ./cockroach sql --insecure --port 26259 <-- connected to node 2
# Welcome to the cockroach SQL interface.
# All statements must be terminated by a semicolon.
# To exit: CTRL + D.
#
# Server version: CockroachDB CCL e302317 (linux amd64, built 2017/09/05 19:07:09, go1.9) (same version as client)
# Cluster ID: 8551c0f3-900f-4286-a35b-505bac30e2eb
# Organization: Cockroach Labs - Production Testing
#
# Enter \? for a brief introduction.
#
root@:26259/> use tpch1;
pq: database "tpch1" does not exist
root@:26259/> SET database = tpch;
SET

Time: 3.658697ms

root@:26259/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001217 |
+----------+
(1 row)

Time: 16.422377829s

root@:26259/tpch> -- stopped node 3, resumed node 1
root@:26259/tpch> SELECT count(*) FROM lineitem; <-- this hangs indefinitely
```

The expected number of rows is 6001215, which is *less* than the number returned by any of these operations, including the RESTORE.

From another terminal connected to node 1, trying to figure out why the latest select isn't returning:

```
root@:26257/> show queries;
+----------------------------------+---------+----------+----------------------------------+-------------------------------+-----------------+------------------+-------------+-----------+
|             query_id             | node_id | username |              start               |             query             | client_address  | application_name | distributed |   phase   |
+----------------------------------+---------+----------+----------------------------------+-------------------------------+-----------------+------------------+-------------+-----------+
| 14e1d89c246613750000000000000001 |       1 | root     | 2017-09-06 18:18:35.655584+00:00 | SHOW CLUSTER QUERIES          | 127.0.0.1:57740 | cockroach        | NULL        | preparing |
| 14e1d88e86917d160000000000000003 |       3 | root     | 2017-09-06 18:17:37.173071+00:00 | SELECT count(*) FROM lineitem | 127.0.0.1:45600 | cockroach        | true        | executing |
| NULL                             |       2 | NULL     | NULL                             | NULL                          | NULL            | NULL             | NULL        | NULL      |
+----------------------------------+---------+----------+----------------------------------+-------------------------------+-----------------+------------------+-------------+-----------+
(3 rows)

Time: 3.005782111s

root@:26257/> select now(), now() - start, * from [SHOW CLUSTER QUERIES];
+----------------------------------+-----------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
|              now()               |  now() - start  |             query_id             | node_id | username |              start               |                           query                            | client_address  | application_name | distributed |   phase   |
+----------------------------------+-----------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
| 2017-09-06 18:18:58.979997+00:00 | 2µs             | 14e1d8a192a43ebf0000000000000001 |       1 | root     | 2017-09-06 18:18:58.979995+00:00 | SELECT now(), now() - start, * FROM [SHOW CLUSTER QUERIES] | 127.0.0.1:57740 | cockroach        | NULL        | preparing |
| 2017-09-06 18:18:58.979997+00:00 | 1m21s806ms926µs | 14e1d88e86917d160000000000000003 |       3 | root     | 2017-09-06 18:17:37.173071+00:00 | SELECT count(*) FROM lineitem                              | 127.0.0.1:45600 | cockroach        | true        | executing |
| 2017-09-06 18:18:58.979997+00:00 | NULL            | NULL                             |       2 | NULL     | NULL                             | NULL                                                       | NULL            | NULL             | NULL        | NULL      |
+----------------------------------+-----------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
(3 rows)

Time: 3.002647251s
```

The final select finally finished:

```
root@:26259/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001220 |
+----------+
(1 row)

Time: 3m33.001129232s
```

So it took 3.5 minutes and still returned the wrong result. Show queries now shows:

```
root@:26257/> select now(), now() - start, * from [SHOW CLUSTER QUERIES];
+----------------------------------+---------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
|              now()               | now() - start |             query_id             | node_id | username |              start               |                           query                            | client_address  | application_name | distributed |   phase   |
+----------------------------------+---------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
| 2017-09-06 18:21:46.917545+00:00 | 2µs           | 14e1d8c8ac8000ed0000000000000001 |       1 | root     | 2017-09-06 18:21:46.917543+00:00 | SELECT now(), now() - start, * FROM [SHOW CLUSTER QUERIES] | 127.0.0.1:57740 | cockroach        | NULL        | preparing |
| 2017-09-06 18:21:46.917545+00:00 | NULL          | NULL                             |       2 | NULL     | NULL                             | NULL                                                       | NULL            | NULL             | NULL        | NULL      |
+----------------------------------+---------------+----------------------------------+---------+----------+----------------------------------+------------------------------------------------------------+-----------------+------------------+-------------+-----------+
(2 rows)

Time: 3.002884454s
```

The current list of bugs, which may or may not be intertwined or caused by a single root issue are:

1. RESTORE is reporting an incorrect number of rows.
1. SELECT count(*) changes its results over time and based on which nodes are running.
1. SELECT count(column) panics because of expected data that isn't present (this is probably caused by exactly the same thing as the previous bug.
1. NULL query showing up in SHOW QUERIES.
1. SELECT count(*) taking 10 times longer than expected (distsql problem? or just a problem because the data is corrupted from the previous bugs?).

**Comment by tschottdorf** [comment] 2017-09-06 18:30
When you time-travel the `SELECT COUNT(*)` at a fixed time, does it return a consistent result? I don't have a theory, just wondering.

**Comment by mjibson** [comment] 2017-09-06 18:33
I've already cleared the data to do more testing, but I would be really surprised if this is the case, because the RESTORE process never changes the MVCC timestamps, they are hard coded to all the same value during the backup creation step. But I will test that next time I have some data ready.

**Comment by mjibson** [comment] 2017-09-06 18:36
Thinking out loud: it is possible bug 5 is caused because when one of the nodes restarted, it chose to download a snapshot which took a few minutes (the original restore takes 2 minutes). I'm not sure why it would block the others from returning results, though, since that node almost certainly isn't a leader/lease holder, right?

**Comment by mjibson** [comment] 2017-09-06 19:31
I was able to reproduce this on lapis (a real 4 node cluster) with the SST files linked above:

```
root@localhost:26257/> restore csv.* from 'http://cockroach-lapis-0001:2015/' with into_db='tpch';
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
|       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
| 277399216838246401 | succeeded |                  1 | 6001225 |      48009720 |              0 | 829069818 |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
(1 row)

Time: 2m59.482272881s

root@localhost:26257/tpch> select count(*) from lineitem;
+----------+
| count(*) |
+----------+
|  6001220 |
+----------+
(1 row)

Time: 22.772303049s

root@localhost:26257/tpch> SELECT count(*) FROM lineitem;
+----------+
| count(*) |
+----------+
|  6001221 |
+----------+
(1 row)

Time: 17.887600837s
```

**Comment by mjibson** [comment] 2017-09-06 20:09
When I recreate the sst files from the table files in the gdrive link above:

```
~/cockroach load csv --table lineitem --dest tbl.sst --data lineitem.tbl --delimiter $'\t' --tempdir ./tmp
```

Then restore them:

```
root@localhost:26257/tpchtbl> RESTORE csv.* FROM 'http://cockroach-lapis-0001:2015/tbl.sst' with into_db='tpchtbl';
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
|       job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |   bytes   |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
| 277407041551335425 | succeeded |                  1 | 6001215 |      48009720 |              0 | 813361309 |
+--------------------+-----------+--------------------+---------+---------------+----------------+-----------+
(1 row)

Time: 2m22.111441686s

root@localhost:26257/tpchtbl> select count(*) from lineitem;
+----------+
| count(*) |
+----------+
|  6001215 |
+----------+
(1 row)

Time: 12.548772684s
```

Everything is correct. So I think we are just going to close this issue because the only way we've been able to reproduce this problem is with the SST files linked above, and those SST files were created with a pretty old version of `cockroach load csv`, and it has since improved and had bug fixes. The RESTORE paths assume that the imported data is correct (ignoring checks is one way we get it to be fast), and apparently the data above is not correct for an unknown reason.

**Comment by robert-s-lee** [comment] 2017-09-06 21:49
The Ubuntu SST were generated using the 0905 cut.  I can regenerate SST to confirm if there is question whether the SST were valid.  

Below does not generate null which is the original test case.  

~/cockroach load csv --table lineitem --dest tbl.sst --data lineitem.tbl --delimiter $'\t' --tempdir ./tmp

**Closed** 2017-09-18 19:24 UTC
