### ISSUE TITLE
cli/dump: `cockroach dump` produces unrestorable output with large records

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#36762] opened 2019-04-11 15:01 UTC
As described in the comments on #25524, `cockroach dump` can produce `INSERT` statements that are too long to be parsed either by CockroachDB's native SQL parser (when executing the statements in a dump file directly) or the parser used by `IMPORT PGDUMP`. `cockroach dump` should be updated to track the length of the statements it generates, ensuring that they can be parsed properly.

**Comment by mjibson** [comment] 2019-04-11 17:45
`max_row_size` from https://www.cockroachlabs.com/docs/v2.1/import.html#import-options can be used to handle longer lines.

**Comment by miretskiy** [comment] 2020-03-18 22:08
duplicate of #31676

**Closed** 2020-03-18 22:09 UTC
Labels: A-bulkio, A-cli, C-bug
