### ISSUE TITLE
Document Improvement: NOWAIT, SKIP LOCKED, etc

### ISSUE THREAD

**Issue by biglobe** [cockroachdb/cockroach#31542] opened 2018-10-17 10:24 UTC
Hi, I didnt find information (using search) on NOWAIT in CR docs. I just want to point out a suggestion to include these things just so that people know that the feature is supported?

**Comment by knz** [comment] 2018-10-19 16:38
Hi @biglobe 

Thanks for pointing out. Really your concern here is a duplicate of #6583.
In general we cannot make an exhaustive list of all features/ syntax clauses supported by PostgreSQL but not yet supported in CockroachDB because PostgreSQL changes regularly.

However in CockroachDB 2.1 the error message for NOWAIT, SKIP LOCKED etc will be specific and refer to that issue #6583.

Thank you again for watching out.

**Closed by knz** 2018-10-19 16:38 UTC
Labels: X-duplicate
