### ISSUE TITLE
sql: v1.1.3: crash in datum.SearchSorted

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#21053] opened 2017-12-26 20:03 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/423618901/

```
*log.safeError: stopper.go:179: <*errors.fundamental>
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 423, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/session.go", line 1381, in maybeRecover
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go", line 751, in Compare
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go", line 1940, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/datum.go", line 1941, in SearchSorted
...
(28 additional frame(s) were not displayed)

stopper.go:179: <*errors.fundamental>
```

**Comment by jordanlewis** [comment] 2017-12-26 20:50
Dupe of #20679.

**Closed by jordanlewis** 2017-12-26 20:50 UTC

**Comment by tschottdorf** [comment] 2017-12-26 20:56
Thanks @jordanlewis! I resolved the sentry crash manually, consider doing that next time as you close the issue (I don't think Sentry is smart enough to take that as a hint).
