### ISSUE TITLE
circleci: failed tests: TestTxnPutOutOfOrder

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6737] opened 2016-05-16 23:54 UTC
The following test appears to have failed:

[#17930](https://circleci.com/gh/cockroachdb/cockroach/17930):

```
I160516 23:54:34.667205 kv/dist_sender.go:986  application error: range 0: replica <nil> not leader; leader is <nil>
I160516 23:54:34.667505 kv/dist_sender.go:986  application error: range 0: replica <nil> not leader; leader is <nil>
I160516 23:54:34.667799 kv/dist_sender.go:986  application error: range 0: replica <nil> not leader; leader is <nil>
I160516 23:54:34.668153 kv/dist_sender.go:986  application error: range 0: replica <nil> not leader; leader is <nil>
I160516 23:54:34.668495 kv/dist_sender.go:986  application error: range 0: replica <nil> not leader; leader is <nil>
panic: test timed out after 5m0s

goroutine 13596 [running]:
panic(0x19ac240, 0xc8217c00c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x184
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x229e9e8, 0x2aa2c60, 0x10f, 0x10f, 0xc820127301)
	/usr/local/go/src/testing/testing.go:583 +0xb39
testing.(*M).Run(0xc820049f00, 0xc8202cdc90)
	/usr/local/go/src/testing/testing.go:515 +0x11e
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc820049f00)
	/go/src/github.com/cockroachdb/cockroach/storage/main_test.go:54 +0x230
main.main()
	github.com/cockroachdb/cockroach/storage/_test/_testmain.go:604 +0x20b

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 18 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2d7c6e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x76
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0xbd

goroutine 13611 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*idAllocator).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:123 +0xa94
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821545450)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13581 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*StorePool).start.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store_pool.go:225 +0x2a2
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc8217986c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13605 [runnable]:
fmt.(*fmt).padString(0xc8218f9bf8, 0x0, 0x0)
	/usr/local/go/src/fmt/format.go:130 +0x685
fmt.(*fmt).fmt_s(0xc8218f9bf8, 0x0, 0x0)
	/usr/local/go/src/fmt/format.go:322 +0x6f
fmt.(*pp).fmtString(0xc8218f9ba0, 0x0, 0x0, 0xc800000073)
	/usr/local/go/src/fmt/print.go:521 +0xef
fmt.(*pp).printArg(0xc8218f9ba0, 0x19ac240, 0xc8218fa6f0, 0x73, 0x0, 0x0)
	/usr/local/go/src/fmt/print.go:797 +0xeb6
fmt.(*pp).doPrintf(0xc8218f9ba0, 0x1d89110, 0x4, 0xc820d85038, 0x2, 0x2)
	/usr/local/go/src/fmt/print.go:1238 +0x2a48
--
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6b20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13586 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:1011 +0x454
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821799b00)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13566 [semacquire, 4 minutes]:
sync.runtime_Syncsemacquire(0xc82141a210)
	/usr/local/go/src/runtime/sema.go:241 +0x201
sync.(*Cond).Wait(0xc82141a200)
	/usr/local/go/src/sync/cond.go:63 +0xb3
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Quiesce(0xc8206ce000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:354 +0x297
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Stop(0xc8206ce000)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:300 +0x20d
github.com/cockroachdb/cockroach/storage_test.TestTxnPutOutOfOrder(0xc820fea000)
	/go/src/github.com/cockroachdb/cockroach/storage/client_replica_test.go:322 +0xf92
testing.tRunner(0xc820fea000, 0x2aa43d0)
	/usr/local/go/src/testing/testing.go:473 +0xdd
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0xae3

goroutine 13580 [select]:
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).startStats(0xc8217db2c0)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:203 +0x10d4
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).(github.com/cockroachdb/cockroach/kv.startStats)-fm()
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:188 +0x2e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc820852a10)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13609 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6ba0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13590 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*replicaScanner).waitAndProcess(0xc8207915e0, 0xececc53af, 0x2888d576, 0x2d7bb00, 0xc82141a140, 0xc8206ce000, 0xc821388b00, 0x60ae6c)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:161 +0x6a2
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1.1(0xc821388b00, 0xc8217634d0)
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:203 +0xf6
github.com/cockroachdb/cockroach/storage.(*storeRangeSet).Visit(0xc821c8c060, 0xc82176b440)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:231 +0x46b
github.com/cockroachdb/cockroach/storage.(*replicaScanner).scanLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/scanner.go:205 +0x33b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821799b60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13608 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6b80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13606 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6b40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13585 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:992 +0x454
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821799a60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13582 [select]:
github.com/cockroachdb/cockroach/storage.(*Store).processRaft.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:2059 +0xfca
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc820853e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13577 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open.func1(0xc82000a6c0)
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:164 +0x5b
created by github.com/cockroachdb/cockroach/storage/engine.(*RocksDB).Open
	/go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:165 +0xacf

goroutine 13604 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6ae0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13607 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821bd6b60)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13584 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*Store).Start.func4()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:921 +0x181
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821799a40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70

goroutine 13589 [select, 4 minutes]:
github.com/cockroachdb/cockroach/storage.(*baseQueue).processLoop.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:356 +0x408
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8206ce000, 0xc821799b40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.144s
=== RUN   TestBatchBasics
I160516 23:51:27.648620 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160516 23:51:27.651139 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.03s)
=== RUN   TestBatchRepr
I160516 23:51:27.677839 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160516 23:51:27.680643 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.01s)
=== RUN   TestBatchGet
I160516 23:51:27.688988 storage/engine/rocksdb.go:137  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-16 23:57
Duplicate of #6736

**Closed by bdarnell** 2016-05-16 23:57 UTC
Labels: Robot, test-failure
