### ISSUE TITLE
admission: support for SQL-only server

### ISSUE THREAD

**Issue by sumeerbhola** [cockroachdb/cockroach#79899] opened 2022-04-13 16:03 UTC
In a multi-tenant setting, we have support for admission control for the multi-tenant storage server. However, there is no support for admission control in the SQL-only server. The latter could be useful for reordering work within that tenant based on priority. The bottleneck resource here would be CPU, and there would 2 WorkQueues: SQLKVResponseWork, SQLSQLResponseWork. We have the code to construct these in `NewGrantCoordinatorSQL`, but the core logic is incomplete: `sqlNodeCPUOverloadIndicator` is not implemented. Therefore, `NewGrantCoordinatorSQL` is never called.

There is a technical challenge here which we will need to address: the lack of KV work means we don't have the slot estimation logic, which serves as an instantaneous indicator that CPU is saturated that then pushes back on higher-level work. We do still have the 1ms polling of the goroutine scheduler's runnable queue, but the 1ms lag may cause too much admission fluctuation. So experimentation is needed before finalizing a solution.

Jira issue: CRDB-15868
Epic: CRDB-13762

**Comment by vy-ton** [comment] 2022-04-13 16:33
Is this different from https://github.com/cockroachdb/cockroach/issues/79425?

**Comment by cucaroach** [comment] 2022-05-31 18:38
dupe of https://github.com/cockroachdb/cockroach/issues/79425

**Closed by cucaroach** 2022-05-31 18:38 UTC
Labels: C-enhancement, A-admission-control, O-sre, T-sql-queries
