### ISSUE TITLE
storage: benchmark low raft tick interval

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#1135] opened 2015-05-26 17:40 UTC
When set low (10ms in #1131), raft tick intervals can cause issues due to the amount of work being done.
We should benchmark this and attempt to resolve any performance issues.

**Comment by bdarnell** [comment] 2015-05-26 20:40
With #1133, the worst problems caused by a tick interval that is too small should be solved, but we should still test and make sure, so I'm leaving this bug open.

**Comment by bdarnell** [comment] 2016-08-19 18:38
I think we can close this: a tick interval of 10ms is pretty crazy; we're more likely to increase the tick interval than decrease it again.

**Closed by bdarnell** 2016-08-19 18:38 UTC
Labels: enhancement, helpwanted
