### ISSUE TITLE
circleci: failed tests: TestClusterRecovery 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7637] opened 2016-07-06 02:24 UTC
The following test appears to have failed:

[#19890](https://circleci.com/gh/cockroachdb/cockroach/19890):

```
I160706 02:20:31.075881 kv/dist_sender.go:982  application error: range 7 was not found
I160706 02:20:31.079581 kv/dist_sender.go:982  application error: range 7 was not found
I160706 02:20:31.089261 kv/dist_sender.go:982  application error: range 7 was not found
E160706 02:20:31.107793 storage/replica.go:1852  [node=2,store=2,range=6] error executing raft command: key range /Local/Range/"\xbb"/RangeDescriptor-/Min outside of bounds of range /Table/50-/Table/51
E160706 02:20:31.111842 raft/raft.go:925  [range 7] 2 state.commit 0 is out of range [10, 10]
panic: [range 7] 2 state.commit 0 is out of range [10, 10]

goroutine 275 [running]:
panic(0x1593460, 0xc82093af50)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/storage.(*raftLogger).Panicf(0xc82093ae90, 0x1b5f620, 0x2b, 0xc8207f14c0, 0x4, 0x4)
	/go/src/github.com/cockroachdb/cockroach/storage/raft.go:117 +0x1ba
github.com/coreos/etcd/raft.(*raft).loadState(0xc82005f2b0, 0x6, 0x1, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:925 +0x2a2
github.com/coreos/etcd/raft.newRaft(0xc820859890, 0x5b6aa4)
	/go/src/github.com/coreos/etcd/raft/raft.go:225 +0x8ff
github.com/coreos/etcd/raft.NewRawNode(0xc820859890, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/rawnode.go:76 +0xbf
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroupLocked(0xc8201f2f00, 0xc820859a08, 0x0, 0x0)
I160706 02:20:33.814423 acceptance/chaos_test.go:355  826 164.3/sec
I160706 02:20:33.917585 acceptance/cluster/localcluster.go:675  stopping
I160706 02:20:33.917819 acceptance/cluster/localcluster.go:573  event stream done, resetting...: net/http: request canceled
I160706 02:20:33.917862 acceptance/cluster/localcluster.go:596  events monitor exits
I160706 02:20:34.781794 acceptance/cluster/localcluster.go:718  node 1: stderr at /tmp/circle-artifacts.BotcTs2/acceptance/TestClusterRecovery/roach1/stderr.2016-07-06T02_20_34Z.log
--- FAIL: TestClusterRecovery (9.58s)
	localcluster.go:652: unexpected extra event &{1 die} (after [{2 die} {2 restart} {1 die} {1 restart}])
=== RUN   TestNodeRestart
I160706 02:20:35.678805 acceptance/cluster/localcluster.go:301  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160706 02:20:35.680743 acceptance/cluster/docker.go:109  ImagePull cockroachdb/builder:20160611-170214 already exists
I160706 02:20:36.309289 acceptance/cluster/localcluster.go:607  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.250996992
I160706 02:20:36.401976 acceptance/cluster/localcluster.go:558  events monitor starts
I160706 02:20:36.668722 acceptance/cluster/localcluster.go:507  *** started roach0 ***
  ui:        https://127.0.0.1:32795
  trace:     https://127.0.0.1:32795/debug/requests
--
E160706 02:23:44.621087 acceptance/cluster/localcluster.go:523  node=2 status=restart
I160706 02:23:56.602766 acceptance/cluster/localcluster.go:675  stopping
I160706 02:23:56.602938 acceptance/cluster/localcluster.go:573  event stream done, resetting...: net/http: request canceled
I160706 02:23:56.602973 acceptance/cluster/localcluster.go:596  events monitor exits
--- PASS: TestRaftUpdate (28.95s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-07-10 15:36
Duplicate of #7480.

**Closed by petermattis** 2016-07-10 15:36 UTC
Labels: Robot, test-failure
