### ISSUE TITLE
Expand backup nemesis and round trip tests

### ISSUE THREAD

**Issue by rhu713** [cockroachdb/cockroach#103071] opened 2023-05-10 20:53 UTC
Expand `TestTenantBackupNemeis` and `TestBackupRestoreRandomDataRoundtrips` to include test cases where keys can have large revision histories, and cases where the elastic CPU limiter is actively preempting backup related work.

Epic: [CRDB-27758](https://cockroachlabs.atlassian.net/browse/CRDB-27758)

Jira issue: CRDB-27821

Epic CRDB-31689

**Comment by msbutler** [comment] 2023-12-15 16:51
Closing as not planned and because the roundtrip roachtests add the coverage the issue is describing

**Closed by msbutler** 2023-12-15 16:51 UTC
Labels: C-enhancement, A-disaster-recovery, T-disaster-recovery
