### ISSUE TITLE
ui+storage: new docker cluster displays incorrect capacity in UI

### ISSUE THREAD

**Issue by Mountainerd** [cockroachdb/cockroach#18041] opened 2017-08-30 19:25 UTC
**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file for each node in your cluster. 

    **roach1**
    I170830 16:07:35.157989 1 util/log/clog.go:1013  [config] file created at: 2017/08/30 16:07:35
    I170830 16:07:35.157989 1 util/log/clog.go:1013  [config] running on machine: roach1
    I170830 16:07:35.157989 1 util/log/clog.go:1013  [config] binary: CockroachDB CCL v1.0.5 (linux amd64, built 2017/08/24 17:43:46, go1.8.3)
    I170830 16:07:35.157989 1 util/log/clog.go:1013  [config] arguments: [/cockroach/cockroach start --insecure]

    **roach2**
    I170830 16:07:44.364810 1 util/log/clog.go:1013  [config] file created at: 2017/08/30 16:07:44
    I170830 16:07:44.364810 1 util/log/clog.go:1013  [config] running on machine: roach2
    I170830 16:07:44.364810 1 util/log/clog.go:1013  [config] binary: CockroachDB CCL v1.0.5 (linux amd64, built 2017/08/24 17:43:46, go1.8.3)
    I170830 16:07:44.364810 1 util/log/clog.go:1013  [config] arguments: [/cockroach/cockroach start --insecure --join=roach1]

    **roach3**
    I170830 16:07:44.844018 1 util/log/clog.go:1013  [config] file created at: 2017/08/30 16:07:44
    I170830 16:07:44.844018 1 util/log/clog.go:1013  [config] running on machine: roach3
    I170830 16:07:44.844018 1 util/log/clog.go:1013  [config] binary: CockroachDB CCL v1.0.5 (linux amd64, built 2017/08/24 17:43:46, go1.8.3)
    I170830 16:07:44.844018 1 util/log/clog.go:1013  [config] arguments: [/cockroach/cockroach start --insecure --join=roach1]

2. Please describe the issue you observed:

- What did you do? 
--I followed the _Getting Started_ guide and setup a basic three-node cluster using Docker (Version 17.06.1-ce-mac24 (18950)) on my local host (mid 2015 Macbook Pro, OS X Sierra 10.12.6, 500GB SSD, 16GB memory)

- What did you expect to see? 
--Storage levels that matched what's actually available to it.

- What did you see instead? 
--A storage level greater than what's in my entire data center. 
<img width="306" alt="screen shot 2017-08-30 at 11 12 57 am" src="https://user-images.githubusercontent.com/3386955/29890935-9cea0710-8d86-11e7-89ae-688aa04698ea.png">

_Please let me know if I can provide better information or troubleshoot in any way. Thanks!_

**Comment by Mountainerd** [comment] 2017-08-31 06:14
I also pulled v1.0.4 and v1.0.3 and the behavior was the same.

**Comment by Mountainerd** [comment] 2017-08-31 06:14
At the suggestion of Tobias, I pulled the v1.1-alpha.20170817 binary .tgz down, placed it in a Ubuntu container, and ran it. It showed GiB instead of TiB but still nowhere close on available space or used space. I suspect it has to do with how Apple does its filesystem.

I then built a contained environment by installing Ubuntu 16.04.3 (with a 100GB disk) in VirtualBox and then installed latest Docker CE from Docker's repository. I then ran the container in that environment and checked the UI. The total capacity was listed at 93.9 GiB, which matches what Ubuntu Disks was reporting as total disk size (100.8 GB or 93.9 GiB). The total install size is 4.6 GB but the UI reported 9.3 GiB (9.9 GB) used. I'm speculating it's double counting somewhere along the way due to the filesystem sitting on top of LVM. Perhaps the UI is getting the disk usage for / but then also adding all the logical/sub volumes to the initial root usage number (hopefully that made sense).

<img width="471" alt="screen shot 2017-08-30 at 11 59 05 pm" src="https://user-images.githubusercontent.com/3386955/29909054-6b17adc2-8de1-11e7-95fa-4c05d7bbb949.png">

**Comment by Mountainerd** [comment] 2017-09-01 20:30
Thanks, @dianasaur323!

**Comment by dianasaur323** [comment] 2017-09-03 21:52
@Mountainerd no worries. Let me follow-up on this issue with the team on Monday so that we get a response back. We might not be able to squeeze a fix into the 1.1, but we should at least figure out what the issue is for you.

**Comment by benesch** [comment] 2018-02-27 16:05
@a-robinson can you triage this? I know you've made some capacity gauge-related fixes in the past. Perhaps it's already fixed?

**Comment by a-robinson** [comment] 2018-02-27 18:08
* 1.0.x was clearly broken.
* 1.1 looks reasonable for Docker for Mac. Docker for Mac runs in a VM with a default max disk size of 64 GiB -- it doesn't have access to your entire machine's disk.
* I don't have a good sense of what's going on in the double counting case. I wasn't able to repro when running docker on Linux, but I was using a GCE VM rather than a local VirtualBox VM. We're getting the disk usage/capacity directly via the `statfs` system call, though, so it'd be surprising if there's something wrong there (https://github.com/elastic/gosigar/blob/01b55aeacddd04369e674d32e0eb9a3e7e4394fe/sigar_unix.go#L14)

I'm going to close this, since I'm unable to reproduce any badness, but if you have reproduction instructions for the VirtualBox situation we can take a look sometime.

**Closed by a-robinson** 2018-02-27 18:08 UTC
Labels: community-questions
