### ISSUE TITLE
cli: cannot dump database with view

### ISSUE THREAD

**Issue by timosellin** [cockroachdb/cockroach#16396] opened 2017-06-07 21:23 UTC
Hi, I am trying to dump a database with a view, but it fails.

How to reproduce:

```
$ ./cockroach sql --insecure
> create database foo;
> create view foo.bar as select 1;
$ ./cockroach dump --insecure foo
CREATE TABLE bar (
        "1" INT NOT NULL
);
Error: pq: column name "rowid" not found
Failed running "dump"
```

My version:

```
$ ./cockroach version
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release
```

Expected result:
```
$ ./cockroach dump --insecure foo
CREATE VIEW bar AS SELECT 1;
$ echo $?
0
```

**Comment by benesch** [comment] 2017-06-09 15:15
Hi, @timosellin, thanks for the report and the minimal test case. I can definitely reproduce this. Assigning to @mjibson, who can give us a better sense of how involved the fix for this will be.

**Comment by benesch** [comment] 2017-06-09 15:17
Seems like we have some hardcoded assumptions about the presence of a `rowid` index: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/dump.go#L327

**Comment by mjibson** [comment] 2017-06-09 18:17
It's unclear to me how to proceed. Since views are just a select, they are not guaranteed to have primary keys, which means it might not be possible to page over the data in a consistent way. Unless there's another idea I think the best we can do now is to return an error saying views aren't supported by dump.

**Comment by dt** [comment] 2017-06-09 18:19
shouldn't dumping a view just dump its create statement, not the underlying data?

**Comment by mjibson** [comment] 2017-06-09 18:27
Yeah, that sounds right. We already support only dumping schemas, so likely need to just teach dump to skip over views during data dump time, and error if it's in data-only mode.

**Comment by timosellin** [comment] 2017-06-09 18:37
IMO dump should never fail. If you are dumping everything or just the schema the create statement should be dumped. If you are running in data-only mode, views should be just skipped.

**Comment by benesch** [comment] 2017-06-09 18:56
That's how pg_dump operates—i.e., skipping views when --data-only is
specified—so I'm in favor of that behavior.

**Closed** 2017-08-17 18:48 UTC
Labels: bug, community-questions
