### ISSUE TITLE
circleci: failed tests (13785): TestDockerPython 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4853] opened 2016-03-04 05:24 UTC
The following test appears to have failed:

[#13785](https://circleci.com/gh/cockroachdb/cockroach/13785):

```
I160304 05:23:33.811834 acceptance/replication_test.go:50  waiting for first range to have 3 replicas
I160304 05:23:34.831802 acceptance/replication_test.go:66  found 2 replicas
I160304 05:23:38.147830 acceptance/replication_test.go:66  found 2 replicas
I160304 05:23:49.861631 acceptance/replication_test.go:66  found 2 replicas
I160304 05:23:49.962275 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestDockerPython (23.78s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestDockerRuby
I160304 05:23:50.829872 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
........I160304 05:23:51.067734 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160304 05:23:52.478863 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.55
I160304 05:23:52.478908 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:63: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 01:46
Duplicate of #4835.

**Closed by petermattis** 2016-03-06 01:46 UTC
Labels: test-failure
