### ISSUE TITLE
Server crash after adding column to table.

### ISSUE THREAD

**Issue by linuxerwang** [cockroachdb/cockroach#5960] opened 2016-04-09 05:53 UTC
Please answer these questions **for each node in your cluster**:

1. What version of CockroachDB are you using (`cockroach version`)?

Build Tag:   beta-20160407
Build Time:  2016/04/07 15:24:20
Platform:    linux amd64
Go Version:  go1.6
C Compiler:  gcc 4.9.2

2. What operating system and processor architecture are you using?

Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty

3. What flags/environment variables did you pass to `cockroach start`?

cockroach start

Please describe the issue you observed:

1. What did you do?

First, create database "bank" as described in "Start a Cluster" document, create table "accounts" and insert one row.
Next, alter table "accounts" and add column "name": alter table accounts add column name varchar not null default '';
Now, run query:

root@:26257> select * from accounts;
driver: bad connection

2. What did you expect to see?

The new column should be added with existing rows have the column value '', the behavior in postgresql. At least, the server should not crash and then allow me to populate the new column.

3. What did you see instead?

The server crashed with:

panic: Non-nullable column with no value!

goroutine 166 [running]:
panic(0x145f6e0, 0xc8203275e0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.(*scanNode).maybeOutputRow(0xc8201d6c00, 0xc820327101)
        /go/src/github.com/cockroachdb/cockroach/sql/scan.go:522 +0x288
github.com/cockroachdb/cockroach/sql.(*scanNode).Next(0xc8201d6c00, 0x7e0)
......

**Comment by petermattis** [comment] 2016-04-09 15:25
Thanks for report @linuxerwang. This is a duplicate of #5751 and was fixed by #5759. The fix will be in the next beta release scheduled for 4/14.

**Closed by petermattis** 2016-04-09 15:25 UTC
