### ISSUE TITLE
Test failure in CI build 4664

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1695] opened 2015-07-16 00:23 UTC
The following test appears to have failed:

[#4664](https://circleci.com/gh/cockroachdb/cockroach/4664):

```
c5681200751585.99  127.0.0.1:0  00:14:41.200770  99.353µs  node                            server/node.go:489
c5681200751585.99  127.0.0.1:0  00:14:41.200789  78.285µs  ·executing InternalRangeLookup  storage/store.go:1237
c5681200751585.99  127.0.0.1:0  00:14:41.200794  73.023µs  ··read path                     storage/range.go:520

I0716 00:14:41.201096      72 kv/range_cache.go:149 adding descriptor: key="\x00\x00meta2\xff\xff" desc=raft_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 > 
panic: test timed out after 30s

goroutine 64414 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [semacquire]:
sync.(*Cond).Wait(0xc208541600)
	/usr/src/go/src/sync/cond.go:62 +0x9e
--
	/go/src/github.com/cockroachdb/cockroach/server/server.go:113 +0x3a
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:79 +0x5d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0xfc
FAIL	github.com/cockroachdb/cockroach/client	30.021s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
I0716 00:14:17.392155      87 base/context.go:141 setting up TLS from certificates directory: test_certs
I0716 00:14:17.408889      87 gossip/gossip.go:166 gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0716 00:14:17.408958      87 base/context.go:141 setting up TLS from certificates directory: test_certs
I0716 00:14:17.427908      87 gossip/gossip.go:166 gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0716 00:14:17.429399      87 base/context.go:103 setting up TLS from certificates directory: test_certs
I0716 00:14:17.471327      87 gossip/server.go:113 gossip: received infostore with 3 info(s): info "local-key": local value, info "node:1": node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "node:2": node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0716 00:21:26.057008     265 kv/range_cache.go:191 evict cached descriptor: key="\x00\x00meta2db1" desc=raft_id:1 start_key:"" end_key:"db 2" replicas:<node_id:1 store_id:1 > 
I0716 00:21:26.057115     265 kv/range_cache.go:191 evict cached descriptor: key="\x00\x00meta1db1" desc=<nil>
W0716 00:21:26.057263     265 kv/dist_sender.go:667 key range "db1"-"" outside of bounds of range "db 2"-"db 3"
I0716 00:21:26.057335     265 kv/range_cache.go:122 lookup range descriptor: key="db1"
I0716 00:21:26.057412     265 kv/range_cache.go:122 lookup range descriptor: key="\x00\x00meta2db1"
panic: test timed out after 5m0s

goroutine 209075 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [semacquire, 4 minutes]:
sync.(*Cond).Wait(0xc208523600)
	/usr/src/go/src/sync/cond.go:62 +0xb6
--
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:130 +0x9df
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:79 +0x8c
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x14c
FAIL	github.com/cockroachdb/cockroach/client	300.092s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
I0716 00:16:43.720261     286 base/context.go:141 setting up TLS from certificates directory: test_certs
I0716 00:16:43.778343     286 gossip/gossip.go:166 gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0716 00:16:43.778787     286 base/context.go:141 setting up TLS from certificates directory: test_certs
I0716 00:16:43.834673     286 gossip/gossip.go:166 gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0716 00:16:43.838460     286 base/context.go:103 setting up TLS from certificates directory: test_certs
I0716 00:16:44.103059     286 gossip/server.go:113 gossip: received infostore with 3 info(s): info "node:1": node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "node:2": node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "local-key": local value

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-07-16 01:30
Duplicate of #1684

**Closed by bdarnell** 2015-07-16 01:30 UTC
Labels: test-failure
