### ISSUE TITLE
kvstreamer: super-linear increase in latency and number of gPRC calls in InOrder mode

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#133043] opened 2024-10-21 12:10 UTC
See the reproduction here: https://gist.github.com/mgartner/6163ac9079c64ca0d46592ff85f115ce

This reproduction runs 3 queries, index-joining ~10k, ~20k, and ~30k rows each. The latency and number of gRPC calls for each index-join grows super-linearly.

<img width="597" alt="image" src="https://github.com/user-attachments/assets/3cd96a32-6f71-4a14-99a9-b6f810aff143">

This seems related to #113729. That issue was addressed by #113809, however, I could not improve the performance of this new reproduction with any setting of `streamer_in_order_eager_memory_usage_fraction` - I tried as low as `0.05` and as high as `0.95`.

I believe the code/comment here may be relevant: https://github.com/cockroachdb/cockroach/blob/c83c57d354741ac36740894f7387c014eb6c09fe/pkg/kv/kvclient/kvstreamer/streamer.go#L1106-L1127

Jira issue: CRDB-43434

**Comment by mgartner** [comment] 2024-10-23 10:17
One workaround that may help improve performance in some cases is to disable the streamer with `SET streamer_enabled = false;`.

**Comment by yuzefovich** [comment] 2024-11-04 22:19
Thanks Marcus for detailed reproduction steps! I found a pretty simple yet somewhat egregious bug that will be fixed by #134132; however, I still see the streamer being about 3x slower that disabling it for this scenario - I filed #134132 to track that investigation separately (which seems to be of a lower urgency).

**Closed** 2024-11-06 00:39 UTC
Labels: C-performance, O-support, branch-master, T-sql-queries, branch-release-22.2, branch-release-23.1, branch-release-24.1, branch-release-23.2, P-2, branch-release-24.2, branch-release-24.3, v23.1.30, v23.2.17, v24.1.8
