### ISSUE TITLE
Update does NOT update the value but returns it (returning), no error message

### ISSUE THREAD

**Issue by v-from-meiro** [cockroachdb/cockroach#98372] opened 2023-03-10 13:55 UTC
**Describe the problem**

I run update on a column for 1 exact row in a table, returning clause returns update value, but when I issue select query for this exact row, the value is NULL.

Notes:
- 1 table customer_attributes, not FK or any other funky business
- I do UPDATE on a single row, updating 2 columns. I use returning clause to see what happened - all good
- But when I do a SELECT on that exact row (no AOST), the value is not updated - it is NULL
- Using autocommit
- No error after issuing any of the statements

I do not know how to reproduce it, I can currently observe it only on 1 table in my cluster (that I know of).

**Expected behavior**
Well, I expect update updates the value :) 

**Additional data / screenshots**
https://cockroachdb.slack.com/archives/CP4D9LD5F/p1678454333738419

**Environment:**
 - CockroachDB version V22.2.3
 - Server OS: Latest Ubuntu LTS
 - DataGrip, cockroach sql, pgx for golang

**Additional context**
The column has been added using Alter table.

I can share debug bundle, but I would rather not do it publicly.

<img width="1321" alt="Screenshot 2023-03-10 at 14 17 35" src="https://user-images.githubusercontent.com/27473626/224334081-e7743003-4737-4359-9395-9065df5fbf6a.png">
<img width="1276" alt="Screenshot 2023-03-10 at 14 17 28" src="https://user-images.githubusercontent.com/27473626/224334087-5ad1b565-311b-43e3-8e34-b748bc8e6e87.png">

Jira issue: CRDB-25231

**Comment by fqazi** [comment] 2023-03-10 15:23
@ajwerner Found that the root cause of this is because our version gates in a mixed version state are not properly aligned, so if a column gets added/dropped in this state we run the danger of potentially using the declarative schema changer for schema changes that other nodes may not correctly support (i.e. depending on which node adopts the job).

**Comment by ajwerner** [comment] 2023-03-10 15:34
Here's a query that can be used to detect the situation in a cluster:

```sql
WITH
	descs
		AS (
			SELECT
				id, crdb_internal.pb_to_json('desc', descriptor) AS descriptor
			FROM
				system.descriptor
		),
	tables
		AS (
			SELECT id, descriptor FROM descs WHERE (descriptor->'table') IS NOT NULL
		),
	primary_index_columns
		AS (
			SELECT
				id, array_agg(col_id) AS col_ids
			FROM
				(
					SELECT
						id,
						json_array_elements(
							descriptor->'table'->'primaryIndex'->'storeColumnIds'
						)
							AS col_id
					FROM
						tables
					UNION ALL
						SELECT
							id,
							json_array_elements(
								descriptor->'table'->'primaryIndex'->'keyColumnIds'
							)
						FROM
							tables
				)
			GROUP BY
				id
		),
	columns
		AS (
			SELECT
				id, array_agg(col->'id') AS col_ids
			FROM
				(
					SELECT
						id,
						json_array_elements(descriptor->'table'->'columns') AS col
					FROM
						tables
				)
			WHERE
				(col->'virtual') IS NULL
			GROUP BY
				id
		)
SELECT
	primary_cols.id
FROM
	primary_index_columns AS primary_cols
	JOIN columns AS all_cols ON (primary_cols.id = all_cols.id)
WHERE
	NOT (primary_cols.col_ids @> all_cols.col_ids);
```

**Comment by fqazi** [comment] 2023-03-11 02:10
Fix merged via: https://github.com/cockroachdb/cockroach/pull/98379

**Closed** 2023-03-11 02:09 UTC
Labels: C-bug, O-community, S-1, X-blathers-triaged, T-sql-schema
