### ISSUE TITLE
LIMIT x OFFSET y: doesn't seem to work correctly

### ISSUE THREAD

**Issue by mmstick** [cockroachdb/cockroach#16163] opened 2017-05-26 11:36 UTC
build:      CCL v1.0 @ 2017/05/10 13:19:57 (go1.8.1)

So I need to be able to grab a range of rows by setting an offset and limiting the results returned. However, it would seem that what is actually happening when using the syntax is that it limits the results by x and then offsets the index from those limited results, quickly resulting in returning 0 results when given something like LIMIT 10 OFFSET 10. In addition, if I invoke OFFSET by itself, or OFFSET before LIMIT, the database crashes.

**Comment by andreimatei** [comment] 2017-05-26 19:54
Dupe of #16090.

This has been recently fixed. The next release (1.0.2) will contain the fix (or you can build from head in the meantime). Sorry for the trouble.

**Closed by andreimatei** 2017-05-26 19:54 UTC
