### ISSUE TITLE
sql: "Validating Schema" stage of schema change doesn't give any indication of progress

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#44358] opened 2020-01-24 18:31 UTC
Or TPCC, the following FK addition takes a while in the "Validating Schema" state and while it does, the progress of the respective job stays at 0%.
```
ALTER TABLE tpcc.public.history ADD FOREIGN KEY (h_c_w_id, h_c_d_id, h_c_id) REFERENCES tpcc.public.customer (c_w_id, c_d_id, c_id)
```

I'd like some indication of progress - like number of rows checked. And if the total is known from the stats, then I'd like the progress bar to move along too.

**Comment by lucy-zhang** [comment] 2020-04-30 18:53
Closing as this is a duplicate of #26639.

**Closed by lucy-zhang** 2020-04-30 18:53 UTC
Labels: C-enhancement
