### ISSUE TITLE
ui: node map not centered in Firefox or Safari

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#22781] opened 2018-02-16 21:26 UTC
### Chrome:

<img width="1277" alt="screen shot 2018-02-16 at 4 25 03 pm" src="https://user-images.githubusercontent.com/5438456/36330009-0cb0a8b2-1336-11e8-8fae-2ea4dd3e11a1.png">

### Firefox:

![screenshot-2018-2-16 cockroach console](https://user-images.githubusercontent.com/5438456/36329921-b81ff974-1335-11e8-8416-103515198af6.png)

### Safari:

<img width="1275" alt="screen shot 2018-02-16 at 4 24 35 pm" src="https://user-images.githubusercontent.com/5438456/36330020-11517af4-1336-11e8-9011-b1ab55b9cccd.png">

**Comment by couchand** [comment] 2018-02-20 14:53
@nvanbenschoten thanks for the report.  Marking this as a dupe of #22594.

**Closed by couchand** 2018-02-20 14:53 UTC
Labels: ux-surprise
