### ISSUE TITLE
settings: setting cluster setting does not take effect until session restart

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#18604] opened 2017-09-19 19:45 UTC
Changing the cluster setting `sql.defaults.distsql = off` does not take effect immediately. DistSQL queries do not inherit the cluster setting when the cluster setting is changed, since they only check the session settings (`SET DISTSQL = OFF`), which is initialized off the cluster setting when the session is initialized.

This behavior is counterintuitive, and should perhaps at least be documented in the cluster setting description.

cc @dt

**Comment by tschottdorf** [comment] 2017-09-19 19:51
My understanding is that this is intentional. Active sessions should not change their behavior, but once you open a new session, you do get it.

**Comment by arjunravinarayan** [comment] 2017-09-19 19:55
I'm willing to buy that it's intentional, but then we should modify the description string to warn users that this will not take effect until the next session.

**Comment by dt** [comment] 2017-09-19 19:59
I also think it was intentional, but given that the behavior is surprising -- people seem to expect changing the setting to change active sessions, and not need to bounce all their app servers to see it take effect. Given the tendency of apps to keep long-lived sessions open, and the unpredictability of when client libraries that pool/multiplex might open new sessions versus use old ones, I can see an argument for using the cluster setting directly in the absence of a session-specific override.

**Comment by tschottdorf** [comment] 2017-09-19 20:12
Those are good points. I don't feel strongly one way or another but

> I can see an argument for using the cluster setting directly in the absence of a session-specific override.

seems reasonable.

**Comment by bdarnell** [comment] 2017-09-20 17:00
For a setting like distsql on/off it seems reasonable for the cluster setting to take effect immediately. (it feels like it's primarily a cluster setting, not a session setting). For other things it's less clear (for example, if we had a cluster setting for time zone it seems weird that changing it would affect things mid-transaction). 

Also, the existence of cluster settings that don't take effect until all sessions have been restarted is a good argument for session cancellation (#17252). Cancelling all active sessions would be less disruptive than restarting all client processes.

**Comment by vivekmenezes** [comment] 2017-10-03 15:22
Moving to 1.2 since this doesn't qualify as a pressing issue.

**Comment by jordanlewis** [comment] 2019-01-04 16:13
This is expected behavior.

**Closed by jordanlewis** 2019-01-04 16:13 UTC
Labels: C-enhancement
