### ISSUE TITLE
stress: failed test in cockroach/util/interval/interval.test: TestRangeListAndRangeGroupIdentical

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4857] opened 2016-03-04 10:59 UTC
The following test appears to have failed:

```
=== RUN   TestRangeListAndRangeGroupIdentical
--- FAIL: TestRangeListAndRangeGroupIdentical (0.00s)
	range_group_test.go:544: expected subtracting [636f15-707fc6) from RangeList [[17ddb3-5f0d01) [707fc6-faa1aa)] and RangeTree [[17ddb3-5f0d01) [707fc6-faa1aa)] to produce the same result; got false from RangeList and true from RangeTree
FAIL


ERROR: exit status 1
```
Please assign, take a look and update the issue accordingly.

**Comment by nvanbenschoten** [comment] 2016-03-04 14:32
Duplicate of #4841.

**Closed by nvanbenschoten** 2016-03-04 14:32 UTC
Labels: Robot, test-failure
