### ISSUE TITLE
stability: cyan crashes with "on-disk and in-memory state diverged"

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#15848] opened 2017-05-10 16:22 UTC
4 nodes on `cyan` crashed with:
```
F170510 16:03:40.456638 79 storage/replica.go:1353  [n3,s3,r6131/1:/System/tsd/cr.node.round-tri…] on-disk and in-memory state diverged
```
(not always or the same range).

Happened more than once, starting yesterday: eg: on cyan-0001:
```
logs/cockroach.stderr:F170509 20:02:09.498146 93 storage/replica.go:1353  [n1,s1,r353/3:/Table/52/1/918{72107…-94587…}] on-disk and in-memory state diverged:
logs/cockroach.stderr:F170510 16:01:34.195071 110 storage/replica.go:1353  [n1,s1,r2167/6:/Table/52/1/283{22717…-45322…}] on-disk and in-memory state diverged:
```
The sha for the older crash is 752e5b3.

Disabling continuous deployment against `cyan` for now.

**Comment by mberhault** [comment] 2017-05-10 16:22
We saw this ages ago on #10723.

**Comment by a-robinson** [comment] 2017-05-10 16:39
This probably just fallout from #15819, assigning to @tamird to double check.

**Comment by tamird** [comment] 2017-05-10 17:55
I think this is just a duplicate of #15819. @mberhault could you re-enable the continuous deployment, please?

**Closed by tamird** 2017-05-10 17:56 UTC

**Comment by mberhault** [comment] 2017-05-10 18:06
can do. does it need a wipe, or will it be able to resume successfully?

**Comment by tamird** [comment] 2017-05-10 18:13
Should be able to resume.

**Comment by mberhault** [comment] 2017-05-10 18:20
ok, not so much. crash-loop.
