### ISSUE TITLE
TypeORM - Lack of support for enum's and Table Locality

### ISSUE THREAD

**Issue by IS-Josh** [cockroachdb/cockroach#68368] opened 2021-08-03 11:06 UTC
name: 'Feature request'
title: 'enum and locality support for TYPEORM'
about: 'We are starting out with our re-factor and we chose to use typeorm. Because of it's nodejs comaptability and support for Cockroachdb.  We'd like to validate input on some columns using e-nums and are have a region by row model however the cockroachdb driver for typeorm does not support either of the features.'
labels: 'C-enhancement'
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
We've got some tight deadlines and it's really frustrating when supported tools have limited support (meaning delays for us to work around or change tactic) 

**Describe the solution you'd like**
I'd like typeorm to support enum's along with the ability to specify locality (region by row) 

**Describe alternatives you've considered**
I've considered implementing validation via foreign key constraints, however i'd rather not go down this path.

**Additional context**

**Comment by rafiss** [comment] 2021-08-05 15:20
Thanks for filing this! I confirmed that the cockroachdb dialect for TypeORM doesn't seem to handle this:
```
DataTypeNotSupportedError: Data type "enum" in "DatasourceAction.action" is not supported by "cockroachdb" database.
    at new DataTypeNotSupportedError (/Users/rafiss/scratch/hello-world-typescript-typeorm/src/error/DataTypeNotSupportedError.ts:9:9)
    at /Users/rafiss/scratch/hello-world-typescript-typeorm/src/metadata-builder/EntityMetadataValidator.ts:87:27
    at Array.forEach (<anonymous>)
```

I was adding an enum definition like this:
```
type Action =
    'add' |
    'update' |
    'delete';
@Entity()
export class Model {

    @PrimaryColumn()
    id: string;

    @Column({ name: 'name', type: 'text', unique: true })
    name: string;

    @Column({ name: 'action', type: 'enum', enum: ['add', 'update', 'delete'] })
    action: Action;
}
```

To address this, support needs to be added in TypeORM. I filed an issue here https://github.com/typeorm/typeorm/issues/8039

**Comment by rafiss** [comment] 2021-09-02 21:01
I'm closing this since this needs to be tracked on the TypeORM side

**Closed** 2021-09-02 21:01 UTC
Labels: O-community, X-blathers-triaged, T-sql-experience
