### ISSUE TITLE
sentry: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object(_, (COALESCE(_._->>_, _)::FLOAT8) + _) RETURNING _ AS _, _: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#32580] opened 2018-11-24 15:22 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/776010945/?referrer=webhooks_plugin

conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object(_, (COALESCE(_._->>_, _)::FLOAT8) + _) RETURNING _ AS _, _: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'lineno': 309, u'in_app': True}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 420, u'in_app': True}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 1143, u'in_app': True}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 95, u'in_app': True}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 403, u'in_app': True}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 825, u'in_app': True}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'lineno': 983, u'in_app': True}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 746, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'lineno': 253, u'in_app': True}, {u'function': u'StartSync', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go', u'lineno': 602, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go', u'lineno': 731, u'in_app': True}, {u'function': u'Run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go', u'lineno': 170, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go', u'lineno': 205, u'in_app': True}, {u'function': u'Next', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go', u'lineno': 123, u'in_app': True}, {u'function': u'BatchedNext', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*upsertNode)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'lineno': 331, u'in_app': True}, {u'function': u'atBatchEnd', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'lineno': 431, u'in_app': True}, {u'function': u'updateConflictingRow', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*tableUpserter)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/tablewriter_upsert.go', u'lineno': 498, u'in_app': True}, {u'function': u'eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*upsertHelper)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/upsert.go', u'lineno': 683, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2587, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 3400, u'in_app': True}, {u'function': u'evalArgs', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FuncExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 3386, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2580, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2729, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CoalesceExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 3318, u'in_app': True}, {u'function': u'Eval', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*BinaryExpr)', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 2594, u'in_app': True}, {u'function': u'func99', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree.glob.', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go', u'lineno': 1396, u'in_app': True}, {u'function': u'panicdottypeI', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'filename': u'runtime/iface.go', u'lineno': 262, u'in_app': False}, {u'function': u'panicdottypeE', u'abs_path': u'/usr/local/go/src/runtime/iface.go', u'module': u'runtime', u'filename': u'runtime/iface.go', u'lineno': 252, u'in_app': False}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'filename': u'runtime/panic.go', u'lineno': 502, u'in_app': False}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'filename': u'runtime/asm_amd64.s', u'lineno': 573, u'in_app': False}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'lineno': 418, u'in_app': True}]}
type: *log.safeError
value: conn_executor.go:670: panic while executing 1 statements: INSERT INTO _(_, _) VALUES (_, _), (__more1__) ON CONFLICT (_) DO UPDATE SET _ = now(), _ = _._ || jsonb_build_object(_, (COALESCE(_._->>_, _)::FLOAT8) + _) RETURNING _ AS _, _: caused by <redacted>

**Comment by rytaft** [comment] 2018-11-26 02:36
Looks like a duplicate of #32579

**Closed by rytaft** 2018-11-26 02:36 UTC
Labels: C-bug, O-sentry
