### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6077] opened 2016-04-15 10:37 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/4335205d7391fc4a6741c0043a085256ec56c838

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x461141 m=0

goroutine 0 [idle]:
runtime.futex(0x11605a8, 0x0, 0x0, 0x0, 0x0, 0x115fb50, 0x0, 0x0, 0x40fbf4, 0x11605a8, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:302 +0x21
runtime.futexsleep(0x11605a8, 0x0, 0xffffffffffffffff)
	/usr/local/go/src/runtime/os1_linux.go:40 +0x53
runtime.notesleep(0x11605a8)
	/usr/local/go/src/runtime/lock_futex.go:145 +0xa4
runtime.stopm()
	/usr/local/go/src/runtime/proc.go:1535 +0x10b
runtime.findrunnable(0xc820017500, 0x0)
	/usr/local/go/src/runtime/proc.go:1973 +0x739
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.park_m(0xc820001e00)
	/usr/local/go/src/runtime/proc.go:2137 +0x18b
runtime.mcall(0x7fff63760dd0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcf6a00, 0x11400c0, 0xb, 0xb, 0xb56901)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82003df08, 0xb569c0)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 7 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x115fa60)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:994 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:595 +0x8a

goroutine 71 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201a5e0c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201a5e08)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc8201a5e00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc82008e000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc82008e000, 0x1140138)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 57 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82019e000, 0xc82013b3a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 58 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd0391c0bc8, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82061f3a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82061f3a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82061f340, 0x0, 0x7fd0390ff138, 0xc8203781e0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82002a028, 0xc82003bea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82002a028, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82061da00, 0x7fd0391bfc20, 0xc82002a028, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82019e000, 0xc82013b3c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 59 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82019e000, 0xc82013b4c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 56 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82019e000, 0xc8201c6080)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 60 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201702a0)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201702a0)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 61 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201bfb34)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201bfb30)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201bfb30, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc8201a5e00, 0xcf7280)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc8201a5e00, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc8201a5e00, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc82061f3b0, 0xc82066c280, 0xc82019db40, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:175 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:157 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82019e000, 0xc82015b4d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 82 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd0391c0b08, 0x72, 0xc8203b6400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82038e060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82038e060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82038e000, 0xc8203b6400, 0x400, 0x400, 0x0, 0x7fd03923e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820126000, 0xc8203b6400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201ba6f0, 0x7fd0391fe550, 0xc820126000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820390000, 0xcf7217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820390000, 0xc82089c000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8201a03c0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8201a03c0, 0xc82037a038, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fd039258618, 0xc8201a03c0, 0xc82037a038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd039258618, 0xc8201a03c0, 0xc82037a038, 0x9, 0x9, 0x3e0aee1e2d547901, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82037a038, 0x9, 0x9, 0x7fd039258618, 0xc8201a03c0, 0x39000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82037a000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201ba870, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8203b0000, 0xc8201ba930)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82061da00, 0x7fd039258668, 0xc8203b0000)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82061da00, 0x7fd039258540, 0xc820390000, 0x7fd0392585a0, 0xc8206742c0)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82061da00, 0x7fd0391fe4f0, 0xc820126000)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 72 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820307c20)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 36 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8203b0000)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 73 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd0391c0a48, 0x72, 0xc820113800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820380060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820380060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820380000, 0xc820113800, 0x400, 0x400, 0x0, 0x7fd03923e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201380f0, 0xc820113800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201c00c0, 0x7fd0391fe550, 0xc8201380f0, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc82039a000, 0xcf7217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc82039a000, 0xc820392000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8206671a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8206671a0, 0xc82088b6b8, 0x9, 0x9, 0xc81fff2296, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fd039258618, 0xc8206671a0, 0xc82088b6b8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd039258618, 0xc8206671a0, 0xc82088b6b8, 0x9, 0x9, 0xc8201731a8, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82088b6b8, 0x9, 0x9, 0x7fd039258618, 0xc8206671a0, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82088b680, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820172fc0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc820307c20)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

rax    0xca
rbx    0x0
rcx    0x461143
rdx    0x0
rdi    0x11605a8
rsi    0x0
rbp    0x1
rsp    0x7fff63760c30
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x5a0
r13    0x8000
r14    0xbc87f0
r15    0x37
rip    0x461141
rflags 0x286
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
68 runs so far, 0 failures, over 5s
140 runs so far, 0 failures, over 10s
210 runs so far, 0 failures, over 15s
283 runs so far, 0 failures, over 20s
352 runs so far, 0 failures, over 25s
425 runs so far, 0 failures, over 30s
498 runs so far, 0 failures, over 35s
568 runs so far, 0 failures, over 40s
645 runs so far, 0 failures, over 45s
707 runs so far, 0 failures, over 50s
781 runs so far, 0 failures, over 55s
853 runs so far, 0 failures, over 1m0s
926 runs so far, 0 failures, over 1m5s
994 runs so far, 0 failures, over 1m10s
1066 runs so far, 0 failures, over 1m15s
1137 runs so far, 0 failures, over 1m20s
1207 runs so far, 0 failures, over 1m25s
1280 runs so far, 0 failures, over 1m30s
1353 runs so far, 0 failures, over 1m35s
1426 runs so far, 0 failures, over 1m40s
1501 runs so far, 0 failures, over 1m45s
1570 runs so far, 0 failures, over 1m50s
1644 runs so far, 0 failures, over 1m55s
1715 runs so far, 0 failures, over 2m0s
1789 runs so far, 0 failures, over 2m5s
1858 runs so far, 0 failures, over 2m10s
1930 runs so far, 0 failures, over 2m15s
1999 runs so far, 0 failures, over 2m20s
2072 runs so far, 0 failures, over 2m25s
2140 runs so far, 0 failures, over 2m30s
2213 runs so far, 0 failures, over 2m35s
2286 runs so far, 0 failures, over 2m40s
2357 runs so far, 0 failures, over 2m45s
2430 runs so far, 0 failures, over 2m50s
2494 runs so far, 0 failures, over 2m55s
2563 runs so far, 0 failures, over 3m0s
2632 runs so far, 0 failures, over 3m5s
2701 runs so far, 0 failures, over 3m10s
2761 runs so far, 0 failures, over 3m15s
2826 runs so far, 0 failures, over 3m20s
2893 runs so far, 0 failures, over 3m25s
2965 runs so far, 0 failures, over 3m30s
3031 runs so far, 0 failures, over 3m35s
3099 runs so far, 0 failures, over 3m40s
3174 runs so far, 0 failures, over 3m45s
3242 runs so far, 0 failures, over 3m50s
3307 runs so far, 0 failures, over 3m55s
3376 runs so far, 0 failures, over 4m0s
3442 runs so far, 0 failures, over 4m5s
3511 runs so far, 0 failures, over 4m10s
3583 runs so far, 0 failures, over 4m15s
3654 runs so far, 0 failures, over 4m20s
3720 runs so far, 0 failures, over 4m25s
3793 runs so far, 0 failures, over 4m30s
3862 runs so far, 0 failures, over 4m35s
3932 runs so far, 0 failures, over 4m40s
3997 runs so far, 0 failures, over 4m45s
4064 runs so far, 0 failures, over 4m50s
4134 runs so far, 0 failures, over 4m55s
4201 runs so far, 0 failures, over 5m0s
4270 runs so far, 0 failures, over 5m5s
4325 runs so far, 0 failures, over 5m10s
4395 runs so far, 0 failures, over 5m15s
4469 runs so far, 0 failures, over 5m20s
4536 runs so far, 0 failures, over 5m25s
4605 runs so far, 0 failures, over 5m30s
4677 runs so far, 0 failures, over 5m35s
4743 runs so far, 0 failures, over 5m40s
4810 runs so far, 0 failures, over 5m45s
4879 runs so far, 0 failures, over 5m50s
4951 runs so far, 0 failures, over 5m55s
5021 runs so far, 0 failures, over 6m0s
5090 runs so far, 0 failures, over 6m5s
5158 runs so far, 0 failures, over 6m10s
5227 runs so far, 0 failures, over 6m15s
5294 runs so far, 0 failures, over 6m20s
5363 runs so far, 0 failures, over 6m25s
5429 runs so far, 0 failures, over 6m30s
5495 runs so far, 0 failures, over 6m35s
5564 runs so far, 0 failures, over 6m40s
5631 runs so far, 0 failures, over 6m45s
5695 runs so far, 0 failures, over 6m50s
5767 runs so far, 0 failures, over 6m55s
5836 runs so far, 0 failures, over 7m0s
5905 runs so far, 0 failures, over 7m5s
5974 runs so far, 0 failures, over 7m10s
6044 runs so far, 0 failures, over 7m15s
6114 runs so far, 0 failures, over 7m20s
6185 runs so far, 0 failures, over 7m25s
6250 runs so far, 0 failures, over 7m30s
6312 runs so far, 0 failures, over 7m35s
6379 runs so far, 0 failures, over 7m40s
6444 runs so far, 0 failures, over 7m45s
6510 runs so far, 0 failures, over 7m50s
6576 runs so far, 0 failures, over 7m55s
6642 runs so far, 0 failures, over 8m0s
6705 runs so far, 0 failures, over 8m5s
6771 runs so far, 0 failures, over 8m10s
6837 runs so far, 0 failures, over 8m15s
6902 runs so far, 0 failures, over 8m20s
6972 runs so far, 0 failures, over 8m25s
7041 runs so far, 0 failures, over 8m30s
7107 runs so far, 0 failures, over 8m35s
7175 runs so far, 0 failures, over 8m40s
7241 runs so far, 0 failures, over 8m45s
7302 runs so far, 0 failures, over 8m50s
7371 runs so far, 0 failures, over 8m55s
7439 runs so far, 0 failures, over 9m0s
7507 runs so far, 0 failures, over 9m5s
7575 runs so far, 0 failures, over 9m10s
7644 runs so far, 0 failures, over 9m15s
7706 runs so far, 0 failures, over 9m20s
7776 runs so far, 0 failures, over 9m25s
7839 runs so far, 0 failures, over 9m30s
7907 runs so far, 0 failures, over 9m35s
7970 runs so far, 0 failures, over 9m40s
8038 runs so far, 0 failures, over 9m45s
8100 runs so far, 0 failures, over 9m50s
8170 runs so far, 0 failures, over 9m55s
8228 runs so far, 0 failures, over 10m0s
8297 runs so far, 0 failures, over 10m5s
8363 runs so far, 0 failures, over 10m10s
8427 runs so far, 0 failures, over 10m15s
8490 runs so far, 0 failures, over 10m20s
8554 runs so far, 0 failures, over 10m25s
8619 runs so far, 0 failures, over 10m30s
8686 runs so far, 0 failures, over 10m35s
8747 runs so far, 0 failures, over 10m40s
8812 runs so far, 0 failures, over 10m45s
8869 runs so far, 0 failures, over 10m50s
8935 runs so far, 0 failures, over 10m55s
9000 runs so far, 0 failures, over 11m0s
9065 runs so far, 0 failures, over 11m5s
9133 runs so far, 0 failures, over 11m10s
9198 runs so far, 0 failures, over 11m15s
9263 runs so far, 0 failures, over 11m20s
9329 runs so far, 0 failures, over 11m25s
9396 runs so far, 0 failures, over 11m30s
9459 runs so far, 0 failures, over 11m35s
9525 runs so far, 0 failures, over 11m40s
9595 runs so far, 0 failures, over 11m45s
9659 runs so far, 0 failures, over 11m50s
9730 runs so far, 0 failures, over 11m55s
9795 runs so far, 0 failures, over 12m0s
9864 runs so far, 0 failures, over 12m5s
9927 runs so far, 0 failures, over 12m10s
9992 runs so far, 0 failures, over 12m15s
10053 runs so far, 0 failures, over 12m20s
10118 runs so far, 0 failures, over 12m25s
10187 runs so far, 0 failures, over 12m30s
10250 runs so far, 0 failures, over 12m35s
10320 runs so far, 0 failures, over 12m40s
10385 runs so far, 0 failures, over 12m45s
10451 runs so far, 0 failures, over 12m50s
10515 runs so far, 0 failures, over 12m55s
10584 runs so far, 0 failures, over 13m0s
10605 runs completed, 1 failures, over 13m1s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:11
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:11 UTC
Labels: Robot, test-failure
