### ISSUE TITLE
1.1.5: admin UI no longer working with FF58

### ISSUE THREAD

**Issue by bsnyder788** [cockroachdb/cockroach#22408] opened 2018-02-06 14:56 UTC
Is this a question, feature request, or bug report?

Bug report

**BUG REPORT**

2. Please describe the issue you observed:

- What did you do?
Upgraded an existing 1.1.4 cluster to 1.1.5. After the upgrade the admin UI no longer loads in Firefox 58 or Firefox Nightly.  The admin UI does still load in Chrome and Chrome beta.

- What did you expect to see?

A working admin UI in Firefox.

- What did you see instead?

A broken admin UI with no console logs or network requests recorded.

**Comment by arjunravinarayan** [comment] 2018-02-06 16:03
Assigned to @vilterp for triage and reassignment.

**Comment by couchand** [comment] 2018-02-06 16:19
@bsnyder788 thanks for the report!  Can you provide a few more details?

What operating system are you running?

What do you mean by broken?  What do you see specifically?

**Comment by bsnyder788** [comment] 2018-02-06 16:23
Sure. @couchand .  I am running Ubuntu 14.04 with Firefox 58.0.1 (64-bit).  
![screen shot 2018-02-06 at 8 43 19 am](https://user-images.githubusercontent.com/3028415/35870639-c45ddfa0-0b27-11e8-8f92-159a3787d093.png)

**Comment by vilterp** [comment] 2018-03-01 21:10
Hi @bsnyder788, I'm unable to repro this using FF 58 on Ubuntu. Are you still seeing this?

**Comment by bsnyder788** [comment] 2018-03-01 21:22
Still not working completely on Ubuntu 14.04 with Firefox 58.0.2 for me (I
can navigate directly to the different tabs (cluster, databases, etc via
URL, yet clicking on them in UI does nothing).  Chrome works completely
fine for me on the same machine, though.

**Comment by vilterp** [comment] 2018-03-01 21:28
(deleted my comment because I realized I was on Cockroach 2.0 alpha, not 1.1.5. However, I still can't repro on 1.1.5).

Can you open the developer tools and take a screenshot of what's in the console? ([web console docs](https://developer.mozilla.org/en-US/docs/Tools/Web_Console/Opening_the_Web_Console)). I'm wondering if a strange FF-only network or JS issue is causing this. Thanks.

**Comment by bsnyder788** [comment] 2018-03-01 21:34
Nothing gets logged in the JS console, but I do see with top that the whole
tab just freezes up and CPU goes to 100% for that FF process.  Which
partially explains why I can't click on the other tabs.

**Comment by vilterp** [comment] 2018-03-01 21:36
Strange that the CPU is pegged. Can you maybe hit "pause" in the JS debugger and take a screenshot of the stack?

**Comment by bsnyder788** [comment] 2018-03-01 21:50
Tried 3 times and each time the UI froze up before I could hit pause and get a meaningful stack.

**Comment by vilterp** [comment] 2018-03-01 22:14
Hm, not sure how to introspect what's taking up the CPU without the devtools, besides resorting to OS-level tools… Would you mind seeing if this also happens with a 2.0 alpha? ([downloads](https://www.cockroachlabs.com/docs/releases/#testing-releases))

**Comment by bsnyder788** [comment] 2018-03-02 15:05
Sure, the cockroach-v2.0-alpha20180129 binary suffers from the same issue.
It seems slightly better in that the overview tab does not have the issue,
but after clicking on 'Cluster', 'Databases', or 'Jobs' the same thing
happens as with the 1.1.5 build.

**Comment by bsnyder788** [comment] 2018-03-02 15:10
I just re-downloaded v1.1.4 and it also suffers from the same issue which I
never had an issue with when it was what we were running.  Feel free to
close it as it may have something to do with my local FF since you cannot
reproduce.

**Comment by couchand** [comment] 2018-03-05 17:11
This is starting to sound like a dupe of #19903 (the original report didn't, but these followups do).  Closing in favor of that issue, @bsnyder788 please feel free to add any further insights you have over there.

As I commented on that one, what's really weird to me about this issue is that I develop using Firefox almost exclusively, and I'm on Ubuntu a fair percent of the time, and I've never seen this problem.  But it does sound like it's affecting a number of people, so hopefully we'll have some time to dig into it soon.

**Closed by couchand** 2018-03-05 17:11 UTC
Labels: bug

**Comment by bsnyder788** [comment] 2018-03-05 17:26
Thanks! It indeed sounds like the exact issue I was seeing.
