### ISSUE TITLE
build: Migrate `cockroach` to go modules

### ISSUE THREAD

**Issue by kenliu** [cockroachdb/cockroach#38824] opened 2019-07-11 19:10 UTC
- Affects all of backend engineering
- Standard way of doing dependency management
- Increases efficiency for engineers

**Comment by akshayjshah** [comment] 2019-11-21 16:54
Dupe of #35426?

**Comment by bobvawter** [comment] 2020-05-04 13:37
Duplicate of #35426

**Closed by bobvawter** 2020-05-04 13:37 UTC
Labels: A-build-system, C-enhancement
