### ISSUE TITLE
Ranges fail to up-replicate on a 5 node cluster with 2 dead nodes

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#117986] opened 2024-01-19 18:28 UTC
**Describe the problem**

When running a 3 node cluster, if there's a scenario where a dead node is replaced with a new node (one at a time) but the old nodes are not decommissioned, once we create n5, then it takes on no replicas and the remaining ranges stay at 2 replicas each.

**To Reproduce**

1.  Create a new 3-node cluster (23.1.13 is fine, but it seems to affect all versions)
2. To speed up the reproduction, run `SET CLUSTER SETTING server.time_until_store_dead = '1m15s';`
3. Kill node 3, wipe the cockroach-data directory and start it again so it begins at n4.  Allow time for node 3 to turn completely dead and up-replicate.
4. Repeat the previous step, killing node 4, wiping the data directory and starting it up again as n5.

**Expected behavior**
The new n5 should take on replicas, but it doesn't.  All of the ranges remain on the other 2 nodes.

**Additional data / screenshots**
<img width="1554" alt="Screenshot 2024-01-19 at 18 21 42" src="https://github.com/cockroachdb/cockroach/assets/28270695/857b58d6-445e-4dc5-80fb-2a3526de06b2">

**Additional context**
I'm aware this is an edge case as normally the dead nodes should be decommissioned, but the behaviour is surprising.

Jira issue: CRDB-35445

**Comment by nvanbenschoten** [comment] 2024-01-19 18:41
Local roachprod reproduction steps:
```bash
roachprod create local -n5
roachprod stage local cockroach

# start nodes 1, 2, and 3
roachprod start local:1-3
roachprod adminurl --open local:1
roachprod sql local:1 -- -e "SET CLUSTER SETTING server.time_until_store_dead = '1m15s'"

# kill node 3, add node 4
roachprod stop local:3
roachprod start local:4
# wait for upreplication...

# kill node 4, add node 5
roachprod stop local:4
roachprod start local:5
```

Ends up in the same state:
<img width="1481" alt="Screenshot 2024-01-19 at 1 40 58 PM" src="https://github.com/cockroachdb/cockroach/assets/5438456/dbd97bab-809a-4e4e-af07-062234c22445">

**Comment by nvanbenschoten** [comment] 2024-01-19 18:43
Passing a range through the replicate queue fails with the following trace:
```
TIMESTAMP | MESSAGE
-- | --
2024-01-19 18:41:18 | kv/kvserver/store.go:3679 [n2,s2,r3/2:/System/{NodeLive…-tsd}] running replicate.shouldQueue
2024-01-19 18:41:18 | kv/kvserver/allocator/plan/replicate.go:155 [n2,s2,r3/2:/System/{NodeLive…-tsd}] computing range action desc=r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, (n2,s2):2, (n4,s4):4, next=5, gen=8] config=range_min_bytes:134217728 range_max_bytes:536870912 gc_policy:<ttl_seconds:14400 > num_replicas:5
2024-01-19 18:41:18 | kv/kvserver/allocator/allocatorimpl/allocator.go:989 [n2,s2,r3/2:/System/{NodeLive…-tsd}] add voter - missing voter need=5, have=3, priority=10000.00
2024-01-19 18:41:18 | kv/kvserver/allocator/plan/replicate.go:164 [n2,s2,r3/2:/System/{NodeLive…-tsd}] repair needed (add voter), enqueuing
2024-01-19 18:41:18 | kv/kvserver/store.go:3681 [n2,s2,r3/2:/System/{NodeLive…-tsd}] shouldQueue=true, priority=10000.000000
2024-01-19 18:41:18 | kv/kvserver/store.go:3687 [n2,s2,r3/2:/System/{NodeLive…-tsd}] running replicate.process
2024-01-19 18:41:18 | kv/kvserver/store.go:3689 [n2,s2,r3/2:/System/{NodeLive…-tsd}] processed: false (err: avoid up-replicating to fragile quorum: 0 of 3 live stores are able to take a new replica for the range (4 already have a voter, 0 already have a non-voter); likely not enough nodes in cluster)
2024-01-19 18:41:18 | kv/kvserver/allocator/plan/replicate.go:258 [n2,s2,r3/2:/System/{NodeLive…-tsd}] planning range change desc=r3:/System/{NodeLivenessMax-tsd} [(n1,s1):1, (n2,s2):2, (n4,s4):4, next=5, gen=8] config=range_min_bytes:134217728 range_max_bytes:536870912 gc_policy:<ttl_seconds:14400 > num_replicas:5
2024-01-19 18:41:18 | kv/kvserver/allocator/allocatorimpl/allocator.go:989 [n2,s2,r3/2:/System/{NodeLive…-tsd}] add voter - missing voter need=5, have=3, priority=10000.00
2024-01-19 18:41:18 | kv/kvserver/allocator/plan/replicate.go:269 [n2,s2,r3/2:/System/{NodeLive…-tsd}] next replica action: add voter
2024-01-19 18:41:18 | kv/kvserver/allocator/allocatorimpl/allocator.go:1467 [n2,s2,r3/2:/System/{NodeLive…-tsd}] allocate voter: [ s5, valid:true, fulldisk:false, necessary:false, voterNecessary:false, diversity:0.25, ioOverloaded: false, ioOverload: 0.00, converges:0, balance:1, hasNonVoter:false, rangeCount:1, queriesPerSecond:0.89]
2024-01-19 18:41:18 | kv/kvserver/allocator/allocatorimpl/allocator.go:1469 [n2,s2,r3/2:/System/{NodeLive…-tsd}] add target: s5, valid:true, fulldisk:false, necessary:false, voterNecessary:false, diversity:0.25, ioOverloaded: false, ioOverload: 0.00, converges:0, balance:1, hasNonVoter:false, rangeCount:1, queriesPerSecond:0.89
2024-01-19 18:41:18 | kv/kvserver/allocator/allocatorimpl/allocator.go:1467 [n2,s2,r3/2:/System/{NodeLive…-tsd}] allocate voter: []
```

**Comment by nvanbenschoten** [comment] 2024-01-19 18:55
This appears to be related to the dynamic 5x replication on the system ranges. The one range that did move over was a timeseries range, which does not receive dynamic 5x replication.
![Screenshot 2024-01-19 at 1 53 02 PM](https://github.com/cockroachdb/cockroach/assets/5438456/84f56f8c-152f-4888-b319-c5d0d68b412e)

**Comment by nvanbenschoten** [comment] 2024-01-19 19:36
Most of the discussion is in https://cockroachlabs.slack.com/archives/C0KB9Q03D/p1705688925856429. This is confusing when looking at the individual replicas for each range, but makes sense when considering failure tolerance and our policy to respect 5x replication once a cluster grows to 5 nodes, regardless of whether those nodes are live or dead.

Closing as working as intended, but please feel free to open if you'd like to discuss further.

**Closed by nvanbenschoten** 2024-01-19 19:36 UTC
Labels: C-bug
