### ISSUE TITLE
ui: separate the range counts for better clarity

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#28193] opened 2018-08-02 10:57 UTC
When the "Total ranges" count is large, it runs into the under-replicated count.

![image](https://user-images.githubusercontent.com/642886/43579757-26b30174-9621-11e8-920d-ebae279ce3f6.png)

cc @piyush-singh @couchand for prioritization.

**Comment by couchand** [comment] 2018-08-02 13:28
I believe there's already an issue for this but I'm having trouble finding it.

**Comment by piyush-singh** [comment] 2018-08-02 17:57
This was something we had tackled earlier in the release cycle, managed to find the closed issue: #23669. This cluster is massive, so perhaps we didn't account for clusters with 1 million+ ranges.

**Comment by couchand** [comment] 2018-08-02 18:24
Ok, unless we hear that this is on master, I think it's a dupe of #23699 then.

**Closed by couchand** 2018-08-02 18:24 UTC
Labels: A-webui, C-enhancement, O-community, X-duplicate
