### ISSUE TITLE
perf: column family vs no column family on upsert vs update

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#17507] opened 2017-08-08 15:56 UTC
**QUESTION**

Trying to better understand the performance of characteristics of column family feature and quantify the tradeoffs on insert, update, delete, and select.   There are 5 groups of columns.  The intent is show that column family has greater throughput when multiple concurrent threads are updating separate column families.  
 
1. Please supply the header (i.e. the first few lines) of your most recent

```
$ cockroach version
Build Tag:    v1.1-alpha.20170803
Build Time:   2017/08/03 17:19:14
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  1e88c32588fd3d7cad826437c18b349fd70e4762
Build Type:   release

$ cockroach version
Build Tag:    v1.0.4
Build Time:   2017/07/27 17:52:31
Distribution: CCL
Platform:     darwin amd64
Go Version:   go1.8.3
C Compiler:   4.2.1 Compatible Clang 3.8.0 (tags/RELEASE_380/final)
Build SHA-1:  5b757262d33d814bda1deb2af20161a1f7749df3
Build Type:   release

$ roachdemo -n 3

$ cockroach sql --insecure <<EOF
create database md;
EOF
```

2. Please describe the issue you observed:

- What did you do?

Two separate http://jmeter.apache.org plans are attached.

[comfam-jmeter-test.zip](https://github.com/cockroachdb/cockroach/files/1208694/comfam-jmeter-test.zip)

colfam-update-cr.jmx does updates
colfam-upsert-cr.jmx does upsets

- What did you expect to see?

column family to product better throughput

- What did you see instead?

No column family has better throughput

on CRDB 1.0.4 not having column family has 2x throughput using update and insert on conflict
on CRDB 1.1-alpha.20170720,  not having column family has slightly better throughput, but the throughput has regressed compared to 1.0.4

[colfam-results.zip](https://github.com/cockroachdb/cockroach/files/1208742/colfam-results.zip)

**Comment by robert-s-lee** [comment] 2017-08-08 16:03
root@:26257/md> set tracing=on;
SET
root@:26257/md> UPDATE tblfam set (state1,state1_access) = (1,now()) where id = 1
             -> ;
UPDATE 1
root@:26257/md> SET TRACING = off; SHOW TRACE FOR SESSION;
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-----------------------------------+-------+
|            timestamp             |        age         |                                                                                                  message                                                                                                  |            context            |             operation             | span  |
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-----------------------------------+-------+
| 2017-08-08 16:00:07.528608+00:00 | 0s                 | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (0,0) |
| 2017-08-08 16:00:07.528703+00:00 | 95µs631ns          | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (0,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208007.528617152,0 orig=1502208007.528617152,0 max=0.000000000,0 wto=false rop=false seq=0 |                               |                                   |       |
| 2017-08-08 16:00:07.528838+00:00 | 230µs433ns         | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (1,0) |
| 2017-08-08 16:00:07.528867+00:00 | 259µs192ns         | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW TRANSACTION STATUS                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (1,0) |
| 2017-08-08 16:00:07.52889+00:00  | 282µs755ns         | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (1,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208007.528845045,0 orig=1502208007.528845045,0 max=0.000000000,0 wto=false rop=false seq=0 |                               |                                   |       |
| 2017-08-08 16:00:07.529025+00:00 | 417µs611ns         | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (2,0) |
| 2017-08-08 16:00:07.52904+00:00  | 432µs395ns         | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW database                                                                                                                                            | [client=[::1]                 | sql txn implicit                  | (2,0) |
| 2017-08-08 16:00:07.529184+00:00 | 576µs155ns         | [client=[::1]:58067,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause                                                                             | [client=[::1]                 | sql txn implicit                  | (2,0) |
| 2017-08-08 16:00:07.529217+00:00 | 609µs235ns         | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (2,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208007.529032402,0 orig=1502208007.529032402,0 max=0.000000000,0 wto=false rop=false seq=0 |                               |                                   |       |
| 2017-08-08 16:00:21.096741+00:00 | 13s568ms133µs196ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.09678+00:00  | 13s568ms172µs337ns | [client=[::1]:58067,user=root,n1] executing 1/1: UPDATE tblfam SET (state1, state1_access) = (1, now()) WHERE id = 1                                                                                      | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.096835+00:00 | 13s568ms226µs874ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (3,0) |
|                                  |                    | txn: "unnamed" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208021.096804611,0 orig=1502208021.096804611,0 max=0.000000000,0 wto=false rop=false seq=0          |                               |                                   |       |
| 2017-08-08 16:00:21.096847+00:00 | 13s568ms239µs393ns | [client=[::1]:58067,user=root,n1] added table 'tblfam' to table collection                                                                                                                                | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097043+00:00 | 13s568ms434µs869ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (3,0) |
|                                  |                    | txn: "unnamed" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208021.097028780,0 orig=1502208021.097028780,0 max=0.000000000,0 wto=false rop=false seq=0          |                               |                                   |       |
| 2017-08-08 16:00:21.097048+00:00 | 13s568ms439µs900ns | [client=[::1]:58067,user=root,n1] found table in table collection for table 'tblfam'                                                                                                                      | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097172+00:00 | 13s568ms564µs11ns  | [client=[::1]:58067,user=root,n1] query not supported for distSQL: mutations not supported                                                                                                                | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097215+00:00 | 13s568ms607µs170ns | [client=[::1]:58067,user=root,n1] querying next range at /Table/52/1/1                                                                                                                                    | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097249+00:00 | 13s568ms641µs161ns | [client=[::1]:58067,user=root,n1] r13: sending batch 1 Scan to (n1,s1):1                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097267+00:00 | 13s568ms659µs749ns | [client=[::1]:58067,user=root,n1] sending request to local server                                                                                                                                         | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097284+00:00 | 13s568ms675µs963ns | === SPAN START: /cockroach.roachpb.Internal/Batch ===                                                                                                                                                     | NULL                          | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097289+00:00 | 13s568ms681µs534ns | 1 Scan                                                                                                                                                                                                    | [n1]                          | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097292+00:00 | 13s568ms684µs24ns  | read has no clock uncertainty                                                                                                                                                                             | [n1]                          | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097298+00:00 | 13s568ms690µs230ns | executing 1 requests                                                                                                                                                                                      | [n1,s1]                       | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097306+00:00 | 13s568ms698µs290ns | read-only path                                                                                                                                                                                            | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097313+00:00 | 13s568ms705µs573ns | command queue                                                                                                                                                                                             | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097321+00:00 | 13s568ms713µs622ns | waiting for read lock                                                                                                                                                                                     | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.09744+00:00  | 13s568ms831µs991ns | read completed                                                                                                                                                                                            | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:00:21.097534+00:00 | 13s568ms926µs732ns | [client=[::1]:58067,user=root,n1] querying next range at /Table/52/1/1/0                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097559+00:00 | 13s568ms951µs403ns | [client=[::1]:58067,user=root,n1] r13: sending batch 1 Put, 1 BeginTxn, 1 EndTxn to (n1,s1):1                                                                                                             | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097572+00:00 | 13s568ms963µs964ns | [client=[::1]:58067,user=root,n1] sending request to local server                                                                                                                                         | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.097583+00:00 | 13s568ms975µs534ns | === SPAN START: /cockroach.roachpb.Internal/Batch ===                                                                                                                                                     | NULL                          | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097589+00:00 | 13s568ms981µs649ns | 1 Put, 1 BeginTxn, 1 EndTxn                                                                                                                                                                               | [n1]                          | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097591+00:00 | 13s568ms983µs496ns | read has no clock uncertainty                                                                                                                                                                             | [n1]                          | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097596+00:00 | 13s568ms988µs154ns | executing 3 requests                                                                                                                                                                                      | [n1,s1]                       | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097601+00:00 | 13s568ms993µs85ns  | read-write path                                                                                                                                                                                           | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097611+00:00 | 13s569ms2µs844ns   | command queue                                                                                                                                                                                             | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.097646+00:00 | 13s569ms37µs905ns  | applied timestamp cache                                                                                                                                                                                   | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.09769+00:00  | 13s569ms82µs305ns  | evaluated request                                                                                                                                                                                         | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.0977+00:00   | 13s569ms92µs22ns   | acquired {raft,replica}mu                                                                                                                                                                                 | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.104468+00:00 | 13s575ms860µs487ns | applying command                                                                                                                                                                                          | [n1,s1,r13/1:/{Table/52-Max}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:00:21.104674+00:00 | 13s576ms66µs68ns   | [client=[::1]:58067,user=root,n1] coordinator stops                                                                                                                                                       | [client=[::1]                 | sql txn implicit                  | (3,0) |
| 2017-08-08 16:00:21.105001+00:00 | 13s576ms393µs690ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (4,0) |
| 2017-08-08 16:00:21.105026+00:00 | 13s576ms418µs386ns | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW TRANSACTION STATUS                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (4,0) |
| 2017-08-08 16:00:21.105065+00:00 | 13s576ms457µs398ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (4,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208021.105013024,0 orig=1502208021.105013024,0 max=0.000000000,0 wto=false rop=false seq=0 |                               |                                   |       |
| 2017-08-08 16:00:21.105226+00:00 | 13s576ms618µs176ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (5,0) |
| 2017-08-08 16:00:21.105243+00:00 | 13s576ms635µs418ns | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW database                                                                                                                                            | [client=[::1]                 | sql txn implicit                  | (5,0) |
| 2017-08-08 16:00:21.105424+00:00 | 13s576ms816µs762ns | [client=[::1]:58067,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause                                                                             | [client=[::1]                 | sql txn implicit                  | (5,0) |
| 2017-08-08 16:00:21.105468+00:00 | 13s576ms860µs442ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]                 | sql txn implicit                  | (5,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208021.105233704,0 orig=1502208021.105233704,0 max=0.000000000,0 wto=false rop=false seq=0 |                               |                                   |       |
| 2017-08-08 16:00:31.486367+00:00 | 23s957ms759µs556ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                          | sql txn implicit                  | (6,0) |
| 2017-08-08 16:00:31.486397+00:00 | 23s957ms788µs966ns | [client=[::1]:58067,user=root,n1] executing 1/1: SET tracing = 'off'                                                                                                                                      | [client=[::1]                 | sql txn implicit                  | (6,0) |
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------+-----------------------------------+-------+
(50 rows)


root@:26257/md> SET tracing = 'on';
SET
root@:26257/md> UPDATE tblnofam set (state1,state1_access) = (1,now()) where id = 1
             -> ;
UPDATE 1
root@:26257/md> SET tracing = 'off'; SHOW TRACE FOR SESSION;
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+-----------------------------------+-------+
|            timestamp             |        age         |                                                                                                  message                                                                                                  |           context           |             operation             | span  |
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+-----------------------------------+-------+
| 2017-08-08 16:01:28.960283+00:00 | 0s                 | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (0,0) |
| 2017-08-08 16:01:28.96037+00:00  | 87µs13ns           | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (0,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208088.960291971,0 orig=1502208088.960291971,0 max=0.000000000,0 wto=false rop=false seq=0 |                             |                                   |       |
| 2017-08-08 16:01:28.960509+00:00 | 226µs133ns         | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (1,0) |
| 2017-08-08 16:01:28.960522+00:00 | 239µs32ns          | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW TRANSACTION STATUS                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (1,0) |
| 2017-08-08 16:01:28.960544+00:00 | 261µs228ns         | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (1,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208088.960514720,0 orig=1502208088.960514720,0 max=0.000000000,0 wto=false rop=false seq=0 |                             |                                   |       |
| 2017-08-08 16:01:28.960721+00:00 | 437µs954ns         | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (2,0) |
| 2017-08-08 16:01:28.960734+00:00 | 451µs197ns         | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW database                                                                                                                                            | [client=[::1]               | sql txn implicit                  | (2,0) |
| 2017-08-08 16:01:28.960907+00:00 | 624µs155ns         | [client=[::1]:58067,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause                                                                             | [client=[::1]               | sql txn implicit                  | (2,0) |
| 2017-08-08 16:01:28.960946+00:00 | 663µs447ns         | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (2,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208088.960727261,0 orig=1502208088.960727261,0 max=0.000000000,0 wto=false rop=false seq=0 |                             |                                   |       |
| 2017-08-08 16:01:46.175732+00:00 | 17s215ms448µs745ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.175768+00:00 | 17s215ms484µs694ns | [client=[::1]:58067,user=root,n1] executing 1/1: UPDATE tblnofam SET (state1, state1_access) = (1, now()) WHERE id = 1                                                                                    | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.175817+00:00 | 17s215ms533µs776ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (3,0) |
|                                  |                    | txn: "unnamed" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208106.175788032,0 orig=1502208106.175788032,0 max=0.000000000,0 wto=false rop=false seq=0          |                             |                                   |       |
| 2017-08-08 16:01:46.175827+00:00 | 17s215ms544µs59ns  | [client=[::1]:58067,user=root,n1] added table 'tblnofam' to table collection                                                                                                                              | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176022+00:00 | 17s215ms739µs73ns  | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (3,0) |
|                                  |                    | txn: "unnamed" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208106.176008027,0 orig=1502208106.176008027,0 max=0.000000000,0 wto=false rop=false seq=0          |                             |                                   |       |
| 2017-08-08 16:01:46.176028+00:00 | 17s215ms744µs914ns | [client=[::1]:58067,user=root,n1] found table in table collection for table 'tblnofam'                                                                                                                    | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176178+00:00 | 17s215ms894µs947ns | [client=[::1]:58067,user=root,n1] query not supported for distSQL: mutations not supported                                                                                                                | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.17622+00:00  | 17s215ms936µs912ns | [client=[::1]:58067,user=root,n1] querying next range at /Table/51/1/1                                                                                                                                    | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176253+00:00 | 17s215ms970µs407ns | [client=[::1]:58067,user=root,n1] r12: sending batch 1 Scan to (n1,s1):1                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176273+00:00 | 17s215ms989µs630ns | [client=[::1]:58067,user=root,n1] sending request to local server                                                                                                                                         | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176289+00:00 | 17s216ms5µs992ns   | === SPAN START: /cockroach.roachpb.Internal/Batch ===                                                                                                                                                     | NULL                        | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176295+00:00 | 17s216ms11µs556ns  | 1 Scan                                                                                                                                                                                                    | [n1]                        | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176298+00:00 | 17s216ms15µs187ns  | read has no clock uncertainty                                                                                                                                                                             | [n1]                        | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176303+00:00 | 17s216ms20µs492ns  | executing 1 requests                                                                                                                                                                                      | [n1,s1]                     | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176311+00:00 | 17s216ms28µs122ns  | read-only path                                                                                                                                                                                            | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176318+00:00 | 17s216ms35µs522ns  | command queue                                                                                                                                                                                             | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176326+00:00 | 17s216ms43µs319ns  | waiting for read lock                                                                                                                                                                                     | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176396+00:00 | 17s216ms112µs599ns | read completed                                                                                                                                                                                            | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,1) |
| 2017-08-08 16:01:46.176487+00:00 | 17s216ms204µs474ns | [client=[::1]:58067,user=root,n1] querying next range at /Table/51/1/1/0                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176513+00:00 | 17s216ms229µs708ns | [client=[::1]:58067,user=root,n1] r12: sending batch 1 Put, 1 BeginTxn, 1 EndTxn to (n1,s1):1                                                                                                             | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176525+00:00 | 17s216ms242µs201ns | [client=[::1]:58067,user=root,n1] sending request to local server                                                                                                                                         | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.176537+00:00 | 17s216ms253µs698ns | === SPAN START: /cockroach.roachpb.Internal/Batch ===                                                                                                                                                     | NULL                        | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176542+00:00 | 17s216ms259µs229ns | 1 Put, 1 BeginTxn, 1 EndTxn                                                                                                                                                                               | [n1]                        | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176544+00:00 | 17s216ms260µs927ns | read has no clock uncertainty                                                                                                                                                                             | [n1]                        | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176548+00:00 | 17s216ms265µs450ns | executing 3 requests                                                                                                                                                                                      | [n1,s1]                     | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176553+00:00 | 17s216ms270µs120ns | read-write path                                                                                                                                                                                           | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176562+00:00 | 17s216ms279µs81ns  | command queue                                                                                                                                                                                             | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.1766+00:00   | 17s216ms316µs615ns | applied timestamp cache                                                                                                                                                                                   | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176645+00:00 | 17s216ms361µs735ns | evaluated request                                                                                                                                                                                         | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.176654+00:00 | 17s216ms371µs546ns | acquired {raft,replica}mu                                                                                                                                                                                 | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.18078+00:00  | 17s220ms497µs464ns | applying command                                                                                                                                                                                          | [n1,s1,r12/1:/Table/5{1-2}] | /cockroach.roachpb.Internal/Batch | (3,2) |
| 2017-08-08 16:01:46.180932+00:00 | 17s220ms649µs402ns | [client=[::1]:58067,user=root,n1] coordinator stops                                                                                                                                                       | [client=[::1]               | sql txn implicit                  | (3,0) |
| 2017-08-08 16:01:46.181182+00:00 | 17s220ms899µs275ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (4,0) |
| 2017-08-08 16:01:46.181201+00:00 | 17s220ms918µs151ns | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW TRANSACTION STATUS                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (4,0) |
| 2017-08-08 16:01:46.181235+00:00 | 17s220ms952µs398ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (4,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208106.181192083,0 orig=1502208106.181192083,0 max=0.000000000,0 wto=false rop=false seq=0 |                             |                                   |       |
| 2017-08-08 16:01:46.181361+00:00 | 17s221ms77µs759ns  | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (5,0) |
| 2017-08-08 16:01:46.181373+00:00 | 17s221ms89µs919ns  | [client=[::1]:58067,user=root,n1] executing 1/1: SHOW database                                                                                                                                            | [client=[::1]               | sql txn implicit                  | (5,0) |
| 2017-08-08 16:01:46.181525+00:00 | 17s221ms242µs206ns | [client=[::1]:58067,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause                                                                             | [client=[::1]               | sql txn implicit                  | (5,0) |
| 2017-08-08 16:01:46.181557+00:00 | 17s221ms274µs467ns | [client=[::1]:58067,user=root,n1] client.Txn did AutoCommit. err: <nil>␤                                                                                                                                  | [client=[::1]               | sql txn implicit                  | (5,0) |
|                                  |                    | txn: "sql txn implicit" id=<nil> key=/Min rw=false pri=0.00000000 iso=SERIALIZABLE stat=COMMITTED epo=0 ts=1502208106.181366688,0 orig=1502208106.181366688,0 max=0.000000000,0 wto=false rop=false seq=0 |                             |                                   |       |
| 2017-08-08 16:01:50.44659+00:00  | 21s486ms306µs676ns | === SPAN START: sql txn implicit ===                                                                                                                                                                      | NULL                        | sql txn implicit                  | (6,0) |
| 2017-08-08 16:01:50.44662+00:00  | 21s486ms336µs813ns | [client=[::1]:58067,user=root,n1] executing 1/1: SET tracing = 'off'                                                                                                                                      | [client=[::1]               | sql txn implicit                  | (6,0) |
+----------------------------------+--------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------+-----------------------------------+-------+

**Comment by knz** [comment] 2017-08-08 16:21
In the trace output I see that the update in both cases is taking approximately 6ms.
Also in both cases as expected a single K/V pair is affected by the update.

Not sure where the overall throughput difference is coming from then. The trace doesn't really tell.

**Comment by knz** [comment] 2017-08-08 16:22
cc @bdarnell @danhhz

**Comment by danhhz** [comment] 2017-08-08 16:39
Oh this is an interesting idea! I'd never thought of using column families to reduce contention.

If a single k/v is affected in each, then it sounds like column families are working correctly. Which means this is more a question for @cockroachdb/core

**Comment by bdarnell** [comment] 2017-08-08 17:04
We're only writing a single key, but what about the Scan? if the scan is covering all the column families, then that might explain the difference (the scan looks fast in these single traces, but maybe it prevents concurrency in the the jmeter runs). Can we get the actual keys touched by these operations?

**Comment by robert-s-lee** [comment] 2017-08-08 17:47
What is the procedure to retrieve the actual keys touched?

**Comment by bdarnell** [comment] 2017-08-08 17:52
It's supposed to be `SHOW KV TRACE FOR UPDATE...` but that wasn't working for you earlier.

**Comment by robert-s-lee** [comment] 2017-08-10 14:28
Full repro script is at https://github.com/robert-s-lee/crdb-column-family

comparison ![graph](https://github.com/robert-s-lee/crdb-column-family/blob/master/crdb-column-family.png)

**Comment by jordanlewis** [comment] 2018-02-05 22:45
I can't reproduce this locally. I see higher performance on the column family schema than the no column family one.

I couldn't get Robert's repro script to work, so I just ran the JMeter configuration he provided. It shows that the column family version gives about 60 ops/s per worker, with 5 workers, and the no column family version gives about 47 ops/s per worker with 5 workers.

Going to close this - @robert-s-lee let me know if you have any further questions about this.

**Closed by jordanlewis** 2018-02-05 22:45 UTC
Labels: investigation, performance
