### ISSUE TITLE
*log.safeError: store.go:1820: *roachpb.RaftGroupDeletedError

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#22596] opened 2018-02-12 18:15 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/459269626/

```
*log.safeError: store.go:1820: *roachpb.RaftGroupDeletedError
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 718, in handleReplicatedEvalResult
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 981, in handleEvalResultRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4480, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3481, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3183, in processRaftRequest
...
(4 additional frame(s) were not displayed)

store.go:1820: *roachpb.RaftGroupDeletedError
```

**Comment by BramGruneir** [comment] 2018-02-12 18:18
@bdarnell not sure if this is a real issue, assigning to you for triage.

**Comment by bdarnell** [comment] 2018-02-13 17:47
Looks like a duplicate of #21146.

**Closed by bdarnell** 2018-02-13 17:47 UTC
