### ISSUE TITLE
conn_executor.go:521: panic while executing 1 statements: SELECT * FROM (SELECT DISTINCT (_, _), _, _, _ FROM _ WHERE _ = _ ORDER BY (_, _) LIMIT _) AS _ ORDER BY _._ DESC

### ISSUE THREAD

**Issue by solongordon** [cockroachdb/cockroach#26602] opened 2018-06-11 18:26 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/577428353
```
*log.safeError: conn_executor.go:521: panic while executing 1 statements: SELECT DISTINCT _._, _._, _._ FROM _ AS _ CROSS JOIN _ AS _ WHERE _._ = _._ LIMIT _: caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "runtime/asm_amd64.s", line 573, in call32
  File "runtime/panic.go", line 505, in gopanic
  File "github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go", line 393, in AddRendering
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 948, in selectRenders
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1898, in createPlanForNode
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1894, in createPlanForNode
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go", line 1934, in createPlanForNode
  File "github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go", line 526, in PlanAndRun
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 665, in execWithDistSQLEngine
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 573, in dispatchToExecutionEngine
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 342, in execStmtInOpenState
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go", line 83, in execStmt
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 911, in run
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 491, in ServeConn
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go", line 260, in func3
```

**Comment by solongordon** [comment] 2018-06-11 18:26
Possibly related to https://github.com/cockroachdb/cockroach/issues/25279?

**Comment by jordanlewis** [comment] 2018-08-21 15:42
Closing as we can't reproduce this.

**Closed by jordanlewis** 2018-08-21 15:42 UTC
Labels: A-sql-execution, C-bug, S-2-temp-unavailability
