### ISSUE TITLE
Failed tests (12525): TestNodeStatus 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4248] opened 2016-02-09 03:39 UTC
The following test appears to have failed:

[#12525](https://circleci.com/gh/cockroachdb/cockroach/12525):

```
I0209 03:34:40.324152 116 raft/raft.go:500  [group 4] 1 became leader at term 6
I0209 03:34:40.430272 116 server/server.go:330  node 1 status: {"desc":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:35900"},"attrs":{}},"store_ids":[1],"range_count":4,"started_at":1454988879851398944,"updated_at":1454988880426302506,"stats":{"last_update_nanos":1454988880334219207,"intent_age":0,"gc_bytes_age":89,"live_bytes":10354,"live_count":56,"key_bytes":1749,"key_count":56,"val_bytes":8784,"val_count":62,"intent_bytes":2001,"intent_count":33,"sys_bytes":1955,"sys_count":1},"leader_range_count":0,"replicated_range_count":0,"available_range_count":0}
[node --host=127.0.0.1 --port=35900 --certs=/tmp/cli-test896090002 status 1]
[node --host=127.0.0.1 --port=35900 --certs=/tmp/cli-test896090002 status]
I0209 03:34:40.644113 116 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestNodeStatus (0.85s)
	cli_test.go:822: value for live_bytes (10354) greater than max (10000)
	cli_test.go:822: value for live_bytes (10354) greater than max (10000)
=== RUN   TestGenMan
Generated CockroachDB man pages in /tmp/TestGenMan060995017/
--- PASS: TestGenMan (0.21s)
	<autogenerated>:28: prior leak detected, leaktest disabled
=== RUN   TestGenAutocomplete
Generated bash completion file /tmp/TestGenAutoComplete055701140/cockroach.bash
--- PASS: TestGenAutocomplete (0.05s)
	<autogenerated>:28: prior leak detected, leaktest disabled
--
W0209 03:34:56.166650 116 storage/replica.go:1707  failed to push during intent resolution: conflicting intents on [/Meta2/Table/13 /Meta2/Max]: resolved? false
[node --host=127.0.0.1 --port=48717 --certs=/tmp/cli-test490063182 ls]
[node --host=127.0.0.1 --port=48717 --certs=/tmp/cli-test490063182 status 10000]
Error: Error: node 10000 doesn't exist
--- PASS: Example_node (0.82s)
FAIL
FAIL	github.com/cockroachdb/cockroach/cli	17.481s
=== RUN   TestClientTxnSequenceNumber
--- PASS: TestClientTxnSequenceNumber (0.00s)
=== RUN   TestTxnRequestTxnTimestamp
--- PASS: TestTxnRequestTxnTimestamp (0.01s)
=== RUN   TestTxnResetTxnOnAbort
--- PASS: TestTxnResetTxnOnAbort (0.01s)
=== RUN   TestTransactionConfig
--- PASS: TestTransactionConfig (0.00s)
=== RUN   TestCommitReadOnlyTransaction
--- PASS: TestCommitReadOnlyTransaction (0.01s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-09 03:46
Dupe of #4239

**Closed by bdarnell** 2016-02-09 03:46 UTC
Labels: test-failure, TestNodeStatus
