### ISSUE TITLE
Test failure in CI build 7242

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2453] opened 2015-09-10 16:27 UTC
The following test appears to have failed:

[#7242](https://circleci.com/gh/cockroachdb/cockroach/7242):

```
E0910 16:27:46.287042 789 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:27:46.586953 789 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:27:46.886971 789 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:27:47.186964 789 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:27:47.486962 789 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
panic: test timed out after 5m0s

goroutine 3808 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1719ec0, 0x1d0f5a0, 0x1f, 0x1f, 0x1428501)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:268 +0x21b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820676180, 0xc820204640)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x70
FAIL	github.com/cockroachdb/cockroach/server	300.061s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.01s)
=== RUN   TestRuntimeStatRecorder
I0910 16:22:52.957475 797 server/status/runtime.go:118  runtime stats: 10 goroutines, 5.19MiB active, 50000000.00cgo/sec, 383800.00/115140.00 %(u/s)time, 3878.37 %gc (1x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by BramGruneir** [comment] 2015-09-10 17:06
dupe of #2440

**Closed by BramGruneir** 2015-09-10 17:06 UTC
Labels: test-failure
