### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestForbiddenDeps

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6489] opened 2016-05-04 11:34 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/3f5b8dbe20282632850030143fa9ed8440cd2e53

Stress build found a failed test:

```
=== RUN   TestForbiddenDeps
--- FAIL: TestForbiddenDeps (0.00s)
	build.go:69: cannot find package "github.com/cockroachdb/cockroach/kv" in any of:
			/usr/local/go/src/github.com/cockroachdb/cockroach/kv (from $GOROOT)
			($GOPATH not set)
FAIL


ERROR: exit status 1
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
1 runs completed, 1 failures, over 22s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-05 22:31
Duplicate of #6488

**Closed by bdarnell** 2016-05-05 22:31 UTC
Labels: Robot, test-failure
