### ISSUE TITLE
sql: pg_am table not implemented

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#31761] opened 2018-10-23 19:28 UTC
See https://www.postgresql.org/docs/9.5/static/catalog-pg-am.html (and note that this table changes between 9.5 and 10.0). Needed for hibernate test org.hibernate.test.schemaupdate.MigrationTest.testIndexCreationViaSchemaUpdate.

**Comment by jordanlewis** [comment] 2018-12-16 16:36
Possible duplicate of #32624.

**Comment by BramGruneir** [comment] 2018-12-18 22:55
Indeed it is.

**Closed by BramGruneir** 2018-12-18 22:55 UTC
Labels: A-sql-hibernate, A-sql-pgcompat, C-enhancement
