### ISSUE TITLE
sql/stats: forecast of stale stats supersedes fresh stats

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#103958] opened 2023-05-26 16:22 UTC
**Describe the problem**
It's been shown in customer issues that the optimizer can underestimate row count if there are old statistics entries with a zero row count combined with entries of a non-zero row count.  Removing the zero row count entries corrects the estimation error as seen in support issue https://github.com/cockroachlabs/support/issues/2322.

This issue is opened to teach the optimizer to ignore the older zero row count stats entries when there are other, newer non-zero row count entries, or otherwise correct its estimation logic.

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**
See https://github.com/cockroachlabs/support/issues/2322

**Environment:**
 - CockroachDB version 22.1.x, 22.2.x

**Additional context**
What was the impact?
Costly full scans or incorrect index usage by the optimizer

Jira issue: CRDB-28271

**Comment by michae2** [comment] 2023-05-30 18:49
[triage meeting] assigning to Mark to dig into this more

**Comment by michae2** [comment] 2023-05-31 19:51
I think I see what is going on here, working on a repro. This might already be fixed by https://github.com/cockroachdb/cockroach/pull/85586

**Comment by michae2** [comment] 2023-05-31 20:23
The problem is that we're producing a statistics forecast based on some stale multi-column statistics that haven't been cleaned up, and the forecast overrides the latest collected statistics.

Here's a repro:

```sql
-- stats injection below is a little easier without histograms
SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;

CREATE TABLE ab (a INT PRIMARY KEY, b INT) WITH (sql_stats_automatic_collection_enabled = false);

-- Now imagine that the following has occurred:

-- we think we need an index at first
-- CREATE INDEX ON ab (b, a);
-- INSERT INTO ab VALUES (0, 0);
-- then a few automatic stats collections occur

-- then we decide we don't need that index any more:
-- DROP INDEX ab_b_a_idx;

-- then we add data to the table:
-- INSERT INTO ab SELECT generate_series(1, 999), 1;
-- another stats collection occurs

-- add more data
-- INSERT INTO ab SELECT generate_series(1000, 1999), 2;
-- another stats collection occurs

-- add yet more data
-- INSERT INTO ab SELECT generate_series(2000, 2999), 3;
-- yet another stats collection occurs

-- use this to simulate all of those stats collections to simplify the repro:
  ALTER TABLE ab INJECT STATISTICS '[
      {
          "avg_size": 1,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-01 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 3,
          "columns": [
              "a",
              "b"
          ],
          "created_at": "2023-01-01 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-01 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 1,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-02 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 3,
          "columns": [
              "a",
              "b"
          ],
          "created_at": "2023-01-02 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-02 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 1,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-03 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 3,
          "columns": [
              "a",
              "b"
          ],
          "created_at": "2023-01-03 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-03 00:00:00",
          "distinct_count": 1,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1
      },
      {
          "avg_size": 1,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-04 00:00:00",
          "distinct_count": 1000,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1000
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-04 00:00:00",
          "distinct_count": 2,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 1000
      },
      {
          "avg_size": 3,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-05 00:00:00",
          "distinct_count": 2000,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2000
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-05 00:00:00",
          "distinct_count": 3,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 2000
      },
      {
          "avg_size": 3,
          "columns": [
              "a"
          ],
          "created_at": "2023-01-06 00:00:00",
          "distinct_count": 3000,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 3000
      },
      {
          "avg_size": 2,
          "columns": [
              "b"
          ],
          "created_at": "2023-01-06 00:00:00",
          "distinct_count": 4,
          "histo_col_type": "",
          "name": "__auto__",
          "null_count": 0,
          "row_count": 3000
      }
  ]';

EXPLAIN SELECT * FROM ab;
```

We can see that there is a forecast for `{a,b}` based on those stale multi-column statistics:

```
demo@127.0.0.1:26257/defaultdb> SHOW STATISTICS FOR TABLE ab WITH FORECAST;
  statistics_name | column_names |       created       | row_count | distinct_count | null_count | avg_size | histogram_id
------------------+--------------+---------------------+-----------+----------------+------------+----------+---------------
  __auto__        | {a}          | 2023-01-01 00:00:00 |         1 |              1 |          0 |        1 |         NULL
  __auto__        | {a,b}        | 2023-01-01 00:00:00 |         1 |              1 |          0 |        3 |         NULL
  __auto__        | {b}          | 2023-01-01 00:00:00 |         1 |              1 |          0 |        2 |         NULL
  __auto__        | {a}          | 2023-01-02 00:00:00 |         1 |              1 |          0 |        1 |         NULL
  __auto__        | {a,b}        | 2023-01-02 00:00:00 |         1 |              1 |          0 |        3 |         NULL
  __auto__        | {b}          | 2023-01-02 00:00:00 |         1 |              1 |          0 |        2 |         NULL
  __auto__        | {a}          | 2023-01-03 00:00:00 |         1 |              1 |          0 |        1 |         NULL
  __auto__        | {a,b}        | 2023-01-03 00:00:00 |         1 |              1 |          0 |        3 |         NULL
  __auto__        | {b}          | 2023-01-03 00:00:00 |         1 |              1 |          0 |        2 |         NULL
  __auto__        | {a}          | 2023-01-04 00:00:00 |      1000 |           1000 |          0 |        1 |         NULL
  __auto__        | {b}          | 2023-01-04 00:00:00 |      1000 |              2 |          0 |        2 |         NULL
  __auto__        | {a}          | 2023-01-05 00:00:00 |      2000 |           2000 |          0 |        3 |         NULL
  __auto__        | {b}          | 2023-01-05 00:00:00 |      2000 |              3 |          0 |        2 |         NULL
  __auto__        | {a}          | 2023-01-06 00:00:00 |      3000 |           3000 |          0 |        3 |         NULL
  __auto__        | {b}          | 2023-01-06 00:00:00 |      3000 |              4 |          0 |        2 |         NULL
  __forecast__    | {a,b}        | 2023-01-07 00:00:00 |         1 |              1 |          0 |        3 |         NULL
(16 rows)
```

If we tell the optimizer not to use forecasts the problem goes away:

```
demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT * FROM ab;
                                                        info
---------------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    estimated row count: 1 (100% of the table; stats collected 146 days ago; using stats forecast for 145 days ago)
    table: ab@ab_pkey
    spans: FULL SCAN
(7 rows)


Time: 1ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> SET optimizer_use_forecasts = false;
SET


Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/defaultdb> EXPLAIN SELECT * FROM ab;
                                       info
----------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • scan
    estimated row count: 3,000 (100% of the table; stats collected 146 days ago)
    table: ab@ab_pkey
    spans: FULL SCAN
(7 rows)


Time: 1ms total (execution 1ms / network 0ms)
```

**Closed** 2023-06-01 19:55 UTC
Labels: C-bug, A-sql-table-stats, T-sql-queries
