### ISSUE TITLE
sql: investigate failures in Hibernate's ConstructorResultNativeQuery

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#26803] opened 2018-06-18 18:48 UTC
For example, this following fails:

First some setup:
```sql
create table person (
       id int4 not null,
        birthDate timestamp,
        p_name varchar(255),
        p_weight int4,
        primary key (id)
    );
insert into person (birthDate, p_name, p_weight, id)                                                                                                                                     values ('2018-06-13 21:19:59', 'John', 0, 1);
```

Then in java:
```java
List results = em.createNativeQuery(
  "select p.id, p.p_name from person p order by p.p_name",
  "person-id-and-name"
).getResultList();
```

Produces the following stack trace:
```
java.lang.IllegalArgumentException: Could not locate appropriate constructor on class : org.hibernate.jpa.test.query.ConstructorResultNativeQueryTest$Person
	at org.hibernate.loader.custom.ConstructorResultColumnProcessor.resolveConstructor(ConstructorResultColumnProcessor.java:92)
	at org.hibernate.loader.custom.ConstructorResultColumnProcessor.performDiscovery(ConstructorResultColumnProcessor.java:45)
	at org.hibernate.loader.custom.CustomLoader.autoDiscoverTypes(CustomLoader.java:494)
	at org.hibernate.loader.Loader.processResultSet(Loader.java:2213)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2169)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1930)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1892)
	at org.hibernate.loader.Loader.doQuery(Loader.java:937)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:340)
	at org.hibernate.loader.Loader.doList(Loader.java:2689)
	at org.hibernate.loader.Loader.doList(Loader.java:2672)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2506)
	at org.hibernate.loader.Loader.list(Loader.java:2501)
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338)
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2223)
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1053)
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:168)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1506)
	at org.hibernate.query.Query.getResultList(Query.java:146)
	at org.hibernate.jpa.test.query.ConstructorResultNativeQueryTest.testConstructorResultNativeQuery(ConstructorResultNativeQueryTest.java:160)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.hibernate.testing.junit4.ExtendedFrameworkMethod.invokeExplosively(ExtendedFrameworkMethod.java:45)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

Here are some tests that fail:

- org.hibernate.jpa.test.query.ConstructorResultNativeQueryTest 
  - testConstructorResultNativeQuery
  - testConstructorResultNativeQuerySpecifyingType
  - testMultipleConstructorResultNativeQuery

**Comment by knz** [comment] 2018-06-19 15:09
Please link to docs that explain what "native queries" are and how they are implemented with postgres. Only then can we qualify what to do here.

**Comment by knz** [comment] 2018-06-30 01:59
@BramGruneir This issue is improperly qualified. It does neither state what is the deviation (difference between expected behavior and actual behavior) nor what action items should be carried out.

Unless you provide either (preferably both), we can't do anything with this.

**Comment by BramGruneir** [comment] 2018-07-02 14:32
The deviation in behaviour here is simple.

In hibernate, a native query, one that issues a direct SQL command, is returning no results.

This is labeled under investigation as more details are required, specifically what you asked for in your previous request.

**Comment by knz** [comment] 2018-07-02 16:04
The title was not accurate. The problem is with some native queries, not all of them. Renamed to reflect the investigation to be done.

**Comment by rafiss** [comment] 2020-07-10 02:25
This Hibernate is passing now. Closing.

**Closed by rafiss** 2020-07-10 02:25 UTC
Labels: A-sql-hibernate, C-investigation
