### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestPropagateTxnOnPushError

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#4978] opened 2016-03-08 15:35 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f7705cbf58d662bb63e151bc4fe65b59c120521b

Stress build found a failed test:

```
=== RUN   TestPropagateTxnOnPushError
W160308 15:09:51.893251 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
W160308 15:09:51.898117 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160308 15:09:51.898268 server/node.go:353  store store=0:0 ([]=) not bootstrapped
I160308 15:09:51.899754 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457449792.900s
I160308 15:09:51.900137 server/node.go:299  **** cluster 0125bb10-8aec-4601-9884-be75a8fbe343 has been created
I160308 15:09:51.900156 server/node.go:300  **** add additional nodes by specifying --join=127.0.0.1:34754
W160308 15:09:51.900170 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160308 15:09:51.900604 server/node.go:366  initialized store store=1:1 ([]=): {Capacity:8312655872 Available:6116524032 RangeCount:0}
I160308 15:09:51.900627 server/node.go:275  node ID 1 initialized
I160308 15:09:51.900666 storage/stores.go:289  read 0 node addresses from persistent storage
I160308 15:09:51.900706 server/node.go:486  connecting to gossip network to verify cluster ID...
I160308 15:09:51.901147 server/node.go:507  node connected via gossip and verified as part of cluster "0125bb10-8aec-4601-9884-be75a8fbe343"
I160308 15:09:51.901175 server/node.go:331  [node=1] Started node with [[]=] engine(s) and attributes []
I160308 15:09:51.901195 server/server.go:322  starting https/postgres server at 127.0.0.1:34754
I160308 15:09:51.901649 storage/split_queue.go:97  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160308 15:09:51.901998 server/status/runtime.go:137  runtime stats: 44 goroutines, 4.67MiB active, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (408x)
I160308 15:09:51.906778 storage/replica_command.go:1332  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160308 15:09:51.912496 storage/replica_command.go:1255  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457449792.950s
I160308 15:09:51.913707 storage/replica_command.go:1332  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160308 15:09:51.918689 storage/replica_command.go:1255  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457449792.950s
I160308 15:09:51.918765 storage/replica_command.go:1332  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
W160308 15:09:51.921896 storage/replica.go:1780  [node=1,store=1,range=1] failed to push during intent resolution: conflicting intents on [/Meta2/Table/13 /Meta2/Max]: resolved? false
I160308 15:09:51.923695 storage/replica_command.go:1255  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457449792.950s
I160308 15:09:51.924032 storage/replica_command.go:1332  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
W160308 15:09:51.926862 storage/replica.go:1780  [node=1,store=1,range=1] failed to push during intent resolution: conflicting intents on [/Meta2/Table/14 /Meta2/Max]: resolved? false
I160308 15:09:51.968736 storage/replica_command.go:1332  initiating a split of range=1 [/Min-/Table/11) at key "b"
I160308 15:09:51.976370 storage/replica_command.go:1255  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1457449792.976s
I160308 15:09:51.979154 stopper.go:273  draining; tasks left:
1      storage/replica.go:1831
1      server/node.go:689
1      kv/txn_coord_sender.go:825
I160308 15:09:51.979194 stopper.go:273  draining; tasks left:
1      storage/replica.go:1831
1      server/node.go:689
I160308 15:09:51.979444 stopper.go:273  draining; tasks left:
1      storage/replica.go:1831
I160308 15:09:51.979714 http2_client.go:877  transport: http2Client.notifyError got notified that the client transport was broken EOF.
I160308 15:09:52.980058 /go/src/google.golang.org/grpc/clientconn.go:463  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34754: getsockopt: connection refused"; Reconnecting to "127.0.0.1:34754"
I160308 15:09:52.980083 /go/src/google.golang.org/grpc/clientconn.go:501  grpc: Conn.transportMonitor exits due to: grpc: the client connection is closing
--- FAIL: TestPropagateTxnOnPushError (5.14s)
	dist_sender_server_test.go:612: expected TransactionRetryError, but got: <nil>
	dist_sender_server_test.go:621: unexpected epoch; the txn must be attempted 2 times, but got 1 attempts
	leaktest.go:80: Leaked goroutine: goroutine 9495 [chan receive]:
		github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError.func1.1(0xc820098500, 0xc820ae80a4)
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:563 +0x13a
		github.com/cockroachdb/cockroach/client.(*DB).Txn.func1(0xc820098500, 0xc820ae80a4, 0x4)
			/go/src/github.com/cockroachdb/cockroach/client/db.go:468 +0x25
		github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc820098500, 0x1c80101, 0xc8204fae58, 0x1)
			/go/src/github.com/cockroachdb/cockroach/client/txn.go:462 +0x394
		github.com/cockroachdb/cockroach/client.(*DB).Txn(0xc820d30be0, 0xc8204faf68, 0x0)
			/go/src/github.com/cockroachdb/cockroach/client/db.go:469 +0x1a1
		github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError.func1(0xc820d30be0, 0xc82031ba40, 0xc82031baa0, 0xc820314000, 0xc82031bb00)
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:556 +0x62
		created by github.com/cockroachdb/cockroach/kv_test.TestPropagateTxnOnPushError
			/go/src/github.com/cockroachdb/cockroach/kv/dist_sender_server_test.go:569 +0x247
FAIL


ERROR: exit status 1
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
2 runs so far, 0 failures, over 25s
7 runs so far, 0 failures, over 30s
7 runs so far, 0 failures, over 35s
8 runs completed, 1 failures, over 37s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-08 15:37
Duplicate of #4906.

**Closed by petermattis** 2016-03-08 15:37 UTC
Labels: Robot, test-failure
