### ISSUE TITLE
schemachangerccl: TestBackupRestoreNonCCL is flaky

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/cockroach#85791] opened 2022-08-09 00:54 UTC
**Describe the problem**

The test `TestBackupRestoreNonCCL/drop_schema/DROP_SCHEMA_db.sc/backup/restore_stage_1_of_1/#01` flaked out in a pre-merge CI run (of #85784). See [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=6017346&buildTypeId=Cockroach_BazelEssentialCi).

Running on the same branch as the PR, and under stress yielded no failures.

Jira issue: CRDB-18434

**Comment by ajwerner** [comment] 2022-08-09 01:23
This is just the test timing out. I think we need to give these tests more CPU cores.

**Comment by ajwerner** [comment] 2022-08-09 14:07
```
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058  job 786208836476862465: running execution encountered retriable error: non-cancelable: failed to construct state for job 786208836476862465: descriptor ‹"db"› (111): job ID mismatch: expected 786208836476862465, got 786208820030078977
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +(1) attached stack trace
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  -- stack trace:
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1273
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:329
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (2) non-cancelable
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (3) attached stack trace
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  -- stack trace:
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:110
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:101
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:44
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1242
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1243
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:329
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (4) failed to construct state for job 786208836476862465
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (5) attached stack trace
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  -- stack trace:
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.makeState.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:206
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | [...repeated from below...]
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (6) descriptor ‹"db"› (111)
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (7) attached stack trace
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  -- stack trace:
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.makeState.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:213
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.makeState.func4
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:238
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.makeState.func5
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:260
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1.1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:106
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:144
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:84
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/kv.runTxn.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:960
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/kv.(*Txn).exec
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/kv/txn.go:957
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/kv.runTxn
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:959
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).TxnWithAdmissionControl
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:922
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/kv.(*DB).Txn
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/kv/db.go:901
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*CollectionFactory).Txn
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/txn.go:79
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps.(*jobExecutionDeps).WithTxnInJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scdeps/run_deps.go:111
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:103
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.makeState
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:247
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun.RunSchemaChangesInJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:100
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).run
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:101
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob.(*newSchemaChangeResumer).Resume
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scjob/job.go:44
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1242
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1243
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:408
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:329
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:489
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | runtime.goexit
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +  | 	GOROOT/src/runtime/asm_amd64.s:1571
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Wraps: (8) job ID mismatch: expected 786208836476862465, got 786208820030078977
I220808 23:44:55.994703 808446 jobs/registry.go:1275 ⋮ [n1] 28058 +Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *withstack.withStack (8) *errutil.leafError
```

**Comment by ajwerner** [comment] 2022-08-09 14:08
My guess is that we're synthesizing two jobs and one bars.

**Comment by postamar** [comment] 2022-08-09 14:14
@fqazi can you please take this on soon?

**Comment by fqazi** [comment] 2022-08-09 14:14
Picking this up now

**Comment by fqazi** [comment] 2022-08-09 19:45
This is caused by us hitting transaction retries while executing `publishDescriptors` inside restoreResumer, which ends up flipping `details.DescriptorsPublished`. On the second call once that flag is flipped it becomes a no-op, which would cause us to leave the descriptors unmodified

**Comment by fqazi** [comment] 2022-08-09 20:57
Nevermind that theory doesn't work we are copying the details into publishDescriptors, so a retry error isn't a valid explanation

**Comment by fqazi** [comment] 2022-08-11 15:44
The root cause of this is that the restore code to modify the database descriptors job ID doesn't work because the immutable version of GetDeclarativeState is used so a cloned copy is altered. Additionally, the backup test has bugs which cause us to skip testing certain stages, and due to timing the failing case correctly tests one of the stages (I need to dig into this aspect to understand, but the issue here is that we are skipping the stage under non-stress scenarios).

**Comment by fqazi** [comment] 2022-08-16 13:34
Fixed via: https://github.com/cockroachdb/cockroach/pull/85998

**Closed by fqazi** 2022-08-16 13:34 UTC
Labels: C-bug, T-sql-schema
