### ISSUE TITLE
CREATE INVERTED INDEX job using 75% of CPU when cluster at rest

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#32681] opened 2018-11-28 17:38 UTC
**Describe the problem**

A customer using v2.1 created (and then cancelled) a CREATE INVERTED INDEX job 6 days ago. Since then, they've observed that CPU spikes periodically to ~75% and disk write activity even when the cluster is completely at rest.

@nvanbenschoten reviewed pprofs and saw that there were a number of `InitPut` ops. The `#/_status/diagnostics/local` endpoint also shows an active inverted index job even though the client has not initiated a job, and all jobs appeared cancelled:

```
      "mutations": [
        {
          "index": {
            "name": "_",
            "id": 4,
            "unique": false,
            "columnNames": [
              "_"
            ],
            "columnDirections": [
              0
            ],
            "storeColumnNames": [
            ],
            "columnIds": [
              2
            ],
            "extraColumnIds": [
              1
            ],
            "storeColumnIds": [
            ],
            "compositeColumnIds": [
            ],
            "foreignKey": {
              "table": 0,
              "index": 0,
              "name": "",
              "validity": 0,
              "sharedPrefixLen": 0,
              "onDelete": 0,
              "onUpdate": 0
            },
            "referencedBy": [
            ],
            "interleave": {
              "ancestors": [
              ]
            },
            "interleavedBy": [
            ],
            "partitioning": {
              "numColumns": 0,
              "list": [
              ],
              "range": [
              ]
            },
            "type": 1
          },
          "state": 2,
          "direction": 1,
          "mutationId": 3,
          "rollback": false
        }
      ],
      "lease": {
        "nodeId": 3,
        "expirationTime": "1542975891759349520"
      },
      "nextMutationId": 4,
      "formatVersion": 3,
      "state": 0,
      "checks": [
      ],
      "drainingNames": [
      ],
      "viewQuery": "",
      "dependsOn": [
      ],
      "dependedOnBy": [
      ],
      "mutationJobs": [
        {
          "mutationId": 3,
          "jobId": "402458394475888641"
        }
      ],
```

**Additional data / screenshots**
![screen shot 2018-11-28 at 12 36 19 pm](https://user-images.githubusercontent.com/38867162/49170497-4523d980-f30a-11e8-846c-89c72f7ba960.png)
![screen shot 2018-11-28 at 12 36 09 pm](https://user-images.githubusercontent.com/38867162/49170498-4523d980-f30a-11e8-915b-2048a76b6fef.png)
![screen shot 2018-11-28 at 12 35 57 pm](https://user-images.githubusercontent.com/38867162/49170499-4523d980-f30a-11e8-9ccd-35f97499bff5.png)

**Environment:**
 - CockroachDB version v2.1
 - AWS, io1 volumes.

**Comment by tim-o** [comment] 2018-11-28 17:39
Also, we have cockroach debug zip output [here - CRDB only](https://drive.google.com/drive/u/1/folders/1gJAhXFhOwuJAkfy5fRpxhZzaHjtGVDFS), and we have access to the Admin UI - you can ping me for access if needed.

**Comment by nvanbenschoten** [comment] 2018-11-28 18:08
cc. @dt @vivekmenezes

**Comment by vivekmenezes** [comment] 2018-11-30 13:58
@tim-o the fact that rollback = false is indicative that the rollback didn't work (cancel failed). Can you attach the output of the admin-UI for the jobs page or SHOW JOBS to this issue.

**Comment by aizumoff** [comment] 2018-12-03 19:04
Hi!
I'm the Customer's representative. 
I'll attach screenshot tomorrow - but it shows "Canceled" in Jobs UI. It's kind of obvious that we've checked that first before creating this ticket. ;) 
I've canceled that via "CANCEL JOB {JOB_ID}" statement - the ID I got from:
SELECT * FROM [SHOW JOBS] WHERE status IN ('running');

**Comment by vivekmenezes** [comment] 2018-12-04 03:43
@aizumoff thanks for reporting that. So it does look a problem where the schema change was not actually rolled back but the underlying job was marked cancelled. I'll take a look.

**Comment by aizumoff** [comment] 2018-12-04 08:15
Here is the screenshot. 
![image](https://user-images.githubusercontent.com/12845564/49428002-ec46bc00-f7b5-11e8-90e0-7a4dc571c1ac.png)

**Comment by vivekmenezes** [comment] 2018-12-06 22:30
@aizumoff I've been staring at this problem for a bit now and am mystified as to how it could be happening. I can understand the CPU spike under the circumstances before and even after the cancel. But it is a mystery if the CPU spike is happening after ROLL BACK JOB has been declared succeeded as you are seeing.

The steps should be
1. Cancel job, job appears cancelled. Schema changer continues to chug along.
2. Schema changer notices job is cancelled and starts a ROLL BACK job. ROLL BACK job start chugging along.
3. ROLL BACK job declares itself succeeded. Cluster is quiet as far as the schema change is concerned.

**Comment by aizumoff** [comment] 2018-12-07 07:46
@vivekmenezes What I've seen (you could contact @tim-o or Andrew - they see that on the cluster as well) was the following:
1. I have 2.5GB mostly big-one-column-JSON table. 
2. I start creating Inverted index - it takes hours/day 
3. I've decided to cancel The Job - it shows Canceled
4. for 2-3-4 more days I see CPU spikes for 2-3 nodes upto 15-25%. Nothing else was run on the cluster at that time. No backups, no queries. 
5. Even after I've on kubernetes restarted all the PODs for that Cockroach Stateful set - cluster "catch-up" where it was I believe - and spikes continue to happen. 
So After I see Canceled - something really crunching continue to happen. And "Rollack job" in the list appears after days of Cancel, while cluster eating CPU in meantime. 

That's what I've observed at least 2-3 times. 

PS: For now I've reduce cluster size (3 nodes, small vs 4 nodes XLarge) - but I can repeat the case. But I think you should be reproducible easily if you'll get one of the tables from CSV - I could share one. And try to create inverted index on that.

**Comment by aizumoff** [comment] 2018-12-07 07:51
Probably the inverted index is pretty big - so Rollback needs so much time? Anyway - it's not clear what's happening in the cluster - that's concerning :) 

And during the Spikes - I've attached to pods to review Logs - nothing was in the logs except basic statistics: Go Coroutines, CPU, et.c So cluster by the logs appears super quiet. That's also strange - some messages for "Rollback" whatever would be helpful to see anything is going on.... 
Also I observer pretty big number upto 900-1200 GO Routines at that times. and the are not dropping as well.

**Comment by vivekmenezes** [comment] 2018-12-07 14:32
@aizumoff thanks for that information. We have some known problems here:
1. index creation takes a lot of time. This is on the road map to be improved in 2.2 ( #12424 )
2. cancel takes a few hours with the ROLL BACK job eventually completing. Already fixed in the 2.2 alpha release through (https://github.com/cockroachdb/cockroach/pull/31326)

And then we have this issue around CPU spikes after ROLL BACK job succeeds. So this issue is not a bug per se but a mystery around unaccounted for CPU. It will be valuable for you to have greater insight into what is happening.

I think if we can have the CSV file (@tim-o) we can take it from here. Thank you for your help!

If you'd like to try out the 2.2 alpha release and see if (2) above is fixed in your case that would be cool.

**Comment by vivekmenezes** [comment] 2018-12-11 17:41
@aizumoff I looked at your cluster and I've confirmed that there are no outstanding schema changes left on that cluster. You should not be seeing CPU being used for schema changes.

Based on the above I've confirmed that the underlying problem seems to be slow schema changes (#12424),  and the rollback being slow which is already fixed through (#31326) in 2.2

I can either close this or leave it open to be confirmed closed once your cluster is running 2.2 in April.

Thanks for your patience!

**Comment by awoods187** [comment] 2018-12-13 02:38
@vivekmenezes have you tested this on the 2.2 alpha that contains #31326? I want to make sure the inverted index works and completes (even if it takes a while) before we write this off as only needing speed up

**Comment by vivekmenezes** [comment] 2018-12-13 03:33
@eriktrinh since you worked on DROP INDEX, can you bring up a TPCC-1000 cluster, run an ADD INDEX and after 30 minutes CANCEL JOB and confirm that you see the cancel succeed in a few minutes.

**Comment by awoods187** [comment] 2018-12-13 03:42
we really need to test the `inverted index` as that's what caused the problem here

**Comment by aizumoff** [comment] 2018-12-13 10:59
Hi! 
Today I've run Import 30x CSV gziped files and after 20mins when it shows it'll take 20hours to complete - I've canceled the Job. in UI it shows "Canceled". CPU now on all 3 Nodes ~20-35%. Let's see when it drops and roll-backs. Will keep you posted.

**Comment by aizumoff** [comment] 2018-12-14 09:07
Hi! It's ~1 day passed. Here is the CPU screenshot - the CPU spikes dropped just couple of hours ago. I don't see Rollback job though. 
![image](https://user-images.githubusercontent.com/12845564/49993830-dba5fb00-ff98-11e8-8069-7f8623db46e0.png)

**Comment by jordanlewis** [comment] 2020-03-02 14:49
This is pretty stale, I'm going to close it.

**Closed by jordanlewis** 2020-03-02 14:49 UTC
Labels: A-schema-changes, A-schema-descriptors, C-bug, O-support, S-3
