### ISSUE TITLE
sql: zone config parsing is problematic

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#8389] opened 2016-08-08 21:16 UTC
In #8152, `parseZoneName` calls out to `ParseTableNameTraditional` which parses a table name by constructing an `ALTER TABLE` statement. The string is arbitrary and we don't verify it's escaped correctly so it has the potential of creating an unexpected statement. This is a bit sketchy (even if it's not a safety concern since we don't actually execute the `ALTER TABLE` statement).

This isn't even a table name in the first place; ideally we would be able to parse names directly.

**Comment by knz** [comment] 2016-08-15 10:56
Woah I didn't realize these were not meant to be table names. Thanks for spotting this.

**Comment by knz** [comment] 2016-09-03 11:22
So we discussed this last week on Gitter with @petermattis who confirmed that zone names relate to tables or indices; as this is exactly the syntax supported by ALTER TABLE the current code is indeed appropriate to parse the name. 
The risk to create additional statements is already covered by `ParseOne` in `parse.go` which checks that not more than 1 statement was recognized during parsing.

So I will close this as "not a bug".

**Closed by knz** 2016-09-03 11:22 UTC
