### ISSUE TITLE
sql: DROP DATABASE CASCADE fails due to ghost table descriptor

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#27135] opened 2018-07-03 18:40 UTC
**BUG REPORT**

![image](https://user-images.githubusercontent.com/7130705/42238343-b8f96842-7f2a-11e8-8ee2-3631f910c9bc.png)

2. Please describe the issue you observed:
- I'm not sure how I got into that, If I want to force drop database, it must work regardless.

P/s: I manually drop table by hand and then drop database, but one table (migrations) show some error, and then I can't drop database

**Comment by knz** [comment] 2018-07-05 07:11
@kocoten1992 Thanks for your report!

Could you please run the following two statements and paste the results:

``sql
> SELECT * FROM encoderv2.crdb_internal.tables;
> SELECT * FROM system.eventlog WHERE info LIKE '%encoderv2%';
```

thank you in advance!

**Comment by knz** [comment] 2018-07-05 07:13
cc @vivekmenezes

**Comment by kocoten1992** [comment] 2018-07-05 07:31
@knz here https://gist.github.com/kocoten1992/67d51ea5e504e4617f0cb678a80e65ef

but the second one a bit long it not my shell scroll only 500 lines, how does I output sql directly to a file, thank you :+1:

**Comment by kocoten1992** [comment] 2018-07-05 07:33
I just notice that, I haven't fully (some machine, yet, some don't) configure systemd-timesync to time1.google.com yet at that time, hope that won't mess thing up

**Comment by knz** [comment] 2018-07-05 07:40
@kocoten1992 you can redirect the output by entering the following command in your shell:

```
$ cockroach sql -e "SELECT * FROM system.eventlog WHERE info LIKE '%encoderv2%'" >output.txt
```

**Comment by kocoten1992** [comment] 2018-07-05 07:42
yep, I'll update it now

**Comment by knz** [comment] 2018-07-05 07:45
@kocoten1992 does the database `encoderv2` still exist? From the output it seems that it has been deleted successfully in the end. Is that possible?

For sure you can run the following statement too:

```sql
> select * from system.namespace;
```

**Comment by kocoten1992** [comment] 2018-07-05 07:45
[crdb_internal.txt](https://github.com/cockroachdb/cockroach/files/2165473/crdb_internal.txt)
[eventlog.txt](https://github.com/cockroachdb/cockroach/files/2165474/eventlog.txt)

**Comment by kocoten1992** [comment] 2018-07-05 07:46
root@192.168.100.204:26257/defaultdb> select * from system.namespace;
+----------+------------------+-----+
| parentID |       name       | id  |
+----------+------------------+-----+
|        0 | defaultdb        |  52 |
|        0 | encoderv2        |  56 |
|        0 | encoderv22       | 250 |
|        0 | system           |   1 |
|        1 | descriptor       |   3 |
|        1 | eventlog         |  12 |
|        1 | jobs             |  15 |
|        1 | lease            |  11 |
|        1 | locations        |  21 |
|        1 | namespace        |   2 |
|        1 | rangelog         |  13 |
|        1 | role_members     |  23 |
|        1 | settings         |   6 |
|        1 | table_statistics |  20 |
|        1 | ui               |  14 |
|        1 | users            |   4 |
|        1 | web_sessions     |  19 |
|        1 | zones            |   5 |
|       70 | migrations       |  71 |
|       72 | migrations       |  73 |
|       74 | migrations       |  75 |
|       77 | migrations       |  78 |
|       81 | migrations       |  82 |
|       85 | migrations       |  86 |
|       89 | migrations       |  90 |
|       89 | users            |  91 |
|       94 | migrations       |  95 |
|       94 | password_resets  |  97 |
|       94 | users            |  96 |
|      100 | machines         | 104 |
|      100 | migrations       | 101 |
|      100 | password_resets  | 103 |
|      100 | users            | 102 |
|      107 | machines         | 111 |
|      107 | migrations       | 108 |
|      107 | password_resets  | 110 |
|      107 | users            | 109 |
|      114 | machines         | 118 |
|      114 | migrations       | 115 |
|      114 | password_resets  | 117 |
|      114 | users            | 116 |
|      121 | machines         | 125 |
|      121 | migrations       | 122 |
|      121 | password_resets  | 124 |
|      121 | users            | 123 |
|      128 | cpus             | 133 |
|      128 | machines         | 132 |
|      128 | migrations       | 129 |
|      128 | password_resets  | 131 |
|      128 | users            | 130 |
|      135 | cpus             | 140 |
|      135 | machines         | 139 |
|      135 | migrations       | 136 |
|      135 | password_resets  | 138 |
|      135 | users            | 137 |
|      151 | cpus             | 156 |
|      151 | machines         | 155 |
|      151 | materials        | 157 |
|      151 | migrations       | 152 |
|      151 | password_resets  | 154 |
|      151 | profiles         | 158 |
|      151 | users            | 153 |
|      161 | cpus             | 166 |
|      161 | machines         | 165 |
|      161 | materials        | 167 |
|      161 | migrations       | 162 |
|      161 | password_resets  | 164 |
|      161 | profiles         | 168 |
|      161 | users            | 163 |
|      171 | cpus             | 176 |
|      171 | machines         | 175 |
|      171 | materials        | 177 |
|      171 | migrations       | 172 |
|      171 | password_resets  | 174 |
|      171 | profiles         | 178 |
|      171 | users            | 173 |
|      181 | cores            | 195 |
|      205 | first_passes     | 215 |
|      250 | audio_streams    | 262 |
|      250 | backups          | 265 |
|      250 | cores            | 263 |
|      250 | cpus             | 255 |
|      250 | depots           | 266 |
|      250 | first_passes     | 260 |
|      250 | machines         | 254 |
|      250 | materials        | 256 |
|      250 | migrations       | 251 |
|      250 | mpds             | 259 |
|      250 | password_resets  | 253 |
|      250 | profiles         | 257 |
|      250 | replicas         | 267 |
|      250 | settings         | 264 |
|      250 | tasks            | 258 |
|      250 | users            | 252 |
|      250 | video_streams    | 261 |
+----------+------------------+-----+
(95 rows)

**Comment by kocoten1992** [comment] 2018-07-05 07:47
root@192.168.100.204:26257/defaultdb> show databases;
+------------+
|  Database  |
+------------+
| defaultdb  |
| encoderv2  |
| encoderv22 |
| system     |
+------------+
(4 rows)

Time: 11.699053ms

**Comment by knz** [comment] 2018-07-05 07:51
Ok I think I know what was happening: when you deleted the `migrations` table in `encoderv2`, the table was immediately marked as "dropped" but the database deletion had to wait for the table lease to expire.

This is unfortunate, but I think now the lease has expired (5-10 minutes later) you can delete the database successfully. What is the output of `drop database encoderv2` now? (no `cascade` needed I think)

**Comment by kocoten1992** [comment] 2018-07-05 07:59
```
root@192.168.100.204:26257/defaultdb> drop database encoderv2
                                   -> ;
DROP DATABASE

Time: 200.069411ms
```
What magic is this, wow thank you :smile: , thank you, we can close this now

**Comment by knz** [comment] 2018-07-05 08:48
No we should not close this -- I think `drop database cascade` should ignore the dropped table descriptors, even if there is a lease still active. But I am glad your issue is resolved.

**Comment by kocoten1992** [comment] 2018-07-06 19:58
Want to point that, it not 5-10 min later, much longer (maybe a day or two)

**Comment by vivekmenezes** [comment] 2018-07-10 01:50
@kocoten1992 I'm unable to reproduce this problem by creating a table, dropping the table and then dropping the database before the table data is cleared. I'd appreciate it if you can give me some instructions to better reproduce this problem.

**Comment by kocoten1992** [comment] 2018-07-11 16:02
I'm been running a loop of create and drop tables, been 8 times already and unable to reproduce it (yayyyyyy!!!! :smile:), previously it show up quite often.

I'll let it run for several days and see what happen

**Comment by vivekmenezes** [comment] 2018-07-11 17:54
while we do support creating and dropping a table, running it in a loop will eventually result the database running out of internal table IDs. We do not support this at the moment.

**Comment by kocoten1992** [comment] 2018-07-11 18:23
@vivekmenezes I mis-read the question, it was ```dropping the database``` instead of tables,

and yes, the bug still exists

![image](https://user-images.githubusercontent.com/7130705/42591812-fd188678-8571-11e8-9b65-cc6bccfe2f7e.png)

I'll drop an email to tim@cockroachlabs.com the loop code and further detail

**Comment by kocoten1992** [comment] 2018-07-17 14:47
hi @vivekmenezes , have you able to reproduce the issue ?

**Comment by vivekmenezes** [comment] 2018-07-17 16:54
@kocoten1992 I've not been able to reproduce this problem. Any help would be very much appreciated. Thanks!

**Comment by poobah** [comment] 2018-07-27 09:04
This issue occurred for me when attempting to drop a table that was cascade FK linked to another table. The tables are not present when viewing but CR still thinks they are there and any attempt to drop the database gives me the same error as above. I attempted this using Postico and after waiting a while I cut the connection.

**Closed** 2018-09-20 02:03 UTC
Labels: A-schema-changes, C-bug, O-community, S-3-ux-surprise
