### ISSUE TITLE
clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the offset)

### ISSUE THREAD

**Issue by wxw9868** [cockroachdb/cockroach#46718] opened 2020-03-30 06:30 UTC
```
 F200330 06:28:40.975752 83 server/server.go:253  [n?] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (0 of 1 are within the offset)
goroutine 83 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0xc0000a6700, 0xc0000a6720, 0x0, 0xdc3a0)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:1020 +0xb1
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x5b4fd40, 0xc000000004, 0x53d023b, 0x10, 0xfd, 0xc0002f90e0, 0x88)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:876 +0x9ac
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x3983640, 0xc000851770, 0xc000000004, 0x2, 0x0, 0x0, 0xc000f51c68, 0x1, 0x1)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:85 +0x2cc
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x3983640, 0xc000851770, 0x1, 0x4, 0x0, 0x0, 0xc000f51c68, 0x1, 0x1)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:71 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatal(...)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:191
github.com/cockroachdb/cockroach/pkg/server.NewServer.func1()
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/server/server.go:253 +0xc7
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).runHeartbeat(0xc0000f03c0, 0xc000341900, 0xc00035ae00, 0x14, 0xc0007a4960, 0x0, 0x0)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:814 +0x658
github.com/cockroachdb/cockroach/pkg/rpc.(*Context).GRPCDial.func1.1.1(0x3983640, 0xc0008dba70)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/rpc/context.go:693 +0x74
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc00042be00, 0xc0004a22d0, 0xc0008db9e0)
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xfb
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/usr/local/cockroach-v19.1.5/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:193 +0xa8
```

**Comment by pbalajiips** [comment] 2020-06-18 04:20
any update on above issue?

**Comment by vineethac** [comment] 2020-06-28 12:11
Even I have a similar issue! I am running cockroachdb on VMware Tanzu Kubernetes clusters.
Describe pod shows warning that "Readiness probe failed!". Any suggestions to resolve this issue?

![image](https://user-images.githubusercontent.com/30316226/85947143-97a1fd80-b966-11ea-8574-4d03626d6302.png)

Thanks
Vineeth

**Comment by pbalajiips** [comment] 2020-06-28 14:41
We fixed this by enabling NTP on each workers synchronised with google time servers.

1)  install NTP on workers

2) comment all entry start with pool and change NTP server configuration to google server in /etc/ntp.conf
        server time1.google.com
        server time2.google.com
        server time3.google.com
        server time4.google.com

3) enable NTP at startup and disable timedatectl service 
# systemctl enable ntp
# systemctl disable systemd-timesyncd.service

4) restart NTP service
# service ntp restart

**Comment by peymanh** [comment] 2020-08-25 13:47
Same Issue here. We use docker image version 20.1.1 in docker swarm. This happened to our second instance

**Comment by yuzefovich** [comment] 2020-09-24 14:45
cc @andreimatei in case you have some wisdom to share here

**Comment by andreimatei** [comment] 2020-09-24 15:25
CRDB requires the clocks on all the nodes to be synchronized at all times with the `--max-offset` value passed to all the nodes. The flag defaults to 500ms. See https://www.cockroachlabs.com/docs/stable/operational-faqs.html#what-happens-when-node-clocks-are-not-properly-synchronized

If you can't ensure tight synchronization, you can always increase the max offset, at a performance cost. Closing, but feel free to comment more or reopen if things are not clear.

**Closed by andreimatei** 2020-09-24 15:25 UTC
Labels: O-community

**Comment by gregory112** [comment] 2023-06-16 06:33
Hi, I feel like this needs to be reopened, I do get this errors so many times in my experience, making the cluster very unreliable, even after restoring and fresh reinstall. The problem is, there is clock drift between nodes at all. I checked them all that NTP works perfectly and the time is synchronized. After a while, a node starts to randomly drops out with this error.
