### ISSUE TITLE
ui: "liveness record" link in admin UI is broken

### ISSUE THREAD

**Issue by TheSamHuang** [cockroachdb/cockroach#57658] opened 2020-12-07 20:38 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

In the admin UI, hovering over any node status of `NODE_STATUS_LIVE` brings up a popup with a link `liveness record`. The link goes to https://www.cockroachlabs.com/docs/v21.1/cluster-setup-troubleshooting.html#node-liveness-issues, which seems to not exist.  
![image](https://user-images.githubusercontent.com/47126443/101402480-cde29200-38a1-11eb-8bb4-996b2ba29edf.png)
![image](https://user-images.githubusercontent.com/47126443/101402621-fc606d00-38a1-11eb-9670-f17b92fb38d9.png)

**To Reproduce**

1. Set up CockroachDB cluster 
2. Open admin UI 
3. Mouse over any `NODE_STATUS_LIVE` status
4. Click `liveness record` in popup
5. See error

**Comment by tharun208** [comment] 2021-03-01 17:59
@TheSamHuang , can you check again, I am not able to reproduce this in the latest master

**Comment by dhartunian** [comment] 2021-03-04 01:11
21.1 docs are now available and the link resolves. Closing this.

**Closed by dhartunian** 2021-03-04 01:11 UTC
Labels: A-webui, C-bug
