### ISSUE TITLE
circleci: failed tests (15874): TestDockerJava 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5876] opened 2016-04-05 19:28 UTC
The following test appears to have failed:

[#15874](https://circleci.com/gh/cockroachdb/cockroach/15874):

```
I160405 19:24:52.206975 acceptance/replication_test.go:66  found 2 replicas
I160405 19:24:52.307557 acceptance/cluster/localcluster.go:649  stopping
I160405 19:24:52.307816 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160405 19:24:52.307834 acceptance/cluster/localcluster.go:570  events monitor exits
I160405 19:24:52.308976 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container b2e54ddabc361c2c5e6ca978258741556a22990651109f6dee0dfc577359f179: Container b2e54ddabc361c2c5e6ca978258741556a22990651109f6dee0dfc577359f179 is not running
--- FAIL: TestDockerJava (27.60s)
	testing.go:113: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestDockerNodeJS
I160405 19:24:54.266547 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160405 19:24:54.268204 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160405 19:24:54.836139 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.471490540
I160405 19:24:54.930957 acceptance/cluster/localcluster.go:532  events monitor starts
I160405 19:24:55.221545 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32856
  trace:     https://127.0.0.1:32856/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-05 20:44
Duplicate of #5858.

**Closed by petermattis** 2016-04-05 20:44 UTC
Labels: Robot, test-failure
