### ISSUE TITLE
sql: COPY into REGIONAL BY ROW table causes internal error

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#87010] opened 2022-08-28 20:55 UTC
**Describe the problem**

Attempting to use `COPY` with a `REGIONAL BY ROW` table caused an internal error.

**To Reproduce**

On master, I ran `./cockroach demo --multitenant=false --nodes 9`
Then, I ran:
```
CREATE DATABASE db PRIMARY REGION "us-east1" REGIONS "us-west1", "europe-west1"; USE db;
CREATE TABLE tab (
  col1 STRING,
  col2 STRING,
  col3 STRING,
  col4 STRING,
  col5 STRING,
  col6 STRING NOT NULL,
  PRIMARY KEY (col1, col2),
  UNIQUE (col5, col6)
) LOCALITY REGIONAL BY ROW;
COPY tab FROM STDIN;
-- Now paste the following:
'remove'	'planned'	'slave'	'instrument'	'shoe'	'rays'
'doing'	'bring'	'color'	'busy'	'flat'	'difficulty'
'western'	'mouse'	'seems'	'fully'	'memory'	'neighborhood'
'cup'	'fairly'	'orbit'	'visit'	'lay'	'cave'
'dry'	'vast'	'instrument'	'scared'	'toy'	'completely'
'paragraph'	'roll'	'atomic'	'doctor'	'best'	'finish'
'job'	'suddenly'	'box'	'affect'	'on'	'date'
\.
```
This resulted in the following error:
```
ERROR: internal error: runtime error: index out of range [6] with length 6
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29: ShouldCatch()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:192: func1()
GOROOT/src/runtime/panic.go:838: gopanic()
GOROOT/src/runtime/panic.go:89: goPanicIndex()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2142: colStatLiteralValues()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:434: colStat()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:266: colStatFromChild()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1102: colStatProject()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:425: colStat()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:2585: colStatWithScan()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:472: colStat()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:266: colStatFromChild()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:365: colStatFromInput()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:4386: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:81: func1()
github.com/cockroachdb/cockroach/pkg/util/pkg/util/fast_int_set.go:206: ForEach()
github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:81: ForEach()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:4380: selectivityFromEquivalencySemiJoin()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:4365: func1()
github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:81: func1()
github.com/cockroachdb/cockroach/pkg/util/pkg/util/fast_int_set.go:206: ForEach()
github.com/cockroachdb/cockroach/pkg/sql/opt/colset.go:81: ForEach()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:4363: selectivityFromEquivalenciesSemiJoin()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1293: buildJoin()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:467: buildJoinProps()
github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:399: buildSemiJoinProps()
github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/memo/expr.og.go:20014: MemoizeSemiJoin()
github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/norm/factory.og.go:5612: ConstructSemiJoin()
github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/opt/norm/factory.og.go:5524: ConstructSemiJoin()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder_unique.go:373: buildInsertionCheck()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/mutation_builder_unique.go:60: buildUniqueChecksForInsert()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/insert.go:683: buildInsert()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

Jira issue: CRDB-19093

**Comment by cucaroach** [comment] 2022-08-31 13:45
dupe of #87011

**Closed by cucaroach** 2022-08-31 13:45 UTC
Labels: C-bug, C-qa, T-sql-queries
