### ISSUE TITLE
error 400 in TestStatusServer

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2059] opened 2015-08-12 00:01 UTC
The following test appears to have failed:

[#5771](https://circleci.com/gh/cockroachdb/cockroach/5771):

```
=== RUN TestRangeReplication
--- PASS: TestRangeReplication (12.10s)
=== RUN TestSingleKey
--- PASS: TestSingleKey (18.56s)
=== RUN TestStatusServer
--- FAIL: TestStatusServer (11.04s)
	status_server_test.go:50: could not GET https://0.0.0.0:32800/_status/details/3 - statuscode: 400
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2015-08-12 07:43
@BramGruneir, could you take a look?

**Comment by tschottdorf** [comment] 2015-08-12 14:45
variation:
```
status_server_test.go:46: could not GET https://0.0.0.0:32800/_status/logfiles/local - Get https://0.0.0.0:32800/_status/logfiles/local: read tcp 127.0.0.1:32800: use of closed network connection
```

**Comment by BramGruneir** [comment] 2015-08-12 14:54
I'll take a look today.  This test has been flaky since I wrote it.  I just can't seem to reproduce the failures  locally.

**Comment by BramGruneir** [comment] 2015-08-13 17:16
Ah, I thought this was the number of log files. I'll still take a look at this and the other strange failures this acceptance test causes.

**Comment by MBerhault** [comment] 2015-08-26 15:45
something else to look at from #2249:
[#6424](https://circleci.com/gh/cockroachdb/cockroach/6424):

```
=== RUN   TestRangeReplication
--- PASS: TestRangeReplication (11.85s)
=== RUN   TestSingleKey
--- PASS: TestSingleKey (16.15s)
=== RUN   TestStatusServer
--- FAIL: TestStatusServer (48.39s)
	testing.go:150: acceptance/replication_test.go:72: condition failed to evaluate within 20s: expected 3 replicas, only found 2
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```

**Comment by BramGruneir** [comment] 2015-11-09 16:51
This has not occurred in months.  Closing for now.

**Closed by BramGruneir** 2015-11-09 16:51 UTC
Labels: test-failure
