### ISSUE TITLE
"pq: unexpected value" error during INSERT

### ISSUE THREAD

**Issue by chessman** [cockroachdb/cockroach#36904] opened 2019-04-17 11:52 UTC
**Describe the problem**

I've got a strange error after INSERT:

```
pq: unexpected value: raw_bytes:"\354\332Yn\003\022mid:a9560f5fcf7da89c485087b1e2a81c1d\000\001C\332\207\200\200\020\023\000\030\250\266\265\313\013\340\341\203\257\007\023\000\037\017\010 \000\000\000\000\000\000\000" timestamp:<wall_time:1555475860990640712 logical:1 >
```

It happened once and I couldn't reproduce it.

**To Reproduce**

I had concurrent INSERTs and a unique constraint that usually returns `unique_violation` that I handle.

**Expected behavior**

The error should be more meaningful. 

**Additional data / screenshots**

```
CREATE TABLE IF NOT EXISTS fs_dirents (
	"id" VARCHAR PRIMARY KEY ,
	"x0" VARCHAR NOT NULL ,
	"parent_id" VARCHAR REFERENCES fs_dirents (id) ,
	"x1" BIGINT NOT NULL ,
	"x2" BIGINT NOT NULL ,
	"x3" TIMESTAMP WITH TIME ZONE NOT NULL ,
	"x4" BIGINT NOT NULL ,
	"x5" JSONB ,
	"x6" VARCHAR NOT NULL ,
	"x7" VARCHAR NOT NULL ,
	"x8" BIGINT NOT NULL DEFAULT 0 ,
	"x9" BIGINT NOT NULL DEFAULT 0 ,
	"x10" BIGINT NOT NULL DEFAULT 0 ,
	"x11" BOOLEAN NOT NULL DEFAULT false ,
	"x12" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now() ,
	FAMILY f1 (id, x8, x9, x10, x11, x12),
	FAMILY f2 (x0, parent_id, x1, x2, x3, x4, x5, x6, x7));
CREATE UNIQUE INDEX ON fs_dirents (parent_id, x0, x6) STORING (x1, x2, x3, x4, x5);
CREATE INDEX ON fs_dirents (x7, x6, x11)

INSERT INTO fs_dirents (x4,x3,id,x5,x1,x0,parent_id,x2,x6,x8,x7) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
```

**Environment:**

3 on-premise servers, cockroaches are in Docker containers.

 - CockroachDB version: 2.1.6
 - Server OS: CentOS 7
 - Client app: Golang database/sql

**Comment by jordanlewis** [comment] 2019-04-17 19:11
Thanks for the report @chessman - as you probably identified, this is almost certainly the same uniqueness constraint error as you normally get, but it's packaged wrong. We'll look into this.

@mjibson could you please take a first look at this?

**Comment by jordanlewis** [comment] 2019-05-01 04:37
The problem here is that a `ConditionFailedError` got propagated up past the spot that's supposed to intercept it, which is `ConvertBatchError`.

I did do some basic testing on the schema and didn't discover anything obviously wrong - a duplicate entry for the primary or unique secondary both produced a good error message. My guess is that something about that error is getting wrapped in a way that `ConvertBatchError` can't handle. Needs more investigation.

**Comment by jordanlewis** [comment] 2019-05-21 18:19
@mjibson to take a slightly deeper look - what else do we need to know before asking core to help?

**Comment by mjibson** [comment] 2019-06-03 18:15
I wasn't able to find out anything more than described above: that this seems to be a case where an error wasn't wrapped correctly, but the error is expected. Maybe there's an error return code path that doesn't go through `ConvertBatchError`. In any case, I'm moving this to our backlog until it shows up more or is reproducible.

**Comment by jordanlewis** [comment] 2019-11-21 15:47
@chessman we're going to close this as we couldn't reproduce. Feel free to comment further if you have more trouble, thanks!

**Closed by jordanlewis** 2019-11-21 15:47 UTC
Labels: C-bug, S-3
