### ISSUE TITLE
Failed tests (12728): TestChaos

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4341] opened 2016-02-12 00:03 UTC
The following test appears to have failed:

[#12728](https://circleci.com/gh/cockroachdb/cockroach/12728):

```
I0211 23:58:54.213146 27480 acceptance/chaos_test.go:160  client 2 shutting down
I0211 23:58:54.369949 27480 acceptance/chaos_test.go:160  client 0 shutting down
I0211 23:58:54.370039 27480 acceptance/chaos_test.go:193  round 2: restarting nodes [1]
W0211 23:58:54.370066 27480 acceptance/chaos_test.go:233  round 2: monkey sleeping while cluster recovers...
I0211 23:58:54.388409 27480 acceptance/chaos_test.go:307  1937 318.5/sec
panic: test timed out after 5m0s

goroutine 228 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0xcddfd8, 0x110c540, 0xe, 0xe, 0x2d8a6ae0d618c001)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc820038f08, 0xcdd840)
	/usr/local/go/src/testing/testing.go:494 +0x70
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc820038f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:140 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:78 +0x113

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1128940)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 6 [syscall, 4 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:131 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:139 +0x30

goroutine 140 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestChaos.func4(0xc8204df920, 0xc8202cf680, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:167 +0x3a
github.com/cockroachdb/cockroach/acceptance.TestChaos(0xc82018a510)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:308 +0x19d0
testing.tRunner(0xc82018a510, 0x110c570)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 19 [select, 4 minutes, locked to thread]:
runtime.gopark(0xcde680, 0xc820024f28, 0xba22b0, 0x6, 0x431b18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc820024f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc820024f28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 196 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc820138780)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 12 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f7f505d0178, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820196610, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820196610, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201965b0, 0xc82019c000, 0x1000, 0x1000, 0x0, 0x7f7f505c8138, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c638, 0xc82019c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82011dce0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 13 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc82011dce0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 150 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f7f505cff38, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8202c5790, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202c5790, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202c5730, 0xc820544000, 0x1000, 0x1000, 0x0, 0x7f7f505c8138, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c278, 0xc820544000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc820138140)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:459 +0x210
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:493 +0x3a7

goroutine 143 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f7f505cfe78, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820528990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820528990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820528930, 0xc82055b000, 0x1000, 0x1000, 0x0, 0x7f7f505c8138, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c068, 0xc82055b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8204a62c0)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 144 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc8204a62c0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 200 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc820138820)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 204 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc8201388c0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 188 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc820347b80)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 156 [select, 4 minutes]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f7f505d9d70, 0xc8202c0640, 0xc8201c6c20, 0xc8202b97a0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xee
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x335

goroutine 227 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc8201394a0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 154 [select, 4 minutes]:
net/http.(*persistConn).readLoop(0xc820257600)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 155 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820257600)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 206 [sleep]:
time.Sleep(0x3b9aca00)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/cockroachdb/cockroach/acceptance.TestChaos.func5(0xc8204df920, 0xc820186ef0, 0xc820388090, 0x3, 0xc8202cf680, 0x3, 0x3, 0x7f7f4d54b478, 0xc820138140, 0xc82018a510, ...)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:235 +0x875
created by github.com/cockroachdb/cockroach/acceptance.TestChaos
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:239 +0xf07
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-12 15:30
Duplicate of #4316.

**Closed by petermattis** 2016-02-12 15:30 UTC
Labels: test-failure, TestChaos
