### ISSUE TITLE
estimated rows from `EXPLAIN SELECT` incorrectly reduced by DISTINCT 

### ISSUE THREAD

**Issue by malwaregarry** [cockroachdb/cockroach#131875] opened 2024-10-04 03:18 UTC
**Describe the problem**
DISTINCT reduces estimated count to 1 even though rows are distinct.
Strangely, adding the HAVING clause does not reduce the row count  

**To Reproduce**
```
CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
INSERT INTO t0 (c0) VALUES(1), (2);
ANALYZE t0;
ANALYZE t1;

EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false); --1
EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false) GROUP BY t0.c0, t1.c0; --1 
EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false) GROUP BY t0.c0, t1.c0 HAVING ((t1.c0) IS NULL);  --2
```

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL 
3. Compare estimated row counts

**Environment:**
 - CockroachDB version 24.2.3
 - Server OS: Arch
 - Client app `cockroach sql`

**Additional context**

Jira issue: CRDB-42731

**Comment by alyshanjahani-crl** [comment] 2024-10-04 15:50
I tried your repro, but i am not seeing a row count, nor an estimated row count of 1, this is on crdb v24.2.3

```
alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> CREATE TABLE t0 (c0 INT);
                                                                                  ->
CREATE TABLE

Time: 584ms total (execution 541ms / network 44ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> CREATE TABLE t1 (c0 INT);
                                                                                  ->
CREATE TABLE

Time: 596ms total (execution 504ms / network 91ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> INSERT INTO t0 (c0) VALUES(1), (2);
                                                                                  ->
INSERT 0 2

Time: 94ms total (execution 52ms / network 42ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> analyze t0;
ANALYZE

Time: 730ms total (execution 690ms / network 40ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> analyze t1;
ANALYZE

Time: 802ms total (execution 678ms / network 124ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false);
  c0 |  c0
-----+-------
   1 | NULL
   2 | NULL
(2 rows)

Time: 44ms total (execution 4ms / network 40ms)

alyshan@bulky-walker-1146.74fg.gcp-us-central1.crdb.io:26257/cluster-1146/defaultdb> explain SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false);
              info
---------------------------------
  distribution: local
  vectorized: true

  • distinct
  │ distinct on: c0, c0
  │
  └── • cross join (left outer)
      │
      ├── • scan
      │     missing stats
      │     table: t0@t0_pkey
      │     spans: FULL SCAN
      │
      └── • norows
(14 rows)

Time: 41ms total (execution 2ms / network 39ms)
```

**Comment by malwaregarry** [comment] 2024-10-08 02:10
hi @alyshanjahani-crl I tested again and it looks like we need to specify the database

```
DROP DATABASE IF EXISTS database0 CASCADE;
CREATE DATABASE database0;
USE database0;

CREATE TABLE t0 (c0 INT);
CREATE TABLE t1 (c0 INT);
INSERT INTO t0 (c0) VALUES(1), (2);
ANALYZE t0;
ANALYZE t1;

EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false); --1
EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false) GROUP BY t0.c0, t1.c0; --1
EXPLAIN SELECT DISTINCT t0.c0, t1.c0 FROM t1 RIGHT OUTER JOIN t0 ON (false) GROUP BY t0.c0, t1.c0 HAVING ((t1.c0) IS NULL);  --2
```

**Comment by DrewKimball** [comment] 2024-10-10 17:20
Hi @malwaregarry, I'm going to close this one, since we don't provide guarantees around the exact estimated row-counts, and so wouldn't consider this a bug. However, your reproduction does suggest an opportunity for a new optimizer rule, which I've pulled out into this issue: #132327.

**Closed** 2024-10-10 17:21 UTC
Labels: C-bug, O-community, T-sql-queries
