### ISSUE TITLE
sql: casts from INT8 to OID should error when they are greater than the max INT4

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#74573] opened 2022-01-07 18:05 UTC
Postgres's OIDs are 4-byte integers, so casting an INT8 that is greater than the max INT4 causes an out of range error:

```
marcus=# SELECT 9999999999::OID;
ERROR:  22003: OID out of range
LOCATION:  i8tooid, int8.c:1403

marcus=# SELECT 9999999999::INT8::OID;
ERROR:  22003: OID out of range
LOCATION:  i8tooid, int8.c:1403
```

As of CRDB version 21.2.3, OIDs are 8-byte integers. This is inconsistent with Postgres.

```
defaultdb> SELECT 9999999999::OID;
     oid
--------------
  9999999999
(1 row)
```

There's also bugs in the casting logic:

```
defaultdb> SELECT 9999999999::INT8::OID;
     oid
--------------
  1410065407
(1 row)
```

**Comment by rafiss** [comment] 2022-01-10 22:05
I think this is mostly a dupe of https://github.com/cockroachdb/cockroach/issues/41904. I started a local draft a while ago to change OIDs like this:
```
 // OIDs are not guaranteed to be globally unique.
 // TODO(rafi): make this use a uint32 instead of a DInt.
 type DOid struct {
-    // A DOid embeds a DInt, the underlying integer OID for this OID datum.
-    DInt
+    // A DOid embeds a oid.Oid, the underlying integer OID for this OID datum.
+    Oid oid.Oid
     // semanticType indicates the particular variety of OID this datum is, whether raw
     // oid or a reg* type.
     semanticType *types.T
     // name is set to the resolved name of this OID, if available.
     name string
```

I hope to come back to it still.

The casting logic we have now was kind of implemented "on purpose" as a temporary workaround to handle negative ints https://github.com/cockroachdb/cockroach/pull/61148 and https://github.com/cockroachdb/cockroach/issues/60533

**Closed by rafiss** 2022-01-10 22:05 UTC
Labels: C-bug, T-sql-experience, T-sql-queries
