### ISSUE TITLE
All Indexes aren't picked up for some time

### ISSUE THREAD

**Issue by Bessonov** [cockroachdb/cockroach#66257] opened 2021-06-09 11:34 UTC
Hello Cockroachers!

I've a strange issue that no one index is used for some time.

**Describe the problem**

On fresh database start with docker and usual migration with knex, the queries are very slow. Explain show, that `table@primary` is used and db do full table scan. If I specify a index to use with `tyble@myindex`, then it works as expected. Some time after or if I drop/recreate one of indexes, then it seems like that the problem goes away. I'm experiencing this behavior with 20.1.9, but also with 21.1.1.

We had very similar problem with update from 20.1.3 to 20.2.x with downgrade option enabled - the performance was 100x worse, even after 2 hours later with nearly empty database. Because of time constraint we doesn't analysed it further and upgraded instead to the ATM latest 20.1.x version of crdb: 20.1.9.

**To Reproduce**

I'm not able to reproduce it constantly, but there is about 10% chance to run in this scenario. At the core, it's just a fresh docker instance with migrations. Probably important: I run performance benchmarks for the app, so multiple queries arrived at same time.

**Expected behavior**
-

**Additional data / screenshots**

I'm not sure that this is a common problem, because, I mean, if it was a common problem, then many people were suffer from it. Therefore I assume I do something that leads to some unusual state. I can provide additional information - what would be helpful? Which settings are interesting?

**Environment:**
 - CockroachDB version: 20.1.9 in docker
 - Server OS: [e.g. Linux/Distrib]: Ubuntu 18.04 host
 - Client app [e.g. `cockroach sql`, JDBC, ...]: knex with PG driver

docker-compose definition:
```yaml
  cockroachdb:
    image: cockroachdb/cockroach:v20.1.9
    hostname: cockroachdb
    container_name: ${TESTSDK_PROJECT}_cockroachdb
    volumes:
      - 'cockroachdb:/cockroach/cockroach-data'
    command: start-single-node --insecure --cache=512m --max-sql-memory=512m
    healthcheck:
      test: ['CMD', './cockroach', 'sql', '--insecure']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped
[...]
volumes:
  cockroachdb:
```

**Comment by kernfeld-cockroach** [comment] 2021-06-09 14:28
This may be caused by automatic stats collection not running in time for your queries. Does running `ANALYZE my_table` querying fix this issue?

**Comment by Bessonov** [comment] 2021-06-15 15:07
@kernfeld-cockroach thank you for your response. If I try I get:

```
ANALYZE my_table;
invalid syntax: statement ignored: at or near "analyze": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
ANALYZE my_table
^
```

**Comment by kernfeld-cockroach** [comment] 2021-06-15 15:28
Ah, I see what's going on. The `ANALYZE my_table` alias is new in 20.2. You could try upgrading to 20.2. If you'd like to stay on 20.1, it's still possible to use [`CREATE STATISTICS ...`](https://www.cockroachlabs.com/docs/v20.1/create-statistics). It's a bit more verbose but it does the same thing.

**Comment by rytaft** [comment] 2021-06-21 16:49
Hi @Bessonov, does running  [`CREATE STATISTICS ...`](https://www.cockroachlabs.com/docs/v20.1/create-statistics) on your table as suggested by @kernfeld-cockroach fix the issue?

Improving automatic statistics collection to avoid the need to run `CREATE STATISTICS` (or `ANALYZE` on later versions) is something that we're working on. Out of curiosity, did you see this poor performance after running an `IMPORT` to load the data? I'd also be curious to hear if you try to upgrade again to 20.2.x or 21.1.x and check whether running `ANALYZE table_name` fixes your issue.

**Comment by Bessonov** [comment] 2021-06-21 17:32
@rytaft thank you very much for your question. I'm not able to get back on this task now, so it takes some time to answer your question.

> Out of curiosity, did you see this poor performance after running an IMPORT to load the data?

`IMPORT` isn't used in my scenario. It's just plain (ddl) migration and then performance testing of our APIs on localhost with [k6](https://github.com/k6io/k6).

**Comment by rytaft** [comment] 2021-06-21 20:30
> @rytaft thank you very much for your question. I'm not able to get back on this task now, so it takes some time to answer your question.

No rush!

> IMPORT isn't used in my scenario. It's just plain (ddl) migration and then performance testing of our APIs on localhost with k6.

Thanks for clarifying. Can you give some details about the performance testing workload? Are there a lot of INSERT or UPDATE statements before the SELECT statements that had poor performance? Approximately how many?

**Comment by rytaft** [comment] 2021-08-30 12:49
I'm closing this since it seems likely that collecting statistics would fix this issue. Please feel free to reopen if you are still seeing poor performance.

**Closed by rytaft** 2021-08-30 12:49 UTC
Labels: C-investigation, O-community, X-blathers-triaged, T-sql-queries
