### ISSUE TITLE
ui: inconsistent use of byte prefixes

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#18949] opened 2017-10-02 18:21 UTC
All charts which show byte metrics have a labeling and computation inconsistency.  The axis label is written with SI unit names, but the tooltips use IEC prefixes, and the computation is done in IEC units.

![screen shot 2017-10-02 at 2 12 11 pm](https://user-images.githubusercontent.com/793969/31092508-acc76302-a77c-11e7-9a49-c71d8934a927.png)

These should be made consistent, which is as simple as replacing the axis labels with the IEC unit names ("kibibytes", "mebibytes", etc.).  It's been two decades since these units have been standardized, we should be adopting them.

**Comment by mrtracy** [comment] 2017-10-04 02:50
This is a duplicate of #4735, I would suggest reading through it.

**Comment by couchand** [comment] 2017-10-04 14:07
Oh my, that is quite the discussion.  Well, it actually sounds like we all agree on what unit multiplier we should be using, which is good.  As of a year and a half ago there was maybe still contention about what label to use for those units, but I definitely am on the side of technical accuracy.  More than anything I'm on the side of consistency.

One way to avoid the question here would be to change the axis label to just not list the units in full, only use the shorthand.  This would make more sense if it were a parenthetical after the measure name, such as "Logical Store Size (GiB)".  That way we're technically accurate but we remove (or minimize) the stumbling block.

Another option mentioned in that thread would be to display these charts in units of ranges - divide the byte size by the range size.  That has the advantage of being more of a logical "how much is in here" quantity, but the disadvantage that it's harder to correlate it with hardware provisioning.

**Closed** 2017-11-09 01:34 UTC
Labels: easy, ux-surprise
