### ISSUE TITLE
SELECT FOR UPDATE from a secondary index has no effect

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#88251] opened 2022-09-20 15:57 UTC
**Describe the problem**
If a SELECT ... FOR UPDATE statement happens to scan a secondary index, it does not block other updates.

**To Reproduce**
In one SQL session:
```
CREATE TABLE t1 (a int PRIMARY KEY, b int, c int, INDEX c_idx(c));
INSERT INTO t1 SELECT g,g,g FROM generate_series(1,10000) g(g);
ANALYZE t1;

BEGIN;
SELECT * FROM t1 WHERE c = 1 FOR UPDATE;
```
In another SQL session:
```
UPDATE t1 SET c=-1 WHERE c = 1;
SELECT * FROM t1 WHERE c = -1;
  a | b | c
----+---+-----
  1 | 1 | -1
```

**Expected behavior**
The update statement should block until the first SQL session commits or rolls back. The predicate `WHERE c = 1` causes a scan of index c_idx, but if the primary index is scanned, the update blocks.

Jira issue: CRDB-19748

**Comment by michae2** [comment] 2024-03-18 17:57
Closing this as a duplicate of https://github.com/cockroachdb/cockroach/issues/57031. This is fixed in 23.2 when using the new SFU implementation (`optimizer_use_lock_op_for_serializable`).

**Closed by michae2** 2024-03-18 17:57 UTC
Labels: C-bug, O-qa, T-kv
