### ISSUE TITLE
circleci: failed tests: TestUnreplicateFirstRange 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8900] opened 2016-08-29 18:52 UTC
The following test appears to have failed:

[#21938](https://circleci.com/gh/cockroachdb/cockroach/21938):

```
I160829 18:51:41.803396 rpc/context.go:165  closing 127.0.0.1:50355
I160829 18:51:41.803436 rpc/context.go:165  closing 127.0.0.1:53507
I160829 18:51:41.803486 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
I160829 18:51:41.803677 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
I160829 18:51:41.803833 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- FAIL: TestUnreplicateFirstRange (0.03s)
	client_test.go:805: no replica node addresses available via gossip
=== RUN   TestStoreRangeDownReplicate
I160829 18:51:41.805390 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
W160829 18:51:41.809071 gossip/gossip.go:1070  not connected to cluster; use --join to specify a connected node
I160829 18:51:41.811044 rpc/context.go:199  dialing 127.0.0.1:32910
I160829 18:51:41.813277 storage/store.go:982  store=1:1: failed initial metrics computation: store=1:1: system config not yet available
I160829 18:51:41.813869 storage/replica.go:2106  store=1:1 range=1 [/Min-/Max): applying command with forced error: storage/replica.go:2031: no-op on empty Raft entry
E160829 18:51:41.814129 storage/replica.go:2141  store=1:1 range=1 [/Min-/Max): error executing raft command: storage/replica.go:2031: no-op on empty Raft entry
I160829 18:51:41.814353 storage/replica_trigger.go:308  store=1:1 range=1 [/Min-/Max): new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160829 18:51:41.814370 storage/replica.go:2738  gossiping sentinel from store 1, range 1
--
I160829 18:52:01.315836 stopper.go:408  quiesceing; tasks left:
85     gossip/infostore.go:290
I160829 18:52:01.315874 stopper.go:408  quiesceing; tasks left:
84     gossip/infostore.go:290
--- PASS: Example_rebalancing (0.15s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	28.036s
=== RUN   TestBatchBasics
I160829 18:51:58.359024 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160829 18:51:58.361503 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchRepr
I160829 18:51:58.364512 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160829 18:51:58.365198 storage/engine/rocksdb.go:402  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.01s)
=== RUN   TestBatchGet
I160829 18:51:58.368835 storage/engine/rocksdb.go:354  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2016-08-29 19:46
I tried in vain to reproduce this locally using both `stress` and `stressrace`.

Assigning @mrtracy because he wrote this test.

**Comment by mrtracy** [comment] 2016-09-04 23:09
I cannot reproduce this in over a hundred thousand runs. Is there a bug in gossip that was recently fixed that would explain this?

**Comment by tamird** [comment] 2016-09-04 23:34
https://github.com/cockroachdb/cockroach/pull/8945, maybe? I don't think there have been other changes to gossip recently.

**Comment by mrtracy** [comment] 2016-09-08 21:09
Going to close this until we get an additional reproduction.

**Closed by mrtracy** 2016-09-08 21:09 UTC
Labels: Robot, test-failure
