### ISSUE TITLE
circleci: failed tests (14550): TestLogic 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5263] opened 2016-03-15 15:02 UTC
The following test appears to have failed:

[#14550](https://circleci.com/gh/cockroachdb/cockroach/14550):

```
I160315 15:01:41.218322 storage/replica_command.go:495  auto-gc'ed ce7809c0 (1 intents)
testdata/poison_after_push: 7
testdata/poison_after_push:33 testuser: COMMIT
testdata/poison_after_push:40 testuser: SELECT * FROM t
I160315 15:01:42.546725 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestLogic (17.11s)
	logic_test.go:531: testdata/poison_after_push:40: expected retry txn, but found <nil>
=== RUN   TestQueryCounts
W160315 15:01:42.610941 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160315 15:01:42.611309 rpc/clock_offset.go:162  monitoring cluster offset every 30s
I160315 15:01:42.624881 server/node.go:350  store store=0:0 ([]=) not bootstrapped
W160315 15:01:42.629787 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160315 15:01:42.644467 raft/raft.go:459  [group 1] 1 became follower at term 5
I160315 15:01:42.644590 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160315 15:01:42.644884 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160315 15:01:42.644919 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
I160315 15:02:01.566283 storage/replica_command.go:68  test injecting error: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
W160315 15:02:01.566524 kv/dist_sender.go:652  failed to invoke BeginTransaction [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/0,/Min), ConditionalPut [/Table/51/1/"g"/2/1,/Min): read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160315 15:02:01.566584 client/db.go:418  failed batch: read at time 0.000000000,0 encountered previous write with future timestamp 0.000000000,0 within uncertainty interval
I160315 15:02:01.567028 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestTxnRestart (0.62s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	39.853s
=== RUN   TestEval
--- PASS: TestEval (0.01s)
=== RUN   TestEvalError
--- PASS: TestEvalError (0.00s)
=== RUN   TestEvalComparisonExprCaching
--- PASS: TestEvalComparisonExprCaching (0.00s)
=== RUN   TestSimilarEscape
--- PASS: TestSimilarEscape (0.00s)
=== RUN   TestQualifiedNameString
--- PASS: TestQualifiedNameString (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-16 16:42
Duplicate of #4787.

**Closed by petermattis** 2016-03-16 16:42 UTC
Labels: Robot, test-failure
