### ISSUE TITLE
sql/pgwire: panic when number of output columns changes between prepare and execute

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#16062] opened 2017-05-22 15:54 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/278019124/

```
*errors.errorString: runtime.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 981, in sendResponse
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 846, in executeStatements
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 823, in handleExecute
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 455, in serve
...
(6 additional frame(s) were not displayed)

runtime.errorString v3.go:353
```

The stack trace says the query has returned more result columns than the query preparation had decided there would be. Either a logic error somewhere or we've not been careful about schema changes happening between prepare and execute.

cc @jordanlewis

**Comment by jordanlewis** [comment] 2017-05-22 17:02
Reproduced with a test:

```
	if _, err := db2.Exec(`CREATE TABLE IF NOT EXISTS f (v INT)`); err != nil {
		t.Fatal(err)
	}
	stmt, err := db2.Prepare(`SELECT * FROM f`)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := db2.Exec(`ALTER TABLE f ADD COLUMN u int`); err != nil {
		t.Fatal(err)
	}
	if _, err := db2.Exec(`INSERT INTO f VALUES (1, 2)`); err != nil {
		t.Fatal(err)
	}
	if _, err := stmt.Exec(); err != nil {
		t.Fatal(err)
	}
```
Output:
```
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range

goroutine 607 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc4203eb040, 0xa711080, 0xc4202407e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x5253b60, 0x61c6ac0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve.func1(0xc420ec8a00, 0xa711080, 0xc4204d26f0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:353 +0x74
panic(0x5253b60, 0x61c6ac0)
        /usr/local/Cellar/go/1.8.1/libexec/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).sendResponse(0xc420ec8a00, 0xa7110c0, 0xc420500a40, 0xc4203d4c80, 0x1, 0x1, 0xc42032b0c8, 0x1, 0x1, 0xc420cf7000, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:981 +0x48b
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc420ec8a00, 0xc420cf7027, 0xf, 0xc42032b0e0, 0xc42032b0c8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:846 +0x1ae
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc420ec8a00, 0xc420ec8a28, 0xc420d93500, 0xc420ec8a45)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:823 +0x1e0
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc420ec8a00, 0xa711080, 0xc4204d26f0, 0xc4204dc350, 0x5400, 0xc4201ce690, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:455 +0xb52
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4201ce540, 0xa7110c0, 0xc4206e7600, 0x5d9bd40, 0xc4201b9500, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:421 +0x926
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5d9cf40, 0xc4210186e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/server/server.go:621 +0x149
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4203eb040, 0xa711080, 0xc4202407e0, 0xc42008c078, 0x5d9cf40, 0xc4210186e0, 0xc420f03170)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:142 +0xa9
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:144 +0x267
exit status 2
FAIL    github.com/cockroachdb/cockroach/pkg/sql/pgwire 0.312s
```

**Comment by tamird** [comment] 2017-05-22 17:06
What happens when you run that test against postgres?

**Comment by knz** [comment] 2017-05-22 17:08
Note that this issue is linked to our general desire to cache logical plans but discard the cached plan if the schema has changed. In this issue here, we'd need to check the version of the schema that was used during prepare against the version that is found at execute time.

**Comment by jordanlewis** [comment] 2017-05-22 17:08
@mjibson assigning to you since I've got a lot on my plate right now. The test is available on my branch if you or whoever ends up fixing this wants to reuse: https://github.com/jordanlewis/cockroach/tree/pgwire-execute-panic

**Comment by jordanlewis** [comment] 2017-05-22 17:20
@knz agreed - but for now there's a much simpler solution. We assign the `outFormats` in `handleBind` based on the number of columns that we initially estimate will be returned, but those `outFormats` are not even used until we iterate through the results at the end of `handleExecute`.

All we need to do to solve this issue is defer setting `outFormats` until after we've executed the prepared statement and have the actual number of results in hand.

**Comment by jordanlewis** [comment] 2017-05-22 17:23
err, s/actual number of results in hand/actual number of result columns in hand/

**Comment by mjibson** [comment] 2017-05-23 03:08
Against postgres: `ERROR:  cached plan must not change result type`

**Comment by jordanlewis** [comment] 2017-05-23 03:33
@mjibson it reproduces on v1.0 for me.

**Comment by jordanlewis** [comment] 2017-05-23 03:34
I triggered it on a release binary to prove it :) https://sentry.io/cockroach-labs/cockroachdb/issues/278019124/

**Comment by mjibson** [comment] 2017-05-23 03:37
Yes, I was attempting to reproduce it using the `PREPARE x AS` syntax, which doesn't trigger it.

**Comment by jordanlewis** [comment] 2017-05-23 03:42
This reminds me that it would be really cool to have `cockroach sql` send `PREPARE` statements to the server as pgwire prepares automatically! Or at least when an option is set. It would be really nice for testing, too.

**Comment by mjibson** [comment] 2017-05-23 03:44
How do they work currently? It would be nice if they failed in the same way as the other ones, like postgres does.

**Comment by jordanlewis** [comment] 2017-05-23 03:48
`PREPARE` and `EXECUTE` SQL statements are handled in [`executor.go`](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/executor.go#L1287).

This is similar to how Postgres behaves - their implementation is just more consistent. You can send a `PREPARE` or `EXECUTE` SQL statement to Postgres as text, as well as sending prepare/execute commands via pgwire.

**Comment by vivekmenezes** [comment] 2017-05-23 19:49
https://github.com/cockroachdb/cockroach/pull/15254 fixes the case where a table version changes during a transaction and will not fix this bug. This bug can be fixed by remembering the table version used while preparing the statement and ensuring that the same version is used while acquiring leases. Error handling will be more complex because we will need to invalidate the prepare statement which will mean closing the connection.

**Comment by mjibson** [comment] 2017-05-23 19:53
We have a different solution in mind that allows table schemas to change during the lifetime of a prepare (which I think is fine?), as long as the query result type columns are the same.

**Comment by knz** [comment] 2017-05-23 20:42
There are two issues here
- one is the case matt outlines, if the subset of the columns used in the prepared query is preserved in the schema change we can make this work
- however in the case where the schema change removes one of the columns used in the prepared query, or if the column gets replaced by something else (esp. with a different type) we still need to invalidate the prepared statement. For this I think a simple SQL error is sufficient, we don't need to invalidate/close the entire session.

**Comment by vivekmenezes** [comment] 2017-05-23 21:03
I think we should not try to reason about this. While this is a specific bug related to incompatible columns, we should fix it by disallowing the use of incompatible descriptor versions. Or else this can easily result in another hairy bug creeping in. Suppose a column gets deleted and added with another type? etc. I believe it is okay to restart the connection when we see a new table version. Its a rare event.

**Comment by tamird** [comment] 2017-05-23 21:21
Won't that cause a server to close all its client connections whenever
schemas change? Sounds like a recipe for a thundering herd of reconnecting
clients.

**Comment by mjibson** [comment] 2017-05-24 03:48
The attached PR fixes the problem where a column is removed and added with another type, because it verifies that the types don't change across executions, so I'm not sure we need to worry about that.

**Comment by knz** [comment] 2017-05-24 13:28
@vivekmenezes I agree that it's better to reject incompatible descriptor versions, but still there is no valid reason to drop the entire connection. We can simply invalidate the specific prepared statement(s) that were prepared off the old schema and reject execute messages with a regular SQL error. The client can re-prepare or issue other queries.

@mjibson: it's semantically incorrect to reuse the prepared query if there's a new column, even with the same name and the same type. The reason is that the application that issued the prepare was assuming specific contents for that column, and the schema change will invalidate that assumption.

**Comment by knz** [comment] 2017-05-24 13:38
@mjibson also your change is technically incorrect: if the query fails because the types has changed, but it contained a data-modifying transaction (e.g. INSERT), the txn is still committed. That's pretty bad.

**Comment by vivekmenezes** [comment] 2017-05-24 17:24
- The version only changes when a new lease is acquired for the table, so as far as the thundering herd problem is concerned it hits one node at a time. Just trying to better characterize it.
- Could we consider re-preparing the statement with the new schema if we feel dropping the connection is not an option?

**Closed** 2017-06-02 19:15 UTC
