### ISSUE TITLE
kv: txn recovery false positive

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#47337] opened 2020-04-10 15:46 UTC
When running kvnemesis on `master` (22d0bb819d42097082b6964c5982d6c381accbdc), I'm able to trigger the `uncommitted txn had writes` invariant in kvnemesis. Looking up in the logs, we always see that these correspond to transactions that have hit `TransactionStatusError: already committed` errors:
```
db0.Txn(ctx, func(ctx context.Context, txn *kv.Txn) error {
    txn.Get(ctx, /Table/50/"8563ef6a") // ("v-3", nil)
    {
      b := &Batch{}
      b.Get(ctx, /Table/50/"c231bad9") // ("v-7", nil)
      txn.Run(ctx, b) // nil
    }
    {
      b := &Batch{}
      b.Put(ctx, /Table/50/"2c797c74", v-8) // nil
      b.Get(ctx, /Table/50/"2c797c74") // ("v-8", nil)
      txn.Run(ctx, b) // nil
    }
    b := &Batch{}
    b.Put(ctx, /Table/50/"ef0bf622", v-9) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
    txn.CommitInBatch(ctx, b) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
    return nil
  }) // TransactionStatusError: already committed (REASON_TXN_COMMITTED)
  return nil
})
```
This error is confusing kvnemesis. The transaction actually was committed, but it also returned an error.

Earlier in the logs, we typically see something like:
```
W200410 15:34:02.677376 1176 roachpb/data.go:1059  updating txn "unnamed" meta={id=382643ec key=/Table/50/"2c797c74" pri=0.06695627 epo=2 ts=1586532842.640559886,3 min=1586532842.618701419,0 seq=1} lock=true stat=PENDING rts=1586532842.640559886,3 wto=false max=1586532843.118701419,0 with COMMITTED txn at earlier epoch meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
E200410 15:34:02.677447 1176 kv/kvclient/kvcoord/txn_coord_sender.go:793  [n1,txn=382643ec] programming error: ABORTED txn in error: TransactionStatusError: already committed (REASON_TXN_COMMITTED): meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2. txn: meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
W200410 15:34:02.677678 1176 roachpb/data.go:1059  updating txn "unnamed" meta={id=382643ec key=/Table/50/"2c797c74" pri=0.06695627 epo=2 ts=1586532842.640559886,3 min=1586532842.618701419,0 seq=1} lock=true stat=PENDING rts=1586532842.640559886,3 wto=false max=1586532843.118701419,0 with COMMITTED txn at earlier epoch meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
E200410 15:34:02.677721 1176 kv/kvclient/kvcoord/txn_coord_sender.go:793  [n1,txn=382643ec] programming error: ABORTED txn in error: TransactionStatusError: already committed (REASON_TXN_COMMITTED): meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2. txn: meta={id=382643ec key=/Table/50/"2c797c74" pri=0.01335293 epo=0 ts=1586532842.618701419,0 min=1586532842.618701419,0 seq=3} lock=true stat=COMMITTED rts=0,0 wto=false max=0,0 int=2
```
This might give an indication of what's going wrong. Are we retrying when a transaction has already committed?

#### Reproduction steps
```
roachprod create $USER-stress -n 30 --gce-machine-type=n1-standard-8 --local-ssd=false
git checkout master
make roachprod-stress PKG=./pkg/kv/kvnemesis TESTS=TestKVNemesisSingleNode TESTTIMEOUT=4m TESTFLAGS='-v -show-logs' CLUSTER=$USER-stress
```
This is the same error that was supposed to be fixed by https://github.com/cockroachdb/cockroach/pull/46596. Maybe there's something else going on. @andreimatei said he would take a look.

**Comment by andreimatei** [comment] 2020-04-14 03:01
I stared this for a while. It would appear that our transaction recovery code has a bug. `QueryIntent` tries to take into account an intent's timestamp when deciding whether the intent had been pushed past its "expected" timestamp. If it has, then the transaction is not implicitly committed. For the intent's timestamp [it uses `intent.Txn.WriteTimestamp`](https://github.com/cockroachdb/cockroach/blob/6c7b80e1d942351dd8ec6f3354ea4b69a20c33e4/pkg/kv/kvserver/batcheval/cmd_query_intent.go#L95). However, it can be that the intent has been pushed, but that field doesn't reflect it: in case of a "push" by a write-too-old, [we bump the `MVCCMetadata.Timestamp`](https://github.com/cockroachdb/cockroach/blob/b9e925b070e7e4d5356411abf45d93f7119c570b/pkg/storage/mvcc.go#L1734), but not the `MVCCMetadata.Txn.WriteTimestamp`.

So, it's possible for the recovery protocol to wrongfully consider a txn committed. That's no good.

I'm not sure, but I believe the problem existed in 19.2 too for a while, until a patch release where we stopped deferring `WriteTooOldErrors`. Once we stopped deferring them, I think it was no longer possible to have a `STAGING` transaction with such a bumped intent. But I'm not sure.

I'll fix it, I think, by keeping the `MVCCMetadata.Timestamp` in sync with `MVCCMetadata.Txn.WriteTimestamp` on initial writes and on pushes.

**Comment by andreimatei** [comment] 2020-04-14 03:04
cc @sumeerbhola - I hear you might know something about this discrepancy between the mvcc meta's timestamp and the txn meta.

**Comment by nvanbenschoten** [comment] 2020-04-14 06:07
Nice debugging! This is a very serious issue.

Sumeer and I were discussing this a few weeks ago for a completely unrelated point - the discrepancy could allow for intents in the MVCC keyspace and locks in the `lockTable` to diverge. This is because the issue is broader than just relating to the transaction recovery protocol - it impacts all interactions with `Intent` objects (e.g. those in `WriteIntentError`) returned from the MVCC layer. In the specific case of the `lockTable`, it seemed like things would be ok because the discrepancy would always be in the direction that the `lockTable` would have a lower timestamp than the MVCC keyspace, but it was still very concerning. I wasn't expecting it to come up in a different context so soon, given that this has been an issue for over 4 years (I think since 4220d4a).

> I'll fix it, I think, by keeping the MVCCMetadata.Timestamp in sync with MVCCMetadata.Txn.WriteTimestamp on initial writes and on pushes.

This is what we were thinking. There's also the question of whether we should keep the timestamps in sync when reading (forward `MVCCMetadata.Txn.WriteTimestamp` to `MVCCMetadata.Timestamp`) before stuffing it in an `Intent` to provide some backwards compatibility.

When we make the change, I think we'll want to remove https://github.com/cockroachdb/cockroach/blob/29c0efdcc5edb5d100449a093b25df107f1df2d6/pkg/kv/kvserver/batcheval/cmd_push_txn.go#L182-L185

This is because the WriteTimestamp of the PusheeTxn will no longer be guaranteed to be a result of the transaction coordinator itself. Instead, it could be an indication that the intent was recently pushed, so it's not a clear indication of client activity. Given that we give transactions 5s to perform their first heartbeat, this should be fine. I think this was also important for a few other reasons with the [Lazy Txn Record RFC](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20181209_lazy_txn_record_creation.md), but the `MinTimestamp` field we later added to intents removed the importance.

EDIT: the RFC actually called this out explicitly: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20181209_lazy_txn_record_creation.md#intent-timestamps. In retrospect, "convenient" probably wasn't the best way to describe this discrepancy.

**Comment by andreimatei** [comment] 2020-04-14 20:48
>  There's also the question of whether we should keep the timestamps in sync when reading (forward MVCCMetadata.Txn.WriteTimestamp to MVCCMetadata.Timestamp) before stuffing it in an Intent to provide some backwards compatibility.

I'm not sure how we'd do this. Also I'm thinking that we don't need to: in 19.2 we should not have such intents with different timestamps because the write too old errors were never deferred.

PTAL at #47491

**Comment by sumeerbhola** [comment] 2020-04-15 13:21
The timestamp handling is getting to be more complicated and confusing (for me). I'd like to have a clear mental model of the invariants. How correct is the following:

We have the following write timestamps for a transaction:
- In the transaction record, which contains a TxnMeta: call this TxnMeta.WriteTimestamp the `txnRecordWriteTS`.

- The writeTS currently being used by the transaction coordinator for attempting to write intents: call this `txnCoordWriteTS`.

- For each writtent intent, the write TS: Call this `intentWriteTS`. Physically, this will now be either MVCCMetadata.Timestamp or MVCCMetadata.Txn.WriteTimestamp since they will always be the same. Is the Timestamp field now redundant -- there is a comment in MVCCMetadata about MVCCMetadata.Txn being nil for reconstructed MVCCMetadata, but IIUC that is just a reuse of the same proto for in-memory data exchange when the latest timestamp is not an intent, and not for storage.

- In lockTable, which
   - mirrors the timestamps of the intent for replicated locks, with lag
    - has unreplicated locks -- we'll call these `unreplLockWriteTS`.

- At any point in time txnRecordWriteTS is >= all the other timestamps since a pusher must update the transaction record first. I suspect I am wrong in this based on what Andrei wrote "QueryIntent tries to take into account an intent's timestamp when deciding whether the intent had been pushed past its "expected" timestamp. If it has, then the transaction is not implicitly committed." -- presumably we would not need to QueryIntent for determining whether a push had happened if the transaction record had been updated first.

- txnCoordWriteTS can be < intentWriteTS when the coordinator does not know about a push.

- The different intentWriteTS and unreplLockWriteTS can be at different timestamps. For the same key, the intentWriteTS and unreplLockWriteTS can be different.

- The commit timestamp of a transaction is lower bounded by txnRecordWriteTS, list of intentWriteTS (if I was wrong abount txnRecordWriteTS being always an upper bound on the timestamps. In that case what about intents whose savepoints have been rolled back -- do they participate in determining the commit timestamp?).

**Comment by andreimatei** [comment] 2020-04-15 19:15
> The timestamp handling is getting to be more complicated and confusing

Ah, I though I was reading The CRDB Story.

> For each writtent intent, the write TS: Call this intentWriteTS. Physically, this will now be either MVCCMetadata.Timestamp or MVCCMetadata.Txn.WriteTimestamp since they will always be the same. Is the Timestamp field now redundant

I think we should get rid of `MVCCMetadata.Timestamp` since it is indeed redundant as far as I can tell.

> At any point in time txnRecordWriteTS is >= all the other timestamps since a pusher must update the transaction record first. I suspect I am wrong in this based on what Andrei wrote "QueryIntent tries to take into account an intent's timestamp when deciding whether the intent had been pushed past its "expected" timestamp. If it has, then the transaction is not implicitly committed." -- presumably we would not need to QueryIntent for determining whether a push had happened if the transaction record had been updated first.

Note that the transaction record doesn't always exist - it's written 1s into the life of the transaction, or at commit/staging time (whichever comes first). Pushers that don't find the txn record can populate a special entry into the ts cache to force the txn record [to bump](https://github.com/cockroachdb/cockroach/blob/678567f8500cbc91550c2414484a56b457240c8e/pkg/kv/kvserver/batcheval/transaction.go#L136-L135) its `WriteTimestamp` when it eventually is written.

Also note that "push" is a very overloaded term. We use it colloquially for any situation in which a write is forced to change its timestamp. That happens when a pusher succeeds in pushing (in which case indeed it either first updates the txn record or, if the record doesn't exist, it populates that ts cache entry I was talking about above), and it also happens when the respective write is evaluated. In this case, there's no "pusher" per se.  Evaluation of a write can bump the write's timestamp either because it ran into the ts cache (i.e. the original write timestamp is too old because there's been a more recent read), or because of a deferred write too old error (i.e. the original write timestamp is too old because there's been a more recent write). In both these cases, the intent ends up being written with a bumped `TxnMeta.WriteTimestamp` and there's no coordination with the txn record.

> The commit timestamp of a transaction is lower bounded by txnRecordWriteTS, list of intentWriteTS (if I was wrong abount txnRecordWriteTS being always an upper bound on the timestamps. In that case what about intents whose savepoints have been rolled back -- do they participate in determining the commit timestamp?).

Intents corresponding to ignored seq nums [do not participate](https://github.com/cockroachdb/cockroach/blob/d230743cc1d0d6deead3e56004faf5710867d3d3/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L656-L659) in "determining the commit timestamp". 
Also note that "determining the commit timestamp" is not a mechanical process. One doesn't simply look at all the intents and decide that the highest shall be the commit timestamp. If any intents were pushed, the coordinator will need to refresh all the previous reads and then try to commit again at the higher timestamp. If there is no coordinator because it died, then the transaction in question will not commit.

Does this answer everything?

**Comment by sumeerbhola** [comment] 2020-04-15 21:05
Thanks, this is very helpful. A couple of small followups:

> it also happens when the respective write is evaluated. In this case, there's no "pusher" per se. Evaluation of a write can bump the write's timestamp either because it ran into the ts cache (i.e. the original write timestamp is too old because there's been a more recent read), or because of a deferred write too old error (i.e. the original write timestamp is too old because there's been a more recent write). In both these cases, the intent ends up being written with a bumped TxnMeta.WriteTimestamp and there's no coordination with the txn record.
...
Intents corresponding to ignored seq nums do not participate in "determining the commit timestamp".

Does the transaction coordinator bump up the timestamp it will use for future writes when it receives an RPC response for such an evaluated write that was "pushed in evaluation"? That is, it can consciously issue writes with a timestamp higher than a (written) transaction record?
The case I am thinking of is:
Intent is written to key="a" at seq=1 and ts=10, then intent written to key="b" seq=2 ts=20, without updating the transaction record. Then a second write to key="a" at seq=2, ts=20 that effectively changes the replicated lock at "a" to ts=20, which allows a different transaction to read at ts=15 and commit, and then the savepoint at seq=2 is rolledback and the first transaction commits at ts=10 since the transaction record still says ts=10 and the intents at ts=20 have been rolled back?

**Closed** 2020-04-15 21:08 UTC
Labels: A-kv-transactions, C-bug

**Comment by andreimatei** [comment] 2020-04-16 01:14
> Does the transaction coordinator bump up the timestamp it will use for future writes when it receives an RPC response for such an evaluated write that was "pushed in evaluation"? That is, it can consciously issue writes with a timestamp higher than a (written) transaction record?

Most definitely. The coordinator [doesn't even try](https://github.com/cockroachdb/cockroach/blob/6c7b80e1d942351dd8ec6f3354ea4b69a20c33e4/pkg/kv/kvserver/batcheval/cmd_heartbeat_txn.go#L75-L77) to update the txn record's `WriteTimestamp`, even when it periodically goes to the txn record to update the `LastHeartbeat` field.

> Intent is written to key="a" at seq=1 and ts=10, then intent written to key="b" seq=2 ts=20, without updating the transaction record. Then a second write to key="a" at seq=2, ts=20 that effectively changes the replicated lock at "a" to ts=20, which allows a different transaction to read at ts=15 and commit, and then the savepoint at seq=2 is rolledback and the first transaction commits at ts=10 since the transaction record still says ts=10 and the intents at ts=20 have been rolled back?

Hmm, if that's how the locks work (and I guess it is), I think maybe you're on to something here; I'm scared now.
Rolling back to a savepoint does not intentionally cause a regression of the `WriteTimestamp`. "Normally", if the txn wrote at ts=20, the coordinator will hear about it and it will not try to commit below 20 even if the client rolls back to an earlier savepoint. There is no timestamp information in the [`savepoint` structure](https://github.com/cockroachdb/cockroach/blob/d230743cc1d0d6deead3e56004faf5710867d3d3/pkg/kv/kvclient/kvcoord/txn_coord_sender_savepoints.go#L26), so rolling back to a savepoint doesn't do anything to them.
**However**, we also allow rolling back to a savepoint after errors. And in such cases I guess it is possible for the `WriteTimestamp` to regress because the coordinator might not have heard about a bumped ts. Like you say, consider that the txn had written "a" at seq=1,ts=10. Then it goes again and wants to write "a" at seq=2,ts=10 - except this time this write gets pushed to ts=20 during evaluation(*). And now say network connection to the coordinator fails and the reply to this RPC gets lost. Now the coordinator knows nothing about ts=20. It knows that there's been an error and it can't simply commit the txn. But it will accept a rollback to a savepoint placed at seq=1, and afterwards it might try to commit at ts=10. And I believe nothing will prevent that commit :S.

Unless I'm missing something, I believe the rub here is, as you also suggest, the way in which our locks get shifted from a timestamp to another. This is not something I've considered when working on the error-recovery-through-savepoints. I'm not entirely sure how the lock table plays into this, but intents don't seem to maintain historical information about the timestamps oh the historical intent versions. Also, I think reads don't care about the history at all; they [simply look at `MVCCMetadata.Timestamp`](https://github.com/cockroachdb/cockroach/blob/678567f8500cbc91550c2414484a56b457240c8e/pkg/storage/mvcc.go#L953) to determine whether there's a conflict - and that `MVCCMetadata.Timestamp` simply reflects the highest seq num.

It seems to me that the right thing to do, one way or another, is to ensure that once a key has been locked at a particular timestamp, that timestamp remains protected even if the txn overwrites the respective intent. I still hope to be missing something...


(*) How can this push happen, given that we already have a lock on "a"? Write-too-olds on "a" can't happen, also the ts cache cannot be populated with a normal entry spanning "a". But other things I guess can still happen: the tscache's low water mark can be bumped above "a" in case there was a lease transfer, or a lot of read volume; the write to "a" can arrive at the replica in a batch with other writes to other keys which are not protected by a lock.

**Comment by sumeerbhola** [comment] 2020-04-16 13:28
> It seems to me that the right thing to do, one way or another, is to ensure that once a key has been locked at a particular timestamp, that timestamp remains protected even if the txn overwrites the respective intent.

Won't this complicate explicit pushing? For example,  txn1 wrote to "a" at ts=10, then (over)wrote to "a" at ts=15, and now txn2 pushes it to ts=20. Both intents need to be at ts=20.

Can we make it such that for any keys with intents that will be committed by a txn, we use the latest timestamp written in the intent, even if it corresponded to a savepoint that was rolled back? This would make a transaction's timestamp monotonically non-decreasing despite savepoint rollback, which makes it easy to reason about. The coordinator could keep track of keys with multiple writes, for which the last write returned an error, and would need to go read the timestamp for that key before deciding on a commit timestamp -- this should be rare, so shouldn't typically cause additional commit latency.

**Comment by andreimatei** [comment] 2020-04-17 00:54
> Won't this complicate explicit pushing? For example, txn1 wrote to "a" at ts=10, then (over)wrote to "a" at ts=15, and now txn2 pushes it to ts=20. Both intents need to be at ts=20.

Indeed. But that makes sense to me.

> Can we make it such that for any keys with intents that will be committed by a txn, we use the latest timestamp written in the intent, even if it corresponded to a savepoint that was rolled back? This would make a transaction's timestamp monotonically non-decreasing despite savepoint rollback, which makes it easy to reason about. The coordinator could keep track of keys with multiple writes, for which the last write returned an error, and would need to go read the timestamp for that key before deciding on a commit timestamp -- this should be rare, so shouldn't typically cause additional commit latency.

Sounds like a lot of bookkeeping that I'd rather not maintain. The client already maintains lock footprint and in-flight writes; now it'd need to maintain... ambiguous overwrites? It seems better to me  to allow the coordinator to commit the txn at ts=10...

I've opened #47587 for the issue. Let's continue there, if you don't mind. I didn't include this branch of the conversation, but feel free copy-paste there if you want.

**Comment by tbg** [comment] 2020-04-24 13:48
All of the transactions are anchored on /Table/57 and /Table/58 (ranges 85 and 67). That probably doesn't mean much, these are likely just the tables TPCC writes to first. They both did have this log spam (and nobody else did):

> W200417 15:07:24.857955 252 kv/kvserver/replica_application_result.go:146  [n4,s4,r67/1:/Table/5{8-9}] failed to repropose with new lease index: [NotLeaseHolderError] r67: replica (n4,s4):1 not lease holder; current lease is repl=(n4,s4):1 seq=3 start=1587133198.675734139,0 epo=1 pro=1587136041.472775780,0

but again that probably just means these are the most active ranges in the system. PS the error comes from here, the message tripped me up at first:

https://github.com/cockroachdb/cockroach/blob/6c7b80e1d942351dd8ec6f3354ea4b69a20c33e4/pkg/kv/kvserver/replica_application_result.go#L206-L217

I didn't find any unusual activity on these ranges in the logs.
