### ISSUE TITLE
schemachanger: schema changes in knex test cause assertion error in SetJobStateOnDescriptor

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#77172] opened 2022-02-28 22:20 UTC
This is causing https://github.com/cockroachdb/cockroach/issues/74021

I haven't yet figured out which series of commands is resulting in these errors, but it can be repro'd with the `knex` roachtest. v21.2 passes the test, but `master` currently has failures.

Errors are in this gist: https://gist.github.com/rafiss/1e44cf546d03565ed43409f1a2ec2d7b

And an example below:
```
Unhandled rejection: error: drop schema if exists "schema_2" - internal error: error executing PreCommitPhase stage 1 of 1 with 7 MutationType ops: unexpected schema change job ID 740454782435098625 on table 104, expected 0
    at Parser.parseErrorMessage (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/mnt/data1/knex/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/mnt/data1/knex/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  length: 5939,
  severity: 'ERROR',
  code: 'XX000',
  detail: 'stages: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+xa227bOBO+jp9C8A/8F0WTWicf2kRAGqdYF41jxAm2QFAYtMTaQmVSICkX7aJAXqt9nDzJgpJ1tFRRltwm3dwEjGaG4nzfiBzO2LIXBLhLSfqndUC9efCP6XiUQTKjMn+c81xVfMGBA+bQOWlPMGVneLWy2RijK7iGhNlzB06WgEKJMrCAkizhj5IsfbbZUtKlC48BZmN0/cWFEnZp+xWfDanq7WbGzsvT19Pz8XX7w0aihRI5K9FDiZKVdEOJmpX0QomWlfRDiZ6VDEJJNyPROqGkl5XIt00h9FKyvNXqS/s5XQIXnrRdbCPWfk7ZFweetG20tunmra2Dg2+5pCkZ0ggMVlS0iF4RTUohTUohTUohTUohTUohTUqCpuHV5WRyPoxEhTyphTypMU/VQWmAGTVFDGWAwRVELMRbu/2IEaP2V3jSHrSfB2rHxwzMHSiZDqD0pI09BknbOGbEOGZW+HQJgcUfU9OdH03DeY9fMMs4fuGr+upGei7/n2gu4wpawGTQytgzy+DQS9Ozv84vTqXRG+n8/Wh6PZXu777//3+q9sr/c3/34+j+7js1l3AFZsr93Y/tt4tOHE7ykxmuwSJvkoTFC987I37SCh+1jJBChBEs/ZpSnDFAFjAiTK9N2DOfsTFYQeoCE1ZkzAIMzAGFIysCQ+5o25NYkJrEdhkmCU2lO9jWRGAFI40cHiqiiroNIXT5GUFSFR1hr3E8O7MMgjGr4XKvIZdvKCQTYq9tBy4g3ZvvbuYVXG9by6OQjJOxAayVjWqg1H9cKG3573pzxzZrADB4XADsGCY1vyW50xBKU38rq4hOsP8VIlPZGblRZyaAVD/jXd9oKHhuNA2A0igAPIGrjoCZtGKWMZu5DjDhEjsWJLONdDbbPxhRcl0xrYyzxwUMEhEka3GiPrl5/W50FpggWY/z9LSgG6fpaUEvztLTgn6cpKcFgzhHv34/nqXydKR04jQ9ZabIcZaeFLS4k60DpB8aCb8YljapfIiMBegSWr4N6nJdXUy3x3W7Yrp9rtsT0x1w3b6YrtzhygNBZfnQSMBYoqxwZVlMWVEPDX4XD0WYsUikcZGWK+LMqHquiBOhdnNFHHe1lyviMKv1E4LbD9TE7tGlW3FH6ERf9DN/gnd4cb4Ot4hWqfmpx5aY2F/9y2I01U9Nbqoek6HhuZO+P/30Lckzr+mjrniJ+789lt/9NhbX/mXtAjLAL0qCoGGPmHCD82gYn485C/Lmf2PyqUCpEKBgVdwbL86lgq9UxFzOROsQOpDBYZTICUZtbJBYf2XSE2dc8CnzXVAd5H3lKt/ztE6uiO9wWv3sqKkN4Aqu8Bq+xXM/5N4QvGoG3twc6y2eJ1R6WkfTtV5f0fq9jqoPOvouMbEvB3JvBk04oGQcuHEtwOAmzVsCtIDkLZ4LLn1ExxidAWRChwuiqRnxcgostZZf+kHI/hH7cEJ7ClkYFpdoj1E9QjazgWN/LYPfX4rY1vwrD9pmo6LoO90DG7mf6GNn48wj/NoanJmJCkT6bWvgJJaXOFBr/ru50IhoNxZULCzJO3ANAs+DVoGI70FC586P4gjxJ5ilc7PyCNvO5f7LDYTsE8FM7wqgT0K0dbJ5ZOpgVKORFo30aNSNw0p8ZdWCKbARjJxNAj0hmGGx4Mn0QMrUH0DroxjeP+LKYf1S+i9TLZjf0td54rNBPvPaEs0Ru6+m1VMIPJoQ2KEj98Tuo2F3T+3GpwhoMAJ+T335iagdiUr2i8ss9tsmfiK3cXLPMl3th9EC//OJFvZbuPR9RuDupe9fWZRLlh+FKgnR3iEQOGzXitmOlbKqlbE/utRVK663OiDaoYEU9cF0QIYE2IlaexT65ZxXrFBFp2dJq0S8jD9uoEJVzpfO+dL8YZcPdX/Y48OuP+zzYc8fDvjw4fxy4wKQTzGcp3RIsOtCS5BfbtloM7zD0an/O89m29pbyWA5MFUyx0k6cyyJ/WAxdUAXoEE+NJBa/4ek+6AhmbYJtGNqo5XBpvWt9W8AAAD//2d9W6wYNgAA\n' +
    '--\n' +
    'dependencies: https://cockroachdb.github.io/scplan/viz.html#H4sIAAAAAAAA/+RY3W7aSBS+xk9heaW9qNIEOwTCFiylgdUiNQQFoq0UVWjwnIJV47FmhqzaVaS8Vvs4eZJqxthjDIQBO1Kq3iAx58dzvm9+vjnYn1IUzUzzf6PCFpP4jxcsGAc6ZrYY3jB+KscrAZpA0LYYRxzmEHJmvRPDYe3uMwk5879B22paR7Fbq8XRJADTCxBjbYssOFDLbXHqtjhORmeAsBhmXjQ5HiZ5Wyccu60T6Srd3dVc8k+ay70BjDwOOBfPsdu5uR6Yw8t/ulcXZu9vs/uxNxwNzafH73/+cVp7J3+eHn8cPz1+Z94M5mjsPD3+WP+6buIkyTMZRmi6KUkm4kRW56oRIxky3CM2QxG0rZCEYH2S4BuVysNGzpwVzjiiU0gJOytM2BvJWB/NgUXIgz0Zw4ijCWLQwykYdrW2ngQD86gfcUIznk69ue4ZojmkHht42BPVsF4SQtf/hUD3RUe7aqKyc+xSQniBkhsllXzLgA6of+8HMAX2YrVHuU8Iv3WvBQPaz64NhOd+WACl818LpbX6o8Uk8L0CADR/LQAOXCYF95JdLQmloTzK9kQnPv+2IrN3MXapxQwQ3f+Oj2RQR/PeKBsAp1QALsn8AJXjZaM4dsfjKEAezEiAgY6X1vH4pcFY6o2lrMAQxZoitE/vlmPVvy7eD7v9URwQ2jVlGNy+/9C7TAxnicHORdSVYTWikRicXMS5MqxGNBPD6WqEU1WGlQjHTgy1XISjDKsRaeVnuYgzZRBab9DtJJaasow+9sc5a1p/PZewoQyrU0jrb+QimsqwCszpW1dM0CMBoW2LAk6WteAUQgwhNyGQmtWkMCf3KDAn8JlQMNXha2JKopTnt65YBUV3yt0n5pHo+Drac39U0/X9RiboUOSHnXSq6elu7MyUU7W73NNDqfP8oaTmkvHceGf19xWzOiOZbZ3sv9KXQF0sgeKPi7KWQJ/w3jyKKwCsyX439h99jbIcbJDyB2HeKB3zc4F5ce3+OjHfKhIPAr9ZNvhOVYBfXBH/BuA7dungOyJjcW36O4Avj/rXczd/INPufSJmd4N0seAzQv1viPsk1LuUb/d90OUI0ftK9nVW9qNs+xRfvs+5u0u5jBjJtuIVcIQR1wRiSBbUgyXOWdG0YUKLyb+EftnitBWgeFaimoV69ce6WCfczitJCICDkm+aq1ZD7x20l2vxQfpa9vIVol9UqResQ0kUaZ9/IrJceOql3zNSsxVvCJcF+I2YNKz1UnZjnW286PnqPm3iyRThUYfZ89KZlYKweEf3JZjNNol2U1ucgDzcRuXBqBiVUCgH1cLhxFz2F44Y/xpA28KIzQBLQEP5/Kvr+YpNpdo2z/tK4qt6vpJSR8/XFvLd0SzOlgK2oekstWlTy9l4MH4GAAD//xN1vXqWHQAAstack trace:\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/scmutationexec/schema_change_job.go:53: SetJobStateOnDescriptor()\n' +
    'github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/schemachanger/scop/mutation_visitor_generated.go:316: Visit()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/exec_mutation.go:39: executeDescriptorMutationOps()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scexec/executor.go:32: ExecuteStage()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:144: executeStage()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:70: runTransactionPhase()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scrun/scrun.go:44: RunPreCommitPhase()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3132: runPreCommitStages()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:920: commitSQLTransactionInternal()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:861: commitSQLTransaction()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2042: handleAutoCommit()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:520: func6()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:733: execStmtInOpenState()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143: execStmt()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1846: func1()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1850: execCmd()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1779: run()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746: ServeConn()\n' +
    'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:723: func1()\n' +
    'GOROOT/src/runtime/asm_amd64.s:1581: goexit()\n',
  hint: 'You have encountered an unexpected error.\n' +
    '\n' +
    'Please check the public issue tracker to check whether this problem is\n' +
    'already tracked. If you cannot find it there, please report the error\n' +
    'with details by creating a new issue.\n' +
    '\n' +
    'If you would rather not post publicly, please contact us directly\n' +
    'using the support form.\n' +
    '\n' +
    'We appreciate your feedback.\n',
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'schema_change_job.go',
  line: '53',
  routine: 'SetJobStateOnDescriptor'
}
```

Jira issue: CRDB-13446

**Comment by ajwerner** [comment] 2022-03-01 15:59
@fqazi can you take a look?

**Comment by timgraham** [comment] 2022-03-10 18:49
Rafi hypothesizes that this may be the cause of the "DROP DATABASE" query at the end of the Django test suite (which creates hundreds of tables) taking hours. The regression first appeared in v22.1 alpha 2. The regression was reflected in CockroachDB nightly between roughly Feb. 23 and March 2.

**Comment by ajwerner** [comment] 2022-03-10 18:52
That's timely and lines up with when we enabled our new schema change infrastructure. I think we know what this might be about. We committed two PRs today which should help the runtime algorithmically for a very complex drop scenario. We should test this out and see if we've fixed this sufficiently.

**Comment by ajwerner** [comment] 2022-03-10 18:53
https://github.com/cockroachdb/cockroach/issues/77601

**Comment by fqazi** [comment] 2022-03-11 00:59
This issue is caused by #77648

**Closed** 2022-03-16 00:27 UTC
Labels: C-bug, A-schema-changes, branch-master, release-blocker, T-sql-schema
