### ISSUE TITLE
Test failure in CI build 10059

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3396] opened 2015-12-10 19:45 UTC
The following test appears to have failed:

[#10059](https://circleci.com/gh/cockroachdb/cockroach/10059):

```
=== RUN   TestEngineBatchCommit
I1210 19:44:33.948594 1063 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEngineBatchCommit (0.05s)
=== RUN   TestEngineBatch
I1210 19:44:33.980282 1063 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestEngineBatch (0.03s)
	engine_test.go:216: 0: expected , but got Coc~roachDBr  BC
	engine_test.go:237: 0: expected , but got Coc~roachDBr  BC
	engine_test.go:248: 0: expected , but got Coc~roachDBr  BC
=== RUN   TestEnginePutGetDelete
I1210 19:44:33.981235 1063 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEnginePutGetDelete (0.00s)
=== RUN   TestEngineMerge
I1210 19:44:33.984266 1063 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEngineMerge (0.00s)
=== RUN   TestEngineScan1
--
=== RUN   TestWillOverflow
--- PASS: TestWillOverflow (0.00s)
=== RUN   TestRocksDBCompaction
I1210 19:44:34.441882 1063 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestRocksDBCompaction (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage/engine	0.593s
?   	github.com/cockroachdb/cockroach/storage/engine/rocksdb	[no test files]
?   	github.com/cockroachdb/cockroach/storage/simulation	[no test files]
?   	github.com/cockroachdb/cockroach/testutils	[no test files]
?   	github.com/cockroachdb/cockroach/testutils/gossiputil	[no test files]
=== RUN   TestStoreTimeSeries
I1210 19:44:51.034873 1117 gossip/gossip.go:189  setting node descriptor node_id:1 address:<network_field:"" address_field:"" > attrs:<> 
I1210 19:44:51.035219 1117 kv/range_cache.go:129  lookup range descriptor: key=/System/"tsdqtest.metric\x00\x01\f\b\xfe\x1b\xff"
I1210 19:44:51.035273 1117 kv/range_cache.go:129  lookup range descriptor: key=/Meta2/"\x04tsdqtest.metric\x00\x01\f\b\xfe\x1b\xff"
I1210 19:44:51.035692 1117 kv/range_cache.go:190  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I1210 19:44:51.035835 1117 kv/range_cache.go:190  adding descriptor: key=/Meta2/Max desc=range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2015-12-11 18:37
Duplicate of #3384.

**Closed by petermattis** 2015-12-11 18:37 UTC
Labels: test-failure
