### ISSUE TITLE
bug? there is not a table name length limit, db users could flood with huge names

### ISSUE THREAD

**Issue by lopezator** [cockroachdb/cockroach#44961] opened 2020-02-11 12:04 UTC
**Describe the problem**

I'm not sure this is even a problem, feel free to close it if it isn't.

The thing is that CockroachDB doesn't have a defined limit for table names length, so a malicious user could flood up with (unlimited?) table names.

Could this cause any adverse effects on database usage?

**PostgreSQL behavior:**

In PostgreSQL the defalt table name length limit is **63 bytes**, so:

```
CREATE TABLE ññññññññññññññññññññññññññññññña(
	ID VARCHAR(30)
)
```

Works (63 bytes):

But:

```
CREATE TABLE ñññññññññññññññññññññññññññññññaA(
	ID VARCHAR(30)
)
```

Although it works (64 bytes) truncates the table name to 63 bytes:

```
NOTICE:  identifier "ñññññññññññññññññññññññññññññññaA" will be truncated to "ññññññññññññññññññññññññññññññña"
Query 1 OK: CREATE TABLE
```

+info: https://www.postgresql.org/docs/12/sql-syntax-lexical.html

**MySQL behavior**:

In MySQL, the limit is **64 chars** so:

```
CREATE TABLE ññññññññññññññññññññññññññññññññññññññññññññññññññññññññññññññññ(
	ID VARCHAR(30)
)
```

Works (64 chars)

But:

```
CREATE TABLE ñññññññññññññññññññññññññññññññññññññññññññññññññññññññññññññññña(
	ID VARCHAR(30)
)
```

Doesn't work, (65 chars) throwing:

```
Query 1 ERROR: Incorrect table name 'ññññññññññññññññññññññññññññññññññññññññññññññññññ'
```

Note: funnily, it omits the extra chars (a) from error message.

+info: https://dev.mysql.com/doc/refman/8.0/en/identifier-length.html

**Comment by solongordon** [comment] 2020-10-27 16:16
Not sure about any adverse effects from this but seems like we might as well match Postgres behavior here.

**Comment by jordanlewis** [comment] 2020-10-27 19:14
See also #48443 and linked issues.

**Comment by jordanlewis** [comment] 2021-07-25 21:28
Closing as  a dupe of #48443.

**Closed by jordanlewis** 2021-07-25 21:28 UTC
Labels: A-sql-syntax
