### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestTxnDBPhantomDeleteAnomaly

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6823] opened 2016-05-20 12:07 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b010e2ea2d2c3128b7c3de4a3b0f15e5bfd62624

Stress build found a failed test:

```
=== RUN   TestTxnDBPhantomDeleteAnomaly
W160520 04:32:16.885058 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160520 04:32:16.885167 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160520 04:32:16.887526 kv/txn_correctness_test.go:525  verifying all possible histories for the "phantom delete" anomaly
I160520 04:32:16.887988 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
E160520 04:32:16.888459 config/config.go:382  unable to determine largest reserved object ID from system config: descriptor table not found in system config of 0 values
--- FAIL: TestTxnDBPhantomDeleteAnomaly (1.41s)
	txn_correctness_test.go:581: ([R2(B) DR1(A-C) I2(B) SC1(A-C) C2 W1(D-A+B) C1]): unexpected failure running DR1(A-C): txn "kv/txn_correctness_test.go:633 txn1" id=2d824a3a key="64.A" rw=true pri=0.00000005 iso=SNAPSHOT stat=PENDING epo=4 ts=0.000000000,3502 orig=0.000000000,3502 max=0.000000000,3501 wto=false rop=false failed to push "kv/txn_correctness_test.go:633 txn2" id=f7207995 key="64.B" rw=true pri=0.00000009 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,3502 orig=0.000000000,3495 max=0.000000000,3495 wto=true rop=false
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
6 runs so far, 0 failures, over 20s
16 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
21 runs so far, 0 failures, over 40s
30 runs so far, 0 failures, over 45s
32 runs so far, 0 failures, over 50s
32 runs so far, 0 failures, over 55s
38 runs so far, 0 failures, over 1m0s
42 runs completed, 1 failures, over 1m2s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:53
Duplicate of #6763

**Closed by bdarnell** 2016-05-21 15:53 UTC
Labels: Robot, test-failure
