### ISSUE TITLE
BUG - INSERT ON CONFLICT IGNORE does not work when there is a duplicate key within the insert statement itself

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#44434] opened 2020-01-28 10:18 UTC
**Describe the problem**

While a big data import migrating a huge mongo database into cockroachdb, suddenly the processed stopped importing. The reason: duplicate key value. But I do have `ON CONFLICT DO NOTHING` active. I got a doubt and was just able to reproduce it. The reason for this is:

We do bulk inserts to go through the import faster. But it turns out in the same batch the same key pair (a distinct key made from 3 fields) appeared at least twice. Cockroachdb does not handle this well yet. This is clearly a bug and only happens in this scenario, if the database holds a value for the duplication already, the conflict handling will work even though there are multiple entries for this key in the statement.

# Expectation

The expectation I have from cockroachdb is: If in the same bulk insert statement a key conflict exists and there is an `ON CONFLICT DO NOTHING`, write the first value and ignore further ones. This is how they would be treated should a value exist in the database already anyways though.

**To Reproduce**

Create a table with some unique value (we had a primaryKey spanned over 3 columns) and execute a bulk statement. The table should not have any record yet with the same key.

`INSERT INTO "table" ("key1", "key2", "key3", "randomfield") VALUES (12,12,13,"1"), (12,12,13,"2") ON CONFLICT DO NOTHING`

**Comment by wzrdtales** [comment] 2020-01-30 15:54
@yuzefovich As always, here is my reproduction.

https://github.com/wzrdtales/cockroachdb-nukes/tree/master/bulkInsertConflict

Hope this gets fixed soon. I needed to build a very nasty workaround by falling back to inserting all entries from the failed batch as a single one. That slows down things drastically though.

**Comment by wzrdtales** [comment] 2020-01-30 15:54
required node version >= 10

**Comment by yuzefovich** [comment] 2020-01-30 16:42
Assigning to @dt for triage.

**Comment by yuzefovich** [comment] 2020-01-30 16:48
My bad, this is sql exec issue, assigning to @solongordon then.

**Comment by karlseguin** [comment] 2020-02-02 15:35
I think this is a duplicate of https://github.com/cockroachdb/cockroach/issues/37880

**Closed** 2020-03-05 19:55 UTC
Labels: O-community

**Comment by wzrdtales** [comment] 2020-04-15 12:04
@andy-kimball was that fixed already? tested latest stable version right now and doesn't seem to be there yet

**Comment by yuzefovich** [comment] 2020-04-15 14:04
It has been fixed on 19.2 and 20.1 branches, but there has been no stable release of those versions yet, the fix will be in the next stable versions.

**Comment by andy-kimball** [comment] 2020-04-15 14:24
Actually, it's only fixed in 20.1. You can try out the latest release candidate here: http://cockroachlabs.com/docs/releases/v20.1.0-rc.1.htmld

**Comment by wzrdtales** [comment] 2020-04-15 15:42
@andy-kimball Unfortunately there is no docker container for that version^^
