### ISSUE TITLE
circleci: failed tests: TestDockerReadWriteForwardReferenceVersion 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8893] opened 2016-08-29 17:25 UTC
The following test appears to have failed:

[#21918](https://circleci.com/gh/cockroachdb/cockroach/21918):

```
+ finish
+ cat out
I160829 17:25:10.936553 acceptance/cluster/localcluster.go:671  stopping
I160829 17:25:10.936750 acceptance/cluster/localcluster.go:571  event stream done, resetting...: net/http: request canceled
I160829 17:25:10.936769 acceptance/cluster/localcluster.go:594  events monitor exits
--- FAIL: TestDockerReadWriteForwardReferenceVersion (18.48s)
	replication_test.go:46: replication test is a no-op for empty cluster
	replication_test.go:46: replication test is a no-op for empty cluster
	reference_test.go:33: non-zero exit code: 1
=== RUN   TestDockerMigration_7429
I160829 17:25:11.516004 acceptance/cluster/localcluster.go:299  Initializing Cluster reference:
{"name":"reference","nodes":[{"count":0,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160829 17:25:11.517777 acceptance/cluster/docker.go:106  ImagePull cockroachdb/builder:20160826-194528 already exists
I160829 17:25:11.996365 acceptance/cluster/localcluster.go:605  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.282697317
I160829 17:25:12.088162 acceptance/cluster/localcluster.go:556  events monitor starts
I160829 17:25:12.090103 acceptance/cluster/docker.go:106  ImagePull cockroachdb/postgres-test:20160705-1326 already exists
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:366: skipping since not run against remote cluster
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by paperstreet** [comment] 2016-08-29 18:29
Looks like the issue is

    + /forward-reference-version/cockroach quit
    Error: client/admin.go:101: GET request failed: http://localhost:8080/_admin/v1/quit, err: Get http://localhost:8080/_admin/v1/quit: EOF
    Failed running "quit"

@tamird Any opinion on whether the answer here to make quit more resilient or to make the test more resilient to quit failing?

**Comment by tamird** [comment] 2016-08-29 18:33
Hm. `client/admin.go` doesn't seem to be a thing, so my guess is that it's already resilient in recent versions.

ISTM that all we can do is make the test more resilient.

**Comment by paperstreet** [comment] 2016-08-29 18:38
Oh right. This quit is being run on an old beta, so fixing it in code now wouldn't do anything anyway. Will fix

**Comment by paperstreet** [comment] 2016-08-31 21:36
I dug into this, but the real fix for the issue (retrying quit until it succeeds) might not be worth the complexity if this is the only time we ever see this flake. Let's wait for another repro.

**Comment by tamird** [comment] 2016-10-04 17:44
Closing; doesn't seem to be any value in leaving it open.

**Closed by tamird** 2016-10-04 17:44 UTC
Labels: Robot, test-failure
