### ISSUE TITLE
circleci: failed tests (14399): TestClusterRecovery 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5190] opened 2016-03-12 13:46 UTC
The following test appears to have failed:

[#14399](https://circleci.com/gh/cockroachdb/cockroach/14399):

```
W160312 13:44:03.056600 acceptance/chaos_test.go:247  round 2: monkey sleeping while cluster recovers...
W160312 13:44:06.358215 acceptance/chaos_test.go:251  round 2: cluster recovered
I160312 13:44:06.458708 acceptance/cluster/localcluster.go:629  stopping
I160312 13:44:06.458920 acceptance/cluster/localcluster.go:527  event stream done, resetting...: net/http: request canceled
I160312 13:44:06.458938 acceptance/cluster/localcluster.go:550  events monitor exits
--- FAIL: TestClusterRecovery (11.58s)
	chaos_test.go:269: pq: storage/store.go:1486: Rejecting command with timestamp in the future: 1457790242343498682 (306.854927ms ahead)
	chaos_test.go:269: pq: storage/store.go:1486: Rejecting command with timestamp in the future: 1457790242343498682 (302.740505ms ahead)
	chaos_test.go:153: pq: storage/store.go:1486: Rejecting command with timestamp in the future: 1457790242343498682 (301.262418ms ahead)
=== RUN   TestNodeRestart
I160312 13:44:08.346917 acceptance/cluster/localcluster.go:273  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
Node 2 - Store 0
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:64: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-17 13:49
Duplicate of #3087.

**Closed by petermattis** 2016-03-17 13:49 UTC
Labels: test-failure
