### ISSUE TITLE
sql: a crash with "invalid datum type given"

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#64290] opened 2021-04-27 20:24 UTC
Extracted from [here](https://github.com/cockroachdb/cockroach/issues/59840#issuecomment-827855797). Possibly related to (or a dup of) #59882.
```
SELECT
	1.358315355190809597E+27:::DECIMAL AS col_667, tab_383.col_666 AS col_668
FROM
	(VALUES ((-5.647958494757258370E+22):::DECIMAL)) AS tab_380 (col_662),
	(
		VALUES
			(
				'01040000C00900000001010000C0D7A94CA37B0F01C2E469F6B1F1E7F5C1969949F90D6DE4C1905EC1CD874EF5C101010000C0048D23BCA9E1F7C1BAB6FB011129F34146550F132B6AF041D4FF50311373EE4101010000C0ABFFC9680AE9F3C11EC4C9446D6B014264A345303F84F9C1344CC0C4BE55EC4101010000C011E72227616700C232ADC2DDB951F041E01A87AF3F66F34156E66951D0B8F44101010000C0326BBAE9EDB2F74110D23A2EFB25C341A45AD8FF106EE541A82560B4E86CFEC101010000C07C92243DD18ADDC118532B810DE0E24180AE1EA45FAED541862D23C2482FE6C101010000C080E71747CE06AD41F84454EDA92EED417A2E681B5B8FF7C1A81BA731A37D00C201010000C084C8473538B3ECC110DB91342C22F2C1B3C32FF4DE11F8C1B49181E57AE3FAC101010000C0A04A9329AD3CDF4194C5524AAFB3E9C116738D60736101C27047BBD56CA0E141':::GEOMETRY
			),
			(
				(
					WITH
						with_118 (col_663)
							AS (
								SELECT
									*
								FROM
									(
										VALUES
											(e'\rie\x0b\x1e/\x1cj':::STRING),
											(lower(e'kR\x1d4a\x01-':::STRING::STRING)::STRING)
									)
										AS tab_381 (col_663)
								UNION ALL
									SELECT
										*
									FROM
										(
											VALUES
												(e'-0\x01D3':::STRING),
												(e'H\x17zR(h':::STRING),
												('"':::STRING),
												('':::STRING),
												(e'f6\b8g':::STRING),
												(e'4R==\x13':::STRING)
										)
											AS tab_382 (col_664)
							)
					SELECT
						'01050000400500000001020000400200000090AF23A4E121F3C19656011E031B01C2EC62C9941451E74192C934C779DBE7C1983D57662CE300C2FC2628EAB87A02C201020000400A000000A00190015F43BB41009AB49ECFC9E5C1A64368A9D22FE4C1F5CFEA20DFA300C21480B484DBE3F9C10824E2B1A569D24100DC533E5CB46AC19A4A753995EAE9C1725835FE221EF8C19ED992A4F380EFC1D71135E435F9FFC1B22CF3ECD18AF141202D4516C76FDF41800236EFF6FF00C274E406D29E43FD419C82D51B047201429D2C3F73F9B4FFC10DADAAF9A655F2C140A44B95F13AF7412572F7325F41F2C1C03691C80261FE41366AB8DD97480042C4BCD70FF491F5C1803778B0ACC2D34144BB41820EC1E141404793AB3C74F54184217176AAEFF5414202D6AB4130E6C1386AF68A4C73F2414C66CAF72AA5EEC1010200004002000000A6CEBF6E0A33004200A09EDDD90ABC4100DD5B2ECAF4A1C180C29B0AD853A6C1A8236E077BC3EA41D21A23AA7819EEC1010200004002000000CE1504CB108FF24128639286251AE741E6B180BEBD76F4C18073BB082EE3BE4178964EE736C2FD41C62FFC16A03CE4C10102000040060000001C21A7A384CEFC4104A5443CB587F5C128106E69F38BEC418AF5B4DD8E28F941000611C9B36AA8C19826475C9107D24168342821F911FF4130DEFBAF669CE74120090A60D191ED41FA00BE8F7E63F3415204E75475F6F04184C3FC66A6C7DFC11EF8A981AD4CFA4138F93FFA80090242A62C73248D1FF3C14AD82B6188F600C2BA8E521F99590042749400F6E3A7FE41':::GEOMETRY
							AS col_665
					FROM
						with_118 AS cte_ref_32
					ORDER BY
						cte_ref_32.col_663 ASC, cte_ref_32.col_663 ASC
					LIMIT
						1:::INT8
				)
			),
			(
				'0103000000010000000500000000000000000000000000000000000000000000000000F03F0000000000000000000000000000F03F000000000000F03F0000000000000000000000000000F03F00000000000000000000000000000000':::GEOMETRY
			)
	)
		AS tab_383 (col_666)
ORDER BY
	tab_383.col_666, tab_380.col_662
LIMIT
	38:::INT8;
```
results in a crash with
```
* ERROR: [n1,client=127.0.0.1:61453,hostnossl,user=root] a panic has occurred!
* invalid datum type given: tuple{geometry, string}, expected geometry
* (1) attached stack trace
*   -- stack trace:
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:482
*   | runtime.gopanic
*   | 	/usr/local/opt/go/libexec/src/runtime/panic.go:965
*   | github.com/cockroachdb/cockroach/pkg/sql/rowenc.DatumToEncDatum
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:179
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createValuesSpecFromTuples
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:3016
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2764
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2745
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2732
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlan
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2661
*   | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:994
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1048
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:915
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529
*   | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450
*   | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:484
*   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
*   | 	/Users/yuzefovich/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626
* Wraps: (2) while executing: SELECT _:::DECIMAL AS _, _._ AS _ FROM (VALUES ((_):::DECIMAL)) AS _ (_), (VALUES (_:::GEOMETRY), (__more2__)) AS _ (_) ORDER BY _._, _._ LIMIT _:::INT8
```

**Comment by yuzefovich** [comment] 2021-04-27 20:29
Assigning to @michae2 for further triage and debugging.

**Comment by michae2** [comment] 2021-04-27 20:57
So far, I've got it down to:

```
demo@127.0.0.1:26257/movr> VALUES (1), ((WITH t(c) AS (SELECT 'a' UNION ALL SELECT 'b') SELECT 2 FROM t ORDER by c LIMIT 1));
  column1
-----------
        1
(1 row)
(error encountered after some results were delivered)
ERROR: internal error: invalid datum type given: tuple{int, string}, expected int
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:179: DatumToEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:181: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:226: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:87: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:284: next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:309: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:91: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:315: Next()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:175: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:803: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:384: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:357: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1001: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1048: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:915: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:659: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:122: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1527: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1529: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1450: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:484: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:626: func1()
runtime/asm_amd64.s:1371: goexit()
```

Explains:

```
demo@127.0.0.1:26257/movr> EXPLAIN VALUES (1), ((WITH t(c) AS (SELECT 'a' UNION ALL SELECT 'b') SELECT 2 FROM t ORDER by c LIMIT 1));
                                                    info
------------------------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • root
  │
  ├── • values
  │     size: 1 column, 2 rows
  │
  └── • subquery
      │ id: @S1
      │ original sql: (WITH t (c) AS (SELECT 'a' UNION ALL SELECT 'b') SELECT 2 FROM t ORDER BY c LIMIT 1)
      │ exec mode: one row
      │
      └── • render
          │ estimated row count: 1
          │
          └── • limit
              │ estimated row count: 1
              │ count: 1
              │
              └── • render
                  │ estimated row count: 2
                  │
                  └── • union all
                      │ estimated row count: 2
                      │
                      ├── • values
                      │     size: 1 column, 1 row
                      │
                      └── • values
                            size: 1 column, 1 row
(31 rows)

Time: 1ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/movr> EXPLAIN (OPT) VALUES (1), ((WITH t(c) AS (SELECT 'a' UNION ALL SELECT 'b') SELECT 2 FROM t ORDER by c LIMIT 1));
                       info
--------------------------------------------------
  values
   ├── (1,)
   └── tuple
        └── subquery
             └── project
                  ├── limit
                  │    ├── project
                  │    │    ├── union-all
                  │    │    │    ├── values
                  │    │    │    │    └── ('a',)
                  │    │    │    └── values
                  │    │    │         └── ('b',)
                  │    │    └── projections
                  │    │         └── "?column?"
                  │    └── 1
                  └── projections
                       └── 2
(17 rows)

Time: 1ms total (execution 1ms / network 0ms)
```

**Comment by yuzefovich** [comment] 2021-04-27 21:06
Oh, it's likely a dup of #64181 then.

**Comment by michae2** [comment] 2021-04-27 21:52
Yeah, I think it is. Got it down to `WITH t(c) AS (SELECT 'a' UNION ALL SELECT 'b') SELECT 2 FROM t ORDER by c LIMIT 1;` which matches that almost exactly. Duplicate of #64181

**Closed** 2021-04-29 04:00 UTC
Labels: C-bug
