### ISSUE TITLE
v19.1 split failed while applying backpressure: could not find valid split key

### ISSUE THREAD

**Issue by heidawei** [cockroachdb/cockroach#41064] opened 2019-09-25 09:33 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:
I try to insert rows to a table which has auto-increment column as pk, concurrent clients 10,
when the table rows count reach to 6000000+ and receive the error:

> split failed while applying backpressure: could not find valid split key

and I no longer  insert success after the error happened.
the fault range MVCC stats:

> **contains_estimates:false** last_update_nanos:1569396047255341376 intent_age:0 gc_bytes_age:3788962738568 **live_bytes:26** **live_count:1** key_bytes:77300729 **key_count:1** val_bytes:56917434 **val_count:6441727** intent_bytes:0 intent_count:0 sys_bytes:302 sys_count:5

I see the key count is 1, live count is 1, but value count is 6441727, it is weird. I suspect the stats is wrong.
I review the code for MVCCFindSplitKey, only when:
`it.Seek(MakeMVCCMetadataKey(key.AsRawKey()))
	if ok, err := it.Valid(); err != nil {
		return nil, err
	} else if !ok {
		return nil, nil
	}`
it.Valid() not OK, is it means there are no keys in the range??

**To Reproduce**

**Expected behavior**

**Additional data / screenshots**

**Environment:**
CockroachDB version: 19.1
Server OS: Linux/CentOS 6
Client app: Go pq driver

**Additional context**

**Comment by dcadevil** [comment] 2019-09-25 11:08
![image](https://user-images.githubusercontent.com/14159754/65595661-d239cc80-dfc7-11e9-8f73-38159f1d3a55.png)

**Comment by heidawei** [comment] 2019-09-26 06:19
I think I find the bug for MVCC stats. 
https://github.com/cockroachdb/cockroach/blob/c0406fd6fa6c4792812b29826e515b1dfaa94c87/pkg/storage/engine/mvcc.go#L224-L378

when the orig has no TXN, than the KeyBytes and ValueBytes is inaccurate, the bug code is here
https://github.com/cockroachdb/cockroach/blob/c0406fd6fa6c4792812b29826e515b1dfaa94c87/pkg/storage/engine/mvcc.go#L346-L358

if the TXN is 1PC TXN, the orig has no TXN!!!!, but compute NEW record, we ADD the keyBytes and valueBytes, the code is here
https://github.com/cockroachdb/cockroach/blob/c0406fd6fa6c4792812b29826e515b1dfaa94c87/pkg/storage/engine/mvcc.go#L364-L371

so when I update a row for many many times, the key count is 1, but value count is big and KeyBytes, ValueBytes is more than 64MB, but can not found split key, because there is only one key in the range

**Comment by heidawei** [comment] 2019-09-26 06:47
when update the row, orig TXN == nil, so the MVCC stats is inaccurate, It has nothing to do with 1PC TXN.

**Comment by tbg** [comment] 2019-09-27 08:47
Hmm, I'm not sure I understand where the issue is. From your description it appears that you have a row that you're updating frequently (the auto_increment counter). This one key (`key_count=1`) will have many many versions (`val_count=6441727`), even though only the most recent version is "live" (`live_count=1`).

The reason no split key can be found is because a split can only be carried out between keys. But you have only one key, and that key has tons of versions. We can't split the key into two keys with half the versions each.

The support team should give you the best advice to resolve this situation. Usually the suggestions are a) to move away from auto_increment (it's not a good thing in a distributed database anyway) and to reduce the GC TTL. @roncrdb, could you help @heidawei out?

**Comment by heidawei** [comment] 2019-09-27 09:04
@tbg  I know the auto_increment is not good scene for NewSQL database, but In the field of e-commerce, a table abort inventory, we need update one row frequently. so I try to fix the "bug", when check range split, if the live count < 2, we do not split range.

**Comment by heidawei** [comment] 2019-09-27 09:12
add this check,  there is no split errror by this issue  in our scene

**Comment by roncrdb** [comment] 2019-10-01 14:36
Hey @heidawei,

For a quick solution to removing this error, you need to lower the GC TTL for the table that you're updating. The default is set for 25 hours (90000 seconds). Lowering this would allow you to clean up the older values. You need to run: 

`ALTER RANGE default CONFIGURE ZONE USING gc.ttlseconds = <NEW VALUE IN SECONDS>;`

Please note, this wouldn't be a long term solution as keeping you GC at a low value could effect things like `AS OF SYSTEM TIME` queries and also Full and Incremental backups. 

Also, could you share your schema and the insert query that is updating the row frequently? 

Thanks

**Comment by lunevalex** [comment] 2020-07-29 21:32
Closing this due to age and based on the final response from @roncrdb. If you think this issue has been closed in error, please let us know and we will look into it again.

**Closed** 2020-08-10 17:11 UTC
Labels: O-community
