### ISSUE TITLE
sql: unable to add unique index on 21.1 beta on multi-region partitioned table

### ISSUE THREAD

**Issue by daniel-crlabs** [cockroachdb/cockroach#63653] opened 2021-04-14 18:41 UTC
**Describe the problem**

Customer is unable to create unique index on multi-region partitioned table.

error: (customer did not provide full stack trace)

```
root@:26257/defaultdb> alter table p add another_id int unique;
ERROR: internal error: relation "p" (56): table has PARTITION ALL BY defined, but index p_another_id_key does not have matching PARTITION BY
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:163: ValidateCrossReferences()
```

**Additional data**

Table ddl:

```
show create table p;

  table_name |                                                                      create_statement

-------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------

  p          | CREATE TABLE public.p (

             |     id INT8 NOT NULL,

             |     data INT8 NULL,

             |     crdb_region public.crdb_internal_region NOT VISIBLE NOT NULL DEFAULT default_to_database_primary_region(gateway_region())::public.crdb_internal_region,

             |     CONSTRAINT "primary" PRIMARY KEY (id ASC),

             |     FAMILY "primary" (id, data, crdb_region)

             | ) LOCALITY REGIONAL BY ROW

(1 row)

 

Time: 5.674s total (execution 5.461s / network 0.213s)
```

Regions:

```
root@172.27.3.17:26257/demodb> SHOW REGIONS FROM CLUSTER;

    region   | zones

-------------+--------

  eu-central | {}

  us-east    | {}

  us-west    | {}

(3 rows)
```

```
root@172.27.3.17:26257/demodb> SHOW REGIONS FROM database defaultdb;

  database  |   region   | primary | zones

------------+------------+---------+--------

  defaultdb | us-east    |  true   | {}

  defaultdb | eu-central |  false  | {}

  defaultdb | us-west    |  false  | {}

(3 rows)
```

**Environment:**
 - CockroachDB version 21.1 beta 2

**Additional context**

The customer has been able to get around this issue with the following workaround:

> Not to rely on implicit crdb_region column. Instead we use explicitly defined column and explicitely defined primary key that includes it.

**Comment by solongordon** [comment] 2021-04-14 18:48
Duplicate of https://github.com/cockroachdb/cockroach/issues/63113

**Closed by solongordon** 2021-04-14 18:48 UTC
Labels: A-sql-execution, C-bug, O-support, S-1-blocking-adoption, T-sql-experience
