### ISSUE TITLE
logictest: TestPlannerLogic/5node-dist/distsql_interleaved_join failed

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#37698] opened 2019-05-21 18:22 UTC
```
=== PAUSE TestPlannerLogic/5node-dist/distsql_interleaved_join
            logic.go:2316: 
                 
                testdata/planner_test/distsql_interleaved_join:106: SELECT start_key, end_key, replicas, lease_holder FROM [SHOW EXPERIMENTAL_RANGES FROM TABLE parent1]
                expected:
                    start_key                   end_key                     replicas  lease_holder
                    NULL                        /2/#/56/1/42/2/#/58/1/2     {1}       1
                    /2/#/56/1/42/2/#/58/1/2     /4/#/55/1/44                {2}       2
                    /4/#/55/1/44                /6/#/56/1/46/6/#/58/1/6     {3}       3
                    /6/#/56/1/46/6/#/58/1/6     /8                          {4}       4
                    /8                          /10/#/56/1/50/10/#/58/1/10  {5}       5
                    /10/#/56/1/50/10/#/58/1/10  /12/#/55/1/52               {1}       1
                    /12/#/55/1/52               /14/#/56/1/54/14/#/58/1/14  {2}       2
                    /14/#/56/1/54/14/#/58/1/14  /16                         {3}       3
                    /16                         /18/#/56/1/58/18/#/58/1/18  {4}       4
                    /18/#/56/1/58/18/#/58/1/18  /20/#/55/1/60               {5}       5
                    /20/#/55/1/60               /22/#/56/1/62/22/#/58/1/22  {1}       1
                    /22/#/56/1/62/22/#/58/1/22  /24                         {2}       2
                    /24                         /26/#/56/1/66/26/#/58/1/26  {3}       3
                    /26/#/56/1/66/26/#/58/1/26  /28/#/55/1/68               {4}       4
                    /28/#/55/1/68               /30/#/56/1/70/30/#/58/1/30  {5}       5
                    /30/#/56/1/70/30/#/58/1/30  /32                         {1}       1
                    /32                         /34/#/56/1/74/34/#/58/1/34  {2}       2
                    /34/#/56/1/74/34/#/58/1/34  /36/#/55/1/76               {3}       3
                    /36/#/55/1/76               /38/#/56/1/78/38/#/58/1/38  {4}       4
                    /38/#/56/1/78/38/#/58/1/38  NULL                        {5}       5
                    
                but found (query options: "colnames") :
                    start_key                   end_key                     replicas  lease_holder
                    NULL                        /2/#/57/1/42/2/#/59/1/2     {1}       1
                    /2/#/57/1/42/2/#/59/1/2     /4/#/55/1/44                {2}       2
                    /4/#/55/1/44                /6/#/57/1/46/6/#/59/1/6     {3}       3
                    /6/#/57/1/46/6/#/59/1/6     /8                          {4}       4
                    /8                          /10/#/57/1/50/10/#/59/1/10  {5}       5
                    /10/#/57/1/50/10/#/59/1/10  /12/#/55/1/52               {1}       1
                    /12/#/55/1/52               /14/#/57/1/54/14/#/59/1/14  {2}       2
                    /14/#/57/1/54/14/#/59/1/14  /16                         {3}       3
                    /16                         /18/#/57/1/58/18/#/59/1/18  {4}       4
                    /18/#/57/1/58/18/#/59/1/18  /20/#/55/1/60               {5}       5
                    /20/#/55/1/60               /22/#/57/1/62/22/#/59/1/22  {1}       1
                    /22/#/57/1/62/22/#/59/1/22  /24                         {2}       2
                    /24                         /26/#/57/1/66/26/#/59/1/26  {3}       3
                    /26/#/57/1/66/26/#/59/1/26  /28/#/55/1/68               {4}       4
                    /28/#/55/1/68               /30/#/57/1/70/30/#/59/1/30  {5}       5
                    /30/#/57/1/70/30/#/59/1/30  /32                         {1}       1
                    /32                         /34/#/57/1/74/34/#/59/1/34  {2}       2
                    /34/#/57/1/74/34/#/59/1/34  /36/#/55/1/76               {3}       3
                    /36/#/55/1/76               /38/#/57/1/78/38/#/59/1/38  {4}       4
                    /38/#/57/1/78/38/#/59/1/38  NULL                        {5}       5
                    
                
            logic.go:2348: 
                testdata/planner_test/distsql_interleaved_join:131: error while processing
            logic.go:2349: testdata/planner_test/distsql_interleaved_join:131: too many errors encountered, skipping the rest of the input
```

**Comment by asubiotto** [comment] 2019-05-21 18:37
Looks like the table ID is different

**Comment by andy-kimball** [comment] 2019-05-23 19:03
We're getting a lot of instances of this issue. This isn't a planner/optimizer issue; I think the next step is to have a SQL Exec team member to take a closer look.

**Comment by asubiotto** [comment] 2019-05-23 19:27
I think Nathan's taking a look in #37751

**Comment by nvanbenschoten** [comment] 2019-05-23 23:37
Duplicate of #37751.

**Closed by nvanbenschoten** 2019-05-23 23:37 UTC
Labels: C-test-failure
