### ISSUE TITLE
adminui: databases page does not display tables in a certain database on a mixed cluster

### ISSUE THREAD

**Issue by spaskob** [cockroachdb/cockroach#47108] opened 2020-04-07 01:11 UTC
**Describe the problem**

The admin ui `databases` page does not display any tables in a given database but they do appear when running query `SHOW TABLES FROM <database>`

**To Reproduce**
1. Start 19.2.5 cluster
```
roachprod create $CLUSTER -n 4
roachprod stage $CLUSTER:1-3 release v19.2.5
roachprod stage $CLUSTER:4 workload
roachprod start $CLUSTER:1-3
```

2. Run workload
```
roachprod run $CLUSTER:4 -- ./workload run schemachange --init --concurrency=2 --verbose=true --max-ops=300 "{pgurl:1-3}"
```
Check that the database `schemachange` has some tables.

3. Upgrade node 1
```
roachprod stop $CLUSTER:1 --sig 2
roachprod stage $CLUSTER:1 cockroach
sleep 90
roachprod start $CLUSTER:1
```
4. Check the database page for database `schemachange` - there are no more tables there.

5. Run `SHOW TABLES`
```
roachprod sql $CLUSTER:1 -- -e "show tables from schemachange";
  table_name
+------------+
  table106
  table124
  <snip>
```

**Expected behavior**
The databases page should display all tables in database.

**Additional data / screenshots**
You can examine the cluster here:

**Environment:**
 - CockroachDB version [ node 1: 20.1 nodes 2 and 3: 19.2.5
 - Server OS: linux

**Comment by dhartunian** [comment] 2020-04-07 16:30
@spaskob not sure if I'm missing something here but in trying to reproduce the issue, I get a panic when I run the workload for the first time.

Then when i trigger again I get a state like this that continues to count up seconds but not print more sql statements to stdout:
```
ROLLBACK;
ERROR: index "primary" is in use as unique constraint (use CASCADE if you really want to drop it) (SQLSTATE XXUUU)
BEGIN
  ALTER TABLE "table1" RENAME COLUMN "col2_0" TO "col1_12";
ROLLBACK;
ERROR: cannot rename column "col2_0" because view "view10" depends on it (SQLSTATE 2BP01)
BEGIN
  DROP TABLE "table1";
ROLLBACK;
ERROR: cannot drop relation "table1" because view "view10" depends on it (SQLSTATE 2BP01)
BEGIN
  ALTER TABLE "table18" ALTER COLUMN "col19_8" DROP STORED;
ROLLBACK;
ERROR: column "col19_8" is not a computed column (SQLSTATE 42611)
BEGIN
  DROP SEQUENCE "seq20";
  ALTER TABLE "table18" DROP COLUMN "col19_6";
  ALTER VIEW "view10" RENAME TO "view10";
COMMIT;
ERROR: restart transaction: TransactionRetryWithProtoRefreshError: TransactionRetryError: retry txn (RETRY_SERIALIZABLE): "sql txn" id=413a3d2b key=/Table/SystemConfigSpan/Start rw=true pri=0.03558323 stat=PENDING epo=0 ts=1586276957.602821784,1 orig=1586276957.571063547,0 min=1586276957.571063547,0 max=1586276957.571287613,13 wto=false seq=17 (SQLSTATE 40001)
_elapsed___errors__ops/sec(inst)___ops/sec(cum)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)
    1.0s        0           18.9           20.0     24.1     71.3    104.9    104.9 err
    1.0s        0            3.8            4.0     15.2     48.2     48.2     48.2 ok
    2.0s        0            0.0           10.0      0.0      0.0      0.0      0.0 err
    2.0s        0            0.0            2.0      0.0      0.0      0.0      0.0 ok
    3.0s        0            0.0            6.7      0.0      0.0      0.0      0.0 err
    3.0s        0            0.0            1.3      0.0      0.0      0.0      0.0 ok
    4.0s        0            0.0            5.0      0.0      0.0      0.0      0.0 err
    4.0s        0            0.0            1.0      0.0      0.0      0.0      0.0 ok
    5.0s        0            0.0            4.0      0.0      0.0      0.0      0.0 err
    5.0s        0            0.0            0.8      0.0      0.0      0.0      0.0 ok
    6.0s        0            0.0            3.3      0.0      0.0      0.0      0.0 err
    6.0s        0            0.0            0.7      0.0      0.0      0.0      0.0 ok
```

Is this expected?

**Comment by dhartunian** [comment] 2020-04-07 16:35
I'm able to repro the issue but I see my CLI query hang as well as the old ui on 19.2.5 nodes so I do not think issue is limited to the new UI changes.

I can see the XHR requests to retrieve the db state stalling out in the browser so the problem is likely there.

**Comment by spaskob** [comment] 2020-04-07 17:02
The CLI query will hang while the workload is running. Can you try it after the workload finishes?

**Comment by dhartunian** [comment] 2020-04-07 22:12
Putting some log statements here in case they're clues:

```
spas-repro-sc-0001> I200407 21:18:39.628810 1238 server/server_update.go:52  [n1] failed attempt to upgrade cluster version, error: not all nodes are running the latest version yet (saw 19.2-16 and 19.2)
spas-repro-sc-0001> I200407 21:18:44.810988 192 server/status/runtime.go:498  [n1] runtime stats: 915 MiB RSS, 215 goroutines, 92 MiB/92 MiB/127 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 49.0 CGO/sec, 2.1/0.6 %(u/s)time, 0.0 %gc (0x), 279 KiB/745 KiB (r/w)net
spas-repro-sc-0001> I200407 21:18:54.811303 192 server/status/runtime.go:498  [n1] runtime stats: 916 MiB RSS, 216 goroutines, 56 MiB/119 MiB/127 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 50.0 CGO/sec, 2.6/0.6 %(u/s)time, 0.0 %gc (1x), 342 KiB/1.7 MiB (r/w)net
spas-repro-sc-0001> I200407 21:19:04.811274 192 server/status/runtime.go:498  [n1] runtime stats: 917 MiB RSS, 218 goroutines, 86 MiB/93 MiB/140 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 43.9 CGO/sec, 2.2/0.9 %(u/s)time, 0.0 %gc (0x), 299 KiB/768 KiB (r/w)net
spas-repro-sc-0001> E200407 21:19:11.958721 4017857 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "spas-repro-sc-0001> I200407 21:18:39.628810 1238 server/server_update.go:52  [n1] failed attempt to upgrade cluster version, error: not all nodes are running the latest version yet (saw 19.2-16 and 19.2)
spas-repro-sc-0001> I200407 21:18:44.810988 192 server/status/runtime.go:498  [n1] runtime stats: 915 MiB RSS, 215 goroutines, 92 MiB/92 MiB/127 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 49.0 CGO/sec, 2.1/0.6 %(u/s)time, 0.0 %gc (0x), 279 KiB/745 KiB (r/w)net
spas-repro-sc-0001> I200407 21:18:54.811303 192 server/status/runtime.go:498  [n1] runtime stats: 916 MiB RSS, 216 goroutines, 56 MiB/119 MiB/127 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 50.0 CGO/sec, 2.6/0.6 %(u/s)time, 0.0 %gc (1x), 342 KiB/1.7 MiB (r/w)net
spas-repro-sc-0001> I200407 21:19:04.811274 192 server/status/runtime.go:498  [n1] runtime stats: 917 MiB RSS, 218 goroutines, 86 MiB/93 MiB/140 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 43.9 CGO/sec, 2.2/0.9 %(u/s)time, 0.0 %gc (0x), 299 KiB/768 KiB (r/w)net
spas-repro-sc-0001> E200407 21:19:11.958721 4017857 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> E200407 21:19:11.958831 4017885 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> E200407 21:19:11.968708 4017899 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> E200407 21:19:11.971128 4017910 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> I200407 21:19:13.449782 187 gossip/gossip.go:567  [n1] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  3: 10.142.0.33:26257 (20h13m59s: infos 183376/140227 sent/received, bytes 25537102B/24128494B sent/received)
gossip server (0/3 cur/max conns, infos 183376/140227 sent/received, bytes 25537102B/24128494B sent/received)
spas-repro-sc-0001> I200407 21:19:13.748265 1238 server/server_update.go:52  [n1] failed attempt to upgrade cluster version, error: not all nodes are running the latest version yet (saw 19.2 and 19.2-16)
spas-repro-sc-0001> I200407 21:19:14.811437 192 server/status/runtime.go:498  [n1] runtime stats: 917 MiB RSS, 222 goroutines, 121 MiB/59 MiB/174 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 65.3 CGO/sec, 4.7/1.0 %(u/s)time," does not exist
spas-repro-sc-0001> E200407 21:19:11.958831 4017885 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> E200407 21:19:11.968708 4017899 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> E200407 21:19:11.971128 4017910 server/admin.go:339  admin-query-namespace-ID: crdb_internal.get_namespace_id(): crdb-internal-get-descriptor-id: column "parentSchemaID" does not exist
spas-repro-sc-0001> I200407 21:19:13.449782 187 gossip/gossip.go:567  [n1] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  3: 10.142.0.33:26257 (20h13m59s: infos 183376/140227 sent/received, bytes 25537102B/24128494B sent/received)
gossip server (0/3 cur/max conns, infos 183376/140227 sent/received, bytes 25537102B/24128494B sent/received)
spas-repro-sc-0001> I200407 21:19:13.748265 1238 server/server_update.go:52  [n1] failed attempt to upgrade cluster version, error: not all nodes are running the latest version yet (saw 19.2 and 19.2-16)
spas-repro-sc-0001> I200407 21:19:14.811437 192 server/status/runtime.go:498  [n1] runtime stats: 917 MiB RSS, 222 goroutines, 121 MiB/59 MiB/174 MiB GO alloc/idle/total, 598 MiB/702 MiB CGO alloc/total, 65.3 CGO/sec, 4.7/1.0 %(u/s)time,
```

Not sure yet if the `parentSchemaID` thing is part of the problem.

**Comment by dhartunian** [comment] 2020-04-08 14:09
@spaskob it looks like this issue is likely addressed by #47167. I don't think there's a separate client-side issue.

**Comment by dhartunian** [comment] 2020-04-08 14:10
Keeping this ticket open in our Release Blockers column to ensure that we test the fix.

**Comment by spaskob** [comment] 2020-04-08 18:21
Thanks this would make sense, I will re-test it and post if I still find
any problems.

**Comment by dhartunian** [comment] 2020-04-16 14:47
I believe this is fixed. Keeping open to verify and reproduce.

**Comment by ajwerner** [comment] 2020-07-06 17:41
Can we close this?

**Closed** 2020-07-24 18:28 UTC
Labels: A-webui-general
