### ISSUE TITLE
sql: retryable errors on auto-commit can result in duplicate results

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#19269] opened 2017-10-16 04:17 UTC
@tschottdorf I cannot make heads nor tails of this:

```
F171016 04:11:18.984054 12 server/server.go:1129  [n1] failed to run migration "populate initial version cluster setting table entry": update version: number of results 2 != expected 1
```

Occurs during race logic tests, but only on an 8CPU DO droplet. I.e., I've been running this:

```
make testrace PKG=./pkg/sql/logictest
```

Applied this diff to get some clarity:

```diff
diff --git a/pkg/sqlmigrations/migrations.go b/pkg/sqlmigrations/migrations.go
index 939c54f..385fb47 100644
--- a/pkg/sqlmigrations/migrations.go
+++ b/pkg/sqlmigrations/migrations.go
@@ -459,7 +459,7 @@ func populateVersionSetting(ctx context.Context, r runner) error {
 	); err == nil {
 		res.Close(ctx)
 	} else if err != nil {
-		return err
+		return errors.Wrap(err, "insert row")
 	}
 
 	pl := parser.MakePlaceholderInfo()
@@ -468,7 +468,7 @@ func populateVersionSetting(ctx context.Context, r runner) error {
 		session, "SET CLUSTER SETTING version = $1", &pl, 1); err == nil {
 		res.Close(ctx)
 	} else if err != nil {
-		return err
+		return errors.Wrap(err, "update version")
 	}
 	return nil
 }
```

So... `SET CLUSTER SETTING` is returning two results instead of one?! o_O 

/cc @dt @knz

**Comment by tschottdorf** [comment] 2017-10-16 10:40
I'm not sure, but I'd be surprised if this was a genuine problem with `SET CLUSTER VERSION`.

Can you uncomment this line:

```go
		return StatementResults{}, errors.Errorf("number of results %d != expected %d", a, e)
```

and then, after the `SET CLUSTER SETTING version`, `pretty.Print(res)`?

And, this is a complete shot in the dark, should

```
// Reset implements the ResultsGroup interface.
func (b *bufferedWriter) Reset(ctx context.Context) {
	if b.currentGroupResults != nil {
		b.currentGroupResults.Close(ctx)
		b.currentGroupResults = nil
	}
	b.resultInProgress = false
}
```

also clear `b.pastResults`? Maybe we're reusing an old `res` internally sometimes. Probably not, but that off-by-one has to come from somewhere.

**Comment by tschottdorf** [comment] 2017-10-16 10:40
cc @andreimatei

**Comment by benesch** [comment] 2017-10-16 14:34
```
sql.ResultList{
    {
        Err:          nil,
        Type:         0,
        PGTag:        "SET CLUSTER SETTING",
        RowsAffected: 0,
        Columns:      nil,
        Rows:         (*sqlbase.RowContainer)(nil),
    },
    {
        Err:          nil,
        Type:         0,
        PGTag:        "SET CLUSTER SETTING",
        RowsAffected: 0,
        Columns:      nil,
        Rows:         (*sqlbase.RowContainer)(nil),
    },
}panic: wtf [recovered]
```

```diff
diff --git a/pkg/sql/executor.go b/pkg/sql/executor.go
index 4a5c0d753..b10c001df 100644
--- a/pkg/sql/executor.go
+++ b/pkg/sql/executor.go
@@ -599,10 +599,10 @@ func (e *Executor) ExecuteStatementsBuffered(
 	}
 	// This needs to be the last error check since in the case of an error during
 	// execution this would swallow the true error.
-	if a, e := len(res.ResultList), expectedNumResults; a != e {
-		res.Close(session.Ctx())
-		return StatementResults{}, errors.Errorf("number of results %d != expected %d", a, e)
-	}
+	// if a, e := len(res.ResultList), expectedNumResults; a != e {
+	// 	res.Close(session.Ctx())
+	// 	return StatementResults{}, errors.Errorf("number of results %d != expected %d", a, e)
+	// }
 	return res, nil
 }
 
diff --git a/pkg/sqlmigrations/migrations.go b/pkg/sqlmigrations/migrations.go
index 939c54fa5..f29145467 100644
--- a/pkg/sqlmigrations/migrations.go
+++ b/pkg/sqlmigrations/migrations.go
@@ -36,6 +36,7 @@ import (
 	"github.com/cockroachdb/cockroach/pkg/util/retry"
 	"github.com/cockroachdb/cockroach/pkg/util/stop"
 	"github.com/cockroachdb/cockroach/pkg/util/timeutil"
+	"github.com/kr/pretty"
 	"github.com/pkg/errors"
 )
 
@@ -466,6 +467,10 @@ func populateVersionSetting(ctx context.Context, r runner) error {
 	pl.SetValue("1", parser.NewDString(v.String()))
 	if res, err := r.sqlExecutor.ExecuteStatementsBuffered(
 		session, "SET CLUSTER SETTING version = $1", &pl, 1); err == nil {
+		if len(res.ResultList) > 1 {
+			pretty.Print(res.ResultList)
+			panic("wtf")
+		}
 		res.Close(ctx)
 	} else if err != nil {
 		return err
```

**Comment by tschottdorf** [comment] 2017-10-16 15:05
Uhm, yeah. Color me confuzzled as well. Could someone from the SQL team take a look?

**Comment by knz** [comment] 2017-10-17 11:05
@justinj although this is not very close to your current working set, you've looked at pgwire recently and you'll want to get familiar with this area of the code if you want to work on the optimizations we discussed yesterday. Perhaps you can look at this as a learning experience?

**Comment by tschottdorf** [comment] 2017-10-23 11:34
@justinj assigning this your way, feel free to chuck it to someone else but it's unlikely that I'll have anything to contribute at this point.

**Comment by justinj** [comment] 2017-10-23 13:14
Sorry, missed this the first time I was mentioned, will take a look!

**Comment by nvanbenschoten** [comment] 2018-02-14 19:42
I'm running into this occasionally too while trying to fix `TestVersionUpgrade`.

```
F180214 19:33:22.933452 27 server/server.go:1246  [n1] failed to run migration "add system.users isRole column and create admin role": number of results 2 != expected 1
```

I'll see if I can figure out what's going on.

**Comment by nvanbenschoten** [comment] 2018-02-14 19:54
I'm seeing this when `ALTER TABLE system.users ADD COLUMN IF NOT EXISTS "isRole" BOOL NOT NULL DEFAULT false` is run, so this doesn't look like an issue specifically with `SET CLUSTER SETTING`.

**Comment by nvanbenschoten** [comment] 2018-02-14 20:56
It looks like this is related to transaction retries and the `bufferedWriter` `ResultsWriter` implementation.

**Comment by nvanbenschoten** [comment] 2018-02-14 22:27
I looked into this with @andreimatei and it looks like this issue is actually larger than I originally thought. The TLDR is that it can result in any implicit transaction returning multiple full result sets.

The problem is that we [`Flush` the statement results for an `AutoRetry` transaction attempt](https://github.com/cockroachdb/cockroach/blob/814a7ee11e5b32c494579265bdf449897b2a1bc8/pkg/sql/executor.go#L1134) before attempting to [perform an auto-commit](https://github.com/cockroachdb/cockroach/blob/814a7ee11e5b32c494579265bdf449897b2a1bc8/pkg/sql/executor.go#L970). The auto-commit can then throw a retryable error, forcing us to retry the entire transaction. At this point, we [check](https://github.com/cockroachdb/cockroach/blob/a91d155c45cf1b340e56ade1af825938b7b0b5c9/pkg/sql/executor.go#L1026) `ResultsSentToClient` to decide whether it's safe to retry automatically on the gateway instead of sending the error up to the client. The issue is that `ResultsGroup.Flush` was meant to be scoped to an entire transaction and because of this, it [resets](https://github.com/cockroachdb/cockroach/blob/a91d155c45cf1b340e56ade1af825938b7b0b5c9/pkg/sql/pgwire/v3.go#L1068) the `hasSentResults` flag. This in turn makes `ResultsSentToClient` return false, which allows us to perform an auto-retry on the gateway after we've sent results to the client, resulting in duplicate results.

This can be used with the following patch to fail `TestTxnAutoRetry`:
```
diff --git a/pkg/sql/txn_restart_test.go b/pkg/sql/txn_restart_test.go
index 9da237eb7..c70d973a2 100644
--- a/pkg/sql/txn_restart_test.go
+++ b/pkg/sql/txn_restart_test.go
@@ -499,22 +499,22 @@ CREATE TABLE t.test (k INT PRIMARY KEY, v TEXT, t DECIMAL);
 		}, false)
 
 	if err := aborter.QueueStmtForAbortion(
-		"INSERT INTO t.test(k, v, t) VALUES (1, 'boulanger', cluster_logical_timestamp())", 2 /* abortCount */, true, /* willBeRetriedIbid */
+		"INSERT INTO t.test(k, v, t) VALUES (1, 'boulanger', cluster_logical_timestamp()) RETURNING 1", 2 /* abortCount */, true, /* willBeRetriedIbid */
 	); err != nil {
 		t.Fatal(err)
 	}
 	if err := aborter.QueueStmtForAbortion(
-		"INSERT INTO t.test(k, v, t) VALUES (2, 'dromedary', cluster_logical_timestamp())", 2 /* abortCount */, true, /* willBeRetriedIbid */
+		"INSERT INTO t.test(k, v, t) VALUES (2, 'dromedary', cluster_logical_timestamp()) RETURNING 1", 2 /* abortCount */, true, /* willBeRetriedIbid */
 	); err != nil {
 		t.Fatal(err)
 	}
 	if err := aborter.QueueStmtForAbortion(
-		"INSERT INTO t.test(k, v, t) VALUES (3, 'fajita', cluster_logical_timestamp())", 2 /* abortCount */, true, /* willBeRetriedIbid */
+		"INSERT INTO t.test(k, v, t) VALUES (3, 'fajita', cluster_logical_timestamp()) RETURNING 1", 2 /* abortCount */, true, /* willBeRetriedIbid */
 	); err != nil {
 		t.Fatal(err)
 	}
 	if err := aborter.QueueStmtForAbortion(
-		"INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp())", 2 /* abortCount */, true, /* willBeRetriedIbid */
+		"INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp()) RETURNING 1", 2 /* abortCount */, true, /* willBeRetriedIbid */
 	); err != nil {
 		t.Fatal(err)
 	}
@@ -534,20 +534,38 @@ CREATE TABLE t.test (k INT PRIMARY KEY, v TEXT, t DECIMAL);
 	// TODO(knz): This test can be made more robust by exposing the
 	// current allocation count in monitor and checking that it has the
 	// same value at the beginning of each retry.
-	if _, err := sqlDB.Exec(`
-INSERT INTO t.test(k, v, t) VALUES (1, 'boulanger', cluster_logical_timestamp());
+	rows, err := sqlDB.Query(`
+INSERT INTO t.test(k, v, t) VALUES (1, 'boulanger', cluster_logical_timestamp()) RETURNING 1;
 BEGIN;
-SELECT * FROM t.test;
-INSERT INTO t.test(k, v, t) VALUES (2, 'dromedary', cluster_logical_timestamp());
-INSERT INTO t.test(k, v, t) VALUES (3, 'fajita', cluster_logical_timestamp());
+INSERT INTO t.test(k, v, t) VALUES (2, 'dromedary', cluster_logical_timestamp()) RETURNING 1;
+INSERT INTO t.test(k, v, t) VALUES (3, 'fajita', cluster_logical_timestamp()) RETURNING 1;
 END;
-INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp());
+INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp()) RETURNING 1;
 BEGIN;
-INSERT INTO t.test(k, v, t) VALUES (5, 'josephine', cluster_logical_timestamp());
-INSERT INTO t.test(k, v, t) VALUES (6, 'laureal', cluster_logical_timestamp());
-`); err != nil {
+INSERT INTO t.test(k, v, t) VALUES (5, 'josephine', cluster_logical_timestamp()) RETURNING 1;
+INSERT INTO t.test(k, v, t) VALUES (6, 'laureal', cluster_logical_timestamp()) RETURNING 1;
+`)
+	if err != nil {
 		t.Fatal(err)
 	}
+	defer rows.Close()
+
+	rowsInserted := 0
+	for {
+		for rows.Next() {
+			rowsInserted++
+		}
+		if !rows.NextResultSet() {
+			break
+		}
+	}
+	if err := rows.Err(); err != nil {
+		t.Fatal(err)
+	}
+	if rowsInserted != 6 {
+		t.Fatalf("Expected 6 rows, got %d", rowsInserted) // fails with 10!
+	}
+
 	cleanupFilter()
 
 	checkRestarts(t, magicVals)
@@ -596,7 +614,7 @@ BEGIN;
 	}
 
 	// Continue the txn in a new request, which is not retriable.
-	_, err := sqlDB.Exec("INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp())")
+	_, err = sqlDB.Exec("INSERT INTO t.test(k, v, t) VALUES (4, 'hooly', cluster_logical_timestamp())")
 	if !testutils.IsError(
 		err, "RETRY_POSSIBLE_REPLAY") {
 		t.Errorf("didn't get expected injected error. Got: %v", err)
```

**Comment by nvanbenschoten** [comment] 2018-02-14 23:30
FWIW, this is fixed by https://github.com/cockroachdb/cockroach/pull/22277! We'll still need a fix for the current executor that we can cherry-pick back to 1.1.

**Closed** 2018-02-15 17:54 UTC
