### ISSUE TITLE
debug zip --redact-logs does not redact ranges

### ISSUE THREAD

**Issue by onno-vos-dev** [cockroachdb/cockroach#54499] opened 2020-09-17 09:00 UTC
**Describe the problem**

Even though the `--redact-logs` describes that it should only concern itself with redacting logs, there is still PII in the `ranges` files that are created under `debug/nodes/N/ranges/*json`. These ranges albeit I'm sure they're useful for debugging, can contain PII. One might be under the impression that `--redact-logs` takes care of every PII but that'd be wrong. It'd be good to find a way to truly get rid of all PII in the debug zip. 

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster
2. Create some table with PII in the primary key
3. debug zip
4. unpack zip
5. look at `debug/nodes/N/ranges/*json`

**Expected behavior**
Another flag is added like `--redact-ranges` is to redact this PII from the debug zip as well.

**Comment by knz** [comment] 2020-09-23 08:51
Thanks Onno for your report.

The range details are not part of the log files. `debug zip` can redact logs but does not redact the rest. This issue a really a duplicate of #52470.

**Closed by knz** 2020-09-23 08:51 UTC
Labels: C-bug, O-community, X-blathers-oncall
