### ISSUE TITLE
Unreplicating the first range

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#3483] opened 2015-12-17 18:41 UTC
The first range cannot be unreplicated from the first store.  This test will fail.

```
func TestUnreplicateFirstRange(t *testing.T) {
	defer leaktest.AfterTest(t)

	mtc := startMultiTestContext(t, 3)
	defer mtc.Stop()

	rangeID := roachpb.RangeID(1)
	// Replicate the range to store 1.
	mtc.replicateRange(rangeID, 0, 1)
	// Unreplicate the from from store 0.
	mtc.unreplicateRange(rangeID, 1, 0)
	// Replicate the range to store 2.
	// This operation will fail.
	mtc.replicateRange(rangeID, 1, 2)
}
```

**Comment by tschottdorf** [comment] 2015-12-17 18:43
logging hints at `DistSender` being unable to look up information from the first range.

**Comment by BramGruneir** [comment] 2015-12-17 18:43
```
I1217 13:39:55.642470 67014 kv/range_cache.go:129  lookup range descriptor: key=/Min
W1217 13:39:55.642630 67014 kv/dist_sender.go:562  key range /Min-/Min could not be located within a range on store
W1217 13:39:55.734003 67014 multiraft/multiraft.go:1139  failed to look up replica ID for range 1 (disabling replica ID check): storage/store.go:1695: store 1 not found as replica of range 1
```

**Comment by bdarnell** [comment] 2015-12-17 19:22
`multiTestContext` uses a manual clock, so the first store's lease will not expire on its own. Does it work if you advance the clock manually, or is there another issue at work here? It could also be gossip-related since that's how the first node is found.

**Comment by mrtracy** [comment] 2015-12-28 06:30
I think the issue is that multiTestContext's RangeDescriptorDB is set to m.senders[0].  That means that operations specific to range lookup only check the first store, whereas other operations which use `Send()` utilize the multiTestContext's special `rpcSend` function which can access all of the stores.

I did not fix this earlier because the RangeDescriptorDB interface was not exported from the storage package; I have a bad habit of treating exported package interfaces as sacred.  In any case, RangeDescriptorDB was already exported as part of another change, so (if my hunch is correct and this is the problem) this can be fixed by implementing FirstRange() and RangeLookup() on the multiTestContext, and then use the multiTestContext itself as the RangeDescriptorDB.

**Comment by BramGruneir** [comment] 2015-12-30 20:13
@bdarnell Advancing the clock manually doesn't help.

@mrtracy I think you're right.  I'm going to try to implement your solution.

**Closed** 2016-01-14 20:02 UTC
