### ISSUE TITLE
storage: client can cause reliable crash (using 2.0.1)

### ISSUE THREAD

**Issue by 474420502** [cockroachdb/cockroach#25270] opened 2018-05-03 04:57 UTC
**BUG REPORT**

```
*
* WARNING: RUNNING IN INSECURE MODE!
*
* - Your cluster is open for any client that can access 172.16.6.47.
* - Any user, even root, can log in without providing a password.
* - Any user, connecting as root, can read or write any data in your cluster.
* - There is no network encryption nor authentication, and thus no confidentiality.
*
* Check out how to secure your cluster: https://www.cockroachlabs.com/docs/v2.0/secure-a-cluster.html
*
CockroachDB node starting at 2018-05-03 03:57:34.112038378 +0000 UTC (took 2.8s)
build:               CCL v2.0.1 @ 2018/04/23 18:39:21 (go1.10)
admin:               http://172.16.6.47:8080
sql:                 postgresql://root@172.16.6.47:8811?sslmode=disable
logs:                /home/cockroach/db/data_8811/data/logs
temp dir:            /home/cockroach/db/data_8811/data/cockroach-temp442703280
external I/O path:   /home/cockroach/db/data_8811/data/extern
store[0]:            path=/home/cockroach/db/data_8811/data
status:              restarted pre-existing node
clusterID:           baaf1724-a023-4530-bb07-bd38f53dc54b
nodeID:              1
```

```
start.sh
port=8811
hostname=172.16.6.47
if [ ! -d "data_$port" ]; then
    mkdir data_$port
fi
cd data_$port
screen -L -dmS cockroach_$port  cockroach start --insecure \
--host=$hostname \
--port=$port \
--store=data
```

Only One Node

Crash After I Test Insert data

```
goroutine 228 [running]:
runtime/debug.Stack(0x38d9eb00, 0xed27c7f6c, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc4f3fa2900, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1756 +0x128
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4f3fa2900, 0xed27c7f00, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1679 +0x6fe
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc4299df180, 0x2771c80, 0xc44c541ec0, 0xc4d3107b20, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5043 +0x4d5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc4299df180, 0x2771c80, 0xc44c541ec0, 0xc4d3107b20, 0x8, 0x6, 0x56, 0x100000001, 0x1, 0x3, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4748 +0x55a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc4299df180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3664 +0x12c8
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReady(0xc4299df180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3365 +0xdb
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processReady(0xc4208d8800, 0x2771c80, 0xc4208c8000, 0x5)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3909 +0xda
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42002e2d0, 0x2771c80, 0xc4208c8000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:215 +0x259
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2771c80, 0xc4208c8000)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc4202de390, 0xc4201d5680, 0xc4202de380)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
```

go code: 
```
package main

import (
	"database/sql"
	"log"
	"runtime/debug"
	"strconv"
	"sync"
	"time"

	"github.com/lib/pq"
	"github.com/zheng-ji/goSnowFlake"
)

func ErrorPanic(err error) {
	if err != nil {
		panic(err)
	}
}

func CreateData1(wg *sync.WaitGroup, db *sql.DB, iw *goSnowFlake.IdWorker, icount int) {
	tx, err := db.Begin()
	defer func() {
		if err := recover(); err != nil {
			log.Println(err)
			debug.PrintStack()
			tx.Rollback()
		}
	}()

	var l []string
	for i := 0; i <= icount; i++ {
		id, err := iw.NextId()
                ErrorPanic(err)
		ids := strconv.FormatInt(id, 16)

		l = append(l, ids)
	}

	stmt, err := tx.Prepare(pq.CopyIn("test", "uid", "url", "content"))
	ErrorPanic(err)

	for _, ids := range l {
		_, err = stmt.Exec(ids, ids, ids)
		ErrorPanic(err)
	}
	stmt.Close()
	ErrorPanic(tx.Commit())

	wg.Done()
}

func main() {
	db, err := sql.Open("postgres", "postgresql://root@172.16.6.47:8811/log?sslmode=disable")
	ErrorPanic(err)
	if err := db.Ping(); err != nil {
		panic(err)
	}

	icount := 5000

	start := time.Now().Unix()

	wg := &sync.WaitGroup{}

	gnums := 10
	for i := 0; i <= gnums; i++ {
		wg.Add(1)
		iw, err := goSnowFlake.NewIdWorker(int64(i*2 + 1))
		ErrorPanic(err)
		go CreateData1(wg, db, iw, icount)
	}

	wg.Wait()
	log.Println("time cost:", float32(icount*gnums)/float32(time.Now().Unix()-int64(start)))
}
```

**Comment by knz** [comment] 2018-05-03 16:27
cc @tschottdorf for triage

**Comment by 474420502** [comment] 2018-05-04 13:15
I commit the data of large batch . so that block the commit of process. and ctrl + c terminate the process that is inserting data. 
i think it is reason that crashing cockroackdb;
but i can't reproduce it;

**Comment by tschottdorf** [comment] 2018-05-04 15:29
Thanks for your report, @474420502. What's the error message for the fatal crash you have observed? It is printed before the stack trace (which you have posted).

**Comment by 474420502** [comment] 2018-05-04 17:44
[error.log](https://github.com/cockroachdb/cockroach/files/1975389/error.log)
All logs here @tschottdorf

**Comment by 474420502** [comment] 2018-05-05 05:10
i see  the actual process crash .
the process is disappear!
i run main.go that adjustment parameters.
i forget  a lot! @tschottdorf

**Comment by tschottdorf** [comment] 2018-05-05 05:15
Hmm, too bad. Could you let us know if you get another crash? If we can reproduce this ourselves, it will be a lot easier to look into. Thanks!

**Comment by 474420502** [comment] 2018-05-05 06:32
ok! 
I hope cockroachdb is getting better! :smile: :+1:

**Comment by tschottdorf** [comment] 2018-05-05 11:13
> I hope cockroachdb is getting better! 😄 👍

That's all we're working on! 😄

**Comment by tschottdorf** [comment] 2018-05-14 18:02
Nothing actionable here at the moment. I assume the crash would be caused by the OOM killer due to lack of memory accounting below the SQL layer, but without a repro, there's no telling. @474420502 if you see this again, please let us know!

**Comment by yiv** [comment] 2018-05-17 09:11
![qq 20180517171038](https://user-images.githubusercontent.com/16640312/40168144-5190e0ea-59f5-11e8-9a86-01e5309983c3.png)
same issue
```
I180517 09:00:08.383719 225220 util/mon/bytes_usage.go:576  distsql: bytes usage increases to 2.1 MiB (+133120)
I180517 09:00:08.383767 225220 util/mon/bytes_usage.go:576  flow: bytes usage increases to 2.1 MiB (+133120)
I180517 09:00:08.850064 225220 util/mon/bytes_usage.go:576  distsql: bytes usage increases to 4.1 MiB (+256000)
I180517 09:00:08.850092 225220 util/mon/bytes_usage.go:576  flow: bytes usage increases to 4.1 MiB (+256000)
I180517 09:00:08.856905 225222 util/mon/bytes_usage.go:576  [n2,HashJoiner] hashjoiner-limited: bytes usage increases to 1.0 MiB (+51200)
I180517 09:00:09.582807 225222 util/mon/bytes_usage.go:576  [n2,HashJoiner] hashjoiner-limited: bytes usage increases to 2.0 MiB (+10240)
I180517 09:00:10.852009 1359 server/status/runtime.go:219  [n2] runtime stats: 3.8 GiB RSS, 305 goroutines, 301 MiB/322 MiB/705 MiB GO alloc/idle/total, 2.6 GiB/3.2 GiB CGO alloc/total, 14785.08cgo/sec, 2.43/0.23 %(u/s)time, 0.00 %gc (8x)
I180517 09:00:20.852379 1359 server/status/runtime.go:219  [n2] runtime stats: 3.7 GiB RSS, 280 goroutines, 232 MiB/254 MiB/568 MiB GO alloc/idle/total, 2.6 GiB/3.2 GiB CGO alloc/total, 71568.42cgo/sec, 1.93/0.13 %(u/s)time, 0.00 %gc (6x)
I180517 09:00:30.855255 1359 server/status/runtime.go:219  [n2] runtime stats: 3.7 GiB RSS, 278 goroutines, 261 MiB/228 MiB/568 MiB GO alloc/idle/total, 2.7 GiB/3.2 GiB CGO alloc/total, 10088.46cgo/sec, 1.25/0.10 %(u/s)time, 0.00 %gc (4x)
E180517 09:00:40.353650 207117 server/server.go:1537  [n2,client=128.1.38.33:42932] write tcp 172.19.0.3:26257->128.1.38.33:42932: write: broken pipe
E180517 09:00:40.404808 207222 server/server.go:1537  [n2,client=128.1.38.33:42920] write tcp 172.19.0.3:26257->128.1.38.33:42920: write: broken pipe
I180517 09:00:40.888205 1359 server/status/runtime.go:219  [n2] runtime stats: 4.0 GiB RSS, 290 goroutines, 376 MiB/428 MiB/910 MiB GO alloc/idle/total, 2.7 GiB/3.2 GiB CGO alloc/total, 9420.09cgo/sec, 1.56/0.16 %(u/s)time, 0.01 %gc (7x)
W180517 09:00:50.476143 1287 storage/store.go:3920  [n2,s2] handle raft ready: 0.9s [processed=0]
I180517 09:00:50.848902 1356 gossip/gossip.go:487  [n2] gossip status (ok, 3 nodes)
gossip client (1/3 cur/max conns)
  1: cockroach1:26257 (8m4s: infos 190/3035 sent/received, bytes 48008B/1630946B sent/received)
gossip server (0/3 cur/max conns, infos 190/3035 sent/received, bytes 48008B/1630946B sent/received)
I180517 09:00:51.228205 1359 server/status/runtime.go:219  [n2] runtime stats: 6.4 GiB RSS, 347 goroutines, 2.0 GiB/1.1 GiB/3.3 GiB GO alloc/idle/total, 2.7 GiB/3.2 GiB CGO alloc/total, 1376.31cgo/sec, 2.71/0.35 %(u/s)time, 0.30 %gc (5x)
W180517 09:00:52.005114 1282 storage/engine/rocksdb.go:1755  batch [23/1914/0] commit took 741.784213ms (>500ms):
goroutine 1282 [running]:
runtime/debug.Stack(0xf96b9e8, 0xed28f3bc3, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc420bf2480, 0xc43fd7c400, 0x1ea, 0x400)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1756 +0x128
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc420bf2480, 0xed28f3b00, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1679 +0x6fe
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).applyRaftCommand(0xc42090bc00, 0x2771c80, 0xc427083a70, 0xc430c828f0, 0x8, 0xc428462690, 0x4c, 0x50, 0xc4284626e0, 0x45, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:5043 +0x4d5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).processRaftCommand(0xc42090bc00, 0x2771c80, 0xc427083a70, 0xc430c828f0, 0x8, 0x1c2, 0x796cb, 0x100000001, 0x1, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4748 +0x55a
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).handleRaftReadyRaftMuLocked(0xc42090bc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:3664 +0x12c8
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue.func1(0x2771c80, 0xc4380a9a10, 0xc42090bc00, 0x2771c80)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3862 +0x109
github.com/cockroachdb/cockroach/pkg/storage.(*Store).withReplicaForRequest(0xc4200b4c00, 0x2771c80, 0xc4380a9a10, 0xc42751bf10, 0xc430887ed0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3184 +0x135
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc4200b4c00, 0x2771c80, 0xc42700ef00, 0x14bb)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3850 +0x229
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc42002a3f0, 0x2771c80, 0xc42700ef00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:226 +0x21b
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2(0x2771c80, 0xc42700ef00)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:166 +0x3e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420318db0, 0xc420948240, 0xc420318da0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:192 +0xe9
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0xad
W180517 09:00:52.020631 1268 storage/store.go:3920  [n2,s2] handle raft ready: 0.8s [processed=0]
W180517 09:00:52.028634 1222 storage/store.go:3920  [n2,s2] handle raft ready: 0.8s [processed=0]

```

**Comment by metalmatze** [comment] 2018-09-24 16:49
I can see the same stack trace running on my [Typhoon cluster](https://typhoon.psdn.io/) v1.11.2 with a StatefulSet. In the events for that namespace I can see that the probes are failing.

```
46m         9h           117       cockroachdb-1.155745066d812e0a   Pod       spec.containers{cockroachdb}   Warning   Unhealthy   kubelet, 10.135.109.194   Readiness probe failed: HTTP probe failed with statuscode: 503
6m          9h           797       cockroachdb-1.15574547eaaf3d21   Pod       spec.containers{cockroachdb}   Warning   Unhealthy   kubelet, 10.135.109.194   Readiness probe failed: Get http://10.2.4.62:8080/health?ready=1: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
33m         9h           260       cockroachdb-1.15574548ad10f5fb   Pod       spec.containers{cockroachdb}   Warning   Unhealthy   kubelet, 10.135.109.194   Liveness probe failed: Get http://10.2.4.62:8080/health: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
56m         9h           58        cockroachdb-1.155745696bcbcd18   Pod       spec.containers{cockroachdb}   Warning   Unhealthy   kubelet, 10.135.109.194   Readiness probe failed: Get http://10.2.4.62:8080/health?ready=1: dial tcp 10.2.4.62:8080: connect: connection refused
1m          9h           163       cockroachdb-1.155745f0d75da90e   Pod       spec.containers{cockroachdb}   Warning   BackOff     kubelet, 10.135.109.194   Back-off restarting failed container
```

Interstingly enough, the other 2 replicas in my cluster are stable.
Any idea? I'm happy to debug further, if you tell me what infos you need.

**Comment by tschottdorf** [comment] 2018-09-25 09:39
Hi @metalmatze, this issue generally indicates that there is some problem writing data to disk in a timely manner. How many ranges does your cluster have (approximately) and what storage medium are you running on (i.e. local SSD, ...)? Is this server potentially overloaded?

**Comment by tschottdorf** [comment] 2018-09-26 11:52
(a `./cockroach debug zip` will be helpful, but it leaks potentially sensitive data via the log files, so you may want to contact me at `tobias@cockroachlabs.com`).

**Comment by metalmatze** [comment] 2018-09-26 17:46
I am running on big enough machines on DigitalOcean with Kubernetes Typhoon. The disks are normal DigitalOcean volumes that are mounted per pod, which are SSDs. 
Apparently one of my nodes went crazy (I think something with the network) and this was only one outcome of it all. nginx pods restarted just as much I saw later on...
After restarting the node it is all back to normal now.

Sorry for the noise. This can be closed from my side.
Thanks for CockrochDB, it's awesome! :tada:

**Comment by tschottdorf** [comment] 2018-09-26 19:05
Thanks for the heads up @metalmatze. Doing our best! Closing 🤞

**Closed by tschottdorf** 2018-09-26 19:05 UTC
Labels: A-core-persistence, C-investigation, O-community
