### ISSUE TITLE
sql: occasional error creating a table after dropping and recreating the database

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5868] opened 2016-04-05 14:47 UTC
If I run this repeatedly through `cockroach sql --insecure`:

```sql
DROP DATABASE TEST;
CREATE DATABASE TEST;
SET DATABASE=TEST;


CREATE TABLE kv (k INT PRIMARY KEY, v INT);

INSERT INTO kv VALUES (1, 1), (2, 2), (3, 3), (4, 1), (5, 2), (6, 3);

SELECT v,SUM(k) FROM kv GROUP by v;
```

I sometimes get this error:
```
DROP DATABASE
CREATE DATABASE
SET
CREATE TABLE
pq: sql/lease.go:108: table ID 159 not found
pq: sql/lease.go:108: table ID 159 not found
Error: pq: sql/lease.go:108: table ID 159 not found
```

It seems like we are trying to reuse some state from the previous database. @andreimatei is this similar with what you were seeing when dropping a table?

**Comment by vivekmenezes** [comment] 2016-04-05 15:36
This is the probably the same issue. The table descriptor cache caches
tables by name and the cache is pointing to the old descriptor ID. You are
reusing the name and hitting this problem.

**Comment by andreimatei** [comment] 2016-04-05 16:01
Yeah, this is a duplicate of #5484. I think I've finished a fix yesterday, need to clean it up a bit.

This issue in particular has to do with the name cache, like Vivek said. Unfortunately the name cache is currently different from the leasing system, and my fix is to the leasing, so the error I think will still be theoretically possible after the fix, but it should be pretty impossible to reproduce.
Leasing and this cache are both driven by gossip, and my fix adds a gossip update at DROP time.

**Closed** 2016-04-05 16:01 UTC

**Comment by tschottdorf** [comment] 2016-04-05 16:48
If you left it open, you could close it in your commit and make sure that you have a test that exercises this particular query.
