### ISSUE TITLE
client request can get lost when range is merged

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2312] opened 2015-09-01 01:35 UTC
The following test appears to have failed:

[#6707](https://circleci.com/gh/cockroachdb/cockroach/6707):

```
I0901 01:34:21.312058 1013 stopper.go:229  draining; tasks left:
1      storage/replica.go:1254
I0901 01:35:20.487935 1013 storage/replica.go:992  gossiping cluster id  from store 1, range 1
W0901 01:35:20.488024 1013 storage/store.go:593  error gossiping first range data: storage/replica.go:972: node is stopping
W0901 01:35:20.488566 1013 storage/store.go:612  error gossiping configs: storage/replica.go:972: node is stopping
panic: test timed out after 1m10s

goroutine 5387 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x1221c48, 0x174c580, 0xb9, 0xb9, 0x7de301)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
--
	/go/src/github.com/cockroachdb/cockroach/storage/id_alloc.go:130 +0x93d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820428120, 0xc8204800d0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x62
FAIL	github.com/cockroachdb/cockroach/storage	70.034s
=== RUN   TestBatchBasics
I0901 01:34:08.284690 981 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0901 01:34:08.285482 981 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0901 01:34:08.287797 981 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2015-09-01 10:50
`TestTree` does a lot of merges. I think what happens here is that an intent resolution starts, but before the command commits the range is merged away, leaving the caller hanging as it waits for its command to pop out of `Raft` on the now-merged `Replica`. Relevant log section:

> E0901 01:34:21.201696 1013 storage/store.go:1533  storage/store.go:1532: got committed raft command for 21 but have no range with that ID: {RangeID:21 OriginNodeID:100000001 Cmd:{[...] ResolveIntent:header:<timestamp:<wall_time:0 logical:4282 > cmd_id:<wall_time:0 random:0 > key:"\000\000\000kt\000\001rtn-" replica:<node_id:1 store_id:1 replica_id:1 > range_id:21 txn:<name:"storage/replica_command.go:1267 (*Replica).AdminMerge" key:"\000range-tree-root" id:"\r\030%0o\227D\254\213\217H\301\007\3350S" priority:1384259902 isolation:SERIALIZABLE status:COMMITTED epoch:0 timestamp:<wall_time:0 logical:3993 > orig_timestamp:<wall_time:0 logical:3993 > max_timestamp:<wall_time:0 logical:3993 > certain_nodes:<> Writing:true > read_consistency:CONSISTENT >  [...]}}

and then the hanging goroutine (during quiesce):

>
goroutine 5359 [chan receive, 1 minutes]:
github.com/cockroachdb/cockroach/storage.(*Replica).addWriteCmd(0xc820416b40, 0x7fe10b694d80, 0xc8201fa2a0, 0x7fe10b69d3c0, 0xc820302100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:734 +0x6a5
[...]
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:123 +0x221

From the looks of it, I'm guessing that we don't properly go through the `pendingCmds` of the range which is being merged and notify waiting clients (i.e. send a `GroupDeletedError` which is converted to a `RangeKeyMismatchError`).

**Comment by tschottdorf** [comment] 2015-09-02 07:52
I'm also seeing this on `TestStoreRangeMergeNonConsecutive` in my WIP.

**Comment by bdarnell** [comment] 2015-09-02 23:17
We do cancel pending commands after a merge (Store.MergeRange calls RemoveReplica which calls MultiRaft.RemoveGroup). I think the problem is that Store.RemoveReplica is not atomic: we remove the group from raft (canceling the pending calls) before we grab the lock and remove the replica from the store. While we're waiting for the lock a new command could be proposed but this command would never get cleaned up. That means this is a duplicate of #1911.

**Comment by tamird** [comment] 2015-09-03 02:05
Also seen in #1839 https://circleci.com/gh/cockroachdb/cockroach/6795

**Closed** 2015-09-04 20:50 UTC
Labels: test-failure
