### ISSUE TITLE
sql/colexec/colbuilder: consider pooling render operators

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#88525] opened 2022-09-22 22:23 UTC
**Is your feature request related to a problem? Please describe.**

Likely fallout from https://github.com/cockroachdb/cockroach/pull/83689, we now see 5+% of bytes allocated in tpcc due to these operators:
![Screen Shot 2022-09-22 at 6 02 48 PM](https://user-images.githubusercontent.com/1839234/191861740-a3dda3c3-5a66-4700-be1d-f18261dc0fd5.png)

**Describe the solution you'd like**
We pool other operators, we could pool these.

Jira issue: CRDB-19943

**Comment by ajwerner** [comment] 2022-09-22 22:46
Here's a fresh profile. I'm worried I let the server keep running without load for too long such that actually these allocations are bogus 😓 

[profile (10).pb.gz](https://github.com/cockroachdb/cockroach/files/9629835/profile.10.pb.gz)

**Comment by yuzefovich** [comment] 2022-09-23 00:56
The first profile does look suspicious, the second one not as much but still. Marking as a GA-blocker since I believe there are some regressions in allocations for simple cases due to #83689.

**Comment by yuzefovich** [comment] 2022-09-23 00:57
@ajwerner do you remember what tpcc parameters you used?

**Comment by yuzefovich** [comment] 2022-09-23 20:34
Alright, I'm not sure how the first profile was obtained - I tried running TPCC and then also left the cluster idle, but I don't see anything similar. In particular, large allocations for `NewVecToDatumConverter` are suspicious - those objects are already pooled.

I did find multiple improvements though, so thanks for filing the issue!

**Comment by ajwerner** [comment] 2022-09-23 21:08
Feel free to close this whenever you feel done with it. Thanks for chasing!

**Comment by mgartner** [comment] 2022-09-26 13:39
I'm going to remove the release-blocker label for now. Feel free to close if you see fit @yuzefovich.

**Comment by yuzefovich** [comment] 2022-09-26 18:13
There is a perf / allocations regression due to #83689: namely that if we wrap a row-by-row processor into the vectorized flow but try to handle the render expressions through the columnar operators, yet we fail to do that (e.g. due to an unsupported expression), we will create an additional row-by-row processor for that rendering. Before #83689 we would create a single row-by-row processor, but now we will have two, which can increase the number of allocations.

Ideally we would check whether native vectorized rendering is possible before splitting out the rendering as done in #83689, but it's not that simple. So instead I have some improvements in #88608 that should alleviate (at least partially) the increase in allocations. Many queries could be affected (for example, mutations with RETURNING clause with some rendering in that clause). What's worse is that due to #85822 even for the supported render expressions we can actually fallback to handling  them the row-by-row processor due to #85822, so I still consider it a GA-blocker (not a beta blocker).

**Comment by yuzefovich** [comment] 2022-09-26 23:06
Alright, I'm removing the blocker label since my concern about the impact of #85822 on mutation statements was incorrect. In particular, the logic from #85822 would only kick in if we have an "estimated row count" during the vectorized planning, and we only propagate that information from the optimizer for the table readers.

**Closed** 2022-09-30 17:33 UTC
Labels: C-enhancement, branch-master, T-sql-queries, branch-release-22.2
