### ISSUE TITLE
debug/zip: capture the last x minutes of timeseries data

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#54202] opened 2020-09-10 17:33 UTC
The Support team has noted that collecting time series metrics from customers’ clusters usually requires asking the customer to take screenshots of their Admin UI. This often requires multiple round trips of communication with the customer.

Tobi noted that if we dump time series metrics from CockroachDB into our debug zips, it may be useful to generate grafana dashboards that can easily view the dumped data.

**Comment by tbg** [comment] 2020-10-07 13:16
https://github.com/cockroachdb/cockroach/issues/16584#issuecomment-704927971 has a relevant discussion and link to WIP PRs in this area.

**Comment by jordanlewis** [comment] 2020-10-07 21:33
I'll close this as a duplicate of #16584 in this case.

**Closed by jordanlewis** 2020-10-07 21:33 UTC
Labels: A-cli, C-enhancement
