### ISSUE TITLE
ui: Replica count does not go down to zero on dead node

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#24771] opened 2018-04-13 08:56 UTC
**Bug report**

After starting ycsb against a 5-node local cluster running 2.0, reducing `server.time_until_store_dead` to 1 min, and then killing 1 node, the cluster marks the down node as dead after 1 min and rebalancing data to the other nodes but never reduces the replica count on the dead node to 0. To reproduce, just follow the steps on https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html.

I'm pretty sure this works fine on 1.1.

```
~/cockroachdb-training$ grep -F '[config]' node1/logs/cockroach.log
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] file created at: 2018/04/13 08:19:58
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] running on machine: JESSEs-MacBook-Pro
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] binary: CockroachDB CCL v2.0.0 (x86_64-apple-darwin13, built 2018/04/03 20:52:33, go1.10)
I180413 08:19:58.241060 1 util/log/clog.go:1104  [config] arguments: [./cockroach start --insecure --store=node1 --host=localhost --port=26257 --http-port=8080 --join=localhost:26257,localhost:26258,localhost:26259]
```

<img width="299" alt="screen shot 2018-04-13 at 4 55 54 am" src="https://user-images.githubusercontent.com/15893490/38726031-015402f8-3ed7-11e8-8724-83538b9359da.png">

<img width="873" alt="screen shot 2018-04-13 at 4 56 07 am" src="https://user-images.githubusercontent.com/15893490/38726038-0502f33c-3ed7-11e8-885a-638ad9c19052.png">

**Comment by couchand** [comment] 2018-04-24 15:46
I believe the problem is just that the replica count is always self-reported.  Perhaps @mrtracy has additional insight.

**Comment by mrtracy** [comment] 2018-04-24 16:03
Seems like a graph bug to me; in that graph screenshot, you can see that the line for node 5 ends, but the value is still reported as 44 in the tooltip.

**Comment by couchand** [comment] 2018-04-24 18:37
Good point, so it's a dupe of #23480 then.

**Closed by couchand** 2018-04-24 18:37 UTC
Labels: A-monitoring, A-webui, C-bug, S-3-ux-surprise
