### ISSUE TITLE
The state if a successful node decommission may not finalize to "decommissioned"

### ISSUE THREAD

**Issue by a-entin** [cockroachdb/cockroach#94433] opened 2022-12-29 19:19 UTC
This is the current behavior (up to 23.1):

If a user decommissioning a node either
1) rans the cockroach node decommission command with `--wait=all` (or without `--wait` since `all` is the default) and then interrupts (^C) it
or
2) rans the cockroach node decommission command with `--wait=none`

AND
the decommissioning ultimately succeeds
THEN
the status of the node will be stuck in "decommissioning" and will never finalize to "decommissioned".

The workaround is to repeat the decommission command, which will promptly succeeds and flips the state to "decommissioned".

The reason for that is that the state flip is effected by the CLI program at the end. Only the CLI (or its underlying API call) is able to finalize the "decommissioned" state. So if you interrupt the command, or do --wait=none , it will only flip to "decommissioned" when the user runs the CLI program again after decommissioning has done all its work. 

This behavior is very problematic because it's not intuitive, easy to overlook, and has occurred in the field. No occurrence frequency statistics is available, yet we were called to help customers who, for example, were unable to upgrade due to "incomplete" decomms.

Note that proactively documenting this behavior in the doc, albeit helpful, is not expected to "solve" the issue as a doc warning is rarely a sure way to avoid a user' stumble. The decomm implementation needs to be more robust and update the state to accurately represent the true state through the decomm execution when the decomm completes, without dependency on the CLI issuer.

Jira issue: CRDB-22889

**Comment by knz** [comment] 2022-12-29 19:23
xref [94430](https://github.com/cockroachdb/cockroach/issues/94430)

**Comment by nvanbenschoten** [comment] 2023-03-06 21:54
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/94430.

**Closed by nvanbenschoten** 2023-03-06 21:54 UTC
Labels: C-bug, T-kv
