### ISSUE TITLE
ui: sort the logs in reverse time order in display

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#18072] opened 2017-08-31 13:17 UTC
Currently in the Admin UI, e.g. at http://localhost:8080/#/cluster/nodes/1/logs

the log entries are displayed in chronological order, with the older entries at the top.

I think it is more common to want to see them in the reverse order.

**Comment by a-robinson** [comment] 2017-08-31 13:54
Dupe of https://github.com/cockroachdb/cockroach/issues/8907

**Closed by a-robinson** 2017-08-31 13:54 UTC
Labels: enhancement
