### ISSUE TITLE
Test failure in CI build 8125

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2712] opened 2015-09-29 16:21 UTC
The following test appears to have failed:

[#8125](https://circleci.com/gh/cockroachdb/cockroach/8125):

```

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-29 16:23
dupe of #2705

**Closed by tamird** 2015-09-29 16:23 UTC
Labels: test-failure
