### ISSUE TITLE
sql/tests: TestRandomSyntaxFunctions failed [array_cat_agg: 9 trailing bytes in encoded value]

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#109629] opened 2023-08-28 20:10 UTC
Found in a random syntax test [here](https://github.com/cockroachdb/cockroach/issues/109560#issuecomment-1695051219):

```sql
SELECT array_cat_agg(
  ARRAY[(416644234484367676:::INT8,),(NULL,),((-0.12116245180368423):::FLOAT8,)]
);
```

Causes the error:

```
ERROR: internal error: 9 trailing bytes in encoded value: [4 191 191 4 128 160 0 0 0]
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:263: EnsureDecoded()
github.com/cockroachdb/cockroach/bazel-out/darwin_arm64-fastbuild/bin/pkg/sql/colexec/rowtovec.eg.go:50: EncDatumRowToColVecs()
github.com/cockroachdb/cockroach/pkg/sql/colexec/values.go:121: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/colexecbase/fn_op.go:32: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/ordered_aggregator.go:207: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:316: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:907: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1960: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1674: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1677: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2291: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1839: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1070: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3232: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:143: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2220: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2225: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2142: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:954: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:247: processCommands()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:999: func3()
```

Jira issue: CRDB-31026

**Comment by mgartner** [comment] 2023-08-28 20:20
Reduced:

```sql
SELECT array_cat_agg(ARRAY[(1::INT,), (1::FLOAT8,)]);
```

I have a hunch that we're not correctly type-checking this expression correctly. It should maybe be a type error.

**Comment by mgartner** [comment] 2023-08-28 21:08
This was introduced in #108387. It allows `ARRAY[(1::INT,), (1::FLOAT)]` to be type checked:

1. `INT` is the first candidate type of the first element of the tuple, so it is the selected first as the "candidate" type.
2. The `INT` "candidate" type can be implicitly cast to `FLOAT8`, so `FLOAT8` becomes the new candidate type.
3. The array is typed as `ARRAY[tuple(FLOAT8)]`.

However, the implicit cast from `1::INT` to `FLOAT8` is never added, so the values during execution don't match expectations, and we get an execution-time error.

**Comment by rafiss** [comment] 2023-08-29 20:51
This was previously reported in https://github.com/cockroachdb/cockroach/issues/109486, but that issue was closed as a dupe of https://github.com/cockroachdb/cockroach/issues/109105. I don't know enough to understand why it's a duplicate.

**Closed** 2023-08-31 17:16 UTC
Labels: C-bug, C-test-failure, O-rsg, T-sql-queries
