### ISSUE TITLE
import: TestCSVImportCanBeResumed flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#92665] opened 2022-11-29 13:47 UTC
https://teamcity.cockroachdb.com/viewLog.html?buildId=7741444&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-21912

**Comment by rafiss** [comment] 2022-11-29 15:49
Duplicate of https://github.com/cockroachdb/cockroach/issues/91828

**Closed by rafiss** 2022-11-29 15:49 UTC
Labels: C-bug, C-test-failure, T-sql-experience
