### ISSUE TITLE
sentry: conn_executor.go:643: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON ((_._ = _._) AND (_._ = _._)) AND (_._ = _._) WHERE (((_._ = $1) AND (_._ = $2)) AND ((_._ < $3) OR (_._ = $4))) AND (_._ > $5) ORDER BY _._ ASC LIMIT $6: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33184] opened 2018-12-17 00:01 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/811019941/?referrer=webhooks_plugin

conn_executor.go:643: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON ((_._ = _._) AND (_._ = _._)) AND (_._ = _._) WHERE (((_._ = $1) AND (_._ = $2)) AND ((_._ < $3) OR (_._ = $4))) AND (_._ > $5) ORDER BY _._ ASC LIMIT $6: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

> stacktrace: {u'frames': [{u'function': u'func4', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl', u'in_app': True, u'lineno': 313, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go'}, {u'function': u'ServeConn', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server)', u'in_app': True, u'lineno': 389, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'run', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 1173, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}, {u'function': u'execStmt', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 96, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execStmtInOpenState', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 402, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'dispatchToExecutionEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 824, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'execWithDistSQLEngine', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor)', u'in_app': True, u'lineno': 982, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go'}, {u'function': u'PlanAndRun', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 752, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2279, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2317, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForNode', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 2273, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'createPlanForLookupJoin', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 1918, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'convertOrdering', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner)', u'in_app': True, u'lineno': 935, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go'}, {u'function': u'panicindex', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 28, u'filename': u'runtime/panic.go'}, {u'function': u'gopanic', u'abs_path': u'/usr/local/go/src/runtime/panic.go', u'module': u'runtime', u'in_app': False, u'lineno': 502, u'filename': u'runtime/panic.go'}, {u'function': u'call32', u'abs_path': u'/usr/local/go/src/runtime/asm_amd64.s', u'module': u'runtime', u'in_app': False, u'lineno': 573, u'filename': u'runtime/asm_amd64.s'}, {u'function': u'func1', u'abs_path': u'/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go', u'module': u'github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn', u'in_app': True, u'lineno': 387, u'filename': u'github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go'}]}
type: *log.safeError
value: conn_executor.go:643: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON ((_._ = _._) AND (_._ = _._)) AND (_._ = _._) WHERE (((_._ = $1) AND (_._ = $2)) AND ((_._ < $3) OR (_._ = $4))) AND (_._ > $5) ORDER BY _._ ASC LIMIT $6: caused by <redacted>

**Comment by jordanlewis** [comment] 2018-12-18 14:49
Dupe of #33179.

**Closed by jordanlewis** 2018-12-18 14:49 UTC
Labels: C-bug, O-sentry
