### ISSUE TITLE
perf: tracking issue for environment knobs that have perf impact

### ISSUE THREAD

**Issue by rjnn** [cockroachdb/cockroach#17165] opened 2017-07-21 17:32 UTC
This is a tracking issue for best practices when really pushing CockroachDB to its performance limit. It is a useful source when trying to benchmark CockroachDB, or when changing defaults.

- Disable snappy RPC compression: `COCKROACH_ENABLE_RPC_COMPRESSION=false`. This gives a 5% throughput boost.
- Disable security (`--insecure`): not recommended, but gives a 5% throughput boost. Make sure comparisons are done on an apples-to-apples basis w.r.t security though.
- `rocksdb.min_wal_sync_interval` (default 1ms) controls the minimal interval between syncs of the RocksDB WAL and thus implies a lower bound on the latency of write operations.
- `kv.raft_log.synchronize` (default true) controls whether the RocksDB WAL is synced after writing to the Raft log. Syncing slows down write operations (and see the `rocksdb.min_wal_sync_interval` setting), but not syncing provides a window for possible data corruption.
- `sql.metrics.statement_details.enabled` (default true) controls whether we collect per-statement query statistics. There is a small 1-2% impact on throughput for this collection, though it is possible this is in the noise.
- Turn off GC Assist (requires manual intervention in the Go compiler) - dramatically reduces tail latencies. 
- Increase the initial stack size of goroutines from 2KB to 32KB - gives a 5% boost to throughput and a modest reduction in latency. See https://github.com/cockroachdb/cockroach/issues/17242.

Here's also an incomplete list of past knobs we've used. This is not something we do, but its tracked so that we have a historical list so we don't forget past experiments/don't repeat past experiments that proved unfruitful.

- `COCKROACH_SCHEDULER_CONCURRENCY=128` used to improve things. Now we set the default to 64 which should be good enough. This knob affects Raft operations (i.e. writes). Nobody has precisely tuned this.
- `COCKROACH_ENABLE_TRACING=false`. Replaced by the `trace.debug.enable` cluster setting which defaults to false.
- `COCKROACH_ENABLE_SQL_EVENT_LOG="false"`. Replaced by the `sql.trace.session_eventlog.enabled` cluster setting which defaults to false.
- Turn off Go GC Idle Workers - doesn't have an impact.
- `GOGC=200` - no significant impact.
- `GODEBUG="memprofilerate=0"` - no significant impact.

Additional suggestions welcome!

cc @petermattis

**Comment by petermattis** [comment] 2017-08-05 12:53
`kv --read-percent=95` workload for `GOGC=100` vs `GOGC=200`:

<img width="726" alt="screen shot 2017-08-05 at 8 52 21 am" src="https://user-images.githubusercontent.com/6201335/28995620-820587e6-79bb-11e7-833c-aad22deed04e.png">

**Comment by petermattis** [comment] 2017-08-05 19:13
`kv --read-percent=95` workload for normal vs `GODEBUG=memprofilerate=0` (using `cockroach-824b975`):

<img width="716" alt="screen shot 2017-08-05 at 3 10 35 pm" src="https://user-images.githubusercontent.com/6201335/28998069-763317dc-79f0-11e7-8548-0c3afce827bd.png">

**Comment by petermattis** [comment] 2017-08-06 20:52
`kv --read-percent=95` workload for normal vs `sql.metrics.statement_details.enabled=false` (using `cockroach-824b975`):

<img width="723" alt="screen shot 2017-08-06 at 4 50 13 pm" src="https://user-images.githubusercontent.com/6201335/29006935-723ab914-7ac7-11e7-8836-67a06e183b3b.png">

There appears to be a very small 1-2% boost to disabling statement stats. It is also possible this is in the noise.

**Comment by jordanlewis** [comment] 2017-08-06 21:27
I think statement stats have a definite performance impact. I've seen them show up in profiling - significantly caused by the re-serialization of the AST using the constant hiding formatter.

**Comment by petermattis** [comment] 2017-08-07 00:30
> I think statement stats have a definite performance impact. I've seen them show up in profiling - significantly caused by the re-serialization of the AST using the constant hiding formatter.

Yeah, I've seen the statement stats show up on profiles too. I would have guessed the impact larger than what is shown in the above graph.

**Comment by jordanlewis** [comment] 2020-10-06 02:08
Closing due to age.

**Closed by jordanlewis** 2020-10-06 02:08 UTC
Labels: A-sql-execution, C-performance
