### ISSUE TITLE
sql: support money type

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#108505] opened 2023-08-10 12:30 UTC
**Is your feature request related to a problem? Please describe.**
PostgreSQL support `money` type

https://www.postgresql.org/docs/current/datatype-money.html

This is not supported by CockroachDB currently

**Additional context**
This affects some tests in efcore.pg library

@fqazi 

Jira issue: CRDB-30498

**Comment by fqazi** [comment] 2023-08-10 14:04
This looks like a duplicate of: https://github.com/cockroachdb/cockroach/issues/41578. At the present time, we should skip these tests. I don't think there are any immediate plans for this one, and there is contention on whether we should even add this.

**Closed by fqazi** 2023-08-10 14:04 UTC
Labels: C-enhancement, O-community, X-blathers-untriaged, A-tools-efcore
