### ISSUE TITLE
roachprod: restarted node stuck in `waiting for init`

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#23990] opened 2018-03-17 16:57 UTC
I have a 24 node `roachprod` cluster that's trying to run several large (tpcc 10k) restores with slightly increased concurrency. A few (the same few fwiw) of my nodes keep crashing due to out-of-memory. 

On restarting them (`roachprod start <cluster>:<node>`), they appear to be stuck in `waiting for init`.

```
$ roachprod ssh david-restore:23 "./cockroach node ls --insecure"
Error: unable to connect or connection lost.

Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).

rpc error: code = Unavailable desc = node waiting for init; /cockroach.server.serverpb.Status/Nodes not available
Failed running "node"
```

Looking at the process in `ps aux`, I see that it _does_ have the expected `join` flag:
```
./cockroach start --insecure [...] --join=<ip of node 1>:26257
```
I can access the cluster's admin UI and SQL prompt on `<ip of node 1>` above.

Restarting again (`roachprod stop` ... `start`) sometimes seems to fix it, but not always.

**Comment by a-robinson** [comment] 2018-03-17 17:16
1. Were all 24 nodes properly initialized before running the restore?
1. Did you wipe it before restarting it?
1. Is there anything in its logs (both before and after the restart)?

**Comment by dt** [comment] 2018-03-18 14:33
Unfortunately I had to step away yesterday and my cluster expired, but i'll try again and see if i can reproduce it.

All 24 nodes were up before I started I believe.

I ran `./bin/workload fixtures load tpcc --warehouses=10000` to load tpcc10k.

I was running with `kv.bulk_io_write.concurrent_import_requests` bumped up to 3, 5, 10 and 20 at various times to see how it worked.

Most of the small tables finished. The big ones slowed down near the end. three nodes repeatedly died OOMing in sst sideload.

I believe i just restarted them -- looking at the logs I have left in my scroll back, they still appeared to know their node ID and seemed to be trying to contact a couple other nodes:

```
I180317 17:04:02.804883 2409 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:03.399574 2413 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
W180317 17:04:03.550838 2450 server/server.go:1069  The server appears to be unable to contact the other nodes in the cluster. Please try

- starting the other nodes, if you haven't already
- double-checking that the '--join' and '--host' flags are set up correctly
- running the 'cockroach init' command if you are trying to initialize a new cluster

If problems persist, please see https://www.cockroachlabs.com/docs/v2.0/cluster-setup-troubleshooting.html.
I180317 17:04:03.962398 2468 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:04.368244 1738 storage/store.go:3485  [n20,s19,r32254/4:/Table/59/1/5052/73057{-/0}] added to replica GC queue (peer suggestion)
I180317 17:04:04.368267 1885 storage/store.go:3485  [n20,s19,r32254/4:/Table/59/1/5052/73057{-/0}] added to replica GC queue (peer suggestion)
I180317 17:04:04.474973 1899 storage/replica_raftstorage.go:726  [n20,s19,r5805/4:/Table/57/1/49{5/2/-…-7/1/-…}] applying Raft snapshot at index 33 (id=f5ebb4d9, encoded size=40840133, 156 rocksdb batches, 2 log entries)
I180317 17:04:04.559637 2456 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:04.601513 2473 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:04.994824 1899 storage/replica_raftstorage.go:732  [n20,s19,r5805/4:/Table/57/1/49{5/2/-…-7/1/-…}] applied Raft snapshot in 520ms [clear=1ms batch=301ms entries=0ms commit=218ms]
I180317 17:04:05.402181 2459 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:05.999839 2480 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:06.163818 2500 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:06.801653 2518 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:07.362244 2527 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:07.514886 2493 storage/replica_raftstorage.go:726  [n20,s19,r7181/?:{-}] applying preemptive snapshot at index 43 (id=fa2e262a, encoded size=11659, 1 rocksdb batches, 33 log entries)
I180317 17:04:07.534840 2493 storage/replica_raftstorage.go:732  [n20,s19,r7181/?:/Table/51/1/1043/10/2734…] applied preemptive snapshot in 20ms [clear=1ms batch=0ms entries=0ms commit=18ms]
I180317 17:04:07.802879 88 storage/stores.go:350  [n20] wrote 20 node addresses to persistent storage
I180317 17:04:08.014743 2538 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:08.361317 1831 storage/store.go:3485  [n20,s19,r44145/4:/Table/59/1/575{5/585…-6/626…}] added to replica GC queue (peer suggestion)
I180317 17:04:08.361706 1738 storage/store.go:3485  [n20,s19,r44145/4:/Table/59/1/575{5/585…-6/626…}] added to replica GC queue (peer suggestion)
I180317 17:04:08.379154 2511 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:08.638126 1513 server/status/runtime.go:219  [n20] runtime stats: 7.5 GiB RSS, 472 goroutines, 6.8 GiB/89 MiB/7.1 GiB GO alloc/idle/total, 378 MiB/402 MiB CGO alloc/total, 209.67cgo/sec, 1.06/0.28 %(u/s)time, 0.00 %gc (2x)
I180317 17:04:08.968708 2569 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:09.199601 2542 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:09.850367 1947 storage/replica_raftstorage.go:726  [n20,s19,r1759/4:/Table/57/1/170{3/4/-…-5/3/-…}] applying Raft snapshot at index 173 (id=bd03ac50, encoded size=40839829, 156 rocksdb batches, 58 log entries)
I180317 17:04:10.406122 1947 storage/replica_raftstorage.go:732  [n20,s19,r1759/4:/Table/57/1/170{3/4/-…-5/3/-…}] applied Raft snapshot in 556ms [clear=0ms batch=313ms entries=0ms commit=242ms]
I180317 17:04:10.430273 2614 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:10.432521 2552 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:11.200088 2557 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:11.561705 2587 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:12.399395 2561 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:12.563525 2607 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:13.205017 2674 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:13.759999 2678 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:14.251082 2631 storage/replica_raftstorage.go:726  [n20,s19,r27922/?:{-}] applying preemptive snapshot at index 17 (id=2be25f19, encoded size=5117, 1 rocksdb batches, 7 log entries)
I180317 17:04:14.265488 2631 storage/replica_raftstorage.go:732  [n20,s19,r27922/?:/Table/51/1/9895/2/331{-/0}] applied preemptive snapshot in 14ms [clear=4ms batch=0ms entries=0ms commit=10ms]
I180317 17:04:14.406997 2649 storage/raft_transport.go:459  [n20] raft transport stream to node 24 established
I180317 17:04:14.566984 2652 storage/raft_transport.go:459  [n20] raft transport stream to node 16 established
I180317 17:04:14.832717 1949 storage/replica_raftstorage.go:726  [n20,s19,r30045/1:/Table/59/1/335{2/402…-3/8155}] applying Raft snapshot at index 26 (id=79bd22ed, encoded size=35015389, 134 rocksdb batches, 2 log entries)
I180317 17:04:15.165709 1949 storage/replica_raftstorage.go:732  [n20,s19,r30045/1:/Table/59/1/335{2/402…-3/8155}] applied Raft snapshot in 333ms [clear=0ms batch=201ms entries=0ms commit=131ms]
I180317 17:04:15.165935 1904 storage/store.go:2356  [replicaGC,n20,s19,r29650/1:/Table/57/1/6931/4/-2092/6…] removing replica
I180317 17:04:15.206190 1904 storage/replica.go:836  [replicaGC,n20,s19,r29650/1:/Table/57/1/6931/4/-2092/6…] removed 13 (0+13) keys in 40ms [clear=10ms commit=30ms]
```

**Comment by petermattis** [comment] 2018-10-05 14:07
This was seen a long time ago and there have been various fixes made to `roachprod` since then. Closing until this reproduces.

**Closed by petermattis** 2018-10-05 14:07 UTC
Labels: A-testing, C-investigation
