### ISSUE TITLE
Sentry: histogram.go:244: the first bucket should have NumRange=0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histo...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#105691] opened 2023-06-28 07:19 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4279891930/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4279891930/?referrer=webhooks_plugin)

Panic Message:

```
histogram.go:244: the first bucket should have NumRange=0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:244
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).Filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:387
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3624
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3441
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3179
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFilters
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3095
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).filterRelExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3049
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1013
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*logicalPropsBuilder).buildSelectProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:288
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).MemoizeSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go:19881
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:1451
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructInnerJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:3021
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).DynamicConstruct
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25181
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:950
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructInnerJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:3021
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).DynamicConstruct
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25181
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:950
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructInnerJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:3021
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).DynamicConstruct
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:25181
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:950
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructSelect
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:673
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildWhere
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1168
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1041
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:986
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:955
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:954
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:305
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:252
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:226
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:561
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:232
Wraps: (3) the first bucket should have NumRange=0
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: the first bucket should have NumRange=0
histogram.go:244: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_opt.go#L231-L233](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_opt.go#L231-L233)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_opt.go#L560-L562](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/plan_opt.go#L560-L562)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L225-L227](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L225-L227)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L251-L253](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L251-L253)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L304-L306](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/builder.go#L304-L306)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L953-L955](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L953-L955)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/with.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/with.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L954-L956](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L954-L956)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L985-L987](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L985-L987)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L1040-L1042](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L1040-L1042)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L1167-L1169](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/optbuilder/select.go#L1167-L1169)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L672-L674](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L672-L674)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L949-L951)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L25180-L25182)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L3020-L3022)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L1450-L1452](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L1450-L1452)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L19880-L19882](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L19880-L19882)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/logical_props_builder.go#L287-L289](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/logical_props_builder.go#L287-L289)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L1012-L1014](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L1012-L1014)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3048-L3050](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3048-L3050)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3094-L3096](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3094-L3096)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3178-L3180](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3178-L3180)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3440-L3442](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3440-L3442)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3623-L3625](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/memo/statistics_builder.go#L3623-L3625)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/props/histogram.go#L386-L388](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/props/histogram.go#L386-L388)
[https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/props/histogram.go#L243-L245](https://github.com/cockroachdb/cockroach/blob/cbe33971930ee972e639203a73f14240b92aeff4/pkg/sql/opt/props/histogram.go#L243-L245)
</details>

```
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 232
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 561
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 226
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 252
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 305
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 954
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 116
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 955
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 986
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1041
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildWhere at line 1168
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 673
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 950
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).DynamicConstruct at line 25181
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructInnerJoin at line 3021
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 950
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).DynamicConstruct at line 25181
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructInnerJoin at line 3021
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 950
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).DynamicConstruct at line 25181
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructInnerJoin at line 3021
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructSelect at line 1451
bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go in pkg/sql/opt/memo.(*Memo).MemoizeSelect at line 19881
pkg/sql/opt/memo/logical_props_builder.go in pkg/sql/opt/memo.(*logicalPropsBuilder).buildSelectProps at line 288
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).buildSelect at line 1013
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).filterRelExpr at line 3049
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFilters at line 3095
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem at line 3179
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet at line 3441
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram at line 3624
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).Filter at line 387
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).filter at line 244
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v22.2.7 |
| Go Version | go1.19.6 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v22.2.7 |
| Cockroach SHA | cbe33971930ee972e639203a73f14240b92aeff4 |
| # of CPUs | 16 |
| # of Goroutines | 855 |

Jira issue: CRDB-29451

**Comment by msirek** [comment] 2023-07-06 01:24
dupe of #106132

**Closed by msirek** 2023-07-06 01:24 UTC
Labels: T-sql-queries
