### ISSUE TITLE
sql: index scan from `-infinity` for `DATE` seems wrong

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#76419] opened 2022-02-11 03:29 UTC
I can only reproduce this in a test, so I'm attaching the repro here. When running these steps on `./cockroach demo` everything seems completely sane. But I'm 99.99% sure it's not my test that's wrong.

Basically, assume a table with the following schema:
```
CREATE TABLE tbl (
id UUID DEFAULT gen_random_uuid(),
crdb_internal_expiration TIMESTAMPTZ,
rand_col_1 INET,
rand_col_2 DATE,
text TEXT,
PRIMARY KEY (id, rand_col_1, rand_col_2),
);
```

And insert some rows with a `-infinity` `DATE` type.

When executing 
```
SELECT id, rand_col_1, rand_col_2 FROM tbl
AS OF SYSTEM TIME '2022-02-11 03:16:59.919707+00:00'
WHERE crdb_internal_expiration <= $1::timestamptz AND (id, rand_col_1, rand_col_2) > ($2::UUID, $3::INET, $4::DATE)
ORDER BY id, rand_col_1, rand_col_2
LIMIT 1
```

with $2, $3, $4 being`('07801f63-ab99-4fcf-9b11-2a0d9aec0570',  'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38', '-infinity')`

the scan returns:
```
  distribution: local
  vectorized: true

  • limit
  │ count: 1
  │
  └── • filter
      │ filter: crdb_internal_expiration <= '2022-02-11 03:23:21.527184+00:00'
      │
      └── • scan
            missing stats
            table: tbl@tbl_pkey
            spans: [/'07801f63-ab99-4fcf-9b11-2a0d9aec0570'/'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38'/'-infinity' - ]
```

which seems wrong: the `-infinity` should be `'4714-11-24 BC'`. However, I could only reproduce this in my test, but trying to produce it manually doesn't seem to work.

The code here is suspicious; `IsMin` and `IsMax` for DDate seems wrong: https://github.com/cockroachdb/cockroach/blob/81e83ae906864020809858f0f4cd2a510f7bc51e/pkg/sql/sem/tree/datum.go#L2030-L2071

----

Repro steps:
* Clone https://github.com/cockroachdb/cockroach/compare/master...otan-cockroach:debug_output?expand=1
* Run `go test ./pkg/sql/ttl/ttljob  -test.v -count 1`. You can see in the EXPLAIN output that we are searching from `-infinity` instead of `'4714-11-24 BC'` and we forever get stuck on a loop of `-infinity` (see last commit which only has output details).
* Here's the [dump](https://gist.github.com/otan/b2e08b63ad2cd71ffb9f897609a8a221) which you can run on `./cockroach demo`. The `EXPLAIN` output seems fine here:
```
root@127.0.0.1:26257/defaultdb> prepare e as SELECT id, rand_col_1, rand_col_2 FROM tbl
AS OF SYSTEM TIME '2022-02-11 03:35:08.281724+00'
WHERE crdb_internal_expiration <= $1::timestamptz AND (id, rand_col_1, rand_col_2) > ($2::UUID, $3::INET, $4::DATE)
ORDER BY id, rand_col_1, rand_col_2
LIMIT 1;
PREPARE


Time: 1ms total (execution 0ms / network 0ms)

root@127.0.0.1:26257/defaultdb> execute e(now(), '07801f63-ab99-4fcf-9b11-2a0d9aec0570',  'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38', '-infinity');
                   id                  |                 rand_col_1                  | rand_col_2
---------------------------------------+---------------------------------------------+-------------
  07b7151e-c318-41d2-af04-a6eb28a17ee6 | 1138:fceb:d647:c7a8:2ec1:8513:5c8c:3e62/116 | 1978-12-28
(1 row)

root@127.0.0.1:26257/defaultdb> explain execute e(now(), '07801f63-ab99-4fcf-9b11-2a0d9aec0570',  'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38', '-infinity');
ERROR: EXPLAIN EXECUTE is not supported; use EXPLAIN ANALYZE
SQLSTATE: 0A000
root@127.0.0.1:26257/defaultdb> explain analyze execute e(now(), '07801f63-ab99-4fcf-9b11-2a0d9aec0570',  'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38', '-infinity');
                                                            info
-----------------------------------------------------------------------------------------------------------------------------
  planning time: 5ms
  execution time: 14ms
  distribution: local
  vectorized: true
  rows read from KV: 371 (30 KiB)
  cumulative time spent in KV: 9ms
  maximum memory usage: 80 KiB
  network usage: 0 B (0 messages)
  regions: us-east1

  • limit
  │ nodes: n1
  │ regions: us-east1
  │ actual row count: 1
  │ estimated row count: 1
  │ count: 1
  │
  └── • filter
      │ nodes: n1
      │ regions: us-east1
      │ actual row count: 1
      │ estimated row count: 4
      │ filter: crdb_internal_expiration <= '2022-02-11 03:35:08.281724+00:00'
      │
      └── • scan
            nodes: n1
            regions: us-east1
            actual row count: 371
            KV time: 9ms
            KV contention time: 0µs
            KV rows read: 371
            KV bytes read: 30 KiB
            estimated max memory allocated: 80 KiB
            estimated row count: 371 - 1,538 (97% of the table; stats collected 55 seconds ago)
            table: tbl@tbl_pkey
            spans: [/'07801f63-ab99-4fcf-9b11-2a0d9aec0570'/'c8c2:891d:c367:e3e:9960:52dc:6daf:23cb/38'/'4714-11-24 BC' - ]
(36 rows)
```

Jira issue: CRDB-13109

**Comment by mgartner** [comment] 2022-05-31 14:10
@otan what are the implications of this? Could we return incorrect results?

**Comment by otan** [comment] 2022-05-31 14:13
yeah, we'd be emitting an extra row

**Comment by mgartner** [comment] 2023-06-08 16:16
Next step: let's try to reproduce a incorrect result due to this.

**Comment by mgartner** [comment] 2023-07-27 22:53
I've been unable to reproduce manually or with @otan's branch (there is an import cycle on the branch that I didn't attempt to untangle). I'm going to close this for now.

**Closed by mgartner** 2023-07-27 22:53 UTC
Labels: C-bug, S-3, branch-master, release-blocker, T-sql-queries
