### ISSUE TITLE
sql: invalid panic or GoExit in logic test

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#82110] opened 2022-05-31 08:36 UTC
Found here:
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/5320671?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
    testing.go:1169: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

Jira issue: CRDB-16214

**Comment by yuzefovich** [comment] 2022-06-01 01:36
I'm not sure whether we can rely on the output of the logic tests to assume that `crdb_internal` was the file that triggered the panic. In the meantime, I kicked off a test run with `--show-sql` on the gceworker on 60a88af659, and it finished successfully.

**Comment by andreimatei** [comment] 2022-06-07 19:11
Happened to me on the same `TestLogic/fakedist/crdb_internal/max_retry_counter`

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/5401547?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by stevendanna** [comment] 2022-07-14 09:51
I may have fixed the most proximate cause of why this test was failing here https://github.com/cockroachdb/cockroach/pull/84419 but it is hard to say as the logs from the builds posted here are all gone.

I fixed the cause of `subtest may have called FailNow on a parent test` here https://github.com/cockroachdb/cockroach/pull/84420

The part I haven't actually dug into here is why we don't get the actual assertion output more visibly in the job.  That is to find the actual failure that led to the above fix I had to go from [main page for the build](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_GitHubCiOptional/5741129?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) to the [Unit test job](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/5741112?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true) and from there to the artifacts, where we can find [log which contains the real assertion failure](https://teamcityartifacts.crdb.io/presignedTokenAuth/bd567ce8-608a-428a-bceb-3412160455ef/repository/download/Cockroach_UnitTests_BazelUnitTests/5741112:id/bazel-testlogs/pkg/sql/logictest/logictest_test/test.log):

```
=== CONT  TestLogic/fakedist/crdb_internal
    logic.go:3251: condition failed to evaluate within 45s: 
        /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/7022/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/logictest_test_/logictest_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/crdb_internal:795: SELECT start_pretty, end_pretty FROM crdb_internal.ranges WHERE split_enforced_until IS NOT NULL
        expected:
            start_pretty    end_pretty
            /Table/112/1/1  /Table/112/1/2
            /Table/112/1/2  /Table/112/1/3
            /Table/112/1/3  /Table/112/2/1
            /Table/112/2/1  /Table/112/2/2
            /Table/112/2/2  /Table/112/2/3
            /Table/112/2/3  /Table/112/3/1
            /Table/112/3/1  /Table/112/3/2
            /Table/112/3/2  /Table/112/3/3
            /Table/112/3/3  /Table/112/4/1
            /Table/112/4/1  /Table/112/4/2
            /Table/112/4/2  /Table/112/4/3
            /Table/112/4/3  /Max
            
        but found (query options: "colnames,retry") :
            start_pretty    end_pretty
            /Table/112/3/1  /Table/112/3/2
            /Table/112/3/2  /Table/112/3/3
            /Table/112/3/3  /Table/112/4/1
            /Table/112/4/1  /Table/112/4/2
            /Table/112/4/2  /Table/112/4/3
            /Table/112/4/3  /Max
=== CONT  TestLogic/fakedist/crdb_internal/max_retry_counter
    testing.go:1169: test executed panic(nil) or runtime.Goexit: subtest may have called FailNow on a parent test
```

Perhaps the fact that we weren't using `t.Error` was breaking some part of the output parsing, so maybe my changes fixes that as well, but I haven't dug into it.

**Comment by yuzefovich** [comment] 2022-08-10 00:44
Looks like Steven fixed this flake, and Ricky's refactor should make failures easier to find in the future, so I'm closing this issue.

**Closed by yuzefovich** 2022-08-10 00:44 UTC
Labels: C-bug, A-testing, T-sql-queries
