### ISSUE TITLE
roachtest: add -count flag to run tests multiple times

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#25303] opened 2018-05-03 22:59 UTC
We should introduce a new `-count` flag to roachtest. Similar to the `-count` flag supported by `go test`, this flag will run each matching test `n` times. This is a small change, but it will make it easier to stress a new test to gain confidence.

**Comment by tschottdorf** [comment] 2018-05-04 04:26
Duplicate of https://github.com/cockroachdb/cockroach/issues/25284. (Sorry, I told you to file this and then did it anyway).

**Closed by tschottdorf** 2018-05-04 04:26 UTC
Labels: A-testing
