### ISSUE TITLE
sql,ui: support, test and optimize loads using thousands of databases

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#28376] opened 2018-08-08 13:01 UTC
**FEATURE REQUEST**

### Motivation

A modern multi-tenant and micro services could have thousands of databases.  Each database could represent a distinct customer and/or micro-services application.  Within each database, a number of tables can be created.

Below is an extremely simple example of creating 10,000 databases with 1 table each and 3 rows per table for initial deployment.  

### Example

```
for i in `seq 10000`; do cockroach sql --insecure --database test -e "create database if not exists db${i}; use db${i}; create table if not exists test${i} (id int primary key); insert into test${i} values (1),(2),(3);"; done
```

### Current limitations

Currently CockroachDB has many problems with a large number of databases:

- the namespace tables and descriptors are propagated via gossip. with 10k databases and ten times that number of tables, this gossip traffic becomes huge

- the lease management becomes inefficient at that scale

- the `databases` section of the UI resource consumption is heavy

- CPU consumption goes up on the server

<img width="617" alt="screen shot 2018-08-08 at 8 58 17 am" src="https://user-images.githubusercontent.com/6315124/43838411-48bc47b8-9ae9-11e8-937f-6de3cbaf9daf.png">

**Comment by knz** [comment] 2018-09-17 16:56
The UI problem here is just the tip of the iceberg. Currently if you create 10k databases even the core product would have a large problem and not work properly.

I will requalify your issue to reveal its full scope.

**Comment by knz** [comment] 2018-09-17 17:02
@vivekmenezes @awoods187 I think addressing this issue of scale will need intervention from multiple teams. It's hard for me to comprehend the scale upfront because there are so many moving pieces.

My advice would be to start with an investigation where we run a test cluster with that many databases (and corresponding table workload) and profile / inventory where resource consumption goes throughout the stack.

**Comment by piyush-singh** [comment] 2018-09-17 18:01
Agreed! There are some tactical things that are specific to the UI that we can accomplish in 2.2 (and beyond) that will further this goal. Examples include tangentially related issues like better handling of large clusters' time series data (#30286) to more fundamental issues like the one Robert mentioned above around resource consumption and load times for large databases on the databases tab. This is a nice issue to be able to refer to when filing other issues that deal with scaling Cockroach

**Comment by couchand** [comment] 2018-09-17 18:13
I suspect the UI part of this issue is a dupe of #22941 and will be covered by cleaning that up.  But it's definitely useful putting that technical view of the issue in the context of real world usage.

**Comment by dt** [comment] 2019-08-21 20:49
I chatted a bit with @knz about this a while back but forgot to write down some notes from that.

We might get a long way by adding a `version` column to the `namespace` table, and then disabling gossiping of the `descriptor` table. Then when a descriptor is changed, we'd put both the new desc but more importantly bump the version in the namespace table. Since the `namespace` table is still gossiped, every node would hear about this and could then check if they currently have a lease on that table and if so, fetch the updated version / release the old one / etc just as they do now, but without gossiping the whole descriptor table. 

We _could_ go even further with this approach and make a new `descriptors` table the has as a PK (ID, version) so that revisions are not done in-place and allow splits in it to remove limitations around numbers of descriptor revisions, but just moving the gossip dependency from being that all the actual descs get gossiped to just the versions would be a big initial win without _that_ much restructuring (or at least it seemed that way to the two of us, neither of whom are actually on the SQL team though so obviously some grains of salt there.)

**Comment by ajwerner** [comment] 2021-06-08 14:14
My sense is that either we treat this as just the UI bug or we close it altogether. The other inefficiencies are known and tracked elsewhere in later but more detailed issues like #63206.

**Closed by ajwerner** 2021-06-08 14:14 UTC
Labels: A-schema-descriptors, A-webui-general, C-enhancement, C-performance, no-issue-activity
