### ISSUE TITLE
sql: binary protocol bug with decimal

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#25460] opened 2018-05-14 09:56 UTC
I am trying to store some decimal values using Elixir / Ecto and it seems CRDB is not decoding the passed value properly:

The `discount` field is defined as DECIMAL(13,4) in the table.

On Elixir/Ecto side
```
INSERT INTO "passes" ("discount", ...) VALUES ($1, ...) [#Decimal<15>, ...]
```

On CRDB side:
```
"INSERT INTO passes(discount, ...) VALUES ($1, ...)" {$1:"1500000.0000", ...} 1.047 1 ""
```

CRDB info:
```
❯ cockroach version
Build Tag:    v2.0.1
Build Time:   2018/04/23 19:18:28
Distribution: CCL
Platform:     darwin amd64 (x86_64-apple-darwin17.5.0)
Go Version:   go1.10.1
C Compiler:   4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
Build SHA-1:  c92bc6e912880c28c0784d3208583fb27f482f76
Build Type:   development
```

**Comment by knz** [comment] 2018-05-14 10:43
@justinj could you have a look, apparently we don't decode received decimals properly. The issue says that if a client sends the value "15" with some precision the server will see 15*10^x with some non-zero x instead.

**Comment by knz** [comment] 2018-05-23 13:27
@tlvenn I have tried arduously to reproduce the error you have described, but have not yet succeeded. Is there any chance you could capture a packet trace of the traffic between your client and CockroachDB? I'd need to see the raw data to understand what's going wrong.

**Comment by tlvenn** [comment] 2018-05-23 13:37
Sure thing, I have since then moved to integer to deal with money in our app but I can definitely look into it again and capture the traffic. I will look into this next week.

@fishcakez might have a clue at what is going on.

**Comment by knz** [comment] 2018-12-13 20:56
@mjibson I think your recent change fixed this right?

**Comment by tlvenn** [comment] 2018-12-14 15:07
Sorry guys, forgot to report back, let me know if you still need me to capture the traffic.

**Comment by mjibson** [comment] 2018-12-14 18:48
My change only affected encoding, not decoding, so this may still be present.

**Comment by RoachietheSupportRoach** [comment] 2020-03-02 16:36
Zendesk ticket #[4818](https://cockroachdb.zendesk.com/agent/tickets/4818) has been linked to this issue.

**Comment by otan** [comment] 2020-03-02 19:38
The issue is this padding here:

https://github.com/cockroachdb/cockroach/blob/a75396ac9efe7292242adb01ab204c345c04a639/pkg/sql/pgwire/pgwirebase/encoding.go#L463

anyone know why we do this?

**Comment by jordanlewis** [comment] 2020-03-02 19:45
I believe https://github.com/cockroachdb/cockroach/commit/82cadcb290f87a1d0e2bcdf78666f45245a6cf58 is where it was introduced, maybe spelunk from there?

**Comment by jordanlewis** [comment] 2020-03-02 19:46
n.b. also, the issue that it marked as closed was filed by another Elixir/Erlang user.

**Comment by otan** [comment] 2020-03-02 20:04
In particular, elixir for values such as "2.0" emits "2" and "0".
I'd believe it to be splunk from there; I'm trying to find how postgres parses this and imitate that instead.

**Comment by otan** [comment] 2020-03-02 20:05
Actually, the comment `// The last digit may contain padding, which we need to deal with.` was there *before*, so the padding comment seems to have been there for longer.

**Comment by otan** [comment] 2020-03-02 20:08
I have not discounted that this may be also elixir not following standard, but I haven't got an idea on how to reproduce the BindStatement from a SQL shell involving a decimal.

**Comment by knz** [comment] 2020-03-02 20:28
> how to reproduce the BindStatement from a SQL shel

I'd recommend a java program or some other custom code using a driver that uses BindStatement. SQL shells typically don't use bind.

**Comment by jordanlewis** [comment] 2020-03-02 20:29
I like to futz with `pkg/acceptance/testdata/java/src/main/java/MainTest.java` when testing stuff that needs Bind - it's a pretty easy edit-compile-test cycle against a running crdb server.

**Closed** 2020-03-03 21:30 UTC
Labels: A-sql-pgwire, C-investigation, O-community, S-3-erroneous-edge-case
