### ISSUE TITLE
Allow setting txn retry options in client

### ISSUE THREAD

**Issue by ajayaa** [cockroachdb/cockroach#3526] opened 2015-12-26 11:52 UTC
Please see [this](https://github.com/cockroachdb/cockroach/blob/master/client/db.go#L196)

Should it be a part of the url itself? Otherwise the function signature will need a change. This function is used in several other places. A simple grep with wc gives 14 as output.

**Comment by tschottdorf** [comment] 2015-12-26 14:08
Hey @ajayaa, thanks for opening this. I think it's a duplicate of #2642. Wanna take the discussion there?

**Closed** 2015-12-26 14:33 UTC
