### ISSUE TITLE
circleci: failed tests (13495): TestMultiRangeScanReverseScanDeleteResolve 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4707] opened 2016-02-28 19:45 UTC
The following test appears to have failed:

[#13495](https://circleci.com/gh/cockroachdb/cockroach/13495):

```
I160228 19:43:20.301603 raft/raft.go:472  [group 4] 1 became candidate at term 6
I160228 19:43:20.301626 raft/raft.go:521  [group 4] 1 received vote from 1 at term 6
I160228 19:43:20.301659 raft/raft.go:500  [group 4] 1 became leader at term 6
I160228 19:43:20.348223 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160228 19:43:20.348496 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestMultiRangeScanReverseScanDeleteResolve (0.13s)
	dist_sender_server_test.go:88: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
=== RUN   TestMultiRangeScanReverseScanInconsistent
I160228 19:43:20.350332 server/context.go:165  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
	setting default rocksdb cache size to 120 GiB (half of system memory)
I160228 19:43:20.354293 rpc/clock_offset.go:154  monitoring cluster offset
I160228 19:43:20.355781 server/node.go:352  store store=0:0 ([]=) not bootstrapped
I160228 19:43:20.357376 raft/raft.go:459  [group 1] 1 became follower at term 5
I160228 19:43:20.357435 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160228 19:43:20.357464 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160228 19:43:20.357519 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
W160228 19:43:21.837114 kv/dist_sender.go:621  failed to invoke BeginTransaction ["a",/Min), Put ["a",/Min), Put ["b",/Min): txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=bd7074cd key="a" rw=true pri=0.01042113 iso=SERIALIZABLE stat=PENDING epo=1 ts=1456688601.835416854,0 orig=1456688601.835416854,0 max=1456688601.835416854,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=620a8dd3 key="b" rw=false pri=0.00845147 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456688601.832056884,0 orig=1456688601.832056884,0 max=1456688601.832056884,0
I160228 19:43:21.837372 client/db.go:488  failed batch: txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=bd7074cd key="a" rw=true pri=0.01042113 iso=SERIALIZABLE stat=PENDING epo=2 ts=1456688601.835416854,0 orig=1456688601.835416854,0 max=1456688601.885416854,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=620a8dd3 key="b" rw=false pri=0.00845147 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456688601.832056884,0 orig=1456688601.832056884,0 max=1456688601.832056884,0
I160228 19:43:21.881541 storage/replica_command.go:457  auto-gc'ed 620a8dd3 (1 intents)
I160228 19:43:21.885125 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.14s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	23.712s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestFlagsToStr
--- PASS: TestFlagsToStr (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-29 22:02
Duplicate of #4723.

**Closed by petermattis** 2016-02-29 22:02 UTC
Labels: test-failure
