### ISSUE TITLE
sql: logictest improvement proposals

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#18096] opened 2017-08-31 19:12 UTC
Some things that I would like, some of which have been mentioned by others as well:

* [x] Be able to name a subsection of a test and indent it (possibly running this in a fresh database so its scope doesn't escape the subtest),
* [ ] introduce a file extension so we can get syntax highlighting (even just mapping the extension to SQL syntax would probably still work decently),
* [ ] for sufficiently long outputs (>4 lines or so), show a diff of the expected and actual.

Maybe crazy:

* [ ] Add a `debugger` statement that drops you into a SQL shell at the point it was added,
* [ ] have a way to test inputs to pgwire as easily as we test SQL statements (distinct but related to logic tests).

cc @knz @jordanlewis @lego thoughts?

**Comment by knz** [comment] 2017-08-31 20:33
All this seems worthwhile, but then make it a checkbox list so we see progress when this moves forward :)

**Comment by knz** [comment] 2017-08-31 20:33
Go for it!

**Comment by lego** [comment] 2017-08-31 21:14
I initially imagined a comment based syntax for naming tests because that way it would conform to SQL highlighting and also not be a difficult incremental change from the existing tests. For example, 
```sql
query T
SELECT '192.168.1.2':::INET;
----
192.168.1.2

query T
SELECT '192.168.1.2/24':::INET;
----
192.168.1.2/24
```

Would become this

```sql
# TestName: It parses an IP
query T
SELECT '192.168.1.2':::INET;
----
192.168.1.2

# TestName: It parses an IP with mask bits
query T
SELECT '192.168.1.2/24':::INET;
----
192.168.1.2/24
```
And it would instead show
```
--- FAIL: TestLogic (0.16s)
    --- FAIL: TestLogic/default (0.01s)
        --- FAIL: TestLogic/default/inet (0.11s)
        	logic_test.go:1771:
                        FAILED: It parses an IP with mask bits 
        		testdata/logic_test/inet:10:
        		expected:
        		    192.168.1.2/24

        		but found (query options: "") :
        		    192.168.1.2
```

**Comment by lego** [comment] 2017-10-23 17:04
After a bit of discussion over lunch with @BramGruneir about logic tests I wanted to call out a few particular problems with them:
1) They poorly test and organize regressions, bugs, or small details of a feature -- let's call them specific tests, in contrast to a general test of feature capabilities.
2) They aren't verbose about what is being tested, and often require implicit knowledge.

For problem 1, anything considered specific tests will at best have a comment preceding the test lines referring detailing what is being tested and referring to a Github issue. But, it won't be clear what statements this comment directly refers to or indicate any other setup around the specific test.

Problem 2 can be solved with a fair level of comments and helped by organizing tests but currently, there are no standards or expectations around test organization.

A solution to the organization problem would naively be to separate tests into separate files for their test cases. What this solves is how intertwined general feature testing is with specific testing. The downside of this is that the files will have redundant setup, but I would argue that this helps the specific tests be less brittle and more targetted.

One idea that also came up was the idea of making logictests more like spec tests. This serves as more of a possible alternative than a suggestion. This has clear issues where spec tests can be wildly nested and make it hard to understand what the current test state is at any given point. This is where strictly sequential tests with no fancy set up or checkpointing makes sense (our current logictests). 

And of course some general improvement ideas:
- Output a CSV on any test failures that may include the expected and actual results, and possibly even the database state from before the line that failed. This might serve an overlapping use case as the suggested `debugger` statement.

Also, does anyone know what the equivalent tests in postgres are? It would be great to understand how they solve these problems, if at all.

**Comment by justinj** [comment] 2017-10-23 17:08
Postgres' equivalent to logic tests is [this](https://github.com/postgres/postgres/tree/master/src/test/regress/sql), I think. The expected results live [here](https://github.com/postgres/postgres/tree/master/src/test/regress/expected).

**Comment by jordanlewis** [comment] 2020-10-06 02:22
Closing due to age.

**Closed by jordanlewis** 2020-10-06 02:22 UTC
Labels: A-testing, C-enhancement, S-3-productivity
