### ISSUE TITLE
UDFs are not respecting schema context

### ISSUE THREAD

**Issue by joachimbulow** [cockroachdb/cockroach#126244] opened 2024-06-26 10:13 UTC
**Describe the problem**

Hello, we are having problems leveraging UDFs in our multi-database cluster setup, because equal UDF definitions in different databases are not respecting the context in which they are executed, seemingly arbitrarily executing against tables in other databases.

**To Reproduce**

I have a minimal reproducable example, which is really simple. It is attached below.

Essentially we create the same table and function in two databases, with users only able to access their respective table.

Trying to execute the function yields PRIVILEGE ERROR because the function is for some reason referencing a table in another database.

**Expected behavior**

We would expect a function declared in the `foo`-schema to target the baz table in the same `foo` schema.
instead it seems that the `qux` function always chooses the same tables: the ones in the `bar` schema.

This results in one of the users getting privilege errors when calling the function. 
This is the opposite of what should happen.

**Additional data / screenshots**

Here is the minimal reproducable example.
Note that you need to connec to the databases separately from the context of the two users, where the comment says so.
It is assumed that you are logged into an `admin` account per default.

```SQL

CREATE DATABASE foo;
CREATE DATABASE bar;

CREATE USER foo_user;
CREATE USER bar_user;

CREATE ROLE foo_role;
CREATE ROLE bar_role;

USE foo;

-- This table is defined in both database
CREATE TABLE baz
(
    id   int     NOT NULL,
    name varchar NOT NULL,
    PRIMARY KEY (id)
);

CREATE
FUNCTION qux() RETURNS VOID LANGUAGE SQL AS $$
    SELECT * FROM baz;
$$;

ALTER TABLE baz
    OWNER TO foo_role;

USE bar;

CREATE TABLE baz
(
    id   int     NOT NULL,
    name varchar NOT NULL,
    PRIMARY KEY (id)
);

CREATE
FUNCTION qux() RETURNS VOID LANGUAGE SQL AS $$
    SELECT * FROM baz;
$$;

ALTER TABLE baz
    OWNER TO bar_role;

GRANT foo_role TO foo_user;
GRANT bar_role TO bar_user;

--- Now connect as foo_user to the foo database and try to run the function
-- This works fine
SELECT * FROM baz;
-- But this fails [42501] ERROR: user foo_user does not have SELECT privilege on relation baz
SELECT qux();

-- This DOES work
SELECT bar.public.qux();

--- Now connect as bar_user on the bar database and try to run the function
-- Now both of these will work
SELECT * FROM baz;
SELECT qux();

```

**Environment:**
 - CockroachDB version 23.2.6
 - Server OS: Happens either way
 - Client app: RAW SQL

**Additional context**
What was the impact?

Our production application is (luckily) able to run the functions, but our staging environment is broken.

I should note, that the problem is fixable by specifing the full context in the function call.
As also shown in the example, `SELECT bar.public.qux()` is fine. Then the function does not randomly SELECT from the table in another database.

Jira issue: CRDB-39814

**Comment by rafiss** [comment] 2024-06-26 20:55
I followed the instructions you included in the issue, but I could not reproduce the issue you are having.

Can you connect as `foo_user` to the `foo` database, then run: `show grants on table baz;`?

**Comment by joachimbulow** [comment] 2024-06-27 08:50
Here are the grants for the `foo` db `baz` table:

<img width="1415" alt="image" src="https://github.com/cockroachdb/cockroach/assets/43139346/3e06f380-ed99-4720-9911-bdf9b6c7c02d">

**Comment by rafiss** [comment] 2024-06-27 20:01
> By not being able to reproduce, i suppose you mean can connect as each individual user to each respective database, and run the qux() directly function without privilege violation?

That is correct. But now we have an explanation. This problem is related to an issue with the optimizer query cache: https://github.com/cockroachdb/cockroach/blob/1c3b6a67b16c71db5bce555aeb4279cc9095256f/pkg/sql/opt/metadata.go#L407-L440

Since it's cache related, that explains why the issue does not always happen. We will have a fix for this soon.

**Closed** 2024-06-27 21:44 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-foundations, v23.1.29, v23.2.10, v24.1.4

**Comment by joachimbulow** [comment] 2024-07-08 10:27
> > By not being able to reproduce, i suppose you mean can connect as each individual user to each respective database, and run the qux() directly function without privilege violation?
> 
> That is correct. But now we have an explanation. This problem is related to an issue with the optimizer query cache:
> 
> https://github.com/cockroachdb/cockroach/blob/1c3b6a67b16c71db5bce555aeb4279cc9095256f/pkg/sql/opt/metadata.go#L407-L440
> 
> Since it's cache related, that explains why the issue does not always happen. We will have a fix for this soon.

Perfect!! Thank you very much
