### ISSUE TITLE
Unable to use `READ-COMMITTED` isolation along with the foreign key constraints

### ISSUE THREAD

**Issue by 50U10FCA7** [cockroachdb/cockroach#120224] opened 2024-03-11 16:50 UTC
**Describe the problem**

Related to #110435

Foreign key constraints failed with
```
ERROR: lock promotion from Shared to Intent is not allowed
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/110435
```

when using them along with `READ-COMMITTED` isolation.

**To Reproduce**

1. Set cluster to use `READ-COMMITTED` isolation.
2. Prepare two tables where one refers to another.
3. Open two transacted sessions and configure to use `READ-COMMITTED` isolation.
4. Insert something to referenced table in the first session.
5. Insert something to referencing table in the second session.
6. Update the referenced table in the second session.
7. Commit the first session.

**Expected behavior**
No error occurred.

**Additional data / screenshots**

MRE:
```sql
--If run multiple times
DROP TABLE my_chats_views;
DROP TABLE my_chats;

--Prerequisites
CREATE TABLE my_chats (
    id INT PRIMARY KEY,
    messages_count INT
);
CREATE TABLE my_chats_views (
    chat_id INT REFERENCES my_chats(id),
    user_id INT,
    unread_messages_count INT
);

SET CLUSTER SETTING sql.txn.read_committed_isolation.enabled = 'true';

--Step #1 (session A)
SET default_transaction_isolation = 'read committed';

BEGIN;
INSERT INTO my_chats (id, messages_count) VALUES (1, 1);

--Step #2 (session B)
SET default_transaction_isolation = 'read committed';

BEGIN;
INSERT INTO my_chats_views (chat_id, user_id, unread_messages_count) VALUES (1, 1, 1);
UPDATE my_chats SET messages_count = 2 WHERE id = 1;

--Step #3 (session A)
COMMIT;
```

**Environment:**
 - CockroachDB version: v23.2.2
 - Server OS: CockroachDB docker image
 - Client app: `cockroach sql`

```
sh-5.1# cockroach --version
cockroach version details:
Build Tag:        v23.2.2
Build Time:       2024/02/26 21:06:15
Distribution:     CCL
Platform:         linux arm64 (aarch64-unknown-linux-gnu)
Go Version:       go1.21.5 X:nocoverageredesign
C Compiler:       gcc 6.5.0
Build Commit ID:  4634a65a4891dcca4fc56916481d56721954d813
Build Type:       release
Enabled Assertions: false
(use 'cockroach version --build-tag' to display only the build tag)
```

Jira issue: CRDB-36555

**Comment by michae2** [comment] 2024-03-12 18:40
Thank you for opening an issue! I'm marking this as a duplicate of https://github.com/cockroachdb/cockroach/issues/110435 for now.

**Closed by michae2** 2024-03-12 18:40 UTC
Labels: C-bug, O-community, T-sql-queries, A-read-committed

**Comment by tyranron** [comment] 2024-03-13 10:20
@michae2 but it's not clear why the shared lock happens at all here on the referenced table, Is it expected?

**Comment by michae2** [comment] 2024-03-13 20:19
@tyranron the shared lock is expected. It is part of the foreign key check on the referenced table. Under read committed isolation we need to acquire a shared lock to make sure the foreign key is not deleted by a concurrent transaction.

By looking at `EXPLAIN` of the insert into my_chats_views (with the insert fast path disabled) we can see the foreign key check with `for share` locking in the plan:

```
demo@127.0.0.1:26257/demoapp/defaultdb> BEGIN;
BEGIN

Time: 0ms total (execution 1ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb  OPEN> EXPLAIN INSERT INTO my_chats_views (chat_id, user_id, unread_messages_count) VALUES (1, 1, 1);
                                   info
--------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • insert fast path
    into: my_chats_views(chat_id, user_id, unread_messages_count, rowid)
    FK check: my_chats@my_chats_pkey
    FK check locking strength: for share
    FK check locking durability: guaranteed
    size: 4 columns, 1 row
(9 rows)

Time: 2ms total (execution 2ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb  OPEN> SET LOCAL enable_insert_fast_path = off;
SET

Time: 0ms total (execution 0ms / network 0ms)

demo@127.0.0.1:26257/demoapp/defaultdb  OPEN> EXPLAIN INSERT INTO my_chats_views (chat_id, user_id, unread_messages_count) VALUES (1, 1, 1);
                                     info
------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • root
  │
  ├── • insert
  │   │ into: my_chats_views(chat_id, user_id, unread_messages_count, rowid)
  │   │
  │   └── • buffer
  │       │ label: buffer 1
  │       │
  │       └── • values
  │             size: 4 columns, 1 row
  │
  └── • constraint-check
      │
      └── • error if rows
          │
          └── • lookup join (anti)
              │ estimated row count: 0
              │ table: my_chats@my_chats_pkey
              │ equality: (column1) = (id)
              │ equality cols are key
              │ locking strength: for share
              │ locking durability: guaranteed
              │
              └── • scan buffer
                    estimated row count: 1
                    label: buffer 1
(29 rows)

Time: 2ms total (execution 1ms / network 0ms)
```
