### ISSUE TITLE
roachtest: automatic issue assignment appears to be broken

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#31464] opened 2018-10-16 13:55 UTC
Automatic assignment of issues appears to be broken after the recent refactorings. @andreimatei You're likely the perpetrator of this crime, and also the one affected by it. I'll take a quick look, though, to see if there is an easy explanation / fix.

**Comment by petermattis** [comment] 2018-10-16 14:10
Well, the logic looks sane. Perhaps the addition of `FatalIfError` is causing a problem. I haven't looked at the recent mis-assignments, but if they are all happening from fatals generated by that code, then they would be attributed to you.

**Comment by andreimatei** [comment] 2018-10-16 14:35
Thanks for looking. I'll take it from here.

**Comment by andreimatei** [comment] 2018-10-16 17:41
Dived into the assignment logic. It seems to be working as intended: the issues are assigned to whomever has the blame on the line corresponding to the first frame under the test runner function. So, generally, this is the line inside the `test.Run()` that, directly or indirectly, generates the failure.
In the case of recent issues filed, the cluster creation was failing, and the call to `t.Fatal()` is done through the `FatalIfErr()` function which is called directly from the test runner, and I take the blame from `FatalIfErr()`.
Whether this policy makes particular sense, I'll let history decide. One consequence is that, for the acceptance tests, all failures with go to you, Peter, because you own the `tc.fun()` line here:
https://github.com/cockroachdb/cockroach/blob/df378dbb9fd8ceef62a949398f9753aac4f27350/pkg/cmd/roachtest/acceptance.go#L65
Same for other tests that use a table-driven approach to creating tests and subtests.
I'm terrified that I'm about to take the blame for many things when I get rid of subtests.

Closing this to bubble up another day.

**Closed by andreimatei** 2018-10-16 17:41 UTC
Labels: A-testing, C-bug

**Comment by petermattis** [comment] 2018-10-16 18:09
@andreimatei Your idea to make ownership of tests explicit (via a field in `testSpec`) makes sense to me.
