### ISSUE TITLE
circleci: failed tests (13678): TestPut 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4797] opened 2016-03-02 23:04 UTC
The following test appears to have failed:

[#13678](https://circleci.com/gh/cockroachdb/cockroach/13678):

```
I160302 23:03:03.262578 acceptance/replication_test.go:66  found 2 replicas
I160302 23:03:05.906403 acceptance/replication_test.go:66  found 2 replicas
I160302 23:03:07.048950 acceptance/replication_test.go:66  found 2 replicas
I160302 23:03:18.054619 acceptance/replication_test.go:66  found 2 replicas
I160302 23:03:18.155183 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestPut (28.07s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestDockerPython
I160302 23:03:19.044012 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
I160302 23:03:20.455887 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160302 23:03:21.743113 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.50
I160302 23:03:21.743155 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:63: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 01:46
Duplicate of #4714.

**Closed by petermattis** 2016-03-06 01:46 UTC
Labels: test-failure
