### ISSUE TITLE
optbuilder: DISTINCT ON doesn't work with expressions

### ISSUE THREAD

**Issue by cward-titanhq** [cockroachdb/cockroach#126932] opened 2024-07-10 15:41 UTC
**Describe the problem**

When using the JSONB type, a query written with DISTINCT ON cannot be sorted. It should be possible to use an ORDER BY clause to determine which of the duplicate rows are eliminated from the results - see the [manual](https://www.cockroachlabs.com/docs/stable/select-clause#eliminate-duplicate-rows).

**To Reproduce**

Create the following in CockroachDB:

```sql
CREATE TABLE test (
  doc JSONB NOT NULL
);

INSERT INTO test (doc) VALUES
('{"id" : "a8b0f1bd-787e-46c6-ae35-909ee406493d", "colour" : "blue", "size" : "large"}'::JSONB),
('{"id" : "ce2e743d-42ba-4dc6-8e38-eaea9a2bba7e", "colour" : "blue", "size" : "medium" }'::JSONB),
('{"id" : "2033835c-2fdf-46cb-a8d7-1468355bd125", "colour" : "red", "size" : "large"}'::JSONB),
('{"id" : "efac2830-90cd-4a37-b7d5-157bf251c367", "colour" : "red", "size" : "large"}'::JSONB),
('{"id" : "8ad51b95-a601-44b7-a25a-1dd342355c72", "colour" : "green", "size" : "small"}'::JSONB);
```

Then run the following query:
```sql
SELECT DISTINCT ON (doc->>'colour') *
FROM test
ORDER BY doc->>'colour', doc->>'size';
```

The result is the following error:

```
ERROR: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
SQLSTATE: 42P10
```

**Expected behavior**
There should be no error, as the leftmost arguments to ORDER BY match the DISTINCT ON arguments. What you should get is this (works in PostgreSQL):
```
                                        doc                                         
------------------------------------------------------------------------------------
 {"id": "a8b0f1bd-787e-46c6-ae35-909ee406493d", "size": "large", "colour": "blue"}
 {"id": "8ad51b95-a601-44b7-a25a-1dd342355c72", "size": "small", "colour": "green"}
 {"id": "2033835c-2fdf-46cb-a8d7-1468355bd125", "size": "large", "colour": "red"}
(3 rows)
```

**Additional data / screenshots**

**Environment:**
 - CockroachDB CCL v24.1.2 (x86_64-pc-linux-gnu, built 2024/06/27 18:06:30, go1.22.3 X:nocoverageredesign)
 - Docker container [cockroachdb/cockroach:v24.1.2](https://hub.docker.com/layers/cockroachdb/cockroach/v24.1.2/images/sha256-9e7ead2ffd6f57bd37a0fd093da1f204ab61db2d7cf8d1c95c8fa9a491385850?context=explore)
 - Client app: `cockroach sql`

**Additional context**
May be possible to workaround with  GROUP BY

Jira issue: CRDB-40194

**Comment by yuzefovich** [comment] 2024-07-16 21:57
Thanks for the report! This seems like a long-standing limitation that we were not aware off. In particular, it appears that if we have almost any type of expression in the ORDER BY clause, we then are unable to use that same expression in the DISTINCT ON clause. For example, this works in PG but fails in CRDB:
```sql
CREATE TABLE t (a INT, b INT);
SELECT DISTINCT ON (a + b) * FROM t ORDER BY a + b;
```
I think the problem is that in this code we only hard-code a single type of expression that we get the column ID for, but we need to have a more general mechanism https://github.com/cockroachdb/cockroach/blob/2e7de368543453cb6c4c9bd4944160d3af0c404d/pkg/sql/opt/optbuilder/distinct.go#L95-L107

**Comment by yuzefovich** [comment] 2024-07-16 22:04
I'll close this as a duplicate of #107516 - please follow that issue for updates.

In the mean time, it's possible to come up with a workaround with something similar to:
```sql
SELECT DISTINCT ON (tmp) *, doc->>'colour' AS tmp
FROM test
ORDER BY doc->>'colour', doc->>'size';
```

**Closed by yuzefovich** 2024-07-16 22:04 UTC
Labels: C-enhancement, O-community, T-sql-queries
