### ISSUE TITLE
bulk: import data race, sstable corruption

### ISSUE THREAD

**Issue by jbowens** [cockroachdb/cockroach#52720] opened 2020-08-12 18:48 UTC
I've been running some large imports in order to test large clusters with large disks. I've seen two separate failures due to  invalid checksums related to imported sstables.

The first  was during large (50 billion rows) `bank` import. Two nodes crashed with a sstable block checksum mismatch. The two sstables (n5's 056150.sst and n7's 055949.sst) are identical and were ingested as a part of the import.
```
I200811 23:36:12.123487 1398 kv/kvserver/replica_command.go:414  [n5,s5,r40762/3:/{Table/53/1/4…-Max}] initiating a split of this range at key /Table/53/1/48619048833 [r40764] (manual); r40762/2 inactive; delayed split for 9.0s to avoid Raft snapshot; r40762/2 is being probed (may or may not need a Raft snapshot)
E200811 23:36:12.234761 1398 kv/kvserver/replica_corruption.go:43  [n5,s5,r40762/3:/{Table/53/1/4…-Max}] stalling replica due to: unable to compute stats for LHS range after split: pebble/table: invalid table 056150 (checksum mismatch at 9203644/27289)
F200811 23:36:12.237082 1398 kv/kvserver/replica_corruption.go:43  [n5,s5,r40762/3:/{Table/53/1/4…-Max}] replica is corrupted: replica corruption (processed=true): unable to compute stats for LHS range after split: pebble/table: invalid table 056150 (checksum mismatch at 9203644/27289)
```
```
I200811 23:35:55.167513 3141514 kv/kvserver/replica_command.go:414  [n7,s7,r40762/2:/{Table/53/1/4…-Max}] initiating a split of this range at key /Table/53/1/48619048833 [r40811] (manual)
E200811 23:35:55.311563 3141514 kv/kvserver/replica_corruption.go:43  [n7,s7,r40762/2:/{Table/53/1/4…-Max}] stalling replica due to: unable to compute stats for LHS range after split: pebble/table: invalid table 055949 (checksum mismatch at 9203644/27289)
F200811 23:35:55.320118 3141514 kv/kvserver/replica_corruption.go:43  [n7,s7,r40762/2:/{Table/53/1/4…-Max}] replica is corrupted: replica corruption (processed=true): unable to compute stats for LHS range after split: pebble/table: invalid table 055949 (checksum mismatch at 9203644/27289)
```
```
I200811 23:35:50.541614 378 vendor/github.com/cockroachdb/pebble/ingest.go:271  [n7] [JOB 53616] ingesting: sstable created 055949
I200811 23:35:50.550028 378 vendor/github.com/cockroachdb/pebble/ingest.go:638  [n7] [JOB 53616] ingested L6:055949 (47 M)
```
[5.cockroach.log](https://gist.githubusercontent.com/jbowens/c4bc022175c3b57bc1ce2a0ec2dc40b8/raw/d97d25fbb2501c3ab97628dff5e218d3bdb94fb8/bank.5.cockroach.log), [7.cockroach.log](https://gist.githubusercontent.com/jbowens/c4bc022175c3b57bc1ce2a0ec2dc40b8/raw/d97d25fbb2501c3ab97628dff5e218d3bdb94fb8/bank.7.cockroach.log)

The second failure was during a large (100k) tpcc import and this time a `kvserverpb.ReplicatedEvalResult_AddSSTable`-level checksum.
```
I200812 02:17:39.510210 5739013 kv/kvserver/replica_command.go:414  [n5,s5,r47718/1:/Table/55/1/{9948/6…-20000/…}] initiating a split of this range at key /Table/55/1/9954/4/-2936/2 [r47746] (manual)
I200812 02:17:40.249143 5738570 kv/kvserver/replica_command.go:414  [n5,s5,r47694/3:/Table/55/{1/90901…-2}] initiating a split of this range at key /Table/55/1/90907/7/-1752/3 [r47747] (manual)
I200812 02:17:43.993221 417 server/status/runtime.go:504  [n5] runtime stats: 19 GiB RSS, 493 goroutines, 2.4 GiB/10 GiB/7.5 GiB GO alloc/idle/total, 8.1 GiB/10 GiB CGO alloc/total, 16863.5 CGO/sec, 435.4/86.9 %(u/s)time, 0.1 %gc (3x), 434 MiB/557 MiB (r/w)net
I200812 02:17:44.859395 5741582 kv/kvserver/replica_command.go:414  [n5,s5,r47747/3:/Table/55/{1/90907…-2}] initiating a split of this range at key /Table/55/1/90913/4/-2277/6 [r47748] (manual)
I200812 02:17:46.846216 5742626 kv/kvserver/replica_command.go:414  [n5,s5,r47765/3:/Table/53/1/{28679/…-40000/1}] initiating a split of this range at key /Table/53/1/28683/17979 [r47749] (manual)
I200812 02:17:49.936896 5743743 kv/kvserver/replica_command.go:414  [n5,s5,r47748/3:/Table/55/{1/90913…-2}] initiating a split of this range at key /Table/55/1/90919/1/-2637/12 [r47750] (manual)
I200812 02:17:50.197355 5744146 kv/kvserver/replica_command.go:414  [n5,s5,r47749/3:/Table/53/1/{28683/…-40000/1}] initiating a split of this range at key /Table/53/1/28687/14211 [r47751] (manual)
F200812 02:17:51.381841 380 kv/kvserver/replica_proposal.go:494  [n5,s5,r47755/1:/Table/55/1/{9960/1…-20000/…}] checksum for AddSSTable at index term 6, index 14 does not match; at proposal time 9f9a14ed (2677675245), now dc61a58e (3697386894)
```
[5.cockroach.log](https://gist.githubusercontent.com/jbowens/c4bc022175c3b57bc1ce2a0ec2dc40b8/raw/d97d25fbb2501c3ab97628dff5e218d3bdb94fb8/tpcc.5.cockroach.log)

I suspected a data race in the IMPORT code path, so I tried running an IMPORT on a cockroach binary compiled with `-race`. It produced a race, but one of the goroutine stack trace escaped capture: [datarace.txt](https://gist.githubusercontent.com/jbowens/c4bc022175c3b57bc1ce2a0ec2dc40b8/raw/316054bdc59924a903d5a00b6022c58d74020b11/datarace.txt)

For what it's worth, all of these IMPORTs were run on clusters with `kv.bulk_io_write.concurrent_addsstable_requests` set to the number of nodes in the cluster.

Epic CRDB-8816

Jira issue: CRDB-3926

**Comment by dt** [comment] 2020-08-13 02:55
It is really unfortunate that that datarace is missing the second stack since that is a very puzzling suggestion. AFAIK, the goroutine that is adding is also the one that will be reading to flush into an SST and that's it -- I don't know, off the top of my head, of anyone else who reads that buffer. Hopefully another repro might catch that second stack.

**Comment by jbowens** [comment] 2020-09-14 17:11
In both the SSTable from the bank import up above and the SSTable provided by the user in #54309, only the one block's checksum appears to be incorrect. If you skip the checksum check, the SST otherwise checks out: eg, keys are ordered, remaining blocks decode fine and when manually inspecting the keys they look normal. The SSTable from the bank import doesn't appear to have any gaps in its keys:

```
/Table/53/1/48618130104/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130105/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130106/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130107/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130108/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130109/0/1597167848.261572582,0#0,SET
Starting block 9203644 with checksum failure.
/Table/53/1/48618130110/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130111/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130112/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130113/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130114/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130115/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130116/0/1597167848.261572582,0#0,SET
/Table/53/1/48618130117/0/1597167848.261572582,0#0,SET
```

I can't think of an explanation other than concurrent writes to the `*sstable.Writer`, but it's weird that it only affects the checksum in both cases.

cc @petermattis, @itsbilal in case this sparks any ideas

**Comment by petermattis** [comment] 2020-09-14 17:15
In addition to the keys and values, the checksum covers the "restarts" table at the end of the block. Is it possible the corruption is in the "restarts" table? I don't think we'd notice that if we were simply dumping the contents of the block. You might try seeing what the `sstable layout` for the block looks like.

**Comment by jbowens** [comment] 2020-09-14 18:21
The restart offsets printed from `sstable layout` look reasonable in both files: offsets within the block at regular intervals. I guess we wouldn't know if a value was corrupted in the bank sstable. The user-provided sstable encodes time series data, and everything _looks_ okay and decodes okay by the Cockroach value formatter.

**Comment by petermattis** [comment] 2020-09-15 12:56
The offsets within a block are misleading when the block is snappy encoded. For instance, here is what `sstable layout` shows for one of the checksum failure blocks:

```
   2568715  data (2415)
pebble/table: invalid table 000000 (checksum mismatch at 2568715/2415): 1
   2568715    record (3570 = 4 [0] + 50 + 3516) [restart]
              <42>#274435316,MERGE <3516>
   2572285    record (3531 = 4 [39] + 11 + 3516)
              <42>#274810147,MERGE <3516>
   2575816    record (3531 = 4 [39] + 11 + 3516)
              <42>#275189513,MERGE <3516>
   2579347    record (3531 = 4 [39] + 11 + 3516)
              <42>#275565599,MERGE <3516>
   2582878    record (3531 = 4 [39] + 11 + 3516)
              <42>#275941193,MERGE <3516>
   2586409    record (3531 = 4 [39] + 11 + 3516)
              <42>#276316804,MERGE <3516>
   2589940    record (3531 = 4 [39] + 11 + 3516)
              <42>#276692855,MERGE <3516>
   2593471    record (3531 = 4 [39] + 11 + 3516)
              <42>#277067668,MERGE <3516>
   2597002    record (3531 = 4 [39] + 11 + 3516)
              <42>#277443342,MERGE <3516>
   2600533    [restart 2568715]
   2571135  data (2415)
```

Many of the record offsets are beyond the start of the next block, which confused me for a moment until I realized that the block is snappy compressed. But that points to something else surprising. If we ignore the checksum failure, snappy compression was able to succeed. That's very surprising.

In both cases, the mismatch checksums are quite different. It isn't the case that we're seeing a bit flip in the checksum. It looks like ~50% of the bits in the checksum are different which would match up with the checksums being computed on different data.

Because the blocks are snappy compressed and the checksum is compute on the compressed data, I suspect that whatever is causing the mismatch is occurring on the compressed data. If the corruption was occurring on the uncompressed data then I don't think we'd be seeing a checksum failure at all.

I tried various attempts to take the decompressed blocks and recompress them on buffers filled with random data. In all cases, the recompressed and original blocks were byte for byte identical.

**Comment by petermattis** [comment] 2020-09-15 13:01
During sstable writing, the checksum of the block is computed as `crc.New(compressed).Update([]byte{snappyCompressionBlockType}).Value()`. The `snappyCompressionBlockType` is written on the trailer of the compressed data. During reading the checksum is computed as `crc.New(compressed+block-type).Value()`. The computations are intended to be equivalent and I verified they produce exactly the same results on the blocks we're examining. (It would have been very surprising if the calculations produced different results, but it is good to verify these things).

**Comment by jbowens** [comment] 2020-09-15 13:09
I find the checksum failure in the AddSSTableRequest proto perplexing, because that checksum is calculated after the sstable is already constructed and serialized. We either have two races or need to be able to explain both failures with one race.

**Comment by petermattis** [comment] 2020-09-15 13:12
> I tried various attempts to take the decompressed blocks and recompress them on buffers filled with random data. In all cases, the recompressed and original blocks were byte for byte identical.

Huh, well apparently I did this wrong in the first attempt because now I have an interesting result. For the timeseries data block, recompressing the decoded blocks produces a different result from the block stored on disk.

The checksum stored in the sstable is `2947ecee`. At read time, the computed checksum is `cd3153a`. If I ignore the checksum failure, decompress the block and recompress it, the recompressed block differs in a single byte from the data stored on disk. This single byte difference occurs at offset 2066: 0xd (recompressed) vs 0x5 (original). The checksum of the recompressed block is `2947ecee`. `0xd` in binary is `1101`. `0x5` in binary is `101`. So we have a 1-bit difference leading to a checksum difference which somehow is not affecting snappy decompression. I suspect that the corruption in #54309 is on-disk data corruption.

**Comment by petermattis** [comment] 2020-09-15 13:13
> I find the checksum failure in the AddSSTableRequest proto perplexing, because that checksum is calculated after the sstable is already constructed and serialized. We either have two races or need to be able to explain both failures with one race.

Or we have one data race and one on-disk corruption.

**Comment by kocoten1992** [comment] 2020-09-15 14:37
For the record, I'm using Samsung SSD 860 1TB.

**Comment by jbowens** [comment] 2020-09-15 21:00
I tried iterating over the bank sstable `056150.sst`'s problematic block, adding keys to a fresh `blockWriter` configured with the default 16 restart interval and it produced an identical uncompressed block. It seems to confirm that the restart intervals are okay.

**Comment by petermattis** [comment] 2020-09-15 22:11
> I tried iterating over the bank sstable 056150.sst's problematic block, adding keys to a fresh blockWriter configured with the default 16 restart interval and it produced an identical uncompressed block. It seems to confirm that the restart intervals are okay.

Interesting. I think this is evidence that the uncompressed data is not corrupted. So is this another instance of the compressed data being different? Yet when we recompress the data it is the same as that stored on disk. So did the checksum itself get modified? There are two many bit differences between `0xb641a8e7` and `e7e1a679` for that to seem correct. I'll poke at this some more tomorrow morning, but would love if you or Bilal figure this out before then.

**Comment by andreimatei** [comment] 2020-11-09 17:22
Seems to have happened again - #56186
This is both marked as "S0" and also hasn't had an update from September :) What gives?

**Comment by petermattis** [comment] 2020-11-09 17:48
@andreimatei We were completely unable to reproduce after significant effort. @jbowens can you take a look at #56186. Given that seems to be related to backup/restore, cc @dt as well.

**Comment by mwang1026** [comment] 2022-03-02 20:23
@dt this is pretty stale -- worth keeping around?

**Comment by dt** [comment] 2022-03-02 23:50
Nope

**Closed by dt** 2022-03-02 23:50 UTC
Labels: C-bug, A-bulkio, S-0-corruption-or-data-loss, T-bulkio
