### ISSUE TITLE
opt: limit not pushed through validated, non-null foreign key constraint

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#48674] opened 2020-05-11 03:48 UTC
Git SHA: ba19aa446d99afa159ee5bd915e31de46940ef90

I'm observing a situation where a limited scan on a snowflake schema with multiple lookup-joins is failing to push its limit into the index scan of the base table. This is surprising to me, as I would expect that a validated, non-null foreign key constraint would prove to the optimizer that the limit can be pushed down.

Here's a simplified reproduction with only two tables.

Schema:
```sql
CREATE TABLE ref (id INT8 PRIMARY KEY, data INT8);

CREATE TABLE base (
    a INT8 NOT NULL,
    b INT8 NOT NULL,
    r INT8 NOT NULL REFERENCES ref,
    PRIMARY KEY (a, b)
);

SHOW CONSTRAINTS FROM base;

  table_name | constraint_name | constraint_type |              details               | validated
-------------+-----------------+-----------------+------------------------------------+------------
  base       | fk_r_ref_ref    | FOREIGN KEY     | FOREIGN KEY (r) REFERENCES ref(id) |   true
  base       | primary         | PRIMARY KEY     | PRIMARY KEY (a ASC, b ASC)         |   true
```

Expected query plan without join:
```sql
EXPLAIN SELECT b FROM base WHERE a = 1 ORDER BY b LIMIT 50;

    tree    |    field    | description
------------+-------------+---------------
            | distributed | false
            | vectorized  | false
  render    |             |
   └── scan |             |
            | table       | base@primary
            | spans       | /1-/2
            | limit       | 50
```

Unexpected query plan with join:
```sql
EXPLAIN   SELECT b, data
            FROM base, ref
           WHERE a = 1 AND r = id
        ORDER BY b
           LIMIT 50;

          tree          |         field         | description
------------------------+-----------------------+---------------
                        | distributed           | true
                        | vectorized            | false
  render                |                       |
   └── limit            |                       |
        │               | count                 | 50
        └── lookup-join |                       |
             │          | table                 | ref@primary
             │          | type                  | inner
             │          | equality              | (r) = (id)
             │          | equality cols are key |
             │          | parallel              |
             └── scan   |                       |
                        | table                 | base@primary
                        | spans                 | /1-/2
```

Notice that the limit is performed after the join. This is either a failure in my understanding of whether this limit can be pushed down in this situation or an optimizer rule ripe for picking.

**Comment by nvanbenschoten** [comment] 2020-05-11 03:52
This actually looks like the same issue as https://github.com/cockroachdb/cockroach/issues/21171.

**Comment by RaduBerinde** [comment] 2020-05-11 03:53
Yeah, I explained in there a difficulty I hit. But at least in this case, where there are no filters that are being pushed down to the referenced table, we could surely do it.

**Comment by nvanbenschoten** [comment] 2020-05-11 04:02
I expect that a large chunk of cases won't have filters on the referenced tables, they'll just be using them to augment the resulting rows with more information that is stored in a highly denormalized schema, so even the basic version of this would be very useful. For instance, I bet you could find all kinds of cases in `pg_catalog` where this comes up (if we actually had proper fk relationships in there).

**Comment by RaduBerinde** [comment] 2020-05-11 14:36
Right, the issue is that if you have a filter on the equality column, it will get pushed down to both sides. For example `SELECT child, parent WHERE child.x = parent.y AND child.x > 1`. We will have a `parent.y > 1` filter pushed down after which it will be hard to tell whether the transformation is correct. I think there are some workarounds that we can investigate (like setting a flag in the join before filter pushdown).

**Comment by andy-kimball** [comment] 2020-05-15 21:46
@DrewKimball is doing some related work with FK-sensitive rules (join elimination in group-by and project cases). He can take this one on once he's done with those.

**Comment by RaduBerinde** [comment] 2020-05-21 15:27
Closing as dup of #21171.

**Closed by RaduBerinde** 2020-05-21 15:27 UTC
Labels: A-sql-optimizer, C-enhancement
