### ISSUE TITLE
could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389

### ISSUE THREAD

**Issue by wzrdtales** [cockroachdb/cockroach#25272] opened 2018-05-03 12:03 UTC
# Description

For some reason nodes that die do not start again due to the failure you can see in the log. The strange thing is, this happens everytime a node stops due to whatever reasons. Unlike cockroach tells, the directory *-tempXYZ is emtpy. As soon as these are removed cockroach boots again. Seems to be a bug and a critical one since this stops the cluster from working without manual intervention.

# Log

```
++ hostname -f
+ exec /cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs --host cockroachdb-1.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%
I180503 11:59:36.331427 1 cli/start.go:918  CockroachDB CCL v2.0.1 (x86_64-unknown-linux-gnu, built 2018/04/23 18:39:21, go1.10)
E180503 11:59:36.590797 1 cli/error.go:109  could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389: directory not empty
Error: could not cleanup temporary directories from record file: remove /cockroach/cockroach-data/cockroach-temp713118389: directory not empty
Failed running "start"
```

**Comment by tschottdorf** [comment] 2018-05-03 13:01
@wzrdtales, if you can repro this at-will, could you stop the node and before restarting it (which would lead to this error) check whether the temp dir is empty?

**Comment by wzrdtales** [comment] 2018-05-03 15:17
@tschottdorf I already wrote that above. Yes it is empty.

**Comment by wzrdtales** [comment] 2018-05-03 15:18
Not even dotfiles in there

**Comment by wzrdtales** [comment] 2018-05-04 15:12
And as written above only deleting the dir completely solves the problem. I may just add that to the start script of the kubernetes definition

**Comment by tschottdorf** [comment] 2018-05-05 11:16
> @tschottdorf I already wrote that above. Yes it is empty.

I saw that you mentioned that it was empty, but did you check that it was empty *after* you saw the bug or before? If you saw it after, then there's a chance that it wasn't empty when the operation that catches the error started, and I'm curious whether anything is suspicious about its contents.

As a workaround, yes, adding this to the start script makes sense. We haven't seen this error in our testing and it looks like the error comes from a standard library for deleting whole directory trees, which is unlikely to have glaring bugs.

I'll make sure we try reproducing this more specifically.

**Comment by wzrdtales** [comment] 2018-05-05 11:28
A few more details, environment is azure. Data is stored on the ssd /dev/sdb.

Here some infos about the mounting

```
/dev/sdb1 on /mnt type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sdb1 on /var/lib/kubelet/pods/b1fb6e2f-5056-11e8-af4d-0227f2172d30/volumes/kubernetes.io~local-volume/local-pv-8b507ceb type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sdb1 on /home/docker-user/mounts/disk1 type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sdb1 on /mnt type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
```

Maybe you can even reproduce it yourself, the setup we utilize is sourced here https://github.com/wzrdtales/cockroachdb-azure-k8s-rancher

**Comment by tschottdorf** [comment] 2018-05-05 11:29
Hmm you're on Azure. I wouldn't be surprised if that had anything to to with it (we had trouble with fuseblk in the past), but if we can repro this with your setup then we're certainly going to be able to get to the bottom of this. Thanks for the info!

**Comment by tschottdorf** [comment] 2018-05-05 11:30
@a-robinson, can I kick this ball in your court? I imagine you'll be able to get this thing set up much faster.

**Comment by wzrdtales** [comment] 2018-05-05 11:30
No problem, azure wasn't my choice but sometimes you're forced though... :/

**Comment by benesch** [comment] 2018-05-06 01:42
Are these "fuseblk" filesystems NTFS under the hood? That's what the internet seems to suggest, and, if memory serves, Azure likes to default drives to NTFS, even on Linux.

If so, I suspect it's an issue with the way we use file locks. We're seeing similar behavior, though with a different error message, whenever a Cockroach server is restarted on Windows: https://github.com/cockroachdb/cockroach/pull/25267.

**Comment by tschottdorf** [comment] 2018-05-06 12:14
Fails instantly on my azworker:

```
* ERROR: could not cleanup temporary directories from record file: could not lock temporary directory /home/tschottdorf/cockroach-v2.0.1.linux-amd64/cockroach-data/cockroach-temp786116098, may still be in use: IO error: While lock file: /home/tschottdorf/cockroach-v2.0.1.linux-amd64/cockroach-data/cockroach-temp786116098/TEMP_DIR.LOCK: Resource temporarily unavailable
*
Failed running "start"
E180506 12:13:49.588797 1 cli/error.go:109  exit status 1
Error: exit status 1
Failed running "start"
```

I'm going to try @benesch's PR.

**Comment by wzrdtales** [comment] 2018-05-06 13:59
@benesch Can't tell this drives are the "temp" drives of azure and are setup automatically though. Could be that this is NTFS since microsoft uses their windows based hypervisor. "Temp" in this case just means if your machine gets replaced all the data is lost. But since running a db on network disks is a terrible idea we use the "temp" ssd.

**Comment by bdarnell** [comment] 2018-05-07 00:13
@wzrdtales Running a DB on network disks may be bad, but running on NTFS-via-FUSE is probably worse. We've seen a lot of problems with this configuration in our testing on azure (performance is *much* worse than reformatting the local disk as `ext4`). If you're running on azure and want to use your local disk, you need to be sure to reformat it as `ext4` (other linux filesystems should work too; just don't leave it as NTFS). 

Unfortunately, Azure sometimes wipes out your temporary disk and replaces it with a new NTFS disk when you reboot, so you'll need to check for this state and reformat the disk if it happens (automated reformats are definitely scary, though).

**Comment by wzrdtales** [comment] 2018-05-07 07:03
@bdarnell Yeah it might not be the beauty, but I still wouldn't agree that network disks would be better. I will however take your suggestion and adjust the setup to reformat that shitty thing.

**Comment by tschottdorf** [comment] 2018-05-07 10:11
@bdarnell I'm curious, is there a way for us to detect fuseblk-over-ntfs (or just fuse alone?) and warn?

**Comment by bdarnell** [comment] 2018-05-07 23:34
@tschottdorf We can detect FUSE filesystems. It's tricky to go from that to figure out *which* FUSE filesystem, but I think it's a fair bet that any FUSE filesystem is worth a warning in the logs.

**Comment by benesch** [comment] 2018-05-11 23:04
The fix for this should be going in shortly. I've filed #25436 about adding a warning if we detect we're running on a FUSE filesystem.

**Closed** 2018-05-12 00:28 UTC
Labels: C-bug, O-community, S-2-temp-unavailability
