### ISSUE TITLE
memory budget exceeded

### ISSUE THREAD

**Issue by carr123** [cockroachdb/cockroach#83767] opened 2022-07-04 07:16 UTC
- CockroachDB version V22.1.2
- Server OS: linux amd64

when i open a simple table with few records, the following error reported:
memory budget exceeded: 378880 bytes requested, 511938560 currently allocated, 512000000 bytes in budget
Consider increasing --max-sql-memory startup parameter.

i restarted cockroachdb with --max-sql-memory=1024000000, the issue gone.

i never saw this kind of error in  CockroachDB version V21.x.x
is it a bug ?

Jira issue: CRDB-17248

**Comment by yuzefovich** [comment] 2022-07-05 18:25
@carr123 is it possible for you to share the reproduction of this issue with us?

**Comment by carr123** [comment] 2022-07-07 09:20
@yuzefovich  hi,  the issue appeard again even after i set  --max-sql-memory=1024000000, 

DBeaver client reports such msg when i try to open a table.
ERROR: root: memory budget exceeded: 215040 bytes requested, 1024000000 currently allocated, 1024000000 bytes in budget
Consider increasing --max-sql-memory startup parameter.

my go program code also reports similar info: 
pq: root: memory budget exceeded: 184320 bytes requested, 1024000000 currently allocated, 1024000000 bytes in budget

one of my server nodes memory:
free -m
              total        used        free      shared  buff/cache   available
Mem:           7953        4006        1728          72        2218        3591
Swap:          2047        1936         111


the start command like such:
cockroach start --certs-dir=/home/certs --store=path=/home/cockroach/dbdata,size=60GB --listen-addr=<IP1>:26257 --http-addr=<IP1>:8080  --locality=region=office,zone=zone1 \
--locality-advertise-addr=region=office@<IP1>:26257 --advertise-addr=<IP1>:26257 --log='file-defaults: {dir: /home/cockroach/dblog}' \
--join=<IP1>:26257,<IP2>:26257,<IP3>:26257 \
--cache=1024000000 --max-sql-memory=1024000000   --background

-------------------------------------------------------------------------------------
when i restart all the 3 cockroachdb processes,  then access the table, the problem is gone. 
wait about 24 hours,  the problem will show up again.

**Comment by yuzefovich** [comment] 2022-07-07 14:41
This sounds like a memory accounting leak we've been trying to find (#77465), but so far we have been unable to reproduce it. Is it possible for you to share the reproduction steps (possibly sharing the backup of the database and the workload via secure methods)? I understand if not.

**Comment by carr123** [comment] 2022-07-12 01:06
@yuzefovich we have lots of micro services accessing CRDB,  lots of business data, i have no rights to reveal those data.
recently, i find high memory usage does not always leads to "memory budget exceeded" error.
my crdb cluster has successfully run for 4 days since last restart.
i have just upgraded to the latest version v22.1.3,  and will keep an eye on that issue.

**Comment by yuzefovich** [comment] 2022-07-12 01:15
That makes sense. Closing this issue as a dup of #77465.

**Closed by yuzefovich** 2022-07-12 01:15 UTC
Labels: C-bug, C-performance, O-community, A-sql-memmon

**Comment by yuzefovich** [comment] 2022-07-13 00:27
@carr123 I think we're likely to have identified the bug, and the relevant backports should land on [22.1](#84089) and [21.2](#84325) branches soon.

**Comment by carr123** [comment] 2022-07-13 00:46
@yuzefovich very glad to hear that.  looking forward to it.
