### ISSUE TITLE
Replica stuck in under-replicated state because it didn't know it had been removed from its range

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#60259] opened 2021-02-09 20:51 UTC
**Describe the problem**

After a series of rebalances, a replica of a range got stuck thinking that it was under-replicated when really it had been removed from the range. The range wasn't under-replicated at all -- it had the 5 replicas that it was configured to have, but it also had this sixth replica that was stuck thinking the range was under-replicated.

I've seen this happen a few times recently. It isn't that big of a deal since you can get the replica unstuck by restarting the process it's on (or presumably the process that holds the lease for the range), but it does make it difficult to have alerts that let you know when a range is under-replicated for an extended period of time.

See the screenshots below from the range debug page for more specifics on a couple of occurrences.

**Environment:**
 - CockroachDB version [e.g. 2.0.x]: v20.2.3

**Additional data / screenshots**

Sorry for their huge size, but that's better than not having them or not being able to read them.

Example 1:
<img src="https://user-images.githubusercontent.com/7085343/107425646-d85d1a00-6ae4-11eb-841a-0f59aa301332.png" width="400" height="800" />

Example 2:
<img src="https://user-images.githubusercontent.com/7085343/107425650-d8f5b080-6ae4-11eb-815a-3b646873d3ed.png" width="400" height="800" />

**Comment by a-robinson** [comment] 2021-02-10 03:58
My understanding is that the general sequence of events here is
1. A replica gets removed from the range and fails to learn about that fact
2. One or more of the (non-leaseholder) nodes that it thinks are part of the range stop running
3. The node that was leaseholder at the time of step 1 keeps the same node liveness epoch live from the time of step 1 onwards.

This can also cause the `ranges_unavailable` metric to get incremented if enough of the old nodes go down before the old replica realizes it's no longer part of the range.

**Comment by aayushshah15** [comment] 2021-04-02 05:35
Hey Alex, the sequence of events you mentioned make sense and seem like they could result in something like this. The replica designated as the one responsible for keeping track of whether the range is under / over-replicated does so based on its applied `ReplicaState`, which can be stale in the scenario you’re describing. 

I’m curious about how often you’ve seen this play out. I ask because (as you might already know) replicas _should_ eagerly destroy themselves when they apply the raft entry that removed them. Another thing I’m curious about is, have you noticed a range stay in this state indefinitely (in particular, over 10 days)? Lastly, have you tried manually enqueuing such a range into the replicaGC queue?

**Comment by a-robinson** [comment] 2021-04-02 14:06
> I’m curious about how often you’ve seen this play out.

Quite often, on at least 15-20 different machines across recent months.

In particular, the trigger for it is a less-than-ideal rolling upgrade process in which for each machine we decommission the cockroach node prior to upgrading/rebooting the machine and then create a new cockroach node on it after the upgrade is complete.

We never saw this problem on v20.1.x releases because in those versions we didn't have to actually create a new cockroach node -- we could just `recommission` the existing one. But on v20.2.x recommissioning no longer works for this purpose so we've stumbled up on this new scenario.

> have you noticed a range stay in this state indefinitely (in particular, over 10 days)?

I've never let it sit like this for more than a day or two without going in and resolving it by restarting the process, so unfortunately I don't know.

> have you tried manually enqueuing such a range into the replicaGC queue?

I have not. That's a good idea though, I'd be happy to try it next time.

**Comment by ajwerner** [comment] 2021-04-02 14:13
I wonder if https://github.com/cockroachdb/cockroach/pull/61977 may be related. A range report for the range would be handy. 

@erikgrinaker filed https://github.com/cockroachdb/cockroach/issues/62075 which, on some level, is likely the problem. I'm not sure whether we think we have something that should cover whatever case is happening here and doesn't or whether it's a gap, but a better heuristic would likely cover over both.

**Comment by a-robinson** [comment] 2021-04-02 14:19
In addition to the two screenshots in the original post (which are admittedly large and clunky), here are the html contents from a different range's status page that this happened to. I had to add the `.txt` suffix to get github to let me upload them, but if you strip it they should be viewable as plain html in your browser.

[2021-03-05-lease-history.html.txt](https://github.com/cockroachdb/cockroach/files/6249928/2021-03-05-lease-history.html.txt)
[2021-03-05-range-info.html.txt](https://github.com/cockroachdb/cockroach/files/6249929/2021-03-05-range-info.html.txt)
[2021-03-05-range-log.html.txt](https://github.com/cockroachdb/cockroach/files/6249927/2021-03-05-range-log.html.txt)

**Comment by a-robinson** [comment] 2021-04-02 14:26
I'm not sure how related this is to those linked issues, since in all the instances of it that I've seen, the range's leaseholder/leader remains unchanged and healthy at the same liveness epoch. The problem is that the follower complaining about underreplication is behind the leader in terms of its raft index and lease applied index, and it persistently isn't catching up due to quiescence.

**Comment by ajwerner** [comment] 2021-04-02 14:49
Right, and that's permitted because the replica is no longer in the range. If the replica were deemed suspect by the referenced heuristics, then we'd go scan the range descriptor to determine whether we need to run replica gc. That's my understanding of the connection.

**Comment by a-robinson** [comment] 2021-04-02 14:52
> Right, and that's permitted because the replica is no longer in the range.

Oh of course, I forgot that part of the issue. You're right.

**Comment by erikgrinaker** [comment] 2021-04-05 19:31
I've been poking at this a little bit. Normally the follower would stop receiving heartbeats and convert itself to a candidate, in which case the GC heuristics would consider it suspect and immediately GC it. However, since this Raft group is quiesced there are no heartbeats.

I think we should start by figuring out why the stale replica isn't picking up on the range descriptor change and removing itself in the first place. If that fails, we could look into the quiescence heuristics, i.e. the stale replica or leader should notice something is up and either wake up or prevent quiescing. Adding heuristics for this in the replica GC queue would, to some extent, just mask an issue in the Raft logic.

We could also consider reducing the inactivity timeout for the GC replica descriptor check from 10 days to 1 day, or even ~hours. This was originally introduced way back in #1908, and seems somewhat arbitrary -- I believe the operation is cheap enough that we could do it more often.

**Comment by ajwerner** [comment] 2021-04-05 20:34
> I think we should start by figuring out why the stale replica isn't picking up on the range descriptor change and removing itself in the first place.

I suspect this is expected. As soon as the other replicas commit the fact that the replica is no longer in the range, they will stop talking to it. If that replica were to reach out to any of the other nodes then it would get a `ReplicaTooOld` error and destroy itself. If, for whatever reason, the replica was partitioned or the node was down while the removal committed then I'd expect it to never learn about its removal. 

>We could also consider reducing the inactivity timeout for the GC replica descriptor check from 10 days to 1 day, or even ~hours. This was originally introduced way back in #1908, and seems somewhat arbitrary -- I believe the operation is cheap enough that we could do it more often.

https://twitter.com/JordanALewis/status/1246134064110866434

**Comment by erikgrinaker** [comment] 2021-04-20 11:20
I haven't been able to reproduce this state yet. I start a cluster with 3 nodes and a 1 GB table with 3 replicas. I then add a new node to the cluster and decommission an old node, and repeat this process a bunch of times. Does that roughly correspond to your scenario @a-robinson?

I've also tried taking down or pausing nodes, rebalancing the range, and then restarting/resuming the node (making sure the range is quiesced first), but in all cases this ended up with the stale replica being GCed reasonably fast. It's a bit more involved to actually set up a network partition, but I'll see if I can write an integration test for this scenario.

In any case, I'll review the GC heuristics and add some conditions that may cover this scenario.

**Comment by a-robinson** [comment] 2021-04-20 19:42
> I haven't been able to reproduce this state yet. I start a cluster with 5 nodes and a 1 GB table with 3 replicas. I then add a new node to the cluster and decommission an old node, and repeat this process a bunch of times. Does that roughly correspond to your scenario @a-robinson?

The exact order of events is something more like: decommission a node, wait a while, create a new node with the same address as the previously decommissioned one. Slowly progress through all the nodes, doing this to each, with sometimes a few being down at once.

**Comment by erikgrinaker** [comment] 2021-05-12 15:21
Still haven't been able to reproduce this, but I submitted #65062 which should cause these replicas to be GCed in a timely manner. It doesn't handle the case where a quiesced replica fails to notice that it's been removed and then just keeps hanging around as a fifth wheel (it's unclear how we would notice this without preventing quiescence in the first place and having the heartbeats handle it), but as soon as it thinks it's underreplicated and triggers this alert it'll be GCed.

I think this, in combination with the other improvements we've made (reducing the general GC check interval from 10 days to 12 hours and using the leaseholder for range-level metrics), should sufficiently address this issue. We should probably let it bake on `master` for a bit before backporting though.

**Comment by a-robinson** [comment] 2021-05-12 15:26
Thanks @erikgrinaker!

**Closed** 2021-05-13 21:35 UTC
Labels: A-kv-replication, C-bug, O-community

**Comment by a-robinson** [comment] 2021-05-14 14:00
@erikgrinaker I have another repro and there's a decent chance of hitting more over the coming days. Is there anything you'd like me to check on the current repro or to set up in advance of the other possible ones, or are you happy with where this ended up?

**Comment by erikgrinaker** [comment] 2021-05-14 14:18
The thing I find odd about this is that the replicas don't pick up on the range descriptor change and remove themselves immediately. As discussed above, the most likely explanation is that the replica is quiesced and partitioned away from the rest of the cluster while the range descriptor is being changed. However, it seems unlikely that this would happen as often as you see. Is there anything about your environment or any hints in e.g. logs or metrics that might explain why the replicas don't pick up on this?

After the fact I think we've done all we can to address this, but it'd be great if we could figure out why this is happening in the first place. However, I've spent a couple of days trying to reproduce this without any luck, so I'd appreciate any help in trying to track this down.

**Comment by a-robinson** [comment] 2021-05-14 15:48
Yeah, I totally get it. I was going to say the same about having spent enough time on it, but I did find what's likely the missing piece in the logs: the replicas that later complain about being underreplicated are being removed while the node is partitioned away from the leaseholder / the rest of the cluster.

The range that's currently in this state has a couple of replicas from the same locality both complaining about being underreplicated, and in both cases they were removed from the range when the nodes were unreachable (and presumably considered dead). They didn't complain about the underreplication until later -- when the nodes that they thought were the other members of the range got decommissioned from the cluster -- but the network partition was what allowed them to be removed from the range without picking up on the range descriptor change.

**Comment by erikgrinaker** [comment] 2021-05-14 16:00
Ah, that explains it -- great to have confirmation, thanks for looking into it!

This is sort of an expected downside of the current quiescence implementation. We've been considering whether quiescence is really necessary now that we've bumped the default range sizes to 512 MB. I suppose we could also consider unquiescing ranges whenever there are liveness changes to relevant nodes. Let me check with the rest of the team how we'd like to proceed here.

**Comment by erikgrinaker** [comment] 2021-05-14 16:47
@ajwerner suggested checking the stale replica's lease epoch against the liveness epoch, which should allow us to GC these replicas once the partition heals. Opened #65202 for this.
