### ISSUE TITLE
ui: Problem range pages linked from `/#/reports/problemranges` always 404

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#49653] opened 2020-05-28 16:44 UTC
**Describe the problem**

The "Problem Ranges" debug page (http://localhost:8080/#/reports/problemranges) links to a report page for each range that has some sort of problem (e.g. http://localhost:8080/#/reports/reports/range/1 ). However, these links all bring me to a "Page Not Found" error page whenever I try to click on them.

**To Reproduce**

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Start a cockroach cluster
2. Load the admin UI
3. Click on the "Advanced Debug" page
4. Click on the "Problem Ranges" page (`#/reports/problemranges`)
5. Click on any of the problematic ranges (`/#/reports/reports/range/1`)

**Expected behavior**

I expect links in the admin UI to take me to functional pages :)

**Additional data / screenshots**

The Problem Ranges page:

<img width="1400" alt="Screen Shot 2020-05-28 at 11 42 47 AM" src="https://user-images.githubusercontent.com/7085343/83169306-76848d80-a0d8-11ea-9600-f63eeef3d526.png">

The Page Not Found error:

<img width="686" alt="Screen Shot 2020-05-28 at 11 42 52 AM" src="https://user-images.githubusercontent.com/7085343/83169312-7a181480-a0d8-11ea-8c52-86e463238697.png">

**Environment:**
 - CockroachDB version v20.1.0

**Comment by dhartunian** [comment] 2020-05-28 16:51
Thanks for reporting @a-robinson! Appreciate the detail. This appears to be a duplicate of an issue that was recently fixed for 20.1.1 here: https://github.com/cockroachdb/cockroach/issues/48559

**Comment by dhartunian** [comment] 2020-05-28 17:26
Closing this but feel free to re-open if you don't think it's a duplicate. Thanks!

**Closed by dhartunian** 2020-05-28 17:26 UTC
Labels: C-bug, O-community, X-blathers-triaged

**Comment by a-robinson** [comment] 2020-05-28 19:42
Yup, that's great, thanks. Sorry for failing to find the existing issue!
