### ISSUE TITLE
circleci: failed tests (13976): TestBaseQueuePurgatory 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4946] opened 2016-03-07 18:22 UTC
The following test appears to have failed:

[#13976](https://circleci.com/gh/cockroachdb/cockroach/13976):

```
W160307 18:21:17.881860 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160307 18:21:17.884105 storage/queue.go:264  [test] range=2 [/Table/11-/Max): split needed; not adding
--- PASS: TestAcceptsUnsplitRanges (0.02s)
=== RUN   TestBaseQueuePurgatory
W160307 18:21:17.894614 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
--- FAIL: TestBaseQueuePurgatory (15.11s)
	queue_test.go:501: expected purgatory size of 10; got 9
	<autogenerated>:32: storage/queue_test.go:517: condition failed to evaluate within 15s: storage/queue_test.go:514: expected 20 processed replicas; got 19
=== RUN   TestGetTruncatableIndexes
W160307 18:21:33.007767 gossip/gossip.go:921  not connected to cluster; use --join to specify a connected node
I160307 18:21:33.010275 raft/raft.go:459  [group 1] 1 became follower at term 5
I160307 18:21:33.010478 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160307 18:21:33.010583 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160307 18:21:33.010676 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160307 18:21:33.010758 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
I160307 18:21:33.010859 raft/raft.go:500  [group 1] 1 became leader at term 6
--
I160307 18:21:41.546806 raft/raft.go:779  [group 1] 2 [commit: 15] restored snapshot [index: 15, term: 6]
I160307 18:21:41.975042 raft/raft.go:459  [group 1] 1 became follower at term 6
I160307 18:21:41.975200 raft/raft.go:235  [group 1] newRaft 1 [peers: [1,2], term: 6, commit: 15, applied: 15, lastindex: 15, lastterm: 6]
I160307 18:21:41.975593 storage/replica.go:1742  [node=1,store=1,range=1] gossiping system config from store 1, range 1, hash 91100e0451ac1aab78723f763fac84cccdd4aea5
I160307 18:21:41.982862 storage/replica.go:1683  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
panic: gossip infostore's NodeID is 0

goroutine 3797 [running]:
panic(0x18d5be0, 0xc8204c0140)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820168080, 0xc8204559e8, 0x10, 0x10, 0x0, 0x2f)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0xb4
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc8201ca280, 0x1c8f7b0, 0xa, 0xc8204559e8, 0x10, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:524 +0x12b
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc8201961a0, 0x35a3640)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1685 +0xa01
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc8200c8a00, 0xc82027df20)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:801 +0x3c3
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:745 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820343b90, 0xc8202f07e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	25.311s
=== RUN   TestBatchBasics
I160307 18:21:56.253959 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.03s)
=== RUN   TestBatchGet
I160307 18:21:56.289809 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160307 18:21:56.298409 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.02s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-03-07 18:34
Dupe of #4815

**Closed by bdarnell** 2016-03-07 18:34 UTC
Labels: test-failure
