### ISSUE TITLE
ui: inconsistent reporting of database sizes

### ISSUE THREAD

**Issue by couchand** [cockroachdb/cockroach#18667] opened 2017-09-21 15:37 UTC
Split out of #18657.

> The database size in the admin UI might be off. For one table it shows me a size of 9.3GiB while the whole cluster in the overview shows a usage of 3.6GiB which also matches the 1.2GiB size of the cockroach-data directory on each node.

**Comment by a-robinson** [comment] 2017-09-21 15:42
There was also recently https://forum.cockroachlabs.com/t/needs-clarification-of-bytes-numbers-in-node-stats/949/3

**Comment by tschottdorf** [comment] 2017-12-04 22:24
Quick update from what @vilterp told me (and which I checked as well): we display `val_bytes + sys_bytes`. In particular we leave out `key_bytes`. Suppose the idea is that prefix compression makes a huge difference for `key_bytes` and that we'd get a better approximation of disk size by omitting it. I'm fairly certain it's futile to unite the two, though. There's just no way to have a simple formula that accounts for two of the key differences, RocksDB compression and write amplification.

I think it's worth taking a look at whether RocksDB has any facilities for (quickly) getting an approximation of the on-disk size of a key range. In the absence of that, the right course of action seems to be more principled about documenting what these stats actually count (and in particular, what they don't account for).

**Comment by petermattis** [comment] 2017-12-04 22:38
```
  // For each i in [0,n-1], store in "sizes[i]", the approximate
  // file system space used by keys in "[range[i].start .. range[i].limit)".
  //
  // Note that the returned sizes measure file system space usage, so
  // if the user data compresses by a factor of ten, the returned
  // sizes will be one-tenth the size of the corresponding user data size.
  //
  // If include_flags defines whether the returned size should include
  // the recently written data in the mem-tables (if
  // the mem-table type supports it), data serialized to disk, or both.
  // include_flags should be of type DB::SizeApproximationFlags
  virtual void GetApproximateSizes(ColumnFamilyHandle* column_family,
                                   const Range* range, int n, uint64_t* sizes,
                                   uint8_t include_flags
                                   = INCLUDE_FILES) = 0;
```

I'm pretty sure this uses only in-memory sstable information.

**Comment by tschottdorf** [comment] 2017-12-04 22:45
That sounds pretty good. Core starter project after we've done some vetting that this thing actually does what's on the tin?

**Comment by vilterp** [comment] 2017-12-07 00:09
We're seeing logical database size (val_bytes + sys_bytes for each table) sometimes be 2-4x of reported disk usage. Does that seem like a reasonable compression factor for RocksDB? (Examples: Rubrik's test db in the issue that references this, and the PM cluster, which has a dump of the reg cluster)

**Comment by tschottdorf** [comment] 2017-12-07 02:18
@vilterp just to make sure, that user you mention is seeing the opposite (at least in one instance): logical 8.8GB, on-disk 14GB. This would happen with a schema that has long primary keys (because the key isn't in `val_bytes`). I haven't confirmed that's the case there.

**Comment by tschottdorf** [comment] 2017-12-07 22:06
btw, looking at `MVCCStats`, it's odd that we chose to report `val_bytes + sys_bytes`. I think it should just be


```
	// key_bytes is the number of bytes stored in all non-system
	// keys, including live, meta, old, and deleted keys.
	// Only meta keys really account for the "full" key; value
	// keys only for the timestamp suffix.
	KeyBytes int64 `protobuf:"fixed64,6,opt,name=key_bytes,json=keyBytes" json:"key_bytes"`
```

plus

```
	// value_bytes is the number of bytes in all non-system version
	// values, including meta values.
	ValBytes int64 `protobuf:"fixed64,8,opt,name=val_bytes,json=valBytes" json:"val_bytes"`
```

plus

```
	// sys_bytes is the number of bytes stored in system-local kv-pairs.
	// This tracks the same quantity as (key_bytes + val_bytes), but
	// for system-local metadata keys (which aren't counted in either
	// key_bytes or val_bytes). Each of the keys falling into this group
	// is documented in keys/constants.go under the localPrefix constant
	// and is prefixed by either LocalRangeIDPrefix or LocalRangePrefix.
	SysBytes int64 `protobuf:"fixed64,12,opt,name=sys_bytes,json=sysBytes" json:"sys_bytes"`
```

**Comment by dianasaur323** [comment] 2017-12-07 22:07
@vilterp based on all the comments that have been flying around, it seems like we should just sit down, hash out the different use cases we want to meet with these different sizes, and then be opinionated and clear about what we are showing. i'll find some time to sync up with you about it sometime next week.

**Comment by vilterp** [comment] 2017-12-07 23:31
@tschottdorf yeah, `KeyByes + ValBytes + SysBytes` makes sense. And yes, we've seen clusters now where logical is smaller than disk, and some where it's much bigger. Adding `KeySize` would make the "logical < disk" ones closer, which I guess just leaves compression as the cause of the "logical > disk" ones?

@dianasaur323 sure, we can hash it out and document it.

**Comment by tschottdorf** [comment] 2017-12-18 17:03
Closing this, as we're using RocksDBs GetApproximateSizes now (#20627).

**Closed by tschottdorf** 2017-12-18 17:03 UTC
Labels: bug, ux-surprise
