### ISSUE TITLE
ERROR: internal error: building declarative schema change targets for ALTER TABLE: failed to find column

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#99561] opened 2023-03-25 07:22 UTC
**Describe the problem**

```
root@localhost:26257/encoderv2> alter table tasks drop column completed;
ERROR: internal error: building declarative schema change targets for ALTER TABLE: failed to find column
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:450: handleDropColumnCreateNewPrimaryIndex()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:432: handleDropColumnPrimaryIndexes()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:284: dropColumn()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_drop_column.go:43: alterTableDropColumn()
GOROOT/src/reflect/value.go:584: call()
GOROOT/src/reflect/value.go:368: Call()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table.go:174: AlterTable()
GOROOT/src/reflect/value.go:584: call()
GOROOT/src/reflect/value.go:368: Call()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/process.go:169: Process()
github.com/cockroachdb/cockroach/pkg/sql/schemachanger/scbuild/build.go:62: Build()
github.com/cockroachdb/cockroach/pkg/sql/schema_change_plan_node.go:80: SchemaChange()
github.com/cockroachdb/cockroach/pkg/sql/opaque.go:56: buildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/opaque.go:70: tryBuildOpaque()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:404: buildStmt()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:252: buildStmtAtRoot()
github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:226: Build()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:561: buildExecMemo()
github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:232: makeOptimizerPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1474: makeExecPlan()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1086: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:696: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:131: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2428: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:130: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1972: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1976: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1898: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:857: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:728: func1()
GOROOT/src/runtime/asm_amd64.s:1594: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
```

Hi cockroachdb,

It started when I got a wierd error where cockroachdb state:

```
[2023-03-24 19:27:10] production.ERROR: SQLSTATE[23505]: Unique violation: 7 ERROR:  duplicate key value violates unique constraint \"tasks_completed_index\"
DETAIL:  Key (completed)=(true) already exists.
```

This is relevant schema:
```sql
CREATE TABLE public.tasks (
    id UUID NOT NULL,
    ...
    completed BOOL NOT NULL DEFAULT false,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    ...
    UNIQUE INDEX tasks_id_key (id ASC),
    INDEX tasks_completed_index (completed ASC),
);
```

As you can see, `tasks_completed_index` is a non-unique index... After pulling most of my hair, I think something is wrong with the column `completed`, so I decide to drop all index related to `completed` column, then drop the `completed` column, then re-add the column and then re-add index. Luckily, when I attempt drop column, I got this error message error above.

**To Reproduce**
I try to reproduce it with newly install cockroachdb before (no luck), the light bulbs happen to me when I think the column on prod have gone corruption, I think I still have backup of this (if you want the back up to try drop column for yourself).

**Environment:**
 - CockroachDB version: `CockroachDB CCL v22.2.6 (x86_64-pc-linux-gnu, built 2023/03/03 19:31:13, go1.19.4)`
 - Server OS: `Ubuntu 22.04`
 - Client app: `cockroach sql`

I've try to get rid of `tasks_completed_index` and recreate index before (without drop `completed` column), it does solve problem for a brief moment but eventually I'll still have that error (unique index violation on non-unique column), only when I try get rid of the column itself, it manifest itself in this way.

Jira issue: CRDB-25934
Epic CRDB-28665

**Comment by kocoten1992** [comment] 2023-03-26 16:21
So... I _think_ I've fix this problem, I _think_ there is a data corruption, the way I fix it is:

1. create a new table using syntax (`like table including all`).
2. give permission new table to relevant user.
3. recreate constraint on new table.
4. alter constraint on foreign table to new table.
5. rename current table to old table and rename new table to current table.

I'd leave this issue open, if you think this issue is worth investigate more... otherwise this can be close.

**Comment by kocoten1992** [comment] 2023-03-27 13:38
Update:

Turn out I only fix the issue cannot **drop column** (now column can be drop properly), but that have nothing to do with what I really want - that is why cockroachdb said **unique value on non-unique index**, that problem I still have :disappointed:

**Comment by kocoten1992** [comment] 2023-03-27 14:40
Hi @Xiang-Gu , here is the info https://gist.github.com/kocoten1992/c154b6913fa635a2c14074f3c4893988

Yes, I've just insert a few records to ensure that `completed` is non-unique, also the query that trigger this error is quite long (over 2 mils characters), but I've ensure that on a newly cluster it can handle 2 mils chars just fine (I've try to reproduce this issue - so now I don't really know why).

**Comment by Xiang-Gu** [comment] 2023-03-28 21:07
I looked at those outputs and they all look fine. What will be the best way for me to reproduce the error:
 1.  the `DROP COLUMN completed` error 
 2.  INSERT results in duplicate value on `completed` error

For 1, you mentioned you have a backup that we can use. Can I have access to it?
For 2, can you tell me how to reproduce it with that 2-million-characs long queries? It seems it's also hard for you to reproduce 2, so maybe it's best for me to start with attempting to reproduce 1.

Finally, have you checked cockroach logs? Did you find anything suspicious or unexpected, like errors, stack traces, etc.?

**Comment by Xiang-Gu** [comment] 2023-03-28 21:49
A side question: Is this the same scenario where you hit and filed [this issue](https://github.com/cockroachdb/cockroach/issues/95720)? We never got the chance to figure out that one (cannot reproduce), and I'm curious whether it's the same root cause as this one underneath.

**Comment by kocoten1992** [comment] 2023-03-29 00:57
@Xiang-Gu , thank you so much for reaching out, and you are right:
`1.` is fairly easy to reproduce.
`2.` is harder - but I'll do my best effort to ensure you can reproduce it (I'm currently writing a `prepare/execute` sql - I hope it work).

Where should I send you the detail? and btw it may take a few days to reproduce `2.`

**Comment by Xiang-Gu** [comment] 2023-03-29 14:15
So let me start poking around with issue 1) first. You can send me relevant information via SendSafely https://upload.cockroachlabs.com/u/xiang and I will take a look as soon as I get a chance.

**Comment by kocoten1992** [comment] 2023-03-29 14:42
I've send info for `1.`, that is database **before any changes**. (`2.` will be send later - I'm working on it).

**Comment by Xiang-Gu** [comment] 2023-03-29 18:39
Okay, I received your info on 1) and identified the cause. The thing to blame is the `tasks_id_key` index. It is one of the unique secondary index but somehow it has a PrimaryIndexEncoding and that has confused the schema change code. 

You can run the following query to change it to a secondaryIndexEncoding with the following query (I've tested myself on your backup and it allowed me to successfully drop the column afterward):
```
select crdb_internal.unsafe_upsert_descriptor(112,
	crdb_internal.json_to_pb('cockroach.sql.sqlbase.Descriptor',
		json_remove_path(
			jsonb_set(
				jsonb_set(
					crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor), ARRAY['table', 'indexes', '0', 'encodingType'], 
					'0'
				),
				ARRAY['table', 'version'],
				((crdb_internal.pb_to_json('cockroach.sql.sqlbase.Descriptor', descriptor)->'table'->>'version')::int + 1)::string::jsonb
			),
			ARRAY['table', 'modificationTime']
		)
	)
)
from system.descriptor where id = 112;
```

Do you have any recollection of how this index (`tasks_id_key`) was created in the first place? I am curious to understand why your table descriptor end up in this corrupted state.

**Comment by ajwerner** [comment] 2023-03-29 18:43
I think this is caused by the issue explained in https://github.com/cockroachdb/cockroach/issues/97526. Can you say more about how this affects the declarative schema changer?

**Comment by Xiang-Gu** [comment] 2023-03-29 18:50
yes, this [line](https://github.com/cockroachdb/cockroach/blob/release-22.2/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/helpers.go#L391) will mistakenly retrieve that secondary unique index and think that is our primary index. It only has a `id` as key column and no stored columns, and later the code errored with "cannot find column `completed`".
In other words, we used `scpb.FindPrimaryIndex` expecting there is only one `scpb.PrimaryIndex` but in this case there are two.

**Comment by ajwerner** [comment] 2023-03-29 18:53
Ah, cool. I think the answer should be to make a post-deserialization change to change the encoding version for secondary indexes which are marked as primary index encoded and there are no mutations. I think it'll fix this and also fix other problems. Can you take that?

**Comment by Xiang-Gu** [comment] 2023-03-29 19:13
yes, of course! So we are going to solve https://github.com/cockroachdb/cockroach/issues/97526 via a post-deserialization instead of the relax-validation solution or the migration solution as suggested there, right?

**Comment by ajwerner** [comment] 2023-03-29 19:23
I think both. We can backport the post-deserialization change, and we can have the migration work by finding descriptors changed by that post deserialization change. WDYT?

**Comment by Xiang-Gu** [comment] 2023-03-29 19:46
In summary, if a user has a corrupted secondary index, she/he can encounter the following problems:
a). upgrading from 22.1 to 22.2 will fail to finalize because the stricter validation prevents it;
b). If somehow a) is not experienced and the user is running 22.2 already, they can still encounter issues during schema changes (e.g. this issue)

To prevent those two problems and ensure the corruption is fixed, can we
1). add a version gate on the stricter validation to 22.2 (to mitigate problem a);
2). add a post-deserialization change to 22.2 (to mitigate problem b);
3). add a migration (i.e. cluster version 22.2-xxx) that actually fixes the corruption in storage before upgrading to 23.1; 

Does this sound right?

**Comment by kocoten1992** [comment] 2023-03-29 20:03
> 3). add a migration (i.e. cluster version 22.2-xxx) that actually fixes the corruption in storage before upgrading to 23.1;

Hello, may I ask what if user is lazy and skip version (asking for a friend)? I mean right now is v22.2.6, and they jump straight into 23.1?

In the past, I've use a software called `gitlab`, they won't let you skip jump any version and have to install each increased version in order to upgrade (I think I've been skipping a lot of minor version in cockroachdb since 19.2).

**Comment by ajwerner** [comment] 2023-03-29 20:12
23.1 is the major release after 22.2. You cannot skip major versions when upgrading cockroach, but you can skip patch version as you please. No need to go through patch version.

**Comment by kocoten1992** [comment] 2023-03-29 20:22
One last question, if a user have a backup on 22.2 (in broken state like me), then they restore it on 23.1, would it still go through that fix code path? (I'm sorry, I'm not familiar with cockroachdb internal at all).

**Comment by ajwerner** [comment] 2023-03-29 20:24
Yes, you are allowed to restore backups from the previous major version into the current major version (but not more than one major version). Our migrations framework will apply the relevant changes at restore time if there are any.

**Comment by kocoten1992** [comment] 2023-03-30 10:25
Hi @Xiang-Gu , I've tell you about the third problem I have (duplicated primary id), I not sure if this is what I see when doing (pressure make me forget everything), but I just check back one of the backup, I found this:

```sql
root@localhost:26257/encoderv2> select id, type from tasks where type = 'sceneDetection';               
                   id                  |      type
---------------------------------------+-----------------
  a4a4ce80-6717-4378-9d03-336238c3a53c | sceneDetection
  a4a4ce80-6717-4378-9d03-336238c3a53c | sceneDetection
(2 rows)


Time: 26ms total (execution 26ms / network 0ms)

root@localhost:26257/encoderv2> SELECT id, COUNT(*) as count FROM tasks GROUP BY id HAVING COUNT(*) > 1;
  id | count
-----+--------
(0 rows)


Time: 39ms total (execution 38ms / network 0ms)

root@localhost:26257/encoderv2> select id from tasks where id = 'a4a4ce80-6717-4378-9d03-336238c3a53c'; 
                   id
----------------------------------------
  a4a4ce80-6717-4378-9d03-336238c3a53c
(1 row)


Time: 2ms total (execution 2ms / network 0ms)


```

I do have `set cluster setting sql.multiple_modifications_of_table.enabled = true;`, but not sure that related.

This is database after I copy old table to new table (I could not find anything before any changes - but If memory don't betray me, think it is there the whole time).

I've send info about this case via SendSafely.

**Comment by Xiang-Gu** [comment] 2023-03-30 15:29
Your message was received. I have a few items on my plate right now, including fixing the incorrect indexEncodingType as we discovered above. I will not be able to get to this new duplicate primary key issue right now. If this is high severity, I can ask my colleagues to see if they have time to take a look at this. Otherwise, I will get back to this as soon as I finish my other work at hand.

After a quick glance at this primary key duplication issue though, I suspect that some corruption in the descriptor caused the incorrect output of the first query. Very quickly, can you try the following query to print out all kv-pairs corresponding to this `id`:
```
SELECT * FROM 
  (SELECT crdb_internal.pretty_key(key, 0) AS pretty_key
   FROM crdb_internal.scan(crdb_internal.table_span('tasks'::REGCLASS::INT)) as t(key, val)) 
WHERE pretty_key LIKE '%a4a4ce80-6717-4378-9d03-336238c3a53c%';
```
We expect to see one kv-pair per column family, so in your case (I think) with one column family, we expect to see only one row in the output. If that's the case, we know there is only one row for this key; it could just be the corruption in the descriptor that has caused the optimizer some "illusion" in the output (which needs to be fixed, but later).

**Comment by kocoten1992** [comment] 2023-03-30 15:49
Ahh, no issue here is urgent (I can side step most of them) (and really appreciated you have spend time for this).

Will send the last issue about uniqueness on non-unique index query when I crafted it.

**Comment by kocoten1992** [comment] 2023-04-02 10:25
The issue with `duplicated primary id` or `uniqueness on non-unique index` probably caused by `set cluster setting sql.multiple_modifications_of_table.enabled = true;`. I've extensive test and confirm that.

So..there is not really an issue any more. The issue you are currently solving are the only issue. Good luck with that :100:

**Closed** 2023-07-07 19:02 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-foundations, A-schema-catalog, C-technical-advisory, branch-release-21.1, branch-release-20.2, v23.1.9
