### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestShowCreateTable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6271] opened 2016-04-24 11:33 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/fbb1243f55df4aa02f59c57d4133ec85460748e7

Stress build found a failed test:

```
=== RUN   TestShowCreateTable
W160424 06:47:11.877476 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160424 06:47:11.878263 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160424 06:47:11.879223 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160424 06:47:11.879374 server/node.go:359  store store=0:0 ([]=) not bootstrapped
I160424 06:47:11.880607 storage/replica_command.go:1439  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m12.88037373s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.880546543 +0000 UTC]
I160424 06:47:11.881318 server/node.go:309  **** cluster {35b9fc94-0891-42a1-9663-4d9da73ca632} has been created
I160424 06:47:11.881337 server/node.go:310  **** add additional nodes by specifying --join=127.0.0.1:34392
W160424 06:47:11.881349 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160424 06:47:11.881961 server/node.go:372  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8106016768 RangeCount:0}
I160424 06:47:11.882001 server/node.go:284  node ID 1 initialized
I160424 06:47:11.882090 storage/stores.go:287  read 0 node addresses from persistent storage
I160424 06:47:11.882175 server/node.go:493  connecting to gossip network to verify cluster ID...
I160424 06:47:11.882398 server/node.go:514  node connected via gossip and verified as part of cluster {"35b9fc94-0891-42a1-9663-4d9da73ca632"}
I160424 06:47:11.882431 server/node.go:337  [node=1] Started node with [[]=] engine(s) and attributes []
I160424 06:47:11.882463 server/server.go:366  starting https server at 127.0.0.1:40792
I160424 06:47:11.882480 server/server.go:367  starting grpc/postgres server at 127.0.0.1:34392
I160424 06:47:11.882545 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160424 06:47:11.883293 storage/replica_command.go:1901  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160424 06:47:11.884096 server/updates.go:147  No previous updates check time.
I160424 06:47:11.906320 storage/replica_command.go:1439  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m12.981558495s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.906293165 +0000 UTC]
I160424 06:47:11.906708 storage/replica_command.go:1901  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160424 06:47:11.910961 storage/replica_command.go:1439  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m12.981558495s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.91092034 +0000 UTC]
I160424 06:47:11.911823 storage/replica_command.go:1901  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160424 06:47:11.917740 storage/replica_command.go:1439  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m12.981558495s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.917697538 +0000 UTC]
I160424 06:47:11.917868 storage/replica_command.go:1901  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160424 06:47:11.981124 storage/replica_command.go:1439  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m13.030715921s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.98107629 +0000 UTC]
I160424 06:47:11.981267 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160424 06:47:11.981597 storage/replica_command.go:1901  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160424 06:47:11.990314 storage/replica_command.go:1439  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m13.040078143s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:11.990270968 +0000 UTC]
I160424 06:47:11.991224 storage/split_queue.go:100  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160424 06:47:11.991629 storage/replica_command.go:1901  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160424 06:47:12.002005 storage/replica_command.go:1439  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405966h47m13.051803975s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-24 06:47:12.001965102 +0000 UTC]
I160424 06:47:12.016784 storage/split_queue.go:100  splitting range=7 [/Table/51-/Max) at keys [/Table/52/0]
I160424 06:47:12.016947 storage/replica_command.go:1901  initiating a split of range=7 [/Table/51-/Max) at key /Table/52
I160424 06:47:12.040692 stopper.go:352  draining; tasks left:
2      server/node.go:742
1      storage/queue.go:383
1      kv/txn_coord_sender.go:895
I160424 06:47:12.040748 stopper.go:352  draining; tasks left:
2      server/node.go:742
1      storage/queue.go:383
E160424 06:47:12.044028 client/txn.go:391  failure aborting transaction: writing transaction timed out or ran on multiple coordinators; abort caused by: node unavailable; try another peer
E160424 06:47:12.044155 storage/queue.go:446  [split] range=7 [/Table/51-/Max): error: storage/split_queue.go:103: unable to split range=7 [/Table/51-/Max) at key "/Table/52/0": storage/replica_command.go:1954: split at key /Table/52 failed: node unavailable; try another peer
I160424 06:47:13.044396 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34392: getsockopt: connection refused"; Reconnecting to "127.0.0.1:34392"
I160424 06:47:14.614792 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:34392: getsockopt: connection refused"; Reconnecting to "127.0.0.1:34392"
I160424 06:47:14.615124 /go/src/google.golang.org/grpc/clientconn.go:317  Failed to dial 127.0.0.1:34392: grpc: timed out trying to connect; please retry.
--- FAIL: TestShowCreateTable (2.76s)
	show_test.go:110: pq: sql/lease.go:108: table ID 52 not found
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
3 runs so far, 0 failures, over 35s
12 runs so far, 0 failures, over 40s
14 runs so far, 0 failures, over 45s
14 runs so far, 0 failures, over 50s
14 runs so far, 0 failures, over 55s
14 runs so far, 0 failures, over 1m0s
15 runs so far, 0 failures, over 1m5s
17 runs completed, 1 failures, over 1m7s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-25 19:37
Duplicate of #6226

**Closed by bdarnell** 2016-04-25 19:37 UTC
Labels: Robot, test-failure
