### ISSUE TITLE
circleci: failed tests (13887): TestRestoreReplicas

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4888] opened 2016-03-05 23:05 UTC
The following test appears to have failed:

[#13887](https://circleci.com/gh/cockroachdb/cockroach/13887):

```
I160305 23:04:15.495401 raft/raft.go:459  [group 1] 1 became follower at term 6
I160305 23:04:15.495584 raft/raft.go:235  [group 1] newRaft 1 [peers: [1,2], term: 6, commit: 15, applied: 15, lastindex: 15, lastterm: 6]
I160305 23:04:15.496020 storage/replica.go:1743  [node=1,store=1,range=1] gossiping system config from store 1, range 1, hash 91100e0451ac1aab78723f763fac84cccdd4aea5
I160305 23:04:15.497036 storage/replica.go:1684  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
I160305 23:04:15.497570 storage/replica.go:1693  [node=1,store=1,range=1] gossiping sentinel from store 1, range 1
panic: gossip infostore's NodeID is 0

goroutine 5319 [running]:
panic(0x18c37a0, 0xc8206575b0)
	/usr/local/go/src/runtime/panic.go:464 +0x3ff
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820164000, 0xc8202db9f8, 0x10, 0x10, 0x1bf08eb000, 0x2a)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0xb4
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc8201ca280, 0x1c8ac30, 0x8, 0xc8202db9f8, 0x10, 0x10, 0x1bf08eb000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:522 +0x12b
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc8202301a0, 0x358d840)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1695 +0xeea
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc82017c600, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:797 +0x3c3
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:741 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820457880, 0xc820615740)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	9.036s
=== RUN   TestBatchBasics
I160305 23:04:24.572868 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I160305 23:04:24.588065 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.02s)
=== RUN   TestBatchMerge
I160305 23:04:24.605258 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.02s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 02:27
Duplicate of #4821.

**Closed by petermattis** 2016-03-06 02:27 UTC
Labels: test-failure
