### ISSUE TITLE
operation "intent_resolver_ir_batcher.sendBatch" timed out after 1m0.005s (given timeout 1m0s) during BACKUP and RESTORE

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#116744] opened 2023-12-19 10:48 UTC
**Describe the problem**

We've recently started observing this error during `backupccl` unit tests (https://github.com/cockroachdb/cockroach/issues/116310#issuecomment-1862447872), nightly roach tests, and in the BACKUPs performed in the CCT cluster.

```
"intent_resolver_ir_batcher.sendBatch" timed out after 1m0.004s (given timeout 1m0s): canceled after waiting (pri=bulk-normal-pri stream=t3/s8 wait-duration=1m0.000054119s mode=apply_to_elastic)
```

```
 sql_runner.go:87: error executing query="RESTORE FROM $4 IN ($1, $2, $3) AS OF SYSTEM TIME 1702975658403050795.0000000000" args=["nodelocal://1/?COCKROACH_LOCALITY=default" "nodelocal://2/?COCKROACH_LOCALITY=dc%3Ddc1" "nodelocal://3/?COCKROACH_LOCALITY=dc%3Ddc2" "/2023/12/19-084738.40"]: pq: looking up user descriptors during restore: operation "intent_resolver_ir_batcher.sendBatch" timed out after 1m0.005s (given timeout 1m0s): deadline expired while waiting in queue: kv-regular-cpu-queue, pri: normal-pri, deadline: 2023-12-19 09:48:56.005267987 +0000 UTC m=+3757.431073214, start: 2023-12-19 09:47:56.011237476 +0000 UTC m=+3697.437042703, dur: 59.994173165s
```

We've recently turned on verbose tracing in the CCT cluster and will attempt to post a trace here when we have it.

Jira issue: CRDB-34747

**Comment by sumeerbhola** [comment] 2023-12-19 20:52
That first timeout `canceled after waiting (pri=bulk-normal-pri stream=t3/s8 wait-duration=1m0.000054119s mode=apply_to_elastic)` is replication AC flow tokens (since it is printing the stream -- tenant 3 trying to write to store s8), which indicates write overload on s8.

The second timeout `waiting in queue: kv-regular-cpu-queue, pri: normal-pri` is CPU overload.
This case is using some txn created and passed into `newInternalPlanner` in SQL land, presumably generated for the RESTORE query, so it is expected that it would be normal priority.

This looks like AC working as expected, and there is *both* write and CPU overload.

**Comment by benbardin** [comment] 2024-01-16 16:39
Closing, working as intended. https://cockroachlabs.atlassian.net/wiki/spaces/CKB/pages/3307930575/Jobs+may+fail+on+clusters+with+high+utilization

**Closed by benbardin** 2024-01-16 16:39 UTC
Labels: C-bug, A-disaster-recovery, T-disaster-recovery

**Comment by cody151** [comment] 2024-07-18 12:31
@benbardin how was this issue solved? I have the same issue on a fresh installed 6-node cluster trying to do a simple insert.

**Comment by benbardin** [comment] 2024-07-18 13:50
If that's happening during an INSERT it sounds like it might be a different issue, as this ticket is specific to this backup-related internal request. To dig into what you're seeing, you likely want to contact support at https://www.cockroachlabs.com/support/ .

**Comment by cody151** [comment] 2024-07-18 13:52
> If that's happening during an INSERT it sounds like it might be a different issue, as this ticket is specific to this backup-related internal request. To dig into what you're seeing, you likely want to contact support at https://www.cockroachlabs.com/support/ .

@benbardin Many thanks I did actually open a GitHub issue about it and me and @yuzefovich are currently looking at it, hopefully there's a solution
