### ISSUE TITLE
Support for PL/SQL ?

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#54886] opened 2020-09-28 20:39 UTC
**Is your feature request related to a problem? Please describe.**
It's a feature where we could run a (mini?) program inside database
Advantage best described here https://www.postgresql.org/docs/current/plpgsql-overview.html#PLPGSQL-ADVANTAGES

AFAIK, most competent database have a kind of that:
SQL Server have [TSQL](https://docs.microsoft.com/en-us/sql/t-sql/language-reference?view=sql-server-ver15)
Oracle have [PL/SQL](https://www.oracle.com/database/technologies/appdev/plsql.html)
Postgres have [PL/PGSQL](https://www.postgresql.org/docs/current/plpgsql.html)

I don't know if we want to .. `go pro` ?

**Comment by jordanlewis** [comment] 2020-11-09 14:48
Closing as duplicate of #17511, which has some more discussion. Thanks for filing @kocoten1992

**Closed by jordanlewis** 2020-11-09 14:48 UTC
Labels: C-enhancement, O-community, X-blathers-oncall
