### ISSUE TITLE
Test failure in CI build 7241

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2452] opened 2015-09-10 16:24 UTC
The following test appears to have failed:

[#7241](https://circleci.com/gh/cockroachdb/cockroach/7241):

```
E0910 16:23:55.709255 771 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:23:56.009181 771 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 16:23:56.309237 771 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
I0910 16:23:56.540543 771 kv/txn_coord_sender.go:280  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0.0 avg/σ/max restarts (0 samples)
E0910 16:23:56.609152 771 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
panic: test timed out after 5m0s

goroutine 3682 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1719c20, 0x1d0f5a0, 0x1f, 0x1f, 0x1428401)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:268 +0x21b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8204503c0, 0xc820601840)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x70
FAIL	github.com/cockroachdb/cockroach/server	300.054s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.01s)
=== RUN   TestRuntimeStatRecorder
I0910 16:19:01.623275 781 server/status/runtime.go:118  runtime stats: 10 goroutines, 5.19MiB active, 50000000.00cgo/sec, 234520.00/234520.00 %(u/s)time, 2395.84 %gc (1x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-10 21:32
dupe of #2440.

**Closed by tamird** 2015-09-10 21:32 UTC
Labels: test-failure
