### ISSUE TITLE
ui: Full event name should show on hover. v2.0-beta.20180319

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#24053] opened 2018-03-20 02:40 UTC
![image](https://user-images.githubusercontent.com/894257/37632771-2f30d314-2bc6-11e8-85c6-ec33dd4696f5.png)

Hovering over the truncated text in the event column doesn't show the full event name. Without that, this component isnt very useful. I think this used to work?

**Comment by couchand** [comment] 2018-03-20 16:41
dupe of #22742

**Closed by couchand** 2018-03-20 16:41 UTC
