### ISSUE TITLE
Support updating array elements by positional syntax

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#87173] opened 2022-08-31 11:59 UTC
**Is your feature request related to a problem? Please describe.**

In PostgreSQL, it's possible to update array elements by using the usual positional syntax. CockroachDB doesn't support this yet.

**Describe the solution you'd like**

This works in PostgreSQL:

```sql
create table t (i int primary key, j int[]);
insert into t values (1, array[1, 1]);
update t set j[1] = 2 returning *;
```

It produces:

```
|i  |j    |
|---|-----|
|1  |{2,1}|
```

Jira issue: CRDB-19193

**Comment by rafiss** [comment] 2022-10-12 02:01
This might relate to the challenges with updating JSON types using subscripting: https://github.com/cockroachdb/cockroach/issues/77434#issuecomment-1173263871

**Comment by mgartner** [comment] 2022-10-18 15:44
Closing as a duplicate of #77434.

**Closed by mgartner** 2022-10-18 15:44 UTC
Labels: C-enhancement, O-community, T-sql-experience, T-sql-queries, A-tools-jooq
