### ISSUE TITLE
Test failure in CI build 4651

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1690] opened 2015-07-15 19:52 UTC
The following test appears to have failed:

[#4651](https://circleci.com/gh/cockroachdb/cockroach/4651):

```
c989881463953912.37  127.0.0.1:0  19:51:21.464001  332.111µs  node                            server/node.go:489
c989881463953912.37  127.0.0.1:0  19:51:21.464043  277.899µs  ·executing InternalRangeLookup  storage/store.go:1237
c989881463953912.37  127.0.0.1:0  19:51:21.464056  263.226µs  ··read path                     storage/range.go:520

I0715 19:51:21.465274     265 kv/range_cache.go:149] adding descriptor: key="\x00\x00meta2\xff\xff" desc=raft_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 > 
panic: test timed out after 5m0s

goroutine 200606 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [semacquire, 4 minutes]:
sync.(*Cond).Wait(0xc2087ca240)
	/usr/src/go/src/sync/cond.go:62 +0xb6
--
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:77 +0x1bb
github.com/cockroachdb/cockroach/util/stop.func·002()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:85 +0xa2
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:86 +0x14c
FAIL	github.com/cockroachdb/cockroach/client	300.109s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
W0715 19:46:37.985738     286 rpc/tls.go:40] listening via tcp to 127.0.0.1:0 without TLS
I0715 19:46:37.987409     286 gossip/gossip.go:166] gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
W0715 19:46:37.987813     286 rpc/tls.go:40] listening via tcp to 127.0.0.1:0 without TLS
I0715 19:46:37.988704     286 gossip/gossip.go:166] gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
W0715 19:46:37.992726     286 rpc/tls.go:52] connecting via tcp to 127.0.0.1:51481 without TLS
I0715 19:46:37.995675     286 rpc/client.go:122] client 127.0.0.1:51481 connected

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-07-15 20:34
Duplicate of #1684. Also, our testrace.log is 100MB (because of 5 minutes of retries while waiting to timeout) and chrome refuses to load it.

**Closed by bdarnell** 2015-07-15 20:34 UTC
Labels: test-failure
