### ISSUE TITLE
exec: support LEFT SEMI and LEFT ANTI merge joins with on expressions

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#39458] opened 2019-08-08 16:00 UTC
This is required to support TPCH query 21

```
SELECT
	s_name,
	count(*) AS numwait
FROM
	supplier,
	lineitem l1,
	orders,
	nation
WHERE
	s_suppkey = l1.l_suppkey
	AND o_orderkey = l1.l_orderkey
	AND o_orderstatus = 'F'
	AND l1.l_receiptDATE > l1.l_commitdate
	AND EXISTS (
		SELECT
			*
		FROM
			lineitem l2
		WHERE
			l2.l_orderkey = l1.l_orderkey
			AND l2.l_suppkey <> l1.l_suppkey
	)
	AND NOT EXISTS (
		SELECT
			*
		FROM
			lineitem l3
		WHERE
			l3.l_orderkey = l1.l_orderkey
			AND l3.l_suppkey <> l1.l_suppkey
			AND l3.l_receiptDATE > l3.l_commitdate
	)
	AND s_nationkey = n_nationkey
	AND n_name = 'SAUDI ARABIA'
GROUP BY
	s_name
ORDER BY
	numwait DESC,
	s_name
LIMIT 100;

pq: unable to vectorize execution plan: can't plan non-inner merge joins with on expressions
```

**Comment by yuzefovich** [comment] 2019-08-08 22:48
This looks like a duplicate of #38018.

**Comment by jordanlewis** [comment] 2019-08-08 22:59
However, it has some critical new information - that we need to be able to plan non-inner merge joins with on expressions for full coverage of TPCH. Maybe we should try to update #34497 with this information and any new details that could be helpful.

**Closed** 2019-09-06 19:40 UTC
Labels: A-sql-execution, A-sql-vec, C-enhancement
