### ISSUE TITLE
sql: panic on rollbackSQLTransaction with non-open txn

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#5744] opened 2016-03-30 22:12 UTC
I got the following crash when killing a load generator app.

```
panic: rollbackSQLTransaction called on non-open txn: &{db:{sender:0xc8202dc160 userPriority:1 txnRetryOptions:{InitialBackoff:50000000 MaxBackoff:5000000000 Multiplier:2 MaxRetries:0 RandomizationFactor:0 Closer:<nil>}} wrapped:0xc820378e40 Proto:"sql/executor.go:380 sql txn" id=42e8c764 key=/Table/51/1/1/2/1 rw=true pri=0.00170982 iso=SERIALIZABLE stat=PENDING epo=1 ts=1459375813.964082583,1 orig=1459375813.964082583,1 max=1459375814.207097056,0 wto=false UserPriority:NORMAL Context:context.Background.WithCancel CollectedSpans:[] systemConfigTrigger:false retrying:false finalized:false}

goroutine 6503 [running]:
panic(0x4edbfa0, 0xc8206edf10)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/sql.rollbackSQLTransaction(0xc8207fc828, 0xc8207fc878, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:813 +0x1cf
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInAbortedTxn(0xc8202241c0, 0x7acf2c0, 0x5dd3b78, 0xc8207fc828, 0xc8207fc878, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:603 +0x166
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8202241c0, 0xc8206edc40, 0x1, 0x1, 0xc8207fc878, 0xc8207fc828, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:558 +0xbbb
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8202241c0, 0xc8207fc878, 0x3, 0xc8207fc828, 0xc8207497a0, 0xc8206edc40, 0x1, 0x1, 0xc820a093a0, 0xc820a093b8, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:488 +0x147
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc8202dc160, 0xc8207497a0, 0xc8208b9c80)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:401 +0x325
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8202dc160, 0x55d0000, 0x0, 0x0, 0xc820a094f8, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/client/txn.go:531 +0x410
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8202241c0, 0x7a059d0, 0xc820644340, 0xc8207fc800, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x7a50d00)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:405 +0x892
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8202241c0, 0x7a059d0, 0xc820644340, 0xc8207fc800, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/executor.go:295 +0xe2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8202f4600, 0x7a059d0, 0xc820644340, 0xc8207be137, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:604 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8202f4600, 0x7a059d0, 0xc820644340, 0xc8202f4628, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:314 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8202f4600, 0x0, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:270 +0x10d3
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc8202c7e58, 0x7a083d8, 0xc820241810, 0x0, 0x0)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:159 +0x929
github.com/cockroachdb/cockroach/server.(*Server).Start.func4.1(0x7a083d8, 0xc820241810)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/server/server.go:300 +0x4b
github.com/cockroachdb/cockroach/util.ServeHandler.func3.1(0xc820140600, 0x7a083d8, 0xc820241810, 0xc820200020)
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:125 +0x5a
created by github.com/cockroachdb/cockroach/util.ServeHandler.func3
	/Users/nathan/Go/src/github.com/cockroachdb/cockroach/util/net.go:127 +0x31f
```

**Comment by seiflotfy** [comment] 2016-04-01 10:27
do you have code for the load generator so i an try it myself?

**Comment by andreimatei** [comment] 2016-04-01 14:36
The problem is the cleanup function called here when the txn state is `RestartWait` has a wrong assert.
https://github.com/cockroachdb/cockroach/blob/master/sql/executor.go#L603

I'll send a fix soon. Need to figure out how to test.

But Nathan I'm wondering how you've triggered this by killing a client. I'd indeed expect this to happen when you're closing a connection whose txn is in state `RestartWait`, except I can't find the code that rolls back the txn if the connection drops.
I see this `conn.finish()` call, which terminates the session, but terminating the session does not appear to actually do anything. https://github.com/cockroachdb/cockroach/blob/master/sql/pgwire/server.go#L144
Maybe @dt would know if pgwire rolls back the txn somehow? I guess it's likely we have just omitted doing that, since the KV txn will be abandoned at some point because of heartbeats and until recently the session was not persisted on the server, but now that it is we should definitely proactively roll back if we're not doing it already. I'll file a bug if David doesn't contradict this.

**Closed** 2016-04-01 18:02 UTC
Labels: bug
