### ISSUE TITLE
user databases not visible when querying information_schema from psql

### ISSUE THREAD

**Issue by andrew-bickerton** [cockroachdb/cockroach#21699] opened 2018-01-23 15:24 UTC
When running as root on v1.1.4 of our cockroach cluster, I get different results when querying the information_schema database.

Specifically when I run the query: SELECT * FROM information_schema.tables;
From psql I only see the databases:
* information_schema
* pg_catalog
* crdb_internal
* system

When running the same query from cockroach sql client, I can see the above databases + the databases we have created.

**cockroach version**
Build Tag:    v1.1.4
Build Time:   2018/01/08 17:32:42
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  b794b52cbfffa2340cdaabf1c33be716ebde1db4
Build Type:   release-gnu

**Comment by mrtracy** [comment] 2018-01-23 19:35
Hi andrew,

I am unable to reproduce this on 1.1.4.  With a single user database "foo", I get the following from cockroach sql:

```
root@***:26257/> select distinct(table_schema) from information_schema.tables;
+--------------------+
|   (table_schema)   |
+--------------------+
| crdb_internal      |
| foo                |
| information_schema |
| pg_catalog         |
| system             |
+--------------------+
(5 rows)

Time: 1.401019ms
```

And from psql:
```
root=> select distinct(table_schema) from information_schema.tables;
   (table_schema)   
--------------------
 crdb_internal
 foo
 information_schema
 pg_catalog
 system
(5 rows) 
```

Are you certain you are connecting to the same instance of cockroachDB from both clients?

**Comment by andrew-bickerton** [comment] 2018-01-25 14:32
Hi @mrtracy,

Yes definitely connecting to the same instance if I run:
`show databases;
system=> show databases;
          Database
-----------------------------
 bank
 crdb_internal
 information_schema
 pg_catalog
 system
(5 rows)`

I'm just in the process of building another cluster to see if I can reproduce this issue, some notes on other potential differences:
* This is an insecure cluster
* a different developer (logged in as root) created the databases
* running on kubernetes

**Comment by knz** [comment] 2018-01-29 18:34
Hello @andrew-bickerton. The distinction depends on whether you have a "current database" active or not.

With a "currrent database" set a query against an (unqualified) `crdb_internal` or `pg_catalog` table will report data only for that database. Without a current database set, the virtual tables report results for all databases. You can observe that difference from `cockroach sql` directly by comparing the output of the following queries:


     select * from foo.information_schema.schematas -- specific to 1 db
     select * from "".information_schema.schematas -- for all dbs

The reason why you observe a difference is that psql always set the current database by default, whereas `cockroach sql` doesn't.

Does this clarify?

**Comment by knz** [comment] 2018-01-29 18:34
See also the work ongoing in #21456

**Comment by andrew-bickerton** [comment] 2018-01-30 13:18
@knz,

Thanks for that clarification, I didn't realise that! Makes more sense now.

Thanks

**Comment by knz** [comment] 2018-01-30 13:21
Ok! I am going to close this issue. If you have any question or comment, let us know!

**Closed by knz** 2018-01-30 13:21 UTC
Labels: ux-surprise
