### ISSUE TITLE
Performance degradation over time

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#30003] opened 2018-09-10 16:48 UTC
I modified tpc-c bench to step tpc-c by 100 warehouses (starting at 100) until failure to fill in a curve for tpc-c performance.

However, when I ran this same code, starting at 1300 warehouses, I saw a big performance difference for 1300, 1400, and 1500 warehouses.

1300 warehouses a 3.74% degradation
1400 warehouses a 10.76% degradation 
1500 warehouses a 9.14% degradation 

@nvanbenschoten thinks this could be related to the fact that over time log commit latency and command commit latency both grow as the number of SSTs grow.

**Comment by awoods187** [comment] 2018-09-20 12:18
This appears to be present in 2.0 as well:

When starting at 1500:
1500 | 14778.9 | 76.61%
1400 | 14150.2 | 78.59%
1300 | 13016.9 | 77.86%
1200 | 14293 | 92.62%

When starting at 1300:
1300 | 15,960.6 | 95.47%
1400 | 14279.1 | 79.31%

**Comment by awoods187** [comment] 2018-09-26 04:39
This appears to be still present in the latest run from today's 2.1 branch:

When starting at 1300:
3 | 16 | 1300 | 16,226.5 | 97.06%
3 | 16 | 1400 | 17,326.8 | 96.24%
3 | 16 | 1500 | 14,709.2 | 76.25%

When starting at 1500:

3 | 16 | 1500 | 18,568.9 | 96.26%
3 | 16 | 1600 |  17,916.5 | 87.07%
3 | 16 | 1700 |  17,329.2 | 79.27%

**Comment by nvanbenschoten** [comment] 2018-10-02 19:29
I'm going to close this, since it's roughly a duplicate of #30374.

**Closed by nvanbenschoten** 2018-10-02 19:29 UTC
Labels: A-coreperf, C-performance
