### ISSUE TITLE
kv: split failed while applying backpressure: could not find valid split key error

### ISSUE THREAD

**Issue by roncrdb** [cockroachdb/cockroach#37772] opened 2019-05-23 14:46 UTC
**Describe the problem**

There have been multiple instances of users seeing this error. We know the cause of this error is due to a single range having so many MVCC versions that it takes up more than 128 MB (twice the max range size).  The cause of why MVCC values on the system config span range are growing so rapidly is not yet fully known, but we think it may be due to schema changes. Usually this error can be resolved by changing a cluster setting (`SET CLUSTER SETTING kv.range.backpressure_range_size_multiplier=0`) as well as adjusting the MVCC TTL to a much lower number (by default this is 25 hours), however as of recent, this issue has been happening on a particular range, the system config span range that houses the cluster settings and zone configurations and so any attempt made at changing these results in the split failed error.  As of now, we have not been able to reproduce this but there have been several instances of users reporting this issue. 

Engineering has come up with a few ideas on how to get to the root cause of this issue: 

* Improve the error message so that this issue can be debugged easier
* Turn off back pressure on the range that holds the cluster settings and zone configurations 

**To Reproduce**

As of yet, unable to reproduce this issue on the system config range

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB cluster ...
2. Send SQL ... / CLI command ...
3. Look at UI / log file / client app ...

**Expected behavior**

MVCC values should not be saturating a system range to the point that a cluster freezes up.
 

**Environment:**
 - CockroachDB version 19.1.0

cc @nvanbenschoten

**Comment by roncrdb** [comment] 2019-05-23 15:07
#37592, #37530, #37337

**Comment by heidawei** [comment] 2019-05-24 01:44
@roncrdb  here is the table schema

```
CREATE TABLE preferential_dtl (
	uuid VARCHAR(50) NOT NULL,
	source_type VARCHAR(240) NOT NULL,
	detail_source_type VARCHAR(240) NOT NULL,
	archive_status VARCHAR(240) NULL,
	action VARCHAR(240) NULL,
	accounting_date TIMESTAMP NOT NULL,
	currency_code VARCHAR(10) NOT NULL,
	org_no_des VARCHAR(240) NULL,
	org_no_src VARCHAR(240) NOT NULL,
	dept VARCHAR(240) NULL,
	amount DECIMAL(38,2) NULL,
	ref_no VARCHAR(240) NULL,
	action_type VARCHAR(240) NULL,
	prefert_no VARCHAR(240) NULL,
	sku_no VARCHAR(240) NULL,
	src_system VARCHAR(240) NULL,
	comments VARCHAR(240) NULL,
	ebs_group_no DECIMAL(38) NULL,
	warning_message VARCHAR(400) NULL,
	creation_date TIMESTAMP NOT NULL,
	last_updated_date TIMESTAMP NOT NULL,
	batch_no VARCHAR(30) NOT NULL,
	jd_pk DECIMAL(38) NULL,
	attribute_category VARCHAR(240) NULL,
	attribute1 VARCHAR(240) NULL,
	attribute2 VARCHAR(240) NULL,
	attribute3 VARCHAR(240) NULL,
	attribute4 VARCHAR(240) NULL,
	attribute5 VARCHAR(240) NULL,
	attribute6 VARCHAR(240) NULL,
	attribute7 VARCHAR(240) NULL,
	attribute8 VARCHAR(240) NULL,
	attribute9 VARCHAR(240) NULL,
	attribute10 VARCHAR(240) NULL,
	attribute11 VARCHAR(240) NULL,
	attribute12 VARCHAR(240) NULL,
	attribute13 VARCHAR(240) NULL,
	attribute14 VARCHAR(240) NULL,
	attribute15 VARCHAR(240) NULL,
	request_id DECIMAL(38) NULL,
	mid_tab_group_name VARCHAR(35) NOT NULL,
	rerun_flag VARCHAR(1) NULL,
	jd_processor VARCHAR(50) NULL,
	group_md5_code VARCHAR(32) NULL,
	CONSTRAINT "primary" PRIMARY KEY (uuid ASC),
	FAMILY "primary" (uuid, source_type, detail_source_type, archive_status, action, accounting_date, currency_code, org_no_des, org_no_src, dept, amount, ref_no, action_type, prefert_no, sku_no, src_system, comments, ebs_group_no, warning_message, creation_date, last_updated_date, batch_no, jd_pk, attribute_category, attribute1, attribute2, attribute3, attribute4, attribute5, attribute6, attribute7, attribute8, attribute9, attribute10, attribute11, attribute12, attribute13, attribute14, attribute15, request_id, mid_tab_group_name, rerun_flag, jd_processor, group_md5_code)
)
```
In cockroachDB v2.1, The probability of occurrence is high with very high concurrency(240 etc.)
the TXN will wait for long time to finish when this error happen, like deadlock, but will success when the split task failed for timeout.

But in V19.1, maybe it's split by load that makes it rare.

**Comment by heidawei** [comment] 2019-05-24 01:52
I use five Nodes(CPU 64 cores, memory 256GB, network 1GB, disk SSD 1TB for each Node) for this test, each machine indicators（CPU，mem，net，disk） are normal before and after errors occur。I use HA proxy to load balance

**Comment by heidawei** [comment] 2019-05-30 01:07
@roncrdb  Can this case be reproduced?

**Comment by ajwerner** [comment] 2020-03-18 22:18
We've fixed the problem with system ranges. I'm going to close this issue. We still have the problem for user ranges which are too large due to a single key but we've made the GC much more robust. We could keep the issue open to improve documentation but I'd rather that we track that when it comes back up again.

**Closed by ajwerner** 2020-03-18 22:18 UTC
Labels: C-bug, S-2
