### ISSUE TITLE
sql: transform OR of ANDs to tuple comparison

### ISSUE THREAD

**Issue by squarespirit** [cockroachdb/cockroach#42502] opened 2019-11-14 22:35 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes Cockroach cannot determine that an OR of ANDs is equivalent to a tuple filter. Here is a query with an OR of ANDs where we expect it to do a reverse scan, but actually Cockroach produces a complicated query plan with a forward scan:
```
explain SELECT * FROM test WHERE (col1 < 'a' OR (col1 = 'a' AND token__pk < 1) OR (col1 = 'a' AND token__pk = 1 AND pk < 'a')) ORDER BY col1 DESC, token__pk DESC, pk DESC LIMIT 100;
          tree         | field  |                                                 description                                                  
+----------------------+--------+-------------------------------------------------------------------------------------------------------------+
  limit                |        |                                                                                                              
   │                   | count  | 100                                                                                                          
   └── sort            |        |                                                                                                              
        │              | order  | -col1,-token__pk,-pk                                                                                         
        └── index-join |        |                                                                                                              
             │         | table  | test@primary                                                                                                 
             └── scan  |        |                                                                                                              
                       | table  | test@col1_idx                                                                                                
                       | spans  | -/"a"/1/"a"                                                                                                  
                       | filter | ((col1 < 'a') OR ((col1 = 'a') AND (token__pk < 1))) OR (((col1 = 'a') AND (token__pk = 1)) AND (pk < 'a')) 
```
However a query with an equivalent tuple filter does an efficient revscan.
```
explain SELECT * FROM test WHERE (col1, token__pk, pk) < ('a', 1, 'a') ORDER BY col1 DESC, token__pk DESC, pk DESC LIMIT 100;
      tree     | field |  description   
+--------------+-------+---------------+
  index-join   |       |                
   │           | table | test@primary   
   └── revscan |       |                
               | table | test@col1_idx  
               | spans | -/"a"/1/"a"    
               | limit | 100
```
For reference, token__pk and pk are the primary keys of test, and there is an ascending index on col1.

**Describe the solution you'd like**
Choose the correct index in the correct direction when using an OR of ANDs

**Describe alternatives you've considered**
To paginate we have been appending an OR of ANDs to all our queries corresponding to the last row in the previous page. The issue with a tuple filter is that it does not work if some columns in the order by are ASC and some are DESC. So we'd like to be able to use an OR of ANDs all the time if possible.

**Additional context**
Was discussed with @justinj .

Jira issue: CRDB-5352

**Comment by DrewKimball** [comment] 2020-08-21 02:38
I'm unable to reproduce on current master with this CREATE TABLE statement:
```
CREATE TABLE test (
  token__pk INT, 
  pk STRING, 
  col1 STRING, 
  extra INT,  
  PRIMARY KEY(token__pk, pk), 
  INDEX(col1)
);
```
Unless I'm missing something, it looks like this may have been fixed at some point; `GenerateConstrainedScans` is leading to the expected plan.

**Comment by rytaft** [comment] 2022-05-17 22:05
Closing this as it appears to have been fixed.

**Closed by rytaft** 2022-05-17 22:05 UTC
Labels: C-enhancement, O-community, A-sql-optimizer, T-sql-queries
