### ISSUE TITLE
sql: schema change does not cancel when the session is closed, when cancelled rollback job takes forever to start

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#33158] opened 2018-12-14 13:44 UTC
```
root@172.31.22.161:26257/> CREATE INVERTED INDEX ON skusv2_all_I (skujson);

^C

skusv2_all_I (skujson) ran for 11 hours and the estimated time increased so I killed it. And even though no rollback appears under jobs. The cluster is running at high CPU without QPS.
```

Two problems:

- no job
- index creation not stopped when the client is interrupted

**Comment by drewdeally** [comment] 2018-12-14 15:40
Schema and data import
`IMPORT TABLE mysale.public.skusv2_all_I (id UUID PRIMARY KEY, skujson JSONB, masterskuid UUID, createdby UUID, createddate STRING, lastsavedby UUID, lastsaveddate STRING, isdeleted BOOL, availabilityjson JSONB, quantityjson JSONB) CSV DATA ('https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export10.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export11.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export12.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export13.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export14.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export15.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export16.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export17.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export18.csv.gz', 'https://s3-ap-southeast-2.amazonaws.com/import-csv-test/SkusV2_full_export19.csv.gz') WITH decompress = 'gzip', "nullif" = '', skip = '1';
`
        job_id       |  status   | fraction_completed |  rows   | index_entries | system_records |    bytes     
+--------------------+-----------+--------------------+---------+---------------+----------------+-------------+
  408577946508263425 | succeeded |                  1 | 1664930 |             0 |              0 | 63126602757  

   count   
+---------+
  1664930  

Commands

`root@172.31.22.161:26257/mysale> CREATE INDEX ON skusv2_all_I  USING GIN (availabilityjson);
pq: relation "skusv2_all_i\u00a0" does not exist
root@172.31.22.161:26257/mysale> CREATE INDEX ON skusv2_all_I  USING GIN (quantityjson);
pq: relation "skusv2_all_i\u00a0" does not exist
root@172.31.22.161:26257/mysale> CREATE INDEX ON skusv2_all_I  USING GIN (skujson);
pq: relation "skusv2_all_i\u00a0" does not exist
root@172.31.22.161:26257/mysale> CREATE INVERTED INDEX ON skusv2_all_I (availabilityjson);
CREATE INDEX

Time: 6m33.24195712s

root@172.31.22.161:26257/mysale> CREATE INVERTED INDEX ON skusv2_all_I (quantityjson);
CREATE INDEX

Time: 3m19.274105429s

root@172.31.22.161:26257/mysale> CREATE INVERTED INDEX ON skusv2_all_I (skujson);



^C

`
skusv2_all_I (skujson) ran for 11 hours and the estimated time increased so I killed it.  And even though no rollback appears under jobs.  The cluster is running at high CPU without QPS.

**Comment by knz** [comment] 2018-12-14 15:49
1) @drewdeally the error you see "pq: relation "skusv2_all_i\u00a0" does not exist" is because you copy-pasted the CREATE INDEX statement incorrectly (probably from some PDF or other document) and there was an invisible special character between the word "skusv2_all_I" and "USING". I check this on my computer and it works without problem.

2) We already have several issues about the performance of inverted indexes:

-  CREATE INVERTED INDEX job using 75% of CPU when cluster at rest #32681 @vivekmenezes 
-  sql: create a roachtest that adds an inverted index to a table with a json column #33142  @vivekmenezes 
-  IMPORT failing to create inverted indexes #32468  @dt 
-  sql: test JSON with a large data set with load #21794  @vivekmenezes @justinj 

3) @andreimatei @vivekmenezes  why is the index creation  not cancelled when the client closes the connection?

4) @vivekmenezes why is there no job created to track the progress of the index creation?

**Comment by vivekmenezes** [comment] 2018-12-14 16:22
I've changed this bug to say that closing a session doesn't cancel the job. I believe that is by design. We wanted the user to explicitly cancel the job, but the more I think about this I can see why that would be the desired behavior. I think this is going to be much harder to fix because there is no guarantee that the schema change is being executed by the gateway node itself, it can move to another node in the process (rarely but technically it can).

**Comment by vivekmenezes** [comment] 2018-12-14 16:37
So it looks like we also have an issue with the rollback job taking forever to start. I'm seeing this on a cluster where an inverted index was being created. The job says its cancelled, but CPU is still being drawn by the index creation. The problem here is the schema changer is not seeing it is cancelled and starting a rollback

**Comment by awoods187** [comment] 2018-12-14 16:41
@knz can we update the error message here or provide more context as I don't think it's obvious to the user that it was user error in reference to `"pq: relation "skusv2_all_i\u00a0" does not exist" is because you copy-pasted the CREATE INDEX statement incorrectly (probably from some PDF or other document) and there was an invisible special character between the word "skusv2_all_I" and "USING". I checked this on my computer and it works without problem.`

**Comment by knz** [comment] 2018-12-14 16:46
@awoods187 I am not sure what the best UX is. I'd like to point out that CockroachDB is currently _extremely_ better than PostgreSQL for this particular problem. Check this out:

```
kena=> create table foo(x int);
CREATE TABLE

kena=> create index on foo (x);  -- note: I added the special character between "foo" and (
ERROR:  relation "foo " does not exist
```

**Comment by drewdeally** [comment] 2018-12-14 16:47
Thank you for the correction on the index.  
The actual issue is the hung create index on skujson. CREATE INVERTED INDEX ON skusv2_all_I (skujson);  I am going to modify the data and try again.  

[debug.zip](https://github.com/cockroachdb/cockroach/files/2681019/debug.zip)

**Comment by knz** [comment] 2018-12-14 16:47
At least the explicit mention of the character was telling me (from the start!) exactly what was wrong. I did ask to confirm but I could have told you with the initial report that 0xa0 (the extra character) was the non-breaking space: https://unicode-table.com/en/00A0/

**Comment by vivekmenezes** [comment] 2018-12-14 18:39
timeline on this index backfill

first it ran on node 1
`
I181214 04:04:54.830206 1413 sql/backfill.go:134  [n1,client=172.31.22.161:36478,user=root,scExec] Running backfill for "skusv2_all_i", v=9, m=3
`

then it moved to node 3
`I181214 11:52:08.545725 480 sql/backfill.go:134  [n3,scExec] Running backfill for "skusv2_all_i", v=9, m=3`

then back to node 1
`I181214 11:57:34.586301 468 sql/backfill.go:134  [n1,scExec] Running backfill for "skusv2_all_i", v=9, m=3`

then it moved to node 2
`I181214 12:03:31.527190 451 sql/backfill.go:134  [n2,scExec] Running backfill for "skusv2_all_i", v=9, m=3`

and then node 1 complained and tried to reverse the schema change
`W181214 12:12:25.629289 1413 sql/schema_changer.go:679  [n1,client=172.31.22.161:36478,user=root,scExec] reversing schema change 408583847186923521 due to irrecoverable error: context canceled`

but was unsuccessful because the context it used was cancelled.

**Comment by drewdeally** [comment] 2018-12-14 19:09
[debug.zip](https://github.com/cockroachdb/cockroach/files/2681389/debug.zip)
@vivekmenezes

**Comment by drewdeally** [comment] 2018-12-14 19:11
at this point in time index create on jsonb is running on smaller table.

**Comment by vivekmenezes** [comment] 2018-12-14 19:23
thanks @drewdeally . It does look like the backfill restarted on node 2 at 12:03:31 as noted above and is continuing to move forward even though the schema change is cancelled. Thanks!

**Comment by vivekmenezes** [comment] 2018-12-14 19:45
I now know what's going on here. The problem is the schema changer only checks the status of the job (cancelled) when it needs to report progress. Progress in the current implementation is reported as the fraction of ranges that have completed processing. But if the data is well distributed, and the schema change is slow (which happens to be the case here), progress while it's happening at the row level might not be happening in terms of the range completion count.

For now, I'd leave the cluster as is and wait until the cancel does get triggered. Hopefully it will. If that is the case we can modify this mechanism to lookup the job status every time to check for the cancel. It would still not resolve the deeper issue here that the schema change is very slow.

**Comment by vivekmenezes** [comment] 2018-12-14 19:54
Hmmm, actually I doubt what I'm saying is true given that the new index on skusv2 is making progress.

**Comment by drewdeally** [comment] 2018-12-14 19:57
It is moving along but the ETA does not seem to update even the progress bar is.

Andrew

**Comment by awoods187** [comment] 2018-12-20 01:20
cc @drewdeally

**Comment by vivekmenezes** [comment] 2019-02-12 17:32
I'm expecting this to not be an issue in 2.2 because of the new index backfill implementation. We need to test and see if this is indeed the case.

**Comment by drewdeally** [comment] 2019-02-12 17:42
Thanks!

**Comment by vivekmenezes** [comment] 2019-03-07 17:44
This is not an issue for 19.1 since the index backfill is a lot more faster with progress updates happening more frequently. Closing!

**Closed by vivekmenezes** 2019-03-07 17:44 UTC
Labels: A-schema-changes, C-bug, S-3-ux-surprise

**Comment by drewdeally** [comment] 2019-03-07 17:50
thanks will try it
