### ISSUE TITLE
Test failure in CI build 4295

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1570] opened 2015-06-29 21:24 UTC
The following test appears to have failed:

[#4295](https://circleci.com/gh/cockroachdb/cockroach/4295):

```
I0629 21:22:08.485608     306 server.go:111] gossip: received 3 info(s) from /tmp/unix-socket129339833
I0629 21:22:08.488469     306 client.go:165] gossip: received 3 info(s) from /tmp/unix-socket129339833
I0629 21:22:08.488568     306 server.go:111] gossip: received 2 info(s) from /tmp/unix-socket242783172
I0629 21:22:08.490713     306 client.go:119] client /tmp/unix-socket129339833 connected
W0629 21:22:08.491107     306 gossip.go:518] missing sentinel gossip 3; assuming partition and reconnecting
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0xaafca6]

goroutine 238 [running]:
github.com/cockroachdb/cockroach/proto.FromNetAddr(0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/proto/gossip.go:29 +0x36
github.com/cockroachdb/cockroach/gossip.(*client).gossip(0xc20800bc20, 0xc20807a3f0, 0xc208030360, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:124 +0x5e9
github.com/cockroachdb/cockroach/gossip.func·001()
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:85 +0x320
github.com/cockroachdb/cockroach/util.func·001()
--
goroutine 273 [runnable]:
github.com/cockroachdb/cockroach/gossip.func·013()
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:296
created by github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:300 +0x40a
FAIL	github.com/cockroachdb/cockroach/kv	0.988s
=== RUN TestHeartbeatSingleGroup-2
--- PASS: TestHeartbeatSingleGroup-2 (0.38s)
=== RUN TestHeartbeatMultipleGroupsJointLeader-2
--- PASS: TestHeartbeatMultipleGroupsJointLeader-2 (0.03s)
=== RUN TestHeartbeatResponseFanout-2
I0629 21:22:11.001027     317 heartbeat_test.go:425] SubmitCommand succeed after Heartbeat Response fanout
E0629 21:22:11.002469     317 transport.go:202] sending rpc failed: read tcp 127.0.0.1:38401: use of closed network connection
E0629 21:22:11.002778     317 transport.go:202] sending rpc failed: read tcp 127.0.0.1:38401: use of closed network connection
E0629 21:22:11.009287     317 transport.go:202] sending rpc failed: read tcp 127.0.0.1:46061: use of closed network connection
--- PASS: TestHeartbeatResponseFanout-2 (0.08s)

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-06-29 22:09
dupe of #1563

**Closed by tamird** 2015-06-29 22:09 UTC
Labels: test-failure
