### ISSUE TITLE
circleci: failed tests (13491): TestKVDBInternalMethods 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4704] opened 2016-02-28 02:27 UTC
The following test appears to have failed:

[#13491](https://circleci.com/gh/cockroachdb/cockroach/13491):

```
I160228 02:25:27.810844 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160228 02:25:27.810922 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160228 02:25:27.811002 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160228 02:25:27.811082 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160228 02:25:27.811317 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestKVDBInternalMethods (0.11s)
	db_test.go:186: 0: unexpected error for HeartbeatTxn: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 1: unexpected error for GC: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 2: unexpected error for PushTxn: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 3: unexpected error for RangeLookup: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 4: unexpected error for ResolveIntent: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 5: unexpected error for ResolveIntentRange: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 6: unexpected error for Merge: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 7: unexpected error for TruncateLog: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 8: unexpected error for LeaderLease: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
	db_test.go:186: 9: unexpected error for EndTransaction: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
--
W160228 02:25:30.788131 kv/dist_sender.go:621  failed to invoke BeginTransaction ["a",/Min), Put ["a",/Min), Put ["b",/Min): txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=48da9dcc key="a" rw=true pri=0.01919749 iso=SERIALIZABLE stat=PENDING epo=1 ts=1456626330.786198470,0 orig=1456626330.786198470,0 max=1456626330.786198470,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=5e593805 key="b" rw=false pri=0.00738432 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456626330.785290029,0 orig=1456626330.785290029,0 max=1456626330.785290029,0
I160228 02:25:30.788374 client/db.go:488  failed batch: txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=48da9dcc key="a" rw=true pri=0.01919749 iso=SERIALIZABLE stat=PENDING epo=2 ts=1456626330.786198470,0 orig=1456626330.786198470,0 max=1456626330.836198470,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=5e593805 key="b" rw=false pri=0.00738432 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456626330.785290029,0 orig=1456626330.785290029,0 max=1456626330.785290029,0
I160228 02:25:30.840340 storage/replica_command.go:457  auto-gc'ed 5e593805 (1 intents)
I160228 02:25:30.844223 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.25s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	18.278s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestFlagsToStr
--- PASS: TestFlagsToStr (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-29 22:02
Duplicate of #4723.

**Closed by petermattis** 2016-02-29 22:02 UTC
Labels: test-failure
