### ISSUE TITLE
Filtering by `select * from` in SQL Activity->Statements renders entire page unusable

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#81720] opened 2022-05-24 08:48 UTC
**Describe the problem**

On 22.1.0, after filtering on `select * from` in SQL Activity->Statements page and hitting Enter, the page then takes you to an error page.

<img width="1175" alt="Screenshot 2022-05-24 at 09 45 28" src="https://user-images.githubusercontent.com/28270695/169990207-8c10141d-6afa-4da0-9780-dfa1b119bb24.png">

<img width="506" alt="Screenshot 2022-05-24 at 09 45 32" src="https://user-images.githubusercontent.com/28270695/169990232-048458d4-8f5d-4ac0-b2a2-8cbd0108c436.png">

What's worse, is that there appears to be no way to 'clear' out the filter other than deleting Session Storage->cockroachui/search/StatementsPage from my browser.

Jira issue: CRDB-16042

**Comment by maryliag** [comment] 2022-05-24 13:05
Duplicate of https://github.com/cockroachdb/cockroach/issues/81695

**Closed** 2022-05-25 15:28 UTC
Labels: C-bug
