### ISSUE TITLE
Add hint to CTAS using UDFs that they are not currently supported

### ISSUE THREAD

**Issue by msirek** [cockroachdb/cockroach#99002] opened 2023-03-20 02:21 UTC
All of the following CREATE OR REPLACE VIEW statements return this error:
```
ERROR: unknown function: one(): function undefined
SQLSTATE: 42883
```
Tests:
``` sql
CREATE OR REPLACE FUNCTION one() RETURNS INT VOLATILE LANGUAGE SQL AS 'SELECT 1';
SELECT * from one();
CREATE OR REPLACE VIEW select_from_udf AS SELECT * from one();
CREATE OR REPLACE VIEW select_from_udf AS SELECT one();
CREATE OR REPLACE VIEW select_from_udf AS SELECT 1 WHERE 1 = one();
```
These are supported by Postgres. If we won't support these now, an "unimplemented" error should be returned indicating UDFs in views aren't supported instead of reporting the function doesn't exist.

Jira issue: CRDB-25647

**Comment by jhatcher9999** [comment] 2023-03-20 02:42
I get the same thing if I try to use a function in a CTAS statement.

```
CREATE TABLE t1 AS SELECT one() AS c1;                                           
ERROR: unknown function: one(): function undefined
SQLSTATE: 42883
```

**Comment by rharding6373** [comment] 2023-03-20 23:27
This is known unsupported behavior. There is a hint for views and UDFs that wasn't being applied properly. We'll need to look into applying the hint to CTAS as well.

**Comment by mgartner** [comment] 2023-06-08 16:51
This is a duplicate of #88197. Closing.

**Closed by mgartner** 2023-06-08 16:51 UTC
Labels: C-enhancement, C-qa, T-sql-queries, E-quick-win
