### ISSUE TITLE
stability: memory leak

### ISSUE THREAD

**Issue by clanstyles** [cockroachdb/cockroach#14143] opened 2017-03-14 19:42 UTC
Is this a question, feature request, or bug report?

**BUG REPORT**

1. Please supply the header (i.e. the first few lines) of your most recent
   log file **for each node in your cluster**. On most unix-based systems
   running with defaults, this boils down to the output of

     grep -F '[config]' cockroach-data/logs/cockroach.INFO

   When log files are not available, supply the output of `cockroach version`
   and all flags/environment variables passed to `cockroach start` instead.

```
E170313 20:36:09.421444 154 util/log/clog.go:999  [config] file created at: 2017/03/13 20:36:09
E170313 20:36:09.421444 154 util/log/clog.go:999  [config] running on machine: debian
E170313 20:36:09.421444 154 util/log/clog.go:999  [config] binary: CockroachDB CCL unknown (linux amd64, built , go1.8)
E170313 20:36:09.421444 154 util/log/clog.go:999  [config] arguments: [cockroach start]
```
2. Please describe the issue you observed:

- What did you do?
Let the database sit idle

- What did you expect to see?
It should have sat idle without growing in memory. No data was queried.

- What did you see instead?
The database grew in memory size until my system nearly crashed and I noticed.

**Comment by petermattis** [comment] 2017-03-14 19:47
This sounds similar to #13333 which I've been unable to reproduce. Can you `grep runtime.go cockroach-data/logs/cockroach.INFO`?

**Comment by clanstyles** [comment] 2017-03-14 19:52
Where is runtime.go? 

```
W170314 15:50:11.711311 27 server/status/runtime.go:116  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170314 15:50:22.222229 48 server/status/runtime.go:228  runtime stats: 53 MiB RSS, 82 goroutines, 7.1 MiB/7.2 MiB/24 MiB GO alloc/idle/total, 7.9 MiB/14 MiB CGO alloc/total, 0.00cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (7x)
I170314 15:50:32.222161 48 server/status/runtime.go:228  runtime stats: 56 MiB RSS, 82 goroutines, 13 MiB/3.3 MiB/25 MiB GO alloc/idle/total, 8.5 MiB/15 MiB CGO alloc/total, 73.30cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
I170314 15:50:42.222218 48 server/status/runtime.go:228  runtime stats: 57 MiB RSS, 82 goroutines, 10 MiB/5.6 MiB/25 MiB GO alloc/idle/total, 9.0 MiB/16 MiB CGO alloc/total, 69.20cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)
I170314 15:50:52.222269 48 server/status/runtime.go:228  runtime stats: 58 MiB RSS, 82 goroutines, 11 MiB/4.8 MiB/25 MiB GO alloc/idle/total, 9.2 MiB/16 MiB CGO alloc/total, 73.30cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)
I170314 15:51:02.222090 48 server/status/runtime.go:228  runtime stats: 58 MiB RSS, 82 goroutines, 12 MiB/3.9 MiB/25 MiB GO alloc/idle/total, 9.4 MiB/17 MiB CGO alloc/total, 73.40cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)
I170314 15:51:12.221982 48 server/status/runtime.go:228  runtime stats: 58 MiB RSS, 83 goroutines, 10 MiB/5.3 MiB/25 MiB GO alloc/idle/total, 9.7 MiB/17 MiB CGO alloc/total, 79.10cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)
I170314 15:51:22.222096 48 server/status/runtime.go:228  runtime stats: 59 MiB RSS, 80 goroutines, 10 MiB/5.5 MiB/25 MiB GO alloc/idle/total, 9.8 MiB/17 MiB CGO alloc/total, 115.80cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (2x)
```

But this doesn't actually represent what happened... I'll leave it running, it only too 6 hours for it to happen.

**Comment by petermattis** [comment] 2017-03-14 19:54
Thanks @clanstyles. There should actually be a few other `*.INFO*` files in `cockroach-data/logs`. (`runtime.go` is the string you're grep'ping for). If you grep in the other `*.INFO*` files it should show where the memory growth is occurring.

**Comment by clanstyles** [comment] 2017-03-14 19:59
[github.txt](https://github.com/cockroachdb/cockroach/files/842523/github.txt)
I had to upload the file, it's huge.

**Comment by petermattis** [comment] 2017-03-14 20:25
`I170314 10:26:41.631028 16 server/status/runtime.go:228  runtime stats: 26 GiB RSS, 90 goroutines, 24 GiB/1.2 MiB/26 GiB GO alloc/idle/total, 119 MiB/182 MiB CGO alloc/total, 17906.37cgo/sec, 6.88/0.04 %(u/s)time, 0.00 %gc (1x)`

So this is different than #13333. Something in Go land allocated 24 GiB of memory. I can't recall seeing anything like this recently.

@clanstyles Is this reproducible? If it is, it would be very useful to grab a heap profile. Or to turn on periodic heap profile dumps by running the server with `COCKROACH_MEMPROF_INTERVAL=60s` or something like that. That will grab a heap profile every 60s (which will create a lot of them),

**Comment by petermattis** [comment] 2017-03-14 20:26
Is this a multi-node cluster or a single-node cluster?

**Comment by clanstyles** [comment] 2017-03-14 20:28
Single node cluster and I can repeat it. Where do I run "COCKROACH_MEMPROF_INTERVAL=60s"

**Comment by petermattis** [comment] 2017-03-14 20:31
> I ran COCKROACH_MEMPROF_INTERVAL=60s cockroach start

Yep, that's correct. `COCKROACH_MEMPROF_INTERVAL` is an environment variable. The files will be output to `cockroach-data/logs`.

**Comment by clanstyles** [comment] 2017-03-15 17:29
Hey, I've been running it, it is growing but it's not at the same rate. I don't think I can reproduce it. I know I saw it.

The only things that were done.

1. New cluster
2. Create 2 databases and 3 tables
3. Let it sit idle. 

I can try to wipe the datastore and start fresh. I did have the Cluster dashboard running with the all time view, maybe something with dashboard analytics caused it? I'm not exactly sure.

**Comment by spencerkimball** [comment] 2017-03-15 17:43
@clanstyles keep in mind that an idle cluster still writes data in the form of periodic time series data. We currently keep 300+ time series, each updated on a 10s interval, one for each node. So an otherwise idle cluster will still be filling up whatever cache you designated for each node, which will look like unconstrained memory usage until you hit the cache limit.

Does this sound like it might explain what you previously saw?

**Comment by petermattis** [comment] 2017-03-15 17:45
@spencerkimball clanstyles logs show that the Go heap (not Cgo) was 24 GiB in size. This cannot be due to the time series data.

**Comment by spencerkimball** [comment] 2017-03-15 17:45
Ah, nevermind; I just read the rest of the bug report.

**Comment by petermattis** [comment] 2017-03-15 17:45
@clanstyles Thanks for the update. The cluster dashboard is an interesting clue. Perhaps try to start fresh and redo the same steps you did before. I'll also try running a cluster and leaving the dashboard open for a significant period of time.

**Comment by clanstyles** [comment] 2017-03-21 14:10
@petermattis I've been running the datastore since we last spoke locally. Without any data being in the store, it's using 6.5 GB. I have memprof running still and it's generated A LOT of them. How should I send you these? I don't think I can upload an archive this large to github.

This isn't the same memory leak I experienced earlier, but something funky is happening. There is currently a total of 4 records in 2 databases.

I did test some stuff earlier in the week bulk loading data into another database (emails) and then truncating them.

**Comment by bdarnell** [comment] 2017-03-21 15:33
6.5GB sounds like a normal result of the time-series processes @spencerkimball mentioned in https://github.com/cockroachdb/cockroach/issues/14143#issuecomment-286822791. I don't think we need to see the profiles from that, but if the 24+GB leak happens again, we'd like to see a few of the profiles. You don't need to send all of them, but at least send the last one and maybe a couple more earlier ones (before/during the growth) for comparison.

**Comment by dianasaur323** [comment] 2017-04-12 17:58
@clanstyles any update on if this is still an issue? We want to make sure to resolve any questions if you still have them.

**Comment by chandradeepak** [comment] 2017-04-13 21:55
@petermattis just to clarify the memory growth I had happened in my local mac also where i launched 3 nodes of cockroach db and let it sit idle.  But i dont have any dash board running . By dashboard you mean the UI page where we can see all the nodes . Is that the one. i dont have that running .

**Comment by petermattis** [comment] 2017-04-13 23:56
@chandradeepak Thanks for the additional info. I'm going to take another stab at reproducing this.

**Comment by petermattis** [comment] 2017-04-20 16:48
@chandradeepak An idle 3-node cluster on my machine shows memory growth, but purely in CGo memory usage and all of that growth is capped by the `--cache` setting (which defaults to 25% of physical memory per node). Can you still reproduce this? If yes, I'd love to see your debug logs and a heap profile.

**Comment by petermattis** [comment] 2017-04-24 00:20
Verified this one more time. An idle 3-node cluster configured with `--cache=256MiB` shows the following memory usage:

```
I170423 20:14:14.983565 32 server/status/runtime.go:225  [n1] runtime stats: 434 MiB RSS, 188 goroutines, 23 MiB/12 MiB/48 MiB GO alloc/idle/total, 304 MiB/397 MiB CGO alloc/total, 99.51cgo/sec, 0.02/0.00 %(u/s)time, 0.00 %gc (1x)
...
I170423 20:19:05.360369 129 server/status/runtime.go:225  [n2] runtime stats: 328 MiB RSS, 187 goroutines, 22 MiB/21 MiB/56 MiB GO alloc/idle/total, 202 MiB/274 MiB CGO alloc/total, 110.34cgo/sec, 0.03/0.00 %(u/s)time, 0.00 %gc (1x)
...
I170423 20:19:05.362250 64 server/status/runtime.go:225  [n3] runtime stats: 227 MiB RSS, 186 goroutines, 15 MiB/12 MiB/38 MiB GO alloc/idle/total, 127 MiB/187 MiB CGO alloc/total, 80.21cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (1x)
```

Notice that all of the memory is in CGO. The variation is likely due to `n1` being the leader for more ranges. I'm going to leave this running for longer. 

I'm also moving this issue to 1.1 milestone as there is nothing actionable to do at the moment.

**Comment by petermattis** [comment] 2017-07-18 14:18
Closing as unreproducible. #14512 tracks the issue of the RocksDB cache growing to fill configured space even on an idle cluster.

**Closed by petermattis** 2017-07-18 14:18 UTC
Labels: community-questions
