### ISSUE TITLE
Q: why not set a timezone ?

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#39316] opened 2019-08-05 04:05 UTC
re https://www.cockroachlabs.com/docs/v19.1/timestamp.html#variants

> Best practices
> We recommend always using the TIMESTAMPTZ variant because the TIMESTAMP variant can sometimes lead to unexpected behaviors when it ignores a session offset. However, we also recommend you avoid setting a session time for your database.

Re the last sentence, what harm will come from doing the following?

`SET TIME ZONE 'America/New_York';`

Why do you recommend avoiding it?  I searched around the docs, but could find no elaboration. If there is a discussion somewhere, please link to it from the warning.

**Comment by mattcrdb** [comment] 2019-08-05 14:18
Hey @glycerine ,

Different types and conversions have different, sometimes unexpected behaviors with respect to the session offset.

The reason we reccomend avoiding it is to to prevent these anomalies in behavior. 

Regarding `SET TIME ZONE 'America/New_York';`, It would be best to have your app choose how to localize the timestamp.

Unfortunately, there is no discussion.

I'm happy to continue the discussion here if you have any more questions.

Thanks,
Matt

**Comment by mattcrdb** [comment] 2019-08-12 17:30
Hi there,

I'm going to close this issue. 

If you have more questions, please reopen this issue.

Thanks,
Matt

**Closed by mattcrdb** 2019-08-12 17:30 UTC
Labels: O-community
