### ISSUE TITLE
Sentry: errors.go:90: referenced descriptor ID 255: descriptor not found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/in...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#106389] opened 2023-07-07 13:40 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4300194216/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4300194216/?referrer=webhooks_plugin)

Panic Message:

```
errors.go:90: referenced descriptor ID 255: descriptor not found
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.wrapError
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:173
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:277
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:340
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:406
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Schema
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:269
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:196
  | github.com/cockroachdb/cockroach/pkg/sql.maybeLookUpUDF
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:536
  | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:441
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1061
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:831
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:428
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:467
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:179
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/project.go:95
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectClause
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1120
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1057
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1026
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).processWiths
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/with.go:116
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildSelect
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/select.go:1025
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:332
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:272
  | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builder).Build
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/builder.go:246
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:576
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:240
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1978
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1484
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964
Wraps: (3) referenced descriptor ID 255
Wraps: (4) secondary error attachment
  | failed to find descriptor [255]
  | (1) attached stack trace
  |   -- stack trace:
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.requiredError
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:215
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.build
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:187
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:114
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogQuery.query
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_query.go:75
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader.go:277
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go:340
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorsByID
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:207
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.getDescriptorByName
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/descriptor.go:406
  |   | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.ByNameGetter.Schema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/getters.go:269
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).LookupSchema
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:196
  |   | github.com/cockroachdb/cockroach/pkg/sql.maybeLookUpUDF
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:536
  |   | github.com/cockroachdb/cockroach/pkg/sql.(*schemaResolver).ResolveFunction
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/schema_resolver.go:441
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/function_name.go:113
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).VisitPre
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:1061
  |   | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/walk.go:831
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).walkExprTree
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:428
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*scope).resolveType
  |   | 	github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder/scope.go:467
  |   | github.com/cockroachdb/cockroach/pkg/sql/opt/optbuilder.(*Builde...
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L963-L965)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1483-L1485)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/conn_executor_exec.go#L1977-L1979)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L575-L577](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/plan_opt.go#L575-L577)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L245-L247](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L245-L247)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L271-L273](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L271-L273)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L331-L333](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/builder.go#L331-L333)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1024-L1026](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1024-L1026)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/with.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/with.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1025-L1027](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1025-L1027)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1056-L1058](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1056-L1058)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1119-L1121](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/select.go#L1119-L1121)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/project.go#L94-L96](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/project.go#L94-L96)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/project.go#L178-L180](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/project.go#L178-L180)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L466-L468](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L466-L468)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L427-L429](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L427-L429)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/sem/tree/walk.go#L830-L832](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/sem/tree/walk.go#L830-L832)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L1060-L1062](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/opt/optbuilder/scope.go#L1060-L1062)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/sem/tree/function_name.go#L112-L114](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/sem/tree/function_name.go#L112-L114)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L440-L442](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L440-L442)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L535-L537](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L535-L537)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L195-L197](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/schema_resolver.go#L195-L197)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/getters.go#L268-L270](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/getters.go#L268-L270)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L405-L407](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L405-L407)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L206-L208](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/descs/descriptor.go#L206-L208)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L339-L341](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader_cached.go#L339-L341)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader.go#L276-L278](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_reader.go#L276-L278)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L74-L76)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L115-L117)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/internal/catkv/catalog_query.go#L172-L174)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[GOROOT/src/runtime/proc.go#L232-L234](GOROOT/src/runtime/proc.go#L232-L234)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6325-L6327](GOROOT/src/runtime/proc.go#L6325-L6327)
[GOROOT/src/runtime/proc.go#L6348-L6350](GOROOT/src/runtime/proc.go#L6348-L6350)
[https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/errors.go#L89-L91](https://github.com/cockroachdb/cockroach/blob/72556c6b5dc0d4ed1a0202bc4176586956d54739/pkg/sql/catalog/errors.go#L89-L91)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 964
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1484
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 1978
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 240
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 576
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).Build at line 246
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmtAtRoot at line 272
pkg/sql/opt/optbuilder/builder.go in pkg/sql/opt/optbuilder.(*Builder).buildStmt at line 332
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect at line 1025
pkg/sql/opt/optbuilder/with.go in pkg/sql/opt/optbuilder.(*Builder).processWiths at line 116
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelect.func1 at line 1026
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectStmtWithoutParens at line 1057
pkg/sql/opt/optbuilder/select.go in pkg/sql/opt/optbuilder.(*Builder).buildSelectClause at line 1120
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeProjectionList at line 95
pkg/sql/opt/optbuilder/project.go in pkg/sql/opt/optbuilder.(*Builder).analyzeSelectList at line 179
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).resolveType at line 467
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).walkExprTree at line 428
pkg/sql/sem/tree/walk.go in pkg/sql/sem/tree.WalkExpr at line 831
pkg/sql/opt/optbuilder/scope.go in pkg/sql/opt/optbuilder.(*scope).VisitPre at line 1061
pkg/sql/sem/tree/function_name.go in pkg/sql/sem/tree.(*ResolvableFunctionReference).Resolve at line 113
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).ResolveFunction at line 441
pkg/sql/schema_resolver.go in pkg/sql.maybeLookUpUDF at line 536
pkg/sql/schema_resolver.go in pkg/sql.(*schemaResolver).LookupSchema at line 196
pkg/sql/catalog/descs/getters.go in pkg/sql/catalog/descs.ByNameGetter.Schema at line 269
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorByName at line 406
pkg/sql/catalog/descs/descriptor.go in pkg/sql/catalog/descs.getDescriptorsByID at line 207
pkg/sql/catalog/internal/catkv/catalog_reader_cached.go in pkg/sql/catalog/internal/catkv.(*cachedCatalogReader).GetByIDs at line 340
pkg/sql/catalog/internal/catkv/catalog_reader.go in pkg/sql/catalog/internal/catkv.catalogReader.GetByIDs at line 277
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.query at line 75
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.catalogQuery.processDescriptorResultRow at line 116
pkg/sql/catalog/internal/catkv/catalog_query.go in pkg/sql/catalog/internal/catkv.wrapError at line 173
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
GOROOT/src/runtime/proc.go in runtime.main at line 233
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6326
GOROOT/src/runtime/proc.go in runtime.doInit at line 6349
pkg/sql/catalog/errors.go in pkg/sql/catalog.init at line 90
```

### Tags

| Tag | Value |
| --- | --- |
| Command | start-single-node |
| Environment | v23.1.5 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.5 |
| Cockroach SHA | 72556c6b5dc0d4ed1a0202bc4176586956d54739 |
| # of CPUs | 12 |
| # of Goroutines | 473 |

Jira issue: CRDB-29550

**Comment by msirek** [comment] 2023-07-07 17:10
dupe of #106389

**Closed by msirek** 2023-07-07 17:10 UTC
Labels: C-bug, O-sentry
