### ISSUE TITLE
ui: Replica count still shows for dead node

### ISSUE THREAD

**Issue by lhirata** [cockroachdb/cockroach#28211] opened 2018-08-02 17:38 UTC
**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?

v2.1.0-alpha.20180702

- What did you do?

I'm running through training docs where we we kill a node and [watch the cluster repair itself](https://www.cockroachlabs.com/docs/stable/training/fault-tolerance-and-automated-repair.html#step-6-watch-the-cluster-repair-itself). 

- What did you expect to see?

Previously, the tooltip would show the dead node 5 with 0 replicas. This is what I was expecting.

- What did you see instead?

The tooltip has the number of replicas node 5 had before it was killed.

<img width="1064" alt="screen shot 2018-08-02 at 1 31 10 pm" src="https://user-images.githubusercontent.com/15386648/43600675-3f9df288-9659-11e8-898f-bf91ca397a52.png">

- What was the impact?

It's confusing.

**Comment by piyush-singh** [comment] 2018-08-02 17:47
@couchand the linked docs correctly show the node in question having 0 replicas, but here we see the most recent non-0 data point. Did we change anything with our tooltips that would cause this behavior?

**Comment by couchand** [comment] 2018-08-02 17:51
Looks like this is a dupe of #23480.

**Closed by couchand** 2018-08-02 17:51 UTC
Labels: A-webui-timeseries, C-bug, X-duplicate
