### ISSUE TITLE
Disconnecting from server results in crash with "unexpected leftover bytes"

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#47114] opened 2020-04-07 06:58 UTC
When disconnecting from the server and reconnecting, the server crashed with the following stack trace:

```
*
* ERROR: [n1,client=127.0.0.1:36800,hostnossl,user=root] a SQL panic has occurred while executing "SELECT t0.c0 FROM t0, t2, t1": flow: unexpected 30720 leftover bytes
*
*
* ERROR: [n1,client=127.0.0.1:36800,hostnossl,user=root] a panic has occurred!
*
panic while executing 1 statements: SELECT _._ FROM _, _, _

goroutine 3475714 [running]:
runtime/debug.Stack(0x4b05500, 0xc011532bc0, 0x3)
	/usr/lib/go-1.13/src/runtime/debug/stack.go:24 +0x9d
github.com/cockroachdb/cockroach/pkg/util/log.ReportPanic(0x4b05500, 0xc011532bc0, 0xc00057aa80, 0x4049560, 0xc00a939c80, 0x1)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:218 +0xb5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0125a3000, 0x4b05500, 0xc011532bc0, 0x3bfa860, 0xc00f22d630)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:803 +0x348
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0125a3000, 0x4b05500, 0xc011532bc0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:474 +0x61
panic(0x3bfa860, 0xc00f22d630)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2
github.com/cockroachdb/cockroach/pkg/util/log.ReportOrPanic(0x4b05500, 0xc00d906040, 0xc00057aa80, 0xc008aefda0, 0x25, 0x0, 0x0, 0x0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/util/log/crash_reporting.go:550 +0x215
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc008d16c80, 0x4b05500, 0xc00d906040, 0xc005eae401)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:397 +0x29c
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*EvalContext).Stop(...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2933
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Cleanup(0xc008d2efc0, 0x4b05500, 0xc00d906040)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:423 +0x78
github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Cleanup(0xc011160cf0, 0x4b05500, 0xc00d906040)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:341 +0x1ea
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run.func8()
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:422 +0xcf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0125a3000, 0x4b055c0, 0xc006d67620, 0xc0125a33d0, 0x3, 0x7efd6aec84c8, 0xc013e88680, 0xc005eae801, 0xc00bc94958, 0x0, ...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:890 +0x554
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0125a3000, 0x4b055c0, 0xc006d67620, 0xc0125a33d0, 0x7efd6aec84c8, 0xc013e88680, 0x0, 0x0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:776 +0x6cd
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0125a3000, 0x4b055c0, 0xc006d67620, 0x4b1ee00, 0xc00a6f3590, 0xc00bd066bd, 0x20, 0x0, 0x3, 0xc00c18d6e0, ...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:481 +0xb06
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0125a3000, 0x4b055c0, 0xc006d67620, 0x4b1ee00, 0xc00a6f3590, 0xc00bd066bd, 0x20, 0x0, 0x3, 0xc00c18d6e0, ...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x4f6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0125a3000, 0x4b05500, 0xc011382880, 0x0, 0x0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1430 +0xed8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0125a3000, 0x4b05500, 0xc011532bc0, 0xc00029dc00, 0x5400, 0x15000, 0xc00029dc98, 0xc008996340, 0x0, 0x0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297 +0x1f2
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0010e0000, 0x4b05500, 0xc011532bc0, 0xc0125a3000, 0x5400, 0x15000, 0xc00029dc98, 0xc008996340, 0x0, 0x0)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476 +0x104
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc008ac1189, 0xc0182cb1c0, 0x4b05500, 0xc011532bc0, 0xc008996340, 0xc0010e0000, 0xc013e88000, 0x4b29140, 0xc00af68bd0, 0xc0074f7e60, ...)
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:594 +0x2e8
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/manuel/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:526 +0x17e
```

I haven't been able to reproduce the crash again (yet), but I thought that a stack trace might already be helpful to fix this. This happened based on commit 6365a3f21e467f3321068fa983d3999415a42609.

**Comment by yuzefovich** [comment] 2020-04-08 03:49
@mrigger do I understand the sequence of actions correctly?
1. start running the query via CLI
2. ctrl-c the connection to quit CLI
3. connect to CockroachDB again
4. CockroachDB crashes before any queries are issued

Also note that this wouldn't have been a crash with an "official" binary (we would report this problem as an error, and the node would keep on running).

**Comment by mrigger** [comment] 2020-04-08 06:47
Sorry for not being more specific. I was running SQLancer, which uses JDBC to connect to CockroachDB. I terminated SQLancer and started it again, which resulted in it being unable to connect. I then noticed that it crashed with the above error. I'm unsure whether the crash occurred when terminating SQLancer, or when reconnecting.

Since this explanation and the stack trace might be insufficient to reproduce the issue, feel free to close it.

**Comment by yuzefovich** [comment] 2020-04-08 14:41
I think I'll keep this issue open since it does indicate a problem with releasing the memory resources in our memory accounting system when shutting down the execution of a query via the vectorized engine. I briefly looked at the relevant code, and nothing wrong stood out to me.

It'd be great if you (or someone else) hit the same problem and was able to reliably reproduce it :)

**Comment by yuzefovich** [comment] 2021-05-12 02:23
Going to close this issue as unreproducible.

**Closed by yuzefovich** 2021-05-12 02:23 UTC
Labels: C-bug
