### ISSUE TITLE
Critical alert: replica inconsistency

### ISSUE THREAD

**Issue by dankinder** [cockroachdb/cockroach#85985] opened 2022-08-11 19:02 UTC
I was told to go ahead and create this in https://github.com/cockroachdb/cockroach/issues/85745

After upgrading to V22.1.5 I've had a few nodes go down with this error:
```
ERROR: startup forbidden by prior critical alert
DETAIL: From /srv/disk5/cockroach-data2/auxiliary/_CRITICAL_ALERT.txt:
ATTENTION:
this node is terminating because a replica inconsistency was detected between [n69,s413,r456341/79:/Table/75/2/"dlib.si"/"www"/"…]
and its other replicas. Please check your cluster-wide log files for more
information and contact the CockroachDB support team. It is not necessarily safe
to replace this node; cluster data may still be at risk of corruption.
A checkpoints directory to aid (expert) debugging should be present in:
/srv/disk5/cockroach-data2/auxiliary
A file preventing this node from restarting was placed at:
/srv/disk5/cockroach-data2/auxiliary/_CRITICAL_ALERT.txt
```

At first I left it alone for debugging but when another one went down I needed to make sure I have enough nodes in the cluster. It's happened to maybe 3 nodes now. Each one I decommed, wiped, and brought back into the cluster.

https://github.com/cockroachdb/cockroach/issues/85745 lists other things I'm seeing with this cluster that could be relevant, but it's hard to tell what's causing what.

Jira issue: CRDB-18512

**Comment by tbg** [comment] 2022-08-12 10:28
Hi Dan, the error you're seeing indicates that replicas in this cluster that should have been byte-by-byte identical have diverged. This is a serious issue, as it opens the door to many kinds of data inconsistencies in the cluster, both in internal data structures as well as in results returned to clients.

We don't see this kind of problem regularly on recent versions of CRDB (22.1.5 being recent), and when it occurs it is usually a problem with the file system used by the stores (for example, disabling fsync on zfs and then having a machine power-cycled), or use of the `kv.raft_log.disable_synchronization_unsafe`, or the copying around of store directories (which is only a safe operation under very limited circumstances).

Before we dig in further, could you confirm your environment is "sane" and you haven't done anything like I described above?

It would then be interesting to see the output of the consistency checker, i.e. the actual diff that was computed. Note that this contains information you may not want to share with the world, i.e. you will want to send it privately. Please email me at tobias@cockroachlabs.com so that I can get your email to set you up with a dropzone. Once you have that, you'll want to upload the `debug.zip` you mentioned on the other ticket. Of primary importance will be the logs, where I will be looking for lines like `====== diff` which print the actual diff; hopefully that will tell us something.

Generally though, you will likely want to replace this cluster. Replica consistency errors are akin to the file system having gone sideways - similar how you probably wouldn't want to trust a disk that failed, it is safer to switch to a new disk or at leas reformat, rather than trying to fix things in place, hoping to have found all of the fallout. But let's look at the diff too; just be advised that this is more to help us and less to help you, as there is very little hope to glean the root cause of the inconsistency from afar, especially since it occurred in the distant past at this point.

However, I will be able to check which ranges you've lost quorum on, and might advise use of tools to restore quorum so that you can at least backup-restore into a new cluster, or at least recreate the affected table(s).

**Comment by tbg** [comment] 2022-08-12 10:29
Just realized anyone can drop files here: https://upload.cockroachlabs.com/dropzone/tobias

So no need to email me, but do let me know when I should check the dropzone. Thanks!

**Comment by dankinder** [comment] 2022-08-12 16:11
Hi @tbg , thanks for the reply. I just uploaded that debug zip.

I can confirm that my environment is sane. Our file systems are all ext4 with no special settings, I didn't disable fsync, and `kv.raft_log.disable_synchronization_unsafe` is set to `f`. I haven't copied any store directories around.

The only other odd thing we did hit was this issue: https://www.cockroachlabs.com/docs/advisories/a82079.html after the upgrade I had to run that query to fix some tables.

Using tools to restore quorum on problematic ranges would be excellent, if there is a way. Luckily the data in this cluster for the most part is not very sensitive, if a bit of it were corrupt it wouldn't kill us. I'd rather risk that than have to restore to last backup.

**Comment by ajwerner** [comment] 2022-08-12 16:38
>The only other odd thing we did hit was this issue: [cockroachlabs.com/docs/advisories/a82079.html](https://www.cockroachlabs.com/docs/advisories/a82079.html) after the upgrade I had to run that query to fix some tables.

Those queries operate at the SQL metadata layer, they should not be able to induce any sort of corruption in the KV layer.

**Comment by dankinder** [comment] 2022-08-15 01:44
Yeah this cluster does not seem happy, I have another node crashing now with this message:
```
I220815 01:42:04.380656 188325 1@go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 178  the server is terminating due to a fatal error (see the DE
V channel for details)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179  2c state.commit 29157 is out of range [29173, 29185]
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !goroutine 188325 [running]:
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/log/get_stacks
.go:25 +0x8a
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).out
putLogEntry(0xc000fb0460, {{{0xc00427d200, 0x24}, {0x50510eb, 0x2}, {0x0, 0x0}, {0x0, 0x0}}, 0x170b612adf66d3d5, ...})
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/log/clog.go:23
7 +0xb8
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInter
nal({0x6355138, 0xc048fcfef0}, 0x3, 0x4, 0x0, 0x0, {0x4f4ed72, 0x2b}, {0xc02e3fe780, 0x4, ...})
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/log/channels.g
o:106 +0x645
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/log/channels.g
o:39
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/log.FatalfDepth(..
.)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pk
g/util/log/log_channels_generated.go:906
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftLogge
r).Panicf(0xc03b1e4e70, {0x4f4ed72, 0x2b}, {0xc02e3fe780, 0x4, 0x4})
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/raft.go:117 +0xcd
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !go.etcd.io/etcd/raft/v3.(*raft).loadState(0xc030d332c0, {0x3
, 0x4, 0x0})
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3
/raft.go:1700 +0x19a
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !go.etcd.io/etcd/raft/v3.newRaft(0xc024463328)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3
/raft.go:349 +0x6de
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !go.etcd.io/etcd/raft/v3.NewRawNode(0xc048fe7c00)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3
/rawnode.go:48 +0x1d
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).
withRaftGroupLocked(0xc048fe7c00, 0x0, 0xc0244638c0)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/replica_raft.go:1752 +0x1c9
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).
withRaftGroup(0xc048fe7c00, 0xc3, 0xeda8b9b6b)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/replica_raft.go:1818 +0x92
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).
stepRaftGroup(0x6355138, 0xc048fcff20)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/replica_raft.go:512 +0x45
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).pr
ocessRaftRequestWithReplica(0x3fc3333333333333, {0x6355138, 0xc048fcff20}, 0xc048fe7c00, 0xc08f57c700)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/store_raft.go:254 +0x38a
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).pr
ocessRequestQueue.func1({0xc048339d68, 0x6355138}, 0xc03170ba10)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/
kvserver/store_raft.go:459 +0x38
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).wi
thReplicaForRequest(0xc001de02c8, {0x6355138, 0xc03170ba10}, 0xc08f57c700, 0xc048339e28)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:213 +0x12e
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processRequestQueue(0xc001ddfb00, {0x6355138, 0xc03170ba10}, 0xc031c866b0)
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:457 +0x1e5
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).worker(0xc033fa0410, {0x6355138, 0xc03170ba10})
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:296 +0x1d2
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494 +0x16f
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:483 +0x445
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !For more context, check log files in: /var/log/cockroach2
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !****************************************************************************
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !This node experienced a fatal error (printed above), and as a result the
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !process is terminating.
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !problem in CockroachDB. With your help, the support team at Cockroach Labs
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !will try to determine the root cause, recommend next steps, and we can
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !improve CockroachDB based on your report.
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !Please submit a crash report by following the instructions here:
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    https://github.com/cockroachdb/cockroach/issues/new/choose
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !If you would rather not post publicly, please contact us directly at:
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !    support@cockroachlabs.com
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !
F220815 01:42:04.380738 188325 go.etcd.io/etcd/raft/v3/external/io_etcd_go_etcd_raft_v3/raft.go:1700 ⋮ [n78,s468,r2335433/44:‹/Table/75/2/"thuenen.de"/"www…›] 179 !The Cockroach Labs team appreciates your feedback.
```

**Comment by tbg** [comment] 2022-08-15 12:00
Thanks for the debug.zip, Dan. Unfortunately I wasn't able to find the information I was looking for - all SQL level debug information is missing, due to this error

> pq: Private key has world access. Permissions should be u=rw,g=r (0640) if owned by root, or u=rw (0600), or less

In particular, this prevents me from easily finding out about the loss of quorum. (But see the steps at the end of this issue, which also perform such analysis).

I also searched the log files you supplied for output from the replica consistency checker and found nothing. Clearly there is an inconsistency and the checker has posted output; but it's possible that all the nodes on which this output had occurred have been decommissioned and that their logs thus aren't included; or that they were down at the time in which case the `debug.zip` command cannot obtain their logs either.

That last message that you posted in particular

> state.commit 29157 is out of range [29173, 29185]

and the fact that I haven't seen a replica divergence in our enterprise customer base nor on our in-house cloud does strongly hint at some problem in your environment. Unfortunately, it is difficult to give good advice without spending a lot of time hands-on with the deployment to circle in. It is similarly difficult to try to patch things up in-place now that things have gone sideways to the degree that they have with apparently no end in sight.

The one tool that you could try to recover quorum is the `cockroach debug recover` family. It works in three steps and needs the cluster offline.

1. collect information from all stores:

https://github.com/cockroachdb/cockroach/blob/3f60a83985cb97caef4fe3a71d21b9704864ae94/pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go#L208

2. In a central location that has access to all of the files from the previous step:

https://github.com/cockroachdb/cockroach/blob/3f60a83985cb97caef4fe3a71d21b9704864ae94/pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go#L218

3. Assuming a plan is created successfully, roll out the plan on all stores:

https://github.com/cockroachdb/cockroach/blob/3f60a83985cb97caef4fe3a71d21b9704864ae94/pkg/cmd/roachtest/tests/loss_of_quorum_recovery.go#L232

I would say given the amount of issues you're seeing, probability of success is relatively low, but something might be learned. The tool does not make any changes to the cluster until step 3.

**Comment by dankinder** [comment] 2022-08-18 16:19
@tbg thanks, out of urgency I just opted for restore from backup. It's been painful too because the largest database (about 120TB) is failing to restore... nodes running out of mem and crashing, context cancelled timeouts, things like that. Still working on that.

**Comment by tbg** [comment] 2022-08-19 07:09
Thanks for the heads-up Dan, and sorry to hear about the trouble you've been having.
I'm going to close this out since the cluster is no longer around.

**Closed** 2022-08-19 07:09 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-kv-replication
