### ISSUE TITLE
No rows shown in Transaction Details page statement fingerprints table

### ISSUE THREAD

**Issue by jocrl** [cockroachdb/cockroach#74627] opened 2022-01-10 16:24 UTC
On cluster-ui in the Transactions Details page, no rows are shown in the table for statement fingerprints. Left over time, the page throws a front end error.

This is not a problem for db-console on master (commit `bd09cb7`), but reproduces on local cluster-ui pointing to staging on the same commit.

**To Reproduce**

e.g. https://management-staging.crdb.io/cluster/93c62a6b-5083-4376-9bac-3376c3e20d67/sql-activity?tab=Transactions&cluster-type=serverless&ascending=false&columnTitle=transactions

In managed-service, go to SQL Activity -> Transactions -> click on a transaction.

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/91907326/148795290-479cc4ee-237a-461a-8b28-c18b575c3351.png">

After waiting a while and coming back to the page, it shows the unexpected front end error graphic from a `statements` variable being null
<img width="499" alt="image" src="https://user-images.githubusercontent.com/91907326/148796345-3f1032e1-ec4b-4518-9ab3-b22b07141f64.png">
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/91907326/148796565-728086ff-19a0-4bae-b373-3eac0d623517.png">

**Environment:**
Managed-service 
- CockroachDB version: v21.2.3
 

Jira issue: CRDB-12179

**Comment by maryliag** [comment] 2022-05-25 14:18
might be related to https://github.com/cockroachdb/cockroach/issues/81470

Also another example:
![image (1)](https://user-images.githubusercontent.com/1017486/170284324-fa613e9c-5c5b-4cd3-a560-6e0ba0962554.png)

**Comment by xinhaoz** [comment] 2022-05-31 19:10
I am still unable to repro the empty stmt fingerprint list part of this bug. However, I can reliably reproduce the transaction details page crashing on 21.2.3. The two issues are unrelated, I can create a new issue for that specifically and release a fix.

**Comment by xinhaoz** [comment] 2022-06-02 18:49
Duplicate of https://github.com/cockroachdb/cockroach/issues/81470

**Closed by xinhaoz** 2022-06-02 18:49 UTC
Labels: C-bug, T-sql-observability, A-sql-console-general, A-sql-cli-observability
