### ISSUE TITLE
Test failure in CI build 9167

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3084] opened 2015-11-10 16:22 UTC
The following test appears to have failed:

[#9167](https://circleci.com/gh/cockroachdb/cockroach/9167):

```
W1110 16:22:48.286549 940 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
W1110 16:22:48.383856 940 multiraft/multiraft.go:1221  node 5 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 16:22:48.384016 940 multiraft/multiraft.go:1221  node 5 failed to send message to 6: multiraft/transport.go:132: transport is closed
W1110 16:22:48.386466 940 multiraft/multiraft.go:1221  node 6 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 16:22:48.386595 940 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
--- FAIL: TestSplitSnapshotRace_SnapshotWins (37.45s)
	<autogenerated>:32: storage/client_split_test.go:778: condition failed to evaluate within 3s: storage/client_test.go:559: expected [0 11 11 11 0 0], got [0 11 11 1 0 0]
	client_test.go:270: timed out during shutdown
=== RUN   Example_rebalancing
W1110 16:22:48.486919 940 multiraft/multiraft.go:1221  node 5 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 16:22:48.487072 940 multiraft/multiraft.go:1221  node 5 failed to send message to 6: multiraft/transport.go:132: transport is closed
W1110 16:22:48.489912 940 multiraft/multiraft.go:1221  node 6 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 16:22:48.490032 940 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
I1110 16:22:48.491241 940 raft/raft.go:488  [group 11] 5 is starting a new election at term 93
I1110 16:22:48.491345 940 raft/raft.go:422  [group 11] 5 became candidate at term 94
I1110 16:22:48.491418 940 raft/raft.go:471  [group 11] 5 received vote from 5 at term 94
--
I1110 16:22:49.102875 940 raft/raft.go:464  [group 11] 5 [logterm: 7, index: 28] sent vote request to 1 at term 96
I1110 16:22:49.103107 940 raft/raft.go:464  [group 11] 5 [logterm: 7, index: 28] sent vote request to 4 at term 96
W1110 16:22:49.107977 940 multiraft/multiraft.go:1221  node 6 failed to send message to 4: multiraft/transport.go:132: transport is closed
W1110 16:22:49.108134 940 multiraft/multiraft.go:1221  node 6 failed to send message to 5: multiraft/transport.go:132: transport is closed
--- PASS: Example_rebalancing (0.68s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	66.742s
=== RUN   TestBatchBasics
I1110 16:21:43.999923 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1110 16:21:44.003878 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1110 16:21:44.009487 945 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-11-10 16:23
Duplicate of #3038

**Closed by bdarnell** 2015-11-10 16:23 UTC
Labels: test-failure
