### ISSUE TITLE
sql: poor index selection

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#19817] opened 2017-11-06 07:23 UTC
On version CockroachDB CCL v1.2-alpha.20170901-1172-g99a04b6 (linux amd64, built 2017/10/29 21:59:18, go1.9). For the table:

```
CREATE TABLE players (
	game INT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	map INT NULL,
	length INT NULL,
	build INT NULL,
	hero INT NULL,
	hero_level INT NULL,
	team INT NULL,
	winner BOOL NULL,
	blizzid INT NULL,
	skill INT NULL,
	battletag STRING NULL,
	talents INT[] NULL,
	INDEX players_game_idx (game ASC),
	INDEX players_blizzid_time_idx (blizzid ASC, "time" DESC),
	INDEX players_battletag_idx (battletag ASC),
	INDEX players_build_map_mode_hero_level_idx (build ASC, map ASC, mode ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_map_hero_level_idx (build ASC, map ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_mode_hero_level_idx (build ASC, mode ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_hero_level_idx (build ASC, hero_level ASC) STORING (hero, winner),
	INDEX players_build_hero_idx (build ASC, hero ASC) STORING (winner, hero_level, length, map, mode),
	INDEX players_build_hero_map_mode_hero_level_idx (build ASC, hero ASC, map ASC, mode ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_map_hero_level_idx (build ASC, hero ASC, map ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_mode_hero_level_idx (build ASC, hero ASC, mode ASC, hero_level ASC) STORING (winner, talents),
	INDEX players_build_hero_hero_level_idx (build ASC, hero ASC, hero_level ASC) STORING (winner, talents),
	FAMILY "primary" (game, mode, "time", map, length, build, hero, hero_level, team, winner, blizzid, skill, battletag, talents, rowid)
)
```

The query:

```
SELECT game, team, winner
FROM players
WHERE build = $1 AND hero = $2 AND map = $3 AND mode = $4 AND hero_level >= $5
```

With parameters: `3, 51, 4, 1, 5`

Produced the plan:

```
EXPLAIN [0 render  ]
EXPLAIN [1 index-join  ]
EXPLAIN [2 scan  ]
EXPLAIN [2  table players@players_build_hero_hero_level_idx]
EXPLAIN [2  spans /3/51/5-/3/52]
EXPLAIN [2 scan  ]
EXPLAIN [2  table players@primary]
```

The explain says it used the players_build_hero_hero_level_idx index, however I would have expected  players_build_hero_map_mode_hero_level_idx to be used since it has all of the columns in the WHERE clause and identical STORING columns.

**Comment by justinj** [comment] 2017-11-07 02:01
How big is the table? Possibly related to #15649?

**Comment by mjibson** [comment] 2017-11-07 03:50
Seems like it's the same thing, yes.

**Comment by petermattis** [comment] 2018-02-21 14:50
Cc @andy-kimball, @RaduBerinde, @rytaft

**Comment by jordanlewis** [comment] 2018-04-27 22:28
Closing as dupe of the above linked issue.

**Closed by jordanlewis** 2018-04-27 22:28 UTC
