### ISSUE TITLE
Insertion of array type column does not work on npgsql.

### ISSUE THREAD

**Issue by rkdrnfds** [cockroachdb/cockroach#24055] opened 2018-03-20 03:01 UTC
When do array type column insertion via Npgsql, it does not work properly.

There's ongoing issue opened at npgsql github with full description of the problem, so I'm linking the issus so you may look at it.

https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/309

**Comment by jordanlewis** [comment] 2018-03-20 17:22
Hi @rkdrnfds, thanks for the report. We're not experts at `npgsql` so we might need a little bit of help getting to the bottom of this. Could you please provide a fully working reproduction example?

**Comment by justinj** [comment] 2018-03-20 17:23
Could you also try on the newest beta? I suspect this might have been fixed by #23467.

**Comment by rkdrnfds** [comment] 2018-03-23 05:25
I created repro github for this issue.
[repro github](https://github.com/rkdrnfds/array-example)

you can test it by manually creating database with table as below
which connects from program by connection string specified in `MyDbContext.cs`

table DDL:
```
CREATE TABLE "Chunks" (
	"Id" INT NOT NULL DEFAULT unique_rowid(),
	CONSTRAINT "PK_Chunks" PRIMARY KEY ("Id" ASC),
	FAMILY "primary" ("Id")
)
```

I tested it in both 
`v2.0-alpha.20180129` and
`v2.0-beta.20180319`

`0129 alpha` reproduces exact error.

but `0319 beta` produces other errors during migration though EF core and inserting `int` type
which I mentioned in other issues. so it just crashes before checking array type.

I'm linking those additional beta version issues here so you can check it.
When doing migration through EF Core:
 While creating database by EF Core Cli Command:
https://github.com/cockroachdb/cockroach/issues/24173
After created database manually:
https://github.com/cockroachdb/cockroach/issues/24172

**Comment by jordanlewis** [comment] 2018-03-23 17:31
Thanks for the report. I can reproduce the issue you're seeing. I think the problem is that the .NET driver sends arrays of `int4`, which we don't properly handle today. The following diff fixes it:

```
diff --git a/pkg/sql/sqlbase/structured.go b/pkg/sql/sqlbase/structured.go
index c4683cf0b..8fcdd2b70 100644
--- a/pkg/sql/sqlbase/structured.go
+++ b/pkg/sql/sqlbase/structured.go
@@ -2277,7 +2277,10 @@ func DatumTypeToColumnSemanticType(ptyp types.T) (ColumnType_SemanticType, error
                if ptyp.FamilyEqual(types.FamCollatedString) {
                        return ColumnType_COLLATEDSTRING, nil
                }
-               return -1, pgerror.NewErrorf(pgerror.CodeFeatureNotSupportedError, "unsupported result type: %s", ptyp)
+               if wrapper, ok := ptyp.(types.TOidWrapper); ok {
+                       return DatumTypeToColumnSemanticType(wrapper.T)
+               }
+               return -1, pgerror.NewErrorf(pgerror.CodeFeatureNotSupportedError, "unsupported result type: %s, %T, %+v", ptyp, ptyp, ptyp)
        }
 }

diff --git a/pkg/sql/sqlbase/table.go b/pkg/sql/sqlbase/table.go
index 2bf7536b5..12a53d53a 100644
--- a/pkg/sql/sqlbase/table.go
+++ b/pkg/sql/sqlbase/table.go
@@ -1922,7 +1922,8 @@ func encodeArray(d *tree.DArray, scratch []byte) ([]byte, error) {
                return scratch, err
        }
        scratch = scratch[0:0]
-       elementType, err := parserTypeToEncodingType(d.ParamTyp)
+       unwrapped := types.UnwrapType(d.ParamTyp)
+       elementType, err := parserTypeToEncodingType(unwrapped)
        if err != nil {
                return nil, err
        }
```

but it needs some more testing.

**Closed** 2018-03-29 15:05 UTC
