### ISSUE TITLE
ui: tooltip measurement values gone when hovering over (some) stats

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5499] opened 2016-03-23 14:02 UTC
<img width="285" alt="screen shot 2016-03-23 at 10 02 06 am" src="https://cloud.githubusercontent.com/assets/5076964/13987527/5c66106c-f0de-11e5-976e-ca0bb7f1b592.png">

They show up sporadically in this graph, but very rarely so. I'd expect there to be a measurement for every cursor position.

**Comment by cuongdo** [comment] 2016-03-23 19:50
I don't know where to begin with this one, so reassigning.

**Comment by maxlang** [comment] 2016-03-23 19:51
Dupe of https://github.com/cockroachdb/cockroach/issues/5486

**Closed by maxlang** 2016-03-23 19:51 UTC
