### ISSUE TITLE
Test failure in CI build 9850

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3320] opened 2015-12-03 22:45 UTC
The following test appears to have failed:

[#9850](https://circleci.com/gh/cockroachdb/cockroach/9850):

```
E1203 22:45:19.789158 1024 client/txn.go:308  failure aborting transaction: kv/txn_coord_sender.go:377: transaction is already committed or aborted; abort caused by: node unavailable; try another peer
W1203 22:45:19.789544 1024 kv/dist_sender.go:568  failed to invoke AdminSplit [/Table/1001,/Min): storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
I1203 22:45:19.789832 1024 client/db.go:483  failed batch: storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
E1203 22:45:19.790077 1024 storage/queue.go:374  failure processing replica range=1 [/Min-/Table/1000) from split queue: storage/split_queue.go:101: unable to split range=1 [/Min-/Table/1000) at key "/Table/1001": storage/replica_command.go:1326: split at key /Table/1001 failed: node unavailable; try another peer
I1203 22:45:19.790968 1024 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestStoreRangeSystemSplits (46.81s)
	<autogenerated>:32: storage/client_split_test.go:609: condition failed to evaluate within 5s: storage/client_split_test.go:603: expected split keys:
		[/System/Meta2/"\xff\f\x03\xe8" /System/Meta2/"\xff\f\x03\xe9" /System/Meta2/"\xff\f\x03\xea" /System/Meta2/"\xff\f\x03\xeb" /System/Meta2/"\xff\f\x03\xec" /System/Meta2/"\xff\f\x03\xed" /System/Meta2/"\xff\f\x03\xee" /System/Meta2/"\xff\f\x03\xef" /System/Meta2/"\xff\f\x03\xf0" /System/Meta2/"\xff\f\x03\xf1" /System/Meta2/"\xff\f\x03\xf2" /System/Meta2/"\xff\f\x03\xf3" /System/Meta2/"\xff\f\x03\xf4" /System/Meta2/"\xff\xff"]
		but found:
		[/System/Meta2/"\xff\f\x03\xe8" /System/Meta2/"\xff\xff"]
=== RUN   TestSplitSnapshotRace_SplitWins
I1203 22:45:19.795399 1024 multiraft/multiraft.go:579  node 1 starting
I1203 22:45:19.795732 1024 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1203 22:45:19.797506 1024 raft/raft.go:441  [group 1] 1 became follower at term 5
I1203 22:45:19.797730 1024 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1203 22:45:19.797858 1024 multiraft/multiraft.go:999  node 1 campaigning because initial confstate is [1]
--
I1203 22:45:22.362500 1024 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1203 22:45:22.362672 1024 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.37s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.41s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	77.812s
=== RUN   TestBatchBasics
I1203 22:44:07.064036 1032 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1203 22:44:07.068242 1032 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1203 22:44:07.084063 1032 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-12-03 22:58
Dupe of #3227.(this build was right before the fix for that issue was merged)

**Closed by bdarnell** 2015-12-03 22:58 UTC
Labels: test-failure

**Comment by tschottdorf** [comment] 2015-12-03 23:00
Good. Was worried for a second there.
