### ISSUE TITLE
replication: TestReplicaRemovalClosesProposalQuota is flakey

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#98412] opened 2023-03-10 21:06 UTC
According to [CI history](https://teamcity.cockroachdb.com/project.html?tab=testDetails&projectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&testNameId=-252657031523786530&page=2), this test gets ignored the vast majority of the time, but when it does run, it fails every time. Going to skip.

Jira issue: CRDB-25251

**Comment by erikgrinaker** [comment] 2023-03-13 14:01
@pavelkalinnikov Can you have a look at this?

**Comment by pavelkalinnikov** [comment] 2023-03-13 22:13
Reproduces under `--stress`:

```
    client_raft_test.go:5629: the replica is not the leaseholder, this happens rarely under stressrace
    testcluster.go:182: condition failed to evaluate within 45s: unexpectedly found 6 active spans:
...

```

**Comment by pavelkalinnikov** [comment] 2023-03-13 22:17
So we're calling [IgnoreLint](https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvserver/client_raft_test.go#L5629), and then the teardown of the test in `TestCluster.stopServers` fails on some conditions.

**Comment by erikgrinaker** [comment] 2023-03-14 08:47
Thanks. This doesn't seem like a critical test. Can we attempt to either deflake it, simplify the test, or remove it?

**Comment by tbg** [comment] 2023-03-14 10:18
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/96932#issuecomment-1438049175, where I investigated already.

**Closed** 2023-03-14 10:19 UTC
Labels: C-test-failure, branch-master, skipped-test, GA-blocker, T-kv-replication, branch-release-23.1
