### ISSUE TITLE
ui: darken axis tick labels

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#16821] opened 2017-06-30 17:15 UTC
I seem to remember seeing an issue related to this, but can't find it.

![image](https://user-images.githubusercontent.com/5768024/27746652-0aa714f8-5d96-11e7-8aea-6a4e3be8c374.png)

This graph with non-integer # of nodes doesn't seem to make much sense. 

Could we also make these labels on the vertical axis darker? I could barely see them on my laptop.

![image](https://user-images.githubusercontent.com/5768024/27746687-32a09c18-5d96-11e7-8072-90f79e6c8d17.png)

**Comment by couchand** [comment] 2017-12-11 18:28
The point about the non-integer node count values is a duplicate of #12973.

Let's make this issue just a design question on the color of the axis tick labels.

**Closed** 2017-12-18 19:07 UTC
Labels: cleanup, good first issue
