### ISSUE TITLE
sql: libpq crashes when using Query to run a statement.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#3821] opened 2016-01-14 00:46 UTC
eg: the following testdata sample:
```
query T colnames
SET DATABASE = foo
----
```

This crashes with:
```
goroutine 21 [running]:
testing.tRunner.func1(0xc820135170)
        /usr/local/go/src/testing/testing.go:450 +0x171
github.com/cockroachdb/cockroach/util/leaktest.AfterTest(0x7f56ac9bedb0, 0xc820135170)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:115 +0x194
github.com/lib/pq.(*rows).Next(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/lib/pq/conn.go:1348 +0x5d
github.com/lib/pq.(*rows).Close(0x0, 0x0, 0x0)
        /home/marc/cockroach/src/github.com/lib/pq/conn.go:1332 +0x42
database/sql.(*Rows).Close(0xc8206d7e60, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1710 +0x92
github.com/lib/pq.(*rows).Columns(0x0, 0xc82020c6e0, 0xc820b43ce0, 0x12)
        /home/marc/cockroach/src/github.com/lib/pq/conn.go:1344 +0x29
database/sql.(*Rows).Columns(0xc8206d7e60, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/database/sql/sql.go:1666 +0x248
github.com/cockroachdb/cockroach/sql_test.(*logicTest).execQuery(0xc820cfbea0, 0xc820719fb0, 0xf, 0xc8
20b43ce0, 0x12, 0x1, 0xc820719f86, 0x1, 0x0, 0x0, ...)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/logic_test.go:491 +0x2a2
github.com/cockroachdb/cockroach/sql_test.(*logicTest).run(0xc820cfbea0, 0xc8201f9dd0, 0xc)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/logic_test.go:395 +0x1593
github.com/cockroachdb/cockroach/sql_test.TestLogic(0xc820135170)
        /home/marc/cockroach/src/github.com/cockroachdb/cockroach/sql/logic_test.go:682 +0x8ee
testing.tRunner(0xc820135170, 0x1e0c330)
        /usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
        /usr/local/go/src/testing/testing.go:561 +0x86d
```

If we can detect that on the server-side, we may be able to return 0 rows as opposed to no row info. Not sure if that's doable, or even desirable.

**Comment by tamird** [comment] 2016-01-14 20:06
I can't reproduce this. I've applied this diff:
```diff
diff --git a/sql/testdata/set b/sql/testdata/set
index fb13828..9f9d5f1 100644
--- a/sql/testdata/set
+++ b/sql/testdata/set
@@ -94,3 +94,8 @@ SHOW SYNTAX
 ----
 SYNTAX
 Modern
+
+# https://github.com/cockroachdb/cockroach/issues/3821
+query T
+SET DATABASE = foo
+----

```
and I get this result:
```
logic_test.go:489: /Users/tamird/src/go/src/github.com/cockroachdb/cockroach/sql/testdata/set:99: expected 1 columns based on type-string, but found 0
```

Closing, but feel free to reopen.

**Closed by tamird** 2016-01-14 20:06 UTC
