### ISSUE TITLE
circleci: failed tests (15589): TestGossipRestart

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5738] opened 2016-03-30 21:00 UTC
The following test appears to have failed:

[#15589](https://circleci.com/gh/cockroachdb/cockroach/15589):

```
I160330 21:00:47.350187 acceptance/replication_test.go:50  waiting for first range to have 3 replicas
I160330 21:00:48.351545 acceptance/replication_test.go:66  found 3 replicas
I160330 21:00:48.351576 acceptance/replication_test.go:74  found 3 replicas
I160330 21:00:48.351672 acceptance/gossip_peerings_test.go:170  waiting for initial gossip connections
I160330 21:00:51.406314 acceptance/gossip_peerings_test.go:175  killing all nodes
panic: test timed out after 5m0s

goroutine 1255 [running]:
panic(0x11e4bc0, 0xc820601120)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x17b92c0, 0x1e51dc0, 0x12, 0x12, 0x9a557a81c8bdf201)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8200cdef8, 0x17b7200)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc8200cdef8)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:86 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [select, 4 minutes, locked to thread]:
runtime.gopark(0x17b9af8, 0xc820027f28, 0x14f95a8, 0x6, 0xc820134018, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820027f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820027f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x2128260)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:993 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:594 +0x8a

goroutine 21 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 1161 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x7fd2d2f7f4a0, 0xc8205afaa0, 0x7fd2d2f7e1b8, 0xc8226333e0, 0xc820622540, 0xc8205afad0, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x49d
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc828d79140, 0x7fd2d2f7f4a0, 0xc8205afaa0, 0x14f28e0, 0x4, 0xc8205b1ec0, 0x51, 0xc8205afad0, 0x7fd2d2f7b6c0, 0xc820620620, ...)
	/go/src/github.com/docker/engine-api/client/request.go:93 +0x45a
github.com/docker/engine-api/client.(*Client).sendRequest(0xc828d79140, 0x7fd2d2f7f4a0, 0xc8205afaa0, 0x14f28e0, 0x4, 0xc8205b1ec0, 0x51, 0xc8205afad0, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:71 +0x2b1
github.com/docker/engine-api/client.(*Client).post(0xc828d79140, 0x7fd2d2f7f4a0, 0xc8205afaa0, 0xc8205b1ec0, 0x51, 0xc8205afad0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:36 +0xb4
github.com/docker/engine-api/client.(*Client).ContainerKill(0xc828d79140, 0x7fd2d2f7f4a0, 0xc8205afaa0, 0xc82c9f7e40, 0x40, 0x14efff8, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/container_kill.go:14 +0x1ff
--
testing.tRunner(0xc82262e870, 0x1e51e68)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 564 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82016e6e0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 26 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fd2d2f7f238, 0x72, 0xc82025d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82025a4c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82025a4c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82025a460, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120390, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82025e410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 27 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc82025e410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 363 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fd2d2f7eff8, 0x72, 0xc8203f9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82037c3e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82037c3e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82037c380, 0xc8203f9000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120238, 0xc8203f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201fa340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1240 [IO wait]:
net.runtime_pollWait(0x7fd2d2fc1358, 0x72, 0xc820559000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8294f5410, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8294f5410, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8294f53b0, 0xc820559000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120d30, 0xc820559000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82a636f70)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 275 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fd2d2f7ee78, 0x72, 0xc820447000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82040d1e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82040d1e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82040d180, 0xc820447000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a250, 0xc820447000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060820)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 276 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820060820)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1241 [select]:
net/http.(*persistConn).writeLoop(0xc82a636f70)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1024 [IO wait]:
net.runtime_pollWait(0x7fd2d2fc1ad8, 0x72, 0xc827f5e000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82a7f66f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82a7f66f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82a7f6690, 0xc827f5e000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002ab68, 0xc827f5e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82cc509c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 755 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820233d90)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 856 [IO wait]:
net.runtime_pollWait(0x7fd2d2fc1958, 0x72, 0xc82a162000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8217d9950, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8217d9950, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8217d98f0, 0xc82a162000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120590, 0xc82a162000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82179a750)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 741 [chan receive]:
database/sql.(*DB).connectionOpener(0xc826c924d0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 561 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82034b760)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 686 [IO wait]:
net.runtime_pollWait(0x7fd2d2f7f178, 0x72, 0xc820371000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200d4ed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200d4ed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200d4e70, 0xc820371000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201203b8, 0xc820371000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820132a90)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 364 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8201fa340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1184 [select]:
net/http.(*persistConn).writeLoop(0xc82a6361a0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 165 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fd2d2f7f0b8, 0x72, 0xc82044b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82037c220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82037c220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82037c1c0, 0xc82044b000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a028, 0xc82044b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200604e0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 166 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8200604e0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 857 [select]:
net/http.(*persistConn).writeLoop(0xc82179a750)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 469 [select]:
net/http.(*persistConn).writeLoop(0xc8201fa750)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 522 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82034a0b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 538 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc8202320b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 468 [IO wait]:
net.runtime_pollWait(0x7fd2d2f7ef38, 0x72, 0xc8204b5000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82037cca0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82037cca0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82037cc40, 0xc8204b5000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201202d0, 0xc8204b5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201fa750)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 525 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82034ad10)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1025 [select]:
net/http.(*persistConn).writeLoop(0xc82cc509c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 529 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82034af20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 687 [select]:
net/http.(*persistConn).writeLoop(0xc820132a90)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1164 [IO wait]:
net.runtime_pollWait(0x7fd2cd4e64a0, 0x72, 0xc82a73a000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82262b9c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82262b9c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82262b960, 0xc82a73a000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002ad68, 0xc82a73a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82c9d2a90)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1165 [select]:
net/http.(*persistConn).writeLoop(0xc82c9d2a90)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1189 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7fd2d2f8ae88, 0xc829461840, 0xc828d73930, 0xc82946ec60)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xef
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336

goroutine 1221 [IO wait]:
net.runtime_pollWait(0x7fd2cd4e63e0, 0x72, 0xc82056f000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8294f59c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8294f59c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8294f5960, 0xc82056f000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120d50, 0xc82056f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82a637380)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1183 [select]:
net/http.(*persistConn).readLoop(0xc82a6361a0)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1187 [IO wait]:
net.runtime_pollWait(0x7fd2cd4e6560, 0x72, 0xc829478000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82a632ed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82a632ed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82a632e70, 0xc829478000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120cb0, 0xc829478000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc82c9d28f0)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:568 +0xd1
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:592 +0x731

goroutine 1234 [IO wait]:
net.runtime_pollWait(0x7fd2d2fc1298, 0x72, 0xc82054a000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8294f4e60, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8294f4e60, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8294f4e00, 0xc82054a000, 0x1000, 0x1000, 0x0, 0x7fd2d2fb5050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820120d10, 0xc82054a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82a636b60)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1235 [select]:
net/http.(*persistConn).writeLoop(0xc82a636b60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1222 [select]:
net/http.(*persistConn).writeLoop(0xc82a637380)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1268 [select]:
net/http.(*persistConn).roundTrip(0xc82c9d2a90, 0xc820636840, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc82ca04540, 0xc820622540, 0xc82ca04540, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc820622540, 0x7fd2d2fb9820, 0xc82ca04540, 0x0, 0x0, 0x0, 0xc82061e400, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82ca09230, 0xc820622540, 0x0, 0x0, 0x0, 0x2, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82ca09230, 0xc820622540, 0x17b9668, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-30 21:20
Docker flakiness. Duplicate of #5732.

**Closed by petermattis** 2016-03-30 21:20 UTC
Labels: Robot, test-failure

**Comment by RoachietheSupportRoach** [comment] 2019-11-05 18:27
Zendesk ticket #[4034](https://cockroachdb.zendesk.com/agent/tickets/4034) has been linked to this issue.
