### ISSUE TITLE
sql: evaluate sql.txn_stats.sample_rate default

### ISSUE THREAD

**Issue by asubiotto** [cockroachdb/cockroach#59379] opened 2021-01-25 15:49 UTC
https://github.com/cockroachdb/cockroach/pull/59132 adds the `sql.txn_stats.sample_rate` cluster setting. The default setting is 0, which means never sample stats. However, we're soon going to change the DB Console page to show these sampled execution stats, which means that this setting has to be nonzero to show interesting information.

This issue tracks quantifying the performance effect of turning this setting up to always sample and seeing if it is realistic to remove this setting at all. If not, we might want to have a low but nonzero sample rate to provide some interesting data.

**Comment by yuzefovich** [comment] 2021-02-24 18:43
Taking this over.

**Comment by yuzefovich** [comment] 2021-02-24 21:53
Initial benchmarks suggest that using a sample rate of 0.5 or 1 has significant performance hit (on the order of 20%) on KV95 workload with 1 min ramp and 5 min duration on 3 node roachprod cluster:
- GCE:
  - sample_rate=0: 8584.3
  - sample_rate=0.5: 7777.8, **-9.4%**
  - sample_rate=1: 7120.9, **-17.0%**
- AWS:
  - sample_rate=0: 10485.8
  - sample_rate=0.5: 8934.1, **-14.8%**
  - sample_rate=1: 8237.3, **-21.4%**

Initial look at the profile suggests that `crdbSpan.getRecording` is to blame (the profile is over 30s):
![Screen Shot 2021-02-24 at 1 37 07 PM](https://user-images.githubusercontent.com/5135385/109070671-a4b6ee00-76a7-11eb-9ff8-c03029920439.png)

**Comment by yuzefovich** [comment] 2021-02-24 22:03
Looks like there are two main time usages there:
- assigning an entry to `tracingpb.RecordedSpan.Tags` map:
```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).getRecordingLocked.func1 in /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go
         0      560ms (flat, cum)  0.98% of Total
         .          .    278:		rs.Finished = true
         .          .    279:	}
         .          .    280:
         .          .    281:	addTag := func(k, v string) {
         .          .    282:		if rs.Tags == nil {
         .       50ms    283:			rs.Tags = make(map[string]string)
         .          .    284:		}
         .      510ms    285:		rs.Tags[k] = v
         .          .    286:	}
```
- calling `tag.ValueStr()`
It is possible that this comment is relevant:
```
ROUTINE ======================== github.com/cockroachdb/redact.StringWithoutMarkers in /go/src/github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/redact/markers_print.go
      40ms      1.97s (flat, cum)  3.44% of Total
         .          .     91:// Note: if this function is ever found to be a performance
         .          .     92:// bottleneck, one can consider using an alternate implementation of
         .          .     93:// Sprint() which similarly calls the SafeFormat() methods but does
         .          .     94:// not introduce markers and instead writes to a string buffer
         .          .     95:// directly.
      10ms       10ms     96:func StringWithoutMarkers(f SafeFormatter) string {
      30ms      1.96s     97:	return Sprint(f).StripMarkers()
         .          .     98:}
```
that is being called by
```
         .          .     36:// String returns the node ID, or "?" if it is unset.
         .          .     37:func (n *NodeIDContainer) String() string {
      10ms      1.98s     38:	return redact.StringWithoutMarkers(n)
```

**Comment by tbg** [comment] 2021-02-25 08:21
1) you're not accidentally starting verbose spans, right? Just to double check
2) I don't see why any tags would need to be added to the span. Tags are slow! I see code like this

https://github.com/cockroachdb/cockroach/blob/5fd21c24926fd0da43f74f21e5175eb59acd1c12/pkg/sql/flowinfra/outbox.go#L221-L225

which makes it seem as though tags are somehow used to transport stats, which is not a good idea in the hot path. I think this is legacy code, but see if things like that are the problem.

3) do you see a similar slowdown in one of the in-process tests? It will be much more pleasant to iterate in a local setup.

**Comment by tbg** [comment] 2021-02-25 10:33
I couldn't really see the same kind of drop on a local three node roachprod cluster running stock `kv95`, but I do see that https://github.com/cockroachdb/cockroach/pull/61116 removes the stringification of tags completely (as intended). Try with that PR and see if that helps.

**Comment by tbg** [comment] 2021-02-25 10:37
Resulting flame graph (bit confusing thanks to recursion, but you get the idea)

![image](https://user-images.githubusercontent.com/5076964/109141294-dee2c700-775d-11eb-8f3c-08518639c631.png)

**Comment by tbg** [comment] 2021-02-25 11:02
This seems unnecessary - the spanstats put tags in the span:

![image](https://user-images.githubusercontent.com/5076964/109143214-0e92ce80-7760-11eb-8273-ac3b5a466504.png)

**Comment by tbg** [comment] 2021-02-25 11:05
^-- the CPU slice here isn't maybe all that big altogether, but the allocs I think are substantial:

![image](https://user-images.githubusercontent.com/5076964/109144651-bc52ad00-7761-11eb-811c-6c8cff48513e.png)

**Comment by asubiotto** [comment] 2021-02-25 13:25
Yeah, we've moved away from using tags in the spans (in favor of `ComponentID`s in the `ComponentStats` proto) so we can probably remove that behavior.

**Comment by yuzefovich** [comment] 2021-02-26 02:17
Thanks for looking into this Tobi!

Replying to your questions from https://github.com/cockroachdb/cockroach/issues/59379#issuecomment-785711416.
> 1. you're not accidentally starting verbose spans, right? Just to double check

I don't think so, we only use verbose spans when the tracing is enabled for the whole session or with EXPLAIN ANALYZE. I hope I'm not reading the code wrong here. Confirmed manually on my laptop that `SetVerbose` is not being called when we start sampling.
> 2. I don't see why any tags would need to be added to the span. Tags are slow! I see code like this

Ack. The code you linked gets executed only is the verbose tracing is enabled. I did find a few thing (#61158) where we would be setting tags in non-verbose tracing. Rerunning my benchmarks with both #61116 and #61158 cherry-picked, and I see an improvement, but the hit with tracing "always on" is still very high - on the order of 15%.

> 3. do you see a similar slowdown in one of the in-process tests? It will be much more pleasant to iterate in a local setup.

I haven't tried any of the local benchmarks yet, but I'll post here if I find something useful.

**Comment by yuzefovich** [comment] 2021-02-27 07:15
The numbers I got yesterday with both #61158 and #61116 cherry-picked with 3 min ramp and 15 min duration:
- GCE:
  - sample_rate=0: 9335.7
  - sample_rate=0.05: 9235.3, **-1.1%**
  - sample_rate=0.1: 9211.2, **-1.3%**
  - sample_rate=0.15: 9078.7, **-2.8%**
- AWS:
  - sample_rate=0: 10636.2
  - sample_rate=0.05: 10488.1, **-1.4%**
  - sample_rate=0.1: 10481.1, **-1.5%**
  - sample_rate=0.15: 10347.0, **-2.7%**

**Comment by asubiotto** [comment] 2021-03-01 16:42
Nice! That looks promising cc @awoods187 @jordanlewis. What's the bottleneck now?

**Comment by awoods187** [comment] 2021-03-01 16:46
This is interesting. I was having to push into 0.5 values to see meaningful values for network and memory when running tpc-c with 10 warehouses via roachprod local previously. 

I'm concerned that too low a sampling value will result in these columns being largely empty and a too high value causing significant performance degradation.

**Comment by asubiotto** [comment] 2021-03-01 16:47
Note that this is with the sampling rate fully turned on.

**Comment by yuzefovich** [comment] 2021-03-01 21:06
I pushed up a minor modification to `BenchmarkKV` from `sql/tests` package that includes the sample rate [here](https://github.com/yuzefovich/cockroach/tree/sample-rate). This seems to track pretty well with my observations on a 3 node roachprod cluster (that with `sample_rate=1` AKA "always on" sampling the hit is something like 10%).

In terms where we seem to be spending most of the extra time, it is in `GetRecording` which is expected. In terms of allocations, that seems to mostly come from `GetQueryLevelStats`. I'm not sure how/whether we can improve the former, but I tried a few things (like pooling stats-related objects and removing node level stats), but the microbenchmarks don't show that anything changed. I'll try the pooling change on an actual cluster.

**Comment by yuzefovich** [comment] 2021-03-01 21:11
One thing that I wondered about is whether we might want to remove `DeprecatedStats` field from `RecordedSpan` since marshaling that object shows up on the profile. I understand that we kept the field initially so that in the mixed version clusters we are able to send the stats data to nodes running old versions, etc, but is it worth paying some performance cost so that in mixed state EXPLAIN ANALYZE diagrams are helpful? I believe our advice to not be in a mixed-version setting, so maybe it is ok to remove the field entirely? I guess we would need to confirm that the old code would not crash if we do, but also maybe I'm missing something.

**Comment by yuzefovich** [comment] 2021-03-02 05:51
I ran the benchmarks with several "optimizations" ([here](https://github.com/yuzefovich/cockroach/commits/sample-rate)), and the improvements didn't really show up:
- GCE:
  - sample_rate=0: 8529.0
  - sample_rate=0.05: 8636.7, **+1.3%**
  - sample_rate=0.2: 8359.2, **-2.0%**
  - sample_rate=0.5: 8023.4, **-5.9%**
  - sample_rate=1: 7599.9, **-10.9%**
- AWS:
  - sample_rate=0: 10762.2
  - sample_rate=0.05: 10602.5, **-1.5%**
  - sample_rate=0.2: 10295.3, **-4.3%**
  - sample_rate=0.5: 10050.5, **-6.6%**
  - sample_rate=1: 9382.6, **-12.8%**
At this point I'm out of ideas to try out and hoping that our KV friends will offer some tips. I don't see any low hanging fruit in the profiles, so any pointers would be appreciated. With the current state of things I think we should be using a sample rate of 0.05 by default.

On a side note in my initial benchmarks last week (before some of the improvements went in) I didn't see significant changes on TPCC 100 warehouses benchmark.

**Comment by tbg** [comment] 2021-03-02 12:44
I played with this over in https://github.com/cockroachdb/cockroach/pull/61328. Two main things that I found helped was disabling the extra redundant trace span that is created in `createStatsSpan` and `*instrumentationHelper.Setup` , respectively. Things are pretty noisy, but from dozens of runs of `cmp.sh` I'm fairly confident that this brings down the slowdown from ~20% to ~10% (in that one benchmark that `cmp.sh` runs). I poked around and disabled random other bits. Interestingly, making `sp.SetSpanStats` drop the payload didn't really make that big a difference. That makes me think that the extra work must be a byproduct of the SQL instrumentation. Are we creating additional trace spans somewhere whenever span collection is on? Do we do something else that's expensive? Since dropping payloads didn't straighten things out I think that excludes the contention registry and the traversal and propagation of recordings. I would still be curious if you see any movement on the two metrics added in a previous commits on this branch when you turn sampling on in your roachprod experiments.
Either way, I've run out of steam for the day. Would appreciate you going over my experiments and making sure the conclusions are solid. You can just run `./cmp.sh` and it will do everything for you.

**Comment by yuzefovich** [comment] 2021-03-02 21:38
Tobi, thanks for the pointers! I'll look into addressing the span creations you pointed out.

I'm wondering though why are we keeping `DeprecatedStats` field in `RecordedSpan`? I assume it is for the mixed version clusters, and I'm not sure whether it is necessary since we have changed the representation in 21.1 cycle. Removing the deprecated field entirely would make it easier to fix the span creation issue. cc @RaduBerinde

**Comment by RaduBerinde** [comment] 2021-03-02 21:46
The DistSQL version was bumped so DistSQL won't use old nodes in the flows anyway.. I don't think the deprecated stats are useful.

**Comment by yuzefovich** [comment] 2021-03-03 03:02
Latest numbers on master (including the removal of `DeprecatesStats` field) + #61380 (cleaning up vectorized stats propagation), perf hit is still high, 3 min ramp 15 min load:
- GCE:
  - sample_rate=0: 8448.6
  - sample_rate=0.05: 8368.6, **-1.4%**
  - sample_rate=0.1: 8304.7, **-2.2%**
  - sample_rate=0.15: 8140.2, **-4.1%**

**Comment by asubiotto** [comment] 2021-03-03 13:30
What's the noise threshold here? Looks like the previous GCE numbers showed +1.3% and with these two improvements it's dropped to -1.4%.

**Comment by yuzefovich** [comment] 2021-03-03 16:41
I wouldn't read too much into this. Previous run was 1 min ramp 5 min duration, this run was 3 min ramp 15 min duration, so I'd trust the latter more. That +... difference is the only "improvement" I observed in my testing, so it was an outlier.

**Comment by yuzefovich** [comment] 2021-03-04 03:24
I implemented all hacky ideas mentioned so far in https://github.com/yuzefovich/cockroach/commits/sample-rate, however, this didn't change microbenchmark numbers nor KV95 numbers on 3 node cluster.

When looking at the profiles of 3 node cluster with `sample_rate=1` I see some time spent in `getRecording` and `ExtractStatsFromSpan`. However, when diving into details I don't see much we can chop off - to me it all seems like propagating the execution stats through traces has inherent overhead which shows up as the performance hit. On 30 seconds profile I see this:
```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).getRecording in /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go
      60ms      1.88s (flat, cum)  3.39% of Total
...
         .      190ms    167:	result := make(Recording, 0, 1+len(s.mu.recording.children)+len(s.mu.recording.remoteSpans))
         .          .    168:	// Shallow-copy the children so we can process them without the lock.
      10ms       10ms    169:	children := s.mu.recording.children
         .      620ms    170:	result = append(result, s.getRecordingLocked(wantTags))
      10ms       50ms    171:	result = append(result, s.mu.recording.remoteSpans...)
         .       70ms    172:	s.mu.Unlock()
         .          .    173:
         .          .    174:	for _, child := range children {
      20ms      680ms    175:		result = append(result, child.getRecording(everyoneIsV211, wantTags)...)
         .          .    176:	}
         .          .    177:
         .          .    178:	// Sort the spans by StartTime, except the first Span (the root of this
         .          .    179:	// recording) which stays in place.
         .       50ms    180:	toSort := sortPool.Get().(*Recording) // avoids allocations in sort.Sort
      10ms       10ms    181:	*toSort = result[1:]
      10ms      150ms    182:	sort.Sort(toSort)
         .          .    183:	*toSort = nil
         .       30ms    184:	sortPool.Put(toSort)
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/util/tracing.(*crdbSpan).getRecordingLocked in /go/src/github.com/cockroachdb/cockroach/pkg/util/tracing/crdbspan.go
      40ms      620ms (flat, cum)  1.12% of Total
...
      20ms       30ms    299:	if numEvents := s.mu.structured.Len(); numEvents != 0 {
         .       10ms    300:		rs.InternalStructured = make([]*types.Any, 0, numEvents)
         .          .    301:		for i := 0; i < numEvents; i++ {
         .       20ms    302:			event := s.mu.structured.Get(i).(Structured)
         .      480ms    303:			item, err := types.MarshalAny(event)
         .          .    304:			if err != nil {
         .          .    305:				// An error here is an error from Marshal; these
         .          .    306:				// are unlikely to happen.
         .          .    307:				continue
         .          .    308:			}
         .          .    309:			rs.InternalStructured = append(rs.InternalStructured, item)
         .          .    310:		}
         .          .    311:	}
```
```
ROUTINE ======================== github.com/cockroachdb/cockroach/pkg/sql/execinfrapb.ExtractStatsFromSpans.func1 in /go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfrapb/component_stats.go
      20ms      460ms (flat, cum)  0.83% of Total
...
      20ms       20ms    345:		span.Structured(func(item *types.Any) {
         .       30ms    346:			if !types.Is(item, componentStats) {
         .          .    347:				return
         .          .    348:			}
         .       40ms    349:			stats := NewComponentStats()
         .      340ms    350:			if err := protoutil.Unmarshal(item.Value, stats); err != nil {
         .          .    351:				return
         .          .    352:			}
```
At this point, I don't know what else to try to reduce the performance hit. Curious to hear whether @tbg or @irfansharif have some suggestions.

I've been using this [script](https://gist.github.com/yuzefovich/65242dee96e3f7bc35754073e22149dc) (no judgement please, I'm a bash noob :D) to run the KV95 benchmarks if anyone is interested in running it themselves.

**Comment by tbg** [comment] 2021-03-04 10:48
The meta question that I have is why we're blaming tracing right now. My experiments over in https://github.com/cockroachdb/cockroach/pull/61328#issuecomment-790485525 (which I'd like you to scrutinize/confirm! I might have messed something up) indicate that the overhead of stats collection related to marshalling, transporting, unmarshalling the extra payloads should be in the single-digit microsecond range, but I see more like 40 microseconds in the single-in-mem-server benchmark. Let's discuss over on https://github.com/cockroachdb/cockroach/pull/61328.

**Comment by asubiotto** [comment] 2021-03-04 14:34
It's possible that something else is slowing this down. The `VectorizedStatsCollector` might be slowing things down when inserted into a flow. It's possible that we should also experiment with pooling all operators in this flow to see what the change is. Since it's hard to see anything from the profiles, I think the way forward here is to list the differences between a non-instrumented flow and an instrumented flow and try to narrow down the search surface area by e.g. experimenting with not allocating stats collectors at all, or making `batchInfoCollector.Next` not do anything.

**Comment by tbg** [comment] 2021-03-04 14:47
Note that `./cmp.sh` (the macrobenchmark) intentionally disables garbage collection, so I don't think pooling should make a difference in at least that benchmark.

**Comment by yuzefovich** [comment] 2021-03-05 03:48
Quick update is that with #61529 cherry-picked, the performance hit of `sample_rate=1` went down noticeably, to -5.7% on GCE and -7.1% on AWS in a single 5 min run.

**Comment by yuzefovich** [comment] 2021-03-05 04:38
In my experiments on df11d417621885310f28dd60e8253878f3117a0e with Tobi's commits from #61328 cherry-picked (but without mine WIP commits) I observe the following explanation for the current 13% perf hit in the macro benchmark (KV/Scan, all numbers are approximate):
- 1% hit for simply creating a new span (the one in `instrumentationHelper.Setup`) and finishing it, without getting the recording. No stats are collected.
- 2-3% hit for getting the recording from that span when no stats have been attached to it. We're getting the trace data that is attached by other components (most likely below SQL, like dist sender).
- 1.5% for saving flows metadata by `saveFlows` function when there are no stats attached still. `saveFlows` also calls `NewFlowsMetadata`. It seems like `NewFlowsMetadata` is currently responsible for about half of 1.5% hit.
- 2.5% for calling `GetQueryLevelStats` on a trace with no stats payload. Note that recording query level stats into `appStats` and `txnStats` seems to be free.
- 2% for planning vectorized stats collectors, but without calling `getStats` on them and, therefore, still not adding stats payload to the trace.
- 1.5% for calling `getStats` (i.e. retrieving the execution stats) but still not attaching them to the trace.
- 1.5% for attaching the stats to the trace (i.e. performing the full action for sampling).

**Comment by yuzefovich** [comment] 2021-03-05 06:32
I prototyped again a few things already mentioned before to see the impact on an actual KV95 run [here](https://github.com/yuzefovich/cockroach/tree/sample-rate).
- the first commit removes an extra span created in `instrumentationHelper.Setup` and uses the already present one. This change seems to reduce the hit by a quarter or so. The numbers look as follows:
  - GCE:
    - `sample_rate=0.5`: **-0.8%**
    - `sample_rate=1`: **-4.1%**
  - AWS:
    - `sample_rate=0.5`: **-3.5%**
    - `sample_rate=1`: **-6.7%**
- the second commit trims the trace analyzer to remove currently unused bookkeeping. This commit surprisingly seems to have thing a bit worse actually. The numbers look as follows:
  - GCE:
    - `sample_rate=0.5`: **-3.0%**
    - `sample_rate=1`: **-6.8%**
  - AWS:
    - `sample_rate=0.5`: **-4.7%**
    - `sample_rate=1`: **-6.2%**
- the third commit pools `ComponentStats` objects. Note that the second commit made it easier to implement this commit. The numbers look as follows:
  - GCE:
    - `sample_rate=0.5`: **-3.2%**
    - `sample_rate=1`: **-6.9%**
  - AWS:
    - `sample_rate=0.5`: **-2.7%**
    - `sample_rate=1`: **-5.0%**
- the fourth commit removes the additional tracing span created by the colbatchscans. Note that in the current form that commit cannot be merged to master because it would cause the computation of cumulative contention time when there are wrapped rowexec processors in the vectorized flow. The numbers look as follows:
  - GCE:
    - `sample_rate=0.5`: **-3.8%**
    - `sample_rate=1`: **-5.4%**
  - AWS:
    - `sample_rate=0.5`: **-0.0%**
    - `sample_rate=1`: **-2.4%**
----
Based on these results, it looks like the most beneficial thing is avoiding creating spans if possible. Thus, I'll open up a PR to include the first commit and will kick off more extensive benchmarks with it.

**Comment by yuzefovich** [comment] 2021-03-05 16:45
With #61532 I got the following:
- 1 min ramp, 5 min duration:
  - GCE:
    - `sample_rate=0.05`: **+1.6%**
    - `sample_rate=0.1`: **+1.6%**
    - `sample_rate=0.25`: **-0.2%**
    - `sample_rate=0.5`: **-2.5%**
    - `sample_rate=1`: **-2.8%**
  - AWS:
    - `sample_rate=0.05`: **-2.2%**
    - `sample_rate=0.1`: **-0.1%**
    - `sample_rate=0.25`: **-1.1%**
    - `sample_rate=0.5`: **-3.3%**
    - `sample_rate=1`: **-7.4%**
- 2 min ramp, 10 min duration:
  - GCE:
    - `sample_rate=0.05`: **-1.4%**
    - `sample_rate=0.1`: **-1.0%**
    - `sample_rate=0.25`: **-2.8%**
    - `sample_rate=0.5`: **-4.5%**
    - `sample_rate=1`: **-7.3%**
  - AWS:
    - `sample_rate=0.05`: **-0.7%**
    - `sample_rate=0.1`: **-0.6%**
    - `sample_rate=0.25`: **-1.8%**
    - `sample_rate=0.5`: **-3.6%**
    - `sample_rate=1`: **-6.8%**
- 3 min ramp, 15 min duration:
  - GCE:
    - `sample_rate=0.05`: **+0.3%**
    - `sample_rate=0.1`: **+1.3%**
    - `sample_rate=0.25`: **-2.6%**
    - `sample_rate=0.5`: **-3.0%**
    - `sample_rate=1`: **-5.8%**
  - AWS:
    - `sample_rate=0.05`: **-0.8%**
    - `sample_rate=0.1`: **-1.0%**
    - `sample_rate=0.25`: **-2.4%**
    - `sample_rate=0.5`: **-3.3%**
    - `sample_rate=1`: **-6.3%**

**Comment by yuzefovich** [comment] 2021-03-06 02:41
Reran the tests on 90d6ba4efd994bdf5c7a662a0cd69b01b0a4a831 with #61532 (Tobi suggested that #61359 might improve things). Looks like without other improvements `sample_rate=0.1` will be the maximum recommended default value. The numbers are for 5 min and 10 min duration:
  - GCE:
    - `sample_rate=0.05`: **-1.8%**, **-0.4%**
    - `sample_rate=0.1`: **-2.0%**, **-1.1%**
    - `sample_rate=0.25`: **-3.1%**, **-2.0%**
    - `sample_rate=0.5`: **-5.1%**, **-2.7%**
    - `sample_rate=1`: **-8.4%**, **-5.6%**
  - AWS:
    - `sample_rate=0.05`: **-2.2%**, **-0.6%**
    - `sample_rate=0.1`: **-1.5%**, **-1.6%**
    - `sample_rate=0.25`: **-3.1%**, **-3.2%**
    - `sample_rate=0.5`: **-5.1%**, **-4.6%**
    - `sample_rate=1`: **-8.9%**, **-8.6%**

**Comment by asubiotto** [comment] 2021-03-09 21:45
Let's set it to 0.1. I'll try to circle back later with a better sampling approach (i.e. sample the first occurrence of a fingerprint) in #61678.

**Comment by irfansharif** [comment] 2021-03-10 05:13
I've yet to digest the experiments here and on #61328, but looking at TPC-C I'm seeing about 10% additional memory usage by just us creating new spans (mostly from `connExecutor.execCmd`): https://github.com/cockroachdb/cockroach/issues/59424#issuecomment-794707212. I don't suppose we can do much about that one, can we? I haven't worked out how that affects CPU usage. We're certainly taking on added GC pressure because of it. In any case, the memory overhead seems a bit worrying.

**Comment by irfansharif** [comment] 2021-03-10 05:56
Hm, ok just familiarized myself with the above. I guess that one is pretty necessary. The analysis here and on #61328 look sound, y'all are way ahead of me.

**Closed** 2021-03-10 22:39 UTC
Labels: C-enhancement
