### ISSUE TITLE
importccl: flake in TestImportWorkerFailure

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#75213] opened 2022-01-20 15:04 UTC
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/4162981?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
------ Stdout: -------
=== RUN   TestImportWorkerFailure
    test_log_scope.go:79: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportWorkerFailure484675052
    test_log_scope.go:80: use -show-logs to present logs inline
    import_stmt_test.go:5070: pq: not enough memory available to create a BulkAdder: root: memory budget exceeded: 33554432 bytes requested, 101011456 currently allocated, 134217728 bytes in budget
    panic.go:642: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestImportWorkerFailure484675052
--- FAIL: TestImportWorkerFailure (8.59s)
```

**Comment by msbutler** [comment] 2022-01-20 22:40
According to t[est history](https://teamcity.cockroachdb.com/test/7140302165166259234?currentProjectId=Cockroach_UnitTests&branch=%3Cdefault%3E&expandTestHistoryChartSection=true&testTab=overview), this is the first time it has failed in ~550 builds. Looking at the code, I don't  immediately see why this test would be memory intensive. Perhaps this is an test infra flake?

**Comment by irfansharif** [comment] 2022-01-21 16:00
Duplicate of #73546. Perhaps we could try stressing it? Might shake something, given the memory budget error unscientifically I'd say it's less likely to be an infra flake (could be wrong!).

**Closed by irfansharif** 2022-01-21 16:00 UTC
Labels: C-bug, C-test-failure, A-bulkio, T-bulkio
