### ISSUE TITLE
circleci: failed tests (15263): TestDockerPHP

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5574] opened 2016-03-25 14:18 UTC
The following test appears to have failed:

[#15263](https://circleci.com/gh/cockroachdb/cockroach/15263):

```
PHP Warning:  pg_query_params(): Query failed: ERROR:  param $1: strconv.ParseInt: parsing "a": invalid syntax in Command line code on line 9
Query failed: ERROR:  param $1: strconv.ParseInt: parsing "a": invalid syntax
I160325 14:18:07.044448 acceptance/cluster/localcluster.go:634  stopping
I160325 14:18:07.044651 acceptance/cluster/localcluster.go:532  event stream done, resetting...: net/http: request canceled
I160325 14:18:07.044672 acceptance/cluster/localcluster.go:555  events monitor exits
panic: test timed out after 5m0s

goroutine 1534 [running]:
panic(0x1199a80, 0xc824962c40)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x176b248, 0x1df1480, 0x10, 0x10, 0xffde454cfd041501)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8204e3f08, 0x1769128)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc8204e3f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:82 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 8 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x20c6a60)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 19 [select, 4 minutes, locked to thread]:
runtime.gopark(0x176ba80, 0xc820028f28, 0x14ab2e0, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820028f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820028f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 10 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 11 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 1379 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x7fa6fcf4b100, 0xc820015530, 0x7fa6fcf4b170, 0xc820453d00, 0xc824922620, 0xc82664ad50, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x49d
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc82037d860, 0x7fa6fcf4b100, 0xc820015530, 0x14a44f8, 0x4, 0xc82037a9c0, 0x51, 0xc82664ad50, 0x7fa6fcf48df0, 0xc820376d20, ...)
	/go/src/github.com/docker/engine-api/client/request.go:93 +0x45a
github.com/docker/engine-api/client.(*Client).sendRequest(0xc82037d860, 0x7fa6fcf4b100, 0xc820015530, 0x14a44f8, 0x4, 0xc82037a9c0, 0x51, 0xc82664ad50, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:71 +0x2b1
github.com/docker/engine-api/client.(*Client).post(0xc82037d860, 0x7fa6fcf4b100, 0xc820015530, 0xc82037a9c0, 0x51, 0xc82664ad50, 0x0, 0x0, 0x0, 0x7fa6fcf3e028, ...)
	/go/src/github.com/docker/engine-api/client/request.go:36 +0xb4
github.com/docker/engine-api/client.(*Client).ContainerKill(0xc82037d860, 0x7fa6fcf4b100, 0xc820015530, 0xc82046cd40, 0x40, 0x14a1b70, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/container_kill.go:14 +0x1ff
--
testing.tRunner(0xc824cc0e10, 0x1df1540)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 552 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820440dc0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 532 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820200580)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 966 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82177c000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 45 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa6fcf4c130, 0x72, 0xc820189000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820391d40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820391d40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820391ce0, 0xc820189000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118290, 0xc820189000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201ceb60)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 46 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc8201ceb60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 457 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fa6fcf4bef0, 0x72, 0xc820314000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204ee370, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204ee370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204ee310, 0xc820314000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118270, 0xc820314000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82012e8f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1477 [select]:
net/http.(*persistConn).writeLoop(0xc8248169c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 256 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fa6fcf4be30, 0x72, 0xc8202fb000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204eea00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204eea00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204ee9a0, 0xc8202fb000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2d8, 0xc8202fb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201ce340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1533 [select]:
net/http.(*persistConn).roundTrip(0xc8248169c0, 0xc824962ba0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8248440c0, 0xc824922620, 0xc8248440c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc824922620, 0x7fa6fcf42820, 0xc8248440c0, 0x0, 0x0, 0x0, 0xc82036b300, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc83220c750, 0xc824922620, 0x0, 0x0, 0x0, 0xc8221e64d8, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc83220c750, 0xc824922620, 0x176b5f0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
--
github.com/docker/engine-api/client/transport/cancellable.Do.func1(0x7fa6fcf4b170, 0xc820453d00, 0xc824922620, 0xc82037ab40)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:49 +0x35
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:52 +0xff

goroutine 374 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fa6fcf4bfb0, 0x72, 0xc8203ea000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204ee1b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204ee1b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204ee150, 0xc8203ea000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118128, 0xc8203ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200605b0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 375 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8200605b0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 157 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fa6fcf4c070, 0x72, 0xc8204cf000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820390bc0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820390bc0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820390b60, 0xc8204cf000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a220, 0xc8204cf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82012edd0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 158 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc82012edd0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 257 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8201ce340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1382 [IO wait]:
net.runtime_pollWait(0x7fa6fcf4b530, 0x72, 0xc8322b9000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc832253bf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc832253bf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc832253b90, 0xc8322b9000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201183e8, 0xc8322b9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8248168f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 800 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fa6fcf59de8, 0x72, 0xc82a5b7000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82a72c220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82a72c220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82a72c1c0, 0xc82a5b7000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a608, 0xc82a5b7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc831eb0dd0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 458 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82012e8f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 522 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820011ce0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1182 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc8268bba00)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 508 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8204aa0b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1383 [select]:
net/http.(*persistConn).writeLoop(0xc8248168f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 801 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc831eb0dd0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 518 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820011ad0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 505 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8204413f0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1476 [IO wait]:
net.runtime_pollWait(0x7fa6fcf59ea8, 0x72, 0xc832226000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc832192d80, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc832192d80, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc832192d20, 0xc832226000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2e0, 0xc832226000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8248169c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1284 [IO wait]:
net.runtime_pollWait(0x7fa6fcf5a1a8, 0x72, 0xc8222bb000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc822558680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc822558680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc822558620, 0xc8222bb000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118db0, 0xc8222bb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8221dcea0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1285 [select]:
net/http.(*persistConn).writeLoop(0xc8221dcea0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 557 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820440f20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 965 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fa6fcf4b2f0, 0x72, 0xc824cbd000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc821598a00, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc821598a00, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8215989a0, 0xc824cbd000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118950, 0xc824cbd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82177c000)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 680 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc832210420)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 581 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8200eb290)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 673 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc832165130)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 637 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fa6fcf4c1f0, 0x72, 0xc823f47000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202a5cd0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202a5cd0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202a5c70, 0xc823f47000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201183e0, 0xc823f47000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82013d380)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 638 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82013d380)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1181 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fa6fcf59f68, 0x72, 0xc83296a000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc826a396b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc826a396b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc826a39650, 0xc83296a000, 0x1000, 0x1000, 0x0, 0x7fa6fcf3e050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820118c70, 0xc83296a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-30 15:15
Duplicate of #5087.

**Closed by petermattis** 2016-03-30 15:15 UTC
Labels: Robot, test-failure
