### ISSUE TITLE
circleci: failed tests (13516): TestMultiRangeEmptyAfterTruncate 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4720] opened 2016-02-29 18:49 UTC
The following test appears to have failed:

[#13516](https://circleci.com/gh/cockroachdb/cockroach/13516):

```
I160229 18:47:35.443546 raft/raft.go:472  [group 4] 1 became candidate at term 6
I160229 18:47:35.443576 raft/raft.go:521  [group 4] 1 received vote from 1 at term 6
I160229 18:47:35.443615 raft/raft.go:500  [group 4] 1 became leader at term 6
I160229 18:47:35.491499 client/db.go:488  failed batch: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
I160229 18:47:35.491803 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestMultiRangeEmptyAfterTruncate (0.12s)
	dist_sender_server_test.go:88: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
=== RUN   TestMultiRangeScanReverseScanDeleteResolve
I160229 18:47:35.493321 server/context.go:141  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
I160229 18:47:35.561294 rpc/clock_offset.go:154  monitoring cluster offset
I160229 18:47:35.561972 server/node.go:352  store store=0:0 ([]=) not bootstrapped
I160229 18:47:35.564151 raft/raft.go:459  [group 1] 1 became follower at term 5
I160229 18:47:35.564223 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160229 18:47:35.564260 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160229 18:47:35.564322 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160229 18:47:35.564355 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
--
W160229 18:47:47.266406 kv/dist_sender.go:621  failed to invoke BeginTransaction ["a",/Min), Put ["a",/Min), Put ["b",/Min): txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=3cccd564 key="a" rw=true pri=0.03663367 iso=SERIALIZABLE stat=PENDING epo=1 ts=1456771667.264739325,0 orig=1456771667.264739325,0 max=1456771667.264739325,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=ede7bc63 key="b" rw=false pri=0.01738723 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456771667.260931924,0 orig=1456771667.260931924,0 max=1456771667.260931924,0
I160229 18:47:47.266695 client/db.go:488  failed batch: txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=3cccd564 key="a" rw=true pri=0.03663367 iso=SERIALIZABLE stat=PENDING epo=2 ts=1456771667.264739325,0 orig=1456771667.264739325,0 max=1456771667.314739325,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=ede7bc63 key="b" rw=false pri=0.01738723 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456771667.260931924,0 orig=1456771667.260931924,0 max=1456771667.260931924,0
I160229 18:47:47.316347 storage/replica_command.go:457  auto-gc'ed ede7bc63 (1 intents)
I160229 18:47:47.320931 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.23s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	30.546s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestFlagsToStr
--- PASS: TestFlagsToStr (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-29 18:53
Duplicate of #4719

**Closed by bdarnell** 2016-02-29 18:53 UTC
Labels: test-failure
