### ISSUE TITLE
internal error: ordering column group contains non-equivalent columns (op project)

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#74332] opened 2021-12-30 17:30 UTC
sql/tests.TestRandomSyntaxSQLSmith [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=4010618&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=4010618&tab=artifacts#/) on master @ [5ac733bb4927020bc1c52da24b2591742fde8e1f](https://github.com/cockroachdb/cockroach/commits/5ac733bb4927020bc1c52da24b2591742fde8e1f):

Random syntax error:

```
    rsg_test.go:782: Crash detected: server panic: pq: internal error: ordering column group (4,11) contains non-equivalent columns (op project)
```
Query:

```
        SELECT
        	st_mpolyfromtext(tab_571967.col1_3::STRING)::GEOMETRY AS col_1298029, tab_571968.col1_3 AS col_1298030
        FROM
        	defaultdb.public.table1 AS tab_571967
        	JOIN defaultdb.public.table1 AS tab_571968 ON
        			(tab_571967.col1_0) = (tab_571968.col1_0) AND (tab_571967.col1_3) = (tab_571968.col1_3),
        	defaultdb.public.table2@[0] AS tab_571969
        	JOIN defaultdb.public.seed@[0] AS tab_571970 ON false
        ORDER BY
        	tab_571967.col1_3 DESC, tab_571969.col2_13;
```
Schema:

```
    rsg_test.go:599: To reproduce, use schema:
    rsg_test.go:601: 
        		SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;
        		SET CLUSTER SETTING sql.stats.histogram_collection.enabled = false;
        	CREATE TABLE table1 (col1_0 INET NOT NULL, col1_1 VARCHAR NOT NULL, col1_2 BOOL NOT NULL, col1_3 STRING NOT NULL AS (lower(CAST(col1_2 AS STRING))) STORED, PRIMARY KEY (col1_0, col1_2 ASC, col1_1 DESC, col1_3 ASC), UNIQUE (col1_2 DESC, col1_3, col1_1 ASC, col1_0 DESC), INDEX (col1_3), UNIQUE (col1_1, col1_2 DESC) WHERE ((table1.col1_1 >= e'\U00002603':::STRING) AND table1.col1_2) OR (table1.col1_3 != 'X':::STRING), INDEX (col1_1 ASC, lower(CAST(col1_2 AS STRING)) ASC), UNIQUE (col1_1 ASC, col1_3 DESC) WHERE ((table1.col1_1 > '"':::STRING) OR (NOT table1.col1_2)) AND (table1.col1_3 = '"':::STRING), UNIQUE (col1_0 ASC));
        CREATE TABLE table2 (col2_0 UUID, col2_1 INT4, col2_2 INT4 NOT NULL, col2_3 INT8 NOT NULL, col2_4 REGCLASS, col2_5 FLOAT8 NOT NULL, col2_6 BYTES NOT NULL, col2_7 INT2 NULL, col2_8 INT4, col2_9 GEOMETRY NULL, col2_10 FLOAT8, col2_11 REGROLE NULL, col2_12 REGCLASS NOT NULL, col2_13 INT4 AS (((col2_8 + col2_2) + col2_1) + col2_3) VIRTUAL, UNIQUE (col2_1 DESC, col2_10 ASC, col2_5 DESC, col2_3 ASC, col2_0 ASC, col2_13 ASC, col2_4 ASC, col2_11 DESC, col2_6, col2_7 DESC), INDEX (col2_10 ASC, col2_13 DESC, lower(CAST(col2_12 AS STRING)) DESC, col2_0 DESC, (col2_1 + (-1762646881):::INT8) ASC, col2_7, col2_5, col2_8 ASC, col2_4, col2_6 ASC, (col2_5 + 0.3314406729933667:::FLOAT8) ASC, col2_3 ASC, col2_11, col2_1 ASC) STORING (col2_2, col2_9, col2_12), INVERTED INDEX (col2_1 ASC, col2_12 ASC, col2_11 DESC, col2_10, col2_2 DESC, col2_4, (((col2_3 + col2_2) + col2_1) + col2_8), col2_9) WHERE ((table2.col2_3 = 2147483647:::INT8) AND (table2.col2_8 = 0:::INT8)) OR (table2.col2_13 <= 1:::INT8), FAMILY (col2_3, col2_7, col2_0), FAMILY (col2_12, col2_4, col2_8, col2_2, col2_11, col2_10), FAMILY (col2_9), FAMILY (col2_1), FAMILY (col2_6, col2_5));
        CREATE TABLE table3 (col3_0 DATE NOT NULL, col3_1 OID NULL, col3_2 INET NULL, col3_3 TIMESTAMPTZ NULL, col3_4 STRING NULL AS (lower(CAST(col3_1 AS STRING))) STORED, col3_5 STRING NULL AS (CASE WHEN col3_3 IS NULL THEN '':::STRING ELSE e'-\x132\x15dIJL':::STRING END) VIRTUAL, PRIMARY KEY (col3_0 DESC), INDEX (col3_4 ASC) WHERE table3.col3_3 >= '3000-01-01 00:00:00+00:00':::TIMESTAMPTZ, INDEX (col3_2, col3_1 ASC, col3_5 ASC, col3_4 ASC), UNIQUE (col3_4 DESC, col3_0 DESC) WHERE ((table3.col3_0 <= 'infinity':::DATE) OR (table3.col3_4 >= e'\U00002603':::STRING)) OR (table3.col3_3 = '-2000-01-01 00:00:00+00:00':::TIMESTAMPTZ), INDEX (col3_2 DESC, col3_3 DESC, col3_5), INDEX (col3_3 ASC, col3_1 DESC, col3_4 DESC) STORING (col3_2), INDEX (col3_2, col3_1 DESC, col3_5, col3_4 ASC), INDEX (col3_0 ASC, col3_5 DESC, col3_3 ASC, (CASE WHEN col3_3 IS NULL THEN e'/[=hn/\x19^':::STRING ELSE e'4\x06k@':::STRING END), col3_4));
        ALTER TABLE table1 INJECT STATISTICS e'[{"avg_size": 0, "columns": ["col1_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 0, "histo_col_type": "INET", "name": "__auto__", "null_count": 0, "row_count": 0}, {"avg_size": 0, "columns": ["col1_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 0, "histo_buckets": [{"distinct_range": 0, "num_eq": 2674223195479844685, "num_range": 0, "upper_bound": ""}], "histo_col_type": "VARCHAR", "name": "__auto__", "null_count": 0, "row_count": 0}, {"avg_size": 0, "columns": ["col1_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 0, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 0}, {"avg_size": 0, "columns": ["col1_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 0, "histo_buckets": [{"distinct_range": 0, "num_eq": 5170967104840240862, "num_range": 0, "upper_bound": "\\u0007|2.}l"}], "histo_col_type": "STRING", "name": "__auto__", "null_count": 0, "row_count": 0}]':::JSONB;
        ALTER TABLE table2 INJECT STATISTICS '[{"avg_size": 0, "columns": ["col2_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 62599754032, "histo_buckets": [{"distinct_range": 0, "num_eq": 8323410361688824726, "num_range": 0, "upper_bound": "-2031465299"}, {"distinct_range": 0, "num_eq": 500000, "num_range": 3000, "upper_bound": "-1764908802"}, {"distinct_range": 0, "num_eq": 3463131039547202341, "num_range": 400000, "upper_bound": "-1328069862"}, {"distinct_range": 4063286079714403000, "num_eq": 100, "num_range": 4063286079714402597, "upper_bound": "-755986082"}, {"distinct_range": 0, "num_eq": 50000, "num_range": 4050874813368844706, "upper_bound": "-692861813"}, {"distinct_range": 70000000000, "num_eq": 90, "num_range": 70000000000, "upper_bound": "707262152"}, {"distinct_range": 0, "num_eq": 4000000000, "num_range": 5953515428145091856, "upper_bound": "1082660009"}, {"distinct_range": 0, "num_eq": 800, "num_range": 611082525489011135, "upper_bound": "1353867531"}, {"distinct_range": 5531140282193392000, "num_eq": 200000000, "num_range": 5531140282193391879, "upper_bound": "1654779447"}], "histo_col_type": "INT4", "name": "__auto__", "null_count": 67899571821, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_6"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 24240091017, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_9"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 4398540585, "histo_col_type": "", "name": "__auto__", "null_count": 58632480038, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_12"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 18985209304, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 82314246722, "histo_col_type": "", "name": "__auto__", "null_count": 38264076323, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 51442246727, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_4"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 61842641555, "histo_col_type": "", "name": "__auto__", "null_count": 24472754715, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_11"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 18913348768, "histo_col_type": "", "name": "__auto__", "null_count": 7301748396, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_7"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 94644683230, "histo_col_type": "", "name": "__auto__", "null_count": 56503371938, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_8"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 77543914943, "histo_col_type": "", "name": "__auto__", "null_count": 74189067974, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_10"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 68192301911, "histo_buckets": [{"distinct_range": 0, "num_eq": 1310486462285608706, "num_range": 0, "upper_bound": "-1.9250995264854922"}, {"distinct_range": 0, "num_eq": 4694343640852303060, "num_range": 5322629381777980909, "upper_bound": "0.021447950478047206"}, {"distinct_range": 0, "num_eq": 40000, "num_range": 1367417688374298407, "upper_bound": "0.17437649308145875"}, {"distinct_range": 1431927666916251100, "num_eq": 6535171847204362729, "num_range": 1431927666916251025, "upper_bound": "0.4280974080442354"}, {"distinct_range": 0, "num_eq": 9198871625414619442, "num_range": 80000000000, "upper_bound": "0.862760321280251"}], "histo_col_type": "FLOAT8", "name": "__auto__", "null_count": 92984994558, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_13"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 56083918278, "histo_col_type": "", "name": "__auto__", "null_count": 21154471638, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 4600207680, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 100000000000}, {"avg_size": 0, "columns": ["col2_5"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 75475549932, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 100000000000}]':::JSONB;
        ALTER TABLE table3 INJECT STATISTICS e'[{"avg_size": 0, "columns": ["col3_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 2320252213474918839, "histo_col_type": "", "name": "__auto__", "null_count": 1518400686224483889, "row_count": 2977998389161674484}, {"avg_size": 0, "columns": ["col3_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 1424119036496537104, "histo_buckets": [{"distinct_range": 0, "num_eq": 5000000000, "num_range": 0, "upper_bound": "118.71.87.154/7"}, {"distinct_range": 0, "num_eq": 60000, "num_range": 3481669527947190747, "upper_bound": "53.239.198.72/15"}, {"distinct_range": 6211721081111102000, "num_eq": 7000000, "num_range": 6211721081111102074, "upper_bound": "175.123.134.59/17"}, {"distinct_range": 746215423047709600, "num_eq": 3742006750917077649, "num_range": 7604392329361036128, "upper_bound": "96.248.151.253/18"}, {"distinct_range": 80000000000, "num_eq": 20000, "num_range": 80000000000, "upper_bound": "139.229.167.8/21"}, {"distinct_range": 9544901.757017976, "num_eq": 9000, "num_range": 40000000, "upper_bound": "50.151.10.75/30"}, {"distinct_range": 8548885488952726000, "num_eq": 7000, "num_range": 8548885488952724995, "upper_bound": "a117:3768:10b0:cf99:a98d:39fc:87f1:3957/41"}, {"distinct_range": 0, "num_eq": 10000, "num_range": 8940752013228271300, "upper_bound": "fc54:9e8b:cad4:b50b:112b:87ae:ceb2:77bf/58"}, {"distinct_range": 60000000, "num_eq": 2175610659134253185, "num_range": 60000000, "upper_bound": "ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"}], "histo_col_type": "INET", "name": "__auto__", "null_count": 660022971158865233, "row_count": 2977998389161674484}, {"avg_size": 0, "columns": ["col3_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 1622460923205375198, "histo_buckets": [{"distinct_range": 0, "num_eq": 200000000, "num_range": 0, "upper_bound": "1977-04-22 12:24:40.000365+00:00"}, {"distinct_range": 0, "num_eq": 3000, "num_range": 0, "upper_bound": "1984-11-06 13:05:34.000159+00:00"}, {"distinct_range": 0, "num_eq": 100000000000, "num_range": 2765918669246668067, "upper_bound": "2000-08-01 20:12:10.000177+00:00"}, {"distinct_range": 20000, "num_eq": 400000000, "num_range": 20000, "upper_bound": "2002-04-07 01:58:18.000805+00:00"}, {"distinct_range": 0, "num_eq": 196957090277412163, "num_range": 60000000000, "upper_bound": "2007-07-23 19:56:09.000941+00:00"}, {"distinct_range": 2383618993727984000, "num_eq": 8176622265286242019, "num_range": 2383618993727984298, "upper_bound": "2008-05-19 15:41:39.000258+00:00"}, {"distinct_range": 0, "num_eq": 5904934200546072669, "num_range": 700000000, "upper_bound": "2032-08-06 04:44:05.000815+00:00"}, {"distinct_range": 0, "num_eq": 8811503724344523827, "num_range": 3104399982753464331, "upper_bound": "3000-01-01 00:00:00+00:00"}, {"distinct_range": 9140913322899541000, "num_eq": 600000, "num_range": 9140913322899541198, "upper_bound": "294276-12-31 23:59:59.999999+00:00"}], "histo_col_type": "TIMESTAMPTZ", "name": "__auto__", "null_count": 2496404543989527958, "row_count": 2977998389161674484}, {"avg_size": 0, "columns": ["col3_4"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 215217474085511137, "histo_buckets": [{"distinct_range": 0, "num_eq": 4133383700111246287, "num_range": 0, "upper_bound": ""}, {"distinct_range": 284884.3412923074, "num_eq": 6000000000, "num_range": 500000, "upper_bound": "\\u0013O4"}, {"distinct_range": 4172744269360115700, "num_eq": 80000, "num_range": 7232483465374189833, "upper_bound": "X"}, {"distinct_range": 7559397755342167000, "num_eq": 80000000000, "num_range": 7559397755342166665, "upper_bound": "ri[JC-"}], "histo_col_type": "STRING", "name": "__auto__", "null_count": 1217843945020892346, "row_count": 2977998389161674484}, {"avg_size": 0, "columns": ["col3_5"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 180635707411548749, "histo_col_type": "", "name": "__auto__", "null_count": 1546255217560478808, "row_count": 2977998389161674484}, {"avg_size": 0, "columns": ["col3_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 184563492108415353, "histo_buckets": [{"distinct_range": 0, "num_eq": 2730676893015166208, "num_range": 0, "upper_bound": "1989-10-19"}], "histo_col_type": "DATE", "name": "__auto__", "null_count": 0, "row_count": 2977998389161674484}]':::JSONB;
        CREATE TYPE rand_typ_0 AS ENUM ('rs', 'bfnn', 's', 'wzlbg', 'cvjym');
        CREATE TYPE rand_typ_1 AS ENUM ('pnwa', 'ko', 'cvv');
        CREATE TYPE rand_typ_2 AS ENUM ('bres', 'vxfjey', 'na');
        CREATE TYPE rand_typ_3 AS ENUM ('wsxd', 'i', 'vmob', 'ert');
        ;
    rsg_test.go:601: 
        CREATE TYPE greeting AS ENUM ('hello', 'howdy', 'hi', 'good day', 'morning');
        CREATE TABLE IF NOT EXISTS seed AS
        	SELECT
        		g::INT2 AS _int2,
        		g::INT4 AS _int4,
        		g::INT8 AS _int8,
        		g::FLOAT4 AS _float4,
        		g::FLOAT8 AS _float8,
        		'2001-01-01'::DATE + g AS _date,
        		'2001-01-01'::TIMESTAMP + g * '1 day'::INTERVAL AS _timestamp,
        		'2001-01-01'::TIMESTAMPTZ + g * '1 day'::INTERVAL AS _timestamptz,
        		g * '1 day'::INTERVAL AS _interval,
        		g % 2 = 1 AS _bool,
        		g::DECIMAL AS _decimal,
        		g::STRING AS _string,
        		g::STRING::BYTES AS _bytes,
        		substring('00000000-0000-0000-0000-' || g::STRING || '00000000000', 1, 36)::UUID AS _uuid,
        		'0.0.0.0'::INET + g AS _inet,
        		g::STRING::JSONB AS _jsonb,
        		enum_range('hello'::greeting)[g] as _enum
        	FROM
        		generate_series(1, 5) AS g;
        
        INSERT INTO seed DEFAULT VALUES;
        CREATE INDEX on seed (_int8, _float8, _date);
        CREATE INVERTED INDEX on seed (_jsonb);
        ;
    rsg_test.go:603: 
    rsg_test.go:604: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestRandomSyntaxSQLSmith804032091
--- FAIL: TestRandomSyntaxSQLSmith (300.89s)
```
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
<details><summary>Same failure on other branches</summary>
<p>

- #74272 sql/tests: TestRandomSyntaxSQLSmith failed [C-test-failure O-robot branch-release-21.1]
- #70855 sql/tests: TestRandomSyntaxSQLSmith failed [C-test-failure O-robot T-sql-queries branch-release-21.2]
</p>
</details>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestRandomSyntaxSQLSmith.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

_Originally posted by @cockroach-teamcity in https://github.com/cockroachdb/cockroach/issues/70663#issuecomment-1002896156_

Jira issue: CRDB-12041

**Comment by mgartner** [comment] 2022-01-04 19:44
This looks similar to #65038.

**Comment by rharding6373** [comment] 2022-01-28 00:19
I've been unable to reproduce this from either this issue or the most recent case of this particular syntax error: https://github.com/cockroachdb/cockroach/issues/70855#issuecomment-1017170225

**Comment by rharding6373** [comment] 2022-03-02 01:26
Closing as not reproducible.

**Closed by rharding6373** 2022-03-02 01:26 UTC
Labels: C-bug, C-test-failure, T-sql-queries
