### ISSUE TITLE
Problem With HAProxy

### ISSUE THREAD

**Issue by stanley160990** [cockroachdb/cockroach#28783] opened 2018-08-18 01:55 UTC
I Already install 3 node cockroachdb with secure install. Now I cinfigure the HAproxy, but i have a problem with cockroach sql in HAProxy machine. This error:

ddoeth@HA-Proxy0:~/bin/cockroach> cockroach sql --certs-dir=certs --host=HA-proxy0
\# Welcome to the cockroach SQL interface.
\# All statements must be terminated by a semicolon.\
\# To exit: CTRL + D.
\#
Error: x509: certificate is valid for cockroachdb-node0, not HA-proxy0
Failed running “sql”

if i connect direct to the node is success:

ddoeth@HA-Proxy0:~/bin/cockroach > cockroach sql --certs-dir=certs --host=cockroachdb-node0
\# Welcome to the cockroach SQL interface.
\# All statements must be terminated by a semicolon.
\# To exit: CTRL + D.
\#
\# Server version: CockroachDB CCL v2.0.5 (x86_64-unknown-linux-gnu, built 2018/08/13 17:59:42, go1.10) (same version as client)
\# Cluster ID: 4e560d29-80ab-4ced-99ed-57b566b368af
\#
\# Enter ? for a brief introduction.

warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
root@cockroachdb-node0:26257/>

Any solution for this problem?

**Comment by knz** [comment] 2018-08-27 11:35
Hi Stanley,

as described here: https://forum.cockroachlabs.com/t/problem-with-haproxy/1937

the problem is that you need to add the name of the proxy to the certificate.

I believe from your answer on the forum that this solved your problem. I will thus close this issue. If you have further comments or questions please let us know.

Thank you!

**Closed by knz** 2018-08-27 11:35 UTC
