### ISSUE TITLE
kv: pipeline DeleteRange requests where possible

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#64723] opened 2021-05-05 15:19 UTC
Sorry if this is intended and I've just missed why, but in a bit of testing recently I noticed that while transactional pipelining of INSERTs/UPSERTs works great (i.e. they return almost instantly when run within a transaction), it doesn't appear to work for DELETEs (i.e. they have to wait for a full replication round trip).

I noticed this on a cluster running v20.2.7 with roughly 30ms RTT between localities in the cluster.

@nvanbenschoten is this expected? Sorry if it's a dupe or I'm way off base here, but it's surprising to me that inserts/upserts can be pipelined but not deletes.

# Reproduction

Create a simple table:

```
root@/defaultdb> create table foo (k string primary key, v string);
```

Single inserts, upserts, and deletes all take around 30ms, corresponding with the network latency between localities:
```
root@/defaultdb> insert into foo values ('a', 'a')
INSERT 1

Time: 31ms total (execution 31ms / network 0ms)
```

Within a transaction, inserts and upserts finish basically immediately, as I'd expect due to transactional pipelining:
```
root@/defaultdb> begin;
BEGIN

Time: 0ms total (execution 1ms / network 0ms)

root@/defaultdb  OPEN> insert into foo values ('c', 'a'), ('d', 'a');
INSERT 2

Time: 2ms total (execution 2ms / network 0ms)

root@/defaultdb  OPEN> commit;
COMMIT

Time: 31ms total (execution 31ms / network 0ms)
```

However, delete statements don't appear to benefit from this optimization:
```
root@/defaultdb> begin;
BEGIN

Time: 0ms total (execution 0ms / network 0ms)

root@/defaultdb  OPEN> delete from foo where k = 'c';
DELETE 1

Time: 30ms total (execution 30ms / network 0ms)

root@/defaultdb  OPEN> commit;
COMMIT

Time: 31ms total (execution 31ms / network 0ms)
```

Jira issue: CRDB-7218

**Comment by nvanbenschoten** [comment] 2021-05-05 17:59
Hi @a-robinson, thanks for the question!

What you're seeing is currently expected, though we're not particularly happy about it. The problem is that ranged writes cannot currently be pipelined, and some `DELETE` statements issue a `DeleteRange` request instead of a `Delete` request.

There are really two things here. The first part about ranged writes not being able to be pipelined is partially fundamental, but also maybe not entirely. Ranged writes are tricky because we can't predict which keys they will touch ahead of time. This is a hard requirement for requests that are in the same batch as an `EndTxn`, as the parallel commit protocol needs to know which in-flight intent writes to write into the STAGING transaction record. But at some point, we realized [1] that it's not a hard requirement for batches issued before the `EndTxn` and we realized that we can record the in-flight writes _after the fact_, which is what we now do in [`(*txnPipeliner).updateLockTracking`](https://github.com/cockroachdb/cockroach/blob/43a079db6dc1e6460a0bdb23a73bb69c81389532/pkg/kv/kvclient/kvcoord/txn_interceptor_pipeliner.go#L472). So then we would just need a way to know which intents a ranged write laid down after it had initiated consensus and returned to the client to be able to properly track them. Conveniently, `DeleteRangeRequest` does have a `ReturnKeys` option which instructs it to include all keys that received intent writes in its response. So I think we could use this to pipeline `DeleteRangeRequests` in most cases.

The second part is tracked in https://github.com/cockroachdb/cockroach/issues/53939. @jordanlewis actually recently wrote a draft fix for this, which is in https://github.com/cockroachdb/cockroach/pull/63416. I think he'd be interested to hear that we're hitting this in the wild.

Do you mind if I use this issue to track the first item here? I think it would be pretty straightforward to address this.

[1] I think there was some confusion on my part earlier on about server-side retries and when requests could be re-evaluated due to lease errors after async consensus had been initiated. So there was probably some concern about a retry resulting in a new set of intents for ranged writes.

**Comment by a-robinson** [comment] 2021-05-05 18:30
Thanks for the explanation, @nvanbenschoten! I assume that neither of the discussed fixes will be in a release until v21.2? The pipelining performance is really quite nice in general, so it was disappointing to notice that it wasn't kicking in for deletes.

> Do you mind if I use this issue to track the first item here?

Not at all.

**Comment by nvanbenschoten** [comment] 2021-05-05 18:40
We've become less restrictive with backports as our patch release qualification process has improved, so it may be possible to get something into earlier releases, depending on how the change ends up looking. Are you planning to upgrade to v21.1 when it is released in the next few weeks?

**Comment by jordanlewis** [comment] 2021-05-05 18:42
Definitely interested. @nvanbenschoten I don't quite understand the implication of your first point, that we could pipeline some `DeleteRange` requests - would that obviate the point delete project? Or are there lots of circumstances besides `ReturnKeys=false` that would cause us not to be able to pipeline? We don't use `ReturnKeys=false` in any important cases anymore, so it's possible that your first point alone would get us all the way there.

This is extra intriguing because the takeaway from our last conversation about this was that the point `Delete` strategies will have issues w.r.t CDC. What would we be missing by implementing just point 1?

**Comment by a-robinson** [comment] 2021-05-05 18:50
> Are you planning to upgrade to v21.1 when it is released in the next few weeks?

Unless there's a particular reason to do differently, we'll most likely start upgrading a few weeks after it's released.

**Comment by nvanbenschoten** [comment] 2021-05-05 18:51
> Or are there lots of circumstances besides ReturnKeys=false that would cause us not to be able to pipeline?

The primary reason why we would still prefer point deletes over range deletes (beyond the reasons why we prefer Get over Scan) is that a batch with multiple `DeleteRange` requests and an `EndTxn` request would not be able to parallel commit. I think this case would come up for multi-row delete statements that look like `DELETE FROM _ WHERE _ IN (...)`.

> This is extra intriguing because the takeaway from our last conversation about this was that the point Delete strategies will have issues w.r.t CDC.

It looks like we're ok there after all: https://github.com/cockroachdb/cockroach/issues/53939#issuecomment-832877181.

**Closed** 2024-03-26 01:30 UTC
Labels: C-performance, O-community, A-kv-transactions, release-blocker, T-kv, branch-release-24.1
