### ISSUE TITLE
storage: 1->3 node replica repair progresses very slowly

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#7161] opened 2016-06-10 21:53 UTC
The test starts with 10GiB of data on one node. It then adds 2 nodes and waits for the # of ranges to be balanced across nodes. There is no client load on the cluster.

After 13 minutes, this is the state of the cluster:

<img width="1409" alt="screenshot 2016-06-10 17 37 00" src="https://cloud.githubusercontent.com/assets/1564582/15979448/0e9b3c44-2f32-11e6-840e-5d58503ce8fa.png">

A prior run of the test (after pre-emptive snapshots but before parallel snapshots) took 18 minutes to finish all up-replicating.

Memory usage is a bit high on node 1 (the original node containing all ranges) considering the lack of client load:

<img width="496" alt="screenshot 2016-06-10 17 35 13" src="https://cloud.githubusercontent.com/assets/1564582/15979453/112af59e-2f32-11e6-886e-e68b940ab2f3.png">

Version info:

```
Build Tag:   beta-20160609-99-gce229b1
Build Time:  2016/06/10 14:26:54
Platform:    linux amd64
Go Version:  go1.6.2
C Compiler:  gcc 4.9.2
```

cc @tamird @BramGruneir

**Comment by tamird** [comment] 2016-06-10 22:25
Do you think this is a regression introduced in parallel snapshots? What happens if you revert that one merge?

**Comment by tschottdorf** [comment] 2016-06-10 22:31
Or just increase that number from 5 to something way higher.

On Fri, Jun 10, 2016 at 6:25 PM Tamir Duberstein <notifications@github.com>
wrote:

> Do you think this is a regression introduced in parallel snapshots? What
> happens if you revert that one merge?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7161#issuecomment-225310666>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135DKR6g_S7JwCG4yWNl77ofct8_O7ks5qKeRNgaJpZM4IzXKJ>
> .
>
-- 

-- Tobias

**Comment by BramGruneir** [comment] 2016-06-10 22:57
Is this using the latest commits off of my branch?
You could try turning off the reservation system using the env variable.  See if that makes a difference.

**Comment by cuongdo** [comment] 2016-06-11 01:39
This is using an "official" binary generated by CircleCI after a merge to master.

I tried testing 7c33d4f1c43e017e4d5b59fb33d31ac11aed7da7 (which was a few commits _before_ multiple in-flight snapshots), and it worked fine. Up-replicating took a respectable 19.5 minutes.

**Comment by tamird** [comment] 2016-06-11 02:54
FWIW multiple in-flight snapshots is relatively poorly tested. I'll get on
that on Monday.

**Comment by cuongdo** [comment] 2016-06-13 14:52
I just verified that 84f3f53bd9369d49d143dcc8fb7289c0be08517 introduced this regression.

**Comment by tamird** [comment] 2016-06-20 00:34
Gonna close this for now since multiple snapshots has been reverted. That said, it's likely that this was exacerbated by #7299 which has since been fixed, and multiple snapshots will be reintroduced in #7307.

**Closed by tamird** 2016-06-20 00:34 UTC
