### ISSUE TITLE
make slow query log parsable

### ISSUE THREAD

**Issue by mikeczabator-doordasher** [cockroachdb/cockroach#58152] opened 2020-12-21 22:17 UTC
**Is your feature request related to a problem? Please describe.**
The output in the slow query log is unparsable.  The log should be in a format that can be parsed by log readers.

**Comment by rafiss** [comment] 2021-02-18 03:47
i believe this is a duplicate of #59105 which is addressed in 21.1

cc @knz

**Closed by rafiss** 2021-02-18 03:47 UTC
Labels: C-enhancement, O-community, X-blathers-untriaged
