### ISSUE TITLE
storage/engine: capacity numbers are incorrect if the directory is symlinked

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#8904] opened 2016-08-29 19:17 UTC
If you symlink a directory across devices, Capacity() returns the total space free for the non-symlinked device instead of the current one.

At this point, I think we should just not allow symlinks for data directories and perhaps perform a check at startup to make sure the data directories are not using them.

**Comment by bdarnell** [comment] 2016-08-30 04:14
It seems reasonable to allow symlinks for data directories; we just need to resolve them correctly to get the capacity.

**Comment by BramGruneir** [comment] 2016-08-30 04:28
I agree, I think it might be an error with the gosigar library.

Not allowing symlinks seems like the easiest option for now, but we should
support them longer term.

We will also have to update how we count capacity used, since logs might be
symlinked inside the data dir to another filesystem and are counted against
db size right now.

**Comment by knz** [comment] 2016-08-31 19:17
I have checked this.

The issue occurs only if the last part of the path is a symlink. Currently if the last part of the path is a symlink to a mountpoint, then the result will be the capacity of the fs containing the symlink, not that of the fs that is the target of the symlink. That's a feature of the underlying `syscall.Statfs` call made by `gosigar`.

The problem does not exist if the last part of the path is not a symlink.

Arguably this is an issue in `gosigar` since any app using `gosigar` probably will not like/expect this behavior. However it is trivial to work around either on our side or `gosigar` via https://golang.org/pkg/path/filepath/#EvalSymlinks 

I'd suggest implementing the workaround and simultaneously filing an issue upstream.

The issue of logs being accounted against the capacity is IMHO a separate issue.

**Comment by spencerkimball** [comment] 2017-04-02 20:29
Not 1.0 IMO. Adding the `ux-surprise`. @petermattis re-specify 1.0 milestone and assign if you disagree.

**Comment by benesch** [comment] 2018-05-03 01:26
Huh, I couldn't reproduce this on Linux. @knz or @BramGruneir can you check that it's still broken?

**Comment by knz** [comment] 2018-05-03 02:39
I have checked this and could not repro either on linux nor freebsd.
Also I went and checked the kernel code and `statfs(2)` ostensibly resolves symlinks.

Then I went to the gosigar repo history and haven't seen the code path changed since 2015. Neither has `engine/rocksdb.go` changed since bram introduced the call.

My analysis today is that I was probably wrong in saying `gosigar` was at fault. Perhaps the display of the capacity in the web UI was using a different path and not hitting the store capacity API. I don't know.

closing this until it reproduces.

**Closed by knz** 2018-05-03 02:39 UTC
Labels: C-bug, S-3-ux-surprise
