### ISSUE TITLE
sql: add tests for SHOW CREATE TABLE in logictest

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#6917] opened 2016-05-26 12:34 UTC
There are no tests for `SHOW CREATE TABLE` and we mention this command in the docs.
@jseldess

**Comment by futureplan01** [comment] 2016-06-04 11:08
Maybe I'm not looking in the right spot,
But I didn't see a SHOW CREATE TABLE Command in docs

only Create Table
or Show Table

**Comment by knz** [comment] 2016-06-04 13:19
@futureplan01 it is mentioned here: https://www.cockroachlabs.com/docs/create-table.html#show-the-definition-of-a-table

**Comment by tschottdorf** [comment] 2016-06-04 14:20
Maybe it's a silly idea, but is it worth keeping a variant of `SHOW CREATE TABLE` which creates Postgres-compatible output? Every time we build examples, we want the result to be able to run on both, but I always find myself hacking around the subtle diff in table creation.

**Comment by knz** [comment] 2016-06-04 14:34
@tschottdorf that sounds reasonable, but I believe we'd then be talking about a different issue. @mjibson, care to comment?

**Comment by bdarnell** [comment] 2016-06-04 14:47
That doesn't sound like the job of SHOW CREATE TABLE. What changes did you have in mind? If the problem is that we normalize things to non-standard syntax when reconstructing the CREATE TABLE statement, we should probably fix that. But if you're talking about translating a cockroachdb table to a postgres table (e.g. changing `INT DEFAULT unique_rowid()` to `SERIAL`), that probably belongs in an external tool instead of in the database itself.

**Comment by tschottdorf** [comment] 2016-06-04 14:50
Oh, that's not what I had in mind. I mostly get tripped up by the slightly
different syntaxes for indexes. Taking it much further than that sounds
like a bigger project and not worth it (and a half-baked solution that
would make me happy is also not worth pursuing, I think).

On Sat, Jun 4, 2016 at 10:47 AM Ben Darnell <notifications@github.com>
wrote:

> That doesn't sound like the job of SHOW CREATE TABLE. What changes did you
> have in mind? If the problem is that we normalize things to non-standard
> syntax when reconstructing the CREATE TABLE statement, we should probably
> fix that. But if you're talking about translating a cockroachdb table to a
> postgres table (e.g. changing INT DEFAULT unique_rowid() to SERIAL), that
> probably belongs in an external tool instead of in the database itself.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6917#issuecomment-223759481>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135IUfbn-PbR5ID06Nuyh0A5KfdA-bks5qIY_8gaJpZM4Infv9>
> .
>
-- 

-- Tobias

**Comment by bdarnell** [comment] 2016-06-04 14:57
What are those differences? I thought our index syntax was close enough to postgresql's that i was using their docs instead of ours for a while :)

**Comment by mjibson** [comment] 2016-06-04 15:04
https://github.com/cockroachdb/cockroach/blob/master/sql/show_test.go contains many tests for `SHOW CREATE TABLE`. Is there a need to move them to the LogicTest?

**Comment by knz** [comment] 2016-06-04 20:10
Closed #7047 since this is already tested. Not sure if this issue should remain open.

**Comment by knz** [comment] 2016-06-09 19:29
Closing for now, feel free to reopen as needed.

**Closed by knz** 2016-06-09 19:29 UTC
Labels: easy, helpwanted
