### ISSUE TITLE
AS OF SYSTEM TIME should be allowed for create table as

### ISSUE THREAD

**Issue by leomkkwan** [cockroachdb/cockroach#41855] opened 2019-10-23 13:29 UTC
Trying to use create table as select to store result for a long query. To decrease conflicts, as of system time is in the query. 

`create table Test as Select * from Test2 as of system time ('-1s');`

However, this SQL Error pops.

`SQL Error [42601]: ERROR: AS OF SYSTEM TIME must be provided on a top-level statement`

This restriction for "as of system time" may be a little bit relax, another example is "explain"

```
explain Select * from Test2 as of system time ('-1s');
SQL Error [42601]: ERROR: AS OF SYSTEM TIME must be provided on a top-level statement
```

**Comment by ajwerner** [comment] 2019-10-23 13:44
I’m closing this as a duplicate of #39275. If that issue does not capture your intent please feel free to add commentary there or reopen this issue explaining how it differs.

Thanks for reporting your experience!

**Closed by ajwerner** 2019-10-23 13:44 UTC
