### ISSUE TITLE
sql: make builtin functions work on bytes

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#2686] opened 2015-09-27 21:26 UTC
eg: `CONCAT`, `LEFT`, `RIGHT`, `RPAD` etc... should all manipulate `BYTES` as well. I believe mysql considers `BYTES` or `VARBINARY` as just plain strings when using those, ignoring encoding.

I've come to need those for https://github.com/cockroachdb/examples-go/pull/13

This would also address [this TODO](https://github.com/cockroachdb/cockroach/blob/master/sql/parser/builtins.go#L90)

**Comment by knz** [comment] 2016-06-06 16:11
Duplicate of #2042.

**Closed by knz** 2016-06-06 16:11 UTC
Labels: enhancement, sql-semantics
