### ISSUE TITLE
sql: transaction is too large error during batch insert with background read requests

### ISSUE THREAD

**Issue by chessman** [cockroachdb/cockroach#29253] opened 2018-08-29 10:46 UTC
- Which version of CockroachDB are you using?

CCL v2.0.5 @ 2018/08/13 17:59:42 (go1.10)

- What did you do?

1. Create a table with 3 columns (primary key, foreign key, secondary index).
2. Create a background routine which selects from the table.
3. Try to batch insert 1000 rows.

I've made a complete reproduction:
https://gist.github.com/chessman/739424c341b4d7821661d4468be7ae2f

The behavior may be worse or better if you change select intensity or add more columns to the table.

- What did you expect to see?

Insert successfully completed.

- What did you see instead?

`pq: transaction is too large to complete; try splitting into pieces`

But the data is actually inserted into the table.

- What was the impact?

It is hard to choose a batch size because it depends not only on data size but on read requests. I can't be sure that my batch size is not too large in production during heavy read.

**Comment by knz** [comment] 2018-09-01 21:36
Hi @chessman, thank you for your interest in CockroachDB.
This is a known limitation in CockroachDB 2.0, which is to be lifted in CockroachDB 2.1. Feel free to download our recent 2.1 beta release and try it out, and let us know if that resolves your issue.

**Comment by chessman** [comment] 2018-09-03 10:04
Hi @knz. I tried `CCL v2.1.0-beta.20180827 @ 2018/08/27 17:37:58 (go1.10.3)` and still can reproduce this issue.

**Comment by knz** [comment] 2018-09-04 18:54
Ok thanks for checking.

@justinj can you take this over? thanks

**Comment by justinj** [comment] 2018-09-05 17:21
I can confirm that this seems to be a real problem but it's beyond my area of expertise - going to pass off to @nvanbenschoten who might have more insight regarding this kind of thing.

**Comment by nvanbenschoten** [comment] 2018-09-05 17:47
Hi @chessman, thanks for filing this issue. What you're observing is a configurable size limitation for transactions that need to be restarted. This limitation will only be hit when the transaction hits a serializable retry error, which is why it appears to "be worse or better if you change select intensity or add more columns to the table."

You can adjust this limit using the `kv.transaction.max_refresh_spans_bytes` cluster setting. For instance, you can try running `SET CLUSTER SETTING kv.transaction.max_refresh_spans_bytes=1e6;` and seeing if the error goes away.

I'm going to close this individual issue as it is related to https://github.com/cockroachdb/cockroach/issues/15849, but please continue to post here if you have other questions or would like to update us on your progress.

**Comment by nvanbenschoten** [comment] 2018-09-06 18:44
> Rows are actually inserted despite the error now.

That absolutely should not be happening. Just like any other non-retryable error, this error should put you in a failed txn state where ROLLBACK is the only acceptable statement. Could you please confirm that rows that you inserted in a transaction which hits this "transaction is too large to complete" error are actually inserted and visible outside of the transaction?

**Comment by chessman** [comment] 2018-09-06 20:11
Yes, I can confirm that. I print the rows count after failed a insert:
https://gist.github.com/chessman/739424c341b4d7821661d4468be7ae2f#file-main-go-L88

```
insert: 1
list: 1
...
list: 18
insert: 1 err: pq: transaction is too large to complete; try splitting into pieces
Number of rows: 1000
```
No inserts were finished successfully but there are 1000 rows.

**Comment by knz** [comment] 2018-09-06 21:43
we may need to re-open this cc @jordanlewis

**Comment by nvanbenschoten** [comment] 2018-09-06 21:47
Thanks for the script @chessman! I was able to reproduce what you are seeing and found the bug. The problem was that we were detecting that a transaction was probably too large to complete even after it had already commited. I'll be sending a fix shortly.

**Closed** 2018-09-11 05:38 UTC
Labels: A-core-kv, C-bug, O-community, S-0-visible-logical-error
