### ISSUE TITLE
pgwire: pgx client encounters "SimpleQuery not allowed while in extended protocol mode"

### ISSUE THREAD

**Issue by SpeedyCoder** [cockroachdb/cockroach#32501] opened 2018-11-20 17:16 UTC
We have an application that is reading an event stream and projecting data into the database. It has been crashing a lot with the following error

```ERROR: SimpleQuery not allowed while in extended protocol mode (SQLSTATE 08P01)```

After starting again the application is able to move forward, but then it crashes again when processing a different event. The application is using the go `pgx` driver (https://github.com/jackc/pgx) and the go `kallax` ORM (https://github.com/src-d/go-kallax) to access the database. I think the problem is with updating/creating the objects in a transaction.

We are running a secure 3 node cluster on version `2.1.1` (although I've first seen the issues on version `2.1.0`).  The nodes are also logging the following error after starting up, though I'm not sure if that's related

```
+ exec /cockroach/cockroach start --logtostderr=WARNING --certs-dir /cockroach/cockroach-certs --advertise-addr cockroachdb-2.cockroachdb.partner.svc.cluster.local --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%
W181120 16:10:25.977018 12 base/addr_validation.go:293  [n?] listen address "::" not in node certificate (IP=127.0.0.1; DNS=localhost,cockroachdb-2.cockroachdb.partner.svc.cluster.local,cockroachdb-2.cockroachdb,cockroachdb-proxy,cockroachdb-proxy.partner.svc.cluster.local; CN=node)
Secure node-node and SQL connections are likely to fail.
Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
*
* WARNING: [n?] listen address "::" not in node certificate (IP=127.0.0.1; DNS=localhost,cockroachdb-2.cockroachdb.partner.svc.cluster.local,cockroachdb-2.cockroachdb,cockroachdb-proxy,cockroachdb-proxy.partner.svc.cluster.local; CN=node)
* Secure node-node and SQL connections are likely to fail.
* Consider extending the node certificate or tweak --listen-addr/--advertise-addr.
```

The cluster is running on Kubernetes with manifests based on examples from this repo. I can't recreate the issue right now, but I can share the code and manifests with you.

**Comment by rytaft** [comment] 2018-11-20 18:58
Thanks for submitting this issue, @SpeedyCoder. Please let us know if/when you are able to reproduce the issue.

For context, this issue originated as a discussion on Gitter. cc @andreimatei and @knz who may have an idea about interactions with `pgx`. cc @a-robinson regarding possible issues with the Kubernetes manifest.

**Comment by andreimatei** [comment] 2018-11-21 02:49
A binary that reproduces the problem would help a lot, or also a packet capture (e.g. with Wireshark) for one of the connections that encounters the error.
Separately, we can also look at it on our side by auditing the pgx code and seeing if/when it sends "simple query" messages inside a "extended protocol" block. I don't know who that falls on, though. Assigning to @mjibson  for triage since I hear he's doing other pgwire work.

**Comment by mjibson** [comment] 2018-11-21 08:18
I'm not yet convinced this is a cockroach problem. Incorrect use of a connection pool or multiple go routines using the same connection could cause something like this from the application side. I'm unlikely to investigate this more without a reliable repro that we are able to run ourselves.

**Comment by knz** [comment] 2018-11-21 09:57
@SpeedyCoder can you please provide a small test program that reproduces the problem without interaction?

Barring this, can you capture a packet trace (via eg `tcpdump`, Wireshark or equivalent technology) of the client conversing with CockroachDB using an insecure connection, and share this with us?

Without this information we fear we cannot help you further. Thank you in advance!

**Comment by SpeedyCoder** [comment] 2018-11-21 15:30
Sorry, I'm really struggling to recreate the issue again even with the same setup. It's quite confusing. I can probably share the code that was failing with you, but I'm not sure that's gonna be helpful.

Do you guys have any idea why we are seeing the warning about the listen address not being in the node certificate? We are running the container with the following command
```
        command:
        - "/bin/bash"
        - "-ecx"
        - "exec /cockroach/cockroach start --logtostderr=WARNING --certs-dir /cockroach/cockroach-certs --advertise-addr $(hostname -f) --http-addr 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%"
```
so the `--advertise-addr` is set. I've tried setting the `--listen-addr` to `0.0.0.0`, but that didn't have any effect. Setting it to `$(hostname -f)` resolved to an IP address and complained again. The cluster seems to be working fine otherwise, it's just not very comforting seeing that message and I don't really have any idea how to get rid of it... 😅

**Comment by knz** [comment] 2018-11-21 16:07
Thanks for asking about the certificate address. However the folk who are looking at this issue about the client error are not expert with SSL certificates, so it's better to start a separate discussion thread.

(Also if you want to capture a packet trace you'll need to enable insecure client/server communication. We can't analyze packet traces over secure connections.)

**Comment by knz** [comment] 2018-11-21 16:08
I filed issue #32539.

**Comment by andreimatei** [comment] 2018-11-21 18:11
I think there's a good chance that @mjibson's speculation that a connection is being used concurrently across multiple go routines might be on the money. To the extent that you have visibility into the layers of your stack, keep an eye out for that.

**Comment by jordanlewis** [comment] 2019-05-01 05:11
Closing - if you see more problems like this @SpeedyCoder feel free to reopen.

**Closed by jordanlewis** 2019-05-01 05:11 UTC
Labels: A-sql-pgwire, C-investigation, O-community
