### ISSUE TITLE
sqlstats: retain stats based on a time period

### ISSUE THREAD

**Issue by xinhaoz** [cockroachdb/cockroach#89454] opened 2022-10-05 23:14 UTC
Currently, the only scenario we delete sql stats from the system table (other than initiating a reset) is when we reach the row limit set by `sql.stats.persisted_rows.max`, at which point we evict entries based on aggregation (oldest entries first). We should investigate whether or not we would like to change this retention to be based on a time period (along with a hard limit). This could potentially reduce the amount of storage used by the system tables.

This could also help reduce the issues described [here](https://github.com/cockroachdb/cockroach/issues/89452), assuming the amount of stats collected within the time period is much less than the hard cap.

Jira issue: CRDB-20260

**Comment by rafiss** [comment] 2022-10-06 01:25
Let's consider using row-level TTL for this. It definitely needs some investigation first, since it hooks up the jobs framework to system tables, which seems a bit fraught, but it's worth considering.

**Comment by kevin-v-ngo** [comment] 2022-10-10 15:07
Agree this should be updated. This is a dup of https://github.com/cockroachdb/cockroach/issues/80523

**Comment by kevin-v-ngo** [comment] 2022-10-17 15:47
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/80523

**Closed by kevin-v-ngo** 2022-10-17 15:47 UTC
Labels: C-enhancement, A-sql-observability, T-sql-observability
