### ISSUE TITLE
circleci/ui: PhantomJS times out while running karma tests

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#9052] opened 2016-09-01 22:33 UTC
Found in https://circleci.com/gh/cockroachdb/cockroach/22185:

```
> node install.js
PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
[...]
karma start

01 09 2016 22:01:30.650:INFO [karma]: Karma v1.2.0 server started at http://localhost:9876/

01 09 2016 22:01:30.653:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency

01 09 2016 22:01:30.671:INFO [launcher]: Starting browser PhantomJS

01 09 2016 22:01:36.057:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#7dLRFSZKJneYrWd3AAAA with id 20944495

01 09 2016 22:01:36.175:WARN [web-server]: 404: /base/jspm_packages/system-polyfills.js

PhantomJS 2.1.1 (Linux 0.0.0) WARN: 'TypeScript', '[Warning]', 'http://localhost:9876/base/typings/modules/chai/index.d.ts -> global could not be resolved'

01 09 2016 22:01:49.703:WARN [PhantomJS 2.1.1 (Linux 0.0.0)]: Disconnected (1 times), because no message in 10000 ms.

PhantomJS 2.1.1 (Linux 0.0.0) ERROR

  Disconnected, because no message in 10000 ms.

Makefile:70: recipe for target 'test' failed
make: *** [test] Error 1
ui/ui.go:21: running "make": exit status 2
```

**Comment by maxlang** [comment] 2016-09-07 21:06
I don't think the issue is with PhantomJS itself, but rather that the tests just never ran.

Based on comments in the following issues I'm going to increase the karma timeout.

https://github.com/karma-runner/karma-phantomjs-launcher/issues/126
https://github.com/karma-runner/karma/issues/598

There's also some discussion of PhantomJS running out of memory if this issue reoccurs.
http://stackoverflow.com/questions/24119506/karma-jasmine-times-out-without-running-tests

**Comment by tamird** [comment] 2016-09-07 21:08
Please don't increase the timeout. There's no evidence here to indicate that it would have worked with a higher timeout.

Something got wedged and died, I'm not sure it's worth investigating further just yet.

**Comment by maxlang** [comment] 2016-09-07 21:09
In that case, should we close the issue for now?

**Comment by tamird** [comment] 2016-09-07 21:10
I'll leave it up to you and @knz. It might be good to keep it open to avoid duplicates if this does become more common.

**Comment by maxlang** [comment] 2016-09-07 21:16
As another datapoint, setting `browserNoActivityTimeout` to 2s (default is 10s) caused the tests to fail for me locally, but they succeeded at 3s.

**Comment by knz** [comment] 2016-09-07 21:17
(I haven't encountered the issue again after that original occurrence. I don't feel strongly either way. Perhaps we should leave the issue open until 1.0 is released and then we can close all issues we could not reproduce during pre-1.0 cleanups)

**Comment by maxlang** [comment] 2016-09-07 21:19
I'm fine leaving open for now. It's possible that if we add more UI tests this will occur more frequently.

**Comment by tamird** [comment] 2016-10-04 17:55
Closing as stale.

**Closed by tamird** 2016-10-04 17:55 UTC
Labels: test-failure
