### ISSUE TITLE
sql: support `'{abc}'` syntax for uuid[] literal

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#54693] opened 2020-09-23 13:48 UTC
pg supports (and, importantly, emits) `uuid[]` literals in the form `'{abc123-abc...}'`

Cockroach currently does not, simply complaining that it is a `string`, since we do not implicitly convert the string to `uuid[]`, though appending an explicit cast works (e.g. `'{abc123-...}'::uuid[]`). 

Appending a cast or using the `ARRAY[...]` syntax provide alternatives for users writing queries by hand, but unfortunately some tools, like `pg_dump` emit the `'{abc...}'` form.

**Comment by jordanlewis** [comment] 2020-09-23 13:58
Duplicate of #54672

**Closed by jordanlewis** 2020-09-23 13:58 UTC
Labels: A-sql-syntax, C-enhancement
