### ISSUE TITLE
sql: leaked error to client: Rejecting command with timestamp in the future

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#3087] opened 2015-11-10 17:42 UTC
The following error occurs occasionally on a multi-node cluster:
```
error running blockwriter 1a33d0d0-debe-4713-b832-da510c7a452d: storage/store.go:1219: Rejecting command with timestamp in the future: 1447175507729080005 (304.348431ms ahead)
goroutine 51 [running]:
```
This error does not cause the server to crash, but does leak back to the client.

Most Interestingly, this occurred on a system where all six nodes were running on the same cluster; thus, all nodes use the same system clock.

**Comment by tamird** [comment] 2015-11-10 17:50
cc @petermattis - you ran into this in the latest lease work

**Comment by tschottdorf** [comment] 2015-11-11 22:29
I suspected this piece of code on lease acquisition:

```go
	// If this replica is a new holder of the lease, update the
	// low water mark in the timestamp cache. We add the maximum
	// clock offset to account for any difference in clocks
	// between the expiration (set by a remote node) and this
	// node.
	if r.getLease().Replica.StoreID == r.store.StoreID() &&
		prevLease.Replica.StoreID != r.getLease().Replica.StoreID {
		r.tsCache.SetLowWater(prevLease.Expiration.Add(int64(r.store.Clock().MaxOffset()), 0))
		log.Infof("range %d: new leader lease %s", rangeID, args.Lease)
	}
```

because that would push incoming commands higher than the clock, potentially at least. Hard to imagine how you'd end up with `>300ms` when the `MaxOffset` is `250ms`.

**Comment by tschottdorf** [comment] 2016-01-08 10:15
From the nightly logic test 2016-01-08-00:00:01

```
--- FAIL: TestLogic (21.67s)
logic_test.go:470:
    test/index/orderby_nosort/10/slt_good_11.test:24034: expected success, but found pq: storage/store.go:1268: Rejecting command with timestamp in the future: 1452229415211951812 (21.724262344s ahead)
FAIL
```

**Comment by petermattis** [comment] 2016-01-08 13:39
A clock 21s ahead seems quite a bit more worrisome than one that is 304ms
ahead.

**Comment by tschottdorf** [comment] 2016-01-08 13:51
Yep. Once the test fixing bonanza is winding down I'd like to add some traps in the HLC code which catch this stuff in the act as it happens with a stack trace to work off of. We've never caught it in the act but repeated adding of `MaxOffset` to a timestamp in a tight loop somewhere could be the culprit, in which case the above should pin it down.

**Comment by tschottdorf** [comment] 2016-02-17 02:57
I should get back and do what I said above. FWIW, my current suspicion is this:

`	tc.lowWater.WallTime += clock.MaxOffset().Nanoseconds()`

in the timestamp cache. Can't explain how that would go above the 250ms yet, but it's a starting point.

**Comment by vivekmenezes** [comment] 2016-02-17 02:58
https://circleci.com/gh/cockroachdb/cockroach/12896

is an example of this failure.

**Comment by vivekmenezes** [comment] 2016-02-17 03:04
Wouldn't surprise me if this has something to do with restarting a node as the test that is failing suggests.

**Comment by tschottdorf** [comment] 2016-02-17 03:14
Yes, the theory would be that some combination of a new leader lease and a new timestamp cache (both of which arbitrarily add MaxOffset to various things) can taint one clock. Just hard to pin down the exact order of events without something that is somewhat reproductible.

**Comment by tschottdorf** [comment] 2016-03-11 19:43
https://circleci.com/gh/petermattis/cockroach/460

**Comment by tschottdorf** [comment] 2016-03-11 20:36
https://circleci.com/gh/cockroachdb/cockroach/14371?utm_campaign=build-failed&utm_medium=email&utm_source=notification

Seems to happen more regularly now in acceptance tests.

**Comment by vivekmenezes** [comment] 2016-03-14 03:04
https://circleci.com/gh/cockroachdb/cockroach/14416

**Comment by tschottdorf** [comment] 2016-03-14 15:54
a record-high seen on the photos app (single node):

```
I160314 11:50:26.601526 user.go:149  failed to run list comments op for 40129: pq: storage/store.go:1531: Rejecting command with timestamp in the future: 1457970630537435000 (3.936211796s ahead)
```

**Comment by tschottdorf** [comment] 2016-03-16 05:25
My last post made me think that perhaps weird local wall times are the whole reason we're seeing this in clusters without clock skew (such as the acceptance tests).

Since #5019 has landed, we can instrument `timeutil.Now()` so that it logs when the wall time moves backwards. The hope would be that the next time we see this in CI (or wherever), we find a corresponding log entry that tells us something about the physical clock. If not, we know we have to keep looking.

@knz assigning you as the resident timestamp expert, but feel free to put this on someone else's plate - should be straightforward enough.

**Comment by knz** [comment] 2016-03-16 17:32
@tschottdorf how do you suggest we go about telling CI to use the check from #5301 once that's merged? Where do we set these build flags / env vars for CI?

**Comment by tamird** [comment] 2016-03-16 17:36
`make foo bar baz GOFLAGS='-tags hello world'`

**Comment by tschottdorf** [comment] 2016-03-16 17:39
As commented, I'd like this check to always be active, at least for now.

**Comment by knz** [comment] 2016-03-16 21:46
Ok #5301 is merged so we just wait for the warning to come up?

**Comment by tschottdorf** [comment] 2016-03-16 22:14
Yep! Fingers crossed that we actually do see the log message you added.

**Comment by knz** [comment] 2016-03-17 20:58
Just checked, in the two runs linked from #5190 and #5212 there is no warning coming up about a clock backward jump.

**Comment by knz** [comment] 2016-03-18 11:00
Summary of yesterday's discussion with @tschortdoff: it seems that the issue is caused by sudden clock forward jumps in CircleCI. We see the wall clock jumping forward in blocks of 200-300ms often, and sometimes up to 3s. This is compatible with the theory that the CI VMs are overloaded and "sleep" for seconds at a time before waking up again.

**Comment by knz** [comment] 2016-03-18 11:09
Summary of yesterday's discussion with @tschortdoff: it seems that the issue is caused by sudden clock forward jumps in CircleCI. We see the wall clock jumping forward in blocks of 200-300ms often, and sometimes up to 3s. This is compatible with the theory that the CI VMs are overloaded and "sleep" for seconds at a time before waking up again.

Another observation that supports the theory: running offending tests this morning (when there is less CI activity overall) reveals no such error -- see https://circleci.com/gh/cockroachdb/cockroach/14786#artifacts for an example.

**Comment by tschottdorf** [comment] 2016-03-18 17:17
Is that really what we saw? We saw HLC timestamps suddenly jumping forward but no proven relation to wall times. If the machines did sleep for a second, I don't know how that would cause the "timestamp in the future errors".

Say node1 was stuck for a second, so its HLC 1s behind. It receives an event by node2 which is at the current time. When node1 made that timestamp, according to your theory, it took it off the physical clock. When node2 complains about the timestamp, it has also just checked its physical clock. This is inside Docker, so its physical clock timestamp can't be behind node2s wall time when it created the timestamp (assuming that if clocks are non-monotonous, they would also be non-monotonous on each on the nodes individually; something we that would've tripped the `timeutil` alarm).

That said, seeing `3s` (on Circle?) rules out all other explanations I've had, so maybe there is a way that this could happen. Did you have a theory for the precise mechanism?

**Comment by vivekmenezes** [comment] 2016-03-18 19:27
Could this issue be affecting us?

https://github.com/docker/toolbox/issues/193

I noticed that whenever this bug shows up all the log messages (often 2 or 3 reported drifts) print a drift time that is approximately the same time (off by a few milliseconds). Does look like a VM is off here and this issue has nothing to do with our implementation.

**Comment by tschottdorf** [comment] 2016-03-18 20:28
I don't doubt that the clocks on `CircleCI` are really slow, but what I'm arguing above is that the clocks do appear to be monotonically increasing (and there is only one clock in use in those tests). For that reason I don't see a mechanism that would create the errors we're seeing.

**Comment by knz** [comment] 2016-03-21 22:26
FWIW the reproducible in #5362 triggers the problem reliably, so we can instrument that further now. Any suggestion as to where to start? What about a warning every time `time.Now()` jumps *forwards* by more than 100ms?

**Comment by tschottdorf** [comment] 2016-03-21 22:52
That's a good one to check, though it's hard to ascertain whether that
happened because nobody wanted a timestamp for 300ms or because the clock
jumped.

**Comment by knz** [comment] 2016-03-22 17:22
Ok I rebased the testing in #5362 and cannot seem to reproduce the original issue any more. Were there any significant changes recently?

**Comment by petermattis** [comment] 2016-03-29 22:18
Running `block_writer` against a 4 node cluster on GCE just now and I saw this error: `2016/03/29 21:33:33 error running blockwriter e99fbdce-3fb2-4558-afd7-d0c255430102: pq: storage/store.go:1547: rejecting command with timestamp in the future: 1459287213701002474 (316.872283ms ahead)`

Just verified that `ntpd` is running on all of the nodes.

**Comment by petermattis** [comment] 2016-03-30 19:05
@tschottdorf This is easy to reproduce using `block_writer` on a GCE cluster. AFAICT, ntp is running on all of the machines and working properly. What info can I get you to debug this?

**Comment by tschottdorf** [comment] 2016-03-30 19:21
How often does it happen? What exact block writer are you running? I'll try
repro'ing tomorrow morning. If I get a reliable repro, I'm sure I can
figure this one out - that's always been the issue so far.

**Comment by petermattis** [comment] 2016-03-30 19:25
I'm running `examples-go/block_writer` with no options against a 4-node GCE cluster. I imagine it would happen on a 3-node cluster as well as one of the nodes is idle (due to rebalancing not working). The problem reproduces on average within a few minutes, though I've seen it take as long as 10min.

**Comment by petermattis** [comment] 2016-03-30 19:26
Oh, and the problem has reproduced about a dozen times now.

**Comment by tschottdorf** [comment] 2016-04-02 13:11
I'm running the thing against a three-node on my single GCE instance now, but I don't expect to see it there. Could you check your logs for occurrences of

`log.Warningf("remote wall time is too far ahead (%s) to be trustworthy - updating anyway", offset)`?

I don't trust the clocks on GCE enough to rule out that it's legitimate clock skew.
What happens if you run with a MaxOffset of 500ms (or whatever is solidly ahead of the offset these errors give you)?

**Comment by petermattis** [comment] 2016-04-02 14:38
This happened again on a fresh 4-node GCE cluster. The problem took 13m23s to reproduce this time:

```
2016/04/02 14:18:18 error running blockwriter 6de8c4b3-267e-4f75-81cf-0ac3787dc239: pq: storage/store.go:1552: rejecting command with timestamp in the future: 1459606697806619953 (250.691519ms ahead)
```

I used the same binary I previously used which has the tag `beta-20160330-17-ga8310e3-dirty`.

On node 1 I found the following log message:

```
W160402 14:18:17.554202 util/hlc/hlc.go:237  remote wall time is too far ahead (252.450544ms) to be trustworthy - updating anyway
```

Similarly on node 4:

```
W160402 14:18:17.552524 util/hlc/hlc.go:237  remote wall time is too far ahead (254.145199ms) to be trustworthy - updating anyway
```

Notice that these timestamps are very close to when the `block_writer` error occurred.

I'll try running again with a 500ms max-offset.

**Comment by tschottdorf** [comment] 2016-04-02 14:44
Btw, do you have any tooling for your cluster? We don't have terraform yet,
and doing it manually kind of irks me. Probably not too bad, but if you
have anything you can share, I'd appreciate it.

**Comment by petermattis** [comment] 2016-04-02 14:46
I have a small script based on the `cloud.sh` script that is floating around. Certainly nothing great. We really need better tooling to make starting, running and tearing down actual clusters easier.

**Comment by tschottdorf** [comment] 2016-04-02 14:54
Should be easier when @mberhault has gotten around to porting the AWS
terraform stuff to GCE.

**Comment by petermattis** [comment] 2016-04-03 00:49
`block_writer` ran for 30min without problem when the cluster was configured with a 500ms max-offset before the ssh session was accidentally killed. I'm going to restart it and leave it running in the background.

**Comment by petermattis** [comment] 2016-04-03 16:59
Encountered the same error with a 500ms max-offset, it just took longer to occur:

```
1h31m48s:  277.0/sec
2016/04/03 02:21:50 error running blockwriter fc99a641-d90c-4e3a-9819-d82df52e9fa0: pq: storage/store.go:1552: rejecting command with timestamp in the future: 1459650110972748223 (594.025242ms ahead)
```

Node 1:

```
W160403 02:21:50.377596 util/hlc/hlc.go:237  remote wall time is too far ahead (598.900689ms) to be trustworthy - updating anyway
```

Node 3:

```
W160403 02:21:50.378222 util/hlc/hlc.go:237  remote wall time is too far ahead (598.292164ms) to be trustworthy - updating anyway
```

Node 4:

```
W160403 02:21:50.371339 util/hlc/hlc.go:237  remote wall time is too far ahead (601.432347ms) to be trustworthy - updating anyway
```

The synchronized nature of these warnings is very suspicious. Note that node 2 did not contain an error, but that might be due to it not containing any range data (see other bug about our failure to rebalance). I also verified the nodes did appear to have activity just before this warning. For example, from node 4:

```
I160403 02:21:50.368884 storage/replica_command.go:1361  range 1: new leader lease replica {4 4 2} 2016-04-03 02:21:50.472748223 +0000 UTC 1.090772237s
W160403 02:21:50.371339 util/hlc/hlc.go:237  remote wall time is too far ahead (601.432347ms) to be trustworthy - updating anyway
```

**Comment by tschottdorf** [comment] 2016-04-03 19:11
Ok. My old theory is that this is caused by

```go
	if r.mu.leaderLease.Replica.StoreID == r.store.StoreID() &&
		prevLease.Replica.StoreID != r.mu.leaderLease.Replica.StoreID {
		r.mu.tsCache.SetLowWater(prevLease.Expiration.Add(int64(r.store.Clock().MaxOffset()), 0))
		log.Infof("range %d: new leader lease %s", r.RangeID, args.Lease)
	}
```

which, if it should happen twice in a row in close succession somehow, would inject timestamps into the system which are about `2*MaxOffset` in the future of the actual clocks.

Try changing to

```go
	if r.mu.leaderLease.Replica.StoreID == r.store.StoreID() &&
		prevLease.Replica.StoreID != r.mu.leaderLease.Replica.StoreID {
		newExpiration := prevLease.Expiration.Add(int64(r.store.Clock().MaxOffset()), 0)
		r.mu.tsCache.SetLowWater(newExpiration)
		log.Infof("range %d: new leader lease %s [lowWaterWallTime=%s, physicalTime=%s]", r.RangeID, args.Lease, time.Duration(newExpiration.WallTime), time.Duration(r.store.Clock().PhysicalNow()))
	}
```

**Comment by vivekmenezes** [comment] 2016-04-04 02:47
I noticed that we don't update the cache's latest value, and yet the latest
value influences the lowWater during eviction. Does it make sense to at
least try updating latest to the new lowWater in the same way it's done in
Clear() ? It would be nice to maintain the lowWater <= latest invariant.

**Comment by tschottdorf** [comment] 2016-04-04 06:16
Yeah, we could update `.latest` in `SetLowWater` if it's behind. Shouldn't change too much though.

**Comment by tschottdorf** [comment] 2016-04-04 08:21
Ok, we're zeroing in on something here. I'm running an idle single-node cluster:

```
I160404 04:14:19.723809 storage/replica_command.go:1379  range 1: irregular leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723296178s [lowWater=wallTime+1.24951872s] following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723296178s
I160404 04:14:19.724243 storage/replica_command.go:1379  range 41: irregular leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723269728s [lowWater=wallTime+1.249048204s] following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723269728s
I160404 04:14:19.724639 storage/replica_command.go:1379  range 14: irregular leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723467285s [lowWater=wallTime+1.248848232s] following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405488h14m20.723467285s
```

where the logging comes from

```diff
diff --git a/storage/replica_command.go b/storage/replica_command.go
index 2f48d82..63e88f3 100644
--- a/storage/replica_command.go
+++ b/storage/replica_command.go
@@ -1368,10 +1368,16 @@ func (r *Replica) LeaderLease(
        // clock offset to account for any difference in clocks
        // between the expiration (set by a remote node) and this
        // node.
-       if r.mu.leaderLease.Replica.StoreID == r.store.StoreID() &&
-               prevLease.Replica.StoreID != r.mu.leaderLease.Replica.StoreID {
-               r.mu.tsCache.SetLowWater(prevLease.Expiration.Add(int64(r.store.Clock().MaxOffset()), 0))
-               log.Infof("range %d: new leader lease %s", r.RangeID, args.Lease)
+       if r.mu.leaderLease.Replica.StoreID == r.store.StoreID() {
+               newExpiration := prevLease.Expiration.Add(int64(r.store.Clock().MaxOffset()), 0)
+               if prevLease.Replica.StoreID != r.mu.leaderLease.Replica.StoreID {
+                       log.Infof("range %d: new leader lease %s", r.RangeID, args.Lease)
+                       r.mu.tsCache.SetLowWater(newExpiration)
+               }
+               if wtOffset := time.Duration(newExpiration.WallTime - r.store.Clock().PhysicalNow()); wtOffset > r.store.Clock().MaxOffset() {
+                       log.Infof("range %d: irregular leader lease %s [lowWater=wallTime+%s] following %s", r.RangeID, args.Lease, wtOffset, prevLease)
+               }
        }

        return reply, nil
```

So what's happening here is that a lease is processed twice (note that the message quotes `prevLease=newLease`). But if the last lease didn't expire well in the past (in this case it's roughly 1s (the lease duration) in the future), the current code doesn't do what it thinks it's doing and injects outrageously high timestamps into the timestamp cache. Easy to fix, but I'm going to dig a little more and see why we're seeing this double requests - Raft replays are one candidate, but that should not happen on a singel node, and in particular not with the regularity at which I've seen these log messages, across variosu ranges.

**Closed** 2016-04-16 11:31 UTC
Labels: bug
