### ISSUE TITLE
storage: replication delay in new 3 node cluster

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7022] opened 2016-06-03 00:24 UTC
The delay in replicating the initial ranges feels too long in a local 3 node cluster. Reproduction steps:

1. Run `roachdemo`
2. Create 3 nodes
3. Visit the admin UI nodes page
4. Witness how long it takes for the nodes to all report 5 replicas

I would expect the replication to occur within seconds, but it seems to take closer to 30 seconds. I could have sworn this worked smoother in the past.

**Comment by WillHaack** [comment] 2016-06-15 18:08
I ran into this problem when trying to create local Multinode benchmark tests. I'm working off of Bram's PR called storepool https://github.com/cockroachdb/cockroach/pull/7147 which changes the way we do replication, and I was able to reduce the initial replication time to ~11s by changing defaultScanMaxIdleTime from 5 seconds to 1 second.
 I also reduced timeoutForDeclinedReservations from 10s to 1s.

**Comment by petermattis** [comment] 2016-06-15 19:23
I wonder why the `defaultScanMaxIdleTime` matters. I thought when a new node was connected via gossip that we would kick the `replicateQueue` which would pull stuff out of purgatory. Is that not happening?

@BramGrunier Why is the default `timeoutForDeclinedReservations` set to 10s? I'm having deja-vu here. I think a delay of 1s or less would be appropriate.

**Comment by d4l3k** [comment] 2016-06-15 20:15
@BramGruneir

**Comment by BramGruneir** [comment] 2016-06-15 20:21
timeoutForDeclinedReservations is 10s because we haven't tuned it yet.  I thought 10s would be a good starting point.  I will be trying a collection of different values in the next week to see what works best and it might just be 1sec.

But to be clear, this is NOT causing the delay you're seeing right now.  The reservation system isn't merged yet.  Should be very shortly and it doesn't cause any new delays to startup up-replication.  There is a fix I've already added to my branch that deals with @WillHaack's problem writing his tests.

**Comment by petermattis** [comment] 2016-06-21 01:14
So my earlier comment about why `scan-max-idle-time` shouldn't matter was revealing my faulty knowledge. A new node being discovered via gossip will cause any replicas in replicate queue purgatory to be retried. But we still limit how fast we scan replicas in the first place. In particular, by default we only scan replicas at a rate such that we examine every replica once every 10 min, but with a maximum inter-replica time of 5 sec. 

With our current system table setup, we see 5 ranges at startup and an initial replication time of 25-30 sec. For some reason, there is sometimes an initial replication delay of 5 sec for the first range which I haven't tracked down yet. After that, you can see the remaining ranges get replicated at 5 sec intervals. Clearly, the current heuristics and mechanism are not great for small/new clusters. 

It seems reasonable to lower `defaultScanMaxIdleTime` to `1s`. Or lower. A node with 1TB of storage could hold 16K replicas. This translates to scanning a replica once every 36ms. Or perhaps `replicaScanner` should have different modes and scan all replicas faster when a new node is discovered.

**Comment by tamird** [comment] 2016-06-21 01:22
A more radical suggestion: can we step away from the scanner-powered replica queue and make things more event driven? There's a relatively narrow list of events that require replicas to be placed into the replicate queue.

**Comment by petermattis** [comment] 2016-06-21 01:27
Yes, we can. We do something similar for the split and raft log gc queues. Those queues still utilize the replica scanner, but are also populated by other events. Question is what the right events are for replication. You wouldn't want to examine every replica when a new node appears via gossip. Or maybe you would (up to some limit).

**Comment by tamird** [comment] 2016-06-21 01:29
Replica creation might be a good start.
On Jun 20, 2016 21:27, "Peter Mattis" <notifications@github.com> wrote:

Yes, we can. We do something similar for the split and raft log gc queues.
Those queues still utilize the replica scanner, but are also populated by
other events. Question is what the right events are for replication. You
wouldn't want to examine every replica when a new node appears via gossip.
Or maybe you would (up to some limit).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/cockroachdb/cockroach/issues/7022#issuecomment-227316557>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABdsPCg1FN2M5X7wm2tH5n3YJ6KrmTRtks5qNz4TgaJpZM4ItGj2>
.

**Comment by petermattis** [comment] 2016-06-21 01:31
Not sure I follow. The initial range splits happen very quickly before the second node is connected.

**Comment by tamird** [comment] 2016-06-21 01:53
Perhaps I misunderstood your earlier comment?

>  A new node being discovered via gossip will cause any replicas in replicate queue purgatory to be retried. But we still limit how fast we scan replicas in the first place.

What do you mean by "in the first place"? If the replicas are in the replicate queue purgatory when the second node is connected, they will all immediately be sent to `processReplica`, and should replicate as quickly as the queue can process them.

If the problem is that they are not yet in the replicate queue purgatory when the second node connects (which is how I interpreted your comment) then enqueuing the right side of every split would help this situation (which is what I was suggesting in my previous comment).

**Comment by petermattis** [comment] 2016-06-21 12:45
@tamird Ah, that's a good point about enqueuing after a split. We actually want to enqueue both the left and right sides after the split because the replicate queue won't process (or queue) ranges that require a split. With this done, initial replication drops from ~30s to ~2s.

**Comment by BramGruneir** [comment] 2016-06-21 14:30
I love the idea of the replicate queue being more event driven, and it clearly helps in the initial case, but once fully replicated, there's no point in enqueuing after a split.

**Closed** 2016-06-22 12:21 UTC
