### ISSUE TITLE
pgwire: python3 py-postgresql driver error

### ISSUE THREAD

**Issue by catroot** [cockroachdb/cockroach#13191] opened 2017-01-27 10:37 UTC
Tried to connect using py-postgresql driver
```
postgresql.exceptions.ClientCannotConnectError: could not establish connection to server
  CODE: 08001
  LOCATION: CLIENT
CONNECTION: [failed]
  failures[0]:
    NOSSL socket('192.168.8.170', 26257)
    postgresql.exceptions.ProtocolError: expected message of types b'K', but received b'Z' instead
      CODE: 08P01
      LOCATION: CLIENT
CONNECTOR: [IP4] pq://root@192.168.8.170:26257
  category: None
DRIVER: postgresql.driver.pq3.Driver
```

**Comment by jordanlewis** [comment] 2017-01-27 17:18
Hi @catroot, thanks for your report. I've been able to reproduce your issue - we'll investigate this soon. In the meantime, `psycopg2` is a good bet for a compatible Python postgres driver.

**Comment by jordanlewis** [comment] 2017-01-27 18:43
This seems to be a small bug in `py-postgresql`, which requires a `BackendKeyData` message be sent during connection initialization. I don't think that this message is strictly required by the Postgres wire protocol format, so I've opened https://github.com/python-postgres/fe/issues/84 for the library author to investigate further.

**Comment by jordanlewis** [comment] 2017-01-27 20:12
This will also be fixed by #13009.

**Comment by catroot** [comment] 2017-01-28 07:13
Thank you.

**Comment by vivekmenezes** [comment] 2017-08-10 17:18
Bilal take a look  #13009 for the discussion on how cancellation can fix this issue. Assigning to you. Thanks!

**Comment by jordanlewis** [comment] 2018-02-22 18:20
Unfortunately, this isn't going to make it into 2.0 either. In 2.1, we should look at @asubiotto's recommended approach from #13009 - to send a random query id to just unstick problems with the protocol. Cancellation won't work against that query id, but at least drivers like this one will be able to connect.

**Comment by knz** [comment] 2018-07-22 08:30
cc @BramGruneir to integrate in the meta lists

**Comment by jordanlewis** [comment] 2020-10-05 22:44
Hey @rafiss, could we fix this one by issuing a BackendKeyData response with obviously wrong values like 0, 0? Or will that cause issues for clients? I feel like it could be fine - clients already receive an error when trying to cancel a query using the Postgres cancellation protocol, so if they tried to use our obviously false BackendKeyData after such a PR no behavior would really change...

**Comment by rafiss** [comment] 2020-12-29 03:33
Sorry I missed your message in October! I think we could use an approach like that. Looks like that's what #13009 did, but it didn't reach the finish line. I don't quite understand why not, but I am in favor of bringing it back for the 21.1 release.

**Comment by rafiss** [comment] 2020-12-29 03:34
@jordanlewis Sorry I missed your message in October! I think we could use an approach like that. Looks like that's what #13009 did, but it didn't reach the finish line. I don't quite understand why not, but I am in favor of bringing it back for the 21.1 release.

**Closed** 2021-02-10 22:22 UTC
Labels: A-sql-pgcompat, A-sql-pgwire, C-enhancement, S-4, meta-issue
