### ISSUE TITLE
builtins: support postgre's FORMAT function

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#87260] opened 2022-09-01 12:04 UTC
See:
https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-FORMAT

This is a much simpler interface than `to_char` and thus would be a nice low hanging fruit to pluck.

Related to #3781.
Discussed for Piccolo ORM compatibility here: https://github.com/piccolo-orm/piccolo/issues/607#issuecomment-1233903763

cc @rafiss 

Jira issue: CRDB-19242

**Comment by rafiss** [comment] 2022-09-01 12:44
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/68330 -- which was closed by https://github.com/cockroachdb/cockroach/pull/84107. If there's more work needed, please reopen with extra details.

**Closed by rafiss** 2022-09-01 12:44 UTC
Labels: C-enhancement, A-sql-pgcompat, A-sql-builtins, T-sql-experience
