### ISSUE TITLE
Test failure in CI build 4662

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1691] opened 2015-07-15 22:08 UTC
The following test appears to have failed:

[#4662](https://circleci.com/gh/cockroachdb/cockroach/4662):

```
c997834159912209.37  127.0.0.1:0  22:03:54.159978  169.761µs  node                            server/node.go:489
c997834159912209.37  127.0.0.1:0  22:03:54.160008  136.295µs  ·executing InternalRangeLookup  storage/store.go:1237
c997834159912209.37  127.0.0.1:0  22:03:54.160019  124.036µs  ··read path                     storage/range.go:520

I0715 22:03:54.160428      72 kv/range_cache.go:149 adding descriptor: key="\x00\x00meta2db 2" desc=raft_id:1 start_key:"" end_key:"db 2" replicas:<node_id:1 store_id:1 > 
panic: test timed out after 30s

goroutine 60213 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [semacquire]:
sync.(*Cond).Wait(0xc2081ca3c0)
	/usr/src/go/src/sync/cond.go:62 +0x9e
--
	/go/src/github.com/cockroachdb/cockroach/ts/db.go:77 +0x141
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:79 +0x5d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0xfc
FAIL	github.com/cockroachdb/cockroach/client	30.047s
?   	github.com/cockroachdb/cockroach/client/rpc	[no test files]
?   	github.com/cockroachdb/cockroach/examples/kv_bank	[no test files]
?   	github.com/cockroachdb/cockroach/examples/sql_bank	[no test files]
=== RUN TestClientGossip
I0715 22:03:28.954375      87 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:03:28.985139      87 gossip/gossip.go:166 gossiping node descriptor node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:03:28.985221      87 base/context.go:141 setting up TLS from certificates directory: test_certs
I0715 22:03:29.013735      87 gossip/gossip.go:166 gossiping node descriptor node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 
I0715 22:03:29.015806      87 base/context.go:103 setting up TLS from certificates directory: test_certs
I0715 22:03:29.051513      87 gossip/server.go:113 gossip: received infostore with 3 info(s): info "node:2": node_id:2 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> , info "local-key": local value, info "node:1": node_id:1 address:<network:"tcp" address:"127.0.0.1:0" > attrs:<> 

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-07-15 22:12
Another dupe of #1684

**Closed by bdarnell** 2015-07-15 22:12 UTC
Labels: test-failure
