### ISSUE TITLE
sql/parser: ON CONFLICT panic "interface conversion: interface is nil, not []string"

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#6765] opened 2016-05-18 13:27 UTC
Looks like it panics if you don't specify the column list for the on-conflict. 
Reproduces by adding to sql/testdata/upsert:
```diff
+statement ok
+INSERT INTO kv VALUES (13, 13), (7, 8) ON CONFLICT DO NOTHING
+
```
I think it's coming from `OnConflict{Columns: NameList($3.strs())`, but unfortunately recovered and rethrown errors don't have their original stack traces.

**Comment by paperstreet** [comment] 2016-05-18 16:20
Duplicate of https://github.com/cockroachdb/cockroach/issues/6732

**Closed by paperstreet** 2016-05-18 16:20 UTC
Labels: bug
