### ISSUE TITLE
webui: logs in ui are truncated

### ISSUE THREAD

**Issue by tomholub** [cockroachdb/cockroach#30269] opened 2018-09-16 21:08 UTC
Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
v2.0.4 on 5 nodes, geo-distributed cluster

- What did you do?
Woke up to a cockroach unresponsive alert around Sep 16 19:50 UTC (all servers run UTC)

- What did you expect to see?
Maybe one server unresponsive?

- What did you see instead?
Whole cluster unresponsive. All recovered around 4 minutes later.

- What was the impact?
Could not issue basic queries for a few minutes on the whole cluster. Our client checks DB liveliness with `SELECT 1+2;` which did not return.

[node-1.txt](https://github.com/cockroachdb/cockroach/files/2387004/node-1.txt)
[node-3.txt](https://github.com/cockroachdb/cockroach/files/2387005/node-3.txt)
[node-4.txt](https://github.com/cockroachdb/cockroach/files/2387006/node-4.txt)
[node-5.txt](https://github.com/cockroachdb/cockroach/files/2387007/node-5.txt)
[node-8.txt](https://github.com/cockroachdb/cockroach/files/2387008/node-8.txt)

![image](https://user-images.githubusercontent.com/6306961/45600825-a538fe00-b9f2-11e8-853c-81433a3913d7.png)

My python client code threw the following exceptions (around the time the cluster **recovered**):
```
Sep 16 19:53:22 de-leader-a: InternalError: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Sep 16 19:53:22 de-leader-a: InternalError: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Sep 16 19:53:22 de-leader-a: InternalError: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Sep 16 19:53:33 gb-leader-a: InternalError: rpc error: code = Unavailable desc = transport is closing
Sep 16 19:53:39 gb-leader-a: InternalError: initial connection heartbeat failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Sep 16 19:56:53 gb-leader-a: InternalError: rpc error: code = Unavailable desc = transport is closing
Sep 16 19:56:53 gb-leader-a: InternalError: rpc error: code = Unavailable desc = transport is closing
```

Side note: node 1, 3 and 8 show logs as happening on 2018-09-15 (wrong) and the nodes 4, 5 as 2018-09-16 (correct). All of my nodes run the same UTC time regardless of physical location, so that looked weird. I confirmed by checking date on all nodes:

```
y$ ./fc execute global date --cockroaches --delay=0
[execute.sh] 94.237.82.84 (cockroach in de): 'date'
Sun Sep 16 20:59:45 UTC 2018

[execute.sh] 94.237.49.204 (cockroach in gb): 'date'
Sun Sep 16 20:59:49 UTC 2018

[execute.sh] 173.199.114.249 (cockroach in ny): 'date'
Sun Sep 16 20:59:53 UTC 2018

[execute.sh] 45.76.228.209 (cockroach in il): 'date'
Sun Sep 16 20:59:57 UTC 2018

[execute.sh] 45.32.231.197 (cockroach in wa): 'date'
Sun Sep 16 21:00:00 UTC 2018
```

Not sure why the date discrepancy in logs, not sure if related.

Thanks!

Jira issue: CRDB-4839

**Comment by tim-o** [comment] 2018-09-17 20:18
Hey @tomholub , can you send over all logs from CRDB directly? The attachments look like a translation, I'm wondering if some rows might be missing.

It's extremely odd that some logs are showing 9/15 and some 9/16. This should absolutely not be possible, since nodes will immediately shut down if they find out they're >500ms out of sync with the average clock on the cluster. If a node was a day out of sync, I'd expect it to immediately shut down.

One potential explanation is that you temporarily lost quorum as nodes shut down due to clocks being out of sync - this would make the cluster unavailable. Were nodes perhaps restarted after ~4 mins?

**Comment by tomholub** [comment] 2018-09-19 05:04
@tim-o I can send you any logs you like. What is a good way to retrieve them directly? Also, the cluster has since been upgraded to v2.0.5 and restarted - hopefully the logs are still available.

**Comment by tim-o** [comment] 2018-09-19 16:59
@tomholub - you can either run `cockroach debug zip`, or ssh onto the nodes and collect files from the log directory (<storeDirectory>/logs by default).

**Comment by tomholub** [comment] 2018-09-20 21:29
@tim-o Collected debug.zip - where can I safely send it so that it's not uploaded publicly?

Had another event just now. 3 of 5 nodes unresponsive for about 12 minutes. Now it's in a weird state - eg I can connect to all nodes and issue queries, even though most of them are listed as dead in the admin ui.

![image](https://user-images.githubusercontent.com/6306961/45847888-1c84cf80-bd1c-11e8-8224-68063dbaa1a4.png)

**Comment by tomholub** [comment] 2018-09-20 21:39
Restarting 45.32.231.197 seemed to bring it and all other nodes to life (in the admin ui), so that may be the suspect.

Overall, running the cluster, I've had the feeling that one misbehaving node has the power to bring the whole cluster to a halt, which is why when I see outages, it would often be several nodes at a time, or all of them. Hopefully the debug logs will shine some light on that! Please let me know where to send.

**Comment by tschottdorf** [comment] 2018-09-22 06:54
Thank you for sending along the logs, @tomholub. Unfortunately, it seems that they weren't collected wholesale into the `debug zip` (likely related due to the cluster troubles in the first place).

Could you grab the logs manually and upload them again? Sorry this is turning out to be such a hassle.

I'm also curious whether you got to the bottom of the `date` confusion in your initial post. Those would add lots of confusion to my attempts to line up events across different nodes, and even if the logs had the correct timestamps this strikes me as puzzling and problematic.

**Comment by tomholub** [comment] 2018-09-22 08:39
@tschottdorf np, I made a script to grab the logs directly. Submitted.

I haven't investigated the date discrepancy further. I figured it must be Admin UI quirk, since the cluster dates on the machines matched up. I'll take a look.

**Comment by tomholub** [comment] 2018-09-22 11:37
Restarted the node and latest logs show current date.

**Comment by tomholub** [comment] 2018-09-23 02:50
Log dates: this morning the logs were showing an old dates again. After restarting, it showed the current ones.

Turns out it's not that the logs have a wrong date. It's that the newest logs would show up in the Admin UI with a few hours delay, thus the date discrepancy on the latest visible logs.

**Comment by couchand** [comment] 2018-09-24 13:41
> Turns out it's not that the logs have a wrong date. It's that the newest logs would show up in the Admin UI with a few hours delay, thus the date discrepancy on the latest visible logs.

@tomholub I'm not sure I totally understand.  Can you describe a little bit more about what you're seeing?

**Comment by tschottdorf** [comment] 2018-09-24 13:56
1. Throughout the logs, lots of "handle raft ready: 0.8-1.5s" messages and a few slow commits. You're not supposed to see these; they indicate a performance problem with the IO layer.
   Sometimes these issues are exacerbated by a high range count, but (please confirm) from what you sent me it looks like you have a range count in the low hundreds, which is benign.
   These messages however are not. What disks are used? How much data is written to the cluster (and are the writes large or small?)
   Are deletions common on this cluster? I poked around in the schema and didn't see anything outrageous.
2. The cluster is running with 5x replication. Just something I'd like to point out so that I remember it.
3. There aren't any visible Gossip problems. It appears that Gossip remains connected throughout the incident.

The below are my debugging notes so far. They probably don't make all that much sense to those not working on CockroachDB, but feel free to tag along. It's unclear to me what the problem is at this point.

Looking at the logs for the first incident (180916 19:50) shows the first sign of trouble:

180916 19:50:02.987168 53719581 kv/dist_sender.go:1305  [n5] have been waiting 1m0s sending RPC to r3 (currently pending: [(n5,s5):5]) for batch: [txn: e17f6438], EndTransaction [/System/NodeLiveness/5,/Min)
180916 19:50:07.294277 129 storage/node_liveness.go:501  [n5,hb] slow heartbeat took 1.3s
180916 19:50:07.479341 53719675 storage/replica.go:1502  [n5,s5,r3/5:/System/NodeLiveness{-Max}] have been waiting 1m0s attempting to acquire lease
180916 19:50:11.927982 99 storage/replica.go:1502  [n5,s5,r3/5:/System/NodeLiveness{-Max}] have been waiting 1m0s attempting to acquire lease

This indicates a problem with the liveness range, one of the central system ranges of a cluster. Looking at the logs more, we see more messages of this type, all originating at n5.

This culminates two minutes later with the following message:

```
180916 19:52:01.121890 99 storage/store.go:1456  [n5,s5,r3/5:/System/NodeLiveness{-Max}] could not gossip node liveness: [NotLeaseHolderError] r3: replica (n5,s5):5 not lease holder; lease holder unknown
```

and then that particular stall seems to untangle (but see further below, there are other problems), with all the stuck requests returning:

```
180916 19:52:11.820081 53723058 storage/node_liveness.go:501  [n5,s5,r342/5:/System/tsd/cr.node.gossip.by…] slow heartbeat took 96.2s
180916 19:52:11.820101 53723058 storage/replica_range_lease.go:282  [n5,s5,r342/5:/System/tsd/cr.node.gossip.by…] heartbeat failed on epoch increment
```

Just before that, I see that n5 gets its epoch incremented (i.e. it loses all of its leases):

```
180916 19:49:53.371867 52480827 storage/node_liveness.go:667  [n3,s3,r552/3:/System/tsd/cr.node.sql.mem.i…] incremented n5 liveness epoch to 72
```

Additionally, searching back through the logs, I have reason to assume that n5 really held the lease for the liveness range (for at least two days):

```
180914 19:30:34.394194 39935279 storage/queue.go:778  [gc,n8,s8,r3/7:/System/NodeLiveness{-Max}] [NotLeaseHolderError] r3: replica (n8,s8):7 not lease holder; current lease is repl=(n5,s5):5 seq=3105 start=1536953414.319243572,1 exp=1536953441.290891078,0 pro=1536953432.
290897536,0
```



In addition to these n5-scoped problems, we're seeing similar messages for replicas on n1 (originating from n1 and n4):

```
180916 19:50:50.220712 51403038 kv/dist_sender.go:1305  [ts-poll,n4] have been waiting 1m0s sending RPC to r103 (currently pending: [(n1,s1):1]) for batch: Merge [/System/tsd/cr.store.queue.replicate.addreplica/4/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.store.queue.replicagc.removereplica/4/10s/2018-09-16T19:00:00Z,/Min)
```

But then again we see n5 have problems getting to the liveness range (now lead by n3):

```
180916 19:51:23.986424 53722743 kv/dist_sender.go:1305  [n5] have been waiting 1m0s sending RPC to r3 (currently pending: [(n5,s5):5]) for batch: [txn: e3787c91], EndTransaction [/System/NodeLiveness/5,/Min)
```

and similar n3 seem unable to get responses back from n5 (or rather, they get stuck on n5).

```
180916 19:51:35.632768 52483991 kv/dist_sender.go:1305  [ts-poll,n3] have been waiting 1m0s sending RPC to r193 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.exec.latency-p99.999/3/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.exec.success/3/10s/2018-09-16T19:00:00Z,/Min)
180916 19:51:35.632898 52483995 kv/dist_sender.go:1305  [ts-poll,n3] have been waiting 1m0s sending RPC to r416 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.gossip.infos.received/3/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.infos.sent/3/10s/2018-09-16T19:00:00Z,/Min)
180916 19:51:35.632953 52483992 kv/dist_sender.go:1305  [ts-poll,n3] have been waiting 1m0s sending RPC to r342 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.gossip.bytes.received/3/10s/2018-09-16T19:00:00Z,/Min)
180916 19:51:35.633003 52483994 kv/dist_sender.go:1305  [ts-poll,n3] have been waiting 1m0s sending RPC to r192 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.gossip.connections.refused/3/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.gossip.connections.outgoing/3/10s/2018-09-16T19:00:00Z,/Min)
...
```

I think it's worth restricting to one of the ranges mentioned here to get a better timeline. Let's pick r193.

Just before things go south, it gets a new lease (n5 before, n5 after)

```
180916 19:49:57.420180 92 storage/replica_proposal.go:201  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] new range lease repl=(n5,s5):5 seq=246 start=1536953863.333839119,0 epo=72 pro=1537127393.903492292,0 following repl=(n5,s5):5 seq=245 start=1536953863.333839119,0 epo
=71 pro=1537125392.194605884,0
```

Next, we see n1 have requests hang on r193 sent against itself, and this doesn't return since it gets stuck trying to acquire a lease.

```
180916 19:50:53.869324 51349517 kv/dist_sender.go:1305  [ts-poll,n1] have been waiting 1m0s sending RPC to r193 (currently pending: [(n1,s1):1]) for batch: Merge [/System/tsd/cr.node.exec.latency-p99.999/1/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.exec.success/1/10s/2018-09-16T19:00:00Z,/Min)
180916 19:50:53.869358 51349719 storage/replica.go:1502  [n1,s1,r193/1:/System/tsd/cr.node.{ex…-go…}] have been waiting 1m0s attempting to acquire lease
```

A little later a similar message indicates that n5 also can't get a lease for that range:

```
180916 19:51:35.632768 52483991 kv/dist_sender.go:1305  [ts-poll,n3] have been waiting 1m0s sending RPC to r193 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.exec.latency-p99.999/3/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.exec.success/3/10s/2018-09-16T19:00:00Z,/Min)
180916 19:51:35.659889 53723056 storage/replica.go:1502  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] have been waiting 1m0s attempting to acquire lease
```

Next activity is a successful lease acquisition on n4:

```
180916 19:51:39.299432 185 storage/replica_proposal.go:201  [n4,s4,r193/4:/System/tsd/cr.node.{ex…-go…}] new range lease repl=(n4,s4):4 seq=247 start=1537127499.196726224,0 epo=131 pro=1537127499.196729551,0 following repl=(n5,s5):5 seq=246 start=1536953863.333839119,0 epo=72 pro=1537127393.903492292,0
```

but n5 is certifiably still in trouble learning about that:

```
180916 19:51:42.300697 53675661 kv/dist_sender.go:1305  [ts-poll,n8] have been waiting 1m0s sending RPC to r193 (currently pending: [(n5,s5):5]) for batch: Merge [/System/tsd/cr.node.exec.latency-p99.999/8/10s/2018-09-16T19:00:00Z,/Min), Merge [/System/tsd/cr.node.exec.success/8/10s/2018-09-16T19:00:00Z,/Min)
180916 19:51:42.319348 53723507 storage/replica.go:1502  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] have been waiting 1m0s attempting to acquire lease
```

It's notable that now there is a whole block of messages originating from n8. Before it was n3 and n5.

The slow heartbeat comes back.

```
180916 19:52:11.820401 53723059 storage/node_liveness.go:501  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] slow heartbeat took 96.2s
180916 19:52:11.820412 53723059 storage/replica_range_lease.go:282  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] heartbeat failed on epoch increment
```

but n5 remains problematic:

```
180916 19:53:11.821986 53726999 storage/replica.go:1502  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] have been waiting 1m0s attempting to acquire lease
```

New lease on n8:

```
180916 19:53:38.416941 87 storage/replica_proposal.go:201  [n8,s8,r193/7:/System/tsd/cr.node.{ex…-go…}] new range lease repl=(n8,s8):7 seq=248 start=1537127618.286796025,0 epo=50 pro=1537127618.286798307,0 following repl=(n4,s4):4 seq=247 start=1537127499.196726224,0 epo=131 pro=1537127499.196729551,0
```

New lease on n5 (why is unclear):

```
180916 19:55:33.477424 89 storage/replica_proposal.go:201  [n5,s5,r193/5:/System/tsd/cr.node.{ex…-go…}] new range lease repl=(n5,s5):5 seq=249 start=1537127733.410868721,0 epo=73 pro=1537127733.410877935,0 following repl=(n8,s8):7 seq=248 start=1537127618.286796025,0 epo=50 pro=1537127618.286798307,0
```

**Comment by tschottdorf** [comment] 2018-09-24 15:08
Looking at the logs, I see that during the above period of time, n5 appears to have been unable to dial n1 and n4 (and vice versa), so we're looking at some sort of network partition here. This cluster is geopartitioned and n1 and n4 are one one continent whereas the other nodes (including n5) are on another. This definitely plays a role, though the expected behavior here would be that nodes n1, n5, and n8 can keep things running (as the majority partition); however your clients pointed at servers in the minority continent would not be able to make progress (so you'd definitely be getting paged at that point). I wasn't able to see connection issues between those nodes in the logs.

However, if the connection degradation between the continents was sufficiently subtle, things could look much worse. For example, a critical amount of packet loss or flapping connections could delay the detection of the disconnect for quite a while while effectively stalling forward progress.o

@tomholub I'd be interested in hearing what your provider's monitoring has to say about the network connectivity during this first episode.

I'm going to look at your second outage next.

**Comment by tschottdorf** [comment] 2018-09-24 15:45
Hmm, looking back into Gossip issues, I'm noticing that during the second outage (not sure about the first yet) n5 is connected to n3 and n1 only.

n1 at around the same time tells us it's connected to n5 only. Similarly n3 is only connected to n5.

So there *is* a Gossip partition; (n5,n3,n1) have no connection to either n8 or n4.

@a-robinson since this is v2.0.4, it doesn't have #25322 - is that just what this is? Is there a suggested workaround until we release v2.0.6 with #25322 in it?

**Comment by tomholub** [comment] 2018-09-24 16:38
Thanks for the detailed notes @tschottdorf 

> (please confirm) from what you sent me it looks like you have a range count in the low hundreds, which is benign

Correct, range count around 300 for a while now. Total DB size 116 mb, growing slowly / gradually.

> What disks are used?

All disks are SSD based. Both providers (Vultr and UpCloud) seem to be running their own SSD based block storage that they attach to each instance. Although we chose servers with equivalent specs, performance may somewhat vary across providers. UpCloud nodes seem somewhat snappier subjectively (n1, n4).

> How much data is written to the cluster (and are the writes large or small?)

All writes are very small, operational - users, tokens, other metadata. No bulk writes. Inserts or updates in the low thousands of ops per day, spread throughout the day.

The largest write in terms of byte size are stack traces - up to 5kb per write, not that many of them.

> Are deletions common on this cluster? I poked around in the schema and didn't see anything outrageous.

Almost none, except when I run a clean up script, which I have not done the day we were having these issues.

> @tomholub I'd be interested in hearing what your provider's monitoring has to say about the network connectivity during this first episode.

I'll check what they have to say about connectivity during the first outage at Sep 16 19:50 UTC

> For the second outage, I estimate that it started at 180920 20:42:29.808085 based on the logs (please confirm @tomholub!) and ended at around 20:57.

Correct. My app logged db downtime on 2018-09-20 from 20:46 until 20:58.

------------------ 

Overall, in terms of desired outcome:
 - during the first outage, a network split would ideally only take the minority nodes down, while majority can continue making progress (actual outcome - all nodes unresponsive)
 - during the second outage with two nodes down, they should eventually recover on their own (actual outcome - they only recovered after I restarted n5. This may have been a coincidence. Maybe the two nodes were going to recover regardless around that time? It did seem like the restart was what made them recover)

Thanks again for looking into this.

**Comment by tschottdorf** [comment] 2018-09-24 16:53
Thanks @tomholub. To sum up my somewhat unfocused writeups above, I now suspect that both outages are ultimately caused by #25322, but there are definitely network issues during the first that might've toppled the cluster, too.

Independently, looking at the logs I see indications throughout (i.e. not restricted to the failures) that there is a base slowness that worries me. Looking again at the logs, it seems that at any point in time the slowness occurs only on some nodes. Pretty sure that this is actually due to your aggressive geo replication.

@tomholub are you using partitioning? I'm asking because evenly spreading out five replicas across the globe without using any data locality in general works very poorly.

@petermattis for context: this cluster has five nodes and geo-replicates from the West Coast into Europe, with no two replicas colocated and a replication factor of five.

**Comment by a-robinson** [comment] 2018-09-24 17:00
> @a-robinson since this is v2.0.4, it doesn't have #25322 - is that just what this is? Is there a suggested workaround until we release v2.0.6 with #25322 in it?

Unfortunately the workaround is just to restart one or more of the nodes in the minority. If you know which one of them has a replica of r1, restarting that one should be enough. If you don't, restarting all the nodes in the minority will do it. If you haven't even done the work to figure out which are in the minority, restarting all nodes in the cluster will do the trick.

It's mind-blowing how this has come up so frequently over the last month when it didn't happen at all the first few months v2.0 was out. v2.0.6 can't come soon enough.

**Comment by tomholub** [comment] 2018-09-24 17:47
> @tomholub are you using partitioning? I'm asking because evenly spreading out five replicas across the globe without using any data locality in general works very poorly.

No partitioning. I initially spread them far and wide with replication factor == node count, expecting writes would be slow and reads would be local (each node has all data).

Noticing that reads are not always local (go through lease holder?), I was considering to bring the nodes a little closer together, keeping them strictly between the East Coast and West Europe (instead of stretching all the way to the West Coast).

**Comment by tschottdorf** [comment] 2018-09-24 21:54
Ack, thanks @a-robinson. In this case every node has a replica of n1. Why is that guaranteed to break the partition again (it's likely that it'll break it, but it's not guaranteed, right?)

@tomholub please keep that workaround in mind, but also note that v2.0.6 is hopefully going to be out in a little bit over a week. You may want to subscribe to https://github.com/cockroachdb/cockroach/issues/30573.

**Comment by a-robinson** [comment] 2018-09-24 22:08
It's really just a probabilistic fix. Upon restart, it's quite likely that one or more of the following will happen:

1. The restarted nodes will choose gossip peers that result in there being no partition in the gossip network
2. The timing of the restarted nodes' `maybeGossipFirstRange` loops will be aligned better such that r1's lease doesn't ping pong
3. Restarting the nodes will cause more requests to r1, preventing its lease from expiring and (thus from ping ponging) for a couple minutes, long enough for the gossip partition to be noticed and fixed.

**Comment by tschottdorf** [comment] 2018-10-11 09:15
@couchand could you close this out once you've followed up on the [comment above](https://github.com/cockroachdb/cockroach/issues/30269#issuecomment-424075397)? Not sure this is easy to explain. But I think I might be seeing something like this?

https://cockroach-adriatic-0001.crdb.io:8080/#/node/1/logs shows me the newest timestamp (at the bottom) of 2018-10-10 21:45:25 (UTC I think). My local time is 2018-10-11 11:13:xx (UTC+2). No amount of longitude can explain that.

I ssh'ed in and checked the logs, and unsurprisingly the actual timestamps are at around I181011 09:14:55.194574. I think this is probably something really silly: the log file is read from the beginning of the file. As it grows beyond some internal limit, the UI (or some API call) truncates it.

The node is live. I wonder what folks in NYC see.

**Comment by lunevalex** [comment] 2021-06-15 14:12
@thtruo @nkodali this recently came up as a result of a postmortem for internal issue https://github.com/cockroachlabs/support/issues/973, pinging so it pops back up on your radar.

**Closed** 2023-04-11 17:48 UTC
Labels: C-investigation, T-observability-inf
