### ISSUE TITLE
sql: v23.1.11: panic in execCopyIn

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#112095] opened 2023-10-10 14:23 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4538404754/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4538404754/?referrer=webhooks_plugin)

Panic Message:

```
conn_executor.go:900: panic: ×
(1) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | [...repeated from below...]
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:884
  | sync.(*WaitGroup).Add
  | 	GOROOT/src/sync/waitgroup.go:83
  | sync.(*WaitGroup).Done
  | 	GOROOT/src/sync/waitgroup.go:108
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCopyIn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:3178
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2364
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2105
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:902
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (3) panic: ×
Error types: (1) *withstack.withStack (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: panic: ×
conn_executor.go:900: *withstack.withStack (top exception)
conn_executor.go:900: *withstack.withStack (1)
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2104-L2106)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2363-L2365](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L2363-L2365)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L3177-L3179](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L3177-L3179)
[GOROOT/src/sync/waitgroup.go#L107-L109](GOROOT/src/sync/waitgroup.go#L107-L109)
[GOROOT/src/sync/waitgroup.go#L82-L84](GOROOT/src/sync/waitgroup.go#L82-L84)
[GOROOT/src/runtime/panic.go#L883-L885](GOROOT/src/runtime/panic.go#L883-L885)
[https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/62ad175cbc0e9041d993ea1cc911e07d279671f5/pkg/sql/conn_executor.go#L899-L901)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 902
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2105
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2364
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCopyIn at line 3178
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Done at line 108
GOROOT/src/sync/waitgroup.go in sync.(*WaitGroup).Add at line 83
GOROOT/src/runtime/panic.go in runtime.gopanic at line 884
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn.func1 at line 900
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v23.1.11 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11 |
| Cockroach SHA | 62ad175cbc0e9041d993ea1cc911e07d279671f5 |
| # of CPUs | 12 |
| # of Goroutines | 5797 |

Jira issue: CRDB-32233
Epic CRDB-34178

**Comment by yuzefovich** [comment] 2023-11-20 22:15
This is `panic("sync: negative WaitGroup counter")`.

**Comment by yuzefovich** [comment] 2023-11-20 22:48
We've observed this problem a few times in CC fleet.

**Comment by yuzefovich** [comment] 2023-11-20 23:22
Hm, I don't know how we made the WaitGroup become negative for the CopyIn. We call `Add(1)` once, before handing over the control over the connection to the copyMachine. We defer calling `Done()` (which internally calls `Add(-1)`) until after the copyMachine is done. The copyMachine only handles `ClientMsgCopyData`, `ClientMsgCopyDone`, `ClientMsgFlush`, and `ClientMsgSync` messages, and it returns errors for all others.

Negative count suggests that the deferred function was executed at least twice which means that `connExecutor.execCopyIn` was called at least twice with the same `CopyIn` struct while being in an open txn, but this doesn't seem possible.

Not sure what to do here. Curious whether @rafiss or @michae2 have thoughts / suggestions. It does look like some of our CC customers are running into this.

**Comment by yuzefovich** [comment] 2023-11-27 23:58
Closing as unactionable

**Comment by yuzefovich** [comment] 2023-11-28 21:30
Re-opening since we've seen it in another customer.

My current hypothesis is that 888001367dee4da574386488590b9234ff0481c5 is to blame (since we've only seen this problem on 23.1). In the linked support ticket we see the following (on 23.1.10):
```
E231128 16:27:01.061393 783943069 9@sql/conn_executor.go:2957 ⋮ [...] 2 error executing ‹CopyIn: COPY ... FROM STDIN WITH (FORMAT BINARY)›: query execution canceled due to statement timeout
E231128 16:27:01.061753 783943069 1@util/log/logcrash/crash_reporting.go:188 ⋮ [...] 102694 a panic has occurred!
```
It seems like somehow the `statement_timeout` cancellation triggers a transparent retry in COPY which then hits negative wait group counter.

I tried some simple reproduction steps (running COPY similar to what we do in `copyfrom` roachtest (for `lineitem` TPCH table) while setting `statement_timeout` to different values and also occasionally tweaking `copy_from_atomic_enabled`), but this didn't trigger the panic in a few runs.

@rafiss I wonder whether you have some ideas on how that linked commit could be faulty, or any other hypothesis.

**Closed** 2023-12-07 19:01 UTC
Labels: C-bug, O-support, O-sentry, T-sql-queries, v23.1.14, v23.2.1
