### ISSUE TITLE
testing: Go Runtime panic in stress test

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#9043] opened 2016-09-01 20:25 UTC
Running stress tests on a GCE Worker, encountered a Go Runtime panic that appears to reproduce readily.

Command invoked: `make stress PKG=./storage TESTS=TestUnreplicateFirstRange`

Test output:

```
11218 runs so far, 0 failures, over 3m30s

I160901 19:54:15.861856 1 rand.go:76  Random seed: -1257422102075973227
I160901 19:54:15.863817 50 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 19:54:15.867804 50 gossip/gossip.go:230  initial resolvers: []
W160901 19:54:15.867826 50 gossip/gossip.go:1041  no resolvers found; use --join to specify a connected node
I160901 19:54:15.867858 50 gossip/gossip.go:264  NodeID set to 1
I160901 19:54:15.868999 50 gossip/gossip.go:264  NodeID set to 1
I160901 19:54:15.869404 50 storage/store.go:975  store=1:1: failed initial metrics computation: store=1:1: system config not yet available
I160901 19:54:15.869511 50 gossip/gossip.go:278  NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:57314" > attrs:<>
I160901 19:54:15.870705 79 storage/replica_trigger.go:308  [s1,r1{/Min-/Max}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160901 19:54:15.871041 50 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 19:54:15.871711 50 gossip/gossip.go:230  initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:57314})]
W160901 19:54:15.871734 50 gossip/gossip.go:1043  no incoming or outgoing connections
I160901 19:54:15.871762 50 gossip/gossip.go:264  NodeID set to 2
I160901 19:54:15.873439 50 gossip/gossip.go:264  NodeID set to 2
I160901 19:54:15.873507 50 storage/store.go:975  store=2:2: failed initial metrics computation: store=2:2: system config not yet available
I160901 19:54:15.873539 50 gossip/gossip.go:278  NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:50033" > attrs:<>
I160901 19:54:15.873724 50 storage/engine/rocksdb.go:354  opening in memory rocksdb instance
I160901 19:54:15.873817 228 gossip/client.go:125  node 2: started gossip client to 127.0.0.1:57314
I160901 19:54:15.874483 50 gossip/gossip.go:230  initial resolvers: [%!s(*resolver.socketResolver=&{tcp 127.0.0.1:57314})]
W160901 19:54:15.874499 50 gossip/gossip.go:1043  no incoming or outgoing connections
I160901 19:54:15.874528 50 gossip/gossip.go:264  NodeID set to 3
I160901 19:54:15.875390 50 gossip/gossip.go:264  NodeID set to 3
I160901 19:54:15.875530 50 storage/store.go:975  store=3:3: failed initial metrics computation: store=3:3: system config not yet available
I160901 19:54:15.875573 326 gossip/client.go:125  node 3: started gossip client to 127.0.0.1:57314
I160901 19:54:15.875586 50 gossip/gossip.go:278  NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:44570" > attrs:<>
runtime: gp: gp=0xc4202d8340, goid=50, gp->atomicstatus=4097
runtime:  g:  g=0x2460b20, goid=0,  g->atomicstatus=0
fatal error: stopg: invalid status

runtime stack:
runtime.throw(0x175578d, 0x15)
        /home/matt/go/src/runtime/panic.go:566 +0x95 fp=0x7ffcd47e4c90 sp=0x7ffcd47e4c70
runtime.scang(0xc4202d8340, 0xc420025c28)
        /home/matt/go/src/runtime/proc.go:811 +0x229 fp=0x7ffcd47e4cc8 sp=0x7ffcd47e4c90
runtime.markroot.func1()
        /home/matt/go/src/runtime/mgcmark.go:236 +0x6d fp=0x7ffcd47e4d08 sp=0x7ffcd47e4cc8
runtime.systemstack(0x7ffcd47e4d60)
        /home/matt/go/src/runtime/asm_amd64.s:314 +0xab fp=0x7ffcd47e4d10 sp=0x7ffcd47e4d08
runtime.markroot(0xc420025c28, 0x35)
        /home/matt/go/src/runtime/mgcmark.go:241 +0x2ba fp=0x7ffcd47e4d88 sp=0x7ffcd47e4d10
runtime.gcDrain(0xc420025c28, 0x0)
        /home/matt/go/src/runtime/mgcmark.go:963 +0xab fp=0x7ffcd47e4dc0 sp=0x7ffcd47e4d88
runtime.gchelper()
        /home/matt/go/src/runtime/mgc.go:1819 +0x89 fp=0x7ffcd47e4e00 sp=0x7ffcd47e4dc0
runtime.stopm()
        /home/matt/go/src/runtime/proc.go:1597 +0xdf fp=0x7ffcd47e4e28 sp=0x7ffcd47e4e00
runtime.findrunnable(0xc42002b500, 0x0)
        /home/matt/go/src/runtime/proc.go:2021 +0x228 fp=0x7ffcd47e4ed8 sp=0x7ffcd47e4e28
runtime.schedule()
        /home/matt/go/src/runtime/proc.go:2120 +0x14c fp=0x7ffcd47e4f18 sp=0x7ffcd47e4ed8
runtime.goschedImpl(0xc4202d8340)
        /home/matt/go/src/runtime/proc.go:2198 +0x100 fp=0x7ffcd47e4f38 sp=0x7ffcd47e4f18
runtime.gopreempt_m(0xc4202d8340)
        /home/matt/go/src/runtime/proc.go:2213 +0x36 fp=0x7ffcd47e4f50 sp=0x7ffcd47e4f38
runtime.newstack()
        /home/matt/go/src/runtime/stack.go:1053 +0x318 fp=0x7ffcd47e50d0 sp=0x7ffcd47e4f50
runtime.morestack()
        /home/matt/go/src/runtime/asm_amd64.s:366 +0x7f fp=0x7ffcd47e50d8 sp=0x7ffcd47e50d0

goroutine 1 [chan receive]:
runtime.gopark(0x18cdd98, 0xc42029c538, 0x174bf2c, 0xc, 0xc42028d917, 0x3)
        /home/matt/go/src/runtime/proc.go:259 +0x13a fp=0xc42067b8e8 sp=0xc42067b8b8
runtime.goparkunlock(0xc42029c538, 0x174bf2c, 0xc, 0xc420000317, 0x3)
        /home/matt/go/src/runtime/proc.go:265 +0x5e fp=0xc42067b928 sp=0xc42067b8e8
runtime.chanrecv(0x1594680, 0xc42029c4e0, 0x0, 0xc42028d901, 0x647dbc)
        /home/matt/go/src/runtime/chan.go:496 +0x2df fp=0xc42067b9b0 sp=0xc42067b928
runtime.chanrecv1(0x1594680, 0xc42029c4e0, 0x0)
        /home/matt/go/src/runtime/chan.go:378 +0x35 fp=0xc42067b9e8 sp=0xc42067b9b0
testing.(*T).Run(0xc4202dc240, 0x17592ee, 0x19, 0x18cc3f8, 0xc42028da01)
        /home/matt/go/src/testing/testing.go:647 +0x316 fp=0xc42067ba90 sp=0xc42067b9e8
testing.RunTests.func1(0xc4202dc240)
        /home/matt/go/src/testing/testing.go:793 +0x6d fp=0xc42067bae0 sp=0xc42067ba90
testing.tRunner(0xc4202dc240, 0xc42067bbc0)
        /home/matt/go/src/testing/testing.go:610 +0x81 fp=0xc42067bb08 sp=0xc42067bae0
testing.RunTests(0x18cd588, 0x2102980, 0x13c, 0x13c, 0xc420192bb0)
        /home/matt/go/src/testing/testing.go:799 +0x2f5 fp=0xc42067bbf0 sp=0xc42067bb08
testing.(*M).Run(0xc42067bee8, 0xc42028dd30)
        /home/matt/go/src/testing/testing.go:743 +0x85 fp=0xc42067bc78 sp=0xc42067bbf0
github.com/cockroachdb/cockroach/storage_test.TestMain(0xc42067bee8)
        /home/matt/src/github.com/cockroachdb/cockroach/storage/main_test.go:57 +0x1ff fp=0xc42067bee0 sp=0xc42067bc78
main.main()
        github.com/cockroachdb/cockroach/storage/_test/_testmain.go:694 +0xc6 fp=0xc42067bf48 sp=0xc42067bee0
runtime.main()
        /home/matt/go/src/runtime/proc.go:183 +0x1f4 fp=0xc42067bfa0 sp=0xc42067bf48
runtime.goexit()
        /home/matt/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42067bfa8 sp=0xc42067bfa0

#... goroutine dump snipped, Toby has the full dump 

ERROR: exit status 2

11234 runs completed, 1 failures, over 3m30s
FAIL
M
```

The GCE Worker bootstrapping may not have completed correct. However, I do not know if this is true or, if true, where the bootstrapping process halted.

**Comment by tamird** [comment] 2016-09-05 18:07
Was this on master or develop? What SHA specifically?

**Comment by tschottdorf** [comment] 2016-09-07 14:07
Just as a datapoint: on current master (75173901a2c72bdb184cb6a57b4152b0cbfac4da).

> 20054 runs so far, 0 failures, over 5m55s

I'm not investigating this further, so unassigning.

**Comment by tamird** [comment] 2016-12-02 12:22
Closing as unable to reproduce.

**Closed by tamird** 2016-12-02 12:22 UTC
