### ISSUE TITLE
sentry: conn_executor.go:643: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON ((_._ = _._) AND (_._ = _._)) AND (_._ = _._) WHERE (((_._ = _) AND (_._ = _)) AND ((_._ < now()) OR (_._ = now()))) AND (_._ > now()) ORDER BY _._ ASC: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33185] opened 2018-12-17 01:09 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/811074139/?referrer=webhooks_plugin

conn_executor.go:643: panic while executing 1 statements: SELECT _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _, _._ AS _ FROM _ AS _ INNER JOIN _ AS _ ON ((_._ = _._) AND (_._ = _._)) AND (_._ = _._) WHERE (((_._ = _) AND (_._ = _)) AND ((_._ < now()) OR (_._ = now()))) AND (_._ > now()) ORDER BY _._ ASC: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in convertOrdering at line 935
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForLookupJoin at line 1918
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2273
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2279
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 752
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1173
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 313
```

**Comment by jordanlewis** [comment] 2018-12-18 14:44
Dupe of #33179

**Closed by jordanlewis** 2018-12-18 14:44 UTC
Labels: C-bug, O-sentry
