### ISSUE TITLE
sql: panic in the host() built-in in combination with computed column

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25627] opened 2018-05-17 19:29 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/558607360/

```
*log.safeError: conn_executor.go:521: panic while executing 1 statements: INSERT INTO _(_, _, _, _) VALUES (_, _, _, _): caused by <redacted>
  File "github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go", line 489, in func2
  File "github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go", line 1281, in MustBeDIPAddr
  File "github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/builtins.go", line 310, in func23
  File "github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go", line 3312, in Eval
  File "github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go", line 3302, in Eval
...
(15 additional frame(s) were not displayed)

conn_executor.go:521: panic while executing 1 statements: INSERT INTO _(_, _, _, _) VALUES (_, _, _, _): caused by <redacted>
```

**Comment by knz** [comment] 2018-05-17 19:34
The panic is at this line of code:

```go
  "host": {
    tree.Builtin{
      Types:      tree.ArgTypes{{"val", types.INet}},
      ReturnType: tree.FixedReturnType(types.String),
      Fn: func(_ *tree.EvalContext, args tree.Datums) (tree.Datum, error) {
        dIPAddr := tree.MustBeDIPAddr(args[0])   // <---- HERE
        s := dIPAddr.IPAddr.String()
        if i := strings.IndexByte(s, '/'); i != -1 {
          return tree.NewDString(s[:i]), nil
        }
        return tree.NewDString(s), nil
      },
      Info: "Extracts the address part of the combined address/prefixlen value as text." +
        "\n\nFor example, `host('192.168.1.2/16')` returns `'192.168.1.2'`",
    },
  },

```

**Comment by knz** [comment] 2018-05-17 19:37
Not a problem with NULL, because `(*FuncExpr).Eval()` pre-checks NULLs already

**Comment by knz** [comment] 2018-05-17 19:40
The scrubbed query only contains a VALUES clause, but the deeper stack trace on Sentry reveals that the error occurs during the evaluation of a computed expression.

**Comment by knz** [comment] 2018-05-17 19:42
Judging by the Eval call tree, the computed expression has the following structure:

`(someunknownfunction(host(x)))::SOMETYPE` 

where `x` is an invalid value that was type checked as INET.

**Comment by knz** [comment] 2018-05-17 19:48
@justinj if you could have a preliminary look that would be swell.

**Comment by knz** [comment] 2018-05-17 19:49
Sentry issue: [COCKROACHDB-GD](https://sentry.io/cockroach-labs/cockroachdb/issues/558607360/)

**Comment by jordanlewis** [comment] 2018-05-18 22:36
This is a duplicate of #25670. Both of these issues are also probably sub-issues of a bigger problem, but for now I'll close this one.

**Closed by jordanlewis** 2018-05-18 22:36 UTC
Labels: A-sql-datatypes, A-sql-execution, C-bug, S-2-temp-unavailability
