### ISSUE TITLE
sql: check constraints referencing sequences are not rewritten to use IDs

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#76137] opened 2022-02-07 04:38 UTC
**Describe the problem**
Many expressions in a descriptor cannot reference sequences. Default expressions surely can. Views also can. In those cases we rewrite the expression to reference the sequence by ID instead of by name. This makes the sequence robust to renames. Unfortunately, check constraints can also reference sequences. We need to detect that and rewrite those constraints accordingly. We also need to track the sequence dependency and back reference. 

**To Reproduce**

Consider:
```sql
create table foo (i INT PRIMARY KEY, CHECK (i > nextval('s')));
```

Jira issue: CRDB-12993

Epic CRDB-19164

**Comment by postamar** [comment] 2022-11-10 21:38
duplicate of https://github.com/cockroachdb/cockroach/issues/87519

**Closed by postamar** 2022-11-10 21:38 UTC
Labels: C-bug, A-schema-descriptors, T-sql-schema
