### ISSUE TITLE
sql: issue creating index using operators

### ISSUE THREAD

**Issue by giangpham712** [cockroachdb/cockroach#110247] opened 2023-09-08 13:08 UTC
**Describe the problem**

Given a table created using the following SQL

```
CREATE TABLE "People" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text,
    "LastName" text,
    CONSTRAINT "PK_People" PRIMARY KEY ("Id")
);
```

Trying to create an index using this SQL

```
CREATE INDEX "IX_People_FirstName_LastName" ON "People" ("FirstName" text_pattern_ops);
```

returns error `ERROR: operator classes are only allowed for the last column of an inverted index`

**Additional context**

This affects efcore.pg tests

@fqazi 

Jira issue: CRDB-31343

**Comment by fqazi** [comment] 2023-09-08 15:57
@giangpham712 Let's skip tests that need this for now, since this isn't going to be sorted in the short term

**Comment by mgartner** [comment] 2023-09-19 20:52
Closing as a duplicate of #57285.

**Closed by mgartner** 2023-09-19 20:52 UTC
Labels: C-bug, O-community, T-sql-foundations, T-sql-queries, A-tools-efcore
