### ISSUE TITLE
sql: CREATE TABLE AS errors out with enums

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#50164] opened 2020-06-12 22:29 UTC
Consider this testcase:

https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/logictest/testdata/logic_test/enums#L852
```
# Test CTAS from a VALUES clause.
statement ok
CREATE TABLE enum_ctas AS VALUES ('howdy'::greeting, 'cockroach'::dbs)
```

If I rewrite it like this:
```
CREATE TABLE enum_ctas AS VALUES (('how' || 'dy')::greeting, 'cockroach'::dbs)
```
I get an error:
```
pq: type "greeting" does not exist`
```

The difference between these statements is that in the existing case, the literal cast is "folded" very early, during type-checking. There are problems with this folding (eg #48717) and I'm working on fixing it. The fix involves leaving in the cast, so with my change the existing test will start failing too.

**Comment by rohany** [comment] 2020-06-13 00:24
Hmm, preliminary investigation is showing that the expression `('how' || 'dy')::greeting` in the values clause isn't a `TypedExpr` (or at least doesn't have its type reference of `greeting` resolved, so it's not able to format itself appropriately (with its ID) for the query to run in the schema changer.

**Comment by rohany** [comment] 2020-06-13 00:48
I think this is stemming from the fact that CTAS serializes the input AST in the AS component, rather than serializing optimizer created representation of the query. This happens to work out in the case of table names, because I think the optimizer mutates the `TableName`s in the input AST while performing name resolution so that all of the table names in the query are fully qualified (see `builder.qualifyDataSourceNamesInAST`). It seems that in the constant case we were lucky enough to not run into this issue, but that's no longer the case once the `BinaryExpr` is present.

I think the solution here to to generate the view query from within the optimizer. There's a TODO here assigned to @RaduBerinde to look into that, maybe you can help me here :D

**Comment by rohany** [comment] 2020-06-13 01:07
A quick and dirty solution would be to install another “type name formatter” that resolves the unresolved type names in the view query so that they are fully qualified. This is similar to the approach for table names, but I’d prefer to leave this as a second option.

**Comment by rohany** [comment] 2020-06-13 03:18
Alright, I was able to confirm that this is the cause. We need to be serializing an AST of typed expressions, not the raw untyped AST. Without the typing information, we can't generate a serialized query where type references are replaced ID references.

**Closed** 2020-06-18 17:50 UTC
Labels: A-sql-execution, C-bug
