### ISSUE TITLE
TestRaftRemoveRace: panic: [group 1] applied(29) is out of range [prevApplied(0), committed(0)]

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3297] opened 2015-12-02 22:40 UTC
The following test appears to have failed:

[#9803](https://circleci.com/gh/cockroachdb/cockroach/9803):

```
original:&{groupID:1 replicaID:7 committedTerm:6 leader:{NodeID:1 StoreID:1 ReplicaID:1} pending:map[] writing:false nodeIDs:[1 2]}
fetched:&{groupID:1 replicaID:8 committedTerm:0 leader:{NodeID:1 StoreID:1 ReplicaID:1} pending:map[] writing:false nodeIDs:[]}
, aborting configuration change
I1202 22:39:56.689552 1079 multiraft/multiraft.go:832  node 3: got message for group 1 with newer replica ID (9 vs 8), recreating group
E1202 22:39:56.689859 1079 raft/log.go:195  [group 1] applied(29) is out of range [prevApplied(0), committed(0)]
panic: [group 1] applied(29) is out of range [prevApplied(0), committed(0)]

goroutine 6519 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc8204d0d70, 0x15a9b60, 0x3c, 0xc820233170, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1a2
github.com/coreos/etcd/raft.(*raftLog).appliedTo(0xc8200cc0e0, 0x1d)
	/go/src/github.com/coreos/etcd/raft/log.go:195 +0x1f7
github.com/coreos/etcd/raft.newRaft(0xc8200cc070, 0xc8203a10e0)
	/go/src/github.com/coreos/etcd/raft/raft.go:208 +0x924
github.com/coreos/etcd/raft.(*multiNode).run(0xc8203a0cc0)
	/go/src/github.com/coreos/etcd/raft/multinode.go:203 +0x423
--
	/go/src/github.com/cockroachdb/cockroach/rpc/codec/client.go:80 +0x4b
net/rpc.(*Client).input(0xc8204532c0)
	/usr/local/go/src/net/rpc/client.go:109 +0xbf
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0xd2
FAIL	github.com/cockroachdb/cockroach/storage	13.597s
=== RUN   TestBatchBasics
I1202 22:39:34.899838 1055 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1202 22:39:34.900937 1055 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I1202 22:39:34.904285 1055 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2015-12-03 13:51
dupe #3306

**Comment by bdarnell** [comment] 2015-12-03 22:42
I don't think this is a dupe of #3306: #3306 was in TestStoreRangeMergeTwoEmptyRanges but this one is TestRaftRemoveRace. This is one of the issues @BramGruneir noted in #3176.

**Comment by BramGruneir** [comment] 2016-01-14 22:25
No longer failing.

**Closed by BramGruneir** 2016-01-14 22:25 UTC
Labels: test-failure
