### ISSUE TITLE
circleci: failed tests: TestIntentResolution

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6446] opened 2016-05-02 14:25 UTC
The following test appears to have failed:

[#17137](https://circleci.com/gh/cockroachdb/cockroach/17137):

```
I160502 14:22:47.968032 server/intent_test.go:103  got "s"-"x"
I160502 14:22:47.969487 stopper.go:352  draining; tasks left:
1      server/node.go:782
W160502 14:22:47.969985 kv/dist_sender.go:732  failed to invoke Get [/Table/3/1/12/2/1,/Min): key range /Table/3/1/12/2/1-/Min outside of bounds of range /Min-"s"
W160502 14:22:47.970119 kv/dist_sender.go:791  key range /Table/3/1/12/2/1-/Min outside of bounds of range /Min-"s"
F160502 14:22:47.970318 kv/txn_coord_sender.go:832  retryable internal error must not happen at this level: key range /Table/3/1/12/2/1-/Min outside of bounds of range /Min-"s"
goroutine 2015 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xeceb95900, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x2491fc0, 0x3, 0x1edfd2b, 0x16, 0x340, 0xc8203d4980, 0x7c)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:726 +0x178
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x3, 0x2, 0x18fc7c0, 0x3a, 0xc820a9d8e8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x7fd300000003, 0x18fc7c0, 0x3a, 0xc820a9d8e8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x18fc7c0, 0x3a, 0xc820a9d8e8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:179 +0x66
--
	/go/src/github.com/cockroachdb/cockroach/server/node.go:694 +0x19b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8204a8a80, 0xc820a12400)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
FAIL	github.com/cockroachdb/cockroach/server	5.277s
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.06s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	0.102s
I160502 14:23:12.188384 rand.go:76  Random seed: 7022728407008660274
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.01s)
=== RUN   TestSplitAndExpr
--- PASS: TestSplitAndExpr (0.01s)
=== RUN   TestSimplifyExpr

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2016-05-02 16:27
See #6436

**Comment by bdarnell** [comment] 2016-05-02 22:14
This is not quite the same as #6436. This test uses `TestServer` so it waits for the initial splits to occur. The problem here appears to be that `Node.recordJoinEvent` is using a worker instead of a task, so it continues to run as things are getting shut down. (It's also an abuse of `retry.Start` since it doesn't specify any backoff time)

I think this and #6436 have the same root cause, though: whenever a `Closer` channel is used in `retry.Options`, the retry loop must be prepared for the possibility that it exits early, with whatever state was passed out of the loop. `DistSender` does this for nil errors, but it will pass any non-nil error through as-is. `TxnCoordSender` expects `DistSender` to resolve all retryable errors so it panics when it sees a `RangeKeyMismatchError`. 

We could either use the `finished` variable to make sure that we only allow expected errors to pass up the stack, or in light of my recent analysis of retry logic in #2500 we could just remove the retryable panic from `TxnCoordSender` (which would fix this issue and some but not all of the errors seen in #6436)

**Comment by tschottdorf** [comment] 2016-05-04 07:30
Removing the panic sounds ok when removing the Retryable interface, but we should still convert the error to `NodeUnavailableError` for cleanliness (at which point the panic shouldn't fire any more anyway).

**Comment by bdarnell** [comment] 2016-05-04 10:51
`NodeUnavailableError` is not currently marked as `Retryable`, although it should be. I'll include it in my work on #2500.

**Closed** 2016-05-14 20:06 UTC
Labels: Robot, test-failure
