### ISSUE TITLE
Issue with 'uuid' type column while using dot net client

### ISSUE THREAD

**Issue by RoachietheSupportRoach** [cockroachdb/cockroach#46030] opened 2020-03-12 15:07 UTC
**Ticket ID:** [#4899](https://cockroachdb.zendesk.com/agent/tickets/4899)
**Priority:** normal
**Issue escalated by:** Tim O'Brien

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi,
<br>We are using NPoco (Version 4.0.2) for querying data from cockroach database.
<br>On of the tables has 'Uid' as a column which is of type "uuid". We see that randomly we get following error while querying for the data from that table
<br>Exception:System.NotSupportedException: The field 'Uid' has a type currently unknown to Npgsql (OID 2950).</p>

<p dir="auto">**To Reproduce** </p>

<p dir="auto">If possible, provide steps to reproduce the behavior: 
<br>Please note that issue does not happen always. 
<br>1. Set up CockroachDB cluster ... 
<br>2. Set up a table with guid column in it.
<br>3. Set up a dot net client with NPoco (4.0.6) and Npgsql(4.1.3) to connect to database.
<br>4. Try to query for the data.</p>

<p dir="auto">**Additional data / screenshots** 
<br>IException:System.NotSupportedException: The field 'Uid' has a type currently unknown to Npgsql (OID 2950). You can retrieve it as a string by marking it as unknown, please see the FAQ.
<br>3/11/2020 5:39:35 PM    at Npgsql.NpgsqlDataReader.GetValue(Int32 ordinal)
<br>3/11/2020 5:39:35 PM    at Npgsql.NpgsqlDataReader.GetValues(Object[] values)
<br>3/11/2020 5:39:35 PM    at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
<br>3/11/2020 5:39:35 PM    at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
<br>3/11/2020 5:39:35 PM    at NPoco.Database.Read[T](Type type, Object instance, DbDataReader r, DbCommand cmd)+MoveNext()
<br>3/11/2020 5:39:35 PM    at NPoco.Database.QueryImp[T](T instance, Expression`1 listExpression, Func`2 idFunc, Sql Sql)+MoveNext()
<br>3/11/2020 5:39:35 PM    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
<br>3/11/2020 5:39:35 PM    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
<br>3/11/2020 5:39:35 PM    at NPoco.Database.Fetch[T](Sql sql)
<br>3/11/2020 5:39:35 PM    at NPoco.Database.Fetch[T](String sql, Object[] args)
<br>3/11/2020 5:39:35 PM    at NPoco.Database.Fetch[T]()</p>

<p dir="auto">**Environment:** 
<br>- CockroachDB version [19.1.2] 
<br>- Server OS: [Linux] 
<br>- Client app [NPoco]</p></div></blockquote>

**Comment by roji** [comment] 2020-03-14 20:27
This got filed on the Npgsql repo by @bhavyabhatj (https://github.com/npgsql/npgsql/issues/2894).

For a bit of context... when Npgsql physically connects to a database for the very first time, it issues a query to download all type information. The above error would seem to suggest that at some point pg_type did not contain a row for the `uuid` type, with OID 2950 (which is indeed the standard PostgreSQL value).

As a workaround, you can pass `Server Compatibility Mode=NoTypeLoading` in the connection string, which stops Npgsql from loading types from the database, and makes it use a hardcoded internal list instead (of which `uuid` is a part). However, any use of fancier/user-defined types (which may or may not be supported by Cockroach) wouldn't work.

Will monitor this issue in case you guys need any help with Npgsql.

**Comment by bhavyabhatj** [comment] 2020-03-17 18:16
Thanks for your reply.  We will certainly try the workaround which you suggested.  But it will be glad if we can get to know why only sometimes we are getting this error when npgsql tries to load type from cockroach database.

**Comment by roji** [comment] 2020-03-26 01:39
@bhavyabhatj I honestly can't say why this only happens sometimes, the Cockroach folks may be able to help you there.

You should definitely not need to delete any tables - the issue is only with Npgsql not seeing the UUID *type* when loading all types from Cockroach. You may want to try invoking NpgsqlConnection.ReloadTypes(), which will attempt to reload again; if this issue is caused by some flakiness on the Cockroach side, this may mitigate it somewhat.

**Comment by rafiss** [comment] 2020-04-23 19:27
It's possible that this relates to https://github.com/cockroachdb/cockroach/issues/43177 -- the issue there is that `pg_type` will be empty unless the user has `SELECT` permissions on the whole database. @bhavyabhatj do you know what permissions the database user has when you repro the issue?

**Comment by rafiss** [comment] 2021-02-08 04:51
Closing this as the privileges issue I mentioned above likely explains this. Please feel free to re-open and comment if there is still a problem.

**Closed by rafiss** 2021-02-08 04:51 UTC
Labels: C-investigation, O-community, S-3-wrong-metadata
