### ISSUE TITLE
Admin UI not working for cockroach demo

### ISSUE THREAD

**Issue by ericharmeling** [cockroachdb/cockroach#46586] opened 2020-03-25 20:37 UTC
**Describe the problem**

The server at the "Web UI" link provided by `cockroach demo` cluster will not load the Admin UI past the log-in screen.

```
$ cockroach demo
```

```
#
# Welcome to the CockroachDB demo database!
#
# You are connected to a temporary, in-memory CockroachDB cluster of 1 node.
#
# This demo session will attempt to enable enterprise features
# by acquiring a temporary license from Cockroach Labs in the background.
# To disable this behavior, set the environment variable
# COCKROACH_SKIP_ENABLING_DIAGNOSTIC_REPORTING=true.
#
# Beginning initialization of the movr dataset, please wait...
#
# The cluster has been preloaded with the "movr" dataset
# (MovR is a fictional vehicle sharing company).
#
# Reminder: your changes to data stored in the demo session will not be saved!
#
# Web UI: http://127.0.0.1:55136
#
# The user "root" with password "admin" has been created. Use it to access the Web UI!
#
# Server version: CockroachDB CCL v20.1.0-beta.2-1088-gffd0a5226c-dirty (x86_64-apple-darwin19.3.0, built 2020/03/25 20:22:52, go1.13.4) (same version as client)
# Cluster ID: 9ef59bdb-ce4a-4245-9a64-baf016963a05
# Organization: Cockroach Demo
#
# Enter \? for a brief introduction.
#
root@127.0.0.1:55138/movr>
```

I navigated to the link provided in Google Chrome, and the log-in page appears:

![image](https://user-images.githubusercontent.com/27286675/77582518-e8144580-6eb5-11ea-9d8b-252769fd373b.png)

I entered "root" and "admin", but pressing "Log In" does not load the next page.

I rebuilt `cockroach`, restarted `cockroach demo`, used a different web browser, and the problem persisted.

**Environment:**
 - CockroachDB version: CockroachDB OSS v20.1.0-beta.2-1088-gffd0a5226c-dirty (x86_64-apple-darwin19.3.0, built 2020/03/25 20:22:52, go1.13.4)
 - Server OS: macOS
 - Client app: `cockroach demo`

**Comment by awoods187** [comment] 2020-03-25 20:39
Thanks for filing! This is a duplicate of https://github.com/cockroachdb/cockroach/issues/46550

**Closed by awoods187** 2020-03-25 20:39 UTC
Labels: A-demo, A-webui-general, C-bug

**Comment by ericharmeling** [comment] 2020-03-25 20:48
> Thanks for filing! This is a duplicate of #46550. You can pass --insecure in the meantime.

Oh wow! We filed this on the same day!
