### ISSUE TITLE
Failed tests (12724): TestChaos

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4340] opened 2016-02-11 23:31 UTC
The following test appears to have failed:

[#12724](https://circleci.com/gh/cockroachdb/cockroach/12724):

```
W0211 23:26:32.072750 27535 acceptance/chaos_test.go:233  round 2: monkey sleeping while cluster recovers...
I0211 23:26:32.073260 27535 acceptance/chaos_test.go:160  client 0 shutting down
I0211 23:26:32.080404 27535 acceptance/chaos_test.go:160  client 2 shutting down
I0211 23:26:32.080636 27535 acceptance/chaos_test.go:160  client 1 shutting down
W0211 23:26:32.173158 27535 acceptance/chaos_test.go:237  round 2: cluster recovered
panic: test timed out after 5m0s

goroutine 228 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0xcd91f8, 0x1106240, 0xe, 0xe, 0x31ff9e90b103e01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
testing.(*M).Run(0xc8202a9f08, 0xcd8a60)
	/usr/local/go/src/testing/testing.go:494 +0x70
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc8202a9f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:140 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:78 +0x113

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive, 2 minutes]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x11225e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1029 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:610 +0xbc

goroutine 6 [syscall, 4 minutes]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [select, 4 minutes, locked to thread]:
runtime.gopark(0xcd98a0, 0xc82002af28, 0xb9dbc8, 0x6, 0x431b18, 0x2)
	/usr/local/go/src/runtime/proc.go:185 +0x163
runtime.selectgoImpl(0xc82002af28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa64
runtime.selectgo(0xc82002af28)
	/usr/local/go/src/runtime/select.go:212 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:227 +0x353
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:131 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:139 +0x30

goroutine 134 [semacquire, 4 minutes]:
sync.runtime_Semacquire(0xc8205cba78)
	/usr/local/go/src/runtime/sema.go:43 +0x26
sync.(*RWMutex).Lock(0xc8205cba70)
	/usr/local/go/src/sync/rwmutex.go:87 +0xa1
github.com/cockroachdb/cockroach/acceptance.TestChaos.func4(0xc8203a91a0, 0xc8205cba70, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/acceptance/chaos_test.go:169 +0x84
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:320 +0xfb
testing.(*common).FailNow(0xc820084750)
	/usr/local/go/src/testing/testing.go:336 +0x36
--
testing.tRunner(0xc820084750, 0x1106270)
	/usr/local/go/src/testing/testing.go:456 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:561 +0x86d

goroutine 156 [select, 4 minutes]:
net/http.(*persistConn).readLoop(0xc820010e70)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 23 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fbb022a6950, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820190920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820190920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201908c0, 0xc82018b000, 0x1000, 0x1000, 0x0, 0x7fbb05326050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200dc538, 0xc82018b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82015a370)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 24 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc82015a370)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 160 [select, 4 minutes]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7fbb05336a40, 0xc8202f43c0, 0xc820259120, 0xc8205d6480)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xee
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x335

goroutine 157 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820010e70)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 152 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fbb022a6710, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8205cd560, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205cd560, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205cd500, 0xc82029c000, 0x1000, 0x1000, 0x0, 0x7fbb05326050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c088, 0xc82029c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc82018e280)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:459 +0x210
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:493 +0x3a7

goroutine 176 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc8202739a0)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 213 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc82018f400)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 227 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc82045b360)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 194 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc820273f40)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 193 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc82018f360)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 137 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fbb022a6650, 0x72, 0xc8200141f0)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200d0f40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200d0f40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200d0ee0, 0xc8202b1000, 0x1000, 0x1000, 0x0, 0x7fbb05326050, 0xc8200141f0)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82002c080, 0xc8202b1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820596210)
	/usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 138 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820596210)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d

goroutine 201 [chan receive, 4 minutes]:
database/sql.(*DB).connectionOpener(0xc820546f00)
	/usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:481 +0x336
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-12 15:30
Duplicate of #4316.

**Closed by petermattis** 2016-02-12 15:30 UTC
Labels: test-failure, TestChaos
