### ISSUE TITLE
uuid_v4 used in WHERE clause causes unoptimized query plan

### ISSUE THREAD

**Issue by novabyte** [cockroachdb/cockroach#20102] opened 2017-11-16 17:20 UTC
**BUG REPORT**

Tested on cockroachdb 1.1.2 with Go lib/pg driver.
The database start command used was "cockroach start --host=localhost --background --insecure".

I've used [dbbench](https://github.com/memsql/dbbench) to perform some active benchmarks with cockroachdb and found a strange occurence with one test:

```ini
[fetch one user by handle not found]
query=SELECT (id, handle, fullname, avatar_url, lang, location, timezone, metadata, created_at, updated_at, last_online_at) \
	FROM users \
	WHERE handle = from_uuid(uuid_v4()) LIMIT 1
```

The purpose of the test was to verify that a login attempt with Nakama server for a user which does not exist performs as expected. The query plan for the execution looks like:

```
EXPLAIN SELECT (id, handle, fullname, avatar_url, lang, location, timezone, metadata, created_at, updated_at, last_online_at) FROM users WHERE handle = from_uuid(uuid_v4()) LIMIT 1;
+-------+--------+-------+---------------+
| Level |  Type  | Field |  Description  |
+-------+--------+-------+---------------+
|     0 | limit  |       |               |
|     1 | render |       |               |
|     2 | scan   |       |               |
|     2 |        | table | users@primary |
|     2 |        | spans | ALL           |
+-------+--------+-------+---------------+
```

In the benchmark node I've tested on with 500K user accounts it takes 4 seconds to complete the query. This didn't make sense because it should map to a KV operation on the index for the UNIQUE constraint with our handle column.

If I change the query above to use a fixed bad input string I get:

```
EXPLAIN SELECT (id, handle, fullname, avatar_url, lang, location, timezone, metadata, created_at, updated_at, last_online_at) FROM users WHERE handle = 'notfound' LIMIT 1;
+-------+------------+-------+-----------------------------+
| Level |    Type    | Field |         Description         |
+-------+------------+-------+-----------------------------+
|     0 | limit      |       |                             |
|     1 | render     |       |                             |
|     2 | index-join |       |                             |
|     3 | scan       |       |                             |
|     3 |            | table | users@users_handle_key      |
|     3 |            | spans | /"notfound"-/"notfound\x00" |
|     3 |            | limit |                           1 |
|     3 | scan       |       |                             |
|     3 |            | table | users@primary               |
+-------+------------+-------+-----------------------------+
```

This looks much better and performs very well (as anticipated). This also performs well:

```
EXPLAIN SELECT (id, handle, fullname) FROM users WHERE handle = btrim(' notfound ') LIMIT 1;
```

It appears that using the `uuid_v4` builtin function in the `WHERE` clause causes the query to fall back to a table scan? Is it because the function generates a value?

This doesn't affect any production workloads of ours. I was just curious because I may not be the only one to use the builtin functions to generate values with synthetic benchmarks 😄

**Comment by jordanlewis** [comment] 2017-11-16 17:48
Thanks for the report - this is a great observation. The proximal cause is that we don't treat impure functions (functions that may return a different value on each invocation) as constant.

This is a problem because the part of the query planner that creates index spans can only produce tight scans when its input filters have been reduced to comparisons against constants. Those constants normally get produced by a phase of planning called constant subexpression evaluation, which finds constant subexpressions (including those with builtin functions) and evaluates them once at the start of the plan.

Since `uuid_v4` is marked as impure, the constant subexpression evaluator skips it and doesn't hand a reduced comparison to index selection.

I think the underlying problem here is that the constant subexpression evaluator is currently used in a few different contexts that expect different results.

1. In `DEFAULT` expressions, we want to reduce constant subexpressions - but not evaluate impure functions. We want those functions to be run every time a new row is added.
2. In ordinary filter evaluation, we do want to evaluate impure functions to prevent this kind of bug.

**Comment by bdarnell** [comment] 2017-11-16 21:11
I think the behavior here is correct: we should evaluate impure functions once per row instead of evaluating them once for the query and treating it as a constant. For example, `SELECT * FROM tbl WHERE random() < 0.1` should return a sample of 10% of your data, instead of returning everything 10% of the time and nothing the rest .

**Comment by novabyte** [comment] 2017-11-17 01:16
@bdarnell I agree that the expression should be evaluated once per row but why is the performance different between:

```sql
SELECT (id, handle, fullname) FROM users WHERE id = uuid_v4() LIMIT 1;
```

And

```sql
SELECT (id, handle, fullname) FROM users WHERE id = b'FA5F31C6-55AD-45F8-8B59-A4C6D5359CB5' LIMIT 1;
```

There queries produce different query plans and drastically different performance when the result of the `uuid_v4()` function is to create a constant value applied to the subexpression?

**Comment by vivekmenezes** [comment] 2017-11-17 01:38
@novabyte I believe this is because our query planner thinks of this is a soft limit query where it doesn't know how many rows it needs to process before the limit is satisfied. See the introduction section of this RFC: https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20170602_distsql_limit.md 

We haven't completed the implementation of the RFC.

**Comment by jordanlewis** [comment] 2017-11-17 02:05
@vivekmenezes the explanation I gave was correct. The query planner can't evaluate a non constant subexpression, so it can't make an index span, so it has to do a table scan.

**Comment by bdarnell** [comment] 2017-11-17 02:28
> These queries produce different query plans and drastically different performance when the result of the uuid_v4() function is to create a constant value applied to the subexpression?

It's not a constant value - it's a different value for each row. And that means these two queries may have different results (due to the birthday paradox). The odds of a `uuid_v4()` match are so low that neither query would ever be expected to return anything, but for a random function with a smaller range (or where you don't use the entire range, as in my `WHERE random() < 0.1` example), it makes a big difference.

**Comment by RaduBerinde** [comment] 2018-04-27 14:48
This is not a bug IMO.

The query `SELECT (id, handle, fullname) FROM users WHERE id = b'FA5F31C6-55AD-45F8-8B59-A4C6D5359CB5' LIMIT 1;` can use the `users_handle_key`  index. The query with `uuid_v4()` cannot use the index, because we are not searching for a constant value; the condition is different every time we evaluate `uuid_v4()`, i.e. on every row. For example, `SELECT .. WHERE id = uuid_v4()` can, in principle, return multiple results with different `id`s (even though it's improbable).

**Closed by RaduBerinde** 2018-04-27 14:48 UTC
Labels: A-sql-optimizer, C-performance
