### ISSUE TITLE
backup: TestBackupRestoreNegativePrimaryKey flakiness in CI

### ISSUE THREAD

**Issue by richardwu** [cockroachdb/cockroach#20904] opened 2017-12-19 21:06 UTC
https://teamcity.cockroachdb.com/project.html?projectId=Cockroach_UnitTests&buildTypeId=&tab=testDetails&testNameId=-3236096413596094857&order=TEST_STATUS_DESC&branch_Cockroach_UnitTests=__all_branches__&itemsCount=50

cc: @benesch  @danhhz

**Comment by benesch** [comment] 2017-12-19 22:08
You sure this is flaky? It's never failed on master.

**Comment by benesch** [comment] 2017-12-27 17:28
Ah, it is indeed, but it's due to the same root cause as #21026. Closing in favor of that issue. Thanks for the spot, @richardwu!

**Closed by benesch** 2017-12-27 17:28 UTC
Labels: test-failure
