### ISSUE TITLE
TestRaftAfterRemoveRange fails with CPUS=4

### ISSUE THREAD

**Issue by tamird** [cockroachdb/cockroach#1980] opened 2015-08-05 20:13 UTC
Discovered in #1839.

https://circleci.com/gh/cockroachdb/cockroach/5526
https://circle-artifacts.com/gh/cockroachdb/cockroach/5526/artifacts/0/tmp/circle-artifacts.F4In60q/testrace.log

Note that this is a different failure from #1911.

**Comment by bdarnell** [comment] 2015-08-05 20:18
Looks like the same failure mode that @tschottdorf found in #1916. My comment there:

> OK, so it looks like a timing issue that was exposed by the fact that EndTransaction now takes longer. It has to do with coalesced heartbeats. After range 2 is removed, node 2 believes that it has no ranges in common with node 1, so it doesn't respond to heartbeats. We have a special case to send heartbeats when the receiving node doesn't know anything about the sending node, but nothing for when the recipient doesn't think there are any ranges in common. I think we just need to remove the cnt check from fanoutHeartbeat and reply unconditionally.

**Comment by tamird** [comment] 2015-10-06 16:01
This is still failing on the multi-cpu branch: https://circleci.com/gh/cockroachdb/cockroach/8289

https://circle-artifacts.com/gh/cockroachdb/cockroach/8289/artifacts/0/tmp/circle-artifacts.rGE3Ag6/test.log

**Comment by bdarnell** [comment] 2015-10-14 09:08
The latest failure is a duplicate of #1878

**Closed by bdarnell** 2015-10-14 09:08 UTC
Labels: multi-cpu, test-failure
