### ISSUE TITLE
Query not utilizing expected Index with ORDER BY on index expressions (greatest)

### ISSUE THREAD

**Issue by thesyncim** [cockroachdb/cockroach#115250] opened 2023-11-29 14:54 UTC
**Issue Description**
I am encountering an issue where a specific query is not using the expected index when ordering by a GREATEST function. Despite creating an index specifically designed for this query, CockroachDB's query optimizer does not seem to utilize it.

**Environment**
CockroachDB Version: 23.1.10
Deployment Details: multi-node cluster
**Steps to Reproduce**
Index Creation:

```sql
CREATE INDEX concurrently idx_channels_on_order ON channels
    (GREATEST(last_message_at, created_at) DESC)
    WHERE (deleted_at IS NULL) AND app_pk = 1266177;
```
Query Not Using the Index:

```sql
EXPLAIN ANALYSE
SELECT cid
FROM "channels" AS "channel"
WHERE (channel.app_pk = 1266177)
  AND (channel.deleted_at IS NULL)
ORDER BY GREATEST(channel.last_message_at, channel.created_at) DESC
LIMIT 10;




planning time: 1ms
execution time: 1m52s
distribution: local
vectorized: true
"rows read from KV: 16,224,249 (25 GiB, 2,517 gRPC calls)"
cumulative time spent in KV: 1m47s
maximum memory usage: 10 MiB
network usage: 0 B (0 messages)
regions: eu-west-1
sql cpu time: 15.7s

• top-k
│ nodes: n19
│ regions: eu-west-1
│ actual row count: 1
│ estimated max memory allocated: 10 KiB
│ estimated max sql temp disk usage: 0 B
│ sql cpu time: 263ms
│ estimated row count: 1
│ order: -column31
│ k: 1
│
└── • render
    │
    └── • filter
        │ nodes: n19
        │ regions: eu-west-1
        │ actual row count: 16,222,512"
        │ sql cpu time: 5.7s
        │ estimated row count: 16,223,242"
        │ filter: deleted_at IS NULL
        │
        └── • scan
              nodes: n19
              regions: eu-west-1
              actual row count: 16,224,249"
              KV time: 1m47s
              KV contention time: 0µs
              KV rows read: 16,224,249"
              KV bytes read: 25 GiB
              KV gRPC calls: 2,517"
              estimated max memory allocated: 10 MiB
              sql cpu time: 9.7s
              estimated row count: 16,370,833 (43% of the table; stats collected 12 minutes ago; using stats forecast for 16 hours in the future)"
              table: channels@channels_pkey
              spans: [/1266177 - /1266177]

```
**Expected Behavior**
I expected the query to utilize the idx_channels_on_order index for efficient ordering and filtering.

**Actual Behavior**
The query does not use the idx_channels_on_order index. Instead, it appears to perform a full table scan or uses another less efficient method, leading to suboptimal performance.

**Additional Context**
The table channels contain columns cid, app_pk, deleted_at, last_message_at, and created_at.
The dataset size is 16M records.
The EXPLAIN ANALYSE output indicates that the query is not using the idx_channels_on_order index.
Impact
This issue impacts the performance of critical queries in our application, leading to increased response times and resource usage.

Jira issue: CRDB-33943

**Comment by mgartner** [comment] 2023-11-29 21:04
Thanks for the report. This is a duplicate of #98681. I've added a simplified version of your example to the issue in this comment: https://github.com/cockroachdb/cockroach/issues/98681#issuecomment-1832696375

**Closed by mgartner** 2023-11-29 21:04 UTC
Labels: C-bug, O-community, X-blathers-triaged
