### ISSUE TITLE
sql: `SHOW server_version` not implemented

### ISSUE THREAD

**Issue by encryptio** [cockroachdb/cockroach#4345] opened 2016-02-12 04:53 UTC
Currently, the SQL command `SHOW server_version` returns the error `unknown variable: SERVER_VERSION`. Since cockroack declares 9.5.0 elsewhere (in the handshake, `sql/pgwire/v3.go`:153), it should probably return "9.5.0".

Context: At least one high level wrapper wants to verify that the server is at least 9.1 (and thus implements `SERIALIZABLE` correctly), but is unable to do so using the handshake variables because they're not exported in the driver used (`github.com/lib/pq`); `SHOW server_version` allows it to get the version after the handshake has finished.

**Comment by petermattis** [comment] 2016-02-12 13:20
What is the higher level wrapper that needs to know the server version? We're not attempting to be Postgres-compatible which makes me a little apprehensive about adding stuff like this.

**Comment by encryptio** [comment] 2016-02-12 16:19
`git.encryptio.com/kvl`, a Go package, used by me and a few other people with small projects.

AFAIK, there is no way to get the server version without using a SQL query when using `github.com/lib/pq` as the client library. Unfortunately, due to the `database/sql` layer in between it and the user (`kvl`), I don't think adding support for that is possible in `lib/pq` without doing a completely separate connection *just* to have the types change.

**Comment by bdarnell** [comment] 2016-02-12 17:09
What are you trying to determine by examining the server version? Is there another way to detect the presence of the feature you're looking for? (even if it's something as clumsy as trying to execute a statement using the feature and seeing if it fails)

We've already set a bit of a precedent by setting the `server_version` connection property, but that turns out to be used by the drivers themselves for information that is not easily accessible any other way (and if we had our own native driver as an alternative to the postgres protocol, this property would go away). The fact that it's less accessible is a feature. If we exposed a SQL `SHOW server_version` command, that would be a stronger commitment that we couldn't just replace with our own version number when running a custom protocol. Unless there's a really strong need for advertising a postgres version number we'd rather be able to return something like "CockroachDB 1.0" for `server_version` instead of pretending to be postgresql 9.5.

**Comment by encryptio** [comment] 2016-02-13 06:23
I'm checking to see if the `SERIALIZABLE` transaction isolation level is actually serializable or not; before PostgreSQL 9.1, `SERIALIZABLE` meant only snapshot isolation, which is insufficient for the transactions I'm running (I've tested.) Granted, 9.1 is pretty old by now, but people run databases that were already old when their now ancient distributions were made; I'd rather have it yell up front than silently corrupt data.

As for returning a CockroachDB-specific version, that's far more appropriate for the return value of the `version(), which returns an English text string including a few server details (and is *also* not implemented in cockroach at the moment.)

If there's a way I can reliably detect that I'm talking to CockroachDB from a SQL query, I could skip the version check in that case (assuming CockroachDB is really serializable, as it says on the tin.)

**Comment by bdarnell** [comment] 2016-02-13 16:59
We're like postgres 9.1 in that we have serializable transactions, but we're also like older versions in that we are missing other new features. There's just no way we can claim compatibility with a specific postgres version. 

We can definitely add a `version()` function which will return something like `CockroachDB/1.0`. If we implement `SHOW server_version` (to have a more easily parseable form), I think it should be for our version number and not postgresql's.

**Comment by dt** [comment] 2016-12-14 19:47
btw, #5763 added a `version()` builtin.

**Comment by jordanlewis** [comment] 2016-12-14 20:41
This is a dupe of #12112 and can be closed, I think.

**Closed by jordanlewis** 2016-12-14 20:41 UTC
Labels: enhancement
