### ISSUE TITLE
Failed tests (10503): TestReplicateRogueRemovedNode 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3569] opened 2015-12-31 11:07 UTC
The following test appears to have failed:

[#10503](https://circleci.com/gh/cockroachdb/cockroach/10503):

```
W1231 11:06:22.174018 975 multiraft/multiraft.go:1297  node 1 failed to send message to 3: multiraft/transport.go:157: unknown peer 3
W1231 11:06:22.181738 975 multiraft/multiraft.go:1297  node 2 failed to send message to 3: multiraft/transport.go:157: unknown peer 3
I1231 11:06:22.227660 975 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1231 11:06:22.227835 975 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1231 11:06:22.227970 975 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (1.46s)
	<autogenerated>:32: storage/client_raft_test.go:1321: condition failed to evaluate within 1s: storage/client_test.go:575: expected [16 0 5], got [16 5 5]
=== RUN   TestReplicateReAddAfterDown
E1231 11:06:22.230151 975 gossip/gossip.go:180  different node IDs were set for the same gossip instance (2147483647, 1)
I1231 11:06:22.231356 975 multiraft/multiraft.go:578  node 1 starting
I1231 11:06:22.231675 975 storage/replica.go:1307  gossiping cluster id  from store 1, range 1
I1231 11:06:22.232269 975 raft/raft.go:446  [group 1] 1 became follower at term 5
I1231 11:06:22.232420 975 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1231 11:06:22.232521 975 multiraft/multiraft.go:998  node 1 campaigning because initial confstate is [1]
I1231 11:06:22.232599 975 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I1231 11:06:22.232675 975 raft/raft.go:459  [group 1] 1 became candidate at term 6
--
I1231 11:06:31.108852 975 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
I1231 11:06:31.109064 975 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.42s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.82s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	29.661s
=== RUN   TestBatchBasics
I1231 11:06:14.668632 1035 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1231 11:06:14.675682 1035 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1231 11:06:14.689549 1035 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-01-04 20:17
Dupe of #3538

**Closed by bdarnell** 2016-01-04 20:17 UTC
Labels: test-failure, TestReplicateRogueRemovedNode
