### ISSUE TITLE
opt: return UPSERT canary column

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#58032] opened 2020-12-17 15:01 UTC
A user expressed interest in having a way of knowing if an UPSERTed row was an insert or an update. Internally, we already use a "canary" column for just this purpose.

The concrete proposal is to provide the option of returning a special `bool` column:  `RETURNING crdb_is_update`.

**Comment by jordanlewis** [comment] 2020-12-17 15:13
I wish Postgres exposed this via their return status codes, but they don't either.

```
jordan=# insert into a(a,b) values(1, 1) on conflict(a) do update set b=2;
INSERT 0 1
jordan=# select * from a;
 a | b
---+---
 1 | 1
(1 row)

jordan=# insert into a(a,b) values(1, 1) on conflict(a) do update set b=2;
INSERT 0 1
jordan=# select * from a;
 a | b
---+---
 1 | 2
(1 row)
```

**Comment by RaduBerinde** [comment] 2020-12-17 15:19
I think the requirement is to have this information per row.

**Comment by jordanlewis** [comment] 2020-12-17 15:20
I see, makes sense

**Comment by karlseguin** [comment] 2020-12-17 16:06
I believe this is a duplicate of:
https://github.com/cockroachdb/cockroach/issues/50418

**Comment by RaduBerinde** [comment] 2020-12-17 19:00
Ah, thanks, closing in favor of #50418.

**Closed** 2020-12-17 19:13 UTC
Labels: C-enhancement
