### ISSUE TITLE
Test failure in CI build 8941

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3011] opened 2015-11-05 05:38 UTC
The following test appears to have failed:

[#8941](https://circleci.com/gh/cockroachdb/cockroach/8941):

```
E1105 05:36:27.317892 16179 acceptance/localcluster/localcluster.go:398  node=1 status=restart
E1105 05:36:27.834713 16179 acceptance/localcluster/localcluster.go:398  node=2 status=start
I1105 05:36:31.901816 16179 acceptance/gossip_peerings_test.go:153  waiting for gossip to be connected
E1105 05:36:31.907229 16179 acceptance/localcluster/localcluster.go:398  node=2 status=restart
I1105 05:36:35.071375 16179 acceptance/localcluster/localcluster.go:525  stopping
--- FAIL: TestGossipRestart (39.45s)
	testing.go:157: acceptance/gossip_peerings_test.go:62: condition failed to evaluate within 1s: acceptance/gossip_peerings_test.go:57: node 0: acceptance/gossip_peerings_test.go:85: sentinel not found
=== RUN   TestPut
I1105 05:36:40.888004 16179 acceptance/localcluster/localcluster.go:211  started docker-spy: 172.17.0.24
I1105 05:36:40.888031 16179 acceptance/localcluster/localcluster.go:218  initializing cluster
I1105 05:36:45.252325 16179 acceptance/localcluster/localcluster.go:328  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.702070847
I1105 05:36:45.326001 16179 acceptance/localcluster/localcluster.go:333  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.702070847
I1105 05:36:47.529153 16179 acceptance/localcluster/localcluster.go:381  *** started roach0.local ***
  ui:    https://0.0.0.0:32784
  trace: https://0.0.0.0:32784/debug/requests
  logs:  /tmp/circle-artifacts.HVjqfWM/acceptance/roach0.local/cockroach.INFO
--
I1105 05:38:07.219283 16179 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32798/_status/logs/3
I1105 05:38:07.223820 16179 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32798/_status/stacks/3
I1105 05:38:07.227896 16179 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32798/_status/nodes/3
I1105 05:38:07.328300 16179 acceptance/localcluster/localcluster.go:525  stopping
--- PASS: TestStatusServer (22.50s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by kkaneda** [comment] 2015-11-05 05:42
Looks like dupe of #3003. Closing

**Closed** 2015-11-05 05:42 UTC
Labels: test-failure
