### ISSUE TITLE
kv: crash on dropping database

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#5241] opened 2016-03-14 20:20 UTC
I was trying to run some queries from the photo app locally and I noticed a crash.

This reproduces it:
```
DROP DATABASE TEST;
CREATE DATABASE TEST;
SET DATABASE=TEST;

CREATE TABLE IF NOT EXISTS users (
  id           INT,
  photoCount   INT,
  commentCount INT,
  name         STRING,
  address      STRING,
  PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS photos (
  id           BYTES DEFAULT EXPERIMENTAL_UUID_V4(),
  userID       INT,
  commentCount INT,
  caption      STRING,
  latitude     FLOAT,
  longitude    FLOAT,
  timestamp    TIMESTAMP,
  PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS photosByUserID ON photos (userID, timestamp);
CREATE TABLE IF NOT EXISTS comments (
  photoID   BYTES,
  commentID BYTES DEFAULT EXPERIMENTAL_UUID_V4(),
  userID    INT,
  message   STRING,
  timestamp TIMESTAMP,
  PRIMARY KEY (photoID, commentID)
);
CREATE UNIQUE INDEX IF NOT EXISTS commentsByPhotoID ON comments (photoID, timestamp);

DROP DATABASE TEST;
```

```
panic: attempt to clone resolve_intent_range:<header:<key:"\305" end_key:"\307" > intent_txn:<id:<1437:2699763392 9:/* unknown wire type 6 */ 4:/* unknown wire type 6 */ 28478418:/* unexpected EOF */ /* unexpected EOF */ >isolation:SERIALIZABLE key:"\307" epoch:0 timestamp:<wall_time:1457986634287956693 logical:0 > > status:COMMITTED poison:false > , which contains ed59c01e-eba0-4e26-90bd-d16c8f9eae96

goroutine 1085 [running]:
panic(0x13e5200, 0xc8207877e0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/util.CloneProto(0x7f8c57d0df00, 0xc820113148, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/clone_proto.go:60 +0x26d
github.com/cockroachdb/cockroach/kv.truncate(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc8205ea520, 0xc82057e000, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/batch.go:99 +0x70c
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func1(0xc8206c4da0, 0xc8206c4af0, 0xc8206c50d0, 0xc82030e980, 0x7f8c57d1f3a8, 0xc8205e2750, 0x8, 0xc820847d70)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:607 +0x11d
github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk(0xc82030e980, 0x7f8c57d1f4b0, 0xc8205b0f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:619 +0x16cf
github.com/cockroachdb/cockroach/kv.(*DistSender).Send(0xc82030e980, 0x7f8c57d1f4b0, 0xc8205b0f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:490 +0x42c
github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send(0xc82041e2a0, 0x7f8c57d1f4b0, 0xc8205b0f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:411 +0xce3
github.com/cockroachdb/cockroach/client.(*DB).send(0xc82030d040, 0xc8202b6800, 0x12, 0x20, 0x0, 0xc8205ea4e0)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:413 +0x16c
github.com/cockroachdb/cockroach/client.(*DB).(github.com/cockroachdb/cockroach/client.send)-fm(0xc8202b6800, 0x12, 0x20, 0x1, 0x7f8c57d994b0)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:378 +0x3e
github.com/cockroachdb/cockroach/client.sendAndFill(0xc8206c5888, 0xc8207b6380, 0x0, 0x10)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:343 +0x4d
github.com/cockroachdb/cockroach/client.(*DB).RunWithResponse(0xc82030d040, 0xc8207b6380, 0xc8209c1980, 0x5d7bb2)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:378 +0x6b
github.com/cockroachdb/cockroach/client.(*DB).Run(0xc82030d040, 0xc8207b6380, 0xc8205ea4e0)
	/go/src/github.com/cockroachdb/cockroach/client/db.go:369 +0x2b
github.com/cockroachdb/cockroach/storage.(*Replica).resolveIntents.func3(0x1632060)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1977 +0x31
github.com/cockroachdb/cockroach/storage.(*Replica).resolveIntents(0xc82069e0e0, 0x7f8c57d1f618, 0xc82005a300, 0xc8205cb000, 0x12, 0x22, 0x1, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1986 +0x9f5
github.com/cockroachdb/cockroach/storage.(*Replica).handleSkippedIntents.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1808 +0x2ec
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc820301180, 0x1f2027d, 0x12, 0x740, 0xc82072f590)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:141 +0xc9
```

It hits every time, but strangely doesn't hit if I comment out one of the tables and its index..

**Comment by tschottdorf** [comment] 2016-03-14 21:25
Any chance your data dump is not compatible with the binary you're running?
The assertion would suggest that.

**Comment by RaduBerinde** [comment] 2016-03-14 21:27
I use  `./cockroach start --store=type=mem,size=1G` which I assume starts empty every time.

**Comment by petermattis** [comment] 2016-03-14 21:30
This panic is coming from `util.CloneProto` and indicates a clone of a proto containing an array which isn't properly supported by gogoproto. @tamird knows more of the details.

**Comment by tschottdorf** [comment] 2016-03-14 21:36
Maybe, but

> panic: attempt to clone resolve_intent_range:<header:<key:"\305"
end_key:"\307" > intent_txn:<id:<1437:2699763392 9:/* unknown wire type 6
*/ 4:/* unknown wire type 6 */ 28478418:/* unexpected EOF */ /* unexpected
EOF */ >isolation:SERIALIZABLE key:"\307" epoch:0
timestamp:<wall_time:1457986634287956693
logical:0 > > status:COMMITTED poison:false > , which contains
ed59c01e-eba0-4e26-90bd-d16c8f9eae96

really looks a lot like old data (unknown wire types). Double-check that
there's no cockroach-data directory that the stuff may be running on
unbeknownst to you.

**Comment by RaduBerinde** [comment] 2016-03-14 23:06
No cockroach-data directory. The store is reported as `store[0]:  type=mem,size=954 MiB`.

Tried restarting without the --store arg and verified it created a fresh directory, same crash.

Something could be getting corrupted.. Here are some more messages from reproducing:

```
panic: attempt to clone resolve_intent_range:<header:<key:"\273" end_key:"\275" > intent_txn:<id:<389050636076:/* unexpected EOF */ 9:9226937799293643451 >isolation:SERIALIZABLE key:"\275" epoch:0 timestamp:<wall_time:1457996311636402072 logical:0 > > status:COMMITTED poison:false > , which contains e2f2b2ce-ca5a-4b49-bbaa-85c30aab0c80

panic: attempt to clone resolve_intent_range:<header:<key:"\273" end_key:"\275" > intent_txn:<id:<872 { 673:/* unexpected EOF */ 8:/* unexpected EOF */ 177392:/* unknown wire type 7 */ 901:/* unexpected EOF */ >isolation:SERIALIZABLE key:"\275" epoch:0 timestamp:<wall_time:1457996469689671052 logical:0 > > status:COMMITTED poison:false > , which contains c3368a2a-ca55-42d8-a5b9-0087cf56ad38

panic: attempt to clone resolve_intent_range:<header:<key:"\273" end_key:"\275" > intent_txn:<id:<227633:/* unexpected EOF */ 2:2543209542 67 { 5 { 0 { 10:/* unknown wire type 7 */ /* unexpected EOF */ >isolation:SERIALIZABLE key:"\275" epoch:0 timestamp:<wall_time:1457996486854650181 logical:0 > > status:COMMITTED poison:false > , which contains 8a936f4e-1546-4c96-979b-042b035791f6

```

**Comment by bdarnell** [comment] 2016-03-14 23:57
I think there are two separate issues here:

The first is that `ResolveIntentRange` is broken when used with `DistSender`, but we haven't noticed because our tests that use `ResolveIntentRange` and our tests that use `DistSender` are disjoint (or maybe things don't actually break until one of these requests actually spans two ranges?). This is because `ResolveIntentRange` contains a `Transaction`, whose ID is a type which triggers a bug in gogoproto. 

Second, the "unknown wire type" messages mean that this data is not a protobuf at all, not just a protobuf from an older `.proto` file. This suggests that there's some sort of corruption happening. I'm not sure where this kind of corruption would happen, though. I don't see any place where we're actually marshaling/unmarshaling the `ResolveIntentRangeRequest` anywhere along this stack.

**Comment by bdarnell** [comment] 2016-03-15 00:35
I think the corruption issue is a red herring. The corruption is always within the `intent_txn:<id:>` field. We can see from the end of the message that a UUID object is getting printed correctly. I think this is just a manifestation of the fact that gogoproto doesn't know how to deal with the UUID type.

When we print a `Transaction`, it has a custom `String` method that prints the UUID correctly. When we print a `TxnMeta` (which is what happens here), we get gogoproto's default string method which prints garbage. I can reproduce this in a simple test.

**Comment by tamird** [comment] 2016-03-15 16:00
I'm looking into this

**Closed** 2016-03-15 19:40 UTC
