### ISSUE TITLE
Cann't get data while table has column named 'name'

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#1986] opened 2015-08-06 01:09 UTC
My test case:
CREATE TABLE t1 (name INT PRIMARY KEY, c2 CHAR(10));
INSERT INTO t1 VALUES(1, 'AAA');
SELECT * FROM t1;

**Comment by vivekmenezes** [comment] 2015-08-06 01:25
Thanks for the report kaka. Do you think you can fix this bug? Thanks

**Comment by veteranlu** [comment] 2015-08-06 01:35
@vivekmenezes , let me try :)

**Comment by arypurnomoz** [comment] 2015-08-06 07:32
It's not just "name". "domain" and some common reserved word in sql seems also cannot be used as a column name

**Comment by petermattis** [comment] 2015-08-06 11:52
`NAME` and `DOMAIN` are both `unreserved_keywords` in the postgres grammar. We've removed the parts of the grammar that use these keywords (`ALTER DOMAIN` and the xml stuff) and can likely just remove them as tokens completely now.

**Comment by MBerhault** [comment] 2015-08-06 13:56
this is encodeSQLIdent adding escaped quotes around all keywords.
we could probably have it apply to only certain levels of keyword reserved-ness

**Comment by MBerhault** [comment] 2015-08-06 13:58
for info, here is a full sql logic test showing the failure:
```
statement ok
CREATE TABLE t1 (name INT PRIMARY KEY, c2 CHAR(10))

statement ok
INSERT INTO t1 VALUES(1, 'AAA');

query TTT colnames
SHOW COLUMNS FROM t1
----
Field Type     Null
name  INT      true
c2    CHAR(10) true

statement error column ""name"" not found
SELECT * FROM t1;
```

**Comment by veteranlu** [comment] 2015-08-06 17:16
@MBerhault u r right.

the error reported by parser.EvalExpr, because the Expr of scanNode.render added escaped quotes, but the column name of scanNode.vals don't add escaped quotes.

We can fix this bug with follow solution:
1. Add escaped quotes with column name which is reserved key while add to scanNode.vals, just like this:
```go
name :=encIdent(col.Name)
n.vals[name] = unmarshalValue(*col, kv)
```
2. Add escaped quotes with column while insert table

Which one is better?

**Comment by petermattis** [comment] 2015-08-06 20:53
@veteranlu A column name, even if it is a reserved word, is just the name without quotes, so I don't think the first option is correct. I think the problem is that `EvalExpr` has overly simplistic logic for looking up `QualifiedName`. Right now it just calls `QualifiedName.String()` and passes the result to `Env.Get()`. But it should really probably pass the `QualifiedName` itself to `Env.Get()`. Doing that is a somewhat invasive change. 

Even better, though, would be to get rid of `Env` entirely. Now that we can walk an expression and find all of the `QualifiedName` nodes, we should perform a pass before expression evaluation in which we replace `QualifiedName` with some sort of new `DRef` node. This would allow statement execution to properly map a `QualifiedName` to the correct column in cases where the name actually is qualified (e.g. `SELECT foo.bar FROM foo`) and allow faster expression evaluation since we could avoid the map lookup. This change is even more invasive than changing the signature of `Env.Get()`, though. Happy to provide more details if you still want to tackle fixing this.

**Comment by veteranlu** [comment] 2015-08-07 03:16
@petermattis I will check postgresql's implement， maybe there is some clues.

**Comment by veteranlu** [comment] 2015-08-07 07:38
@petermattis postgresql wouldn't quote unreserved keyword.
```java
/* Column identifier --- names that can be column, table, etc names.
 */
ColId:		IDENT									{ $$ = $1; }
			| unreserved_keyword					{ $$ = pstrdup($1); }
			| col_name_keyword						{ $$ = pstrdup($1); }
```

cockroach add quote for all kind of keyword.
```go
	if _, ok := keywords[strings.ToUpper(s)]; ok {
		fmt.Fprintf(buf, "\"%s\"", s)
		return
	}
```

Maybe we mixed reserved and unreserved keyword, we should add type for keyword, like postgresql:
```c
PG_KEYWORD("ALTER", ALTER, UNRESERVED_KEYWORD)
PG_KEYWORD("ALWAYS", ALWAYS, UNRESERVED_KEYWORD)
PG_KEYWORD("ANALYSE", ANALYSE, RESERVED_KEYWORD)		/* British spelling */
PG_KEYWORD("ANALYZE", ANALYZE, RESERVED_KEYWORD)
```
just only quote reserved keyword.

**Comment by petermattis** [comment] 2015-08-07 13:24
I'm fine with adding a type field to the `keywords` map. Or to add a separate `reservedKeywords` map.

**Comment by tamird** [comment] 2015-08-14 11:10
Looks like this is fixed now.
```
> create database t;
OK
> set database = t;
OK
> CREATE TABLE t1 (name INT PRIMARY KEY, c2 CHAR(10));
OK
> INSERT INTO t1 VALUES(1, 'AAA');
OK
> SELECT * FROM t1;
name	c2
1	AAA
```

**Closed by tamird** 2015-08-14 11:10 UTC

**Comment by petermattis** [comment] 2015-08-14 13:27
The qualified name lookup was fixed by #2021. Someone still needs to fix the unnecessary quoting of `non_reserved_keywords`.

**Comment by tamird** [comment] 2015-08-14 14:22
Meaning separating `sql/parser/keywords` into keywords and `sql/parser/reservedKeywords`? What's the symptom that would address?

**Comment by petermattis** [comment] 2015-08-14 14:27
Its a minor enhancement now: `SELECT name FROM bar` currently is output as `SELECT "name" FROM bar`. I'll file a separate issue.
