### ISSUE TITLE
No error returned when using materialized views in dbvisualizer 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24645] opened 2018-04-10 20:59 UTC
In DbVisualizer, I tried to select a materialized view. I was expecting an error since we do not support materialized views. Instead, no error was present in dbvisualizer or in the `logtostderr`

Here is the query that is run:
`SELECT n.nspname = ANY (current_schemas(true)), n.nspname, t.typname FROM pg_catalog.pg_type AS t JOIN pg_catalog.pg_namespace AS n ON t.typnamespace = n.oid WHERE t.oid = $1`

I180410 20:54:53.965198 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] [NoTxn pos:351] executing Sync

**Comment by jordanlewis** [comment] 2018-04-11 01:49
Probably a duplicate of #24646, just because we don't support something doesn't mean that we'll return an error when someone tries to ask for that thing.

For example, materialized views and temp tables (sometimes) are queried for by asking the `pg_catalog.pg_class` table, which holds all "relations" in the database, for all relations that have category "materialized view" or "temp table". We won't fail those queries.

On the other hand, sometimes tools will ask for values from tables like (and I'm making this up) `information_schema.materialized_views`, which we may not support.

What I'm trying to say is that this isn't a bug.

**Closed** 2018-04-11 14:37 UTC
Labels: pg-compat
