### ISSUE TITLE
After getting a JDBC Connection, calling getTransactionIsolation fails 

### ISSUE THREAD

**Issue by vladmihalcea** [cockroachdb/cockroach#14698] opened 2017-04-07 11:28 UTC
I wanted to integrate a connection pooling solution (e.g. c3p0, HikariCP) for the CockroachDB connections, but all solutions fail because the transaction isolation is inspected right after acquiring the JDBC Connection.

So HikariCP does this:

    transactionIsolation = connection.getTransactionIsolation();

While c3p0 does this:

    ResultSet rs = execSQLQuery("SHOW TRANSACTION ISOLATION LEVEL"); 

Both ending up throwing:

    org.postgresql.util.PSQLException: ERROR: there is no transaction in progress

According to [the docs](https://www.cockroachlabs.com/docs/show-transaction.html), we need to call BEGIN first:

```
BEGIN;

SET TRANSACTION ISOLATION LEVEL SNAPSHOT, PRIORITY HIGH;

SHOW TRANSACTION ISOLATION LEVEL;
```

However, since JDBC Drivers don't provide a begin method, most of them don't require the Java developer to mark the start of the transaction. This typically happens when the `setAutoCommit(false)` method is called.

So, if I didn't call  `setAutoCommit(false)`, it means that every statement should still work in auto-commit mode, so the BEGIN/COMMIT should be automatically wrapping any statement that I send to CockroachDB, right?

### Temporary workaround

By setting the default isolation level in HikariCP, the `getTransactionIsolation()` call can be skipped.

    properties.put("hibernate.hikari.transactionIsolation", "TRANSACTION_SERIALIZABLE");

**Comment by bdarnell** [comment] 2017-04-07 15:45
Duplicate of #14700. This issue is new in the 0406 beta release, so as another workaround you can use the 0330 beta instead.

**Closed by bdarnell** 2017-04-07 15:45 UTC
