### ISSUE TITLE
`debug zip`: provide redacted form of `system.jobs.payload` when --redact flag used

### ISSUE THREAD

**Issue by abarganier** [cockroachdb/cockroach#86315] opened 2022-08-17 15:36 UTC
**Is your feature request related to a problem? Please describe.**
https://github.com/cockroachdb/cockroach/pull/86180 introduced the --redact flag for the debug zip command. As a first iteration, it provides an immediate but coarse-grained level of compliance for debug zip bundles, where all sensitive data is omitted or redacted from the bundle (except for keys, which have been deemed necessary to support CockroachDB).

One area affected by this is the dumps of `crdb_internal.*` and `system.* tables`, where via an audit of all the dumped tables and their columns, we've implemented a mechanism where sensitive columns are simply omitted from the dumped tables when the --redact flag is provided.

However, this of course poses issues for our support team as some of these table dumps (and more specifically, certain columns) are crucial to their workflows.

One example of this is the `system.jobs` table. The `payload` column in this table can contain sensitive information (for example, unredacted URI parameters such as `AWS_ACCESS_KEY_ID` within the `statement` field). Therefore, in the first iteration of making debug zip compliant, this column has been omitted from `system.jobs.txt` when the `--redact` flag is passed to `debug zip`.

We should provide a way to provide these payloads in a redacted form, as opposed to omitting the payloads entirely. This information has been identified as important in our support workflows. Furthermore, much of the payload itself is not sensitive (the `statement` itself is the primary culprit), so we can likely still get a lot of use out of these payloads even with the sensitive bits redacted.

**Describe the solution you'd like**
Redaction of the payload is not immediately possible via a SQL query against `system.jobs`. Is there an analogous gRPC/http endpoint that can be utilized until we find a more robust redaction solution at the SQL level? 

If so, we can utilize such an endpoint and its available redaction facilities to provide job payloads where only sensitive information is redacted. The `payload` provides a lot of data that's not sensitive, so we should provide as much as possible to avoid scenarios where people needing to analyze jobs aren't left "blind".

Jira issue: CRDB-18693

Epic CRDB-12732

**Comment by thtruo** [comment] 2022-10-11 19:03
Heads up @abarganier I'm going to close out this issue since we identified that this is a dupe of https://github.com/cockroachdb/cockroach/issues/88069 which is already on the Jobs team's backlog.

**Closed by thtruo** 2022-10-11 19:03 UTC
Labels: C-enhancement, T-observability-inf, A-observability-inf
