### ISSUE TITLE
'Insufficient capacity' error when running in docker with volume mount on MacOS

### ISSUE THREAD

**Issue by bogatuadrian** [cockroachdb/cockroach#90150] opened 2022-10-18 16:06 UTC
**Describe the problem**

Hi. When running the CockroachDB docker image (`cockroachdb/cockroach:v22.1.9` and older, but after `v21.2.17`) on MacOS (Intel **and** M1) using a volume mount for the data dir, cockroach incorrectly reports "insufficient remaining capacity" when trying to add a column to a non-empty table:

```
root@127.0.0.1:26257/defaultdb> CREATE TABLE IF NOT EXISTS users (PRIMARY KEY (id),id UUID NOT NULL );
CREATE TABLE


Time: 15ms total (execution 14ms / network 1ms)

root@127.0.0.1:26257/defaultdb> INSERT INTO users (id) VALUES ('11b7282f-7c9d-4596-a10e-0a87fe7749de') ON CONFLICT(id) DO NOTHING;
INSERT 1


Time: 32ms total (execution 31ms / network 1ms)

root@127.0.0.1:26257/defaultdb> ALTER TABLE users ADD COLUMN new_column VARCHAR(128) UNIQUE;
ERROR: job 806213686315220993 was paused before it completed with reason: store 1 has insufficient remaining capacity to ingest data (remaining: 74 GiB / 0.1%, min required: 5.0%)
```

The sizes look wrong to me: `(remaining: 74 GiB / 0.1%, min required: 5.0%)`. Maybe I'm parsing it wrong, but it looks like CockroachDB is expecting to have 3TB of space for this simple `ALTER TABLE`. In any case, this command works in other circumstances, but not in the combination "CockroachDB v22 + MacOS + docker + volume mounts". Read the "Additional data" section for more details.

**To Reproduce**

Steps to reproduce:

1. On a MacOS with docker installed run:
  ```docker run -ti -v $(mktemp -d):/cockroach/cockroach-data cockroachdb/cockroach:v22.1.9 start-single-node```
1. Run the following commands
  ```sql
  CREATE TABLE IF NOT EXISTS users (
    PRIMARY KEY (id),
    id UUID NOT NULL
  );

  -- if this insert is skipped, then the ALTER TABLE works without any errors.
  INSERT INTO users (id)
    VALUES ('11b7282f-7c9d-4596-a10e-0a87fe7749de')
    ON CONFLICT(id) DO NOTHING;

  ALTER TABLE users
    ADD COLUMN new_column VARCHAR(128) UNIQUE;
  ```

**Expected behavior**

I'm expecting that the table is correctly updated.

**Additional data / screenshots**

Important Mentions:
1. This problem occurs on both Intel **and** M1 Macs
1. This problem **doesn't** happen if there are no elements in the altered table
1. The error **doesn't** occur when running the repro steps **without** volume mounts (so without the `-v ...` flag)
1. The error **doesn't** occur when running the native cockroach binary directly on MacOS
1. The remaining size reported is the available size of the MacOS filesystem as reported by `df`
1. The latest working image that I tested is `cockroachdb/cockroach:v21.2.17`, and the first image with problems is `cockroachdb/cockroach:v22.1.0`.
1. This is the error on the M1 machine that has `788Gi` available:
   ```
   ERROR: job 806204073413083137 was paused before it completed with reason: store 1 has 
   insufficient remaining capacity to ingest data (remaining: 788 GiB / 0.3%, min required: 5.0%)
   ```

**Environment:**
 - CockroachDB version 22; on 21 the error doesn't seem to happen
 - Server OS: MacOS 12.6
 - Client app: whatever cockroachdb docker image uses when running the `start-single-node` command

**Additional context**

This impacts our local development flows as we need to run cockroackdb in k3d with local volume mounts.

Jira issue: CRDB-20617

Epic CRDB-20293

**Comment by rafiss** [comment] 2022-10-18 18:12
I'm putting this on the Storage team's radar to start off with. I believe the space usage check is new in v22.1 (5a7a7bcfc2cd62698edda2e2977af4d5f34150a1), so the bug with inaccurate capacity may have been present before that too.

**Comment by nicktrav** [comment] 2022-10-24 21:22
@bananabrick - mind doing a quick triage of this one? Fortunately, there's a nice reproducer :)

**Comment by mylegfeelsfunny** [comment] 2022-10-26 20:32
Having this issue as well. It seems to make a key of `XXXX_crdb_internal_dpe_key`. Both `_crdb_internal_dpe_key` and the original constraints are not able to be dropped afterward.

**Comment by nicktrav** [comment] 2022-10-27 00:10
Posting some initial findings. This is certainly some Docker filesystem weirdness on macOS.

I threw together a little binary that calls `statfs` (which is what we do down in Pebble to compute the disk usage, [here](https://github.com/cockroachdb/pebble/blob/master/vfs/disk_usage_linux.go)) and prints out the stats (in GiB).

Same as the original report:

```bash
$ docker run --rm -it -v $(mktemp -d):/data test
root@757f1d4f16ec:/# ./test /data/
free: 498
avail: 498
total: 238476
```

The `total` amount above is certainly incorrect. I don't have 238 TiB on this macbook. The `free` and `avail` figures are accurate. The presence of a large (incorrect) denominator causes the 5% check to fail. Need to dig into _why_ Docker does this. I feel like I've seen this before, but can't recall. I'll ask around.

Given there are other ways to mount volumes, I tried a few different incantations, with results that are more in-line with what I'd expect.

Using a `docker volume` carved out of the engine's volume (size configured in the preferences of the app, in my case a 58 GiB volume):

```bash
$ docker volume create test
$ docker run --rm -it --mount source=test,target=/data test
root@f4dadf43af0e:/# ./test /data/
free: 7
avail: 4
total: 58
```

So that looks reasonable. The `ALTER TABLE` command works fine here.

Now with a tempfs:

```bash
$ docker run --rm -it --mount type=tmpfs,target=/data test
root@33996af4656c:/# ./test /data/
free: 3
avail: 3
total: 3
```

Same thing. Reasonable values, and the `ALTER TABLE` works.

Looks like you can also pass a size to the tmpfs mount (Neat! TIL.). In this case a 10 GiB volume:

```bash
$ docker run --rm -it --mount type=tmpfs,tmpfs-size=$(( 10 << 30 )),target=/data test
root@633bb897ca7d:/# ./test /data/
free: 10
avail: 10
total: 10
```

Looks good here too.

So there's something funky with Docker, macos, `-v`, and passing in a volume from the host.

FWIW, [our docs](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html) seem to indicate using a `docker volume`. Based on what we find here, I think it might be worth us updating some docs.

As a workaround, for now, I'd suggest seeing if one of the alternate incantations - e.g. `--mount type=tmpfs`, with a size, would do the trick.

**Comment by nicktrav** [comment] 2022-10-27 18:09
I've opened an internal ticket to make it more obvious in our documentation that using `-v` with a macOS filesystem can cause issues. The current recommendation is to use a volume.

@bogatuadrian - mind confirming if either a Docker volume or a tmpfs mount solve this issue for you?

**Comment by bogatuadrian** [comment] 2022-10-28 08:00
Thanks for looking into this.

> mind confirming if either a Docker volume or a tmpfs mount solve this issue for you?

Unfortunately we are using `k3d` for our local setup which seems to only support bind mounts. But from my perspective there's nothing much you can do at this point. We'll just stick to not using mounts for now.

**Comment by mylegfeelsfunny** [comment] 2022-10-28 15:23
We are using docker compose to mount our volumes. Is there a way get around this issue?

**Comment by nicktrav** [comment] 2022-10-28 15:30
I did find a bug in the storage engine (linked above) that I'm hoping will fix this. I will update when it has landed on the various release branches.

**Comment by mylegfeelsfunny** [comment] 2022-10-28 18:36
Posting a solution we were able to implement. 
Instead of 
````
services:
  cockroach:
    image: cockroachdb/cockroach:v22.1.2
    container_name: cockroach
    restart: always
    volumes:
      - ./config/cockroach/data:/cockroach/cockroach-data
````

we tried, which resolved the issue
````
services:
  cockroach:
    image: cockroachdb/cockroach:v22.1.2
    container_name: cockroach
    restart: always
    volumes:
      - config:/cockroach/cockroach-data

volumes:
  config:
    external: true
````

**Comment by nicktrav** [comment] 2022-10-28 19:05
@mylegfeelsfunny - glad to hear it. I've also made a note to see if we can get a docker-compose example included in our documentation.

**Comment by nicktrav** [comment] 2022-10-31 17:54
Backports have landed. The fix will appear in the next point release of 21.2, 22.1, and 22.2.1.

**Closed by nicktrav** 2022-10-31 17:54 UTC
Labels: C-bug, O-community, B-os-macos, X-blathers-triaged, T-storage

**Comment by Hades32** [comment] 2023-01-12 11:54
This also happens to me on WSL with CRDB v22.2.2
```
failed to ingest index entries during backfill: addsstable [/Table/119/2/"xxx"/"yyy"/0,/Table/119/2/"xxx"/"yyy"/0/NULL): store 1 has insufficient remaining capacity to ingest data (remaining: 3.4 GiB / 1.4%, min required: 5.0%)
```
Seems like the remaining value comes from the container space (IIRC that defaults to 10GB when empty) and the 1.4% seem to be 251GB of my root drive in WSL.

Is this a separate issue?

FYI as a quick workaround I'm just mounting to tmpfs:
```yaml
version: '3'
services:
  crdb:
    image: cockroachdb/cockroach:v22.2.2
    command:
    - start-single-node
    - --insecure
    ports:
    - 127.0.0.1:26257:26257
    - 127.0.0.1:28080:8080
    tmpfs:
      - /cockroach/cockroach-data:mode=770,size=50m
```

**Comment by nicktrav** [comment] 2023-01-12 15:25
@Hades32 - would you mind posting your original configuration? Were you using a Docker volume? Or were you passing through a volume directly from the host? The former is the recomended way, per our [docs](https://www.cockroachlabs.com/docs/v22.2/start-a-local-cluster-in-docker-linux).

**Comment by Hades32** [comment] 2023-01-13 06:44
@nicktrav I originally didn't have any volume, as this is used for tests only, so I want the data to not persist.but I also tried with a volume and that failed. I have yet to try a host dir, but that would not fit very well to our use-case

**Comment by nicktrav** [comment] 2023-01-13 15:08
> I also tried with a volume and that failed

Volumes should work too. I understand that you may not need the persistence, however, if it's not working as expected, that is something we should dig into. 

> I have yet to try a host dir, but that would not fit very well to our use-case

Tmpfs seems like it is a good fit for your testing usecase.

**Comment by nicktrav** [comment] 2024-06-11 21:30
@wodka - might be best if you can file an issue for your specific problem, filling out the template with your specific setup, version, platform, etc.
