### ISSUE TITLE
kv: timestamp cache degenerate case causes panic

### ISSUE THREAD

**Issue by spencerkimball** [cockroachdb/cockroach#4914] opened 2016-03-06 19:28 UTC
```
panic: start key greater than or equal to end key "\xbb\x8a" >= "\xbb\x8a"

goroutine 1015 [running]:
panic(0x4dfc320, 0xc820532880)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cockroachdb/cockroach/util/cache.(*IntervalCache).MakeKey(0xc820b64000, 0xc820267e38, 0x2, 0x8, 0xc820b42a18, 0x2, 0x8, 0x0, 0x0, 0x0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/cache/cache.go:434 +0x28e
github.com/cockroachdb/cockroach/storage.(*TimestampCache).Add.func1(0xc820267e38, 0x2, 0x8, 0xc820b42a18, 0x2, 0x8)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/timestamp_cache.go:128 +0xad
github.com/cockroachdb/cockroach/storage.(*TimestampCache).Add(0xc820881d40, 0xc820b42a00, 0x5, 0x8, 0xc820b42a18, 0x2, 0x8, 0x14395701722fdaeb, 0x0, 0xc820b42af0, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/timestamp_cache.go:245 +0x7a7
github.com/cockroachdb/cockroach/storage.(*Replica).endCmds(0xc820530680, 0xc8201f5500, 0x1, 0x1, 0xc82068ee10, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/replica.go:771 +0x4b4
github.com/cockroachdb/cockroach/storage.(*Replica).beginCmds.func1(0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/replica.go:750 +0x52
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd.func1(0xc820603080, 0xc8205eeda8)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/replica.go:855 +0x29
github.com/cockroachdb/cockroach/storage.(*Replica).addReadOnlyCmd(0xc820530680, 0x8348700, 0xc820665a10, 0x14395701722fdaeb, 0x0, 0x100000001, 0x1, 0x6, 0x0, 0xc82025b340, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/replica.go:871 +0x43e
github.com/cockroachdb/cockroach/storage.(*Replica).Send(0xc820530680, 0x8348700, 0xc820665a10, 0x14395701722fdaeb, 0x0, 0x100000001, 0x1, 0x6, 0x0, 0xc82025b340, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/replica.go:656 +0x505
github.com/cockroachdb/cockroach/storage.(*Store).Send(0xc8202bc600, 0x8348700, 0xc820665a10, 0x14395701722fdaeb, 0x0, 0x100000001, 0x1, 0x6, 0x0, 0xc82025b340, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/store.go:1491 +0xdc2
github.com/cockroachdb/cockroach/storage.(*Stores).Send(0xc82018a280, 0x8348700, 0xc820665980, 0x14395701722fdaeb, 0x0, 0x100000001, 0x1, 0x6, 0x0, 0xc82025b340, ...)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/storage/stores.go:186 +0x5ef
github.com/cockroachdb/cockroach/server.(*Node).executeCmd.func2()
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/server/node.go:677 +0x50e
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask(0xc82031b500, 0xc8205efe88, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:125 +0xd9
github.com/cockroachdb/cockroach/server.(*Node).executeCmd(0xc82011a300, 0x83056a0, 0xc82087d4b0, 0x0, 0x0, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/server/node.go:689 +0x1ab
github.com/cockroachdb/cockroach/server.(*Node).(github.com/cockroachdb/cockroach/server.executeCmd)-fm(0x83056a0, 0xc82087d4b0, 0x0, 0x0, 0x0, 0x0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/server/node.go:327 +0x50
github.com/cockroachdb/cockroach/rpc.syncAdapter.exec.func1(0xc8206658f0, 0xc8201703a0, 0x83056a0, 0xc82087d4b0)
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/rpc/server.go:50 +0x30
created by github.com/cockroachdb/cockroach/rpc.syncAdapter.exec
	/Users/spencerkimball/go/src/github.com/cockroachdb/cockroach/rpc/server.go:51 +0x53
```

**Comment by spencerkimball** [comment] 2016-03-06 19:29
Here's the preceding set of values being added to the timestamp cache:

```
adding /Table/51/1/30463-/Table/51/2 to ts cache for *roachpb.ScanRequest
adding /Table/52/2/35707-/Table/52/2/35708 to ts cache for *roachpb.ReverseScanRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/0-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/2/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/3/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/4/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/5/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/6/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"0=yWзF\xe2\xbcE\xf1\x8eJ \x94\x84"/7/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/2/17544/Sun Mar  6 19:13:38 UTC 2016/0-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/51/1/17544/0-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/51/1/17544/2/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/51/1/17544/3/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/51/1/17544/4/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/52/1/"\x1fIӻ)XH\x1d\x9aR\x98\x9f\x04-\xbb\x95"-/Table/52/1/<util/encoding/encoding.go:469: unknown escape sequence: 0x0 0x2> to ts cache for *roachpb.ScanRequest
adding /Table/51/1/17544/5/1-/Min to ts cache for *roachpb.ResolveIntentRequest
adding /Table/51/1/15499-/Table/51/2 to ts cache for *roachpb.ScanRequest
```
It's the last one which fails.

**Comment by nvanbenschoten** [comment] 2016-03-06 19:48
This looks like a duplicate of #4882, but I'm glad to have more context on the issue. Investigating now.

**Closed by nvanbenschoten** 2016-03-06 19:48 UTC

**Comment by nvanbenschoten** [comment] 2016-03-06 19:51
By the way, how long was your cluster running and what was it's environment (# nodes, load, anything else unusual)? I'm having trouble reproducing the issue.

**Comment by nvanbenschoten** [comment] 2016-03-06 20:08
Never mind, got it.
