### ISSUE TITLE
circleci: failed tests (13468): TestMultiRangeScanReverseScanInconsistent 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4694] opened 2016-02-26 18:40 UTC
The following test appears to have failed:

[#13468](https://circleci.com/gh/cockroachdb/cockroach/13468):

```
1      storage/replica.go:1777
I160226 18:38:16.369765 client/db.go:488  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:620: node 1 stopped
I160226 18:38:16.369794 storage/store.go:1612  [node=1,store=1,range=1] on RangeLookup: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:620: node 1 stopped
W160226 18:38:16.369837 storage/replica.go:1726  [node=1,store=1,range=1] failed to push during intent resolution: conflicting intents on [/Meta2/Table/13 /Meta2/Max]: resolved? false
I160226 18:38:16.369959 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestMultiRangeScanReverseScanInconsistent (0.07s)
	dist_sender_server_test.go:88: client/rpc_sender.go:83: failed to send RPC request Server.Batch: client is unhealthy
=== RUN   TestSingleRangeReverseScan
I160226 18:38:16.372171 server/context.go:165  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
	setting default rocksdb cache size to 30 GiB (half of system memory)
I160226 18:38:16.375370 rpc/clock_offset.go:154  monitoring cluster offset
I160226 18:38:16.376837 server/node.go:352  store store=0:0 ([]=) not bootstrapped
I160226 18:38:16.378320 raft/raft.go:459  [group 1] 1 became follower at term 5
I160226 18:38:16.378382 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160226 18:38:16.378412 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160226 18:38:16.378438 raft/raft.go:472  [group 1] 1 became candidate at term 6
--
W160226 18:38:22.209512 kv/dist_sender.go:621  failed to invoke BeginTransaction ["a",/Min), Put ["a",/Min), Put ["b",/Min): txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=f2e62438 key="a" rw=true pri=0.04633227 iso=SERIALIZABLE stat=PENDING epo=1 ts=1456511902.207903063,0 orig=1456511902.207903063,0 max=1456511902.207903063,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=94f92b5c key="b" rw=false pri=0.04633232 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456511902.204873775,0 orig=1456511902.204873775,0 max=1456511902.204873775,0
I160226 18:38:22.209734 client/db.go:488  failed batch: txn "kv/dist_sender_server_test.go:586 TestPropagateTxnOnPushError" id=f2e62438 key="a" rw=true pri=0.04633227 iso=SERIALIZABLE stat=PENDING epo=2 ts=1456511902.207903063,0 orig=1456511902.207903063,0 max=1456511902.257903063,0 failed to push "kv/dist_sender_server_test.go:560 TestPropagateTxnOnPushError.func1" id=94f92b5c key="b" rw=false pri=0.04633232 iso=SERIALIZABLE stat=PENDING epo=0 ts=1456511902.204873775,0 orig=1456511902.204873775,0 max=1456511902.204873775,0
I160226 18:38:22.258479 storage/replica_command.go:457  auto-gc'ed 94f92b5c (1 intents)
I160226 18:38:22.261211 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestPropagateTxnOnPushError (0.17s)
FAIL
FAIL	github.com/cockroachdb/cockroach/kv	27.231s
=== RUN   TestCombinable
--- PASS: TestCombinable (0.00s)
=== RUN   TestBatchSplit
--- PASS: TestBatchSplit (0.00s)
=== RUN   TestFlagsToStr
--- PASS: TestFlagsToStr (0.00s)
=== RUN   TestBatchRequestGetArg
--- PASS: TestBatchRequestGetArg (0.00s)
=== RUN   TestKeyNext
--- PASS: TestKeyNext (0.00s)

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-02-29 22:02
Duplicate of #4723.

**Closed by petermattis** 2016-02-29 22:02 UTC
Labels: test-failure
