### ISSUE TITLE
sql: panic during serialization of empty string in decimal placeholder

### ISSUE THREAD

**Issue by KarHack** [cockroachdb/cockroach#34429] opened 2019-01-30 22:23 UTC
** Node crashes and stops if you try to insert "" (empty string) in decimal type column. **

When I tried to update "" Empty string through my application, then the database just crashes and stops working, I have to restart the server using cockroach --start ....

** Steps of Execution **

When updating the table with new values, if one of the values are supposed to be a Decimal but I try updating the decimal with an Empty String, then the database crashes.

**Expected behavior**
Probably an SQL Error message should be returned suggesting that I am trying to update with the wrong datatype.

**Additional data / screenshots**
While testing this in sql, it behaves as expected, ie. it shows a type error, but while inserting from the application the db crashes.

**Environment:**
 - CockroachDB version 2.1
 - Server OS: Ubuntu
 - Client app Java JDBC Driver

**Comment by knz** [comment] 2019-01-31 01:02
@mjibson I think that's up your alley?

Justin Jaffray <notifications@github.com> schreef op 30 januari 2019 23:59:48 CET:
>Assigned #34429 to @knz.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cockroachdb/cockroach/issues/34429#event-2107972186

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mjibson** [comment] 2019-01-31 05:38
I'm not able to reproduce this. I tried:

```
create table t (d decimal);
insert into t values ('1');
update t set d = '';
```

and got an error:could not parse "" as type decimal

I also tried using prepare/execute and a lib/pq client with placeholders both using `update  t set d = $1` with an empty string and got the same error message as above. Can you give us the exact queries you ran including table schema?

**Comment by KarHack** [comment] 2019-01-31 07:07
I have also not been able to reproduce it in pure sql.
This is the table schema (or part of it)
CREATE TABLE IF NOT EXISTS product_temp_tb (
product_master_id UUID PRIMARY KEY DEFAULT uuid_v4()::UUID, 
weight DECIMAL(10,2) NOT NULL DEFAULT 0);

INSERT INTO product_temp_tb (weight) VALUES (0);

UPDATE product_temp_tb SET weight = $1 WHERE product_master_id = $2

> When I run the Update Statement through the JDBC then I get this Error "Unauthorized Err : An I/O error occurred while sending to the backend." And the Database Stops.

I am running on a ec2  t2.micro and running in -insecure mode.

I just reproduced this error through JDBC with this exact schema.  I am pretty sure I am doing something wrong.

**Comment by knz** [comment] 2019-01-31 10:47
@KarHack thanks for the extra instructions. Can you give us more info about how you are passing $1 and $2 through JDBC. What Java object types are you using for this?

**Comment by KarHack** [comment] 2019-01-31 12:23
@knz I am using an object of java.sql.PreparedStatement & adding it using setObject.
Also I am running CRDB 2.1.3.

**Comment by knz** [comment] 2019-01-31 12:53
What are the arguments you're using for `setObject`? What is the type of the values?

Alternatively you can run `set cluster setting sql.trace.log_statement_execute = true` in cockroachdb prior to your test and provide us with the resulting `cockroach-sql-exec.log` file. Thanks

**Comment by KarHack** [comment] 2019-01-31 13:06
I am using Parameter Index & Object to be stored as the arguments in setObject.

I know this is naive I did "set cluster setting sql.trace.log_statement_execute = true", and tested it, the db crashed, now where to get the file from? Thank you.

**Comment by knz** [comment] 2019-01-31 13:08
from the server, in directory `cockroach-data/logs`.

**Comment by KarHack** [comment] 2019-02-01 05:57
@knz Hello, did the logs show anything helpful? Do I need to change something?

I have reattached the logs.
[cockroach-sql-exec.log](https://github.com/cockroachdb/cockroach/files/2820267/cockroach-sql-exec.log)

**Comment by knz** [comment] 2019-02-01 11:58
@KarHack something is seriously wrong, the exec log looks like it has been corrupted. Here's an example:

```
I190131 13:03:45.403072 139280 sql/exec_log.go:164  [n1,client=172.31.1.215:53610,intExec=get-hashed-pwd] 3 exec "$ internal-get-hashed-pwd" {} "SELECT \"hashedPassword\" FROM system.public.users WHERE (username = $1) AND (\"isRole\" = $
```

The log message finishes with `$` which is not possible. Is it possible that you have loaded the log file in a text editor, which may have changed the text, then save it afterwards before you uploaded it to github?

Is it possible that you used a file transfer program between your ubuntu machine and your browser that could change the file?

Maybe you could zip the file on the server remotely, before you transfer it. I know that some file transfer programs will alter text files but not zip files.

Some more example corruption:

```
I190131 13:03:45.405667 139281 sql/exec_log.go:164  [n1,client=172.31.1.215:53610,user=cloud_kv_user] 6 exec "PostgreSQL JDBC Driver" {} "SELECT * FROM api_keys WHERE api_key = $1" {$1:"'IusrG4a047lcBTON4h2iZLANEC04YHFsjSQH6mCu4WO6KkuSl$
```

and 

```
I190131 13:03:45.419974 139289 sql/exec_log.go:164  [n1,client=172.31.1.215:53614,user=a36e_biz_user] 18 exec "PostgreSQL JDBC Driver" {} "UPDATE product_temp_tb SET weight = $1 WHERE product_master_id = $2" {$2:"'1294e419-2dae-4b99-a2d$
```

Because of this corruption it is not possible for us to properly analyze the cause of your crash yet. We would like to see this details.

**Comment by knz** [comment] 2019-02-01 12:00
Until we have more details about the args, here's the stack trace:

```
panic: failed to serialize placeholder: could not parse "" as type decimal [recovered]
        panic: panic while executing 1 statements: UPDATE _ SET _ = $1 WHERE _ = $2; caused by failed to serialize placeholder: could not parse "" as type decimal

goroutine 139289 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc4264b0a00, 0x3032640, 0xc4278007c0, 0x2688940, 0xc4292fbd90)
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc4264b0a00, 0x3032640, 0xc4278007c0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:387 +0x61
panic(0x2688940, 0xc4292fbd90)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.exprFmtCtxBase.func1(0xc424e2be90, 0xc4260fc2a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:40 +0x105
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*Placeholder).Format(0xc4260fc2a0, 0xc424e2be90)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/expr.go:721 +0x3e
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).formatNodeOrHideConstants(0xc424e2be90, 0x3005840, 0xc4260fc2a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/hide_constants.go:47 +0xa4
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*FmtCtx).FormatNode(0xc424e2be90, 0x3005840, 0xc4260fc2a0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/format.go:276 +0x8d
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.MakeExpression(0x3046ba0, 0xc4260fc2a0, 0xc4264b0eb0, 0xc424e217a0, 0x2, 0x2, 0x0, 0x0, 0xc424e217c8, 0x2, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/expression.go:84 +0x1d2
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.(*PhysicalPlan).AddRendering(0xc428fb1070, 0xc424e2bb90, 0x3, 0x3, 0xc4264b0eb0, 0xc424e217a0, 0x2, 0x2, 0xc425f2fe40, 0x3, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go:484 +0x225
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).selectRenders(0xc420835900, 0xc428fb1070, 0xc425f2fce0, 0xc4264b0eb0, 0xc4299c7080, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:1160 +0x2e1
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc420835900, 0xc4251336e0, 0x3025700, 0xc425f2fce0, 0xc4299c7080, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2283 +0xd8b
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan.func1(0x3032700, 0xc424e2a960, 0x2ad825d, 0x6, 0x3025700, 0xc425f2fce0, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2437 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4250620a0, 0x3025700, 0xc425f2fce0, 0x2ad825d, 0x6)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:124 +0x4e5e
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4250620a0, 0x3025700, 0xc425f2fce0, 0x6, 0x3025e40)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4250620a0, 0x3025e40, 0xc42803a500, 0x2ad86a1, 0x6)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:455 +0x1f9c
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitConcrete(0xc4250620a0, 0x3025e40, 0xc42803a500)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:114 +0x83
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc4250620a0, 0x3025780, 0xc4260fc900, 0x2ad5c1f, 0x5)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:468 +0x3991
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc4250620a0, 0x3025780, 0xc4260fc900, 0xc428fb3348, 0x6c4069)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8f
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x3032700, 0xc424e2a960, 0x3025780, 0xc4260fc900, 0x0, 0xc427801b00, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:65 +0x193
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan(0xc420835900, 0xc4251336e0, 0x3025780, 0xc4260fc900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2412 +0x205
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc420835900, 0xc4251336e0, 0x3025780, 0xc4260fc900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2366 +0x15e
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420835900, 0x3032700, 0xc424e2a960, 0xc4264b0eb0, 0xc4251336e0, 0xc425b39b90, 0x3025780, 0xc4260fc900, 0xc4291d6f00)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:752 +0x126
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc4264b0a00, 0x3032700, 0xc424e2a960, 0xc4264b0e18, 0x2, 0x7fbc13194f80, 0xc425b39dd0, 0x4854200, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x2d8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc4264b0a00, 0x3032700, 0xc424e2a960, 0x3036840, 0xc4204ddea0, 0x4854280, 0x0, 0x0, 0xc420057b30, 0x43, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa8a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc4264b0a00, 0x3032700, 0xc424e2a960, 0x3036840, 0xc4204ddea0, 0x4854280, 0x0, 0x0, 0xc420057b30, 0x43, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc4264b0a00, 0x3032700, 0xc424e2a960, 0x3036840, 0xc4204ddea0, 0x4854280, 0x0, 0x0, 0xc420057b30, 0x43, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc4264b0a00, 0x3032640, 0xc4278007c0, 0xc4201172d8, 0x5400, 0x15000, 0xc420117370, 0xc4292fb010, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1173 +0x1400
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc42094aff0, 0x3032640, 0xc4278007c0, 0xc4264b0a00, 0x5400, 0x15000, 0xc420117370, 0xc4292fb010, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:389 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc42094aff0, 0x3032640, 0xc4278007c0, 0xc4264b0a00, 0x5400, 0x15000, 0xc420117370, 0xc4292fb010, 0xc4292fb020, 0xc424e20d80)
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:313 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:312 +0x107c
```

@jordanlewis @RaduBerinde can you have a look at this stack trace and share what you think?

**Comment by knz** [comment] 2019-02-01 12:03
@KarHack please provide us the exact output of `cockroach version` too, thank you.

**Comment by KarHack** [comment] 2019-02-01 15:32
@knz Sorry about that, I copied it into a text editor.
I am using v2.1.3

I am having trouble downloading the file. I have downloaded it now, please check if this file is proper.
Really sorry for the inconvenience.
[cockroach-sql-exec.log](https://github.com/cockroachdb/cockroach/files/2822198/cockroach-sql-exec.log)

**Comment by KarHack** [comment] 2019-02-03 06:57
@knz Thanks a ton for looking into this issue, did these logs help or was it corrupted?

**Comment by knz** [comment] 2019-02-03 08:55
It helped thanks.

**Comment by KarHack** [comment] 2019-02-03 16:53
@knz Thank you.

**Comment by jordanlewis** [comment] 2019-02-03 17:14
@knz, you seem to have identified the cause of the issue but you haven't added any more details to the issue. Can you please share what you learned?

**Comment by knz** [comment] 2019-02-03 17:15
@jordanlewis I pinged you in the comment above https://github.com/cockroachdb/cockroach/issues/34429#issuecomment-459700503
see the stack trace

**Comment by jordanlewis** [comment] 2019-02-08 06:09
I can reproduce this problem on `2.1.4`, but not on master. On master, the query returns:

```
  testEmptyStringDec(MainTest): ERROR: could not parse "" as type decimal
```

@mjibson did something here change recently? Do we need to backport anything? I'll check in the test that I wrote in any event.

**Comment by mjibson** [comment] 2019-02-08 06:32
Hmm I don't recall anything. I'll try this test locally on 2.1 and see what happens.

**Comment by knz** [comment] 2019-02-08 09:38
The change on `master` I think is the big placeholder refactor by Radu.

**Comment by mjibson** [comment] 2019-02-08 18:25
That makes sense. I don't think this is a problem with decimals specifically, it's some kind of dist sql datum -> string -> datum problem.

**Comment by jordanlewis** [comment] 2019-02-28 19:41
Going to close this as wontfix for the 2.1 branch - it'll be fixed in our next major release.

**Closed by jordanlewis** 2019-02-28 19:41 UTC
Labels: A-sql-execution, C-bug, S-2-temp-unavailability
