### ISSUE TITLE
stress: failed test in cockroach/server/status/status.test: TestMetricsRecorder

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#4973] opened 2016-03-08 11:04 UTC
The following test appears to have failed:

```
=== RUN   TestMetricsRecorder
--- FAIL: TestMetricsRecorder (1.03s)
	recorder_test.go:287: recorder did not yield expected time series collection; diff:
		 [[97].Datapoints[0].Value: 10 != 0 [99].Datapoints[0].Value: 10 != 0 [101].Datapoints[0].Value: 10 != 0 [103].Datapoints[0].Value: 10 != 0 [105].Datapoints[0].Value: 10 != 0 [107].Datapoints[0].Value: 10 != 0 [109].Datapoints[0].Value: 10 != 0 [111].Datapoints[0].Value: 10 != 0]
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-08 15:22
Duplicate of #4907.

**Closed by petermattis** 2016-03-08 15:22 UTC
Labels: Robot, test-failure
