### ISSUE TITLE
circleci: failed tests (15790): TestReplicateRogueRemovedNode 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5825] opened 2016-04-03 00:38 UTC
The following test appears to have failed:

[#15790](https://circleci.com/gh/cockroachdb/cockroach/15790):

```
I160403 00:37:45.554204 storage/raft_transport.go:232  remote node 2 at 127.0.0.1:54206 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160403 00:37:45.554299 storage/raft_transport.go:232  remote node 3 at 127.0.0.1:33889 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
I160403 00:37:45.554877 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160403 00:37:45.555011 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160403 00:37:45.555116 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (15.43s)
	testing.go:113: storage/client_raft_test.go:1354: condition failed to evaluate within 15s: storage/client_test.go:827: expected [16 0 5], got [16 0 0]
=== RUN   TestReplicateReAddAfterDown
I160403 00:37:45.607191 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160403 00:37:45.608025 gossip/gossip.go:891  not connected to cluster; use --join to specify a connected node
I160403 00:37:45.609972 raft/raft.go:459  [group 1] 1 became follower at term 5
I160403 00:37:45.610026 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160403 00:37:45.610043 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160403 00:37:45.610058 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160403 00:37:45.610071 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
I160403 00:37:45.610093 raft/raft.go:500  [group 1] 1 became leader at term 6
--
I160403 00:38:00.421421 storage/raft_transport.go:197  establishing Raft transport stream to node 2 at 127.0.0.1:35097
--- PASS: TestInOrderDelivery (0.56s)
=== RUN   Example_rebalancing
W160403 00:38:00.972271 gossip/gossip.go:891  not connected to cluster; use --join to specify a connected node
--- PASS: Example_rebalancing (0.16s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	46.650s
=== RUN   TestBatchBasics
I160403 00:37:31.220836 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160403 00:37:31.222226 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I160403 00:37:31.225712 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160403 00:37:31.226339 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I160403 00:37:31.229100 storage/engine/rocksdb.go:137  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-05 15:03
Duplicate of #5775.

**Closed by petermattis** 2016-04-05 15:03 UTC
Labels: Robot, test-failure
