### ISSUE TITLE
ERROR: cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked

### ISSUE THREAD

**Issue by yiv** [cockroachdb/cockroach#18577] opened 2017-09-19 01:35 UTC
```
ERROR: cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked; range [n1,s1,r325/1:/System/tsd/cr.node.sql.mem.c…] has overlapping range r20540:/System/tsd/cr.node.sql.mem.client.max-p99.9/{1/10s/2017-08-17T23:00:00Z-3/10s/2017-08-17T23:00:00Z} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4]
```
I deployed cockroachdb sine v1.0.1, and this happened after i upgraded from v1.0.4 to v1.0.5, this didn't happen when i restart after upgraded, it happened days later after I have done upgrade when the concurrency growing, 

I use docker-compose to deploy 3 nodes of cockroachdb 
```
version: '3'
services:
  cockroach1:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach1
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - /data/docker/data/cockroach/roach1:/cockroach/cockroach-data
    command: start --insecure
    networks:
      - cocknetwork
    restart: always
  cockroach2:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach2
    volumes:
      - /data/docker/data/cockroach/roach2:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always
  cockroach3:
    image: cockroachdb/cockroach:v1.0.5
    hostname: cockroach3
    volumes:
      - /data/docker/data/cockroach/roach3:/cockroach/cockroach-data
    command: start --insecure --join=cockroach1
    networks:
      - cocknetwork
    restart: always 
networks:
  cocknetwork:
    driver: bridge
```
The error just happened on cockroach1

**Comment by vivekmenezes** [comment] 2017-09-19 03:05
@yiv thanks for reporting this problem. Is this the first time you started these cockroach servers, or was this part of a restart or upgrade to a new version? Thanks!

How many nodes are part of the cluster and which version of cockroachdb are you running?

supply the output of `cockroach version` and all flags/environment variables passed to `cockroach start`

Thanks!

**Comment by yiv** [comment] 2017-09-19 03:21
@vivekmenezes I have updated the comment,

**Comment by petermattis** [comment] 2017-09-19 17:48
@cuongdo Can you triage?

**Comment by tschottdorf** [comment] 2017-09-20 15:16
@yiv to help me investigate this further, could you send me the output of `./cockroach debug range-descriptors <path-to-store-directory>` for each of the nodes (the node has to be offline for this to work)? Note that this may contain sensitive information, so you may want to upload this on a private service and email me at tobias@cockroachlabs.com.

I'd also like all the log files you have from the first node (and, to be safe, also from the others). Again, there could be sensitive information in them.

Thanks!

**Comment by yiv** [comment] 2017-09-21 01:59
@tschottdorf 
after that error happened, i didn't find the right way to fix it, so i dumped all db data and remove all nodes container and also relative data directories

and the cockroach db is on service, if i shutdown the first node, others can not work, right?

I'll find a maintaining time to do the logs

**Comment by tschottdorf** [comment] 2017-09-21 17:29
> The cockroach db is on service, if i shutdown the first node, others can not work, right?

I'm not sure I understand the question. Could you elaborate? If you are running with three-way replication, it should be fine to restart the first node. If you kill it (i.e. not clean shutdown), you could have ~10s of unavailability. I would avoid running with only two out of three nodes for more than a short period of time, though, as you won't be able to lose another node without also losing cluster availability.

**Comment by yiv** [comment] 2017-09-22 06:30
@tschottdorf 

I use docker-compose to run three nodes on a **same host**.  cockroach1 export ports 26257 and 8080, cockroach2 and cockroach3 don't export any ports (please refer my upper docker-com.yml), just like what [Start a Cluster in Docker (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html) do.  

Right now, if I stop cockroach1, not just the cockroach1 and Admin UI can't not access, neither the cockroach2 and cockroach3, looks like I did't achieve **three-way replication**, I had do some document search, but didn't find any further detail about my issue.

**Comment by tschottdorf** [comment] 2017-09-22 13:59
Does the Admin UI show that you are running a three node cluster (when the nodes are actually running)?

**Comment by yiv** [comment] 2017-09-24 12:15
@tschottdorf 
yes, it does, it shows all three nodes join in a cluster, if I stop cockroach1 I will lose cluster availability, but if I stop cockroach2 or cockroach3 , the cluster is still available.

by the way, today the cluster lose cluster availability again, I will send the logs to your email, please help me out

**Comment by tschottdorf** [comment] 2017-09-25 15:51
@yiv I took a look at the logfiles you sent me and nothing looked particularly dramatic. I did notice though that the system seemed a bit overloaded, which may be in parts due to performance problems that we've fixed in 1.1 (which is slated to be released in the coming weeks).

This doesn't explain the availability problem you mention in your last comment. How are you connecting to the nodes? From your comment, it seems that perhaps you have your client set up to always connect to the first node (in which case nothing will work if you kill that one)? You'll either have to tell your clients to try all three nodes, or you point them at a load balancer (see `./cockroach gen haproxy`). Is that by any chance the issue? If not, could you provide me with a screenshot of the `/#/cluster/all/replication` page from the ui (in particular, the "replicas per store" metric)?

**Comment by yiv** [comment] 2017-09-25 16:44
@tschottdorf 
I am new to use cluster, I didn't know the cockroach cluster need a load balancer, I got the hint from https://gitter.im/cockroachdb/cockroach, and research the cockroach docs, find some useful docs about how to set  load balancer from [Manual Deployment](https://www.cockroachlabs.com/docs/stable/manual-deployment.html) which not be mentioned in [Start a Cluster in Docker (Insecure)](https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker.html)

many thanks for your patience

I am working on deploying  load balancer right now, then I will export the logs as you request above.

exciting to know 1.1 is coming.

**Comment by tschottdorf** [comment] 2017-09-28 18:24
Thanks @yiv! I'll close this issue (since the original error isn't reproducible), if you run into further problems please just open a new one 😄

**Closed by tschottdorf** 2017-09-28 18:24 UTC
Labels: community-questions

**Comment by yiv** [comment] 2017-09-29 01:44
@tschottdorf ok, thanks a lot, if this problem occur, I will submit immediately

**Comment by mjibson** [comment] 2018-01-18 20:05
I just ran into this issue while running a test on v2.0-alpha.20180116-346-g3e9ff26. I had started a 4 node cluster on GCE to do a 100GB CSV import test. I let it run overnight. In the morning the cluster had wedged. I stopped and restarted it. Some nodes started (but would only return the UI parts of the admin ui, no actual data). The log message from one of the nodes that didn't start at all was:

```
I180118 19:59:26.906106 20 storage/engine/rocksdb.go:541  opening rocksdb instance at "/mnt/data1/cockroach/cockroach-temp322469448"
I180118 19:59:27.138585 20 storage/engine/rocksdb.go:541  opening rocksdb instance at "/mnt/data1/cockroach"
I180118 19:59:27.403272 20 server/config.go:518  [n?] 1 storage engine initialized
I180118 19:59:27.403302 20 server/config.go:521  [n?] RocksDB cache size: 3.7 GiB
I180118 19:59:27.403313 20 server/config.go:521  [n?] store 0: RocksDB, max size 0 B, max open file limit 10000
I180118 19:59:27.409074 20 server/server.go:920  [n?] sleeping for 226.360769ms to guarantee HLC monotonicity
I180118 19:59:27.639488 62 gossip/server.go:219  [n?] received initial cluster-verification connection from {tcp mjibson-import-0002:26257}
I180118 19:59:28.404816 20 storage/store.go:1251  [n1,s1] [n1,s1,r2083/?:/Table/51/1/457{45133…-61004…}]: added to replica GC queue
E180118 19:59:29.543015 1 cli/error.go:102  cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked; range [n1,s1,r5150/3:/Table/51/8/45{33087…-65272…}] has overlapping range r3950:/Table/51/8/4{486513/486514/157389286/1-565272/565273/448232452/4} [(n4,s4):1, (n3,s3):2, (n1,s1):3, next=4]
Error: cockroach server exited with error: failed to start store: [n1,s1]: cannot addReplicaInternalLocked; range [n1,s1,r5150/3:/Table/51/8/45{33087…-65272…}] has overlapping range r3950:/Table/51/8/4{486513/486514/157389286/1-565272/565273/448232452/4} [(n4,s4):1, (n3,s3):2, (n1,s1):3, next=4]
Failed running "start"
E180118 19:59:29.547485 1 cli/error.go:102  exit status 1
Error: exit status 1
Failed running "start"
```

**Comment by mjibson** [comment] 2018-01-18 21:40
The store has been copied into the cockroach-issue-18577 gcs bucket for future investigation.

**Comment by tschottdorf** [comment] 2018-01-18 21:52
For the record, we suspect this is fixed by https://github.com/cockroachdb/cockroach/pull/21557 (not the original issue, but Matt's incarnation of it).
