### ISSUE TITLE
sql: implement pg_table_is_visible()

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#16394] opened 2017-06-07 21:05 UTC
`psql` uses `pg_table_is_visible` to display the available tables in `\d`. We should implement it - it takes an `oid` and returns a boolean indicating whether the table is present in the current search path.

https://www.postgresql.org/docs/9.6/static/functions-info.html

**Comment by bdarnell** [comment] 2017-06-07 21:29
Duplicate of #12538

**Closed by bdarnell** 2017-06-07 21:29 UTC

**Comment by jordanlewis** [comment] 2017-06-07 21:42
Heh, I even filed that other one... 🤦‍♂️
