### ISSUE TITLE
ui: graphs show interpolated data when no data is present

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7319] opened 2016-06-18 14:46 UTC
<img width="291" alt="screen shot 2016-06-18 at 10 40 01 am" src="https://cloud.githubusercontent.com/assets/6201335/16171633/cf0324be-3541-11e6-878c-2f20a830394d.png">

In the above graph, the server was down during the periods between the peeks. I would have expected the graph to show 0 values, but instead there is a line from the peak down to the next recorded value.

**Comment by maxlang** [comment] 2016-08-22 20:22
@mrtracy 

Since you're working on the data being returned, you should probably take a look at this. When we have no data at a specific timestamp, we should return undefined/null instead of nothing. This would make the fix a lot easier on the UI side.

**Comment by mrtracy** [comment] 2016-08-22 20:29
This is not data interpolation, this is simply a connected line graph.  We have two points with a gap in between, where the second point is recorded after a data crash. The second point actually is very close to a zero value.

What is missing is an additional interpolated point on the graph which represents "the value went to zero here".  That's going to be tricky; you need to detect a decrease in a graph that *should* be monotonic, and then insert an extra zero into the graph immediately after the point of the apparent crash.

This is therefore a client-side issue, not a backend issue.

**Comment by maxlang** [comment] 2016-08-22 20:56
The issue is that the UI doesn't currently know the sampling interval and so can't guess when there should've been a value but isn't.

Discussed with @mrtracy and decided we should pass through an option to the backend to fill missing values with `null`/`0`/`NaN`. Unfortunately it's not quite similar enough to the downsampling work he's doing currently to tack on.

https://github.com/grafana/grafana/issues/471
https://github.com/elastic/kibana/issues/3234
https://github.com/OpenTSDB/opentsdb/issues/673

@petermattis I moved this to 1.0, but feel free to comment on the priority of this issue.

**Comment by spencerkimball** [comment] 2017-04-01 23:55
@mrtracy could you update this issue? I haven't seen this problem in a good long time. Unless this is still a problem we intend to address, please close the issue.

**Comment by dianasaur323** [comment] 2017-04-19 19:01
I think it seems safe for us to close this issue out

**Closed by dianasaur323** 2017-04-19 19:01 UTC
