### ISSUE TITLE
sql: conditional statement diagnostics

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#57634] opened 2020-12-07 14:18 UTC
We should extend the statement diagnostics to allow enabling on a specific statement with additional conditions - eg only generate diagnostics if exec time > 100ms.

We would enable tracing for all instances of the statement until one execution satisfies the condition. This would be very useful to debug occasional slow instances of a query (high p99 time).

Epic: CRDB-8649

CC @awoods187 @andreimatei

**Comment by awoods187** [comment] 2020-12-07 15:06
How would you imagine this working? Some kind of filter setting inside of the activate? 
![image](https://user-images.githubusercontent.com/22278911/101367124-cc9a7080-3873-11eb-8798-5a93dd5e9c4a.png)

**Comment by RaduBerinde** [comment] 2020-12-07 15:21
Yeah, eg a checkbox that says "only collect statistics if execution time is above: XXX"

**Comment by awoods187** [comment] 2020-12-07 15:22
cc @Annebirzin

**Comment by Annebirzin** [comment] 2020-12-17 23:02
@awoods187 @RaduBerinde  I put together some designs for how this could work. There are 3 places from where a user can activate diagnostics: 

1. the statement list page
2. the statement detail page when no diagnostics have been activated
3. the statement details page when there have been diagnostics activated

For the first state, we currently show a modal with a description how diagnostics work. For the other 2 we do not show a modal.

Thinking for #1 we can just introduce the radio button selection below the description text. For #2 and 3, we can introduce a modal with just the radio button selection.

I've attached screenshots below to show how this looks and figma designs are [here](https://www.figma.com/file/C85d0mrz8dkNs7Nw5mcTmf/obsrv-statements?node-id=2017%3A7087)

![Screen Shot 2020-12-17 at 5 58 25 PM](https://user-images.githubusercontent.com/51920721/102554041-f59bdc00-4091-11eb-968b-b96b0ad702df.png)
![Screen Shot 2020-12-17 at 5 58 38 PM](https://user-images.githubusercontent.com/51920721/102554043-f6cd0900-4091-11eb-86f0-590601d5a47b.png)
![Screen Shot 2020-12-17 at 5 58 51 PM](https://user-images.githubusercontent.com/51920721/102554046-f7659f80-4091-11eb-9ae2-5206e3dd31b5.png)

**Comment by RaduBerinde** [comment] 2020-12-18 21:18
Thanks Anne, these are very good! The only thing we should change is the phrasing. The result will always be a "full" diagnostics bundle, we are choosing whether to collect it on any instance of the query, or wait until we see an instance that slower than X.  So maybe "Would you like to set a condition for the diagnostics collection? a) No, collect on the next instance of the statement; b) Yes, collect on the next instance of the statement that takes longer than <dropdown> ms"

**Comment by Annebirzin** [comment] 2020-12-19 16:19
Thanks Radu, that makes sense. I've updated the figma designs and the screenshots in my previous comment to reflect some copy changes. One question, should the use be able to define the timeframe (eg. 100ms) or would we set a predefined time?

**Comment by RaduBerinde** [comment] 2020-12-20 20:10
Definitely needs to be controllable by the user.

**Comment by Annebirzin** [comment] 2020-12-21 18:05
Ok I see, in that case I've updated the screens/figma link above to include a time picker so the user can control the time length for collecting diagnostics.

**Comment by RaduBerinde** [comment] 2021-06-09 18:25
We have seen multiple customer issues where this functionality would have been very useful.

One wart is that we really need to be able to cancel such a diagnostics request. If we set a time bound that is too high, the request will be open forever, and all instances of that query will run slower. Probably the safest way to do this would be for the user to also have to choose an "expiration time" from the request.

We should make this high priority for 21.2. I can work on the lower-level implementation but we will need UI changes.

**Comment by andreimatei** [comment] 2021-06-09 18:30
Another thing that came up on a customer call yesterday was the hesitation to enable diagnostics collection for a high-frequency query, because of the fear of the contention that will be caused by all nodes trying to write a bundle at the same time. One thing that was suggested was to optionally ask a single node to collect a bundle.

**Comment by RaduBerinde** [comment] 2021-06-10 18:53
CC @vy-ton for help with prioritization.

**Comment by lin-crl** [comment] 2021-07-24 22:32
In recent customer support cases [#1011](https://github.com/cockroachlabs/support/issues/1011) we find it challenging to identify the query and predicates used that had performance issues. Since the query is executed many times, and it doesn't use the same plan for each predicates. Having this feature would help us identify the root cause much faster

**Comment by maryliag** [comment] 2021-11-10 14:42
On the PR https://github.com/cockroachdb/cockroach/pull/72491 I can see this is also adding an `expires after`. The ui should have the input for that value too (with a default value of never expires)

**Comment by RaduBerinde** [comment] 2021-11-10 17:00
> On the PR #72491 I can see this is also adding an expires after. The ui should have the input for that value too (with a default value of never expires)

I would say that if a non-zero latency is selected, the `expires after` should default to something like 15 minutes; and there should be a hint or tooltip that explains that outstanding requests with latency cause all "fast" instances of that query to run slower.

**Comment by yuzefovich** [comment] 2021-11-23 22:36
#72491 has been merged, so we are now able to support conditional statement diagnostics on the DB side. It'd be great if @cockroachdb/sql-observability could prioritize resolving this issue before 22.1.

An additional flow that we need to work out as part of this issue is how to cancel an already created request for statement diagnostics. Imagine a scenario where a user creates a request with too large value for `MinExecutionLatency` that never expires - if no query instance runs slow enough, this will mean that every query instance matching the fingerprint will be traced every time, which will have non-trivial impact on the latency for that query fingerprint. (The only workaround right now is modifying the system table manually.)

We probably want to introduce some flow to cancel an already existing request. This will allow the user to then create a new request with the updated `MinExecutionLatency` or `ExpiresAfter` value (or make the request non-conditional).

**Comment by Annebirzin** [comment] 2021-12-07 03:47
I've updated the [Conditional statement diagnostic designs](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A129574) to include the Expiration After input, and also added the [request cancellation flows](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A130978)

a couple of open questions:
- For the [`MinExecutionLatency` selection](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A129586), are seconds and milliseconds good for units of time?
- For the [`ExpiresAfter` selection](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A127507), is it ok to only offer minutes as the unit of time?

@stbof wanted to get this on your radar for a copy review at some point:
- The description copy in the [modal](https://www.figma.com/file/xdmwvnFQd6KkO9RJ0XLDH0/22.1_SQL-obsrv_query-performance?node-id=4722%3A130433) is pulled from the current copy on the Statement details > Diagnostics tab (empty state) with a minor tweak to reference the new conditional collection option.
- There also may be a need for a tooltip on the Expiration field to let the user know that activating a bundle could cause the query to slow down 

Let me know any other thoughts 

cc @kevin-v-ngo @maryliag

**Closed** 2021-12-23 21:12 UTC
Labels: C-enhancement, O-postmortem, T-sql-observability, N-followup, A-sql-debug-bundle
