### ISSUE TITLE
kv: TestOwnNodeCertain goroutine leak

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#7462] opened 2016-06-24 12:35 UTC
```
--- FAIL: TestOwnNodeCertain (5.05s)
	leaktest.go:86: Leaked goroutine: goroutine 120 [IO wait]:
		net.runtime_pollWait(0x8401300, 0x77, 0x40559b0)
			/Users/pmattis/Development/go-1.6/src/runtime/netpoll.go:160 +0x60
		net.(*pollDesc).Wait(0xc8202de060, 0x77, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
		net.(*pollDesc).WaitWrite(0xc8202de060, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:82 +0x36
		net.(*netFD).connect(0xc8202de000, 0x0, 0x0, 0x8400498, 0xc8200104a0, 0xeceff1eb1, 0x1e3d49a5, 0x61150c0, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/fd_unix.go:127 +0x28e
		net.(*netFD).dial(0xc8202de000, 0x8400450, 0x0, 0x8400450, 0xc82000a960, 0xeceff1eb1, 0xc81e3d49a5, 0x61150c0, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/sock_posix.go:137 +0x364
		net.socket(0x54b4508, 0x3, 0x2, 0x1, 0x0, 0xc82000a900, 0x8400450, 0x0, 0x8400450, 0xc82000a960, ...)
			/Users/pmattis/Development/go-1.6/src/net/sock_posix.go:89 +0x429
		net.internetSocket(0x54b4508, 0x3, 0x8400450, 0x0, 0x8400450, 0xc82000a960, 0xeceff1eb1, 0xc81e3d49a5, 0x61150c0, 0x1, ...)
			/Users/pmattis/Development/go-1.6/src/net/ipsock_posix.go:161 +0x153
		net.dialTCP(0x54b4508, 0x3, 0x0, 0xc82000a960, 0xeceff1eb1, 0x1e3d49a5, 0x61150c0, 0x0, 0x1, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/tcpsock_posix.go:171 +0x12b
		net.dialSingle(0xc8201de000, 0x84003e8, 0xc82000a960, 0xeceff1eb1, 0x1e3d49a5, 0x61150c0, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:371 +0x40c
		net.dialSerial.func1(0xeceff1eb1, 0x1e3d49a5, 0x61150c0, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:343 +0x75
		net.dial(0x54b4508, 0x3, 0x84003e8, 0xc82000a960, 0xc820010480, 0xeceff1eb1, 0x1e3d49a5, 0x61150c0, 0x0, 0x0, ...)
			/Users/pmattis/Development/go-1.6/src/net/fd_unix.go:40 +0x60
		net.dialSerial(0xc8201de000, 0xc8205241b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:345 +0x7d0
		net.(*Dialer).Dial(0xc82013b9b0, 0x54b4508, 0x3, 0xc820210900, 0xb, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:239 +0x512
		net.DialTimeout(0x54b4508, 0x3, 0xc820210900, 0xb, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go-1.6/src/net/dial.go:200 +0xa3
		google.golang.org/grpc/transport.newHTTP2Client.func1(0xc820210900, 0xb, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:110 +0x69
		google.golang.org/grpc/transport.newHTTP2Client(0xc820210900, 0xb, 0xc82013be60, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:116 +0x111
		google.golang.org/grpc/transport.NewClientTransport(0xc820210900, 0xb, 0xc82013be60, 0x0, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/transport/transport.go:347 +0x4d
		google.golang.org/grpc.(*Conn).resetTransport(0xc8201d0000, 0x0, 0x0, 0x0)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:464 +0x448
		google.golang.org/grpc.NewConn.func1(0xc8201d0000)
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:350 +0x2a
		created by google.golang.org/grpc.NewConn
			/Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
```

**Comment by tamird** [comment] 2016-06-27 19:48
20k runs and no repro (my network stack died instead). closing.

**Comment by petermattis** [comment] 2016-06-27 20:07
This was happening to me frequently this weekend. I'll try to reproduce for you again, but I'm 99% positive this is still a problem.

**Comment by petermattis** [comment] 2016-06-27 20:13
Gah. Not reproducing for me either right now. What the heck? I've seen this a dozen times over the past week.

**Comment by tamird** [comment] 2016-06-27 20:14
Perhaps this is a fun interaction with another test?

**Comment by tschottdorf** [comment] 2016-06-27 20:34
If a goroutine from a previous test were to launch another goroutine (which
then leaked), then the goroutine leak would be blamed on the wrong test.
Not sure this is what's happening, just throwing one possible scenario out
there.

On Mon, Jun 27, 2016 at 4:14 PM Tamir Duberstein <notifications@github.com>
wrote:

> Perhaps this is a fun interaction with another test?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7462#issuecomment-228861475>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135P2_yV8e6GUgJBgVuLyzXH2RC4vnks5qQC8VgaJpZM4I9uhd>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment] 2016-06-28 13:24
@tschottdorf Yep, tried running `make stress PKG=./kv`. Also tried checking out code from last week to reproduce. No failures. So I'm going to close this issue which will be a sure fire way to make it rear its ugly head again.

**Comment by petermattis** [comment] 2016-06-29 19:14
Just had this happen again after running `make test`. Seems to be reproducible right now with `make stress PKG=./kv TESTS=TestOwnNodeCertain`.

```
--- FAIL: TestOwnNodeCertain (5.04s)
        leaktest.go:86: Leaked goroutine: goroutine 110 [IO wait]:
                net.runtime_pollWait(0x6b8f758, 0x77, 0x4055d30)
                        /Users/pmattis/Development/go-1.6/src/runtime/netpoll.go:160 +0x60
                net.(*pollDesc).Wait(0xc820210bc0, 0x77, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:73 +0x3a
                net.(*pollDesc).WaitWrite(0xc820210bc0, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/fd_poll_runtime.go:82 +0x36
                net.(*netFD).connect(0xc820210b60, 0x0, 0x0, 0x6b8e830, 0xc8201b2c00, 0xecf061485, 0x2e1dd97a, 0x6125480
, 0x0, 0x0, ...)
                        /Users/pmattis/Development/go-1.6/src/net/fd_unix.go:127 +0x28e
                net.(*netFD).dial(0xc820210b60, 0x6b8e7e8, 0x0, 0x6b8e7e8, 0xc8201f76b0, 0xecf061485, 0xc82e1dd97a, 0x61
25480, 0x0, 0x0, ...)
                        /Users/pmattis/Development/go-1.6/src/net/sock_posix.go:137 +0x364
                net.socket(0x54bf600, 0x3, 0x2, 0x1, 0x0, 0xc8201f7600, 0x6b8e7e8, 0x0, 0x6b8e7e8, 0xc8201f76b0, ...)
                        /Users/pmattis/Development/go-1.6/src/net/sock_posix.go:89 +0x429
                net.internetSocket(0x54bf600, 0x3, 0x6b8e7e8, 0x0, 0x6b8e7e8, 0xc8201f76b0, 0xecf061485, 0x2e1dd97a, 0x6
125480, 0x1, ...)
                        /Users/pmattis/Development/go-1.6/src/net/ipsock_posix.go:161 +0x153
                net.dialTCP(0x54bf600, 0x3, 0x0, 0xc8201f76b0, 0xecf061485, 0xc82e1dd97a, 0x6125480, 0x0, 0x0, 0x0, ...)
                        /Users/pmattis/Development/go-1.6/src/net/tcpsock_posix.go:171 +0x12b
                net.dialSingle(0xc82020f0e0, 0x6b8e780, 0xc8201f76b0, 0xecf061485, 0x2e1dd97a, 0x6125480, 0x0, 0x0, 0x0,
 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/dial.go:371 +0x40c
                net.dialSerial.func1(0xecf061485, 0x2e1dd97a, 0x6125480, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/dial.go:343 +0x75
                net.dial(0x54bf600, 0x3, 0x6b8e780, 0xc8201f76b0, 0xc8201b2be0, 0xecf061485, 0x2e1dd97a, 0x6125480, 0x0, 0x0, ...)
                        /Users/pmattis/Development/go-1.6/src/net/fd_unix.go:40 +0x60
                net.dialSerial(0xc82020f0e0, 0xc8202137b0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/dial.go:345 +0x7d0
                net.(*Dialer).Dial(0xc8200579b0, 0x54bf600, 0x3, 0xc820212d90, 0xf, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/dial.go:239 +0x512
                net.DialTimeout(0x54bf600, 0x3, 0xc820212d90, 0xf, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go-1.6/src/net/dial.go:200 +0xa3
                google.golang.org/grpc/transport.newHTTP2Client.func1(0xc820212d90, 0xf, 0x4a817c800, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:110 +0x69
                google.golang.org/grpc/transport.newHTTP2Client(0xc820212d90, 0xf, 0xc820057e60, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/transport/http2_client.go:116 +0x111
                google.golang.org/grpc/transport.NewClientTransport(0xc820212d90, 0xf, 0xc820057e60, 0x0, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/transport/transport.go:347 +0x4d
                google.golang.org/grpc.(*Conn).resetTransport(0xc8201d8000, 0x0, 0x0, 0x0)
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:464 +0x448
                google.golang.org/grpc.NewConn.func1(0xc8201d8000)
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:350 +0x2a
                created by google.golang.org/grpc.NewConn
                        /Users/pmattis/Development/go/src/google.golang.org/grpc/clientconn.go:356 +0x4e3
```

**Comment by vivekmenezes** [comment] 2016-06-30 15:25
https://github.com/cockroachdb/cockroach/blob/master/kv/transport.go#L177

could be the reason for these leaks?

**Comment by tamird** [comment] 2016-06-30 15:28
That's not the leaked goroutine, though.

The real reason for these leaks (I suspect) is that
grpc.(*ClientConn).Close() lies and doesn't immediately kill a connection
if it's in the middle of a retry loop (think backoff). #7494 should help
with this.

**Comment by petermattis** [comment] 2016-07-01 13:23
This is still happening for me. @tamird Have you had any success reproducing?

**Comment by tamird** [comment] 2016-07-05 15:46
I have not.

**Comment by tamird** [comment] 2016-07-05 17:17
Closing as a duplicate of #7524 which has more useful discussion.

**Closed by tamird** 2016-07-05 17:17 UTC
