### ISSUE TITLE
ui: Custom Chart Builder: unit dropdown selector is too wide

### ISSUE THREAD

**Issue by Annebirzin** [cockroachdb/cockroach#50149] opened 2020-06-12 18:46 UTC
In Advanced Debug > Custom Charts the Unit dropdown selector spans the width of the page and pushes the 'remove chart' button down:

![Screen Shot 2020-06-11 at 5 36 33 PM](https://user-images.githubusercontent.com/51920721/84441602-1dedde00-ac0a-11ea-91c3-55bd548f5a93.png)

**Comment by koorosh** [comment] 2020-10-08 13:44
Couldn't reproduce with on master (7bc2bf9c02)

Fixed by 7c86555287cd63ef6745757f48619b530d09f420

![Screen Shot 2020-10-08 at 3 00 02 PM](https://user-images.githubusercontent.com/3106437/95455971-4a76f400-0977-11eb-9086-6acb33feb56f.png)

**Closed by koorosh** 2020-10-08 13:44 UTC
Labels: C-bug
