### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestTxnDBPhantomDeleteAnomaly

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6840] opened 2016-05-21 12:18 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/82e5c27735be951890f22fc85888a2cf46a13605

Stress build found a failed test:

```
=== RUN   TestTxnDBPhantomDeleteAnomaly
W160521 04:31:49.396376 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160521 04:31:49.396442 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160521 04:31:49.399635 kv/txn_correctness_test.go:525  verifying all possible histories for the "phantom delete" anomaly
I160521 04:31:49.400125 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
E160521 04:31:49.400350 config/config.go:382  unable to determine largest reserved object ID from system config: descriptor table not found in system config of 0 values
--- FAIL: TestTxnDBPhantomDeleteAnomaly (1.61s)
	txn_correctness_test.go:581: ([R2(B) I2(B) DR1(A-C) SC1(A-C) W1(D-A+B) C1 C2]): unexpected failure running I2(B): txn "kv/txn_correctness_test.go:633 txn1" id=b891f0b1 key="31.A" rw=false pri=0.00000005 iso=SERIALIZABLE stat=PENDING epo=3 ts=0.000000000,1724 orig=0.000000000,1724 max=0.000000000,1724 wto=false rop=false failed to push "kv/txn_correctness_test.go:633 txn2" id=3e01d89b key="31.B" rw=true pri=0.00000009 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,1712 orig=0.000000000,1712 max=0.000000000,1712 wto=false rop=false
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
6 runs so far, 0 failures, over 20s
16 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
22 runs so far, 0 failures, over 40s
26 runs completed, 1 failures, over 43s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:53
Duplicate of #6763

**Closed by bdarnell** 2016-05-21 15:53 UTC
Labels: Robot, test-failure
