### ISSUE TITLE
randomize replica order within each bucket

### ISSUE THREAD

**Issue by veteranlu** [cockroachdb/cockroach#3078] opened 2015-11-10 11:37 UTC
datanode workload lost balance while running readonly stress test, It always choose the first replica as leader, randomize replica order maybe solve this problem, I find a TODO as follow:
`
// TODO(peter): need to randomize the replica order within each bucket.
func (rs replicaSlice) SortByCommonAttributePrefix(attrs []string) int {
`

**Comment by tamird** [comment] 2015-11-10 12:41
I think this is in progress in #3041

**Comment by veteranlu** [comment] 2015-11-10 14:31
@tamird That's great, can I close this issue?

**Comment by tamird** [comment] 2015-11-10 15:45
Yep. Closing as duplicate of #2957.

**Closed by tamird** 2015-11-10 15:45 UTC
