### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestTxnDBPhantomDeleteAnomaly

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6791] opened 2016-05-19 12:16 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/bfb28e1ab481c9cf2c475b85f55081e42ba851f5

Stress build found a failed test:

```
=== RUN   TestTxnDBPhantomDeleteAnomaly
W160519 04:32:52.360604 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 04:32:52.360670 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160519 04:32:52.362400 kv/txn_correctness_test.go:525  verifying all possible histories for the "phantom delete" anomaly
I160519 04:32:52.362761 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
E160519 04:32:52.362916 config/config.go:382  unable to determine largest reserved object ID from system config: descriptor table not found in system config of 0 values
--- FAIL: TestTxnDBPhantomDeleteAnomaly (1.56s)
	txn_correctness_test.go:581: ([R2(B) I2(B) DR1(A-C) SC1(A-C) W1(D-A+B) C2 C1]): unexpected failure running I2(B): txn "kv/txn_correctness_test.go:633 txn1" id=693f91af key="67.A" rw=false pri=0.00000005 iso=SNAPSHOT stat=PENDING epo=3 ts=0.000000000,3806 orig=0.000000000,3806 max=0.000000000,3806 wto=false rop=false failed to push "kv/txn_correctness_test.go:633 txn2" id=f0c699bd key="67.B" rw=true pri=0.00000009 iso=SERIALIZABLE stat=PENDING epo=0 ts=0.000000000,3794 orig=0.000000000,3794 max=0.000000000,3794 wto=false rop=false
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
8 runs so far, 0 failures, over 20s
16 runs so far, 0 failures, over 25s
16 runs so far, 0 failures, over 30s
16 runs so far, 0 failures, over 35s
22 runs so far, 0 failures, over 40s
31 runs so far, 0 failures, over 45s
32 runs so far, 0 failures, over 50s
32 runs so far, 0 failures, over 55s
39 runs so far, 0 failures, over 1m0s
47 runs so far, 0 failures, over 1m5s
48 runs so far, 0 failures, over 1m10s
48 runs so far, 0 failures, over 1m15s
54 runs so far, 0 failures, over 1m20s
61 runs so far, 0 failures, over 1m25s
64 runs so far, 0 failures, over 1m30s
64 runs so far, 0 failures, over 1m35s
67 runs completed, 1 failures, over 1m38s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:53
Duplicate of #6763

**Closed by bdarnell** 2016-05-21 15:53 UTC
Labels: Robot, test-failure
