### ISSUE TITLE
circleci: failed tests (13270): TestIntentResolution 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4594] opened 2016-02-23 15:26 UTC
The following test appears to have failed:

[#13270](https://circleci.com/gh/cockroachdb/cockroach/13270):

```
1      storage/replica.go:1776
1      server/node.go:560
I0223 15:23:53.559822 419 stopper.go:273  draining; tasks left:
1      storage/replica.go:1776
I0223 15:23:53.563491 419 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestIntentResolution (1.02s)
	intent_test.go:137: 0: unexpected non-local intents, expected [s x]: [s s x x]
=== RUN   TestBootstrapCluster
I0223 15:23:53.585393 419 raft/raft.go:459  [group 1] 1 became follower at term 5
I0223 15:23:53.585766 419 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0223 15:23:53.585957 419 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I0223 15:23:53.586136 419 raft/raft.go:472  [group 1] 1 became candidate at term 6
I0223 15:23:53.586382 419 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
I0223 15:23:53.586592 419 raft/raft.go:500  [group 1] 1 became leader at term 6
I0223 15:23:53.589849 419 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456241034.588s
I0223 15:23:53.590541 419 storage/replica.go:1182  reproposing 1 commands after empty entry
--
I0223 15:24:12.842582 419 stopper.go:273  draining; tasks left:
1      server/server.go:329
I0223 15:24:12.842674 419 server/server.go:351  node 1 status: {"desc":{"node_id":1,"address":{"network":"tcp","address":"127.0.0.1:56655"},"attrs":{}},"store_ids":[1],"range_count":4,"started_at":1456241051239381329,"updated_at":1456241052824550543,"stats":{"last_update_nanos":1456241052818683447,"intent_age":9,"gc_bytes_age":5043,"live_bytes":79305,"live_count":51,"key_bytes":2623,"key_count":51,"val_bytes":94305,"val_count":146,"intent_bytes":1633,"intent_count":27,"sys_bytes":5538,"sys_count":56},"leader_range_count":0,"replicated_range_count":0,"available_range_count":0}
I0223 15:24:12.844172 419 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (1.66s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	22.982s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.02s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.04s)
=== RUN   TestRuntimeStatRecorder
I0223 15:24:11.209870 446 server/status/runtime.go:137  runtime stats: 4 goroutines, 4.65MiB active, 50000000.00cgo/sec, 888820.00/282800.00 %(u/s)time, 185623.08 %gc (3x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.03s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-23 15:47
Presumably a dupe of #4579, although the messages are slightly different.

**Closed by bdarnell** 2016-02-23 15:47 UTC
Labels: test-failure
