### ISSUE TITLE
sql: support precision with date/time fields (tool compat)

### ISSUE THREAD

**Issue by ruzkant** [cockroachdb/cockroach#24714] opened 2018-04-12 05:13 UTC
A tool like liquibase for example supports specifying a precision in a datetime field and this then fails on cockroach db as postgres does not support the syntax. So I say syntax because in my use case it would be fine to ignore the precision, and merely have it as an alias, but can't say what the broader implications are of that approach.

See here as to what liquibase does for postgres:
https://github.com/liquibase/liquibase/blob/19c45e373dd84429f56be99c2800b38a012d7424/liquibase-core/src/main/java/liquibase/datatype/core/DateTimeType.java

**Comment by ruzkant** [comment] 2018-04-12 05:14
@BramGruneir this follows on from your request to log tool issues

**Comment by jordanlewis** [comment] 2019-05-15 04:19
Closing as duplicate of #32098, which has received a bit more discussion.

**Closed by jordanlewis** 2019-05-15 04:19 UTC
Labels: A-sql-pgcompat, C-enhancement
