### ISSUE TITLE
sql: Result of casting infinity to timestamp differs from PostgreSQL

### ISSUE THREAD

**Issue by nnaka2992** [cockroachdb/cockroach#82447] opened 2022-06-05 06:43 UTC
**Is your feature request related to a problem? Please describe.**
In PostgreSQL, casting both positive and negative infinity to timezone return positive or negative infinity respectively.
However, in CockroachDB, the casting returns the maximum and the minimum of timestamp.

**Describe the solution you'd like**
Make CockroachDB to return positive and negative infinity when casting positive and negative infinity to timestamp.

**Additional context**
```psql
admin=# select 'infinity'::timestamp positive_inf,'-infinity'::timestamp negative_inf;
select 'infinity'::timestamp positive_inf,'-infinity'::timestamp negative_inf;
 positive_inf | negative_inf 
--------------+--------------
 infinity     | -infinity
```
```crdb
root@localhost:26257/defaultdb> select '+infinity'::timestamp positive_inf, '-infinity'::timestamp negative_inf;
select '+infinity'::timestamp positive_inf, '-infinity'::timestamp negative_inf;
          positive_inf         |      negative_inf
-------------------------------+-------------------------
  294276-12-31 23:59:59.999999 | 4714-11-24 00:00:00 BC
```

Jira issue: CRDB-16398

**Comment by otan** [comment] 2022-06-06 03:19
This is a known issue and unfortunately not straightforward to solve - I'm closing this as a duplicate of #41564

**Closed by otan** 2022-06-06 03:19 UTC
Labels: C-enhancement, O-community, T-sql-experience
