### ISSUE TITLE
circleci: failed tests: TestSystemConfigGossip 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6019] opened 2016-04-12 21:43 UTC
The following test appears to have failed:

[#16221](https://circleci.com/gh/cockroachdb/cockroach/16221):

```
I160412 21:40:02.066141 gossip/client.go:83  closing client to node 1 (127.0.0.1:59609): gossip/client.go:177: stopping outgoing client to node 1 (127.0.0.1:59609); loopback connection
I160412 21:40:02.067990 gossip/server.go:206  node 1 received [store:1 system-db cluster-id first-range node:1 sentinel] from node 1 (0 fresh)
I160412 21:40:02.068069 gossip/server.go:261  @1: distantHops: 0 from 0
I160412 21:40:02.069073 storage/replica_command.go:580  auto-gc'ed bc837db4 (1 intents)
I160412 21:40:02.572615 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestSystemConfigGossip (1.55s)
	server_test.go:434: did not receive gossip message
=== RUN   TestOfficializeAddr
--- PASS: TestOfficializeAddr (0.01s)
=== RUN   TestStatusLocalStacks
E160412 21:40:02.594683 util/envutil/env.go:90  error parsing COCKROACH_LINEARIZABLE: strconv.ParseBool: parsing "abcd": invalid syntax
E160412 21:40:02.594826 util/envutil/env.go:90  error parsing COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE: strconv.ParseBool: parsing "abcd": invalid syntax
E160412 21:40:02.594903 util/envutil/env.go:146  error parsing COCKROACH_MAX_OFFSET: time: invalid duration abcd
E160412 21:40:02.595011 util/envutil/env.go:146  error parsing COCKROACH_METRICS_SAMPLE_INTERVAL: time: invalid duration abcd
E160412 21:40:02.595086 util/envutil/env.go:146  error parsing COCKROACH_SCAN_INTERVAL: time: invalid duration abcd
E160412 21:40:02.595192 util/envutil/env.go:146  error parsing COCKROACH_SCAN_MAX_IDLE_TIME: time: invalid duration abcd
--
I160412 21:40:21.099463 gossip/server.go:261  @1: distantHops: 0 from 0
I160412 21:40:21.100311 gossip/client.go:83  closing client to node 1 (127.0.0.1:44595): gossip/client.go:177: stopping outgoing client to node 1 (127.0.0.1:44595); loopback connection
I160412 21:40:21.351282 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160412 21:40:21.351888 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestReportUsage (1.36s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	60.774s
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.13s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	1.191s
I160412 21:40:36.300833 rand.go:76  Random seed: -1274696888175088464
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.01s)
=== RUN   TestSplitAndExpr
--- PASS: TestSplitAndExpr (0.02s)
=== RUN   TestSimplifyExpr

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-13 14:52
Duplicate of #5870.

**Closed by petermattis** 2016-04-13 14:52 UTC
Labels: Robot, test-failure
