### ISSUE TITLE
Invalid foreign key violation error code

### ISSUE THREAD

**Issue by mijicd** [cockroachdb/cockroach#16836] opened 2017-07-01 19:46 UTC
According to the [Postgres documentation](https://www.postgresql.org/docs/current/static/errcodes-appendix.html), violating a foreign key constraint should result in an error with status `foreign_key_violation`. However, instead of the specified value, status code `internal_error` is used.

The log message clearly mentions the cause:
```
pq: foreign key violation: value ['foo@example.com'] not found in users@primary [email]
```

**Comment by jordanlewis** [comment] 2017-07-01 21:30
Duplicate of #16196, which was solved by #16319. This fix will be included in the next major release.

**Closed by jordanlewis** 2017-07-01 21:30 UTC

**Comment by andreimatei** [comment] 2017-07-01 21:40
Or you can use next week's alpha release or perhaps the last one.

**Comment by mijicd** [comment] 2017-07-01 21:41
Thank you!
