### ISSUE TITLE
circleci: failed tests (14479): TestStoreMetrics 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5232] opened 2016-03-14 18:17 UTC
The following test appears to have failed:

[#14479](https://circleci.com/gh/cockroachdb/cockroach/14479):

```
I160314 18:16:50.446964 storage/raft_transport.go:221  remote node 2 at 127.0.0.1:40125 closed Raft transport with error: rpc error: code = 13 desc = "transport is closing"
E160314 18:16:50.447642 storage/raft_transport.go:229  rpc error: code = 13 desc = "transport is closing"
I160314 18:16:50.447682 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160314 18:16:50.447845 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160314 18:16:50.447976 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestStoreMetrics (0.09s)
	client_metrics_test.go:47: storage/client_metrics_test.go:84: sysbytes for store: actual 1012 != expected 902
	client_metrics_test.go:47: storage/client_metrics_test.go:85: syscount for store: actual 13 != expected 12
	client_metrics_test.go:91: storage/client_metrics_test.go:184: verifyStats failed, aborting test.
=== RUN   TestRaftLogQueue
W160314 18:16:50.449446 gossip/gossip.go:909  not connected to cluster; use --join to specify a connected node
I160314 18:16:50.456030 raft/raft.go:459  [group 1] 1 became follower at term 5
I160314 18:16:50.456204 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160314 18:16:50.456237 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160314 18:16:50.456269 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160314 18:16:50.456295 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
--
I160314 18:17:16.074634 stopper.go:273  draining; tasks left:
2      gossip/infostore.go:286
I160314 18:17:16.074675 stopper.go:273  draining; tasks left:
1      gossip/infostore.go:286
--- PASS: Example_rebalancing (0.15s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	28.399s
=== RUN   TestBatchBasics
I160314 18:17:02.113388 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I160314 18:17:02.120808 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160314 18:17:02.123284 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-14 18:21
Duplicate of #5208.

**Closed by petermattis** 2016-03-14 18:21 UTC
Labels: Robot, test-failure
