### ISSUE TITLE
release: v19.2.0-beta.20191014

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#41353] opened 2019-10-05 12:18 UTC
Candidate SHA: 27ea46b456d6b3dabac2c0f6c5c120ed316fffce
Deployment status: https://teamcity.cockroachdb.com/viewLog.html?buildId=1525663&buildTypeId=Cockroach_PublishProvisionalArtifacts
Nightly Suite: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_WorkloadNightly?branch=provisional_201910072154_v19.2.0-beta.20191014&buildTypeTab=overview 

[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: 2019-10-07

- [x] [Pick a SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-process of SHA.
- [x] [Tag the provisional SHA](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA) `provisional_201910072154_v19.2.0-beta.20191014`
- [x] [Publish provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries) - [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=1525663&buildTypeId=Cockroach_PublishProvisionalArtifacts)
- [x] [Check binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)   
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `WIP fill in date: usually Monday WIP`
- [ ] [Check cluster status](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [ ] [Tag release](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [ ] [Bless provisional binaries](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [ ] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)
 
- [ ] Update docs
- [ ] External communications for release

**Comment by knz** [comment] 2019-10-06 01:01
I am observing 18ms average latency on the beta cluster, compared to 6ms latency on the 19.1.5 cluster. That's probably worth investigating.
cc @nvanbenschoten

**Comment by knz** [comment] 2019-10-06 01:35
Next step: collect test failures from the nightly suite.

**Comment by knz** [comment] 2019-10-06 14:12
For docs: the release note from #26433 must be picked up manually.

**Comment by justinj** [comment] 2019-10-07 15:51
Proceeding with the expectation of releasing this this week (though some test failures look concerning).

Failed tests, requests for sign-off:
* [ ] TestRandomSyntaxSQLSmith @mjibson 

Failed roachtest nightlies:
* [ ] clearrange/checks=true @bdarnell 
* [ ] import/tpcc/warehouses=1000/nodes=32 @dt 
* [ ] jepsen/monotonic/majority-ring @bdarnell 
* [ ] jepsen/monotonic/majority-ring-start-kill-2 @bdarnell 
* [ ] jepsen/monotonic/split @bdarnell 
* [ ] jepsen/monotonic/start-kill-2 @bdarnell 
* [ ] pgjdbc @jordanlewis 
* [ ] tpccbench/nodes=9/cpu=4/multi-region @nvanbenschoten 
* [ ] tpchbench/tpchVec/nodes=3/cpu=4/sf=1 @jordanlewis 
* [ ] hibernate @jordanlewis 
* [ ] interleavedpartitioned @dt
* [ ] kv50/rangelookups/relocate/nodes=8 @bdarnell 

Took a best guess at assignees, please reassign if they're inappropriate.

**Comment by jordanlewis** [comment] 2019-10-07 15:55
Signed off on `tpchVec`, which tests functionality that's not enabled by default.
@rafiss can you look at `pgjdbc` and `hibernate` and sign off if appropriate?

**Comment by rafiss** [comment] 2019-10-07 16:27
Signed off:
- `pgdbc` had two new passing test cases, so we just have to update the expected failure blacklist
- `hibernate` tests have known stability problems, but there's nothing indicating there's a blocker

**Comment by bdarnell** [comment] 2019-10-07 16:30
The jepsen and clearrange problems are blockers; I've reassigned them to @dt and @andreimatei. I can't tell what happened with the kv50 test. I'm not seeing an immediate cause for concern, but this test isn't known to be flaky.

**Comment by andreimatei** [comment] 2019-10-07 20:14
I've got a revert that should make the Jepsen tests pass again - #41406

**Comment by bdarnell** [comment] 2019-10-07 20:26
The clearrange problem is a stats inconsistency (the replicas agree, but the MVCCStats don't agree with the values recomputed from scratch). This only crashes a cluster if COCKROACH_FATAL_ON_STATS_MISMATCH is set, and it's only set in our tests. While that's concerning (and I think still a blocker for the final release), I think we can unblock the beta and start qualifying a new build once #41406 lands.

**Comment by justinj** [comment] 2019-10-07 21:47
Reverting the status on this issue and starting the release process over with 27ea46b456d6b3dabac2c0f6c5c120ed316fffce.

**Comment by rafiss** [comment] 2019-10-09 16:37
signed off on hibernate -- known flakiness that we're working on

**Comment by bdarnell** [comment] 2019-10-09 16:38
Signed off on the kv50 failure. This test has never passed (as far back as teamcity has history) and it's a test scaffolding problem, not a bug in the product as far as I can tell (the workload driver is getting killed).

**Comment by lucy-zhang** [comment] 2019-10-09 17:07
Signed off on `schemachange/mixed/tpcc` as a known issue being investigated and not a beta release blocker.

**Comment by rohany** [comment] 2019-10-09 17:57
Signed off on interleavedpartitioned -- the test partitioning setup just needs to be fixed post a patch that added some more verification to zone configurations.

**Comment by nvanbenschoten** [comment] 2019-10-10 21:16
`tpccbench/nodes=9/cpu=4/multi-region` failed with the error `could not validate zone config: when per-replica constraints are set, num_replicas must be set as well`, which will be fixed by https://github.com/cockroachdb/cockroach/pull/41484.

`tpccbench/nodes=9/cpu=4/chaos/partition` failed with a timeout error, like it has been doing in https://github.com/cockroachdb/cockroach/issues/41027. This appears to be a test error. I think we're killing nodes faster than we can prepare all of the prepared statements on each worker, so we're getting into an endly retry loop in the workload. Will investigate more over there.

Signing off on both.

**Comment by nvanbenschoten** [comment] 2019-10-11 03:33
> I think we're killing nodes faster than we can prepare all of the prepared statements on each worker, so we're getting into an endly retry loop in the workload.

This was actually due to a connection limit in the HAProxy load balancer, which we are hitting now that the `tpccbench` search grows to 1230 warehouses. https://github.com/cockroachdb/cockroach/pull/41527 fixes the issue.

Still signing off on both tpccbench tests.

**Comment by asubiotto** [comment] 2019-10-14 14:34
Signed off on `cancel/tpcc/distsql/w=10,nodes=3`, it just seems like the query completed before cancellation could take place.

**Comment by jseldess** [comment] 2019-10-30 01:54
Should we close this?

**Closed** 2019-10-30 14:20 UTC
