### ISSUE TITLE
sql: SET CLUSTER SETTING doesn't reliably wait for propagation when run on a tenant

### ISSUE THREAD

**Issue by HonoreDB** [cockroachdb/cockroach#87201] opened 2022-08-31 17:57 UTC
[This test](https://gist.github.com/HonoreDB/74d8cbbfa60ed3053f74fea68e97fd68) fails or flakes on large enough n: you can't quite rely on logic that does things like

```
for mode in modes:
  run sql to set cluster settings for mode
  run more sql 
```

Because even if you're the only database client, it's possible that the cluster settings won't be what you think they are after setting them.

This has come up a few times in tests since they often test behavior against multiple cluster settings in the same session. In theory though it could also happen in real life: there are some cluster settings that are the only way to control behavior, so if you want to set them "per statement", you need to change them repeatedly.

This is probably related to the implementation of [waitForSettingUpdate](https://github.com/cockroachdb/cockroach/blob/d4f2c416fdf0ea6e8e27e3961ac26255d7e8cf9f/pkg/sql/set_cluster_setting.go#L556-L559) and/or the rangefeed consumer that propagates settings, but it's not obvious to me where the race condition is. I think ideally waitForSettingUpdate would wait until it sees a setting being propagated that's tagged as being from its own unique statement id, or we should document that just as you can't set cluster settings in a transaction or multi-statement block, you can't rely on sessions being ordered with respect to them.

Jira issue: CRDB-19212

**Comment by michae2** [comment] 2022-09-06 18:37
We don't currently guarantee that `SET CLUSTER SETTING` is synchronous, do we? Just session settings? @yuzefovich suggests maybe we should add a variant of `SET CLUSTER SETTING` that blocks until all nodes have the new value.

**Comment by ajwerner** [comment] 2022-09-06 18:43
1) This issue seems to talk about tenants, but I don't think it's particularly tenant specific. I don't see how tenants come into play.

2) I don't think waiting for all nodes to have the new value solves the underlying problem. Indeed, the experiment Aaron ran is on a single node. The problem is if you toggle the setting back and forth, the currently polling logic isn't smart enough to know whether it was due to some previous change. If we wanted to make the waiting robust, we'd need some notion of time and causality and wait for that causality token to propagate. The truth is that that's not crazy hard to do -- there is a uniform notion of time here. We'd just need to plumb the timestamp corresponding to the value into the settings container and then wait for it to take on the correct value at a timestamp greater than or equal to the timestamp at which the setting was written.

**Comment by michae2** [comment] 2022-09-06 19:44
@HonoreDB regarding the linked test, do we need this blocking behavior from `SET CLUSTER SETTING security.ocsp.mode` or is this only needed for testing?

**Comment by ajwerner** [comment] 2022-09-06 19:47
I'd say this is something of an edge case we can document away, and is primarily painful only for testing.

**Comment by michae2** [comment] 2022-09-06 21:20
I guess we do [document](https://www.cockroachlabs.com/docs/v22.1/cluster-settings.html#change-a-cluster-setting) this already:

> Changing a cluster setting is not instantaneous, as the change must be propagated to other nodes in the cluster.

Closing.

**Closed by michae2** 2022-09-06 21:20 UTC
Labels: C-bug, docs-known-limitation, T-sql-schema, T-sql-queries

**Comment by ajwerner** [comment] 2022-09-08 04:09
I did something about this here: https://github.com/cockroachdb/cockroach/pull/87564.
