### ISSUE TITLE
stress: failed test in cockroach/cli/cli.test: TestNoLinkForbidden

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6522] opened 2016-05-05 11:42 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/9dc275b7bc4447f18538c2398083fb6bb88a4e27

Stress build found a failed test:

```
=== RUN   TestNoLinkForbidden
--- FAIL: TestNoLinkForbidden (0.00s)
	build.go:69: cannot find package "github.com/cockroachdb/cockroach" in any of:
			/usr/local/go/src/github.com/cockroachdb/cockroach (from $GOROOT)
			($GOPATH not set)
```

Run Details:

```
0 runs so far, 0 failures, over 5s
1 runs completed, 1 failures, over 6s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-05 22:29
Duplicate of #6488

**Closed by bdarnell** 2016-05-05 22:29 UTC
Labels: Robot, test-failure
