### ISSUE TITLE
0A000 unimplemented

### ISSUE THREAD

**Issue by 1N50MN14** [cockroachdb/cockroach#29972] opened 2018-09-08 16:56 UTC
Is this a bug report or a feature request?
Not sure.

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
2.0.5

- What did you do?
Multi row update on a table with `id` (Primary Key) and `data` (JSONB Inverted Index) columns using pgs compatible query (node-postgress):

```javascript
UPDATE "profiles" AS t SET "data"=v."data" FROM (VALUES('66083a02-acbf-4681-a541-093d94201d30','{"firstname":"24fu9yve5j47oacq2ct5of","lastname":"6o72avicweody0yajxrfpo","gender":"F","birthdate":"1979-10-01T04:51:51.803Z","_updated":"2018-09-08T16:41:19.113Z"}')) AS v("id","data") WHERE v.id = t.id
```
- What did you expect to see?
Successful execution.

- What did you see instead?
An error message  `unimplemented at or near "where"` (code `0A000`)

- What was the impact?
I took a shot of tequila. I can alternatively batch all updates, wondering whether the above query syntax is not implemented as the error states (if so, any plans to support it) or if I did something wrong in there. 

**FEATURE REQUEST**
If the above is indeed not a bug, kindly consider this issue a feature request.

Thank you!

**Comment by knz** [comment] 2018-09-08 17:09
Thank you for your report!

This is a duplicate of issue #7841.

**Closed by knz** 2018-09-08 17:09 UTC
Labels: X-duplicate
