### ISSUE TITLE
sql: EXPLAIN(PLAN) for scanNode does not display DECIMAL boundaries in key ranges properly

### ISSUE THREAD

**Issue by sploiselle** [cockroachdb/cockroach#7215] opened 2016-06-14 14:42 UTC
#### Logs

```
I160612 20:42:46.472556 util/log/clog.go:998  [config] file created at: 2016/06/12 20:42:46
I160612 20:42:46.472556 util/log/clog.go:998  [config] running on machine: crdb1
I160612 20:42:46.472556 util/log/clog.go:998  [config] binary: CockroachDB beta-20160609 (linux amd64, built 2016/06/09 16:31:43, go1.6.2)
I160612 20:42:46.472556 util/log/clog.go:998  [config] arguments: [cockroach start]
```
#### Description
- What did you do?

```
CREATE TABLE t (decimalCol DECIMAL);
CREATE INDEX decimalIndex ON t (decimalCol);
EXPLAIN SELECT decimalCol FROM t WHERE decimalCol>10;
```
- What did you expect to see?

```
+-------+------+---------------------------+
| Level | Type |        Description        |
+-------+------+---------------------------+
|     0 | scan | t@decimalIndex /10.001 -  |
+-------+------+---------------------------+
```
- What did you see instead?

```
+-------+------+------------------------------------------------------------------------------------------------+
| Level | Type |                                          Description                                           |
+-------+------+------------------------------------------------------------------------------------------------+
|     0 | scan | t@decimalIndex /<util/encoding/decimal.go:395: did not find terminator 0x0 in buffer 0x1401>-  |
+-------+------+------------------------------------------------------------------------------------------------+
```

I have a little more detail available in [this Gist](https://gist.github.com/sploiselle/a66de3daa0260ff9434e40201bb41f5f)

**Comment by knz** [comment] 2016-06-14 14:56
cc @nvanbenschoten

**Comment by nvanbenschoten** [comment] 2016-06-14 16:21
Hi Sean, thanks for the bug report. The problem described here has been noted before (by @andreimatei) and is not unique to `DECIMAL` encodings. The issue is an artifact of how we handle index selection for Datum types which do not have logical next values during the encoding of inclusive span constraints. Because spans require exclusive end keys, we would like to take the inclusive value and turn it into an exclusive value by getting "the next logical value". For instance, for an `INT` between (and including) `[0, 5]`, we would add `1` to the inclusive end value to get `[0, 6)`. 

In cases where encoding a logical next value is not possible (like with `DECIMAL`s, whose precision is arbitrary), we instead resort to using the next logical encoded byte value as the span constraint (see the use of `PrefixEnd` in https://github.com/cockroachdb/cockroach/blob/master/sql/index_selection.go). This all works correctly for index selection, but it means that pretty printing these artificial keys will not produce valid Datum values because the key values have been brought out of bounds. Last time @andreimatei and I discussed this, we decided it wasn't a large enough concern to worry about for now. That said, we may want to at least improve the error reporting in these cases.

**Comment by sploiselle** [comment] 2016-06-14 19:19
@nvanbenschoten Got it. Thank you! I was able to pull together what I needed by simply using a defined bound with >=.

**Comment by petermattis** [comment] 2017-02-22 15:50
@nvanbenschoten I believe you just fixed something in this area.

**Comment by nvanbenschoten** [comment] 2017-02-22 15:57
Closing in favor of #13412.

**Closed by nvanbenschoten** 2017-02-22 15:57 UTC
Labels: enhancement
