### ISSUE TITLE
sentry: conn_executor.go:643: panic while executing 1 statements: SELECT _._, _._, _._, _._, _._, _._, _._, _._, _._, _._, COALESCE(json_agg(json_build_object(_, _._, _, _._, _, _._, _, _._))) AS _ FROM _ AS _ INNER JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) INNER JOIN _ AS _ ON _._ = _._ WHERE ((_._ = $1) AND (_._ = $2)) GROUP BY _._, _._, _._, _._, _._, _._, _._, _._, _._, _._ ORDER BY _._ ASC: caused by <redacted>

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#33179] opened 2018-12-15 16:10 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/809089873/?referrer=webhooks_plugin

conn_executor.go:643: panic while executing 1 statements: SELECT _._, _._, _._, _._, _._, _._, _._, _._, _._, _._, COALESCE(json_agg(json_build_object(_, _._, _, _._, _, _._, _, _._))) AS _ FROM _ AS _ INNER JOIN _ AS _ ON (_._ = _._) AND (_._ = _._) INNER JOIN _ AS _ ON _._ = _._ WHERE ((_._ = $1) AND (_._ = $2)) GROUP BY _._, _._, _._, _._, _._, _._, _._, _._, _._, _._ ORDER BY _._ ASC: caused by <redacted>

github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1

```
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 387
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in convertOrdering at line 935
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForLookupJoin at line 1918
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2273
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForLookupJoin at line 1844
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2273
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2279
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2289
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2279
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2299
github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go in createPlanForNode at line 2279
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 752
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 982
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 824
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 402
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 96
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1173
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 389
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func4 at line 313
```

**Comment by jordanlewis** [comment] 2018-12-15 21:34
```
        for i, o := range props.ordering {
                streamColIdx := o.ColIdx
                if planToStreamColMap != nil {
                        streamColIdx = planToStreamColMap[o.ColIdx]
                }
```

`o.ColIdx` must have been missing from `planToStreamColMap`.

**Comment by jordanlewis** [comment] 2018-12-28 19:18
Closing this as a dupe of #33343 which has a better report.

**Closed by jordanlewis** 2018-12-28 19:18 UTC
Labels: C-bug, O-sentry, V-2.1.2
