### ISSUE TITLE
sql: internal error executing values clause with record types

### ISSUE THREAD

**Issue by rharding6373** [cockroachdb/cockroach#105669] opened 2023-06-27 21:42 UTC
When a `VALUES` clause lists `RECORD` types and includes an empty and non-empty tuple, the type resolution results in an error during execution: 

```
SELECT * FROM (VALUES (('hello'::STRING,)::RECORD),(()));

ERROR: internal error: invalid datum type given: tuple{string}, expected tuple
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/rowenc/encoded_datum.go:195: DatumToEncDatum()
github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:227: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/columnarizer.go:239: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:118: next()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/stats.go:126: Next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:250: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:254: next()
github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:286: Run()
github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:317: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1913: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1645: func3()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1648: PlanAndRunAll()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2096: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1656: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:964: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2984: execWithProfiling()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2171: func1()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2176: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2093: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:903: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310: func1()
GOROOT/src/runtime/asm_amd64.s:1594: goexit()

HINT: You have encountered an unexpected error.

```

We don't see an error if all values are non-empty:
```
SELECT * FROM (VALUES (('hello'::STRING,)::RECORD),((1,)::RECORD));                                  
  column1
-----------
  (hello)
  (1)
```

Or if we explicitly cast the empty tuple to `RECORD:
```
SELECT * FROM (VALUES (('hello':::STRING,)::RECORD),(()::record));                                    
  column1
-----------
  (hello)
  ()

```

Jira issue: CRDB-29145

**Comment by rharding6373** [comment] 2023-06-28 19:46
@mgartner and I were looking at similar examples in postgres to compare behavior. The closest to the original example we've found is:

```
SELECT * FROM (VALUES (('hello'::text,1)::RECORD),(row()::record)) AS foo;
  column1  
-----------
 (hello,1)
 ()
```

We also verified that postgres supports VALUES clauses with records that have different underlying types that cannot be implicitly cast:

```
select * from (values ((true::bool,1)::RECORD), ((1::int,1)::RECORD)) as foo;
 column1 
---------
 (t,1)
 (1,1)
(2 rows)

select * from (values ((true::bool,1)), ((1::int,1))) as foo;
 column1 
---------
 (t,1)
 (1,1)
```

**Comment by DrewKimball** [comment] 2024-07-15 09:23
Dupe of #117101

**Closed by DrewKimball** 2024-07-15 09:23 UTC
Labels: C-bug, T-sql-queries
