### ISSUE TITLE
logictest: SQLite Logic Test High VModule Nightly fails due to test output parsing error

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#50136] opened 2020-06-12 06:31 UTC
SQLite Logic Test High VModule Nightly has been failing for a while now (e.g. https://teamcity.cockroachdb.com/viewLog.html?buildId=2003283&buildTypeId=Cockroach_Nightlies_SqlLogicTestHighVModuleNightly&tab=buildLog&branch_Cockroach_Nightlies=%3Cdefault%3E) due to what appears to be a test output parsing error:
```
360381 [16:57:08]W:                     [run] not a single test was parsed, but detected test output:  -- XFAIL;^M
360382 [16:57:08] :             [Run TestLogic tests under verbose] post issues^M
360383 [16:57:08]W:             [Run TestLogic tests under verbose] artifacts^M
360384 [16:57:08]W:                     [artifacts] not a single test was parsed, but detected test output:    -- XFAIL;^M                                                                                  
360385 [16:57:08]W:                     [artifacts] Process exited with code 1^M
```

@tbg I wonder whether from a quick glance you can tell what could be wrong.

**Comment by tbg** [comment] 2020-06-12 07:20
I think the test isn't using JSON output when it should be. You need to pass `GOTESTFLAGS=json` to the `make test` invocation. I didn't migrate this when I did the work to do so because the build step isn't checked in - maybe take the opportunity to load it from the repo at `./build/teamcity-<something>`. Then it can also use all the helpers available to those scripts.

**Comment by yuzefovich** [comment] 2020-06-17 21:56
It turns out that there is `build/teamcity-testlogic-verbose.sh` file checked in which does have `GOTESTFLAGS=-json` set.

Interestingly, this test fails only on `20.1` and `master` branches but succeeds on the older ones. I looked at an arbitrary output from the run on 20.1 and it seems to be the same - I don't see any failures, but the test is failed due to `not a single test was parsed, but detected test output`.

@tbg do you have a bandwidth to take a more close look at this? If not, I think we have a test infra community service team, and this issue might be a good one for them to tackle.

**Comment by tbg** [comment] 2020-06-18 09:07
No, I don't have bandwidth to fix this, but I did look into the problem. It's basically this line:

https://github.com/cockroachdb/cockroach/blob/27cd4c39c66b66639fa42d2abbdbaa09d72c4e67/Makefile#L1079

We build the binary first and then invoke it manually. The problem is that there is no way to emit json in that case (you'd have to pipe into ` | go tool test2json`, but that has limitations since `go tool test2json` does not see the exit status of the test binary).

I would strongly advise to set this up without invoking the binary manually, in which case everything will "just work". The cheap alternative is to switch to `run_text_test` in the script (see `teamcity-acceptance.sh` for an example), but this has the limitations mentioned above (i.e. it won't fail very gracefully when -test.timeout gets exceeded).

It is unfortunate that there isn't a `-test.json` flag, otherwise we could have fixed this rather easily.

> If not, I think we have a test infra community service team, and this issue might be a good one for them to tackle

In this particular case, my preference would be for someone on the SQL teams to get this straightened out since this is all bespoke SQL testing. I understand the hesitation to get involved with the Makefile, but there is a well-defined way to get this all to work, which is to invoke the test directly. Folks on the test-infra team don't know this stuff any better.

**Comment by jordanlewis** [comment] 2020-07-15 16:25
We've decided this should be owned by the execution team, because it doesn't fit within the standard testing pattern we use.

**Closed** 2020-09-21 12:30 UTC
Labels: C-test-failure
