### ISSUE TITLE
rpc: TestRemoteOffsetUnhealthy is flaky

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#116002] opened 2023-12-11 02:17 UTC
```
Failed
=== RUN   TestRemoteOffsetUnhealthy
I231209 01:31:06.300564 439 2@rpc/peer.go:527  [rnode=2,raddr=127.0.0.1:33581,class=default,rpc] 19  connection is now healthy
I231209 01:31:06.307581 456 2@rpc/peer.go:527  [rnode=3,raddr=127.0.0.1:38671,class=default,rpc] 20  connection is now healthy
I231209 01:31:06.314528 423 2@rpc/peer.go:527  [rnode=4,raddr=127.0.0.1:42411,class=default,rpc] 21  connection is now healthy
I231209 01:31:06.322039 486 2@rpc/peer.go:527  [rnode=1,raddr=127.0.0.1:46337,class=default,rpc] 22  connection is now healthy
I231209 01:31:06.329132 467 2@rpc/peer.go:527  [rnode=3,raddr=127.0.0.1:38671,class=default,rpc] 23  connection is now healthy
I231209 01:31:06.353446 96 2@rpc/peer.go:527  [rnode=4,raddr=127.0.0.1:42411,class=default,rpc] 24  connection is now healthy
    context_test.go:1172: initial connection heartbeat failed: operation "conn heartbeat" timed out after 117ms (given timeout 100ms): grpc: context deadline exceeded [code 4/DeadlineExceeded]
E231209 01:31:06.472593 445 2@rpc/peer.go:601  [rnode=1,raddr=127.0.0.1:46337,class=default,rpc] 25  failed connection attempt (last connected 0s ago): operation "conn heartbeat" timed out after 117ms (given timeout 100ms): grpc: context deadline exceeded [code 4/DeadlineExceeded]
--- FAIL: TestRemoteOffsetUnhealthy (0.19s)
```

https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/13055561?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true

Jira issue: CRDB-34370

**Comment by nvanbenschoten** [comment] 2024-01-16 16:20
Closing as duplicate of https://github.com/cockroachdb/cockroach/issues/116898.

**Closed by nvanbenschoten** 2024-01-16 16:20 UTC
Labels: C-bug, C-test-failure, A-testing, T-kv, no-test-failure-activity, P-3
