### ISSUE TITLE
demo: console doesn't load for multitenant demo cluster

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#95367] opened 2023-01-17 16:59 UTC
```
cockroach demo
```
Click on the link to log into the console. The home page only partially loads, and you see this in the Chrome Console:
```
Failed to load resource: the server responded with a status of 501 (Not Implemented)     :8080/_admin/v1/liveness:1 
Failed to load resource: the server responded with a status of 501 (Not Implemented)     :8080/_status/nodes_ui:1 
GET http://127.0.0.1:8080/_status/nodes_ui 501 (Not Implemented)
```

Running with `--multitenant=false` seems to work.

Also see #95366.

cc @knz 

Jira issue: CRDB-23487

**Comment by dhartunian** [comment] 2023-01-17 17:23
This is a known issue of DB Console support on tenants that is fixed by https://github.com/cockroachdb/cockroach/pull/94968 that's currently on its way through bors.

This was caused by poor ordering of change between demo and the server endpoints, making the tenant UI default before it was really ready.

**Closed by dhartunian** 2023-01-17 17:23 UTC
Labels: C-bug, A-demo, A-multitenancy, T-multitenant

**Comment by dhartunian** [comment] 2023-01-17 17:25
I will amend the server to delete the cookie when a nonsensical tenant is requested.
