### ISSUE TITLE
'DISCARD ALL' performance regression on v22.2

### ISSUE THREAD

**Issue by JeffSwenson** [cockroachdb/cockroach#95864] opened 2023-01-25 21:04 UTC
**Describe the problem**

DISCARD ALL is more expensive to execute on v22.2.2 when compared to v22.1.11. Some Serverless clients appear to run DISCARD ALL when a connection is returned to the connection pool. The extra overhead causes a noticeable load increase in lightly loaded clusters that are serving mostly health checks. It also increases the overhead of each operation using the pool. See https://cockroachlabs.atlassian.net/browse/CC-9132 for context.

**To Reproduce**

Connect to a v22.2 cluster and run SHOW DISCARD. The execution will take 5-30ms. On v22.1, it consistently took <1 ms.

I ran SHOW DISCARD with tracing enabled on v22.2.2 and v22.1.11.

```
# v22.2.2
jeff@sprobe-3284.6h5c.crdb.io:26257/sprobe> SHOW CLUSTER SETTING version;
  version
-----------
  22.2
(1 row)


Time: 42ms total (execution 3ms / network 39ms)

jeff@sprobe-3284.6h5c.crdb.io:26257/sprobe> SET tracing = 'on'
                                         -> ;
SET TRACING


Time: 37ms total (execution 0ms / network 37ms)

jeff@sprobe-3284.6h5c.crdb.io:26257/sprobe> DISCARD ALL;
NOTICE: datestyle_enabled no longer has any effect
NOTICE: experimental_enable_hash_sharded_indexes no longer has any effect
NOTICE: intervalstyle_enabled no longer has any effect
NOTICE: enable_drop_enum_value no longer has any effect
DISCARD ALL


Time: 54ms total (execution 14ms / network 39ms)

jeff@sprobe-3284.6h5c.crdb.io:26257/sprobe> SHOW COMPACT KV TRACE FOR SESSION;
        age       |                                                                                                                 message                                                                                                                 |                                               tag                                                |    operation
------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------+-------------------
  00:00:00.118497 | sql/conn_executor_exec.go:697 rows affected: 1                                                                                                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff]                                 | sql query
  00:00:02.553212 | sql/row/kv_batch_fetcher.go:406 Scan /Tenant/3284/Table/4/1/"jeff"{-/PrefixEnd}                                                                                                                                                         | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,intExec=read-users]              | colbatchscan
  00:00:02.553337 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/4/1/"jeff"                                                                                                                                              | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,intExec=read-users,txn=264e72ec] | dist sender send
  00:00:02.553387 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/4/1/"jeff", desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0]                                     | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,intExec=read-users,txn=264e72ec] | dist sender send
  00:00:02.553423 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Scan to (n1,s1):1                                                                                                                                                       | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,intExec=read-users,txn=264e72ec] | dist sender send
  00:00:02.555214 | sql/conn_executor_exec.go:697 rows affected: 1                                                                                                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,intExec=read-users]              | sql query
  00:00:02.555896 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/0/0                                                                                                                                                | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.555949 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/0/0, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0]                                       | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.55598  | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Scan to (n1,s1):1                                                                                                                                                       | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.557178 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/3/1/100/2/1                                                                                                                                             | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.557221 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/3/1/100/2/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0]                                    | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.557244 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 4 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.558796 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/3/1/101/2/1                                                                                                                                             | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.55884  | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/3/1/101/2/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0]                                    | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.558863 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 4 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.560559 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/100/0/"pg_temp_1674680085229196954_2"/4/1                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.560625 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/100/0/"pg_temp_1674680085229196954_2"/4/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0] | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.560646 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.561551 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/102/0/"pg_temp_1674680085229196954_2"/4/1                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.561593 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/102/0/"pg_temp_1674680085229196954_2"/4/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0] | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.561613 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.56246  | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/124/0/"pg_temp_1674680085229196954_2"/4/1                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.562501 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/124/0/"pg_temp_1674680085229196954_2"/4/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0] | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.562521 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.563434 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/104/0/"pg_temp_1674680085229196954_2"/4/1                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.563481 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/104/0/"pg_temp_1674680085229196954_2"/4/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0] | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.563505 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.564333 | kv/kvclient/kvcoord/range_iter.go:183 querying next range at /Tenant/3284/Table/30/1/1/0/"pg_temp_1674680085229196954_2"/4/1                                                                                                            | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.564374 | kv/kvclient/kvcoord/range_iter.go:216 key: /Tenant/3284/Table/30/1/1/0/"pg_temp_1674680085229196954_2"/4/1, desc: r10290:/Tenant/3284{-/Table/106} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=3361, sticky=1669765149.511403611,0]   | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.564394 | kv/kvclient/kvcoord/dist_sender.go:2046 r10290: sending batch 1 Get to (n1,s1):1                                                                                                                                                        | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff,txn=264e72ec]                    | dist sender send
  00:00:02.565443 | sql/conn_executor_exec.go:697 rows affected: 0                                                                                                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff]                                 | sql query
  00:00:02.720143 | sql/conn_executor_exec.go:697 rows affected: 1                                                                                                                                                                                          | [nsql2,peer=10.0.3.57:55876,client=71.190.30.48:51536,user=jeff]                                 | sql query
```

```
# v22.1.11
jeff@long-herder-3.jeffsw-883z.crdb.io:26257/defaultdb> SHOW CLUSTER SETTING version;
  version
-----------
  22.1
(1 row)


Time: 39ms total (execution 2ms / network 37ms)

jeff@long-herder-3.jeffsw-883z.crdb.io:26257/defaultdb> SET tracing = 'on';
SET TRACING


Time: 37ms total (execution 0ms / network 37ms)

jeff@long-herder-3.jeffsw-883z.crdb.io:26257/defaultdb> DISCARD ALL;
DISCARD


Time: 40ms total (execution 1ms / network 39ms)

jeff@long-herder-3.jeffsw-883z.crdb.io:26257/defaultdb> SHOW COMPACT KV TRACE FOR SESSION;
        age       |                    message                     |                               tag                                | operation
------------------+------------------------------------------------+------------------------------------------------------------------+------------
  00:00:00.107343 | sql/conn_executor_exec.go:747 rows affected: 1 | [nsql1,peer=10.0.2.13:54784,client=71.190.30.48:52433,user=jeff] | sql query
  00:00:04.403253 | sql/conn_executor_exec.go:747 rows affected: 0 | [nsql1,peer=10.0.2.13:54784,client=71.190.30.48:52433,user=jeff] | sql query
  00:00:04.521179 | sql/conn_executor_exec.go:747 rows affected: 1 | [nsql1,peer=10.0.2.13:54784,client=71.190.30.48:52433,user=jeff] | sql query
(3 rows)

```

Jira issue: CRDB-23779

**Comment by ajwerner** [comment] 2023-01-25 22:01
The root cause is https://github.com/cockroachdb/cockroach/pull/86246. This code should consult in-memory data structures to determine what work there is to do and then should act accordingly.

**Comment by JeffSwenson** [comment] 2023-01-25 22:29
Running `DISCARD ALL` after a connection is returned appears to be the default behavior for pg bouncer: https://www.pgbouncer.org/config.html#connection-sanity-checks-timeouts

**Comment by ajwerner** [comment] 2023-01-26 22:09
Re-opening until the backport merges.

**Comment by ajwerner** [comment] 2023-01-27 18:47
Fixed by https://github.com/cockroachdb/cockroach/pull/96102.

**Closed by ajwerner** 2023-01-27 18:47 UTC
Labels: C-bug, T-sql-sessions
