### ISSUE TITLE
sqlproxyccl: flake in TestCurConnCountMetric

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#108477] opened 2023-08-09 20:19 UTC
Seen on unrelated PR [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=11254659&buildTypeId=Cockroach_BazelEssentialCi)

```
=== RUN   TestCurConnCountMetric
    test_log_scope.go:167: test logs captured to: /artifacts/tmp/_tmp/a455c59caed0cf9d0a0298ad88bfe7a2/logTestCurConnCountMetric1490050169
    test_log_scope.go:81: use -show-logs to present logs inline
    proxy_handler_test.go:2459: -- test log scope end --
panic: test timed out after 4m55s

goroutine 118877 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```

Jira issue: CRDB-30487

**Comment by JeffSwenson** [comment] 2023-08-21 14:11
The last 1k runs in CI were green: 
<img width="1267" alt="image" src="https://github.com/cockroachdb/cockroach/assets/5283435/2e8afba1-edec-455a-8cba-07b392b9d92f">

The last time this test flaked it was caused by random issue in the sql server: https://github.com/cockroachdb/cockroach/issues/83690.

**Comment by JeffSwenson** [comment] 2023-08-21 17:48
I ran this 10k times on master and 5k times on the base commit for the PR that experienced the flake. So far I have been unable to reproduce it.

```
./dev test pkg/ccl/sqlproxyccl --filter=TestCurConnCountMetric --stress --count 10000
```

**Comment by JeffSwenson** [comment] 2023-08-21 18:53
I tried reproducing this with stress+oversubscription. 1K runs were green. 

```
bazel test --local_cpu_resources=100 pkg/ccl/sqlproxyccl:all --test_env=GOTRACEBACK=all --test_env=COCKROACH_STRESS=true --notest_keep_going --test_filter=TestCurConnCountMetric --runs_per_test=1000 --test_sharding_strategy=disabled --test_output errors --jobs=48
```

I'm going to close this as not reproducible. There was an issue with TC configuration last week that may have been the root case (internal slack: https://cockroachlabs.slack.com/archives/C016CAD2HQ8/p1692642502088029).

**Closed by JeffSwenson** 2023-08-21 18:53 UTC
Labels: C-test-failure, T-serverless
