### ISSUE TITLE
ui: revisit UX for showing jobs progress

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#17946] opened 2017-08-27 19:13 UTC
Noticed this when loading tpcc data

![image](https://user-images.githubusercontent.com/894257/29753176-a0943f92-8b39-11e7-8c16-2d630fbfca92.png)

We should double check the actual UX for showing progress in the jobs table. The progress bar hangs for long periods of time (how often do we check for an updated completion estimate? seems like minutes between any update) and in general feels very static. Is there something from a design (and potentially eng) point of view we can do to show work is actually happening?

# cockroach version
Build Tag:    798df64
Build Time:   2017/08/21 15:05:23
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.3
C Compiler:   gcc 6.3.0
Build SHA-1:  798df647566b6bd5391f533f865d2e85bc756ca8
Build Type:   release-gnu

**Comment by nstewart** [comment] 2017-08-27 19:14
cc @kuanluo

**Comment by dianasaur323** [comment] 2017-08-27 19:22
Yes, I noticed this as well when I was testing, but wasn't able to reproduce. I think it might have something to do with this fix? https://github.com/cockroachdb/cockroach/pull/17927 

@benesch do you mind sharing your thoughts on if this will still be an issue after our latest master? Perhaps we should test it again. My understand is that the progress is being updated every 10 sec.

cc @jordanlewis since he was helping me look at the delay in progress updates on schema changes a while back, but we were unable to reproduce.

**Comment by benesch** [comment] 2017-08-28 19:20
Yeah, you should see a progress update every few seconds. Not sure we'll be able to do anything about this for 1.1; there are some critical performance/stability problems with restore that we need to fix first.

**Comment by dianasaur323** [comment] 2017-08-29 17:22
Ok, let's move this into 1.2, but keep that other jobs table related issue in 1.1 in case you have time. This one seems like a larger issue that we might not have time to address.

**Comment by dianasaur323** [comment] 2017-10-24 15:16
I re-ran this, and it looks like it hasn't been freezing up anymore. It won't be second-to-second responsive, since the admin UI isn't updating that quickly. The import csv problem is being worked on in terms of being able to track progress, and you should now be able to see 1/3, 2/3, and 3/3 process once our fixes go in. Closing this out for now, and will test import csv again later in the release cycle.

**Closed by dianasaur323** 2017-10-24 15:16 UTC
Labels: bulkio
