### ISSUE TITLE
Support for CREATE USER statement

### ISSUE THREAD

**Issue by tlvenn** [cockroachdb/cockroach#9999] opened 2016-10-15 01:13 UTC
Hi,

Unless I am missing something, it does not look like that `CREATE USER` statement is handled at the moment but users seems to be implicitly created when using `GRANT`.

Use case would be to support Vault Postgresql Backend

> https://www.vaultproject.io/docs/secrets/postgresql/

Of interest, Vault is leveraging the `VALID UNTIL` option in the statement.

**Comment by andreimatei** [comment] 2016-10-15 01:24
As it just so happens, `CREATE USER` is coming: https://github.com/cockroachdb/cockroach/pull/9794

cc @asubiotto for `VALID UNTIL`. Don't know if there's plans for that.

**Comment by asubiotto** [comment] 2016-10-15 17:36
There aren't any plans for ```VALID UNTIL``` yet but it will be something to look at as we discuss the topic of users/roles further.

**Comment by tlvenn** [comment] 2016-12-22 05:12
Would it be harmful to parse properly VALID UNTIL and noop on it for now, may be emitting a warning ? In Vault case, it should be fine, because it has its own revocation system but if someone rely entirely on the DB to revoke, then it's definitely a problem...

**Comment by asubiotto** [comment] 2017-01-10 16:02
Sorry for the late response. Yes, I think that it would be a problem for uses of an unimplemented feature to not error out and not provide expected behavior. I will keep you posted if there are any developments regarding `VALID UNTIL`.

Closing this issue because support for `CREATE USER` was added in #9794.

**Closed by asubiotto** 2017-01-10 16:02 UTC
