### ISSUE TITLE
stability: rho failed on inconsistency

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#12130] opened 2016-12-07 14:18 UTC
sha: 677f6f1 with race-detection enabled.

`rho` nodes all died within 24h
timeline:
```
0: cockroach@104.196.18.63
cockroach                        EXITED     Dec 06 01:45 AM
1: cockroach@104.196.102.49
cockroach                        EXITED     Dec 05 08:24 PM
2: cockroach@104.196.147.189
cockroach                        EXITED     Dec 05 07:58 PM
3: cockroach@104.196.164.29
cockroach                        EXITED     Dec 05 05:11 PM
```

three of the nodes died with the previously-seen "panic during panic", unique to race builds.
However, another (`104.196.147.189`) died with inconsistencies:
```
I161205 19:58:51.854693 58 storage/replica_proposal.go:404  [n3,s3,r2059/2:/Table/51/1/4{399621â<80>¦-404032â<80>¦},@c42cf38480] range [n3,s3,r2059/2:/Table/51/1/4{399621â<80>¦-404032â<80>¦}]: transferring raft leadership to replica ID 4
E161205 19:58:52.125690 65010180 storage/replica_command.go:1877  [n3,s3,r1618/4:/Table/51/1/352{09637â<80>¦-54308â<80>¦},@c42c1ffb00] replica {2 2 2} is inconsistent: expected checksum c1b4ffa6c5b3078da8b8a2632ab40cdf8e7362f2eac201dbb122100e569ad644374b964ab1ce71e9dad90614a863366c24d7d3762591d2b8e4bfec1e45ad05fb, got c86ca26b9f66abe6c4b92c21f0fb37b4cd55d96832577745715f648f8d1fd17d67d7f96bbd7f96206e6c3055308d59e7c33767261f1fcc518ee66f35e2143a33
--- leaseholder
+++ follower
-0.000000000,0 /Local/RangeID/1618/r/RaftTombstone
-  ts:<zero>
-  value:^R^D^H^@^P^@^X^@ ^@(^@2^Gúü 7^C^H^E
-  raw_key:/Local/RangeID/1618/r/RaftTombstone raw_value:1204080010001800200028003207fafca037030805
E161205 19:58:52.126742 65010179 storage/replica_command.go:1877  [n3,s3,r1618/4:/Table/51/1/352{09637â<80>¦-54308â<80>¦},@c42c1ffb00] replica {1 1 1} is inconsistent: expected checksum c1b4ffa6c5b3078da8b8a2632ab40cdf8e7362f2eac201dbb122100e569ad644374b964ab1ce71e9dad90614a863366c24d7d3762591d2b8e4bfec1e45ad05fb, got c86ca26b9f66abe6c4b92c21f0fb37b4cd55d96832577745715f648f8d1fd17d67d7f96bbd7f96206e6c3055308d59e7c33767261f1fcc518ee66f35e2143a33
--- leaseholder
+++ follower
-0.000000000,0 /Local/RangeID/1618/r/RaftTombstone
-  ts:<zero>
-  value:^R^D^H^@^P^@^X^@ ^@(^@2^Gúü 7^C^H^E
-  raw_key:/Local/RangeID/1618/r/RaftTombstone raw_value:1204080010001800200028003207fafca037030805
F161205 19:58:52.127938 65009868 storage/replica_command.go:1893  [n3,s3,r1618/4:/Table/51/1/352{09637â<80>¦-54308â<80>¦},@c42c1ffb00] consistency check failed with 2 inconsistent replicas
goroutine 65009868 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x3d04a01, 0x7a030ec, 0x332fc60, 0x10b39ba)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:849 +0xc2
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x3331260, 0xc400000004, 0x2b252d2, 0x1a, 0x765, 0xc42ce3c700, 0x74)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:714 +0x99a
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x2e74900, 0xc4287704b0, 0x4, 0x2, 0x2056512, 0x36, 0xc4203f4000, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:140 +0x331
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x2e74900, 0xc4287704b0, 0x1, 0x4, 0x2056512, 0x36, 0xc4203f4000, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x9a
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x2e74900, 0xc4287704b0, 0x2056512, 0x36, 0xc4203f4000, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x90
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc42c1ffb00, 0x2e74900, 0xc4287704b0, 0xc426cf98c0, 0x36, 0x40, 0xc426cf9b40, 0x36, 0x40, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1893 +0xc8c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addAdminCmd(0xc42c1ffb00, 0x2e74900, 0xc4287704b0, 0x148d747b3c31d98f, 0x0, 0x300000003, 0x4, 0x652, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1635 +0x4a5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc42c1ffb00, 0x2e74900, 0xc4287704b0, 0x148d747b3c31d98f, 0x0, 0x300000003, 0x4, 0x652, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1221 +0x7a5
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420191880, 0x2e74900, 0xc4287704b0, 0x148d747b3c31d98f, 0x0, 0x300000003, 0x4, 0x652, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2446 +0x913
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4202a0cc0, 0x2e74900, 0xc4287704b0, 0x0, 0x0, 0x300000003, 0x4, 0x652, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x24b
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:818 +0x433
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc4203ac000, 0xc42bb67cc0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x10e
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc420210500, 0x2e74840, 0xc42cb94340, 0xc423bbcac8, 0xc42cb94340, 0xc42a7b4880, 0xc420d9cf00)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:829 +0x210
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc420210500, 0x2e74840, 0xc42cb94340, 0xc423bbcac8, 0x2e7dba0, 0xc42a67da80, 0x11)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:851 +0xbf
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0x2e5cbc0, 0xc420210500, 0xc42b31ebe0, 0xc423bbcaa0, 0xc4298dc4e0)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:185 +0x86
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:188 +0x3c3
```

Not sure how much effort we want to put into debugging `rho`, race-detection causes some odd things.
Silencing alerts for a bit.

**Comment by bdarnell** [comment] 2016-12-07 14:32
Race detection causes some odd things, but it shouldn't cause inconsistencies, so I think this is worth investigating. We also have an inconsistency on delta (#11191) which we haven't been able to explain.

That said, I think this is different from #11191. That issue affected normal data; this one only affects raft tombstones. Those keys are incorrectly marked as replicated so the consistency checker is verifying them, but they're supposed to be deleted whenever there is actual data. It may just be a timing thing that has prevented the tombstones from being either written or cleaned up at the right time.

**Comment by mberhault** [comment] 2016-12-07 14:40
similar problem on delta, single node (`104.196.191.196`) on sha 0d2ec04 died with:
```
E161207 09:18:20.700863 153442556 storage/replica_command.go:1877  [n1,s2,r7204/3:/Table/51/1/8{099277â<80>¦-100398â<80>¦},@c420f80480] replica {9 17 4} is inconsistent: expected checksum ffde07ad189d84685a288f1868e91d981f8127962e124da2b1a6cc395d82d58cd1ade3f21515e5e548a7b3b587ea8823ea38faa5025519a6c46fdcef965d6d10, got 5984e2d6af27791365081bff5a341a72c7eeec6394c79fa7155ece831f346955147cadb0fae5d847aa58d950f674115a04130ff6aac8340adfddd6ef797c369c
--- leaseholder
+++ follower
+0.000000000,0 /Local/RangeID/7204/r/RaftTombstone
+  ts:<zero>
+  value:^R^D^H^@^P^@^X^@ ^@(^@2^GIÉ^KI^C^H^E
+  raw_key:/Local/RangeID/7204/r/RaftTombstone raw_value:120408001000180020002800320749c90b49030805
F161207 09:18:20.701782 153431182 storage/replica_command.go:1893  [n1,s2,r7204/3:/Table/51/1/8{099277â<80>¦-100398â<80>¦},@c420f80480] consistency check failed with 1 inconsistent replicas
goroutine 153431182 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x9252c01, 0x29d45b42, 0x2a44a20, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:849 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2a46020, 0xc400000004, 0x22451b2, 0x1a, 0x765, 0xc436561200, 0x74)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:714 +0x7b1
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f89f141d040, 0xc430520750, 0x4, 0x2, 0x19fbfcc, 0x36, 0xc42f002ad0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f89f141d040, 0xc430520750, 0x1, 0x4, 0x19fbfcc, 0x36, 0xc42f002ad0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f89f141d040, 0xc430520750, 0x19fbfcc, 0x36, 0xc42f002ad0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).CheckConsistency(0xc420f80480, 0x7f89f141d040, 0xc430520750, 0xc4211e2ac0, 0x36, 0x40, 0xc4211e2b00, 0x36, 0x40, 0x1, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1893 +0x65c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addAdminCmd(0xc420f80480, 0x7f89f141d040, 0xc430520750, 0x148deeaef873bb83, 0x0, 0x200000001, 0x3, 0x1c24, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1650 +0x39c
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc420f80480, 0x7f89f141d040, 0xc430520750, 0x148deeaef873bb83, 0x0, 0x200000001, 0x3, 0x1c24, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1221 +0x682
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc42035e000, 0x7f89f141d040, 0xc430520750, 0x148deeaef873bb83, 0x0, 0x200000001, 0x3, 0x1c24, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2471 +0x6c5
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42026afc0, 0x7f89f141d040, 0xc430520750, 0x0, 0x0, 0x200000001, 0x3, 0x1c24, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:824 +0x2a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc42039e000, 0xc43d353cd8, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x100
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc420199340, 0x7f89f141d000, 0xc4293d6980, 0xc428d21928, 0xc4293d6980, 0x62ef23, 0xc422f14ef0)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:835 +0x1ed
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc420199340, 0x7f89f141d000, 0xc4293d6980, 0xc428d21928, 0xc422f14f60, 0xc422f14f70, 0xc422f14f88)
        /go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:857 +0xa0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0x256ea60, 0xc420199340, 0xc43971b020, 0xc428d21900, 0xc43971ad20)
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:189 +0x64
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
        /go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:192 +0x23c
```

**Comment by petermattis** [comment] 2016-12-07 15:04
`delta-09` shows:

```
cockroach@cockroach-delta-09:~$ sudo ./cockroach debug range-data /mnt/data1 7204 | head -5
/Local/RangeID/7204/r/RangeFrozenStatus: false
/Local/RangeID/7204/r/RangeLastGC: : EMPTY

/Local/RangeID/7204/r/RaftAppliedIndex: 88127
/Local/RangeID/7204/r/RaftTombstone: next_replica_id:5
```

@bdarnell Claims that we should only have Raft tombstone keys when we don't have normal range data, but that clearly isn't the case here. It's unfortunate that the RaftTombstone key is in the replicated key space because it definitely isn't written in a replicated fashion. As a short term hack we could exclude this key from the consistency checker and snapshotting, though it would be good to figure out how it got there in the first place.

**Comment by petermattis** [comment] 2016-12-07 15:45
Well, the problem is definitely due to the recent addition of writing the tombstone key before applying a preemptive snapshot. Something I haven't figured out yet is why applying the snapshot doesn't delete the tombstone key.

**Comment by petermattis** [comment] 2016-12-07 15:48
Ah, we skip applying the snapshot if raft gave us an empty snapshot. Ok, seems easy enough to fix this. We shouldn't be writing the tombstone key when applying a preemptive snapshot.

**Closed** 2016-12-07 19:37 UTC
