### ISSUE TITLE
*: all nodes in zombie state

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#7693] opened 2016-07-08 10:33 UTC
Reported by @LorenzoBoccaccia on Gitter:
- is there a way to limit max memory usage of the cockroach process? this thing is eating up all memory including the swap even while doing nothing (literally, zero connections ever, no data), if tomcat sneezes oomk will bring down the whole thing just because
- ah, didn't notice but this morning all nodes were ded (ram is still used and process is still up), see https://files.gitter.im/cockroachdb/cockroach/qMRw/blob 
  with, in logs:

```
W160708 04:04:29.258612 gossip/gossip.go:902 first range unavailable or cluster not initialized
and many 
E160707 09:09:48.930454 storage/replica_command.go:1873 consistency check failed: k:v = (/System/"tsd\x12cr.node.exec.latency-1m-p90\x00\x01\x89\xf8\x068\xc32" (/System/"tsd\x12cr.node.exec.latency-1m-p90\x00\x01\x89\xf8\x068\xc32")
```
- /dev/sda1: clean, 307/36432 files, 77459/145408 blocks, dmesg no relevant messgaes - also corruption on all six disk concurrently seems implausible
- unless corruption on one file kills the whole cluster but then I misunderstood the advertised durability

**Comment by LorenzoBoccaccia** [comment] 2016-07-08 10:46
also whatever happened propagated to all cluster nodes
![image](https://cloud.githubusercontent.com/assets/3062853/16685220/f8074c00-4509-11e6-94d3-b7bcbe8cc16a.png)

**Comment by petermattis** [comment] 2016-07-08 12:20
@LorenzoBoccaccia Thanks for the report.

By default, cockroach uses 1/4 of physical memory for the RocksDB cache. Were you setting the `--cache-size` flag? If not, running 6 nodes on a single machine is going to cause problems.

Even an idle node will be periodically writing stats, but what you have experienced is extreme. I see from your screenshot that the nodes started 19 hours ago. Was that when the cluster was created? Some more details would be helpful as we try to reproduce. This is definitely a bug.

The consistency check failure is almost certainly a bug in the cockroach code. That checker was introduced primarily to detect bugs, not to detect disk corruption. We'll be trying to reproduce this failure as well.

Lastly, the "first range unavailable" message is something we're actively addressing right now. Unavailability of the first range can lead to the entire cluster being unavailable.

**Comment by LorenzoBoccaccia** [comment] 2016-07-08 12:39
sorry I didn't make it clear, but it's six different (virtual) machines, each with 4 cores, 2g ram and 40g hdd. 

I restarted the cluster once because it hung up during a database drop, it previously ran for 2 days after I had to recreate it because gossip didn't work and some nodes couldn't join.

after restarting every node joined as usual and resumed operations, only to die the morning after. I?ve one data dir saved on the first node if you need.

it's 200mb, it contains only an empty schema and logs.  
https://www.dropbox.com/s/eet1yacbppobegf/cockroach-data.zip?dl=0

cluster is six nodes with 5 replicas, I'm still at the point where I'm trying to get a hand of read/write performances before scaling.

**Comment by petermattis** [comment] 2016-07-08 14:40
The supplied data directory contains 64065 keys. The breakdown is as follows:
* 48 keys in the namespace table
* 667 keys in the descriptor table
* 15 keys in the zones table
* 40 keys in the lease table
* 314 keys in the event log table
* 3206 keys in the range event table
* 64 keys in the ui table
* 48054 timeseries keys
* 9633 raft log keys
* 723 meta keys (meta1 and meta2)
* 1472 miscellaneous keys (local range, meta1, meta2, etc)

Where is all the space going? There is 1003 MB of raw key/value data. The breakdown:
* 249 MB for timeseries
* 752 MB for raft log
* 0.87 MB for everything else

The size of the timeseries data is very consistent. A single timeseries key holds the data for one metric/source/resolution tuple. We only store the `10s` resolution currently. For the `10s` resolution we bucket 1 hour worth of data points into a key which translates to 360 samples for a full hour. Looking at the data, the vast majority of timeseries keys have values that are 5670 bytes in size. That's 15.75 bytes per sample which looks about right considering we're storing a 4-byte offset + 8-byte sum per sample along with encoding overhead. We could do a little better on the encoding overhead with a bit of reshuffling of the `InternalTimeSeriesData` proto, but that's going to be a difficult change now. We currently have 136 node level and 29 store level metrics which translates into ~1 MB of metrics data per node/store per hour.

The raft log is strange. 9578 of the entries are smaller than 10 KB and consume 3.8 MB of space. The remaining 55 entries are larger than 10 MB and consume 749 MB. The largest is 35 MB. These largest entries are only present in 4 of the 49 ranges. Hand inspection reveals that the largest all correspond to `VerifyChecksum` operations. Further inspection shows we have 59 `VerifyChecksum` operations in the raft log. 4 of these operations are tiny, consuming a few hundred bytes. The remaining are gigantic and correspond to a `VerifyChecksumRequest` containing a `RaftSnapshotData` which occurs during a consistency check failure. A consistency check failure causing huge data blow-up is less than ideal, though I understand this was necessary to provide better log messages about which keys were causing the consistency failure. @vivekmenezes, @bdarnell Thoughts?

**Comment by tschottdorf** [comment] 2016-07-08 14:52
Off topic, but it'll be helpful for future such analyses if you post some
of the commands you ran to arrive at this breakdown.

On Fri, Jul 8, 2016 at 10:40 AM Peter Mattis <notifications@github.com>
wrote:

> The supplied data directory contains 64065 keys. The breakdown is as
> follows:
>
>    - 48 keys in the namespace table
>    - 667 keys in the descriptor table
>    - 15 keys in the zones table
>    - 40 keys in the lease table
>    - 314 keys in the event log table
>    - 3206 keys in the range event table
>    - 64 keys in the ui table
>    - 48054 timeseries keys
>    - 9633 raft log keys
>    - 723 meta keys (meta1 and meta2)
>    - 1472 miscellaneous keys (local range, meta1, meta2, etc)
>
> Where is all the space going? There is 1003 MB of raw key/value data. The
> breakdown:
>
>    - 249 MB for timeseries
>    - 752 MB for raft log
>    - 0.87 MB for everything else
>
> The size of the timeseries data is very consistent. A single timeseries
> key holds the data for one metric/source/resolution tuple. We only store
> the 10s resolution currently. For the 10s resolution we bucket 1 hour
> worth of data points into a key which translates to 360 samples for a full
> hour. Looking at the data, the vast majority of timeseries keys have values
> that are 5670 bytes in size. That's 15.75 bytes per sample which looks
> about right considering we're storing a 4-byte offset + 8-byte sum per
> sample along with encoding overhead. We could do a little better on the
> encoding overhead with a bit of reshuffling of the InternalTimeSeriesData
> proto, but that's going to be a difficult change now. We currently have 136
> node level and 29 store level metrics which translates into ~1 MB of
> metrics data per node/store per hour.
>
> The raft log is strange. 9578 of the entries are smaller than 10 KB and
> consume 3.8 MB of space. The remaining 55 entries are larger than 10 MB and
> consume 749 MB. The largest is 35 MB. These largest entries are only
> present in 4 of the 49 ranges. Hand inspection reveals that the largest all
> correspond to VerifyChecksum operations. Further inspection shows we have
> 59 VerifyChecksum operations in the raft log. 4 of these operations are
> tiny, consuming a few hundred bytes. The remaining are gigantic and
> correspond to a VerifyChecksumRequest containing a RaftSnapshotData which
> occurs during a consistency check failure. A consistency check failure
> causing huge data blow-up is less than ideal, though I understand this was
> necessary to provide better log messages about which keys were causing the
> consistency failure. @vivekmenezes <https://github.com/vivekmenezes>,
> @bdarnell <https://github.com/bdarnell> Thoughts?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7693#issuecomment-231377567>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135Kda1C29_3pJNR7NVoSoQ-sPtNAUks5qTmF1gaJpZM4JH6c7>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment] 2016-07-08 14:52
I'd be willing to bet those large `VerifyChecksumRequest` messages are also causing memory blow up.

**Comment by tschottdorf** [comment] 2016-07-08 14:53
Just saw the PR. Even better!

On Fri, Jul 8, 2016 at 10:52 AM Tobias Schottdorf <tobias@cockroachlabs.com>
wrote:

> Off topic, but it'll be helpful for future such analyses if you post some
> of the commands you ran to arrive at this breakdown.
>
> On Fri, Jul 8, 2016 at 10:40 AM Peter Mattis <notifications@github.com>
> wrote:
>
>> The supplied data directory contains 64065 keys. The breakdown is as
>> follows:
>>
>>    - 48 keys in the namespace table
>>    - 667 keys in the descriptor table
>>    - 15 keys in the zones table
>>    - 40 keys in the lease table
>>    - 314 keys in the event log table
>>    - 3206 keys in the range event table
>>    - 64 keys in the ui table
>>    - 48054 timeseries keys
>>    - 9633 raft log keys
>>    - 723 meta keys (meta1 and meta2)
>>    - 1472 miscellaneous keys (local range, meta1, meta2, etc)
>>
>> Where is all the space going? There is 1003 MB of raw key/value data. The
>> breakdown:
>>
>>    - 249 MB for timeseries
>>    - 752 MB for raft log
>>    - 0.87 MB for everything else
>>
>> The size of the timeseries data is very consistent. A single timeseries
>> key holds the data for one metric/source/resolution tuple. We only store
>> the 10s resolution currently. For the 10s resolution we bucket 1 hour
>> worth of data points into a key which translates to 360 samples for a full
>> hour. Looking at the data, the vast majority of timeseries keys have values
>> that are 5670 bytes in size. That's 15.75 bytes per sample which looks
>> about right considering we're storing a 4-byte offset + 8-byte sum per
>> sample along with encoding overhead. We could do a little better on the
>> encoding overhead with a bit of reshuffling of the InternalTimeSeriesData
>> proto, but that's going to be a difficult change now. We currently have 136
>> node level and 29 store level metrics which translates into ~1 MB of
>> metrics data per node/store per hour.
>>
>> The raft log is strange. 9578 of the entries are smaller than 10 KB and
>> consume 3.8 MB of space. The remaining 55 entries are larger than 10 MB and
>> consume 749 MB. The largest is 35 MB. These largest entries are only
>> present in 4 of the 49 ranges. Hand inspection reveals that the largest all
>> correspond to VerifyChecksum operations. Further inspection shows we
>> have 59 VerifyChecksum operations in the raft log. 4 of these operations
>> are tiny, consuming a few hundred bytes. The remaining are gigantic and
>> correspond to a VerifyChecksumRequest containing a RaftSnapshotData
>> which occurs during a consistency check failure. A consistency check
>> failure causing huge data blow-up is less than ideal, though I understand
>> this was necessary to provide better log messages about which keys were
>> causing the consistency failure. @vivekmenezes
>> <https://github.com/vivekmenezes>, @bdarnell
>> <https://github.com/bdarnell> Thoughts?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/cockroachdb/cockroach/issues/7693#issuecomment-231377567>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AE135Kda1C29_3pJNR7NVoSoQ-sPtNAUks5qTmF1gaJpZM4JH6c7>
>> .
>>
> --
>
> -- Tobias
>
-- 

-- Tobias

**Comment by tschottdorf** [comment] 2016-07-08 14:55
> I'd be willing to bet those large VerifyChecksumRequest messages are also causing memory blow up.

Yeah. Perhaps that can explain a lot of weirdness we've been seeing on test clusters when the consistency checker is unhappy.

**Comment by petermattis** [comment] 2016-07-08 15:00
Looking into the gossip problem. The first indication is:

```
W160707 08:16:21.027521 gossip/gossip.go:904  partition in gossip network; attempting new connection
```

A short time later:

```
W160707 08:17:37.911107 gossip/gossip.go:904  partition in gossip network; attempting new connection
I160707 08:17:40.288281 gossip/gossip.go:926  starting client to cockroach-004.boostrappr.com:26257
I160707 08:17:40.897899 gossip/server.go:188  refusing gossip from node 4 (max 3 conns); forwarding to 3 ({tcp cockroach-003.boostrappr.com:26257})
I160707 08:18:45.665532 server/status/runtime.go:187  runtime stats: 1.7 GiB RSS, 220 goroutines, 622 MiB/1.2 GiB/1.8 GiB GO alloc/idle/total, 372 MiB/433 MiB CGO alloc/total, 2.21cgo/sec, 0.07/0.06 %(u/s)time, 0.00 %gc (0x)
I160707 08:18:45.665592 gossip/gossip.go:926  starting client to cockroach-005.boostrappr.com:26257
W160707 08:18:45.962063 gossip/gossip.go:904  partition in gossip network; attempting new connection
E160707 08:18:48.098614 server.go:2159  http: TLS handshake error from 2.227.226.122:50678: EOF
E160707 08:18:48.334552 server.go:2159  http: TLS handshake error from 2.227.226.122:50679: EOF
E160707 08:18:48.334623 server.go:2159  http: TLS handshake error from 2.227.226.122:50680: EOF
I160707 08:18:48.335768 gossip/gossip.go:926  starting client to cockroach-006.boostrappr.com:26257
E160707 08:18:48.415123 server.go:2159  http: TLS handshake error from 2.227.226.122:50677: EOF
E160707 08:18:48.415205 server.go:2159  http: TLS handshake error from 2.227.226.122:50682: EOF
I160707 08:18:48.416611 gossip/server.go:188  refusing gossip from node 5 (max 3 conns); forwarding to 6 ({tcp cockroach-006.boostrappr.com:26257})
```

And then:

```
I160707 08:18:54.183715 gossip/client.go:87  closing client to node 5 (cockroach-005.boostrappr.com:26257): stopping out
going client to node 5 (cockroach-005.boostrappr.com:26257); already have incoming
W160707 08:18:54.183754 gossip/gossip.go:904  partition in gossip network; attempting new connection
I160707 08:18:54.230272 gossip/gossip.go:926  starting client to cockroach-002.boostrappr.com:26257
I160707 08:18:54.231555 gossip/client.go:87  closing client to node 6 (cockroach-006.boostrappr.com:26257): stopping out
going client to node 6 (cockroach-006.boostrappr.com:26257); already have incoming
W160707 08:18:54.279939 gossip/gossip.go:902  first range unavailable or cluster not initialized
I160707 08:18:54.284092 gossip/client.go:87  closing client to node 2 (cockroach-002.boostrappr.com:26257): received forward from node 2 to 5 (cockroach-005.boostrappr.com:26257); already have active connection, skipping
W160707 08:18:54.284122 gossip/gossip.go:902  first range unavailable or cluster not initialized
W160707 08:18:55.419758 gossip/gossip.go:902  first range unavailable or cluster not initialized
I160707 08:18:56.234470 gossip/gossip.go:926  starting client to cockroach-003.boostrappr.com:26257
I160707 08:18:56.234663 gossip/server.go:188  refusing gossip from node 6 (max 3 conns); forwarding to 3 ({tcp cockroach-003.boostrappr.com:26257})
I160707 08:18:58.628481 gossip/gossip.go:926  starting client to cockroach-005.boostrappr.com:26257
I160707 08:18:58.628694 gossip/server.go:188  refusing gossip from node 6 (max 3 conns); forwarding to 2 ({tcp cockroach-002.boostrappr.com:26257})
I160707 08:18:59.194719 gossip/client.go:87  closing client to node 5 (cockroach-005.boostrappr.com:26257): stopping outgoing client to node 5 (cockroach-005.boostrappr.com:26257); already have incoming
W160707 08:18:59.194767 gossip/gossip.go:902  first range unavailable or cluster not initialized
I160707 08:19:00.133281 gossip/gossip.go:926  starting client to cockroach-006.boostrappr.com:26257
```

@tamird I think you're the authority on gossip. What can you make of this? Note that the logs are contained in the cockroach-data.zip that @LorenzoBoccaccia provided.

**Comment by petermattis** [comment] 2016-07-08 15:04
The spike in Go memory usage occurred slightly before the above events:

```
I160707 08:14:00.907620 server/status/runtime.go:187  runtime stats: 446 MiB RSS, 112 goroutines, 9.9 MiB/9.3 MiB/46 MiB GO alloc/idle/total, 292 MiB/352 MiB CGO alloc/total, 927.47cgo/sec, 0.11/0.05 %(u/s)time, 0.00 %gc (6x)
I160707 08:14:02.091052 storage/replica_command.go:1575  range 1: new leader lease replica {1 1 12} 2016-07-07 12:14:02.011908602 +0000 UTC 4.820268364s following replica {5 5 21} 2016-07-07 11:41:07.238437535 +0000 UTC 32m54.773471067s [physicalTime=2016-07-07 12:14:02.090723577 +0000 UTC]
I160707 08:14:21.703865 server/status/runtime.go:187  runtime stats: 1.2 GiB RSS, 124 goroutines, 658 MiB/52 MiB/744 MiB GO alloc/idle/total, 374 MiB/436 MiB CGO alloc/total, 2069.90cgo/sec, 0.92/0.50 %(u/s)time, 0.07 %gc (16x)
```

So over the span of 20s, Go memory usage grew by 650 MB and the only entry in the log is a leader lease acquisition. Note that this is well before the first consistency check failure which occurred at `E160707 08:57:38.200673`.

**Comment by tschottdorf** [comment] 2016-07-08 15:19
Related gossip issue here:
https://github.com/cockroachdb/cockroach/issues/7668

I haven't looked at this closely, but we shouldn't be seeing many
capacity-based forwards ("refusing gossip from node x (max 3 conns)") -
maybe we're not decreasing the count correctly.

On Fri, Jul 8, 2016 at 11:09 AM Peter Mattis <notifications@github.com>
wrote:

> The spike in Go memory usage occurred slightly before the above events:
>
> I160707 08:14:00.907620 server/status/runtime.go:187  runtime stats: 446 MiB RSS, 112 goroutines, 9.9 MiB/9.3 MiB/46 MiB GO alloc/idle/total, 292 MiB/352 MiB CGO alloc/total, 927.47cgo/sec, 0.11/0.05 %(u/s)time, 0.00 %gc (6x)
> I160707 08:14:02.091052 storage/replica_command.go:1575  range 1: new leader lease replica {1 1 12} 2016-07-07 12:14:02.011908602 +0000 UTC 4.820268364s following replica {5 5 21} 2016-07-07 11:41:07.238437535 +0000 UTC 32m54.773471067s [physicalTime=2016-07-07 12:14:02.090723577 +0000 UTC]
> I160707 08:14:21.703865 server/status/runtime.go:187  runtime stats: 1.2 GiB RSS, 124 goroutines, 658 MiB/52 MiB/744 MiB GO alloc/idle/total, 374 MiB/436 MiB CGO alloc/total, 2069.90cgo/sec, 0.92/0.50 %(u/s)time, 0.07 %gc (16x)
>
> So over the span of 20s, Go memory usage grew by 650 MB and the only entry
> in the log is a leader lease acquisition. Note that this is well before the
> first consistency check failure which occurred at E160707 08:57:38.200673.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/7693#issuecomment-231384220>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AE135MZYiAWtNT7iZFgFvAmxbEBCGqVKks5qTmcmgaJpZM4JH6c7>
> .
>
-- 

-- Tobias

**Comment by petermattis** [comment] 2016-07-08 15:21
Perhaps gossip should periodically log its state. Similar to the runtime stats, it would be handy to see the number of incoming/outgoing gossip connections and basic stats about traffic.

**Comment by LorenzoBoccaccia** [comment] 2016-07-08 20:34
left the cluster alone without touching anything, not restarting nodes, nothing at all. after another half day now the server gives a 500 error; before it was at least showing the admin interface. 

last error is
E160708 16:30:49.541776 server/admin.go:638  rpc error: code = 13 desc = An internal server error has occurred. Please check your CockroachDB logs for more details.

but CockroachDB logs doesn't give more details. do you want an updated data dir?

**Comment by petermattis** [comment] 2016-07-08 20:39
@LorenzoBoccaccia Your cluster is in a bad state. I would be extremely surprised if it recovered on its own. No need for an updated data dir at this point. We have a couple of actions to take on our side.

**Comment by tamird** [comment] 2016-10-04 01:34
The gossip issues here may have been (accidentally) fixed by https://github.com/cockroachdb/cockroach/pull/8945.

**Comment by knz** [comment] 2018-07-13 11:02
@tschottdorf can you close or triage

**Comment by tschottdorf** [comment] 2018-07-19 04:16
Closing as not actionable.

**Closed** 2018-07-19 04:16 UTC
Labels: C-investigation, S-1-stability
