### ISSUE TITLE
Delete queries with IN clauses are slow with full scans

### ISSUE THREAD

**Issue by jhatcher9999** [cockroachdb/cockroach#72037] opened 2021-10-27 14:55 UTC
**Describe the problem**
When deleting records using `WHERE id IN ( SELECT id FROM ... )`, the execution plan creates a full scan.  If you run that SELECT clause and get the values directly and change to `WHERE id IN ( val1, val2, ... )`, it uses an index and runs much faster.

**To Reproduce**

SETUP:
```
CREATE DATABASE IF NOT EXISTS test;
USE test;

DROP TABLE IF EXISTS child;
DROP TABLE IF EXISTS parent;

CREATE TABLE parent (
  id INT8 NOT NULL,
  name STRING NULL,
  CONSTRAINT "pk_parent" PRIMARY KEY (id ASC),
  INDEX ix_parent_name (name ASC)
);

CREATE TABLE child (
  child_id INT8 NOT NULL DEFAULT unique_rowid(),
  parent_id INT8 NULL,
  value INT8 NULL,
  CONSTRAINT "pk_child" PRIMARY KEY ( child_id ),
  CONSTRAINT fk_parent_id_ref_parent FOREIGN KEY (parent_id) REFERENCES parent(id),
  INDEX ix_child_parent_id (parent_id ASC)
);


INSERT INTO parent ( id, name ) VALUES ( 1, '1' );
INSERT INTO parent ( id, name ) VALUES ( 2, '2' );
INSERT INTO child ( child_id, parent_id, value ) VALUES ( 1, 1, '1' );
INSERT INTO child ( child_id, parent_id, value ) VALUES ( 2, 2, '2' );
```

explain plan for SELECT approach:
```
root@:26257/test> EXPLAIN DELETE FROM child WHERE parent_id IN ( SELECT id FROM parent WHERE name = '1');
                                          info
----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • delete
  │ from: child
  │ auto commit
  │
  └── • lookup join (semi)
      │ table: parent@ix_parent_name
      │ equality: (lookup_join_const_col_@12, parent_id) = (name,id)
      │ equality cols are key
      │
      └── • render
          │ estimated row count: 2
          │
          └── • scan
                estimated row count: 2 (100% of the table; stats collected 8 days ago)
                table: child@ix_child_parent_id
                spans: FULL SCAN
```

explain plan for list:
```
root@:26257/test> EXPLAIN DELETE FROM child WHERE parent_id IN ( 1 );
                                     info
-------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • delete
  │ from: child
  │ auto commit
  │
  └── • scan
        estimated row count: 1 (50% of the table; stats collected 8 days ago)
        table: child@ix_child_parent_id
        spans: [/1 - /1]
```

**Expected behavior**
I would expect that the SQL optimizer could use stats to figure out that it can use point lookups to make this query faster.  Or, maybe I could work around this behavior by using a temp table (that didn't work) or by suggesting an index hint (that didn't work either).

**Additional data / screenshots**

**Environment:**
 - CockroachDB 21.1.9

**Additional context**
What was the impact?  Slow delete queries.  They get exponentially slower with bigger tables and bigger set of results used in the where clause.

Jira issue: CRDB-10918

**Comment by rytaft** [comment] 2021-11-02 18:48
cc @vy-ton for prioritization

**Comment by jhatcher9999** [comment] 2021-11-18 22:03
hi @vy-ton any way I can bump this?  (thx!!)

**Comment by jordanlewis** [comment] 2021-11-18 22:11
I think this is a duplicate of #23264.

**Comment by jordanlewis** [comment] 2021-11-18 22:13
@rytaft could we solve some special cases of this issue with a specific optimizer rule? It seems like it's really common to see a `SELECT` within an `IN`. Could we convert this into a lookup join, maybe?

**Comment by rytaft** [comment] 2021-11-18 22:29
We do already have rules that do this. And I think we're doing the right thing in this case when there are a larger number of rows in the table. If I add the following to the above example, I get the desired plan:
```
INSERT INTO parent ( id, name ) select generate_series (3, 1000), generate_series (3, 1000)::string;
INSERT INTO child ( child_id, parent_id, value ) select generate_series (3, 1000), generate_series (3, 1000), generate_series (3, 1000);
ANALYZE parent;
ANALYZE child;

EXPLAIN DELETE FROM child WHERE parent_id IN ( SELECT id FROM parent WHERE name = '1'); 
                                          info
-----------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • delete
  │ from: child
  │ auto commit
  │
  └── • lookup join
      │ estimated row count: 1
      │ table: child@ix_child_parent_id
      │ equality: (id) = (parent_id)
      │
      └── • scan
            estimated row count: 1 (0.10% of the table; stats collected 57 seconds ago)
            table: parent@ix_parent_name
            spans: [/'1' - /'1']
(16 rows)
```

I don't think there's much else to do here that's not covered by #23264.

**Comment by jordanlewis** [comment] 2021-11-18 22:37
Ahh, thanks. @jhatcher9999, are you seeing this on larger tables as well, or just small testing tables? Stats matter!

**Comment by jhatcher9999** [comment] 2021-11-18 22:48
Large tables (10s of millions).  I could show you in my customer's environment.  I was trying to give you a simple repro with small tables.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jordanlewis** [comment] 2021-11-18 23:53
Got it, thanks. @jhatcher9999 it would be helpful if you could upload a statement bundle for this case somewhere internally, we can construct a minimized repro from there.

**Comment by jhatcher9999** [comment] 2022-01-26 21:43
this seems like https://github.com/cockroachdb/cockroach/issues/7042 to me

**Comment by jordanlewis** [comment] 2022-06-11 20:38
This doesn't repro as of 21.2 so closing! 🎉

**Closed by jordanlewis** 2022-06-11 20:38 UTC
Labels: C-bug, T-sql-queries
