### ISSUE TITLE
sql: bug with lookup join

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#24401] opened 2018-04-02 06:43 UTC
Version: CockroachDB CCL v2.1-alpha.00000000-1468-gb9d7e8b12

The following table and query produces an error:

```
SET experimental_force_lookup_join = true;
create database d;
use d;
CREATE TABLE players (
	game INT NOT NULL,
	mode INT NULL,
	"time" TIMESTAMP NULL,
	hero INT NULL,
	team INT NULL,
	blizzid INT NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (game ASC, blizzid ASC)
);
select p.team = games.team as sameteam, p.hero
from (
	select game, max(team) team
	from players
	group by game
) games
join players p  on games.game = p.game;
```

`pq: "$4" = "$1": unsupported comparison operator: <timestamp> = <int>`

If I remove the SET line it runs. Interestingly, if I remove pretty much any line of the CREATE it also runs. Kinda feels like an incorrect index offset somewhere.

**Comment by jordanlewis** [comment] 2018-04-02 17:50
Somehow I doubt that this is related to lookup joins.

**Comment by jordanlewis** [comment] 2018-04-02 17:52
Wait, nevermind. I thought you were talking about running that whole batch as a single query and seeing that fail. For the record, the `JOIN` in question reproducibly causes that error once the schema and setting is created.

**Comment by andreimatei** [comment] 2018-04-09 16:32
@pbardea , any update on this?

**Comment by pbardea** [comment] 2018-04-10 16:05
@andreimatei found a fix to this issue which should be up shortly. while fixing it I found out that the `processorBase.init` has to be called sometimes from the `joinReader` (because the parameters to `processorBase.init` differ for lookup joins and index joins. Cleaning that up a bit will be included in the fix to this bug.

**Closed** 2018-04-12 20:50 UTC
