### ISSUE TITLE
Test failure in CI build 5437

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1954] opened 2015-08-04 20:33 UTC
The following test appears to have failed:

[#5437](https://circleci.com/gh/cockroachdb/cockroach/5437):

```
W0804 20:32:40.109741 488 storage/store.go:584  error gossiping first range data: storage/replica.go:971: node is stopping
W0804 20:32:40.110039 488 storage/store.go:603  error gossiping configs: storage/replica.go:971: node is stopping
I0804 20:32:40.122899 488 storage/replica.go:988  gossiping cluster id  from store 3, range 1
I0804 20:32:40.123434 488 storage/replica.go:996  gossiping sentinel from store 3, range 1
I0804 20:32:40.123853 488 storage/replica.go:1000  gossiping first range from store 3, range 1
panic: test timed out after 5m0s

goroutine 25603 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x1491a60, 0x19b9f40, 0xba, 0xba, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:249 +0x4ea
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x8c
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x14c
FAIL	github.com/cockroachdb/cockroach/storage	300.056s
=== RUN TestBatchBasics
I0804 20:28:31.724292 499 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 20:28:31.725925 499 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN TestBatchGet
I0804 20:28:31.731403 499 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 20:28:31.732001 499 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN TestBatchMerge
I0804 20:28:31.737185 499 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-08-04 21:40
Another dupe of #1928.

**Closed by tamird** 2015-08-04 21:40 UTC
Labels: test-failure
