### ISSUE TITLE
circleci: failed tests: TestSystemConfigGossip 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6481] opened 2016-05-03 21:32 UTC
The following test appears to have failed:

[#17224](https://circleci.com/gh/cockroachdb/cockroach/17224):

```
I160503 21:27:58.589453 storage/intent_resolver.go:99  [node=1,store=1,range=1] on Scan: failed to push "storage/replica_command.go:1953 (*Replica).AdminSplit" id=d3ca6b16 key=/Local/Range/"\x96"/RangeDescriptor rw=true pri=0.11116969 iso=SERIALIZABLE stat=PENDING epo=1 ts=1462310878.518165464,1 orig=1462310878.505901157,0 max=1462310878.505901157,0 wto=false
W160503 21:27:58.589618 storage/store.go:1772  conflicting intents on [/Meta2/Table/14 /Meta2/Max]: resolved? false
W160503 21:27:58.732869 sql/lease.go:732  /Table/3/1/49/2/1: unable to unmarshal descriptor {[13 188 7 252 3 10 3 102 111 111 16 1] 1462310878.655162746,0}
W160503 21:27:58.742624 sql/schema_changer.go:527  /Table/3/1/49/2/1: unable to unmarshal descriptor {[13 188 7 252 3 10 3 102 111 111 16 1] 1462310878.655162746,0}
I160503 21:27:58.742816 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestSystemConfigGossip (0.91s)
	server_test.go:419: unexpected message received on gossip channel: {[{/Table/2/1/0/"system"/3/1 {[18 88 97 62 1 2] 1462310877.881974506,0}} {/Table/2/1/1/"descriptor"/3/1 {[136 238 172 209 1 6] 1462310877.881974506,0}} {/Table/2/1/1/"eventlog"/3/1 {[44 21 140 5 1 24] 1462310877.881974506,0}} {/Table/2/1/1/"lease"/3/1 {[205 248 213 252 1 22] 1462310877.881974506,0}} {/Table/2/1/1/"namespace"/3/1 {[60 185 31 84 1 4] 1462310877.881974506,0}} {/Table/2/1/1/"rangelog"/3/1 {[202 163 171 90 1 26] 1462310877.881974506,0}} {/Table/2/1/1/"ui"/3/1 {[123 247 193 129 1 28] 1462310877.881974506,0}} {/Table/2/1/1/"users"/3/1 {[93 180 27 24 1 8] 1462310877.881974506,0}} {/Table/2/1/1/"zones"/3/1 {[233 251 73 123 1 10] 1462310877.881974506,0}} {/Table/3/1/1/2/1 {[188 24 237 68 3 18 22 10 6 115 121 115 116 101 109 16 1 26 10 10 8 10 4 114 111 111 116 16 48] 1462310877.881974506,0}} {/Table/3/1/2/2/1 {[240 215 100 34 3 10 157 1 10 9 110 97 109 101 115 112 97 99 101 24 2 32 1 40 1 48 0 58 4 8 0 16 0 66 24 10 8 112 97 114 101 110 116 73 68 16 1 26 6 8 1 16 0 24 0 32 0 48 0 66 20 10 4 110 97 109 101 16 2 26 6 8 7 16 0 24 0 32 0 48 0 66 18 10 2 105 100 16 3 26 6 8 1 16 0 24 0 32 1 48 0 72 4 82 37 10 7 112 114 105 109 97 114 121 16 1 24 1 34 8 112 97 114 101 110 116 73 68 34 4 110 97 109 101 48 1 48 2 64 0 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 48 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/3/2/1 {[218 7 93 30 3 10 122 10 10 100 101 115 99 114 105 112 116 111 114 24 3 32 1 40 1 48 0 58 4 8 0 16 0 66 18 10 2 105 100 16 1 26 6 8 1 16 0 24 0 32 0 48 0 66 26 10 10 100 101 115 99 114 105 112 116 111 114 16 2 26 6 8 8 16 0 24 0 32 1 48 0 72 3 82 21 10 7 112 114 105 109 97 114 121 16 1 24 1 34 2 105 100 48 1 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 48 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/4/2/1 {[57 169 40 143 3 10 134 1 10 5 117 115 101 114 115 24 4 32 1 40 1 48 0 58 4 8 0 16 0 66 24 10 8 117 115 101 114 110 97 109 101 16 1 26 6 8 7 16 0 24 0 32 0 48 0 66 30 10 14 104 97 115 104 101 100 80 97 115 115 119 111 114 100 16 2 26 6 8 8 16 0 24 0 32 1 48 0 72 3 82 27 10 7 112 114 105 109 97 114 121 16 1 24 1 34 8 117 115 101 114 110 97 109 101 48 1 64 0 96 2 106 11 10 9 10 4 114 111 111 116 16 240 3 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/5/2/1 {[172 119 151 213 3 10 114 10 5 122 111 110 101 115 24 5 32 1 40 1 48 0 58 4 8 0 16 0 66 18 10 2 105 100 16 1 26 6 8 1 16 0 24 0 32 0 48 0 66 22 10 6 99 111 110 102 105 103 16 2 26 6 8 8 16 0 24 0 32 1 48 0 72 3 82 21 10 7 112 114 105 109 97 114 121 16 1 24 1 34 2 105 100 48 1 64 0 96 2 106 11 10 9 10 4 114 111 111 116 16 240 3 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/11/2/1 {[169 219 90 48 3 10 215 1 10 5 108 101 97 115 101 24 11 32 1 40 1 48 0 58 4 8 0 16 0 66 22 10 6 100 101 115 99 73 68 16 1 26 6 8 1 16 0 24 0 32 0 48 0 66 23 10 7 118 101 114 115 105 111 110 16 2 26 6 8 1 16 0 24 0 32 0 48 0 66 22 10 6 110 111 100 101 73 68 16 3 26 6 8 1 16 0 24 0 32 0 48 0 66 26 10 10 101 120 112 105 114 97 116 105 111 110 16 4 26 6 8 5 16 0 24 0 32 0 48 0 72 5 82 66 10 7 112 114 105 109 97 114 121 16 1 24 1 34 6 100 101 115 99 73 68 34 7 118 101 114 115 105 111 110 34 10 101 120 112 105 114 97 116 105 111 110 34 6 110 111 100 101 73 68 48 1 48 2 48 4 48 3 64 0 64 0 64 0 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 2 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/12/2/1 {[190 164 0 201 3 10 151 2 10 8 101 118 101 110 116 108 111 103 24 12 32 1 40 1 48 0 58 4 8 0 16 0 66 25 10 9 116 105 109 101 115 116 97 109 112 16 1 26 6 8 5 16 0 24 0 32 0 48 0 66 25 10 9 101 118 101 110 116 84 121 112 101 16 2 26 6 8 7 16 0 24 0 32 0 48 0 66 24 10 8 116 97 114 103 101 116 73 68 16 3 26 6 8 1 16 0 24 0 32 0 48 0 66 27 10 11 114 101 112 111 114 116 105 110 103 73 68 16 4 26 6 8 1 16 0 24 0 32 0 48 0 66 20 10 4 105 110 102 111 16 5 26 6 8 7 16 0 24 0 32 1 48 0 66 53 10 8 117 110 105 113 117 101 73 68 16 6 26 6 8 8 16 0 24 0 32 0 42 27 101 120 112 101 114 105 109 101 110 116 97 108 95 117 110 105 113 117 101 95 98 121 116 101 115 40 41 48 0 72 7 82 42 10 7 112 114 105 109 97 114 121 16 1 24 1 34 9 116 105 109 101 115 116 97 109 112 34 8 117 110 105 113 117 101 73 68 48 1 48 6 64 0 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 2 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/13/2/1 {[35 69 33 107 3 10 163 2 10 8 114 97 110 103 101 108 111 103 24 13 32 1 40 1 48 0 58 4 8 0 16 0 66 25 10 9 116 105 109 101 115 116 97 109 112 16 1 26 6 8 5 16 0 24 0 32 0 48 0 66 23 10 7 114 97 110 103 101 73 68 16 2 26 6 8 1 16 0 24 0 32 0 48 0 66 23 10 7 115 116 111 114 101 73 68 16 3 26 6 8 1 16 0 24 0 32 0 48 0 66 25 10 9 101 118 101 110 116 84 121 112 101 16 4 26 6 8 7 16 0 24 0 32 0 48 0 66 28 10 12 111 116 104 101 114 82 97 110 103 101 73 68 16 5 26 6 8 1 16 0 24 0 32 1 48 0 66 20 10 4 105 110 102 111 16 6 26 6 8 7 16 0 24 0 32 1 48 0 66 40 10 8 117 110 105 113 117 101 73 68 16 7 26 6 8 1 16 0 24 0 32 0 42 14 117 110 105 113 117 101 95 114 111 119 105 100 40 41 48 0 72 8 82 42 10 7 112 114 105 109 97 114 121 16 1 24 1 34 9 116 105 109 101 115 116 97 109 112 34 8 117 110 105 113 117 101 73 68 48 1 48 7 64 0 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 2 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/14/2/1 {[206 111 135 222 3 10 140 1 10 2 117 105 24 14 32 1 40 1 48 0 58 4 8 0 16 0 66 19 10 3 107 101 121 16 1 26 6 8 7 16 0 24 0 32 0 48 0 66 21 10 5 118 97 108 117 101 16 2 26 6 8 8 16 0 24 0 32 1 48 0 66 27 10 11 108 97 115 116 85 112 100 97 116 101 100 16 3 26 6 8 5 16 0 24 0 32 0 48 0 72 4 82 22 10 7 112 114 105 109 97 114 121 16 1 24 1 34 3 107 101 121 48 1 64 0 96 2 106 10 10 8 10 4 114 111 111 116 16 2 128 1 1 136 1 1 144 1 0] 1462310877.881974506,0}} {/Table/3/1/49/2/1 {[13 188 7 252 3 10 3 102 111 111 16 1] 1462310878.655162746,0}} {/Table/5/1/0/2/1 {[133 167 118 192 3 10 0 16 128 128 64 24 128 128 128 32 34 4 8 128 163 5] 1462310877.881974506,0}}]}
=== RUN   TestOfficializeAddr
--- PASS: TestOfficializeAddr (0.02s)
=== RUN   TestStatusLocalStacks
E160503 21:27:58.785886 util/envutil/env.go:121  error parsing COCKROACH_LINEARIZABLE: strconv.ParseBool: parsing "abcd": invalid syntax
E160503 21:27:58.786030 util/envutil/env.go:121  error parsing COCKROACH_CONSISTENCY_CHECK_PANIC_ON_FAILURE: strconv.ParseBool: parsing "abcd": invalid syntax
E160503 21:27:58.786122 util/envutil/env.go:177  error parsing COCKROACH_MAX_OFFSET: time: invalid duration abcd
E160503 21:27:58.786219 util/envutil/env.go:177  error parsing COCKROACH_METRICS_SAMPLE_INTERVAL: time: invalid duration abcd
E160503 21:27:58.786302 util/envutil/env.go:177  error parsing COCKROACH_SCAN_INTERVAL: time: invalid duration abcd
E160503 21:27:58.786389 util/envutil/env.go:177  error parsing COCKROACH_SCAN_MAX_IDLE_TIME: time: invalid duration abcd
--
I160503 21:28:09.375970 storage/replica_command.go:1439  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406197h28m10.424117785s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-03 21:28:09.37581396 +0000 UTC]
I160503 21:28:09.376507 storage/replica_command.go:1901  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160503 21:28:09.856473 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160503 21:28:09.856777 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestReportUsage (1.07s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	39.798s
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.12s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	1.182s
I160503 21:28:34.248233 rand.go:76  Random seed: 8419090661589234222
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.02s)
=== RUN   TestSplitAndExpr
--- PASS: TestSplitAndExpr (0.04s)
=== RUN   TestSimplifyExpr

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-05 22:34
Duplicate of #6203

**Closed by bdarnell** 2016-05-05 22:34 UTC
Labels: Robot, test-failure
