### ISSUE TITLE
sql: support pg_catalog.pg_opclas

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24742] opened 2018-04-12 19:14 UTC
An error pops up in Dbeaver when selecting system info, access methods, prefix, operator classes:

```SELECT oc.oid, oc.* 
FROM pg_catalog.pg_opclass AS oc 
ORDER BY oc.oid```

I180409 23:14:12.602038 5839 sql/conn_executor.go:1805  [n1,client=127.0.0.1:58767,user=root] execution error: relation "pg_catalog.pg_opclass" does not exist

**Comment by jordanlewis** [comment] 2019-04-27 00:18
Duplicate of #24742

**Closed by jordanlewis** 2019-04-27 00:18 UTC
Labels: A-sql-pgcompat, C-enhancement
