### ISSUE TITLE
Test failure in CI build 3759

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#1402] opened 2015-06-17 17:20 UTC
The following test appears to have failed:
[#3759](https://circleci.com/gh/cockroachdb/cockroach/3759)

```
=== RUN TestRangeDescriptorSnapshotRace
I0617 16:35:58.553714     299 rocksdb.go:88] opening in-memory rocksdb instance
I0617 16:35:58.554828     299 range.go:949] gossiping cluster id  from store 1, range 1
I0617 16:35:58.555695     299 range_command.go:772] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.555790     299 range.go:1010] gossiping accounting config from store 1, range 1
I0617 16:35:58.555874     299 range.go:1010] gossiping permissions config from store 1, range 1
I0617 16:35:58.555953     299 range.go:1010] gossiping zones config from store 1, range 1
I0617 16:35:58.556069     299 range.go:957] gossiping sentinel from store 1, range 1
I0617 16:35:58.556098     299 range.go:961] gossiping first range from store 1, range 1
I0617 16:35:58.569802     299 range_command.go:835] initiating a split of range=1 ["" - "\xff\xff") at key "A020"
I0617 16:35:58.574008     299 range_command.go:835] initiating a split of range=1 ["" - "A020") at key "A019"
I0617 16:35:58.575313     299 range_command.go:772] range 2: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.610234     299 range_command.go:835] initiating a split of range=1 ["" - "A019") at key "A018"
I0617 16:35:58.629230     299 range_command.go:772] range 3: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.691769     299 range_command.go:835] initiating a split of range=1 ["" - "A018") at key "A017"
I0617 16:35:58.693544     299 range_command.go:772] range 4: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.722230     299 range_command.go:835] initiating a split of range=1 ["" - "A017") at key "A016"
I0617 16:35:58.746755     299 range_command.go:772] range 5: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.775321     299 range_command.go:835] initiating a split of range=1 ["" - "A016") at key "A015"
I0617 16:35:58.777255     299 range_command.go:772] range 6: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.819058     299 range_command.go:835] initiating a split of range=1 ["" - "A015") at key "A014"
I0617 16:35:58.820933     299 range_command.go:772] range 7: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.852571     299 range_command.go:835] initiating a split of range=1 ["" - "A014") at key "A013"
I0617 16:35:58.879477     299 range_command.go:772] range 8: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.910123     299 range_command.go:835] initiating a split of range=1 ["" - "A013") at key "A012"
I0617 16:35:58.911997     299 range_command.go:772] range 9: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:58.954409     299 range_command.go:835] initiating a split of range=1 ["" - "A012") at key "A011"
I0617 16:35:58.966598     299 range_command.go:772] range 10: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.012529     299 range_command.go:835] initiating a split of range=1 ["" - "A011") at key "A010"
I0617 16:35:59.029463     299 range_command.go:772] range 11: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.059014     299 range_command.go:835] initiating a split of range=1 ["" - "A010") at key "A009"
I0617 16:35:59.081827     299 range_command.go:772] range 12: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.159634     299 range_command.go:835] initiating a split of range=1 ["" - "A009") at key "A008"
I0617 16:35:59.174914     299 range_command.go:772] range 13: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.220353     299 range_command.go:835] initiating a split of range=1 ["" - "A008") at key "A007"
I0617 16:35:59.222584     299 range_command.go:772] range 14: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.274939     299 range_command.go:835] initiating a split of range=1 ["" - "A007") at key "A006"
I0617 16:35:59.324771     299 range_command.go:772] range 15: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.362902     299 range_command.go:835] initiating a split of range=1 ["" - "A006") at key "A005"
I0617 16:35:59.398015     299 range_command.go:772] range 16: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.469602     299 range_command.go:835] initiating a split of range=1 ["" - "A005") at key "A004"
I0617 16:35:59.538024     299 range_command.go:772] range 17: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.565211     299 range_command.go:835] initiating a split of range=1 ["" - "A004") at key "A003"
I0617 16:35:59.580017     299 range_command.go:772] range 18: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.625520     299 range_command.go:835] initiating a split of range=1 ["" - "A003") at key "A002"
I0617 16:35:59.626951     299 range_command.go:772] range 19: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.668303     299 range_command.go:835] initiating a split of range=1 ["" - "A002") at key "A001"
I0617 16:35:59.687867     299 range_command.go:772] range 20: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.731190     299 range_command.go:835] initiating a split of range=2 ["A020" - "\xff\xff") at key "B000"
I0617 16:35:59.784597     299 range_command.go:772] range 21: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.812603     299 range_command.go:835] initiating a split of range=22 ["B000" - "\xff\xff") at key "B001"
I0617 16:35:59.828096     299 range_command.go:772] range 22: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.866247     299 range_command.go:835] initiating a split of range=23 ["B001" - "\xff\xff") at key "B002"
I0617 16:35:59.877300     299 range_command.go:772] range 23: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:35:59.927899     299 range_command.go:835] initiating a split of range=24 ["B002" - "\xff\xff") at key "B003"
I0617 16:35:59.946136     299 range_command.go:772] range 24: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.028872     299 range_command.go:835] initiating a split of range=25 ["B003" - "\xff\xff") at key "B004"
I0617 16:36:00.030578     299 range_command.go:772] range 25: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.091486     299 range_command.go:835] initiating a split of range=26 ["B004" - "\xff\xff") at key "B005"
I0617 16:36:00.118227     299 range_command.go:772] range 26: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.162346     299 range_command.go:835] initiating a split of range=27 ["B005" - "\xff\xff") at key "B006"
I0617 16:36:00.176533     299 range_command.go:772] range 27: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.201816     299 range_command.go:835] initiating a split of range=28 ["B006" - "\xff\xff") at key "B007"
I0617 16:36:00.203938     299 range_command.go:772] range 28: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.213211     299 range_command.go:835] initiating a split of range=29 ["B007" - "\xff\xff") at key "B008"
I0617 16:36:00.214702     299 range_command.go:772] range 29: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.222545     299 range_command.go:835] initiating a split of range=30 ["B008" - "\xff\xff") at key "B009"
I0617 16:36:00.223628     299 range_command.go:772] range 30: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.233314     299 range_command.go:835] initiating a split of range=31 ["B009" - "\xff\xff") at key "B010"
I0617 16:36:00.235056     299 range_command.go:772] range 31: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.243501     299 range_command.go:835] initiating a split of range=32 ["B010" - "\xff\xff") at key "B011"
I0617 16:36:00.244648     299 range_command.go:772] range 32: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.253686     299 range_command.go:835] initiating a split of range=33 ["B011" - "\xff\xff") at key "B012"
I0617 16:36:00.255555     299 range_command.go:772] range 33: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.262567     299 range_command.go:835] initiating a split of range=34 ["B012" - "\xff\xff") at key "B013"
I0617 16:36:00.263796     299 range_command.go:772] range 34: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.274023     299 range_command.go:835] initiating a split of range=35 ["B013" - "\xff\xff") at key "B014"
I0617 16:36:00.275303     299 range_command.go:772] range 35: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.282407     299 range_command.go:835] initiating a split of range=36 ["B014" - "\xff\xff") at key "B015"
I0617 16:36:00.283773     299 range_command.go:772] range 36: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.293159     299 range_command.go:835] initiating a split of range=37 ["B015" - "\xff\xff") at key "B016"
I0617 16:36:00.295618     299 range_command.go:772] range 37: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.305675     299 range_command.go:835] initiating a split of range=38 ["B016" - "\xff\xff") at key "B017"
I0617 16:36:00.306886     299 range_command.go:772] range 38: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.315133     299 range_command.go:835] initiating a split of range=39 ["B017" - "\xff\xff") at key "B018"
I0617 16:36:00.316389     299 range_command.go:772] range 39: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.324316     299 range_command.go:835] initiating a split of range=40 ["B018" - "\xff\xff") at key "B019"
I0617 16:36:00.325613     299 range_command.go:772] range 40: new leader lease replica 1:1 00:00:00.000 +1.000s
I0617 16:36:00.340638     299 range_command.go:772] range 41: new leader lease replica 1:1 00:00:00.000 +1.000s
--- FAIL: TestRangeDescriptorSnapshotRace (1.79s)
	client_raft_test.go:776: failed to snapshot max range: range_raftstorage.go:257: couldn't find range descriptor

**Comment by bdarnell** [comment] 2015-06-17 18:23
Duplicate of #1191

**Closed by bdarnell** 2015-06-17 18:23 UTC
