### ISSUE TITLE
server: TLS handshake log spam from health checks

### ISSUE THREAD

**Issue by markharding** [cockroachdb/cockroach#32102] opened 2018-11-01 19:06 UTC
## Summary

We are using k8s on AWS and experience the following errors despite cockroachdb working without issues.

```

2018-11-01 10:38:34 | ERROR | http: TLS handshake error from 10.0.9.140:36238: EOF | server.go:2921
-- | -- | -- | --
2018-11-01 10:38:36 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.140:62179": EOF | vendor/google.golang.org/grpc/server.go:603
2018-11-01 10:38:37 | ERROR | http: TLS handshake error from 10.0.9.66:4587: EOF | server.go:2921
2018-11-01 10:38:38 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.66:1101": EOF

```

k8s configs -> https://github.com/cockroachdb/cockroach/pull/27921/files

Load Balancer configs:

```
apiVersion: v1
kind: Service
metadata:
  # This service is meant to be used by clients of the database. It exposes a ClusterIP that will
  # automatically load balance connections to the different database pods.
  name: cockroachdb-external
  labels:
    app: cockroachdb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  # The main port, served by gRPC, serves Postgres-flavor SQL, internode
  # traffic and the cli.
  - port: 26257
    targetPort: 26257
    name: grpc
  # The secondary port serves the UI as well as health and debug endpoints.
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: cockroachdb
```

## Steps to reproduce

1. Setup k8s with the above configurations
2. View error logs

## Expected Result

No error log entry

## Actual Result

Error log entry

### Node 1

```

2018-11-01 10:22:43 | INFO | [config] clusterID: 0e8897c8-ce0f-498b-95c1-e56892697e47 | util/log/clog.go:1067
-- | -- | -- | --
2018-11-01 10:22:43 | INFO | [config] arguments: [/cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs --advertise-host cockroachdb-0.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%] | util/log/clog.go:1067
2018-11-01 10:22:43 | INFO | [config] binary: CockroachDB CCL v2.1.0 (x86_64-unknown-linux-gnu, built 2018/10/30 12:32:34, go1.10.3) | util/log/clog.go:1067
2018-11-01 10:22:43 | INFO | [config] running on machine: cockroachdb-0 | util/log/clog.go:1067
2018-11-01 10:22:43 | INFO | [config] file created at: 2018/11/01 10:22:43


---


2018-11-01 10:38:34 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.66:50273": EOF | vendor/google.golang.org/grpc/server.go:603
-- | -- | -- | --
2018-11-01 10:38:34 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.66:56280": EOF | vendor/google.golang.org/grpc/server.go:603
2018-11-01 10:38:34 | ERROR | http: TLS handshake error from 10.0.9.140:36238: EOF | server.go:2921
2018-11-01 10:38:36 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.140:62179": EOF | vendor/google.golang.org/grpc/server.go:603
2018-11-01 10:38:37 | ERROR | http: TLS handshake error from 10.0.9.66:4587: EOF | server.go:2921
2018-11-01 10:38:38 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.66:1101": EOF
```

### Node 2

```

2018-11-01 10:07:28 | INFO | [config] clusterID: 0e8897c8-ce0f-498b-95c1-e56892697e47 | util/log/clog.go:1067
-- | -- | -- | --
2018-11-01 10:07:28 | INFO | [config] arguments: [/cockroach/cockroach start --logtostderr --certs-dir /cockroach/cockroach-certs --advertise-host cockroachdb-2.cockroachdb.default.svc.cluster.local --http-host 0.0.0.0 --join cockroachdb-0.cockroachdb,cockroachdb-1.cockroachdb,cockroachdb-2.cockroachdb --cache 25% --max-sql-memory 25%] | util/log/clog.go:1067
2018-11-01 10:07:28 | INFO | [config] binary: CockroachDB CCL v2.1.0 (x86_64-unknown-linux-gnu, built 2018/10/30 12:32:34, go1.10.3) | util/log/clog.go:1067
2018-11-01 10:07:28 | INFO | [config] running on machine: cockroachdb-2 | util/log/clog.go:1067
2018-11-01 10:07:28 | INFO | [config] file created at: 2018/11/01 10:07:28



---


2018-11-01 10:22:37 | ERROR | http: TLS handshake error from 10.0.9.140:7586: EOF | server.go:2921
-- | -- | -- | --
2018-11-01 10:22:41 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.140:18280": EOF | vendor/google.golang.org/grpc/server.go:603
2018-11-01 10:22:42 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.66:59662": EOF | vendor/google.golang.org/grpc/server.go:603
2018-11-01 10:22:44 | WARNING | grpc: Server.Serve failed to complete security handshake from "10.0.9.140:10379": EOF

```

**Comment by bdarnell** [comment] 2018-11-01 20:11
These messages are harmless, but annoying. They're happening because the load balancer is just doing a TCP-level health check and closing the connection immediately. Unfortunately we can't easily suppress these log messages because they're coming from deep within our dependencies. 

The k8s configs are supposed to be doing HTTPS health checks, which wouldn't generate these messages. There might be something else going on in the AWS environment, or maybe there's something wrong with those templates.

**Comment by a-robinson** [comment] 2018-11-12 19:46
> The k8s configs are supposed to be doing HTTPS health checks, which wouldn't generate these messages. There might be something else going on in the AWS environment, or maybe there's something wrong with those templates.

That "something else" is most likely the AWS network load balancer that got created by the "Service" that @markharding referred to being of `type: LoadBalancer`. It may be worth checking out that load balancer's health checks to confirm they're the cause and optionally tweak them.

**Comment by RoachietheSupportRoach** [comment] 2019-07-29 16:53
Zendesk ticket #[3527](https://cockroachdb.zendesk.com/agent/tickets/3527) has been linked to this issue.

**Comment by robert-s-lee** [comment] 2019-09-04 21:13
@bdarnell @jseldess is the appropriately NLP config step known in-house for documentation?  who has the knowledge to help?

**Comment by bdarnell** [comment] 2019-09-04 21:17
Maybe the MSO team? If not them, I'm not sure if anyone internal has tried this.

**Comment by robert-s-lee** [comment] 2019-09-04 21:22
@kannanlakshmi How is the MSO LB setup (with and w/o K8s) on AWS and Google.

**Comment by RoachietheSupportRoach** [comment] 2019-09-04 21:31
NLB health checks are easily configured:
https://docs.aws.amazon.com/elasticloadbalancing/latest/network/target-group-health-checks.html
Details of the health check endpoint are in
https://www.cockroachlabs.com/docs/v19.1/monitoring-and-alerting.html#health-endpoints

**Comment by robert-s-lee** [comment] 2019-09-04 21:53
Is there a working annotation K8a config available with HTTP and HTTPS?  The original post had HTTP but resulted in error message in the log file.  Is the required change as simple as specifying HTTPS as Ben indicated?

**Comment by mberhault** [comment] 2019-09-04 22:11
Looking further, there doesn't seem to be much in the way of configuration for NLB on EKS: https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support

And a [number of](https://github.com/kubernetes/kubernetes/issues/73362) [issues](https://github.com/kubernetes/kubernetes/issues/81469) against kubernetes.

**Comment by knz** [comment] 2020-10-06 15:54
Investigated this today with @HonoreDB - the log spam here is slightly more complicated to eliminate than others because it is produced by our `grpc` upstream dependency, not the crdb code directly.

We do use some mechanism to prevent log spam for gRPC logging, but it's based on a threshold: we refuse to print the same error more than once per 30 seconds. Maybe that would be good enough for the TLS handshake error as well?

**Comment by bdarnell** [comment] 2020-10-06 17:29
The once-per-30-seconds rule makes sense for *outgoing* connection attempts - there should be some indication that we're attempting to initiate a connection that is failing. But for this issue of *incoming* connections that do nothing wrong except close without going through the TLS handshake, it'd be better not to print them at all.

**Closed** 2020-10-07 13:50 UTC
Labels: A-kv-server, C-question, O-support, S-3-ux-surprise
