### ISSUE TITLE
sql: RandomSyntax test timeout due to a corruption when dropping a column involved in concurrent mutation

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#61500] opened 2021-03-04 20:32 UTC
Adding a column seems to have timed out and caused RandomSyntax tests to fail.

See https://teamcity.cockroachdb.com/viewLog.html?buildId=2744772&buildTypeId=Cockroach_Nightlies_RandomSyntaxTests&tab=buildLog&branch_Cockroach_Nightlies=release-20.2&_focus=15395

```
timeout: "ALTER TABLE ident.ident ADD PUBLICATION TIME [ ]".

currently executing: map[
  ALTER TABLE ident.ident ADD COLUMN IF NOT EXISTS EXTRACT_DURATION CHAR ( 304 ) ARRAY [ 497 ]:1
  ALTER TABLE ident.ident ADD COLUMN IF NOT EXISTS GEOGRAPHY INTERVAL [ ]:1
  ALTER TABLE ident.ident ADD PUBLICATION TIME [ ]:1
  ALTER TABLE ident.ident ALTER COLUMN ident SET NOT NULL:1
  ALTER TABLE ident.ident DROP COLUMN IF EXISTS TEMP RESTRICT:1
  ALTER TABLE ident.ident DROP COLUMN IF EXISTS ident:1
  ALTER TABLE ident.ident DROP IF EXISTS CHARACTERISTICS CASCADE:1
  ALTER TABLE ident.ident DROP VARBIT RESTRICT:1
]
panic: statement exec timeout```

**Comment by ajwerner** [comment] 2021-03-09 18:48
I love randomized testing :p

```
ALTER TABLE ident.ident ALTER COLUMN "string" DROP NOT NULL
ALTER TABLE ident.ident DROP COLUMN IF EXISTS "string" CASCADE
```

There's a rename in there but it's not important. What's fun here is that we are trying to validate a condition on a table but then a subsequent user transaction moved the column out of public which makes the validation query. @vy-ton this is a quintessential example of a bug caused by allowing concurrent schema changes to queue but not thinking hard enough about how that could work. The later `DROP COLUMN` breaks the `DROP NOT NULL` and leads to a permanent corruption.

**Comment by vy-ton** [comment] 2021-03-09 21:24
Ideally, shouldn't the later `DROP COLUMN`have no impact until the `DROP NOT NULL` is complete?

I get confused when we refer to this as queuing because that implies waiting until the current schema change is finished. But it sounds like both schema changes have concurrent side effects on the system?

**Comment by ajwerner** [comment] 2021-03-09 21:54
I worry that I've failed to explain the way that the current system works well and that that has been a source of confusion. Schema changes are decomposed into steps. The first step gets run in the user transaction. The way that we know about the steps are through a concept called mutations. Mutations live on the descriptor. Jobs reference mutations. Mutations also, for better or for worse, encapsulate some state in the descriptor. When we run that first step, we do it relative to the "current" state of the descriptor. 

For example:

```
ALTER TABLE ... ALTER COLUMN ... DROP NOT NULL
```
might lead to the below descriptor (pseudo-code)
```
TableDescriptor{
   MutationJobs: []{{JobID: ..., MutationID: 1}
   Mutations: []{
     {MutationID: 1, DropConstraint:..., State: DeleteAndWriteOnly}
  } 
}
```

Note that the above statement will block until it finishes because it waits for the job to process the corresponding mutation.

Now, say from a different connection we come along and want to drop that column:

```
TableDescriptor{
   MutationJobs: []{{JobID: ..., MutationID: 1}
   Mutations: []{
     {MutationID: 1, DropConstraint:..., State: DeleteAndWriteOnly}
     // the existence of this mutation makes the column now not visible
     {MutationID: 2, DropColumn:..., State: DeleteAndWriteOnly} 
  } 
}
```
In this way the drop column both has had a side effect and is queued. All of this logic sort of grew organically -- I'm not totally convinced there was a lot of thought put into it. The main reason I think it existed was if you were to run both of those statements in the same transaction then you'd end up with something like:

```
TableDescriptor{
   MutationJobs: []{{JobID: ..., MutationID: 1}
   Mutations: []{
     {MutationID: 1, DropConstraint:..., State: DeleteAndWriteOnly}
     // the existence of this mutation makes the column now not visible
     {MutationID: 1, DropColumn:..., State: DeleteAndWriteOnly} 
  } 
}
```
But the above code works just because of some special cases.

Part of the reason all of this gets tricky is that the second statement could have been in an explicit transaction. We could have dropped the column and then tried to insert into the table. Today we don't show that column. The reason we feel okay not showing that column (on some level), is that by the time we commit we are going to commit a version of the descriptor which does not have that column. That also is probably broken.

In short, today we have no way of talking about queuing without talking about some side-effects. 

----

I do understand a perspective that all of this is in the weeds. My strong feeling, which may be a point of contention, is that it's crazy to accept and commit some DDL operation if some concurrent operation is going to make it invalid. In a transactional world that surely will be wrong. In the short term we should just work towards sanity. 

----

None of that has anything to do with this particular bug. This particular bug is sad but the solution, I think, is to just move on and not explode if the column has been dropped. The failure of an earlier mutation does not effect the code from attempting the later mutation even if setting up the later mutation assumed the existence or success of the earlier mutation. We just hope and pray we have sane error handling and state checking. We know from experience that we do not. That's a part of the reason we're rewriting all of this.

**Comment by ajwerner** [comment] 2021-03-09 22:03
@fqazi it seems like you're tearing through issues at a good clip and I haven't yet figured out the right way to schedule the new stuff. This one will give you some intuition for some of the existing problems both in terms of state management and coordination.

Especially interesting will be if you look at cases where we have:

```
CREATE TABLE t (i INT PRIMARY KEY, j INT)
INSERT INTO t VALUES (1, 1)
BEGIN
    ALTER TABLE t ALTER COLUMN j SET NOT NULL;
    ALTER TABLE t ADD COLUMN k INT NOT NULL DEFAULT 42 UNIQUE;
COMMIT;
```
The pause the schema change job above after it backfills the unique index (or also after it does the column backfill). Then run `ALTER TABLE t DROP COLUMN j`. Right now we'll explode unrecoverably. What's interesting is what happens to the unique index on `k` or more generally on `k`. I think it's sane for this fail out `k`. Now, also interesting, is if this later transaction does stuff involving `j`.

```
BEGIN;
    ALTER TABLE t DROP COLUMN j;
    ALTER TABLE t ALTER COLUMN k SET NOT NULL;
COMMIT
```

Now, my guess is that this will fail but I don't even know what the final state of `j` is going to be.

**Comment by ajwerner** [comment] 2021-03-09 22:18
Grr this just straight up duplicates https://github.com/cockroachdb/cockroach/issues/47719. I'm going to close this one.

**Closed by ajwerner** 2021-03-09 22:18 UTC
Labels: A-schema-changes, C-bug

**Comment by vy-ton** [comment] 2021-03-09 22:30
@ajwerner I see you closed this issue as a duplicate but I wanted to close out the discussion.

> I worry that I've failed to explain the way that the current system works well and that that has been a source of confusion.

FYI, I don't think this has happened. This is all fairly complex especially in the ways an end-user might see in error scenarios. While this info might be in the weeds, it does help me understand things more.

> My strong feeling, which may be a point of contention, is that it's crazy to accept and commit some DDL operation if some concurrent operation is going to make it invalid. 

I think it's important to distinguish whether the concurrent operation is DML or DDL. In the case we've discussed of adding a constraint, failing the DDL because a concurrent DML makes the DDL invalid seems reasonable. I'm less confident about failing a DDL because of a concurrent DDL, which is the case above.

> In short, today we have no way of talking about queuing without talking about some side-effects.

Can we discuss in the context of no queuing with the new schema changer. When a user executes the later `DROP COLUMN`, my understanding is the second descriptor above would not even get created and the user would get an error (maybe a retryable one).

**Comment by ajwerner** [comment] 2021-03-09 22:34
> In the case we've discussed of adding a constraint, failing the DDL because a concurrent DML makes the DDL invalid seems reasonable. I'm less confident about failing a DDL because of a concurrent DDL, which is the case above.

There don't need to be any concurrent DMLs to hit these bugs. 

> Can we discuss in the context of no queuing with the new schema changer. When a user executes the later DROP COLUMN, my understanding is the second descriptor above would not even get created and the user would get an error (maybe a retryable one).

What would happen is that the `DROP COLUMN` would wait for the constraint to finish and then it would proceed without an error.
