### ISSUE TITLE
Sentry: memo.go:488: cannot overwrite × /  (243.019999) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129763] opened 2024-08-28 00:34 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5764992863/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5764992863/?referrer=webhooks_plugin)

Panic Message:

```
memo.go:488: cannot overwrite × /  (243.019999) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).SetBestProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:488
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:819
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:275
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).reuseMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:557
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:785
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:809
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2291
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1841
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1174
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:146
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3429
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:251
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2421
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2423
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2238
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:963
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommands
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:253
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).serveImpl.func4
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:1036
  | runtime.goexit
  | 	src/runtime/asm_amd64.s:1695
Wraps: (3) cannot overwrite × /  (243.019999) with × /  (×)
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: cannot overwrite × /  (243.019999) with × /  (×)
memo.go:488: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[src/runtime/asm_amd64.s#L1694-L1696](src/runtime/asm_amd64.s#L1694-L1696)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/pgwire/server.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/pgwire/server.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/pgwire/conn.go#L252-L254](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/pgwire/conn.go#L252-L254)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L962-L964](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L962-L964)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2237-L2239](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2237-L2239)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2422-L2424](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2422-L2424)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2420-L2422](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor.go#L2420-L2422)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L3428-L3430](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L3428-L3430)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L145-L147](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L145-L147)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1173-L1175](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1173-L1175)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1840-L1842](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L1840-L1842)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/conn_executor_exec.go#L2290-L2292)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L250-L252)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L808-L810)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L784-L786)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L556-L558](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/plan_opt.go#L556-L558)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L274-L276](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L274-L276)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L818-L820](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/xform/optimizer.go#L818-L820)
[https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/memo.go#L487-L489](https://github.com/cockroachdb/cockroach/blob/953d09cce5a01cc0053e138516d80a27454f027c/pkg/sql/opt/memo/memo.go#L487-L489)
</details>

```
src/runtime/asm_amd64.s in runtime.goexit at line 1695
pkg/sql/pgwire/server.go in pkg/sql/pgwire.(*Server).serveImpl.func4 at line 1036
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommands at line 253
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 963
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2238
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2423
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func2 at line 2421
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execPortal at line 251
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3429
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 146
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1174
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1841
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2291
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 251
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 809
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).fetchPreparedMemoLegacy at line 785
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).reuseMemo at line 557
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 275
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 819
pkg/sql/opt/memo/memo.go in pkg/sql/opt/memo.(*Memo).SetBestProps at line 488
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.0 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.0 |
| Cockroach SHA | 953d09cce5a01cc0053e138516d80a27454f027c |
| # of CPUs | 4 |
| # of Goroutines | 467 |

Jira issue: CRDB-41699

**Comment by rytaft** [comment] 2024-09-10 14:27
Duplicate of #116022

**Closed by rytaft** 2024-09-10 14:27 UTC
Labels: C-bug, X-duplicate, O-sentry, branch-release-24.2
