### ISSUE TITLE
distsql: panic in hashjoiner due to uninitialized EvalContext(?)

### ISSUE THREAD

**Issue by justinj** [cockroachdb/cockroach#22264] opened 2018-01-31 19:56 UTC
Only had a bit of time to experiment with this one, seems like a nil pointer in the cast, although strangely I don't seem to get an explicit stack trace when I run this query, my database just stops running. Seems like the EvalContext is lacking a `Planner` field at that point.
```
DROP DATABASE IF EXISTS t;
CREATE DATABASE t;
USE t;
CREATE TABLE d (id INT PRIMARY KEY, str STRING);
CREATE TABLE e (id INT PRIMARY KEY, did INT REFERENCES d (id), str STRING);
INSERT INTO d VALUES (4, 'abc');
INSERT INTO e VALUES (5, 4, 'abc');
SELECT e.str FROM e INNER JOIN d on (e.str::REGCLASS = d.str::REGCLASS);
```

Found while investigating #22249, but seems to be distinct from that from what I could tell (though possibly related).

Stack trace:
```
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.performCast(0xc421975040, 0x6695dc0, 0xc420f88900, 0x667d460, 0x68a3d00, 0x0, 0x0, 0x668d480, 0x0)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2899 +0x63d
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*CastExpr).Eval(0xc420bb5180, 0xc421975040, 0xc420bb5180, 0x668d480, 0xc420bb5180, 0x4ab33f9)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2475 +0xe3
github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*ComparisonExpr).Eval(0xc4219a6780, 0xc421975040, 0xc420a3af90, 0x30, 0x6695dc0, 0xc420968800)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/sem/tree/eval.go:2998 +0x7a
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.RunFilter(0x668d600, 0xc4219a6780, 0xc421975040, 0xc422240330, 0x0, 0x1)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/expr_filter.go:26 +0x48
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*exprHelper).evalFilter(0xc4221183d0, 0xc422240300, 0x2, 0x2, 0xc420a3af90, 0x1, 0x1)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/expr.go:154 +0x97
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*joinerBase).render(0xc422118000, 0xc420a3af60, 0x1, 0x1, 0xc420a3af90, 0x1, 0x1, 0x0, 0x0, 0x66905a0, ...)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/joinerbase.go:234 +0x29f
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).probeRow(0xc422118000, 0x6685fe0, 0xc420a3af30, 0xc420a3af60, 0x1, 0x1, 0x668a840, 0xc421a87b00, 0x4694300, 0x0, ...)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:542 +0x283
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).probePhase(0xc422118000, 0x6685fe0, 0xc420a3af30, 0x668a840, 0xc421a87b00, 0x0, 0x0, 0x0)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:636 +0x1c3
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Run(0xc422118000, 0xc42011c7d8)
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:257 +0xcaf
created by github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Start
 /Users/justin/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:466 +0x3c5
```

Assigning to @arjunravinarayan for triage.

**Comment by knz** [comment] 2018-01-31 20:13
cc @andreimatei

**Comment by andreimatei** [comment] 2018-01-31 20:17
this issue doesn't contain the panic :)

**Comment by justinj** [comment] 2018-01-31 21:26
For some reason that is unclear to me I don't get a stack trace when I run the given queries against a running Cockroach instance, but I do get it when I run a logic test, so I've edited that into the first post.

**Comment by jordanlewis** [comment] 2018-03-04 17:30
This behaves differently now:

```
root@:26257/t> SELECT e.str FROM e INNER JOIN d on (e.str::REGCLASS = d.str::REGCLASS);
pq: cannot backfill such evaluated expression
```

**Comment by solongordon** [comment] 2018-03-06 15:11
@jordanlewis proposed just using local execution for queries like this, since they're mainly used for schema introspection. It looks simple enough to always recommend local execution for queries which include a cast to an OID type (like REGCLASS). Any objections to this approach?

**Comment by knz** [comment] 2018-03-06 15:15
Op 06-03-18 om 16:12 schreef solongordon:
> @jordanlewis <https://github.com/jordanlewis> proposed just using local
> execution for queries like this, since they're mainly used for schema
> introspection. It looks simple enough to always recommend local
> execution for queries which include a cast to an OID type (like
> REGCLASS). Any objections to this approach?

I like this. I think it's a good idea all around.


-- 
Raphael 'kena' Poss

**Comment by jordanlewis** [comment] 2018-03-06 15:18
👍 I think before this is closed we should also figure out what's up with that error message and fix it - it seems inappropriate for this context. Even if we always plan these with local SQL going forward, I'm nervous that there's a confused error message getting generated somewhere that will leak out in unexpected situations.

**Comment by solongordon** [comment] 2018-03-15 20:27
Should be all set for 2.0. Moving the milestone so I can come back and look into the error message more.

**Comment by solongordon** [comment] 2018-03-20 19:43
The `cannot backfill such evaluated expression` happens when `EvalContext.Planner` gets used during distributed execution. It looks to me like this only happens for built-ins, OID casts, and subqueries, which are all disabled for distsql, so I think we're OK here. I'll still look at improving the related error messages.

**Comment by jordanlewis** [comment] 2018-07-19 17:45
This will get closed by the upcoming local DistSQL work. The main `planner` will get passed to the gateway node's flow as its EvalPlanner, which sidesteps this issue.

**Comment by jordanlewis** [comment] 2018-08-14 18:02
Confirmed this is fixed.

**Closed by jordanlewis** 2018-08-14 18:02 UTC
Labels: A-sql-execution, C-bug, S-2-temp-unavailability
