### ISSUE TITLE
Test failure in CI build 5407

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1945] opened 2015-08-04 15:03 UTC
The following test appears to have failed:

[#5407](https://circleci.com/gh/cockroachdb/cockroach/5407):

```
W0804 15:02:16.565238 447 storage/store.go:584  error gossiping first range data: storage/replica.go:971: node is stopping
W0804 15:02:16.565795 447 storage/store.go:603  error gossiping configs: storage/replica.go:971: node is stopping
I0804 15:02:16.575039 447 storage/replica.go:988  gossiping cluster id  from store 3, range 1
I0804 15:02:16.575407 447 storage/replica.go:996  gossiping sentinel from store 3, range 1
I0804 15:02:16.575695 447 storage/replica.go:1000  gossiping first range from store 3, range 1
panic: test timed out after 5m0s

goroutine 25607 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14b8100, 0x19e5940, 0xba, 0xba, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:600 +0x477
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x8c
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x14c
FAIL	github.com/cockroachdb/cockroach/storage	300.064s
=== RUN TestBatchBasics
I0804 14:58:17.823623 493 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 14:58:17.824849 493 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN TestBatchGet
I0804 14:58:17.829271 493 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 14:58:17.829567 493 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0804 14:58:17.833313 493 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-08-04 15:45
Another dupe of #1928.

**Closed by tamird** 2015-08-04 15:45 UTC
Labels: test-failure
