### ISSUE TITLE
Test failure in CI build 9079

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3059] opened 2015-11-09 17:38 UTC
The following test appears to have failed:

[#9079](https://circleci.com/gh/cockroachdb/cockroach/9079):

```
I1109 17:37:40.650341 15966 acceptance/localcluster/localcluster.go:525  stopping
--- PASS: TestPut (36.51s)
=== RUN   TestRangeReplication
I1109 17:37:47.835726 15966 acceptance/localcluster/localcluster.go:211  started docker-spy: 172.17.0.29
I1109 17:37:47.835752 15966 acceptance/localcluster/localcluster.go:218  initializing cluster
panic: test timed out after 5m0s

goroutine 132 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0xb5f1d0, 0xf2d4c0, 0x8, 0x8, 0xa59d01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-11-13 20:02
dupe of #3025.

**Closed by tamird** 2015-11-13 20:02 UTC
Labels: test-failure
