### ISSUE TITLE
opt: explore using multiple indexes better for filters when they are available.

### ISSUE THREAD

**Issue by cucaroach** [cockroachdb/cockroach#70934] opened 2021-09-30 14:39 UTC
Inspired by support issue 1225.   Typically if we filter on two columns with indexes available as first column for both (but no index with both) we'll do something like:

```
filter
      │ filter: a = 'filterAval'
      │
      └── • index join
          │ table: foo@primary
          │
             └── • scan
                    table: foo@idx_colB
                    spans: ...
```

But wouldn't it be better in some cases to do something like:

```
└── • merge join
              ├── • scan
                    table: foo@idx_colA
                    spans: ...
              ├── • scan
                    table: foo@idx_colB
                    spans: ...
```

Depending on the data maybe a ZZ join would be better?

This issue is a TODO item to explore this idea some more with some real data.

Jira issue: CRDB-10297

**Comment by mgartner** [comment] 2023-05-31 13:35
Closing as a duplicate of #88997.

**Closed by mgartner** 2023-05-31 13:35 UTC
Labels: C-enhancement, T-sql-queries
