### ISSUE TITLE
SQL: test performance and success % of retries with and without savepoints

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#36249] opened 2019-03-27 22:18 UTC
We should compare the performance and likelihood of retry success with and without savepoints.

If users don't use savepoints, the first attempt of the transaction must fully abort and clean up after itself. if you use savepoints, the retry is linked to the original attempt and can use some of the original attempt's intents. this improves its chance of success on the second attempt (it's not exactly increasing the priority, it's more like holding a place in line)

Without savepoints perf, should be worse because you have to wait for it to fully abort and clean up plus reissue. And, with savepoints, perf is better bc you don't have to wait and bc it's more likely to succeed.

We've seen evidence that suggests that this theory might not hold up. We should investigate further.

**Comment by bdarnell** [comment] 2019-03-27 22:21
Dupe of #5935. We need to figure out whether this is still true.

**Closed by bdarnell** 2019-03-27 22:21 UTC
Labels: A-core-concurrency, A-sql-builtins, A-testing, C-investigation
