### ISSUE TITLE
kvserver: add tracing through Raft

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#104035] opened 2023-05-29 08:18 UTC
Currently, our tracing stops when we submit the proposal to Raft:

https://github.com/cockroachdb/cockroach/blob/da5be736ddb6579055b237b33c61024a3e4a0d70/pkg/kv/kvserver/replica_proposal_buf.go#L906-L909

And only resumes once the proposal is applied locally:

https://github.com/cockroachdb/cockroach/blob/939f9552e8c5787506f589094888f52fca667175/pkg/kv/kvserver/replica_application_decoder.go#L60-L61

It would be very useful to have trace events for the intermediate steps as well. In particular:

* Log append (on any replica).
* Submitted to send queue.
* Sent across the network.
* Received across the network.
* Submitted to the local Raft replica.
* Log read and/or entry cache read.

Because we control both the storage and network code, most of this can be done in CRDB code rather than etcd/raft, but we'll also need a couple of changes in upstream Raft. A rough sketch:

* A field on `raftpb.Entry` with arbitrary user metadata (in our case, the proposal ID from `ProposalData.idKey`).
* A mechanism to fetch the tracing context for a given proposal ID.
* A channel to propagate tracing information from and back to the caller, probably via `MsgApp` and `MsgAppResp`.

Jira issue: CRDB-28326
Epic: CRDB-37516

**Comment by erikgrinaker** [comment] 2023-10-09 09:30
In a past conversation with @tbg, he pointed out that there is already some infrastructure in place for propagating this and tracing through Raft, but I'm not familiar with the details. There will likely be some amount of research/archaeology to determine what infrastructure already exists.

**Comment by erikgrinaker** [comment] 2023-10-25 09:08
Adding O-support, since missing Raft tracing regularly hampers diagnosis of latency escalations.

**Comment by pav-kv** [comment] 2024-04-10 11:24
> there is already some infrastructure in place for propagating this and tracing through Raft, but I'm not familiar with the details

There are a [couple of fields](https://github.com/cockroachdb/cockroach/blob/911f1ce389342459592d89fe7b78bcba3a2d265a/pkg/raft/raftpb/raft.proto#L104-L108) in raft messages:

- an arbitrary context, which some [flows](https://github.com/cockroachdb/cockroach/blob/911f1ce389342459592d89fe7b78bcba3a2d265a/pkg/raft/raft.go#L999) use. Although we would have to be careful not to accidentally override it.
- a more recent addition is that requests can have an attached response, although these don't work across nodes.

Now that we've imported raft, we can modify the protocol more flexibly.

> A field on `raftpb.Entry` with arbitrary user metadata (in our case, the proposal ID from `ProposalData.idKey`).

An ideal ID would be `(term, index)` of the submitted entry. If it were that leaseholder==leader, we would get this ID at flushing to raft time. Unfortunately, we don't have this information exposed to the proposer, so extending `raftpb.Entry` might be the way in the short term.

**Comment by pav-kv** [comment] 2024-05-16 16:11
_<WIP, I'm updating this comment with more details later>_

Here are some key points in the raft entry lifetime, between evaluation on the leaseholder and confirming the entry is applied to the state machine. We want most of these events traced.

["propose" phase on the leaseholder]
1. From the [proposals](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/kv/kvserver/replica.go#L739) map, they get [inserted](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/kv/kvserver/replica_raft.go#L444) to the proposals [buffer](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/kv/kvserver/replica.go#L571-L584).
2. Later, the proposals buffer's `FlushLockedWithRaftGroup` builds the `raftpb.Entry` slices, and [steps](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/kv/kvserver/replica_proposal_buf.go#L1038-L1042) them into `raft.RawNode` as a `MsgProp` message.
	- If the raft instance is not the leader, it may (if this feature is enabled) [forward](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/raft/raft.go#L1607-L1616) the proposal message to the leader over network.

["propose" phase on the leader]

3. The leader may drop proposals on the floor, but most of the time it [appends](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/raft/raft.go#L1268) them to its log.
4. Eventually, the leader [broadcasts](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/raft/raft.go#L658-L667) the `raftpb.Entry`-s to followers with a `MsgApp` message.
5. In parallel, it also sends the entry to the local log storage via `Ready` call (the protocol is the same as on the follower below).

["accept" phase on a follower]

6. The `MsgApp` message is stepped, and the follower [appends](https://github.com/cockroachdb/cockroach/blob/021c72ae4a131bf511bff654fd3e4162947d3b15/pkg/raft/raft.go#L1661) the entry to the in-memory log.
    - It's possible that the follower's log is not up-to-date, in which case the below does not happen. Instead, there is a bit of back and forth with the leader until the log is caught up.
7. The entry is sent to local log storage via `Ready` call.
8. Once the storage confirmed storing the entry, the follower sends `MsgAppResp` to the leader.

["commit/apply" phase on the leader]

9. Once the leader collected a quorum of `MsgAppResp` covering an entry, the entry is committed.
10. The entry pops up via `Ready` call, in the `CommittedEntries` slice. Below the entry is applied to the state machine.
11. In parallel, the leader notifies the followers that the entry got committed.

["commit/apply" phase on the follower]

12. When the follower sees a commit index advancement, it returns newly committed entries via `Ready.CommittedEntries`.
13. The entries get applied to the state machine.

[on the leaseholder]

14. Once the leaseholder applied an entry that sits in the `proposals` map, it notifies the client.

Nuances:

- reproposals: there can be multiple `raftpb.Entry` submitted for a single proposal

**Comment by kvoli** [comment] 2024-05-20 21:12
A simple insert trace currently looks like:

![image](https://github.com/cockroachdb/cockroach/assets/39606633/1b5a82a9-69da-4e24-87d1-e66ba23cf226)


Or, with `vmodule=raft=1` to hit 

https://github.com/cockroachdb/cockroach/blob/ceb19c5b75cf4aa02c68a669122349a3e9aca33d/pkg/kv/kvserver/raft.go#L258-L258

![image](https://github.com/cockroachdb/cockroach/assets/39606633/da1bc943-a082-4311-983f-2bdf3df94ab0)

**Comment by kvoli** [comment] 2024-07-10 14:08
Un-assigning myself as I'm not actively working on this issue.

**Closed** 2024-10-18 22:11 UTC
Labels: C-enhancement, O-support, A-kv-replication, A-kv-observability, T-kv, P-3
