### ISSUE TITLE
Sentry: datum.go:5341: comparison of two different versions of enum %!s(func() string=0x14c7a00) oid ×: versions 105 and 104
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  ...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#137893] opened 2024-12-21 17:48 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/6167530494/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/6167530494/?referrer=webhooks_plugin)

Panic Message:

```
datum.go:5341: comparison of two different versions of enum %!s(func() string=0x14c7a00) oid ×: versions 105 and 104
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.(*DEnum).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/tree/datum.go:5341
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*KeyContext).Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:320
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.Key.Compare
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/key.go:111
  | github.com/cockroachdb/cockroach/pkg/sql/opt/constraint.(*Span).StartsAfter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/constraint/span.go:217
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:265
  | github.com/cockroachdb/cockroach/pkg/sql/opt/props.(*Histogram).Filter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/props/histogram.go:406
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3898
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3713
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3448
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).applyFilters
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:3336
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*statisticsBuilder).buildJoin
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/statistics_builder.go:1369
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*logicalPropsBuilder).buildJoinProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:484
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*logicalPropsBuilder).buildLookupJoinProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/logical_props_builder.go:534
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).MemoizeLookupJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go:21462
  | github.com/cockroachdb/cockroach/pkg/sql/opt/norm.(*Factory).ConstructLookupJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go:6563
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).generateLookupJoinsImpl.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:518
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:299
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*scanIndexIter).ForEach
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/scan_index_iter.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).generateLookupJoinsImpl
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:411
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*CustomFuncs).GenerateLookupJoins
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/join_funcs.go:259
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreInnerJoin
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:974
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroupMember
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go:30
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*explorer).exploreGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/explorer.go:180
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:532
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:295
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:574
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:519
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:295
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:574
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroup
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:519
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeExpr
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:295
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:574
Wraps: (3) comparison of two different versions of enum %!s(func() string=0x14c7a00) oid ×: versions 105 and 104
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: comparison of two different versions of enum %!s(func() string=0x14c7a00) oid ×: versions 105 and 104
datum.go:5341: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L518-L520](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L518-L520)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L573-L575)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L294-L296)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L531-L533](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/optimizer.go#L531-L533)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/explorer.go#L179-L181](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/explorer.go#L179-L181)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L29-L31](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L29-L31)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L973-L975](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go#L973-L975)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L258-L260](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L258-L260)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L410-L412](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L410-L412)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/scan_index_iter.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/scan_index_iter.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/scan_index_iter.go#L298-L300](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/scan_index_iter.go#L298-L300)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L517-L519](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/xform/join_funcs.go#L517-L519)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L6562-L6564](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go#L6562-L6564)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L21461-L21463](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go#L21461-L21463)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/logical_props_builder.go#L533-L535](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/logical_props_builder.go#L533-L535)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/logical_props_builder.go#L483-L485](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/logical_props_builder.go#L483-L485)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L1368-L1370](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L1368-L1370)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3335-L3337](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3335-L3337)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3447-L3449](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3447-L3449)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3712-L3714](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3712-L3714)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3897-L3899](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/memo/statistics_builder.go#L3897-L3899)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/props/histogram.go#L405-L407](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/props/histogram.go#L405-L407)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/props/histogram.go#L264-L266](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/props/histogram.go#L264-L266)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/span.go#L216-L218](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/span.go#L216-L218)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/key.go#L110-L112](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/key.go#L110-L112)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/key.go#L319-L321](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/opt/constraint/key.go#L319-L321)
[https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/sem/tree/datum.go#L5340-L5342](https://github.com/cockroachdb/cockroach/blob/74f60821a82c570ab58b8d7716c1d74b85e87df0/pkg/sql/sem/tree/datum.go#L5340-L5342)
</details>

```
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember at line 574
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeExpr at line 295
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 519
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember at line 574
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeExpr at line 295
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 519
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroupMember at line 574
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeExpr at line 295
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).optimizeGroup at line 532
pkg/sql/opt/xform/explorer.go in pkg/sql/opt/xform.(*explorer).exploreGroup at line 180
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreGroupMember at line 30
bazel-out/k8-opt/bin/pkg/sql/opt/xform/explorer.og.go in pkg/sql/opt/xform.(*explorer).exploreInnerJoin at line 974
pkg/sql/opt/xform/join_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).GenerateLookupJoins at line 259
pkg/sql/opt/xform/join_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).generateLookupJoinsImpl at line 411
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEach at line 202
pkg/sql/opt/xform/scan_index_iter.go in pkg/sql/opt/xform.(*scanIndexIter).ForEachStartingAfter at line 299
pkg/sql/opt/xform/join_funcs.go in pkg/sql/opt/xform.(*CustomFuncs).generateLookupJoinsImpl.func1 at line 518
bazel-out/k8-opt/bin/pkg/sql/opt/norm/factory.og.go in pkg/sql/opt/norm.(*Factory).ConstructLookupJoin at line 6563
bazel-out/k8-opt/bin/pkg/sql/opt/memo/expr.og.go in pkg/sql/opt/memo.(*Memo).MemoizeLookupJoin at line 21462
pkg/sql/opt/memo/logical_props_builder.go in pkg/sql/opt/memo.(*logicalPropsBuilder).buildLookupJoinProps at line 534
pkg/sql/opt/memo/logical_props_builder.go in pkg/sql/opt/memo.(*logicalPropsBuilder).buildJoinProps at line 484
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).buildJoin at line 1369
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFilters at line 3336
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyFiltersItem at line 3448
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).applyConstraintSet at line 3713
pkg/sql/opt/memo/statistics_builder.go in pkg/sql/opt/memo.(*statisticsBuilder).updateHistogram at line 3898
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).Filter at line 406
pkg/sql/opt/props/histogram.go in pkg/sql/opt/props.(*Histogram).filter at line 265
pkg/sql/opt/constraint/span.go in pkg/sql/opt/constraint.(*Span).StartsAfter at line 217
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.Key.Compare at line 111
pkg/sql/opt/constraint/key.go in pkg/sql/opt/constraint.(*KeyContext).Compare at line 320
pkg/sql/sem/tree/datum.go in pkg/sql/sem/tree.(*DEnum).Compare at line 5341
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.2.6 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.2.6 |
| Cockroach SHA | 74f60821a82c570ab58b8d7716c1d74b85e87df0 |
| # of CPUs | 8 |
| # of Goroutines | 1027 |

Jira issue: CRDB-45794

**Comment by annrpom** [comment] 2024-12-23 22:44
Dupe of https://github.com/cockroachdb/cockroach/issues/137895

**Comment by yuzefovich** [comment] 2024-12-23 22:58
dup of #129623

**Closed by yuzefovich** 2024-12-23 22:58 UTC
Labels: C-bug, O-sentry, X-blathers-triaged, T-sql-queries, branch-release-24.2
