### ISSUE TITLE
Support RETURNS TABLE for UDFs

### ISSUE THREAD

**Issue by DingDLu** [cockroachdb/cockroach#121515] opened 2024-04-01 23:12 UTC
ustomer uses UDFs and would like the resultset to be returned as a table and not as a list of tuples

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Jira issue: CRDB-37298

**Comment by DrewKimball** [comment] 2024-12-06 10:07
Dupe of #100226.

**Closed by DrewKimball** 2024-12-06 10:07 UTC
Labels: C-enhancement, T-sql-queries
