### ISSUE TITLE
sql: flaky drop_constraint_in_txn schema change logic test

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#40200] opened 2019-08-24 20:37 UTC
I've seen `schema_change_in_txn/drop_constraint_in_txn` fail intermittently on my PRs that should have nothing to do with the test. Here is the test output:
```
------- Stdout: -------
--- progress: testdata/logic_test/fk_opt: 517 statements/queries
--- done: testdata/logic_test/parallel_stmts_compat with config local: 93 tests, 0 failures
--- done: testdata/logic_test/union with config local: 48 tests, 0 failures
=== CONT  TestLogic/local/zero
=== CONT  TestLogic/local/with-opt
--- done: testdata/logic_test/zone_config with config local: 17 tests, 0 failures
--- total progress: 6842 statements/queries
=== CONT  TestLogic/local/with
                logic.go:1864: 
                    
                    testdata/logic_test/schema_change_in_txn:1688: 
                    expected success, but found
                    (40001) restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for tables: [{t2 116 5} {t 115 11}], old versions still in use
                logic.go:1278: 
                     pq: restart transaction: TransactionRetryWithProtoRefreshError: cannot publish new versions for tables: [{t2 116 5} {t 115 11}], old versions still in use
```
And the link to the build https://teamcity.cockroachdb.com/viewLog.html?buildId=1452932&buildTypeId=Cockroach_UnitTests.

**Comment by lucy-zhang** [comment] 2019-08-29 18:02
I opened a PR (#40337) to skip this part of the test for now.

**Comment by lucy-zhang** [comment] 2019-09-07 00:33
The comments in #40542 are correct in that this is unrelated to the closed timestamp-related test flakes.

The most minimal reproduction (with the fewest schema change jobs) I've been able to find is
```
statement ok
CREATE TABLE t (a INT)

statement ok
CREATE TABLE t2 (b INT PRIMARY KEY)

statement ok
ALTER TABLE t ADD CONSTRAINT fk FOREIGN KEY (a) REFERENCES t2

statement ok
ALTER TABLE t DROP CONSTRAINT fk

statement ok
ALTER TABLE t ADD CONSTRAINT fk_not_valid FOREIGN KEY (a) REFERENCES t2 NOT VALID

statement ok
BEGIN

statement ok
ALTER TABLE t DROP CONSTRAINT fk_not_valid

statement ok
COMMIT
```
(diff for repro: https://gist.github.com/lucy-zhang/a98dce2392a9ef389e9d0e7324f02a06)

I don't know what could be holding a lease on a descriptor two versions ago in a single-node logic test.

**Comment by lucy-zhang** [comment] 2020-08-27 14:33
Closing since we're not going to do anything about retry errors in explicit transactions in logic tests for the foreseeable future.

**Comment by lucy-zhang** [comment] 2020-08-27 14:34
Never mind, it's unclear why this is happening in `local`. We'll look at it but not soon.

**Closed** 2020-09-16 22:26 UTC
Labels: A-schema-changes, C-cleanup
