### ISSUE TITLE
sql: upgrade 1.1.5 -> 2.0.2 failed to run migration 

### ISSUE THREAD

**Issue by kmcrawford** [cockroachdb/cockroach#26422] opened 2018-06-05 13:41 UTC
I upgraded to a dev cluster from 2.0.2 from 1.1.5.  The upgrade didn't complete due to the following error:
`failed to run migration "upgrade table descs to interleaved format version": parentID 50 does not exist`  

I was able to rollback to 1.1.5 and can execute queries successfully. However, if I connect to the cluster using the cockroach client and set my database, then run `show tables;` I get` pq: no database with ID 50 found`.   I spoke to a developer this morning if he has seen anything strange with this instance and he told me things have been strange when he was updating a table and the internet when down before it could complete.  I'm not sure if this is what caused this, but I am unable to upgrade the cluster.

@benesch

**Comment by tschottdorf** [comment] 2018-06-05 13:48
@knz could you triage?

**Comment by knz** [comment] 2018-06-05 14:07
This can happen if a table descriptor lands in an invalid state, e.g. via a schema change.
In general the migrations should be tolerant of invalid table states.

**Comment by knz** [comment] 2018-06-05 14:07
@kmcrawford are you able to determine which specific table is causing the problem?

**Comment by kmcrawford** [comment] 2018-06-05 14:54
I am not.  I do see this in the console that is strange.

![image](https://user-images.githubusercontent.com/40531/40984004-db56174c-68ae-11e8-8248-92c6879703b0.png)

**Comment by knz** [comment] 2018-06-05 15:02
Yes this is helpful. thanks

**Comment by knz** [comment] 2018-06-05 15:03
@mjibson @vivekmenezes can you have a brief look, then we'll talk together to determine what is the best way to move forward (we need both to ensure that failed migrations don't leave bad descriptors around, and also make migrations more tolerant of bad descriptors).

Perhaps an opportunity to revive SCRUB too.

**Comment by benesch** [comment] 2018-06-05 15:36
> also make migrations more tolerant of bad descriptors

This scares me. The migration in question needs to ensure that every table has been upgraded to the latest format version. If some table descriptors fail to validate how can we be sure that the cluster is in a consistent state? In fact I think this is working as designed: the user is forced to stay on a version that is guaranteed to be able to handle the pre-migration state of the table descriptors.

Obviously it's a huge failing that we've managed to write a bad table descriptor—apologies, @kmcrawford!—but I'd prefer that we build tooling to repair the busted table descriptor rather than attempting to make the system tolerant of bad table descriptors.

**Comment by benesch** [comment] 2018-06-05 15:38
@kmcrawford could you run the following query and share the output?

```
SELECT * FROM crdb_internal.tables;
```

Unlike `SHOW TABLES` I believe `crdb_internal.tables` is tolerant of a missing parent database. You should see (at least) one row with a parent_id of 50. That's the invalid descriptor and it should give us some insight into what's gone wrong. In particular, if it's the `delivery.overrides` table that's showing up on the jobs page, it's very likely a bug in schema changes.

**Comment by vivekmenezes** [comment] 2018-06-05 15:52
can't imagine how this can happen but there is one case where this can happen. When you run DROP DATABASE, the database gets dropped and the tables linger around in the DROP state until the underlying data gets garbage collected. Such tables do not have parentID.

**Comment by kmcrawford** [comment] 2018-06-05 16:21
@benesch You are correct, and here is the infamous '50'
![image](https://user-images.githubusercontent.com/40531/40989162-f9242e24-68ba-11e8-9b9a-4f5ec20b93f4.png)

**Comment by knz** [comment] 2018-06-05 16:28
@benesch I think that a parent-less table should be considered a valid state for a descriptor. As Vivek states there are several known-good situations where this can happen. I suggest we relax the descriptor validation for this specific case.

**Comment by vivekmenezes** [comment] 2018-06-05 16:39
So on further looking at this, this problem is a combination of three things.

1. DROP database takes a long time to GC the underlying tables in the 1.1 release . Remember the implementation doesn't use ClearRange()
2. DROP tables being GC-ed do not show up in the jobs table.
3. The migration path is the only path that can modify a dropped table. After modifying the dropped table it calls validate on it which will fail.

I think the solution here is to not call validate on an upgrade to a dropped table.

**Comment by vivekmenezes** [comment] 2018-06-05 16:50
wait a minute @kmcrawford has reported that the table is in the PUBLIC state.

**Comment by knz** [comment] 2018-06-05 16:59
There might have been a bug in the 1.1 timeline e.g. #24888 (or some other bug which we haven't found yet).

In general:

1) migrations should be careful to assume less validity from non-public descriptors *anyway*
2) either migrations should tolerate some amount of descriptor badness "to tolerate current or past bugs in CockroachDB" **or** we must provide tools for users to fix their bad descriptors whenever a migration fails (e.g. SCRUB).

**Comment by vivekmenezes** [comment] 2018-06-05 17:31
@kmcrawford I'd appreciate if you provide us with the output of 

```select * from system.eventlog```

Thanks

**Comment by kmcrawford** [comment] 2018-06-05 17:56
@vivekmenezes during the upgrade I see only the following events. set_cluster_setting, alter_table, & finish_schema_change.

**Comment by vivekmenezes** [comment] 2018-06-05 18:34
@kmcrawford all such events are recorded in the eventlog table. I'd like to know how you landed up with two tables with the same name where both tables are in the PUBLIC state. These two tables were last modified in January and February (see the mod_time column above) so something happened then. Thanks!

**Comment by kmcrawford** [comment] 2018-06-05 19:27
@vivekmenezes apologies I though you were asking during the upgrade timeframe.  This is a busy table, let me try to find something about the overrides table during the timeframe specified.

**Comment by kmcrawford** [comment] 2018-06-05 19:45
@vivekmenezes Here are the modifications with overrides during the specified time frames

2018-01-30 21:24:12.865714+00:00 | alter_table | 76 | 1 | {"TableName":"overrides","Statement":"ALTER TABLE overrides ADD COLUMN delivery_fee FLOAT NOT NULL DEFAULT 2.99","User":"deliverysvc","MutationID":1,"CascadeDroppedViews":null}
-- | -- | -- | -- | --
2018-01-30 21:24:12.865714+00:00 | alter_table | 76 | 1 | {"TableName":"overrides","Statement":"ALTER TABLE overrides ALTER COLUMN delivery_fee DROP DEFAULT","User":"deliverysvc","MutationID":0,"CascadeDroppedViews":null}

2018-02-23 21:37:53.114525+00:00 | create_table | 91 | 3 | {"TableName":"overrides","Statement":"CREATE TABLE IF NOT EXISTS overrides (id SERIAL PRIMARY KEY, slot_id INT NOT NULL, effective_date TIMESTAMP NOT NULL, capacity INT NOT NULL, FOREIGN KEY (slot_id) REFERENCES time_slots)","User":"deliverysvc"}
-- | -- | -- | -- | --
2018-02-23 21:37:53.544675+00:00 | alter_table | 91 | 3 | {"TableName":"overrides","Statement":"ALTER TABLE overrides ADD COLUMN delivery_fee FLOAT NOT NULL DEFAULT 2.99","User":"deliverysvc","MutationID":1,"CascadeDroppedViews":null}
2018-02-23 21:37:53.544675+00:00 | alter_table | 91 | 3 | {"TableName":"overrides","Statement":"ALTER TABLE overrides ALTER COLUMN delivery_fee DROP DEFAULT","User":"deliverysvc","MutationID":0,"CascadeDroppedViews":null}
2018-02-23 21:37:54.034729+00:00 | finish_schema_change | 91 | 3 | {"MutationID":1}

**Comment by benesch** [comment] 2018-06-06 01:55
This is interesting. Thanks, @kmcrawford! I'm assuming you're using some sort of an ORM that syncs your database schema with models defined in code somewhere? Looks like it the schema change your ORM completed just fine on the second version of the overrides table, but not the first. Not sure if that's related to this bug, though.

Could you also search your event log for events relating to ID 50 and post the results? I think `SELECT * FROM system.eventlog WHERE target_id = 50` should do it.

**Comment by vivekmenezes** [comment] 2018-06-06 02:50
There are two issues here:

1. The table referencing a database that doesn't exist
2. the new and old table have an existing column backfill that hasn't yet terminated.

Fortunately I've been able to reproduce problem 2 and it's been fixed on master through https://github.com/cockroachdb/cockroach/commit/87c4b07903d057e7870c6a8e046d84076ea2ff32

When we run two schema changes in the same transaction, one that adds a default demanding a column backfill and the other that drops the default, a column backfill runs and hits an error. The 1.1 code treats this error as a temporary error and keeps retrying the schema change. The code on master treats this as a permanent error and drops the schema change.

```
statement ok
BEGIN

statement ok
ALTER TABLE add_default ADD fee FLOAT NOT NULL DEFAULT 2.99

statement ok
ALTER TABLE add_default ALTER COLUMN fee DROP DEFAULT

# an unexpected error which in 1.1 is treated as temporary error.
statement error got 0 values but expected 1
COMMIT

# on master this column has been purged correctly, but on 1.1 this column still exists and returns a "column is being added error"
statement error pgcode 42703 column "fee" does not exist
ALTER TABLE add_default DROP fee
```

We can port the change over to 1.1 which will at least shutdown the schema change jobs that have been running for 3-4 months on your cluster.

**Comment by vivekmenezes** [comment] 2018-06-06 14:27
I've stared at this for a while and there might be the possibility that after a DROP DATABASE we might (unable to reproduce) not drop a VIEW dependent on a table in the database, but I can't see how we wouldn't drop the tables in the database. 

@kmcrawford I'd appreciate it if we you can give us some output of ```SELECT * FROM system.eventlog WHERE target_id = 50``` thanks!

**Comment by kmcrawford** [comment] 2018-06-06 21:14
@vivekmenezes 

2017-10-17 17:35:26.956674+00:00 | create_database | 50 | 2 | {"DatabaseName":"delivery","Statement":"CREATE DATABASE delivery","User":"root"}
-- | -- | -- | -- | --
2018-02-26 15:42:46.881981+00:00 | drop_database | 50 | 1 | {"DatabaseName":"delivery_old","Statement":"DROP DATABASE delivery_old CASCADE","User":"root","DroppedTablesAndViews":["goose_db_version","store_rules"]}

**Comment by vivekmenezes** [comment] 2018-06-07 16:39
I think we can conclude that we have a bug in DROP DATABASE . I'll keep looking into this.

**Comment by knz** [comment] 2018-06-12 08:55
I'd like to gently push for decoupling the (possible) problems with drop database and the progress of mutations. Regardless of the specific cause, mutations should be tolerant and/or users should have a way forward. The solution is either to make mutations tolerant or provide a tool to fix the broken schema.

Would #26543 help? I could prepare a patch and have it back-ported for 2.0.x.

**Comment by knz** [comment] 2018-06-12 08:55
@vivekmenezes please advise what is your preference.

**Comment by vivekmenezes** [comment] 2018-06-12 15:08
@knz I think the minimum we can do here is to not do the descriptor validation for the parent id so that these headless descriptors do not prevent an upgrade. This will at lease unblock the upgrade process. Thoughts?

**Comment by knz** [comment] 2018-06-12 15:12
I would recommend running the validation but with a boolean to accept a parent-less table.

**Comment by benesch** [comment] 2018-06-12 16:02
I'm not sure that #26543 would help: won't `DROP TABLE [50]` try to validate the descriptor before it drops it?

There is a third option:

```
DELETE FROM system.descriptor WHERE id = 50;
DELETE FROM system.namespace WHERE id = 50;
```

**Comment by vivekmenezes** [comment] 2018-06-18 02:03
I'm going to be working on this issue tomorrow.

**Comment by vivekmenezes** [comment] 2018-06-20 17:45
The upgrade to the next 2.0 release 2.0.4 (due mid July) should succeed.

**Comment by vivekmenezes** [comment] 2018-07-24 16:39
@kmcrawford release 2.0.4 is out

**Comment by vivekmenezes** [comment] 2018-09-20 02:31
We were not able to reproduce the dangling database reference for the table. Closing until it is reproducible.

**Closed** 2018-09-20 02:31 UTC
Labels: A-schema-descriptors, C-bug, S-1-stability
