### ISSUE TITLE
ERROR: no builtin aggregate for SUM_INT on [unknown]

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#83874] opened 2022-07-06 00:32 UTC
**Describe the problem**

An error was encountered when using NULL in `sum_int` function.

**To Reproduce**

```sql
SELECT sum_int(NULL+1); --ERROR: no builtin aggregate for SUM_INT on [unknown]
```

**Expected behavior**
No error.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [02dcb3816c4148ee15318a614901b266f1b8ae34]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-17325

**Comment by mgartner** [comment] 2022-07-06 22:23
To start, we should probably make the error match that of `sum`:

```
defaultdb> select sum(NULL+1);
ERROR: ambiguous call: sum(unknown), candidates are:
sum(float) -> float
sum(decimal) -> decimal
sum(interval) -> interval
sum(int) -> decimal
SQLSTATE: 42725
```

Ideally, `sum_int` wouldn't exist. It's only necessary because `sum(int)` returns a decimal rather than an integer.

**Comment by mgartner** [comment] 2024-01-02 16:59
> To start, we should probably make the error match that of sum:

I don't think this last comment of mine is quite right. It won't have the same error message because there is only one overload for `sum_int`.

To match Postgres's behavior here, we need to match Postgres's function resolution logic, which is tracked in #75101. I'm going to close this as a duplicate of that.

**Closed by mgartner** 2024-01-02 16:59 UTC
Labels: C-bug, O-community, T-sql-queries, no-issue-activity
