### ISSUE TITLE
Test failure in CI build 6938

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2367] opened 2015-09-04 18:57 UTC
The following test appears to have failed:

[#6938](https://circleci.com/gh/cockroachdb/cockroach/6938):

```
W0904 18:55:04.302783 963 storage/store.go:608  error gossiping configs: storage/replica.go:976: node is stopping
W0904 18:56:04.301780 963 storage/store.go:627  error gossiping system config: storage/replica.go:976: node is stopping
I0904 18:56:04.302262 963 storage/replica.go:996  gossiping cluster id  from store 1, range 1
W0904 18:56:04.302683 963 storage/store.go:589  error gossiping first range data: storage/replica.go:976: node is stopping
W0904 18:56:04.302905 963 storage/store.go:608  error gossiping configs: storage/replica.go:976: node is stopping
panic: test timed out after 5m0s

goroutine 2683 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14cff60, 0x1a48840, 0xba, 0xba, 0x125ba01)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:624 +0x447
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8200c6120, 0xc820482660)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.042s
=== RUN   TestBatchBasics
I0904 18:51:57.259529 949 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0904 18:51:57.263162 949 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0904 18:51:57.268869 949 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-06 13:32
dupe of #2363.

**Closed by tamird** 2015-09-06 13:32 UTC
Labels: test-failure
