### ISSUE TITLE
ui: decommissioned nodes are still plotted in graphs

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#19541] opened 2017-10-25 20:44 UTC
![image](https://user-images.githubusercontent.com/5076964/32022136-7bc925ea-b9a3-11e7-9c4b-870d98138e03.png)

The nodes with zero values were successfully decommissioned days ago. We shouldn't plot these nodes (unless they actually write timeseries data).

cc @dianasaur323 for triage. This is also something we should address sooner rather than later. Folks seem to be using decommissioning frequently.

**Comment by dianasaur323** [comment] 2017-10-25 20:47
GAWD! the decommissioning madness comes again! these are high up on our priority list for 1.2 bug fixes, and our bug fix stage is coming up in Nov.

**Comment by couchand** [comment] 2017-10-26 15:39
I wonder if this ties into #15609, which was the issue mentioned left over from #17553 for handling what seems to be the same concern?

**Comment by tschottdorf** [comment] 2017-10-30 16:26
Maybe, I'd leave both open though to make sure we're not missing one of them. You mean that the likely fix would fix both issues at the same time, right?

**Comment by couchand** [comment] 2017-11-06 21:32
I guess it could go either way.  We might say that decommissioned nodes should be plotted until their liveness record expires, which would mean this is a dupe of #15609.  Or, we could say that as soon as the node is decomissioned and dead they should be removed from the charts, so this is something new to implement.

I'm inclined to say that the charts should always have the same nodes that the node list shows, but it wouldn't take much for me to be persuaded otherwise.

**Comment by tschottdorf** [comment] 2017-11-06 21:39
> I'm inclined to say that the charts should always have the same nodes that the node list shows, but it wouldn't take much for me to be persuaded otherwise.

Making graph display predicated on the liveness record being "recent" SGTM. Having things disappear at different times will be confusing at best. Re: the dupe, works for me if the original issue is updated to reflect the problem described here.

**Comment by dianasaur323** [comment] 2017-11-14 20:25
Note: want to make sure not to remove nodes too quickly after decommissioning

**Comment by mrtracy** [comment] 2018-02-12 19:57
Note that the concern about removing decommissioned nodes to fast should now be resolved; we have separate states "Decommissioning" and "Decommissioned", which exactly capture the desire to keep around a decommissioning node while it is still technically alive.

However, this does not resolve the issue of *historical* data.  Removing a decommissioned node from graphs is based on current status; however, that would remove that node's data across all time spans.  That means if you view line-per-node graphs from a week ago, nodes that were alive then but decommissioned now won't appear.

**Comment by couchand** [comment] 2018-02-12 20:21
somewhere else (I can't remember where) we discussed this, and it was decided that it's more important to hide decommissioned nodes than to show historical data. I think it's unfortunate that this is the tradeoff we're talking about making, but hey, whatever.

**Closed** 2018-02-14 19:51 UTC
