### ISSUE TITLE
sql: shouldn't be able to drop cols depended on by computed cols

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#26305] opened 2018-05-31 23:56 UTC

**Comment by knz** [comment] 2018-06-04 07:57
Is this a regression? I distinctly remember asking @justinj to fix a similar issue just after computed cols were first implemented in the ramp-up to 2.0.

**Comment by bobvawter** [comment] 2018-06-04 15:49
Duplicate of #26045

**Closed by bobvawter** 2018-06-04 15:49 UTC
Labels: A-bulkio-schema-changes, C-bug
