### ISSUE TITLE
ui:why CockroachDB donot compatible to pg navicat ？

### ISSUE THREAD

**Issue by jake2009** [cockroachdb/cockroach#18529] opened 2017-09-17 10:08 UTC
this  is a feature request . [must-have]
I expect to see CockroachDB will compatible to a powerful ui tool .
I hope it is easy to learn to use CockroachDB .
If CockroachDB  have  a powerful ui tool , then it will be easy to learn ,to use .
Many people create a table by ui not by command .
Command is hard to remember，hard to use.

**Comment by dianasaur323** [comment] 2017-09-17 13:46
Thanks for your request @jake2009. This is similar to https://github.com/cockroachdb/cockroach/issues/15441. We unfortunately don't have building out a UI planned yet, but you could try Postico. We have heard some users have success there. If you hit any issues using it, please let us know.

**Comment by jordanlewis** [comment] 2017-09-17 17:15
Duplicate of #5583. Please follow that issue for updates on Navicat support.

**Closed by jordanlewis** 2017-09-17 17:15 UTC
