### ISSUE TITLE
circleci: failed tests (13914): TestDockerPHP 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4910] opened 2016-03-06 17:28 UTC
The following test appears to have failed:

[#13914](https://circleci.com/gh/cockroachdb/cockroach/13914):

```
I160306 17:27:29.690387 acceptance/replication_test.go:66  found 1 replicas
I160306 17:27:30.692228 acceptance/replication_test.go:66  found 1 replicas
I160306 17:27:31.693994 acceptance/replication_test.go:66  found 1 replicas
I160306 17:27:32.695757 acceptance/replication_test.go:66  found 1 replicas
I160306 17:27:32.796371 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestDockerPHP (27.11s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 1
=== RUN   TestPut
I160306 17:27:34.924598 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
....I160306 17:27:35.324606 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160306 17:27:35.668300 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.3
I160306 17:27:35.668348 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:66: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 20:38
Duplicate of #4894.

**Closed by petermattis** 2016-03-06 20:38 UTC
Labels: test-failure
