### ISSUE TITLE
circleci: failed tests: 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6047] opened 2016-04-13 19:33 UTC
The following test appears to have failed:

[#16279](https://circleci.com/gh/cockroachdb/cockroach/16279):

```

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:20
Duplicate of #6048

**Closed by bdarnell** 2016-04-23 14:20 UTC
Labels: Robot, test-failure
