### ISSUE TITLE
Intent count is negative

### ISSUE THREAD

**Issue by MBerhault** [cockroachdb/cockroach#1209] opened 2015-06-01 17:57 UTC
See both graph and query response.
![image](https://cloud.githubusercontent.com/assets/5901480/7919423/2ecaebe8-0866-11e5-89fa-5b361a549f91.png)

**Comment by tschottdorf** [comment] 2015-06-01 17:58
duplicate of #1189.

**Closed by tschottdorf** 2015-06-01 17:58 UTC
