### ISSUE TITLE
acceptance: expected 3 replicas, only found 2

### ISSUE THREAD

**Issue by irfansharif** [cockroachdb/cockroach#10056] opened 2016-10-18 17:41 UTC
The following test appears to have failed: [#4856](https://teamcity.cockroachdb.com/viewLog.html?buildId=33257&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Acceptance), [log](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=33257#_focus=240).

```
[Step 2/2] TestAdminLossOfQuorum (4m:04s)
[17:29:13][TestAdminLossOfQuorum] I161018 17:29:13.933964 23 acceptance/cluster/localcluster.go:283  creating docker network with name: cockroachdb_acceptance-81441079
[17:29:14][TestAdminLossOfQuorum] I161018 17:29:14.136804 23 acceptance/cluster/localcluster.go:315  Initializing Cluster AdHoc 3x1:
[17:29:14][TestAdminLossOfQuorum] {"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
[17:29:14][TestAdminLossOfQuorum] I161018 17:29:14.161406 23 acceptance/cluster/docker.go:107  ImagePull cockroachdb/builder:20160912-171706 already exists
[17:29:15][TestAdminLossOfQuorum] I161018 17:29:15.009769 23 acceptance/cluster/localcluster.go:634  creating certs (1024bit) in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822
[17:29:15][TestAdminLossOfQuorum] I161018 17:29:15.070255 23 acceptance/cluster/localcluster.go:418  creating docker container with name: roach-81441079-0
[17:29:15][TestAdminLossOfQuorum] I161018 17:29:15.619321 23 acceptance/cluster/localcluster.go:529  *** started roach-81441079-0 ***
[17:29:15][TestAdminLossOfQuorum]   ui:        https://127.0.0.1:37997
[17:29:15][TestAdminLossOfQuorum]   trace:     https://127.0.0.1:37997/debug/requests
[17:29:15][TestAdminLossOfQuorum]   logs:      /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-0/cockroach.INFO
[17:29:15][TestAdminLossOfQuorum]   pprof:     docker exec -it 232b9 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):8080/debug/pprof/heap)'
[17:29:15][TestAdminLossOfQuorum]   cockroach: [start --ca-cert=/certs/ca.crt --cert=/certs/node.crt --key=/certs/node.key --host=roach-81441079-0 --alsologtostderr=INFO --verbosity=1 --store=path=/data1.0 --log-dir=/logs/roach-81441079-0 --logtostderr=false]
[17:29:15][TestAdminLossOfQuorum] 
[17:29:15][TestAdminLossOfQuorum]   cli-env:   COCKROACH_INSECURE=false COCKROACH_CA_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/ca.crt COCKROACH_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.crt COCKROACH_KEY=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.key COCKROACH_HOST=127.0.0.1 COCKROACH_PORT=37997
[17:29:15][TestAdminLossOfQuorum] I161018 17:29:15.619421 23 acceptance/cluster/localcluster.go:418  creating docker container with name: roach-81441079-1
[17:29:16][TestAdminLossOfQuorum] I161018 17:29:16.081176 23 acceptance/cluster/localcluster.go:529  *** started roach-81441079-1 ***
[17:29:16][TestAdminLossOfQuorum]   ui:        https://127.0.0.1:37999
[17:29:16][TestAdminLossOfQuorum]   trace:     https://127.0.0.1:37999/debug/requests
[17:29:16][TestAdminLossOfQuorum]   logs:      /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-1/cockroach.INFO
[17:29:16][TestAdminLossOfQuorum]   pprof:     docker exec -it 8bc89 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):8080/debug/pprof/heap)'
[17:29:16][TestAdminLossOfQuorum]   cockroach: [start --ca-cert=/certs/ca.crt --cert=/certs/node.crt --key=/certs/node.key --host=roach-81441079-1 --alsologtostderr=INFO --verbosity=1 --store=path=/data2.0 --join=roach-81441079-0:26257 --log-dir=/logs/roach-81441079-1 --logtostderr=false]
[17:29:16][TestAdminLossOfQuorum] 
[17:29:16][TestAdminLossOfQuorum]   cli-env:   COCKROACH_INSECURE=false COCKROACH_CA_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/ca.crt COCKROACH_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.crt COCKROACH_KEY=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.key COCKROACH_HOST=127.0.0.1 COCKROACH_PORT=37999
[17:29:16][TestAdminLossOfQuorum] I161018 17:29:16.081273 23 acceptance/cluster/localcluster.go:418  creating docker container with name: roach-81441079-2
[17:29:16][TestAdminLossOfQuorum] I161018 17:29:16.554885 23 acceptance/cluster/localcluster.go:529  *** started roach-81441079-2 ***
[17:29:16][TestAdminLossOfQuorum]   ui:        https://127.0.0.1:38001
[17:29:16][TestAdminLossOfQuorum]   trace:     https://127.0.0.1:38001/debug/requests
[17:29:16][TestAdminLossOfQuorum]   logs:      /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-2/cockroach.INFO
[17:29:16][TestAdminLossOfQuorum]   pprof:     docker exec -it 040f5 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):8080/debug/pprof/heap)'
[17:29:16][TestAdminLossOfQuorum]   cockroach: [start --ca-cert=/certs/ca.crt --cert=/certs/node.crt --key=/certs/node.key --host=roach-81441079-2 --alsologtostderr=INFO --verbosity=1 --store=path=/data3.0 --join=roach-81441079-0:26257 --log-dir=/logs/roach-81441079-2 --logtostderr=false]
[17:29:16][TestAdminLossOfQuorum] 
[17:29:16][TestAdminLossOfQuorum]   cli-env:   COCKROACH_INSECURE=false COCKROACH_CA_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/ca.crt COCKROACH_CERT=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.crt COCKROACH_KEY=/home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/.localcluster.certs.735676822/node.key COCKROACH_HOST=127.0.0.1 COCKROACH_PORT=38001
[17:29:16][TestAdminLossOfQuorum] I161018 17:29:16.554920 23 acceptance/replication_test.go:55  waiting for first range to have 3 replicas
[17:29:17][TestAdminLossOfQuorum] I161018 17:29:17.557971 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:18][TestAdminLossOfQuorum] I161018 17:29:18.561039 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:19][TestAdminLossOfQuorum] I161018 17:29:19.564403 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:20][TestAdminLossOfQuorum] I161018 17:29:20.567488 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:21][TestAdminLossOfQuorum] I161018 17:29:21.570725 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:22][TestAdminLossOfQuorum] I161018 17:29:22.573905 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:23][TestAdminLossOfQuorum] I161018 17:29:23.576935 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:29:24][TestAdminLossOfQuorum] I161018 17:29:24.580065 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:33:17][TestAdminLossOfQuorum] I161018 17:33:17.269607 23 util/stop/stopper.go:353  stop has been called, stopping or quiescing all running tasks
[17:33:17][TestAdminLossOfQuorum] I161018 17:33:17.370078 23 acceptance/cluster/localcluster.go:700  stopping
[17:33:17][TestAdminLossOfQuorum] I161018 17:33:17.370296 8 acceptance/cluster/localcluster.go:603  event stream done, resetting...: net/http: request canceled
[17:33:17][TestAdminLossOfQuorum] I161018 17:33:17.696688 23 acceptance/cluster/localcluster.go:742  node 0: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-0/stderr.2016-10-18T17_33_17Z.log
[17:33:18][TestAdminLossOfQuorum] I161018 17:33:18.042452 23 acceptance/cluster/localcluster.go:742  node 1: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-1/stderr.2016-10-18T17_33_17Z.log
[17:33:18][TestAdminLossOfQuorum] I161018 17:33:18.346166 23 acceptance/cluster/localcluster.go:742  node 2: stderr at /home/agent/work/.go/src/github.com/cockroachdb/cockroach/pkg/acceptance/artifacts/acceptance/TestAdminLossOfQuorum-81441079/roach-81441079-2/stderr.2016-10-18T17_33_18Z.log
[17:33:18][TestAdminLossOfQuorum]   testing.go:117: acceptance/replication_test.go:83, condition failed to evaluate within 45s: expected 3 replicas, only found 2
[17:33:18][TestAdminLossOfQuorum]   testing.go:117: acceptance/replication_test.go:83, condition failed to evaluate within 45s: expected 3 replicas, only found 2
```

**Comment by tschottdorf** [comment] 2016-10-24 18:11
This seems new and introduced not too long before this commit. I'm seeing this fail on unrelated PRs based on current master, so it persists.

**Comment by tschottdorf** [comment] 2016-10-26 08:51
This is pretty rampant (seeing this a lot on my PRs), and it's a fairly fundamental problem, so I would be elated if someone took a look at it.

**Comment by tschottdorf** [comment] 2016-10-26 11:16
`make acceptance TESTS=BuildInfo TESTFLAGS='-v -count 50'` on the gceworker (osx is slow) finds this. Probably faster if you change that test to only do the initial replication and to then immediately os.Exit(0).

**Comment by petermattis** [comment] 2016-10-26 12:55
On my TODO list to track this down.

**Comment by tschottdorf** [comment] 2016-10-26 14:54
https://teamcity.cockroachdb.com/viewLog.html?buildId=36738&buildTypeId=Cockroach_UnitTests_Acceptance&tab=artifacts#!8ytppl1gmpfd

`TestBuildInfo` has the node's logs. I don't know if they help. Maybe you want to run acceptance tests at a high enough verbosity to gain insight as they happen.

**Comment by petermattis** [comment] 2016-10-27 00:35
I have so far been unable to reproduce this on my laptop, though I did get docker to hang. I'll try again tomorrow on a gceworker.

**Comment by petermattis** [comment] 2016-10-27 00:40
Btw, after disabling the guts of `testBuildInfoInner`, `TestBuildInfo` takes 7-10s to run which is about 10x slower than if you use local processes (ala the `zerosum` tool). Docker!

**Comment by petermattis** [comment] 2016-11-07 01:13
Duplicate of #10409.

**Closed by petermattis** 2016-11-07 01:13 UTC
