### ISSUE TITLE
circleci: failed tests: TestParallel 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8123] opened 2016-07-29 16:30 UTC
The following test appears to have failed:

[#20718](https://circleci.com/gh/cockroachdb/cockroach/20718):

```
I160729 16:26:14.852549 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160729 16:26:14.853589 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160729 16:26:14.855225 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
I160729 16:26:14.857318 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
2 parallel tests passed
--- FAIL: TestParallel (18.63s)
	<autogenerated>:31: Leaked goroutine: goroutine 37829 [chan receive]:
		google.golang.org/grpc/credentials.(*tlsCreds).ClientHandshake(0xc820cd05f8, 0xc820e8ddf0, 0xf, 0x7f8f43c47d20, 0xc820025a78, 0x4a6de0be3, 0x0, 0x0, 0x0, 0x0, ...)
			/go/src/google.golang.org/grpc/credentials/credentials.go:170 +0x4bd
		google.golang.org/grpc/transport.newHTTP2Client(0xc820e8ddf0, 0xf, 0x0, 0x0, 0xc820d05b00, 0x0, 0x0, 0x0, 0x0, 0x7f8f43bf5bf8, ...)
			/go/src/google.golang.org/grpc/transport/http2_client.go:134 +0x3e3
		google.golang.org/grpc/transport.NewClientTransport(0xc820e8ddf0, 0xf, 0x0, 0x0, 0xc820d05b00, 0x0, 0x0, 0x0, 0x0, 0x7f8f43bf5bf8, ...)
			/go/src/google.golang.org/grpc/transport/transport.go:373 +0x84
		google.golang.org/grpc.(*addrConn).resetTransport(0xc82098a5a0, 0xc820d5e401, 0x0, 0x0)
			/go/src/google.golang.org/grpc/clientconn.go:568 +0x5ba
		google.golang.org/grpc.(*addrConn).transportMonitor(0xc82098a5a0)
--
E160729 16:27:30.896675 storage/replica.go:1923  store=1:1 ([]=) range=7 [/Table/51-/Max): error executing raft command: storage/replica.go:1802: no-op on empty Raft entry
I160729 16:27:30.897189 stopper.go:408  quiesceing; tasks left:
1      storage/intent_resolver.go:352
I160729 16:27:30.899987 storage/engine/rocksdb.go:398  closing in-memory rocksdb instance
--- PASS: TestReacquireLeaseOnRestart (0.77s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	231.414s
I160729 16:23:53.290368 rand.go:76  Random seed: 9078957719547011403
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.03s)
=== RUN   TestFlowRegistry
--- PASS: TestFlowRegistry (0.30s)
=== RUN   TestOrderedSync
--- PASS: TestOrderedSync (0.00s)
=== RUN   TestJoinReader
I160729 16:23:53.626501 storage/engine/rocksdb.go:353  opening in memory rocksdb instance
W160729 16:23:53.652828 gossip/gossip.go:953  not connected to cluster; use --join to specify a connected node

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-07-30 15:21
Duplicate of #7793.

**Closed by petermattis** 2016-07-30 15:21 UTC
Labels: Robot, test-failure
