### ISSUE TITLE
dump command dramatically slower than insert

### ISSUE THREAD

**Issue by donbowman** [cockroachdb/cockroach#51116] opened 2020-07-08 02:51 UTC
**Describe the problem**

attached is a sql file to load. I load it into an in-memory (store type=mem) cockroachdb. This takes approximately 35s.
I then run dump. This takes approximately 46minutes.

If I use --echo-sql, nearly all of the time is spent trying to understand the schema. It appears to take <1min for the actual data dump, the other ~45 min is spent loading the schema of each table one by one.

**To Reproduce**

```
start-single-node --background --insecure --store=type=mem,size=10% --listen-addr=localhost:26257
cockroach sql --insecure < dump.sql
cockroach dump --insecure defaultdb > /tmp/dump.sql
```

**Expected behavior**

I expect in this case, a single-node, in memory, non-contended server, the dump performance to be on par w/ the load performance.

**Environment:**

```
cockroach version
Build Tag:    v20.1.0
Build Time:   2020/05/05 00:07:18
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.13.9
C Compiler:   gcc 6.3.0
Build SHA-1:  9d456b9ec82cbf9a740a092c0d9f56da48779689
Build Type:   release

```

**Additional context**

This is blocking ability to backup.

[dump.sql.gz](https://github.com/cockroachdb/cockroach/files/4888147/dump.sql.gz)

**Comment by donbowman** [comment] 2020-07-08 21:19
I am considering adding e.g. https://github.com/proullon/ramsql as a cache in the dump code, doing a fetch all of the crdb_internal into it, and then letting the normal dump logic work against that table.

**Comment by adityamaru** [comment] 2020-08-18 16:57
@donbowman did the above-linked work related to cleaning up of temp tables/sequences mitigate this issue? In which case I can close this issue 🙂

**Comment by donbowman** [comment] 2020-08-18 20:29
i don't know what the `above-linked` means?

the attached sql, on a clean db, shows the issue, was there a change made i should try?

**Comment by adityamaru** [comment] 2020-08-18 22:52
Apologies, I meant the issue referencing this one - https://github.com/cockroachdb/cockroach/issues/51219. I was going to wait for those changes to merge in before I revisited this issue to see if it had any positive impact on the performance. Let me reproduce and take a look.

**Comment by artificiosus** [comment] 2020-10-16 12:47
For more information, we run `cockroach dump mydatabase --dump-mode=both > dump-file.sql` nightly on our database.
When running v19.2.1 the runtime was always <1min.
Having just upgraded to v20.1.7 the runtime has increased to >30min.
Database size, or any other property, has not changed since the upgrade.

**Comment by dt** [comment] 2021-03-09 16:17
We deprecated text-based dump in 20.2 and the more performant and reliable binary BACKUP/RESTORE available to all non-enterprise users, and have removed `dump` of anything other than metadata in the upcoming 21.1, so closing this as wontfix for now.

**Closed by dt** 2021-03-09 16:17 UTC
Labels: C-bug, O-community, T-bulkio, X-blathers-triaged

**Comment by dt** [comment] 2021-03-10 14:26
@donbowman When we talked to some users about those kinds of long-term retention/archival requirements, what we heard was that for those use-cases, they often actually preferred  text-based exports to CSV or similar vendor and version neutral format, so along with making BACKUP free, we also made our parallel/distributed `EXPORT` to CSV command free as well. Does that sound like it might be at least partially useful for the situations you were considering?

**Comment by dt** [comment] 2021-03-10 15:54
Interesting. Our `dump` files were specifically _not_ always compatible with older versions than dumped them (e.g. if they used new features and syntax) and were not compatible with non-cockroach SQL like say postgresql due to including cockroach-specific features, so we didn't believe they often a lot of value for x-version or x-vendor migrations, compared to going to something version and platform agnostic like CSV, Avro, etc and then using that version/system's data importing support. 

fwiw, there's also still `cockroach sql -e "select * from mytbl' --format=inserts` > mydata.sql` for the rows themselves.

**Comment by rafiss** [comment] 2021-03-10 22:17
One more thing to add: for the schema use case with alembic, v21.1 will have a `SHOW CREATE ALL TABLES` SQL command that outputs the same info as `cockroach dump --dump-mode=schema`. https://github.com/cockroachdb/cockroach/issues/53488
