### ISSUE TITLE
sql: RETURNING clause should not prevent auto-commit txns

### ISSUE THREAD

**Issue by nvanbenschoten** [cockroachdb/cockroach#34504] opened 2019-02-01 23:20 UTC
We currently have an issue where RETURNING statements prevent implicit transactions from auto-committing. This means that we're not able to hit the 1PC fast-path. There's no fundemental reason why RETURNING columns should prevent a 1PC transaction, so there should be a nice win here.

```
root@:26257/defaultdb> create table kv (k int primary key, v int);
CREATE TABLE

# with inserts

root@:26257/defaultdb> set tracing = on; insert into kv values (1, 0); set tracing = off; show kv trace for session;
             timestamp             |       age       |                     message                      |                      tag                       | location |    operation     | span
+----------------------------------+-----------------+--------------------------------------------------+------------------------------------------------+----------+------------------+------+
  2019-02-01 23:15:25.277294+00:00 | 00:00:00.000658 | querying next range at /Table/69/1/1/0           | [n1,client=[::1]:53196,user=root,txn=65521b1e] |          | dist sender send |    5
  2019-02-01 23:15:25.277335+00:00 | 00:00:00.000699 | r63: sending batch 1 CPut, 1 EndTxn to (n1,s1):1 | [n1,client=[::1]:53196,user=root,txn=65521b1e] |          | dist sender send |    5
  2019-02-01 23:15:25.27817+00:00  | 00:00:00.001534 | fast path completed                              | [n1,client=[::1]:53196,user=root]              |          | flow             |    3
  2019-02-01 23:15:25.27821+00:00  | 00:00:00.001574 | rows affected: 1                                 | [n1,client=[::1]:53196,user=root]              |          | sql txn          |    1
(4 rows)

root@:26257/defaultdb> set tracing = on; insert into kv values (2, 0) returning v; set tracing = off; show kv trace for session;
             timestamp             |       age       |                         message                         |                      tag                       | location |    operation     | span
+----------------------------------+-----------------+---------------------------------------------------------+------------------------------------------------+----------+------------------+------+
  2019-02-01 23:15:44.125428+00:00 | 00:00:00.000476 | querying next range at /Table/69/1/2/0                  | [n1,client=[::1]:53196,user=root,txn=e9372883] |          | dist sender send |    6
  2019-02-01 23:15:44.125461+00:00 | 00:00:00.000509 | r63: sending batch 1 CPut to (n1,s1):1                  | [n1,client=[::1]:53196,user=root,txn=e9372883] |          | dist sender send |    6
  2019-02-01 23:15:44.125863+00:00 | 00:00:00.000911 | rows affected: 1                                        | [n1,client=[::1]:53196,user=root]              |          | sql txn          |    1
  2019-02-01 23:15:44.12591+00:00  | 00:00:00.000958 | querying next range at /Table/69/1/2/0                  | [n1,client=[::1]:53196,user=root,txn=e9372883] |          | dist sender send |   10
  2019-02-01 23:15:44.125926+00:00 | 00:00:00.000974 | r63: sending batch 1 EndTxn, 1 QueryIntent to (n1,s1):1 | [n1,client=[::1]:53196,user=root,txn=e9372883] |          | dist sender send |   10
(5 rows)

# with updates

root@:26257/defaultdb> set tracing = on; update kv set v = v + 1 where true; set tracing = off; show kv trace for session;
             timestamp             |       age       |                     message                     |                      tag                       | location |    operation     | span
+----------------------------------+-----------------+-------------------------------------------------+------------------------------------------------+----------+------------------+------+
  2019-02-01 23:17:01.950405+00:00 | 00:00:00.000529 | Scan /Table/69/{1-2}                            | [n1,client=[::1]:53196,user=root]              |          | table reader     |    7
  2019-02-01 23:17:01.950442+00:00 | 00:00:00.000566 | querying next range at /Table/69/1              | [n1,client=[::1]:53196,user=root,txn=a2d086be] |          | dist sender send |    9
  2019-02-01 23:17:01.950479+00:00 | 00:00:00.000603 | r63: sending batch 1 Scan to (n1,s1):1          | [n1,client=[::1]:53196,user=root,txn=a2d086be] |          | dist sender send |    9
  2019-02-01 23:17:01.950794+00:00 | 00:00:00.000918 | querying next range at /Table/69/1/1/0          | [n1,client=[::1]:53196,user=root,txn=a2d086be] |          | dist sender send |    5
  2019-02-01 23:17:01.950805+00:00 | 00:00:00.000929 | r63: sending batch 1 Put, 1 EndTxn to (n1,s1):1 | [n1,client=[::1]:53196,user=root,txn=a2d086be] |          | dist sender send |    5
  2019-02-01 23:17:01.951471+00:00 | 00:00:00.001595 | fast path completed                             | [n1,client=[::1]:53196,user=root]              |          | flow             |    3
  2019-02-01 23:17:01.951513+00:00 | 00:00:00.001637 | rows affected: 1                                | [n1,client=[::1]:53196,user=root]              |          | sql txn          |    1
(7 rows)

root@:26257/defaultdb> set tracing = on; update kv set v = v + 1 where true returning v; set tracing = off; show kv trace for session;
             timestamp             |       age       |                         message                         |                      tag                       | location |    operation     | span
+----------------------------------+-----------------+---------------------------------------------------------+------------------------------------------------+----------+------------------+------+
  2019-02-01 23:17:33.895528+00:00 | 00:00:00.000507 | Scan /Table/69/{1-2}                                    | [n1,client=[::1]:53196,user=root]              |          | table reader     |   12
  2019-02-01 23:17:33.895589+00:00 | 00:00:00.000568 | querying next range at /Table/69/1                      | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |   14
  2019-02-01 23:17:33.895618+00:00 | 00:00:00.000597 | r63: sending batch 1 Scan to (n1,s1):1                  | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |   14
  2019-02-01 23:17:33.895863+00:00 | 00:00:00.000842 | querying next range at /Table/69/1/1/0                  | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |    6
  2019-02-01 23:17:33.895885+00:00 | 00:00:00.000864 | r63: sending batch 1 Put to (n1,s1):1                   | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |    6
  2019-02-01 23:17:33.896114+00:00 | 00:00:00.001093 | rows affected: 1                                        | [n1,client=[::1]:53196,user=root]              |          | sql txn          |    1
  2019-02-01 23:17:33.896168+00:00 | 00:00:00.001147 | querying next range at /Table/69/1/1/0                  | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |   10
  2019-02-01 23:17:33.896182+00:00 | 00:00:00.001161 | r63: sending batch 1 EndTxn, 1 QueryIntent to (n1,s1):1 | [n1,client=[::1]:53196,user=root,txn=bc325662] |          | dist sender send |   10
(8 rows)
```

**Comment by nvanbenschoten** [comment] 2019-02-01 23:21
@jordanlewis suspects that this is because if anything but the insert/update/whatever plan node is the actual plan root the auto-commit won’t be enabled properly.

```
root@:26257/defaultdb> explain update kv set v = v + 1 where true returning v;
            tree           |  field   | description
+--------------------------+----------+-------------+
  render                   |          |
   └── run                 |          |
        └── update         |          |
             │             | table    | kv
             │             | set      | v
             │             | strategy | updater
             └── render    |          |
                  └── scan |          |
                           | table    | kv@primary
                           | spans    | ALL
(10 rows)

Time: 980µs

root@:26257/defaultdb> explain update kv set v = v + 1 where true;
         tree         |  field   | description
+---------------------+----------+-------------+
  count               |          |
   └── update         |          |
        │             | table    | kv
        │             | set      | v
        │             | strategy | updater
        └── render    |          |
             └── scan |          |
                      | table    | kv@primary
                      | spans    | ALL
(9 rows)
```

**Comment by jordanlewis** [comment] 2019-02-01 23:30
We have to watch out for #20847 - the naive way of doing this won't work. Only the top-level mutation can be the one to autocommit, I guess.

**Comment by nvanbenschoten** [comment] 2019-02-01 23:47
So is this just a matter of propagating the auto-commit setting through `render` and `run` nodes then? Or is that not ok because an arbitrary `render` can throw errors?

**Comment by knz** [comment] 2019-02-11 13:26
Guys I fear that in general it's not too reasonable to let a KV txn autocommit just because the mutation has finished executing. The SQL transaction engine should be responsible for this. Consider this:

```
with a as (insert into ... returning x)
select pg_sleep(200)  from a
```

If the user CANCELs the query the mutation must be cancelled too.
Even though there's "merely" just 1 render after it.

**Comment by knz** [comment] 2019-02-11 13:28
Personally I think the better design is to transform the implementation of mutation fast path so that the mutation code is not responsible for running the KV batch any more.

Instead it should complete its last batch, register it to the planner (or the exec context, whatever struct we use for "currently executing statment"), and say "I'm done executing, please commit this baby or abort if you want to"

Then let the executor actually complete and run the batch with an EndTxn if it determines the SQL txn is actually committing.

**Comment by nvanbenschoten** [comment] 2019-02-19 17:52
@knz that sounds reasonable to me, although we'd need to be careful in cases where plan nodes above the mutation code depend on the result of the mutation. Even if we don't flush the KV batch immediately, other parts of the query would still need to observe its effect.

The case you brought up again re-enforces that the ability to auto-commit is a global property of the query plan. That said, I don't see any problem with extending the cases where a plan can auto-commit to include top-level RETURNING clauses until we move to a different model. This would allow us to optimize away the transaction in a number of cases that we're seeing with customers.

I'm curious if/how this kind of thing differs in @andy-kimball's optimizer-based mutation code.

**Comment by andy-kimball** [comment] 2019-02-20 00:57
If this is a global property of the query plan, it might make sense to walk the `opt` tree rather than the `planNode` tree in order to determine if auto-commit is possible. While we have some issues with our `HasSideEffect` logical property, it's theoretically a better way to test whether there are problematic expressions that occur after mutation(s) have occurred.

**Comment by knz** [comment] 2019-02-20 12:40
Agreed with you andy
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jordanlewis** [comment] 2019-07-23 00:06
I think if we could assert that a query had no side-effecting renders and wasn't part of a subquery (or postquery), and additionally the tree contains no further mutations, we'd be good to go. 

By the way, I tested @knz's suggestion (with `pg_sleep`) in Postgres and confirmed that the database indeed does not commit the transaction if one cancels the query halfway through the sleep.

One question I have is what a huge result set equivalent should do in this case. Imagine something like:

```
INSERT INTO t SELECT a FROM huge_table RETURNING a
```

and imagine that the client consumes the first 10 rows and then cancels the query. Is it okay to have committed the transaction in this case? I think the answer is "yes", but if not, that certainly complicates the situation.

**Comment by andy-kimball** [comment] 2019-07-23 03:36
If a user sends a cancel request, then I think one of two outcomes should be permissible:
1. The engine cancels the query and replies to the cancel request.
2. The engine runs the query to completion and replies to the cancel request. Note that any buffered output that has not yet been fully returned to the client *may* be discarded.

What should not be permissible is sending a cancel request, and then getting a reply ack for it, even though the query has not yet been aborted/committed.

In the huge result case you give, #2 should be totally fine. As long as the transaction is committed, you can discard any pending rows.

**Comment by knz** [comment] 2019-07-23 08:33
First order business is to be careful about terminology. The pgwire protocol supports something called "cancel request" (a special message type) that is being "sent" by a client and "acknowledged" by the server, but this was out of scope from this issue so far (I will cover this below).

What we're talking about here (presumably, correct me if I'm wrong) is the following:

A. a client closes the connections before a request completes, or
B. a client uses the portal/cursor interfaces and closes/abort a portal before the full results have been received.

I am worried by the following query: a table  `tb` containing 10 rows, and do something like `insert into tb2(x) select x from tb returning x`, then close the conn after just 1 row has been received in the client. How many rows are there in tb2 in either situation A or B? What does pg say? (We should not use pg_sleep to analyze this as it muddies the results).

In situation A specifically, I guess we could *choose* to let a txn commit even if not all results are at the client yet, on the perhaps shaky ground that it's somewhat indistinguishable whether the results were "not yet computed" (the txn was onging and could be rolled back) or "they were in transit in the network" (after the txn had completed).

For situation B, this would be more complicated. 

What do you say about the following realistic, valid-in-pg architectural choice:
- a client issues a mutation using `WITH a AS (INSERT RETURNING) SELECT * FROM a`
- uses pgwire-level limit to only consume 1 row from the select, to "peek" at what the INSERT actually did (e.g. because the client is interested in the result of conflict detection, or perhaps there was a non-deterministic value in there and they want to see what it actually was)
- if the value is found to be "unsatisfying" cancels the txn

If you try to say "nobody is doing that!" I'd ask - how do you know? This is what you get with a conversational protocol and pgwire-level portal limits (which we're on the way to provide).

**Comment by knz** [comment] 2019-07-23 08:35
Separately, regarding cancel requests. 
Note that these in pg are issued asynchronously, "out of band" from query processing.
So here the situation is more simple: there is no way for a client to guarantee that a cancel request be received by the server before or after the txn that they want to cancel has committed. So for cancel requests (the pgwire message or the `pg_cancel` builtin) specifically we can do whatever.

**Comment by knz** [comment] 2019-07-23 08:38
> If you try to say "nobody is doing that!" I'd ask - how do you know? This is what you get with a conversational protocol and pgwire-level portal limits (which we're on the way to provide).

Also whatever answer we provide here, if it ends up becoming different from pg, we must be extra careful to make it *silently* different from pg -- i.e. not choose a behavior which causes a client oblivious to the difference to end up with bad data. In this case, for example a bad choice would be to silently commit the txn without any way for existing clients to notice.

**Comment by RaduBerinde** [comment] 2019-07-26 15:49
Talked with Jordan for a bit. We think the reasonable thing to do for now is to enable autocommit when the mutation is the root of the tree or is directly under a Project with no side-effects in its expressions.

Note that:
 - the mutation nodes only autocommit when the mutation is complete (all the input was consumed). If not enough rows were read from the mutation node, it doesn't happen.
 - Mutations under WITH will not allow autocommit; also, their output is buffered fully before the rest of the query runs.
 - Mutations under `[ .. ]` will be handled as if `WITH` was used.

**Closed** 2019-09-19 18:26 UTC
Labels: A-sql-mutations, C-performance
