### ISSUE TITLE
roachtest: weekly tests fail to publish artifacts

### ISSUE THREAD

**Issue by renatolabs** [cockroachdb/cockroach#82899] opened 2022-06-14 18:40 UTC
[Roachtest Weekly](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel?mode=builds) does not publish artifacts, making debugging a failure impossible. This has been the case for at least a couple of months now.

Example: https://github.com/cockroachdb/cockroach/issues/82779.

**Error message when trying to publish artifacts**

```
Publishing artifacts

[07:38:11 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5442458?buildTab=log&focusLine=13636&linesState=13636)    Collecting files to publish: [/go/src/github.com/cockroachdb/cockroach/artifacts/bazel-20220611-5442458/kv95/weekly/enc=false/nodes=32/run_1/** => kv95/weekly/enc=false/nodes=32/run_1]
[07:38:11 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5442458?buildTab=log&focusLine=13637&linesState=13637)    Artifacts path '/go/src/github.com/cockroachdb/cockroach/artifacts/bazel-20220611-5442458/kv95/weekly/enc=false/nodes=32/run_1/**' not found
```

[TeamCity link](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5442458?buildTab=log&expandAll=true&focusLine=13674)

This has potentially happened in the past, see @tbg's comment: https://github.com/cockroachdb/cockroach/issues/54570#issuecomment-707809302 (the same fix does not apply in this case as a similar `chmod` is already called in the weekly tests).

This issue only happens with weekly tests; nightly tests are able to publish their artifacts just fine. One potential difference to be noted is that the weekly tests write their artifacts in the `/go/src/...` directory, whereas the nightly tests do so in the agent's home directory.

Jira issue: CRDB-16718

**Comment by srosenberg** [comment] 2022-08-15 12:55
This was a mere configuration problem in TC; i.e., artifacts path was left unspecified. Artifacts are being uploaded as of recent runs, e.g., [1],

```
[08:42:13 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5991681?buildTab=log&focusLine=12847&linesState=12847)  + gsutil cp artifacts/bazel-20220806-5991681/kv95/weekly/enc=false/nodes=32/run_1/33.perf/stats.json gs://cockroach-nightly/artifacts/bazel-20220806-5991681/kv95/weekly/enc=false/nodes=32/run_1/33.perf/stats.json
[08:42:14 ](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5991681?buildTab=log&focusLine=12848&linesState=12848)  Copying file://artifacts/bazel-20220806-5991681/kv95/weekly/enc=false/nodes=32/run_1/33.perf/stats.json [Content-Type=application/json]...
```

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_RoachtestWeeklyBazel/5991681?buildTab=log&focusLine=3

**Comment by srosenberg** [comment] 2022-08-30 03:33
@renatolabs My bad, I misinterpreted/misread the type of artifact that wasn't being published. This is still an issue as we saw in the most recent failure [1]. There are essentially two types of artifacts that we need,

1. `stats.json` (histogram from roachperf)
2. test runner and cluster logs (plus system logs captured by `collectClusterArtifacts` on failure/timeout)

It turns out that this job was actually missing both types. I fixed 1) by setting the correct "Artifacts Path" (we use `%teamcity.build.checkoutDir%/artifacts` for all jobs afaik)[2]. I didn't realize that 2) was still an issue. Hence, I am reopening and reassigning to @herkolategan :)

[1] https://github.com/cockroachdb/cockroach/issues/86987
[2] https://github.com/cockroachlabs/teamcity-config/commit/a21a991135fd446f7be07c8373b508574918df91#diff-4caa0c02c06e6c188490b47f8ae43e6b6ed37110e97f3b1c3774155604e40d2cR7

**Comment by srosenberg** [comment] 2022-08-30 03:43
Note, we do have roachperf artifacts uploaded correctly. From the previous successful run,

```
gsutil ls -lr "gs://cockroach-nightly/artifacts/bazel-20220820-6166306/**"
   3681250  2022-08-24T08:41:50Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/kv0/weekly/enc=false/nodes=32/run_1/33.perf/stats.json
   6291082  2022-08-24T08:42:14Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/kv95/weekly/enc=false/nodes=32/run_1/33.perf/stats.json
   2355998  2022-08-24T08:42:00Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8000/stats.json
   2354794  2022-08-24T08:42:07Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8050/stats.json
   2356401  2022-08-24T08:42:02Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8150/stats.json
   2358099  2022-08-24T08:42:09Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8350/stats.json
   2365483  2022-08-24T08:42:05Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8550/stats.json
   2369713  2022-08-24T08:42:12Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8600/stats.json
   2347367  2022-08-24T08:42:10Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8650/stats.json
   2349114  2022-08-24T08:42:03Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/tpccbench/nodes=12/cpu=16/run_1/13.perf/warehouses=8750/stats.json
1328676787  2022-08-24T08:41:58Z  gs://cockroach-nightly/artifacts/bazel-20220820-6166306/weekly/tpcc/headroom/run_1/4.perf/stats.json
TOTAL: 11 objects, 1357506088 bytes (1.26 GiB)
```

As for the other type of artifacts, the issue is that this rather obscure CLI arg. `--artifacts-literal` [1] doesn't receive the correct value. It's intended to be an absolute path on the host file system of the agent, but instead it ends up being a path inside the docker container where roachtest is running,

```
--artifacts-literal=/go/src/github.com/cockroachdb/cockroach/artifacts/bazel-20220827-6260294
```

I'm sending a draft PR which effectively refactors the weekly scripts to be almost identical to the nightly ones. In fact, other than the `tag:weekly` and a couple of other CLI args, the invocation scripts should be exactly the same. We should consider refactoring further; I'll add a summary of simplifications below.

[1] https://github.com/cockroachdb/cockroach/blob/master/build/teamcity/cockroach/nightlies/roachtest_weekly_impl.sh#L53

**Comment by srosenberg** [comment] 2022-08-30 04:12
Summary of further improvements,

1. We should record the fact that it was a weekly roachtest that failed; i.e, `tag:weekly` is not reported under `Parameters` in [1]. This would minimize the chance of a dummy user (i.e., myself) to jumping to the wrong conclusions :)
2. The names of the weekly tests could be made more consistent to reflect that these are indeed weekly, i.e., long-running; cf. `weekly/tpcc/headroom` and `tpccbench/nodes=12/cpu=16/`.
3. I think we should either get rid of `literalArtifacts` [2] or at least rename it to make it more intuitive.

With respect to 3), it's effectively using a Team City (TC) service message [3] to publish artifacts as soon as they are available. That requires an absolute path on the host file system of the TC agent. However, `roachtest` is invoked via `run_bazel` which runs everything inside a docker container. The container has the following volume mapping,

```
/artifacts -> /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts
```

Thus, `roachtest` will write artifacts under `/artifacts` but somehow it needs to tell TC that it should publish the artifacts under `/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/`. Afaik, nothing prevents the identity mapping, i.e.,

```
/home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts -> /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts
```

Note the location of the artifacts directory on the host is known at runtime by `%teamcity.build.checkoutDir%/artifacts`. (This is a per job setting in TC, but we use the same for all the jobs afaik.)

[1] https://github.com/cockroachdb/cockroach/issues/86987#issue-1352988612
[2] https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/main.go#L85
[3] https://www.jetbrains.com/help/teamcity/service-messages.html#Publishing+Artifacts+While+Build+is+in+Progress

**Comment by srosenberg** [comment] 2022-08-31 01:07
Running `roachperf` locally and loading the last 30 days. The last successful run of `tpccbench` was August 20,

<img width="824" alt="tpccbench_weekly_12nodes_16cpu" src="https://user-images.githubusercontent.com/1616764/187570497-4b187404-867a-4e0f-9453-cdbc1c122e6a.png">

**Closed** 2022-10-12 10:21 UTC
Labels: C-bug, A-testing
