### ISSUE TITLE
ui: Inconsistent identification of nodes between list and details pages

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10365] opened 2016-11-01 15:19 UTC
On the node list page ("#/nodes/overview"), we appear to use hostnames to identify nodes:

<img width="1293" alt="screen shot 2016-11-01 at 11 06 47 am" src="https://cloud.githubusercontent.com/assets/7085343/19894764/8a15066c-a024-11e6-8ff3-581b1487cd85.png">

But once you click on one of the nodes ("#/nodes/3"), we start identifying it by its ID:

<img width="1054" alt="screen shot 2016-11-01 at 11 17 11 am" src="https://cloud.githubusercontent.com/assets/7085343/19894809/c5af1960-a024-11e6-9d19-a59e5c97b2e3.png">

Is there a reason for the inconsistency between the two? When I clicked through from the list page to a particular node's details, the change made me do a double take and retrace my steps to make sure I had clicked on the correct hostname.

@maxlang @kuanluo

**Comment by a-robinson** [comment] 2016-11-01 15:22
Also, on the list page, the nodes seem to be sorted by ID rather than by hostname, even though the hostname is what's displayed.

**Comment by kuanluo** [comment] 2016-12-08 22:14
Thanks for noticing this, @a-robinson! And sorry for the delayed reply. Between hostname and ID, which one would be better as a identifier? 

We should stick with one for sure.

**Comment by a-robinson** [comment] 2016-12-08 22:21
I don't personally have a strong preference. I'd probably lean slightly toward the host:port combo, especially since that's what's currently used in the "Graph" dropdown on the Cluster Overview page.

**Comment by kuanluo** [comment] 2016-12-08 22:43
Perhaps @dianasaur323 can weigh in here? 

We're discussing what identifier to display for the nodes across the admin ui. My hesitation around host:port is that it's too long, but not sure if we have anything better that's unique/short.

**Comment by dianasaur323** [comment] 2016-12-08 22:55
I think host:port is a familiar way of seeing nodes listed, so we should be good here with sticking with host:port

**Comment by kuanluo** [comment] 2016-12-08 22:58
Cool, thanks! 

@maxlang can you make sure the host:port naming convention is consistent throughout? Thanks!

**Comment by mrtracy** [comment] 2017-03-09 21:41
#12587 brings this into question: if a user creates a node on a host, destroys that node, and then creates another node on the same host, that new node will have a new node ID but the same host/port combination - host/port is *not* guaranteed to be unique in this situation.

I share the opinion that host/port is better in general because it is more recognizable to administrators, but the situation in #12587 may not be rare for developers setting up a new cluster; do we need to use something like host:port(nodeID) instead?

**Comment by a-robinson** [comment] 2017-03-09 22:00
Or just have separate columns for ID and hostname if we're always going to display both.

I agree with your take on the situation though. Host/port seems better in general but cases like #12587 will be confusing and disproportionately affect new users, which isn't good.

**Comment by kuanluo** [comment] 2017-03-10 18:38
I like the idea of having both the ID and host:port for clarity. In node overview page (ie: https://blue.crdb.io:8080/#/cluster/nodes) we can add a column for ID.

**Comment by dianasaur323** [comment] 2017-04-05 10:05
Let's try to clean this up before 1.0? It seems like a relatively straight-forward fix. Taking off @kuanluo and @maxlang and leaving @mrtracy on as the primary assignee (thanks Matt!)

**Comment by tamird** [comment] 2017-04-30 19:16
Note sure it's related, but I'm also seeing duplicate entires in the node graph dropdown on blue when accessing the UI via SSH tunnel:

<img width="1105" alt="screen shot 2017-04-30 at 15 14 27" src="https://cloud.githubusercontent.com/assets/1535036/25567263/e9f0c9b0-2db7-11e7-875f-294e5bafd332.png">

**Comment by tamird** [comment] 2017-05-01 02:34
Ah, the above is caused by the fact that nodes are identified in that list by their hostname, and node ID 7 was recreated as node ID 11 (still on the host blue 7). So perhaps we need to be careful about identifying nodes by their addresses.

**Comment by mrtracy** [comment] 2017-05-01 02:53
That's related, but I think it's a distinct bug. I'm not going to be able to fix it in 1.0, but the original bug here is being closed by a PR i'm about to merge. @tamird would you log that as a separate issue?

**Closed** 2017-05-01 03:20 UTC
Labels: cleanup
