### ISSUE TITLE
Cockroach complains that non existant DB already exists

### ISSUE THREAD

**Issue by sbstp** [cockroachdb/cockroach#59672] opened 2021-02-01 22:18 UTC
**Describe the problem**

I was testing migrations on our schema, I created a few tables then ran the downgrade part to delete the tables. When I tried running the migration again, the migrations would not longer work. I tried adding a DROP statement right before the CREATE statement, it says that the table does not exist. But the CREATE still fails.

I tried checking manually what's up with the database, here's what I get:

```sql
root@:26257/api> show tables;
  schema_name |          table_name          | type  | owner | estimated_row_count
--------------+------------------------------+-------+-------+----------------------
  public      | alembic_version              | table | admin |                   1
  public      | backup_storage               | table | admin |                   1
  public      | clusters                     | table | admin |                   1
  public      | clusters_groups              | table | admin |                   0
  public      | clusters_resources           | table | admin |                   0
  public      | groups                       | table | admin |                   0
  public      | groups_resources_permissions | table | admin |                   0
  public      | object_types                 | table | admin |                   4
  public      | permissions                  | table | admin |                   3
  public      | products                     | table | admin |                   2
  public      | products_object_types_specs  | table | admin |                  12
  public      | products_providers           | table | admin |                   8
  public      | products_upgrade_matrix      | table | admin |                   3
  public      | products_versions            | table | admin |                   4
  public      | providers                    | table | admin |                   4
  public      | providers_clusters           | table | admin |                   1
  public      | quotas                       | table | admin |                   2
  public      | redirects                    | table | admin |                  13
  public      | resources                    | table | admin |                   0
  public      | resources_object_types       | table | admin |                   0
  public      | resources_specs              | table | admin |                   0
  public      | specs                        | table | admin |                  12
  public      | tokens                       | table | admin |                   0
  public      | users                        | table | admin |                   0
  public      | users_clusters_quotas        | table | admin |                   0
  public      | users_groups                 | table | admin |                   0
  public      | users_resources_permissions  | table | admin |                   0
  public      | users_tokens                 | table | admin |                   0
(28 rows)

Time: 89ms total (execution 88ms / network 1ms)

root@:26257/api> CREATE TABLE nodepools_node_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    node_type TEXT NOT NULL CHECK (node_type <> '')
);
ERROR: relation "nodepools_node_types" already exists
SQLSTATE: 42P07
```

**Expected behavior**
A table that does not exist should not exist.

**Additional data / screenshots**
Upgrade SQL
```sql
CREATE TABLE nodepools_node_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    node_type TEXT NOT NULL CHECK (node_type <> '')
);

DROP INDEX IF EXISTS idx_nodepools_node_types_node_type;
```

Downgrade SQL
```sql
DROP INDEX IF EXISTS idx_nodepools_node_types_node_type;
DROP TABLE IF EXISTS nodepools_node_types;
```

**Environment:**
 - CockroachDB version: 20.1.3 / 20.1.11 / 20.2.4
 - Server OS: Linux (Ubuntu 20.04) running inside Docker, official image
 - Client app: cockroach shell / alembic / psycopg2

Jira issue: CRDB-3259

**Comment by sbstp** [comment] 2021-02-01 23:49
I have done further testing. I can reproduce the bug on v20.1.3 but not v20.2.4. If a database was on v20.1.3 and the bug was triggered, it's not able to recover even if upgraded to v20.2.4.

What I do to test is:

1. Create tables on my databases
2. Seed it with our initial data
3. Migrate it to latest with alembic
4. Downgrade 1 migration with alembic
5. Upgrade back to latest

On a brand new v20.2.4, the bug no longer occurs. On a brand new v20.1.3 it occurs.

**Comment by jordanlewis** [comment] 2021-02-02 15:04
Hi, could you share a reproduction case that we can run as well?

Also, if you could include the output of `cockroach debug doctor` on the cluster as well, that would be helpful.

**Comment by sbstp** [comment] 2021-02-02 16:50
I'm trying to create a reproduction case but at the moment I can only reproduce it using our full set of migrations and seed data which contains sensitive information.

I tried running `cockroach debug doctor` on a broken DB but it says the `doctor` subcommand does not exist.

**Comment by jordanlewis** [comment] 2021-02-02 16:54
I think debug doctor is only in 20.2.

**Comment by sbstp** [comment] 2021-02-02 16:57
Ok, so I created a v20.1.3, broke it. Then updated to v20.2.4 and ran doctor. Here's the output:

```
[root@51f42459adbe cockroach]# cockroach debug doctor cluster --insecure
Examining 64 descriptors and 68 namespace entries...
   Table  81: ParentID  52, ParentSchemaID 29, Name 'nodepools_node_types': extra draining names found [{ParentID:52 ParentSchemaID:29 Name:nodepools_node_types}]
   Table  82: ParentID  52, ParentSchemaID 29, Name 'nodepools_providers_node_types': extra draining names found [{ParentID:52 ParentSchemaID:29 Name:nodepools_providers_node_types}]
   Table  83: ParentID  52, ParentSchemaID 29, Name 'nodepools': extra draining names found [{ParentID:52 ParentSchemaID:29 Name:nodepools}]
Examining 0 running jobs...
ERROR: validation failed
Failed running "debug doctor cluster"
```

It does seem to mention my broken tables...

**Comment by postamar** [comment] 2022-03-08 19:22
Closing this because we've since added namespace validation which should prevent this type of issue from reoccurring.

**Closed by postamar** 2022-03-08 19:22 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-schema
