### ISSUE TITLE
perf: regression since 20190805 release

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#41206] opened 2019-09-30 17:21 UTC
While testing the 20190930 release in #41128, the test clusters diverged pretty heavily in their performance:

![ss](https://user-images.githubusercontent.com/41181/65898630-3addcc00-e36f-11e9-80cd-f582236720cd.png)

vs

![ss](https://user-images.githubusercontent.com/41181/65898948-e0913b00-e36f-11e9-8c30-3d688a2e68e0.png)

The top image (the newer release) shows heavily increasing time and variance for SQL latency compare to the 0805 release which has a slighty increase over time. The various transaction, SQL, and storage metrics are similar. This seems like a performance regression since then.

**Comment by mjibson** [comment] 2019-09-30 17:24
These clusters are at http://mjibson-release-v1920-alpha20190805-0001.roachprod.crdb.io:26258
http://mjibson-release-250f4c36de2b88eff443cf9be9cd5d2759312c88-0001.roachprod.crdb.io:26258 and should be around for the next few days. Can extend if requested.

**Comment by andreimatei** [comment] 2019-09-30 17:28
Just to eliminate one thing can you please disable the periodic generation of the new replication reports by doing `set cluster setting kv.replication_reports.interval = 0`? I think the chances of this helping are not great, though.

**Comment by mjibson** [comment] 2019-09-30 17:41
Sure. I executed `set cluster setting kv.replication_reports.interval = '0s'` just now on mjibson-release-250f4c36de2b88eff443cf9be9cd5d2759312c88. We can check back tomorrow and see what changes.

**Comment by bdarnell** [comment] 2019-09-30 18:05
My first guess was that the uninitialized variable that Andrew K just discovered was causing a lot of unnecessary compactions (and for some obscure reason this uninitialized variable happened to be zero most of the time in the old build). But it looks like the number of rocksdb compactions is the same between the two builds. (We don't know the *size* of the compactions, so there could be a change in this area, but it's unlikely that the count of compactions would match so closely with a substantially different size).

Is this regression visible in roachperf, or does that not run long enough to see the performance degrade like this? It would be nice to narrow this change down to a smaller window than two months.

**Comment by nvanbenschoten** [comment] 2019-09-30 18:31
The high latencies appear at very regular intervals, with a period of almost exactly 30 minutes.

**Comment by nvanbenschoten** [comment] 2019-09-30 18:33
CPU utilization doesn't seem to be correlated with the spikes but Go allocated memory usage does. We should wait for the next spike and grab a heap profile.

**Comment by jordanlewis** [comment] 2019-09-30 18:40
Could this be statistics collection? I didn't think runs were so regularly scheduled, but collecting statistics does use a good amount of Go memory on each run. There's nothing in the jobs table though, and I think statistics runs do get jobs, so I think this theory is wrong.

**Comment by nvanbenschoten** [comment] 2019-09-30 19:04
I'm seeing large fluctuations in Go allocated memory in the following sources:
```
  457.52MB 29.25% 29.25%   551.03MB 35.23%  github.com/cockroachdb/cockroach/pkg/sql.(*optTableStat).init
   93.51MB  5.98% 35.23%    93.51MB  5.98%  github.com/cockroachdb/cockroach/pkg/sql/sqlbase.(*DatumAlloc).NewDInt
   41.74MB  2.67% 37.89%   593.77MB 37.96%  github.com/cockroachdb/cockroach/pkg/sql.newOptTable
```
We also saw this in https://github.com/cockroachdb/cockroach/issues/40566#issuecomment-532856275 and we addressed it by reducing the SQL connection limit. Here we have 2k connections.

cc. @RaduBerinde is it possible that something changed here in the past two months? It does suspect that we suddenly needed https://github.com/cockroachdb/cockroach/pull/40924 after never needing it before.

**Comment by nvanbenschoten** [comment] 2019-09-30 19:10
We do have very regular stats recomputation on the `warehouse` and `district` tables. Perhaps this is invalidating all of the connection's optimizer metadata and forcing recreation of query plans.

**Comment by nvanbenschoten** [comment] 2019-09-30 19:11
I'm going to turn off auto-stats collection (`sql.stats.automatic_collection.enabled`) and see if that has an effect.

**Comment by jordanlewis** [comment] 2019-09-30 19:15
#39743 turned on histograms by default, which was merged 8/20. I wonder if that's related.

**Comment by nvanbenschoten** [comment] 2019-09-30 19:24
It's possible. There is a `sql.stats.histogram_collection.enabled` cluster setting, so we can play with that once we see whether `sql.stats.automatic_collection.enabled` has any effect.

**Comment by RaduBerinde** [comment] 2019-09-30 19:26
I believe the delta of memory usage in `optTableStats` is due to the histograms. @rytaft might know better how much of a difference we should expect. I do agree that having separate instances of these objects across connections is silly so I plan to fix that for 20.1 (tracked by #40922). We can also try a smaller fix to make the stat cache itself store these objects.

**Comment by RaduBerinde** [comment] 2019-09-30 20:15
I started working on a change to push the decoding of the histograms to the stats cache. That will reuse the histogram memory across all connections (and make things more efficient when a new statistics becomes available).

**Comment by nvanbenschoten** [comment] 2019-09-30 21:13
> I'm going to turn off auto-stats collection (sql.stats.automatic_collection.enabled) and see if that has an effect.

Unfortunately, it looks like that didn't resolve the issue. We still see the oscillations.

Regardless, @RaduBerinde thanks for getting #41220 out so fast!

**Comment by nvanbenschoten** [comment] 2019-10-01 15:32
That said, it does seem like the memory fluctuations are from `optTableStats`. Here's a series of heap profiles that show its growing contribution.

![Screen Shot 2019-10-01 at 11 28 31 AM](https://user-images.githubusercontent.com/5438456/65977039-35e84d80-e43f-11e9-951c-00f0740ba6db.png)
![Screen Shot 2019-10-01 at 11 28 41 AM](https://user-images.githubusercontent.com/5438456/65977040-35e84d80-e43f-11e9-848c-e23c5361d161.png)
![Screen Shot 2019-10-01 at 11 28 48 AM](https://user-images.githubusercontent.com/5438456/65977041-35e84d80-e43f-11e9-8964-179951242cbd.png)
![Screen Shot 2019-10-01 at 11 28 56 AM](https://user-images.githubusercontent.com/5438456/65977042-35e84d80-e43f-11e9-9eea-d4d946ec76cb.png)


@RaduBerinde do you have any idea why this memory would be getting flushed every 30 minutes even without auto stats collection?

**Comment by nvanbenschoten** [comment] 2019-10-01 15:45
https://github.com/cockroachdb/cockroach/issues/41230 was also contributing to memory usage in the cluster, but that memory was stable so it's not responsible for this issue.

**Comment by RaduBerinde** [comment] 2019-10-01 18:04
The optCatalog (one per connection) has a cache of dataSources. When this reaches 100, it gets cleared. Very simplistic but these were meant to be small objects.

With auto stats off, this should only happen if something else is causing the table descriptor versions to keep changing.

We should see if #41220 fixes it.

**Comment by knz** [comment] 2019-10-02 07:01
Comment from @nvanbenschoten 

> the v19.2-beta cluster looks much better running cbbf40a08e45caeda82930a78e19a4b6430d0f8c, which contains https://github.com/cockroachdb/cockroach/pull/41220 and https://github.com/cockroachdb/cockroach/pull/41231
> 
<img width="982" alt="Screen Shot 2019-10-01 at 11 52 11 PM" src="https://user-images.githubusercontent.com/642886/66024055-262a4100-e4f3-11e9-9ac8-d88fc5e4fcb7.png">

> we should continue to monitor the cluster, but as long as things are still looking ok tomorrow morning, we should consider https://github.com/cockroachdb/cockroach/issues/41206 sufficiently resolved to where it’s no longer a blocker

**Comment by nvanbenschoten** [comment] 2019-10-02 15:22
It looks like this is fixed. Thanks for the help @knz and @RaduBerinde.

<img width="978" alt="Screen Shot 2019-10-02 at 11 19 12 AM" src="https://user-images.githubusercontent.com/5438456/66057510-da819280-e506-11e9-8c09-a9a375ffb9ac.png">

<img width="980" alt="Screen Shot 2019-10-02 at 11 19 23 AM" src="https://user-images.githubusercontent.com/5438456/66057516-dce3ec80-e506-11e9-9029-2044a73436d2.png">

**Closed by nvanbenschoten** 2019-10-02 15:22 UTC
Labels: regression
