### ISSUE TITLE
Entire cluster down with this range is likely unavailable errors.

### ISSUE THREAD

**Issue by SixFive7** [cockroachdb/cockroach#90135] opened 2022-10-18 12:53 UTC
**Describe the problem**

On a seemingly random low load moment our four node cluster suddenly went offline. Rebooting the entire cluster gives us back control for about a minute after which everything crashes again.

Our logs are filled with messages similar to this one for lots of ranges:

```
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849  range unavailable: have been waiting 15.00s for proposing command Merge [‹/System/tsd/cr.node.sql.stats.mem.max-max/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p99.999/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p99.99/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p99.9/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p99/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p90/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p75/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-p50/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.max-count/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.mem.current/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.discarded.current/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.count/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.error/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-max/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p99.999/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p99.99/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p99.9/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p99/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p90/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration-p75/4/10s/2022-10-18T12:00:00Z›,‹/Min›),... 23 skipped ..., Merge [‹/System/tsd/cr.node.sql.stats.flush.duration.internal-p90/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration.internal-p75/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration.internal-p50/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.flush.duration.internal-count/4/10s/2022-10-18T12:00:00Z›,‹/Min›), Merge [‹/System/tsd/cr.node.sql.stats.cleanup.rows_removed.internal/4/10s/2022-10-18T12:00:00Z›,‹/Min›).
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +This range is likely unavailable.
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +Please submit this message to Cockroach Labs support along with the following information:
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +Descriptor:  r173:‹/System/tsd/cr.node.sql.s{ervice.latency.internal-p99.99/3/10s/2022-08-22T11:00:00Z-tats.reported.mem.current/1/10s/2022-08-24T05:00:00Z}› [(n1,s1):1, (n2,s2):5, (n4,s4):4, next=6, gen=20]
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +Live:        (n1,s1):1,(n2,s2):5,(n4,s4):4
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +Non-live:    
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +Raft Status: {"id":"1","term":30,"vote":"0","commit":3519684,"lead":"5","raftState":"StateFollower","applied":3519684,"progress":{},"leadtransferee":"0"}
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +and a copy of https://yourhost:8080/#/reports/range/173
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +If you are using CockroachDB Enterprise, reach out through your
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +support contract. Otherwise, please open an issue at:
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +
E221018 12:01:05.370910 154106 kv/kvserver/replica_write.go:285 ⋮ [n1,s1,r173/1:‹/System/tsd/cr.node.sql.s…›] 160849 +  https://github.com/cockroachdb/cockroach/issues/new/choose
```

Going to https://yourhost:8080/#/reports/range/173 doesn't show anything out of the ordinary except for the range log timing out.

Furthermore on each of our nodes the dashboard seems very unstable. Only sometimes it works at all and if it does this intermittent output is the best we get:
![image](https://user-images.githubusercontent.com/6650122/196430806-561f28ae-df28-4b6e-86ab-3e53e7d2537d.png)

**Environment:**
 - CockroachDB version v21.2.9
 - Server OS: Talos OS (self hosted kubernetes)
 - Client app: Microsoft Orleans (not relevant here)

**Additional context**
The impact is that we are completely down. But having excluded any hardware issues or load issues (there is not even an app server up now) we more worried about how stable cockroachdb actually is in the long term.

If anybody can shine a light on what is happening here or how this sudden crash could have happened we would be very very thankful!

Jira issue: CRDB-20605

**Comment by erikgrinaker** [comment] 2022-10-18 13:03
Unavailable ranges are typically caused by network outages or node crashes that cause a majority of range replicas to become unavailable.

> after which everything crashes again

Can you clarify what you mean by "crashes"? Do the nodes actually crash (i.e. does the process exit), or are they just unresponsive? Are there any indications in the logs for why the nodes are crashing or otherwise unable to communicate with each other?

**Comment by SixFive7** [comment] 2022-10-18 13:19
Hi, thanks for the fast reply.

The process does not actually crash or exit. However, all SQL queries time out and the dashboard becomes mostly unresponsive. I've got pages and pages of logs that show these errors. Not sure if I can find any other indication as to what is happening. With our kubernetes monitoring we are 100% sure there are no nodes down and that there is no network outage. Also, the (intermittently loading) dashboard gives all 4 nodes as alive, 978 ranges with 0 under replicated and 0 unavailable ranges. I've clicked through the entire dashboard so far and can't find anything except for a whole bunch of invalid lease ranges.

Hope this helps clarify. Thanks again for helping!

```
I221017 21:42:04.923548 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552488  [JOB 236550] compacting: sstable created 864910
W221017 21:42:04.955502 29737369 kv/kvclient/kvcoord/dist_sender.go:1575 ⋮ [n1,raftlog,s1,r482/1:‹/Table/79/1/"\xe{a\x9…-b\xd…}›] 1552489  slow range RPC: have been waiting 60.00s (1 attempts) for RPC TruncateLog [‹/Table/79/1/"\xea\x9d\xcc\xdb\x1d\aGf\x97М[S}\xcdw"/"1"›,‹/Min›) to r482:‹/Table/79/1/"\xe{a\x9d\xcc\xdb\x1d\aGf\x97М[S}\xcdw"/"1"-b\xd0D\xdc\xfayA\x03\x9d\x18\x13\x8d\x98\x9da("/"0"}› [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=90]; resp: aborted during DistSender.Send: context deadline exceeded
W221017 21:42:04.955630 29737369 kv/kvclient/kvcoord/dist_sender.go:1585 ⋮ [n1,raftlog,s1,r482/1:‹/Table/79/1/"\xe{a\x9…-b\xd…}›] 1552490  slow RPC response: slow RPC finished after 60.00s (1 attempts)
E221017 21:42:04.955672 29737369 kv/kvserver/queue.go:1088 ⋮ [n1,raftlog,s1,r482/1:‹/Table/79/1/"\xe{a\x9…-b\xd…}›] 1552491  ‹operation "raftlog queue process replica 482" timed out after 1m0s›: aborted during DistSender.Send: context deadline exceeded
I221017 21:42:04.956747 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552492  [JOB 236550] compacting: sstable created 864911
I221017 21:42:04.976135 29743501 kv/kvserver/store_snapshot.go:793 ⋮ [n1,s1] 1552493  cannot accept snapshot: ‹snapshot intersects existing range; initiated GC:› [n1,s1,r848/1:‹/Table/79/1/"\xe1{(\xc…-\xff…}›] (incoming ‹/Table/79/1/"\xe1\x{a0i\xc7\xd8<B\x15\x8f\xe4q\x10\x9c\x87(\x1f"/"1"-ff\xf9\x88\x12\xe8G@\xbb\xfdByKәu"/"0"}›)
I221017 21:42:04.990407 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552494  [JOB 236550] compacting: sstable created 864912
I221017 21:42:05.023868 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552495  [JOB 236550] compacting: sstable created 864913
I221017 21:42:05.059523 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552496  [JOB 236550] compacting: sstable created 864914
I221017 21:42:05.086024 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552497  [JOB 236550] compacting: sstable created 864915
W221017 21:42:05.100800 29743054 sql/user.go:215 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552498  user lookup for ‹"app"› failed: context canceled
W221017 21:42:05.100895 29743054 sql/user.go:162 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552499  user membership lookup for ‹"app"› failed: internal error while retrieving user account: context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500  user retrieval failed for user=‹"app"›: internal error while retrieving user account memberships: internal error while retrieving user account: context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +(1) attached stack trace
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  -- stack trace:
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:163
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/auth.go:143
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:627
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | runtime.goexit
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | 	/usr/local/go/src/runtime/asm_amd64.s:1371
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +Wraps: (2) internal error while retrieving user account memberships
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +Wraps: (3) internal error while retrieving user account: context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | -- cause hidden behind barrier
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | internal error while retrieving user account: context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | (1) attached stack trace
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   -- stack trace:
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql.retrieveSessionInitInfoWithCache
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:216
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo.func4
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:133
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/util/contextutil.RunWithTimeout
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/contextutil/context.go:89
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo.func2
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:99
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql.GetUserSessionInitInfo
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/user.go:130
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).handleAuthentication
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/auth.go:143
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:627
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | runtime.goexit
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | 	/usr/local/go/src/runtime/asm_amd64.s:1371
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | Wraps: (2) internal error while retrieving user account
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | Wraps: (3) context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | -- cause hidden behind barrier
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | (1) context canceled
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  |   | Error types: (1) *errors.errorString
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +  | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *barriers.barrierErr
W221017 21:42:05.100940 29743054 sql/pgwire/auth.go:151 ⋮ [n1,client=10.1.7.254:52914,hostssl,user=‹app›] 1552500 +Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *barriers.barrierErr
I221017 21:42:05.112424 29743413 3@vendor/github.com/cockroachdb/pebble/event.go:619 ⋮ [n1,pebble,s1] 1552501  [JOB 236550] compacting: sstable created 864916
```

**Comment by erikgrinaker** [comment] 2022-10-18 13:59
Thanks. There isn't really an indication of the root cause in these log messages, only that ranges are unavailable.

If you can collect a debug.zip with debugging information and upload it to me at https://upload.cockroachlabs.com/dropzone/grinaker then I can have a look. You can find instructions on this here:

https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html

**Comment by SixFive7** [comment] 2022-10-18 15:34
Thank you for looking into this! The files have been submitted:
Submission ID# MCRN-9CNF

**Comment by knz** [comment] 2022-10-18 15:39
Drive-by comment:

- Just to clarify the observations so far:
  - the log messages in the issue above point to some of the timeseries ranges (those containing the data for the charts) being unavailable. Just this explains why the DB Console and the charts seem to be unstable. The display of any chart accessing the specific timeseries that have unavailable ranges will simply hang.
  - This does not say whether _other_ ranges are unavailable too. We will know this with the debug zip submitted, and can also be seen in the "advanced debug" page of the UI -> "problem ranges".
- To help with the investigation, it would be useful to explain to us:
  - has there been any hardware upgrade or extension recently? What was changed?
  - has there been any operational event (node restart, routine  maintainance, etc) recently? How was it changed?
  - was the orchestration configuration changed recently? What did you change?

All these explanations about changes will provide us more context for the investigation.

**Comment by erikgrinaker** [comment] 2022-10-19 12:50
I've had a quick look at the debug.zip. We see a bunch of slow `handle raft ready` events starting on n3,s3,r482 at 2022-10-17 21:33:22. This means that the node is processing Raft write commands slower than expected, and often indicates that the node is overloaded. I'm not seeing much CPU usage here, so my guess is slow disk IO. r482 belongs to table 79, in case that tells you something.

Unfortunately, the debug.zip is rather sparse, since many commands errored out -- likely because `debug zip` was run from outside of Kubernetes:

```
dial tcp: lookup cockroachdb-0.cockroachdb.cockroachdb.svc.cluster.local: no such host
```

You may want to have a look at various resource/storage metrics, as well as fsync latencies, in the DB console and see if something is out of the ordinary.

**Comment by erikgrinaker** [comment] 2022-10-31 10:40
No updates, closing.

**Closed by erikgrinaker** 2022-10-31 10:40 UTC
Labels: C-bug, O-community, A-kv-replication, X-blathers-triaged, T-kv-replication

**Comment by SixFive7** [comment] 2022-11-03 14:11
It turns out that our logging was misconfigured making it impossible to look far enough into the past to see the origin of the failure.
To debug and prevent this in the future we plan on fixing our logging setup next to engaging with Cockroach Labs for a support contract.
