### ISSUE TITLE
circleci: failed tests (13853): TestRestoreReplicas

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4874] opened 2016-03-04 21:57 UTC
The following test appears to have failed:

[#13853](https://circleci.com/gh/cockroachdb/cockroach/13853):

```
I160304 21:55:57.952023 raft/raft.go:779  [group 1] 2 [commit: 15] restored snapshot [index: 15, term: 6]
I160304 21:55:58.360905 raft/raft.go:459  [group 1] 1 became follower at term 6
I160304 21:55:58.361121 raft/raft.go:235  [group 1] newRaft 1 [peers: [1,2], term: 6, commit: 15, applied: 15, lastindex: 15, lastterm: 6]
I160304 21:55:58.361705 storage/replica.go:1709  [node=1,store=1,range=1] gossiping system config from store 1, range 1, hash 91100e0451ac1aab78723f763fac84cccdd4aea5
I160304 21:55:58.365433 storage/replica.go:1650  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
panic: gossip infostore's NodeID is 0

goroutine 4977 [running]:
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc8203b6000, 0xc8202a59e8, 0x10, 0x10, 0x0, 0x2f)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0xb4
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc820234780, 0x1c748d0, 0xa, 0xc8202a59e8, 0x10, 0x10, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:522 +0x12b
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc8201fa680, 0x3582780)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1652 +0xa01
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc8200c9400, 0x0)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:797 +0x3c3
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:741 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc820ae10a0, 0xc8203be4a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	8.844s
=== RUN   TestBatchBasics
I160304 21:56:11.673637 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I160304 21:56:11.683239 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160304 21:56:11.688402 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 02:27
Duplicate of #4821.

**Closed by petermattis** 2016-03-06 02:27 UTC
Labels: test-failure
