### ISSUE TITLE
sql: "could not decorrelate subquery" on insert to enum with asyncpg

### ISSUE THREAD

**Issue by gordthompson** [cockroachdb/cockroach#80169] opened 2022-04-19 15:44 UTC
**Describe the problem**

As originally reported in

https://github.com/sqlalchemy/sqlalchemy/issues/7945

attempting to insert into a table with an enum column results in "could not decorrelate subquery".

**To Reproduce**

### psycopg2 (2.9.3) - No issue

This code runs fine for both PostgreSQL (pg) and CockroachDB (cr)

```python
import psycopg2

cr = {"host": "localhost", "port": 26257, "user": "root", "dbname": "defaultdb"}
pg = {"host": "192.168.0.199", "port": 5432, "user": "scott", "password": "tiger", "dbname": "test"}
conn = psycopg2.connect(**cr)
cur = conn.cursor()
cur.execute("DROP TABLE IF EXISTS test_enums")
cur.execute("DROP TYPE IF EXISTS myenum")
cur.execute("CREATE TYPE myenum AS ENUM ('foo', 'bar')")
cur.execute(
    """\
CREATE TABLE test_enums (
    id int NOT NULL, 
    test myenum
)
"""
)
cur.execute(
    "INSERT INTO test_enums (id, test) VALUES (%(id)s, %(test)s)",
    {"id": 1, "test": "foo"},
)
conn.commit()
```

### asyncpg with PostgreSQL - No issue

```python
import asyncio

import asyncpg

# uses ENUM and TABLE created by previous (sync) tests


async def run():
    pg = {
        "host": "192.168.0.199",
        "port": 5432,
        "user": "scott",
        "password": "tiger",
        "database": "test",
    }
    conn = await asyncpg.connect(**pg)
    await conn.execute(
        "INSERT INTO test_enums (id, test) VALUES ($1, $2)",
        1,
        "foo",
    )
    await conn.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(run())
```

### asyncpg with CockroachDB - "could not decorrelate subquery"

```python
import asyncio

import asyncpg

# uses ENUM and TABLE created by previous (sync) tests


async def run():
    cr = {"host": "localhost", "port": 26257, "user": "root", "database": "defaultdb"}
    conn = await asyncpg.connect(**cr)
    await conn.execute(
        "INSERT INTO test_enums (id, test) VALUES ($1, $2)",
        1,
        "foo",
    )
    await conn.close()


loop = asyncio.get_event_loop()
loop.run_until_complete(run())

"""
Traceback (most recent call last):
  File "/home/gord/git/sqlalchemy-cockroachdb/gord_test/async_issue_7945_mcve.py", line 28, in <module>
    loop.run_until_complete(run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/gord/git/sqlalchemy-cockroachdb/gord_test/async_issue_7945_mcve.py", line 19, in run
    await conn.execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 320, in execute
    _, status, _ = await self._execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1711, in _do_execute
    stmt = await self._get_statement(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 413, in _get_statement
    types, intro_stmt = await self._introspect_types(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 459, in _introspect_types
    return await self.__execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/home/gord/git/sqlalchemy-cockroachdb/venv/lib/python3.8/site-packages/asyncpg/connection.py", line 1731, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions._base.UnknownPostgresError: could not decorrelate subquery
"""
```

**Environment:**
 - CockroachDB version: v22.1.0-beta.3
 - Server OS: Ubuntu 20.04
 - Client app: asyncpg 0.25.0

Epic CRDB-18886
Jira issue: CRDB-15824

**Comment by rafiss** [comment] 2022-04-19 15:51
Thanks for filing! I ran this and saw that the INSERT query itself runs fine, but then right after `asyncpg` sends this query, which is the one that's failing:

```
WITH RECURSIVE typeinfo_tree(
    oid, ns, name, kind, basetype, elemtype, elemdelim,
    range_subtype, attrtypoids, attrnames, depth)
AS (
    SELECT
        ti.oid, ti.ns, ti.name, ti.kind, ti.basetype,
        ti.elemtype, ti.elemdelim, ti.range_subtype,
        ti.attrtypoids, ti.attrnames, 0
    FROM
            (
        SELECT
            t.oid                           AS oid,
            ns.nspname                      AS ns,
            t.typname                       AS name,
            t.typtype                       AS kind,
            (CASE WHEN t.typtype = 'd' THEN
                (WITH RECURSIVE typebases(oid, depth) AS (
                    SELECT
                        t2.typbasetype      AS oid,
                        0                   AS depth
                    FROM
                        pg_type t2
                    WHERE
                        t2.oid = t.oid

                    UNION ALL

                    SELECT
                        t2.typbasetype      AS oid,
                        tb.depth + 1        AS depth
                    FROM
                        pg_type t2,
                        typebases tb
                    WHERE
                       tb.oid = t2.oid
                       AND t2.typbasetype != 0
               ) SELECT oid FROM typebases ORDER BY depth DESC LIMIT 1)

               ELSE NULL
            END)                            AS basetype,
            t.typelem                       AS elemtype,
            elem_t.typdelim                 AS elemdelim,
            range_t.rngsubtype              AS range_subtype,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.atttypid ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrtypoids,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.attname::text ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrnames
        FROM
            pg_catalog.pg_type AS t
            INNER JOIN pg_catalog.pg_namespace ns ON (
                ns.oid = t.typnamespace)
            LEFT JOIN pg_type elem_t ON (
                t.typlen = -1 AND
                t.typelem != 0 AND
                t.typelem = elem_t.oid
            )
            LEFT JOIN pg_range range_t ON (
                t.oid = range_t.rngtypid
            )
    )
 AS ti
    WHERE
        ti.oid = any($1::oid[])

    UNION ALL

    SELECT
        ti.oid, ti.ns, ti.name, ti.kind, ti.basetype,
        ti.elemtype, ti.elemdelim, ti.range_subtype,
        ti.attrtypoids, ti.attrnames, tt.depth + 1
    FROM
            (
        SELECT
            t.oid                           AS oid,
            ns.nspname                      AS ns,
            t.typname                       AS name,
            t.typtype                       AS kind,
            (CASE WHEN t.typtype = 'd' THEN
                (WITH RECURSIVE typebases(oid, depth) AS (
                    SELECT
                        t2.typbasetype      AS oid,
                        0                   AS depth
                    FROM
                        pg_type t2
                    WHERE
                        t2.oid = t.oid

                    UNION ALL

                    SELECT
                        t2.typbasetype      AS oid,
                        tb.depth + 1        AS depth
                    FROM
                        pg_type t2,
                        typebases tb
                    WHERE
                       tb.oid = t2.oid
                       AND t2.typbasetype != 0
               ) SELECT oid FROM typebases ORDER BY depth DESC LIMIT 1)

               ELSE NULL
            END)                            AS basetype,
            t.typelem                       AS elemtype,
            elem_t.typdelim                 AS elemdelim,
            range_t.rngsubtype              AS range_subtype,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.atttypid ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrtypoids,
            (CASE WHEN t.typtype = 'c' THEN
                (SELECT
                    array_agg(ia.attname::text ORDER BY ia.attnum)
                FROM
                    pg_attribute ia
                    INNER JOIN pg_class c
                        ON (ia.attrelid = c.oid)
                WHERE
                    ia.attnum > 0 AND NOT ia.attisdropped
                    AND c.reltype = t.oid)

                ELSE NULL
            END)                            AS attrnames
        FROM
            pg_catalog.pg_type AS t
            INNER JOIN pg_catalog.pg_namespace ns ON (
                ns.oid = t.typnamespace)
            LEFT JOIN pg_type elem_t ON (
                t.typlen = -1 AND
                t.typelem != 0 AND
                t.typelem = elem_t.oid
            )
            LEFT JOIN pg_range range_t ON (
                t.oid = range_t.rngtypid
            )
    )
 ti,
        typeinfo_tree tt
    WHERE
        (tt.elemtype IS NOT NULL AND ti.oid = tt.elemtype)
        OR (tt.attrtypoids IS NOT NULL AND ti.oid = any(tt.attrtypoids))
        OR (tt.range_subtype IS NOT NULL AND ti.oid = tt.range_subtype)
)

SELECT DISTINCT
    *,
    basetype::regtype::text AS basetype_name,
    elemtype::regtype::text AS elemtype_name,
    range_subtype::regtype::text AS range_subtype_name
FROM
    typeinfo_tree
ORDER BY
    depth DESC
```

**Comment by mgartner** [comment] 2022-04-26 18:46
Could also be similar to https://github.com/cockroachdb/cockroach/issues/73573.

**Comment by michae2** [comment] 2022-04-26 18:47
Tagging @vy-ton

**Comment by vy-ton** [comment] 2022-04-26 18:49
@kernfeld-cockroach fyi there's a group of `could not decorrelate subquery` issues that Queries will need to investigate whenever DX prioritizes asyncpg support

**Comment by andy-kimball** [comment] 2022-05-13 17:45
Looking at this query, there are at least 3 different things preventing decorrelation:

1. The `ia.attname::text` cast is treated as `Immutable` rather than `LeakProof`. Since there's no way that converting from a `name` type to a `text` type can generate an error, we could easily fix this.

2. The `tb.depth + 1` expressions prevent hoisting subqueries out of `CASE` statements, since they may generate an error in the extreme case that the addition triggers 64-bit `int` overflow. This is much tougher to address. We could implement "apply with probe" as described in the "Conditional scalar execution" section of [this paper](https://www.researchgate.net/profile/Mostafa-Elhemali-2/publication/221213885_Execution_strategies_for_SQL_subqueries/links/584f631308aecb6bd8d02aa4/Execution-strategies-for-SQL-subqueries.pdf), which would yield the highest performance. Or we could upgrade execution support for evaluating correlated subqueries in every case, but would be quite slow.

3. We don't yet support decorrelating window functions, which are generated by expressions like `array_agg(ia.attname::text ORDER BY ia.attnum)`. Not doing this was just about never taking the time, not because there's anything preventing it.

**Comment by andy-kimball** [comment] 2022-05-13 17:50
Alternatively, if we could make an upstream change to `asyncpg`, it'd probably be fairly easy to avoid these problematic constructs without changing the output of the query.

**Comment by andy-kimball** [comment] 2022-05-13 21:37
Another bigger change to solve the general case would be an implementation of [this paper](https://dl.gi.de/bitstream/handle/20.500.12116/2418/383.pdf?sequence=1). Materialize uses an approach like this to decorrelate in the general case.

**Comment by msirek** [comment] 2022-05-14 00:29
> Another bigger change to solve the general case would be an implementation of [this paper](https://dl.gi.de/bitstream/handle/20.500.12116/2418/383.pdf?sequence=1). Materialize [uses an approach like this](https://materialize.com/decorrelation-subquery-optimization/) to decorrelate in the general case.

Thanks for posting this paper.  I was thinking about more generalized decorrelation in #77877, and this paper clarifies things.  I was stuck thinking about how to remove duplicate references to outer table rows using the rowid, but here they handle it by adding a join to new relation 'D' containing just the outer table correlated column values with dupes removed.  Removing duplicates before the dependent join is probably also better for performance than grouping by the rowid after the join (and more correct perhaps).

**Comment by andy-kimball** [comment] 2022-05-14 02:16
Well, the problem is that we'd likely need to use a `With` operator to cache the input to `D`, since it's also used to do the post-join. That means caching up the input, which might be worse than the group-by, especially if there's enough data to trigger spilling to disk. I suspect that the best solution will be to do group-by decorrelation for most common cases, and then to fall back on generalized decorrelation for other cases. But we'd need to do some performance testing to be sure.

**Comment by msirek** [comment] 2022-05-14 17:49
> Well, the problem is that we'd likely need to use a `With` operator to cache the input to `D`, since it's also used to do the post-join.

I'm not sure I understand this point. Are you worried that rows will be inserted into the source relation of `D` in between 2 separate scans? Wouldn't our transaction logic handle this by either blocking the writes or making our transaction recompute results if we scanned one of the written rows?

**Comment by andy-kimball** [comment] 2022-05-14 21:39
Right, the input to `D` could be very expensive to recompute. It's better to cache it locally, since we *know* we're going to need it twice. If the execution engine was able to handle graphs like Materialize, this wouldn't be necessary.

**Comment by msirek** [comment] 2022-05-16 16:55
Leakproof, short definition:
```
LEAKPROOF indicates that the function has no side effects. It reveals no information about its arguments other than by its return value. For example, a function which throws an error message for some argument values but not others, or which includes the argument values in any error message, is not leakproof. 
```

**Closed** 2023-01-18 21:39 UTC
Labels: C-bug, O-community, X-blathers-triaged, A-tools-asyncpg

**Comment by glstas** [comment] 2024-09-07 17:34
Hi folks, I just wanted to get a random enum value to insert it into dummy data and this all started...

At first, I had an issue with not random random() in subquery. I solved it with some magic by pushing an unnecessary parameter into a subquery so that it is not optimized and remains random.
Second, I wanted some condition for my case and got `[XXUUU] ERROR: could not decorrelate subquery`

Prepared a simplified example:
```
select random()                                                                     r1, -- random
       (select random())                                                            r2, -- NOT random
       a.rnd                                                                        r3, -- random
       (select a.rnd)                                                               r4, -- random
       (select * from (values (1), (2), (3) order by random() limit 1))             r5, -- NOT random
       (select * from (values (1), (2), (3) order by a.rnd limit 1))                r6, -- NOT random
       (select * from (values (1), (2), (3) order by random() + a.rnd * 0 limit 1)) r7  -- random
--        ,   -- uncomment this to see the error
--        CASE
--            WHEN a.rnd is null
--                THEN (select * from (values (1), (2), (3) order by random() + a.rnd * 0 limit 1))
--            END                                                                      r8
FROM (select random() as rnd from generate_series(1, 5)) a;
```

**Comment by mgartner** [comment] 2024-09-09 16:05
What version of CockroachDB are you running? The example works for me on 24.1.0:

```
defaultdb> SELECT version();
                                                    version
----------------------------------------------------------------------------------------------------------------
  CockroachDB CCL v24.1.0 (aarch64-apple-darwin21.2, built 2024/05/15 21:28:46, go1.22.2 X:nocoverageredesign)
(1 row)

defaultdb> select random()                                                                     r1, -- random
                             ->        (select random())                                                            r2, -- NOT random
                             ->        a.rnd                                                                        r3, -- random
                             ->        (select a.rnd)                                                               r4, -- random
                             ->        (select * from (values (1), (2), (3) order by random() limit 1))             r5, -- NOT random
                             ->        (select * from (values (1), (2), (3) order by a.rnd limit 1))                r6, -- NOT random
                             ->        (select * from (values (1), (2), (3) order by random() + a.rnd * 0 limit 1)) r7  -- random
                             -> --        ,   -- uncomment this to see the error
                             -> --        CASE
                             -> --            WHEN a.rnd is null
                             -> --                THEN (select * from (values (1), (2), (3) order by random() + a.rnd * 0 limit 1))
                             -> --            END                                                                      r8
                             -> FROM (select random() as rnd from generate_series(1, 5)) a;
          r1         |         r2         |         r3          |         r4          | r5 | r6 | r7
---------------------+--------------------+---------------------+---------------------+----+----+-----
  0.8520581431472002 | 0.7700118613437877 | 0.05309619602943774 |  0.5845364382099532 |  3 |  1 |  2
  0.7999319435348232 | 0.7700118613437877 |  0.9486610797811332 | 0.40158784469443626 |  3 |  1 |  2
  0.8435308743600572 | 0.7700118613437877 |  0.5563158895851964 |  0.5422660811151345 |  3 |  1 |  3
  0.9563179665476974 | 0.7700118613437877 |  0.9307144294265303 |  0.8603713894855165 |  3 |  1 |  2
  0.5949518140737686 | 0.7700118613437877 | 0.36121661583884346 | 0.42138355585690657 |  3 |  1 |  3
(5 rows)
```

**Comment by sglushko** [comment] 2024-09-10 16:25
Yes, you are right, I had version v22.2.1, I updated to v24.1 and there is no error.

**Comment by glstas** [comment] 2024-09-10 16:57
Yes, you are right, I had version v22.2.1, I updated to v24.1 and there is no error.
