### ISSUE TITLE
importccl: IMPORT TABLE .... PGDUMP DATA .... fails silently 

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#29037] opened 2018-08-24 18:09 UTC
I was testing the `IMPORT TABLE foo (i int primary key, b string, ...) PGDUMP DATA ('pg_dump_file');` variant of `IMPORT PGDUMP` for #28158, and I found that it fails silently if it cannot find the requested table.

For example, if it cannot find `foo` in 'pg_dump_file' in the above example, it creates an empty table with the given schema and prints success (correctly showing that no rows were loaded):
```
        job_id       |  status   | fraction_completed | rows | index_entries | system_records | bytes  
+--------------------+-----------+--------------------+------+---------------+----------------+-------+
  377026930593300481 | succeeded |                  1 |    0 |             0 |              0 |     0  
(1 row)
```

The other variant for loading a specific table, `IMPORT TABLE foo FROM PGDUMP 'pg_dump_file';` gives a nice error in this case:
```
pq: table "foo" not found in file (found tables: bar)
```

It seems like both variants should fail with the same error.

**Comment by mjibson** [comment] 2018-09-06 03:45
@dt what do you think about this? It's currently working as intended. The table name and schema is specified, but the import file just happens to have 0 INSERT statements for that file name. I guess that most of the time if this happens it's actually because the user mistyped the table name, and we should detect that there are 0 rows? We could also disallow specifying the table schema like this from bundle files. However this is a convenient way to quickly change the schema of a table, although the new schema would have to be string compatible with the old one. Ergh.

I think specifying a create table with a bundle format should be an error. If you want to import a specific table with a different schema than in the bundle file, edit the bundle file by hand.

**Comment by dt** [comment] 2018-09-06 14:03
I'd be fine with error'ing if we don't see a row for an explicitly named table  during the schema extraction pass.

I'm -1 on making explicit schema with bundle format and error. I think it's a good tool for on-the-fly adjustments, which I think is a particularly important workaround option where our conversion rules might not match what someone wants. Files could often be too big to easily edit by hand, or stored in a non-editable location, or otherwise be annoying to edit, e.g. I've tried editing our testdata files by hand a couple times and my default editor corrupts their content on save (either whitespace trim or the bad unicode bytes maybe? whatever it is, it still illustrates that not all dump files get along with all editors).

**Comment by mjibson** [comment] 2018-09-06 18:59
After discussion: we are leaving this as is for 2.1. We may make a change in 2.2 to detect this case and error, but we consider it rare enough that it's not a priority now.

**Comment by dt** [comment] 2019-07-11 22:13
I think we might want to disallow explicit schemas with bundle formats -- the benefits of it are an edge case and the potential mistakes, as this shows, are subtle.

**Comment by mwang1026** [comment] 2020-11-18 18:57
Pretty edgy so closing. Can reopen if we keep encountering this.

**Closed by mwang1026** 2020-11-18 18:57 UTC
Labels: A-bulkio, C-bug, C-qa, S-3-ux-surprise
