### ISSUE TITLE
sql: invalid datum type given with an apply join

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#59882] opened 2021-02-06 02:13 UTC
We get a `invalid datum type given: string, expected varbit` panic (converted by the vectorized engine into an internal error) on the following query:
```
WITH
  with_2675 AS (SELECT * FROM (VALUES ('', (SELECT ''))) AS tab_8229 (col_14424, col_14425))
SELECT
  (
    SELECT
      cte_ref_793.col_14424
    WHERE
      EXISTS(
        SELECT
          NULL
        WHERE
          ''
          IN (
              (
                SELECT
                  NULL
                FROM
                  (VALUES (NULL), ((SELECT B'101100110111011110011100101001110000111001110' FROM (VALUES (0)) AS tab_8238 (col_14434))))
                    AS tab_8239 (col_14436)
                ORDER BY
                  tab_8239.col_14436 DESC
                LIMIT
                  1
              ),
              ''
            )
      )
  ),
  cte_ref_793.col_14425
FROM
  with_2675 AS cte_ref_793;
```

Jira issue: CRDB-3216

**Comment by jordanlewis** [comment] 2023-01-05 01:48
No longer true:

```
demo@127.0.0.1:26257/defaultdb> WITH
                             ->   with_2675 AS (SELECT * FROM (VALUES ('', (SELECT ''))) AS tab_8229 (col_14424, col_14425))
                             -> SELECT
                             ->   (
                             ->     SELECT
                             ->       cte_ref_793.col_14424
                             ->     WHERE
                             ->       EXISTS(
                             ->         SELECT
                             ->           NULL
                             ->         WHERE
                             ->           ''
                             ->           IN (
                             ->               (
                             ->                 SELECT
                             ->                   NULL
                             ->                 FROM
                             ->                   (VALUES (NULL), ((SELECT B'101100110111011110011100101001110000111001110' FROM (VALUES (0)) AS tab_8238 (col_14434))))
                             ->                     AS tab_8239 (col_14436)
                             ->                 ORDER BY
                             ->                   tab_8239.col_14436 DESC
                             ->                 LIMIT
                             ->                   1
                             ->               ),
                             ->               ''
                             ->             )
                             ->       )
                             ->   ),
                             ->   cte_ref_793.col_14425
                             -> FROM
                             ->   with_2675 AS cte_ref_793;
ERROR: unimplemented: apply joins with subqueries in the "inner" and "outer" contexts are not supported
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/66447/v23.1
```

I guess it's now a dupe of #66447.

**Closed by jordanlewis** 2023-01-05 01:48 UTC
Labels: C-bug, T-sql-queries
