### ISSUE TITLE
storage: Replica.withRaftGroupLocked panic

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#24406] opened 2018-04-02 14:00 UTC
Seen on [sentry](https://sentry.io/cockroach-labs/cockroachdb/issues/511068961/) running on v1.2-alpha.20171204: `runtime error: invalid memory address or nil pointer dereference`. The code in question is:

```
		if shouldCampaignOnCreation {
			log.VEventf(ctx, 3, "campaigning")
			if err := raftGroup.Campaign(); err != nil {
				return err
			}
			if fn := r.store.cfg.TestingKnobs.OnCampaign; fn != nil {
				fn(r)
			}
		}
```

Line 594 is the `raftGroup.Campaign` call. Earlier in the function we allocated `raftGroup` so I'm not clear on how a nil pointer dereference could be occurring. @bdarnell or @tschottdorf Any thoughts?

**Comment by bdarnell** [comment] 2018-04-02 16:11
Sounds like a duplicate of #20629, fixed in #20704 (on dec 15).

**Closed by bdarnell** 2018-04-02 16:11 UTC
