### ISSUE TITLE
kv: cluster unavailability in proximity to node drain

### ISSUE THREAD

**Issue by ajstorm** [cockroachdb/cockroach#119523] opened 2024-02-22 16:52 UTC
On the DRT cluster, we're seeing a brief period of complete unavailability around the time that we're draining a node.  The recently introduced chaos script periodically drains/kills/disk-stalls nodes and then recovers the outage.  In a recent run, we're seeing that half of all ranges become unavailable: 

<img width="1164" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/58905ec2-98ef-4013-aa5e-1f2b913a00b2">

At the same time, the foreground workload drops to zero momentarily:

<img width="836" alt="image" src="https://github.com/cockroachdb/cockroach/assets/18447034/bac590b7-1762-46fa-a653-01cb1f550b68">

This is being discussed further [here](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1708616468236599).

Jira issue: CRDB-36268

**Comment by kvoli** [comment] 2024-03-01 16:35
Logs are available [here](https://cockroachlabs.slack.com/archives/C05FHJJ0MD0/p1709065167166279?thread_ts=1708616468.236599&cid=C05FHJJ0MD0) (internal).
Metrics are available [here](https://grafana.testeng.crdb.io/d/J-yAVzkVddd/detailed?orgId=1&from=1708616101142&to=1708616703335&var-cluster=teamcity-13629094-1705818598-51-n6cpu16&var-cluster=cct-232&var-DS_PROMETHEUS=Prometheus&var-node=All&var-rate_interval=30s) (internal)

The cause of the minute long outage appears to be a combination of **stopping a node** (`n9`) **at the same time as a rejoined node was behind** (`n11`), resulting in unavailable ranges  until the rejoined node caught up.


**Timeline**

- `14:50:54` `n11` rejoins cluster, begins failing liveness heartbeats (i/o timeout conn errors)
![image](https://github.com/cockroachdb/cockroach/assets/39606633/ee869449-b529-4b6f-9780-c92667934acb)
- `15:37:13` `n11` begins successfully heart beating liveness, replicas still unavailable and circuit breakers are tripped. Local SQL traffic (using `n11`) as a gateway is failing due to DistSender fast failing on circuit breaker errors. #118435 Would prevent the first 60s unavailability and #118266 (merged) which retries circuit breaker errors, limiting the unavailability when the breaker trips.
- `15:37:25` `n9` drain starts
- `15:37:58` `n9` drain complete successfully and shuts down. Note here that `n11` is still not caught up on its raft log for all replicas. Any RF=3 ranges which include both `n11` and `n9` may now be unavailable until `n11` is caught up, or `n9` rejoins and catches up. e.g.
```
W240222 15:38:07.471032 246907619 sql/conn_executor_exec.go:1592 ⋮ [T3,Vapplication,n1,client=10.142.1.104:51010,hostssl,user=root] 136018  txn rollback failed: replica unavailable: (n11,s11):23 unable to serve request to r15935:‹/Tenant/3/Table/107/1/1{145/5-303/6}› [(n9,s9):24, (n1,s1):20, (n11,s11):23, next=25, gen=172, sticky=1706217568.979394919,0]: lost quorum (down: (n9,s9):24,(n1,s1):20); closed timestamp: 1708615739.511423774,0 (2024-02-22 15:28:59); raft status: {"id":"17","term":500,"vote":"17","commit":458661987,"lead":"0","raftState":"StatePreCandidate","applied":458661987,"progress":{},"leadtransferee":"0"}: have been waiting 61.00s for slow proposal EndTxn(commit) [/Tenant/3/Table/107/1/‹1150›/‹3›/‹2›/‹1›], [txn: e9e05345]
```
![image](https://github.com/cockroachdb/cockroach/assets/39606633/20cad4f0-90c8-4953-9cfd-ff172e2ac263)
![image](https://github.com/cockroachdb/cockroach/assets/39606633/b4b2ac90-7fc6-4e7d-b293-9484e3316632)
- `15:38:15` QPS drops to 0
![image](https://github.com/cockroachdb/cockroach/assets/39606633/e30867ea-9fc8-42e6-baff-e1a91f2af71b)
- `15:39:15` CPU spikes to 100% on all nodes begin failing liveness heartbeats
![image](https://github.com/cockroachdb/cockroach/assets/39606633/ce10cf82-9844-4091-8dae-2444ba176e42)
- `15:39:30` `n11` is caught up on all raft logs, QPS begins climbing back up.
- `15:44:48` `n9` rejoins.

We could dig further, in particular why the CPU went to 100% and liveness heartbeats failed in the second half of the outage. Possibly thundering herd situation with retries after the initial unavailability but am uncertain -- the result would be the same until there were less unavailable ranges, which the workload runners would all end up stuck on (fixed concurrency), until the circuit breakers tripped (around `15:39:00`).

This situation could be prevented by not restarting `n9` quicker, or allowing `n11` to catch up before stopping `n9`. The situation was also probably worsened by `n11` getting leases while being behind with an inverted LSM:

![image](https://github.com/cockroachdb/cockroach/assets/39606633/84c8ddee-d285-45de-9610-238b7ed558ed)

These would be shed promptly with #118866.

**Comment by kvoli** [comment] 2024-03-01 16:45
From an internal conversation:

> Providing programatic checks would be great here, either as an endpoint or a pre-check for drain/stopping. Logging loudly in a drain would be a start, something like querying the leaseholder for each range the node has a replica for and checking whether any other replicas are in StateProbe or log is behind by more than X.

**Comment by kvoli** [comment] 2024-03-05 19:25
Filed https://github.com/cockroachdb/cockroach/issues/119952

Closing this issue as root cause has been identified.

**Closed by kvoli** 2024-03-05 19:25 UTC
Labels: C-bug, A-admission-control, A-kv, T-kv, O-testcluster, P-1
