### ISSUE TITLE
sql: auto array type cast from '{}' in column default definition for better pg compatibility

### ISSUE THREAD

**Issue by kimxogus** [cockroachdb/cockroach#33341] opened 2018-12-24 07:02 UTC
**Is your feature request related to a problem? Please describe.**
I'm using scala backend and https://github.com/slick/slick and https://github.com/tminglei/slick-pg, and I'm trying to use cockroach with them.

slick-pg generates sql like below with array column defaults.

```sql
create table test {
  foo text[] default '{}'
}
```

In postgres, that SQL works.

But in cockroach, `Error: pq: expected DEFAULT expression to have type string[], but ''{}'' has type string` occurs and sql should be fixed as below.

```sql
create table test {
  foo text[] default '{}'::text[]
}
```

**Describe the solution you'd like**
Automatically cast `'{}'` to its own column type.

**Describe alternatives you've considered**
Modify https://github.com/tminglei/slick-pg to generate sql with type cast like `::text[]`, but I think fixing in cockroach would be better in pg-compatibility.

**Additional context**

**Comment by knz** [comment] 2018-12-24 12:54
This overlaps with, but is not fully duplicate of, #23299

**Comment by khalibartan** [comment] 2019-06-08 09:09
@jordanlewis Can you help me getting started with this one?

**Comment by jordanlewis** [comment] 2019-06-14 14:52
This issue requires adding some functionality to the "constant up-cast" system in CockroachDB. This subsystem lives in `pkg/sql/sem/tree/constant.go`. Its job is to take constants, which can either be numeric or string-like, and resolve them into real types in the type system.

The trouble in this case is that we don't have a way to upcast a string into an array. The relevant code here is `StrVal.ResolveAsType` in the file I mentioned above. You'll need to add a type switch for array types in the second half of that function, and reuse the array parsing code from `pkg/sql/sem/tree/parse_array.go` (`ParseDArrayFromString`) to actually get an array type out from the string.

Does that help?

**Closed** 2019-07-19 15:34 UTC
Labels: A-sql-pgcompat, A-sql-typing, C-enhancement, O-community
