### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestReplicaLeaseCounters

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6433] opened 2016-05-01 11:41 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/2f7d0f60f694357e12322c70e4c8f78c2ca8e81d

Stress build found a failed test:

```
=== RUN   TestReplicaLeaseCounters
W160501 06:55:02.144310 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160501 06:55:02.144365 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160501 06:55:02.147109 storage/replica_command.go:1440  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 1s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160501 06:55:02.148832 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
--- FAIL: TestReplicaLeaseCounters (0.01s)
	replica_test.go:712: metrics counters actual=2, expected=1
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
11 runs completed, 1 failures, over 27s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-01 16:45
Duplicate of #6420

**Closed by bdarnell** 2016-05-01 16:45 UTC
Labels: Robot, test-failure
