### ISSUE TITLE
sql: partial index corruption

### ISSUE THREAD

**Issue by klesniewski** [cockroachdb/cockroach#74385] opened 2022-01-03 13:33 UTC
**Describe the problem**

We have observed in our database, that after updating a row, queries leveraging a partial, unique index work as if row wasn't updated. This leads to wrong query results when the index is used. The problem seems to occur only if more than one index is defined on the table.

**To reproduce**

The problem is easily reproducible.

First we will start a CockroachDB node (single-node, but the behavior was originally observed in Cockroach Cloud cluster) and connect SQL client to it:

```bash
# Start CockroachDB
docker run -d --rm --name roach0 -p 26257:26257 cockroachdb/cockroach:v21.2.3 start-single-node --insecure

# Open SQL shell
docker exec -it roach0 ./cockroach sql --insecure
```

Then run the following SQL:
```sql
-- Create database with table and indexes
create database test;
use test;
create table assets (
  id             uuid not null default gen_random_uuid(),
  tenant_id      uuid not null,
  external_id    text,
  legacy_id      text not null,
  delete_time    timestamptz default null,

  constraint asset_ck_id unique (id)
);

create unique index asset_unique_external_id_per_tenant
  on assets(external_id, tenant_id)
  where delete_time is null
;

create unique index asset_unique_legacy_id_per_tenant
  on assets (legacy_id, tenant_id)
  where delete_time is null
;

-- Insert sample data
insert into assets (id,tenant_id,external_id,legacy_id,delete_time) VALUES
  ('d07dfac2-1384-4a3e-9bd6-5b7e63d5bcbf'::uuid,'f862c2b1-f949-4117-8fc8-dbdd7d5d352a'::uuid,'2-3231925','Qo4E89',NULL),
  ('3121b4e5-d1be-4d8c-9008-227fcd1d52b8'::uuid,'f862c2b1-f949-4117-8fc8-dbdd7d5d352a'::uuid,NULL,'5cOAr6','2021-11-26 18:13:17.314984+01')
;

-- Find asset by external ID
select * from assets
where external_id ='2-3231925' 
  and tenant_id='f862c2b1-f949-4117-8fc8-dbdd7d5d352a' 
  and delete_time is null
;
--                    id                  |              tenant_id               | external_id | legacy_id | delete_time
-- ---------------------------------------+--------------------------------------+-------------+-----------+--------------
--   d07dfac2-1384-4a3e-9bd6-5b7e63d5bcbf | f862c2b1-f949-4117-8fc8-dbdd7d5d352a | 2-3231925   | Qo4E89    | NULL
-- (1 row)

-- Set asset's external ID to null
update assets set external_id = null 
where id='d07dfac2-1384-4a3e-9bd6-5b7e63d5bcbf'
;

-- Again, find asset by external ID. This still returns the asset, even though it no longer has the external ID.
select * from assets
where external_id ='2-3231925' 
  and tenant_id='f862c2b1-f949-4117-8fc8-dbdd7d5d352a' 
  and delete_time is null
;
--                    id                  |              tenant_id               | external_id | legacy_id | delete_time
-- ---------------------------------------+--------------------------------------+-------------+-----------+--------------
--   d07dfac2-1384-4a3e-9bd6-5b7e63d5bcbf | f862c2b1-f949-4117-8fc8-dbdd7d5d352a | NULL        | Qo4E89    | NULL
-- (1 row)

-- Again, find asset by external ID using primary index (index selection). This correctly doesn't find any asset with the ID.
select * from assets@primary
where external_id ='2-3231925' 
  and tenant_id='f862c2b1-f949-4117-8fc8-dbdd7d5d352a' 
  and delete_time is null
;
--  id | tenant_id | external_id | legacy_id | delete_time
-- ----+-----------+-------------+-----------+--------------
-- (0 rows)
```

**Expected behavior**
Query should return correct results, regardless which index is used.

**Environment:**
 - CockroachDB version 21.2.3
 - Client app: `cockroach sql` and JDBC

gz#10904

**Comment by yuzefovich** [comment] 2022-01-04 03:56
cc @mgartner

**Comment by mgartner** [comment] 2022-01-04 15:32
Thanks for the report. We'll look into this right away.

The reproduction works on v21.2.3 and v21.1.12. The reproduction does not work on v20.2.8, so the bug may not be present on that version.

**Comment by mgartner** [comment] 2022-01-04 17:01
I've identified the problem and am working on a solution.

In the meantime, I've come up with a workaround to get around this issue. The bug is only present when two or more partial indexes have the same predicate expression. Therefore, the workaround is to add additional expressions to some of the partial indexes to make their expressions different. You'll need to be careful when changing the expressions to be sure that:

1. The partial index can still service all the queries it did before. Be sure that the query filters still imply the partial index expression.
2. The semantics of unique partial indexes does not change. Be sure that the same exact rows that were included in the index before the change are included after the change, no more and no less.

For the example above, here's a change to the indexes  that should prevent the bug. Assuming that the UUID `00000000-0000-0000-000000000000` is never created and the only query that uses the first index is the `SELECT` in the example, (1) and (2) should hold and it should not have side-effects on the application. But, if there are other queries that use the index that don't filter by `tenant_id`, they would not be able to use the new index.

```diff
 create unique index asset_unique_external_id_per_tenant
   on assets(external_id, tenant_id)
-  where delete_time is null
+  where delete_time is null and tenant_id != '00000000-0000-0000-0000-000000000000'
 ;
 
 create unique index asset_unique_legacy_id_per_tenant
   on assets (legacy_id, tenant_id)
   where delete_time is null
 ;
```

**Comment by alex-berger** [comment] 2022-01-05 08:04
What happens to already existing (potentially wrong) index data, is it fixed automatically (e.g. on CRDB version upgrade to version with fix)?

**Comment by mgartner** [comment] 2022-01-05 16:26
There are some subtle details which are required in order for this bug to be present:

1. A table must have two or more partial indexes, unique or non-unique, with identical `WHERE` clauses.
2. An UPDATE must be issued to the table which updates a column(s) included in one of the indexes but not another. For example:

```sql
CREATE TABLE t (
    a INT,
    b INT,
    c INT,
    INDEX a_idx (a) WHERE c IS NULL,
    INDEX b_idx (b) WHERE c IS NULL
);

-- This will cause corruption. b_idx does not include the updated
-- column, a, in indexed columns or in its WHERE clause.
UPDATE t SET a = 1;

-- This will not cause corruption because columns indexed by both
-- a_idx and b_idx are updated.
UPDATE t SET a = 1, b = 2;

-- This will NOT cause corruption because c is in the WHERE clause of
-- both a_idx and b_idx.
UPDATE t SET a = 1, c = 3;
```

-- 

> What happens to already existing (potentially wrong) index data, is it fixed automatically (e.g. on CRDB version upgrade to version with fix)?

@alex-berger you'll have to drop partial indexes and recreate them to ensure there is no corrupt indexes.

**Comment by alex-berger** [comment] 2022-01-05 19:09
@mgartner Hey, this is the always on never die CockroachDB, why do I have to track bug-reports to figure out whether I might have to drop and recreated indexes? I would really appreciate if (potentially) affected indexes would be automatically fixed without any interruption of service (let's call this online recreate) upon version upgrade (to the version that contains the fix).

Don't get me wrong, I am not ranting, but one reason we chose CockroachDB is because we don't need to have full time DBA wizards which spend their whole working-day keeping database healthy and running :-).

**Closed** 2022-01-05 19:43 UTC
Labels: C-bug, O-community, S-0-visible-logical-error, T-sql-queries

**Comment by mgartner** [comment] 2022-01-05 20:11
@alex-berger I agree that manually recreating indexes is tedious and far from ideal. I've created an issue to track your suggestion: #74473.

Unfortunately, there's no existing mechanisms in 21.1 or 21.2 that we can utilize to automatically recreate potentially corrupt indexes for this bug. So I'm sorry to say that manually recreating them is the only option.

Thanks again for the detailed bug report. Happy New Year!
