### ISSUE TITLE
build: stale libedit build causes errors in TestLint

### ISSUE THREAD

**Issue by danhhz** [cockroachdb/cockroach#30324] opened 2018-09-17 20:29 UTC
#30306 failed TestLint with the following error. Oddly, the first build was fine and the only changes between them was tweaking a bit of (clearly unrelated) go code, but now it's happened twice in a row. Also happened to #29380.

#20867 is the only reference I found, but it was closed as fixed months ago

```
=== PAUSE TestLint/TestVet
        lint_test.go:1089: 
            In file included from wrap-common.c:1:
        lint_test.go:1089: 
            In file included from vendor/github.com/knz/go-libedit/unix/src/libedit-common.c:1:
        lint_test.go:1089: 
            vendor/github.com/knz/go-libedit/unix/src/c-libedit/common.c:371:21: warning: passing 'wint_t *' (aka 'unsigned int *') to parameter of type 'wchar_t *' (aka 'int *') converts between pointers to integer types with different sign [-Wpointer-sign]
        lint_test.go:1089: 
            vendor/github.com/knz/go-libedit/unix/src/c-libedit/histedit.h:267:37: note: passing argument to parameter here
        lint_test.go:1089: 
            In file included from wrap-search.c:1:
        lint_test.go:1089: 
            In file included from vendor/github.com/knz/go-libedit/unix/src/libedit-search.c:1:
        lint_test.go:1089: 
            vendor/github.com/knz/go-libedit/unix/src/c-libedit/search.c:607:20: warning: passing 'wint_t *' (aka 'unsigned int *') to parameter of type 'wchar_t *' (aka 'int *') converts between pointers to integer types with different sign [-Wpointer-sign]
        lint_test.go:1089: 
            vendor/github.com/knz/go-libedit/unix/src/c-libedit/histedit.h:267:37: note: passing argument to parameter here
```

**Comment by benesch** [comment] 2018-09-17 20:35
The problem is related to the fact that the agent ran a build on https://github.com/cockroachdb/cockroach/pull/30309, which targets 2.0 and vendors the old buggy version of go-libedit. Inexplicably that build succeeded, and yet it seems to have polluted the build cache?!

**Comment by knz** [comment] 2018-09-17 22:03
what do we do about it?

**Comment by benesch** [comment] 2018-09-17 22:47
I think we can just let the broken agents cycle out for now. We’re not
backporting to 2.0 frequently right now. Won’t have time to track down for
a while.

**Comment by petermattis** [comment] 2019-01-17 16:18
Dan's original error is exactly https://github.com/cockroachdb/cockroach/issues/34059. Perhaps this was an early indication of the funky `go vet` behavior with caching. I'm closing this as the upstream warnings are now fixed, so I don't think there is anything to do here.

**Closed by petermattis** 2019-01-17 16:18 UTC
Labels: A-build-system, C-investigation
