### ISSUE TITLE
YCSB Regression since December

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34426] opened 2019-01-30 21:05 UTC
Test | Change |
-- | -- 
YCSB-A | 4.2% regression
YCSB-B | 21.2% regression
YCSB-C | 44% regression
YCSB-F | 5% improvement

**YCSB-A**
5 runs in December Alpha

Test | AVERAGE of Read Throughput | AVERAGE of Update Throughput | AVERAGE of Total Throughput | AVERAGE of Read p95 Latency | AVERAGE of Write p95 Latency
-- | -- | -- | -- | -- | --
YCSB - Normal | 8,629,530 | 8,629,568 | 17,259,099 | 3.88 | 6.42

vs. 1/30 master

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0        8268509        13780.8      1.2      0.9      2.8      6.6    176.2  read
  600.0s        0        8269034        13781.7      3.4      3.0      7.1     11.0    704.6  update

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0       16537543        27562.6      2.3      1.8      5.8     10.0    704.6  
```

YCSB-A is about a 4.2% regression

**Comment by awoods187** [comment] 2019-01-30 21:12
**YCSB-B**
4 runs on December Alpha

Test | AVERAGE of Read Throughput | AVERAGE of Update Throughput | SUM of Total Throughput | AVERAGE of Read p95 Latency | AVERAGE of Write p95 Latency
-- | -- | -- | -- | -- | --
YCSB - Normal | 31,540,575 | 1,658,257 | 166,408,746 | 2.16 | 7.44

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0       24922645        41537.7      1.3      1.0      3.3      6.3    209.7  read
  600.0s        0        1310049         2183.4      4.1      3.3      9.4     21.0     65.0  update

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0       26232694        43721.1      1.5      1.1      3.9      7.3    209.7 
```

**Comment by awoods187** [comment] 2019-01-30 21:52
**YCSB-C**
4 runs in December Alpha 

Test | AVERAGE of Total Throughput | AVERAGE of Total p95 Latency
-- | -- | --
YCSB - Normal | 53,154,147 | 1.40

```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__total
  600.0s        0       29534334        49223.9      1.3      1.0      3.1      5.5    209.7  read

_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0       29534334        49223.9      1.3      1.0      3.1      5.5    209.7
```

**Comment by awoods187** [comment] 2019-01-30 22:33
**YCSB-F**

Test | AVERAGE of Total Throughput | AVERAGE of Total p95 Latency
-- | -- | --
YCSB - Normal | 7,867,798 | 8.22


```
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
  600.0s        0        8287391        13812.3      4.6      3.1     12.1     32.5    234.9  
```

**Comment by nvanbenschoten** [comment] 2019-02-12 00:53
@awoods187 thanks for putting this all together. I'm pretty skeptical about the 20-40% swings you're seeing. I took a look at whether I could reproduce them by comparing the december (`v2.2.0-alpha.20181217`), january (`v2.2.0-alpha.20190114`), and february (`v2.2.0-alpha.20190211`) alpha. Here are my results:

<img width="1095" alt="screen shot 2019-02-11 at 7 39 07 pm" src="https://user-images.githubusercontent.com/5438456/52603419-bddc0180-2e34-11e9-9089-45853743a6f1.png">

It looks like the only workload with a statistically significant change is ycsb-B, which dropped by about **3%** on both AWS and GCP between the December alpha and the February alpha. We can see from the January results that the drop appears to have accured between December and January.

This workload is actually almost idential to kv95, other than that it performs UPDATEs instead of UPSERTs and works over a zipf distribution. Interestingly, in [roachperf](https://crdb.io/perf/?filter=&view=kv95%2Fencrypt%3Dfalse%2Fnodes%3D1&cloud=gce) we see somewhat of a dip right at the beginning of the year on both single and multi-node kv95. I'm going to see if I can isolate this drop to a smaller date range.

**Comment by nvanbenschoten** [comment] 2019-02-14 01:04
I finally bisected the regression I was chasing down to this change: 8085992fb79000eefa0a65852d3b04940f9f1975. It turns out that we began sampling plans fairly aggressively after that point, and sampling entire query plans isn't cheap. 

Here's a CPU profile from YCSB B on that SHA showing `planToTree` taking over **2%** of CPU usage.

<img width="1176" alt="screen shot 2019-02-13 at 7 44 38 pm" src="https://user-images.githubusercontent.com/5438456/52754433-82723c00-2fc8-11e9-9c0d-55b5682a1eb6.png">

Fortunately, it looks like @celiala has already improved the situation in 8085992fb79000eefa0a65852d3b04940f9f1975! When I profile past that point, I don't see `planToTree`.

I'm created a change (#34887) that should remove a few allocations from those code paths and speed up `planToTree` marginally. Past that point, I'm going to close this issue as it appears that the big dip in January has already been addressed.

**Closed** 2019-02-14 01:26 UTC
