### ISSUE TITLE
sql+cli: dump should work with PKs named other than "primary"

### ISSUE THREAD

**Issue by jtescher** [cockroachdb/cockroach#18500] opened 2017-09-15 00:17 UTC
It looks like the primary key constraint name has to be "primary" for sql dump to work, however schema migration tools often have their own naming conventions e.g. liquibase does "pk_[tablename]" so this could be a somewhat common situation.

Steps to reproduce:

```sql
CREATE DATABASE liquibase;
CREATE TABLE liquibase.episodes (id INT NOT NULL, season INT NULL, num INT NULL, title STRING NULL, stardate DECIMAL NULL, CONSTRAINT "pk_episodes" PRIMARY KEY (id), FAMILY "primary" (id, season, num), FAMILY fam_1_title (title), FAMILY fam_2_stardate (stardate));

CREATE DATABASE standard;
CREATE TABLE standard.episodes (id INT NOT NULL, season INT NULL, num INT NULL, title STRING NULL, stardate DECIMAL NULL, CONSTRAINT "primary" PRIMARY KEY (id), FAMILY "primary" (id, season, num), FAMILY fam_1_title (title), FAMILY fam_2_stardate (stardate));
```

Running `./cockroach dump liquibase --insecure` will now error with:

```
Error: pq: column name "rowid" not found
```

Even though `./cockroach dump standard --insecure` works as expected

(client and server version: v1.1-beta.20170907)

**Comment by mjibson** [comment] 2017-09-15 19:15
I wasn't able to reproduce this:

```
root@:26257/> CREATE DATABASE liquibase;
CREATE DATABASE

Time: 31.434091ms

root@:26257/> CREATE TABLE liquibase.episodes (id INT NOT NULL, season INT NULL, num INT NULL, title STRING NULL, stardate DECIMAL NULL, CONSTRAINT "pk_episodes" PRIMARY KEY (id), FAMILY "primary" (id, season, num), FAMILY fam_1_title (title), FAMILY fam_2_stardate (stardate));CREATE TABLE

Time: 59.355878ms

root@:26257/> 
root@:26257/> CREATE DATABASE standard;
CREATE DATABASE

Time: 64.314378ms

root@:26257/> CREATE TABLE standard.episodes (id INT NOT NULL, season INT NULL, num INT NULL, title STRING NULL, stardate DECIMAL NULL, CONSTRAINT "primary" PRIMARY KEY (id), FAMILY "primary" (id, season, num), FAMILY fam_1_title (title), FAMILY fam_2_stardate (stardate));
CREATE TABLE

Time: 40.491742ms
```

```
~/src/github.com/cockroachdb/cockroach (master)$ ./cockroach dump --insecure standard
# Server version: CockroachDB CCL 4969e28 (linux amd64, built 2017/09/15 18:56:08, go1.9) (same version as client)
# Cluster ID: dcd3ae38-3530-4b48-85df-8c345d2f286f
CREATE TABLE episodes (
        id INT NOT NULL,
        season INT NULL,
        num INT NULL,
        title STRING NULL,
        stardate DECIMAL NULL,
        CONSTRAINT "primary" PRIMARY KEY (id ASC),
        FAMILY "primary" (id, season, num),
        FAMILY fam_1_title (title),
        FAMILY fam_2_stardate (stardate)
);
~/src/github.com/cockroachdb/cockroach (master)$ ./cockroach dump --insecure liquibase
# Server version: CockroachDB CCL 4969e28 (linux amd64, built 2017/09/15 18:56:08, go1.9) (same version as client)
# Cluster ID: dcd3ae38-3530-4b48-85df-8c345d2f286f
CREATE TABLE episodes (
        id INT NOT NULL,
        season INT NULL,
        num INT NULL,
        title STRING NULL,
        stardate DECIMAL NULL,
        CONSTRAINT pk_episodes PRIMARY KEY (id ASC),
        FAMILY "primary" (id, season, num),
        FAMILY fam_1_title (title),
        FAMILY fam_2_stardate (stardate)
);
```

I tried inserting a row into liquibase.episodes, dumping, and injecting the dump, too. Everything worked as intended. What version are you running? Does your client and server version match? Dump has changed since 1.0 and so if the versions mismatch that might explain it.

**Comment by jtescher** [comment] 2017-09-15 20:42
Ah you're right! I was using v1.1-beta.20170907, but it is working in master so it's already been fixed. Thanks for looking into it.

**Comment by jtescher** [comment] 2017-10-14 19:44
It looks like this is in master but didn't make it into v1.1.0. Could this get backported to the 1.1.x series?

**Comment by mjibson** [comment] 2017-10-16 17:26
Can you please post the error you are seeing and the version strings from the server and client? The 1.1 fork from master happened just recently, and shouldn't have affected this.

**Comment by jtescher** [comment] 2017-10-16 17:42
Steps to reproduce using docker and v1.1.0 of client and server:

1. (tab1) docker run --name cockroach cockroachdb/cockroach:v1.1.0 start --insecure
2. (tab 2) docker exec -it cockroach bash
3. (tab 2 - docker) ./cockroach sql --insecure
4. (tab 2- docker - cli) create table with different pk name:

```
CREATE DATABASE liquibase;
CREATE TABLE liquibase.episodes (id INT NOT NULL, season INT NULL, num INT NULL, title STRING NULL, stardate DECIMAL NULL, CONSTRAINT "pk_episodes" PRIMARY KEY (id), FAMILY "primary" (id, season, num), FAMILY fam_1_title (title), FAMILY fam_2_stardate (stardate));
```
5. (tab 2 - docker - cli) \q
6. (tab 2 - docker) ./cockroach dump liquibase --insecure

Fails with the following error:
```
# Server version: CockroachDB CCL v1.1.0 (linux amd64, built 2017/10/12 14:50:18, go1.8.3) (same version as client)
# Cluster ID: 7174cc4d-cf5a-458d-bc2b-e9bb47c2db57
CREATE TABLE episodes (
	id INT NOT NULL,
	season INT NULL,
	num INT NULL,
	title STRING NULL,
	stardate DECIMAL NULL,
	CONSTRAINT pk_episodes PRIMARY KEY (id ASC),
	FAMILY "primary" (id, season, num),
	FAMILY fam_1_title (title),
	FAMILY fam_2_stardate (stardate)
);
Error: pq: column name "rowid" not found
Failed running "dump"
```

**Comment by mjibson** [comment] 2017-10-16 19:20
Reproduced. Thanks for the report.

**Comment by mjibson** [comment] 2017-10-20 20:39
This will be in the 1.1.2 release, which is probably a few weeks out. It just missed the deadline for 1.1.1.

**Closed** 2017-11-07 08:32 UTC
Labels: bug, community-answered
