### ISSUE TITLE
sql: crash in bytes monitor under V(2)

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#28691] opened 2018-08-16 11:03 UTC
`make test PKG=./pkg/kv/ TESTFLAGS='-v --verbosity=1'` reliably triggers this, I think it's this code: https://github.com/cockroachdb/cockroach/blob/d556fa9bfb9bcfc3f98b35207d4c3233b895b8b9/pkg/util/mon/bytes_usage.go#L391

This could be an issue in production when using `logspy` for debugging.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x45fc6d6]

goroutine 23678 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.contextBottomTag(0x0, 0x0, 0x5d1b6e0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:45 +0x26
github.com/cockroachdb/cockroach/pkg/util/log.contextLogTags(0x0, 0x0, 0xc4210a72f8, 0x0, 0x8, 0xc4215fdb48, 0x435f840, 0xc420203160)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log_context.go:55 +0x39
github.com/cockroachdb/cockroach/pkg/util/log.formatTags(0x0, 0x0, 0xc4210a7290, 0x45b903a)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:109 +0x66
github.com/cockroachdb/cockroach/pkg/util/log.MakeMessage(0x0, 0x0, 0x5f335b4, 0x16, 0xc4215fde00, 0x2, 0x2, 0x0, 0x0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:127 +0x58
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x0, 0x0, 0x1, 0x3, 0x5f335b4, 0x16, 0xc4215fde00, 0x2, 0x2)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:142 +0xc9
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x0, 0x0, 0x2, 0xc400000001, 0x5f335b4, 0x16, 0xc4215fde00, 0x2, 0x2)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:69 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.InfofDepth(0x0, 0x0, 0x1, 0x5f335b4, 0x16, 0xc4215fde00, 0x2, 0x2)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:113 +0x89
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).doStop(0xc421544500, 0x0, 0x0, 0x6407801)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:391 +0x3ae
github.com/cockroachdb/cockroach/pkg/util/mon.(*BytesMonitor).Stop(0xc421544500, 0x0, 0x0)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/util/mon/bytes_usage.go:384 +0x44
github.com/cockroachdb/cockroach/pkg/sql.(*txnState).finishExternalTxn(0xc42157d388)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/txn_state.go:259 +0x48
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).close(0xc42157d300, 0x64078c0, 0xc421596120, 0x2)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:706 +0x49e
github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx.func1(0xc42157d300, 0x64078c0, 0xc421596120, 0xc4202a2b80, 0xc421544280, 0xc420308510)
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:217 +0xcf
created by github.com/cockroachdb/cockroach/pkg/sql.(*internalExecutorImpl).initConnEx
        /Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/pkg/sql/internal.go:199 +0x275
```

**Comment by jordanlewis** [comment] 2018-08-21 11:33
Duplicate of #26887.

**Closed by jordanlewis** 2018-08-21 11:33 UTC
Labels: A-sql-execution
