### ISSUE TITLE
cdc: changefeed job stuck in reverting state.

### ISSUE THREAD

**Issue by shailendra-patel** [cockroachdb/cockroach#132160] opened 2024-10-08 11:57 UTC
On `drt-large` i am seeing Oldest protected timestamp age ~15 days. On digging found that there are two changefeeds job which are in reverting  state for days and holding the pts.
```sql
SELECT
->     id,
->     (ts/1000000000)::INT::TIMESTAMPTZ AS timestamp,
->     meta_type,
->     encode(meta, 'escape') AS meta,
->     num_spans,
->     crdb_internal.pb_to_json('cockroach.protectedts.Spans', spans) AS spans,
->     verified,
->     crdb_internal.pb_to_json('cockroach.protectedts.Target', target) AS target
-> FROM
->     system.protected_ts_records
-> ORDER BY
->     ts;
                   id                  |       timestamp        | meta_type |        meta         | num_spans | spans | verified |                target
---------------------------------------+------------------------+-----------+---------------------+-----------+-------+----------+---------------------------------------
  5fb4260a-4a78-4e93-88c8-7f58706c9651 | 2024-09-23 08:24:41+00 | jobs      | 1004661810832080897 |         0 | {}    |    f     | {"schemaObjects": {"ids": [142, 3]}}
  34526dca-9116-406e-95f3-6292f64bd1ca | 2024-09-24 06:51:14+00 | jobs      | 1004661906847956993 |         0 | {}    |    f     | {"schemaObjects": {"ids": [144, 3]}}
```

Job ids are `1004661810832080897`  and `1004661906847956993` 
Details of one of the job
```sql
roachprod@localhost:26257/defaultdb> show job 1004661906847956993;
 -[ RECORD 1 ]
job_id             | 1004661906847956993
job_type           | CHANGEFEED
description        | CREATE CHANGEFEED FOR TABLE tpcc.new_order INTO 'azure-event-hub://cdcdrt.servicebus.windows.net:9093?shared_access_key=redacted&shared_access_key_name=RootManageSharedAccessKey&tls_enabled=true&topic_name=new' WITH OPTIONS (diff, initial_scan = 'no', kafka_sink_config = '{"Flush": {"MaxMessages": 200, "Messages": 100,  "Frequency": "1s"}, "RequiredAcks": "ONE"}', metrics_label = 'azure_tpcc.new_order', updated)
statement          |
user_name          | root
status             | reverting
running_status     | NULL
created            | 2024-09-18 14:14:42+00
started            | 2024-09-18 14:14:43+00
finished           | NULL
modified           | 2024-09-24 09:03:26+00
fraction_completed | NULL
error              | protected timestamp records 34526dca-9116-406e-95f3-6292f64bd1ca as of 1727160673.903146881,0 (age 96h0m33.022646251s) exceeds job configured limit of 96h0m0s
coordinator_id     | 1
trace_id           | 1177570081829405783
execution_errors   | NULL

Time: 94ms total (execution 94ms / network 0ms)
```

Jira issue: CRDB-42856

**Comment by wenyihu6** [comment] 2024-10-08 21:16
Closing. We think we've found the root cause of this issue tracking in https://github.com/cockroachdb/cockroach/issues/132198.

**Closed by wenyihu6** 2024-10-08 21:16 UTC
Labels: C-bug, A-cdc, branch-master, T-cdc, O-testcluster, P-1
