### ISSUE TITLE
stability: missing range descriptors for node liveness data after unclean shutdown

### ISSUE THREAD

**Issue by cppforlife** [cockroachdb/cockroach#12580] opened 2016-12-27 06:16 UTC
Version used: 

```
Build Tag:   beta-20161215
Build Time:  2016/12/15 15:10:48
Platform:    linux amd64
Go Version:  go1.7.3
C Compiler:  gcc 4.9.2
```

I've recreated entire cluster (with prev data) after it was stopped uncleanly. Following error comes from the first node (other 2 nodes are not yet started). 

```
 65 storage/replica_command.go:1115  [n1,hb,range-lookup,s1,r1/1:/{Min-Table/11},@c4202eca00] range lookup of meta key /Meta1/System/NodeLiveness/1 found only non-matching ranges: []
goroutine 65 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x0, 0x1757c840, 0x2aaf5e0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:849 +0xa5
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x2ab0be0, 0xc400000004, 0x22a6317, 0x1a, 0x45b, 0xc420391540, 0x91)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:712 +0x7d5
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x7f66a3d46160, 0xc4207f2b40, 0xc400000004, 0x2, 0x1a58960, 0x3f, 0xc4208288d0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:146 +0x296
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x7f66a3d46160, 0xc4207f2b40, 0x1, 0xc400000004, 0x1a58960, 0x3f, 0xc4208288d0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:88 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x7f66a3d46160, 0xc4207f2b40, 0x1a58960, 0x3f, 0xc4208288d0, 0x2, 0x2)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:172 +0x7e
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).RangeLookup(0xc4202eca00, 0x7f66a3d46160, 0xc4207f2b40, 0x7f66a3d46878, 0xc42023ae10, 0x14938707e9c3907f, 0x0, 0x100000001, 0x1, 0x1, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:1115 +0xe67
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeCmd(0xc4202eca00, 0x7f66a3d46160, 0xc4207f2b40, 0x0, 0x0, 0x0, 0x7f66a3d46878, 0xc42023ae10, 0x0, 0x14938707e9c3907f, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica_command.go:130 +0x2a5
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).executeBatch(0xc4202eca00, 0x7f66a3d46160, 0xc4207f2b40, 0x0, 0x0, 0x7f66a3d46878, 0xc42023ae10, 0x0, 0x14938707e9c3907f, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:4005 +0x428
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).addReadOnlyCmd(0xc4202eca00, 0x7f66a3d46160, 0xc4207f2b40, 0x14938707e9c3907f, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1801 +0x2db
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).Send(0xc4202eca00, 0x7f66a3d46160, 0xc4207f2b40, 0x14938707e9c3907f, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:1302 +0x48f
github.com/cockroachdb/cockroach/pkg/storage.(*Store).Send(0xc420060380, 0x7f66a3d46160, 0xc4207f2a80, 0x14938707e9c3907f, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2479 +0x6c5
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc42014d620, 0x7f66a3d46160, 0xc4207f29f0, 0x0, 0x0, 0x100000001, 0x1, 0x1, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:187 +0x202
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:825 +0x2a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr(0xc420436000, 0xc42082bcc8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:245 +0x100
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal(0xc42022c840, 0x7f66a3d46218, 0xc420208e40, 0xc4203c6c08, 0xc420208e40, 0xc42077df28, 0xefe7d1)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:836 +0x1ed
github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch(0xc42022c840, 0x7f66a3d46218, 0xc420208e40, 0xc4203c6c08, 0xc4200141f8, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/server/node.go:858 +0xa0
github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext.func1(0x25d7a60, 0xc42022c840, 0xc420820180, 0xc4203c6be0, 0xc420820000)
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:189 +0x64
created by github.com/cockroachdb/cockroach/pkg/kv.(*grpcTransport).SendNext
	/go/src/github.com/cockroachdb/cockroach/pkg/kv/transport.go:192 +0x23c
```

- is this currently expected?
- how can I recover manually (keeping my data)?

**Comment by tamird** [comment] 2016-12-27 15:04
What version were you running before the shutdown? What version are you
running now, after the shutdown?

What is the cluster configuration (i.e. how many nodes, where are they
running, etc.)?

**Comment by cppforlife** [comment] 2016-12-27 20:29
> What version were you running before the shutdown? What version are you
running now, after the shutdown?

same version before and after.

> What is the cluster configuration (i.e. how many nodes, where are they
running, etc.)?

- 3 nodes test cluster (same before and after)
- nodes start one by one, stuck on the first one
- running on 3 diff machines in the same az on aws
- cluster was running ok before termination
- machines have been terminated unexpectedly without some disk changes flushed

**Comment by tamird** [comment] 2016-12-27 20:32
On Tue, Dec 27, 2016 at 3:29 PM, Dmitriy Kalinin <notifications@github.com>
wrote:

> same version before and after.
>
And what version is that?

>
>    - nodes start one by one, stuck on the first one
>
> So the error manifests with only one node running? That's surprising,
since that node should not be able to make progress without at least one
other running node. Does the error manifest on all three nodes, or just a
particular one?

Finally: are you able to share your data with us?

**Comment by cppforlife** [comment] 2016-12-27 21:33
@tamird see initial comment for version info.

> since that node should not be able to make progress without at least one
other running node.

first node is configured as bootstrap node (per docs i believe) so it's not trying to join any others nodes (--join is not specified). or is the recommended configuration to have all nodes started in parallel and provide same --join flag to all of them (that would be great)?

> are you able to share your data with us?

in this case i've only imported example data from gen command.

**Comment by tamird** [comment] 2016-12-27 21:46
Since the cluster was already running with 3 nodes, it is probable (certain) that all the ranges have been replicated to all three nodes. Each range requires quorum to make progress, so any one node, without at least one other, would not be able to make progress (and thus shouldn't be able to produce the error you're seeing).

In this case, sharing your data with us would let us look at your meta records, which is where the problem appears to lie.

**Comment by cppforlife** [comment] 2016-12-27 22:36
@tamird will try to repro again (pretty sure this would happen everytime if i just remount disk as ro) and reboot the cluster.

> Each range requires quorum to make progress, so any one node, without at least one other, would not be able to make progress

but it will still come up i assume?

**Comment by cppforlife** [comment] 2016-12-27 23:27
by "come up" i mean not crash (even after initial start sequence finished). 

if process dies due to its background activity it will be restarted, but im assuming that for it to become healthy it needs to see other nodes (based on your above comment), but if other nodes are in the similar cycle there is likelihood that they will keep on missing each other as they crash. in my case other nodes are not started until first node is started hence no progress will be made. (i know almost nothing on what cockroachdb bootstrap process looks like so this is all speculation on my part.)

**Comment by a-robinson** [comment] 2016-12-28 15:09
This may an old bug that's now getting triggered by the somewhat new migration code causing us to try kv operations as soon as a node starts up. It's not easy to reproduce, though, at least not without more information about how you got into this state.

Would you mind sharing the rest of the logs from the node that's failing?

**Comment by knz** [comment] 2016-12-29 14:18
Ideally you would package and archive of your data directory (containing logs & sst files) for all 3 nodes so we can investigate.

**Comment by bdarnell** [comment] 2017-01-05 06:01
Two shots in the dark: 

1. If the system clocks moved significantly backwards while the cluster was down (so that the new processes see a time "before" the original processes started), I think we might see this crash. 

2. Range lookups use inconsistent reads which bypass various safety checks. If this were a cluster of more than 3 nodes, I'd think that maybe an inconsistent read was hitting a replica that was in the process of being created or destroyed and seeing it containing no data. On a three-node cluster no replicas should be created or destroyed after the initial replication (except when they are created in-place via splits), but maybe at some point during the unclean shutdown the node looked "dead" and the replicate queue kicked in. 

In any case, we need at least the logs and preferably the full data directories to figure out what's going on here. If you're unwilling to share the full data directories, run `cockroach debug range-descriptors ./cockroach-data` and share the output. 

> or is the recommended configuration to have all nodes started in parallel and provide same --join flag to all of them (that would be great)?

The first time the first node is started, it must not have a `--join` flag. Once this initialization is completed, you can restart the first node with a `--join` flag; the first node is no longer special at this point and can use the same configuration as all the other nodes. When restarting a cluster with existing data but all servers down, I would recommend starting them all at once.

**Comment by dianasaur323** [comment] 2017-04-06 16:21
@cppforlife Are you still experiencing this issue? I'm going to close it for now as this is dated, but feel free to re-open if necessary.

**Closed by dianasaur323** 2017-04-06 16:21 UTC
Labels: bug, community-questions, investigation
