### ISSUE TITLE
kv: the RangeCache is sometimes clobbered with old descriptors

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#10751] opened 2016-11-17 01:26 UTC
A funky phenomenon seems to be happening every once in a while in a test: up-to-date descriptors from the `RangeCache` are clobbered by older (pre-split) versions.

This seems to happen in two distinct cases:

1) a RangeLookup request returns two versions of a range descriptor (presumably one of them is an intent). The old version of the descriptor is inserted into the cache, replacing all overlapping descriptors (which were newer).
Interestingly, the cache did previously have the newest version of a descriptor. Also, all this happens a good deal of time after the range in question has been split, so it's dubious that an intent on the descriptor is still present.

2) the cache is checked for range 1, and it's a miss. Range 1 is gossiped, not read from the database, and the descriptor we get from gossip is inserted into the cache. This seems particularly bad, since the version of the descriptor in gossip in this test seems to be particularly old (it covers /Min - /Max, so it completely wipes the cache).

I'm not sure of the whole story yet; investigating.

cc: @tamird

**Comment by tamird** [comment] 2016-11-17 15:36
Woof, this does seem bad (and certainly possible). cc @nvanbenschoten as well.

**Comment by andreimatei** [comment] 2016-11-18 00:49
So it would appear that a number of things are funky:

1. After running a `LookupRange` RPC, we insert *all* the descriptors we got back into the cache:
https://github.com/cockroachdb/cockroach/blob/99f09b6/pkg/kv/range_cache.go#L369
This is a problem because, if we've gotten two versions of the same descriptor (a committed one and an intent), the intent will be inserted second and evict the committed. This is contrary to what the code just above is trying to do, which is use the committed and have the intent be magically inserted through an `EvictionToken` if the committed proved to be stale.
2. If we've gotten prefetched descriptors, we have ignored whatever intents they might have. We insert these descriptors in the cache, possibly overriding newer ones.
3. But! it is still possible, in the prefetches, to return two versions of the same descriptor, if, after a split, the intent on one side is resolved and the intent on the other side is not resolved. And so we insert both in the cache, overriding each other (they overlap).
4. The descriptor for the first range come from gossip, so it can easily be stale. Whenever someone wants to do a lookup on `KeyMin` (and people do lookups on `KeyMin` all the time because `meta(Meta1Prefix) == KeyMin`), we insert it in the cache. Since it's stale, it will likely be evicted from the cache quickly, only to be inserted again soon after.

I think I'll do a couple of things:
1. Don't insert both a committed version and an intent version - stick to the committed.
2. Put timestamps on cache entries and only evict them if they're being replaced by newer ones. The timestamps would be the MVCC timestamps of the descriptors.
3. Return intents for the prefetched ranges, like we do for the regular looked up one, and insert a coherent set of prefetched ranges in the cache. I guess the problem is that intents don't map 1-1 with the committed versions, so I'll extend the response to include a set of intents for every committed descriptor.
4. Never cache range 0. We might want a path to read the descriptor from the database if gossip proves stale.


I suspect this is all exacerbated because intents on descriptors tend to linger around longer than other intents, since, on a split, I think we fail to synchronously resolve the intent on the right side.
I think I've seen this before and talked to @bdarnell about it, but I remember there was little motivation to fix it. Does that sound right?

**Comment by bdarnell** [comment] 2016-11-18 08:12
The four proposed changes SGTM.

Range descriptors live in two places: in the ranges themselves, and in the meta ranges. We don't synchronously resolve the intent that lives in the new RHS range (and in the past we had other problems because the transaction record lived on the HRS too). However, the intents on the meta ranges are resolved normally (not synchronously, but immediately after the transaction commit). They shouldn't generally live longer than any other intents. 

One way in which meta descriptor intents are special is that they are almost exclusively resolved asynchronously - either after the transaction commits, or after an inconsistent read notices them. They're almost never cleaned up synchronously due to a consistent read. This means that if the intentResolver is having trouble (#10733), it affects meta range descriptors more than other things.

**Comment by andreimatei** [comment] 2016-11-18 15:53
Thanks for the info, Ben.

I'm wondering what people think about this whole idea of doing inconsistent reads for descriptors. Is it really worth it? I guess the idea is to not block large numbers of transactions while a split is happening. But a) is the split txn expected to take very long? and b) we'd only be blocking nodes that don't have a descriptor in their cache.
Even if we keep the inconsistent reads, I'm wondering if it'd be a good idea for the owners of meta ranges to try to resolve the intents in a non-blocking manner before returning the result. That would cover the case where the transaction holding the intent has already committed. If it hasn't, we could remember that information for a few seconds and not try this synchronous resolving again.
I'm thinking this would help a thundering herd of transactions operating on a hot spot that just split - I think it's possible for a bunch of transactions to find out that they have a stale descriptor all at once, at which point they go to the meta range and race with the intent resolution, so they might all get the stale version + intent back.

**Comment by tamird** [comment] 2016-11-18 16:01
Recall that range descriptors are also updated on rebalancing, not just on
splits/merges.

**Comment by bdarnell** [comment] 2016-11-19 03:38
> this whole idea of doing inconsistent reads for descriptors. Is it really worth it?

This is not just an optimization; it's required in some situations. You may need to see the post-split descriptor in order to find the transaction record, which is necessary to resolve the intent. 

> I'm wondering if it'd be a good idea for the owners of meta ranges to try to resolve the intents in a non-blocking manner before returning the result.

Before returning the result to what? `RangeLookup`? What do you mean by both "non-blocking" and "before returning"? Those sound like opposites to me. A single blocking attempt to resolve the intent might reduce the chance of returning an uncommitted value, although I'm not sure how much difference that would make. 

> I'm thinking this would help a thundering herd of transactions operating on a hot spot that just split - I think it's possible for a bunch of transactions to find out that they have a stale descriptor all at once, at which point they go to the meta range and race with the intent resolution, so they might all get the stale version + intent back.

But then they have the intent, so they won't have to make a second query. And they'll all have to make one query anyway, so it doesn't seem to make much difference whether they make their query before or after the intent resolves.

**Comment by andreimatei** [comment] 2016-11-21 02:35
> This is not just an optimization; it's required in some situations. You may need to see the post-split descriptor in order to find the transaction record, which is necessary to resolve the intent.

I see.

> > I'm wondering if it'd be a good idea for the owners of meta ranges to try to resolve the intents in a non-blocking manner before returning the result.

> Before returning the result to what? RangeLookup? What do you mean by both "non-blocking" and "before returning"? Those sound like opposites to me. A single blocking attempt to resolve the intent might reduce the chance of returning an uncommitted value, although I'm not sure how much difference that would make.

I meant "non-blocking" in the sense that the attempt to resolve wouldn't block for the intent's txn to commit, if it hasn't committed yet (i.e. what `Store.Send()` does).

> > I'm thinking this would help a thundering herd of transactions operating on a hot spot that just split - I think it's possible for a bunch of transactions to find out that they have a stale descriptor all at once, at which point they go to the meta range and race with the intent resolution, so they might all get the stale version + intent back.

> But then they have the intent, so they won't have to make a second query. And they'll all have to make one query anyway, so it doesn't seem to make much difference whether they make their query before or after the intent resolves.

Well, yeah, this suggestion wouldn't reduce the number of RangeLookup queries, but it would save the subsequent Batch requests to a wrong range.

Anyway, perhaps the thing to do is to introduce a metric for the number of `RangeLookup`s that return intents.

**Comment by cuongdo** [comment] 2017-04-06 18:38
reassigning to @petermattis to find a new owner

**Comment by petermattis** [comment] 2017-04-11 01:44
@andreimatei Is there a test which is exhibiting problems due to the current `RangeCache` behavior? Or a way to reproduce badness? Wondering if this should be pushed out of the 1.0 milestone.

**Comment by bdarnell** [comment] 2017-04-11 02:07
This was fixed (or at least improved) in #14217. In any case, the problem here appears to be self-correcting, so I think it's post-1.0 if there are any residual issues.

**Comment by nvanbenschoten** [comment] 2017-04-11 07:29
#14217 didn't address the heart of this issue, which is related to timestamping cache entries. It did, however, resolve a lingering bug in the RangeCache mentioned above (funky behavior #*1* in https://github.com/cockroachdb/cockroach/issues/10751#issuecomment-261416836).

I'll second @bdarnell's position that because this is a self-correcting phenomenon that hasn't been linked with any egregious perf issues, it's resolution can be pushed to post-1.0.

**Comment by andreimatei** [comment] 2017-04-11 15:08
@petermattis to get flaky tests, remove the sleep here. The sleep done after range splits was put in to hide instability in the cache.
https://github.com/cockroachdb/cockroach/blob/f3aaf15/pkg/sql/distsqlplan/span_resolver_test.go#L359

In fact, a number of tests in that file are currently skipped because they were flaky even with the sleep - I think still because of these cache issues.

The fact that the cache can flip-flop like this is a nightmare for testing. But, yeah, it'll have to wait for later as I haven't done anything about it.

**Comment by petermattis** [comment] 2018-01-25 18:03
@andreimatei Do we think this is still a problem?

**Comment by andreimatei** [comment] 2018-01-25 18:57
Why wouldn't it be?

**Comment by petermattis** [comment] 2018-01-25 19:02
Because is 9 months old and we haven't done any work on it.

**Comment by nvanbenschoten** [comment] 2018-01-25 19:22
> a RangeLookup request returns two versions of a range descriptor (presumably one of them is an intent). The old version of the descriptor is inserted into the cache, replacing all overlapping descriptors (which were newer).
Interestingly, the cache did previously have the newest version of a descriptor. Also, all this happens a good deal of time after the range in question has been split, so it's dubious that an intent on the descriptor is still present.

This issue should be improved [when we move](https://github.com/cockroachdb/cockroach/pull/21276#issuecomment-355880901) from `INCONSISTENT` range lookup scans to `READ_UNCOMMITTED` range lookup scans. With that change, I don't think it will be possible for a range lookup scan to return older versions of descriptors than we have in the cache because the lookups will always go to the leaseholder.

> the cache is checked for range 1, and it's a miss. Range 1 is gossiped, not read from the database, and the descriptor we get from gossip is inserted into the cache. This seems particularly bad, since the version of the descriptor in gossip in this test seems to be particularly old (it covers /Min - /Max, so it completely wipes the cache).

Is this actually possible? I didn't think the `RangeDescriptorCache` stored the first range descriptor directly in the cache. I think that's the point of `RangeDescriptorDB.FirstRange`.

**Comment by nvanbenschoten** [comment] 2018-09-18 14:42
Moving this out to 2.2, but we should address it along with #18988 early in the next release cycle. Could be a good starter project.

**Comment by tbg** [comment] 2018-12-04 13:59
Also related: https://github.com/cockroachdb/cockroach/issues/28967

**Comment by jeffrey-xiao** [comment] 2019-07-10 22:24
Addressed by #38334.

**Closed by jeffrey-xiao** 2019-07-10 22:24 UTC
Labels: A-core-kv, C-bug, S-3-wrong-metadata
