### ISSUE TITLE
Scheduled backup doesn't complete

### ISSUE THREAD

**Issue by charsleysa** [cockroachdb/cockroach#63526] opened 2021-04-13 03:44 UTC
**Describe the problem**
Hi there, asked in Slack and advised to log issue here.

Having an issue where scheduled backups aren't completing, they get stuck at ~96% with 1 second remaining. There are no long running queries which could be blocking but I would also expect the backup to take priority over any running queries.

**To Reproduce**

Unknown

**Expected behavior**
Backup to finish in reasonable time (usually 2 minutes).

**Additional data / screenshots**
Debug zip supplied to support@cockroachlabs.com

**Environment:**
 - CockroachDB version 20.2.5
 - Server OS: Official Docker Image
 - Client app: N/A

**Additional context**
Tried to decommission and replace the node that looked like was stuck and the scheduled backup job simply failed and restarted with the same issues on another node.

Unscheduled backups also don't work so no backup seems possible which is a high risk issue.

**Comment by dt** [comment] 2021-04-13 04:16
Unfortunately the debug.zip failed to collect most of the files including jobs (you can see most files are empty and have a companion file named `.err.txt` they says it timed out), but what it did capture included the node status map, which shows 20k+ intents on many nodes. My guess is this is a known issue where some workloads can cause a leak/build-up of unresolved intents that prevent BACKUP from reading. In the short-term, running `BEGIN PRIORITY HIGH; SELECT COUNT(*) FROM my_tbl; COMMIT;` where `my_tbl` is any table that has excess intents may help clear them and get the backup un-stuck. In the longer term, the fix to #59704 should help here.

I'm going to close this as a dupe of #59704, but please comment/re-open if the high-priority select doesn't help.

**Closed by dt** 2021-04-13 04:16 UTC
Labels: C-bug, O-community, X-blathers-triaged

**Comment by charsleysa** [comment] 2021-04-13 04:40
Hi @dt 

Thanks for your help! The workaround fixed our stuck backups.

It seems that a table which had severe contention for some days last week had caused the number of intents to skyrocket up to almost 9 million and even today were still at 300 thousand.

After running the high priority transaction on the table the intents cleared and the backups proceeded successfully.
