### ISSUE TITLE
kvserver: split failed while applying backpressure during a long INSERT

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#52292] opened 2020-08-03 21:04 UTC
I'm hitting the following error when trying to insert millions of single column rows into an empty table:
```
ERROR: split failed while applying backpressure to [txn: fc68b80a], ConditionalPut [/Table/52/1/578084722265554945/0,/Min), ConditionalPut [/Table/52/1/578084722265587713/0,/Min), ConditionalPut [/Table/52/1/578084722265620481/0,/Min), ConditionalPut [/Table/52/1/578084722265653249/0,/Min), ConditionalPut [/Table/52/1/578084722265686017/0,/Min), ConditionalPut [/Table/52/1/578084722265718785/0,/Min), ConditionalPut [/Table/52/1/578084722265751553/0,/Min), ConditionalPut [/Table/52/1/578084722265784321/0,/Min), ConditionalPut [/Table/52/1/578084722265817089/0,/Min), ConditionalPut [/Table/52/1/578084722265849857/0,/Min), ConditionalPut [/Table/52/1/578084722265882625/0,/Min), ConditionalPut [/Table/52/1/578084722265915393/0,/Min), ConditionalPut [/Table/52/1/578084722265948161/0,/Min), ConditionalPut [/Table/52/1/578084722265980929/0,/Min), ConditionalPut [/Table/52/1/578084722266013697/0,/Min), ConditionalPut [/Table/52/1/578084722266046465/0,/Min), ConditionalPut [/Table/52/1/578084722266079233/0,/Min), ConditionalPut [/Table/52/1/578084722266112001/0,/Min), ConditionalPut [/Table/52/1/578084722266144769/0,/Min), ConditionalPut [/Table/52/1/578084722266177537/0,/Min), ... 9975 skipped ..., ConditionalPut [/Table/52/1/578084722593071105/0,/Min), ConditionalPut [/Table/52/1/578084722593103873/0,/Min), ConditionalPut [/Table/52/1/578084722593136641/0,/Min), ConditionalPut [/Table/52/1/578084722593169409/0,/Min), ConditionalPut [/Table/52/1/578084722593202177/0,/Min) on range r35:/{Table/52-Max} [(n1,s1):1, (n2,s2):2, (n3,s3):3, next=4, gen=5]: operation "split queue process replica 35" timed out after 1m0s: split at key /Table/52/1/578084507703214081 failed: aborted during DistSender.Send: context deadline exceeded
```
Reproduction steps:
- start 3 node cluster (in four different terminals)
```
./cockroach start --insecure --listen-addr=localhost:26257 --join=localhost:26257 --store=temp1
./cockroach start --insecure --listen-addr=localhost:26258 --http-port=8081 --join=localhost:26257 --store=temp2
./cockroach start --insecure --listen-addr=localhost:26259 --http-port=8082 --join=localhost:26257 --store=temp3
./cockroach init --insecure
```
- connect to the cluster and run the following:
```
set cluster setting sql.stats.automatic_collection.enabled=false;
create table t (a int);
insert into t select i from generate_series(1,9000000) as g(i);
```
I've seen the error several times, and there were some successful runs as well (in one successful insert it took 1m 40s, there were a few attempts that took longer than 3 minutes or so and they were canceled). Every time I would remove the data directories and create a new cluster.

cc @andreimatei

**Comment by aayushshah15** [comment] 2020-08-04 14:01
The failure mode looks vaguely similar to what we're seeing in #47325, so I'll take this.

**Comment by aayushshah15** [comment] 2020-08-13 16:34
I was unable to reproduce this error; Attempted the repro with 15 & 20 mil inserts as well, with no luck. I'll close this issue for now, we can dig further if it reoccurs.

**Closed by aayushshah15** 2020-08-13 16:34 UTC
Labels: C-investigation
