### ISSUE TITLE
cli: interactive client lets user drop entire non-empty database or table without confirmation

### ISSUE THREAD

**Issue by jseldess** [cockroachdb/cockroach#3943] opened 2016-01-21 22:06 UTC
Currently, you can run `drop database` on a db that contains tables. When chatting with @vivekmenezes, he suggested that we might want that intention to be explicit in the command; in other words, running just `drop database` on a database containing tables would return an error. 

Also, noticed that you can drop a database even when you're connected to it. Postgres doesn't let you do that: "This command cannot be executed when connected to the target database." http://www.postgresql.org/docs/9.5/static/sql-dropdatabase.html

```
JESSEs-MBP.home:26257> set database = test;
OK
JESSEs-MBP.home:26257> show database;
+----------+
| DATABASE |
+----------+
| test     |
+----------+
JESSEs-MBP.home:26257> CREATE TABLE weather (
                    ->     city            string(80),
                    ->     temp_lo         int,           -- low temperature
                    ->     temp_hi         int,           -- high temperature
                    ->     prcp            float,          -- precipitation
                    ->     date            date
                    -> );
OK
JESSEs-MBP.home:26257> show tables;
+---------+
|  Table  |
+---------+
| weather |
+---------+
JESSEs-MBP.home:26257> drop database test;
OK
JESSEs-MBP.home:26257> show databases;
+----------+
| Database |
+----------+
| system   |
+----------+
JESSEs-MBP.home:26257> show tables;
query error: database "test" does not exist
```

**Comment by petermattis** [comment] 2016-01-21 22:26
The current behavior is intentional and I believe it mirrors what other DBs do. I'm not a fan of these semantics and would rather require explicit table deletion and only allow a database to be deleted if it was empty. I'd be interested in hearing if that would cause a hardship for anyone.

**Comment by bdarnell** [comment] 2016-01-25 18:43
I've written/used a lot of test harnesses that start with "DROP DATABASE IF EXISTS foo_test; CREATE DATABASE foo_test" and then create their tables. It would be tedious to replace this with a loop over all tables (and ultimately no less safe as long as it remains common to blindly delete any tables that exist). I'd rather address concerns about an accidental "DROP DATABASE" by making it a "move to trash" operation that can be undone within some time period, and/or by ensuring that our privilege guidelines encourage the use of credentials that don't have permission to drop databases.

**Comment by JackKrupansky** [comment] 2016-01-25 22:13
+1 for being (at least relatively) Postgres-compatible - as a default
unless some compelling advantage.

MySQL, et al have required permissions to perform the DROP DATABASE so
random users can't accidentally/intentionally do it. Each of the vendors
seems to do the permissions differently, in part since DROP DATABASE is not
a standard SQL feature. Postgres merely requires that you be the owner.
Postgres also has a dropdb utility, for cases where you just want to
externally script the deletion of the database without talking SQL
(although it uses SQL under the hood anyway.)

FWIW, MySQL also returns the number of tables that were removed. At least
log this info.

Oracle also has a NOPROMPT option on DROP DATABASE, with the default to
prompt the user before deletion.

Oracle requires you to be connected to the database and does not have a
name parameter, while Postgres requires that you NOT be connected. MySQL
doc doesn't say which.

MS SQL Server permits a comma-separated list of databases to delete. Also
requires CONTROL permission to drop a database.

My favorite is SQLite - no DROP DATABASE command, just delete the directory.

Interesting question: If some nodes are temporarily down when a database is
dropped, what will their status be when they come back up? And if you did a
CREATE DATABASE after the DROP before they come back, will those zombie
nodes be able to rejoin the cluster (with their zombie data) when they do
come back up? Or is there some kind of UUID for the database so that the
zombies (and non-zombies) can know that they really aren't part of the
cluster anymore?


-- Jack Krupansky

**Comment by petermattis** [comment] 2016-01-26 00:43
@JackKrupansky Thanks for the info about what other SQL systems do.

Database data and metadata is stored within the internal KV storage system. If a node is down when a database is dropped, the node will not serve data when it comes back up until it syncs up with the rest of the cluster again. There is no danger of the deleted database being resurrected by a node returning to the system. This is accomplished via the raft replication and transaction system built on top of it.

**Comment by knz** [comment] 2016-01-29 16:30
I think it is reasonable to plan a permission system for after the beta.

We could also envision a special extra check for the command-line interactive sql client since one could argue people will use that to tinker / experiment and might appreciate an extra warning/confirmation before losing a lot of data. 

However, since the current direction is to have the command-line client talk via the pgwire interface we cannot arbitrarily extend the internal API between the command-line client and the database. The best way forward is thus probably to:

- introduce a configuration flag customizable by means of SET to indicate whether destructive operations (drop table, drop database) should require confirmation,
- have this flag disabled by default (no confirmation) for regular pgwire clients (JDBC, etc) 
- have this flag disabled by default for statements after `sql -e` (for tests & scripts)
- and have the interactive client issue a SET upon start-up, before displaying the prompt, so that the default during an interactive session is to ask confirmation.

**Comment by mberhault** [comment] 2016-02-17 14:41
we have permissions already. If you're connected as root, you have `ALL` permissions on the database you created. otherwise, you'd have to explicitly grant permissions to a different user. eg: `GRANT DROP ON DATABASE foo TO marc`. without that specific privilege, nothing I can do.

As for confirmation, I think we should stick with expected behavior. Yes, it's mad and dangerous, but apparently people are happy living on the edge and assume they've set up their permissions properly.

I don't think the cli should be different. Were I to script some db setup/teardown, I would expect `cockroach sql -e` to work the same way as a regular driver. We could add the extra safety @knz mentioned, but I'm not sure it's necessary. Again, the expectation is that permissions are setup properly.

**Comment by knz** [comment] 2016-02-18 17:53
@mberhault you have a point for "drop table". However for "drop database" it's a little bit different because (AFAIK) it's not ruled by permissions. Also by default `cockroach sql` logs into the database as `root` which has all permissions. 

I think I want to handle this as follows:
- change the default behavior of `cockroach sql` to log in with the current user's name, not `root` by default
- when the user specifies `root` explicitly (or they happen to use `cockroach` from their root account), print a big warning that they can enter destructive SQL commands and that there will be no confirmation asked.

Comments?

**Comment by mberhault** [comment] 2016-02-18 18:06
dropping a database requires `DROP` permission at the database level, so that's protected too.
* we could definitely change the default user, but for now, using `root` makes it easier to run without worrying about permissions. I'd say the change should come when we have more fleshed out user management, probably post-beta.
* `root` is like any other user, the only difference is that it's the only user with privileges by default. I could give `ALL` privileges to user `marc`, then remove some privileges from user `root`.

**Comment by knz** [comment] 2016-02-18 18:15
@mberhault ok now I see the point.

I think that unless we start to parse statements client-side to detect DROP, there is not much left we can do at this point.

@petermattis Given @mberhault's comments it feels to me like the current behavior is fine for Beta, and that we'll revisit the topic post-Beta. What do you think: close the issue or change the milestone?

**Comment by knz** [comment] 2016-04-26 15:32
Here's a summary of the possible approaches as discussed here, on #6257 and Gitter:

-  (@knz) simple word-based, client-side detection on the query string, with client-directed confirmation (#6257).  @bdarnell suggests there would be too much false positives. Also does not protect against TRUNCATE, DELETE without a filter, etc.

- (@petermattis) "Rather than performing the check in the cli, I wonder if it would be better to allow a user to revoke their own privileges on a per-session basis. For example, a user could revoke their DROP privilege for the duration of a session, thus preventing accidental drops. [...] I was imagining that a session would have a set of privileges which defaults to ALL. If you remove the DROP privilege you wouldn't be able to drop any table or database even if it was created after the session privileges were set. [...]  there would definitely be additional work in the cli as well to capture the error returned when you have insufficient privileges and ask the user for confirmation. You'd then have to open a new DB connection [or retry the statement]."

- (@tamird) force a user to use a different unprivileged user account.

- (@knz, @bdarnell) introduce a new session flag (eg "confirm" or "safety"), off by default. Have the SQL cli client enable it for its session during start-up. When the flag is set, a data-destroying statement would fail with a distinctive error. Upon recognizing this error, the client would ask for confirmation, disable the flag, re-issue the statement, and re-enable the flag.

**Comment by bdarnell** [comment] 2016-04-26 15:59
Another suggestion is that `DROP` should be a "move to trash", so it can be undone until the data is actually deleted at some later time.

**Comment by tamird** [comment] 2016-04-26 16:01
Note that "move to trash" is still scary in that it has downstream outage
potential.

**Comment by bdarnell** [comment] 2016-04-26 16:10
Guarding against anything that has downstream outage potential is much more intrusive than guarding against things that are unrecoverable. Renaming a table (to trash or not) is easily undoable so I think it's better to just let it through without confirmation. Minimizing privilege is a better strategy if you want to guard against any kind of outage.

**Comment by knz** [comment] 2016-07-06 10:01
Since my original proposed approach is much weaker than the alternative proposals made since then, and I am not planning to work on these alternatives in the short term, I am de-assigning this for now.

**Comment by a-robinson** [comment] 2016-10-11 19:43
This gets a little worse with the addition of views, where you can have a view in database foo that depends on a table in database bar getting deleted when you drop database bar. Permission checks will have to pass, but it still feels dangerous to not have any sort of restriction on this.

When [DROP DATABASE was first added, it got brought up that its closest postgres parallel is DROP SCHEMA](https://github.com/cockroachdb/cockroach/pull/2015#r36515853), which [offers RESTRICT/CASCADE options and defaults to RESTRICT](https://www.postgresql.org/docs/current/static/sql-dropschema.html). Would that be too much of a deviation from expected behavior?

**Closed** 2017-08-23 20:59 UTC
Labels: enhancement
