### ISSUE TITLE
cmd/localcluster: panic in key formatting

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#17791] opened 2017-08-21 21:13 UTC
Restarting zerosum locally, I found this printed from the localcluster "wait for rebalancing" code:

```
I170821 17:01:00.992343 1 cmd/localcluster/localcluster/localcluster.go:251  waiting for replication
  /Min                                                                         /System/""                                                                   [1]    [1 2 4]
  /System/""                                                                   %!s(PANIC=runtime error: invalid memory address or nil pointer dereference)  [2]    [1 4 2]
  %!s(PANIC=runtime error: invalid memory address or nil pointer dereference)  /System/"tse"                                                                [3]    [1 3 4]
  /System/"tse"                                                                /Table/SystemConfigSpan/Start
```

Looks like the end key of the system range panics our key pretty printer. The range is, of course (note that both of those presumably call `someKey.String()` but it works in the browser and not in the log output. We might be tickling a bug in `tablewriter`.

![image](https://user-images.githubusercontent.com/5076964/29538413-bb477fc0-8693-11e7-9f81-6e3ac98c6887.png)

The code which produce the output at the top of this post is generated by

```
	tw := tabwriter.NewWriter(&buf, 2, 1, 2, ' ', 0)
        // ...
		fmt.Fprintf(tw, "\t%s\t%s\t[%d]\t%d\n",
			desc.StartKey, desc.EndKey, desc.RangeID, storeIDs)
		if len(desc.Replicas) != 3 {
			done = false
		}
```

**Comment by petermattis** [comment] 2017-08-21 21:49
I'm not able to reproduce this locally. Is there anything special you are doing when starting `zerosum`?

**Comment by knz** [comment] 2019-01-21 12:19
We haven't seen this in a long time. Also the pretty formatting code has been adjusted/fixed quite a bit since. Closing as non-actionable.

**Closed by knz** 2019-01-21 12:19 UTC
Labels: C-bug, E-easy, help wanted
