### ISSUE TITLE
spanconfigsqltranslatorccl: flake in TestDataDriven/3node/partition/multi_col_list_partitioning_default

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#110400] opened 2023-09-12 00:47 UTC
Saw on likely unrelated PR #109449 [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=11729116&buildTypeId=Cockroach_BazelEssentialCi)
```
        output didn't match expected:
        @@ -3,7 +3,7 @@
         [/Table/<table-id>/1/3/5, /Table/<table-id>/1/5)       constraints=[+n1]
         [/Table/<table-id>/1/5, /Table/<table-id>/1/5/7)       constraints=[+n2]
         [/Table/<table-id>/1/5/7, /Table/<table-id>/1/5/8)     constraints=[+n3]
         [/Table/<table-id>/1/5/8, /Table/<table-id>/1/5/9)     constraints=[+n1]
         [/Table/<table-id>/1/5/9, /Table/<table-id>/1/6)       constraints=[+n2]
        -[/Table/<table-id>/1/6, /Table/<table-id+1>)           constraints=[+n1]
        +[/Table/<table-id>/1/6, /Table/<table-id>/PrefixEnd)   constraints=[+n1]
```
I stressed the test for a bit, but the problem didn't reproduce, so the failure is likely pretty rare.

Jira issue: CRDB-31406

**Comment by rafiss** [comment] 2023-09-12 03:45
dupe of https://github.com/cockroachdb/cockroach/issues/110239 https://github.com/cockroachdb/cockroach/issues/110240 and https://github.com/cockroachdb/cockroach/issues/110242

**Closed by rafiss** 2023-09-12 03:45 UTC
Labels: C-test-failure, T-sql-foundations
