### ISSUE TITLE
storage: panic in raft when running TestStoreRangeDownReplicate

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#10456] opened 2016-11-04 14:35 UTC
I ran `make stress PKG=./pkg/storage TESTS=TestStoreRangeDownReplicate` and saw this panic. I haven't been able to reproduce it.

```
I161104 10:19:43.079010 1 rand.go:76  Random seed: -153639414791849756
I161104 10:19:43.080780 6 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161104 10:19:43.093331 6 gossip/gossip.go:237  [n?] initial resolvers: []
W161104 10:19:43.095094 6 gossip/gossip.go:1055  [n?] no resolvers found; use --join to specify a connected node
I161104 10:19:43.095206 6 base/node_id.go:62  NodeID set to 1
I161104 10:19:43.110747 6 storage/store.go:1174  [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I161104 10:19:43.110878 6 gossip/gossip.go:280  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:50822" > attrs:<> locality:<> 
I161104 10:19:43.112022 44 storage/replica_proposal.go:334  [s1,r1/1:/M{in-ax}] new range lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000124ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0s [physicalTime=1970-01-01 00:00:00.000000123 +0000 UTC]
I161104 10:19:43.112602 6 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161104 10:19:43.113797 6 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:50822]
W161104 10:19:43.113834 6 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
I161104 10:19:43.113865 6 base/node_id.go:62  NodeID set to 2
I161104 10:19:43.115643 6 storage/store.go:1174  [n2,s2]: failed initial metrics computation: [n2,s2]: system config not yet available
I161104 10:19:43.115680 6 gossip/gossip.go:280  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:50824" > attrs:<> locality:<> 
I161104 10:19:43.116161 6 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161104 10:19:43.116223 96 gossip/client.go:125  [n2] started gossip client to 127.0.0.1:50822
I161104 10:19:43.117458 6 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:50822]
W161104 10:19:43.117484 6 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
I161104 10:19:43.117553 6 base/node_id.go:62  NodeID set to 3
I161104 10:19:43.126606 6 storage/store.go:1174  [n3,s3]: failed initial metrics computation: [n3,s3]: system config not yet available
I161104 10:19:43.126658 6 gossip/gossip.go:280  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:50826" > attrs:<> locality:<> 
I161104 10:19:43.126712 149 gossip/client.go:125  [n3] started gossip client to 127.0.0.1:50822
I161104 10:19:43.126936 6 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161104 10:19:43.128345 6 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:50822]
W161104 10:19:43.128368 6 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
I161104 10:19:43.128405 6 base/node_id.go:62  NodeID set to 4
I161104 10:19:43.131452 271 gossip/client.go:125  [n4] started gossip client to 127.0.0.1:50822
I161104 10:19:43.132376 6 storage/store.go:1174  [n4,s4]: failed initial metrics computation: [n4,s4]: system config not yet available
I161104 10:19:43.132448 6 gossip/gossip.go:280  [n4] NodeDescriptor set to node_id:4 address:<network_field:"tcp" address_field:"127.0.0.1:50828" > attrs:<> locality:<> 
I161104 10:19:43.132978 6 storage/engine/rocksdb.go:340  opening in memory rocksdb instance
I161104 10:19:43.134127 6 gossip/gossip.go:237  [n?] initial resolvers: [127.0.0.1:50822]
W161104 10:19:43.134145 6 gossip/gossip.go:1057  [n?] no incoming or outgoing connections
I161104 10:19:43.134183 6 base/node_id.go:62  NodeID set to 5
I161104 10:19:43.135980 6 storage/store.go:1174  [n5,s5]: failed initial metrics computation: [n5,s5]: system config not yet available
I161104 10:19:43.136021 6 gossip/gossip.go:280  [n5] NodeDescriptor set to node_id:5 address:<network_field:"tcp" address_field:"127.0.0.1:50830" > attrs:<> locality:<> 
I161104 10:19:43.136072 346 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:50822
I161104 10:19:43.136348 171 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 2 ({tcp 127.0.0.1:50824})
I161104 10:19:43.136426 171 gossip/server.go:263  [n1] refusing gossip from node 5 (max 3 conns); forwarding to 4 ({tcp 127.0.0.1:50828})
I161104 10:19:43.136543 346 gossip/client.go:130  [n5] closing client to node 1 (127.0.0.1:50822): received forward from node 1 to 2 (127.0.0.1:50824)
I161104 10:19:43.136815 425 gossip/client.go:125  [n5] started gossip client to 127.0.0.1:50824
I161104 10:19:43.139304 6 storage/client_test.go:414  gossip network initialized
I161104 10:19:43.140039 6 storage/replica_raftstorage.go:446  [s1,r1/1:/M{in-ax}] generated snapshot f2aa2a1f for range 1 at index 17 in 71.846µs.
I161104 10:19:43.140892 6 storage/store.go:3103  streamed snapshot: kv pairs: 36, log entries: 7
I161104 10:19:43.142658 475 storage/replica_raftstorage.go:592  [s2] [n2,s2,r1/?:{-}]: with replicaID [?], applying preemptive snapshot at index 17 (id=f2aa2a1f, encoded size=16, 1 rocksdb batches, 7 log entries)
I161104 10:19:43.143179 475 storage/replica_raftstorage.go:595  [s2] [n2,s2,r1/?:/M{in-ax}]: with replicaID [?], applied preemptive snapshot in 0.000s
I161104 10:19:43.143631 6 storage/replica_command.go:3242  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > next_replica_id:2 
I161104 10:19:43.144470 479 storage/replica.go:2000  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA {NodeID:2 StoreID:2 ReplicaID:2} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2}]
I161104 10:19:43.145429 6 storage/replica_raftstorage.go:446  [s1,r1/1:/M{in-ax}] generated snapshot e5fe71ce for range 1 at index 19 in 40.625µs.
I161104 10:19:43.145874 6 storage/store.go:3103  streamed snapshot: kv pairs: 39, log entries: 9
I161104 10:19:43.146130 519 storage/replica_raftstorage.go:592  [s3] [n3,s3,r1/?:{-}]: with replicaID [?], applying preemptive snapshot at index 19 (id=e5fe71ce, encoded size=16, 1 rocksdb batches, 9 log entries)
I161104 10:19:43.146568 519 storage/replica_raftstorage.go:595  [s3] [n3,s3,r1/?:/M{in-ax}]: with replicaID [?], applied preemptive snapshot in 0.000s
I161104 10:19:43.147026 6 storage/replica_command.go:3242  change replicas: read existing descriptor range_id:1 start_key:"" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > next_replica_id:3 
I161104 10:19:43.148861 531 storage/raft_transport.go:432  raft transport stream to node 1 established
I161104 10:19:43.150387 429 storage/replica.go:2000  [s1,r1/1:/M{in-ax}] proposing ADD_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 1: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3}]
I161104 10:19:43.152524 432 storage/raft_transport.go:432  raft transport stream to node 1 established
I161104 10:19:43.152901 6 storage/replica_command.go:2360  initiating a split of this range at key "m" [r2]
I161104 10:19:43.157041 6 storage/replica_raftstorage.go:446  [s1,r2/1:{"m"-/Max}] generated snapshot fc11994b for range 2 at index 10 in 100.626µs.
I161104 10:19:43.157706 6 storage/store.go:3103  streamed snapshot: kv pairs: 28, log entries: 0
I161104 10:19:43.157966 400 storage/replica_raftstorage.go:592  [s4] [n4,s4,r2/?:{-}]: with replicaID [?], applying preemptive snapshot at index 10 (id=fc11994b, encoded size=16, 1 rocksdb batches, 0 log entries)
I161104 10:19:43.158229 400 storage/replica_raftstorage.go:595  [s4] [n4,s4,r2/?:{"m"-/Max}]: with replicaID [?], applied preemptive snapshot in 0.000s
I161104 10:19:43.158632 6 storage/replica_command.go:3242  change replicas: read existing descriptor range_id:2 start_key:"m" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > next_replica_id:4 
W161104 10:19:43.161186 562 storage/stores.go:218  range not contained in one range: [/Meta2/Max,"m\x00"), but have [/Min,"m")
I161104 10:19:43.162606 534 storage/replica.go:2000  [s1,r2/1:{"m"-/Max}] proposing ADD_REPLICA {NodeID:4 StoreID:4 ReplicaID:4} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I161104 10:19:43.164111 6 storage/replica_raftstorage.go:446  [s1,r2/1:{"m"-/Max}] generated snapshot 942ba787 for range 2 at index 14 in 39.889µs.
I161104 10:19:43.164594 6 storage/store.go:3103  streamed snapshot: kv pairs: 30, log entries: 4
I161104 10:19:43.164872 559 storage/replica_raftstorage.go:592  [s5] [n5,s5,r2/?:{-}]: with replicaID [?], applying preemptive snapshot at index 14 (id=942ba787, encoded size=16, 1 rocksdb batches, 4 log entries)
I161104 10:19:43.165301 559 storage/replica_raftstorage.go:595  [s5] [n5,s5,r2/?:{"m"-/Max}]: with replicaID [?], applied preemptive snapshot in 0.000s
I161104 10:19:43.165503 458 storage/raft_transport.go:432  raft transport stream to node 1 established
I161104 10:19:43.165724 6 storage/replica_command.go:3242  change replicas: read existing descriptor range_id:2 start_key:"m" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:5 
I161104 10:19:43.167590 537 storage/replica.go:2000  [s1,r2/1:{"m"-/Max}] proposing ADD_REPLICA {NodeID:5 StoreID:5 ReplicaID:5} for range 2: [{NodeID:1 StoreID:1 ReplicaID:1} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4} {NodeID:5 StoreID:5 ReplicaID:5}]
I161104 10:19:43.172991 572 storage/raft_transport.go:432  raft transport stream to node 1 established
I161104 10:19:43.182861 82 storage/replica_proposal.go:383  [s1,r2/1:{"m"-/Max}] range [n1,s1,r2/1:{"m"-/Max}]: transferring raft leadership to replica ID 2
I161104 10:19:43.184296 414 storage/raft_transport.go:432  raft transport stream to node 5 established
I161104 10:19:43.184312 413 storage/raft_transport.go:432  raft transport stream to node 4 established
I161104 10:19:43.184393 132 storage/replica_proposal.go:334  [s2,r2/2:{"m"-/Max}] new range lease replica {2 2 2} 1970-01-01 00:00:00.900000124 +0000 UTC 1.800000002s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000124ms [physicalTime=1970-01-01 00:00:01.800000125 +0000 UTC]
I161104 10:19:43.184419 415 storage/raft_transport.go:432  raft transport stream to node 3 established
I161104 10:19:43.185088 524 storage/raft_transport.go:432  raft transport stream to node 2 established
I161104 10:19:43.185162 584 storage/raft_transport.go:432  raft transport stream to node 2 established
I161104 10:19:43.185246 542 storage/raft_transport.go:432  raft transport stream to node 2 established
I161104 10:19:43.185444 6 storage/replica_command.go:3242  [replicate,s2,r2/2:{"m"-/Max}] change replicas: read existing descriptor range_id:2 start_key:"m" end_key:"\377\377" replicas:<node_id:1 store_id:1 replica_id:1 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > replicas:<node_id:5 store_id:5 replica_id:5 > next_replica_id:6 
I161104 10:19:43.194512 87 storage/replica_proposal.go:383  [s1,r1/1:{/Min-"m"}] range [n1,s1,r1/1:{/Min-"m"}]: transferring raft leadership to replica ID 2
I161104 10:19:43.195173 132 storage/replica_proposal.go:334  [s2,r1/2:{/Min-"m"}] new range lease replica {2 2 2} 1970-01-01 00:00:00.900000124 +0000 UTC 1.800000002s following replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900.000124ms [physicalTime=1970-01-01 00:00:01.800000125 +0000 UTC]
I161104 10:19:43.197834 576 storage/replica.go:2000  [s2,r2/2:{"m"-/Max}] proposing REMOVE_REPLICA {NodeID:1 StoreID:1 ReplicaID:1} for range 2: [{NodeID:5 StoreID:5 ReplicaID:5} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:3 StoreID:3 ReplicaID:3} {NodeID:4 StoreID:4 ReplicaID:4}]
I161104 10:19:43.199867 192 storage/store.go:2960  [s1] [n1,s1,r2/1:{"m"-/Max}]: added to replica GC queue (peer suggestion)
I161104 10:19:43.200043 192 storage/store.go:2960  [s1] [n1,s1,r2/1:{"m"-/Max}]: added to replica GC queue (peer suggestion)
I161104 10:19:43.231957 202 storage/replica_command.go:3242  [replicate,s2,r2/2:{"m"-/Max}] change replicas: read existing descriptor range_id:2 start_key:"m" end_key:"\377\377" replicas:<node_id:5 store_id:5 replica_id:5 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:6 
I161104 10:19:43.250536 561 storage/replica.go:2000  [s2,r2/2:{"m"-/Max}] proposing REMOVE_REPLICA {NodeID:3 StoreID:3 ReplicaID:3} for range 2: [{NodeID:5 StoreID:5 ReplicaID:5} {NodeID:2 StoreID:2 ReplicaID:2} {NodeID:4 StoreID:4 ReplicaID:4}]
I161104 10:19:43.252332 129 storage/replica_proposal.go:383  [s2,r2/2:{"m"-/Max}] range [n2,s2,r2/2:{"m"-/Max}]: transferring raft leadership to replica ID 3
I161104 10:19:43.252485 254 storage/replica_proposal.go:334  [s3,r2/3:{"m"-/Max}] new range lease replica {3 3 3} 1970-01-01 00:00:02.700000126 +0000 UTC 1.800000002s following replica {2 2 2} 1970-01-01 00:00:00.900000124 +0000 UTC 1.800000002s [physicalTime=1970-01-01 00:00:03.600000127 +0000 UTC]
I161104 10:19:43.253670 695 storage/raft_transport.go:432  raft transport stream to node 4 established
I161104 10:19:43.253951 202 storage/replica_command.go:3242  [replicate,s2,r2/2:{"m"-/Max}] change replicas: read existing descriptor range_id:2 start_key:"m" end_key:"\377\377" replicas:<node_id:5 store_id:5 replica_id:5 > replicas:<node_id:2 store_id:2 replica_id:2 > replicas:<node_id:3 store_id:3 replica_id:3 > replicas:<node_id:4 store_id:4 replica_id:4 > next_replica_id:6 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45400ac]

goroutine 259 [running]:
panic(0x51f1920, 0xc4200140d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420798120)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:185 +0x6e
panic(0x51f1920, 0xc4200140d0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/coreos/etcd/raft.(*raft).appendEntry(0xc4206f8b40, 0xc420aeca50, 0x1, 0x1)
	/Users/vivek1/go/src/github.com/coreos/etcd/raft/raft.go:521 +0xdc
github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc4206f8b40)
	/Users/vivek1/go/src/github.com/coreos/etcd/raft/raft.go:621 +0x1ce
github.com/coreos/etcd/raft.stepCandidate(0xc4206f8b40, 0x6, 0x3, 0x2, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek1/go/src/github.com/coreos/etcd/raft/raft.go:1013 +0x5a9
github.com/coreos/etcd/raft.(*raft).Step(0xc4206f8b40, 0x6, 0x3, 0x2, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek1/go/src/github.com/coreos/etcd/raft/raft.go:779 +0x11ef
github.com/coreos/etcd/raft.(*RawNode).Step(0xc42096e600, 0x6, 0x3, 0x2, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek1/go/src/github.com/coreos/etcd/raft/rawnode.go:195 +0xc9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest.func4(0xc42096e600, 0x7aaf128, 0xc420014558, 0x7a70438)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2921 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc420237c00, 0x5538b00, 0xc420e35848, 0x40c239b, 0xc420237cd8)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:486 +0x139
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc420237c00, 0xc420e35848, 0x0, 0x0)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:503 +0x92
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc420178e00, 0x7a70438, 0xc420bc1e00, 0xc4208df380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2922 +0xb72
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc420178e00, 0x2)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3149 +0x180
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4206f6460, 0xc420798120)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:241 +0x267
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420798120, 0xc4206b2a40)
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
	/Users/vivek1/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66


ERROR: exit status 2

4506 runs completed, 1 failures, over 2m34s
```

**Comment by tamird** [comment] 2016-11-04 14:36
Looks like a dupe of #8535.

**Closed by tamird** 2016-11-04 14:36 UTC
