### ISSUE TITLE
sql: v23.1.8-custom: relation × (582): referenced table × (581) is dropped

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#109095] opened 2023-08-20 07:13 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4407611287/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4407611287/?referrer=webhooks_plugin)

Panic Message:

```
validate.go:466: relation × (582): referenced table × (581) is dropped
(1) keys: [sql.schema.validation_errors.write.forward_references.relation]
Wraps: (2) keys: [sql.schema.validation_errors.write.forward_references.relation]
Wraps: (3) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:256
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:186
  | [...repeated from below...]
Wraps: (4) relation × (582)
Wraps: (5) assertion failure
Wraps: (6) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).validateOutboundFK
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:466
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/validate.go:203
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate.func2
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:103
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:202
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate.Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/internal/validate/validate.go:98
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).Validate
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:40
  | github.com/cockroachdb/cockroach/pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors
  | 	github.com/cockroachdb/cockroach/pkg/sql/catalog/descs/validate.go:74
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransactionInternal
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1330
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).commitSQLTransaction
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1234
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).handleAutoCommit
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2728
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState.func14
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:748
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1060
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2986
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2181
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2186
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2103
  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:900
  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:310
  | runtime.goexit
  | 	GOROOT/src/runtime/asm_amd64.s:1594
Wraps: (7) referenced table × (581) is dropped
Error types: (1) *telemetrykeys.withTelemetry (2) *telemetrykeys.withTelemetry (3) *withstack.withStack (4) *errutil.withPrefix (5) *assert.withAssertionFailure (6) *withstack.withStack (7) *errutil.leafError
-- report composition:
*errutil.leafError: referenced table × (581) is dropped
validate.go:466: *withstack.withStack (top exception)
*assert.withAssertionFailure
*errutil.withPrefix: relation × (582)
validate.go:256: *withstack.withStack (1)
*telemetrykeys.withTelemetry: sql.schema.validation_errors.write.forward_references.relation
*telemetrykeys.withTelemetry: sql.schema.validation_errors.write.forward_references.relation
(check the extra data payloads)
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1059-L1061](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1059-L1061)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L747-L749](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L747-L749)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2727-L2729](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2727-L2729)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1233-L1235](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1233-L1235)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1329-L1331](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1329-L1331)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L97-L99](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L97-L99)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L185-L187](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L185-L187)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L255-L257](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L255-L257)
[GOROOT/src/runtime/asm_amd64.s#L1593-L1595](GOROOT/src/runtime/asm_amd64.s#L1593-L1595)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/pgwire/conn.go#L309-L311](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/pgwire/conn.go#L309-L311)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L899-L901](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L899-L901)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2102-L2104](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2102-L2104)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2185-L2187](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2185-L2187)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2180-L2182](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor.go#L2180-L2182)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L140-L142](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L140-L142)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2985-L2987](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2985-L2987)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1059-L1061](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1059-L1061)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L747-L749](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L747-L749)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2727-L2729](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L2727-L2729)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1233-L1235](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1233-L1235)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1329-L1331](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/conn_executor_exec.go#L1329-L1331)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L73-L75](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L73-L75)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L39-L41](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/descs/validate.go#L39-L41)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L97-L99](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L97-L99)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L201-L203](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L201-L203)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L102-L104](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/internal/validate/validate.go#L102-L104)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L202-L204](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L202-L204)
[https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L465-L467](https://github.com/cockroachdb/cockroach/blob/6c5e4535cd8b587823fc2780e5d464f1a9262249/pkg/sql/catalog/tabledesc/validate.go#L465-L467)
</details>

```
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1060
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func14 at line 748
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).handleAutoCommit at line 2728
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1234
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1330
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 74
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 98
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func2 at line 103
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences at line 203
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).Report at line 186
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).decorate at line 256
GOROOT/src/runtime/asm_amd64.s in runtime.goexit at line 1594
pkg/sql/pgwire/conn.go in pkg/sql/pgwire.(*conn).processCommandsAsync.func1 at line 310
pkg/sql/conn_executor.go in pkg/sql.(*Server).ServeConn at line 900
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).run at line 2103
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2186
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2181
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 141
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 2986
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1060
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState.func14 at line 748
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).handleAutoCommit at line 2728
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransaction at line 1234
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).commitSQLTransactionInternal at line 1330
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).ValidateUncommittedDescriptors at line 74
pkg/sql/catalog/descs/validate.go in pkg/sql/catalog/descs.(*Collection).Validate at line 40
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate at line 98
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.(*validationErrorAccumulator).validateDescriptorsAtLevel at line 202
pkg/sql/catalog/internal/validate/validate.go in pkg/sql/catalog/internal/validate.Validate.func2 at line 103
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).ValidateForwardReferences at line 203
pkg/sql/catalog/tabledesc/validate.go in pkg/sql/catalog/tabledesc.(*wrapper).validateOutboundFK at line 466
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.8 |
| Go Version | go1.19.10 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.8-1-g6c5e4535cd |
| Cockroach SHA | 6c5e4535cd8b587823fc2780e5d464f1a9262249 |
| # of CPUs | 16 |
| # of Goroutines | 275 |

Jira issue: CRDB-30775

**Comment by yuzefovich** [comment] 2023-08-25 19:40
This is Serverless.

**Comment by chrisseto** [comment] 2023-10-10 14:13
It seems that this issue occurs across a variety of versions but I've only found serverless reports thus far.

The volume does appear to be somewhat high (Thank you Yahor for triaging!) and we have access to some of these clusters via serverless.

My best guess is that there's one or more tenants that have a corrupt descriptor.

I'd vote to close this (and potentially similar reports in the future) unless we intend to manually fix these descriptors.

@rafiss and/or @yuzefovich, mind sanity checking me before I slap close?

**Comment by yuzefovich** [comment] 2023-10-10 17:17
Sounds good to me.

My rule of thumb is that if one cannot figure out the sentry issue within 5-10 minutes of looking at the related code (and unless a user explicitly comments on that issue), just close it as unactionable / unreproducible. If I see that it came from CC / serverless, then spending a bit more time is warranted, but most likely it won't lead anywhere without the user collaboration. In this case, it seems like you have a hypothesis (corrupted descriptor) for the reason, but it's impossible to know how it occurred, so closing sgtm.

**Closed** 2023-10-12 15:47 UTC
Labels: C-bug, O-sentry, T-sql-foundations
