### ISSUE TITLE
TestCorruptedClusterID takes 10s

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7260] opened 2016-06-16 02:52 UTC
no bueno. Probably has to wait for some timeout.

```
go test -v  -i ./server
go test  -run "CorruptedClusterID" -timeout 1m10s ./server -v
=== RUN   TestCorruptedClusterID
I160615 22:51:33.525430 storage/engine/rocksdb.go:143  opening in memory rocksdb instance
I160615 22:51:33.528787 storage/replica_command.go:1570  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407234h51m38.028350059s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-06-16 02:51:33.528688123 +0000 UTC]
W160615 22:51:33.530108 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
W160615 22:51:43.532803 storage/store.go:1059  [node=1,store=1] error gossiping system config: storage/replica.go:2474: node is stopping
--- PASS: TestCorruptedClusterID (10.01s)
PASS
ok  	github.com/cockroachdb/cockroach/server	10.039s
```

**Comment by bdarnell** [comment] 2016-06-16 02:58
Duplicate of #6889

**Closed by bdarnell** 2016-06-16 02:58 UTC
