### ISSUE TITLE
acceptance: allocator tests failing during cluster init

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#18817] opened 2017-09-27 11:01 UTC
During last night's runs of the allocator tests, the initial cluster failed to start. This is a new problem that started with last night's runs. The messages in [one of the cockroach.log files](https://teamcity.cockroachdb.com/repository/download/Cockroach_AllocatorTest1to310g/362270:id/acceptance/node.0/cockroach/cockroach.log) point to startup/init errors:

```
I170927 06:17:06.272982 200 gossip/server.go:232  [n1] received initial cluster-verification connection from {tcp uprep-1to3s-kickassnorthcutt-cockroach-1:26257}
I170927 06:17:06.276470 40 gossip/client.go:134  [n1] closing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257): stopping outgoing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I170927 06:17:06.296202 196 storage/node_liveness.go:355  [n1,hb] heartbeat failed on epoch increment; retrying
I170927 06:17:07.104318 430 gossip/client.go:129  [n1] started gossip client to uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257
I170927 06:17:07.105706 430 gossip/client.go:134  [n1] closing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257): stopping outgoing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I170927 06:17:08.106772 717 gossip/client.go:129  [n1] started gossip client to uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257
I170927 06:17:08.108127 717 gossip/client.go:134  [n1] closing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257): stopping outgoing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I170927 06:17:09.108819 1094 gossip/client.go:129  [n1] started gossip client to uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257
I170927 06:17:09.109559 1094 gossip/client.go:134  [n1] closing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257): stopping outgoing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
I170927 06:17:10.110920 1112 gossip/client.go:129  [n1] started gossip client to uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257
I170927 06:17:10.112004 1112 gossip/client.go:134  [n1] closing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257): stopping outgoing client to node 1 (uprep-1to3s-kickassnorthcutt-cockroach-1.eastus.cloudapp.azure.com:26257); loopback connection
W170927 06:17:10.487129 97 storage/store.go:3592  [n1,s1] handle raft ready: 1.4s [processed=1]
W170927 06:17:10.487409 1064 storage/node_liveness.go:417  [n1,s1,r5/1:/System/ts{d-e}] slow heartbeat took 1.4s
W170927 06:17:10.487595 1122 storage/node_liveness.go:417  [n1,s1,r4/1:/System/{NodeLiveâ€¦-tsd}] slow heartbeat took 1.4s
W170927 06:17:10.487685 1108 storage/node_liveness.go:417  [n1,s1,r7/1:/Table/{SystemConâ€¦-11}] slow heartbeat took 1.4s
```

Failed tests:
https://teamcity.cockroachdb.com/viewLog.html?buildId=362270&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest1to310g
https://teamcity.cockroachdb.com/viewLog.html?buildId=362278&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_SchemaChangeTest3to510g
https://teamcity.cockroachdb.com/viewLog.html?buildId=362271&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest3to510g

Here's an example `cockroach.log`:
https://teamcity.cockroachdb.com/repository/download/Cockroach_AllocatorTest1to310g/362270:id/acceptance/node.0/cockroach/cockroach.log

cc @benesch

**Comment by a-robinson** [comment] 2017-09-27 19:37
I'm inclined to think this is the same issue as #18825, which was caused by #18689 and just fixed by #18835. If it fails again tonight, we'll know that's incorrect. If it passes the next few nights, I'll close this on Monday.

**Comment by a-robinson** [comment] 2017-10-02 14:35
Well, they did all pass for the next day or two, but are back to failing, so I guess I can't get out of this quite so easily :)

**Comment by a-robinson** [comment] 2017-10-02 19:03
Well, it turns out I can get out of it this easily. The last few days worth of failures have been due to https://github.com/cockroachdb/cockroach/issues/18940.

cc @petermattis, mostly just to be aware that the acceptance tests are apparently pretty good at detecting proto-related breakages.

**Closed by a-robinson** 2017-10-02 19:03 UTC

**Comment by petermattis** [comment] 2017-10-02 19:22
Ack. Will pay closer attention in the future.
