### ISSUE TITLE
circleci: failed tests (15863): TestClusterRecovery 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5871] opened 2016-04-05 16:05 UTC
The following test appears to have failed:

[#15863](https://circleci.com/gh/cockroachdb/cockroach/15863):

```
I160405 16:00:33.065277 acceptance/replication_test.go:66  found 2 replicas
I160405 16:00:33.166005 acceptance/cluster/localcluster.go:649  stopping
I160405 16:00:33.166204 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160405 16:00:33.166223 acceptance/cluster/localcluster.go:570  events monitor exits
I160405 16:00:33.167462 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container f4310fb45919890b4d2699f9d71da25812e4e614151a2775601e8d9c5b1a197c: Container f4310fb45919890b4d2699f9d71da25812e4e614151a2775601e8d9c5b1a197c is not running
--- FAIL: TestClusterRecovery (19.30s)
	testing.go:113: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestNodeRestart
I160405 16:00:35.174455 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160405 16:00:35.175995 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160405 16:00:35.748143 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.886941342
I160405 16:00:35.793518 acceptance/cluster/localcluster.go:532  events monitor starts
I160405 16:00:36.056373 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32798
  trace:     https://127.0.0.1:32798/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-05 21:08
Duplicate of #5858.

**Closed by petermattis** 2016-04-05 21:08 UTC
Labels: Robot, test-failure
