### ISSUE TITLE
changefeedccl: remove old webhook and pubsub sinks

### ISSUE THREAD

**Issue by amruss** [cockroachdb/cockroach#109353] opened 2023-08-23 17:24 UTC
We are turning the new sink implementations on by default
https://github.com/cockroachdb/cockroach/issues/108806 

We should delete the old implementations

Jira issue: CRDB-30887

**Comment by rharding6373** [comment] 2024-05-23 16:37
Dupe of https://github.com/cockroachdb/cockroach/issues/121249

**Closed by rharding6373** 2024-05-23 16:37 UTC
Labels: C-enhancement
