### ISSUE TITLE
prod: env var set by Kubernetes interferes with server initialization

### ISSUE THREAD

**Issue by patwhite** [cockroachdb/cockroach#8876] opened 2016-08-28 17:12 UTC
Attempting to run cockroach on kubernetes, and seeing crash. Log file:

```
+ CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)")
++ hostname -f
+ /cockroach/cockroach start --logtostderr --insecure --host cockroach-ktbqx
I160828 16:25:48.273274 cli/start.go:342  CockroachDB beta-20160728-675-g2d7438d (linux amd64, built 2016/08/27 01:22:56, go1.7)
I160828 16:25:48.376600 cli/backtrace.go:40  backtrace disabled: stat /opt/backtrace/bin/ptrace: no such file or directory
I160828 16:25:48.376905 server/context.go:407  1 storage engine initialized
I160828 16:25:48.380121 cli/start.go:362  starting cockroach node
Error: failed to start Cockroach server: unable to resolve RPC address "cockroach-ktbqx:tcp://10.59.253.106:8080": too many colons in address cockroach-ktbqx:tcp://10.59.253.106:8080
Failed running "start"
```

Attempting to run on Google Container Engine, which hosts kubernetes 1.3.5. I've tried numerous different combinations of yaml files and configurations, but this one failed (you need to have a data disk created):

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: cockroach
  labels:
    component: cockroach
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cockroach
    spec:
      serviceAccount: cockroach
      containers:
      - name: cockroach
        image: cockroachdb/cockroach:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 26257
          name: data
          protocol: TCP
        volumeMounts:
        - mountPath: /cockroach/cockroach-data
          name: data
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            CRARGS=("start" "--logtostderr" "--insecure" "--host" "$(hostname -f)")
            /cockroach/cockroach ${CRARGS[*]}
      volumes:
      - name: data
        # This GCE PD must already exist.
        gcePersistentDisk:
          pdName: cockroach-1-data
          fsType: ext4
```

By all accounts it seems this should work, but not having any luck.

**Comment by tschottdorf** [comment] 2016-08-28 17:31
`cockroach-ktbqx:tcp://10.59.253.106:8080` looks weird and you're not (obviously) passing it to `cockroach start`. Did you perhaps botch setting your hostname? What does `hostname -f` return in this context?

**Comment by tschottdorf** [comment] 2016-08-28 17:32
Ah, nevermind. The log seems to indicate that that indeed returns `cockroach-ktbqx`.

**Comment by patwhite** [comment] 2016-08-28 17:36
Ya, it's a weird one, feels like something from the internals, but hard to say. Happy to try and debug if you have any ideas.

**Comment by tschottdorf** [comment] 2016-08-28 17:37
What version are you running?

**Comment by knz** [comment] 2016-08-28 17:38
It's in the log: beta-20160728-675-g2d7438d

**Comment by tschottdorf** [comment] 2016-08-28 17:42
Duh, thanks @knz.

**Comment by a-robinson** [comment] 2016-08-28 22:24
The exact same yaml config works for me locally on minikube if I remove the `serviceAccount` and use a `hostPath` instead of a `gcePersistentDisk`. The only difference is that I pulled down image beta-20160728-677-g2542434.

Where is the extra ":tcp" coming from? I've never seen that get added anywhere within Kubernetes. I can check out the cockroach startup code tomorrow, I've been meaning to do that soon anyways.

However, for what it's worth, if all you want to do is get cockroach working in a 1-node configuration, I'd recommend just dropping the `--host $(hostname -f)` part of the command and just let it listen on all interfaces.

**Comment by patwhite** [comment] 2016-08-28 22:42
@a-robinson I think I tried that configuration, but just to be sure, I retried. The only real change besides host was getting rid of the service account. Same result, here's the new log file:

```
+ CRARGS=("start" "--logtostderr" "--insecure")
+ /cockroach/cockroach start --logtostderr --insecure
I160828 22:40:14.784666 cli/start.go:342  CockroachDB beta-20160728-677-g2542434 (linux amd64, built 2016/08/28 19:14:59, go1.7)
I160828 22:40:14.885304 cli/backtrace.go:40  backtrace disabled: stat /opt/backtrace/bin/ptrace: no such file or directory
I160828 22:40:14.885658 server/context.go:407  1 storage engine initialized
I160828 22:40:14.885805 cli/start.go:362  starting cockroach node
Error: failed to start Cockroach server: unable to resolve RPC address ":tcp://10.59.253.174:8080": too many colons in address :tcp://10.59.253.174:8080
Failed running "start"
```

And the updated yaml:
```
apiVersion: v1
kind: ReplicationController
metadata:
  name: cockroach
  labels:
    component: cockroach
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: cockroach
    spec:
#      serviceAccount: cockroach
      containers:
      - name: cockroach
        image: cockroachdb/cockroach:latest
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 26257
          name: data
          protocol: TCP
        volumeMounts:
        - mountPath: /cockroach/cockroach-data
          name: data
        command:
          - "/bin/bash"
          - "-ecx"
          - |
            CRARGS=("start" "--logtostderr" "--insecure")
            /cockroach/cockroach ${CRARGS[*]}
      volumes:
      - name: data
        # This GCE PD must already exist.
        gcePersistentDisk:
          pdName: cockroach-1-data
          fsType: ext4

**Comment by patwhite** [comment] 2016-08-28 22:44
Does cockroach try to ping itself on the admin port or anything? It could be a routing thing in GCE, but then again, the "too many colons" thing really looks like it's grabbing something internally it shouldn't.

**Comment by tschottdorf** [comment] 2016-08-28 23:28
No, this is barfing when it tries to bind to the host, in this bit of code:

```go
	if _, err := net.ResolveTCPAddr("tcp", srvCtx.Addr); err != nil {
		return nil, errors.Errorf("unable to resolve RPC address %q: %v", srvCtx.Addr, err)
	}
```

See whether you have any environment variables left - we use some of them, and perhaps we're just clashing with something that is also provided by Kubernetes (in fact, that is a likely explanation). Maybe `COCKROACH_PORT` is set in the container or something like that? Just dump the env and see.

**Comment by a-robinson** [comment] 2016-08-29 02:48
Hm, I tried exactly replicating your config on GKE version 1.3.5 (other than the service account), even down to finding the exact same docker image (cockroachdb/cockroach:alpha-12673-g2d7438d) and can't reproduce the problem.

Does it happen if you retry it with a different persistent disk? Maybe some weird state has gotten onto it.

**Comment by patwhite** [comment] 2016-08-29 07:36
@tschottdorf Great call, here's the dump, looks like you're right. So, hard to say if this is a bug or not, but I think more people will run into it. Basically, if you create a service cockroach it injects the env variable COCKROACH_PORT, which it looks like you use internally. 

```
HOSTNAME=cockroach-y1hcn
ELASTICSEARCH_PORT_9200_TCP_PORT=9200
KUBERNETES_PORT=tcp://10.59.240.1:443
KUBERNETES_PORT_443_TCP_PORT=443
COCKROACH_SERVICE_PORT_DATA=26257
COCKROACH_SERVICE_HOST=10.59.240.192
ELASTICSEARCH_SERVICE_PORT=9200
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.59.240.1
COCKROACH_SERVICE_PORT_HTTP=8080
ELASTICSEARCH_PORT_9200_TCP_PROTO=tcp
ELASTICSEARCH_PORT_9300_TCP_PORT=9300
COCKROACH_PORT=tcp://10.59.240.192:8080
ELASTICSEARCH_SERVICE_PORT_HTTP=9200
ELASTICSEARCH_PORT_9300_TCP_ADDR=10.59.246.96
COCKROACH_PORT_8080_TCP_PROTO=tcp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
COCKROACH_PORT_26257_TCP_ADDR=10.59.240.192
COCKROACH_PORT_26257_TCP=tcp://10.59.240.192:26257
PWD=/cockroach
COCKROACH_PORT_8080_TCP_PORT=8080
COCKROACH_PORT_26257_TCP_PORT=26257
SHLVL=1
HOME=/root
ELASTICSEARCH_PORT=tcp://10.59.246.96:9200
COCKROACH_PORT_8080_TCP=tcp://10.59.240.192:8080
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
ELASTICSEARCH_PORT_9200_TCP=tcp://10.59.246.96:9200
COCKROACH_PORT_26257_TCP_PROTO=tcp
COCKROACH_SERVICE_PORT=8080
ELASTICSEARCH_SERVICE_HOST=10.59.246.96
ELASTICSEARCH_PORT_9300_TCP=tcp://10.59.246.96:9300
COCKROACH_PORT_8080_TCP_ADDR=10.59.240.192
KUBERNETES_PORT_443_TCP_ADDR=10.59.240.1
ELASTICSEARCH_PORT_9300_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.59.240.1:443
ELASTICSEARCH_PORT_9200_TCP_ADDR=10.59.246.96
```

I changed the name of the pods and services to cockroachdb, and things started up just fine.

I'll change the service name for the time being, but you may want to consider how to warn / deal with this in documentation, I don't think in the docs I read (start, etc.) that there was any mention of env variables, only of command line args. Or maybe don't even support a env variable for this, you can always pipe env variable to a command line.

Anyawys, thanks for all your help guys!

**Comment by tschottdorf** [comment] 2016-08-29 13:28
Thanks @patwhite, glad you got it running. We're going to have to do something about this (and in particular we should print at startup which env vars, if any, informed the running process' configuration.

**Comment by a-robinson** [comment] 2016-08-29 13:31
Yeah, agreed on having to do something about this, both to make it easier to understand and probably to change the behavior. All those env vars are locked into the Kubernetes API and aren't going to be going away anytime soon, if ever.

Thanks @patwhite!

**Comment by smarterclayton** [comment] 2016-08-31 03:53
They are locked in for at least the next two majors but xrefing the removal issue https://github.com/kubernetes/kubernetes/issues/7365

**Comment by spencerkimball** [comment] 2017-04-03 22:29
@a-robinson, could you decide whether this should be 1.0? Remove that milestone if not.

**Comment by a-robinson** [comment] 2017-04-03 22:47
We now print the environment variables used, so at least it'll be somewhat clear to users why they're getting the error. We also now have easily discoverable configurations for kubernetes so that fewer people will be trying to craft their own. 

I'd be comfortable closing this due to the above, but it'd be nice to just remove the environment variable aliases for our flags. That would align pretty well with the sentiment in #9189. Let me follow up on that.

**Closed** 2017-04-04 20:03 UTC
Labels: community-questions, docs-todo
