### ISSUE TITLE
Unexpected Error of Unique Index

### ISSUE THREAD

**Issue by bajinsheng** [cockroachdb/cockroach#83976] opened 2022-07-07 08:09 UTC
**Describe the problem**

When executing the following sql statements, CockroachDB returns this error.

**To Reproduce**

```sql
CREATE TABLE t0 (c0 TIME AS (TIME '1970-01-17T15:19:39') STORED NOT NULL );
CREATE UNIQUE INDEX ON t0(c0);

SELECT * FROM t0 WHERE (t0.rowid IS NULL) OR (t0.c0 IS NULL); -- ERROR: cannot execute distinct on no columns
```

**Expected behavior**
No error.

**Additional data / screenshots**

**Environment:**
 - CockroachDB version [02dcb3816c4148ee15318a614901b266f1b8ae34]
 - Server OS: [Ubuntu 20.04]
 - Client app [`cockroach sql`]

**Additional context**

Jira issue: CRDB-17382

**Comment by rytaft** [comment] 2022-07-21 16:16
Thanks for the report! I can confirm that this bug exists on all versions since 21.2. Moving it to backlog since it's not a new issue, but assigning quick win label so someone can pick it up during a fixit day.

**Closed** 2022-12-14 00:55 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries, E-quick-win
