### ISSUE TITLE
sql-queries: tpch workload is failing due to "disk budget exceeded"

### ISSUE THREAD

**Issue by nameisbhaskar** [cockroachdb/cockroach#134415] opened 2024-11-06 15:33 UTC
We are trying to run the tpch workload on drt-scale cluster with a scale factor of 1000. We are seeing the following error while running the queries by tpch workload:
```
Nov 06 11:09:02 workload-scale-0001 bash[17452]: E241106 11:09:02.935389 1 workload/cli/run.go:599  [-] 20  [q2]: pq: temp disk storage: disk budget exceeded: 1048576 bytes requested, 3435>
Nov 06 11:09:02 workload-scale-0001 bash[17452]: Error: [q2]: pq: temp disk storage: disk budget exceeded: 1048576 bytes requested, 34359738368 currently allocated, 34359738368 bytes in bu>
Nov 06 11:09:02 workload-scale-0001 systemd[1]: tpch_run_scale_factor_1000.service: Main process exited, code=exited, status=1/FAILURE
Nov 06 11:09:02 workload-scale-0001 systemd[1]: tpch_run_scale_factor_1000.service: Failed with result 'exit-code'.
Nov 06 11:09:02 workload-scale-0001 systemd[1]: tpch_run_scale_factor_1000.service: Consumed 1.336s CPU time.
```

The disk capacity for the cluster is at 30% and still we are seeing this error. More details in the slack thread: https://cockroachlabs.slack.com/archives/C07HPMBLVJ7/p1730892175726699?thread_ts=1730789573.794549&cid=C07HPMBLVJ7

Jira issue: CRDB-44072

**Comment by mgartner** [comment] 2024-11-12 19:58
Duplicate of #134333.

**Closed by mgartner** 2024-11-12 19:58 UTC
Labels: C-bug, T-sql-queries, O-testcluster, branch-release-24.3, O-24.3-scale-testing
