### ISSUE TITLE
circleci: failed tests (13525): TestSSLEnforcement 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4725] opened 2016-02-29 19:55 UTC
The following test appears to have failed:

[#13525](https://circleci.com/gh/cockroachdb/cockroach/13525):

```
E160229 19:53:18.500941 server.go:2159  http: TLS handshake error from 127.0.0.1:57200: tls: first record does not look like a TLS handshake
E160229 19:53:18.574595 server.go:2159  http: TLS handshake error from 127.0.0.1:57202: tls: first record does not look like a TLS handshake
E160229 19:53:18.620207 server.go:2159  http: TLS handshake error from 127.0.0.1:57203: tls: first record does not look like a TLS handshake
E160229 19:53:18.651673 server.go:2159  http: TLS handshake error from 127.0.0.1:57204: tls: first record does not look like a TLS handshake
I160229 19:53:18.690547 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestSSLEnforcement (5.96s)
	authentication_test.go:148: [28]: expected success=true, got err=Post https://127.0.0.1:55662/sql/Execute: stream error: stream ID 13; STREAM_CLOSED
=== RUN   TestParseInitNodeAttributes
I160229 19:53:18.709591 server/context.go:141  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
I160229 19:53:18.710388 server/context.go:229  1 storage engine initialized
I160229 19:53:18.710483 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestParseInitNodeAttributes (0.00s)
=== RUN   TestParseJoinUsingAddrs
I160229 19:53:18.713231 server/context.go:141  can't read available memory from cgroups (open /sys/fs/cgroup/memory/memory.limit_in_bytes: no such file or directory)
I160229 19:53:18.713793 server/context.go:229  1 storage engine initialized
I160229 19:53:18.713957 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--
E160229 19:53:36.273725 server/server.go:370  failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:620: node 1 stopped
I160229 19:53:36.275122 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (0.70s)
=== RUN   TestNewStoreSpec
--- PASS: TestNewStoreSpec (0.03s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	37.823s
=== RUN   TestMetricsRecorder
--- PASS: TestMetricsRecorder (0.11s)
=== RUN   TestRuntimeStatRecorder
I160229 19:53:12.785619 server/status/runtime.go:137  runtime stats: 5 goroutines, 4.86MiB active, 50000000.00cgo/sec, 1260290.00/326740.00 %(u/s)time, 283545.73 %gc (4x)
--- PASS: TestRuntimeStatRecorder (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/server/status	1.195s
=== RUN   TestSplitOrExpr
--- PASS: TestSplitOrExpr (0.02s)
=== RUN   TestSplitAndExpr

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-29 20:39
Dupe of #4718

**Closed by bdarnell** 2016-02-29 20:39 UTC
Labels: test-failure
