### ISSUE TITLE
Test failure in CI build 7202

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2441] opened 2015-09-10 00:06 UTC
The following test appears to have failed:

[#7202](https://circleci.com/gh/cockroachdb/cockroach/7202):

```
E0910 00:06:03.012425 998 storage/replica.go:980  error executing raft command: key range "\x00\x00meta2\xff\xff"-"" outside of bounds of range ""-""
E0910 00:06:03.012514 998 storage/replica.go:980  error executing raft command: key range "\x00\x00meta1\xff\xff"-"" outside of bounds of range ""-""
E0910 00:06:03.012606 998 storage/replica.go:980  error executing raft command: key range ""-"" outside of bounds of range ""-""
W0910 00:06:03.012642 998 multiraft/multiraft.go:916  aborting configuration change: key range ""-"" outside of bounds of range ""-""
W0910 00:06:03.012701 998 multiraft/multiraft.go:916  aborting configuration change: key range ""-"" outside of bounds of range ""-""
--- FAIL: TestRaftRemoveRace (1.94s)
	testing.go:150: storage/client_test.go:350: condition failed to evaluate within 1s: storage/client_test.go:346: range not found on store 2
=== RUN   TestStoreRangeRepair
I0910 00:06:04.047841 998 multiraft/multiraft.go:447  node 100000001 starting
I0910 00:06:04.047930 998 storage/replica.go:1191  gossiping cluster id  from store 1, range 1
I0910 00:06:04.048084 998 raft/raft.go:406  group 1 100000001 became follower at term 5
I0910 00:06:04.048150 998 raft/raft.go:219  group 1 newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0910 00:06:04.048277 998 raft/raft.go:485  group 1 100000001 is starting a new election at term 5
I0910 00:06:04.048307 998 raft/raft.go:419  group 1 100000001 became candidate at term 6
I0910 00:06:04.048321 998 raft/raft.go:468  group 1 100000001 received vote from 100000001 at term 6
I0910 00:06:04.048354 998 raft/raft.go:447  group 1 100000001 became leader at term 6
--
I0910 00:06:07.572571 998 storage/replica_command.go:1109  initiating a split of range=63 ["db13/table"-"db14") at key "db13/tablf"
W0910 00:06:07.577500 998 storage/store.go:1374  conflicting intents on ["\x00\x00meta2db14"]: resolved? true
--- PASS: TestStoreRangeManySplits (1.30s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.16s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	12.686s
=== RUN   TestBatchBasics
I0910 00:05:49.311296 969 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0910 00:05:49.311949 969 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0910 00:05:49.314261 969 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-10 15:28
dupe of #2417.

**Closed by tamird** 2015-09-10 15:28 UTC
Labels: test-failure
