### ISSUE TITLE
circleci: failed tests (13862): TestRestoreReplicas

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4875] opened 2016-03-04 23:11 UTC
The following test appears to have failed:

[#13862](https://circleci.com/gh/cockroachdb/cockroach/13862):

```
I160304 23:10:18.413660 raft/raft.go:459  [group 1] 1 became follower at term 6
I160304 23:10:18.413852 raft/raft.go:235  [group 1] newRaft 1 [peers: [1,2], term: 6, commit: 15, applied: 15, lastindex: 15, lastterm: 6]
I160304 23:10:18.414403 storage/replica.go:1709  [node=1,store=1,range=1] gossiping system config from store 1, range 1, hash 91100e0451ac1aab78723f763fac84cccdd4aea5
I160304 23:10:18.415501 storage/replica.go:1650  [node=1,store=1,range=1] gossiping cluster id "00000000-0000-0000-0000-000000000000" from store 1, range 1
I160304 23:10:18.415993 storage/replica.go:1659  [node=1,store=1,range=1] gossiping sentinel from store 1, range 1
panic: gossip infostore's NodeID is 0

goroutine 5132 [running]:
github.com/cockroachdb/cockroach/gossip.(*infoStore).newInfo(0xc820168000, 0xc8202e59f8, 0x10, 0x10, 0x1bf08eb000, 0x2a)
	/go/src/github.com/cockroachdb/cockroach/gossip/infostore.go:135 +0xb4
github.com/cockroachdb/cockroach/gossip.(*Gossip).AddInfo(0xc8201c4000, 0x1c86df0, 0x8, 0xc8202e59f8, 0x10, 0x10, 0x1bf08eb000, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:522 +0x12b
github.com/cockroachdb/cockroach/storage.(*Replica).maybeGossipFirstRange(0xc820182b60, 0x3587780)
	/go/src/github.com/cockroachdb/cockroach/storage/replica.go:1661 +0xeea
github.com/cockroachdb/cockroach/storage.(*Store).maybeGossipFirstRange(0xc82017ae00, 0xc82047b780)
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:797 +0x3c3
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func1()
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:741 +0x6d
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201dc8c0, 0xc82068f5c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	8.894s
=== RUN   TestBatchBasics
I160304 23:10:29.559582 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I160304 23:10:29.568940 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I160304 23:10:29.574187 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 02:27
Duplicate of #4821.

**Closed by petermattis** 2016-03-06 02:27 UTC
Labels: test-failure
