### ISSUE TITLE
build: unable to inject temporary updates to dependencies

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#56177] opened 2020-10-31 09:21 UTC
Use case: as a crdb developer, I often want to test changes to our own dependency packages *before I commit the changes or tag a released version*.

Until recently, I was able to edit files in the `vendor` directory, for example I would run

```
  cp /path/to/my/dep/working/directory/source.go  vendor/dep/directory/source.go
```

However with the new `go.mod` / `bazel` infrastructure, this works horribly: my changes to the `vendor` directory are ignored and the build system picks the "pinned" version in any case.

I would like a solution to this and a documentation for it in the wiki.

cc @jlinder @otan

**Comment by irfansharif** [comment] 2020-12-17 03:54
Ref: https://github.com/bazelbuild/rules_go/blob/0.19.0/go/workspace.rst#overriding-dependencies

**Comment by rickystewart** [comment] 2021-02-02 17:37
Today, this is *almost* easy. For example you can create a `.bazelrc.user` with the content:

```
build --override_repository=com_github_cockroachdb_sentry_go=/Users/ricky/go/src/github.com/cockroachdb/sentry-go
```

... and then you can update the local content of the repo and see them reflected in your build. The problem is our usage of Gazelle which doesn't square with this for Go repos, so you get errors like this:

```
ERROR: /Users/ricky/go/src/github.com/cockroachdb/cockroach/pkg/util/log/logcrash/BUILD.bazel:3:11: //pkg/util/log/logcrash:logcrash depends on @com_github_cockroachdb_sentry_go//:sentry-go in repository @com_github_cockroachdb_sentry_go which failed to fetch. no such package '@com_github_cockroachdb_sentry_go//': No WORKSPACE file found in /private/var/tmp/_bazel_ricky/be70b24e7357091e16c49d70921b7985/external/com_github_cockroachdb_sentry_go
```

You can pretty easily work around this by just pulling a custom commit from a custom fork, but that's more difficult than just updating a local file.

**Comment by knz** [comment] 2021-02-02 18:30
> just pulling a custom commit from a custom fork,

What's the step-by-step method to achieve that?

**Comment by rickystewart** [comment] 2021-04-28 22:44
Here's an example:

```
diff --git a/DEPS.bzl b/DEPS.bzl
index 0c96711652..20adceeb9c 100644
--- a/DEPS.bzl
+++ b/DEPS.bzl
@@ -585,8 +585,9 @@ def go_deps():
         name = "com_github_cockroachdb_sentry_go",
         build_file_proto_mode = "disable_global",
         importpath = "github.com/cockroachdb/sentry-go",
-        sum = "h1:IKgmqgMQlVJIZj19CdocBeSfSaiCbEBZGKODaixqtHM=",
-        version = "v0.6.1-cockroachdb.2",
+        vcs = "git",
+        remote = "https://github.com/rickystewart/sentry-go",  # Custom fork.
+        commit = "6c8e10aca9672de108063d4953399bd331b54037",  # Custom commit.
     )
     go_repository(
         name = "com_github_cockroachdb_stress",

```

**Comment by knz** [comment] 2021-04-29 07:16
Can I use a local filesystem path to a fit clone in the remote field?

**Comment by rickystewart** [comment] 2021-04-29 16:33
Yup.

```
diff --git a/DEPS.bzl b/DEPS.bzl
index 8800f1a561..33569eb3dc 100644
--- a/DEPS.bzl
+++ b/DEPS.bzl
@@ -585,8 +585,9 @@ def go_deps():
         name = "com_github_cockroachdb_sentry_go",
         build_file_proto_mode = "disable_global",
         importpath = "github.com/cockroachdb/sentry-go",
-        sum = "h1:IKgmqgMQlVJIZj19CdocBeSfSaiCbEBZGKODaixqtHM=",
-        version = "v0.6.1-cockroachdb.2",
+        vcs = "git",
+        remote = "/Users/ricky/go/src/github.com/cockroachdb/sentry-go",  # Custom fork.
+        commit = "6c8e10aca9672de108063d4953399bd331b54037",  # Custom commit.
     )
     go_repository(
         name = "com_github_cockroachdb_stress",

```

I'll take an action item to update the documentation letting people know this is possible.

**Comment by knz** [comment] 2021-04-29 16:45
that's great, I love it

**Comment by rickystewart** [comment] 2021-04-29 17:00
Also updated https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1380090083/How+to+ensure+your+code+builds+with+Bazel with a pointer to DEPS.bzl (that will fully make sense when the PR is merged).

**Closed** 2021-04-29 18:45 UTC
Labels: A-build-system, C-bug
