### ISSUE TITLE
Test failure in CI build 10063

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3400] opened 2015-12-10 21:22 UTC
The following test appears to have failed:

[#10063](https://circleci.com/gh/cockroachdb/cockroach/10063):

```
W1210 21:22:22.296639 1101 multiraft/multiraft.go:1298  node 1 failed to send message to 3: multiraft/transport.go:158: unknown peer 3
W1210 21:22:22.299412 1101 multiraft/multiraft.go:1298  node 2 failed to send message to 3: multiraft/transport.go:158: unknown peer 3
I1210 21:22:22.376653 1101 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1210 21:22:22.376778 1101 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1210 21:22:22.376865 1101 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (1.38s)
	testing.go:157: storage/client_raft_test.go:1322: condition failed to evaluate within 1s: storage/client_test.go:576: expected [16 0 5], got [16 5 5]
=== RUN   TestReplicateReAddAfterDown
E1210 21:22:22.377961 1101 gossip/gossip.go:181  different node IDs were set for the same gossip instance (2147483647, 1)
I1210 21:22:22.378296 1101 multiraft/multiraft.go:579  node 1 starting
I1210 21:22:22.378381 1101 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1210 21:22:22.378728 1101 raft/raft.go:441  [group 1] 1 became follower at term 5
I1210 21:22:22.378873 1101 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1210 21:22:22.378919 1101 multiraft/multiraft.go:999  node 1 campaigning because initial confstate is [1]
I1210 21:22:22.378935 1101 raft/raft.go:521  [group 1] 1 is starting a new election at term 5
I1210 21:22:22.378949 1101 raft/raft.go:454  [group 1] 1 became candidate at term 6
--
I1210 21:22:28.742753 1101 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
I1210 21:22:28.742899 1101 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.34s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.13s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	20.138s
=== RUN   TestBatchBasics
I1210 21:22:00.275533 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1210 21:22:00.276718 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.02s)
=== RUN   TestBatchMerge
I1210 21:22:00.297366 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto
--
=== RUN   TestEngineBatchCommit
I1210 21:22:00.374593 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEngineBatchCommit (0.07s)
=== RUN   TestEngineBatch
I1210 21:22:00.438764 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- FAIL: TestEngineBatch (0.05s)
	engine_test.go:216: 0: expected , but got Coc~roachDBr  BC
	engine_test.go:237: 0: expected , but got Coc~roachDBr  BC
	engine_test.go:248: 0: expected , but got Coc~roachDBr  BC
=== RUN   TestEnginePutGetDelete
I1210 21:22:00.440058 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEnginePutGetDelete (0.00s)
=== RUN   TestEngineMerge
I1210 21:22:00.442666 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestEngineMerge (0.00s)
=== RUN   TestEngineScan1
--
=== RUN   TestWillOverflow
--- PASS: TestWillOverflow (0.00s)
=== RUN   TestRocksDBCompaction
I1210 21:22:01.079079 1080 storage/engine/rocksdb.go:138  closing in-memory rocksdb instance
--- PASS: TestRocksDBCompaction (0.00s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage/engine	0.826s
?   	github.com/cockroachdb/cockroach/storage/engine/rocksdb	[no test files]
?   	github.com/cockroachdb/cockroach/storage/simulation	[no test files]
?   	github.com/cockroachdb/cockroach/testutils	[no test files]
?   	github.com/cockroachdb/cockroach/testutils/gossiputil	[no test files]
=== RUN   TestStoreTimeSeries
I1210 21:22:19.923826 1132 multiraft/multiraft.go:579  node 1 starting
I1210 21:22:19.924015 1132 gossip/gossip.go:189  setting node descriptor node_id:1 address:<network_field:"" address_field:"" > attrs:<> 
I1210 21:22:19.924047 1132 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1210 21:22:19.924360 1132 raft/raft.go:441  [group 1] 1 became follower at term 5
I1210 21:22:19.924399 1132 kv/range_cache.go:129  lookup range descriptor: key=/System/"tsd test.metric\x00\x01\x89\x85\xfe\x1b\xff"

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2015-12-11 18:37
Duplicate of #3384.

**Closed by petermattis** 2015-12-11 18:37 UTC
Labels: test-failure
