### ISSUE TITLE
Problems Launching with Docker or from dev build

### ISSUE THREAD

**Issue by cloudmode** [cockroachdb/cockroach#590] opened 2015-04-08 15:21 UTC
root@b656c892f035:/cockroach# ./cockroach init -stores ssd="$(mktemp -d /tmp/dbXXX)" &> node.log &
root@b656c892f035:/cockroach# more node.log
I0408 15:16:28.119047      10 context.go:147] Initialized 1 storage engine(s)
Cockroach cluster 5888add2-cc17-468d-95a3-e4f17d79a247 has been initialized
I0408 15:16:28.337995      10 start.go:135] Build Vers: go1.4.2
I0408 15:16:28.338012      10 start.go:136] Build Tag:  alpha-1518-ga889f82
I0408 15:16:28.338017      10 start.go:137] Build Time: 2015/04/08 05:47:30
I0408 15:16:28.338049      10 start.go:138] Build Deps: code.google.com/p/go-commander:df033a4b379cd723ef7408b881c1e092cd943831 code.go
ogle.com/p/go-uuid:35bc42037350f0078e3c974c6ea690f1926603ab code.google.com/p/snappy-go:8850bd446ad6f18a271a08aae26bdf85bdf87c7f github
.com/biogo/store:cb1ae010c5c75b7ce4f5c5d0ef92defcafdfdce4 github.com/cockroachdb/c-protobuf:9e8dac59ca2a3fc82cd0665ad32b1a36f3df40b8 gi
thub.com/cockroachdb/c-rocksdb:72de025ca13dd4ab2dce63e8e19c6a59b8388ffd github.com/cockroachdb/c-snappy:af73b00e85e6f0e3c1fcc51f73f1d03
6df1e99ff github.com/cockroachdb/cockroach:a889f828214fcfd76f7f2689b74cb4bec2bd23a1 github.com/coreos/etcd:e5f2f401450b56947e231336f9e8
350059428036 github.com/elazarl/go-bindata-assetfs:09ba9c6a7e9a5ee35586127fdf88bb20bb4990b7 github.com/gogo/protobuf:bc946d07d1016848df
d2507f90f0859c9471681e github.com/golang/glog:44145f04b68cf362d9c4df2182967c2275eaefed gopkg.in/yaml.v1:9f9df34309c04878acc86042b16630b
0f696e1de
I0408 15:16:28.338071      10 start.go:140] Starting cockroach cluster
I0408 15:16:28.338292      10 context.go:147] Initialized 1 storage engine(s)
W0408 15:16:28.338321      10 tls.go:138] Listening via tcp to b656c892f035:0 without TLS
I0408 15:16:28.339451      10 server.go:144] Started RPC server at b656c892f035:53911
I0408 15:16:28.339482      10 server.go:151] Started gossip instance
F0408 15:16:28.340103      10 gossip.go:322] no hosts specified for gossip network (use -gossip)
goroutine 23 [running]:
github.com/golang/glog.stacks(0x151ea00, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:766 +0xcd
github.com/golang/glog.(*loggingT).output(0x14fb9e0, 0xc200000003, 0xc2081ba000, 0x121264c, 0x9, 0x142, 0x0)
	/go/src/github.com/golang/glog/glog.go:717 +0x283
github.com/golang/glog.(*loggingT).printf(0x14fb9e0, 0x3, 0xf58650, 0x33, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:655 +0x1ef
github.com/golang/glog.Fatalf(0xf58650, 0x33, 0x0, 0x0, 0x0)
	/go/src/github.com/golang/glog/glog.go:1145 +0x64
github.com/cockroachdb/cockroach/gossip.(*Gossip).parseBootstrapAddresses(0xc2081b0600)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:322 +0x1c3
github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap(0xc2081b0600)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:353 +0x53
created by github.com/cockroachdb/cockroach/gossip.(*Gossip).Start
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:260 +0x4e
I0408 15:16:28.340877      10 server.go:93] serving on b656c892f035:53911...

This stack trace is from boot2docker on Mac OSX 10.10. Similar trace when run straight from command line on latest build.

**Comment by cloudmode** [comment] 2015-04-08 15:29
seems to be missing gossip address(s). what should that look like for a standalone node for testing purposes?

**Comment by tschottdorf** [comment] 2015-04-08 15:38
You shouldn't have to specify it. I think that's something that broke within the last 20 commits, I'll have a fix up shortly.

**Comment by tschottdorf** [comment] 2015-04-08 16:07
Should be fixed when #593 lands.

The issue is that when the first node bootstraps itself, it shouldn't require a list of other hosts to connect to (because there may not yet be any). A recent change seems to have broken that.

Of course you could've added just any bootstrap address, like '-gossip doesnotexist:123', but with #590 a node which starts as part of a `./cockroach init` call doesn't require a gossip bootstrap any more.

Thanks for reporting this, @cloudmode!

**Comment by kkaneda** [comment] 2015-04-08 16:15
Ah, I guess my change broke this.. Thanks!

**Comment by tschottdorf** [comment] 2015-04-08 16:16
No @kkaneda, don't think it was you. Must've happened during refactoring of the client package. Unless that was you too ;)

**Closed** 2015-04-08 16:48 UTC
