### ISSUE TITLE
sql: broken tests in Bazel

### ISSUE THREAD

**Issue by rickystewart** [cockroachdb/cockroach#61917] opened 2021-03-12 18:21 UTC
We are making a lot of progress in the migration from make to Bazel. Before we can complete our migration, we need to make sure that all tests in-tree continue to pass when run inside of the Bazel sandbox. The following tests are broken when run in the Bazel sandbox:

    pkg/ccl/logictestccl:logictestccl_test
    pkg/sql/logictest:logictest_test
    pkg/sql/sem/tree/eval_test:eval_test_test
    pkg/util/json:json_test

Please help us by doing the following:

* Reproduce the failure locally; for example, with `bazel test pkg/util/json:json_test`, and consult the test logs to see what went wrong
* Identify the root cause of the failure
* If you are able, repair the failure such that the test passes, and submit a PR removing the `broken_in_bazel` tag from the test (see the linked documentation below)
* If not, take your findings to #bazel in Slack, and we’ll work with you to figure out how we can get the tests working

Helpful documentation:
* [How to ensure your tests can run in the Bazel sandbox (consider starting here!)](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1553172016/How+to+ensure+your+tests+can+run+in+the+Bazel+sandbox)
* [How to ensure your code builds with Bazel](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1380090083/How+to+ensure+your+code+builds+with+Bazel)
* [A user's guide to Bazel](https://docs.bazel.build/versions/4.0.0/guide.html)

**Comment by rafiss** [comment] 2021-03-12 21:54
`pkg/sql/logictest:logictest_test` is failing because it cannot find the spatial libs. This part of `pkg/geo/geos/geos.go` is failing.


```
// initGEOS initializes the CR_GEOS by attempting to dlopen all
// the paths as parsed in by locs.
func initGEOS(dirs []string) (*C.CR_GEOS, string, error) {
	var err error
	for _, dir := range dirs {
		var ret *C.CR_GEOS
		newErr := statusToError(
			C.CR_GEOS_Init(
				goToCSlice([]byte(filepath.Join(dir, getLibraryExt(libgeoscFileName)))),
				goToCSlice([]byte(filepath.Join(dir, getLibraryExt(libgeosFileName)))),
				&ret,
			),
		)
		if newErr == nil {
			return ret, dir, nil
		}
		err = errors.CombineErrors(
			err,
			errors.Newf(
				"geos: cannot load GEOS from dir %q: %s",
				dir,
				newErr,
			),
		)
	}
	if err != nil {
		return nil, "", wrapGEOSInitError(errors.Wrap(err, "geos: error during GEOS init"))
	}
	return nil, "", wrapGEOSInitError(errors.Newf("geos: no locations to init GEOS"))
}
```

It looks in all these places:

```
// findLibraryDirectories returns the default locations where GEOS is installed.
func findLibraryDirectories(flagLibraryDirectoryValue string, crdbBinaryLoc string) []string {
	// Try path by trying to find all parenting paths and appending
	// `lib/libgeos_c.<ext>` to the current working directory, as well
	// as the directory in which the cockroach binary is initialized.
	cwd, err := os.Getwd()
	if err != nil {
		panic(err)
	}
	locs := []string{}
	if flagLibraryDirectoryValue != "" {
		locs = append(locs, flagLibraryDirectoryValue)
	}
	locs = append(
		append(
			locs,
			findLibraryDirectoriesInParentingDirectories(crdbBinaryLoc)...,
		),
		findLibraryDirectoriesInParentingDirectories(cwd)...,
	)
	return locs
}
```

Is it OK to use `bazel.Runfile()` in non-test code? I think someone from the spatial team should help out with this. It looks like by default the GEOS libraries are supposed to be in `/usr/local/lib/cockroach` but IDK if this is overridden for tests

**Comment by rickystewart** [comment] 2021-03-12 22:02
GEOS is a whole unresolved mess: https://github.com/cockroachdb/cockroach/issues/61664, https://github.com/cockroachdb/cockroach/issues/61665

I'll note that this test is blocked on GEOS -- you can ignore it for now.

**Comment by rafiss** [comment] 2021-03-15 16:18
I increased the size of `pkg/ccl/logictestccl:logictestccl_test` to `large` and these tests are now also failing because of GEOS libraries. So I'll close this issue in favor of https://github.com/cockroachdb/cockroach/issues/61665 (and updating the description of that issue to say that these logic tests need GEOS).

**Comment by rickystewart** [comment] 2021-03-23 23:01
Rafi -- `pkg/sql/logictest` is still disabled. I tried applying the following patch to get it working:

```
diff --git a/pkg/sql/logictest/BUILD.bazel b/pkg/sql/logictest/BUILD.bazel
index da1430530d..0c583b9db8 100644
--- a/pkg/sql/logictest/BUILD.bazel
+++ b/pkg/sql/logictest/BUILD.bazel
@@ -57,9 +57,10 @@ go_test(
         "main_test.go",
         "parallel_test.go",
     ],
-    data = glob(["testdata/**"]),
+    data = glob(["testdata/**"]) + [
+        "@cockroach//c-deps:libgeos",
+    ],
     embed = [":logictest"],
-    tags = ["broken_in_bazel"],
     deps = [
         "//pkg/base",
         "//pkg/config/zonepb",
```

I can't really understand the failure here -- the logs are filled with errors like this, I assume it's related?

```
E210323 22:54:39.373411 3905302 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r6/1:/Table/{SystemCon…-11}] 578  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.185777 3906968 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r11/1:/Table/1{5-6}] 580  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.449659 3906812 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r6/1:/Table/{SystemCon…-11}] 583  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:39.479735 3906159 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r6/1:/Table/{SystemCon…-11}] 581  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.438641 3905323 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r35/1:/Table/{39-40}] 582  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:39.414349 3906042 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r4/1:/System{/tsd-tse}] 579  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.648159 3906207 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r4/1:/System{/tsd-tse}] 584  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.646212 3905718 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r11/1:/Table/1{5-6}] 585  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.787127 3906990 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r35/1:/Table/{39-40}] 586  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:40.764085 3906907 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r3/1:/System/{NodeLive…-tsd}] 587  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:43.264977 3905539 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r6/1:/Table/{SystemCon…-11}] 588  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:43.266893 3910282 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r35/1:/Table/{39-40}] 589  failed to heartbeat own liveness record: context canceled
E210323 22:54:43.349203 3907085 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r4/1:/System{/tsd-tse}] 590  failed to heartbeat own liveness record: heartbeat failed on epoch increment
E210323 22:54:43.370662 3907376 pkg/kv/kvserver/replica_range_lease.go:359  [n1,s1,r3/1:/System/{NodeLive…-tsd}] 591  failed to heartbeat own liveness record: heartbeat failed on epoch increment
```

Can you take a look and maybe try to get the test fully working?

**Comment by rafiss** [comment] 2021-03-24 02:11
Those heartbeat logs are likely just noise but I'll take a look at what the issue might be.

**Comment by rafiss** [comment] 2021-03-24 03:57
@rickystewart  I ran this on my GCE worker and it passed. Can you share the error logs you got from the bazel sandbox? (Or whatever the ones here are called `/home/rafiss/.cache/bazel/_bazel_rafiss/0f88dabb340b77574625d94d22fa4e9d/execroot/cockroach/bazel-out/k8-fastbuild/testlogs/pkg/sql/logictest/logictest_test/test.log`

**Comment by rickystewart** [comment] 2021-03-24 15:14
https://gist.github.com/rickystewart/88b771b0b0a7cfd0b4710ec6e376e00e

This also looks related?

```
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136  encountered internal error:
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +invalid index 1 for "EXISTS (SELECT 1)"
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +(1)
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +Wraps: (2) assertion failure
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +Wraps: (3) attached stack trace
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  -- stack trace:
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).EvalSubquery
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/subquery.go:39
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/physicalplan.(*evalAndReplaceSubqueryVisitor).VisitPre
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/physicalplan/expression.go:118
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/sem/tree.WalkExpr
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/sem/tree/walk.go:801
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/physicalplan.MakeExpression
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/physicalplan/expression.go:82
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/physicalplan.(*PhysicalPlan).AddFilter
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/physicalplan/physical_plan.go:760
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_physical_planner.go:2661
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlanForPlanNode
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_physical_planner.go:2710
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPhysPlan
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_physical_planner.go:2639
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_running.go:855
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_running.go:793
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.runPlanInsidePlan
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/apply_join.go:246
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).runRightSidePlan
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/apply_join.go:227
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/apply_join.go:210
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/plan_node_to_row_source.go:166
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Columnarizer).Next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexec/columnarizer.go:199
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*InvariantsChecker).Next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexec/invariants_checker.go:78
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexec/materializer.go:290
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).nextAdapter
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexec/materializer.go:315
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexecerror/error.go:91
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/colexec.(*Materializer).Next
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/colexec/materializer.go:321
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/execinfra/base.go:171
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/execinfra/processorsbase.go:774
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/flowinfra/flow.go:382
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_running.go:359
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/distsql_running.go:968
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor_exec.go:1040
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor_exec.go:912
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor_exec.go:656
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor_exec.go:120
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor.go:1515
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor.go:1517
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +  | 	pkg/sql/conn_executor.go:1438
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +Wraps: (4) invalid index 1 for "EXISTS (SELECT 1)"
E210324 15:05:15.165754 848013 pkg/sql/sqltelemetry/report.go:57  [n1,client=127.0.0.1:57856,hostssl,user=root] 136 +Error types: (1) *colexecerror.notInternalError (2) *assert.withAssertionFailure (3) *withstack.withStack (4) *errutil.leafError
```

**Comment by rafiss** [comment] 2021-03-24 17:09
The `invalid index 1 for "EXISTS (SELECT 1)"` is an internal error and a bad log message. The logic tests are a huge test suite and many of them intentionally test erroring cases. I confirmed the same logs happen in a successful `make testlogic` run.

In the gist you posted, all I see are internal error logs, which are expected. I can't find any results that show that any of the tests failed. Could you point me to a where it says the test failed?

Here's what I got when I ran the test on my GCE worker:
```
$ bazel test pkg/sql/logictest:logictest_test  --sandbox_writable_path=$HOME/.ccache
INFO: Analyzed target //pkg/sql/logictest:logictest_test (2 packages loaded, 1574 targets configured).
INFO: Found 1 test target...
INFO: From CcCmakeMakeRule c-deps/libgeos/include:
Target //pkg/sql/logictest:logictest_test up-to-date:
  bazel-bin/pkg/sql/logictest/logictest_test_/logictest_test

INFO: Elapsed time: 669.721s, Critical Path: 669.12s
INFO: 7 processes: 5 internal, 2 linux-sandbox.
INFO: Build completed successfully, 7 total actions
//pkg/sql/logictest:logictest_test                                       PASSED in 453.1s

INFO: Build completed successfully, 7 total actions
```

**Closed** 2021-03-24 23:07 UTC
Labels: C-bug
