### ISSUE TITLE
circleci: failed tests (15353): TestDockerPHP

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5617] opened 2016-03-27 03:31 UTC
The following test appears to have failed:

[#15353](https://circleci.com/gh/cockroachdb/cockroach/15353):

```
PHP Warning:  pg_query_params(): Query failed: ERROR:  param $1: strconv.ParseInt: parsing "a": invalid syntax in Command line code on line 9
Query failed: ERROR:  param $1: strconv.ParseInt: parsing "a": invalid syntax
I160327 03:31:24.659042 acceptance/cluster/localcluster.go:639  stopping
I160327 03:31:24.659225 acceptance/cluster/localcluster.go:537  event stream done, resetting...: net/http: request canceled
I160327 03:31:24.659244 acceptance/cluster/localcluster.go:560  events monitor exits
panic: test timed out after 5m0s

goroutine 1726 [running]:
panic(0x11a63e0, 0xc82023e760)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x1780758, 0x1e0c5c0, 0x12, 0x12, 0xbc1a0b5d7617e501)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc8205f1f08, 0x177e620)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc8205f1f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:86 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 19 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x20e1d00)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:993 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:594 +0x8a

goroutine 8 [select, 4 minutes, locked to thread]:
runtime.gopark(0x1780f90, 0xc820022f28, 0x14bd318, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820022f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820022f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 21 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 22 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 1531 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x7f39dddffa10, 0xc8200155b0, 0x7f39dddffa80, 0xc82061eae0, 0xc820145500, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x49d
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc8204c4d80, 0x7f39dddffa10, 0xc8200155b0, 0x14b4780, 0x6, 0xc8205c86e0, 0x4a, 0x0, 0x7f39dddfd5d8, 0xc8200db2d0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:93 +0x45a
github.com/docker/engine-api/client.(*Client).sendRequest(0xc8204c4d80, 0x7f39dddffa10, 0xc8200155b0, 0x14b4780, 0x6, 0xc8205c86e0, 0x4a, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:71 +0x2b1
github.com/docker/engine-api/client.(*Client).delete(0xc8204c4d80, 0x7f39dddffa10, 0xc8200155b0, 0xc8205c86e0, 0x4a, 0x0, 0x0, 0xc820014089, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/request.go:55 +0xa6
github.com/docker/engine-api/client.(*Client).NetworkRemove(0xc8204c4d80, 0x7f39dddffa10, 0xc8200155b0, 0xc8206284c0, 0x40, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/network_remove.go:7 +0xb1
--
testing.tRunner(0xc820438750, 0x1e0c698)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 26 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f39dde00b00, 0x72, 0xc82025d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202584c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202584c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820258460, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820124410, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820203ad0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 27 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820203ad0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 257 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f39dde00740, 0x72, 0xc82052b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820286680, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820286680, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820286620, 0xc82052b000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a1d8, 0xc82052b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060750)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 159 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820060340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 367 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f39dde008c0, 0x72, 0xc8201d5000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820430140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820430140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204300e0, 0xc8201d5000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820124118, 0xc8201d5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820202340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 533 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82055ad10)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 274 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820060750)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 465 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f39dde00800, 0x72, 0xc8204e2000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820430b50, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820430b50, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820430af0, 0xc8204e2000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a230, 0xc8204e2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060b60)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 760 [IO wait]:
net.runtime_pollWait(0x7f39dde41a58, 0x72, 0xc820507000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205b2290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205b2290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205b2230, 0xc820507000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a220, 0xc820507000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820203930)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 552 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8202e8420)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 158 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f39dde00980, 0x72, 0xc8205ed000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204313a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204313a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820431340, 0xc8205ed000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a210, 0xc8205ed000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060340)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 517 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8202d40b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 520 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8202d4d10)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 620 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820202680)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 368 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820202340)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 524 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8202d4f20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 761 [select]:
net/http.(*persistConn).writeLoop(0xc820203930)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 660 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8202c4b00)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 466 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820060b60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 508 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc8202e80b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 619 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f39dde00a40, 0x72, 0xc8201d3000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202861b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202861b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820286150, 0xc8201d3000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201242b0, 0xc8201d3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820202680)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 640 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8202d42c0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1116 [select]:
net/http.(*persistConn).writeLoop(0xc8202b0ea0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 921 [IO wait]:
net.runtime_pollWait(0x7f39dde00080, 0x72, 0xc820408000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200da290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200da290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200da230, 0xc820408000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a290, 0xc820408000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8202b0750)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1425 [IO wait]:
net.runtime_pollWait(0x7f39dddfff00, 0x72, 0xc8204db000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204318e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204318e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820431880, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8201244e0, 0xc8204db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200c71e0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1538 [select]:
net/http.(*persistConn).writeLoop(0xc820202000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 922 [select]:
net/http.(*persistConn).writeLoop(0xc8202b0750)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1115 [IO wait]:
net.runtime_pollWait(0x7f39dde41c98, 0x72, 0xc820126000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820430300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820430300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204302a0, 0xc820126000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2d8, 0xc820126000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8202b0ea0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1521 [IO wait]:
net.runtime_pollWait(0x7f39dddffd80, 0x72, 0xc8202dc000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200da060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200da060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200da000, 0xc8202dc000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a020, 0xc8202dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820202000)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1631 [select]:
net/http.(*persistConn).writeLoop(0xc820060c30)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1346 [select]:
net/http.(*persistConn).writeLoop(0xc820060410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1329 [IO wait]:
net.runtime_pollWait(0x7f39dde00380, 0x72, 0xc82052d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200da990, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200da990, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200da930, 0xc82052d000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820124408, 0xc82052d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1442 [select]:
net/http.(*persistConn).writeLoop(0xc8200c71e0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1630 [IO wait]:
net.runtime_pollWait(0x7f39dddffe40, 0x72, 0xc820534000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200da840, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200da840, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200da7e0, 0xc820534000, 0x1000, 0x1000, 0x0, 0x7f39dde33050, 0xc820014200)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a338, 0xc820534000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060c30)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1712 [select]:
net/http.(*persistConn).roundTrip(0xc820060c30, 0xc820410970, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc820256300, 0xc820145500, 0xc820256300, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc820145500, 0x7f39dde37820, 0xc820256300, 0x0, 0xc800000000, 0x0, 0xc82043d720, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc8203ea8d0, 0xc820145500, 0x0, 0x0, 0x0, 0xc9ad37, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).Do(0xc8203ea8d0, 0xc820145500, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:193 +0x2b1

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-28 13:45
Duplicate of #5574.

**Closed by petermattis** 2016-03-28 13:45 UTC
Labels: Robot, test-failure
