### ISSUE TITLE
opt: Allow automatic stats to be run on a per table basis

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35497] opened 2019-03-07 15:30 UTC
**Is your feature request related to a problem? Please describe.**
Currently, automatic statistics apply to the entire cluster. 

Having a per table toggle may allow somebody to bulk load into a staging table quickly and then move data around to tables more slowly where statistics are applied.

Some tables may need automatic statistics--others may not. 

**Describe the solution you'd like**
Per table toggle to turn Automatic Statistics on or off.

**Comment by rytaft** [comment] 2021-06-08 15:24
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/40989.

**Closed by rytaft** 2021-06-08 15:24 UTC
Labels: A-sql-optimizer, C-enhancement, no-issue-activity
