### ISSUE TITLE
sql: CREATE MATERIALIZED VIEW does not use the right name resolution scope for its scalar expressions

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#53819] opened 2020-09-02 09:27 UTC
```
> create sequence s;
> create view a as select nextval('s'); -- OK!
> create materialized view am as select nextval('s');
ERROR: nextval(): relation "s" does not exist
SQLSTATE: 42P01
```

oops

(found while double checking #47267) 

----

@otan edit:

The fix for this is the same as the fix for https://github.com/cockroachdb/cockroach/issues/51090 -- we should rewrite the SQL clause of CREATE MATERIALIZED VIEW (and CREATE TABLE t AS) to use stable identifiers. See discussion in  #54410

**Comment by otan** [comment] 2020-09-15 16:59
Looks like `maybeBackfillMaterializedView` is initialised with CurrentDatabase == system.

**Comment by otan** [comment] 2020-09-15 17:01
This similar fails for

```
create table a as (select nextval('s'));
```

**Comment by otan** [comment] 2020-09-15 19:27
duplicate of #51090

**Comment by rafiss** [comment] 2020-09-15 23:03
I personally don't have all the context to make this call, but I notice that this issue is labelled as a release-blocker, but the linked issue this duplicates is not. Is #51090 supposed to be a release blocker?

**Comment by otan** [comment] 2020-09-15 23:34
My two cents is that I'm not sure this would count as a release blocker
considering its also a bug for CTAS. If it turns out to be a release
blocker then we should tag that issue as a release blocker.

**Comment by knz** [comment] 2020-09-16 11:31
I don't understand why this is marked as a duplicate of the other issue. 

The other issue is about creating things "not in the same database". But the example I pasted above contains no such thing! 

It seems to me this issue here is one of name resolution, not one of sequence ID stability. @otan can you give some more words about why you think this is a duplicate?

**Comment by otan** [comment] 2020-09-16 18:16
See the discussion of https://github.com/cockroachdb/cockroach/pull/54410 -- the proposed solution by the schema team is to have this also be re-written to use the stable schema id.

**Comment by knz** [comment] 2020-09-16 19:59
But until that solution is implemented, this issue has not been solved (and is not a duplicate)

Let's keep the issue open, and then when the PR that fixes both is issued it can "close" both issues.

**Comment by otan** [comment] 2020-09-17 01:11
Alright, but for reasons listed above, I'm going to unmark this as a release blocker since I don't see this as blocking most use cases + is an existing bug with CTAS. Unless there is a strong objection.

**Comment by otan** [comment] 2020-09-17 01:11
Alright, but for reasons listed above, I'm going to unmark this as a release blocker since I don't see this as blocking most use cases + is an existing bug with CTAS. Unless there is a strong objection.

**Comment by otan** [comment] 2020-09-17 01:14
cc @solongordon WDYT? ^

**Comment by awoods187** [comment] 2020-09-17 21:21
If its destabilizing and an existing problem then unfortunately I think we have to punt this to the next release.

**Comment by solongordon** [comment] 2020-09-17 22:09
+1 to not calling this a release blocker, thanks for the investigation.

**Comment by ajwerner** [comment] 2020-09-22 18:37
This isn't exactly the same as  #54410 though the proposed solution there would fix this. We could do something akin to what oliver was proposing but realistically this issue feels directly related to https://github.com/cockroachdb/cockroach/issues/42508. My thinking is that for release-20.2 we should disallow sequence operations inside of materialized views as they are totally busted.

**Comment by knz** [comment] 2020-09-22 20:47
No objection to a clean error. Yields more user clarity.

The error should reference this issue with unimplemented telemetry though.

**Closed** 2021-10-13 19:50 UTC
Labels: C-bug, A-sql-name-resolution, T-sql-schema
