### ISSUE TITLE
ui: decommissioned nodes have a strange UX

### ISSUE THREAD

**Issue by dianasaur323** [cockroachdb/cockroach#18478] opened 2017-09-13 15:40 UTC
I am running in the PM cluster. I decommissioned node 2 and we have a cron job that automatically starts up Cockroach again. The good thing is that I can no longer access cockroach sql in node 2. However, it still shows up as a live node, and is included in the capacity calculation. If a node has been successfully decommissioned, we should remove it from the count, even if it is still live.

![image](https://user-images.githubusercontent.com/5768024/30386615-48be4bb8-9878-11e7-8d9d-70fb2e408ef4.png)

**Comment by tschottdorf** [comment] 2017-09-13 15:44
If you decommission a node and that has finished, you should make it non-live and not doing so should be obvious. For that reason I don't think we want to hide the node there. We may want to add a cue to the fact that it is in decommissioning status though. That will be useful even as the node is decommissioning.

**Comment by dianasaur323** [comment] 2017-09-15 16:20
Ok, that's a good point that we should distinguish between dead / decommissioned and live / decommissioning. Perhaps this is as simple as a little warning that flags that the node is currently decommissioning, and it has to be "dead" to be considered decommissioned. We should address this in 1.2.

**Comment by couchand** [comment] 2017-09-18 18:23
Yes, this is something that tripped me up as I was reviewing the decommissioning PR as well.  There's no indication that decommissioning is in progress (probably because it would be a more major change?).  Restarting a decommissioned node without recommissioning it is definitely expected behavior at times, e.g. if the node didn't finish decommissioning.  It will be useful to think through how this will be displayed.  It might also be a good opportunity to think about how to allow decommissioning through the Admin UI if the user is logged in with sufficient privileges.

**Comment by tschottdorf** [comment] 2017-09-19 14:50
> There's no indication that decommissioning is in progress (probably because it would be a more major change?)

No, I expect that to be easy. The information is available now (for example, we hide dead & decommissioned nodes).

**Comment by tschottdorf** [comment] 2017-09-19 14:51
If you wanted a "progress bar" on how much the node is decommissioned, yes, that's harder. What you have is the number of remaining replicas on that node though, which is some indication of progress, though it's hard to map it to a percent scale.

**Comment by tschottdorf** [comment] 2017-09-19 14:53
Then again, just computing `1/(1+<number_of_remaining_replicas>)` can serve that purpose. Or any other transformation that has `f(infinity) = 0` and `f(0) = 1`.

**Comment by couchand** [comment] 2017-09-19 15:40
Yeah, adding some indication that the node is in the progress of decommissioning seems like it would be very useful.  I didn't mean that it would be hard (major was the wrong word), just that it would be harder than the changes that were made (filter out decommissioned nodes in most places), since it requires design updates.

**Comment by dianasaur323** [comment] 2017-09-25 13:15
Some feedback from a user: killed a node first, then decommissioned it. Would have wanted to observe that it was decommissioned, but saw it was dead, and has no way to remove the node. Not sure what the approach is yet for this feature, but wanted to mark down the feedback.

**Comment by couchand** [comment] 2017-09-25 15:30
There does seem to be a hitch here... I haven't tested it, but the docs describe something strange in the Admin UI: https://www.cockroachlabs.com/docs/v1.1/remove-nodes.html#step-2-mark-the-dead-node-as-decommissioned

> If the node is ever restarted, it will be listed as Live in the Admin UI, but the cluster will recognize it as decommissioned and will not rebalance any data to the node. If the node is then stopped again, a short time later, it will be listed as Decommissioned in the Admin UI

**Comment by dianasaur323** [comment] 2017-09-25 15:33
Basically, he accidentally killed the node, then decommissioned it. I'm assuming he did not put in the --wait=live flag. Either way, we should test this. His other annoying nit is that this ends up triggering the staggered version warning, since it's dead and not decommissioned.

**Comment by pmwebster** [comment] 2017-09-25 15:52
I'm the user @dianasaur323 was referring to. Just a clarification, I eventually got it to decommission properly as we're on GCE and I had the boot disk set to not delete. I just spun up a new VM, then re-added and properly removed it.

The gripe about the versions is that even when all nodes are decommissioned properly, I still get a staggered version warning. Please let me know if there's any other information I can provide to be useful.

**Comment by tschottdorf** [comment] 2017-09-25 18:08
@dianasaur323 we do test decommissioning a non-live node, hence my interest in understanding what exactly didn't go as planned.

@pmwebster the staggered version warning is [slated to be addressed in 1.2](https://github.com/cockroachdb/cockroach/issues/15534). Agreed that it's annoying!

Could you elaborate what the first (main) gripe here is? Killing the node and running `node decommission <id> --wait=live` should work (though you should always decommission the node while it's running, or the benefits of an explicit decommissioning step go away!), in that (after the store dead timeout, by default 5min) the UI shows the node as decommissioned. It probably still shows up in the "nodes" page (as indicated in the initial post in this thread, or did it go away if you left the node down for 5min, @dianasaur323?) so that needs to be fixed. But was there any other problem?

**Comment by pmwebster** [comment] 2017-09-25 18:23
We're running cockroach on an instance group in GCE, by default if a node dies there isn't a way to get the drive back and they're created with a unique ID upon instantiation. 

Given that, I killed the wrong node on accident and tried to decommission it after the fact and it didn't work. It might honestly be my fault for not using the wait=live flag, then killing the command and running it again with the flag added.

Either way, I found that the drive hadn't deleted yet so I recreated a machine with it and successfully added and decommissioned it properly.

**Comment by pmwebster** [comment] 2017-09-25 18:33
@tschottdorf It's probably worth noting the replacement node came back with the same IP. I'm not sure if that factors in to the equation.

**Comment by tschottdorf** [comment] 2017-09-25 18:49
@pmwebster thanks, but -- the bit I'm looking for is -- when the node was dead, what was it that didn't work as expected? It still showed up in the admin ui (and the staggered version warning)? Those two are what's tracked here so far, just making sure you didn't observe anything else that you thought wasn't right. There's no functional difference between `decommission` and `decommission --wait=live` expect that the former will hang forever if the target node is dead (but it will mark the node just the same first), so it didn't matter that you ran one instead of the other (except for poorer UX 😄)

**Comment by pmwebster** [comment] 2017-09-25 19:02
No matter what combination of decommission command flags were run, the node just stayed "dead", not decommissioned. Oddly enough it just happened again when I was playing around with a couple different alpha/beta versions. 

Joining from the same machine (same IP) as a different node in the CR cluster, then trying to decommission the old one that is marked "dead" just hangs indefinitely without every marking it decommissioned.

**Comment by pmwebster** [comment] 2017-09-25 19:04
fwiw -- when I say hang, I mean this is stuck in a loop and hasn't budged: 

`+----+---------+-------------------+--------------------+-------------+
| id | is_live | gossiped_replicas | is_decommissioning | is_draining |
+----+---------+-------------------+--------------------+-------------+
|  4 | false   |               349 | false              | true        |
+----+---------+-------------------+--------------------+-------------+`

**Comment by tschottdorf** [comment] 2017-09-25 19:51
Ah, now I see what you mean. Indeed one would hope that `is_decommissioning` gets marked as true, but [that's not correct](https://github.com/cockroachdb/cockroach/blob/f6463996176e3310dd8682baeceae8afbf161720/pkg/acceptance/decommission_test.go#L369-L375).

The node is still marked as decommissioning (essentially in a cluster-wide system table) but that information doesn't spread because it's the dead node which is usually in charge of this.

I filed https://github.com/cockroachdb/cockroach/issues/18749 for that. For this issue, let's limit to the fact that the UI doesn't properly hide decommissioning nodes (i.e. those for which the decommissioning status is correctly broadcast).

**Comment by tschottdorf** [comment] 2017-09-25 21:46
I just updated #18749 but wanted to ping this thread too for completeness:

@pmwebster we seem to test precisely that scenario already and the node should be marked as decommissioning. Are you sure you're running `cockroach node decommission --wait=live`? Also, can you check that it disappears from `./cockroach node ls`? It should.

**Comment by pmwebster** [comment] 2017-09-25 22:11
@tschottdorf 
Yes, I was running that command. The node ls lists all of the nodes, live, dead, and decommissioned.

**Comment by tschottdorf** [comment] 2017-09-28 20:36
Closing in favor of https://github.com/cockroachdb/cockroach/issues/18219.

**Closed by tschottdorf** 2017-09-28 20:36 UTC
