### ISSUE TITLE
circleci: failed tests: TestReplicateAddAndRemove 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7688] opened 2016-07-07 23:48 UTC
The following test appears to have failed:

[#20008](https://circleci.com/gh/cockroachdb/cockroach/20008):

```
W160707 23:44:55.310565 storage/replica.go:331  range 1: outgoing raft transport stream to {1 1 1} closed by the remote: rpc error: code = 13 desc = transport is closing
I160707 23:44:55.310769 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
I160707 23:44:55.311392 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
I160707 23:44:55.311930 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
I160707 23:44:55.312365 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
--- FAIL: TestReplicateAddAndRemove (15.53s)
	<autogenerated>:33: condition failed to evaluate within 15s: addFirst: true, expected [39 0 39 39], got [39 5 39 39]
=== RUN   TestRaftHeartbeats
I160707 23:44:55.333404 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
W160707 23:44:55.334546 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
W160707 23:44:55.342687 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
I160707 23:44:55.344674 storage/replica.go:2436  [node=1,store=1,range=1] gossiping cluster id {"00000000-0000-0000-0000-000000000000"} from store 1, range 1
I160707 23:44:55.346449 storage/replica.go:1850  applying command with forced error: storage/replica.go:1771: no-op on empty Raft entry
E160707 23:44:55.347617 storage/replica.go:1861  [node=1,store=1,range=1] error executing raft command: storage/replica.go:1771: no-op on empty Raft entry
I160707 23:44:55.348023 storage/replica_command.go:1596  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 900ms following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=1970-01-01 00:00:00 +0000 UTC]
I160707 23:44:55.349158 storage/replica.go:2445  [node=1,store=1,range=1] gossiping sentinel from store 1, range 1
--
=== RUN   Example_rebalancing
W160707 23:45:46.058759 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
I160707 23:45:46.649534 stopper.go:355  draining; tasks left:
19     gossip/infostore.go:288
--- PASS: Example_rebalancing (0.59s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	83.333s
=== RUN   TestBatchBasics
I160707 23:45:54.849012 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
I160707 23:45:54.852675 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160707 23:45:54.861433 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
I160707 23:45:54.863007 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.01s)
=== RUN   TestBatchGet
I160707 23:45:54.868456 storage/engine/rocksdb.go:289  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-07-10 15:36
Duplicate of #7565.

**Closed by petermattis** 2016-07-10 15:36 UTC
Labels: Robot, test-failure
