### ISSUE TITLE
distsql/storage: OOM while looping TPC-H query 1 on 6-node cluster

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#14898] opened 2017-04-13 16:16 UTC
build: e9a94ab
config: 6-node Azure Standard_D3 cluster, no env variables except for memprof & lightstep
load: `tpch -queries 1 -concurrency 3 -loops 0`

last runtime stats:
```
I170413 06:58:18.486346 22 server/status/runtime.go:227  [n1] runtime stats: 13 GiB RSS, 190 goroutines, 8.3 GiB/1.6 GiB
/10 GiB GO alloc/idle/total, 2.0 GiB/2.6 GiB CGO alloc/total, 484973.87cgo/sec, 2.69/0.30 %(u/s)time, 0.00 %gc (1x)
```

Logs from node with OOM (note that the logs include a manual restart I did):
[cockroach.stderr.txt](https://github.com/cockroachdb/cockroach/files/920204/cockroach.stderr.txt)

memprof profile just before OOM kill:
[profile001.pdf](https://github.com/cockroachdb/cockroach/files/920214/profile001.pdf)

**Comment by cuongdo** [comment] 2017-04-13 16:16
@radu reassign if you see the need. also let me know if you need more info

**Comment by cuongdo** [comment] 2017-04-13 16:21
Also, I'm not sure if this has any relationship to #14776 

@danhhz do you see anything familiar in [the memprof profile](https://github.com/cockroachdb/cockroach/files/920214/profile001.pdf)?

**Comment by RaduBerinde** [comment] 2017-04-13 16:33
The profile shows all that usage coming from `engine.MVCCIterate`. I am not sure if `EncDatum`s stored in distsql can hold references to memory allocated in there.

What is the query that is being run?

**Comment by danhhz** [comment] 2017-04-13 16:47
Nothing looks familiar in the profile, but as long as #14776 is unresolved, it's probably a good idea to bounce the cluster after RESTORE as there's almost certainly a memory leak causing it

**Comment by cuongdo** [comment] 2017-04-13 16:59
@danhhz I did bounce after RESTORE to turn off prop eval KV.

@RaduBerinde the query is [from here](https://github.com/cockroachdb/loadgen/blob/master/tpch/query1.go):

```
SELECT
	l_returnflag,
	l_linestatus,
	SUM(l_quantity) AS sum_qty,
	SUM(l_extendedprice) AS sum_base_price,
	SUM(l_extendedprice * (1 - l_discount)) AS sum_disc_price,
	SUM(l_extendedprice * (1 - l_discount) * (1 + l_tax)) AS sum_charge,
	AVG(l_quantity) AS avg_qty,
	AVG(l_extendedprice) AS avg_price,
	AVG(l_discount) AS avg_disc,
	COUNT(*) AS count_order
FROM
	lineitem
WHERE
	l_shipdate <= DATE '1998-12-01' - INTERVAL '95' DAY
GROUP BY
	l_returnflag,
	l_linestatus
ORDER BY
	l_returnflag,
	l_linestatus;
```
Schema is:
```
```


This table has ~30 million rows, and

**Comment by danhhz** [comment] 2017-04-13 17:23
Gotcha. Then I would guess this isn't related to RESTORE

**Comment by RaduBerinde** [comment] 2017-04-13 17:49
I don't think any `EncDatums` would be stored directly inside distsql for that query. Anything we store would be the result of a SUM or COUNT which would be a new datum. So I don't think distsql can be holding on to memory from `MVCCIterate`

**Comment by RaduBerinde** [comment] 2017-04-13 17:50
@cuongdo it would be useful to see if it can be reproduced with distsql off to rule that out as a culprit.

**Comment by cuongdo** [comment] 2017-04-13 17:50
Sure, I'll try that now

**Comment by cuongdo** [comment] 2017-04-13 18:34
The query takes approximately 5x as long without distsql, so it might take a really long time to repro this with distsql off.

**Comment by RaduBerinde** [comment] 2017-04-13 19:51
I'm a bit surprised it's that much faster because looking at the query, it seems like it would require an index join, and we don't distribute that (we use a single index-joiner, and from that point on all aggregation happens on one node).

**Comment by petermattis** [comment] 2017-05-03 20:22
Is this still being investigated?

**Comment by arjunravinarayan** [comment] 2017-05-03 20:39
I will investigate this, thanks for the heads up.

**Comment by arjunravinarayan** [comment] 2017-05-03 21:11
@cuongdo what scalefactor did you use for this? I'm going to try and repro this with the scalefactor=10 dataset, since I'm loading that up in cluster `navy` to repro #15194 anyway. It's unlikely you used anything bigger, but pinging you just in case.

**Comment by cuongdo** [comment] 2017-05-03 21:14
Scale factor 10. That's the largest I've generated.

**Comment by arjunravinarayan** [comment] 2017-05-04 17:19
`tpch -queries 1 -concurrency 3 -loops 0` has been running on cluster denim on `rc2` for hours now, with no memory leak. Query execution is predictably slow (~8 minutes per query) on scalefactor=10, but no OOMs. All queries complete successfully. Closing this issue.

**Closed by arjunravinarayan** 2017-05-04 17:19 UTC
