### ISSUE TITLE
cannot use go mod

### ISSUE THREAD

**Issue by nnsgmsone** [cockroachdb/cockroach#47246] opened 2020-04-09 03:04 UTC
**Describe the problem**

I want to use go mod to refer to cockroach, but it failed. The error message is 

> "go/pkg/mod/github.com/cockroachdb/cockroach@v19.2.5+incompatible/pkg/util/tracing/shadow.go:48:12: undefined: zipkintracer.Collector"

**To Reproduce**

I tried to quote the cockroach package, this is part of my go mod file:

> replace (
>     github.com/cockroachdb/apd => github.com/cockroachdb/apd/v2 v2.0.2-0.20190505045354-5843f9b6a583
>     go.etcd.io/etcd => go.etcd.io/etcd v0.5.0-alpha.5.0.20191113212143-63dd73c1869f
> )
>

**Comment by bobvawter** [comment] 2020-04-13 14:10
Duplicate of #38824

**Closed by bobvawter** 2020-04-13 14:10 UTC
Labels: C-investigation

**Comment by charlesvdv** [comment] 2020-09-26 12:32
I also stumbled on this issue when trying to import `github.com/cockroachdb/cockroach/pkg/sql/parser`. For future reference, here is the fix: 

Add in your `go.mod`:
```
replace github.com/openzipkin-contrib/zipkin-go-opentracing => github.com/openzipkin-contrib/zipkin-go-opentracing v0.3.5
```
The problem comes from the fact that `zipkin-go-opentracing` has broken backward compatibility somewhere between v0.3.5 and v0.4.5 and for some reason (not a go module expert), the go module system is taking the v0.4.5 when cockroach uses the v0.3.5.
