### ISSUE TITLE
storage: experiment with priority mechanism to avoid starvation while maximizing throughput and fairness

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#5727] opened 2016-03-30 18:44 UTC
We might want to replace the notion of priority used to schedule transaction with
a combination of  1. start-timestamp and 2. user defined priority. These two variables 
better describe what a user cares about. 1. Preventing starvation and 2.
Getting the more important work done first. We already have the notion of user defined priority.
With this model when a transaction gets pushed, its start time keeps moving
back from the current time and that should allows cockroach to schedule it before other
fresher transactions.

via @tschottdorf in #5710:

> Separately, if transactions A at priority 1 and B at priority 2^16 both lose against
> priority 2^25, it does not seem fair that both should end up at priority
> 2^25-1. Instead, it would seem more reasonable that their priority be increased
> as a fraction of the difference, for instance bumping A by (2^25-1)/2 and B by
> (2^25-2^16)/2, which preserves the relative ordering of A and B but still lets
> them approach the priority of their mutual enemy.

**Comment by tschottdorf** [comment] 2016-03-30 18:49
Thanks @vivekmenezes. I took the liberty to edit your comment slightly (removing the issue template and referring to the PR).

**Comment by spencerkimball** [comment] 2016-04-04 18:25
Happy to consider changing the scheme, but before we do anything, we need to develop a framework with which to evaluate latency and throughput distributions in the face of various competing transaction scenarios. I'm going to change the issue title as current title advocates for something which is not an explicit goal. The goal should be something along the lines of "Experiment with priority mechanism to avoid starvation while maximizing throughput and fairness"

**Comment by mrtracy** [comment] 2016-04-05 20:04
The alternative I am personally most interested in experimenting with is the use of "earliest original timestamp", instead of priority.

Why I believe it *might* be better: 
+ It basically prevents pathological starvation entirely, putting a cap on the number of times a transaction can be restarted (equal to the number of uncommitted earlier transactions).  On servers with relatively constant workload, this should allow long-running transactions to make progress more quickly, with less wasted work.
+ I also believe it to be somewhat simpler to reason about. There are no priority re-calculations or randomness involved.

Why it could be deficient:
+ The priority system was designed for applications with "bursty", uneven workload. It allows the occasional long-running transaction to fall into the dips in the uneven workflow, without needing to block short-running transactions during the peaks.
+ The priority system also provides an extra check on Abandoned transactions; aside from heartbeat, abandoned transactions can be probabilistically aborted by later transactions with higher priority; with "earliest timestamp", that's not the case.
+ Due to clock skew, transactions running through gateways with slower clocks might get an unfair advantage, and might result in the cluster's "retry load" being distributed unevenly.

**Comment by spencerkimball** [comment] 2017-03-29 16:56
We now use something much closer to "earliest timestamp wins" with the push txn queues. Closing this due to #13501.

**Closed by spencerkimball** 2017-03-29 16:56 UTC
