### ISSUE TITLE
Query planner issue? v2.1.0-beta.20181015

### ISSUE THREAD

**Issue by tephrocactus** [cockroachdb/cockroach#31629] opened 2018-10-19 14:04 UTC
We're currently investigating the possibility to migrate our project from MySQL 5.7 to CockroachDB.
The migration process is quite smooth, but we notice strange behaviour of query planner in some cases like this:

**Tables involved**

```
CREATE TABLE contracts (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	...
	INDEX load_place_id (load_place_id ASC),
	INDEX delivery_place_id (deliver_place_id ASC),
);

CREATE TABLE places (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	name STRING NOT NULL DEFAULT '':::STRING,
	code STRING NOT NULL DEFAULT '':::STRING,
	city STRING NOT NULL DEFAULT '':::STRING,
	region STRING NOT NULL DEFAULT '':::STRING,
	country STRING NOT NULL,
	type_id INT NOT NULL DEFAULT 0:::INT,
	lat FLOAT8 NULL DEFAULT 0.0:::FLOAT8,
	lng FLOAT8 NULL DEFAULT 0.0:::FLOAT8,
	area STRING NOT NULL DEFAULT '':::STRING,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	UNIQUE INDEX name (name ASC, code ASC, region ASC, country ASC, type_id ASC)
    ...
)

CREATE TABLE invoices_contracts (
	id UUID NOT NULL DEFAULT gen_random_uuid(),
	invoice_id UUID NOT NULL,
	contract_id UUID NOT NULL,
	cost FLOAT8 NOT NULL,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	UNIQUE INDEX contract_id (contract_id ASC),
	...
)
```

**Query**

```
select
	"contracts"."id",
	"load_place_id_places"."id" as "load_place_id_places_id",
	"load_place_id_places"."type_id" as "load_place_id_places_type_id",
	"load_place_id_places"."name" as "load_place_id_places_name",
	"load_place_id_places"."city" as "load_place_id_places_city",
	"load_place_id_places"."region" as "load_place_id_places_region",
	"load_place_id_places"."area" as "load_place_id_places_area",
	"load_place_id_places"."country" as "load_place_id_places_country",
	"load_place_id_places"."lng" as "load_place_id_places_lng",
	"load_place_id_places"."lat" as "load_place_id_places_lat",
	"deliver_place_id_places"."id" as "deliver_place_id_places_id",
	"deliver_place_id_places"."type_id" as "deliver_place_id_places_type_id",
	"deliver_place_id_places"."name" as "deliver_place_id_places_name",
	"deliver_place_id_places"."city" as "deliver_place_id_places_city",
	"deliver_place_id_places"."region" as "deliver_place_id_places_region",
	"deliver_place_id_places"."area" as "deliver_place_id_places_area",
	"deliver_place_id_places"."country" as "deliver_place_id_places_country",
	"deliver_place_id_places"."lng" as "deliver_place_id_places_lng",
	"deliver_place_id_places"."lat" as "deliver_place_id_places_lat"
from
	"contracts" as "contracts"
join "invoices_contracts" on
	(invoices_contracts.invoice_id = '2b72c544-20a7-4ca1-9147-671b0a4df6e9')
join "places" as "load_place_id_places" on
	(load_place_id_places.id = contracts.load_place_id)
join "places" as "deliver_place_id_places" on
	(deliver_place_id_places.id = contracts.deliver_place_id)
order by
	"contracts"."created_on" desc
limit 32;
```

**DB content**

Tables _contracts_ and _invoices_contracts_ have only **one** row each.
Table _places_ has 337k rows.

**Observations**

The original query execution takes about 3 seconds;
Explain output:

```
                 tree                |  field   |        description          
+------------------------------------+----------+----------------------------+
  render                             |          |                             
   └── limit                         |          |                             
        └── sort                     |          |                             
             │                       | order    | -created_on                 
             └── join                |          |                             
                  │                  | type     | inner                       
                  │                  | equality | (deliver_place_id) = (id)   
                  ├── join           |          |                             
                  │    │             | type     | inner                       
                  │    │             | equality | (load_place_id) = (id)      
                  │    ├── join      |          |                             
                  │    │    │        | type     | cross                       
                  │    │    ├── scan |          |                             
                  │    │    │        | table    | contracts@primary           
                  │    │    │        | spans    | ALL                         
                  │    │    └── scan |          |                             
                  │    │             | table    | invoices_contracts@primary  
                  │    │             | spans    | ALL                         
                  │    └── scan      |          |                             
                  │                  | table    | places@primary              
                  │                  | spans    | ALL                         
                  └── scan           |          |                             
                                     | table    | places@primary              
                                     | spans    | ALL
```

If I add ``` where contracts.status = 1 ``` or ``` where contracts.status IN (1,2) ``` the execution time drops to a few milliseconds and I get one row, as expected. The query planner switches to lookup joins.

```
                 tree                | field |        description          
+------------------------------------+-------+----------------------------+
  render                             |       |                             
   └── limit                         |       |                             
        └── sort                     |       |                             
             │                       | order | -created_on                 
             └── lookup-join         |       |                             
                  │                  | type  | inner                       
                  ├── lookup-join    |       |                             
                  │    │             | type  | inner                       
                  │    ├── join      |       |                             
                  │    │    │        | type  | cross                       
                  │    │    ├── scan |       |                             
                  │    │    │        | table | contracts@primary           
                  │    │    │        | spans | ALL                         
                  │    │    └── scan |       |                             
                  │    │             | table | invoices_contracts@primary  
                  │    │             | spans | ALL                         
                  │    └── scan      |       |                             
                  │                  | table | places@primary              
                  └── scan           |       |                             
                                     | table | places@primary     
```

But if I add third argument to IN ... ```where contracts.status IN (1,2,3)``` ... query planner switches back to hash joins and execution time raises to 2.8 - 3.0 seconds again. The same latency if table _contracts_ is empty and query returns zero rows.

**Cluster status**

Cluster seems to be healthy. All 3 nodes alive and of the same version. No problem ranges, no capacity or memory limits reached. The vast majority of our queries runs fine.

**Environment**

CockroachDB version: ```v2.1.0-beta.20181015```
OS: ```Darwin tephros-MBP 17.6.0 Darwin Kernel Version 17.6.0```
Cluster: ```3 nodes with default configuration on a single machine```
Hardware: ```4 core i5, 8g RAM, SSD. No other services are active on the machine```

So, am I doing something wrong or this is the issue you, guys, already aware of?
Thank you!

**Comment by tephrocactus** [comment] 2018-10-19 14:58
One more observation. If I ask db to return a minimal column set, execution time drops from 3s to 700ms avg. The length of values in string columns of _places_ table never exceed 32 chars.

```
select
	"contracts"."id",
	"load_place_id_places"."id" as "load_place_id_places_id",
	"deliver_place_id_places"."id" as "deliver_place_id_places_id"
from
	"contracts" as "contracts"
join "invoices_contracts" on
	(invoices_contracts.invoice_id = '2b72c544-20a7-4ca1-9147-671b0a4df6e9')
join "places" as "load_place_id_places" on
	(load_place_id_places.id = contracts.load_place_id)
join "places" as "deliver_place_id_places" on
	(deliver_place_id_places.id = contracts.deliver_place_id)
order by
	"contracts"."created_on" desc
limit 32;
```

**Comment by andy-kimball** [comment] 2018-10-19 16:32
The problem is that the optimizer does not know that "contracts" and "invoices_contracts" have only 1 row each. It assumes there can be more than 1 row in each table. And once the estimated number of rows returned by the joins gets big enough, it switches to hash join from lookup join, since lookup join can get very slow if there are a larger number of rows. So you're just observing the "crossover point" for this particular query, where it concludes that a lookup join would have too many input rows.

There are a few ways to give the optimizer the knowledge that you only have 1 row in those two tables:

1. Create statistics for those two tables:
```
CREATE STATISTICS contracts_stats ON id FROM contracts;
CREATE STATISTICS invoices_contracts_stats ON id FROM invoices_contracts;
```
The optimizer doesn't yet make heavy use of statistics (it will use them much more in the future), but it does use the row counts to make better cardinality estimates.

2. If you're certain that the filtered number of rows from the contracts and invoices_contracts tables can never exceed 1, then you can tweak your query to give that information to the optimizer:
```
select
	"contracts"."id",
	"load_place_id_places"."id" as "load_place_id_places_id",
	"load_place_id_places"."type_id" as "load_place_id_places_type_id",
	"load_place_id_places"."name" as "load_place_id_places_name",
	"load_place_id_places"."city" as "load_place_id_places_city",
	"load_place_id_places"."region" as "load_place_id_places_region",
	"load_place_id_places"."area" as "load_place_id_places_area",
	"load_place_id_places"."country" as "load_place_id_places_country",
	"load_place_id_places"."lng" as "load_place_id_places_lng",
	"load_place_id_places"."lat" as "load_place_id_places_lat",
	"deliver_place_id_places"."id" as "deliver_place_id_places_id",
	"deliver_place_id_places"."type_id" as "deliver_place_id_places_type_id",
	"deliver_place_id_places"."name" as "deliver_place_id_places_name",
	"deliver_place_id_places"."city" as "deliver_place_id_places_city",
	"deliver_place_id_places"."region" as "deliver_place_id_places_region",
	"deliver_place_id_places"."area" as "deliver_place_id_places_area",
	"deliver_place_id_places"."country" as "deliver_place_id_places_country",
	"deliver_place_id_places"."lng" as "deliver_place_id_places_lng",
	"deliver_place_id_places"."lat" as "deliver_place_id_places_lat"
from (
	select * from "contracts" where contracts.status IN (1,2,3) limit 1
) as "contracts"
join (
	select *
	from "invoices_contracts"
	where invoices_contracts.invoice_id = '2b72c544-20a7-4ca1-9147-671b0a4df6e9'
	limit 1
) as "invoices_contracts" on true
join "places" as "load_place_id_places" on
	(load_place_id_places.id = contracts.load_place_id)
join "places" as "deliver_place_id_places" on
	(deliver_place_id_places.id = contracts.deliver_place_id)
order by
	"contracts"."created_on" desc
limit 32;
```

In the future, this kind of manual stats gathering/query rewrite won't be necessary, once we add automatic stats. But for now, you have to help the optimizer along from time to time.

**Comment by tephrocactus** [comment] 2018-10-19 16:44
Thanks for the explanation. Will stick to statistics approach for now.

**Comment by tephrocactus** [comment] 2018-10-19 17:02
Yes, it solved the problem, including in real queries.

**Comment by andy-kimball** [comment] 2018-10-19 17:17
Great to hear. I'll close this down as resolved.

**Closed by andy-kimball** 2018-10-19 17:17 UTC
Labels: A-sql-planning, C-investigation
