### ISSUE TITLE
sql: move schema change lease to schema change job.

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#34211] opened 2019-01-24 02:19 UTC
The schema change lease is stored in the table descriptor. What this means is when it gets updated every 2-3 minutes, the system config span gets gossiped. The schema change lease is also modifying the descriptor without changing the Version on the descriptor. It is best that it be moved to the schema change job.

**Comment by andreimatei** [comment] 2019-01-24 20:00
Worse than the thing getting gossipped, the range can grow too large at which point the cluster is completely stuck.
Besides moving the lease away, I think we should also make sure that taking and releasing this lease doesn't leave old MVCC versions around, and also we probably should be taking it and releasing it in a loop like it happened in #34082.
And also more generally I think we need to be more judicious around schema change retry. I don't think it's a sane policy to just retry things endlessly like we apparently do. I'm thinking we should find ways of getting an operator into the loop when things go awry.

**Comment by andreimatei** [comment] 2019-01-24 20:02
FWIW, this is the descriptor with the flipping lease. I thought I linked it from #34211, but it looks like I forgot:
https://gist.github.com/andreimatei/11566c4ed239dd6ce01cae8e550ddf12

**Comment by andreimatei** [comment] 2019-05-20 18:57
@dt I believe this issue is a biggie. This came up again recently; we've gotten multiple reports for 19.1 about writes to system config ranges being backpressured because the range is too large - at which point the cluster is pretty hosed.
We haven't figured out exactly how the system config range gets that big, but the suspicion is on schema changes - either one that runs for a long time, or one that keeps retrying, which according to what I was saying in #34082 seems to result in this schema change lease being taken over and over.

cc @nvanbenschoten

**Comment by dt** [comment] 2019-06-06 18:14
@andreimatei do you have any idea which schema change might be at fault here? They're supposed to renew their leases ever 2.5min so with a 25h TTL I'd expect no more than 600 MVCC revisions of a given desc, but I heard someone say we're seeing thousands _per minute_ so something seems off.

**Comment by andreimatei** [comment] 2019-06-06 21:26
I have to dig through the logs, which I'll do hopefully later today (I'll send you a link to them). The last time when we saw this, it was about a schema change retrying endlessly.

**Comment by andreimatei** [comment] 2019-06-07 00:50
The latest incarnation of this has #38088 as the cause for the schema change retries.

**Comment by lucy-zhang** [comment] 2020-04-30 21:35
Closing since schema change leases (i.e. `TableDescriptor.Lease`) don't exist anymore.

**Closed by lucy-zhang** 2020-04-30 21:35 UTC
Labels: A-schema-descriptors, C-enhancement, S-1-stability
