### ISSUE TITLE
backupccl, schedules: Broken (or confusing) scheduled table backup behavior.

### ISSUE THREAD

**Issue by miretskiy** [cockroachdb/cockroach#69865] opened 2021-09-07 16:06 UTC
It appears that scheduled table backups do not work unless the table names are fully qualified.
Consider for example:
```
sql> use defaultdb;
sql> CREATE TABLE foo (...);
sql> CREATE SCHEDULE FOR BACKUP TABLE foo INTO '....' RECURRING '@hourly'
```

You would get the schedule that looks like this:
```
sql> SHOW SCHEDULES FOR BACKUP;
  691125546476503041 | BACKUP 1630985178 | ACTIVE          | 2021-09-07 17:00:00+00 | reschedule: failed to create job for schedule 691125546476503041: err=executing schedule 691125546476503041: failed to resolve targets specified in the BACKUP stmt: table "foo" does not exist, or invalid RESTORE timestamp: supplied backups do not cover requested time | @hourly    |           0 | root  | 2021-09-07 03:26:18.456696+00 | BACKUP TABLE foo INTO 'nodelocal://0/db.foo' WITH detached
```

Note that in the above schedule table `foo` was left unqualified;  The schedule was created -- the "dry run backup" performed all of the necessary validations -- and table `foo` does indeed exists in the `defaultdb` -- the database I was connected to when I executed `create schedule`.

But of course, the schedule itself doesn't work and fails to backup as seen in the error message above.
https://github.com/cockroachdb/cockroach/pull/69863 adds a small test demonstrating the above behavior.

To make matters more confusing
```
sql> USE system;
sql> CREATE SCHEDULE FOR BACKUP TABLE jobs INTO .... RECURRING '@hourly'
```

The above schedule backing up `jobs` table from `system` database seems to work fine -- I guess because "system" is special.

I think this behavior is broken -- or at the very least very confusing.
Either schedule planning should return an error if the tables are not fully qualified, or it should fully qualify table names
when creating backup schedule.

**Comment by dt** [comment] 2021-09-07 22:17
Duplicate of #66450

**Closed by dt** 2021-09-07 22:17 UTC
Labels: C-bug, A-bulkio, T-bulkio
