### ISSUE TITLE
gossip: Liveness not gossiped after single node restarts

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#27731] opened 2018-07-18 21:52 UTC
In a nine-node cluster running on GCE (which contained node IDs higher than 9 due to past decommissions), the following sequence of events occurred:

1. Node 12 was restarted (to upgrade from 2.0.3 to 2.0.4)
1. Gossip-based metrics (live nodes, underreplicated ranges) started to indicate problems. It's unclear whether there were any real problems. The web UI showed 3x as many ranges as there should be, 2/3 of which were "underreplicated', and most nodes showed 6 of the 9 nodes as being down.
1. Node 12 was restarted again, to revert to 2.0.3. Nothing really changed; the gossip metric problems remained the same
1. Node 4 was restarted (on a hunch because this node had been linked to another superficially-similar incident). This triggered something that brought everything back to normal, about an hour after the first restart.

This appears to be a gossip problem. By the `liveness.livenodes` metric, we can see that three nodes (12, 4, and 9) saw all 9 nodes as alive. The other six nodes only considered one node (themselves) to be alive most of the time, although this number fluctuated a bit.

![image](https://user-images.githubusercontent.com/160562/42909134-05ab241e-8ab1-11e8-97cd-63d98068c13e.png)

The KV portions of NodeLiveness were working correctly, as shown by the nodes that believed all 9 nodes were alive and confirmed by the `liveness.heartbeatsuccesses` metric. Only the gossip portion was (mostly) missing.

Complete information from the outage is not available, but the gossip graph shows no abnormalities while the cluster is healthy (for example, there are no single points of failure that could partition the graph). The image in #27652 is taken from this cluster after the outage.

At the time of the outage, the cluster was experiencing unusual clock offsets on several nodes (4, 5, and 12). The clock offset graph shows a sawtooth pattern with offsets on these nodes steadily increasing to about 200ms, then snapping back to 0.  This pattern occurred for roughly the 24 hour period surrounding the outage but had not been seen before or since. It is suspected that this is due to a widely-reported GCP outage on the same day.

Gossip relies on the monotonicity of the system clock (with an in-process ratchet). If the clock jumps backwards while the process is being restarted, some messages could get dropped (for a duration after startup equal to the clock jump). This would include the startup gossip messages in which a new node announces its presence. However, the liveness messages are re-gossiped every ~5s, so as far as I can tell the system should recover from any dropped messages within a few seconds.

**Comment by a-robinson** [comment] 2018-07-18 22:39
Huh, that's an interesting one. I don't assume a `debug zip` was taken during the outage or that the gossip values from that time were otherwise recorded?

Which nodes were r1's and the node liveness range's replicas on?

This tickles some memories of old issues, most notably https://github.com/cockroachdb/cockroach/issues/24753 and https://github.com/cockroachdb/cockroach/issues/24023. We believe we fixed https://github.com/cockroachdb/cockroach/issues/24753. We never truly tracked down https://github.com/cockroachdb/cockroach/issues/24023, although it looks like it could reasonably be explained by the same root cause. We only cherry-picked one of the two parts of the fix to release-2.0 (https://github.com/cockroachdb/cockroach/pull/25521, but not https://github.com/cockroachdb/cockroach/pull/25322). There's a decent chance this is related.

**Comment by grempe** [comment] 2018-07-18 22:49
Just to clarify:

> Gossip-based metrics (live nodes, underreplicated ranges) started to indicate problems. It's unclear whether there were any real problems. 

There were real problems with data. We were unable to write records and query some data during this period. It resulted in user-visible issues.

**Comment by bdarnell** [comment] 2018-07-18 22:49
The cluster uses a replication factor of 5. r1 has replicas on n4, n6, n9, n10, and n11. The liveness range is on n4, n8, n9, n10, and n12 (there has not been any movement of these ranges since april!). So the thing about n4 that caused it to wake the cluster back up could have been either r1 or liveness. 

Yes, #24753 was my first thought as well. As expected (since #25322 was not backported), we do see ping-ponging of the r1 lease (even while the cluster is healthy)

**Comment by m-schneider** [comment] 2018-08-06 14:48
Adding combined logs:

https://drive.google.com/open?id=15xXH0z2kWXbZvxyJMCJSGNLFOu0SyNGA

It looks like after the restart we see a lot of errors of the form:

```
message":"grpc: addrConn.createTransport failed to connect to { 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: missing address\". Reconnecting...
```
However we don't see any at all on node 4, node 6 and node 9.

**Comment by petermattis** [comment] 2018-08-21 18:09
> `message":"grpc: addrConn.createTransport failed to connect to { 0  <nil>}. Err :connection error: desc = \"transport: Error while dialing dial tcp: missing address\". Reconnecting...`

Why are we trying to open connections without a valid address?

**Comment by petermattis** [comment] 2018-08-21 18:17
> It looks like after the restart we see a lot of errors of the form:

You're not kidding! There are thousands of these errors. We should track down what is causing this error. So strange to not have an address here.

**Comment by a-robinson** [comment] 2018-08-21 18:17
> Why are we trying to open connections without a valid address?

Without having dug in yet, presumably because the node descriptors for the desired node weren't in gossip (because of the gossip partion), and we were blindly using an empty result from the gossip method that's used to look up node addresses given their IDs.

**Comment by petermattis** [comment] 2018-08-21 18:44
> Without having dug in yet, presumably because the node descriptors for the desired node weren't in gossip (because of the gossip partion), and we were blindly using an empty result from the gossip method that's used to look up node addresses given their IDs.

Node descriptors have a TTL of 2h. So even when a node goes down, the previously present node descriptor will remain in gossip. The timings around this outage are that a node was taken down and brought up a few minutes later. So perhaps you're correct that there is a gossip problem with the node descriptor, but the question is why is it the address field empty.

**Comment by petermattis** [comment] 2018-08-21 18:54
Early when node 12 restarts it outputs a message say it set its node descriptor which does contain a non-empty address field. This corresponds to the log message in `Gossip.SetNodeDescriptor`.

**Comment by petermattis** [comment] 2018-08-21 19:51
This code looks very suspicious:

```
	if ok && oldNodeID != unknownNodeID && oldNodeID != desc.NodeID {
		log.Infof(ctx, "removing node %d which was at same address (%s) as new node %v",
			oldNodeID, desc.Address, desc)
		g.removeNodeDescriptorLocked(oldNodeID)

		// Deleting the local copy isn't enough to remove the node from the gossip
		// network. We also have to clear it out in the infoStore by overwriting
		// it with an empty descriptor, which can be represented as just an empty
		// byte array due to how protocol buffers are serialized.
		// Calling addInfoLocked here is somewhat recursive since
		// updateNodeAddress is typically called in response to the infoStore
		// being updated but won't lead to deadlock because it's called
		// asynchronously.
		key := MakeNodeIDKey(oldNodeID)
		var emptyProto []byte
		if err := g.addInfoLocked(key, emptyProto, NodeDescriptorTTL); err != nil {
			log.Errorf(ctx, "failed to empty node descriptor for node %d: %s", oldNodeID, err)
		}
	}
```

The above provides an explanation for how we could gossip a node descriptor without an address.

**Comment by petermattis** [comment] 2018-08-21 20:15
Unfortunately, the `was at same address` error is not present in the logs.

Something else that is interesting. When `n12` restarts it creates a gossip client connection to `n4`. That was the node that was eventually restarted which then "fixed" everything. Restarting `n4` forced `n12` to connect to a different node.

**Comment by petermattis** [comment] 2018-08-21 20:32
Before the outage (at `00:00:03`), the gossip connectivity graph looks like:

![screen shot 2018-08-21 at 4 27 21 pm](https://user-images.githubusercontent.com/6201335/44427342-4bfabd80-a55f-11e8-9c0c-26f895c10cac.png)

After node 12 is killed and restarted at `04:53:49`, the connectivity graph looks like:

![screen shot 2018-08-21 at 4 24 40 pm](https://user-images.githubusercontent.com/6201335/44427385-67fe5f00-a55f-11e8-8472-c77d0fe31e74.png)

At `05:18:12`, the graph looks like:

![screen shot 2018-08-21 at 4 31 48 pm](https://user-images.githubusercontent.com/6201335/44427508-c75c6f00-a55f-11e8-8557-2e0d08650357.png)

So one of the partitions healed, but the other did not.

**Comment by petermattis** [comment] 2018-08-21 20:55
The mechanism for gossip to create new connections is the lack of the "sentinel" key which is gossiped by the leaseholder for range 1. This key has a TTL of 2min and the key is gossiped every 2min. 

The logs I have do not indicate which node holds the lease for range 1. Disturbingly, I do see this message (after the cluster has recovered): `[n10,s10,r1/7:/{Min-System/}] could not gossip first range descriptor: [NotLeaseHolderError] r1: replica (n10,s10):7 not lease holder; lease holder unknown`

So `n10` has a replica of range 1 and it doesn't know who the lease holder is. Range 1 has an expiration based lease so it should have a lease holder as long as there is activity on the range. And the mechanism to periodically gossip the sentinel should be forcing the lease to be acquired. Perhaps that mechanism isn't working correctly.

**Comment by tschottdorf** [comment] 2018-08-21 20:59
@petermattis this message rings a bell from my investigation here: https://github.com/cockroachdb/cockroach/issues/28179#issuecomment-411005719

My proximate assumption was that the node might have a stale replica of the first range and the lease acquisition would get stuck on it until GC, which perhaps wouldn't happen for quite a while. I think to remember that there was a distinct lack of evidence for this scenario in the logs though. Curious what you'll find here.

**Comment by a-robinson** [comment] 2018-08-21 21:01
> So n10 has a replica of range 1 and it doesn't know who the lease holder is. Range 1 has an expiration based lease so it should have a lease holder as long as there is activity on the range. And the mechanism to periodically gossip the sentinel should be forcing the lease to be acquired. Perhaps that mechanism isn't working correctly.

In case it's slipped your mind, please remember the prior art from https://github.com/cockroachdb/cockroach/issues/24753 which we thought we fixed with https://github.com/cockroachdb/cockroach/pull/25214 (in 2.0) and https://github.com/cockroachdb/cockroach/pull/25322 (in 2.1).

**Comment by petermattis** [comment] 2018-08-21 21:49
@tschottdorf The logs don't say much about `r1`. My thinking about next steps here are to take what we know so far and start trying to reproduce the scenario. 

I think this is looking a lot like #24753. I'm not clear on why increasing the node descriptor TTL was supposed to help. It looks like the lack of a lease on `r1` could be the root problem and that #25322 would be the real fix.

**Comment by petermattis** [comment] 2018-08-22 02:07
I think the root fragility in gossip is its external requirement that the sentinel key is gossiped on a regular basis from a single node. I think we should do something about this in 2.2 and make gossip more independent of the surrounding code. I don't have a concrete proposal for how to do this, though I'll make the observation that each gossip node knows about who is connected to it and who it is connected to (from which the graphs above were created). It seems like gossip has more than enough info to determine that all of the nodes are fully connected or not. The challenge is coming up with a protocol which stabilizes to a fully connected state. 

@a-robinson Was any thought given to backporting #25322 to 2.0.x?

**Comment by a-robinson** [comment] 2018-08-22 04:38
> I'm not clear on why increasing the node descriptor TTL was supposed to help.

I can't remember why I thought that. If I had to guess, though, it'd be that I carried over my concerns about the gossip network-tightening logic from https://github.com/cockroachdb/cockroach/issues/24753#issuecomment-380941242. Looking at it with fresh eyes, though, the increased node descriptor TTLs do not appear to fix this in most cases.

> @a-robinson Was any thought given to backporting #25322 to 2.0.x?

It seemed risky at the time, especially without a proper test for it. At this point though it's been very thoroughly tested and seems clearly deserving.

**Comment by a-robinson** [comment] 2018-08-22 04:46
> I think the root fragility in gossip is its external requirement that the sentinel key is gossiped on a regular basis from a single node. I think we should do something about this in 2.2 and make gossip more independent of the surrounding code. I don't have a concrete proposal for how to do this, though I'll make the observation that each gossip node knows about who is connected to it and who it is connected to (from which the graphs above were created). It seems like gossip has more than enough info to determine that all of the nodes are fully connected or not. The challenge is coming up with a protocol which stabilizes to a fully connected state.

I'm not sure I buy this, at least not without further elaboration. In the presence of machine failures, you have to be able to determine whether you're in a partition or there are just a lot of nodes down, so it requires more than just an understanding of who you're connected to, but also of what nodes exist and are live.

There are certainly other ways you could design this (e.g. occasionally attempt to connect to all addresses that have ever been known) and it's possible that some may be slightly better than this, but the fact that the sentinel key is gossiped from a "single node" isn't as bad as it sounds when you consider that all meta1 lookups are also served from that "single node". It means that gossip effectively shares its point of failure with the kv/storage layer, which is better than having two different points of failure, either of which can bring down the cluster.

**Comment by petermattis** [comment] 2018-08-22 12:52
> I'm not sure I buy this, at least not without further elaboration. In the presence of machine failures, you have to be able to determine whether you're in a partition or there are just a lot of nodes down, so it requires more than just an understanding of who you're connected to, but also of what nodes exist and are live.

While the cluster has to determine it is a part of a partition, I don't think that requirement needs to be imposed on gossip. We already have Raft and node liveness to guarantee correct operation in the face of network partitions. 

> There are certainly other ways you could design this (e.g. occasionally attempt to connect to all addresses that have ever been known) and it's possible that some may be slightly better than this, but the fact that the sentinel key is gossiped from a "single node" isn't as bad as it sounds when you consider that all meta1 lookups are also served from that "single node". It means that gossip effectively shares its point of failure with the kv/storage layer, which is better than having two different points of failure, either of which can bring down the cluster.

The current failure point of gossip is more than just the single point of the range 1 leaseholder. There is  a subtle interaction between these two systems which is what I'm saying is the "root cause of the fragility".

As you mention above, there are other design approaches for gossip. Gossip's primary job is disseminating information. Currently it has this unfortunate complexity in how it forms connections that requires the user of gossip to periodically send the "sentinel" key from a stable node in the cluster. If the propagation of the "sentinel" key is not done correctly, then gossip fails closed and we can get a wedged cluster. I think it would be better for gossip to fail open and create an overly connected gossip network. 

Let's ponder some changes here for 2.2. I don't think there is anything urgent to do for either 2.0 or 2.1 other than backport #25322.

One bit that I still don't understand is why the gossip partition caused such problems. Is this because node liveness is dependent on gossip and it was being propagated? Also, where are the "missing address" grpc errors coming from?

**Comment by petermattis** [comment] 2018-08-30 19:05
Fixed by https://github.com/cockroachdb/cockroach/pull/28963.

**Closed by petermattis** 2018-08-30 19:05 UTC
Labels: A-core-gossip, C-bug, O-support, S-2-temp-unavailability
