### ISSUE TITLE
sql: dump ignores ordering constraints from REFERENCES

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#17037] opened 2017-07-16 21:56 UTC
See the attached schema, seen in #16875. The file was created using

```
./cockroach  dump --dump-mode=schema --host XXX --insecure RO &> schema.sql
```

but it cannot be imported into a new cluster for a few reasons.

1. it does not attempt to create the database RO (obvious how to fix it)
1. it references table `venues` before it creates it.

This is similar when dumping the data: tables referencing a table may be dumped before the actual table is populated.

[schema.sql.txt](https://github.com/cockroachdb/cockroach/files/1151374/schema.sql.txt)

**Comment by mjibson** [comment] 2017-07-17 06:23
1. Is a feature, not a bug. It allows restoring to any database instead of only the one named. That's doubtful to change.
2. Is a known bug that already has a TODO. So we'll bump this up the priority list.

**Comment by mattiasmak** [comment] 2017-07-17 08:24
It's also the same with the inserts that FK-references to rows in other tables.

**Comment by miracle2k** [comment] 2017-08-04 12:25
Is there a workaround? The docs on CSV files seem to imply it only works with numeric values.

**Comment by mjibson** [comment] 2017-08-04 16:40
@miracle2k I'm not sure what your comment about CSV files is about.

**Comment by miracle2k** [comment] 2017-08-04 17:29
@mjibson Since cockroachdb supports import of CSV files, I was imagining that it would be an alternative to transfer data between cockroach clusters, as a workaround to the problems described here.

I noticed now that cockroach doesn't have the ability to dump into CSV; also, in the documentation it is written that the CSV import only works with "numeric values".

What I did for my small use case: Edited the sql file by hand to a) reorder the tables, and b) split all multi-insert-statements from the dump into individual statements inserting one row each. This avoids the foreign key issue. I couldn't find any easier way to migrate my data.

**Comment by mjibson** [comment] 2017-08-04 17:37
The comment about CSV only working with numeric values only applies to that specific example. We can import any kind of data. That example is illustrating how to convert some arbitrary numeric text into something cockroach can import (probably so it can avoid discussion of quoting and escaping). A smarter script or export program would produce correctly quoted CSV files that could be used for any kind of data.

In any case, this bug will be fixed within the month.

**Closed** 2017-08-17 18:48 UTC
