### ISSUE TITLE
Panic killed node during tpc-c on a six node cluster 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34255] opened 2019-01-25 18:20 UTC
**Describe the problem**

Node died while running tpc-c on a six node cluster with range merging and loadbased splitting turned off. In the shell I saw:

```
Error: error in payment: EOF
Error:  exit status 1
```
**To Reproduce**

1. export CLUSTER=andy-base
2. roachprod create $CLUSTER -n 7 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge
3. roachprod run $CLUSTER:1-6 -- 'sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /dev/nvme1n1 /mnt/data1/; mount | grep /mnt/data1'
4. roachprod stage $CLUSTER:1-6 cockroach
5. roachprod stage $CLUSTER:7 workload
6. roachprod start $CLUSTER:1-6
7.  roachprod sql $CLUSTER:1
8. SET CLUSTER SETTING kv.range_merge.queue_enabled = false
9. SET CLUSTER SETTING kv.range_split.by_load_enabled = false
10. roachprod adminurl --open $CLUSTER:1
11. roachprod run $CLUSTER:1 -- "./cockroach workload fixtures import tpcc --warehouses=5000 --db=tpcc"
12. roachprod run $CLUSTER:7 "./workload run tpcc --ramp=5m --warehouses=3400 --duration=15m --split --scatter {pgurl:1-3}"

**Expected behavior**
Completing tpc-c

**Additional data / screenshots**
![image](https://user-images.githubusercontent.com/22278911/51764748-eda0b080-20a3-11e9-9196-39f862e13c64.png)

**Environment:**
v2.2.0-alpha.20181217-836-g2952f08

From log to stderr
 https://gist.github.com/awoods187/701775096fe15cc8e0af3524fe19c26f

```
* ERROR: [n1,client=172.31.38.207:41378,user=root] a SQL panic has occurred while executing "SELECT i_price, i_name, i_data FROM item WHERE i_id IN (11946, 14108, 48849, 49892, 49913, 58017, 80705, 80961, 82017) ORDER BY i_id": runtime error: index out of range
* ERROR: [n1,client=172.31.38.207:41378,user=root] a panic has occurred!
panic while executing 1 statements: SELECT _, _, _ FROM _ WHERE _ IN (_, _, __more7__) ORDER BY _; caused by runtime error: index out of range
```

**Comment by jordanlewis** [comment] 2019-01-28 05:06
Duplicate of #34256.

**Closed by jordanlewis** 2019-01-28 05:06 UTC
