### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6097] opened 2016-04-17 02:57 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/0903b5fb8673a3df981587dbf1372a270ec7d18d

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x4612c9 m=0

goroutine 0 [idle]:
runtime.epollwait(0x7ffd00000004, 0x7ffd1b5a05b8, 0xffffffff00000080, 0x1, 0x1ffffffff, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/runtime/sys_linux_amd64.s:440 +0x19
runtime.netpoll(0x1160b01, 0x0)
	/usr/local/go/src/runtime/netpoll_epoll.go:67 +0x94
runtime.findrunnable(0xc820012000, 0x0)
	/usr/local/go/src/runtime/proc.go:1955 +0x62c
runtime.schedule()
	/usr/local/go/src/runtime/proc.go:2072 +0x24f
runtime.goexit0(0xc82013dc80)
	/usr/local/go/src/runtime/proc.go:2207 +0x1f9
runtime.mcall(0x7ffd1b5a0cd0)
	/usr/local/go/src/runtime/asm_amd64.s:233 +0x5b

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcf75a8, 0x1141060, 0xb, 0xb, 0xb57301)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82002ff08, 0xb57320)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 20 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1160a60)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:994 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:595 +0x8a

goroutine 14 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8202100cc)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8202100c8)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc8202100c0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc82035c000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc82035c000, 0x11410d8)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 15 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e070, 0xc820224040)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 66 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd78d6f84e0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201893a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201893a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820189340, 0x0, 0x7fd78d675368, 0xc82016f940)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820228010, 0xc820033ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820228010, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc820197a00, 0x7fd78d6f7538, 0xc820228010, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e070, 0xc820193480)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 68 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820132620)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820132620)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 67 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e070, 0xc820193580)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 29 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd78d6f8420, 0x72, 0xc820025400)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200d6060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200d6060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200d6000, 0xc820025400, 0x400, 0x400, 0x0, 0x7fd78d6f0050, 0xc82000c068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820126098, 0xc820025400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820144420, 0x7fd78d6b9580, 0xc820126098, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200da000, 0xcf7e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8200da000, 0xc8209f8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8200c6240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8200c6240, 0xc820434038, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fd78d6bdd60, 0xc8200c6240, 0xc820434038, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd78d6bdd60, 0xc8200c6240, 0xc820434038, 0x9, 0x9, 0x35b68fcb42102e01, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820434038, 0x9, 0x9, 0x7fd78d6bdd60, 0xc8200c6240, 0x8d000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820434000, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201ae3c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8200e6000, 0xc8201ae480)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc820197a00, 0x7fd78d6bddb0, 0xc8200e6000)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc820197a00, 0x7fd78d6bdc88, 0xc8200da000, 0x7fd78d6bdce8, 0xc8202062c0)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc820197a00, 0x7fd78d6f87f8, 0xc820126098)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 16 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e070, 0xc820193460)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 51 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc8203e8000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 69 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201b1714)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201b1710)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201b1710, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc8202100c0, 0xcf7e28)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc8202100c0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc8202100c0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8201893b0, 0xc8201f61e0, 0xc8201a14f0, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:175 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:157 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e070, 0xc8201acd80)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 40 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8200e6000)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 52 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7fd78d6f8360, 0x72, 0xc8203d8c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201f3870, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201f3870, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201f3810, 0xc8203d8c00, 0x400, 0x400, 0x0, 0x7fd78d6f0050, 0xc82000c068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820022000, 0xc8203d8c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8201783f0, 0x7fd78d6b9580, 0xc820022000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200d8000, 0xcf7e17, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8200d8000, 0xc820408000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc820191020)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820191020, 0xc820417178, 0x9, 0x9, 0xc81fff5f0c, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fd78d6bdd60, 0xc820191020, 0xc820417178, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd78d6bdd60, 0xc820191020, 0xc820417178, 0x9, 0x9, 0xc8201b1358, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc820417178, 0x9, 0x9, 0x7fd78d6bdd60, 0xc820191020, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc820417140, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201b11a0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc8203e8000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

rax    0xfffffffffffffffc
rbx    0xffffffff
rcx    0x4612c9
rdx    0x80
rdi    0x4
rsi    0x7ffd1b5a05b8
rbp    0x11614a0
rsp    0x7ffd1b5a0578
r8     0x11614a0
r9     0x7fd78d740260
r10    0xffffffff
r11    0x246
r12    0xc8200e6000
r13    0xa
r14    0xbc91a0
r15    0x37
rip    0x4612c9
rflags 0x246
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
31 runs so far, 0 failures, over 5s
66 runs so far, 0 failures, over 10s
98 runs so far, 0 failures, over 15s
128 runs so far, 0 failures, over 20s
160 runs so far, 0 failures, over 25s
191 runs so far, 0 failures, over 30s
221 runs so far, 0 failures, over 35s
254 runs so far, 0 failures, over 40s
285 runs so far, 0 failures, over 45s
320 runs so far, 0 failures, over 50s
349 runs so far, 0 failures, over 55s
382 runs so far, 0 failures, over 1m0s
415 runs so far, 0 failures, over 1m5s
448 runs so far, 0 failures, over 1m10s
477 runs so far, 0 failures, over 1m15s
508 runs so far, 0 failures, over 1m20s
538 runs so far, 0 failures, over 1m25s
572 runs so far, 0 failures, over 1m30s
602 runs so far, 0 failures, over 1m35s
633 runs so far, 0 failures, over 1m40s
665 runs so far, 0 failures, over 1m45s
696 runs so far, 0 failures, over 1m50s
726 runs so far, 0 failures, over 1m55s
756 runs so far, 0 failures, over 2m0s
788 runs so far, 0 failures, over 2m5s
821 runs so far, 0 failures, over 2m10s
853 runs so far, 0 failures, over 2m15s
882 runs so far, 0 failures, over 2m20s
915 runs so far, 0 failures, over 2m25s
944 runs so far, 0 failures, over 2m30s
974 runs so far, 0 failures, over 2m35s
1005 runs so far, 0 failures, over 2m40s
1035 runs so far, 0 failures, over 2m45s
1066 runs so far, 0 failures, over 2m50s
1093 runs so far, 0 failures, over 2m55s
1124 runs so far, 0 failures, over 3m0s
1155 runs so far, 0 failures, over 3m5s
1185 runs so far, 0 failures, over 3m10s
1219 runs so far, 0 failures, over 3m15s
1249 runs so far, 0 failures, over 3m20s
1282 runs so far, 0 failures, over 3m25s
1312 runs so far, 0 failures, over 3m30s
1341 runs so far, 0 failures, over 3m35s
1370 runs so far, 0 failures, over 3m40s
1402 runs so far, 0 failures, over 3m45s
1434 runs so far, 0 failures, over 3m50s
1466 runs so far, 0 failures, over 3m55s
1490 runs so far, 0 failures, over 4m0s
1521 runs so far, 0 failures, over 4m5s
1550 runs so far, 0 failures, over 4m10s
1581 runs so far, 0 failures, over 4m15s
1607 runs so far, 0 failures, over 4m20s
1639 runs so far, 0 failures, over 4m25s
1670 runs so far, 0 failures, over 4m30s
1700 runs so far, 0 failures, over 4m35s
1728 runs so far, 0 failures, over 4m40s
1760 runs so far, 0 failures, over 4m45s
1793 runs so far, 0 failures, over 4m50s
1825 runs so far, 0 failures, over 4m55s
1855 runs so far, 0 failures, over 5m0s
1887 runs so far, 0 failures, over 5m5s
1917 runs so far, 0 failures, over 5m10s
1946 runs so far, 0 failures, over 5m15s
1976 runs so far, 0 failures, over 5m20s
2008 runs so far, 0 failures, over 5m25s
2041 runs so far, 0 failures, over 5m30s
2064 runs so far, 0 failures, over 5m35s
2095 runs so far, 0 failures, over 5m40s
2123 runs so far, 0 failures, over 5m45s
2152 runs so far, 0 failures, over 5m50s
2183 runs so far, 0 failures, over 5m55s
2214 runs so far, 0 failures, over 6m0s
2249 runs so far, 0 failures, over 6m5s
2277 runs so far, 0 failures, over 6m10s
2308 runs so far, 0 failures, over 6m15s
2338 runs so far, 0 failures, over 6m20s
2370 runs so far, 0 failures, over 6m25s
2401 runs so far, 0 failures, over 6m30s
2431 runs so far, 0 failures, over 6m35s
2464 runs so far, 0 failures, over 6m40s
2493 runs so far, 0 failures, over 6m45s
2523 runs so far, 0 failures, over 6m50s
2556 runs so far, 0 failures, over 6m55s
2589 runs so far, 0 failures, over 7m0s
2620 runs so far, 0 failures, over 7m5s
2653 runs so far, 0 failures, over 7m10s
2681 runs so far, 0 failures, over 7m15s
2711 runs so far, 0 failures, over 7m20s
2743 runs so far, 0 failures, over 7m25s
2768 runs so far, 0 failures, over 7m30s
2798 runs so far, 0 failures, over 7m35s
2828 runs so far, 0 failures, over 7m40s
2858 runs so far, 0 failures, over 7m45s
2887 runs so far, 0 failures, over 7m50s
2907 runs so far, 0 failures, over 7m55s
2940 runs so far, 0 failures, over 8m0s
2972 runs so far, 0 failures, over 8m5s
3003 runs so far, 0 failures, over 8m10s
3034 runs so far, 0 failures, over 8m15s
3064 runs so far, 0 failures, over 8m20s
3095 runs so far, 0 failures, over 8m25s
3126 runs so far, 0 failures, over 8m30s
3159 runs so far, 0 failures, over 8m35s
3190 runs so far, 0 failures, over 8m40s
3221 runs so far, 0 failures, over 8m45s
3251 runs so far, 0 failures, over 8m50s
3279 runs so far, 0 failures, over 8m55s
3310 runs so far, 0 failures, over 9m0s
3342 runs so far, 0 failures, over 9m5s
3369 runs so far, 0 failures, over 9m10s
3399 runs so far, 0 failures, over 9m15s
3430 runs so far, 0 failures, over 9m20s
3461 runs so far, 0 failures, over 9m25s
3495 runs so far, 0 failures, over 9m30s
3527 runs so far, 0 failures, over 9m35s
3562 runs so far, 0 failures, over 9m40s
3589 runs so far, 0 failures, over 9m45s
3620 runs so far, 0 failures, over 9m50s
3652 runs so far, 0 failures, over 9m55s
3684 runs so far, 0 failures, over 10m0s
3716 runs so far, 0 failures, over 10m5s
3748 runs so far, 0 failures, over 10m10s
3775 runs completed, 1 failures, over 10m14s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:12
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:12 UTC
Labels: Robot, test-failure
