### ISSUE TITLE
Failed tests (10547): TestConvergence 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3585] opened 2016-01-04 18:07 UTC
The following test appears to have failed:

[#10547](https://circleci.com/gh/cockroachdb/cockroach/10547):

```
W0104 18:03:28.475994 518 rpc/server.go:240  rpc: server cannot decode request: read tcp 127.0.0.1:53847->127.0.0.1:48053: read: connection reset by peer
W0104 18:03:28.476376 518 rpc/server.go:240  rpc: server cannot decode request: read tcp 127.0.0.1:50343->127.0.0.1:54579: read: connection reset by peer
W0104 18:03:28.476655 518 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:53847->127.0.0.1:48060: write: broken pipe
W0104 18:03:28.477453 518 rpc/server.go:240  rpc: server cannot decode request: read tcp 127.0.0.1:53847->127.0.0.1:48054: read: connection reset by peer
W0104 18:03:28.478187 518 rpc/server.go:240  rpc: server cannot decode request: read tcp 127.0.0.1:37926->127.0.0.1:55731: read: connection reset by peer
--- FAIL: TestConvergence (0.67s)
	convergence_test.go:33: expected a fully-connected network within 15 cycles; took 18
W0104 18:03:28.482116 518 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:53847->127.0.0.1:48053: use of closed network connection
W0104 18:03:28.482347 518 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:53847->127.0.0.1:48051: use of closed network connection
W0104 18:03:28.482449 518 rpc/server.go:309  rpc: write response failed: write tcp 127.0.0.1:53847->127.0.0.1:48054: use of closed network connection
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	0.984s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.022s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.01s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-01-04 22:58
Duplicate of #3571

**Closed by bdarnell** 2016-01-04 22:58 UTC
Labels: test-failure, TestConvergence
