### ISSUE TITLE
stability: failed to allocate memory

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#10581] opened 2016-11-09 23:20 UTC
Seen on delta. The RSS of the cockroach binary was only using around 7.79 GB on a machine with 16GB total, although it looks kernel caching may have been using up most of the rest of the memory on the machine. This looks like it may be more an issue with our production node config than with cockroach itself. Why was kernel caching preventing a user process from allocating more memory?

```
[bcd] 2016/11/09 21:55:56 Retrieved goid: 226
I161109 21:55:56.271705 622 storage/replica.go:2073  [n10,s20,r594/6:/Table/55/1/127{85990…-91617…}] not quiescing: 1 pending commands
[bcd] 2016/11/09 21:55:56 Command: &{/opt/backtrace/bin/ptrace [/opt/backtrace/bin/ptrace --load= --module=go:enable,true,filter,user,goid,226 --faulted 15498 -L WARNING --kv cgo-compiler:gcc 4.9.2 --kv go-version:go1.7.3 --kv platform:linux amd64 --kv tag:beta-20161103-94-g3e0f63d --kv time:2016/11/07 14:50:41 --fault-thread 22493 --kv error:runtime error: invalid memory address or nil pointer dereference --classifier runtime.errorString] [] /home/cockroach/logs <nil> <nil> 0xc420128018 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
[bcd] 2016/11/09 21:55:56 Waiting for tracer completion...
[bcd] 2016/11/09 21:55:56 Starting tracer &{/opt/backtrace/bin/ptrace [/opt/backtrace/bin/ptrace --load= --module=go:enable,true,filter,user,goid,226 --faulted 15498 -L WARNING --kv cgo-compiler:gcc 4.9.2 --kv go-version:go1.7.3 --kv platform:linux amd64 --kv tag:beta-20161103-94-g3e0f63d --kv time:2016/11/07 14:50:41 --fault-thread 22493 --kv error:runtime error: invalid memory address or nil pointer dereference --classifier runtime.errorString] [] /home/cockroach/logs <nil> <nil> 0xc420128018 [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
I161109 21:55:56.322793 415042785 storage/raft_transport.go:432  [n10] raft transport stream to node 5 established
I161109 21:55:56.477219 772 storage/replica.go:2073  [n10,s20,r594/6:/Table/55/1/127{85990…-91617…}] not quiescing: 1 pending commands
[bcd] 2016/11/09 21:55:56 Tracer finished execution
[bcd] 2016/11/09 21:55:56 Tracer failed to run: fork/exec /opt/backtrace/bin/ptrace: cannot allocate memory
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x103634c]

goroutine 226 [running]:
panic(0x172d440, 0xc420010070)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/pkg/cli.initBacktrace.func2(0x172d440, 0xc420010070)
        /go/src/github.com/cockroachdb/cockroach/pkg/cli/backtrace.go:98 +0xca
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420430000)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:182 +0x56
panic(0x172d440, 0xc420010070)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/coreos/etcd/raft.(*raft).appendEntry(0xc427056960, 0xc437c8fcc0, 0x1, 0x1)
        /go/src/github.com/coreos/etcd/raft/raft.go:521 +0xdc
github.com/coreos/etcd/raft.(*raft).becomeLeader(0xc427056960)
        /go/src/github.com/coreos/etcd/raft/raft.go:621 +0x1ce
github.com/coreos/etcd/raft.stepCandidate(0xc427056960, 0x6, 0x3, 0x5, 0x452, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/raft.go:1013 +0x5a9
github.com/coreos/etcd/raft.(*raft).Step(0xc427056960, 0x6, 0x3, 0x5, 0x452, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/raft.go:779 +0x11ef
github.com/coreos/etcd/raft.(*RawNode).Step(0xc42745db40, 0x6, 0x3, 0x5, 0x452, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/coreos/etcd/raft/rawnode.go:195 +0xc9
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest.func4(0xc42745db40, 0x7fa10fe62268, 0xc420010280, 0x7fa10fedf880)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2925 +0x89
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroupLocked(0xc420885180, 0x1a49400, 0xc4523a9828, 0xacb6db, 0xc420885258)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:492 +0x139
github.com/cockroachdb/cockroach/pkg/storage.(*Replica).withRaftGroup(0xc420885180, 0xc4523a9828, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/replica.go:509 +0x92
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRaftRequest(0xc42009d500, 0x7fa10fedf880, 0xc431a44b70, 0xc43bde2d80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:2926 +0xb72
github.com/cockroachdb/cockroach/pkg/storage.(*Store).processRequestQueue(0xc42009d500, 0x4022)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/store.go:3153 +0x180
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).worker(0xc4203c94a0, 0xc420430000)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:241 +0x267
github.com/cockroachdb/cockroach/pkg/storage.(*raftScheduler).Start.func2()
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/scheduler.go:181 +0x33
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker.func1(0xc420430000, 0xc42166b900)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:196 +0x7d
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunWorker
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:197 +0x66

[...]
```

```
$ top
top - 23:08:34 up 58 days,  7:55,  1 user,  load average: 31.86, 33.48, 34.10
Tasks: 124 total,   1 running, 123 sleeping,   0 stopped,   0 zombie
%Cpu(s): 39.5 us, 23.1 sy,  0.0 ni, 35.9 id,  0.0 wa,  0.0 hi,  1.5 si,  0.0 st
GiB Mem:    15.708 total,    7.250 used,    8.458 free,    0.055 buffers
GiB Swap:    0.000 total,    0.000 used,    0.000 free.    6.566 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 8567 root      20   0  511.8m  15.4m   0.5m S   0.0  0.1   4:06.00 node_exporter
16093 root      20   0 4682.1m  14.4m   3.6m S 501.2  0.1 735:17.61 block_writer
19134 root      20   0   57.1m  12.5m   2.4m S  31.6  0.1 135:03.99 supervisord
  599 root      20   0   56.0m  11.2m   2.0m S   0.0  0.1   2:20.88 google_accounts
  598 root      20   0   55.8m  10.9m   1.9m S   0.0  0.1   2:16.81 google_ip_forwa
  600 root      20   0   55.5m  10.9m   2.0m S   0.0  0.1   2:17.18 google_clock_sk

$ free -m
             total       used       free     shared    buffers     cached
Mem:         16085       7400       8684         56         56       6697
-/+ buffers/cache:        646      15438
Swap:            0          0          0

$ smem -w -k
Area                           Used      Cache   Noncache
firmware/hardware                 0          0          0
kernel image                      0          0          0
kernel dynamic memory          7.6G       7.4G     133.8M
userspace memory             111.5M      19.1M      92.4M
free memory                    8.0G       8.0G          0
```

**Comment by a-robinson** [comment] 2016-11-10 00:00
Looks like most of the cached memory is/was from the cockroach sstable files:

```
$ sudo vmtouch /mnt/data1/
           Files: 1737
     Directories: 1
  Resident Pages: 551938/36516446  2G/139G  1.51%
         Elapsed: 1.1746 seconds
$ sudo vmtouch /mnt/data2/
           Files: 1707
     Directories: 1
  Resident Pages: 893569/36163755  3G/137G  2.47%
         Elapsed: 1.2047 seconds
```

**Comment by petermattis** [comment] 2016-11-10 01:43
The `cannot allocate memory` error is coming from backtrace (see http://backtrace.io) which is invoked in our panic handling code. In other words, it isn't the root problem. That stack trace looks the same as #8535. I thought that was supposed to be fixed by #10530. Do you know if that PR was in the binary running on delta when this crash occurred?

**Comment by a-robinson** [comment] 2016-11-10 14:33
The binary did not contain that change, which explains the underlying segfault. I'm still confused that we weren't able to allocate enough memory to run backtrace, but that's the only real question here, and it'd be reasonable to say it isn't all that important right now.

**Comment by petermattis** [comment] 2016-11-10 15:20
I've seen that backtrace error before but never taken the time to investigate. Probably something we should notify the folks on #backtrace of.

**Comment by knz** [comment] 2016-11-14 14:00
If that process is attempting to fork to run ptrace, that would explain -- forking 7.79GB will hit up near 16GB.

**Comment by petermattis** [comment] 2016-11-14 14:02
Forking marks the shared memory between the parent and child copy-on-write. Doesn't it?

**Comment by knz** [comment] 2016-11-14 14:02
It does but the virtual size (address space) needs to double.

**Comment by petermattis** [comment] 2016-11-14 14:08
Right, but Linux allows that. At least, I think it allows it.

**Comment by knz** [comment] 2016-11-14 14:22
The default on linux has changed from the old days.
Details of the behavior here:
https://www.kernel.org/doc/Documentation/vm/overcommit-accounting

The default mode 0 uses a heuristic; this fails because "The problem is that fork will fail when the process has more than approximately half of the available memory as commit charge." see https://github.com/jemalloc/jemalloc/issues/193

Note that this issue was addressed upstream in jemalloc, perhaps we can reuse their wisdom.

**Comment by a-robinson** [comment] 2016-11-14 14:34
Very interesting, my thinking was the same as @petermattis's. Thanks for correcting us. I'll read more into what jemalloc is doing later this week and see if there's anything simple we can do to avoid this, but may not prioritize it super highly given that it only affects us during shutdown.

**Comment by a-robinson** [comment] 2016-11-17 21:11
Jemalloc did already fix this as pointed out by @knz. All we'd have to do to fix this ourselves is update our version of jemalloc. We're currently at 4.1.0, while the first version with their fix is 4.2.0, which was released in May (with 4.2.1 in June). They also released 4.3.1 just 10 days ago.

I realize this isn't a huge issue, so we could just ignore it for a while if merging/verifying a new version of jemalloc is too much hassle for now given our other priorities. Thoughts on how much work it is from having done it before, @tamird @petermattis?

**Comment by tamird** [comment] 2016-11-17 21:15
It's not bad at all. I'll put a PR out today, though the verification work
might be the real blocker.

**Comment by dianasaur323** [comment] 2017-04-05 15:54
@tamird is this still an issue? If not, let's close out.

**Comment by tamird** [comment] 2017-04-05 16:08
Yes, jemalloc has been updated. I'll let @a-robinson close this.

**Comment by a-robinson** [comment] 2017-04-05 16:35
We've updated jemalloc, and don't have backtrace enabled anymore. No reason to keep this open.

**Closed** 2017-04-05 16:34 UTC
Labels: stability
