### ISSUE TITLE
latest docker tag points to 2.1.9

### ISSUE THREAD

**Issue by jakob** [cockroachdb/cockroach#41067] opened 2019-09-25 11:22 UTC
**Describe the problem**

Our test suite automatically fetches the "latest" tag from https://hub.docker.com/r/cockroachdb/cockroach/tags

This ended up downloading 2.1.9 instead of 19.1.4

**To Reproduce**

(see above)

**Expected behavior**

I expect the latest tag to be the latest stable version of CockroachDB

**Additional data / screenshots**

N/A

**Environment:**

N/A

**Additional context**
What was the impact?

We're testing our app against an outdated version of CockroachDB. We could use specific tags instead, but then we would have to manually keep the tag up to date.

Seems to be related to this issue: https://github.com/cockroachdb/cockroach/issues/25176

**Comment by petermattis** [comment] 2019-09-25 19:21
This should be fixed.

@kenliu the steps to fix were:

```
~ docker pull cockroachdb/cockroach:v19.1.4
~ docker tag cockroachdb/cockroach:v19.1.4 cockroachdb/cockroach:latest
~ docker push cockroachdb/cockroach:latest
```

Replace `v19.1.4` with whatever the desired `latest` version is.

**Comment by jordanlewis** [comment] 2019-12-16 22:41
@kenliu this still seems broken, and it's worse now because we're up to 19.2 :) Looks like a script needs to be fixed.

**Comment by jordanlewis** [comment] 2019-12-16 22:48
The problem is that `build/teamcity-publish-artifacts.sh` doesn't distinguish between the release branches. It just pushes to `latest` always. Whereas what we really want is to make only the 19.2 branch (or whatever the current, newest branch is) push to `latest`.

**Comment by awoods187** [comment] 2019-12-17 22:22
This seems like it should be a priority fix to help new users who only come via docker. @kenliu

**Comment by jordanlewis** [comment] 2019-12-19 14:54
Team, we have to fix this ASAP.

**Comment by kenliu** [comment] 2019-12-19 15:01
sorry I missed this. Reassigning to @bobvawter for triage.

**Comment by bobvawter** [comment] 2020-01-16 21:37
Will pick this up on Monday, per conversation with @kenliu

**Comment by bobvawter** [comment] 2020-01-21 18:56
I've tweaked the "Bless Provisional Artifacts" build step in such as way as to suppress pushing the `latest` tag except on `19.2.*` branches.  There's a 19.1 point release coming up to verify.

**Comment by bobvawter** [comment] 2020-01-28 14:41
Verified that the '19.1.7` image push didn't also push the `latest` tag.

**Closed by bobvawter** 2020-01-28 14:41 UTC
