### ISSUE TITLE
sql: SCRUB does not have a SessionData set on the InternalExecutor

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#47031] opened 2020-04-04 15:40 UTC
otan edit:

I've been playing around with SCRUB, and it appears that the InternalExecutor on SCRUB does not have the SessionData properly set.

As such, when it tries to execute the query of check-constraint, it lands here https://github.com/cockroachdb/cockroach/blob/ea7c4594a3c1d3b54c00bb5e7f795ddf0736f0c3/pkg/sql/internal.go#L365

and as such, when executing the subquery to check temp tables, the SearchPath is set incorrectly when set incorrectly despite being available in https://github.com/cockroachdb/cockroach/blob/ea7c4594a3c1d3b54c00bb5e7f795ddf0736f0c3/pkg/sql/scrub_constraint.go#L100 as `params.extendedEvalCtx.SessionData.SearchPath`

I've had similar issues with SCRUB before not having the same session data as before, going let let SQL schema take a look. I can't find anywhere obvious where SessionData is mis-set but happy to be wrong. Or maybe using the InternalExecutor for this is not a good idea.

----

Consider the following statements:

```sql
SET experimental_enable_temp_tables = 'on';
SET experimental_enable_hash_sharded_indexes = 'on';
CREATE TEMP TABLE t0(c0 INT);
CREATE INDEX ON t0(c0) USING HASH WITH BUCKET_COUNT=2;
EXPERIMENTAL SCRUB table t0; -- ERROR: check-constraint: cannot access temporary tables of other sessions
```
Unexpectedly, the `SCRUB` statement results in an error `ERROR: check-constraint: cannot access temporary tables of other sessions`. It seems that this error occurs only for hash-sharded indexes on `TEMP` tables.

I found this issue based on commit 5d33d44abe755effcf31b9cfd2d85274b530392a.

Jira issue: CRDB-5049

**Comment by yuzefovich** [comment] 2020-04-04 16:32
Hm, probably a missed edge case in temp table work. cc @otan @rohany

**Comment by otan** [comment] 2020-04-14 17:12
This issue seems to be that the InternalExecutor for `SCRUB` does not have the SessionData set correctly. I've hacked around this before but I'm not sure what the thing that is totally setting this wrong is. Passing to SQL Schema.

**Comment by postamar** [comment] 2022-03-08 20:19
Closing, can't reproduce. I don't know what changed since then but things seem to be fine now.

**Closed by postamar** 2022-03-08 20:19 UTC
Labels: C-bug, A-sql-scrub, T-sql-schema
