### ISSUE TITLE
Query with HAVING clause, DISTSQL=off, and vectorize=on results in an internal error

### ISSUE THREAD

**Issue by mrigger** [cockroachdb/cockroach#46503] opened 2020-03-24 17:29 UTC
Consider the following statements:

```sql
SET SESSION DISTSQL=off;
SET vectorize=on;
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES(0);
SELECT * FROM t0 GROUP BY t0.c0 HAVING MAX(CASE WHEN NULL THEN t0.c0::SMALLINT ELSE 0 END)::BOOL IS NULL; -- internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []int16
```
Unexpectedly, the `SELECT` results in an internal error with the following stack trace:
```
ERROR: internal error: unexpected error from the vectorized runtime: interface conversion: coldata.column is []int64, not []int16
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:92: func1()
runtime/panic.go:679: gopanic()
runtime/iface.go:255: panicdottypeE()
github.com/cockroachdb/cockroach/pkg/col/coldata/vec.go:196: Int16()
github.com/cockroachdb/cockroach/pkg/sql/colexec/cast.eg.go:485: cast()
github.com/cockroachdb/cockroach/pkg/sql/colexec/cast.eg.go:2138: func1()
github.com/cockroachdb/cockroach/pkg/sql/colexec/allocator.go:182: PerformOperation()
github.com/cockroachdb/cockroach/pkg/sql/colexec/cast.eg.go:2137: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/is_null_ops.go:114: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/simple_project.go:110: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/simple_project.go:110: Next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:149: next()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:140: nextAdapter()
github.com/cockroachdb/cockroach/pkg/sql/colexec/execerror/error.go:95: CatchVectorizedRuntimeError()
github.com/cockroachdb/cockroach/pkg/sql/colexec/materializer.go:177: Next()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:170: Run()
github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:749: Run()
github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:405: Run()
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1019: PlanAndRun()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:874: execWithDistSQLEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:767: dispatchToExecutionEngine()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:472: execStmtInOpenState()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:95: execStmt()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1368: execCmd()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1297: run()
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:476: ServeConn()
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:594: func1()
runtime/asm_amd64.s:1357: goexit()
```

Environment:
```
Build Tag:    v20.1.0-beta.2-1038-gd53a78b2dd
Build Time:   2020/03/24 16:45:33
Distribution: CCL
Platform:     linux amd64 (x86_64-linux-gnu)
Go Version:   go1.13.4
C Compiler:   gcc 8.3.0
Build SHA-1:  d53a78b2dd6aa8f25b2d1687ba744ce213728874
Build Type:   development
```

**Comment by asubiotto** [comment] 2020-03-30 13:51
Possible that this could be fixed by #46712

**Comment by yuzefovich** [comment] 2020-04-06 23:23
This is not fixed by #46712, however, the problem occurs only with `distsql=off` which I thought should be disabling the vectorized engine.

**Comment by yuzefovich** [comment] 2020-04-07 00:35
Ok, so `distsql=off` matters here because in `physicalplan.MakeExpression` we choose to keep the already typed expression, but with `distsql=auto` we will stringify it to `@2::BOOL` and will reparse it later.

I believe this issue is related to #46940 (not respecting width of integers types):
```
root@:26257/defaultdb> explain (types, verbose) SELECT * FROM t0 GROUP BY t0.c0 HAVING MAX(CASE WHEN NULL THEN t0.c0::SMALLINT ELSE 0 END)::BOOL IS NULL;
            tree           |    field    |                     description                      |        columns        | ordering
---------------------------+-------------+------------------------------------------------------+-----------------------+-----------
                           | distributed | false                                                |                       |
                           | vectorized  | true                                                 |                       |
  render                   |             |                                                      | (c0 int)              |
   │                       | render 0    | (c0)[int]                                            |                       |
   └── filter              |             |                                                      | (c0 int, max int2)    |
        │                  | filter      | (((max)[int2]::BOOL)[bool] IS (NULL)[unknown])[bool] |                       |
        └── group          |             |                                                      | (c0 int, max int2)    |
             │             | aggregate 0 | c0                                                   |                       |
             │             | aggregate 1 | max(column3)                                         |                       |
             │             | group by    | c0                                                   |                       |
             └── render    |             |                                                      | (column3 int, c0 int) |
                  │        | render 0    | (0)[int]                                             |                       |
                  │        | render 1    | (c0)[int]                                            |                       |
                  └── scan |             |                                                      | (c0 int)              |
                           | table       | t0@primary                                           |                       |
                           | spans       | FULL SCAN                                            |                       |
```
We think that `CASE` expression returns `INT2` and that `MAX(CASE)` will also return `INT2`, however,  `execinfrapb.GetAggregateInfo` says that return type of `MAX` aggregate is `INT8`, so we end up with this mismatch.

I actually don't know how to "synchronize" the vectorized engine with the logical type system in this case. For some reason, when `distsql=off`, `tree.IndexedVar` that references the second output column of the aggregator has `INT2` as the type annotation, but with `distsql=auto` the type annotation contains `INT8`.

It feels to me that this should be fixed before we do the planning in the vectorized engine, as if we're missing some casts. cc @RaduBerinde @rytaft do the types look good to you guys in the explain output?

**Comment by rytaft** [comment] 2020-04-07 18:39
It's pretty hard for me to tell anything based on that explain output... is there a particular type that you think is wrong? `EXPLAIN (opt, types)` might be helpful.

**Comment by yuzefovich** [comment] 2020-04-07 22:20
```
  project
   ├── columns: c0:1(int)
   ├── stats: [rows=33.3333333]
   ├── cost: 1082.40333
   ├── key: (1)
   ├── prune: (1)
   └── select
        ├── columns: c0:1(int) max:4(int!null)
        ├── stats: [rows=33.3333333]
        ├── cost: 1082.06
        ├── key: (1)
        ├── fd: (1)-->(4)
        ├── group-by
        │    ├── columns: c0:1(int) max:4(int!null)
        │    ├── grouping columns: c0:1(int)
        │    ├── stats: [rows=100, distinct(1)=100, null(1)=10]
        │    ├── cost: 1081.05
        │    ├── key: (1)
        │    ├── fd: (1)-->(4)
        │    ├── prune: (4)
        │    ├── project
        │    │    ├── columns: column3:3(int2!null) c0:1(int)
        │    │    ├── stats: [rows=1000, distinct(1)=100, null(1)=10]
        │    │    ├── cost: 1050.03
        │    │    ├── fd: ()-->(3)
        │    │    ├── prune: (1,3)
        │    │    ├── scan t0
        │    │    │    ├── columns: c0:1(int)
        │    │    │    ├── stats: [rows=1000, distinct(1)=100, null(1)=10]
        │    │    │    ├── cost: 1030.02
        │    │    │    └── prune: (1)
        │    │    └── projections
        │    │         └── const: 0 [as=column3:3, type=int]
        │    └── aggregations
        │         └── max [as=max:4, type=int2, outer=(3)]
        │              └── variable: column3:3 [type=int2]
        └── filters
             └── is [type=bool, outer=(4)]
                  ├── cast: BOOL [type=bool]
                  │    └── variable: max:4 [type=int]
                  └── null [type=unknown]
```

I feel like I'm actually confused on what is the expected integer width should be in each place, probably what should be the output type of `max` aggregate. In distsql physical planning stage we expect it to be `INT8`, but the explain suggests it should be `INT2`. Then the vectorized engine actually outputs `INT8` as well.

**Comment by rytaft** [comment] 2020-04-08 21:59
This does look a bit weird. The columns of the `group-by` and `select` operators show column `max` with type `int`, but the aggregation `max` has type `int2`:
```
...
        ├── columns: c0:1(int) max:4(int!null)
...
        │    ├── columns: c0:1(int) max:4(int!null)
...
        │         └── max [as=max:4, type=int2, outer=(3)]
...
```

The issue you referenced (#46940) does seem like it could be the culprit here.

**Comment by yuzefovich** [comment] 2020-10-10 20:29
Hm, this issue no longer reproduces on master and on 20.2 (but it is still present on 20.1.5), so I'm guessing we fixed something around type resolution and it is probably not going to be backported. Closing.

**Closed by yuzefovich** 2020-10-10 20:29 UTC
Labels: C-bug
