### ISSUE TITLE
build: add a make flag to insert a "vendor tag" into the version field

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#17103] opened 2017-07-19 02:41 UTC
Discussed with @nstewart @dt:

When RedHat and other vendors "ship" CockroachDB we would like to measure in our reg server how many users are using CockroachDb from that channel. Same for other channels like Docker, Mesosphere, etc.

To achieve this as suggested by @dt we should extend the "platform" field already sent by cluster to the reg server with information about the provider. For example from `linux` to `linux-redhat`. 

The additional string would be "baked into" the binary executable by means of a make flag.

Once this is possible we should then be disciplined to explain to vendors who build their own cockroach binary from sources to use this flag in their builds if possible.

cc @mberhault @benesch

**Comment by mberhault** [comment] 2017-07-19 12:20
Why combine it into the `platform` field? We may as well add another field so we don't need to re-extract the vendor later.
We'll most likely need to change the build pipeline for binaries. Adding that one flag shouldn't rebuild much.

**Comment by benesch** [comment] 2018-03-12 21:55
Duplicate of #22283, and fixed by https://github.com/cockroachdb/cockroach/pull/23437.

**Closed by benesch** 2018-03-12 21:55 UTC
