### ISSUE TITLE
Test failure in CI build 3937

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1463] opened 2015-06-23 20:19 UTC
The following test appears to have failed:

[#3937](https://circleci.com/gh/cockroachdb/cockroach/3937):

```
W0623 20:17:37.351517     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.353455     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.355516     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.357425     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.359328     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
--- FAIL: TestRangeDanglingMetaIntent (0.35s)
	range_test.go:2478: expected close to 50/50 counts; got 38/62
=== RUN TestInternalRangeLookup
I0623 20:17:37.363540     498 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:17:37.368686     498 range.go:976] gossiping cluster id test from store 1, range 1
I0623 20:17:37.372929     498 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0623 20:17:37.373226     498 range.go:1037] gossiping accounting config from store 1, range 1
I0623 20:17:37.373752     498 range.go:1037] gossiping permissions config from store 1, range 1
I0623 20:17:37.374286     498 range.go:1037] gossiping zones config from store 1, range 1
I0623 20:17:37.374992     498 range.go:984] gossiping sentinel from store 1, range 1
I0623 20:17:37.375455     498 range.go:988] gossiping first range from store 1, range 1
--
E0623 20:17:51.960564     498 queue.go:266] failure processing range range=2 ["b" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0623 20:17:51.973128     498 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
--- PASS: TestStoreStatus (0.13s)
=== RUN: ExampleAllocatorRebalancing
--- PASS: ExampleAllocatorRebalancing (0.98s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	17.751s
=== RUN TestBatchBasics
I0623 20:18:23.983596     606 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:18:23.984654     606 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0623 20:18:23.987441     606 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:18:23.987715     606 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0623 20:18:23.990678     606 rocksdb.go:88] opening in-memory rocksdb instance
W0623 20:17:37.351517     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.353455     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.355516     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.357425     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
W0623 20:17:37.359328     498 range.go:1059] failed to resolve on inconsistent read: conflicting intents on ["\x00\x00meta2a"]: resolved? false
--- FAIL: TestRangeDanglingMetaIntent (0.35s)
	range_test.go:2478: expected close to 50/50 counts; got 38/62
=== RUN TestInternalRangeLookup
I0623 20:17:37.363540     498 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:17:37.368686     498 range.go:976] gossiping cluster id test from store 1, range 1
I0623 20:17:37.372929     498 range_command.go:774] range 1: new leader lease replica 1:1 00:00:00.000 +1.000s
I0623 20:17:37.373226     498 range.go:1037] gossiping accounting config from store 1, range 1
I0623 20:17:37.373752     498 range.go:1037] gossiping permissions config from store 1, range 1
I0623 20:17:37.374286     498 range.go:1037] gossiping zones config from store 1, range 1
I0623 20:17:37.374992     498 range.go:984] gossiping sentinel from store 1, range 1
I0623 20:17:37.375455     498 range.go:988] gossiping first range from store 1, range 1
--
E0623 20:17:51.960564     498 queue.go:266] failure processing range range=2 ["b" - "\xff\xff") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
E0623 20:17:51.973128     498 queue.go:266] failure processing range range=1 ["" - "b") from replicate queue: allocator.go:207: unable to allocate a target store for {[] }
--- PASS: TestStoreStatus (0.13s)
=== RUN: ExampleAllocatorRebalancing
--- PASS: ExampleAllocatorRebalancing (0.98s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	17.751s
=== RUN TestBatchBasics
I0623 20:18:23.983596     606 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:18:23.984654     606 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0623 20:18:23.987441     606 rocksdb.go:88] opening in-memory rocksdb instance
I0623 20:18:23.987715     606 rocksdb.go:113] closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0623 20:18:23.990678     606 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-06-23 20:22
Dupe of #1451.

**Closed by tamird** 2015-06-23 20:22 UTC
Labels: test-failure
