### ISSUE TITLE
kv: TestKVNemesisMultiNode failed in CI

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#110457] opened 2023-09-12 17:00 UTC
https://teamcity.cockroachdb.com/viewLog.html?buildId=11740779&buildTypeId=Cockroach_BazelEssentialCi

Jira issue: CRDB-31440

**Comment by andrewbaptist** [comment] 2023-09-14 21:01
dupe of #110519

**Comment by nvanbenschoten** [comment] 2023-09-18 17:49
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/110519.

**Closed by nvanbenschoten** 2023-09-18 17:49 UTC
Labels: C-test-failure, branch-master, T-kv, A-ci
