### ISSUE TITLE
kv: TPC-C perf degradation in 22.2.5 compared to 21.1

### ISSUE THREAD

**Issue by williamkulju** [cockroachdb/cockroach#97747] opened 2023-02-27 20:10 UTC
@erikgrinaker reported the following: "Regarding 81-node TPCC benchmarks, 22.2.5 doesn't pass at 140.000 warehouses (the 21.1 baseline) -- the cluster doesn't handle the load and the workload errors out. I couldn't get a 120.000 warehouse run (on a 140.000 warehouse dataset) to pass either."

Not sure if this was due to a regression or an env issue. Regardless, we need to figure out what's going on ASAP. This should be considered a release blocker for 23.1.

Jira issue: CRDB-24863

Epic CRDB-24849

**Comment by andrewbaptist** [comment] 2023-03-13 13:22
I ran this across multiple releases to see the impact. While I hit a few other problems (tracked separately) the performance for the 15-node TPCC improved release-over-release. Here are the results from the runs:

This test was hard to reliability run by manually following the online instructions as minor things like partitioning or not changing settings would alter results.  I additionally created automation to set up and test any of the sizes that are published and set up the 15-node test to run as part of weekly testing #98418


*v21.1.21*
```
Duration: 30m0., Warehouses: 0, Efficiency: +Inf, tpmC: 161894.26
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          271.5     41.9    218.1    285.2    402.7    939.5 delivery
 1800.0s         2698.2     29.4    176.2    226.5    335.5   1275.1 newOrder
 1800.0s          271.7      4.2     22.0     31.5     56.6    704.6 orderStatus
 1800.0s         2715.8     17.8    109.1    151.0    226.5    872.4 payment
 1800.0s          271.6     15.2     60.8     83.9    142.6    738.2 stockLevel
```
*v21.2.17*
```
Duration: 30m0., Warehouses: 13000, Efficiency: 99.92, tpmC: 163737.78
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1801.0s          272.0     35.7     88.1    104.9    142.6    738.2 delivery
 1801.0s         2729.0     18.9     56.6     71.3    104.9    520.1 newOrder
 1801.0s          272.2      3.8     10.0     14.2     24.1    130.0 orderStatus
 1801.0s         2722.6     10.0     33.6     46.1     71.3    335.5 payment
 1801.0s          272.0     13.6     37.7     48.2     79.7    469.8 stockLevel
```
*v22.1.16*
```
Duration: 30m0., Warehouses: 13000, Efficiency: 99.98, tpmC: 163828.74
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          272.1     31.5     67.1     83.9    109.1    268.4 delivery
 1800.0s         2730.5     17.8     41.9     56.6     83.9    436.2 newOrder
 1800.0s          272.5      3.7      7.6     11.5     19.9    226.5 orderStatus
 1800.0s         2725.8      9.4     25.2     35.7     56.6    268.4 payment
 1800.0s          272.2     13.1     29.4     39.8     62.9    243.3 stockLevel
```
*v22.2.6*
```
Duration: 30m0., Warehouses: 13000, Efficiency: 99.99, tpmC: 163849.29
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          272.3     30.4     60.8     75.5    109.1    335.5 delivery
 1800.0s         2730.8     17.8     37.7     52.4     79.7    302.0 newOrder
 1800.0s          272.6      3.9      7.1      9.4     16.8    226.5 orderStatus
 1800.0s         2725.4      9.4     22.0     30.4     50.3    285.2 payment
 1800.0s          272.3     14.2     28.3     39.8     71.3    260.0 stockLevel
```
*v23.1.0*
```
Duration: 30m0., Warehouses: 13000, Efficiency: 99.98, tpmC: 163827.57
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          272.0     33.6     75.5     96.5    142.6    637.5 delivery
 1800.0s         2730.5     18.9     48.2     65.0    100.7    402.7 newOrder
 1800.0s          272.4      4.5     10.0     13.6     24.1    151.0 orderStatus
 1800.0s         2724.8     10.0     26.2     35.7     58.7    369.1 payment
 1800.0s          272.1     16.8     35.7     48.2     83.9    369.1 stockLevel
```

I'm going to rerun the "medium" test with more warehouses to establish a new baseline for 23.1 going forward.

**Comment by andrewbaptist** [comment] 2023-03-13 13:30
For reference I grabbed some pprof loops from each run (at 13K warehouses) - I didn't spend much time debugging since there wasn't a detectable slowdown, but these might be useful as a reference in the future.

[21.1](https://github.com/cockroachdb/cockroach/files/10957824/pprof_20230310_201629.pb.gz)

[21.2](https://github.com/cockroachdb/cockroach/files/10957830/pprof_20230310_204819.pb.gz)

[22.1](https://github.com/cockroachdb/cockroach/files/10957831/pprof_20230310_215406.pb.gz)

[22.2](https://github.com/cockroachdb/cockroach/files/10957841/pprof_20230310_223155.pb.gz)

[23.1](https://github.com/cockroachdb/cockroach/files/10957842/pprof_20230311_002550.pb.gz)

**Comment by erikgrinaker** [comment] 2023-03-13 13:43
Were you able to get the 81-node test to pass 140k warehouses?

**Comment by andrewbaptist** [comment] 2023-03-13 19:51
Just as an additional test, I bumped the medium test from 13K to 14K warehouses to see if it would pass (it fails at 15K) and ran again on v22.2 and `master`. While both pass, there is a small degradation. 

v22.2:
```
Duration: 30m0., Warehouses: 14000, Efficiency: 99.97, tpmC: 176415.90
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          293.1     33.6     79.7    100.7    151.0   4563.4 delivery
 1800.0s         2940.3     18.9     52.4     67.1    109.1   6710.9 newOrder
 1800.0s          293.7      4.5     10.5     14.7     26.2   3221.2 orderStatus
 1800.0s         2934.1     10.0     29.4     39.8     67.1   4026.5 payment
 1800.0s          293.3     16.8     39.8     54.5    100.7   6710.9 stockLevel
```

master (v23.1)
```
Duration: 30m0., Warehouses: 14000, Efficiency: 99.99, tpmC: 176458.17
_elapsed___ops/sec(cum)__p50(ms)__p90(ms)__p95(ms)__p99(ms)_pMax(ms)
 1800.0s          293.1     28.3     54.5     71.3    100.7   4563.4 delivery
 1800.0s         2941.0     16.3     35.7     48.2     75.5   4831.8 newOrder
 1800.0s          293.5      3.7      6.3      8.9     15.7   3892.3 orderStatus
 1800.0s         2935.3      8.9     19.9     28.3     48.2   4563.4 payment
 1800.0s          293.2     12.6     24.1     31.5     58.7   3489.7 stockLevel
```

The 81-node test is started now on v22.2 and if that passes at 140K warehouses I will close this out.

**Comment by andrewbaptist** [comment] 2023-03-27 22:16
I'm going to put this research on hold for the time being (and remove the GA-blocker flag). There have been a lot of interesting findings and issues that have come out of this research. 
With 81 nodes on 23.1, I am able to run 140K warehouses for a few minutes and 130K warehouses for the full 30 minutes. The easiest way to see them is by looking at the automated run. This is "close enough" to the original settings to mark this as done. There is still a bug in the way --partition-affiinity is applied which is causing a higher load on the nodes outside of the "first set". That will likely be enough to make up the remaining difference. 

Getting 140K to pass again in some ways is not very interesting because the issue is that it is not very close to how our customers will run the system. The more interesting thing is to compare the vanilla settings to the highly tuned settings to see where we can make improvements. 

I am going to continue to work on #98418 once I finish outstanding 23.1 tasks and figure out if there are ways we can use the learnings from that to optimize our software future.

**Comment by erikgrinaker** [comment] 2023-03-27 22:41
Thanks for digging into this. Had a quick look at https://github.com/cockroachdb/cockroach/pull/98418 -- was it admission control that was the deciding factor to pass 140k warehouses?

**Comment by nvanbenschoten** [comment] 2023-11-06 15:38
Closing as stale.

**Closed by nvanbenschoten** 2023-11-06 15:38 UTC
Labels: C-bug, T-kv
