### ISSUE TITLE
Dropping a database seems to hang forever

### ISSUE THREAD

**Issue by damienhollis** [cockroachdb/cockroach#32622] opened 2018-11-27 02:34 UTC
**Describe the problem**

We have a database that is globally distributed and we just tried dropping a database and it seems to hang forever (1 hour so far).  The database has a few hundred thousand rows of data (I didn't actually check before executing the drop).  We have dropped a similar database (it was probably bigger) that was not globally distributed and it worked fine. 

**To Reproduce**

Execute: drop database oph cascade;

**Expected behavior**

The database is dropped.

**Additional data / screenshots**

Screenshot of the drop statement included.

![screen shot 2018-11-27 at 3 25 31 pm](https://user-images.githubusercontent.com/465195/49054680-e868e600-f259-11e8-9deb-b18a5e4f85c4.png)

**Environment:**
 - CockroachDB version - 2.1.1
 - Server OS: Linux on Kubernetes
 - Client app cockroach sql

**Additional context**
What was the impact?

This is delaying our testing of this cluster configuration.

**Comment by knz** [comment] 2018-11-27 11:08
Thank you for your report!

@tim-o can you help qualify this further?

**Comment by tim-o** [comment] 2018-11-27 14:50
Hey @damienhollis,

Just a hunch but I think you might be running into #31818. Are you dropping and recreating the same database with the same names multiple times?

If so, assuming this is a testing cluster and you don't need to use AOST queries, you can try adjusting your [zone configurations](https://www.cockroachlabs.com/docs/stable/configure-replication-zones.html) so that `gc.ttlseconds` is short (say 5 minutes). Wait until that time passes, and then drop the database. It should complete much faster.

Let me know if that helps matters.

Thanks!

**Comment by vivekmenezes** [comment] 2018-11-30 15:21
@damienhollis thanks for reporting this issue. Were you indeed running some kind of automation that was dropping and creating tables?

**Comment by damienhollis** [comment] 2018-11-30 19:43
Sorry, I haven’t had a chance to test this again. I will next week. 

However, from memory the situation was that we had just restarted the whole cluster after it had been shutdown for several days and one of the first things I tried to do was drop the database and this happened. 

I have seen the issue with dropping and recreating the same database with 2.0 but not really with 2.1. But like I said above, I’ll retest next week.

**Comment by vivekmenezes** [comment] 2018-11-30 23:10
@damienhollis we know of another issue https://github.com/cockroachdb/cockroach/issues/32254 that could be the cause of what you're seeing. This happens when you restart a cluster (or one node for that manner) and run a schema change immediately (DROP TABLE), it *can* hang for 5 minutes. But it eventually goes through.

**Comment by tim-o** [comment] 2019-03-05 16:29
Hey @damienhollis - given that #32988 has merged, this should be resolved. If you're still running into issues let me know, and I'll reopen.

**Closed by tim-o** 2019-03-05 16:29 UTC
Labels: A-schema-changes, C-investigation, O-community
