### ISSUE TITLE
sql: insert fast path panics when evaluating check constraint errors

### ISSUE THREAD

**Issue by mgartner** [cockroachdb/cockroach#51690] opened 2020-07-22 00:34 UTC
A panic occurs when evaluating a `CHECK` constraint expression results in an error during an `INSERT` fast path (`insertFastPathNode`).

```
root@127.0.0.1:61739/defaultdb> create table t (a int, b int, check (3 / b = 1));
CREATE TABLE

Time: 7.83ms

root@127.0.0.1:61739/defaultdb> insert into t values (1, 0);
*
* ERROR: [n1,client=127.0.0.1:61741,hostssl,user=root] a SQL panic has occurred while executing the following statement:
* INSERT INTO t VALUES (1, 0)
*
*
* ERROR: [n1,client=127.0.0.1:61741,hostssl,user=root] a panic has occurred!
*
panic: runtime error: index out of range [3] with length 3 [recovered]
        panic: runtime error: index out of range [3] with length 3

goroutine 488 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc0023a2d80, 0x8e26860, 0xc000bd42c0, 0x809f960, 0xc001c44e00)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:800 +0x359
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc0023a2d80, 0x8e26860, 0xc000bd42c0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:489 +0x61
panic(0x809f960, 0xc001c44e00)
        /usr/local/Cellar/go/1.14.4/libexec/src/runtime/panic.go:969 +0x166
github.com/cockroachdb/cockroach/pkg/sql.interceptAlterColumnTypeParseError(0xc000522900, 0x3, 0x3, 0x3, 0x8d98a00, 0xc0003b1140, 0x7a45b17, 0xf)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert_fast_path.go:390 +0x29b
github.com/cockroachdb/cockroach/pkg/sql.(*insertFastPathNode).BatchedNext(0xc00183a600, 0x8e26860, 0xc0016c82c0, 0xc001fe8840, 0xc0023a3158, 0x7e99a00, 0xcedf01af83adcc01, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert_fast_path.go:289 +0x4c9
github.com/cockroachdb/cockroach/pkg/sql.(*rowCountNode).startExec(0xc0019a2e80, 0x8e26860, 0xc0016c82c0, 0xc001fe8840, 0xc0023a3158, 0xc000876d00, 0xc000791201)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:159 +0xcd
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x82bd9b4, 0x5, 0x8e290e0, 0xc0019a2e80, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:473 +0xc6
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0017a7b10, 0x82bd9b4, 0x5, 0x8e290e0, 0xc0019a2e80)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:142 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0017a7b10, 0x8e290e0, 0xc0019a2e80, 0x82bd9b4, 0x5)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:813 +0x38f
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0017a7b10, 0x8e290e0, 0xc0019a2e80, 0x1, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:109 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:73
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x8e26860, 0xc0016c82c0, 0xc001fe8840, 0xc0023a3158, 0x8e290e0, 0xc0019a2e80, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:476 +0x1bb
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc001729900, 0x8e26860, 0xc0016c82c0, 0xb88b540, 0x7bf3a00)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:125 +0xd6
github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBase).Run(0xc001729900, 0x8e26860, 0xc0016c82c0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:747 +0x52
github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run(0xc0005e6900, 0x8e26860, 0xc0016c82c0, 0x8497498, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:370 +0x23e
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc00091e0a0, 0xc002270cb0, 0xc0020805a0, 0xc0010df600, 0xc00225a300, 0xc0023a3240, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:409 +0x594
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc00091e0a0, 0x8e26920, 0xc0010a0180, 0xc0023a3240, 0xc002270cb0, 0xc0020805a0, 0x8e290e0, 0xc0019a2e80, 0x0, 0xc00225a300, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:981 +0x1d1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc0023a2d80, 0x8e26920, 0xc0010a0180, 0xc0023a3158, 0x2, 0xe176318, 0xc001832f80, 0xc0017a8400, 0xc0014510d8, 0x0, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:935 +0x3af
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc0023a2d80, 0x8e26920, 0xc0010a0180, 0xc0023a3158, 0xe176318, 0xc001832f80, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:833 +0x6c1
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc0023a2d80, 0x8e26920, 0xc0010a0180, 0x8e444e0, 0xc0006359f0, 0xc0025491b6, 0x1b, 0x0, 0x1, 0x0, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:520 +0xafb
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc0023a2d80, 0x8e26920, 0xc0010a0180, 0x8e444e0, 0xc0006359f0, 0xc0025491b6, 0x1b, 0x0, 0x1, 0x0, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:111 +0x863
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc0023a2d80, 0x8e26860, 0xc000bd4fc0, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1390 +0x1da4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc0023a2d80, 0x8e26860, 0xc000bd42c0, 0xc00091e320, 0x5400, 0x15000, 0xc00091e3c0, 0xc00041e430, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1319 +0x1ee
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc0008a9700, 0x8e26860, 0xc000bd42c0, 0xc0023a2d80, 0x5400, 0x15000, 0xc00091e3c0, 0xc00041e430, 0x0, 0x0)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:491 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc000524b22, 0xc000710b20, 0x8e26860, 0xc000bd42c0, 0xc00041e430, 0xc0008a9700, 0xc001832900, 0x8e521a0, 0xc000a2a7e0, 0xc00102a2a0, ...)
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:580 +0x39b
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        /Users/marcus/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:508 +0x17e
```

The expected behavior is a graceful error:

```
root@127.0.0.1:61826/defaultdb> create table a (a int, check (1 / a = 1));
CREATE TABLE

Time: 3.484ms

root@127.0.0.1:61826/defaultdb> select * from b;
  b
-----
  0
(1 row)

Time: 784µs

root@127.0.0.1:61826/defaultdb> insert into a (select b from b);
ERROR: division by zero
SQLSTATE: 22012
```

**Comment by knz** [comment] 2020-07-22 09:10
cc @asubiotto @yuzefovich for triage

**Comment by yuzefovich** [comment] 2020-07-22 16:21
The panic is caused by the new code path that was added a few months ago for ALTER COLUMN TYPE by @RichardJCai.

**Comment by RichardJCai** [comment] 2020-07-23 03:13
Fixed by https://github.com/cockroachdb/cockroach/pull/51789

**Closed** 2020-07-23 03:13 UTC
Labels: A-sql-execution, A-sql-mutations, C-bug, S-2-temp-unavailability
