### ISSUE TITLE
sql: group by with and without having unexpected error

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#25826] opened 2018-05-22 22:20 UTC
I found a group operation runs fine in CR

```
select count(1), id from accounts group by 2;
```
results
```
..
..
|     1 | 1705693954 |
|     1 |   14615598 |
|     1 |  437470398 |
|     1 | 1139529158 |
|     1 | 2014039347 |
|     1 | 2042943891 |
|     1 | 1099331843 |
|     1 | 1854847510 |
|     1 |  168120867 |
|     1 |  240648069 |
|     1 |  442538452 |
|     1 | 1833914446 |
+-------+------------+
(2327468 rows)

Time: 2m42.872759377s
```

When limiting the group by with having clause I encountered a memory budget exceeded error
```
root@:26257/test> select count(1), id from accounts group by 2 having count(1) > 1 order by 1;
pq: root: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
root@:26257/test> 

root@:26257/test> explain select count(1), id from accounts group by 2 having count(1) > 1 order by 1;
+-------------------------------+----------+------------------+
|             Tree              |  Field   |   Description    |
+-------------------------------+----------+------------------+
| sort                          |          |                  |
|  │                            | order    | +count           |
|  └── render                   |          |                  |
|       └── filter              |          |                  |
|            └── group          |          |                  |
|                 │             | group by | @1-@1            |
|                 └── render    |          |                  |
|                      └── scan |          |                  |
|                               | table    | accounts@primary |
|                               | spans    | ALL              |
+-------------------------------+----------+------------------+
(10 rows)

Time: 6.45954ms

```

I would have expected since it is streamed to output in the original group by , the having should have completed.  

In additional tests, without a PK, even with a larger set of rows, the group by and group by with having works fine. I can REPRO if required.

**Comment by asubiotto** [comment] 2018-09-06 19:35
Looking into this now. @drewdeally, does this still happen if you remove the having but keep the order by, i.e.:
```
select count(1), id from accounts group by 2 order by 1;
```
Could you also run `SHOW CREATE TABLE accounts` so I could take a look at the schema? Just to confirm, are you running this through distsql? If so, it would be helpful if you could share the `EXPLAIN (DISTSQL) <output>` for either query.

**Comment by drewdeally** [comment] 2018-09-06 19:43
I have not tried it since. let me repro and report what I find.

**Comment by drewdeally** [comment] 2018-09-06 20:00
time cockroach sql --insecure -e "explain select count(1), custid from smallbank.accounts group by 2 having count(1) > 1 order by 1"
+-------------------------------+-------------+----------------------------------+
|             tree              |    field    |           description            |
+-------------------------------+-------------+----------------------------------+
| render                        |             |                                  |
|  └── sort                     |             |                                  |
|       │                       | order       | +agg0                            |
|       └── filter              |             |                                  |
|            └── group          |             |                                  |
|                 │             | aggregate 0 | smallbank.public.accounts.custid |
|                 │             | aggregate 1 | count(column3)                   |
|                 │             | group by    | @2                               |
|                 └── render    |             |                                  |
|                      └── scan |             |                                  |
|                               | table       | accounts@pk_accounts             |
|                               | spans       | ALL                              |
+-------------------------------+-------------+----------------------------------+
(12 rows)

real	0m0.092s
user	0m0.048s
sys	0m0.031s
Andrews-MacBook-Pro:cockroachdb-training andrewdeally$ cockroach sql --insecure -e "show create table smallbank.accounts"
+---------------------------+------------------------------------------------------+
|        table_name         |                   create_statement                   |
+---------------------------+------------------------------------------------------+
| smallbank.public.accounts | CREATE TABLE accounts (                              |
|                           |                                                      |
|                           |     custid BIGINT NOT NULL,                          |
|                           |                                                      |
|                           |     name STRING(64) NOT NULL,                        |
|                           |                                                      |
|                           |     CONSTRAINT pk_accounts PRIMARY KEY (custid ASC), |
|                           |                                                      |
|                           |     INDEX idx_accounts_name (name ASC),              |
|                           |                                                      |
|                           |     FAMILY "primary" (custid, name)                  |
|                           |                                                      |
|                           | )                                                    |
+---------------------------+------------------------------------------------------+
(1 row)

**Comment by asubiotto** [comment] 2018-09-10 15:17
@drewdeally have you been able to reproduce? What sha are you using?

**Comment by asubiotto** [comment] 2018-09-10 17:45
With the current master (+ release2.1), because the optimizer does not currently use input ordering (https://github.com/cockroachdb/cockroach/issues/30000) unless the result of the group by needs it (in this case it doesn't use it since it orders by count), the aggregator is planned as a hash aggregator. This would trigger a memory issue, but the initial query would do so as well. This is a known limitation of the optimizer that will be fixed in 2.2. To get around it, I would `SET optimizer=off; <QUERY>; SET optimizer=on;`.

In your case, I assume the optimizer was not enabled (is this correct?) so the initial query without the having and sort would have an ordered aggregator planned, which would result in a successful run. However, for the second one, the most likely thing is that the aggregator runs out of memory because it is planned as a hashAggregator since the having filters out output rows and the sort should be planned as a `sortAllProcessor` which has external storage. There are a couple things I need to get more insight.

1) The sha, so that I can take a closer look at the plan.
2) Could you run `select count(1), id from accounts group by 2 having count(1) > 1` (the same query without the order by) with the problem sha to eliminate the order by variable. If this succeeds, the culprit is the order by and I would just want to confirm that external storage is enabled by running `SELECT * FROM [SHOW ALL CLUSTER SETTINGS] WHERE variable LIKE '%temp_storage%';`
3) Did you have the optimizer enabled for any of those two queries? If it was enabled for both, I would have expected `select count(1), id from accounts group by 2;` to also fail with an out of memory error.

**Comment by drewdeally** [comment] 2018-09-11 13:51
I will need to reproduce the data set. And will share the results.

**Comment by drewdeally** [comment] 2018-09-11 13:57
CCL v2.1.0-alpha.20180730 @ 2018/07/30 21:08:34 (go1.10.3)

**Comment by asubiotto** [comment] 2018-09-11 14:26
@drewdeally, are you sure that was the version with which this issue happened? Just want to check because the original comment was posted on `May 22`, around two months before that alpha.

**Comment by asubiotto** [comment] 2018-09-11 14:50
Talked to @drewdeally through slack. The query seems to work fine now and it's not worth the effort to figure out exactly what was going on in May. Closing.

**Closed by asubiotto** 2018-09-11 14:50 UTC
Labels: A-sql-memmon, C-investigation
