### ISSUE TITLE
sql: unique secondary index that used to be primary incorrectly uses PrimaryIndexEncoding in the descriptor on 21.1 and before

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#71552] opened 2021-10-13 23:18 UTC
On 21.1 and prior version if we do this sequence of steps:
```
CREATE TABLE t (a INT PRIMARY KEY, b INT NOT NULL);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (b);
ALTER TABLE t ALTER PRIMARY KEY USING COLUMNS (a);
```
we will have 3 indexes total (a primary as well as two unique secondary indexes). If we examine the descriptor of `t_b_key` unique secondary index we will see that it's incorrectly thinking that it is using the PrimaryIndexEncoding
```
      {
          "columnDirections": [
              "ASC"
          ],
          "columnIds": [
              2
          ],
          "columnNames": [
              "b"
          ],
...
          "encodingType": 1,
          "extraColumnIds": [
              1
          ],
...
          "id": 5,
...
          "name": "t_b_key",
...
      }
```
Versions 21.2 and newer don't have this problem

**Comment by ajwerner** [comment] 2021-10-13 23:22
The problem is that we used to just copy the old primary index and then modify it:

https://github.com/cockroachdb/cockroach/blob/a6daab16ee8a1c15abc4c4a8a425e46d12033b5c/pkg/sql/alter_primary_key.go#L396

We fixed this in https://github.com/cockroachdb/cockroach/pull/66599.
https://github.com/cockroachdb/cockroach/blob/c90895943b99f098892320328b603e890f3f1abd/pkg/sql/alter_primary_key.go#L407

This issue asks for a migration to fix up these secondary indexes. Fortunately they are easy to detect.

**Comment by postamar** [comment] 2021-11-09 01:55
@yuzefovich I've been looking at this issue, as you can tell from the noise, and I've reached a point where I realize I don't _really_ understand what it means for an index descriptor to have an encoding type set one way or another.

> If we examine the descriptor of t_b_key unique secondary index we will see that it's incorrectly thinking that it is using the PrimaryIndexEncoding

Could you clarify what you mean by that, especially the word "incorrectly"? The index really is using the `PrimaryIndexEncoding`. It's doing so by mistake, but that's really what's happening.

**Comment by postamar** [comment] 2021-11-09 01:59
I plan to do a fix for 21.1 and 20.2 in which ALTER PRIMARY KEY creates the unique index using the correct encoding types and format versions, but until proven otherwise I'm going to assume there are clusters out there for which some tables have secondary indexes with encoding type set to `PrimaryIndexEncoding`.

**Comment by yuzefovich** [comment] 2021-11-09 02:24
The actual data in the index in this case is correctly encoded using `SecondaryIndexEncoding`; however, the descriptor _incorrectly_ says that the encoding is `PrimaryIndexEncoding`. So the problem is only limited to a descriptor not matching the actual state of things - no data migration is needed. This matters since we definitely look at the encoding type coming from the descriptor during the execution, e.g.: https://github.com/cockroachdb/cockroach/blob/c297b73ffd7df6341dc255dbbbdb3c09e886ae71/pkg/sql/colfetcher/cfetcher.go#L1073

If you wanna see more, you could take a look at https://github.com/cockroachlabs/support/issues/1278#issuecomment-942651742 (note that you'll have to look at the version before last, which I modified).

**Comment by postamar** [comment] 2021-11-09 02:31
> The actual data in the index in this case is correctly encoded using SecondaryIndexEncoding

That's... surprising! I'm not doubting it, but I do find it weird that, evidently, the encoding type is ignored when backfilling the index. I would expect the value returned by `GetEncodingType()` to be the source of truth here. I assume that this is not the case due to historical reasons.

**Comment by yuzefovich** [comment] 2021-11-09 02:34
>> The actual data in the index in this case is correctly encoded using `SecondaryIndexEncoding`

> That's... surprising!

Hm, I guess it might be good for you to double-check this, just in case :)

**Comment by postamar** [comment] 2021-11-09 14:05
I looked into this further and as far as I can tell, INSERTs will behave according the encoding type:
https://github.com/cockroachdb/cockroach/blob/c4bb04b063bf6f18e765660b4ecb8b85de9639f5/pkg/sql/rowenc/index_encoding.go#L1115-L1118
This would mean that if a populated index built using `PrimaryIndexEncoding` has its descriptor changed such that encoding type is set to `SecondaryIndexEncoding`, subsequent inserts causes us to have the old rows encoded using `EncodePrimaryIndex` and the new rows using `EncodeSecondaryIndex`.

Now, I ran cockroach demo on 21.1 and tried to blow it up, by creating and modifying a table `t` as in the issue description, doing some descriptor surgery to change the encoding type of `t_b_key` and INSERTing to the table both before and after the surgery. Nothing happens. Could it be that `PrimaryIndexEncoding` is backward-compatible with `SecondaryIndexEncoding`? The opposite is definitely not true, I did surgery on `t_a_key` to set its encoding type to primary and a `SELECT * FROM t@t_a_key` would blow up.

**Comment by yuzefovich** [comment] 2021-11-09 16:17
> Could it be that `PrimaryIndexEncoding` is backward-compatible with `SecondaryIndexEncoding`?

Unfortunately, I dunno - the tech note doesn't offer much explanation about the differences between two encoding types, and I'm not too familiar with the code either. Pinging @jordanlewis and @RaduBerinde in case one of you remembers what is the difference between two encoding types for the secondary indexes.

**Comment by postamar** [comment] 2021-11-24 22:02
I'll close this for the time being, feel free to re-open if need be.

**Closed by postamar** 2021-11-24 22:02 UTC
Labels: C-cleanup, T-sql-schema
