### ISSUE TITLE
pgwire: binary encoding for int2/int4 should use fewer bytes than 8

### ISSUE THREAD

**Issue by mguillemot-tel** [cockroachdb/cockroach#34730] opened 2019-02-08 03:53 UTC
**Describe the problem**

I'm accessing CockroachDB in a Rust program using the `diesel` crate with the standard Postgres driver. 

When I try to read tables using INT2 or INT4 (mapped to `i16` or `i32` respectively), the driver raises an error `Received more than 2 bytes decoding i16. Was an Integer expression accidentally identified as SmallInt?`. If I map those fields to a `i64` in my code, then it works properly.

This also seems to have happened to nocduro as mentioned in this comment: https://github.com/cockroachdb/cockroach/issues/26925#issuecomment-441139298

**To Reproduce**

Here is a simple repro that demonstrates the issue: https://github.com/mguillemot-tel/cockroack-diesel-int-size-issue

(It has the instructions to run the code in the README.)

**Expected behavior**

So it seems to me that the Rust postgres driver is expecting a `INT2` to be sent using only 2 bytes, and a `INT4` to be sent using only 4 bytes, and complaining that it receives 8 bytes in both cases.

I'm not sure if it a violation of the postgres wire protocol to send a smaller INTn as INT8, but definitely CockroachDB is at least behaving differently from PostgreSQL in this scenario.

**Environment:**
 - CockroachDB version: 2.1.4
 - Server OS: using the official Docker image `cockroachdb/cockroach:v2.1.4`
 - Client app: Rust nightly, using the `diesel` crate version 1.4.0

**Comment by knz** [comment] 2019-02-11 13:05
@mguillemot-tel good catch! We're in the process of refining our handling of the INT type variants internally, but we hadn't yet caught on the fact that the binary protocol was also affected. This is news to us (or rather, we hadn't realized).

@bobvawter @mjibson we'll need to give the int values also the proper width in pgwire, it seems.

@mguillemot-tel the workaround for the time being is indeed to expect 64bit integers in results. Another alternative is to require `diesel` to use the text encoding instead of binary, where the error should not happen. (If that's an option).

Thanks again!

**Comment by mjibson** [comment] 2019-02-20 20:14
Did some experiments. This can be fixed by using `wrapWithOid` in `PerformCast`, so that a CastExpr node eval returns a oidwrapper instead of a DInt. We think it's too late in the cycle to make that change now, though, because our current int and datum handling isn't great. We do type assertions in various places, and it's not clear if this change would stop some things from working or trigger panics, maybe in new edge cases that were previously untested (we don't do much int2/int4 testing since it's little more than a name alias).

Furthermore, wrapping the type like that raises some questions: should our add operator change when adding an int2 + int8? What about int2 + int2? If we are actually propagating int types around, we should probably (?) actually enforce the 2-byte range limitation, which we don't do.

For this release I think this will be a known limitation. We hope to have a larger internal type overhaul in the next release that will fix this class of bug.

**Comment by knz** [comment] 2019-02-21 10:59
I don't think that `wrapWithOid` and `DOidWrapper` are a fruitful avenue for this change.

What we need to do is to stop using the Go `Datum` implementation type as the SQL type information, and instead use a separate type annotation (like the other Expr nodes). This way `DInt` can separately use `Int2`, `Int8` or `Int4` depending on context.

This is a more involved change since it touches a lot of layers of scalar expression typing and evaluation. However it seems to be unavoidable. We should consider the ideas in the "sql leaf data" RFC (`20170926_sql_aux_data.md`)

**Comment by jordanlewis** [comment] 2019-05-03 16:00
@mguillemot-tel thanks for filing! I'm closing this as a duplicate of #36811, which is where we're centralizing this discussion. Please follow that issue for more.

**Closed by jordanlewis** 2019-05-03 16:00 UTC
Labels: A-sql-datatypes, A-sql-pgcompat, C-bug
