### ISSUE TITLE
stability: panic on RangeLookup dispatched to correct range

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6000] opened 2016-04-12 13:45 UTC
build sha: c382dd7
Beta cluster with photos + block_writer load. Restarted from scratch earlier today.

~1h after a restart, encountered the following:
```
panic: RangeLookup dispatched to correct range, but no matching RangeDescriptor was found: /Meta2/Table/55/1/8752590996753796817/"88e08dd7-d1b6-4aeb-ad46-1880b351e731"/6611/0

1: running [Created by grpc.(*Server).serveStreams.func1 @ server.go:324]
              panic.go:464            panic(#1, #18)
    storage   store.go:1557           (*Store).Send.func1(0xc833bd1258, 0xc833bd12c8, 0x14449b721ca69e59, 0, 0xc833bd12c0, #5)
              panic.go:426            panic(#1, #18)
    storage   replica_command.go:909  (*Replica).RangeLookup(#12, #19, #9, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
    storage   replica_command.go:129  (*Replica).executeCmd(#12, #20, #17, 0, 0, 0, #19, #9, 0, #22, ...)
    storage   replica.go:1784         (*Replica).executeBatch(#12, #20, #17, 0, 0, #19, #9, 0, #22, 0, ...)
    storage   replica.go:1071         (*Replica).addReadOnlyCmd(#12, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
    storage   replica.go:765          (*Replica).Send(#12, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
    storage   store.go:1639           (*Store).Send(#5, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
    storage   stores.go:177           (*Stores).Send(#6, #20, 0xc82bb06c30, 0, 0, #4, 0x4, 0x1, 0, 0, ...)
    server    node.go:729             (*Node).Batch.func2()
    stop      stopper.go:166          (*Stopper).RunTask(#8, 0xc833bd1870, 0)
    server    node.go:741             (*Node).Batch(#7, #20, #16, 0xc8271b2150, 0, 0, 0)
    roachpb   api.pb.go:1306          _Internal_Batch_Handler(#2, #7, #20, #16, 0xc833082a00, 0, 0, 0, 0)
    grpc      server.go:497           (*Server).processUnaryRPC(#11, #21, #14, #15, #10, #3, 0, 0, 0)
    grpc      server.go:646           (*Server).handleStream(#11, #21, #14, #15, 0)
    grpc      server.go:323           (*Server).serveStreams.func1.1(#13, #11, #21, #14, #15)
```

Full log (from `ec2-52-91-234-29.compute-1.amazonaws.com`):
[node4.log.parse.txt](https://github.com/cockroachdb/cockroach/files/215109/node4.log.parse.txt)

**Comment by tschottdorf** [comment] 2016-04-12 13:47
Could you save the data? Only that node is ok. Please don't restart (you
can after taking the dump, but it'll likely happen again).

On Tue, Apr 12, 2016 at 9:45 AM marc <notifications@github.com> wrote:

> build sha: c382dd7
> <https://github.com/cockroachdb/cockroach/commit/c382dd7589cc9dfed7b5023008058e8845ecdaf7>
> Beta cluster with photos + block_writer load. Restarted from scratch
> earlier today.
>
> ~1h after a restart, encountered the following:
>
> panic: RangeLookup dispatched to correct range, but no matching RangeDescriptor was found: /Meta2/Table/55/1/8752590996753796817/"88e08dd7-d1b6-4aeb-ad46-1880b351e731"/6611/0
>
> 1: running [Created by grpc.(*Server).serveStreams.func1 @ server.go:324]
>               panic.go:464            panic(#1, #18)
>     storage   store.go:1557           (*Store).Send.func1(0xc833bd1258, 0xc833bd12c8, 0x14449b721ca69e59, 0, 0xc833bd12c0, #5)
>               panic.go:426            panic(#1, #18)
>     storage   replica_command.go:909  (*Replica).RangeLookup(#12, #19, #9, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
>     storage   replica_command.go:129  (*Replica).executeCmd(#12, #20, #17, 0, 0, 0, #19, #9, 0, #22, ...)
>     storage   replica.go:1784         (*Replica).executeBatch(#12, #20, #17, 0, 0, #19, #9, 0, #22, 0, ...)
>     storage   replica.go:1071         (*Replica).addReadOnlyCmd(#12, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
>     storage   replica.go:765          (*Replica).Send(#12, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
>     storage   store.go:1639           (*Store).Send(#5, #20, #17, #22, 0, #4, 0x4, 0x1, 0, 0, ...)
>     storage   stores.go:177           (*Stores).Send(#6, #20, 0xc82bb06c30, 0, 0, #4, 0x4, 0x1, 0, 0, ...)
>     server    node.go:729             (*Node).Batch.func2()
>     stop      stopper.go:166          (*Stopper).RunTask(#8, 0xc833bd1870, 0)
>     server    node.go:741             (*Node).Batch(#7, #20, #16, 0xc8271b2150, 0, 0, 0)
>     roachpb   api.pb.go:1306          _Internal_Batch_Handler(#2, #7, #20, #16, 0xc833082a00, 0, 0, 0, 0)
>     grpc      server.go:497           (*Server).processUnaryRPC(#11, #21, #14, #15, #10, #3, 0, 0, 0)
>     grpc      server.go:646           (*Server).handleStream(#11, #21, #14, #15, 0)
>     grpc      server.go:323           (*Server).serveStreams.func1.1(#13, #11, #21, #14, #15)
>
> Full log (from ec2-52-91-234-29.compute-1.amazonaws.com):
> node4.log.parse.txt
> <https://github.com/cockroachdb/cockroach/files/215109/node4.log.parse.txt>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cockroachdb/cockroach/issues/6000>
>
-- 

-- Tobias

**Comment by mberhault** [comment] 2016-04-12 13:54
yeah, it's still down, but I'm backing up with suffix `.6000` on `ec2-52-91-234-29.compute-1.amazonaws.com`

**Comment by tamird** [comment] 2016-07-02 01:53
Is this data still available somewhere?

**Comment by tamird** [comment] 2016-10-04 01:23
This looks like a meta2 gap? Closing as dupe of #9265.

**Closed by tamird** 2016-10-04 01:23 UTC
Labels: stability
