### ISSUE TITLE
sql: SQL client responses take a while on Fedora

### ISSUE THREAD

**Issue by ggitau** [cockroachdb/cockroach#6853] opened 2016-05-23 06:18 UTC
```
cockroach version
Build Tag:   beta-20160414
Build Time:  2016/04/14 15:15:52
Platform:    linux amd64
Go Version:  go1.6
C Compiler:  gcc 4.9.2
```

On fedora 22 interactions with the sql client take too long..an average of 3 minutes. I ran show databases. It took about 3 minutes before listing the databases.

**Comment by petermattis** [comment] 2016-05-23 12:24
@ggitau Wow, that latency is excessive. Can you show the exact commands you're running? Does "sql client" mean you're using `cockroach sql` or something else?

**Comment by ggitau** [comment] 2016-05-23 14:39
@petermattis Yes..I was referring to interactions from `cockroach sql` . I ran the following commands

-    ` cockroach sql --ca-cert=/etc/cockroachdb/certs/ca.cert --cert=/etc/cockroachdb/certs/root.cert --key=/etc/cockroachdb/certs/root.key`
- `show databases`

**Comment by tamird** [comment] 2016-05-23 14:48
@ggitau can you also provide the options you passed to `cockroach start`? our issue template asks for lots more information than you provided.

Also, in this particular case, could you provide the output of `uname -a`? Are you running in a VM, docker, or some combination thereof?

**Comment by ggitau** [comment] 2016-05-23 15:06
@tamird  sorry about that. Thought I covered all the points. 

- Options passed 
 `-ca-cert=/etc/cockroachdb/certs/ca.cert --cert=/etc/cockroachdb/certs/node.cert --key=/etc/cockroachdb/certs/node.key --store=/var/data/cockroachdb/ --port=26257 --http-port=7005`

- Output of uname -a
 `Linux mandk 4.4.9-200.fc22.x86_64 #1 SMP Fri May 6 17:42:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I am running in a VM.

**Comment by ggitau** [comment] 2016-05-23 15:10
@tamird  sorry about that. Thought I covered all the points. 

- Options passed 
 `-ca-cert=/etc/cockroachdb/certs/ca.cert --cert=/etc/cockroachdb/certs/node.cert --key=/etc/cockroachdb/certs/node.key --store=/var/data/cockroachdb/ --port=26257 --http-port=7005`

- Output of uname -a
 `Linux mandk 4.4.9-200.fc22.x86_64 #1 SMP Fri May 6 17:42:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I am running in a VM.

**Comment by petermattis** [comment] 2016-05-23 15:15
@ggitau This is going to be difficult for us to debug. Can you try running outside of a VM? And try running without security (i.e. pass the `--insecure` flag to `cockroach start`). A ~3min latency for `show databases` is indicating that there is something really bad going on in your setup. FWIW, I have never seen such latencies before and everything works quickly when I tried it just now (using `cockroach sql -e "show databases"`).

**Comment by ggitau** [comment] 2016-05-24 08:07
@petermattis Still haven't set up outside a VM but after creating a my first database, everything seems to work just fine. The latency is there before creating a new database. Will see how it works outside a VM.

**Comment by petermattis** [comment] 2016-05-24 12:29
@ggitau I'm not able to think of a reason creating a database would make a difference to subsequent `show databases` queries.

**Comment by ggitau** [comment] 2016-05-24 14:48
@petermattis I think something is wrong with the VM. Am getting timeouts on etcd as well.

**Comment by knz** [comment] 2016-08-03 18:29
Hi @ggitau, have you been able to make progress with this issue since? We've been running tests on our side and were not able to reproduce the issue you reported. How can we help you further on this?

**Comment by ggitau** [comment] 2016-08-04 04:49
@knz sorry for the delayed response. The server was the one at fault. Anything listening on localhost was timing out; not just cockroachdb

**Comment by knz** [comment] 2016-08-04 09:15
Thanks for your feedback. then I will close this issue for now. Feel free to contact us again if you need more help!

**Closed by knz** 2016-08-04 09:15 UTC
