### ISSUE TITLE
opt: contradictions from check constraints should be used for optimization

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#80304] opened 2022-04-21 14:28 UTC
Similar to #80187, we should detect when contradictions exist for check constraints and change the query plan to an empty values clause. For example:
```
exec-ddl
CREATE TABLE t (
  k INT PRIMARY KEY,
  a INT,
  CHECK (a > 0)
)
----

opt
SELECT * FROM t WHERE a = 0
----
select
 ├── columns: k:1!null a:2!null
 ├── key: (1)
 ├── fd: ()-->(2)
 ├── scan t
 │    ├── columns: k:1!null a:2
 │    ├── key: (1)
 │    └── fd: (1)-->(2)
 └── filters
      └── a:2 = 0 [outer=(2), constraints=(/2: [/0 - /0]; tight), fd=()-->(2)]
```
The optimizer should replace the `Select` and `Scan` with an empty values clause here, since the predicate `a = 0` contradicts the check constraint `a > 0`.

Jira issue: CRDB-15776

**Comment by mgartner** [comment] 2022-06-22 00:06
Duplicate of #63112.

**Closed by mgartner** 2022-06-22 00:06 UTC
Labels: C-enhancement, T-sql-queries, E-quick-win
