### ISSUE TITLE
sql: ADD COLUMN with some DEFAULT values does not work

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#22508] opened 2018-02-08 17:18 UTC
```
statement ok
CREATE SEQUENCE initial_seq

statement error cannot backfill such sequence operation
ALTER TABLE add_default ADD g INT DEFAULT nextval('initial_seq')

statement error cannot backfill such evaluated expression
ALTER TABLE add_default ADD g OID DEFAULT 'foo'::regclass::oid

statement error cannot backfill such evaluated expression
ALTER TABLE add_default ADD g INT DEFAULT 'foo'::regtype::INT
```

**Comment by jseldess** [comment] 2018-04-02 01:57
Documented as known limitation in https://github.com/cockroachdb/docs/pull/2823.

**Comment by jordanlewis** [comment] 2020-03-31 04:39
Duplicate of #42508. Also, this does work if the table is empty if it's any consolation. Probably not much of one.

**Closed by jordanlewis** 2020-03-31 04:39 UTC
Labels: A-schema-changes, C-bug
