### ISSUE TITLE
opt: v23.1.12: index out of range in groupByColumns

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#113900] opened 2023-11-06 20:50 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/4606960092/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/4606960092/?referrer=webhooks_plugin)

Panic Message:

```
catch.go:29: runtime error: index out of range [0] with length 0
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/util/errorutil.ShouldCatch
  | 	github.com/cockroachdb/cockroach/pkg/util/errorutil/catch.go:29
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.getResultColumns.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:33
  | runtime.gopanic
  | 	GOROOT/src/runtime/panic.go:890
  | runtime.goPanicIndex
  | 	GOROOT/src/runtime/panic.go:113
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.groupByColumns
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:261
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.getResultColumns
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/result_columns.go:99
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.newNode
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/explain_factory.go:96
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.(*PlanGistFactory).decodeOperatorBody
  | 	github.com/cockroachdb/cockroach/bazel-out/k8-opt/bin/pkg/sql/opt/exec/explain/plan_gist_factory.og.go:1193
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.(*PlanGistFactory).decodeOp
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:240
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.DecodePlanGistToPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:213
  | github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain.DecodePlanGistToRows
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/exec/explain/plan_gist_factory.go:181
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).DecodeGist
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:728
  | github.com/cockroachdb/cockroach/pkg/sql/sem/builtins.(*gistPlanGenerator).Start
  | 	github.com/cockroachdb/cockroach/pkg/sql/sem/builtins/generator_builtins.go:630
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).nextInputRow
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:209
  | github.com/cockroachdb/cockroach/pkg/sql/rowexec.(*projectSetProcessor).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/rowexec/project_set.go:291
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:128
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).nextAdapter
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:145
  | github.com/cockroachdb/cockroach/pkg/sql/colexecerror.CatchVectorizedRuntimeError
  | 	github.com/cockroachdb/cockroach/pkg/sql/colexecerror/error.go:92
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*FlowCoordinator).Next
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:150
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/base.go:193
  | github.com/cockroachdb/cockroach/pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/execinfra/processorsbase.go:726
  | github.com/cockroachdb/cockroach/pkg/sql/flowinfra.(*FlowBase).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/flowinfra/flow.go:580
  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:313
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:902
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1912
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1644
  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunAll
  | 	github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1647
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2153
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1707
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1036
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:142
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3083
Wraps: (3) runtime error: index out of range [0] with length 0
  | -- cause hidden behind barrier
  | runtime error: index out of range [0] with length 0
  | (1) runtime error: index out of range [0] with length 0
  | Error types: (1) runtime.boundsError
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *barriers.barrierErr
-- report composition:
*barriers.barrierErr: masked error: runtime error: index out of range [0] with length 0
catch.go:29: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L3082-L3084](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L3082-L3084)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L141-L143](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L141-L143)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1035-L1037](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1035-L1037)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1706-L1708](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L1706-L1708)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L2152-L2154](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/conn_executor_exec.go#L2152-L2154)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1646-L1648](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1646-L1648)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1643-L1645](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1643-L1645)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1911-L1913](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L1911-L1913)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L901-L903](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/distsql_running.go#L901-L903)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/vectorized_flow.go#L312-L314](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/vectorized_flow.go#L312-L314)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/flowinfra/flow.go#L579-L581](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/flowinfra/flow.go#L579-L581)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/execinfra/processorsbase.go#L725-L727](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/execinfra/processorsbase.go#L725-L727)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/execinfra/base.go#L192-L194](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/execinfra/base.go#L192-L194)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L149-L151](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L149-L151)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colexecerror/error.go#L91-L93](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colexecerror/error.go#L91-L93)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L127-L129](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/colflow/flow_coordinator.go#L127-L129)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/rowexec/project_set.go#L290-L292](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/rowexec/project_set.go#L290-L292)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/rowexec/project_set.go#L208-L210](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/rowexec/project_set.go#L208-L210)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/sem/builtins/generator_builtins.go#L629-L631](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/sem/builtins/generator_builtins.go#L629-L631)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L727-L729](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/plan_opt.go#L727-L729)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L180-L182](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L180-L182)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L212-L214](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L212-L214)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L239-L241](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/plan_gist_factory.go#L239-L241)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/bazel-out/k8-opt/bin/pkg/sql/opt/exec/explain/plan_gist_factory.og.go#L1192-L1194](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/bazel-out/k8-opt/bin/pkg/sql/opt/exec/explain/plan_gist_factory.og.go#L1192-L1194)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/explain_factory.go#L95-L97](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/explain_factory.go#L95-L97)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L98-L100](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L98-L100)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L260-L262](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L260-L262)
[GOROOT/src/runtime/panic.go#L112-L114](GOROOT/src/runtime/panic.go#L112-L114)
[GOROOT/src/runtime/panic.go#L889-L891](GOROOT/src/runtime/panic.go#L889-L891)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L32-L34](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/sql/opt/exec/explain/result_columns.go#L32-L34)
[https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/util/errorutil/catch.go#L28-L30](https://github.com/cockroachdb/cockroach/blob/fb1ed73d9d88f459c3cda5866fae29831cce06b4/pkg/util/errorutil/catch.go#L28-L30)
</details>

```
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3083
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 142
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1036
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1707
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithDistSQLEngine at line 2153
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll at line 1647
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRunAll.func3 at line 1644
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).PlanAndRun at line 1912
pkg/sql/distsql_running.go in pkg/sql.(*DistSQLPlanner).Run at line 902
pkg/sql/colflow/vectorized_flow.go in pkg/sql/colflow.(*vectorizedFlow).Run at line 313
pkg/sql/flowinfra/flow.go in pkg/sql/flowinfra.(*FlowBase).Run at line 580
pkg/sql/execinfra/processorsbase.go in pkg/sql/execinfra.(*ProcessorBaseNoHelper).Run at line 726
pkg/sql/execinfra/base.go in pkg/sql/execinfra.Run at line 193
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).Next at line 150
pkg/sql/colexecerror/error.go in pkg/sql/colexecerror.CatchVectorizedRuntimeError at line 92
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).nextAdapter at line 145
pkg/sql/colflow/flow_coordinator.go in pkg/sql/colflow.(*FlowCoordinator).next at line 128
pkg/sql/rowexec/project_set.go in pkg/sql/rowexec.(*projectSetProcessor).Next at line 291
pkg/sql/rowexec/project_set.go in pkg/sql/rowexec.(*projectSetProcessor).nextInputRow at line 209
pkg/sql/sem/builtins/generator_builtins.go in pkg/sql/sem/builtins.(*gistPlanGenerator).Start at line 630
pkg/sql/plan_opt.go in pkg/sql.(*planner).DecodeGist at line 728
pkg/sql/opt/exec/explain/plan_gist_factory.go in pkg/sql/opt/exec/explain.DecodePlanGistToRows at line 181
pkg/sql/opt/exec/explain/plan_gist_factory.go in pkg/sql/opt/exec/explain.DecodePlanGistToPlan at line 213
pkg/sql/opt/exec/explain/plan_gist_factory.go in pkg/sql/opt/exec/explain.(*PlanGistFactory).decodeOp at line 240
bazel-out/k8-opt/bin/pkg/sql/opt/exec/explain/plan_gist_factory.og.go in pkg/sql/opt/exec/explain.(*PlanGistFactory).decodeOperatorBody at line 1193
pkg/sql/opt/exec/explain/explain_factory.go in pkg/sql/opt/exec/explain.newNode at line 96
pkg/sql/opt/exec/explain/result_columns.go in pkg/sql/opt/exec/explain.getResultColumns at line 99
pkg/sql/opt/exec/explain/result_columns.go in pkg/sql/opt/exec/explain.groupByColumns at line 261
GOROOT/src/runtime/panic.go in runtime.goPanicIndex at line 113
GOROOT/src/runtime/panic.go in runtime.gopanic at line 890
pkg/sql/opt/exec/explain/result_columns.go in pkg/sql/opt/exec/explain.getResultColumns.func1 at line 33
pkg/util/errorutil/catch.go in pkg/util/errorutil.ShouldCatch at line 29
```

### Tags

| Tag | Value |
| --- | --- |
| Command | mt start-sql |
| Environment | v23.1.12 |
| Go Version | go1.19.13 |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v23.1.11-596-gfb1ed73d9d8 |
| Cockroach SHA | fb1ed73d9d88f459c3cda5866fae29831cce06b4 |
| # of CPUs | 32 |
| # of Goroutines | 318 |

Jira issue: CRDB-33249

**Comment by mgartner** [comment] 2024-01-09 19:51
Possible duplicate of #111346.

**Comment by rytaft** [comment] 2024-01-10 19:20
https://github.com/cockroachdb/cockroach/pull/111347 has been backported.

**Closed by rytaft** 2024-01-10 19:20 UTC
Labels: C-bug, O-sentry, T-sql-queries
