### ISSUE TITLE
Update schema statements not finished and lock table

### ISSUE THREAD

**Issue by ikgo** [cockroachdb/cockroach#49876] opened 2020-06-04 19:07 UTC
**Describe the problem**

we running schema change statements, add column, on same table. all jobs in running state but never ends.
this happening second time on production, but never in testing environment.
cockoach running in k8s in both environments.
after this happening the table locked and not possible run any schema changes.

**To Reproduce**

Run several schema changes with `alter table add column`
What did you do? Describe in your own words.

**Expected behavior**
how can we unlock table for schema updates?   
statement fail, possible run it again   

**Additional data / screenshots**
**show jobs**
last 4 jobs we stop manually, but this not unlock table
first 2 still running
```
561029020001009668	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS test_test_2 INT8		root	running		2020-06-04 15:01:09	2020-06-04 15:01:10		2020-06-04 15:01:09	0.0		4
561027487566168069	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS prefered_blend_count INT8 DEFAULT 15		root	running		2020-06-04 14:53:21	2020-06-04 14:53:23		2020-06-04 14:53:21	0.0		5
561006448969023493	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS daily_cap INT8		mobco	failed		2020-06-04 13:06:21	2020-06-04 14:20:06	2020-06-04 14:20:06	2020-06-04 13:06:21	0.0	job 561006448969023493: cannot be reverted, manual cleanup may be required: job failed but had no recorded error	4
561009174088712198	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS coverage_type INT8		mobco	failed		2020-06-04 13:20:12	2020-06-04 14:20:06	2020-06-04 14:20:06	2020-06-04 13:20:12	0.0	job 561009174088712198: cannot be reverted, manual cleanup may be required: job failed but had no recorded error	4
561010910477778950	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS min_clicks_traffic_back INT8 DEFAULT 5000		mobco	failed		2020-06-04 13:29:02	2020-06-04 14:20:06	2020-06-04 14:20:06	2020-06-04 13:29:02	0.0	job 561010910477778950: cannot be reverted, manual cleanup may be required: job failed but had no recorded error	4
561009188814520326	SCHEMA CHANGE	ALTER TABLE mobco.public.campaign_sources ADD COLUMN IF NOT EXISTS campaign_algorithm INT8		mobco	failed		2020-06-04 13:20:17	2020-06-04 14:20:06	2020-06-04 14:20:06	2020-06-04 13:20:17	0.0	job 561009188814520326: cannot be reverted, manual cleanup may be required: job failed but had no recorded error	4
```
**crdb_internal.schema_changes**
```
157	61	campaigns	COLUMN	15	daily_cap	DELETE_ONLY	ADD
157	61	campaigns	COLUMN	16	coverage_type	DELETE_ONLY	ADD
157	61	campaigns	COLUMN	17	min_clicks_traffic_back	DELETE_ONLY	ADD
157	61	campaigns	COLUMN	18	prefered_blend_count	DELETE_ONLY	ADD
157	61	campaigns	COLUMN	19	test_test_2	DELETE_ONLY	ADD
158	61	campaign_sources	COLUMN	17	campaign_algorithm	DELETE_ONLY	ADD
```

**Environment:**
 - CockroachDB version [e.g. 20.1.0]
 - Server OS: cockroach docker on k8s, 3 nodes
 - Client app golang `ithub.com/lib/pq v1.5.2`

**Comment by ajwerner** [comment] 2020-06-04 19:31
> 561006448969023493	SCHEMA CHANGE	ALTER TABLE mobco.public.campaigns ADD COLUMN IF NOT EXISTS daily_cap INT8		mobco	failed		2020-06-04 13:06:21	2020-06-04 14:20:06	2020-06-04 14:20:06	2020-06-04 13:06:21	0.0	job 561006448969023493: cannot be reverted, manual cleanup may be required: job failed but had no recorded error	4

I find this to be relatively concerning. Is there any chance you'd feel comfortable sharing a debug zip (privately) or, if that's not okay, would be willing to collect your logs from `2020-06-04 13:20:1` to `2020-06-04 15:01:10` and see if there's anything interested (realistically the more you could share the better but I understand reasons to limit private info).

**Comment by ikgo** [comment] 2020-06-04 19:36
No a problem to share.
how I create debug zip?

**Comment by ajwerner** [comment] 2020-06-04 20:02
https://www.cockroachlabs.com/docs/stable/cockroach-debug-zip.html

**Comment by ikgo** [comment] 2020-06-04 20:37
how can I share it with you?

**Comment by ajwerner** [comment] 2020-06-04 20:40
In the past sharing through google drive has worked well for similar things  (ajwerner@cockroachlabs.com). If it's small enough you could try emailing it to me though I understand that the zip is often above the size limit for many email providers. 

I'm open to other suggestions and if we can't come up with something easy, I'll ask around. I know we have a tool to upload to our support portal but I don't quite know how to make that available to you.

**Comment by ajwerner** [comment] 2020-06-05 01:59
There are a few scary and unexpected things going on here at a first glance. I'm just posting some notes without any clue of root cause or what's going on.

1) There's a ton of logging of a warning I've never seen.
`> W200407 23:07:46.135694 724664 storage/engine/mvcc.go:2554  [n5,s5,r41574/3:/Table/188/1/96{2924-3613}] unable to find value for /Table/188/1/963030/0 @ 1585998224.231238311,2 (txn:<id:db78a54f-9d56-41f9-b936-b1a665f2897b key:"\366\274\211\370#\336I\210" timestamp:<wall_time:1586300652611544554 > min_timestamp:<wall_time:1586300652611544554 > priority:804806 sequence:4222 > timestamp:<wall_time:1586300652611544554 logical:0 > deleted:false key_bytes:12 val_bytes:743  vs {ID:e960d0b2-48c8-480a-b3b6-c0ddd1da32c2 Key:[246 188 137 248 35 253 195 136] Epoch:0 Timestamp:1585998224.231238311,2 MinTimestamp:1585998132.748620161,0 Priority:168156 Sequence:372428})`

https://github.com/cockroachdb/cockroach/blob/4f36d0c62435596ca103454e113ebe8e55f005de/pkg/storage/engine/mvcc.go#L2513-L2525

This seems to be related to https://github.com/cockroachdb/cockroach/issues/9399 but I'm not clear that this case should ever happen and there's a *ton* of it going on (358825 times to be exact).

I'm not clear on whther this is actually a problem.

2) At some point the nodes become 20.1.0 

There are lots of random warnings that I assume have to do with one of the sqlmigrations. In particular the schema changer freaks out about the validity of some tables it finds.

```
gke-mobco-cluster-pool-data-3eafaae5-wv28> E200604 14:17:36.363613 1989 sql/schema_changer.go:2165  [n6] /Table/3/1/31/2/1: received invalid table descriptor: no allowed privileges found for system object with ID=31. Desc: name:"protected_ts_meta" id:31 parent_id:1 version:1 modification_time:<> columns:<name:"singleton" id:1 type:<InternalType:<family:BoolFamily width:0 precision:0 locale:"" visible_type:0 oid:16 > > nullable:false default_expr:"true" hidden:false > columns:<name:"version" id:2 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 > > nullable:false hidden:false > columns:<name:"num_records" id:3 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 > > nullable:false hidden:false > columns:<name:"num_spans" id:4 type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 > > nullable:false hidden:false > columns:<name:"total_bytes" id:5
type:<InternalType:<family:IntFamily width:64 precision:0 locale:"" visible_type:0 oid:20 > > nullable:false hidden:false > next_column_id:6 families:<name:"primary" id:0 column_names:"singleton" column_names:"version" column_names:"num_records" column_names:"num_spans" column_names:"total_bytes" column_ids:1 column_ids:2 column_ids:3 column_ids:4 column_ids:5 default_column_id:0 > next_family_id:1 primary_index:<name:"primary" id:1 unique:true column_names:"singleton" column_directions:ASC column_ids:1 foreign_key:<table:0 index:0 name:"" validity:Validated shared_prefix_len:0 on_delete:NO_ACTION on_update:NO_ACTION match:SIMPLE > interleave:<> partitioning:<num_columns:0 > type:FORWARD created_explicitly:false > next_index_id:2 privileges:<users:<user:"admin" privileges:0 > users:<user:"root" privileges:0 > > next_mutation_id:1 format_version:3 state:PUBLIC offline_reason:"" checks:<expr:"singleton" name:"check_singleton" validity:Validated column_ids:1
is_non_null_constraint:false > view_query:"" drop_time:0 replacement_of:<id:0 time:<> > audit_mode:DISABLED drop_job_id:0 create_query:"" create_as_of_time:<>      
```

At first I thought it was just something I did with the `protected_ts` tables but it seems to happen on a bunch of tables:

`statement_bundle_chunks`, `statement_diagnostics_requests`, `statement_diagnostics`, `namespace2`, `role_options`

My guess is that it's just all of the new ones and something perhaps about how we add them?

3) Then, and I think this is part of the smoking gun, we see some jobs fail for reasons I don't know about:

`> E200604 14:20:06.959069 272085 jobs/registry.go:952  [n4] job 561009188814520326: adoption completed with error job 561009188814520326: cannot be reverted, manual cleanup may be required: job failed but had no recorded error`
`> E200604 14:20:06.969959 272162 jobs/registry.go:952  [n4] job 561010910477778950: adoption completed with error job 561010910477778950: cannot be reverted, manual cleanup may be required: job failed but had no recorded error`
`> E200604 14:20:06.989841 272198 jobs/registry.go:952  [n4] job 561009174088712198: adoption completed with error job 561009174088712198: cannot be reverted, manual cleanup may be required: job failed but had no recorded error`
`> E200604 14:20:07.007311 272187 jobs/registry.go:952  [n4] job 561006448969023493: adoption completed with error job 561006448969023493: cannot be reverted, manual cleanup may be required: job failed but had no recorded error
`

We then proceed to see the following pretty much forever which is indicative of your symptom.

`> E200604 15:00:08.266055 1027649 jobs/registry.go:952  [n5] job 561027487566168069: adoption completed with error job 561027487566168069: schema change
not first in line: restarting in background`


4) One fascinating observation is that the debug zip failed to grab `system.jobs` and `crdb_internal.jobs`

`system.jobs.txt.err.txt`: `pq: query execution canceled due to statement timeout` - no clue what that's about.

-------

Another point is that I think we had intended to disallow schema changes while upgrading from 19.2 to 20.1 but it's not clear that that applies to this set of schema changes (see https://www.cockroachlabs.com/docs/stable/known-limitations.html#dropping-and-renaming-objects-during-an-upgrade-to-v20-1-0).

The `namespace` and `namespace2` tables seem to have the same size. 

So, @lucy-zhang, any thoughts on whether this symptom of these arbitrarily failed jobs is due to the upgrade or should we dig deeper?

Additional context:

These nodes seem to be flapping up and down a ton and the disks seem to be getting crushed. Seems like there's a restart every few minutes. That shouldn't in itself cause problems and indicates that there's a bug somewhere. Just out of curiosity, were you doing mean things to this cluster intentionally? Were you seeing instability that was problematic from the outset?

**Comment by ikgo** [comment] 2020-06-05 09:28
>> were you doing mean things to this cluster intentionally?
was not enough memory and we get unexpected high load

What are your recommendations about the current state of the cluster?

**Comment by ajwerner** [comment] 2020-06-09 16:19
Despite all the above problems, I think the smoking gun here is actually: 

`gke-mobco-cluster-pool-data-3eafaae5-wv28> W200425 14:26:25.229793 653 sql/schema_changer.go:2034  [n6] Error executing schema change: batch timestamp 1587824056.447005684,0 must be after replica GC threshold 1587824072.796741143,0`

In terms of recovery, it's a bit tricky but we can devise something. One option is to copy the data to a new table using `CREATE TABLE AS SELECT` and then drop the old table, then rename the new table to the old table's name. If that is not an option let me know and we can come up with something more bespoke. We have a query inside our schema changer that we expect to not get stuck for 10 minutes. We'd need to handle that error better. I'm still working to understand the exact why of the situation but here we are.

**Comment by ikgo** [comment] 2020-06-09 16:47
thanks a lot. we not planing change shema on near future, so we set for now.
will contact you before next shema change update. we planing change shema
for big table, about 500M records. copy data it's not case.

Please kepp me updated about issue.

best
\ik

**Comment by ajwerner** [comment] 2020-06-09 17:07
My main concern is that you had these periods of unavailability. We seem to be missing some robustness in our schema changer in the face of those long pauses. In general running schema changes over large amounts of data doesn't concern me. It's the fact that you had nodes flopping a bunch that seems to have caused the problems. So long as your cluster seems stable, I wouldn't hesitate to run the schema changes. One thing I will say is that if you are both adding and dropping columns, I'd encourage you to do those as two separate transactions. Do all of the adds in one transaction and then, later, do all of the drops. Rollbacks of drops can cause problems and adds can fail. 

It's worth grouping the adds in a transaction as they'll happen in the same backfill as opposed to individual backfills if you were to do them together. 

I'll be filing an issue for my understanding of the root cause soon.

**Comment by ajwerner** [comment] 2020-07-09 19:58
I'm not sure exactly what happened here. My guess is that there is a strange interaction between either schema changes failing (perhaps due to treating an error as not retriable) or being canceled manually and ultimately bad descriptor state. I'm sorry it took me so long to loop back around. 

We can help with the repair but I don't know that we're going to get to a root cause on this one. I'm closing this as most of this infrastructure has been majorly overhauled since 19.2.

**Closed by ajwerner** 2020-07-09 19:58 UTC
Labels: C-bug, O-community, X-blathers-triaged
