### ISSUE TITLE
stress: failed test in cockroach/kv/kv.test: TestClientNotReady

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5207] opened 2016-03-13 10:36 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b1125fa08614aa770703b67a18dfb9856e2cd4ad

Stress build found a failed test:

```
=== RUN   TestClientNotReady
--- FAIL: TestClientNotReady (0.03s)
	send_test.go:285: kv/send_test.go:264: unexpected error when client was closed: failed to send RPC: too many errors encountered (1 of 1 total): rpc error: code = 2 desc = "grpc: the client connection is closing\n```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
1 runs so far, 0 failures, over 15s
8 runs so far, 0 failures, over 20s
8 runs so far, 0 failures, over 25s
9 runs so far, 0 failures, over 30s
15 runs so far, 0 failures, over 35s
16 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
22 runs so far, 0 failures, over 50s
24 runs so far, 0 failures, over 55s
24 runs so far, 0 failures, over 1m0s
29 runs so far, 0 failures, over 1m5s
32 runs so far, 0 failures, over 1m10s
34 runs so far, 0 failures, over 1m15s
36 runs so far, 0 failures, over 1m20s
40 runs so far, 0 failures, over 1m25s
41 runs so far, 0 failures, over 1m30s
43 runs so far, 0 failures, over 1m35s
47 runs so far, 0 failures, over 1m40s
49 runs so far, 0 failures, over 1m45s
52 runs so far, 0 failures, over 1m50s
55 runs so far, 0 failures, over 1m55s
57 runs so far, 0 failures, over 2m0s
58 runs so far, 0 failures, over 2m5s
63 runs so far, 0 failures, over 2m10s
65 runs so far, 0 failures, over 2m15s
65 runs so far, 0 failures, over 2m20s
71 runs so far, 0 failures, over 2m25s
73 runs so far, 0 failures, over 2m30s
73 runs so far, 0 failures, over 2m35s
77 runs so far, 0 failures, over 2m40s
81 runs so far, 0 failures, over 2m45s
82 runs so far, 0 failures, over 2m50s
85 runs so far, 0 failures, over 2m55s
89 runs so far, 0 failures, over 3m0s
90 runs so far, 0 failures, over 3m5s
92 runs so far, 0 failures, over 3m10s
95 runs so far, 0 failures, over 3m15s
98 runs so far, 0 failures, over 3m20s
101 runs so far, 0 failures, over 3m25s
104 runs so far, 0 failures, over 3m30s
106 runs so far, 0 failures, over 3m35s
107 runs so far, 0 failures, over 3m40s
111 runs so far, 0 failures, over 3m45s
114 runs so far, 0 failures, over 3m50s
115 runs so far, 0 failures, over 3m55s
118 runs so far, 0 failures, over 4m0s
122 runs so far, 0 failures, over 4m5s
123 runs so far, 0 failures, over 4m10s
125 runs so far, 0 failures, over 4m15s
131 runs so far, 0 failures, over 4m20s
131 runs so far, 0 failures, over 4m25s
134 runs so far, 0 failures, over 4m30s
136 runs so far, 0 failures, over 4m35s
139 runs so far, 0 failures, over 4m40s
141 runs so far, 0 failures, over 4m45s
143 runs so far, 0 failures, over 4m50s
148 runs so far, 0 failures, over 4m55s
149 runs so far, 0 failures, over 5m0s
152 runs so far, 0 failures, over 5m5s
154 runs so far, 0 failures, over 5m10s
157 runs so far, 0 failures, over 5m15s
158 runs so far, 0 failures, over 5m20s
161 runs so far, 0 failures, over 5m25s
165 runs so far, 0 failures, over 5m30s
168 runs so far, 0 failures, over 5m35s
170 runs so far, 0 failures, over 5m40s
173 runs so far, 0 failures, over 5m45s
175 runs so far, 0 failures, over 5m50s
178 runs so far, 0 failures, over 5m55s
181 runs so far, 0 failures, over 6m0s
183 runs so far, 0 failures, over 6m5s
186 runs so far, 0 failures, over 6m10s
189 runs so far, 0 failures, over 6m15s
190 runs so far, 0 failures, over 6m20s
195 runs so far, 0 failures, over 6m25s
197 runs so far, 0 failures, over 6m30s
198 runs so far, 0 failures, over 6m35s
202 runs so far, 0 failures, over 6m40s
206 runs so far, 0 failures, over 6m45s
206 runs so far, 0 failures, over 6m50s
208 runs so far, 0 failures, over 6m55s
214 runs so far, 0 failures, over 7m0s
214 runs so far, 0 failures, over 7m5s
217 runs so far, 0 failures, over 7m10s
221 runs so far, 0 failures, over 7m15s
222 runs so far, 0 failures, over 7m20s
225 runs so far, 0 failures, over 7m25s
229 runs so far, 0 failures, over 7m30s
230 runs so far, 0 failures, over 7m35s
233 runs so far, 0 failures, over 7m40s
237 runs so far, 0 failures, over 7m45s
238 runs so far, 0 failures, over 7m50s
242 runs so far, 0 failures, over 7m55s
245 runs so far, 0 failures, over 8m0s
247 runs so far, 0 failures, over 8m5s
250 runs so far, 0 failures, over 8m10s
252 runs so far, 0 failures, over 8m15s
254 runs so far, 0 failures, over 8m20s
259 runs so far, 0 failures, over 8m25s
260 runs so far, 0 failures, over 8m30s
263 runs so far, 0 failures, over 8m35s
267 runs so far, 0 failures, over 8m40s
269 runs so far, 0 failures, over 8m45s
271 runs so far, 0 failures, over 8m50s
275 runs so far, 0 failures, over 8m55s
277 runs so far, 0 failures, over 9m0s
281 runs so far, 0 failures, over 9m5s
283 runs so far, 0 failures, over 9m10s
285 runs so far, 0 failures, over 9m15s
288 runs completed, 1 failures, over 9m19s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-13 16:53
Duplicate of #5187.

**Closed by petermattis** 2016-03-13 16:53 UTC
Labels: Robot, test-failure
