### ISSUE TITLE
sql: int, float comparison gets wrong result due to round-off

### ISSUE THREAD

**Issue by eisenstatdavid** [cockroachdb/cockroach#10406] opened 2016-11-02 19:13 UTC
```
root@:26257> select 1e16::float < 1e16 + 1;
+--------------------------+
| 1e16::FLOAT < (1e16 + 1) |
+--------------------------+
| false                    |
+--------------------------+
(1 row)
```
The mathematical result is true.

**Comment by eisenstatdavid** [comment] 2016-11-02 20:59
(Note that both mathematical values involved in the comparison have exact representations in their respective types.)

**Comment by knz** [comment] 2016-11-05 12:42
I'm not sure the behavior here is different from what's expected. 
It's a feature of Summer that the resolved type FLOAT on the LHS propagates to the RHS as a demanded type; the result of the constant folding for 1e16+1 is casted down to float before the comparison takes place.

For example `select 1e16::float < (1e16 + 1)::decimal` returns true.

@nvanbenschoten what do you think?

@eisenstatdavid perhaps it would help if you could also share what you were expecting.

**Comment by eisenstatdavid** [comment] 2016-11-09 22:36
Oops, forgot to make that other constant an `int`. Here's what I meant:

```
root@:26257> select 1e16::float;
+-------------+
| 1e16::FLOAT |
+-------------+
| 1e+16       |
+-------------+
(1 row)
root@:26257> select (1e16+1)::int;
+-------------------+
|  (1e16 + 1)::INT  |
+-------------------+
| 10000000000000001 |
+-------------------+
(1 row)
root@:26257> select 1e16::float < (1e16+1)::int;
+-------------------------------+
| 1e16::FLOAT < (1e16 + 1)::INT |
+-------------------------------+
| false                         |
+-------------------------------+
(1 row)
```

If we're going to provide comparison operators on mixed numeric types, they should be right.

**Comment by eisenstatdavid** [comment] 2016-11-09 22:46
There's also an argument that int/float arithmetic operations should be correctly rounded (they're not presently), but I find it less compelling.

**Comment by knz** [comment] 2016-11-10 13:15
Some data points for further consideration:

- PostgreSQL gets this wrong - compares using floats
- Python gets this right - compares using bignums

Any opinions about where we should go from here? @mjibson? @bdarnell?

**Comment by eisenstatdavid** [comment] 2016-11-10 13:41
Worth noting that the fast path of a correct function is just a couple
instructions and a predictable branch, since the problems only turn up on
inputs of magnitude greater than 2^53.

**Comment by knz** [comment] 2016-11-10 13:53
s/correct/exact

**Comment by mjibson** [comment] 2016-11-10 18:55
Hmm. Could we convert any comparison between multiple types to decimal before comparing? It would be slower but guaranteed to be correct I think.

**Comment by bdarnell** [comment] 2016-11-11 10:30
We currently disallow int/float arithmetic because of the possibility of inexact results. Do we allow int/float comparisons because we think they're required for compatibility or just because we were incorrectly assuming that comparisons would always be exact? I would say that based on this we should not be treating comparisons as different from other arithmetic operations. 

If we think it's OK (from a compatibility perspective) to disallow int/float comparisons, then I'd vote to do that for consistency with our arithmetic decision. If not, I think I'd prefer to promote to decimal to get exact results (and this logic applies to all the arithmetic operations, so we could have `int + float -> decimal`).

**Comment by nvanbenschoten** [comment] 2016-11-12 07:58
For the original query, what @knz said is exactly right. The result is what we'd expect from our type system, and what we deemed as the "correct" behavior with respect to the constraints of the data type desired.

When comparing across data types, the "correct" behavior gets a little less clear. There was previously some debate about int/float comparisons, but they eventually were added for compatibility reasons. Thinking about this again, I tend to agree with @bdarnell here that there is not a fundamental difference between comparisons and arithmetic on mixed types. To maintain consistency, we should either:
- Disallow both (not feasible because of compatibility needs)
- Support inexact comparisons and arithmetic (follow PG's lead and promote int->float in these cases, and return floats from mixed-type arithmetic)
- Support exact comparisons and arithmetic (promote both to decimals before performing comparisons or arithmetic, and return decimals from mixed-type arithmetic)

My initial reaction is to continue in the direction we've been going and fully embrace option 2. This will give us the same behavior as Postgres and avoid shocking users with hidden performance complications. The general concern with this approach is that users may be surprised by the result of mixed-type comparisons/arithmetic (ala this issue), but I think there's enough documentation out there urging users to be careful with floating point values in SQL that it's acceptable.

**Comment by eisenstatdavid** [comment] 2016-11-14 17:00
Another potential twist is the `IN` operator. Postgres allows mixed-type `IN`:

```
eisen=# SELECT 2::INT IN (2::FLOAT, 4::FLOAT, 6::INT);
 ?column?
----------
 t
(1 row)
```

Currently, `IN` is implemented with binary search, so we would need to implement `.Compare` carefully so as not to violate the requirement of a transitive comparison operator. The obvious alternative of converting everything to float when at least one float is present means that it's possible to compare two ints for equality by converting them to floats first, which has wat potential.

**Comment by dianasaur323** [comment] 2017-04-05 14:47
assigning to @nvanbenschoten if this is still an issue. I agree with you that option 2 of maintaining PostgreSQL compatibility is the way we should go, as that's the path we've taken thus far. Please close if no longer relevant.

**Comment by mjibson** [comment] 2017-04-05 17:36
I think we should close this as expected behavior. It's the same as what postgres does. Using floats is already known to produce inconsistencies like this. See for example the `variance` and `stddev` aggregate float functions, which will return different results based on the order their input was received.

**Comment by dianasaur323** [comment] 2017-04-05 17:46
Perfect, closing

**Closed by dianasaur323** 2017-04-05 17:46 UTC
