### ISSUE TITLE
sql: severe regression in ORM query performance {django}

### ISSUE THREAD

**Issue by dikshant** [cockroachdb/cockroach#96218] opened 2023-01-30 19:17 UTC
I was investigating ORM query performance in CRDB 22.2.2 as well as latest (g69dd453d0e) and noticed some major regressions for Django's table introspection query when testing on Roachprod.

Steps to repro:

1. Create two separate 9 node multi region roachprod cluster using 22.2.2 and latest
```
roachprod create rp-test -n 9 --gce-zones 'us-east4-a','us-east4-a','us-east4-a','us-west2-a','us-west2-a','us-west2-a','us-central1-a','us-central1-a','us-central1-a' && roachprod stage rp-test release v22.2.2 && roachprod start rp-test:1-9
```

2. Create lots of tables. (15k)
```
for i in $(seq 1 15000); do echo "CREATE TABLE t_$i (i INT PRIMARY KEY, j INT);" >> out.sql;
cat out.sql | roachprod sql rp-test
```

3. Run the following query in both clusters:
```
              SELECT
                c.relname,
                CASE
                    WHEN c.relispartition THEN 'p'
                    WHEN c.relkind IN ('m', 'v') THEN 'v'
                    ELSE 't'
                END,
                obj_description(c.oid, 'pg_class')
            FROM pg_catalog.pg_class c
            LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
            WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                AND pg_catalog.pg_table_is_visible(c.oid);
```

4. Observe that latest (g69dd453d0e) takes a lot longer than 22.2.2 and the query plans are different.
- [Gist for 22.2.2](https://gist.github.com/dikshant/703f590a996f3666294f5de640c351b7) - takes 127 seconds.
- [Gist for latest (`g69dd453d0e`)](https://gist.github.com/dikshant/1d048760d1f5948ca7264113c1d415a4) - takes 694 seconds

Jira issue: CRDB-24010

**Comment by ZhouXing19** [comment] 2023-01-30 22:37
Adding more info -- I tried on my single-region gceworker with the latest commit on master (`10ef5d9d7a`) and it took shorter time for the same number of table and query, and gave different plan:
```
root@localhost:26257/defaultdb> SELECT VERSION();                                                        
                                                       version
---------------------------------------------------------------------------------------------------------------------
  CockroachDB CCL v23.1.0-alpha.1-1423-g10ef5d9d7a-dirty (x86_64-pc-linux-gnu, built 2023/01/30 22:19:41, go1.19.4)
(1 row)

Time: 9ms total (execution 8ms / network 0ms)

root@localhost:26257/defaultdb> EXPLAIN ANALYZE SELECT t.typname,t.oid FROM pg_catalog.pg_type t         
                             ->    JOIN pg_catalog.pg_namespace n ON (t.typnamespace = n.oid)            
                             ->      WHERE n.nspname  != 'pg_toast'                                      
                             ->           AND                                                            
                             ->        (t.typrelid = 0 OR (SELECT c.relkind = 'c' FROM                   
                             -> pg_catalog.pg_class c WHERE c.oid = t.typrelid));                        
                          info
---------------------------------------------------------
  planning time: 557µs
  execution time: 4.2s
  distribution: local
  vectorized: true
  maximum memory usage: 3.6 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 168ms

  • hash join
  │ nodes: n1
  │ actual row count: 82
  │ estimated max memory allocated: 100 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 247µs
  │ equality: (oid) = (typnamespace)
  │
  ├── • filter
  │   │ nodes: n1
  │   │ actual row count: 5
  │   │ sql cpu time: 8µs
  │   │ filter: nspname != 'pg_toast'
  │   │
  │   └── • virtual table
  │         nodes: n1
  │         actual row count: 5
  │         sql cpu time: 158µs
  │         table: pg_namespace@primary
  │
  └── • filter
      │ nodes: n1
      │ actual row count: 82
      │ sql cpu time: 2ms
      │ filter: (typrelid = 0) OR "?column?"
      │
      └── • distinct
          │ nodes: n1
          │ actual row count: 15,380
          │ estimated max memory allocated: 370 KiB
          │ estimated max sql temp disk usage: 0 B
          │ sql cpu time: 3ms
          │ distinct on: rownum
          │ error on duplicate
          │
          └── • hash join (left outer)
              │ nodes: n1
              │ actual row count: 15,380
              │ estimated max memory allocated: 2.6 MiB
              │ estimated max sql temp disk usage: 0 B
              │ sql cpu time: 24ms
              │ equality: (typrelid) = (oid)
              │
              ├── • ordinality
              │   │ nodes: n1
              │   │ actual row count: 15,380
              │   │ sql cpu time: 187µs
              │   │
              │   └── • virtual table
              │         nodes: n1
              │         actual row count: 15,380
              │         sql cpu time: 30ms
              │         table: pg_type@primary
              │
              └── • render
                  │
                  └── • virtual table
                        nodes: n1
                        actual row count: 30,322
                        sql cpu time: 108ms
                        table: pg_class@primary
(69 rows)

Time: 4.245s total (execution 4.237s / network 0.008s)

```

**Comment by rafiss** [comment] 2023-02-01 00:28
I tried with 6fd5b048 (the commit before https://github.com/cockroachdb/cockroach/pull/95234 was merged), and observed that the apply join is no longer planned. On a local single node cluster with 0 tables:
```
root@localhost:26257/defaultdb> explain analyze SELECT
                             ->                 c.relname,
                             ->                 CASE
                             ->                     WHEN c.relispartition THEN 'p'
                             ->                     WHEN c.relkind IN ('m', 'v') THEN 'v'
                             ->                     ELSE 't'
                             ->                 END,
                             ->                 obj_description(c.oid, 'pg_class')
                             ->             FROM pg_catalog.pg_class c
                             ->             JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
                             ->             WHERE c.relkind IN ('f', 'm', 'p', 'r', 'v')
                             ->                 AND n.nspname NOT IN ('pg_catalog', 'pg_toast')
                             ->                 AND pg_catalog.pg_table_is_visible(c.oid);
                                           info
------------------------------------------------------------------------------------------
  planning time: 5ms
  execution time: 120ms
  distribution: local
  vectorized: true
  maximum memory usage: 1000 KiB
  network usage: 0 B (0 messages)

  • render
  │
  └── • distinct
      │ nodes: n1
      │ actual row count: 3
      │ estimated max memory allocated: 10 KiB
      │ estimated max sql temp disk usage: 0 B
      │ distinct on: rownum
      │
      └── • hash join (right outer)
          │ nodes: n1
          │ actual row count: 3
          │ estimated max memory allocated: 60 KiB
          │ estimated max sql temp disk usage: 0 B
          │ equality: (objoid) = (oid)
          │
          ├── • hash join
          │   │ nodes: n1
          │   │ actual row count: 287
          │   │ estimated max memory allocated: 110 KiB
          │   │ estimated max sql temp disk usage: 0 B
          │   │ equality: (relnamespace) = (oid)
          │   │
          │   ├── • virtual table lookup join
          │   │   │ nodes: n1
          │   │   │ actual row count: 287
          │   │   │ table: pg_class@pg_class_oid_idx
          │   │   │ equality: (classoid) = (oid)
          │   │   │ pred: relname = 'pg_class'
          │   │   │
          │   │   └── • filter
          │   │       │ nodes: n1
          │   │       │ actual row count: 2,191
          │   │       │ filter: objsubid = 0
          │   │       │
          │   │       └── • virtual table
          │   │             nodes: n1
          │   │             actual row count: 2,191
          │   │             table: pg_description@primary
          │   │
          │   └── • filter
          │       │ nodes: n1
          │       │ actual row count: 1
          │       │ filter: nspname = 'pg_catalog'
          │       │
          │       └── • virtual table
          │             nodes: n1
          │             actual row count: 5
          │             table: pg_namespace@primary
          │
          └── • ordinality
              │ nodes: n1
              │ actual row count: 3
              │
              └── • virtual table lookup join
                  │ nodes: n1
                  │ actual row count: 3
                  │ table: pg_namespace@pg_namespace_oid_idx
                  │ equality: (relnamespace) = (oid)
                  │ pred: nspname NOT IN ('pg_catalog', 'pg_toast')
                  │
                  └── • filter
                      │ nodes: n1
                      │ actual row count: 132
                      │ filter: "?column?"
                      │
                      └── • render
                          │
                          └── • distinct
                              │ nodes: n1
                              │ actual row count: 296
                              │ estimated max memory allocated: 60 KiB
                              │ estimated max sql temp disk usage: 0 B
                              │ distinct on: rownum
                              │
                              └── • merge join
                                  │ nodes: n1
                                  │ actual row count: 296
                                  │ estimated max memory allocated: 330 KiB
                                  │ estimated max sql temp disk usage: 0 B
                                  │ equality: (oid) = (oid)
                                  │
                                  ├── • virtual table lookup join
                                  │   │ nodes: n1
                                  │   │ actual row count: 320
                                  │   │ table: pg_namespace@pg_namespace_oid_idx
                                  │   │ equality: (relnamespace) = (oid)
                                  │   │
                                  │   └── • virtual table
                                  │         nodes: n1
                                  │         actual row count: 320
                                  │         estimated max memory allocated: 60 KiB
                                  │         estimated max sql temp disk usage: 0 B
                                  │         table: pg_class@pg_class_oid_idx
                                  │
                                  └── • sort
                                      │ nodes: n1
                                      │ actual row count: 296
                                      │ estimated max memory allocated: 110 KiB
                                      │ estimated max sql temp disk usage: 0 B
                                      │ order: +oid
                                      │
                                      └── • filter
                                          │ nodes: n1
                                          │ actual row count: 296
                                          │ filter: relkind IN ('f', 'm', 'p', 'r', 'v')
                                          │
                                          └── • ordinality
                                              │ nodes: n1
                                              │ actual row count: 320
                                              │
                                              └── • virtual table
                                                    nodes: n1
                                                    actual row count: 320
                                                    table: pg_class@primary
(122 rows)
```

**Comment by rafiss** [comment] 2023-02-01 18:36
cc @mgartner if you have any ideas for why https://github.com/cockroachdb/cockroach/pull/95234 would lead to this regression.

**Comment by rafiss** [comment] 2023-02-01 20:10
I tried with commit 2f811420 (from https://github.com/cockroachdb/cockroach/pull/93218), and that also does not have the apply join.

```
  planning time: 5ms
  execution time: 117ms
  distribution: local
  vectorized: true
  maximum memory usage: 1000 KiB
  network usage: 0 B (0 messages)

  • render
  │
  └── • distinct
      │ nodes: n1
      │ actual row count: 3
      │ estimated max memory allocated: 10 KiB
      │ estimated max sql temp disk usage: 0 B
      │ distinct on: rownum
      │
      └── • hash join (right outer)
          │ nodes: n1
          │ actual row count: 3
          │ estimated max memory allocated: 60 KiB
          │ estimated max sql temp disk usage: 0 B
          │ equality: (objoid) = (oid)
          │
          ├── • hash join
          │   │ nodes: n1
          │   │ actual row count: 287
          │   │ estimated max memory allocated: 110 KiB
          │   │ estimated max sql temp disk usage: 0 B
          │   │ equality: (relnamespace) = (oid)
          │   │
          │   ├── • virtual table lookup join
          │   │   │ nodes: n1
          │   │   │ actual row count: 287
          │   │   │ table: pg_class@pg_class_oid_idx
          │   │   │ equality: (classoid) = (oid)
          │   │   │ pred: relname = 'pg_class'
          │   │   │
          │   │   └── • filter
          │   │       │ nodes: n1
          │   │       │ actual row count: 2,191
          │   │       │ filter: objsubid = 0
          │   │       │
          │   │       └── • virtual table
          │   │             nodes: n1
          │   │             actual row count: 2,191
          │   │             table: pg_description@primary
          │   │
          │   └── • filter
          │       │ nodes: n1
          │       │ actual row count: 1
          │       │ filter: nspname = 'pg_catalog'
          │       │
          │       └── • virtual table
          │             nodes: n1
          │             actual row count: 5
          │             table: pg_namespace@primary
          │
          └── • ordinality
              │ nodes: n1
              │ actual row count: 3
              │
              └── • virtual table lookup join
                  │ nodes: n1
                  │ actual row count: 3
                  │ table: pg_namespace@pg_namespace_oid_idx
                  │ equality: (relnamespace) = (oid)
                  │ pred: nspname NOT IN ('pg_catalog', 'pg_toast')
                  │
                  └── • filter
                      │ nodes: n1
                      │ actual row count: 132
                      │ filter: "?column?"
                      │
                      └── • render
                          │
                          └── • distinct
                              │ nodes: n1
                              │ actual row count: 296
                              │ estimated max memory allocated: 60 KiB
                              │ estimated max sql temp disk usage: 0 B
                              │ distinct on: rownum
                              │
                              └── • merge join
                                  │ nodes: n1
                                  │ actual row count: 296
                                  │ estimated max memory allocated: 330 KiB
                                  │ estimated max sql temp disk usage: 0 B
                                  │ equality: (oid) = (oid)
                                  │
                                  ├── • virtual table lookup join
                                  │   │ nodes: n1
                                  │   │ actual row count: 320
                                  │   │ table: pg_namespace@pg_namespace_oid_idx
                                  │   │ equality: (relnamespace) = (oid)
                                  │   │
                                  │   └── • virtual table
                                  │         nodes: n1
                                  │         actual row count: 320
                                  │         estimated max memory allocated: 60 KiB
                                  │         estimated max sql temp disk usage: 0 B
                                  │         table: pg_class@pg_class_oid_idx
                                  │
                                  └── • sort
                                      │ nodes: n1
                                      │ actual row count: 296
                                      │ estimated max memory allocated: 110 KiB
                                      │ estimated max sql temp disk usage: 0 B
                                      │ order: +oid
                                      │
                                      └── • filter
                                          │ nodes: n1
                                          │ actual row count: 296
                                          │ filter: relkind IN ('f', 'm', 'p', 'r', 'v')
                                          │
                                          └── • ordinality
                                              │ nodes: n1
                                              │ actual row count: 320
                                              │
                                              └── • virtual table
                                                    nodes: n1
                                                    actual row count: 320
                                                    table: pg_class@primary
(122 rows)

Time: 124ms total (execution 123ms / network 1ms)
```

**Comment by mgartner** [comment] 2023-02-01 21:25
On 61233f0649a75417181711323191b795561040d2, the commit in #95234, there is also no apply-join. I'll bisect to hone in on the commit that introduced the apply-join.

**Comment by rafiss** [comment] 2023-02-01 22:22
My bad. I thought I had tested 61233f0, which was why I tagged you. Thanks for taking on the bisect!

**Comment by mgartner** [comment] 2023-02-01 22:28
This is the commit where the apply-join gets added: c2c6239dc201f661f657fe13bbf1b8145555b405.

The `pg_table_is_visible` builtin, now defined as an "internal UDF", is strict, meaning that if it's input is `NULL` then it results directly in `NULL` without being called. In c2c6239dc201f661f657fe13bbf1b8145555b405 we switched from some special `tree.Routine` execution logic for this behavior (which was broken in some cases), to wrapping all strict UDFs in a `CASE` expression. Unfortunately, this `CASE` expression prevents decorrelation of the inlined subquery that represents the UDF. 

One workaround is to mark the builtin (and the ones similar to it) as NOT strict. I believe the behavior of the `pg_table_is_visible` builtin will be the same. It's defined as:

```sql
SELECT n.nspname = any current_schemas(true)
FROM pg_catalog.pg_class c
INNER LOOKUP JOIN pg_catalog.pg_namespace n
ON c.relnamespace = n.oid
WHERE c.oid=$1 LIMIT 1
```

The `WHERE c.oid=$1` clause should never be truthy if `$1` is `NULL`, so this query should always return zero rows when presented with `NULL`. When the last query in a UDF results in zero rows, `NULL` is returned. In order words, if we mark it as NOT strict, it should return `NULL` when presented with a `NULL` argument, just like it would if it were marked strict. The only different being that the query will actually be executed when presented with `NULL`, whereas it wouldn't if marked as strict. But calling `pg_table_is_visible` builtin with `NULL` arguments is an edge case that we probably shouldn't worry about optimizing for.

I'll go ahead and put up a PR.

**Comment by rafiss** [comment] 2023-02-01 22:33
Nice find! I suppose we should make the same change for the other `pg_*_is_visible` builtins, since those are likely to be used in the same way.

> we switched from some special tree.Routine execution logic for this behavior (which was broken in some cases), to wrapping all strict UDFs in a CASE expression. Unfortunately, this CASE expression prevents decorrelation of the inlined subquery that represents the UDF.

is there a concern that preventing decorrelation would be bad for other performance of other functions?

**Comment by DrewKimball** [comment] 2023-02-02 23:48
@mgartner do you think it would be possible to have a rule that will remove the `CaseExpr` in a case like this?

**Comment by mgartner** [comment] 2023-02-07 00:57
> @mgartner do you think it would be possible to have a rule that will remove the CaseExpr in a case like this? I'm going to see if I can hack one together.

Yes, that seems valuable, but I don't think it helps in this case because these builtins are stable, non-leakproof functions.

**Comment by DrewKimball** [comment] 2023-02-07 01:05
We can still hoist stable functions a lot of the time, right? After function hoisting, the CASE becomes leakproof (at least in this case)

**Closed** 2023-02-24 21:43 UTC
Labels: C-bug, C-investigation, T-sql-sessions, GA-blocker, branch-release-23.1
