### ISSUE TITLE
sql: unsupported binary operator: <timestamptz> - <string>

### ISSUE THREAD

**Issue by rmloveland** [cockroachdb/cockroach#44871] opened 2020-02-07 18:21 UTC
CockroachDB 19.2.3 running on a Mac laptop. 

Interestingly, addition works for these types, but not subtraction.  I was surprised since querying against times in the past seems like the more common case.

```
> SELECT now() + '1y';
              ?column?              
+----------------------------------+
  2021-02-07 18:14:38.224385+00:00  
```

```
> SELECT now() - '1y';
pq: unsupported binary operator: <timestamptz> - <string>
```

**Comment by yuzefovich** [comment] 2020-02-08 03:48
Casual look into the code suggests that optimizer implicitly adds a type cast from string to interval for the plus operation but not for minus:
```
root@127.0.0.1:50953/defaultdb> explain (opt, types) SELECT now() + '1y';
                       text
---------------------------------------------------
  values
   ├── columns: "?column?":1(timestamptz)
   ├── cardinality: [1 - 1]
   ├── side-effects
   ├── stats: [rows=1]
   ├── cost: 0.02
   ├── key: ()
   ├── fd: ()-->(1)
   ├── prune: (1)
   └── tuple [type=tuple{timestamptz}]
        └── plus [type=timestamptz]
             ├── function: now [type=timestamptz]
             └── const: '1 year' [type=interval]
(13 rows)

Time: 492µs

root@127.0.0.1:50953/defaultdb> explain (opt, types) SELECT now() - '1y';
ERROR: unsupported binary operator: <timestamptz> - <string>
SQLSTATE: 22023
```
so kicking this to Optimizer friends.

**Comment by yongyanglai** [comment] 2020-06-10 08:44
cc @RaduBerinde @rmloveland 
I found the problem is that there is only one possible overloads `TimestampTZ + Interval` for  expression `TimestampTZ + string` while three possible overloads `TimestampTZ - TimestampTZ`, `TimestampTZ - Timestamp`, `TimestampTZ - Interval` for expression `TimestampTZ - string` so the function `canConstantBecome` used in function `typeCheckOverloadsExprs` failed:
```go
// canConstantBecome returns whether the provided Constant can become resolved
// as the provided type.
func canConstantBecome(c Constant, typ *types.T) bool {
	avail := c.AvailableTypes()
	for _, availTyp := range avail {
		if availTyp.Equivalent(typ) {
			return true
		}
	}
	return false
}
```
This function doesn't consider semantic of string value, I think we should replace it with function 
 `ResolveAsType` that is aware of semantic of constant.

**Comment by RaduBerinde** [comment] 2020-06-11 17:36
Note that this doesn't work in postgres either, it defaults to treating the string as a timestamp:
```
radu=> select 'now'::timestamp + '1 day';
         ?column?          
---------------------------
 2020-06-12 13:35:18.57792

radu=> select 'now'::timestamp - '1 day';
ERROR:  invalid input syntax for type timestamp: "1 day"
```

**Comment by nvanbenschoten** [comment] 2021-09-10 20:27
If this doesn't work in Postgres either, should we close this issue?

**Comment by mgartner** [comment] 2021-09-21 13:42
Casting from a string type to an interval requires and explicit cast. Notice below that the `TEXT` intervals are not implicitly cast to `INTERVAL`s.

```
marcus=# SELECT now() + '1 day'::TEXT;
ERROR:  42883: operator does not exist: timestamp with time zone + text
LINE 1: SELECT now() + '1 day'::TEXT;
                     ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


marcus=# SELECT now() - '1 day'::TEXT;
ERROR:  42883: operator does not exist: timestamp with time zone - text
LINE 1: SELECT now() - '1 day'::TEXT;
                     ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

The reason that `now() + '1 day'` works is because `'1 day'` is directly resolved as an interval because there is a `+(timestamptz, interval)` overload. There is no `-(timestamptz, interval)` overload, so `now() - '1 day'` fails.

I agree with @nvanbenschoten. I don't think we should stray from Postgres unless there is a strong reason to. Adding an explicit cast, like `now() - '1 day'::INTERVAL`, seems like a fine workaround. I'll close the issue.

**Closed by mgartner** 2021-09-21 13:42 UTC
Labels: C-enhancement, T-sql-queries
