### ISSUE TITLE
Test failure in CI build 8258

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2767] opened 2015-10-05 15:42 UTC
The following test appears to have failed:

[#8258](https://circleci.com/gh/cockroachdb/cockroach/8258):

```
W1005 15:40:30.380431 912 storage/store.go:594  error gossiping first range data: storage/replica.go:1211: node is stopping
W1005 15:40:30.380694 912 storage/store.go:613  error gossiping system config: storage/replica.go:1211: node is stopping
I1005 15:41:30.379948 912 storage/replica.go:1231  gossiping cluster id  from store 1, range 1
W1005 15:41:30.380277 912 storage/store.go:594  error gossiping first range data: storage/replica.go:1211: node is stopping
W1005 15:41:30.380493 912 storage/store.go:613  error gossiping system config: storage/replica.go:1211: node is stopping
panic: test timed out after 5m0s

goroutine 7159 [running]:
testing.startAlarm.func1()
	/tmp/workdir/go/src/testing/testing.go:703 +0x16b
created by time.goFunc
	/tmp/workdir/go/src/time/sleep.go:129 +0x6e

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x179b018, 0x1d9d680, 0xc2, 0xc2, 0x1482201)
	/tmp/workdir/go/src/testing/testing.go:562 +0xafa
--
	/go/src/github.com/cockroachdb/cockroach/storage/queue.go:278 +0x3db
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8203d4180, 0xc8205056c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x60
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x70
FAIL	github.com/cockroachdb/cockroach/storage	300.052s
=== RUN   TestBatchBasics
I1005 15:37:12.619368 906 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1005 15:37:12.623648 906 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1005 15:37:12.630420 906 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-10-05 15:44
Duplicate of #2206

**Closed by bdarnell** 2015-10-05 15:44 UTC
Labels: test-failure
