### ISSUE TITLE
sql: SAVEPOINT errors do not consistently cause an error to be reported to the client

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#8297] opened 2016-08-03 17:58 UTC
reported by @fishcakez in https://github.com/cockroachdb/cockroach/issues/5582#issuecomment-236400566:

"However there is a surprise that a savepoint error does not cause the transaction to enter the failed status."

**Comment by knz** [comment] 2016-08-03 17:58
cc @andreimatei

**Comment by fishcakez** [comment] 2016-08-03 18:56
The savepoint is causing an `ErrorResponse` but the following `ReadyForQuery` message has status indicator of inside transaction block, rather than inside failed transaction block. Perhaps cockroach does not have the concept of "failed transaction" because it does not have savepoints?

**Comment by tlvenn** [comment] 2016-10-10 15:52
Any update on the above @andreimatei ? thanks in advance

**Comment by andreimatei** [comment] 2016-10-10 16:21
Hey @tlvenn, sorry for dropping this. I believe we should be sending the "failed transaction block" bit, I don't see us handing errors on unsupported `SAVEPOINT` statements any differently than any other errors inside a txn. And we do have the concept of "inside a failed transaction".
Could you give me a series of statements leading to this wrong status being reported? Thanks!

**Comment by tlvenn** [comment] 2016-10-11 02:26
@fishcakez any chance you can provide the series of statements that @andreimatei is asking for ? Thanks !

**Comment by spencerkimball** [comment] 2017-04-03 22:19
@andreimatei could you determine whether this should have the 1.0 milestone? If not, please remove, fix, or re-assign.

**Comment by andreimatei** [comment] 2017-04-03 22:22
Waiting for reproduction instruction from @fishcakez.
In any case, doesn't seem like a show-stopper. Removed the 1.0 label.

**Comment by fishcakez** [comment] 2017-04-04 00:51
Sorry I don't have this available, I think it was to do whether a transaction got rolled back on commit after trying and failing to create a savepoint.

**Comment by knz** [comment] 2017-05-02 14:51
@andreimatei I think this may be fixed by #15563.

**Comment by andreimatei** [comment] 2017-05-02 15:26
Thanks @knz. Let's hope so. This bug is a bit vague in its current description, so I'm going to close it hoping that it was indeed fix.
As always, if anything even looks suspicious with our pgwire implementation or transaction state handling, please let us know.

**Closed by andreimatei** 2017-05-02 15:26 UTC
Labels: bug, investigation, ux-surprise
