### ISSUE TITLE
sql/sem/tree: CreateTable partition by expressions are not walked

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#33724] opened 2019-01-14 21:45 UTC
The `CreateTable.walkStmt` implementation is not walking over the expressions inside CreateTable.PartitionBy. This results in abnormal behavior when placeholders or subqueries are used inside those expressions.

CC @knz @danhhz

Jira issue: CRDB-4674

**Comment by knz** [comment] 2019-01-22 18:32
yes I found this, also it doesn't walk the DEFAULT expressions. Both are problematic.

**Comment by knz** [comment] 2021-06-05 07:16
This bug still exists in v21.1

**Comment by mgartner** [comment] 2023-06-08 16:09
Closing as duplicate of #102032.

**Closed by mgartner** 2023-06-08 16:09 UTC
Labels: C-bug, A-sql-optimizer, T-sql-queries
