### ISSUE TITLE
Implicit casting does not work for uuid[]

### ISSUE THREAD

**Issue by martinjankoehler** [cockroachdb/cockroach#57226] opened 2020-11-30 15:28 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Create a Table with `uuid[]`
- Attempt to insert a row using an implicit casting literal for the `uuid[] vector`, the way it works on PostgreSQL
- I get a syntax error `ERROR:  value type string doesn't match type uuid[] of column "liste"`

**What did you do? Describe in your own words.**

- Attempted to INSERT an `uuid[]` literal using https://www.cockroachlabs.com/docs/stable/array.html#implicit-casting
```sql
CREATE TABLE uuid_test (
    id bigint DEFAULT unique_rowid() PRIMARY KEY,
    liste uuid[]
);

-- BUG: this attempt fails (but works with PostgreSQL)
INSERT INTO "public"."uuid_test"("liste") VALUES('{a16d1e64-06d5-42d7-a899-dbad1b1f4150}') RETURNING "id", "liste";

-- NOTE: this attempt works
INSERT INTO "public"."uuid_test"("liste") VALUES(ARRAY['a16d1e64-06d5-42d7-a899-dbad1b1f4150']) RETURNING "id", "liste";
```

**Environment:**
 - CockroachDB version [CCL v20.1.0]
 - Server OS: [x86_64-unknown-linux-gnu, built 2020/05/05 00:07:18, go1.13.9]
 - Client app [http://postico.app]

**Comment by rafiss** [comment] 2020-11-30 16:45
Thanks for the issue! This is a duplicate of https://github.com/cockroachdb/cockroach/issues/54672

We have fixed the issue for CockroachDB v20.2.x, but we will not be able to include this change in any v20.1 releases.

**Closed by rafiss** 2020-11-30 16:45 UTC
Labels: C-bug, O-community, X-blathers-triaged
