### ISSUE TITLE
sql: panic: invalid datum type given: string, expected oid[]

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#39343] opened 2019-08-06 04:55 UTC
```
USE defaultdb;

CREATE TABLE table0 (col0 OID NULL, col1 INET NOT NULL, col2 INT4 NULL, col3 FLOAT8, col4 UUID, col5 INET, col6 INET, col7 FLOAT4 NOT NULL, col8 REGCLASS NOT NULL, col9 VARCHAR, col10 REGPROCEDURE NULL, col11 BIT(7), col12 FLOAT8 NULL, col13 TIMESTAMPTZ NOT NULL, col14 FLOAT8 NOT NULL, col15 BIT(42), col16 REGPROC, FAMILY fam0 (col6), FAMILY fam1 (col4), FAMILY fam2 (col10), FAMILY fam3 (col16), FAMILY fam4 (col3), FAMILY fam5 (col2), FAMILY fam6 (col15), FAMILY fam7 (col1), FAMILY fam8 (col12), FAMILY fam9 (col0), FAMILY fam10 (col5), FAMILY fam11 (col13), FAMILY fam12 (col7), FAMILY fam13 (col11), FAMILY fam14 (col9), FAMILY fam15 (col8), FAMILY fam16 (col14), PRIMARY KEY (col6 DESC), UNIQUE (col10, col13 ASC, col3 ASC, col15 ASC, col16, col11, col14, col8 ASC, col0 ASC, col7 DESC, col2 ASC, col4 ASC, col9 DESC, col1 ASC, col5 ASC, col6 ASC), INDEX (col3, col7, col9 DESC, col16, col14 DESC, col0 DESC, col11 ASC, col8), UNIQUE (col10 DESC, col4 ASC, col1 ASC, col6 ASC, col5));

CREATE TABLE table1 (col0 INT2 NULL, col1 DATE, col2 "char" NOT NULL, col3 REGCLASS NOT NULL, col4 VARCHAR NOT NULL, col5 TIMESTAMP NULL, col6 REGNAMESPACE NOT NULL, col7 DECIMAL NULL, col8 REGCLASS NULL, col9 REGPROC NOT NULL, col10 NAME, col11 INT8 NOT NULL, col12 BOOL NOT NULL, col13 BOOL NOT NULL, col14 BYTES NULL, col15 INT4 NULL, col16 REGPROCEDURE NULL, FAMILY fam0 (col0, col8, col9, col12, col10, col14, col5, col2, col15, col11, col3, col6, col16, col4, col1, col13, col7), PRIMARY KEY (col9, col16 DESC), INDEX (col8 DESC, col11, col6 ASC, col16, col9, col2 ASC, col12 ASC, col0, col14, col13 ASC), UNIQUE (col4 ASC, col13 ASC, col8 ASC), INDEX (col12 DESC, col13 ASC, col9 DESC, col5, col16 ASC, col14 ASC, col1 ASC, col7 DESC), INDEX (col9, col1 DESC, col2 ASC, col15 DESC, col3 ASC, col7 ASC, col4, col10, col5 ASC, col16 DESC, col0 ASC));

CREATE TABLE IF NOT EXISTS tab_orig AS
	SELECT
		g::INT2 AS _int2,
		g::INT4 AS _int4,
		g::INT8 AS _int8,
		g::FLOAT4 AS _float4,
		g::FLOAT8 AS _float8,
		'2001-01-01'::DATE + g AS _date,
		'2001-01-01'::TIMESTAMP + g * '1 day'::INTERVAL AS _timestamp,
		'2001-01-01'::TIMESTAMPTZ + g * '1 day'::INTERVAL AS _timestamptz,
		g * '1 day'::INTERVAL AS _interval,
		g % 2 = 1 AS _bool,
		g::DECIMAL AS _decimal,
		g::STRING AS _string,
		g::STRING::BYTES AS _bytes,
		substring('00000000-0000-0000-0000-' || g::STRING || '00000000000', 1, 36)::UUID AS _uuid,
		'0.0.0.0'::INET + g AS _inet,
		g::STRING::JSONB AS _jsonb
	FROM
		generate_series(1, 5) AS g;

WITH
	with_11475 (col_147513, col_147514, col_147515)
		AS (
			SELECT
				*
			FROM
				(
					VALUES
						(
							(e'\x06z;\f \x050l':::STRING, '\xc7':::BYTES, (), B'111011'),
							B'10111000110',
							e' |}\f]W+':::STRING
						),
						(
							(e'\x00':::STRING, '\x2c03000ef85506a3':::BYTES, (), B'001000'),
							B'11000110001010001011110110001001000001000000010100111011111001110100001010011011',
							NULL
						)
				)
					AS tab_50755 (col_147513, col_147514, col_147515)
		)
SELECT
	count_rows()::INT8 AS col_147581,
	max(tab_50756._timestamp::TIMESTAMP)::TIMESTAMP AS col_147582,
	e'YPP\x02':::STRING AS col_147583,
	(-2147483648):::INT8 AS col_147584,
	1479688130622180784:::INT8 AS col_147585,
	count(tab_50756._timestamp)::INT8 AS col_147586,
	3630315307:::OID AS col_147587,
	876408800:::OID AS col_147588
FROM
	defaultdb.public.tab_orig AS tab_50756
WHERE
	(NOT (tab_50756._bytes::BYTES IN (WITH with_11483 (col_147563, col_147564, col_147565, col_147566, col_147567, col_147568, col_147569, col_147570, col_147571, col_147572, col_147573, col_147574, col_147575) AS (SELECT * FROM (VALUES (e'Y~No\x07\b':::STRING, 2486356602077416437:::INT8, (WITH with_11480 (col_147546, col_147547, col_147548, col_147549, col_147550, col_147551, col_147552) AS (SELECT * FROM (VALUES (NULL, (WITH with_11476 (col_147516) AS (SELECT * FROM (VALUES ('58 years 10 mons 805 days 09:56:06.843838':::INTERVAL), ('82 years 11 mons 600 days 09:14:15.074813':::INTERVAL), (NULL), (NULL), ('8 mons 338 days 02:26:18.160772':::INTERVAL), ('-58 years -2 mons -634 days -18:07:41.646648':::INTERVAL)) AS tab_50757 (col_147516)) SELECT COALESCE('"':::STRING, e'\x00':::STRING) AS col_147517 LIMIT 1:::INT8), 3372103110:::OID, (WITH with_11477 (col_147519, col_147520, col_147521, col_147522) AS (SELECT * FROM (VALUES ((SELECT ARRAY[2292177053:::OID,142543474:::OID,3876443082:::OID] AS col_147518 FROM defaultdb.public.table1 AS tab_50758 WHERE tab_50758.col13 GROUP BY tab_50758.col16 LIMIT 1:::INT8), (-7379610829396311947):::INT8, (), 1271179161:::OID), (ARRAY[2817322446:::OID,3904477271:::OID,2702950472:::OID], 2147483647:::INT8, (), 1674189746:::OID), (ARRAY[534291138:::OID,586933495:::OID,2142181989:::OID], (-7182608556152553381):::INT8, (), NULL), (ARRAY[3828678275:::OID], (-1819220568151711360):::INT8, (), 4203575333:::OID)) AS tab_50759 (col_147519, col_147520, col_147521, col_147522)) , with_11478 (col_147523, col_147524, col_147525, col_147526, col_147527, col_147528, col_147529, col_147530, col_147531, col_147532) AS (SELECT * FROM (VALUES ((-0.16231307960534563):::FLOAT8, e'\x00':::STRING, '-57 years -5 mons -795 days -06:43:54.665591':::INTERVAL, (-8536915487714927461):::INT8, '[{"5*:aP": [], "8FW ": [], "bar": ["c", true, 3.5305467480692414]}, 0.08162288107597893, 0.138848410122428, [true, {"foo": []}, {}]]':::JSONB, B'1011100101010100110111011111001001', (-8.526606128531150051E+20):::DECIMAL, (-59766043665.96310110):::DECIMAL, 3271364767:::OID, '1970-01-03 17:34:40.00058+00:00':::TIMESTAMP), ((-0.41884467898781197):::FLOAT8, e'\x00':::STRING, '-45 years -318 days -22:36:51.490018':::INTERVAL, (-5607296423817760928):::INT8, '["^2[tF", {"5<aZ": [[null]], "b": {"foobar": null}, "bar": ["foobar", true, 1.1102145447877978]}, {"Tl<": [">cA_RMX"], "bar": "b$f|C-6o*", "c": []}]':::JSONB, NULL, 'NaN':::DECIMAL, (-809860881452480.3051):::DECIMAL, 3068577754:::OID, NULL)) AS tab_50760 (col_147523, col_147524, col_147525, col_147526, col_147527, col_147528, col_147529, col_147530, col_147531, col_147532)) , with_11479 (col_147533, col_147534, col_147535, col_147536, col_147537, col_147538, col_147539, col_147540, col_147541, col_147542, col_147543, col_147544) AS (SELECT * FROM (VALUES (NULL, NULL, ARRAY[1355658189:::OID], '18:14:01.685898':::TIME, NULL, '09:26:50.347617':::TIME, 3893819903:::OID, 'a478:6ece:f1f6:442c:1569:8795:479f:1ce1/36':::INET, ARRAY[853420955:::OID,3367298864:::OID,1023315874:::OID], (e'\x1b\x14\x14':::STRING,), '':::STRING, (-6514018791040196246):::INT8), (ARRAY['1974-12-26':::DATE,'1981-02-25':::DATE], 'f532:1cf5:1526:725e:d757:bfcb:2cfa:7fa1/121':::INET, ARRAY[2089000142:::OID], '03:41:23.825731':::TIME, NULL, '21:20:40.930454':::TIME, NULL, '139.25.27.40/12':::INET, ARRAY[2502028419:::OID,2262552726:::OID,3230085146:::OID], ('':::STRING,), NULL, (-3105008963224517653):::INT8)) AS tab_50761 (col_147533, col_147534, col_147535, col_147536, col_147537, col_147538, col_147539, col_147540, col_147541, col_147542, col_147543, col_147544)) SELECT '.':::STRING AS col_147545 LIMIT 1:::INT8), 3319214834:::OID, 3202006296:::OID, 1474824030:::OID), ('1970-01-10 04:08:45.000461+00:00':::TIMESTAMP, e'\x1aPF.\r':::STRING, 3962430047:::OID, e'yP{\x1dQ ':::STRING, 3377032960:::OID, 429531493:::OID, 1154219912:::OID), ('1970-01-09 18:56:54.000248+00:00':::TIMESTAMP, '{;=W-^':::STRING, 644902613:::OID, 'R':::STRING, 3269806531:::OID, NULL, 3989420997:::OID)) AS tab_50762 (col_147546, col_147547, col_147548, col_147549, col_147550, col_147551, col_147552)) , with_11481 (col_147553, col_147554, col_147555, col_147556) AS (SELECT * FROM (VALUES (e'DLb-\x07\x1f':::STRING, B'100100100011001100101010', 1955947210712375344:::INT8, '':::STRING), (e'\x1b':::STRING, B'110000111101000000100001', (-1971960013600805222):::INT8, 'wd':::STRING), (NULL, B'000011001111000101001110', NULL, e'\'':::STRING)) AS tab_50763 (col_147553, col_147554, col_147555, col_147556)) , with_11482 (col_147557, col_147558, col_147559, col_147560, col_147561) AS (SELECT * FROM (VALUES (1039843872:::OID, e'2$`UX9>\\I':::STRING, '6425595b-ca6b-4ade-9dda-8056c8bd81e8':::UUID, e'}\x1fHy[\x15\x1a':::STRING, 3372870353:::OID), (1801991604:::OID, e'R\x7f\nZ|x\n\\':::STRING, '5abbf24a-10df-4e73-8307-f1ef7f927cb1':::UUID, e'\x0eFm':::STRING, 3209597036:::OID), (1399294734:::OID, e'\x05P\x03]=V\x1a,M':::STRING, '0e8d999c-32c7-4e1c-90b1-21c0d444b31c':::UUID, e'\x00':::STRING, 673866952:::OID), (2066270621:::OID, NULL, '7048be39-0f36-4234-91d4-aedfc431bb9c':::UUID, e'MA_\x1em#/':::STRING, 75695349:::OID)) AS tab_50764 (col_147557, col_147558, col_147559, col_147560, col_147561)) SELECT 1615706988:::OID AS col_147562 FROM with_11481 WHERE false ORDER BY with_11481.col_147554 DESC LIMIT 1:::INT8), 2688513658074069665:::INT8, 1854276749:::OID, '1988-01-12':::DATE, (), '1970-01-10 00:59:10.000557+00:00':::TIMESTAMP, ARRAY[1458483560:::OID,739664878:::OID,1265660363:::OID], 3722221740:::OID, e'!6\x15\x18':::STRING, true, '01:10:26.194995':::TIME), ('>':::STRING, 116596730822574665:::INT8, 175468666:::OID, 5556862614214392760:::INT8, 2959319991:::OID, '1976-03-26':::DATE, (), '1970-01-06 06:49:03.000429+00:00':::TIMESTAMP, ARRAY[3499162075:::OID,1846573928:::OID,4178947111:::OID], 2675966294:::OID, e'\\:P\x0e\x02}':::STRING, true, '15:01:49.237727':::TIME), (e'\x1c4':::STRING, 5274640755360634193:::INT8, 1887264634:::OID, (-3219660759285201339):::INT8, 1816527809:::OID, NULL, (), '1970-01-07 08:33:18.000531+00:00':::TIMESTAMP, NULL, 1188062000:::OID, e'\x00':::STRING, false, NULL), (e'I\x1eM\x1aPX@\x11\t':::STRING, 350855008945300623:::INT8, 2890245119:::OID, 1260560996675042013:::INT8, 1310342273:::OID, '1995-09-26':::DATE, (), '3000-01-01 00:00:00+00:00':::TIMESTAMP, NULL, 1386779046:::OID, e'\x01\n\x1dv\t\x18f;\x19':::STRING, true, NULL)) AS tab_50765 (col_147563, col_147564, col_147565, col_147566, col_147567, col_147568, col_147569, col_147570, col_147571, col_147572, col_147573, col_147574, col_147575)) , with_11484 (col_147576, col_147577, col_147578, col_147579) AS (SELECT * FROM (VALUES (1813261624:::OID, '232.83.32.72/1':::INET, 345809514:::OID, '6f078e5d-17cc-4a72-9f06-e52f96ce78aa':::UUID), (1304901919:::OID, NULL, 477983419:::OID, '99330c1b-147b-4098-a27c-5a0992cc3d8c':::UUID), (1469696881:::OID, 'd06:304d:6e9b:fbf6:3b94:8c76:63af:e4c1/51':::INET, NULL, '6ab46672-b791-4331-8023-14c3c2d27963':::UUID), (788416335:::OID, NULL, 2875266124:::OID, NULL)) AS tab_50766 (col_147576, col_147577, col_147578, col_147579)) SELECT tab_50756._bytes::BYTES AS col_147580 FROM with_11484, with_11483)))
GROUP BY
	tab_50756._timestamp, tab_50756._decimal
HAVING
	bool_and(tab_50756._bool::BOOL)::BOOL
ORDER BY
	tab_50756._timestamp DESC
LIMIT
	84:::INT8;
```

```
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc001c5b100, 0x44a3b80, 0xc001a02cc0, 0x36b7720, 0xc001456970)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:727 +0x330
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc001c5b100, 0x44a3b80, 0xc001a02cc0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:440 +0x61
panic(0x36b7720, 0xc001456970)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xc002706e00, 0x44fc640, 0xc001892cd8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:167 +0x1e2
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0026a0a00, 0xc001c5b450, 0x44a4d00, 0xc0021b4000, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:179 +0x517
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.Run(0x44a3c40, 0xc002212b70, 0x44af4c0, 0xc0026a0a00, 0x4481780, 0xc002734380)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/base.go:171 +0x35
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0026a0a00, 0x44a3c40, 0xc002212b70)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:793 +0x92
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc001a69440, 0x44a3c40, 0xc002212b70, 0x3d781b0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:578 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000104120, 0xc0012939e0, 0xc0021fa480, 0xc000f9ba08, 0xc0026a2580, 0xc002706400, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:328 +0x368
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc000104120, 0x44a3c40, 0xc001b1a660, 0x8, 0xc0021b4060, 0x3, 0x1, 0x44a4d00, 0xc0021b4000, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:855 +0x7d5
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc000104120, 0x44a3c40, 0xc001b1a660, 0xc001c5b450, 0xc000f9bcc0, 0xc001cd2000, 0x12, 0x12, 0xc002406000, 0xc001c5b201, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:759 +0x1ba
github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).runRightSidePlan(0xc000d1ce00, 0x44a3c40, 0xc001b1a660, 0xc000f6d600, 0xc001c5b450, 0xc00226fc80, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:303 +0x26b
github.com/cockroachdb/cockroach/pkg/sql.(*applyJoinNode).Next(0xc000d1ce00, 0x44a3c40, 0xc001b1a660, 0xc000f6d600, 0xc001c5b450, 0x0, 0x3d78b50, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/apply_join.go:273 +0x6df
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc002505400, 0x203000, 0x3ab2f60, 0x10000c0002e82a0, 0x75d55c)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:171 +0x43c
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).accumulateRows(0xc001a99c00, 0x25b7e6d, 0xc0002e82a0, 0x3c1f129, 0x15, 0x36b66a0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:467 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashAggregator).Next(0xc001a99c00, 0x44a3c40, 0xc001b1a660, 0x3bff3d3, 0x8)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go:704 +0x14d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortTopKProcessor).Start(0xc00228c000, 0x44a3c40, 0xc001b1a660, 0x44a3b80, 0xc00038b600)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:407 +0xed
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*sortAllProcessor).Start(0xc00228c500, 0x44a3c40, 0xc001b1a660, 0x67938c0, 0x36b6620)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go:281 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc00228c500, 0x44a3c40, 0xc001b1a660)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:792 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc001cdb560, 0x44a3c40, 0xc001b1a660, 0x3d781b0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:578 +0x1e9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc000104120, 0xc000cd8840, 0xc0021fa480, 0xc000f9c878, 0xc0028362c0, 0xc001c5b528, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:328 +0x368
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc000104120, 0x44a3c40, 0xc002185d70, 0xc001c5b528, 0xc000cd8840, 0xc0021fa480, 0x44a5940, 0xc001cecd80, 0xc0028362c0, 0xc001c5b200)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:937 +0x217
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc001c5b100, 0x44a3c40, 0xc002185d70, 0xc001c5b450, 0x3, 0x7f85d96571c0, 0xc000113c68, 0xc000f9ca00, 0x0, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:902 +0x370
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc001c5b100, 0x44a3c40, 0xc002185d70, 0xc001c5b450, 0x7f85d96571c0, 0xc000113c68, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:734 +0x6e5
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc001c5b100, 0x44a3c40, 0xc002185d70, 0x44a92c0, 0xc00038b500, 0xc001c46000, 0x2021, 0x0, 0x5, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:417 +0xb64
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc001c5b100, 0x44a3c40, 0xc002185d70, 0x44a92c0, 0xc00038b500, 0xc001c46000, 0x2021, 0x0, 0x5, 0x0, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:99 +0x4ec
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc001c5b100, 0x44a3b80, 0xc00038b600, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1211 +0x1aba
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc001c5b100, 0x44a3b80, 0xc001a02cc0, 0xc000106340, 0x5400, 0x15000, 0xc0001063d8, 0xc001e944d0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1140 +0x1a3
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000592000, 0x44a3b80, 0xc001a02cc0, 0xc001c5b100, 0x5400, 0x15000, 0xc0001063d8, 0xc001e944d0, 0x0, 0x0)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:442 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1(0xc00244965f, 0xc00214da40, 0x44a3b80, 0xc001a02cc0, 0xc001e944d0, 0xc000592000, 0xc000113600, 0x44a7840, 0xc00214d9e0, 0xc002074300, ...)
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:584 +0x21c
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
	/home/mjibson/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:513 +0x17b
```

**Comment by mjibson** [comment] 2019-08-06 04:55
Woo a panic! These are hard to find nowadays.

**Comment by yuzefovich** [comment] 2019-08-06 05:27
I think it might be the same issue as #38867.

**Comment by jordanlewis** [comment] 2019-08-06 12:34
Yeah, this is a duplicate of #38867 (which I haven't made any progress on).

**Closed by jordanlewis** 2019-08-06 12:34 UTC
Labels: C-bug, O-sqlsmith
