### ISSUE TITLE
circleci: failed tests: TestDockerFinagle 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6037] opened 2016-04-13 14:58 UTC
The following test appears to have failed:

[#16246](https://circleci.com/gh/cockroachdb/cockroach/16246):

```
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:98)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:45)

FAILURES!!!
Tests run: 12,  Failures: 2

I160413 14:56:10.534985 acceptance/cluster/localcluster.go:649  stopping
I160413 14:56:10.535234 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160413 14:56:10.535254 acceptance/cluster/localcluster.go:570  events monitor exits
I160413 14:56:10.536494 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container bdee226c51368c0f28b2cffd14144c2338dad7d479fcdc4cbd897ea35093331f: Container bdee226c51368c0f28b2cffd14144c2338dad7d479fcdc4cbd897ea35093331f is not running
--- FAIL: TestDockerFinagle (20.92s)
	util_test.go:281: expected success: non-zero exit code: 1
=== RUN   TestGossipPeerings
I160413 14:56:20.451719 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160413 14:56:20.453377 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160413 14:56:21.871207 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.680813568
I160413 14:56:21.989742 acceptance/cluster/localcluster.go:532  events monitor starts
I160413 14:56:22.625368 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32832
  trace:     https://127.0.0.1:32832/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by dt** [comment] 2016-04-14 04:05
```
There were 2 failures:
1) A postgres client should update a row(com.twitter.finagle.postgres.integration.IntegrationSpec)
org.scalatest.exceptions.TestFailedException: OK(0) did not equal OK(1)
```
Another dupe of #5951

**Closed by dt** 2016-04-14 04:05 UTC
Labels: Robot, test-failure
