### ISSUE TITLE
stress: failed test in cockroach/storage/storage.test: TestBaseQueuePurgatory

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6825] opened 2016-05-20 12:07 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/b010e2ea2d2c3128b7c3de4a3b0f15e5bfd62624

Stress build found a failed test:

```
=== RUN   TestBaseQueuePurgatory
W160520 07:21:19.441971 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
--- FAIL: TestBaseQueuePurgatory (15.08s)
	queue_test.go:509: expected purgatory size of 10; got 9
	testing.go:113: storage/queue_test.go:525: condition failed to evaluate within 15s: storage/queue_test.go:522: expected 20 processed replicas; got 19
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
15 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
15 runs so far, 0 failures, over 50s
15 runs so far, 0 failures, over 55s
15 runs so far, 0 failures, over 1m0s
15 runs so far, 0 failures, over 1m5s
15 runs so far, 0 failures, over 1m10s
18 runs so far, 0 failures, over 1m15s
29 runs so far, 0 failures, over 1m20s
29 runs so far, 0 failures, over 1m25s
29 runs so far, 0 failures, over 1m30s
29 runs so far, 0 failures, over 1m35s
30 runs so far, 0 failures, over 1m40s
30 runs so far, 0 failures, over 1m45s
30 runs so far, 0 failures, over 1m50s
39 runs so far, 0 failures, over 1m55s
40 runs so far, 0 failures, over 2m0s
40 runs so far, 0 failures, over 2m5s
40 runs so far, 0 failures, over 2m10s
40 runs so far, 0 failures, over 2m15s
42 runs so far, 0 failures, over 2m20s
42 runs so far, 0 failures, over 2m25s
50 runs so far, 0 failures, over 2m30s
52 runs so far, 0 failures, over 2m35s
52 runs so far, 0 failures, over 2m40s
52 runs so far, 0 failures, over 2m45s
56 runs so far, 0 failures, over 2m50s
58 runs so far, 0 failures, over 2m55s
58 runs so far, 0 failures, over 3m0s
63 runs so far, 0 failures, over 3m5s
67 runs so far, 0 failures, over 3m10s
67 runs so far, 0 failures, over 3m15s
67 runs so far, 0 failures, over 3m20s
69 runs so far, 0 failures, over 3m25s
73 runs so far, 0 failures, over 3m30s
73 runs so far, 0 failures, over 3m35s
76 runs so far, 0 failures, over 3m40s
80 runs so far, 0 failures, over 3m45s
80 runs so far, 0 failures, over 3m50s
80 runs so far, 0 failures, over 3m55s
81 runs completed, 1 failures, over 3m56s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:52
Duplicate of #6342

**Closed by bdarnell** 2016-05-21 15:52 UTC
Labels: Robot, test-failure
