### ISSUE TITLE
storage: very slow restart of local cluster

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#26391] opened 2018-06-04 20:32 UTC
I created a 3-node local cluster using roachdemo on top of 98b1ceb6975874c5a8670b56e6540307ab791728 with minor unrelated modifications to the SQL layer. I created a simple table with 100 ranges but no data in it (`create table foo (k int primary key, v int); alter table foo [Csplit at select generate_series(0, 10000, 100);`).

I stopped the cluster for about a minute then restarted it, and after restarting it any query that tried to touch the table took multiple minutes to complete (e.g. `SHOW TESTING_RANGES FOR TABLE foo;` or `SELECT * FROM foo;`). After the first one succeeds, additional such queries complete in well under a second.

The cluster is hardly using any CPU, so it's not spinning on a bunch of real work.

The most suspicious bit I've noticed so far is a lot of raft election traffic until the moment when things start working:

<img width="1301" alt="screen shot 2018-06-04 at 3 02 40 pm" src="https://user-images.githubusercontent.com/7085343/40939982-ed1dd080-680b-11e8-9195-abe283a190a9.png">

<img width="698" alt="screen shot 2018-06-04 at 3 29 30 pm" src="https://user-images.githubusercontent.com/7085343/40940033-1bfc20aa-680c-11e8-88ae-815bcc3cc34a.png">

Also showing the slow startup is the very slow ramp-up of the replicas and leaseholders metrics:

<img width="986" alt="screen shot 2018-06-04 at 3 14 14 pm" src="https://user-images.githubusercontent.com/7085343/40940063-3269d8b4-680c-11e8-8b48-0300279a4145.png">

<img width="980" alt="screen shot 2018-06-04 at 3 14 18 pm" src="https://user-images.githubusercontent.com/7085343/40940054-2c6cb86e-680c-11e8-81a9-c080067ed3b7.png">

Maybe relevant is an "Invalid Lease" for range 9, the eventlog range, although that seems unlikely, particularly since it remains "Invalid" even after the cluster has started responding to queries quickly.

<img width="752" alt="screen shot 2018-06-04 at 3 16 24 pm" src="https://user-images.githubusercontent.com/7085343/40940057-2e986728-680c-11e8-8694-d78db1d301d9.png">

**Comment by a-robinson** [comment] 2018-06-04 20:39
Trace from a 2.5 minute `SHOW TESTING_RANGES`: https://gist.githubusercontent.com/a-robinson/14d7740fd58c221cd2bb089d5b18eed8/raw/c713b3f9ddb29b5ad75330bdae43333694342336/gistfile1.txt

**Comment by bdarnell** [comment] 2018-06-04 20:49
That looks like #26257. That commit was before the fix/workaround was merged in #26291.

**Comment by a-robinson** [comment] 2018-06-04 21:06
Actually, it looks like it's different. I've rebased on top of HEAD (5d2feacf867f19df37f53a5d53553c680c1b218b) and am still seeing the same behavior.

The trace suggests that what's happening is that the SQL plan for the query is hitting each range serially with a `LeaseInfo` request, and each range takes the full 3 second raft ticks timeout in order to respond to it. It's possibly still related to the recent unquiesced replica changes, but it isn't the exact same issue. For example:

```
| 2018-06-04 19:47:13.389449+00:00 | 3s601ms392µs381ns    | heartbeat 1528141642.885732004,0                                         | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | liveness heartbeat                                    |   68 |
| 2018-06-04 19:47:13.389479+00:00 | 3s601ms422µs462ns    | read-write path                                                          | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:13.389507+00:00 | 3s601ms450µs111ns    | applied timestamp cache                                                  | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:13.389815+00:00 | 3s601ms758µs530ns    | evaluated request                                                        | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:13.389826+00:00 | 3s601ms769µs139ns    | acquired {raft,replica}mu                                                | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.378799+00:00 | 6s590ms742µs654ns    | retry proposal 50397e81a2bd7e83: reasonTicks                             | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.378956+00:00 | 6s590ms899µs155ns    | applied timestamp cache                                                  | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.379316+00:00 | 6s591ms259µs198ns    | evaluated request                                                        | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.379326+00:00 | 6s591ms269µs722ns    | acquired {raft,replica}mu                                                | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.581442+00:00 | 6s793ms384µs914ns    | retry proposal 52d17b0bb61814c0: reasonNewLeader                         | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.581726+00:00 | 6s793ms669µs21ns     | applied timestamp cache                                                  | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.583367+00:00 | 6s795ms310µs768ns    | evaluated request                                                        | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.583413+00:00 | 6s795ms355µs946ns    | acquired {raft,replica}mu                                                | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.585453+00:00 | 6s797ms395µs860ns    | retry proposal 7ce5ca9e7298e9d4: reasonNewLeaderOrConfigChange           | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.585601+00:00 | 6s797ms544µs811ns    | applied timestamp cache                                                  | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.58639+00:00  | 6s798ms333µs721ns    | evaluated request                                                        | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.586431+00:00 | 6s798ms373µs989ns    | acquired {raft,replica}mu                                                | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
| 2018-06-04 19:47:16.589585+00:00 | 6s801ms528µs468ns    | command proposed from replica (n1,s1):1 with lease #3 incompatible       | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
|                                  |                      | to repl=(n1,s1):1 seq=4 start=1528141568.365333322,0 epo=3               |                                                                                                                       |                                 |                                                       |      |
|                                  |                      | pro=1528141633.385683914,0                                               |                                                                                                                       |                                 |                                                       |      |
| 2018-06-04 19:47:16.58965+00:00  | 6s801ms593µs206ns    | applying command with forced error: cannot replace lease repl=(n1,s1):1  | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
|                                  |                      | seq=4 start=1528141568.365333322,0 epo=3 pro=1528141633.385683914,0      |                                                                                                                       |                                 |                                                       |      |
|                                  |                      | with repl=(n1,s1):1 seq=4 start=1528141568.365333322,0 epo=3             |                                                                                                                       |                                 |                                                       |      |
|                                  |                      | pro=1528141633.385683914,0: proposed under invalid lease                 |                                                                                                                       |                                 |                                                       |      |
| 2018-06-04 19:47:16.590403+00:00 | 6s802ms346µs692ns    | replica.Send got error: cannot replace lease repl=(n1,s1):1 seq=4        | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | [async] storage.pendingLeaseRequest: requesting lease |   67 |
|                                  |                      | start=1528141568.365333322,0 epo=3 pro=1528141633.385683914,0            |                                                                                                                       |                                 |                                                       |      |
|                                  |                      | with repl=(n1,s1):1 seq=4 start=1528141568.365333322,0 epo=3             |                                                                                                                       |                                 |                                                       |      |
|                                  |                      | pro=1528141633.385683914,0: proposed under invalid lease                 |                                                                                                                       |                                 |                                                       |      |
| 2018-06-04 19:47:16.590588+00:00 | 6s802ms530µs888ns    | read has no clock uncertainty                                            | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | /cockroach.roachpb.Internal/Batch                     |   65 |
| 2018-06-04 19:47:16.590613+00:00 | 6s802ms556µs777ns    | command queue                                                            | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | /cockroach.roachpb.Internal/Batch                     |   65 |
| 2018-06-04 19:47:16.590658+00:00 | 6s802ms600µs991ns    | waiting for read lock                                                    | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | /cockroach.roachpb.Internal/Batch                     |   65 |
| 2018-06-04 19:47:16.590753+00:00 | 6s802ms696µs119ns    | read completed                                                           | [n1,s1,r41/1:/Table/52/1/1{700-800}]                                                                                  |                                 | /cockroach.roachpb.Internal/Batch                     |   65 |
```

**Comment by a-robinson** [comment] 2018-06-04 22:16
I'm still seeing the problem even after reverting your 4 recent unquiesced replica changes. Do you have any thoughts on what to look into? The initial election for each raft group appears to hit a stalemate where each replica votes for itself:

<img width="841" alt="screen shot 2018-06-04 at 5 10 53 pm" src="https://user-images.githubusercontent.com/7085343/40944483-90f5a3be-681a-11e8-927f-6ba7fcd71c58.png">

And then I guess it takes until `reasonTicks` fires for a new election to get kicked off? After that things move reasonably quickly.

This would mostly be a non-issue if batches were sent to more/all ranges in parallel (which I'd at least expect for `SELECT * FROM foo;`), but it still seems undesirable.

**Comment by bdarnell** [comment] 2018-06-04 22:18
Which specific ones did you revert? This stalemate sounds like it could be caused by 786954d3 or 44e39779

**Comment by a-robinson** [comment] 2018-06-04 22:28
Ah, I had missed that PR, but even after reverting them I'm still seeing the problem. I've now reverted https://github.com/cockroachdb/cockroach/pull/26297, https://github.com/cockroachdb/cockroach/pull/26291, https://github.com/cockroachdb/cockroach/pull/26269, https://github.com/cockroachdb/cockroach/pull/24956, and https://github.com/cockroachdb/cockroach/pull/24920, and it's still happening. It does not reproduce on 2.0.0.

**Comment by a-robinson** [comment] 2018-06-04 22:32
Wait, nevermind. After reverting all of #24920 and restarting a couple times, the queries now succeed quickly after the restart. I'm not sure why my first couple attempts after #24920 were still taking over a minute, but it may be because I wasn't waiting as long as I had been before between stopping and restarting the cluster.

Are you up for taking over? The repro steps are: create a 3 node local cluster, create a simple table with 100 ranges in it as shown in the initial comment, kill the cluster, wait until the last node has finished "gracefully" shutting down, then restart it and run `select * from yourtable`. It should return in no more than a couple seconds. In cases when it isn't working, it takes minutes.

**Comment by bdarnell** [comment] 2018-06-05 16:46
> The initial election for each raft group appears to hit a stalemate where each replica votes for itself:

And yet they're all in the follower state, not candidate. I think what's happening is that the range is being awakened for an incoming MsgVote, but before it processes that message, it initiates its own campaign (committing its vote for this term and sending out its own MsgVotes), then it has to reject the incoming vote request because it's already voted for itself.

**Comment by bdarnell** [comment] 2018-06-05 18:09
I've written this up as a roachtest in [this commit](https://github.com/bdarnell/cockroach/commit/e0bce4c63b1ff89a5f5e0933ec1705eef17d3b80). It only fails about half the time for me (in local mode on my laptop), making it annoying to figure out whether my change has made a difference.

**Comment by tschottdorf** [comment] 2018-06-06 13:04
I think I'm seeing the same thing restarting a (remote) three node cluster with 100k ranges:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/5076964/41039780-7d7f0a6a-6968-11e8-8032-4bf4c3840dac.png">

The kv load I'm running hovers at 200qps and is slowly climbing, but it used to do over 1000qps before I restarted the cluster.

**Comment by tschottdorf** [comment] 2018-06-12 09:19
Tried this again for #26448 -- sometimes 1s, but a run just now took 2m16s... I don't think we can call this closed.

**Comment by tschottdorf** [comment] 2018-10-11 10:20
What I was seeing here is likely along the lines of #30613 and we're fixing all of these bugs right now.

**Closed by tschottdorf** 2018-10-11 10:20 UTC
Labels: A-core-replication, C-cleanup
