### ISSUE TITLE
admission,debug: bump priority on debug.zip queries so they complete reliably under high load

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#93359] opened 2022-12-09 23:29 UTC
Some clusters under high load can struggle to generate a debug.zip, possibly due to AC.

We should increase their priority or find a way to bypass AC optionally so that we can reliably take debug info in adverse conditions.

Jira issue: CRDB-22285

**Comment by aadityasondhi** [comment] 2023-10-03 17:52
Duplicate of https://github.com/cockroachdb/cockroach/issues/72977

**Closed by aadityasondhi** 2023-10-03 17:52 UTC
Labels: C-enhancement, A-admission-control, T-observability-inf, A-observability-inf
