### ISSUE TITLE
sql: OFFSET not working correctly when used with ORDER BY

### ISSUE THREAD

**Issue by eldos-dl** [cockroachdb/cockroach#16310] opened 2017-06-04 11:08 UTC
**BUG REPORT**
```
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release
```
Code:
```
CREATE TABLE A (            
    id INT NOT NULL DEFAULT unique_rowid(),  
    name STRING(100) NOT NULL,               
    age INT NOT NULL,         
    CONSTRAINT "primary" PRIMARY KEY (id)
);
INSERT INTO A (name, age) VALUES ('A', 22);
INSERT INTO A (name, age) VALUES ('B', 23);

SELECT name, age FROM a;
-- +------+-----+
-- | name | age |
-- +------+-----+
-- | A    |  22 |
-- | B    |  23 |
-- +------+-----+

SELECT name, age FROM a LIMIT 1 OFFSET 1;
-- +------+-----+
-- | name | age |
-- +------+-----+
-- | B    |  23 |
-- +------+-----+
SELECT name, age FROM a ORDER BY name;
-- +------+-----+
-- | name | age |
-- +------+-----+
-- | A    |  22 |
-- | B    |  23 |
-- +------+-----+

SELECT name, age FROM a ORDER BY name LIMIT 1 OFFSET 1;
-- +------+-----+
-- | name | age |
-- +------+-----+
-- +------+-----+
```
In the last query we expect one matching row but it is not returning any rows.

**Comment by andreimatei** [comment] 2017-06-04 15:44
Thanks for the report!
This is a duplicate of #16090, which has been fixed. The fix will be available in a release in a few days.

**Closed by andreimatei** 2017-06-04 15:44 UTC
