### ISSUE TITLE
sentry: lease sequence jump

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#26315] opened 2018-06-01 13:13 UTC
Seen on two separate clusters, both running 2.0.0.

https://sentry.io/cockroach-labs/cockroachdb/issues/569535449/

```
*log.safeError: replica_proposal.go:250: lease sequence jump, prevLease=%s, newLease=%s | roachpb.Lease; roachpb.Lease
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 537, in handleReplicatedEvalResult
  File "github.com/cockroachdb/cockroach/pkg/storage/replica_proposal.go", line 796, in handleEvalResultRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 4809, in processRaftCommand
  File "github.com/cockroachdb/cockroach/pkg/storage/replica.go", line 3658, in handleRaftReadyRaftMuLocked
  File "github.com/cockroachdb/cockroach/pkg/storage/store.go", line 3799, in func1
...
(5 additional frame(s) were not displayed)

replica_proposal.go:250: lease sequence jump, prevLease=%s, newLease=%s | roachpb.Lease; roachpb.Lease
```

**Comment by nvanbenschoten** [comment] 2018-06-04 16:53
I'm having a hard time reasoning through what could have caused this assertion to trigger. I'll walk through why I think it's impossible (even though it's clearly not) and maybe that will reveal a logic error.

The `lease sequence jump` assertion checks that a new lease with a new sequence number always has a sequence that's exactly 1 larger than the Replica's current lease's sequence during Raft command application. This property should emerge because of two factors. First, new leases with incremented sequence numbers are always given sequences that are [greater than their "proposer lease's sequence" by 1](https://github.com/cockroachdb/cockroach/blob/a6b498b7aff14234bcde23107b9e7fa14e6a34a8/pkg/storage/batcheval/cmd_lease.go#L142). Second, we ensure that a lease request's "proposer lease" always has the [same sequence number](https://github.com/cockroachdb/cockroach/blob/a6b498b7aff14234bcde23107b9e7fa14e6a34a8/pkg/storage/replica.go#L4467) as the Replica's "current lease" during Raft command application. So for this assertion to trigger, one of these conditions needs to not hold, probably under some race condition or due to some strange interplay between snapshots and regular raft log application.

Right now I'm exploring whether there are situations where the second condition fails to be held. Specifically, one thing that's stood out to me on a re-read of this code is that a lease request can be [proposed](https://github.com/cockroachdb/cockroach/blob/a6b498b7aff14234bcde23107b9e7fa14e6a34a8/pkg/storage/replica.go#L2700) under a lease even though the request itself was evaluated using the [Replica's current lease](https://github.com/cockroachdb/cockroach/blob/a6b498b7aff14234bcde23107b9e7fa14e6a34a8/pkg/storage/batcheval/cmd_lease_transfer.go#L42). These leases don't need to be the same. I don't have any reason to think this could cause an issue like we see here, but nevertheless, it's suprising to me.

**Comment by tschottdorf** [comment] 2018-06-05 05:44
Can this be caused by https://github.com/cockroachdb/cockroach/pull/24228? This was fixed but is not on the release-2.0 branch.

**Comment by bdarnell** [comment] 2018-06-05 15:33
I don't think it could be #24228, although I'm not 100% sure. The bug there was that we were *only* looking at sequence numbers when we should have been looking at other things too.

**Comment by nvanbenschoten** [comment] 2018-06-05 15:40
Yeah, I don't think #24228 could have caused us to skip a sequence number. It had kind of the opposite effect.

**Comment by tschottdorf** [comment] 2018-06-05 15:43
In the absence of a better idea, we should make sure we see the actual leases here. Maybe the "jump" is really from zero to nonzero.

**Comment by nvanbenschoten** [comment] 2018-06-05 15:48
Extra logging is a good idea. The other option is to remove the assertion entirely. The only property we need out of lease sequence numbers is that they're monotonically increasing - jumps don't break anything. The only reason I'm worried about removing it is because the jump indicates that there's an interaction that we're not considering and it's possible that it's hiding other issues, so I'd prefer to understand how this is ever possible.

**Comment by nvanbenschoten** [comment] 2018-08-15 15:40
Last seen on June 18th and all events have been on 2.0.0. We don't have a resolution to this but we now have logging to help debug it in the future. Closing until this comes up again.

**Closed by nvanbenschoten** 2018-08-15 15:40 UTC
Labels: A-core-replication, C-bug, O-sentry, S-2-temp-unavailability
