### ISSUE TITLE
cdc: TestChangefeedProgressMetrics failed

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#123708] opened 2024-05-07 02:17 UTC
See [here](https://mesolite.cluster.engflow.com/invocations/default/11bf7857-6324-4a19-ba5f-a8e1b0df6cfd#targets-Ly9wa2cvY2NsL2NoYW5nZWZlZWRjY2w6Y2hhbmdlZmVlZGNjbF90ZXN0).
```
 helpers_test.go:864: making server as secondary tenant
    helpers_test.go:943: making pulsar feed factory
    changefeed_test.go:411: condition failed to evaluate within 45s: from changefeed_test.go:417: waiting for aggregator_progress to advance from 1715047555063225615 (value=1715047555063225615)
        --- FAIL: TestChangefeedProgressMetrics/running_changefeed/pulsar (46.65s)
```

Jira issue: CRDB-38493

**Comment by rharding6373** [comment] 2024-05-08 19:31
Duplicate of other pulsar test failures. Pulsar test changes have been rolled back.

**Closed by rharding6373** 2024-05-08 19:31 UTC
Labels: C-test-failure, X-duplicate, A-cdc, T-cdc
