### ISSUE TITLE
stats referencing dead nodes create unrecoverable failure in db console network page

### ISSUE THREAD

**Issue by dhartunian** [cockroachdb/cockroach#59322] opened 2021-01-22 22:43 UTC
**Describe the problem**

This was a customer issue where their node stats contained references to NodeIDs which were marked as "DEAD" in the liveness struct. However the code still attempted to retrieve stats for them since LIVE nodes had retained some network stats for the missing nodes. When the code attempts to render the network stats table, the uncaught failure causes a dead page.

**Expected behavior**
The network page should render without the DEAD nodes referenced.

Jira issue: CRDB-3303

**Comment by dhartunian** [comment] 2021-02-01 21:02
This PR may be helpful here: https://github.com/cockroachdb/cockroach/pull/56529

**Comment by florence-crl** [comment] 2021-02-24 22:36
Hi @dhartunian, do you have an estimate when this will be fixed? thanks!

**Comment by dhartunian** [comment] 2021-02-26 23:35
@florence-crl not at the moment. let us know if this is critical for next release or for a backport and we can re-prioritize

cc @thtruo

**Comment by florence-crl** [comment] 2021-03-23 20:46
Hi @dhartunian, for clarification, does PR: #56529 prevent this issue from happening? thanks!

**Comment by dhartunian** [comment] 2021-03-30 16:33
It appears that https://github.com/cockroachdb/cockroach/pull/56529 may fix the issue, I will reproduce by EOW and provide an update in this ticket.

**Comment by thtruo** [comment] 2022-02-18 21:24
I was able to reproduce this on 21.2.5 using roachprod

- I created a 5 node cluster and started 3 nodes (n1, n2, n3). I can load the Network Latency page
- I stopped n3. The Network Latency page correctly shows n3 is inactive
- I started n4. Now the Network Latency page errors out and is no longer accessible. I see this error in the browser dev console
<img width="994" alt="Image 2022-02-18 at 4 12 00 PM" src="https://user-images.githubusercontent.com/1474303/154762187-c163ca5c-ad03-4855-af4b-4d5a9f5545fe.png">
- Only when I restart n3 does the Network Latency page work again
- For fun, I decided to stop n3 again. This time, I started n5 and again I see that the Network Latency page breaks.

**Comment by Santamaura** [comment] 2022-03-14 17:32
Hi @thtruo I've been trying to reproduce this on the latest master build - `v22.1.0-alpha.2-360-geb4fc9a9c7` but i'm struggling to reproduce it. Specifically on step 2 of your above procedure after n3 is inactive I can no longer view/load any pages (I guess since the majority of nodes are down?). Any ideas on what i'm doing wrong/how I can reproduce it like you did? cc @dhartunian

**Comment by thtruo** [comment] 2022-03-22 15:30
Alex and I synced offline. So it looks like this issue is reproducible for v22.1 but it still affects 21.2.5+ 
Our next step is to ensure the change that prevents the page from breaking on 22.1 is backported to 21.2.x

**Comment by Santamaura** [comment] 2022-03-22 21:02
So it seemed a bit fishy to me that it wasn't occurring on latest but was on 21.2.x since the page flow is basically the same between the versions. I spent awhile testing and I actually can reproduce this on latest as well as 21.2.x. It seems to only occur when a nodes liveness status is `UNKNOWN` or `UNAVAILABLE` (this happens for a short amount of time when a node is stopped and isn't considered `DEAD` yet).  What was mentioned in https://github.com/cockroachdb/cockroach/pull/62917 is indeed still happening where the node is still being reported because it is not in a `DEAD` state yet but since it also isn't `LIVE` there is no returned `latency` value for that node. I'm thinking the best solution here might be to make the FE code more defensive in the `<Latency />` component and when no `latency` value is passed for a node we can set the value to `--`.

**Closed** 2022-03-28 15:24 UTC
Labels: C-bug, T-kv-observability
