### ISSUE TITLE
Test failure in CI build 9755

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3282] opened 2015-12-02 16:38 UTC
The following test appears to have failed:

[#9755](https://circleci.com/gh/cockroachdb/cockroach/9755):

```
E1202 16:37:04.466091 17502 acceptance/cluster/localcluster.go:400  node=1 status=restart
E1202 16:37:05.053760 17502 acceptance/cluster/localcluster.go:400  node=2 status=start
I1202 16:37:06.978568 17502 acceptance/gossip_peerings_test.go:159  waiting for gossip to be connected
E1202 16:37:06.980249 17502 acceptance/cluster/localcluster.go:400  node=2 status=restart
I1202 16:37:10.347192 17502 acceptance/cluster/localcluster.go:527  stopping
--- FAIL: TestGossipRestart (35.68s)
	testing.go:157: acceptance/gossip_peerings_test.go:63: condition failed to evaluate within 1s: acceptance/gossip_peerings_test.go:58: node 0: acceptance/gossip_peerings_test.go:86: sentinel not found
=== RUN   TestPut
I1202 16:37:17.905069 17502 acceptance/cluster/localcluster.go:213  started docker-spy: 172.17.0.33
I1202 16:37:17.905121 17502 acceptance/cluster/localcluster.go:220  initializing cluster
I1202 16:37:21.771409 17502 acceptance/cluster/localcluster.go:330  creating ca (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.701514733
I1202 16:37:21.841008 17502 acceptance/cluster/localcluster.go:335  creating node (1024bit) certs in: /home/ubuntu/cockroach/.localcluster.certs.701514733
I1202 16:37:25.142742 17502 acceptance/cluster/localcluster.go:383  *** started roach0.local ***
  ui:    https://0.0.0.0:32791
  trace: https://0.0.0.0:32791/debug/requests
  logs:  /tmp/circle-artifacts.oL1dIGT/acceptance/roach0.local/cockroach.INFO
--
I1202 16:38:32.897025 17502 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32805/_status/logs/3
I1202 16:38:32.905678 17502 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32805/_status/stacks/3
I1202 16:38:32.911008 17502 acceptance/status_server_test.go:67  OK response from https://0.0.0.0:32805/_status/nodes/3
I1202 16:38:33.011457 17502 acceptance/cluster/localcluster.go:527  stopping
--- PASS: TestStatusServer (16.90s)
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-12-02 22:04
Duplicate of #3134

**Closed by bdarnell** 2015-12-02 22:04 UTC
Labels: test-failure
