### ISSUE TITLE
foreign key, extra column added

### ISSUE THREAD

**Issue by armanraina** [cockroachdb/cockroach#15271] opened 2017-04-22 21:59 UTC
**BUG REPORT**

I170422 11:21:19.560936 1 util/log/clog.go:1007  [config] file created at: 2017/04/22 11:21:19
I170422 11:21:19.560936 1 util/log/clog.go:1007  [config] running on machine: arman-lioness
I170422 11:21:19.560936 1 util/log/clog.go:1007  [config] binary: CockroachDB CCL beta-20170413-dirty (linux amd64, built 2017/04/13 21:06:17, go1.8.1)
I170422 11:21:19.560936 1 util/log/clog.go:1007  [config] arguments: [cockroach start]

2. Please describe the issue you observed:

- What did you do? 

Using GORM with logging enabled, I created several tables using auto-migration and added foreign keys using raw query execution. I switched on logging to see the logs of the queries I was indirectly using. I then executed show constraints on a junction table I had created. 
Here are the logs:

[2017-04-22 11:21:27]  [6.94ms]  CREATE TABLE "answerdb_userdbs" ("userdb_id" integer,"answerdb_id" integer, PRIMARY KEY ("userdb_id","answerdb_id")) 

[2017-04-22 11:21:27]  [5.33ms]  CREATE TABLE "userdbs" ("id" serial,"username" text,"password" text,"email" text , PRIMARY KEY ("id")) 

[2017-04-22 11:21:27]  [5.98ms]  CREATE TABLE "answerdbs" ("id" serial,"sentence" text,"questiondb_id" integer , PRIMARY KEY ("id")) 

[2017-04-22 11:21:27]  [5.29ms]  CREATE TABLE "questiondbs" ("id" serial,"sentence" text,"userdb_id" integer , PRIMARY KEY ("id")) 

[2017-04-22 11:21:27]  [24.28ms]  ALTER TABLE questiondbs ADD CONSTRAINT userdb_fk FOREIGN KEY (userdb_id) REFERENCES userdbs(id);

[2017-04-22 11:21:27]  [20.73ms]  ALTER TABLE answerdbs ADD CONSTRAINT questiondb_fk FOREIGN KEY (questiondb_id) REFERENCES questiondbs(id);

[2017-04-22 11:21:27]  [20.69ms]  ALTER TABLE answerdb_userdbs ADD CONSTRAINT answerdb_fk FOREIGN KEY (answerdb_id) REFERENCES answerdbs(id);

[2017-04-22 11:21:27]  [22.75ms]  ALTER TABLE answerdb_userdbs ADD CONSTRAINT userdb_fk FOREIGN KEY (userdb_id) REFERENCES userdbs(id);

- What did you expect to see?
The actual result supplied below except with only userdb_id in the bottom row of the fourth column.
- What did you see instead?
![screenshot from 2017-04-22 14-50-30](https://cloud.githubusercontent.com/assets/13897679/25308528/2373c9a6-276b-11e7-8b26-3f64e80fcf67.png)

**Comment by jordanlewis** [comment] 2017-04-22 22:13
Thanks for the report. I was able to reproduce it easily (logs below).

I think this is an error in the `SHOW CONSTRAINTS FROM` mechanism rather than the foreign key mechanism itself, as the foreign key seems to behave correctly.

Assigning to @dt for further triage.

```
root@:26257/datablocks> create database arman;
CREATE DATABASE
root@:26257/datablocks> set database=arman;
SET
root@:26257/arman>  CREATE TABLE "answerdb_userdbs" ("userdb_id" integer,"answerdb_id" integer, PRIMARY KEY ("userdb_id","answerdb_id"));
CREATE TABLE
root@:26257/arman>  CREATE TABLE "userdbs" ("id" serial,"username" text,"password" text,"email" text , PRIMARY KEY ("id"));
CREATE TABLE
root@:26257/arman>  CREATE TABLE "answerdbs" ("id" serial,"sentence" text,"questiondb_id" integer , PRIMARY KEY ("id"));
CREATE TABLE
root@:26257/arman> CREATE TABLE "questiondbs" ("id" serial,"sentence" text,"userdb_id" integer , PRIMARY KEY ("id"));
CREATE TABLE
root@:26257/arman> ALTER TABLE questiondbs ADD CONSTRAINT userdb_fk FOREIGN KEY (userdb_id) REFERENCES userdbs(id);
ALTER TABLE
root@:26257/arman> ALTER TABLE answerdbs ADD CONSTRAINT questiondb_fk FOREIGN KEY (questiondb_id) REFERENCES questiondbs(id);
ALTER TABLE
root@:26257/arman> ALTER TABLE answerdb_userdbs ADD CONSTRAINT answerdb_fk FOREIGN KEY (answerdb_id) REFERENCES answerdbs(id);
ALTER TABLE
root@:26257/arman> ALTER TABLE answerdb_userdbs ADD CONSTRAINT userdb_fk FOREIGN KEY (userdb_id) REFERENCES userdbs(id);
ALTER TABLE
root@:26257/arman> SHOW CONSTRAINTS FROM answerdb_userdbs;
+------------------+-------------+---------------------------+------------------------+----------------+
|      Table       |    Name     |           Type            |       Column(s)        |    Details     |
+------------------+-------------+---------------------------+------------------------+----------------+
| answerdb_userdbs | answerdb_fk | FOREIGN KEY (UNVALIDATED) | answerdb_id            | answerdbs.[id] |
| answerdb_userdbs | primary     | PRIMARY KEY               | userdb_id, answerdb_id | NULL           |
| answerdb_userdbs | userdb_fk   | FOREIGN KEY (UNVALIDATED) | userdb_id, answerdb_id | userdbs.[id]   |
+------------------+-------------+---------------------------+------------------------+----------------+
(3 rows)
```

**Closed** 2017-04-25 23:44 UTC
Labels: community-questions
