### ISSUE TITLE
Postgres "bug" of ordering the empty array:

### ISSUE THREAD

**Issue by Shivs11** [cockroachdb/cockroach#102624] opened 2023-04-28 16:38 UTC
Currently, Postgres sorts the empty JSON array
before any other JSON values. An issue has been opened 
but no response was received from Postgres:
https://www.postgresql.org/message-id/17873-826fdc8bbcace4f1%40postgresql.org

An open PR exists which has replicated this functionality:
https://github.com/cockroachdb/cockroach/pull/101260

However, a decision has not been taken to merge this PR or not.
It is not evident if replicating this "bug" is worth it in CRDB since
the new SQL standard may define a JSON ordering which is 
different than the one found in Postgres. In the event that the 
new JSON ordering does not sort the empty array first, for
the ascending designation, this change will not be required.

Jira issue: CRDB-27565

**Comment by mgartner** [comment] 2023-08-04 20:03
Closing as duplicate of #105668.

**Closed by mgartner** 2023-08-04 20:03 UTC
Labels: C-enhancement, T-sql-queries
