### ISSUE TITLE
kvserver: flake in TestQuotaPool

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#59353] opened 2021-01-23 15:37 UTC
Observed in https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2608982?

```
------- Stdout: -------
=== RUN   TestQuotaPool
test_log_scope.go:73: test logs captured to: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestQuotaPool289873277
test_log_scope.go:74: use -show-logs to present logs inline
client_raft_test.go:2299: didn't observe the expected quota acquisition, available: 10000
panic.go:617: -- test log scope end --
test logs left over in: /go/src/github.com/cockroachdb/cockroach/artifacts/logTestQuotaPool289873277
--- FAIL: TestQuotaPool (0.83s)
```

cc @irfansharif @lunevalex for triage

**Comment by lunevalex** [comment] 2021-01-25 15:25
It reproduces pretty quickly under stress, I took a quick look and could not figure out why though. I can take a deeper look on Friday.

**Comment by lunevalex** [comment] 2021-02-02 18:18
Closing as dupe

**Closed by lunevalex** 2021-02-02 18:18 UTC
Labels: A-kv-replication, C-bug, C-test-failure, skipped-test
