### ISSUE TITLE
sql: planToStreamColMap mismatch: [0], [-1]

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#36182] opened 2019-03-26 21:28 UTC
```
CREATE TABLE t (
    _bool BOOL,
    _bytes BYTES,
    _date DATE,
    _decimal DECIMAL,
    _float4 FLOAT4,
    _float8 FLOAT8,
    _inet INET,
    _int4 INT4,
    _int8 INT8,
    _interval INTERVAL,
    _jsonb JSONB,
    _string STRING,
    _time TIME,
    _timestamp TIMESTAMP,
    _timestamptz TIMESTAMPTZ,
    _uuid UUID
);

WITH
    with_1448 (col_21216, col_21217, col_21255)
        AS (
            SELECT
                tab_7046._timestamp AS col_21216,
                CASE
                WHEN tab_7046._bool THEN B'00100111110000'
                ELSE (
                    B'11100001101110110100001101101100110011000011110001101110011110111001'::VARBIT
                    # (
                            (
                                B'1010110011'::VARBIT
                                | B'011110110000000111000101100010101001110110011000101001010100001110'::VARBIT
                            )::VARBIT
                            | CASE
                                WHEN tab_7046._bool THEN NULL
                                ELSE NULL
                                END::VARBIT
                        )::VARBIT
                )
                END
                    AS col_21217,
                (
                    SELECT
                        NULL AS col_21254
                    FROM
                        [
                            INSERT
                            INTO
                                defaultdb.public.t AS tab_7047
                            WITH
                                with_1446 (col_21218)
                                    AS (
                                        SELECT
                                            *
                                        FROM
                                            (
                                                VALUES
                                                    (
                                                        852383433688934788:::INT8
                                                    ),
                                                    (
                                                        7813099685921699019:::INT8
                                                    ),
                                                    (
                                                        399830444582409014:::INT8
                                                    ),
                                                    (
                                                        (-7867402869268206211):::INT8
                                                    ),
                                                    (
                                                        (-5628220479224208899):::INT8
                                                    )
                                            )
                                                AS tab_7048
                                                    (col_21218)
                                        UNION ALL
                                            SELECT
                                                tab_7049._int8
                                                    AS col_21219
                                            FROM
                                                defaultdb.public.t
                                                    AS tab_7049
                                    ),
                                with_1447
                                    (
                                        col_21220,
                                        col_21221,
                                        col_21222,
                                        col_21223,
                                        col_21224,
                                        col_21225,
                                        col_21226,
                                        col_21227,
                                        col_21228,
                                        col_21229,
                                        col_21230,
                                        col_21231,
                                        col_21232,
                                        col_21233,
                                        col_21234,
                                        col_21235,
                                        col_21236,
                                        col_21237
                                    )
                                    AS (
                                        SELECT
                                            ret_2923 AS col_21220,
                                            '{":kKs/>1>_,X7": false, "b": {}, "baz": false, "foo": {"b": true, "foo": {"Dnno]M": "bar", "c": true, "foo": {}}}, "foobar": [{"r}+": 0.5362634059851421}]}':::JSONB
                                                AS col_21221,
                                            ret_2923 AS col_21222,
                                            '1978-04-27':::DATE
                                                AS col_21223,
                                            ret_2919 AS col_21224,
                                            7037762997267190135:::INT8
                                                AS col_21225,
                                            'yQ/n':::STRING
                                                AS col_21226,
                                            e'\\x60f51af6':::BYTES
                                                AS col_21227,
                                            ret_2923 AS col_21228,
                                            ret_2921 AS col_21229,
                                            '1970-01-06 11:21:21.000132+00:00':::TIMESTAMPTZ
                                                AS col_21230,
                                            false AS col_21231,
                                            NULL AS col_21232,
                                            79039725:::OID
                                                AS col_21233,
                                            ret_2918 AS col_21234,
                                            false AS col_21235,
                                            NULL AS col_21236,
                                            B'001011101011011101011011101000110100111110101110100'
                                                AS col_21237
                                        FROM
                                            [
                                                DELETE FROM
                                                    defaultdb.public.t
                                                        AS tab_7050
                                                RETURNING
                                                    3887041059:::OID
                                                        AS ret_2914,
                                                    '17:57:16.359657':::TIME
                                                        AS ret_2915,
                                                    70320.6310850762218:::DECIMAL
                                                        AS ret_2916,
                                                    '805e:7633:845:52f4:51ae:3b6e:1b83:f94f/120':::INET
                                                        AS ret_2917,
                                                    6217678276303640116:::INT8
                                                        AS ret_2918,
                                                    NULL AS ret_2919,
                                                    '9c36:f165:2d47:7a06:a298:cebe:eaa0:71c5/119':::INET
                                                        AS ret_2920,
                                                    0.2640589700082572:::FLOAT8
                                                        AS ret_2921,
                                                    0.33268963674711216:::FLOAT8
                                                        AS ret_2922,
                                                    (-3973464773959783847):::INT8
                                                        AS ret_2923,
                                                    _timestamp
                                                        AS ret_2924,
                                                    _timestamp
                                                        AS ret_2925,
                                                    0.25059712645800203:::FLOAT8
                                                        AS ret_2926,
                                                    '1970-01-09 12:56:26.000648+00:00':::TIMESTAMP
                                                        AS ret_2927,
                                                    B'011000000111100000011100000000011101000011110001010010101110100001111010111'
                                                        AS ret_2928,
                                                    '15:01:50.530636':::TIME
                                                        AS ret_2929,
                                                    _inet AS ret_2930
                                            ],
                                            with_1446
                                        WHERE
                                            false
                                    )
                            SELECT
                                false AS col_21238,
                                tab_7051._bytes AS col_21239,
                                '1992-11-14':::DATE AS col_21240,
                                tab_7051._decimal AS col_21241,
                                (-0.027862337298586115):::FLOAT8
                                    AS col_21242,
                                tab_7051._float4 AS col_21243,
                                '140.197.102.74/19':::INET
                                    AS col_21244,
                                with_1447.col_21225 AS col_21245,
                                with_1447.col_21234 AS col_21246,
                                '26 years 441 days 13:03:14.53602':::INTERVAL
                                    AS col_21247,
                                with_1447.col_21221 AS col_21248,
                                NULL AS col_21249,
                                tab_7051._time AS col_21250,
                                '1970-01-11 12:33:31.00025+00:00':::TIMESTAMP
                                    AS col_21251,
                                tab_7051._timestamptz AS col_21252,
                                NULL AS col_21253
                            FROM
                                defaultdb.public.t AS tab_7051,
                                with_1447
                            ORDER BY
                                tab_7051._bool DESC
                            LIMIT
                                42:::INT8
                            RETURNING
                                _int4 AS ret_2931,
                                _time AS ret_2932,
                                _uuid AS ret_2933,
                                _inet AS ret_2934,
                                B'01011110011110000000000001000010'
                                    AS ret_2935,
                                NULL AS ret_2936,
                                _jsonb AS ret_2937,
                                NULL AS ret_2938
                        ],
                        defaultdb.public.t AS tab_7052,
                        defaultdb.public.t AS tab_7053
                    WHERE
                        tab_7053._bool
                    LIMIT
                        1:::INT8
                )
                    AS col_21255
            FROM
                defaultdb.public.t AS tab_7046
            WHERE
                tab_7046._bool
        )
SELECT
    DISTINCT
    tab_7054._string AS col_21256,
    1676241776396717940:::INT8 AS col_21257,
    tab_7054._string AS col_21258,
    '1989-09-02':::DATE AS col_21259
FROM
    defaultdb.public.t AS tab_7054, defaultdb.public.t AS tab_7055
WHERE
    NULL
ORDER BY
    col_21259 ASC, col_21258 DESC, col_21256
LIMIT
    39:::INT8;
```

Error:

`pq: planToStreamColMap mismatch: [0], [-1]`

**Comment by jordanlewis** [comment] 2019-03-26 21:48
@solongordon looks like this was produced during set op physical planning:

```
	// Check that the left and right side PlanToStreamColMaps are equivalent.
	// TODO(solon): Are there any valid UNION/INTERSECT/EXCEPT cases where these
	// differ? If we encounter any, we could handle them by adding a projection on
	// the unioned columns on each side, similar to how we handle mismatched
	// ResultTypes.
	if !reflect.DeepEqual(leftPlan.PlanToStreamColMap, rightPlan.PlanToStreamColMap) {
		return PhysicalPlan{}, errors.Errorf(
			"planToStreamColMap mismatch: %v, %v", leftPlan.PlanToStreamColMap,
			rightPlan.PlanToStreamColMap)
	}
```

Here's the stack trace up to the error getting returned:

```
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForSetOp(0xc0000f4280, 0xc000ab89c0, 0xc0012c20a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2855 +0x211c
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744fda0, 0xc0012c20a0, 0xc00118b500, 0x2, 0x2, 0xc0003bd360, 0x1, 0x1, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2360 +0x21aa
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc0000f4280, 0xc000ab89c0, 0xc0002560e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2177 +0x196
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f520, 0xc0002560e0, 0x0, 0x0, 0xc000872ea0, 0x1, 0x1, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2304 +0x20a3
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f860, 0xc00118c360, 0xc000872ea0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2307 +0x1395
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc0000f4280, 0xc000ab89c0, 0xc000256d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2177 +0x196
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f520, 0xc000256d20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2304 +0x20a3
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f860, 0xc00118c000, 0x2020202020202020, 0x2020202020202020, 0x2020202020202020, 0x372d282020202020, 0x3638323034373638, 0x3236303238363239, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2307 +0x1395
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744fc20, 0xc0012c3860, 0x2c343139325f7465, 0x202020202020200a, 0x2020202020202020, 0x2020202020202020, 0x2020202020202020, 0x2020202020202020, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2327 +0x77e
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f560, 0xc0012c38b0, 0x7487a60, 0x8e5b7cf, 0x74881e0, 0xc0019b20a0, 0x74881e0, 0xc0019b20b0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2345 +0x1a35
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan.func1(0x744dc60, 0xc00089ba40, 0x6cdb0b4, 0x5, 0x744f560, 0xc0012c38b0, 0xc0019b2200, 0x74881e0, 0xc0019b2210)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2466 +0x178
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8c00, 0x744f560, 0xc0012c38b0, 0x6cdb0b4, 0x5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:135 +0x5932
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8c00, 0x744f560, 0xc0012c38b0, 0x6, 0x744f4e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8c00, 0x744f4e0, 0xc0012f0780, 0x6cdcda0, 0x6)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:454 +0x4911
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitConcrete(0xc000ab8c00, 0x744f4e0, 0xc0012f0780)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:125 +0x81
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8c00, 0x744fa20, 0xc001478f30, 0x6cd8852, 0x3)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:532 +0x5577
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8c00, 0x744fa20, 0xc001478f30, 0x203000, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x744dc60, 0xc00089ba40, 0x744fa20, 0xc001478f30, 0x0, 0xc0011029c0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:76 +0x1a4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan(0xc0000f4280, 0xc000ab89c0, 0x744fa20, 0xc001478f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2447 +0x1ed
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744fa20, 0xc001478f30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2401 +0x13f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f860, 0xc00118cd80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2307 +0x1395
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan.func1(0x744dc60, 0xc00089ba40, 0x6cdd3be, 0x6, 0x744f860, 0xc00118cd80, 0x0, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2466 +0x178
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8ba0, 0x744f860, 0xc00118cd80, 0x6cdd3be, 0x6)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:135 +0x5932
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8ba0, 0x744f860, 0xc00118cd80, 0x5, 0x744fca0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8ba0, 0x744fca0, 0xc001479860, 0x6cdb59b, 0x5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:577 +0x432c
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8ba0, 0x744fca0, 0xc001479860, 0x203000, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x744dc60, 0xc00089ba40, 0x744fca0, 0xc001479860, 0x0, 0xc001102980, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:76 +0x1a4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan(0xc0000f4280, 0xc000ab89c0, 0x744fca0, 0xc001479860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2447 +0x1ed
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744fca0, 0xc001479860, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2401 +0x13f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForJoin(0xc0000f4280, 0xc000ab89c0, 0xc000257260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2173 +0xe0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f520, 0xc000257260, 0x1, 0x1, 0xc000440e00, 0x74557e0, 0x92e2248, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2304 +0x20a3
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f860, 0xc000104fc0, 0xc00003a000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2307 +0x1395
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f560, 0xc0012c3e50, 0x0, 0x0, 0x0, 0xc0017e4228, 0x5977a96, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2345 +0x1a35
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f560, 0xc0011d2190, 0xc0017e53b8, 0xc00118c360, 0x0, 0xc000facc90, 0x74691e0, 0xc0008cce00, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2345 +0x1a35
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan.func1(0x744dc60, 0xc00089ba40, 0x6cdb0b4, 0x5, 0x744f560, 0xc0011d2190, 0x100000000000000, 0x0, 0x120)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2466 +0x178
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8ae0, 0x744f560, 0xc0011d2190, 0x6cdb0b4, 0x5)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:135 +0x5932
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8ae0, 0x744f560, 0xc0011d2190, 0x7, 0x744f5e0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc000ab8ae0, 0x744f5e0, 0xc001479260, 0x6cdf51b, 0x7)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:321 +0x41d1
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc000ab8ae0, 0x744f5e0, 0xc001479260, 0x203000, 0x8)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:112 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x744dc60, 0xc00089ba40, 0x744f5e0, 0xc001479260, 0x0, 0xc001102940, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:76 +0x1a4
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).wrapPlan(0xc0000f4280, 0xc000ab89c0, 0x744f5e0, 0xc001479260, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2447 +0x1ed
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc0000f4280, 0xc000ab89c0, 0x744f5e0, 0xc001479260, 0x744f5e0, 0xc001479260, 0x0, 0x8, 0xc0004977a0, 0x2, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2401 +0x13f
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc0000f4280, 0x744dc60, 0xc00089ba40, 0x0, 0xc00089b7d0, 0x4, 0x1, 0x744f5e0, 0xc001479260, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:728 +0x44c
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc0000f4280, 0x744dc60, 0xc00089ba40, 0xc000facbd0, 0xc00042df20, 0xc001102380, 0x1, 0x1, 0xc0016b42c0, 0xc000faca01, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:666 +0x1ba
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000fac880, 0x744dc60, 0xc00089ba40, 0xc000facbd0, 0x3, 0xf5a0520, 0xc0008ead10, 0x1, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1112 +0x3d4
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000fac880, 0x744dc60, 0xc00089ba40, 0xc000facbd0, 0xf5a0520, 0xc0008ead10, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:957 +0x658
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000fac880, 0x744dc60, 0xc00089ba40, 0x74537a0, 0xc00087dd00, 0xc00117a000, 0x2eba, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:459 +0xdf6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000fac880, 0x744dc60, 0xc00089ba40, 0x74537a0, 0xc00087dd00, 0xc00117a000, 0x2eba, 0x0, 0x0, 0x0, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:101 +0x610
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000fac880, 0x744dba0, 0xc001582e40, 0xc00022c7b8, 0x5400, 0x15000, 0xc00022c850, 0xc000410c50, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1183 +0x21c8
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000b5edc0, 0x744dba0, 0xc001582e40, 0xc000fac880, 0x5400, 0x15000, 0xc00022c850, 0xc000410c50, 0x0, 0x0)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:433 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000b5edc0, 0x744dba0, 0xc001582e40, 0xc000111600, 0xc000405104, 0xc000410c50, 0xc000fac880, 0x5400, 0x15000, 0xc00022c850, ...)
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:338 +0xe6
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/repo/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:321 +0x1080
```

**Comment by asubiotto** [comment] 2019-05-14 14:30
Simplified the query a bit:
```
WITH
    with_1448 (col_21255)
        AS (
            SELECT
                (
                    SELECT
                        NULL AS col_21254
                    FROM
                        [
                            INSERT
                            INTO
                                defaultdb.public.t AS tab_7047
                            WITH
                                with_1446 (col_21218)
                                    AS (
                                        SELECT
                                            *
                                        FROM
                                            (VALUES (852383433688934788:::INT8))
                                        UNION ALL
                                            SELECT
                                                NULL
                                            FROM
                                                defaultdb.public.t AS tab_7049
                                    ),
                                with_1447 (col_21228)
                                    AS (SELECT NULL FROM with_1446)
                            SELECT
                                NULL AS col_21253
                            FROM
                                with_1447
                            RETURNING
                                NULL AS ret_2938
                        ]
                )
                    AS col_21255
            FROM
                defaultdb.public.t AS tab_7046
        )
SELECT
    tab_7054._string
FROM
    defaultdb.public.t AS tab_7054;
```
I think the correct behavior of this query would be to error out with: `pq: unimplemented: common table expression "with_1448" with side effects was not used in query` according to #24307

**Comment by asubiotto** [comment] 2019-05-14 17:23
Weirdly enough, when I put `EXPLAIN (OPT)` before the query, it errors out with the correct error.

The reason the query fails is that the union:
```
SELECT
    *
FROM
    (VALUES (852383433688934788:::INT8))
UNION ALL
    SELECT
        NULL
    FROM
        defaultdb.public.t AS tab_7049;
```
plans a table reader for the `SELECT NULL..` side which gets passed in a scan node with 17 columns (the columns in the table): https://github.com/cockroachdb/cockroach/blob/5fe38b2d251bd084108f5230509340a7d3c660a8/pkg/sql/scan.go#L52-L53. The `outCols` in `createTableReaders` is empty:
https://github.com/cockroachdb/cockroach/blob/5fe38b2d251bd084108f5230509340a7d3c660a8/pkg/sql/distsql_physical_planner.go#L1183-L1190
So `planToStreamColMap` is just a bunch of `-1`s that gets translated to a `[-1]` after the render.

Extracting this union and running it alone results in no error. Both `planStreamToColMap`s are `[0]`. The difference seems to be that the scan node has 0 columns and the render is a NULL `TypedExpr` rather than a `CastExpr`. I'm unclear as to what the expectation/desired result is here.

**Comment by asubiotto** [comment] 2019-05-15 19:58
So I talked to @justinj and it seems that the reason `EXPLAIN (OPT)` errors out with the correct error while running the query itself produces the `planStreamToColMap` error in the distsql_physical_planner is that the optimizer returns unimplemented errors when running `EXPLAIN (OPT)` but falls back to the heuristic planner during normal planning.

This explains why running the `UNION` query separately versus as part of the larger query results in different `scanNode`s: the larger query is planned by the heuristic planner due to encountering `pq: unimplemented: common table expression "with_1448" with side effects was not used in query` in the optimizer.

Since this fall back behavior is being deleted this release, I'll wait for that to close this issue.

**Comment by asubiotto** [comment] 2019-05-17 15:14
Closing as wontfix due to "caused by heuristic planner"

**Closed by asubiotto** 2019-05-17 15:14 UTC
Labels: C-bug, O-sqlsmith, X-wontfix
