### ISSUE TITLE
sql: java.sql.PreparedStatement's setFloat fails on columns of type DECIMAL

### ISSUE THREAD

**Issue by arjunravinarayan** [cockroachdb/cockroach#14311] opened 2017-03-22 16:01 UTC
The following query (from OLTPBench's TPCC workload) succeeds in Postgres but fails in CockroachDB. First the schema:

```
CREATE TABLE item (
  i_id int NOT NULL,
  i_name varchar(24) NOT NULL,
  i_price decimal(5,2) NOT NULL,
  i_data varchar(50) NOT NULL,
  i_im_id int NOT NULL,
  PRIMARY KEY (i_id)
);
```

Then the query and its error:

```
11:47:23,829 (TPCCLoader.java:215) ERROR - Failed to load data for TPC-C
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO ITEM VALUES (1, 'sxvnjhpdqdxvcras', 76.24, 'vybcwvmgnykrxvzxkgxtspsjdgyluegq', 6069) was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:134)
	at org.postgresql.core.v3.QueryExecutorImpl$ErrorTrackingResultHandler.handleError(QueryExecutorImpl.java:325)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2024)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1204)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1229)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:1026)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1661)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader.loadItems(TPCCLoader.java:202)
	at com.oltpbenchmark.benchmarks.tpcc.TPCCLoader$1.load(TPCCLoader.java:85)
	at com.oltpbenchmark.api.Loader$LoaderThread.run(Loader.java:65)
	at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:343)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
11:47:23,830 (TPCCLoader.java:216) ERROR - BatchUpdateException Cause => ERROR: value type float doesn't match type DECIMAL of column "i_price"
j
```

This failure is probably because JDBC is setting some postgres OID(?) in [the call to `setDouble`](https://github.com/oltpbenchmark/oltpbench/blob/master/src/com/oltpbenchmark/benchmarks/tpcc/TPCCLoader.java#L195) and we are being too picky about that.

@nvanbenschoten I'm unsure who to assign to, so if you're not the right candidate do you mind triaging this to the right person? Thank you!

**Comment by jordanlewis** [comment] 2017-03-22 18:00
This is related to #14245. As Arjun mentions, the issue here is probably the type hint that JDBC sends for `setDouble` not matching the oid for decimal.

**Comment by jordanlewis** [comment] 2017-03-25 04:42
Upon further investigation, it seems that this is a little bit different from the issue in #14245. The type mismatch here seems to completely evade the type checker, only getting caught at the last second by `MarshalColumnValue` when trying to marshal the input `DFloat` into a `ColumnType_DECIMAL`. The stack trace is below.

```
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.MarshalColumnValue(0xc420b46103, 0x5, 0x1, 0x200000003, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/table.go:1351 +0x113
github.com/cockroachdb/cockroach/pkg/sql.(*RowInserter).InsertRow(0xc420b01440, 0x8096cc0, 0xc420e1ff80, 0x5fc8940, 0xc420c04300, 0xc420970760, 0x2, 0x2, 0x0, 0xc420b46170, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/rowwriter.go:238 +0x115
github.com/cockroachdb/cockroach/pkg/sql.(*tableInserter).row(0xc420b01440, 0x8096cc0, 0xc420e1ff80, 0xc420970760, 0x2, 0x2, 0x2, 0x1, 0xed067e899, 0x39b89ba4, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/tablewriter.go:95 +0x87
github.com/cockroachdb/cockroach/pkg/sql.(*insertNode).Next(0xc42076d1e0, 0x8096cc0, 0xc420e1ff80, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:327 +0x2c7
github.com/cockroachdb/cockroach/pkg/sql.countRowsAffected(0x8096cc0, 0xc420e1ff80, 0x5fe0220, 0xc42076d1e0, 0xc42076d1e0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:804 +0x84
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execClassic(0xc420106680, 0xc420a421a0, 0x5fe0220, 0xc42076d1e0, 0xc420ac0420, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1298 +0xf5
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmt(0xc420106680, 0x5fd7cc0, 0xc42075c550, 0xc420a421a0, 0xc420106601, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1414 +0x520
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtInOpenTxn(0xc420106680, 0x5fd7cc0, 0xc42075c550, 0xc420a421a0, 0x101, 0xc420a42068, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:1168 +0x32a
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execStmtsInCurrentTxn(0xc420106680, 0xc42035d810, 0x1, 0x1, 0xc420a421a0, 0xc420a42068, 0x101, 0x0, 0x3, 0xc420497380, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:918 +0x863
github.com/cockroachdb/cockroach/pkg/sql.runTxnAttempt(0xc420106680, 0xc420a421a0, 0x1, 0xc420a42068, 0xc42035d908, 0xc42035d810, 0x1, 0x1, 0x0, 0xc420ac0c70, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:833 +0x100
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest.func2(0x8096cc0, 0xc420e1ff80, 0xc420b85040, 0xc42035d908, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:672 +0x1af
github.com/cockroachdb/cockroach/pkg/internal/client.(*Txn).Exec(0xc420b85040, 0x8096cc0, 0xc420e1ff80, 0x10101, 0xc4207f04e0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/txn.go:591 +0xb6
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).execRequest(0xc420106680, 0xc420a42000, 0xc420a45372, 0x1e, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:694 +0x614
github.com/cockroachdb/cockroach/pkg/sql.(*Executor).ExecuteStatements(0xc420106680, 0xc420a42000, 0xc420a45372, 0x1e, 0xc420ac1498, 0x0, 0x0, 0x0, 0xc420a45300)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/executor.go:503 +0x180
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).executeStatements(0xc42072a000, 0xc420a45372, 0x1e, 0xc420ac1498, 0x6460c38, 0x0, 0x0, 0x642a900, 0x1, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:831 +0x94
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).handleExecute(0xc42072a000, 0xc42072a028, 0xc4202fb140, 0xc42072a045)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:818 +0x172
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*v3Conn).serve(0xc42072a000, 0x8096cc0, 0xc420402a50, 0xc42074e310, 0x5400, 0xc4202d0310, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go:450 +0xb37
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*Server).ServeConn(0xc4202d01c0, 0x8096da0, 0xc420792300, 0x5fe0be0, 0xc420a8c640, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/server.go:415 +0x927
github.com/cockroachdb/cockroach/pkg/server.(*Server).Start.func9.1(0x5fe0be0, 0xc420a8c640)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:587 +0x153
github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith.func1(0xc4204200a0, 0xc42023c020, 0x5fe0be0, 0xc420a8c640, 0xc4202de060)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:136 +0x95
created by github.com/cockroachdb/cockroach/pkg/util/netutil.(*Server).ServeWith
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/util/netutil/net.go:138 +0x239
I170325 00:27:05.969013 201 sql/executor.go:705  [client=127.0.0.1:53096,user=root,n1] execRequest: error: value type float doesn't match type DECIMAL of column "price"
```

The type checker should be catching this mismatch before this marshalling failure. I'm not really sure where this check should be happening, though - paging @nvanbenschoten for his thoughts.

As a general fix, I'm exploring the idea of using the `CastExpr` machinery to transparently cast placeholder values of the wrong type to the correct type when possible.

**Comment by nvanbenschoten** [comment] 2017-03-27 09:01
Thanks for looking into this @jordanlewis. I'm not sure exactly how the type mismatch is evading the type checker, but I suspect it has to do with us using `TypeCheck` instead of `TypeCheckAndRequire` somewhere in the `valuesNode` used by an `insertNode`. If that is the case, then we will avoid asserting the correct top-level type in the expression tree. Just to confirm, that stack trace wasn't from a panic, correct? The only difference was that we return a slightly different error? If that is the case, then I think the divergent behavior might actually be intended so that we return more specific errors on INSERTS of incorrect types.

In terms of addressing this issue (and #14245), I've gone back and forth on a few different alternatives. Wrapping the placeholder in a cast when necessary may actually be one of the better options available. It would be a localized version of implicit casts, which I think is justifiable given the apparent imprecision in client driver handling of placeholder types. On the surface, it looks like the fix would actually be pretty small too, as the following prototype seems to get OLTPBench's TPCC working:

```
func (expr *Placeholder) TypeCheck(ctx *SemaContext, desired Type) (TypedExpr, error) {
	// If there is a value known already, immediately substitute with it.
	if v, ok := ctx.Placeholders.Value(expr.Name); ok {
		if !desired.Equivalent(v.ResolvedType()) {
			t, err := DatumTypeToColumnType(desired)
			if err != nil {
				return nil, err
			}
			cast := &CastExpr{Expr: v, Type: t}
			return cast.TypeCheck(ctx, desired)
		}
		return v, nil
	}
	...
```

**Comment by jordanlewis** [comment] 2017-03-27 15:48
Yes, the stack trace wasn't a panic - I just dumped the stack where the error was getting returned so I could understand what was going on better. I've confirmed that this error path is in fact used by `INSERT` statements with invalid input values. I suppose it makes some sense to let the mismatch fall through to the marshaller to get a better error message. On the other hand, it's a bit surprising to me that the type checker wouldn't be responsible for catching type mismatches like these and producing a good error message.

Your proposed fix is exactly what I had in mind, and I've independently confirmed that it fixes the issue. I'll prepare a PR that uses the same strategy to fix #14245 as well.

**Comment by jordanlewis** [comment] 2017-03-29 22:41
I mentioned this offline to @arjunravinarayan, but adding to this issue for posterity:

For what it's worth, even though Postgres accepts this type hint as valid, this really is an invalid type hint. The program is sending a `float` type hint for a `decimal` column. Floats are not decimals! The program could be fixed by using `setBigDecimal` instead of `setFloat`.

**Comment by arjunravinarayan** [comment] 2017-03-30 14:06
I can confirm that with switching all instances of `setFloat` and `setInt` to `setBigDecimal` in the OLTPBench TPCC Loader, the rest of the loader runs fine. I will now check out running the actual benchmark. Thank you @jordanlewis!

**Comment by jordanlewis** [comment] 2017-03-30 14:55
I'm surprised that you had to change the `setInt` instances to `setBigDecimal`, because unless the program was incorrectly sending integer type hints for decimal columns, you're now sending decimal type hints for the integer columns that used to be set with `setInt`. Probably you only wanted to change the (incorrect) instances of `setFloat`. If that didn't work for you, please send along the errors you encountered!

**Comment by dianasaur323** [comment] 2017-04-19 17:47
@arjunravinarayan it looks like there might not be any more action items associated with this issue?

**Comment by arjunravinarayan** [comment] 2017-04-19 17:58
#14387 is still open. This one has a workaround (manually changing the type hints) but this issue still isn't closed until the allow-imprecise-type-hints PR is merged.

**Comment by dianasaur323** [comment] 2017-04-19 22:39
Gotcha - ok, seems like it should be merged soon.

**Comment by arjunravinarayan** [comment] 2017-05-02 16:42
@jordanlewis assigning you since you have an open PR that closes this issue already.

**Closed** 2017-08-24 20:38 UTC
