### ISSUE TITLE
CPU usage of idle single node

### ISSUE THREAD

**Issue by WhiteTrashLord** [cockroachdb/cockroach#24695] opened 2018-04-11 18:15 UTC
I upgraded to version 2.0. I am using Ubuntu. I noticed that my Cockroachdb single node will always use 4 - 6 % CPU usage even if there was no activity for a long time.

Maybe you have an explanation what Cockroachdb is doing. Maybe you can improve the CPU usage :)

**Comment by EdSchouten** [comment] 2018-04-21 15:26
Also noticed this. It looks like Cockroach has a hard time sitting still. It keeps on calling Linux system call `pselect6()` with a 20 microsecond timeout:

```
$ strace -fp 1809 -e pselect6
[pid  1812] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
[pid  1812] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
[pid  1812] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
[pid  1812] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
[pid  1812] pselect6(0, NULL, NULL, NULL, {tv_sec=0, tv_nsec=20000}, NULL) = 0 (Timeout)
...
```

**Comment by jordanlewis** [comment] 2018-05-02 17:30
Nevermind, I wasn't passing the `-f` flag to `strace`.

**Comment by jordanlewis** [comment] 2018-05-02 17:57
So I think that all of this is pretty much well-expected, because of the Go runtime. I believe that you can't do really do blocking reads in Go, since Go multiplexes goroutines over its available physical threads. That means that Go prefers to never block a physical thread, since that would reduce the amount of available concurrency in the system.

The `read` call returns `EAGAIN`, which means its a non-blocking read, so that's expected.

I did some investigation about `pselect6` and discovered that it's used to implement `usleep` in the Go runtime: https://groups.google.com/forum/#!topic/golang-codereviews/GmeazxlWjIw

I used `pprof` to determine that `usleep` is called by the `sysmon` and `runqgrab`, both Go runtime functions that I don't fully understand. But I think the long story short is that this is all stuff that's caused by the Go runtime and scheduler.

**Comment by jordanlewis** [comment] 2018-05-02 17:58
I also don't think that 4-6% is unexpected. Cockroach needs to do a little bit of stuff at all time, even when idle, like updating time series information, and various inter-node gossip. Thanks for the report, but I'm going to close this as not an issue.

**Closed by jordanlewis** 2018-05-02 17:58 UTC
Labels: C-investigation

**Comment by WhiteTrashLord** [comment] 2018-05-03 16:52
But I was using a single node. So there should not be any inter-node gossip. For me 4 - 6 % is much. I hope you can improve the performance in the future.

**Comment by jordanlewis** [comment] 2018-05-03 16:55
Thanks for the input! You might want to try turning off the internal time-series recording to see if that helps. https://www.cockroachlabs.com/docs/stable/operational-faqs.html#can-i-reduce-or-disable-the-storage-of-timeseries-data-new-in-v2-0

**Comment by WhiteTrashLord** [comment] 2018-07-27 23:10
I upgraded to 2.0.4 and I set timeseries.storage.enabled to false.
Now the idle CPU usage is around 1 % which is okay. It's possible that Cockroach was not really idle when I checked it before.
