### ISSUE TITLE
Test failure in CI build 8348

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2802] opened 2015-10-08 20:09 UTC
The following test appears to have failed:

[#8348](https://circleci.com/gh/cockroachdb/cockroach/8348):

```
I1008 20:09:23.681692 913 raft/raft.go:737  [group 2] 3 restored progress of 3 [next = 19, match = 18, state = ProgressStateProbe, waiting = false, pendingSnapshot = 0]
I1008 20:09:23.681760 913 raft/raft.go:702  [group 2] 3 [commit: 0] restored snapshot [index: 18, term: 6]
I1008 20:09:23.719119 913 storage/range_gc_queue.go:122  destroying local data from range 2
I1008 20:09:23.723454 913 multiraft/multiraft.go:586  node 3: got message for unknown group 2; creating it
E1008 20:09:23.725149 913 raft/log.go:195  [group 2] applied(20) is out of range [prevApplied(10), committed(10)]
panic: [group 2] applied(20) is out of range [prevApplied(10), committed(10)]

goroutine 5538 [running]:
github.com/cockroachdb/cockroach/multiraft.(*raftLogger).Panicf(0xc8200fd830, 0x16a4d20, 0x3c, 0xc82027e5a0, 0x3, 0x3)
	/go/src/github.com/cockroachdb/cockroach/multiraft/raft.go:121 +0x1ce
github.com/coreos/etcd/raft.(*raftLog).appliedTo(0xc82005c460, 0x14)
	/go/src/github.com/coreos/etcd/raft/log.go:195 +0x2c8
github.com/coreos/etcd/raft.newRaft(0xc82005c3f0, 0xc820468d20)
	/go/src/github.com/coreos/etcd/raft/raft.go:209 +0xcfb
github.com/coreos/etcd/raft.(*multiNode).run(0xc820468900)
	/go/src/github.com/coreos/etcd/raft/multinode.go:203 +0x573
--
	/go/src/github.com/cockroachdb/cockroach/rpc/codec/client.go:80 +0x59
net/rpc.(*Client).input(0xc8200168a0)
	/usr/local/go/src/net/rpc/client.go:109 +0x177
created by net/rpc.NewClientWithCodec
	/usr/local/go/src/net/rpc/client.go:201 +0x126
FAIL	github.com/cockroachdb/cockroach/storage	12.546s
=== RUN   TestBatchBasics
I1008 20:09:09.347312 907 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I1008 20:09:09.351337 907 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1008 20:09:09.357869 907 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tschottdorf** [comment] 2015-10-12 11:49
known offender, right @bdarnell?

**Comment by bdarnell** [comment] 2015-10-12 12:00
Yes, duplicate of #1878

**Closed by bdarnell** 2015-10-12 12:00 UTC
Labels: test-failure
