### ISSUE TITLE
storage: possible goroutine leak from pebble

### ISSUE THREAD

**Issue by stevendanna** [cockroachdb/cockroach#92026] opened 2022-11-17 01:03 UTC
**Describe the problem**

After a few thousand runs of various logic tests on stress:

```
=== RUN   TestCCLLogic_redact_descriptor
    test_log_scope.go:161: test logs captured to: /home/ssd/go/src/github.com/cockroachdb/cockroach/tmp/_tmp/effab48683274210e068775452544fff/logTestCCLLogic_redact_descriptor224268157
    test_log_scope.go:79: use -show-logs to present logs inline
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
*
* INFO: Running test with the default test tenant. If you are only seeing a test case failure when this message appears, there may be a problem with your test case running within tenants.
*
[00:56:18] --- done: /home/ssd/.cache/bazel/_bazel_ssd/8d7b887d1ed310166524748df3a7b647/sandbox/linux-sandbox/2172/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/ccl/logictestccl/tests/fakedist-disk/fakedist-disk_test_/fakedist-disk_test.runfiles/com_github_cockroachdb_cockroach/pkg/ccl/logictestccl/testdata/logic_test/redact_descriptor with config fakedist-disk: 6 tests, 0 failures
[00:56:19] --- total progress: 6 statements
--- total: 6 tests, 0 failures
    logic.go:3977: -- test log scope end --
    generated_test.go:95: Leaked goroutine: goroutine 11041 [select]:
        github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked.func1()
                github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:302 +0xe5
        created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFS).startTickerLocked
                github.com/cockroachdb/pebble/vfs/external/com_github_cockroachdb_pebble/vfs/disk_health.go:297 +0x7a
```

Jira issue: CRDB-21527

**Comment by jbowens** [comment] 2022-11-18 03:53
Typically this is the result of not closing the Engine (at least synchronously, with test end).

**Comment by nicktrav** [comment] 2022-12-07 17:11
Going to close this one out as as dupe of #92504 and #92903.

**Closed by nicktrav** 2022-12-07 17:11 UTC
Labels: C-bug, A-storage, T-storage
