### ISSUE TITLE
circleci: failed tests: TestReplicaRemovalCampaign

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7387] opened 2016-06-22 13:40 UTC
The following test appears to have failed:

[#19443](https://circleci.com/gh/cockroachdb/cockroach/19443):

```
I160622 13:37:41.346923 storage/replica_raftstorage.go:441  generated snapshot for range 1 at index 14 in 533.5µs. encoded size=3558, 31 KV pairs, 4 log entries
I160622 13:37:41.347483 storage/raft_transport.go:215  successfully sent MsgSnap to {2 2 2} at 127.0.0.1:59767
I160622 13:37:41.348381 storage/replica_raftstorage.go:533  replica 2 received snapshot for range 1 at index 14. encoded size=3558, 31 KV pairs, 4 log entries
I160622 13:37:41.349595 storage/replica_raftstorage.go:535  replica 2 applied snapshot for range 1 in 1.124529ms
I160622 13:37:41.385982 storage/replica_command.go:2127  initiating a split of range=1 [/Min-/Max) at key "m"
panic: requested entry at index is unavailable

goroutine 8250 [running]:
panic(0x1cddb40, 0xc820190d70)
	/usr/local/go/src/runtime/panic.go:481 +0x3ff
github.com/coreos/etcd/raft.(*raftLog).term(0xc82054dab0, 0xa, 0x6181f4, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/log.go:238 +0x1fe
github.com/coreos/etcd/raft.(*raftLog).lastTerm(0xc82054dab0, 0xa)
	/go/src/github.com/coreos/etcd/raft/log.go:212 +0x57
github.com/coreos/etcd/raft.newRaft(0xc820eab7f0, 0x0)
	/go/src/github.com/coreos/etcd/raft/raft.go:238 +0x114b
github.com/coreos/etcd/raft.NewRawNode(0xc820eab7f0, 0x0, 0x0, 0x0, 0x7f2d8dd430a8, 0x0, 0x0)
	/go/src/github.com/coreos/etcd/raft/rawnode.go:76 +0xe1
github.com/cockroachdb/cockroach/storage.(*Replica).withRaftGroupLocked(0xc820f10380, 0xc820eab998, 0x0, 0x0)
--
	/go/src/github.com/cockroachdb/cockroach/storage/replica_range_lease.go:118 +0x2c4
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1(0xc820052f50, 0x29ec81e, 0x1e, 0x99, 0xc82079f7c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:181 +0x74
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:182 +0xdc
FAIL	github.com/cockroachdb/cockroach/storage	19.950s
=== RUN   TestBatchBasics
I160622 13:37:56.552170 storage/engine/rocksdb.go:143  opening in memory rocksdb instance
I160622 13:37:56.554345 storage/engine/rocksdb.go:186  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchRepr
I160622 13:37:56.571339 storage/engine/rocksdb.go:143  opening in memory rocksdb instance
I160622 13:37:56.573268 storage/engine/rocksdb.go:186  closing in-memory rocksdb instance
--- PASS: TestBatchRepr (0.02s)
=== RUN   TestBatchGet
I160622 13:37:56.586487 storage/engine/rocksdb.go:143  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-06-22 13:44
Duplicate of #7386.

**Closed by petermattis** 2016-06-22 13:44 UTC
Labels: Robot, test-failure
