### ISSUE TITLE
sql: report anonymized descriptor set to Sentry when encountering descriptor corruption

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#51255] opened 2020-07-09 23:19 UTC
Several issues around schema descriptor corruption could have been made easier to debug if the Sentry reports for them contained the anonymized descriptor set. Specifically, having the ids of various descriptor objects and links between them would help enormously in debugging.

The first step here is to add the descriptors to the set of reportable objects via @knz's [redactable logs proposal](https://docs.google.com/presentation/d/1PZnOcuEbPrkkN4KvUV_kmYdtZ71J3SDMK9UxvdyUsSQ/edit#slide=id.p). Then, I suppose we need to either sprinkle outputs of descriptors when necessary, or introduce something that attempts to record descriptors when sending info to Sentry.

One thing I'm concerned about - isn't there a limit on the number of bytes we can send in a Sentry report?

Jira issue: CRDB-4065

**Comment by dt** [comment] 2020-07-09 23:41
We already report The anonymizes set of all descriptors in telemetry with a reflection-based string scrubber that might be able to be repurposed here

**Comment by jordanlewis** [comment] 2020-07-09 23:44
Awesome, can you provide a link? I'm not familiar with this code.

**Comment by dt** [comment] 2020-07-10 00:02
https://github.com/cockroachdb/cockroach/blob/master/pkg/server/updates.go#L464

**Comment by knz** [comment] 2020-07-14 09:14
> One thing I'm concerned about - isn't there a limit on the number of bytes we can send in a Sentry report?

Yes there is: it's currently 200KB, and a lot of that is consumed by the various stack traces included in the report.

Is there a way to scope down this proposal to include only those descriptors (And their dependencies) used by the current transaction? Using the table cache?

> The first step here is to add the descriptors to the set of reportable objects

Why not reuse the mechanism that was used for the statement - having a `tagFn` that the logging package picks up whenever reporting. See the `log.RegisterTagFn` at the end of `conn_executor.go` for an example.

**Comment by ajwerner** [comment] 2020-10-05 21:03
More context here: we include statements in sentry reports but we anonymize aggressively to the point where we cannot determine which columns are in use. It'd be great to use the numeric column IDs etc in the scrubbed statement rather than just underscores.

**Comment by knz** [comment] 2020-10-06 12:16
The numeric column and table IDs are not in the AST - and the formatting logic doesn't have a context to look them up. Lifting the AST formatting code in this way would be quite the undertaking.

Maybe an alternative could be to include a (compact) representation of the logical plan? with IDs?

**Comment by postamar** [comment] 2022-03-11 15:34
Closing as duplicate of https://github.com/cockroachdb/cockroach/issues/57436

**Closed by postamar** 2022-03-11 15:34 UTC
Labels: C-cleanup, T-sql-schema
