### ISSUE TITLE
Support for table change notifications

### ISSUE THREAD

**Issue by boyvinall** [cockroachdb/cockroach#9712] opened 2016-10-04 14:33 UTC
**Feature request**

Essentially, I'm just looking for something like https://godoc.org/github.com/cockroachdb/pq#hdr-Notifications - I guess that would come under the "change feeds" 2017 item on https://github.com/cockroachdb/cockroach/wiki? But thought I'd see if you're open to bringing that in a little? 😄 

Thanks!

**Comment by dt** [comment] 2016-10-04 17:36
#6130 covers some similar functionality

**Comment by boyvinall** [comment] 2016-10-04 19:08
Hi @dt, yep similar, although that's explicitly looking for row- or column- watches.  I'm just looking for table-level changes, which brings parity with some other systems.

**Comment by knz** [comment] 2018-04-28 14:32
I think this is a dup of #2656?

**Comment by dianasaur323** [comment] 2018-04-30 14:29
yeah, I think it is a dup. @danhhz perhaps make a final call on whether or not to close this out in favor of #2656?

**Comment by danhhz** [comment] 2018-04-30 14:56
I'm comfortable calling this a duplicate of #2656

**Closed** 2018-04-30 14:56 UTC
Labels: C-enhancement, O-community
