### ISSUE TITLE
sql: memory accounting leak (strongly suspected)

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#25607] opened 2018-05-17 13:09 UTC
Running v2.0.1.

The symptoms: 

- a given query running multiple times over constant data starts running into "memory budget exceeded" although it succeeded before. 
- Restarting the cluster alleviates the problem temporarily.

Working hypothesis, a bug: some memory gets billed against the root SQL monitor and not properly released (by closing accounts). 

Two places where this can happen: 

- at the SQL gateway, with session monitors, since we have recently demoted accounting errors from fatal errors to mere warnings.
- in distsql processors, where some memory account does not get closed properly.

User @rjinski on Gitter was helpful to present exactly the symptoms described above:

- SQL max mem configured to 2GB
- a single query issued performing a clean inner join over 2 tables with 31K rows each (clean = good match between keys, so no cross product amplification)
- query runs into aforementioned error after succeeding for a while, note the values: `memory budget exceeded: 327680 bytes requested, 2016333949 currently allocated, 2016399360 bytes in budget` (2GB in budget!)
- **at the time the error occurs, less than 1GB is allocated by Go as per the web UI graph.** ![https://files.gitter.im/cockroachdb/cockroach/4Xma/image.png](https://files.gitter.im/cockroachdb/cockroach/4Xma/image.png)
- cluster restart alleviates.

The fact that the SQL memory error is encountered for an account of 2GB while the overall Go memory is less than 1GB alone is for me strong indication of a memory accounting error.

**However** at the same time the `sql_mem` metrics in the `/_status/vars` endpoint remain at zero, which in turn is a counter-signal against a memory accounting problem. This counter-signal would disappear if we found out somehow that the metrics are not collected properly.

The user reports that **the problem tends to disappear if recreating the cluster from scratch** which in turn suggests the error is dependent on data layout, which in turn somewhat orients the investigation towards a failure in distsql memory accounting.

The schema of that use case:

```sql
CREATE TABLE quotes (
    id UUID NOT NULL,
    revision_id UUID NOT NULL,
    rfq_id UUID NOT NULL,
    market_id UUID NOT NULL,
    client_id UUID NOT NULL,
    provider_id UUID NOT NULL,
    payload STRING NOT NULL,
    lifespan INT NOT NULL,
    created_on TIMESTAMP WITH TIME ZONE NULL DEFAULT current_timestamp(),
    on_behalf_of STRING NULL,
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    UNIQUE INDEX quotes_revision_id_key (revision_id ASC),
    FAMILY "primary" (id, revision_id, rfq_id, market_id, client_id, provider_id, payload, lifespan, created_on, on_behalf_of)
);
CREATE TABLE quote_revisions (
    id UUID NOT NULL,
    quote_id UUID NOT NULL,
    status STRING NOT NULL,
    acceptance STRING NOT NULL,
    completion STRING NOT NULL,
    updated_on TIMESTAMP WITH TIME ZONE NULL DEFAULT current_timestamp(),
    CONSTRAINT "primary" PRIMARY KEY (id ASC),
    FAMILY "primary" (id, quote_id, status, acceptance, completion, updated_on)
);
```

The query that encounters the error:

```sql
select * from quotes 
inner join quote_revisions ON quotes.revision_id = quote_revisions.id;
```

The specific distsql physical plan in the user environment: [See here](https://cockroachdb.github.io/distsqlplan/decode.html?eJzkk0-LnEAQxe_5FEuddqECljr5IwTqmM1hNyy5BQm9dmVscG3T3YYMg989qIGJRs0MyW2PdvevXr3H8wi11XKnnsRD9hkIEBLIERpnC_Heuv54fHSrf0AWIZi6aUN_nCMU1glkRwgmVAIZfFKPlTyI0uIAQUtQphoGN848KXfgb60N8sXJd-ONrT0g3Lchu2JCjpET5BR5h_wK8g7BtuGX1Enh8XBVKl9OpzNB3uUIPqi9QBZ3uLLyaU5bW6fFiZ5Mynvyb08WfL9XvvxgTT23XcnXcM3xzTtn9mW4ZrpZdYz8GvkN8ltkipCJkClGpgSZUmTaIdM8lpPl5B8sL_i5sy9tM09mUTidCNP_qMd6KyYZXViReFIRWl37GVZkYdsH8Y2tvZzVgaj3K3ovY37etq6Qj84Wg8z4eT9wQ9RafBhv0_Hjth6uht_2fJi2YZrD0e9wPIFpDseb8G4CR3M4ucDzH8rbMG3D6UWe8-7FzwAAAP__OSnsOw==)

**Comment by knz** [comment] 2018-05-17 13:26
Planning to ask the user for a full allocation trace.

**Comment by knz** [comment] 2018-05-17 14:13
User reports:

on one node:

```
I180517 14:03:17.996470 97796 util/mon/bytes_usage.go:576 distsql: bytes usage increases to 33 MiB (+17175802)
I180517 14:03:17.996477 97796 util/mon/bytes_usage.go:576 flow: bytes usage increases to 33 MiB (+17175802) 
I180517 14:03:17.996500 97796 util/mon/bytes_usage.go:576 distsql: bytes usage increases to 66 MiB (+17172366)
```

on another node:

```
I180517 14:03:17.999899 117772 sql/distsqlrun/hashjoiner.go:234  [client=127.0.0.1:49390,user=root,n1,HashJoiner] build phase error root: memory budget exceeded: 1710080 bytes requested, 2016051200 currently allocated, 2016397312 bytes in budget
```

**Comment by knz** [comment] 2018-05-17 14:13
the error with HashJoiner is interesting

**Comment by knz** [comment] 2018-05-17 14:34
@asubiotto somehow in this specific case I'm not yet confident we're running into #25590 because the amount of data is very small.

**Comment by rjinski** [comment] 2018-05-17 16:11
[cockroach.cockroachdb-0.root.2018-05-17T16_03_55Z.000001.log](https://github.com/cockroachdb/cockroach/files/2013951/cockroach.cockroachdb-0.root.2018-05-17T16_03_55Z.000001.log)

Logs with `--vmodule=bytes_usage=2` from one node of the cluster

**Comment by knz** [comment] 2018-05-17 16:14
@asubiotto can you have a look at this log? I'd like to understand the following:

- why is the hashjoiner requesting memory in chunks of 17 **megabytes** at a time? What's the size computation that produces this size?

- why are there multiple chunks allocated over time?

**Comment by knz** [comment] 2018-05-17 16:17
Oh interesting the allocations come from the flow of the hash router not the joiner.

**Comment by asubiotto** [comment] 2018-05-17 18:40
I have no idea, looking into it.

**Comment by asubiotto** [comment] 2018-05-19 15:48
@knz, related to the `sql_mem` metrics I think the reason that it stays at 0 is because the `distsql` monitor is hooked up directly to the `root` monitor. @rjinski a better metric to look at might be `sql.mem.distsql.current` by going to:
```
<your_admin_ui>/#/debug/chart?metrics=%5B%7B%22downsampler%22%3A1%2C%22aggregator%22%3A2%2C%22derivative%22%3A0%2C%22perNode%22%3Afalse%2C%22source%22%3A%22%22%2C%22metric%22%3A%22cr.node.sql.mem.distsql.current%22%7D%5D
```

There are two issues here:
1) The huge memory allocations at a time
2) The suspected "leak" (i.e. why does this query run fine and then at some point start producing memory errors)

I have unfortunately been unable to reproduce either issue with the version, specific distsql execution plan, and an artificial dataset (same schema, size, and relationship between tables).

@rjinski do you mind giving me more information:
- How long would you say it took to hit the memory error?
- Is there a possibility that any queries apart from the given one were running on the cluster at the same time?

Current status:
1) Huge memory allocations:
Looking into another memory accounting issue, I came across the fact that JSON objects reported incorrectly huge sizes (on the order of MB). However, all the types in the given schema seem to have correct `Size` calculations. Since the log shows that the correct default allocation size of `10240` is used in a lot of cases, this means that somebody explicitly requested 17MB. The trace in these allocations also seem to point the finger at the `rowSize` calculation in `AddRow` in both the `hashRouter` AND the `hashJoiner`. Kind of stumped on this one since I verified the `rowSize` calculations but I might have missed something. I'm seeing some higher than usual but not extravagantly big allocation requests in my reproduction attempts, will dig deeper.
2) Leak:
Not a lot of digging has gone into this one but I'm unsure there is a leak. The logs show on a memory error that:
```
I180517 16:04:26.162239 33031 util/mon/bytes_usage.go:384  [client=127.0.0.1:47560,user=root,n1] flow, bytes usage max 1.9 GiB
```
Which implies that the root monitor was saturated with memory allocations from one particular flow and seems to disprove that a leak caused the memory error because a new `flow` monitor is created in `setupFlow` each time we set up a flow (i.e. on every query) which points the finger at 1. The fact that `set distsql=off` resolves this problem has me stumped because I think we would be using the same row size calculation functions.

**Comment by rjinski** [comment] 2018-05-21 10:40
@asubiotto 

**How long would you say it took to hit the memory error?**
Unfortunatly this has been a little bit variable. Originally, it was several hours under load, but, now its generally <5 runs of the query before failure

**Is there a possibility that any queries apart from the given one were running on the cluster at the same time?**
Yes, there is possibility, but very unlikely. This query is orders of magnitude bigger than any other table/query in our environment too so nothing else _should_ be suspect.

Potientally worth noting, I deleted the cluster last week, rebuilt and restored the data and the problem persisted. What I would still like to do is restore the data to an identical k8s cluster to see if I can reproduce it and also restore to a _bare metal_ db cluster to see if is reproducable. I'm happy to share the SQL dump (it is generally test data) if it is useful?

**Comment by asubiotto** [comment] 2018-05-21 14:58
> Yes, there is possibility, but very unlikely. This query is orders of magnitude bigger than any other table/query in our environment too so nothing else should be suspect.

The incorrect JSON `Size` reporting I mentioned could be an issue even if you have relatively infrequent queries or expect it to not be huge (PR for reference: https://github.com/cockroachdb/cockroach/pull/25719). If you have any other tables apart from the ones that you shared that have JSON in their schema that are queried every so often this might be an issue. If not, we can disregard this.

> I'm happy to share the SQL dump (it is generally test data) if it is useful?

That would be great, it might help with the reproduction on my side.

I appreciate you taking the time to help us find the issue!

**Comment by rjinski** [comment] 2018-05-22 07:47
There is definitely other tables that contain JSON. On review, there has been _unshareable_ data put in our database so I'm not able to share the SQL dump so I'm going to try and focus on generating some truely random dataset to A. test if it is reproducable with new data and B. then be able to share it with you

**Comment by rjinski** [comment] 2018-05-22 10:01
![image](https://user-images.githubusercontent.com/2047299/40355694-07774f40-5daf-11e8-9f38-eef02885f4e3.png)

I'm not sure if this is related but doing a READ, INSERT load we get some pretty significant latency increase - going to continue digging deeper

**Comment by asubiotto** [comment] 2018-05-23 14:38
@rjinski, if there are tables that contain JSON it might be less work for you to attempt to reproduce the issue with the binary linked above instead of generating a dataset. The latency increases should not be related.

**Comment by rjinski** [comment] 2018-05-31 13:07
@asubiotto Sorry for the delay. The link is 404 but I've updated to 2.0.2 and the problem continues

**Comment by asubiotto** [comment] 2018-05-31 14:21
@rjinski, 2.0.2 doesn't include the JSON fix. 2.0.3 will and will come out mid-june, in the meantime you can try use an alpha. Here's an updated link: http://edge-binaries.cockroachdb.com/cockroach/cockroach.linux-gnu-amd64.29c01356fbe35810ab9ab54e566f9a4192505e5e

**Comment by asubiotto** [comment] 2018-06-18 13:53
I'm going to go ahead and close this issue since I think we understand the cause. 2.0.3 should be coming out today. If you can reproduce the issue with that release please re-open this issue.

**Closed by asubiotto** 2018-06-18 13:53 UTC
Labels: A-sql-execution, A-sql-memmon, C-bug, C-investigation, O-community, S-2-temp-unavailability
