### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestPurgeOldLeases

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6792] opened 2016-05-19 12:16 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/bfb28e1ab481c9cf2c475b85f55081e42ba851f5

Stress build found a failed test:

```
=== RUN   TestPurgeOldLeases
W160519 07:05:25.477537 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 07:05:25.480986 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160519 07:05:25.482770 server/node.go:401  store store=0:0 ([]=) not bootstrapped
W160519 07:05:25.484331 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 07:05:25.484669 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406567h5m26.484106585s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 07:05:25.484560143 +0000 UTC]
I160519 07:05:25.485144 server/node.go:327  **** cluster {2b10fe5b-3b51-4979-8527-e0894ab12a49} has been created
I160519 07:05:25.485164 server/node.go:328  **** add additional nodes by specifying --join=127.0.0.1:39797
W160519 07:05:25.485173 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160519 07:05:25.485819 server/node.go:414  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:7973199872 RangeCount:0}
I160519 07:05:25.485858 server/node.go:302  node ID 1 initialized
I160519 07:05:25.485914 storage/stores.go:287  read 0 node addresses from persistent storage
I160519 07:05:25.486017 server/node.go:535  connecting to gossip network to verify cluster ID...
I160519 07:05:25.486507 server/node.go:556  node connected via gossip and verified as part of cluster {"2b10fe5b-3b51-4979-8527-e0894ab12a49"}
I160519 07:05:25.486551 server/node.go:355  [node=1] Started node with [[]=] engine(s) and attributes []
I160519 07:05:25.486587 server/server.go:417  starting https server at 127.0.0.1:39864
I160519 07:05:25.486603 server/server.go:418  starting grpc/postgres server at 127.0.0.1:39797
I160519 07:05:25.501602 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160519 07:05:25.514949 server/updates.go:155  No previous updates check time.
I160519 07:05:25.520126 storage/replica_command.go:2011  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160519 07:05:25.526086 storage/replica_command.go:1470  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406567h5m26.585441987s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 07:05:25.526046435 +0000 UTC]
I160519 07:05:25.526335 storage/replica_command.go:2011  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160519 07:05:25.532881 storage/replica_command.go:1470  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406567h5m26.585441987s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 07:05:25.532841743 +0000 UTC]
I160519 07:05:25.533012 storage/replica_command.go:2011  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160519 07:05:25.538891 storage/replica_command.go:1470  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406567h5m26.588647842s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 07:05:25.538850379 +0000 UTC]
I160519 07:05:25.539054 storage/replica_command.go:2011  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160519 07:05:25.688491 storage/replica_command.go:1470  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406567h5m26.738152375s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-19 07:05:25.68844231 +0000 UTC]
I160519 07:05:25.689335 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0 /Table/51/0]
E160519 07:05:25.690102 storage/queue.go:446  [split] range=5 [/Table/14-/Max): error: storage/split_queue.go:103: unable to split range=5 [/Table/14-/Max) at key "/Table/50/0": node unavailable; try another peer
I160519 07:05:25.690138 stopper.go:352  draining; tasks left:
1      storage/queue.go:383
1      kv/txn_coord_sender.go:863
W160519 07:05:25.690575 sql/lease.go:1100  error purging leases for table 51(test): node unavailable; try another peer
--- FAIL: TestPurgeOldLeases (0.22s)
	lease_internal_test.go:148: found 2 leases instead of 3
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
0 runs so far, 0 failures, over 40s
0 runs so far, 0 failures, over 45s
14 runs so far, 0 failures, over 50s
15 runs so far, 0 failures, over 55s
15 runs so far, 0 failures, over 1m0s
15 runs so far, 0 failures, over 1m5s
15 runs so far, 0 failures, over 1m10s
15 runs so far, 0 failures, over 1m15s
15 runs so far, 0 failures, over 1m20s
15 runs so far, 0 failures, over 1m25s
15 runs so far, 0 failures, over 1m30s
22 runs so far, 0 failures, over 1m35s
30 runs so far, 0 failures, over 1m40s
30 runs so far, 0 failures, over 1m45s
30 runs so far, 0 failures, over 1m50s
30 runs so far, 0 failures, over 1m55s
30 runs so far, 0 failures, over 2m0s
30 runs so far, 0 failures, over 2m5s
30 runs so far, 0 failures, over 2m10s
30 runs so far, 0 failures, over 2m15s
33 runs so far, 0 failures, over 2m20s
40 runs so far, 0 failures, over 2m25s
45 runs so far, 0 failures, over 2m30s
45 runs so far, 0 failures, over 2m35s
45 runs so far, 0 failures, over 2m40s
45 runs so far, 0 failures, over 2m45s
45 runs so far, 0 failures, over 2m50s
45 runs so far, 0 failures, over 2m55s
45 runs so far, 0 failures, over 3m0s
45 runs so far, 0 failures, over 3m5s
52 runs so far, 0 failures, over 3m10s
58 runs completed, 1 failures, over 3m13s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:55
Duplicate of #6810

**Closed by bdarnell** 2016-05-21 15:55 UTC
Labels: Robot, test-failure
