### ISSUE TITLE
stress: failed test in cockroach/rpc/rpc.test: TestOffsetMeasurement

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6062] opened 2016-04-14 10:40 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/371017263b122dbd2423dc1c2c6b8e98b1ff19f0

Stress build found a failed test:

```
=== RUN   TestOffsetMeasurement
SIGABRT: abort
PC=0x461143 m=0

goroutine 6 [syscall]:
runtime.notetsleepg(0x115f578, 0x129f8bf95, 0x0)
	/usr/local/go/src/runtime/lock_futex.go:205 +0x4e fp=0xc820028738 sp=0xc820028710
runtime.timerproc()
	/usr/local/go/src/runtime/time.go:209 +0xde fp=0xc8200287c0 sp=0xc820028738
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200287c8 sp=0xc8200287c0
created by runtime.addtimerLocked
	/usr/local/go/src/runtime/time.go:116 +0x11f

goroutine 1 [chan receive, 9 minutes]:
testing.RunTests(0xcf69a0, 0x113ffa0, 0xb, 0xb, 0xb56901)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc82003df08, 0xb56960)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/rpc/_test/_testmain.go:74 +0x117

goroutine 17 [syscall, 9 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 82 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc82064258c)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc820642588)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/util/hlc.(*Clock).MaxOffset(0xc820642580, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:135 +0x3a
github.com/cockroachdb/cockroach/rpc.TestOffsetMeasurement(0xc8203fa000)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:129 +0x719
testing.tRunner(0xc8203fa000, 0x1140018)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 34 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x115f940)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:993 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:594 +0x8a

goroutine 9 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b6000, 0xc8203ca1a0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 10 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b6000, 0xc8201c8e20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 11 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f39586fc520, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200573a0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200573a0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820057340, 0x0, 0x7f39586fc608, 0xc8200fc0c0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc82013c0a8, 0xc820036ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc82013c0a8, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82009ba00, 0x7f39586fb578, 0xc82013c0a8, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b6000, 0xc8201c8e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 12 [chan receive, 9 minutes]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:89 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b6000, 0xc8201c8f40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 13 [select, 9 minutes]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc820158380)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc820158380)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 14 [semacquire, 9 minutes]:
sync.runtime_Semacquire(0xc8201cb594)
	/usr/local/go/src/runtime/sema.go:47 +0x26
sync.(*Mutex).Lock(0xc8201cb590)
	/usr/local/go/src/sync/mutex.go:83 +0x1c4
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano(0xc8201cb590, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:202 +0x30
github.com/cockroachdb/cockroach/rpc.(*AdvancingClock).UnixNano-fm(0x2)
	/go/src/github.com/cockroachdb/cockroach/rpc/context_test.go:105 +0x20
github.com/cockroachdb/cockroach/util/hlc.(*Clock).getPhysicalClock(0xc820642580, 0xcf7220)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:160 +0x25
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalNow(0xc820642580, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:200 +0x7d
github.com/cockroachdb/cockroach/util/hlc.(*Clock).PhysicalTime(0xc820642580, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/hlc/hlc.go:206 +0x35
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc8200573b0, 0xc8200f41e0, 0xc82000e950, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:175 +0x19c
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:157 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc8201b6000, 0xc820168e40)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 70 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f39586fc3a0, 0x72, 0xc820060c00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203ac060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203ac060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203ac000, 0xc820060c00, 0x400, 0x400, 0x0, 0x7f395876e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82012e150, 0xc820060c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820126900, 0x7f395872f240, 0xc82012e150, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820644000, 0xcf7217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820644000, 0xc820680000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc82068a720)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc82068a720, 0xc8201b00f8, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f39587337b0, 0xc82068a720, 0xc8201b00f8, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f39587337b0, 0xc82068a720, 0xc8201b00f8, 0x9, 0x9, 0x5e633fb9ebf7cc01, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc8201b00f8, 0x9, 0x9, 0x7f39587337b0, 0xc82068a720, 0x58000000, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8201b00c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201ca930, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc8203fa1b0, 0xc8201ca9f0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82009ba00, 0x7f3958733800, 0xc8203fa1b0)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82009ba00, 0x7f39587336d8, 0xc820644000, 0x7f3958733738, 0xc820197290)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82009ba00, 0x7f39586fc860, 0xc82012e150)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 83 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc82030cc30)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 71 [select, 9 minutes]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc8203fa1b0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:620 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853

goroutine 84 [IO wait, 9 minutes]:
net.runtime_pollWait(0x7f39586fc460, 0x72, 0xc82060ec00)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8200fa060, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200fa060, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200fa000, 0xc82060ec00, 0x400, 0x400, 0x0, 0x7f395876e050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a000, 0xc82060ec00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820014450, 0x7f395872f240, 0xc82002a000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8203b2000, 0xcf7217, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8203b2000, 0xc8200de000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
bufio.(*Reader).fill(0xc8203ae5a0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc8203ae5a0, 0xc82063fe38, 0x9, 0x9, 0xc81fff6918, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f39587337b0, 0xc8203ae5a0, 0xc82063fe38, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7f39587337b0, 0xc8203ae5a0, 0xc82063fe38, 0x9, 0x9, 0xc8201c7d48, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82063fe38, 0x9, 0x9, 0x7f39587337b0, 0xc8203ae5a0, 0x0, 0xc800000000, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82063fe00, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201c7bf0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc82030cc30)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

rax    0xfffffffffffffffc
rbx    0xc8200286c8
rcx    0x461143
rdx    0x0
rdi    0x115f578
rsi    0x0
rbp    0x3b8d9795
rsp    0xc820028690
r8     0x0
r9     0x0
r10    0xc8200286c8
r11    0x206
r12    0x2
r13    0xcf3c3c
r14    0x0
r15    0x8
rip    0x461143
rflags 0x206
cs     0x33
fs     0x0
gs     0x0


ERROR: exit status 2
```

Run Details:

```
65 runs so far, 0 failures, over 5s
140 runs so far, 0 failures, over 10s
211 runs so far, 0 failures, over 15s
282 runs so far, 0 failures, over 20s
352 runs so far, 0 failures, over 25s
429 runs so far, 0 failures, over 30s
504 runs so far, 0 failures, over 35s
576 runs so far, 0 failures, over 40s
650 runs so far, 0 failures, over 45s
719 runs so far, 0 failures, over 50s
793 runs so far, 0 failures, over 55s
864 runs so far, 0 failures, over 1m0s
933 runs so far, 0 failures, over 1m5s
1009 runs so far, 0 failures, over 1m10s
1073 runs so far, 0 failures, over 1m15s
1145 runs so far, 0 failures, over 1m20s
1219 runs so far, 0 failures, over 1m25s
1293 runs so far, 0 failures, over 1m30s
1365 runs so far, 0 failures, over 1m35s
1437 runs so far, 0 failures, over 1m40s
1509 runs so far, 0 failures, over 1m45s
1579 runs so far, 0 failures, over 1m50s
1647 runs so far, 0 failures, over 1m55s
1716 runs so far, 0 failures, over 2m0s
1786 runs so far, 0 failures, over 2m5s
1852 runs so far, 0 failures, over 2m10s
1922 runs so far, 0 failures, over 2m15s
1993 runs so far, 0 failures, over 2m20s
2064 runs so far, 0 failures, over 2m25s
2134 runs so far, 0 failures, over 2m30s
2206 runs so far, 0 failures, over 2m35s
2274 runs so far, 0 failures, over 2m40s
2347 runs so far, 0 failures, over 2m45s
2411 runs so far, 0 failures, over 2m50s
2481 runs so far, 0 failures, over 2m55s
2554 runs so far, 0 failures, over 3m0s
2621 runs so far, 0 failures, over 3m5s
2691 runs so far, 0 failures, over 3m10s
2761 runs so far, 0 failures, over 3m15s
2827 runs so far, 0 failures, over 3m20s
2895 runs so far, 0 failures, over 3m25s
2966 runs so far, 0 failures, over 3m30s
3038 runs so far, 0 failures, over 3m35s
3108 runs so far, 0 failures, over 3m40s
3180 runs so far, 0 failures, over 3m45s
3249 runs so far, 0 failures, over 3m50s
3322 runs so far, 0 failures, over 3m55s
3395 runs so far, 0 failures, over 4m0s
3468 runs so far, 0 failures, over 4m5s
3538 runs so far, 0 failures, over 4m10s
3610 runs so far, 0 failures, over 4m15s
3678 runs so far, 0 failures, over 4m20s
3741 runs so far, 0 failures, over 4m25s
3801 runs so far, 0 failures, over 4m30s
3868 runs so far, 0 failures, over 4m35s
3933 runs so far, 0 failures, over 4m40s
3999 runs so far, 0 failures, over 4m45s
4064 runs so far, 0 failures, over 4m50s
4131 runs so far, 0 failures, over 4m55s
4192 runs so far, 0 failures, over 5m0s
4262 runs so far, 0 failures, over 5m5s
4321 runs so far, 0 failures, over 5m10s
4386 runs so far, 0 failures, over 5m15s
4451 runs so far, 0 failures, over 5m20s
4513 runs so far, 0 failures, over 5m25s
4577 runs so far, 0 failures, over 5m30s
4636 runs so far, 0 failures, over 5m35s
4696 runs so far, 0 failures, over 5m40s
4759 runs so far, 0 failures, over 5m45s
4819 runs so far, 0 failures, over 5m50s
4885 runs so far, 0 failures, over 5m55s
4947 runs so far, 0 failures, over 6m0s
5008 runs so far, 0 failures, over 6m5s
5065 runs so far, 0 failures, over 6m10s
5124 runs so far, 0 failures, over 6m15s
5183 runs so far, 0 failures, over 6m20s
5252 runs so far, 0 failures, over 6m25s
5307 runs so far, 0 failures, over 6m30s
5372 runs so far, 0 failures, over 6m35s
5438 runs so far, 0 failures, over 6m40s
5495 runs so far, 0 failures, over 6m45s
5555 runs so far, 0 failures, over 6m50s
5622 runs so far, 0 failures, over 6m55s
5686 runs so far, 0 failures, over 7m0s
5748 runs so far, 0 failures, over 7m5s
5811 runs so far, 0 failures, over 7m10s
5867 runs so far, 0 failures, over 7m15s
5927 runs so far, 0 failures, over 7m20s
5991 runs so far, 0 failures, over 7m25s
6044 runs so far, 0 failures, over 7m30s
6105 runs so far, 0 failures, over 7m35s
6165 runs so far, 0 failures, over 7m40s
6229 runs so far, 0 failures, over 7m45s
6294 runs so far, 0 failures, over 7m50s
6354 runs so far, 0 failures, over 7m55s
6415 runs so far, 0 failures, over 8m0s
6478 runs so far, 0 failures, over 8m5s
6539 runs so far, 0 failures, over 8m10s
6609 runs so far, 0 failures, over 8m15s
6671 runs so far, 0 failures, over 8m20s
6735 runs so far, 0 failures, over 8m25s
6800 runs so far, 0 failures, over 8m30s
6859 runs so far, 0 failures, over 8m35s
6916 runs so far, 0 failures, over 8m40s
6985 runs so far, 0 failures, over 8m45s
7052 runs so far, 0 failures, over 8m50s
7114 runs so far, 0 failures, over 8m55s
7179 runs so far, 0 failures, over 9m0s
7244 runs so far, 0 failures, over 9m5s
7306 runs so far, 0 failures, over 9m10s
7363 runs so far, 0 failures, over 9m15s
7415 runs so far, 0 failures, over 9m20s
7482 runs so far, 0 failures, over 9m25s
7539 runs so far, 0 failures, over 9m30s
7596 runs so far, 0 failures, over 9m35s
7660 runs so far, 0 failures, over 9m40s
7714 runs so far, 0 failures, over 9m45s
7775 runs so far, 0 failures, over 9m50s
7839 runs so far, 0 failures, over 9m55s
7904 runs so far, 0 failures, over 10m0s
7969 runs so far, 0 failures, over 10m5s
8034 runs so far, 0 failures, over 10m10s
8102 runs so far, 0 failures, over 10m15s
8163 runs so far, 0 failures, over 10m20s
8226 runs so far, 0 failures, over 10m25s
8289 runs so far, 0 failures, over 10m30s
8349 runs so far, 0 failures, over 10m35s
8417 runs so far, 0 failures, over 10m40s
8478 runs so far, 0 failures, over 10m45s
8544 runs so far, 0 failures, over 10m50s
8602 runs so far, 0 failures, over 10m55s
8659 runs so far, 0 failures, over 11m0s
8723 runs so far, 0 failures, over 11m5s
8788 runs so far, 0 failures, over 11m10s
8850 runs so far, 0 failures, over 11m15s
8913 runs so far, 0 failures, over 11m20s
8976 runs so far, 0 failures, over 11m25s
8989 runs completed, 1 failures, over 11m26s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:11
Duplicate of #6024

**Closed by bdarnell** 2016-04-23 14:11 UTC
Labels: Robot, test-failure
