### ISSUE TITLE
Roachperf shows poor performance on some days for YCSB

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#34458] opened 2019-01-31 18:50 UTC
[Roachperf](https://crdb.io/perf/?filter=&view=ycsb%2FC%2Fnodes%3D3
) displays large dips in performance on YCSB in January.

![image](https://user-images.githubusercontent.com/22278911/52077517-2f779e00-255f-11e9-89f0-5a3107eedeb1.png)

**Comment by ajwerner** [comment] 2019-02-05 17:54
With AWS data added we see the same sort of pattern on one day. This is definitely something to dig in to.

**Comment by ajwerner** [comment] 2019-02-13 16:31
The good news is that there seems to be a very reasonable explanation for all of this. The bad news is that it's going to be somewhat difficult to rectify. 

These performance drops seem to be due to the fact that we run the same nightly tests off of different branches and releases yet the test script is completely unaware of this. The reason we find these dips to be highly correlated across cloud providers is that the roachperf code processes the first completed result on a given day based on lexicographical order which will end up being based on build ID and then will  skip other builds. This means that these dips generally correspond to previous releases. 


There are a couple of mitigations and forward looking changes I have in mind.

1) We should capture the build hash for each test run somewhere
2) We should probably only store data for master runs, or at least store runs from different branches elsewhere
3) We need a way to go back and pick the right data for a given day, my first approach is likely going to be to change roachperf to process all of the data for a given day and keep the best one which I'll take as a proxy for the newest one. It's not perfect and it's totally possible that some prior release performed better for some metric but it's going to give us a better signal than what we've got today.

**Comment by petermattis** [comment] 2019-02-13 16:35
Heh, this is somewhat amusing. I think it is worth writing up a short note to eng@ about the dips and how they were correlated across cloud providers, and then providing a reveal as to the cause.

Storing only master runs makes sense to me. At the very least, we should include the build branch in the storage directory.

**Comment by ajwerner** [comment] 2019-02-15 16:28
Closing with the tweak to the teamcity scripts and some cleanup. There's still more to be done to increase the robustness of the roachperf information collection and management but that's for a different issue.

**Closed by ajwerner** 2019-02-15 16:28 UTC
