### ISSUE TITLE
storage: allocator 3 to 5 small test failing

### ISSUE THREAD

**Issue by cuongdo** [cockroachdb/cockroach#17989] opened 2017-08-29 14:12 UTC
https://teamcity.cockroachdb.com/viewLog.html?buildId=336851&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest3to510g

This build included the change to disable stats-based rebalancing. I've run the test locally, since the logs weren't collected for the TeamCity run (known issue with test timeout). Here the logs from my local run:

[3to5small.zip](https://github.com/cockroachdb/cockroach/files/1260546/3to5small.zip)

The logs start off with:

```
I170829 14:01:27.717500 19 server/node.go:461  [n1] initialized store [n1,s1]: disk (capacity=197 GiB, available=176 GiB, used=10 GiB, logicalBytes=10 GiB), ranges=263, leases=0, writes=0.00, bytesPerReplica={p10=40172095.00 p25=41614097.00 p50=43936703.00 p75=45788234.00 p90=47055897.00}, writesPerReplica={p10=0.00 p25=0.00 p50=0.00 p75=0.00 p90=0.00}
I170829 14:01:27.717539 19 server/node.go:326  [n1] node ID 1 initialized
I170829 14:01:27.717678 19 gossip/gossip.go:311  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"rebal-3to5s-awesomemurdock-cockroach-1:26257" > attrs:<> locality:<> ServerVersion:<major_val:1 minor_val:0 patch:0 unstable:3 >
I170829 14:01:27.717850 19 storage/stores.go:303  [n1] read 2 node addresses from persistent storage
I170829 14:01:27.718044 19 storage/stores.go:322  [n1] wrote 4 node addresses to persistent storage
I170829 14:01:27.718160 19 server/node.go:606  [n1] connecting to gossip network to verify cluster ID...
I170829 14:01:27.718200 19 server/node.go:631  [n1] node connected via gossip and verified as part of cluster "d840ed4f-e385-42d2-8eb7-faddc8ef2b71"
I170829 14:01:27.718266 19 server/node.go:403  [n1] node=1: started with [<no-attributes>=/mnt/data0] engine(s) and attributes []
I170829 14:01:27.718374 19 sql/executor.go:383  [n1] creating distSQLPlanner with address {tcp rebal-3to5s-awesomemurdock-cockroach-1:26257}
I170829 14:01:27.726237 19 server/server.go:879  [n1] starting http server at rebal-3to5s-awesomemurdock-cockroach-1:8080
I170829 14:01:27.726258 19 server/server.go:880  [n1] starting grpc/postgres server at rebal-3to5s-awesomemurdock-cockroach-1:26257
I170829 14:01:27.726274 19 server/server.go:881  [n1] advertising CockroachDB node at rebal-3to5s-awesomemurdock-cockroach-1:26257
W170829 14:01:27.726313 19 sql/jobs/registry.go:156  [n1] unable to get node liveness: node not in the liveness table
I170829 14:01:27.727515 108 vendor/google.golang.org/grpc/grpclog/grpclog.go:75  grpc: Server.processUnaryRPC failed to write status connection error: desc = "transport is closing"
I170829 14:01:27.903858 182 storage/replicate_queue.go:211  [replicate,n1,s1,r219/1:/Table/51/1/16{59367…-97144…}] no rebalance target found, not enqueuing
I170829 14:01:28.104504 182 storage/replicate_queue.go:211  [replicate,n1,s1,r253/1:/Table/51/1/56{59927…-95805…}] no rebalance target found, not enqueuing
I170829 14:01:28.305076 182 storage/replicate_queue.go:211  [replicate,n1,s1,r286/1:/Table/51/1/2{479350…-516543…}] no rebalance target found, not enqueuing
I170829 14:01:28.505627 182 storage/replicate_queue.go:211  [replicate,n1,s1,r22/1:/Table/51/1/40{05578…-38689…}] no rebalance target found, not enqueuing
I170829 14:01:28.706785 182 storage/replicate_queue.go:211  [replicate,n1,s1,r172/1:/Table/51/1/42{04972…-34334…}] no rebalance target found, not enqueuing
```

with plenty of these after:
```
I170829 14:02:25.896055 182 storage/allocator.go:241  [replicate,n1,s1,r236/1:/Table/51/1/15{08328…-45226…}] unable to take action - live replicas [] don't meet quorum of 2
```

**Comment by a-robinson** [comment] 2017-08-29 18:29
@cuongdo that zip file doesn't appear to exist on github servers. Still have a copy that you can reupload?

**Comment by cuongdo** [comment] 2017-08-29 18:31
This is a more recent failure through TeamCity that has server logs in the artifacts:

https://teamcity.cockroachdb.com/viewLog.html?buildId=337646&tab=buildResultsDiv&buildTypeId=Cockroach_AllocatorTest3to510g

The errors look different for some reason.

**Comment by a-robinson** [comment] 2017-08-29 18:36
That test run looks downright busted. The stderr artifacts don't include any actual logs (did we change the log settings for acceptance tests recently?) and the block writer output indicates that the cluster got completely stuck early on in the test.

**Comment by cuongdo** [comment] 2017-08-29 18:47
The `cockroach.{stderr,stdout}` files only have the CockroachDB startup messages. Most logs are in `node.?/cockroach/cockroach.log`. For example:

https://teamcity.cockroachdb.com/repository/download/Cockroach_AllocatorTest3to510g/337646:id/acceptance/node.0/cockroach/cockroach.log

**Comment by a-robinson** [comment] 2017-08-29 19:17
Doh, thanks. I don't know why my brain wasn't processing the additional "cockroach" dropdowns.

Anyways, the splits on the cluster are pretty messed up. Tons of snapshots are failing with intersection errors for a bunch of different ranges. There may also be an issue with the replicate queue getting stuck, but it's hard to tell whether that's just a symptom of all the snapshot errors.

```
E170829 18:12:26.917477 124 storage/queue.go:656  [raftsnapshot,n3,s3,r363/3:/Table/1{7-8}] snapshot failed: (n1,s1):1: remote couldn't accept snapshot with error: [n1,s1],r363: cannot apply snapshot: snapshot intersects existing range [n1,s1,r5/1:/Table/{14-50}]
```

I'm trying to reproduce so that I can have a running cluster to examine.

**Comment by cuongdo** [comment] 2017-08-30 11:57
This happened again with last night's run. Let me know if you want me to set up a cluster to poke at. I can copy your SSH public key over and give you full access.

**Comment by a-robinson** [comment] 2017-08-30 14:07
No need, I didn't have any trouble reproducing it last night. I don't have it narrowed down to its cause yet, but there's a very real problem with taking the old store directories and running them with new binaries. The clusters are broken before we even add nodes 4 and 5, and before rebalancing ever starts.

What's really weird is that node 1 can't serve queries that nodes 2 and 3 can. For example, `select * from system.rangelog limit 10` hung on node 1 but succeeded almost immediately on nodes 2 and 3.

At least part of the issue is that some initial splits happen on node 2 that node 1 never catches up with. It's left with an unsplit range, but it never catches up on raft. In what may be relevant, on both broken clusters I looked at node 1's copy was in the `PreCandidate` raft state a few terms ahead of the other replicas (example in screenshot below).

I initially tried following up on my thought that the bad splits were caused by https://github.com/cockroachdb/cockroach/pull/17810. The first time I ran the test with those commits reverted, everything did work fine. I tried it again, though, and the test still failed in the same way. Testing with https://github.com/cockroachdb/cockroach/pull/17808 reverted would be a reasonable next step, but I also clearly need to enable more verbose logging of non-allocator modules.

**Comment by a-robinson** [comment] 2017-08-30 14:09
And to add some logs, part of the problem is appearing in the form of context cancellations on node 1. Both in splits and in lease requests:

```
I170830 01:57:45.228885 97 storage/replica_command.go:2702  [split,n1,s1,r354/1:/System/ts{d-e}] initiating a split of this range at key /System/tsd/cr.node.sql.mem.internal.txn.max-p75/1/10s/2017-08-29T23:00:00Z [r754]
W170830 01:58:40.401946 97 internal/client/txn.go:525  [split,n1,s1,r354/1:/System/ts{d-e}] failure aborting transaction: context deadline exceeded; abort caused by: failed to send RPC: sending to all 3 replicas failed; last error: {<nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded}
E170830 01:58:40.402004 97 storage/queue.go:656  [split,n1,s1,r354/1:/System/ts{d-e}] storage/replica_command.go:2782: split at key /System/tsd/cr.node.sql.mem.internal.txn.max-p75/1/10s/2017-08-29T23:00:00Z failed: failed to send RPC: sending to all 3 replicas failed; last error: {<nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded}
I170830 01:58:46.737140 97 storage/replica_command.go:2702  [split,n1,s1,r354/1:/System/ts{d-e}] initiating a split of this range at key /System/tsd/cr.node.sql.mem.internal.txn.max-p75/4/10s/2017-08-29T19:00:00Z [r755]
W170830 01:59:40.402689 97 internal/client/txn.go:525  [split,n1,s1,r354/1:/System/ts{d-e}] failure aborting transaction: context deadline exceeded; abort caused by: failed to send RPC: sending to all 3 replicas failed; last error: {<nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded}
E170830 01:59:40.402746 97 storage/queue.go:656  [split,n1,s1,r354/1:/System/ts{d-e}] storage/replica_command.go:2782: split at key /System/tsd/cr.node.sql.mem.internal.txn.max-p75/4/10s/2017-08-29T19:00:00Z failed: failed to send RPC: sending to all 3 replicas failed; last error: {<nil> rpc error: code = DeadlineExceeded desc = context deadline exceeded}
I170830 01:59:44.016189 97 storage/replica_command.go:2702  [split,n1,s1,r354/1:/System/ts{d-e}] initiating a split of this range at key /System/tsd/cr.node.sql.mem.internal.txn.max-p50/1/10s/2017-08-29T23:00:00Z [r756]
```

```
W170830 03:24:25.826077 2561 storage/replica.go:2643  [split,n1,s1,r5/1:/Table/{14-50}] context cancellation after 2.8s of attempting command RequestLease [/Table/14,/Min)
W170830 03:27:25.827212 6399 storage/replica.go:2643  [split,n1,s1,r5/1:/Table/{14-50}] context cancellation after 2.8s of attempting command RequestLease [/Table/14,/Min)
```

**Comment by a-robinson** [comment] 2017-08-30 17:29
So after disabling prevote, I've now had 3 straight runs that didn't hit this problem. That's not conclusive, but it's pretty fishy given the failure rate I've observed with prevote enabled.

I'm going to do a run with prevote enabled again and a bunch of verbose logging turned on to try and narrow in on the issue. Is there anything specific you'd suggest looking at, @bdarnell?

**Comment by bdarnell** [comment] 2017-08-30 18:16
> on both broken clusters I looked at node 1's copy was in the PreCandidate raft state a few terms ahead of the other replicas (example in screenshot below).

Where is that screenshot?

> I'm going to do a run with prevote enabled again and a bunch of verbose logging turned on to try and narrow in on the issue. Is there anything specific you'd suggest looking at, @bdarnell?

The main thing I'd look at is the interaction with quiesced replicas. When a replica is stuck as a PreCandidate, is it quiesced? Are the other replicas quiesced? Is there a leader?

**Comment by a-robinson** [comment] 2017-08-30 18:24
Sorry, here are screenshots of the range:

<img width="480" alt="screen shot 2017-08-30 at 2 21 53 pm" src="https://user-images.githubusercontent.com/7085343/29888359-a4896ff8-8d8e-11e7-87cc-6f4f8c4a74da.png">

<img width="616" alt="screen shot 2017-08-30 at 2 22 00 pm" src="https://user-images.githubusercontent.com/7085343/29888366-a719324e-8d8e-11e7-8285-7302472f4c64.png">

**Comment by a-robinson** [comment] 2017-08-30 18:30
Or check out http://rebal-3to5s-lonelyjennings-cockroach-2.eastus.cloudapp.azure.com:8080/#/reports/problemranges for your pick of ranges currently in this state

**Comment by bdarnell** [comment] 2017-08-30 18:55
This is a very old backup, from before the introduction of epoch leases (it's interesting that node 2, as the lease holder when the backup was taken, was able to backdate its new epoch lease to 2016). It also predates propEvalKV, which is a problem. We don't support upgrading clusters that old any more; if there were any raft log entries that were committed but unapplied, things will break (I would not expect that to manifest as raft election problems, but I don't actually know what it would look like). 

To salvage this backup, run it with beta-20170413 and save a fresh copy before upgrading to anything 1.0 or later.

**Comment by a-robinson** [comment] 2017-08-30 18:58
Ugh, I had been reading that as June 2017, not June 2016. Yup, looking into this as it currently stands is pretty worthless.

**Comment by a-robinson** [comment] 2017-08-30 19:04
@cuongdo was anything special required to create these dumps way back in 3ef36e66441c008a2d339ef6cf4798b6a4e3bd7a? Should we create new dumps or should we download the existing ones, migrate them to be usable with post-1.0 builds, and re-upload them?

**Comment by cuongdo** [comment] 2017-08-30 19:07
It's interesting that these tests have been mostly working this whole time.

In any case, the dumps were created using `block_writer`. There's nothing at all valuable about these dumps, so they should be recreated. I can do that.

**Comment by a-robinson** [comment] 2017-08-30 19:10
Well, just because there's no guarantee that such upgrades work it doesn't mean that they're guaranteed not to :) It is interesting that prevote seems to tickle the badness more often, but making a situation that already has undefined behavior break more frequently isn't necessarily bad.

**Comment by irfansharif** [comment] 2017-09-01 10:55
I'm going to err on the side of disabling PreVote here given we're cutting today: #18128, this in response to the incidents tracked in #release yesterday but informs this issue as well.

**Closed** 2017-09-01 19:44 UTC
