### ISSUE TITLE
sql: JDBC metadata fails to query indexes (liquibase)

### ISSUE THREAD

**Issue by ruzkant** [cockroachdb/cockroach#24713] opened 2018-04-12 05:00 UTC
The following query fails when quering jdbc metadata from liquibase for the <indexExists> element in a changeset.

```
SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM,   ct.relname AS TABLE_NAME, NOT i.indisunique AS NON_UNIQUE,   NULL AS INDEX_QUALIFIER, ci.relname AS INDEX_NAME,   CASE i.indisclustered     WHEN true THEN 1    ELSE CASE am.amname       WHEN 'hash' THEN 2      ELSE 3    END   END AS TYPE,   (i.keys).n AS ORDINAL_POSITION,   trim(both '"' from pg_catalog.pg_get_indexdef(ci.oid, (i.keys).n, false)) AS COLUMN_NAME,   CASE am.amcanorder     WHEN true THEN CASE i.indoption[(i.keys).n - 1] & 1       WHEN 1 THEN 'D'       ELSE 'A'     END     ELSE NULL   END AS ASC_OR_DESC,   ci.reltuples AS CARDINALITY,   ci.relpages AS PAGES,   pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS FILTER_CONDITION FROM pg_catalog.pg_class ct   JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)   JOIN (SELECT i.indexrelid, i.indrelid, i.indoption,           i.indisunique, i.indisclustered, i.indpred,           i.indexprs,           information_schema._pg_expandarray(i.indkey) AS keys         FROM pg_catalog.pg_index i) i     ON (ct.oid = i.indrelid)   JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)   JOIN pg_catalog.pg_am am ON (ci.relam = am.oid) WHERE true  AND n.nspname = 'public' AND ct.relname = 'act_de_databasechangelog' ORDER BY NON_UNIQUE, TYPE, INDEX_NAME, ORDINAL_POSITION
```

Error:
```
invalid syntax: statement ignored: syntax error at or near "."
```
So this is related to _pg_expandarray work that is ongoing, but I am not sure if other nooks and crannies of the query works as I am not too clued up on the catalog structures.

**Comment by ruzkant** [comment] 2018-04-12 05:01
@BramGruneir the promised issue

**Comment by BramGruneir** [comment] 2018-04-12 20:31
I tried to clean up the query a bit:

```sql
SELECT NULL AS table_cat,
       n.nspname AS table_schem,
       ct.relname AS TABLE_NAME,
       NOT i.indisunique AS non_unique,
       NULL AS index_qualifier,
       ci.relname AS index_name,
       CASE i.indisclustered
         WHEN TRUE THEN 1
         ELSE CASE am.amname
           WHEN 'hash' THEN 2
           ELSE 3
         END
       END AS TYPE, 
       (i.KEYS).n AS ordinal_position,
       trim(BOTH '"' FROM pg_catalog.pg_get_indexdef(ci.oid, (i.KEYS).n, FALSE)) AS COLUMN_NAME,
       CASE am.amcanorder
         WHEN TRUE THEN CASE i.indoption[(i.keys).n - 1] & 1
           WHEN 1 THEN 'D'
           ELSE 'A'
         END
         ELSE NULL
       END AS asc_or_desc,
       ci.reltuples AS CARDINALITY,
       ci.relpages AS pages,
       pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS filter_condition
FROM pg_catalog.pg_class ct
JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid)
JOIN (
  SELECT i.indexrelid,
         i.indrelid,
         i.indoption,
         i.indisunique,
         i.indisclustered,
         i.indpred,
         i.indexprs,
         information_schema._pg_expandarray(i.indkey) AS KEYS
  FROM pg_catalog.pg_index i
) i 
  ON (ct.oid = i.indrelid)
JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid)
JOIN pg_catalog.pg_am am ON (ci.relam = am.oid)
WHERE TRUE
  AND n.nspname = 'public'
  AND ct.relname = 'act_de_databasechangelog'
ORDER BY non_unique,
         TYPE,
         index_name,
         ordinal_position
```

**Comment by knz** [comment] 2018-04-23 13:57
This is a dup of #16971. @BramGruneir please take the example query and add it to #16971 as an additional example query that should be tested. Then close this issue.

**Comment by knz** [comment] 2018-05-05 01:26
Duplicate of #16971.

**Closed by knz** 2018-05-05 01:26 UTC
Labels: A-pg-compat, C-enhancement, O-community
