### ISSUE TITLE
sql: panic in indexed var name resolution

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15976] opened 2017-05-17 10:45 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/272149669/

```
*errors.errorString: *errors.errorString v3.go:353
  File "github.com/cockroachdb/cockroach/pkg/sql/pgwire/v3.go", line 353, in func1
  File "github.com/cockroachdb/cockroach/pkg/sql/executor.go", line 507, in logIfPanicking
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/indexed_vars.go", line 139, in AssertSameContainer
  File "github.com/cockroachdb/cockroach/pkg/sql/select_name_resolution.go", line 74, in VisitPre
  File "github.com/cockroachdb/cockroach/pkg/sql/parser/walk.go", line 548, in WalkExpr
...
(37 additional frame(s) were not displayed)

*errors.errorString v3.go:353
```

If I am reading this right, an IndexedVar was already resolved, then injected into a render from a different planNode, then resolved again. (The fact this resolution is occurring in the context of a subquery is probably not relevant)
cc @jordanlewis @raduberinde

**Comment by knz** [comment] 2017-05-17 10:47
The last level in the expression walk was in a WindowDef expression.

**Comment by cuongdo** [comment] 2017-05-17 10:49
Dupe of #15970?

**Comment by knz** [comment] 2017-05-17 10:51
Can't say without checking the stack trace more thoroughly.

**Comment by jordanlewis** [comment] 2017-05-17 14:30
Indeed this is a dupe of #15970.

**Closed by jordanlewis** 2017-05-17 14:30 UTC
