### ISSUE TITLE
sql: temp table can still persist when parent database is dropped

### ISSUE THREAD

**Issue by chengxiong-ruan** [cockroachdb/cockroach#106606] opened 2023-07-11 17:44 UTC
**Describe the problem**
In https://github.com/cockroachlabs/support/issues/2421 we saw an case where the parent database of a temporary table was dropped but the temp table descriptor still exists. We don't see a way how this can be reproduced. That would be the 1st step.

Jira issue: CRDB-29639

**Comment by rafiss** [comment] 2023-07-11 18:29
Let's see if we can reproduce this. If we are unable to, we can leave this as a tracking issue in case this reoccurs in the future.

**Comment by rafiss** [comment] 2023-08-15 18:22
Looks like we tracked this down in https://github.com/cockroachdb/cockroach/issues/108751, so I'll close this.

**Closed by rafiss** 2023-08-15 18:22 UTC
Labels: C-bug, T-sql-foundations
