### ISSUE TITLE
storage: leaked iterator panic during node shut-down

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#44863] opened 2020-02-07 16:06 UTC
Customer is reporting the following when restarting a node:

```
E200205 19:25:43.608369 1802165988 util/log/crash_reporting.go:207 a panic has occurred!
E200205 19:25:53.608743 1802165988 util/log/crash_reporting.go:539 Time out trying to submit crash report
panic: 1 leaked iterators [recovered]
panic: 1 leaked iterators

goroutine 1802165988 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc0001dd170, 0x497dbc0, 0xc009bb4db0)
/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:181 +0x121
panic(0x3b7e5c0, 0xc031cab820)
/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/cockroachdb/cockroach/pkg/storage/engine.(*RocksDB).Close(0xc000495080)
/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:772 +0x3e4
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBTempEngine).Close(0xc00004c060)
/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/temp_engine.go:30 +0x2e
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Stop(0xc0001dd170, 0x497dbc0, 0xc009bb4db0)
/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:493 +0x3c8
github.com/cockroachdb/cockroach/pkg/server.(*adminServer).Drain.func1(0xc000ce09a0, 0x497dbc0, 0xc009bb4db0)
/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go:1380 +0x64
created by github.com/cockroachdb/cockroach/pkg/server.(*adminServer).Drain
/go/src/github.com/cockroachdb/cockroach/pkg/server/admin.go:1374 +0x2f5
```

The panic is interleaved with other regular node shut-down messages without other warnings.

See https://cockroachdb.zendesk.com/agent/tickets/4644 for more details including debug zip, logs etc

Jira issue: CRDB-5198

**Comment by knz** [comment] 2020-02-07 16:06
@itsbilal this is the issue we discussed yesterday

**Comment by itsbilal** [comment] 2020-02-07 16:15
Thanks for creating this issue, @knz!

There's some use of `DiskRowContainer` (which wraps the `SortedDiskMap` for the temp engine) that is not correctly `defer`-ing an `iter.Close()`. The panic listed happened during a node shutdown, and the temp engine was `Close()`ed before all iterators were.

Fixing this issue would involve diving into all uses of `DiskRowContainer` and the iterators it spawns, to see if all of them would get cleaned up in a node shutdown case.

**Comment by knz** [comment] 2020-02-07 16:15
Ok cool @asubiotto can you triage this then?

**Comment by asubiotto** [comment] 2020-02-07 16:38
Gladly. These iterators must be retained across calls to `Next`, so we can't just `defer i.Close` them. The problem is that these iterators are only cleaned up when a flow terminates gracefully or not, but not when the stack is unwinding on a panic. We never do any cleanup in a flow when a panic happens. We're looking at registering `Closer`s in a flow to perform this type of cleanup in the vectorized engine for a graceful case and this method could probably be reused to solve this issue. cc @yuzefovich 

This issue doesn't seem like super-high priority so we'll get to it in the next couple of weeks. Thanks for raising it!

**Comment by yuzefovich** [comment] 2020-02-07 16:41
Wait, this is in row-by-row execution engine, I don't think it relates to the discussion we had about cleaning up disk infrastructure when vectorized flow needs to shutdown before the query completes.

**Comment by asubiotto** [comment] 2020-02-07 16:42
Yes, but the same idea can be reused for the row-by-row execution engine in the case of panics.

**Comment by itsbilal** [comment] 2023-09-13 17:12
@DrewKimball  that’s #110520

**Comment by DrewKimball** [comment] 2023-09-13 17:30
>@DrewKimball that’s https://github.com/cockroachdb/cockroach/issues/110520

Thank you, I couldn't find that for some reason.

**Comment by DrewKimball** [comment] 2023-09-19 18:41
Question for storage: what would cause a leaked iterator?

From the test failure:
```
     F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1  error during engine close: leaked iterators:
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 +0.0:
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 +  000005:[a\x00#10,RANGEKEYSET-n\x00#inf,RANGEKEYSET]
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !goroutine 7339 [running]:
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !runtime/debug.Stack()
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  GOROOT/src/runtime/debug/stack.go:24 +0x64
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}}, ...})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/clog.go:274 +0x9c
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x223e6a0, 0x4000c72840}, 0x2, 0x4, 0x0, 0x0?, {0x1d83f71, 0x1e}, {0x4000f556f8, 0x1, ...})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/channels.go:109 +0x40c
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(...)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/bazel-out/aarch64-fastbuild/bin/pkg/util/log/log_channels_generated.go:848
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close.func1({0x22265a0?, 0x4000bbd7e8?})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1431 +0x7c
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage.(*Pebble).Close(0x40004a5b00)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/storage/pebble.go:1437 +0xdc
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !runtime.Goexit()
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  GOROOT/src/runtime/panic.go:522 +0x174
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !testing.(*common).FailNow(0x4000af2340)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  GOROOT/src/testing/testing.go:980 +0x44
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.runDirective({0x2257fb8, 0x4000af2340}, 0x40009db320, 0x0?)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:352 +0x84
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.runDirectiveOrSubTest({0x2257fb8, 0x4000af2340}, 0x4000af2340?, {0x0, 0x0}, 0x4000010528?)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:211 +0x84
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.runTestInternal({0x2257fb8, 0x4000af2340}, {0x400075d180, 0x13a}, {0x22286a0, 0x4000010528}, 0x400072c980?, 0x10?)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:184 +0x88
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.RunTestAny({0x2257fb8, 0x4000af2340}, {0x400075d180, 0x13a}, 0x1?)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:144 +0x228
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.RunTest(0x4000af2340, {0x400075d180, 0x13a}, 0x40004e4280)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:117 +0x88
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/cockroach/pkg/storage_test.TestMVCCHistories.func1(0x4000af2340, {0x400075d180, 0x13a})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/cockroach/pkg/storage_test/pkg/storage/mvcc_history_test.go:374 +0x5e0
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.Walk.func1({0x2257fb8?, 0x4000af2340?}, {0x400075d180?, 0x13a?})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:425 +0x54
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.WalkAny({0x2257fb8, 0x4000af2340}, {0x400075d180, 0x13a}, 0x400072c600)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:436 +0x188
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.WalkAny.func1({0x2257fb8, 0x4000af2340})
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/datadriven.go:449 +0x98
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !github.com/cockroachdb/datadriven.subTest.func1(0x400005a068?)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  github.com/cockroachdb/datadriven/external/com_github_cockroachdb_datadriven/test_interface.go:27 +0x30
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !testing.tRunner(0x4000af2340, 0x400071bef0)
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  GOROOT/src/testing/testing.go:1576 +0x104
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !created by testing.(*T).Run
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !  GOROOT/src/testing/testing.go:1629 +0x370
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !For more context, check log files in: /artifacts/tmp/_tmp/df49cd4529be694977d51f20f1abedea/logTestMVCCHistories3228575326
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !****************************************************************************
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !This node experienced a fatal error (printed above), and as a result the
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !process is terminating.
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !Fatal errors can occur due to faulty hardware (disks, memory, clocks) or a
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !problem in CockroachDB. With your help, the support team at Cockroach Labs
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !will try to determine the root cause, recommend next steps, and we can
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !improve CockroachDB based on your report.
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !Please submit a crash report by following the instructions here:
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !    https://github.com/cockroachdb/cockroach/issues/new/choose
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !If you would rather not post publicly, please contact us directly at:
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !    support@cockroachlabs.com
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !
      F230913 16:12:23.565822 7339 storage/pebble.go:1431  [s?,pebble] 1 !The Cockroach Labs team appreciates your feedback.
```

**Comment by jbowens** [comment] 2023-09-20 17:51
> Question for storage: what would cause a leaked iterator?

It's always some client code above storage that's failing to close an iterator. It's common in unit tests during a panic too, because the stack is unwound without calling Close on the iterator.

I'll close this ancient ticket out.

**Closed by jbowens** 2023-09-20 17:51 UTC
Labels: C-investigation, O-support, A-storage, A-sql-execution, T-storage, T-sql-queries
