### ISSUE TITLE
Violation of Foreign Key constraint in “task_metadata_fk” when launching a Task in Spring Cloud Data Flow with CockroachDB

### ISSUE THREAD

**Issue by louispool** [cockroachdb/cockroach#57732] opened 2020-12-09 11:20 UTC
**Describe the problem**

I posted a question on Stackoverflow here: [https://stackoverflow.com/questions/65126245/violation-of-foreign-key-constraint-in-task-metadata-fk-when-launching-a-task](https://stackoverflow.com/questions/65126245/violation-of-foreign-key-constraint-in-task-metadata-fk-when-launching-a-task)

I'm trying to launch Spring Cloud Data Flow (SCDF) with CockroachDB as the underlying persistence layer.

As far as the Schema creation, and running  Spring Tasks and Spring Batch, that seems to function flawlessly with the Hibernate ORM. 

But when I try to launch tasks using the SCDF I run into the following exception:

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT INTO task_execution_metadata (id, task_execution_id, task_execution_manifest) VALUES (?, ?, ?)]; ERROR: insert on table "task_execution_metadata" violates foreign key constraint "task_metadata_fk"
  Detail: Key (task_execution_id)=(14) is not present in table "task_execution".; nested exception is org.postgresql.util.PSQLException: ERROR: insert on table "task_execution_metadata" violates foreign key constraint "task_metadata_fk"
  Detail: Key (task_execution_id)=(14) is not present in table "task_execution".
```

`task_execution_id` is a self incrementing identifier so in the logs I post you may see different values for it. In the above log, I had tried to launch a task 14 times already.

Looking at the SQL access log on my node I could see the following order of operations:

```
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT taskdeploy0_.id AS id1_4_, taskdeploy0_.object_version AS object_v2_4_, taskdeploy0_.created_on AS created_3_4_, taskdeploy0_.platform_name AS platform4_4_, taskdeploy0_.task_definition_name AS task_def5_4_, taskdeploy0_.task_deployment_id AS task_dep6_4_ FROM task_deployment AS taskdeploy0_ WHERE taskdeploy0_.task_definition_name = $1 ORDER BY taskdeploy0_.created_on ASC LIMIT $2"› ‹{$1:"'run-batch-client'", $2:"1"}› 1.053 0 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT taskdefini0_.definition_name AS definiti1_3_0_, taskdefini0_.description AS descript2_3_0_, taskdefini0_.definition AS definiti3_3_0_ FROM task_definitions AS taskdefini0_ WHERE taskdefini0_.definition_name = $1"› ‹{$1:"'run-batch-client'"}› 0.904 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT appregistr0_.id AS id1_0_, appregistr0_.object_version AS object_v2_0_, appregistr0_.default_version AS default_3_0_, appregistr0_.metadata_uri AS metadata4_0_, appregistr0_.name AS name5_0_, appregistr0_.type AS type6_0_, appregistr0_.uri AS uri7_0_, appregistr0_.version AS version8_0_ FROM app_registration AS appregistr0_ WHERE ((appregistr0_.name = $1) AND (appregistr0_.type = $2)) AND (appregistr0_.default_version = true)"› ‹{$1:"'batch-client'", $2:"4"}› 0.953 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT nextval('TASK_SEQ')"› ‹{}› 32.725 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"INSERT INTO task_execution(task_execution_id, exit_code, start_time, task_name, last_updated, external_execution_id, parent_execution_id) VALUES ($1, $2, $3, $4, $5, $6, $7)"› ‹{$1:"14", $2:"NULL", $3:"NULL", $4:"'run-batch-client'", $5:"'2020-12-07 16:55:55.733'", $6:"NULL", $7:"NULL"}› 1.612 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT task_execution_manifest FROM task_execution_metadata AS m INNER JOIN task_execution AS e ON m.task_execution_id = e.task_execution_id WHERE e.task_name = $1 ORDER BY e.task_execution_id DESC LIMIT 1 OFFSET 0"› ‹{$1:"'run-batch-client'"}› 2.138 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT nextval('task_execution_metadata_seq')"› ‹{}› 3.576 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"INSERT INTO task_execution_metadata(id, task_execution_id, task_execution_manifest) VALUES ($1, $2, $3)"› ‹{$1:"13", $2:"14", $3:"'{\"taskDeploymentRequest\":{\"definition\":{\"name\":\"run-batch-client\",\"properties\":{\"management.metrics.tags.service\":\"task-application\",\"spring.datasource.username\":\"SA\",\"spring.datasource.url\":\"jdbc:postgresql://localhost:26257/batchdb?ssl=false\",\"spring.datasource.driverClassName\":\"org.postgresql.Driver\", <SNIP>\"--spring.cloud.task.executionid=14\"]},\"platformName\":\"default\"}'"}› 1.007 1 ‹"insert on table \"task_execution_metadata\" violates foreign key constraint \"task_metadata_fk\""› 0
```
A foreign key violation occurs on `task_execution_id` = 14 even though it was inserted into the `task_execution` table in a previous insertion operation.

**To Reproduce**

1. Set up local insecure single-node Cockroach cluster at `localhost:26257`
2. Create database `batchdb` and user `SA` with full rights on the database
2. Install Spring Cloud Dataflow Server for Batch Mode only: https://dataflow.spring.io/docs/recipes/batch/batch-only-mode/
3. Run SCDF with the following configuration:

```
spring.datasource.url=jdbc:postgresql://localhost:26257/batchdb?ssl=false
spring.datasource.username=SA
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.initialization-mode=always

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.CockroachDB201Dialect

spring.cloud.dataflow.features.streams-enabled=false
spring.cloud.dataflow.features.schedules-enabled=false
spring.cloud.dataflow.features.tasks-enabled=true
```
4. Once SCDF is running, go to the dashboard at `http://localhost:9393/dashboard`, register an app (you can use the sample spring app coordinates), create a task and then launch the task.

**Additional data / screenshots**

Table schema for `task_execution`:
```sql
CREATE  TABLE public.task_execution ( 
	task_execution_id INT8  NOT  NULL, 
	start_time TIMESTAMP  NULL, 
	end_time TIMESTAMP  NULL, 
	task_name VARCHAR(100) NULL, 
	exit_code INT8  NULL, 
	exit_message VARCHAR(2500) NULL, 
	error_message VARCHAR(2500) NULL, 
	last_updated TIMESTAMP  NULL, 
	external_execution_id VARCHAR(255) NULL, 
	parent_execution_id INT8  NULL, 
	CONSTRAINT  "primary" PRIMARY KEY (task_execution_id ASC), 
	FAMILY "primary" (task_execution_id, start_time, end_time, task_name, exit_code, exit_message, error_message, last_updated, external_execution_id, parent_execution_id) 
)
```
Table schema for `task_execution_metadata`:
```sql
CREATE  TABLE public.task_execution_metadata ( 
	id  INT8  NOT  NULL, 
	task_execution_id INT8  NOT  NULL, 
	task_execution_manifest STRING  NULL, 
	CONSTRAINT  "primary" PRIMARY KEY (id  ASC), 
	CONSTRAINT task_metadata_fk FOREIGN KEY (task_execution_id) REFERENCES public.task_execution(task_execution_id), 
	FAMILY "primary" (id, task_execution_id, task_execution_manifest) 
)
```
**Environment:**
 - CockroachDB 20.2
 - Spring Cloud Dataflow Server 2.7.0 / 2.8.0-SNAPSHOT
 - Ubuntu Linux / Windows 10 / WSL
 - JDBC postgresql driver 42.2.18

**Additional context**

If I try and reproduce the issue with a small Spring JPA application, with two tables `task` and `sub_task` of a similar scheme to SCDF's `task_exection` and `task_execution_metadata` tables, using the same `postgresql`  driver:

```
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"INSERT INTO task(body, id) VALUES ($1, $2)"› ‹{$1:"'task'", $2:"3"}› 0.467 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT subtask0_.id AS id1_0_0_, subtask0_.body AS body2_0_0_, subtask0_.parent_id AS parent_i3_0_0_ FROM sub_task AS subtask0_ WHERE subtask0_.id = $1"› ‹{$1:"3"}› 0.546 0 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"SELECT task0_.id AS id1_1_0_, task0_.body AS body2_1_0_ FROM task AS task0_ WHERE task0_.id = $1"› ‹{$1:"3"}› 0.367 1 ‹""› 0
‹exec› ‹"PostgreSQL JDBC Driver"› ‹{}› ‹"INSERT INTO sub_task(body, parent_id, id) VALUES ($1, $2, $3)"› ‹{$1:"'sub-task'", $2:"3", $3:"3"}› 0.961 1 ‹""› 0
```
the same insertion call does not incur the foreign key violation.

At this point I am out of ideas and would really appreciate any thoughts or ideas on the issue.

**Comment by rafiss** [comment] 2020-12-10 00:05
@louispool  Thanks for filing this issue. I am trying to follow your steps to reproduce this. One question -- where do I place the configuration file that you pasted?

**Comment by louispool** [comment] 2020-12-10 00:32
Hi @rafiss, thanks for taking a look. SCDF will by default look for a config server at `localhost:8888` where it pulls it configuration from. If you don't want to set up a config service you can specify the properties as program arguments, as described here: https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-local

**Comment by rafiss** [comment] 2020-12-10 15:39
@louispool Thanks for the pointer. I was able to get it running and reproduce the issue.

I was also able to follow the same instructions, except using a PostgreSQL backend. The steps work when using the `read committed` isolation level in PostgreSQL, but they do not work when I change `postgresql.conf` to make the isolation level `serializable`. With this setting, I get the same FK error in PostgreSQL.

CockroachDB only supports the SERIALIZABLE isolation level. So it seems to me that this issue is a bug in Spring Cloud Data Flow, and it does not manage its transactions correctly.

I see that in SCDF, the [DefaultTaskExecutionService](https://github.com/spring-cloud/spring-cloud-dataflow/blob/639a64227203e4f7ec26b181ed0da9d98803f243/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java) starts a new transaction (`tx1`) when doing any operation. When it calls [createTaskExecution](https://github.com/spring-cloud/spring-cloud-dataflow/blob/639a64227203e4f7ec26b181ed0da9d98803f243/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionService.java#L302), it looks like that [creates a separate new transaction](https://github.com/spring-cloud/spring-cloud-dataflow/blob/038e39f02e65812721c1d1773d740f9ee2d09f45/spring-cloud-dataflow-server-core/src/main/java/org/springframework/cloud/dataflow/server/service/impl/DefaultTaskExecutionRepositoryService.java#L41) (`tx2`). Then, after `tx2` commits, `tx1` tries to insert the row into the `task_execution_metadata` table.

This does not work with SERIALIZABLE isolation, because `tx2` cannot affect `tx1` unless `tx2` commits before `tx1` starts. See these docs for more: https://www.cockroachlabs.com/docs/stable/transactions.html#serializable-isolation. READ COMMITTED does allow this kind of behavior.

I'd recommend filing an issue in the SCDF project with these details. If you point out that it doesn't work with PostgreSQL in SERIALIZABLE mode, they might pay a bit more attention. Sorry we can't help you further.

**Closed by rafiss** 2020-12-10 15:39 UTC
Labels: C-bug, O-community, X-blathers-triaged

**Comment by louispool** [comment] 2020-12-11 09:56
Thanks @rafiss. This definitely helps!
