### ISSUE TITLE
TestTxnDBLostUpdateAnomaly fails occasionally

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#2838] opened 2015-10-14 15:46 UTC
Seen locally in a `-race` build: 

```
--- FAIL: TestTxnDBLostUpdateAnomaly (2.23s)
	txn_correctness_test.go:517: ([R1(A) R2(A) I1(A) C1 I2(A) C2]): unexpected failure running R2(A): txn aborted "kv/txn_correctness_test.go:567 txn1" id=2c11c308 key="5.A" rw=true pri=0.00000005 iso=SERIALIZABLE stat=PENDING epo=1 ts=0.000000000,177 orig=0.000000000,175 max=0.000000000,171
	txn_correctness_test.go:557: 5: iso=[SERIALIZABLE SERIALIZABLE], pri=[1 2], history="R1(A) R2(A) I1(A) C1 I2(A) C2": actual="R1.1(A) R2.1(A) I1.1(A)[1] R1.2(A) I2.1(A)[1] R2.2(A) I2.2(A)[1] R1.3(A) C2.2 R1.4(A) I1.4(A)[2]", verify="R0.0(A)[1 ts={62135596800 0 104789344}]": kv/txn_correctness_test.go:695: expected A=2, got 1
	txn_correctness_test.go:491: expected success, experienced 1 errors
```

**Comment by tamird** [comment] 2015-10-14 15:55
See https://github.com/cockroachdb/cockroach/issues/2180

**Comment by bdarnell** [comment] 2015-10-14 16:01
OK, so it's not multi-cpu related and it doesn't sound like much of a priority to fix. I'll leave this issue open so we'll have something to point to next time it happens.

**Comment by petermattis** [comment] 2016-02-12 16:46
Duplicate of #3123.

**Closed by petermattis** 2016-02-12 16:46 UTC
