### ISSUE TITLE
util/log: panic: logging already active

### ISSUE THREAD

**Issue by erikgrinaker** [cockroachdb/cockroach#102588] opened 2023-04-28 12:57 UTC
There seems to be a race in e.g. `log.Infof()` leading to a panic when multiple goroutines attempt to log concurrently. Seen e.g. in #84638 and #101612.

```
panic: logging already active; first use:
goroutine 5155563 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/cockroachdb/cockroach/pkg/util/log.setActive()
	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:418 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000456b20, {{{0xc018e4bd40, 0x24}, {0x0, 0x0}, {0x60add4b, 0x1}, {0x60add4f, 0x1}}, 0x1756710a3cbc0e79, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:250 +0x50
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7622280, 0xc0183dd620}, 0x2, 0x1, 0x0, 0x0?, {0x6069108, 0x1c}, {0xc0384d5b20, 0x1, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x605
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
github.com/cockroachdb/cockroach/pkg/util/log.Infof(...)
	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:277
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc0044f2a80, 0x7622280?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:655 +0x337
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc005fa4480, {0x7622280, 0xc0156c8870}, {0x7605f00, 0xc0044f2a80}, 0xc0129d2000)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:392 +0x195
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x7622280?, 0xc0156c8870?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:299 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b [recovered]
	panic: logging already active; first use:
goroutine 5155563 [running]:
runtime/debug.Stack()
	GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/cockroachdb/cockroach/pkg/util/log.setActive()
	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:418 +0xa7
github.com/cockroachdb/cockroach/pkg/util/log.(*loggerT).outputLogEntry(0xc000456b20, {{{0xc018e4bd40, 0x24}, {0x0, 0x0}, {0x60add4b, 0x1}, {0x60add4f, 0x1}}, 0x1756710a3cbc0e79, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/clog.go:250 +0x50
github.com/cockroachdb/cockroach/pkg/util/log.logfDepthInternal({0x7622280, 0xc0183dd620}, 0x2, 0x1, 0x0, 0x0?, {0x6069108, 0x1c}, {0xc0384d5b20, 0x1, ...})
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:106 +0x605
github.com/cockroachdb/cockroach/pkg/util/log.logfDepth(...)
	github.com/cockroachdb/cockroach/pkg/util/log/channels.go:39
github.com/cockroachdb/cockroach/pkg/util/log.Infof(...)
	github.com/cockroachdb/cockroach/bazel-out/k8-fastbuild/bin/pkg/util/log/log_channels_generated.go:277
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).processReady(0xc0044f2a80, 0x7622280?)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_raft.go:655 +0x337
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftSchedulerShard).worker(0xc005fa4480, {0x7622280, 0xc0156c8870}, {0x7605f00, 0xc0044f2a80}, 0xc0129d2000)
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:392 +0x195
github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*raftScheduler).Start.func2({0x7622280?, 0xc0156c8870?})
	github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/scheduler.go:299 +0x45
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2()
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:470 +0x146
created by github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx
	github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:461 +0x43b
```

Jira issue: CRDB-27551

**Comment by knz** [comment] 2023-08-17 15:46
This looks like a direct duplicate of https://github.com/cockroachdb/cockroach/issues/84638.

**Comment by knz** [comment] 2023-08-17 15:48
However, the circumstances in #101612 are different and specific to that test. I believe that's worth investigating. I propose to keep both #84638 and #101612 open simultaneously.

**Comment by abarganier** [comment] 2023-08-23 18:01
I think we can close this and consider it a duplicate of https://github.com/cockroachdb/cockroach/issues/84638, where I'll continue the resolution.

FYI, https://github.com/cockroachdb/cockroach/issues/101612 was closed & found to be due to a separate issue (fixed by https://github.com/cockroachdb/cockroach/pull/102591).

Closing.

**Closed by abarganier** 2023-08-23 18:01 UTC
Labels: C-bug, regression, T-observability-inf, A-observability-inf
