### ISSUE TITLE
sql: Presto compatibility

### ISSUE THREAD

**Issue by TedBear42** [cockroachdb/cockroach#20419] opened 2017-12-02 03:12 UTC
I'm trying to connect presto to cockroachDB.  I have been successful using the postgresql JDBC driver to connect.  I can see all databases that I have grants too and all tables and views in some of the information_schema database's tables through presto.

However there is something not right when trying to show tables that I have created.  And it relates to this query that gets generated when I fire this in presto "show tables from postgresql.db1;" I have attached this query.

[ShowTables.SQL.txt](https://github.com/cockroachdb/cockroach/files/1523520/ShowTables.SQL.txt)

Now when I look at this query in the cockroachDB console SQL I have found that the result of this query will change depending on if I'm in the db1 database or if I'm in the default top level.

>  SELECT relname FROM pg_catalog.pg_class;

When I'm in the top level my tables that my user has access to are not there.  When I'm in the database they are there.

I have tried to say use db1 in presto but I still get 0 records when listing tables in the db1 database.

Just so you can see here are the grants on db1 database and I can see the tables from the cockroach sql console, just not from presto.

> show grants on database db1;
> +----------+--------+------------+
> | Database |  User  | Privileges |
> +----------+--------+------------+
> | db1      | public | ALL        |
> | db1      | root   | ALL        |
> | db1      | userf  | ALL        |
> +----------+--------+------------+

> SHOW GRANTS ON foo;
> +-------+--------+------------+
> | Table |  User  | Privileges |
> +-------+--------+------------+
> | foo   | public | ALL        |
> | foo   | root   | ALL        |
> | foo   | userf  | ALL        |
> +-------+--------+------------+`

This is the output when running cockroach in debug mode like 
> ./cockroach start --insecure --host=10.63.128.115 --vmodule=executor=2

and I run this in presto

> show tables from postgresql.db1;

```
parsing: SET application_name = 'PostgreSQL JDBC Driver'
I171202 02:43:33.534956 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] 
preparing: SET application_name = 'PostgreSQL JDBC Driver'
I171202 02:43:33.535001 504 sql/executor.go:673  [client=10.63.128.116:60356,user=root,n1] 
execPrepared: SET application_name = 'PostgreSQL JDBC Driver'
I171202 02:43:33.535027 504 sql/executor.go:1181  [client=10.63.128.116:60356,user=root,n1] 
executing 1/1: SET application_name = 'PostgreSQL JDBC Driver'
I171202 02:43:33.535037 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] SET application_name = 'PostgreSQL JDBC Driver'
I171202 02:43:33.535058 504 sql/executor.go:2084  [client=10.63.128.116:60356,user=root,n1] query not supported for distSQL: SET / SET CLUSTER SETTING should never distribute
I171202 02:43:33.535077 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] SET done
I171202 02:43:33.536848 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] parsing: SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspn
ame = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'  
 WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'p' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  W
HEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'p' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS T
ABLE_TYPE, d.description AS REMARKS  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_cata
log.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND n.nspname LIKE 'db1' AND (false  OR ( c.relkind IN ('r','p') AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'v' AND n.nspname 
<> 'pg_catalog' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'm' )  OR ( c.relkind = 'f' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME 
I171202 02:43:33.537320 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] preparing: SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.ns
pname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'
   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'p' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END 
 WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'p' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND n.nspname LIKE 'db1' AND (false  OR ( c.relkind IN ('r','p') AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'v' AND n.nspname <> 'pg_catalog' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'm' )  OR ( c.relkind = 'f' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME 
I171202 02:43:33.538006 504 sql/executor.go:673  [client=10.63.128.116:60356,user=root,n1] execPrepared: SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, c.relname AS TABLE_NAME,  CASE n.nspname ~ '^pg_' OR n.nspname = 'information_schema'  WHEN true THEN CASE  WHEN n.nspname = 'pg_catalog' OR n.nspname = 'information_schema' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TABLE'   WHEN 'v' THEN 'SYSTEM VIEW'   WHEN 'i' THEN 'SYSTEM INDEX'   ELSE NULL   END  WHEN n.nspname = 'pg_toast' THEN CASE c.relkind   WHEN 'r' THEN 'SYSTEM TOAST TABLE'   WHEN 'i' THEN 'SYSTEM TOAST INDEX'   ELSE NULL   END  ELSE CASE c.relkind   WHEN 'r' THEN 'TEMPORARY TABLE'   WHEN 'p' THEN 'TEMPORARY TABLE'   WHEN 'i' THEN 'TEMPORARY INDEX'   WHEN 'S' THEN 'TEMPORARY SEQUENCE'   WHEN 'v' THEN 'TEMPORARY VIEW'   ELSE NULL   END  END  WHEN false THEN CASE c.relkind  WHEN 'r' THEN 'TABLE'  WHEN 'p' THEN 'TABLE'  WHEN 'i' THEN 'INDEX'  WHEN 'S' THEN 'SEQUENCE'  WHEN 'v' THEN 'VIEW'  WHEN 'c' THEN 'TYPE'  WHEN 'f' THEN 'FOREIGN TABLE'  WHEN 'm' THEN 'MATERIALIZED VIEW'  ELSE NULL  END  ELSE NULL  END  AS TABLE_TYPE, d.description AS REMARKS  FROM pg_catalog.pg_namespace n, pg_catalog.pg_class c  LEFT JOIN pg_catalog.pg_description d ON (c.oid = d.objoid AND d.objsubid = 0)  LEFT JOIN pg_catalog.pg_class dc ON (d.classoid=dc.oid AND dc.relname='pg_class')  LEFT JOIN pg_catalog.pg_namespace dn ON (dn.oid=dc.relnamespace AND dn.nspname='pg_catalog')  WHERE c.relnamespace = n.oid  AND n.nspname LIKE 'db1' AND (false  OR ( c.relkind IN ('r','p') AND n.nspname !~ '^pg_' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'v' AND n.nspname <> 'pg_catalog' AND n.nspname <> 'information_schema' )  OR ( c.relkind = 'm' )  OR ( c.relkind = 'f' ) )  ORDER BY TABLE_TYPE,TABLE_SCHEM,TABLE_NAME 
I171202 02:43:33.538170 504 sql/executor.go:1181  [client=10.63.128.116:60356,user=root,n1] executing 1/1: SELECT NULL AS table_cat, n.nspname AS table_schem, c.relname AS table_name, CASE (n.nspname ~ '^pg_') OR (n.nspname = 'information_schema') WHEN true THEN CASE WHEN (n.nspname = 'pg_catalog') OR (n.nspname = 'information_schema') THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TABLE' WHEN 'v' THEN 'SYSTEM VIEW' WHEN 'i' THEN 'SYSTEM INDEX' ELSE NULL END WHEN n.nspname = 'pg_toast' THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TOAST TABLE' WHEN 'i' THEN 'SYSTEM TOAST INDEX' ELSE NULL END ELSE CASE c.relkind WHEN 'r' THEN 'TEMPORARY TABLE' WHEN 'p' THEN 'TEMPORARY TABLE' WHEN 'i' THEN 'TEMPORARY INDEX' WHEN 'S' THEN 'TEMPORARY SEQUENCE' WHEN 'v' THEN 'TEMPORARY VIEW' ELSE NULL END END WHEN false THEN CASE c.relkind WHEN 'r' THEN 'TABLE' WHEN 'p' THEN 'TABLE' WHEN 'i' THEN 'INDEX' WHEN 'S' THEN 'SEQUENCE' WHEN 'v' THEN 'VIEW' WHEN 'c' THEN 'TYPE' WHEN 'f' THEN 'FOREIGN TABLE' WHEN 'm' THEN 'MATERIALIZED VIEW' ELSE NULL END ELSE NULL END AS table_type, d.description AS remarks FROM pg_catalog.pg_namespace AS n, pg_catalog.pg_class AS c LEFT JOIN pg_catalog.pg_description AS d ON ((c.oid = d.objoid) AND (d.objsubid = 0)) LEFT JOIN pg_catalog.pg_class AS dc ON ((d.classoid = dc.oid) AND (dc.relname = 'pg_class')) LEFT JOIN pg_catalog.pg_namespace AS dn ON ((dn.oid = dc.relnamespace) AND (dn.nspname = 'pg_catalog')) WHERE ((c.relnamespace = n.oid) AND (n.nspname LIKE 'db1')) AND ((((false OR (((c.relkind IN ('r', 'p')) AND (n.nspname !~ '^pg_')) AND (n.nspname != 'information_schema'))) OR (((c.relkind = 'v') AND (n.nspname != 'pg_catalog')) AND (n.nspname != 'information_schema'))) OR (c.relkind = 'm')) OR (c.relkind = 'f')) ORDER BY table_type, table_schem, table_name
I171202 02:43:33.538273 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] SELECT NULL AS table_cat, n.nspname AS table_schem, c.relname AS table_name, CASE (n.nspname ~ '^pg_') OR (n.nspname = 'information_schema') WHEN true THEN CASE WHEN (n.nspname = 'pg_catalog') OR (n.nspname = 'information_schema') THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TABLE' WHEN 'v' THEN 'SYSTEM VIEW' WHEN 'i' THEN 'SYSTEM INDEX' ELSE NULL END WHEN n.nspname = 'pg_toast' THEN CASE c.relkind WHEN 'r' THEN 'SYSTEM TOAST TABLE' WHEN 'i' THEN 'SYSTEM TOAST INDEX' ELSE NULL END ELSE CASE c.relkind WHEN 'r' THEN 'TEMPORARY TABLE' WHEN 'p' THEN 'TEMPORARY TABLE' WHEN 'i' THEN 'TEMPORARY INDEX' WHEN 'S' THEN 'TEMPORARY SEQUENCE' WHEN 'v' THEN 'TEMPORARY VIEW' ELSE NULL END END WHEN false THEN CASE c.relkind WHEN 'r' THEN 'TABLE' WHEN 'p' THEN 'TABLE' WHEN 'i' THEN 'INDEX' WHEN 'S' THEN 'SEQUENCE' WHEN 'v' THEN 'VIEW' WHEN 'c' THEN 'TYPE' WHEN 'f' THEN 'FOREIGN TABLE' WHEN 'm' THEN 'MATERIALIZED VIEW' ELSE NULL END ELSE NULL END AS table_type, d.description AS remarks FROM pg_catalog.pg_namespace AS n, pg_catalog.pg_class AS c LEFT JOIN pg_catalog.pg_description AS d ON ((c.oid = d.objoid) AND (d.objsubid = 0)) LEFT JOIN pg_catalog.pg_class AS dc ON ((d.classoid = dc.oid) AND (dc.relname = 'pg_class')) LEFT JOIN pg_catalog.pg_namespace AS dn ON ((dn.oid = dc.relnamespace) AND (dn.nspname = 'pg_catalog')) WHERE ((c.relnamespace = n.oid) AND (n.nspname LIKE 'db1')) AND ((((false OR (((c.relkind IN ('r', 'p')) AND (n.nspname !~ '^pg_')) AND (n.nspname != 'information_schema'))) OR (((c.relkind = 'v') AND (n.nspname != 'pg_catalog')) AND (n.nspname != 'information_schema'))) OR (c.relkind = 'm')) OR (c.relkind = 'f')) ORDER BY table_type, table_schem, table_name
I171202 02:43:33.541599 504 sql/executor.go:2084  [client=10.63.128.116:60356,user=root,n1] query not supported for distSQL: unsupported node *sql.valuesNode without SQL VALUES clause
I171202 02:43:33.542898 504 sql/executor.go:1505  [client=10.63.128.116:60356,user=root,n1] SELECT (0 results) done
```

**Comment by jordanlewis** [comment] 2017-12-02 21:49
Hi @TedBear42,

The problem is that this query relies on there being 1 entry in `pg_description` for every entry in `pg_class`. We don't currently populate `pg_description`. It's too bad that the query chose to perform an inner join against `pg_description`, since the only purpose of that part of the query is to retrieve the "remarks" about each table, which doesn't seem critical for whatever is going on here.

Is it possible for you to modify the queries being emitted by Presto? There are actually several suspicious things in this query - there's no reason for the query to re-join against pg_class dc or pg_namespace dn as far as I can tell. Here's an equivalent query that skips getting the remarks that seems to work ok:

```
SELECT NULL          AS TABLE_CAT, 
       n.nspname     AS TABLE_SCHEM, 
       c.relname     AS TABLE_NAME, 
       CASE n.nspname ~ '^pg_' 
             OR n.nspname = 'information_schema' 
         WHEN true THEN 
           CASE 
             WHEN n.nspname = 'pg_catalog' 
                   OR n.nspname = 'information_schema' THEN 
               CASE c.relkind 
                 WHEN 'r' THEN 'SYSTEM TABLE' 
                 WHEN 'v' THEN 'SYSTEM VIEW' 
                 WHEN 'i' THEN 'SYSTEM INDEX' 
                 ELSE NULL 
               end 
             WHEN n.nspname = 'pg_toast' THEN 
               CASE c.relkind 
                 WHEN 'r' THEN 'SYSTEM TOAST TABLE' 
                 WHEN 'i' THEN 'SYSTEM TOAST INDEX' 
                 ELSE NULL 
               end 
             ELSE 
               CASE c.relkind 
                 WHEN 'r' THEN 'TEMPORARY TABLE' 
                 WHEN 'p' THEN 'TEMPORARY TABLE' 
                 WHEN 'i' THEN 'TEMPORARY INDEX' 
                 WHEN 'S' THEN 'TEMPORARY SEQUENCE' 
                 WHEN 'v' THEN 'TEMPORARY VIEW' 
                 ELSE NULL 
               end 
           end 
         WHEN false THEN 
           CASE c.relkind 
             WHEN 'r' THEN 'TABLE' 
             WHEN 'p' THEN 'TABLE' 
             WHEN 'i' THEN 'INDEX' 
             WHEN 'S' THEN 'SEQUENCE' 
             WHEN 'v' THEN 'VIEW' 
             WHEN 'c' THEN 'TYPE' 
             WHEN 'f' THEN 'FOREIGN TABLE' 
             WHEN 'm' THEN 'MATERIALIZED VIEW' 
             ELSE NULL 
           end 
         ELSE NULL 
       end           AS TABLE_TYPE
FROM   pg_catalog.pg_namespace n
       LEFT JOIN pg_catalog.pg_class c
              ON (c.relnamespace = n.oid)
WHERE  c.relnamespace = n.oid 
       AND n.nspname LIKE 'db1'
       AND ( false 
              OR ( c.relkind IN ( 'r', 'p' ) 
                   AND n.nspname !~ '^pg_' 
                   AND n.nspname <> 'information_schema' ) 
              OR ( c.relkind = 'v' 
                   AND n.nspname <> 'pg_catalog' 
                   AND n.nspname <> 'information_schema' ) 
              OR ( c.relkind = 'm' ) 
              OR ( c.relkind = 'f' ) ) 
ORDER  BY table_type, 
          table_schem, 
          table_name 
```

**Comment by jordanlewis** [comment] 2017-12-02 22:03
Another way to work around this would be to modify the query generated by Presto to use the standard `obj_description` function (see  https://www.postgresql.org/docs/current/static/functions-info.html#FUNCTIONS-INFO-COMMENT-TABLE) to get the description instead of doing the join by hand.

**Comment by jordanlewis** [comment] 2017-12-02 22:11
Wait, sorry for the churn, but most of the above analysis was wrong - the query is in fact using an outer join.

Actually the query you supplied works fine for me. I have a couple of tables in a database called `test`, and running the query with `test` instead of `db1` as the `root` user with no set database produces some output:

```
root@:26257/> SELECT NULL          AS TABLE_CAT,
           ->        n.nspname     AS TABLE_SCHEM,
           ->        c.relname     AS TABLE_NAME,
           ->        CASE n.nspname ~ '^pg_'
           ->              OR n.nspname = 'information_schema'
           ->          WHEN true THEN
           ->            CASE
           ->              WHEN n.nspname = 'pg_catalog'
           ->                    OR n.nspname = 'information_schema' THEN
           ->                CASE c.relkind
           ->                  WHEN 'r' THEN 'SYSTEM TABLE'
           ->                  WHEN 'v' THEN 'SYSTEM VIEW'
           ->                  WHEN 'i' THEN 'SYSTEM INDEX'
           ->                  ELSE NULL
           ->                end
           ->              WHEN n.nspname = 'pg_toast' THEN
           ->                CASE c.relkind
           ->                  WHEN 'r' THEN 'SYSTEM TOAST TABLE'
           ->                  WHEN 'i' THEN 'SYSTEM TOAST INDEX'
           ->                  ELSE NULL
           ->                end
           ->              ELSE
           ->                CASE c.relkind
           ->                  WHEN 'r' THEN 'TEMPORARY TABLE'
           ->                  WHEN 'p' THEN 'TEMPORARY TABLE'
           ->                  WHEN 'i' THEN 'TEMPORARY INDEX'
           ->                  WHEN 'S' THEN 'TEMPORARY SEQUENCE'
           ->                  WHEN 'v' THEN 'TEMPORARY VIEW'
           ->                  ELSE NULL
           ->                end
           ->            end
           ->          WHEN false THEN
           ->            CASE c.relkind
           ->              WHEN 'r' THEN 'TABLE'
           ->              WHEN 'p' THEN 'TABLE'
           ->              WHEN 'i' THEN 'INDEX'
           ->              WHEN 'S' THEN 'SEQUENCE'
           ->              WHEN 'v' THEN 'VIEW'
           ->              WHEN 'c' THEN 'TYPE'
           ->              WHEN 'f' THEN 'FOREIGN TABLE'
           ->              WHEN 'm' THEN 'MATERIALIZED VIEW'
           ->              ELSE NULL
           ->            end
           ->          ELSE NULL
           ->        end           AS TABLE_TYPE,
           ->        d.description AS REMARKS
           -> FROM   pg_catalog.pg_namespace n,
           ->        pg_catalog.pg_class c
           ->        LEFT JOIN pg_catalog.pg_description d
           ->               ON ( c.oid = d.objoid
           ->                    AND d.objsubid = 0 )
           -> WHERE  c.relnamespace = n.oid
           ->        AND n.nspname LIKE 'test'
           ->        AND ( false
           ->               OR ( c.relkind IN ( 'r', 'p' )
           ->                    AND n.nspname !~ '^pg_'
           ->                    AND n.nspname <> 'information_schema' )
           ->               OR ( c.relkind = 'v'
           ->                    AND n.nspname <> 'pg_catalog'
           ->                    AND n.nspname <> 'information_schema' )
           ->               OR ( c.relkind = 'm' )
           ->               OR ( c.relkind = 'f' ) )
           -> ORDER  BY table_type,
           ->           table_schem,
           ->           table_name
           -> ;
+-----------+-------------+------------+------------+---------+
| table_cat | table_schem | table_name | table_type | remarks |
+-----------+-------------+------------+------------+---------+
| NULL      | test        | blah       | TABLE      | NULL    |
| NULL      | test        | kv         | TABLE      | NULL    |
+-----------+-------------+------------+------------+---------+
(2 rows)

Time: 5.123332ms
```

**Comment by TedBear42** [comment] 2017-12-02 22:38
Jorden,

Thanks for the reply.  

I am way from the cluster at the minute.  I'll build a new one on Monday.  But this was what I was seeing.

**Through the Cockroach cli Sql**
1. If I was user "userf" and I ran this query outside the db1 database I didn't see the tables through the cockroach cli sql.
2. If I was user "userf" and I ran this query inside the db1 database I did see the tables through the cockroach cli sql.
3. When I ran the query as root it would always work from the cockroachDB cli sql

**When I ran through Presto**
1. With root and userf, I could see the system tables but not the db1 tables.
2. I could see all databases that I had rights too with root and userf.
3. I tried using "use db1" in presto but it seem to make no change.

**Next Steps for Me**
On Monday I will set up test environment on my local using docker containers for presto and cockroachDB.  I'll document the full steps taken and if the problem comes up again I'll post the complete path to recreating the problem here.

**Use Case**
In case your interested.  I'm looking to use CockRoachDB as a nested store that provides speed layer in front of a object store or and HDFS and use Presto to give me a seamless experience across both systems.  If this sounds crazy please let me know.  

Thanks again
Ted Malaska

**Comment by TedBear42** [comment] 2017-12-07 02:12
I'm making progress.  I got the container setup to work and I can see my created tables.  However, I have hit a new error when trying to execute a "select * from bar;" statement.

Have you ever seen this?  I will do more research after I land, I'm mid flight between Singapore and the US.

presto:foo> select * from bar;

Query 20171207_020723_00018_eusij, FAILED, 1 node
Splits: 2 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20171207_020723_00018_eusij failed: org.postgresql.util.PSQLException: ERROR: syntax error at or near "read"
  Detail: source SQL:
SET SESSION CHARACTERISTICS AS TRANSACTION READ ONLY
                                           ^
  Hint: try \h SET SESSION

**Comment by jordanlewis** [comment] 2017-12-07 03:11
CockroachDB doesn't support read-only transactions yet, so this won't work. See #16033.

**Comment by TedBear42** [comment] 2017-12-07 20:12
Do you know of a work around?  I'm going to see if I can get presto to not call this command or change the transaction types.

**Comment by TedBear42** [comment] 2017-12-07 20:18
Looks like this might be the source of the problem from presto.

https://github.com/prestodb/presto/blob/master/presto-base-jdbc/src/main/java/com/facebook/presto/plugin/jdbc/BaseJdbcClient.java#L258

And doesn't look like there is a way to avoid this line with a config.

**Comment by jordanlewis** [comment] 2017-12-07 20:34
There's no workaround for this unfortunately.

It's a fairly simple issue to fix, though, as it turns out. There's a PR open: #20547

**Comment by danjallen** [comment] 2018-01-11 04:14
Ted,
Where you able to get Presto to see the tables and query them after that PR was merged?  I was curious about your use case and wanted to follow up to see if you had any luck.
Thanks!

**Comment by TedBear42** [comment] 2018-01-11 04:16
I haven’t tried it yet.  They is a bunch of work at the moment with the
overwatch league thing.  I should have time to try it next month

**Comment by knz** [comment] 2018-04-24 12:05
This should have been addressed in CockroachDB 2.0/2.0.1.

**Comment by knz** [comment] 2018-05-04 20:53
@TedBear42 we have made significant improvements in this area in CockroachDB 2.0. We'd be curious to know your experience with Presto with the new CockroachDB release (currently 2.0.1). 

Meanwhile, we're keeping an eye on compatibility in general. If you don't observe complete success now, we're likely to improve the situation further over time.

**Comment by jordanlewis** [comment] 2019-04-10 03:22
Closing due to inactivity.

**Closed by jordanlewis** 2019-04-10 03:22 UTC
Labels: A-sql-pgcompat, C-question, O-community, meta-issue
