### ISSUE TITLE
circleci: docker flakiness

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4894] opened 2016-03-06 01:11 UTC
Every now and then (but often enough to fail a significant amount of builds due to the sheer volume of iterations this bug gets), Gossip doesn't join up:
```
I160306 00:51:43.699152 cli/start.go:129  [build] alpha.v1-676-g3325b63 @ 2016/03/06 00:37:29 (go1.6)
I160306 00:51:43.701589 server/context.go:223  1 storage engine initialized
I160306 00:51:43.701841 cli/start.go:143  starting cockroach node
E160306 00:51:43.896722 gossip/gossip.go:733  invalid bootstrap address: &{typ:tcp addr:roach0.local:26257 exhausted:false}, lookup roach0.local: no such host
I160306 00:51:43.900384 storage/engine/rocksdb.go:106  opening rocksdb instance at "/data2.0"
I160306 00:51:43.909866 server/node.go:353  store store=0:0 ([]=/data2.0) not bootstrapped
I160306 00:51:43.910160 storage/stores.go:289  read 0 node addresses from persistent storage
I160306 00:51:43.911156 server/node.go:486  connecting to gossip network to verify cluster ID...
```

Note `E160306 00:51:43.896722 gossip/gossip.go:733  invalid bootstrap address: &{typ:tcp addr:roach0.local:26257 exhausted:false}, lookup roach0.local: no such host` which suggests that there's maybe a DNS issue with `docker-spy` and a subsequent failure in Gossip to retry in a speedy manner.

Repros locally, for example

```
while [ $? -eq 0 ]; do rm -rf ./acceptance/Test*; make acceptance TESTS=GossipPeerings TESTFLAGS='-v -l .'; done
```

**Comment by petermattis** [comment] 2016-03-06 01:18
We retry gossip bootstrapping every second until it succeeds. So the DNS issue must be persistent and you must be seeing that error in the log files every second or so. Let me try to repro.

**Comment by tschottdorf** [comment] 2016-03-06 01:22
That was the whole log file, and it tries for 15s. Possible the retry loop gets stuck somewhere. If you're trying to repro this now, I suggest you run it without the 15s timeout so you can `killall -3` the containers (or take a look at the stacktraces in another way).

**Comment by tschottdorf** [comment] 2016-03-06 05:54
Unfortunately still happening, though the retry every second is there:

https://circle-artifacts.com/gh/cockroachdb/cockroach/13904/artifacts/0/tmp/circle-artifacts.MzLlVqN/acceptance/TestDockerPHP/roach1.local/stderr.2016-03-06T04_51_55Z.log

I think we ought to be looking at what's going on with the docker-spy container. We should start logging its output as well, at least for failed tests.

**Comment by petermattis** [comment] 2016-03-06 14:15
Gah! Ok, I'll take a closer look at this tonight.

**Comment by tschottdorf** [comment] 2016-03-06 15:33
Reopening since probably accidentally closed.

**Comment by petermattis** [comment] 2016-03-06 20:34
Oops, yes, didn't mean to close. Btw, I'm unable to reproduce failures locally. Any additional magic to doing so besides the shell invocation above?

**Comment by tschottdorf** [comment] 2016-03-07 01:25
No, it did happen every now and then with the shell script above, but seems to be more prominent on CI (as usual).

**Comment by petermattis** [comment] 2016-03-07 14:46
@bdarnell I thought you said #4927 didn't fix this.

**Comment by tschottdorf** [comment] 2016-03-07 14:46
github isn't smart enough for "doesn't seem to fix #...".

**Comment by bdarnell** [comment] 2016-03-07 14:49
Oops, I thought github only matched things like that at the beginning of a line.

**Comment by petermattis** [comment] 2016-03-07 16:42
Ok, the new flakiness is happening for me all the time locally and it looks like DNS badness causing failure to connect to the gossip network. When a failure occurs I see errors like:

```
I160307 16:36:19.907581 /go/src/google.golang.org/grpc/clientconn.go:318  Failed to dial roach0:26257: grpc: timed out trying to connect; please retry.
```

I instrumented gossip to first resolve the address which shows:

```
I160307 16:36:16.901478 gossip/gossip.go:951  starting client to roach0:26257 (92.242.140.21:26257)
```

But that IP address is incorrect. I can `docker exec` into the container and `ping roach0` without problem:

```
root@roach2:/go# ping roach0
PING roach0 (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.071 ms
```

The `172.18.0.2` is correct and matches up with some additional instrumentation I added to `localcluster.go`. So where is the `92.242.140.21` address coming from?

**Comment by bdarnell** [comment] 2016-03-07 16:50
```
$ host 92.242.140.21
21.140.242.92.in-addr.arpa domain name pointer unallocated.barefruit.co.uk.
```

`barefruit.co.uk` is one of those shady companies that does advertising on DNS errors. So maybe it's trying to go out to external DNS before resolving it within the docker bridge network?

**Comment by petermattis** [comment] 2016-03-07 16:55
Hmm, specifying `GODEBUG=netdns=cgo` seems to fix the problem:

```
diff --git a/acceptance/cluster/localcluster.go b/acceptance/cluster/localcluster.go
index 259e2bd..813578b 100644
--- a/acceptance/cluster/localcluster.go
+++ b/acceptance/cluster/localcluster.go
@@ -363,6 +363,7 @@ func (l *LocalCluster) createRoach(node *testNode, vols *Container, cmd ...strin
                                defaultTCP: {},
                        },
                        Entrypoint: entrypoint,
+                       Env:        []string{"GODEBUG=netdns=cgo"},
                        Cmd:        cmd,
                        Labels: map[string]string{
                                // Allow for `docker ps --filter label=Hostname=roach0` or `--filter label=Roach`.
```

**Closed** 2016-03-07 18:44 UTC
Labels: bug
