### ISSUE TITLE
release: v19.2.2

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#43058] opened 2019-12-09 20:15 UTC
Candidate SHA: 3cbd05602d4aeaebbccea18d66ad0fdf8db482a5
Deployment status: [v19.2.1](http://david-release-v1921-53eef08-0001.roachprod.crdb.io:26258/) vs [v19.2.2](http://david-release-v1922-3cbd0560-0001.roachprod.crdb.io:26258/)
Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite
 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: `2019-12-10`
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-announce of SHA.
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkbinaries)
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [ ] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RoachtestFailureSignoff)
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: `WIP fill in date: usually Monday WIP`
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [x] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [x] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [ ] Announce version to the [registration cluster](https://github.com/cockroachlabs/production#publishing-a-new-release-version)
  - [ ] Upgrade the registration cluster (reg runs latest stable version)
 
- [x] Update docs
- [x] External communications for release

**Comment by dt** [comment] 2019-12-10 14:31
Roachtest failure investigations and sing-offs: 

- [ ] cdc/bank
- [ ] jepsen/bank-multitable/majority-ring
- [ ] sqlsmith/setup=empty/setting=no-ddl
- [ ] sqlsmith/setup=rand-tables/setting=no-ddl
- [ ] hibernate
- [ ] splits/load/uniform/nodes=3
- [ ] sqlsmith/setup=rand-tables/setting=default

**Comment by tbg** [comment] 2019-12-10 14:49
I'll take a look at splits/load/uniform/nodes=3. I think it started failing after https://github.com/cockroachdb/cockroach/pull/42833 though I wouldn't know why that would be connected.

**Comment by tbg** [comment] 2019-12-10 14:52
The jepsen failure has

> 00:38:02 jepsen.go:205: passed, grabbing minimal logs

And the test seems to have failed because the dead node detection threw up:

```
00:38:08 test.go:284: test failure: 	cluster.go:1258,context.go:135,cluster.go:1247,test_runner.go:737: dead node detection: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod monitor teamcity-1634692-1575931985-39-n6cpu4 --oneshot --ignore-empty-nodes: exit status 1 2: error: exit status 255
		6: skipped
		1: skipped
		5: skipped
		3: skipped
		4: skipped
		Error:  2: error: exit status 255
```

I'm not sure what exactly went wrong here, but it doesn't look like jepsen failed.

**Comment by tbg** [comment] 2019-12-10 15:38
I confirmed that the splits failure is resolved by reverting #42833. Won't be too hard to find out why (hope springs eternal).

**Comment by dt** [comment] 2019-12-10 16:09
Restarting qualification on top of #43072

**Comment by tbg** [comment] 2019-12-10 16:44
The splits failure is fixed by https://github.com/cockroachdb/cockroach/pull/43078. Between backporting that and reverting the original, backporting is the better option.

**Comment by dt** [comment] 2019-12-12 03:58
Okay, with the new SHA, our nightly failures are now:

- [ ] [cdc/bank](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId2129317789298891322 "Show related test details") `TransactionRetryWithProtoRefreshError`
- [ ] [kv/contention/nodes=4](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId-9215103075698950051 "Show related test details") `spent 70.689655% of time below target of 100.000000 txn/s, wanted no more than 5.000000%`

SQL:
- [ ] [cancel/tpcc/distsql/w=10,nodes=3](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId-9001178873075005748 "Show related test details") `query completed before it could be canceled`
- [ ] [sqlsmith/setup=rand-tables/setting=default](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId-2020432820602765727 "Show related test details") `pq: at or near "null": syntax error: unimplemented: this syntax`
- [ ] [sqlsmith/setup=rand-tables/setting=no-mutations](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId3050041756343658206 "Show related test details") `at or near ",": syntax error: unimplemented: this syntax`
- [ ] [sqlsmith/setup=tpch-sf1/setting=default](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId6328311146274652684 "Show related test details") `query timed out, but did not cancel execution:`
- [ ] [hibernate](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId-3931757827174594180 "Show related test details")
- [ ] [pgjdbc](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637507&buildTypeId=Cockroach_Nightlies_NightlySuite#testNameId-5749868698903386485 "Show related test details") 
- [ ] [tpccbench/nodes=9/cpu=4/chaos/partition](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637505&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly#testNameId7647859149799979980) `test timed out (10h0m0s)`
- [ ]  [tpccbench/nodes=9/cpu=4/multi-region](https://teamcity.cockroachdb.com/viewLog.html?buildId=1637505&tab=buildResultsDiv&buildTypeId=Cockroach_Nightlies_WorkloadNightly#testNameId-7667002519850730298) `test timed out (10h0m0s)`

**Comment by irfansharif** [comment] 2019-12-14 18:55
`kv/contention` is not a new failure: https://github.com/cockroachdb/cockroach/issues/40786

**Comment by andreimatei** [comment] 2019-12-16 18:25
ticked off cdc/bank. It's been firing for a month and a half (https://github.com/cockroachdb/cockroach/issues/42773 and https://github.com/cockroachdb/cockroach/issues/41177).
But I'll look into what's going on.

**Comment by jseldess** [comment] 2020-01-02 15:33
@dt, can this be closed?

**Closed** 2020-01-23 18:20 UTC
