### ISSUE TITLE
circleci: failed tests: TestParallel 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#7705] opened 2016-07-08 18:17 UTC
The following test appears to have failed:

[#20030](https://circleci.com/gh/cockroachdb/cockroach/20030):

```
--- progress: partestdata/subquery_retry/txn: 1 statements/queries
--- progress: partestdata/subquery_retry/txn: 1 statements/queries
partestdata/subquery_retry/main:5: running final
I160708 18:14:59.805564 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
1 parallel tests passed
--- FAIL: TestParallel (6.43s)
	logic_test.go:1216: partestdata/subquery_retry/txn:6: expected success, but found
		pq: context deadline exceeded
	parallel_test.go:104: partestdata/subquery_retry/txn:6: error in statement, skipping to next file
=== RUN   TestPGWire
I160708 18:14:59.853422 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
W160708 18:14:59.856976 server/server.go:111  running in insecure mode, this is strongly discouraged. See --insecure.
W160708 18:14:59.858002 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
W160708 18:14:59.874956 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
I160708 18:14:59.877219 server/node.go:399  store store=0:0 ([]=) not bootstrapped
I160708 18:14:59.900483 storage/replica.go:1850  applying command with forced error: storage/replica.go:1771: no-op on empty Raft entry
--
I160708 18:16:15.500684 storage/replica_command.go:1596  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 407779h31m19.892193471s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-07-08 18:16:15.500122383 +0000 UTC]
I160708 18:16:15.503851 stopper.go:355  draining; tasks left:
1      storage/intent_resolver.go:345
I160708 18:16:15.512888 storage/engine/rocksdb.go:333  closing in-memory rocksdb instance
--- PASS: TestReacquireLeaseOnRestart (1.51s)
FAIL
FAIL	github.com/cockroachdb/cockroach/sql	234.854s
I160708 18:12:08.526693 rand.go:76  Random seed: 5954998720571842014
=== RUN   TestProcessExpression
--- PASS: TestProcessExpression (0.03s)
=== RUN   TestOrderedSync
--- PASS: TestOrderedSync (0.00s)
=== RUN   TestJoinReader
I160708 18:12:08.566727 storage/engine/rocksdb.go:289  opening in memory rocksdb instance
W160708 18:12:08.588955 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node
I160708 18:12:08.627491 server/node.go:399  store store=0:0 ([]=) not bootstrapped
W160708 18:12:08.630788 gossip/gossip.go:900  not connected to cluster; use --join to specify a connected node

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-07-10 15:35
Duplicate of #7654.

**Closed by petermattis** 2016-07-10 15:35 UTC
Labels: Robot, test-failure
