### ISSUE TITLE
Reverting schema change job hangs due to command size too large

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#83047] opened 2022-06-18 08:09 UTC
**Describe the problem**

I was running schema change command alter column float to int, cockroachdb said I required to set `enable_experimental_alter_column_type_general`

```
ERROR: ALTER COLUMN TYPE from float to int is only supported experimentally
SQLSTATE: 0A000
HINT: See: https://go.crdb.dev/issue-v/49329/v22.1
--
you can enable alter column type general support by running `SET enable_experimental_alter_column_type_general = true`
```

I run that command `SET enable_experimental_alter_column_type_general = true` and then run `alter table movies alter column word_common_index type int;`

CRDB shell hang for really long (about 5 minutes - table have only about 2000 rows), I press Ctrl+C (and then Ctrl+C again to exit shell).

After I reconnect to cockroachdb cli and try to run alter table command, it said:

```
ERROR: unimplemented: table movies is currently undergoing a schema change
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://go.crdb.dev/issue-v/47137/v22.1
```

I'm like - okay, I'm gonna wait. But here the thing, after another 10mins, I realize something is wrong: in cockroachdb dashboard `jobs` tab, there is no `alter table` command I just run. But If I try run `alter table` command again, cockroachdb report it going under schema change.

![image](https://user-images.githubusercontent.com/7130705/174428680-1c99601a-8d41-4d22-b328-d753615c4e35.png)
### (in picture above, my command alter table float to int did not appear).

In desperate, I try to stop cluster and restart - but the problem is still there.

**Expected behavior**
What should I do in this case? I was trying to revert schema change, drop column and recreate seem faster, but now schema in flux state, not sure what I should do.

**Environment:**
 - CockroachDB version: `CockroachDB CCL v22.1.0 (x86_64-pc-linux-gnu, built 2022/05/23 16:27:47, go1.17.6)`
 - Server OS: Ubuntu 22.04
 - Client app: `cockroach sql`

Jira issue: CRDB-16818

gz#12893

**Comment by Xiang-Gu** [comment] 2022-06-18 11:38
Hi, thank you for filing an issue and we're sorry you experienced an issue. @cockroachdb/sql-experience 

I tried to alter column type on a table with 2000 rows and it succeeded instantly so something is wrong.

First of all, can you tell us what exactly is the issue you're experiencing? Is it that the `ALTER COLUMN TYPE` hangs forever and it prevents you from doing any other alter table command on the table?

**Comment by kocoten1992** [comment] 2022-06-18 13:24
> Is it that the ALTER COLUMN TYPE hangs forever and it prevents you from doing any other alter table command on the table?

Yes, it is correct.

And I do see it in manually running that query:

```
771576610819276801 | SCHEMA CHANGE |  ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.movies ALTER COLUMN word_common_index SET DATA TYPE INT8                                                 |           | reverting | NULL
```

When I try cancel it, it said:

```
root@:26257/website> cancel job 771576610819276801;
ERROR: job 771576610819276801: job with status reverting cannot be requested to be canceled
```

I run 2 of total queries for schema change - the last one was created by cockroachdb I think, not sure if it related:

```
  771576610819276801 | SCHEMA CHANGE |  ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.movies ALTER COLUMN word_common_index SET DATA TYPE INT8                                                 |           | reverting | NULL
  771579392347537409 | SCHEMA CHANGE |  ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.episodes ALTER COLUMN word_common_index SET DATA TYPE INT8                                               |           | succeeded | NULL
  771579394126807041 | SCHEMA CHANGE | CLEANUP JOB for ' ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.episodes ALTER COLUMN word_common_index SET DATA TYPE INT8'                             |           | succeeded | NULL
```

One query have `reverting` state for a few hours already. Also, none of those query above show up on dashboard.

**Comment by kocoten1992** [comment] 2022-06-18 15:59
I saw this in log:

```
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168  SCHEMA CHANGE job 771576610819276801: stepping through state reverting with error: command is too large: 82763050 bytes (max: 67108864)
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +(1)
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | (opaque error wrapper)
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | type name: github.com/cockroachdb/errors/withstack/*withstack.withStack
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | reportable 0:
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).evalAndPropose
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_raft.go:238
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeWriteBatch
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_write.go:167
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).executeBatchWithConcurrencyRetries
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:478
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).sendWithoutRangeID
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:174
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Replica).Send
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/replica_send.go:100
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Store).Send
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/store_send.go:197
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvserver.(*Stores).Send
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvserver/pkg/kv/kvserver/stores.go:191
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/server/node.go:1006
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunTaskWithErr
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:344
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/server/node.go:989
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/server.(*Node).Batch
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/server/node.go:1058
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/rpc.internalClientAdapter.Batch
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/rpc/pkg/rpc/context.go:609
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).sendBatch
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:209
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*grpcTransport).SendNext
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/transport.go:191
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendToReplicas
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:2062
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatch
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1608
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord.(*DistSender).sendPartialBatchAsync.func1
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/kv/kvclient/kvcoord/dist_sender.go:1481
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTaskEx.func2
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:494
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  | runtime.goexit
I220618 07:35:02.020383 6502 jobs/registry.go:1134 ⋮ [n1] 168 +  |      GOROOT/src/runtime/asm_amd64.s:1581
```

**Comment by Xiang-Gu** [comment] 2022-06-18 17:24
```
771576610819276801 | SCHEMA CHANGE |  ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.movies ALTER COLUMN word_common_index SET DATA TYPE INT8                                                 |           | reverting | NULL
771579392347537409 | SCHEMA CHANGE |  ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.episodes ALTER COLUMN word_common_index SET DATA TYPE INT8                                               |           | succeeded | NULL
771579394126807041 | SCHEMA CHANGE | CLEANUP JOB for ' ALTER COLUMN word_common_index SET DATA TYPE INT8; ALTER TABLE website.public.episodes ALTER COLUMN word_common_index SET DATA TYPE INT8'                             |           | succeeded | NULL
```
It looks like another `ALTER COLUMN TYPE` succeeded without errors. Is the `movies` table in any sense "special" from other tables (e.g. a lot of rows, or a lot of columns, gigantic keys)?

Thanks for providing the error log. The error message seems to suggest it's related to the replica raft protocol, which is handled by the kv team. I will need to get in touch with them to better assist you on Monday.

In the meantime, as a workaround, can you create a new table and work on the new one for now?

**Comment by kocoten1992** [comment] 2022-06-19 17:38
Hi @Xiang-Gu, I've recompile cockroachdb binary with comment out these lines:

https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_raft.go#L237-L241

It does work for my case, however I think we should strongly push forward to kv team as you suggested (it create bad user experience).

The `movies` table is special, it contains `subtitle` (which is a text field with maybe go up to 200kb), with that many rows, no wonder it exceeding `64 MiB`.

I guess one work around would be allow user change schema max limit command size ? (I cannot find any setting relate to that on https://www.cockroachlabs.com/docs/v22.1/cluster-settings).

**Comment by Xiang-Gu** [comment] 2022-06-19 18:27
> It does work for my case,....

Do you mean commenting out that block of code allows you to succeed the `ALTER COLUMN TYPE` on the `movies` table? If so, great, but we will still talk to the kv team for me to better understand why we have such a limit and why it causes the issue -- after all, a TEXT column of size about 200kb per row in a 2000 rows table isn't that uncommon.

> I guess one work around would be allow user change schema max limit command size ?

I found `kv.raft.command.max_size`, which defaults to 64 MiB, and maybe you can try something like 
```
SET CLUSTER SETTING kv.raft.command.max_size = '128MiB'
```

> Do we have an api for that - like resume job 771576610819276801 now ?

Can't you just do 
```
resume job 771576610819276801
```
?

**Comment by kocoten1992** [comment] 2022-06-19 18:42
Pardon me if I said anything wrong, I don't know how internal cockroachdb work..

Do we have exponential backoff if a job fail to run? At the time I was changing `SET CLUSTER SETTING kv.raft.command.max_size = '128MiB'`, maybe it already +6h or something - I couldn't find error `command is too large` anymore - only learn about `select job_id, job_type, description, statement, status, running_status from [show jobs] order by created;` after chatting with you - sorry about that.

Does `resume job 771576610819276801` trigger it immediately, I was running that command but I remember it not trigger immediately - sorry if this is wrong.

Have a nice weekend!

**Comment by Xiang-Gu** [comment] 2022-06-19 19:11
No worries, we are happy to be able to help!

> Do we have exponential backoff if a job fail to run?

Yes, "CockroachDB automatically retries jobs that fail due to [retry errors](https://www.cockroachlabs.com/docs/v22.1/transaction-retry-error-reference) or job coordination failures, with [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff)"

> Does resume job 771576610819276801 trigger it immediately

yes. In practice, it might take a short while for the underlying job framework to be notified before resuming it.

Last but not least, can you confirm that an accurate summary of your issue is:
A customer has a table `t` of about 2000 rows. `t`, among others, notably has a FLOAT column `c1` and a TEXT column `c2`. `c2` stores somewhat lengthy text of about 200 KB per row. 

The customer attempted 
```ALTER TABLE t ALTER COLUMN c1 TYPE INT```
but it hangs; after about 5 minutes, the customer pressed "CTRL+c" once, and then twice to exit the sql shell.

After reconnecting to the cluster, the customer sees the job for the above commend hangs in reverting state. Logs revealed that it failed in the kv layer bc the "command size is too large".

The user commented out the block of code that checks for that error and was able to finish the `ALTER COLUMN TYPE` command.

**Comment by kocoten1992** [comment] 2022-06-19 19:39
Yes, that is correct.

Also I misread you before, `kv.raft.command.max_size` <- I never change this, not found that in document setting.

One last question, does `resume job` also update `next_run` on job? I remember it does not, that why I've to wait almost 24h for `reverting` job to work again.

**Comment by Xiang-Gu** [comment] 2022-06-19 20:14
right, I found `kv.raft.command.max_size` in the code, not from the doc.

hold on, I'm a bit confused. What actions did you take to resolve the issue of a job hanging in revert status? 

When you say it worked for you after commenting out the block of code, did you then compile CRDB, re-create your database, re-populate your tables, and then `ALTER COLUMN TYPE`? You didn't continue to work on the old cluster with a hanging reverting job, right?

Also, you said you waited for almost 24h for the `reverting` job to work again. Do you mean that reverting job finally succeeded and no longer hangs in `reverting`?

**Comment by kocoten1992** [comment] 2022-06-19 20:34
My bad, I did not explain enough, the first part is exactly as you describe, I'll just explain the second part - what I did to debug and make it run again, here is the exact event order:
1. After chatting with you (at the very first answer), I dig into logging and `crdb_internal.jobs` and saw `command is too large`
2. I go to document setting and find exactly 5 settings that have default value of `64 MiB`, I read and none of that apply to my case `command is too large`, but I change it to `256 MiB` anyway and hope for a miracle.
3. Of course no miracle happen, but at the same time error log do not seem to appear anymore (I do not realize at this time - it not because of my setting change but rather than exponential backoff already kick in).
4. I dig into `crdb_internal.jobs` again, and realize there is a `next_run` column (you don't show me this column), I try to update `next_run` but not even root can do that, `resume job` cannot update that either.
5. I don't believe 5 settings I have change would have any effect.
6. I recompile cockroach binary and comment out https://github.com/cockroachdb/cockroach/blob/master/pkg/kv/kvserver/replica_raft.go#L237-L241
7. I want that job `771576610819276801` to rerun immediately to test if my change work, but I cannot, and wait for 24h.
8. 24h pass, that job succeed, then I run command `ALTER COLUMN TYPE`, also succeed.
9. I swap back cockroach binary and tell you.

**Comment by Xiang-Gu** [comment] 2022-06-19 21:03
Thanks for writing this up!

1. After step 6, how did you let the node run the newly compiled binary and be able to keep working on the pre-recompile cluster state? That is, what did you do to make sure that step 7 is run with the new binary?
2. In step 8, after you commented out the code, how long does it take to finish the `ALTER COLUMN TYPE`? Originally, you said you waited for about 5 mins before you CTRL + c twice.

**Comment by kocoten1992** [comment] 2022-06-19 21:18
> Thanks for writing this up!
> 
> 1. After step 6, how did you let the node run the newly compiled binary and be able to keep working on the pre-recompile cluster state? That is, what did you do to make sure that step 7 is run with the new binary?

Good question, I've wrote a script that gradually update cockroachdb binary (service down - replace binary - service up) once at a time. But reality is: this cluster I only have one machine node, so there was downtime about 30s (if I have 3 nodes hopefully would be zero).

> 2. In step 8, after you commented out the code, how long does it take to finish the `ALTER COLUMN TYPE`? Originally, you said you waited for about 5 mins before you CTRL + c twice.

I look at `io` and `cpu` and `network`, if something is happening, I'll let it run forever, but if everything is as usual, I know something is wrong and will cancel the command, it took `33s` the second time.

**Comment by Xiang-Gu** [comment] 2022-06-20 16:46
Thank you for providing the above information!

In order for us to properly provide a fix to close this issue, I am now trying to reproduce the issue you ran into. Any chance you are using some public and free dataset that I can also use (most importantly, the `website.public.movies` table)?

**Comment by kocoten1992** [comment] 2022-06-20 19:12
@Xiang-Gu I extract from backup and try running in my local machine, same issue, where could I send you the database? https://support.cockroachlabs.com/hc/en-us good?

**Comment by Xiang-Gu** [comment] 2022-06-20 21:00
We have a secure data transfer platform and you can send it to me via this URL: https://upload.cockroachlabs.com/u/xiang

**Comment by Xiang-Gu** [comment] 2022-06-20 21:06
Can you send me the ticket link/number so I can take a look right now? 

The company process is that technical support engineers will first view, triage, and resolve the ticket, and escalate to the engineers if they need further assistance. There hence might be a delay before I or another engineer actually got to see your ticket.

**Comment by kocoten1992** [comment] 2022-06-20 21:07
Huh, you just delete a message about upload.cockroachdb right?

I just sent one to you there (upload.cockroachlabs.com), no worry about creds, it properly configurated

**Comment by Xiang-Gu** [comment] 2022-06-20 21:14
Got it, taking a look at it now.

**Comment by Xiang-Gu** [comment] 2022-06-21 10:00
The follow-ups are to answer the following two questions:

1. Why did ALTER COLUMN TYPE hang in the first place? Or, is it just taking a long time? Note that this is a table with only ~1200 rows but each row is quite wide (~460 KB per row).
2. Why did we hit the kv.raft.command.max_size limit when reverting?

Also, this issue exhibits some of the limitations of `ALTER COLUMN TYPE` being an experimental feature, as tracked in https://github.com/cockroachdb/cockroach/issues/83047

**Comment by ajwerner** [comment] 2022-06-21 14:45
I think the core problem here is that the column backfiller does not take into account row-size when building its batches: it just uses the number of rows. Clearly here you have rows bigger than 128KiB on average. Your 24h waiting is about exponential backoff in the jobs framework. We will be getting rid of the column backfiller, but this is obviously a bad experience. To fix it, we should limit the built batch based on size as well as on row count.

**Comment by Xiang-Gu** [comment] 2022-06-22 17:21
Since we've figured out the root cause of this issue and the user is unblocked, I'm closing it in favor of #83199

**Closed by Xiang-Gu** 2022-06-22 17:21 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-schema
