### ISSUE TITLE
stability: /_status/vars wedges.

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#20118] opened 2017-11-17 12:56 UTC
At 20171117-11:40UTC, multiple nodes across multiple clusters were reported as dead.
This turned out to be prometheus timing out trying to fetch `/_status/vars`.

Persistently-wedged clusters are all running 1.2-alpha. Others (1.1 stable or 1.1-head) get failing scrapes, but work out eventually.

Active goroutines on some nodes (eg: `cockroach-adriatic-0003` and `cockroach-cyan-0001`) show a wedged `handleVars` goroutine. Since this holds a lock on metric data structures, this wedges a lot of other goroutines:

```
1: IO wait [12 minutes] [Created by http.(*Server).Serve @ server.go:2720]
    poll       netpoll.go:173             runtime_pollWait(#3801, 0x77, 0)
    poll       fd_poll_runtime.go:85      (*pollDesc).wait(#1793, 0x77, 0xffffffffffffff00, #65, #59)
    poll       fd_poll_runtime.go:94      (*pollDesc).waitWrite(#1793, #3465, 0x2d6e, 0x6d51)
    poll       fd_unix.go:226             (*FD).Write(#1792, #3464, 0x401d, 0x8000, 0, 0, 0)
    net        fd_unix.go:220             (*netFD).Write(#1792, #3464, 0x401d, 0x8000, 0, 0, #3211)
    net        net.go:188                 (*conn).Write(#1498, #3464, 0x401d, 0x8000, 0, 0, 0)
    cmux       <autogenerated>:1          (*MuxConn).Write(#2849, #3464, 0x401d, 0x8000, 0x8000, #3760, 0x8000)
    tls        conn.go:832                (*Conn).write(#2180, #3464, 0x401d, 0x8000, #2103, 0x1, 0)
    tls        conn.go:909                (*Conn).writeRecordLocked(#2180, #51, #3724, 0xf013, 0xb434, 0, 0, 0)
    tls        conn.go:1068               (*Conn).Write(#2180, #3723, 0xf013, 0xf013, 0, 0, 0)
    http       server.go:3217             checkConnErrorWriter.Write(#2850, #3723, 0xf013, 0xf013, 0xc0, 0x6, 0)
    bufio      bufio.go:599               (*Writer).Write(#2098, #3723, 0xf804, 0xf013, #2126, 0x1, 0x1)
    http       server.go:364              (*chunkWriter).Write(#2613, #3722, 0xf804, 0xf804, #1981, #2127, #2128)
    bufio      bufio.go:599               (*Writer).Write(#2724, #3722, 0xffff, 0xf804, 0x4, 0, 0)
    http       server.go:1500             (*response).write(#2612, 0xffff, #3721, 0xffff, 0xffff, 0, 0, 0x4, 0, 0)
    http       server.go:1470             (*response).Write(#2612, #3721, 0xffff, 0xffff, 0x4, 0, 0)
    flate      huffman_bit_writer.go:144  (*huffmanBitWriter).write(#2376, #3721, 0xffff, 0xffff)
    flate      huffman_bit_writer.go:193  (*huffmanBitWriter).writeBytes(#2376, #3721, 0xffff, 0xffff)
    flate      deflate.go:289             (*compressor).writeStoredBlock(#3710, #3721, 0xffff, 0xffff, 0x5, 0x5)
    flate      deflate.go:528             (*compressor).store(#3710)
    flate      deflate.go:551             (*compressor).write(#3710, #3369, 0x14, 0xdb, 0xe0, #126, #3252)
    flate      deflate.go:709             (*Writer).Write(#3710, #3368, 0x14, 0xe0, 0xe0, #126, 0x6b3e32)
    gzip       gzip.go:196                (*Writer).Write(#2681, #3368, 0x14, 0xe0, #2130, #16, #3508)
    server     server.go:1430             (*gzipResponseWriter).Write(#2681, #3368, 0x14, 0xe0, #2129, 0x5ea50f, 0x10)
    fmt        print.go:216               Fprint(#10, #2681, #2130, 0x1, 0x1, 0x14, 0x7, 0x14)
    expfmt     text_create.go:209         writeSample(#3019, 0x14, #2241, #32, 0x2, #3253, 0xc, #3863, #10, #2681, ...)
    expfmt     text_create.go:144         MetricFamilyToText(#10, #2681, #1502, 0xc7, 0, 0)
    metric     prometheus_exporter.go:90  (*PrometheusExporter).PrintAsText(#263, #10, #2681, #19, #34)
    status     recorder.go:234            (*MetricsRecorder).PrintAsText(#260, #10, #2681, 0, 0)
    server     status.go:879              (*statusServer).handleVars(#254, #1, #2681, #1015)
    server     server.go:1116             handleVars)-fm(#1, #2681, #1015)
    http       server.go:1918             HandlerFunc.ServeHTTP(#1363, #1, #2681, #1015)
    http       server.go:2254             (*ServeMux).ServeHTTP(#5, #1, #2681, #1015)
    server     server.go:1399             (*Server).ServeHTTP(#4, #2, #2612, #1015)
    http       server.go:2619             serverHandler.ServeHTTP(#6, #2, #2612, #1015)
    http       server.go:1801             (*conn).serve(#2850, #3, #2097)
```

A quick sample of FD counts on various nodes show:
* `adriatic-3`: 70K open, 34K rocksdb, 32K tcp
* `omega-3`: 102K open, 60K rocksdb, 38K tcp
* `cyan-1`: 430K open, 360K rocksdb, 54K tcp

**Comment by a-robinson** [comment] 2017-11-17 13:56
On cyan, there are 690 goroutines blocked trying to acquire the mutex in `(*MetricsRecorder).PrintAsText`. The goroutine holding the lock is blocked in:

```
1 @ 0x66905c 0x66419a 0x663797 0x6d588e 0x6d597d 0x6d7274 0x7efc32 0x80243d 0x104040a 0x8c1607 0x8c1b20 0x8c2a3b 0x975f06 0x74a22f 0x96996b 0x74a22f 0x96f650 0x96f424 0x8fbf41 0x8fc1b5 0x8f8449 0x8f961c 0x8f9820 0x8faecb 0x906b7d 0x17ca2eb 0x70ac25 0xda714c 0xda6bcc 0xda536f 0xda9f36 0x143c2b6
#	0x663796	internal/poll.runtime_pollWait+0x56									/usr/local/go/src/runtime/netpoll.go:173
#	0x6d588d	internal/poll.(*pollDesc).wait+0xad									/usr/local/go/src/internal/poll/fd_poll_runtime.go:85
#	0x6d597c	internal/poll.(*pollDesc).waitWrite+0x3c								/usr/local/go/src/internal/poll/fd_poll_runtime.go:94
#	0x6d7273	internal/poll.(*FD).Write+0x243										/usr/local/go/src/internal/poll/fd_unix.go:226
#	0x7efc31	net.(*netFD).Write+0x51											/usr/local/go/src/net/fd_unix.go:220
#	0x80243c	net.(*conn).Write+0x6c											/usr/local/go/src/net/net.go:188
#	0x1040409	github.com/cockroachdb/cockroach/vendor/github.com/cockroachdb/cmux.(*MuxConn).Write+0x59		<autogenerated>:1
#	0x8c1606	crypto/tls.(*Conn).write+0x1a6										/usr/local/go/src/crypto/tls/conn.go:832
#	0x8c1b1f	crypto/tls.(*Conn).writeRecordLocked+0x35f								/usr/local/go/src/crypto/tls/conn.go:909
#	0x8c2a3a	crypto/tls.(*Conn).Write+0x1ba										/usr/local/go/src/crypto/tls/conn.go:1068
#	0x975f05	net/http.checkConnErrorWriter.Write+0x55								/usr/local/go/src/net/http/server.go:3217
#	0x74a22e	bufio.(*Writer).Write+0x14e										/usr/local/go/src/bufio/bufio.go:599
#	0x96996a	net/http.(*chunkWriter).Write+0xaa									/usr/local/go/src/net/http/server.go:364
#	0x74a22e	bufio.(*Writer).Write+0x14e										/usr/local/go/src/bufio/bufio.go:599
#	0x96f64f	net/http.(*response).write+0x14f									/usr/local/go/src/net/http/server.go:1500
#	0x96f423	net/http.(*response).Write+0x63										/usr/local/go/src/net/http/server.go:1470
#	0x8fbf40	compress/flate.(*huffmanBitWriter).write+0x60								/usr/local/go/src/compress/flate/huffman_bit_writer.go:144
#	0x8fc1b4	compress/flate.(*huffmanBitWriter).writeBytes+0xf4							/usr/local/go/src/compress/flate/huffman_bit_writer.go:193
#	0x8f8448	compress/flate.(*compressor).writeStoredBlock+0x98							/usr/local/go/src/compress/flate/deflate.go:289
#	0x8f961b	compress/flate.(*compressor).store+0x6b									/usr/local/go/src/compress/flate/deflate.go:528
#	0x8f981f	compress/flate.(*compressor).write+0x7f									/usr/local/go/src/compress/flate/deflate.go:551
#	0x8faeca	compress/flate.(*Writer).Write+0x4a									/usr/local/go/src/compress/flate/deflate.go:709
#	0x906b7c	compress/gzip.(*Writer).Write+0xfc									/usr/local/go/src/compress/gzip/gzip.go:196
#	0x17ca2ea	github.com/cockroachdb/cockroach/pkg/server.(*gzipResponseWriter).Write+0x4a				/go/src/github.com/cockroachdb/cockroach/pkg/server/server.go:1430
#	0x70ac24	fmt.Fprintf+0xa4											/usr/local/go/src/fmt/print.go:182
#	0xda714b	github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt.labelPairsToText+0x23b	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt/text_create.go:261
#	0xda6bcb	github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt.writeSample+0x16b		/go/src/github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt/text_create.go:214
#	0xda536e	github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt.MetricFamilyToText+0x2fe	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/prometheus/common/expfmt/text_create.go:77
#	0xda9f35	github.com/cockroachdb/cockroach/pkg/util/metric.(*PrometheusExporter).PrintAsText+0xc5			/go/src/github.com/cockroachdb/cockroach/pkg/util/metric/prometheus_exporter.go:90
#	0x143c2b5	github.com/cockroachdb/cockroach/pkg/server/status.(*MetricsRecorder).PrintAsText+0xa5			/go/src/github.com/cockroachdb/cockroach/pkg/server/status/recorder.go:234`
```

**Comment by mberhault** [comment] 2017-11-17 13:59
Yup, same thing. The ultimate question is: why are we not able to send things over the network. I'm guessing something wrong on the prometheus (itself, or azure vm/network) causing the issue.

**Comment by tschottdorf** [comment] 2017-11-17 14:28
paging @nvanbenschoten, is this similar to the gossip 15min timeout?

**Comment by bdarnell** [comment] 2017-11-17 16:07
> I'm guessing something wrong on the prometheus (itself, or azure vm/network) causing the issue.

It's possible that this is just prometheus failing to read from the socket (and we should release the mutex while writing to the network), but since we've seen the same symptom elsewhere we should consider that it's something on the sending side. 

I think mishandling file descriptors (most likely in C++ land, i.e. rocksdb) could have this symptom. Every confirmed instance of this problem is on a 1.2-alpha build. Do they all include rocksdb 5.9, or have we seen this problem on an old rocksdb?

Specifically, the scenario I'm thinking of is some other thread closing the file descriptor (probably by number instead of via the Go netFD object, hence the concern about C++. A double-close with insufficient checking could cause this) while this thread is writing to it.

**Comment by nvanbenschoten** [comment] 2017-11-17 19:14
@tschottdorf very interesting! Yes, this does look similar to the gossip 15m timeout issue. Just like over there, we see a goroutine stuck in `runtime_pollWait` while trying to perform a write. The key difference is that the write here isn't even going through gRPC.

> Every confirmed instance of this problem is on a 1.2-alpha build

This is technically true about https://github.com/cockroachlabs/rubrik/issues/5 (which I think is why you said "confirmed"), but some of the initial results there, before we began collecting goroutine dumps, were from 1.1. That goes to say that there's a chance this isn't limited to 1.2.

**Comment by tschottdorf** [comment] 2017-11-20 21:12
I ran a script to `close()` all the fds belonging to these stuck connections to see what would happen. It didn't go well (forgot to grep for CLOSE_WAIT and got a SIGSEGV after ~8k `close()s` and the process also closed :8080 and :26257) but I'll document what I did below for posterity.

I used `lsof` to list the fds, though had to change the code that assigns to `Lf->fd` (to print the full fd numbers and not only a suffix)

```
apt-get install debhelper libselinux1-dev gdb
apt-get source lsof
cd lsof*
# make edits
...
# compile
dpkg-buildpackage -us -uc -nc
# on further edits: re-run make

./lsof -p $(pgrep roach) -a -i TCP | awk '{print $4 }' | grep CLOSE_WAIT | grep -E '[0-9]+' -o | awk '$0="call close("$0")"' > batch
gdb -p $(pgrep roach) -batch -x batch

**Comment by nvanbenschoten** [comment] 2017-11-20 22:05
To provide more context to @tschottdorf's experiment, we saw about 12 thousand open file descriptors on each of the wedged nodes in the `CLOSE_WAIT` state. These descriptors were all TCP connections on port 8080, presumably handling the `/_status/vars` endpoint. This issue was not seen on other nodes, so it seems safe to say that it's related to this issue. Whether it was the cause or not is harder to say.

@vijaykarthik-rubrik just ran the test in cockroachlabs/rubrik#5 and found no descriptors in this state. In fact, the `lsof` output looked perfectly healthy over there. This leads me to believe that the issues are more different from each other than I had hoped.

**Comment by a-robinson** [comment] 2017-11-20 22:12
This is mostly uninformed conjecture, but couldn't all the CLOSE_WAIT connections just be due to prometheus giving up on waiting for responses? i.e. prometheus closed the connection on its end but the server hasn't closed its socket yet because it's still waiting on the goroutine to finish processing the request.

**Comment by mberhault** [comment] 2017-11-20 22:20
This seems likely. The `/_status/vars` lock is forcing all requests behind the wedged one. Changing the vars handler to write to a temporary buffer and then flush that into the response writer outside the lock would avoid this. That's only a work-around though, it does not explain why the initial request failed.

**Comment by nvanbenschoten** [comment] 2017-11-20 22:21
@a-robinson yeah that seems like it adds up. We still see all of the goroutines stuck waiting on the lock (like you posted above) so they wouldn't have closed their FDs yet.

I played around with closing random TCP file descriptors like @bdarnell suggested but wasn't able to cause any damage to a running cluster. The worst I was able to do was cause "ambiguous result" errors which KV didn't like, but Cockroach neither crashed nor got stuck.

**Comment by mberhault** [comment] 2017-12-20 12:41
The `/_status/vars` locking issue was fixed, but the root problem is still the same (hung connections). @nvanbenschoten: what was the final say on this? Just bad networking?

**Comment by nvanbenschoten** [comment] 2017-12-20 17:14
Unless we see this again or find any other proof that may implicate prometheus as an actor here, I think that's the only guess we can make. The one thing we do know is that this wasn't related to the privately reported issue. I'm going to close for now, but we can reopen if we ever see it again.

**Closed by nvanbenschoten** 2017-12-20 17:14 UTC

**Comment by mberhault** [comment] 2017-12-20 17:17
Thanks. Unfortunately, if prometheus causes hung connections somehow, this will hid it (unless we accumulate enough that we run out of file descriptors or memory).
