### ISSUE TITLE
circleci: failed tests (15284): TestDockerPHP

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5579] opened 2016-03-25 17:39 UTC
The following test appears to have failed:

[#15284](https://circleci.com/gh/cockroachdb/cockroach/15284):

```
  ui:        https://127.0.0.1:32848
  trace:     https://127.0.0.1:32848/debug/requests
  logs:      /tmp/circle-artifacts.KPONkFV/acceptance/TestDockerPHP/roach0/cockroach.INFO
  pprof:     docker exec -it f4a77 /bin/bash -c 'go tool pprof /cockroach <(wget --no-check-certificate -qO- https://$(hostname):8080/debug/pprof/heap)'
  cockroach: [start --ca-cert=/certs/ca.crt --cert=/certs/node.crt --key=/certs/node.key --host=roach0 --alsologtostderr=INFO --store=path=/data1.0 --log-dir=/logs/roach0 --logtostderr=false]
panic: test timed out after 5m0s

goroutine 1373 [running]:
panic(0x119c380, 0xc82057f900)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0x176f5f8, 0x1df66c0, 0x11, 0x11, 0xf2199b774adfcc01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820338f08, 0x176d4c8)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc820338f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:84 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x20cbb40)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1003 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 22 [select, 4 minutes, locked to thread]:
runtime.gopark(0x176fe30, 0xc820027f28, 0x14aeb00, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820027f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820027f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 7 [syscall, 4 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 8 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 1324 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x7f029af957c0, 0xc820083460, 0x7f029af95830, 0xc8204ec140, 0xc8200e0d20, 0x0, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x49d
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc8203a01e0, 0x7f029af957c0, 0xc820083460, 0x14a7d18, 0x4, 0xc82049c1e0, 0x52, 0x0, 0x7f029af934b0, 0xc8204cee00, ...)
	/go/src/github.com/docker/engine-api/client/request.go:93 +0x45a
github.com/docker/engine-api/client.(*Client).sendRequest(0xc8203a01e0, 0x7f029af957c0, 0xc820083460, 0x14a7d18, 0x4, 0xc82049c1e0, 0x52, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:71 +0x2b1
github.com/docker/engine-api/client.(*Client).post(0xc8203a01e0, 0x7f029af957c0, 0xc820083460, 0xc82049c1e0, 0x52, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:36 +0xb4
github.com/docker/engine-api/client.(*Client).ContainerStart(0xc8203a01e0, 0x7f029af957c0, 0xc820083460, 0xc8202e0a80, 0x40, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/container_start.go:7 +0xd8
--
testing.tRunner(0xc820446090, 0x1df6780)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 164 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8201408f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 12 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7f029af968b0, 0x72, 0xc82025d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82025a4c0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82025a4c0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82025a460, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a3d0, 0xc82025d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82025e410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 13 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc82025e410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 922 [IO wait]:
net.runtime_pollWait(0x7f029afa3b68, 0x72, 0xc8204f6000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820304530, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820304530, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203044d0, 0xc8204f6000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820086278, 0xc8204f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82025e820)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 269 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f029af964f0, 0x72, 0xc8202a1000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203c4d10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203c4d10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203c4cb0, 0xc8202a1000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820086218, 0xc8202a1000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201fa820)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1366 [select]:
net/http.(*persistConn).writeLoop(0xc82025eea0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 270 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc8201fa820)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1141 [IO wait]:
net.runtime_pollWait(0x7f029afa3ce8, 0x72, 0xc8202bf000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203043e0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203043e0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820304380, 0xc8202bf000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a310, 0xc8202bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82025ea90)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 365 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820068410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 163 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f029af96730, 0x72, 0xc820488000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203ac840, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203ac840, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203ac7e0, 0xc820488000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a270, 0xc820488000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201408f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 616 [select]:
net/http.(*persistConn).writeLoop(0xc8203061a0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1372 [select]:
net/http.(*persistConn).roundTrip(0xc820306410, 0xc82057f870, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8202586c0, 0xc8200e0d20, 0xc8202586c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc8200e0d20, 0x7f029af55998, 0xc8202586c0, 0x0, 0x0, 0x0, 0xc820396500, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc82051c150, 0xc8200e0d20, 0x0, 0x0, 0x0, 0xc8203f6358, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).doFollowingRedirects(0xc82051c150, 0xc8200e0d20, 0x176f9a0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:475 +0x8a4
--
github.com/docker/engine-api/client/transport/cancellable.Do.func1(0x7f029af95830, 0xc8204ec140, 0xc8200e0d20, 0xc82049c300)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:49 +0x35
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:52 +0xff

goroutine 1327 [IO wait]:
net.runtime_pollWait(0x7f029afa4168, 0x72, 0xc820313000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203c4290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203c4290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203c4230, 0xc820313000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a388, 0xc820313000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820306410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 364 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f029af96670, 0x72, 0xc82032b000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203ac140, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203ac140, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203ac0e0, 0xc82032b000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820086030, 0xc82032b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820068410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 470 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f029af965b0, 0x72, 0xc8201f4000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203ac300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203ac300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203ac2a0, 0xc8201f4000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820086208, 0xc8201f4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201409c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 615 [IO wait]:
net.runtime_pollWait(0x7f029af967f0, 0x72, 0xc8202e3000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203ac760, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203ac760, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203ac700, 0xc8202e3000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a650, 0xc8202e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8203061a0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 471 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8201409c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 497 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82010ba20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 655 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc820011340)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 662 [chan receive, 1 minutes]:
database/sql.(*DB).connectionOpener(0xc8202320b0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 517 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82010bc30)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 510 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820233810)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 923 [select]:
net/http.(*persistConn).writeLoop(0xc82025e820)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 513 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820512160)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 542 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc820513600)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 525 [chan receive, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc82035cd10)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 1251 [select]:
net/http.(*persistConn).writeLoop(0xc82025f110)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 766 [IO wait]:
net.runtime_pollWait(0x7f029af95cb0, 0x72, 0xc8204ea000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203048b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203048b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820304850, 0xc8204ea000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2a8, 0xc8204ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8203065b0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 767 [select]:
net/http.(*persistConn).writeLoop(0xc8203065b0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1345 [IO wait]:
net.runtime_pollWait(0x7f029afa3c28, 0x72, 0xc820335000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8204ce6f0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204ce6f0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204ce690, 0xc820335000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200862d0, 0xc820335000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).monitor(0xc820306d00)
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:553 +0xd1
created by github.com/cockroachdb/cockroach/acceptance/cluster.(*LocalCluster).Start
	/go/src/github.com/cockroachdb/cockroach/acceptance/cluster/localcluster.go:577 +0x731

goroutine 1365 [select]:
net/http.(*persistConn).readLoop(0xc82025eea0)
	/usr/local/go/src/net/http/transport.go:1178 +0xd52
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1328 [select]:
net/http.(*persistConn).writeLoop(0xc820306410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1250 [IO wait]:
net.runtime_pollWait(0x7f029af95e30, 0x72, 0xc8202ca000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820304d10, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820304d10, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820304cb0, 0xc8202ca000, 0x1000, 0x1000, 0x0, 0x7f029af4d028, 0xc8200820b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200862f8, 0xc8202ca000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82025f110)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1142 [select]:
net/http.(*persistConn).writeLoop(0xc82025ea90)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1350 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do.func3(0x7f029af58810, 0xc8204dfb40, 0xc82057ef50, 0xc820448000)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:78 +0xef
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:84 +0x336
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-28 13:45
Duplicate of #5574.

**Closed by petermattis** 2016-03-28 13:45 UTC
Labels: Robot, test-failure
