### ISSUE TITLE
raft: deadlock during split

### ISSUE THREAD

**Issue by mrtracy** [cockroachdb/cockroach#2598] opened 2015-09-21 20:42 UTC
This occurred on a six-node cluster which was under constant insertion load; splits were occuring and ranges were being rebalanced. 

At some point, a range split caused one of the nodes to deadlock; raft communication from other nodes ceased.

Unfortunately, I do not have a good stack trace which illustrates this; however, I have had this occur more than once, and if others begin testing on 3+ node clusters they will likely encounter the same issue.  Please add any information you uncover to this issue.

**Comment by tschottdorf** [comment] 2015-10-23 03:22
is this still current? The issue is not helpful without additional information. Closing for cleanup, but please reopen if there's something to add.

**Closed by tschottdorf** 2015-10-23 03:22 UTC
