### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestShowCreateTable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6232] opened 2016-04-22 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/7330af43411417dc60927b5a4cee0ee715b2cadc

Stress build found a failed test:

```
=== RUN   TestShowCreateTable
W160422 06:29:25.771563 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160422 06:29:25.791155 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160422 06:29:25.792435 server/node.go:359  store store=0:0 ([]=) not bootstrapped
W160422 06:29:25.792540 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160422 06:29:25.794091 storage/replica_command.go:1465  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.793836017s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.794018577 +0000 UTC]
I160422 06:29:25.794602 server/node.go:309  **** cluster {1dee8c37-3809-4c8e-9863-686d67bfd55a} has been created
I160422 06:29:25.794619 server/node.go:310  **** add additional nodes by specifying --join=127.0.0.1:36456
W160422 06:29:25.794631 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160422 06:29:25.795334 server/node.go:372  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8371040256 RangeCount:0}
I160422 06:29:25.795354 server/node.go:284  node ID 1 initialized
I160422 06:29:25.795389 storage/stores.go:287  read 0 node addresses from persistent storage
I160422 06:29:25.795431 server/node.go:493  connecting to gossip network to verify cluster ID...
I160422 06:29:25.795696 server/node.go:514  node connected via gossip and verified as part of cluster {"1dee8c37-3809-4c8e-9863-686d67bfd55a"}
I160422 06:29:25.795736 server/node.go:337  [node=1] Started node with [[]=] engine(s) and attributes []
I160422 06:29:25.795760 server/server.go:366  starting https server at 127.0.0.1:36407
I160422 06:29:25.795770 server/server.go:367  starting grpc/postgres server at 127.0.0.1:36456
I160422 06:29:25.795832 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160422 06:29:25.796371 server/updates.go:147  No previous updates check time.
I160422 06:29:25.802586 storage/replica_command.go:1919  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160422 06:29:25.809837 storage/replica_command.go:1465  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.895022772s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.809794335 +0000 UTC]
I160422 06:29:25.810228 storage/replica_command.go:1919  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160422 06:29:25.823621 storage/replica_command.go:1465  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.895022772s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.823578237 +0000 UTC]
I160422 06:29:25.823743 storage/replica_command.go:1919  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160422 06:29:25.831547 storage/replica_command.go:1465  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.895022772s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.831519568 +0000 UTC]
I160422 06:29:25.831653 storage/replica_command.go:1919  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160422 06:29:25.894994 storage/replica_command.go:1465  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.944650673s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.894948639 +0000 UTC]
I160422 06:29:25.895127 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160422 06:29:25.895443 storage/replica_command.go:1919  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160422 06:29:25.903711 storage/replica_command.go:1465  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.953478586s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.903666601 +0000 UTC]
I160422 06:29:25.904375 storage/split_queue.go:100  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160422 06:29:25.904649 storage/replica_command.go:1919  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160422 06:29:25.916947 storage/replica_command.go:1465  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.9663977s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.91690411 +0000 UTC]
I160422 06:29:25.917090 storage/split_queue.go:100  splitting range=7 [/Table/51-/Max) at keys [/Table/52/0]
I160422 06:29:25.917215 storage/replica_command.go:1919  initiating a split of range=7 [/Table/51-/Max) at key /Table/52
I160422 06:29:25.942987 storage/replica_command.go:1465  range 8: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405918h29m26.992674632s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-22 06:29:25.94294121 +0000 UTC]
I160422 06:29:25.943113 storage/split_queue.go:100  splitting range=8 [/Table/52-/Max) at keys [/Table/53/0]
I160422 06:29:25.943269 stopper.go:352  draining; tasks left:
1      storage/queue.go:383
1      server/node.go:742
E160422 06:29:25.943469 storage/queue.go:446  [split] range=8 [/Table/52-/Max): error: storage/split_queue.go:103: unable to split range=8 [/Table/52-/Max) at key "/Table/53/0": failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:743: node 1 stopped
I160422 06:29:26.943680 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:36456: getsockopt: connection refused"; Reconnecting to "127.0.0.1:36456"
I160422 06:29:28.470964 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:36456: getsockopt: connection refused"; Reconnecting to "127.0.0.1:36456"
I160422 06:29:28.471149 /go/src/google.golang.org/grpc/clientconn.go:317  Failed to dial 127.0.0.1:36456: grpc: timed out trying to connect; please retry.
--- FAIL: TestShowCreateTable (2.76s)
	show_test.go:110: pq: sql/lease.go:108: table ID 52 not found
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
6 runs so far, 0 failures, over 35s
13 runs so far, 0 failures, over 40s
16 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
19 runs completed, 1 failures, over 1m8s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:15
Duplicate of #6226

**Closed by bdarnell** 2016-04-23 14:15 UTC
Labels: Robot, test-failure
