### ISSUE TITLE
storage: Separate out consistency checks over floating point data

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#5518] opened 2016-03-23 20:44 UTC
We run periodic consistency checks over all the replicated data. Timeseries data which is cockroach internal, is replicated consistently, but merged independently often outside of raft on each replica. While the consistency checker forces a merge on each replica at a snapshot, thereby making it consistent before computing a checksum on the data, the data itself contains floating points, with the merge operator running floating point math like adding up all the timeseries values. We'd like to continue running consistency checks on this data so we can catch consistency problems on homogenous clusters, while accepting consistency differences on heterogenous one.

Options:
1. Separate out the checksum over timeseries data so that it doesn't interfere with the range checksum (preferred).
2. Convert the floating point values into integers and run integer math on them. Not recommended because we also really don't care about this data being that accurate.

**Comment by vivekmenezes** [comment] 2016-03-24 01:36
Turns out floating point addition is not associative even on the same machine

http://www.walkingrandomly.com/?p=5380

So option 1 is the only way to fix this bug. I'm going to remove timeseries from the checksum for now.

**Comment by tschottdorf** [comment] 2016-03-24 02:07
That statement doesn't make sense to me. Could you clarify?

**Comment by vivekmenezes** [comment] 2016-03-24 02:41
Actually I stand corrected. Merging of values are done is a specific order. So merging A, B, C involves,
merging A and B first followed by merging it with C. What's true though is that the A and B merge can happen on one node due to a read command executed on that node, without the merge happening on a replica. But when we run a consistency check, all nodes would have done (A + B) + C because the consistency check reads a value at the same snapshot on all replicas.

Also, earlier I meant that I'd like to use option 2 (not option 1) to fix this bug.

For now, I'm going to stick with option 1

**Comment by tschottdorf** [comment] 2016-03-24 11:56
That sounds like we have nothing to worry about - are we really not doing
`A + (B + C)` on one node and `(A + B) + C` on another due to the order in which the merges are flushed out? I don't mind separating out a subchecksum (maybe having checksums for each individual chunk of data makes sense anyway) but it'd be good to know whether we think it's actually necessary.

**Comment by vivekmenezes** [comment] 2016-03-24 12:45
We still need to be wary of floating point because of the additions
happening on heterogeneous systems.

We are always doing (a+b)+c on all nodes

**Comment by tschottdorf** [comment] 2016-03-24 14:27
Oh, so the only worry left is that two nodes are running binaries with...
different Go versions? Or can there be differences across different
architectures? That seems like it (hopefully) shouldn't be the case.

**Comment by tschottdorf** [comment] 2016-03-24 14:27
This would also ruin our consistency in general, btw, because SQL does
float computations (if you want it to).

**Comment by vivekmenezes** [comment] 2016-03-24 14:47
http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

if you're interested.

I don't think we can be confident that the representation of floats as well as their math can be consistent across two different hardware architectures. I believe Go version doesn't affect this.

Regarding SQL, there is reason why customers are encouraged to not use floats for things like representing money.

**Comment by tamird** [comment] 2016-03-24 14:53
What are we looking for in that article, exactly?

> Regarding SQL, there is reason why customers are encouraged to not use floats for things like representing money.

Yes, there is a reason, but that reason is typically rounding error, not "float operations are inconsistent" or "float operations aren't associative" or some variant of that.

Separately, reading this thread from the start has left me confused. Do we still believe that we have inconsistency wrt floats? What's the cause?

**Comment by vivekmenezes** [comment] 2016-03-24 15:05
We don't haven't seen any inconsistencies due to float. But this issue is about ensuring that when cockroach runs on heterogenous clusters, and inconsistencies are seen due to rounding error, or any other issue caused by FP, the consistency checker doesn't panic. I'd like to take values that we believe might become inconsistent out, while continuing to checksum them so that if we notice a true consistency issue on a homogenous system we notice.

**Comment by vivekmenezes** [comment] 2016-03-24 15:07
https://github.com/cockroachdb/cockroach/pull/5525

implements option 1

**Comment by tschottdorf** [comment] 2016-03-24 15:13
> This would also ruin our consistency in general, btw, because SQL does
float computations (if you want it to).

This is a nonsense statement (of mine). SQL happens outside of Raft, so different nodes might be putting different stuff in, but that's fine.

I don't disagree that floats (at least down in C++) can be tricky, and I don't object to shelling out that part of the keyspace for now. But at the end of the day, option 2 doesn't seem so bad - if it does save us all the trouble

**Comment by vivekmenezes** [comment] 2016-03-24 15:18
The problem I have with option 2 is that we're limiting the implementation because of the consistency checker, and that feels wrong.

**Comment by tamird** [comment] 2016-03-24 15:38
> We don't haven't seen any inconsistencies due to float. But this issue is about ensuring that when cockroach runs on heterogenous clusters, and inconsistencies are seen due to rounding error, or any other issue caused by FP, the consistency checker doesn't panic. I'd like to take values that we believe might become inconsistent out, while continuing to checksum them so that if we notice a true consistency issue on a homogenous system we notice.

I don't follow this - are you suggesting that FP operations are not platform-independent? What "other issues caused by FP" do we expect?

**Comment by vivekmenezes** [comment] 2016-03-24 16:08
On Thu, Mar 24, 2016 at 11:39 AM Tamir Duberstein <notifications@github.com>
wrote:

> We don't haven't seen any inconsistencies due to float. But this issue is
> about ensuring that when cockroach runs on heterogenous clusters, and
> inconsistencies are seen due to rounding error, or any other issue caused
> by FP, the consistency checker doesn't panic. I'd like to take values that
> we believe might become inconsistent out, while continuing to checksum them
> so that if we notice a true consistency issue on a homogenous system we
> notice.
>
> I don't follow this - are you suggesting that FP operations are not
> platform-independent? What "other issues caused by FP" do we expect?
>
I'm not familiar with the entire gamut of possible issues here. One issue
could be FP representation. The same fp number can be represented in
different ways. I believe that most architectures should use a normalized
form, but can we depend on that? I'm uncomfortable with depending on fp
representation and math being consistent.

**Comment by vivekmenezes** [comment] 2016-03-24 17:55
FYI, trying out option 2, which is to convert the floats to integer representations.

**Comment by petermattis** [comment] 2016-03-24 23:49
I'm pretty sure every system we care about uses IEEE 754 floating point. Go requires IEEE 754 math. Supporting other kinds of floating point doesn't seem reasonable to me.

Is there a specific set of operations on IEEE 754 floating point numbers that is problematic?

**Comment by vivekmenezes** [comment] 2016-03-25 00:09
I just sent out another PR which includes  the requirements in the
description. While I agree with what you're saying I feel strongly that we
should land that PR because it just makes this bullet proof without
compromising anything.

I've not found a conclusive discussion anywhere guaranteeing the
requirements via pure floating point.  Only the paranoid survive.

**Comment by petermattis** [comment] 2016-03-25 00:19
Paranoia can be taken too far. IEEE 754 guarantees a consistent representation across systems. I was mainly curious if there is an actual failure that we know about. If there isn't, moving away from floating point for timeseries data seems like unnecessary churn at this time.

**Comment by vivekmenezes** [comment] 2016-03-25 01:05
https://github.com/cockroachdb/cockroach/pull/5560

is the relevant PR. It's not that bad.

We haven't seen any issues but my concern comes from the difficult of
debugging consistency issues when they happen.
The next time I see a panic because of a consistency issue, I'm going to
have to ask myself, "could this be because of floating point", and
trust me I don't have any interest in reading the IEEE standard.

**Comment by petermattis** [comment] 2016-03-25 04:27
I don't think you need to read the IEEE 754 standard. But we shouldn't be making changes based on fear-uncertainty-and-doubt. A little googling shows it is easy to demonstrate the lack of associativity in floating point addition. See http://play.golang.org/p/RQD-ShnP0G for an example. If we can't construct a series of merge operations which cause discrepancy then we shouldn't be making a change here.

**Comment by vivekmenezes** [comment] 2016-03-25 13:00
Let's chat about this. I do think we should be making changes eliminating
uncertainty. These are the kinds of bugs impossible to debug. I already
have a PR ready, and the burden should not be placed on proving that
floating point operations are predictable. What's the concern with making
the change?

**Comment by tamird** [comment] 2016-03-25 13:44
On Fri, Mar 25, 2016 at 9:00 AM, vivekmenezes <notifications@github.com>
wrote:

> the burden should not be placed on proving that
> floating point operations are predictable
>

Indeed, the burden should be on proving that FP operations are
*unpredictable*. AFAICT there's no evidence that this is the case.

**Comment by bdarnell** [comment] 2016-03-25 14:34
> Go requires IEEE 754

The floating-point math in question happens in C++, and C++ does not mandate IEEE 754 (protobufs require that the final value is in IEEE 754 format but the intermediate computation could have been otherwise).

Unless you take great care, a conforming C/C++ compiler is free to change your code in ways that may affect the result: https://randomascii.wordpress.com/2013/07/16/floating-point-determinism/.  Fortunately for us, we're only doing one addition at a time and there's enough abstraction going on that I don't think the compiler would be able to do enough inlining to affect us here, but we're definitely on unstable ground here. 

I agree with @vivekmenezes; it's too risky to use floating point in areas that are expected to be bit-for-bit identical (i.e. in the application of raft commands). I think it would be best to move to integer/fixed point for timeseries data.

**Comment by petermattis** [comment] 2016-03-25 22:46
I'm not against switching to fixed-point for timeseries data, but let's be clear why we are doing so: there is a concern that future changes to our use of floating point data may introduce inconsistencies. Note that there is an alternative to switching to a fixed-point representation: avoid performing floating point calculations in the merge operator. I mentioned one approach for doing this in #5560. Note that we already do this for partial merges.

**Comment by vivekmenezes** [comment] 2016-03-26 01:32
You are referring to the approach of not doing the addition at all and just merging the values into single proto per offset. That reduces the risk considerably because I feel a lot more comfortable with the representation being stable. And the order is guaranteed via raft.

Luckily we can change `optional sum` to `repeated sum ` whenever we want, so there is no hurry to do that as far as the protobuf freeze is concerned. We might as well make this change now. We can also rename sum to value and get rid of count. It might actually be a savings given that we are eliminating count.

I can do this over the weekend if you like as long as there is consensus that we will merge it.

**Comment by bdarnell** [comment] 2016-03-27 16:16
As long as we never expect to have more than a handful of values per record (per @mtracy's comment in #5560), replacing the sum with `repeated double value` SGTM. 

This also implies that contention is low for these keys - we might be able to simplify things post-beta by moving from Merge to CPut and getting rid of all the merge machinery.

**Comment by vivekmenezes** [comment] 2016-04-04 15:21
@mtracy for your thoughts on whether we should just make this CPut and be done with it.

**Comment by mrtracy** [comment] 2016-04-05 19:37
The performance impact would be quite substantial regardless of contention, as we currently only need to _write_ when merging data, and this would move to a _read-modify-write_ model. But, I suppose that is relative to the contention on the keys.

However, because the system is already working, I don't see how it would be any easier than modifying the existing C++ code.  The current "accumulate" method could be modified to simply discard all but the most recent sample at a given offset.

**Comment by mrtracy** [comment] 2016-04-06 22:31
I believe that this issue will be closed by #5905, which removes all floating point math in the merge operation.

**Comment by petermattis** [comment] 2016-04-11 13:56
@mrtracy, @vivekmenezes Is there anything else to do here now that #5905 is merged?

**Closed** 2016-04-11 15:35 UTC
