### ISSUE TITLE
multitenant: TestWaitingRU flaked

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#99476] opened 2023-03-24 14:14 UTC
See CI flake [here](https://teamcity.cockroachdb.com/viewLog.html?buildId=9234881&buildTypeId=Cockroach_BazelEssentialCi). 

Jira issue: CRDB-25897

**Comment by rharding6373** [comment] 2023-04-26 17:31
This looks like a dupe of #95547

**Closed by rharding6373** 2023-04-26 17:31 UTC
Labels: C-test-failure, T-sql-queries
