### ISSUE TITLE
circleci: failed tests: TestGossipNoForwardSelf 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5927] opened 2016-04-07 18:23 UTC
The following test appears to have failed:

[#16042](https://circleci.com/gh/cockroachdb/cockroach/16042):

```
I160407 18:18:05.203358 gossip/server.go:261  @5: distantHops: 2 from 2
I160407 18:18:05.209071 gossip/client.go:146  node 4 received [node:1 node:2 node:3 node:5] from node 1 (4 fresh)
I160407 18:18:05.209165 gossip/server.go:261  @4: distantHops: 2 from 2
I160407 18:18:05.209801 gossip/client.go:84  closing client to node 1 (127.0.0.1:57973): gossip/client.go:168: received forward from node 1 to 2 (127.0.0.1:36523)
==================
WARNING: DATA RACE
Read by goroutine 35:
  reflect.Value.Int()
      /usr/local/go/src/reflect/value.go:887 +0x14f
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:865 +0x44e
  fmt.(*pp).printValue()
      /usr/local/go/src/fmt/print.go:848 +0x551
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:932 +0x4aa5
  fmt.(*pp).printValue()
--
  github.com/cockroachdb/cockroach/gossip.TestGossipNoForwardSelf()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip_test.go:197 +0x1585
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Previous write by goroutine 142:
  github.com/cockroachdb/cockroach/gossip.(*client).handleResponse()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:151 +0x847
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2.1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:229 +0x94
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:233 +0x62
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Goroutine 35 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:120 +0x210

Goroutine 142 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:234 +0x573
  github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:78 +0x323
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f
==================
==================
WARNING: DATA RACE
Read by goroutine 35:
  reflect.Value.pointer()
      /usr/local/go/src/reflect/value.go:91 +0x97
  reflect.Value.MapKeys()
      /usr/local/go/src/reflect/value.go:1070 +0xec
  fmt.(*pp).printReflectValue()
      /usr/local/go/src/fmt/print.go:893 +0x2eb1
  fmt.(*pp).printValue()
      /usr/local/go/src/fmt/print.go:848 +0x551
  fmt.(*pp).printReflectValue()
--
  github.com/cockroachdb/cockroach/gossip.TestGossipNoForwardSelf()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip_test.go:197 +0x1585
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:473 +0xdc

Previous write by goroutine 142:
  github.com/cockroachdb/cockroach/gossip.(*client).handleResponse()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:153 +0x900
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2.1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:229 +0x94
  github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:233 +0x62
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f

Goroutine 35 (running) created at:
  testing.RunTests()
      /usr/local/go/src/testing/testing.go:582 +0xae2
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:515 +0x11d
  main.main()
      github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:120 +0x210

Goroutine 142 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x6f
  github.com/cockroachdb/cockroach/gossip.(*client).gossip()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:234 +0x573
  github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/client.go:78 +0x323
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x5f
==================
I160407 18:18:05.214724 gossip/server.go:114  node 1 returned 3 info(s) to node 3
--- FAIL: TestGossipNoForwardSelf (0.07s)
	gossip_test.go:197: expected &{1 0xc82012c118 <nil> map[3:1460053085177280592 5:1460053085189022321 1:1460053085152216054 2:1460053085159977248] 0xc8203cf8c0} to be disconnected, got &{1 0xc82012c118 0xc820192f60 map[] 0xc8203cf620}
=== RUN   TestGossipCullNetwork
W160407 18:18:05.236376 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
W160407 18:18:05.239236 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:18:05.241437 gossip/gossip.go:913  starting client to 127.0.0.1:59423
W160407 18:18:05.245553 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:18:05.247984 gossip/gossip.go:913  starting client to 127.0.0.1:60236
W160407 18:18:05.248641 gossip/gossip.go:887  not connected to cluster; use --join to specify a connected node
I160407 18:18:05.252943 gossip/gossip.go:913  starting client to 127.0.0.1:36657
I160407 18:18:05.257409 gossip/server.go:114  node 3 returned 1 info(s) to node 1
--
I160407 18:18:06.841700 stopper.go:352  draining; tasks left:
2      gossip/infostore.go:286
I160407 18:18:06.841869 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
--- PASS: TestGossipStorage (0.11s)
FAIL
FAIL	github.com/cockroachdb/cockroach/gossip	2.093s
=== RUN   TestParseResolverSpec
--- PASS: TestParseResolverSpec (0.00s)
=== RUN   TestGetAddress
--- PASS: TestGetAddress (0.00s)
PASS
ok  	github.com/cockroachdb/cockroach/gossip/resolver	1.056s
?   	github.com/cockroachdb/cockroach/gossip/simulation	[no test files]
=== RUN   TestKeySorting
--- PASS: TestKeySorting (0.00s)
=== RUN   TestMakeKey

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-07 21:29
Duplicate of #5923

**Closed by bdarnell** 2016-04-07 21:29 UTC
Labels: Robot, test-failure
