### ISSUE TITLE
Test failure in CI build 7209

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2443] opened 2015-09-10 01:21 UTC
The following test appears to have failed:

[#7209](https://circleci.com/gh/cockroachdb/cockroach/7209):

```
E0910 01:21:03.793029 792 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 01:21:04.093036 792 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
I0910 01:21:04.303260 792 kv/txn_coord_sender.go:280  txn coordinator: 0.00 txn/sec, 0.00/0.00/0.00 %cmmt/abrt/abnd, 0/0/0 avg/σ/max duration, 0.0/0.0/0.0 avg/σ/max restarts (0 samples)
E0910 01:21:04.393032 792 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
E0910 01:21:04.693033 792 server/raft_transport.go:142  could not get address for node 0: gossip/gossip.go:220: unable to lookup descriptor for node 0
panic: test timed out after 1m10s

goroutine 2842 [running]:
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:703 +0x132
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive, 1 minutes]:
testing.RunTests(0x13b4a40, 0x1952160, 0x1f, 0x1f, 0x7d4b01)
	/usr/local/go/src/testing/testing.go:562 +0x8ad
--
	/go/src/github.com/cockroachdb/cockroach/multiraft/storage.go:145 +0x9eb
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82018e300, 0xc820562340)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x62
FAIL	github.com/cockroachdb/cockroach/server	70.031s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.00s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.00s)
=== RUN   TestRuntimeStatRecorder
I0910 01:20:02.082158 809 server/status/runtime.go:118  runtime stats: 10 goroutines, 5.09MiB active, 50000000.00cgo/sec, 72250.00/72250.00 %(u/s)time, 1676.20 %gc (1x)
--- PASS: TestRuntimeStatRecorder (0.00s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.00s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by BramGruneir** [comment] 2015-09-10 03:07
Dupe of #2440

**Closed by BramGruneir** 2015-09-10 03:07 UTC
Labels: test-failure
