### ISSUE TITLE
Test failure in CI build 7909

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2645] opened 2015-09-23 20:39 UTC
The following test appears to have failed:

[#7909](https://circleci.com/gh/cockroachdb/cockroach/7909):

```
goroutine 2683 [runnable]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc82009c360)
	/go/src/github.com/coreos/etcd/raft/multinode.go:195 +0x2499
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x30d
FAIL	github.com/cockroachdb/cockroach/storage	1.353s
=== RUN   TestBatchBasics
I0923 20:39:09.219562 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0923 20:39:09.220359 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0923 20:39:09.222794 974 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-09-23 20:41
another dupe of #2566

**Closed by tamird** 2015-09-23 20:41 UTC
Labels: test-failure
