### ISSUE TITLE
bulkio: IndexSpan: expected all resolved spans for the BACKUP to be distinct

### ISSUE THREAD

**Issue by petermattis** [cockroachdb/cockroach#62721] opened 2021-03-29 12:49 UTC
Running a local single-node 21.1 CRDB cluster, `BACKUP` currently always fails with:

```
root@localhost:26257/test> BACKUP TO 'nodelocal://0/test_cluster/cluster/2021-03-29T12:20:00Z' AS OF SYSTEM TIME 1617020401000000000 WITH revision_history;
ERROR: internal error: IndexSpan: expected all resolved spans for the BACKUP to be distinct
SQLSTATE: XX000
DETAIL: stack trace:
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_planning.go:365: spansForAllTableIndexes()
github.com/cockroachdb/cockroach/pkg/ccl/backupccl/backup_planning.go:970: func3()
github.com/cockroachdb/cockroach/pkg/sql/planhook.go:145: func1()
runtime/asm_amd64.s:1374: goexit()
HINT: You have encountered an unexpected error.
Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.
If you would rather not post publicly, please contact us directly
using the support form.
We appreciate your feedback.
```

I have a tar.gz of the data directory which should allow reproduction, though that archive contains info that I don't want to put on a public github issues.

**Comment by pbardea** [comment] 2021-03-29 21:29
Missed this when filing https://github.com/cockroachdb/cockroach/issues/62738. Closing as a duplicate of that one since it has a self-contained repro.

**Closed by pbardea** 2021-03-29 21:29 UTC
Labels: A-bulkio, C-bug
