### ISSUE TITLE
db console: back button on transactions page doesn't work right

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#63418] opened 2021-04-10 00:37 UTC
I go to the transactions page, click on a transaction to see its details. If I do a browser back, instead of taking me back to the transactions page, it either takes me to the home page of the console or to the statements page.

**Comment by nvanbenschoten** [comment] 2021-04-13 19:43
Duplicate of https://github.com/cockroachdb/cockroach/issues/58107. cc. @thtruo.

**Closed by nvanbenschoten** 2021-04-13 19:43 UTC
Labels: A-webui, C-bug, T-observability
