### ISSUE TITLE
sql: planner should prefer index that has more columns used by filter

### ISSUE THREAD

**Issue by RaduBerinde** [cockroachdb/cockroach#16426] opened 2017-06-09 18:27 UTC
From https://github.com/cockroachdb/cockroach/issues/16313#issuecomment-307437645.

We have two similar indexes, one has an extra STORING column and it is not chosen despite that with that column the filter can be entirely processed during the index scan. The planner should take this into account - the more we can push down filters, the better.

**Comment by andy-kimball** [comment] 2018-08-24 21:46
Closing, since this is fixed in the cost-based optimizer (regression case added in opt/xform/testdata/external/customer).

**Closed by andy-kimball** 2018-08-24 21:46 UTC
Labels: A-sql-planning, C-performance
