### ISSUE TITLE
backupccl: RESTORE hung at 100% after restoring the same table twice

### ISSUE THREAD

**Issue by nstewart** [cockroachdb/cockroach#23987] opened 2018-03-17 14:39 UTC
Version: `v2.0-beta.20180312`
I restored a table with ~5M rows, dropped it, and replaced it with another backup that was only 50k rows. I created the second backup in the same folder, though I cleared the original one first
[wedged-backup.zip](https://github.com/cockroachdb/cockroach/files/1821738/wedged-backup.zip)
. 
![image](https://user-images.githubusercontent.com/894257/37556557-5dfea576-29ce-11e8-9fc0-37f4a4a568e7.png)

jobs table output: [jobs.txt](https://github.com/cockroachdb/cockroach/files/1821728/jobs.txt)

**Comment by vivekmenezes** [comment] 2018-07-10 19:12
@dt any update on this issue?

**Comment by mjibson** [comment] 2018-08-07 19:35
We think this is a core problem. Unable to reproduce on our side. When we have seen this it's a hanging split.

**Comment by tschottdorf** [comment] 2018-08-13 12:56
Closing this as it occurred on a 2.0 beta, and our time is better spent on more recent reports. In particular, a hung restore occurs infrequently during our roachtest nightlies.

**Closed by tschottdorf** 2018-08-13 12:56 UTC
Labels: A-bulkio, C-bug, C-performance, S-2-temp-unavailability
