### ISSUE TITLE
cli: have a signal generate a goroutine dump in logs

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cockroach#35476] opened 2019-03-06 21:09 UTC
SIGQUIT is a standard go signal to get the go routine dump, without stopping the process and we have altered this behaviour to stop the server instead.

knz edit: SIGQUIT used to do a goroutine dump but now stops the process. That's OK. However we still want a way to get goroutine dumps.

**Comment by BramGruneir** [comment] 2019-03-06 21:20
In start_unix.go:
change
`var drainSignals = []os.Signal{unix.SIGINT, unix.SIGTERM, unix.SIGQUIT}`
to 
`var drainSignals = []os.Signal{unix.SIGINT, unix.SIGTERM}`

**Comment by knz** [comment] 2019-04-01 13:15
After thinking more about this, I think SIGQUIT should still stop the program.
However we should have a separate thing to trigger a goroutine dump.

**Comment by tbg** [comment] 2019-04-01 15:19
Was this motivated by anything in particular? You can get a goroutine dump from the debug ui. We also have the goroutine dumper that automatically generates goroutine dumps in the `goroutine_dump` directory.

I'm not 100% sure what problem we're solving here, though there are probably situations in which sending a signal is the most convenient (more convenient than `curl` though?), or in which the debug endpoint isn't ready. But `dlv attach` can also list the goroutines.

At the very least, I don't think we want to dump the goroutines in the logs but in a dedicated subdirectory.

**Comment by bdarnell** [comment] 2019-04-01 16:51
A signal-based approach A) has a chance of working when everything else is is hopelessly deadlocked and B) works in contexts that don't run HTTP servers (or don't tell you what port they're on) like unittests. It may not be standard, but I'm in favor of using SIGQUIT for this based on the JVM precedent (mainly for unittests)

Should it terminate the process? I could go either way on this. I generally lean towards terminating, although one nice thing about the JVM's dump without termination is that you could do it several times to see which threads were still moving.

And I think the stacks should be written to the logs and/or stderr, since the point of the signal interface is to work in environments other than servers, which may not have good directories to write to.

**Comment by tbg** [comment] 2019-04-01 20:55
> since the point of the signal interface is to work in environments other than servers, which may not have good directories to write to.

I don't understand this point. CockroachDB is a server and has good directories to write to (falling back to stderr if none specified), so why wouldn't we?

> And I think the stacks should be written to the logs and/or stderr,

Just pointing out that if we write to the logs, we go through `clog` and that may be the thing actually deadlocked on some mutex. I think if we worry about

> a chance of working when everything else is is hopelessly deadlocked 

we want the signal handler to do nothing except generate the dump, generate a filename, and write out the file (or to use `stderr`).

Anyway, my only strong opinion here is that we shouldn't grab any locks or do any other nonessential stuff. Beyond that, I take @bdarnell's word over my own.

**Comment by bdarnell** [comment] 2019-04-01 21:02
> I don't understand this point. CockroachDB is a server and has good directories to write to (falling back to stderr if none specified), so why wouldn't we?

`cockroach start` is a server. `pkg/storage/storage_test` is not. This is most useful IMHO for generating stack dumps from a hanging unittest.

I'm not sure how important the "hopelessly deadlocked" case is for us. It's one motivation for the signal handler approach in other systems, but it's not one that I care about much right now.

**Comment by tbg** [comment] 2019-04-01 21:10
> This is most useful IMHO for generating stack dumps from a hanging unittest.

But that works already, the standard Go signal handler does give you the stack trace.

**Comment by tbg** [comment] 2019-04-01 21:10
(whenever I have wanted that, anways. Maybe there are some situations in which `cli/start.go` is involved and it won't work any more?)

**Comment by tbg** [comment] 2019-04-01 21:11
Definitely works here:

```
$ go test ./pkg/util/stop/ -v
=== RUN   TestStopper
^\SIGQUIT: quit
PC=0x7fff5803c1b2 m=0 sigcode=0
...
```

**Comment by tbg** [comment] 2019-04-01 21:12
Works with `make test PKG=./pkg/cli/ TESTFLAGS=-v` as well 🤷‍♂️

**Comment by bdarnell** [comment] 2019-04-01 21:12
Oh, so we can get dump-and-exit by just removing SIGQUIT from our signal list? We should probably do that then instead of building our own SIGQUIT handler.

**Comment by tbg** [comment] 2019-04-01 21:14
Yeah, that's standard Go behavior (https://golang.org/pkg/os/signal/#hdr-Default_behavior_of_signals_in_Go_programs)

It happens on many other signals, too.

**Comment by knz** [comment] 2019-04-02 04:44
> Oh, so we can get dump-and-exit by just removing SIGQUIT from our signal list? We should probably do that then instead of building our own SIGQUIT handler.

I knew this already. **The point of this PR is to enable dumping the goroutines without stopping the process** (in case it can make progress).

Like [this comment](https://github.com/cockroachdb/cockroach/issues/35476#issuecomment-478658118) pointed out already.

The point about dumping the stacks to a better location if available, and being careful about the logging mutex, is well taken. I'll think about it.

**Comment by tbg** [comment] 2019-04-02 08:06
It still seems we're all a bit confused about the motivation. Do we want this for use in production? Do we want it for use in unit tests? I don't see a strong need in production due to the debug pages which already give you the dumps, unless we're worried about cases in which the debug endpoint isn't hooked up yet. I don't see a strong need in unit tests though if we wanted it there I wouldn't be opposed.

I'm also not generally opposed to this, but I do want to understand what the problem is we're solving, and I don't think anyone has stated one. Even the goal of not stopping the server when the goroutine is dumped isn't clearly requested; the initial post in the issue quotes @knz as saying that it doesn't matter whether the process stops or not.

**Comment by knz** [comment] 2019-04-02 09:50
So the use case is the following:

- I'm running some workload against a CockroachDB node
- the workload hangs
- the node doesn't respond (at least for a while)
- I want to know what's going on
- I don't want to stop the node, because my workload takes forever to initialize and I don't want to stop it all if it's going to resume on its own

Last time it happened was ~12 minutes into the SQLAlchemy test suite with Bram. (The stack trace enabled us to determine it was a txn deadlock. Yet being investigated.)

The time before was ~20 minutes into a manual import from `cockroach dump`. The stack trace enabled me to determine that it was just slow and I just had to wait.

The time before that was ~5 minutes into a stress unit test that just hung. There was no network endpoint.

I don't generally agree with the idea that "we have a debug page and therefore our work stops there". Getting a low level snapshot of what all the threads are doing is useful, I want to be able to do that even when the debug pages are not reachable (either because of network config, OR because the thing doesn't accept new connections, OR because it's locked up on a mutex somewhere.)

**Comment by knz** [comment] 2019-04-02 09:53
I do understand however that having this go through `util/log` and the logging mutex is bad because we have a logging mutex that may be taken already. That's why my linked PR is not yet complete. I'll have a further look.

**Comment by knz** [comment] 2019-08-02 02:49
I found a different way to achieve this than a signal. closing

**Closed by knz** 2019-08-02 02:49 UTC
Labels: C-bug
