### ISSUE TITLE
circleci: failed tests (13917): TestBuildInfo TestDockerJava 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4911] opened 2016-03-06 18:16 UTC
The following test appears to have failed:

[#13917](https://circleci.com/gh/cockroachdb/cockroach/13917):

```
I160306 18:12:48.734235 acceptance/replication_test.go:66  found 1 replicas
I160306 18:12:49.735964 acceptance/replication_test.go:66  found 1 replicas
I160306 18:12:50.737663 acceptance/replication_test.go:66  found 1 replicas
I160306 18:12:51.739266 acceptance/replication_test.go:66  found 1 replicas
I160306 18:12:51.839849 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestBuildInfo (63.58s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 1
=== RUN   TestDockerC
I160306 18:12:53.878712 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
....I160306 18:12:54.165048 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160306 18:12:54.678461 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.3
I160306 18:12:54.678507 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
--
I160306 18:15:03.037681 acceptance/replication_test.go:66  found 1 replicas
I160306 18:15:04.039258 acceptance/replication_test.go:66  found 1 replicas
I160306 18:15:05.041060 acceptance/replication_test.go:66  found 1 replicas
I160306 18:15:06.042868 acceptance/replication_test.go:66  found 1 replicas
I160306 18:15:06.143611 acceptance/cluster/localcluster.go:596  stopping
--- FAIL: TestDockerJava (91.41s)
	testing.go:170: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 1
=== RUN   TestDockerPHP
I160306 18:15:08.320382 acceptance/cluster/docker.go:72  ImagePull cockroachdb/docker-spy:20160209-143235 starting
....I160306 18:15:08.565545 acceptance/cluster/docker.go:87  ImagePull cockroachdb/docker-spy:20160209-143235 complete
I160306 18:15:09.055073 acceptance/cluster/localcluster.go:261  started docker-spy: 172.17.0.3
I160306 18:15:09.055121 acceptance/cluster/localcluster.go:268  Initializing Cluster:
Cluster Setup: AdHoc 3x1
Duration: 5s, Stall: 2m0s
Node 0 - Store 0
Node 1 - Store 0
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:66: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-06 20:37
Duplicate of #4894.

**Closed by petermattis** 2016-03-06 20:37 UTC
Labels: test-failure
