### ISSUE TITLE
sql: break gossip dep for table descriptors / table leases

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#47150] opened 2020-04-07 20:35 UTC
Table descriptors versions are leased by nodes. We ensure that at most, the latest two versions of a table are leased. Schema changes which increment the version of a table descriptor wait until all leases to previous versions of the table are dropped. Gossip is the mechanism by which nodes are informed of their need to drop the table descriptor. In order to make this work, we ensure that all DDL statements in explicit transactions occur as the first writing statement so that we can synthetically anchor the transaction record to the system config span (`(*kv.Txn).SetSystemConfigTrigger()`). 

This is an awkward restriction and should be lifted. 

```
ERROR: unimplemented: schema change statement cannot follow a statement that has written in the same transaction
SQLSTATE: 0A000
HINT: You have attempted to use a feature that is not yet implemented.
See: https://github.com/cockroachdb/cockroach/issues/26508
```

Additionally, this dependency on gossip is an impediment to separating the SQL layer from the gossip network.

**Comment by nvanbenschoten** [comment] 2020-05-13 03:57
@ajwerner should this be closed yet? You said in #48159 that the PR
> Relates to but does not fully resolve #47150. Another PR will follow-up and disable the gossip of the descriptors table and lift the enforcement of the system config transaction anchor.

**Comment by ajwerner** [comment] 2020-05-13 05:25
I suppose I should file a follow-up issue if I want to close this. It allows a nil gossip to be passed to the lease manager, or rather, it did until we introduced the `DeprecatedGossip` thing. Now, if a cluster is bootstrapped at 20.2, the lease manager should not ever look at gossip so the title of the issue is done.

**Comment by ajwerner** [comment] 2020-06-11 20:54
One thing claimed at the outset here was that we'd be able to stop gossipping the descriptor table. This unfortunately is not true given the way that the KV layer computes the zone config for a given key. We can stop gossipping namespace but it's so much smaller than descriptor it's not clear there's a win there. That's not to say that there isn't a win to be had here. We don't need to set the `SystemConfigTrigger` nearly as often. We only need to set it when writing zone configs, cluster settings, creating tables, and re-parenting tables. Not for any other table modifications.

@nvanbenschoten does this need to gossip the whole descriptor table make you as sad as it makes me? I don't really have a great set of alternatives. We could maintain a data structure that maps IDs to their parents which would likely be a couple of orders of magnitude smaller but still `O(descriptors)`.

If we weren't so constrained by the implementation we have today, what would we do? Would we attach zone configuration state to range state and then have some mechanism to reconcile mismatches between the expectation set at a global level and what exists at the range level?

**Comment by nvanbenschoten** [comment] 2020-06-11 21:08
> does this need to gossip the whole descriptor table make you as sad as it makes me?

Yes, especially as these descriptors grow and move through more complex state machines that cause them to be updated more frequently. If we can avoid setting the `SystemConfigTrigger` on all table modifications then I'd already be a lot happier.

> We could maintain a data structure that maps IDs to their parents which would likely be a couple of orders of magnitude smaller but still O(descriptors).

We'd also need to gossip the type of each descriptor to satisfy `sqlbase.ShouldSplitAtDesc`. We might be able to get a large portion of the way there just by stripping descriptor protos of unnecessary fields before putting them into the gossip network.

But that begs the question, what's the concern here? The size of the updates being communicated in the gossip network or the expense of the SystemConfigSpan's leaseholder needing to scan all of these keys on every descriptor update? I think it was actually the latter that [we've seen](https://github.com/cockroachdb/cockroach/issues/20753) cause issues in the past.

> Would we attach zone configuration state to range state and then have some mechanism to reconcile mismatches between the expectation set at a global level and what exists at the range level?

What would drive this reconciliation process? Sounds like a good task for gossip...

**Comment by ajwerner** [comment] 2020-06-11 21:18
> What would drive this reconciliation process? Sounds like a good task for gossip...

Perhaps. We could imagine that be dealt with by one of the queues. Perhaps the replication queue. Furthermore, we could imagine thinking of changes to zone configs taking effect as not a real time thing. In that case we could make replica state track not just the zone config that applies to it but the also the set of relevant descriptors and the timestamp at which the configuration was known to apply. Then perhaps with a rangefeed we could know with very little in-memory state whether there was a chance that a zone config had been invalidated and in need of being re-resolved.

This idea of changing the structure of zone configs and how they are mapped to replica is almost certainly out of the question for 20.2 but I'd love to start making our way towards a real improvement in 21.1. I'm using this thread for brainstorming at the moment. 

> But that begs the question, what's the concern here? The size of the updates being communicated in the gossip network or the expense of the SystemConfigSpan's leaseholder needing to scan all of these keys on every descriptor update? I think it was actually the latter that we've seen cause issues in the past.

This is a bummer that I'll only be minimally changing in this release. For an add-drop cycle on a table we currently public 3 different SystemConfigTrigger transactions. This will take it down to two as we don't need to publish one on the transaction which removes the table from namespace and marks it dropping.

**Comment by ajwerner** [comment] 2020-08-05 17:37
I'm closing this and will open a different issue for eliminating some of the calls to `SetSystemConfigTrigger`

**Comment by knz** [comment] 2020-09-11 10:19
@ajwerner please only re-close this after you've updated the remaining reference to this issue in the source code (in lease.go)

(we keep X-anchored-telemetry issues open until the product doesn't refer to them in "live" problems)

**Comment by ajwerner** [comment] 2021-09-22 12:33
The errors have been removed. I'm closing this in favor of the newer issue #70560 which covers the more general problem of not gossiping the system config span.

**Closed by ajwerner** 2021-09-22 12:33 UTC
Labels: A-multitenancy
