### ISSUE TITLE
Changes in casting values between 21.1 and 21.2 now incompatible with Postgres

### ISSUE THREAD

**Issue by smcvey** [cockroachdb/cockroach#78083] opened 2022-03-18 14:57 UTC
On version 21.1.16:

```
root@:26257/defaultdb> select * from generate_series('2022-01-01 00:00:00', '2022-01-03 00:00:00', '1 day'::interval);
    generate_series
-----------------------
  2022-01-01 00:00:00
  2022-01-02 00:00:00
  2022-01-03 00:00:00
(3 rows)
```

However, on version 21.2.7:

```
root@:26257/defaultdb> select * from generate_series('2022-01-01 00:00:00', '2022-01-03 00:00:00', '1 day'::interval);
ERROR: unknown signature: generate_series(string, string, interval)
SQLSTATE: 42883
```

As a comparison, this works on Postgres 14.2:

```
postgres=# select * from generate_series('2022-01-01 00:00:00', '2022-01-03 00:00:00', '1 day'::interval);
    generate_series     
------------------------
 2022-01-01 00:00:00+00
 2022-01-02 00:00:00+00
 2022-01-03 00:00:00+00
(3 rows)
```

Epic CRDB-2474
Jira issue: CRDB-13960

**Comment by rafiss** [comment] 2022-03-19 19:32
The reason for this is 723ded97a3 -- where we added support for the `generate_series(TIMESTAMPTZ, TIMESTAMPTZ, INTERVAL)` overload. Previously, CockroachDB only supported `generate_series(TIMESTAMP, TIMESTAMP, INTERVAL)`.

Unfortunately, this had an unintended consequence due to the abilities of the CockroachDB type resolution system. It can't figure out which of the two overloads to pick to automatically cast the strings. 

I believe the long-term fix for this would be to support implicit casts (see https://github.com/cockroachdb/cockroach/issues/75101). Perhaps @mgartner could confirm that would fix this.

Until then, the workaround is to add explicit casts to the arguments of the function.

**Comment by mgartner** [comment] 2022-03-21 19:50
> I believe the long-term fix for this would be to support implicit casts (see https://github.com/cockroachdb/cockroach/issues/75101). Perhaps @mgartner could confirm that would fix this.

I think two major things will be required to solve this. First, we'll need to type string literals initially as `unknown`. [PG Type Conversion Overview](https://www.postgresql.org/docs/14/typeconv-overview.html):

> If a type is not specified for a string literal, then the placeholder type unknown is assigned initially, to be resolved in later stages as described below.

Second, we'll need to match PG's function overload resolution. [PG Type Conversion - Functions] mentions this case specifically:

> If any input arguments are unknown, check the type categories accepted at those argument positions by the remaining candidates. At each position, select the string category if any candidate accepts that category. (This bias towards string is appropriate since an unknown-type literal looks like a string.) Otherwise, if all the remaining candidates accept the same type category, select that category; otherwise fail because the correct choice cannot be deduced without more clues. Now discard candidates that do not accept the selected type category. Furthermore, if any candidate accepts a preferred type in that category, discard candidates that accept non-preferred types for that argument. Keep all candidates if none survive these tests. If only one candidate remains, use it; else continue to the next step.

Implementing implicit casts won't solve the issue because there are no implicit casts from TEXT to TIMESTAMP[TZ]. But it's related to casts in a way. (We've been using the terms "implicit casts" and "assignment casts" to refer to the broader topic of "type conversion". I've reworded the issue you linked to so that there is a distinction between "type conversion" and the multiple pieces of that which include "assignment casts", "implicit casts", "function overload resolution", etc.)

**Comment by rafiss** [comment] 2024-06-04 18:57
I will close this as a duplicate of https://github.com/cockroachdb/cockroach/issues/75101

**Closed by rafiss** 2024-06-04 18:57 UTC
Labels: C-bug, O-support, T-sql-foundations, P-3
