### ISSUE TITLE
ui: SQL connection count mismatch

### ISSUE THREAD

**Issue by knutster** [cockroachdb/cockroach#14026] opened 2017-03-09 17:04 UTC
BUG:

[config]
I170309 11:12:51.969739 1 util/log/clog.go:999  [config] file created at: 2017/03/09 11:12:51
I170309 11:12:51.969739 1 util/log/clog.go:999  [config] running on machine: cockroach-2
I170309 11:12:51.969739 1 util/log/clog.go:999  [config] binary: CockroachDB CCL beta-20170223 (linux amd64, built 2017/02/23 16:30:53, go1.7.5)
I170309 11:12:51.969739 1 util/log/clog.go:999  [config] arguments: [cockroach start --ca-cert=/etc/cockroach/ca.cert --cert=/etc/cockroach/cockroach-2.**** --key=/etc/cockroach/cockroach-2.****.key --host=cockroach-2.**** --store=/mnt/ssd-1/cockroach --join=cockroach-3.****:26257 --locality=datacenter=us2]

We are operating a 3 node cluster.  They all have similar configs as to what you see above.  We have recently experimented with dist_sql=on and have experienced a 2 out of 3 node crash on the cluster.  Upon restarting all nodes and loading the cluster normally without any joins we see a discrepancy in connections being reported on the ui vs what can be observed via netstat:

![screen shot 2017-03-09 at 11 59 45](https://cloud.githubusercontent.com/assets/1041163/23761268/34e7ca2a-04c0-11e7-8e07-90b9a2b2a5f1.png)

Via netstat one observes the 6 expected connections:

```
cockroach@cockroach-2.us2:~$ netstat -tuplan | grep 26257 | grep 2.118
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 10.1.1.241:26257        10.1.2.118:45122        ESTABLISHED 8185/cockroach
tcp        0      0 10.1.1.241:26257        10.1.2.118:35184        ESTABLISHED 8185/cockroach
tcp        0      0 10.1.1.241:26257        10.1.2.118:54144        ESTABLISHED 8185/cockroach
tcp        0      0 10.1.1.241:26257        10.1.2.118:54122        ESTABLISHED 8185/cockroach
tcp        0     54 10.1.1.241:26257        10.1.2.118:54046        ESTABLISHED 8185/cockroach
tcp        0    137 10.1.1.241:26257        10.1.2.118:54090        ESTABLISHED 8185/cockroach
tcp        0      0 10.1.1.241:26257        10.1.2.118:54064        ESTABLISHED 8185/cockroach
```

**Comment by petermattis** [comment] 2017-03-09 18:20
@asubiotto Can you take a look at this given your recent interaction with the pgwire code? Seems like something isn't recognizing when a pgwire connection goes away.

**Comment by asubiotto** [comment] 2017-03-10 15:46
I haven't been able to reproduce this issue with the same scenario. @knutster, as discussed, could you attempt to reproduce this, go to `<node address>:<admin port>/debug` while the non-existent connections are being reported and share the output of `goroutine (all)`?

I also remember you mentioned you were using `haproxy` in front of the cluster. Are you by any chance using SQL level health checks?

**Comment by knutster** [comment] 2017-05-10 14:37
@asubiotto, no I haven't been using SQL health checks.  I am not able to reproduce on this end either, I think it was an extreme edge case!  I'm going to stop expending effort to reproduce and can re-open this if I run across the issue again.

**Comment by asubiotto** [comment] 2017-05-10 15:03
@knutster Thanks for spending time on trying to reproduce this! Sounds good.

**Comment by mrtracy** [comment] 2017-07-17 04:53
Moved to later milestone, @asubiotto should this just be closed since it couldn't be reproduced?

**Comment by asubiotto** [comment] 2017-07-17 14:20
Closing and will reopen if this comes up again. Thanks @mrtracy

**Closed by asubiotto** 2017-07-17 14:20 UTC
Labels: priority
