### ISSUE TITLE
storage: use sensible zone configs for critical system and time series ranges

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#14990] opened 2017-04-17 17:12 UTC
While it makes sense for small clusters, our current default zone configuration that only creates 3 replicas of all data by default is somewhat risky for large clusters, where it may be preferable to keep more than 3 replicas of critical system ranges.

This can be addressed via documentation for 1.0 (https://github.com/cockroachdb/docs/issues/1280, https://github.com/cockroachdb/docs/issues/1248), but before 1.1 we should do some testing with different configurations and consider setting more replicas of the system ranges by default.

**Comment by tschottdorf** [comment] 2017-06-16 18:37
A sensible choice would be to replicate these ranges with factor `max(min(nodes_in_cluster, 5), highest_replication_factor_for_any_zone)`. By that token, you could be assured that if you run a range with, say,  x11, you can actually tolerate 5 dead replicas (and not just whatever the critical system ranges top out at).

**Comment by tschottdorf** [comment] 2017-06-16 22:12
via @bdarnell:

yeah. we should eventually move to more fine-grained defaults for different system sub-ranges (high replication factor and long ttl for range metadata, high replication and low ttl for liveness, low replication for timeseries)

**Comment by bdarnell** [comment] 2017-06-20 19:27
The `.system` special zone currently includes too much. It has both the liveness span (which wants to have a short TTL) and the system descriptor/namespace tables (which need to have a TTL at least as high as the TTL for any other table. Time travel queries are limited to the *shorter* of the TTLs of the table itself and the table descriptor tables).

**Comment by cuongdo** [comment] 2017-08-22 20:40
@petermattis this seems like a risky change at this point; should this move to 1.2?

**Comment by bdarnell** [comment] 2017-08-22 20:43
Yes, we already agreed to move this to 1.2 in #17628

**Comment by bdarnell** [comment] 2018-02-08 19:50
We've done most of this: splitting `.system` into sub-zones, and giving better default TTLs. The only thing that remains is to (maybe) use a higher replication factor for meta and liveness.

**Comment by tschottdorf** [comment] 2018-05-24 23:11
Is it the "right thing" to move to "adaptive"  replication factors? Adaptive meaning we get to put, say, a special value "up_to(5)` (mod bikeshed) and the allocator will attempt to upreplicate to 5 copies as long as there are enough nodes in the cluster (and will also downreplicate to 3 as nodes die without complaining about under-replication after).

**Comment by bdarnell** [comment] 2018-05-28 16:27
> Is it the "right thing" to move to "adaptive" replication factors?

Probably, although there are some subtleties. If we only use this `up_to(5)` configuration on the system ranges, would they be lower-priority for recovery than regular ranges that just specify `5`? That's the opposite of what we want. 

Maybe all zone configs should be "adaptive" in this way. We already kind of do this in that the default replication factor is 3 but we support running single-node clusters (with logged complaints). The main reason we don't do this is that we don't want a cluster that is only temporarily larger than 3 nodes to get stuck in a problematic state, but I'm not sure this is as big a problem as we've thought. You need to decommission the outgoing nodes in order to make the transition safe anyway. The only thing we'd need to change is the safeguard that we won't reduce a range below its target replication factor when decommissioning. If we permitted this under some circumstances (letting the replication factor go as low as 3 as long as it is using every non-decommissioned node), it might be OK to make the default replication factor for the system ranges 5.

**Comment by tschottdorf** [comment] 2018-05-29 18:13
Good point about decommissioning.

I was thinking that the way to expose "adaptive ranges" is to split the replication factor into `min_replicas` and `max_replicas` (where typically min=max=3 and system ranges would have min=3, max=5). We could then say that a range is `(3,5)@5`-replicated (meaning it wants between three and five replicas, currently has five).

The code in the allocator is straightforward (?) until we deal with dead/decommissioning nodes. For example, if a `(3,5)@5` range has a dead node, and the allocator can't find suitable targets for a lateral move of that replica (i.e. the cluster only had five nodes to begin with), the allocator would try to make it a `(3,5)@3` range instead. This might be a little too aggressive because a `(3,5)@5` range with a down node is no worse than a `(3,3)@3` range, so we could predicate that process on the down node being decommissioned. But I think that's a bit dangerous because if users generally lose nodes every now and then but don't decommission them, they'll eventually kill their adaptive-replicated ranges. Besides, you don't want metrics to alert for extended periods of time until the allocator decides to downreplicate, and we don't want an extra knob to tune unless it's truly useful.

**Comment by tschottdorf** [comment] 2018-06-14 08:41
@bdarnell is the above in line with how you'd expect adaptive replication factors to be implemented? I'm not in love with the `min,max` nomenclature since the allocator will in general gravitate towards `max` when it gets a chance. Maybe just `min_replicas` and `replicas` or `target_replicas`.

I'd like to figure out what we're going to do here and in https://github.com/cockroachdb/cockroach/issues/24430 soon so that we can start working on a solution.

**Comment by bdarnell** [comment] 2018-06-15 19:29
My question about the `min_replicas` nomenclature is whether it makes sense for this to be configurable, or is it just how all zones should work when there aren't enough nodes? If it's just how things work, then we don't have a separate threshold we need to name.

My strawman proposal:
- Set default zone config for system zones to `replicas: 5`
- Allow the allocator to downreplicate from higher replication factors to 3 when there are not enough live nodes to reach the higher number
- Handle the UI/Alerting problem with special cases in the upper layers: Don't complain about under-replicated system ranges if there are only three nodes
- In the long term, encourage admins of single-node and three-node clusters to explicitly say so, maybe as a part of #15301.

**Comment by tschottdorf** [comment] 2018-07-17 15:45
We talked about this in the weekly today and came to the conclusion that the biggest problem at hand is that zone configs don't "cascade". For example, take a `.default` zone config that specifies `replicas: 3`. Now specify a zone config for `.liveness` that specifies `ttl: 1h`. Now change `.default` to specify `replicas: 5`. Naively you expect `replicas: 5` to apply to the `.liveness` range, as it's a subzone of `.default` and has never explicitly had a replication factor specified. But this isn't true, it remains at three. The reason is that the zone config which is persisted for a zone is fully populated at creation time. That is, we store `replicas: 3` instead of `replicas: not specified, use the parents'`.

In particular, in setting up specialized zone configs for the system ranges in the first place (without specifying an explicit replication factor for them), we set ourselves up for the hairy problem that when a user explicitly asks for global 5x replication via the `.default` zone, the system ranges will continue to use 3x unless overridden individually.

I'm not very familiar with the code, but this seems like it could be hairy to fix in that generality. For example, we already use zone configs with a zero replication factor as indicating a "subzone placeholder":

```go
func (z *ZoneConfig) IsSubzonePlaceholder() bool {
	// A ZoneConfig with zero replicas is otherwise invalid, so we repurpose it to
	// indicate that a ZoneConfig is a placeholder for subzones rather than
	// introducing a dedicated IsPlaceholder flag.
	return z.NumReplicas == 0
}
```

There's also a mild migration concern in that these changes wouldn't solve the problem for existing clusters. But this could be worked around via manual steps and documented.

The other, more targeted option is to slap special logic into the allocator that basically says "for the system ranges, use the maximum replication factor seen in any other zone". This looks like it'd be easier to implement. On the negative side, it's a wart and also results in semantics that are hard to explain, and which may necessitate further incisions to avoid setting an explicit replication factor on these system ranges.

@a-robinson, am I overestimating how hard the first option is?

Once the "cascading" is set and done, the adaptive allocator might still be a good idea because it allows us to bump the `replicas` for the `.default` zone config to 5 (or even 7) without having to deal with alerts going off when the cluster has fewer nodes than that. But cascading seems like the bigger, more immediate, problem.

**Comment by bdarnell** [comment] 2018-07-18 01:49
> the adaptive allocator might still be a good idea because it allows us to bump the replicas for the .default zone config to 5 (or even 7) without having to deal with alerts going off when the cluster has fewer nodes than that. 

That's not how I see the benefits of the adaptive allocator (for one thing, increasing the default replication factor is a very expensive change, and I believe it's something that an operator should explicitly opt in to, unless we're saying that the risk of two simultaneous failures is high enough that it's unwise to run with only three replicas). 

The goal (as implemented in #2734) is to make it easier (in fact, the default) for critical system ranges to have more replicas than the data ranges (the alternative of "use the highest replication factor from any zone", in addition to its hackiness, doesn't provide this benefit, and neither does cascading). Is that important? It has its limitations, since the loss of two nodes can still result in loss of the 3x-replicated data ranges (and we cannot currently recover from this if the loss is permanent). However, it still offers some value. First, it ensures that a (temporary) two-node outage only affects some data ranges, instead of knocking out the entire cluster if it happens to strike two replicas of the liveness range. Second, in the future when/if we have a better ability to recover from the loss of a data range, this will most likely require that the system ranges remain available (this is admittedly speculative).

Cascading zone configs is a clean solution to the "setting `.default` doesn't have the desired effect", both for system ranges and for userspace `.default`/db/table/partition hierarchies. But the adaptive allocator can also solve the problem for system ranges (with the assumption that 5x or 7x replication will be enough for any realistic scenario), so I think (contrary to my comments this morning) that it could still be worth doing given its ease of implementation relative to cascading.

**Comment by a-robinson** [comment] 2018-07-18 18:05
> @a-robinson, am I overestimating how hard the first option is?

It will be hairy, but doable. We'll have to change how subzone placeholders are recognized, make it possible to unset individual fields in a zone config, change the code paths for reading zones to also read the parent zones when necessary, change a bunch of documentation and tests, and some other minor things.

It'll also create new edge cases we have to think about and handle. For example, if the zone for database `foo` sets `NumReplicas: 5`, then table `foo.bar` sets `Constraints: {'region=west': 2, 'region=east': 2, 'region=central': 1} without setting `NumReplicas` for `foo.bar`, then it would be illegal to reduce `foo`'s `NumReplicas` below 5, so we'll have to check a zone's children for certain conditions when changing the parent in certain ways.

On the plus side, all the changes should be localized just in the `config` package. The logic for getting/setting zones is pretty well contained there, except for maybe a little bit of leakage into the sql statement for modifying them.

> Cascading zone configs is a clean solution to the "setting .default doesn't have the desired effect", both for system ranges and for userspace .default/db/table/partition hierarchies. But the adaptive allocator can also solve the problem for system ranges (with the assumption that 5x or 7x replication will be enough for any realistic scenario), so I think (contrary to my comments this morning) that it could still be worth doing given its ease of implementation relative to cascading.

I'm happy with this. I'm still not 100% confident that the "adaptive" logic will always play nice with cascading, but both a clear improvement overall.

**Comment by tschottdorf** [comment] 2018-08-21 16:25
Filed https://github.com/cockroachdb/cockroach/issues/28901 to track cascading zone configs.

**Comment by petermattis** [comment] 2018-10-04 13:51
@m-schneider Is there anything left to do here?

**Comment by m-schneider** [comment] 2018-10-04 14:43
No, closing.

**Comment by tschottdorf** [comment] 2018-10-08 09:59
I'm a bit confused. I assume that https://github.com/cockroachdb/cockroach/pull/27349 is the PR that closes this issue (though it didn't refer it prior to this commit).

That PR is sparse on description, but from the code it *looks* like what should happen is that if I set up a new five node cluster, I'll get my critical system ranges 5x replicated.

That doesn't seem to be the case:

```
root@:26257/> select * from crdb_internal.ranges;
  range_id |     start_key     |         start_pretty          |      end_key      |          end_pretty           | database |      table       | index | replicas | lease_holder
+----------+-------------------+-------------------------------+-------------------+-------------------------------+----------+------------------+-------+----------+--------------+
         1 |                   | /Min                          | \004              | /System/""                    |          |                  |       | {1,4,5}  |            1
         2 | \004              | /System/""                    | \004\000liveness- | /System/NodeLiveness          |          |                  |       | {1,3,2}  |            1
         3 | \004\000liveness- | /System/NodeLiveness          | \004\000liveness. | /System/NodeLivenessMax       |          |                  |       | {1,3,5}  |            3
         4 | \004\000liveness. | /System/NodeLivenessMax       | \004tsd           | /System/tsd                   |          |                  |       | {4,5,3}  |            4
         5 | \004tsd           | /System/tsd                   | \004tse           | /System/"tse"                 |          |                  |       | {4,5,3}  |            5
         6 | \004tse           | /System/"tse"                 | \210              | /Table/SystemConfigSpan/Start |          |                  |       | {1,3,2}  |            1
         7 | \210              | /Table/SystemConfigSpan/Start | \223              | /Table/11                     |          |                  |       | {1,3,2}  |            1
         8 | \223              | /Table/11                     | \224              | /Table/12                     | system   | lease            |       | {1,5,2}  |            2
         9 | \224              | /Table/12                     | \225              | /Table/13                     | system   | eventlog         |       | {4,3,2}  |            2
        10 | \225              | /Table/13                     | \226              | /Table/14                     | system   | rangelog         |       | {5,4,2}  |            4
        11 | \226              | /Table/14                     | \227              | /Table/15                     | system   | ui               |       | {1,2,3}  |            1
        12 | \227              | /Table/15                     | \230              | /Table/16                     | system   | jobs             |       | {5,4,2}  |            5
        13 | \230              | /Table/16                     | \231              | /Table/17                     |          |                  |       | {1,3,4}  |            3
        14 | \231              | /Table/17                     | \232              | /Table/18                     |          |                  |       | {4,5,2}  |            5
        15 | \232              | /Table/18                     | \233              | /Table/19                     |          |                  |       | {1,2,4}  |            2
        16 | \233              | /Table/19                     | \234              | /Table/20                     | system   | web_sessions     |       | {1,5,3}  |            3
        17 | \234              | /Table/20                     | \235              | /Table/21                     | system   | table_statistics |       | {1,5,2}  |            2
        18 | \235              | /Table/21                     | \236              | /Table/22                     | system   | locations        |       | {1,3,2}  |            1
        19 | \236              | /Table/22                     | \237              | /Table/23                     |          |                  |       | {4,5,2}  |            2
        20 | \237              | /Table/23                     | \377\377          | /Max                          | system   | role_members     |       | {4,3,5}  |            5
(20 rows)

Time: 29.585ms

warning: no current database set. Use SET database = <dbname> to change, CREATE DATABASE to make a new database.
root@:26257/> select * from crdb_internal.gossip_liveness;
  node_id | epoch |       expiration       | draining | decommissioning
+---------+-------+------------------------+----------+-----------------+
        1 |     1 | 1538992670.035649687,0 |  false   |      false
        2 |     1 | 1538992670.740451009,0 |  false   |      false
        3 |     1 | 1538992671.575627883,0 |  false   |      false
        4 |     1 | 1538992672.506993000,0 |  false   |      false
        5 |     1 | 1538992673.226969883,0 |  false   |      false
(5 rows)
```

@m-schneider are my assumptions wrong? What should happen in my situation?

**Comment by m-schneider** [comment] 2018-10-08 15:09
Taking a look.

**Comment by tschottdorf** [comment] 2018-10-08 15:29
I used `roachdemo` and clicked the add button in the ui five times :-)

**Comment by tschottdorf** [comment] 2018-10-08 15:30
Let me try that again.. it'd be puzzling if that made a difference.

**Comment by tschottdorf** [comment] 2018-10-08 15:39
Hrm. Unfortunately, it behaves as advertised now. I wonder what the difference was? How's our test coverage for this?

**Comment by m-schneider** [comment] 2018-10-08 16:33
We have pretty extensive testing in allocator_test.go for various combinations of available vs alive nodes.

**Comment by a-robinson** [comment] 2018-10-08 16:44
That doesn't necessarily mean that it always works end-to-end, though.

@tschottdorf do you know which version of cockroach you were on and whether roachdemo was resuming a preexisting cluster or if it initialized a new one? If the cluster was initialized before https://github.com/cockroachdb/cockroach/pull/27349 / https://github.com/cockroachdb/cockroach/pull/30480 then you wouldn't see the new behavior regardless of which version you were using.

**Comment by m-schneider** [comment] 2018-10-10 15:10
I haven't been able to reproduce after a couple of attempts and after using roachdemo. Should we close for now? If you see this again can you please run:
```select * from crdb_internal.kv_store_status;```

**Comment by tschottdorf** [comment] 2018-10-10 20:04
@a-robinson I looked after reading your comment two days ago but the buffer had been lost. I also gave this a a few more rounds but it just worked. Still very weird. I `make build` pretty regularly, though perhaps I had a stray cockroach binary from a release branch that I used by accident.
Sorry about the noise!

**Closed by tschottdorf** 2018-10-10 20:04 UTC
Labels: A-core-kv, C-enhancement, S-2-temp-unavailability, docs-todo
