### ISSUE TITLE
Trying to sent a batch to decommissioned node results in Ambiguous error

### ISSUE THREAD

**Issue by darinpp** [cockroachdb/cockroach#47460] opened 2020-04-14 00:48 UTC
**Describe the problem**

Trying to send a batch to decommissioned node results in Ambiguous error. 

**To Reproduce**
- from n2 access a range on n1
- decommission n1 (making sure the range doesn't rebalance to n2)
- try to access the same range from n2 

In this case n2 will use a stale descriptor and try to access n1. The error that was reported in this case is:
```
ERROR: result is ambiguous (error=failed to connect to n2 at ...: initial connection heartbeat failed: operation "rpc heartbeat" timed out after 6s: rpc error: code = DeadlineExceeded desc = context deadline exceeded [exhausted]);
```
This will only happen once as the range descriptor will be updated after the first request. 

**Expected behavior**
The error should not be Ambiguous. 

**Additional data / screenshots**
It seems that we were not able to distinguish well at some point if the batch was sent or not - see here https://github.com/cockroachdb/cockroach/blob/c3068495c20fa8d29e2cdfc73419feccfd5bc185/pkg/util/grpcutil/grpc_util.go#L93

**Environment:**
 - CockroachDB version 19.2.5
 - Server OS: ubuntu bionic
 - Client app

**Additional context**
The client sees an error and has to retry. This should not be needed.

**Comment by erikgrinaker** [comment] 2021-06-18 16:48
@aliher1911 I believe #66199 should have fixed this, can you confirm?

**Comment by aliher1911** [comment] 2021-06-18 19:26
Superficially is looks different. I need to dig on what was happening in 19.x and if heartbeat shorcutting locally for decommissioned nodes was added in 20.x. Otherwise we still wouldn't recognize this error as non ambiguous.

**Comment by aliher1911** [comment] 2021-06-21 17:04
In 19.1 there's no shortcut yet to preemptively block communication with decommissioned node and hence no check for those kind of errors:
https://github.com/cockroachdb/cockroach/blob/master/pkg/rpc/context.go#L1061-L1063

On current 21.1 we should have authentication error which would result in non ambiguous error, but still a failure without a retry in all cases, with the latest fix on master it should retry cleanly now.

I tried this test:
https://gist.github.com/aliher1911/82214d52a3fd4a74e5384475c080b64b
and with current code it retries just fine. Also tried to revert error to always be Auth Error and it fails unexpectedly when trying to run a query. Can't get ambiguous error though.
And with PreconditionFailed in place it always succeeds to write and read.
Mind that if I don't loop to wait for all ranges to move off decommissioned nodes, all hell breaks loose and it gets into endless retries for minutes because it tries to move leases non-cooperatively I think.

All in all the problem seem resolved.

**Comment by erikgrinaker** [comment] 2021-06-21 18:35
Great, thanks for checking! We can close this issue then.

>Mind that if I don't loop to wait for all ranges to move off decommissioned nodes, all hell breaks loose and it gets into endless retries for minutes because it tries to move leases non-cooperatively I think.

Uhm, this seems bad. Is this because you're sending requests to the decommissioned node itself, and so that node starts having problems? It should bail out due to `PermissionDenied` error instead of retrying indefinitely, but it will spew tons of log noise as it tries to reach the cluster.

**Comment by aliher1911** [comment] 2021-06-24 11:24
I did another go on it to verify and It seem very similar to what was happening in #47459. Current error handling in 21.x should take care of interaction with decommissioned node and retrying. What Andrei was mentioning in the other issue that we should only see that if ranges are stale and don't refresh, but it is not easily reproducible with a simple test like that.

As for decommissioning without draining it is noisy because there would be some noise in the logs in the process, but time wise it seem to work just fine so I'll close this issue as well.

If we see this behaviour again we'll open new one.

**Closed by aliher1911** 2021-06-24 11:24 UTC
Labels: A-kv-client, A-kv-decom-rolling-restart, T-kv
