### ISSUE TITLE
Test failure in CI build 9778

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3290] opened 2015-12-02 19:47 UTC
The following test appears to have failed:

[#9778](https://circleci.com/gh/cockroachdb/cockroach/9778):

```
W1202 19:47:04.416992 937 storage/store.go:1354  conflicting intents on [/Local/Range/RangeDescriptor/"\xff\f\x03\xe8YxwuEyHEJPgFqJnBjubtvhOLWFMdlHHyMZzugInzXqHDYNXIPTtJBttpCHLqFwYhHjVyCFuJrGnOQxJunBvGMaUOxZzruJGwNWLP"]: resolved? true
W1202 19:47:04.421307 937 storage/store.go:1354  conflicting intents on [/Local/Range/RangeDescriptor/"\xff\f\x03\xe8"]: resolved? true
I1202 19:47:04.423083 937 client/db.go:483  failed batch: node unavailable; try another peer
E1202 19:47:04.423326 937 storage/queue.go:374  failure processing replica range=2 [/Table/1000-/Max) from split queue: storage/replica_command.go:1326: split at key /Table/1000/"YxwuEyHEJPgFqJnBjubtvhOLWFMdlHHyMZzugInzXqHDYNXIPTtJBttpCHLqFwYhHjVyCFuJrGnOQxJunBvGMaUOxZzruJGwNWLP" failed: node unavailable; try another peer
I1202 19:47:04.423994 937 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- FAIL: TestStoreZoneUpdateAndRangeSplit (53.09s)
	client_split_test.go:493: expected range to split within 1s
=== RUN   TestStoreRangeSplitWithMaxBytesUpdate
I1202 19:47:04.425003 937 gossip/gossip.go:172  gossiping node descriptor node_id:1 address:<network_field:"localhost" address_field:"1" > attrs:<> 
I1202 19:47:04.427278 937 multiraft/multiraft.go:566  node 1 starting
I1202 19:47:04.428076 937 storage/replica.go:1308  gossiping cluster id  from store 1, range 1
I1202 19:47:04.428721 937 raft/raft.go:409  [group 1] 1 became follower at term 5
I1202 19:47:04.428896 937 raft/raft.go:218  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1202 19:47:04.429083 937 multiraft/multiraft.go:980  node 1 campaigning because initial confstate is [1]
I1202 19:47:04.429245 937 raft/raft.go:489  [group 1] 1 is starting a new election at term 5
I1202 19:47:04.429363 937 raft/raft.go:422  [group 1] 1 became candidate at term 6
--
I1202 19:47:07.798372 937 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
I1202 19:47:07.798490 937 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestLeaderAfterSplit (0.24s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.40s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	81.639s
=== RUN   TestBatchBasics
I1202 19:46:07.678589 997 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1202 19:46:07.682923 997 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1202 19:46:07.688678 997 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-12-02 22:03
Duplicate of #3219

**Closed by bdarnell** 2015-12-02 22:03 UTC
Labels: test-failure
