### ISSUE TITLE
importccl: Import feature not working with minio s3 storage server

### ISSUE THREAD

**Issue by sahlex** [cockroachdb/cockroach#21412] opened 2018-01-12 07:28 UTC
Cockroach version:
     
    Build Tag:    v2.0-alpha.20171218
    Build Time:   2017/12/18 21:54:11
    Distribution: CCL
    Platform:     linux amd64
    Go Version:   go1.9
    C Compiler:   gcc 6.3.0
    Build SHA-1:  e23cfcc1f16d18800b9a9855124fdf84fbf47466
    Build Type:   release-gnu

Cluster is started this way:

    ./cockroach start --insecure --store=/data/roach/roach1&
    ./cockroach start --insecure --store=/data/roach/roach2 --port=26258 --http-port=8081 --join=localhost:26257&
    ./cockroach start --insecure --store=/data/roach/roach3 --port=26259 --http-port=8082 --join=localhost:26257&

I'm trying to use the IMPORT feature of CRDB v2.0-alpha.20171218 . To mimic an s3 service I'm using a minio docker image offering s3 compatible interface (so they say) .

I've created all the necessary buckets with the minio UI and checked tham with minio `mc` console.

I'm calling the import command from cockroach sql console like this:

`import table "user" (pkuserid int4,  username varchar(40), bmcno varchar(16), personno varchar(45),                                                                                                                   cspid int8, customerno varchar(40), userLevel int2, banneduntil timestamp, tokenrequired bool,  failedloginattempts int2, loginemail varchar(80), title varchar(20), firstname varchar(80), lastname varchar(80), street varchar(120), zipcode varchar(10), city varchar(80), countrycode varchar(3), privatephone varchar(30), businessphone varchar(30), privatefax varchar(30), businessfax varchar(30),                                                                                                                privatemobile varchar(30), businessmobile varchar(30), privateemail varchar(80), businessmail varchar(80), admintype int2, active bool, lastsuccessfullogin timestamp, salt text, pwhash text) csv data ('s3://s3.dev.net:9001/temp/users_20180109.csv?AWS_ACCESS_KEY_ID=testtest&AWS_SECRET_ACCESS_KEY=testtest&AWS_REGION=us-east-1') with                                                                                                                                      temp = 's3://import-temp/?AWS_ACCESS_KEY_ID=testtest&AWS_SECRET_ACCESS_KEY=testtest&AWS_REGION=us-east-1&AWS_ENDPOINT=s3.dev.net:9001', delimiter = ',', comment = '#', nullif = 'null';`

However, after 1-2 seconds it gives me an error message:
> pq: cannot write to s3://import-temp/?AWS_ACCESS_KEY_ID=testtest&AWS_SECRET_ACCESS_KEY=testtest&AWS_REGION=us-east-1&AWS_ENDPOINT=s3.dev.net:9001: failed to put s3 object: RequestError: send request failed
caused by: Put https://import-temp.s3.dev.net:9001/BACKUP-CHECKPOINT: EOF

where I set s3.dev.net and import-temp.s3.dev.net in /etc/hosts to point to my minio server.
There is no error in the CRDB logs. 
Minio logs shows several times this message:

    time="2018-01-12T07:36:49Z" level=error msg="Received non-HTTP message from new connection 172.17.42.50:60814 at server 172.21.0.2:9000" cause="junk message" source="[listener.go:210:github.com/minio/minio/pkg/http.(*httpListener).start.func2()]"
t

**Comment by knz** [comment] 2018-01-29 21:08
cc @cockroachdb/sql-ccl -

**Comment by dt** [comment] 2018-01-29 21:15
Whoops, sorry, missed this, @sahlex 

I'll try this out and see if I can reproduce it -- the `non-http` message from minio makes me wonder if one side is trying to use TLS or something.

**Comment by ramkumarkb** [comment] 2018-02-18 14:35
@dt : I asked the Minio team about this error and this is what [@vadmeste](https://github.com/vadmeste) had to say about this issue:

> that error means Minio didn't receive an http request, which most likely means that a client sent a https request but Minio is not configured with a tls certificate

**Comment by dt** [comment] 2018-02-18 15:40
Thanks for looking into this @ramkumarkb! That sounds very likely -- the s3 client library (we use the official one from aws) is going to use https be default when expanding the hostname provided in the endpoint parameter to a full URL. You can avoid this by instead passing the full URL yourself in the endpoint parameter, with the `http` scheme and all -- but note that this really means the _full_ URL, including the bucket name in the endpoint path. For example, I'm running minio locally and have made a bucket `s3test` and updated my `hosts` file to resolve `s3test.localhost` as well, so my URI for BACKUP/IMPORT looks like. `'s3://s3dev/bar?AWS_ACCESS_KEY_ID=...&AWS_SECRET_ACCESS_KEY=...&AWS_REGION=us-east-1&AWS_ENDPOINT=http%3A%2F%2Flocalhost%3A9000%2Fs3dev'`

Does that help?

**Comment by dt** [comment] 2018-02-18 16:04
@mjibson it's possible we should flip on [`S3ForcePathStyle`](https://github.com/aws/aws-sdk-go/blob/master/aws/config.go#L126) when we see a custom endpoint, or at least a full URL one?

**Comment by vivekmenezes** [comment] 2018-07-23 17:05
@dt can we close this issue?

**Comment by mjibson** [comment] 2018-07-23 18:45
@dt it does look like S3ForcePathStyle would help (although wouldn't have fixed this issue). I'm not sure it's worth adding an issue for it until someone actually sees it thought? Like maybe minio already handles this case? Unclear.

**Closed** 2018-08-08 23:38 UTC
Labels: C-enhancement, O-community, S-3-ux-surprise, docs-todo
