### ISSUE TITLE
opt: could not decorrelate subquery

### ISSUE THREAD

**Issue by springe2004** [cockroachdb/cockroach#68086] opened 2021-07-27 01:59 UTC
```sql
SELECT
    typ.oid AS typoid,
    nspname,
    relname,
    attname,
    attrelid,
    attnum,
    attnotnull,
    attidentity != '' AS isidentity,
    CASE
    WHEN typ.typtype = 'd' THEN typ.typtypmod
    ELSE atttypmod
    END
        AS typmod,
    CASE
    WHEN atthasdef
    THEN (
        SELECT
            pg_get_expr(adbin, cls.oid)
        FROM
            pg_attrdef
        WHERE
            adrelid = cls.oid AND adnum = attr.attnum
    )
    ELSE NULL
    END
        AS default,
    CASE
    WHEN col.is_updatable = 'YES' THEN true
    ELSE false
    END
        AS is_updatable,
    EXISTS(
        SELECT
            *
        FROM
            pg_index
        WHERE
            pg_index.indrelid = cls.oid
            AND pg_index.indisprimary
            AND attnum = ANY indkey
    )
        AS isprimarykey,
    EXISTS(
        SELECT
            *
        FROM
            pg_index
        WHERE
            pg_index.indrelid = cls.oid
            AND pg_index.indisunique
            AND pg_index.indnkeyatts = 1
            AND attnum = pg_index.indkey[0]
    )
        AS isunique
FROM
    pg_attribute AS attr
    JOIN pg_type AS typ ON attr.atttypid = typ.oid
    JOIN pg_class AS cls ON cls.oid = attr.attrelid
    JOIN pg_namespace AS ns ON ns.oid = cls.relnamespace
    LEFT JOIN information_schema.columns AS col ON
            col.table_schema = nspname
            AND col.table_name = relname
            AND col.column_name = attname
WHERE
    atttypid != 0
    AND relkind IN ('r', 'v', 'm')
    AND NOT attisdropped
    AND nspname NOT IN ('pg_catalog', 'information_schema')
    AND attnum > 0
    AND (
            (attr.attrelid = 557 AND attr.attnum = 1)
            OR (attr.attrelid = 557 AND attr.attnum = 2)
            OR (attr.attrelid = 557 AND attr.attnum = 3)
            OR (attr.attrelid = 557 AND attr.attnum = 4)
            OR (attr.attrelid = 557 AND attr.attnum = 5)
            OR (attr.attrelid = 557 AND attr.attnum = 6)
            OR (attr.attrelid = 557 AND attr.attnum = 7)
            OR (attr.attrelid = 557 AND attr.attnum = 8)
            OR (attr.attrelid = 557 AND attr.attnum = 9)
            OR (attr.attrelid = 557 AND attr.attnum = 10)
            OR (attr.attrelid = 557 AND attr.attnum = 11)
            OR (attr.attrelid = 557 AND attr.attnum = 12)
            OR (attr.attrelid = 557 AND attr.attnum = 13)
            OR (attr.attrelid = 557 AND attr.attnum = 14)
            OR (attr.attrelid = 557 AND attr.attnum = 15)
            OR (attr.attrelid = 557 AND attr.attnum = 16)
            OR (attr.attrelid = 557 AND attr.attnum = 17)
            OR (attr.attrelid = 557 AND attr.attnum = 18)
        )
ORDER BY
    attnum;
```

**Comment by rafiss** [comment] 2021-07-27 03:48
@springe2004 -- could you please share a bit more information? what were you doing when this error happened? where is the query you shared coming from? are you using a tool that creates that query? which version of CockroachDB are you using?

**Comment by rafiss** [comment] 2021-07-28 15:33
I'll close this as a duplicate of https://github.com/cockroachdb/cockroach/issues/67951 but let me know if you find that it's actually a different problem.

**Closed by rafiss** 2021-07-28 15:33 UTC
Labels: C-bug, O-community, T-sql-queries, X-blathers-triaged
