### ISSUE TITLE
server: decommissioning with replication factor one causes outage

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#27025] opened 2018-06-27 17:34 UTC
Is this a question, feature request, or bug report?

**BUG REPORT**

Feature request to disallow dropping replication factor to 1 in multi-node cluster is here: #27026 

Logs to be provided. Reported by user leonardo on the forum: https://forum.cockroachlabs.com/t/node-decommissioned-but-2-ranges-are-broken-unavailable/1786

2. Please describe the issue you observed:

- What did you do?
In a 6 node cluster, reduced replication factor to 1 and decommissioned node. Node reported decommissioning complete, but two ranges are still leased to the node.

- What did you expect to see?
No ranges leased to node, stopping the node has no impact on data availability.

- What did you see instead?
Stopping the node results in unavailable ranges.

**Comment by leofiore** [comment] 2018-06-27 21:21
Hi,

i am OP of the post related to this issue. As suggested by @tim-o i attached the  [log of the failing decommissioned node ](https://github.com/cockroachdb/cockroach/files/2142937/node_2.log). You can see the decommissioning process taking place and some eventual goroutines failing during the process.

**Comment by tschottdorf** [comment] 2018-06-28 16:36
Thank you for your report. I think that fundamentally the problem is that the first step in the decommissioning process is entering draining mode, in which leases won't be renewed.

I agree that this isn't working as intended and it doesn't seem difficult to fix (famous last words): right now the node starts draining when it discovers that it's decommissioning. In doing so, it prevents all of its ranges from acquiring new leases. That of course is a terrible idea if one replica is all you have.

I think we should consider completely remove setting nodes to draining when they discover that they're decommissioning. This happens automatically when they're shut down in a clean way; the only concern is whether the decommissioning process might end up taking a long time since every leaseholder has to be transferred away by the allocator before the replica can be moved elsewhere. But that may even be a benefit; transferring an unbounded number of leases simultaneously may not be a good idea neither, and removing a node is allowed to take a little bit of time.

As a quick fix, we could also massage the draining status so that a singleton replica ignores the restrictions about retrieving new leases, but the whole concept of trying to drain a singleton replica while it still needs to work is flawed.

**Comment by tim-o** [comment] 2018-08-12 16:28
Zendesk ticket #[2298](https://cockroachdb.zendesk.com/agent/tickets/2298) has been linked to this issue.

**Closed** 2018-08-16 20:13 UTC
Labels: A-core-distribution, C-bug, S-2-temp-unavailability
