### ISSUE TITLE
DbVisualizer error when selecting indexes

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24648] opened 2018-04-10 21:22 UTC
In DbVisualizer, I tried to select a indexes. An error was present in dbvisualizer and in the logtostderr

`An error occurred while performing the operation:
ERROR: syntax error at or near "."
Detail: source SQL:
SELECT NULL AS TABLE_CAT, n.nspname AS TABLE_SCHEM, ct.relname AS TABLE_NAME, NOT i.indisunique AS NON_UNIQUE, NULL AS INDEX_QUALIFIER, ci.relname AS INDEX_NAME, CASE i.indisclustered WHEN true THEN 1 ELSE CASE am.amname WHEN 'hash' THEN 2 ELSE 3 END END AS TYPE, (i.keys).n AS ORDINAL_POSITION, trim(both '"' from pg_catalog.pg_get_indexdef(ci.oid, (i.keys).n, false)) AS COLUMN_NAME, CASE am.amcanorder WHEN true THEN CASE i.indoption[(i.keys).n - 1] & 1 WHEN 1 THEN 'D' ELSE 'A' END ELSE NULL END AS ASC_OR_DESC, ci.reltuples AS CARDINALITY, ci.relpages AS PAGES, pg_catalog.pg_get_expr(i.indpred, i.indrelid) AS FILTER_CONDITION FROM pg_catalog.pg_class ct JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid) JOIN (SELECT i.indexrelid, i.indrelid, i.indoption, i.indisunique, i.indisclustered, i.indpred, i.indexprs, information_schema._pg_expandarray(i.indkey) AS keys FROM pg_catalog.pg_index i) i ON (ct.oid = i.indrelid) JOIN pg_catalog.pg_class ci ON (ci.oid = i.indexrelid) JOIN pg_catalog.pg_am am ON (ci.relam = am.oid) WHERE true AND n.nspname = 'information_schema' AND ct.relname = 'columns' ORDER BY NON_UNIQUE, TYPE, INDEX_NAME, ORDINAL_POSITION
^`

And in logtostderr
`I180410 21:21:37.945919 215 server/status/runtime.go:219  [n1] runtime stats: 165 MiB RSS, 161 goroutines, 135 MiB/12 MiB/163 MiB GO alloc/idle/total, 49 MiB/77 MiB CGO alloc/total, 63.29cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I180410 21:21:45.402292 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] [NoTxn pos:863] executing SendError: syntax error at or near "."
I180410 21:21:45.402348 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] execution error: syntax error at or near "."
I180410 21:21:45.402388 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] [NoTxn pos:867] executing Sync`

**Comment by jordanlewis** [comment] 2018-04-10 21:37
Duplicate of #16971

**Closed** 2018-04-11 14:37 UTC
Labels: pg-compat
