### ISSUE TITLE
sql: datestyle cannot be passed as sql uri session variable

### ISSUE THREAD

**Issue by dbist** [cockroachdb/cockroach#70827] opened 2021-09-28 15:20 UTC
**Describe the problem**

ISO, MDY works

```bash
cockroach sql --url 'postgresql://root@roach3:26257/defaultdb?sslmode=disable&datestyle=ISO, MDY'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.2.0-beta.2 (x86_64-unknown-linux-gnu, built 2021/09/27 18:10:34, go1.16.6) (same version as client)
# Cluster ID: 9e574b7b-2a78-4d6f-8299-7dca3e86f11c
#
# Enter \? for a brief introduction.
#
root@roach3:26257/defaultdb> 
```

MDY, ISO doesn't

```sql
```bash
[root@roach3 cockroach]# cockroach sql --url 'postgresql://root@roach3:26257/defaultdb?sslmode=disable&datestyle=MDY, ISO'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: setting datestyle must be absent or ISO, MDY; got MDY, ISO
Failed running "sql"
```

within CLI it doesn't take effect but at least it doesn't error out

```sql
root@roach3:26257/defaultdb> set datestyle = 'MDY, ISO';
SET


Time: 1ms total (execution 0ms / network 0ms)

root@roach3:26257/defaultdb> show datestyle;
  datestyle
-------------
  ISO, MDY
(1 row)


Time: 1ms total (execution 1ms / network 0ms)
```
also `$PGDATESTYLE` now takes effect

```bash
 export PGDATESTYLE="ISO, MDY"
```

```bash
[root@roach1 cockroach]# cockroach sql --url 'postgresql://root@roach1:26257/defaultdb?sslmode=disable'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.2.0-beta.2 (x86_64-unknown-linux-gnu, built 2021/09/27 18:10:34, go1.16.6) (same version as client)
# Cluster ID: 9e574b7b-2a78-4d6f-8299-7dca3e86f11c
#
# Enter \? for a brief introduction.
#
root@roach1:26257/defaultdb> 
```

but setting it to `MDY, ISO` doesn't

```bash
[root@roach1 cockroach]# export PGDATESTYLE="MDY, ISO"[root@roach1 cockroach]# cockroach sql --url 'postgresql://root@roach1:26257/defaultdb?sslmode=disable'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: setting datestyle must be absent or ISO, MDY; got MDY, ISO
Failed running "sql"
```

`psql` doesn't make a difference in re: `$PGDATESTYLE`

```bash
[root@roach1 cockroach]# export PGDATESTYLE="ISO, MDY"
[root@roach1 cockroach]# echo $PGDATESTYLE 
ISO, MDY
[root@roach1 cockroach]# psql 'postgresql://root@roach1:26257/defaultdb?sslmode=disable'
psql (13.4, server 13.0.0)
Type "help" for help.

defaultdb=> \q
```

```bash
[root@roach1 cockroach]# export PGDATESTYLE="MDY, ISO"
[root@roach1 cockroach]# psql 'postgresql://root@roach1:26257/defaultdb?sslmode=disable'
psql (13.4, server 13.0.0)
Type "help" for help.

defaultdb=> \q
```

the `postgresql.conf` file doesn't take effect in either `psql` or `cockroach` unfortunately.

**To Reproduce**

**Expected behavior**

passing `datestyle=MDY, ISO` shouldn't break `cockroach` connection

**Environment:**
 - CockroachDB version: 21.1.2-beta2 
 - Server OS: official docker image unstable branch
 - Client app:`cockroach sql`, `psql`

Epic CRDB-8948

gz#10101

**Comment by vy-ton** [comment] 2021-09-28 15:24
@dbist You say your version is `21.1.2-beta2`. Can you test with `21.2`?

For example, I can see that the following works
```
root@localhost:26257/defaultdb> SET datestyle_enabled = true;
root@localhost:26257/defaultdb> set datestyle = "ISO, DMY";
root@localhost:26257/defaultdb> show datestyle;
  datestyle
-------------
  ISO, DMY
```

**Comment by dbist** [comment] 2021-09-28 15:33
where do I get access to 21.2? `ISO, DMY` does take effect in the beta

```sql
root@roach1:26257/defaultdb> set datestyle = "ISO, DMY";
SET


Time: 1ms total (execution 0ms / network 0ms)

root@roach1:26257/defaultdb> show datestyle;
  datestyle
-------------
  ISO, DMY
(1 row)
```

It does not however work in the connection string

```sql
[root@roach1 cockroach]# cockroach sql --url 'postgresql://root@roach1:26257/defaultdb?sslmode=disable&datestyle_enabled=true&datestyle=ISO, DMY'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: setting datestyle must be absent or ISO, MDY; got ISO, DMY
Failed running "sql"
[root@roach1 cockroach]# cockroach sql --url 'postgresql://root@roach1:26257/defaultdb?sslmode=disable&datestyle_enabled=true&datestyle=MDY, ISO'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
ERROR: setting datestyle must be absent or ISO, MDY; got MDY, ISO
Failed running "sql"
[root@roach1 cockroach]# cockroach sql --url 'postgresql://root@roach1:26257/defaultdb?sslmode=disable&datestyle_enabled=true&datestyle=ISO, MDY'
#
# Welcome to the CockroachDB SQL shell.
# All statements must be terminated by a semicolon.
# To exit, type: \q.
#
# Server version: CockroachDB CCL v21.2.0-beta.2 (x86_64-unknown-linux-gnu, built 2021/09/27 18:10:34, go1.16.6) (same version as client)
# Cluster ID: 9e574b7b-2a78-4d6f-8299-7dca3e86f11c
#
# Enter \? for a brief introduction.
#
root@roach1:26257/defaultdb> 
```

**Comment by vy-ton** [comment] 2021-09-28 15:35
The betas are available here, https://www.cockroachlabs.com/docs/releases/index.html#testing-releases

**Comment by dbist** [comment] 2021-09-28 15:54
that's the version I'm using

**Comment by otan** [comment] 2021-09-28 20:15
this is not a supported feature in postgres:

```
> psql 'postgres://otan@localhost:5432/otan?datestyle=ISO, MDY'
psql: error: invalid URI query parameter: "datestyle"
```

which makes this a feature request, not a bug.

if you want this to be set by default, you have two existing options:
* `ALTER USER x SET datestyle = 'ISO, MDY'` -- defaults for the user
* `ALTER DATABASE x SET datestyle = 'ISO, MDY'` -- defaults for the database.

Adjust priority and unassigned accordingly.

**Comment by dbist** [comment] 2021-09-28 20:21
@otan, I need `MDY, ISO` which I just tested with the syntax for user and for database does not error out but it doesn't take effect either. Hope that still satisfies my customer concern.

**Comment by otan** [comment] 2021-09-28 20:29
you have to "relogin", i think. if that doesn't work, @rafiss can help you out.
`MDY, ISO` is also the default, so not sure what the concern is. (ISO, MDY == MDY, ISO)

**Comment by dbist** [comment] 2021-09-28 20:39
it works with `ISO, MDY` but errors out with `MDY, ISO` even if its equivalent.

**Comment by otan** [comment] 2021-09-28 20:39
what doesn't work? what are you trying?

**Comment by dbist** [comment] 2021-09-28 20:42
ok, let me wait for the customer's response and I'll respond with a repro in case we are having an issue.

**Comment by otan** [comment] 2021-09-28 20:57
FWIW we did do some testing and find that ALTER USER/DATABASE doesn't work for DateStyle:

```

root@127.0.0.1:5436/defaultdb> set cluster setting sql.defaults.datestyle.enabled = 'on';
SET CLUSTER SETTING

root@127.0.0.1:5436/defaultdb> set datestyle_enabled = true; -- double tap
SET


Time: 0ms total (execution 0ms / network 0ms)

root@127.0.0.1:5436/defaultdb> create user bob;
CREATE ROLE


Time: 42ms total (execution 42ms / network 0ms)

root@127.0.0.1:5436/defaultdb>  alter user bob set datestyle = 'ymd, iso';
ERROR: setting DateStyle is not enabled
SQLSTATE: 0A000
DETAIL: Setting DateStyle changes the volatility of timestamp/timestamptz/date::string and string::timestamp/timestamptz/date/time/timetz casts from immutable to stable. No computed columns, partial indexes, partitions and check constraints can use this casts. Use to_char_with_style or parse_{timestamp,timestamptz,date,time,timetz} instead if you need these casts to work in the aforementioned cases.
HINT: You can enable DateStyle customization for all sessions with the cluster setting sql.defaults.datestyle_enabled, or per session using SET datestyle_enabled = true.
```

@rafiss is looking at it :)

**Comment by rafiss** [comment] 2021-09-29 05:01
re: `iso, mdy` vs `mdy, iso` i recall that we earlier decided to support either order (https://github.com/cockroachdb/cockroach/pull/62042), since postgres does too. the reason was the tool a customer was using was insisting on `MDY, ISO`.

looks like we accidentally undid that work.

re: `alter user bob set datestyle = 'ymd, iso'`, the issue is https://github.com/cockroachdb/cockroach/blob/bdb4c1ac404a99cb679643d734f292b81487e15a/pkg/sql/vars.go#L1911

`GetSessionVariableValueValid` always will fail this check because of  how it makes a fake SessionData. we should be able to fix that, but this points to a deeper problem:

i’m not sure how we can set `datestyle` during session-init in general (as is), whether it’s from connection string or from per-user defaults. during session init, we don’t really know whether `datestyle_enabled` is true or not. and if we assume it is, but then later turns out it’s not, it would be an error to set `datestyle` so then the session init would fail. if needed, we'll spin off a different issue for this point i'm raising.

**Comment by vy-ton** [comment] 2021-10-11 20:49
> During session init, we don't have the ability to do conditional behavior based on cluster settings?
> not sure what you mean, but the cluster setting sql.defaults.datestyle still works

Clarified, `cockroach sql --url postgresql://root@roach3:26257/defaultdb?sslmode=disable&datestyle=MDY, ISO`

**Comment by dbist** [comment] 2021-10-12 13:53
I communicated to the customer, they will enable the cluster setting and observe behavior of the driver expecting the property.

**Comment by rafiss** [comment] 2021-11-01 21:05
fixed by https://github.com/cockroachdb/cockroach/pull/72010

**Closed by rafiss** 2021-11-01 21:05 UTC
Labels: C-enhancement, T-sql-experience
