### ISSUE TITLE
sql: panic: invalid datum type given: oid[], expected int[]

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#34438] opened 2019-01-31 06:10 UTC
```
CREATE TABLE table0 (col0 VARBIT NOT NULL, col1 OID[], col2 TIMESTAMP NOT NULL, col3 STRING NOT NULL, col4 TIME NOT NULL, col5 BOOL NULL, col6 DECIMAL NULL, col7 STRING COLLATE da, col8 UUID NOT NULL, FAMILY fam0 (col8, col2, col5, col3, col0, col4, col6, col7, col1), PRIMARY KEY (col4 ASC, col7 DESC, col5, col2, col8 ASC, col3), UNIQUE (col5 DESC, col3 ASC, col8 ASC, col0, col7, col2, col4 DESC, col6 ASC), UNIQUE (col6 ASC, col7, col0), INDEX (col5 ASC, col7 ASC, col8 ASC, col2, col4), INDEX (col6 DESC, col5 DESC, col8, col7 ASC, col2 ASC), UNIQUE (col3 ASC, col0 ASC, col4 ASC, col2 DESC, col5 DESC)) ;
CREATE TABLE table1 (col0 NAME NOT NULL, col1 DATE NULL, col2 TIMESTAMP, col3 TIMESTAMPTZ NULL, col4 STRING NULL, col5 VARBIT, col6 NAME NOT NULL, col7 INT8, col8 OID, col9 DATE NOT NULL, col10 BOOL NULL, col11 TIMESTAMP NULL, col12 UUID, col13 TIMESTAMP NULL, FAMILY fam0 (col3, col9, col4, col13, col1, col6, col5, col0, col10, col8, col7, col11, col2, col12), PRIMARY KEY (col5 DESC, col8 ASC, col4 DESC, col7 DESC, col6 DESC, col10 ASC, col2 DESC, col11 ASC, col0 ASC, col12 DESC, col3 ASC, col1 ASC, col13 ASC), INDEX (col4 ASC, col12 DESC, col13, col3 ASC, col0 ASC, col7, col8), INDEX (col5 DESC, col3, col9, col8 ASC, col6, col2), UNIQUE (col10, col3 ASC, col4, col13 DESC, col9, col8, col5, col7 DESC, col0, col6 DESC, col2 DESC), UNIQUE (col3 ASC, col10, col13, col2, col6 DESC, col8 ASC, col5 ASC, col1 DESC, col7 DESC, col4, col11 ASC, col12 ASC), UNIQUE (col6 DESC, col12 DESC, col0, col3, col4 DESC, col10 ASC, col8 ASC, col5 DESC, col1 DESC), INDEX (col0), UNIQUE (col6 ASC, col8, col13 DESC, col2 ASC)) ;
CREATE TABLE table2 (col0 NAME NOT NULL, col1 TIMESTAMP NULL, col2 FLOAT8 NOT NULL, col3 NAME, col4 FLOAT8, col5 TIMESTAMPTZ NOT NULL, col6 STRING COLLATE de NOT NULL, col7 TIMESTAMP NOT NULL, col8 TIME, col9 OID NOT NULL, col10 OID[] NULL, col11 VARBIT NULL, col12 INET NULL, FAMILY fam0 (col6, col10), FAMILY fam1 (col5, col8, col12, col0, col9, col4, col3, col2, col1, col11, col7), PRIMARY KEY (col6), UNIQUE (col12 DESC, col1 ASC, col6 ASC), INDEX (col2, col5 DESC, col3 DESC), INDEX (col6, col0 DESC, col11 ASC, col12 DESC, col5, col7, col9, col4 ASC, col2 ASC, col8), INDEX (col1, col12 DESC, col7 DESC, col8 DESC, col0, col4 ASC, col11, col9 DESC, col2 DESC, col6 DESC, col3 ASC, col5), UNIQUE (col0 DESC, col3 ASC, col1 ASC), UNIQUE (col3, col2, col7 ASC)) ;
CREATE TABLE table3 (col0 INTERVAL NULL, col1 BOOL, col2 OID[] NULL, FAMILY fam0 (col1, col2, col0), PRIMARY KEY (col0, col1 ASC), INDEX (col1), UNIQUE (col0, col1 DESC), UNIQUE (col0 DESC, col1 DESC), UNIQUE (col0), INDEX (col1 ASC, col0 ASC), UNIQUE (col0 DESC), UNIQUE (col0 DESC, col1 DESC)) ;
CREATE TABLE table4 (col0 NAME, col1 BYTES, col2 OID NOT NULL, col3 INT8[] NOT NULL, FAMILY fam0 (col3, col0, col1, col2), PRIMARY KEY (col1 DESC), INDEX (col2 ASC, col0), UNIQUE (col0, col2, col1), UNIQUE (col2 ASC, col1 ASC), INDEX (col2, col1, col0 ASC), INDEX (col2 ASC, col1 DESC), UNIQUE (col2), INDEX (col1 DESC, col0 ASC, col2 ASC), UNIQUE (col2 ASC, col0 ASC, col1 DESC)) ;
CREATE TABLE table5 (col0 BYTES NOT NULL, col1 VARBIT, col2 DECIMAL NULL, col3 INT8[] NOT NULL, col4 NAME NULL, col5 UUID NULL, col6 INTERVAL, col7 BOOL NULL, col8 BYTES NULL, col9 NAME NOT NULL, col10 OID NOT NULL, FAMILY fam0 (col0), FAMILY fam1 (col8, col6, col1, col10, col3, col5, col2, col7), FAMILY fam2 (col9, col4), PRIMARY KEY (col0 DESC), UNIQUE (col5 DESC, col8 ASC), INDEX (col4 DESC), INDEX (col7, col1 ASC, col8 ASC, col5, col4, col9 DESC), INDEX (col1 DESC, col0 ASC, col2 DESC, col7 ASC, col4, col10 ASC, col6, col9 ASC, col8 DESC, col5 ASC), UNIQUE (col1 ASC, col6, col4 DESC, col8 ASC, col10 ASC, col5), INDEX (col2 DESC)) ;
CREATE TABLE table6 (col0 TIME NOT NULL, col1 DATE NULL, col2 DATE, col3 BOOL, col4 INTERVAL NULL, col5 BOOL NOT NULL, col6 NAME NOT NULL, col7 INET NULL, col8 FLOAT8 NULL, col9 STRING COLLATE en NULL, col10 INT8 NULL, col11 INET, col12 UUID, col13 UUID NOT NULL, col14 TIMESTAMPTZ NOT NULL, col15 UUID NULL, FAMILY fam0 (col5, col6, col12, col0), FAMILY fam1 (col11, col14, col3, col1, col13, col8, col7, col4, col9, col15, col2, col10), PRIMARY KEY (col6 DESC, col0 ASC, col12 ASC, col5 DESC), UNIQUE (col14, col12, col11, col8, col3 DESC, col2, col15, col7 DESC, col4 ASC, col10 ASC), UNIQUE (col9 ASC), INDEX (col5 DESC, col0 DESC, col3, col8, col14, col7 DESC, col6, col13, col10, col1 DESC, col11 ASC), UNIQUE (col3, col15 ASC, col13 DESC, col8, col9 ASC, col0, col5 DESC, col10 ASC, col14, col7, col4, col6), UNIQUE (col4 ASC, col8 DESC, col3 DESC, col12, col2 DESC, col15, col0 ASC, col6 ASC, col13 ASC, col9, col10, col11, col1 ASC, col5, col14 DESC), INDEX (col12 ASC, col10, col13, col11 ASC, col2 DESC, col15 ASC, col4 DESC, col14 ASC, col6 ASC, col8, col1), UNIQUE (col10 DESC, col13 DESC)) ;
CREATE TABLE table7 (col0 DATE NOT NULL, col1 INT8[] NOT NULL, col2 OID[], col3 INTERVAL NOT NULL, col4 BYTES NOT NULL, col5 BOOL NULL, col6 DATE NULL, col7 DATE NOT NULL, FAMILY fam0 (col0, col6), FAMILY fam1 (col7, col4, col5, col2, col1, col3), PRIMARY KEY (col6 ASC, col0 DESC), UNIQUE (col5 ASC, col4, col3), UNIQUE (col0, col6 ASC, col5 ASC, col7, col4, col3 DESC), INDEX (col5 ASC, col4 DESC, col0 DESC, col7, col6, col3 ASC), UNIQUE (col7, col5 ASC)) ;
CREATE TABLE table8 (col0 STRING NULL, col1 TIMESTAMPTZ NOT NULL, col2 VARBIT, col3 OID NOT NULL, col4 INTERVAL NOT NULL, FAMILY fam0 (col0, col3, col4, col2, col1), PRIMARY KEY (col1 ASC, col4 ASC, col3 ASC, col0 DESC, col2), UNIQUE (col4 ASC, col0), UNIQUE (col1 ASC, col4 DESC), UNIQUE (col1, col3 ASC, col0 DESC, col4, col2), INDEX (col4, col3 ASC, col2 DESC), UNIQUE (col2, col1 ASC), INDEX (col1 ASC, col2, col4 ASC, col0 DESC)) ;
CREATE TABLE table9 (col0 DATE NOT NULL, col1 TIME NULL, col2 VARBIT NULL, col3 TIMESTAMPTZ NULL, col4 BOOL, col5 OID[] NULL, col6 INTERVAL, col7 VARBIT, col8 INT8[], col9 OID[] NULL, col10 INT8[] NOT NULL, col11 INTERVAL, col12 NAME NOT NULL, col13 TIMESTAMPTZ NOT NULL, col14 TIMESTAMP, col15 INTERVAL NULL, col16 NAME, col17 UUID, col18 INT8 NULL, FAMILY fam0 (col13, col17, col1, col0, col7, col16, col14, col10, col6, col4, col11, col18, col12, col3, col2, col15, col5, col9, col8), PRIMARY KEY (col13 DESC), INDEX (col12, col18, col6 DESC), INDEX (col4 ASC), UNIQUE (col16, col1 DESC, col15 ASC, col11 ASC, col0 ASC, col12 ASC, col3, col13, col2 ASC, col17, col7), UNIQUE (col16 DESC, col15 DESC, col12, col6, col17 ASC, col7, col3 ASC, col1, col13, col18), UNIQUE (col17 DESC, col4 DESC, col16 DESC, col13 DESC, col1, col2 ASC), UNIQUE (col2), UNIQUE (col12 ASC, col6, col7 ASC, col13 ASC, col16 DESC), INDEX (col1 ASC, col2 ASC, col18, col3 DESC, col17, col0 DESC, col15 ASC, col11 DESC, col14 ASC, col13)) ;
VALUES ('fa450287-6f8a-49a9-981b-05e8b245b322', (B'001110010111111100110110010110' & B'110010000001010100111101101100011111000000101100100111110111111100110000100110011'), CASE WHEN false THEN (SELECT '8255:e96b:97a9:15eb:f348:d659:9adc:bdbb/72' FROM table5 AS tab_1 LIMIT 1) ELSE '72.160.180.5/29' END, '1970-01-09 21:04:18.000943+00:00', (B'1001001001110100' # B'11010')), ('4dcc701e-6500-472d-8da3-e9b4eca311db', B'100111000111011101011001100100000001110101110110100101011100', '185.50.154.169/16', '1970-01-03 05:40:57.000387+00:00', varbit_in('18:42:44.225736')), ((SELECT '9fffb870-baf6-4a7c-835d-ba31d249fc48' FROM [INSERT INTO table9(col0, col2, col3, col5, col8, col9, col10, col13, col14, col16, col12) (VALUES ('1971-04-25', B'10010100001010101001001101100110000100', NULL, ARRAY[4051529915, 1785875776, 3526896629, 2714789808], ARRAY[-4113386296976016540], ARRAY[], ARRAY[-6806128580490536161, -7848314492355076899, -7365716551336316359], '1970-01-06 01:58:06.000194+00:00', '1970-01-11 03:24:31.000829+00:00', NULL, NULL), ('1983-05-29', B'101000010001011010111000011', '1970-01-10 16:23:44.000532+00:00', ARRAY[3819382847, 2654780775], ARRAY[5024447036552396525, -7203918009937671726, 546799975354074099], ARRAY[147296989, 3750968201, 4291598444, 2129429749, 1677548632, 2880888410, 3628840314, 2628059600], ARRAY[-6991539424454055165, -2073674107366548484, 682340236967464746, -956264086859338307, -5149569525191493376], '1970-01-11 12:27:15.00092+00:00', '1970-01-04 07:33:27.000106+00:00', e'\\t/=\\x16>P!i', ''), (NULL, B'00101111101110', '1970-01-12 13:22:04.000785+00:00', ARRAY[755157065, 3649637064, 3245915249], ARRAY[], ARRAY[2193404529, 4008661543, 1100424352, 204333852, 1953736390, 3545070506], ARRAY[3283440759657622984, 9141492992198255144, -1937708246718604019, -5894307240916615593, 8365671150753844709], '1970-01-08 00:07:54.000649+00:00', '1970-01-04 20:02:51.000331+00:00', NULL, e'%6\\x03')) INTERSECT (SELECT '1979-01-25', B'0111011100001111000100100', '1970-01-02 18:29:01.000453+00:00', ARRAY[1163317930, 2818958946, 29071040], ARRAY[-2181398704520823556, 8775836607358052514], ARRAY[3834965167, 3701854907], ARRAY[7753217566155620834, -3834802679039276674, -6871100071110445114], '1970-01-10 09:09:23.000071+00:00', '1970-01-04 07:01:29.000677+00:00', e')\\x12G<T7', '' FROM table4 AS tab_13 WHERE ('1993-01-31' > '1970-01-06 10:53:23.000915+00:00')) RETURNING table9.col4, -83595664563.30181256, table9.col18, table9.col18] WHERE (1343318939 IS DISTINCT FROM 2058384652) LIMIT 1), B'0000011101000110101010001101100100110011000001010010100110000111', NULL, '1970-01-10 17:29:02.000076+00:00', varbit_in('ff8f81c9-a17c-4af9-b315-752d46f59751')), (NULL, B'1111101110011100110000000', 'ebd2:1b02:5a3c:83e9:3c5:e43e:fae8:c52f/126', '1970-01-10 00:36:41.000365+00:00', B'11101111000111110011101110111111000000010010110'), (NULL, B'00011111001010011101110001001101101111110000', '189.98.89.167/24', '1970-01-07 15:58:54.000786+00:00', B'01111010011100000001000010011010101100111100110011010011001111110110000110'), ('4fc21010-7ec9-4ec1-b090-c1fa96b0d368', B'10110001001000101101010110000001011101111110100101000010011010111110010001110100000010111001', '2e18:d41d:397d:6210:3048:53b9:d8d6:779/56', '1970-01-05 10:32:26.00059+00:00', (B'10010110110111101000001' << 2516533621443746251));
```

```
panic: invalid datum type given: oid[], expected int[] [recovered]
	panic: panic while executing 1 statements: VALUES (_, (_ & _), CASE WHEN _ THEN (SELECT _ FROM _ AS _ LIMIT _) ELSE _ END, _, (_ # _)), (__more5__); caused by invalid datum type given: oid[], expected int[]

goroutine 419 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc000ab6000, 0x73f01e0, 0xc001083140, 0x675e9e0, 0xc00042ad70)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:711 +0x36d
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1(0xc000ab6000, 0x73f01e0, 0xc001083140)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:423 +0x61
panic(0x675e9e0, 0xc00042ad70)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:513 +0x1b9
github.com/cockroachdb/cockroach/pkg/sql/sqlbase.DatumToEncDatum(0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00036ef94, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/sqlbase/encoded_datum.go:170 +0x25d
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Next(0xc0007cd400, 0xc000941d40, 0xb, 0xb, 0xc001571290)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:198 +0x593
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Distinct).Next(0xc00091e700, 0x0, 0x0, 0x680dde0, 0xc0010c2b10)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/distinct.go:203 +0x5d
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).receiveNext(0xc0008f5600, 0x73f0200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:635 +0x1a1
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).readProbeSide(0xc0008f5600, 0x3, 0x0, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:421 +0x388
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*hashJoiner).Next(0xc0008f5600, 0x0, 0x98, 0xc00080e500, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/hashjoiner.go:241 +0x278
github.com/cockroachdb/cockroach/pkg/sql.(*rowSourceToPlanNode).Next(0xc0016e5440, 0x73f02a0, 0xc0010c27b0, 0xc0017c0f00, 0xc000ab6450, 0x0, 0x0, 0xc001d70c28)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/row_source_to_plan_node.go:76 +0x63
github.com/cockroachdb/cockroach/pkg/sql.(*insertNode).BatchedNext(0xc0017b1680, 0x73f02a0, 0xc0010c27b0, 0xc0017c0f00, 0xc000ab6450, 0x0, 0x0, 0xc00134f680)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/insert.go:474 +0xcc
github.com/cockroachdb/cockroach/pkg/sql.(*serializeNode).Next(0xc0014f1d70, 0x73f02a0, 0xc0010c27b0, 0xc0017c0f00, 0xc000ab6450, 0x13, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_batch.go:123 +0xa1
github.com/cockroachdb/cockroach/pkg/sql.(*spoolNode).startExec(0xc0014f1e00, 0x73f02a0, 0xc0010c27b0, 0xc0017c0f00, 0xc000ab6450, 0xc0014f1d70, 0xc001d70d50)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/spool.go:61 +0x18b
github.com/cockroachdb/cockroach/pkg/sql.startExec.func2(0x6c35ba8, 0x5, 0x73f2260, 0xc0014f1e00, 0xc0016847e0, 0xc001d70d60)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:493 +0x55
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal.func1(0xc0014cf630, 0x6c35ba8, 0x5, 0x73f2260, 0xc0014f1e00)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:134 +0x5d
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visitInternal(0xc0014cf630, 0x73f2260, 0xc0014f1e00, 0x6c35ba8, 0x5)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:598 +0x1c4
github.com/cockroachdb/cockroach/pkg/sql.(*planVisitor).visit(0xc0014cf630, 0x73f2260, 0xc0014f1e00, 0xc001d71a00, 0x400ec6f)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:101 +0x8d
github.com/cockroachdb/cockroach/pkg/sql.walkPlan(0x73f02a0, 0xc0010c27b0, 0x73f2260, 0xc0014f1e00, 0x0, 0x6d9ad38, 0x0, 0x0, 0xc0010c28a0, 0xc000783600, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/walk.go:65 +0x1b2
github.com/cockroachdb/cockroach/pkg/sql.startExec(0x73f02a0, 0xc0010c27b0, 0xc0017c0f00, 0xc000ab6450, 0x73f2260, 0xc0014f1e00, 0xc00042aac8, 0xc00042aac0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan.go:496 +0xf8
github.com/cockroachdb/cockroach/pkg/sql.(*planNodeToRowSource).Start(0xc0007cd900, 0x73f02a0, 0xc0010c27b0, 0x91faec0, 0x675dc60)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/plan_node_to_row_source.go:124 +0xd9
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*ProcessorBase).Run(0xc0007cd900, 0x73f02a0, 0xc0010c27b0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go:801 +0x52
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun.(*Flow).Run(0xc0017c10e0, 0x73f02a0, 0xc0010c27b0, 0x6d9a4b8, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go:657 +0x209
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run(0xc0007bc780, 0xc000b869c0, 0xc00134e1b0, 0xc001d72838, 0xc000277600, 0xc0017c0960, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:251 +0x8a0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).planAndRunSubquery(0xc0007bc780, 0x73f02a0, 0xc0014f01e0, 0x0, 0xc0014f1ec0, 0x4, 0x1, 0x73f1e20, 0xc001708dc0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:715 +0x877
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRunSubqueries(0xc0007bc780, 0x73f02a0, 0xc0014f01e0, 0xc000ab6450, 0xc0010c2120, 0xc000be44c0, 0x1, 0x1, 0xc000277340, 0xc000ab6100, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:615 +0x1a6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc000ab6000, 0x73f02a0, 0xc0014f01e0, 0xc000ab6450, 0x3, 0xf760dd0, 0xc00134e240, 0x0, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1005 +0x371
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc000ab6000, 0x73f02a0, 0xc0014f01e0, 0x73f5d20, 0xc001041a80, 0xc001625000, 0xcf6, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:856 +0x6bf
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc000ab6000, 0x73f02a0, 0xc0014f01e0, 0x73f5d20, 0xc001041a80, 0xc001625000, 0xcf6, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:437 +0xe85
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc000ab6000, 0x73f02a0, 0xc0014f01e0, 0x73f5d20, 0xc001041a80, 0xc001625000, 0xcf6, 0x0, 0x0, 0x0, ...)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:93 +0x36f
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc000ab6000, 0x73f01e0, 0xc001083140, 0xc0008227b8, 0x5400, 0x15000, 0xc000822850, 0xc0004da440, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1172 +0x21e5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc000a58680, 0x73f01e0, 0xc001083140, 0xc000ab6000, 0x5400, 0x15000, 0xc000822850, 0xc0004da440, 0x0, 0x0)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:425 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc000a58680, 0x73f01e0, 0xc001083140, 0xc000ab6000, 0x5400, 0x15000, 0xc000822850, 0xc0004da440, 0xc0004da450, 0xc000405754)
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:319 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
	/Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:318 +0x1033
```

**Comment by yuzefovich** [comment] 2019-02-01 17:56
Here is slightly reduced reproduction:
```
CREATE TABLE table9 (col0 DATE NOT NULL, col1 TIME NULL, col2 VARBIT NULL, col3 TIMESTAMPTZ NULL, col4 BOOL, col5 OID[] NULL, col6 INTERVAL, col7 VARBIT, col8 INT8[], col9 OID[] NULL, col10 INT8[] NOT NULL, col11 INTERVAL, col12 NAME NOT NULL, col13 TIMESTAMPTZ NOT NULL, col14 TIMESTAMP, col15 INTERVAL NULL, col16 NAME, col17 UUID, col18 INT8 NULL, FAMILY fam0 (col13, col17, col1, col0, col7, col16, col14, col10, col6, col4, col11, col18, col12, col3, col2, col15, col5, col9, col8), PRIMARY KEY (col13 DESC), INDEX (col12, col18, col6 DESC), INDEX (col4 ASC), UNIQUE (col16, col1 DESC, col15 ASC, col11 ASC, col0 ASC, col12 ASC, col3, col13, col2 ASC, col17, col7), UNIQUE (col16 DESC, col15 DESC, col12, col6, col17 ASC, col7, col3 ASC, col1, col13, col18), UNIQUE (col17 DESC, col4 DESC, col16 DESC, col13 DESC, col1, col2 ASC), UNIQUE (col2), UNIQUE (col12 ASC, col6, col7 ASC, col13 ASC, col16 DESC), INDEX (col1 ASC, col2 ASC, col18, col3 DESC, col17, col0 DESC, col15 ASC, col11 DESC, col14 ASC, col13)) ;

INSERT
INTO
    table9
        (
            col0,
            col2,
            col3,
            col5,
            col8,
            col9,
            col10,
            col13,
            col14,
            col16,
            col12
        )
VALUES
    (
        '1971-04-25',
        B'10010100001010101001001101100110000100',
        NULL,
        ARRAY[
            4051529915,
            1785875776,
            3526896629,
            2714789808
        ],
        ARRAY[-4113386296976016540],
        ARRAY[],
        ARRAY[
            -6806128580490536161,
            -7848314492355076899,
            -7365716551336316359
        ],
        '1970-01-06 01:58:06.000194+00:00',
        '1970-01-11 03:24:31.000829+00:00',
        NULL,
        ''
    ),
    (
        NULL,
        B'00101111101110',
        '1970-01-12 13:22:04.000785+00:00',
        ARRAY[755157065, 3649637064, 3245915249],
        ARRAY[],
        ARRAY[
            2193404529,
            4008661543,
            1100424352,
            204333852,
            1953736390,
            3545070506
        ],
        ARRAY[
            3283440759657622984,
            9141492992198255144,
            -1937708246718604019,
            -5894307240916615593,
            8365671150753844709
        ],
        '1970-01-08 00:07:54.000649+00:00',
        '1970-01-04 20:02:51.000331+00:00',
        NULL,
        e'%6\x03'
    );
```
Separately, both rows can be added (if in the second one the column value `NULL` for `col0` is changed to a valid date - `col0` is now allowing NULLs). I wonder whether this constraint violation is what's causing the bug.

**Comment by yuzefovich** [comment] 2019-02-02 00:53
Turning off the optimizer removes the panic (the query gets an error: `pq: null value in column "col0" violates not-null constraint`).

**Comment by jordanlewis** [comment] 2019-02-03 20:32
Thanks for the analysis @yuzefovich, kicking over to @andy-kimball's team.

**Comment by andy-kimball** [comment] 2019-02-05 22:17
This is a duplicate of #34592. Empty arrays of different types in the same query will cause various symptoms.

**Closed by andy-kimball** 2019-02-05 22:17 UTC
Labels: C-bug, O-sqlsmith, S-3
