### ISSUE TITLE
Add roachtest-owner as tag for vms while running tests. 

### ISSUE THREAD

**Issue by BabuSrithar** [cockroachdb/cockroach#129955] opened 2024-08-31 07:30 UTC
**Is your feature request related to a problem? Please describe.**
Roachtest tests have owners associated with it. It would be helpful have the ability to map test run cost by owners.  

**Describe the solution you'd like**
The owners should be added as additional tag while creating VMs. 

@nameisbhaskar @srosenberg @lunevalex 

Jira issue: CRDB-41797

**Comment by renatolabs** [comment] 2024-09-03 13:34
This is a duplicate of #111107.

**Closed** 2024-09-15 10:30 UTC
Labels: C-enhancement, T-testeng
