### ISSUE TITLE
acceptance: test_url_db_override.tcl is flaky

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#30839] opened 2018-10-01 16:47 UTC
This failure on an unrelated PR seems to be a flake https://teamcity.cockroachdb.com/viewLog.html?buildId=934633&buildTypeId=Cockroach_UnitTests

@knz, I'm sorry to assign this to you just because you're the "tcl guy", but maybe you can triage this cause I still don't quite understand the output.

```
.181001 00:44:59.318080434 EXPECT TEST: START TEST: Check that the host flag overrides the host if URL is already set.
spawn /cockroach/cockroach sql --url postgresql://root@localhost:26257?sslmode=disable --host nonexistent -e select 1
Error: cannot dial server.
Is the server running?
If the server is running, check --host client-side and --advertise server-side.

dial tcp: i/o timeout
Failed running "sql"
expect: spawn id exp15 not open
    while executing
"expect {
	$text {}
	timeout { handle_timeout $text }
    }"
    (procedure "eexpect" line 2)
    invoked from within
"eexpect eof"
    (file "/go/src/github.com/cockroachdb/cockroach/cli/interactive_tests/test_url_db_override.tcl" line 91)
non-zero exit code: 1
    	cli_test.go:92: non-zero exit code: 1
[00:45:25] :			 [TestDockerCLI] TestDockerCLI/test_url_login.tcl
[00:45:25] :				 [TestDockerCLI/test_url_login.tcl] tcl
[00:45:25] :				 [TestDockerCLI/test_url_login.tcl] /runMode=docker
```

**Comment by petermattis** [comment] 2018-12-19 15:11
Duplicate of https://github.com/cockroachdb/cockroach/issues/30796.

**Closed by petermattis** 2018-12-19 15:11 UTC
Labels: A-testing, C-test-failure
