### ISSUE TITLE
sql: `SELECT DISTINCT jsoncol->foo` is broken

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#24436] opened 2018-04-02 22:37 UTC
Realistic reproduction:

```
> create table t (ext json);
> insert into t values ('{"foo": "bar"}');
> select distinct ext->'foo' from t;
pq: unable to encode table key: *tree.DJSON
```

Minimal reproduction:

```
> select distinct '{}'::json;
pq: unable to encode table key: *tree.DJSON
```

@justinj suggests that this is because we can't currently key-encode JSON values. As a workaround:

```
> select distinct ext->>'foo' from t;
+-------------+
| ext->>'foo' |
+-------------+
| bar         |
+-------------+
(2 rows)
```

**Comment by awoods187** [comment] 2018-09-18 14:00
Do we have a plan to address this in 2.1 bug fixing period @jordanlewis ?

**Comment by jordanlewis** [comment] 2018-09-18 14:01
Unfortunately this isn't fixable in 2.1 - it's too much work. We could potentially put a better error message for it, but I'm not sure it's worth the effort.

**Comment by sploiselle** [comment] 2018-10-24 15:46
@justinj Can I get a quick blurb describing this known limitation w/r/t the impact to user experience? Ideally, we need it by Friday 10/26 for the 2.1 Known Limitations page. Posting it on this issue and/or pinging me would be great.

**Comment by RaduBerinde** [comment] 2019-02-23 17:43
Similar case that hits the same error: `SELECT DISTINCT json_array_elements('[10, 200, 200, 300, 400]');`

**Comment by knz** [comment] 2019-03-18 16:08
I have added telemetry links inside CockroachDB to the underlying/overarching issue #35706.

**Comment by jordanlewis** [comment] 2019-05-07 16:43
Closing as duplicate of #35706.

**Closed by jordanlewis** 2019-05-07 16:43 UTC
Labels: A-sql-encoding, A-sql-execution, A-sql-json, C-bug, S-3-ux-surprise, docs-done, docs-known-limitation
