### ISSUE TITLE
sql+storage: table copy using INSERT ... SELECT yields large range that isn't split

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#15713] opened 2017-05-05 10:23 UTC
Running on rc1 presumably (to be checked)

Scenario:

- multiple issues of `INSERT INTO ... SELECT ...`  to populate a new table using data from another
- the new table grows to 1.8GB
- the admin UI shows that tables has only 1 range (!!)

Expected: the table is split into multiple ranges as the INSERTs are processed.

**Comment by yznming** [comment] 2017-05-05 10:35
Config:
````
I170504 22:16:41.202688 1 util/log/clog.go:990  [config] file created at: 2017/05/04 22:16:41
I170504 22:16:41.202688 1 util/log/clog.go:990  [config] running on machine: gzns-dba-sz-ndbtest-02
I170504 22:16:41.202688 1 util/log/clog.go:990  [config] binary: CockroachDB CCL v1.0-rc.1-dirty (linux amd64, built 2017/05/01 18:33:34, go1.8.1)
I170504 22:16:41.202688 1 util/log/clog.go:990  [config] arguments: [/home/ndbadmin/ndb/bin//cockroach start --port=26257 --http-port=8080 --store=path=/ssd/ndb-data,attrs=ssd --joi
n=gzns-dba-sz-ndbtest-01.gzns.baidu.com --join=gzns-dba-sz-ndbtest-02.gzns.baidu.com --join=gzns-dba-sz-ndbtest-03.gzns.baidu.com --cache=48G --attrs=gzns --insecure]
````

And there are lots of such log messages:
````
I170504 22:22:01.007442 484 storage/replica_raftstorage.go:415  [replicate,n2,s2,r9/2:/Table/1{4-5}] generated preemptive snapshot 0d8ccdac at index 40
I170504 22:22:01.008129 484 storage/replicate_queue.go:234  [replicate,n2,s2,r9/2:/Table/1{4-5}] snapshot failed: (n4,s4):?: remote declined snapshot: reservation rejected
I170504 22:22:01.064573 484 storage/replica_raftstorage.go:415  [replicate,n2,s2,r9/2:/Table/1{4-5}] generated preemptive snapshot 7a0d4c09 at index 40
I170504 22:22:01.064854 484 storage/replicate_queue.go:234  [replicate,n2,s2,r9/2:/Table/1{4-5}] snapshot failed: (n4,s4):?: remote declined snapshot: reservation rejected
I170504 22:22:01.161841 484 storage/replica_raftstorage.go:415  [replicate,n2,s2,r9/2:/Table/1{4-5}] generated preemptive snapshot ab333264 at index 40
I170504 22:22:01.162106 484 storage/replicate_queue.go:234  [replicate,n2,s2,r9/2:/Table/1{4-5}] snapshot failed: (n4,s4):?: remote declined snapshot: reservation rejected
````
````
W170505 11:06:31.399935 39860230 storage/replica.go:1754  [n2,s2,r1280/2:/{Table/52/1/"[3m<80>-Max}] have been waiting 1m0s for dependencies: cmds:
[{global:<nil> local:<nil>} {global:<nil> local:0xc43a707980}]
global:
  5257068 [/Table/52/1/"6664471432915804"/0)
  5417883 [/Table/52/1/"6664471432915804"/0,/Table/52/2/"pwplSjp/3OYIp6=="/1922-10-06T14:26:20.999999999Z/"6823734935515804"/0/NULL)
    0: 5417884 [/Table/52/1/"9502185486415804"/0)
    1: 5417885 [/Table/52/2/"3253536630"/NULL/"9502185486415804"/0)
    2: 5417886 [/Table/52/1/"9979000586415804"/0)
    3: 5417887 [/Table/52/2/"2842369417"/1922-09-28T01:49:44.999999999Z/"9979000586415804"/0)
    4: 5417888 [/Table/52/2/"3253536630"/NULL/"1729086686415804"/0)
    5: 5417889 [/Table/52/2/"3516331557"/1922-09-22T23:37:16.999999999Z/"2351110886415804"/0)
    6: 5417890 [/Table/52/2/"3253536630"/1922-09-29T17:48:13.999999999Z/"1057433886415804"/0)
    7: 5417891 [/Table/52/2/"2180868994"/1922-09-13T10:53:27.999999999Z/"3942063886415804"/0)
    8: 5417892 [/Table/52/1/"6860442986415804"/0)
````
````
E170505 11:06:32.268673 487 storage/queue.go:634  [raftsnapshot,n2,s2,r1280/2:/{Table/52/1/"[3m<80>-Max}] [n2,s2,r1280/2:/{Table/52/1/"[3m<80>-Max}]: change replicas failed to generate snapshot: [n2,s2,r1280/2:/{Table/52/1/"[3m<80>-Max}]: not generating Raft snapshot because replica is too large: 580828677 > 2 * 67108864
````

**Comment by knz** [comment] 2017-05-05 10:47
Oh I can see a scenario happening: the replica has grown too large already and the request to split it is failing because of that. It's an unfortunate catch-22. cc @bdarnell

**Comment by tschottdorf** [comment] 2017-05-05 10:56
Why would the split fail because of that? We made sure that a split doesn't have to scan the full replica (ok, maybe it does in some situations, but the idea was that it wouldn't have to generally) by carving off chunks of the desired target size on each split.

**Comment by petermattis** [comment] 2017-05-05 12:49
@knz We won't rebalance a range that is too large, but we will split it. The only time we'll stop trying to split a range (modulo bugs) is if the range is unsplittable. For example, a range containing a single very large row cannot be split because we only split at row boundaries. I'm not at all clear on why a split isn't being performed.

**Comment by bdarnell** [comment] 2017-05-08 20:55
Are there any log messages from `split_queue.go`?

**Comment by petermattis** [comment] 2017-05-09 13:44
I wonder how many batches `INSERT ... SELECT` creates. Unless something has changed since my time in SQL-land, it might be creating a single batch, which would be problematic to say the least.

@cuongdo Assigning to you for triage.

**Comment by petermattis** [comment] 2017-05-09 13:45
@jseldess This might be the opposite problem of truncating a large table.

**Comment by petermattis** [comment] 2017-05-09 17:42
I'm actually surprised that the this worked. `INSERT INTO ... SELECT ...` to copy one table into another takes place within the confines of a single transaction and is thus limited by the `kv.transaction.max_intents` setting and the `kv.raft.command.max_size` setting. When I tried to replicate the problem just now, I hit the max intents limit:

```
root@:26257/test> insert into kv2 select * from kv;
pq: kv/txn_coord_sender.go:428: transaction is too large to commit: 232984 intents
```

@yznming The logs above indicating you were running on 1.0-rc.1, but the settings I mention above were present in that release. Is there any more detail you can provide about what you were doing? I'm curious why you didn't hit those limits. Perhaps you ran the `INSERT` on a prior version.

**Comment by andreimatei** [comment] 2017-05-09 21:21
So it sounds to me like there's two issues here: the first one is how come @yznming didn't run into the "transaction is too large" limit, and how did we end up with a range that wasn't being split. The other one is "transaction is too large". I'm gonna talk about the 2nd.

Unfortunately the "transaction is too large to commit" is by design - currently an `EndTransaction` carries all the intents, and so we need to be reasonably sure that each replica will have enough memory to process the corresponding Raft command.

This is a topic that I've randomly discussed at the watercooler with the likes of @bdarnell and @tschottdorf at times. Dumping stuff here for institutional memory. 
There are various things we could do: one way or another, intents (or, at least, _all_ intents) shouldn't have to be attached to an `EndTransaction` request. They could be stored in the db and the cleanup happening after `EndTransaction` has marked the txn record as committed could retrieve them from there. For example, they could be stored in the transaction record itself. The `TxnCoordSender` could keep appending intent spans when it heartbeats the record, for example. That might not be sufficient, since you'll end up with a humongous txn record. What'd be better is to store them adjacently to the txn rec, such that the range can be split, etc. But then you prolly need to be careful with the orchestration of the cleanup process and the cleanup of these intent records themselves.

Without, or besides, storing the intents into the db, the client (the `client.Txn` layer) could be more involved in the cleanup of such large txns; it could store intents in memory and not attach them to `EndTransaction`, but do cleanup afterwards. It could keep the intents below a memory budget by having a limited-size interval tree and merging spans when it needs to - trading pessimistic scanning at cleanup time for memory at execution time. This would probably work great for cases as the one here (I assume): copying a table.
An approach like this would probably be made more feasible by the merging of the `TxnCoordSender` (which currently keeps track of intents) and `client.Txn` that I'm hoping to do.

@petermattis, I'm assigning back to you... But I will keep an eye on supporting work here when I do `TxnCoordSender` refactorings.

Incidentally - here's one idea about the codelab we were talking about: implement `CREATE TABLE AS <query>`, or a version of `INSERT INTO... SELECT...` that does some limited version of the above - doesn't accumulate intents and scans the whole table for cleanup.

**Comment by jseldess** [comment] 2017-05-09 21:42
@petermattis or @andreimatei, since time's short, would either of you write up a brief explanation of this known issue for me to add to the docs?

**Comment by petermattis** [comment] 2017-05-09 21:45
@jseldess `INSERT INTO ... SELECT FROM ...` is performed in a single transaction and will hit the max transaction/command size limits. If those limits are encountered, the workaround is to manually page through the data to be inserted using separate transactions.

**Comment by jseldess** [comment] 2017-05-09 21:56
Documented the limitation under **Write and update limits for a single transaction**: https://github.com/cockroachdb/docs/pull/1381

**Comment by a-robinson** [comment] 2017-05-10 15:39
Thanks for the writeup, @andreimatei. This is something I'd be interested in playing with if we get time during the 1.1 development cycle. It's certainly ripe for improvement given that we don't even to track intents to maintain correctness.

**Comment by petermattis** [comment] 2017-05-10 16:45
@a-robinson and @andreimatei Could one of you file a new issue about supporting large transactions (and copy @andreimatei's comment from above into it)?

**Comment by yznming** [comment] 2017-05-18 00:55
@petermattis Sorry for reply so late. Yes, I have limited the `SELECT` result less than 10000 row by using `WHERE id < 'xxxxxx' AND id >'xxxxxx' ` in every `INSERT ... SELECT` statement and haven't hit the ‘transaction is too large’ error.

**Comment by petermattis** [comment] 2017-06-15 15:55
This isn't something I'll have time to work on for 1.1. Punting to @a-robinson who expressed interested (though he might not have time either).

**Comment by a-robinson** [comment] 2017-07-20 14:46
This is mostly covered by the combination of #15849 (which is scheduled for 1.2) and #16180 (which hasn't had any activity and will likely be bumped to 1.2. Moving this to 1.2 to correspond.

**Comment by cuongdo** [comment] 2017-09-07 18:43
This is a large effort, so we'd need to plan for this effort up front. Moved to Later.

**Comment by cuongdo** [comment] 2017-09-07 20:21
Related to #15849

**Comment by nvanbenschoten** [comment] 2018-02-09 20:44
I'm going to do some testing of this scenario during the code freeze. I expect that it is now sufficiently well handled by the combination of https://github.com/cockroachdb/cockroach/pull/21078 and https://github.com/cockroachdb/cockroach/pull/21777.

**Closed** 2018-03-07 06:01 UTC
Labels: bug, docs-done, known-limitation

**Comment by netice** [comment] 2018-12-17 04:04
I  also get  
```
transaction is too large  
```
errors when import data from my app.
It is not posibble to commit the transaction besides all data are imported without errors.
Is there any solution to deal with this use case? @knz
