### ISSUE TITLE
circleci: failed tests (13277): TestIntentResolution 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#4599] opened 2016-02-23 17:28 UTC
The following test appears to have failed:

[#13277](https://circleci.com/gh/cockroachdb/cockroach/13277):

```
1      storage/replica.go:1776
1      server/node.go:560
I0223 17:25:32.768586 430 stopper.go:273  draining; tasks left:
1      storage/replica.go:1776
I0223 17:25:32.772191 430 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- FAIL: TestIntentResolution (0.88s)
	intent_test.go:137: 0: unexpected non-local intents, expected [s x]: [s s x x]
=== RUN   TestBootstrapCluster
I0223 17:25:32.787138 430 raft/raft.go:459  [group 1] 1 became follower at term 5
I0223 17:25:32.789956 430 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0223 17:25:32.790100 430 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I0223 17:25:32.790230 430 raft/raft.go:472  [group 1] 1 became candidate at term 6
I0223 17:25:32.790368 430 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
I0223 17:25:32.790537 430 raft/raft.go:500  [group 1] 1 became leader at term 6
I0223 17:25:32.792632 430 storage/replica_command.go:1255  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1456248333.792s
I0223 17:25:32.798229 430 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--
I0223 17:25:49.724534 430 kv/range_cache.go:228  evict cached descriptor: key=/Meta1/System/"tsd!cr.node.exec.error-10m\x00\x01\x89\xf8\x06,!1" desc=<nil>
I0223 17:25:49.724887 430 client/db.go:485  failed batch: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:561: node 1 stopped
W0223 17:25:49.725160 430 ts/db.go:96  error writing time series data: failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:561: node 1 stopped
I0223 17:25:49.726848 430 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (1.97s)
FAIL
FAIL	github.com/cockroachdb/cockroach/server	20.091s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.02s)
=== RUN   TestRuntimeStatRecorder
I0223 17:25:46.922146 458 server/status/runtime.go:137  runtime stats: 4 goroutines, 3.38MiB active, 50000000.00cgo/sec, 748380.00/320730.00 %(u/s)time, 9855.63 %gc (3x)
--- PASS: TestRuntimeStatRecorder (0.00s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-02-23 17:31
Duplicate of #4579.

**Closed by bdarnell** 2016-02-23 17:31 UTC
Labels: test-failure
