### ISSUE TITLE
Test failure in CI build 9461

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3172] opened 2015-11-19 04:30 UTC
The following test appears to have failed:

[#9461](https://circleci.com/gh/cockroachdb/cockroach/9461):

```
I1119 04:29:10.339004 936 storage/replica_gc_queue.go:126  destroying local data from range 1
E1119 04:29:10.344129 936 storage/store.go:1574  storage/store.go:1573: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:PushTxn [/Local/Range/RangeDescriptor/"",/Min)}
E1119 04:29:10.344625 936 storage/store.go:1574  storage/store.go:1573: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:BeginTransaction [/Local/Range/RangeDescriptor/"",/Min), ConditionalPut [/Local/Range/RangeDescriptor/"",/Min), Put [/System/Meta2/"\xff\xff",/Min), Put [/System/Meta1/"\xff\xff",/Min)}
E1119 04:29:10.344897 936 storage/store.go:1574  storage/store.go:1573: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:EndTransaction [/Local/Range/RangeDescriptor/"",/Min)}
W1119 04:29:10.345740 936 multiraft/multiraft.go:1175  aborting configuration change: storage/store.go:1573: got committed raft command for 1 but have no range with that ID: {RangeID:1 OriginReplica:{NodeID:1 StoreID:1 ReplicaID:1} Cmd:EndTransaction [/Local/Range/RangeDescriptor/"",/Min)}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0xdd402f]

goroutine 6713 [running]:
github.com/coreos/etcd/raft.(*multiNode).run(0xc82038c720)
	/go/src/github.com/coreos/etcd/raft/multinode.go:264 +0x174f
created by github.com/coreos/etcd/raft.StartMultiNode
	/go/src/github.com/coreos/etcd/raft/multinode.go:71 +0x338

goroutine 1 [chan receive]:
testing.RunTests(0x19e7268, 0x203bc00, 0xcf, 0xcf, 0x1675501)
--
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:426 +0xb5
github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP.func1(0xc820091a80, 0x7f0bc854cfa0, 0xc8205bf800, 0xc8204a9ec0, 0xc82057f970)
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:195 +0x4d
created by github.com/cockroachdb/cockroach/rpc.(*Server).ServeHTTP
	/go/src/github.com/cockroachdb/cockroach/rpc/server.go:197 +0xa8c
FAIL	github.com/cockroachdb/cockroach/storage	18.998s
=== RUN   TestBatchBasics
I1119 04:29:19.246616 1009 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN   TestBatchGet
I1119 04:29:19.251128 1009 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.01s)
=== RUN   TestBatchMerge
I1119 04:29:19.258114 1009 storage/engine/rocksdb.go:132  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.01s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by BramGruneir** [comment] 2015-11-19 05:16
duplicate of #3010

**Closed by BramGruneir** 2015-11-19 05:16 UTC
Labels: test-failure
