### ISSUE TITLE
release: v19.1.7

### ISSUE THREAD

**Issue by otan** [cockroachdb/cockroach#44179] opened 2020-01-21 21:35 UTC
Candidate SHA: `a8444e28d3e7bf07c8ee0c6d5809e7466b57f6f9`
Deployment status: 
```
Return to check the workloads with:
+ echo '  roachprod ssh otan-release-v1916-4fa6d707:7'
  roachprod ssh otan-release-v1916-4fa6d707:7
+ echo or
or
+ echo '  roachprod ssh otan-release-v1917-a8444e28:7'
  roachprod ssh otan-release-v1917-a8444e28:7
```
Sentry: https://sentry.io/organizations/cockroach-labs/issues/?environment=v19.1.7&project=164528
Nightly Suite: https://teamcity.cockroachdb.com/viewLog.html?buildId=1702951&tab=queuedBuildOverviewTab
Release Qualification Suite: https://teamcity.cockroachdb.com/viewQueued.html?itemId=1702933&tab=queuedBuildOverviewTab
Cluster Status:
* http://otan-release-v1916-4fa6d707-0001.roachprod.crdb.io:26258/#/overview/list
* http://otan-release-v1917-a8444e28-0001.roachprod.crdb.io:26258/#/overview/list

 
[Release process checklist](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process)
 
Prep date: 21st January 2020
- [x] [Pick a SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-PickingaSHA), fill in `Candidate SHA` above, notify #release-announce of SHA.
- [x] [Tag the provisional SHA](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-TagtheprovisionalSHA)
- [x] [Publish provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Publishtheprovisionalbinaries)
- [x] [Check binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkbinaries) -- https://github.com/cockroachdb/bincheck/pull/164
- [x] [Deploy to test clusters](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-DeploytoTestClusters)
- [x] [Verify node crash reports](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Verifynodecrashreportsappearinsentry.io)
- [x] [Start release qualification suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] [Start nightly suite](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RuntheSuiteofNightlyRoachtests)
- [x] fill in `Deployment status` above with clusters and `Nightly Suite` with the link to Nightly TeamCity Job
 
One day after prep date:
- [x] [Get signoff on roachtest failures](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-RoachtestFailureSignoff)
 
- Keep an eye on clusters until release date. Do not proceed below until the release date.
 
Release date: 28th January 2020
- [x] [Check cluster status](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Checkclusterstatus)
- [x] [Tag release](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Tagtherelease)
- [x] [Bless provisional binaries](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-Blesstheprovisionalbinaries)
 
- For production or stable releases in the latest major release series
  - [ ] Update the [Homebrew Formula](https://github.com/cockroachdb/homebrew-tap/blob/master/Formula/cockroach.rb)
  - [ ] Update the image tag in our [Orchestrator configurations](https://wiki.crdb.io/wiki/spaces/CRDB/pages/73105625/Release+process#Releaseprocess-Orchestratorconfigurations)
  - [ ] Announce version to the [registration cluster](https://cockroachlabs.atlassian.net/wiki/spaces/ENG/pages/73105625/Release+process#Releaseprocess-AnnounceVersionToRegCluster)
 
- [x] Update docs
- [ ] External communications for release
- [x] Clean up provisional tag from repository

**Comment by otan** [comment] 2020-01-22 19:00
Roachtest Failures:

# GCE

## owner finding
[] acceptance/decommission
[] scaledata/filesystem_simulator/nodes=6
[] synctest
[] tpccbench/nodes=9/cpu=4/multi-region
[] version/mixed/nodes=5

## kv
[] kv0bench/nodes=20/cpu=8/sequential
[] kv0bench/nodes=20/cpu=8/shards=80/sequential

## bulkio
[] schemachange/invertedindex
[] schemachange/mixed/tpcc
[] schemachange/index/tpcc/w=1000
[] backupTPCC

## sqlexec
[] import/tpcc/warehouses=1000/nodes=4
[] tpccbench/nodes=9/cpu=4/chaos/partition

## appdev
[] typeorm
[] sqlalchemy
[] pgjdbc

# AWS

## kv
[] kv0bench/nodes=5/cpu=8/sequential/2nd_idx
[] kv0bench/nodes=5/cpu=8/shards=10/sequential/2nd_idx

**Comment by nvanbenschoten** [comment] 2020-01-22 21:41
The `tpccbench` tests both failed with the error:

`
Error: Could not postload: could not partition tables: Couldn't exec "\n\t\t\tALTER INDEX item@replicated_idx_2\n\t\t\tCONFIGURE ZONE USING num_replicas = COPY FROM PARENT, constraints = '{\"+rack=2\":1}', lease_preferences = '[[+rack=2]]'": pq: could not validate zone config: at least one replica is required
`

I'm not aware of anything changing around here the load generator recently, but I will investigate.

**Comment by nvanbenschoten** [comment] 2020-01-22 21:49
This was likely broken by https://github.com/cockroachdb/cockroach/commit/86fa0c024e0b5523333cd28b4f542873124692b3, which landed 3 months ago, but by no fault of its own.

`num_replicas = COPY FROM PARENT` leading to `at least one replica is required` indicates that zone config inheritance is not working properly.

**Comment by otan** [comment] 2020-01-22 22:06
was 86fa0c0 backported to 19.1?

**Comment by nvanbenschoten** [comment] 2020-01-22 22:24
> was 86fa0c0 backported to 19.1? or am i missing something?
We run `master`'s roachtests against each release branch, not their individual roachtests. There's been a long back and forth about whether this is the right thing to do.

I tracked the issue down to https://github.com/cockroachdb/cockroach/issues/44231. It looks like it was a regression in v19.1.6, so it won't be new in v19.1.7. I think that means that the issue is not a release blocker, but I'm not sure what our stance is on regressions in previous patch releases which are only caught later.

**Comment by nvanbenschoten** [comment] 2020-01-22 22:50
According to our release criteria, these are not blockers for this patch release.

**Comment by tbg** [comment] 2020-01-23 10:54
https://github.com/cockroachdb/cockroach/issues/42059#issuecomment-577033459 failed on the provisional commit, I am looking into this now.

**Comment by tbg** [comment] 2020-01-23 11:49
I cleared the one above. It's a fairly opaque failure, looks like perhaps a VM went unresponsive.

**Comment by tbg** [comment] 2020-01-23 11:52
Also signing off on acceptance/decommission. It's failing on some new UX improvement @knz added recently, nothing that should block a release.

**Comment by nvanbenschoten** [comment] 2020-01-23 19:01
All four of the `kv0bench` failures hit opaque `exit status 255` errors midway through their workload. I don't see anything indicating what caused these errors. However, I do notice that on GCP, both failed at exactly `06:45:03` and on AWS, both failed at exactly `07:00:37`. None of the tests started at the same time. So I feel ok with signing off on those as not being issues with the release itself.

**Comment by dt** [comment] 2020-01-23 20:16
the bulk-io BACKUP failure is a change in the test, not the code, and I'll fix it but it isn't a blocker.

The other bulk-io ones look like opaque context-cancelled which we can't really tell if/what went wrong.

**Comment by nvanbenschoten** [comment] 2020-01-27 18:17
Signing off on `scaledata/filesystem_simulator/nodes=6`. The failure appears to be the same flake present in https://github.com/cockroachdb/cockroach/issues/43273 and https://github.com/cockroachdb/cockroach/issues/43284.

**Comment by miretskiy** [comment] 2020-01-27 20:35
@jseldess Ready for docs update.

**Closed** 2020-01-31 15:30 UTC
