### ISSUE TITLE
kv: range lookup of key /Meta2/System/"node-idgen\x00" found only non-matching ranges

### ISSUE THREAD

**Issue by benesch** [cockroachdb/cockroach#20910] opened 2017-12-19 22:17 UTC
While running `make stress PKG=./pkg/ccl/sqlccl TESTS=TestBackupRestoreNegativePrimaryKey`, I got what seems to be a totally unrelated error:

```
I171219 22:14:27.931279 503 kv/dist_sender.go:355  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
F171219 22:14:27.932005 503 internal/client/range_lookup.go:221  [range-lookup,n?,range-lookup] range lookup of key /Meta2/System/"node-idgen\x00" found only non-matching ranges
goroutine 503 [running]:
github.com/cockroachdb/cockroach/pkg/util/log.getStacks(0x6dcb800, 0x1501d1d641e62312, 0x6a249ec, 0x1f)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:870 +0xcf
github.com/cockroachdb/cockroach/pkg/util/log.(*loggingT).outputLogEntry(0x6dcb860, 0xc400000004, 0x6a249ec, 0x1f, 0xdd, 0xc42106e1c0, 0x70)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/clog.go:754 +0x5c1
github.com/cockroachdb/cockroach/pkg/util/log.addStructured(0x6b6c380, 0xc420365cb0, 0xc400000004, 0x2, 0x5d78da1, 0x35, 0xc4213dd9d0, 0x1, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/structured.go:153 +0x308
github.com/cockroachdb/cockroach/pkg/util/log.logDepth(0x6b6c380, 0xc420365cb0, 0x1, 0x4, 0x5d78da1, 0x35, 0xc4213dd9d0, 0x1, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:56 +0x8c
github.com/cockroachdb/cockroach/pkg/util/log.Fatalf(0x6b6c380, 0xc420365cb0, 0x5d78da1, 0x35, 0xc4213dd9d0, 0x1, 0x1)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/log/log.go:150 +0x7e
github.com/cockroachdb/cockroach/pkg/internal/client.RangeLookup(0x6b6c380, 0xc420365cb0, 0x6b4c240, 0xc420d844b0, 0xc4202393c0, 0xd, 0xd, 0x2, 0x8, 0x300000000, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/internal/client/range_lookup.go:221 +0xbcb
github.com/cockroachdb/cockroach/pkg/kv.(*DistSender).RangeLookup(0xc420d844b0, 0x6b6c380, 0xc420365cb0, 0xc4202393c0, 0xd, 0xd, 0x6b6c300, 0xc420365cb0, 0xc420365b30, 0xc420022000, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/kv/dist_sender.go:287 +0xaa
github.com/cockroachdb/cockroach/pkg/kv.(*RangeDescriptorCache).performRangeLookup(0xc420fd4c60, 0x6b6c380, 0xc420365cb0, 0xc4202393c0, 0xd, 0xd, 0x6b7b500, 0xc420d9f040, 0xc420a57dd0, 0x4009104, ...)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:433 +0x31f
github.com/cockroachdb/cockroach/pkg/kv.(*RangeDescriptorCache).lookupRangeDescriptorInternal.func3(0x0, 0x0, 0x0, 0x0)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/kv/range_cache.go:309 +0x14f
github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).doCall(0xc420fd4ca0, 0xc4213a0050, 0xc42042e9c0, 0x13, 0xc4212c4300)
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:118 +0x2e
created by github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight.(*Group).DoChan
	/Users/benesch/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:111 +0x327
```

@nvanbenschoten is this your wheelhouse? Can you triage?

**Comment by benesch** [comment] 2017-12-19 22:17
Related: #19147

**Comment by nvanbenschoten** [comment] 2017-12-19 22:19
Yeah, this is a duplicate of #19147, thanks for reporting! We hadn't seen it for a while so I was just going to wait until code freeze to fix it, but since we're seeing this more frequently now, I guess I should revisit sooner.

**Closed by nvanbenschoten** 2017-12-19 22:19 UTC

**Comment by nvanbenschoten** [comment] 2017-12-19 22:30
It does seem like backup and restore tests are pretty good at reproducing this, which is good to know.

**Comment by benesch** [comment] 2017-12-19 22:45
Woo, glad I could help. Godspeed!
