### ISSUE TITLE
Cluster name cannot include dots, the error message says otherwise

### ISSUE THREAD

**Issue by MagicalTux** [cockroachdb/cockroach#126604] opened 2024-07-03 04:39 UTC
**Describe the problem**

Running cockroachdb with a cluster name containing dots produces this error message:

    ERROR: invalid argument "xxx.xxx" for "--cluster-name" flag: cluster name must contain only letters, numbers or the "-" and "." characters

**To Reproduce**

1. Pass `--cluster-name` a value that contains a dot.

**Expected behavior**

Either the dot should be accepted, or the error message changed to reflects dots aren't allowed.

**Additional data / screenshots**

Error message defined at: https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/flags.go#L207

The regexp is a few lines below:

```go
var errClusterNameInvalidFormat = errors.New(`cluster name must contain only letters, numbers or the "-" and "." characters`)

// clusterNameRe matches valid cluster names.
// For example, "a", "a123" and "a-b" are OK,
// but "0123", "a-" and "123a" are not OK.
var clusterNameRe = regexp.MustCompile(`^[a-zA-Z](?:[-a-zA-Z0-9]*[a-zA-Z0-9]|)$`)
```

The regexp includes hyphens, but no dots.

Jira issue: CRDB-39994

**Comment by MagicalTux** [comment] 2024-07-03 04:48
Looking at the documentation it seems that allowing dots was supposed to be the right behavior, in which case the regexp can be updated as below.

```go
var clusterNameRe = regexp.MustCompile(`^[a-zA-Z](?:[-.a-zA-Z0-9]*[a-zA-Z0-9]|)$`)
```

The tests in `pkg/cli/flags_test.go` in `func TestClusterNameFlag` should also have one valid cluster name with a dot added to ensure this is handled properly and doesn't break in the future.

**Comment by mohitsethia** [comment] 2024-07-13 19:34
Hi @rimadeodhar @MagicalTux , can I contribute to this?

**Comment by mohitsethia** [comment] 2024-12-18 20:43
Hi @rimadeodhar @MagicalTux , the PR & the issue is still open. Can we please close this issue if it is not going to be solved or merge the PR? cc: @annrpom

**Comment by rafiss** [comment] 2024-12-19 18:36
Thanks for reporting this. The spec actually disallows dots/periods:

> in CC serverless, cluster names match the regexp ^[a-z0-9][a-z0-9-]{4,98}[a-z0-9]$, i.e. they can't contain a period and never start or end with a hyphen, with a min of 6 characters and a max of 100.

https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20221212_virtual_cluster_routing.md

The reason is that these names are used to create URLs with the cluster name being a subdomain.

**Closed by rafiss** 2024-12-19 18:36 UTC
Labels: C-bug, E-easy, O-community, good first issue, E-quick-win, branch-release-23.1, branch-release-24.1, branch-release-23.2, T-db-server, branch-release-24.2
