### ISSUE TITLE
multiple test failiures

### ISSUE THREAD

**Issue by smg260** [cockroachdb/cockroach#98905] opened 2023-03-17 23:16 UTC
On 2023-03-17 BORS has been failing with multiple issues. This is an umbrella issue to link to, and can be updated as required.

changefeedccl/TestChangefeedRandomExpressions/kafka - 96532

changefeedccl/TestChangefeedSchemaChangeAllowBackfill 5 fails https://teamcity.cockroachdb.com/test/-626867411426624385?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true

changefeedccl.TestChangefeedNemeses 5 fails  https://teamcity.cockroachdb.com/test/4626064293122723814?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true
	
kvserver/TestDecommission - > 20 fails https://teamcity.cockroachdb.com/test/-6750397557676147176?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true

kvserver/TestSystemZoneConfigs - 3 fails staging - https://teamcity.cockroachdb.com/test/1437690617008383303?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&expandTestHistoryChartSection=true

kvserver/TestReplicaTombstone/(4) (4.1) raft messages to newer replicaID
multiregionccl/TestMultiRegionDataDriven/regional_by_table
logictest/distsql_join - 2 fails https://teamcity.cockroachdb.com/test/7978722684846482798?currentProjectId=Cockroach_Ci_TestsGcpLinuxX8664BigVm&branch=&expandTestHistoryChartSection=true

logictest/sequences_distsql

Jira issue: CRDB-25581

**Comment by aadityasondhi** [comment] 2023-03-20 20:51
`multiregionccl/TestMultiRegionDataDriven/regional_by_table` failed again on: https://github.com/cockroachdb/cockroach/pull/98077

https://github.com/cockroachdb/cockroach/pull/98077

**Comment by erikgrinaker** [comment] 2023-03-22 16:29
Fix for `TestReplicaTombstone` being merged in #99099.

**Comment by mgartner** [comment] 2023-03-22 20:19
@smg260 Do you have more context about the `logictest/sequences_distsql` flakes? I'm unable to reproduce any flakes with that test.

**Comment by mgartner** [comment] 2023-03-22 20:37
I'm also unable to reproduce a failure with `logictest/distsql_join`.

**Comment by rafiss** [comment] 2023-03-22 20:47
I believe all logictests running under the `fakedist-vec-off` config are currently affected by the "slow quiesce" flakes as seen in https://github.com/cockroachdb/cockroach/issues/99242. Here's an example of it affecting sequences_distsql: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/9172335?showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true

**Comment by smg260** [comment] 2023-03-22 21:12
@mgartner sorry for the lack of detail; it was getting late on Friday. @rafiss is correct, the flakes I saw were "slow quiesce". [This](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/9116215?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true) was in the staging branch.

**Closed** 2023-04-05 13:31 UTC
Labels: C-test-failure, branch-master, skipped-test, GA-blocker
