### ISSUE TITLE
circleci: failed tests (14637): TestStoreMetrics 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5313] opened 2016-03-16 19:00 UTC
The following test appears to have failed:

[#14637](https://circleci.com/gh/cockroachdb/cockroach/14637):

```
E160316 18:59:31.844388 storage/raft_transport.go:229  rpc error: code = 13 desc = "transport is closing"
W160316 18:59:31.845173 storage/replica.go:1324  group 2 on store 2 failed to send message to 1: storage/raft_transport.go:255: node stopped
I160316 18:59:31.846837 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160316 18:59:31.847064 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
I160316 18:59:31.847284 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- FAIL: TestStoreMetrics (0.27s)
	client_metrics_test.go:47: storage/client_metrics_test.go:84: sysbytes for store: actual 777 != expected 900
	client_metrics_test.go:47: storage/client_metrics_test.go:85: syscount for store: actual 8 != expected 9
	client_metrics_test.go:91: storage/client_metrics_test.go:199: verifyStats failed, aborting test.
=== RUN   TestRaftLogQueue
W160316 18:59:31.861652 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
I160316 18:59:31.867784 raft/raft.go:459  [group 1] 1 became follower at term 5
I160316 18:59:31.867952 raft/raft.go:235  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160316 18:59:31.868033 raft/raft.go:539  [group 1] 1 is starting a new election at term 5
I160316 18:59:31.868107 raft/raft.go:472  [group 1] 1 became candidate at term 6
I160316 18:59:31.868178 raft/raft.go:521  [group 1] 1 received vote from 1 at term 6
--
I160316 19:00:10.435475 storage/raft_transport.go:186  establishing Raft transport stream to node 2 at 127.0.0.1:35264
--- PASS: TestInOrderDelivery (0.61s)
=== RUN   Example_rebalancing
W160316 19:00:11.024905 gossip/gossip.go:898  not connected to cluster; use --join to specify a connected node
--- PASS: Example_rebalancing (0.88s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	46.400s
=== RUN   TestBatchBasics
I160316 19:00:18.102131 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.02s)
=== RUN   TestBatchGet
I160316 19:00:18.128201 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.02s)
=== RUN   TestBatchMerge
I160316 19:00:18.137538 storage/engine/rocksdb.go:149  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.02s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-17 13:40
Duplicate of #5208.

**Closed by petermattis** 2016-03-17 13:40 UTC
Labels: Robot, test-failure
