### ISSUE TITLE
sql: several privileges show without user action

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#46757] opened 2020-03-30 22:26 UTC
I started a cluster on roachprod and noticed that it made several privilege jobs:
![image](https://user-images.githubusercontent.com/22278911/77967812-e979af80-72b3-11ea-9239-4fb36ac43371.png)

```SQL
root@localhost:26257/defaultdb> show jobs;
        job_id       |   job_type    |     description     | statement | user_name |  status   | running_status |             created              |             started              |             finished             |             modified             | fraction_completed | error | coordinator_id
---------------------+---------------+---------------------+-----------+-----------+-----------+----------------+----------------------------------+----------------------------------+----------------------------------+----------------------------------+--------------------+-------+-----------------
  542428507073282049 | SCHEMA CHANGE | updating privileges |           | root      | succeeded | NULL           | 2020-03-30 22:14:03.417699+00:00 | 2020-03-30 22:14:03.426879+00:00 | 2020-03-30 22:14:03.429971+00:00 | 2020-03-30 22:14:03.429491+00:00 |                  1 |       |              1
  542428507010629633 | SCHEMA CHANGE | updating privileges |           | root      | succeeded | NULL           | 2020-03-30 22:14:03.398563+00:00 | 2020-03-30 22:14:03.407858+00:00 | 2020-03-30 22:14:03.411415+00:00 | 2020-03-30 22:14:03.410912+00:00 |                  1 |       |              1
  542428506943520769 | SCHEMA CHANGE | updating privileges |           | root      | succeeded | NULL           | 2020-03-30 22:14:03.378102+00:00 | 2020-03-30 22:14:03.387405+00:00 | 2020-03-30 22:14:03.390739+00:00 | 2020-03-30 22:14:03.390019+00:00 |                  1 |       |              1
  542428506877296641 | SCHEMA CHANGE | updating privileges |           | root      | succeeded | NULL           | 2020-03-30 22:14:03.357827+00:00 | 2020-03-30 22:14:03.368937+00:00 | 2020-03-30 22:14:03.372304+00:00 | 2020-03-30 22:14:03.371828+00:00 |                  1 |       |              1
(4 rows)

Time: 1.960419ms
```
What are these jobs? I can't see any information about these jobs.

To repro:
```
export CLUSTER=andy-3node

roachprod create $CLUSTER -n 4 --clouds=aws  --aws-machine-type-ssd=c5d.4xlarge

roachprod run $CLUSTER --  "sudo umount /mnt/data1; sudo mount -o discard,defaults,nobarrier /mnt/data1/; mount | grep /mnt/data1"

roachprod stage $CLUSTER:1-3 cockroach
roachprod stage $CLUSTER:4 workload

roachprod start $CLUSTER:1-3

roachprod adminurl --open $CLUSTER:1
```
V20.1.0-BETA.4-187-G93CB2EB

**Comment by awoods187** [comment] 2020-03-30 22:27
@jordanlewis I don't know where to sort this. What do you think?

**Comment by jordanlewis** [comment] 2020-03-31 04:02
I think this is caused by the privileges migration code at startup. I think that any time someone does an alter privilege action, you'll get one of these anonymous looking jobs.

@lucy-zhang I think knows something about this.

**Comment by lucy-zhang** [comment] 2020-03-31 04:45
Yeah, they're for a startup migration that updates the privileges on one of the system tables. In general we now make a lot of schema change-related jobs that we didn't before. I filed https://github.com/cockroachdb/cockroach/issues/46769 for making these job descriptions slightly more useful.

I don't know if it's possible to make any other UI improvements here. Maybe they can go under a separate "Type" from other schema changes?

**Comment by lucy-zhang** [comment] 2020-04-01 00:15
@knz Apart from all these UI issues, would it be possible to prevent the `remove public permissions on system.comments` migration from running at all on a fresh 20.1 cluster by setting `includedInBootstrap`? (I assume the change has been baked in for the comments table now.)

**Comment by knz** [comment] 2020-04-01 07:31
I did not know about / understand includedInBootstrap. Seems like it should be set in this case.

**Comment by knz** [comment] 2020-04-01 07:58
I'll send a PR.

also this makes me notice that this change needed to be backported. thanks for the reminder.

**Comment by lucy-zhang** [comment] 2020-04-28 13:10
Now that we're not creating these migration jobs for new clusters, I'm going to close this in favor of #46769, which covers improving the schema change job descriptions in general (including for `GRANT`).

**Closed by lucy-zhang** 2020-04-28 13:10 UTC
Labels: C-investigation
