### ISSUE TITLE
insert into tbl values (...) missing data vs insert into tbl (a,b,c) values (...) 

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#29688] opened 2018-09-06 23:17 UTC
separating the correctness issue from https://github.com/cockroachdb/cockroach/issues/29532.  For a quick repro, setup a single node on osx.  the load takes around 90seconds to complete.

- clone https://github.com/robert-s-lee/oltpbench/tree/cockroachdb.  
- From the script below, the first will fail.  The 2nd will work.  (all other combinations: interleave on/off and batch rewrite on/off do not make any difference).
- comparing count from two DML techniques,  customer and history tables have no data at all which probably is a bad thing.

table | no column name in DML | column name in DML | count diff
-- | -- | -- | --
district | 10 | 10 |  
item | 100000 | 100000 |  
stock | 100000 | 100000 |  
warehouse | 1 | 1 |  
customer | 0 | 30000 | Error
history | 0 | 31383 | Error
new_order | 8719 | 9038 | Error
oorder | 30000 | 31386 | Error
order_line | 300621 | 313892 | Error

```
ant clean
sed -i bak 's/COCKROACHDB.*),$/COCKROACHDB("org.postgresql.Driver", false, false, true),/' src/com/oltpbenchmark/types/DatabaseType.java
sed -i bak 's/tpcc?reWriteBatchedInserts=false/tpcc?reWriteBatchedInserts=true/' config/tpcc_config_cockroachdb.xml
ant
cockroach sql --insecure -e "drop database if exists tpcc cascade; create database tpcc"
time ./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --create=true --load=true -s 5 -v -o outputfile
./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --execute=true -s 5 -v -o outputfile

ant clean
sed -i bak 's/COCKROACHDB.*),$/COCKROACHDB("org.postgresql.Driver", false, true, true),/' src/com/oltpbenchmark/types/DatabaseType.java
sed -i bak 's/tpcc?reWriteBatchedInserts=false/tpcc?reWriteBatchedInserts=true/' config/tpcc_config_cockroachdb.xml
ant
cockroach sql --insecure -e "drop database if exists tpcc cascade; create database tpcc"
time ./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --create=true --load=true -s 5 -v -o outputfile
./oltpbenchmark -b tpcc -c config/tpcc_config_cockroachdb.xml --execute=true -s 5 -v -o outputfile
```

**Comment by jordanlewis** [comment] 2018-09-07 03:32
Thanks @robert-s-lee - I tracked this down. It's not as scary as it seems, thankfully!

The root cause is that we have some questionable behavior when inserting into a table with an implicit `rowid` column primary key. If no column names are specified, the first value in the `VALUES` clause will be assigned to that `rowid`.

In this instance, this is triggered by the fact that the`history` table has no primary key, so we give it an implicit `rowid` column. The reason there's no data in the `customer` table as well is that the load generator inserts into the `customer` and `history` tables in the same transaction.

So I think we have to fix the implicit `rowid` issue.

**Comment by jordanlewis** [comment] 2018-09-07 03:36
Ah, no, this is fine with `rowid`. It's broken by the recent changes with implicit `SERIAL` columns. I'm not too sure how those work, so @knz can you please take this over and fix?

**Comment by jordanlewis** [comment] 2018-09-07 03:42
Er, sorry, I spoke too soon. @robert-s-lee this is because you made an explicit `SERIAL` column in the DDL:

```
create table history (
  hist_id  serial PRIMARY KEY,    
  h_c_id   integer,
  h_c_d_id integer,
  h_c_w_id integer,
  h_d_id   integer,
  h_w_id   integer,
  h_date   timestamp,
  h_amount decimal(6,2),
  h_data   varchar(24),
  index (h_w_id, h_d_id),
  index (h_c_w_id, h_c_d_id, h_c_id)
);
```

If you move the `PRIMARY KEY` def to the end, after `h_data`, the problem disappears. The reason is that the column isn't hidden, so an insert into this table without specifying columns will naturally want to insert into the columns in order, and the `SERIAL` column is first, offsetting all of the columns by 1.

Does that make sense, @robert-s-lee? I confirmed the fix locally.

**Comment by jordanlewis** [comment] 2018-09-07 03:55
Going to close this as there's no DB bug in my opinion, but feel free to re-open if you think otherwise.

**Closed by jordanlewis** 2018-09-07 03:55 UTC
Labels: C-investigation
