### ISSUE TITLE
DbVisualizer error when selecting row id

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#24649] opened 2018-04-10 21:25 UTC
DbVisualizer error when selecting row id

An error occurred while performing the operation:
ERROR: syntax error at or near "."
Detail: source SQL:

`SELECT a.attname, a.atttypid, atttypmod 
FROM pg_catalog.pg_class ct JOIN pg_catalog.pg_attribute a ON (ct.oid = a.attrelid) 
JOIN pg_catalog.pg_namespace n ON (ct.relnamespace = n.oid) 
JOIN (SELECT i.indexrelid, i.indrelid, i.indisprimary, information_schema._pg_expandarray(i.indkey) 
AS keys FROM pg_catalog.pg_index i) i ON (a.attnum = (i.keys).x AND a.attrelid = i.indrelid) 
WHERE true AND n.nspname = 'information_schema' AND ct.relname = 'columns' AND i.indisprimary ORDER BY a.attnum`
^
Hint: try \h `

In logtostderr
`180410 21:23:27.945154 215 server/status/runtime.go:219  [n1] runtime stats: 167 MiB RSS, 163 goroutines, 133 MiB/13 MiB/163 MiB GO alloc/idle/total, 49 MiB/78 MiB CGO alloc/total, 58.39cgo/sec, 0.00/0.00 %(u/s)time, 0.00 %gc (0x)
I180410 21:23:30.787393 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] [NoTxn pos:873] executing SendError: syntax error at or near "."
I180410 21:23:30.787430 24081 sql/conn_executor.go:1805  [n1,client=127.0.0.1:52331,user=root] execution error: syntax error at or near "."`

**Comment by jordanlewis** [comment] 2018-04-10 21:30
Duplicate of #16971

**Closed** 2018-04-11 14:37 UTC
Labels: pg-compat
