### ISSUE TITLE
sql: missing transaction_isolation session var

### ISSUE THREAD

**Issue by LibreTitan** [cockroachdb/cockroach#19611] opened 2017-10-28 01:07 UTC
Microsof Access ODBC : "ERROR: unknow variable 'transaction_isolation' (#110)"

====================================================
server : CentOS 7.4
cockroachdb version: 1.1.1
binary in : /usr/local/bin

client: Windows 10
odbc: https://ftp.postgresql.org/pub/odbc/versions/msi/psqlodbc_10_00_0000-x64.zip
microsoft access: 2016

**Comment by jordanlewis** [comment] 2017-10-29 15:42
Thanks for the report. Looks like we're missing that session variable entirely.

This should be straightforward to implement, as setting and showing it exactly mirrors `SET/SHOW TRANSACTION ISOLATION LEVEL`. We'll add this to the next patch release if possible.

**Comment by mwistrom** [comment] 2017-12-11 21:10
I'd be interested in tackling this issue. It looks straight forward. Anything special I should be aware of?

**Comment by jordanlewis** [comment] 2017-12-11 21:25
Hi @mwistrom, in the intervening months we've added read-only support for `transaction_isolation`. Write support is still missing and your contribution would be appreciated.

It should indeed be straightforward. Check out `sql/vars.go` for the implementation of set/show against session variables and `internal/client/txn.go`for the implementation of setting isolation levels on a transaction.

Tests can be added to `sql/logictest/testdata/logic_test/txn` (run with `make testlogic FILES=txn`).

**Comment by mwistrom** [comment] 2017-12-13 07:49
It looks like this bug "ERROR: unknown variable 'transaction_isolation" is a duplicate of #18506, which is fixed in #20264.

**Comment by jordanlewis** [comment] 2017-12-13 13:16
I'm happy to keep this open to track the `SET transaction_isolation` variant which we still don't support.

**Closed** 2018-02-05 20:06 UTC
Labels: good first issue, pg-compat
