### ISSUE TITLE
stress: failed test in cockroach/server/status/status.test: TestMetricsRecorder

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5188] opened 2016-03-12 11:05 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/6a7f101fdcc8adda1e84d85b5546396964b622fa

Stress build found a failed test:

```
=== RUN   TestMetricsRecorder
--- FAIL: TestMetricsRecorder (1.04s)
	recorder_test.go:287: recorder did not yield expected time series collection; diff:
		 [[96].Datapoints[0].Value: 10 != 0 [97].Datapoints[0].Value: 10 != 0 [98].Datapoints[0].Value: 10 != 0 [99].Datapoints[0].Value: 10 != 0 [100].Datapoints[0].Value: 10 != 0 [101].Datapoints[0].Value: 10 != 0 [102].Datapoints[0].Value: 10 != 0 [103].Datapoints[0].Value: 10 != 0 [104].Datapoints[0].Value: 10 != 0 [105].Datapoints[0].Value: 10 != 0 [106].Datapoints[0].Value: 10 != 0 [107].Datapoints[0].Value: 10 != 0 [108].Datapoints[0].Value: 10 != 0 [109].Datapoints[0].Value: 10 != 0 [110].Datapoints[0].Value: 10 != 0 [111].Datapoints[0].Value: 10 != 0]
```

Run Details:

```
609 runs so far, 0 failures, over 5s
1193 runs so far, 0 failures, over 10s
1769 runs so far, 0 failures, over 15s
2334 runs so far, 0 failures, over 20s
2904 runs so far, 0 failures, over 25s
3473 runs so far, 0 failures, over 30s
4049 runs so far, 0 failures, over 35s
4625 runs so far, 0 failures, over 40s
5199 runs so far, 0 failures, over 45s
5770 runs so far, 0 failures, over 50s
6340 runs so far, 0 failures, over 55s
6799 runs so far, 0 failures, over 1m0s
7370 runs so far, 0 failures, over 1m5s
7943 runs so far, 0 failures, over 1m10s
8513 runs so far, 0 failures, over 1m15s
9076 runs so far, 0 failures, over 1m20s
9644 runs so far, 0 failures, over 1m25s
10203 runs so far, 0 failures, over 1m30s
10773 runs so far, 0 failures, over 1m35s
11348 runs so far, 0 failures, over 1m40s
11925 runs so far, 0 failures, over 1m45s
12491 runs so far, 0 failures, over 1m50s
13065 runs so far, 0 failures, over 1m55s
13626 runs so far, 0 failures, over 2m0s
14198 runs so far, 0 failures, over 2m5s
14774 runs so far, 0 failures, over 2m10s
15348 runs so far, 0 failures, over 2m15s
15914 runs so far, 0 failures, over 2m20s
16485 runs so far, 0 failures, over 2m25s
17053 runs so far, 0 failures, over 2m30s
17622 runs so far, 0 failures, over 2m35s
18190 runs so far, 0 failures, over 2m40s
18763 runs so far, 0 failures, over 2m45s
19338 runs so far, 0 failures, over 2m50s
19911 runs so far, 0 failures, over 2m55s
20479 runs so far, 0 failures, over 3m0s
21047 runs so far, 0 failures, over 3m5s
21622 runs so far, 0 failures, over 3m10s
22197 runs so far, 0 failures, over 3m15s
22773 runs so far, 0 failures, over 3m20s
23346 runs so far, 0 failures, over 3m25s
23919 runs so far, 0 failures, over 3m30s
24482 runs so far, 0 failures, over 3m35s
25050 runs so far, 0 failures, over 3m40s
25620 runs so far, 0 failures, over 3m45s
26186 runs so far, 0 failures, over 3m50s
26754 runs so far, 0 failures, over 3m55s
27319 runs so far, 0 failures, over 4m0s
27888 runs so far, 0 failures, over 4m5s
28459 runs so far, 0 failures, over 4m10s
29036 runs so far, 0 failures, over 4m15s
29605 runs so far, 0 failures, over 4m20s
30171 runs so far, 0 failures, over 4m25s
30741 runs so far, 0 failures, over 4m30s
31319 runs so far, 0 failures, over 4m35s
31879 runs so far, 0 failures, over 4m40s
32447 runs so far, 0 failures, over 4m45s
33019 runs so far, 0 failures, over 4m50s
33590 runs so far, 0 failures, over 4m55s
34161 runs so far, 0 failures, over 5m0s
34728 runs so far, 0 failures, over 5m5s
35302 runs so far, 0 failures, over 5m10s
35863 runs so far, 0 failures, over 5m15s
36432 runs so far, 0 failures, over 5m20s
37004 runs so far, 0 failures, over 5m25s
37579 runs so far, 0 failures, over 5m30s
38149 runs so far, 0 failures, over 5m35s
38722 runs so far, 0 failures, over 5m40s
39291 runs so far, 0 failures, over 5m45s
39856 runs so far, 0 failures, over 5m50s
40089 runs completed, 1 failures, over 5m53s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-13 16:53
Duplicate of #4855.

**Closed by petermattis** 2016-03-13 16:53 UTC
Labels: Robot, test-failure
