### ISSUE TITLE
circleci: failed tests: TestReplicateRogueRemovedNode 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#6238] opened 2016-04-22 15:45 UTC
The following test appears to have failed:

[#16687](https://circleci.com/gh/cockroachdb/cockroach/16687):

```
I160422 15:44:52.461011 storage/raft_transport.go:250  remote node 2 at 127.0.0.1:37086 closed Raft transport with error: rpc error: code = 13 desc = transport is closing
I160422 15:44:52.461098 storage/raft_transport.go:250  remote node 3 at 127.0.0.1:33264 closed Raft transport with error: rpc error: code = 13 desc = transport is closing
I160422 15:44:52.461697 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160422 15:44:52.461824 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
I160422 15:44:52.461907 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- FAIL: TestReplicateRogueRemovedNode (15.44s)
	testing.go:113: storage/client_raft_test.go:1357: condition failed to evaluate within 15s: storage/client_test.go:829: expected [16 0 5], got [16 0 0]
=== RUN   TestReplicateReAddAfterDown
I160422 15:44:52.523199 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
W160422 15:44:52.524281 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160422 15:44:52.526509 raft/raft.go:469  [group 1] 1 became follower at term 5
I160422 15:44:52.526754 raft/raft.go:238  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I160422 15:44:52.526784 raft/raft.go:549  [group 1] 1 is starting a new election at term 5
I160422 15:44:52.526812 raft/raft.go:482  [group 1] 1 became candidate at term 6
I160422 15:44:52.526837 raft/raft.go:531  [group 1] 1 received vote from 1 at term 6
I160422 15:44:52.526930 raft/raft.go:510  [group 1] 1 became leader at term 6
--
I160422 15:45:08.059241 stopper.go:352  draining; tasks left:
2      gossip/infostore.go:286
I160422 15:45:08.059277 stopper.go:352  draining; tasks left:
1      gossip/infostore.go:286
--- PASS: Example_rebalancing (0.11s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	44.988s
=== RUN   TestBatchBasics
I160422 15:44:38.321709 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160422 15:44:38.322968 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I160422 15:44:38.326402 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160422 15:44:38.327006 storage/engine/rocksdb.go:178  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I160422 15:44:38.329414 storage/engine/rocksdb.go:137  opening in memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:14
duplicate of #5775

**Closed by bdarnell** 2016-04-23 14:14 UTC
Labels: Robot, test-failure
