### ISSUE TITLE
*: perf regression in tpccbench/nodes=3/cpu=16 (and others) around Jun 18th

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#83273] opened 2022-06-23 14:11 UTC
<img width="763" alt="image" src="https://user-images.githubusercontent.com/5076964/175319951-f88a4399-9b66-43ad-bb1c-0c603fd13bc2.png">

https://roachperf.crdb.dev/?filter=&view=tpccbench%2Fnodes%3D3%2Fcpu%3D16&tab=gce

This is on both clouds and on most tpccbench flavors.

Jira issue: CRDB-16968

**Comment by tbg** [comment] 2022-06-23 15:01
Looking through https://roachperf.crdb.dev/perf.js, we hit (for the test above on GCE) 2565 WH on 6/16 and 780 on 6/18. (There is no data point on the 17th, probably roachtest infra failure).

@rachitgsrivastava the changepoint detection [actually caught this one too, on the 22nd](https://groups.google.com/a/cockroachlabs.com/g/test-eng/c/w6p0RgBQEt0/m/pcSwrwQ0AQAJ?pli=1), so pretty good! (Though it is of course a rather obvious regression).

**Comment by tbg** [comment] 2022-06-23 15:17
export BAD_SHA=8d34ef1ea15850ee1c70470610b6652df4c317de # [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=5500557&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel)
export GOOD_SHA=47df1bc3a28f705e56ff4efc3d81c6fc90e096b5 # [build](https://teamcity.cockroachdb.com/viewLog.html?buildId=5484799&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel)

Bisection table:

```
$ git log $BAD_SHA --not $GOOD_SHA^ --topo-order --merges --oneline | sed 's/^/- [ ] /g'
```

- [ ] 8d34ef1ea1 Merge #83035
- [ ] 57c79aed6a Merge #76582
- [ ] 8f23486add Merge #82911 #82950 #82988 #82998 #82999 #83006
- [ ] 6f6466f932 Merge #82889
- [ ] 50c375e8e6 Merge #80247 #83000
- [ ] 22a00bc4d1 Merge #82659
- [ ] 877542df9a Merge #82691 #82754
- [ ] 277921b6d7 Merge #82925 #82952
- [ ] 1634866e44 Merge #82937
- [ ] 2b082dd6d0 Merge #82789
- [ ] 8aea0c72f3 Merge #82795
- [ ] 47df1bc3a2 Merge #81275

**Comment by erikgrinaker** [comment] 2022-06-24 08:14
Looks like this recovered in last night's run:

<img width="757" alt="Screenshot 2022-06-24 at 10 09 14" src="https://user-images.githubusercontent.com/644420/175492733-3c279bce-6db3-4ba5-8831-dbd87b7ea09d.png">

Any thoughts on what's going on here? If I had to guess, I'd look at the Pebble bump. It was bumped again recently in #83163.

**Comment by tbg** [comment] 2022-06-24 18:28
It's likely the pebble bump, I'm re-running on 50c375e8e6 and if that commit is "bad" it's got to be pebble. (My first run failed for reasons that might be unrelated to it being a bad commit).

**Comment by tbg** [comment] 2022-06-24 20:34
Confirmed - it is highly likely to be the pebble bump at https://github.com/cockroachdb/cockroach/pull/83000.

@nicktrav mind seeing what we might've picked up there? And note that it seems to have been rectified in https://github.com/cockroachdb/cockroach/pull/83163.

**Comment by nicktrav** [comment] 2022-06-24 21:53
cc: @jbowens

**Comment by jbowens** [comment] 2022-06-25 03:48
I suspect that the regression was caused by the persistence of range keys (introduced in #83000). The `MVCCPut` code path was already configured to read using [a combined point-key/range-key iterator](https://github.com/cockroachdb/cockroach/blob/50c375e8e63ce9e04736d92b90d4efe795723bc0/pkg/storage/mvcc.go#L1091-L1094). The introduction of range-key persistence added a heavy penalty to iterator construction and seeks. 

The subsequent #83163 pebble bump included an optimization that maintains a separate in-memory level organization for files containing range keys. This eliminates all of the penalty introduced by persistence in the case where no range keys exist in the LSM.

**Comment by erikgrinaker** [comment] 2022-06-25 08:55
I suspected as much too, but it's interesting that TPCC is seeing such a dramatic effect when other write-heavy benchmarks show little-to-no impact. The most affected `kv0` benchmark was `kv0/enc=false/nodes=3/cpu=32/seq`:

<img width="756" alt="Screenshot 2022-06-25 at 10 52 45" src="https://user-images.githubusercontent.com/644420/175766069-d08fc961-76a0-4636-bc1c-8d380afc6559.png">

While it hardly registers on `kv0/enc=false/nodes=3/cpu=32`:

<img width="751" alt="Screenshot 2022-06-25 at 10 54 18" src="https://user-images.githubusercontent.com/644420/175766091-76df622d-b065-481c-9bd4-0d76feebd271.png">

**Comment by jbowens** [comment] 2022-06-25 16:41
On master we never actually write _any_ `RangeKeySet`s, `RangeKeyUnset`s or `RangeKeyDelete`s currently, right?

The only other regression that I'm aware of is related to `RangeKeyDelete`s. There was a bug that could cause Pebble to repeatedly rewrite a file containing a `RangeKeyDelete`, unproductively consuming a CPU core, write bandwidth and one of the three compaction concurrency slots. This regression was also fixed in the #83163 pebble bump.

**Comment by erikgrinaker** [comment] 2022-06-25 16:52
> On master we never actually write _any_ `RangeKeySet`s, `RangeKeyUnset`s or `RangeKeyDelete`s currently, right?

It's possible that we'll sometimes drop `RangeKeyDelete` when clearing key spans (typically when building SSTs), but we shouldn't in most cases. We'll address this in #83032. We otherwise don't write MVCC range tombstones anywhere yet.

In any case, it doesn't seem worth digging into this further now that it's recovered -- we'll be investigating this plenty later as we optimize MVCC range tombstones.

**Comment by nicktrav** [comment] 2022-06-25 17:36
Thank you both. Given that this has recovered, how do we feel about closing this one out? Happy to start bisecting the Pebble commits, but it seems like it's well understood that there were some regressions introduced in that batch, but we've mostly clawed it back.

One suggestion I have for us (Storage) coming out of this would be to _try_ and increase our bump cadence to aid in future bisecting exercises, given all the active development we have going on in Pebble. We currently aim (unofficially, via a Slackbot reminder) for a bump once a week. Maybe we need to up that to twice a week for a while and hold ourselves (more) accountable for getting that done - I'll work something out here.

**Comment by erikgrinaker** [comment] 2022-06-25 17:39
Yeah, may as well. Dissenters should feel free to reopen.

>Maybe we need to up that to twice a week for a while and hold ourselves (more) accountable for getting that done - I'll work something out here.

Seems like a good idea -- that'd be helpful in unblocking CRDB work as well.

**Closed by erikgrinaker** 2022-06-25 17:39 UTC
Labels: C-performance, A-roachperf-investigation
