### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestShowCreateTable

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6261] opened 2016-04-23 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/18d9f805a6ec17edc9f027e5f4853291db2c47c0

Stress build found a failed test:

```
=== RUN   TestShowCreateTable
W160423 06:29:13.215124 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160423 06:29:13.215685 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160423 06:29:13.217890 server/node.go:359  store store=0:0 ([]=) not bootstrapped
W160423 06:29:13.219036 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160423 06:29:13.222531 storage/replica_command.go:1439  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.222158772s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.222433309 +0000 UTC]
I160423 06:29:13.223134 server/node.go:309  **** cluster {d29b759e-48a4-4223-9afe-a262f7fd6934} has been created
I160423 06:29:13.223162 server/node.go:310  **** add additional nodes by specifying --join=127.0.0.1:45963
W160423 06:29:13.223178 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160423 06:29:13.223835 server/node.go:372  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8369844224 RangeCount:0}
I160423 06:29:13.223862 server/node.go:284  node ID 1 initialized
I160423 06:29:13.223912 storage/stores.go:287  read 0 node addresses from persistent storage
I160423 06:29:13.223972 server/node.go:493  connecting to gossip network to verify cluster ID...
I160423 06:29:13.224246 server/node.go:514  node connected via gossip and verified as part of cluster {"d29b759e-48a4-4223-9afe-a262f7fd6934"}
I160423 06:29:13.224632 server/node.go:337  [node=1] Started node with [[]=] engine(s) and attributes []
I160423 06:29:13.224669 server/server.go:366  starting https server at 127.0.0.1:42598
I160423 06:29:13.224685 server/server.go:367  starting grpc/postgres server at 127.0.0.1:45963
I160423 06:29:13.225445 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160423 06:29:13.229003 server/updates.go:147  No previous updates check time.
I160423 06:29:13.229184 storage/replica_command.go:1901  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160423 06:29:13.260932 storage/replica_command.go:1439  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.323405386s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.260776162 +0000 UTC]
I160423 06:29:13.261858 storage/replica_command.go:1901  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160423 06:29:13.267131 storage/replica_command.go:1439  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.323405386s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.267088703 +0000 UTC]
I160423 06:29:13.267433 storage/replica_command.go:1901  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160423 06:29:13.273593 storage/replica_command.go:1439  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.323405386s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.273552635 +0000 UTC]
I160423 06:29:13.273721 storage/replica_command.go:1901  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160423 06:29:13.364162 storage/replica_command.go:1439  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.411805549s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.364125618 +0000 UTC]
I160423 06:29:13.367118 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160423 06:29:13.367465 storage/replica_command.go:1901  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160423 06:29:13.376718 storage/replica_command.go:1439  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.426498864s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.376674353 +0000 UTC]
I160423 06:29:13.386028 storage/split_queue.go:100  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0 /Table/52/0]
I160423 06:29:13.386134 storage/replica_command.go:1901  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160423 06:29:13.394713 storage/replica_command.go:1439  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.444284477s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.394666166 +0000 UTC]
I160423 06:29:13.395802 storage/replica_command.go:1901  initiating a split of range=7 [/Table/51-/Max) at key /Table/52
I160423 06:29:13.412047 storage/replica_command.go:1439  range 8: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.461789798s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.411998397 +0000 UTC]
I160423 06:29:13.420660 storage/split_queue.go:100  splitting range=8 [/Table/52-/Max) at keys [/Table/53/0 /Table/54/0]
I160423 06:29:13.420755 storage/replica_command.go:1901  initiating a split of range=8 [/Table/52-/Max) at key /Table/53
I160423 06:29:13.429206 storage/replica_command.go:1439  range 9: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.478615819s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.42915732 +0000 UTC]
I160423 06:29:13.429332 storage/replica_command.go:1901  initiating a split of range=9 [/Table/53-/Max) at key /Table/54
I160423 06:29:13.446557 storage/replica_command.go:1439  range 10: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.496333957s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.446514497 +0000 UTC]
I160423 06:29:13.446923 storage/split_queue.go:100  splitting range=10 [/Table/54-/Max) at keys [/Table/55/0]
I160423 06:29:13.447225 storage/replica_command.go:1901  initiating a split of range=10 [/Table/54-/Max) at key /Table/55
I160423 06:29:13.476065 storage/replica_command.go:1439  range 11: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.525822646s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.476021154 +0000 UTC]
I160423 06:29:13.518247 storage/split_queue.go:100  splitting range=11 [/Table/55-/Max) at keys [/Table/56/0]
I160423 06:29:13.518371 storage/replica_command.go:1901  initiating a split of range=11 [/Table/55-/Max) at key /Table/56
I160423 06:29:13.541711 storage/replica_command.go:1439  range 12: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.59131044s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.541665501 +0000 UTC]
I160423 06:29:13.541835 storage/split_queue.go:100  splitting range=12 [/Table/56-/Max) at keys [/Table/57/0]
I160423 06:29:13.541958 storage/replica_command.go:1901  initiating a split of range=12 [/Table/56-/Max) at key /Table/57
I160423 06:29:13.558764 stopper.go:352  draining; tasks left:
1      storage/replica.go:529
1      storage/queue.go:383
I160423 06:29:13.558932 storage/replica_command.go:1439  range 13: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 405942h29m14.608658573s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-04-23 06:29:13.558857713 +0000 UTC]
I160423 06:29:13.559043 stopper.go:352  draining; tasks left:
1      storage/queue.go:383
I160423 06:29:13.559117 storage/split_queue.go:100  splitting range=13 [/Table/57-/Max) at keys [/Table/58/0]
E160423 06:29:13.559306 storage/queue.go:446  [split] range=13 [/Table/57-/Max): error: storage/split_queue.go:103: unable to split range=13 [/Table/57-/Max) at key "/Table/58/0": failed to send RPC: too many errors encountered (1 of 1 total): server/node.go:743: node 1 stopped
I160423 06:29:14.559517 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:45963: getsockopt: connection refused"; Reconnecting to "127.0.0.1:45963"
I160423 06:29:15.921242 /go/src/google.golang.org/grpc/clientconn.go:462  grpc: Conn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 127.0.0.1:45963: getsockopt: connection refused"; Reconnecting to "127.0.0.1:45963"
I160423 06:29:15.921449 /go/src/google.golang.org/grpc/clientconn.go:317  Failed to dial 127.0.0.1:45963: grpc: timed out trying to connect; please retry.
--- FAIL: TestShowCreateTable (2.71s)
	show_test.go:125: pq: sql/lease.go:108: table ID 57 not found
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
3 runs so far, 0 failures, over 35s
12 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
15 runs so far, 0 failures, over 50s
15 runs so far, 0 failures, over 55s
15 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
19 runs so far, 0 failures, over 1m10s
26 runs so far, 0 failures, over 1m15s
30 runs so far, 0 failures, over 1m20s
30 runs so far, 0 failures, over 1m25s
30 runs so far, 0 failures, over 1m30s
31 runs so far, 0 failures, over 1m35s
31 runs so far, 0 failures, over 1m40s
33 runs so far, 0 failures, over 1m45s
39 runs so far, 0 failures, over 1m50s
44 runs so far, 0 failures, over 1m55s
44 runs so far, 0 failures, over 2m0s
45 runs completed, 1 failures, over 2m4s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:15
Duplicate of #6232

**Closed by bdarnell** 2016-04-23 14:15 UTC
Labels: Robot, test-failure
