### ISSUE TITLE
add UUID type for postgres compatibility

### ISSUE THREAD

**Issue by glycerine** [cockroachdb/cockroach#16832] opened 2017-06-30 22:22 UTC
For compatibility with postgres, a feature could be added to cockroachdb: alias the type UUID to BYTES when creating schema.

I see in the FAQ where this is the suggested workaround. However for backwards compatibility with existing codebases that use postgres, it would nice to simply have UUID means BYTES, so that the SQL doen't have to change.

For example, I tried to run the Go web framework GoBuffalo on cockroach instead of postgres.  Some of the create schema commands won't work out of the box because they use the UUID type.
Reference: https://github.com/markbates/pop/issues/82

**Comment by jordanlewis** [comment] 2017-07-01 15:15
Duplicate of #8719, which was solved by #15930. You'll be able to use UUIDs in the next major release of CockroachDB.

**Closed by jordanlewis** 2017-07-01 15:15 UTC

**Comment by glycerine** [comment] 2017-07-07 02:22
@jordanlewis Does 1.0.3 just released include this?

**Comment by jordanlewis** [comment] 2017-07-07 02:30
No, it'll be included in 1.1 which is scheduled for release within the next couple of months.

If you like, and you don't mind living on the bleeding edge for the time being, you can try the feature out in an [alpha release](https://www.cockroachlabs.com/docs/v1.1-alpha.20170629.html).
