### ISSUE TITLE
failed to update store after split: range ID 11 already exists on store

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2887] opened 2015-10-22 16:00 UTC
during Put acceptance test. The error occurs in the split trigger's deferred `(*Store).SplitRange` when the `rangesByKey` btree is updated and, apparently, finds that the entry is already there in `addReplicaInternal`, which has only the split trigger as relevant call path.
However, `processRangeDescriptorUpdateLocked` also inserts in the btree, and is called by `ApplySnapshot` and `changeReplicasTrigger`, and  `MergeRange`.
My best bet is that the split happened earlier on other nodes, prompting auto-creation of the replica on this node, in which case the snapshot would populate `rangesByKey` too early.

>
F1022 15:33:16.038214 1 storage/replica_command.go:1273  failed to update Store after split: storage/
store.go:923: couldn't insert range range=11 ["00016168"-"\xff\xff") in rangesByKey btree: range for
Range ID 11 already exists on store
goroutine 40 [running]:
github.com/cockroachdb/cockroach/util/log.stacks(0xecdbaf801, 0x0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:884 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x1e58e00, 0x3, 0x18535a6, 0x1a,
 0x4f9, 0x0, 0xc82028bd90)
        /go/src/github.com/cockroachdb/cockroach/util/log/clog.go:741 +0x12f
github.com/cockroachdb/cockroach/util/log.AddStructured(0x0, 0x0, 0x3, 0x2, 0x14353e0, 0x26, 0xc8213f94b0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/structured.go:39 +0x121
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0x3, 0x14353e0, 0x26, 0xc8213f94b0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:65 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatalf(0x14353e0, 0x26, 0xc8213f94b0, 0x1, 0x1)
        /go/src/github.com/cockroachdb/cockroach/util/log/log.go:168 +0x66
github.com/cockroachdb/cockroach/storage.(*Replica).splitTrigger.func1()
        /go/src/github.com/cockroachdb/cockroach/storage/replica_command.go:1273 +0x113
github.com/cockroachdb/cockroach/storage/engine.(*rocksDBBatch).Commit(0xc8214959e0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/storage/engine/rocksdb.go:700 +0x19f
github.com/cockroachdb/cockroach/storage.(*Replica).applyRaftCommand(0xc82016c0c0, 0x7f68da2d8608, 0x

**Comment by bdarnell** [comment] 2015-10-23 18:02
Most likely a duplicate of #1644

**Closed** 2015-10-23 18:02 UTC
