### ISSUE TITLE
Wrong implementation of WINDOW ROWS clause

### ISSUE THREAD

**Issue by lukaseder** [cockroachdb/cockroach#42935] opened 2019-12-04 10:14 UTC
**Describe the problem**

It seems that the `WINDOW` function `ROWS` clause is implemented incorrectly. It seems to behave like `RANGE`

**To Reproduce**

Run this query:

```sql
select 
  a,
  b,
  count(*) over (order by b) as "no frame", 
  count(*) over (order by b range between unbounded preceding and current row) as "range frame", 
  count(*) over (order by b rows between unbounded preceding and current row) as "rows frame"
from (values (1, 1), (2, 1), (3, 2), (4, 2)) t (a, b)
order by a, b; 
```

The result is:

|a|b|no frame|range frame|rows frame|
|-|-|--------|-----------|----------|
|1|1|2|2|2|
|2|1|2|2|2|
|3|2|4|4|4|
|4|2|4|4|4|

(Observe the `rows frame` column)

In PostgreSQL and most other RDBMS, the result is:

```sql
|a|b|no frame|range frame|rows frame|
|-|-|--------|-----------|----------|
|1|1|2|2|1|
|2|1|2|2|2|
|3|2|4|4|3|
|4|2|4|4|4|
```

If possible, provide steps to reproduce the behavior:

**Environment:**
 - CockroachDB version: `CockroachDB CCL v19.2.1 (x86_64-unknown-linux-gnu, built 2019/11/18 23:23:55, go1.12.12)`
 - Server OS: Linux on Docker on Windows
 - Client app: JDBC

**Comment by yuzefovich** [comment] 2019-12-04 17:13
Thanks for the report!

I believe it is a duplicate of #38901, but I'll keep this issue open as well to make sure that it gets addressed.

**Closed** 2020-01-09 19:55 UTC
Labels: A-sql-execution, A-sql-pgcompat, C-bug
