### ISSUE TITLE
storage: create PutRawMVCCRangeKey method

### ISSUE THREAD

**Issue by msbutler** [cockroachdb/cockroach#84919] opened 2022-07-22 19:07 UTC
BACKUP currently uses `PutRawMVCC` quickly copy MVCC Kvs into a Backup SST, and as of #84875, Backup will use `PutMVCCRangeKey` to copy over rangekeys. A faster alternative to `PutMVCCRangeKey` would be `PutRawMVCCRangeKey`, but it doesn't exist yet! 

Jira issue: CRDB-17948

**Comment by erikgrinaker** [comment] 2022-07-23 10:46
Dupe of #84896

**Closed by erikgrinaker** 2022-07-23 10:46 UTC
Labels: C-enhancement
