### ISSUE TITLE
sql: temp schema cleaner job always fails

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#55086] opened 2020-09-30 22:33 UTC
**Describe the problem**

I have a local cluster that never cleans up it's temporary schemas.

The error log shows this:
```
406 sql/temporary_schema.go:468 ⋮ [n1] error during schema cleanup, retrying: ‹delete-temp-TABLE›: ‹unimplemented: schema change statement cannot follow
a statement that has written in the same transaction›
```

**To Reproduce**

```
root@:26257/defaultdb> SET CLUSTER SETTING sql.defaults.experimental_temporary_tables.enabled = 'true';

root@:26257/defaultdb> create temp table tmp(a int primary key);
CREATE TABLE

# exit the session, and start a new one

root@:26257/defaultdb> \d
           schema_name          |   table_name    | type  | estimated_row_count
--------------------------------+-----------------+-------+----------------------
  pg_temp_1601505050722443000_1 | tmp             | table |                   0
```

**Expected behavior**
The cleanup job should work and the temp schemas should be removed.

**Environment:**
Happening on CockroachDB master and release-20.2 branch.

**Comment by rafiss** [comment] 2020-10-27 19:57
I can't reproduce this any more...

**Comment by rafiss** [comment] 2020-10-27 20:06
But I did see this strange behavior. On a fresh cluster, the cluster setting doesn't seem to take effect right away:

```
root@:26257/defaultdb> SET CLUSTER SETTING sql.defaults.experimental_temporary_tables.enabled = 'true';
SET CLUSTER SETTING

Time: 47ms total (execution 47ms / network 0ms)

root@:26257/defaultdb> create temp table tmp(a int primary key);
ERROR: temporary tables are only supported experimentally
SQLSTATE: 0A000
HINT: See: https://go.crdb.dev/issue-v/46260/v20.2
--
You can enable temporary tables by running `SET experimental_enable_temp_tables = 'on'`.
```

**Comment by gnanakeethan** [comment] 2020-11-19 07:01
@rafiss I am experiencing this problem. The job has not failed, but in running condition ever since. 

Even through server restarts and upgrades.

**Comment by arulajmani** [comment] 2020-12-14 16:22
@rafiss do you happen to remember if you created a database right before the statements in your repro? For context, @adityamaru and I have been trying to look at this a bit more over the last few days and we've consistently seen this error in 20.1 and 20.2 if a database is created and the steps you mentioned above are performed very quickly after the db creation.  It's worth noting that this no longer reproduces on master, and seems to have been fixed by https://github.com/cockroachdb/cockroach/commit/86eee612ff1fe7e825ed230b5ad93c3814609998 which was merged by @lucy-zhang. The patch above switches to using `descs.Txn` which ensures descriptors are properly leased. This, and the timing factor mentioned above, makes me suspect that this was a database descriptor leasing issue. 

It's worth noting this issue pops up even when there is no relationship between the temp table and the database created, because we read all database descriptors during the cleanup job. 

This seems to happen in 20.1 and 20.2 when a database is created

**Comment by rafiss** [comment] 2020-12-14 16:50
I remember repro-ing by opening a session and just running those commands I had in my issue description. But maybe I did something else weird...

So there's no issue with that `retryFunc` logic we were looking at before?

**Comment by rafiss** [comment] 2020-12-14 20:01
@arulajmani I think here is a reliable repro:

```
# brand new cluster, start session
create database d;
# wait any amount of time. logout. whatever

set experimental_enable_temp_tables=true;
create temp table foo (id INT);
# logout

# start new session
show tables;

# output includes temp table from last session
```

**Comment by adityamaru** [comment] 2020-12-14 20:05
@rafiss this is a correct repro, if you enable logging on the server side you'll see the error message immediately on session shutdown.

**Comment by rafiss** [comment] 2020-12-18 23:33
fixed by https://github.com/cockroachdb/cockroach/pull/57922

**Closed** 2020-12-21 19:04 UTC
Labels: A-schema-descriptors, C-bug
