### ISSUE TITLE
Allow documentation of views

### ISSUE THREAD

**Issue by rasmuslund** [cockroachdb/cockroach#50530] opened 2020-06-23 08:08 UTC
Is seems like I cannot document views, e.g.:
```
COMMENT ON VIEW my_view IS
    'Some excellent documentation text'
```
I have some fairly complex views. It would be nice to be able to explain what they do.

**Comment by solongordon** [comment] 2020-06-23 16:29
Thanks for the request. Closing as duplicate of #44135.

**Closed by solongordon** 2020-06-23 16:29 UTC
Labels: O-community, X-blathers-oncall
