### ISSUE TITLE
roachtest: TC timing out with test downloading debug.zip after acceptance/bank/cluster-recovery timeout

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#37200] opened 2019-04-30 02:34 UTC
The roachtests that we run as part of the Github CI seem to sometimes time out after spending the better part of an hour stuck on downloading a debug.zip after `acceptance/bank/cluster-recovery` has hit its 10m timeout.
Recent examples:
https://teamcity.cockroachdb.com/viewLog.html?buildId=1265950&buildTypeId=Cockroach_UnitTests&tab=buildResultsDiv
https://teamcity.cockroachdb.com/viewLog.html?buildId=1265767&buildTypeId=Cockroach_UnitTests&tab=buildResultsDiv

Possibly related #35326 ?

**Comment by andreimatei** [comment] 2019-04-30 02:34
Note that in these TC runs, roachtest runs with `--local`.

**Comment by tbg** [comment] 2019-04-30 08:16
That the roachtest failures stall the test is roachtest's fault. The test times out, we get the debug zip (successfully, btw, but the `.status()` API is ever misleading because it never asks you to clear the status). Then the harness waits for the actual test to continue, which of course it never does (though, to be fair, its context is now canceled, it just doesn't seem to care about that). Often, destroying the cluster saves us, but in this case we don't do that because we're running subtests.

**Comment by tbg** [comment] 2019-04-30 08:31
The problem is that we `t.Fatal` inside of https://github.com/cockroachdb/cockroach/blob/5f8adee5daf015f6c40dc4971c9bef977adeb19a/pkg/cmd/roachtest/bank.go#L457 but then there's this deferred `wg.Wait()`: https://github.com/cockroachdb/cockroach/blob/5f8adee5daf015f6c40dc4971c9bef977adeb19a/pkg/cmd/roachtest/bank.go#L436

Someone's not releasing their WG. Pretty sure it's the chaos monkey getting stuck in

https://github.com/cockroachdb/cockroach/blob/5f8adee5daf015f6c40dc4971c9bef977adeb19a/pkg/cmd/roachtest/bank.go#L238-L240

and it's probably because this call hangs (which is what has the test failing originally):

https://github.com/cockroachdb/cockroach/blob/5f8adee5daf015f6c40dc4971c9bef977adeb19a/pkg/cmd/roachtest/bank.go#L62-L64

Honestly this test is a mess. I'm going to send a patch addressing the problem at hand, but these tests are going to cause more problems than they're ever going to find. @nvanbenschoten is it possible that these fail for the same reasons as https://github.com/cockroachdb/cockroach/pull/37199?

**Comment by tbg** [comment] 2019-04-30 08:59
Weird, I'm running this code:

https://github.com/cockroachdb/cockroach/blob/fb93d1cb2abf83e51fdca3b5aa2cc56e24a4bca2/pkg/cmd/roachtest/bank.go#L58-L78

and it fails with

> after 3.3s: pq: query execution canceled due to statement timeout

`statement_timeout` claims to be in seconds and I specified 15. Weird.

**Comment by tbg** [comment] 2019-04-30 09:01
Ah nvm, it's ms

**Comment by tbg** [comment] 2019-04-30 09:12
Caught the stall in the act -- with all my preventions in. Will take a look.

**Comment by tbg** [comment] 2019-04-30 09:18
Cluster is running, but everything seems pretty screwed up. Here's the network diag page:

<img width="706" alt="image" src="https://user-images.githubusercontent.com/5076964/56951765-f4264480-6b38-11e9-9ef9-fa1872169355.png">

Ranges are marked as "unavailable" with status reports like the one below. Not sure why this range is supposedly unavailable. It looks like all nodes except for n3 are live (n3 has its heartbeats time out).

![image](https://user-images.githubusercontent.com/5076964/56952068-a78f3900-6b39-11e9-9cf3-2399952c7b6a.png)

**Comment by tbg** [comment] 2019-04-30 09:30
n3 is messed up good. I don't fully understand why that would ruin the network diagnostics page, but basically n3 can't heartbeat itself because of this:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/5076964/56952467-b1656c00-6b3a-11e9-89f5-fdf9729966ea.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/5076964/56952543-d4901b80-6b3a-11e9-9981-8143b132288d.png">

Logspy tells me this from n3:

```
r1: sending batch 1 Scan to (n1,s1):1
reply error Scan [/Meta1/System/NodeLiveness/NULL/NULL,/Meta2/""): failed to send RPC: leaseholder s4 (via (n1,s1):1) not in cached replicas [(n1,s1):1]
evicting range descriptor on *roachpb.SendError and backoff for re-lookup: r1:/{Min-System/NodeLiveness} [(n1,s1):1, next=2, gen=0]

[1s break]

<repeats>
```

The actual leaseholder is n4. It looks like we're potentially getting stuck in a loop in which we deterministically try n1 even though we ought to hit n4 to get things unstuck.

**Comment by tbg** [comment] 2019-04-30 09:52
From n3 via `./cockroach debug gossip-values --port 26261 --insecure`

> "first-range": r1:/{Min-System/NodeLiveness} [(n1,s1):1, next=2, gen=0]

So on n3, no matter how hard you try, that's what you'll get as a descriptor. This explains why n3 is broken. But shouldn't the actual descriptor contain n1, n3, and n4? Oh well:

```
$ for p in 26257 26259 26261 26263; do ./cockroach debug gossip-values --port $p --insecure | grep first-range; done
"first-range": r1:/{Min-System/NodeLiveness} [(n3,s3):4, (n1,s1):5, (n4,s4):3, next=6, gen=0]
"first-range": r1:/{Min-System/NodeLiveness} [(n3,s3):4, (n1,s1):5, (n4,s4):3, next=6, gen=0]
"first-range": r1:/{Min-System/NodeLiveness} [(n1,s1):1, next=2, gen=0]
"first-range": r1:/{Min-System/NodeLiveness} [(n3,s3):4, (n1,s1):5, (n4,s4):3, next=6, gen=0]
```

Here's n1 and n3 compared (from `/_status/gossip/local`)

```
    "first-range": {
      "value": {
        "rawBytes": "3qOVxgMIARIAGgsEAGxpdmVuZXNzLSIGCAMQAxgEIgYIARABGAUiBggEEAQYAygG",
        "timestamp": {
          "wallTime": "1556617250930647000",
          "logical": 0
        }
      },
      "origStamp": "1556617250930648000",
      "ttlStamp": "9223372036854775807",
      "hops": 1,
      "nodeId": 4,
      "peerId": 4
    },

    "first-range": {
      "value": {
        "rawBytes": "B/zJHwMIARIAGgsEAGxpdmVuZXNzLSIGCAEQARgBKAI=",
        "timestamp": {
          "wallTime": "1556615409299004000",
          "logical": 0
        }
      },
      "origStamp": "1556615409299005000",
      "ttlStamp": "9223372036854775807",
      "hops": 2,
      "nodeId": 1,
      "peerId": 4
    },
```

First we read off that n1 has the newer version of the descriptor as expected:

```
# timestamp.wallTime
n1 1556617250930647000
n3 1556615409299004000
```

The origStamp reflects the same ordering, i.e. n3's is lower than n1's.

```
# origStamp
n1 1556617250930648000
n3 1556615409299005000

The TTL stamp is the same.

```
# ttlStamp
n1 9223372036854775807
n3 9223372036854775807
```

This looks like some gossip problem. n3 should've replaced its stale first range desc with the new one, but it didn't and is instead holding on to an old copy from the early days of the cluster when n1 was the only member of the first range.

Oh... I think the problem is less subtle than I thought:

```
I190430 09:49:07.566491 256 gossip/gossip.go:557  [n3] gossip status (stalled, 4 nodes)
gossip client (0/3 cur/max conns)
gossip server (0/3 cur/max conns, infos 13/58 sent/received, bytes 2526B/27780B sent/received)
```

Looks like there aren't any gossip connections at all any more. Time to look into that.

**Comment by tbg** [comment] 2019-04-30 10:05
From logspy, grepping for gossip:

```
I190430 09:54:29.544974 49100 vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:449  [n3] circuitbreaker: gossip 127.0.0.1:26261->127.0.0.1:26257 event: BreakerReady
I190430 09:54:29.545006 49100 vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:449  [n3] circuitbreaker: gossip 127.0.0.1:26261->127.0.0.1:26257 event: BreakerFail
I190430 09:54:29.545071 49100 vendor/github.com/cockroachdb/circuitbreaker/circuitbreaker.go:327  [n3] circuitbreaker: gossip 127.0.0.1:26261->127.0.0.1:26257 fail (not tripped): initial connection heartbeat failed: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:26257: connect: connection refused"
```

> dial tcp 127.0.0.1:26257: connect: connection refused

indicates that n1 isn't running. But n1 **is** running and is actually not doing nearly as poorly as n3. I think we maybe are keeping an old connection in the connection pool that will eternally pretend n1 is down.

This makes me think that we're perhaps dealing with fallout from #34158. The code that wants to start outgoing gossip clients (which is what n3 needs and is trying to do in the log above) is https://github.com/cockroachdb/cockroach/blob/5bce267fc1bcc00fbcd941a9cebc0c4a431170c9/pkg/gossip/gossip.go#L1550-L1559

The problem is this line https://github.com/cockroachdb/cockroach/blob/66414991483af5c3c98537a5d2f550472bc14693/pkg/rpc/context.go#L735

where basically we say "if you established a conn to node1 at :26257, also make this the conn that you get for unspecified nodeID at :26257". But then we only delete the first of the two map entries, meaning that those asking for unspecified nodeID will get the broken conn handed out forever. I guess in this run we happened to connect to n1 under its nodeID before doing it "anonymously" (only Gossip does the latter).

I'm going to whip up a fix, it's reproducible enough so we shall see.

**Comment by tbg** [comment] 2019-04-30 10:34
cc @knz on the above

I was also surprised that the statement timeout didn't cancel the client request, which I think is this one:

```
1: chan receive [43 minutes] [Created by conn.go:515 (*conn).processCommandsAsync({[] [] false})]
Stack
- internal.go:569 (*internalExecutorImpl).execInternal({[{824638694816 #412} {123016480 #83} {824731043664 #1179} {115272811 #55} {20 } {0 } {1 } {115126376 #54} {4 } {824731043616 #1178}] [] true})
- internal.go:255 (*internalExecutorImpl).queryInternal({[{824638694816 #412} {123016352 #80} {824634089616 #172} {115272811 #55} {20 } {0 } {1 } {0 } {0 } {0 }] [] true})
- internal.go:226 (*InternalExecutor).Query({[{824638694816 #412} {123016352 #80} {824634089616 #172} {115272811 #55} {20 } {0 } {116022105 #60} {204 } {824722279872 #906} {1 }] [] true})
- stats_cache.go:359 (*TableStatisticsCache).getTableStatsFromDB({[{824642607552 #633} {123016352 #80} {824634089616 #172} {53 } {824637363204 #340} {109381024 #38} {824722288464 #910} {0 } {0 }] [] false})
- stats_cache.go:233 (*TableStatisticsCache).addCacheEntryLocked.func1({[{824642607552 #633} {123016352 #80} {824634089616 #172} {53 } {824727143016 #1102} {824727143040 #1103}] [] false})
- stats_cache.go:234 (*TableStatisticsCache).addCacheEntryLocked({[{824642607552 #633} {123016352 #80} {824634089616 #172} {53 } {0 } {0 } {0 } {0 } {0 }] [] false})
- stats_cache.go:171 (*TableStatisticsCache).GetTableStats({[{824642607552 #633} {123016352 #80} {824634089616 #172} {824633720885 #158} {0 } {0 } {0 } {0 } {0 }] [] false})
- opt_catalog.go:280 (*optCatalog).dataSourceForTable({[{824727685824 #1126} {123016480 #83} {824727677040 #1122} {824727764992 #1129} {824727913472 #1133} {824727685848 #1127} {824727677040 #1122} {123175808 #96} {824727683920 #1124} {824727685848 #1127}] [] false})
- opt_catalog.go:244 (*optCatalog).dataSourceForDesc({[{824727685824 #1126} {123016480 #83} {824727677040 #1122} {824727633920 #1118} {824727913472 #1133} {824727685848 #1127} {0 } {824727913472 #1133} {0 } {0 }] [] false})
- opt_catalog.go:167 (*optCatalog).ResolveDataSource({[{824727685824 #1126} {123016480 #83} {824727677040 #1122} {3839461022865227776 #1342} {824727381184 #1113} {0 } {0 } {0 } {0 } {0 }] [] true})
- util.go:448 (*Builder).resolveDataSource({[{824727505984 #1116} {824727381184 #1113} {824633720840 #157} {113095840 #43} {113856576 #50} {0 } {0 } {0 } {0 } {0 }] [] true})
- util.go:434 (*Builder).resolveTable({[{824727505984 #1116} {824727381184 #1113} {824633720840 #157} {0 } {0 } {0 } {0 } {0 } {0 } {0 }] [] true})
- update.go:90 (*Builder).buildUpdate({[{824727505984 #1116} {824722198464 #899} {824723026432 #947} {0 }] [] false})
- builder.go:217 (*Builder).buildStmt({[{824727505984 #1116} {123041888 #89} {824722198464 #899} {824723026432 #947} {4 }] [] false})
- builder.go:152 (*Builder).Build({[{824727505984 #1116} {0 } {0 }] [] false})
- plan_opt.go:404 (*optPlanningCtx).buildExecMemo({[{824727685816 #1125} {123016480 #83} {824727677040 #1122} {824727628312 #1117} {74695395 #33} {123016480 #83} {824727677040 #1122}] [] false})
- plan_opt.go:147 (*planner).makeOptimizerPlan({[{824727683920 #1124} {123016480 #83} {824727677040 #1122} {115328611 #57} {25 } {913694162777563859 #1332} {1556615412 #137}] [] false})
- conn_executor_exec.go:761 (*connExecutor).makeExecPlan({[{824727683072 #1123} {123016480 #83} {824727677040 #1122} {824727683920 #1124} {6 } {67166031 #13}] [] false})
- conn_executor_exec.go:648 (*connExecutor).dispatchToExecutionEngine({[{824727683072 #1123} {123016480 #83} {824727677040 #1122} {824727683920 #1124} {186288608 #117} {824723047456 #949} {0 } {0 }] [] false})
- conn_executor_exec.go:412 (*connExecutor).execStmtInOpenState({[{824727683072 #1123} {123016480 #83} {824727677040 #1122} {123041888 #89} {824722198464 #899} {824727707680 #1128} {187 } {0 } {0 } {0 }] [] true})
- conn_executor_exec.go:100 (*connExecutor).execStmt({[{824727683072 #1123} {123016480 #83} {824727677040 #1122} {123041888 #89} {824722198464 #899} {824727707680 #1128} {187 } {0 } {0 } {0 }] [] true})
- conn_executor.go:1200 (*connExecutor).execCmd({[{824727683072 #1123} {123016480 #83} {824727676992 #1121} {0 } {0 }] [] false})
- conn_executor.go:1136 (*connExecutor).run({[{824727683072 #1123} {123016288 #3} {824727380992 #1112} {824634780728 #183} {21504 } {86016 } {824634780880 #184} {824727491408 #1115} {0 } {0 }] [] false})
- conn_executor.go:436 (*Server).ServeConn({[{824645485248 #819} {123016288 #3} {824727380992 #1112} {824727683072 #1123} {21504 } {86016 } {824634780880 #184} {824727491408 #1115} {0 } {0 }] [] false})
- conn.go:580 (*conn).processCommandsAsync.func1({[{824637982297 #372} {824637859936 #366} {123016288 #3} {824727380992 #1112} {824727491408 #1115} {824645485248 #819} {824634871040 #186} {123030816 #87} {824637859872 #365} {824726718720 #1098}] [] true})

```

```
- range_cache.go:370 (*RangeDescriptorCache).lookupRangeDescriptorInternal({[{824636920672 #307} {123016480 #83} {824731047456 #1181} {824638506024 #399} {3 } {8 } {0 } {0 } {0 } {0 }] [] true})
- range_cache.go:244 (*RangeDescriptorCache).LookupRangeDescriptorWithEvictionToken({[{824636920672 #307} {123016480 #83} {824731047456 #1181} {824638506024 #399} {3 } {8 } {0 } {4594572339843379968 #1343} {824644100960 #694} {824722298208 #914}] [] true})
- dist_sender.go:456 (*DistSender).getDescriptor({[{824636077408 #195} {123016480 #83} {824731047456 #1181} {824638506024 #399} {3 } {8 } {0 } {824644100864 #693} {50000000 #8} {1000000000 #136}] [] true})
- range_iter.go:160 (*RangeIterator).Seek({[{824725218000 #1061} {123016480 #83} {824731047456 #1181} {824638506024 #399} {3 } {8 } {0 }] [] false})
- span_resolver.go:247 (*spanResolverIterator).Seek({[{824646973056 #833} {123016480 #83} {824731047456 #1181} {824638506024 #399} {3 } {8 } {824638506040 #400} {3 } {3 } {0 }] [] true})
- distsql_physical_planner.go:747 (*DistSQLPlanner).PartitionSpans({[{824642273920 #626} {824724283488 #1018} {824723299264 #976} {1 } {1 } {824728465792 #1144} {0 } {0 } {0 } {0 }] [] false})
- distsql_physical_planner.go:1079 (*DistSQLPlanner).createTableReaders({[{824642273920 #626} {824724283488 #1018} {824730256192 #1158} {0 } {0 } {0 } {0 } {0 } {0 } {0 }] [] true})
- distsql_physical_planner.go:2288 (*DistSQLPlanner).createPlanForNode({[{824642273920 #626} {824724283488 #1018} {123024096 #85} {824730256192 #1158} {0 } {123243424 #102} {824637363360 #342} {0 } {0 } {0 }] [] true})
- distsql_physical_planner.go:2323 (*DistSQLPlanner).createPlanForNode({[{824642273920 #626} {824724283488 #1018} {123024800 #86} {824725217920 #1060} {37 } {824727980376 #1135} {1 } {1 } {1556615413 #138} {67746139 #20}] [] true})
- distsql_running.go:835 (*DistSQLPlanner).PlanAndRun({[{824642273920 #626} {123016480 #83} {824731047456 #1181} {824730775952 #1170} {824724283488 #1018} {824644194816 #703} {123024800 #86} {824725217920 #1060} {824645488064 #820}] [] false})
- conn_executor_exec.go:895 (*connExecutor).execWithDistSQLEngine({[{824730774912 #1168} {123016480 #83} {824731047456 #1181} {824730775760 #1169} {3 } {186040208 #116} {824730549664 #1164} {1 } {0 } {0 }] [] false})
- conn_executor_exec.go:731 (*connExecutor).dispatchToExecutionEngine({[{824730774912 #1168} {123016480 #83} {824731047456 #1181} {824730775760 #1169} {186040208 #116} {824730549664 #1164} {0 } {0 }] [] false})
- conn_executor_exec.go:412 (*connExecutor).execStmtInOpenState({[{824730774912 #1168} {123016480 #83} {824731047456 #1181} {123039008 #88} {824725105728 #1056} {116022106 #61} {202 } {1 } {824725113952 #1057} {9 }] [] true})
- conn_executor_exec.go:100 (*connExecutor).execStmt({[{824730774912 #1168} {123016480 #83} {824731047456 #1181} {123039008 #88} {824725105728 #1056} {116022106 #61} {202 } {1 } {824725113952 #1057} {9 }] [] true})
- conn_executor.go:1259 (*connExecutor).execCmd({[{824730774912 #1168} {123016480 #83} {824731047408 #1180} {0 } {0 }] [] false})
- conn_executor.go:1136 (*connExecutor).run({[{824730774912 #1168} {123016480 #83} {824731043664 #1179} {824642584064 #629} {0 } {0 } {0 } {0 } {0 } {0 }] [] false})
- internal.go:205 (*internalExecutorImpl).initConnEx.func1({[{824730774912 #1168} {123016480 #83} {824731043664 #1179} {824638694816 #412} {824638149472 #388} {0 } {824637363344 #341}] [] false})
```

Perhaps the real problem there is the failure to observe context cancellation in `lookupRangeDescriptorInternal`, though I think that it would.

**Comment by tbg** [comment] 2019-04-30 11:11
As far as the (or one) root cause goes, I'm fairly confident at this point that #37204 prevents the test from failing. When I tried initially, I got the stall within the first 6 rounds. Now I've run a lot more. Maybe 30? 40?

**Comment by tbg** [comment] 2019-04-30 13:04
I left this running until just now and it never got stuck again after what must've been 100+ iters. #37204 is merging, so closing this.

**Closed by tbg** 2019-04-30 13:04 UTC
