### ISSUE TITLE
kv: intent resolution for high priority pushes should not wait for batching

### ISSUE THREAD

**Issue by kocoten1992** [cockroachdb/cockroach#50390] opened 2020-06-18 14:08 UTC
**Describe the problem**

When select for update a row, other query running into it will significantly increase cost, example below: 

**To Reproduce**

1. start fresh `./cockroach start-single-node --insecure`
2. 
```sql

CREATE TABLE test_table (
  id uuid NOT NULL,
  PRIMARY KEY (id)
);

INSERT INTO test_table (id) values ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');
INSERT INTO test_table (id) values ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb');
```

3. open two cockroach shells:

```sql
# shell 1
begin;
root@:26257/test_database  OPEN> select * from test_table where id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' for update;
                   id
----------------------------------------
  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
(1 row)

Time: 766.309µs
```

```sql
# shell 2
begin priority high;
root@:26257/default  OPEN> select * from test_table where id = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb' for update;
                   id
----------------------------------------
  bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb
(1 row)

Time: 1.265911ms

root@:26257/default  OPEN> select * from test_table where id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' for update;
                   id
----------------------------------------
  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
(1 row)

Time: 14.729765ms
```

Notice that, the select time are significantly higher.

I don't know how to get around this ? Maybe we could have a `select priority read` and skip all of the checking

Because this make our `select for update` kinda work - but does not truly.

**Environment:**
 - CockroachDB version: v20.1.1

P/s: another example

```sql
# shell 1
begin priority low;
root@:26257/default  OPEN> select * from test_table where id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' for update;
                   id
----------------------------------------
  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
(1 row)

Time: 1.081118ms
```

```sql
# shell 2
# no need transaction here
root@:26257/default> select * from test_table where id = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';           
                   id
----------------------------------------
  aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
(1 row)

Time: 19.77373ms
```

Jira issue: CRDB-4129

Epic CRDB-25217

**Comment by kocoten1992** [comment] 2020-06-18 14:09
My mistake was not pointing out, on shell 2, it doesn't have to be select for update, updating example

**Comment by yuzefovich** [comment] 2020-06-18 19:35
cc @nvanbenschoten

**Comment by kocoten1992** [comment] 2020-06-18 20:24
I forgot to mention, `begin read only;` does not help, maybe it make sense to `read only` ?

**Comment by riking** [comment] 2020-06-19 05:50
This looks like the intended behavior of `SELECT .. FOR UPDATE`? The entire point of the statement is to take a write lock on the row, because you're about to update it. If other reads didn't wait for you to finish, then they'd have aborted transactions.

**Comment by kocoten1992** [comment] 2020-06-19 14:13
For some peculiar flow control, what you really want is really both `select .. for update` and normal `select` working together.

With postgresql, `select .. for update` (and even `select .. for share`) don't interfere with normal `select` (we could achieve maximum query throughput with normal select).

With cockroachdb, our `select .. for update` does interfere with normal select, but instead we have something better than postgres, **priority transaction**. Unfortunately, as current state, normal select would be affected in performance.

It's all about query throughput, I hope I made myself clear.

**Comment by riking** [comment] 2020-06-20 06:25
Right, so the delay is because the read only client needs to find the transaction record of the FOR UPDATE client, see that it hasn't committed yet, **bump the transaction time of the other transaction so it will happen after the read**, and return.

I think this means that the SELECT FOR UPDATE is causing read only transactions to perform a write.

**Comment by kocoten1992** [comment] 2020-06-20 13:19
> The good news is that any other concurrent reads for the same key should be satisfied by the same timestamp bump?

Are you sure about that ? @riking 

Here is my testing, I open 3 cockroach client:
shell1. begin with normal priority, `select for update`
shell2. begin high priority, hiccup
shell3. begin high priority, **still hiccup**

If we are talking about calling the same select on the same transaction, that is not what I am after.

**Comment by nvanbenschoten** [comment] 2020-06-22 18:20
Hi @kocoten1992, thanks for the report and the reproduction steps. Like @riking mentioned, the delay is partly because the high priority transaction needs to perform a write to the other transaction's record. In my testing on my Mac, this was responsible for about 8ms. Do you mind measuring the duration of an INSERT statement in your test environment? As an aside, this 8ms was slower than I was expecting until I was reminded of https://github.com/golang/go/issues/26650.

In practice, you will only hit this delay if the first transaction has heartbeat its transaction record, which begins after the transaction has been alive for 1s (see [`DefaultTxnHeartbeatInterval`](https://github.com/cockroachdb/cockroach/blob/bd6daa83f6d3b1a60a543d015fef959d1bfd27ff/pkg/base/constants.go#L22)). If not, the push is a fully in-memory operation which does not require a disk write and should take less than 1ms. Are you holding transactions open for longer than this in your application?

The other ~5m appears to be coming from [a delay in during intent resolution](https://github.com/cockroachdb/cockroach/blob/bd6daa83f6d3b1a60a543d015fef959d1bfd27ff/pkg/kv/kvserver/intentresolver/intent_resolver.go#L90). CockroachDB attempts to batch intent resolution across multiple transactions, which is effective in avoiding redundant pushes and reducing the aggregate number of disk writes due to contention handling. In practice, this is a latency/throughput trade-off. However, I think there's a strong argument that high-priority transactions should not wait for this delay. So we should be able to remove this remaining 5ms. Do you mind if I repurpose this issue to track that change?

**Comment by kocoten1992** [comment] 2020-06-22 19:42
I don't mind at all, and thank you!

p/s: my testing method was wrong (I open cockroachdb client and let transaction live for longer than 1s), thanks for letting me know.

**Closed** 2023-05-18 20:36 UTC
Labels: C-bug, O-community, A-kv-transactions, T-kv, A-read-committed
