### ISSUE TITLE
sql: COPY results in invalid interval warning

### ISSUE THREAD

**Issue by rytaft** [cockroachdb/cockroach#86993] opened 2022-08-27 22:14 UTC
**Describe the problem**

After running COPY, I get a strange warning:
```
warning: invalid interval value in SHOW LAST QUERY STATISTICS, column "service_latency": invalid format: "-296 years -6 mons -11 days -23:47:16.854776"
```

**To Reproduce**

On master, run `./cockroach demo`. Then run:
```
CREATE TABLE tab (col1 STRING, col2 STRING, col3 STRING, col4 STRING, col5 STRING, col6 STRING);
COPY tab FROM STDIN;
-- Now paste the following:
'remove'	'planned'	'slave'	'instrument'	'shoe'	'rays'
'doing'	'bring'	'color'	'busy'	'flat'	'difficulty'
'western'	'mouse'	'seems'	'fully'	'memory'	'neighborhood'
'cup'	'fairly'	'orbit'	'visit'	'lay'	'cave'
'dry'	'vast'	'instrument'	'scared'	'toy'	'completely'
'paragraph'	'roll'	'atomic'	'doctor'	'best'	'finish'
'job'	'suddenly'	'box'	'affect'	'on'	'date'
\.
```

This results in:
```
> COPY tab FROM STDIN;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> 'remove'	'planned'	'slave'	'instrument'	'shoe'	'rays'
'doing'	'bring'	'color'	'busy'	'flat'	'difficulty'
'western'	'mouse'	'seems'	'fully'	'memory'	'neighborhood'
'cup'	'fairly'	'orbit'	'visit'	'lay'	'cave'
'dry'	'vast'	'instrument'	'scared'	'toy'	'completely'
'paragraph'	'roll'	'atomic'	'doctor'	'best'	'finish'
'job'	'suddenly'	'box'	'affect'	'on'	'date'
\.

COPY 7


Time: 2ms

warning: invalid interval value in SHOW LAST QUERY STATISTICS, column "service_latency": invalid format: "-296 years -6 mons -11 days -23:47:16.854776"
```

**Expected behavior**

I would expect the copy to succeed without the warning.

Jira issue: CRDB-19077

**Comment by msirek** [comment] 2022-08-30 18:45
@knz Might your demo fixes address this?

**Comment by cucaroach** [comment] 2022-08-31 17:28
I think this warning is coming from some side query being issued by the demo tool and has something to do with the 22.2 pgx switch.

**Comment by rafiss** [comment] 2022-09-06 15:17
duplicate of https://github.com/cockroachdb/cockroach/issues/86741, which has been fixed

it's a server-side bug, not related to pgx

**Closed by rafiss** 2022-09-06 15:17 UTC
Labels: C-bug, C-qa, T-sql-queries
