### ISSUE TITLE
stress: failed test in cockroach/server/status/status.test: TestMetricsRecorder

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5156] opened 2016-03-11 09:20 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/e9f364bea3014b627b66e8dddcc79a4f3cbcfaad

Stress build found a failed test:

```
=== RUN   TestMetricsRecorder
--- FAIL: TestMetricsRecorder (1.04s)
	recorder_test.go:287: recorder did not yield expected time series collection; diff:
		 [[96].Datapoints[0].Value: 10 != 0 [97].Datapoints[0].Value: 10 != 0 [98].Datapoints[0].Value: 10 != 0 [99].Datapoints[0].Value: 10 != 0 [100].Datapoints[0].Value: 10 != 0 [101].Datapoints[0].Value: 10 != 0 [102].Datapoints[0].Value: 10 != 0 [103].Datapoints[0].Value: 10 != 0 [104].Datapoints[0].Value: 10 != 0 [105].Datapoints[0].Value: 10 != 0 [106].Datapoints[0].Value: 10 != 0 [107].Datapoints[0].Value: 10 != 0 [108].Datapoints[0].Value: 10 != 0 [109].Datapoints[0].Value: 10 != 0 [110].Datapoints[0].Value: 10 != 0 [111].Datapoints[0].Value: 10 != 0]
```

Run Details:

```
609 runs so far, 0 failures, over 5s
1204 runs so far, 0 failures, over 10s
1795 runs so far, 0 failures, over 15s
2384 runs so far, 0 failures, over 20s
2976 runs so far, 0 failures, over 25s
3571 runs so far, 0 failures, over 30s
4165 runs so far, 0 failures, over 35s
4756 runs so far, 0 failures, over 40s
5343 runs so far, 0 failures, over 45s
5935 runs so far, 0 failures, over 50s
6522 runs so far, 0 failures, over 55s
7112 runs so far, 0 failures, over 1m0s
7692 runs so far, 0 failures, over 1m5s
8274 runs so far, 0 failures, over 1m10s
8858 runs so far, 0 failures, over 1m15s
9440 runs so far, 0 failures, over 1m20s
10020 runs so far, 0 failures, over 1m25s
10608 runs so far, 0 failures, over 1m30s
11196 runs so far, 0 failures, over 1m35s
11779 runs so far, 0 failures, over 1m40s
12368 runs so far, 0 failures, over 1m45s
12948 runs so far, 0 failures, over 1m50s
13532 runs so far, 0 failures, over 1m55s
14123 runs so far, 0 failures, over 2m0s
14710 runs so far, 0 failures, over 2m5s
15291 runs so far, 0 failures, over 2m10s
15876 runs so far, 0 failures, over 2m15s
16462 runs so far, 0 failures, over 2m20s
17047 runs so far, 0 failures, over 2m25s
17631 runs so far, 0 failures, over 2m30s
18219 runs so far, 0 failures, over 2m35s
18805 runs so far, 0 failures, over 2m40s
19389 runs so far, 0 failures, over 2m45s
19973 runs so far, 0 failures, over 2m50s
20561 runs so far, 0 failures, over 2m55s
21141 runs so far, 0 failures, over 3m0s
21714 runs so far, 0 failures, over 3m5s
22305 runs so far, 0 failures, over 3m10s
22892 runs so far, 0 failures, over 3m15s
23481 runs so far, 0 failures, over 3m20s
24070 runs so far, 0 failures, over 3m25s
24648 runs so far, 0 failures, over 3m30s
25237 runs so far, 0 failures, over 3m35s
25817 runs so far, 0 failures, over 3m40s
26409 runs so far, 0 failures, over 3m45s
26993 runs so far, 0 failures, over 3m50s
27578 runs so far, 0 failures, over 3m55s
28162 runs so far, 0 failures, over 4m0s
28749 runs so far, 0 failures, over 4m5s
29332 runs so far, 0 failures, over 4m10s
29917 runs so far, 0 failures, over 4m15s
30499 runs so far, 0 failures, over 4m20s
31087 runs so far, 0 failures, over 4m25s
31665 runs so far, 0 failures, over 4m30s
32243 runs so far, 0 failures, over 4m35s
32824 runs so far, 0 failures, over 4m40s
33404 runs so far, 0 failures, over 4m45s
33996 runs so far, 0 failures, over 4m50s
34583 runs so far, 0 failures, over 4m55s
35164 runs so far, 0 failures, over 5m0s
35741 runs so far, 0 failures, over 5m5s
36324 runs so far, 0 failures, over 5m10s
36901 runs so far, 0 failures, over 5m15s
37479 runs so far, 0 failures, over 5m20s
38067 runs so far, 0 failures, over 5m25s
38657 runs so far, 0 failures, over 5m30s
39237 runs so far, 0 failures, over 5m35s
39818 runs so far, 0 failures, over 5m40s
40390 runs so far, 0 failures, over 5m45s
40960 runs so far, 0 failures, over 5m50s
41539 runs so far, 0 failures, over 5m55s
42113 runs so far, 0 failures, over 6m0s
42695 runs so far, 0 failures, over 6m5s
43269 runs so far, 0 failures, over 6m10s
43853 runs so far, 0 failures, over 6m15s
44431 runs so far, 0 failures, over 6m20s
45009 runs so far, 0 failures, over 6m25s
45586 runs so far, 0 failures, over 6m30s
46165 runs so far, 0 failures, over 6m35s
46747 runs so far, 0 failures, over 6m40s
47328 runs so far, 0 failures, over 6m45s
47910 runs so far, 0 failures, over 6m50s
48491 runs so far, 0 failures, over 6m55s
49079 runs so far, 0 failures, over 7m0s
49673 runs so far, 0 failures, over 7m5s
50256 runs so far, 0 failures, over 7m10s
50838 runs so far, 0 failures, over 7m15s
51429 runs so far, 0 failures, over 7m20s
52005 runs so far, 0 failures, over 7m25s
52586 runs so far, 0 failures, over 7m30s
53163 runs so far, 0 failures, over 7m35s
53746 runs so far, 0 failures, over 7m40s
54326 runs so far, 0 failures, over 7m45s
54903 runs so far, 0 failures, over 7m50s
55482 runs so far, 0 failures, over 7m55s
56060 runs so far, 0 failures, over 8m0s
56634 runs so far, 0 failures, over 8m5s
57220 runs so far, 0 failures, over 8m10s
57688 runs so far, 0 failures, over 8m15s
58264 runs so far, 0 failures, over 8m20s
58845 runs so far, 0 failures, over 8m25s
59428 runs so far, 0 failures, over 8m30s
60002 runs so far, 0 failures, over 8m35s
60582 runs so far, 0 failures, over 8m40s
61160 runs so far, 0 failures, over 8m45s
61735 runs so far, 0 failures, over 8m50s
62313 runs so far, 0 failures, over 8m55s
62892 runs so far, 0 failures, over 9m0s
63465 runs so far, 0 failures, over 9m5s
64039 runs so far, 0 failures, over 9m10s
64620 runs so far, 0 failures, over 9m15s
65201 runs so far, 0 failures, over 9m20s
65774 runs so far, 0 failures, over 9m25s
66351 runs so far, 0 failures, over 9m30s
66922 runs so far, 0 failures, over 9m35s
67497 runs so far, 0 failures, over 9m40s
68078 runs so far, 0 failures, over 9m45s
68654 runs so far, 0 failures, over 9m50s
69226 runs so far, 0 failures, over 9m55s
69801 runs so far, 0 failures, over 10m0s
70379 runs so far, 0 failures, over 10m5s
70958 runs so far, 0 failures, over 10m10s
71526 runs so far, 0 failures, over 10m15s
72094 runs so far, 0 failures, over 10m20s
72667 runs so far, 0 failures, over 10m25s
73238 runs so far, 0 failures, over 10m30s
73801 runs so far, 0 failures, over 10m35s
74366 runs so far, 0 failures, over 10m40s
74932 runs so far, 0 failures, over 10m45s
75508 runs so far, 0 failures, over 10m50s
76085 runs so far, 0 failures, over 10m55s
76660 runs so far, 0 failures, over 11m0s
77239 runs so far, 0 failures, over 11m5s
77808 runs so far, 0 failures, over 11m10s
78382 runs so far, 0 failures, over 11m15s
78959 runs so far, 0 failures, over 11m20s
79517 runs so far, 0 failures, over 11m25s
80090 runs so far, 0 failures, over 11m30s
80662 runs so far, 0 failures, over 11m35s
81243 runs so far, 0 failures, over 11m40s
81628 runs completed, 1 failures, over 11m44s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by mrtracy** [comment] 2016-03-12 00:01
Duplicate of #4855

**Closed by mrtracy** 2016-03-12 00:01 UTC
Labels: Robot, test-failure
