### ISSUE TITLE
Memory rises until crash

### ISSUE THREAD

**Issue by mattiasmak** [cockroachdb/cockroach#17313] opened 2017-07-31 07:28 UTC
We have a cluster that does a lot of inserts and upserts. It's a service that logs data in a frequent manner. In another issue [(issues/16875)](https://github.com/cockroachdb/cockroach/issues/16875) I thought that the problem was a join query. However when we run the same cluster without that query the same pattern is still there. It takes about 12 hours and then the nodes start to crash. 

The pattern is obvious in the image below:
<img width="409" alt="memory" src="https://user-images.githubusercontent.com/606639/28766925-0dae1eb8-75d2-11e7-8887-316b91885288.png">

Currently we have isolated this behaviour to 2 queries that runs a few times/second.

```
UPSERT INTO devices (id, prefix, name) VALUES (...);

INSERT INTO raw_visits (venue_id, device_id, first_signal, last_signal, duration_signal, signals_per_hour, avg_distance, min_distance) VALUES (...)
```

We're actually quite worried about this. It's a really simple application and it still crashes 3 nodes very easy.

**Comment by cuongdo** [comment] 2017-07-31 14:54
assigning to @vivekmenezes for triage; this issue seems serious

**Comment by tschottdorf** [comment] 2017-08-01 18:35
@mattiasmak no worries, your cluster is the pain and we're trying to fix it! Sorry about the delayed response. We're wrapping up the feature freeze and this fell off our radar.

Would you be able to open that cluster to the public like you did with that other one? We should be able to diagnose what's going on most efficiently that way. If you can't, I understand -- in that case, we'll circle back with specific instructions on what to check.

**Comment by vivekmenezes** [comment] 2017-08-01 18:35
Sorry to not get back to you earlier. This looks a lot like a memory leak of some sort. Is there a correlation between the drop in memory and a restart, because it does look like the memory footprint grows in size over time and then drops with every restart.

**Comment by vivekmenezes** [comment] 2017-08-02 03:12
Can you attach the output of ```http(s)://<hostname>:<admin-ui-port>/debug/pprof/heap```  (the heap profile) to this issue. Thanks

**Comment by mattiasmak** [comment] 2017-08-02 12:15
Yes, every drop is when I restart or the node crashes.

http://67.207.72.227:8080/#/cluster/all/overview

You can access the nodes just like you did before.



[heap.gz](https://github.com/cockroachdb/cockroach/files/1193767/heap.gz)

**Comment by mattiasmak** [comment] 2017-08-02 12:16
The three nodes ip:

46.101.157.129
46.101.183.149
207.154.201.151

Load balancer:
67.207.72.227

**Comment by vivekmenezes** [comment] 2017-08-02 13:51
Just adding some information here:

node 1 has 100% unavailable ranges

http://67.207.72.227:8080/#/cluster/nodes/1

I wonder if this is being caused by a queue up of transactions on the unavailable ranges. I remember there being no timeout on transaction right?

**Comment by vivekmenezes** [comment] 2017-08-02 13:55
hmmm, looks like I was looking at the cluster at the exact moment node 1 died. The cluster is back to normal with 2 nodes up and all ranges available. node 1 is still down after 8 minutes.

**Comment by mattiasmak** [comment] 2017-08-02 14:58
Tell me if I should do something, like restarting anything

**Comment by vivekmenezes** [comment] 2017-08-02 17:45
@mattiasmak please restart node 1 so that the cluster remains available. I'm trying to understand the heap profile but I did notice that the cluster is seeing distSQL queries. If you 
hover over the graph "sql queries" you will see distsql queries being executed.

**Comment by vivekmenezes** [comment] 2017-08-02 18:42
go tool pprof -symbolize=remote -alloc_objects http://46.101.183.149:8080/debug/pprof/heap

```
(pprof) top10   
5167428 of 6152076 total (83.99%)
Dropped 495 nodes (cum <= 30760)
Showing top 10 nodes out of 175 (cum >= 111085)
      flat  flat%   sum%        cum   cum%
   1331086 21.64% 21.64%    1331086 21.64%  runtime.convT2E
    917518 14.91% 36.55%     917518 14.91%  encoding/binary.Write
    808314 13.14% 49.69%    4315272 70.14%  github.com/cockroachdb/cockroach/pkg/storage.(*Replica).sha512
    753675 12.25% 61.94%     753675 12.25%  github.com/cockroachdb/cockroach/pkg/util/hlc.(*Timestamp).Marshal
    617149 10.03% 71.97%     617149 10.03%  github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBIterator).Key
    367660  5.98% 77.95%     367660  5.98%  runtime.gobytes
    171515  2.79% 80.74%     171515  2.79%  github.com/cockroachdb/cockroach/pkg/kv.truncate
     72091  1.17% 81.91%      72091  1.17%  strings.genSplit
     66096  1.07% 82.98%      66096  1.07%  runtime.makemap
     62324  1.01% 83.99%     111085  1.81%  github.com/cockroachdb/cockroach/pkg/storage.entries
```

**Comment by mattiasmak** [comment] 2017-08-02 18:48
I just restarted the cluster, since node 1 didn't want to start at first

**Comment by mattiasmak** [comment] 2017-08-02 18:51
With regards to distSQL. Can SET CLUSTER SETTING sql.default.distsql = 0; help avoiding distSQL? I know there a few simple SELECT queries being run once an hour or so... But can this have such dramatic effect on the cluster?

**Comment by vivekmenezes** [comment] 2017-08-02 18:52
I think we should turn off distsql so we can eliminate that from this problem. Thanks for restarting the cluster

**Comment by vivekmenezes** [comment] 2017-08-02 18:56
```
(pprof) top10   
56.09MB of 65.21MB total (86.01%)
Dropped 1019 nodes (cum <= 0.33MB)
Showing top 10 nodes out of 201 (cum >= 1MB)
      flat  flat%   sum%        cum   cum%
   34.33MB 52.65% 52.65%    34.33MB 52.65%  runtime.hashGrow
    8.85MB 13.58% 66.22%     8.85MB 13.58%  github.com/cockroachdb/cockroach/pkg/kv.truncate
    4.50MB  6.90% 73.12%     4.50MB  6.90%  runtime.rawstringtmp
       2MB  3.07% 76.19%        3MB  4.60%  github.com/cockroachdb/cockroach/pkg/storage.(*timestampCache).AddRequest
    1.16MB  1.79% 77.98%     1.66MB  2.55%  github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).Unmarshal
    1.11MB  1.71% 79.68%     1.11MB  1.71%  github.com/cockroachdb/cockroach/pkg/roachpb.(*BatchRequest).CreateReply
    1.07MB  1.64% 81.33%     1.07MB  1.64%  github.com/cockroachdb/cockroach/pkg/rpc.snappyCompressor.Do
    1.05MB  1.61% 82.93%     1.05MB  1.61%  github.com/cockroachdb/cockroach/vendor/github.com/codahale/hdrhistogram.New
       1MB  1.54% 84.47%        1MB  1.54%  regexp.mergeRuneSets.func2
       1MB  1.54% 86.01%        1MB  1.54%  github.com/cockroachdb/cockroach/vendor/github.com/google/btree.(*node).insert
```

is from the profile attached to this issue.

**Comment by mattiasmak** [comment] 2017-08-02 18:56
ERROR:  unknown cluster setting 'sql.default.distsql'. What am I missing?

In the session_varieble table it's set to 'auto'.

**Comment by vivekmenezes** [comment] 2017-08-02 20:43
sorry about that. the documentation is a bit wrong. You need to use "defaults" instead of "default"
``` SET CLUSTER SETTING sql."defaults".distsql = 0;```

**Comment by vivekmenezes** [comment] 2017-08-03 01:21
I've turned off distsql on your cluster. When you get a chance can you restart node 1 again. Thanks

**Comment by vivekmenezes** [comment] 2017-08-03 02:12
The profiles don't point to anything in particular. I'm seeing a correlation between the last crash a few queries that landed around the same time. These queries seem to be issued every two hours. hopefully turning off distsql is going to help. Let's see. Thanks

**Comment by mattiasmak** [comment] 2017-08-03 08:59
I can inform you that the cluster seems to be in a much better state now when I turned of distSQL completely. The very few SELECT queries (one small every 5 minute) I did, destroyed everything. I'm not jumping to any conclusions just yet. But the memory usage is now stable around 66%. This is a pattern I have not seen before. Fingers crossed.

**Comment by mattiasmak** [comment] 2017-08-03 11:41
I'm sorry to say the memory is rising anyways. I was too quick to respond before.

Question is what to do? Do you see anything out of the ordinary? Memory leaks?

I feel we must soon abandon CockroachDB for the projects well being. We're getting close to production. 

<img width="418" alt="skarmavbild 2017-08-03 kl 13 39 00" src="https://user-images.githubusercontent.com/606639/28920234-31fb43c8-7851-11e7-943d-d4bc509c3d68.png">

**Comment by petermattis** [comment] 2017-08-03 12:09
@mattiasmak Sorry for the trouble you're having. I'm taking another look right now (though my network connection is spotty). Go memory usage appears to be very low. I'm taking a look at cgo memory usage, but hitting the bad networking. I'll be in a better network environment in about an hour. 

Btw, I noticed you're using `v1.1-alpha`. Have we provided adequate warnings about running alpha versions in production?

**Comment by mattiasmak** [comment] 2017-08-03 12:13
About the v1.1-alpha, I installed just to see if this particular issue magically got resolved by itself. (And another issue that was actually fixed).

**Comment by mattiasmak** [comment] 2017-08-03 12:14
I agree the memory is very low. It get lower and lower for every minute :)

**Comment by petermattis** [comment] 2017-08-03 12:15
@mattiasmak Can you `grep runtime.go` from the debug logs during the time period you showed above? Also, how are you monitoring memory usage? Is that graph above a measure of RSS or something else?

**Comment by mattiasmak** [comment] 2017-08-03 12:25
I look at Digital ocean's graphs. I also watch -n 5 free -m on each node.

I can do that I think. I found lots of rows with runtime.go. The number of gorutines seems to go up as well as memory usage.

[cockroach.ro-cockroach-3.root.2017-08-03T06_07_17Z.001676.log.zip](https://github.com/cockroachdb/cockroach/files/1197160/cockroach.ro-cockroach-3.root.2017-08-03T06_07_17Z.001676.log.zip)

Is this helpful? http://67.207.72.227:8080/debug/

**Comment by petermattis** [comment] 2017-08-03 12:32
Your nodes are using the default cache size of 1/4 of system memory which translates to 500 MiB on your nodes. Across the 3 nodes, there is 1.6 GiB in cgo memory usage which is in the right ballpark for that cache size (cgo memory is dominated by the RocksDB cache). But cgo total memory is 3.1 GiB. That discrepancy is unusual and concerning. I think this is a bug in jemalloc that forced us to revert to an earlier version of jemalloc. You're running `v1.1-alpha.20170713` which predates the revert that occurred on 7/17. Can you try running `v1.1-alpha.20170720`?

PS The goroutine count seems fairly stable. It is rising very slightly but the number of goroutines isn't obviously concerning.

**Comment by mattiasmak** [comment] 2017-08-03 12:54
So, I managed to update the cluster. Now running v1.1-alpha.20170720.

**Comment by petermattis** [comment] 2017-08-03 13:10
Roger. I'll keep an eye on the memory growth over the next few hours.

**Comment by mattiasmak** [comment] 2017-08-03 17:22
I see a slight improvement. Don't know what to expect under normal conditions, but at least the memory rises slower now. Hoping it will pan out and be stable...

**Comment by petermattis** [comment] 2017-08-03 17:46
I've been watching the growth throughout the day. The big improvement is the delta between `CGo Allocated` and `CGo Total` is now much smaller.

**Comment by mberhault** [comment] 2017-08-03 18:01
All alpha versions are still susceptible to the HTTP2 hpack header table
infinite growth problem (that's a mouthful).
See https://github.com/cockroachdb/cockroach/issues/17052 for details.

20170720 reverted jemalloc which should free memory back to the system more
reasonable (symptom was constantly growing total CGO memory, but allocated
CGO was reasonably stable)
20170803 (coming out today) will have the fix for #17052. The symptom is
slowly growing Go allocated memory. The issue has a sample heap profile
attached, the big path is hpack.dynamicTable -> runtime.mapassign ->
runtime.hashGrow

**Comment by mattiasmak** [comment] 2017-08-03 18:06
Wow. You can never guess how much trouble this has caused us. I've been sleeping very bad lately. But now it looks there's a fix. Thank you guys for great support, guys. 

Do you recommend us upgrading to 20170720? Or should we stay and wait for a stable release?

**Comment by petermattis** [comment] 2017-08-03 18:08
Thanks, @mberhault. The profiles I looked at showed `runtime.hashGrow`. 

@mattiasmak It would be nice to upgrade to `v1.1-alpha.20170803` when it is released, but we can't recommend using that release for a production deployment. I believe that neither of these memory leaks was present in `1.0.4`. 

PS The `1.1` release is currently scheduled for Oct 12.

**Comment by mberhault** [comment] 2017-08-03 18:09
Sorry, I should have mentioned that. Indeed, neither of those problems impact 1.0.4, either because we didn't trigger the hpack bug (this is related to tracing), or we were on the older version of jemalloc.

**Comment by petermattis** [comment] 2017-08-03 18:13
Right, but `1.0.4` has known problems with distsql memory usage which it sounds like @mattiasmak might have been encountering. @mattiasmak also beware that we haven't tested downgrading significantly yet. That is something we're promising to support, but at this time there might be bugs in downgrading from `v1.1-alpha` to `1.0.4`.

**Comment by mattiasmak** [comment] 2017-08-03 18:17
Thanks for your info. And yes, the distSQL was an issue as well that we encountered. That and some positive changes in table_constrains (I think) made me upgrade to alpha. 

We'll stay developing on alpha and Deploy on 1.0.4. Thanks again.

**Comment by petermattis** [comment] 2017-08-04 01:18
<img width="923" alt="screen shot 2017-08-03 at 9 16 16 pm" src="https://user-images.githubusercontent.com/6201335/28950320-09ef59ba-7891-11e7-91e0-ee2b22429412.png">

Upgrading to `v1.1-alpha.20170720` fixed the cgo memory usage was has been nice and stable over the last 12 hours. Go memory has been growing steadily over that time. I think upgrading to `v1.1-alpha.20170803` will fix that issue as the memory growth is exactly as @mberhault described:

<img width="233" alt="screen shot 2017-08-03 at 9 17 38 pm" src="https://user-images.githubusercontent.com/6201335/28950355-538a94ae-7891-11e7-9df0-8d7d642e7130.png">

**Comment by vivekmenezes** [comment] 2017-08-09 12:05
your cluster seems to be in a good shape now with a rather flat memory usage. Feel free to close this issue if you're satisfied. Thanks

**Closed** 2018-05-02 15:29 UTC
Labels: C-performance, O-community
