### ISSUE TITLE
kv: reduce latch contention for GCRequest

### ISSUE THREAD

**Issue by tbg** [cockroachdb/cockroach#24237] opened 2018-03-26 23:40 UTC
GCRequest is special in that it only affects data that is not observable by regular reads and writes. As such, they shouldn't need command queue serialization with anything else.

@nvanbenschoten pointed this out in #24209.

The effects of these optimizations should be observable in tests like https://github.com/cockroachdb/cockroach/issues/24236.

Jira issue: CRDB-5778

**Comment by nvanbenschoten** [comment] 2022-03-10 19:59
Duplicate of https://github.com/cockroachdb/cockroach/issues/55293.

**Closed by nvanbenschoten** 2022-03-10 19:59 UTC
Labels: C-performance, A-kv-transactions, T-kv
