### ISSUE TITLE
sql: allow password creation in insecure mode

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#24061] opened 2018-03-20 10:36 UTC
https://github.com/cockroachdb/cockroach/pull/22328 removed setting password in insecure mode. We need to reenable this functionality after coming up with a plan.

**Comment by bdarnell** [comment] 2018-03-20 19:15
Duplicate of #16188, let's reopen and keep discussion there.

**Closed by bdarnell** 2018-03-20 19:15 UTC
