### ISSUE TITLE
High CPU utilization on a single-node cockroachdb docker instance without traffic

### ISSUE THREAD

**Issue by AInteriorB** [cockroachdb/cockroach#69960] opened 2021-09-09 14:58 UTC
We run a singl-node cockroachdb in a docker container. Even when there's no traffic on this instance, cockroachdb's cpu consumption is always around 10% on an high end virtualized debian host. 

```
    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                             
 252423 root      20   0 1260292 356452  97608 S  12.3  12.5   2:59.91 /cockroach/cockroach start-single-node --http-port 26256 --insecure   
```

I searched the whole internet if this is normal, but didn't find an answer. Why does cockroach need so much cpu time even if it is just ideling? 

**To Reproduce**

1. deploy a docker cockroachdb/cockroach:v21.1.8 image
2. start cockroachdb as a single-node
3. observe cpu utilization

**Expected behavior**
no cpu utilization

**Environment:**
 - CockroachDB version v21.1.8 from docker image cockroachdb/cockroach:v21.1.8
 - Server OS: Linux Debian Bullseye 11 XEN virtualized
 - Docker Version: 20.10.8

**Comment by rafiss** [comment] 2021-09-09 18:02
@AInteriorB that amount of idle CPU usage isn't expected. There was a fix that made it into v21.1.6 that decreased CPU usage (https://github.com/cockroachdb/cockroach/pull/66894) but it seems like maybe you're having a different issue.

Would you be able to capture a CPU profile and share it? You can do so with:
```
curl -kL http://localhost:26256/debug/pprof/profile\?seconds\=5 --output profile.tar.gz
```
(change the URL and port as needed)

**Comment by AInteriorB** [comment] 2021-09-09 19:14
@rafiss sure, thanks for your investigation
[profile.gz](https://github.com/cockroachdb/cockroach/files/7139189/profile.gz)

**Comment by rafiss** [comment] 2021-09-09 19:56
It looks like the profile shows a fair amount of time spent in `time.Now()`

Would you also be able to share the execution trace?
```
curl -kL http://localhost:26256/debug/pprof/trace\?debug\=1 --output trace.out
```

**Comment by AInteriorB** [comment] 2021-09-09 20:23
Of course 
[trace.log](https://github.com/cockroachdb/cockroach/files/7139547/trace.log)

**Comment by rafiss** [comment] 2021-09-10 15:06
I haven't found anything more specific so far, but I think it's likely the problem is related to the environment you are running in. Running in a virtualized environment cane make `time.Now` perform slowly, and in this case there are two layers of virtualization (docker and the Xen environment). I haven't been able to reproduce this CPU usage when I tried running the docker image on a GCE Ubuntu 18.04.5 host.

I did a bit of searching and found these other issues where `time.Now` performed poorly because of issues with the environment (https://github.com/golang/go/issues/33448 and https://github.com/golang/go/issues/22601). The first issue includes this benchmark that maybe you could try using for yourself. I'm not familiar enough to know if this is the best benchmark, but at least it would be interesting to compare your results.

```
package main

import (
	"fmt"
	"log"
	"os"
	"runtime/pprof"
	"time"
)

type buffer [200000][]byte

func main() {
	f, err := os.Create("cpup.prof")
	if err != nil {
		log.Fatal(err)
	}
	pprof.StartCPUProfile(f)
	defer pprof.StopCPUProfile()

	pstart := time.Now()
	var (
		b     *buffer
		worst time.Duration
	)
	b = new(buffer)
	for i := 0; i < 1000000; i++ {
		start := time.Now()
		item := make([]byte, 1024)
		(*b)[i%200000] = item
		elapsed := time.Since(start)
		if elapsed > worst {
			worst = elapsed
		}
	}
	pruntime := time.Since(pstart)
	fmt.Println("Worst write time: ", worst, pruntime)
}
```

I'd recommend you try the following:
1. Check if you see the idle CPU usage if you run the CockroachDB docker image on a different host.
2. Run the above benchmark directly on your Debian Bullseye 11 Xen host, and share the output and profile.
3. Run the above benchmark inside of a docker container on your Xen host, and share the output and profile.

**Comment by rafiss** [comment] 2021-09-15 20:54
I'm going to go ahead and close this since it doesn't seem like a CockroachDB issue. Feel free to share more info if you do the experiments I described.

**Closed by rafiss** 2021-09-15 20:54 UTC
Labels: C-bug, O-community
