### ISSUE TITLE
TTL jobs fail when gc.ttlseconds is exceeded

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cockroach#90811] opened 2022-10-27 22:08 UTC
**Describe the problem**

I have `gc.ttlseconds = 7200` for a table and configured TTL to expire data after two hours like so:

```sql
ALTER TABLE events 
SET (ttl = 'on', 
     ttl_expiration_expression = "if(not keep_record, (updated_at AT TIME ZONE 'utc' + INTERVAL '2h') AT TIME ZONE 'utc', NULL)",
     ttl_label_metrics = true,
     ttl_range_concurrency = 1,
     ttl_delete_rate_limit=3334);
```

Data was being removed and storage reclaimed, however I noticed jobs were failing and being restarted:

```sql
                     
root@localhost:26257/defaultdb> select job_id, job_type,started,now(),status from [show jobs] ;
        job_id       |   job_type    |          started           |              now              | status
---------------------+---------------+----------------------------+-------------------------------+----------
  808661360278798344 | ROW LEVEL TTL | 2022-10-27 07:04:23.927365 | 2022-10-27 19:18:27.945998+00 | failed
  808685331213221891 | ROW LEVEL TTL | 2022-10-27 09:06:25.974274 | 2022-10-27 19:18:27.945998+00 | failed
  808709355362254855 | ROW LEVEL TTL | 2022-10-27 11:08:37.636123 | 2022-10-27 19:18:27.945998+00 | failed
  808733312603684870 | ROW LEVEL TTL | 2022-10-27 13:10:26.635653 | 2022-10-27 19:18:27.945998+00 | failed
  808757355415633922 | ROW LEVEL TTL | 2022-10-27 15:12:38.262785 | 2022-10-27 19:18:27.945998+00 | failed
  808781372525674504 | ROW LEVEL TTL | 2022-10-27 17:15:00.681812 | 2022-10-27 19:18:27.945998+00 | failed
  808805228194365444 | ROW LEVEL TTL | 2022-10-27 19:16:08.102349 | 2022-10-27 19:18:27.945998+00 | running
```

Monitoring systems for this cluster alert teams when jobs fail.  It appears that things are restarting, but the failed job should be handled more gracefully so as not to fire an alert.  With a new feature, this can be unsettling to those trying to use the feature.

Please describe the issue you observed, and any steps we can take to reproduce it:

Reduce the `gc.ttlseconds` on a large table and enable TTL on the table so that the initial cleanup job takes longer than `gc.ttlseconds`.

Jira issue: CRDB-20952

**Comment by rafiss** [comment] 2022-11-17 16:12
this is a duplicate of https://github.com/cockroachdb/cockroach/issues/90979, which has been resolved and backported to 22.2.1.

**Closed by rafiss** 2022-11-17 16:12 UTC
Labels: C-bug, T-sql-experience
