### ISSUE TITLE
ui: "Leader not leaseholder" misreported as "no lease"

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#18055] opened 2017-08-30 22:47 UTC
On cyan, the problem ranges page is currently reporting two ranges with "no lease"

![image](https://user-images.githubusercontent.com/160562/29898245-b66a0eca-8db2-11e7-9082-0bdccc35a5bf.png)

These ranges appear to have a valid lease, it's just not on the leaseholder (if the lease isn't valid, why not?):

![image](https://user-images.githubusercontent.com/160562/29898268-db60a450-8db2-11e7-8c76-b541a87bcf00.png)

![image](https://user-images.githubusercontent.com/160562/29898424-b0d81730-8db3-11e7-9bee-60ed9e7ab430.png)

The "Lease Holder QPS" here is non-zero, although the cluster as a whole is reporting zero qps so  something's not right, in addition to this incorrect error message.

Both of the problematic ranges look nearly identical: replicas on nodes 2, 3, and 6, with 2 as the raft leader and 6 as the lease holder.

**Comment by a-robinson** [comment] 2017-08-31 02:05
In case it changes anything, the "Lease Holder QPS" counts any `Send()` call to a replica, and is an average over the last 30 minutes.

I'm not sure what's up with the "No Lease" errors.

**Comment by dianasaur323** [comment] 2017-09-01 05:39
probably want to have @BramGruneir take a look. assigning!

**Comment by BramGruneir** [comment] 2017-09-01 15:50
There is no way I'll be able to squeeze this in today.  Moving to 1.2.

**Comment by tschottdorf** [comment] 2017-10-30 23:18
Seen on `register` as well. That range has no activity, and perhaps for that reason the situation doesn't seem to resolve. I have to double-check where the code is that nudges leaseholder and Raft leader into the same place and whether it just doesn't run in this case.

![image](https://user-images.githubusercontent.com/5076964/32200180-afe3309e-bda6-11e7-82dd-4db71c282a7d.png)

**Comment by a-robinson** [comment] 2017-10-31 02:38
@tschottdorf it looks like that lease is considered expired, so "No Lease" seems like an accurate diagnose.

**Comment by dianasaur323** [comment] 2018-01-30 17:26
@BramGruneir is this still a problem, and should we fix it before 2.0? We will be surfacing these pages to users in 2.0 as experimental pages.

**Comment by mrtracy** [comment] 2018-03-08 23:04
I think this was already addressed by adding the "Lease State" field in 219eff361d00aa85cfdb1b97016e0511973d71d2.  Looking at the condition in the original bug report (which was before that addition), I believe it was probably caused by the Lease being expired (or in some other invalid state); however, other than the "No Lease" warning, there was no indication in the UI of the issue.

The only possible thing I might consider changing here is the actual "No Lease" text, since it actually refers to an "Invalid Lease", but I think that's a minor issue.

@BramGruneir If you agree with that assessment, this can be closed out.

**Comment by jordanlewis** [comment] 2018-03-13 15:43
ping @BramGruneir

**Comment by BramGruneir** [comment] 2018-03-15 17:38
@mrtracy I think you're right.  This should be addressed at this point.  

I'll issue a cosmetic change to change the `No Lease` to `Invalid Lease`.

**Closed** 2018-03-20 18:34 UTC
Labels: bug, ux-surprise
