### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestRaceWithBackfill

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6556] opened 2016-05-06 11:37 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/f6ed931f3edc5da0508c4bf15c1413b544196a14

Stress build found a failed test:

```
=== RUN   TestRaceWithBackfill
W160506 06:32:03.051541 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160506 06:32:03.052068 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160506 06:32:03.053239 server/node.go:400  store store=0:0 ([]=) not bootstrapped
W160506 06:32:03.053364 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160506 06:32:03.055028 storage/replica_command.go:1452  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.054702795s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.054933326 +0000 UTC]
I160506 06:32:03.055525 server/node.go:326  **** cluster {b6b39904-93ed-4a8f-9c8b-e92132c6f048} has been created
I160506 06:32:03.055555 server/node.go:327  **** add additional nodes by specifying --join=127.0.0.1:36311
W160506 06:32:03.055572 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160506 06:32:03.056205 server/node.go:413  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:8323203072 RangeCount:0}
I160506 06:32:03.056244 server/node.go:301  node ID 1 initialized
I160506 06:32:03.056302 storage/stores.go:287  read 0 node addresses from persistent storage
I160506 06:32:03.056362 server/node.go:534  connecting to gossip network to verify cluster ID...
I160506 06:32:03.076887 server/node.go:555  node connected via gossip and verified as part of cluster {"b6b39904-93ed-4a8f-9c8b-e92132c6f048"}
I160506 06:32:03.076925 server/node.go:354  [node=1] Started node with [[]=] engine(s) and attributes []
I160506 06:32:03.076957 server/server.go:391  starting https server at 127.0.0.1:41292
I160506 06:32:03.076974 server/server.go:392  starting grpc/postgres server at 127.0.0.1:36311
I160506 06:32:03.077122 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160506 06:32:03.078067 storage/replica_command.go:1986  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160506 06:32:03.078490 server/updates.go:155  No previous updates check time.
I160506 06:32:03.109611 storage/replica_command.go:1452  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.158348733s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.108522665 +0000 UTC]
I160506 06:32:03.109882 storage/replica_command.go:1986  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160506 06:32:03.125098 storage/replica_command.go:1452  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.170703807s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.125051012 +0000 UTC]
I160506 06:32:03.125496 storage/replica_command.go:1986  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160506 06:32:03.132094 storage/replica_command.go:1452  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.181888988s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.132061763 +0000 UTC]
I160506 06:32:03.132190 storage/replica_command.go:1986  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160506 06:32:03.145361 storage/replica_command.go:1452  range 5: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.195114514s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.145318241 +0000 UTC]
I160506 06:32:03.199167 storage/split_queue.go:100  splitting range=5 [/Table/14-/Max) at keys [/Table/50/0]
I160506 06:32:03.199286 storage/replica_command.go:1986  initiating a split of range=5 [/Table/14-/Max) at key /Table/50
I160506 06:32:03.214241 storage/replica_command.go:1452  range 6: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m4.263499759s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:03.213860264 +0000 UTC]
I160506 06:32:03.220227 storage/split_queue.go:100  splitting range=6 [/Table/50-/Max) at keys [/Table/51/0]
I160506 06:32:03.220386 storage/replica_command.go:1986  initiating a split of range=6 [/Table/50-/Max) at key /Table/51
I160506 06:32:04.053585 gossip/gossip.go:918  starting client to 127.0.0.1:36311
I160506 06:32:04.055160 gossip/client.go:86  closing client to node 1 (127.0.0.1:36311): gossip/client.go:180: stopping outgoing client to node 1 (127.0.0.1:36311); loopback connection
I160506 06:32:04.115395 storage/replica_command.go:1452  range 7: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406254h32m5.165060808s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-06 06:32:04.115345956 +0000 UTC]
I160506 06:32:05.110428 sql/lease.go:222  publish (count leases): descID=51 name=test version=4 count=1
I160506 06:32:05.136695 sql/lease.go:222  publish (count leases): descID=51 name=test version=5 count=1
I160506 06:32:05.681546 sql/lease.go:222  publish (count leases): descID=51 name=test version=7 count=1
I160506 06:32:05.737149 sql/lease.go:222  publish (count leases): descID=51 name=test version=8 count=1
W160506 06:32:06.069701 sql/schema_changer.go:220  node unavailable; try another peer
W160506 06:32:06.069790 sql/schema_changer.go:184  node unavailable; try another peer
W160506 06:32:06.069811 sql/session.go:281  Error executing schema change: sql/schema_changer.go:245: error purging mutation: node unavailable; try another peer, after error: node unavailable; try another peer
E160506 06:32:06.069843 sql/pgwire/v3.go:138  write tcp 127.0.0.1:36311->127.0.0.1:37456: use of closed network connection
--- FAIL: TestRaceWithBackfill (3.03s)
	schema_changer_test.go:452: schema change ALTER TABLE t.test ADD COLUMN x DECIMAL DEFAULT (DECIMAL '1.4') took 513.645976ms
	schema_changer_test.go:497: pq: duplicate key value (k)=(2203) violates unique constraint "primary"
	schema_changer_test.go:450: sql: database is closed
	schema_changer_test.go:452: schema change ALTER TABLE t.test DROP pi took 395.552458ms
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
3 runs so far, 0 failures, over 40s
15 runs so far, 0 failures, over 45s
16 runs so far, 0 failures, over 50s
16 runs so far, 0 failures, over 55s
16 runs so far, 0 failures, over 1m0s
16 runs so far, 0 failures, over 1m5s
16 runs so far, 0 failures, over 1m10s
16 runs so far, 0 failures, over 1m15s
20 runs so far, 0 failures, over 1m20s
28 runs so far, 0 failures, over 1m25s
32 runs so far, 0 failures, over 1m30s
32 runs so far, 0 failures, over 1m35s
32 runs so far, 0 failures, over 1m40s
32 runs so far, 0 failures, over 1m45s
32 runs so far, 0 failures, over 1m50s
32 runs so far, 0 failures, over 1m55s
36 runs so far, 0 failures, over 2m0s
43 runs so far, 0 failures, over 2m5s
48 runs so far, 0 failures, over 2m10s
48 runs so far, 0 failures, over 2m15s
48 runs so far, 0 failures, over 2m20s
48 runs so far, 0 failures, over 2m25s
48 runs so far, 0 failures, over 2m30s
48 runs so far, 0 failures, over 2m35s
51 runs so far, 0 failures, over 2m40s
56 runs so far, 0 failures, over 2m45s
61 runs so far, 0 failures, over 2m50s
64 runs so far, 0 failures, over 2m55s
64 runs so far, 0 failures, over 3m0s
64 runs so far, 0 failures, over 3m5s
64 runs so far, 0 failures, over 3m10s
64 runs so far, 0 failures, over 3m15s
66 runs so far, 0 failures, over 3m20s
72 runs so far, 0 failures, over 3m25s
76 runs so far, 0 failures, over 3m30s
80 runs so far, 0 failures, over 3m35s
80 runs so far, 0 failures, over 3m40s
80 runs so far, 0 failures, over 3m45s
80 runs so far, 0 failures, over 3m50s
80 runs so far, 0 failures, over 3m55s
80 runs so far, 0 failures, over 4m0s
86 runs so far, 0 failures, over 4m5s
91 runs so far, 0 failures, over 4m10s
96 runs so far, 0 failures, over 4m15s
96 runs so far, 0 failures, over 4m20s
96 runs so far, 0 failures, over 4m25s
96 runs so far, 0 failures, over 4m30s
96 runs so far, 0 failures, over 4m35s
98 runs so far, 0 failures, over 4m40s
101 runs so far, 0 failures, over 4m45s
106 runs so far, 0 failures, over 4m50s
111 runs so far, 0 failures, over 4m55s
112 runs so far, 0 failures, over 5m0s
112 runs so far, 0 failures, over 5m5s
112 runs so far, 0 failures, over 5m10s
112 runs so far, 0 failures, over 5m15s
112 runs so far, 0 failures, over 5m20s
117 runs so far, 0 failures, over 5m25s
118 runs so far, 0 failures, over 5m30s
127 runs so far, 0 failures, over 5m35s
128 runs so far, 0 failures, over 5m40s
128 runs so far, 0 failures, over 5m45s
128 runs so far, 0 failures, over 5m50s
128 runs so far, 0 failures, over 5m55s
128 runs so far, 0 failures, over 6m0s
132 runs so far, 0 failures, over 6m5s
134 runs so far, 0 failures, over 6m10s
140 runs so far, 0 failures, over 6m15s
143 runs so far, 0 failures, over 6m20s
143 runs so far, 0 failures, over 6m25s
143 runs so far, 0 failures, over 6m30s
143 runs so far, 0 failures, over 6m35s
143 runs so far, 0 failures, over 6m40s
145 runs so far, 0 failures, over 6m45s
148 runs so far, 0 failures, over 6m50s
153 runs so far, 0 failures, over 6m55s
157 runs so far, 0 failures, over 7m0s
157 runs so far, 0 failures, over 7m5s
157 runs so far, 0 failures, over 7m10s
157 runs so far, 0 failures, over 7m15s
157 runs so far, 0 failures, over 7m20s
159 runs so far, 0 failures, over 7m25s
162 runs so far, 0 failures, over 7m30s
167 runs so far, 0 failures, over 7m35s
172 runs so far, 0 failures, over 7m40s
172 runs so far, 0 failures, over 7m45s
172 runs so far, 0 failures, over 7m50s
172 runs so far, 0 failures, over 7m55s
172 runs so far, 0 failures, over 8m0s
173 runs so far, 0 failures, over 8m5s
177 runs so far, 0 failures, over 8m10s
179 runs so far, 0 failures, over 8m15s
186 runs so far, 0 failures, over 8m20s
187 runs so far, 0 failures, over 8m25s
187 runs so far, 0 failures, over 8m30s
187 runs so far, 0 failures, over 8m35s
187 runs so far, 0 failures, over 8m40s
187 runs so far, 0 failures, over 8m45s
189 runs so far, 0 failures, over 8m50s
194 runs so far, 0 failures, over 8m55s
200 runs so far, 0 failures, over 9m0s
202 runs so far, 0 failures, over 9m5s
202 runs so far, 0 failures, over 9m10s
202 runs so far, 0 failures, over 9m15s
202 runs so far, 0 failures, over 9m20s
202 runs so far, 0 failures, over 9m25s
204 runs so far, 0 failures, over 9m30s
207 runs so far, 0 failures, over 9m35s
212 runs so far, 0 failures, over 9m40s
217 runs so far, 0 failures, over 9m45s
217 runs so far, 0 failures, over 9m50s
217 runs so far, 0 failures, over 9m55s
217 runs so far, 0 failures, over 10m0s
218 runs so far, 0 failures, over 10m5s
219 runs so far, 0 failures, over 10m10s
222 runs so far, 0 failures, over 10m15s
224 runs so far, 0 failures, over 10m20s
230 runs so far, 0 failures, over 10m25s
231 runs so far, 0 failures, over 10m30s
231 runs so far, 0 failures, over 10m35s
231 runs so far, 0 failures, over 10m40s
232 runs so far, 0 failures, over 10m45s
233 runs so far, 0 failures, over 10m50s
236 runs so far, 0 failures, over 10m55s
238 runs so far, 0 failures, over 11m0s
243 runs so far, 0 failures, over 11m5s
245 runs so far, 0 failures, over 11m10s
246 runs so far, 0 failures, over 11m15s
246 runs so far, 0 failures, over 11m20s
246 runs so far, 0 failures, over 11m25s
248 runs so far, 0 failures, over 11m30s
250 runs so far, 0 failures, over 11m35s
252 runs so far, 0 failures, over 11m40s
257 runs so far, 0 failures, over 11m45s
259 runs so far, 0 failures, over 11m50s
259 runs so far, 0 failures, over 11m55s
260 runs so far, 0 failures, over 12m0s
260 runs so far, 0 failures, over 12m5s
262 runs so far, 0 failures, over 12m10s
265 runs so far, 0 failures, over 12m15s
266 runs so far, 0 failures, over 12m20s
272 runs so far, 0 failures, over 12m25s
274 runs so far, 0 failures, over 12m30s
274 runs so far, 0 failures, over 12m35s
274 runs so far, 0 failures, over 12m40s
275 runs so far, 0 failures, over 12m45s
276 runs so far, 0 failures, over 12m50s
277 runs so far, 0 failures, over 12m55s
282 runs so far, 0 failures, over 13m0s
285 runs so far, 0 failures, over 13m5s
288 runs so far, 0 failures, over 13m10s
289 runs so far, 0 failures, over 13m15s
289 runs so far, 0 failures, over 13m20s
290 runs so far, 0 failures, over 13m25s
291 runs so far, 0 failures, over 13m30s
293 runs completed, 1 failures, over 13m34s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-12 02:54
Duplicate of #6432

**Closed by bdarnell** 2016-05-12 02:54 UTC
Labels: Robot, test-failure
