### ISSUE TITLE
circleci: failed tests (14333): TestDockerRuby

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5123] opened 2016-03-11 00:37 UTC
The following test appears to have failed:

[#14333](https://circleci.com/gh/cockroachdb/cockroach/14333):

```
I160311 00:36:59.094709 acceptance/replication_test.go:66  found 3 replicas
I160311 00:36:59.094742 acceptance/replication_test.go:74  found 3 replicas
I160311 00:36:59.094823 acceptance/cluster/docker.go:73  ImagePull cockroachdb/postgres-test:20160203-140220 starting
.......I160311 00:36:59.639616 acceptance/cluster/docker.go:88  ImagePull cockroachdb/postgres-test:20160203-140220 complete
I160311 00:37:02.437846 acceptance/cluster/localcluster.go:597  stopping
panic: test timed out after 5m0s

goroutine 1694 [running]:
panic(0xaba3a0, 0xc8203f9fb0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
testing.startAlarm.func1()
	/usr/local/go/src/testing/testing.go:725 +0x14b
created by time.goFunc
	/usr/local/go/src/time/sleep.go:129 +0x3a

goroutine 1 [chan receive]:
testing.RunTests(0xe9a220, 0x133fe60, 0xf, 0xf, 0xb34c73656fb60a01)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820762f08, 0xe99170)
	/usr/local/go/src/testing/testing.go:515 +0x81
github.com/cockroachdb/cockroach/acceptance.TestMain(0xc820762f08)
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:48 +0x3e
main.main()
	github.com/cockroachdb/cockroach/acceptance/_test/_testmain.go:80 +0x114

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x135c6e0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1010 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:604 +0x8a

goroutine 1650 [select]:
github.com/docker/engine-api/client/transport/cancellable.Do(0x7fd9a610bff0, 0xc8200157d8, 0x7fd9a610c120, 0xc82069f7a0, 0xc820165dc0, 0xc820371740, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:56 +0x49d
github.com/docker/engine-api/client.(*Client).sendClientRequest(0xc8203ab140, 0x7fd9a610bff0, 0xc8200157d8, 0xd22180, 0x6, 0xc820476af0, 0x4c, 0xc820371740, 0x7fd9a610c0c8, 0xc820473d50, ...)
	/go/src/github.com/docker/engine-api/client/request.go:110 +0x45a
github.com/docker/engine-api/client.(*Client).sendRequest(0xc8203ab140, 0x7fd9a610bff0, 0xc8200157d8, 0xd22180, 0x6, 0xc820476af0, 0x4c, 0xc820371740, 0x0, 0x0, ...)
	/go/src/github.com/docker/engine-api/client/request.go:88 +0x2b8
github.com/docker/engine-api/client.(*Client).delete(0xc8203ab140, 0xc820476af0, 0x4c, 0xc820371740, 0x0, 0xc820476af0, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/request.go:72 +0xe0
github.com/docker/engine-api/client.(*Client).ContainerRemove(0xc8203ab140, 0xc820620e00, 0x40, 0xc820010001, 0x0, 0x0)
	/go/src/github.com/docker/engine-api/client/container_remove.go:23 +0x3cb
--
testing.tRunner(0xc820646630, 0x133ff50)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 8 [chan receive, 4 minutes]:
github.com/cockroachdb/cockroach/acceptance.TestMain.func1()
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:39 +0xd8
created by github.com/cockroachdb/cockroach/acceptance.TestMain
	/go/src/github.com/cockroachdb/cockroach/acceptance/main_test.go:47 +0x30

goroutine 7 [syscall, 4 minutes]:
os/signal.signal_recv(0x6)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 1135 [IO wait]:
net.runtime_pollWait(0x7fd9a610c720, 0x72, 0xc8203c5000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82048c300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82048c300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82048c2a0, 0xc8203c5000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6328, 0xc8203c5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820061520)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 21 [select, 4 minutes, locked to thread]:
runtime.gopark(0xe9aa20, 0xc820023f28, 0xd2a118, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820023f28, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820023f28)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 12 [IO wait, 4 minutes]:
net.runtime_pollWait(0x7fd9a610d1a0, 0x72, 0xc8201db000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201bf560, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201bf560, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201bf500, 0xc8201db000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a370, 0xc8201db000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820139d40)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 13 [select, 4 minutes]:
net/http.(*persistConn).writeLoop(0xc820139d40)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 224 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd9a610cf60, 0x72, 0xc82043f000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82026e300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026e300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026e2a0, 0xc82043f000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6290, 0xc82043f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060410)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 967 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8201388f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 403 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820329970)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 136 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7fd9a610cea0, 0x72, 0xc82047e000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201b08b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b08b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201b0850, 0xc82047e000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6288, 0xc82047e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060820)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 225 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820060410)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 401 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820284b00)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 470 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd9a60d4368, 0x72, 0xc820335000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205f8300, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205f8300, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205f82a0, 0xc820335000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a238, 0xc820335000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820138b60)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 137 [select, 3 minutes]:
net/http.(*persistConn).writeLoop(0xc820060820)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 320 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820138a90)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 366 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820285c30)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 589 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82037a8f0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 319 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd9a610d020, 0x72, 0xc82041d000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82026e920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026e920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026e8c0, 0xc82041d000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a218, 0xc82041d000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820138a90)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 396 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc82018fd90)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 471 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820138b60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 375 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820328a50)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 379 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820328e70)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 364 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820285a20)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 742 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fd9a610c2a0, 0x72, 0xc820115000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82048c8b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82048c8b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82048c850, 0xc820115000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f62a0, 0xc820115000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8200609c0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 507 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc820424fd0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 588 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd9a610c7e0, 0x72, 0xc8202cf000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205f8290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205f8290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205f8230, 0xc8202cf000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6430, 0xc8202cf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82037a8f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 494 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc8203291e0)
	/usr/local/go/src/database/sql/sql.go:727 +0x45
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x33f

goroutine 523 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7fd9a610d0e0, 0x72, 0xc8202aa000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82026eed0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82026eed0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82026ee70, 0xc8202aa000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2f8, 0xc8202aa000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820060ea0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 524 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820060ea0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1233 [IO wait]:
net.runtime_pollWait(0x7fd9a60d41e8, 0x72, 0xc820315000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82048cdf0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82048cdf0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82048cd90, 0xc820315000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a3c0, 0xc820315000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820139e10)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 743 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc8200609c0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 966 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fd9a60d4068, 0x72, 0xc8203a4000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8205f8370, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8205f8370, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8205f8310, 0xc8203a4000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f62e0, 0xc8203a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc8201388f0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1136 [select]:
net/http.(*persistConn).writeLoop(0xc820061520)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1536 [select]:
net/http.(*persistConn).writeLoop(0xc82037b2b0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1053 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7fd9a610c360, 0x72, 0xc8203e0000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820246920, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820246920, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202468c0, 0xc8203e0000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a268, 0xc8203e0000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820061040)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1054 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc820061040)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1250 [select]:
net/http.(*persistConn).writeLoop(0xc820139e10)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1703 [select]:
net/http.(*persistConn).roundTrip(0xc820139930, 0xc8203336e0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1469 +0xf1f
net/http.(*Transport).RoundTrip(0xc8201b43c0, 0xc820165dc0, 0xc8201b43c0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:320 +0x9bb
net/http.send(0xc820165dc0, 0x7fd9a6105820, 0xc8201b43c0, 0x0, 0x0, 0x0, 0xc820460720, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:260 +0x6b7
net/http.(*Client).send(0xc820624cc0, 0xc820165dc0, 0x0, 0x0, 0x0, 0x92eff7, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:155 +0x185
net/http.(*Client).Do(0xc820624cc0, 0xc820165dc0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:193 +0x2b1
github.com/docker/engine-api/client/transport/cancellable.Do.func1(0x7fd9a610c120, 0xc82069f7a0, 0xc820165dc0, 0xc8203a97a0)
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:49 +0x35
created by github.com/docker/engine-api/client/transport/cancellable.Do
	/go/src/github.com/docker/engine-api/client/transport/cancellable/cancellable.go:52 +0xff

goroutine 1451 [IO wait]:
net.runtime_pollWait(0x7fd9a610c5a0, 0x72, 0xc8202ea000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202461b0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202461b0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820246150, 0xc8202ea000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8200f6318, 0xc8202ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820160b60)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1654 [select]:
net/http.(*persistConn).writeLoop(0xc820139930)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1354 [IO wait]:
net.runtime_pollWait(0x7fd9a60d3fa8, 0x72, 0xc8202bd000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc820638fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820638fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820638f50, 0xc8202bd000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a288, 0xc8202bd000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82037a0d0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1355 [select]:
net/http.(*persistConn).writeLoop(0xc82037a0d0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 1535 [IO wait]:
net.runtime_pollWait(0x7fd9a610c420, 0x72, 0xc82010f000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82048cca0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82048cca0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82048cc40, 0xc82010f000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a308, 0xc82010f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc82037b2b0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1653 [IO wait]:
net.runtime_pollWait(0x7fd9a610c960, 0x72, 0xc820256000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82048ca70, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82048ca70, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82048ca10, 0xc820256000, 0x1000, 0x1000, 0x0, 0x7fd9a6101050, 0xc820014210)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82002a2e8, 0xc820256000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
--
net/http.(*persistConn).readLoop(0xc820139930)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 1452 [select]:
net/http.(*persistConn).writeLoop(0xc820160b60)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-03-11 02:15
Duplicate of #5059.

**Closed by petermattis** 2016-03-11 02:15 UTC
Labels: test-failure
