### ISSUE TITLE
Test failure in CI build 5405

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#1942] opened 2015-08-04 14:49 UTC
The following test appears to have failed:

[#5405](https://circleci.com/gh/cockroachdb/cockroach/5405):

```
W0804 14:48:19.586075 450 storage/store.go:584  error gossiping first range data: storage/replica.go:971: node is stopping
W0804 14:48:19.586658 450 storage/store.go:603  error gossiping configs: storage/replica.go:971: node is stopping
I0804 14:48:19.597349 450 storage/replica.go:988  gossiping cluster id  from store 3, range 1
I0804 14:48:19.597815 450 storage/replica.go:996  gossiping sentinel from store 3, range 1
I0804 14:48:19.598132 450 storage/replica.go:1000  gossiping first range from store 3, range 1
panic: test timed out after 5m0s

goroutine 25583 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x168
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x59

goroutine 1 [chan receive, 4 minutes]:
testing.RunTests(0x14b8100, 0x19e5940, 0xba, 0xba, 0x1)
	/usr/src/go/src/testing/testing.go:556 +0xdc3
--
	/go/src/github.com/cockroachdb/cockroach/storage/store.go:581 +0x477
github.com/cockroachdb/cockroach/util/stop.func·001()
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:80 +0x8c
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:81 +0x14c
FAIL	github.com/cockroachdb/cockroach/storage	300.048s
=== RUN TestBatchBasics
I0804 14:44:20.775736 495 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 14:44:20.777335 495 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.01s)
=== RUN TestBatchGet
I0804 14:44:20.782167 495 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance
I0804 14:44:20.782522 495 storage/engine/rocksdb.go:124  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0804 14:44:20.786301 495 storage/engine/rocksdb.go:99  opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by tamird** [comment] 2015-08-04 14:52
Dupe of #1928.

**Closed by tamird** 2015-08-04 14:52 UTC
Labels: test-failure
