### ISSUE TITLE
sql: (release-20.2) flake in logic test temp_table/regression_48233

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#55031] opened 2020-09-30 09:35 UTC
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests/2333600?

```
../../sql/logictest/testdata/logic_test/temp_table:248: SELECT * FROM system.namespace WHERE name LIKE '%48233'
expected:
50  65  reg_48233  78
but found (query options: "rowsort" -> ignore the following ordering of rows) :
50  65  reg_48233  79
```

I think there's a table ID mismatch?

cc @solongordon for triage

**Comment by rafiss** [comment] 2020-12-15 18:12
I wonder if this could be explained by #55086 -- that was a rather flaky bug with temp tables.

**Comment by rafiss** [comment] 2021-01-12 20:02
Closing since we haven't been able to reproduce. We'll prioritize this if it happens again.

**Closed by rafiss** 2021-01-12 20:02 UTC
Labels: C-test-failure, backport-20.2.x, branch-release-20.2
