### ISSUE TITLE
importccl: investigate potential import performance regression

### ISSUE THREAD

**Issue by adityamaru** [cockroachdb/cockroach#77157] opened 2022-02-28 19:00 UTC
This is a tracking issue for a potential performance regression in IMPORT. This was first reported by @mwang1026 when running side-by-side IMPORTs on 21.2 and master of:

`IMPORT INTO defaultdb.public.trade CSV DATA ('gs://cockroach-fixtures/tpce-csv/customers=500000/*/Trade.txt?AUTH=implicit') WITH delimiter = '|', detached`

which resulted in the following durations:
```
21.2.3 in 3:43
master in 5:52
```

A similar regression was observed when running:

`./cockroach workload fixtures import tpcc --warehouses=500 --checks=false` on a single node, laptop.

The results were:

```
21.2 - imported 34 GiB bytes in 9 tables (took 4m8.855161s, 139.36 MiB/s) 
master - imported 34 GiB bytes in 9 tables (took 21m5.918455s, 27.57 MiB/s)
```

Jira issue: CRDB-13440

**Comment by adityamaru** [comment] 2022-02-28 19:38
I ran a smoke test TPCC import on a 4 node cluster with 500 warehouses and I haven't noticed the above regression yet:

Master:

<img width="1396" alt="Screen Shot 2022-02-28 at 2 36 55 PM" src="https://user-images.githubusercontent.com/13837382/156047441-3331ae8d-c85f-467b-a331-50c15bd6ab10.png">



21.2:
<img width="1404" alt="Screen Shot 2022-02-28 at 2 37 04 PM" src="https://user-images.githubusercontent.com/13837382/156047454-d5bc6530-da9f-480f-bfae-b9afc29a307d.png">

**Comment by adityamaru** [comment] 2022-02-28 20:57
Tried a 1 node default roachprod cluster with 500 warehouses to see if admission control was throttling us on master but results were pretty compareable again:

Master:

`imported 34 GiB bytes in 9 tables (took 16m34.133041242s, 35.11 MiB/s)`

21.2:

`imported 34 GiB bytes in 9 tables (took 17m46.111469398s, 32.53 MiB/s)`

**Comment by adityamaru** [comment] 2022-03-01 19:35
So giving up on the single node import thread for now, and focussing on the larger ~50 file import regression we are observing. I ran the same import on 21.2 and master. I ran in twice on master, one starting at ~22:00 on 02/28 and one starting at 14:00 on 01/03. Posting some observations (note the master graphs are across two imports):

`Master` - 

`21.2` - 3:35



The  rate of  `addsstable.sent`  seems to degrade on master  during the import:
<img width="1094" alt="master-addsstable-sent" src="https://user-images.githubusercontent.com/13837382/156231326-b87123cf-d953-4aba-aaad-e3f515faa8b6.png">

Whereas its pretty constant albeit spikey on 21.2
<img width="1058" alt="21 2-addsstable-sent" src="https://user-images.githubusercontent.com/13837382/156231333-1277b96f-a2e6-42e1-81c7-db03f3f21061.png">

The `total.delay` on master is less than what we see on 21.2:
<img width="990" alt="master-total-delay" src="https://user-images.githubusercontent.com/13837382/156231573-bb512497-43c6-41e8-93a6-7603e7e206fe.png">

21.2
<img width="1028" alt="21 2-total-delay" src="https://user-images.githubusercontent.com/13837382/156231579-351322e9-cd40-4763-ab70-524b5c156347.png">

There are more compactions during master than on 21.2, which led to looking at some metrics like log commit latency:

<img width="1704" alt="Screen Shot 2022-03-01 at 12 34 33 PM" src="https://user-images.githubusercontent.com/13837382/156231873-c456e947-889b-4155-8afe-ae261ad38771.png">


These however seem pretty comparable (master vs 21.2):
<img width="1704" alt="Screen Shot 2022-03-01 at 12 47 33 PM" src="https://user-images.githubusercontent.com/13837382/156231784-a243b4cb-2a39-4c2f-aeb4-c6514f648e1c.png">

I saw some differences in the range operations between the two clusters. Notably, the number of Adds (red), Removes (blue), and Snapshots Applied (initial replication) is more on master. @aayushshah15 noted that since the number of Adds and Removes are equal this is related to the better rebalancing that is occurring during the import, most likely due to https://github.com/cockroachdb/cockroach/pull/75894.

<img width="1879" alt="Screen Shot 2022-03-01 at 1 08 30 PM" src="https://user-images.githubusercontent.com/13837382/156232382-fe862cc2-67b6-40f4-acf9-a6ff0a7f9b5b.png">

I'm in the process of digging through a debug zip while the import was running. A preliminary look at the stacks show some nodes waiting on `AdminSplitAndScatter`. I also see `slow range RPCs logs` of the form:

` slow range RPC: have been waiting 110.14s (1 attempts) for RPC AdminScatter [‹/Table/104/1/200001402755827›,‹/Table/104/1/200001402755827/NULL›) to r8147:‹/Table/104/1/200001{402755827-572111887}› [(n6,s6):1, (n10,s10):2, (n1,s1):3, next=4, gen=4600, sticky=1646102723.249836119,0]; resp: ‹(err: <nil>), *roachpb.AdminScatterResponse›`

**Comment by nicktrav** [comment] 2022-03-01 21:06
Import performance came up in our weekly Storage meeting, and @mwang1026 asked me to post here.

In debugging a seemingly unrelated roachtest failure in clearrange (see #77080), I noticed that the import that seeds the test is taking 2.5-3 hours, whereas it used to only take 30 mins or so (~2 months ago from what I recall). The [import command being run](https://github.com/cockroachdb/cockroach/blob/9bab39faaf33dfe1f52b3edccc3f758fa6697f40/pkg/cmd/roachtest/tests/clearrange.go#L71-L72) is:

```
	c.Run(ctx, c.Node(1), "./cockroach", "workload", "fixtures", "import", "bank",
		"--payload-bytes=10240", "--ranges=10", "--rows=65104166", "--seed=4", "--db=bigbank")
```

There's a fairly strong signal in the import time log line (printed [here](https://github.com/cockroachdb/cockroach/blob/9bab39faaf33dfe1f52b3edccc3f758fa6697f40/pkg/cmd/roachtest/tests/clearrange.go#L73)) that I've been using to gauge good vs. bad. I've got a bisect working in the background (it's fairly slow going).

I can capture a debug zip for each of these runs and share at a later point, if it helps?

**Comment by erikgrinaker** [comment] 2022-03-01 21:18
I wonder if this could be related to the recent MVCC-ful `AddSSTable` changes, even the regression seems much worse than I'd expect. Does it still happen if you set `bulkio.import_at_current_time.enabled` to `false`?

**Comment by adityamaru** [comment] 2022-03-01 21:23
I'm currently running the import on a commit before https://github.com/cockroachdb/cockroach/pull/75894 and the addsstable sent rate seems to be more stable as compared to master where we saw a decay within the first hour.

<img width="1061" alt="Screen Shot 2022-03-01 at 4 23 11 PM" src="https://user-images.githubusercontent.com/13837382/156251154-86a236ed-4fa0-465a-a46c-9a92e12c5bd6.png">

> Does it still happen if you set bulkio.import_at_current_time.enabled to false

I'll kick this off too and let you know.

**Comment by adityamaru** [comment] 2022-03-01 21:27
incase folks want to poke around I have the following running the imports:
```
adityamaru-import-trade-21-2
adityamaru-import-trade-before-scatter
adityamaru-import-trade-master
```

**Comment by adityamaru** [comment] 2022-03-01 23:22
Okay so an import on the commit prior to https://github.com/cockroachdb/cockroach/pull/75894 is much more in line with 21.2 performance. It is on track to finish ~3.5 hours. I'm posting some more graphs I found interesting:

addsstable.sent is the higher plot:

Commit before scatter:

<img width="1138" alt="Screen Shot 2022-03-01 at 5 49 28 PM" src="https://user-images.githubusercontent.com/13837382/156264449-cff9b324-9ced-4362-af2f-4fd8723d2faa.png">

Master:

<img width="1128" alt="Screen Shot 2022-03-01 at 5 49 34 PM" src="https://user-images.githubusercontent.com/13837382/156264442-15cb2ab6-8313-4bb2-ad50-aac7fc832264.png">


Compactions on commit before scatter are more in line with 21.2. On master (graph above) they were between 20-30 during the import:

<img width="989" alt="Screen Shot 2022-03-01 at 6 12 44 PM" src="https://user-images.githubusercontent.com/13837382/156264585-7f512653-e9a5-4f1a-8253-c3afb7b2e054.png">

I also observed that in 21.2, and the commit prior to scatter we are creating ~15-20K SSTs during the import, but on master we are creating ~10k SSTs.

commit before scatter:
<img width="991" alt="Screen Shot 2022-03-01 at 6 15 33 PM" src="https://user-images.githubusercontent.com/13837382/156265065-e6e8dc80-7f5f-4664-91a4-e9011c1fce8b.png">

master:

<img width="986" alt="Screen Shot 2022-03-01 at 6 16 26 PM" src="https://user-images.githubusercontent.com/13837382/156265085-3b8a7aa3-28ac-4ffd-98f5-b37f6afb7f2a.png">


commit before scatter: 
<img width="971" alt="Screen Shot 2022-03-01 at 6 16 03 PM" src="https://user-images.githubusercontent.com/13837382/156265243-92ae3f80-9e3e-48f6-9737-6f8270a00574.png">


master:

<img width="985" alt="Screen Shot 2022-03-01 at 6 17 01 PM" src="https://user-images.githubusercontent.com/13837382/156265220-256eea5d-d88e-47ea-8877-a1020368df43.png">

**Comment by adityamaru** [comment] 2022-03-02 14:40
I ran the import @nicktrav mentioned above since its a quicker repro at `657c0e14884a7c29cf94192da14ccba699a555aa` and at `08ecb047a019c28e413f59ee30245df28f147163` to be doubly sure. The former took ~27mins, the latter is still running ~1hr in. Sensitizing AdminScatter seems to be decaying our addsstable.sent rate, and causing far more compactions:

<img width="995" alt="Screen Shot 2022-03-02 at 9 16 36 AM" src="https://user-images.githubusercontent.com/13837382/156380995-79a68026-82ef-4d11-93c8-f4da553e0c92.png">
<img width="984" alt="Screen Shot 2022-03-02 at 9 19 06 AM" src="https://user-images.githubusercontent.com/13837382/156380999-81c4125f-69f3-4ccd-88ec-f186bd150481.png">



<img width="1073" alt="Screen Shot 2022-03-02 at 9 23 42 AM" src="https://user-images.githubusercontent.com/13837382/156381168-bd07b390-ede4-491c-8632-6f406ed41f99.png">
<img width="1010" alt="Screen Shot 2022-03-02 at 9 24 02 AM" src="https://user-images.githubusercontent.com/13837382/156381178-d2759cdf-315b-4b23-9e38-bf723bf051bc.png">

Surprisingly the `total.delay` and `engine.backpressure` are not starkly different. I'm going to tag @aayushshah15 in at this point so we can start narrowing down on the root cause.

**Comment by adityamaru** [comment] 2022-03-02 15:00
Left is commit before scatter, right is with sensitized AdminScatter.

<img width="1731" alt="Screen Shot 2022-03-02 at 9 58 02 AM" src="https://user-images.githubusercontent.com/13837382/156387091-2a54011e-8efe-4750-906e-3db2e3374b92.png">
<img width="1710" alt="Screen Shot 2022-03-02 at 9 58 59 AM" src="https://user-images.githubusercontent.com/13837382/156387097-21328a1b-d1f3-4e1f-8882-3f4987e9de62.png">

**Comment by nicktrav** [comment] 2022-03-02 19:17
If it helps, I put the debug zips and the tsdumps I gathered while debugging this [here](https://drive.google.com/drive/folders/1xIr82d6xBA-6SQqo44iON2NVpAyRc7d6?usp=sharing) (CRL internal link). I marked the various commits as good / bad based on the import length I observed. For each of the debug zips / tsdumps, I took them after the import had completed.

**Comment by adityamaru** [comment] 2022-03-02 20:11
Bumped the vmodule of the `buffering_adder` to 4 and picked up the tail of the logs:

Pre admin scatter:
```
flushing (23m31.665905602s sending, 3m32.228025143s splitting
flushing (23m43.202919423s sending, 3m24.963353331s splitting
flushing (23m56.498414732s sending, 3m0.76597843s splitting
flushing (24m5.28881913s sending, 2m58.162760804s splitting
flushing (24m27.762106307s sending, 2m32.796113242s splitting
flushing (23m33.128476s sending, 3m32.463136514s splitting
```

With admin scatter:

```
flushing (23m35.563391927s sending, 39m41.074926782s splitting
flushing (14m34.850680674s sending, 49m31.489606554s splitting
flushing (19m52.671094483s sending, 43m49.60419277s splitting
flushing (19m12.534158477s sending, 44m30.784566003s splitting
flushing (14m36.461885424s sending, 49m45.535861296s splitting
```

So it seems pretty clear we're waiting a lot more in the bulk adder [`SplitAndScatter` call](https://github.com/cockroachdb/cockroach/blob/e4475a5e6acfeb694c5de59c59192772caa7e3ab/pkg/kv/bulk/sst_batcher.go#L410).

**Comment by aayushshah15** [comment] 2022-03-02 20:16
>So it seems pretty clear we're spending a lot more time in the bulk adder [SplitAndScatter call](https://github.com/cockroachdb/cockroach/blob/e4475a5e6acfeb694c5de59c59192772caa7e3ab/pkg/kv/bulk/sst_batcher.go#L410).

One of the reasons we decided to make `AdminScatter` more aggressive is based on the assumption that it was only ever called on empty ranges by the bulk adder. If that's the case, it's very surprising that we're spending so much more time on those `SplitAndScatter` calls,  so I strongly suspect that this understanding of ours is incorrect in the current implementation.

**Comment by adityamaru** [comment] 2022-03-03 13:37
To verify Aayush's theory that we weren't scattering empty ranges I tried looking for a metric that tracks the snapshot bytes flying around, but I don't believe we have one? Then I found https://github.com/cockroachdb/cockroach/blob/ac7e0b65886a2140763d1712e5aa9e70e2f6d976/pkg/kv/kvserver/replica_raftstorage.go#L869 where we log the data size of the snapshots being applied.


I looked at only the snapshots that were being applied to the table being imported into using:

`cg 'Table/109.*applied.*ingestion' debug/nodes/*/logs/cockroach.*.log | grep -o 'applied.*' | less`

and got the following output:
[snapshot.txt](https://github.com/cockroachdb/cockroach/files/8178260/snapshot.txt)

Theres a large variance in the data sizes but towards the end, I do see noticeable sized snapshots being applied:
```
applied INITIAL snapshot bea661be from (n6,s6):1 at applied index 14 (total=29ms data=29 MiB ingestion=6@27ms)
applied INITIAL snapshot 008b9bbd from (n9,s9):3 at applied index 23 (total=11ms data=49 MiB ingestion=6@9ms)
applied INITIAL snapshot 6e6b3c8f from (n9,s9):3 at applied index 22 (total=9ms data=29 MiB ingestion=6@8ms)
applied INITIAL snapshot 9bdf1e0f from (n2,s2):2 at applied index 13 (total=12ms data=29 MiB ingestion=6@11ms)
applied INITIAL snapshot cfbc29ed from (n9,s9):3 at applied index 31 (total=24ms data=29 MiB ingestion=6@23ms)
applied INITIAL snapshot 6ce28057 from (n9,s9):3 at applied index 41 (total=4ms data=49 MiB ingestion=6@2ms)
```

**Comment by adityamaru** [comment] 2022-03-20 05:58
@dt assigning this to you since youve been knee deep in the fixes, and will have a better idea of when this can be closed.

**Comment by dt** [comment] 2022-04-01 23:36
This is expected to be fixed by https://github.com/cockroachdb/cockroach/pull/78523 + https://github.com/cockroachdb/cockroach/pull/78218 both of which will need backports.

**Closed** 2022-04-07 15:49 UTC
Labels: C-bug, A-bulkio, A-kv, branch-master, T-bulkio, GA-blocker
