### ISSUE TITLE
storage: Rebalancing should take region topology into consideration

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#35524] opened 2019-03-07 21:36 UTC
**Is your feature request related to a problem? Please describe.**
Rebalancing should take region topology into consideration. If we can safely rebalance to another node in the same region we should do this rather than traveling across to another region.

This will reduce the cost of rebalancing and speed it up to get to a recovered state faster.

**Comment by lunevalex** [comment] 2021-04-23 04:02
Dupe of #42491

**Closed** 2021-04-23 04:02 UTC
Labels: A-kv-distribution, C-enhancement, X-duplicate
