### ISSUE TITLE
sql,opt: query on a table with 91 rows can hang forever

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#106734] opened 2023-07-12 23:52 UTC
**Describe the problem**

The following query seems to hang forever
```
SELECT NOT EXISTS (SELECT *
 FROM "Customers" AS c
   WHERE NOT (EXISTS (SELECT *
 FROM "Customers" AS c0
   WHERE EXISTS (SELECT *
 FROM "Customers" AS c1
   WHERE c."CustomerID" = c1."CustomerID"))))
```

**To Reproduce**

Use this script [northwind-simple.txt](https://github.com/cockroachdb/cockroach/files/12028135/northwind-simple.txt) to create and populate the sample database

Run the above query. It never completes.

**Expected behavior**
It should finish, and return a single row, with a `true` result.

**Additional data / screenshots**
The explain plan
```
  distribution: local
  vectorized: true

  • root
  │
  ├── • values
  │     size: 1 column, 1 row
  │
  └── • subquery
      │ id: @S1
      │ original sql: (SELECT * FROM "Customers" AS c WHERE NOT (EXISTS (SELECT * FROM "Customers" AS c0 WHERE EXISTS (SELECT * FROM "Customers" AS c1 WHERE c."CustomerID" = c1."CustomerID"))))
      │ exec mode: one row
      │
      └── • render
          │
          └── • limit
              │ count: 1
              │
              └── • apply join (anti)
                  │ estimated row count: 0
                  │
                  └── • scan
                        estimated row count: 91 (100% of the table; stats collected 2 minutes ago)
                        table: Customers@Customers_Region_idx
                        spans: FULL SCAN
                        
```

**Environment:**
CockroachDB v23.1.3

Jira issue: CRDB-29695

**Comment by mgartner** [comment] 2023-07-13 18:19
Nice find! Thanks for the report! This is a duplicate of #105882 and it should be addressed by #105931. I'll close this for now.

**Closed by mgartner** 2023-07-13 18:19 UTC
Labels: C-bug, T-sql-queries, A-tools-efcore
