### ISSUE TITLE
sql: panic while executing 1 statements: SELECT count(*) AS _ FROM (SELECT _, _,...

### ISSUE THREAD

**Issue by jordanlewis** [cockroachdb/cockroach#29477] opened 2018-09-03 02:04 UTC
https://sentry.io/cockroach-labs/cockroachdb/issues/672256053/

```
*log.safeError: conn_executor.go:668: panic while executing 1 statements: SELECT count(*) AS _ FROM (SELECT _, _, _ FROM _ WHERE ((_ = $1) AND (_ < $2)) AND (_ IN (SELECT _ FROM _ JOIN _ ON (((_ = _) AND (_ = _)) AND (_ >= (_ - _))) AND (_ < _) WHERE (_ = $3) AND (_ = $4)))) AS _: caused by <redacted>
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in func1 at line 414
Called from: runtime/asm_amd64.s in call32
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in ProcessRow at line 370
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in processRowHelper at line 716
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/interleaved_reader_joiner.go in nextRow at line 239
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/interleaved_reader_joiner.go in Next at line 109
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go in fill at line 308
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/sorter.go in Start at line 289
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/stream_group_accumulator.go in start at line 62
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/stream_merger.go in start at line 45
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/mergejoiner.go in Start at line 118
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go in start at line 400
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/aggregator.go in Start at line 396
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/processors.go in Run at line 738
github.com/cockroachdb/cockroach/pkg/sql/distsqlrun/flow.go in StartSync at line 594
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in Run at line 245
github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go in PlanAndRun at line 735
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execWithDistSQLEngine at line 966
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in dispatchToExecutionEngine at line 808
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmtInOpenState at line 401
github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go in execStmt at line 95
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in run at line 1135
github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go in ServeConn at line 416
github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go in func3 at line 267

conn_executor.go:668: panic while executing 1 statements: SELECT count(*) AS _ FROM (SELECT _, _, _ FROM _ WHERE ((_ = $1) AND (_ < $2)) AND (_ IN (SELECT _ FROM _ JOIN _ ON (((_ = _) AND (_ = _)) AND (_ >= (_ - _))) AND (_ < _) WHERE (_ = $3) AND (_ = $4)))) AS _: caused by <redacted>
```

**Comment by jordanlewis** [comment] 2018-09-03 02:07
```
	} else if h.outputCols != nil {
		// Projection.
		for i, col := range h.outputCols {
			h.outputRow[i] = row[col]
		}
```

This is an index out of bounds error on the assignment line above.

**Comment by robert-s-lee** [comment] 2018-09-03 02:17
Generated while running https://github.com/louishust/benchmarksql-cockroachdb

**Comment by asubiotto** [comment] 2018-11-30 18:47
Looking at the repo, this looks like (placeholders filled in):
```
SELECT
    count(*) AS low_stock
FROM
    (
        SELECT
            s_w_id, s_i_id, s_quantity
        FROM
            stock
        WHERE
            s_w_id = 0
            AND s_quantity < 20
            AND s_i_id
                IN (
                        SELECT
                            ol_i_id
                        FROM
                            district
                            JOIN order_line
                            ON
                                ol_w_id = d_w_id
                                AND ol_d_id = d_id
                                AND ol_o_id >= d_next_o_id - 20
                                AND ol_o_id < d_next_o_id
                        WHERE
                            d_w_id = 0 AND d_id = 4
                    )
    )
        AS l;
```
Unfortunately running this query on 1-node local cluster with tpcc stocklevel 1 doesn't produce a panic.

**Comment by jordanlewis** [comment] 2019-02-07 16:50
This is another one of #34468, but reproducible. Going to dig in more.

**Comment by yuzefovich** [comment] 2019-09-05 01:13
@jordanlewis what did you mean when you said "reproducible" above? I tried running the benchmark that Robert linked, but the issue didn't repro. Specifically, I tried a single local node on current master (19.2) and a single local node as well as a three node cluster on my laptop on v2.1.8. Do you remember whether you were able to reproduce the issue, and if so, what were the steps?

**Comment by jordanlewis** [comment] 2019-09-05 01:29
Unfortunately, I don't remember. I ran Robert's benchmark on a multi-node cluster. Probably roachprod. Try running it for a while. If you can't reproduce, close it.

**Comment by yuzefovich** [comment] 2019-09-05 02:03
Ok, I'm trying it out on a 3 node roachprod cluster.

Should the interleaved joiner appear on the output of explain?
```
  group                         |                |                                                              
   │                            | aggregate 0    | count_rows()                                                 
   │                            | scalar         |                                                              
   └── render                   |                |                                                              
        └── join                |                |                                                              
             │                  | type           | semi                                                         
             │                  | equality       | (s_i_id) = (ol_i_id)                                         
             │                  | mergeJoinOrder | +"(s_i_id=ol_i_id)"                                          
             ├── scan           |                |                                                              
             │                  | table          | bmsql_stock@primary                                          
             │                  | spans          | /0-/1                                                        
             │                  | filter         | s_quantity < 20                                              
             └── sort           |                |                                                              
                  │             | order          | +ol_i_id                                                     
                  └── join      |                |                                                              
                       │        | type           | inner                                                        
                       │        | equality       | (d_w_id, d_id) = (ol_w_id, ol_d_id)                          
                       │        | mergeJoinOrder | +"(d_w_id=ol_w_id)",+"(d_id=ol_d_id)"                        
                       │        | pred           | (ol_o_id >= (d_next_o_id - 20)) AND (ol_o_id < d_next_o_id)  
                       ├── scan |                |                                                              
                       │        | table          | bmsql_district@primary                                       
                       │        | spans          | /0/4-/0/4/#                                                  
                       └── scan |                |                                                              
                                | table          | bmsql_order_line@primary                                     
                                | spans          | /0/4-/0/5 
```

**Comment by jordanlewis** [comment] 2019-09-05 03:17
It should, or at least on the explain distsql.

**Comment by yuzefovich** [comment] 2019-09-06 00:10
I tried to reproduce it using the benchmark Robert linked above but didn't succeed. I tried the following cluster configurations:
- single node on my laptop
  - v2.0.5
  - v2.1.8
  - current master (v19.2)
- 3 node cluster on my laptop
  - v2.1.8
  - current master (v19.2)
- 3 node roachprod cluster
  - v2.0.5
  - v2.1.8

One confusing to me thing is that interleaved join is in the stack trace posted above, but it doesn't show up in the output of `EXPLAIN (DISTSQL)` of the query:
<img width="898" alt="Screen Shot 2019-09-05 at 5 08 18 PM" src="https://user-images.githubusercontent.com/5135385/64392031-d776ad80-cfff-11e9-94be-32c4725c9912.png">

I will close this issue as unactionable at the moment, and if the problem appears again, we'll take it from there.

**Closed by yuzefovich** 2019-09-06 00:10 UTC
Labels: A-sql-execution, A-sql-interleaved, C-bug, O-sentry, S-2-temp-unavailability
