### ISSUE TITLE
CDC: Can't specify which certificate authority to trust for schema registry connection

### ISSUE THREAD

**Issue by rolandcrosby** [cockroachdb/cockroach#42882] opened 2019-12-02 16:53 UTC
A customer ran into the following errors when attempting to set up CDC with Kafka and the confluent schema registry:

`W191129 08:35:07.650325 688506364 ccl/changefeedccl/changefeed_stmt.go:521 [n1] CHANGEFEED job 507727404355256321 returning with error: Post https://[schema registry address]:8443/subjects/[table name]-key/versions: x509: certificate signed by unknown authority`

This is because the TLS certificates used by the schema registry's HTTPS endpoints were signed by a custom enterprise certificate authority, and CockroachDB doesn't have a way of specifying which CA to trust for this scenario. (The CA certificate configuration URI parameter we added was specifically for connections to Kafka itself, not the schema registry.)

In the short term, the customer may be able to work around this by adding the CA certificate to the OS's global CA pool, but it would be good for CockroachDB to provide a mechanism to configure this directly.

**Comment by RoachietheSupportRoach** [comment] 2020-04-01 15:04
Zendesk ticket #[4135](https://cockroachdb.zendesk.com/agent/tickets/4135) has been linked to this issue.

**Comment by robert-s-lee** [comment] 2020-04-01 15:06
@mwang1026 are there updates that may have moved this forward?

**Comment by mwang1026** [comment] 2020-04-01 15:25
Not for 20.1. There is a workaround for this so we pushed it out in terms of priority

**Comment by spiffyyeng** [comment] 2021-06-29 20:06
Closing since this looks like a duplicate of #64622

**Closed by spiffyyeng** 2021-06-29 20:06 UTC
Labels: A-cdc, C-bug, T-cdc
