### ISSUE TITLE
sql: support `FOR {UPDATE,SHARE} {SKIP LOCKED,NOWAIT}`

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#40476] opened 2019-09-04 17:38 UTC
#6583 and #40206 added support for SELECT FOR UPDATE. There is additional syntax to support: SKIP LOCKED and NOWAIT. See an example of the syntax here: https://www.postgresql.org/docs/current/sql-select.html

---

Update, Feb 2021: CockroachDB v20.2 supports the `NO WAIT` syntax. `SKIP LOCKED` is still not supported at the time of this writing.

Epic CRDB-11976

Jira issue: CRDB-5535

**Comment by nvanbenschoten** [comment] 2020-01-15 16:59
This rest of this was addressed by #43868.

**Comment by rafiss** [comment] 2020-01-15 19:49
@nvanbenschoten thanks for adding this to the parser! It looks like the #43868 adds code that references this issue(i.e. `unimplementedWithIssueDetailf(40476, ...)`) , so I'm going to leave this open.

**Comment by nvanbenschoten** [comment] 2020-01-15 19:51
Good point, thanks for re-opening. I was thinking this was now covered by #40205, but that's not the case.

**Comment by KoryNunn** [comment] 2020-07-29 00:14
Has there been any activity towards adding NOWAIT recently?

**Comment by nvanbenschoten** [comment] 2020-07-29 13:28
Hi @KoryNunn, unfortunately, NOWAIT is not currently on our short term roadmap. Do you mind elaborating on your use case for the functionality?

**Comment by KoryNunn** [comment] 2020-07-30 01:03
Sure, we would like to use it to check if processing should be done on a record. If any other process has a lock on a row, it should ignore it, as another process is working on it.

Currently without NOWAIT all processes that look up a row have to wait untill the lock is released, see that processing is complete, and then skip the row.

If you have any suggestions to get equivalent functionality without NOWAIT, I'd be very happy to learn.

**Comment by nvanbenschoten** [comment] 2020-08-18 17:37
@KoryNunn https://github.com/cockroachdb/cockroach/pull/52522 just landed, so this will make it into the next release of CockroachDB, version 20.2.

**Comment by dilyevsky** [comment] 2020-10-08 18:03
@nvanbenschoten thanks, great to see progress with `NOWAIT`! Is `SKIP LOCKED` still in the works?

**Comment by nvanbenschoten** [comment] 2020-10-08 18:36
@dilyevsky `SKIP LOCKED` is not yet planned. We're pretty hesitant to introduce it because, unlike `NOWAIT`, `SKIP LOCKED` is a direct violation of serializable isolation. This complicates the implementation and leaves a lot of ambiguity around the interaction that the option should have in relation to other functionality.

**Comment by rockwotj** [comment] 2021-02-17 14:18
> @dilyevsky `SKIP LOCKED` is not yet planned. We're pretty hesitant to introduce it because, unlike `NOWAIT`, `SKIP LOCKED` is a direct violation of serializable isolation. This complicates the implementation and leaves a lot of ambiguity around the interaction that the option should have in relation to other functionality. 

FWIW SKIP LOCKED is really a workaround for building transactional queues, I wonder if cockroach could provide a better abstraction for this (in terms have having first class queues). Spanner does this, so you can get the perf benefits that SKIP LOCKED provides, but isolate it from the rest of the system and don't have to reason about being able to break serialization layers.

**Comment by kocoten1992** [comment] 2021-02-17 15:51
I want to share my experience, I'm also building a queues, before I though I would need `SELECT FOR UPDATE` and `SKIP LOCKED`, turn out I didn't need any of those!!

My trick is to use `CTE` with `RETURNING` clause, for example:

```sql
with abc as (
    select id table_1 where ... limit 1
), xyz as (
    update table_2 set ... returning id
), mnt as (
    delete from table_3 where table_1_id in (select id from table_1) and not exists (select * from xyz)
) select 1;
```

You get the idea!

Since with CTE we could run many sql, you can get rid of transaction (autocommit mode) and still guarantee serialize isolation. That how I don't need these feature anymore.

(That just my assumption, could anyone confirm cockroachdb work that way ?)

**Comment by Nican** [comment] 2021-09-05 19:04
I am in need of `SKIP LOCKED` for a ticketing system. I have a scenario where each user can only claim one ticket, and would like a method for users to claim the first non-claimed ticket in a payment transaction. 

Also making queues would be nice.

**Comment by kocoten1992** [comment] 2021-09-06 20:08
> I am in need of `SKIP LOCKED` for a ticketing system. I have a scenario where each user can only claim one ticket, and would like a method for users to claim the first non-claimed ticket in a payment transaction.

Wouldn't this work ? `update tickets set user_id = ?, claimed = true where claimed = false returning *`

**Comment by Nican** [comment] 2021-09-07 02:58
> Wouldn't this work ? `update tickets set user_id = ?, claimed = true where claimed = false returning *`

That is not the only operation inside of the transaction. The order must be completed, vouchers may have been claimed, and other things. I would like to keep the atomicity of the whole operation.

**Comment by Bessonov** [comment] 2021-09-07 18:05
Transactions are serialized (not linearilized) by design. Do you have an example when it won't work for you? And look at CTE above.

**Comment by Nican** [comment] 2021-09-07 21:20
Thank you for taking your time @kocoten1992 / @Bessonov. 

I just took some time to test things.

The original issue that we had is that were using a `in_stock` value in a `products` table. Every time an order was complete, a `UPDATE products SET in_stock=in_stock-1` query would be executed, but we found that the row would be locked, and only allow 1 transaction to be executed at the time. This was causing delays sometimes when several orders were being processed at the same time for the same product. (Unfortunately, due to some design decisions, some orders may take up to 3 seconds to process)

I just did some tests by using the `tickets` table without using "SKIP LOCKED", and while the operations are still serialized, it has the lock/delay issue. Each transaction is going to be waiting on other transactions to find an available ticket.

Example code:
```
create table orders(id int primary key, status string);
create table tickets (id int primary key, claimed boolean);
insert into orders values (0, 'unpaid'), (1, 'unpaid');
insert into tickets values (0, false), (1, false);
```

User 1: 
```
begin transaction;
update orders set status='paid' where id=0;
update tickets set claimed=true where claimed=false limit 1 returning *;
```

User 2:
```
begin transaction;
update orders set status='paid' where id=1;
update tickets set claimed=true where claimed=false limit 1 returning *;
```

User 2 is stuck until User 1 runs `commit`.  While the code functions correctly, it is a bottleneck during periods of high load.

**Comment by kocoten1992** [comment] 2021-09-08 05:54
@Nican , moved the discussion here https://www.reddit.com/r/CockroachDB/comments/pk4nqa/using_cte_instead_select_for_updateskip_locked/

**Comment by Bessonov** [comment] 2021-09-08 17:50
Doesn't [something like](https://dbfiddle.uk/?rdbms=postgres_13&fiddle=95ceb0c64ed027edcda76dd0b9ee0203) works for you? (I have no crdb on this laptop):

```sql
with t as (
  select * from tickets where claimed=false limit 1
),
o as (
  update orders set status='paid' where id=0
)
update tickets set claimed=true where id in (select id from t) returning *
```

**Comment by otan** [comment] 2021-12-08 11:22
this blocks hasura

**Closed** 2022-08-10 02:44 UTC
Labels: C-enhancement, A-sql-pgcompat, X-anchored-telemetry, T-kv, A-tools-hasura
