### ISSUE TITLE
Has data race at the master branch

### ISSUE THREAD

**Issue by thundercw** [cockroachdb/cockroach#3195] opened 2015-11-23 09:34 UTC
```
WARNING: DATA RACE
Write by goroutine 107:
  github.com/cockroachdb/cockroach/storage.(*Replica).ApplySnapshot()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/storage/replica_raftstorage.go:503 +0xa15
  github.com/cockroachdb/cockroach/multiraft.(*writeTask).start.func1()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/multiraft/storage.go:236 +0xbe6
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Previous read by goroutine 132:
  github.com/cockroachdb/cockroach/storage.(*splitQueue).shouldQueue()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/storage/split_queue.go:83 +0x2fd
  github.com/cockroachdb/cockroach/storage.(*baseQueue).MaybeAdd()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/storage/queue.go:210 +0x452
  github.com/cockroachdb/cockroach/storage.(*Store).systemGossipUpdate()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/storage/store.go:648 +0x2c6
  github.com/cockroachdb/cockroach/storage.(*Store).(github.com/cockroachdb/cockroach/storage.systemGossipUpdate)-fm()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/storage/store.go:519 +0x37

Goroutine 107 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:89 +0x6f
  github.com/cockroachdb/cockroach/multiraft.(*writeTask).start()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/multiraft/storage.go:257 +0xcd
  github.com/cockroachdb/cockroach/multiraft.(*state).start.func1()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/multiraft/multiraft.go:559 +0x222
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:88 +0x5f

Goroutine 132 (finished) created at:
  github.com/cockroachdb/cockroach/gossip.(*Gossip).updateSystemConfig()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/gossip/gossip.go:390 +0x3c0
  github.com/cockroachdb/cockroach/gossip.(*Gossip).(github.com/cockroachdb/cockroach/gossip.updateSystemConfig)-fm()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/gossip/gossip.go:158 +0x81
  github.com/cockroachdb/cockroach/gossip.(*infoStore).processCallbacks.func1()
      /home/thunder/cock/src/github.com/cockroachdb/cockroach/gossip/infostore.go:242 +0xe5

```

**Comment by bdarnell** [comment] 2015-11-23 11:08
Duplicate of #3164

**Closed by bdarnell** 2015-11-23 11:08 UTC
