### ISSUE TITLE
ui: clusterviz circle layout gets crowded easily

### ISSUE THREAD

**Issue by a-robinson** [cockroachdb/cockroach#22874] opened 2018-02-21 04:11 UTC
<img width="1379" alt="screen shot 2018-02-20 at 11 06 03 pm" src="https://user-images.githubusercontent.com/7085343/36462694-e42f6dd2-1692-11e8-9078-d91f470788f5.png">

This is running on top of 6ce6e9534fde28a66bc2fa7ce248f1bed03bd307. I created a 9 node cluster with 3 nodes in each of `region=us-east1,zone=us-east1-b`, `region=us-east1,zone=us-east1-c`, and `region=us-east1,zone=us-east1-d`. I opened up the UI, clicked on the us-east1-b locality, and saw the above image, which is failing to show the name/ID of the top node, and I can't figure out a way to scroll or click-and-drag it into view.

There's also some overlap of the text on the lower two nodes, but it seems as though not being able to see what the top node is at all is a bigger deal.

If I make my Chrome window as tall as I can, the only extra little bit I get is:

<img width="1376" alt="screen shot 2018-02-20 at 11 10 16 pm" src="https://user-images.githubusercontent.com/7085343/36462755-48b808b8-1693-11e8-803f-afdb5ae1563c.png">

@couchand

**Comment by couchand** [comment] 2018-02-21 14:40
I had at first thought this was a dupe of #22557, but it looks like the discussion there was focused entirely on the map view, and this is about the circle view.  All the discussion about this has been offline.

I'm changing the title to reflect the more general layout concerns with this non-geographical layout.

**Comment by couchand** [comment] 2018-02-21 14:41
The problem looking much worse on omega:

![image 1](https://user-images.githubusercontent.com/793969/36485987-6acab0ec-16eb-11e8-87da-aad02c9fc3a4.png)

**Comment by couchand** [comment] 2018-02-21 22:46
Closed in #22905

**Closed by couchand** 2018-02-21 22:46 UTC
