### ISSUE TITLE
webui: node presents as healthy in the face of network partition 

### ISSUE THREAD

**Issue by awoods187** [cockroachdb/cockroach#42790] opened 2019-11-26 16:40 UTC
We met with a customer today and they weren't sure how to debug a one-way network partition. This is related to https://github.com/cockroachdb/cockroach/issues/42788.

The node appeared to be healthy on the overview page. This creates a false impression that the node (and cluster) is in a healthy state. The node was not receiving replicas, was not rebalancing, and otherwise was not participating in the cluster. 

cc @BramGruneir and @piyush-singh

**Comment by piyush-singh** [comment] 2019-11-26 19:13
Closing this as a duplicate of #36890 . FWIW we are adding this as a callout to the network latency matrix, and we're going to eventually add alerts as indicated in the linked issue.

![image](https://user-images.githubusercontent.com/21692034/69664717-f01ebe80-1056-11ea-9eca-a6ea22f0e5ae.png)

**Closed by piyush-singh** 2019-11-26 19:13 UTC
Labels: A-webui-general, C-bug, S-3-productivity, S-3-ux-surprise
