### ISSUE TITLE
Limit concurrency of active SQL requests to reduce metastable outages

### ISSUE THREAD

**Issue by andrewbaptist** [cockroachdb/cockroach#110272] opened 2023-09-08 17:23 UTC
**Is your feature request related to a problem? Please describe.**
In several instances we have seen a high number of active transaction on a system cause the system to fall over. Many customers with open loop workloads have large connection pools (thousands of open connections) that are mostly idle. However if there is any other problem in the system which causes higher KV/storage latency, and this causes the number of active connections to grow rapidly. Even worse if the system hits client timeouts, we can end up with a higher QPS at the time where we have a high active connection count and a slow system which spirals. Specifically we see high goroutine counts per CPU and high scheduling latencies which makes everything slower and makes recovery impossible until the user workload decreases. So even though we could have handled this many QPS initially we are now in a worse state.

**Describe the solution you'd like**
The simplest solution is to add a configuration parameter similar to `server.max_connections_per_gateway` that is `server.max_open_transactions_per_gateway`. Many customers are reluctant to set `server.max_connections_per_gateway` because if it is too low it causes problems and if it is too high it will be ineffective. The default setting for this should be something like 200 (or maybe computed as `max_open_transctions_per_cpu` and set at 5).  Once the limit is hit, a new transaction would fail fast with a "too busy" error (something like an HTTP 503). This allows the client to wait and retry. This could optionally also be configured at a per-tenant level with a lower limit.

**Describe alternatives you've considered**
There are two other alternatives to this.

The first is to multiplex transactions onto a small number of goroutines. This would require some type of affinity and scheduling at the connection to goroutine boundary but in theory we could at least maintain QPS in the face of more active connections rather than decreasing. If this is done in a FIFO manner, it would likely just defer the problem a little since all the requests would time out. 

The second and better long term solution is to make this more dynamic. Specifically AC would observe the number of goroutines and scheduling latency and dynamically cap the number of transactions once it was impacting system performance. This would allow the system to dynamically compute what the right number of active transactions are and pause new transactions if the load was too high. This is probably the better long term solution, but harder to implement, so we might not want to expose this parameter as customer facing immediately. 

Jira issue: CRDB-31355

Epic CRDB-35306

**Comment by sumeerbhola** [comment] 2023-09-14 12:50
Can we get a roachtest reproduction of this? I fully appreciate that we have seen these problems in the wild, but I don't quite understand what we are seeing.
I am wary of a limit like `server.max_open_transactions_per_gateway`, since it is sensitive to the workload and current processing speed -- longer running txns would cause this limit to be hit while resources are sitting idle.

**Comment by sumeerbhola** [comment] 2023-09-19 14:48
assigning to you @andrewbaptist only for the reproduction

**Comment by sumeerbhola** [comment] 2023-09-27 14:27
See also https://cockroachlabs.slack.com/archives/C01SRKWGHG8/p1695770180815579 for a customer cluster with periodic SQL statement spikes and high runnable goroutine counts.

**Comment by andrewbaptist** [comment] 2023-09-28 16:53
As discussed with @shralex 
1) SQL Foundations creates a repro 
2) Admission Control folks take a look and see what exactly causes the issue, 
3) we discuss next steps with Rima, either falling on Admission Control, SQL Foundation, both or neither, depending on the gained understanding of the issue.

**Comment by rimadeodhar** [comment] 2023-10-20 20:51
Reassigning to Rafi who is working on the repro.

**Comment by rimadeodhar** [comment] 2023-11-29 16:57
@andrewbaptist - Rafi has a repro at https://cockroachlabs.atlassian.net/browse/CRDB-31584. Could you take a look and let us know if you need anything else?

**Comment by shralex** [comment] 2023-11-30 12:08
Thanks! Based on the next steps outlined in https://github.com/cockroachdb/cockroach/issues/110272#issuecomment-1739692114, assigning this to @sumeerbhola  to take a look from AC end. If KV involvement is needed, please let us know.

**Comment by sumeerbhola** [comment] 2023-11-30 15:57
@rafiss I looked at the repro instructions and I am confused: it seems to be one or a few high concurrency kv95 workloads. It is expected that these will overload the CPU, and so there will be AC queueing. And since they are all running at the same priority they will all be affected. High latency is expected in this case.

The original issue was about things happening that are outside of AC's control and causing metastable outages. I am assigning this back to @andrewbaptist and @rafiss so that we can have clarity on what this issue is about and whether this repro is doing something in line with the expectations of the issue.

**Comment by rafiss** [comment] 2023-11-30 18:52
Sure, let's keep discussing here. The repro I was shooting for in https://cockroachlabs.atlassian.net/browse/CRDB-31584 is described in the description of that ticket:
> We have seen a number of Roblox escalations where foreground traffic performance degrades when the number of active connections is high. 

From reading the details on https://github.com/cockroachlabs/support/issues/2579, it seems like one of the other symptoms we wanted to reproduce was "runnable goroutines per CPU" rising high above the single digits. Both of these behaviors can be seen when running the kv workload with high concurrency. For example, using
```
roachprod run $CLUSTER:4 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
roachprod run $CLUSTER:5 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
roachprod run $CLUSTER:6 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
``` 
I see that the runnable goroutines per CPU rises up to ~60.

>  It is expected that these will overload the CPU, and so there will be AC queueing. And since they are all running at the same priority they will all be affected. High latency is expected in this case.

I agree that the high latencies are expected. We also [document](https://www.cockroachlabs.com/docs/stable/connection-pooling?filters=selfhosted#size-connection-pools) that one should avoid running too many concurrent queries:

> Use the following formula to size the connection pool:
> 
> **connections = (number of cores * 4)**
> 
> If you have a large number of services connecting to the same cluster, make sure the number of concurrent active connections across all the services does not exceed this recommendation. 

My understanding is that although the higher latency was expected, the ask here was just to reproduce that behavior so that we can use the repro to drive investigation into further improvements (which is also mentioned in the description of https://cockroachlabs.atlassian.net/browse/CRDB-31584).

**Comment by rafiss** [comment] 2023-11-30 18:57
Sure, let's keep discussing here. The repro I was shooting for in https://cockroachlabs.atlassian.net/browse/CRDB-31584 is described in the description of that ticket:
> We have seen a number of escalations where foreground traffic performance degrades when the number of active connections is high. 

From reading the details on https://github.com/cockroachlabs/support/issues/2579, it seems like one of the other symptoms we wanted to reproduce was "runnable goroutines per CPU" rising high above the single digits. Both of these behaviors can be seen when running the kv workload with high concurrency. For example, using
```
roachprod run $CLUSTER:4 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
roachprod run $CLUSTER:5 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
roachprod run $CLUSTER:6 -- "./cockroach workload run kv --read-percent=95 --concurrency=2500 --duration=20m {urls}"
``` 
I see that the runnable goroutines per CPU rises up to ~60.

>  It is expected that these will overload the CPU, and so there will be AC queueing. And since they are all running at the same priority they will all be affected. High latency is expected in this case.

I agree that the high latencies are expected. We also [document](https://www.cockroachlabs.com/docs/stable/connection-pooling?filters=selfhosted#size-connection-pools) that one should avoid running too many concurrent queries:

> Use the following formula to size the connection pool:
> 
> **connections = (number of cores * 4)**
> 
> If you have a large number of services connecting to the same cluster, make sure the number of concurrent active connections across all the services does not exceed this recommendation. 

My understanding is that although the higher latency was expected, the ask here was just to reproduce that behavior so that we can use the repro to drive investigation into further improvements (which is also mentioned in the description of https://cockroachlabs.atlassian.net/browse/CRDB-31584).

**Comment by andrewbaptist** [comment] 2023-11-30 20:35
The core point here is not that the system had high latency, but that it had significantly worse throughput with a higher active connection count. 

Specifically running with a smaller number of concurrent active transactions they were able to achieve considerably higher throughput with much lower disk utilization. 

In this specific case, the customer requested the ability to throttle the number of concurrent running transactions (mostly single statement selects) without limiting the number of concurrent connections. Specifically they would rather reject the new requests rather than having all the requests be slow.  They are also unable to limit the number of idle connections because they are from a relatively small number of connections each from a large number of nodes.

I believe the impact is something similar to "Max Transaction Limit" in mysql: https://dev.mysql.com/blog-archive/the-new-mysql-thread-pool/ . For some reason it is really hard to find much more information on how this works.

I think we should take a multi-step approach here:
1) Create a test which replicates this behavior (throughput decreases significantly as concurrency increases). 
2) Add a new setting that allows limiting the number of concurrent running transactions to a specific limit - a request to start a new transaction will either fail or block if this limit is exceeded. By default the limit could be "infinity" to not impact existing customers.
3) Auto-tune the new setting using AC to reduce runnable goroutines due to SQL connections. 

Ideally we could generate a graph similar to their posting where we see a drastic decrease in the throughput of the system as the number of concurrent connections increases. I'm not sure if the current reproduction did this.

**Comment by rafiss** [comment] 2023-12-06 18:33
Here's another internal thread discussing a customer test where this kind of behavior was observed again: https://cockroachlabs.slack.com/archives/C01C1HGC46Q/p1701882981589619?thread_ts=1701800563.796959&cid=C01C1HGC46Q

Some interesting qualities of this workload:
- Every SELECT is returning more data
- queries are on secondary indexes and have to do an index join
- number of queries per replica climbs.
- They were running 512 connections per node, (16 total nodes)- things seemed to slow down a lot when those became saturated and # of open transactions hit 5k

**Comment by rafiss** [comment] 2024-01-16 19:28
also see this internal issue: https://cockroachlabs.atlassian.net/browse/CRDB-31584

**Comment by jonstjohn** [comment] 2024-01-23 22:23
I believe the idea is to be able to achieve the same throughput and latency regardless of whether there are 1k connections / active queries or 10k connections / active queries.

So, if I have a cluster that is capable of doing 50k QPS < 30ms latency with 1k connections / active queries, the idea is to be able to maintain that 50k QPS < 30ms latency with 10k connections / active queries. It seems like the only way that could be possible would be to error / reject the additional 9k queries. Perhaps this is where the idea of a cap in active queries came from.

I agree that it doesn't seem like a generalizable solution.

**Comment by sumeerbhola** [comment] 2024-01-25 21:25
> So, if I have a cluster that is capable of doing 50k QPS < 30ms latency with 1k connections / active queries, the idea is to be able to maintain that 50k QPS < 30ms latency with 10k connections / active queries. It seems like the only way that could be possible would be to error / reject the additional 9k queries.

The throughput goal is a reasonable expectation, and without a reproduction (which we can run CPU profiles on), we can only speculate on solutions. But first we need to temper the latency goals -- e.g. is the throughout dropping because the workload did not have enough concurrency to maintain throughput under 100ms latency? There will be a latency increase, and first we need to see if throughput drops even under high concurrency of the workload (and solve that).

**Comment by sean-** [comment] 2024-03-03 19:43
Outright rejecting queries without a "waiting room" is a suboptimal experience for application developers as well as the end users of these types of tunables.  Nodes in an overflow state need to have their queries queued for a duration before being rejected.  See also [TREQ-88](https://cockroachlabs.atlassian.net/browse/TREQ-88?focusedCommentId=213318&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-213318) for additional discussion about this problem and an alternate proposal.

**Comment by rimadeodhar** [comment] 2024-03-06 21:45
The simplest solution outlined here has been implemented in https://github.com/cockroachdb/cockroach/pull/118781. We'll review [TREQ-88](https://cockroachlabs.atlassian.net/browse/TREQ-88?focusedCommentId=213318&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-213318) for potential enhancements to this solution. Closing this one out as completed.

**Closed by rimadeodhar** 2024-03-06 21:45 UTC
Labels: C-enhancement, O-support, A-sql-execution, A-sql-executor, A-admission-control, T-sql-foundations, P-3

**Comment by andrewbaptist** [comment] 2024-03-06 22:21
To address some of the concerns from @sean-  and @sumeerbhola . Specifically the issue has to do with how P99 latency is impacted as the number of active connections on the system grows. If our system was "perfect" there would be a linear relationship between those two once we hit the maximum QPS that we can support.

Assume a cluster that has a max QPS of 20K and there is no client timeout set on requests. Also assume the client is creating requests independent of how long it takes us to finish each request.

Ideal world
```
<10K QPS - P99 = 10ms
15K QPS - P99 = 10ms
19.9K QPS - P99 - 10ms
20.1K QPS - P99 - Infinity, execute 20K QPS but the queue keeps growing
```

In reality it looks like the following:
```
<10K QPS - P99 = 10ms
15K QPS - P99 = 100ms
19.9K QPS - P99 - 2s
20.1K QPS - P99 - Infinity, executes ~10K QPS - we build the number of active queries and we start throttling in a non-optimal way as the number of goroutines build.
```

I previously created a test to demonstrate the issue here: #90006 and we have an open issue #89142 that describes the problem. We can retest this with server.max_open_transactions_per_gateway set to something like 200. This will likely demonstrate how the system behaves with a cap. With the right queueing it will avoid hitting AC and the nodes won't crash.
