### ISSUE TITLE
The cockroach.exe does not run under Windows 10

### ISSUE THREAD

**Issue by AnyCPU** [cockroachdb/cockroach#16839] opened 2017-07-02 14:41 UTC
Cockroachdb v.1.0.2
OS: Windows 10 Pro, version 1703 (OS Build 15063.413)

What did I do?
I have run `.\cockroach.exe version`

Event Viewer info
>Version=1
EventType=APPCRASH
EventTime=131434796394835101
ReportType=2
Consent=1
UploadTime=131434796402727739
ReportStatus=97
ReportIdentifier=eba28dce-088e-4287-8bf7-19ba48ae1036
IntegratorReportIdentifier=fbe199fe-dba0-4812-99d1-fc12575d2871
Wow64Host=34404
NsAppName=cockroach.exe
AppSessionGuid=0000358c-0010-0010-79a2-163e40f3d201
TargetAppId=W:00060352bab5806efee0f996bd59f908712b0000ffff!0000c5aa9b94dc4be194557914404d282d55c903c7df!cockroach.exe
TargetAppVer=2017//06//15:13:04:02!239d33e!cockroach.exe
BootId=4294967295
TargetAsId=32408
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=cockroach.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=594285c2
Sig[3].Name=Fault Module Name
Sig[3].Value=cockroach.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=594285c2
Sig[6].Name=Exception Code
Sig[6].Value=c000001d
Sig[7].Name=Exception Offset
Sig[7].Value=0000000001cedba2
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.15063.2.0.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=674f
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=674f8b37e59c2953e2af903051ee3186
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=ec19
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=ec19bf10ebda15e232a3311ee81825f9
UI[2]=D:\c\cockroach.exe
UI[3]=cockroach.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=D:\c\cockroach.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\System32\KERNEL32.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[4]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[5]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[6]=C:\WINDOWS\System32\USER32.dll
LoadedModule[7]=C:\WINDOWS\System32\win32u.dll
LoadedModule[8]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[9]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[10]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[11]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[12]=C:\WINDOWS\System32\WS2_32.dll
LoadedModule[13]=C:\WINDOWS\System32\sechost.dll
LoadedModule[14]=C:\WINDOWS\SYSTEM32\WINMM.dll
LoadedModule[15]=C:\WINDOWS\SYSTEM32\winmmbase.dll
LoadedModule[16]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[17]=C:\WINDOWS\System32\IMM32.DLL
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=cockroach.exe
AppPath=D:\c\cockroach.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=ACAB83112F30C1D8DCBA042877C26A55
MetadataHash=-2030111959

and

>Faulting application name: cockroach.exe, version: 0.0.0.0, time stamp: 0x594285c2
Faulting module name: cockroach.exe, version: 0.0.0.0, time stamp: 0x594285c2
Exception code: 0xc000001d
Fault offset: 0x0000000001cedba2
Faulting process id: 0x358c
Faulting application start time: 0x01d2f3403e16a279
Faulting application path: D:\c\cockroach.exe
Faulting module path: D:\c\cockroach.exe
Report Id: fbe199fe-dba0-4812-99d1-fc12575d2871
Faulting package full name: 
Faulting package-relative application ID:

**Comment by bdarnell** [comment] 2017-07-02 18:03
Are you perhaps running on a 32-bit version of Windows? (There's a lot of `system32` in that report; I don't know whether that means 32-bit or if it's just names that can't be changed for historical reasons) CockroachDB requires a 64-bit platform. 

Or maybe this is the windows version of the SSE4.2 issue (#15589)? What model of CPU are you using?

**Comment by AnyCPU** [comment] 2017-07-02 21:03
@bdarnell It is just MS' naming.
Installed Windows is a 64-bit OS.
CPU is AMD Phenom(tm) II X6 1055T. It does not have the SSE4.2.
I guess I have to try building sources.

**Comment by bdarnell** [comment] 2017-07-03 19:49
OK, closing this as a duplicate of #15589, then.

**Closed by bdarnell** 2017-07-03 19:49 UTC
