### ISSUE TITLE
Query with subselect against the same table as column returns 0 if an aggregation is used.

### ISSUE THREAD

**Issue by iluminae** [cockroachdb/cockroach#59734] opened 2021-02-02 23:37 UTC
**Describe the problem**
using the k3s-io/kine project to use kubernetes backed by cockroachdb I am getting the errors: `Error from server: illegal resource version from storage: 0` from kubernetes clients. As it turns out, this comes down to odd query behavior where a field in a SELECT that is populated by a SELECT against the same table if a aggregation is used on the parent query.

filed with kine as https://github.com/k3s-io/kine/issues/74

**To Reproduce**
I do not know if the issue is related to my dataset or not, but seems rather reproducible with the query that is made from kine.

1. Set up CockroachDB cluster 
2. Start up k3s pointing at cockroachdb
```
K3S_DATASTORE_ENDPOINT=postgres://user:pass@myhost:26257/mydb?sslmode=require k3s server
```
3. This is where I get lost a bit, I have had this system running well for over a month and this is a new issue after an attempted upgrade (and reversal) to crdb version v20.2.4

The SQL that is running is very large but I have distilled it down to the following example:
```sql
SELECT
    ( SELECT MAX(rkv.id) AS id FROM kine AS rkv ),
    kv.name,
    MAX(kv.id) AS theid
FROM kine AS kv
WHERE kv.deleted = 0
AND kv.name like '/registry/deployments/kube-system/%'
GROUP BY kv.name;
```
which results with:
```
     id    |                           name                           |  theid
-----------+----------------------------------------------------------+-----------
  48319912 | /registry/deployments/kube-system/coredns                | 36707654
         0 | /registry/deployments/kube-system/local-path-provisioner | 48300495
  48319912 | /registry/deployments/kube-system/metrics-server         | 36707040
         0 | /registry/deployments/kube-system/traefik                | 36707269
```
Note that the result of the subselect:
1) is run against the same table
2) results in a scalar value

If, however, the aggregation is removed from the parent query:
```sql
SELECT
    ( SELECT MAX(rkv.id) AS id FROM kine AS rkv ),
    kv.name
FROM kine AS kv
WHERE kv.deleted = 0
AND kv.name like '/registry/deployments/kube-system/%'
GROUP BY kv.name;
```
which results with:
```
     id    |                           name
-----------+-----------------------------------------------------------
  48325996 | /registry/deployments/kube-system/coredns
  48325996 | /registry/deployments/kube-system/local-path-provisioner
  48325996 | /registry/deployments/kube-system/metrics-server
  48325996 | /registry/deployments/kube-system/traefik
```

**Expected behavior**
I expect the first column to all be the same number in the example query.

**Environment:**
 - CockroachDB version: v20.2.3 (3 servers)
 - Server OS: kubernetes (docker amd64)
 - Client app: `cockroach sql` and `k3s`

**Additional context**
With this query oddity, half of the commands issued to the kubernetes server will fail all the way back to the client.

I also have tried:
* restoring a backup taken a week before the attempted upgrade, and the error was the same on that restored table.
* copying all the data from the live table into a new table and performing the query there.

Let me know what troubleshooting steps you would recommend. I may try to bring up a fresh cluster and load the backup into it to test that.

**Comment by iluminae** [comment] 2021-02-03 00:45
I have continued looking at this and performed the following:
* spin down cluster
* spin up cluster with fresh state (v20.2.4)
* `cockroach init`
* `restore from 'gs://...'`
* run the sql from above

and now it works. The same queries that were returning oddly before are now returning correctly. Notably, I had already tried restoring the database before to no avail (using the existing storage directory though).  So, it _seems_ there may be a bug in pebble that I had triggered.

Is there anything I can get to help identify the issue? I will hold on to the old state directories for a few days just in case.

**Comment by rytaft** [comment] 2021-05-03 19:59
Hello @iluminae, so sorry for the delay; this got buried. Are you still able to reproduce this issue? Very much appreciate your help here.

**Comment by iluminae** [comment] 2021-05-04 21:35
I still have the directory with the tablets that were misbehaving, I will try to copy them off and get them running with a crdb in docker or something and make sure it still reproduces.

**Comment by rytaft** [comment] 2021-05-05 00:14
Great! Thank you!

**Comment by rytaft** [comment] 2021-05-19 20:12
Hi @iluminae, any update on whether you were able to reproduce this issue?

**Comment by iluminae** [comment] 2021-05-20 02:24
@rytaft sorry for the 2 weeks of silence there - yes I can still reproduce this with the backups I took. _but only on v20.x_. When I try with the same directories and v21.1.0 the query returns correctly.

soo... good job guys, you fixed it.

Do you need anything from my reproduction in v20.2.3? I suppose you will since that version is supported for another year or so.

**Comment by rytaft** [comment] 2021-05-20 14:23
Hi @iluminae,

Thanks so much for looking into this! Yes, we do want to fix the issue on the 20.2 branch, so any info you can give me about how to reproduce it would be much appreciated. Perhaps to start you could try running `EXPLAIN ANALYZE (DEBUG)` with the problematic query as well as the one that works correctly on both 20.2.x and 21.1.0, and attach the resulting zip files. If the data is sensitive I can also provide a way for you to send the files privately and securely -- just let me know.

If I understand your earlier comments correctly, it also sounds like loading the same dataset onto a new cluster with 20.2.4 did not experience this issue, right? I wonder if there was some data corruption in one of the indexes (as you mentioned this could be a pebble bug, but more likely an issue higher up in the stack). If that's the case I may need to pull in some engineers from other teams.

Thanks again for your help!

**Comment by iluminae** [comment] 2021-05-25 22:24
yea maybe I can do that tonight - I have to kinda do a lot to set up the test environment (running 3 crdb in the docker vm on your laptop is tough!)

I am not sure how much granular data is in the zip file but there is potential for k8s passwords to be in the raw values, so if you have a more private place to put them that would be fine.

**Comment by rytaft** [comment] 2021-05-28 22:43
Ok thanks, please let me know if you manage to get to it this weekend, and I'll figure out how to get a secure channel for you to send the files.

**Comment by rytaft** [comment] 2021-06-02 17:36
Hi @iluminae, you can send data securely by opening a support ticket here: https://support.cockroachlabs.com/hc/en-us. If you go that route, please mention my name and GitHub issue #59734 when you open the ticket so our support team knows where to direct it.

Alternatively, it would be great if you can find some minimal reproduction steps so I can reproduce the issue myself. I am trying to reproduce it based on what you included in the issue description, but it's quite difficult without more info about which specific commands you ran to create the dataset in CockroachDB. If possible, please send very specific reproduction steps or a minimal dataset that reproduces the issue. Thank you!

**Comment by rytaft** [comment] 2021-08-30 12:37
I'm going to close this since it seems to be not reproducible. Please feel free to reopen if you have detailed reproduction steps we can follow. Thank you!

**Closed by rytaft** 2021-08-30 12:37 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries
