### ISSUE TITLE
sql: ALTER TABLE kills cluster

### ISSUE THREAD

**Issue by mattiasmak** [cockroachdb/cockroach#15026] opened 2017-04-18 09:09 UTC
```
I170418 08:56:38.297063 1 util/log/clog.go:1007  [config] file created at: 2017/04/18 08:56:38
I170418 08:56:38.297063 1 util/log/clog.go:1007  [config] running on machine: RO-DB1
I170418 08:56:38.297063 1 util/log/clog.go:1007  [config] binary: CockroachDB CCL beta-20170413-dirty (linux amd64, built 2017/04/13 21:06:17, go1.8.1)
I170418 08:56:38.297063 1 util/log/clog.go:1007  [config] arguments: [cockroach start --ca-cert=certs/ca.cert --cert=certs/DB1.cert --key=certs/DB1.key --advertise-host=10.135.68.54 --logtostderr]
```

I Altered a table with:
`ALTER TABLE raw_visits ADD COLUMN max_duration INT NULL;`

Then after a few minutes of working on the query the nodes starts to die one after another. And I can't start any of the nodes again.

cockroach start --background --ca-cert=certs/ca.cert --cert=certs/DB1.cert --key=certs/DB1.key --advertise-host=10.135.68.54 --logtostderr

After a while it ends with: 

```
time limit reached, initiating hard shutdown
Error: time limit reached, initiating hard shutdown
Failed running "start"
```

This is a piece of the output before it fails:

```
I170418 08:56:38.296978 1 cli/start.go:390  CockroachDB CCL beta-20170413-dirty (linux amd64, built 2017/04/13 21:06:17, go1.8.1)
I170418 08:56:38.398709 24 cli/start.go:427  starting cockroach node
I170418 08:56:38.417363 24 storage/engine/rocksdb.go:379  opening rocksdb instance at "/root/cockroach-data"
I170418 08:56:38.665371 24 server/config.go:403  1 storage engine initialized
I170418 08:56:38.666939 24 server/server.go:651  [n?] sleeping for 242.845307ms to guarantee HLC monotonicity
E170418 08:56:38.692690 7 server.go:2751  http: TLS handshake error from 93.182.128.2:57603: EOF
E170418 08:56:38.700658 43 server.go:2751  http: TLS handshake error from 93.182.128.2:50993: EOF
W170418 08:56:39.242554 73 storage/store.go:1343  [n1,s1,r2/5:/Table/{0-11},@c4209d6f00] could not gossip system config: [NotLeaseHolderError] range 2: replica {1 1 5} not lease holder; lease holder unknown
I170418 08:56:39.242805 24 storage/store.go:1256  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170418 08:56:39.244686 24 server/node.go:456  [n1] initialized store [n1,s1]: {Capacity:20749852672 Available:17882222592 RangeCount:195 LeaseCount:0}
I170418 08:56:39.244959 24 server/node.go:347  [n1] node ID 1 initialized
I170418 08:56:39.245340 24 gossip/gossip.go:307  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"10.135.68.54:26257" > attrs:<> locality:<>
I170418 08:56:39.245795 24 storage/stores.go:296  [n1] read 2 node addresses from persistent storage
I170418 08:56:39.246384 24 server/node.go:606  [n1] connecting to gossip network to verify cluster ID...
I170418 08:56:39.246531 24 server/node.go:631  [n1] node connected via gossip and verified as part of cluster "c4fc09cd-f14d-4b1d-80c8-8671325a595c"
I170418 08:56:39.246649 24 server/node.go:394  [n1] node=1: started with [[]=/root/cockroach-data] engine(s) and attributes []
I170418 08:56:39.254402 24 sql/executor.go:326  [n1] creating distSQLPlanner with address {tcp 10.135.68.54:26257}
I170418 08:56:39.277512 24 server/server.go:705  [n1] starting https server at RO-DB1:8080
I170418 08:56:39.277577 24 server/server.go:706  [n1] starting grpc/postgres server at RO-DB1:26257
I170418 08:56:39.277614 24 server/server.go:707  [n1] advertising CockroachDB node at 10.135.68.54:26257
W170418 08:56:39.300892 73 storage/store.go:1343  [n1,s1,r2/5:/Table/{0-11},@c4209d6f00] could not gossip system config: [NotLeaseHolderError] range 2: replica {1 1 5} not lease holder; lease holder unknown
W170418 08:56:39.398135 73 storage/store.go:1343  [n1,s1,r2/5:/Table/{0-11},@c4209d6f00] could not gossip system config: [NotLeaseHolderError] range 2: replica {1 1 5} not lease holder; lease holder unknown
I170418 08:56:39.422166 137 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.135.68.94:26257: getsockopt: connection refused"; Reconnecting to {10.135.68.94:26257 <nil>}
W170418 08:56:39.422361 135 gossip/client.go:125  [n1] failed to start gossip client to 10.135.68.94:26257: rpc error: code = Unavailable desc = grpc: the connection is unavailable
W170418 08:56:39.590493 73 storage/store.go:1343  [n1,s1,r2/5:/Table/{0-11},@c4209d6f00] could not gossip system config: [NotLeaseHolderError] range 2: replica {1 1 5} not lease holder; lease holder unknown
W170418 08:56:39.961670 73 storage/store.go:1343  [n1,s1,r2/5:/Table/{0-11},@c4209d6f00] could not gossip system config: [NotLeaseHolderError] range 2: replica {1 1 5} not lease holder; lease holder unknown
I170418 08:56:40.426613 137 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.135.68.94:26257: getsockopt: connection refused"; Reconnecting to {10.135.68.94:26257 <nil>}
```

**Comment by vivekmenezes** [comment] 2017-04-18 12:21
Thanks for reporting this issue.

What is the size of this cluster? Is it a single node cluster?

Can you send us the output of:

```SHOW CREATE TABLE raw_visits```

**Comment by mattiasmak** [comment] 2017-04-18 13:53
3 nodes.  44.826 rows (Much less than I expected)

```
CREATE TABLE raw_visits (
	id INT NOT NULL DEFAULT unique_rowid(),
	venue_id INT NOT NULL,
	device_id STRING NOT NULL,
	first_signal TIMESTAMP WITH TIME ZONE NULL,
	last_signal TIMESTAMP WITH TIME ZONE NULL,
	duration_signal INTERVAL NULL,
	signals_per_hour INT NULL,
	avg_distance INT NULL,
	visitortype INT NULL,
	durationtype INT NULL,
	dayssincelastvisit INT NULL,
	visitweight INT NULL,
	min_distance INT NULL DEFAULT 0,
	CONSTRAINT "primary" PRIMARY KEY (id ASC),
	CONSTRAINT fk_venue_id_ref_venues FOREIGN KEY (venue_id, device_id, first_signal, duration_signal) REFERENCES venues (id),
	CONSTRAINT fk_device_id_ref_devices FOREIGN KEY (device_id) REFERENCES devices (id),
	FAMILY "primary" (id, venue_id, device_id, first_signal, last_signal, duration_signal, signals_per_hour, avg_distance, visitortype, durationtype, dayssincelastvisit, visitweight, min_distance)
)
```

**Comment by mattiasmak** [comment] 2017-04-18 18:09
I finally got all three nodes back up after a bit of struggle. The latency seems to be much worse now than before. P99 is around 800ms and P50 is around 250. I thing this is not good at all. Even though it's 99 inserts...

I can give you access to the admin console if there's something there. This is actually a soon-production-ready system with a bit of load already.

**Comment by mattiasmak** [comment] 2017-04-18 18:15
```
Schema Change Finished: Schema Change Completed: Schema change with ID 1 was completed.	6 hours ago
Node Rejoined: Node 1 rejoined the cluster	6 hours ago
Node Rejoined: Node 3 rejoined the cluster	6 hours ago
Node Rejoined: Node 2 rejoined the cluster	6 hours ago
Schema Change: User client began a schema change to alter table raw_visits with ID 1	10 hours ago
```

**Comment by vivekmenezes** [comment] 2017-04-19 14:03
looks like because some of your nodes were down the schema change took a lot of time to complete. In fact it looks like it completed as soon as the nodes came back up. The slowness of the schema change looks like this issue:

https://github.com/cockroachdb/cockroach/issues/13655

But why your nodes didn't come back up for a long time is still a mystery.

Can you attached the cockroach node logs to this issue? Thanks

**Comment by mattiasmak** [comment] 2017-04-20 10:00
I had to do some crazy stuff to get the nodes up and running. I tried many things until one finally was up, then the rest could join that one. 

what logs do you refer to? Not the one on top of this issue?

**Comment by mattiasmak** [comment] 2017-04-20 13:52
The cluster behaved very odd since this. Even before the latency was very high. I created a new cluster but insecure this time. I restored all data and pointed the apps to the new cluster. Now the P50 latency is around 3.7ms. That's an improvement of 100 times.

**Comment by vivekmenezes** [comment] 2017-04-25 02:13
this might be related to #15311

**Comment by mattiasmak** [comment] 2017-05-02 10:05
We have another issue. After running a cluster for 10 days two nodes died during weekend. It's a struggle to get them up again. Lots of errors like below:

My question is: Should I make this another issue? Is this us doing things wrong? How do we debug this? 

We really love Cockroach, but there is  a lot of things that goes wrong for us at the moment. 


```
I170502 10:01:52.180016 76 storage/replica_raftstorage.go:413  [replicate,n3,s3,r29/3:/System/tsd/cr.node.sys.cpu.s…,@c4204ffb00] generated preemptive snapshot 40410405 at index 53
I170502 10:01:52.183406 76 storage/replicate_queue.go:231  [replicate,n3,s3,r29/3:/System/tsd/cr.node.sys.cpu.s…,@c4204ffb00] snapshot failed: r29: remote declined snapshot: reservation rejected
```
AND 

```
I170502 09:59:21.546561 31 server/status/runtime.go:227  [n1] runtime stats: 99 MiB RSS, 209 goroutines, 17 MiB/8.3 MiB/32 MiB GO alloc/idle/total, 13 MiB/19 MiB CGO alloc/total, 68.10cgo/sec, 0.01/0.00 %(u/s)time, 0.00 %gc (0x)
I170502 09:59:22.121205 252 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.135.15.39:26257: getsockopt: connection refused"; Reconnecting to {10.135.15.39:26257 <nil>}
E170502 09:59:22.704451 36 gossip/gossip.go:972  [n1] unable to get address for node 3: unable to look up descriptor for node 3
E170502 09:59:22.704851 36 gossip/gossip.go:972  [n1] unable to get address for node 3: unable to look up descriptor for node 3
I170502 09:59:22.955127 252 vendor/google.golang.org/grpc/clientconn.go:806  grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp 10.135.15.39:26257: getsockopt: connection refused"; Reconnecting to {10.135.15.39:26257 <nil>}
```

**Comment by petermattis** [comment] 2017-05-02 12:45
@mattiasmak Sorry to hear you're having trouble. Let's see what we can do about that. I've created a new issue #15591 as this problem is distinct from the ALTER TABLE issue.

**Comment by vivekmenezes** [comment] 2017-08-30 15:30
@mattiasmak is this still an issue? I know we didn't do much here in terms of figuring out what the problem is, but time has moved on and many changes have been baked into the system. I'm wondering if you can try this out and refresh this issue/close this issue with your findings. Thanks!

**Comment by vivekmenezes** [comment] 2018-04-23 17:33
Closing this issue. Please do reopen if this is still an issue. Thanks!

**Closed by vivekmenezes** 2018-04-23 17:33 UTC
Labels: community-questions
