### ISSUE TITLE
Test failure in CI build 1909

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#845] opened 2015-04-29 18:03 UTC
The following test appears to have failed:

[#1909](https://circleci.com/gh/cockroachdb/cockroach/1909):

```
I0429 17:58:20.808996     259 multiraft.go:693] HardState updated: {Term:6 Vote:4294967297 Commit:41 XXX_unrecognized:[]}
I0429 17:58:20.809139     259 multiraft.go:696] New Entry[0]: 6/40 EntryNormal 0000000000000000036529231f9da003: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809278     259 multiraft.go:696] New Entry[1]: 6/41 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809412     259 multiraft.go:699] Committed Entry[0]: 6/40 EntryNormal 0000000000000000036529231f9da003: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809550     259 multiraft.go:699] Committed Entry[1]: 6/41 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 30s

goroutine 3072 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x107a4a0, 0x1516320, 0xa1, 0xa1, 0xc207ffb901)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:487 +0x90c
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	30.017s
=== RUN TestBatchBasics
I0429 17:59:00.495384     361 rocksdb.go:88] opening in-memory rocksdb instance
I0429 17:59:00.496556     361 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0429 17:59:00.497481     361 rocksdb.go:88] opening in-memory rocksdb instance
I0429 17:59:00.497807     361 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0429 17:59:00.498722     361 rocksdb.go:88] opening in-memory rocksdb instance
I0429 17:58:20.808996     259 multiraft.go:693] HardState updated: {Term:6 Vote:4294967297 Commit:41 XXX_unrecognized:[]}
I0429 17:58:20.809139     259 multiraft.go:696] New Entry[0]: 6/40 EntryNormal 0000000000000000036529231f9da003: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809278     259 multiraft.go:696] New Entry[1]: 6/41 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809412     259 multiraft.go:699] Committed Entry[0]: 6/40 EntryNormal 0000000000000000036529231f9da003: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
I0429 17:58:20.809550     259 multiraft.go:699] Committed Entry[1]: 6/41 EntryNormal 00000000000000005359ab8439abb31b: raft_id:1 origin_node_id:4294967297 cmd:<internal_resolve_intent:<header:<timestamp:<wall_time:0 logical:52 > cmd_id:<wall_time:0 random:0 > key:"\00
panic: test timed out after 30s

goroutine 3072 [running]:
testing.func·008()
	/usr/src/go/src/testing/testing.go:681 +0x12f
created by time.goFunc
	/usr/src/go/src/time/sleep.go:129 +0x4b

goroutine 1 [chan receive]:
testing.RunTests(0x107a4a0, 0x1516320, 0xa1, 0xa1, 0xc207ffb901)
	/usr/src/go/src/testing/testing.go:556 +0xad6
--
	/go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:487 +0x90c
github.com/cockroachdb/cockroach/util.func·005()
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:73 +0x51
created by github.com/cockroachdb/cockroach/util.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stopper.go:74 +0xe3
FAIL	github.com/cockroachdb/cockroach/storage	30.017s
=== RUN TestBatchBasics
I0429 17:59:00.495384     361 rocksdb.go:88] opening in-memory rocksdb instance
I0429 17:59:00.496556     361 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchBasics (0.00s)
=== RUN TestBatchGet
I0429 17:59:00.497481     361 rocksdb.go:88] opening in-memory rocksdb instance
I0429 17:59:00.497807     361 rocksdb.go:112] closing rocksdb instance at ""
--- PASS: TestBatchGet (0.00s)
=== RUN TestBatchMerge
I0429 17:59:00.498722     361 rocksdb.go:88] opening in-memory rocksdb instance

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-04-29 18:05
Duplicate of #838

**Closed by bdarnell** 2015-04-29 18:05 UTC
Labels: test-failure
