### ISSUE TITLE
circleci: failed tests (15844): TestDockerJava 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5858] opened 2016-04-05 00:09 UTC
The following test appears to have failed:

[#15844](https://circleci.com/gh/cockroachdb/cockroach/15844):

```
I160405 00:06:05.389963 acceptance/replication_test.go:66  found 1 replicas
I160405 00:06:05.490693 acceptance/cluster/localcluster.go:649  stopping
I160405 00:06:05.490956 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160405 00:06:05.490974 acceptance/cluster/localcluster.go:570  events monitor exits
I160405 00:06:05.492388 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container ed77a437f24fc632f931f931e283be41671086a58ed5507efadd7f682a6b5f0d: Container ed77a437f24fc632f931f931e283be41671086a58ed5507efadd7f682a6b5f0d is not running
--- FAIL: TestDockerJava (19.10s)
	testing.go:113: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 1
=== RUN   TestDockerNodeJS
I160405 00:06:07.412891 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160405 00:06:07.414508 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160405 00:06:07.983675 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.948877516
I160405 00:06:08.121158 acceptance/cluster/localcluster.go:532  events monitor starts
I160405 00:06:08.405878 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32846
  trace:     https://127.0.0.1:32846/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-06 14:27
Duplicate of #5879. `roach{1,2}` failed to connect to the gossip network.

**Closed by petermattis** 2016-04-06 14:27 UTC
Labels: Robot, test-failure
