### ISSUE TITLE
tests: verify on-the-wire compatibility

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5678] opened 2016-03-29 17:47 UTC
Similar to the current `ReferenceVersion` tests that verify forwards and backwards compatibility with on-disk data between a tested version and some well-known reference version, we should probably also test on-the-wire network compatibility.

Specifically, we want to make sure that a tested binary can join a cluster running the reference version and vice-versa, that it can replicate ranges back and forth, send and receive requests, etc (in the future we probably also want to include participate in a distsql query execution both as the coordinator and as a worker).

**Comment by a6802739** [comment] 2016-09-08 02:50
@dt, I have time to fix this now. I wonder if you mean just add test case about addinf new node with different binary version to the cluster?

**Comment by spencerkimball** [comment] 2017-03-29 16:48
@dt Do we have aspirations of this making the 1.0 release? Could you re-add the 1.0 milestone **and assign** if so?

**Comment by dt** [comment] 2017-03-29 17:11
We can probably fold this in to our production cluster testing more easily (by just rolling a canary before the fleet for non-STW upgrades) more easily than adding automated tests.

**Comment by bdarnell** [comment] 2017-03-29 18:40
Our production clusters will let us test small jumps, but post-1.0 we should set up the infrastructure (similar to the reference version test we have now for on-disk stuff) to verify that a 1.0 cluster can be upgraded to 1.1.

**Comment by cuongdo** [comment] 2017-08-22 20:57
@tschottdorf seems related to your current work. if not, please feel free to unassign and move milestone

**Comment by tschottdorf** [comment] 2017-08-31 00:31
actually, closing as a dupe of #15851.

**Closed by tschottdorf** 2017-08-31 00:31 UTC
Labels: easy, enhancement, helpwanted
