### ISSUE TITLE
kv: bound the size of in-flight write tracking in txnPipeliner

### ISSUE THREAD

**Issue by manigandham** [cockroachdb/cockroach#32522] opened 2018-11-21 07:51 UTC
We have a table with a 26M rows and 20 columns. Issuing a delete, for roughly half the rows in the table, crashes the node:

`DELETE FROM accounts WHERE datasetversion = 4;`

Limiting the deletes works, I tried up to 500k without issue.

`DELETE FROM accounts WHERE datasetversion = 4 LIMIT 500000;`

3 nodes x n1-standard-2 (2 cpu / 7.5gb) with local nvme SSD on GCE with 25% cache/mem settings, 3x RF, this is the only table in the database.

Tried it again with a single node with 4 cpu / 15gb, same result

![image](https://user-images.githubusercontent.com/457226/48826328-d0a3d600-ed1e-11e8-9980-ec44ac58d9e9.png)

**To Reproduce**

Start single or multi-node cluster. Run `import` of 6gb CSV file containing 26M rows. Run 'DELETE' command filtering on a single column with 2 possible values, which should remove about half of the data. The node connected to the client will slowly run up memory usage until it crashes.

**Expected behavior**
Delete around 12M out of 26M rows in table without crashing.

**Environment:**
 - CockroachDB version 2.1.1
 - Server OS: Ubuntu 18.04 LTS on GCE
 - Client app: psql client on separate vm

Debug output from 3 node cluster:
[debug.zip](https://github.com/cockroachdb/cockroach/files/2603971/debug.zip)

**Comment by tbg** [comment] 2018-11-21 11:48
Thanks @manigandham. As the node crashes, does it leave anything in `logs/heap_profiler`? We'd be interested in seeing these files if you have them. (They don't contain sensitive information).

**Comment by manigandham** [comment] 2018-11-21 12:02
Are you talking about the folder on the node? I already deleted the cluster but can run the process again...

**Comment by manigandham** [comment] 2018-11-21 12:04
It looks like the debug output contains that? Can you check the attached zip file and see if it's valid?

**Comment by tbg** [comment] 2018-11-21 12:04
Oh, I had missed that attached file. Apologies! Taking a look.

**Comment by tbg** [comment] 2018-11-21 12:08
@nvanbenschoten this looks like your wheelhouse. We don't unconditionally support large transactions, but the profile indicates something we need to fix regarding the txn pipeliner.



<img width="823" alt="image" src="https://user-images.githubusercontent.com/5076964/48840296-7b9fa880-ed8e-11e8-9b52-ce4a3c096eaf.png">

**Comment by jseldess** [comment] 2018-11-21 14:40
@tbg, @nvanbenschoten, back in v1.0, we had a [known limitation about truncating a large table](https://www.cockroachlabs.com/docs/v1.0/known-limitations.html#removing-all-rows-from-large-tables). But that was resolved, and we no longer have a stated limitation about large transactions. At the very end of a current limitation about [Write and update limits for a single statement](https://www.cockroachlabs.com/docs/stable/known-limitations.html#write-and-update-limits-for-a-single-statement), we say:

> Note that even though not directly restricted any more, large transactions can have performance implications on the cluster.

Given that large transactions can go beyond just impacting performance (and crash nodes, as in this case), should we create a separate known limitation about this? 

This might also be another sign that we need to revive the docs project to identify and publish "production limits" (nodes, dbs, tables, rows, transactions, etc.), even if they are just recommendations based on our current understanding.

**Comment by tbg** [comment] 2018-11-21 20:49
Large transactions are still a bad idea, though we weren't aware of them causing an outright memory blowup as seen here. My assumption right now is that this is a regression.

**Comment by manigandham** [comment] 2018-11-22 02:47
Another update: reading the table with a `SELECT COUNT(*)` with a filter on that column after deleting millions rows in smaller batches also crashes the node. From the documentation, is that due to scanning through tombstones?

Our expectation is that updates and queries will always complete, even if slow. Is this inaccurate? Will there be hard limits to data updates? And if so, how would we approach such large transactions?

**Comment by nvanbenschoten** [comment] 2018-11-26 19:58
The memory blowup in the txn pipeliner is due to two issues. The first is that the `kv.transaction.write_pipelining_max_batch_size` currently defaults to 0, which means that a key-value batch will be pipelined, regardless of the number of operations that it performs. This doesn't play well with `sql.max{Insert/Update/Upsert/Delete}BatchSize`, which breaks large implicit SQL txns into non-1PC kv txns. The intention was for these to never be pipelined, but they currently will be. This should be fixed by https://github.com/cockroachdb/cockroach/pull/32606.

The other issue is more general - we need to address this TODO:

https://github.com/cockroachdb/cockroach/blob/a7e13e8fdb1db2094e17c13d25215fb7b711313e/pkg/kv/txn_interceptor_pipeliner.go#L185-L187

I suspect that the first issue is the cause of almost all cases where this memory blows up, but we should have a hard memory bound here regardless.

> Another update: reading the table with a SELECT COUNT(*) with a filter on that column after deleting millions rows in smaller batches also crashes the node. From the documentation, is that due to scanning through tombstones?

This sounds like a different issue. Is it reproducible for you?

**Comment by manigandham** [comment] 2018-11-26 23:14
@nvanbenschoten 

Somewhat reproducible. After crashing from the delete query, I restart the node then do run the `SELECT COUNT(*) WHERE X = Y` which either crashes the node again or takes an extremely long time. Single bigger node seems to finish the query vs smaller cluster nodes.

Here's a screenshot of a 17 minute query time. Running the same exact query again takes 44 seconds.

![screenshot_1](https://user-images.githubusercontent.com/457226/49047854-9ce90600-f18d-11e8-9091-5a9914b154c6.png)

**Closed** 2019-02-26 16:20 UTC
Labels: A-sql-mutations, C-investigation, O-community, S-2-temp-unavailability
