### ISSUE TITLE
sql: try reusing existing renders in GROUP BY

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#10919] opened 2016-11-21 21:33 UTC
Found while working on #10799, suggested by @RaduBerinde: when GROUP BY is specified using a column ordinal (e.g. `GROUP BY 1`) we duplicate the rendered expression in the select node instead of reusing the existing render. This could be perhaps optimized.

**Comment by nvanbenschoten** [comment] 2016-11-22 03:34
Duplicate of #9173?

**Comment by knz** [comment] 2016-11-22 08:25
It's not really a dup but is the dual of that other issue for the groupNode.
I think that #9173 was really specific to sortNode.

**Comment by andy-kimball** [comment] 2018-08-25 02:16
I propose we close this as "won't fix", since it only applies to the heuristic planner (no extra render with cost-based optimizer).

**Comment by andy-kimball** [comment] 2018-08-25 07:13
In fact, I'll just go ahead and close it, and if anyone objects, they can reopen. : )

**Closed by andy-kimball** 2018-08-25 07:13 UTC
Labels: A-sql-planning, C-performance
