### ISSUE TITLE
sql/logictest: TestSqlLiteLogic test failed on 3node-tenant config

### ISSUE THREAD

**Issue by yuzefovich** [cockroachdb/cockroach#49625] opened 2020-05-28 02:58 UTC
In this [run](https://teamcity.cockroachdb.com/viewLog.html?buildId=1970598&buildTypeId=Cockroach_SqlLogicTests&tab=buildLog&branch_Cockroach_Nightlies=49333), the tests have passed on all configs except for `3node-tenant` which failed with
```
16866 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663434987-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"        --- FAIL: TestSqlLiteLogic/3node-tenant/slt_good_20.test (62.68s)\n"}^M
16867 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663442398-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"            logic.go:2204: \n"}^M
16868 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663453658-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                \n"}^M
16869 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.66346093-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3node      -tenant/slt_good_20.test","Output":"                /go/src/github.com/cockroachdb/sqllogictest/test/index/commute/10/slt_good_20.test:3463: SELECT pk FROM tab3 WHERE ((((((((col4       IN (33.89,9.44,68.6,75.65,35.32)))) AND col3 \u003c= 40 AND col0 \u003e 34 OR col3 \u003e= 30 AND (col3 \u003c 64 OR col4 \u003e 52.64 OR (((col0 BETWEEN 11 AND 54)) AND col3 \u0      03e= 37) AND col3 IN (78,86,27,77,55,40) AND col4 \u003c= 39.26 AND (col1 \u003e= 47.38 AND col4 \u003e= 84.84 AND col3 \u003e 16 AND col3 \u003e 13) OR col0 \u003e 60 OR col1 \u0      03e= 50.31) OR col4 \u003e= 70.37 AND col3 \u003c= 24) AND (col0 IN (SELECT col3 FROM tab3 WHERE (((col3 \u003c 66)))) OR (col0 = 44 AND col3 \u003e 74))))))\n"}^M
16870 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663482094-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                expected success, but found\n"}^M
16871 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663491528-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                (XX000) internal error: cannot overwrite [] /  (0.01000000103) with [ordering: +12] / [ordering: +12] (0.010000001)\n"}^M
16872 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663499291-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                memo.go:328: in SetBestProps()\n"}^M
16873 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663515788-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                DETAIL: stack trace:\n"}^M
16874 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663523303-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:328: SetBestProps()\n"}^M
16875 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.66353099-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3node      -tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:721: setLowestCostTree()\n"}^M
16876 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663538017-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16877 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663545008-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16878 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.66355189-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3node      -tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16879 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663558907-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16880 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663565677-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16881 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663578134-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16882 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663585849-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16883 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663592868-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16884 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663608865-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16885 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663616154-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16886 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.663622766-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3nod      e-tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
16887 [17:06:44] :› ›  [run] {"Time":"2020-05-27T13:06:43.66362968-04:00","Action":"output","Package":"github.com/cockroachdb/cockroach/pkg/sql/logictest","Test":"TestSqlLiteLogic/3node      -tenant/slt_good_20.test","Output":"                github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:707: setLowestCostTree()\n"}^M
...
```
I didn't try to reproduce it.

**Comment by asubiotto** [comment] 2020-06-02 08:24
Is this an optimizer issue?

**Comment by yuzefovich** [comment] 2020-06-02 13:52
Yes, it looks like an optimizer issue, but given it happened only on `3node-tenant` config, I thought you're the best person to take the first look.

**Comment by asubiotto** [comment] 2020-06-02 14:12
@RaduBerinde could you take a quick look/route?

**Comment by RaduBerinde** [comment] 2020-06-02 22:28
I isolated the query but cannot reproduce.. I have no idea how an "ordering" would show up anywhere with this query. I looked at the full memo for the query and there's nothing involving orderings.

**Comment by asubiotto** [comment] 2020-06-03 13:34
Hmm, looking at the code it looks like the `Memo` panics with this error. Maybe the recovery doesn't correctly associate the panic with the query that caused it?

**Comment by RaduBerinde** [comment] 2020-06-03 13:55
Not sure how it is possible, panics from opt are caught at the boundary of the opt layer and converted to assertion errors.

**Comment by asubiotto** [comment] 2020-06-04 09:54
Do you think there's anything else to do here? Happy to close if we can't repro, but maybe we could add more info if this happens again.

**Comment by RaduBerinde** [comment] 2020-06-04 14:19
Let's leave it open for a while in case it happens again.

**Comment by asubiotto** [comment] 2020-06-30 14:36
Closing as this hasn't happened in nearly a month.

**Closed by asubiotto** 2020-06-30 14:36 UTC
Labels: A-multitenancy, C-bug
