### ISSUE TITLE
circleci: failed tests (15917): TestClusterRecovery 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5884] opened 2016-04-06 03:02 UTC
The following test appears to have failed:

[#15917](https://circleci.com/gh/cockroachdb/cockroach/15917):

```
I160406 02:57:18.646637 acceptance/replication_test.go:66  found 2 replicas
I160406 02:57:18.747166 acceptance/cluster/localcluster.go:649  stopping
I160406 02:57:18.747352 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160406 02:57:18.747374 acceptance/cluster/localcluster.go:570  events monitor exits
I160406 02:57:18.749095 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container 64dc2db7b402a50fe93718ed8f757f0320f69c9d43a0ed1055ac12937877aa18: Container 64dc2db7b402a50fe93718ed8f757f0320f69c9d43a0ed1055ac12937877aa18 is not running
--- FAIL: TestClusterRecovery (18.88s)
	testing.go:113: acceptance/replication_test.go:72: condition failed to evaluate within 15s: expected 3 replicas, only found 2
=== RUN   TestNodeRestart
I160406 02:57:20.560465 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160406 02:57:20.562068 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160406 02:57:21.000914 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.010043939
I160406 02:57:21.076042 acceptance/cluster/localcluster.go:532  events monitor starts
I160406 02:57:21.344493 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32798
  trace:     https://127.0.0.1:32798/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by petermattis** [comment] 2016-04-06 14:26
Duplicate of #5879. `roach2` failed to connect to the gossip network.

**Closed by petermattis** 2016-04-06 14:26 UTC
Labels: Robot, test-failure
