### ISSUE TITLE
Test failure in CI build 7509

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#2532] opened 2015-09-16 19:29 UTC
The following test appears to have failed:

[#7509](https://circleci.com/gh/cockroachdb/cockroach/7509):

```
E0916 19:29:22.602110 992 storage/replica.go:954  error executing raft command: key range ""-"" outside of bounds of range ""-""
E0916 19:29:22.602320 992 storage/replica.go:954  error executing raft command: key range "\x00\x00\x00k\x00\x01rdsc"-"" outside of bounds of range ""-""
E0916 19:29:22.602524 992 storage/replica.go:954  error executing raft command: key range ""-"" outside of bounds of range ""-""
W0916 19:29:22.602564 992 multiraft/multiraft.go:912  aborting configuration change: key range ""-"" outside of bounds of range ""-""
W0916 19:29:22.602626 992 multiraft/multiraft.go:912  aborting configuration change: key range ""-"" outside of bounds of range ""-""
--- FAIL: TestRaftRemoveRace (1.98s)
	testing.go:151: storage/client_test.go:374: condition failed to evaluate within 1s: storage/client_test.go:370: range not found on store 2
=== RUN   TestStoreRangeRemoveDead
I0916 19:29:23.682987 992 multiraft/multiraft.go:446  node 100000001 starting
I0916 19:29:23.683088 992 storage/replica.go:1234  gossiping cluster id  from store 1, range 1
I0916 19:29:23.683243 992 raft/raft.go:406  group 1 100000001 became follower at term 5
I0916 19:29:23.683304 992 raft/raft.go:219  group 1 newRaft 100000001 [peers: [100000001], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I0916 19:29:23.683442 992 raft/raft.go:485  group 1 100000001 is starting a new election at term 5
I0916 19:29:23.683461 992 raft/raft.go:419  group 1 100000001 became candidate at term 6
I0916 19:29:23.683476 992 raft/raft.go:468  group 1 100000001 received vote from 100000001 at term 6
I0916 19:29:23.683508 992 raft/raft.go:447  group 1 100000001 became leader at term 6
--
c431766846057893.27          19:29:26.846124  466.191µs  ·sending RPC             kv/dist_sender.go:424

--- PASS: TestStoreRangeSystemSplits (0.33s)
=== RUN   Example_rebalancing
--- PASS: Example_rebalancing (0.18s)
FAIL
FAIL	github.com/cockroachdb/cockroach/storage	12.139s
=== RUN   TestBatchBasics
I0916 19:29:07.910602 968 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchBasics (0.00s)
=== RUN   TestBatchGet
I0916 19:29:07.911354 968 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchGet (0.00s)
=== RUN   TestBatchMerge
I0916 19:29:07.913350 968 storage/engine/rocksdb.go:122  closing in-memory rocksdb instance
--- PASS: TestBatchMerge (0.00s)
=== RUN   TestBatchProto

```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2015-09-16 19:38
Dupe of #1878

**Closed by bdarnell** 2015-09-16 19:38 UTC
Labels: test-failure
