### ISSUE TITLE
sql: Add support for TEMP tables

### ISSUE THREAD

**Issue by dt** [cockroachdb/cockroach#5807] opened 2016-04-01 18:00 UTC
Passing the modifier `TEMP` or `TEMPORARY` to CREATE TABLE would indicate the the table should be dropped when the session ends.

Like other DBs, using the unqualified table name for the remainder of the session would reference the temporary table -- an existing, non-temporary table of the same name would need to be accessed using a qualified name.

Postgres docs, for reference:

> TEMPORARY or TEMP
> If specified, the table is created as a temporary table. Temporary tables are automatically dropped at the end of a session, or optionally at the end of the current transaction (see ON COMMIT below). Existing permanent tables with the same name are not visible to the current session while the temporary table exists, unless they are referenced with schema-qualified names. Any indexes created on a temporary table are automatically temporary as well.
> 
> ...
> 
> Optionally, GLOBAL or LOCAL can be written before TEMPORARY or TEMP. This presently makes no difference in PostgreSQL and is deprecated; see Compatibility.

http://www.postgresql.org/docs/current/static/sql-createtable.html

**Comment by dt** [comment] 2016-04-01 19:08
From discussion in gitter with @bdarnell and @petermattis:

Where to actually store a temp table. 
Small temp tables might make sense to keep in-memory on the gateway (in the session), skipping replication/raft overhead/rocks.
Larger tables, or larger numbers of clients using temp tables against a single gateway, though will require storing on them !gateway. To remain resilient to non-gateway node death, those will still need to be replicated normally.

**Comment by petermattis** [comment] 2016-04-01 19:11
Storing the temp table in-memory on the gateway will add a wrinkle when we distribute SQL processing. The planner will have to know about the temporary table and arrange for JOINs against it to be done on the gateway node. Not insurmountable, but yet another consideration.

**Comment by dt** [comment] 2016-04-01 19:18
Yeah, my inclination is to start with the storing temp tables in regular, globally replicated tables in a special system, DB, and just intercept unqualified name resolution (plus add a heartbeat from the session to something that keeps them from being GCed), then consider added the special-case of gateway-local, in-memory tables later.

That said, if we wanted to leave room for the more performant, gateway-local version to be the default at a later time, we'd might want to artificially limit the size unless eg the `GLOBAL` modifier is used to prevent anyone relying on it in the mean time.

**Comment by alexlovescoding** [comment] 2016-05-12 17:35
I'm learning Go and I would like to do so by helping with this project.  Can I try to work on this issue?

**Comment by vivekmenezes** [comment] 2016-05-12 19:04
@alexlovescoding please do send us a PR for this issue. If you need any help you can ping this issue or hit us on gitter https://gitter.im/cockroachdb/cockroach

**Comment by tschottdorf** [comment] 2016-07-07 22:03
I'm untagging this as `easy` because I don't think it qualifies.

**Comment by jordanlewis** [comment] 2019-05-24 16:18
I've talked to a number of people about this feature recently. I think we should aim to implement temporary tables as ordinary tables that are automatically dropped at the end of the session, without thinking about any in-memory optimizations or anything like that.

I think for now we should ignore the `ON COMMIT` modifier, which produces transaction-scoped temporary tables.

There are a number of requirements.

1. Only the current session may observe the temporary table.
2. The temporary table must live in a namespace that is isolated from other sessions - other sessions must be able to create a temporary table of the same name as a temporary table in another session.
3. The temporary tables must be dropped at the end of a session.
4. Temporary tables may not reference permanent tables via foreign key relations. Likewise, permanent tables may not reference temporary tables via foreign key relations.
5. DistSQL flows on remote nodes must be able to observe the temporary tables for the session that initiated them.

I think this is very doable.

cc @rafiss as a potential project for you.

**Comment by petermattis** [comment] 2019-05-24 17:30
* Can the schema of a temporary table be altered? Can the zone config?
* Are temporary tables completely inaccessible from other sessions? This might follow from your point 2, but I can imagine a design which doesn't prohibit such access. For example, each session gets its own unique "schema" which only it can write to, but everyone can read from.
* Will temporary tables increase table ID / namespace churn and the size of the system config range? I think the answer is yes, and fixing this is the biggest obstacle I see.

**Comment by jordanlewis** [comment] 2019-05-30 14:21
> Can the schema of a temporary table be altered? Can the zone config?

I would imagine yes on both points, but just by accident. In this proposed design, temporary tables would simply be ordinary tables. I don't think it's important that we think about this too carefully.

> Are temporary tables completely inaccessible from other sessions? This might follow from your point 2, but I can imagine a design which doesn't prohibit such access. For example, each session gets its own unique "schema" which only it can write to, but everyone can read from.

Yes, we would make them completely inaccessible by design, for compatibility (and to decrease complexity).

> Will temporary tables increase table ID / namespace churn and the size of the system config range? I think the answer is yes, and fixing this is the biggest obstacle I see.

Yeah, I don't know how to deal with this. How bad is it to use lots of table ids? That doesn't sound too bad. But writing too much to system config range sounds bad. Unfortunately, I have no idea how to fix that. Isn't it a bigger problem that all of this stuff is relegated to one range?

**Comment by leafji** [comment] 2019-07-29 06:19
Hello @jordanlewis :

Is there any plan of this temp table feature now? I would like to use this feature in our application project, if have any short-term planning， plz Let me know that.

thanks
leafji

**Comment by awoods187** [comment] 2020-03-17 02:53
@otan do you think we can close this now?

**Comment by otan** [comment] 2020-03-17 05:45
Yes. We support TEMP tables, views and sequences.

**Closed by otan** 2020-03-17 05:45 UTC
Labels: A-sql-hibernate, A-sql-pgcompat, A-sql-semantics, C-enhancement, X-anchored-telemetry
