### ISSUE TITLE
circleci: failed tests: TestDockerFinagle 

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#5959] opened 2016-04-09 01:35 UTC
The following test appears to have failed:

[#16107](https://circleci.com/gh/cockroachdb/cockroach/16107):

```
	at org.junit.runner.JUnitCore.run(JUnitCore.java:117)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:98)
	at org.junit.runner.JUnitCore.runMainAndExit(JUnitCore.java:53)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:45)

FAILURES!!!
Tests run: 12,  Failures: 2

I160409 01:33:15.347881 acceptance/cluster/localcluster.go:649  stopping
I160409 01:33:15.348074 acceptance/cluster/localcluster.go:547  event stream done, resetting...: net/http: request canceled
I160409 01:33:15.348094 acceptance/cluster/localcluster.go:570  events monitor exits
I160409 01:33:15.349230 acceptance/cluster/docker.go:397  ContainerKill: *errors.errorString: Error response from daemon: Cannot kill container d6e6cd8ccebb2925ae5eb4ff7bbe111bbd9b1c0bf355be1d9ad23d1fb80e142e: Container d6e6cd8ccebb2925ae5eb4ff7bbe111bbd9b1c0bf355be1d9ad23d1fb80e142e is not running
--- FAIL: TestDockerFinagle (17.07s)
	util_test.go:281: expected success: non-zero exit code: 1
=== RUN   TestGossipPeerings
I160409 01:33:17.207021 acceptance/cluster/localcluster.go:286  Initializing Cluster AdHoc 3x1:
{"name":"AdHoc 3x1","nodes":[{"count":3,"stores":[{"count":1,"max_ranges":0}]}],"duration":5000000000}
I160409 01:33:17.208746 acceptance/cluster/docker.go:102  ImagePull cockroachdb/builder:20160305-182433 already exists
I160409 01:33:17.842739 acceptance/cluster/localcluster.go:581  creating certs (1024bit) in: /home/ubuntu/cockroach/.localcluster.certs.718791333
I160409 01:33:17.920725 acceptance/cluster/localcluster.go:532  events monitor starts
I160409 01:33:18.257386 acceptance/cluster/localcluster.go:480  *** started roach0 ***
  ui:        https://127.0.0.1:32834
  trace:     https://127.0.0.1:32834/debug/requests
--
--- SKIP: TestBuildBabyCluster (0.00s)
	terraform_test.go:30: only enabled during testing
=== RUN   TestFiveNodesAndWriters
--- SKIP: TestFiveNodesAndWriters (0.00s)
	util_test.go:65: running in docker mode
FAIL
ok github.com/cockroachdb/cockroach/acceptance 1337s

```
Please assign, take a look and update the issue accordingly.

**Comment by dt** [comment] 2016-04-09 18:45
```
There were 2 failures:
1) A postgres client should update a row(com.twitter.finagle.postgres.integration.IntegrationSpec)
org.scalatest.exceptions.TestFailedException: OK(0) did not equal OK(1)
	at org.scalatest.MatchersHelper$.newTestFailedException(MatchersHelper.scala:160)
	at org.scalatest.MustMatchers$MustMethodHelper$.mustMatcher(MustMatchers.scala:6231)
	at org.scalatest.MustMatchers$AnyMustWrapper.must(MustMatchers.scala:6277)
	at com.twitter.finagle.postgres.integration.IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply$mcV$sp(IntegrationSpec.scala:148)
	at com.twitter.finagle.postgres.integration.IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(IntegrationSpec.scala:137)
	at com.twitter.finagle.postgres.integration.IntegrationSpec$$anonfun$1$$anonfun$apply$mcV$sp$3.apply(IntegrationSpec.scala:137)
```
Duplicate of #5951 -- still think underlying cause is probably #5484.

**Closed by dt** 2016-04-09 18:45 UTC
Labels: Robot, test-failure
