### ISSUE TITLE
sql: OFFSET without LIMIT query crashes the node.

### ISSUE THREAD

**Issue by eldos-dl** [cockroachdb/cockroach#16311] opened 2017-06-04 11:26 UTC
**BUG REPORT**
```
Build Tag:    v1.0.1
Build Time:   2017/05/25 15:17:49
Distribution: CCL
Platform:     linux amd64
Go Version:   go1.8.1
C Compiler:   gcc 6.3.0
Build SHA-1:  50fd18dcf8da75a0f4980344a885fe6105d0cf23
Build Type:   release
```
Code:
```
CREATE TABLE A (            
    id INT NOT NULL DEFAULT unique_rowid(),  
    name STRING(100) NOT NULL,               
    age INT NOT NULL,         
    CONSTRAINT "primary" PRIMARY KEY (id)
);
INSERT INTO A (name, age) VALUES ('A', 22);
INSERT INTO A (name, age) VALUES ('B', 23);

SELECT name, age FROM a OFFSET 1; -- Works fine.
SELECT name, age FROM a ORDER BY name OFFSET 1; -- Crashes the node
```
Not sure if the last query is legal though. But even if it is illegal I believe it should not crash the node.

**Comment by jordanlewis** [comment] 2017-06-04 15:12
Thanks for the report - it's a duplicate of #16090 which has been recently fixed and should be available in an upcoming bugfix release.

**Closed by jordanlewis** 2017-06-04 15:12 UTC
