### ISSUE TITLE
Sentry: memo.go:488: cannot overwrite × /  (9.15) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo)...

### ISSUE THREAD

**Issue by cockroach-sentry** [cockroachdb/cockroach#129294] opened 2024-08-20 01:37 UTC
This issue was auto filed by Sentry. It represents a crash or reported error on a live cluster with telemetry enabled.

Sentry Link: [https://cockroach-labs.sentry.io/issues/5733054376/?referrer=webhooks_plugin](https://cockroach-labs.sentry.io/issues/5733054376/?referrer=webhooks_plugin)

Panic Message:

```
memo.go:488: cannot overwrite × /  (9.15) with × /  (×)
(1) assertion failure
Wraps: (2) attached stack trace
  -- stack trace:
  | github.com/cockroachdb/cockroach/pkg/sql/opt/memo.(*Memo).SetBestProps
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/memo/memo.go:488
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:819
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).setLowestCostTree
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:804
  | github.com/cockroachdb/cockroach/pkg/sql/opt/xform.(*Optimizer).Optimize
  | 	github.com/cockroachdb/cockroach/pkg/sql/opt/xform/optimizer.go:275
  | github.com/cockroachdb/cockroach/pkg/sql.(*optPlanningCtx).buildExecMemo
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:620
  | github.com/cockroachdb/cockroach/pkg/sql.(*planner).makeOptimizerPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/plan_opt.go:250
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).makeExecPlan
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:2325
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1817
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1150
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:145
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithProfiling
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:3457
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:144
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func1
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2292
  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
  | 	github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:2297
Wraps: (3) cannot overwrite × /  (9.15) with × /  (×)
Error types: (1) *assert.withAssertionFailure (2) *withstack.withStack (3) *errutil.leafError
-- report composition:
*errutil.leafError: cannot overwrite × /  (9.15) with × /  (×)
memo.go:488: *withstack.withStack (top exception)
*assert.withAssertionFailure
```

<details>
<summary>Stacktrace (expand for inline code snippets):</summary>

[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor.go#L2296-L2298](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor.go#L2296-L2298)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor.go#L2291-L2293](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor.go#L2291-L2293)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L143-L145](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L143-L145)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L3456-L3458](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L3456-L3458)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L144-L146](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L144-L146)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L1149-L1151](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L1149-L1151)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L1816-L1818](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L1816-L1818)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L2324-L2326](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/conn_executor_exec.go#L2324-L2326)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L249-L251](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L249-L251)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L619-L621](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/plan_opt.go#L619-L621)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L274-L276](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L274-L276)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L803-L805)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L818-L820](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/xform/optimizer.go#L818-L820)
[https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/memo/memo.go#L487-L489](https://github.com/cockroachdb/cockroach/blob/9e10212477fde97f55ea4fff01797288c836575c/pkg/sql/opt/memo/memo.go#L487-L489)
</details>

```
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd at line 2297
pkg/sql/conn_executor.go in pkg/sql.(*connExecutor).execCmd.func1 at line 2292
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt at line 144
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execWithProfiling at line 3457
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmt.func1 at line 145
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).execStmtInOpenState at line 1150
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).dispatchToExecutionEngine at line 1817
pkg/sql/conn_executor_exec.go in pkg/sql.(*connExecutor).makeExecPlan at line 2325
pkg/sql/plan_opt.go in pkg/sql.(*planner).makeOptimizerPlan at line 250
pkg/sql/plan_opt.go in pkg/sql.(*optPlanningCtx).buildExecMemo at line 620
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).Optimize at line 275
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 804
pkg/sql/opt/xform/optimizer.go in pkg/sql/opt/xform.(*Optimizer).setLowestCostTree at line 819
pkg/sql/opt/memo/memo.go in pkg/sql/opt/memo.(*Memo).SetBestProps at line 488
```

### Tags

| Tag | Value |
| --- | --- |
| Command | server |
| Environment | v24.1.3 |
| Go Version | go1.22.5 X:nocoverageredesign |
| Platform | linux amd64 |
| Distribution | CCL |
| Cockroach Release | v24.1.3 |
| Cockroach SHA | 9e10212477fde97f55ea4fff01797288c836575c |
| # of CPUs | 4 |
| # of Goroutines | 470 |

Jira issue: CRDB-41479

**Comment by DrewKimball** [comment] 2024-08-26 19:21
Dupe of #116022

**Closed by DrewKimball** 2024-08-26 19:21 UTC
Labels: C-bug, O-sentry, branch-release-24.1
