### ISSUE TITLE
sql: crdb_internal.force_retry doesn't actually cause a client.Txn retry

### ISSUE THREAD

**Issue by andreimatei** [cockroachdb/cockroach#16827] opened 2017-06-30 20:02 UTC
Don't know what's going on exactly, but there's something about how a retryable error can be generated for a txn that doesn't have an id, but then is checked against the txn after the txn has been assigned an id. The deferred id assignment probably has something to do with `RETURNING NOTHING` statements which are executed async.

Repro:

```
CREATE TABLE kv (
  k string PRIMARY KEY,
  v string
)

root@:26257/test> BEGIN TRANSACTION; select 1; INSERT INTO kv(k, v) VALUES ('auto_retry', 'b') RETURNING NOTHING; SELECT crdb_internal.force_retry('1000000ms':::INTERVAL); rollback;
+---+
| 1 |
+---+
| 1 |
+---+
(1 row)
root@:26257 ERROR> rollback;
ROLLBACK
```

The error is `pq: retryable error from another txn. Current txn ID: 8a4be5f8-63fd-4ced-9e2c-937f2cea5e1c: HandledRetryableTxnError: forced by crdb_internal.force_retry()`, but it's not showing in the CLI because of #16825.

Hopefully this is only a problem for errors generated with `crdb_internal.force_retry()`, as errors generated by real operations would require a txn with an id. The problem is likely similar to the one fixed in #16709.

**Comment by andreimatei** [comment] 2017-08-10 19:07
With #17299 which assigns txn ids early, the behavior here changes - the 2nd execution of the `INSERT` gives: `pq: duplicate key value (k)=('auto_retry') violates unique constraint "primary"`.
This sounds like #17197, except Nathan says that the SELECT should drain the queue and synchronize everything. Which also raises questions about how the original issue reported here was happening exactly. Something's funky.

**Comment by nvanbenschoten** [comment] 2017-08-10 19:40
I'm seeing the `pq: duplicate key value (k)=('auto_retry') violates unique constraint "primary"` error even without the `INSERT` using `RETURNING NOTHING`. Strange.

**Comment by nvanbenschoten** [comment] 2017-08-10 19:43
Does `crdb_internal.force_retry` actually cause the txn epoch to be incremented?

**Comment by nvanbenschoten** [comment] 2017-08-23 21:57
Yeah, this isn't an issue with `RETURNING NOTHING`, it's an issue with `crdb_internal.force_retry`.
```
root@:26257/test> BEGIN TRANSACTION; SELECT 1; INSERT INTO kv(k, v) VALUES ('auto_retry', 'b'); SELECT crdb_internal.force_retry('1000000ms':::INTERVAL); ROLLBACK TRANSACTION;
pq: duplicate key value (k)=('auto_retry') violates unique constraint "primary"
```
I think the issue is that the `HandledRetryableTxnError` created by the builtin function isn't actually passed up through `client.Txn.send`, so the client doesn't ever even see it. In other words, the retryable error doesn't actually cause the `client.Txn` to retry.

I'm not sure if we want to try to fix this or it we should just document that `crdb_internal.force_retry` should only be used to test retriable errors at the SQL layer and that behavior like this is expected. Two questions that might guide this decision are:
- What do we do for `force_retry(some_other_id)`? We're not actually forcing that other transaction to retry if it exists (eg. writing to it's TxnRecord). Should we?
- If we introduced a `crdb_internal.force_abort` function, would we expect it to actually abort our transaction record?

I guess my indecision is due to a lack of understanding about what the goal of these `crdb_internal` builtins are for (just testing vs. general purpose hooks into the system).

\cc @knz

**Comment by knz** [comment] 2017-08-28 15:14
>  What do we do for force_retry(some_other_id)? We're not actually forcing that other transaction to retry if it exists (eg. writing to it's TxnRecord). Should we?

I do not understand the question. the `force_retry` built-in takes a duration, not an ID.

>   If we introduced a crdb_internal.force_abort function, would we expect it to actually abort our transaction record?

I do not understand this either. What would you want to use this built-in for?

Look in this situation you're confusing the forest for the trees. I introduced `force_retry` just and only for testing of the retry mechanism. The original use was to check the CLI prompt `pkg/cli/interactive_tests/test_txn_prompt.tcl` and since then Andrei added some stuff in `txn_restart_test.go` and Tristan in `result_writer_test.go`.

The only two questions that matter are:

1) are these tests still able to test whatever they were intended to test? Yes - nothing is broken, don't do anything. No - make a replacement force_retry that triggers the correct error for these tests to work.

2) is there anything new that needs testing for which this particular function doesn't work? No - nothing is broken, don't do anything. No - either change the function or add a new one, but check that all the existing tests using the current function still test what they were intending to test.

(use `git grep -i force_retry`)

**Comment by nvanbenschoten** [comment] 2017-08-28 15:30
> the `force_retry` built-in takes a duration, not an ID.

`force_retry` has [an overload](https://github.com/cockroachdb/cockroach/blob/a55a56ee340327acc13fc4d1f1cdcea2157fb4ce/pkg/sql/parser/builtins.go#L1875) to take a TxnID.

> What would you want to use this built-in for?

That's exactly my question when I said "I guess my indecision is due to a lack of understanding about what the goal of these crdb_internal builtins are for (just testing vs. general purpose hooks into the system)."

From your response

> I introduced `force_retry` just and only for testing of the retry mechanism

it sounds like these builtins are only for testing the upper layers of the sql engine, which is fine. In that case we can close this issue with a small comment on `crdb_internal.force_retry`. But if we intend for these functions to be general purpose hooks into the system (to be used during testing, debugging, etc.) then they're insufficient at the moment and the questions I asked still stand.

**Comment by andreimatei** [comment] 2018-01-29 16:46
#21836 bumps the epoch on the restarting txn.

**Closed** 2018-01-31 00:33 UTC
