### ISSUE TITLE
stress: failed test in cockroach/sql/sql.test: TestPurgeOldLeases

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6841] opened 2016-05-21 12:18 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/82e5c27735be951890f22fc85888a2cf46a13605

Stress build found a failed test:

```
=== RUN   TestPurgeOldLeases
W160521 07:01:57.015699 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160521 07:01:57.024401 storage/engine/rocksdb.go:137  opening in memory rocksdb instance
I160521 07:01:57.025638 server/node.go:401  store store=0:0 ([]=) not bootstrapped
W160521 07:01:57.027201 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160521 07:01:57.027562 storage/replica_command.go:1470  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406615h1m58.026993698s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-21 07:01:57.027456439 +0000 UTC]
I160521 07:01:57.028136 server/node.go:327  **** cluster {71583ebb-6c84-4c0e-9f7a-a246bedffe46} has been created
I160521 07:01:57.028161 server/node.go:328  **** add additional nodes by specifying --join=127.0.0.1:34375
W160521 07:01:57.028171 gossip/gossip.go:897  not connected to cluster; use --join to specify a connected node
I160521 07:01:57.028925 server/node.go:414  initialized store store=1:1 ([]=): {Capacity:10365558784 Available:7971717120 RangeCount:0}
I160521 07:01:57.028956 server/node.go:302  node ID 1 initialized
I160521 07:01:57.029013 storage/stores.go:287  read 0 node addresses from persistent storage
I160521 07:01:57.029129 server/node.go:535  connecting to gossip network to verify cluster ID...
I160521 07:01:57.029687 server/node.go:556  node connected via gossip and verified as part of cluster {"71583ebb-6c84-4c0e-9f7a-a246bedffe46"}
I160521 07:01:57.029719 server/node.go:355  [node=1] Started node with [[]=] engine(s) and attributes []
I160521 07:01:57.029748 server/server.go:416  starting https server at 127.0.0.1:44591
I160521 07:01:57.029763 server/server.go:417  starting grpc/postgres server at 127.0.0.1:34375
I160521 07:01:57.030149 storage/split_queue.go:100  splitting range=1 [/Min-/Max) at keys [/Table/11/0 /Table/12/0 /Table/13/0 /Table/14/0]
I160521 07:01:57.060870 storage/replica_command.go:2011  initiating a split of range=1 [/Min-/Max) at key /Table/11
I160521 07:01:57.088802 server/updates.go:155  No previous updates check time.
I160521 07:01:57.108026 storage/replica_command.go:1470  range 2: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406615h1m58.134913525s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-21 07:01:57.09159051 +0000 UTC]
I160521 07:01:57.108538 storage/replica_command.go:2011  initiating a split of range=2 [/Table/11-/Max) at key /Table/12
I160521 07:01:57.147961 storage/replica_command.go:1470  range 3: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406615h1m58.187995402s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-21 07:01:57.147909926 +0000 UTC]
I160521 07:01:57.148104 storage/replica_command.go:2011  initiating a split of range=3 [/Table/12-/Max) at key /Table/13
I160521 07:01:57.155139 storage/replica_command.go:1470  range 4: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC 406615h1m58.204880007s following replica {0 0 0} 1970-01-01 00:00:00 +0000 UTC 0 [physicalTime=2016-05-21 07:01:57.155091353 +0000 UTC]
I160521 07:01:57.155828 storage/replica_command.go:2011  initiating a split of range=4 [/Table/13-/Max) at key /Table/14
I160521 07:01:57.256830 stopper.go:352  draining; tasks left:
1      server/node.go:803
W160521 07:01:57.257698 sql/lease.go:1100  error purging leases for table 51(test): node unavailable; try another peer
--- FAIL: TestPurgeOldLeases (0.27s)
	lease_internal_test.go:148: found 2 leases instead of 3
```

Run Details:

```
0 runs so far, 0 failures, over 5s
0 runs so far, 0 failures, over 10s
0 runs so far, 0 failures, over 15s
0 runs so far, 0 failures, over 20s
0 runs so far, 0 failures, over 25s
0 runs so far, 0 failures, over 30s
0 runs so far, 0 failures, over 35s
0 runs so far, 0 failures, over 40s
0 runs so far, 0 failures, over 45s
0 runs so far, 0 failures, over 50s
3 runs completed, 1 failures, over 52s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-05-21 15:55
Duplicate of #6810

**Closed by bdarnell** 2016-05-21 15:55 UTC
Labels: Robot, test-failure
