### ISSUE TITLE
sql: support pg_catalog.regclass when casting

### ISSUE THREAD

**Issue by robins** [cockroachdb/cockroach#18856] opened 2017-09-28 00:16 UTC
When casting, apparently Cockroachdb doesn't (yet) support pg_catalog.regclass although regclass works fine. It would help if CockroachDB could (eventually) support this, to avoid namespace clashes.

**In Postgres**

```
postgres2=> select 'a'::regclass::OID;
   oid
----------
 20041642
(1 row)
postgres2=> select 'a'::pg_catalog.regclass::OID;
   oid
----------
 20041642
(1 row)
```

**In CockroachDB**

```
bank=> \d a
                      Table "bank.a"
 Column |  Type  |     Collation     | Nullable | Default
--------+--------+-------------------+----------+---------
 b      | bigint | Not Supported Yet |          |
Indexes:
    "primary" PRIMARY KEY, (Not Supported Yet)
bank=> select 'a'::regclass::OID;
 'a'::REGCLASS::OID
--------------------
          818765073
(1 row)

bank=> select 'a'::pg_catalog.regclass::OID;
ERROR:  syntax error at or near "pg_catalog"
select 'a'::pg_catalog.regclass::OID;
            ^

```
Downstream issue robins/postgres#23 is dependent on this to be fixed.

**Comment by knz** [comment] 2018-02-28 14:13
I have had a look into this. This is a larger issue than it first seemed because it requires a rather large refactor of our SQL grammar. Will look into it for 2.1 instead of 2.0.

**Comment by knz** [comment] 2018-02-28 14:28
Proposing #23208 but lemme see if my colleagues agree on having such a special case compatibility rule.

**Comment by jordanlewis** [comment] 2019-09-19 02:36
Closing as a duplicate of #16395.

**Closed by jordanlewis** 2019-09-19 02:36 UTC
Labels: A-sql-name-resolution, A-sql-pgcompat, C-enhancement
