### ISSUE TITLE
sql: cast (SELECT NULL) shouldn't be usable

### ISSUE THREAD

**Issue by mjibson** [cockroachdb/cockroach#29372] opened 2018-08-30 19:23 UTC
```
SELECT string_agg('foo', CAST ((SELECT NULL) AS BYTES)) OVER ();
```

exists in the aggregate logictest. The second argument to that function is an error in postgres and probably should be in cockroach?

**Comment by knz** [comment] 2018-09-21 12:06
This is absolutely valid in PostgreSQL:

```sql
>  select cast((select null) as bytea);
 ?column?
----------

(1 row)
```

and is valid in CockroachDB:

```sql
> select cast((select null) as bytea);
  bytes
+-------+
  NULL
(1 row)
```

Incidentally, the query you reported initially both works in postgres and CockroachDB without errors:

```
> SELECT string_agg('foo', CAST ((SELECT NULL) AS BYTES)) OVER ();
  string_agg
+------------+
  foo
(1 row)
```

```
kena=# SELECT string_agg('foo', CAST ((SELECT NULL) AS BYTEA)) OVER ();
 string_agg
------------
 \x666f6f
(1 row)
```

(`\x666f6f` is the `psql` representation of "foo"  as byte array. The result is the same.)

**Comment by knz** [comment] 2018-09-21 12:07
I think this all works as intended. I will close the issue; if you think we should do something more feel free to re-open.

**Closed by knz** 2018-09-21 12:07 UTC
Labels: C-bug
