### ISSUE TITLE
stability: use-after-finish during server shutdown

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#8733] opened 2016-08-22 14:43 UTC
Immediately after CTRL+C.

```
I160822 10:42:37.321461 stopper.go:408  quiesceing; tasks left:
1      ts/db.go:103
1      server/node.go:700
panic: (*basictracer.errAssertionFailed) (0x4f4e520,0xc421175840) [recovered]
	panic: (*basictracer.errAssertionFailed) (0x4f4e520,0xc421175840)

goroutine 115 [running]:
panic(0x4f4e520, 0xc421175840)
	/usr/local/Cellar/go/1.7rc4/libexec/src/runtime/panic.go:500 +0x1a1
github.com/cockroachdb/cockroach/util/stop.(*Stopper).Recover(0xc420385320)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:176 +0x6e
panic(0x4f4e520, 0xc421175840)
	/usr/local/Cellar/go/1.7rc4/libexec/src/runtime/panic.go:458 +0x243
github.com/opentracing/basictracer-go.(*spanImpl).maybeAssertSanityLocked(0xc420385170)
	/Users/tschottdorf/go/src/github.com/opentracing/basictracer-go/debug.go:27 +0x331
github.com/opentracing/basictracer-go.(*spanImpl).Lock(0xc420385170)
	/Users/tschottdorf/go/src/github.com/opentracing/basictracer-go/debug.go:19 +0x3f
github.com/opentracing/basictracer-go.(*spanImpl).Log(0xc420385170, 0x0, 0x0, 0x0, 0xc4211806c0, 0x53, 0x0, 0x0)
	/Users/tschottdorf/go/src/github.com/opentracing/basictracer-go/span.go:106 +0x83
github.com/opentracing/basictracer-go.(*spanImpl).LogEvent(0xc420385170, 0xc4211806c0, 0x53)
	/Users/tschottdorf/go/src/github.com/opentracing/basictracer-go/span.go:94 +0x9e
github.com/cockroachdb/cockroach/util/log.Trace(0x7b459f8, 0xc42049b710, 0xc4211806c0, 0x53)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/trace.go:33 +0xc7
github.com/cockroachdb/cockroach/util/log.addStructured(0x7b459f8, 0xc42049b710, 0xc400000001, 0x2, 0x512ddf6, 0x21, 0xc420633ec8, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:62 +0x10d
github.com/cockroachdb/cockroach/util/log.logDepth(0x7b459f8, 0xc42049b710, 0x1, 0x1, 0x512ddf6, 0x21, 0xc420633ec8, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/log.go:70 +0x8c
github.com/cockroachdb/cockroach/util/log.Warningf(0x7b459f8, 0xc42049b710, 0x512ddf6, 0x21, 0xc420633ec8, 0x1, 0x1)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/log/log.go:103 +0x7e
github.com/cockroachdb/cockroach/storage.(*Store).startGossip.func2()
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/storage/store.go:1030 +0x305
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc420385320, 0xc420ba7960)
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x7d
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/Users/tschottdorf/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:188 +0x66
```

**Comment by bdarnell** [comment] 2016-08-22 14:45
Dupe of #8732

**Closed by bdarnell** 2016-08-22 14:45 UTC
