### ISSUE TITLE
stress: failed test in cockroach/gossip/gossip.test: TestConvergence

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#6259] opened 2016-04-23 11:15 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/18d9f805a6ec17edc9f027e5f4853291db2c47c0

Stress build found a failed test:

```
=== RUN   TestConvergence
I160423 03:47:08.131605 gossip/simulation/network.go:57  simulating gossip network with 10 nodes
W160423 03:47:08.132019 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
W160423 03:47:08.133030 gossip/gossip.go:892  not connected to cluster; use --join to specify a connected node
I160423 03:47:08.133354 gossip/gossip.go:918  starting client to 127.0.0.1:40683
F160423 03:47:08.138176 gossip/simulation/network.go:73  listen tcp 127.0.0.1:0: listen: address already in use
goroutine 1576 [running]:
github.com/cockroachdb/cockroach/util/log.getStacks(0xeceace701, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:862 +0xb8
github.com/cockroachdb/cockroach/util/log.(*loggingT).outputLogEntry(0x1206fa0, 0x3, 0xfd98ea, 0x1c, 0x49, 0xc8204a4740, 0x36)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:728 +0x9c5
github.com/cockroachdb/cockroach/util/log.addStructured(0x0, 0x0, 0x7fd200000003, 0x2, 0x0, 0x0, 0xc820293dd8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/structured.go:57 +0xfc
github.com/cockroachdb/cockroach/util/log.logDepth(0x0, 0x0, 0x1, 0xc800000003, 0x0, 0x0, 0xc820293dd8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:73 +0x7b
github.com/cockroachdb/cockroach/util/log.Fatal(0xc820293dd8, 0x1, 0x1)
	/go/src/github.com/cockroachdb/cockroach/util/log/log.go:172 +0x5e
github.com/cockroachdb/cockroach/gossip/simulation.NewNetwork(0xa, 0xc820d1b200)
	/go/src/github.com/cockroachdb/cockroach/gossip/simulation/network.go:73 +0x4b9
github.com/cockroachdb/cockroach/gossip_test.verifyConvergence(0xa, 0x64, 0xc820d1b200)
	/go/src/github.com/cockroachdb/cockroach/gossip/convergence_test.go:30 +0x3d
github.com/cockroachdb/cockroach/gossip_test.TestConvergence(0xc820d1b200)
	/go/src/github.com/cockroachdb/cockroach/gossip/convergence_test.go:49 +0x87
testing.tRunner(0xc820d1b200, 0x11e7848)
	/usr/local/go/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/go/src/testing/testing.go:582 +0x892

goroutine 1 [chan receive]:
testing.RunTests(0xd7e240, 0x11e7560, 0x21, 0x21, 0xc82017f901)
	/usr/local/go/src/testing/testing.go:583 +0x8d2
testing.(*M).Run(0xc820041f08, 0x409883)
	/usr/local/go/src/testing/testing.go:515 +0x81
main.main()
	github.com/cockroachdb/cockroach/gossip/_test/_testmain.go:120 +0x117

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 50 [chan receive]:
github.com/cockroachdb/cockroach/util/log.(*loggingT).flushDaemon(0x1206fa0)
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:1011 +0x64
created by github.com/cockroachdb/cockroach/util/log.init.1
	/go/src/github.com/cockroachdb/cockroach/util/log/clog.go:598 +0x8a

goroutine 1515 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).manage.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:791 +0x33b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201ec100)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1591 [select]:
google.golang.org/grpc.(*Conn).transportMonitor(0xc8201140e0)
	/go/src/google.golang.org/grpc/clientconn.go:510 +0x1d3
google.golang.org/grpc.NewConn.func1(0xc8201140e0)
	/go/src/google.golang.org/grpc/clientconn.go:321 +0x1b5
created by google.golang.org/grpc.NewConn
	/go/src/google.golang.org/grpc/clientconn.go:322 +0x4dd

goroutine 1521 [select]:
google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc8201f4450, 0xc820134230, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:141 +0x7e6
google.golang.org/grpc/transport.(*Stream).Read(0xc8201142a0, 0xc820134230, 0x5, 0x5, 0xd7af68, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:294 +0x71
io.ReadAtLeast(0x7fd2602d4000, 0xc8201142a0, 0xc820134230, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd2602d4000, 0xc8201142a0, 0xc820134230, 0x5, 0x5, 0x7fd260319e90, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
google.golang.org/grpc.(*parser).recvMsg(0xc820134220, 0xc820cf50a8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/rpc_util.go:218 +0xb9
google.golang.org/grpc.recv(0xc820134220, 0x7fd26031e518, 0x1227048, 0xc8201142a0, 0x0, 0x0, 0xbc4d60, 0xc8204aa1e0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/rpc_util.go:302 +0x45
google.golang.org/grpc.(*clientStream).RecvMsg(0xc820478280, 0xbc4d60, 0xc8204aa1e0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/stream.go:232 +0xac
github.com/cockroachdb/cockroach/gossip.(*gossipGossipClient).Recv(0xc82016a3e0, 0x4b41e9, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.pb.go:176 +0x7e
github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2.1(0x7fd2602d4078, 0xc82016a3e0, 0xc8201f60c0, 0xc82000d8c0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:227 +0x37
github.com/cockroachdb/cockroach/gossip.(*client).gossip.func2()
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:235 +0x51
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201f4660)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1517 [IO wait]:
net.runtime_pollWait(0x7fd26031f040, 0x72, 0xc82034e000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8201b8220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201b8220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201b81c0, 0xc82034e000, 0x8000, 0x8000, 0x0, 0x7fd2603d4050, 0xc82000e068)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc820034118, 0xc82034e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820160480)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820160480, 0xc82042c278, 0x9, 0x9, 0x9, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7fd2603d9c30, 0xc820160480, 0xc82042c278, 0x9, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:297 +0xe6
io.ReadFull(0x7fd2603d9c30, 0xc820160480, 0xc82042c278, 0x9, 0x9, 0xb71a021c34773e01, 0x0, 0x0)
	/usr/local/go/src/io/io.go:315 +0x62
golang.org/x/net/http2.readFrameHeader(0xc82042c278, 0x9, 0x9, 0x7fd2603d9c30, 0xc820160480, 0x20000000, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:236 +0xa5
golang.org/x/net/http2.(*Framer).ReadFrame(0xc82042c240, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:463 +0x106
google.golang.org/grpc/transport.(*framer).readFrame(0xc820012600, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Client).reader(0xc820356000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:757 +0x109
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:200 +0x159a

goroutine 1578 [chan receive]:
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func1()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:47 +0x47
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8200ce9e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1518 [select]:
google.golang.org/grpc.NewClientStream.func1(0x7fd2603580c0, 0xc820356000, 0xc8201142a0, 0xc820478280)
	/go/src/google.golang.org/grpc/stream.go:149 +0x258
created by google.golang.org/grpc.NewClientStream
	/go/src/google.golang.org/grpc/stream.go:157 +0xab2

goroutine 1516 [select]:
google.golang.org/grpc/transport.(*http2Client).controller(0xc820356000)
	/go/src/google.golang.org/grpc/transport/http2_client.go:835 +0x5da
created by google.golang.org/grpc/transport.newHTTP2Client
	/go/src/google.golang.org/grpc/transport/http2_client.go:194 +0x153b

goroutine 1592 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc8201141c0, 0xc8201141c0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7fd26031e518, 0x1227048, 0x0, 0x0, 0x0, 0x0, 0x7fd260396100, 0xc8201340c0, 0x100, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7fd260396280, 0xc8201f62a0, 0xcb7680, 0x1d, 0xbcd060, 0xc8204a43c0, 0xbc7960, 0xc820134100, 0xc820478000, 0x0, ...)
	/go/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/cockroachdb/cockroach/rpc.(*heartbeatClient).Ping(0xc820174178, 0x7fd260396280, 0xc8201f62a0, 0xc8204a43c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/heartbeat.pb.go:115 +0xec
github.com/cockroachdb/cockroach/rpc.(*Context).heartbeat(0xc82015c1c0, 0x7fd260396228, 0xc820174178, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:237 +0x150
github.com/cockroachdb/cockroach/rpc.(*Context).runHeartbeat(0xc82015c1c0, 0xc820478000, 0xc820c92240, 0xf, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:192 +0x247
github.com/cockroachdb/cockroach/rpc.(*Context).GRPCDial.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:173 +0x66
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201f6210)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1514 [select]:
github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:754 +0x26b
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201ec0e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1577 [chan receive]:
github.com/cockroachdb/cockroach/rpc.NewContext.func1()
	/go/src/github.com/cockroachdb/cockroach/rpc/context.go:105 +0x57
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8200ce8e0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1513 [chan receive]:
github.com/cockroachdb/cockroach/gossip.(*server).start.func3()
	/go/src/github.com/cockroachdb/cockroach/gossip/server.go:298 +0x5c
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201ec0c0)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1579 [IO wait]:
net.runtime_pollWait(0x7fd26031ebc0, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc82015c290, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82015c290, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82015c230, 0x0, 0x7fd260394090, 0xc8201720c0)
	/usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(*TCPListener).AcceptTCP(0xc820132068, 0xc820045ea8, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820132068, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc82013e000, 0x7fd26031e5d8, 0xc820132068, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:252 +0x1b5
github.com/cockroachdb/cockroach/util.ListenAndServeGRPC.func2()
	/go/src/github.com/cockroachdb/cockroach/util/net.go:52 +0x3f
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8200cea20)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1607 [runnable]:
golang.org/x/net/http2/hpack.(*Decoder).readString(0xc82017e1a0, 0xc8202942d1, 0x26, 0x26, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/golang.org/x/net/http2/hpack/hpack.go:538 +0x69f
golang.org/x/net/http2/hpack.(*Decoder).parseFieldLiteral(0xc82017e1a0, 0x6, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/hpack/hpack.go:418 +0x30e
golang.org/x/net/http2/hpack.(*Decoder).parseHeaderFieldRepr(0xc82017e1a0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/hpack/hpack.go:360 +0xd4
golang.org/x/net/http2/hpack.(*Decoder).Write(0xc82017e1a0, 0xc8202942a0, 0x57, 0x57, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/hpack/hpack.go:307 +0xae
golang.org/x/net/http2.(*Framer).readMetaFrame(0xc8200d60c0, 0xc8201f6420, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:1424 +0x41e
golang.org/x/net/http2.(*Framer).ReadFrame(0xc8200d60c0, 0x0, 0x0, 0x0, 0x0)
	/go/src/golang.org/x/net/http2/frame.go:488 +0x81a
google.golang.org/grpc/transport.(*framer).readFrame(0xc8201f6300, 0x0, 0x0, 0x0, 0x0)
	/go/src/google.golang.org/grpc/transport/http_util.go:406 +0x3d
google.golang.org/grpc/transport.(*http2Server).HandleStreams(0xc820c48120, 0xc8201f63c0)
	/go/src/google.golang.org/grpc/transport/http2_server.go:247 +0x646
google.golang.org/grpc.(*Server).serveStreams(0xc82013e000, 0x7fd2603d9c80, 0xc820c48120)
	/go/src/google.golang.org/grpc/server.go:325 +0x159
google.golang.org/grpc.(*Server).serveNewHTTP2Transport(0xc82013e000, 0x7fd2603962c0, 0xc820150008, 0x0, 0x0)
	/go/src/google.golang.org/grpc/server.go:312 +0x49d
google.golang.org/grpc.(*Server).handleRawConn(0xc82013e000, 0x7fd2603962c0, 0xc820150008)
	/go/src/google.golang.org/grpc/server.go:289 +0x4ee
created by google.golang.org/grpc.(*Server).Serve
	/go/src/google.golang.org/grpc/server.go:261 +0x372

goroutine 1590 [select]:
github.com/cockroachdb/cockroach/gossip.(*client).gossip(0xc8201f60c0, 0xc82000d8c0, 0x7fd260396150, 0xc820174170, 0xc82015c150, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:239 +0x619
github.com/cockroachdb/cockroach/gossip.(*client).start.func1()
	/go/src/github.com/cockroachdb/cockroach/gossip/client.go:80 +0x2c7
github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1(0xc82015c150, 0xc8201f6150)
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:139 +0x52
created by github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker
	/go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:140 +0x62

goroutine 1532 [runnable]:
google.golang.org/grpc/transport.(*http2Server).controller(0xc820c48120)
	/go/src/google.golang.org/grpc/transport/http2_server.go:618
created by google.golang.org/grpc/transport.newHTTP2Server
	/go/src/google.golang.org/grpc/transport/http2_server.go:134 +0x853


ERROR: exit status 255
```

Run Details:

```
73 runs so far, 0 failures, over 5s
149 runs so far, 0 failures, over 10s
225 runs so far, 0 failures, over 15s
303 runs so far, 0 failures, over 20s
380 runs so far, 0 failures, over 25s
455 runs so far, 0 failures, over 30s
534 runs so far, 0 failures, over 35s
615 runs so far, 0 failures, over 40s
690 runs so far, 0 failures, over 45s
767 runs so far, 0 failures, over 50s
848 runs so far, 0 failures, over 55s
914 runs completed, 1 failures, over 59s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by bdarnell** [comment] 2016-04-23 14:16
Duplicate of #6230

**Closed by bdarnell** 2016-04-23 14:16 UTC
Labels: Robot, test-failure
