### ISSUE TITLE
Lateral join / `SELECT DISTINCT ON` failing to use index

### ISSUE THREAD

**Issue by jgallagher** [cockroachdb/cockroach#120866] opened 2024-03-22 01:00 UTC
**Describe the problem**

We observed a `unexpected database error: root: memory budget exceeded:` error and tracked it down to a query that was accessing a table that was significantly larger (a few hundred thousand rows instead of a few hundred rows) than expected. However, that table has an index that we believe is relevant to the query, so we were surprised to discover that the query was performing a full scan and join with the contents of the table. I think I've boiled a reproducer down; see below.

**To Reproduce**

Run cockroach in `start-single-node` mode, then create a couple tables with fake data:

```sql
-- create a "zpool" table with 100 random IDs.
create table zpool (id uuid);
insert into zpool select gen_random_uuid() from generate_series(1,100);

-- create an "inv_zpool" table with an id that references "zpool", a total
-- size that is not very relevant, and a timestamp.
create table inv_zpool (id uuid, total_size int, time_collected timestamptz);

-- populate "inv_zpool" with 10,000 rows, each of which has:
--   * a random ID chosen from the IDs of "zpool"
--   * a total_size of 1000
--   * a random timestamp in the window of "10 hours ago to now()"
insert into inv_zpool 
  select zpool.id, 1000, now() - random() * (timestamp '2024-01-01 20:00:00' - timestamp '2024-01-01 10:00:00')
  from generate_series(1,10000) as g
  inner join lateral (select id from zpool where g != -1 order by random() limit 1) as zpool on true;

-- create an index on inv_zpool
CREATE INDEX IF NOT EXISTS inv_zpool_by_id_and_time ON inv_zpool (id, time_collected DESC);

-- refresh crdb stats
analyze zpool;
analyze inv_zpool;
```

We'd like to write a query that returns "for each `zpool.id`, get the `total_size` from `inv_zpool` with the matching id and maximal `time_collected`. Given a single, individual zpool ID, we see that the index is used as expected:

```
root@[::1]:26257/defaultdb> select id from zpool order by random() limit 1;
                   id
----------------------------------------
  72edaaab-ff20-45d3-9dc2-a40f898d7089
(1 row)


Time: 1ms total (execution 1ms / network 0ms)

root@[::1]:26257/defaultdb> explain analyze select total_size from inv_zpool where id = '72edaaab-ff20-45d3-9dc2-a40f898d7089' order by time_collected limit 1;
                                                info
----------------------------------------------------------------------------------------------------
  planning time: 2ms
  execution time: 1ms
  distribution: local
  vectorized: true
  rows read from KV: 2 (112 B)
  cumulative time spent in KV: 844µs
  maximum memory usage: 50 KiB
  network usage: 0 B (0 messages)

  • index join
  │ nodes: n1
  │ actual row count: 1
  │ KV time: 225µs
  │ KV contention time: 0µs
  │ KV rows read: 1
  │ KV bytes read: 47 B
  │ estimated max memory allocated: 20 KiB
  │ estimated max sql temp disk usage: 0 B
  │ estimated row count: 1
  │ table: inv_zpool@inv_zpool_pkey
  │
  └── • revscan
        nodes: n1
        actual row count: 1
        KV time: 619µs
        KV contention time: 0µs
        KV rows read: 1
        KV bytes read: 65 B
        estimated max memory allocated: 20 KiB
        estimated row count: 1 (0.01% of the table; stats collected 4 minutes ago)
        table: inv_zpool@inv_zpool_by_id_and_time
        spans: [/'72edaaab-ff20-45d3-9dc2-a40f898d7089' - /'72edaaab-ff20-45d3-9dc2-a40f898d7089']
        limit: 1
(33 rows)
```

However, we haven't been able to construct a query that does the bulk work that doesn't involve a full scan, join, then sort of all 10,000 rows of `inv_zpool`. These are three attempts that I believe all return the correct results:

```sql 
select distinct on (id) id,total_size from inv_zpool order by id, time_collected desc;

select zpool.id, total_size from zpool, lateral (select total_size from inv_zpool where id = zpool.id order by time_collected desc limit 1) as foo;

select zpool.id, total_size from zpool inner join lateral (select total_size from inv_zpool where id = zpool.id order by time_collected desc limit 1) as foo on true;
```

but all three have similar `explain analyze` output that show a 10,000 row sort (possibly after a 10,000 row join):

```
root@[::1]:26257/defaultdb> explain analyze select distinct on (id) id,total_size from inv_zpool order by id, time_collected desc;
                                              info
-------------------------------------------------------------------------------------------------
  planning time: 560µs
  execution time: 7ms
  distribution: full
  vectorized: true
  rows decoded from KV: 10,000 (643 KiB, 1 gRPC calls)
  cumulative time spent in KV: 4ms
  maximum memory usage: 1.5 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 4ms
  isolation level: serializable
  priority: normal
  quality of service: regular

  • sort
  │ nodes: n1
  │ actual row count: 100
  │ estimated max memory allocated: 10 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 24µs
  │ estimated row count: 100
  │ order: +id
  │
  └── • distinct
      │ nodes: n1
      │ actual row count: 100
      │ estimated max memory allocated: 10 KiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 324µs
      │ estimated row count: 100
      │ distinct on: id
      │
      └── • sort
          │ nodes: n1
          │ actual row count: 10,000
          │ estimated max memory allocated: 1.0 MiB
          │ estimated max sql temp disk usage: 0 B
          │ sql cpu time: 2ms
          │ estimated row count: 10,000
          │ order: -time_collected
          │
          └── • scan
                nodes: n1
                actual row count: 10,000
                KV time: 4ms
                KV contention time: 0µs
                KV rows decoded: 10,000
                KV bytes read: 643 KiB
                KV gRPC calls: 1
                estimated max memory allocated: 730 KiB
                sql cpu time: 1ms
                estimated row count: 10,000 (100% of the table; stats collected 17 seconds ago)
                table: inv_zpool@inv_zpool_pkey
                spans: FULL SCAN
(53 rows)


Time: 9ms total (execution 8ms / network 1ms)

root@[::1]:26257/defaultdb> explain analyze select zpool.id, total_size from zpool, lateral (select total_size from inv_zpool where id = zpool.id order by time_collected desc limit 1) as foo;
                                                                      info
-------------------------------------------------------------------------------------------------------------------------------------------------
  planning time: 580µs
  execution time: 6ms
  distribution: full
  vectorized: true
  rows decoded from KV: 10,100 (648 KiB, 2 gRPC calls)
  cumulative time spent in KV: 3ms
  maximum memory usage: 2.3 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 4ms
  isolation level: serializable
  priority: normal
  quality of service: regular

  • distinct
  │ nodes: n1
  │ actual row count: 100
  │ estimated max memory allocated: 10 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 185µs
  │ estimated row count: 100
  │ distinct on: rowid
  │
  └── • sort
      │ nodes: n1
      │ actual row count: 10,000
      │ estimated max memory allocated: 1.6 MiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 2ms
      │ estimated row count: 10,000
      │ order: -time_collected
      │
      └── • hash join
          │ nodes: n1
          │ actual row count: 10,000
          │ estimated max memory allocated: 150 KiB
          │ estimated max sql temp disk usage: 0 B
          │ sql cpu time: 315µs
          │ estimated row count: 10,000
          │ equality: (id) = (id)
          │
          ├── • scan
          │     nodes: n1
          │     actual row count: 10,000
          │     KV time: 3ms
          │     KV contention time: 0µs
          │     KV rows decoded: 10,000
          │     KV bytes read: 643 KiB
          │     KV gRPC calls: 1
          │     estimated max memory allocated: 730 KiB
          │     sql cpu time: 1ms
          │     estimated row count: 10,000 (100% of the table; stats collected 2 seconds ago)
          │     table: inv_zpool@inv_zpool_pkey
          │     spans: FULL SCAN
          │
          └── • scan
                nodes: n1
                actual row count: 100
                KV time: 265µs
                KV contention time: 0µs
                KV rows decoded: 100
                KV bytes read: 5.1 KiB
                KV gRPC calls: 1
                estimated max memory allocated: 20 KiB
                sql cpu time: 23µs
                estimated row count: 100 (100% of the table; stats collected 32 seconds ago; using stats forecast for 36 seconds in the future)
                table: zpool@zpool_pkey
                spans: FULL SCAN
(67 rows)


Time: 8ms total (execution 7ms / network 1ms)

root@[::1]:26257/defaultdb> explain analyze select zpool.id, total_size from zpool inner join lateral (select total_size from inv_zpool where id = zpool.id order by time_collected desc limit 1) as foo on true;
                                                                      info
-------------------------------------------------------------------------------------------------------------------------------------------------
  planning time: 670µs
  execution time: 11ms
  distribution: full
  vectorized: true
  rows decoded from KV: 10,100 (648 KiB, 2 gRPC calls)
  cumulative time spent in KV: 8ms
  maximum memory usage: 2.3 MiB
  network usage: 0 B (0 messages)
  sql cpu time: 3ms
  isolation level: serializable
  priority: normal
  quality of service: regular

  • distinct
  │ nodes: n1
  │ actual row count: 100
  │ estimated max memory allocated: 10 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 191µs
  │ estimated row count: 100
  │ distinct on: rowid
  │
  └── • sort
      │ nodes: n1
      │ actual row count: 10,000
      │ estimated max memory allocated: 1.6 MiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 2ms
      │ estimated row count: 10,000
      │ order: -time_collected
      │
      └── • hash join
          │ nodes: n1
          │ actual row count: 10,000
          │ estimated max memory allocated: 150 KiB
          │ estimated max sql temp disk usage: 0 B
          │ sql cpu time: 483µs
          │ estimated row count: 10,000
          │ equality: (id) = (id)
          │
          ├── • scan
          │     nodes: n1
          │     actual row count: 10,000
          │     KV time: 8ms
          │     KV contention time: 0µs
          │     KV rows decoded: 10,000
          │     KV bytes read: 643 KiB
          │     KV gRPC calls: 1
          │     estimated max memory allocated: 730 KiB
          │     sql cpu time: 905µs
          │     estimated row count: 10,000 (100% of the table; stats collected 14 seconds ago)
          │     table: inv_zpool@inv_zpool_pkey
          │     spans: FULL SCAN
          │
          └── • scan
                nodes: n1
                actual row count: 100
                KV time: 303µs
                KV contention time: 0µs
                KV rows decoded: 100
                KV bytes read: 5.1 KiB
                KV gRPC calls: 1
                estimated max memory allocated: 20 KiB
                sql cpu time: 22µs
                estimated row count: 100 (100% of the table; stats collected 44 seconds ago; using stats forecast for 24 seconds in the future)
                table: zpool@zpool_pkey
                spans: FULL SCAN
(67 rows)


Time: 13ms total (execution 12ms / network 1ms)
```

**Expected behavior**

If we do the same setup in Postgres and explain the same three queries, I believe it's making use of the index and does not need to full scan `inv_zpool`:

```
Unique (cost=0.29..776.06 rows=200 width=28) (actual time=0.008..12.473 rows=100 loops=1)
-> Index Scan using inv_zpool_by_id_and_time on inv_zpool (cost=0.29..749.23 rows=10730 width=28) (actual time=0.007..11.743 rows=10000 loops=1)

Nested Loop (cost=0.29..6243.64 rows=1850 width=20) (actual time=0.016..0.392 rows=100 loops=1)
-> Seq Scan on zpool (cost=0.00..28.50 rows=1850 width=16) (actual time=0.005..0.011 rows=100 loops=1)
-> Limit (cost=0.29..3.34 rows=1 width=12) (actual time=0.004..0.004 rows=1 loops=100)
-> Index Scan using inv_zpool_by_id_and_time on inv_zpool (cost=0.29..165.23 rows=54 width=12) (actual time=0.003..0.003 rows=1 loops=100)
Index Cond: (id = zpool.id)

Nested Loop (cost=0.29..6243.64 rows=1850 width=20) (actual time=0.012..0.307 rows=100 loops=1)
-> Seq Scan on zpool (cost=0.00..28.50 rows=1850 width=16) (actual time=0.004..0.010 rows=100 loops=1)
-> Limit (cost=0.29..3.34 rows=1 width=12) (actual time=0.003..0.003 rows=1 loops=100)
-> Index Scan using inv_zpool_by_id_and_time on inv_zpool (cost=0.29..165.23 rows=54 width=12) (actual time=0.002..0.002 rows=1 loops=100)
Index Cond: (id = zpool.id)
```

**Environment:**

We first observed this on illumos using a relatively old cockroach (v22.1.9), but the above reproduction output is all from using v23.2.2 on Linux.

**Additional context**

We're worried about queries that we think ought to be using indices failing to do so, and therefore running into more cockroach memory pressure at inopportune times. We've disabled full table scans, but that doesn't catch the above; CRDB is _able_ to use the index. We tried adding `inv_zpool@{NO_FULL_SCAN}`. The details vary, but in general this causes the query memory to go down and the execution time to go up, but it still results in a 10,000 row scan.

Jira issue: CRDB-36908

**Comment by yuzefovich** [comment] 2024-03-22 02:22
Thanks for filing the issue!

I haven't digested crux of your comment, but I can comment on `root: memory budget exceeded`: this error means that "root" SQL memory monitor reached its limit. That limit is specified by `--max-sql-memory` startup flag and is shared between all queries running on a particular node. How does `sql.mem.root.current` metric look like?

Apart from "global" limit, we have "local" operation-level limit controlled with `distsql_workmem` session variable - for example, once sort consumes more than 64MiB (default value of `distsql_workmem`), it spills to temporary disk storage in order to not exceed its workmem allowance. Not all SQL operations can spill to disk.

This all is to say that it's not necessarily the query you identified that consumed most of the "root" budget (you could also be right that it's this query that is the culprit). On later versions we have `crdb_internal.node_memory_monitors` table that exposes how the "root" budget is utilized on a particular node at any point time.

**Comment by jgallagher** [comment] 2024-03-22 02:45
Ah, sorry, I cut off part of the error. The initial errors we saw were of the flavor

```
unexpected database error: root: memory budget exceeded: 40960 bytes requested, 134190929 currently allocated, 134217728 bytes in budget
```

during a process that was invoking several copies of a set of related queries concurrently. We checked the logs for the execution times of all the successful queries, and focused on the very long running ones as suspects; that led to the query that led to this reproducer. When we ran it under `EXPLAIN ANALYZE`, it showed the very large full scan plus a max memory usage in the neighborhood of 30 MiB; we figured a handful of these running concurrently probably explained the memory pressure we were seeing. (Plus trimming the table in question back down to the size it should've been - from 250,000 rows down to ~600 - brought the queries time down and chased away the memory pressure errors.)

**Comment by michae2** [comment] 2024-03-26 23:09
Thanks for opening an issue, @jgallagher. The crux of the issue is that CRDB doesn't yet have a variant of lookup join that will read just a single row for each lookup (which is tracked by https://github.com/cockroachdb/cockroach/issues/62471).

To see what I mean, consider your last query with `inner lookup join lateral` instead of `inner join lateral`:

```
demo@127.0.0.1:26257/demoapp/defaultdb> explain analyze select zpool.id, total_size from zpool inner lookup join lateral (select total_size, random() from inv_zpool where id = zpool.id order by time_collected desc limit 1) as foo on true;
                                               info
--------------------------------------------------------------------------------------------------
  planning time: 288µs
  execution time: 102ms
  distribution: local
  vectorized: true
  rows decoded from KV: 20,100 (1.1 MiB, 5 gRPC calls)
  cumulative time spent in KV: 76ms
  maximum memory usage: 11 MiB
  network usage: 0 B (0 messages)
  regions: us-east1
  sql cpu time: 24ms
  estimated RUs consumed: 0
  isolation level: serializable
  priority: normal
  quality of service: regular

  • distinct
  │ nodes: n1
  │ regions: us-east1
  │ actual row count: 100
  │ estimated max memory allocated: 10 KiB
  │ estimated max sql temp disk usage: 0 B
  │ sql cpu time: 285µs
  │ estimated row count: 100
  │ distinct on: rowid
  │
  └── • sort
      │ nodes: n1
      │ regions: us-east1
      │ actual row count: 10,000
      │ estimated max memory allocated: 1.6 MiB
      │ estimated max sql temp disk usage: 0 B
      │ sql cpu time: 4ms
      │ estimated row count: 10,000
      │ order: -time_collected
      │
      └── • lookup join (streamer)
          │ nodes: n1
          │ regions: us-east1
          │ actual row count: 10,000
          │ KV time: 62ms
          │ KV contention time: 0µs
          │ KV rows decoded: 10,000
          │ KV bytes read: 487 KiB
          │ KV gRPC calls: 2
          │ estimated max memory allocated: 11 MiB
          │ sql cpu time: 15ms
          │ estimated row count: 10,000
          │ table: inv_zpool@inv_zpool_pkey
          │ equality: (rowid) = (rowid)
          │ equality cols are key
          │
          └── • lookup join (streamer)
              │ nodes: n1
              │ regions: us-east1
              │ actual row count: 10,000
              │ KV time: 13ms
              │ KV contention time: 0µs
              │ KV rows decoded: 10,000
              │ KV bytes read: 655 KiB
              │ KV gRPC calls: 2
              │ estimated max memory allocated: 1.7 MiB
              │ sql cpu time: 5ms
              │ estimated row count: 10,000
              │ table: inv_zpool@inv_zpool_by_id_and_time
              │ equality: (id) = (id)
              │
              └── • scan
                    nodes: n1
                    regions: us-east1
                    actual row count: 100
                    KV time: 1ms
                    KV contention time: 0µs
                    KV rows decoded: 100
                    KV bytes read: 5.3 KiB
                    KV gRPC calls: 1
                    estimated max memory allocated: 20 KiB
                    sql cpu time: 46µs
                    estimated row count: 100 (100% of the table; stats collected 47 minutes ago)
                    table: zpool@zpool_pkey
                    spans: FULL SCAN
(80 rows)

Time: 103ms total (execution 103ms / network 1ms)
```

If CRDB had a single-row-reading variant of lookup join, the innermost lookup join would be much like the revscan with limit 1 in the single ID plan. But because we don't, the innermost lookup join has to read _all_ rows with a given ID, and then we have to sort and distinct on top of that.

There's a hacky way we can get the revscan-with-limit-1 plan for each ID: we can add a volatile function call to `random()` and some other magic to prevent the optimizer from decorrelating the subquery. (Thanks to @mgartner for this trick.)

```
demo@127.0.0.1:26257/demoapp/defaultdb> EXPLAIN ANALYZE (VERBOSE)
                                     -> WITH n AS NOT MATERIALIZED (SELECT NULL AS m)
                                     -> SELECT zpool.id,
                                     ->   COALESCE(
                                     ->     (SELECT m FROM n),
                                     ->     (SELECT total_size + random()::int * 0 FROM inv_zpool WHERE id = zpool.id ORDER BY time_collected DESC LIMIT 1),
                                     ->     0
                                     ->   ) AS total_size
                                     -> FROM zpool;
                                         info
--------------------------------------------------------------------------------------
  planning time: 2ms
  execution time: 109ms
  distribution: local
  vectorized: true
  rows decoded from KV: 100 (5.3 KiB, 100 KVs, 1 gRPC calls)
  cumulative time spent in KV: 108ms
  maximum memory usage: 30 KiB
  network usage: 0 B (0 messages)
  regions: us-east1
  sql cpu time: 61ms
  estimated RUs consumed: 0
  isolation level: serializable
  priority: normal
  quality of service: regular

  • root
  │ columns: (id, total_size)
  │
  ├── • render
  │   │ columns: (id, total_size)
  │   │ render total_size: COALESCE(@S1::INT8, subquery(id), 0)
  │   │ render id: id
  │   │
  │   └── • scan
  │         columns: (id)
  │         nodes: n1
  │         regions: us-east1
  │         actual row count: 100
  │         vectorized batch count: 7
  │         KV time: 108ms
  │         KV contention time: 0µs
  │         KV rows decoded: 100
  │         KV pairs read: 100
  │         KV bytes read: 5.3 KiB
  │         KV gRPC calls: 1
  │         estimated max memory allocated: 20 KiB
  │         sql cpu time: 61ms
  │         MVCC step count (ext/int): 100/100
  │         MVCC seek count (ext/int): 1/1
  │         estimated row count: 100 (100% of the table; stats collected 1 hour ago)
  │         table: zpool@zpool_pkey
  │         spans: FULL SCAN
  │
  └── • subquery
      │ id: @S1
      │ original sql: (SELECT m FROM n)
      │ exec mode: one row
      │
      └── • values
            columns: (m)
            nodes: n1
            regions: us-east1
            actual row count: 1
            vectorized batch count: 1
            sql cpu time: 63µs
            size: 1 column, 1 row
            row 0, expr 0: NULL
(57 rows)

Time: 112ms total (execution 111ms / network 0ms)
```

The `EXPLAIN` output doesn't show it very well, but the `subquery(id)` in the `render` means we optimize and execute this subquery for each row in `zpool`: `(SELECT total_size + random()::int * 0 FROM inv_zpool WHERE id = zpool.id ORDER BY time_collected DESC LIMIT 1)`. When we optimize that subquery, it will get the same revscan plan from the single ID case.

Usually any plan that evaluates a subquery for every row is _much_ slower than reading extra rows, but it probably does use less memory.

**Comment by jgallagher** [comment] 2024-03-27 12:36
> There's a hacky way we can get the revscan-with-limit-1 plan for each ID: we can add a volatile function call to `random()` and some other magic to prevent the optimizer from decorrelating the subquery. (Thanks to @mgartner for this trick.)

Wow, nice! Thanks for this - we definitely would not have come up with it. Do you have any feeling for how fragile this might be? (E.g., I could see a reasonable change to the optimizer realizing that `random() * 0` is a no-op and removing it entirely, but maybe that's colored by thinking of this like a compiler optimizer.)

> Usually any plan that evaluates a subquery for every row is much slower than reading extra rows, but it probably does use less memory.

Agreed, but I think it depends on the table sizes, right? In the larger context that this reproducer came from, if our `zpool` table has `N` rows, we expect the `inv_zpool` table to have `M * N` rows. Under normal circumstances `M` is small (like, less than 5), in which case reading all `M * N` rows is definitely faster and also not prohibitively expensive in terms of memory. But we had a but where `M` was much larger than intended (1,000+); at that point the memory is prohibitively expensive, and I assume there is some value for `M` at which reading all the rows becomes slower than doing `N` lookups into the index on the `M*N` table.

**Comment by michae2** [comment] 2024-04-11 19:11
@jgallagher here's a less hacky way to do it using a UDF (again, thanks to @mgartner!):

```sql
CREATE FUNCTION most_recent_total_size(zpool_id uuid) RETURNS int AS $$
  SELECT total_size FROM inv_zpool WHERE id = zpool_id ORDER BY time_collected DESC LIMIT 1;
$$ LANGUAGE SQL;

SELECT id, most_recent_total_size(id) FROM zpool;
```

If it's alright with you, I'm going to go ahead and close this issue, since we have https://github.com/cockroachdb/cockroach/issues/62471 tracking the need for a per-lookup limit on lookup joins.

**Closed by michae2** 2024-04-11 19:11 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries
