### ISSUE TITLE
sql: a txn that runs a CREATE TABLE and doesn't commit will stall all of sql

### ISSUE THREAD

**Issue by vivekmenezes** [cockroachdb/cockroach#16824] opened 2017-06-30 19:15 UTC
this happens because the CREATE TABLE command creates an uncommitted name -> id mapping and a SQL command when attempting to lookup a name -> id runs a scan over the entire key space of the name -> id map.

One solution is to write the table descriptor and hand over writing the name -> id map to the schema changer so that the transaction that writes the map is internal to cockroach.

```
func TestOpenTxnOnCreateTable(t *testing.T) {
	defer leaktest.AfterTest(t)()
	params, _ := createTestServerParams()
	s, sqlDB, _ := serverutils.StartServer(t, params)
	defer s.Stopper().Stop(context.TODO())

	if _, err := sqlDB.Exec(`
CREATE DATABASE t;
CREATE TABLE t.kv (k CHAR PRIMARY KEY, v CHAR);
INSERT INTO t.kv VALUES ('a', 'b');
`); err != nil {
		t.Fatal(err)
	}

	tx, err := sqlDB.Begin()
	if err != nil {
		t.Fatal(err)
	}

	if _, err := tx.Exec(`
CREATE TABLE t.timestamp (k CHAR PRIMARY KEY, v CHAR);
`); err != nil {
		t.Fatal(err)
	}

	rows, err := sqlDB.Query(`SELECT * FROM t.kv`)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
}

```

**Comment by vivekmenezes** [comment] 2017-08-11 01:42
Yeah it does look like I misdiagnosed the issue. phew!

**Comment by justinj** [comment] 2017-08-14 13:01
Should I close this issue then? I don't think there's anything to do here.

**Comment by justinj** [comment] 2017-08-30 20:20
After discussion with Vivek, he thinks this test might reveal the issue if we remove the `INSERT` in the test above, I'll try that out and report back.

**Comment by justinj** [comment] 2017-09-05 18:53
I can't reproduce any issues with this test, so I'm going to close this issue for the time being.

**Closed by justinj** 2017-09-05 18:53 UTC
