### ISSUE TITLE
stability: data race in roachpb.Transaction

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#8794] opened 2016-08-24 13:56 UTC
build sha: 54be705

Data race (from `104.196.102.49`):
```
==================
WARNING: DATA RACE
Write at 0x00c47f0baed9 by goroutine 182:
  github.com/cockroachdb/cockroach/roachpb.(*Transaction).Update()
      /go/src/github.com/cockroachdb/cockroach/roachpb/data.go:863 +0x651
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:820 +0xe9e
  github.com/cockroachdb/cockroach/kv.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:591 +0x1a0
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:374 +0x5cf
  github.com/cockroachdb/cockroach/internal/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:52 +0x120
  github.com/cockroachdb/cockroach/internal/client.(*DB).send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:490 +0x2be
  github.com/cockroachdb/cockroach/internal/client.(*Txn).send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:675 +0x675
  github.com/cockroachdb/cockroach/internal/client.(*Txn).(github.com/cockroachdb/cockroach/internal/client.send)-fm()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:359 +0x7c
  github.com/cockroachdb/cockroach/internal/client.sendAndFill()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x1ab
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Run()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:359 +0xfd
  github.com/cockroachdb/cockroach/internal/client.runOneResult()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:517 +0x97
  github.com/cockroachdb/cockroach/internal/client.runOneRow()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:531 +0x6d
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Get()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:221 +0xfa
  github.com/cockroachdb/cockroach/sql.(*planner).getDescriptor()
      /go/src/github.com/cockroachdb/cockroach/sql/descriptor.go:180 +0xed
  github.com/cockroachdb/cockroach/sql.(*planner).getTableDesc()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:123 +0x293
  github.com/cockroachdb/cockroach/sql.(*planner).mustGetTableDesc()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:135 +0x46
  github.com/cockroachdb/cockroach/sql.(*planner).getTableLease()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:180 +0xcdd
  github.com/cockroachdb/cockroach/sql.(*planner).makeEditNode()
      /go/src/github.com/cockroachdb/cockroach/sql/update.go:43 +0x8b
  github.com/cockroachdb/cockroach/sql.(*planner).Delete()
      /go/src/github.com/cockroachdb/cockroach/sql/delete.go:55 +0x11b
  github.com/cockroachdb/cockroach/sql.(*planner).newPlan()
      /go/src/github.com/cockroachdb/cockroach/sql/plan.go:248 +0xeed
  github.com/cockroachdb/cockroach/sql.(*planner).makePlan()
      /go/src/github.com/cockroachdb/cockroach/sql/plan.go:212 +0x91
  github.com/cockroachdb/cockroach/sql.(*planner).query()
      /go/src/github.com/cockroachdb/cockroach/sql/planner.go:215 +0x14c
  github.com/cockroachdb/cockroach/sql.(*planner).exec()
      /go/src/github.com/cockroachdb/cockroach/sql/planner.go:243 +0x91
  github.com/cockroachdb/cockroach/sql.LeaseStore.Release.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:218 +0x2c3
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn.func1()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:454 +0x46
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:553 +0x230
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:455 +0x30e
  github.com/cockroachdb/cockroach/sql.LeaseStore.Release()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:227 +0x181
  github.com/cockroachdb/cockroach/sql.(*tableState).removeLease.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:740 +0xc1
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0xa2

Previous read at 0x00c47f0baed9 by goroutine 1427:
  github.com/cockroachdb/cockroach/roachpb.(*Transaction).MarshalTo()
      /go/src/github.com/cockroachdb/cockroach/roachpb/data.pb.go:966 +0xc14
  github.com/cockroachdb/cockroach/roachpb.(*Header).MarshalTo()
      /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:4287 +0x765
  github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).MarshalTo()
      /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:4338 +0x145
  github.com/cockroachdb/cockroach/roachpb.(*BatchRequest).Marshal()
      /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:4323 +0x91
  github.com/golang/protobuf/proto.Marshal()
      /go/src/github.com/golang/protobuf/proto/encode.go:233 +0xb5
  google.golang.org/grpc.protoCodec.Marshal()
      /go/src/google.golang.org/grpc/rpc_util.go:68 +0x8c
  google.golang.org/grpc.(*protoCodec).Marshal()
      <autogenerated>:22 +0x8b
  google.golang.org/grpc.encode()
      /go/src/google.golang.org/grpc/rpc_util.go:264 +0x495
  google.golang.org/grpc.sendRequest()
      /go/src/google.golang.org/grpc/call.go:97 +0x1ae
  google.golang.org/grpc.Invoke()
      /go/src/google.golang.org/grpc/call.go:185 +0x8e1
  github.com/cockroachdb/cockroach/roachpb.(*internalClient).Batch()
      /go/src/github.com/cockroachdb/cockroach/roachpb/api.pb.go:1476 +0x106
  github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext.func1()
      /go/src/github.com/cockroachdb/cockroach/kv/transport.go:180 +0x13f

Goroutine 182 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:232 +0xc9
  github.com/cockroachdb/cockroach/sql.(*tableState).removeLease()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:743 +0x1b6
  github.com/cockroachdb/cockroach/sql.(*tableState).releaseLeasesIfNotActive.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:634 +0x154
  github.com/cockroachdb/cockroach/sql.(*tableState).releaseLeasesIfNotActive()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:636 +0xc1
  github.com/cockroachdb/cockroach/sql.(*tableState).purgeOldLeases.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:787 +0x25f
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn.func1()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:454 +0x46
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:553 +0x230
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:455 +0x30e
  github.com/cockroachdb/cockroach/sql.(*tableState).purgeOldLeases()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:791 +0x33e
  github.com/cockroachdb/cockroach/sql.(*LeaseManager).RefreshLeases.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:1180 +0x9c5
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:187 +0x8a

Goroutine 1427 (running) created at:
  github.com/cockroachdb/cockroach/kv.(*grpcTransport).SendNext()
      /go/src/github.com/cockroachdb/cockroach/kv/transport.go:189 +0x2b6
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendToReplicas()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:1008 +0x3d1
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendRPC()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:364 +0x27b
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendSingleRange()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:480 +0x1d8
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk.func2()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:746 +0x2ea
  github.com/cockroachdb/cockroach/kv.(*DistSender).sendChunk()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:747 +0x55a
  github.com/cockroachdb/cockroach/kv.(*DistSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/dist_sender.go:591 +0x1a0
  github.com/cockroachdb/cockroach/kv.(*TxnCoordSender).Send()
      /go/src/github.com/cockroachdb/cockroach/kv/txn_coord_sender.go:374 +0x5cf
  github.com/cockroachdb/cockroach/internal/client.(*txnSender).Send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:52 +0x120
  github.com/cockroachdb/cockroach/internal/client.(*DB).send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:490 +0x2be
  github.com/cockroachdb/cockroach/internal/client.(*Txn).send()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:675 +0x675
  github.com/cockroachdb/cockroach/internal/client.(*Txn).(github.com/cockroachdb/cockroach/internal/client.send)-fm()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:359 +0x7c
  github.com/cockroachdb/cockroach/internal/client.sendAndFill()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:417 +0x1ab
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Run()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:359 +0xfd
  github.com/cockroachdb/cockroach/internal/client.runOneResult()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:517 +0x97
  github.com/cockroachdb/cockroach/internal/client.runOneRow()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:531 +0x6d
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Get()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:221 +0xfa
  github.com/cockroachdb/cockroach/sql.(*planner).getDescriptor()
      /go/src/github.com/cockroachdb/cockroach/sql/descriptor.go:180 +0xed
  github.com/cockroachdb/cockroach/sql.(*planner).getTableDesc()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:123 +0x293
  github.com/cockroachdb/cockroach/sql.(*planner).mustGetTableDesc()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:135 +0x46
  github.com/cockroachdb/cockroach/sql.(*planner).getTableLease()
      /go/src/github.com/cockroachdb/cockroach/sql/table.go:180 +0xcdd
  github.com/cockroachdb/cockroach/sql.(*planner).makeEditNode()
      /go/src/github.com/cockroachdb/cockroach/sql/update.go:43 +0x8b
  github.com/cockroachdb/cockroach/sql.(*planner).Delete()
      /go/src/github.com/cockroachdb/cockroach/sql/delete.go:55 +0x11b
  github.com/cockroachdb/cockroach/sql.(*planner).newPlan()
      /go/src/github.com/cockroachdb/cockroach/sql/plan.go:248 +0xeed
  github.com/cockroachdb/cockroach/sql.(*planner).makePlan()
      /go/src/github.com/cockroachdb/cockroach/sql/plan.go:212 +0x91
  github.com/cockroachdb/cockroach/sql.(*planner).query()
      /go/src/github.com/cockroachdb/cockroach/sql/planner.go:215 +0x14c
  github.com/cockroachdb/cockroach/sql.(*planner).exec()
      /go/src/github.com/cockroachdb/cockroach/sql/planner.go:243 +0x91
  github.com/cockroachdb/cockroach/sql.LeaseStore.Release.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:218 +0x2c3
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn.func1()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:454 +0x46
  github.com/cockroachdb/cockroach/internal/client.(*Txn).Exec()
      /go/src/github.com/cockroachdb/cockroach/internal/client/txn.go:553 +0x230
  github.com/cockroachdb/cockroach/internal/client.(*DB).Txn()
      /go/src/github.com/cockroachdb/cockroach/internal/client/db.go:455 +0x30e
  github.com/cockroachdb/cockroach/sql.LeaseStore.Release()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:227 +0x181
  github.com/cockroachdb/cockroach/sql.(*tableState).removeLease.func1()
      /go/src/github.com/cockroachdb/cockroach/sql/lease.go:740 +0xc1
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunAsyncTask.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:231 +0xa2
==================
```

**Comment by tschottdorf** [comment] 2016-08-24 15:18
dupe of #8020

**Closed by tschottdorf** 2016-08-24 15:18 UTC
