### ISSUE TITLE
stress: failed test in cockroach/util/timeutil/timeutil.test: TestMonotonicityCheck

### ISSUE THREAD

**Issue by mberhault** [cockroachdb/cockroach#5527] opened 2016-03-24 10:27 UTC
Binary: cockroach/static-tests.tar.gz sha: https://github.com/cockroachdb/cockroach/commits/a0621a77c4d629f3b6d84b299202b3b352491d76

Stress build found a failed test:

```
=== RUN   TestMonotonicityCheck
W160324 10:11:49.933402 util/timeutil/time.go:101  backward time jump detected: previously 2016-03-24 11:11:49.933402916 +0000 UTC, now 2016-03-24 11:11:49.933402916 +0000 UTC (offset 0)
W160324 10:11:49.933402 util/timeutil/time.go:101  backward time jump detected: previously 2016-03-24 11:11:49.933402916 +0000 UTC, now 2016-03-24 10:01:49.933402916 +0000 UTC (offset -1h10m0s)
--- FAIL: TestMonotonicityCheck (0.00s)
	time_monotonic_test.go:40: clock backward jump was not detected by the monotonicity checker (from 2016-03-24 11:11:49.933402916 +0000 UTC to 2016-03-24 10:01:49.933402916 +0000 UTC)
FAIL


ERROR: exit status 1
```

Run Details:

```
5661 runs so far, 0 failures, over 5s
11226 runs so far, 0 failures, over 10s
16682 runs so far, 0 failures, over 15s
22018 runs so far, 0 failures, over 20s
27206 runs so far, 0 failures, over 25s
32209 runs so far, 0 failures, over 30s
37117 runs so far, 0 failures, over 35s
41896 runs so far, 0 failures, over 40s
46479 runs so far, 0 failures, over 45s
51003 runs so far, 0 failures, over 50s
55478 runs so far, 0 failures, over 55s
59787 runs so far, 0 failures, over 1m0s
64057 runs so far, 0 failures, over 1m5s
68135 runs so far, 0 failures, over 1m10s
72099 runs so far, 0 failures, over 1m15s
75982 runs so far, 0 failures, over 1m20s
79798 runs so far, 0 failures, over 1m25s
83532 runs so far, 0 failures, over 1m30s
87146 runs so far, 0 failures, over 1m35s
90706 runs so far, 0 failures, over 1m40s
94211 runs so far, 0 failures, over 1m45s
97653 runs so far, 0 failures, over 1m50s
101062 runs so far, 0 failures, over 1m55s
104340 runs so far, 0 failures, over 2m0s
107574 runs so far, 0 failures, over 2m5s
110747 runs so far, 0 failures, over 2m10s
113879 runs so far, 0 failures, over 2m15s
117015 runs so far, 0 failures, over 2m20s
120053 runs so far, 0 failures, over 2m25s
123025 runs so far, 0 failures, over 2m30s
126045 runs so far, 0 failures, over 2m35s
128953 runs so far, 0 failures, over 2m40s
131865 runs so far, 0 failures, over 2m45s
134672 runs so far, 0 failures, over 2m50s
137473 runs so far, 0 failures, over 2m55s
140234 runs so far, 0 failures, over 3m0s
142979 runs so far, 0 failures, over 3m5s
145708 runs so far, 0 failures, over 3m10s
148398 runs so far, 0 failures, over 3m15s
151087 runs so far, 0 failures, over 3m20s
153732 runs so far, 0 failures, over 3m25s
156267 runs so far, 0 failures, over 3m30s
158842 runs so far, 0 failures, over 3m35s
161411 runs so far, 0 failures, over 3m40s
163897 runs so far, 0 failures, over 3m45s
166432 runs so far, 0 failures, over 3m50s
168808 runs so far, 0 failures, over 3m55s
171208 runs so far, 0 failures, over 4m0s
173612 runs so far, 0 failures, over 4m5s
175935 runs so far, 0 failures, over 4m10s
178279 runs so far, 0 failures, over 4m15s
180586 runs so far, 0 failures, over 4m20s
182859 runs so far, 0 failures, over 4m25s
185218 runs so far, 0 failures, over 4m30s
187479 runs so far, 0 failures, over 4m35s
189693 runs so far, 0 failures, over 4m40s
191926 runs so far, 0 failures, over 4m45s
194164 runs so far, 0 failures, over 4m50s
196356 runs so far, 0 failures, over 4m55s
198583 runs so far, 0 failures, over 5m0s
200783 runs so far, 0 failures, over 5m5s
202932 runs so far, 0 failures, over 5m10s
205078 runs so far, 0 failures, over 5m15s
207210 runs so far, 0 failures, over 5m20s
209317 runs so far, 0 failures, over 5m25s
211362 runs so far, 0 failures, over 5m30s
213475 runs so far, 0 failures, over 5m35s
215567 runs so far, 0 failures, over 5m40s
217595 runs so far, 0 failures, over 5m45s
219591 runs so far, 0 failures, over 5m50s
221635 runs so far, 0 failures, over 5m55s
223703 runs so far, 0 failures, over 6m0s
225729 runs so far, 0 failures, over 6m5s
227721 runs so far, 0 failures, over 6m10s
229632 runs so far, 0 failures, over 6m15s
231606 runs so far, 0 failures, over 6m20s
233579 runs so far, 0 failures, over 6m25s
235571 runs so far, 0 failures, over 6m30s
237522 runs so far, 0 failures, over 6m35s
239458 runs so far, 0 failures, over 6m40s
241420 runs so far, 0 failures, over 6m45s
243348 runs so far, 0 failures, over 6m50s
245273 runs so far, 0 failures, over 6m55s
247078 runs so far, 0 failures, over 7m0s
248984 runs so far, 0 failures, over 7m5s
250940 runs so far, 0 failures, over 7m10s
252808 runs so far, 0 failures, over 7m15s
254637 runs so far, 0 failures, over 7m20s
256372 runs so far, 0 failures, over 7m25s
258223 runs so far, 0 failures, over 7m30s
260096 runs so far, 0 failures, over 7m35s
261964 runs so far, 0 failures, over 7m40s
263768 runs so far, 0 failures, over 7m45s
265545 runs so far, 0 failures, over 7m50s
267288 runs so far, 0 failures, over 7m55s
268326 runs completed, 1 failures, over 7m59s
FAIL
```
Please assign, take a look and update the issue accordingly.

**Comment by RaduBerinde** [comment] 2016-03-24 15:33
@knz - I saw #5522 moves around that test, not sure if the change is related though

**Comment by knz** [comment] 2016-03-24 19:54
I think this is fixed by #5522 / #5541. How can I verify this?

**Comment by RaduBerinde** [comment] 2016-03-24 20:07
I would verify using `make stress pkg=./whatever TESTS=TestMonotonicityCheck` and let it run for 15-30m.

**Comment by knz** [comment] 2016-03-24 20:49
Done. The test doesn't fail any more. Closing this tentatively.

**Comment by knz** [comment] 2016-03-24 20:50
Closing #5527 via #5522 and #5541.

**Closed by knz** 2016-03-24 20:50 UTC
Labels: Robot, test-failure

**Comment by tschottdorf** [comment] 2016-03-24 21:22
Does "any more" imply that you checked it with a commit before #5522 && #5541 and **were** able to repro it? Often things fail in CircleCI but only very rarely or never locally.

**Comment by knz** [comment] 2016-03-24 23:02
I do not understand your question. I said I was not able to repro locally even when running for very long, much longer than the 15mn advised by Radu. Do you want to suggest how I could investigate this further? I blame the original failure on the fact the test was timing-dependent (and thus inherently flaky) and the new code uses a manual clock which always deterministically shifts regardless of system load.

**Comment by tschottdorf** [comment] 2016-03-24 23:09
The question was whether you were ever able to reproduce it locally at a commit which precedes those which you suspect fixed the issue. Otherwise it might just be one of those bugs that only ever happens on those crazy CircleCI machines.
If you have reasonable suspicion that this was fixed I wouldn't investigate further (after all, if it does happen again, we'll see a new issue), I'm just pointing out for future investigations that it can occasionally be hard to reproduce failures on CircleCI locally, and that the only way to be "certain" is to have it fail locally at one commit, and running way longer at a later commit.
Sometimes passing `TESTFLAGS=-p 16`, or using `stressrace` can tickle bugs when vanilla `make stress` doesn't want to fail.

**Comment by knz** [comment] 2016-03-25 15:12
Thanks for the testing tips! I will use this further next time.
As I explained in this case I have reasonable suspicion the problem is fixed (cf. comment on the determinism of the test).
