### ISSUE TITLE
cmd: TestExtractEpicIDs is flaky

### ISSUE THREAD

**Issue by rafiss** [cockroachdb/cockroach#110684] opened 2023-09-14 21:24 UTC
failed at https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/11784678?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

```
Failed
=== RUN   TestExtractEpicIDs/lots_of_variations_epic:_CRDB-9234._epic_CRDB-235,_DOC-6883;___DEVINF-392_https://cockroachlabs.atlassian.net/browse/CRDB-28708_Release_note_(sql_change):_Import_now_checks_readability...
    docs_issue_generation_test.go:3099:
          Error Trace:  github.com/cockroachdb/cockroach/pkg/cmd/docs-issue-generation/docs_issue_generation_test.go:3099
          Error:        Not equal:
                        expected: map[string]int{"CRDB-18955":1, "CRDB-235":1, "DOC-6883":1}
                        actual  : map[string]int{"CRDB-235":1, "DOC-6883":1}
                        Diff:
                        --- Expected
                        +++ Actual
                        @@ -1,3 +1,2 @@
                        -(map[string]int) (len=3) {
                        - (string) (len=10) "CRDB-18955": (int) 1,
                        +(map[string]int) (len=2) {
                          (string) (len=8) "CRDB-235": (int) 1,
          Test:         TestExtractEpicIDs/lots_of_variations_epic:_CRDB-9234._epic_CRDB-235,_DOC-6883;___DEVINF-392_https://cockroachlabs.atlassian.net/browse/CRDB-28708_Release_note_(sql_change):_Import_now_checks_readability...
    --- FAIL: TestExtractEpicIDs/lots_of_variations_epic:_CRDB-9234._epic_CRDB-235,_DOC-6883;___DEVINF-392_https://cockroachlabs.atlassian.net/browse/CRDB-28708_Release_note_(sql_change):_Import_now_checks_readability... (0.00s)
```

Jira issue: CRDB-31556

**Comment by jlinder** [comment] 2023-09-20 15:12
This is a duplicate of https://github.com/cockroachdb/cockroach/issues/110682, which is fixed.

**Closed by jlinder** 2023-09-20 15:12 UTC
Labels: C-test-failure, T-dev-inf
