### ISSUE TITLE
cdc: regression in `resolved` behavior in v22.1.0

### ISSUE THREAD

**Issue by jakedt** [cockroachdb/cockroach#93168] opened 2022-12-06 22:09 UTC
**Describe the problem**

At SpiceDB, we use `EXPERIMENTAL CHANGEFEED` to power our Watch API. When we attempted to update the version of CRDB that we test against our watch tests started failing. After bisecting across all releases of CRDB it appears this change/regression was introduced in v22.1.0. It appears that the `resolved` parameters is not respected, and we are getting resolved events every `30s` now, instead of the specified `1s`. The SQL command that we send to initiate the changefeed is here:

https://github.com/authzed/spicedb/blob/77fded3b72594c7b62da66f9b10ee0816c4ab499/internal/datastore/crdb/watch.go#L16

**To Reproduce**

To reproduce you can run one of the test cases in our watch test suite with the following command on a machine with Docker:

`go test . -tags ci,docker -run "TestCRDBDatastore/TestWatch/1"`

**Expected behavior**

We expect to get resolved events every ~1s, and instead our test times out because we aren't getting them until ~30s.

**Additional data / screenshots**

N/A

**Environment:**
 - CockroachDB version v22.1.0 - 22.2.0
 - Server OS: all
 - Client app: pgx from golang

**Additional context**

Our Watch API is broken on the most recent releases of CockroachDB, preventing us from upgrading.

Jira issue: CRDB-22199

**Comment by miretskiy** [comment] 2022-12-06 23:00
Please try specifying `min_checkpoint_frequency` option.  It's default is 30s, so that's probably what you're experiencing.

**Comment by jakedt** [comment] 2022-12-06 23:13
That doesn't appear to be a documented option for `EXPERIMENTAL CHANGEFEED FOR`:

https://www.cockroachlabs.com/docs/v22.2/changefeed-for

It _did_ however have the intended effect and our perf is back to what it was in v21.1.X.

**Comment by miretskiy** [comment] 2022-12-07 00:15
First, please accept my apologies -- the rollout of that option was not done
correctly; I will follow up w/ docs team to make sure we document this behavior change.

Secondly, I'm glad that the option had intended behavior.

**Comment by miretskiy** [comment] 2022-12-07 00:17
On an unrelated note: you do not need to use "experimental" keyword, I believe you can simply
omit the sink argument `CREATE CHANGEFEED FOR x WITH ...`
Also, I'm glad you're giving 22.2 a try; it has lots of new features, including cdc transformations.

**Comment by miretskiy** [comment] 2022-12-07 14:49
@hatheri

**Comment by miretskiy** [comment] 2022-12-07 14:51
@kathancox 
When we introduced `min_checkpoint_frequency`, we screwed up a bit, mostly
by not calling out that this change might be surprising in that it will slow resolved messages
down to be at least 30seconds (used to be 5s or whatever resolved option was set to).
I want to make sure we have a callout in the docs about that.
Still, I think the change to intro this option was a good change -- it's just we should not
surprise our users.

**Comment by kathancox** [comment] 2022-12-07 14:57
Ack @miretskiy I have created a docs issue for this and will start work on the updates this week.

**Comment by amruss** [comment] 2022-12-21 18:58
Closing this issues in favor of the docs issue @kathancox can you link it here?

**Closed by amruss** 2022-12-21 18:58 UTC
Labels: C-bug, O-community, A-cdc, X-blathers-triaged, T-cdc

**Comment by kathancox** [comment] 2022-12-21 19:00
Here is the docs issue that is complete: https://cockroachlabs.atlassian.net/browse/DOC-6321
