### ISSUE TITLE
ui: statements page: Pass sort order as query parameters to persist sort state

### ISSUE THREAD

**Issue by piyush-singh** [cockroachdb/cockroach#29312] opened 2018-08-29 21:22 UTC
When reloading the Statements page or navigating back from the Statements details page, users lose their sort order since we are not tracking that anywhere. Instead, users should see the page in the state in which they last left it.

**Comment by irfansharif** [comment] 2020-03-23 18:17
Duplicate of #45404.

**Closed by irfansharif** 2020-03-23 18:17 UTC
Labels: A-webui-routing, C-cleanup, S-3-ux-surprise
