### ISSUE TITLE
Import Data continues with a crashed node

### ISSUE THREAD

**Issue by drewdeally** [cockroachdb/cockroach#35417] opened 2019-03-05 12:47 UTC
**Describe the problem**
Import Table results in a failed node with OOM

**To Reproduce**

```

1. roachporod GCE 3 nodes n1-highcpu-4 with SSD
2.
#
root@localhost:26257/defaultdb> IMPORT TABLE skusv2  (id UUID PRIMARY KEY, skujson JSONB, masterskuid UUID, createdby UUID, createddate STRING, lastsavedby UUID, lastsaveddate STRING, isdeleted BOOL, availabilityjson JSONB, quantityjson JSONB) CSV DATA ('nodelocal:///XClean_SkusV2_full_export10.csv.gz') WITH decompress = 'gzip', "nullif" = '', skip = '1';
        job_id       |  status   | fraction_completed |  rows  | index_entries | system_records |   bytes     
+--------------------+-----------+--------------------+--------+---------------+----------------+------------+
  431612000220086274 | succeeded |                  1 | 166490 |             0 |              0 | 6302980232  
(1 row)

Time: 3m45.542554575s

root@localhost:26257/defaultdb> \q

Stats kicked off.

3. Logs attached before and after restarting failed node

4. ERROR node 1 log
 I190305 12:15:48.651439 216 server/status/runtime.go:464  [n1] runtime stats: 2.3 GiB RSS, 201 goroutines, 275 MiB/1.8 GiB/2.2 GiB GO alloc/idle/total, 110 MiB/134 MiB CGO alloc/total, 8051.0 CGO/sec, 214.6/26.7 %(u/s)time, 0.1 %gc (23x), 385 MiB/542 MiB (r/w)net
I190305 12:15:58.652340 216 server/status/runtime.go:464  [n1] runtime stats: 2.2 GiB RSS, 192 goroutines, 257 MiB/1.9 GiB/2.2 GiB GO alloc/idle/total, 62 MiB/85 MiB CGO alloc/total, 10362.3 CGO/sec, 47.2/16.1 %(u/s)time, 0.1 %gc (15x), 438 MiB/172 MiB (r/w)net
I190305 12:16:08.653396 216 server/status/runtime.go:464  [n1] runtime stats: 2.4 GiB RSS, 193 goroutines, 276 MiB/1.8 GiB/2.2 GiB GO alloc/idle/total, 250 MiB/284 MiB CGO alloc/total, 577.8 CGO/sec, 6.5/1.5 %(u/s)time, 0.0 %gc (0x), 311 KiB/339 KiB (r/w)net
I190305 12:16:18.262030 212 gossip/gossip.go:557  [n1] gossip status (ok, 3 nodes)
gossip client (0/3 cur/max conns)
gossip server (2/3 cur/max conns, infos 5241/2159 sent/received, bytes 1146009B/473785B sent/received)
  2: drew-cluster-three-0003:26257 (12m0s)
  3: drew-cluster-three-0002:26257 (12m0s)
I190305 12:16:18.654223 216 server/status/runtime.go:464  [n1] runtime stats: 2.7 GiB RSS, 197 goroutines, 258 MiB/1.9 GiB/2.2 GiB GO alloc/idle/total, 575 MiB/630 MiB CGO alloc/total, 962.7 CGO/sec, 11.9/2.4 %(u/s)time, 0.0 %gc (1x), 39 MiB/489 KiB (r/w)net
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x3183481, 0x16)
        /usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc0a0000000, 0x4000000, 0x59c6038)```

**Expected behavior**
Nodes should not go down - unless this import requires a larger memory footprint

**Additional data / screenshots**
Also noticed HIGH cpu
![image](https://user-images.githubusercontent.com/39496073/53806382-d4004d80-3f1a-11e9-89ee-231359b0ad17.png)


[debug.zip](https://github.com/cockroachdb/cockroach/files/2930931/debug.zip)
[2.cockroach.log](https://github.com/cockroachdb/cockroach/files/2930933/2.cockroach.log)
[3.cockroach.log](https://github.com/cockroachdb/cockroach/files/2930934/3.cockroach.log)
[1.cockroach.log](https://github.com/cockroachdb/cockroach/files/2930935/1.cockroach.log)

Build Tag:    v19.1.0-beta.20190225
Build Time:   2019/02/19 22:44:03
Distribution: CCL
Platform:     linux amd64 (x86_64-unknown-linux-gnu)
Go Version:   go1.11.4
C Compiler:   gcc 6.3.0
Build SHA-1:  763e90b043b5d732856d3ecf1d7b0d6aa33e3b26
Build Type:   release

**Comment by drewdeally** [comment] 2019-03-05 13:22
2nd node crash no activity 

[cockroach.log](https://github.com/cockroachdb/cockroach/files/2931075/cockroach.log)

**Comment by awoods187** [comment] 2019-03-05 13:44
@tbg is this a stability problem or should it be routed to import?

**Comment by nvanbenschoten** [comment] 2019-03-06 07:41
```
F190305 13:16:40.508818 5541 server/server_engine_health.go:54  [n1] disk stall detected: unable to write to <no-attributes>=/mnt/data1/cockroach within 10s
```

The node crashed because it detected a stall in its ability to write to its disk. The current thinking is that we're being a little overly aggressive here. @tbg should confirm, but I believe we're planning on doing something about this for 19.1. Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/34224.

**Closed by nvanbenschoten** 2019-03-06 07:41 UTC
Labels: C-bug, S-1-stability
