### ISSUE TITLE
TestMerge failure

### ISSUE THREAD

**Issue by tschottdorf** [cockroachdb/cockroach#3555] opened 2015-12-30 12:10 UTC
https://circleci.com/gh/cockroachdb/cockroach/10438

Haven't investigated, but this looks new.

```
error

        I1230 11:52:42.958787 923 raft/raft.go:446  [group 1] 1 became follower at term 5
I1230 11:52:42.958940 923 raft/raft.go:234  [group 1] newRaft 1 [peers: [1], term: 5, commit: 10, applied: 10, lastindex: 10, lastterm: 5]
I1230 11:52:42.959006 923 raft/raft.go:526  [group 1] 1 is starting a new election at term 5
I1230 11:52:42.959076 923 raft/raft.go:459  [group 1] 1 became candidate at term 6
I1230 11:52:42.959135 923 raft/raft.go:508  [group 1] 1 received vote from 1 at term 6
I1230 11:52:42.959221 923 raft/raft.go:487  [group 1] 1 became leader at term 6
I1230 11:52:42.961669 923 storage/replica.go:1554  gossiping cluster id test from store 1, range 1
I1230 11:52:42.963643 923 storage/replica_command.go:1208  range 1: new leader lease replica {1 1 1} 1970-01-01 00:00:00 +0000 UTC +1.000s
I1230 11:52:42.963833 923 storage/replica.go:1614  gossiping system config from store 1, range 1
I1230 11:52:42.964458 923 storage/replica.go:1563  gossiping sentinel from store 1, range 1
I1230 11:52:42.964690 923 storage/replica.go:1569  gossiping first range from store 1, range 1
I1230 11:52:42.965454 923 storage/replica.go:1120  reproposing 1 commands after empty entry
I1230 11:52:42.969581 923 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
	replica_test.go:2732: Get did not return expected value: aabcd != abcd
```

**Comment by bdarnell** [comment] 2015-12-31 16:52
This bug is not present in `master`; it's new in #3528.

**Comment by bdarnell** [comment] 2015-12-31 17:45
I spoke too soon. The test failure is not reproducible on `master`, but the underlying issue has been there since the beginning. We generally rely on MVCC (and the monotonicity of timestamps) to ensure that commands that get duplicated within raft don't produce incorrect results (especially for non-idempotent commands like `Increment`), but `Merge` does not use timestamps. If a `Merge` command is replayed by raft we may get incorrect results as seen here.

We need to either build replay protection into raft for all non-idempotent, non-MVCC commands (Is `Merge` the only one? I had a TODO comment in multiraft to do this for membership changes but I think that's actually safe for various other reasons), or incorporate timestamps into `Merge` so it can use the same mechanisms as other commands. Either way, we need to persist additional information at least temporarily to guard against replays, which might conflict with the efficiency goals of `Merge`.  

We could also try to attack this from the other side by preventing raft from replaying (some) commands, although this was tricky last time we looked at it.

**Comment by petermattis** [comment] 2015-12-31 18:35
Could we make Merge operations idempotent at the MVCC level by including
some sort of ID in the value and then not applying the merge if the ID is
already present? Not sure what the ID would be. Perhaps the timestamp when
the op entered raft.

**Comment by tschottdorf** [comment] 2016-01-05 14:38
Keeping consistent state on what has already been applied will be tricky (or at least annoying). With time series (our only user of Merge as far as I'm aware), it feels like the right thing to do is to relax guarantees. That doesn't really work cleanly right now because we either have no replication or full-blown Raft replication, but giving full replay protection (including guaranteed consistency of all replicas) may just be too much. There are alternatives which eliminate replays at the expense of (presumably very rare) retryable errors. For example, if a command is proposed at the leader, the log position at which it is proposed could be made a prerequisite for the execution of the command. By that, the second execution turns into a Noop (since it can't be at the right log position). The price is that some requests which never execute at their predetermined position must retry, but this should be rare and limited to leadership/config changes. There are also some issues related to forwarding (and I'm sure there's more). We should figure out the desired semantics for time series' storage and then a solution (which may well be: working around until we use this feature more).

**Comment by bdarnell** [comment] 2016-01-05 19:37
Relaxing the guarantees for `Merge` would be risky, because the time series are part of how you understand what happened when something goes wrong. Does that spike in the graph represent the cause of your problem, or is it the bogus result of a bunch Merge operations that got replayed after a leader election? On the other hand, some data points will inevitably be lost when a node fails, so maybe it's OK to provide relaxed guarantees here (probably best to lean towards losing data rather than duplicating it)

**Comment by tschottdorf** [comment] 2016-01-06 10:58
Yes, I would also prefer losing data in those cases. For now, my vote is to work around the issue (I suppose all tests which are flaky due to this should just retry a couple of times for the right result) and come up with a sound solution when we really need it. What do you think?

**Comment by mrtracy** [comment] 2016-01-06 19:10
Time series are already designed to work with both missing AND duplicated data.  If the same time series sample gets merged twice, that will not effect the quality of the time series data at all.  So if the only user of Merge is TimeSeries, then we are in fact safe here.

**Comment by bdarnell** [comment] 2016-01-06 19:23
When there is a raft election, any commands which were pending at that time will get replayed, so replays will tend to come in bursts.

**Comment by tschottdorf** [comment] 2016-01-08 13:43
`TestStoreTimeSeries` now belongs to this issue (I closed the original to declutter).

**Comment by tschottdorf** [comment] 2016-01-12 11:23
@mrtracy what we would be seeing would be a "bias" towards the duplicated values, right? In particular, assuming that we hit a large replay, the data duplicated would tend to be average, and if we hit a small replay, it won't have a very large effect as well since it doesn't add too much on the counts side.

If that's how it is, I would feel comfortable (at least for now) fixing up the tests to tolerate replays (or avoiding them during the test in some way, perhaps by waiting for the election). What do you (two) think?

**Comment by bdarnell** [comment] 2016-01-12 19:38
Yeah, for now we should just fix up the tests to work without replay protection. We can see if it ever becomes a problem in practice.

**Closed** 2016-01-14 15:35 UTC
Labels: test-disabled, test-failure, TestPollSource, TestQuery, TestStoreTimeSeries
