### ISSUE TITLE
ORDER BY clause does not take effect without reporting any error

### ISSUE THREAD

**Issue by sayJason** [cockroachdb/cockroach#97451] opened 2023-02-22 07:40 UTC
**Describe the problem**

Please describe the issue you observed, and any steps we can take to reproduce it:

**To Reproduce**

I start CockroachDB v22.2.0 with a single node.

I try the following statements, in which the ORDER BY clause is expected to generate an error. Because the function TO_IP takes an invalid argument.
```SQL
CREATE TABLE t1 (c0 BYTES AS ('a') STORED);
INSERT INTO t1 (rowid) VALUES(1), (2);
SELECT c0 FROM t1 ORDER BY (t1.c0 < ANY (t1.c0, TO_IP('1777767583'))) ASC; -- expect to see an error in order by
EXPLAIN SELECT c0 FROM t1 ORDER BY (t1.c0 < ANY (t1.c0, TO_IP('1777767583'))) ASC;
         info
-----------------------
  distribution: local
  vectorized: true

  • scan
    missing stats
    table: t1@t1_pkey
    spans: FULL SCAN
```

**Expected behavior**
The SELECT statement should return an error.

**Environment:**
 - CockroachDB version v22.2.0
 - Server OS: Ubuntu 22.04 LTS
 - Client app CockroachDB sql

Jira issue: CRDB-24705

**Comment by mgartner** [comment] 2023-02-28 21:22
Thanks for the report!

For the same reasons I outlined in https://github.com/cockroachdb/cockroach/issues/97446#issuecomment-1448899698, this is valid and expected behavior.

In the expressions `ORDER BY (t1.c0 < ANY (t1.c0, TO_IP('1777767583')))`, `t1.c0` is actually a constant because it is a computed column with a constant expression. The optimizer correctly determines that because `t1.c0` is a constant, and there are no other variables in the `ORDER BY` clause, that the `ORDER BY` is a no-op that can be entirely omitted without changing the semantics of the query.

I'm going to close this as it is expected behavior.

**Closed by mgartner** 2023-02-28 21:22 UTC
Labels: C-bug, O-community, X-blathers-triaged, T-sql-queries
