### ISSUE TITLE
`cockroach node status` shows incorrect nodes as decommissioned

### ISSUE THREAD

**Issue by tim-o** [cockroachdb/cockroach#29308] opened 2018-08-29 20:34 UTC
Reported by user fat0 on the [forum](https://forum.cockroachlabs.com/t/inconsistent-is-live-node-status-after-decomissioning-a-node/1970).

**BUG REPORT**

Please describe the issue you observed, and any steps we can take to reproduce it:

- Which version of CockroachDB are you using?
v 2.0.4
- What did you do?

decommissioned node 3: `root@ip-10-207-52-213:~# cockroach node decommission 3 --wait=live --certs-dir=/cockroach/certs --host="${IP}" --port=11400`
- What did you expect to see?

Node 3 as decommissioned when running `cockroach node status`

- What did you see instead?

Node 4 showing as decommissioned:
```
root@ip-10-207-52-213:~# echo $IP
10.207.52.213

root@ip-10-207-52-213:~# cockroach node status --certs-dir=/cockroach/certs --host="${IP}" --port=11400
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  1 | 10.207.52.213:11400  | v2.0.4 | 2018-08-29 18:24:16 | 2018-08-29 17:40:34 | true    |
|  2 | 10.207.37.230:11400  | v2.0.4 | 2018-08-29 18:24:19 | 2018-08-29 16:12:49 | true    |
|  4 | 10.187.107.240:11400 | v2.0.4 | 2018-08-29 18:24:18 | 2018-08-29 16:15:38 | false   |
|  5 | 10.187.108.184:11400 | v2.0.4 | 2018-08-29 18:24:21 | 2018-08-29 16:15:41 | true    |
|  6 | 10.187.104.243:11400 | v2.0.4 | 2018-08-29 18:24:18 | 2018-08-29 16:16:08 | true    |
|  7 | 10.207.44.157:11400  | v2.0.4 | 2018-08-29 18:24:16 | 2018-08-29 18:22:46 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(6 rows)
```
However, not when running `cockroach node status --decommission`:
```
root@ip-10-207-52-213:~# cockroach node status --decommission --certs-dir=/cockroach/certs --host="${IP}" --port=11400
+----+----------------------+--------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
| id |       address        | build  |     updated_at      |     started_at      | is_live | gossiped_replicas | is_decommissioning | is_draining |
+----+----------------------+--------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
|  1 | 10.207.52.213:11400  | v2.0.4 | 2018-08-29 18:24:26 | 2018-08-29 17:40:34 |    true |        22         |              false |    false    |
|  2 | 10.207.37.230:11400  | v2.0.4 | 2018-08-29 18:24:29 | 2018-08-29 16:12:49 |    true |        22         |              false |    false    |
|  3 | 10.207.42.36:11400   | v2.0.4 | 2018-08-29 18:20:39 | 2018-08-29 16:12:49 |   false |         0         |               true |    true     |
|  4 | 10.187.107.240:11400 | v2.0.4 | 2018-08-29 18:24:28 | 2018-08-29 16:15:38 |    true |        22         |              false |    false    |
|  5 | 10.187.108.184:11400 | v2.0.4 | 2018-08-29 18:24:31 | 2018-08-29 16:15:41 |    true |        22         |              false |    false    |
|  6 | 10.187.104.243:11400 | v2.0.4 | 2018-08-29 18:24:28 | 2018-08-29 16:16:08 |    true |        22         |              false |    false    |
|  7 | 10.207.44.157:11400  | v2.0.4 | 2018-08-29 18:24:26 | 2018-08-29 18:22:46 |    true |         0         |              false |    false    |
+----+----------------------+--------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
(7 rows)
```

And not when running status on node 4 directly:
```
root@ip-10-207-52-213:~# cockroach node status 4 --certs-dir=/cockroach/certs --host="${IP}" --port=11400
+----+----------------------+--------+---------------------+---------------------+---------+
| id |       address        | build  |     updated_at      |     started_at      | is_live |
+----+----------------------+--------+---------------------+---------------------+---------+
|  4 | 10.187.107.240:11400 | v2.0.4 | 2018-08-29 19:16:21 | 2018-08-29 19:04:00 | true    |
+----+----------------------+--------+---------------------+---------------------+---------+
(1 row)
```

- What was the impact?
Confusing UX.

**Comment by tschottdorf** [comment] 2018-08-30 13:39
This is likely https://github.com/cockroachdb/cockroach/pull/27808 (which unfortunately missed adding a release note). Please retry on v2.0.5.

**Comment by fat0** [comment] 2018-09-11 20:51
Retried on v2.0.5, issue remains the same as per [forum](https://forum.cockroachlabs.com/t/inconsistent-is-live-node-status-after-decomissioning-a-node/1970/4)

**Comment by tim-o** [comment] 2018-09-17 17:09
@tschottdorf - is there any info @fat0 or I need to provide to help move this forward given that it's still an issue in 2.0.5?

**Comment by tschottdorf** [comment] 2018-09-20 19:09
@tim-o no additional information needed. I'm fairly sure that this is fixed in 2.1, but the code on 2.0 is different. It will likely be obvious once we take a look.

**Comment by tschottdorf** [comment] 2018-09-26 12:19
@fat0 I took a first look through the code, but nothing stood out at me. Just to double check, when you say you tested this against v2.0.5, you also also upgraded the client-side binary to v2.0.5, right (i.e. the one you use to run `cockroach node status`)? I'll try to repro this directly in an example.

**Comment by tschottdorf** [comment] 2018-09-26 12:27
I can't reproduce this:

```
[tschottdorf@toblerone cockroach (release-2.0)]$ ./cockroach node status --insecure --decommission
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
| id |          address          |            build            |     updated_at      |     started_at      | is_live | gossiped_replicas | is_decommissioning | is_draining |
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
|  1 | toblerone.fritz.box:26257 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:03 | 2018-09-26 12:23:33 |    true |        15         |              false |    false    |
|  2 | toblerone.fritz.box:26259 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:04 | 2018-09-26 12:23:44 |    true |        16         |              false |    false    |
|  3 | toblerone.fritz.box:26261 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:24:05 | 2018-09-26 12:23:45 |   false |         0         |               true |    false    |
|  4 | toblerone.fritz.box:26263 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:05 | 2018-09-26 12:23:45 |    true |        16         |              false |    false    |
|  5 | toblerone.fritz.box:26265 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:06 | 2018-09-26 12:23:46 |    true |        16         |              false |    false    |
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+-------------------+--------------------+-------------+
(5 rows)
[tschottdorf@toblerone cockroach (release-2.0)]$ ./cockroach node status --insecure
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+
| id |          address          |            build            |     updated_at      |     started_at      | is_live |
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+
|  1 | toblerone.fritz.box:26257 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:13 | 2018-09-26 12:23:33 | true    |
|  2 | toblerone.fritz.box:26259 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:14 | 2018-09-26 12:23:44 | true    |
|  4 | toblerone.fritz.box:26263 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:15 | 2018-09-26 12:23:45 | true    |
|  5 | toblerone.fritz.box:26265 | v2.0.5-64-gf4ac7d47b3-dirty | 2018-09-26 12:26:16 | 2018-09-26 12:23:46 | true    |
+----+---------------------------+-----------------------------+---------------------+---------------------+---------+
(4 rows)
```

so perhaps it's really a small oversight on your end, @fat0? Please let me know, thanks!

**Comment by fat0** [comment] 2018-09-26 17:36
Good point re the cockroach version on the client. I am checking this again right now, will post update as soon as I find the results.

**Comment by tschottdorf** [comment] 2018-10-09 13:34
@fat0, any updates? Thanks!

**Comment by tschottdorf** [comment] 2018-10-11 09:08
I'm going to close this out as fixed, but let me know if you think otherwise, @fat0!

**Closed by tschottdorf** 2018-10-11 09:08 UTC
Labels: A-cli, C-bug, S-3-ux-surprise
