### ISSUE TITLE
docker: 20.2.2 errors out with * ERROR: [n3] Queued as error a755755e13c34eb4b1b042d4aa6b7ad3

### ISSUE THREAD

**Issue by robert-s-lee** [cockroachdb/cockroach#57873] opened 2020-12-13 00:47 UTC
**Describe the problem**

Followed instructions per https://www.cockroachlabs.com/docs/stable/start-a-local-cluster-in-docker-mac.html

With Version 20.1.0, 20.2.0 the Docker instructions work as expected.  **20.2.1 and 20.2.2 do not work**
 
**To Reproduce**

```
docker run -d --name=roach1 --hostname=roach1 --net=roachnet -p 26257:26257 -p 8080:8080  -v "${PWD}/cockroach-data/roach1:/cockroach/cockroach-data"  cockroachdb/cockroach:v20.2.2 start --insecure --join=roach1,roach2,roach3
docker run -d --name=roach2 --hostname=roach2 --net=roachnet -v "${PWD}/cockroach-data/roach2:/cockroach/cockroach-data" cockroachdb/cockroach:v20.2.2 start --insecure --join=roach1,roach2,roach3
docker run -d --name=roach3 --hostname=roach3 --net=roachnet -v "${PWD}/cockroach-data/roach3:/cockroach/cockroach-data" cockroachdb/cockroach:v20.2.2 start --insecure --join=roach1,roach2,roach3
docker exec -it roach1 ./cockroach init --insecure
Cluster successfully initialized
```

```
docker logs roach2
* ERROR: [n3] Queued as error a755755e13c34eb4b1b042d4aa6b7ad3
```
```
docker logs roach3
* ERROR: [n2] Queued as error 1d24dc1315034bdf8b3cb7956ad8aa3b
```

**Expected behavior**
Be able to start the cluster following the instructions

**Additional data / screenshots**

attaching 
- `tar -cvf - */logs/* | gzip > logs.tar.gz`
[logs.tar.gz](https://github.com/cockroachdb/cockroach/files/5684002/logs.tar.gz)

- admin UI screen <img width="1525" alt="Screen Shot 2020-12-12 at 7 37 46 PM" src="https://user-images.githubusercontent.com/6315124/102000128-00312c80-3cb2-11eb-8dec-141f8e41e36d.png">

**Environment:**
 - CockroachDB version [20.2.2]
 - Server OS: [Docker on OSX]
 - Client app [`cockroach sql`

**Additional context**
could not start the CRDB

**Comment by erikgrinaker** [comment] 2020-12-13 12:49
This is a dupe of #57192.

**Comment by knz** [comment] 2020-12-13 13:47
dup #57192 indeed

**Closed by knz** 2020-12-13 13:47 UTC
Labels: B-os-macos, C-test-failure
