### ISSUE TITLE
util/goschedstats,admission: evaluate CPU overload detection and response

### ISSUE THREAD

**Issue by ajwerner** [cockroachdb/cockroach#82702] opened 2022-06-10 01:26 UTC
**Is your feature request related to a problem? Please describe.**
Today's overload detection works by sampling the runqueue lengths of the go runtime (see https://github.com/cockroachdb/cockroach/pull/64149). We take a periodic measurement of the runnable goroutines. We use this instantaneous reading to decide whether the system is overloaded. This can be problematic because the queue length is going to be a high variance metric. Perhaps these goroutines are not going to run for very long. 

There's a note we should experiment with a smoother signal: https://github.com/cockroachdb/cockroach/blob/50649b6f7fe3df1aa6e5447bf5793258e6a3438c/pkg/util/admission/granter.go#L1480-L1481

One fundamental problem with this approach is that the average queue length which implies overload is workload dependent. One can contrive a go program whereby an average queue length of 2 per CPU means we're sorely overloaded:

```go
for i := 0; i < runtime.GOMAXPROCS * 3; i++ {
   go func() { bcrypt.GenerateFromPassword([]byte("foo"), 10) }() 
}
```

Cockroach sets the overload threshold to 10. This number is, unfortunately, both too high in some cases to detect sustained overload and too low in other cases such that patterns of burst lead to admission control decisions which seemingly ought not to be made.

**Describe the solution you'd like**

Another approach would be to instead of looking at queue length, look at the property we really care about: queuing delay. Indeed, the whole purpose of admission control is to eliminate substantial queuing delay in the go runtime and shift those scheduling decisions into our code. If there's no queuing delay, we're doing a good job and if there's substantial queuing delay, we're doing a bad job.

If we could cheaply measure queuing delay and base our overload signal on that queuing delay, then we could make better decisions. One could even imagine interpreting the signal as something other than binary. Rather fortunately, the go runtime gives us a measure of scheduling latency via its metrics package:

```
/sched/latencies:seconds
	Distribution of the time goroutines have spent in the scheduler
	in a runnable state before actually running.
```
https://pkg.go.dev/runtime/metrics

To compute the number of scheduling events cumulatively which took place in the last millisecond, one would need to sum up over 700 values. Maybe this is reasonable to do once a millisecond. One could then compute things like the longest a goroutine waited to be scheduled during the time interval. In terms of efficiency, one might be able to do better than summing up the whole tail of the distribution for the number of goroutines less than something. Perhaps one could find the highest bucket which experienced an increase over the interval. This would be akin to the max delay metric advocated in the [CoDel](https://queue.acm.org/detail.cfm?id=2209336) protocol.

If we find that the basic idea is sound, but the overhead of adding up all of those measurements is costly, it's not hard to imagine changing some parameters in the go runtime to produce smaller histograms which use wider buckets and a narrower range of values:
https://github.com/golang/go/blob/2cfbef438049fd4c3f73d1562773ad1f93900897/src/runtime/histogram.go#L54-L57

**Describe alternatives you've considered**
A potentially simpler approach would be to use a smoothed queue length metric. The problem with that approach is that it might make the system less responsive to short-term fluctuations. In order to compensate for the smoothing, one might want to increase the frequency. It seems very possible that running at a higher frequency on a higher core machines might make sense when combined with smoothing. At some point, timer efficiency at the runtime layer becomes a rather significant problem. Herein lies the rub: the sampling based approaches are not particularly robust to timer delays whereas the histogram deltas are.

**Additional context**
A lot of this issue is speculation. The first steps in doing anything about this will be to collect more information to validate the hypotheses and to experiment with the proposed solution. 

Jira issue: CRDB-16634

**Comment by sumeerbhola** [comment] 2022-06-10 18:13
Can you provide a reproducible CockroachDB experiment where this affects us? I am asking since there are a large number of things we can improve in admission control, and there are tradeoffs both in code complexity and behavior (e.g. as you mention about smoothing). Without something reproducible and representative, it's hard to justify making any changes.

**Comment by ajwerner** [comment] 2022-06-10 19:08
This is somewhat speculation. My sense is that there can be cases where there are large volumes of runnable goroutines but on average they run for very short amounts of time. If the average runtime is only in the 10 microseconds, we can happily have a queue of 100 and incur a delay of 1ms, which is arguably acceptable, or just at the edge of acceptable. We've seen scenarios with very large admission control latency due to waiting for slots with very poor average CPU utilization. My assumption, which might be poorly formed, is that this can only happen if we're making bad decisions on how to adjust slots. Right now we use an arbitrary threshold of 32. I can't see how that's a universally correct choice. 

I will admit that the reproducible scenario of poor utilization seem primarily a result of the failure to detect IO bandwidth overload, I just wouldn't expect to see a 75th percentile admission control delay in the 10s of over 100ms in this situation. Fixing the bandwidth exhaustion limit may make my immediate concerns melt away.

I'll leave this here for future readers and experimenters to consider, but for now, I have no intention of doing anything to prove whether or not this is a problem. 


<img width="737" alt="Screen Shot 2022-06-10 at 2 58 02 PM" src="https://user-images.githubusercontent.com/1839234/173133892-335dec8e-934d-4142-8028-7f23685b0a5f.png">
<img width="737" alt="Screen Shot 2022-06-10 at 2 40 02 PM" src="https://user-images.githubusercontent.com/1839234/173133895-6cf40248-563a-4ae3-afab-815b8c817ebc.png">

**Comment by sumeerbhola** [comment] 2023-10-02 18:41
Closing as a duplicate of https://github.com/cockroachdb/cockroach/issues/91536

**Closed by sumeerbhola** 2023-10-02 18:41 UTC
Labels: C-enhancement, A-admission-control, T-kv
