### ISSUE TITLE
sql: internal error distsql physical planning 

### ISSUE THREAD

**Issue by knz** [cockroachdb/cockroach#31673] opened 2018-10-20 16:09 UTC
**Describe the problem**

Found via the Hibernate test org.hibernate.test.subselect.SubselectTest.testCustomColumnReadAndWrite

Query fails with CodeInternalError

```
conflicting ColumnTypes: semantic_type:INT width:0 precision:0 visible_type:NONE  and semantic_type:INT width:64 precision:0 visible_type:BIGINT
```

**To Reproduce**

Extracting the statements from a SQL statement log:

```sql
CREATE TABLE humans (bid INT8 NOT NULL, name VARCHAR(255) NOT NULL, sex CHAR NOT NULL, address VARCHAR(255), height_centimeters FLOAT8 NOT NULL, PRIMARY KEY (bid));
CREATE TABLE aliens (bid INT8 NOT NULL, ident VARCHAR(255) NOT NULL, planet VARCHAR(255), species VARCHAR(255) NOT NULL, height_centimeters FLOAT8 NOT NULL, PRIMARY KEY (bid));

        select
            being0_.height_centimeters / 2.54E0 as col_0_0_
        from
            (     select
                bid,
                name as ident,
                address as loc,
                'human' as species,
                height_centimeters
            from
                humans
            union
            select
                bid,
                ident,
                planet as loc,
                species,
                height_centimeters
            from
                aliens
        ) being0_
    where
        being0_.ident='gavin';
```

**Comment by knz** [comment] 2018-10-20 16:09
Assigning Jordan for triage and prioritization.

**Comment by knz** [comment] 2018-10-20 16:11
Ditto with

```sql
        select
            being0_.bid as bid1_0_,
            being0_.ident as ident2_0_,
            being0_.loc as loc3_0_,
            being0_.species as species4_0_,
            being0_.height_centimeters / 2.54E0 as height_c5_0_
        from
            (     select
                bid,
                name as ident,
                address as loc,
                'human' as species,
                height_centimeters
            from
                humans
            union
            select
                bid,
                ident,
                planet as loc,
                species,
                height_centimeters
            from
                aliens
        ) being0_
```

**Comment by jordanlewis** [comment] 2018-10-24 03:41
```
github.com/cockroachdb/cockroach/pkg/sql/distsqlplan.MergeResultTypes(0xc421070b40, 0x5, 0x5, 0xc4210706c0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsqlplan/physical_plan.go:896 +0x2c0
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForSetOp(0xc420945200, 0xc4217ca8a0, 0xc42186c800, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2974 +0xfa9
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc420945200, 0xc4217ca8a0, 0x6b6cca0, 0xc42186c800, 0x0, 0x6530be0, 0xc420644000, 0x52d85f4, 0xc42107cf00, 0x81429e0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2370 +0x25db
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).createPlanForNode(0xc420945200, 0xc4217ca8a0, 0x6b6c660, 0xc4209b0420, 0x25, 0xc421c7aa10, 0x1, 0x1, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_physical_planner.go:2317 +0x11fd
github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun(0xc420945200, 0x6b7c360, 0xc421177590, 0xc42163e4b8, 0xc4217ca8a0, 0xc42126f050, 0x6b6c660, 0xc4209b0420, 0xc4217ac580)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:781 +0x126
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine(0xc42163e000, 0x6b7c360, 0xc421177590, 0xc42163e420, 0x3, 0xa1587e8, 0xc42126f0e0, 0x1, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:982 +0x27a
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine(0xc42163e000, 0x6b7c360, 0xc421177590, 0x6b7fa60, 0xc420d03180, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:824 +0xa96
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState(0xc42163e000, 0x6b7c360, 0xc421177590, 0x6b7fa60, 0xc420d03180, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:402 +0xb3b
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt(0xc42163e000, 0x6b7c360, 0xc421177590, 0x6b7fa60, 0xc420d03180, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:96 +0x341
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc42163e000, 0x6b7c2a0, 0xc4212f8c80, 0xc420a3a9d8, 0x5400, 0x15000, 0xc420a3aa70, 0xc4210285b0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1113 +0x21aa
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc420971950, 0x6b7c2a0, 0xc4212f8c80, 0xc42163e000, 0x5400, 0x15000, 0xc420a3aa70, 0xc4210285b0, 0x0, 0x0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:390 +0xce
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl.func4(0xc420971950, 0x6b7c2a0, 0xc4212f8c80, 0xc42163e000, 0x5400, 0x15000, 0xc420a3aa70, 0xc4210285b0, 0xc4210285c0, 0xc420362ce0)
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:309 +0x81
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).serveImpl
        /Users/jordan/go/src/github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:308 +0x107c
pq: conflicting ColumnTypes: semantic_type:INT width:0 precision:0 visible_type:NONE  and semantic_type:INT width:64 precision:0 visible_type:BIGINT
```

**Comment by jordanlewis** [comment] 2018-10-24 03:48
The problem is that during planning, we try to roundtrip a semantic type through its datum type and back. That is a lossy transformation.

**Comment by jordanlewis** [comment] 2019-05-06 18:33
Fixed via new type system stuff.

**Closed by jordanlewis** 2019-05-06 18:33 UTC
Labels: A-sql-execution, A-sql-hibernate, C-bug, S-3
