### ISSUE TITLE
DNS names used for inter-node communication despite --advertise-host=<ip-address>

### ISSUE THREAD

**Issue by jgehrcke** [cockroachdb/cockroach#41471] opened 2019-10-09 15:18 UTC
Seen with CockroachDB 2.1.8.

We ran into a problem where inter-node communication in CockroachDB took place via DNS names *despite* all nodes being configured with `--advertise-addr=<IP-address>`. 

We are now changing this to `--advertise-host`, as of:

```
--advertise-host | Deprecated. Use --advertise-addr instead.
```
(https://www.cockroachlabs.com/docs/v2.1/start-a-node.html)

Could it be that `--advertise-host` is not just deprecated but actually removed/disabled? If we are certain that it *should* behave the same as `--advertise-addr` (in CockroachDB 2.1.8) then I think we might have run into a rare issue as of which `--advertise-addr/--advertise-host` wasn't respected and/or didn't work as expected, probably non-deterministically. In that case, I think, it might be a serious bug (which can hit our production customers badly) and I hope you can maybe investigate a bit despite this thin bug report.

We cannot reproduce, a cluster started with the same config on equally set up nodes behaved "properly", using IP addresses for inter-node comms. 

By the way, the inter-node communication failed in our case when using DNS names because of the way our X.509 certificates are set up. Corresponding error messages:
```
grpc: addrConn.createTransport failed to connect to {
<dns-name>:26257 0  <nil>}..
```
(and then showing a hostname validation error). Our certificates are built under the assumption that inter-node communication takes place via IP addresses, so in our case it is *expected* that certificate verification fails when CockroachDB uses DNS names instead of IP addresses.

What follows is the command line of one of the CockroachDB instances in the cluster that showed the failure, just to "prove" that we indeed are configuring IP addresses only, and that we are indeed using `--advertise-host=<ip-address>`:
```
/opt/mesosphere/active/cockroach/bin/cockroach start --logtostderr --cache=100MiB --store=/var/lib/dcos/cockroach --certs-dir=/run/dcos/pki/cockroach --advertise-host=172.31.25.198 --host=172.31.25.198 --port=26257 --http-host=127.0.0.1 --http-port=8090 --log-dir= --pid-file=/run/dcos/cockroach/cockroach.pid --join=172.31.3.60,172.31.13.34,172.31.39.28,172.31.25.198
```

**To Reproduce**

Sorry, no repro.

**Comment by jongiddy** [comment] 2019-10-10 13:57
I looked into how this might happen. I didn't find the mechanism exactly, but the following might help track it down.

First, this comment is incorrect:
https://github.com/cockroachdb/cockroach/blob/a32985e6ceef99a0d0b8a42bed97d7d2a99a849b/pkg/cli/flags.go#L238

`cockroachCmd` is a parent of `startCmd`  so the `start` command also inherits this preexec and `extraClientFlagInit` is unexpectedly called for `cockroach start`
https://github.com/cockroachdb/cockroach/blob/a32985e6ceef99a0d0b8a42bed97d7d2a99a849b/pkg/cli/cli.go#L193

This means that `advertise-addr` can also be affected by the values of the client flags `-f`, `--file`, `--host`, `--url`, or by the values of the environment variables `COCKROACH_HOST` or `COCKROACH_URL`.

The fact that we are setting both `--host` and `--advertise-host` may cause unexpected behaviour. However, we set both of those values to IP addresses.

Hence, I suspect that the code conflicts in a way that causes `AdvertiseAddr` not to be set at all, allowing `os.Hostname` to provide the DNS name.
https://github.com/cockroachdb/cockroach/blob/1b525120c78ee8db16f8831830b6eac8728e9695/pkg/base/addr_validation.go#L173

**Comment by ricardocrdb** [comment] 2019-11-21 21:10
Hey @jgehrcke 

Are you still unable to repro this error? Let me know if you have any other questions.

**Comment by jgehrcke** [comment] 2019-11-22 19:04
@ricardocrdb I am not working on this anymore. But I think the lovely well-researched input provided by @jongiddy above should help understanding the actual problem, and provide a good idea about how to make things more robust.

**Comment by jordanlewis** [comment] 2020-11-10 18:50
Closing due to age.

**Closed by jordanlewis** 2020-11-10 18:50 UTC
