### ISSUE TITLE
beta-20160929

### ISSUE THREAD

**Issue by bdarnell** [cockroachdb/cockroach#9583] opened 2016-09-28 11:55 UTC
Gamma and delta are currently running commit 980c6fe. I don't think we want to release this one because it introduced a panic (#9575), although that panic has not been seen in production. We probably want to include the fix (#9578) when that is merged (or revert 980c6fe).

**Comment by petermattis** [comment] 2016-09-28 14:47
[Sounds like](https://github.com/cockroachdb/cockroach/pull/9578#issuecomment-250187751) like #9575 is a test-only panic.

**Comment by tschottdorf** [comment] 2016-09-28 15:03
I would want to have that confirmed conclusively by @RaduBerinde when he has fixed the test (and found no further issue after that), but I'm fairly certain at this point that that's how it is.

**Comment by knz** [comment] 2016-09-28 22:55
#9578 has been merged anyways.

**Comment by jseldess** [comment] 2016-09-29 15:08
Any updates on today's release? Should I finalize the release notes?

**Comment by RaduBerinde** [comment] 2016-09-29 15:38
With respect to the issue mentioned here, it's fine to release (the fix is in, but it's a test-only fix).

**Comment by tschottdorf** [comment] 2016-09-29 15:40
I think we're all good to go, though we have neglected this a bit this week. The clusters are running the current master and are looking good.

**Comment by tschottdorf** [comment] 2016-09-29 17:28
I'm starting the release process. The below has been added on master since ` 980c6fe`. We definitely want to pick up `4a5fc2932866bdedb523fcfb2691aa28094d2921` (report snapshot status) and the top one is harmless, so I designate 96fa76f49c83a5c9fce12ef6b15449e16442adbf (=master at the time of writing) the beta sha.

@jseldess let me know if you need help with any release notes that those potentially new PRs make necessary. 

```
commit 96fa76f49c83a5c9fce12ef6b15449e16442adbf
Merge: 4a5fc29 bd580db
Author: Cuong Do <cuongdo@users.noreply.github.com>
Date:   Thu Sep 29 13:10:41 2016 -0400

    Merge pull request #9615 from cuongdo/fix_terraform_0.7.4

    acceptance+cloud: fix for Terraform 0.7.4

commit 4a5fc2932866bdedb523fcfb2691aa28094d2921
Merge: 8dca72b b2018c6
Author: Jordan Lewis <jordanthelewis@gmail.com>
Date:   Wed Sep 28 16:44:37 2016 -0400

    Merge pull request #9606 from jordanlewis/report-snapshot-status

    storage: reinstate snapshot status reporting

commit 8dca72bc03d2385487342faf265d3096dd4d4138
Merge: cff14f7 18b9dbb
Author: RaduBerinde <radu@cockroachlabs.com>
Date:   Wed Sep 28 15:04:41 2016 -0400

    Merge pull request #9599 from RaduBerinde/update-tracing

    tracing: use the updated opentracing infrastructure

commit cff14f74e946420439140a6ed15957ffd4fdc298
Merge: f084c6b 3f4dec4
Author: RaduBerinde <radu@cockroachlabs.com>
Date:   Wed Sep 28 14:18:53 2016 -0400

    Merge pull request #9578 from RaduBerinde/fix-raft-ctx-crash

    storage: fix crash in TestLeaseConcurrent

commit f084c6b1961d6c047226012df8e676f5c5a95cf3
Merge: b0b2edb a35e122
Author: Andrei Matei <andreimatei1@gmail.com>
Date:   Wed Sep 28 12:39:15 2016 -0400

    Merge pull request #9581 from andreimatei/fix-testclustershim

    testutils: fix assertion for factory init

commit b0b2edb8c81569ffc354c8bd73085158bbb9ec0e
Merge: c51d8ba 9efcacb
Author: Bram Gruneir <BramGruneir@users.noreply.github.com>
Date:   Wed Sep 28 12:29:49 2016 -0400

    Merge pull request #9595 from BramGruneir/testcluster

    cherry-picked testcluster updates from develop -> master

commit c51d8ba7d50cc5879b6e65329a781c1c5a205075
Merge: cd73708 eda0783
Author: Alex Robinson <alexdwanerobinson@gmail.com>
Date:   Wed Sep 28 12:15:56 2016 -0400

    Merge pull request #9573 from a-robinson/httpaddr-master

    cli: Add http-host flag as first step of replacing http-addr

commit cd73708a5f8db9e35a493ed6a448d84392504300
Merge: 4d98421 9fc80cf
Author: Tamir Duberstein <tamird@gmail.com>
Date:   Wed Sep 28 11:28:52 2016 -0400

    Merge pull request #9590 from tamird/no-double-queues

    storage: remove asynchronous snapshot queues

commit 4d984211aedf1404b02ba8dead4b647f45154716
Merge: bd8df4a 4a86a7f
Author: Peter Mattis <peter@cockroachlabs.com>
Date:   Wed Sep 28 10:57:25 2016 -0400

    Merge pull request #9589 from petermattis/pmattis/send-snapshot-circuit-breaker

    storage: only fail circuit breaker on RPC errors

commit bd8df4a31bd7409555fe9c0f8155d5d1993c8dce
Merge: fcc0395 b202cd0
Author: Peter Mattis <peter@cockroachlabs.com>
Date:   Wed Sep 28 09:30:18 2016 -0400

    Merge pull request #9584 from petermattis/pmattis/raft-transport-client-dropped

    storage: increment clientDropped stat when circuit breaker is open

commit fcc0395c4861ad30074bca9f4c36dfab0a166933
Merge: aec8167 99f3749
Author: marc <marc.berhault@gmail.com>
Date:   Wed Sep 28 15:29:49 2016 +0200

    Merge pull request #9582 from cockroachdb/marc/add_fd_metrics

    Export file descriptor usage/limit.

commit aec8167cadfbbe7f6c168ce2fb0879de6f076d02
Merge: 8a03d34 4d8123a
Author: Peter Mattis <peter@cockroachlabs.com>
Date:   Wed Sep 28 08:36:38 2016 -0400

    Merge pull request #9550 from petermattis/pmattis/dont-campaign-after-split

    storage: don't campaign the RHS after splits

commit 8a03d342296c381cf5a80949d90075acb7fd3b7b
Merge: 7c04255 f6621f5
Author: kena <knz@users.noreply.github.com>
Date:   Tue Sep 27 16:18:33 2016 -0400

    Merge pull request #9571 from knz/monitor-gc

    stability: expose more GCQueue details

commit 7c04255b125d219388ac11f7b603541f1fcdfc12
Merge: 0fcbee0 8bb3226
Author: Alex Robinson <alexdwanerobinson@gmail.com>
Date:   Tue Sep 27 12:53:41 2016 -0400

    Merge pull request #9503 from a-robinson/advert-master

    cli: Add advertise-host flag to start command

commit 0fcbee0d45860ebc7e3dead9ea488b3f076d8c7e
Merge: 324fc58 b4acd5b
Author: mrtracy <matt@cockroachlabs.com>
Date:   Tue Sep 27 11:58:51 2016 -0400

    Merge pull request #9343 from mrtracy/mtracy/time_series_culling

    RFC: Time Series Culling
```

**Comment by jseldess** [comment] 2016-09-29 17:37
Thanks, @tschottdorf. It'd be a huge help if you could write up a line for each of these. You can just add a comment to this PR: https://github.com/cockroachdb/docs/pull/701

**Comment by tschottdorf** [comment] 2016-09-29 17:48
Done. I'm waiting for teamcity to hopefully build the binary; assuming all goes well I'll update the release instructions (which rotted and still assume CircleCI does it).

**Comment by tschottdorf** [comment] 2016-09-29 17:51
Teamcity seems to do what I want. I updated the instructions.

**Comment by tschottdorf** [comment] 2016-09-29 18:22
Binary is baked and was verified.

**Comment by tschottdorf** [comment] 2016-09-29 18:31
```
@:26257> INSERT INTO registration.versions (version, details) VALUES ('beta-20160929', 'https://www.cockroachlabs.com/docs/beta-20160929.html');
INSERT 1
```

I believe that's all we need to do mod releasing it officially.

**Closed** 2016-10-05 16:01 UTC
