### ISSUE TITLE
Restore geo partitioned data with enterprise backup and restore

### ISSUE THREAD

**Issue by Marko2202** [cockroachdb/cockroach#42108] opened 2019-11-01 09:55 UTC
**Describe the problem**

Enerprise database backup and restore doesn't honor table partitioning

**To Reproduce**

1. Create a database and a table with geo partitioned rows
2. Verify the location of data with: SHOW RANGE FROM TABLE ${TABLE_NAME} FOR ROW ($ROW) (this outputs the desired replica_localities)
3. Backup a database with: BACKUP DATABASE
4. Drop the database
5. Restore the database with: RESTORE DATABASE
6. Verify the location of data with: SHOW RANGE FROM TABLE ${TABLE_NAME} FOR ROW ($ROW). Now all the rows in the table are distributed (not geo partitioned)

**Expected behavior**
After an enterprise RESTORE the data is distributed the same way it was when backed up.

**Environment:**
 - CockroachDB version v19.2.0-rc.2
 - Server OS: Ubuntu 18.04
 - Client app: cockroach sql

**Comment by ricardocrdb** [comment] 2019-11-21 21:12
Hey @Marko2202 

Apologies for the delayed response. Have you attempted to perform the same backup steps on the 19.2? Can you reproduce using the latest release of 19.2? Let me know if you have any questions.

**Comment by Marko2202** [comment] 2019-11-22 13:55
I have tested it now with 19.2.0 and the issue still persist

If one have used the ALTER PARTITION primary_idx_database_partition_5 OF INDEX ..... CONFIGURE ZONE USING constraints = '[+region=europe-west1]'
this information is lost in the backup

**Comment by Marko2202** [comment] 2019-11-25 07:12
The same thing happens on 19.2.0.
We partition our tables with statements like:

ALTER PARTITION created_idx_database_partition_0 OF INDEX db.table@created_idx CONFIGURE ZONE USING constraints = '[+region=europe-west1]'

This information is lost during backup (or restore).

**Comment by Marko2202** [comment] 2019-12-19 06:42
Is anybody looking at this?

**Comment by mwang1026** [comment] 2020-02-11 15:29
Database and table backups don't preserve zone configurations, so when you restore the backup it will restore as if the zone configurations weren't applied.

One workaround is to kick off `RESTORE`, immediately pause the `RESTORE`, apply the zone configs, and then resume `RESTORE`. In this case it will restore respecting the zone configs.

In 20.1, with Full Cluster Backup and Restore, we'll be saving zone configurations to the backup and those zone configurations will be applied when you do a full cluster restore. https://github.com/cockroachdb/cockroach/issues/44814

**Comment by mwang1026** [comment] 2021-06-07 20:45
Closing due to the functionality in CLUSTER level restore. Feel free to open if that is insufficient. https://www.cockroachlabs.com/docs/v21.1/restore.html#full-cluster

**Closed by mwang1026** 2021-06-07 20:45 UTC
Labels: A-bulkio, T-bulkio
